### ISSUE TITLE
Opacity clips SingleChildScrollView content

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#101110] opened 2022-03-31 11:20 UTC
Setting `opacity` to any value other than `1.0` or `0.0` clips the `Column` inside `SingleChildScrollView` by the scroll `offset`.

This is a regression. It works fine with Flutter `stable, 2.10.4` but is broken on `master, 2.13.0-0.0.pre.333` 

## Steps to Reproduce

Run the example code

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Bug101110());
}

/// https://github.com/flutter/flutter/issues/101110
class Bug101110 extends StatefulWidget {
  const Bug101110({Key? key}) : super(key: key);

  @override
  State<Bug101110> createState() => _Bug101110State();
}

class _Bug101110State extends State<Bug101110> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        child: Opacity(
          // opacity: 1.0, // works
          opacity: 0.5, // clips Column when scrolling
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                color: Colors.green,
                height: 300,
              ),
              Container(
                color: Colors.red,
                height: 300,
              ),
              Container(
                color: Colors.blue,
                height: 300,
              ),
              Container(
                color: Colors.yellow,
                height: 300,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

Broken with `opacity: 0.5`

![Screen-Recording-2022-03-31-13-06-15](https://user-images.githubusercontent.com/1096485/161043292-c016bd6e-d438-422c-be66-999796d31c68.gif)
[video](https://user-images.githubusercontent.com/1096485/161042485-4ee0782a-b726-4177-bd54-15e693cf9162.mp4)

Working with `opacity: 1.0`

![Screen-Recording-2022-03-31-13-00-00](https://user-images.githubusercontent.com/1096485/161043277-81ca1cd5-86d8-4070-b3bb-7adce6dc8df5.gif)
[video](https://user-images.githubusercontent.com/1096485/161042797-33d1f1d0-51aa-4b0d-b33a-886d41f912bc.mp4)

**Expected results:** Column should be 50% transparent and fully visible

**Actual results:** Column is 50% transparent but clips the children at the bottom when scrolling (yellow box only partially visible)

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.333, on macOS 12.1 21C52 darwin-arm, locale en-DE)
    • Flutter version 2.13.0-0.0.pre.333 at /opt/homebrew/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9bd04bd03a (2 hours ago), 2022-03-31 05:35:09 -0400
    • Engine revision e4f9ee1d7c
    • Dart version 2.17.0 (build 2.17.0-251.0.dev)
    • DevTools version 2.11.4
```

</details>

**Comment by danagbemava-nc** [comment] 2022-03-31 13:14
Hi @passsy, thanks for reporting this. 

This seems like a fairly recent regression as I cannot reproduce on `master, 2.13.0-0.0.pre.330` but I can reproduce on `master, 2.13.0-0.0.pre.334`.

Reproducible using code sample provided above. 

<details>
<summary>videos</summary>

| 2.13.0-0.0.pre.330 | 2.13.0-0.0.pre.334 |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/161058175-8aad5a1f-af30-459f-aade-7ac12d0e24f2.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/161058160-58d6805c-f16a-46d2-b66f-481d12444d23.mov" /> | 

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (6 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.330, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.330 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e77d3ef48 (6 hours ago), 2022-03-31 00:40:09 -0400
    • Engine revision 14d728777e
    • Dart version 2.17.0 (build 2.17.0-251.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.334, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.334 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d0bef4a49a (20 minutes ago), 2022-03-31 08:20:11 -0400
    • Engine revision 94be30a8a3
    • Dart version 2.17.0 (build 2.17.0-258.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by jason-simmons** [comment] 2022-04-02 01:19
This was introduced in https://github.com/flutter/engine/commit/be7fffa8cf1d740114691639dbdb7d78ace748ac, which was later reverted (https://github.com/flutter/engine/commit/503cc732413a594ea2ba4f9a5a28a68095e3558a)

The new version of that PR does not have this issue (https://github.com/flutter/engine/pull/32378)

**Comment by TheJulianJES** [comment] 2022-04-02 01:25
Possibly unrelated, but could https://github.com/flutter/engine/commit/be7fffa8cf1d740114691639dbdb7d78ace748ac also have broken ExpansionPanels? -> https://github.com/flutter/flutter/issues/101146 (so same issue at this?)

**Comment by jason-simmons** [comment] 2022-04-02 01:40
Yes - https://github.com/flutter/flutter/issues/101146 is the same issue

**Comment by danagbemava-nc** [comment] 2022-04-04 06:38
Hi @passsy, given that the pr that caused the regression has been reverted and I can no longer reproduce this issue on the latest version of master (see video below). I'm going to close this as fixed. Thank you

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/161486907-dadeea69-8b36-4fc4-99b2-b358a5c42306.mov
</details>

**Closed by danagbemava-nc** 2022-04-04 06:38 UTC
Labels: severe: regression, framework, engine, f: scrolling, severe: rendering, has reproducible steps, found in release: 2.13
