### ISSUE TITLE
Invalid argument(s): string is not well-formed UTF-16

### ISSUE THREAD

**Issue by wakandan** [flutter/flutter#52306] opened 2020-03-10 06:43 UTC
## Steps to Reproduce

Passing a string with emoji into Text widget crashes flutter. Is there a way to santinize the text so that flutter rendering is not affected? I searched around and there's not a way to do it yet, so I'm leaning toward just try to render the text anyway and if flutter throws error then just ignore the text entirely instead of trying to deal with it. However my code like this doesn't seem to work

```
var para = ParagraphBuilder(ParagraphStyle());
para.addText(title);
para.build();
print(para);
```

Here's the text (title) in question 'Đấy, nhà có 3 anh em mà chơi thiếu đoàn kết quá bảo sao thằng nhỏ hông giận. 😗😗😗'

```
[        ] I/flutter ( 2937): The following ArgumentError was thrown during performLayout():
[   +7 ms] I/flutter ( 2937): Invalid argument(s): string is not well-formed UTF-16
[        ] I/flutter ( 2937): 
[        ] I/flutter ( 2937): The relevant error-causing widget was:
[        ] I/flutter ( 2937):   Text file:///Users/kdang/Documents/vietgag/lib/screens/main_screen.dart:490:24
[        ] I/flutter ( 2937): 
[   +7 ms] I/flutter ( 2937): When the exception was thrown, this was the stack:
[   +4 ms] I/flutter ( 2937): #0      ParagraphBuilder.addText (dart:ui/text.dart:2041:7)
[        ] I/flutter ( 2937): #1      TextSpan.build (package:flutter/src/painting/text_span.dart:207:15)
[        ] I/flutter ( 2937): #2      TextPainter.layout (package:flutter/src/painting/text_painter.dart:544:13)
[        ] I/flutter ( 2937): #3      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:477:18)
[        ] I/flutter ( 2937): #4      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:500:5)
[        ] I/flutter ( 2937): #5      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:567:5)
[        ] I/flutter ( 2937): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[        ] I/flutter ( 2937): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #9      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] I/flutter ( 2937): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
[        ] I/flutter ( 2937): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[   +7 ms] I/flutter ( 2937): #13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] I/flutter ( 2937): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #17     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
[        ] I/flutter ( 2937): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[  +15 ms] I/flutter ( 2937): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[        ] I/flutter ( 2937): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[  +22 ms] I/flutter ( 2937): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter ( 2937): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #36     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
[  +19 ms] I/flutter ( 2937): #37     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
[        ] I/flutter ( 2937): #38     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:220:19)
[        ] I/flutter ( 2937): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #40     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
[        ] I/flutter ( 2937): #41     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
[        ] I/flutter ( 2937): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter ( 2937): #43     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
[  +11 ms] I/flutter ( 2937): #44     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
[        ] I/flutter ( 2937): #45     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
[        ] I/flutter ( 2937): #46     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
[        ] I/flutter ( 2937): #47     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] I/flutter ( 2937): #48     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
[        ] I/flutter ( 2937): #49     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
[        ] I/flutter ( 2937): #50     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[        ] I/flutter ( 2937): #51     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[   +9 ms] I/flutter ( 2937): #52     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] I/flutter ( 2937): #53     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
[        ] I/flutter ( 2937): #57     _invoke (dart:ui/hooks.dart:259:10)
[        ] I/flutter ( 2937): #58     _drawFrame (dart:ui/hooks.dart:217:3)
[        ] I/flutter ( 2937): (elided 3 frames from package dart:async)
[        ] I/flutter ( 2937): 
[        ] I/flutter ( 2937): The following RenderObject was being processed when the exception was fired: RenderParagraph#1e737 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT:
[        ] I/flutter ( 2937):   creator: RichText ← Text ← ConstrainedBox ← Container ← Padding ← Row ← Padding ← DecoratedBox ←
[        ] I/flutter ( 2937):     Container ← Column ← Semantics ← DefaultTextStyle ← ⋯
[  +11 ms] I/flutter ( 2937):   parentData: <none> (can use size)
[        ] I/flutter ( 2937):   constraints: BoxConstraints(w=353.5, 0.0<=h<=Infinity)
[        ] I/flutter ( 2937):   size: MISSING
[        ] I/flutter ( 2937):   textAlign: start
[        ] I/flutter ( 2937):   textDirection: ltr
[        ] I/flutter ( 2937):   softWrap: wrapping at box width
[        ] I/flutter ( 2937):   overflow: clip
[        ] I/flutter ( 2937):   locale: en_US
[        ] I/flutter ( 2937):   maxLines: unlimited
[        ] I/flutter ( 2937): This RenderObject had the following child:
[        ] I/flutter ( 2937):     text: TextSpan
[        ] I/flutter ( 2937): ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +7 ms] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderParagraph#1e737 relayoutBoundary=up17 NEEDS-PAINT
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#47a2e relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderPadding#9eaec relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderFlex#eaf30 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderPadding#c3e10 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#72d3d relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[   +3 ms] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderFlex#38609 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#082a4 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#1342a relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#97086 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#58395 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderPadding#0263e relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#f6325 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d823a relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 2937): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
[ +200 ms] I/flutter ( 2937): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
[        ] I/flutter ( 2937): Another exception was thrown: RenderBox was not laid out: RenderIndexedSemantics#c1a06 relayoutBoundary=up3 NEEDS-PAINT
[   +3 ms] I/flutter ( 2937): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.

```

```
Analyzing vietgag...                                                    

   info • Prefer using /// for doc comments • lib/business/auth.dart:106:3 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/business/posts.dart:44:3 • slash_for_doc_comments
   info • Unused import: 'package:firebase_analytics/firebase_analytics.dart' • lib/screens/loading_screen.dart:1:8 • unused_import
   info • Unused import: 'package:flutter/scheduler.dart' • lib/screens/loading_screen.dart:4:8 • unused_import
   info • Unused import: 'package:localstorage/localstorage.dart' • lib/screens/main_screen.dart:13:8 • unused_import
   info • Avoid using braces in interpolation when not needed • lib/screens/main_screen.dart:73:49 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/screens/main_screen.dart:81:49 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/screens/main_screen.dart:459:44 • unnecessary_brace_in_string_interps
   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/screens/sign_in_screen.dart:4:8 • unused_import
   info • Unused import: 'package:flutter/gestures.dart' • lib/screens/sign_in_screen.dart:7:8 • unused_import
   info • Unused import: 'package:flutter_auth_buttons/flutter_auth_buttons.dart' • lib/screens/sign_in_screen.dart:10:8 • unused_import
   info • Unnecessary cast • lib/screens/sign_in_screen.dart:395:19 • unnecessary_cast

12 issues found. (ran in 6.4s)

```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.5 18F132, locale en-VN)
    • Flutter version 1.12.13+hotfix.7 at /Users/kdang/development/flutter
    • Framework revision 9f5ff2306b (6 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kdang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/kdang/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/kdang/Library/Android/sdk
    • Java binary at: /Users/kdang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6200805/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/kdang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6200805/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Users/kdang/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

~/Documents/vietgag change-android-app-id* 10s
(base) ❯ 

```

**Comment by wakandan** [comment] 2020-03-10 06:49
my problem is similar to this issue https://github.com/flutter/flutter/issues/43302

**Comment by TahaTesser** [comment] 2020-03-10 08:40
Hi @wakandan 

Please check out this [DartPad Code Sample](https://dartpad.dev/43168709ecc4776b09ec8441fccba792)
Notice the console, can't reproduce this error 

Thank you

**Comment by jason-simmons** [comment] 2020-03-19 00:01
Strings given to the text layout engine must be valid UTF-16.

Try representing the emoji as a Unicode escape sequence: `'\u{1F617}'`

**Comment by TahaTesser** [comment] 2020-04-03 09:12
Hi @wakandan 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-03 09:12 UTC
Labels: in triage, waiting for customer response
