### ISSUE TITLE
Cannot install any audio plugin but other plugins are being installed fine

### ISSUE THREAD

**Issue by realdiganta** [flutter/flutter#62066] opened 2020-07-22 21:10 UTC
When I add any audio plugin to pubspec.yaml file and click on Pub Get, the terminal keeps on loading for eternity and never finishes loading. But if the remove the audio plugin and then Run Pub Get again, it works fine.

I tried with the following audio plugins : audioplayers, chewie_audio,  just_audio

I am really confused. Why are only audio plugins not being installed? I tried the video_player plugin and it installed fine. The problem is only the audio player plugins. But why

The outputs of running flutter doctor -v are pasted below:

✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_IN)
    • Flutter version 1.18.0-11.1.pre at /home/realdiganta/flutter
    • Framework revision 2738a1148b (2 months ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/realdiganta/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/realdiganta/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /home/realdiganta/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2020-07-23 08:48
Hi @realdiganta 
From what I can see, the issue is related to `pub` rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-23 08:48 UTC

**Comment by realdiganta** [comment] 2020-07-24 19:33
No, you are right. Thanks for guiding me to the correct repo
