### ISSUE TITLE
Placeholder order error in generated Dart file for i18n when using "price" as first parameter

### ISSUE THREAD

**Issue by gaogq3** [flutter/flutter#149394] opened 2024-05-31 08:01 UTC
## Description
I've encountered an issue with the Flutter i18n process where the order of placeholders in the generated Dart file does not match the order defined in the arb file. Specifically, when I use "price" as the first placeholder in an arb file, the generated Dart file incorrectly positions "price" as the second parameter in the getter method.

### Steps to Reproduce
1. Define a string with placeholders in an arb file, with "price" as the first placeholder.
![image](https://github.com/cfug/flutter.cn/assets/30523358/80a73233-30e1-472f-ba1d-d18ca88d07ff)

2. Run flutter run to generate the Dart file from the arb file.
3. Observe the generated Dart file.

![image](https://github.com/cfug/flutter.cn/assets/30523358/ae47ae8b-6b93-49df-bd35-353a137676ce)

### Expected results

The generated Dart file should have a method signature that matches the order of placeholders in the arb file:

`String specialFun(Object price, Object number){//...}`

### Actual results

The generated Dart file has the "price" placeholder as the second parameter instead of the first:

`String specialFun(Object number, Object price){//...}`

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.16.2, on macOS 13.5 22G74 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.2 on channel stable at /Users/leo.gao2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 months ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/leo.gao2/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

```

</details>

**Comment by huycozy** [comment] 2024-05-31 10:51
Hi @gaogq3, this is a known issue at https://github.com/flutter/flutter/issues/116308 and it has been solved with new parameter `--use-named-parameters`, see https://github.com/flutter/flutter/pull/138663. 

Closing as a duplicate of https://github.com/flutter/flutter/issues/116308.

**Closed by huycozy** 2024-05-31 10:51 UTC
Labels: in triage
