### ISSUE TITLE
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 769 pos 16: 'extra >= 0.0': is not true.

### ISSUE THREAD

**Issue by hachem9** [flutter/flutter#138744] opened 2023-11-20 19:41 UTC
```
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 769 pos 16: 'extra >= 0.0': is not true.
nested_scroll_view.dart:769
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _NestedScrollCoordinator._getMetrics
nested_scroll_view.dart:769
#3      _NestedScrollCoordinator.createOuterBallisticScrollActivity
nested_scroll_view.dart:725
2      _NestedScrollCoordinator._getMetrics
nested_scroll_view.dart:769
#3      _NestedScrollCoordinator.createOuterBallisticScrollActivity
nested_scroll_view.dart:725
#4      _NestedScrollCoordinator.goBallistic
nested_scroll_view.dart:673
#5      ScrollDragController.end
scroll_activity.dart:411
#6      ScrollableState._handleDragEnd
scrollable.dart:751
#7      DragGestureRecognizer._checkEnd.<anonymous closure>
monodrag.dart:540
#8      GestureRecognizer.invokeCallback
recognizer.dart:275
#9      DragGestureRecognizer._checkEnd
monodrag.dart:540
#10     DragGestureRecognizer.didStopTrackingLastPointer
monodrag.dart:463
#11     OneSequenceGestureRecognizer.stopTrackingPointer
recognizer.dart:465
#12     DragGestureRecognizer._giveUpPointer
monodrag.dart:471
#13     DragGestureRecognizer.handleEvent
monodrag.dart:394
#14     PointerRouter._dispatch
pointer_router.dart:98
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#17     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#18     PointerRouter.route
pointer_router.dart:127
#19     GestureBinding.handleEvent
binding.dart:465
#20     GestureBinding.dispatchEvent
binding.dart:445
#21     RendererBinding.dispatchEvent
binding.dart:331
#22     GestureBinding._handlePointerEventImmediately
binding.dart:400
#23     GestureBinding.handlePointerEvent
binding.dart:363
#24     GestureBinding._flushPointerEventQueue
binding.dart:320
#25     GestureBinding._handlePointerDataPacket
binding.dart:293
#26     _invoke1 (dart:ui/hooks.dart:158:13)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#a3777
  start behavior: start
```

**Comment by dam-ease** [comment] 2023-11-21 08:44
Hi @hachem9 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-11-21 08:44 UTC
Labels: in triage
