### ISSUE TITLE
Flutter web mouse tracking issue

### ISSUE THREAD

**Issue by xrgouda** [flutter/flutter#46658] opened 2019-12-10 05:10 UTC
How to solve this problem in flutter web?

```bash
The following assertion was thrown while routing a pointer event:
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
(targetState == null) == (targetEvent is PointerAddedEvent)
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
package:flutter/src/gestures/mouse_tracking.dart 388:51                                                                                                                 [_updateDevices]
package:flutter/src/gestures/mouse_tracking.dart 292:5                                                                                                                  [_handleEvent]
package:flutter/src/gestures/pointer_router.dart 76:12                                                                                                                  [_dispatch]
package:flutter/src/gestures/pointer_router.dart 117:9                                                                                                                  <fn>
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 23:13      forEach
package:flutter/src/gestures/pointer_router.dart 115:17                                                                                                                 [_dispatchEventToRoutes]
package:flutter/src/gestures/pointer_router.dart 107:5                                                                                                                  route
package:flutter/src/gestures/binding.dart 180:23                                                                                                                        dispatchEvent
package:flutter/src/gestures/binding.dart 156:7                                                                                                                         [_handlePointerEvent]
package:flutter/src/gestures/binding.dart 102:7                                                                                                                         [_flushPointerEventQueue]
package:flutter/src/gestures/binding.dart 72:5                                                                                                                          unlocked
package:flutter/src/scheduler/binding.dart 417:11                                                                                                                       unlocked
package:flutter/src/foundation/binding.dart 228:9                                                                                                                       <fn>
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1376:54                                          run
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 164:18                                    handleWhenComplete
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 652:38                                    handleWhenCompleteCallback
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 708:37                                    _propagateToListeners
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 526:5                                     [_completeWithValue]
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 556:7                                     callback
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 43:11                              _microtaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 52:5                               _startMicrotaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15           <fn>

Event:
PointerHoverEvent#80a45(position: Offset(784.0, 512.0), delta: Offset(-2.0, 0.0), timeStamp:
0:00:08.723370, pointer: 0, kind: mouse, device: 1, down: false, pressure: 0.0, pressureMin: 0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14

```

**Comment by iapicca** [comment] 2019-12-10 11:34
Hi @xrgouda 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by moodstubos** [comment] 2019-12-13 15:15
code sample:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(      
      home: GestureDetector(
        onTap: () => print("onTap"),
        onTapUp: (_) => print("onTapUp"),
        onTapDown: (_) => print("onTapDown"),
        onScaleStart: (_) => print("onScaleStart"),
        onScaleUpdate: (_) => print("onScaleUpdate"),
        child: Container(color: Colors.green),
      ),
    );
  }
}
```

1) Just move/drag/click in the app
2) go back to vscode and hot reload
3) repeat 1) + 2) for some time

result:

> ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
> The following assertion was thrown while routing a pointer event:
> Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
> (targetState == null) == (targetEvent is PointerAddedEvent)
> is not true
> Either the assertion indicates an error in the framework itself, or we should provide substantially
> more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
> https://github.com/flutter/flutter/issues/new?template=BUG.md
> When the exception was thrown, this was the stack:
> throw_ (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:196:49)
> assertFailed (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:26:3)
> [_updateDevices]
> package:flutter/…/gestures/mouse_tracking.dart:388
> [_handleEvent]
> package:flutter/…/gestures/mouse_tracking.dart:292
> [_dispatch]
> package:flutter/…/gestures/pointer_router.dart:76
> <fn>
> package:flutter/…/gestures/pointer_router.dart:117

doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.19041.1], locale de-DE)
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Chrome - develop for the web
> [√] Android Studio (version 3.5)
> [√] VS Code (version 1.40.2)
> [√] Connected device (2 available)
> 
> • No issues found!

**Comment by dkwingsmt** [comment] 2020-01-03 22:15
This issue should have been solved in https://github.com/flutter/flutter/pull/46285, which is landed since v1.13.1. Can you try the latest dev?

**Comment by mdebbar** [comment] 2020-01-06 18:43
I'm unable to repro this issue on master. You saw the issue on `v1.13.0` (according to the `flutter doctor -v` output) so let me try that one and see if I can repro.

**Comment by mdebbar** [comment] 2020-01-06 18:54
I confirm this issue is reproducible in older version of flutter (e.g. `v1.13.0`). @dkwingsmt's PR should've fixed it though. @xrgouda @moodstubos please upgrade your flutter version and reopen this issue if you are still able to reproduce it.

**Closed by mdebbar** 2020-01-06 18:54 UTC
Labels: customer: crowd, f: gestures, framework, ☸ platform-web

**Comment by andrea689** [comment] 2020-01-16 11:30
Hi, I have the same problem when from a page with a plugin that use `PlatformView`, I go to another page and go back to previous page.

This is a simple example with use of `video_player`, but I experienced this with other plugin also:
https://github.com/andrea689/flutter_mouse_tracking_issue

doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.1-pre.23, on Mac OS X 10.14.6 18G1012, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by andrea689** [comment] 2020-01-29 12:45
Any news? I think you should reopen this issue.

**Comment by dkwingsmt** [comment] 2020-01-29 17:23
@andrea689 A fix has been merged yesterday. Can you try again with the latest master?

**Comment by andrea689** [comment] 2020-01-29 17:45
@dkwingsmt I confirm that the problem is resolved! Thank you!

**Comment by iapicca** [comment] 2020-02-06 07:39
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
