### ISSUE TITLE
Unable to launch app on ios simulator

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#21335] opened 2018-09-02 09:25 UTC
## Steps to Reproduce

1. flutter channel master
2. flutter upgrade
3. flutter run

## Logs

```
flutter run

Launching lib/main.dart on iPhone 7 in debug mode...
Starting Xcode build...
Xcode build done.
Exit code 1 from: /usr/bin/xcrun simctl launch 1D5215F2-841E-49BF-8D2A-F982A94BD31F "com.orgname.app" --enable-dart-profiling --enable-checked-mode --observatory-port=0:
"com.orgname.app": -1

An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open ""com.orgname.app"" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application ""com.orgname.app"" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application ""com.orgname.app"" is unknown to FrontBoard.
	Application ""com.orgname.app"" is unknown to FrontBoard.
Error launching application on iPhone 7.
```

```
flutter doctor -v

[✓] Flutter (Channel master, v0.7.6-pre.20, on Mac OS X 10.13.6 17G65, locale de-DE)
    • Flutter version 0.7.6-pre.20 at /Users/chris/Development/flutter
    • Framework revision 457e7b23df (22 hours ago), 2018-09-01 04:06:46 -0700
    • Engine revision 017dafd426
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Users/chris/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • iPhone 7 • 1D5215F2-841E-49BF-8D2A-F982A94BD31F • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment] 2018-09-02 10:09
I found https://stackoverflow.com/questions/46384321/react-native-run-ios-doesnt-run-application-is-unknown-to-frontboard
Searching "Application is unknown to FrontBoard" in Google provides more results. I just posted the first.

**Comment by christian-muertz** [comment] 2018-09-02 11:08
I can launch the app through xCode 9 but not via flutter run. Switching back to the beta branch fixes the problem. So the problem seems to be with the master.

**Comment by zoechi** [comment] 2018-09-02 11:13
Just to be sure. Did you try `flutter clean`?

**Comment by david-schopf** [comment] 2018-09-02 20:48
I have exactly the same problem! Xcode build & run works, but flutter run does not start the app on the device.

$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                       3,8s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    5,3s                                                                                                                                       
 └─Compiling, linking and signing...                  8,6s                                                                                                                                       
Xcode build done.                                           18,4s
Exit code 1 from: /usr/bin/xcrun simctl launch 10B93E7C-1CE7-40DF-A3BA-12BBB010F3E0 "de.org.app" --enable-dart-profiling --enable-checked-mode --observatory-port=0:
"de.org.app": -1

An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open ""de.org.app"" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application ""de.org.app"" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
        The operation couldn’t be completed. Application ""de.org.app"" is unknown to FrontBoard.
        Application ""de.org.app"" is unknown to FrontBoard.
Error launching application on iPhone X.

**Flutter Doctor:**

$ flutter doctor -v
[✓] Flutter (Channel master, v0.7.6-pre.23, on Mac OS X 10.13.6 17G65, locale de-DE)
    • Flutter version 0.7.6-pre.23 at /Users/dschopf/dev/flutter
    • Framework revision 6678efecba (2 hours ago), 2018-09-02 14:30:34 -0400
    • Engine revision 949fb0fb4c
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /usr/local/Cellar/android-sdk/24.4.1_1
    • Android NDK at /usr/local/Cellar/android-sdk/24.4.1_1/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /usr/local/Cellar/android-sdk/24.4.1_1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    • IntelliJ at /Users/dschopf/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 10B93E7C-1CE7-40DF-A3BA-12BBB010F3E0 • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by jasnig** [comment] 2018-09-04 08:18
meeting the same problem

**Comment by christian-muertz** [comment] 2018-09-10 18:04
Any update on this?

**Comment by jeroen-meijer** [comment] 2018-09-20 17:17
Still a problem on some projects on beta.

**Comment by matthewtsmith** [comment] 2018-09-21 16:31
We have run into this as well. It looks to me that it has to do with using different bundleIds. 

We have 3 flavors in our app, each with their own Info.plist file. There is also a Info.plist file inside of the Runner directory that has a CFBundleIdentifier of $(PRODUCT_BUNDLE_IDENTIFIER) set.

On 0.7.3 this worked fine. The $(PRODUCT_BUNDLE_IDENTIFIER) would get set based on the flavor that was chosen. It would correctly find the correct bundleId based on the build scheme and build the app.

I tried running `flutter run --verbose` and noticed that it was picking up a bundleId that was not from the flavor I was currently trying to run. However, it would **build** the correct bundleId. It seems that the simulator commands to kill the process and launch the app are using the wrong bundleId but the build is using the correct one.

Here is what I noticed from the output of `flutter run --verbose`

```
[+1087 ms] Launching lib/main.dart on iPhone X in debug mode...
[  +11 ms] executing: /usr/bin/defaults read /Users/matthew/Projects/AppTree/revolution/mobile_client/ios/Runner/Info CFBundleIdentifier
[  +77 ms] Exit code 0 from: /usr/bin/defaults read /Users/matthew/Projects/AppTree/revolution/mobile_client/ios/Runner/Info CFBundleIdentifier
[        ] $(PRODUCT_BUNDLE_IDENTIFIER)
[  +15 ms] Building Runner.app for BF0A1B4B-FAFC-4943-9EF6-486FDF5E958E.
[  +14 ms] executing: script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "BF0A1B4B-FAFC-4943-9EF6-486FDF5E958E"
[ +110 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS "BF0A1B4B-FAFC-4943-9EF6-486FDF5E958E""
[   +6 ms] [DEVICE LOG] Timestamp                       (process)[PID]
[ +292 ms] Skipping kernel compilation. Fingerprint match.
[+1074 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[ +146 ms] Wrote build/flutter_assets
[   +1 ms] executing: /usr/bin/xcrun simctl get_app_container BF0A1B4B-FAFC-4943-9EF6-486FDF5E958E com.apptreesoftware.accruent.famis
```

This line ` /usr/bin/defaults read /Users/matthew/Projects/AppTree/revolution/mobile_client/ios/Runner/Info CFBundleIdentifier`
is reading the Info.plist from the Runner folder which has a value of ` $(PRODUCT_BUNDLE_IDENTIFIER)`

For some reason,  $(PRODUCT_BUNDLE_IDENTIFIER) is set to `com.apptreesoftware.accruent.famis` which is the wrong bundleId for this flavor.

For development, I've worked around this issue by manually setting the CFBundleIdentifier in the Runner/Info.plist file to the bundleID i'm trying to run.

**Comment by christian-muertz** [comment] 2018-09-21 16:54
@matthewtsmith My bundle identifier is correct all along the way, so its might be not the problem.

**Comment by christian-muertz** [comment] 2018-09-22 19:31
Now the error is in the beta as well... Cannot start the app :/

**Comment by kayvane1** [comment] 2018-09-23 14:09
I've also got this problem... very frustrating :(

**Comment by mogol** [comment] 2018-09-24 13:13
Replacing in `ios/Runner/Info.plist` CFBundleIdentifier from $(PRODUCT_BUNDLE_IDENTIFIER) to some value solved this issue for me.
```
        <key>CFBundleIdentifier</key>
-       <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
+       <string>bla.bla.bla</string>
```

**Comment by christian-muertz** [comment] 2018-09-24 18:11
@mogol @matthewtsmith Works for me too now!

**Comment by jugyo** [comment] 2018-09-26 21:44
Here is my workaround:

```
flutter install
```

First attempt may fails somehow so you need to execute above twice.

```
flutter attach
```

Then launch the app on the Simulator.

**Comment by nashfive** [comment] 2018-09-30 11:40
I have the same issue with a simple project with a `dev` flavor.

I have created a `dev.xcconfig` which is set for `Debug-dev` and `Release-dev` configurations, and a `dev` scheme which is set to use the appropriate configuration.
I also added a `Info-dev.plist` in the `Runner` project which sets a custom bundle display name and a custom bundle identifier set to `$(PRODUCT_BUNDLE_IDENTIFIER).dev`.

The command `flutter build ios --debug --no-codesign --flavor dev` seems to build a correct `.app` with the correct bundle identifier (the packaged `Info.plist` has the correct infos).

The command `flutter run --verbose --debug --flavor dev` shows that the default bundle identifier is  used for all the executed `xcrun` commands. So, this creates some issues when trying to kill a current running app and also launching the wrong one (or not launching any).

**Comment by jugyo** [comment] 2018-09-30 19:42
So changing your bundle identifier could be a workaround.

e.g.

Change `com.example.flutter-app` to `com.example.flutterapp` that won't be surrounded with double quotes in project.pbxproj.

**Comment by nashfive** [comment] 2018-09-30 20:29
@jugyo my bundle id doesn't include any dashes, only dots.

I think the problem is that the bundle id is only determined by the result of the `defaults` command, which (and I don't know if this is hardcoded somewhere) seems to always query the file `Runner/Info.plist`, no matter if I have created other property list files to handle different bundle display names and ids for each flavors... 

But so far it looks like a small annoyance (the app isn't installed or launched properly), since the builds seems to have the correct bundle IDs & names.

**Comment by nashfive** [comment] 2018-10-01 05:56
@jugyo thanks for the detailed explanation :)
Indeed, flavors are ignored in this process. In my case, it is using the first match found in the xcode project file... 😔

**Comment by zoechi** [comment] 2018-10-03 06:00
Looks like a dup of #15567

**Comment by ngocluan1192** [comment] 2018-11-12 04:51
> Replacing in `ios/Runner/Info.plist` CFBundleIdentifier from $(PRODUCT_BUNDLE_IDENTIFIER) to hard coded value solved this issue for me.
> 
> ```
>         <key>CFBundleIdentifier</key>
> -       <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> +       <string>bla.bla.bla</string>
> ```

You saved me! Thank you very much!

**Comment by matthewcook333** [comment] 2018-12-13 21:52
Wondering if there is any update on this? Running into the same issue, and also have different bundle id for different flavors.

**Comment by KingWu** [comment] 2019-01-21 10:07
Facing the same issues on switching different flavours

**Comment by nachiketkhasbag** [comment] 2019-01-21 10:16
> Replacing in `ios/Runner/Info.plist` CFBundleIdentifier from $(PRODUCT_BUNDLE_IDENTIFIER) to hard coded value solved this issue for me.
> 
> ```
>         <key>CFBundleIdentifier</key>
> -       <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> +       <string>bla.bla.bla</string>
> ```

Worked for me!

**Comment by KingWu** [comment] 2019-01-21 10:24
@nachiketkhasbag not work for me. i set PRODUCT_BUNDLE_IDENTIFIER  with this value com.test.flutterstarterkit$(BUNDLE_SUFFIX)
The bundle id is dynamic. cannot be hard code

**Comment by jlhour** [comment] 2019-01-28 14:42
In case it helps someone in my situation (several flavors, associated `.xcconfig` files and parametrised `PRODUCT_BUNDLE_IDENTIFIER`), I found out a way to launch the app on simulator by checking the `flutter_tools/lib/src/project.dart`'s `get productBundleIdentifier` method.
The only usable `Info.plist` file is the default one, so you can only rely on it.
But within it instead of:
```xml
<key>CFBundleIdentifier</key>
<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```
use:
```xml
<key>CFBundleIdentifier</key>
<string>$(CUSTOM_BUNDLE_IDENTIFIER)</string>
```
with `CUSTOM_BUNDLE_IDENTIFIER` being defined in the `.xcconfig` file(s).

Once this is done, it will skip the "Common case" and jump to the "General case" to get the Bundle ID. This allows me to run my app on an iOS simulator.

**Comment by ajithk444** [comment] 2019-01-29 03:07
Same issue for me too. any resolutions ahead ? Any help would be much appreciated !
![screenshot 2019-01-29 at 8 36 55 am](https://user-images.githubusercontent.com/6139652/51881413-10331200-23a1-11e9-996a-da7b68fdf9ef.png)

**Comment by zoechi** [comment] 2019-01-29 07:57
@ajithk444 please try https://stackoverflow.com/questions/53201957/the-sandbox-is-not-in-sync-with-the-podfile-lock-in-ionic-3-ios-build

Please post errors as text instead of as screenshot.

**Comment by zoechi** [comment] 2019-02-08 15:26
I think this was fixed by #26300
Can you please check if you're still seeing this in `master` channel?

**Comment by KingWu** [comment] 2019-02-10 10:42
@jlhour I try your steps. but no hope. other thing should be setup?

**Comment by jlhour** [comment] 2019-02-12 17:28
@KingWu Has the error evolved in the logs since your modification?
Perhaps make sure that in your iOS build configuration, you have also `PRODUCT_BUNDLE_IDENTIFIER = "$(CUSTOM_BUNDLE_IDENTIFIER)";` that matches the parametrized value in the Info.plist

**Closed** 2019-03-14 23:08 UTC
Labels: severe: regression, tool, waiting for customer response, ⌺‬ platform-ios

**Comment by saitbnzl** [comment] 2019-04-21 22:55
This is still an issue for me, on stable, beta and master channels. I can't hardcode bundle identifier, because my app's bundle id depends on scheme (flavor). The issue is just as described. No issue when running from Xcode. App is installed successfully but not launching with OP's error message. But I can open it manually. So, not a big problem issue, I guess.

**Comment by nashfive** [comment] 2019-05-03 07:36
The problem is still not fixed (trying with beta 1.5.4) for the simulator. 
I've tried all the solutions mentioned here but it is still not working, even with hardcoding the bundle identifiers in the project files directly (not relying on the .xcconfig files). 
Pretty annoying :(

**Comment by PandaGeek1024** [comment] 2019-05-21 14:31
Please don't close Im facing the same issue as well.

**Comment by PandaGeek1024** [comment] 2019-05-22 01:13
I have run into the same issue, it works fine with a real device but only when comes to the simulator it tries to run with different bundle id. obviously it has some thing to do with the command.

**Comment by vidathmw** [comment] 2019-09-22 23:48
Try running flutter clean followed by flutter upgrade & packages upgrade. Worked for me

**Comment by jmagman** [comment] 2019-10-23 21:35
Please leave the Info.plist CFBundleIdentifier as `$(PRODUCT_BUNDLE_IDENTIFIER)` or you're going to have all kinds of different cascading debugging problems from Xcode's side if CFBundleIdentifier doesn't match PRODUCT_BUNDLE_IDENTIFIER
If you need the bundle identifier to be different per build configuration, set it in Runner > Build Settings > Product Build Identifier > expand by hitting the little arrow

![Screen Shot 2019-10-23 at 2 26 16 PM](https://user-images.githubusercontent.com/682784/67435904-07731380-f5a2-11e9-9448-499ea91ee1db.png)

This will update PRODUCT_BUNDLE_IDENTIFIER per configuration, so the right thing will get populated in the Info.plist.

**Comment by jmagman** [comment] 2019-10-23 21:46
@mogol @jlhour I'm going to hide your comments since I think it's leading people down a path that will make CFBundleIdentifier and PRODUCT_BUNDLE_IDENTIFIER out of sync, which is causing different issues and showing up as solutions in search results.  Thank you for being solution-minded, though!

**Comment by huy-t** [comment] 2019-11-16 17:49
In my case.
Just close Simulator and open again :)

**Comment by amyghotra** [comment] 2020-02-29 16:50
Had the same issue. 

Try this:
`flutter clean`

Then once that's done:
`flutter run`

**Comment by chitgoks** [comment] 2020-04-18 10:54
> Had the same issue.
> 
> This worked for me:
> `flutter clean`
> 
> Then once that's done:
> `flutter run`

just wondering. what is the difference with flutter run and clicking the green arrow in android studio to run the app in the ios simulator?

the green button always results in that error message but the 'flutter run' command works.
