### ISSUE TITLE
Update Tooltip widget

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#125981] opened 2023-05-03 15:27 UTC
### Proposal

Part of: #91605

Updating the [Tooltip](https://m3.material.io/components/tooltips/overview) component widget according to Material 3 specifications

1. Plain tooltip
2. Rich tooltip

<img width="1024" alt="unnamed1" src="https://user-images.githubusercontent.com/102767277/235963210-498cb519-0135-42d9-965f-1e630010a37f.png">
<img width="1024" alt="unnamed" src="https://user-images.githubusercontent.com/102767277/235963217-e2291ebf-a418-422e-849f-3288766dcc88.png">

**Comment by HansMuller** [comment] 2023-05-04 16:51
Good request. Closing this one as a duplicate of https://github.com/flutter/flutter/issues/126069

**Closed** 2023-05-04 16:51 UTC
Labels: new feature, framework, f: material design, proposal
