### ISSUE TITLE
Flag emojis have differing widths in iPhone

### ISSUE THREAD

**Issue by lgh001** [flutter/flutter#95716] opened 2021-12-23 07:15 UTC
## Steps to Reproduce

1.Some flag emoji seem to have extra padding. See the image below:

![screenshot-20211223-145819](https://user-images.githubusercontent.com/15257811/147201752-16cd2c44-3ec6-4ca9-aed8-aa24ac401998.png)

**In iPhone、Arabic environment**

**This error occurs in the Arabic environment.**

Bug,it is normal in the English environment.

Maybe in solving this problem https://github.com/flutter/flutter/issues/43230, the Arabic language environment was omitted.

Note:
The TextDirection in the normal language environment is left to right，but it is the opposite in the Arabic environment.

The code:

```
Container(
       color: Colors.blue,
       child: Text( '🇯🇴'',style: TextStyle(fontSize: 30),),),
Container(
        color: Colors.grey,
        child: Text('🇸🇦'',style: TextStyle(fontSize: 30),),),
```

**Comment by mamuseferha** [comment] 2021-12-23 08:28
Hi @lgh001, thank you for filing this issue. 

I tested this issue with the sample code below on the latest stable and master channel and it is not reproducible. Can you please provide your `flutter doctor -v` as well as your device specifications?

<details>
<summary>output</summary>

<img src="https://user-images.githubusercontent.com/92717368/147211368-5a1f5a3e-63c6-4f3d-b6df-5ca465a9a012.png" width="250" height="550" />

</details>

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Reproduction',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key}) : super(key: key);
  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            color: Colors.blue,
            child: const Text(
              '🇯🇴',
              style: TextStyle(fontSize: 30),
            ),
          ),
          Container(
            color: Colors.grey,
            child: const Text(
              '🇸🇦',
              style: TextStyle(fontSize: 30),
            ),
          ),
        ],
      ),
    ));
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.173, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.173 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60de93f297 (5 hours ago), 2021-12-22 22:09:12 -0500
    • Engine revision 2235abc0aa
    • Dart version 2.16.0 (build 2.16.0-128.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by lgh001** [comment] 2021-12-24 07:45
Hi @mamuseferha, Thanks for your response.

In this case ,you need to set the Text param `textDirection: TextDirection.rtl`.

like this:

```
Container(
       color: Colors.blue,
       child: Text( '🇯🇴'',style: TextStyle(fontSize: 30),textDirection: TextDirection.rtl,),),
Container(
        color: Colors.grey,
        child: Text('🇸🇦'',style: TextStyle(fontSize: 30),textDirection: TextDirection.rtl,),),
```

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-arm, )
    • Flutter version 2.5.3 at /Users/***/***/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 mouth ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/lgh/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/AndroidStudio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 96.0.4664.110
    ! Device 20f2ea8e is not authorized.
      You might need to check your device for an authorization dialog.

• No issues found!

</details>

**Comment by mamuseferha** [comment] 2021-12-27 07:43
Hi @lgh001, I tested this again using `textDirection: TextDirection.rtl` and the issue is reproducible on the stable channel but not on the master channel.

This issue seems to be fixed on the latest master channel, I'll go ahead and close this now as it has been fixed. If you disagree please write in the comments and I will reopen it. 


<details>
<summary>output</summary>


**Stable channel**

<img src="https://user-images.githubusercontent.com/92717368/147447411-db16c103-e5ca-4329-b27c-aaaa45356446.png" width="250" height="550" />


**Master channel**

<img src="https://user-images.githubusercontent.com/92717368/147447430-08be36ea-559b-49b4-874b-9c1db1c63a98.png" width="250" height="550" />



</details>
<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Reproduction',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key}) : super(key: key);
  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            color: Colors.blue,
            child: const Text(
              '🇯🇴',
              style: TextStyle(fontSize: 30),
              textDirection: TextDirection.rtl,
            ),
          ),
          Container(
            color: Colors.grey,
            child: const Text(
              '🇸🇦',
              style: TextStyle(fontSize: 30),
              textDirection: TextDirection.rtl,
            ),
          ),
        ],
      ),
    ));
  }
}


```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 mini (mobile) • 9C529156-56BD-48DE-AB6A-71C02E2A91B3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.199, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.199 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a014515c1 (4 hours ago), 2021-12-26 22:09:16 -0500
    • Engine revision 8816e59dd4
    • Dart version 2.16.0 (build 2.16.0-135.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 mini (mobile) • 9C529156-56BD-48DE-AB6A-71C02E2A91B3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Closed by mamuseferha** 2021-12-27 07:43 UTC
Labels: in triage
