### ISSUE TITLE
[web]: Icons not rendering on canvasKit

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#60037] opened 2020-06-23 00:18 UTC
Icons are no longer rendering when canvaskit flag is used. The missing icons are specifically from https://pub.dev/packages/material_design_icons_flutter

![unnamed (1)](https://user-images.githubusercontent.com/56849473/85347013-236de280-b4ac-11ea-946d-a2b8e9076a25.png)
![unnamed (2)](https://user-images.githubusercontent.com/56849473/85347018-2537a600-b4ac-11ea-88c7-07b3332ed06e.png)

➝  flutter --version
Flutter 1.20.0-1.0.pre.135 • channel master • https://github.com/flutter/flutter.git
Framework • revision eaf9ff738a (3 hours ago) • 2020-06-22 11:53:54 -0700
Engine • revision 676cd566f7
Tools • Dart 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

➝ flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true

**Comment by thlorenz** [comment] 2020-06-23 00:36
To repro you could checkout [this version](https://github.com/thlorenz/batufo/tree/8202ee21afbb97e504cc913a3c94fda25a641482) of the game pictured above and run the above from inside `batufo/client`.

```sh
flutter run -d chrome --release \
 --dart-define=FLUTTER_WEB_USE_SKIA=true \
 lib/main/web.release.dart
```

**Comment by AndroidNils** [comment] 2020-06-23 18:54
This might be a duplicate of #54330

**Comment by thlorenz** [comment] 2020-06-24 01:05
It possibly is even though the suggested workaround there did not fix the problem for me.

```sh
flutter run -d chrome --release \
  --dart-define FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true \
  --dart-define=FLUTTER_WEB_USE_SKIA=true \
  lib/main/web.release.dart 
```
still shows icons rendered as an `X`

**Comment by thlorenz** [comment] 2020-06-24 01:54
Realized when looking closer into this that those icons are actually Emojis.
So it seems a different issue after all. [example of a die emoji I'm using](https://github.com/thlorenz/batufo/blob/8202ee21afbb97e504cc913a3c94fda25a641482/client/lib/widgets/game/menu_widget.dart#L35).

**Comment by thlorenz** [comment] 2020-06-24 05:22
I worked around the issue by using `png` icons instead of emojis.
The game built with the above mentioned `SKIA` flag is hosted [here](http://thlorenz.com/batufo/webgame/#/) (make sure to stay on http otherwise you won't be able to connect to the socket server).

**Comment by markusaksli-nc** [comment] 2020-07-20 15:13
Closing this as a duplicate of #54330.

> 
> 
> Realized when looking closer into this that those icons are actually Emojis.
> So it seems a different issue after all. [example of a die emoji I'm using](https://github.com/thlorenz/batufo/blob/8202ee21afbb97e504cc913a3c94fda25a641482/client/lib/widgets/game/menu_widget.dart#L35).

**Closed by markusaksli-nc** 2020-07-20 15:13 UTC
Labels: P4, dependency: skia, e: web_canvaskit, engine, f: material design, framework, platform-web, severe: rendering
