### ISSUE TITLE
Accessibility semantics labels don't show when view is scrollable

### ISSUE THREAD

**Issue by swiftymf** [flutter/flutter#127393] opened 2023-05-23 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the project with voice control turned on in Accessibility setting on iOS. 
Observe the 'hello' label in the middle of the screen does not have a semantics label. 
Change the 'numberOfAddedDividers' property to have less items so the view doesn't need to scroll. 6 should work.
Stop and re-run the project (re-building doesn't work for this). 
Observe the semantics label is now showing for the 'hello' label.

### Expected results

We expect the semantics label to appear on all items that have one, including those in scrollable views

### Actual results

Semantics labels are not appearing for UI in scrollable views.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    // Same behavior for ListView or SingleChildScrollView+Column

    // return ListView(children: _generateWidgets());
    return SingleChildScrollView(child: Column(children: _generateWidgets()));
  }
}

_generateWidgets() {
  int numberOfListItem = 15;
  List<Widget> widgets = [];

  for (var i = 0; i < numberOfListItem; i++) {
    widgets.add(
      TextButton(onPressed: () {}, child: Text('hello$i')),
    );
  }
  return widgets;
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![IMG_3919](https://github.com/flutter/flutter/assets/13595016/fdeaeb23-ed7e-409b-af71-2179804eb25f)
![IMG_3918](https://github.com/flutter/flutter/assets/13595016/55290e1b-1ade-499c-bc9e-34ee553db024)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Downloading Material fonts...                                      502ms
Downloading Gradle Wrapper...                                       25ms
Downloading package sky_engine...                                  107ms
Downloading flutter_patched_sdk tools...                           302ms
Downloading flutter_patched_sdk_product tools...                   286ms
Downloading darwin-arm64 tools...                                2,091ms
Downloading libimobiledevice...                                     66ms
Downloading usbmuxd...                                              26ms
Downloading libplist...                                             28ms
Downloading openssl...                                             131ms
Downloading ios-deploy...                                           38ms
Downloading darwin-arm64/font-subset tools...                      225ms
[!] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/markfransen/fvm/versions/3.10.1
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/markfransen/fvm/versions/3.10.1. Consider adding /Users/markfransen/fvm/versions/3.10.1/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/markfransen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • C307E5D9-C775-490A-A5E6-2966160828BE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-05-24 09:42
Hi @swiftymf. Thanks for filing this issue. I tried reproducing this on a physical iOS device and the label doesn't show in either case but the `VoiceOver` tool reads out the semantic label accurately in both cases. Is this the correct interpretation of the issue or is there anything missing for me to replicate it properly?

<details><summary>Video</summary>
<p>


https://github.com/flutter/flutter/assets/53122008/d990826e-b9f4-446d-8788-8a05f029264a



</p>
</details> 
<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (2 weeks ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            • android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.4 20E247
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3 22E252 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.1 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                            •
      android-arm64  • Android 11 (API 30) (emulator)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e •
      ios            • iOS 16.4 20E247
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by dam-ease** [comment] 2023-05-25 08:00
Thanks @swiftymf. I am able to replicate the hot restart issue. Running the code for the first time, the semantics label reads properly, but on hot restart, it doesn't read both the title and hello text. Closing this as its a duplicate of #109391. Kindly follow up on that issue for updates.

**Comment by swiftymf** [comment] 2023-05-31 15:33
@dam-ease I updated the code sample to be more simplified and I'm including some screenshots to help explain what I'm experiencing. The main issue I'm having is with the `item names` and `item numbers` NOT appearing when a view is scrollable, my issue has nothing to do with hot restart, that was just a bit I added for testing this issue. 

Steps to reproduce: 
- Run on physical device on iOS 16
- Observe when list goes beyond view boundaries the labels do not appear
- Stop running project
- reduce value of `numberOfListItem` to 6 (or whatever number reduces the widgets so they all fit on the screen without scrolling)
- Observe labels appear as expected

When I run this on a device that is on iOS 15, the labels appears as expected all the time. So maybe there were some changes that happened between iOS 15 and 16 that broke this? 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    // Same behavior for ListView or SingleChildScrollView+Column

    // return ListView(children: _generateWidgets());
    return SingleChildScrollView(child: Column(children: _generateWidgets()));
  }
}

_generateWidgets() {
  int numberOfListItem = 15;
  List<Widget> widgets = [];

  for (var i = 0; i < numberOfListItem; i++) {
    widgets.add(
      TextButton(onPressed: () {}, child: Text('hello$i')),
    );
  }
  return widgets;
}

```

</details>

**Comment by dam-ease** [comment] 2023-06-01 09:46
Hi @swiftymf. Thanks for the detailed explanation. I was unable to reproduce this issue on my iPhone X (iOS 16.4) on the latest `stable` channel, upgraded to iOS 16.5 and I'm still unable to reproduce. Can you upgrade to the latest flutter version to confirm if this issue still persist?
<details><summary>Screenshot</summary>
<p>

![IMG_3065](https://github.com/flutter/flutter/assets/53122008/b865a380-dc20-4fdd-86f9-1cc701718571)


</p>
</details>

**Closed** 2023-06-22 10:09 UTC
Labels: waiting for customer response, in triage
