### ISSUE TITLE
Custom FontWeights

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [flutter/flutter#106725] opened 2022-06-28 08:05 UTC
## Use case

Hi, flutter team! In some cases we want to use custom font weights(like 350 or 450). But at this I can't see this are possible. Please make ability to add custom font weights.

## Proposal
At this moment font weights are const values with 100, 200, 300, 400, 500, 600, 700, 800 and 900. Please add custom constructor(or smth else) to be able to add font weight we want

**Comment by LongCatIsLooong** [comment] 2022-06-28 19:13
Duplicate of https://github.com/flutter/flutter/issues/33709

**Closed by LongCatIsLooong** 2022-06-28 19:13 UTC
Labels: new feature, framework, a: typography, proposal
