### ISSUE TITLE
MissingPluginException "No implementation found for method" in path_provider when called from isolate

### ISSUE THREAD

**Issue by Henk-Keijzer** [flutter/flutter#99155] opened 2022-02-25 14:49 UTC
E/flutter ( 9978): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 9978): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 9978): <asynchronous suspension>
E/flutter ( 9978): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
E/flutter ( 9978): <asynchronous suspension>
E/flutter ( 9978): #2      onBackgroundStart (package:szwmobiletracker/main.dart:135:19)
E/flutter ( 9978): <asynchronous suspension>
E/flutter ( 9978): 

Just updated to path_provider version 2.0.9

**Comment by stuartmorgan** [comment] 2022-02-25 14:55
Please use the issue template when filing issues; your report is missing a lot of information that is requested in the template.

What version of Flutter are you using? What platform is this on? What is the complete reproducible test case?

**Comment by Henk-Keijzer** [comment] 2022-02-25 14:59
Not so familiar with github.... Where do I find the template????

Running on Android Studio. 
K:\AndroidStudioProjects\SZWMobileTracker>flutter doctor -v
[√] Flutter (Channel master, 2.11.0-0.0.pre.599, on Microsoft Windows [Version 10.0.22000.527], locale nl-NL)
    • Flutter version 2.11.0-0.0.pre.599 at K:\AndroidStudioProjects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 525c620718 (8 days ago), 2022-02-16 23:16:36 -0800
    • Engine revision 754478998b
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\hwkei\AppData\Local\Android\sdk
    • Platform android-Tiramisu, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.527]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 97.0.4692.99
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

Trying to run on an Android device with Android 12

**Comment by Henk-Keijzer** [comment] 2022-02-25 15:01
And it worked before............

**Comment by stuartmorgan** [comment] 2022-02-25 15:04
We still need a reproducible case.

> And it worked before............

There was a recent change to `path_provider_android`, but to understand what the issue with that change is we need a reproducible test case.

**Comment by Henk-Keijzer** [comment] 2022-02-25 15:10
But I'm not willing to share my complete program publicly. And I have no time to produce a dummy with the same issue.
I just did a full flutter pub upgrade. These are the packages I use:

import 'dart:async';
import 'dart:io';
import 'dart:convert';
import 'package:intl/intl.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:http/http.dart' as http;
import 'package:uuid/uuid.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

The stack trace with filenames and line numbers should provide enough insight for the experts to find where the issue is:

E/flutter ( 9978): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 9978): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 9978):
E/flutter ( 9978): https://github.com/flutter/flutter/pull/1 getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
E/flutter ( 9978):
E/flutter ( 9978): https://github.com/flutter/flutter/pull/2 onBackgroundStart (package:szwmobiletracker/main.dart:135:19)
E/flutter ( 9978):
E/flutter ( 9978):

**Comment by stuartmorgan** [comment] 2022-02-25 15:25
> And I have no time to produce a dummy with the same issue.

We need reproducible test cases to investigate issues. See https://github.com/flutter/flutter/wiki/Issue-hygiene#issues-should-have-clear-steps-to-reproduce and https://github.com/flutter/flutter/wiki/Issue-hygiene#issues-should-have-clear-steps-to-reproduce

We have automated tests that use `path_provider`, and they pass. Your use case is clearly different in some way; without knowing how, we cant' investigate.

> The stack trace with filenames and line numbers should provide enough insight for the experts to find where the issue is

It isn't, because we don't know anything about what `szwmobiletracker/main.dart:135` is doing. For instance, whether or not it is running in an isolate is likely important here, and we have absolutely no way to determine that from the information you have provided.

**Comment by stuartmorgan** [comment] 2022-02-26 11:13
This is due to https://github.com/flutter/flutter/issues/98591 then, and is the `path_provider` version of https://github.com/flutter/flutter/issues/98473.

The [workaround described there](https://github.com/flutter/flutter/issues/98473#issuecomment-1041895729) will work for `path_provider` as well:
- Add dependencies on `path_provider_android` and `path_provider_ios`.
- At the beginning of your background isolate entry point, add something like:
  ```
  if (Platform.isAndroid) PathProviderAndroid.registerWith();
  if (Platform.isIOS) PathProviderIOS.registerWith();
  ```

**Comment by Henk-Keijzer** [comment] 2022-03-01 10:41
It worked for Android, unfortunately I still get the same error on iOS, despite adding the "registerWith" line.

2022-03-01 11:14:50.632181+0100 Runner[1070:257679] Metal API Validation Enabled
2022-03-01 11:14:50.877308+0100 Runner[1070:257941] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_ios)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115)
<asynchronous suspension>
#2      onBackgroundStart (package:szwmobiletracker/main.dart:119)
<asynchronous suspension>

Using path-provider-ios Version 2.0.8

**Comment by stuartmorgan** [comment] 2022-03-01 15:00
It's not the same error:

> No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/**path_provider_ios**

That's the correct channel, which means that the Dart registration has run successfully. You don't have the native side of the plugin registered.

Registering the native plugin implementations with anything but the main engine instance is up to you (or the package you are using to provide background services via the isolate), so that's not a Flutter issue.

**Comment by Henk-Keijzer** [comment] 2022-03-01 15:13
Thanks for your answer, but how do I do that??? And why is it working on Android and not on iOS??? 
Isn't flutter supposed to solve these multiplatform issues?
Sorry for giving you such a hard time. You must be thinking that I'm stupid...

**Comment by stuartmorgan** [comment] 2022-03-01 15:25
> Thanks for your answer, but how do I do that??? And why is it working on Android and not on iOS???

Those are questions you would need to ask the developers of `flutter_background_service`.

> Isn't flutter supposed to solve these multiplatform issues?

The Flutter project cannot control how third-party plugins work.

**Comment by stuartmorgan** [comment] 2022-03-03 21:11
The longer-term workaround is that anything setting up an isolate where plugins are expected to work should call `DartPluginRegistrant.ensureInitialized()`, which will run all Dart plugin registration (similar to how they already need to call `WidgetsFlutterBinding.ensureInitialized()` to make platform message work in the first place). That's not currently on `stable` yet though, as it only just landed on `master`.

**Comment by stuartmorgan** [comment] 2022-03-07 17:46
To summarize the solution: at the start of the entry point for any isolate that needs to use plugins (where you are presumably already calling `WidgetsFlutterBinding.ensureInitialized()`):
- For Flutter 2.11+ (currently `master`), call `DartPluginRegistrant.ensureInitialized()`, which will run the Dart plugin registration for all plugins that need it.
- For older versions of Flutter, manually call the `registerWith` of any plugin implementations you use that have Dart registration. For `path_provider`, see [above](https://github.com/flutter/flutter/issues/99155#issuecomment-1052023743) for details.

Since the plan going forward is to require `DartPluginRegistrant.ensureInitialized()` in isolates, closing as fixed.

**Closed by stuartmorgan** 2022-03-07 17:46 UTC
Labels: plugin, p: path_provider, P3

**Comment by Henk-Keijzer** [comment] 2022-03-07 20:47
Thanks!! We'll do some testing tomorrow. Will let you know.

**Comment by subhashish-bacancy** [comment] 2022-03-15 14:35
> Ok, that works! Thanks!!

Please let me know how to implement this in code.
