### ISSUE TITLE
Whenever running a flutter project, facing this issue

### ISSUE THREAD

**Issue by Aryan3010** [flutter/flutter#97205] opened 2022-01-25 13:40 UTC
Whenever running a flutter project, getting this error. Even after creating a new project and even running a couple of 
commands like flutter clean , etc, the issue still persists.

<img width="1475" alt="Screenshot 2022-01-25 at 7 09 29 PM" src="https://user-images.githubusercontent.com/64428401/150987407-44d6229b-6040-4cb5-92fa-baa08397b120.png">

**Comment by Aryan3010** [comment] 2022-01-26 05:30
[flutter run -v.txt](https://github.com/flutter/flutter/files/7939137/flutter.run.-v.txt)
<img width="967" alt="Screenshot 2022-01-26 at 10 55 31 AM" src="https://user-images.githubusercontent.com/64428401/151108941-ed075003-bd14-459c-8475-4baec5a35989.png">

**Comment by danagbemava-nc** [comment] 2022-01-26 07:23
Hi @Aryan3010, kindly share the contents of the following files.

- pubspec.yaml, pubspec.lock
- android/build.gradle
- android/app/build.gradle
- AndroidManifest.xml

Thank you

**Comment by Shashwat2708** [comment] 2022-01-26 07:54
[androidappbuild.gradle.txt](https://github.com/flutter/flutter/files/7939782/androidappbuild.gradle.txt)
[androidbuild.gradle.txt](https://github.com/flutter/flutter/files/7939783/androidbuild.gradle.txt)
[AndroidManifest.txt](https://github.com/flutter/flutter/files/7939832/AndroidManifest.txt)
[pubspec.lock.txt](https://github.com/flutter/flutter/files/7939785/pubspec.lock.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/7939786/pubspec.yaml.txt)

Hi @danagbemava-nc , I am attaching these files you asked for on behalf of @Aryan3010 as we both are working on this project. 

Although, I don't think that think there is a problem in these files as they are working fine in my project. I think that there is a problem in his flutter as even after creating new files, the same problem occurs.

He has also tried reinstalling flutter but it did not work.

**Comment by danagbemava-nc** [comment] 2022-01-27 06:11
Hi @Shashwat2708, thanks for the files. 

@Aryan3010, do you have this issue only with android or it's also present when you try to run on other platforms?

**Comment by Shashwat2708** [comment] 2022-01-27 06:21
@danagbemava-nc allow me to answer that as well.

The same error was coming in chrome as well. 
For ios, there was a different error which was
`fatal error module 'agora_rtc_engine' not found `

**Comment by danagbemava-nc** [comment] 2022-01-27 10:18
Can you share the verbose logs for both chrome and ios?

**Comment by Shashwat2708** [comment] 2022-01-27 16:53
How to send verbose logs?

**Comment by Aryan3010** [comment] 2022-01-27 20:20
<img width="843" alt="Screenshot 2022-01-28 at 1 49 55 AM" src="https://user-images.githubusercontent.com/64428401/151437330-1efc860e-4621-42bb-90cb-e6eeda6592a6.png">
<img width="703" alt="Screenshot 2022-01-27 at 10 21 43 PM" src="https://user-images.githubusercontent.com/64428401/151437350-20cb10fc-9283-496b-8467-70df35658dbb.png">

**Comment by danagbemava-nc** [comment] 2022-01-28 06:36
Hi @Aryan3010, can you create a dummy flutter project and try to run it and share the logs of that?
This is what I would need from you. 

- The output of `flutter create <project_name> -v`
- The output of `flutter run -v`, on any platform where you have issues


> How to send verbose logs?

You can paste it into a .txt file 

> Is it the output in debug console?

Not quite, the verbose log is what you get when you do `flutter run -v` or any flutter command -v.

**Comment by Aryan3010** [comment] 2022-01-28 07:18
[flutter create<> -v.txt](https://github.com/flutter/flutter/files/7956539/flutter.create.-v.txt)
`Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/aryanarora/Desktop/temp_project/android/app/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.android.application' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`
Unable to run flutter run -v for android device, so sent the output of the debug console

**Comment by danagbemava-nc** [comment] 2022-01-28 12:34
Hi @Aryan3010, are you able to run the default app on either `iOS` or `chrome` or do you have issues running the sample app on those platforms as well?

**Comment by Aryan3010** [comment] 2022-01-28 12:36
Yup, able to run the sample app on ios

**Comment by danagbemava-nc** [comment] 2022-01-28 13:52
Hi @Shashwat2708, I suspect this might be an issue with gradle.

Can you navigate to `~/.gradle/wrapper/dists` and provide `ls -lah` so I can see if a gradle version is available?

**Comment by Aryan3010** [comment] 2022-01-28 15:14
<img width="746" alt="Screenshot 2022-01-28 at 8 43 49 PM" src="https://user-images.githubusercontent.com/64428401/151571879-c2e1472a-ced6-410d-9356-a150601409c3.png">

**Comment by danagbemava-nc** [comment] 2022-01-31 07:25
Hi @Aryan3010, 

Can you change into the `gradle-6.7-all` directory? You should see a folder with a long gibberish name. If you have that folder, change into it and see if you have the following files and directories

- `gradle-6.7`
- `gradle-6.7-all.zip`
- `gradle-6.7-all.zip.lck` and 
- `gradle-6.7-all.zip.ok`

**Comment by Aryan3010** [comment] 2022-01-31 11:05
<img width="1062" alt="Screenshot 2022-01-31 at 4 34 31 PM" src="https://user-images.githubusercontent.com/64428401/151782831-f7305c11-a64f-452c-98f0-ffb47b397137.png">
All the above mentioned files are present

**Comment by danagbemava-nc** [comment] 2022-02-01 07:02
Kindly try clearing your gradle cache and running the sample app again to see if it works. 
See [this so post](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) for some info on how to do that

**Comment by Aryan3010** [comment] 2022-02-03 09:50
Thanks
Now it is working absolutely fine.

**Comment by Aryan3010** [comment] 2022-02-09 22:56
Getting another error
`Running "flutter pub get" in.  <project_name>...                         3.9s
The plugin `firebase_auth` doesn't have a main class defined in /Users/aryanarora/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.3.5/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java or /Users/aryanarora/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.3.5/android/src/main/kotlin/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.kt. This is likely to due to an incorrect `androidPackage: io.flutter.plugins.firebase.auth` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
exit code 1
`
<img width="1456" alt="Screenshot 2022-02-10 at 4 26 08 AM" src="https://user-images.githubusercontent.com/64428401/153304471-be7bf1ff-a223-4ab6-8d14-89b3746b391b.png">

**Comment by danagbemava-nc** [comment] 2022-02-10 14:14
Hi @Shashwat2708, since the initial issue for this thread was solved, I'm going to close this issue again. 

Kindly file new issues for the ones you are currently facing and provide any relevant logs as well as steps to reproduce. 

Feel free to mention me in them. 

Please provide clear and concise descriptions of the new issues you create. 

Closing this as the initial problem was solved. 

Thank you

**Closed by danagbemava-nc** 2022-02-10 14:14 UTC
Labels: in triage
