### ISSUE TITLE
3.16.2: Chip side: BordeSide.none does not work via ChipThemeData

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#139572] opened 2023-12-05 16:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a chip and try to remove the border using `BorderSide.none` or setting width to 0.0, it does not work. You must also specify the color as transparent.

### Expected results

Chip with no border

### Actual results

Chip with border

### Code sample

<details><summary>Does not work sample</summary>

```dart
chipTheme: ChipThemeData(
                shape: StadiumBorder(
                    side: BorderSide.none)),
```

</details>
<details><summary>Does not work sample</summary>

```dart
chipTheme: ChipThemeData(
                shape: StadiumBorder(
                    side: BorderSide(
                        width: 0.0,
                        style: BorderStyle.none))),
```
</details>
<details><summary>Working sample</summary>

```dart
chipTheme: ChipThemeData(
                shape: StadiumBorder(
                    side: BorderSide(
                        width: 0.0,
                        color: Colors.transparent,
                        style: BorderStyle.none))),
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.1 23B81
    darwin-arm64, locale en-GB)
    • Flutter version 3.16.2 on channel stable at
      /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (5 days ago), 2023-11-30
      11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.0)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at
      /Users/jimmyff/Downloads/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 09021FDD40027X • android-arm64  •
      Android 14 (API 34)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS
      14.1.1 23B81 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google
      Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2023-12-06 12:59
> as I see it still works with Chip.shape directly like this

Looks like `BorderStyle.none` also doesn't work in Chip.shape.  
You're providing `BorderSide(style: BorderStyle.none),` which works

**Comment by asci-00** [comment] 2023-12-10 03:57
@TahaTesser 
This issue is resolved by applying [BorderSide.none] to `widget.side` or `chipTheme.side`.
But it seems reasonable for developers to be confused.
The internal comment of `chip.dart` specifies the `side` `shape` attributes as follows:
"To omit the outline entirely, pass [BorderSide.none] to [side]."
However, it does not seem clear whether this refers to the `side` attribute or the `shape.side` attribute.
If it is applied only if BorderSide.none is specified in widget.side, it seems necessary to write a more clear comment.

Also, looking only at the properties provided by Chip, I expected that the priority that determines the side would be something like widget.side > widget.shape.side > chipTheme.side > chipTheme.shape.side > default value.
However, in reality, if `(widget or chipTheme).shape.side` was provided as the default `BorderSide.none`, it would be ignored, which was confusing.

If this is what the flutter team intended, it would be good if they wrote it down in more detail in the documentation. If not, I'd like to take on the task of editing the comments and editing the code. Could you please do that?

**Comment by jimmyff** [comment] 2023-12-12 11:22
ah yes, that is confusing! 😵‍💫

> I expected that the priority that determines the side would be something like widget.side > widget.shape.side > chipTheme.side > chipTheme.shape.side > default value.

Yes this is what I would have expected. I actually didn't even realise that there was a `chipTheme.side` -it's a little confusing that side can be specified there and in the shape although I imagine there are use-cases for both. Regardless it should really honour assigment based on the hierarchy in your comment.

**Comment by TahaTesser** [comment] 2024-02-26 13:59
@asci-00 Thanks for documentation, this is working as designed. ` chipTheme.side` existed for a while in the chip but it causes confusion with `shape.side`, the documentation should help. Closing as fixed.

**Closed by TahaTesser** 2024-02-26 13:59 UTC
Labels: framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.16, found in release: 3.18
