### ISSUE TITLE
[Web, Mobile browser] Due to some error, the webapp crashes and the mobile browser reloads the entire page.

### ISSUE THREAD

**Issue by szunyogh** [flutter/flutter#124026] opened 2023-04-03 16:11 UTC
I have such a problem that the webapp written in flutter gets completely stuck in the mobile browser and reloads. This is not true for a desktop environment. The device shown in the video is an iPhone XR device. This problem does not occur on all phones, so far it occurs on iPhone in any browser and on older Android devices. My main device is a Samsung Galaxy S21 Ultra, on which I don't even see a trace of this error and similar caliber Android devices. In debug mode, I don't have any information about the error, because I can't recreate it. After uploading, it will appear in the release version. I will position this section in the code, so that if any error occurs, it is stored in the database. However, nothing is received regarding this error.

```
FlutterError.onError = (errorDetails) async {
   await service.errorLog(errorDetails.toString(), device);
};
PlatformDispatcher.instance.onError = (error, stack) {
   service.errorLog('PlatformDispatcher ${error.toString()}-$stack', device);
   return true;
};
```

The web was built entirely on a canvaskit basis. I use the Hive package to cache images.

Please help me find a solution to this problem or give me a starting point.

**Expected results:** 

You should keep going without crashing.

**Actual results:** 

As you can see in the video. The page crashes with a grey screen, then turns white, then reloads completely from scratch.

<details>
<summary>Code sample</summary>

```
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  emojis: ^0.9.9
  rive: ^0.10.0
  collection: ^1.16.0
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  intl: ^0.18.0
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.15
  intl_phone_field: ^3.1.0
  percent_indicator: ^4.2.2
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  graphview: ^1.1.1
  youtube_player_iframe: ^2.3.0
  pointer_interceptor: ^0.9.3+3
  package_info_plus: ^3.0.2
  time_machine: ^0.9.17
  fl_chart: ^0.55.2
  supabase_flutter: ^1.2.2
  logger: ^1.1.0
  badges: ^3.0.2
  webviewx: ^0.2.1
  #audioplayers: ^3.0.1
  flutter_secure_storage: ^7.0.1
  flutter_facebook_auth: ^5.0.7
  hive_flutter: ^1.1.0
  device_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
```

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Map<String, dynamic> readAndroidBuildData(AndroidDeviceInfo build) {
    return <String, dynamic>{
      'version.securityPatch': build.version.securityPatch,
      'version.sdkInt': build.version.sdkInt,
      'version.release': build.version.release,
      'version.previewSdkInt': build.version.previewSdkInt,
      'version.incremental': build.version.incremental,
      'version.codename': build.version.codename,
      'version.baseOS': build.version.baseOS,
      'board': build.board,
      'bootloader': build.bootloader,
      'brand': build.brand,
      'device': build.device,
      'display': build.display,
      'fingerprint': build.fingerprint,
      'hardware': build.hardware,
      'host': build.host,
      'id': build.id,
      'manufacturer': build.manufacturer,
      'model': build.model,
      'product': build.product,
      'supported32BitAbis': build.supported32BitAbis,
      'supported64BitAbis': build.supported64BitAbis,
      'supportedAbis': build.supportedAbis,
      'tags': build.tags,
      'type': build.type,
      'isPhysicalDevice': build.isPhysicalDevice,
      'systemFeatures': build.systemFeatures,
    };
  }

  Map<String, dynamic> readIosDeviceInfo(IosDeviceInfo data) {
    return <String, dynamic>{
      'name': data.name,
      'systemName': data.systemName,
      'systemVersion': data.systemVersion,
      'model': data.model,
      'localizedModel': data.localizedModel,
      'identifierForVendor': data.identifierForVendor,
      'isPhysicalDevice': data.isPhysicalDevice,
      'utsname.sysname:': data.utsname.sysname,
      'utsname.nodename:': data.utsname.nodename,
      'utsname.release:': data.utsname.release,
      'utsname.version:': data.utsname.version,
      'utsname.machine:': data.utsname.machine,
    };
  }

  Map<String, dynamic> readLinuxDeviceInfo(LinuxDeviceInfo data) {
    return <String, dynamic>{
      'name': data.name,
      'version': data.version,
      'id': data.id,
      'idLike': data.idLike,
      'versionCodename': data.versionCodename,
      'versionId': data.versionId,
      'prettyName': data.prettyName,
      'buildId': data.buildId,
      'variant': data.variant,
      'variantId': data.variantId,
      'machineId': data.machineId,
    };
  }

  Map<String, dynamic> readWebBrowserInfo(WebBrowserInfo data) {
    return <String, dynamic>{
      'browserName': describeEnum(data.browserName),
      'appCodeName': data.appCodeName,
      'appName': data.appName,
      'appVersion': data.appVersion,
      'deviceMemory': data.deviceMemory,
      'language': data.language,
      'languages': data.languages,
      'platform': data.platform,
      'product': data.product,
      'productSub': data.productSub,
      'userAgent': data.userAgent,
      'vendor': data.vendor,
      'vendorSub': data.vendorSub,
      'hardwareConcurrency': data.hardwareConcurrency,
      'maxTouchPoints': data.maxTouchPoints,
    };
  }

  Map<String, dynamic> readMacOsDeviceInfo(MacOsDeviceInfo data) {
    return <String, dynamic>{
      'computerName': data.computerName,
      'hostName': data.hostName,
      'arch': data.arch,
      'model': data.model,
      'kernelVersion': data.kernelVersion,
      'osRelease': data.osRelease,
      'activeCPUs': data.activeCPUs,
      'memorySize': data.memorySize,
      'cpuFrequency': data.cpuFrequency,
    };
  }

  Map<String, dynamic> readWindowsDeviceInfo(WindowsDeviceInfo data) {
    return <String, dynamic>{
      'numberOfCores': data.numberOfCores,
      'computerName': data.computerName,
      'systemMemoryInMegabytes': data.systemMemoryInMegabytes,
    };
  }

  final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();

  Map<String, dynamic> device = {};

  try {
    if (kIsWeb) {
      device = readWebBrowserInfo(await deviceInfoPlugin.webBrowserInfo);
    } else {
      if (Platform.isAndroid) {
        device = readAndroidBuildData(await deviceInfoPlugin.androidInfo);
      } else if (Platform.isIOS) {
        device = readIosDeviceInfo(await deviceInfoPlugin.iosInfo);
      } else if (Platform.isLinux) {
        device = readLinuxDeviceInfo(await deviceInfoPlugin.linuxInfo);
      } else if (Platform.isMacOS) {
        device = readMacOsDeviceInfo(await deviceInfoPlugin.macOsInfo);
      } else if (Platform.isWindows) {
        device = readWindowsDeviceInfo(await deviceInfoPlugin.windowsInfo);
      }
    }
  } on PlatformException {
    device = <String, dynamic>{'Error:': 'Failed to get platform version.'};
  }

  await FastCachedImageConfig.init(clearCacheAfter: const Duration(days: 15));

  await FacebookAuth.i.webAndDesktopInitialize(
    appId: "xxxx",
    cookie: true,
    xfbml: true,
    version: "v15.0",
  );

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await Supabase.initialize(
    url: supabaseUrl,
    anonKey: supabaseKey,
    localStorage: SecureLocalStorage(),
    debug: true,
  );
  BaseService service = BaseService();

  FlutterError.onError = (errorDetails) async {
    await service.errorLog(errorDetails.toString(), device);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    service.errorLog('PlatformDispatcher ${error.toString()}-$stack', device);
    return true;
  };

  runApp(const ProviderScope(child: Application()));
  setUrlStrategy(PathUrlStrategy());
}

class SecureLocalStorage extends LocalStorage {
  SecureLocalStorage()
      : super(
          initialize: () async {},
          hasAccessToken: () {
            const storage = FlutterSecureStorage();
            return storage.containsKey(key: supabasePersistSessionKey);
          },
          accessToken: () {
            const storage = FlutterSecureStorage();
            return storage.read(key: supabasePersistSessionKey);
          },
          removePersistedSession: () {
            const storage = FlutterSecureStorage();
            return storage.delete(key: supabasePersistSessionKey);
          },
          persistSession: (String value) {
            const storage = FlutterSecureStorage();
            return storage.write(key: supabasePersistSessionKey, value: value);
          },
        );
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2728], locale hu-HU)
    • Flutter version 3.3.10 on channel stable at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\tomi2\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: E:\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at E:\android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/60134128/229563764-498fbe64-ce33-4819-9f7c-6dd8353c581a.mov

**Comment by iapicca** [comment] 2023-04-04 13:38
>  [...] I suspect it's caused by the build or 3rd party packages.

@szunyogh there isn't much flutter team can do about that

**Comment by iapicca** [comment] 2023-04-16 08:35
@narumi147 
can you provide a reproducible code sample?

**Comment by iapicca** [comment] 2023-04-16 08:37
> I agreed that it's really hard to provide minimal reproducibale example. It's just like a black box for me.

@narumi147 without a code sample it's impossible to know what went wrong
(it could be a bad plugin or an issue with the code rather than an issue with flutter, 
no way to know without testing it out)

**Comment by szunyogh** [comment] 2023-04-17 12:33
@iapicca For me, 3rd party packages are important, without them I wouldn't be complete and I wouldn't be able to create a build. But it would be a 3rd party error, somehow flutter should catch the error and log it.

**Comment by darshankawar** [comment] 2023-04-18 05:42
Please atleast narrow down to minimal third party package code implementation that still triggers the reported error so that we can analyze further.

**Comment by chaoyang-zhou** [comment] 2023-04-23 07:25
I have the same problem on iOS 16.4.1. Steps to reproduce, just open https://gallery.flutter.dev/#/ in safari. Click more than 6 items, and then click the top gallery in turn. will get crashed.

https://user-images.githubusercontent.com/62043326/233825955-f57a69b5-15f1-4567-b04b-16c4364eecf8.mp4

**Comment by dkdkdk8v8** [comment] 2023-04-23 16:25
i have same crash ....  pls  fix , 

just open  https://gallery.flutter.dev/#/  , click 2/3 item , my safari reload .... 

in my flutter-web hava same crash ..  random crash !!!!!!

iphone 7plus ,iphone x , iphone 12   all have this crash .. omg ..

**Comment by dkdkdk8v8** [comment] 2023-04-23 16:33
pls check this example on iphone safari , so easy crash 
  https://gallery.flutter.dev/#/rally

**Comment by iapicca** [comment] 2023-04-23 19:56
> I have the same problem on iOS 16.4.1. Steps to reproduce, just open https://gallery.flutter.dev/#/ in safari. Click more than 6 items, and then click the top gallery in turn. will get crashed.

@chaoyang-zhou 
thank you for providing a resemblance of reproducibility, I tried to stress test [gallery.flutter.dev](https://gallery.flutter.dev/) 
on a simulator running 16.2.x and I can't reproduce the issue (yet)
nonetheless it's a good place where to start

**Comment by huycozy** [comment] 2023-04-24 05:45
>I have the same problem on iOS 16.4.1. Steps to reproduce, just open https://gallery.flutter.dev/#/ in safari. Click more than 6 items, and then click the top gallery in turn. will get crashed.

<details>
<summary>Demo Gallery app on iOS 16.4</summary>

https://user-images.githubusercontent.com/104349824/233908727-d70a610f-1bf9-4ba6-8212-c79c02a150d7.mov
</details>

I can not reproduce the issue with these steps on iOS 16.4. If the issue only happens on Gallery app, I would recommend reporting a new issue there for better support. 

>don't run in simulator, I tested my web app in simulator too without crash but does crash in real device(both edge and safari).

@narumi147 For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample code.

**Comment by chaoyang-zhou** [comment] 2023-04-24 10:31
Please let me know of any fixes. I'll keep an eye out. I have the same problem with a project I'm working on. I suspect that the created canvas is not being recycled, or OOM. I don't know how to reduce the canvas creation to support my guess. Starting/closing multiple pages in Android chorme reduces frame rate, then returns to normal frame rate after some time. It will be fine after that. But opening/closing multiple pages in safari will crash directly. I guess the recycling mechanism intervenes too late.

Debugging in Safari, canvas2, 4, 5, 6, and 7 are all the same Widget. I have closed the pages but they are not being recycled. Does this have anything to do with the crash? How do I handle recycling them in real time?

![image](https://user-images.githubusercontent.com/62043326/233970514-9ef8fd28-8f82-40cd-928c-6614c9801e17.png)

**Comment by dkdkdk8v8** [comment] 2023-04-25 09:37
i have same crash .... pls fix ,

just open https://gallery.flutter.dev/#/ , click 2/3 item , my safari reload ....

in my flutter-web hava same crash .. random crash !!!!!!

iphone 7plus ,iphone x , iphone 12 all have this crash .. omg ..

ps. into [Rally] this example , sog easy crash ...!!!



https://user-images.githubusercontent.com/125789426/234237232-1fe9c4d2-2c55-47dc-811f-f097244c55e3.mov

**Comment by CodeToFreedom** [comment] 2023-05-01 00:13
We have the same problem.
Summary of what we learned in 2 weeks of intense debugging:

**- The web app reloads and crashes on all iOS devices (new and old). The browser doesn't matter (we have tested Safari and Chrome). We have tested it on different iPhones.** 
- Changing build mode does not help: profile, release mode, canvaskit as well as html all crash
- self-hosting fonts or canvaskit does not help
- we rarely saw some messages in the console. For example "abort(undefined). Build with -s ASSERTIONS=1 for more info." messages in the console (like described here: https://github.com/flutter/flutter/issues/56938)
- other messages in the console hinted to fonts or Material icons. We then commented all Icons out or replaced them with svg files but the crashes still persist. 
- Most often there are no message at all. Also sentry and other monitoring tools are not capable of tracking the error

- The problem does not follow a strictly repeatable pattern. Sometimes the app reloads directly, sometimes it crashes completely "A problem repeatedly occured on {url}". Usually clicking around between pages triggers it after a while. 

Please set this bug to high priority. Thisbug  makes flutter web apps on iOS devices pretty much unusable. 
Thanks a lot for your help. 

Attachment: The only console messages we got were those and usually it fails without error. So it might not be the cause of the problem, just a follow-up exception.
![Screenshot from 2023-04-29 11-37-22](https://user-images.githubusercontent.com/81858559/235382307-089eae27-ffb2-43d4-bd0c-f44918a67adc.png)
![Screenshot from 2023-04-29 11-41-54](https://user-images.githubusercontent.com/81858559/235382338-770f8286-8e6c-44e5-a388-42c7a781ac23.png)

**Comment by iapicca** [comment] 2023-05-01 15:40
@CodeToFreedom  as @huycozy mentioned [above](https://github.com/flutter/flutter/issues/124026#issuecomment-1519416512)

>  For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample code.

also your [post](https://github.com/flutter/flutter/issues/124026#issuecomment-1529179299) shows [this](https://user-images.githubusercontent.com/81858559/235382307-089eae27-ffb2-43d4-bd0c-f44918a67adc.png) screenshot shows a very familiar decoration above the logs
which suggest that you are probably not running the latest version of flutter
does the issue occur with the latest `master`?

**Comment by CodeToFreedom** [comment] 2023-05-03 13:15
Hi @iapicca, 
thanks for your reply. I created a small demo project. It doesn't crash as fast as a "real" project but it still crashes. 
To trigger the problem please click between "Home Page" and "Profile Page"using an iPhone (see video).
In addition to the source files I also deployed the demo project here: https://904af847.demo-app-8mz.pages.dev/#/ 

Thanks a lot for your help. I really appreciate it. 

Attachments: 
- Flutter demo project (bug_report.zip)
- Screen Recordings of the demo app and how it crashes / reloads on iphone. 

[bug_report.zip](https://github.com/flutter/flutter/files/11382710/bug_report.zip)

https://user-images.githubusercontent.com/81858559/235922333-5a117bab-c876-43cf-b877-5f8700dbbacd.mp4


https://user-images.githubusercontent.com/81858559/235922375-9dce3881-4047-4ae9-acef-9c30e7d1766f.mp4

**Comment by CodeToFreedom** [comment] 2023-05-06 17:07
PS: Sorry I forgot to add the flutter version. @iapicca, were you able to reproduce the error?

 Flutter version 3.7.12 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/sbb/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: ###
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at ###
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment] 2023-05-08 05:36
@CodeToFreedom 
I tried again on iPhone but was unable to replicate it.


https://user-images.githubusercontent.com/67046386/236742082-93a7fb6f-db95-4277-925f-d7f4568f2a72.MP4



> Attachment: The only console messages we got were those and usually it fails without error. So it might not be the cause of the problem, just a follow-up exception.
> ![Screenshot from 2023-04-29 11-37-22](https://user-images.githubusercontent.com/81858559/235382307-089eae27-ffb2-43d4-bd0c-f44918a67adc.png)
> ![Screenshot from 2023-04-29 11-41-54](https://user-images.githubusercontent.com/81858559/235382338-770f8286-8e6c-44e5-a388-42c7a781ac23.png)

If we go by this error that you are getting, there were couple of similar issues that were fixed recently that you can take a look for your reference:

https://github.com/flutter/flutter/issues/121557
https://github.com/flutter/flutter/issues/91674

Also, a similar error issue is open in which you can follow-up for further reference: https://github.com/flutter/flutter/issues/120977 and can share your findings in it for better tracking.

I am going ahead and closing this as a duplicate based on the error message that is mentioned here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-08 05:36 UTC
Labels: waiting for customer response, in triage

**Comment by arok** [comment] 2023-05-10 13:37
In my case the issue was in `ShaderMask` widget

**Comment by CodeToFreedom** [comment] 2023-05-15 21:37
Hi @darshankawar and @arok,
thanks for your responses. 

@darshankawar :
The unfortunate thing about that bug is that it doesn't always happen directly and in constantly reproducable way. It sometimes works for 10 clicks, sometimes for 50, 100  or sometimes only for 2. 
We used real physical iPhones for our tests and also checked it on browser testing platforms like browserstack with enumerous devices.  

All of the iOS devices crashed eventually. This demo app is quite tiny and crashes much later than a heavier real world app. 
So unfortunately it might be necessary to click around quickly much more often to trigger the error.  Please also try it on different iPhones.
As you have seen in my screen record, the demo app can be triggered to crash unexpectedly. 
So there is definitely something wrong.  If that helps I can also record testing it on different devices (but it will be the same as the screen records I posted above). 

Many thanks for your efforts.

@arok:  That sounds interesting. What exactly was wrong in your widget?
