### ISSUE TITLE
it's important for communicate with js by setcookies on webview_flutter 

### ISSUE THREAD

**Issue by twopai** [flutter/flutter#39804] opened 2019-09-04 08:34 UTC
most of flutter webview, their all not method for the setcookies ,but communicate with js through the cookies before the webview_flutter load , so can you add the api directly or give me some codes for setcookies ? help me thanks !

**Comment by BondarenkoStas** [comment] 2019-09-04 09:57
Closing as it's duplicate of #39805

**Closed by BondarenkoStas** 2019-09-04 09:57 UTC
