### ISSUE TITLE
Why is flutter master version lower than stable?

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#110652] opened 2022-08-31 08:29 UTC
```shell
$ flutter upgrade
Flutter is already up to date on channel master
Flutter 3.1.0-0.0.pre.2592 • channel master • https://github.com/flutter/flutter.git
Framework • revision 069f504297 (7 hours ago) • 2022-08-30 18:20:09 -0700
Engine • revision 0ef08a8525
Tools • Dart 2.19.0 (build 2.19.0-152.0.dev) • DevTools 2.16.0
```

```shell
$ flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffccd96b62 (32 hours ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0
```

Am I missing anything? I want to know how this can happen.

PS: Does it mean stable have newer codes?

**Comment by iapicca** [comment] 2022-08-31 09:16
it happens sometimes, it confuses me as well
https://github.com/flutter/flutter/issues/95178

**Comment by christopherfujino** [comment] 2022-08-31 16:07
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/110536. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-08-31 16:07 UTC
Labels: passed first triage, d: conductor
