### ISSUE TITLE
Google maps redraws itself always on top on Android

### ISSUE THREAD

**Issue by YofarDev** [flutter/flutter#112917] opened 2022-10-05 06:10 UTC
> Flutter (Channel master, 3.4.0-40.0.pre.16, on Linux Mint 21
    5.15.0-48-generic, locale en_US.UTF-8)

Yesterday after a flutter update on channel master, the google maps has started having this weird behaviour to redraw itself on top of everything. 

To reproduce it, run the code below, press the button to navigate to Test(), press the android home button and reopen the app. I get this result all the time :

<img src="https://i.imgur.com/xxuhw9e.jpeg" width="300"> 

Switching to channel stable fixes the issue.

Some android infos :
>compileSdkVersion 33
>minSdkVersion 24
>targetSdkVersion 33

Tested on a real device (Samsung S10e) with Android 12. I have not tested on ios.

> map_test.dart

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:video_test/ui/test.dart';

class MapTest extends StatefulWidget {
  const MapTest({Key? key}) : super(key: key);

  @override
  _MapTestState createState() => _MapTestState();
}

class _MapTestState extends State<MapTest> {
  GoogleMapController? _mapController;

  @override
  void dispose() {
    _mapController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Stack(
          children: <Widget>[
            _googleMaps(),
            _btn(),
          ],
        ),
      ),
    );
  }

//////////////////////////////// WIDGETS ////////////////////////////////

  Widget _googleMaps() => GoogleMap(
        myLocationEnabled: true,
        myLocationButtonEnabled: false,
        initialCameraPosition: const CameraPosition(
          target: LatLng(37.43296265331129, -122.08832357078792),
        ),
        onMapCreated: (GoogleMapController controller) =>
            _onMapCreated(controller),
      );

  Widget _btn() => FloatingActionButton(onPressed: () {
        Navigator.of(context).push(
          MaterialPageRoute<dynamic>(
            builder: (BuildContext context) => const Test(),
          ),
        );
      });

//////////////////////////////// LISTENERS ////////////////////////////////

  void _onMapCreated(
    GoogleMapController controller,
  ) {
    _mapController ??= controller;
  }
}

```

> test.dart

```
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      color: Colors.red,
    ));
  }
}
```

**Comment by huycozy** [comment] 2022-10-05 10:04
@YofarDev Could you provide `google_maps_flutter` version are you using? And please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by YofarDev** [comment] 2022-10-05 11:13
@huycozy 

```flutter doctor
[✓] Flutter (Channel master, 3.5.0-1.0.pre.6, on Linux Mint 21
    5.15.0-48-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
In `pubspec.yaml` I just let the version empty
`google_maps_flutter:`

But from `flutter pub upgrade` :

```
google_maps_flutter 2.2.1
google_maps_flutter_android 2.3.2
google_maps_flutter_ios 2.1.12
google_maps_flutter_platform_interface 2.2.4
```

**Comment by ppiatkowski-here** [comment] 2022-10-05 12:07
Could you check if this workaround helps you? https://github.com/flutter/flutter/issues/112929#issuecomment-1268185202

I think these two issues might be connected. Maybe even a duplicate.

**Comment by huycozy** [comment] 2022-10-06 03:54
Hi @YofarDev (and cc @ppiatkowski-here for your issue #112929)
I see there are two open issues addressing the case you described:
- #82105
- #89558

I think this issue is duplicated to one of them (or both), so please check these issues if they are similar to your case.

**Comment by ppiatkowski-here** [comment] 2022-10-07 08:03
@YofarDev I think this is a duplicate of https://github.com/flutter/flutter/issues/89558
Please leave a comment there and react 👍 on the original comment there to help get it prioritized.

**Comment by YofarDev** [comment] 2022-10-07 08:24
> Could you check if this workaround helps you? [#112929 (comment)](https://github.com/flutter/flutter/issues/112929#issuecomment-1268185202)
> 
> I think these two issues might be connected. Maybe even a duplicate.

Sorry for the late answer @ppiatkowski-here 

In your workaround I'm not sure what I should put there :
`   .registerViewFactory("com.example.nativeView", NativeViewFactory())`

> @YofarDev I think this is a duplicate of https://github.com/flutter/flutter/issues/89558
> Please leave a comment there and react +1 on the original comment there to help get it prioritized.

I just did 👍

**Comment by ppiatkowski-here** [comment] 2022-10-07 08:57
@YofarDev 
> In your workaround I'm not sure what I should put there :
> .registerViewFactory("com.example.nativeView", NativeViewFactory())

In my example app I followed this https://docs.flutter.dev/development/platform-integration/android/platform-views#on-the-platform-side to add a native view to my flutter app. In your case I guess it's all handled by the google maps flutter plugin.
Maybe try simply adding the lines marked with '+' sign and don't touch anything else.

**Comment by huycozy** [comment] 2022-10-07 09:48
Closing this issue as a duplicate, so please follow up on mentioned issues for further updates.

**Closed by huycozy** 2022-10-07 09:48 UTC
Labels: in triage
