### ISSUE TITLE
AppLifeCycleState.detached have some imature behaviour(not working properly)

### ISSUE THREAD

**Issue by uzairleo** [flutter/flutter#76702] opened 2021-02-24 13:04 UTC
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlatButton(
          color: Colors.orange,
          child: Text("Press"),
          onPressed: () {
            Navigator.push(
                context, MaterialPageRoute(builder: (context) => Page2()));
          },
        ),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  @override
  _Page2State createState() {
    return _Page2State();
  }
}

class _Page2State extends State<Page2> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print("APP LIFE CYCLE UPDATE STATUS=======>$state");
    if (state == AppLifecycleState.detached) {
      print("App closed Successfully");
    }
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        //do something here before pop
        return true;
      },
      child: Scaffold(
        body: Container(
          child: Center(
            child: FlatButton(
              color: Colors.blue,
              child: Text("Back"),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
when exiting the app directly from the app then all of the events are happening as shown in code snippets 
```
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.inactive
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.paused
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.resumed
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.inactive
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.paused
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.detached

```
AppLifeCyclyState.detached is printing only if I am swiping my flutter application /exiting the application from the same app but its not working when I am jumping  to some other apps and then exiting the app by swiping it from recent than AppLifeCycle.detached is not working 
```
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.inactive
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.paused
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.resumed
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.inactive
I/flutter ( 7575): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.paused
```

Its look like there is some kind of bug with AppLifeCycleState.detached 

The above problem is triggered in Android dont know about ios status !

## problem I want to solve
   
 Actually, I want to call some function before the end-user closing app either directly from the existing app or either from recent whenever he/she want but it's not working try a lot of alternatives even there is nothing more about this in the official documentation of flutter 
Any type of help will be highly appreciated

**Comment by TahaTesser** [comment] 2021-02-24 13:54
Hi @uzairleo 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by uzairleo** [comment] 2021-02-24 14:01
@TahaTesser  yes 
```dart
uzairleo@uzairleo-ThinkPad-T450:~$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /home/uzairleo/Documents/sdk/flutter
    • Framework revision 840c9205b3 (7 months ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/uzairleo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/uzairleo/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Nokia 2 2 (mobile) • HZAL1670DAJA1800026 • android-arm64 • Android 10 (API
      29)

! Doctor found issues in 1 category.
uzairleo@uzairleo-ThinkPad-T450:~$ 

```

**Comment by pedromassangocode** [comment] 2021-02-25 14:28
Hi @uzairleo 
Your Flutter version is seven months old. Can you please upgrade and try again?
If the issue persists, please provide your `flutter doctor -v`.
Thank you

**Comment by uzairleo** [comment] 2021-02-25 14:48
@pedromassangocode  i cant update my flutter version tett because my all dart packages and plugin still familiar with this version and implementation is almost done if i change the version then everything will become depricated

**Comment by uzairleo** [comment] 2021-02-26 06:19
@pedromassango

**Comment by pedromassangocode** [comment] 2021-02-26 07:37
Hi @uzairleo 
I cannot reproduce the issue on latest stable channel whith the following steps: 

1. run app
2. navigate to page 2
3. open another app
4. open Recent apps page
5. close the app

Note in the logs that detached was called before losing the connection with the device.

```console
Syncing files to device sdk gphone x86 64...
[        ] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:flutter_example/main.dart 86dee5f0-f8f7-4f75-8001-11435d4ebf2c
[        ] <- 86dee5f0-f8f7-4f75-8001-11435d4ebf2c
[ +100 ms] Updating files
[ +832 ms] DevFS: Sync finished
[        ] Synced 24.4MB.
[   +1 ms] <- accept
[+1200 ms] Hot restart performed in 2,138ms.
[+55600 ms] I/flutter ( 5550): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.inactive
[+2028 ms] I/flutter ( 5550): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.paused
[+19517 ms] I/flutter ( 5550): APP LIFE CYCLE UPDATE STATUS=======>AppLifecycleState.detached
[   +1 ms] I/flutter ( 5550): App closed Successfully
[  +52 ms] Service protocol connection closed.
[   +3 ms] Lost connection to device.
```


> @pedromassangocode i cant update my flutter version

So I'm not sure what else we can do. As you can see I was not able to reproduce the issue on latest stable, this is because this issue may be already fixed on latest stable version of Flutter. Even if we do  fix for this you still need to upgrade to get the fix.

Since you can't upgrade and I cannot reproduce the issue on latest stable channel, I'm going to close this as there is nothing Flutter team can do about this. Please let me know if you face this issue on any of the latest version of Flutter.
Thank you

**Closed by pedromassangocode** 2021-02-26 07:37 UTC
Labels: in triage
