### ISSUE TITLE
It throws "AbsoluteImportUriError" when I run my application for web platform.

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#93547] opened 2021-11-12 15:17 UTC
My APP can work on Android, iOS, macOS, and  Windows platforms but not on the web.
It shows me the following error log when I execute `flutter run -d chrome`. And I can see nothing on my browser.

```txt
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
ERROR - 2021-11-12 23:06:51.248021
GET /main_module.bootstrap.js
Error thrown by handler.
AbsoluteImportUriError: 'file:///Users/yowfung/workspace/proitav/projects/visualm_flutter/.dart_tool/flutter_build/generated_main.dart'
package:dwds/src/debugging/metadata/provider.dart 232:9   MetadataProvider._addMetadata
package:dwds/src/debugging/metadata/provider.dart 204:15  MetadataProvider._initialize.<fn>

```

But, if I execute `flutter build web` and deploy it on my server. It works!

<details>
<summary>flutter doctor -v</summary>

```txt
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/yowfung/Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yowfung/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/yowfung/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is
      localhost,0.0.0.0,127.0.0.1,192.168.1.253,192.168.1.250,192.168.1.251,192.168.5.253,192.168.0.122,192.1
      68.*,169.254.1.1,169.254.*
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment] 2021-11-12 18:19
Duplicate of https://github.com/flutter/flutter/issues/90782

You can work around this (until the next major release on `stable`) by deleting `.dart_tool/flutter_build/generated_main.dart` when switching from a desktop build to a web or mobile build.

**Closed by stuartmorgan** 2021-11-12 18:19 UTC
