### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "streamListen".

### ISSUE THREAD

**Issue by smailbouramdane** [flutter/flutter#67018] opened 2020-09-30 23:25 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=EC7B4A04-12FB-4790-80E1-DCA3CE3A1E43 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: The client closed with pending request "streamListen".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.410, on Mac OS X 10.15.6 19G2021 x86_64, locale fr-MA)
    • Flutter version 1.22.0-10.0.pre.410 at /Users/sami/developer/flutter
    • Framework revision d693d2b9d2 (31 hours ago), 2020-09-29 09:29:36 -0700
    • Engine revision 414805d1d8
    • Dart version 2.11.0 (build 2.11.0-176.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sami/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • EC7B4A04-12FB-4790-80E1-DCA3CE3A1E43 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: d693d2b9d282c30ef14b444a7860c46893499f7d
### Plugins
cloud_firestore-0.14.0+2
cloud_firestore_web-0.2.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_storage-4.0.1
flutter_pdfview-1.0.3+5
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
sqflite-1.3.1+1

**Comment by jonahwilliams** [comment] 2020-09-30 23:27
Duplicate of https://github.com/flutter/flutter/issues/66823

**Closed by jonahwilliams** 2020-09-30 23:27 UTC
