### ISSUE TITLE
Cupertino Icon isn't aligned vertically to the center

### ISSUE THREAD

**Issue by smallgirl** [flutter/flutter#59264] opened 2020-06-11 14:44 UTC
`Container(
    width: 40,
    alignment: Alignment.center,
    height: 40,
    child: Icon(Icons.star，size:40)，
) 
`
i can center Icon use Icons
`Container(
    width: 40,
    alignment: Alignment.center,
    height: 40,
    child: Icon(CupertinoIcons .xxxxx
，size:40)，
)
`
i can not center Icon use CupertinoIcons 
the other font download from iconfont has the same problem, it is work well when is use the same png ,because  icons has not space around the image 
<img width="100" alt="C68EC36A-2128-416F-9CE6-D5827F94B113" src="https://user-images.githubusercontent.com/5234650/84400762-0a0ba180-ac35-11ea-8267-4ea0b7edc59e.png">

**Comment by Abhishek01039** [comment] 2020-06-11 15:12
hii @smallgirl 
Please see https://flutter.dev/community for resources and asking questions like this.

**Comment by VladyslavBondarenko** [comment] 2020-06-11 15:34
Hi @smallgirl 
with this code sample

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
        child: Center(
          child: Container(
            color: Colors.blue,
            width: 80,
            alignment: Alignment.center,
            height: 100,
            child: Row(
              children: [
                Icon(
                  Icons.search,
                  size: 40,
                ),
                Icon(
                  CupertinoIcons.search,
                  size: 40,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

I can't see that CupertinoIcon to be not centered vertically. Tried with current dev `1.19.0-5.0.pre`. 
Closing, It doesn't look like an issue with flutter.
if you disagree please provide complete reproducible code sample with your `flutter doctor -v` and I will reopen it

**Comment by smallgirl** [comment] 2020-06-12 01:09
@VladyslavBondarenko 
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G84, locale
zh-Hans-CN)
• Flutter version 1.17.0 at /Users/haitao/Library/Android/flutter
• Framework revision e6b34c2 (6 weeks ago), 2020-05-02 11:39:18 -0700
• Engine revision 540786dd51
• Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/haitao/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /Users/haitao/Library/Android/sdk
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)
! Some Android licenses not accepted. To resolve this, run: flutter doctor
--android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.2.1, Build version 11B500
• CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 46.0.1
• Dart plugin version 192.8052
• Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
• iPhone 11 Pro Max • E45BD60E-971E-43F3-9A4A-FBE06484AF67 • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:jianeryou/config/iconfont.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
        child: Stack(
          children: <Widget>[
            Center(
              child: Container(
                color: Colors.blue,
                width: 120,
                alignment: Alignment.center,
                height: 100,
                child: Row(
                  children: [
                    Icon(
                      Icons.add_circle_outline,
                      size: 40,
                    ),
                    Icon(
                      CupertinoIcons.add_circled,
                      size: 40,
                    ),
                    Icon(
                      Iconfont.star,
                      size: 40,
                    ),
                  ],
                ),
              ),
            ),
            Center(
              child: Container(
                height: 1,
                color: Colors.red,
              ),
            )
          ],
        ),
      ),
    );
  }
}

```
[
<img width="299" alt="47ACEAD8-67EC-4612-B12F-32A65361C0C4" src="https://user-images.githubusercontent.com/5234650/84454141-56ce9700-ac8c-11ea-9961-ad3632ce6ab7.png">
](url)

**Comment by VladyslavBondarenko** [comment] 2020-06-12 10:46
Reproduces with current dev `1.20.0-0.0.pre`, `cupertino_icons: ^0.1.3`

**Comment by smallgirl** [comment] 2020-06-12 12:49
I think ti is the  problem of cupertino.ttf , I use the svg create ttf file with https://www.iconfont.cn/  ，It isn't aligned vertically to the center，while i  use the same svg create ttf file with other web site，it is aligned vertically to the center。

**Comment by xster** [comment] 2020-09-28 06:11
I'm deprecating this issue since cupertino_icons 1.0.0 is replacing the old ttf. Though this same problem is present in the new font as well. Deduping into https://github.com/flutter/flutter/issues/66285.

**Closed by xster** 2020-09-28 06:11 UTC
Labels: f: cupertino, found in release: 1.20, framework, has reproducible steps
