### ISSUE TITLE
FlexibleSpaceBar and Hero animation widget weird artifact

### ISSUE THREAD

**Issue by yuehkchou** [flutter/flutter#12518] opened 2017-10-12 21:02 UTC
### Create a Start widget and an End widget

**Start Widget**
- can be any generic widget containing the `Hero` widget.

**End Widget**
- Container > Material > CustomScrollWidget > SliverAppBar > FlexibleSpaceBar > Position.fill > Hero

Set up onPressed event in StartWidget so user can navigate to End Widget.

Click on the button, color block will fill first before Hero widget.

## Sample Code, in Main, runApp(new MyApp())

```dart
import 'package:flutter/material.dart';

/// Root MaterialApp

class MyApp extends StatelessWidget {
  var _routes = <String, WidgetBuilder>{
    "/anotherPage": (BuildContext context) =>
    new AnotherPage(title: "Another Page"),
  };

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Home Page'),
      routes: _routes,
    );
  }
}

/// place: "/"
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // llama Image
    var decoratedBox = new DecoratedBox(
        decoration: new BoxDecoration(
          image: new DecorationImage(
            fit: BoxFit.fitWidth,
            image: new AssetImage('images/images.jpeg'),
          ),
          shape: BoxShape.rectangle,
        ));

    // hero top left
    var hero = new Hero(
      tag: 'hero-tag-llama',
      child: decoratedBox,
    );

    var _children = <Widget>[
      new Container(
        margin: const EdgeInsets.only(top: 200.0),
        height: 250.0,
        width: 250.0,
        child: hero,
      ),
    ];

    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Column(children: _children),
      floatingActionButton: new FloatingActionButton(
        onPressed: _onPressed,
        tooltip: 'Increment',
        child: new Icon(Icons.done),
      ),
    );
  }

  void _onPressed() {
    Navigator.of(context).pushNamed("/anotherPage");
  }
}

// place: "/anotherPage"
class AnotherPage extends StatefulWidget {
  AnotherPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _AnotherPageState createState() => new _AnotherPageState();
}

class _AnotherPageState extends State<AnotherPage> {
  @override
  Widget build(BuildContext context) {
    var decoratedBox = new DecoratedBox(
      decoration: new BoxDecoration(
        image: new DecorationImage(
          fit: BoxFit.fitWidth,
          image: new AssetImage('images/images.jpeg'),
        ),
        shape: BoxShape.rectangle,
      ),
    );

    var hero = new Hero(
      tag: 'hero-tag-llama',
      child: decoratedBox,
    );

    List<Widget> stackChildren = <Widget>[
      new Positioned.fill(child: hero),
    ];

    var center = new Container(
      color: Colors.black,
      child: new Material(
        child: new CustomScrollView(
          slivers: [
            new SliverAppBar(
              flexibleSpace: new FlexibleSpaceBar(

                background: new Stack(
                  children: stackChildren,
                ),
              ),
              pinned: true,
              // Extruding edge from the sliver appbar, may need to fix expanded height
              expandedHeight: MediaQuery.of(context).size.height / 2.5,
              backgroundColor: Colors.red,
            ),
          ],
        ),
      ),
    );

    return center;
  }
}
```
## Logs

No Error

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Framework revision dc41544793 (2 days ago), 2017-10-10 12:04:29 -0400
    • Engine revision 459f722b86
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.4)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by collinjackson** [comment] 2017-10-12 23:09
I made a couple changes:
- Changed the background color of the `FlexibleSpaceBar` to `Colors.transparent`.
- Changed the `fit` of the `DecorationImage` to `BoxFit.cover` in both places

![untitled 5 2](https://user-images.githubusercontent.com/394889/31523336-a86c9f3c-af67-11e7-8c75-ad28f7142096.gif)

Does this look like you intended?

**Comment by collinjackson** [comment] 2017-10-12 23:40
You can get rid of the white background by making the background of the `Material` transparent (and also the `Container` wrapping the `Material`)

![untitled 5 3](https://user-images.githubusercontent.com/394889/31524042-efa4d5fa-af6b-11e7-9224-8df0337e918a.gif)

```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 2.0;
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  var _routes = <String, WidgetBuilder>{
    "/anotherPage": (BuildContext context) =>
    new AnotherPage(title: "Another Page"),
  };

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Home Page'),
      routes: _routes,
    );
  }
}

/// place: "/"
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // llama Image
    var decoratedBox = new DecoratedBox(
        decoration: new BoxDecoration(
          image: new DecorationImage(
            fit: BoxFit.cover,
            image: new AssetImage('images/images.jpeg'),
          ),
          shape: BoxShape.rectangle,
        ));

    // hero top left
    var hero = new Hero(
      tag: 'hero-tag-llama',
      child: decoratedBox,
    );

    var _children = <Widget>[
      new Container(
        margin: const EdgeInsets.only(top: 200.0),
        height: 250.0,
        width: 250.0,
        child: hero,
      ),
    ];

    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Column(children: _children),
      floatingActionButton: new FloatingActionButton(
        onPressed: _onPressed,
        tooltip: 'Increment',
        child: new Icon(Icons.done),
      ),
    );
  }

  void _onPressed() {
    Navigator.of(context).pushNamed("/anotherPage");
  }
}

// place: "/anotherPage"
class AnotherPage extends StatefulWidget {
  AnotherPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _AnotherPageState createState() => new _AnotherPageState();
}

class _AnotherPageState extends State<AnotherPage> {
  @override
  Widget build(BuildContext context) {
    var decoratedBox = new DecoratedBox(
      decoration: new BoxDecoration(
        image: new DecorationImage(
          fit: BoxFit.cover,
          image: new AssetImage('images/images.jpeg'),
        ),
        shape: BoxShape.rectangle,
      ),
    );

    var hero = new Hero(
      tag: 'hero-tag-llama',
      child: decoratedBox,
    );

    List<Widget> stackChildren = <Widget>[
      new Positioned.fill(child: hero),
    ];

    var center = new Container(
      color: Colors.transparent,
      child: new Material(
        color: Colors.transparent,
        child: new CustomScrollView(
          slivers: [
            new SliverAppBar(
              flexibleSpace: new FlexibleSpaceBar(

                background: new Stack(
                  children: stackChildren,
                ),
              ),
              pinned: true,
              // Extruding edge from the sliver appbar, may need to fix expanded height
              expandedHeight: MediaQuery.of(context).size.height / 2.5,
              backgroundColor: Colors.transparent,
            ),
            new SliverFillRemaining(
              child: new Container(color: Colors.white),
            )
          ],
        ),
      ),
    );

    return center;
  }
}
```

**Comment by yuehkchou** [comment] 2017-10-13 05:14
@collinjackson Hey Sorry for the slow reply. 
- The first image has the error I was getting. In the original files, both hero widgets are wrapped in a Boxfit.Cover. 
- I have tried setting both SliverBar and Material's `Colors.transparent`, that would render destination page's background invisible. I tried adding the Container and its color to `white` after making the Material to transparent. But, I think the block is still there.

**Comment by thgoebel** [comment] 2019-01-31 09:44
Changing the `SliverAppBar`s `backgroundColor` to `Colors.transparent` as @collinjackson proposed only works as long as you don't need the image to scroll out of view, contracting the flexible space. Then your AppBar will be transparent too, while you might want it to be colorful.

Ideally you would set the backgroundColor to `Colors.transparent` if the `SliverAppBar` is expanded and to `Theme.of(context).primaryColor` if it is collapsed. This requires https://github.com/flutter/flutter/issues/18567 to be implemented though :/

**Comment by markusaksli-nc** [comment] 2020-07-22 12:51
The behavior is caused simply by the Route animation slightly leading the Hero animation. This is because the Hero animation is separate from the Route animation, there is no property to force the hero to match the edge of the new Page all the way during the animation. 

Closing, as this is working as intended. Feel free to create a new feature request if this is something you think should be added.

**Closed by markusaksli-nc** 2020-07-22 12:51 UTC
Labels: P4, a: animation, customer: posse (eap), framework
