### ISSUE TITLE
Web page doesn't open

### ISSUE THREAD

**Issue by caofuqing** [flutter/flutter#85850] opened 2021-07-04 06:13 UTC
最新SDKflutter2.2.3 创建一个Demo 执行flutter build web  iOS设备浏览器可以打开网页 Android设备打不开是啥原因

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.2 20D80 darwin-x64, locale
    zh-Hans-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
```

**Comment by caofuqing** [comment] 2021-07-04 06:53
![image](https://user-images.githubusercontent.com/10884004/124376032-8a38f500-dcd7-11eb-9b88-7c61b356459b.png)

**Comment by caofuqing** [comment] 2021-07-04 07:08
waitForActivation(reg.installing ? reg.installing : reg.waiting);
这样就解决了

**Comment by TahaTesser** [comment] 2021-07-05 11:55
Hi @caofuqing 
Using Google trnaslate 
`The latest SDKflutter2.2.3 creates a demo and executes flutter build web. The browser of the iOS device can open the webpage. What is the reason why the Android device cannot be opened?`

`waitForActivation(reg.installing? reg.installing: reg.waiting);
So solved`


Can you please provide a complete reproducible minimal code sample, and complete `flutter build web --verbose` logs building the minimal code sample?
Thank you

**Comment by caofuqing** [comment] 2021-07-06 01:38
> `The latest SDKflutter2.2.3 creates a demo and executes flutter build web. The browser of the iOS device can open the webpage. What is the reason why the Android device cannot be opened?`
> 
> `waitForActivation(reg.installing? reg.installing: reg.waiting); So solved`
> 
> Can you please provide a complete reproducible minimal code sample, and complete `flutter build web --verbose` logs building the minimal code sample?
> Thank you



你好,我新建了一个Demo 没有做任何更改  直接使用命令编译了web,然后把build/web 里面的文件放到了服务器上,现在可以在手机端浏览器上访问 
访问地址:  https://webapp.xinling001.cn/  (使用Android手机浏览器访问该地址白屏, iOS手机浏览器访问正常)
demo测试仓库:https://github.com/caofuqing/flutter_test.git
demo编译后的文件(build/web):https://github.com/caofuqing/flutter_test_build_web.git
我的操作日志:
talking@talkingdeMac-mini flutter_app111 % flutter doctor                       
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
talking@talkingdeMac-mini flutter_app111 % flutter build web --web-renderer html                                                                      

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             21.8s
talking@talkingdeMac-mini flutter_app111 % open .


我的手机请求情况(iOS正常显示,Android显示白屏): https://webapp.xinling001.cn/doc/image.jpg

**Comment by caofuqing** [comment] 2021-07-06 04:35
flutter build web --web-renderer html --verbose.  log日志
`talking@talkingdeMac-mini flutter_test % flutter build web --web-renderer html --verbose
[  +93 ms] executing: sysctl hw.optional.arm64
[  +16 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +9 ms] executing: [/Users/talking/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [/Users/talking/Documents/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +19 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +8 ms] executing: [/Users/talking/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/talking/Documents/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +101 ms] executing: [/Users/talking/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H15
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +62 ms] Skipping pub get: version match.
[ +127 ms] Generating /Users/talking/Desktop/未命名文件夹/flutter_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +69 ms] 💪 Building with sound null safety 💪
[  +47 ms] Compiling lib/main.dart for the Web...
[   +5 ms] Initializing file store
[  +17 ms] Done initializing file store
[  +74 ms] Skipping target: web_entrypoint
[   +3 ms] Skipping target: gen_localizations
[ +253 ms] Skipping target: dart2js
[  +56 ms] Skipping target: web_release_bundle
[  +11 ms] Skipping target: web_service_worker
[   +1 ms] Persisting file store
[   +8 ms] Done persisting file store
[  +23 ms] Compiling lib/main.dart for the Web... (completed in 444ms)
[   +2 ms] "flutter web" took 855ms.
[ +262 ms] ensureAnalyticsSent: 258ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
talking@talkingdeMac-mini flutter_test % 
`

**Comment by TahaTesser** [comment] 2021-07-06 07:43
Hi @caofuqing 
I tried to replicate the issue using your demo, executed `flutter build web --web-renderer html --verbose` to build web app, and hosted the build files on Netlify and I can load the web app on Android and iOS

https://hungry-hodgkin-91ffa3.netlify.app/

I also tried your web page link  `https://webapp.xinling001.cn/`, it takes 1-2 seconds to load but your pages also load on my Android device

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/124561711-dd7d8580-de46-11eb-9b11-c86728834ee5.jpg" height="450" />	|



Closing, as this doesn't look like an issue with Flutter itself If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-06 07:43 UTC
Labels: in triage
