### ISSUE TITLE
UnsatisfiedLinkError at io.flutter.view.FlutterMain.startInitialization

### ISSUE THREAD

**Issue by ogrenichv** [flutter/flutter#43853] opened 2019-10-30 21:20 UTC
Seeing such crash on Google Play console.
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1011)
  at java.lang.System.loadLibrary (System.java:1657)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:138)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:110)
  at ...MyApplication.onCreate (MyApplication.java:29)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1119)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5770)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1662)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6543)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:440)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
```
It influes quite a lot on core vitals in GP console.

## Steps to Reproduce
Can't reproduce locally. Seems to be happening only on Android 9.0 (96% from all reports), and Android 8.1 (4%)

We have to use latest Flutter beta version 1.10.7 because the following issue: https://github.com/flutter/flutter/issues/36130

Top devices from GP console:
Galaxy A50 (a50) - 18.0%
Galaxy J7 (j7y17lte) - 15.6%
Galaxy J4+ (j4primelte) - 11.7%
Galaxy J6+ (j6primelte) - 9.0%
Galaxy J6 (j6lte) - 8.2%
Galaxy A10 (a10) - 6.6%
Galaxy J7 Star (j7topltetmo) -  4.7%

## Logs

```
[✓] Flutter (Channel beta, v1.10.7, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.10.7 at /opt/flutter
    • Framework revision e70236e36c (4 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)

 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio-35/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-35
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by VladimirRychlitskiy** [comment] 2019-11-18 19:11
Guys do you have any update here?

**Comment by aabanaag** [comment] 2019-11-25 10:34
i just got this error on my firebase crashlytics. All I can see is that the OS used is 5.1.1 Any ideas?

**Comment by ogrenichv** [comment] 2019-11-29 20:15
Some update on this issue: we have some reports from users who faced this issue. We didn't know how to help them but we have some ideas - one idea is was to increase version number, build apk file (note that we upload bundle to Play console) and ask users to try to upgrade the application (as apk file was signed with the same certificate). So users were able to update application localy and it worked! All application related data was not lost after this upgrade.
We like app bundle as it reduces download size greatly and we would like to stay with it but it seems that we can't. Using app bundle is the root cause of the issue.
So here the question: is this issue related to Flutter or whole app bundle approach could not work as expected in some rare cases?

**Comment by kleinpetr** [comment] 2019-12-14 04:58
I hate exactly thé samé question. When I uploader App Bundle instead APK I am getting this error through crashlytics..

**Comment by creativecreatorormaybenot** [comment] 2020-02-24 12:51
This can be reproduced on a Lenovo Lenovo 500e Chromebook (2nd Gen):

<details>
<summary>Device info</summary>

```
Device: Intel Apollo Lake Chromebook (coral_cheets) 
Android version: Android 9
```

</details>

<details>
<summary>Full stack trace</summary>

```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1669)
  at io.flutter.embedding.engine.loader.FlutterLoader.a (FlutterLoader.java:33)
  at io.flutter.embedding.engine.loader.FlutterLoader.a (FlutterLoader.java:5)
  at io.flutter.view.FlutterMain.a (FlutterMain.java:9)
  at io.flutter.app.FlutterApplication.onCreate (FlutterApplication.java:3)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1167)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6130)
  at android.app.ActivityThread.access$1100 (ActivityThread.java:201)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1725)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6971)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:865)
```

</details>

App was built using `Flutter 1.15.4-pre.84` and `flutter build appbundle`.

**Comment by deadsoul44** [comment] 2020-04-27 15:22
I got the same crash from Firebase Crashlytics. User device is Pixel, Android 7.1.2.

**Comment by RenanDelfanti** [comment] 2020-05-11 11:04
I got the same crash too, Nexus 5X, Android 8.1, Flutter v1.12.13+hotfix.9.

**Comment by xster** [comment] 2020-05-13 01:13
Does anyone have any sample projects or steps to reproduce this issue?

**Comment by creativecreatorormaybenot** [comment] 2020-05-13 12:49
@xster See https://github.com/flutter/flutter/issues/43853#issuecomment-590304426.

**Comment by Nico04** [comment] 2020-06-05 07:13
I've this on the last stable Flutter v1.17.2

**Comment by Nico04** [comment] 2020-06-05 07:19
What do you need to resolve this ?
I can provide CrashLytics reports if it helps

**Comment by 5ran6** [comment] 2020-06-09 13:50
I think this is a very serious issue faced by developers right now...including myself. I could give you a link to a github repo to reproduce. But please let this issue be reopened as a fix has not been made. 

For my project, it only crashed for Android 10 devices

**Comment by xster** [comment] 2020-06-09 17:29
Yes, if you have ways to reproduce this, please share.

**Comment by creativecreatorormaybenot** [comment] 2020-06-09 18:15
@xster People seem to see this a lot in Crashlytics.

I would reckon publishing a project on Android with Firebase services and having a few hundred users will always reveal this issue..

**Comment by xster** [comment] 2020-06-09 19:48
Bot going rogue :D

**Comment by 5ran6** [comment] 2020-06-11 08:59
First of all, this is an app I hosted on playStore. It crashes for Android 10 devices. 
https://play.google.com/store/apps/details?id=com.myshopify.shopdeliverknysna.sdk_staff

Here is the link to the github source codes. https://github.com/5ran6/sdk_staff

Lemme know if you need any other thing

**Comment by ymakhno** [comment] 2020-08-03 19:27
@5ran6 I checked out the provided app and it doesn't include libflutter.so in assembled bundle.

**Comment by 5ran6** [comment] 2020-08-27 09:13
> @5ran6 I checked out the provided app and it doesn't include libflutter.so in assembled bundle.

I'm not so sure why it doesn't. Sorry, how do I fix that?

**Comment by xster** [comment] 2020-10-19 19:07
If you could reproduce this locally, could you unzip your built release mode APK (you can just rename .apk to .zip) then copy paste your content structure? Such as with a https://en.wikipedia.org/wiki/Tree_(command) command.

**Comment by deadsoul44** [comment] 2020-11-12 15:00
Hi @xster ,

I tried to reproduce with internal testing but the app cannot be even installed. A lot of devices are named in this thread and you can reproduce the issue with one of them. The problem is related to appbundle and the only way to install appbundle to a device is through Google Play Store and it cannot be installed with internal testing. I got the error with Xiaomi A2 Lite.

Currently, I have to release fat apk to Play Store due to this issue.

**Comment by darshankawar** [comment] 2020-11-25 11:33
Hi @ogrenichv 
Are you still seeing the issue or has this been resolved ?

**Comment by pedromassangocode** [comment] 2020-12-16 09:34
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-16 09:34 UTC
Labels: P4, engine, platform-android, severe: crash, waiting for customer response
