### ISSUE TITLE
[Impeller] Drawing arcs on Canvas with Custom Painter with a background animation results in strange behaviour.

### ISSUE THREAD

**Issue by Wackymax** [flutter/flutter#134515] opened 2023-09-12 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have the following image that I render using a custom painter. With Impeller disabled it renders fine but when using Impeller it renders incorrectly.
![IMG_0190](https://github.com/flutter/flutter/assets/11558269/a4aaa986-e51d-492b-86bf-89f3f327b8c9)
![IMG_0191](https://github.com/flutter/flutter/assets/11558269/8326573e-fffb-4ac0-bb4d-16dd8d9e5c91)
I also have an animation behind it, when impeller is enabled it causes flickering of the custom painted image but when not using impeller everything works correctly.

I created the some code to reproduce the flickering issue. You can also see that when impeller is enabled it causes another weird problem when the one arc is suddenly moving away from the center:
![RPReplay_Final1694508357](https://github.com/flutter/flutter/assets/11558269/90982884-5ce7-4d36-bc32-e32391284d83)

### Expected results

Enabling Impeller should be changing the behaviour of Custom painters. Animations behind custom painters should not be altering the custom painter canvas and positioning.

### Actual results

As described in steps to reproduce. Custom painters don't work correctly when using Impeller.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SizedBox(
        width: 400,
        height: 400,
        child: Center(
          child: Stack(
            children: [
              Positioned.fill(
                child: _AnimatedBackground(),
              ),
              Padding(
                padding: const EdgeInsets.all(48.0),
                child: DrawingError(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DrawingError extends StatelessWidget {
  const DrawingError({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AspectRatio(
      aspectRatio: 1,
      child: CustomPaint(
        painter: _Painter(),
        child: Center(
          child: Container(
              width: 20,
              height: 20,
              decoration: BoxDecoration(
                color: theme.colorScheme.surface,
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.ac_unit,
                color: theme.colorScheme.primary,
                size: 12,
              )),
        ),
      ),
    );
  }
}

class _Painter extends CustomPainter {
  _Painter() : super();

  Paint get _brush => Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0;

  final Paint windIndicatorPaint = Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0
    ..color = Colors.red
    ..style = PaintingStyle.fill
    ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

  final Paint windIndicatorWhitePaint = Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0
    ..color = Colors.white
    ..style = PaintingStyle.fill
    ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

  @override
  void paint(Canvas canvas, Size size) {
    final Offset center = Offset(size.width / 2, size.height / 2);

    for (var i = 0; i < 7; i++) {
      _drawQuadrant(canvas, size, i);
    }
  }

  void _drawQuadrant(Canvas canvas, Size size, int quadrant) {
    final Offset center = Offset(size.width / 2, size.height / 2);

    final advice = quadrant % 3;
    final heading = 45 * quadrant - (45 / 2);

    double percentage = 0.4;
    Color color = Colors.black;
    switch (advice) {
      case 0:
        color = Colors.green;
        percentage = 1.0;
        break;
      case 1:
        color = Colors.blue;
        percentage = 0.9;
        break;
      case 2:
        color = Colors.red;
        percentage = 0.8;
        break;
    }

    final totalQuadrants = 7;
    final quadrantSize = size.width / totalQuadrants;

    final needlePath = Path();
    needlePath.addPolygon([
      Offset(size.width / 2 - quadrantSize, size.height / 4 * percentage),
      Offset(size.width / 2 + quadrantSize, size.height / 4 * percentage),
      Offset(size.width / 2, size.height / 2)
    ], true);

    final rotation = (270 * pi / 180) + 0.05 + (heading * pi / 180);
    final sweepAngle = 360 / totalQuadrants * pi / 180;

    final needle = _brush
      ..shader = RadialGradient(
              colors: [color.withOpacity(1.0), color.withOpacity(0.8)])
          .createShader(Rect.fromLTWH(0, 0, size.width, size.height))
      ..style = PaintingStyle.fill
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

    canvas.drawArc(
        Rect.fromCenter(
            center: center,
            width: size.width * percentage - 8,
            height: size.height * percentage - 8),
        rotation,
        sweepAngle,
        true,
        needle);
  }

  @override
  bool shouldRepaint(_Painter oldDelegate) => true;
}

class _AnimatedBackground extends StatelessWidget {
  const _AnimatedBackground({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Opacity(
      opacity: 0.04,
      child: Stack(
        children: [
          Positioned.fill(
              child: _Box(
            startOffset: 0.15,
            topOffset: 0.05,
            opacity: 0.8,
            width: 0.4,
            color: Colors.blueGrey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.65,
            topOffset: 0.1,
            opacity: 0.6,
            width: 0.7,
            color: Colors.grey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.3,
            topOffset: 0.25,
            opacity: 0.7,
            width: 0.4,
            color: Colors.black87,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.5,
            topOffset: 0.45,
            opacity: 0.7,
            width: 0.5,
            color: Colors.blueGrey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.7,
            topOffset: 0.65,
            opacity: 0.8,
            width: 0.6,
            color: Colors.grey,
          )),
        ],
      ),
    );
  }
}

class _Box extends StatefulWidget {
  final double startOffset;
  final double topOffset;
  final double opacity;
  final double width;
  final Color color;

  const _Box({
    Key? key,
    required this.startOffset,
    required this.topOffset,
    required this.opacity,
    required this.width,
    required this.color,
  }) : super(key: key);

  @override
  _BoxState createState() => _BoxState();
}

class _BoxState extends State<_Box> with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
        vsync: this,
        duration: const Duration(minutes: 2),
        value: widget.startOffset)
      ..repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _CloudsAnimation(
      controller: _controller,
      topOffset: widget.topOffset,
      opacity: widget.opacity,
      width: widget.width,
      color: widget.color,
    );
  }
}

class _CloudsAnimation extends AnimatedWidget {
  final double topOffset;
  final double opacity;
  final double width;
  final Color color;

  const _CloudsAnimation({
    Key? key,
    required AnimationController controller,
    required this.topOffset,
    required this.opacity,
    required this.width,
    required this.color,
  }) : super(key: key, listenable: controller);

  Animation<double> get _duration => listenable as Animation<double>;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) => Stack(
        children: [
          Positioned(
              top: constraints.maxHeight * topOffset,
              left: lerpDouble(constraints.maxWidth * width * -1,
                  constraints.maxWidth, _duration.value),
              child: Opacity(
                opacity: opacity,
                child: SizedBox(
                  width: constraints.maxWidth * width,
                  child: AspectRatio(
                    aspectRatio: 1,
                    child: Container(
                      color: color,
                    ),
                  ),
                ),
              )),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![RPReplay_Final1694508357](https://github.com/flutter/flutter/assets/11558269/d76ba710-de2d-4ce1-9950-ae2de12e8434)

</details>

### Logs

<details><summary>Logs</summary>

No logs, just running the app normally

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-ZA)
    • Flutter version 3.13.3 on channel stable at /Users/hennie/Tools/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hennie/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/hennie/Library/Android/sdk
    • Java binary at: /Users/hennie/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/hennie/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/hennie/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000E11020AE3401E • ios            • iOS 16.6 20G75
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by yarmel** [comment] 2023-09-12 09:12
It seems that the updated Flutter version 3.13.3 release has brought us more headaches than improvements. I've observed the same strange behaviors with charts. Flutter 3.13.3 also has a significant regression in performance while scrolling (IOS), so I've reverted to Flutter 3.13.2.

**Comment by darshankawar** [comment] 2023-09-12 12:22
Thanks for the report @Wackymax 
Is this only occuring on ipad it seems ? Because I tried the code sample on iOS simulator using latest stable and master versions, but it seems to render the arcs properly without any issues:


https://github.com/flutter/flutter/assets/67046386/b385e88c-b6c9-4a62-aaf1-4844fa9df30f

Can you confirm by running on iOS simulator as well at your end ?

**Comment by Wackymax** [comment] 2023-09-12 15:10
> ```dart
> import 'dart:math';
> import 'dart:ui';
> 
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
>         useMaterial3: true,
>       ),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key, required this.title});
> 
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         backgroundColor: Theme.of(context).colorScheme.inversePrimary,
>         title: Text(widget.title),
>       ),
>       body: SizedBox(
>         width: 400,
>         height: 400,
>         child: Center(
>           child: Stack(
>             children: [
>               Positioned.fill(
>                 child: _AnimatedBackground(),
>               ),
>               Padding(
>                 padding: const EdgeInsets.all(48.0),
>                 child: DrawingError(),
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class DrawingError extends StatelessWidget {
>   const DrawingError({
>     super.key,
>   });
> 
>   @override
>   Widget build(BuildContext context) {
>     final theme = Theme.of(context);
>     return AspectRatio(
>       aspectRatio: 1,
>       child: CustomPaint(
>         painter: _Painter(),
>         child: Center(
>           child: Container(
>               width: 20,
>               height: 20,
>               decoration: BoxDecoration(
>                 color: theme.colorScheme.surface,
>                 shape: BoxShape.circle,
>               ),
>               child: Icon(
>                 Icons.ac_unit,
>                 color: theme.colorScheme.primary,
>                 size: 12,
>               )),
>         ),
>       ),
>     );
>   }
> }
> 
> class _Painter extends CustomPainter {
>   _Painter() : super();
> 
>   Paint get _brush => Paint()
>     ..style = PaintingStyle.stroke
>     ..strokeWidth = 2.0;
> 
>   final Paint windIndicatorPaint = Paint()
>     ..style = PaintingStyle.stroke
>     ..strokeWidth = 2.0
>     ..color = Colors.red
>     ..style = PaintingStyle.fill
>     ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);
> 
>   final Paint windIndicatorWhitePaint = Paint()
>     ..style = PaintingStyle.stroke
>     ..strokeWidth = 2.0
>     ..color = Colors.white
>     ..style = PaintingStyle.fill
>     ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);
> 
>   @override
>   void paint(Canvas canvas, Size size) {
>     final Offset center = Offset(size.width / 2, size.height / 2);
> 
>     for (var i = 0; i < 7; i++) {
>       _drawQuadrant(canvas, size, i);
>     }
>   }
> 
>   void _drawQuadrant(Canvas canvas, Size size, int quadrant) {
>     final Offset center = Offset(size.width / 2, size.height / 2);
> 
>     final advice = quadrant % 3;
>     final heading = 45 * quadrant - (45 / 2);
> 
>     double percentage = 0.4;
>     Color color = Colors.black;
>     switch (advice) {
>       case 0:
>         color = Colors.green;
>         percentage = 1.0;
>         break;
>       case 1:
>         color = Colors.blue;
>         percentage = 0.9;
>         break;
>       case 2:
>         color = Colors.red;
>         percentage = 0.8;
>         break;
>     }
> 
>     final totalQuadrants = 7;
>     final quadrantSize = size.width / totalQuadrants;
> 
>     final needlePath = Path();
>     needlePath.addPolygon([
>       Offset(size.width / 2 - quadrantSize, size.height / 4 * percentage),
>       Offset(size.width / 2 + quadrantSize, size.height / 4 * percentage),
>       Offset(size.width / 2, size.height / 2)
>     ], true);
> 
>     final rotation = (270 * pi / 180) + 0.05 + (heading * pi / 180);
>     final sweepAngle = 360 / totalQuadrants * pi / 180;
> 
>     final needle = _brush
>       ..shader = RadialGradient(
>               colors: [color.withOpacity(1.0), color.withOpacity(0.8)])
>           .createShader(Rect.fromLTWH(0, 0, size.width, size.height))
>       ..style = PaintingStyle.fill
>       ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);
> 
>     canvas.drawArc(
>         Rect.fromCenter(
>             center: center,
>             width: size.width * percentage - 8,
>             height: size.height * percentage - 8),
>         rotation,
>         sweepAngle,
>         true,
>         needle);
>   }
> 
>   @override
>   bool shouldRepaint(_Painter oldDelegate) => true;
> }
> 
> class _AnimatedBackground extends StatelessWidget {
>   const _AnimatedBackground({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return const Opacity(
>       opacity: 0.04,
>       child: Stack(
>         children: [
>           Positioned.fill(
>               child: _Box(
>             startOffset: 0.15,
>             topOffset: 0.05,
>             opacity: 0.8,
>             width: 0.4,
>             color: Colors.blueGrey,
>           )),
>           Positioned.fill(
>               child: _Box(
>             startOffset: 0.65,
>             topOffset: 0.1,
>             opacity: 0.6,
>             width: 0.7,
>             color: Colors.grey,
>           )),
>           Positioned.fill(
>               child: _Box(
>             startOffset: 0.3,
>             topOffset: 0.25,
>             opacity: 0.7,
>             width: 0.4,
>             color: Colors.black87,
>           )),
>           Positioned.fill(
>               child: _Box(
>             startOffset: 0.5,
>             topOffset: 0.45,
>             opacity: 0.7,
>             width: 0.5,
>             color: Colors.blueGrey,
>           )),
>           Positioned.fill(
>               child: _Box(
>             startOffset: 0.7,
>             topOffset: 0.65,
>             opacity: 0.8,
>             width: 0.6,
>             color: Colors.grey,
>           )),
>         ],
>       ),
>     );
>   }
> }
> 
> class _Box extends StatefulWidget {
>   final double startOffset;
>   final double topOffset;
>   final double opacity;
>   final double width;
>   final Color color;
> 
>   const _Box({
>     Key? key,
>     required this.startOffset,
>     required this.topOffset,
>     required this.opacity,
>     required this.width,
>     required this.color,
>   }) : super(key: key);
> 
>   @override
>   _BoxState createState() => _BoxState();
> }
> 
> class _BoxState extends State<_Box> with SingleTickerProviderStateMixin {
>   late AnimationController _controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     _controller = AnimationController(
>         vsync: this,
>         duration: const Duration(minutes: 2),
>         value: widget.startOffset)
>       ..repeat();
>   }
> 
>   @override
>   void dispose() {
>     _controller.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return _CloudsAnimation(
>       controller: _controller,
>       topOffset: widget.topOffset,
>       opacity: widget.opacity,
>       width: widget.width,
>       color: widget.color,
>     );
>   }
> }
> 
> class _CloudsAnimation extends AnimatedWidget {
>   final double topOffset;
>   final double opacity;
>   final double width;
>   final Color color;
> 
>   const _CloudsAnimation({
>     Key? key,
>     required AnimationController controller,
>     required this.topOffset,
>     required this.opacity,
>     required this.width,
>     required this.color,
>   }) : super(key: key, listenable: controller);
> 
>   Animation<double> get _duration => listenable as Animation<double>;
> 
>   @override
>   Widget build(BuildContext context) {
>     return LayoutBuilder(
>       builder: (BuildContext context, BoxConstraints constraints) => Stack(
>         children: [
>           Positioned(
>               top: constraints.maxHeight * topOffset,
>               left: lerpDouble(constraints.maxWidth * width * -1,
>                   constraints.maxWidth, _duration.value),
>               child: Opacity(
>                 opacity: opacity,
>                 child: SizedBox(
>                   width: constraints.maxWidth * width,
>                   child: AspectRatio(
>                     aspectRatio: 1,
>                     child: Container(
>                       color: color,
>                     ),
>                   ),
>                 ),
>               )),
>         ],
>       ),
>     );
>   }
> }
> ```

It seems to be size related somehow, I managed to get it to break on the simulator but now I can't get it to break anymore. It seems to be sporadic, probably because of the animation. I got it to break on a width and height of 200. You will also notice if you change the padding surrounding the drawing error to a larger value the arcs start to draw incorrectly, drawing with flat sides it seems.

Here is the code that was last breaking on my side

```
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SizedBox(
        width: 100,
        height: 100,
        child: Center(
          child: Stack(
            children: [
              Positioned.fill(
                child: _AnimatedBackground(),
              ),
              Padding(
                padding: const EdgeInsets.all(2.0),
                child: DrawingError(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DrawingError extends StatelessWidget {
  const DrawingError({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AspectRatio(
      aspectRatio: 1,
      child: CustomPaint(
        painter: _Painter(),
        child: Center(
          child: Container(
              width: 20,
              height: 20,
              decoration: BoxDecoration(
                color: theme.colorScheme.surface,
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.ac_unit,
                color: theme.colorScheme.primary,
                size: 12,
              )),
        ),
      ),
    );
  }
}

class _Painter extends CustomPainter {
  _Painter() : super();

  Paint get _brush => Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0;

  final Paint windIndicatorPaint = Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0
    ..color = Colors.red
    ..style = PaintingStyle.fill
    ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

  final Paint windIndicatorWhitePaint = Paint()
    ..style = PaintingStyle.stroke
    ..strokeWidth = 2.0
    ..color = Colors.white
    ..style = PaintingStyle.fill
    ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

  @override
  void paint(Canvas canvas, Size size) {
    final Offset center = Offset(size.width / 2, size.height / 2);

    for (var i = 0; i < 8; i++) {
      _drawQuadrant(canvas, size, i);
    }
  }

  void _drawQuadrant(Canvas canvas, Size size, int quadrant) {
    final Offset center = Offset(size.width / 2, size.height / 2);

    final advice = quadrant % 3;
    final heading = 45 * quadrant - (45 / 2);

    double percentage = 0.4;
    Color color = Colors.black;
    switch (advice) {
      case 0:
        color = Colors.green;
        percentage = 1.0;
        break;
      case 1:
        color = Colors.blue;
        percentage = 0.9;
        break;
      case 2:
        color = Colors.red;
        percentage = 0.8;
        break;
    }

    final totalQuadrants = 8;
    final quadrantSize = size.width / totalQuadrants;

    final needlePath = Path();
    needlePath.addPolygon([
      Offset(size.width / 2 - quadrantSize, size.height / 4 * percentage),
      Offset(size.width / 2 + quadrantSize, size.height / 4 * percentage),
      Offset(size.width / 2, size.height / 2)
    ], true);

    final rotation = (270 * pi / 180) + 0.05 + (heading * pi / 180);
    final sweepAngle = 360 / totalQuadrants * pi / 180;

    final needle = _brush
      ..shader = RadialGradient(
              colors: [color.withOpacity(1.0), color.withOpacity(0.8)])
          .createShader(Rect.fromLTWH(0, 0, size.width, size.height))
      ..style = PaintingStyle.fill
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.5);

    canvas.drawArc(
        Rect.fromCenter(
            center: center,
            width: size.width * percentage - 8,
            height: size.height * percentage - 8),
        rotation,
        sweepAngle,
        true,
        needle);
  }

  @override
  bool shouldRepaint(_Painter oldDelegate) => true;
}

class _AnimatedBackground extends StatelessWidget {
  const _AnimatedBackground({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Opacity(
      opacity: 0.04,
      child: Stack(
        children: [
          Positioned.fill(
              child: _Box(
            startOffset: 0.15,
            topOffset: 0.05,
            opacity: 0.8,
            width: 0.4,
            color: Colors.blueGrey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.65,
            topOffset: 0.1,
            opacity: 0.6,
            width: 0.7,
            color: Colors.grey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.3,
            topOffset: 0.25,
            opacity: 0.7,
            width: 0.4,
            color: Colors.black87,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.5,
            topOffset: 0.45,
            opacity: 0.7,
            width: 0.5,
            color: Colors.blueGrey,
          )),
          Positioned.fill(
              child: _Box(
            startOffset: 0.7,
            topOffset: 0.65,
            opacity: 0.8,
            width: 0.6,
            color: Colors.grey,
          )),
        ],
      ),
    );
  }
}

class _Box extends StatefulWidget {
  final double startOffset;
  final double topOffset;
  final double opacity;
  final double width;
  final Color color;

  const _Box({
    Key? key,
    required this.startOffset,
    required this.topOffset,
    required this.opacity,
    required this.width,
    required this.color,
  }) : super(key: key);

  @override
  _BoxState createState() => _BoxState();
}

class _BoxState extends State<_Box> with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
        vsync: this,
        duration: const Duration(minutes: 2),
        value: widget.startOffset)
      ..repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _CloudsAnimation(
      controller: _controller,
      topOffset: widget.topOffset,
      opacity: widget.opacity,
      width: widget.width,
      color: widget.color,
    );
  }
}

class _CloudsAnimation extends AnimatedWidget {
  final double topOffset;
  final double opacity;
  final double width;
  final Color color;

  const _CloudsAnimation({
    Key? key,
    required AnimationController controller,
    required this.topOffset,
    required this.opacity,
    required this.width,
    required this.color,
  }) : super(key: key, listenable: controller);

  Animation<double> get _duration => listenable as Animation<double>;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) => Stack(
        children: [
          Positioned(
              top: constraints.maxHeight * topOffset,
              left: lerpDouble(constraints.maxWidth * width * -1,
                  constraints.maxWidth, _duration.value),
              child: Opacity(
                opacity: opacity,
                child: SizedBox(
                  width: constraints.maxWidth * width,
                  child: AspectRatio(
                    aspectRatio: 1,
                    child: Container(
                      color: color,
                    ),
                  ),
                ),
              )),
        ],
      ),
    );
  }
}
```

**Comment by Wackymax** [comment] 2023-09-12 15:11
Oh, one other note, the code above only breaks about 45 seconds into the animation

**Comment by darshankawar** [comment] 2023-09-13 06:45
I am unable to replicate the reported error. Based on the report, keeping it open for team's attention.

**Comment by chinmaygarde** [comment] 2023-09-18 18:18
Triage: @chunhtai s [fix might hav](https://github.com/flutter/engine/commit/343dfe85c7e810574bd80c71ff774947d495d0b4) addressed this. @bdero is going to try to replicate.

**Comment by jason-simmons** [comment] 2023-09-22 01:57
Reproduced this on an iPhone 11.  It reproduced quickly when I replaced the animation duration with `Duration(seconds: 5)`.

Looks like this was fixed by https://github.com/flutter/engine/commit/105f6e3de3d075ff16ccf8461c184bc4273ddd25 and is no longer happening on the Flutter master branch.

**Comment by chinmaygarde** [comment] 2023-09-22 06:22
Closing as fixed in https://github.com/flutter/engine/commit/105f6e3de3d075ff16ccf8461c184bc4273ddd25. cc @bdero

**Closed by chinmaygarde** 2023-09-22 06:22 UTC
Labels: engine, P2, e: impeller, team-engine, triaged-engine
