### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by sumit1011** [flutter/flutter#157762] opened 2024-10-28 22:55 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.2, on macOS 15.0.1 24A348 darwin-x64, locale en-GB)
    [32m•[39m Flutter version 3.24.2 on channel stable at /Users/sumitech/fvm/versions/3.22.3
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4cf269e36d (8 weeks ago), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/sumitech/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.23+7-LTS-222)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /Users/sumitech/Library/Mobile Documents/.Trash/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m VS Code (version 1.93.0)
    [32m•[39m VS Code at /Users/sumitech/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /Users/sumitech/Desktop/Visual Studio Code 2.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Sumit Kumar Saini (mobile) • 00008110-000655640A9B801E • ios            • iOS 17.6.1 21G93
    [32m•[39m macOS (desktop)            • macos                     • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    [32m•[39m Chrome (web)               • chrome                    • web-javascript • Google Chrome 130.0.6723.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cf269e36de2573851eaef3c763994f8f9be494d
### Plugins
cloud_firestore-4.17.5
cloud_firestore_web-3.12.5
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_auth-4.20.0
firebase_auth_web-5.12.0
firebase_core-2.32.0
firebase_core_web-2.17.3
firebase_storage-11.7.7
firebase_storage_web-3.9.7
flutter_email_sender-6.0.3
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.19
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
geolocator-12.0.0
geolocator_android-4.6.0
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
google_api_headers-1.6.0
google_maps_flutter-2.7.0
google_maps_flutter_android-2.12.0
google_maps_flutter_ios-2.10.0
google_maps_flutter_web-0.5.8
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-6.0.2
location_web-5.0.1
package_info_plus-4.2.0
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.7
permission_handler_apple-9.4.5
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
pointer_interceptor-0.10.1+1
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.2
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-10-29 07:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-10-29 07:29 UTC
Labels: in triage
