### ISSUE TITLE
Your app isn't using AndroidX

### ISSUE THREAD

**Issue by rahulk8** [flutter/flutter#47818] opened 2019-12-26 13:04 UTC
This Problem comes in every app that i download from github and tries running in flutter vscode.
It mainly occurs after i have updated sdk to flutter v1.12.13 hotfix.5

**Comment by as1ndu** [comment] 2019-12-26 19:43
you need to convert it to AndoidX

`
flutter create --androidx -t <project-type> <new-project-path>
`

I however don't know what "project-type" is BTW maybe someone can help us explain?

**Comment by erlange** [comment] 2019-12-27 08:19
> 
> 
> This Problem comes in every app that i download from github and tries running in flutter vscode.
> It mainly occurs after i have updated sdk to flutter v1.12.13 hotfix.5

It happens to me also and every solution available only leads into another issue.  Downgrading to v1.9.1+hotfix.2  seems to be the current workaround for me.

> 
> 
> You need to convert it to AndoidX
> https://flutter.dev/docs/development/androidx-migration
> 
> `flutter create --androidx -t <project-type> <new-project-path>`
> 
> I however don't know what "project-type" is BTW maybe someone can help us explain?

The option specifies what type of project to create: `app` `package` or `plugin`
For more details:
`
flutter -h create
`

**Comment by iapicca** [comment] 2019-12-27 10:41
Hi @rahulk8 
could you please run 
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by as1ndu** [comment] 2019-12-29 12:13
I had the same issue & converted it using @erlange's comment everything works fine now.

**Comment by jnaval04** [comment] 2020-01-04 03:41
You don't need any repro steps for this one. Go try and create a new project, then run `flutter run` even the generated project is not working!

I am using this version Channel stable, v1.12.13+hotfix.5

**Comment by VladyslavBondarenko** [comment] 2020-01-28 10:08
I hope the issue is solved. 
You can find info about migration to AndroidX [here](https://flutter.dev/docs/development/androidx-migration) or [here](https://medium.com/@swhussain110/how-to-migrate-your-flutter-app-to-androidx-9a78eaaa924b), or [here](https://medium.com/@gabrc52/how-to-migrate-your-flutter-app-to-androidx-1202ad43c8c8) or in any other sources.
We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution

**Closed by VladyslavBondarenko** 2020-01-28 10:08 UTC
Labels: waiting for customer response

**Comment by keitoro** [comment] 2020-03-13 12:04
It seems a bug that is still causing problem. I just started migrating an old project to the new androidx project by copying all the files and it solved the issue but today I started the project with vscode and an emulator and the error was back that I am not using android x for some reason.  No solution seems to be working. The app runs as it should, but this is worrying me.

**Comment by iapicca** [comment] 2020-03-13 12:37
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
