### ISSUE TITLE
[Linux] Cursor and Text Input Backwards

### ISSUE THREAD

**Issue by jr1221** [flutter/flutter#77298] opened 2021-03-04 23:06 UTC
https://user-images.githubusercontent.com/53871299/110043509-83907600-7d15-11eb-9af0-a48230e22ca4.mp4

## Steps to Reproduce

Use the TextField widget and build on the Linux platform (exact code below).

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        children: <Widget>[
          TextField(),
        ],
      ),
    );
  }
}

```

**Expected results:** 
The cursor would move each time something is inputted into the TextField.  All text input would be to right of previous text input.

**Actual results:** 
The cursor does not move, and all text input is placed to the left of the current text.  The cursor can be moved via arrow keys or mouse, but all text is still added at the beginning of the existing characters.

I am new to flutter programming, but I figure this is a bug because it is isolated to the Linux desktop.  My OS is the Arch based Manjaro, so this could be a problem isolated to new versions of a Linux based tool.

<details>
  <summary>Logs</summary>

```
[  +56 ms] executing: [/home/jack/.local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] executing: [/home/jack/.local/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +10 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +29 ms] executing: [/home/jack/.local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/jack/.local/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +32 ms] executing: [/home/jack/.local/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: /home/jack/Android/Sdk/platform-tools/adb devices -l
[  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: /home/jack/Android/Sdk/platform-tools/adb devices -l
[   +7 ms] Skipping pub get: version match.
[  +88 ms] Generating /home/jack/DataPart/StudioProjects/flutter_app_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +66 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +4 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/jack/.local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/jack/.local/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/jack/.local/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.WNDHTU/flutter_tool.FXJKMC/app.dill --packages
/home/jack/DataPart/StudioProjects/flutter_app_test/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +17 ms] Building Linux application...
[  +28 ms] <- compile package:flutter_app_test/main.dart
[   +1 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/jack/DataPart/StudioProjects/flutter_app_test/linux
[   +8 ms] List of devices attached
[   +2 ms] List of devices attached
[  +35 ms] -- Configuring done
[   +5 ms] -- Generating done
[   +9 ms] -- Build files have been written to: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug
[   +3 ms] executing: ninja -C build/linux/debug install
[  +11 ms] ninja: Entering directory `build/linux/debug'
[+11709 ms] [1/5] Generating /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/jack/DataPart/StudioProjects/flutter_app_test/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +4 ms] [  +61 ms] executing: [/home/jack/.local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +28 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] [        ] executing: [/home/jack/.local/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] [  +10 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] [        ] 2.0.1
[        ] [  +39 ms] executing: [/home/jack/.local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [/home/jack/.local/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +30 ms] executing: [/home/jack/.local/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +48 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +45 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +78 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +32 ms] Skipping target: gen_localizations
[        ] [+1328 ms] Skipping target: unpack_linux
[        ] [ +461 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[   +2 ms] [   +6 ms] /home/jack/.local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/jack/.local/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/jack/.local/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages
/home/jack/DataPart/StudioProjects/flutter_app_test/.dart_tool/package_config.json --output-dill /home/jack/DataPart/StudioProjects/flutter_app_test/.dart_tool/flutter_build/ec3e91617bb2f53e51f1846e3340ee78/app.dill --depfile
/home/jack/DataPart/StudioProjects/flutter_app_test/.dart_tool/flutter_build/ec3e91617bb2f53e51f1846e3340ee78/kernel_snapshot.d package:flutter_app_test/main.dart
[   +1 ms] [+7542 ms] kernel_snapshot: Complete
[        ] [ +606 ms] debug_bundle_linux_assets: Starting due to {InvalidatedReason.inputChanged}
[        ] [ +238 ms] debug_bundle_linux_assets: Complete
[        ] [ +359 ms] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [  +11 ms] "flutter assemble" took 10,748ms.
[        ] [ +218 ms] ensureAnalyticsSent: 212ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +818 ms] [2/5] Building CXX object CMakeFiles/flutter_app_test.dir/flutter/generated_plugin_registrant.cc.o
[  +72 ms] [3/5] Building CXX object CMakeFiles/flutter_app_test.dir/my_application.cc.o
[ +196 ms] [4/5] Linking CXX executable intermediates_do_not_run/flutter_app_test
[        ] [4/5] Install the project...
[  +11 ms] -- Install configuration: "Debug"
[  +26 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/flutter_app_test
[        ] -- Set runtime path of "/home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/flutter_app_test" to "$ORIGIN/lib"
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +179 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +57 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/NOTICES
[   +1 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +1 ms] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/jack/DataPart/StudioProjects/flutter_app_test/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[  +15 ms] Building Linux application... (completed in 13.2s)
[ +330 ms] Observatory URL on device: http://127.0.0.1:46249/3a3w1GemSUs=/
[   +6 ms] Caching compiled dill
[  +84 ms] Connecting to service protocol: http://127.0.0.1:46249/3a3w1GemSUs=/
[ +254 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:46249/3a3w1GemSUs=/.
[ +118 ms] DDS is listening at http://127.0.0.1:45505/qNNbHXMHZpU=/.
[  +67 ms] Successfully connected to service protocol: http://127.0.0.1:46249/3a3w1GemSUs=/
[ +598 ms] DevFS: Creating new filesystem on the device (null)
[  +19 ms] DevFS: Created new filesystem on the device (file:///tmp/flutter_app_testRVBIDJ/flutter_app_test/)
[   +6 ms] Updating assets
[ +117 ms] Syncing files to device Linux...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:flutter_app_test/main.dart 89303b9c-e8bd-405a-93d2-4f52b2beb8f2
[        ] <- 89303b9c-e8bd-405a-93d2-4f52b2beb8f2
[  +80 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 88ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +5 ms] Connected to _flutterView/0x55fad6d7b6a0.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:45505/qNNbHXMHZpU=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on Linux is available at: http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A45505%2FqNNbHXMHZpU%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+35133 ms] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "�" because we are busy.
[        ] Ignoring terminal input: "[   +2 ms] R Hot restart.
           [        ] h Repeat this help message.
           [        ] d Detach (terminate "flutter run" but leave application running).
           [        ] c Clear the screen
           [        ] q Quit (terminate the application on the device).
           [        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:45505/qNNbHXMHZpU=/
           [   +1 ms] 
                      Flutter DevTools, a Flutter debugger and profiler, on Linux is available at: http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A45505%2FqNNbHXMHZpU%3D%2F
           [        ] Running with unsound null safety
           [        ] For more information see https://dart.dev/null-safety/unsound-null-safety" because we are busy.
```

```
```

```
[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/jack/.local/flutter
    • Framework revision c5a4b4029c (5 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/jack/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/jack/Android/
    • Java binary at: /home/jack/.local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.5
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /home/jack/.local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/jack/.local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /usr/share/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.72

• No issues found!

```

</details>

**Comment by frknkrc44** [comment] 2021-03-05 01:09
I have same issue and looking for a temp fix

**Comment by sqiao2-ford** [comment] 2021-03-05 08:44
I have a question ,when I update EditorText values how to remove cursor to end?

**Comment by TahaTesser** [comment] 2021-03-05 09:53
Hi @frknkrc44 
This is a duplicate of https://github.com/flutter/flutter/issues/76383
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-05 09:53 UTC
Labels: in triage
