### ISSUE TITLE
A way to set Window title on desktop targets

### ISSUE THREAD

**Issue by GCSBOSS** [flutter/flutter#129684] opened 2023-06-27 23:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I need to display my human readable app name on window title bar on desktop targets, but it seems to only display the alpha-numeric app name by default.

### Proposal

I'm new to Flutter, so this may be just non-sense, but should it use the `title` defined here?

```dart
// ...
 return MaterialApp(
      title: 'Flutter Demo',
// ...
```

**Comment by stuartmorgan** [comment] 2023-06-28 00:46
Duplicate of https://github.com/flutter/flutter/issues/30712

**Closed by stuartmorgan** 2023-06-28 00:46 UTC
