### ISSUE TITLE
[web]: keyboard insets are sometimes ignored on Safari on mobile

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#42211] opened 2019-10-08 06:10 UTC
When clicking/tapping on a `TextField` on mobile, the field should grab the focus and the keyboard should appear. The page should then slide up to accommodate the keyboard and keep the field visible.

With a regular flutter mobile app all is well, but with a flutter web app running in Safari on mobile, the page does not slide up if the field didn't already have the focus.

Here's a minimal app to show the issue:
```dart
return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.blue[100],
        body: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: Container(
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter,
                      colors: [
                        Colors.indigo[100],
                        Colors.indigo[900],
                      ],
                    ),
                  ),
                  child: SizedBox(),
                ),
              ),
              Container(
                color: Colors.white,
                child: TextField(),
              ),
            ],
          ),
        ),
      ),
    );
```

When tapping the field for the first time, the field is hidden behind the keyboard:
![ios safari nok](https://user-images.githubusercontent.com/13898333/66370896-b0374580-e9dc-11e9-882d-b71f0374e3db.png)

Then, when tapping away and tapping again the field (which kept focus), the keyboard shows up again but pushes the page as expected:
![ios safari ok](https://user-images.githubusercontent.com/13898333/66371231-a3672180-e9dd-11e9-95e5-c950c72fd0e1.png)

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.10.13, on Mac OS X 10.14.6 18G95, locale en-KR)
    • Flutter version 1.10.13 at /Users/thibaultdeckers/projects/flutter
    • Framework revision 97e00b2288 (15 hours ago), 2019-10-07 08:11:45 -0700
    • Engine revision 7d90779bb6
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thibaultdeckers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/thibaultdeckers/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.6.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/thibaultdeckers/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (4 available)
    • SM G970N        • R39M4001Z1M                          • android-arm64  • Android 9 (API 28)
    • iPhone 11       • 75CFC2E6-18BA-4EA3-AC14-4E55B77A0C58 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)
    • Chrome          • chrome                               • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server                      • web-javascript • Flutter Tools

• No issues found!
```

**Comment by nturgut** [comment] 2019-10-10 15:49
Hi, 

If the issue is " the page does not slide up if the field didn't already have the focus.", we cancelled it intentionally.

Here is the code which does those checks, and keeps the page from scrolling:
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text_editing.dart#L265
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text_editing.dart#L715

The issue is we had was, in Webkit Mobile when virtual keyboard is coming up, it also shifts the page up. There are no events to track when the shift started, when it is ended, how much did it shift. Due to these, engine is not able to send the shift related info back to Flutter Framework (which will layout the page accordingly).

For example, if one disables this code and let webkit shift the page up. After closing the virtual keyboard, they can see how some parts under the keyboard are not rendered.

One future solution to this is getting a reliable information from webkit about the virtual keyboard activty, this can be mostly done with the safari 13 update. They started supporting the VisualViewport API: https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport. 

Since this is not an available utility in many Iphones now, I'm marking the issue as Goals. We can definitely change text_editing.dart in the future.

**Comment by nturgut** [comment] 2019-10-10 15:49
Thanks for filing the issue!

**Comment by deckerst** [comment] 2019-10-16 00:39
@nturgut thank you for the explanations

This issue is a blocker for our Flutter web app, as it basically prevents iOS users from using a text field.

According to [Apple](https://www.apple.com/newsroom/2019/06/apple-previews-ios-13/?1559586061): "New software features will be available this fall as a free software update for iPhone 6s and later, and will be available with iPadOS for iPad Air 2 and later, all iPad Pro models, iPad 5th generation and later, and iPad mini 4 and later."

All iPhones from iPhone 6s have access to Safari 13 and, contrary to Android, adoption of new iOS releases is fast. Also, all browsers on iOS rely on the same engine, so this issue impacts all iOS users, whatever their favourite browser.

Could you please reconsider the impact and solvability of this issue?

**Comment by nturgut** [comment] 2019-10-16 02:05
Thanks for sharing the feedback, I will update the code for safari 13 iOS, then.

**Comment by nturgut** [comment] 2019-10-31 22:51
Note: this is only fixed for safari 13.

**Closed** 2019-10-31 22:51 UTC
Labels: a: text input, customer: webeap, ☸ platform-web

**Comment by Surio89** [comment] 2020-05-13 07:31
The error can currently be observed on iPad Pro iOS 12 and 13 and latest Safari. No autoscroll to textfield, no layout reaction to softkeyboard popup. Flutter Dev/Master Channel.
