### ISSUE TITLE
[Web] : TextField loose focus after navigation

### ISSUE THREAD

**Issue by karabanovbs** [flutter/flutter#71476] opened 2020-12-01 12:28 UTC
When i user pushReplacement the TextField on second screen loose focus. On android work correctly, problem reproduce on IOS and WEB.

With  push navigation (without replacement) work correctly.

## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Screen 1'),
        ),
        body: Builder(
          builder: (context) {
            return AutofillGroup(
              child: TextFormField(
                autofocus: true,
                onChanged: (value) {
                  Navigator.of(context).pushReplacement(MaterialPageRoute(
                    builder: (context) {
                      return Scaffold(
                        appBar: AppBar(
                          title: Text('Screen 2'),
                        ),
                        body: TextField(
                          autofocus: true,
                          onChanged: (value) {},
                        ),
                      );
                    },
                  ));
                },
              ),
            );
          },
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale ru-RU)
    • Flutter version 1.24.0-10.2.pre at /Users/boriskarabanov/dev/sdk/flutter
    • Framework revision 022b333a08 (13 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/boriskarabanov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/boriskarabanov/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/boriskarabanov/Library/Android/sdk
    • Java binary at: /Users/boriskarabanov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/boriskarabanov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Users/boriskarabanov/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • DNS s4502 (mobile)                 • 323c1501ac89e45a8a7d4f96378b819cc7ef3d5c • ios            • iOS 14.2
    • iPhone 12 Pro Max (mobile)         • 7D85263D-F555-47CD-9F9C-F1902DE7F82B     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)                   • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome                                   • web-javascript • Google Chrome 87.0.4280.67
    ! Error: DNS s4502 is busy: Copying cache files from device. Xcode will continue when DNS s4502 is finished. (code -10)

• No issues found!
```

**Comment by hello-addweb** [comment] 2020-12-01 12:40
Use GlobalKey for that so issue will resolve : 
`static final GlobalKey<FormFieldState<String>> _orderFormKey = GlobalKey<FormFieldState<String>>();`

**Comment by karabanovbs** [comment] 2020-12-01 12:48
@hello-addweb Thanks for answer.

I try use keys in TextFields, but this still have issue.

Example:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static final GlobalKey<FormFieldState<String>> _key1 = GlobalKey<FormFieldState<String>>();
  static final GlobalKey<FormFieldState<String>> _key2 = GlobalKey<FormFieldState<String>>();
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Screen 1'),
        ),
        body: Builder(
          builder: (context) {
            return AutofillGroup(
              child: TextFormField(
                key: _key1,
                autofocus: true,
                onChanged: (value) {
                  Navigator.of(context).pushReplacement(MaterialPageRoute(
                    builder: (context) {
                      return Scaffold(
                        appBar: AppBar(
                          title: Text('Screen 2'),
                        ),
                        body: TextFormField(
                          key: _key2,
                          autofocus: true,
                          onChanged: (value) {},
                        ),
                      );
                    },
                  ));
                },
              ),
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-12-01 13:15
@karabanovbs 
Tried your original code sample on Android, iOS and web and works well on both mobile platforms, but not in web.

[71476_android.mov.zip](https://github.com/flutter/flutter/files/5622765/71476_android.mov.zip)

[71746_ios.mov.zip](https://github.com/flutter/flutter/files/5622766/71746_ios.mov.zip)
[71746_web.mov.zip](https://github.com/flutter/flutter/files/5622767/71746_web.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (13 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!


```

</details>

**Comment by karabanovbs** [comment] 2020-12-01 13:26
@darshankawar On iOS focus exist ~1 seconds, and then loose. In my video, I had enough time to type 2 symbol, and then focus has been loosed.

[ios.mov.zip](https://github.com/flutter/flutter/files/5622831/2020-12-01.18.21.21.mov.zip)

**Comment by karabanovbs** [comment] 2021-02-25 22:41
In this case, the second screen loses focus and call `onFieldSubmitted`.

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: AutofillGroup(
          child: TextFormField(
            autofocus: true,
            onChanged: (_) {
              Navigator.of(context).pushReplacement(
                MaterialPageRoute(
                  builder: (context) {
                    return Scaffold(
                      body: Center(
                        child: TextFormField(
                          autofocus: true,
                          onFieldSubmitted: (_) {
                            print('onFieldSubmitted');
                          },
                        ),
                      ),
                    );
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

**Comment by karabanovbs** [comment] 2021-02-26 00:13
I don't know if this can help.

Explanations:
When `AutofillGroup` uses with `AutofillContextAction.cancel` or `AutofillContextAction.commit` parameter `onDisposeAction`, then `finishAutofillContext` calling for all existing `TextInput`.
Then if new `TextInput` already exists and has focus, they handle `finishAutofillContext` and close connection.

Why `AutofillGroup` not call `finishAutofillContext` only for their clients?
I`m will glad is someone help me. Thanks.

**Comment by xu-baolin** [comment] 2021-02-26 00:51
This bug is related to this [PR](https://github.com/flutter/engine/pull/20256#discussion_r534057426),
CC @LongCatIsLooong @nturgut

**Comment by maheshmnj** [comment] 2023-01-12 04:29
Hello @karabanovbs, I verified the issue on stable 3.3 and master 3.7 and It looks like the issue is fixed.

IOS | Web
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/211974888-f15281b0-6f3b-45a0-ae09-2bfe05308f0d.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/211976185-e1e9ee1a-16c1-4c11-8b11-e35aa20e8a94.mov' width=180/> 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

I am going to close this issue as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-12 04:29 UTC
Labels: a: text input, framework, f: routes, platform-web, passed first triage, f: focus, has reproducible steps, P4, found in release: 1.24
