### ISSUE TITLE
Error while cross compiling flutter engine for ARM linux embedded device (pango/pango.h file not found)

### ISSUE THREAD

**Issue by dsamt** [flutter/flutter#87509] opened 2021-08-02 18:53 UTC
I am running into an error while building the flutter engine while targeting an embedded Linux device that uses an ARM 32 bit processor. The steps to reproduce are included in this link: https://wiki.loliot.net/docs/lang/flutter/engine/flutter-engine-for-linux-arm64/ and I am getting an error related to the last step when running the command "ninja -C out/linux_debug_arm". The error I get is pasted below and it seems to not be finding a file pango.h that is located on my machine at /usr/include/pango and I don't know if it just can't find this file or if there is a different version it might be looking for. I was hoping if there was someone who has seen this problem, help me directly fix it or point me to someone or somewhere that can help resolve this issue. This is preventing me from running any flutter commands on my targeted device, while I can run everything perfectly on my host device. Any help would be greatly appreciated.

<details> 
<summary>logs</summary> 
	
```console
~/flutter-engine/engine/src$ ninja -C out/linux_release_arm/
ninja: Entering directory `out/linux_release_arm/'
[1/105] CXX obj/flutter/shell/platform/linux/flutter_linux_sources.fl_gl_area.o
FAILED: obj/flutter/shell/platform/linux/flutter_linux_sources.fl_gl_area.o
/home/daniel/flutter-engine/sdk/toolchain/bin/clang++ -MD -MF obj/flutter/shell/platform/linux/flutter_linux_sources.fl_gl_area.o.d --target=arm-linux-gnueabihf --sysroot /home/daniel/flutter-engine/sdk/sysroot -DFLUTTER_LINUX_COMPILATION -DFLUTTER_ENGINE_NO_PROTOTYPES -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=3 -DFLUTTER_RELEASE=1 -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_NOEXCEPT -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/rapidjson -I../../third_party/rapidjson/include -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -march=armv7-a -mfloat-abi=hard -mtune=generic-armv7-a -mthumb -fPIC -pipe -pthread -fcolor-diagnostics -mfpu=neon -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-parameter -Wno-unused-const-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -fvisibility=hidden --sysroot=/home/daniel/flutter-engine/sdk/sysroot -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -isystem../../../../sdk/sysroot/usr/include/gtk-3.0 -isystem../../../../sdk/sysroot/usr/include/at-spi2-atk/2.0 -isystem../../../../sdk/sysroot/usr/include/at-spi-2.0 -isystem../../../../sdk/sysroot/usr/include/dbus-1.0 -isystem../../../../sdk/sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem../../../../sdk/sysroot/usr/include/gtk-3.0 -isystem../../../../sdk/sysroot/usr/include/gio-unix-2.0 -isystem../../../../sdk/sysroot/usr/include/cairo -isystem../../../../sdk/sysroot/usr/include/pango-1.0 -isystem../../../../sdk/sysroot/usr/include/fribidi -isystem../../../../sdk/sysroot/usr/include/harfbuzz -isystem../../../../sdk/sysroot/usr/include/atk-1.0 -isystem../../../../sdk/sysroot/usr/include/cairo -isystem../../../../sdk/sysroot/usr/include/pixman-1 -isystem../../../../sdk/sysroot/usr/include/uuid -isystem../../../../sdk/sysroot/usr/include/freetype2 -isystem../../../../sdk/sysroot/usr/include/libpng16 -isystem../../../../sdk/sysroot/usr/include/gdk-pixbuf-2.0 -isystem../../../../sdk/sysroot/usr/include/libmount -isystem../../../../sdk/sysroot/usr/include/blkid -isystem../../../../sdk/sysroot/usr/include/glib-2.0 -isystem../../../../sdk/sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fno-exceptions -c ../../flutter/shell/platform/linux/fl_gl_area.cc -o obj/flutter/shell/platform/linux/flutter_linux_sources.fl_gl_area.o
In file included from ../../flutter/shell/platform/linux/fl_gl_area.cc:5:
In file included from ../../flutter/shell/platform/linux/fl_gl_area.h:8:
In file included from /usr/include/gtk-3.0/gtk/gtk.h:30:
In file included from /usr/include/gtk-3.0/gdk/gdk.h:32:
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:
/usr/include/gtk-3.0/gdk/gdktypes.h:35:10: fatal error: 'pango/pango.h' file not found
#include <pango/pango.h>
     	^~~~~~~~~~~~~~~
1 error generated.
[2/105] CXX obj/flutter/shell/platform...nux_sources.fl_key_channel_responder.o
FAILED: obj/flutter/shell/platform/linux/flutter_linux_sources.fl_key_channel_responder.o
/home/daniel/flutter-engine/sdk/toolchain/bin/clang++ -MD -MF obj/flutter/shell/platform/linux/flutter_linux_sources.fl_key_channel_responder.o.d --target=arm-linux-gnueabihf --sysroot /home/daniel/flutter-engine/sdk/sysroot -DFLUTTER_LINUX_COMPILATION -DFLUTTER_ENGINE_NO_PROTOTYPES -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=3 -DFLUTTER_RELEASE=1 -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_NOEXCEPT -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/rapidjson -I../../third_party/rapidjson/include -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -march=armv7-a -mfloat-abi=hard -mtune=generic-armv7-a -mthumb -fPIC -pipe -pthread -fcolor-diagnostics -mfpu=neon -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-parameter -Wno-unused-const-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -fvisibility=hidden --sysroot=/home/daniel/flutter-engine/sdk/sysroot -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -isystem../../../../sdk/sysroot/usr/include/gtk-3.0 -isystem../../../../sdk/sysroot/usr/include/at-spi2-atk/2.0 -isystem../../../../sdk/sysroot/usr/include/at-spi-2.0 -isystem../../../../sdk/sysroot/usr/include/dbus-1.0 -isystem../../../../sdk/sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem../../../../sdk/sysroot/usr/include/gtk-3.0 -isystem../../../../sdk/sysroot/usr/include/gio-unix-2.0 -isystem../../../../sdk/sysroot/usr/include/cairo -isystem../../../../sdk/sysroot/usr/include/pango-1.0 -isystem../../../../sdk/sysroot/usr/include/fribidi -isystem../../../../sdk/sysroot/usr/include/harfbuzz -isystem../../../../sdk/sysroot/usr/include/atk-1.0 -isystem../../../../sdk/sysroot/usr/include/cairo -isystem../../../../sdk/sysroot/usr/include/pixman-1 -isystem../../../../sdk/sysroot/usr/include/uuid -isystem../../../../sdk/sysroot/usr/include/freetype2 -isystem../../../../sdk/sysroot/usr/include/libpng16 -isystem../../../../sdk/sysroot/usr/include/gdk-pixbuf-2.0 -isystem../../../../sdk/sysroot/usr/include/libmount -isystem../../../../sdk/sysroot/usr/include/blkid -isystem../../../../sdk/sysroot/usr/include/glib-2.0 -isystem../../../../sdk/sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fno-exceptions -c ../../flutter/shell/platform/linux/fl_key_channel_responder.cc -o obj/flutter/shell/platform/linux/flutter_linux_sources.fl_key_channel_responder.o
In file included from ../../flutter/shell/platform/linux/fl_key_channel_responder.cc:5:
In file included from ../../flutter/shell/platform/linux/fl_key_channel_responder.h:8:
In file included from /usr/include/gtk-3.0/gdk/gdk.h:32:
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:
/usr/include/gtk-3.0/gdk/gdktypes.h:35:10: fatal error: 'pango/pango.h' file not found
#include <pango/pango.h>
     	^~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```
	
</details>

**Comment by TahaTesser** [comment] 2021-08-03 08:29
Hi @dsamt 
Looks like GTK needs pango, can you please try `sudo apt install libpango-1.0-0` 
`/usr/include/gtk-3.0/gdk/gdktypes.h:35:10: fatal error: 'pango/pango.h' file not found` is location in  your host, this error is not coming from Flutter engine

**Comment by dsamt** [comment] 2021-08-03 12:51
Hi @TahaTesser thanks for the reply
I understand this isn't coming from the engine I was just hoping someone may have seen a similar error here because I do indeed have pango installed and is in the /usr/include directory, as I briefly mentioned in my original post. I am just unsure why it can't be found. Thanks.

**Comment by TahaTesser** [comment] 2021-08-03 12:53
@dsamt 
I have a raspberry pi 4, I am wondering If I can reproduce this on this device. Let me try tonight.

**Comment by TahaTesser** [comment] 2021-08-03 20:12
Hey @dsamt 
I tried but couldn't set up it properly I am not familiar with embedded systems, anyways, I recommend you to ask about this on StackOverflow or Reddit
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-03 20:12 UTC
Labels: in triage
