### ISSUE TITLE
iOS Plugin stopped working after new beta

### ISSUE THREAD

**Issue by victoraugustolls** [flutter/flutter#21221] opened 2018-08-30 15:27 UTC
## Steps to Reproduce

1. With previous beta, version `0.5.1` QR Code Scanning plugin was working fine, with no problems at all.
2. After upgrading to current beta, version `0.6.0`, started receiving the following logs:

```
[+16642 ms] [VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[        ] [VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[        ] [VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
```

3. The plugin used is: https://github.com/apptreesoftware/flutter_barcode_reader
4. As it was working with previous beta, posted the issue here as it seems to be a flutter issue.

## Logs

Lost were too big for raw text on GitHub: https://justpaste.it/7e99m

```
No issues
```

```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 0.6.0 at /Users/victorsouza/Documents/Flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/victorsouza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /Users/victorsouza/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Users/victorsouza/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Victor’s iPhone • a5b21a21fc88260180f7749fa4f4d85cec4107d9 • ios • iOS 11.4.1

! Doctor found issues in 1 category.
```

**Comment by xqwzts** [comment] 2018-08-30 15:55
@victoraugustolls This sounds more like a plugin-specific error. There are already a couple of reports in the plugin's repo about iOS compatibility problems, so you're best bet would be to follow up with them there: https://github.com/apptreesoftware/flutter_barcode_reader/issues.

**Comment by victoraugustolls** [comment] 2018-08-30 15:58
The problem is that the plugin was working fine with no engine error logs with flutter beta `0.5.1`, and all was working fine!

**Comment by zoechi** [comment] 2018-08-31 09:08
Have you tried `flutter clean`?

**Comment by victoraugustolls** [comment] 2018-08-31 12:27
Yes I did!

**Comment by zoechi** [comment] 2018-08-31 12:33
The suggestion in #20777 might help.

**Comment by victoraugustolls** [comment] 2018-08-31 20:07
Will try it out as soon as possible and answer here! Probably today at night or tomorrow morning!

**Comment by pulyaevskiy** [comment] 2018-09-05 01:19
I'm seeing similar issues with google_sign_in plugin after successful sign in (when redirected back from webview).

Looked at suggested solution in #20777 and checked flutter_assets in my project which seems to be in place.

**Comment by zoechi** [comment] 2018-09-05 07:57
@Hixie I don't know how to triage

**Comment by AppleEducate** [comment] 2018-09-06 17:59
This is happening a lot to me this week. 

Xcode Log Error:
`Engine run configuration was invalid.`
`Could not launch engine with configuration.`

Flutter Doctor:
`[✓] Flutter (Channel master, v0.7.6-pre.48, on Mac OS X 10.13.6 17G65, locale en-US)`
`[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)`
`[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)`
`[✓] Android Studio (version 3.1)`
`[✓] VS Code (version 1.26.1)`
`[✓] Connected devices (3 available)`

Just gets stuck on the launch screen.

**Comment by AppleEducate** [comment] 2018-09-06 18:09
This issue comes in a lot with fastlane and automation. After debugging and testing when I go to send it to TestFlight I have to do the following steps to get it to work:

1. `flutter clean`
2. Go to Xcode > Product > Clean
3. `flutter build ios'
4. Open Runner in Xcode
5. Run Project to Make Sure it works
6. Go to Product > Archive
7. Manually Upload to iTunes Connect

Normally I would just do `fastlane ios beta`

**Comment by AppleEducate** [comment] 2018-09-06 18:37
Running:  `flutter clean` then `flutter build ios --debug` reveals a lot of errors that were not visible before.

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
Encountered error while building for device.
```

**Comment by Hixie** [comment] 2018-09-07 07:33
cc @cbracken

**Comment by pulyaevskiy** [comment] 2018-09-09 04:46
If this is of any help, I've just added an AppLifecycle listener and was printing out lifecycle events for debugging. Here is what I just saw in the logs:

```
flutter: AppLifecycleState.inactive
flutter: AppLifecycleState.paused
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
flutter: AppLifecycleState.inactive
flutter: AppLifecycleState.resumed
```

This happened while I was using image picker plugin in iOS simulator.

I'm on:

```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G2307, locale en-US)
```

**Comment by diegogalico** [comment] 2018-09-11 16:54
Hi, I am fighting with the same error, I have tried the solutions explained before without success. Basically the app get stuck on the launch screen (just in iOS). I will appreciate any help.

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                      10.1s
Starting Xcode build...
Xcode build done.                                           12.5s
[VERBOSE-2:shell.cc(181)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
        [1.1 A17CCD8F-BD62-4910-8166-A907FC1F4DAF 192.168.1.38.53082<->216.58.211.202:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.433s, DNS @0.014s took 0.012s, TCP @0.034s took 0.027s, TLS took 0.286s
        bytes in/out: 3441/1057, packets in/out: 9/10, rtt: 0.027s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone X...                          7.5s

[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.4 17E199, locale en-ES)
    • Flutter version 0.7.3 at /Users/diego.galico/Dev/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/diego.galico/Library/Android/sdk
    • Android NDK at /Users/diego.galico/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • SM G950F • 988a1b374c4f4b424c • android-arm64 • Android 8.0.0 (API 26)

**Comment by dnfield** [comment] 2018-09-24 03:13
In one case where these messages were appearing (with `open_file`), the `FlutterViewController` is trying to restart an already running isolate on `viewWillAppear`.

We should either check if the isolate is already running first, or make the call to `engine->Run` more tolerant so that it doesn't print errors out if it's already running.

**Comment by yathit** [comment] 2018-09-24 04:05
With the error, `[UIDocumentInteractionController.presentPreview](https://github.com/yathit/share_file/blob/master/ios/Classes/SwiftShareFilePlugin.swift)` did not execute.

**Comment by dnfield** [comment] 2018-09-26 05:36
I've confirmed that the erorr messages no longer show with my patch (which should be making its way to Flutter master channel before much longer) - however, even without my patch I'm not able to reproduce the freeze up.

Can you provide a minimal example that results in a freeze up?  Here's the code I'm using:

```dart
import 'package:flutter/material.dart';

import 'package:barcode_scan/barcode_scan.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    BarcodeScanner.scan().then((String s) => print(s));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

Unfortunately, right now you'd have to do a local build of the engine to test with the patch that fixes the error messages.

**Comment by thisisran** [comment] 2018-10-03 23:49
Just wanted to +1 on this. This happens to me when I run an ios document picker by using the InvokeMethod for a platform channel. The error happens after returning from that function. The error doesn't get picked up by the try catch clause (which makes sense since this is an engine error).

Was wondering when can we expect to see the patch released via flutter upgrade? not sure how to manually insert the patch and do the build myself.


Thanks for the help!

**Comment by dnfield** [comment] 2018-10-04 00:05
The patch should be present on the dev channel currently, but not beta yet.  Can you test your app out on dev?

**Comment by thisisran** [comment] 2018-10-04 10:42
I tested on dev, and the error does disappear but for some reason after the call to InvokeMethod, the lines after it never execute (just as before switching to dev), even though no error gets caught in the try catch statement.

I opened xcode to debug through there so AppDelegate.swift will be debugged as well, the document picker launches (as before), and at the end of copying the file the debugger gets to: 
flutterResult?(documentsFolder.path) which is the last statement. It seems to 'step over' it ok but then control never returns to the method in flutter that called InvokeMethod (or any code after that, for that matter) even though the application seems to continue to run ok (and I can InvokeMethod to open the document picker again).

Could this be related to the engine problem? Any ideas on how to solve? any other information you would need from my end?


Thank you in advance

**Comment by dnfield** [comment] 2018-10-06 21:44
Do you have a small sample app that reproduces this?

**Comment by thisisran** [comment] 2018-10-07 01:00
sure, so this is the code in AppDelegate.swift:

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController;
    let pickerChannel = FlutterMethodChannel.init(name: "com.flutter.myapp/documentpicker",
                                                   binaryMessenger: controller);
    let delegate = SwiftFlutterDocumentPickerDelegate();
    pickerChannel.setMethodCallHandler({
        (call: FlutterMethodCall, result: FlutterResult) -> Void in
        if ("callDocumentPicker" == call.method) {
            self.launchDocumentPicker(result: result, delegate: delegate, controller: controller);
        } else {
            result(FlutterMethodNotImplemented);
        }
    });
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
    private func launchDocumentPicker(result: FlutterResult, delegate: SwiftFlutterDocumentPickerDelegate, controller: FlutterViewController) {
        var documentTypes = ["public.data"]
        let documentPickerViewController = UIDocumentPickerViewController(documentTypes: documentTypes, in: .import)
        
        documentPickerViewController.delegate = delegate;
        
        controller.present(documentPickerViewController, animated: true, completion: nil)
    }
}

public class SwiftFlutterDocumentPickerDelegate: NSObject, UIDocumentPickerDelegate {
    fileprivate var flutterResult: FlutterResult?
    fileprivate var params: FlutterDocumentPickerParams?

    func getDocumentsDirectory() -> URL {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        let documentsDirectory = paths[0]
        return documentsDirectory
    }

    public func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentAt url: URL) {
        var documentsFolder = URL(fileURLWithPath: getDocumentsDirectory().absoluteString)
        documentsFolder.appendPathComponent(url.lastPathComponent)
        do {
            // Move file from app_id-Inbox to Documents/filename
            try FileManager.default.moveItem(atPath: url.path, toPath: documentsFolder.path)
            flutterResult?(documentsFolder.path)
        } catch {
            print(error.localizedDescription)
            flutterResult?(nil)
        }
    }
```


And this is the code from my flutter app that uses that:

```
  static const _platform = const MethodChannel('com.flutter.myapp/documentpicker');

  Future<String> _callDocumentPicker() async {
    String newFile;
    try {
      newFile = await _platform.invokeMethod(
          'callDocumentPicker'); // Using the dev channel, this does not throw an error anymore but control disappears after this line, the return newFile does not get called (and there is no error being caught here)
    } on PlatformException catch (e) {
      print('Error in document picker: $e');
    }
    return newFile;
  }
```

Control just completed disappears after the call to _callDocumentPicker, right after the invokeMethod runs (after closing the document picker dialogue).

I would assume this would happen with any native ios dialogue/UI that you open from flutter, I don't think it's unique to Document Picker.

**Comment by dnfield** [comment] 2018-10-10 03:55
@thisisran Sorry I didn't get to this sooner.  I just tested out your code and I'm not able to reproduce your issue.  Here's what I did:

1. Created a new Swift project with a single view
2. Added a flutter app to it and made the view controller a FlutterViewController
3. replaced AppDelegate.swift with what's below
4. Had below in main.dart

I don't get any errors, and control returns to my Flutter/Swift app (with a print out of the file path I chose), and I can repeatedly invoke the document picker.  

The waiting for customer response is to see if the original issue is still a problem, which it seems like it's not.  You might be having a separate issue.  If you have a minimal reproduction I'd be happy to take a look at it.

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
    ) -> Bool {
//    GeneratedPluginRegistrant.register(with: self)
    
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController;
    let pickerChannel = FlutterMethodChannel.init(name: "com.flutter.myapp/documentpicker",
                                                  binaryMessenger: controller);
    let delegate = SwiftFlutterDocumentPickerDelegate();
    pickerChannel.setMethodCallHandler({
      (call: FlutterMethodCall, result: FlutterResult) -> Void in
      if ("callDocumentPicker" == call.method) {
        self.launchDocumentPicker(result: result, delegate: delegate, controller: controller);
      } else {
        result(FlutterMethodNotImplemented);
      }
    });
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  
  private func launchDocumentPicker(result: FlutterResult, delegate: SwiftFlutterDocumentPickerDelegate, controller: FlutterViewController) {
    let documentTypes = ["public.data"]
    let documentPickerViewController = UIDocumentPickerViewController(documentTypes: documentTypes, in: .import)
    
    documentPickerViewController.delegate = delegate;
    
    controller.present(documentPickerViewController, animated: true, completion: nil)
  }
}

public class SwiftFlutterDocumentPickerDelegate: NSObject, UIDocumentPickerDelegate {
  fileprivate var flutterResult: FlutterResult?
//  fileprivate var params: FlutterDocumentPickerParams?
  
  func getDocumentsDirectory() -> URL {
    let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    let documentsDirectory = paths[0]
    return documentsDirectory
  }
  
  public func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentAt url: URL) {
    var documentsFolder = URL(fileURLWithPath: getDocumentsDirectory().absoluteString)
    documentsFolder.appendPathComponent(url.lastPathComponent)
    do {
      // Move file from app_id-Inbox to Documents/filename
      try FileManager.default.moveItem(atPath: url.path, toPath: documentsFolder.path)
      flutterResult?(documentsFolder.path)
    } catch {
      print(error.localizedDescription)
      flutterResult?(nil)
    }
}
}
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  static const _platform =
      const MethodChannel('com.flutter.myapp/documentpicker');

  void _incrementCounter() async {
    String newFile;
    try {
      newFile = await _platform.invokeMethod(
          'callDocumentPicker'); // Using the dev channel, this does not throw an error anymore but control disappears after this line, the return newFile does not get called (and there is no error being caught here)
    } on PlatformException catch (e) {
      print('Error in document picker: $e');
    }
    print(newFile);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by dnfield** [comment] 2018-10-10 03:57
I'm going to close this out since I'm fairly confident this is no longer an issue.

@thisisran - please feel free to open a new issue if you're still facing the problem you're describing.

**Closed by dnfield** 2018-10-10 03:57 UTC
Labels: e: embedder, engine, plugin, severe: crash, waiting for customer response, ⌺‬ platform-ios
