### ISSUE TITLE
Running layout_bench accumulates closures in _postFrameCallbacks over time

### ISSUE THREAD

**Issue by fsc8000** [flutter/flutter#6896] opened 2016-11-16 21:49 UTC
## Steps to Reproduce

```
flutter run -t lib/stocks/layout_bench.dart
```

Running this test for a long time makes the old-gen heap grow over time.

## Logs

Here is a screenshot from observatory. The list ```_postFrameCallbacks``` grows over time. In the example it had already >30K entries.

![screenshot from 2016-11-16 13 44 14](https://cloud.githubusercontent.com/assets/2890421/20367107/e95d322c-ac02-11e6-8075-0920a56413f3.png)

## Flutter Doctor
```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/fschneider/flutter
    • Framework revision 856fef876b (23 hours ago), 2016-11-15 14:42:52
    • Engine revision ce8b187914
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /usr/local/google/home/fschneider/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • OpenJDK Runtime Environment (build 1.8.0_102-google-v7-137518472-137512069)

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Nexus 4 • 00a422c28d51adf9 • android-arm • Android 5.1.1 (API 22)
```

@Hixie

**Comment by Hixie** [comment] 2016-11-16 22:03
The problem is something in layout is setting up a postFrameCallback but we're not actually running the pipeline (just flushing layout over and over) so nothing ever deals with those callbacks.

We should just override the binding in the benchmark so that addPostFrameCallback is a no-op.

**Comment by eseidelGoogle** [comment] 2016-11-17 17:13
Should we assert at some point in the lifecycle that postFrameCallbacks is empty?  (i.e. so running this benchmark or other unittests in checked mode would have failed instead of silently leaking?)

**Comment by Hixie** [comment] 2016-11-17 19:53
This benchmark skips the parts of the system where we could put that assert, unfortunately.

**Comment by Hixie** [comment] 2017-02-27 22:20
This should be fixed now.

**Closed by Hixie** 2017-02-27 22:20 UTC
