### ISSUE TITLE
RE: SliverAppBar flexibleSpace with height depending on children

### ISSUE THREAD

**Issue by noordawod** [flutter/flutter#21639] opened 2018-09-10 11:36 UTC
The same question as #18345, which was sadly closed by its author. Before I go to public forums with this, just a simple question:

> I have a SliverAppBar with a flexibleSpace that holds information that will change in height. I simply want my AppBar to determine it's height at runtime rather than the static expandedHeight option. Do I really need to calculate the height of this widget before I pass it to the flexibleSpace? Or is there a built in method to allow the SliverAppBar to determine that on it's own?

Can it be done somehow by using Flutter's existing components?

**Comment by zoechi** [comment] 2019-02-14 10:09
#18345 is not closed and hasn't been closed before.

Duplicate of #18345

**Closed by zoechi** 2019-02-14 10:09 UTC
Labels: f: material design, framework

**Comment by noordawod** [comment] 2019-02-14 13:48
Now that this is out of the way, have you got an idea about how to accomplish this?
