### ISSUE TITLE
Android camera records video with wrong orientation (rotation of -90.00 degrees)

### ISSUE THREAD

**Issue by jt274** [flutter/flutter#156343] opened 2024-10-07 17:29 UTC
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  camera:
    dependency: "direct main"
    description:
      path: ".."
      relative: true
    source: path
    version: "0.11.0+2"
  camera_android_camerax:
    dependency: transitive
    description:
      name: camera_android_camerax
      sha256: "59a01443c280cf969449f4b72db9396e80e5a9e8f07a2500a042906a157ce894"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.9+2"
  camera_avfoundation:
    dependency: transitive
    description:
      name: camera_avfoundation
      sha256: "7c28969a975a7eb2349bc2cb2dfe3ad218a33dba9968ecfb181ce08c87486655"
      url: "https://pub.dev"
    source: hosted
    version: "0.9.17+3"
  camera_platform_interface:
    dependency: transitive
    description:
      name: camera_platform_interface
      sha256: b3ede1f171532e0d83111fe0980b46d17f1aa9788a07a2fbed07366bbdbb9061
      url: "https://pub.dev"
    source: hosted
    version: "2.8.0"
  camera_web:
    dependency: "direct overridden"
    description:
      path: "../../camera_web"
      relative: true
    source: path
    version: "0.3.5"
```

</details>

### Steps to reproduce

1. Run current camera plugin example app (tried Galaxy S20 and Emulator of Pixel 7 Pro API 35)
2. Select a camera
3. Take video
4. See video showing sideways in the thumbnail.

Reverting to `camera_android_camerax` `0.6.8+3` did not fix. I'm not sure at what point this stopped working.

### Expected results

Video should be recorded as shown in the `CameraPreview` widget without any rotation flags for easy playback on any platform. Video shows correctly in preview widget.

### Actual results

Video is recorded with a rotation of 90 degrees CCW (left). Analyzing the video file with `ffprobe`, it appears to have a metadata flag of `displaymatrix` set to `rotation of -90.00 degrees`.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22621.4169], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.10.0)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.94.0)
[√] Connected device (5 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-10-08 08:43
Hi @jt274 
`camera_android_camerax` example is using `video_player` to play the output video and this is a known issue at https://github.com/flutter/flutter/issues/154696. Marking this as a duplicate of that issue, so please follow it for updates.

**Comment by jt274** [comment] 2024-10-08 15:06
@huycozy I believe this is a separate issue. Yes, the `video_player` package is not properly rotating videos with `displaymatrix` rotation metadata flags. However, the camera package should be recording videos according to their original orientation, not a default orientation and adding a flag.

**Current state**
1. Put phone in portrait up mode and record video
2. Video records at 1920x1080 resolution (landscape left) with `displaymatrix` flag of -90 rotation
3. Video player on any platform must rotate video according to metadata flag (+90 rotation) to display properly. Players/platforms other than `video_player` may have the same rotation issue.

**Expected state**
1. Put phone in portrait mode and record video
2. Video records at 1080x1920 resolution (portrait up) with no `displaymatrix` flag.
4. Video plays back on all platforms with no required rotation by a video player.

**Comment by huycozy** [comment] 2024-10-09 03:34
Your steps above and sample code match what was reported at https://github.com/flutter/flutter/issues/154696 (see demo video at https://github.com/flutter/flutter/issues/154696#issue-2509236120). I also used [camerax example](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax/example) to verify that issue.

To confirm this, can you try using `video_player_android: 2.7.1` (without Impeller integration)?

**Comment by jt274** [comment] 2024-10-09 04:15
What I'm saying is if I download the recorded video from the device, I can see that a video recorded in portrait mode was encoded in a landscape orientation with a metadata flag to tell the player to rotate the video back to portrait mode during playback. This will cause issues for players that do not properly interpret this flag (including `video_player`).

The proposed fix is to encode the portrait video in portrait (not landscape), without a rotation flag set. This would ensure proper playback on all platforms and players. The video would record in 1080 width x 1920 height, instead of 1920 width x 1080 height and a rotation flag.

I confirmed this flag and resolution by downloading the recorded file to a PC and analyzing it with `ffprobe`.

**Comment by jt274** [comment] 2024-10-09 04:46
> Your steps above and sample code match what was reported at #154696 (see demo video at [#154696 (comment)](https://github.com/flutter/flutter/issues/154696#issue-2509236120)). I also used [camerax example](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax/example) to verify that issue.
> 
> To confirm this, can you try using `video_player_android: 2.7.1` (without Impeller integration)? (see [#154696 (comment)](https://github.com/flutter/flutter/issues/154696#issuecomment-2394772134))

I pinned `video_player_android: 2.7.1` and can confirm:

1. The video is still recorded with the wrong orientation, and includes the `displaymatrix` rotation flag.
2. The video player now correctly plays the video by rotating it during playback.

So it fixes the **PLAYBACK** error, but not the **RECORDING** issue.

**Comment by huycozy** [comment] 2024-10-10 03:40
Thanks for your update. 

I used `ffprobe` with the output video from [camerax example](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax/example) here and see `displaymatrix` value is `rotation of -90.00 degrees`:

```console
➜  Desktop ffprobe REC235196964642373781.mp4 
ffprobe version 7.0.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'REC235196964642373781.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2024-10-09T11:51:07.000000Z
    com.android.version: 14
  Duration: 00:00:04.39, start: 0.000000, bitrate: 6114 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 720x480, 6108 kb/s, 29.86 fps, 30 tbr, 90k tbn (default)
      Metadata:
        creation_time   : 2024-10-09T11:51:07.000000Z
        handler_name    : VideoHandle
        vendor_id       : [0][0][0][0]
      Side data:
        displaymatrix: rotation of -90.00 degrees
```

However, when I play video on macOS (with VLC app), I see its orientation keeps portrait as expected:

<details>
<summary>camera_android_camerax example output video</summary>

https://github.com/user-attachments/assets/955fc6ce-1b57-434f-be10-7e1bb8d7a5c7
</details>

Marking this as a separate issue with the camera package to get others' perspectives. Current package version: `camera_android_camerax: 0.6.10`

**Comment by camsim99** [comment] 2024-10-10 18:17
From Android triage: Closing this as a duplicate of https://github.com/flutter/flutter/issues/154241 and https://github.com/flutter/flutter/issues/154696. Feel free to leave any repro reports under https://github.com/flutter/flutter/issues/154241 if `camera_android_camerax: 0.6.10` did not fix your issue with the camera preview orientation (not the video playback)!

**Closed by camsim99** 2024-10-10 18:17 UTC
Labels: platform-android, p: camera, package, has reproducible steps, team-android, fyi-ecosystem, found in release: 3.24
