### ISSUE TITLE
`FlutterError.onError` is not called when framework throws an error

### ISSUE THREAD

**Issue by chvin** [flutter/flutter#78503] opened 2021-03-18 03:33 UTC
### flutter doctor:
```bash
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
```

### Code demo:
```dart
import 'package:flutter/material.dart';

void main() {
  FlutterError.onError = (FlutterErrorDetails details) {
    print('~~~~~~~ FlutterError catch: $details');
  };
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FlutterError.onError not called',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('FlutterError.onError not called'),
        ),
        body: Row(
          children: [
            Text('A' * 1000),
          ],
        ));
  }
}
```

### Screenshot
![image](https://user-images.githubusercontent.com/5383506/111569356-6e1f4f80-87dd-11eb-884c-118e9e60df67.png)

### Question
![image](https://user-images.githubusercontent.com/5383506/111569481-b8a0cc00-87dd-11eb-983e-eef4d6f0c25a.png)
FlutterError.onError not called when flutter framework error

**Comment by chvin** [comment] 2021-03-18 05:47
I switch the Flutter version to 1.22.0, FlutterError.onError works!
```bash
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.0, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

![image](https://user-images.githubusercontent.com/5383506/111579109-5c937300-87f0-11eb-9ae4-0249de4db1d2.png)

So in Flutter 2.0.2 version, there is a problem with FlutterError.onError.

**Comment by pedromassangocode** [comment] 2021-03-18 10:19
I was able to reproduce this issue. I can confirm that in Flutter 1.22.0 the `FlutterError.onError` was being called in debug but in Flutter 2 it is not called.

<details>
<summary>logs (Flutter 1.22.0)</summary>

```bash
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutterm run
Using hardware rendering with device sdk gphone x86 64. If you notice graphics artifacts,
consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        44.5s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 1.7s
I/flutter_exampl( 5826): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl( 5826): Unquickening 12 vdex files!
W/flutter_exampl( 5826): Unexpected CPU variant for X86 using defaults: x86_64
W/flutter_exampl( 5826): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_exampl( 5826): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl( 5826): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl( 5826): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Waiting for sdk gphone x86 64 to report its views...                15ms
I/OpenGLRenderer( 5826): Davey! duration=1289ms; Flags=1, IntendedVsync=440941553762, Vsync=441074887090, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=441086711472, AnimationStart=441086715733, PerformTraversalsStart=441086718538, DrawStart=442114499297, SyncQueued=442117729054, SyncStart=442119292708, IssueDrawCommandsStart=442119678871, SwapBuffers=442166883865, FrameCompleted=442232890228, DequeueBufferDuration=38157672, QueueBufferDuration=1739182, GpuCompleted=129415406168625, 
I/Choreographer( 5826): Skipped 68 frames!  The application may be doing too much work on its main thread.
Syncing files to device sdk gphone x86 64...                     1,984ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 64 is available at:
http://127.0.0.1:55859/H5xl2EyuBuA=/
I/flutter ( 5826): ~~~~~~~ FlutterError catch: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞══════════════════════
I/flutter ( 5826): The following assertion was thrown during layout:
I/flutter ( 5826): A RenderFlex overflowed by 8740 pixels on the right.
I/flutter ( 5826): 
I/flutter ( 5826): The relevant error-causing widget was:
I/flutter ( 5826):   Row
I/flutter ( 5826):   file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:27:15
I/flutter ( 5826): 
I/flutter ( 5826): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter ( 5826): The edge of the RenderFlex that is overflowing has been marked in
I/flutter ( 5826): the rendering with a yellow and black striped pattern. This is
I/flutter ( 5826): usually caused by the contents being too big for the RenderFlex.
I/flutter ( 5826): Consider applying a flex factor (e.g. using an Expanded widget)
I/flutter ( 5826): to force the children of the RenderFlex to fit within the
I/flutter ( 5826): available space instead of being sized to their natural size.
I/flutter ( 5826): This is considered an error condition because it indicates that
I/flutter ( 5826): there is content that cannot be seen. If the content is
I/flutter ( 5826): legitimately bigger than the available space, consider clipping
I/flutter ( 5826): it with a ClipRect w
```
</details>


<details>
<summary>flutter doctor -v (1.22.0)</summary>

```bash
[✓] Flutter (Channel unknown, 1.22.0, on macOS 11.2.3 20D91, locale en-AO)
    • Flutter version 1.22.0 at /Users/pedromassango/Code/flutter_master
    • Framework revision d408d302e2 (6 months ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11
      (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.3
      20D91
    • Web Server (web)           • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.0.2 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by jason-simmons** [comment] 2021-03-18 20:11
The `FlutterError.onError` handler is being replaced by a handler used by the Flutter development tools (see https://github.com/flutter/flutter/commit/5b1aa60a46bf6317b1ff1e0e10e5751e4491881c)

One way to work around this would be setting `FlutterError.onError` after calling `WidgetsFlutterBinding.ensureInitialized()`

**Comment by goderbauer** [comment] 2021-03-22 16:31
We should document this behavior on `FlutterError.onError`.

/cc @kenzieschmoll

**Comment by kenzieschmoll** [comment] 2021-03-23 15:58
If it is a common use case to add a custom onError handler to an app, perhaps we should allow for multiple onError handlers instead of only one. Overriding the FlutterError.onError handler set by the framework could have some unintended consequences like disabling certain tooling features that depend on the structured error handler being set (structured logs, deep links to the inspector, error notifications in DevTools, etc.)

**Comment by srgbrito** [comment] 2021-04-10 13:36
It is very useful for applications to have a global Error handler, to ensure that ALL errors will be handled by the application.
Without this, we have to put try / catch in all the onPressed () of the application's buttons.
It is very laborious and unnecessary, as they will usually only display an error message.
That global handler can decide what to do when he catches an exception that is not handled by the application.

**Comment by srgbrito** [comment] 2021-04-10 14:02
> If it is a common use case to add a custom onError handler to an app, perhaps we should allow for multiple onError handlers instead of only one. Overriding the FlutterError.onError handler set by the framework could have some unintended consequences like disabling certain tooling features that depend on the structured error handler being set (structured logs, deep links to the inspector, error notifications in DevTools, etc.)

It is very useful for applications to have a global Error handler, to ensure that ALL errors will be handled by the application.
Without this, we have to put try / catch in all the onPressed () of the application's buttons.
It is very laborious and unnecessary, as they will usually only display an error message.
That global handler can decide what to do when he catches an exception that is not handled by the application.

**Comment by nt4f04uNd** [comment] 2021-08-16 23:50
duplicate of https://github.com/flutter/flutter/issues/41540

**Comment by nt4f04uNd** [comment] 2021-12-16 22:12
Closing as duplicate of https://github.com/flutter/flutter/issues/48972

**Closed by nt4f04uNd** 2021-12-16 22:12 UTC
Labels: severe: regression, framework, a: error message, has reproducible steps, found in release: 2.0, found in release: 2.1
