### ISSUE TITLE
"command 'flutter.createProject' not found" in VS Code after following Getting Started guide

### ISSUE THREAD

**Issue by stt106** [flutter/flutter#14928] opened 2018-02-27 20:16 UTC
From URL: https://flutter.io/get-started/editor.md

I followed the Configure Editor with VS Code. However after installing the Dart Code plugin (2.9.0), when I tried to run Flutter: New Project command, I got an error saying "command 'flutter.createProject' not found" in VS Code. Seems that something is wrong with my Dart Code plugin install as there is no other commands available when typing Flutter in VS Code, the only one available is Flutter: New Project which doesn't work.
Running flutter doctor in the cmd, the only issue it shows is "Connected devices: No devices available"; everything else ticks.

**Comment by eskerber** [comment] 2018-02-27 20:26
Google led me here 9 minutes after it was posted.

The beta edges... they are bloody 😸

**Comment by chrisdunelm** [comment] 2018-02-27 22:16
Also got this.
Linux - Ubuntu 17.10
VS Code 1.20.1; with Dart Code extension v2.9.0

I also had to manually set "dart.sdkPath" in VS Code, not sure if this is relevant or not.

**Comment by chrisdunelm** [comment] 2018-02-27 22:19
Uninstalling and re-installing the "Dart Code" extension fixed this for me.

**Comment by InMatrix** [comment] 2018-02-27 22:24
Cc: @DanTup

**Comment by DanTup** [comment] 2018-02-27 22:51
Hey all,

I think there are a couple of issues here:

1. Windows is super-bad with PATH updates. If you add flutter to your PATH and don't reboot, VS Code doesn't get the updated path and therefore Dart Code doesn't find Flutter
2. When Dart Code can't find Flutter/Dart and fails to activate the extension, it results in the "New Project" command not being registered, which results in a poor error message ("command 'flutter.createProject' not found")

I've raised https://github.com/Dart-Code/Dart-Code/issues/624 to handle `2` better though I don't know if there's much I can do about `1`. I'll do some testing and we can't handle it better we can update the docs to cover this.

@chrisdunelm 

> I also had to manually set "dart.sdkPath" in VS Code

You shouldn't need to do this is dart/flutter on in your PATH (and if on Windows, rebooted so it actually works - restarting Code does not result in this being picked up in my experience!). If Dart Code is finding flutter correctly now, I would remove that setting so that it uses the Dart version shipped with flutter.

(@InMatrix thanks!)

**Comment by chrisdunelm** [comment] 2018-02-27 23:45
@DanTup
I've now removed "dart.sdkPath" and reloaded the VSCode project. It works correctly.
flutter is on my path.

It's likely that I hadn't restart VSCode after installing flutter when I first installed the Dart Code extension; which would explain why it failed the first time.
As you say, better error messages here would be good.

Thanks.

**Comment by Herohtar** [comment] 2018-02-28 01:40
@DanTup The actual cause of this issue isn't Windows being bad about `path` updates; it's that you actually have to have **dart** in the `path` as well, not just flutter.

I followed the configuration instructions in "Getting Started" and added flutter to `path` before opening VS Code and installing the Dart Code extension. I was able to run **Flutter: Run Flutter Doctor** and everything checked out. I then tried **Flutter: New Project** and got the error message *"command 'flutter.createProject' not found"* in addition to a message saying it couldn't find the Dart SDK and that if it was installed I could set the `dart.sdkPath` setting in VS Code.

I tried rebooting and uninstalling/reinstalling the Dart Code extension, but it still didn't work. However, after adding the full path to the Dart SDK to `path` (`C:\[...]\flutter\bin\cache\dart-sdk\bin`) it now works.

**Comment by DanTup** [comment] 2018-02-28 07:17
> The actual cause of this issue isn't Windows being bad about path updates; it's that you actually have to have dart in the path as well, not just flutter

If that's what's happening, it's not intended. For a flutter project we find flutter and then search in its cache for Dart (I guess you need to have also run flutter once for this to exist - I'll check the docs mention this). The reason the error message says Dart instead of Flutter in this case is that when the extension is activated by the command the startup code doesn't realise it will be working with Flutter so shows the Dart version of the error message.

I'm gonna see if Code provides context at startup that will allow us to detect this and provide a better error (if not, I can think of some workarounds).

Providing a `dart.sdkPath` is not a good idea for Flutter as it won't track the version shipped with Flutter (unless you point out at the version inside Flutter, but that's not ideal if you also work on Dart CLI/web/etc).

**Comment by DanTup** [comment] 2018-02-28 08:51
This should be fixed in v2.9.1 of Dart Code (https://github.com/Dart-Code/Dart-Code/issues/624)

The changes are:

1. Handle the `Flutter: New Project` command even when the extension fails to find SDKs, to ensure `command 'flutter.createProject' not found` is not shown
2. In the handling of the command (above) force the project type to Flutter so that the error message shown is the Flutter error and not the Dart error

I've also tweaked the messages in both Dart and Flutter activation failures to include `(you may need to restart)` to encourage people to try that rather than explicitly adding settings (using the settings is not a recommended approach unless you're explicitly trying to override the detected paths now).

If anyone is still having issues after updating to v2.9.1 please let me know (the best place is to raise issues in the [Dart Code](https://github.com/Dart-Code/Dart-Code/) repo, or grab me in [Gitter](https://gitter.im/dart-code/Dart-Code) if it's daylight hours in the UK).

**Comment by DanTup** [comment] 2018-02-28 08:54
@mit-mit I believe this is sorted now, though I don't know if we should add a note to the "Adding to path" section of installation about restarting. Based on [this](https://serverfault.com/a/489539) I'm guessing that environment/PATH changes don't propogate to explorer, so if you're launching Code from the taskbar, it has stale info.

**Comment by cbracken** [comment] 2018-03-02 00:07
@DanTup is this resolved? Is there a PR out for the setup documentation (re: path) or do we still need to document this.

**Comment by mit-mit** [comment] 2018-03-02 07:07
Path change PR here now: https://github.com/flutter/website/pull/853

**Comment by mit-mit** [comment] 2018-03-02 07:07
@DanTup with that we can close this, right?

**Comment by DanTup** [comment] 2018-03-02 07:11
Yep, LGTM - thanks!

**Comment by mit-mit** [comment] 2018-03-02 08:42
Thanks, closing.

**Closed by mit-mit** 2018-03-02 08:42 UTC
Labels: dev: first hour, dev: ide - vscode

**Comment by DanTup** [comment] 2018-03-05 10:07
For anyone still having path issues, please try [v2.10.0 Beta 1 of Dart Code](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) and it should now allow you to easily select the SDK folder from the error message.

**Comment by Arcadie90** [comment] 2019-06-02 00:11
I had the same problem and solved it by doing:
1. Uninstall Visual Studio dart and flutter extensions and close Visual Studio.
2. After this go to: Users\.vscode\extensions and remove all the files.
3. Open Visual Studio and install dart and flutter extensions.
 
The cause for me might be that when you uninstall an extension files aren't erased.

**Comment by DanTup** [comment] 2019-06-02 08:24
If that fixes the problem, it sounds like the extension didn't install correctly. This sounds a bit like https://github.com/microsoft/vscode/issues/73134 where VS Code didn't unpack the extension correctly. If anyone sees this, please try to get a copy of the logs mentioned in that issue (and post there) for the VS Code team to review. Thanks!

**Comment by 1990b** [comment] 2019-07-14 08:50
Extension host terminated unexpectedly. hi! my matter is when I want to do a space between my code it refuses! and show me this error message

**Comment by DanTup** [comment] 2019-07-14 09:10
@1990b that does not seem related to this issue, and posting on closed issues can easily go unnoticed. Please open a new issue - though since this is VS Code specific, please open it at https://github.com/Dart-Code/Dart-Code.

Please include the versions of VS Code and the Dart+Flutter extensions you're using, as well as any output shown in the developer console (click Tools -> Toggle Developer Tools then click the Console tab).
