### ISSUE TITLE
NestedScrollView mixes up different Tabs scroll position

### ISSUE THREAD

**Issue by aletorrado** [flutter/flutter#32564] opened 2019-05-11 19:33 UTC
Hi! I've made a single file demo showing how NestedScrollView mixes up the scroll position of different tabs (using `wantKeepAlive => true` to prevent the tabs from being disposed).

## Steps to Reproduce

Just run this single file demo, and scroll the first tab. You will notice when moving around that the other tabs are being scrolled as well.

```
import 'package:flutter/material.dart';

const TABS = 3;

class TabContent extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => _TabContentState();

}

class _TabContentState extends State<TabContent> with AutomaticKeepAliveClientMixin {

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        for (var i=0; i<200; i++)
          Text("Some text $i", style: TextStyle(fontSize: 20)),
      ],
    );
  }

}

class TestPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: TABS,
        child: Scaffold(
          body: NestedScrollView(
            headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                SliverAppBar(
                  title: Text("Demo"),
                  pinned: true,
                  bottom: TabBar(
                    tabs: <Widget>[
                      for (var i=0; i<TABS; i++) 
                        Tab(child: Text("Tab $i"),),
                    ],
                  ),
                )
              ];
            },
            body: TabBarView(
              children: <Widget>[
                for (var i=0; i<TABS; i++)
                  TabContent()
              ],
            ),
          ),
        ),
      ),
    );
  }

}
```

## `flutter doctor` output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by Piinks** [comment] 2020-01-23 23:08
I think this is a duplicate of #36419. If that is not the case, feel free to re-open this bug. :)

**Closed by Piinks** 2020-01-23 23:08 UTC
Labels: f: material design, framework
