### ISSUE TITLE
Keyboard Flickering Issue on Android Devices

### ISSUE THREAD

**Issue by nizxcoder** [flutter/flutter#149131] opened 2024-05-27 12:11 UTC
### Steps to reproduce

Issue Description:

When tapping on the "Password" and "Email" text fields in my Flutter app on an Android 14 device, the keyboard flickers intermittently, causing a disruptive user experience.

Steps to Reproduce:

Launch the Flutter app on an Android 14 device.
Navigate to the screen containing the "Password" and "Email" text fields.
Tap on the "Password" text field.
Tap on the "Email" text field.
Observe the keyboard behavior, noting any flickering or unusual movements.

Additional Information:
Flutter SDK Version: 3.22.1
Device/Emulator: Android 14

Possible Causes:
Conflicting focus requests or listeners
Bug in the Flutter framework
Notes:

I have already ruled out the following potential causes:

Consistent keyboard types set for text fields
Focus handling conflicts
Flutter SDK is up to date
Tested on different devices and emulators, the issue persists on Android 14the 

### Expected results

Expected Behavior:

The keyboard should smoothly appear and disappear when tapping on text fields, without any flickering or interruptions.

### Actual results

Actual Behavior:

The keyboard flickers intermittently when tapping on the "Password" and "Email" text fields on an Android 14 device, making text input difficult and causing a disruptive user experience.

### Code sample

Relevant Code Snippets:

TextField(
  decoration: const InputDecoration(
    labelText: 'Username',
  ),
  keyboardType: TextInputType.text,
  focusNode: userNode,
),
TextField(
  decoration: const InputDecoration(
    labelText: 'Password',
  ),
  obscureText: true,
  keyboardType: TextInputType.number,
  focusNode: passNode,
),
TextField(
  decoration: const InputDecoration(
    labelText: 'Email',
  ),
  keyboardType: TextInputType.number,
  focusNode: emailNode,
),

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/76437265/95c6e832-b377-43df-aa9b-209d65436b72

### Logs

D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring on
D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring on
D/InsetsController(29368): show(ime(), fromIme=true)
I/ImeTracker(29368): com.example.test_app:a37792fc: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/ImeTracker(29368): com.example.test_app:5906ebad: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
D/InputMethodManager(29368): showSoftInput() view=io.flutter.embedding.android.FlutterView{49444ff VFE...... .F...... 0,0-1440,3200 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(29368): show(ime(), fromIme=true)
I/ImeTracker(29368): com.example.test_app:5906ebad: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/HandWritingStubImpl(29368): getCurrentKeyboardType: 1
I/HandWritingStubImpl(29368): getCurrentKeyboardType: 1
I/ImeTracker(29368): com.example.test_app:595cce3: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
D/InputMethodManager(29368): showSoftInput() view=io.flutter.embedding.android.FlutterView{49444ff VFE...... .F...... 0,0-1440,3200 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(29368): Flattened final assist data: 384 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring on
D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(29368): The input method toggled cursor monitoring on
D/InsetsController(29368): show(ime(), fromIme=true)
I/ImeTracker(29368): com.example.test_app:595cce3: onCancelled at PHASE_CLIENT_APPLY_ANIMATION

### Flutter Doctor output

PS C:\Users\hp\OneDrive\Desktop\WIS Module\test\test_app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.26120.461], locale en-US)
    ! Warning: `dart` on your path resolves to C:\Program Files\Dart\dart-sdk\bin\dart.exe, which is not inside your
      current Flutter SDK checkout at C:\Users\hp\Downloads\flutter_windows_3.13.6-stable\flutter. Consider adding
      C:\Users\hp\Downloads\flutter_windows_3.13.6-stable\flutter\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment] 2024-05-27 13:05
Closing as duplicate of https://github.com/flutter/flutter/issues/148530

**Closed by darshankawar** 2024-05-27 13:05 UTC
Labels: in triage
