### ISSUE TITLE
The cursor vertical offset in the TextField has incorrect position if there is no text in the TextField

### ISSUE THREAD

**Issue by bubnov** [flutter/flutter#122100] opened 2023-03-07 13:45 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Set focus to the text field and check the cursor vertical offset with and without text

**Expected results:** The cursor position is expected to have the same vertical offset.

**Actual results:** When there is no text in the text field, the vertical position of the cursor is a bit lower than the text is present (check the attached video and screenshot below).

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: IssueDemo(),
    ),
  );
}

class IssueDemo extends StatelessWidget {
  const IssueDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTextHeightBehavior(
        textHeightBehavior: const TextHeightBehavior(applyHeightToFirstAscent: false),
        child: Center(
          child: Container(
            color: Colors.blueGrey[50],
            padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
            child: TextField(
              controller: TextEditingController(text: 'Text'),
              style: const TextStyle(
                fontSize: 40,
                textBaseline: TextBaseline.ideographic,
                color: Colors.black,
              ),
              textAlign: TextAlign.right,
              cursorColor: Colors.red,
              cursorWidth: 4,
              cursorRadius: const Radius.circular(2),
              decoration: const InputDecoration(
                fillColor: Colors.purple,
                isCollapsed: true,
                border: UnderlineInputBorder(
                  borderSide: BorderSide(width: 0, style: BorderStyle.none),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
% fvm flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2 22D49 darwin-arm64, locale en-CY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.76.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

https://user-images.githubusercontent.com/818612/223435621-6d92682e-3e17-4fd5-8462-7c5681b3653f.mp4

![CleanShot 2023-03-07 at 15 32 41@2x](https://user-images.githubusercontent.com/818612/223439556-1c2419b3-95cb-4817-99cc-7461dfe34936.png)

**Comment by danagbemava-nc** [comment] 2023-03-07 14:01
Hi @bubnov, I believe this is a duplicate of https://github.com/flutter/flutter/issues/92080. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2023-03-07 14:01 UTC
Labels: in triage

**Comment by bubnov** [comment] 2023-03-07 14:23
@danagbemava-nc it is ok, thanks! The issue you have mentioned is pretty old though.

**Comment by danagbemava-nc** [comment] 2023-03-08 06:43
Yhh, but the team is aware of it. If you look closely, you'll see there's a pr mention which means that issue is being worked on
