### ISSUE TITLE
Janky scrolling on iPhone X/Xs that disappears when screen recording is active

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#40042] opened 2019-09-07 22:36 UTC
- I experience the janky scrolling on iPhone X/Xs, but never on any Android device.

- Both finger-down and kinetic scrolling of vertical and horizontal list views are janky.

- It affects simple list views and complex ones.

- It only happens in portrait, but never in landscape mode.

- When I do screen recording, as soon as the recording starts after the 3s countdown, the jank fully disappears until I turn recording off.

**Comment by derolf** [comment] 2019-09-07 22:50
Related to https://github.com/flutter/flutter/issues/38293 ?

**Comment by derolf** [comment] 2019-09-10 16:32
I don’t think it’s a duplicate of the other one. This one here disappears during screen recording, but #31086 doesn’t.

**Comment by derolf** [comment] 2019-09-13 20:50
I tested with master channel from today. Still exists. What can I do to help finding the cause?

**Comment by liyuqian** [comment] 2019-09-16 23:33
Thank you for reporting this! Can you please provide us more information so we can reproduce and analyze this issue?

1.  Please tell us exactly how to reproduce the problem you are running into.

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

3.  Switch flutter to master channel and run this app on a physical device
     using profile mode with Skia tracing enabled, as follows:
       ```
       flutter channel master
       flutter run --profile --trace-skia
       ```
     Then press ‘P’ to enable the performance overlay.

     The bleeding edge master channel is encouraged here because Flutter is
     constantly fixing bugs and improving its performance. Your problem in an
     older Flutter version may have already been solved in the master channel.

4.  Record a video of the performance issue using another phone so we
     can have an intuitive understanding of what happened. Don’t use
     "adb screenrecord", as that affects the performance of the profile run.

5.  Open Observatory and save a timeline trace of the performance issue
     so we know which functions might be causing it. See "How to Collect
     and Read Timeline Traces" on this blog post:
       https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af03#a499

**Comment by liyuqian** [comment] 2019-10-24 22:58
This might be a throttling or scheduling issue that we're also seeing in our lab: https://github.com/flutter/flutter/issues/43452

Can you please provide more traces, reproduction apps, and video screenshots so we can better investigate this?

**Comment by sooxiaotong** [comment] 2019-10-24 23:15
@liyuqian you could try out the pesto in flutter gallery on Flutter (Channel master, v1.10.15-pre.186) it behaves the same

**Comment by liyuqian** [comment] 2019-11-06 20:05
@sooxiaotong : I just tested the Pesto on an iPhone Xs with Flutter master channel. I didn't see any jank even with very low brightness and no screen recording: https://photos.google.com/share/AF1QipPdJym1j5uc1irndxEmBZm_8okzkHu3PeIF3xPxP1S1xyul2Xbbt13MCIHTbrkltw?key=OU5YTGVESldnNTVQUUdHUVJVN1JZazFnMjNxaHVR

One thing I noticed is that our Pesto demo is only enabled in debug mode. I have to comment out the `assert` in https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/demos.dart#L561 to test it in the profile mode. Are you testing it in debug mode?

**Comment by sooxiaotong** [comment] 2019-11-07 00:10
@liyuqian yep in debug mode, you could try switch to diff app and scroll (like fb or insta)  then switch back to the gallery and scroll , you will notice the janky with low brightness

**Comment by leejh10003** [comment] 2019-11-12 13:42
Same on here too. I'm using iPhone XS as a test device, and have the same issue. Janky scrolling disappears right after turning on screen recording. I even tried release mode build, but do not affect.
But on iPhone 6S, regardless of screen recording, scrolling is super fast.
+ I'm not testing Presto. Testing my project.

**Comment by leejh10003** [comment] 2019-11-12 14:43
Maybe this issue is related to #31086

**Comment by liyuqian** [comment] 2019-11-12 18:24
@sooxiaotong @leejh10003 : thanks for the info! I'll keep investigating. To accelerate my investigation and ensure that I'm finding the right issue, can you please post:
1) a slo-mo video screenshot of the janky scroll in profile mode with performance overlay turned on
2) the corresponding timeline trace of that janky scroll
3) the version of Flutter

**Comment by leejh10003** [comment] 2019-11-13 15:08
The flutter version is 1.9.1+hotfix.6 
If video and trace size is too big, I'll compress and upload it again.
[issue.zip](https://github.com/flutter/flutter/files/3841832/issue.zip)
[report.z01.zip](https://github.com/flutter/flutter/files/3841835/report.z01.zip)
Timeline track JSON and video are compressed. Please rename report.z01.zip into report.z01 and unzip.

**Comment by sooxiaotong** [comment] 2019-11-14 10:37
@leejh10003 youre not running in profile mode with the perm overlay, and the slow-mo video seems weird and jumpy.

**Comment by leejh10003** [comment] 2019-11-14 11:59
@sooxiaotong Okay. I'll do it again.

**Comment by leejh10003** [comment] 2019-11-24 07:40
I solved it. Just upgrading flutter version to 1.11.0(beta) solved the issue.

**Comment by liyuqian** [comment] 2019-11-25 22:06
@leejh10003 : I'm glad that it's fixed! Closing this issue. Please feel free to re-open it if you still find it not fixed in the latest beta or master branch.

**Closed by liyuqian** 2019-11-25 22:06 UTC
Labels: e: device-specific, engine, f: scrolling, severe: performance, ⌺‬ platform-ios

**Comment by sroddy** [comment] 2021-03-26 16:56
Hi @liyuqian,
I'm experiencing this very same issue on current Stable (2.0.3) on my iPhone 12 mini when running on iOS 14.4.
I can easily reproduce it when scrolling down the list that I see in the current Reflectly app right after resuming the app from background.
This issue is really noticeable in Add2App because it doesn't happen only when app is resumed from background but also when new `FlutterViewController`s are pushed/presented (even with new lightweight engines). It looks like this weird behaviour is tied to something that happens right after the viewDidAppear call inside the FlutterViewController.
As stated above, when screen recording is active everything runs butter-smooth.

**Comment by sroddy** [comment] 2021-03-28 13:55
I've managed to perform a profile-run both with screen recording active and not active (and --trace-skia flag).
in the first case you see that the frames timings are constantly below 16ms.
in the second one you can observe that for ~half of the trace, the raster thread is unable to keep the pace of the rendering, but after a while it goes back to normal (and no jank is observed anymore)

[on_resume_jank.zip](https://github.com/flutter/flutter/files/6217423/on_resume_jank.zip)

**Comment by sroddy** [comment] 2021-04-09 00:52
@gaaclarke do you think it is possible to reopen this issue and try to understand why this is happening?
As I said above, this is especially painful in Add2App because it consistently happens every time a new FlutterViewController is pushed/presented
Thanks

**Comment by sroddy** [comment] 2021-04-13 00:41
@TahaTesser may I ask you to take a look at this issue and see if it's worth to reassess/reopen it?
Otherwise I'll create a new one.
Thanks

**Comment by TahaTesser** [comment] 2021-04-13 09:54
@sroddy 
The issue is too old to reopen, please file a new issue with all the details (tag me)
