### ISSUE TITLE
Chinese FontWeight on Flutter3.0.5 not work

### ISSUE THREAD

**Issue by jackTang11** [flutter/flutter#107809] opened 2022-07-18 01:29 UTC
FontWeight.w100~w500 will display as FontWeight.w400 when showing Chinese characters

![image](https://user-images.githubusercontent.com/7345590/179433663-78732eb1-3727-4061-a0b9-865a27dd44a1.png)

**Comment by jackTang11** [comment] 2022-07-18 01:30
Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/jack/Documents/work/softwork/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/jack/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • FAC38063-F678-44FE-AE0C-324EF776E2A2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by jackTang11** [comment] 2022-07-18 01:31
![image](https://user-images.githubusercontent.com/7345590/179433760-52627379-c528-43f4-9a10-8c4968fedb0f.png)

**Comment by jackTang11** [comment] 2022-07-18 01:35
![image](https://user-images.githubusercontent.com/7345590/179433927-110e57ba-66d5-4bca-a582-a9843c1ee8f7.png)

```
Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text('你好,谢谢你',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            SizedBox(height: 1),
            Text('Hello, thank you', style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            Text('你好,谢谢你',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            SizedBox(height: 1),
            Text('Hello, thank you', style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            Text('你好,谢谢你',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            SizedBox(height: 1),
            Text('Hello, thank you', style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
            SizedBox(height: 40),
            Text('你好,谢谢你,Hello, thank you',
                style: TextStyle(fontWeight: FontWeight.w100, fontSize: 30)),
            SizedBox(height: 10),
            Text('你好,谢谢你,Hello, thank you',
                style: TextStyle(fontWeight: FontWeight.w200, fontSize: 30)),
            SizedBox(height: 10),
            Text('你好,谢谢你,Hello, thank you',
                style: TextStyle(fontWeight: FontWeight.w300, fontSize: 30)),
            SizedBox(height: 10),
            Text('你好,谢谢你,Hello, thank you',
                style: TextStyle(fontWeight: FontWeight.w400, fontSize: 30)),
            SizedBox(height: 10),
            Text('你好,谢谢你,Hello, thank you',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 30)),
          ],
        )

```

**Comment by darshankawar** [comment] 2022-07-18 12:59
Closing this as duplicate of https://github.com/flutter/flutter/issues/105014.

**Closed by darshankawar** 2022-07-18 12:59 UTC
Labels: in triage
