### ISSUE TITLE
iOS validation fails after upgrading to 1.22.0

### ISSUE THREAD

**Issue by DEMndz5** [flutter/flutter#67132] opened 2020-10-02 14:49 UTC
I haven't been able to pinpoint the actual issue but the app validates with flutter 1.20.4.

![image](https://user-images.githubusercontent.com/62218601/94936793-1eee9800-04a5-11eb-922e-61335beab835.png)

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-BR)
• Flutter version 1.22.0 at /Users/demndz/Development/flutter
• Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
• Engine revision 5babba6c4d
• Dart version 2.10.0

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.0.1, Build version 12A7300
• CocoaPods version 1.9.3
```
</details>

**Comment by TahaTesser** [comment] 2020-10-02 15:00
Hi @DEMndz5 
Please check out this https://github.com/flutter/flutter/issues/58200#issuecomment-675085313 
By default bump it i0S 9, it should resolve your issue
Closing as duplicate of https://github.com/flutter/flutter/issues/58200

**Closed by TahaTesser** 2020-10-02 15:00 UTC

**Comment by DEMndz5** [comment] 2020-10-02 16:03
Thanks for the quick reply. This indeed fixed the issue.
