### ISSUE TITLE
Explore home widgets for iOS 14

### ISSUE THREAD

**Issue by xster** [flutter/flutter#60026] opened 2020-06-22 23:04 UTC
Might be challenging considering that the APIs expect serializable archived views from swift UI. 

Based on a new Widget build target extension in the xcode project. We'll have to try it out first.

**Comment by NoahJApps** [comment] 2020-06-22 23:45
I'm planning on just exposing my flutter data in swift and then learning swift UI for the widgets...

**Comment by sathwikdoddi** [comment] 2020-06-29 19:36
Any guesses as to when iOS 14 Homescreen widgets for flutter will be available?

**Comment by fadhlisulaimi** [comment] 2020-07-04 05:08
@sathwikdoddi i think it will take a while. The current flutter version itself isn't compatible with ios14 and xcode 12. This will be the highest priority for the flutter team right now. And ios widgets is something new, it's developed mostly using swift UI and xcode (if im correct). Integrating that building tools itself for flutter wont be easy as we developed flutter using VSC or android studio. I can talk more about this but u get my point

**Comment by dancojocaru2000** [comment] 2020-09-16 19:45
A temporary workaround would be a way to facilitate easy data communication between the widget written with SwiftUI and the app written in Flutter.

**Comment by aytunch** [comment] 2020-09-16 20:04
Since home widgets are something completely new for iOS users, they will most probably have an extra interest towards apps utilizing this feature and these apps will have higher downloads. Thats my humble opinion. So I believe supporting home widgets asap while it is still new as a very important topic. Can someone explain why is it difficult to implement this feature in terms of swiftUI?

**Comment by fadhlisulaimi** [comment] 2020-09-17 00:35
@aytunch 

If I can answer on behalf of the community here, I believe it's not difficult to implement home widgets using swift UI. Just that  we have to learn swift UI and implement it on native iOS side. Most of us here only have knowledge in Dart/Flutter and we dont know how to code in native Android/iOS. So learning how to code in swift UI is another obstacle for us if we wanna implement widgets in iOS. Likewise for Android widgets as well, i think one has to code in native Java/Kotlin too.

**Comment by aytunch** [comment] 2020-09-17 01:10
@fadhlisulaimi So what you are saying is, Platform Channels can not be used in this scenario. It is not as simple as waiting for someone to write a plugin for camera/etc. Every developer needs to code these widgets through native ways. If that's true, it might not still be the end of the world. How hard can it be to display a very basic and simple UI? no state management no nothing. We just need to supply SwiftUI with some simple data stream and expect to see the widget UI reflect this data. How does the data transfer supposed to happen if we are ok with writing swiftUI? can you please share your thoughts
?

**Comment by fadhlisulaimi** [comment] 2020-09-17 01:55
@aytunch 

Swift UI is a declarative UI framework similar to Flutter. Meaning you develop the UI and logic on the fly (same with Flutter). So creating a flutter package or library to cater to this is nearly impossible as different users has differents way of designing the widget UI.

We can use platform channels to pass information or data between native OS and Flutter but let's say you have created the iOS widget you want using Flutter, how are you suppose to pass this info and translate it in native SwiftUI code. The only way I can think of is creating the UI using Swift UI and pass whatever data you wanna show using platform channels.

But there is another problem, based on the official documentation is stated that platform channels only support languages Objective-C, Java, Kotlin and Swift (via Objective-C interop). Swift UI is not yet supported. So this is another challenge we have to face.

**Comment by minikin** [comment] 2020-09-17 06:58
@fadhlisulaimi `Swift UI` is not a language it's a framework written in `Swift`. It's not a big deal and definitely not a deal-breaker for me that Flutter doesn't have the possibility to create a home widget. 

What would be great and a time saver that's to have Swift support in [pigeon](https://pub.dev/packages/pigeon).
Maybe @gaaclarke can share some plans about that, pls?

**Comment by Jeremywhiteley** [comment] 2020-09-17 18:05
Looks like they made progress with React Native.   

Maybe this will help?   https://link.medium.com/nbeePxDoR9

**Comment by aytunch** [comment] 2020-09-17 19:41
@Jeremywhiteley Thanks for sharing, but I guess the post was about App Clips. I am not sure if they have similarities with Home Widgets.

**Comment by gaaclarke** [comment] 2020-09-17 20:47
@minikin Pigeon does support Swift.  I have a working demonstration here: https://github.com/gaaclarke/GiantsA2A  I made it for a talk I gave on add-to-app but you can see it working with Swift.  Swift can call into objective-c with no problem as long as you put the headers in the magical "bridging" header.

**Comment by minikin** [comment] 2020-09-18 09:44
@gaaclarke great! thank you very much for the clarifications and the repo :pray:

**Comment by shadyshrif** [comment] 2020-09-26 12:10
I think there must be a way to compile flutter as SwiftUI, skipping that will make a big barrier between flutter and the Apple Echo system.  Apple watch and IOS Home widgets are the main two applications for SwiftUI till now but it seems that Apple is going to expand the usage of SwiftUI beyond them.

**Comment by ajbeattie** [comment] 2020-09-27 14:00
Recognizing the difficulty of allowing iOS widgets (and watch apps for that matter) to be developed directly with Dart/Flutter, an official guide on getting started with platform channels for these specific purposes would be awesome, especially if it were geared toward Flutter developers who typically _consume_ plugins rather than those who are already accustomed to working with native code.

**Comment by fl0gic** [comment] 2020-10-01 16:52
Not sure if this is applicable, but I saw this [thread](https://twitter.com/stroughtonsmith/status/1311698992561090561?s=21) on Twitter. Could Flutter implement something along those lines?

**Comment by Jeremywhiteley** [comment] 2020-10-20 19:21
They can do it with React Native and swift ui. Here is a how to article.  Couldn't we do something like this with Flutter? 

https://link.medium.com/O1qaApRfKab

**Comment by fadhlisulaimi** [comment] 2020-10-21 00:51
@Jeremywhiteley 
Not sure if u have read the article fully, the widget itself is built using SwiftUI, not react native. React native is only used to pass the data via bridge to the widget. Similar to flutter platform channels. Regardless, we still have to learn swiftUI.

**Comment by Jeremywhiteley** [comment] 2020-10-21 00:59
> @Jeremywhiteley
> Yes we can do something like this, but you have to learn SwiftUI haha. The widget itself is built using SwiftUI, not react native. React native is only used to pass the data via bridge to the widget. Similar to flutter platform channels, which is already available.

It's not a big deal to learn Swift UI if we can do this with Flutter and SWIFT UI like this article is doing with "React Native and SwiftUI."

**Comment by aytunch** [comment] 2020-10-21 13:05
@fadhlisulaimi @Jeremywhiteley I agree that it is not a big deal to learn SwiftUI just enough for displaying a very small UI. how hard can it be? If we had the tool to pass data from Flutter to SwiftUI, I don't think any programmer would be complaining. I really want to use the new iOS goodies while using Flutter. It would not make sense if we take advantage of Home Widgets when iOS15 is out. This is a big selling point for react over us unfortunately in social the communities..

**Comment by Jeremywhiteley** [comment] 2020-10-21 22:40
> @fadhlisulaimi @Jeremywhiteley I agree that it is not a big deal to learn SwiftUI just enough for displaying a very small UI. how hard can it be? If we had the tool to pass data from Flutter to SwiftUI, I don't think any programmer would be complaining. I really want to use the new iOS goodies while using Flutter. It would not make sense if we take advantage of Home Widgets when iOS15 is out. This is a big selling point for react over us unfortunately in social the communities..

I agree!  IOS Widgets are super useful and they are hot.  So many users are using them already.  Someone needs to publish a hot to article on how to do this.    I would, but I don't know swift UI yet.

**Comment by aytunch** [comment] 2020-10-21 23:11
@Jeremywhiteley I just saw this in twitter. I guess we are in luck:)

**Comment by AndroidNils** [comment] 2020-10-25 11:28
> @Jeremywhiteley I just saw this in twitter. I guess we are in luck:)
> [home widget coming soon tweet](https://twitter.com/ABausG/status/1318897531909296128?s=20)

Your tweet, @ABausG 🎉   
Awesome work! 🔥

**Comment by tomLadder** [comment] 2020-10-29 18:11
Here is my [library](https://github.com/fasky-software/flutter_widgetkit) that makes it easy to develop Widget-Extensions for a Flutter app. I also wrote a [blog article](https://thomas-leiter.medium.com/develop-an-ios-14-widget-in-flutter-with-swiftui-e98eaff2c606) that explains the concept with a simple example. Appreciate any feedback 🙏🏻

**Comment by imReker** [comment] 2020-11-06 15:49
![ios](https://user-images.githubusercontent.com/4949937/98385489-f9e3db00-2089-11eb-8058-4e6de2fb05e1.png)
Guys, I'm making a Home Widget demo for both iOS and Android by using Flutter directly. 
Project is here: https://github.com/imReker/FlutterHomeWidget

**Comment by ABausG** [comment] 2020-11-06 17:00
> @Jeremywhiteley I just saw this in twitter. I guess we are in luck:)
> [home widget coming soon tweet](https://twitter.com/ABausG/status/1318897531909296128?s=20)

I'm the one from twitter. I have published a first rough Version here:
https://pub.dev/packages/home_widget

It supports Interfaces to send Data to both Android and iOS
I have added a guide on the necessary steps for both platforms in the README

If you have a question or find an issue please file it in the repository:
https://github.com/ABausG/home_widget

**Comment by juliavi** [comment] 2020-11-12 07:30
> Here is my [library](https://github.com/fasky-software/flutter_widgetkit) that makes it easy to develop Widget-Extensions for a Flutter app. I also wrote a [blog article](https://thomas-leiter.medium.com/develop-an-ios-14-widget-in-flutter-with-swiftui-e98eaff2c606) that explains the concept with a simple example. Appreciate any feedback 🙏🏻

Thanks! worked perfectly!

**Comment by ztigunes** [comment] 2020-12-13 11:31
According to the apple review document, the home widget should not just open. If the application is opened from the home widget, how can I understand and redirect the page.

**Comment by Piinks** [comment] 2023-10-11 18:12
@xster or maybe @leighajarett  is this a dupe of https://github.com/flutter/flutter/issues/26134? If so, we can close to consolidate there.

**Closed** 2023-11-01 19:08 UTC
Labels: platform-ios, waiting for customer response, framework, engine, customer: crowd, e: OS-version specific, P2, team-ios, triaged-ios, multiteam-retriage-candidate
