### ISSUE TITLE
[Camera][Android] io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession crash

### ISSUE THREAD

**Issue by tijanirf** [flutter/flutter#117945] opened 2023-01-04 05:07 UTC
## Description
I found there are many crashes on android devices

This is the stack trace from the Crashlytics:
> Fatal Exception: java.lang.IllegalArgumentException: No handler given, and current thread has no looper!
       at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2280)
       at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2295)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:305)
       at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:510)
       at io.flutter.plugins.camera.Camera.access$900(Camera.java:100)
       at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:440)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
       at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(-.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

It might be related with this [unsolved issue](https://github.com/flutter/flutter/issues/92361). By the way, I am using `camera: 0.10.0+1` and `flutter v2.10.3`

## Steps to Reproduce

Actually, I can't replicate the issue using my available devices. But at least I can provide impacted devices:
- Redmi Note 8 Pro
- Redmi Note 8
- Redmi Note 10S
- Galaxy A02s
- Galaxy A73 5G
- Oppo CPH2239
- Oppo CPH2179
- Oppo A9 2020
- Realme 7

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.5 21G72 darwin-arm, locale en-ID)
    • Flutter version 2.10.3 at /Users/tijanirijalf/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (10 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tijanirijalf/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

```

</details>

**Comment by exaby73** [comment] 2023-01-04 09:27
Hello @tijanirf. Looks like you're using an old version of Flutter. Can you try on the latest stable `3.3.10`?

**Comment by tijanirf** [comment] 2023-01-05 03:11
> Hello @tijanirf. Looks like you're using an old version of Flutter. Can you try on the latest stable `3.3.10`? If still reproducible, please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with the logs to `flutter run -v`

Hi, thanks for the response. Unfortunately, we can't just upgrade the Flutter SDK on our production app right now. The release that contains the Flutter 3 is still testing by our QA and it takes time to fully release it due to organizational procedures (UAT, user approval, etc)

Is there any workaround that can be applied to Flutter 2.10.3?

**Comment by exaby73** [comment] 2023-01-05 08:01
Unfortunately, we do not provide support for old versions. This issue may be already fixed in a later version of Flutter. I would suggest trying to create a new project with the sole purpose of trying to reproduce this bug. If you can make a project like that on 3.3.10, I may take this issue forward

**Comment by tijanirf** [comment] 2023-01-05 16:16
> Unfortunately, we do not provide support for old versions. This issue may be already fixed in a later version of Flutter. I would suggest trying to create a new project with the sole purpose of trying to reproduce this bug. If you can make a project like that on 3.3.10, I may take this issue forward

Thanks for the reply. 

Well, I can't hide my disappointment because in theory the `camera: 0.10.0+1` is still compatible with `flutter: 2.6.3`. At a glimpse, the stack trace strongly indicates the root cause is the camera plugin itself. So, it is still hard to understand for me why I need to use Flutter 3 to validate this issue. 

That being said, I will get back to it after our app already released the Flutter 3 updates. Maybe I will keep this issue open for a while to check if there's someone who has a similar issue, especially who can't upgrade to Flutter 3 in the near future.

**Comment by exaby73** [comment] 2023-01-06 07:15
You ca still try to reproduce this issue on a fresh Flutter project. The official camera plugin example would give you a starting point. If you can reproduce it, do share the code sample so that I can verify and label the issue

**Closed** 2023-01-27 08:10 UTC
Labels: waiting for customer response, in triage

**Comment by farukprogrammer** [comment] 2023-02-24 04:36
Also crash on `Redmi Note 11 Pro 5G`
Just buy one of the device list above then try to run the camera example project.
Clicking any camera will produce empty black screen.

**Comment by jiagengArctuition** [comment] 2023-03-03 03:51
flutter 3.7.0android 12
