### ISSUE TITLE
simple_animation

### ISSUE THREAD

**Issue by manu223** [flutter/flutter#71305] opened 2020-11-27 07:19 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
![Screenshot (82)](https://user-images.githubusercontent.com/64858666/100421683-dde2c080-30ae-11eb-81b3-08859b50aacd.png)
I got this error how to solve me

**Comment by iapicca** [comment] 2020-11-27 08:27
@manu223 from your [screenshot](https://user-images.githubusercontent.com/64858666/100421683-dde2c080-30ae-11eb-81b3-08859b50aacd.png) seems that the issue is with the package [simple_animations](https://pub.dev/packages/simple_animations) rather than with flutter itself
I recommend to open an issue in the dedicated [github](https://github.com/felixblaschke/simple_animations/issues)

**Comment by darshankawar** [comment] 2020-11-27 09:28
@manu223 
`simple_animations` is a 3rd party plugin. Please open this issue in plugin owner's repo as suggested above.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2020-11-27 09:28 UTC
