### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by yunxingyu** [flutter/flutter#147916] opened 2024-05-07 09:23 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=873f3e55 --start-paused --dart-define=FLAVOR=product --flavor=product --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:205:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:153:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:147:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:323:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:331:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1090:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:411:5)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1736:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
```
```
[✓] Flutter (Channel master, 3.22.0-18.0.pre.49, on Microsoft Windows [版本 10.0.19045.4291], locale zh-CN)
    • Flutter version 3.22.0-18.0.pre.49 on channel master at D:\soft\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1189d44240 (9 days ago), 2024-04-28 06:00:58 +0530
    • Engine revision 20fb62ba14
    • Dart version 3.5.0 (build 3.5.0-105.0.dev)
    • DevTools version 2.35.0-dev.8
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:/soft/Android/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:/soft/Android/android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    ✗ The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] Connected device (4 available)
    • MI CC9 Pro (mobile) • 873f3e55 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [版本 10.0.19045.4291]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 123.0.6312.124
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 124.0.2478.80

[!] Network resources
    ✗ A cryptographic error occurred while checking "https://cocoapods.org/": Handshake error in client
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 087b15ae0d8dfa09e82d873f0d7195ed7c6d29ff
### Plugins
ali_iot_plugin
crypt_plugin
device_info_plus-10.1.0
flutter_blue_plus-1.32.4
flutter_inappwebview-6.0.0
flutter_inappwebview_android-1.0.13
flutter_inappwebview_ios-1.0.13
flutter_inappwebview_macos-1.0.11
flutter_inappwebview_web-1.0.8
flutter_native_splash-2.4.0
in_app_update-4.2.2
ota_update-6.0.0
package_info_plus-7.0.0
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler_android-12.0.5
permission_handler_apple-9.4.4
permission_handler_windows-0.2.1
screen_retriever-0.1.9
sqflite-2.3.2
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.0
url_launcher_windows-3.1.1
window_manager-0.3.8

**Comment by danagbemava-nc** [comment] 2024-05-07 09:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by danagbemava-nc** 2024-05-07 09:44 UTC
Labels: in triage
