### ISSUE TITLE
Adding border to ListTile inside IndexedStack shows up on other pages

### ISSUE THREAD

**Issue by terence-truong** [flutter/flutter#114317] opened 2022-10-30 11:07 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
Borders from bottom page shows up on top page.

**Actual results:** 
Borders should only show up on the bottom page.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: IndexedStack(
        index: 0,
        children: [
          SafeArea(
              child: Center(
            child: Text("Top Page"),
          )),
          SafeArea(
              child: Center(
            child: Text("Middle Page"),
          )),
          SafeArea(
              child: Center(
            child: ListView(
              children: List.generate(
                  10,
                  (index) => ListTile(
                        shape: Border.all(color: Colors.black, width: 1),
                      )),
            ),
          )),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
   info • The value of the field '_counter' isn't used • lib/main.dart:51:7 • unused_field
   info • Prefer const with constant constructors • lib/main.dart:81:11 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:82:22 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:83:20 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:85:11 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:86:22 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:87:20 • prefer_const_constructors

7 issues found. (ran in 3.3s)
```

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Users/terence/.fl_dir
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/terence/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

![Screenshot_20221030_180205](https://user-images.githubusercontent.com/33561189/198875175-da3a7be3-3401-47c1-ac3f-cd1c3b7df650.png)

**Comment by Nanangprasetya** [comment] 2022-10-30 11:53
hi @terence-truong 
maybe you can use `List.separated`. And inside `separatorBuilder` you can add `Divider()`

**Comment by iapicca** [comment] 2022-10-30 19:32
@terence-truong 
always nice to see some workable code sample, good job!

**Comment by danagbemava-nc** [comment] 2022-10-31 09:09
Hi @terence-truong, this is working by design. 

The `Ink` is painted on the nearest `Material` widget in the tree, in this case, this will be your `Scaffold`. 
You can resolve this issue by wrapping your `ListTile` with a `Material`. 

See the following links for more information. 
https://api.flutter.dev/flutter/material/InkWell-class.html
https://api.flutter.dev/flutter/material/Material-class.html
https://api.flutter.dev/flutter/material/Ink-class.html

I'll be closing this since it is working by design. 

Thank you

**Closed by danagbemava-nc** 2022-10-31 09:09 UTC
Labels: in triage
