### ISSUE TITLE
CheckedPopupMenuItem icon color

### ISSUE THREAD

**Issue by mliitfall** [flutter/flutter#29602] opened 2019-03-19 15:49 UTC
I'm trying to change icon colour in CheckedPopupMenuItem with iconTheme, but there is no effect. Also try to put ListTileTheme as it is using List Tile but still unchanged. Could you add a colour parameter on it?

```
Theme(
            data: Theme.of(context).copyWith(
              cardColor: Colors.indigo,
              iconTheme: IconThemeData(color: Colors.white),
            ),
            child: ListTileTheme(
              iconColor: Colors.white,
              child: PopupMenuButton<String>(
                onSelected: _showCheckedMenuSelections,
                itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                  CheckedPopupMenuItem<String>(
                    value: _checkedValue1,
                    checked: _showRoles,
                    child: ListTileTheme(
                      iconColor: Colors.white,
                      child: Text(_checkedValue1, style: Theme.of(context).textTheme.body1),
                    ),
                  ),
                  const PopupMenuDivider(),
                  PopupMenuItem<String>(
                    value: 'Get Link',
                    child: ListTile(
                      leading: Icon(Icons.phonelink),
                      title: Text('Get link', style: Theme.of(context).textTheme.body1),
                    ),
                  ),
                ],
              ),
            ),
          ),
```

**Comment by TahaTesser** [comment] 2020-02-21 15:03
Hi @mliitfall 
Are you still experiencing this issue? 
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-03-16 10:55
Hi @mliitfall 
I checked with flutter v1.15.22-pre.33, seems to be working as intended.
Closing, as probably,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-03-16 10:55 UTC
Labels: f: material design, framework, waiting for customer response
