### ISSUE TITLE
Scrollable SelectableText Bug: When selecting text in the bottom, the widget autoscrolls to top.

### ISSUE THREAD

**Issue by JohannaShiri** [flutter/flutter#96434] opened 2022-01-11 00:14 UTC
## Steps to Reproduce

1. `flutter run` the code from below, on iOS simulator
2. Scroll to the bottom part of the text.
3. Long press on a word to select it

**Expected results:**
Text scroll positions stays the same.

**Actual results:**
The text widget scrolls to the top, so that the selection is not seen anymore. 

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: const Center(
          child: SingleChildScrollView(
            padding: EdgeInsets.all(30),
            child: SelectableText(
              loremIpsum,
              style: TextStyle(fontSize: 20)
            ),
          )
        )
      )
    );
  }
}

const String loremIpsum = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sodales eros sit amet rhoncus viverra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec gravida efficitur erat in mollis. Nam consequat facilisis arcu, ac varius nisi elementum vitae. Ut at tellus maximus, suscipit est ac, faucibus diam. Phasellus faucibus lacus ligula, at bibendum metus dictum eu. Cras dui purus, pellentesque ac tempor sit amet, interdum in sem. Sed ut maximus nunc, ac vestibulum libero.

In mollis tincidunt vulputate. Aenean ullamcorper finibus laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer posuere congue felis vel mattis. Donec rhoncus nisl a hendrerit finibus. Curabitur auctor vehicula nisl, quis pellentesque lorem luctus quis. Quisque nec finibus turpis, ac congue tortor. Duis pretium congue felis sit amet cursus.

Nam sit amet arcu tincidunt, cursus ipsum in, lobortis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam placerat mauris velit, id convallis justo aliquet at. Integer ac suscipit nisi. Morbi at lobortis magna. Maecenas eleifend placerat dui eget mattis. Proin ac turpis ex. Praesent fermentum nunc lorem, et porttitor dolor pharetra eget. Nulla commodo euismod nulla. Nunc sollicitudin leo et nulla volutpat, nec semper sem cursus. Integer elementum euismod tortor, non vestibulum quam malesuada sed. Etiam sit amet felis elit. Nunc felis magna, mattis vitae finibus faucibus, luctus id odio. Aenean vitae fringilla mi.

Pellentesque nec urna a mi rutrum auctor. Phasellus congue, neque quis vestibulum tempor, sem felis consectetur tellus, at gravida felis sapien eu purus. Sed ut risus vitae augue porta tristique id ac libero. Aliquam vestibulum velit justo, a varius orci efficitur et. In sit amet nulla arcu. Praesent eleifend in ex vitae imperdiet. Proin fringilla eleifend eros non hendrerit. Donec sagittis mauris ac malesuada interdum.

Donec bibendum pellentesque dui ac bibendum. Maecenas mattis congue orci. Nulla sit amet dui in velit semper pellentesque. Morbi pellentesque risus et laoreet vulputate. Maecenas tincidunt consequat pellentesque. Curabitur lobortis aliquam dolor sed finibus. Vivamus sit amet sollicitudin leo, ac sagittis sem. Sed sed condimentum dolor. Aliquam at tincidunt urna, nec cursus risus. Fusce vulputate ultricies dui porta vehicula. Pellentesque rhoncus ornare rutrum. Suspendisse molestie erat vitae dolor feugiat vehicula. Nunc a velit finibus, iaculis dui eget, elementum nisl. Quisque sed aliquet lacus, nec faucibus eros.''';

```

</details>

<details>
  <summary>Logs</summary>

Output of `flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.5.3 at /Users/johanna/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/johanna/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • EE00CEEF-AE5A-481E-846E-6056673C88F0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 13 (mobile)         • C6F6AF0A-D2CF-46A3-A928-8E41F416EE27 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-01-11 09:34
Duplicate of #91464

**Closed by danagbemava-nc** 2022-01-11 09:34 UTC
Labels: in triage
