### ISSUE TITLE
Edge mobile and Safari load blank page (seems like a problem with the dart '??' operator and service worker)

### ISSUE THREAD

**Issue by bencer3283** [flutter/flutter#83646] opened 2021-05-31 03:03 UTC
## Steps to Reproduce

I' am building a image gallery app mainly for web usage, currently at the early stage of development. I am maintaining the repo at: [ImageGallery](https://github.com/bencer3283/ImageGallery).

1. Debug the app locally with Chrome and Edge on windows all works fine.
1. Run `flutter build web`.
2. Upload the file under the build/web folder to a web sever
3. Use a android phone with the mobile Edge browser to access the website.
4. Also access the website with desktop Edge and Chrome all works well, Chrome on Android also works as intended.
5. I've also asked a person the access the website with desktop Safari, also ended up with a blank page.

**Expected results:** Similar results across all platform.

**Actual results:** On Edge mobile and Safari browser, it can not load any content. Only a blank page show up.

## Debug with browser
Using the MS Edge [remote debug](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/) tool I was able to see the edge mobile browser console with error `Uncaught SyntaxError: Unexpected token '?'`at `index.html` line 67.  

## Eliminating the ?? operator seems like a fix
Around line 67 is a code block working with service-worker.
```
if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing ?? reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
```
If I manually change the code to 
```
if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              if (reg.installing == null) waitForActivation(reg.waiting)    // << Modified here
              else waitForActivation(reg.installing);                                 // << Modified here
              //waitForActivation(reg.installing ?? reg.waiting);              // << Modified here
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
```
Than it works really well as intended. I have no idea why this is happening only on certain platform + browser combo. I don't have any apple device to do further debugging with Safari.
<details>
```
  ❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.1023], locale zh-TW)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)
    ! Device 8A3X0L7ND is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 1 category.
```

</details>

**Comment by espanadebate** [comment] 2021-05-31 10:19
Same issue as #83176, this may well be an easy solution to implement.

**Comment by TahaTesser** [comment] 2021-05-31 14:35
Hi @bencer3283 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83176
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-31 14:35 UTC
Labels: in triage
