### ISSUE TITLE
Waiting for connection from debug service on Chrome runs forever

### ISSUE THREAD

**Issue by mirlife** [flutter/flutter#79188] opened 2021-03-27 08:00 UTC
I am trying to run a flutter web project but once I launch it opens new chrome window and shows blank page and shows waiting forever on the console

Flutter web is enabled.
Flutter and dart pluguns are also installed
Chrome dart debug extention also installed

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.1.0-13.0.pre.292, on Microsoft Windows [Version 10.0.14393], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code (version 1.54.3)
[√] Connected device (1 available)

• No issues found!

```
[ +127 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +152 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b60c855af5150b695638b2195f500d3c003b71ab
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at b60c855af5150b695638b2195f500d3c003b71ab
[  +88 ms] Exit code 0 from: git tag --points-at b60c855af5150b695638b2195f500d3c003b71ab
[   +6 ms] executing: [C:\src\flutter/] git describe --match *.*.* --long --tags b60c855af5150b695638b2195f500d3c003b71ab
[ +150 ms] Exit code 0 from: git describe --match *.*.* --long --tags b60c855af5150b695638b2195f500d3c003b71ab
[   +1 ms] 2.1.0-12.0.pre-292-gb60c855af5
[   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +104 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +194 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +167 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +130 ms] List of devices attached
[  +29 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +167 ms] Skipping pub get: version match.
[ +210 ms] Generating D:\flutterApps\firstwebapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +258 ms] Launching lib\main.dart on Chrome in debug mode...
[ +222 ms] Updating assets
[ +156 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +6 ms] Waiting for connection from debug service on Chrome...
[ +254 ms] <- reset
[  +12 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\User\AppData\Local\Temp\flutter_tools.4e0a34a7\flutter_tool.812c8029\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\flutterApps\firstwebapp\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\User\AppData\Local\Temp\flutter_tools.4e0a34a7\flutter_tools.586ab128
--filesystem-scheme org-dartlang-app --initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[ +140 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+29453 ms] Waiting for connection from debug service on Chrome... (completed in 29.8s)
[   +3 ms] Synced 29.4MB.
[   +1 ms] <- accept
[   +4 ms] Caching compiled dill
[+8169 ms] [CHROME]:
[  +10 ms] [CHROME]:DevTools listening on ws://127.0.0.1:49827/devtools/browser/c141dd07-ffc1-43ab-a7e4-5b81aca77d80
[+2073 ms] DwdsInjector: Received request for entrypoint at http://localhost:49684/main_module.bootstrap.js
[   +9 ms] MetadataProvider: Loading debug metadata...
[  +25 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +12 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:49684/main_module.bootstrap.js
```

**Comment by darshankawar** [comment] 2021-03-29 08:54
@mirlife 
Does your app have assets that you are load ? 
From the log, I see below:

`Updating assets
[ +156 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.`

So not sure if the behavior you are seeing is because of above log and has something to do with the assets. Can you confirm if your assets are proprly implemented and called in your code ?
If so, can you provide `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)` that shows this issue ?

Thanks.

**Comment by pedromassangocode** [comment] 2021-04-21 09:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:09 UTC
Labels: in triage, waiting for customer response
