### ISSUE TITLE
Issue from website (tutorial) page Building Layouts in Flutter

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#13507] opened 2017-12-12 06:53 UTC
First, please don't think I'm just bashing because you all are doing great! There is so much to learn and I'm having breakthroughs every few hours, loving it most of the time... but there are, of course, moments. What I keep running into are issues with phrases that aren't easily understood by the student and the way that teaching any given lesson is approached. Such as when to break code into files and when to do it all in one file. That said, I had a particularly hard time with the layout tutorial and was unable to finish. Here's why:

From URL: https://flutter.io/tutorials/layout/index.md

In short, I'm so turned around after trying to follow this that I can't figure out which way is up.

- The nesting is at the root of all the confusion.
     - In the MyApp class it goes to, at minimum, 11 deep. People on Gitter have said that if they need more than 3 deep then they write a function.
     - Because the nesting is so deep, if you miss a ) or } and use auto-format your code format goes totally out the window. Also, you can't rely on the prompts from IntelliJ to tell you where to put a missing paren or bracket in a case like this because for every red squiggle you get rid of, it causes 3 more. Fixing a missing paren or bracket at nesting 3-4 deep isn't that hard but after 6 or 7 it gets pretty frustrating. 10 or more is just insane. I literally had 30 lines of:
)
,
]
,
)
)

You get the idea.

- Adding code to MyApp to implement the button, image or text sections:
     - I look at this and I see that understanding the code is the easy part. Figuring out where to put later steps feels like guesswork.
     - I tried to make things a little more readable by putting MyApp into it's own class. Big mistake. It looked as if that was going to be okay in Step 2, which had me put a container at the top of the MyApp class. I had just assumed that we were going to be calling it from within main.dart, after home:
     - But then I got to Step 3, which had me put the MaterialApp into the MyApp class. More confusion ensued because I thought we had just started that class off with a container? 
     - So now I realize that I have to have all of this in one file, since all of the following sections have me adding more and more steps to the MyApp class...

I have more than 30 years troubleshooting experience in electronics. We have a term for when you open a panel and find a million wires all tangled around each other like a cat's been playing with it all for a month. We call it an "explosion in a spaghetti factory".

The code is nested 11 deep after just Step 2. I lost more than half my time trying to run down missing parens and brackets because IntelliJ complains about them as I'm building out the nesting and I never seem to know when the nesting is done... so am I supposed to keep up with brackets, parens and semicolons as I go?

Additional steps have you add code to some point in the MyApp class, I can't really tell where each new section should go because I kind of think the code diagram looks as if the new code starts at a point 3 levels deep, or is it 4? Then there are the //... which don't help because what that leads me to believe is that this code goes... well, somewhere. Where I'm not quite sure. There are several areas that are 3 or 4 levels deep.

Yes, I *could* just go copy the code from the finished source but I'm here because I need to learn to build this myself, one step at a time. I need to understand it and see how each piece fits together.

And folks, someone who is trying to learn this shouldn't be having a hard time figuring out where to put the code for later steps and they certainly shouldn't be taught the bad habit of cramming all their code into one file. With all the nesting going on in Flutter it's absolutely *crucial* to learn how to use functions to break the code up so that you don't end up with a monster that is nested 8, 10, maybe 15 lines deep. Those habits need to be ingrained early on.

I pass myself off as a noob but that's not quite true. Back in the days just before Windows released the disaster that was Vista, I was using C# to make the SpeechAPI and MS Agent do things that make Cortana look like an idiot. My "assistant" had an attitude variable that made it nicer or more sullen and moody, depending on how you treated it. If you really made it mad then it would refuse to cooperate at all, telling you no, she won't open the web browser because all you're going to do is watch porn.

This was in 2001/2002. Then Vista came, breaking SAPI and Agent both so badly that my program wouldn't run on Vista at all and there was no update for SAPI that would work in Vista for a long time... so I quit messing with programming. 

But now I'm back, and trying to follow along to learn to use Flutter. I'm trying to build good habits and write clear, concise, clean and understandable code. But it's hard to learn about things like the layout on the phone screen when I'm spending 80% of my time trying to figure out the layout of the code in the editor... and failing.

Hey... this is an Alpha. *I totally get it.* Therefore, I'm trying to point out the rough spots in tutorials before the masses come storming in here, and they will come. Once word really gets out that people can develop for both ios and Android with only one app, individuals and entire companies are going to stampede over to Flutter... especially companies. The cost savings will be incredible. Instead of 2 teams producing 1 project every six months you can have them produce different projects and still target both platforms, doubling the company's productivity.

People will come here in droves... and they're all going to be going through these tutorials. If they hit roadblocks, they'll be pounding your emails and flooding Gitter with questions. The more I can help you make the tutorials easy to understand, the fewer problems people will be bothering you with.

Again, overall I'm having a blast and learning a ton! I wake up and look forward to digging deeper into the details of Flutter every day and that's all because of the hard work the team has done so far!

Scott

**Comment by zoechi** [comment] 2017-12-12 07:57
You mention tutorials. 
Can you please post links to some that you think should be improved,
perhaps with concrete suggestions how to improve?

I doubt the intention of Flutter docs is to teach basic programming skills, but I'm sure they don't want the docs to cause additional confusion to less experienced programmers. 

(I'm not from the Flutter team, just stumbled upon your comment)

**Comment by ScottS2017** [comment] 2017-12-12 11:50
The link goes directly to the tutorial, it's one of the one's from flutter.io. There is a link there that says to report any issues with it, and that link takes you here.

I don't really see these as basic programming issues because I've never seen this kind of nesting in C#, Java or Kotlin. With Flutter, the nesting appears to be necessary and I can't see a way around it because of the structure of the UI's we're building, and that's okay... but I have the feeling that there has to be a better way to organize the code.

Here are a couple of screenshots. I recreated what happens when a ) is missed for this one:
![flutterissue2](https://user-images.githubusercontent.com/32370328/33882983-003de318-df08-11e7-8759-e183cb77b611.png)

And here is the same code, fixed. I was told to not nest it out nearly this far but to, instead, use functions.

![flutterissue2a](https://user-images.githubusercontent.com/32370328/33883019-235a1f56-df08-11e7-9b26-6129c96bc50b.png)

**Comment by zoechi** [comment] 2017-12-13 11:11
I'm sure the formatting issue is a IntelliJ IDEA/WebStorm/Android Studio issue. 
Dartformat by itself doesn't do that, but when called from inside IntelliJ some other actions are executed (like sorting imports) and one of them caused the bad formatting shown above when the code is not valid.

**Comment by Hixie** [comment] 2018-05-22 00:11
I recommend filing just one bug pre issue. I can't tell here if the problem is with Flutter's design using many nested widgets, or if it's a formatter issue in IntelliJ, or if it's a problem with the tutorial, or...?

**Comment by ScottS2017** [comment] 2018-05-24 11:09
Wow, how time flies and the learning curve accelerates. I had forgotten about this. Hixie, I think it's an issue with the formatter when your code is messed up in some yet to be determined way. Trouble is, unlike when you're missing a comma it's harder to figure out what went wrong. With a missing comma you just go to the top of the dead code. I have had this happen once a week or so and haven't had enough occurrences of it to see any pattern yet.

On another topic, thanks for taking over the spacer widget! I had abandoned it when I heard about how expensive a container was.

Oh, and you managed to break my code, and only my code. I feel really special. You see, I had used my local, path package spacer in a few of my older practice apps. I went to show someone something and found the app broken badly. Turned out that Spacer was defined twice, because you pushed it to the framework and I had updated.

So you managed to single me out and break only my code. lol

**Comment by zoechi** [comment] 2018-05-24 14:59
dartfmt doesn't format code with invalid syntax. It's somehow done by the Flutter plugin.
See flutter/flutter-intellij#1413

**Comment by Sfshaza** [comment] 2018-06-12 08:45
Hi, @ScottS2017.  I'm not sure what IDE you're using, but if it's IntelliJ or Android Studio, it won't format code with invalid syntax (as zoechi mentioned). Also, Android Studio now helps you by adding automated comments on the closing brackets/parentheses, telling you which widget it closes. (I'm not sure if VSCode does that.) I've included a screenshot showing what I mean.

<img width="535" alt="screen shot 2018-06-12 at 1 44 37 am" src="https://user-images.githubusercontent.com/6293442/41279790-431cb650-6de2-11e8-9bba-06471687697b.png">

Can I close this issue? Or is there something still to be resolved?

**Comment by ScottS2017** [comment] 2018-06-18 10:59
Yup, thanks! I should have closed this a long time ago but I'm fairly new to github and didn't realise I need to do that. Thanks for the help!

**Closed** 2018-06-18 11:37 UTC
Labels: d: website - content
