### ISSUE TITLE
[webview_flutter] The screen freezes when previewing selected images. (Observed only on Pixel 8)

### ISSUE THREAD

**Issue by tttuuu1234** [flutter/flutter#151088] opened 2024-07-01 08:08 UTC
### Steps to reproduce

os: Google Pixel 8, Android14 (AP2A.240605.024)

1. Start with the WebView displayed.
2. Open the Android file selection screen using file_picker.
3. Display a full-screen preview of the selected image.
4. Close the preview.
5. Close the file selection screen.
6. Return to the original WebView.
7. At this point, the WebView display freezes in the state it was before opening the file selection screen.
8. Visual updates such as scrolling are no longer reflected on the screen.
9. However, the screen is actually still accepting touch operations.
10. If you remember the positions of buttons on the screen and tap them accurately, they will respond.

### Expected results

Ensure that the screen does not freeze when previewing images on Pixel 8.

### Actual results

The WebView display freezes in the state it was before opening the file selection screen.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details>

<summary>Flutter doctor details</summary>

```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.0 23A344 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.5 on channel stable at /Users/user/fvm/versions/3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 months ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode-15.0.1.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile) • 52FA7DB9-44EE-48EC-954F-749747887A58 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPhone 15 (mobile)                  • 5DB4BF94-363C-479F-9772-01730111E206 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for TsubasaのiPhone12. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by tttuuu1234** [comment] 2024-07-01 08:18
We have confirmed the issue on version 3.22.2 as well. Please verify.

**Comment by huycozy** [comment] 2024-07-01 11:54
Hi @tttuuu1234 
Does the issue only happen on Pixel 8 device? Could you try on another device/simulator if any?

For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), thanks!

**Comment by tttuuu1234** [comment] 2024-07-02 04:47
Hi @huycozy 
Thank you for your reply!

I have tested on the following devices, but so far I have only confirmed the issue on the Pixel 8 device:

- Pixel 6 Android 14 emulator
- Pixel 7a Android 14 device
- Nothing Phone (1) Android14 device
- Motorola g53 Android14 device

Please wait a moment while I provide the sample code.
I apologize for the delay.

**Comment by tttuuu1234** [comment] 2024-07-03 03:10
@huycozy 

Thank you for waiting.
Here is the sample code.
I'm using the FilePicker package to allow image selection on Android from the Flutter side.
The package versions are as follows:
```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  file_picker: ^8.0.0
  path: ^1.8.3

```
Please check and let me know your thoughts.

<details>

<summary>Sample code</summary>

```dart
import 'dart:developer';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:path/path.dart' as path;

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final WebViewController _webViewController;

  @override
  void initState() {
    super.initState();
    _webViewController = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(NavigationDelegate(
        onProgress: (int progress) {
          log('progress: $progress');
        },
        onPageStarted: (String url) {
          log('page started: $url');
        },
        onPageFinished: (String url) {
          log('page finished: $url');
          if (Platform.isAndroid) {
            _webViewController.runJavaScript(
              '''
              function selectFile() {
                  let contactFile = document.querySelector("#attached-file");
                  if (!contactFile) {
                    return;
                  }

                  contactFile.addEventListener("click",(event)=>{
                    select_file.postMessage(event.target.id);
                  });
              }

              selectFile();
              ''',
            );
          }
        },
        onWebResourceError: (WebResourceError error) {
          log('error: $error');
        },
      ))
      ..loadRequest(
        Uri.parse('https://dev.kmc.kowa.co.jp/contact/app/index'),
      );

    if (Platform.isAndroid) {
      _webViewController.addJavaScriptChannel(
        'select_file',
        onMessageReceived: (result) async {
          await _selectFileToAndroid(result.message);
        },
      );
    }
  }

  Future<void> _selectFileToAndroid(String id) async {
    final fpresult = await FilePicker.platform.pickFiles(
      type: FileType.any,
    );
    if (fpresult == null) {
      return;
    }

    final fpath = fpresult.files.single.path ?? "";
    final file = File(fpath);
    final bindata = await file.readAsBytes();
    final binlist = bindata.buffer.asUint8List();
    final dataURI = Uri.dataFromBytes(binlist).toString();
    _webViewController.runJavaScript(
      """
      var dataURI = "$dataURI";
      var byteString = atob( dataURI.split( "," )[1] ) ;
      var mimeType = "application/octet-stream";
      for( var i=0, l=byteString.length, content=new Uint8Array( l ); l>i; i++ ) {
        content[i] = byteString.charCodeAt( i ) ;
      }
      var blob = new Blob( [ content ], {
        type: mimeType ,
      } ) ;
      var imgFile = new File([blob], '${path.basename(fpath)}', {type: "application/octet-stream"});
      var inputtag = document.getElementById("$id");
      var dt = new DataTransfer();
      dt.items.add(imgFile);
      inputtag.files = dt.files;
      var event = new Event("change");
      inputtag.dispatchEvent(event);
      """,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: WebViewWidget(controller: _webViewController),
    );
  }
}

```
</details>

**Comment by huycozy** [comment] 2024-07-03 06:11
Thanks for your update. I tried your sample code above but couldn't see the issue on my device Pixel 7, Android 14. 

<details>
<summary>Demo (issue is not reproduced)</summary>

https://github.com/flutter/flutter/assets/104349824/8e3032c3-a6b0-450d-9e5a-8f33047edea2

</details>



Can you retry with [image_picker](https://pub.dev/packages/image_picker) instead? (To rule out the possibility of file_picker's bug which is a 3rd party package). And can you please share a recorded video of the bug?

**Comment by tttuuu1234** [comment] 2024-07-04 01:30
@huycozy 

Thank you for your reply.
I will modify the implementation to allow image selection using image_picker, so please wait for a moment.
I will contact you again when it's ready.

The following video shows the malfunction.
Please check it.

<details>

<summary> Pixel8 demo  </summary>

https://github.com/flutter/flutter/assets/47853132/25336a45-79a2-483a-b7d9-5ee128869b5b

</details>

**Comment by huycozy** [comment] 2024-07-04 03:54
Here is the example I updated to use image_picker package, you can try on your device: [repro_151088.zip](https://github.com/user-attachments/files/16093110/repro_151088.zip) to see if the issue persists.

**Comment by tttuuu1234** [comment] 2024-07-05 00:30
Thank you for providing the sample code.
After changing to image_picker, I confirmed that the screen does not freeze on Pixel 8.
However, I'm not sure if file_picker is the root cause.
If the issue https://github.com/flutter/flutter/issues/146499 is also affecting this, I think file_picker might not be directly responsible for the problem...

**Comment by huycozy** [comment] 2024-07-05 05:26
If you suspect https://github.com/flutter/flutter/issues/146499 is the cause, you can try switching to Flutter beta/master channel and give it a try because the PR fixed that issue (https://github.com/flutter/engine/pull/52370) has been landed on these channels but not yet landed on the latest stable (3.22.2)

**Comment by tttuuu1234** [comment] 2024-07-10 03:24
I apologize for the delayed response.
After discussions within our team, we have decided to address the issue by replacing the current implementation with image_picker. We have confirmed that image selection works without screen freezing on Pixel 8 and other devices.
Thank you very much for your assistance.
Would it be alright to close the issue?

**Comment by huycozy** [comment] 2024-07-10 03:50
Yes, closing the issue as above

**Closed by huycozy** 2024-07-10 03:50 UTC
Labels: in triage
