### ISSUE TITLE
Material 3 themed AppBar actions icons doesn't respect foregroundColor property

### ISSUE THREAD

**Issue by Footmau** [flutter/flutter#110631] opened 2022-08-30 23:36 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** Actions icons are red (like the title).

**Actual results:** Action icons has default theme color (but title is red).

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const AppBarExample(),
      theme: ThemeData(
        useMaterial3: true,
      ),
    );
  }
}

class AppBarExample extends StatelessWidget {
  const AppBarExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('AppBar Demo'),
        foregroundColor: Colors.red,
        leading: const BackButton(),
        actions: <Widget>[
          IconButton(
            icon: const Icon(Icons.add_alert),
            onPressed: () {
            },
          ),
          IconButton(
            icon: const Icon(Icons.add_alert),
            onPressed: () {
            },
          ),
          IconButton(
            icon: const Icon(Icons.add_alert),
            onPressed: () {
            },
          ),
        ],
      ),
      body: Container(),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

![Untitled](https://user-images.githubusercontent.com/5335629/187647458-9b538795-f16b-4c68-91b9-d9436858bfcc.png)

**Comment by danagbemava-nc** [comment] 2022-08-31 10:04
Hi @Footmau, this seems to be fixed on the master channel as I can reproduce this on stable, but not on master. See the screenshots below.

Per our triage policy, I'll be closing this since it has been fixed on the master channel. If you still experience this issue on the master channel, kindly leave a comment below and I will reopen this. 

Thank you

<details>
<summary>screenshots</summary>

| stable | master |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/187652699-de0ab579-8884-4a4b-9c7d-3b15aab8cb1e.png" /> | <img src="https://user-images.githubusercontent.com/88313112/187652712-165684ba-1f97-4f62-b217-ee6938269f61.png" /> |
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (34 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Nexus (mobile)             • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
    • iPhone 13 Pro Max (mobile) • FD5949EA-E739-4960-9E9D-16F3DE69816E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2592, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2592 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 069f504297 (9 hours ago), 2022-08-30 18:20:09 -0700
    • Engine revision 0ef08a8525
    • Dart version 2.19.0 (build 2.19.0-152.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Nexus (mobile)             • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
    • iPhone 13 Pro Max (mobile) • FD5949EA-E739-4960-9E9D-16F3DE69816E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Closed by danagbemava-nc** 2022-08-31 10:04 UTC
Labels: in triage
