### ISSUE TITLE
FLUTTER_NOTIFICATION_CLICK action or Navigation from push notifications is not working as expected 

### ISSUE THREAD

**Issue by itsurmvk** [flutter/flutter#25546] opened 2018-12-19 09:19 UTC
I have included  "firebase_messaging" package in my project and added below intent filter in AndroidManifest.xml

```
<intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
Now in `my main.dart` file I have configured below code in `initState()` method of the main Application stateful widget which is called via `runApp();`

---------SETUP------------------
```dart
firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });

    firebaseMessaging.getToken().then((String token) {
      print("FCM Token: " + token);
    });
```
--------CONFIGURE------------
```dart
firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message){
        print("onMessage :${message.toString()}");
        Navigator.pushNamed(context, '/promote');
      },
      onLaunch: (Map<String, dynamic> message){
        print("onLaunch :${message.toString()}");
        Navigator.pushNamed(context, '/notify');
      },
      onResume: (Map<String, dynamic> message){
        print("onResume :${message.toString()}");
        Navigator.pushNamed(context, '/chat');
      },
    );
```

with the FCM token printed in my app console I used firebase cURL command mentioned in docs to push a notification . After receiving the notification on my device , I clicked on the notification.

-----ISSUE-----

whenever I clicked on the notification the app gets launched with the route '/' but not with the '/promote' or '/notify' or '/chat' provided in onMessage, onResume or onLaunch callbacks in configure. it is observed the even the print statement is not executed.

Please help in navigation to different screens from Push notification

**Comment by hjJunior** [comment] 2018-12-19 13:48
I got the same problem, I receive the notification, but when I click on notification I just got again the token

I tried app running on background and closed, both I got the notification but I can't get the print events

**Comment by zoechi** [comment] 2018-12-19 14:03
I guess the `context` in `Navigator.pushNamed(context, '/promote');` is not the one that contains the `Navigator` that knows about the route.
Use instead a https://docs.flutter.io/flutter/material/MaterialApp/navigatorKey.html and get the `context` from there to `Navigator` methods.

See also https://stackoverflow.com/questions/50124355/flutter-navigator-not-working or https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf for how to use navigatorKey

**Comment by hjJunior** [comment] 2018-12-19 16:45
### Update
Sorry about that, I didn't see that I was supposed to send the data: `"click_action": "FLUTTER_NOTIFICATION_CLICK"`, so I added this and everything worked :)

**Comment by zoechi** [comment] 2019-01-08 09:04
I think this is a 
Duplicate of #11607

**Closed by zoechi** 2019-01-08 09:04 UTC
Labels: waiting for customer response

**Comment by minh98** [comment] 2019-03-12 09:16
work fine when add click_action and FLUTTER_NOTIFICATION_CLICK :D .
tks

**Comment by AnandGupta7866** [comment] 2019-05-01 10:06
Anyone can help me how to run the app in background if the app is terminated. (Because when app terminated then firebase notification are not received by device)

**Comment by AlejandroC90** [comment] 2019-07-02 02:17
@minh98 Where do I need to add this?

**Comment by maqoo** [comment] 2019-07-31 09:47
> @minh98 Where do I need to add this?
> 
> > work fine when add click_action and FLUTTER_NOTIFICATION_CLICK :D .
> > tks

To the "data" object in json

**Comment by jhoanrivers** [comment] 2019-12-10 08:00
> ### Update
> Sorry about that, I didn't see that I was supposed to send the data: `"click_action": "FLUTTER_NOTIFICATION_CLICK"`, so I added this and everything worked :)

where should i put "click_action": "FLUTTER_NOTIFICATION_CLICK" bro?,  anyone can provide a tutorial please.

**Comment by maskas** [comment] 2019-12-31 14:49
@jhoanrivers you put "click_action" next to "title" and "body" when sending out the notification.

**Comment by naeem-shah** [comment] 2020-05-08 15:28
> ### Update
> Sorry about that, I didn't see that I was supposed to send the data: `"click_action": "FLUTTER_NOTIFICATION_CLICK"`, so I added this and everything worked :)

I put it in my notification and data, but still both method are not working..

loh:
```
D/EGL_emulation(30282): eglMakeCurrent: 0x9e5049c0: ver 2 0 (tinfo 0x890d34a0)
W/FirebaseMessaging(30282): Unable to log event: analytics library is missing
W/FirebaseMessaging(30282): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
```

**Comment by elgsylvain85** [comment] 2020-07-15 20:46
> I guess the `context` in `Navigator.pushNamed(context, '/promote');` is not the one that contains the `Navigator` that knows about the route.
> Use instead a https://docs.flutter.io/flutter/material/MaterialApp/navigatorKey.html and get the `context` from there to `Navigator` methods.
> 
> See also https://stackoverflow.com/questions/50124355/flutter-navigator-not-working or https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf for how to use navigatorKey

I had the same problem and It has been the solution for me.
