### ISSUE TITLE
LinearGradients using `transform: GradientRotation()` do not behave as expected

### ISSUE THREAD

**Issue by LegendAF** [flutter/flutter#157475] opened 2024-10-23 22:12 UTC
### Steps to reproduce

Use `transform: GradientRotation()` on a `LinearGradient` inside of a `Container` that does not have an aspect ratio that is sqaure. The transform should be 45deg, 90deg or 270deg.

Please let me know if I am doing something wrong here.

### Expected results

When you use `transform: GradientRotation(1.5707963267948966)` _(90 degrees)_ for it to be the same as if you used alignment.

Transform:
```
LinearGradient(
  colors: const [
    Colors.black,
    Colors.white,
  ],
  transform: GradientRotation(1.5707963267948966),
),
```
vs

Alignment:
```
LinearGradient(
  colors: const [
    Colors.black,
    Colors.white,
  ],
  begin: Alignment.topCenter,
  end: Alignment.bottomCenter,
),
```

(There are circumstances where it works fine such as 0 degrees and 180 degrees)
![IMG_2412](https://github.com/user-attachments/assets/db9f789a-8054-429c-894c-f59f78a9cdbd)

### Actual results

If the aspect ratio of the container is square it works fine. If the aspect ratio is not square it starts to get distorted vs what's expected.

 
![IMG_2413](https://github.com/user-attachments/assets/416dafc7-2f28-4d75-be10-ebc9abc5dfe9)

### Code sample

<details open><summary>Code sample</summary>

I have set a repo up 
https://github.com/LegendAF/flutter-linear-gradient

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/d7acc763-4267-42ab-8e1d-788ccdaa4aaf

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  flutter_linear_gradient git:(main) flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/username/Development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/username/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.0.12+7/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)            
    • Legend's iPhone (mobile)        • 00008140-001069683082201C • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-10-24 09:07
Thanks for the report. I can observe the same as reported on Flutter `Channel master, 3.27.0-1.0.pre.206` (on macOS app).

**Comment by nate-thegrate** [comment] 2024-10-29 23:54
[GradientTransform](https://main-api.flutter.dev/flutter/painting/GradientTransform-class.html) transforms the gradient shaders as if the shape had been transformed, without transforming the shape.

![gradient transform](https://github.com/user-attachments/assets/c98c7bf1-ca1d-4887-bd6c-d3eb2236fde5)

I believe this is likely working as intended, but let me know if you disagree!

**Comment by LegendAF** [comment] 2024-10-30 08:09
I missed the line "_without applying the same transform to the entire canvas_" in the docs before. Thanks for that!

To rotate a gradient to match as I was expecting I will now have to do something like:

```
Alignment alignmentFromDegrees(double degree) {
  final x = cos(degree * pi / 180);
  final y = sin(degree * pi / 180);
  final xAbs = x.abs();
  final yAbs = y.abs();

  if ((0.0 < xAbs && xAbs < 1.0) || (0.0 < yAbs && yAbs < 1.0)) {
    return Alignment(-x, -y) *
        ((1 / xAbs) < (1 / yAbs) ? (1 / xAbs) : (1 / yAbs));
  } else {
    return Alignment(-x, -y);
  }
}

const LinearGradient(
  begin: alignmentFromDegrees(90),
  end: -alignmentFromDegrees(90),
  colors: [
    Colors.black,
    Colors.white,
  ],
  stops: [0, 1],
);
```

Is this what is expected in Flutter or am I just missing something glaringly obivous?

**Comment by chunhtai** [comment] 2024-10-30 18:52
Closing as WAI

**Closed by chunhtai** 2024-10-30 18:52 UTC
Labels: framework, has reproducible steps, team-framework, found in release: 3.24, found in release: 3.27

**Comment by LegendAF** [comment] 2024-10-30 19:35
@nate-thegrate Thanks for the reply and looking into it.

We have a transform layer we wrote between Figma and Flutter that run pre-build that does all this code for us. That means our designers can (and do) use non 45/90 degree multiples. I wish we could do 90 degrees multiples only as that is vastly simpler!
