### ISSUE TITLE
`didChangeAppLifecycleState` is called with `AppLifecycleState.resumed` while screen is locked

### ISSUE THREAD

**Issue by ashley-arta** [flutter/flutter#130055] opened 2023-07-06 07:57 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On iPhone 14 Pro, OS 16.5.1, `didChangeAppLifecycleState` is called with `AppLifecycleState.resumed` while screen is locked by clicking the side button. 
This function seems to work as expected when moving App to the background, or pulling down the top menu.

Can be reproduced with a simple flutter project which is provided as Code sample below

This does NOT happen on iPhone 13 Pro Max, OS 16.5.1.

### Expected results

`AppLifecycleState.resumed` should only show up once, after the screen is unlocked. 

### Actual results

These are printed after screen is locked. `AppLifecycleState.resumed` should not be printed but it was.

```
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.resumed
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.paused
```

After screen is unlocked, `AppLifecycleState.resumed` is printed again.

```
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.resumed
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with WidgetsBindingObserver {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    debugPrint('AppLifecycleState: $state');
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.2 22D49 darwin-arm64, locale
    en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ashley-arta** [comment] 2023-07-06 08:31
just tried upgrading flutter to 3.10.5, and it can still be reproduced

**Comment by huycozy** [comment] 2023-07-06 10:55
Thanks for the report. I can reproduce this issue on `iPhone 14 Pro, iOS 16.4 (emulator)`. Meanwhile, it doesn't happen on another device `iPhone 7, iOS 15.7.2`.

Lifecycle states are a bit different as below on Flutter master channel (additional `hidden` state), but `resumed` does appear when the screen is locked:
```console
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.resumed
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.hidden
flutter: AppLifecycleState: AppLifecycleState.paused
```
### Additional information
- I see there is a similar report at https://github.com/flutter/flutter/issues/130038 but it's still not very clear when the OP described the issue with case: `move the app to background or terminated state`. 

    cc @bilalgodesto: it's good to have a look at this issue if this is the case same to yours. If it is, feel free to close your issue and follow up on this issue. 

- Looks like `didChangeAppLifecycleState ` API might be changed in the upcoming time (see https://github.com/flutter/flutter/issues/73947#issuecomment-1421333690) (Linking this issue to it so that we can verify this again once the new API is landed)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-14.0.pre.48, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-14.0.pre.48 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc49cd1bca (3 hours ago), 2023-07-05 17:42:57 -0700
    • Engine revision bd2e42b203
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by huycozy** [comment] 2023-07-06 10:56
Thanks for the report. I can reproduce this issue on `iPhone 14 Pro, iOS 16.4 (emulator)`. Meanwhile, it doesn't happen on another device `iPhone 7, iOS 15.7.2` and Android device.

Lifecycle states are a bit different as below on Flutter master channel (additional `hidden` state), but `resumed` does appear when the screen is locked:
```console
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.resumed
flutter: AppLifecycleState: AppLifecycleState.inactive
flutter: AppLifecycleState: AppLifecycleState.hidden
flutter: AppLifecycleState: AppLifecycleState.paused
```
### Additional information
- I see there is a similar report at https://github.com/flutter/flutter/issues/130038 but it's still not very clear when the OP described the issue with case: `move the app to background or terminated state`. 

    cc @bilalgodesto: it's good to have a look at this issue if this is the case same to yours. If it is, feel free to close your issue and follow up on this issue. 

- Looks like `didChangeAppLifecycleState ` API might be changed in the upcoming time (see https://github.com/flutter/flutter/issues/73947#issuecomment-1421333690) (Linking this issue to it so that we can verify this again once the new API is landed)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-14.0.pre.48, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-14.0.pre.48 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc49cd1bca (3 hours ago), 2023-07-05 17:42:57 -0700
    • Engine revision bd2e42b203
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by bilalgodesto** [comment] 2023-07-06 12:12
@darshankawar 
In my case didChangeAppLifecycleState resume state is called multiple times on both android and ios

**Comment by onuohasilver** [comment] 2023-07-07 00:18
> @darshankawar In my case didChangeAppLifecycleState resume state is called multiple times on both android and ios

Currently experiencing the same issue. Any temporary hack around it for now?

**Comment by EmmanuelAdeiza** [comment] 2023-07-07 00:28
Same here. Any fix yet?

**Comment by zanderso** [comment] 2023-07-10 18:00
cc @gspencergoog for context and help with triage.

**Comment by gspencergoog** [comment] 2023-07-10 18:12
The application states on iOS are determined by calls from the OS: `resumed` isn't entered unless `applicationBecameActive` is called, or if `UIApplication.sharedApplication.applicationState == UIApplicationStateActive` and `viewDidAppear` is called.

If the OS is calling those differently on different OS releases, then there's not much we can do about that. The framework already filters out state changes that traverse to the same state it is already in, so duplicate transitions shouldn't occur, only transitions that actually change the state.

Perhaps the problem is that we're entering the `inactive` state more often then necessary? If that's the case, and we've been relying on deduplication to prevent calls to resume in the past, it might cause more calls to resume to occur.

Is this a regression, or just undesired behavior?

**Comment by zhongwuzw** [comment] 2023-08-22 02:56
I debugged on iPhone 14 Pro, the system fires inactive， active， inactive notification in one runloop, seems we can cancel the inactive using `performSelector` and `cancelPreviousPerformRequestsWithTarget`. I'll try to make a PR for this.

**Closed** 2023-08-29 06:59 UTC
Labels: e: device-specific, platform-ios, framework, engine, has reproducible steps, P2, found in release: 3.10, found in release: 3.12, team-ios, triaged-ios, multiteam-retriage-candidate
