### ISSUE TITLE
Can you plan to support Huawei HarmonyOS NEXT and Open HarmonyOS ArkTs programming language

### ISSUE THREAD

**Issue by kshq1996** [flutter/flutter#150755] opened 2024-06-25 04:29 UTC
### Use case

Huawei HarmonyOS NEXT and Open HarmonyOS Not support android apk

### Proposal

please Support Huawei HarmonyOS NEXT and Open HarmonyOS，ArkTs ,

doc：https://developer.huawei.com/consumer/cn/arkts

**Comment by danagbemava-nc** [comment] 2024-06-25 09:33
Flutter has no plan for this currently, you can check [gitee.com/openharmony-sig/flutter_flutter](https://gitee.com/openharmony-sig/flutter_flutter) to see if it helps. Please also see suggestion on https://github.com/flutter/flutter/issues/150536#issuecomment-2179766074.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/38437

**Closed by danagbemava-nc** 2024-06-25 09:33 UTC
Labels: in triage
