### ISSUE TITLE
InputDecorationTheme override does not work in appBarTheme override in Search Box

### ISSUE THREAD

**Issue by kevaljuthani** [flutter/flutter#56574] opened 2020-05-07 17:56 UTC
My flutter application has the form where I am using TextFormFields. And to theme them, I have added InputDecorationTheme in my light and dark theme. Light theme property is given below:

```dart
inputDecorationTheme: InputDecorationTheme(
        focusColor: Colors.black,
        labelStyle: TextStyle(
          color: Colors.black54,
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(
            color: Colors.black,
          ),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(
            color: Colors.black,
            width: 2.0,
          ),
        ),
      ),

```
Because of this setup I get perfect TextFormFields with border, as expected. But this changes the Search TextField in the appBar in Search Delegate.
![Screenshot_20200507-133021](https://user-images.githubusercontent.com/62698603/81327937-ad5b1b00-90b9-11ea-9e42-0df7ac9e5df2.png)

I did override appBarTheme in search delegate function like this

```dart
@override
  ThemeData appBarTheme(BuildContext context) {
    if (MediaQuery.of(context).platformBrightness == Brightness.dark) {
      final ThemeData theme = Theme.of(context);
      return theme.copyWith(
        inputDecorationTheme: theme.inputDecorationTheme.copyWith(
          border: InputBorder.none,
          focusedBorder: InputBorder.none,
          enabledBorder: InputBorder.none,
          hintStyle: TextStyle(
            color: Colors.grey,
            fontFamily: theme.primaryTextTheme.headline6.fontFamily,
          ),
        ),
        textTheme: theme.textTheme.copyWith(
          headline6: theme.textTheme.headline6
              .copyWith(color: theme.primaryTextTheme.headline6.color),
        ),
      );
    } else {
      assert(context != null);
      final ThemeData theme = Theme.of(context);
      assert(theme != null);
      return theme.copyWith(
        inputDecorationTheme: theme.inputDecorationTheme.copyWith(
          border: InputBorder.none,
          focusedBorder: InputBorder.none,
          enabledBorder: InputBorder.none,
          hintStyle: TextStyle(
            color: Colors.grey,
            fontFamily: theme.primaryTextTheme.headline6.fontFamily,
          ),
        ),
      );
    }
  }
```

This override is not helping. It only changes hint style as far as input decoration theme is concerned.

**Comment by iapicca** [comment] 2020-05-08 07:12
Hi @kevaljuthani 
can you please provide your `flutter doctor -v`
and  a reproducible minimal code sample.
Thank you

possible duplicate of
https://github.com/flutter/flutter/issues/19734
https://github.com/flutter/flutter/issues/45498
https://github.com/flutter/flutter/issues/52483
see also
https://github.com/flutter/flutter/issues/48857

**Comment by kevaljuthani** [comment] 2020-05-08 10:57
> 
> 
> Hi @kevaljuthani
> can you please provide your `flutter doctor -v`
> and a reproducible minimal code sample.
> Thank you
> 
> possible duplicate of
> #19734
> #45498
> #52483
> see also
> #48857

Hello @ianloic ,

```

> Flutter doctor -v result:
> 
> [√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-IN)
>     • Flutter version 1.17.0 at C:\src\flutter
>     • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
>     • Engine revision 540786dd51
>     • Dart version 2.8.1
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\Keval\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.45.0)
>     • VS Code at C:\Users\Keval\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.10.1
> 
> [√] Connected device (1 available)
>     • Pixel 2 • FA7A61A09831 • android-arm64 • Android 10 (API 29)
> 
> • No issues found!

```

To reproduce the issue I have created a small app which has search delegate. 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        primaryTextTheme: TextTheme(
          headline5: TextStyle(
            fontSize: 22,
            color: Colors.black,
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          focusColor: Colors.black,
          labelStyle: TextStyle(
            color: Colors.black54,
          ),
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide(
              color: Colors.black,
            ),
          ),
          focusedBorder: OutlineInputBorder(
            borderSide: BorderSide(
              color: Colors.black,
              width: 2.0,
            ),
          ),
        ),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _form = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Search Test'),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () async {
              final searchQuery = await showSearch(
                context: context,
                delegate: DataSearch(),
              );
            },
          )
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Form(
          key: _form,
          child: ListView(
            children: <Widget>[
              TextFormField(
                style: Theme.of(context).primaryTextTheme.headline6,
                textCapitalization: TextCapitalization.characters,
                initialValue: '',
                decoration: InputDecoration(labelText: 'Enter something'),
              )
            ],
          ),
        ),
      ),
    );
  }
}

class DataSearch extends SearchDelegate<String> {
  List<String> continents = [
    'Africa',
    'Asia',
    'Antarctica',
    'Europe',
    'North America',
    'Australia',
    'South America',
  ];

  List<String> suggested = [
    'Africa',
    'Europe',
  ];
  @override
  String get searchFieldLabel => 'Search something!';

  @override
  ThemeData appBarTheme(BuildContext context) {
    assert(context != null);
    final ThemeData theme = Theme.of(context);
    assert(theme != null);
    return theme.copyWith(
      inputDecorationTheme: theme.inputDecorationTheme.copyWith(
        border: InputBorder.none,
        focusedBorder: InputBorder.none,
        enabledBorder: InputBorder.none,
        hintStyle: TextStyle(
          color: Colors.white,
        ),
      ),
    );
  }

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
        icon: Icon(
          Icons.clear,
        ),
        onPressed: () {
          query = '';
        },
      )
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
        icon: AnimatedIcon(
            icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
        onPressed: () {
          close(context, null);
        });
  }

  @override
  Widget buildResults(BuildContext context) {
    return null;
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Center(
      child: ListView.separated(
        padding: const EdgeInsets.all(10),
        itemCount: suggested.length,
        itemBuilder: (ctx, i) => Text(
          suggested[i],
          style: Theme.of(context).primaryTextTheme.headline5,
        ),
        separatorBuilder: (ctx, i) {
          return Divider();
        },
      ),
    );
  }
}
```

After running the above code, you'll see that you can write the changes in appBarTheme to override the inputdecorationtheme but it doesn't get applied. On the screen, you can see that I have created a form with a TextFormField, and the base theme data gets applied to that field. The only way to not have the border around search box is to remove it from the theme itself. Please look at the screenshots
![Screenshot_20200508-162239](https://user-images.githubusercontent.com/62698603/81399465-ae875900-9148-11ea-97b5-a67a12f25128.png)
![Screenshot_20200508-162244](https://user-images.githubusercontent.com/62698603/81399464-ad562c00-9148-11ea-92f8-4c4ed23bf684.png)

**Comment by iapicca** [comment] 2020-05-08 14:05
Hi @kevaljuthani 
as mentioned above
there's an open [issue](https://github.com/flutter/flutter/issues/45498) addressing the case you 
described linked to a pending [PR](https://github.com/flutter/flutter/pull/55209).

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by kevaljuthani** [comment] 2020-05-08 14:13
Hello @iapicca ,
I have also done the pull request #56577

**Comment by iapicca** [comment] 2020-05-08 14:39
Hi again @kevaljuthani 
I apologise, I missed your PR
I took the liberty of referencing it in the linked issue for visibility,
for now I'm keeping the issue open as reference.
Thanks again

**Comment by kevaljuthani** [comment] 2020-06-13 04:19
Hello @iapicca ,
I have opened a new pull request ( #58970 ) as my forked repo got too many unnecessary commits

**Comment by markusaksli-nc** [comment] 2020-07-20 09:43
Closing this as a duplicate of #45498. Referencing the PR in the mentioned issue to track it there.

**Closed by markusaksli-nc** 2020-07-20 09:43 UTC
Labels: a: quality, f: material design, framework
