### ISSUE TITLE
image_picker: Fatal Exception being thrown when picking file from gallery in Android

### ISSUE THREAD

**Issue by diver2** [flutter/flutter#29594] opened 2019-03-19 10:02 UTC
This was first found/discussed in #21863 but is not the same I guess.
When picking a file from Android, sometimes the code crashes with a fatal error such as:

```
E/BitmapFactory(26640): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Download/cube-clipart-unit-cube-3.png (No such file or directory)
D/AndroidRuntime(26640): Shutting down VM
E/AndroidRuntime(26640): FATAL EXCEPTION: main
E/AndroidRuntime(26640): Process: com.logbkapp.app, PID: 26640
E/AndroidRuntime(26640): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/627 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }} to activity {com.logbkapp.app/com.logbkapp.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(26640): at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
E/AndroidRuntime(26640): at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
E/AndroidRuntime(26640): at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime(26640): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
E/AndroidRuntime(26640): at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26640): at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(26640): at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(26640): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26640): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(26640): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime(26640): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(26640): at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:48)
E/AndroidRuntime(26640): at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
E/AndroidRuntime(26640): at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:430)
E/AndroidRuntime(26640): at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:372)
E/AndroidRuntime(26640): at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:351)
E/AndroidRuntime(26640): at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(26640): at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime(26640): at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(26640): at android.app.Activity.dispatchActivityResult(Activity.java:7256)
E/AndroidRuntime(26640): at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
E/AndroidRuntime(26640): ... 9 more
```
Code causing the crash was a simple
```dart
void _getImage(BuildContext context, ImageSource source) {
    ImagePicker.pickImage(source: source, maxHeight: 400.0).then((io.File image) {
      setState(() => _imageFile = image);
      Navigator.pop(context);
    }).catchError((onError) {
      print(onError);
    });
  }
```
After investigation, I found out that on `ImagePickerDelegate.java` we could use a check to test the path returned by FileUtils

```java
private void handleChooseImageResult(int resultCode, Intent data) {
    if (resultCode == Activity.RESULT_OK && data != null) {
      //String path = fileUtils.getPathFromUri(activity, data.getData());
      String path = FileUtils.getRealPath(activity, data.getData());
       if (path==null || !(new File(path).canRead() )) {
        finishWithError("ACCESS_ERROR",
            "Can't read your photo. Please pick one in the gallery, not in other folders such as downloads. Some Android versions mishandle those folders.");
        return;
      }
      handleImageResult(path);
      return;
    }

    // User cancelled choosing a picture.
    finishWithSuccess(null);
  }
```
This prevents the fatal crashes, and makes your code pleasant to the user... should be there anyways. I'm still investigating if FileUtils can access the downloads folder on proper files, if this is an issue.

There is another confirmed issue that I'm investigating: when choosing a good image (from the Gallery for example), it creates a new file with the image in your phone (so changing the date of your image/photo), and leaves the handle for the old file invalid, an invalid file path. On my phone, it shows the proper thumbnail in gallery view, but when I click on it, it shows a white exclamation dot on a grey background when you try to access.
Maybe it is my fix that is causing this... (interrupting some process without deleting tmp files, for example). Still investigating.

@cyanglaz

**Comment by temirfe** [comment] 2019-04-01 10:13
same problem on Android 4.4.4, also image in phone gallery gets deleted

**Comment by Toolenaar** [comment] 2019-04-03 12:08
Having the same problem. But it happens on any image I pick from any source. The app just crashes with
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/295/ORIGINAL/NONE/257219287 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F295/ORIGINAL/NONE/257219287} }} to activity {nl.thebroadcaster.locali/com.example.locali.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
```

**Comment by cyanglaz** [comment] 2019-04-03 17:32
I wasn't able to reproduce the same issue. Can someone provide some device models and android version that this issue happened on?

**Comment by ozzy1873** [comment] 2019-04-03 22:34
Pixel 3, Android 9
Here is some additional info:
This happens when picking a file from the downloads folder while specifying maxHeight and maxWidth. If the maxHeight and maxWidth are not specified, the error does not occur. However, once the error has occurred, the image will not be loadable whether or not maxWidth and maxHeight are specified. With maxWidth and maxHeight specified, the exception will be thrown. Without, an error will be returned. My users are reporting that as soon as they pick a file from the downloads directory with maxHeight and maxWidth specified, the file gets deleted or, in some cases, replaced with a gray box with an exclamation point in the center of it. On my phone (Pixel 3), it looks like the file is there, but it is not pickable. 

Looking at the changelog, I see that 0.5.0+6 introduced "delete original image if it was scaled". I think that original images should not be modified in any way by the image_picker. If a file must be generated when scaling, it should be a separate file.

**Comment by cyanglaz** [comment] 2019-04-04 18:41
Should be fixed in https://github.com/flutter/plugins/pull/1445. If any related issue is found, please feel free to open another issue with details.

**Closed by cyanglaz** 2019-04-04 18:41 UTC
Labels: p: image_picker, plugin
