### ISSUE TITLE
Collect statistics on dependency resolution failure rates

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#35277] opened 2019-06-28 16:28 UTC
We suspect that failures to resolve an app's dependency constraint is a real pain for Flutter developers.

To get further insight and monitor this we'd like to collect statistics regarding the number of `pub get`/`pub upgrade` invocations that succeed/fail to resolve dependency constraints.

While this can potentially be reported by the pub client, the required collection infrastructure isn't in place.

The flutter tool seems like a good candidate for reporting this metric as it wraps the pub invocations for flutter apps and has metric collection infra.

cc @zanderso @jonasfj @kevmoo

**Comment by kevmoo** [comment] 2019-06-28 16:51
cc @mit-mit

**Comment by zanderso** [comment] 2020-02-11 21:41
Closing as duplicate of https://github.com/flutter/flutter/issues/41309

**Closed by zanderso** 2020-02-11 21:41 UTC
Labels: severe: new feature, tool
