### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by hussampw** [flutter/flutter#125681] opened 2023-04-28 09:18 UTC
## Command
```
flutter run --machine -d cf324870 --profile --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:280:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Kali GNU/Linux Rolling 6.1.0-kali5-amd64, locale en_US.UTF-8)
    • Flutter version 3.7.0-1.2.pre on channel beta at /home/hussam/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (4 months ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /usr/lib/android-sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /usr/lib/android-sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version openjdk version "11.0.10" 2021-01-19
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version openjdk version "11.0.10" 2021-01-19

[✓] Android Studio
    • Android Studio at /usr/local/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio/
    • Java version openjdk version "11.0.10" 2021-01-19

[✓] VS Code (version 1.76.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • M2101K6G (mobile) • cf324870 • android-arm64  • Android 12 (API 31)
    • Linux (desktop)   • linux    • linux-x64      • Kali GNU/Linux Rolling 6.1.0-kali5-amd64
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.2+123
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
### Plugins
app_tracking_transparency-2.0.3
device_apps-2.2.0
device_info-2.0.3
firebase_core-2.4.1
firebase_core_web-2.1.0
firebase_crashlytics-3.0.11
firebase_messaging-14.2.1
firebase_messaging_web-3.2.11
flutter_inapp_purchase-7ecc5aab96455026a75b2500d77b90ad43dbf793
flutter_local_notifications-13.0.0
google_mobile_ads-2.4.0
in_app_review-2.0.6
in_app_update-4.0.1
native_admob_flutter-1.5.0+1
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.7
path_provider_windows-2.1.3
share-2.0.4
shared_preferences-2.0.17
shared_preferences_android-2.0.15
shared_preferences_foundation-2.1.2
shared_preferences_linux-2.1.3
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.3
sqflite-2.2.3
url_launcher-6.1.8
url_launcher_android-6.0.23
url_launcher_ios-6.0.18
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.2

**Comment by danagbemava-nc** [comment] 2023-04-28 09:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/118400

**Closed by danagbemava-nc** 2023-04-28 09:42 UTC
Labels: in triage
