### ISSUE TITLE
[web] the bottom text is partially obscured When textfield fills a line

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#62952] opened 2020-08-05 07:32 UTC
example code：

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context)=> MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with SingleTickerProviderStateMixin  {


  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Material(
      child: TextField(
        enabled: true,
        textAlign: TextAlign.left,
        style: TextStyle(
            fontSize: 16, color: Colors.blue , fontWeight: FontWeight.w500),
        maxLines: 1,
        minLines: 1,
        decoration: 
            InputDecoration(
                filled: true,
                fillColor: Colors.white,
                enabled: true,
                helperText: "",
                isDense: true,
                focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.all(Radius.circular(4.0)),
                    borderSide:
                        BorderSide(color: Colors.blue, width: 1.0)),
                enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.all(Radius.circular(4.0)),
                    borderSide:
                        BorderSide(color: Colors.blue, width: 1.0)),
                disabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.all(Radius.circular(4.0)),
                    borderSide:
                        BorderSide(color: Colors.blue, width: 1.0)),
                hintText: "hint",
                hintStyle: TextStyle(fontSize: 16, color: Colors.blue)),
        maxLength: 100,
      ),
    );
}

```
input some character  "gggGGGBBBbbbVVVvvvggg谅解GGGBBBbbbVVVvvvgggGGGBBBbbbVVVvvv" 

![image](https://user-images.githubusercontent.com/2295872/89384194-4ee11f80-d730-11ea-8fc0-f65c91c3dbf9.png)

flutter doctor - v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.190, on Mac OS X 10.15.5 19F101,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2020-08-05 09:46
Hi @lyf571321556,
Please see my comment on [62949](https://github.com/flutter/flutter/issues/62949).

**Comment by lyf571321556** [comment] 2020-08-05 14:46
@darshankawar  Sorry, I forgot to mark it as a web issue!

**Comment by lyf571321556** [comment] 2020-08-05 14:56
@darshankawar , this issue  produced on android brower or iOS safari.

**Comment by mdebbar** [comment] 2020-08-06 21:32
Duplicate of https://github.com/flutter/flutter/issues/40221

**Closed by mdebbar** 2020-08-06 21:32 UTC
Labels: P4, a: text input, a: typography, e: web_html, platform-web
