### ISSUE TITLE
Windows desktop support

### ISSUE THREAD

**Issue by Gavin-Williams** [flutter/flutter#45881] opened 2019-12-02 06:10 UTC
## Use case

Windows desktop applications / games

## Proposal

Win32? Ahm, a lot of new Windows app and game development is moving in the UWP/WinRT direction. Microsoft have been moving in that direction for years now. Even WinForms and WPF are moving to .Net Core (which is a sister technology to UWP with all the UWP technologies being integrated). It seems to me like targeting C based Windows (or .Net Framework) is a little bit old school. Not many people go back to Win32/GDI/.Net Framework after adopting WinRT/.Net Core/UWP. Time moves in one direction generally.

Do you intend to make this usable from both C# and C++ like Windows Runtime Components?

If going UWP route, I don't know if you intend to wrap WinUI like the other frameworks or if you intend to use a custom DirectX layer - if that's the case then CoreWindow would obviously be the choice?

It's hard to imagine how the Win32 approach is going to be useful in 5-10 years. Just a few years ago, Win32 still seemed relevant. But I would be very cautious about investing in that approach now. I'm just curious how you're going to get this to the people that want to use it. Isn't it more likely that people using UWP and WinUI today are the same people that will look at flutter. Legacy apps already have their code base in place. It's greenfield projects you want to be targeting.

Anyway, excited to see some interest in Windows!

**Comment by stuartmorgan** [comment] 2019-12-02 12:03
It's not clear to me what exactly the proposal here is; as far as I can tell though this is a duplicate of #14967.

**Closed by stuartmorgan** 2019-12-02 12:03 UTC

**Comment by stuartmorgan** [comment] 2019-12-02 12:06
>  I don't know if you intend to wrap WinUI

Flutter on Windows will use the same approach as it does on every other platform, so no.
