### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by whichname** [flutter/flutter#103685] opened 2022-05-13 08:22 UTC
Flutter application crash:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> hide <<<

backtrace:
  #00  pc 00000000017c6e94  /vendor/lib64/egl/libGLES_mali.so [arm64-v8a::a3d2ed1e7122bb3da94a891fa469c4d1]
  #01  pc 00000000017c8800  /vendor/lib64/egl/libGLES_mali.so [arm64-v8a::a3d2ed1e7122bb3da94a891fa469c4d1]
  #02  pc 00000000017df110  /vendor/lib64/egl/libGLES_mali.so [arm64-v8a::a3d2ed1e7122bb3da94a891fa469c4d1]
  #03  pc 00000000017ddea4  /vendor/lib64/egl/libGLES_mali.so [arm64-v8a::a3d2ed1e7122bb3da94a891fa469c4d1]
  #04  pc 000000000000d4c8  /system/lib64/libEGL.so [arm64-v8a::b1a71d4d7d49a4bb60aef39abd09301c]
  #05  pc 000000000000964c  /system/lib64/libEGL.so (eglSwapBuffersWithDamageKHR+104) [arm64-v8a::b1a71d4d7d49a4bb60aef39abd09301c]
  #06  pc 000000000000b084  /hide/arm64-v8a/libflutter.so 
  #07  pc 0000000000342db4  /hide/arm64-v8a/libflutter.so 
  #08  pc 0000000000270f8c  /hide/arm64-v8a/libflutter.so 
  #09  pc 0000000000270fd0  /hide/arm64-v8a/libflutter.so 
  #10  pc 000000000044d0f8  /hide/arm64-v8a/libflutter.so 
  #11  pc 000000000027be64  /hide/arm64-v8a/libflutter.so 
  #12  pc 000000000027ba8c  /hide/arm64-v8a/libflutter.so 
  #13  pc 000000000027cb14  /hide/arm64-v8a/libflutter.so 
  #14  pc 000000000027c538  /hide/arm64-v8a/libflutter.so 
  #15  pc 0000000000284c68  /hide/arm64-v8a/libflutter.so 
  #16  pc 000000000002b7bc  /hide/arm64-v8a/libflutter.so 
  #17  pc 000000000002f088  /hide/arm64-v8a/libflutter.so 
```
Flutter version: 2.10.5

**Comment by whichname** [comment] 2022-05-13 08:23
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/103685#issue-1234901092 flutter#v2.10.5 arm64

**Comment by whichname** [comment] 2022-05-13 08:26
Maybe is the same issue with https://github.com/flutter/flutter/issues/100122#issue-1169404600 ?

**Comment by darshankawar** [comment] 2022-05-13 09:57
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/103685#issue-1234901092 flutter#v2.10.5 arm64

**Comment by darshankawar** [comment] 2022-05-13 10:03
Keeping it open for further insights from the team.

/cc @chinmaygarde

**Comment by whichname** [comment] 2022-05-20 02:32
Hi, bro, any progress?

**Comment by Vollinator** [comment] 2022-06-22 08:30
Hi there,
I have had the same error since upgrading to Flutter 3. I downgrade back to 2.10.5 and everything works without problems.
Here is the more detailed log that is written during the crash:

```
> --------- beginning of crash
> 05-18 10:47:58.238 F/libc    (15072): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15109 (1.ui)
> 05-18 10:47:58.241 W/        ( 3011): debuggerd: handling request: pid=15072 uid=10232 gid=10232 tid=15109
> 05-18 10:47:58.287 E/audit   ( 3019): type=1400 audit(1652863678.271:402): avc:  denied  { search } for  pid=15590 comm="debuggerd64" name="com.google.android.gms" dev="sda18" ino=721084 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0005
> 05-18 10:47:58.288 E/audit   ( 3019): type=1400 audit(1652863678.271:403): avc:  denied  { search } for  pid=15590 comm="debuggerd64" name="com.google.android.gms" dev="sda18" ino=721084 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0005
> 05-18 10:47:58.288 E/audit   ( 3019): type=1400 audit(1652863678.271:404): avc:  denied  { search } for  pid=15590 comm="debuggerd64" name="com.google.android.gms" dev="sda18" ino=721084 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0005
> 05-18 10:47:58.359 F/DEBUG   (15590): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 05-18 10:47:58.364 F/DEBUG   (15590): Build fingerprint: 'samsung/zerofltexx/zeroflte:7.0/NRD90M/G920FXXU5EQCN:user/release-keys'
> 05-18 10:47:58.364 F/DEBUG   (15590): Revision: '11'
> 05-18 10:47:58.364 F/DEBUG   (15590): ABI: 'arm64'
> 05-18 10:47:58.364 F/DEBUG   (15590): pid: 15072, tid: 15109, name: 1.ui  >>> com.test.app <<<
> 05-18 10:47:58.364 F/DEBUG   (15590): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
> 05-18 10:47:58.364 F/DEBUG   (15590):     x0   0000000000000000  x1   0000007a8eea4560  x2   0000000000000008  x3   0000000000000000
> 05-18 10:47:58.364 F/DEBUG   (15590):     x4   0000000000000000  x5   0000007a961c9c98  x6   00ffffffffffffff  x7   ffffffffffffffff
> 05-18 10:47:58.364 F/DEBUG   (15590):     x8   000000005ae4141b  x9   000000007fc00000  x10  0000000000000000  x11  000000007f800000
> 05-18 10:47:58.364 F/DEBUG   (15590):     x12  0000000000000000  x13  ffffffffffffff00  x14  0000000000000000  x15  2e8ba2e8ba2e8ba3
> 05-18 10:47:58.365 F/DEBUG   (15590):     x16  0000007a96d23e18  x17  0000007abea55a80  x18  0000007a5f3f51a0  x19  0000000000000100
> 05-18 10:47:58.365 F/DEBUG   (15590):     x20  0000000000000081  x21  0000000000000000  x22  0000007a961c9e40  x23  0000007a936a4fa8
> 05-18 10:47:58.365 F/DEBUG   (15590):     x24  0000007a4f7e31e0  x25  0000007a8edf8a00  x26  0000007ab184f700  x27  0000007a8ee80c00
> 05-18 10:47:58.365 F/DEBUG   (15590):     x28  0000007a96d00a68  x29  0000007a936a4f00  x30  0000007a96ab4228
> 05-18 10:47:58.365 F/DEBUG   (15590):     sp   0000007a961c9d40  pc   0000007a96ab4234  pstate 0000000080000000
> 05-18 10:47:58.367 F/DEBUG   (15590): 
> 05-18 10:47:58.367 F/DEBUG   (15590): backtrace:
> 05-18 10:47:58.367 F/DEBUG   (15590):     #00 pc 00000000002f8234  /data/app/com.test.app-1/lib/arm64/libflutter.so (offset 0x2ea000)
> 05-18 10:47:58.367 F/DEBUG   (15590):     #01 pc 00000000002f8224  /data/app/com.test.app-1/lib/arm64/libflutter.so (offset 0x2ea000)
```

flutter doctor -v output:

```

> [√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1706], locale de-DE)
>     • Flutter version 3.0.2 at C:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
>     • Engine revision f15f824b57
>     • Dart version 2.17.3
>     • DevTools version 2.12.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     • Android SDK at C:\Development\Android_SDK
>     • Platform android-32, build-tools 32.1.0-rc1
>     • ANDROID_HOME = C:\Development\Android_SDK
>     • Java binary at: C:\Development\Android_Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.6.30225.117
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 4.1)
>     • Android Studio at C:\Development\Android_Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.68.1)
>     • VS Code at C:\Users\---\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.42.0
> 
> [√] Connected device (4 available)
>     • SM G986B (mobile) • RFCN90X3K0R • android-arm64  • Android 11 (API 30)
>     • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
>     • Chrome (web)      • chrome      • web-javascript • Google Chrome 102.0.5005.115
>     • Edge (web)        • edge        • web-javascript • Microsoft Edge 102.0.1245.44
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
```

**Comment by chinmaygarde** [comment] 2022-07-25 17:55
Without a reproducible test case, this isn't actionable. Closing. Please re-open once a reduced test case can be created.

**Closed by chinmaygarde** 2022-07-25 17:55 UTC
Labels: severe: crash, platform-android, engine, a: production, needs repro info
