### ISSUE TITLE
[web] Stop spam 'postEvent Flutter.Frame' logs in debug mode by default

### ISSUE THREAD

**Issue by chertov** [flutter/flutter#75225] opened 2021-02-02 13:58 UTC
## Use case
In the debug mode flutter app in web has a lot of messages like this:
![image](https://user-images.githubusercontent.com/436625/106607945-ea830980-6574-11eb-913e-6512af3c60b0.png)

```
dart.developer.postEvent Flutter.Frame {"number":11,"startTime":13272380,"elapsed":18300,"build":14485,"raster":3775,"vsyncOverhead":35} developer_patch.dart:95
dart.developer.postEvent Flutter.Frame {"number":12,"startTime":13357145,"elapsed":16825,"build":13075,"raster":3731,"vsyncOverhead":15} developer_patch.dart:95
dart.developer.postEvent Flutter.Frame {"number":13,"startTime":13477574,"elapsed":12490,"build":9161,"raster":3310,"vsyncOverhead":15} developer_patch.dart:95
```

I found a bad way to disable it:
```Dart
import 'package:flutter/scheduler.dart';
void main() async {
    // go to definition initInstances() and comment all under if (!kReleaseMode) {}
    SchedulerBinding.instance.initInstances();
}
```

https://github.com/flutter/flutter/blob/502ff3dbfec73677aa4bee2a9dd1129075a39aab/packages/flutter/lib/src/scheduler/binding.dart#L209

## Proposal

Is it possible to add an option and disable this logs by default?

**Comment by darshankawar** [comment] 2021-02-03 06:53
@chertov 
Can you provide `flutter doctor -v` and a minimal code sample that shows these logs ?

**Comment by chertov** [comment] 2021-02-10 23:41
@darshankawar, i found that CircularProgressIndicator() writes this logs.
I see this logs in chrome console on https://dartpad.dev/ with this sample:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}
```

my flutter doctor -v
```
MacBook-Pro:app user$ flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-18.0.pre.257, on macOS 11.2.1 20D74 darwin-x64, locale en-RU)
    • Flutter version 1.26.0-18.0.pre.257 at /Users/user/development/flutter
    • Framework revision 16af4aa7eb (15 hours ago), 2021-02-10 17:01:04 +0800
    • Engine revision b3a18f5182
    • Dart version 2.13.0 (build 2.13.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.8.0 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment] 2021-02-11 06:45
@chertov 
I was able to see the logs in the web console after running your code sample. Although only after I selected `verbose` option from the list. So the logs are not displayed by default, but only when we select `verbose`.

<img width="165" alt="Screenshot 2021-02-11 at 12 08 51 PM" src="https://user-images.githubusercontent.com/67046386/107608747-cf925280-6c62-11eb-93f4-d40267ff1b32.png">
<img width="552" alt="Screenshot 2021-02-11 at 12 09 11 PM" src="https://user-images.githubusercontent.com/67046386/107608750-d0c37f80-6c62-11eb-8801-2b8f03aaaac1.png">

**Comment by chertov** [comment] 2021-02-11 08:37
@darshankawar thank you! I had the console sidebar open. With the sidebar chrome shows all log levels even if the 'default levels' are selected.
In my opinion it is a strange chrome UI problem.

https://user-images.githubusercontent.com/436625/107615211-d027ea80-6c5c-11eb-91db-10423dff5415.mov

**Comment by BartusZak** [comment] 2021-02-24 12:12
Hey @chertov  and @darshankawar,

How are you?

Is there any way to disable those messages?

My first idea was that is a memory leak...

It increments to a huge value and crashes Chrome Dev Tools (no response, etc.)

![image](https://user-images.githubusercontent.com/16143176/108998679-8a7a1180-76a1-11eb-8645-c21a421fba75.png)
![image](https://user-images.githubusercontent.com/16143176/108998948-ecd31200-76a1-11eb-9036-50d01c0c8bc1.png)
![image](https://user-images.githubusercontent.com/16143176/108998622-78986e80-76a1-11eb-84af-49d1ec6f9714.png)

**Comment by John-Dormevil** [comment] 2021-03-11 15:03
litteraly crash my devtools instance in chrome

**Comment by John-Dormevil** [comment] 2021-03-11 15:11
![image](https://user-images.githubusercontent.com/18209197/110808521-5a776480-8284-11eb-97cf-59fda895ff84.png)

**Comment by BartusZak** [comment] 2021-03-23 10:47
Can we please reopen that issue?

Does update to Flutter 2.0 fix the problem?

**Comment by sbergmair** [comment] 2021-03-23 13:04
No, it doesn't
I have the same issue 

Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (3 weeks ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by christopherfujino** [comment] 2021-04-05 18:18
I'm re-opening the issue as it seems that even if the logs messages are not shown by default, they are still loading in memory and freezing devtools.

**Comment by jacob314** [comment] 2021-04-08 21:50
@grouma, @nshahan we should cleanup the DDC implementation of dart:developer so it doesn't rely on `console.debug` to dispatch events. With the chrome debug extension, it would be fairly easy dispatch events via a different mechanism. I'd have to think about how we would handle this case otherwise. 
Note that the user has enabled verbose logging in chrome devtools. With the default logging settings you wouldn't see the messages.
<img width="553" alt="Screen Shot 2021-04-08 at 2 47 19 PM" src="https://user-images.githubusercontent.com/1226812/114100629-6fdab100-9879-11eb-8bfb-a463d28ea6bf.png">

**Comment by christopherfujino** [comment] 2021-04-08 22:33
> Note that the user has enabled verbose logging in chrome devtools. With the default logging settings you wouldn't see the messages.

Note that even with the default logging settings, these will load in memory and crash chrome devtools.

**Comment by jacob314** [comment] 2021-04-08 22:58
I'm surprised this is actually crashing chrome unless the overhead per log message is much higher than I'm estimating.
Assuming 200 bytes per message, an an app that runs an animation continuously at 60FPS will take a day for the log to use ~1gb of memory. Typical Flutter apps shouldn't be continuously animating so the real usage should be a lot less.
`200*60*60*60*24 = 1036800000`

**Comment by BartusZak** [comment] 2021-04-09 10:05
The funny part of that is when loader/ spinner is being displayed for a user it produces thousands of logs to `Google DevTools` and crashes the app with `release` build even.

Messages aren't displayed by default but they are produced underneath still like you can see here:

> ![image](https://user-images.githubusercontent.com/16143176/108998948-ecd31200-76a1-11eb-9036-50d01c0c8bc1.png)
> ![image](https://user-images.githubusercontent.com/16143176/108998622-78986e80-76a1-11eb-84af-49d1ec6f9714.png)

**Comment by mdebbar** [comment] 2021-04-09 16:59
At least on Chrome, these logs are hidden by default. On other browsers e.g. Safari, they are visible and there's no way to hide them:

![image](https://user-images.githubusercontent.com/1278212/114215093-09599f80-991a-11eb-8491-06120f9e82b7.png)

**Comment by jacob314** [comment] 2021-04-09 17:37
We don't support Dart VM Service debugging on any browsers other than Chrome and Edge so there is no cost to replacing dart:developer with a no-op implementation on Safari and FireFox similar to what we do in release dart2js builds. Fyi @nshahan

**Comment by grouma** [comment] 2021-04-09 17:42
We could hoist a global function in `package:dwds` injected [client](https://github.com/dart-lang/webdev/blob/658f69284cab7b025a4742f1039ced6e16cd6143/dwds/web/client.dart#L35). This could use the existing SSE / Websocket connection for communication. However, when the application is paused, we won't get events. Is this a blocker?

**Comment by jacob314** [comment] 2021-04-09 17:53
As long as events are sent in order when the application resumes this should be acceptable even though it technically diverges from the VM implementation. Flutter is is already intentionally making all of its extensions wait until the app resumes to avoid bugs due to service extensions executing in the middle of a frame.
I am not sure we should but we could modify the Dart VM to match the behavior Flutter is already adopting. My main concern would be that this default would not be good for command line Dart code.

**Comment by grouma** [comment] 2021-04-09 18:00
I think we need a bit more clarity here. Folks have said it crashes the "app". Are they referring to Dart DevTools or Chrome DevTools?

For Dart DevTools, should these logs even be displayed? Are they displayed when debugging a native application?

**Comment by grouma** [comment] 2021-04-09 18:03
One other thing we could explore is clearing the console after a certain number of messages. That obviously has some undesirable consequences.

**Comment by grouma** [comment] 2021-04-09 18:13
For now, I think it makes sense that we don't log to to the console in release mode and unsupported browsers. Routing to @nshahan to triage and fix.

**Comment by nshahan** [comment] 2021-04-09 20:41
> For now, I think it makes sense that we don't log to to the console in release mode and unsupported browsers.

The [dart2js implementation](https://github.com/dart-lang/sdk/blob/da42b0d32308c7bad1c578b89cd7b46449ad5461/sdk/lib/_internal/js_runtime/lib/developer_patch.dart#L51) of postEvent is a no-op already so nothing to change there. That makes [the report of crashes in release mode](https://github.com/flutter/flutter/issues/75225#issuecomment-816574783) all the more confusing. I'm not sure what action to take here. Is there a repro for release mode that someone can point to? 

In debug mode, does the [current implementation](https://github.com/dart-lang/sdk/blob/da42b0d32308c7bad1c578b89cd7b46449ad5461/sdk/lib/_internal/js_dev_runtime/patch/developer_patch.dart#L94) of postEvent do anything useful for DevTools and the extensions when running in Chrome? Are they using the `cosole.debug` log as a communication channel? I could remove it entirely if we want to follow up with a more proper connection between the dart:developer library and the dev tools.

**Comment by grouma** [comment] 2021-04-13 23:18
I confirmed that the `flutter run -d chrome --release` does not have the verbose debug logs. @BartusZak can you confirm you are seeing the same? I'm hesitant to root cause your crash to these logs given this fact.

**Comment by BartusZak** [comment] 2021-04-19 11:41
Hey, @grouma 

Confirmed.

**Comment by grouma** [comment] 2021-04-20 23:16
So it looks like the action item here is to remove the logging support for non-Chrome browsers. @nshahan is that something you can tackle?

@John-Dormevil are we sure these logs are the root cause? Can you share a repro?

**Comment by cws-alb** [comment] 2021-05-01 02:35
Can I ask, who uses this log message? It spams the logs and offers no value to the vast majority of developers. 

Using AndroidStudio to debug a flutter web app, I can see easily 1000 messages within seconds. Simply saying dont have verbose enabled isnt quite the solution as the logs still exist. Chrome shows a count of exactly how many are there. As the advice is to debug in Chome jumping to an alternative browsers seems counter intuitive. If this log entry is needed, can it not have some form of switch to enable it, so those developers who are interested in this log message will have to switch it on? Switch this messages off by default so those with no interest in them dont have to find a way to disable it. My point here is that the developer who is interested in this message is more than likely a lot more technical than I am, probably one of the devs on the flutter team or close to that and will have an usnderstanding of the internals. With that understanding such a person will also know how to enable this logging for their purpose.

I can use Google, which is why I am here, but its just not friendly to have these messages on by default. It uses CPU resources and memory resources generating logs that I have no interest in and whilst debugging which can take some time, my laptop is ramping up to log these messages. Please think of the common dev here and either just delete the message or find a way to disable them so the normal devs dont get spammed. Please.

**Comment by chertov** [comment] 2021-05-12 21:25
i am using only chrome dev console and i do not use Android Studio or Dart DevTools
```flutter run -d web-server --web-port 5000``` open vscode text editor, browser and start coding)
i do not use debug mode as breakpoints, play/pause, but i want to see logs and full errors information like call stack, source maps, etc
release mode starts very slowly, debug is faster!

the spam into console makes chrome dead and sometimes i can't even reload a page on my macbook pro 2016
sometimes I see how a page was rendered but the dev console doesn't response and print state logs only in 20-60 seconds!
Please, remove all unnecessary messages from web console when developer using only browser

**Comment by grouma** [comment] 2021-05-13 15:23
> Please, remove all unnecessary messages from web console when developer using only browser

As mentioned above, these logs are necessary. Does changing the default logging level in Chrome solve your problem?

@jonahwilliams / @nshahan should we consider a Flutter Tools flag to disable these logs? That would come at the cost of no debug support through IDEs and DevTools (among other things?).

**Comment by jonahwilliams** [comment] 2021-05-13 17:06
I think the intention of these messages is that they are consumed by debuggers like devtools. I wouldn't expect them to show up in the console ui. At any rate, we definitely need to keep sending them.

**Comment by nshahan** [comment] 2021-05-13 18:22
> should we consider a Flutter Tools flag to disable these logs? That would come at the cost of no debug support through IDEs and DevTools (among other things?).

It would be simple to add a flag in the DDC runtime that could be set by the infrastructure before running the main method that would disable these log messages. 

I'd like to better understand the desire to turn off these messages as it seems they are important to the debug tools. If they slow down apps running in chrome to the point of them being unusable does this mean those apps can't be debugged using the Dart/Flutter debugger or IDEs at all?

**Comment by cws-alb** [comment] 2021-05-13 18:48
> > Can I ask, who uses this log message? It spams the logs and offers no value to the vast majority of developers.
> 
> These messages is how debugging works through IDEs as well as Dart DevTools. They are consumed by `package:dwds`.
> 
> > Using AndroidStudio to debug a flutter web app, I can see easily 1000 messages within seconds.
> 
> What's the workflow here? How exactly are you debugging the Flutter Web app?
> 
> @jacob314 do we support a Dart / Flutter plugin for Android Studio?
> 
> > Simply saying dont have verbose enabled isnt quite the solution as the logs still exist. Chrome shows a count of exactly how many are there. As the advice is to debug in Chome jumping to an alternative browsers seems counter intuitive. If this log entry is needed, can it not have some form of switch to enable it, so those developers who are interested in this log message will have to switch it on?
> 
> As mentioned above these logs are required for debugging so I'm confused as to how you are debugging your app through Android Studio.
> 
> > Switch this messages off by default so those with no interest in them dont have to find a way to disable it. My point here is that the developer who is interested in this message is more than likely a lot more technical than I am, probably one of the devs on the flutter team or close to that and will have an usnderstanding of the internals. With that understanding such a person will also know how to enable this logging for their purpose.
> 
> That's not the case. We support debugging through IDEs and Dart DevTools which requires these messages.
> 
> > I can use Google, which is why I am here, but its just not friendly to have these messages on by default. It uses CPU resources and memory resources generating logs that I have no interest in and whilst debugging which can take some time, my laptop is ramping up to log these messages. Please think of the common dev here and either just delete the message or find a way to disable them so the normal devs dont get spammed. Please.
> 
> Please provide more details about your Android Studio debug workflow as it may make sense to disable logging in that scenario.

Sorry for the delay here. Using android studio is a noise to the message I and others here are trying to communicate. 

These logs kill chrome. You can ignore them, but they still exist and the browser eventually runs out of memory. 

I’m unclear what the debugger uses these for, but given the volume coming through it’s killing things.

**Comment by grouma** [comment] 2021-05-13 18:52
> These logs kill chrome. You can ignore them, but they still exist and the browser eventually runs out of memory.

What version of Chrome are you using? Does it impact all apps? If not can you provide a sample app. I'm not aware of other reports of Chrome crashing due to these logs.

As mentioned above I wonder if clearing the logs after a set number would alleviate the problem.

**Comment by cws-alb** [comment] 2021-05-13 18:58
> seems

I (and assume others) are using term app to describe the flutter code running through a browser, built using flutter build web. 

It’s important to debug but these messages are of no interest to me and they are generated at such a high rate, chrome eventually runs out of memory. 

Adding a flag to disable these messages would be ideal for me. I’m unsure what they are used for in the debugger, this has not been explained, but if they are so required that stopping them would kill debugging, could the rate be throttled? There are 1000s of these being thrown into the log and kept. If it’s for the debugger, they seem transient and so there is no point to keeping them. 

Having a process delete them seems another resource hungry process, killing the cpu even more in unrequited garbage collect. 

If it’s transient use, take this out of the logs and add them with a stream to the debugger rather than abusing the log ?

**Comment by chertov** [comment] 2021-05-13 20:31
> What version of Chrome are you using? Does it impact all apps? If not can you provide a sample app. I'm not aware of other reports of Chrome crashing due to these logs.

Please, open https://dartpad.dev/, chrome console, and try code from this comment
https://github.com/flutter/flutter/issues/75225#issuecomment-777115305
you will see something like this
![Screen Recording 2021-05-13 at 11 27 58 PM](https://user-images.githubusercontent.com/436625/118183793-329eab80-b443-11eb-8660-c7e9f6323e70.gif)

Chrome is up to date
<img width="702" alt="Screenshot 2021-05-13 at 10 50 12 PM" src="https://user-images.githubusercontent.com/436625/118179187-a047d900-b43d-11eb-863d-f644c1dc6c17.png">

**Comment by tim-montague** [comment] 2021-05-28 16:44
How can I turn off these "dart.developer.postEvent" messages?

<img width="1231" alt="Screen Shot 2021-05-28 at 9 37 19 AM" src="https://user-images.githubusercontent.com/1149793/120015626-64ae2280-bf98-11eb-9db3-94992e908830.png">

I use a Mac, I installed flutter with brew, I work with Vscode, and I test with Safari.

```
flutter run -d web-server
```

Not even able to see my `print` logs, because the console is flooded with these "dart.developer.postEvent" messages when I click on buttons, inputs, etc.

**Comment by cedvdb** [comment] 2021-06-21 13:26
Could someone give some clarification as to why the debug tools consume messages from the logs and if another channel could be viable ? Just to understand what happens under the hood a bit more clearly

**Comment by nshahan** [comment] 2021-06-21 16:36
> Could someone give some clarification as to why the debug tools consume messages from the logs and if another channel could be viable ? Just to understand what happens under the hood a bit more clearly

I believe this was just a case of a simple implementation that was easy to get up and running but is replaceable if it ever becomes a problem. I've landed a change to migrate away from using the log as a messaging channel in the Dart SDK https://github.com/dart-lang/sdk/commit/c83eeac5b89ada105c6df3be75b54bce97d5de1b. It has been rolled into the flutter engine so a future release should clear these up.

**Closed by nshahan** 2021-06-21 16:36 UTC
Labels: d: devtools, passed first triage, perf: memory, platform-web
