### ISSUE TITLE
[share]: On iPad with iOS 14, the native box for sharing is not displayed

### ISSUE THREAD

**Issue by jjvillavicencio** [flutter/flutter#66984] opened 2020-09-30 15:42 UTC
### Description
When you press the share button on the iPad, you can see that a sale is displayed in the upper left part outside the display range of the screen

![image](https://user-images.githubusercontent.com/4654352/94707924-9edffb00-0309-11eb-92cf-5267e3360f88.png)

**Comment by TahaTesser** [comment] 2020-10-01 08:30
Hi @jjvillavicencio 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by jjvillavicencio** [comment] 2020-10-01 15:08
> `flutter doctor -v` your `flutter run --verbose`

### Code example

```
Future<void> shareLink(String comment, Uri url) async {
    return Share.share('$comment, $url');
  }
```
## flutter doctor -v

```➜  donebusiness-store git:(feature/jjvillavicencio-2020-09-30) ✗ flutter doctor -v                           
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale es-419)
    • Flutter version 1.20.4 at /Users/developer/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

 
[✓] Connected device (1 available)            
    • iPad Pro (9.7-inch) (mobile) • 0E51469D-3B63-4CDC-A6A6-35BBA49FD61E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

## flutter run --verbose

[verbose.txt](https://github.com/flutter/flutter/files/5312988/verbose.txt)

**Comment by TahaTesser** [comment] 2020-10-02 09:11
The issue is reproducible on iPad only, it works on iPhone, reproduces from `stable` to `master`
| iPhone | iPad |
| --------------- | --------------- |
![Simulator Screen Shot - iPhone 11 - 2020-10-02 at 14 12 32](https://user-images.githubusercontent.com/48603081/94906429-15245f00-04bc-11eb-9aa5-da019ee6f605.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-10-02 at 14 10 52](https://user-images.githubusercontent.com/48603081/94906433-16ee2280-04bc-11eb-9fc8-b6960de44078.png)

<details> 
<summary>code sample</summary> 

```dart
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:ui';

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show visibleForTesting;

/// Plugin for summoning a platform share sheet.
class Share {
  /// [MethodChannel] used to communicate with the platform side.
  @visibleForTesting
  static const MethodChannel channel =
      MethodChannel('plugins.flutter.io/share');

  /// Summons the platform's share sheet to share text.
  ///
  /// Wraps the platform's native share dialog. Can share a text and/or a URL.
  /// It uses the `ACTION_SEND` Intent on Android and `UIActivityViewController`
  /// on iOS.
  ///
  /// The optional [subject] parameter can be used to populate a subject if the
  /// user chooses to send an email.
  ///
  /// The optional [sharePositionOrigin] parameter can be used to specify a global
  /// origin rect for the share sheet to popover from on iPads. It has no effect
  /// on non-iPads.
  ///
  /// May throw [PlatformException] or [FormatException]
  /// from [MethodChannel].
  static Future<void> share(
    String text, {
    String subject,
    Rect sharePositionOrigin,
  }) {
    assert(text != null);
    assert(text.isNotEmpty);
    final Map<String, dynamic> params = <String, dynamic>{
      'text': text,
      'subject': subject,
    };

    if (sharePositionOrigin != null) {
      params['originX'] = sharePositionOrigin.left;
      params['originY'] = sharePositionOrigin.top;
      params['originWidth'] = sharePositionOrigin.width;
      params['originHeight'] = sharePositionOrigin.height;
    }

    return channel.invokeMethod<void>('share', params);
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (1 available)            
    • iPad Pro (9.7-inch) (mobile) • 1BC774A9-7D56-4F62-A12F-B73CAEFB3E4F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.105, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.105 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision f1013e6873 (7 hours ago), 2020-10-02 09:50:33 +0800
    • Engine revision 0522ff22cc
    • Dart version 2.11.0 (build 2.11.0-181.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • iPad Pro (9.7-inch) (mobile) • 1BC774A9-7D56-4F62-A12F-B73CAEFB3E4F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)              • macos                                •
      darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)             • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)                 • chrome                               •
      web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-10-07 08:56
duplicate of https://github.com/flutter/flutter/issues/47220

**Closed by TahaTesser** 2020-10-07 08:56 UTC
Labels: e: OS Version specific, found in release: 1.22, found in release: 1.23, has reproducible steps, p: first party, p: share, platform-ios, plugin
