### ISSUE TITLE
FormTextField inserts/repeats all previous characters in the text field on new sentence (i.e after '.') on some keyboards

### ISSUE THREAD

**Issue by joelbrostrom** [flutter/flutter#39570] opened 2019-08-30 14:36 UTC
## Steps to Reproduce

1. Create `Form` with at least one `FormTextField` 
2. Focus on a `FormTextField` (i.e by selecting it)
3. Remove focus from the `FormTextField` (for example by selecting another TextField)
4. Return to the previous `FormTextField`.
5. Write some characters, followed by a dot, followed by one more character.

The character after the dot should be a character that that should be capitalized in a new sentence. This will copy all characters from before prior to the new dot between itself and the new character.

This seams to be keyboard related. 
I cant say how many soft keyboards are effected by it, but Samsungs is and that alone should be a good reason to look into it.

_side note:_ sometimes when playing around the keyboard lose all input capability and the app must be killed.

## Example

```
Some examples on the  format:

<Original>
<After deleting characters>
<After retyping dot and the first character>
```
```
my.email
my                          
my.my.e
```
```
my.email@host.com
my.email@host
my.email@host.my.email@host.c
```
```
my.email@host.com
my.email@host.c //not deleting dot
my.email@host.co //no inserted string
```
```
my.email@host.com
my.email@host. //removing characters excluding dot
my.email@host.my.email@host.c //inserts string
```
```
my.email@host.@com
my.email@host.
my.email@host.@ //no inserted string
```
```
//Adding one character at a time from empty string:
<Empty String>
a
a.a.b
a.a.b.a.a.b.c
a.a.b.a.a.b.c.a.a.b.a.a.b.c
a.a.b.a.a.b.c.a.a.b.a.a.b.c.a.a.b.a.a.b.c.a.a.b.a.a.b.c.d
```

## Observations

Does not effect iOS
Does not effect Android phones with G-board
Does effect samsung keyboard

Triggers on **auto**-capitalized character
Inserts textfield content before new character

## Code

Runnable project to reproduce the reported behavior.
<details><summary><b><font color="#ff0000">Show Code</font></b></summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Playground()));

class Playground extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => FormTextExampleState();
}

class FormTextExampleState extends State<Playground> {
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController(text: 'my.email@host.com');
  final _passwordController = TextEditingController(text: 'password');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(
        builder: (context) {
          return Center(
            child: Form(
              key: _formKey,
              child: Padding(
                padding: EdgeInsets.only(left: 64, right: 64),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    TextFormField(
                      controller: _emailController,
                      keyboardType: TextInputType.text,
                    ),
                    TextFormField(
                        controller: _passwordController, keyboardType: TextInputType.text),
                    Padding(
                      padding: EdgeInsets.only(top: 16),
                      child: RaisedButton(
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                        color: Colors.red[700],
                        onPressed: () {
                          showSnackBarMessage(context);
                        },
                        child: Text(
                          'Login',
                          style: TextStyle(color: Colors.white),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  void showSnackBarMessage(BuildContext context) {
    Scaffold.of(context).showSnackBar(
      SnackBar(
        content: Text(
          'Button click registered',
          textAlign: TextAlign.center,
        ),
      ),
    );
  }
}
```
</details>

## Logs

Log from event
```
I: checkScoreBasedQuality -  mPreviousScore[0]:67 mPreviousScore[1]:67 mPreviousScore[2]:66 s2Score:67mPrevoiusScoreAverage:66
D: Input event(1): value=1 when=362256.621938
D: Input event(1): value=1 when=362256.621938
I: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.4348 ] when=362256.621938
I: Delivering touch to (12333): action: 0x4, displayId: 0, '4afb65 ', toolType: 1
I: Delivering touch to (12333): action: 0x4, displayId: 0, 'ece29d1', toolType: 1
I: Add pinfo end.  0
I: Delivering touch to (13958): action: 0x0, displayId: 0, '444ae66', toolType: 1
D: ViewPostIme pointer 0
I: bwq [PF_KL][getKeyIndexAndNearbyCodes] 165461, In Tyme, getSimpleKeyIndexAndNearbyCodes
I: ayr request vibrate()
I: AbstractKeyboardView [PF_KL] onTouchEvent  0 5 2 2489269
V: vibrate - package: com.sec.android.inputmethod, token: android.os.BinderProxy@5d2bd41, usage: 13, effect: SemHaptic{mType=50025, mRepeat=-1, mMagnitude=-1, mMagnitudeType=TYPE_TOUCH}, mag: 4000, TYPE_TOUCH
V: vibratePatternMagnitude - package: com.sec.android.inputmethod, repeat: -1, token: android.os.BinderProxy@5d2bd41, mag: 4000, TYPE_TOUCH
D: Turning vibrator off
D: writeNode node:/sys/class/timed_output/vibrator/enable val:0
I: ayr vibrate() : 7
D: vibratorOn() : 7ms, mag :4000, f : 4
D: writeNode node:/sys/class/timed_output/vibrator/multi_freq val:4
D: writeNode node:/sys/class/timed_output/vibrator/intensity val:4000
D: writeNode node:/sys/class/timed_output/vibrator/enable val:7
D: Input event(1): value=0 when=362256.671648
D: Input event(1): value=0 when=362256.671648
I: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=362256.671648
I: Add pinfo.  (channel) 444ae66 InputMethod (server) (pkg) AppWindowToken{d15a55b token=Token{d8f6c6a ActivityRecord{myAppActivity}}} 13958 10168 (action) 1
I: Add pinfo end.  1
I: Delivering touch to (13958): action: 0x1, displayId: 0, '444ae66', toolType: 1
D: ViewPostIme pointer 1
I: [ATIM] [ppfockfsk] IMI,25,IR,0
I: cmw [PF_KL][SIIC] getTextBeforeCursor[ 2 ] done  3
I: cmw [PF_KL][SIIC] getTextBeforeCursor[ 127 ] done  2
I: cmw [PF_KL][SIIC] getTextAfterCursor[ 127 ] done  2
I: TymeCore mPdL: BuildTime = 0.0315s
I: [IIManager] [PF_KL] IIfo BuildTime - tookTime : 32
I: cmw [PF_KL][SIIC] getExtractedText done  2
I: [IIManager] IIfo SI [il:0x656e4742] [p:1] [c:0] [t:0] [im:0/0/0/0/0/0] [sC:0] [aC:1] [sS:0] [aS:1] [aP:0] [pW:0] [eM:1] [uR:0] [acI:0] [iT:21] [iO:2000005] [pID:26347] [pO:null]
I: [IIManager] IIfo II [ir:0] [rand:c2690f78e7fa4053a66186b0020cf51a] [hC:0] [hI:0] [tr:0] [tc:0] [long:0] [cpl:15] [xyD:0/0] [xycD:33/96] [kWHG:88/133/17] [tD:50] [tP:44] [fil:true] [IC:5/10] [cB:1/32]
E: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I: cmw [SIIC] setComposingText :  true ,  1
I: [ATIM] [PF_KL][onCharacterKey]  43
I: arx [PF_KL][onKeyHandleNormalKey::onCharacterKey] 43103308
I: amf [PF_KL][onKey] 43206846
I: AbstractKeyboardView [PF_KL] onTouchEvent  1 3 44 44556692
I: [ATIM] [updateSelectionForInputModule] oldSelStart : 14, oldSelEnd : 14, newSelStart : 29, newSelEnd : 29, candidatesStart : 14, candidatesEnd : 29, viewClicked : false
I: [ATIM] [updateSelectionForInputModule] isTyping : true, viewClicked : false, isKBDShown : true
I: TymeCore mPdL: BuildTime = 0.0376s
I: [IIManager] [PF_KL] IIfo BuildTime - tookTime : 38
I: bbh setToolbarVisibility, isVisible = false
I: CandidateTextView boldText : false
I: CandidateTextView useSuperDraw : true
I: CandidateTextView boldText : false
I: CandidateTextView useSuperDraw : true
```

Flutter analyze
```
Analyzing brl-birthday-flutter...                                       
No issues found! (ran in 6.4s)
```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-SE)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by red282** [comment] 2019-12-02 05:14
Maybe it's related to one of these issues. https://github.com/flutter/flutter/issues/42273

**Comment by GaryQian** [comment] 2020-02-20 19:36
Duplicate of https://github.com/flutter/flutter/issues/31512. Closing this! Please continue to track it over in the other thread!

**Closed by GaryQian** 2020-02-20 19:36 UTC
Labels: a: text input, e: device-specific, f: material design, framework, ▣ platform-android

**Comment by Faiyyaz** [comment] 2021-03-26 15:05
I am facing the same issue on my lg q6 with suggestions enabled. If i disable the suggestions on textfield then everything works fine.
