### ISSUE TITLE
[url_launcher]  Opening the Messenger app for the first time.

### ISSUE THREAD

**Issue by VanToan08** [flutter/flutter#139417] opened 2023-12-02 05:29 UTC
Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We have to wait over 5 second to open messenger app for the first time after we have clicked  icon.
https://drive.google.com/file/d/1fofXXn4NAZhS-wmyr6S4tQJ8--exZNRV/view?usp=sharing

### Expected results

I want to open messenger app instantly for the first time after we clicked icon.

### Actual results

I want to open messenger app instantly for the first time after we clicked icon.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() async {
    await launchUrl(Uri.parse("https://m.me/appcheap.io"), mode: LaunchMode.platformDefault);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body:const Center(
        child: Text('a'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://drive.google.com/file/d/1fofXXn4NAZhS-wmyr6S4tQJ8--exZNRV/view?usp=sharing)
s
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.13.9, on macOS 13.6.1 22G313 darwin-x64, locale en-VN)
    ! Flutter version 3.13.9 on channel [user-branch] at /Users/nguyenvantoan/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```
</details>

**Comment by opxdelwin** [comment] 2023-12-02 05:45
Can you confirm if you build the apk using `--release` flag, i.e `flutter build apk --release`?

**Comment by VanToan08** [comment] 2023-12-02 06:36
> Can you confirm if you build the apk using `--release` flag, i.e `flutter build apk --release`?

I did a release build but the problem still occurs.

i tested with Samsung s23 ultra and Iphone 11 pro max.
The bug happens in both

Thank you.

**Comment by opxdelwin** [comment] 2023-12-03 07:21
If that's the case, this looks like an issue with how Messenger app handles external requests, and not with how flutter sends these requests. 

Let this be open for a while for others to share their thoughts.

**Comment by VanToan08** [comment] 2023-12-05 02:22
> Hi @VanToan08 This could depend on Messenger app. In case Messenger app is not loaded yet. When you open it from Flutter app, it triggers a cold start on Messenger app, it will be longer than hot start if the app has already opened.
> 
> You can try checking this with a simple Android native app to see if the issue persists or not. Also, let's try open other apps as well (not Messenger app)

Hi [huycozy](https://github.com/huycozy)

**I did the checks as you said**. And other applications such as **phone, sms, email work stably**. And I also tested it on a **real iPhone 11pro "ios16.3" device** and it also works stably, but my **customer checked and reported to me** that the problem was on the **11Pro Max** device as well. And I realize this will happen on most Android devices in **all Android versions**.

I think the possibility of the **problem** lies in the **messenger app**

**Thank you** for your comments on my article

**Comment by huycozy** [comment] 2023-12-05 07:54
Thanks for the update. This is quite vague because it depends on the device status at that time (memory, CPU usage...). It would be useful if you could replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and write a comment when you have clear steps to reproduce.

**Closed** 2023-12-26 08:09 UTC
Labels: waiting for customer response, in triage
