### ISSUE TITLE
Got error when changing channel - Crash when compiling file://home/pramit/Documents/development/flutter/packages/flutter_tools/bin/flutter_tools.dart,

### ISSUE THREAD

**Issue by pramitsawant** [flutter/flutter#67638] opened 2020-10-08 14:38 UTC
I'm getting the following error.

Step 1:
`flutter channel master
`
Step 2:
`flutter upgrade`
```
Building flutter tool...
Crash when compiling file://home/pramit/Documents/development/flutter/packages/flutter_tools/bin/flutter_tools.dart,
at character offset null:
Invalid argument(s): Exception when reading 'file://home/pramit/Documents/development/flutter/packages/flutter_tools/.dart_tool/package_config.json': Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:554:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:568:32)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:633:17)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:501:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:455:38)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#9      CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#24     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:554:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:568:32)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:633:17)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:501:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:455:38)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#9      CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#24     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by mkustermann** [comment] 2020-10-08 14:41
Is this the same issue as https://github.com/flutter/flutter/issues/63579 ?

**Comment by TahaTesser** [comment] 2020-10-09 14:04
Labelling the issue for tracking this critical upgrade tool bug, related to https://github.com/flutter/flutter/issues/63579

**Comment by christopherfujino** [comment] 2020-10-21 21:17
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/63579. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2020-10-21 21:17 UTC
Labels: passed first triage, severe: crash, tool
