### ISSUE TITLE
Trouble with using path_provider  package in an isolate 

### ISSUE THREAD

**Issue by Drkstr** [flutter/flutter#51685] opened 2020-02-29 05:16 UTC
### Issue description: 
I am using the [flutter_isolate](https://pub.dev/packages/flutter_isolate) package to spawn an isolate. When I try to call getApplicationDocumentsDirectory() in the isolate I get the following error. 

> Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### flutter doctor -v 

> [✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-AU)
>     • Flutter version 1.14.6 at /Users/drkstr/development/flutter
>     • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
>     • Engine revision c4229bfbba
>     • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> 
>     • Android SDK at /Users/drkstr/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/drkstr/Android/Sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> 
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C504
>     • CocoaPods version 1.8.4
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.5)
> 
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 43.0.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [!] VS Code (version 1.42.1)
> 
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
>  [✓] Connected device (3 available)
> 
>     • Pixel XL   • HT74T0205374 • android-arm64  • Android 10 (API 29)
>     • Chrome     • chrome       • web-javascript • Google Chrome 80.0.3987.122
>     • Web Server • web-server   • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 1 category.
> 

pubspec.yaml file 

> name: tablet_tests
> description: Application to test tablet functionality 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.1.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^0.1.3
>   usb_serial: 0.2.3
>   flutter_isolate: 1.0.0+11
>   provider: 4.0.1
>   flutter_secure_storage: 3.3.1+1
>   sqflite: 1.2.0
>   path_provider: 1.6.1
>   path: 1.6.4
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
> flutter:
>   uses-material-design: true
> 

### stacktrace

> E/flutter (11692): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
> E/flutter (11692): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> E/flutter (11692): <asynchronous suspension>
> E/flutter (11692): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> E/flutter (11692): #2      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:92:22)
> E/flutter (11692): #3      DatabaseSingleton.initDB (package:tablet_tests/singletons/DatabaseSingleton.dart:31:42)
> E/flutter (11692): #4      DatabaseSingleton.database (package:tablet_tests/singletons/DatabaseSingleton.dart:25:36)
> E/flutter (11692): #5      DatabaseSingleton.insertLog (package:tablet_tests/singletons/DatabaseSingleton.dart:40:22)
> E/flutter (11692): #6      backgroundTask (package:tablet_tests/background_processes/BackgroundStuff.dart:11:8)
> E/flutter (11692): #7      isolate1 (package:tablet_tests/main.dart:10:3)
> E/flutter (11692): #8      FlutterIsolate._isolateInitialize.<anonymous closure>.<anonymous closure> (package:flutter_isolate/flutter_isolate.dart:128:23)
> E/flutter (11692): #9      _rootRunUnary (dart:async/zone.dart:1138:13)
> E/flutter (11692): #10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
> E/flutter (11692): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
> E/flutter (11692): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> E/flutter (11692): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
> E/flutter (11692): #14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
> E/flutter (11692): #15     _StreamController._add (dart:async/stream_controller.dart:649:7)
> E/flutter (11692): #16     _StreamController.add (dart:async/stream_controller.dart:595:5)
> E/flutter (11692): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

The output of flutter run --verbose: </br>https://drive.google.com/open?id=1heTLOyNBqSR13jv8MzLOj6sb2whjEQcK01KbRnxHzz4 

Minimal app to reproduce the error: </br> https://drive.google.com/open?id=1eWJguDVGzyeuzvhReQVHb1i8uIEmSX6A 

To reproduce the error download and run the minimal app I have linked above. 

Let me know if you would like any more info.

**Comment by VladyslavBondarenko** [comment] 2020-03-17 14:37
Related to https://github.com/flutter/flutter/issues/46679

**Comment by tiagoantunes** [comment] 2020-06-26 00:14
A possible related issue, #59683 (comment).

**Comment by oligazar** [comment] 2021-01-29 04:58
Same problem here. `Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)` when running getApplicationDocumentsDirectory() in isolate.

**Comment by oligazar** [comment] 2021-01-29 13:29
> Same problem here. `Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)` when running getApplicationDocumentsDirectory() in isolate.
> 
> Is there any solution or clue how to handle that?

I manage to work around this issue registering plugins manually in Application.kt
```
class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }
    
    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.pathprovider")) {
            PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.pathprovider"))
        }
    }
}
```

**Comment by One-djey** [comment] 2021-12-02 21:30
The @oligazar workaround isn't suitable for me and I'm still experiencing the error:
```
Null check operator used on a null value
I/flutter (11969): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
I/flutter (11969): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
I/flutter (11969): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
I/flutter (11969): #3      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
I/flutter (11969): #4      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:138:40)
```
When I call `Directory appDocDir = await getApplicationDocumentsDirectory();` from package `package:path_provider/path_provider.dart` in an Isolate.

**Comment by krunalgajera98** [comment] 2022-02-07 12:14
Hi, @Drkstr same Issue here, can you please tell me how you solve this error, any help would be appreciated
thanks!

**Comment by Drkstr** [comment] 2022-02-23 03:32
@krunalgajera98 I never found a workaround for this. I ended up rearchitecting the app to not need isolates.

**Comment by brunodmn** [comment] 2022-03-04 18:20
Similar here, when trying to use use it with [workmanager](https://pub.dev/packages/workmanager) on iOS.
In my mainframe I can inject and use the path_provider, but when I trigger it from workmanager it wont work at all. Already tried `flutter clean/get`, `flutter pub cache repair`, close and reopen emulator and IDE..nothing works.

If you need reproducible steps let me know. 

Someone knows how can I manually initialize the plugin on my AppDelegate as a workaround?

**Comment by Kashishm273** [comment] 2022-04-07 00:08
Facing the same issue, any solution to make it work on iOS?

**Comment by One-djey** [comment] 2022-04-07 06:54
I was stuck with this problem on Android. I haven't found any solution or workaround. Isolate does not work as the main thread since they cannot use MethodChannels (so far it's what I understood).
My non-productive answer would be: do it in another way.

**Comment by Kashishm273** [comment] 2022-04-07 07:13
I ended up using 

```
import 'dart:io';

// Get the system temp directory.
var systemTempDir = Directory.systemTemp;
```

Works fine on different isolate as well. The data that I need to store, is required temporarily and can be exposed publicly.

**Comment by brunodmn** [comment] 2022-04-13 12:30
> I ended up using
> 
> ```
> import 'dart:io';
> 
> // Get the system temp directory.
> var systemTempDir = Directory.systemTemp;
> ```
> 
> Works fine on different isolate as well. The data that I need to store, is required temporarily and can be exposed publicly.

Nice workaround for some situations. Unfortunately, won't work if you run a package that uses 
`getApplicationDocumentsDirectory()` to initialize on isolate, such as hive or shared_preferences.

What worked for me on Android, but I not tested on iOS yet was related to  [#360](https://github.com/fluttercommunity/flutter_workmanager/issues/360#issuecomment-1043171712). :
 1. Add packages **path_provider_android** and **path_provider_ios**
 2. Add bellow snipet into your isolate (before `getApplicationDocumentsDirectory()`):
```
 if (Platform.isAndroid) PathProviderAndroid.registerWith();
 if (Platform.isIOS) PathProviderIOS.registerWith();
```

Could you give it a try and feedback the results?

**Comment by stuartmorgan** [comment] 2022-04-14 18:03
Closing as the original issue was about a third-party package; when using isolates special handling is required to register plugins, and that's up to the package configuring the isolate to do correctly (or explain how to clients to do correctly if they don't).

The more recent comments are likely to be https://github.com/flutter/flutter/issues/99155 instead; see there for details.

**Closed by stuartmorgan** 2022-04-14 18:03 UTC
Labels: severe: crash, plugin, p: first party, p: path_provider, p: third party, P5
