### ISSUE TITLE
error is not reported when more than one forward slash is used in an import statement

### ISSUE THREAD

**Issue by davidnwaneri** [flutter/flutter#125134] opened 2023-04-19 14:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In any Flutter project just add a double forward slash in any import statement

So if you have
`import 'package:forward_slash_issue/bloc//sample_bloc.dart';`

it does not report any error

but if the double forward slash was exactly after the package name, it reports the error:
`import 'package:forward_slash_issue//bloc/sample_bloc.dart';`

### Expected results

The usual error (Target of URI doesn't exist...) should be reported when more than one forward slash is detected

### Actual results

The error is not reported, resulting in possible runtime errors to code that uses that import

### Code sample

<details><summary>Code sample</summary>
This code sample is not exactly relevant to this issue. The **Steps to reproduce** should be sufficient. The whole purpose of this code sample is to show how this can lead to a runtime error, and hopefully, for this to be given some attention

In the `main.dart` file

```dart
import 'package:flutter/material.dart';
import 'package:forward_slash_issue/bloc/sample_bloc.dart';
import 'package:forward_slash_issue/view/home.dart';

void main() {
  runApp(
    BlocProvider<SampleBloc>(
      create: (context) => SampleBloc(),
      child: const MyApp(),
    ),
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
       // The [MyHomePage] widget from the default template has been moved to another file
      // import 'package:forward_slash_issue/view/home.dart';
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
MyHomePage in `lib/view/home.dart`
```dart
import 'package:flutter/material.dart';
// Pay attention to the double forward slash in this import.
// The location of the double forward slash is important.
// If it was: import 'package:forward_slash_issue//bloc/sample_bloc.dart';
// an error would be reported, since it is immediately after the package name.
// It appears the only time the error is reported in regards to this issue, is when the double forward slash
// is immediately after the package name.
// This issue also applies of it was three forward slash.
import 'package:forward_slash_issue/bloc//sample_bloc.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
// Trying to read this bloc will throw a runtime error  of:
// ```
// Error: Could not find the correct Provider<SampleBloc> above this MyHomePage Widget

// This happens because you used a `BuildContext` that does not include the provider
// of your choice. There are a few common scenarios:
//```
// because of the import statement.
    final state = context.read<SampleBloc>().state;
    print('State: $state');
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
SAMPLE BLOC in `lib/bloc/sample_bloc.dart';`
```dart
import 'package:flutter_bloc/flutter_bloc.dart';

class SampleBloc extends Bloc<SampleEvent, bool> {
  SampleBloc() : super(false) {
    on<SampleEvent>((event, emit) {
    });
  }
}

class SampleEvent {}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by abitofevrything** [comment] 2023-04-19 14:13
We did some investigation separately on the r/flutterdev Discord server prior to this issue being created and we think to have found the cause:

This code (https://github.com/dart-lang/package_config/blob/master/lib/src/package_config_impl.dart#L154): 
```dart
  @override
  Uri? resolve(Uri packageUri) {
    var packageName = checkValidPackageUri(packageUri, 'packageUri');
    return _packages[packageName]?.packageUriRoot.resolveUri(
        Uri(path: packageUri.path.substring(packageName.length + 1)));
  }
```

Will resolve to an absolute URL if `packageUri.path.substring(packageName.length + 1)` happens to start with a forward slash (which it does if the package name is followed by two slashes in the import URI).

This means that the "path" is relative to the root of the device's filesystem instead of relative to the package's root, which obviously causes the file to not be found.

**Comment by abitofevrything** [comment] 2023-04-19 14:14
This should probably be transferred to dart-lang/sdk or dart-lang/package_config

**Comment by abitofevrything** [comment] 2023-04-19 14:23
Additionally, the issue of context.read not being able to find `SampleBloc` is because the frontend sees `package:forward_slash_issue/bloc/sample_bloc.dart` and `package:forward_slash_issue/bloc//sample_bloc.dart` as two different files, both declaring a class named `SampleBloc`.

As @julemand101 pointed out, this is a common issue (as this also applies to paths with different casing in Windows), so maybe this part of the issue can be ignored.

**Comment by stuartmorgan** [comment] 2023-04-19 21:21
This is a duplicate of https://github.com/dart-lang/sdk/issues/42829

**Closed by stuartmorgan** 2023-04-19 21:21 UTC
