### ISSUE TITLE
ToStringDeep() isn't defined for the class 'PlatformException' with last update

### ISSUE THREAD

**Issue by AlpenYeti** [flutter/flutter#30381] opened 2019-04-02 13:25 UTC
## Steps to Reproduce

Error thrown on Gradle task 'assembleDebug' when run using Android Studio play button.

## Logs

```
Launching lib/main.dart on E5823 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'PlatformException'.
 - 'PlatformException' is from 'package:flutter/src/services/message_codec.dart' ('file:///home/alpenyeti/development/flutter/packages/flutter/lib/src/services/message_codec.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'PlatformException'.
 - 'PlatformException' is from 'package:flutter/src/services/message_codec.dart' ('file:///home/alpenyeti/development/flutter/packages/flutter/lib/src/services/message_codec.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'PlatformException'.
 - 'PlatformException' is from 'package:flutter/src/services/message_codec.dart' ('file:///home/alpenyeti/development/flutter/packages/flutter/lib/src/services/message_codec.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'PlatformException'.
 - 'PlatformException' is from 'package:flutter/src/services/message_codec.dart' ('file:///home/alpenyeti/development/flutter/packages/flutter/lib/src/services/message_codec.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'SqfliteDatabaseException'.
 - 'SqfliteDatabaseException' is from 'package:sqflite/src/exception.dart' ('file:///home/alpenyeti/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.0/lib/src/exception.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'SqfliteDatabaseException'.
 - 'SqfliteDatabaseException' is from 'package:sqflite/src/exception.dart' ('file:///home/alpenyeti/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.0/lib/src/exception.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'SqfliteDatabaseException'.
 - 'SqfliteDatabaseException' is from 'package:sqflite/src/exception.dart' ('file:///home/alpenyeti/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.0/lib/src/exception.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'SqfliteDatabaseException'.
 - 'SqfliteDatabaseException' is from 'package:sqflite/src/exception.dart' ('file:///home/alpenyeti/development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.0/lib/src/exception.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
toStringDeep()
^^^^^^^^^^^^
Compiler failed on /home/alpenyeti/git/flutterapppoc/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1
```

```
flutter analyze
Analyzing flutterapppoc...                                              
No issues found! (ran in 1.9s)
```

```
flutter doctor-v
[✓] Flutter (Channel beta, v1.3.8, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.3.8 at /home/alpenyeti/development/flutter
    • Framework revision e5b1ed7a7f (il y a 4 semaines), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/alpenyeti/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.24.0
```

**Comment by FleurA** [comment] 2019-04-02 14:31
i get the same errors!

**Comment by AlpenYeti** [comment] 2019-04-02 15:05
> i get the same errors!

It only happens with Android Studio's interface. you can still run it with `flutter run`. Not the best option but at least it doesn't stop you from working.

**Comment by laharshah** [comment] 2019-04-02 23:14
run the following command: 

`flutter clean`

Works for me.

**Comment by mbikt** [comment] 2019-04-03 01:33
It also happen to me, but with different class specifically from RxDart. After rxdart package upgrade to 21, no problem.

**Comment by antekone** [comment] 2019-04-05 04:33
Remove the `build` directory or run `flutter clean`.

**Comment by jaumard** [comment] 2019-04-05 09:00
look like a duplicate of #30267 who has more upvote

**Comment by jason-simmons** [comment] 2019-04-11 19:48
See https://github.com/dart-lang/sdk/issues/36091

Does this still happen on the Flutter master channel?

**Comment by ride4sun** [comment] 2019-04-19 20:15
I just updated and see of these statements in the console window - super anything besides all the other instability I am seeing.(Android Studio crashing, freezing, flickering, andoidx) I also getting really annoyed because I can not concentrate on my problems and I don't know anymore what is real and what is flutter and what is the Android toolchain. The standard answer is to delete the breakpoint and run flutter clean. That is not a solution - that is a poor man's workaround without fixing the root cause. - sorry for the rant.

Can flutter not detect when a new upgrade was done and run clean on the project automatically?

I am on :
C:\Projects\obdchk>flutter doctor -v
[√] Flutter (Channel master, v1.5.3-pre.33, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.5.3-pre.33 at c:\sdks\flutter
    • Framework revision eaf058d81d (4 hours ago), 2019-04-19 08:50:30 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[√] VS Code, 32-bit edition (version 1.30.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

**Comment by escamoteur** [comment] 2019-09-25 10:52
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment] 2019-11-07 14:21
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-07 14:21 UTC
Labels: waiting for customer response
