### ISSUE TITLE
Same here whenever i click on any of the textField in the app am getting this

### ISSUE THREAD

**Issue by zingsai** [flutter/flutter#90496] opened 2021-09-22 05:15 UTC
Same here whenever i click on any of the textField in the app am getting this

W/IInputConnectionWrapper(20969): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(20969): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(20969): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(20969): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(20969): endBatchEdit on inactive InputConnection

_Originally posted by @Lawati97 in https://github.com/flutter/flutter/issues/9471#issuecomment-907760476_

**Comment by danagbemava-nc** [comment] 2021-09-22 07:59
Hi @zingsai, since #9471 is already open and active, I would advise you post under there.

Closing as duplicate of #9471.

Thank you

**Closed by danagbemava-nc** 2021-09-22 07:59 UTC
Labels: in triage
