### ISSUE TITLE
Hiding floatingActionButton on new page also hides it on the previous page

### ISSUE THREAD

**Issue by LampeMW** [flutter/flutter#40708] opened 2019-09-17 20:59 UTC
## Steps to Reproduce

I am running into an issue where we have a floating action button on two consecutive screens.  There is a floating action button on the first screen, and when pressed takes you to a new screen with a different floating action button. After some action is done on this second screen, we hide the floating action button.  Now, when popping to the previous screen, its floating action button is also hidden which seems like an unintended bug.

First Screen
```
import 'package:flutter/material.dart';
import 'SecondScreen.dart';

class FirstScreen extends StatefulWidget {
  FirstScreen();
 
  @override
  State<StatefulWidget> createState() {
    return new FirstScreenState();
  }
}

class FirstScreenState extends State<FirstScreen>{

  loadSecondScreen() {
    SecondScreen secondScreen = new SecondScreen();
    Navigator.of(context).push(new MaterialPageRoute(builder: (context) => secondScreen));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      floatingActionButton: new FloatingActionButton(
        onPressed: () {loadSecondScreen();},
        tooltip: "Submit",
        child: new Icon(Icons.add),
      ),
      appBar: new AppBar(
        title: new Text("First Screen"),
        elevation: 0.0,
        centerTitle: true,
      ),
      body: new Container(),
    );
  }
}
```

Second Screen
```
import 'package:flutter/material.dart';

class SecondScreen extends StatefulWidget {
  SecondScreen();
 

  @override
  State<StatefulWidget> createState() {
    return new SecondScreenState();
  }
}

class SecondScreenState extends State<SecondScreen>{
  bool shouldShowFloatingActionButton = true;

  hideFloatingActionButton() {
    setState(() {
      shouldShowFloatingActionButton = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      floatingActionButton: shouldShowFloatingActionButton ? new FloatingActionButton(
        onPressed: () {},
        tooltip: "Submit",
        child: new Icon(Icons.add),
      ) : null,
      appBar: new AppBar(
        title: new Text("First Screen"),
        elevation: 0.0,
        centerTitle: true,
      ),
      body: new Container(
        child: new Center(
          child: new RaisedButton(
            child: Text('Tap to hide floating action button'),
            onPressed: () {
              hideFloatingActionButton();
            },
          ),
        ),
      ),
    );
  }
}
```

```
❯ flutter analyze

   info • Dead code • lib/Controller/DashboardController.dart:151:5 • dead_code
   info • Unused import: 'dart:math' • lib/Controller/WorkOrderCreatorController.dart:2:8 • unused_import
   info • The value of the field '_employeeText' isn't used • lib/Controller/WorkOrderCreatorController.dart:1642:10 • unused_field
   info • The value of the local variable 'jsonResponse' isn't used • lib/calls.dart:3494:7 • unused_local_variable

4 issues found. (ran in 7.2s)
```

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.9.6, on Mac OS X 10.14.6 18G95, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-18 11:33
I just tried it but could not reproduce it. I used master V1.10.3-pre.39.
Could you try if it also happens if you switch to the latest master?

**Comment by LampeMW** [comment] 2019-09-18 14:54
Switching to the newest master commit worked for me.  Thanks!

**Comment by escamoteur** [comment] 2019-09-18 15:11
Could you please check if it also works on the latest stable?

**Comment by LampeMW** [comment] 2019-09-18 15:33
I just tried it on the stable branch and the issue occurs there as well.

**Comment by escamoteur** [comment] 2019-09-18 16:17
Thanks

**Comment by escamoteur** [comment] 2019-09-18 16:17
@HansMuller do we have a label for problems that are fixed in coming versions?

**Comment by TahaTesser** [comment] 2020-04-30 13:45
Hi @LampeMW 
Switching to latest master, solved the issue for you [comment reference](https://github.com/flutter/flutter/issues/40708#issuecomment-532722339)

if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you

**Closed by TahaTesser** 2020-04-30 13:45 UTC
Labels: f: material design, framework
