### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by rohit19img** [flutter/flutter#157076] opened 2024-10-17 04:14 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.24.3 on channel stable at /Users/img/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/img/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.14.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m IMG’s iPhone 11 old (mobile)    • 00008030-000208463A78802E • ios            • iOS
      17.6.1 21G93
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS
      15.0.1 24A348 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS
      15.0.1 24A348 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript •
      Google Chrome 129.0.6668.101
    [33m![39m Error: Browsing on the local area network for IMG’s iPhone 11 new. Ensure the device
      is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 41456452f29d64e8deb623a3c927524bcf9f111b
### Plugins
camera-0.10.6
camera_android-0.10.9+14
camera_avfoundation-0.9.17+4
camera_web-0.3.5
cloud_firestore-4.17.5
cloud_firestore_web-3.12.5
device_info_plus-9.1.2
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_core-2.32.0
firebase_core_web-2.18.1
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_local_notifications-17.2.3
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.23
fluttertoast-8.2.8
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
geolocator-11.1.0
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-3.0.0
geolocator_windows-0.2.3
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.10
google_maps_flutter_ios-2.13.1
google_maps_flutter_web-0.5.10
image_picker-1.1.2
image_picker_android-0.8.12+16
image_picker_for_web-3.0.5
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-4.2.0
path_provider-2.1.4
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
razorpay_flutter-1.3.7
share-2.0.4
shared_preferences-2.3.2
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.0
sqflite_android-2.4.0
sqflite_darwin-2.4.1-1
url_launcher-6.3.1
url_launcher_android-6.3.12
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.10.0
webview_flutter_android-4.0.0
webview_flutter_wkwebview-3.16.0

**Comment by danagbemava-nc** [comment] 2024-10-17 07:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-10-17 07:14 UTC
Labels: in triage
