### ISSUE TITLE
Clicking right arrow key on selection isn't removed and cursor is missing, 

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#58068] opened 2020-05-27 04:52 UTC
## Steps to Reproduce

1. Create a Flutter application using a `TextField`.
2. Run your application.
3. Enter the text "01234" in the the field using the keyboard.
4. Select using the mouse "12".
5. Press the right arrow key.

**Expected results:**

Selection is removed, cursor is placed between "2" and "3".

**Actual results:**

Selection is removed, cursor is placed between "3" and "4" (off by one error?).

Note that the left cursor works correctly, and moves to the start of the selection. Tested on Linux.

**Comment by markusaksli-nc** [comment] 2020-07-17 15:29
Hi @robert-ancell 
I can't reproduce this on Windows. Can you confirm that the issue persists and provide `flutter doctor -v` logs?
Thank you

**Comment by stuartmorgan** [comment] 2020-07-19 01:45
> I can't reproduce this on Windows.

Some key handling is done at the embedding level, and thus differs between Windows and Linux.

**Comment by TahaTesser** [comment] 2020-07-23 12:24
When testing on latest, selection isn't removed when left arrow or right now  and cursor is missing

![Screenshot from 2020-07-23 17-52-13](https://user-images.githubusercontent.com/48603081/88285862-733f0400-cd0d-11ea-9edd-4d733d139e2a.png)


<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.114, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.114 at /home/taha/Code/flutter_master
    • Framework revision ddb8e6e3bf (9 hours ago), 2020-07-22 20:00:07 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at //home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = //home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.

```

</details>

**Comment by YeungKC** [comment] 2020-10-17 09:08
Can I have it assigned?

@gspencergoog

**Comment by YeungKC** [comment] 2020-10-17 10:47
This is a issue with the leftArrow and rightArrow error behavior after selecting text, not just on Linux, please remove the Linux label.

**Comment by justinmc** [comment] 2020-10-20 15:47
Should be fixed with https://github.com/flutter/flutter/pull/68402

**Closed by justinmc** 2020-10-20 15:47 UTC
Labels: P3, a: desktop, a: text input, f: material design, found in release: 1.22, framework, has reproducible steps
