### ISSUE TITLE
Cupertino text field - warning to delete a string

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#137290] opened 2023-10-25 20:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Test environment: Pixel 6 + Android 14
2. Go to any app that includes text field widget provided in the code section (similar to https://gallery.flutter.dev/#/demo/text-field )
3. Go to the cupertino text field
4. Select the first input field
5. Change the keyboard language
6. Type a text
7. Try to delete the text by selecting the cross on the right side (try 2 o 3 times until it deletes the string)
8. The following warning is logged:

```
W/RemoteInputConnectionImpl(18845): getSurroundingText on inactive InputConnection
```

### Expected results

None warning should be displayed after deleting a string in this way

### Actual results

The following warning is logged after deleting a string by selecting the "cross" symbol in cupertino text field

### Code sample

<details><summary>Code sample</summary>

This is the widget I’m using in Flutter:
```
class MaterialTextFieldView extends StatelessWidget {
  const MaterialTextFieldView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Text fields'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.symmetric(
          horizontal: 24,
          vertical: 16,
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                labelText: 'Left to right',
              ),
            ),
            SizedBox(height: 48),
            TextField(
              decoration: InputDecoration(
                labelText: 'Right to left',
              ),
              textDirection: TextDirection.rtl,
            ),
            SizedBox(height: 48),
            TextField(
              maxLines: 2,
              decoration: InputDecoration(labelText: 'Max lines (2)'),
              textDirection: TextDirection.ltr,
            ),
            SizedBox(height: 48),
            PasswordTextField(),
            SizedBox(height: 48),
            PhoneNumberTextField(),
            SizedBox(height: 48),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20231025-171844](https://github.com/flutter/flutter/assets/11681325/88eb7d96-c698-42c2-bcba-5b54e386830b)
<img width="1369" alt="Screenshot 2023-10-25 at 5 29 21 PM" src="https://github.com/flutter/flutter/assets/11681325/f24b0f17-2b09-4bdf-81d7-c8b291784b0a">

</details>

### Logs

<details><summary>Logs</summary>

```console
W/RemoteInputConnectionImpl(18845): getSurroundingText on inactive InputConnection
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-15.0.pre.52, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.16.0-15.0.pre.52 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5ceb7284bc (2 days ago), 2023-10-23 14:28:36 -0400
    • Engine revision eaed54aa67
    • Dart version 3.3.0 (build 3.3.0-48.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 1A141FDF600823            • android-arm64  • Android 14 (API 34)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 17.1 21B74
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)   

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by gmackall** [comment] 2023-10-26 18:26
Note from android triage: re-routing to framework

**Comment by Renzo-Olivares** [comment] 2023-10-26 21:46
Potentially a duplicate of https://github.com/flutter/flutter/issues/9471. Is this the same behavior that you're experiencing @DiegoGW?

**Comment by DiegoGW** [comment] 2023-10-26 22:07
> Potentially a duplicate of #9471. Is this the same behavior that you're experiencing @DiegoGW?

Yes @Renzo-Olivares , between all comments there is a similar replication step.

**Comment by Renzo-Olivares** [comment] 2023-10-26 23:02
I'm going to close this issue in favor of #9471. Please feel free to re-open if this issue is different.

**Closed by Renzo-Olivares** 2023-10-26 23:02 UTC
Labels: a: text input, P3, team-design, triaged-design, from: manual-qa
