### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by adambatchi** [flutter/flutter#152355] opened 2024-07-26 03:12 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=R9WR40YB2RJ --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: Broken pipe, errno = 32
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2004:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2481:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2216:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2168:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2314:36)
#16     _StdSink._write (dart:io/stdio.dart:401:13)
#17     _StdSink.writeln (dart:io/stdio.dart:419:5)
#18     DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:907:20)
<asynchronous suspension>
#19     _CompilationRequest.run (package:flutter_tools/src/compile.dart:396:24)
<asynchronous suspension>
#20     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:782:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4 23E214 darwin-arm64, locale en-JO)
    • Flutter version 3.22.3 on channel stable at /Users/adamabzakh/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (9 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/adamabzakh/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Users/adamabzakh/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • SM T505N (mobile)               • R9WR40YB2RJ               • android-arm64  • Android 12 (API 31)
    • Adam’s iPhone (mobile)          • 00008120-001834D20163C01E • ios            • iOS 18.0 22A5307i
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.185

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
firebase_core-3.2.0
firebase_core_web-2.17.3
firebase_messaging-15.0.3
firebase_messaging_web-3.8.11
flutter_local_notifications-17.2.1+2
flutter_local_notifications_linux-4.0.1
path_provider-2.1.3
path_provider_android-2.2.7
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.7
permission_handler_apple-9.4.5
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
phone_state-1.0.4
printing-5.13.1
share_plus-9.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.5
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-07-26 09:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/136753

**Closed by danagbemava-nc** 2024-07-26 09:14 UTC
Labels: in triage
