### ISSUE TITLE
Hot restart breaks correspondence between text field and soft keyboard on Android

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11044] opened 2017-06-29 21:09 UTC
## Steps to Reproduce

In the "Building Beautiful UIs with Flutter" code lab, step 5, using Android emulator. The UI contains a single `TextField`.
1. Tap the text field so that the soft keyboard appears.
1. Perform hot restart. Note: the soft keyboard stays up.
1. Type `hmm` on the keyboard. Note: the text field apparently receives nothing.
1. Dismiss the soft keyboard. Note: the keyboard disappears; the text field is still empty.
1. Tap the text field. Note: the text field now contains `hmm`.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/mravn/github/flutter
    • Framework revision d36e2f6191 (8 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by Skylled** [comment] 2017-06-30 01:07
Also covered in #11011

**Comment by cbracken** [comment] 2018-02-06 01:05
Just hit this too, though on iOS. Closing as dupe of #10713 and #11011.

**Closed by cbracken** 2018-02-06 01:05 UTC
