### ISSUE TITLE
FocusNode state change makes the state dependent widget not execute its callback on web 

### ISSUE THREAD

**Issue by wzslr321** [flutter/flutter#153277] opened 2024-08-12 13:21 UTC
`FocusNode`'s state used as a variable determining display of a clickable widget inside StatefulWidget leads to different behavior on mobile & web. 

 **Description:**
`FocusNode` can have a listener. If it is used to manipulate the state of `StatefulWidget` it can lead to unexpected results. 
In case where - on web - change of focus is triggered by a widget containing a `onTap` callback, the callback is not executed, if the focus node listener manipulated the variable on which the display of the widget was depending & refreshed the state causing it to be removed. 
In the same situation, on mobile, it leads to **only** executing the callback, unless the callback does not temporary force request focus, e.g. `showModalBottomSheet`, in which case both actions happen. 

Therefore it appears to execute processes in the following order:
1. Focus change handling
2. Rebuild
3. Gesture handling

### Steps to reproduce

Create a new project with `flutter create [name]` and adjust `main.dart` to the one in code sample below in this issue. 

### Expected results

I expect the callback to be executed on both platforms. 

### Actual results

The callback is only executed on mobile.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _hasFocus = false;
  final focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    focusNode.addListener(() {
      setState(() {
        _hasFocus = focusNode.hasFocus;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              width: 300,
              color: Colors.amber,
              child: TextField(
                focusNode: focusNode,
              ),
            ),
            if (_hasFocus)
              InkWell(
                onTap: () {
                  showModalBottomSheet(
                      context: context,
                      builder: (context) {
                        return Container(
                          padding: const EdgeInsets.all(50),
                          child: const Text('clicked'),
                        );
                      });
                },
                child: const Text(
                  'I will show you bottom sheet... but not on web',
                ),
              )
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![flutter-focus-bug](https://github.com/user-attachments/assets/45b99078-ba97-4b24-918b-64358bef8d1e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1.2 23B92 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/creatix/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (10 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/creatix/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5556         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-08-13 06:43
Hi @wzslr321 
This is working as intended (WAI). This is the difference between mobile and desktop platforms. You can try checking on macOS app (same result as Web) and touching outside (background) to see this.

On mobile platforms, the TextField is not unfocused when touching outside so the focus on the field persists and you can see the model sheet appears. But on web and desktop platforms, the field loses the focus so you will see the text disappear when tapping on. See the relevant code here:


https://github.com/flutter/flutter/blob/289ba8dc25f6b34738ee8e62a6c53db83c7b45e7/packages/flutter/lib/src/widgets/editable_text.dart#L5104-L5131 

You can work around this by adding `onTapOutside` to TextField like this:

```dart
TextField(
  focusNode: focusNode,
  onTapOutside: (event) => focusNode.requestFocus(),
),
```

I will close this as this is WAI. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2024-08-13 06:43 UTC
Labels: in triage
