### ISSUE TITLE
Crash on Flutter application launch on emulator

### ISSUE THREAD

**Issue by egodefroy** [flutter/flutter#66443] opened 2020-09-23 12:03 UTC
## Steps to Reproduce

Crashes with 1.22.0-12.1.pre

Works with  1.21.0-9.1.pre

1. From Xcode, launch the application on Emulator iPad air (4th generation)
2. The project builds
3. The application crashes at launch

## Logs

```
2020-09-23 13:29:01.527533+0200 Runner[52852:484760] [VERBOSE-2:shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "localhost", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
#1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
#2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
2020-09-23 13:29:01.527542+0200 Runner[52852:484773] [VERBOSE-2:shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "localhost", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
#1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
#2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
2020-09-23 13:29:01.527696+0200 Runner[52852:484773] [VERBOSE-3:dart_io.cc(39)] Check failed: !LogIfError(set_domain_network_policy_result).
2020-09-23 13:29:01.527728+0200 Runner[52852:484760] [VERBOSE-3:dart_io.cc(39)] Check failed: !LogIfError(set_domain_network_policy_result).
CoreSimulator 732.17 - Device: iPad Air (4th generation) (7888B562-066B-41D9-A280-0A022398BD1E) - Runtime: iOS 14.0 (18A372) - DeviceType: iPad Air (4th generation)

```

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-09-23 12:35
Hi @egodefroy 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by alvinthen** [comment] 2020-10-02 05:02
Finally solved this after hours, it seems that with the new network_policy.dart, we no longer need to add 'localhost' as NSExceptionDomains

**Comment by egodefroy** [comment] 2020-10-02 06:37
@alvinthen Great ! Sorry but I didn't manage to make a minimal example reproducing the problem

**Comment by pedromassangocode** [comment] 2020-10-02 10:47
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-02 10:47 UTC
Labels: in triage

**Comment by mvolpato** [comment] 2020-10-02 13:53
I experienced the same issue today after migrating to 1.22.

More specifically, I connect to **local Firebase Cloud Functions emulator**. In order to do that in iOS I need to add
```
         <dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```
to the `Info.plist`. And in my Dart file:

```
final cloudFunctionInstance = CloudFunctions(region: region).useFunctionsEmulator(origin: "http://localhost:5001")
```

Unfortunately since I updated to 1.22, I get the same error as above.

Following the [suggestion from alvinthen](https://github.com/flutter/flutter/issues/66443#issuecomment-702526131) I removed the dictionary key above from the `Info.plist`, and the app stopped crashing, but it still gave an error.
```
flutter: PlatformException(-1022, The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., null, null)
```

### Solution

I had to change the configuration of the Cloud Function emulator, adding the **host**, in `firebase.json`:
```
"emulators": {
    "functions": {
      "port": 5001,
      "host": "0.0.0.0" <-- added this
    },
    "firestore": {
      "port": 8080,
      "host": "0.0.0.0" <-- added this
    },
    "ui": {
      "enabled": true
    }
  }
```
and changed the `useFunctionsEmulator` call to:
```
final cloudFunctionInstance = CloudFunctions(region: region).useFunctionsEmulator(origin: "http://0.0.0.0:5001")
```
Now everything works again.

I do not know if this was intended behaviour, that is way I replied to this issue. @pedromassangocode feel free to close again if so.

**Comment by kuyazee** [comment] 2020-10-03 18:44
In my experience, if I set this key to true it seems to cause the crash

```
<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
<true/>
```

If I set it to false or remove it altogether the app doesn't crash.

More information:
- I'm running on iOS 14 Simulator 
- Seems to happen on any domain 

Here's my `flutter doctor -v`

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-PH)
    • Flutter version 1.22.0 at /Users/zonilyjamepesquera/flutter
    • Framework revision d408d302e2 (4 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zonilyjamepesquera/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • FD9EBBCA-9F59-4B3C-970B-CF66715D628A
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```
