### ISSUE TITLE
i was working  with fire base authentication but i am stuck with the error.

### ISSUE THREAD

**Issue by Rakshith202** [flutter/flutter#52951] opened 2020-03-20 11:54 UTC
<error

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity( 5812): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 5812): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 5812): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 5812): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 5812): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@cad72ab
D/FlutterActivityAndFragmentDelegate( 5812): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:50194/IF00I7mVk94=/ws
Syncing files to device Android SDK built for x86...
E/OpenGLRenderer( 5812): GL error: 0x506
>

<code

import 'package:flutter/material.dart';
//pages
import 'homepage.dart';
import 'loginpage.dart';
import 'signuppage.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: LoginPage(),
      routes:<String,WidgetBuilder>{
        '/landingpage':(BuildContext context)=>MyApp(),
        '/signup':(BuildContext context)=>Signup(),
        '/homepage':(BuildContext context)=>Home(),
      }
    );
  }
}
>

<

code

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Dash board"),
        centerTitle: true,
      ),
      body: Center(
        child: Container(
          child: Column(
            children: <Widget>[
              Text("You are now logged in"),
              SizedBox(height: 15.0,),
              OutlineButton(
                borderSide: BorderSide(
                  color: Colors.red,
                  style: BorderStyle.solid,width: 3.0
                ),
                child:Text("Log out"),
                onPressed: (){
                  FirebaseAuth.instance.signOut().then((value){}).catchError((e){print(e);});
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}
>

<
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/widgets.dart';

class UserManagement {
  storeNewUser(user, context) {
    Firestore.instance.collection('/users').add({
      'email':user.email,
      'uid':user.uid
    }).then((value) {
      Navigator.of(context).pop();
      Navigator.of(context).pushReplacementNamed('/homepage');
    }).catchError((e) {
      print(e);
    });

  }
}
>

<
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {

  String _email;
  String _password;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          padding:EdgeInsets.all(25.0),
          child:Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                decoration: InputDecoration(hintText: 'Email'),
                onChanged: (value){
                  setState(() {
                    _email=value;
                  });
                },
              ),

              SizedBox(height: 15,),
              TextField(
                decoration:InputDecoration(hintText: 'Password'),
                obscureText: true,
                onChanged: (value){
                  setState(() {
                    _password=value;
                  });
                },
              ),
              SizedBox(height: 20.0,),
              RaisedButton(
                child: Text('Login'),
                color: Colors.blue,
                textColor: Colors.white,
                elevation: 7.0,
                onPressed: (){
                  FirebaseAuth.instance.signInWithEmailAndPassword(email: _email, password: _password).then((user){
                    Navigator.of(context).pushReplacementNamed('/homepage');
                  }).catchError((e){print(e);});
                },
              ),
              SizedBox(height: 15,),
              Text('Dont have an account?'),
              SizedBox(height: 10.0,),
              RaisedButton(
                child: Text('Sign UP'),
                color: Colors.blue,
                textColor: Colors.white,
                elevation: 7.0,
                onPressed: (){
                  Navigator.of(context).pushNamed('/signup');
                },
              )
            ],
          )
        ),
      ),
    );
  }
}
>

<
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebaseproject/services/usermanagement.dart';

import 'package:flutter/material.dart';

class Signup extends StatefulWidget {
  @override
  _SignupState createState() => _SignupState();
}

class _SignupState extends State<Signup> {
  String _email;
  String _password;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
            padding:EdgeInsets.all(25.0),
            child:Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                TextField(
                  decoration: InputDecoration(hintText: 'Email'),
                  onChanged: (value){
                    setState(() {
                      _email=value;
                    });
                  },
                ),

                SizedBox(height: 15,),
                TextField(
                  decoration:InputDecoration(hintText: 'Password'),
                  obscureText: true,
                  onChanged: (value){
                    setState(() {
                      _password=value;
                    });
                  },
                ),
                SizedBox(height: 20.0,),
                RaisedButton(
                  child: Text('signup'),
                  color: Colors.blue,
                  textColor: Colors.white,
                  elevation: 7.0,
                  onPressed: (){
                   FirebaseAuth.instance.createUserWithEmailAndPassword(email: _email, password: _password).then((signedInUser){
                     UserManagement().storeNewUser(signedInUser, context);
                   }).catchError((e){
                     print(e);
                   });
                  },
                ),

              ],
            )
        ),
      ),
    );
  }
}
>
>

**Comment by TahaTesser** [comment] 2020-03-20 13:26
Hi @Rakshith202 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Rakshith202** [comment] 2020-03-20 14:14
<this is my flutter doctor>
C:\Users\chimple>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.10240], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.43.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment] 2020-03-20 14:42
Hi @Rakshith202 
I'm not sure what error are you talking about here with firebase auth 

Make sure to have email and password sign in enable in your firebase console and user acccount are created successfully 

### Code Sample
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: RaisedButton(onPressed: () async {
            FirebaseAuth.instance
                .signInWithEmailAndPassword(
                    email: 'taha@mail.com', password: "123456")
                .then((AuthResult user) {
              print(user.user.email);
            });
          }),
        ),
      ),
    );
  }
}
```

i test this minimal sample code and with latest version `firebase_auth` and it logs in fine 

please `flutter run --verbose` and, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem because above code sample has missing code or link your repository 

Thank you

**Comment by Rakshith202** [comment] 2020-03-20 15:08
Actually i was  following some tutorial but i dont know where iam wrong. The sample code which you have sent is understandable .Can u please send me the similar  code for storing the user data for registering and retrieving the same when required for updating .

**Comment by TahaTesser** [comment] 2020-03-20 15:28
Hi @Rakshith202 
This might help you [repo](https://github.com/bizz84/firebase_auth_demo_flutter) 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-03-20 15:28 UTC
Labels: in triage
