### ISSUE TITLE
Support physical keyboards on Android

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11177] opened 2017-07-12 20:37 UTC
## Steps to Reproduce

1. Fire up an AVD in Android Studio
2. Run the Flutter gallery in the AVD
3. Navigate to the "Text fields" demo
4. Select the first text input and begin typing on your physical keyboard

## Expected Behavior

You expect the text input to respond to physical key events, as they do in the iOS simulator.

## Actual Behavior

The text input does not respond to physical key events.

## Additional information

Some AVDs (such as the default used within Google) disable the virtual keyboard by default and rely on physical keyboard input.  For these emulators, there's no way to enter text in flutter apps.

**Comment by eseidelGoogle** [comment] 2017-07-13 03:19
See also https://github.com/flutter/flutter/issues/7943 and https://github.com/flutter/flutter/issues/9347

**Comment by MarkOSullivan94** [comment] 2017-10-22 01:05
Still experiencing issues where I can't use hardware keyboard for input into emulated Android device. Any estimation on when a fix will be released?

Details of my Flutter install:

Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision e8aa40eddd (4 days ago) • 2017-10-17 15:42:40 -0700
Engine • revision 7c4142808c
Tools • Dart 1.25.0-dev.11.0

**Comment by efortuna** [comment] 2017-10-24 18:46
+1 this affects codelabs and anyone working with Flutter for the first time who doesn't have a physical device

**Comment by slightfoot** [comment] 2017-10-28 15:12
+1 Just experienced this issue on Android 7.1 (API 25) running on Genymotion.

**Comment by hugovangalen** [comment] 2017-12-12 06:09
This same issue exists on real devices.

The Pixel C with hardware keyboard does not work...

**Comment by jerryzhenleicai** [comment] 2018-01-07 17:50
Yeah this will push devs to iOS camp.

**Comment by ChowieUK** [comment] 2018-01-12 12:30
I experience this issue on Android 7.0 and Android 7.1 but not on Android 8.0

**Comment by mit-mit** [comment] 2018-03-02 14:36
Clarifying that this is not emulator specific

**Comment by fareesh** [comment] 2018-03-04 22:51
Same issue on 4.4 Kitkat

**Comment by slightfoot** [comment] 2018-03-05 14:57
@mit-mit I can confirm that this is not Android version related or emulator related. I just plugged in a USB keyboard via a OTG connector to my PIxel phone running Android 8.1.0. The keyboard works with native apps but fails with Flutter apps.

I can also confirm the HW keyboard works with `RawKeyboardListener` on the Emulator Android v7.1.0 and Pixel running Android v8.1.0.

So it sounds like the raw event handling needs to be hooked up the text editable field code.

**Comment by tvolkert** [comment] 2018-03-05 15:48
iirc this is just something we never wired up in the engine.  @jason-simmons

**Comment by slightfoot** [comment] 2018-03-05 16:01
For myself, Having to enter in text in an app using the on-screen keyboard is a pain and slows down development. That fast hot-reload becomes painful when you have to enter text all the time.

**Comment by mark-amaray** [comment] 2018-03-08 14:07
Hi,

has anyone found a workaround for this? I have a barcode scanner that emulates an external keyboard that I need to process the input from.

**Comment by slightfoot** [comment] 2018-03-08 16:20
@mark-amaray as I said above, you can use [RawKeyboardListener](https://docs.flutter.io/flutter/widgets/RawKeyboardListener-class.html) the `focusNode` you supply it with will need to have the Focus for the `onKey` callback to be invoked.

**Comment by mark-amaray** [comment] 2018-03-09 09:19
@slightfoot Thanks for the confirmation, however, i am new to dart/flutter and understand in principal what you mean, but do you have an example of how this hangs together please? It would be a big help.

Thanks again.

**Comment by mark-amaray** [comment] 2018-03-12 16:20
I have been working on finding a solution to this and this is the code I have so far

class SearchScreenState extends State<SearchScreen> {

   TextEditingController _c = new TextEditingController();
   _buildTextComposer() {
     TextField t = new TextField(controller: _c,onSubmitted: _handleSubmitted,);
      FocusNode n = new FocusNode();
     FocusScope.of(context).requestFocus(n);
     return  new RawKeyboardListener(focusNode: n, onKey: (key) => handleKey(key.data.hashCode.toString()), child: t);
  }

  void _handleSubmitted(String text) {
  
  }

  void handleKey(String key)
  {
    String x = key;
    setState((){_c = new TextEditingController(text: x);});
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Search Item")),
      body: _buildTextComposer(),
    );
  }
}

Now pressing any key, if that is on the bluetooth keyboard or the scanner will replace the text in the TextField with a hash code.

This will be a different code each time, even if i press the same key.

Does anyone know how I am able to get the actual key pressed form the RawKeyEventDataAndroid that is generated by the RawKeyboardListner?

Thank you

**Comment by zoechi** [comment] 2018-03-12 16:36
@mark-amaray  you can make the code more readable by wrapping it in ```

**Comment by mark-amaray** [comment] 2018-03-12 16:40
@zoechi Thanks for the tip

I have made more progress, by including 

"import 'package:flutter/services.dart';"

and usinf the following code:

`class SearchScreenState extends State<SearchScreen> {

   TextEditingController _c = new TextEditingController();
   _buildTextComposer() {
     TextField t = new TextField(controller: _c,onSubmitted: _handleSubmitted,);
      FocusNode n = new FocusNode();
     FocusScope.of(context).requestFocus(n);
     return  new RawKeyboardListener(focusNode: n, onKey: (key) => handleKey(key.data), child: t);
  }

  void _handleSubmitted(String text) {

  }

  void handleKey(RawKeyEventDataAndroid key)
  { 
    String x;
    x = key.keyCode.toString();
    setState((){_c = new TextEditingController(text: x);});
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Search Item")),
      body: _buildTextComposer(),
    );
  }
}`

The TextField will give me the Android KeyCode value of the key pressed. I am now looking for a way to convert that into a String.

**Comment by zoechi** [comment] 2018-03-12 16:42
still no ``` :D
My eyes are already sour ;-)

**Comment by mark-amaray** [comment] 2018-03-12 16:45
@zoechi I used the insert code option in the toolbar and pasted between the characters in put in the window

**Comment by mark-amaray** [comment] 2018-03-12 16:46
```
class SearchScreenState extends State<SearchScreen> {

   TextEditingController _c = new TextEditingController();
   _buildTextComposer() {
     TextField t = new TextField(controller: _c,onSubmitted: _handleSubmitted,);
      FocusNode n = new FocusNode();
     FocusScope.of(context).requestFocus(n);
     return  new RawKeyboardListener(focusNode: n, onKey: (key) => handleKey(key.data), child: t);
  }

  void _handleSubmitted(String text) {

  }

  void handleKey(RawKeyEventDataAndroid key)
  {
    String x;
    x = key.keyCode.toString();
    setState((){_c = new TextEditingController(text: x);});
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Search Item")),
      body: _buildTextComposer(),
    );
  }
}
```

**Comment by zoechi** [comment] 2018-03-12 16:56
@mark-amaray much better :)
You can also edit previous comments. No need to add corrections as a new comment if you just posted the comment and it's unlikely anybody will miss the update or if the update doesn't change the meaning of a comment (like with formatting-only changes)

**Comment by ohir** [comment] 2018-03-19 10:23
Confirmed on physical device. Both BT and wired keyboards are just mute for a flutter app.

P.S. This »nonfeature« is an **absolute blocker** for any productivity app. Be it mail, questionnaires or simply chat one. Why it has been assigned to the **next** milestone is beyond my comprehension.

**Comment by tvolkert** [comment] 2018-03-19 18:06
This also blocks running Flutter apps on Chromebooks (via the ability to run Android apps on Chromebooks).

**Comment by gregko** [comment] 2018-04-23 11:52
+1 same issues here with Android Studio Android emulators, AMIDuOS emulator, Genymotion etc. Urgent fix is needed. Also sometimes the bug blocks physical input keyboard in other, native Android apps.

**Comment by MarkOSullivan94** [comment] 2018-05-13 12:01
Found a really weird case of the physical keyboard not working for emulated Pixel 2XL (API 27) when the TextFormField has `obsecureText: true`.

For anyone wanting to run an example: https://gist.github.com/MarkOSullivan94/bb3f0ea1eb158503f3235339bc23dae0

**Comment by Sdlion** [comment] 2018-05-18 19:04
- Install AndroidStudio and all the flutter SDK
- Run "Complete Example" https://flutter.io/cookbook/forms/validation/ on a newly created emulated device
- Click on the TextFormField

Result: nothing will happen. You won't be able to enter text. People beginning with Flutter would be deterred from using Flutter since finding this thread won't even explain why they can't even input any text. 

Workaround: [disable hardware keyboard](https://stackoverflow.com/questions/10238769/how-can-i-make-the-android-emulator-show-the-soft-keyboard) (since it still is not compatible) through the Settings App (Settings > Language & Input > Keyboard & Input Methods > Default > Turn Off "Hardware")

**Comment by gregko** [comment] 2018-05-21 12:08
I would be happy to test the patch too - with external keyboard on a Samsung tablet, on a Chromebook (debug build only I guess, as my Chromebook has Intel processor...) and of course on many emulators. If it's not integrated into master branch soon, how could I test it? Build entire flutter from sources at GitHub, or is there a simpler way?

**Comment by MarkOSullivan94** [comment] 2018-05-21 12:12
@gregko probably build sources from @slightfoot's branch where he has made the changes

**Closed** 2018-05-24 22:21 UTC
Labels: a: text input, customer: mulligan (g3), severe: new feature, ⎊ platform-chromebook, ▣ platform-android

**Comment by jagged3dge** [comment] 2019-01-16 07:21
Might I suggest a small patch to handle the `Home` and `End` keys in the physical keyboard interface as well?

**Comment by Jemshi101** [comment] 2019-04-25 07:09
> Found a really weird case of the physical keyboard not working for emulated Pixel 2XL (API 27) when the TextFormField has `obsecureText: true`.
> 
> For anyone wanting to run an example: https://gist.github.com/MarkOSullivan94/bb3f0ea1eb158503f3235339bc23dae0

This is happening still. I could not enter anything using a physical keyboard in a textfield with `obscureText: true` is used.

**Comment by tvolkert** [comment] 2019-04-25 14:36
@Jemshi101 since this issue is closed, can you open a new issue about the `obscureText` case?

**Comment by mikeesouth** [comment] 2020-10-07 12:21
I'm so confused - was this ever fixed back in May 2018 when this PR was merged and the issue closed? I'm having real struggles with this now in a production app where we try to support chromebooks with physical keyboards. Our app is already live and working on slates but extending it to chromebooks and also bluetooth connected keyboards has proven difficult.

Short summary is this: If I just create a textfield it'll work as expected. I can write with the physical keyboard - no problems. But when I use a RawKeyboardListener it's really buggy. The "onKey" callback is not triggered when I type letters, but then I realised that modifiers triggers the onKey event. So if I press left alt I get keycode 57, left shift gives 59 right ctrl gives 110 and so on. The top function keys on my chromebook works as well, such as back arrow, forward arrow, refresh and so on. But the letter keys, digits, space and backspace does not work. We need to register all key presses.

What's even weirder is that when I hold the left alt, then I can type letters and the RawKeyboardListener triggers onkey for those letters! So I can actually type in my application, if I hold down left alt... But not if I hold down shift, it seems to only work with left (and right) alt. Why is this?

So my question is - is this as intended by some reason? Is the RawKeyboardListener not supported on chromebooks? 

Was this issue closed when textfields were working and the RawKeyboardListener was forgotten in the fix? If I try the example code from @mark-amaray from March 12 2018 (2,5 years ago!) it still doesn't work with the physical keyboard on my chromebook. The result is exactly the same as in my other application: modifiers and function keys are registered, letters, space and digits only work when holding down the alt key.

I'm testing on a newly purchased HP Chromebook 14-db0004no 14" btw.

Any workarounds for supporting physical keyboards without using the RawKeyboardlistener in cases where I cannot use a regular flutter TextField?

**Comment by slightfoot** [comment] 2020-10-07 12:37
@mikeesouth no reason it shouldn't work. I have that same Chromebook. So i can test. Email me on simon@devangels.london and we can work out time for a chat today.

**Comment by mikeesouth** [comment] 2020-10-07 13:29
@slightfoot sounds nice! I created a very simple repro for this, do you mind firing it up on your side to see if you get the same results? The repro is here: https://github.com/mikeesouth/chromebook_keyboard

This repro is as simple as this:

1. `flutter create chromebook_keyboard`
2. Add `final _keyboardListenerFocus = FocusNode();` to the state class
3. Add `String _keyName = 'N/A';` to the state class
4. Add the following to the build method (e.g. as children to the column class):
```
Text('Here is plain TextField:'),
Container(width: 200, child: TextField()),
SizedBox(height: 50),
Text(
    'Tap the green container to show the keycode using a RawKeyboardListener:'),
GestureDetector(
  onTap: () => _keyboardListenerFocus.requestFocus(),
  child: Container(
    width: 200,
    height: 100,
    color: Colors.green,
    alignment: Alignment.center,
    child: RawKeyboardListener(
      focusNode: _keyboardListenerFocus,
      onKey: (keyEvent) => setState(
          () => _keyName = keyEvent.data.logicalKey.debugName),
      child: Text('keyName = $_keyName'),
    ),
  ),
),
```

I'm using latest flutter stable (1.22). 

**Expected results:** the physical keyboard works for the TextField and the physical keyboard also works for the RawKeyboardListener when pressing the green container (to set focus to the keyboard listener).

**Actual results:** if you start with the green container (keyboard listener) it recognizes all keys (i.e a, b, c, 1, 2, 3, space, left alt, left shift and so on). If you switch to the text field you can type text as expected. If you switch back to the green container - it no longer recognizes text, only modifiers such as left alt, left shift etc. BUT if you hold left alt, then it also recognizes letters and other keys (i.e. alt + a will display "_keyName = A"). Restart the app - the KeyboardListener works again but as soon as you focus the TextField the RawKeyboardListener will no longer recognize key presses.

Do you have the same behavior on your side? If so - then I guess it's a bug? If not it's something on my side.
