### ISSUE TITLE
Can't select text on desktop with `PointerDeviceKind.mouse` on `dragDevices`

### ISSUE THREAD

**Issue by talski** [flutter/flutter#122519] opened 2023-03-13 11:23 UTC
Right, please file a file to trace it.

_Originally posted by @xu-baolin in https://github.com/flutter/flutter/issues/122141#issuecomment-1465366625_
            
When I tap and drag inside a textfield, I expect it first tries to select, otherwise scroll, currently it's just scrolling. It only selects the text when I double tap and drag.

https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag#setting-a-custom-scrollbehavior-for-your-application

https://user-images.githubusercontent.com/740549/224310998-30964448-8814-4d3a-aa84-0c792c8738f6.mp4

<details>
<summary>Code sample</summary>

```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      };
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  String lorem =
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce luctus enim elit, at cursus lectus pellentesque at. Donec ac lorem ac nulla tincidunt dapibus sed sit amet velit. Aenean consequat, lorem ut efficitur hendrerit, nisi ante lobortis libero, a rutrum felis nisi sed mi. Aenean finibus urna at consequat egestas. Donec efficitur odio non dolor vestibulum congue. Donec aliquet ac neque non vestibulum. Ut pellentesque nunc nec blandit egestas. Maecenas mauris erat, euismod posuere dui nec, mattis ultricies justo.\n\nSed eget scelerisque risus. Donec quis odio enim. Cras eu urna enim. Fusce eget interdum nisl. Phasellus tempus vestibulum turpis, eu iaculis sem pellentesque ac. Proin ultricies, eros quis rutrum convallis, velit neque rutrum ante, non sodales urna sem quis velit. Nullam lacinia massa vel tempor egestas. Fusce euismod, nibh vel commodo ornare, est ante elementum neque, non condimentum ipsum odio et sem. Nam nec consectetur urna.\n\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur iaculis elit turpis, sit amet convallis lacus volutpat sit amet. Morbi quis elementum velit. Curabitur nec massa ut diam semper convallis et eu lorem. Donec maximus lobortis sem non suscipit. Nam ultrices, velit nec volutpat tristique, quam tortor sollicitudin purus, sit amet gravida mauris leo sed dui. Quisque facilisis tortor in nisl sollicitudin, sit amet pellentesque nisl malesuada. Etiam et justo eget nisl malesuada consectetur et nec leo.\n\nProin accumsan sollicitudin porta. Cras venenatis tempor enim, sit amet facilisis orci dapibus nec. In ornare mi et egestas pharetra. Pellentesque congue, turpis in consectetur rutrum, dolor dolor pellentesque odio, ut mollis lorem purus vitae lorem. Proin et dui nunc. Fusce eget augue nec sem cursus consectetur. Cras ac tempor felis, ut imperdiet erat. Ut viverra iaculis tellus, nec rutrum neque viverra eu. Quisque rutrum ex nec nisl ultricies, nec volutpat ante fermentum. Phasellus ac sem lorem. Sed nec massa eu massa efficitur ullamcorper nec in velit. Etiam nisl justo, finibus eget vulputate at, auctor sit amet metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n\nSuspendisse facilisis massa vel nisl porttitor interdum. Morbi odio est, accumsan et pulvinar sit amet, pretium ac augue. Vivamus lacus felis, egestas ut velit eget, rhoncus eleifend ligula. Pellentesque felis massa, mollis ac sagittis vitae, scelerisque at lectus. Quisque neque erat, hendrerit tristique dui sit amet, scelerisque porttitor ante. Suspendisse blandit risus maximus sapien euismod rutrum placerat quis erat. Nunc ut diam ac neque sodales pharetra id in ipsum. Mauris quam purus, vulputate a finibus sit amet, mollis at enim. Suspendisse ac efficitur quam, nec varius turpis. Morbi fermentum dui in imperdiet blandit.';

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ScrollConfiguration(
          behavior: MyCustomScrollBehavior(),
          child: ListView(
            //mainAxisAlignment: MainAxisAlignment.center,
            shrinkWrap: true,
            physics: const BouncingScrollPhysics(),
            children: [
              const Text(
                'You have pushed the button this many times:',
              ),
              Center(
                child: SizedBox(
                  width: 500,
                  child: TextFormField(
                    initialValue: lorem,
                    minLines: 20,
                    maxLines: 20,
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              Container(
                height: 1200,
                color: Colors.blue.withAlpha(32),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

**Comment by exaby73** [comment] 2023-03-13 12:28
Hello @talski. Are you referring to the behavior you described in https://github.com/flutter/flutter/issues/122141#issuecomment-1459044456?

**Comment by talski** [comment] 2023-03-13 16:43
@exaby73, exactly

**Comment by exaby73** [comment] 2023-03-14 07:50
In that example, I do not see a `SelectionArea` used. Therefore, by default, you cannot select any text

**Comment by exaby73** [comment] 2023-03-15 07:53
## Triage report

I can reproduce this issue on `Master (3.9.0-7.0.pre.32)`. 

<details>
<summary>Code Sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      };
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  String lorem =
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce luctus enim elit, at cursus lectus pellentesque at. Donec ac lorem ac nulla tincidunt dapibus sed sit amet velit. Aenean consequat, lorem ut efficitur hendrerit, nisi ante lobortis libero, a rutrum felis nisi sed mi. Aenean finibus urna at consequat egestas. Donec efficitur odio non dolor vestibulum congue. Donec aliquet ac neque non vestibulum. Ut pellentesque nunc nec blandit egestas. Maecenas mauris erat, euismod posuere dui nec, mattis ultricies justo.\n\nSed eget scelerisque risus. Donec quis odio enim. Cras eu urna enim. Fusce eget interdum nisl. Phasellus tempus vestibulum turpis, eu iaculis sem pellentesque ac. Proin ultricies, eros quis rutrum convallis, velit neque rutrum ante, non sodales urna sem quis velit. Nullam lacinia massa vel tempor egestas. Fusce euismod, nibh vel commodo ornare, est ante elementum neque, non condimentum ipsum odio et sem. Nam nec consectetur urna.\n\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur iaculis elit turpis, sit amet convallis lacus volutpat sit amet. Morbi quis elementum velit. Curabitur nec massa ut diam semper convallis et eu lorem. Donec maximus lobortis sem non suscipit. Nam ultrices, velit nec volutpat tristique, quam tortor sollicitudin purus, sit amet gravida mauris leo sed dui. Quisque facilisis tortor in nisl sollicitudin, sit amet pellentesque nisl malesuada. Etiam et justo eget nisl malesuada consectetur et nec leo.\n\nProin accumsan sollicitudin porta. Cras venenatis tempor enim, sit amet facilisis orci dapibus nec. In ornare mi et egestas pharetra. Pellentesque congue, turpis in consectetur rutrum, dolor dolor pellentesque odio, ut mollis lorem purus vitae lorem. Proin et dui nunc. Fusce eget augue nec sem cursus consectetur. Cras ac tempor felis, ut imperdiet erat. Ut viverra iaculis tellus, nec rutrum neque viverra eu. Quisque rutrum ex nec nisl ultricies, nec volutpat ante fermentum. Phasellus ac sem lorem. Sed nec massa eu massa efficitur ullamcorper nec in velit. Etiam nisl justo, finibus eget vulputate at, auctor sit amet metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n\nSuspendisse facilisis massa vel nisl porttitor interdum. Morbi odio est, accumsan et pulvinar sit amet, pretium ac augue. Vivamus lacus felis, egestas ut velit eget, rhoncus eleifend ligula. Pellentesque felis massa, mollis ac sagittis vitae, scelerisque at lectus. Quisque neque erat, hendrerit tristique dui sit amet, scelerisque porttitor ante. Suspendisse blandit risus maximus sapien euismod rutrum placerat quis erat. Nunc ut diam ac neque sodales pharetra id in ipsum. Mauris quam purus, vulputate a finibus sit amet, mollis at enim. Suspendisse ac efficitur quam, nec varius turpis. Morbi fermentum dui in imperdiet blandit.';

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ScrollConfiguration(
          behavior: MyCustomScrollBehavior(),
          child: ListView(
            //mainAxisAlignment: MainAxisAlignment.center,
            shrinkWrap: true,
            physics: const BouncingScrollPhysics(),
            children: [
              const Text(
                'You have pushed the button this many times:',
              ),
              Center(
                child: SizedBox(
                  width: 500,
                  child: TextFormField(
                    initialValue: lorem,
                    minLines: 20,
                    maxLines: 20,
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              Container(
                height: 1200,
                color: Colors.blue.withAlpha(32),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
<summary>Video demonstration</summary>

https://user-images.githubusercontent.com/50555895/225242702-8337a966-84ce-4594-ad8b-e50b2ff8a6e8.mp4

</details>

**Comment by talski** [comment] 2023-03-17 17:32
> This sounds like a regression. @moffatman do you think this could be related to the pointer changes on web?
> 
> @talski what kind of mouse are you using? Is it a magic mouse?

It's a logitech mouse, I'm on Windows

**Comment by moffatman** [comment] 2023-03-17 18:02
As a first guess I don't think it is related to my changes, I only looked at scroll wheel events.

Just to clarify - what's the expected behaviour, you will scroll when dragging vertically, but select when dragging horizontally? And right now it scrolls when dragging horizontally?

**Comment by moffatman** [comment] 2023-03-17 18:24
I think the bug is introduced here: https://github.com/flutter/flutter/pull/118342. Now the new TapAndDragGestureRecognizer will never win in competition with other recognizers. It won't do the work of `_acceptDrag` based on the drag distance until it has already `_wonArenaForPrimaryPointer` which is kind of in conflict with each other. I guess on touch screens this works since it will claim after a timeout anyway. But on desktop, the drag threshold for a vertical drag is only 1 pixel. So unless you keep your mouse incredibly still, the vertical drag is gonna win.

**Comment by Piinks** [comment] 2023-03-17 19:40
Thanks for taking the time to look!

I wonder if the threshold should be changed for desktop then.. @Renzo-Olivares can you take a look when you have a chance?

**Comment by Renzo-Olivares** [comment] 2023-03-18 00:22
@Piinks Will take a look ASAP this does seem troublesome, thanks for the heads up!

**Comment by xu-baolin** [comment] 2023-03-21 07:42
When the user configures mouse-drag scrolling, this gesture will conflict with mouse-drag selection. Mouse-drag scrolling is rarely used on desktop, so the native behavior cannot be known. It seems to me that this is most likely a gesture conflict issue and we should clarify what the desired behavior is. CC @Renzo-Olivares @Piinks

**Comment by xu-baolin** [comment] 2023-03-22 03:50
@Renzo-Olivares  As you stated above, there may not be a good solution. 
In my opinion this is a wrong usage scenario and is not reasonable to implement anyway. Some people want scrolling first, others want selection text first.

**Comment by talski** [comment] 2023-03-22 13:52
> In the sample code, on `stable`, if I start dragging inside a textfield towards top or down, it will scroll, if I start dragging towards left or right, it will select the text, so I can move up or down and it will keep selecting.

The current stable behavior is at least better than beta/master, I can do both actions, select and scroll, depending on wich direction I start to drag.

**Comment by Renzo-Olivares** [comment] 2023-03-28 08:45
@talski It looks like the documentation in the framework warns against the use of `PointerDeviceKind.mouse` on `dragDevices` when used in situations with selectable text.

https://github.com/flutter/flutter/blob/0300cfa60382fe2cb1e154ee98a590996e22d59a/packages/flutter/lib/src/widgets/scroll_configuration.dart#L131-L137

I do agree this is a regression in the previous behavior. And it has also brought to light a similar issue on touch devices where you cannot drag to select in any direction while TextField is inside of a `Scrollable`.

From my observation on Android you can start a drag to move the cursor in a `Scrollable` and without a `Scrollable` if you move horizontally first. On iOS you can move vertically and horizontally if your touch begins on the cursor.

I have a proposed fix for this issue and #122141 with PR #123055. Curious to hear any thoughts on the solution.

### Before fix

macOS|iOS|Android
--|--|--
https://user-images.githubusercontent.com/948037/228179483-c6393ddb-2410-4e12-8eef-474c123049ef.mov|https://user-images.githubusercontent.com/948037/228180665-79741006-579e-4bcb-bdc5-d2cf1ec3ae2a.mov|https://user-images.githubusercontent.com/948037/228180531-f9cd8882-44e1-45b6-a280-c6ec5be3accf.mov

### After fix

macOS|iOS|Android
--|--|--
https://user-images.githubusercontent.com/948037/228175951-a7de18b2-e2a3-4ccd-8cdf-8603e1994342.mov|https://user-images.githubusercontent.com/948037/228176384-597bd6ff-380d-43fc-b2d2-687085599044.mov|https://user-images.githubusercontent.com/948037/228177595-7f66a7b5-0c2a-4f28-aafe-54feb2f9116b.mov

**Comment by talski** [comment] 2023-03-28 15:06
@Renzo-Olivares, thank you, I've tested on windows and it works fine when the text comes pre-defined or I type everything directly in the field, when I paste a text with line breaks and select the text, when it reaches the line break, it jumps to the top of field,

On web build it doesn't work at all, also it doesn't show line breaks properly, it's showing square characters, and when I type, it shows the caret always on beggining, when tap anywhere inside the field it jumps to start of the field too.

using Flutter SDK3.9.0-18.0.pre.34 and Dart SDK3.0.0-367.0.dev

windows test
https://user-images.githubusercontent.com/740549/228281711-6e1d9a9f-43b5-4af3-abef-cf6067487d1e.mp4

web test
https://user-images.githubusercontent.com/740549/228281742-eb0e7f81-5cd2-4a80-9236-35d96164a371.mp4

**Comment by talski** [comment] 2023-03-28 17:37
I guess the bugs I mentioned in the previous comment was introduced somewhere else, I applied your pr manually on
`Flutter SDK3.9.0-1.0.pre.146 / Dart SDK3.0.0-313.0.dev (Flutter)` and it worked as you described.

**Closed** 2023-04-05 23:00 UTC
Labels: severe: regression, framework, f: scrolling, a: desktop, has reproducible steps, P4, found in release: 3.7, found in release: 3.9
