### ISSUE TITLE
Face Authentication is not working in Flutter App

### ISSUE THREAD

**Issue by Mobile-AppDeveloper** [flutter/flutter#158318] opened 2024-11-07 12:48 UTC
### Steps to reproduce

I'm using local_auth: 2.1.8.
and i'm enabling face id and fingerprint in my app.

### Expected results

showing an dialog face id and fingerprint to authenticate.

### Actual results

when i enable face id without enabling fingerprint in my device settings, then i get an dialog tell that biometric authentication isn't setup.

when i enable face id and fingerprint together in my device settings, then i get an dialog with fingerprint option only .

### Code sample

  bool authenticated = await auth.authenticate(
          localizedReason:  S.of(AppCommon.context).pleaseAuthenticateToAccessApp,
          options: AuthenticationOptions(
              useErrorDialogs: true,
              stickyAuth: true,
              biometricOnly: true
          ),
        );

### Screenshots or Video

![WhatsApp Image 2024-11-07 at 2 25 39 PM](https://github.com/user-attachments/assets/2bbbfe56-9403-4620-b57e-971e2ff32298)
![WhatsApp Image 2024-11-07 at 2 25 39 PM (1)](https://github.com/user-attachments/assets/4320b62f-5dc6-4383-a04d-150bffc68ebd)

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-x64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2024.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2024-11-07 13:16
Closing as duplicate of https://github.com/flutter/flutter/issues/117309

**Closed by darshankawar** 2024-11-07 13:16 UTC
Labels: in triage
