### ISSUE TITLE
Print statements not showing up

### ISSUE THREAD

**Issue by EricPreventa** [flutter/flutter#41409] opened 2019-09-26 20:41 UTC
## Steps to Reproduce

Upgraded my iPad to iPad OS 13.1, upgraded Xcode to latest, running the latest dev branch of flutter. I'm not getting a print output. Not sure if this has something to do with the latest iPad version, or if there's something else I need to do. Tried print and debugPrint. Both not working. 

```
Flutter 1.10.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc3ca9a916 (30 hours ago) • 2019-09-25 10:57:58 -0400
Engine • revision 63949eb0fd
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

```

**Comment by EricPreventa** [comment] 2019-09-26 23:06
Oddly enough, using a simulator with version 12.2 works just fine. Seems like something is going on with either Apple and their latest iPad OS 13+ or something with flutter and being able to display print statements from Apple iPad OS 13+

**Comment by jmagman** [comment] 2019-09-27 16:55
Duplicate of https://github.com/flutter/flutter/issues/41133.

**Closed by jmagman** 2019-09-27 16:55 UTC
Labels: ⌺‬ platform-ios
