### ISSUE TITLE
Flutter thinks everything is its fault.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8908] opened 2017-03-20 18:40 UTC
I often get asserts like this:

```
11:28:23.642: I/flutter (32115): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
11:28:23.649: I/flutter (32115): The following assertion was thrown building ThreadListItem([Thread#230133652]; dirty):
11:28:23.652: I/flutter (32115): 'package:widgets/src/user/alphatar.dart': Failed assertion: line 78: 'avatarUrl != null': is not
11:28:23.655: I/flutter (32115): true.
11:28:23.665: I/flutter (32115):
11:28:23.668: I/flutter (32115): Either the assertion indicates an error in the framework itself, or we should provide substantially
11:28:23.671: I/flutter (32115): more information in this error message to help you determine and fix the underlying cause.
11:28:23.674: I/flutter (32115): In either case, please report this assertion by filing a bug on GitHub:
11:28:23.676: I/flutter (32115):   https://github.com/flutter/flutter/issues/new
11:28:23.679: I/flutter (32115):
11:28:23.682: I/flutter (32115): When the exception was thrown, this was the stack:
11:28:23.684: I/flutter (32115): #2      Alphatar.Alphatar.withUrl (package:widgets/src/user/alphatar.dart:78)
11:28:23.687: I/flutter (32115): #3      Alphatar.Alphatar.fromNameAndUrl (package:widgets/src/user/alphatar.dart:144)
11:28:23.689: I/flutter (32115): #4      ThreadListItem.build (package:widgets/src/email/thread_list_item.dart:68)
11:28:23.692: I/flutter (32115): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3120)
11:28:23.694: I/flutter (32115): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3065)
11:28:23.697: I/flutter (32115): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
11:28:23.700: I/flutter (32115): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
11:28:23.702: I/flutter (32115): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
11:28:23.705: I/flutter (32115): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
11:28:23.708: I/flutter (32115): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)

```

This is obviously an issue in the build function of the Alphatar widget but Flutter takes ownership: "Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause."

While I appreciate Flutter's suggestion it's Flutter's fault I can't create a valid Flutter program, it's not.

**Comment by Hixie** [comment] 2017-03-20 20:02
Yeah this is a known bug. The code that tries to decide whether to show this or not bitrotted.

**Comment by Hixie** [comment] 2017-03-20 20:03
Dupe of https://github.com/flutter/flutter/issues/4021

**Closed by Hixie** 2017-03-20 20:03 UTC
