### ISSUE TITLE
Symlink generation needs to account for error 1 "incorrect function" on Windows

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66795] opened 2020-09-28 01:25 UTC
This can happen if the project resides on a network drive, from SO:

> On windows it is not possible to symbolically link a folder from a local drive to a network drive.

The exception looks like:

```
Thread 0 main threadFileSystemException: FileSystemException: Cannot create link, path = 'e:\<ELIDED>\windows\flutter\ephemeral\.plugin_symlinks\url_launcher_windows' (OS Error: Incorrect function.
, errno = 1)


at _Link.throwIfError | (link.dart:276)
-- | --
  | at _Link.createSync | (link.dart:197)
  | at ForwardingLink.createSync | (forwarding_link.dart:22)
  | at ForwardingLink.createSync | (forwarding_link.dart:22)
  | at _createPlatformPluginSymlinks | (plugins.dart:1113)
  | at createPluginSymlinks | (plugins.dart:1078)
  | at refreshPluginsList | (plugins.dart:1142)
  | at <asynchronous gap> | (async)
  | at FlutterProject.ensureReadyForPlatformSpecificTooling | (project.dart:241)
  | at CreateCommand._generateApp | (create.dart:678)
  | at <asynchronous gap> | (async)
  | at CreateCommand.runCommand | (create.dart:434)
  | at _rootRunUnary | (zone.dart:1198)
  | at _CustomZone.runUnary | (zone.dart:1100)
  | at _FutureListener.handleValue | (future_impl.dart:143)
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:696)
  | at Future._propagateToListeners | (future_impl.dart:725)
  | at Future._completeWithValue | (future_impl.dart:529)
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:40)
  | at _completeOnAsyncReturn | (async_patch.dart:311)
  | at FlutterProject.organizationNames | (project.dart)
  | at _rootRunUnary | (zone.dart:1198)
  | at _CustomZone.runUnary | (zone.dart:1100)
  | at _FutureListener.handleValue | (future_impl.dart:143)
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:696)
  | at Future._propagateToListeners | (future_impl.dart:725)
  | at Future._completeWithValue | (future_impl.dart:529)
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:40)
  | at _completeOnAsyncReturn | (async_patch.dart:311)
  | at IosProject.productBundleIdentifier | (project.dart)
  | at _rootRunUnary | (zone.dart:1198)
  | at _CustomZone.runUnary | (zone.dart:1100)
  | at _FutureListener.handleValue | (future_impl.dart:143)
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:696)
  | at Future._propagateToListeners | (future_impl.dart:725)
  | at Future._completeWithValue | (future_impl.dart:529)
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:40)
  | at _completeOnAsyncReturn | (async_patch.dart:311)
  | at IosProject._parseProductBundleIdentifier | (project.dart)
  | at _rootRunUnary | (zone.dart:1198)
  | at _CustomZone.runUnary | (zone.dart:1100)
  | at _FutureListener.handleValue | (future_impl.dart:143)
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:696)
  | at Future._propagateToListeners | (future_impl.dart:725)
  | at Future._completeWithValue | (future_impl.dart:529)
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:40)
  | at _completeOnAsyncReturn | (async_patch.dart:311)
  | at IosProject.buildSettingsForBuildInfo | (project.dart)
  | at _rootRunUnary | (zone.dart:1198)
  | at _CustomZone.runUnary | (zone.dart:1100)
  | at _FutureListener.handleValue | (future_impl.dart:143)
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:696)
  | at Future._propagateToListeners | (future_impl.dart:725)
  | at Future._completeWithValue | (future_impl.dart:529)
  | at Future._asyncCompleteWithValue.<anonymous closure> | (future_impl.dart:567)
  | at _rootRun | (zone.dart:1190)
  | at _CustomZone.run | (zone.dart:1093)
  | at _CustomZone.runGuarded | (zone.dart:997)
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:1037)
  | at _microtaskLoop | (schedule_microtask.dart:41)
  | at _startMicrotaskLoop | (schedule_microtask.dart:50)
  | at _runPendingImmediateCallback | (isolate_patch.dart:118)
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:169)

```

The tool should catch this particular exception, and treat it as if symlinks are not supported for the project and/or exit with an explanation and solution (move project to non-network drive)

**Comment by stuartmorgan** [comment] 2020-09-28 17:24
Duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by stuartmorgan** 2020-09-28 17:24 UTC
Labels: P4, platform-windows, severe: crash, tool
