### ISSUE TITLE
DataTable Exception: The method '[]' was called on null.

### ISSUE THREAD

**Issue by dutyk** [flutter/flutter#34992] opened 2019-06-24 13:05 UTC
error message:
```
I/flutter (21607): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21607): The following NoSuchMethodError was thrown during paint():
I/flutter (21607): The method '[]' was called on null.
I/flutter (21607): Receiver: null
I/flutter (21607): Tried calling: [](0)
I/flutter (21607): 
I/flutter (21607): When the exception was thrown, this was the stack:
I/flutter (21607): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (21607): #1      RenderTable.paint (package:flutter/src/rendering/table.dart:1137:33)
I/flutter (21607): #2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #6      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #7      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #8      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (21607): #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (21607): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #13     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:560:17)
I/flutter (21607): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #16     RenderSliverPadding.paint (package:flutter/src/rendering/sliver_padding.dart:314:15)
I/flutter (21607): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #19     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:528:17)
I/flutter (21607): #20     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter (21607): #21     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter (21607): #22     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:519:15)
I/flutter (21607): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #24     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #25     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #26     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (21607): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (21607): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #35     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2608:11)
I/flutter (21607): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #42     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2608:11)
I/flutter (21607): #43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #50     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #51     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #52     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (21607): #53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (21607): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #55     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:564:11)
I/flutter (21607): #56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #60     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #61     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #62     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (21607): #63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (21607): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #66     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #67     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #68     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter (21607): #69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter (21607): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (21607): #71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #73     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:560:17)
I/flutter (21607): #74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (21607): #76     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:528:17)
I/flutter (21607): #77     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter (21607): #78     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter (21607): #79     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:519:15)
I/flutter (21607): #80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (21607): #81     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (21607): #82     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (21607): #83     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:859:29)
I/flutter (21607): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:19)
I/flutter (21607): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (21607): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (21607): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (21607): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (21607): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (21607): #93     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (21607): #94     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (21607): (elided 3 frames from package dart:async)
I/flutter (21607): 
I/flutter (21607): The following RenderObject was being processed when the exception was fired:
I/flutter (21607):   RenderTable#4563b relayoutBoundary=up5
I/flutter (21607):   creator: Table ← DataTable ← TopBar ← RepaintBoundary-[<3>] ← IndexedSemantics ←
I/flutter (21607):   NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← SliverList ←
I/flutter (21607):   MediaQuery ← SliverPadding ← Viewport ← ⋯
I/flutter (21607):   parentData: <none> (can use size)
I/flutter (21607):   constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
I/flutter (21607):   size: Size(411.4, 536.0)
I/flutter (21607):   specified column widths: {0: IntrinsicColumnWidth(flex: null), 1: IntrinsicColumnWidth(flex:
I/flutter (21607):   null), 2: IntrinsicColumnWidth(flex: null)}
I/flutter (21607):   default column width: FlexColumnWidth(1.0)
I/flutter (21607):   table size: 3×11
I/flutter (21607):   column offsets: 0.0, 115.14285714285715, 284.2857142857143
I/flutter (21607):   row offsets: 0.0, 56.0, 104.0, 152.0, 200.0, 248.0, 296.0, 344.0, 392.0, 440.0, 488.0, 536.0
I/flutter (21607): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (21607):   RenderSemanticsGestureHandler#4b0b0 relayoutBoundary=up6
I/flutter (21607):     RenderPointerListener#5abba relayoutBoundary=up7
I/flutter (21607):       RenderConstrainedBox#e3871 relayoutBoundary=up8
I/flutter (21607):         RenderPadding#4ae3d
I/flutter (21607):           RenderPositionedBox#11b58
I/flutter (21607):   RenderSemanticsGestureHandler#30546 relayoutBoundary=up6
I/flutter (21607):     RenderPointerListener#2390b relayoutBoundary=up7
I/flutter (21607):       RenderConstrainedBox#4528d relayoutBoundary=up8
I/flutter (21607):         RenderPadding#69711
I/flutter (21607):           RenderPositionedBox#45693
I/flutter (21607):   RenderSemanticsGestureHandler#d9962 relayoutBoundary=up6
I/flutter (21607):     RenderPointerListener#cb5d5 relayoutBoundary=up7
I/flutter (21607):       RenderConstrainedBox#97df0 relayoutBoundary=up8
I/flutter (21607):         RenderPadding#6cecc
I/flutter (21607):           RenderPositionedBox#ea064
I/flutter (21607):   RenderSemanticsGestureHandler#252f0 relayoutBoundary=up6
I/flutter (21607):     RenderPointerListener#b310d relayoutBoundary=up7
I/flutter (21607):       RenderConstrainedBox#ce284 relayoutBoundary=up8
I/flutter (21607):         RenderPadding#77ef8
I/flutter (21607):           RenderPositionedBox#241cb
I/flutter (21607):   RenderSemanticsGestureHandler#f88ec relayoutBoundary=up6
I/flutter (21607):     RenderPointerListener#22c34 relayoutBoundary=up7
I/flutter (21607):       RenderConstrainedBox#9ba5b relayoutBoundary=up8
I/flutter (21607):         RenderPadding#7a321
I/flutter (21607):           RenderPositionedBox#dfbb8
I/flutter (21607):   ...(descendants list truncated after 25 lines)
I/flutter (21607): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (21607): Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.
```

**Comment by shihaohong** [comment] 2019-06-24 15:21
Hi @dutyk, could you share a minimal runnable sample to reproduce this error?

**Comment by dutyk** [comment] 2019-06-25 12:28
@override
  Widget build(BuildContext context) {
    return new Container(
      height: 700,
      child: new DefaultTabController(
        length: myTabs.length,
      child: new Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            backgroundColor: Colors.white,
            bottom: new TabBar(
              tabs: myTabs,
              controller: _tabController,
              isScrollable: true,
              indicatorColor: Colors.red,
              indicatorSize: TabBarIndicatorSize.tab,
              labelColor: Colors.red,
              unselectedLabelColor: Colors.black,
              indicatorWeight: 5.0,
              labelStyle: TextStyle(fontSize: 20),
            ),
          ),
            preferredSize: Size.fromHeight(70)
        ),
//        body: new TabBarView(
//          children: myTabs.map((Tab tab) {
//            return new Center(child: new Text(tab.text));
//          }).toList(),
//        ),
      body: TabBarView(
          controller: _tabController,
          children: <Widget>[
            ListView(
              children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topIncreaseData.map(
                    (data){
                      return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                      );
                    },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
//              DataTable(
//                columns: [
//                  DataColumn(label: Text('名称')),
//                  DataColumn(label: Text('最新价(CNY)')),
//                  DataColumn(label: Text('24H成交额(CNY)')),
//                ],
//                rows: topDealData.map(
//                      (data){
//                    return DataRow(
//                        cells: [
//                          DataCell(Text('${data.fromSymbol}')),
//                          DataCell(Text('${data.latestPrice}')),
//                          DataCell(Text('${data.dealAmount}')),
//                        ]
//                    );
//                  },
//                ).toList(),
//              ),
              Text('aaaaaa'),
              Text('aaaaaa'),
              Text('aaaaaa'),
              Text('aaaaaa'),

            ],
            ),
            ListView(children: <Widget>[
//              DataTable(
//                columns: [
//                  DataColumn(label: Text('名称')),
//                  DataColumn(label: Text('最新价(CNY)')),
//                  DataColumn(label: Text('涨跌幅')),
//                ],
//                rows: topNewData.map(
//                      (data){
//                    return DataRow(
//                        cells: [
//                          DataCell(Text('${data.fromSymbol}')),
//                          DataCell(Text('${data.latestPrice}')),
//                          DataCell(Text('${data.range}')),
//                        ]
//                    );
//                  },
//                ).toList(),
//              ),
              Text('aaaaaa'),
              Text('aaaaaa'),
              Text('aaaaaa'),
              Text('aaaaaa'),

            ],
            ),
          ]),
      ),
      )
    );
  }

**Comment by dutyk** [comment] 2019-06-25 12:30
@override
  Widget build(BuildContext context) {
    return new Container(
      height: 700,
      child: new DefaultTabController(
        length: myTabs.length,
      child: new Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            backgroundColor: Colors.white,
            bottom: new TabBar(
              tabs: myTabs,
              controller: _tabController,
              isScrollable: true,
              indicatorColor: Colors.red,
              indicatorSize: TabBarIndicatorSize.tab,
              labelColor: Colors.red,
              unselectedLabelColor: Colors.black,
              indicatorWeight: 5.0,
              labelStyle: TextStyle(fontSize: 20),
            ),
          ),
            preferredSize: Size.fromHeight(70)
        ),
        body: TabBarView(
          controller: _tabController,
          children: <Widget>[
            ListView(
              children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topIncreaseData.map(
                    (data){
                      return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                      );
                    },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('24H成交额(CNY)')),
                ],
                rows: topDealData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.dealAmount}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topNewData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
          ]),
      ),
      )
    );
  }

**Comment by dutyk** [comment] 2019-06-25 12:30
`@override
  Widget build(BuildContext context) {
    return new Container(
      height: 700,
      child: new DefaultTabController(
        length: myTabs.length,
      child: new Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            backgroundColor: Colors.white,
            bottom: new TabBar(
              tabs: myTabs,
              controller: _tabController,
              isScrollable: true,
              indicatorColor: Colors.red,
              indicatorSize: TabBarIndicatorSize.tab,
              labelColor: Colors.red,
              unselectedLabelColor: Colors.black,
              indicatorWeight: 5.0,
              labelStyle: TextStyle(fontSize: 20),
            ),
          ),
            preferredSize: Size.fromHeight(70)
        ),
        body: TabBarView(
          controller: _tabController,
          children: <Widget>[
            ListView(
              children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topIncreaseData.map(
                    (data){
                      return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                      );
                    },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('24H成交额(CNY)')),
                ],
                rows: topDealData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.dealAmount}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topNewData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
          ]),
      ),
      )
    );
  }`

**Comment by dutyk** [comment] 2019-06-25 12:31
`
@override
  Widget build(BuildContext context) {
    return new Container(
      height: 700,
      child: new DefaultTabController(
        length: myTabs.length,
      child: new Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            backgroundColor: Colors.white,
            bottom: new TabBar(
              tabs: myTabs,
              controller: _tabController,
              isScrollable: true,
              indicatorColor: Colors.red,
              indicatorSize: TabBarIndicatorSize.tab,
              labelColor: Colors.red,
              unselectedLabelColor: Colors.black,
              indicatorWeight: 5.0,
              labelStyle: TextStyle(fontSize: 20),
            ),
          ),
            preferredSize: Size.fromHeight(70)
        ),
        body: TabBarView(
          controller: _tabController,
          children: <Widget>[
            ListView(
              children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topIncreaseData.map(
                    (data){
                      return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                      );
                    },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('24H成交额(CNY)')),
                ],
                rows: topDealData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.dealAmount}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
            ListView(children: <Widget>[
              DataTable(
                columns: [
                  DataColumn(label: Text('名称')),
                  DataColumn(label: Text('最新价(CNY)')),
                  DataColumn(label: Text('涨跌幅')),
                ],
                rows: topNewData.map(
                      (data){
                    return DataRow(
                        cells: [
                          DataCell(Text('${data.fromSymbol}')),
                          DataCell(Text('${data.latestPrice}')),
                          DataCell(Text('${data.range}')),
                        ]
                    );
                  },
                ).toList(),
              ),
            ],
            ),
          ]),
      ),
      )
    );
  }
`

**Comment by dutyk** [comment] 2019-06-26 03:20
is this ok?

**Comment by dutyk** [comment] 2019-06-26 12:46
how to solve the problem

**Comment by shihaohong** [comment] 2019-06-26 15:22
@dutyk Could you also share your state (the variables in your Widget)? With only the `build` method, it's difficult to tell where error could be coming from.

**Comment by shihaohong** [comment] 2019-06-26 15:33
Could you share your state as well? It would be helpful to see `topNewData`, `topDealData` and `topIncreaseData`.

**Comment by dutyk** [comment] 2019-06-27 12:44
![2](https://user-images.githubusercontent.com/23434767/60267010-cf253680-991b-11e9-83e7-fd678dc5c5fc.JPG)

when switch from "行情" to "首页", the problem occurs

![1](https://user-images.githubusercontent.com/23434767/60267035-d9dfcb80-991b-11e9-9bf6-411a63cab0fc.JPG)

```
class TopBar extends StatefulWidget {
  final topIncreaseDataApi;
  final topDealDataApi;
  final topNewDataApi;

  const TopBar([this.topIncreaseDataApi, this.topDealDataApi, this.topNewDataApi]) : super();

  @override
  State<StatefulWidget> createState() => _TopBarState();
}

class _TopBarState extends State<TopBar>{
  TabController _tabController;
  List topIncreaseData = new List();
  List topDealData = new List();
  List topNewData = new List();


  final List<Tab> myTabs = <Tab>[
    new Tab(text: '涨幅榜'),
    new Tab(text: '成交额榜'),
    new Tab(text: '新币榜'),
  ];

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _getData();
    _tabController = new TabController(
      length: myTabs.length,
      vsync: ScrollableState(),
    );
  }

  Future _getData() async {

    List topIncreaseTemp = [];
    List topDealTemp = [];
    List topNewTemp = [];

    if (widget.topIncreaseDataApi is Function) {
      topIncreaseTemp = await widget.topIncreaseDataApi();
    }

    if (widget.topDealDataApi is Function) {
      topDealTemp = await widget.topDealDataApi();
    }

    if (widget.topNewDataApi is Function) {
      topNewTemp = await widget.topNewDataApi();
    }

    //if (newEntries.isEmpty) {
    if (this.mounted) {
      setState(() {
        topIncreaseData.clear();
        topDealData.clear();
        topNewData.clear();
        topIncreaseData.addAll(topIncreaseTemp);
        topDealData.addAll(topDealTemp);
        topNewData.addAll(topNewTemp);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return new Container(
      height: 700,
      padding: EdgeInsets.only(top: 100),
      child: new DefaultTabController(
        length: myTabs.length,
        child: new Scaffold(
          appBar: PreferredSize(
              child: AppBar(
                backgroundColor: Colors.white,
                bottom: new TabBar(
                  tabs: myTabs,
                  controller: _tabController,
                  isScrollable: true,
                  indicatorColor: Colors.red,
                  indicatorSize: TabBarIndicatorSize.tab,
                  labelColor: Colors.red,
                  unselectedLabelColor: Colors.black,
                  indicatorWeight: 5.0,
                  labelStyle: TextStyle(fontSize: 20),
                ),
              ),
              preferredSize: Size.fromHeight(70)
          ),
          body: TabBarView(
              controller: _tabController,
              children: <Widget>[
                ListView(
                  children: <Widget>[
                    DataTable(
                      columns: [
                        DataColumn(label: Text('名称')),
                        DataColumn(label: Text('最新价')),
                        DataColumn(label: Text('涨跌幅')),
                      ],
                      rows: topIncreaseData.map(
                            (data){
                              return DataRow(
                                  cells: [
                                    DataCell(Text('${data.fromSymbol}')),
                                    DataCell(Text('${data.latestPrice}')),
                                    DataCell(Text('${data.range}')),
                                  ]
                              );
                              },
                      ).toList(),
                    ),
                  ],
                ),
                ListView(
                  children: <Widget>[
                    DataTable(
                      columns: [
                        DataColumn(label: Text('名称')),
                        DataColumn(label: Text('最新价(CNY)')),
                        DataColumn(label: Text('24H成交额(CNY)')),
                      ],
                      rows: topDealData.map(
                            (data){
                              return DataRow(
                                  cells: [
                                    DataCell(Text('${data.fromSymbol}')),
                                    DataCell(Text('${data.latestPrice}')),
                                    DataCell(Text('${data.dealAmount}')),
                                  ]
                              );
                              },
                      ).toList(),
                    ),
                  ],
                ),
                ListView(
                  children: <Widget>[
                    DataTable(
                      columns: [
                        DataColumn(label: Text('名称')),
                        DataColumn(label: Text('最新价(CNY)')),
                        DataColumn(label: Text('涨跌幅')),
                      ],
                      rows: topNewData.map(
                            (data){
                              return DataRow(
                                  cells: [
                                    DataCell(Text('${data.fromSymbol}')),
                                    DataCell(Text('${data.latestPrice}')),
                                    DataCell(Text('${data.range}')),
                                  ]
                              );
                              },
                      ).toList(),
                    ),
                  ],
                ),
              ]
          ),
        ),
      )
    );
  }

```

**Comment by TahaTesser** [comment] 2020-02-27 12:57
Hi @dutyk 
Due to lack complete code sample, `flutter doctor -v` isn't given
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you

**Closed by TahaTesser** 2020-02-27 12:57 UTC
Labels: f: material design, framework
