### ISSUE TITLE
flutter_plugin_tools Fails with Unhandled exception

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#15381] opened 2018-03-10 17:14 UTC
Using the platform-tools to format/analyze the code fails with the below exception.

Command Used: `pub global run flutter_plugin_tools format --plugins share`

I have git, dart sdk, flutter, pub and clang in my PATH.

Exception:

```
Formatting all .dart files...
CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: flutter format "F:\05. Project\01-Flutter\plugins\packages\share\example\lib\main.dart" "F:\05. Project\01-Flutter\plugins\packages\share\lib\share.dart"
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:59)
<asynchronous suspension>
#1      FormatCommand._formatDart (package:flutter_plugin_tools/src/format_command.dart:100)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:38)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#5      new Future.sync (dart:async/future.dart:222)
#6      CommandRunner.run (package:args/command_runner.dart:109)
#7      main (package:flutter_plugin_tools/src/main.dart:37)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Doctor Results below.

```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-IN)
    • Flutter version 0.1.5 at F:\03. System Paths\flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices (1 available)
    • MotoG3 • ZY222ZZS6C • android-arm • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by Purus** [comment] 2018-03-10 17:17
Formatting individual files work fine.

`flutter format "F:\05. Project\01-Flutter\plugins\packages\share\example\lib\main.dart"`

**Comment by Purus** [comment] 2018-03-10 17:18
Output of the analyze command.

`pub global run flutter_plugin_tools analyze --plugins share`

**Exception:**

```
Activating tuneup package...
CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: pub global activate tuneup
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:59)
<asynchronous suspension>
#1      AnalyzeCommand.run (package:flutter_plugin_tools/src/analyze_command.dart:25)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#4      new Future.sync (dart:async/future.dart:222)
#5      CommandRunner.run (package:args/command_runner.dart:109)
#6      main (package:flutter_plugin_tools/src/main.dart:37)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by Purus** [comment] 2018-03-13 05:07
Any hint on this?

**Comment by quentinleguennec** [comment] 2018-04-03 11:14
Same here.
I can also run "flutter format" and "flutter analyze" just fine by themselves.

**Comment by zoechi** [comment] 2018-07-06 09:30
Is this still an issue?

**Comment by quentinleguennec** [comment] 2018-07-18 20:56
I thing I had this when I was working on a Windows computer (not sure, it was a will back). 
I'm working on a Mac now and did some addition to the share plugin today and flutter_plugin_tools worked perfectly.

**Comment by quentinleguennec** [comment] 2018-07-18 21:00
I thing I had this when I was working on a Windows computer (not sure, it was a will back). 
I'm working on a Mac now and did some addition to the share plugin today and flutter_plugin_tools worked perfectly.

**Comment by zoechi** [comment] 2018-07-31 20:01
Probably caused by a space in the user name or the path of the project.
See also #18938

**Comment by zoechi** [comment] 2018-08-27 08:27
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-08-27 08:27 UTC
Labels: p: tooling, ❖ platform-windows
