### ISSUE TITLE
Bimodal behaviour on complex_layout_scroll_perf_ios__timeline_summary worst_frame_rasterizer_time_millis

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#24019] opened 2018-11-06 20:48 UTC
The complex_layout_scroll_perf_ios__timeline_summary worst_frame_rasterizer_time_millis benchmark is bimodal, with some results being around 20ms and some being around 60ms. We should figure out why and either fix the benchmark or the engine to be more reliable.

cc @cbracken @liyuqian

**Comment by franciscojma86** [comment] 2019-07-30 22:03
Regressions started to flake since [c96806ec887bc8120e236ae37ecb966e483e5451](https://github.com/flutter/flutter/commit/c96806ec887bc8120e236ae37ecb966e483e5451) on 7/16

**Comment by liyuqian** [comment] 2019-07-30 22:13
Interesting, it seems that the old bimodal behaviour is gone on 7/16. Instead, we get some red bars, which is much slower than before, but also less frequent than the old modal. It's hard to tell which commit changes the behavior due to the noise. Maybe an automated bisection is needed to understand this.

**Comment by Hixie** [comment] 2019-08-04 16:21
check if the bimodal behavior corresponds to running on different hosts, could just be two different hardware configurations

**Comment by jonahwilliams** [comment] 2024-08-13 03:19
worst frame times are frequently unstable, as host select or a random GC can make them much worse. Closing as unactionable.

**Closed by jonahwilliams** 2024-08-13 03:19 UTC
Labels: engine, c: performance, P2, team-engine, triaged-engine
