### ISSUE TITLE
[Discussion] 174 packages broken on Flutter master

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41308] opened 2019-09-25 16:39 UTC
The latest `flutter update-packages` (flutter/flutter#39932) changed the pinned version of the `intl` package from 0.15.x to 0.16.0.

The `intl` package has [174 dependent packages](https://pub.dev/packages?q=dependency%3Aintl&page=1). Following the update in the Flutter tree (pinning `intl` to 0.16.0) these packages cannot be used with Flutter master by apps that use `flutter_localizations` (assuming they follow the common practice of using `^` as the constraint for its dependencies).

The "default fix" a package maintainer would follow up with is to bump their `intl` constraint to `^0.16.0`, but this makes the latest version of the package unsupported with Flutter master (which we try hard to avoid).

As we were considering how to deal with this issue for the `local_auth` plugin ([PR comment thread](https://github.com/flutter/plugins/pull/2084)), it turned out that the major version bump to the `intl` package was a mistake (https://github.com/dart-lang/intl/issues/233). So we can mitigate this specific issue by extending the `intl` version constraint to `>=0.15.1 <0.17.0`. Though I'm not sure it will be obvious to the maintainers of the other 173 packages.

I'd like to raise a few points for discussion:

### Dealing with similar future scenarios
How do we allow packages to support both Flutter master and Flutter stable following a major version bump to a transitive dependency that is pinned by Flutter?

While Flutter's rule is to always pin a dependency maybe we should consider allowing Flutter to depend both on version N.0.0 and N-1.0.0 following a major version bump, and only pin the dependency to N.0.0 after a stable Flutter release (to minimize the versions Flutter should worry about maybe we could use a "version a.b.c or version x.y.z" constraint instead of a version range, AFAIK pub does not support such "or" constraints?)

@Hixie any thoughts?

### Mitigating unnecessary major version bumps
Maybe a simple check like requiring a "BREAKING CHANGE" section in the changelog when a major version bump is published can help prevent accidental major version bumps?

@mit-mit @csells @jonasfj any thoughts? (I realize it's not trivial as CHANGELOG is unstructured, but we can probably think of some way to make sure an author is aware they are publishing a breaking change)

### Mitigating unnecessary major version bumps after the fact
For cases like the `0.16.0` which turned out to not be a breaking change - if we believe this is leading to a wide breakage in the ecosystem can anyone think of a reasonable mechanism to allow mitigation after the fact?

@mit-mit @jonasfj 

### Monitoring such breakages
I believe that we are currently pretty much blind to such issues in the ecosystem, unless we hear of them through GitHub issues.

@zanderso we've previously discussed collecting dependency resolution failure rates for `flutter pub get`, this may be a good tool to monitor for such failures.

cc @alan-knight

**Comment by Hixie** [comment] 2019-09-25 22:24
If we have a package where we say we support two versions, we would have to run our entire test battery against each version. If we have two packages where we support two versions, we'd have to run our entire test battery against every combination of those two packages, so four times. This will rapidly get out of control. This will be especially unlikely to be practical since this will only be relevant when the change is across a package's "breaking change" boundary, so in theory we shouldn't be able to use either version interchangeably anyway.

So I don't think we can support multiple versions.

We don't want to wait until just before we bump our own version to bump our dependencies, for a few reasons. First, we don't know when we're going to bump our version, so we can't make that prediction easily. Second, we bump the version at the very start of the cycle, not the end, so it would actually just maximize the problem. We could instead bump our dependencies at the end of the cycle,  before we cut our release branch, but that runs into a similar problem: we don't know when we're going to cut our branch. Thirdly, and most importantly, we really don't want to wait until the last minute to bump our dependencies because we need time to catch errors that they introduce.

So I don't think we want to change the timing of our dependency bumps.

Making it easy to make a package that works with both the current master Flutter and the current stable Flutter seems ideal, but I really don't know how to do that in a statically-analyzable way...

cc @mit-mit @vsmenon @leafpetersen

**Comment by amirh** [comment] 2019-09-25 22:37
@Hixie what would be your suggestion for package maintainers in such cases (major update to a package pinned by Flutter)? support Flutter master? (in which case Flutter stable users are likely not going to get bugfixes until Flutter is released) or support Flutter stable? (in which case the moment Flutter is release a bunch of packages cannot be resolved with the new Flutter version)

**Comment by Hixie** [comment] 2019-09-25 22:56
One option for package maintainers would be to maintain two versions of their package, one for master at x.y.z, and one for stable at x-1.y.z, assuming pub supports that.

**Comment by amirh** [comment] 2019-09-25 22:58
Another interesting alternative - maybe we can try and get the maintainers of packages pinned by Flutter to land breaking changes in a phased way (similar to how we land breaking changes in Flutter to mitigate the same problem). 
Probably a first step would be to reach out to all of them and get them aware of the implications, and a second step would be to have some mechanism to detect/enforce this early.

**Comment by amirh** [comment] 2019-09-25 22:58
> One option for package maintainers would be to maintain two versions of their package, one for master at x.y.z, and one for stable at x-1.y.z, assuming pub supports that.

As a package maintainer I'd hate to have to keep 2 branches and release bug fixes to both.

**Comment by alan-knight** [comment] 2019-09-25 23:05
I certainly didn't realize that bumping the minor version was going to be a
problem for people. I only bumped it because we were significantly
increasing the minimum SDK, which while significant, isn't really breaking.
One obvious thing is that we really ought to bring it up to a 1.0.0 release
so that anyone pinning with ^ won't be broken by second-level increments.

**Comment by Hixie** [comment] 2019-09-25 23:09
> As a package maintainer I'd hate to have to keep 2 branches and release bug fixes to both.

Certainly. It shouldn't be a problem that often, though.

> One obvious thing is that we really ought to bring it up to a 1.0.0 release so that anyone pinning with ^ won't be broken by second-level increments.

We should bring `intl` to 1.0 in general, if we expect people to use it. :-)

**Comment by amirh** [comment] 2019-09-25 23:51
Seems like part of the confusion is around the pub versioning conventions for packages with versions smaller than 1.0.0 (the versioning scheme for these is `0.MAJOR.MINOR+PATCH`). This isn't the first time we see wrong version updates as package developers aren't aware of this convention.

I guess this can be partly mitigated by forcing a breaking change description when publishing major version updates.

Another (maybe crazy?) idea is managing versions for plugin authors, e.g when you pub publish we ask you: "Does this update include a breaking change?" "Does this update include a new feature?", and then the tool proposes what the version number should be.

**Comment by Hixie** [comment] 2019-09-25 23:54
I agree that part of the problem is that we have breaking-change updates that aren't (though I suspect we have non-breaking-change-version-updates that _should_ be much more often, technically), but I think that's mostly a distraction from the core problem here, which would still occur regardless.

**Comment by mit-mit** [comment] 2019-09-26 07:51
@Hixie wrote:
> One option for package maintainers would be to maintain two versions of their package, one for master at x.y.z, and one for stable at x-1.y.z, assuming pub supports that.

Yes, you can publish a package on what corresponds to both a stable channel and a dev channel: https://dart.dev/tools/pub/publishing#publishing-pre-releases. Consumers always get stable channel packages by default; you need to specifically specify the pre-release version to get that.

But this, as @amirh pointed out, means maintaining two versions of the package, which is painful.

**Comment by mit-mit** [comment] 2019-09-26 07:51
Is it time to consider running tests on all our channels?

**Comment by jonasfj** [comment] 2019-09-30 15:30
Also:
 * Loosen your dependency constraints (I understand why you pin, but this is the downside),
 * Vendor packages you depend on into the Flutter SDK and hide their interface,
 * Avoid major version breaks by creating a new package name (e.g. `intl2`).
 * Avoid major version break by creating a new library in the package `package:intl/intl2.dart`.

**Comment by pedromassangocode** [comment] 2021-02-19 13:29
Hi @amirh 
Is this still a valid issue? It has been one year since this issue was filled and this may not be valid anymore.
Thank you

**Comment by pedromassangocode** [comment] 2021-03-12 14:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:07 UTC
Labels: plugin, waiting for customer response
