### ISSUE TITLE
Probable type inference error?

### ISSUE THREAD

**Issue by eduardkieser** [flutter/flutter#18357] opened 2018-06-11 10:22 UTC
I got the below exception message this morning:
Also, this is my first bug report ever, so please excuse any newbness.
In my own words: I created 2 lists of integers in a separate function called getTextAndColorIndexes().
Which looks like this:
```
List<List> getTextAndColorIndexes(){
  var rng = new Random();
  List<int> colorList = [];
  List<int> colorTextList = [];
  for (int i = 0;i<6;i++){
    colorList = appendNext4Colors(colorList);
  }
  for (int i = 0;i<6;i++){
    colorTextList = appendNext4Texts(colorList,colorTextList);
  }
  return [colorList,colorTextList];
  print(colorList);
  print(colorTextList);
}
```
I tested the function in it's own main function and it printed the correct info, but when incorporating into the rest my app as follows:
```
  static List<List> _colorAndTextOrder = getTextAndColorIndexes();
  List<int> _colorOrder = _colorAndTextOrder[0];
  //print(_colorOrder);
  List<int> _textOrder  = _colorAndTextOrder[1];
  //print(_textOrder);
```
The following happened:
```
I/flutter ( 2176): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2176): The following assertion was thrown building Builder:
I/flutter ( 2176): type 'List<dynamic>' is not a subtype of type 'List<num>'
I/flutter ( 2176): 
I/flutter ( 2176): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2176): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2176): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2176):   https://github.com/flutter/flutter/issues/new
I/flutter ( 2176): 
I/flutter ( 2176): When the exception was thrown, this was the stack:
I/flutter ( 2176): #0      absElementWise (package:stroop_test/utils.dart:21:10)
I/flutter ( 2176): #1      appendNext4Texts (package:stroop_test/utils.dart:107:29)
I/flutter ( 2176): #2      getTextAndColorIndexes (package:stroop_test/utils.dart:126:21)
I/flutter ( 2176): #3      _MyHomePageState._colorAndTextOrder (file:///C:/Users/Eduard/GoogleDrive/WorkSpaces/Flutter/stroop_test/lib/main.dart:59:42)
I/flutter ( 2176): #4      _MyHomePageState._colorAndTextOrder (file:///C:/Users/Eduard/GoogleDrive/WorkSpaces/Flutter/stroop_test/lib/main.dart:59:21)
I/flutter ( 2176): #5      new _MyHomePageState (file:///C:/Users/Eduard/GoogleDrive/WorkSpaces/Flutter/stroop_test/lib/main.dart:61:27)
I/flutter ( 2176): #6      MyHomePage.createState (file:///C:/Users/Eduard/GoogleDrive/WorkSpaces/Flutter/stroop_test/lib/main.dart:43:41)
I/flutter ( 2176): #7      new StatefulElement (package:flutter/src/widgets/framework.dart:3710:23)
I/flutter ( 2176): #8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:789:42)
I/flutter ( 2176): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2905:40)
I/flutter ( 2176): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #99     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
I/flutter ( 2176): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #102    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter ( 2176): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #131    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): Observatory server failed to start after 2 tries
I/flutter ( 2176): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #157    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #163    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #176    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #180    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2176): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #199    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #210    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #214    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #216    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #220    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #222    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #223    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #224    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #225    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #227    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #229    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #230    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #231    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #232    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #233    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #235    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #236    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #237    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2176): #238    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #239    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #240    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2176): #242    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2176): #243    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2176): #244    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2176): #245    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2176): #246    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2176): #247    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter ( 2176): #248    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter ( 2176): #249    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter ( 2176): #250    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 2176): #251    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter ( 2176): #252    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter ( 2176): #253    runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter ( 2176): #254    main (file:///C:/Users/Eduard/GoogleDrive/WorkSpaces/Flutter/stroop_test/lib/main.dart:4:16)
I/flutter ( 2176): #255    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 2176): #256    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by zoechi** [comment] 2018-06-11 10:56
Bug report is good. Adding the output of `flutter doctor` as requested in the issue template is usually a good idea.

I think the error is caused by

```
List<int> colorList = [];
```
which should be

```
var /* or final */ colorList = <int>[];
```
or
```
List<int> colorList = <int>[];
```

The left type is only the type of the variable, the right side is the type of the value.
If you pass the value to a function or other variable, the type of the original variable has no effect anymore.
Usually it's better to just use `var` or `final` and let the tools infer the type.

**Comment by jonahwilliams** [comment] 2018-06-11 20:55
I believe the issue might be caused by the return type of `getTextAndColorIndexes`.  `List<List>` is equivalent to `List<List<dynamic>>`, not "infer the type of the list".  And since you return a list literal without a type annotation `return [colorList,colorTextList];` this gets reified as such.

**Comment by zoechi** [comment] 2018-06-12 03:11
@eduardkieser I deleted above comment because what I wrote was not true. 
Dart does infer the generic type from the variable type.
Sorey for the confusion.

**Comment by eduardkieser** [comment] 2018-06-12 12:28
Thanks, implementing the fix of the first (deleted) comment, put me on the right path. I also used a few helper functions to do element-wise subtraction of list items which took and returned num types, which also caused the lists to be cast back to num and then gave issues.
My current work around seems to work, but for future would the correct way of dealing with this issue be to add the type annotation in the return statement of `getTextAndColorIndexes` ?
Something like:  `return [List<List<int>>colorList,List<List<int>>colorTextList];` ?

**Comment by jonahwilliams** [comment] 2018-06-12 16:28
The fix for the snippet above is:

```dart
List<List<int>> getTextAndColorIndexes() {
  var rng = new Random();
  List<int> colorList = [];
  List<int> colorTextList = [];
  for (int i = 0; i<6; i++){
    colorList = appendNext4Colors(colorList);
  }
  for (int i = 0; i<6; i++){
    colorTextList = appendNext4Texts(colorList, colorTextList);
  }
  return <int>[colorList,colorTextList];
}
```

I don't know what `appendNext4Texts` does, but this will work provided that it does indeed return a `List<int>`.

**Comment by Hixie** [comment] 2018-06-12 18:31
Sounds like this was not an issue in Flutter, so I'm going to close this. Thanks.

**Closed by Hixie** 2018-06-12 18:31 UTC
