### ISSUE TITLE
Horizontal overscroll is being clipped on Android

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8523] opened 2017-03-02 06:24 UTC
The horizontal overscroll glow is being clipped or rendered incorrectly. The vertical overscroll glow is correctly rendered.

![screenshot_20170301-221958-01](https://cloud.githubusercontent.com/assets/37941/23495467/b4480a58-fecd-11e6-81f2-6037407e6cc9.jpg)

**Comment by abarth** [comment] 2017-03-02 06:25
Can you say a bit more about how to reproduce this issue?

**Comment by lukef** [comment] 2017-03-02 06:33
Sure. Sorry, will make sure I include more details in the future.

Two scenarios: 

1. Using a regular `TabBarView` inside a `Positioned.fill`
2. I'm using a `PageView.custom`:

```
List<Widget> children = ...
SliverChildDelegate childrenDelegate = new SliverChildListDelegate(children);
PageView pageView = new PageView.custom(
  childrenDelegate: this.childrenDelegate,
);
```

Both cases seem to be exhibiting the issue consistently.

**Comment by abarth** [comment] 2017-03-03 01:42
@Hixie I think we still have a coordinate flipped somewhere in the horizontal glow math.

**Comment by Hixie** [comment] 2017-03-03 18:46
What's the issue exactly?

**Comment by lukef** [comment] 2017-03-03 18:50
The `GlowingOverscrollIndicator` is being clipped to the rect rather than being displayed as circular on android devices for any horizontal scroll actions. I'm not sure if its an issue with a radius or a center point calculation or something else. I tried to debug that code last night (very briefly) but got caught up with other things sorry.

**Comment by eseidelGoogle** [comment] 2017-03-03 19:04
This is easy to repro with a horizontal scrollview on Android, btw.  It looks like the overscroll glow is drawing from the bottom of the screen with the correct cliprect, just wrong origin.

**Comment by Hixie** [comment] 2017-03-03 20:45
Wow yeah I wonder what I did.

**Comment by Hixie** [comment] 2017-03-06 23:29
Turns out this is a Skia bug. Consider this app. It has a function that draws a rectangle with a circle in the middle. The first one has no particular transforms applied. It renders fine (whitish). The second is rotate by pi/2 and flipped along the y-axis; it renders fine too (green).

The next three should all look identical (they are the red ones). They are the same as the green one but with the y-axis (now effectively the x-axis since we're rotated by pi/2) squeezed further, by 0.5 plus or minor 0.001. It should look like a squeezed version of the green one, blurred out a bit. Instead, two of the circles end up squeezed in the wrong direction.

```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() {
  runApp(new CustomPaint(painter: new TestPainter()));
}

class TestPainter extends CustomPainter {
  void drawFlag(Canvas canvas, Paint paint) {
    canvas.drawRect(new Rect.fromLTWH(50.0, 50.0, 300.0, 200.0), paint);
    canvas.drawCircle(new Point(200.0, 150.0), 50.0, paint);
  }

  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = 10.0;

    paint.color = const Color(0xFFEEEEEE);
    drawFlag(canvas, paint);

    canvas.rotate(math.PI / 2.0);
    canvas.scale(1.0, -1.0);
    paint.color = const Color(0xFF00FF00);
    drawFlag(canvas, paint);

    canvas.save();
    canvas.scale(1.0, 0.4999);
    paint.color = const Color(0xFFFF0000);
    drawFlag(canvas, paint);
    canvas.restore();

    canvas.save();
    canvas.scale(1.0, 0.5000);
    paint.color = const Color(0xFFFF0000);
    drawFlag(canvas, paint);
    canvas.restore();

    canvas.save();
    canvas.scale(1.0, 0.5001);
    paint.color = const Color(0xFFFF0000);
    drawFlag(canvas, paint);
    canvas.restore();
  }
  @override
  bool shouldRepaint(TestPainter oldDelegate) => true;
}
```

This is what it renders:
![flutter_01](https://cloud.githubusercontent.com/assets/551196/23634788/fb9bb31c-0280-11e7-90cd-1ee2b4390a08.png)

cc @chinmaygarde to take over the investigation. :-)

**Comment by chinmaygarde** [comment] 2017-03-07 00:59
Hmm. I can't reproduce this on the desktop shell. It probably platform specific. But how ?! :( I guess thats a data point. 

![screen shot 2017-03-06 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/44085/23637043/32d4406c-028e-11e7-9cde-2c783a663e93.png)

**Comment by eseidelGoogle** [comment] 2017-03-07 01:02
@chinmaygarde can you escalate to Skia? :)  Thanks!

**Comment by chinmaygarde** [comment] 2017-03-07 01:03
Will do. Trying all platform variants first.

**Comment by eseidelGoogle** [comment] 2017-03-07 01:19
So this is an Android-GL only bug?

**Comment by chinmaygarde** [comment] 2017-03-07 01:20
Android is fine too. Am I being trolled ?!

![img_0661](https://cloud.githubusercontent.com/assets/44085/23637558/4287d49e-0291-11e7-9780-eea4dd708b99.jpg)

**Comment by chinmaygarde** [comment] 2017-03-07 01:37
Ok, I tried both debug and release variants on Android to make sure there were no differences between AOT vs JIT modes. Both are fine.

**Comment by chinmaygarde** [comment] 2017-03-07 01:39
Ok. I was testing on ToT with local engine. I can reproduce this with the currently released engine. I need to do a bisect of the changes since the last release and current ToT. But this is definitely not an issue anymore. Rather worrying how this regressed though. Bisecting.

**Comment by chinmaygarde** [comment] 2017-03-07 01:59
The only two changes in the engine repository between ToT and the released version is a minor change where [I got rid of an iOS specific flag](https://github.com/flutter/engine/commit/be5d971aa7641f43819e5305f6ca892dcc0a00e8) and literally a commit [with a whitespace change](https://github.com/flutter/engine/commit/6a00eee9f3b1201e42f0ca76d46ba1c13df610d8). I tried bisecting the framework and cannot find a revision using a released version of the engine that is correctly rendering the test case. All I can think of is to manually pull the released engine and do a binary diff against the locally built variant. This is bizarre.

**Comment by Hixie** [comment] 2017-03-21 22:15
What's the status of this bug? Did we figure out if it was a Skia problem? Local issue? Only devices @chinmaygarde hasn't touched? :-)

**Comment by chinmaygarde** [comment] 2017-03-21 23:25
I have not made any progress on this. Local builds on all platforms were fine for me. I was building on a Mac and did ensure to checkout to the version of the released engine. Will try building on Linux. Besides that, out of ideas.

**Comment by Hixie** [comment] 2017-03-21 23:41
Ah, could be something that happens with the compiler on Linux maybe?

**Comment by eseidelGoogle** [comment] 2017-03-25 02:24
I'm able to reproduce this on genymotion on Mac:
<img width="446" alt="screen shot 2017-03-24 at 7 23 33 pm" src="https://cloud.githubusercontent.com/assets/11857803/24318745/6e161104-10c7-11e7-8732-a9fbe8f82450.png">

However looks fine in iOS Simulator.

**Comment by eseidelGoogle** [comment] 2017-03-25 02:39
Same problem on Android Emulator:
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

<img width="456" alt="screen shot 2017-03-24 at 7 38 53 pm" src="https://cloud.githubusercontent.com/assets/11857803/24318838/9821fde4-10c9-11e7-91b9-f87853fc9fdf.png">

**Comment by eseidelGoogle** [comment] 2017-03-25 02:52
Here is the code I used to repro:
https://github.com/eseidelGoogle/bug5823

I'm using flutter/flutter@06144a7207fb0ea860e6db20e63b71f680b0ebab

flutter doctor is clean
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)

**Comment by chinmaygarde** [comment] 2017-03-27 20:30
I converted the code in the sample to the equivalent Skia calls and added it to [this fiddle](https://fiddle.skia.org/c/c92d54a8a9cb214c694355d2144b61ce). This does not seem to be a Skia issue. Maybe the raster cache. Checking now.

**Comment by chinmaygarde** [comment] 2017-03-27 20:34
@eseidelGoogle Did you try using a locally built engine on Mac or was this from the released engine?

**Comment by eseidelGoogle** [comment] 2017-03-28 17:49
@chinmaygarde i was using a released engine.

**Comment by eseidelGoogle** [comment] 2017-04-04 22:32
@chinmaygarde are you actively working on this?  (Just checking our in-progress M2 bugs to make sure they're actually owned.)

**Comment by chinmaygarde** [comment] 2017-04-04 23:27
No. I am not actively working on this because I am not able to reproduce this.

**Comment by sethladd** [comment] 2017-04-05 19:19
I don't know if it's the same issue, but you can see a rectangular (instead of ellipse) vertical glow in the gallery: https://github.com/flutter/flutter/issues/8747

**Comment by lukef** [comment] 2017-04-05 19:47
Yes, this is the same issue as far as I know

**Comment by jason-simmons** [comment] 2017-04-12 00:17
Reproduced it and looked at the Skia code.  This apparently happens if we flow through EllipseOp::Make

EllipseOp::Make is calculating the ellipse's x and y radius based on scale and skew values extracted from the viewMatrix that I don't think are accurate if a negative scale transform has been applied.

This works as expected if I patch EllipseOp::Make to call viewMatrix.mapRect(ellipse) and use the resulting radii.

**Comment by chinmaygarde** [comment] 2017-04-12 01:13
Can you prepare a reduced test case on fiddle.skia.org so we can share it
with the Skia team?

**Comment by jason-simmons** [comment] 2017-04-12 17:42
Skia bug files: https://bugs.chromium.org/p/skia/issues/detail?id=6495

**Comment by jvanverth** [comment] 2017-04-21 15:31
Should be fixed by https://skia-review.googlesource.com/c/13989/.

**Comment by jason-simmons** [comment] 2017-04-25 17:56
Fix has been integrated into Flutter

**Closed by jason-simmons** 2017-04-25 17:56 UTC
Labels: customer: posse (eap), dependency: skia, prod: scrolling
