### ISSUE TITLE
Flutter issues after update to Android Studio 4.2.1

### ISSUE THREAD

**Issue by emru67** [flutter/flutter#82975] opened 2021-05-20 03:05 UTC
OS Windows 10 Pro 64-bit

1. Download and install Android Studio 4.2.1. Open it and let it download and update all the files that it needs. All new tools are available (database inspector, emulator window, profiler - **but it says 6 Problems** as soon as it starts up, before doing anything and it does not show **what** problems or where). Set and save option to open emulator in window (not as standalone).
2. Download and install Flutter and Dart plugins inside Android Studio.
3. Download and unpack Flutter (version 2.2.0). Run Flutter doctor, accept Android licenses.
4. Open new Flutter project in Android Studio: **no new tools (no database inspector, no emulator window, no profiler) - bottom toolbar reports 6 Problems but doesn't show them (this happens when opening a regular Android project page also)**
5. Run Flutter doctor: all good except **Android Studio not found**
6. Run flutter config --android-studio-dir="path to your directory" (tipically on Windows 10 "C:\Program Files\Android\Android Studio")
7. As per **years ago** it doesn't see the plugins (Flutter and Dart) but now also says **Android licenses status unknown**
8. Running flutter doctor --android-licenses produces an error

## Logs
**As per step 5:**
![install-android-studio-not-found](https://user-images.githubusercontent.com/48123940/118908510-24c1bc80-b954-11eb-988f-b603c64f2911.jpg)
**As per step 7 (after running flutter config --android-studio-dir="path to your directory") :**
![install-after-android-studio-dir](https://user-images.githubusercontent.com/48123940/118908433-05c32a80-b954-11eb-9023-2b2957f6d65e.jpg)
**As per step 8:**
![install-android-studio-licenses-cannot-be-accepted](https://user-images.githubusercontent.com/48123940/118908832-b0d3e400-b954-11eb-9551-48bbe105da4a.jpg)
##Android Studio
**As per step 1 (Android project, all tools available, 6 Problems):**
![android-studio-new-tools-and-problems](https://user-images.githubusercontent.com/48123940/118912354-4160f300-b95a-11eb-8b02-d6bed809ea68.jpg)
**As per step 4 (Flutter project, no new tools, 6 Problems):**
![android-studio-no-new-tools-and-problems](https://user-images.githubusercontent.com/48123940/118912566-8e44c980-b95a-11eb-9daf-4c5383196765.jpg)

If I revert to step 5 (running android dir empty and getting Android Studio not found in Flutter doctor) and open a new Flutter project I can (apparently) build an app, but I don't have database inspector, emulator window (I'm forced to open the emulator as standalone and it does the **old ADB not found dialog**, these are all oldoldold issues) or profiler. And I always have the 6 mysterious Problems...

I can see that it finds Java in different locations according to the fact that it finds Android Studio or not. 

I haven't found anything online yet about all this and I'm surprised. I hope someone will find the time to explain what's going on.

Thanks

**P.S.**
I tried with Flutter on the same hard drive as AndroidStudio (C:\Users\User\flutter). Same results. 
I'm beginning to think that I could fix it if I knew how to tell Flutter to accept the android licenses on the Java at C:\Program Files\Android\Android Studio\jre\bin\java
Flutter is accepting them on Java at C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
I don't know about the missing tools, maybe it has to do with the **workspace.xml** file
No idea what the 6 mysterious Problems are...

**Comment by TahaTesser** [comment] 2021-05-20 10:07
Hu @emru67 
This is a known issue, you need to install [this](https://stackoverflow.com/a/64162776) 

Closing as duplicate of https://github.com/flutter/flutter/issues/80273
Thank you

**Closed by TahaTesser** 2021-05-20 10:07 UTC
Labels: in triage

**Comment by emru67** [comment] 2021-05-21 02:05
Thank you @TahaTesser 
downloading Android SDK command line tools fixed the detection and licenses problems.

But I still have **no database inspector, profiler and emulator tool window**.
The emulator on start still gives me the ADB not found dialog.

**Comment by TahaTesser** [comment] 2021-05-26 12:01
> But I still have no database inspector, profiler and emulator tool window.

This is not related to Flutter 

> The emulator on start still gives me the ADB not found dialog.

Also not related to Flutter

Open the Project window and select any Android API 

![Screenshot 2021-05-26 145918](https://user-images.githubusercontent.com/48603081/119656118-fdc32900-be32-11eb-9fad-1fee2c8a38f1.png)

**Comment by emru67** [comment] 2021-05-28 04:00
@TahaTesser thanks but I think this:

> But I still have no database inspector, profiler and emulator tool window

is a Flutter issue because if I open the android app inside the same project I get all the tools back. When I go back to Flutter they disappear again.

**Comment by TahaTesser** [comment] 2021-05-28 12:03
@emru67 
You're using Android Studio/Intellij, it uses Flutter plugins, please file an issue plugin side, Flutter doesn't decide what tools would show in the IDE
