### ISSUE TITLE
FocusNode onKey function is not called

### ISSUE THREAD

**Issue by snaeji** [flutter/flutter#83023] opened 2021-05-20 15:44 UTC
## Steps to Reproduce

<details>
  <summary>Minimal code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.select): const ActivateIntent(),
      },
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Row(
          children: [
            MainImageBox(key: ValueKey('asdf')),
          ],
        ),
      ),
    );
  }
}

class MainImageBox extends StatefulWidget {
  const MainImageBox({required Key key}) : super(key: key);

  @override
  _MainImageBoxState createState() => _MainImageBoxState();
}

class _MainImageBoxState extends State<MainImageBox> {
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode(onKey: handleKey);
  }

  bool handleKey(FocusNode focusNode, RawKeyEvent key) {
    print("handleKey function called");
    return false;
  }

  @override
  Widget build(BuildContext context) {
    return RawMaterialButton(
      focusNode: focusNode,
      focusColor: Colors.transparent,
      splashColor: Colors.transparent,
      onPressed: () async {
        print('press');
      },
      child: Container(
        color: Colors.green,
        width: 230,
        padding: EdgeInsets.fromLTRB(5.0, 0.0, 5.0, 0.0),
      ),
    );
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }
}

```

</details>

1. Run `Minimal code sample`.
2. Move focus around with arrow keys

**Expected results:** 
FocusNode onKey function should be called

**Actual results:** 
onKey function is not called

Works on Flutter 2.0.2 but not 2.2

<details>
  <summary>Logs</summary>

```
➜  onkey flutter analyze
Analyzing onkey...                                                      
No issues found! (ran in 2.9s)
➜  onkey 

```

```
➜  onkey flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/snaebjorn/development/flutter
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/snaebjorn/Library/Android/sdk
    • Platform android-S, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    ! Error: Living Room is not connected. Xcode will continue when Living Room is connected. (code -13)
    ! Error: Living Room is not connected. Xcode will continue when Living Room is connected. (code -13)
    ! Error: Auglysingadeild4thgen is not connected. Xcode will continue when Auglysingadeild4thgen is connected. (code -13)
    ! Error: Snaeji is not connected. Xcode will continue when Snaeji is connected. (code -13)

! Doctor found issues in 1 category.
➜  onkey 

```

</details>

**Comment by TahaTesser** [comment] 2021-05-21 13:47
Hi @snaeji 
Thanks for filing the issue

FocusNode [onKey](https://api.flutter.dev/flutter/widgets/FocusNode/onKey.html) mentiones it received while FocusNode is focused. 

Using the code sample below, requesting, yet onKey is not called 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter - flutter/issues/#67915',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter - flutter/issues/#67915'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _keyboardListenerFocus = FocusNode(
    onKey: (_,__){
        print('onKey called');
    }
  );
  String? _keyName = 'N/A';
  bool _listenerActive = false;

  @override
  void initState() {
    super.initState();


    _keyboardListenerFocus.addListener(() {
      setState(() => _listenerActive = _keyboardListenerFocus.hasFocus);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Plain TextField:'),
            Container(width: 200, child: TextField()),
            SizedBox(height: 50),
            Text('Tap the green container to focus the RawKeyboardListener:'),
            SizedBox(height: 5),
            GestureDetector(
              onTap: () => _keyboardListenerFocus.requestFocus(),
              child: Container(
                width: 200,
                height: 100,
                color: _listenerActive ? Colors.lightGreen : Colors.green,
                alignment: Alignment.center,
                child: RawKeyboardListener(
                  focusNode: _keyboardListenerFocus,
                  onKey: (keyEvent) => setState(
                      () => _keyName = keyEvent.data.logicalKey.debugName),
                  child: _listenerActive
                      ? Text(
                          'Listener focused!\nPress some keys.\nkeyName = $_keyName',
                          textAlign: TextAlign.center,
                        )
                      : Text(
                          'Listener not focused\nTap here to focus\n',
                          textAlign: TextAlign.center,
                        ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _keyboardListenerFocus.dispose();

    super.dispose();
  }
}
``` 

</details>


Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  reproduced |   reproduced | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.3.1 20E241
      darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      90.0.4430.212

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.87, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-13.0.pre.87 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d6a925326 (9 hours ago), 2021-05-21 01:09:02 -0400
    • Engine revision 20260fb95f
    • Dart version 2.14.0 (build 2.14.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.3.1 20E241
      darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      90.0.4430.212

• No issues found!
```
		
</details>

**Comment by gspencergoog** [comment] 2021-05-24 15:58
Ideally, `FocusNode.onKey` should be avoided when using focus nodes with `Focus` widgets (and the same is true for all callbacks set on FocusNode when using them with Focus). The `Focus` widget should really be the one managing the attributes of the `FocusNode`, and the only thing that you would ever need to call on the focus node directly is `requestFocus`.

If you want to do what I think you want to do, you could use this build function instead, and just introduce a new `Focus` widget that would manage the node:

```dart
  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: handleKey,
      child: RawMaterialButton(
        focusColor: Colors.transparent,
        splashColor: Colors.transparent,
        onPressed: () async {
          print('press');
        },
        child: Container(
          color: Colors.green,
          width: 230,
          padding: EdgeInsets.fromLTRB(5.0, 0.0, 5.0, 0.0),
        ),
      ),
    );
  }
```

This would also mean that your widget could be stateless.

**Comment by xu-baolin** [comment] 2021-05-24 16:22
The root cause of this issue is that the `RawKeyboardListener` widget introduces a `Focus` widget without setting the `onKey` callback.
https://github.com/flutter/flutter/blob/53a99a408d03a96762cfeb841ba02a4ec524b3a5/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart#L129

**Comment by xu-baolin** [comment] 2021-05-24 16:36
> The root cause of this issue is that the `RawKeyboardListener` widget introduces a `Focus` widget without setting the `onKey` callback.
> 
> https://github.com/flutter/flutter/blob/53a99a408d03a96762cfeb841ba02a4ec524b3a5/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart#L129

Update,
I used @TahaTesser 's sample code. https://github.com/flutter/flutter/issues/83023#issuecomment-845962253

**Comment by gspencergoog** [comment] 2021-05-24 16:42
OK, in that case, it looks like the `RawKeyboardListener` just needs to be rewritten to set the `onKey` on the Focus widget it has, which would even allow it to be a stateless widget too. Really, that class is a relic anyhow, and most apps want to use a `Focus` node instead.

**Comment by snaeji** [comment] 2021-05-25 00:29
Thanks @xu-baolin and @gspencergoog for the help! Everything works after migrating to the Focus widget like suggested 👌

**Comment by LongCatIsLooong** [comment] 2021-09-26 02:37
#90684 failed an internal test because `FocusNode.onKey` was erased by the `Focus` widget it attaches to.

@gspencergoog For leaf widgets that take a `FocusNode` (`TextField` & `EdtitableText` for example), configuring the internal `Focus` will be unfeasible. Does it make sense if we introduce a new `Focus.withExternalFocusNode` constructor that does not have `onKey`, `onKeyEvent` or `debugLabel`, and deprecate the `focusNode` argument in the unnamed constructor? If the developer brought their own `FocusNode` then with the new constructor the `Focus` widget won't mess with the existing configuration specified in `FocusNode`.

**Comment by gspencergoog** [comment] 2021-09-27 18:35
Hmm, that's a nice idea.  I'll see if I can put that together.

Someday, I'd like to deprecate even the `Focus.withExternalFocusNode` constructor and make the `FocusNode` interface as private as possible (would probably still need to have `requestFocus` be public). It's complicated and error-prone to manage the focus nodes manually.

**Comment by gspencergoog** [comment] 2021-09-28 00:20
OK, check out https://github.com/flutter/flutter/pull/90843 and see if that helps.

**Comment by goderbauer** [comment] 2022-04-20 22:21
(Triage) @gspencergoog Does https://github.com/flutter/flutter/pull/90843 resolve this issue or is there more to do? If it's resolved, let's close this issue.

**Comment by gspencergoog** [comment] 2022-04-20 23:48
I think it's resolved.

**Closed by gspencergoog** 2022-04-20 23:48 UTC
Labels: waiting for customer response, framework, waiting for PR to land (fixed), f: focus, has reproducible steps, found in release: 2.2, found in release: 2.3
