### ISSUE TITLE
TabBar indicator animation glitch when tapping TabBarView child before return animation completes

### ISSUE THREAD

**Issue by mirza-s** [flutter/flutter#17739] opened 2018-05-19 08:06 UTC
## Steps to Reproduce
1. Create a TabBar with 3 tabs
2. Drag side to side under the threshold of switching between tabs
3. During the return animation, one-time tap the area where the drag was started from
4. The indicator jumps to the next tab and returns to the actually selected tab

![Image](https://media.giphy.com/media/2A6YndcZfmUSFmZcRw/giphy.gif)

```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-BA)
    • Flutter version 0.3.2 at /Users/mbp/flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mbp/Library/Android/sdk
    • Android NDK at /Users/mbp/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/mbp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • iPhone X • F3AB43D1-1EE1-4093-A92C-7AAEBDCA2638 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by zoechi** [comment] 2019-01-29 16:49
Are you still seeing this. I think this was fixed. I was not able to reproduce in the Gallery app.

**Comment by mirza-s** [comment] 2019-01-31 14:55
Hi, I will give it a try and let you know.

**Comment by zoechi** [comment] 2019-01-31 15:48
Thanks for the update. Closing then.
Feel free to add a comment to have it reopened if you see it again.

**Closed by zoechi** 2019-01-31 15:48 UTC
Labels: f: material design, framework
