### ISSUE TITLE
[bug] TextField context menu overflow

### ISSUE THREAD

**Issue by Sp4Rx** [flutter/flutter#37388] opened 2019-08-01 11:53 UTC
## Steps to Reproduce

Write a long text and select a **word**. If its a small sceen phone the context menu will overflow.
See screenshot :
![TextField context menu overflow](https://i.imgur.com/1w5ys2o.jpg)
### Flutter doctor

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-IN)
    • Flutter version 1.7.8+hotfix.3 at C:\Users\heysu\Documents\flutter
    • Framework revision b712a172f9 (3 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\heysu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\heysu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi Note 4 • 46e8c6c00504 • android-arm64 • Android 7.0 (API 24)

• No issues found!

```

**Comment by justinmc** [comment] 2019-08-01 16:05
Closing as a duplicate of https://github.com/flutter/flutter/issues/35826.

Thanks for reporting this though, I really want to work on this soon and it's useful to see so many people are encountering it.  I plan to add a dropdown for overflowing items in Android, as native does.

**Closed by justinmc** 2019-08-01 16:05 UTC
Labels: f: material design, framework

**Comment by Thomaslay7** [comment] 2019-08-05 07:26
same issue
