### ISSUE TITLE
Autofill support in Flutter

### ISSUE THREAD

**Issue by jcivelli-google** [flutter/flutter#49385] opened 2020-01-23 23:19 UTC
It would be good to have autofill support in Flutter apps.

To support the Android Autofill framework, Flutter should returning a virtual view hierarchy to the Android framework, see [here](https://developer.android.com/guide/topics/text/autofill-optimize#virtual) for more information.

Having support for Autofill hints would provide a way for developers to indicate to the Autofill service the types of the input fields. The list of existing hints on Android can be found [here](https://developer.android.com/reference/androidx/autofill/HintConstants) (and on iOS [here](https://developer.apple.com/documentation/uikit/uitextcontenttype)).

Having a stable unique identifier (stable for a specific version of an app on any device) for fields and forms provided to the Autofill service would be extremely useful for features like crowdsourcing.

**Comment by dnfield** [comment] 2020-01-24 08:52
Duplicate of https://github.com/flutter/flutter/issues/13015

**Closed by dnfield** 2020-01-24 08:52 UTC

**Comment by justinmc** [comment] 2020-01-25 00:11
Hey @jcivelli-google, you, me, and a few others were talking about supporting autofill yesterday.  Sorry this got closed as a duplicate immediately.  Let's focus discussion over on https://github.com/flutter/flutter/issues/13015.  I'm going to write a big comment over there with all of the info from this issue and any other info we have, and we can go from there.

**Comment by LongCatIsLooong** [comment] 2020-02-27 00:01
Hi @jcivelli-google, could you elaborate a bit more on this "stable unique id", and how we can supply this id to autofill services on Android? Should we put this id in [`AutofillId`](https://developer.android.com/reference/kotlin/android/view/autofill/AutofillId)?

**Comment by mdebbar** [comment] 2020-02-27 18:35
> extremely useful for features like crowdsourcing.

I'm not sure what is meant by crowdsourcing here. Would you mind explaining? Ideally, we would like to avoid asking developers to supply a unique, stable id for each text field.

**Comment by jcivelli-google** [comment] 2020-02-27 23:10
Autofill with Google uses "signatures" (hash of some properties of a node)
to uniquely identify a node. This is useful in several cases, one of which
is crowdsourcing, where detection results performed on one device can be
used to detect that same field on other devices.
There are several cases in Autofill with Google where we used these
signatures.
One example would be, if a user forces autofill a password in a field that
Autofill hasn't detected correctly, it's a strong signal that that field is
of type password. (you can force autofill by long pressing in a field and
selecting "autofill").
If we have a signature for that field, we can send that mapping "field
signature -> PASSWORD" to a server and serve it down to other clients so
that if a user uses the same app, that field is detected properly as a
password.
What we have seen with some ReactNative apps is that the ViewNodes can have
very few parameters set on them, so when hash we may end up with conflicts:
different fields across different forms having the same signatures.
Having Flutter provide a stable and distinct ID for every field in the same
version of an app would be very helpful, as it would hopefully help limit
signature conflicts.
I was thinking that the Flutter framework could use some data not made
available in the AssistStructure.ViewNode to compute a unique ID. I think
at some point someone mentioned using the hash of the class file (or
Flutter equivalent) where the layout is created, I could be totally wrong.

I don't think the AutofillId is the right place for that signature.
Having it in the extras
<https://developer.android.com/reference/android/app/assist/AssistStructure.ViewNode#getExtras()>
of the node may be an idea.

**Comment by jcivelli-google** [comment] 2020-02-27 23:12
See my explanation for crowdsourcing in the comment above.
The ID I am talking about wouldn't be specified by the developper, but by
the Flutter framework.
