### ISSUE TITLE
Images used in iOS library are not displayed

### ISSUE THREAD

**Issue by tdc-w** [flutter/flutter#58749] opened 2020-06-05 03:36 UTC
There is an iOS library that has icon images in Assets.xcassets.
I'm developing a Flutter app that uses this library.

Until now, I used Flutter `1.12.13+hotfix.8` channel stable, 
and the image of the library was displayed normally.

However, after upgrading to Flutter `1.17.2` channel stable and running it, 
the images in the library are no longer displayed.
I am confused about the cause and solution for this.

This issue is related.
https://github.com/flutter/flutter/issues/58232

The images is displayed when adding `resources` to podspec of iOS library.
```
s.resource_bundles = {'Library' => ['Assets.xcassets','Resource.bundle','Sources/**/*.{xib,storyboard}']}
s.resources = ['Assets.xcassets']
```
But this iOS library is also used by React Native app, and using `resources` will affect React Native side.
https://github.com/CocoaPods/CocoaPods/issues/8431

I would like to solve the problem using only `resource_bundles` instead of `resources`.
If you know any solution, please let me know.
Thank you.

**Comment by iapicca** [comment] 2020-06-05 08:15
Hi @tdc-w 
the issue appears to be very similar indeed 
did the proposed [solution](https://github.com/flutter/flutter/issues/58232#issuecomment-635896175) worked for you?

If it didn't, like as in the referred [issue](https://github.com/flutter/flutter/issues/58232#issuecomment-635870961), could you please provide a reproducible minimal code sample?
Thank you

**Comment by tdc-w** [comment] 2020-06-05 12:56
Hi @iapicca 
Thank you for your reply.

The solution seems to work for Flutter, but the problem is not solved because it affects React Native app.

A sample is here.
https://github.com/tdc-w/flutter_sample

When the screen of the library is displayed and the image is displayed normally, the card brand logo etc. are displayed as shown in the screenshot.
https://github.com/payjp/payjp-ios

The images were displayed normally with Flutter 1.12.13+hotfix.9, 
so I'm wondering if there was any modification in the processing around Bundle of iOS on Flutter side.
Is there any information?

**Comment by tdc-w** [comment] 2020-06-08 03:04
After adding App.framwork to Link Binary With Libraries, images are displayed correctly.

<img width="949" alt="スクリーンショット 2020-06-08 11 47 11" src="https://user-images.githubusercontent.com/38201241/83988812-65146e80-a97f-11ea-9282-2f5ab0c4bfcf.png">

After reading this(https://flutter.dev/docs/development/ios-project-migration), 
the above steps seemed incorrect, what do you think?

**Comment by iapicca** [comment] 2020-06-08 06:36
Hi @...
From what I can see, the issue is related to a [3rd party plugin](https://pub.dev/packages/payjp_flutter) rather than to Flutter itself. 
Please open the issue in the dedicated [repository](https://github.com/payjp/payjp-flutter-plugin/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, 
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-08 06:36 UTC
Labels: in triage

**Comment by tdc-w** [comment] 2020-06-09 08:09
Hi @iapicca 
This issue may be related.
https://github.com/flutter/flutter/issues/54586

After adding App.framework, I get a migration error when I run `flutter run` command.
```
Your Xcode project requires migration. See https://flutter.dev/docs/development/ios-project-migration for details.
Error launching application on iPhone 11.
```
But, the build succeeds when I run it on Xcode.

I will continue to investigate settings around the framework.
Thank you.
