### ISSUE TITLE
DropdownButton null selection no longer gets display using Flutter 2

### ISSUE THREAD

**Issue by incon** [flutter/flutter#77655] opened 2021-03-09 00:30 UTC
## Steps to Reproduce

DropdownButton `null` selection no longer gets display using Flutter 2

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Downdown Menu Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyDropdownMenu(),
    );
  }
}

class MyDropdownMenu extends StatefulWidget {
  @override
  _MyDropdownMenuState createState() => _MyDropdownMenuState();
}

class _MyDropdownMenuState extends State<MyDropdownMenu> {
  String _selection;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Downdown Menu'),
      ),
      body: Center(
        child: DropdownButton<String>(
          value: _selection,
          items: [
            DropdownMenuItem(
              child: Text('null'),
              value: null,
            ),
            DropdownMenuItem(
              child: Text('one'),
              value: 'one',
            ),
            DropdownMenuItem(
              child: Text('two'),
              value: 'two',
            ),
          ],
          onChanged: (String value) {
            setState(() {
              _selection = value;
            });
          },
        ),
      ),
    );
  }
}
```
</details>

Flutter 1.22.6
<img width="208" alt="Screen Shot 2021-03-09 at 8 24 39 am" src="https://user-images.githubusercontent.com/405629/110399770-5d6e2b80-80b1-11eb-8b24-3c57c04387fb.png">

Flutter 2.0.1
<img width="208" alt="Screen Shot 2021-03-09 at 8 27 21 am" src="https://user-images.githubusercontent.com/405629/110399810-74ad1900-80b1-11eb-923f-2d87ed54ce02.png">

Currently `{void Function(String?)? onChanged}` allows a `null` `DropdownMenuItem` item to be selection but isn't highlighted or displayed as selected.

Breaking Change: Flutter 2 no longer works correctly with a null valued item in items.

**Comment by SirusCodes** [comment] 2021-03-09 03:19
Do you really want to display null to users? It's better to keep a default value rather than a null.

**Comment by incon** [comment] 2021-03-09 05:06
'null' (text string) is just the tje example text description for the `null` value selection option.

**Comment by SirusCodes** [comment] 2021-03-09 05:18
Ya now I got a use case. If you don't want your user to select default(placeholder) value again.

**Comment by SirusCodes** [comment] 2021-03-09 05:24
> Ya now I got a use case. If you don't want your user to select default(placeholder) value again.

Just found out if you need this use case then you can use `hint` param
https://github.com/flutter/flutter/blob/638e39e668e37eeb7b6732e1e4d63a037ed7c94b/packages/flutter/lib/src/material/dropdown.dart#L886

**Comment by SirusCodes** [comment] 2021-03-09 05:28
> Ya now I got a use case. If you don't want your user to select default(placeholder) value again.

I guess if you want a placeholder you can use `hint` param?
https://github.com/flutter/flutter/blob/638e39e668e37eeb7b6732e1e4d63a037ed7c94b/packages/flutter/lib/src/material/dropdown.dart#L886

**Comment by incon** [comment] 2021-03-09 05:50
In my current use case `null` is a valid selection option.
Using hint you're unable to select this option again if you select any of the items.

**Comment by SirusCodes** [comment] 2021-03-09 06:04
TBH I'm not able to think such a use case but I would suggest you to make an implementation of `Dropdown` yourself as if your PR gets merged it will take a lot of time for moving from master to stable or even beta...

**Comment by incon** [comment] 2021-03-09 06:21
I'm in the progress of updating an app to Flutter 2 and the backend is currently supplying and expecting `null` to be submitted. `null` is being used as `None`
It's a breaking change for `Dropdown`, I wonder how many other people have been affected by this change.

**Comment by incon** [comment] 2021-03-09 07:43
My current workaround
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Downdown Menu Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyDropdownMenu(),
    );
  }
}

class MyDropdownMenu extends StatefulWidget {
  @override
  _MyDropdownMenuState createState() => _MyDropdownMenuState();
}

class _MyDropdownMenuState extends State<MyDropdownMenu> {
  String? _selection;

  static const List<Map<String, String?>> _selections = [
    {
      'label': 'None',
      'value': null,
    },
    {
      'label': 'One',
      'value': 'one',
    },
    {
      'label': 'Two',
      'value': 'two',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Downdown Menu'),
      ),
      body: Center(
        child: DropdownButton<String>(
          value: _selection ?? '',
          items: _selections
              .map((selection) => DropdownMenuItem(
                    child: Text(selection['label']!),
                    value: selection['value'] ?? '',
                  ))
              .toList(),
          onChanged: (String? value) {
            setState(() {
              _selection = value;
            });
          },
        ),
      ),
    );
  }
}
```

**Comment by incon** [comment] 2021-03-09 08:23
Yes

**Comment by pedromassangocode** [comment] 2021-03-09 08:45
Hi @incon 
I think this is working as expect and the docs explicitly says so:

https://github.com/flutter/flutter/blob/698d4389604ef1f0fecda9c93cfba6a2e5d06a7d/packages/flutter/lib/src/material/dropdown.dart#L815-L816

If you want to show "null" you should pass it as a String: 

```dart
DropdownMenuItem(
    child: Text('null'),
    value: "null",         // null as a string
),
```

**Comment by incon** [comment] 2021-03-09 09:05
I'm wanting to keep passing a nullable type like I did before Flutter 2.

**Comment by SirusCodes** [comment] 2021-03-09 09:20
And it also wasn't mentioned in breaking change

> Hi @incon
> I think this is working as expect and the docs explicitly says so:
> 
> https://github.com/flutter/flutter/blob/698d4389604ef1f0fecda9c93cfba6a2e5d06a7d/packages/flutter/lib/src/material/dropdown.dart#L815-L816
> 
> If you want to show "null" you should pass it as a String:
> 
> ```dart
> DropdownMenuItem(
>     child: Text('null'),
>     value: "null",         // null as a string
> ),
> ```

`DropdownItem.value` shouldn't be nullable if you can't pass null to it.
And I feel it should be documented as breaking change as it will not work as expected.

**Comment by incon** [comment] 2021-03-09 09:22
Why is `{void Function(String?)? onChanged}` nullable if you shouldn't have a `null` item to select?

**Comment by incon** [comment] 2021-03-09 09:28
`DropdownMenuItem` currently allows `null`

https://github.com/flutter/flutter/blob/698d4389604ef1f0fecda9c93cfba6a2e5d06a7d/packages/flutter/lib/src/material/dropdown.dart#L702-L705

**Comment by SirusCodes** [comment] 2021-03-09 09:28
If you are talking about `String?` then it is because of `DropdownMenuItem.value` is nullable.
`Function(String?)?` is nullable since passing null to will mark dropdown as disabled.

**Comment by incon** [comment] 2021-03-09 09:35
```dart
DropdownButton<String>(
  // Selected item and is .value null
  value: null,
  ....
 )
 ```
 
 ```dart
 DropdownMenuItem(
  child: Text('Please show me as selected'),
  // Allows .value to be null
  value: null,
)
 ```

https://github.com/flutter/flutter/blob/698d4389604ef1f0fecda9c93cfba6a2e5d06a7d/packages/flutter/lib/src/material/dropdown.dart#L702-L705
 
Flutter <2 shows selected
Flutter >2 doesn't

**Comment by pedromassangocode** [comment] 2021-03-09 13:44
> True either `value` should be non-nullable or it should react to null 🤔 as it was expected before

This is a long thread and was already discussed before, please see https://github.com/flutter/flutter/issues/56725#issuecomment-628160352.

Cc @shihaohong  (because you wrote https://github.com/flutter/flutter/issues/56725#issuecomment-628160352) maybe you have some input for this.

**Comment by shihaohong** [comment] 2021-03-15 02:21
I agree that this should not be a breaking change, and if it were, it should be properly documented. I left a comment on the PR you submitted, but there are some failing tests that need to be fixed, and a new test should be added to prevent a future regression.

**Closed** 2021-03-16 01:35 UTC
Labels: a: null-safety, f: material design, found in release: 2.0, found in release: 2.1, framework, has reproducible steps, severe: regression

**Comment by davidmartos96** [comment] 2021-03-16 13:23
@incon  I've encountered with this issue the other day, and I changed a bit how I handle those nullable dropdown values. 
If you need a working solution before the PR reaches the stable branch, you can make us of the `Option` type from the `dartz` package,  which is a way to represent that something can have a value or not without using null.

```dart
import 'package:dartz/dartz.dart' show Option, None, Some, optionOf;

int? dropdownValue;

DropdownButton<Option<int>>(
    // This here converts a nullable value into a some(v) or a none()
    value: optionOf(dropdownValue), 
    items: [
      DropdownMenuItem(
        value: const None(),
        child: Text("Nothing here"),
      ),
      DropdownMenuItem(
        value: const Some(1),
        child: Text("Option 1"),
      ),
      DropdownMenuItem(
        value: const Some(2),
        child: Text("Option 2"),
      ),
    ],
    onChanged: (v) {
      setState(() {
        // This here takes the wrapped value from inside the `some` or null if it is `none`
        dropdownValue = v | null;
      });
    },
),
```

**Comment by nt4f04uNd** [comment] 2021-03-17 03:27
@pedromassangocode wrong r: i guess

**Comment by peterweb2005** [comment] 2021-04-01 22:33
there may also:

'Null' is not a subtype of type 'FutureOr<_DropdownRouteResult<String?>>'
