### ISSUE TITLE
url_launcher experiences exception with certain urls 

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#14321] opened 2018-01-29 06:31 UTC
The demo app below launches a url to show a web page. In the iOS Simulator, it throws an exception for certain urls, but not others.

For example, this url (http://www.bbc.com/news/technology-42853072) works fine, but this url (http://www.bbc.co.uk/news/entertainment-arts-42855097) throws the following:

```
PlatformException(Error, Error while launching http://www.bbc.co.uk/news/entertainment-arts-42855097, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:47:19)
#3      MyHomePage._launchUrl (/Users/.../CoreSimulator/Devices/02C18B63-A9EC-47B9-A9FC-BC517BF11D46/data/Containers/Data/Application/63A1AD8D-CA1A-43F3-BD82-30267BB88D05/tmp/app5V0OVz/app/lib/main.dart:47:13)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureReco<…>
```

Demo app:

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';


void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(
        title: 'URL Launch Tester',
        // url: 'http://www.bbc.com/news/technology-42853072', // Working URL
        url: 'http://www.bbc.co.uk/news/entertainment-arts-42855097', // Exception URL
      )
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title, this.url}) : super(key: key);

  final String title;
  final String url;

   Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(title),
      ),
      body: new Center(
        child: new RaisedButton(
          child: new Text('Click me'),
          onPressed: _launchUrl,
        ),
      ),
    );
  }

  _launchUrl() async {
    if (await canLaunch(url)) {
      await launch(url, forceWebView: true);
    } else {
      throw 'Could not launch $url';
    }
  }
}
```

**Comment by chuihinwai** [comment] 2018-03-05 08:34
@mjohnsullivan 

I have luck with `Uri.encodeFull()`

This doesn't work:
```
launch('https://www.google.com/maps/search/?api=1&query=${some interpolated address}');
```

Wrapping it around `encodeFull` does:
```
launch(Uri.encodeFull('https://www.google.com/maps/search/?api=1&query=${some interpolated address}'))
```

**Comment by cyanglaz** [comment] 2019-03-05 22:57
@mjohnsullivan The example code you provided seems to be working. Are you still facing similar issues with the url_launcher?

**Comment by cyanglaz** [comment] 2019-05-03 15:38
Sorry that we have to close this issue because we couldn't gather enough details to proceed. If anyone found the same issue and can provide detailed step to reproduce, please feel empowered to open another issue with details!.

**Closed by cyanglaz** 2019-05-03 15:38 UTC
Labels: p: first party, p: url_launcher, plugin, severe: crash, waiting for customer response

**Comment by ivanesi** [comment] 2020-01-16 08:47
I faced this issue using `url_launcher: ^5.4.1`

```
void _launchUrl(String url) async {
    final encodedUrl = Uri.encodeFull(url);
    if (await canLaunch(encodedUrl)) {
      await launch(encodedUrl);
    } else {
      throw 'Could not launch $encodedUrl';
    }
  }
```

got:
```
Exception has occurred.
PlatformException (PlatformException(Error, Error while launching http://apps.apple.com/app/id1482374845, null))
```

**Comment by fransiskapw** [comment] 2020-12-05 05:33
I faced the same issue for certain phone types - iPhone 8 & iPhone SE 2, but only on real device. It works well in the simulator
