### ISSUE TITLE
Windows build bot is flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#18699] opened 2018-06-21 23:06 UTC
The following log is copied from https://build.chromium.org/p/client.flutter/builders/Windows/builds/3583
```
00:48 +560 ~4: E:\b\build\slave\Windows\build\flutter\packages\flutter\test\material\date_picker_test.dart: showDatePicker tap-select a day                                                            
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderPadding class returned values that violate the
intrinsic protocol contract.
The following failure was detected:
 * getMinIntrinsicHeight(Infinity) returned a larger value (40.0) than
   getMaxIntrinsicHeight(Infinity) (24.0)
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1777:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1787:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1507:17)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1507:65)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:202:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#6      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#20     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:559:15)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#22     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#27     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#29     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:479:13)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#47     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#64     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2818:13)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#66     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#68     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#80     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
#81     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
#82     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
#83     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:756:23)
#84     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#85     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#86     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#87     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:667:9)
#90     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#91     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:654:27)
#92     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:224:22)
#95     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#96     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:221:27)
#97     _tests.<anonymous closure> (file:///E:/b/build/slave/Windows/build/flutter/packages/flutter/test/material/date_picker_test.dart:42:18)
#99     _tests.<anonymous closure> (file:///E:/b/build/slave/Windows/build/flutter/packages/flutter/test/material/date_picker_test.dart:38:35)
#100    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:69:23)
#101    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:518:19)
#115    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:862:17)
#117    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:850:39)
(elided 34 frames from class _FakeAsync, package dart:async, and package stack_trace)

The following RenderObject was being processed when the exception was fired:
  RenderPadding#159f5 relayoutBoundary=up8 NEEDS-PAINT
  creator: Padding ← ConstrainedBox ← Semantics ← Semantics ← Listener ← RawGestureDetector ←
  GestureDetector ← Tooltip ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ←
  ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(48.0<=w<=Infinity, 48.0<=h<=Infinity)
  size: Size(48.0, 48.0)
  padding: EdgeInsets.all(8.0)
  textDirection: ltr
This RenderObject had the following descendants (showing up to depth 5):
  RenderConstrainedBox#a35c0 relayoutBoundary=up9 NEEDS-PAINT
    RenderPositionedBox#40d0e NEEDS-PAINT
      RenderSemanticsAnnotations#6769d relayoutBoundary=up1 NEEDS-PAINT
        RenderExcludeSemantics#ddf62 relayoutBoundary=up2 NEEDS-PAINT
          RenderConstrainedBox#2aa1e relayoutBoundary=up3 NEEDS-PAINT
```

**Comment by DanTup** [comment] 2018-07-19 10:05
Seen on AppVeyor just now:

https://ci.appveyor.com/project/flutter/flutter/build/1.0.15383

I'm restarting, so not sure if that link will work, not sure if you can get logs of previous attempts of a same build on AppVeyor so here's the first instance from the log:

```
[00:13:03] 06:03 +1888 ~25: C:\projects\flutter sdk\packages\flutter\test\widgets\drawer_test.dart: Drawer drag cancel resume (RTL)                                                                               
[00:13:03] 06:03 +1889 ~25: loading C:\projects\flutter sdk\packages\flutter\test\widgets\editable_text_show_on_screen_test.dart                                                                                  
[00:13:03] 06:03 +1889 ~25: C:\projects\flutter sdk\packages\flutter\test\widgets\drawer_test.dart: Drawer navigator back button                                                                                  
[00:13:03] 06:04 +1889 ~25: C:\projects\flutter sdk\packages\flutter\test\widgets\drawer_test.dart: Drawer navigator back button                                                                                  
[00:13:03] 06:04 +1889 ~25: C:\projects\flutter sdk\packages\flutter\test\widgets\drawer_test.dart: Drawer navigator back button                                                                                  
[00:13:03] ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[00:13:03] The following assertion was thrown during performLayout():
[00:13:03] The intrinsic dimension methods of the RenderPadding class returned values that violate the
[00:13:03] intrinsic protocol contract.
[00:13:03] The following failures was detected:
[00:13:03]  * getMinIntrinsicWidth(Infinity) returned a larger value (116.0) than
[00:13:03]    getMaxIntrinsicWidth(Infinity) (84.0)
[00:13:03]  * getMinIntrinsicWidth(800.0) returned a larger value (116.0) than getMaxIntrinsicWidth(800.0)
[00:13:03]    (84.0)
[00:13:03] If you are not writing your own RenderBox subclass, then this is not
[00:13:03] your fault. Contact support: https://github.com/flutter/flutter/issues/new
[00:13:03] 
[00:13:03] When the exception was thrown, this was the stack:
[00:13:03] #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1823:11)
[00:13:03] #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1833:6)
[00:13:03] #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1553:17)
[00:13:03] #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1553:65)
[00:13:03] #4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:202:5)
[00:13:03] #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1147:11)
[00:13:03] #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #17     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:263:13)
[00:13:03] #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #19     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
[00:13:03] #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #21     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:263:13)
[00:13:03] #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #25     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
[00:13:03] #26     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
[00:13:03] #27     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
[00:13:03] #28     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
[00:13:03] #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #33     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1147:11)
[00:13:03] #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #50     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2824:13)
[00:13:03] #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #52     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
[00:13:03] #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #54     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
[00:13:03] #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
[00:13:03] #66     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
[00:13:03] #67     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
[00:13:03] #68     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
[00:13:03] #69     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:793:23)
[00:13:03] #70     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[00:13:03] #71     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[00:13:03] #72     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[00:13:03] #73     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:704:9)
[00:13:03] #76     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
[00:13:03] #77     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:691:27)
[00:13:03] #78     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:227:22)
[00:13:03] #81     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
[00:13:03] #82     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:224:27)
[00:13:03] #83     main.<anonymous closure> (file:///C:/projects/flutter%20sdk/packages/flutter/test/widgets/drawer_test.dart:187:18)
[00:13:03] #85     main.<anonymous closure> (file:///C:/projects/flutter%20sdk/packages/flutter/test/widgets/drawer_test.dart:183:47)
[00:13:03] #86     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:72:23)
[00:13:03] #87     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:555:19)
[00:13:03] #101    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:899:17)
[00:13:03] #103    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:887:39)
[00:13:03] (elided 34 frames from class _FakeAsync, package dart:async, and package stack_trace)
[00:13:03] 
[00:13:03] The following RenderObject was being processed when the exception was fired:
[00:13:03]   RenderPadding#3c378 relayoutBoundary=up10 NEEDS-PAINT
[00:13:03]   creator: Padding ← Container ← IconTheme ← Builder ← Listener ← _GestureSemantics ←
[00:13:03]   RawGestureDetector ← GestureDetector ← InkWell ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
[00:13:03]   _InkFeatures-[GlobalKey#3dcaf ink renderer] ← ⋯
[00:13:03]   parentData: <none> (can use size)
[00:13:03]   constraints: BoxConstraints(88.0<=w<=800.0, 36.0<=h<=600.0)
[00:13:03]   size: Size(116.0, 36.0)
[00:13:03]   padding: EdgeInsets(16.0, 0.0, 16.0, 0.0)
[00:13:03]   textDirection: ltr
[00:13:03] This RenderObject had the following descendants (showing up to depth 5):
[00:13:03]   RenderPositionedBox#e7cd9 relayoutBoundary=up11 NEEDS-PAINT
[00:13:03]     RenderParagraph#a1d32 relayoutBoundary=up12 NEEDS-PAINT
```

**Comment by Hixie** [comment] 2018-08-04 00:14
Dupe of https://github.com/flutter/flutter/issues/19696

**Closed by Hixie** 2018-08-04 00:14 UTC
Labels: team: flakes
