### ISSUE TITLE
Scroll and Swipe are not working in flutter 2.5 (Web)

### ISSUE THREAD

**Issue by aliazimoshan** [flutter/flutter#90122] opened 2021-09-15 11:43 UTC
Hi,
 I update my flutter to 2.5,
The new version of flutter have problems with scroll and swap on the web,
First I work with ```carousel_slider: ^4.0.0``` and see I can not swap my images,
after that, I test ListView and PageView and face the same problems,
so I downgrade to version 2.2.3 and everything work fine,

**Comment by danagbemava-nc** [comment] 2021-09-15 11:49
Hi @aliazimoshan, this is the intended behaviour.
 
There was a breaking change with the way scrollables work in `flutter 2.5.0`. 

Please see the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) and let me know if it fixes your issue. 

Thank you

**Comment by aliazimoshan** [comment] 2021-09-15 12:01
@danagbemava-nc 
Thanks for your response,
I was not aware of these changes,
Aren't we in trouble when using a third-party package like carousel_slider?

**Comment by danagbemava-nc** [comment] 2021-09-15 12:37
@aliazimoshan, I don't think it will be an issue. 
You have more control over the gestures now, so if anything doesn't work the way you want it, you can customize it. I also believe that the package maintainers should be aware of these changes and will update their packages accordingly

**Comment by raviganwal** [comment] 2021-09-15 15:23
@danagbemava-nc thanks, now scroll works for me.

**Comment by danagbemava-nc** [comment] 2021-09-16 05:59
Closing based on [this comment](https://github.com/flutter/flutter/issues/90122#issuecomment-920119612).

**Closed** 2021-10-05 13:22 UTC
Labels: waiting for customer response, in triage
