### ISSUE TITLE
`flutter run` should fail if the initial cocoapods podspec repo hasn't been cloned instead of doing a 20 minute clone

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9580] opened 2017-04-25 16:13 UTC
Right now if you don't have cocoapods installed we will (silently) set it up for you as part of the `pod install` run as part of `flutter run`.  This first install can take 20 minutes. :/

It seems like it would be better to separate setup from running so we don't have a bad first-run experience.

```
%rm -rf ~/.cocoapods
%flutter run

Launching lib/main.dart on iPhone 6s in debug mode...
Running pod install...                                    
CoreSimulatorBridge: Getting container class internal daemon!
```

It's just hanging checking out cocoapods:
32981 ttys000    0:00.02 /usr/local/git/current/bin/git clone https://github.com/CocoaPods/Specs.git master --progress

I think a better experience would be to just fail instead of silently installing.  @mit-mit

**Comment by eseidelGoogle** [comment] 2017-04-25 16:14
I think this is in part that https://github.com/flutter/flutter/issues/8983 doesn't appear solved.

**Comment by eseidelGoogle** [comment] 2017-04-27 21:14
I was bit by this again today.  It's a really bad experience in intellij since it just prints
```
Launching lib/main.dart on iPhone 6s in debug mode...
```
There is a window which shows up with background tasks "pod install", but the user won't know what that is. :(

FYI @devoncarew

**Comment by devoncarew** [comment] 2017-04-27 21:22
Urk. I agree that we're better off failing the run (w/ good messaging), and having an explicit step to get cocoapods set up.

**Comment by eseidelGoogle** [comment] 2017-04-27 21:24
Actually intelliJ eventually gives up:
```
Launching lib/main.dart on iPhone 6s in debug mode...
Observatory connection never became ready.
Application finished.
```
So this is worse than I thought.  If you don't have cocaopods installed and flutter run, your runs will just eventually time out. :(

**Comment by mit-mit** [comment] 2017-04-27 21:25
Yes, we all agree. This *has* to be fixed. Just need to find someone who has cycles right now...

**Comment by eseidelGoogle** [comment] 2017-04-27 21:26
Just making it error out should be straightforward.  Maybe @xster could help?

**Comment by xster** [comment] 2017-04-27 22:21
Maybe we should just show a prompt and let the user decide:
```
> flutter run
[...]
we use cocoapods to automatically resolve iOS dependencies, would you like to install cocoapods now (Y/n)
```
```
(Y/n) y
Installing cocoapods, this may take minutes...
↳   downloading...
    configuring...
    wtv...

Resolving cocoapods dependencies...
Building...
```
```
(Y/n) n
cocoapods is needed to build the flutter app. You can install it by running `brew install blah`.
>
```

Showing prompts is probably a pattern we can expand more on with like #7863

**Comment by sethladd** [comment] 2017-04-27 22:37
If you do this (would you like to install cocoapods now (Y/n)) please help the user understand how to make the decision. If I saw that on my first run, I wouldn't know how to answer. :/

* What if I don't install cocapods now?
* Can I install it later?
* What's the impact if I choose Y or N?

**Comment by sethladd** [comment] 2017-04-27 22:39
How about this:

* Can we prompt to download cocoapods _when the user needs it_ ?

* If we detect the user needs cocoapods, and they don't have it, we error out, give them a nice message, and say "run flutter install cocoapods to get the hotness"

**Comment by jakobr-google** [comment] 2017-04-27 22:44
I don't think this is about installing CocoaPods, but about retrieving the
spec repo. If CocoaPods isn't installed, we just skip this step entirely.

I don't know if there's a reliable, stable way to check if the spec repo
has been downloaded, but that'd be what we'd have to check.

Initializing CocoaPods should be in our setup guide (run 'pod setup' to
download the specs), IIRC, so we could also add a doctor check for it.

tor. 27. apr. 2017 kl. 15.39 skrev Seth Ladd <notifications@github.com>:

**Comment by xster** [comment] 2017-04-27 22:49
Let's defer the reasoning for the dependency to #9035. We should do it generally regardless of timing.

**Comment by eseidelGoogle** [comment] 2017-04-27 22:54
`pod repo list` appears to say if there are repos or not?

**Comment by xster** [comment] 2017-04-29 01:00
Step took 12 minutes on my monster mac pro too :(
Just to make sure I'm listing this correctly in sequence:

During build/run
1. If the project being built isn't iOS, nothing to do [✓]
2. If the project being built doesn't have a Podfile, nothing to do [~]
    - Though today, `flutter create` makes a Podfile. Wonder if we can scope down further the amount of users exposed to that file until they start using plugins (#9686)
3. If the user doesn't have cocoapods installed, dump error and instructions and continue without resolving native dependencies [~]
    - Consequences not clear to the user (#9686, #9035)
4. If the user has cocoapods installed but never cloned the specs, dump error and instructions and continue without resolving native dependencies to stay consistent with 3
    - Not sure I trust `pod repo list`'s output's format. Probably safer to just check for `~/.cocoapods/repos/master`'s presence

In doctor
1. If the user doesn't have cocoapods, ask user to brew install and pod setup (i.e. clone) [✓]
2. If the user has cocoapods but doesn't have `~/.cocoapods/repos/master`, ask the user to pod setup [✗]
3. In both cases 1 and 2, explain inline that it's not mandatory to build and run but without it, plugins won't work [✗]
4. In the future #9035, move inline messaging 3 to something hierarchical to more clearly illustrate the cause-effect chain to the user [✗]

**Comment by xster** [comment] 2017-05-01 21:02
With the 3 PRs above:

During build/run
1. If the project being built isn't iOS, nothing to do [✓]
2. If the project being built doesn't have a flutter: plugin: in their pubspec, nothing to do [✓]
3. If the user doesn't have cocoapods installed, dump error and instructions and continue without resolving native dependencies [✓]
4. If the user has cocoapods installed but never cloned the specs, dump error and instructions and continue without resolving native dependencies to stay consistent with 3 [✓]

In doctor
1. If the user doesn't have cocoapods, ask user to brew install and pod setup (i.e. clone) [✓]
2. If the user has cocoapods but doesn't have `~/.cocoapods/repos/master`, ask the user to pod setup [✓]
3. In both cases 1 and 2, explain inline that it's not mandatory to build and run but without it, plugins won't work [✓]
4. In the future #9035, move inline messaging 3 to something hierarchical to more clearly illustrate the cause-effect chain to the user [✗]

**Comment by mit-mit** [comment] 2017-05-02 13:39
Thanks @xster, great improvements!

**Comment by mit-mit** [comment] 2017-05-02 13:40
One comment: I don't think that prompting is a good solution; we invoke Flutter tools also from IntelliJ, and while we do print the output to the console pane, that may be closed and thus the user won't see the prompt.

But also looks like we ended up not pursuing that approach?

**Comment by xster** [comment] 2017-05-02 18:35
ya, I didn't realize it took 10+ minutes on a beast machine. Let's skip the prompting for this scenario.

**Comment by jakobr-google** [comment] 2017-05-02 18:44
It's network I/O-bound, so the size of your machine doesn't really matter.
tir. 2. maj 2017 kl. 20.35 skrev xster <notifications@github.com>:

**Comment by eseidelGoogle** [comment] 2017-05-02 22:08
My impression is this is very close to resolved?  Is there more work to do here for M2?

**Comment by xster** [comment] 2017-05-02 22:51
Still need to un-revert #9701 then merge #9703. 
Should be good for Friday.

**Closed** 2017-05-03 22:18 UTC
Labels: dev: tool

**Comment by CharlesCleveJr** [comment] 2017-08-09 22:59
Has there been a fix for this issue?

**Comment by xster** [comment] 2017-08-09 23:34
@CharlesCleveJr, it's fixed in the sense that Flutter doesn't automatically and silently trigger a CocoaPods spec repo clone while building anymore. 

Though we nevertheless still have a dependency on CocoaPods and the spec repo still needs to be cloned. We provide a message asking the user to perform that step (`pod setup`) manually now.

**Comment by CharlesCleveJr** [comment] 2017-08-18 01:34
I'm still getting the "Observatory connection never became ready" notice.  I'm updated IntelliJ and run `pod setup`.  I'm attempting to run it on the iPhone 7 Plus simulator with Firebase packages and a Firebase GeoFire plugin.  Any other suggestions to get this to work.
