### ISSUE TITLE
[latest master][Impeller] widgets disappear too early during perspective animation

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#130613] opened 2023-07-14 19:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I upgraded to latest master and faced this issue.
Resolved by downgrading to 3.12.0 and pointing you to this version as a bug free reference.

I do apologise but at moment I cannot create a sample for this, but I thought this was worth a report.

- latest master (issue). Look at avatar and icons disappearing while they partially go off stage.
https://github.com/flutter/flutter/assets/53510751/8faf2222-3d7b-4555-8174-8f21ca58ceb6

- flutter v 3.12.0 (no issue)
https://github.com/flutter/flutter/assets/53510751/bffaa18d-1839-48f8-976d-8e81abd3e60b

### Expected results

Widget shouldn't be visible.

### Actual results

Widget get unmounted before they fully disappear from stage.

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.12.0, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
    ! Flutter version 3.12.0 on channel [user-branch] at /Users/delf/Development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by huycozy** [comment] 2023-07-17 07:32
Thanks for filing the issue, @delfme 
Please provide a sample code so the issue can be actionable with clear steps to reproduce it. And please also provide the output of `flutter doctor` on master channel as well.

**Comment by delfme** [comment] 2023-07-17 20:53
@huycozy unfortunately I cant. Just filed this in the hope you guys can narrow it down before master will diverge too much from v 3.12.0

**Comment by huycozy** [comment] 2023-07-18 05:14
There are multiple commits between revisions. Without a code sample, it would be difficult to move on. 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a single `main.dart` file that can be run independently. If the issue's still reproducible, please provide that `main.dart` file so that we can verify the issue properly. Thank you!

**Comment by huycozy** [comment] 2023-07-18 10:17
Unfortunately, I can't find an existing test for this case. The issue may be related to different components whilst not sure which one you implemented in the above example. I check this with [SlideTransition](https://api.flutter.dev/flutter/widgets/SlideTransition-class.html) example and modify it a bit but can't reproduce the issue. Looks like this needs a more complicated sample to reproduce it. 

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/bb451869-43f8-4aef-871d-d3f4e5344822

</details>

I will close this issue since it's not reproducible now. Once you can provide a sample code for this, feel free to write a comment with more information then I will reopen issue for further investigation. Thanks!

**Comment by delfme** [comment] 2023-07-18 13:09
👍 yes sample must comprise a transition between two screens.

Could you please try with this sample? It is not our code but noticed it should let us reproduce the issue without wasting time coding.
https://github.com/mitchkoko/CUBEcarousel

To test it, we just need to add some elements on the screen and then drag the screen to move to the next one. Elements should disappearing during transition.

**Comment by huycozy** [comment] 2023-07-20 03:31
It looks good as I can see. The sample above is using a package with lots of code, though. If the issue is reproducible, you should also disassemble the unrelated components to find the component that caused the error.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/3e11b98a-6ba1-4ba0-a707-b078c96efb8d

</details>

**Comment by delfme** [comment] 2023-07-20 05:39
Okay, will double check it also on my side and revert here

**Comment by delfme** [comment] 2023-07-20 12:44
@huycozy I think we nailed issue. I tested with that sample and cannot reproduce issue coz  the transition is not the same (see vid 1 below)

Vid 1:

https://github.com/flutter/flutter/assets/53510751/c4a464a3-8c8c-46bc-be7c-9ab424b72178

Vid 2: is the correct transition where issue occurs


https://github.com/flutter/flutter/assets/53510751/974c0b56-d62a-423a-8493-b569f5c5173f


Good news is that while previous master was throwing no errors, the latest one v. 3.13.0-7.0.pre.37 throws this error multiple times while widgets get unmounted.

 [VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
 
Maybe you guys can understand what it is. Also, is it any helpful to compare that line with the one of version v. 3.12.0, which is not affected by issue?

**Comment by delfme** [comment] 2023-07-20 13:05
I will meantime investigae more. Feeling is that issue is inside a plugin, although it points to engine.

**Comment by delfme** [comment] 2023-07-20 14:37
Was able to nail down the issue and create a sample repo.
Please have a look here
https://github.com/delfme/cube-sample

I extracted our own cube widget `CubePageView` (which doesn't use any plugin) and I'm using it inside `homepage.dart`.

My discovery is that issue is caused by plugin `FastCachedImage`, but it looks like it might be an engine issue for following reasons:
1) code works fine with 3.12.0
2) console prints Impeller error: [VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
3) all widgets get unmounted even if they are not images. As you can see from the video, I've added a couple of circles with no images, and they get unmounted as well when we rotate the screen.

https://github.com/flutter/flutter/assets/53510751/26398dcc-9b2d-438e-b0c7-f8e1e76ba6fc


Note: issue resolves if you comment the widget which uses `FastCachedImage` and uncomment the ones which use `Image.network or `CachedNetworkImage` . At first glance, although a plugin is involved, it looks like it might be an engine issue.

**Comment by huycozy** [comment] 2023-07-21 04:58
Thanks for the update. I see the issue now and it only occurs when using `fast_cached_network_image` (it's still a complicated package that is using other dependencies: hive, dio). 

But I'm seeing a new issue https://github.com/flutter/flutter/issues/131012 that has been filed recently and it could be similar/related. I will leave my comment there. You can follow up on it for updates.

**Comment by dnfield** [comment] 2023-07-25 21:31
I updated the title - `unmounted` is a framework term, what you're dealing with here is a rendering bug.

Also AFAICT there's a perspective transform going on here.

What I think is happening is some bug in applying the perspective transform to some entity to determine whether it should render or not.

**Comment by dnfield** [comment] 2023-07-25 22:24
The image packages are failing because they're using fade transitions, which are wrapping the image in an opacity layer.

**Comment by dnfield** [comment] 2023-07-25 22:24
(so the `Image.network` fails too if you wrap it in something like `Opacity(opacity: .9, child: Image.network(...`)

**Comment by delfme** [comment] 2023-07-26 07:52
@dnfield great to see you nailed the root of problem! Yesterday I was hit by the issue even when not using that image plugin, but we have several places where we wrap images inside Opacity or Visibility, so it should be that. 👍

What is not clear to me is why issue affects all the widgets on the scene, not only the images.

**Comment by dnfield** [comment] 2023-07-26 15:50
I haven't quite finished nailing this down but should get to it today. Opacity introduces a new layer in the backend and something is going wrong when perspective is involved.

**Comment by dnfield** [comment] 2023-07-26 17:35
This seems to be a bug in the display list/dispatching code...

**Comment by dnfield** [comment] 2023-07-26 17:36
If I disable rtree based culling everything is happy again.

**Comment by jonahwilliams** [comment] 2023-07-26 17:38
Is this something that regressed when we stopped eagerly projecting transforms in flow?

**Comment by dnfield** [comment] 2023-07-26 17:48
If I did my revert right, this regressed with https://github.com/flutter/engine/pull/43536

/cc @flar fyi

**Comment by dnfield** [comment] 2023-07-26 17:49
I haven't really worked out why this regresses on impeller but not skia though

**Comment by jonahwilliams** [comment] 2023-07-26 17:50
If this is in the beta we should consider a CP revert of the 4x4 change at least.

**Comment by flar** [comment] 2023-07-26 18:56
The cube-sample test case works fine with both Impeller and Skia on desktop on [the current ToT](https://github.com/flutter/flutter/commit/27e912316f7ad67099d843f8b1249f66663f5631)

**Comment by dnfield** [comment] 2023-07-26 20:43
I have a test case locally that is failing on ToT impeller but not Skia (on desktop).

**Comment by dnfield** [comment] 2023-07-27 16:41
Here's a single-frame smallish reproduction, based on a point in time where the cube demo disappears.

```dart
import 'dart:typed_data';
import 'dart:ui';

void main() {
  final view = PlatformDispatcher.instance.implicitView!;
  final builder = SceneBuilder();
  builder.pushTransform(Float64List.fromList(<double>[
    2.0, 0.0, 0.0, 0.0, //
    0.0, 2.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
  ]));
  builder.pushOffset(-93.0, 0);
  builder.pushTransform(
    Float64List.fromList(<double>[
      0.8, -0.2, -0.1, -0.0, //
      0.0, 1.0, 0.0, 0.0,
      1.4, 1.3, 1.0, 0.0,
      63.2, 65.3, 48.6, 1.1,
    ]),
  );
  // Offset is ok, opacity breaks things.
  //  builder.pushOffset(35, 75);
  builder.pushOpacity(252, offset: const Offset(35, 75));
  final pictureRecorder = PictureRecorder();
  final canvas = Canvas(pictureRecorder);
  canvas.drawRect(
    const Rect.fromLTWH(0, 0, 50, 50),
    Paint()..color = const Color(0xFFABCDEF),
  );
  final picture = pictureRecorder.endRecording();
  builder.addPicture(Offset.zero, picture);

  final scene = builder.build();

  PlatformDispatcher.instance.onBeginFrame = (_) {
    view.render(scene);
    PlatformDispatcher.instance.scheduleFrame();
  };
  PlatformDispatcher.instance.scheduleFrame();
}
```

The combination that seems to cause it is:

- A CTM involving perspective that puts part of the drawn content outside the cull rect.
- Opacity.
- Impeller.

**Comment by dnfield** [comment] 2023-07-27 16:42
Impeller's dl_dispatcher implementation is never getting the `DrawRect` call in this test case, where as Skia's dispatcher does.

**Comment by dnfield** [comment] 2023-07-27 17:03
Argh something has gone wrong, this example seems to render now for me.

**Comment by dnfield** [comment] 2023-07-27 18:19
This doesn't happen on desktop because desktop is not providing a cull_rect when creating the impeller dispatcher.

**Comment by flar** [comment] 2023-07-27 18:34
Hmmm, for Skia we let SkCanvas do the layer culling, but for Impeller it is DLBuilder doing the culling. DlBuilder will use m44.asM33().transform whereas SkCanvas uses that internal transform. We had convinced ourselves that SkMatrix's use of an SkPath to do the transform of the rect should be equivalent to the internal code used by SkCanvas, but maybe it's not the case. We could try porting the internal perspective rect transform code to our internal MatrixClipTracker?

**Comment by flar** [comment] 2023-07-27 18:39
Does the entire DL get culled? Or does the DrawRect itself get culled from within the DL? I'm guessing it's the latter since the image and the rect disappeared at different times and they are likely part of the same DL? Or are they separated by an OpacityLayer?

**Comment by flar** [comment] 2023-07-27 18:44
I can confirm that Impeller's transform of a rect that has perspective elements doesn't deal correctly with clipping against the near plane, but I'm not sure that comes up in this case.

Impeller Matrix*Point is just transform the 4 points in isolation (dividing by the generated `w` result even if it is negative), and then min-maxing the 4 transformed points.

Skia's internal mapRect (and even the version in SkMatrix) will project all of the points, perform clipping against the near plane, and then take the bounds of the clipped polygon.

**Comment by flar** [comment] 2023-07-27 19:50
Possible solutions if the problem is the computation of the local-space clip bounds in Impeller:

- Have Impeller Matrix operate similarly to the internal Skia rect mapping (see below)
- Detect non-affine matrix and do not use rtree culling in DlDispatcher::DrawDisplayList()

The technique (that Skia uses) for perspective rect mapping is very simple - for any corner that transforms to a point with a "clipped" `w'` value (i.e. `w' < ~1.0/2^14` in Skia's case), they linearly interpolate that value to its 2 adjacent corners if those corners have an unclipped `w'` value and include those interpolated points in the bounds. Note that any clipped corner may generate 0, 1, or 2 interpolated points depending on whether neither, one, or both of its adjacent corners is unclipped. The actual bounds may be accumulated on 0, 3, 4, or 5 points depending on how many corners are clipped (if you go through all ways in which a rectangle can slip beneath the surface of the near clipping plane).

For quickest turn around we should probably take the second option which is to just avoid the rtree case in Impeller's DrawDisplayList if there is perspective in the transform (you only need to really check 3 entries since we ignore all of the Z entries).

**Comment by dnfield** [comment] 2023-07-27 20:14
I believe there's a bug in Impeller's transform rect routine. Trying to cpy skia's now.

**Closed** 2023-07-28 15:18 UTC
Labels: engine, P1, e: impeller

**Comment by dnfield** [comment] 2023-07-28 16:05
https://github.com/flutter/engine/pull/44106 will CP this into beta.

**Comment by delfme** [comment] 2023-07-28 20:50
Will test master again and revert here by monday

**Comment by delfme** [comment] 2023-08-02 09:21
Fix work perfectly on our side 👍

https://github.com/flutter/flutter/assets/53510751/0887b64c-a218-4255-ba29-ad3f4fcc5a40

**Comment by delfme** [comment] 2023-08-03 08:22
That is a 1.5px difference (vertically) compared to 3.13.0-0.2.pre. Im out travelling and cant file an issue. But to see it, simply put a Text widget inside a Container with a border line.  Master 3.13.0-16.0.pre.22 places the Text in a different position

**Comment by dnfield** [comment] 2023-08-03 16:15
I believe @LongCatIsLooong might know about this, and it may be intentional.

**Comment by LongCatIsLooong** [comment] 2023-08-04 23:43
I don't think I've landed anything recently that could change the padding or the text placement (although I'm about to). [Material3 was recently made the default](https://github.com/flutter/flutter/pull/129724) and that changes a lot of default padding values so that's likely what caused the padding change.
