### ISSUE TITLE
Flutter issue still unsolved, ACCESS DENIED WHILE TRYING TO CREATE NEW APP

### ISSUE THREAD

**Issue by avisehgal4** [flutter/flutter#82615] opened 2021-05-15 15:19 UTC
Microsoft Windows [Version 10.0.18363.1082]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\>flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional
                            diagnostic information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Available commands:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  attach            Attach to a running app.
  bash-completion   Output command line shell completion setup scripts.
  build             Build an executable app or install bundle.
  channel           List or switch Flutter channels.
  clean             Delete the build/ and .dart_tool/ directories.
  config            Configure Flutter settings.
  create            Create a new Flutter project.
  devices           List all connected devices.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  drive             Run integration tests for the project on an attached device or emulator.
  emulators         List, launch and create emulators.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  precache          Populate the Flutter tool's cache of binary artifacts.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  test              Run Flutter unit tests for the current project.
  upgrade           Upgrade your copy of Flutter.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.

D:\>flutter doctor
Running "flutter pub get" in flutter_tools...                      12.5s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-UG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (1 available)

• No issues found!

D:\>flutter>flutter create newapp
Access is denied.

D:\>flutter doctor -v
[√] Flutter (Channel dev, 2.3.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-UG)
    • Flutter version 2.3.0-1.0.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (2 weeks ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\dsehgal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

D:\>flutter create my app
Multiple output directories specified.

D:\>flutter>flutter create bodyspace
Access is denied.

D:\>flutter run --verbose
[  +84 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +165 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] d97f41caed971d4668ffe56699367ec3978db8f6
[   +2 ms] executing: [D:\flutter/] git tag --points-at d97f41caed971d4668ffe56699367ec3978db8f6
[ +172 ms] Exit code 0 from: git tag --points-at d97f41caed971d4668ffe56699367ec3978db8f6
[   +2 ms] 2.3.0-1.0.pre
[   +9 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +135 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/dev
[   +1 ms] executing: [D:\flutter/] git ls-remote --get-url origin
[ +110 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +223 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[ +127 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[  +84 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +145 ms] executing: C:\Users\dsehgal\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +128 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] "flutter run" took 381ms.
[  +19 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +6 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1360:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:449:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1198:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1091:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[ +259 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

D:\>

**Comment by iapicca** [comment] 2021-05-15 17:43
@avisehgal4 

> D:>flutter>flutter create newapp
> Access is denied.

> D:>flutter>flutter create bodyspace
> Access is denied.

can you run `flutter create newapp -v` and provide the logs

#

> D:>flutter create my app
> Multiple output directories specified.

you are using a wrong command: try `my_app` instead of `my app`

#

> [ +19 ms] Error: No pubspec.yaml file found.
> This command should be run from the root of your Flutter project.

this happens when you run the command `flutter run` **not** from your app folder
run `cd <YOUR APP FOLDER>` first

# 

> Flutter issue still unsolved, ACCESS DENIED WHILE TRYING TO CREATE NEW APP

to which issue are you referring to?

**Comment by ZurMaD** [comment] 2021-05-15 18:44
I higly recommend to use dockerized environments to avoid weirs stuff like this on Win10.
Please check this post https://medium.com/@cezary.zelisko/how-to-prepare-a-flutter-workspace-in-a-docker-container-e56e0c7c7dcd

**Comment by TahaTesser** [comment] 2021-05-17 10:12
Hi @avisehgal4 
As mentioned in https://github.com/flutter/flutter/issues/82343, you don't seem to follow the official documentation
`flutter create my app` is an invalid command, it should be `flutter create myapp` with no space in the app name
`flutter run --verbose` you cannot this command from  a random directory, it should execute from the root of a Flutter project 


Please read the official guide and watch some Youtube videos for a better understanding
Closing as duplicate of https://github.com/flutter/flutter/issues/82343

**Closed by TahaTesser** 2021-05-17 10:12 UTC
