### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by FunlabStudio** [flutter/flutter#86163] opened 2021-07-09 09:24 UTC
```
Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Ionicons.ttf'. The parent directory may not exist, or the user does not have permiss
ion to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Foundation.ttf'. The parent directory may not exist, or the user does not have permi
ssion to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Octicons.ttf'. The parent directory may not exist, or the user does not have permiss
ion to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Entypo.ttf'. The parent directory may not exist, or the user does not have permissio
n to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/cupertino_icons/assets/CupertinoIcons.ttf'. The parent directory may not exist, or the user does not hav
e permission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/MaterialCommunityIcons.ttf'. The parent directory may not exist, or the user does no
t have permission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/SimpleLineIcons.ttf'. The parent directory may not exist, or the user does not have
permission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/AntDesign.ttf'. The parent directory may not exist, or the user does not have permis
sion to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/FontAwesome5_Regular.ttf'. The parent directory may not exist, or the user does not
have permission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/FontAwesome.ttf'. The parent directory may not exist, or the user does not have perm
ission to create this file.

Failed to open output file 'C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile Source\
Flutter-BuySell\build\app\intermediates\flutter\release\flutter_assets\packages/flutter_icons/fonts/Feather.ttf'. The parent directory may not exist, or the user does not have permissi
on to create this file.



FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\wasiq\Downloads\flutter_windows_1.22.2-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\wasiq\Downloads\flutter_windows_1.22.2-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 1s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     183.9s
Gradle task assembleRelease failed with exit code 1
```

**Comment by SinaElahimanesh** [comment] 2021-07-09 10:03
Try the following:
Go to `pubspec.yaml` file, and try doing `Packages get | Pub get`,

<img width="169" alt="uytNU" src="https://user-images.githubusercontent.com/59636948/125061340-7d931300-e0c2-11eb-9a78-3f9853bc0e76.png">

<img width="491" alt="GXmSr" src="https://user-images.githubusercontent.com/59636948/125061438-956a9700-e0c2-11eb-9982-9b1f7283f212.png">

and then build the project again.

Even if this doesn't work, try removing the import dart:html; from the code and build again. Hope this resolves!

**Comment by FunlabStudio** [comment] 2021-07-09 10:34
I did both way but still same errors.

**Comment by SinaElahimanesh** [comment] 2021-07-09 10:39
It is somehow strange!
can you use `flutter clean` command. That's worked for me. I hope be useful for you.

**Comment by FunlabStudio** [comment] 2021-07-09 10:44
When I do flutter clean the terminal gives an error

Failed to remove build. A program may still be using a file in the directory or the directory itself. To find and stop such a program, see:
https://superuser.com/questions/1333118/cant-delete-empty-folder-because-it-is-used
Deleting build...                                                   24ms
Failed to remove C:\Users\wasiq\Downloads\codecanyon-Zl0LlVY9-flutter-buysell-for-ios-android-olx-mercari-offerup-carousell-buy-sell-10-\Flutter-BuySell(v2.6)\Mobile
Source\Flutter-BuySell\.dart_tool. A program may still be using a file in the directory or the directory itself. To find and stop such a program, see:

**Comment by SinaElahimanesh** [comment] 2021-07-09 10:47
I think you should run your cmd as administrator then run the command. 
If you are using macOS or Linux you could run this command:
`sudo flutter clean`

**Comment by SinaElahimanesh** [comment] 2021-07-09 10:48
and did you do **File => Invalidate caches / Restart** ?

**Comment by FunlabStudio** [comment] 2021-07-09 10:58
yes, I just did but the build failed.
flutter build apk

**Comment by darshankawar** [comment] 2021-07-09 11:17
@FunlabStudio 
Can you provide `flutter doctor -v`, and `pubspec.yaml` ?

**Comment by FunlabStudio** [comment] 2021-07-09 12:00
###### Flutter Doctor ##########

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale en-GB)
    • Flutter version 2.2.3 at C:\Users\wasiq\Downloads\flutter_windows_1.22.2-stable\flutter
    • Framework revision f4abaa0735 (8 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\wasiq\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\wasiq\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\wasiq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • SM A305F (mobile) • R58M843YKMZ • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!


#### yaml ########


name: flutterbuyandsell
description: A new Flutter Buy Sell store application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: none


# CCV 2.6 = 2.6.0+21
# CCV 2.5 = 2.5.0+20
# CCV 2.4 = 2.4.0+19
# CCV 2.3 = 2.3.0+18
# CCV 2.3 = 2.3.0+17
# CCV 2.2 = 2.2.0+16
# CCV 2.2 = 2.2.0+15
# CCV 2.1 = 2.1.0+14
# CCV 2.0 = 2.0.0+13
# CCV 1.9 = 1.9.0+12
# CCV 1.8 = 1.8.0+11
# CCV 1.7 = 1.7.0+10
# CCV 1.6 = 1.6.0+9
# CCV 1.5 = 1.5.0+7
# CCV 1.4 = 1.4.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: 2.0.5 
  http: 0.13.1
  provider: 5.0.0
  connectivity: 3.0.3
  
  dynamic_theme : 
    path: packages/dynamic_theme
  flutter_map: 
    path: packages/flutter_map  
  optimized_cached_image: 
    path: packages/optimized_cached_image  
  multi_image_picker: 
    path: packages/multi_image_picker
  easy_localization: 
    path: packages/easy_localization
  latlong:
    path: packages/latlong
  flutter_widget_from_html: 0.6.0-rc.2021031201 
  sembast: 3.0.0+4
  path_provider: 2.0.1
  intl: 0.17.0
  shimmer: 1.1.2
  url_launcher: 6.0.2
  carousel_slider: 3.0.0
  firebase_core: 1.0.1
  firebase_messaging: 9.0.0
  firebase_database: 6.1.0
  firebase_auth: 1.0.1
  flutter_native_admob: 2.1.0+3
  google_mobile_ads: 0.12.2+1
  google_sign_in: 5.0.0
  flutter_facebook_login: 3.0.0
  flutter_webview_plugin: 0.3.11
  photo_view: 0.10.3
  progress_dialog: 1.2.4
  braintree_payment: 1.2.4
  launch_review: 2.0.0
  package_info: 0.4.3
  flutter_icons: 1.1.0
  flutter_stripe: 1.0.2
  flutter_credit_card: 0.1.4
  fluttertoast: 7.1.6
  permission_handler: 6.1.0
  permission_handler_platform_interface: 3.1.1
  geocoder: 0.2.1
  geolocator: 7.0.1
  share: 2.0.4
  the_apple_sign_in: 1.1.1
  razorpay_flutter: 1.2.3
  group_radio_button: 1.0.1
  flutter_native_image: 0.0.5+3
  flutter_paystack: 1.0.5
  firebase_dynamic_links: 0.5.0+11
  in_app_purchase: 1.0.5
  camera: 0.8.0
  flutter_linkify: 4.0.2
  google_maps_flutter: 2.0.4
  flutter_datetime_picker: 1.5.0
  font_awesome_flutter: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_circle_image.png
   - assets/images/placeholder_image.png
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/de-DE.json
   - assets/langs/es-ES.json
   - assets/langs/fr-FR.json
   - assets/langs/id-ID.json
   - assets/langs/it-IT.json
   - assets/langs/ja-JP.json
   - assets/langs/ko-KR.json
   - assets/langs/ms-MY.json
   - assets/langs/pt-PT.json
   - assets/langs/ru-RU.json
   - assets/langs/th-TH.json
   - assets/langs/tr-TR.json
   - assets/langs/zh-CN.json
   - assets/images/verify_email_icon.jpg
   - assets/images/down.png
   - assets/images/baesline_access_time_black_24.png
   - assets/images/baseline_check_green_24.png
   - assets/images/baseline_graph_black_24.png
   - assets/images/baseline_price_down_black_24.png
   - assets/images/chat.png
   - assets/images/seo.png
   - assets/images/upload.png
   - assets/images/baseline_price_up_black_24.png
   - assets/images/baseline_empty_item_grey_24.png
   - assets/images/home_icon/discount_products.png
   - assets/images/home_icon/easy_payment.png
   - assets/images/home_icon/featured_products.png
   - assets/images/home_icon/free_download.png
   - assets/images/trending.png
   - assets/images/flutter_buy_and_sell_logo.png
   - assets/images/flutter_buy_and_sell_logo_light.png
   - assets/images/baseline_pin_black_24.png
   - assets/images/baseline_favourite_grey_24.png
   - assets/images/default_image.png
   - assets/images/baseline_promotion_color_74.png
   - assets/images/user_default_photo.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by hndrbrm** [comment] 2021-07-10 07:30
I have meet this kind of problem in windows. The problem caused by Comodo Anti Virus. It contained some binary application from the flutter sdk by default. Need to give an exception to Comodo Containment system. Or just simply turn it off temporary.

**Comment by darshankawar** [comment] 2021-07-12 06:28
@FunlabStudio 
Try above solution and see if it works. Also check if there's any other external program / tool that's enabled which may be prohibiting to run your app properly.

**Comment by FunlabStudio** [comment] 2021-07-12 08:20
My other application works well on 'flutter build apk'  but I'm facing a problem only with this application

**Comment by hndrbrm** [comment] 2021-07-12 14:25
Try delete the build directory, manually from Explorer.
If you can't then something in your OS block it.
Maybe some AV app, or maybe something else.

**Comment by darshankawar** [comment] 2021-07-13 06:06
@FunlabStudio 
This seems to be your setup issue rather than an issue in the framework. Please ask this question on support channels like StackOverflow. 
Closing from here. If you disagree, write in comments and I'll reopen with a valid argument.

**Closed by darshankawar** 2021-07-13 06:06 UTC
Labels: in triage
