### ISSUE TITLE
Video Recording Problems on Flutter CameraX Package

### ISSUE THREAD

**Issue by mrcandev** [flutter/flutter#140581] opened 2023-12-24 06:35 UTC
### Steps to reproduce

1- We start the video recording with the startVideoRecording() method.
2- After shooting what we want to shoot during the video, we end the video recording with the stopVideoRecording() method.

### Expected results

Video recording without any problems

### Actual results

A few seconds after you start shooting a video in the camera_android_camerax package, the video preview becomes distorted and changes to horizontal. The quality drops a lot. Video is not recorded after using the recording stopvideorecording method. When we try to access it via the file path, we get an error saying "There is no such file, there is no video type file in the relevant path."

Tests performed:
- The same problem occurs when we run the example sample included in the flutter camera_android_camerax package.

### Code sample

<details open><summary>Code sample</summary>

```dart

// RUN THIS METHOD FOR START AND STOP VIDEO RECORD
void _videoRecordingChanger() async {
    if(isVideoRecording) {
      _stopVideoRecording();
    } else {
      _startVideoRecording();
    }
  }

void _startVideoRecording() async {

    if(!Platform.isAndroid){
      await _cameraController?.prepareForVideoRecording();
    }
    await _cameraController?.startVideoRecording();
    setState(() {
      isVideoRecording = true;
    });

  }

void _stopVideoRecording() async {

    XFile videoFile = await _cameraController!.stopVideoRecording();
    setState(() {
      isVideoRecording = false;
    });
    
    var realFilePath = '/VIDEO_${DateTime.now().millisecondsSinceEpoch}_${generateNumber()}.mp4';

    await videoFile.saveTo(realFilePath);

  }




```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale tr-TR)
    • Flutter version 3.13.2 on channel stable at /Users/simeray/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (4 months ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/simeray/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/simeray/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109
    ! Error: Browsing on the local area network for Sinem iPhone’u. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-27 11:08
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137366. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-27 11:08 UTC
Labels: in triage
