### ISSUE TITLE
Image picker not working after targeting api level 30, plystore mandate to use scoped storage. What to do now

### ISSUE THREAD

**Issue by madhu6264** [flutter/flutter#81369] opened 2021-04-28 09:37 UTC
## Steps to Reproduce

We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

```
```

```
```

```
```

</details>

**Comment by mrmike** [comment] 2021-04-28 12:19
Related topic: https://github.com/flutter/flutter/issues/80502

**Comment by TahaTesser** [comment] 2021-04-28 12:43
duplicate of https://github.com/flutter/flutter/issues/80502

**Closed by TahaTesser** 2021-04-28 12:43 UTC
Labels: in triage
