### ISSUE TITLE
[iOS]After entering text into the iOS 17 text input box, the cursor selects the last character

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#128406] opened 2023-06-07 10:59 UTC
After entering text into the iOS 17 text input box, the cursor selects the last text of the Chinese character

[video](https://package.lanxin.cn/client/6a5a8f0ce974f8f800969b1f22125773origin.57DBEE33-0350-41EE-934E-1976ECC98612%20(1).mp4) 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by kutian** [comment] 2023-06-08 02:39
Your suggestion has been received. Due to the large development and testing costs required for upgrading, we will not upgrade the Flutter version in a short time. We will continue to observe the subsequent beta versions of iOS 17. Thank you.

**Comment by kutian** [comment] 2023-06-08 09:44
this is our code demo
···
 return TextField(
      keyboardAppearance:
          XColor.instance.isDarkColor ? Brightness.dark : Brightness.light,
      controller: textEditingController,
      style: XTextStyle.instance.style_16_primary_label.toScale(),
      decoration: InputDecoration(
        contentPadding: EdgeInsets.all(4.0),
        border: OutlineInputBorder(
          borderSide: BorderSide.none,
        ),
        fillColor: Colors.transparent,
        filled: true,
        hintText: hintText,
        hintStyle: XTextStyle.instance.style_16_tertiary_label.toScale(),
      ),
      cursorColor: XColor.instance.brandColor6,
      onChanged: (text) => _handleTextChanged(text, false),
      autofocus: autofocus ? true : false,
      focusNode: _focusScope,
    );
···

**Comment by huycozy** [comment] 2023-06-09 07:18
Hi @kutian 
Your snippet code is still containing undefined components and not minimal so I'm not sure if it can be related to the issue. 

Please try checking this with the sample code that [dam-ease](https://github.com/dam-ease) provided above. If the issue still persists with that sample code, please also check it on the latest Flutter channels as well. Thank you!

**Comment by g0dzillaa** [comment] 2023-06-10 15:38
I can confirm that this is happening in my app as well. 

Everything works perfectly on the 16.4 version (both phone and simulator). After upgrading to iOS 17, the last character will be selected as we type.

https://github.com/flutter/flutter/assets/127401074/1be84625-be17-4402-a874-261d0fc08653

**Comment by g0dzillaa** [comment] 2023-06-10 16:27
> Hi @kutian. Thanks. I tried replicating the issue on other iOS versions I have installed currently and couldn't reproduce it with the sample code below, will update OS to iOS 17, can you share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?
> 
> Code Sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     const appTitle = 'Form Styling Demo';
>     return MaterialApp(
>       title: appTitle,
>       home: Scaffold(
>         appBar: AppBar(
>           title: const Text(appTitle),
>         ),
>         body: const MyCustomForm(),
>       ),
>     );
>   }
> }
> 
> class MyCustomForm extends StatelessWidget {
>   const MyCustomForm({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return const Column(
>       crossAxisAlignment: CrossAxisAlignment.start,
>       children: <Widget>[
>         Padding(
>           padding: EdgeInsets.symmetric(horizontal: 8, vertical: 16),
>           child: TextField(
>             decoration: InputDecoration(
>               border: OutlineInputBorder(),
>               hintText: 'Enter a search term',
>             ),
>           ),
>         )
>       ],
>     );
>   }
![IMG_F35FFC94397B-1](https://github.com/flutter/flutter/assets/127401074/2ba6c0af-d530-4491-bc59-6e4d6bbddc02)

> }
> ```

Can confirm this can be replicated on iOS 17.

**Comment by g0dzillaa** [comment] 2023-06-20 11:32
Any update on this? This is happening for **all** existing Flutter apps in iOS 17.

See screenshot for Google Pay and Wonderous Apps.
![IMG_3134](https://github.com/flutter/flutter/assets/127401074/442e040a-fb42-41f0-87df-cf5449c5aaba)
![IMG_3135](https://github.com/flutter/flutter/assets/127401074/533ad920-a1a4-4663-a845-9107bce93ca6)

@dam-ease @darshankawar

**Comment by dam-ease** [comment] 2023-06-26 08:02
Thanks for these.
Currently, I am unable to replicate this due to lack of latest iOS 17 config, but based on the report, adding applicable labels for team's attention.

Below is the list of issues related to Flutter, Xcode 15 and iOS 17 for reference:

https://github.com/orgs/flutter/projects/87/views/1

/cc @vashworth

**Comment by castleche** [comment] 2023-07-18 07:54
This issue can be reproduced in the latest iOS 17 developer beta 3 (21A5277j), which may be the last version before public beta. And this issue is so obvious. The official iOS 17 will be released soon in mid September. Could the Flutter team please report this to Apple and push them to fix it? Or could Flutter team please fix it ASAP ?

**Comment by Kiruel** [comment] 2023-07-18 14:49
Really agree with @castleche this is something really urgent to fix. Textfield is used everywhere. I got the same result with the latest iOS17 developer beta 3. How priority works in the Flutter project ? Can we ping someone to at least prevent this in the stable Flutter version ?

**Comment by stuartmorgan** [comment] 2023-07-18 15:38
@hellohuanlin Could you take a look at what the OS is giving us from the engine side, and see what the marked region information is (or if you already did that, document the results here; I feel like we discussed this but couldn't find notes)? It's unclear to me if this is something that would need adjustment in our text input plugin, or in the framework.

**Comment by hellohuanlin** [comment] 2023-07-18 20:51
@LongCatIsLooong and I just did a few experiment. Here's a quick summary: 

1. The highlight is from autocorrection feature. In iOS 17, there's an additional call to UITextInput's `firstRectForRange` function, which triggers our logic to show auto correction highlight with length of 1 ([code here](https://github.com/flutter/engine/blob/f3297964f2af68797290f3824d58677149c24023/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1632-L1638)). 

2. The reason we put the autocorrection highlight logic inside `firstRectForRange` is that there's no other API that supports it. So we have to put it there as a workaround. This will trigger the framework to highlight the last character. 

3. We noticed another issue - the native autocorrection highlight is displayed in iOS 17, probably by a dummy UITextField in FlutterTextInputPlugin. The native highlight is positioned at the wrong place (top), and with incorrect size (possibly due to different font configurations). An idea is to just use the native autocorrection rect, but will need more research. 
 
![Screenshot 2023-07-18 at 1 38 59 PM](https://github.com/flutter/flutter/assets/41930132/ad9a9b90-b76b-428e-9c2f-f07d0f7eb436)

**Comment by stuartmorgan** [comment] 2023-07-19 14:56
> * The highlight is from autocorrection feature. In iOS 17, there's an additional call to UITextInput's `firstRectForRange` function, which triggers our logic to show auto correction highlight with length of 1 ([code here](https://github.com/flutter/engine/blob/f3297964f2af68797290f3824d58677149c24023/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1632-L1638)).
> * The reason we put the autocorrection highlight logic inside `firstRectForRange` is that there's no other API that supports it. So we have to put it there as a workaround. This will trigger the framework to highlight the last character.

That sounds like this is an engine bug then; triggering display in the framework just because the OS is asking us for location information is clearly not expected behavior, so if we need it as a hack we need to fix the hack to handle this case.

**Comment by castleche** [comment] 2023-07-26 03:57
> > * The highlight is from autocorrection feature. In iOS 17, there's an additional call to UITextInput's `firstRectForRange` function, which triggers our logic to show auto correction highlight with length of 1 ([code here](https://github.com/flutter/engine/blob/f3297964f2af68797290f3824d58677149c24023/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1632-L1638)).
> > * The reason we put the autocorrection highlight logic inside `firstRectForRange` is that there's no other API that supports it. So we have to put it there as a workaround. This will trigger the framework to highlight the last character.
> 
> That sounds like this is an engine bug then; triggering display in the framework just because the OS is asking us for location information is clearly not expected behavior, so if we need it as a hack we need to fix the hack to handle this case.

Good to know this is considered as a bug and will be fixed!

As iOS 17 is coming soon, when can we have it fixed? Could this be a high-priority bug?

**Comment by castleche** [comment] 2023-07-28 03:52
Looks like this issue doesn't repro on iOS 17 beta 4 (21A5291h). Maybe Apple fixed it. I've tried my app and Wonderous.

**Comment by g0dzillaa** [comment] 2023-07-28 09:13
@castleche I can confirm that this issue **still persists** on iOS 17 developer beta 4 (21A5291h).

What model is your phone? 🥴

**Comment by thoradam** [comment] 2023-07-28 11:59
I can also confirm that this issues persists in iOS 17.0 (21A5291h). It's also apparent that there is nothing for Apple to fix since this is occurring in Flutter's handling of `firstRectForRange`. I am becoming worried this will persist into the public release of iOS 17.

**Comment by stuartmorgan** [comment] 2023-07-28 13:44
> I am becoming worried this will persist into the public release of iOS 17.

This issue is being actively worked on, and the public release of iOS 17 is likely more than a month away.

**Closed** 2023-08-02 18:20 UTC
Labels: a: text input, platform-ios, engine, e: OS-version specific, P1, team-ios, multiteam-retriage-candidate

**Comment by castleche** [comment] 2023-08-04 06:45
> @castleche I can confirm that this issue **still persists** on iOS 17 developer beta 4 (21A5291h).
> 
> What model is your phone? 🥴

iPhone 14 Pro. My bad, I can still repro this from time to time. Good to know this issue will be fixed by Flutter.

**Comment by g0dzillaa** [comment] 2023-08-06 01:24
Thanks @hellohuanlin. Can we expect this in the next release/hf?

**Comment by hellohuanlin** [comment] 2023-08-06 04:24
> Thanks @hellohuanlin. Can we expect this in the next release/hf?

Yes
