### ISSUE TITLE
image_picker, unintended scrolling when taking photo and using brightness controls

### ISSUE THREAD

**Issue by fredrik-smedberg** [flutter/flutter#136126] opened 2023-10-07 13:57 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**Description**
If I use the `image_picker` library and attempt to take a photo while also making use of the _brightness controls_ in the camera preview window, then the Flutter app will scroll or bounce my window when returning from the camera. For example, it will scroll my ListView for no reason.

**Tested on**
Flutter: 3.13.6
Device: iPad Pro 12,9" (MHR63KN/A)
image_picker: ^1.0.4
iOS: iPad OS 16.6, 16.7 (and a friend tested on iPad OS 17.0)

I've tested this both in debug and release modes.

**How to reproduce**
1. Attempt to take a photo by launching the camera preview window
```
ImagePicker().pickImage(
    source: ImageSource.camera,
);
```

2. In the camera preview, adjust the brightness by clicking once on the screen to see the brightness controls. Adjust the brightness level either up or down.
4. Now take a photo.
5. When returning from the camera preview view (after taking a photo), the ListView has been scrolled up or down. This only happens when taking a photo **and** using the brightness control. Just taking a photo doesn't scroll the app.

I've prepared a small reproducible example that can be found here:
https://github.com/fredrik-smedberg/image_picker_scroll_bug

### Expected results

The app should never scroll when returning from camera preview.

### Actual results

The app scrolls up, down or bounces when returning from the camera preview if I've used the brightness controls.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  void takePhoto(ImageSource source) {
    ImagePicker().pickImage(
      source: source,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Camera Scroll Test'),
        ),
        body: Center(
          child: ListView(
            physics: const BouncingScrollPhysics(),
            children: <Widget>[
              SizedBox(
                height: 200,
                child: CupertinoButton(
                  child: const Text('Click to take a photo'),
                  onPressed: () => takePhoto(ImageSource.camera),
                ),
              ),
              Container(
                color: Colors.amber,
                child: const SizedBox(
                  height: 200,
                  child: Center(
                    child: Text(
                      'Some text to fill out the height (A)',
                    ),
                  ),
                ),
              ),
              Container(
                color: Colors.deepPurple,
                child: const SizedBox(
                  height: 200,
                  child: Center(
                    child: Text(
                      'Some text to fill out the height (B)',
                    ),
                  ),
                ),
              ),
              SizedBox(
                height: 200,
                child: CupertinoButton(
                  child: const Text('Pick from gallery'),
                  onPressed: () => takePhoto(ImageSource.gallery),
                ),
              ),
              Container(
                color: Colors.pink,
                child: const SizedBox(
                  height: 200,
                  child: Center(
                    child: Text(
                      'Some text to fill out the height (C)',
                    ),
                  ),
                ),
              ),
              Container(
                color: Colors.lime,
                child: const SizedBox(
                  height: 200,
                  child: Center(
                    child: Text(
                      'Some text to fill out the height (D)',
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

For full example, check out
https://github.com/fredrik-smedberg/image_picker_scroll_bug

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Video was too big to upload, so I uploaded it to my server](https://cute.se/image_picker_bug/RPReplay_Final1696684627.MP4)

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on iPad Pro 12,9 tum in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: TKBJDR9C95
Xcode build done.                                           12,5s
(lldb) 2023-10-07 16:16:07.379484+0300 Runner[10168:6871887] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
[SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
[SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
Connecting to VM Service at ws://127.0.0.1:52596/-oJmByZanQA=/ws
[Camera] Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackAuto). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackAuto). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackAuto). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackAuto). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[Camera] Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[SystemGestureGate] <0x105217bd0> Gesture: System gesture gate timed out.
[SystemGestureGate] <0x105216760> Touch: System gesture gate timed out.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale sv-SE)
    • Flutter version 3.13.6 on channel stable at /Users/fredriksmedberg/Code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (11 dagar sedan), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/fredriksmedberg/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPad Pro 12,9 tum (mobile) • 00008103-000D6584013B001E • ios            • iOS 16.3 20D47
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by mandgeprathamesh** [comment] 2023-10-07 18:47
i can try to solve the issue . give me access

**Comment by stuartmorgan** [comment] 2023-10-07 19:52
Closing as a duplicate of https://github.com/flutter/flutter/issues/14720

**Closed by stuartmorgan** 2023-10-07 19:52 UTC
