### ISSUE TITLE
[google_maps_flutter] Add Support for Changing Map Language in Google Maps Flutter Plugin

### ISSUE THREAD

**Issue by IbrokhimMirzaev** [flutter/flutter#161016] opened 2024-12-31 13:01 UTC
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Create a Flutter app using the google_maps_flutter package.
2. Add a GoogleMap widget to your app, initializing it with a valid CameraPosition and API key.
3. Set the device's language to a specific locale (e.g., Turkish).
4. Observe that the map labels (e.g., place names) appear in the device's locale language.
5. Try to programmatically change the map language by inspecting the GoogleMap or GoogleMapController API.
6. Notice there is no method or property to set the language explicitly in the Flutter plugin.

### Expected results

1. The google_maps_flutter package should provide a way to programmatically set the language for map labels and UI elements.
2. Developers should be able to specify a language (e.g., 'tr' for Turkish, 'en' for English) either as a property of the GoogleMap widget or through a method in the GoogleMapController.
3. When the language is set, all map labels, place names, and UI elements (such as zoom controls or directions) should display in the specified language, regardless of the device's locale.

GoogleMap(
  initialCameraPosition: CameraPosition(
    target: LatLng(41.015137, 28.979530),
    zoom: 10,
  ),
  language: 'tr', // Expected new property
);

### Actual results

1. The google_maps_flutter package does not provide any method or property to explicitly set the map's language.
2. The map language defaults to the device's locale, and there is no way to override it programmatically.
3. This limitation makes it impossible to match the map language with the app's selected language in multilingual apps.

### Code sample

GoogleMap(
  initialCameraPosition: CameraPosition(
    target: LatLng(41.015137, 28.979530),
    zoom: 10,
    // No property or method available to set the language
);

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2024-12-31 16:46
Please do not re-file issues unless there is new information that would lead to a different outcome. 

Closing as a duplicate of your https://github.com/flutter/flutter/issues/156205

**Closed by stuartmorgan** 2024-12-31 16:46 UTC
