### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by kobe1081** [flutter/flutter#155517] opened 2024-09-23 00:55 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008030-0013049C1191802E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:608:5)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.19.1, on macOS 15.0 24A335 darwin-arm64 (Rosetta), locale en-CN)
    • Flutter version 3.19.1 on channel stable at /Users/Tony/fvm/versions/3.16.0
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.2.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/Tony/fvm/versions/3.16.0. Consider adding /Users/Tony/fvm/versions/3.16.0/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (7 months ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Tony/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ! Unknown CocoaPods version installed.
        Flutter is unable to determine the installed CocoaPods's version.
        Ensure that the output of 'pod --version' contains only digits and . to be recognized by Flutter.
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • 小日月 (mobile)    • 00008030-0013049C1191802E • ios            • iOS 18.0 22A3354
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 129.0.6668.58

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.2.3+83
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9
### Plugins
aliyun_push-0.1.6
audioplayers-6.1.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
background_downloader-8.5.5
contacts_service-0.6.3
device_info_plus-9.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
flutter_baidu_mapapi_base-3.8.0
flutter_baidu_mapapi_map-3.8.0
flutter_baidu_mapapi_search-3.8.0
flutter_bmflocation-3.6.0
flutter_ffmpeg-0.4.2
flutter_image_compress-2.3.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.3
flutter_image_compress_web-0.1.4+1
flutter_native_contact_picker-0.0.7
flutter_openim_sdk-3.5.1
flutter_plugin_android_lifecycle-2.0.19
fluttertoast-8.2.8
fluwx-4.5.5
gal-2.3.0
google_mlkit_barcode_scanning-0.12.0
google_mlkit_commons-0.7.1
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-4.2.0
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
photo_manager-3.3.0
record-5.1.2
record_android-1.2.6
record_darwin-1.1.2
record_linux-0.7.2
record_web-1.1.0
record_windows-1.0.3
sqflite-2.3.3+1
Flutter
tencentcloud_cos_sdk_plugin-1.1.6
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_compress-3.1.3
video_player-2.9.1
video_player_android-2.4.14
video_player_avfoundation-2.6.1
video_player_web-2.3.2
video_thumbnail-0.5.3
webview_flutter-4.8.0
webview_flutter_android-3.16.3
webview_flutter_wkwebview-3.14.0

**Comment by danagbemava-nc** [comment] 2024-09-23 06:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-09-23 06:53 UTC
Labels: in triage
