### ISSUE TITLE
CI/CD failing with: Invalid plugin specification moor_ffi

### ISSUE THREAD

**Issue by NightOwlCoder** [flutter/flutter#62098] opened 2020-07-23 04:25 UTC
My app's CI/CD has been working for over 6 months, today I got below on `master` branch:

```
Running "flutter pub get" in s...                                  24.0s
Invalid plugin specification moor_ffi.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
```

Did we have any breaking change I'm not aware?

I got "unblocked" by checkout out yesterday's code:

`git checkout adc9dde3ba8563eebb824feb689f95eb947ab745`

So probably something added today broke the build.

**Comment by jonahwilliams** [comment] 2020-07-23 04:29
Potentially an issue with https://github.com/flutter/flutter/pull/61338

FYI @cyanglaz

**Comment by NightOwlCoder** [comment] 2020-07-23 15:55
Hey guys, the awesome Moor developer already gave us some additional info and a workaround.
Probably there is information from his investigation that can help?
See https://github.com/simolus3/moor/issues/727.

**Comment by cyanglaz** [comment] 2020-07-23 19:12
Looks like the issue is related to the moor_ffi package itself. The plugin is using something like 
```
plugin:
 foo: bar
```

Removing the plugin key al together should resolve the issue.

**Comment by cyanglaz** [comment] 2020-07-23 19:13
@NightOwlCoder I have commented on the issue in the simoulus3/moor repo as well. Please let us know if my comment resolves your issue so we can close this one.

**Comment by NightOwlCoder** [comment] 2020-07-23 21:03
@cyanglaz Chris, as I'm no the owner of the plugin, I can't change his source code.
Let's wait for his changes and see what he says.
Just FYI, using @simolus3 suggestion I got unblocked.

**Comment by cyanglaz** [comment] 2020-07-23 21:12
@NightOwlCoder I'm glad that you found a solution. I'm going to close the issue as it looks like an issue with the plugin's pubspec format, and the tool actually properly caught the error. I'm going to close the issue for now. If you find there is actually an issue within the framework, please feel empowered to ping me here. I'll reopen the issue and investigate.

**Closed by cyanglaz** 2020-07-23 21:12 UTC
Labels: P3, severe: regression, tool

**Comment by simolus3** [comment] 2020-07-24 09:07
@cyanglaz The problem is that
- `moor_ffi` can't depend on Flutter, since it must work for CLI & serverside apps as well
- `moor_ffi` needs to have a native buildscript when included in a Flutter application. We can't upgrade to the new format since pub requires a min-Flutter dependency when publishing

This was possible before, by using an empty `flutter.plugin` key in the pubspec. Now it seems like I have to split this to two packages (one with the Dart code, and one that only contains the native buildscripts). Are you aware of any workaround that might still work?

**Comment by cyanglaz** [comment] 2020-07-24 16:51
@simolus3 Does it work if you remove the `flutter.plugin` key completely?
