### ISSUE TITLE
Flutter example - gallery - Animation Section organizer

### ISSUE THREAD

**Issue by tombirmingham** [flutter/flutter#9910] opened 2017-05-09 00:07 UTC
[analyze-1.txt](https://github.com/flutter/flutter/files/985157/analyze-1.txt)
## Steps to Reproduce

Ran flutter gallery and selected Animation Section Organizer

## Logs

See attached logs.

## Flutter Doctor

C:\Users\Tom\GitHub\flutter\examples\flutter_gallery>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel alpha)
    • Flutter at c:\Users\Tom\flutter
    • Framework revision ffa8483f3b (7 days ago), 2017-05-01 14:18:00 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.4)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
[issue-2.txt](https://github.com/flutter/flutter/files/985156/issue-2.txt)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jason-simmons** [comment] 2017-05-09 00:20
The stack trace:

I/flutter (13105): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13105): The following _CompileTimeError was thrown building AnimationDemo():
I/flutter (13105): 'file:///C:/Users/Tom/GitHub/flutter/examples/flutter_gallery/lib/demo/animation/home.dart':
I/flutter (13105): malformed type: line 440: cannot resolve class 'NeverScrollableScrollPhysics' from
I/flutter (13105): '_AnimationDemoHomeState@434118703'
I/flutter (13105):   ScrollPhysics _headingScrollPhysics = const NeverScrollableScrollPhysics();
I/flutter (13105):                                               ^
I/flutter (13105):
I/flutter (13105): When the exception was thrown, this was the stack:
I/flutter (13105): #0      AnimationDemoHome.createState (file:///C:/Users/Tom/GitHub/flutter/examples/flutter_gallery/lib/demo/animation/home.dart:433)
I/flutter (13105): #1      StatefulElement.StatefulElement (package:flutter/src/widgets/framework.dart:3214)
I/flutter (13105): #2      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:601)
I/flutter (13105): #3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2504)
I/flutter (13105): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2309)
I/flutter (13105): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156)
I/flutter (13105): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3045)
I/flutter (13105): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3124)
I/flutter (13105): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3119)
I/flutter (13105): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506)
...

@HansMuller 

(note that this is on an alpha release from a week ago)

**Comment by tombirmingham** [comment] 2017-05-09 01:03
Was on the master, just now tried the alpha, and it works!

**Comment by Hixie** [comment] 2017-05-09 01:54
Odd. Does it work on master for you now by any chance?

**Comment by tombirmingham** [comment] 2017-05-09 02:33
Just downloaded the master again from GitHub.  Same error occurred for Shrine.

BTW - I shouldn't have Closed this Issue myself, that is for others.  I Reopened it.

**Comment by Hixie** [comment] 2017-05-09 02:35
Can you paste the output of `flutter doctor` while you're on master? I would have thought this kind of error would have been caught by our tests.

**Comment by tombirmingham** [comment] 2017-05-09 02:58
Flutter Doctor output:

C:\Users\Tom\Flutter Issues\test-master\flutter-master\examples\flutter_gallery>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel alpha)
    • Flutter at c:\Users\Tom\flutter
    • Framework revision ffa8483f3b (7 days ago), 2017-05-01 14:18:00 -0700
    • Engine revision da8ebf40bd
    • Tools Dart version 1.23.0-dev.11.11

[√] Host Executable Compatibility
    • Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.4)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    • Gradle version 3.4.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

**Comment by Hixie** [comment] 2017-05-09 05:16
Looks like that's still on the alpha branch. Maybe we forked at a bad moment? Anyway we hope to cut another alpha tomorrow and so hopefully it'll work then.

**Comment by HansMuller** [comment] 2017-05-09 16:57
The `NeverScrollableScrollPhysics` was included with the updated AnimationDemo in  https://github.com/flutter/flutter/pull/9845

I don't understand how you could  end up with the new version of the demo but not the new ScrollPhysics subclass. Is there some mixology going on here?

**Comment by tombirmingham** [comment] 2017-05-09 17:07
Yeah, that's what happened, mixology.  I was running Alpha for Flutter but
the Flutter_gallery was master.  When I ran both alpha, it was fine, I'm
sure that will be the case with master and master.

**Comment by Hixie** [comment] 2017-05-09 17:33
Can you elaborate on your setup? I'm confused about how you can be running one at one version and another at another version. Do you have two checkouts or something?

**Comment by tombirmingham** [comment] 2017-05-09 17:44
I'm not at my PC right now but what I did was follow your install steps for
Windows which for git clone is for alpha.  Then I ran the flutter_gallery
and got these errors.

**Comment by Hixie** [comment] 2017-05-09 17:46
How did you end up with a master gallery though, if you followed the steps to get alpha?

**Comment by tombirmingham** [comment] 2017-05-09 18:04
Good question...could it be when I cloned alpha, it was a snapshot in code
transition that was broken?

**Comment by Hixie** [comment] 2017-05-09 18:11
It's possible, but unlikely that it was that broken...

**Comment by tombirmingham** [comment] 2017-05-09 18:44
Yeah, the sequence was, late last week I cloned the alpha and yesterday
tried gallery and got the errors.  Then downloaded alpha gallery and all
worked.  No worries on my end, I'm going to move to the master branch for
now.

**Comment by Hixie** [comment] 2017-05-09 20:49
Ok. I'm going to close this bug because we have no idea how to reproduce the problem and it looks like it works for you now, but please if you see something like this again do not hesitate to open a bug.

**Closed by Hixie** 2017-05-09 20:49 UTC

**Comment by tombirmingham** [comment] 2017-05-09 21:59
Whoops, checked where I was launching Flutter and Flutter_gallery and it was both from the Alpha branch.  So all is OK.  Same goes for Issue #9906.  Thanks for your Support!
