### ISSUE TITLE
Non-public API usage error from webview_flutter

### ISSUE THREAD

**Issue by banool** [flutter/flutter#105479] opened 2022-06-06 23:08 UTC
## Steps to Reproduce

```
git clone https://github.com/banool/aclip
cd aclip/frontend/ios
flutter build ios --release --no-codesign
fastlane ios beta
```

Unfortunately to truly repro this you need to be able to push to Apple, so others can't make further than this. Nonetheless, from this point the app seems to push successfully, but then I get an email back from Apple saying this:

> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

So it seems like it's an issue with the [webview_flutter](https://pub.dev/packages/webview_flutter) plugin, for which I believe we track issues here.

```
$ flutter analyze
Analyzing frontend...

   info • Avoid using `forEach` with a function literal • lib/download_manager_mobile.dart:204:29 •
          avoid_function_literals_in_foreach_calls

1 issue found. (ran in 7.0s)
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.1.0, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

I was previously using stable, but I switched to beta to see if it would fix it (to no avail). This issue hard blocks pushing to Apple.

Thanks!

**Comment by WONDERJEWEL** [comment] 2022-06-06 23:16
I have the same error

**Comment by stuartmorgan** [comment] 2022-06-06 23:25
Duplicate of Duplicate of https://github.com/flutter/flutter/issues/105472

**Closed by stuartmorgan** 2022-06-06 23:25 UTC

**Comment by banool** [comment] 2022-06-06 23:26
Apologies, missed that. Thanks, I'll wait for Apple to fix it.
