### ISSUE TITLE
the url launcher does not work on Android11 and above

### ISSUE THREAD

**Issue by adamsyy** [flutter/flutter#90099] opened 2021-09-15 04:38 UTC
the package avaialable in pub.dev (https://pub.dev/packages/url_launcher)d does not launch links when used in android 11 and above.

**Comment by AbhishekDoshi26** [comment] 2021-09-15 07:03
@weberstills can you please post the error and minimal reproducible code?

**Comment by darshankawar** [comment] 2021-09-15 09:48
Verified this issue using latest master version on Android 11 (Api 30) device with plugin's official [example ](https://pub.dev/packages/url_launcher/example) and observed that it throws below exception upon trying to open a link:
```

E/flutter ( 1340): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Could not launch https://www.cylog.org/headers/
E/flutter ( 1340): #0      _MyHomePageState._launchInBrowser (package:demo/main.dart:51:7)
E/flutter ( 1340): <asynchronous suspension>
E/flutter ( 1340): 
I/ViewRootImpl@3838939[MainActivity]( 1340): ViewPostIme pointer 0
I/ViewRootImpl@3838939[MainActivity]( 1340): ViewPostIme pointer 1
E/flutter ( 1340): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Could not launch https://www.cylog.org/headers/
E/flutter ( 1340): #0      _MyHomePageState._launchInBrowser (package:demo/main.dart:51:7)
E/flutter ( 1340): <asynchronous suspension>
E/flutter ( 1340): 

```

![IMG-1270](https://user-images.githubusercontent.com/67046386/133411368-57a690e0-0696-42f4-b8cd-fb203de375cb.JPG)


While the same plugin example works properly on Android 8.1 device (Api 27) and opens the link properly:

![IMG-1269](https://user-images.githubusercontent.com/67046386/133411410-580798b5-1c11-436d-b16d-9207c07e4318.JPG)






<details>
<summary> flutter doctor -v </summary>

```

[√] Flutter (Channel master, 2.6.0-6.0.pre.95, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-6.0.pre.95 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 269f2d8fb5 (42 minutes ago), 2021-09-15 02:02:05 -0400
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • SM G975F (mobile) • RZ8M802WY0X      • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment] 2021-09-16 20:26
Is this specific to 2.6? Specific to web URLs?

**Comment by rtlsilva** [comment] 2021-09-17 13:49
Check that the app's `AndroidManifest.xml` declares the appropriate package visibility configuration as per
https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher#android

I was encountering this issue on Flutter 2.2.3 with url_launcher 6.0.9 until adding the required configuration.

**Comment by Hugovidafe** [comment] 2021-09-21 06:17
I've the same problem, my app can't open https://open.spotify.com/*, https://drive.google.com/*...
My phone is Android 11. Otherwise, the same app exported at the web, I can open them.

**Comment by echomartha** [comment] 2021-09-26 14:36
add this code in `AndroidManifest.xml` inside manifest tag
`<queries>
  
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.DIAL" />
    <data android:scheme="tel" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
</queries>`

**Comment by FMorschel** [comment] 2021-09-27 20:41
Hi! I was having this issue opening Google Maps until I added ALL of the bellow inside my `AndroidManifest.xml`
```xml
<queries>
  <!-- If your app opens https URLs -->
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  <!-- If your app makes calls -->
  <intent>
    <action android:name="android.intent.action.DIAL" />
    <data android:scheme="tel" />
  </intent>
  <!-- If your app emails -->
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
</queries>
```
Could someone please solve this? The code above is a workaround. I would like to have it fixed cause I only need the first two intents.

**Comment by stuartmorgan** [comment] 2021-09-27 22:12
> Verified this issue using latest master version on Android 11 (Api 30) device with plugin's official [example](https://pub.dev/packages/url_launcher/example)

Can you clarify what you ran exactly? You linked to the example's main.dart on pub, not the actual example in the repo, so I can't tell if you ran the example (which should have the query metadata configured) it you ran the *source* of the example in a new app (which doesn't, unless you added it).

**Comment by stuartmorgan** [comment] 2021-09-27 22:14
> I would like to have it fixed cause I only need the first two intents.

Are you saying that if you remove just the email metadata, you are unable to launch https links? If so, could you link to a reproducible test case?

**Comment by FMorschel** [comment] 2021-09-29 16:48
> Are you saying that if you remove just the email metadata, you are unable to launch https links? If so, could you link to a reproducible test case?

@stuartmorgan here is the code for the reproduction:

  <details>

  <summary> <code>AndroidManifest.xml</code>: </summary>

  ```xml
  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="com.example.url_launcher_example">
      <queries>
        <!-- If your app opens https URLs -->
        <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="https" />
        </intent>
        <!-- If your app makes calls -->
        <intent>
          <action android:name="android.intent.action.DIAL" />
          <data android:scheme="tel" />
        </intent>
      </queries>
      <application ...>
      ...
      </application>
  </manifest>
  ```

  </details>

  <details>

  <summary> <code>main.dart</code>: </summary>

  ```dart
  import 'package:flutter/material.dart';
  import 'package:url_launcher/url_launcher.dart';
  
  void main() => runApp(const MyApp());
  
  class MyApp extends StatelessWidget {
    const MyApp({Key? key}) : super(key: key);
  
    @override
    Widget build(BuildContext context) {
      final uri = Uri.https('www.google.com.br', '/maps');
      return MaterialApp(
        title: 'Url Launcher Example',
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Url Launcher Example'),
          ),
          body: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                child: const Text('Open Google Maps with "canLaunch"'),
                onPressed: () async {
                  final can = await canLaunch(uri.toString());
                  if (can) {
                    await launch(uri.toString());
                  }
                },
              ),
              ElevatedButton(
                child: const Text('Open Google Maps only launch'),
                onPressed: () async {
                  await launch(uri.toString());
                },
              ),
              ElevatedButton(
                child: const Text('Open dial'),
                onPressed: () async {
                  const tel = 'tel: +1 555 010 999';
                  final can = await canLaunch(tel);
                  if (can) {
                    await launch(tel);
                  }
                },
              ),
            ],
          ),
        ),
      );
    }
  }
  ```

  </details>

Tested on: 
- Samsung Galaxy S10 (Android 11)
- LG Q6+ (Android 7.1)

What happened:
  On Android 11 `canLaunch()` returned `false` for the HTTPS opening, but with `launch`, it worked anyway (I'm not sure what it actually does, figured it looked for permissions). And on Android 7.1 everything just worked.
  
If you add the code bellow to your `AndroidManifest.xml` the `canLaunch()` works in both versions of the OS :
```xml
  <!-- If your app emails -->
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
```

**Comment by stuartmorgan** [comment] 2021-09-29 18:54
Does using [this query](https://developer.android.com/training/package-visibility/use-cases#check-browser-available) fix the issue for you? The docs may just need to be adjusted for http/https URLs.

More generally, I think we should also adjust the README section that recommends the `canLaunch`/`launch` pair, since unless there's a specific need (e.g., enabling or disabling specific UI) I don't think the `canLaunch` step is actually needed, and that's certain not what's shown in the README.

**Comment by FMorschel** [comment] 2021-09-30 12:58
> Does using this query fix the issue for you? The docs may just need to be adjusted for http/https URLs.

No, it doesn't. But thank you for the explanation and I agree that this should be better explained in the README.

**Comment by arslan9380** [comment] 2021-12-20 07:48
Even though I'm using only https link but I need to add all intents to launch URL in manifest using gradle 4.1.0
 <queries>
        
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>

**Comment by danielgomezrico** [comment] 2022-01-20 12:42
I have added the required setup, and it works in my android 12 devices, but on my error monitors I still see logs of people not been able to launch the urls.

In my case Im trying to launch an url for whatsapp, but it works fine to me, but not on some other devices

### Env
-  url_launcher: `6.0.7`
- environment:
  - dart: `2.15.1`
  - flutter: `2.8.1`

### Android env

- Gradle:
```groovy
classpath 'com.android.tools.build:gradle:4.1.1'
```

- Manifest
```xml
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="https"/>
        </intent>

        <package android:name="com.whatsapp" />
    </queries>
```

### Url example
"https://wa.me/573176195724/?text=%F0%9F%8F%A0%20%F0%9F%92%A1%20%F0%9F%93%B1%0AMe%20gustar%C3%ADa%20saber%20m%C3%A1s%20sobre%20esta%20propiedad%3A%0Ahttps%3A%2F%2Flahaus.com%2Fp%2Fmakassar-339684%2Fbogota%3Futm_source%3Dhs_mobile_app_android%26utm_medium%3Dshared_pdp%26utm_campain%3Dshared%26utm_action%3Dapp_mobile_detail%26utm_source%3Dhs_mobile_app_android%26city%3DBogot%C3%A1%0ACodigo%3A%20339684%0Aproperty_type%3A%20NEW%0AAID%3A%2058fc32ed-5f1e-43bf-989c-93fd5d07b978%0A*Por%20favor%20no%20borres%20este%20mensaje*%0A%F0%9F%93%B1%20%F0%9F%92%A1%20%F0%9F%8F%A0"

**Comment by stuartmorgan** [comment] 2022-01-20 15:11
> In my case Im trying to launch an url for whatsapp, but it works fine to me, but not on some other devices

You haven't said what exactly isn't working. If it's `canLaunch`, you are probably hitting https://github.com/flutter/flutter/issues/93765

**Comment by stuartmorgan** [comment] 2022-01-20 15:16
Looking back at the repro cases above, it looks like those that aren't explained by missing query info are are all about `canLaunch` for URLs that may have app-specific handlers, is covered by #93765.

If anyone has an issue with `url_launcher` on Android 11+ that:
- Is not fixed by adding the query permissions described in the README, and
- Is not specific to certain http(s) URLs that are for sites that have associated apps on the phone (#93765), please file a new bug with clear reproduction steps.

**Closed by stuartmorgan** 2022-01-20 15:16 UTC
Labels: platform-android, plugin, p: first party, p: url_launcher, e: OS Version specific, has reproducible steps, P4, found in release: 2.6
