### ISSUE TITLE
Integration test error : Error loading AssetManifest.json, e: Unable to load asset: AssetManifest.json

### ISSUE THREAD

**Issue by jarinrocks** [flutter/flutter#73261] opened 2021-01-04 11:13 UTC
Error loading AssetManifest.json, e: Unable to load asset: AssetManifest.json
(The following exception is now available via WidgetTester.takeException:)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Unable to load asset: assets/locale/localization_en.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:33)
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:166:56)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:166:27)
#5      AppTranslations.load (package:mobile/languagesetup/AppTranslations.dart:22:10)
#6      AppTranslationsDelegate.load (package:mobile/languagesetup/AppTranslationsDelegate.dart:18:28)
#7      _loadAll (package:flutter/src/widgets/localizations.dart:60:49)
#8      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:515:62)
#9      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:480:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (124 frames)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
#137    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#138    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#139    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#141    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#142    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#143    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#144    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#145    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#146    LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1447:13)
#147    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 15 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

**Comment by pedromassangocode** [comment] 2021-01-04 11:19
Hi @jarinrocks 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment] 2021-01-27 10:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-27 10:45 UTC
Labels: in triage, waiting for customer response

**Comment by jarinrocks** [comment] 2021-01-27 11:03
I'll comment and reopen. Just now I'm getting noticed and I wasn't notified
earlier. Mail might have fallen in to non primary category.

Regards
Jarin PJ
Android Developer
Jarin Apps (google play)

**Comment by carldressler** [comment] 2021-06-28 16:58
Hello! I figured out that this issue is caused by Google Fonts and not Flutter. I do not know how to solve it though.
