### ISSUE TITLE
[tool_crash] _TypeError: (#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43))

### ISSUE THREAD

**Issue by Mfatihunv** [flutter/flutter#145385] opened 2024-03-19 09:31 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43))
```
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:326:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:67:12)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:91:24)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     analytics (package:flutter_tools/src/globals.dart:93:36)
#11     _exit (package:flutter_tools/runner.dart:302:15)
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:120:24)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.7, on macOS 13.5.2 22G91 darwin-arm64
    (Rosetta), locale tr-TR)
    [32m•[39m Flutter version 3.13.7 on channel stable at
      /Users/onurgumus/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2f708eb839 (5 months ago), 2023-10-09 09:58:08 -0500
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.14.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at
      /Users/onurgumus/Library/Containers/com.Ababe.UnzipAnyFile/Data/Library/Ap
      plication Support/F2600AB37D905D43084B731ADA114729/Visual Studio
      Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at /Users/onurgumus/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.2 22G91
      darwin-arm64 (Rosetta)
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment] 2024-03-19 10:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/145285. More generally, it seems you face the recent issue https://github.com/flutter/flutter/issues/145201, please check the workaround at https://github.com/flutter/flutter/issues/145201#issuecomment-1999463478.

**Closed by huycozy** 2024-03-19 10:42 UTC
Labels: in triage

**Comment by Mfatihunv** [comment] 2024-03-19 10:43
Thank you
