### ISSUE TITLE
AnimatedCrossFade is not working 

### ISSUE THREAD

**Issue by divyang159** [flutter/flutter#103174] opened 2022-05-06 04:56 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2.click on Change text button

**Expected results: whole first child have to fade to the second child.

**Actual results:first child first shrink itself to the size of the second child and than fade animation start

<details>
<summary>Code sample</summary>

```
class _MyHomePageState extends State<MyHomePage> {
  bool change = true;

  void crossFade() => setState(() {
    change = !change;
  });
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            AnimatedCrossFade(
              firstChild: const Text("divyangparmar"),
              secondChild: const Text("Parmar"),
              duration: const Duration(seconds: 2),
              crossFadeState:
              change ? CrossFadeState.showFirst : CrossFadeState.showSecond,
            ),
            MaterialButton(
              onPressed: () {
                crossFade();
              },
              child: const Text("Change Text"),
            ),
          ],
        ),
      ),
    );
  }
}
```

```

```

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

Analyzing animationcrossfade...                                         
No issues found! (ran in 1.5s)

```
```

[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.2 20G314 darwin-x64, locale en-IN)
    • Flutter version 2.10.3 at /Users/divyang.parmar/Documents/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/divyang.parmar/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Users/divyang.parmar/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.2 20G314 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

https://user-images.githubusercontent.com/55906611/167069375-70c758b3-6f84-41c4-93e3-027691cc9645.mp4

**Comment by K-Rafiki** [comment] 2022-05-06 06:17
Try this code. 

`AnimatedCrossFade(
              firstChild: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: const [
                  Text("First Text here")
                ]
              ),
              secondChild: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: const [
                  Text("Second")
                ]
              ),
              duration: const Duration(seconds: 2),
              crossFadeState:
              change ? CrossFadeState.showFirst : CrossFadeState.showSecond,
            ),`

**Comment by maheshmnj** [comment] 2022-05-06 09:03
Hi @divyang159, This is working as intended as mentioned in the [docs](https://api.flutter.dev/flutter/widgets/AnimatedCrossFade-class.html)

> A widget that cross-fades between two given children and animates itself between their sizes. 


https://user-images.githubusercontent.com/31410839/167101177-c9569e50-3a84-4e93-b35b-def5dd42f0af.mov


consider this code sample (Same as yours but with a  different child widgets)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool change = true;

  void crossFade() => setState(() {
        change = !change;
      });
  Widget box(double size, Color color) {
    return Container(
      height: size,
      width: size,
      color: color,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            AnimatedCrossFade(
              firstChild: box(30, Colors.red),
              secondChild: Text('Hello world'),
              duration: const Duration(seconds: 2),
              crossFadeState:
                  change ? CrossFadeState.showFirst : CrossFadeState.showSecond,
            ),
            MaterialButton(
              onPressed: () {
                crossFade();
              },
              child: const Text("Change Text"),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details> 



https://user-images.githubusercontent.com/31410839/167101304-11a345db-d322-49b7-ba5d-12c32891e16e.mov



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as this is working as intended, Incase you disagree feel free to write in the comments and we will reopen it.

**Closed by maheshmnj** 2022-05-06 09:03 UTC
Labels: in triage
