### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by jameskaguo777** [flutter/flutter#71043] opened 2020-11-22 15:28 UTC
## Command
```
flutter run --enable-software-rendering
```

## Steps to Reproduce
1. Add image to assets
2. rename the image
3. Hot reload

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ResidentRunner.preExit (package:flutter_tools/src/resident_runner.dart:1324:25)
#4      HotRunner.preExit (package:flutter_tools/src/run_hot.dart:1157:17)
<asynchronous suspension>
#5      ResidentRunner.detach (package:flutter_tools/src/resident_runner.dart:1013:11)
<asynchronous suspension>
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1495:30)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1643:13)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale en-TZ)
    • Flutter version 1.22.4 at C:\tools\flutter
    • Framework revision 1aafb3a8b9 (9 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\James Kaguo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\James Kaguo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: a0860f6e87ba4f9031bee4d6f56c08b970606bee

**Comment by iapicca** [comment] 2020-11-22 23:00
possible duplicate of 
https://github.com/flutter/flutter/issues/69537
https://github.com/flutter/flutter/issues/69109
https://github.com/flutter/flutter/issues/50880

**Comment by darshankawar** [comment] 2020-11-23 11:36
@jameskaguo777 
Can you switch to latest master and try again to see if it works or issue persists ?

**Comment by jameskaguo777** [comment] 2020-11-24 09:10
> @jameskaguo777
> Can you switch to latest master and try again to see if it works or issue persists ?

Thanks, I did, solved the issue.

**Closed** 2020-11-24 09:11 UTC
Labels: in triage
