### ISSUE TITLE
Unable to make current Step as Complete in Stepper Widget

### ISSUE THREAD

**Issue by srikanthbollojula** [flutter/flutter#22405] opened 2018-09-28 06:43 UTC
Unable to change the properties State and IsActive because set as final. Which is restricting them from being modified from events like onStepContinue or onStepCancel. Could you please check?
File path: flutter\lib\src\material\stepper.dart

**Comment by zoechi** [comment] 2018-09-28 07:57
`Step` is a stateless widget and therefore state is not supposed to be modified.
You need to rebuild (caused by `setState()`) and render it as not active.

Closing because this is a support request.

**Closed** 2018-09-28 07:57 UTC
