### ISSUE TITLE
Flutter Gradle should automatically add MultiDex

### ISSUE THREAD

**Issue by slightfoot** [flutter/flutter#21009] opened 2018-08-24 22:53 UTC
## Steps to Reproduce

Build app with more than 64K methods.

## Logs
> The number of method references in a .dex file cannot exceed 64K.
> Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

## Recommended Changes
1. Project template or `flutter.gradle` script should set the `multiDexEnabled` property to true, and add the `multiDexKeepFile file('multidex-flutter.txt')` config file. Example: [multidex-flutter.txt](https://github.com/flutter/flutter/files/2320127/multidex-flutter.txt)
    ```txt
    io/flutter/app/FlutterApplication.class
    io/flutter/view/FlutterMain.class
    io/flutter/util/PathUtils.class
    ```

2. Project template or `flutter.gradle` script should add the multidex dependency.
    `implementation 'com.android.support:multidex:1.0.3'`

3. FlutterApplication should have the following addition.
    ```java
    @Override
    protected void attachBaseContext(Context base)
    {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
    ```

**Adding the `multiDexKeepFile` is important as the `FlutterApplication` class and its dependencies are required to me in the primary dex file or the Application class may its onCreate lifecycle event.**

```
Flutter 0.5.7 • channel v0.5.7 • https://github.com/slightfoot/flutter
Framework • revision 66091f9696 (7 weeks ago) • 2018-07-09 12:52:41 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
```

**Comment by slightfoot** [comment] 2018-08-24 22:55
Was just caught by this. @Hixie @eseidel I think this is important addition towards v1.0, especially when we have lots of users that have no previous app-dev experience, and its a big gotcha.

**Comment by BugsBunnyBR** [comment] 2018-08-25 05:05
While multidex is important, it should not be the default option. It makes the app loading and compiling time longer.
I think it should be an opt-in feature. Maybe flutter cli could update the project structure to solve this when the developer requests to.

**Comment by slightfoot** [comment] 2018-08-25 16:16
@BugsBunnyBR I believe the compilation time is not a big deal as it once was. Remember instant-run, and other tools features use multiple dex files and use `adb install-multple`. The tooling has improved since multidex initial launch. Compilation time is a problem in the "Android" world, but because of hot-reload and hot-restart it's not so much of an issue when it comes to Flutter development. Yes, app-loading takes a hit to load multiple dex files, but that's only when there are more dex files and only on pre-v21 since multi--dex is a no-op on v21+ because the framework loads multiple dex files now.

I think as long as it is handled by the Flutter framework and not left to the developer to figure out the black magic then I'm all happy for a opt-in feature, like a extra parameter on the create command, and/or a tick-box in the IntelliJ plugin.

Either way, along as something is done, I'm happy.

**Comment by Hixie** [comment] 2018-09-25 22:35
cc @matthew-carroll @jason-simmons @filiph

**Comment by Hixie** [comment] 2018-09-25 22:35
cc @bparrishMines

**Comment by Hixie** [comment] 2018-09-25 22:35
cc @gspencergoog

**Comment by Hixie** [comment] 2018-09-25 22:37
Maybe we should trigger this automatically when we hit the limit? (You're likely to hit the limit with some of our plugins.)

**Comment by matthew-carroll** [comment] 2018-09-26 00:53
Seems reasonable to support.  I agree with the earlier comment that it should not be enabled by default.  We might consider exposing this via pubspec for ephemeral projects.  Once the host app is made editable, it's up to the developer to deal with this, I think.

**Comment by slightfoot** [comment] 2018-09-28 01:52
I just upgraded to Android Studio 3.2.0 and saw this in the notes:
> Native multi-dex enabled by default: The Android plugin for Gradle now enables native multidex for all modules that set minSdkVersion = 21 or higher.

This might have an effect on this ticket.

**Comment by filiph** [comment] 2018-09-28 03:09
Agreed. Just setting minSdkVersion = 21 in `build.gradle` makes the multidex issue go away. But Flutter has minSdkVersion set to 16 by default, and it's one of the selling points of the SDK.

**Comment by slightfoot** [comment] 2018-09-28 09:07
My earlier remark was not to set the minSdk, but rather to be aware of the build change, just in case the app developer changes the minSdk to 21 or above and screws up the possible fix for this ticket.

**Comment by slightfoot** [comment] 2018-09-28 09:09
Either way you always going to need the `multiDexKeepFile` or some of the initialisation files might go in classes2.dex or something and the app fails to load.

**Comment by raveesh-me** [comment] 2018-10-01 03:00
> Maybe we should trigger this automatically when we hit the limit? (You're likely to hit the limit with some of our plugins.)

This would be amazing...

**Comment by drexel-ue** [comment] 2018-11-10 13:47
I've just run into the same issue trying to build

`D8: Cannot fit requested classes in a single dex file (# methods: 85866 > 65536)`

attempting the fix now

**Comment by uppercase-army** [comment] 2018-11-13 16:31
@drexel-ue i've just run into it now, do you have any fix?

**Comment by slightfoot** [comment] 2018-11-14 08:58
Enable Multidex as described here, and adjust it with my instructions in the description of the ticket.
https://developer.android.com/studio/build/multidex

If that doesn't work, today is Wednesday which is Flutter #HumpDayQandA and you can join us on Zoom to chat about the issue and resolve it. https://tinyurl.com/HumpDayQandA

**Comment by Leisser** [comment] 2019-01-01 16:06
Am new to flutter and also to app-dev but not sure how i must treat this code`@Override

protected void attachBaseContext(Context base)
{
    super.attachBaseContext(base);
    MultiDex.install(this);
}`

in my flutter application, am i supposed to put it in my main.dart. Am too confused.

**Comment by wtoalabi** [comment] 2019-02-09 13:54
> Am new to flutter and also to app-dev but not sure how i must treat this code
> 
> `@Override protected void attachBaseContext(Context base) { super.attachBaseContext(base); MultiDex.install(this); }`
> 
> in my flutter application, am i supposed to put it in my main.dart. Am too confused.
> 
> I've edited my app/build.gradle script and enabled multiDexEnabled, added implementation 'com.android.support:multidex:1.0.3' and multiDexKeepFile file('multidex-flutter.txt').
> The app crashes on after installation, thought am only missing the override bit but don't know how to handle it.

I am seriously looking for a solution to this.
I found this: https://stackoverflow.com/questions/53740908/flutter-enable-multidex-for-sdk-less-than-21
But just like you, no way to know where to put that snippet of code.

**Comment by slightfoot** [comment] 2019-02-09 14:25
For those that are having problems.. follow these instructions.
1. Open Android Studio and choose "Open and existing Android Studio project" and choose the `android` directory inside your project directory.
2. Wait for gradle to sync.
3. In the project explorer panel on the left open the app/java folder and keep expanding down until you find `MainActivity.java` then right click on the parent folder and choose `New > Java Class`. Name the new class appropriately for your app. I'll use `ExampleApp`. (do not actually use this name)
4. In the new `ExampleApp.java` file edit your class to extend from `FlutterApplication`, and override `attachBaseContext` the result should look similar to below, save it.
    ```
    package com.example.mobile;

    import android.content.Context;

    import android.support.multidex.MultiDex;
    import io.flutter.app.FlutterApplication;


    public class ExampleApp extends FlutterApplication
    {
        @Override
        protected void attachBaseContext(Context base)
        {
            super.attachBaseContext(base);
            MultiDex.install(this);
        }
    }
    ```
    If you have any red errors or issues. Open your `app` modules `build.gradle` script and add this line to your `dependencies` section and run gradle sync again.
    `compileOnly files("$flutterRoot/bin/cache/artifacts/engine/android-x64/flutter.jar")`

5. Now expand the `manifests` section in your project explorer and open AndroidManifest.xml. Find the `<application>` tag delete the contents of the `android:name` attribute and replace it with `.ExampleApp` (the name of your class from the previous step).

Those instructions show you how to create a android Application class and attach MultiDex support library to it. More info can be found here: https://developer.android.com/studio/build/multidex

Don't forget you'll need to add `multiDexEnabled true` and `multiDexKeepFile file('multidex-flutter.txt')` to your `defaultConfig` in your `build.gradle` file. Place the multidex-flutter.txt in your `android\app` folder. Example: [multidex-flutter.txt](https://github.com/flutter/flutter/files/2320127/multidex-flutter.txt)
   ```
   io/flutter/app/FlutterApplication.class
   io/flutter/view/FlutterMain.class
   io/flutter/util/PathUtils.class
   ```

Side Note: If you upgrade your Android project to use AndroidX then you'll need to change the dependency from `com.android.support:multidex:1.0.3` to `androidx.multidex:multidex:2.0.0` and replace `android.support.multidex.MultiDex` with `androidx.multidex.MultiDex`. Migration details here: https://developer.android.com/jetpack/androidx/migrate

**Comment by wtoalabi** [comment] 2019-02-09 14:45
Very detailed.
Thanks so much!
Here are my issues...Note that this is a fresh flutter installation with only a handful official plugins installed for firebase.

Following your instructions, here are my observations and where i'm stuck:

1. In the newly created java class file, this line:
`import android.support.multidex.MultiDex;`
shows "Cannot resolve symbol "MultiDex"

2. I think this has to do with the error you warned about, so I added:
` compileOnly files("$flutterRoot/bin/cache/artifacts/engine/android-x64/flutter.jar")`
to my gradle.build dependencies.
However, I cant see where to "sync gradle again" as you advised.
And also, I am not sure if "$flutterRoot" should be passed in raw as it is, or if I should change that string to the directory of my flutter sdk.

I dont feel comfortable going further with the rest of the instructions until I am able to sort these 2 out.
Thanks so much for your help!

**Comment by slightfoot** [comment] 2019-02-09 15:24
You need to have `implementation 'com.android.support:multidex:1.0.3'` in your app module `dependencies` section.

**Comment by wtoalabi** [comment] 2019-02-09 19:53
Apologies if I am sounding so dumb....I cant see where to sync gradle.
I have added the line as suggested, yet the `Cannot resolve symbol MultiDex` still shows.
I am on the latest Android Studio (3.3.1)

**Comment by wtoalabi** [comment] 2019-02-10 21:58
So, I realise I cant beat the 64k limit, at least not with my constraints (below 20SDKs are a must). I eventually  settled with adding Proguard to the debug section of my buildTypes (within the project level build.gradle  file).
The result was the same, as I got over 43,000 methods scrapped, to give me just a little above 27,000 methods.
And now, I get to test and debug my app on low SDK phones without hitting the limits as Proguards does amazing job of scrapping off unused methods.
Shout out to @slightfoot for helping me out...even via screen sharing sessions.
I am grateful!

**Comment by Leisser** [comment] 2019-02-15 15:43
@slightfoot thanks for the help am humbled.

**Comment by fritz-playmaker** [comment] 2019-02-19 16:03
> ## Steps to Reproduce
> Build app with more than 64K methods.
> 
> ## Logs
> > The number of method references in a .dex file cannot exceed 64K.
> > Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
> 
> ## Recommended Changes
> 1. Project template or `flutter.gradle` script should set the `multiDexEnabled` property to true, and add the `multiDexKeepFile file('multidex-flutter.txt')` config file. Example: [multidex-flutter.txt](https://github.com/flutter/flutter/files/2320127/multidex-flutter.txt)
>    ```
>    io/flutter/app/FlutterApplication.class
>    io/flutter/view/FlutterMain.class
>    io/flutter/util/PathUtils.class
>    ```
> 2. Project template or `flutter.gradle` script should add the multidex dependency.
>    `implementation 'com.android.support:multidex:1.0.3'`
> 3. FlutterApplication should have the following addition.
>    ```java
>    @Override
>    protected void attachBaseContext(Context base)
>    {
>        super.attachBaseContext(base);
>        MultiDex.install(this);
>    }
>    ```
> 
> **Adding the `multiDexKeepFile` is important as the `FlutterApplication` class and its dependencies are required to me in the primary dex file or the Application class may its onCreate lifecycle event.**
> 
> ```
> Flutter 0.5.7 • channel v0.5.7 • https://github.com/slightfoot/flutter
> Framework • revision 66091f9696 (7 weeks ago) • 2018-07-09 12:52:41 -0700
> Engine • revision 6fe748490d
> Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
> ```

How i do this in VSCode

**Comment by Leisser** [comment] 2019-02-19 16:40
Its not about the editor its about the changes to be done on the specified pages check slightfoot's detailed solution above

**Comment by kabyanil** [comment] 2019-02-24 14:19
been trying to solve this problem for more than a month. flutter should be able to add multidex functionality automatically when total methods reach 64k. the iOS development cycle is noticeably smoother than Android because of android's multidex problem. flutter should be smart enough to handle tasks like these by itself so that developers can focus on their actual development, rather than spending days to fix issues. hope next version of flutter will fix this!

**Comment by mrgoonie** [comment] 2019-03-01 17:21
JUST. CAN'T. FIX. THIS. ISSUE. FOR. DAYS!!! Really frustrated ! 😭

**Comment by wtoalabi** [comment] 2019-03-02 10:04
@mrgoonie @kabyanil Maybe you can read about my work around [here](https://medium.com/@olawale_alabi/android-flutter-64k-methods-dex-limit-how-to-use-proguard-in-development-728af11a4e22)?

**Comment by kabyanil** [comment] 2019-03-02 13:05
> @mrgoonie @kabyanil Maybe you can read about my work around [here](https://medium.com/@olawale_alabi/android-flutter-64k-methods-dex-limit-how-to-use-proguard-in-development-728af11a4e22)?

I tried your solution but Gradle's throwing an error in `signingConfigs.release` portion.
here is my build.gradle

`
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.worldconnect"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        
        multiDexEnabled true
    }


    
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
        }
        debug {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.android.support:multidex:1.0.3'
}

`

**Comment by mrgoonie** [comment] 2019-03-03 15:39
> @mrgoonie @kabyanil Maybe you can read about my work around [here](https://medium.com/@olawale_alabi/android-flutter-64k-methods-dex-limit-how-to-use-proguard-in-development-728af11a4e22)?

Tried bro, it's not working for my case 😢

**Comment by yvanvds** [comment] 2019-03-26 08:47
If you need a simple workaround, you can just increase minSdkVersion from 16 to 21 in the applevel build.gradle. You will loose support for devices with android < 5.0, but that's only 10 percent of them.

**Comment by jamespfinn** [comment] 2019-03-26 16:31
To resolve this all I had to do was add `multDexEnabled true` to the `defaultConfig` section of my `app/build.gradle`.  e.g.:

```
    defaultConfig {
        applicationId "com.here.yourapp"
        minSdkVersion 16
        // adding the below line resolved https://github.com/flutter/flutter/issues/21009 for me.
        multiDexEnabled true
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

**Comment by trentturvey** [comment] 2019-03-29 12:13
> To resolve this all I had to do was add `multDexEnabled true` to the `defaultConfig` section of my `app/build.gradle`. e.g.:
> 
> ```
>     defaultConfig {
>         applicationId "com.here.yourapp"
>         minSdkVersion 16
>         // adding the below line resolved https://github.com/flutter/flutter/issues/21009 for me.
>         multiDexEnabled true
>         targetSdkVersion 28
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }
> ```

I can confirm, this solved my issue too! thank you

**Comment by RobbinDG** [comment] 2019-04-20 17:41
This also solved the issue for me. Works like a charm now. Thanks!

**Comment by HiroshiHorie** [comment] 2019-07-13 08:39
@jamespfinn Is this enough to enable multidex ?

**Comment by AubergineDevelopers** [comment] 2019-08-01 10:08
> Correct. Just setting minSdkVersion = 21 in `build.gradle` makes the multidex issue go away. But Flutter has minSdkVersion set to 16 by default, and it's one of the selling points of the SDK.

Flutter app crashes as we do this.

**Comment by vshashi01** [comment] 2019-08-14 12:21
![image](https://user-images.githubusercontent.com/28664567/63020533-f71f2800-bed0-11e9-8dea-313c960d54ad.png)
Adding multidexEnabled to true causes the gradle build to fail, what could be the reason for this?

![image](https://user-images.githubusercontent.com/28664567/63020588-1c139b00-bed1-11e9-88f3-6a60396f59b1.png)

**Comment by slightfoot** [comment] 2019-08-14 15:55
> ![image](https://user-images.githubusercontent.com/28664567/63020533-f71f2800-bed0-11e9-8dea-313c960d54ad.png)
> Adding multidexEnabled to true causes the gradle build to fail, what could be the reason for this?
> 
> ![image](https://user-images.githubusercontent.com/28664567/63020588-1c139b00-bed1-11e9-88f3-6a60396f59b1.png)

`multiDexEnabled` note the capital D for Dex.

**Comment by qq3144225600** [comment] 2019-08-22 06:24
> ## 重现步骤
> 使用超过64K的方法构建应用程序。
> 
> ## 日志
> > .dex文件中的方法引用数不能超过64K。
> > 请访问[https://developer.android.com/tools/building/multidex.html，](https://developer.android.com/tools/building/multidex.html)了解如何解决此问题[](https://developer.android.com/tools/building/multidex.html)
> 
> ## 推荐的更改
> 1. 项目模板或`flutter.gradle`脚本应将该`multiDexEnabled`属性设置为true，并添加`multiDexKeepFile file('multidex-flutter.txt')`配置文件。示例：[multidex-flutter.txt](https://github.com/flutter/flutter/files/2320127/multidex-flutter.txt)
>    ```
>    io/flutter/app/FlutterApplication.class
>    io/flutter/view/FlutterMain.class
>    io/flutter/util/PathUtils.class
>    ```
> 2. 项目模板或`flutter.gradle`脚本应添加multidex依赖项。
>    `implementation 'com.android.support:multidex:1.0.3'`
> 3. FlutterApplication应该有以下添加。
>    ```java
>    @覆盖
>    保护 空隙 attachBaseContext（上下文基）
>    {
>        超。attachBaseContext（基峰）;
>        MultiDex 。安装（这）;
>    }
>    ```
> 
> **添加它`multiDexKeepFile`很重要，因为`FlutterApplication`在主dex文件中我需要类及其依赖项，或者Application类可能是onCreate生命周期事件。**
> 
> ```
> Flutter 0.5.7 • channel v0.5.7 • https://github.com/slightfoot/flutter
> Framework • revision 66091f9696 (7 weeks ago) • 2018-07-09 12:52:41 -0700
> Engine • revision 6fe748490d
> Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
> ```

FlutterApplication怎么修改

**Comment by qq3144225600** [comment] 2019-08-22 06:32
Will the FlutterApplication be modified there?

**Comment by Iampato** [comment] 2019-09-04 12:39
Any solution rather than changing the min android version ?

**Comment by jamespfinn** [comment] 2019-09-04 14:33
> Any solution rather than changing the min android version ?

Yes, see my comment above. 
https://github.com/flutter/flutter/issues/21009#issuecomment-476733365

**Comment by slightfoot** [comment] 2019-09-04 14:51
> Any solution rather than changing the min android version ?

This is what the description is all about.
Please make sure you also add `multiDexKeepFile file('multidex-flutter.txt')` as noted previously. It's not in comment #21009

**Comment by manacespereira** [comment] 2019-10-04 17:52
Change your minSdjVersion from 16 to 21

**Comment by netopaez97** [comment] 2019-10-09 18:37
Yo should add 
`android {
    defaultConfig {
        //other tasks
        multiDexEnabled true
    }
}`

And it works.

**Comment by Sese-Schneider** [comment] 2019-10-09 20:30
@slightfoot maybe you could add a flag to the `pubspec.yaml` to activate MutliDex building?
`multiDex: true`

similar to this https://github.com/flutter/flutter/issues/28805

**Comment by JSANL** [comment] 2019-10-20 19:11
Currently I ran into an issue with firebase and I set up a minimal reproducible example for a ticket.
I already had the experience of knowing about this issue but I think it's just incomprehensible how every new flutter developer has to go through this experience when using firebase. 
It's not even (as far as I can see) mentioned in the documentation of the plugin. Maybe somewhere in a codelab, but if you just install the plugin and follow the instructions you will hit that error.

I think the idea from @Hixie 
> Maybe we should trigger this automatically when we hit the limit? (You're likely to hit the limit with some of our plugins.)

is pretty good.

**Comment by xster** [comment] 2020-01-09 19:27
Are you running into this issue by:

1- Starting with a `flutter create`d project and just adding a bunch of plugins and hit the 65k limit?
2- Starting with a `flutter create`d project, but then went into the android/ directory and added a bunch additional custom java/kotlin code (add-to-Flutter)?
3- Started with an existing Android app and adding a Flutter module to it which caused it to go over the 65k limit (add-to-app)?

I don't think we should be doing this automatically if it's cases 2 and 3. In case 2, the user is essentially doing regular Android development and taking ownership of the project. Flutter tools shouldn't try to concurrently drive it as well. In case 3, the Android project is entirely outside of the awareness of the Flutter tools so we can't do it either. 

Case 1 is reasonable and seems plausible. The flutter_gallery is at 20,506 methods. Just the exoplayer plugin brings in ~8k.

**Comment by edjostenes** [comment] 2020-01-15 16:02
It worked for me. Bellow the ExampleApp in kotlin:

`package com.example.mobile;

import android.content.Context
import androidx.multidex.MultiDex;
import io.flutter.app.FlutterApplication;

class ExampleApp  : FlutterApplication() {
    override fun attachBaseContext(base: Context)
    {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
}`

**Comment by edjostenes** [comment] 2020-01-15 16:13
> For those that are having problems.. follow these instructions.
> 
> 1. Open Android Studio and choose "Open and existing Android Studio project" and choose the `android` directory inside your project directory.
> 2. Wait for gradle to sync.
> 3. In the project explorer panel on the left open the app/java folder and keep expanding down until you find `MainActivity.java` then right click on the parent folder and choose `New > Java Class`. Name the new class appropriately for your app. I'll use `ExampleApp`. (do not actually use this name)
> 4. In the new `ExampleApp.java` file edit your class to extend from `FlutterApplication`, and override `attachBaseContext` the result should look similar to below, save it.
>    ```
>    package com.example.mobile;
>    
>    import android.content.Context;
>    
>    import android.support.multidex.MultiDex;
>    import io.flutter.app.FlutterApplication;
>    
>    
>    public class ExampleApp extends FlutterApplication
>    {
>        @Override
>        protected void attachBaseContext(Context base)
>        {
>            super.attachBaseContext(base);
>            MultiDex.install(this);
>        }
>    }
>    ```
>    
>    
>    If you have any red errors or issues. Open your `app` modules `build.gradle` script and add this line to your `dependencies` section and run gradle sync again.
>    `compileOnly files("$flutterRoot/bin/cache/artifacts/engine/android-x64/flutter.jar")`
> 5. Now expand the `manifests` section in your project explorer and open AndroidManifest.xml. Find the `<application>` tag delete the contents of the `android:name` attribute and replace it with `.ExampleApp` (the name of your class from the previous step).
> 
> Those instructions show you how to create a android Application class and attach MultiDex support library to it. More info can be found here: https://developer.android.com/studio/build/multidex
> 
> Don't forget you'll need to add `multiDexEnabled true` and `multiDexKeepFile file('multidex-flutter.txt')` to your `defaultConfig` in your `build.gradle` file. Place the multidex-flutter.txt in your `android\app` folder. Example: [multidex-flutter.txt](https://github.com/flutter/flutter/files/2320127/multidex-flutter.txt)
> 
> ```
> io/flutter/app/FlutterApplication.class
> io/flutter/view/FlutterMain.class
> io/flutter/util/PathUtils.class
> ```
> 
> Side Note: If you upgrade your Android project to use AndroidX then you'll need to change the dependency from `com.android.support:multidex:1.0.3` to `androidx.multidex:multidex:2.0.0` and replace `android.support.multidex.MultiDex` with `androidx.multidex.MultiDex`. Migration details here: https://developer.android.com/jetpack/androidx/migrate

It worked for me. Bellow the ExampleApp in kotlin:

`package com.example.mobile;

import android.content.Context
import androidx.multidex.MultiDex;
import io.flutter.app.FlutterApplication;

class ExampleApp : FlutterApplication() {
override fun attachBaseContext(base: Context)
{
super.attachBaseContext(base);
MultiDex.install(this);
}
}`

**Comment by JSANL** [comment] 2020-01-16 00:23
@xster 

> 1- Starting with a flutter created project and just adding a bunch of plugins and hit the 65k limit?
2- Starting with a flutter created project, but then went into the android/ directory and added a bunch additional custom java/kotlin code (add-to-Flutter)?
3- Started with an existing Android app and adding a Flutter module to it which caused it to go over the 65k limit (add-to-app)?

Case 1 - Literally just `flutter create`, add `cloud_firestore` (per documentation) and voila ;)
Like I said, I now know exactly what is going on, but I think this is just unnecessarily hostile for new developers.

**Comment by xster** [comment] 2020-01-16 23:23
Ah understood. Thanks for the clarification. If the user can get into this state by just staying on the Flutter side, never touching any Android code, and still end up with this issue, then I agree, we should perform this automatically if we can detect that the user has never altered their build.gradle and/or MainActivity. 

We should likely let @blasten finish his work of clarifying the file ownership of the various files in the project before doing this.

**Comment by JSANL** [comment] 2020-01-16 23:42
Well what I meant with

>  cloud_firestore (per documentation)

was adding 'cloud_firestore' to the pubspec, adding the necessary lines to the `build.gradle` and downloading the `google-services.json` file and then running the project. Sorry for being so vague.

Why shouldn't it be added automatically in this case? The thing is, that I still remember the first time having this problem, where there was not even the helpful answer on stackoverflow. I was basically stuck because I had (oder realistically have) no experience with gradle nor did I even necessarily know what everything did in the setup steps. It would've been immensely helpful that the flutter tool handels that. Because I think many developers are new to flutter and I don't think that they should be overloaded with all the things to learn on the flutter side **and** on the gradle side directly.   
I mean a goal of flutter is to be easy and quick to pick up, no?

**Comment by xster** [comment] 2020-03-10 22:30
We should use https://github.com/flutter/flutter/issues/40460 to do this for [case 1](https://github.com/flutter/flutter/issues/21009#issuecomment-572716200). If we don't use `flutter migrate`, the best case we should do is a web page at flutter.dev with instructions.

**Comment by LostInDarkMath** [comment] 2020-03-21 19:59
Hi,
I have a similar issue to https://github.com/FirebaseExtended/flutterfire/issues/1340. Can you please tell where I can find the `FlutterApplication` file?

**Comment by xster** [comment] 2020-04-09 22:14
@blasten is this still in your queue for the April milestone?

**Comment by blasten** [comment] 2020-04-09 22:57
@xster I updated the milestone. I think it might be worth having a doc with the minimal set of changes required to support this feature.

**Comment by xster** [comment] 2020-04-09 23:00
I think the MVP is to just have a flutter.dev page describing the manual steps. Going in and modifying user owned content like the .java files will be very custom until the dependency https://github.com/flutter/flutter/issues/40460 is ready.

**Comment by zanderso** [comment] 2020-06-23 21:44
@blasten @xster Should the milestone on this be updated?

**Comment by julienduchow** [comment] 2021-07-06 17:47
> Hi,
> I have a similar issue to [FirebaseExtended/flutterfire#1340](https://github.com/FirebaseExtended/flutterfire/issues/1340).
> 
> I've been trying to get this to work for days now, but it doesn't work.
> In view of your tutorial [#21009 (comment)](https://github.com/flutter/flutter/issues/21009#issuecomment-462048805), I hang in step 3, because I don't find a file named `MainActivity.java`. I searched the whole project tree for it.
> 
> Currently, my files looks like this:
> `app/build.gradle`:
> 
> ```
>     defaultConfig {
>         applicationId "com.myAppName.prototype" 
>         minSdkVersion 18
>         targetSdkVersion 28
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>         multiDexEnabled true
>     }
>    buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>             multiDexKeepFile file('multidex-config.txt')
>         }
>     }
>    ...
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.1.1'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
>     implementation 'com.google.firebase:firebase-analytics:17.2.2'
>     implementation 'com.android.support:multidex:1.0.3'
>     implementation 'androidx.multidex:multidex:2.0.1'
> }
> ```
> 
> File `multidex-config.txt`:
> 
> ```
> com/google/firebase/provider/FirebaseInitProvider.class
> io/flutter/app/FlutterApplication.class
> io/flutter/view/FlutterMain.class
> io/flutter/util/PathUtils.class
> ```
> 
> File `android/app/src/main/java/io/MyApplication.java`:
> 
> ```
> import io.flutter.app.FlutterApplication;
> import android.content.Context;
> // import android.support.multidex.MultiDex; // doesn't work
> import androidx.multidex.MultiDex;
> 
> public class MyApplication extends FlutterApplication {
>     @Override
>     protected void attachBaseContext(Context base) {
>         super.attachBaseContext(base);
>         MultiDex.install(this);
>     }
> }
> ```
> 
> in combination with ` <application android:name="io.MyApplication"`
> in the `app/src/main/AndroidMainfest.xml` file.
> 
> I currently get the following error in LogCat:
> 
> ```
> FATAL EXCEPTION: main
>     Process: com.myAppName.prototype, PID: 11372
>     java.lang.RuntimeException: Unable to instantiate application io.MyApplication: java.lang.ClassNotFoundException: Didn't find class "io.MyApplication" on path: DexPathList[[zip file "/data/app/com.myAppName.prototype-8.apk"],nativeLibraryDirectories=[/data/app-lib/com.myAppName.prototype-8, /vendor/lib, /system/lib]]
> ```
> 
> Could anyone please help me?

Have the same issue, did you found a solution?

**Comment by LostInDarkMath** [comment] 2021-07-06 18:03
@julienduchow I fixed this by following the steps in https://github.com/flutter/flutter/issues/21009#issuecomment-462048805 once again and more carefully.

I also started from scratch with a fresh generated Flutter project and copied my old code in the new one before I tried it again. Hope that helps :)

**Comment by SirFilbido** [comment] 2021-08-16 16:44
Hello,

I'm having a similar problem but in a very different scenario.

I have an Android app using minSDK 21 that has a Flutter module added. So, my project was not made directly in Flutter, but in native Android and which has a Flutter module, in which we follow this [documentation](https://flutter.dev/docs/development/add-to-app) to implement.

As it is a Flutter module, its files like `.android`,`.ios`, `.dart_tool` cannot be committed. When I run the command `flutter clean` and `flutter pub get`, it erases these files and their settings that I made and recreates them again with the default values, minSDK 16. 

Do you have any solution to overwrite or change the Flutter module minSKD? As I said before, the project is configured for minSDK 21, but this configuration does not reflect in the Flutter module in app native Android.

**Comment by GaryQian** [comment] 2021-09-24 23:30
go/flutter-multidex, outlines some approaches to handling automatic (or non automatic) multidex support

**Comment by blasten** [comment] 2021-09-24 23:31
nice! can we make the doc public?

**Closed** 2021-10-14 00:48 UTC
Labels: severe: new feature, platform-android, tool, t: gradle, customer: crowd, proposal, a: annoyance, passed first triage, P4

**Comment by blasten** [comment] 2021-10-14 00:57
Multidex support has been added to Flutter in the master channel.

The tool will guide you about how to enable multidex in an existing project, 
and it will automatically enable multidex when necessary if the project is new.

**Comment by zanderso** [comment] 2021-10-14 05:24
https://github.com/flutter/flutter/pull/90944 broke some things. Reverting here https://github.com/flutter/flutter/pull/91791 and re-opening this as a result.

**Comment by blasten** [comment] 2021-10-20 18:16
PR relanded
