### ISSUE TITLE
TextField resize issue

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#18805] opened 2018-06-25 20:03 UTC
I have a TextField inside a stacked scafold (the outer one contains a bottombar and the inner one a tabbar with a pageView below it containing the textfield), I've had to set ``resizeToAvoidBottomPadding: false`` in order to keep the textfield from disappearing when the keyboard pops-up.
I need to have the textfield occupy the whole available pageview's area, which I can accomplish visually with ``maxLines = null`` and ``InputDecoration.collapsed``, The issue that I have (might be related to the scafold flag) is that when the keyboard pops-up, the textview does not resize, so the keyboard appears over what you're writing.
I tried Enveloping the Textfield in a container with a ``BoxConstraints.loose`` and that allows me to limit it's height, but then it never spans the rest of the pageview.

What's the correct way to have the TextField occupy the whole pageView and have it resize when the keyboard pops-up? is the container approach the appropriate one? Maybe there's a way to change the boxContraints when the keyboard pops-up, although that seems a lot of work.

**Comment by d-silveira** [comment] 2018-06-25 20:32
fixed it wrapping with an expanded instead of a container, but the question remains, shouldn't the resize be automatic?

**Comment by zoechi** [comment] 2019-01-22 17:44
Duplicate of #18341, #9780

**Closed by zoechi** 2019-01-22 17:44 UTC
Labels: f: material design, framework

**Comment by patelkrunal78** [comment] 2019-10-06 06:19
To adjust the width, you could wrap your TextField with a Container widget, like so:

new Container(
width: 100.0,
child: new TextField()
)

Find Full Code At [Here](https://icetutor.com/question/how-to-update-flutter-textfields-height-and-width)
