### ISSUE TITLE
W/Gralloc3: mapper 3.x is not supported -->64-bit APK Fails to Load After Submitting to App Store

### ISSUE THREAD

**Issue by fatherchill** [flutter/flutter#57112] opened 2020-05-13 14:13 UTC
Error message: W/Gralloc3: mapper 3.x is not supported
E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"

Specifically has failed on Pixel 3 and a Hauwei P30 Pro.

Have app published in App Store, but after updating to Flutter 1.17.0 and updating packages 64-bit APK does not run **after** uploading to Google Play Store. It will show splash screen and then just a blank white/gray screen.

The APK works on emulator and Pixel 3 before sending to App Store, it is only the derived APK that is failing. Failing APK https://drive.google.com/file/d/1JW3hzXGmrLZ4Ex_vGtecfNxWQDZkDBCJ/view?usp=sharing

But the 32-bit APK for the same build works fine.

I have refactored several parts of the app, created a new flutter project and moved application files over, and changed the targetSDK and compileSDK between 28-29.

**EDIT** App continues to work before uploading split apks to play store. However, flutter run -v does identify the issue, yet it is able to continue.

**EDIT 2** Related to https://github.com/flutter/flutter/issues/50405

## Steps to Reproduce
Failing APK https://drive.google.com/file/d/1JW3hzXGmrLZ4Ex_vGtecfNxWQDZkDBCJ/view?usp=sharing

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:**
A working app from the store.

**Actual results:**
Splash screen, then white screen.

<details>
  <summary>Logs</summary>

Logcat

```
2020-05-13 08:37:54.849 10239-10239/? E/icanchurchkeny: Not starting debugger since process cannot load the jdwp agent.
2020-05-13 08:37:54.892 10239-10239/? I/Adreno: QUALCOMM build                   : 4a00b69, I4e7e888065
    Build Date                       : 04/09/19
    OpenGL ES Shader Compiler Version: EV031.26.06.00
    Local Branch                     : mybranche95a5ea3-cf05-f19a-a0e7-5cb90179c3d8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-05-13 08:37:54.892 10239-10239/? I/Adreno: Build Config                     : S P 8.0.6 AArch64
2020-05-13 08:37:54.893 10239-10239/? I/Adreno: PFP: 0x016ee183, ME: 0x00000000
2020-05-13 08:37:55.106 626-626/? I/hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
2020-05-13 08:37:55.106 10239-10260/? W/Gralloc3: mapper 3.x is not supported
2020-05-13 08:37:55.107 10239-10239/? W/RenderThread: type=1400 audit(0.0:1438): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20109 scontext=u:r:untrusted_app:s0:c131,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2020-05-13 08:37:55.109 10239-10260/? E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
2020-05-13 08:37:55.120 1436-1499/? I/ActivityTaskManager: Displayed org.worldliturgy.anglicanchurchkenya/.MainActivity: +303ms
2020-05-13 08:37:55.130 1436-1499/? I/ActivityTaskManager: Fully drawn org.worldliturgy.anglicanchurchkenya/.MainActivity: +316ms
2020-05-13 08:37:55.136 942-942/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
2020-05-13 08:37:55.257 10239-10263/? I/flutter: visitation transferred from 2020-05-31 00:00:00.000Z to 2020-06-01 00:00:00.000Z
2020-05-13 08:37:55.320 2979-2979/? D/ImageWallpaper: wallpaper visibility changes to: false
2020-05-13 08:37:55.332 669-669/? E/Layer: [Surface(name=AppWindowToken{d13f7bf token=Token{4cbb9de ActivityRecord{9e4c519 u0 org.worldliturgy.anglicanchurchkenya/.MainActivity t19202}}})/@0xa942689 - animation-leash#0] No local sync point found
2020-05-13 08:37:55.332 669-669/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 1 line
2020-05-13 08:37:55.332 669-669/? E/Layer: [Surface(name=AppWindowToken{d13f7bf token=Token{4cbb9de ActivityRecord{9e4c519 u0 org.worldliturgy.anglicanchurchkenya/.MainActivity t19202}}})/@0xa942689 - animation-leash#0] No local sync point found
2020-05-13 08:37:55.332 669-669/? E/Layer: [Surface(name=AppWindowToken{80ca26 token=Token{24e4981 ActivityRecord{f0d1168 u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t19170}}})/@0x931d636 - animation-leash#0] No local sync point found
2020-05-13 08:37:55.332 669-669/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 1 line
2020-05-13 08:37:55.332 669-669/? E/Layer: [Surface(name=AppWindowToken{80ca26 token=Token{24e4981 ActivityRecord{f0d1168 u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t19170}}})/@0x931d636 - animation-leash#0] No local sync point found
2020-05-13 08:37:55.376 5057-9945/? I/PBSessionCacheImpl: Deleted sessionId[22242510569775502] from persistence.
2020-05-13 08:37:55.691 5057-5300/? W/SearchServiceCore: Abort, client detached.
2020-05-13 08:37:55.697 5057-5300/? I/StreamController: cleanUpControllerScope(nowcards-15-7a8ac2-0cd0)
2020-05-13 08:37:56.861 10239-10263/? I/flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```
Another Log
```
2020-05-13 22:16:04.514 3465-3465/? I/icanchurchkeny: Late-enabling -Xcheck:jni
2020-05-13 22:16:04.570 3465-3465/? E/icanchurchkeny: Unknown bits set in runtime_flags: 0x8000
2020-05-13 22:16:04.708 3465-3513/org.worldliturgy.anglicanchurchkenya I/ResourceExtractor: Resource version mismatch res_timestamp-2070-1589422562907
2020-05-13 22:16:04.907 3465-3513/org.worldliturgy.anglicanchurchkenya I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2020-05-13 22:16:04.908 3465-3513/org.worldliturgy.anglicanchurchkenya I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2020-05-13 22:16:04.939 3465-3513/org.worldliturgy.anglicanchurchkenya I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
2020-05-13 22:16:04.949 3465-3465/org.worldliturgy.anglicanchurchkenya I/Adreno: QUALCOMM build                   : 4a00b69, I4e7e888065
    Build Date                       : 04/09/19
    OpenGL ES Shader Compiler Version: EV031.26.06.00
    Local Branch                     : mybranche95a5ea3-cf05-f19a-a0e7-5cb90179c3d8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-05-13 22:16:04.949 3465-3465/org.worldliturgy.anglicanchurchkenya I/Adreno: Build Config                     : S P 8.0.6 AArch64
2020-05-13 22:16:04.952 3465-3465/org.worldliturgy.anglicanchurchkenya I/Adreno: PFP: 0x016ee183, ME: 0x00000000
2020-05-13 22:16:05.063 3465-3465/org.worldliturgy.anglicanchurchkenya W/icanchurchkeny: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
2020-05-13 22:16:05.064 3465-3465/org.worldliturgy.anglicanchurchkenya W/icanchurchkeny: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
2020-05-13 22:16:05.064 3465-3465/org.worldliturgy.anglicanchurchkenya W/icanchurchkeny: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
2020-05-13 22:16:05.064 3465-3465/org.worldliturgy.anglicanchurchkenya W/icanchurchkeny: Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
2020-05-13 22:16:05.069 3465-3534/org.worldliturgy.anglicanchurchkenya I/flutter: Observatory listening on http://127.0.0.1:42831/jocB4Aed2yk=/
2020-05-13 22:16:05.228 3465-3514/org.worldliturgy.anglicanchurchkenya W/Gralloc3: mapper 3.x is not supported
2020-05-13 22:16:05.230 3465-3514/org.worldliturgy.anglicanchurchkenya E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
```

```
[ +392 ms] Syncing files to device Pixel 3...
[   +1 ms] Scanning asset files
[   +9 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:kenya_liturgy/main.dart 539e3319-d9d3-495e-a32f-3bb4914cfa99
[        ] <- 539e3319-d9d3-495e-a32f-3bb4914cfa99
[        ] W/Gralloc3(20973): mapper 3.x is not supported
[        ] W/RenderThread(20973): type=1400 audit(0.0:5374): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20109 scontext=u:r:untrusted_app:s0:c143,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file
permissive=0
[        ] E/libc    (20973): Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
[        ] I/flutter (20973): Debug #  1
[  +93 ms] Updating files
[   +7 ms] I/flutter (20973): Debug #  2
[  +22 ms] I/flutter (20973): Debug #  3
[ +327 ms] I/flutter (20973): Debug #  4
[  +20 ms] I/flutter (20973): Debug #  5
[        ] I/flutter (20973): Debug #  6
[        ] I/flutter (20973): Debug #  7
[   +9 ms] I/flutter (20973): Debug #  8
[        ] I/flutter (20973): Debug #  9
[        ] I/flutter (20973): Debug #  10
[        ] I/flutter (20973): Debug #  11
[   +3 ms] I/flutter (20973): Debug #  12
[  +12 ms] I/flutter (20973): Debug #  13
[   +1 ms] I/flutter (20973): Debug #  14
[+1524 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 3... (completed in 2,038ms, longer than expected)
[        ] Synced 13.3MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x715d514620, isolate: {type: @Isolate, fixedId: true, id: isolates/3689295852469351, name: main.dart$main-3689295852469351, number: 3689295852469351}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x715d514620.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
```

```
$ flutter analyze
Analyzing android...                                                    
No issues found! (ran in 0.6s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

```
name: name
description: app
version: 2.0.63+2063

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  xml: '^3.0.0'

  #library to convert the xml files to json
  xml2json: '>=4.2.0'

  #to transform the JSON into Dart object
  #works with build_runner and json_serializable
  json_annotation: '>=3.0.1'

  #add function to capitalize
  strings: '>=0.1.2'
  auto_size_text: '^2.1.0'

  path_provider: ">=1.6.7"

  #  good looking calendar
  flutter_calendar: '>=0.0.9'

  # storing user preferences on both android and iOs
  shared_preferences: '>=0.5.7'

dev_dependencies:
  flutter_test:
    sdk: flutter

  #works with json_annotation. see above
  build_runner: '>=1.9.0'
  json_serializable: '>=3.3.0'


  assets:
    - assets/wlp_format/docs/prayerBooks.xml
    - assets/wlp_format/docs/calendar.xml
    - assets/wlp_format/docs/tenziZaRohoni.xml

    - assets/bibles/WEB/metadata.xml
    - assets/bibles/WEB/release/versification.vrs
    - assets/bibles/WEB/release/USX_4/

    - assets/bibles/SUV.xml
    - assets/songBooks/english_songs/songs/


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-SemiBold.ttf
          weight: 600

```

</details>

**Comment by TahaTesser** [comment] 2020-05-14 10:46
Mentioned issue is reopened and labeled
Closing as duplicate of https://github.com/flutter/flutter/issues/50405#issuecomment-595308935

**Comment by pedromassangocode** [comment] 2020-12-02 10:30
Closing as duplicate of  https://github.com/flutter/flutter/issues/50405 because the reported logs are the same.

**Closed by pedromassangocode** 2020-12-02 10:30 UTC
Labels: P4, dependency: android, engine, platform-android, severe: crash
