### ISSUE TITLE
`TimePicker` color and visual issues

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#127035] opened 2023-05-17 15:52 UTC
#91605

I think we should make small visual changes to the TimePicker:

1. Change the "Period selector label text" to "On surface variant" for a non-selected color.

`from specification`
<img width="53" alt="unnamed" src="https://github.com/flutter/flutter/assets/102767277/674cf490-665a-4a68-a538-b514061b5085">

`from flutter`
![Screenshot_2023_05_17_15_13_09_717_com_example_material_3_demo](https://github.com/flutter/flutter/assets/102767277/234e7c98-1205-4842-89df-896434cdb534)

2. In the "Time picker input" change the width of the period selection container, making it the same as in the time picker with the (12 hour) selector.

1 | 2
--- | ---
![Screenshot_2023_05_17_15_45_35_739_com_example_material_3_demo](https://github.com/flutter/flutter/assets/102767277/b3b7a826-4cca-493e-aa7a-248d65bf9fed) | ![Screenshot_2023_05_17_15_45_15_624_com_example_material_3_demo](https://github.com/flutter/flutter/assets/102767277/b8c82e71-74a4-4451-bfef-5899f92c11ec)

3. In the "Time picker dial" reduce the width of the period selector container, making it a width (114 dp), which is slightly larger than with the selector (12 hour).

`example Flutter / Compose`
![Screenshot_2023_05_17_15_21_10_535_androidx_compose_material_catalog](https://github.com/flutter/flutter/assets/102767277/69b9177b-4712-44a4-ba73-889dfdf845aa)

**Comment by raghav042** [comment] 2023-05-24 10:11
M3 Timepicker UI is cropped.
![Screenshot_20230524-153517](https://github.com/flutter/flutter/assets/88577550/2af22fd6-be8a-4fc3-9229-f916c2f36d1f)
![Screenshot_20230524-153521](https://github.com/flutter/flutter/assets/88577550/28f002ad-d0e1-4821-a19e-c2efa0eb5197)

**Comment by MaxYablochkin** [comment] 2023-05-24 11:48
See also Numeric values bouncing in the time picker container


https://github.com/flutter/flutter/assets/102767277/638637a0-2f1d-4d43-aed2-b0ebd6569f01

**Comment by HansMuller** [comment] 2023-05-24 19:17
@guidezpl - what do you think of this proposal? 

@MaxYablochkin - https://github.com/flutter/flutter/issues/127035#issuecomment-1560837171 looks like a bug. Does this occur because the app's text scale factor has been increased?

**Comment by MaxYablochkin** [comment] 2023-05-24 23:44
It is noticeable that this happens when switching the time format 24, 12 hours.

**Comment by guidezpl** [comment] 2023-05-25 09:06
I've numbered the issues raised

1. This should be fixed
2. This is as designed in the spec
3. This should be fixed by growing the time picker height such that the dial keeps its size
4. This should be fixed. The source here might be the use of a custom font or a11y text size which renders it as such. Limiting the size and fading would be preferable to vertical overflow
5. This is a low priority fix, likely an artefact of the border drawing inside its bounds rather than outside. Might be easily fixable by aligning the text on the center line rather than the baseline.

**Comment by darshankawar** [comment] 2023-05-25 13:07
@raghav042 I am unable to replicate the behavior you reported. I tried with official [example](https://api.flutter.dev/flutter/material/showTimePicker.html#material.showTimePicker.4) using latest stable and master running on Pixel 6 api 33 emulator, but didn't see the cropped UI.

<img width="231" alt="Screenshot 2023-05-25 at 6 22 26 PM" src="https://github.com/flutter/flutter/assets/67046386/a7287b1a-afb1-42ff-bcce-7ba606650b8b">
<img width="235" alt="Screenshot 2023-05-25 at 6 23 23 PM" src="https://github.com/flutter/flutter/assets/67046386/5b5b9a80-8480-41a0-8d08-8429df4f99f6">

If this doesn't represent your case, I suggest you to file a new issue and provide relevant details (`flutter doctor -v` and complete minimal reproducible code sample) so that we can properly address the issue you are seeing.

**Comment by raghav042** [comment] 2023-06-21 07:25
### Avobe ui issue is because of incorrect themedata.

`return ThemeData.dark().copyWith(useMaterial3: true);` --> **Cropped Timepicker UI issue**
`return ThemeData.dark(useMaterial3: true).copyWith();` --> **working fine.**

**Comment by sidlatau** [comment] 2023-07-03 10:19
> ### Above ui issue is because of incorrect themedata.
> `return ThemeData.dark().copyWith(useMaterial3: true);` --> **Cropped Timepicker UI issue** `return ThemeData.dark(useMaterial3: true).copyWith();` --> **working fine.**

I can confirm the same behaviour: `.copyWith(useMaterial3: true)` breaks time picker, `ThemeData.dark(useMaterial3: true)` works OK.

**Comment by darshankawar** [comment] 2023-07-04 08:04
Filed new issue https://github.com/flutter/flutter/issues/129941 based on above findings.

**Comment by larrytamnjong** [comment] 2023-07-16 04:13
I faced thesame issue with material 3 time picker UI cropped and @darshankawar solution worked but I think there has to be a better way to prevent such from happening difficult to debug I spent a few hours wondering what's wrong 😂

**Comment by TahaTesser** [comment] 2023-07-25 11:28
Addressing issues mentioned here.

Under https://github.com/flutter/flutter/issues/127035#issue-1714203381
1.  Fixed by https://github.com/flutter/flutter/pull/131253
2. Working as designed
3. Tracking in https://github.com/flutter/flutter/issues/82661

Under https://github.com/flutter/flutter/issues/127035#issuecomment-1560837171
4. See https://github.com/flutter/flutter/issues/129941

Under https://github.com/flutter/flutter/issues/127035#issuecomment-1560971982
5.  Fixed by https://github.com/flutter/flutter/pull/131253. The cause of the issue is explained in https://github.com/flutter/flutter/issues/131247

**Closed** 2023-07-28 14:11 UTC
Labels: framework, f: material design, f: date/time picker, team-design, triaged-design, multiteam-retriage-candidate
