### ISSUE TITLE
[camera] How to capture video from multiple cameras at the same time?

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#103263] opened 2022-05-07 09:27 UTC
Recently, I see many social apps which can capture and save video from both cameras at the same time. 
_I can show my surroundings using the back camera and in a small PIP layout, I can show myself._

What needs to be done to accomplish this without losing fps and resolution?

- Can we record with both cameras at the same time and use ffmpeg to combine 2 videos?
- Can we use image streams from both cameras at the same time to overlay them on each other?

Are there any blockers for this functionality in Flutter?

<img width="331" alt="Screen Shot 2022-05-07 at 12 24 27" src="https://user-images.githubusercontent.com/6442915/167248101-54381515-3ce4-4d0e-b692-fb8379c4c22c.png">

**Comment by stuartmorgan** [comment] 2022-05-07 13:40
As a feature request for the `camera` plugin, this is a duplicate of https://github.com/flutter/flutter/issues/51928

> Are there any blockers for this functionality in Flutter?

Nothing prevents someone from implementing this functionality in a Flutter application, it's just not currently supported by the first-party camera plugin.

**Closed by stuartmorgan** 2022-05-07 13:40 UTC
