### ISSUE TITLE
Resource android:attr/fontVariationSettings not found. SDK location not found

### ISSUE THREAD

**Issue by divyanshkumaar** [flutter/flutter#53674] opened 2020-03-31 18:36 UTC
For AndroidX Migration, I had added 
```
android.useAndroidX=true
android.enableJetifier=true
```
to gradle.properties but still when I tried to 'Migrate to AndroidX', it said 'No usages found in the project.'

Other than that, this is the whole 'run' code followed by the error it shows.
```
D:\Project\New>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\Project\New\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:189: error: resource android:attr/fontVariationSettings not found.
  D:\Project\New\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:190: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\15820ac8876d3772b68f5299fe5b21c5\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Divyansh Kumar\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Project\New\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Project\New\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Project\New\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Project\New\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.examplerealtime\
          -0\
          apk\
          -0\
          tflite\
          --output-text-symbols\
          D:\Project\New\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\d6d7d29868c2b712196ac4d5fd8e4b2f\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationS
ettings not found.

  C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\d6d7d29868c2b712196ac4d5fd8e4b2f\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\15820ac8876d3772b68f5299fe5b21c5\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Divyansh Kumar\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Project\New\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Project\New\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Project\New\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Project\New\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.examplerealtime\
          -0\
          apk\
          -0\
          tflite\
          --output-text-symbols\
          D:\Project\New\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        26.3s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.5s
         *********************************************************
WARNING: This version of camera will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin camera could not be built due to the issue above.
```

**Comment by VladyslavBondarenko** [comment] 2020-04-01 08:53
Hi @divyanshkumaar 
Could you provide your `flutter doctor -v`?
Are you experiencing this when running new project with camera plugin?
Are you using camera 0.5.7+4 version?
Could you provide your `android/app/build.gradle`?

Related to https://github.com/flutter/flutter/issues/46881

**Comment by divyanshkumaar** [comment] 2020-04-01 14:29
Yes I'm using a camera plugin. 
I downloaded this project from GitHub so I don't know the camera version. Could you tell me how to check it? 
Please find the `flutter doctor -v` below:

D:\Project\New>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at D:\Flutter_SDK\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Divyansh Kumar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.



Below is the `android/app/build.gradle` :

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.examplerealtime"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    aaptOptions {
        noCompress 'tflite'
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by VladyslavBondarenko** [comment] 2020-04-02 10:02
@divyanshkumaar 
could you check with using `camera 0.5.7+4`? 
note that `4.0` is already a year old

**Comment by divyanshkumaar** [comment] 2020-04-02 16:36
I changed `camera: 0.4.0` to `camera: 0.5.7+4` in the `pubspec.yaml` file as you asked.
This is the new `run` code now: 
Still errors.

D:\Project\New>flutter run
Running "flutter pub get" in New...                                 4.7s
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\Project\New\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:189: error: resource android:attr/fontVariationSettings not found.
  D:\Project\New\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:190: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\15820ac8876d3772b68f5299fe5b21c5\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Divyansh Kumar\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Project\New\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Project\New\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Project\New\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Project\New\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.examplerealtime\
          -0\
          apk\
          -0\
          tflite\
          --output-text-symbols\
          D:\Project\New\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\d6d7d29868c2b712196ac4d5fd8e4b2f\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationS
ettings not found.

  C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\d6d7d29868c2b712196ac4d5fd8e4b2f\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\Divyansh Kumar\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\15820ac8876d3772b68f5299fe5b21c5\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Divyansh Kumar\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          D:\Project\New\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          D:\Project\New\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @D:\Project\New\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          D:\Project\New\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.example.examplerealtime\
          -0\
          apk\
          -0\
          tflite\
          --output-text-symbols\
          D:\Project\New\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 6s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       310.3s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                   16.6s


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s


The plugin camera could not be built due to the issue above.

**Comment by iapicca** [comment] 2020-04-03 09:11
Hi @almaystroOo 
does this proposed [solution](https://github.com/flutter/flutter/issues/53829#issuecomment-608073300) fix the issue?
thank you 

possible duplicate of https://github.com/flutter/flutter/issues/46881

**Comment by divyanshkumaar** [comment] 2020-04-03 13:55
Hey @iapicca ! I changed the `compileSdkVersion` to 28 and I think it worked because the Android Emulated turned into an all white screen, but that was it, nothing else happened. The application still didn't run. 
This it the `run` code below:


D:\Project\New>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
Note: D:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.7+4\android\src\main\java\io\flutter\plugins\camera\CameraPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_tts-0.2.6\android\src\main\java\com\tundralabs\fluttertts\FlutterTtsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\razorpay-0.0.2\android\src\main\java\in\appyflow\razorpay\RazorpayPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\tflite-1.0.4\android\src\main\java\sq\flutter\tflite\TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       307.3s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        16.8s
Flutter is taking longer than expected to report its views. Still trying...
E/flutter ( 4831): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 4831): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `W
idgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 4831): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter ( 4831): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter ( 4831): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter ( 4831): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter ( 4831): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter ( 4831): #4      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:335:40)
E/flutter ( 4831): #5      availableCameras (package:camera/camera.dart:81:10)
E/flutter ( 4831): #6      main (package:flutter_realtime_detection/main.dart:10:21)
E/flutter ( 4831): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 4831): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 4831): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4831): #10     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 4831): #11     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 4831): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 4831): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 4831): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 4831):
I/TextToSpeech( 4831): Sucessfully bound to com.google.android.tts
W/examplerealtim( 4831): Verification of android.renderscript.Allocation sq.flutter.tflite.TflitePlugin.renderScriptNV21ToRGBA888(android.content.Context, int, int, byte[]) took 110.020ms
W/examplerealtim( 4831): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/examplerealtim( 4831): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/examplerealtim( 4831): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/examplerealtim( 4831): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
I/OpenGLRenderer( 4831): Initialized EGL, version 1.4
D/OpenGLRenderer( 4831): Swap behavior 1
D/HostConnection( 4831): HostConnection::get() New Host Connection established 0xe5139780, tid 4977
D/HostConnection( 4831): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_K
HR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
W/OpenGLRenderer( 4831): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 4831): Swap behavior 0
D/eglCodecCommon( 4831): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4831): eglCreateContext: 0xe51056c0: maj 2 min 0 rcv 2
D/EGL_emulation( 4831): eglMakeCurrent: 0xe51056c0: ver 2 0 (tinfo 0xcd604e70)
D/HostConnection( 4831): HostConnection::get() New Host Connection established 0xe3824e20, tid 4868
D/HostConnection( 4831): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_K
HR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/eglCodecCommon( 4831): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4831): eglCreateContext: 0xeb4c6460: maj 2 min 0 rcv 2
D/HostConnection( 4831): createUnique: call
D/HostConnection( 4831): HostConnection::get() New Host Connection established 0xe5139c30, tid 4977
D/HostConnection( 4831): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_K
HR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
E/eglCodecCommon( 4831): GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/EGL_emulation( 4831): eglMakeCurrent: 0xeb4c6460: ver 2 0 (tinfo 0xe3815cf0)
I/Choreographer( 4831): Skipped 48 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 4831): eglMakeCurrent: 0xe51056c0: ver 2 0 (tinfo 0xcd604e70)
I/OpenGLRenderer( 4831): Davey! duration=926ms; Flags=1, IntendedVsync=102221993357086, Vsync=102222793357054, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=102222796427960, Animati
onStart=102222796499760, PerformTraversalsStart=102222798548860, DrawStart=102222807999260, SyncQueued=102222809445660, SyncStart=102222810484760, IssueDrawCommandsStart=102222810682760, SwapBuffers=10222282495
7560, FrameCompleted=102222921093360, DequeueBufferDuration=22891000, QueueBufferDuration=1530000,
Syncing files to device AOSP on IA Emulator...
I/TextToSpeech( 4831): Connected to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
I/TextToSpeech( 4831): Set up connection to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
Syncing files to device AOSP on IA Emulator...                  28,136ms (!)

�  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:50477/4DafCkrYHi4=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                             /Error -32601 received from application: Method not found

Reloaded 0 of 495 libraries in 292ms.

Error -32601 received from application: Method not found
Application finished.

**Comment by VladyslavBondarenko** [comment] 2020-04-03 15:04
@divyanshkumaar 
I'm glad that changing `compileSdkVersion` to 28 helped.
Please create a separate issue for the another error if it persists (with providing `flutter doctor -v` and `flutter run -v`).
I'm going to close the current one.
Thank you

**Closed by VladyslavBondarenko** 2020-04-03 15:04 UTC
Labels: platform-android, severe: crash, t: gradle, tool

**Comment by divyanshkumaar** [comment] 2020-04-03 15:21
Okay! Thankyou for your help @VladyslavBondarenko and @iapicca!
