### ISSUE TITLE
GestureDetector Regression in Beta Channel on Samsung Galaxy S7 actual device

### ISSUE THREAD

**Issue by joniaiuser** [flutter/flutter#76064] opened 2021-02-15 13:37 UTC
## Steps to Reproduce
So far I have only been able to replicate it on this particular physical device. It doesn't occur on simulator or my other android device or iOS devices.

0. Use physical device **Samsung Galaxy S7 - SM G930F**
1. flutter run any app with a GestureDetector with onTap

**Expected results:** 
GestureDetector should respond to tap.

**Actual results:** 
GestureDetector is unresponsive 9/10 times on **Beta** channel. Going back to Stable channel fixes it.
This was experienced both in debug and release modes (after releasing via PlayStore).

<details>
  <summary>Logs</summary>

```
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 0
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 1
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 0
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 1
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 0
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 1
D/ViewRootImpl@6107568[MainActivity](31951): ViewPostIme pointer 0
```

```
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.2 20D64 darwin-arm, locale en-SG)
    • Flutter version 1.26.0-17.5.pre at /Users/xx/Development/flutter
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM G930F (mobile) • ce0516056916af3101 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 88.0.4324.150

• No issues found!


```

</details>

**Comment by TahaTesser** [comment] 2021-02-15 15:27
Labelling since this is device-specific, we currently don't have this specific device

**Comment by mayken** [comment] 2021-02-26 11:47
A similar problem with the galaxy s8, galaxy fold is probably on all samsung galaxy models.

**Comment by TahaTesser** [comment] 2021-03-01 11:56
Hi @mayken 
I just got a Samsung device, can you please provide a minimal code sample?
Thanks

**Comment by mayken** [comment] 2021-03-01 14:32
Hi @TahaTesser 


<details>
  <summary>Use this code</summary>
```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
    GestureBinding.instance.resamplingEnabled = true;    
    runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: GestureDetector(
          onTap: () {
            print('test - ${_count}');
            setState(() {
              _count++;
            });
          },
          child: FlutterLogo(
            size: 300,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

**Comment by kuhnroyal** [comment] 2021-03-22 11:38
Probably a duplicate of #73286

**Closed** 2021-07-09 22:24 UTC
Labels: e: device-specific, f: gestures, framework, passed first triage, platform-android, severe: regression
