### ISSUE TITLE
Flutter crashes on clicking anything after opening a tray menu

### ISSUE THREAD

**Issue by aayushagrawal9** [flutter/flutter#113368] opened 2022-10-13 09:53 UTC
## Steps to Reproduce

1. Install the plugin https://github.com/leanflutter/tray_manager
2. Create a basic context menu based on the example in the above GitHub repo
3. Click the tray icon and select any option (Or even clicking outside the context menu will cause the crash)

**Expected results:** No crash

**Actual results:** Flutter crashes with the below text in verbose mode

<details>
  <summary>Logs</summary>

`[  +24 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device
(file:///var/folders/fy/jgms32fs6_g2mxfr_6ljhvvh0000gp/T/desktop-appJDlREo/deskt
op-app/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after
0:00:00.250000: Future not completed
[   +6 ms] "flutter run" took 21,572ms.
[ +257 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0`
</details>
```
```

Only info warnings in `flutter analyze`

```
```
 ~/De/Q/desktop-app | three-tasks ! ?  flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    en-IN)
    • Flutter version 3.3.4 on channel stable at /Users/Aayush/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (8 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
```

</details>

The same bug also occurs when using this plugin instead: https://pub.dev/packages/system_tray

**Comment by huycozy** [comment] 2022-10-13 12:27
Hi @aayushagrawal9 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repositories.
Closing, as this isn't an issue with Flutter itself.  

If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-10-13 12:27 UTC
Labels: in triage
