### ISSUE TITLE
MessageLoop.CanCreateConcurrentMessageLoop runs forever

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34070] opened 2019-06-07 20:56 UTC
It seems that there might be some deadlock in MessageLoop.CanCreateConcurrentMessageLoop which runs 45 minutes in https://cirrus-ci.com/task/6032548447125504 until cancelled.

This at least means a flaky test. In the worst case, this might signal that our MessageLoop can sometimes hang on a user device. That's probably worse than a crash. Hence I'm giving it a `severe: crash` label even without crashing because I can't find a `severe: hang` label.

CC @chinmaygarde

**Comment by gaaclarke** [comment] 2019-06-10 18:05
link to test: https://github.com/flutter/engine/blob/44b1cedff6ead71a5f7a3abe87132c893cb7e7cc/fml/message_loop_unittests.cc#L284

I played around with surfacing a WaitWithTimeout method on the CountDownLatch.  I got that working but the problem is that fml::Thread will join in its deconstructor so detecting a timeout isn't enough to avoid a hang in the unit tests (since the app will just hang in ~Thread).  It appears that googletest doesn't have the option to set global timeout value per test.  Is there a way we can tweak the timeout for the whole suite in cirrus?  45 minutes is a bit too generous.

**Comment by gaaclarke** [comment] 2019-06-11 21:25
> for i in {1..1000}; do ./host_debug_unopt/fml_unittests --gtest_filter="*CanCreateConcurrentMessageLoop*"; done;

You can use this script to try to reproduce it.  I ran it thousands of times and I couldn't reproduce it.

**Comment by chinmaygarde** [comment] 2019-06-11 22:04
Or, `./host_debug_unopt/fml_unittests --gtest_filter="*CanCreateConcurrentMessageLoop*" --gtest_repeat=-1`

**Comment by chinmaygarde** [comment] 2019-07-09 23:09
Fixed in https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc

**Closed by chinmaygarde** 2019-07-09 23:09 UTC
Labels: engine, severe: crash, team: flakes
