### ISSUE TITLE
These "samples" are really, really bad

### ISSUE THREAD

**Issue by nick1246789** [flutter/flutter#47443] opened 2019-12-19 10:50 UTC
I had the misfortune of clicking "Material Theming in Flutter" while browsing the material.io homepage, which took me to "flutter.github.io/samples". I am opening this issue here because that is what the "Send Feedback" link in the footer tells me to do.

When I first landed on the page, I assumed I was looking at some sort of stretched 720p video, due to the subtle judder, low frame rate, and pixelated appearance of text and edges. I quickly realized this was actually meant to be an interactive user interface, so I gave it a try. 

Upon mousing over various elements and scrolling down the page, I had the distinct impression I was interacting with a Flash application from 2002, or perhaps a low-bandwidth remote desktop connection to an android tablet instance somewhere in the cloud. The UI stuttered and had perceptible latency on my high end workstation, with a current gen desktop video card, running the latest version of Chrome. 

The ugly blur on text and edges surely results from subpixel element sizing. I looked briefly in chrome dev tools, and I see there's some sort of canvas api abuse going on with a ton of nested elements. That was enough for me.

**Comment by alishashaw439** [comment] 2019-12-19 16:35
@nick1246789 Can you give me the specific link of at least one sample which needs to be get fixed? What is the sample and what exact result you are expecting from this particular sample?

**Comment by jmagman** [comment] 2019-12-19 21:32
What OS and browser are you using?  https://flutter.github.io/samples looks really nice on my machine...

**Comment by nick1246789** [comment] 2019-12-20 15:16
**Test device:**
- Desktop workstation
- Windows 10 (latest)
- Chrome (latest)
- 1920x1080
- Nvidia Pascal card 8GB
- 9th gen Intel desktop processor

**Samples in question:**
- I have mainly only looked at the main flutter gallery page that leads to the various samples

### Some thoughts/observations:

**"Blurry" appearance of text and hard edges**
- Probably mainly related to subpixel element sizing and positioning, and subsequent pixel rounding (stuff like `translate3d(1.5px, 25px, 0px)` and `width: 283.5px; height: 216px; transform: translate(940.5px, 0px)`)
- using "transform" to position everything probably doesn't help, especially if those positions are all derived from subpixel container sizes
- high dpi displays probably hide this issue to a degree, but nevertheless there will be pixel rounding happening when you have elements that are sized or positioned with values like `100.36287px` 

**overall pixelated appearance**
- rendering all the icons with bitmaps (as blobs) instead of svgs definitely doesn't help... they're pretty low res to begin with, and the pixelation gets worse with the above mentioned pixel rounding issues
- it looks like some of the elements have rounded corners that are created using bitmaps instead of css border radius, clip path, svg, or some other more modern means.... this makes it look super old school to me

**laggy/janky element/image repaint on scrolling and resizing**
- Probably the massively nested element trees and above mentioned positioning and sizing techniques don't help
- i am seeing images and icons "flash" blank continually when scrolling or resizing the browser window.
- if i resize the window and watch a single element, like the "starter app" card, I notice the values for "translate" and "width" change rapidly and the image flashes in and out of visibility as this happens. 

**bitmap blob rendering**
- it looks like those bitmap blobs are being generated client side on-demand... I've seen some examples recently of this kind of approach, and the result is usually really bad. 
- the concept is something like, "let's redraw the image off-screen then insert it once it has been resized" ... sounds clever, but usually looks like crap vs the regular browser/OS scaling,
- inevitably you end up using low quality algorithms/libs to accommodate the lowest common denominator. Much better to pre-render on the server... This is like a poor man's server side image rendering, but with none of the advantages
- swapping assets in and out has to be done properly, clearly not the case here because the images disappear and then reappear
- should not remove elements before new ones have been inserted 
- bitmaps should only be used for actual photos anyway, not graphics

**requestanimationframe**

- everything seems to be tied to requestanimationframe, I guess in an effort to have react-like fixed update intervals, or something
- this is another one of those trendy/clever concepts, but there aren't that many good implementations
- from my limited anecdotal observations of various requestanimationframe implementations -- i.e. as a way of regulating the "main thread" operations -- the results can be like a bad stop-motion film.
- note: i am running a high refresh rate monitor, which likely makes the above worse. This will also affect devices like ipad pro and increasing number of higher refresh rate devices

**Comment by nick1246789** [comment] 2019-12-20 15:53
From my chrome console, on a 4.5GHz desktop computer:

> [Violation] 'requestAnimationFrame' handler took 108ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 55ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 111ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 88ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 75ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 73ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 65ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 85ms
js_helper.dart:2049 [Violation] 'requestAnimationFrame' handler took 72ms

**Comment by nturgut** [comment] 2019-12-20 19:22
Thanks a lot for filing the issue and all the notes you shared.

**Comment by tbodt** [comment] 2019-12-21 03:27
The first thing you mentioned is #32274. Using translate instead of translate3d helps with that a ton, because translate3d rasterizes the text before translating it and rasterizes it again after translating, and that never looks good. translate3d was added to fix a bug, though: flutter/engine#13860

Also, text is drawn to the canvas in some cases, instead of being directly added to the DOM. This generally makes it look worse for the same reason translate3d makes it look worse. Changing [_drawOnCanvas](https://github.com/flutter/engine/blob/5a730c60d3cee8deb6901d9e14ae9971ec54b720/lib/web_ui/lib/src/engine/text/paragraph.dart#L289) to always return true made a big difference here. I haven't looked into why canvas rendering would be considered desirable.

**Comment by yjbanov** [comment] 2019-12-21 04:19
This is a duplicate of https://github.com/flutter/flutter/issues/32274. The problem is that the bitmap canvas is misaligned w.r.t. the physical pixel grid, resulting in double anti-aliasing. This is problematic for screens with device pixel ratio of 1.0.

**Comment by tbodt** [comment] 2019-12-21 04:20
I don't think this should be closed, a number of points have been brought up that are unrelated to double antialiasing

**Comment by jmagman** [comment] 2019-12-23 18:21
Reopening, it sounds like this needs to be broken up into several issues.

**Comment by yjbanov** [comment] 2020-01-03 22:26
@nick1246789 Thank you for the detailed write-up. We have many of these issues captured as individual Github issues. Please, feel free to file those that have not been filed yet. I'm going to close this issue because we cannot address everything listed here in a single go.

**Closed by yjbanov** 2020-01-03 22:26 UTC
Labels: d: examples, ☸ platform-web
