### ISSUE TITLE
showDatePicker() - impossible to enter date typing manually in case of non-English locale.

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#58439] opened 2020-06-01 21:10 UTC
When start editing input format is automatically switching to English mm/dd/yyyy

```dart
DateTimeField(
    format: DateFormat.yMd(),
``` 

![image](https://user-images.githubusercontent.com/4129763/83454250-c7fe8680-a410-11ea-83d6-09244d46059d.png)

![image](https://user-images.githubusercontent.com/4129763/83454335-dfd60a80-a410-11ea-9d53-d4c02a2649cb.png)

```
flutter doctor -v
[√] Flutter (Channel dev, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.16299.1087], locale en-US)
    • Flutter version 1.19.0-2.0.pre at c:\Programs\flutter
    • Framework revision 1d395c5e18 (30 hours ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-06-02 11:22
Hi @slavap 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/jifalops/datetime_picker_formfield/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Comment by slavap** [comment] 2020-06-03 01:54
@TahaTesser 
You are wrong, this problem is related to Flutter's standard InputDatePickerFormField.
This third party widget is just calling standard date picker dialog.
The problem is somewhere in localization, because InputDatePickerFormField has:
```dart
@override
  Widget build(BuildContext context) {
    final MaterialLocalizations localizations = MaterialLocalizations.of(context);
    final InputDecorationTheme inputTheme = Theme.of(context).inputDecorationTheme;
    return TextFormField(
      decoration: InputDecoration(
        border: inputTheme.border ?? const UnderlineInputBorder(),
        filled: inputTheme.filled ?? true,
        hintText: widget.fieldHintText ?? localizations.dateHelpText,
        labelText: widget.fieldLabelText ?? localizations.dateInputLabel,
      ),
      validator: _validateDate,
      inputFormatters: <TextInputFormatter>[
        DateTextInputFormatter(localizations.dateSeparator),
      ],
```
but inputFormatters are wrongly initialized, despite I'm having 
localizationsDelegates: GlobalMaterialLocalizations.delegates,
in my MaterialApp.

**Comment by TahaTesser** [comment] 2020-06-03 08:46
Hi @slavap 
Your initial post is using third party package and it's widget

Can you please provide your `flutter run --verbose` and a minimal **complete** reproducible code sample,  your code snippet isn't complete to reproduce the issue
Thank you

**Comment by slavap** [comment] 2020-06-03 22:58
@TahaTesser It is completely reproducible, see below and attached project. This bug is making standard showDatePicker() completely useless in my project. 
Also please add **ability to define custom inputFormatters when running showDatePicker()**

![image](https://user-images.githubusercontent.com/4129763/83696732-0d0dee80-a5b2-11ea-9058-73a19ba9439b.png)

![image](https://user-images.githubusercontent.com/4129763/83696742-15fec000-a5b2-11ea-8f67-d8e224521d9e.png)

![image](https://user-images.githubusercontent.com/4129763/83696759-2020be80-a5b2-11ea-8d87-28f0d5ca47ca.png)

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
      supportedLocales: [Locale('ru', 'RU')],
      locale: Locale('ru', 'RU'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  DateTime _date = DateTime.now();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have selected:'),
            Text(
              DateFormat.yMd().format(_date),
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showDatePick(context),
        tooltip: 'Select Date',
        child: Icon(Icons.add),
      ),
    );
  }

  void _showDatePick(BuildContext context) async {
    var d = await showDatePicker(
      context: context,
      firstDate: DateTime(2020, 1, 1),
      lastDate: DateTime(2025, 12, 31),
      initialDate: _date,
    );
    if (d != null) {
      setState(() {
        _date = d;
      });
    }
  }
}
```
```
flutter doctor -v
[√] Flutter (Channel dev, 1.19.0-3.0.pre, on Microsoft Windows [Version 10.0.16299.1087], locale en-US)
    • Flutter version 1.19.0-3.0.pre at c:\Programs\flutter
    • Framework revision 6135091de9 (2 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.
```
```
flutter run -d chrome --verbose
[   +9 ms] executing: [c:\Programs\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 6135091de9f8f6befc2ec7f8835d28d43a21cd05
[   +1 ms] executing: [c:\Programs\flutter/] git tag --contains HEAD
[ +216 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.19.0-3.0.pre
[   +8 ms] executing: [c:\Programs\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[   +1 ms] executing: [c:\Programs\flutter/] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +81 ms] executing: [c:\Programs\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[  +56 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: C:\Users\slavap\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +32 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +10 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +173 ms] Generating
d:\Temp\flutter\datepick\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +78 ms] Launching lib\main.dart on Chrome in debug mode...
[  +59 ms] Updating assets
[  +75 ms] Syncing files to device Chrome...
[  +37 ms] Generating
d:\Temp\flutter\datepick\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +145 ms] <- reset
[   +6 ms] c:\Programs\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --old_gen_heap_size=2000
c:\Programs\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
c:\Programs\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\slavap\AppData\Local\Temp\flutter_tools.741ba3d0\flutter_tool.80b7e02b\app.dill --libraries-spec
file:///c:/Programs/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\slavap\AppData\Local\Temp\flutter_tools.741ba3d0\flutter_tools.53db0b0f --filesystem-scheme org-dartlang-app
--initialize-from-dill build\cache.dill.track.dill --platform
file:///c:/Programs/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+15889 ms] Syncing files to device Chrome... (completed in 16,076ms, longer than expected)
[   +2 ms] Synced 25.2MB.
[        ] <- accept
[ +111 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56020/devtools/browser/02f3c8ce-4db5-4a4f-87fd-e966c8a70cdb
[+7007 ms] Debug service listening on ws://127.0.0.1:56067/0d2vqcDMfmg=

[ +551 ms] Debug service listening on ws://127.0.0.1:56067/0d2vqcDMfmg=
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+19776 ms] Stopped debug service on ws://127.0.0.1:56067

[  +67 ms] Application finished.
[   +3 ms] "flutter run" took 44,111ms.
[  +76 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[ +152 ms] Shutdown hooks complete
```
[datepick.zip](https://github.com/flutter/flutter/files/4726597/datepick.zip)

**Comment by slavap** [comment] 2020-06-04 10:41
@TahaTesser please reopen this issue. Or should I open a new one?

**Comment by TahaTesser** [comment] 2020-06-04 13:24
Issue is reproducible 
Thanks for code sample
Closing as duplicate https://github.com/flutter/flutter/issues/55535

**Closed by TahaTesser** 2020-06-04 13:24 UTC
