### ISSUE TITLE
Framework post submit tests not running but tree is open

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#79380] opened 2021-03-30 15:16 UTC
We need to either start the tests running, or somehow close the tree.

https://media.discordapp.net/attachments/608021351567065092/826437333028831242/AJjRPfS5tpbXQgc.png

**Comment by zanderso** [comment] 2021-03-30 15:18
Since CI is not running at all, we can't close the tree by landing a failing PR. Is it possible to close the master branch? @kf6gpe @godofredoc @Hixie

**Comment by keyonghan** [comment] 2021-03-30 16:20
Yeah, API `/api/refresh-chromebot-status` has been failing continously. Keep digging.

@zanderso Tree is still closable by failing a task on purpose. The tree status is pushed to Github via another API `/api/push-build-status-to-github`.

**Comment by keyonghan** [comment] 2021-03-30 16:28
Oh, sorry that's not the case. `/api/push-build-status-to-github` is based on existing tasks status in datastore. So it is not reflecting the real status (those new empty ones are not updated in datastore yet, though are up-to-date in luci).

**Comment by keyonghan** [comment] 2021-03-30 16:30
Manually updated task `linux_docs_test` to be failed in datastore to close the tree on purpose.

**Comment by godofredoc** [comment] 2021-03-30 16:42
Let's revert to a previous version of the dashboard. 

```

NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Null.iterator (dart:core/null.dart:1:1)
#2      ExpandIterator.moveNext (dart:_internal/iterable.dart:479:51)
#3      List.addAll (dart:core-patch/growable_array.dart:314:17)
#4      LuciService.getBuildsForBuilderList.<anonymous closure> (package:cocoon_service/src/service/luci.dart:127:18)
<asynchronous suspension>
#5      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#6      LuciService.getBuildsForBuilderList (package:cocoon_service/src/service/luci.dart:124:7)
<asynchronous suspension>
#7      LuciService.getBranchRecentTasks (package:cocoon_service/src/service/luci.dart:73:32)
<asynchronous suspension>
#8      RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:56:75)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#10     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:7)
<asynchronous suspension>
#11     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:5)
<asynchronous suspension>
#12     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:125:9)
<asynchronous suspension>
```

**Comment by keyonghan** [comment] 2021-03-30 16:46
It is not related to the previous version. (hit error on the previous version as well).
I am still debugging to find the root cause.

**Comment by keyonghan** [comment] 2021-03-30 17:24
It is confirmed `Mac_ios animation_with_microtasks_perf_ios__timeline_summary` returns null response.
Working on a fix.

**Comment by CaseyHillers** [comment] 2021-03-30 17:54
Should we temporarily remove Mac_ios animation_with_microtasks_
perf_ios__timeline_summary  from the prod_builders.json to unblock the tree?

**Comment by keyonghan** [comment] 2021-03-30 18:33
A new version is pushed and status is being populated. Closing.

**Closed by keyonghan** 2021-03-30 18:33 UTC
Labels: P0, team: infra

**Comment by godofredoc** [comment] 2021-03-30 18:41
@keyonghan do we have a bug to track the real issue or should we keep this bug open?

**Comment by keyonghan** [comment] 2021-03-30 18:48
The real issue was referenced above: https://github.com/flutter/flutter/issues/79393.

To summarize: post submit tasks did get scheduled and run, but the status refresh API has been failing due to an empty response from a builderbucket API call (caused by a builder which is not configured in https://devops-console-oss.corp.google.com/flutter/infra/+/master:config/framework_config.star, but got enabled in https://github.com/flutter/flutter/commit/e6920662adf73d7935245461621ec338797f053b). The API was trying to query records of this builder which doesn't have any.

The fix is to exclude empty builders in the response. If any similar issues happen in the future, this can be caught from the dashboard, since they never get scheduled to run. Like this one:
![Screen Shot 2021-03-30 at 11 48 07 AM](https://user-images.githubusercontent.com/54558023/113040626-df4ff280-914d-11eb-8127-8e50acb4665d.png)

**Comment by godofredoc** [comment] 2021-03-30 19:34
I'd recommend to add the presubmit check independently of the work to consolidate the config files. The consolidation of config files may take some time.

**Comment by keyonghan** [comment] 2021-03-30 20:03
Created https://github.com/flutter/flutter/issues/79399 to track that.
