### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by BhadrakshB** [flutter/flutter#151634] opened 2024-07-12 06:45 UTC
## Command
```
flutter run -d chrome --web-renderer html
```

## Steps to Reproduce
1. I am running this project on flutter web. It's a very simple project for my org that uses firebase.

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart

**Comment by danagbemava-nc** [comment] 2024-07-12 07:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-07-12 07:59 UTC
Labels: in triage
