### ISSUE TITLE
url_launcher does not launch external https URLs when a web app as PWA is installed on the homescreen of an iOS or iPadOS device

### ISSUE THREAD

**Issue by mbalmer** [flutter/flutter#117652] opened 2022-12-26 12:51 UTC
## Steps to Reproduce

1. Create web app that uses url_launcher
2. Launch it in safari on mobile
3. Install it on the homescreen
4. Try to launch a a URL
5. Nothing happens

**Comment by huycozy** [comment] 2022-12-27 07:48
@mbalmer I can not reproduce the issue with [url_launcher example](https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher/example). The url is opened normally from PWA. 

Verifying on `iPhone 7, iOS 15.7.2` and `url_launcher: ^6.1.7`.

<details>
<summary>Demo video</summary>


https://user-images.githubusercontent.com/104349824/209630953-825dd66e-6438-42aa-bf5f-ac03fdd9da93.MP4


</details>

Which `url_launcher` version are you using? And please provide the device information (OS, model) so that we may verify the issue. Thanks!

**Comment by mbalmer** [comment] 2022-12-27 08:47
> @mbalmer <https://github.com/mbalmer> I can not reproduce the issue with url_launcher example <https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher/example>. The url is opened normally from PWA.
> Verifying on iPhone 7, iOS 15.7.2 and url_launcher: ^6.1.7.
> 
> Demo video
>  <https://user-images.githubusercontent.com/104349824/209630953-825dd66e-6438-42aa-bf5f-ac03fdd9da93.MP4>
> Which url_launcher version are you using? And please provide the device information (OS, model) so that we may verify the issue. Thanks!
> 
The devices are an iPhone 11 Pro Max and an iPad Mini 6th generation (2021) both running the latest iOS/iPadOS version 16.2

url_launcher is at version 6.1.7

**Comment by huycozy** [comment] 2022-12-27 09:48
@mbalmer Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, you may try using [url_launcher example](https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher/example) to confirm if the issue still persists from your end as well.

**Comment by mbalmer** [comment] 2022-12-27 10:59
> 
> @mbalmer <https://github.com/mbalmer> Please provide a completed and minimal reproducible code sample <https://stackoverflow.com/help/minimal-reproducible-example> so that we may verify this. Also, you may try using url_launcher example <https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher/example> to confirm if the issue still persists from your end as well.
> 

FWIW: The code I use is actually from the example code, and it works on iOS native; macOS, Android, in desktop safari, just not in the mobile safari or as PWA on iOS/iPad.

canLaunchUrl() returns true, but the subsequent call to launchUrl() does nothing.

This is the function I use:

_launchURL(url) async {
    if (await canLaunchUrl(Uri.parse(url))) {
      print('launch url ' + url);
      await launchUrl(Uri.parse(url));
    } else {
      Flushbar(
        title: AppLocalizations.of(context).failed,
        message: url,
        duration: Duration(seconds: 10),
      ).show(context);
      throw 'Could not launch $url';
    }
  }

and this is how it is called:

child: ListTile(
                              title: Text(w.name,
                                  style: TextStyle(fontSize: 18.0)),
                              onTap: () {
                                Navigator.of(context).push(
                                    new MaterialPageRoute(
                                        builder: (context) => new DashBoard(
                                            w.id, w.name, w.role)));
                              },
                              onLongPress: w.url.length > 0
                                  ? () => {_launchURL(w.url)}
                                  : null,
                              trailing:
                                  w.url.length > 0 ? Icon(Icons.link) : null));

I wonder if manifest.json needs an entry so that URLs can be launched?

**Comment by huycozy** [comment] 2022-12-28 04:24
@mbalmer I don't have any device running with `16.2`, I tried with `16.1` but it also works well from my end. May be the issue only happens on a specific OS. 

Can you retry with this deployed site with url_launcher sample code (https://reproduceissues.web.app/) on your device?

**Comment by mbalmer** [comment] 2022-12-28 09:39
> @mbalmer <https://github.com/mbalmer> I don't have any device running with 16.2, I tried with 16.1 but it also works well from my end. May be the issue only happens on a specific OS.
> Can you retry with this deployed site with url_launcher sample code (https://reproduceissues.web.app/) on your device?
> 
I open that URL in Safari on my iPadMini 6, running iPadOS 16.2,  Then I click the button „Launch in browser“ and it opens a new tab with the cylog.org <http://cylog.org/> pages, as expected.

The only difference to my code seems to be that you likely call launchURL in the onTap() method whereas I use onLongPress(), but that is unlikely to be the reason…

Your sample also works correctly when I install the page as PWA in the home screen.

I am really puzzled now, it is obvious that it is not a bug in url_launcher but has something to do with how I use it.  I will continue to investigate this, and once I find out, I will write a note about it, in case someone else runs into the same issue…

**Comment by mbalmer** [comment] 2022-12-28 10:01
> 
>> @mbalmer <https://github.com/mbalmer> I don't have any device running with 16.2, I tried with 16.1 but it also works well from my end. May be the issue only happens on a specific OS.
>> Can you retry with this deployed site with url_launcher sample code (https://reproduceissues.web.app/) on your device?
>> 
> I open that URL in Safari on my iPadMini 6, running iPadOS 16.2,  Then I click the button „Launch in browser“ and it opens a new tab with the cylog.org <http://cylog.org/> pages, as expected.
> 
> The only difference to my code seems to be that you likely call launchURL in the onTap() method whereas I use onLongPress(), but that is unlikely to be the reason…

to my suprise, this actually makes a difference….  When I call launchURL() from the onTap() method of a ListTile, it opens the URL.  When, however, I call it from the onLongPress() method, nothing happens.

**Comment by mbalmer** [comment] 2022-12-28 10:25
> Am 28.12.2022 um 11:01 schrieb Marc Balmer ***@***.***>:
> 
> 
>> 
>>> @mbalmer <https://github.com/mbalmer> I don't have any device running with 16.2, I tried with 16.1 but it also works well from my end. May be the issue only happens on a specific OS.
>>> Can you retry with this deployed site with url_launcher sample code (https://reproduceissues.web.app/) on your device?
>>> 
>> I open that URL in Safari on my iPadMini 6, running iPadOS 16.2,  Then I click the button „Launch in browser“ and it opens a new tab with the cylog.org <http://cylog.org/> pages, as expected.
>> 
>> The only difference to my code seems to be that you likely call launchURL in the onTap() method whereas I use onLongPress(), but that is unlikely to be the reason…
> 
> to my suprise, this actually makes a difference….  When I call launchURL() from the onTap() method of a ListTile, it opens the URL.  When, however, I call it from the onLongPress() method, nothing happens.
> 

More information:  onLongPress() actually calls the callback function, which runs canLaunchUrl() (returns true), then calls launchUrl(), which does nothing, but also returns true.

**Comment by huycozy** [comment] 2022-12-29 03:37
@mbalmer I'm not sure this will be a normal behavior to open a url by long pressing on a view (ListTile/Button..). But it seems to be happening on normal web too (not necessarily PWA). Please retry and confirm this. 

If you also see the same behavior, please file a new issue for this case (which is different than the original issue here) and add all information you found along with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we have a clear context to verify that issue. Thanks!

**Comment by mbalmer** [comment] 2022-12-29 09:22
> @mbalmer <https://github.com/mbalmer> I'm not sure this will be a normal behavior to open a url by long pressing on a view (ListTile/Button..). But it seems to be happening on normal web too (not necessarily PWA). Please retry and confirm this.

(The use case is to show the name of a club in a ListTile, a short tap (onTap()) takes you to a detail page within the app, a long press will launch the URL of the club, thus taking you to clubs website.)

And yes, I can confirm that neither works in Safari, nor as PWA, on Apples mobile browser (tested on iOS 16.2 and iPadOS 16.2).  The function that is defined for onLongPress() (e.g. launchMyURL) is actually called, but launchURL() is a no-op when coming from onLongPress(). launchURL() returns true nevertheless.

> If you also see the same behavior, please file a new issue for this case (which is different than the original issue here) and add all information you found along with a completed and minimal reproducible code sample <https://stackoverflow.com/help/minimal-reproducible-example> so that we have a clear context to verify that issue. Thanks!
> 
I try to bake a small and complete example and put it online.

**Comment by mbalmer** [comment] 2022-12-29 10:04
> If you also see the same behavior, please file a new issue for this case (which is different than the original issue here) and add all information you found along with a completed and minimal reproducible code sample so that we have a clear context to verify that issue. Thanks!

I opened new bug #117775 for this issue, with code example.  The code example can be viewed online at https://scoremaker.ch/launcher_issue.

**Comment by huycozy** [comment] 2022-12-30 05:20
@mbalmer thanks for confirming and filing a new issue for this. As the original issue has been redirected to a new one, I will close this issue as it's no longer valid.

**Closed by huycozy** 2022-12-30 05:20 UTC
Labels: in triage
