### ISSUE TITLE
[webview_flutter] should use TextDirection.ltr for webview_android

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#66208] opened 2020-09-20 07:52 UTC
https://github.com/flutter/plugins/blob/webview_flutter-v0.3.22+1/packages/webview_flutter/lib/src/webview_android.dart#L53

```dart
AndroidView(
  // WebView content is not affected by the Android view's layout direction,
  // we explicitly set it here so that the widget doesn't require an ambient
  // directionality.
  layoutDirection: TextDirection.rtl,
)
```

## Steps to Reproduce

**Expected results:**

**Actual results:**

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by PixelToast** [comment] 2020-09-20 09:22
As the comment seems to suggest, the layoutDirection has no effect and is only specified to make `Directionality.of(context)` happy. Is there any unintended behavior that you are observing as a result of this being set to rtl?

**Comment by Sunbreak** [comment] 2020-09-20 09:35
> As the comment seems to suggest, the layoutDirection has no effect and is only specified to make `Directionality.of(context)` happy. Is there any unintended behavior that you are observing as a result of this being set to rtl?

I'm porting android implementaion of webview_flutter to `Hybrid Composition`

https://github.com/flutter/flutter/wiki/Hybrid-Composition suggests to use `TextDirection.ltr`

It is reasonable to keep them identical, isn't it?

**Comment by pedromassangocode** [comment] 2020-09-21 08:22
IMHO since this does not affect anything this can be left as it is. And probably that is why someone left a comment there.

**Comment by red282** [comment] 2020-11-23 15:16
I have an issue that the position of webview scrollbar is wrong in android. (same as https://github.com/flutter/flutter/issues/47339) 
I don't know why this happens, but when replacing its direction with `ltr`, the bug is gone.

To test it, in my custom webview screen code, I copied & pasted the whole implementation code of `AndroidWebView` (with text direction fix), and added the line `WebView.platform = AndroidWebView();`.

**Comment by amirh** [comment] 2020-12-03 19:35
Per @red282 it seems like the Android view's layoutDirection does have some effect on the webview's rendering (I'm guessing probably on specific platforms #47339 wasn't reproducible by others).

I think the right thing to do would be to use ambient directionality and allow explicit specification of directionality, to not make this a breaking change I'd go with defaulting to ltr if no directionality is specified explicitly nor through a ancestor directionality widget.

If you're willing to contribute a PR to add that feature I'm happy to review it.

**Comment by pedromassangocode** [comment] 2021-01-08 14:54
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Sunbreak** [comment] 2021-01-27 09:16
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

![image](https://user-images.githubusercontent.com/7928961/105969318-16107a80-60c3-11eb-83b5-bc55c6ff1580.png)

Reproduced on MI 10 (Android 11）with one of our APPs in local test. We'd like to investigate the root cause if you could open the issue up @pedromassangocode

**Comment by pedromassangocode** [comment] 2021-01-27 10:24
> Reproduced on MI 10 (Android 11）with one of our APPs in local test. We'd like to investigate the root cause if you could open the issue up @pedromassangocode

Hi @Sunbreak 
Can you please elaborate what issue you where able to reproduce?

**Comment by Sunbreak** [comment] 2021-01-27 13:03
Scrollbar is on the left

**Comment by pedromassangocode** [comment] 2021-01-28 09:55
Hi @Sunbreak 
I think this is more related to https://github.com/flutter/flutter/issues/47339. Reopening this since the issue seems to be caused by `TextDirection` on `webview` plugin, see https://github.com/flutter/flutter/issues/66208#issuecomment-738247198.

**Comment by stuartmorgan** [comment] 2021-05-13 18:06
It looks like this should be fixed by https://github.com/flutter/plugins/pull/3765; please let me know if that's not the case.

**Closed by stuartmorgan** 2021-05-13 18:06 UTC
Labels: p: first party, p: webview, passed first triage, plugin, proposal
