### ISSUE TITLE
Horizontal Stepper  Causes pixel overflow Issue

### ISSUE THREAD

**Issue by kururu-abdo** [flutter/flutter#114742] opened 2022-11-05 07:41 UTC
I  tried  to use Stepper widget with many steps
but i faced an issue which is pixel in the right side
so i edit some line of code in Stepper class 

i remove Expanded Widget in line 798  in 
_buidHorizontal()  function

in the function's returned widget i use ListView instead of Row widget

`  return Column(
      children: <Widget>[
        Material(
          elevation: widget.elevation ?? 2,
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 24.0),
            height: _isLabel() ? 104.0 : 72.0,
            width: double.maxFinite,
            child: ListView(
              scrollDirection: Axis.horizontal,
              children: children,
            ),
          ),
        ),
        Expanded(
          child: ListView(
            physics: widget.physics,
            padding: const EdgeInsets.all(24.0),
            children: <Widget>[
              AnimatedSize(
                curve: Curves.fastOutSlowIn,
                duration: kThemeAnimationDuration,
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: stepPanels),
              ),
              _buildVerticalControls(widget.currentStep),
            ],
          ),
        ),
      ],
    );`

**Comment by danagbemava-nc** [comment] 2022-11-07 07:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/40601. 

Kindly follow up in the issue linked above for updates. Please upvote the issue as well. 

Thank you

**Closed by danagbemava-nc** 2022-11-07 07:41 UTC
Labels: in triage
