### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by opadasaeed** [flutter/flutter#160844] opened 2024-12-25 13:33 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008130-000E1C391AA0001C --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. run on my real device ( iphone 15 pro )

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 15.1.1 24B91 darwin-arm64, locale en-EG)
    • Flutter version 3.24.2 on channel stable at /Users/opada/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (4 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/opada/Library/Android/sdk
    • Platform android-35, build-tools 33.0.2
    • ANDROID_HOME = /Users/opada/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/opada/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (4 available)
    • opada’s iPhone (mobile)         • 00008130-000E1C391AA0001C • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
### Plugins
app_links-6.3.3
app_links_linux-1.0.3
app_links_web-1.0.4
audio_session-0.1.23
connectivity_plus-6.1.1
device_info_plus-11.2.0
facebook_auth_desktop-2.1.1
file_selector_linux-0.9.3+2
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_analytics-11.3.6
firebase_analytics_web-0.5.10+5
firebase_auth-5.3.4
firebase_auth_web-5.13.5
firebase_core-3.9.0
firebase_core_web-2.19.0
firebase_dynamic_links-6.0.11
firebase_messaging-15.1.6
firebase_messaging_web-3.9.5
firebase_remote_config-5.2.0
firebase_remote_config_web-1.7.5
flutter_contacts-1.1.9+2
flutter_facebook_auth-7.1.1
flutter_facebook_auth_web-6.1.2
flutter_fgbg-0.6.0
flutter_image_compress-2.3.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.3
flutter_image_compress_web-0.1.4+1
flutter_inappwebview-6.1.5
flutter_inappwebview_android-1.1.3
flutter_inappwebview_ios-1.1.2
flutter_inappwebview_macos-1.1.2
flutter_inappwebview_web-1.1.2
flutter_inappwebview_windows-0.6.0
flutter_local_notifications-18.0.1
flutter_local_notifications_linux-5.0.0
flutter_localization-0.3.0
flutter_plugin_android_lifecycle-2.0.24
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
flutter_sim_country_code-0.1.2
flutter_wallet_card-3.0.4
google_mlkit_commons-0.9.0
google_mlkit_text_recognition-0.14.0
google_sign_in-6.2.2
google_sign_in_android-6.1.34
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3
gtk-2.1.0
home_widget-0.7.0
image_cropper-8.1.0
image_cropper_for_web-6.0.2
image_picker-1.1.2
image_picker_android-0.8.12+19
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.6+12
in_app_purchase_storekit-0.3.20+2
just_audio-0.9.42
just_audio_web-0.4.13
mobile_device_identifier-0.0.2
nfc_manager-3.5.0
open_settings-2.0.2
package_info_plus-8.1.2
path_provider-2.1.5
path_provider_android-2.2.15
path_provider_foundation-2.4.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+5
permission_handler_windows-0.2.1
purchases_flutter-8.3.2
qr_code_scanner-1.0.1
rate_my_app-2.2.0
root-2.0.4
sentry_flutter-8.12.0
share_plus-10.1.3
shared_preferences-2.3.4
shared_preferences_android-2.4.0
shared_preferences_foundation-2.5.4
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.4
sign_in_with_apple_web-2.1.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.2
url_launcher_linux-3.2.1
url_launcher_macos-3.2.2
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.7.16
video_player_avfoundation-2.6.5
video_player_web-2.3.3
wakelock_plus-1.2.10
webview_flutter-4.10.0
webview_flutter_android-4.2.0
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-30 07:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-30 07:32 UTC
Labels: in triage
