### ISSUE TITLE
Assets not serving on the web

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#50624] opened 2020-02-12 04:44 UTC
Moving @matthew-carroll's [comment](https://github.com/flutter/flutter/issues/40707#issuecomment-585003686) into a dedicated issue:

> I just created a Flutter project with web support. I've listed my `assets/` directory under the `assets:` key in the pubspec file. No asset is copied to the `/web` directory, no assets are referenced in the `manifest.json` file, and the asset I'm trying to display is getting a 404.
>
> I've tried killing and rebuilding the app with `flutter web build` followed by `flutter run -d chrome`. I'm still not seeing any change with relation to asset inclusion.
>
> Is there anything else I should be trying for this? Also, do we have any CI tests that verify this particular behavior?

```
 Flutter (Channel master, v1.15.4-pre.20, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.15.4-pre.20 at 
    • Framework revision 781cd4d87c (52 minutes ago), 2020-02-11 18:25:17 -0800
    • Engine revision e4f46f32f1
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 fd992e423e)
```

/cc @jonahwilliams (could be a tools issue), @hterkelsen (who knows a thing or two about web assets)

**Comment by yjbanov** [comment] 2020-02-12 04:47
> do we have any CI tests that verify this particular behavior?

There's probably some unit-tests in the tools, but I'm pretty sure we don't have any e2e tests. The good news is we're bringing up infrastructure for integration-testing web functionality this quarter, so at least we should be able to write tests for something like this hopefully very soon.

**Comment by hterkelsen** [comment] 2020-02-13 21:06
Can you provide a small repro? I just tried the following:

1. Create a new project with `flutter create .`
2. `mkdir assets`
3. `cp ~/Downloads/my_image.png assets`
4. Add this to `pubspec.yaml`:

```yaml
  assets:
    - assets/
```

5. Add the asset image to my app in `lib/main.dart`:

```dart
  @override
  Widget build(BuildContext context) {
    ...
    Image.asset('assets/my_image.png'),
  }
```

And the image is loading correctly.

**Comment by matthew-carroll** [comment] 2020-02-18 04:36
I tried creating a new project and reproducing the issue. The issue isn't reproducing.

I'm curious, I think in my primary project where this issue occurs, I began with the web flag turned off, then I realized I needed to enable the web flag so I did, then I reran `flutter create .` to fill in the web details. Is it possible that doing so corrupted something that now prevents asset inclusion?

**Comment by matthew-carroll** [comment] 2020-02-18 04:55
Also, upon further inspection of my primary project, the `/build` directory does contain the expected assets. But for some reason it triggers a 404 on the image request.

**Comment by matthew-carroll** [comment] 2020-02-18 04:56
@yjbanov I won't be able to remove the "waiting for customer response" tag because you filed this issue and I no longer GitHub privileges.

**Comment by jonahwilliams** [comment] 2020-02-18 04:57
What sorts of errors are you seeing in the browser console? Just a network tab 404 or anything else?

**Comment by matthew-carroll** [comment] 2020-02-18 05:00
Here's what I see in Chrome's dev console:

```
DevTools failed to parse SourceMap: http://localhost:60874/dwds/src/injected/client.dart.js.map
html_dart2js.dart:17441 GET http://localhost:60874/assets/logo-full_no-bk_with-padding.png 404 (Not Found)
Error while trying to load an asset: Failed to load asset at "assets/logo-full_no-bk_with-padding.png" (404)
```

There are long stacktraces in the 2nd two lines. I can provide those if needed, but it's a lot of content.

**Comment by jonahwilliams** [comment] 2020-02-18 05:04
FWIW the development mode with hot restart and the release mode have fairly different runtimes. So `flutter build web` will put together a bundle that can be served with a basic http server, such as:

`flutter build web`
`cd build/web`
`python -m SimpleHTTPServer`

Whereas `flutter run -d chrome` will spawn a development build that is sufficiently different. 

It might be worth trying to server the release build first.

**Comment by matthew-carroll** [comment] 2020-02-18 05:09
I just tried using the python server with `flutter build web` and the problem still occurs.

**Comment by matthew-carroll** [comment] 2020-02-18 05:10
I'll just post this project. Gimme a minute.

**Comment by matthew-carroll** [comment] 2020-02-18 05:12
Here's the project that is failing for me, maybe you can find some configuration that I messed up or corrupt files.

https://github.com/matthew-carroll/superdeclarative_com

**Comment by jonahwilliams** [comment] 2020-02-18 05:21
I can see the error for the asset failing to load `assets/logo-full_no-bk_with-padding.png`, but this one isn't listed in the pubspec.yaml so I think that is expected

**Comment by matthew-carroll** [comment] 2020-02-18 05:40
That must have been a last minute mistake. I just pushed a change that includes everything under `- assets/` and the problem still occurs with `flutter build web`.

**Comment by jonahwilliams** [comment] 2020-02-18 05:51
Ahh, in this case the second Image.asset invocation is missing the leading `assets/` as part of the key:

https://github.com/matthew-carroll/superdeclarative_com/blob/master/lib/main.dart#L202

**Comment by matthew-carroll** [comment] 2020-02-18 06:01
Ok, seems to be working now. The reason the other image that I included didn't show up is because I stuck in a widget tree that was gated on a media query. I'm not entirely sure if this was always working - I thought I had the path correct at one point. Nonetheless, it seems to be working now. Thanks @jonahwilliams 

@yjbanov please feel free to close this ticket.

**Closed** 2020-02-18 07:16 UTC
Labels: a: assets, a: build, severe: regression, tool, ☸ platform-web

**Comment by sgehrman** [comment] 2021-07-21 04:57
Tried everything and can't get it working.
