### ISSUE TITLE
not able to download video 

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#31011] opened 2019-04-13 13:21 UTC
```
I/zygote  (23872): WaitForGcToComplete blocked NativeAlloc on None for 26.939ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/chatty  (23872): uid=10085(kw.ltd.twitter.facebook.youtube.twitter_facebook_youtube_app) identical 2 lines
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): Do partial code cache collection, code=246KB, data=162KB
I/zygote  (23872): After code cache collection, code=246KB, data=162KB
I/zygote  (23872): Increasing code cache capacity to 1024KB
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 105(63KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1647KB/3MB, paused 10.117ms total 90.411ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/chatty  (23872): uid=10085(kw.ltd.twitter.facebook.youtube.twitter_facebook_youtube_app) identical 4 lines
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 116(63KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1663KB/3MB, paused 24.558ms total 481.739ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 197(47KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1631KB/3MB, paused 9.545ms total 127.561ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 819(80KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1631KB/3MB, paused 1.041ms total 135.663ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
D/        (23872): PlayerBase::stop() from IPlayer
D/AudioTrack(23872): stop() called with 363600 frames delivered
W/cr_MediaCodecBridge(23872): Releasing: OMX.google.h264.decoder
I/zygote  (23872): NativeAlloc concurrent copying GC freed 112(48KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1695KB/3MB, paused 988us total 237.823ms
D/SurfaceUtils(23872): disconnecting from surface 0xc26d0808, reason disconnectFromSurface
D/gralloc_ranchu(23872): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
D/        (23872): HostConnection::get() New Host Connection established 0xcecb4500, tid 24532
D/gralloc_ranchu(23872): gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
W/cr_MediaCodecBridge(23872): Codec released
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 457(96KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1646KB/3MB, paused 1.760ms total 104.004ms
D/skia    (23872): Program linking failed.
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 213(66KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1612KB/3MB, paused 61.241ms total 107.694ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 30(47KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1643KB/3MB, paused 990us total 133.246ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 209(52KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1627KB/3MB, paused 43.098ms total 91.804ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
E/EGL_emulation(23872): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation(23872): tid 24062: eglQueryContext(1830): error 0x3004 (EGL_BAD_ATTRIBUTE)
D/        (23872): PlayerBase::PlayerBase()
D/        (23872): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(23872): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
I/AudioTrack(23872): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 1440 -> 1440
D/AudioTrack(23872): Client defaulted notificationFrames to 720 for frameCount 1440
I/OMXClient(23872): Treble IOmx obtained
D/SurfaceUtils(23872): connecting to surface 0xcfc66008, reason connectToSurface
I/MediaCodec(23872): [OMX.google.h264.decoder] setting surface generation to 24444935
D/SurfaceUtils(23872): disconnecting from surface 0xcfc66008, reason connectToSurface(reconnect)
D/SurfaceUtils(23872): connecting to surface 0xcfc66008, reason connectToSurface(reconnect)
E/ACodec  (23872): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
D/MediaCodec(23872): [OMX.google.h264.decoder] setting dataspace on output surface to #103
W/GrallocMapperPassthrough(23872): buffer descriptor with invalid usage bits 0x2000
D/        (23872): HostConnection::get() New Host Connection established 0xcecb4880, tid 24708
D/SoftwareRenderer(23872): setting dataspace on output surface to #103
W/GrallocMapperPassthrough(23872): buffer descriptor with invalid usage bits 0x2000
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 689(124KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1662KB/3MB, paused 1.077ms total 259.545ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/zygote  (23872): NativeAlloc concurrent copying GC freed 235(80KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1631KB/3MB, paused 6.618ms total 61.556ms
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
W/zygote  (23872): Attempt to remove non-JNI local reference, dumping thread
I/chromium(23872): [INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20190408/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.", source: https://www.getfvid.com/downloader (0)
D/        (23872): PlayerBase::stop() from IPlayer
D/AudioTrack(23872): stop() called with 478080 frames delivered
W/cr_MediaCodecBridge(23872): Releasing: OMX.google.h264.decoder
D/SurfaceUtils(23872): disconnecting from surface 0xcfc66008, reason disconnectFromSurface
W/cr_MediaCodecBridge(23872): Codec released
```

**Comment by Blaxou** [comment] 2019-04-13 14:32
Maybe you try to elaborate ? Say a bit more about the issue, stick to the issue template, `format the code` as it is meant to ?? You probably won't get any answers considering the way you asked ;) Just saying ;)

**Comment by kw2019ltd** [comment] 2019-04-13 16:10
i used the code from example in githube,  then change the url to https://www.fbdown.net/  and try to download  any facebook video try https://www.facebook.com/watch/?v=346505585999613 then press download nothing happend , above info printed in console.
![Screenshot_20190412-095509](https://user-images.githubusercontent.com/47334522/56082258-5dab1100-5e1f-11e9-9371-9355ce56d421.jpg)

**Comment by Blaxou** [comment] 2019-04-14 23:56
You are only displaying a webview and not a browser, thus you can't download or anything inside that webview
What you could do instead is find a pattern in the download url and do a request to that url with the `http` package.

**Comment by kw2019ltd** [comment] 2019-04-15 06:21
not good this feature needs to be added, in case iam doing checkout using pay pal and pay pal generated for me pdf file and i want to download it  it should be possible.

**Comment by AresVampire** [comment] 2019-05-04 02:05
Yes, I have this problem as well, there needs to be download feature in webview

**Comment by Blaxou** [comment] 2019-12-15 10:40
Duplicate of #39321 I guess ?

**Comment by iapicca** [comment] 2020-01-14 12:42
Hi @kw2019ltd 
as @Blaxou  pointed out
I see there's an open [issue](https://github.com/flutter/flutter/issues/39321) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-01-14 12:42 UTC
Labels: p: webview
