### ISSUE TITLE
GPU Hang Error on iOS 15 (Real device only)

### ISSUE THREAD

**Issue by RubyRook** [flutter/flutter#154328] opened 2024-08-29 10:35 UTC
### Steps to reproduce

I know this problem happened in version 3.24. But after update to 3.24.1 it still happen.

- iOS: 15.7.1
- iPhone 7 Plus (physical device)
- I don't see problem on virtual device

### Expected results

Show modal bottom sheet above WebViewWidget and scroll content inside modal bottom sheet without any problem.

### Actual results

App crash when rotate to landscape when scroll content inside modal bottom sheet.
* I found out that, if i disable Card Widget shadow inside modal bottom sheet everything work normally

### Code sample

<details open><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  final controller = WebViewController();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    controller.loadRequest(
        Uri.parse('https://flutter.dev/?gad_source=1&gclid=Cj0KCQjww5u2BhDeARIsALBuLnNGzjFH1Q6kq_LXdRphXkCW1LWIdS684KHw06PfD_BFJtq3OqMuzskaAhekEALw_wcB&gclsrc=aw.ds'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: ListBody(
          children: [
            AspectRatio(
              aspectRatio: const Size(640, 290).aspectRatio,
              child: WebViewWidget(controller: controller,),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showModalBottomSheet(
            context: context,
            isScrollControlled: true,
            showDragHandle: true,
            useSafeArea: true,
            builder: (context) {
              return SingleChildScrollView(
                child: ListBody(
                  children: List.generate(6, (index) => Card(
                    clipBehavior: Clip.antiAlias,
                    color: Colors.blue,
                    margin: const EdgeInsets.symmetric(horizontal: 10, vertical: 6,),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),),
                    child: const AspectRatio(
                      aspectRatio: 2.35/1,
                    ),
                  ),),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/b4f4130a-98cc-4ce9-aff3-150b2d2e3e47

</details>

### Logs

<details open><summary>Logs</summary>

```console
Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (00000005:kIOGPUCommandBufferCallbackErrorInnocentVictim)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
"/Users/sounniroth/development/flutter 3.24/bin/flutter" doctor --verbose
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/sounniroth/development/flutter 3.24
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (9 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sounniroth/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2
```

</details>

**Comment by huycozy** [comment] 2024-08-29 12:00
This seems to be similar to https://github.com/flutter/flutter/issues/153574 which was confirmed as fixed on Flutter master channel. Can you switch to master channel and confirm?

You can also check https://github.com/flutter/flutter/issues/153574#issuecomment-2305256726 to see if it works for you in Flutter 3.24.1 as well.

**Comment by RubyRook** [comment] 2024-08-30 03:39
[✓] Flutter (Channel master, 3.25.0-1.0.pre.203, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)

I can confirm no `GPU Hang Error` in this `Channel master`. But scroll performance inside Modal bottom sheet feel laggy.

**Comment by huycozy** [comment] 2024-08-30 05:42
>But scroll performance inside Modal bottom sheet feel laggy.

Thanks for confirming this on master. The performance could be another issue. Please help to open a new issue for better tracking, see [My app is slow or missing frames issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=from%3A+performance+template&projects=&template=5_performance_speed.yml). 

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/153574.

**Closed by huycozy** 2024-08-30 05:42 UTC
Labels: in triage

**Comment by mtallenca** [comment] 2024-09-02 17:17
> This seems to be similar to #153574 which was confirmed as fixed on Flutter master channel. Can you switch to master channel and confirm?
> 
> You can also check [#153574 (comment)](https://github.com/flutter/flutter/issues/153574#issuecomment-2305256726) to see if it works for you in Flutter 3.24.1 as well.

Master seemed to fix the issue - however - the "fix" was that FLTUseMetalLayer is now defaults to true in master.  In master if you see this to false in the plist you will still get the GPU hangs.

The commit causing the GPU hangs...

[643848aa99f04b316999af9a17c79ea5e826f76b](https://github.com/flutter/flutter/commit/643848aa99f04b316999af9a17c79ea5e826f76b) - Apr 5 - started seeing old iPad GPU hang (our 3 tap - freeze)
[477ebd831c1253d2e19ac8084963f3088282ddd3](https://github.com/flutter/flutter/commit/477ebd831c1253d2e19ac8084963f3088282ddd3) - Apr 5 - previous commit working

**Comment by RubyRook** [comment] 2024-09-03 06:17
@mtallenca, yes GPU hang when i set FLTUseFlutterMetalLayer to false in info.plist. But this problem out of my hand, and look like i can only wait for hot fix release.
