### ISSUE TITLE
NestedScrollView and IndexedStack coupled scrolling

### ISSUE THREAD

**Issue by Mawrte** [flutter/flutter#89544] opened 2021-09-06 10:59 UTC
When i have a `NestedScrollView` and the body is an `IndexedStack`-based tab bar view with a vertical `ScrollView` per tab, like the one in the example down here, the `ScrollView`s in the tabs scroll together even though only one tab is active and being scrolled down.

## Code to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  // This widget is the root of your application.
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  late TabController tabController;

  @override
  void initState() {
    tabController = TabController(length: 2, vsync: this)
      ..addListener(_listener);
    super.initState();
  }

  @override
  void dispose() {
    tabController
      ..removeListener(_listener)
      ..dispose();
    super.dispose();
  }

  void _listener() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: NestedScrollView(
          floatHeaderSlivers: true,
          body: IndexedStack(
            index: tabController.index,
            children: [
              ListView.builder(
                itemBuilder: (context, index) => Text(
                  index.toString(),
                  style: TextStyle(
                    fontSize: 32,
                  ),
                ),
              ),
              Container(
                color: Colors.yellowAccent,
                child: ListView.builder(
                  itemBuilder: (context, index) => Text(index.toString()),
                ),
              ),
            ],
          ),
          headerSliverBuilder:
              (BuildContext context, bool innerBoxIsScrolled) => [
            SliverAppBar(
              bottom: TabBar(
                controller: tabController,
                tabs: [
                  Tab(text: '1'),
                  Tab(text: '2'),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
If i am in tab 1 and scroll the list, tab 2 should not scroll.

**Actual results:** 
if I am in tab 1 and scroll the list, tab 2 scrolls too.

Note:
This does not happen if the parent is a `Scaffold` instead of a `NestedScrollView` or if the body of the `NestedScrollView` is the default flutter `TabBarView` (which is based on a `PageView`).
This always happens whenever the `NestedScrollView` body's tab bar view is made with a `Stack`

<details>
  <summary>Logs</summary>

output of `flutter analyze`
```
Analyzing nested_navigation_cross_fade...                       
No issues found! (ran in 1.4s)
```

output of `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale it-IT)
    • Flutter version 2.2.3 at /Users/giuseppedimarzo/fvm/versions/stable
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/giuseppedimarzo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • FD4340EB-5039-4331-8678-21DB5C522A89 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-09-06 12:00
Hi @Mawrte 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/36419
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-06 12:00 UTC
Labels: in triage
