### ISSUE TITLE
Add Feature Drag and Drop and Design View

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#116470] opened 2022-12-04 03:35 UTC
I Have Suggestion Please Add Feature Add Feature Drag and Drop and Design View Integrated in Android Studio or VS Code Like in Visual Studio in Visual basic language.
I Mean When Create Project in Visual Studio Visual basic
Creating Form Display You can Drag and Drop any element in form offline and after design When double click to Button or any Elements It Switch to Programming it
I want to see this in Flutter.

**Comment by darshankawar** [comment] 2022-12-05 07:32
Closing as self duplicate of https://github.com/flutter/flutter/issues/116461
Please don't open multiple issues for same reason.

**Closed by darshankawar** 2022-12-05 07:32 UTC
Labels: in triage
