### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by KalaliEhsan** [flutter/flutter#100197] opened 2022-03-16 08:14 UTC
## Command
```
flutter pub add printing
```

I added this package. But this error occurred on this proccess.
Flutter 2.10.3 channel stable
Dart 2.16.1

**Comment by darshankawar** [comment] 2022-03-16 08:59
Closing this as duplicate of https://github.com/flutter/flutter/issues/96568

**Closed by darshankawar** 2022-03-16 08:59 UTC
Labels: in triage
