### ISSUE TITLE
Enabling NNBD in future releases

### ISSUE THREAD

**Issue by flukejones** [flutter/flutter#53541] opened 2020-03-29 21:45 UTC
Given that the v2.8 release of Dart will be including almost complete bring-up of [non-nullable](https://github.com/dart-lang/sdk/milestone/77), and null is a constant source of issues - what are the plans for flutter to include support for NNBD (if any)?

I am aware of this topic being broached a few times in the past, but due to the imminent release of Dart with NNBD, it may be wise to start considering support of NNBD, or at the very least create an issue to centralise all information pertaining to this.

**Comment by cbenhagen** [comment] 2020-03-30 08:30
Looks like this tracked here: https://github.com/dart-lang/sdk/issues/40146

**Comment by flukejones** [comment] 2020-03-30 21:05
> Looks like this is being tracked here: [dart-lang/sdk#40146](https://github.com/dart-lang/sdk/issues/40146)

Ah thanks, I don't think I would have looked for an issue central to flutter in the dart issues...

**Comment by goderbauer** [comment] 2020-04-01 22:14
Duplicate of https://github.com/flutter/flutter/issues/53662.

**Closed by goderbauer** 2020-04-01 22:14 UTC
Labels: dependency: dart, engine, framework, proposal
