### ISSUE TITLE
[file_selector] not working on web

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#80994] opened 2021-04-22 21:14 UTC
I am not sure if it is possible to use the plugin on the web but there is a package for it on pub.dev so yea not very sure 🙃

## Steps to Reproduce

1. Run `flutter create flutter_selector_problem`.
2. add a button to get save path on home screen of the default app
3. add this code in the `onPressed` and import the file selector:
```dart
      /// get save path
      final String savePath = await file_selector.getSavePath(
        suggestedName: "$randomNumber.jpg",
        acceptedTypeGroups: <file_selector.XTypeGroup>[
          file_selector.XTypeGroup(label: 'images', extensions: ['jpg']),
        ],
      );

      if (savePath == null || savePath.isEmpty) {
        print("Save path is empty or null");
        setBusy(false);
        return;
      }
```
4. make sure you added `file_selector` and `files_selector_web` to the `pubspec.yaml`:
![image](https://user-images.githubusercontent.com/41989385/115785837-ae6b8200-a3c8-11eb-9a4b-3e50d292367d.png)
Add other platforms if you need them but for reproducing the bug no need 🙃

**Expected results:** 

I expect a dialog to pop up so I can get a save path, if possible

**Actual results:** 

Nothing, empty path

<details>
  <summary>Logs</summary>

```
PS C:\Users\yazee> flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.5 at Y:\extra\flutter
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\yazee\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\yazee\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code, 64-bit edition (version 1.55.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.42

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2021-04-22 21:53
Duplicate of https://github.com/flutter/flutter/issues/78142

**Closed by stuartmorgan** 2021-04-22 21:53 UTC
