### ISSUE TITLE
Engine tree closing sporadically on Mac builder_cache build

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141688] opened 2024-01-17 16:08 UTC
Due to the `Archive builder` step crashing or timing out?

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20builder_cache/2878/overview

cc @ricardoamador @godofredoc

**Comment by ricardoamador** [comment] 2024-01-17 17:08
Working on this now.

**Comment by ricardoamador** [comment] 2024-01-17 17:20
This appears to be an issue with uploading to CAS and I have reached out to the LUCI team to see if anything is happening on there side.

**Comment by ricardoamador** [comment] 2024-01-17 19:34
Updating logging to see if we can get more information from the archive command: https://flutter-review.googlesource.com/c/recipes/+/54126

**Comment by ricardoamador** [comment] 2024-01-17 20:54
https://ci.chromium.org/ui/p/flutter/builders/prod.shadow/Mac%20builder_cache/1/overview
Shows the debug logging but I am not sure if it will be helpful. It appears that the archive call is just minting tokens and not doing much else.

**Comment by ricardoamador** [comment] 2024-01-17 22:24
Okay from the LUCI team: 

```
Cas is actually busy archiving stuff, in particular paths like: 
/Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/Ruby.framework/Versions/Current/Headers/ruby/missing.h
```

```
is it expected to cas archive OSX SDK? It has tons and tons of files.
regardless, it appears it is stuck in some kind of a loop, since I see it revisits same set of files
IIRC OSX SDK has unusual symlinking structure, maybe cas archive is getting confused
```

```
it if helps, there's a bunch of OSX SDKs there
/Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts/SDKs
% ls
MacOSX13.3.sdk        iPhoneOS16.4.sdk    iPhoneSimulator16.4.sdk
```

**Comment by ricardoamador** [comment] 2024-01-17 22:26
Possibly as a result of this change: https://github.com/flutter/buildroot/pull/807

**Comment by keyonghan** [comment] 2024-01-17 22:36
`Mac builder_cache` keeps refreshing/uploading the `[CACHE]/builder` to CAS as a second layer of cache.
https://github.com/flutter/buildroot/pull/807 changed the SDKs to `builder/src/flutter/prebuilts`, and this caused the CAS upload failure due to symlink issues as discussed in http://go/flutter-cl/53803.

To unblock, we should remove the SDKs from `builder` when uploading to CAS.

**Comment by keyonghan** [comment] 2024-01-18 19:16
Issue is unblocked and @ricardoamador is working on a generic way to handle cache.

**Comment by ricardoamador** [comment] 2024-01-19 18:58
Reopening so I can track the switch back to prod from staging for this target.

**Comment by ricardoamador** [comment] 2024-01-22 16:17
@zanderso are you okay if I move this back to prod today?

**Comment by zanderso** [comment] 2024-01-22 16:18
Looks green on the dashboard for awhile so sgtm.

**Comment by zanderso** [comment] 2024-01-23 05:26
Reopening because it seems like engine presubmit checks started failing after this was reenabled earlier today.

**Comment by ricardoamador** [comment] 2024-01-23 16:59
@zanderso okay. Do you have a link?

**Comment by zanderso** [comment] 2024-01-23 17:01
From https://github.com/flutter/engine/pull/49959, the builds under https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_unopt/16029/overview failed in the gn step with logs

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8758142983441827537/+/u/gn_--ios_--runtime-mode_debug_--simulator_--no-lto_--rbe_--no-goma_--xcode-symlinks_--rbe-server-address_unix:___Volumes_Work_s_w_ir_x_w_recipe_cleanup_rbev6jb28cx_reproxy.sock/stdout?format=raw

**Comment by zanderso** [comment] 2024-01-23 17:19
Does this list here https://github.com/flutter/engine/blob/main/.ci.yaml#L133 need to include a `Library` entry as well?

**Comment by ricardoamador** [comment] 2024-01-23 17:25
If that needs to be excluded then yes. I only added the other because that was the cause in post submit. But I can try adding this to see if that fixes it.

**Comment by keyonghan** [comment] 2024-01-23 17:28
The PR (move to prod) was landed around 9:05am 01/22.
The mentioned issue started happening around 14:48pm 01/22 ([first occurrence](https://ci.chromium.org/ui/b/8758161086267315697))

I would expect the issue to happen right after the PR if it's related to the cache.

**Comment by zanderso** [comment] 2024-01-23 17:45
I don't have a deep understanding here, but my expectation would be the opposite. That is, an issue introduced by caching would take time to present as machines with a corrupted cache start taking on new jobs.

There are no suspicious engine commits that I can see in the timeframe. The failing script `ios_sdk.py` hasn't been changed in 3 years, and there were no rolls from flutter/buildroot in the timeframe.

Another datapoint is that this failure is only happening in the try pool. This failure is not happening in prod.

**Comment by keyonghan** [comment] 2024-01-23 20:30
One thing I can confirm is: bots (which had failed builds) all ran an unexpected `KILLED` build earlier, which triggered `mount cache` (fetching from earlier uploaded `builder` dir in CAS):
Example: https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac%20Engine%20Drone/644983/overview
![Screenshot 2024-01-23 at 11 24 33 AM](https://github.com/flutter/flutter/assets/54558023/17adf1a9-2aec-4c45-a641-dd41423d89e6)

Cleaning the cache does fix the problem:
Earlier failed build: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/3ba9b3308c6d9e30172925fb7da66eb1322f0fd3d7964a2baf42a4bd1a460285/+/build.proto?server=chromium-swarm.appspot.com
Cleaning cache and reran on the same bot succeeded: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/7e90f58bae25c80a1aa688642951d6f516903f10c55268ee6707ab287a954678/+/build.proto?server=chromium-swarm.appspot.com

**Comment by keyonghan** [comment] 2024-01-23 20:33
Another observation: the issue seems mitigated for recent builds:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_unopt?limit=200

If any new failure, I will validate if https://github.com/flutter/engine/pull/49971 helps.

**Comment by keyonghan** [comment] 2024-01-23 20:53
https://github.com/flutter/flutter/issues/141688 to track using different CAS archives for different pools.

**Comment by keyonghan** [comment] 2024-01-23 21:23
A new failure happened: https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac%20Engine%20Drone/652096/overview
The failure reproduced on the same bot: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e2e64d30d87a978496120001a53d33825dbdb86dcab0be85d52fb862a053ca4e/+/build.proto?server=chromium-swarm.appspot.com
With https://github.com/flutter/engine/pull/49971 (re-mounting the second-layer cache) does fix the issue: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b935110a06a4377e3eb4a2e46cd4ecd226396281effecf800b0d0ebc50a845fd/+/build.proto?server=chromium-swarm.appspot.com

I will force re-mounting the second-layer cache (this adds only 2 mins compared to the complete cache clobber which increases 15 mins) and make sure all bots have been refreshed. Then revert.

**Comment by keyonghan** [comment] 2024-01-24 16:34
http://go/flutter-cl/54361 landed yesterday, and we haven't seen any failure since then: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_unopt?limit=200

Will give it another day to validate, and then I will revert the change to bring back the 2+ mins.

**Comment by keyonghan** [comment] 2024-01-24 23:32
No single failure happens by now. We should have high confidence the Cache has been refreshed on each bot. reverting the force cache mount CL: http://go/flutter-cl/54384

**Closed** 2024-01-29 17:14 UTC
Labels: team-infra, P0, triaged-infra
