### ISSUE TITLE
Hide keyboard on hot restart

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#70937] opened 2020-11-20 13:43 UTC
Hot restart in Flutter means full restart of Flutter application, so I think keyboard should also hide.

**Comment by imeDevelopers** [comment] 2020-11-20 14:08
@sanekyy 
i am not agree for hot reload ..
i am agree for hot Restart ..

**Comment by sidrao2006** [comment] 2020-11-20 14:10
@sanekyy hot reload is not a full app restart. Only the changes are pushed...also the state is preserved. This my may be the reason that the keyboard is not dismissed. 

If you disagree, please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample

Thank you!

**Comment by sanekyy** [comment] 2020-11-20 14:16
@imeDevelopers @sidrao2006

Ou, yep, sorry, my mistake.

Of course I talk about hot restart:)

**Comment by sidrao2006** [comment] 2020-11-20 14:18
Duplicate of #10713
Hey @sanekyy , I found an open issue addressing this problem. Please post the output of `flutter doctor -v` and follow up there.

Thanks.

**Comment by darshankawar** [comment] 2020-11-23 07:42
Closing this as duplicate of [10713](https://github.com/flutter/flutter/issues/10713)

**Closed by darshankawar** 2020-11-23 07:42 UTC
