### ISSUE TITLE
PlatformView always shows as top component, ignoring Stack components.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#109531] opened 2022-08-15 12:34 UTC
I already checked https://github.com/flutter/flutter/issues/103630 , but it seems the problem is slightly different.

The problem is, 

I'm trying to draw some flutter components on top of arview (native platform view), and it was fine at 2.8.1, but it is broken at flutter 3.0.5. The screen only shows AR view without any flutter GUI components.

I'm using flutter_ar_core library (https://pub.dev/packages/arcore_flutter_plugin) and it is not implemented as hybrid composition.
We can see the code like this, at here, https://github.com/giandifra/arcore_flutter_plugin/blob/master/lib/src/arcore_android_view.dart

```kotlin
class ArCoreAndroidView extends AndroidView {
  final String viewType;
  final PlatformViewCreatedCallback? onPlatformViewCreated;
  final ArCoreViewType arCoreViewType;
  final bool debug;

  ArCoreAndroidView(
      {Key? key,
      required this.viewType,
      this.onPlatformViewCreated,
      this.arCoreViewType = ArCoreViewType.STANDARDVIEW,
      this.debug = false})
      : super(
          viewType: viewType,
          onPlatformViewCreated: onPlatformViewCreated,
          creationParams: <String, dynamic>{
            "type": arCoreViewType == ArCoreViewType.AUGMENTEDFACE
                ? "faces"
                : arCoreViewType == ArCoreViewType.AUGMENTEDIMAGES
                    ? "augmented"
                    : "standard",
            "debug": debug
          },
          creationParamsCodec: const StandardMessageCodec(),
        );
}
```

So, I thought that, the problem mentioned in #103630 is for hybrid composition case, but why the case of virtual display also has similar problem? How can I solve this? 

NOTE: For the record, I tried to change this into hybrid composition case, with simply following the direction mentioned at https://docs.flutter.dev/development/platform-integration/android/platform-views#on-the-dart-side but, it was not feasible. (it seems there are some performance problem, google ar core cannot calculate the view.)

**Comment by exaby73** [comment] 2022-08-15 13:07
Hello @wangmir. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) without using 3rd party libraries so that we can investigate this issue in isolation? Would be great if you can also provide the outputs to `flutter doctor -v` and `flutter run -v`. Thank you.

**Comment by wangmir** [comment] 2022-08-15 13:22
@exaby73 Oh, when I upgrade to beta, it solved. Thanks.

**Comment by exaby73** [comment] 2022-08-15 13:54
Glad it worked for you. Marking this as duplicate of https://github.com/flutter/flutter/issues/103630

**Closed by exaby73** 2022-08-15 13:54 UTC
Labels: in triage
