### ISSUE TITLE
Exception: Invalid image data on Android 

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#67823] opened 2020-10-10 14:51 UTC
When I try to load an image from my drive with file id. 
**Image is loading fine in flutter web**. but when I try to show an image with the same widget in android mobile it shows Error 
```
I/flutter (32291): Exception: Invalid image data
Reloaded 26 of 1801 libraries in 2,141ms.
I/flutter (32291): Exception: Invalid image data
[38;5;244mI/flutter (32291): #0      _futurize  (dart:ui/painting.dart:4856:5))[39;49m
[38;5;244mI/flutter (32291): #1      ImageDescriptor.encoded  (dart:ui/painting.dart:4724:12))[39;49m
[38;5;244mI/flutter (32291): #2      instantiateImageCodec  (dart:ui/painting.dart:1721:60))[39;49m
I/flutter (32291): <asynchronous suspension>
[38;5;244mI/flutter (32291): #3      PaintingBinding.instantiateImageCodec[39;49m 
 package:flutter/…/painting/binding.dart
[38;5;244mI/flutter (32291): #4      NetworkImage._loadAsync[39;49m 
 package:flutter/…/painting/_network_image_io.dart
I/flutter (32291): <asynchronous suspension>
[38;5;244mI/flutter (32291): #5      NetworkImage.load[39;49m 
 package:flutter/…/painting/_network_image_io.dart
[38;5;244mI/flutter (32291): #6      ImageProvider.resolveStreamForKey.<anonymous closure>[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (32291): #7      ImageCache.putIfAbsent[39;49m 
 package:flutter/…/painting/image_cache.dart
[38;5;244mI/flutter (32291): #8      ImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (32291): #9      ScrollAwareImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/widgets/scroll_aware_image_provider.dart
I/flutter (32291): #10     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provid
Reloaded 0 of 1801 libraries in 600ms.
I/flutter (32291): Exception: Invalid image data
[38;5;244mI/flutter (32291): #0      _futurize  (dart:ui/painting.dart:4856:5))[39;49m
[38;5;244mI/flutter (32291): #1      ImageDescriptor.encoded  (dart:ui/painting.dart:4724:12))[39;49m
[38;5;244mI/flutter (32291): #2      instantiateImageCodec  (dart:ui/painting.dart:1721:60))[39;49m
I/flutter (32291): <asynchronous suspension>
[38;5;244mI/flutter (32291): #3      PaintingBinding.instantiateImageCodec[39;49m 
 package:flutter/…/painting/binding.dart
[38;5;244mI/flutter (32291): #4      NetworkImage._loadAsync[39;49m 
 package:flutter/…/painting/_network_image_io.dart
I/flutter (32291): <asynchronous suspension>
[38;5;244mI/flutter (32291): #5      NetworkImage.load[39;49m 
 package:flutter/…/painting/_network_image_io.dart
[38;5;244mI/flutter (32291): #6      ImageProvider.resolveStreamForKey.<anonymous closure>[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (32291): #7      ImageCache.putIfAbsent[39;49m 
 package:flutter/…/painting/image_cache.dart
[38;5;244mI/flutter (32291): #8      ImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (32291): #9      ScrollAwareImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/widgets/scroll_aware_image_provider.dart
I/flutter (32291): #10     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provid
```
``` 
Image.network(
              'https://drive.google.com/uc?export=download&id=$imagefileid',
              loadingBuilder: (ctx, i, k) => Row(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [CircularProgressIndicator()]),
              errorBuilder: (ctx, o, n) {
                print(o);
                print(n);
                return  Image.asset(
                        'assets/empty-avatar.png',
                        fit: BoxFit.contain);
              },
            ),
```

**Comment by iapicca** [comment] 2020-10-10 20:04
@anandsubbu007 
can you provide your `flutter doctor -v` and a minimal reproducible code sample

**Comment by darshankawar** [comment] 2020-10-12 10:20
@anandsubbu007 
Please provide above details.
Thanks.

**Comment by anandsubbu007** [comment] 2020-10-13 02:49
This Code is working for web. 
i also tried sending auth header. it is also not working

```
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart';
import 'package:googleapis/drive/v3.dart' as drive;
import 'package:http/io_client.dart';
import 'package:http/http.dart';
import 'package:google_sign_in/google_sign_in.dart';

Future main() async {
  runApp(MaterialApp(home: ProfileAvatar()));
}

class ProfileAvatar extends StatefulWidget {
  const ProfileAvatar({Key key}) : super(key: key);

  @override
  _ProfileAvatarState createState() => _ProfileAvatarState();
}

class _ProfileAvatarState extends State<ProfileAvatar> {
  @override
  Widget build(BuildContext context) {
    String fileid;
    Future getImage(ImageSource source) async {
      showDialog(
        barrierDismissible: false,
        context: context,
        child: Dialog(
          child: Container(
            padding: EdgeInsets.all(15),
            child: Text(
                'Please Wait, '
                '\nYour Image Is Uploading to Google Drive...',
                overflow: TextOverflow.clip),
          ),
        ),
      );
      PickedFile pickedFile =
          await ImagePicker().getImage(source: source, imageQuality: 25);
      String base = basename(pickedFile.path);
      final vals = await pickedFile.readAsBytes();
      fileid = await uploadImageToDrive(
          media: drive.Media(Stream.value(vals), vals.length), filename: base);
      print('fileid :: $fileid');
      Navigator.pop(context);
      if (fileid != null) {
        setState(() {});
      }
    }

    return Scaffold(
        appBar: AppBar(),
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Camera'),
              onPressed: () async {
                await getImage(ImageSource.camera);
              },
            ),
            Container(
                color: Colors.grey,
                alignment: Alignment.center,
                width: 150,
                height: 150,
                foregroundDecoration: BoxDecoration(shape: BoxShape.circle),
                child: Image.network(
                  // 'http://www.google.de/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
                  'https://drive.google.com/uc?export=download&id=$fileid',
                  loadingBuilder: (ctx, i, k) => Container(
                      alignment: Alignment.center,
                      width: 150,
                      height: 150,
                      child: Center(child: CircularProgressIndicator())),
                  errorBuilder: (ctx, o, n) {
                    print(o);
                    return Icon(Icons.error);
                  },
                )),
          ],
        ));
  }
}

Future<String> uploadImageToDrive({drive.Media media, String filename}) async {
  try {
    GoogleSignIn googleSignIn = GoogleSignIn(scopes: [
      drive.DriveApi.DriveFileScope,
      drive.DriveApi.DriveAppdataScope,
    ]);
    GoogleSignInAccount gauth =
        await googleSignIn.signInSilently(suppressErrors: true);
    gauth = gauth ?? await googleSignIn.signIn();
    Map<String, String> header = await gauth.authHeaders;
    var client = GoogleHttpClient(header);
    drive.DriveApi dvr = drive.DriveApi(client);
    drive.File fileToUpload = drive.File();
    fileToUpload.name = filename;
    drive.File response;
    fileToUpload.isAppAuthorized = true;
    fileToUpload.copyRequiresWriterPermission = false;
    try {
      response = await dvr.files.create(fileToUpload, uploadMedia: media);
    } catch (e) {
      return null;
    }
    print('1.Image Responce :: ${response?.toJson()}');
    return response?.id;
  } catch (e) {
    print('Error Upload Image :: $e');
    return null;
  }
}

class GoogleHttpClient extends IOClient {
  Map<String, String> _headers;
  GoogleHttpClient(this._headers) : super();

  @override
  Future<IOStreamedResponse> send(BaseRequest request) =>
      super.send(request..headers.addAll(_headers));

  @override
  Future<Response> head(Object url, {Map<String, String> headers}) =>
      super.head(url, headers: headers..addAll(_headers));
}
```

```
[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.22.1 at C:\Flutter Components\flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\anand\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\anand\AppData\Local\Android\Sdk
    • Java binary at: C:\Flutter Components\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 3.6)
    • Android Studio at C:\Flutter Components\Android Studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\anand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (4 available)
    • ASUS X00TD (mobile) • 192.168.43.35:5555 • android-arm64  • Android 9 (API 28)
    • Web Server (web)    • web-server         • web-javascript • Flutter Tools
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 86.0.622.38
```

**Comment by darshankawar** [comment] 2020-10-13 06:04
@anandsubbu007 
Please check out [this](https://www.c-sharpcorner.com/article/google-drive-integration-in-flutter-upload-download-list-files/) article and see if following the steps resolves your issue.
Thanks

**Comment by anandsubbu007** [comment] 2020-10-13 15:08
that is also not working.

but when i made that image file public it is loading in android

**Comment by darshankawar** [comment] 2020-10-14 06:26
@anandsubbu007 What do you mean by making the file public ?
Also, can you put your `Image.network` code in `try catch` and see what exception does it throw ?
Thanks.

**Comment by darshankawar** [comment] 2020-10-14 06:28
May be related to [25748](https://github.com/flutter/flutter/issues/25748)

**Comment by anandsubbu007** [comment] 2020-10-14 14:05
when i catch error it shows:
```
Exception: Invalid image data
```

when i made that uploaded image in my drive to public. image is loading in mobile.
![Uploading image.png…]()

**Comment by darshankawar** [comment] 2020-10-15 06:58
@anandsubbu007 
Since you are using `import 'package:googleapis/drive/v3.dart' as drive`, can you try with v2.dart and see if you get same error ?
Thanks.

**Comment by anandsubbu007** [comment] 2020-10-15 08:53
```
Future<Output> uploadImageToDrive({drive.Media media, String filename}) async {
  try {
    GoogleSignInAccount gauth = await googleSignIn.signInSilently();
    gauth = gauth ?? await googleSignIn.signIn();
    Map<String, String> header = await gauth.authHeaders;
    var client = GoogleHttpClient(header);
    drive.DriveApi dvr = drive.DriveApi(client);
    drive.File fileToUpload = drive.File();
    fileToUpload.originalFilename = filename;
    // fileToUpload.isAppAuthorized = true;
    drive.File response;
    fileToUpload.isAppAuthorized = true;
    response = await dvr.files
        .insert(fileToUpload, enforceSingleParent: true, uploadMedia: media);
    print('1.Image Responce :: ${response?.id}');
    return Output(
        error: 'Image Uploaded To Drive', issuccess: true, value: response?.id);
  } catch (e) {
    print('Error Upload Image :: $e');
    return Output(error: e.toString(), issuccess: false);
  }
```

```
Restarted application in 7,816ms.
W/DynamiteModule(18041): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(18041): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(18041): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/ConnectivityManager.CallbackHandler(18041): callback not found for CALLBACK_AVAILABLE message
I/flutter (18041): Exception: Invalid image data
[38;5;244mI/flutter (18041): #0      _futurize  (dart:ui/painting.dart:4856:5))[39;49m
[38;5;244mI/flutter (18041): #1      ImageDescriptor.encoded  (dart:ui/painting.dart:4724:12))[39;49m
[38;5;244mI/flutter (18041): #2      instantiateImageCodec  (dart:ui/painting.dart:1721:60))[39;49m
I/flutter (18041): <asynchronous suspension>
[38;5;244mI/flutter (18041): #3      PaintingBinding.instantiateImageCodec[39;49m 
 package:flutter/…/painting/binding.dart
[38;5;244mI/flutter (18041): #4      NetworkImage._loadAsync[39;49m 
 package:flutter/…/painting/_network_image_io.dart
I/flutter (18041): <asynchronous suspension>
[38;5;244mI/flutter (18041): #5      NetworkImage.load[39;49m 
 package:flutter/…/painting/_network_image_io.dart
[38;5;244mI/flutter (18041): #6      ImageProvider.resolveStreamForKey.<anonymous closure>[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (18041): #7      ImageCache.putIfAbsent[39;49m 
 package:flutter/…/painting/image_cache.dart
[38;5;244mI/flutter (18041): #8      ImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/painting/image_provider.dart
[38;5;244mI/flutter (18041): #9      ScrollAwareImageProvider.resolveStreamForKey[39;49m 
 package:flutter/…/widgets/scroll_aware_image_provider.dart
I/flutter (18041): #10     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provid
```


Still Same Responce

**Comment by darshankawar** [comment] 2020-10-16 05:23
@anandsubbu007 
Since you said it's working on web, can you provide the web logs using try catch block for same code block ?
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-06 10:27
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-06 10:27 UTC

**Comment by rvvarasdiya** [comment] 2021-02-16 19:33
Use SvgPicture.network.

it should be work.
