### ISSUE TITLE
`Clip.none` ignored during overscroll on Android 

### ISSUE THREAD

**Issue by cachapa** [flutter/flutter#133330] opened 2023-08-25 15:41 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a scrollable view that's larger than the screen bounds
2. Give the view some padding on the scroll direction
3. Configure the scrollable to use `clipBehavior: Clip.none`
4. Run it on Android, or simulate Android platform defaults

### Expected results

The view should overscroll (stretch) normally.

### Actual results

During the stretching overscroll effect, the bounds outside the scrollview disappear (are clipped) until the view is no longer being overscrolled.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

void main() {
  // Test this code in other platforms
  debugDefaultTargetPlatformOverride = TargetPlatform.android;
  runApp(const AppBarApp());
}

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(vertical: 100),
          child: SingleChildScrollView(
            clipBehavior: Clip.none,
            child: Column(
              children:
                  List.generate(20, (i) => ListTile(title: Text('Item $i'))),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Screencast from 2023-08-25 16-38-34.webm](https://github.com/flutter/flutter/assets/1006207/caa063ae-e07a-42ed-91b1-15fda784ec03)

</details>

### Logs

<details><summary>Logs</summary>

```console
No relevant logs
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.14.0-9.0.pre.93, on Fedora Linux 38 (Workstation Edition) 6.4.11-200.fc38.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-08-28 06:04
Thanks for filing the issue. I can see this on Android whilst it doesn't appear on iOS platform. Adding demo video with enabling Overlay guideline  in Devtools Widget Inspector to see the issue more clearly. 

Also, the issue is only reproducible on master channel. On stable 3.13.1, the issue doesn't happen. Marking this as a regression issue.

<details>
<summary>Demo</summary>

| master | stable |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/78c17be1-3f9c-43b2-9d2e-8856045b6021"/> | <video src="https://github.com/flutter/flutter/assets/104349824/b5ff96ea-5a6b-4632-8140-c26bf7db45e2"/>

</details> 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (23 hours ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-9.0.pre.115, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-9.0.pre.115 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6d22a11b62 (3 hours ago), 2023-08-27 19:57:26 -0400
    • Engine revision 0593c0455f
    • Dart version 3.2.0 (build 3.2.0-97.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Piinks** [comment] 2023-08-30 18:15
Looks related to https://github.com/flutter/flutter/issues/133445

**Comment by Piinks** [comment] 2023-08-30 20:03
@huycozy the examples in your videos are not the same. On stable it is using the GlowingOverscrollIndicator, not the StretchingOverscrollIndicator, which is the new default on the master channel.

**Comment by Piinks** [comment] 2023-08-30 21:18
This is caused by the SingleChildScrollView. Swapping it out for a ListView shows no issue. I am guessing the clipBehavior in SingleChildScrollView is not passed on to the Scrollable that then passes it on to the overscroll indicator. Looking at fixing this now.

**Closed** 2023-08-31 23:50 UTC
Labels: platform-android, framework, f: scrolling, has reproducible steps, P2, workaround available, team-framework, triaged-framework, found in release: 3.14

**Comment by huycozy** [comment] 2023-09-06 03:48
>the examples in your videos are not the same. On stable it is using the GlowingOverscrollIndicator, not the StretchingOverscrollIndicator, which is the new default on the master channel.

Oh, that's right. Thanks for clarifying this!
