### ISSUE TITLE
Disable console unknown logging output in Flutter 1.17

### ISSUE THREAD

**Issue by abdulmuaz97** [flutter/flutter#57035] opened 2020-05-12 18:17 UTC
### Disabling the console logging output in v1.17
Hi, I'm trying to disable the logging output from the flutter framework, back then in the version **1.12** was fine and only prints what's important, after updating to **1.17** it keeps printing system logging, tools, touch details, cursor movement..etc

**How can I disable those stuff?**
This is a simple app

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomeView(),
    );
  }
}

class HomeView extends StatelessWidget {
  const HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('Hello, World!'),
      ),
    );
  }
}
```

**Logging stuff**
And once I run first debug, the console printed out these

```
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Parameter format not correct -
√ Built build\app\outputs\apk\debug\app-debug.apk.
W/e.bit_simulato( 6189): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/e.bit_simulato( 6189): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/e.bit_simulato( 6189): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/e.bit_simulato( 6189): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
I/OpenGLRenderer( 6189): Initialized EGL, version 1.4
D/OpenGLRenderer( 6189): Swap behavior 1
D/HostConnection( 6189): HostConnection::get() New Host Connection established 0xdf5a2c10, tid 6367
D/HostConnection( 6189): HostConnection::get() New Host Connection established 0xe10213c0, tid 6347
D/HostConnection( 6189): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
W/OpenGLRenderer( 6189): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 6189): Swap behavior 0
D/eglCodecCommon( 6189): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6189): eglCreateContext: 0xde3d3300: maj 2 min 0 rcv 2
D/HostConnection( 6189): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/EGL_emulation( 6189): eglMakeCurrent: 0xde3d3300: ver 2 0 (tinfo 0xcc222890)
D/eglCodecCommon( 6189): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6189): eglCreateContext: 0xe10054e0: maj 2 min 0 rcv 2
D/HostConnection( 6189): createUnique: call
D/HostConnection( 6189): HostConnection::get() New Host Connection established 0xcc4d0a50, tid 6367
D/HostConnection( 6189): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
E/eglCodecCommon( 6189): GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/EGL_emulation( 6189): eglMakeCurrent: 0xe10054e0: ver 2 0 (tinfo 0xe10036e0)
I/Choreographer( 6189): Skipped 355 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 6189): eglMakeCurrent: 0xde3d3300: ver 2 0 (tinfo 0xcc222890)
I/OpenGLRenderer( 6189): Davey! duration=6237ms; Flags=1, IntendedVsync=1198435604290, Vsync=1204352270720, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1204363553000, AnimationStart=1204363742600, PerformTraversalsStart=1204363839400, DrawStart=1204457957200, SyncQueued=1204522248900, SyncStart=1204528215800, IssueDrawCommandsStart=1204532778700, SwapBuffers=1204590650000, FrameCompleted=1204678915900, DequeueBufferDuration=53271000, QueueBufferDuration=2935000,
D/EGL_emulation( 6189): eglMakeCurrent: 0xe10054e0: ver 2 0 (tinfo 0xe10036e0)
D/eglCodecCommon( 6189): setVertexArrayObject: set vao to 0 (0) 1 0
```

Any solutions?

**Comment by iapicca** [comment] 2020-05-13 08:02
Hi @abdulmuaz97 
are you experiencing this with [android studio ](https://stackoverflow.com/questions/55437643/flutter-disable-system-debug-messages-in-run-tab) or  vs code or  terminal  
or all the above?
Thank you

**Comment by abdulmuaz97** [comment] 2020-05-13 08:03
I'm currently using VS Code with its default console

**Comment by abdulmuaz97** [comment] 2020-05-13 08:09
Any ideas? @iapicca
Thank you

**Comment by iapicca** [comment] 2020-05-13 08:25
Hi @abdulmuaz97 
this is the output I get from `vscode` running your code
```bash
Launching lib/main.dart on Pixel 3a in debug mode...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
W/Gralloc3(19056): mapper 3.x is not supported
Application finished.
Exited (sigterm)
```
I'm not sure if the issue is with flutter or vs code,
could you please try to run your sample app from terminal,
(simple `flutter run`, not `flutter run --verbose`)

if the logs are "chatty" please provide that output, 
otherwise I'd recommend to
follow the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) and open an issue on the dedicated [github](https://github.com/Dart-Code/Dart-Code/issues)
Thank you

**Comment by egyleader** [comment] 2020-05-13 22:26
I've faced the same problem since flutter 1.7 I think 😥😥
all this arbitrary logs are useless and I don't know how to disable them to see only my app specific logs ? 

**using latest vs code version with flutter 1.17.0** 

`V/AudioManager(23356): getStreamMaxVolume  treamType: 3
V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
V/AudioManager(23356): getStreamMaxVolume  treamType: 3
V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
V/AudioManager(23356): getStreamMaxVolume  treamType: 3
V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
I/Ads     (23356): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("3F14AD86C92271CB3975C5B76E5B7957") to get test ads on this device.
V/AudioManager(23356): getMode...
E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
V/AudioManager(23356): isMusicActive...
E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
V/AudioManager(23356): isSpeakerphoneOn: false
V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
V/AudioManager(23356): getRingerMode...
V/AudioManager(23356): getStreamVolume  streamType: 2 volume: 0
W/Ads     (23356): Not retrying to fetch app settings
E/flutter (23356): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): GameControl#784f1(lifecycle state: defunct)
E/flutter (23356): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (23356): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (23356): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (23356): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1197
E/flutter (23356): #1      State.setState 
package:flutter/…/widgets/framework.dart:1232
E/flutter (23356): #2      GameControl.down 
package:AtariZaman/gamer/gamer.dart:193
E/flutter (23356): #3      GameControl._autoFall.<anonymous closure> 
package:AtariZaman/gamer/gamer.dart:285
E/flutter (23356): #4      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (23356): #5      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (23356): #6      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (23356): #7      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1024:26)
E/flutter (23356): #8      _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (23356): #9      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (23356): #10     _CustomZone.bindUnaryCallback.<anonymous closure>  (dart:async/zone.dart:1008:26)
E/flutter (23356): #11     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (23356): #12     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (23356): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23356):
E/        (23356): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
V/AudioManager(23356): getStreamMaxVolume  treamType: 3
V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
Application finished.
Exited (sigterm)
`

**Comment by iapicca** [comment] 2020-06-05 13:30
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 13:30 UTC
Labels: in triage, waiting for customer response

**Comment by abdulmuaz97** [comment] 2020-06-18 21:08
Hi @iapicca 
Thanks for the response, I was literally busy due to the last events around.
And we still facing the same issue that I described before, it'e actually not a big problem but the thing is that the console was not showing me these strange outputs in version **1.12.13** until the last **Flutter** update.
The console was only shows me what I print in the code, but now it keeps printing some unwanted outputs.

```
I/e.ecommerce_ap(12105): Starting profile saver IsSaveProfileNow end.
V/InputMethodManager(12105): Reporting focus gain, without startInput
W/Settings(12105): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(12105): User setup is finished.
V/InputMethodManager(12105): Reporting focus gain, without startInput
W/HiTouch_PressGestureDetector(12105): Touch pointer move a lot. The moving distance of X is:6.9935246, limit is:51The moving distance of Y is:69.9693, limit is:51
D/ZrHung.AppEyeUiProbe(12105): stop checker.
W/libEGL  (12105): EGLNativeWindowType 0x78f3325010 disconnect failed
I/SurfaceView(12105): delay destroy surface control
W/libEGL  (12105): EGLNativeWindowType 0x78f3323010 disconnect failed
I/SurfaceView(12105): need destroy surface control
D/ViewRootImpl[MainActivity](12105): surface should not be released
D/ZrHung.AppEyeUiProbe(12105): Current Activity:false
D/ZrHung.AppEyeUiProbe(12105): not watching, wait.
E/        (12105): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
Lost connection to device.
Exited (sigterm)
```
This is the output (VS Code Debug Console Output, **NOT** Terminal Output) of the newest app I created few minutes ago using **Flutter 1.17.1** and running on a real device (Android 9) through USB cable.
Hope these information help you to figure out the problem here.

Best Regards Dear

**Comment by bilalbaz1** [comment] 2020-07-30 16:33
> Çarpıntı 1.7'den beri aynı problemle karşılaştım sanırım 😥😥
> tüm bu keyfi günlükler işe yaramaz ve bunları yalnızca uygulamaya özgü günlüklerimi görmek için nasıl devre dışı bırakacağımı bilmiyorum?
> 
> **flutter 1.17.0 ile en son vs kod sürümünü kullanma**
> 
> ```
> V/AudioManager(23356): getStreamMaxVolume  treamType: 3
> V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
> V/AudioManager(23356): getStreamMaxVolume  treamType: 3
> V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
> V/AudioManager(23356): getStreamMaxVolume  treamType: 3
> V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
> I/Ads     (23356): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("3F14AD86C92271CB3975C5B76E5B7957") to get test ads on this device.
> V/AudioManager(23356): getMode...
> E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
> E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
> V/AudioManager(23356): isMusicActive...
> E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
> E/IPCThreadState(23356): More than IPC_START_MONITOR_LEVEL, start Monitor
> V/AudioManager(23356): isSpeakerphoneOn: false
> V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
> V/AudioManager(23356): getRingerMode...
> V/AudioManager(23356): getStreamVolume  streamType: 2 volume: 0
> W/Ads     (23356): Not retrying to fetch app settings
> E/flutter (23356): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): GameControl#784f1(lifecycle state: defunct)
> E/flutter (23356): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
> E/flutter (23356): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
> E/flutter (23356): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
> E/flutter (23356): #0      State.setState.<anonymous closure> 
> package:flutter/…/widgets/framework.dart:1197
> E/flutter (23356): #1      State.setState 
> package:flutter/…/widgets/framework.dart:1232
> E/flutter (23356): #2      GameControl.down 
> package:AtariZaman/gamer/gamer.dart:193
> E/flutter (23356): #3      GameControl._autoFall.<anonymous closure> 
> package:AtariZaman/gamer/gamer.dart:285
> E/flutter (23356): #4      _rootRunUnary  (dart:async/zone.dart:1192:38)
> E/flutter (23356): #5      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
> E/flutter (23356): #6      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
> E/flutter (23356): #7      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1024:26)
> E/flutter (23356): #8      _rootRunUnary  (dart:async/zone.dart:1196:13)
> E/flutter (23356): #9      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
> E/flutter (23356): #10     _CustomZone.bindUnaryCallback.<anonymous closure>  (dart:async/zone.dart:1008:26)
> E/flutter (23356): #11     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:398:19)
> E/flutter (23356): #12     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:429:5)
> E/flutter (23356): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
> E/flutter (23356):
> E/        (23356): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
> V/AudioManager(23356): getStreamMaxVolume  treamType: 3
> V/AudioManager(23356): getStreamVolume  streamType: 3 volume: 0
> Application finished.
> Exited (sigterm)
> ```

**You may encounter this problem if you are not using async in a function that is async.**

**Comment by TejasDhanda-L11** [comment] 2021-07-03 15:21
I used flutter run --release and it didn't showed the extra stuff (touches and other stuff)
