### ISSUE TITLE
[Android] Early crash (captured via Crashlytics)

### ISSUE THREAD

**Issue by maysamsh** [flutter/flutter#96754] opened 2022-01-17 20:17 UTC
Apparently on Android 9 some of user experience an early crash. I could not reproduce it on my own phone but it's the log from Crashlytics:

<details>
  <summary>Logs</summary>

```
 Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/base.apk", zip file "/data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.en.apk", zip file "/data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.mdpi.apk", zip file "/data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/lib/x86, /data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/base.apk!/lib/x86, /data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.en.apk!/lib/x86, /data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.mdpi.apk!/lib/x86, /data/app/[REDACTED]-zUog5qSB1t8QfmZuf41IsA==/split_config.x86.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
java.lang.System.loadLibrary (System.java:1669)
io.flutter.embedding.engine.FlutterJNI.loadLibrary (FlutterJNI.java:2)
io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java:4)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764) 
```

This line is highlighted in blue:
`io.flutter.embedding.engine.FlutterJNI.loadLibrary (FlutterJNI.java:2)`

This is my `settings.gradle` :
```
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

</details>
How can I read this log? where should I look for a clue? this is all I have

**Comment by darshankawar** [comment] 2022-01-18 09:47
Looking at the error log, this seems to be similar / duplicate of https://github.com/flutter/flutter/issues/83596. Please follow-up in it for further updates.
Closing.

**Closed by darshankawar** 2022-01-18 09:47 UTC
Labels: in triage
