### ISSUE TITLE
[google_maps_flutter] sharedmem_gpuobj_alloc & gsl_memory_alloc_pure

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#72186] opened 2020-12-12 07:32 UTC
plugin V: 1.0.6
flutter V: 1.22.5
dev system: windows 10
device: realme 5
android: 10

i use two fingers to just rotate the map and see the effect of flat markers and move the maps using one finger ,etc ..

and in this case above , if i move the map any direction for some time i get the below error and the device lose the connection ..

it happens every time i do this from 3 months ago ..

Log:
```
[ +506 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +68 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[ +104 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +76 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +9 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[ +122 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +59 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +68 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +59 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +76 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +29 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +56 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +57 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +66 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +6 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[ +149 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +15 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +62 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +69 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +71 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[ +113 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +52 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +66 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +65 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +54 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[ +135 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +60 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +7 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[ +140 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +78 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +99 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +66 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +58 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +75 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +24 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +85 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +77 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +86 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +63 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +60 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +18 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +54 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +65 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +59 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +57 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +61 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +5 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +58 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +64 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +60 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +58 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +6 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +63 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +57 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +71 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +81 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +53 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +63 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +52 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +64 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +65 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +66 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +59 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +63 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +6 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +61 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +75 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +55 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[ +115 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +64 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +6 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +62 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +58 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[ +121 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +57 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +61 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +63 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[   +6 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +58 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +64 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[   +6 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[  +67 ms] W/Adreno-GSL(28724): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap
failed errno 12 Out of memory
[  +58 ms] E/Adreno-GSL(28724): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR:
kgsl_sharedmem_alloc ioctl failed.
[ +162 ms] Service protocol connection closed.
[  +87 ms] Lost connection to device.
[  +23 ms] executing: C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
192.168.1.3:55555 forward --list
[ +386 ms] Exit code 0 from: C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
192.168.1.3:55555 forward --list
[  +10 ms] 192.168.1.3:55555 tcp:52203 tcp:42267
[  +20 ms] executing: C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
192.168.1.3:55555 forward --remove tcp:52203
[  +97 ms] Error writing "lib/main.dart.swap.dill" to DevFS: SocketException: Write failed (OS
Error: An established connection was aborted by the software in your host machine.
           , errno = 10053), address = 127.0.0.1, port = 53405
[  +67 ms] trying again in a few - 9 more attempts left
[ +289 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/PKGNAME/code_cache/imeQYAYFV/APPNAME/)
[ +317 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Futurenot completed
[  +82 ms] executing: C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
192.168.1.3:55555 forward --list
[ +686 ms] Exit code 0 from: C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools\adb.exe -s   
192.168.1.3:55555 forward --list
[ +250 ms] "flutter run" took ١٬٧١٢٬٢٤٤ms.
[ +500 ms] Running shutdown hooks
[ +133 ms] Shutdown hook priority 4
[ +194 ms] Shutdown hooks complete
[ +324 ms] Error writing "lib/main.dart.swap.dill" to DevFS: SocketException: OS Error: The    
remote computer refused the network connection.
                    , errno = 1225, address = 127.0.0.1, port = 53414
[ +327 ms] trying again in a few - 8 more attempts left
[ +216 ms] exiting with code 0
```

**Comment by iapicca** [comment] 2020-12-12 09:02
@imeDevelopers 
can you provide your `flutter doctor -v` and a **_minimal reproducible code sample_**

**Comment by darshankawar** [comment] 2020-12-14 07:27
@imeDevelopers 
Please provide above requested details to better address your issue.

**Comment by imeDevelopers** [comment] 2020-12-14 20:48
@darshankawar 
@iapicca 
i have no time.

**Comment by darshankawar** [comment] 2020-12-15 06:39
@imeDevelopers 
Without a reproducible use case, it's tough to identify root-cause for the issue you are facing and we may have to close this since it's not actionable without required details.

**Comment by pedromassangocode** [comment] 2021-01-06 12:29
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:29 UTC
Labels: in triage, waiting for customer response
