### ISSUE TITLE
 W/Gralloc3: mapper 3.x is not supported. Access denied finding property "vendor.gralloc.disable_ahardware_buffer"

### ISSUE THREAD

**Issue by fatherchill** [flutter/flutter#57185] opened 2020-05-14 03:39 UTC
Re: https://github.com/flutter/flutter/issues/50405#issuecomment-595308935

Have steps to reproduce!

Encounter this error on Logcat when running flutter app on Pixel 3.
`2020-05-13 23:27:43.874 15995-16046/? W/Gralloc3: mapper 3.x is not supported
2020-05-13 23:27:43.877 15995-16046/? E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
`

## Steps to Reproduce

1. Create a new flutter project in Android Studio.
2. Change nothing on the Demo Counter App.
3. Run app on physical Pixel 3 (does not occur on emulator). See logcat.

<details>
  <summary>Logs</summary>

```
2020-05-13 23:19:40.028 14822-14822/? I/erchill.texas4: Late-enabling -Xcheck:jni
2020-05-13 23:19:40.046 14822-14822/? E/erchill.texas4: Unknown bits set in runtime_flags: 0x8000
2020-05-13 23:19:40.170 14822-14855/com.fatherchill.texas42 I/ResourceExtractor: Resource version mismatch res_timestamp-1-1589426379312
2020-05-13 23:19:40.361 14822-14855/com.fatherchill.texas42 I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2020-05-13 23:19:40.362 14822-14855/com.fatherchill.texas42 I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2020-05-13 23:19:40.394 14822-14855/com.fatherchill.texas42 I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
2020-05-13 23:19:40.404 14822-14822/com.fatherchill.texas42 I/Adreno: QUALCOMM build                   : 4a00b69, I4e7e888065
    Build Date                       : 04/09/19
    OpenGL ES Shader Compiler Version: EV031.26.06.00
    Local Branch                     : mybranche95a5ea3-cf05-f19a-a0e7-5cb90179c3d8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-05-13 23:19:40.404 14822-14822/com.fatherchill.texas42 I/Adreno: Build Config                     : S P 8.0.6 AArch64
2020-05-13 23:19:40.407 14822-14822/com.fatherchill.texas42 I/Adreno: PFP: 0x016ee183, ME: 0x00000000
2020-05-13 23:19:40.538 14822-14822/com.fatherchill.texas42 W/erchill.texas4: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
2020-05-13 23:19:40.538 14822-14822/com.fatherchill.texas42 W/erchill.texas4: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
2020-05-13 23:19:40.538 14822-14822/com.fatherchill.texas42 W/erchill.texas4: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
2020-05-13 23:19:40.538 14822-14822/com.fatherchill.texas42 W/erchill.texas4: Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
2020-05-13 23:19:40.542 14822-14877/com.fatherchill.texas42 I/flutter: Observatory listening on http://127.0.0.1:39287/VIjMg0oxags=/
2020-05-13 23:19:40.701 14822-14856/com.fatherchill.texas42 W/Gralloc3: mapper 3.x is not supported
2020-05-13 23:19:40.701 14822-14822/com.fatherchill.texas42 W/RenderThread: type=1400 audit(0.0:5784): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20109 scontext=u:r:untrusted_app_27:s0:c148,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2020-05-13 23:19:40.703 14822-14856/com.fatherchill.texas42 E/libc: Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
```

```
```

(Currently on stable channel, but have encountered error on dev 1.19.xx as well)
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/fatherchill/Dev/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /home/fatherchill/Android/Sdk
    • Platform android-29, build-tools 30.0.0-rc4
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Pixel 3 • 8CFX1NYJX • android-arm64 • Android 10 (API 29)

```

</details>

**Comment by TahaTesser** [comment] 2020-05-14 10:46
Mentioned issue is reopened and labeled
Closing as duplicate of https://github.com/flutter/flutter/issues/50405#issuecomment-595308935

**Closed by TahaTesser** 2020-05-14 10:46 UTC

**Comment by fatherchill** [comment] 2020-05-16 03:12
@TahaTesser,  @VladyslavBondarenko asked anyone having this issue to open a new issue with logs and steps to reproduce. #50405 doesn't have steps to reproduce.  Should I put my logs and steps to reproduce in #50405?

**Comment by VladyslavBondarenko** [comment] 2020-05-18 11:39
@fatherchill yes, add it there
