### ISSUE TITLE
Timeout while attempting to retrieve Uri for Observatory 

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10125] opened 2017-05-16 21:25 UTC
For about a week it becomes more and more difficult to launch my app using IOS Simulator.

When running the app it may freeze for some minutes before launching a timeout and sometimes I need to restart the process many times before a successful start.

I edit to add this seems to only happen when launching from Intellij, from the Flutter run in the terminal it's always a quick startup.

## Steps to Reproduce

Just launch app from Intellij on IOs simulator

## Logs

Error waiting for a debug connection: Exception: Timeout while attempting to retrieve Uri for Observatory
Error launching application on iPhone SE.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/robbie/Install/flutter
    • Framework revision dc4ca8db83 (5 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/robbie/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] WebStorm (version 2016.3.4)
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B84FB97F-1BAE-48EF-9313-99BE7E7F92D2 • ios • iOS 10.3 (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment] 2017-05-16 21:36
I think @tvolkert was looking at something which might have been related here.

**Comment by tvolkert** [comment] 2017-05-16 21:38
This is likely fixed at tip-of-tree in the master branch (https://github.com/flutter/flutter/pull/10092).  Please let us know.

**Comment by Solido** [comment] 2017-05-16 22:01
`Git pull `
`flutter channel master` 

Still freeeeeze and look like I broke my favorite toy. 
It really only happen from intellij, never from flutter run on terminal.

`CoreSimulatorBridge: Requesting installation of file:///Users/robbie/Documents/PRJCTS/SustainR/sustainr-sky/build/ios/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.sustainrSky";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/robbie/Library/Developer/CoreSimulator/Devices/B84FB97F-1BAE-48EF-9313-99BE7E7F92D2/data";
	}
	state->old_bundle: /Users/robbie/Library/Developer/CoreSimulator/Devices/B84FB97F-1BAE-48EF-9313-99BE7E7F92D2/data/Containers/Bundle/Application/9E28F045-EDA4-4BC3-ABA3-63B49CB9DA18/Runner.app
	state->new_bundle: /Users/robbie/Documents/PRJCTS/SustainR/sustainr-sky/build/ios/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/robbie/Library/Developer/CoreSimulator/Devices/B84FB97F-1BAE-48EF-9313-99BE7E7F92D2/data/Library/Caches/com.apple.mobile.installd.staging/temp.aqHiIS/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/robbie/Library/Developer/CoreSimulator/Devices/B84FB97F-1BAE-48EF-9313-99BE7E7F92D2/data/Library/Caches/com.apple.mobile.installd.staging/temp.aqHiIS/extracted
Error waiting for a debug connection: Exception: Timeout while attempting to retrieve URL for Observatory
Error launching application on iPhone SE.`

**Comment by Solido** [comment] 2017-05-16 22:03
✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/robbie/Install/flutter
    • Framework revision 63cfe1e30d (46 minutes ago), 2017-05-16 14:17:41 -0700
    • Engine revision 6fef702cfa
    • Tools Dart version 1.23.0-dev.11.11

**Comment by Solido** [comment] 2017-05-16 22:07
Launching from intellij terminal should help me to continue working.
Let me know if I can help.
Thank you !

**Comment by tvolkert** [comment] 2017-05-16 22:26
@pq can you try to repro and take a look?

**Comment by pq** [comment] 2017-05-16 23:21
Sorry for the inconvenience @Solido!

I notice that you're on an older version of the plugin:

> Flutter plugin version 0.1.11.1

Can you try updating?  The latest is [`13.1`](https://plugins.jetbrains.com/plugin/9212-flutter/update/34818).

(If you can't maybe we're hitting a WebStorm incompatibility issue; in that case cc @devoncarew for thoughts.)

**Comment by Solido** [comment] 2017-05-16 23:34
That's a trick because I got Webstorm installed but I'm working with Intellij java with Flutter plugin and it's said it's up to date to 13.1.
Note it's still happen on terminal much just from time to time.
It's kinda 'painful' to loose time but it's OK because it's Alpha ;)

**Comment by pq** [comment] 2017-05-17 13:49
Interesting.  Thanks for the follow-up.

> Note it's still happen on terminal much just from time to time.

@tvolkert : are we seeing intermittent failures on the CLI too?

cc @skybrian who may have thoughts.

**Comment by tvolkert** [comment] 2017-05-17 14:40
> are we seeing intermittent failures on the CLI too?

Nope, we haven't had any new reports of it happening on the CLI, and the reporters of the old bugs confirmed that it's fixed for them.

**Comment by Solido** [comment] 2017-05-17 14:59
So If I'm the only case I should have missed smth ! 
It's OK for me to work on the console now and learn new commands. 
Will wait for the next update and see if problem persist or others complain.
Thank you.

**Comment by tvolkert** [comment] 2017-05-19 06:13
I actually just had this happen to me at the CLI (OSX, simulator, debug mode), so you're not the only one!  The app seemed to launch and then immediately close.

**Comment by tvolkert** [comment] 2017-05-19 07:22
In my case, `simctl` just hangs trying to see if the app is even installed (which it's not).  Trying to run in Xcode makes Xcode hang!  Had to force-quit Xcode...  after quitting and relaunching Simulator, everything worked...

**Comment by sethladd** [comment] 2017-05-19 12:57
Was happening on the codelabs machines, too. Quitting and restarting
simulate fixed it.

**Comment by pq** [comment] 2017-05-19 13:19
@mit-mit: we should document this as a known issue?  Or @sethladd, is the something comparable to where we document [known plugin issues](https://github.com/flutter/flutter-intellij#known-issues) for Flutter proper?

**Comment by mravn-google** [comment] 2017-05-19 13:44
https://github.com/flutter/flutter/issues/10201 seems similar, but happens with Android.

**Comment by pedia** [comment] 2017-05-30 15:53
failed me too.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-HK, channel master)
    • Flutter at /Users/odd/wa/flutter/flutter
    • Framework revision d14bb2cdfc (4 hours ago), 2017-05-30 13:28:30 +0200
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/odd/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/odd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    ✗ libimobiledevice is incompatible with the installed Xcode version. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    •  • ff46916473d277e0cd5b34e33fca53b952135b0f • ios • iOS  ()
```

**Comment by eseidelGoogle** [comment] 2017-05-30 16:27
@pedia looks like `flutter doctor` is reporting a problem with libimobiledevice which is likely related to your failure?

**Comment by skybrian** [comment] 2017-05-30 19:13
I wonder if we can we get "flutter run" to report the same error as "flutter doctor"?

**Comment by Hixie** [comment] 2017-05-30 20:56
@cbracken Any chance you can look at this? We think it may also be the cause of the especially flaky tests on devicelab (the ones we've commented out). See also https://github.com/flutter/flutter/issues/10228.

**Comment by cbracken** [comment] 2017-05-30 21:06
Can do - do we have any verbose logs (e.g., from devicelab machines)?

**Comment by pedia** [comment] 2017-06-03 04:32
@eseidelGoogle  The failure gone, after fix the problem.

**Comment by wlekin** [comment] 2017-06-03 19:09
I have the same problem, but when I changed the device from iphone se ( default simulator ) to iphone 7, problem is gone.

**Comment by eseidelGoogle** [comment] 2017-06-03 23:20
@wlekin I suspect that it doesn't have to do with *changing* the device, but rather moving to a new device image which does not have any version of your app installed.  My current theory (and @cbracken would know best) is that our installation process (via `ios-deploy`) doesn't work reliably when a version of your app is already installed.

**Comment by Hixie** [comment] 2017-06-06 20:50
This may be a dupe of https://github.com/flutter/flutter/issues/10228.

**Comment by DanTup** [comment] 2017-07-14 15:39
I've had reports about this in Dart Code too:

https://github.com/Dart-Code/Dart-Code/issues/358

**Comment by cbracken** [comment] 2017-07-17 20:02
@DanTup I suspect that's a separate (iOS 11-specific) issue. #10602

**Comment by cbracken** [comment] 2017-08-30 21:41
@DanTup #10602 is now resolved. I've updated #358 with details as well.

**Closed** 2018-09-26 14:53 UTC
Labels: severe: regression, team: flakes, tool, ⌺‬ platform-ios
