### ISSUE TITLE
PathProvider.getApplicationDocumentsDirectory always return different Documents Directory on real device IOS

### ISSUE THREAD

**Issue by faspadaro** [flutter/flutter#23957] opened 2018-11-05 21:27 UTC
**Steps to Reproduce**
Run the following app on ios, observe `print(appDir.path)` and then restart application and observe `appDir.path` again . 
You will notice that `getApplicationDocumentsDirectory` always return different Documents Directory.
```dart
    import 'package:flutter/material.dart';
    import 'dart:async';
    import 'dart:io';
    import 'package:path_provider/path_provider.dart';

    void main() => runApp(new MyApp());

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
          title: 'Flutter Demo',
          theme: new ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: new FlutterDemo(),
        );
      }
    }


    class FlutterDemo extends StatefulWidget {
      FlutterDemo({Key key}) : super(key: key);

      @override
      _FlutterDemoState createState() => new _FlutterDemoState();
    }

    class _FlutterDemoState extends State<FlutterDemo> {
      Future getDir() async {
        Directory appDir = await getApplicationDocumentsDirectory();
        print(appDir.path);
      }

      @override
      void initState() {
        getDir();
        super.initState();
      }
      @override
      Widget build(BuildContext context) {
         return new Scaffold(
            appBar: new AppBar(
              title: new Text('Flutter Demo'),
            ),
            body: new Column(children: [
            ]));
       }
    }
```

**Logs**
```
flutter: /var/mobile/Containers/Data/Application/8A4BEDFC-FD32-4783-8468-03CCD8F83AA3/Documents
flutter:  /var/mobile/Containers/Data/Application/28ECEAF4-E764-4368-A79E-D5E5C15CD3C6/Documents
 flutter: /var/mobile/Containers/Data/Application/1BDF398C-C0F1-43DE-B977-EA4ECA27B6A0/Documents
```

**Flutter doctor**
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale it-IT)
    • Flutter version 0.9.4 at /Users/fabio/FLutter/flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.0


[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[✓] Connected devices (1 available)
    • iPhone XXXXXX
```

**Comment by zoechi** [comment] 2018-11-08 06:32
How do you start the App? Did you install it and then start from there or did you start it from IDE or `flutter run`?

**Comment by zoechi** [comment] 2018-12-11 15:17
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by zoechi** [comment] 2019-01-17 06:49
Can you reproduce with a release build and a real device
with `flutter build ios --release; flutter install` after 4. ?

**Comment by dubemarcantoine** [comment] 2019-01-17 13:00
Hi, thanks for the help and the quick response, the paths are now the same by using the 2 commands!

However, is there a reason why it does not work while in development/debug mode as it works fine in the simulators?

**Comment by mcplectrum** [comment] 2019-02-05 21:34
That is normal iOS behaviour since iOS 8. As a developer you have to recreate the url with getApplicationDocumentsDirectory() every time you relaunch the app and should not save the absolute path. 
getApplicationDocumentsDirectory() internally uses `NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)` 

Please have a look at https://flutter.io/docs/cookbook/persistence/reading-writing-files. Only the relative path after getApplicationDocumentsDirectory() is important for developing.

**Comment by kangwang1988** [comment] 2019-02-07 14:27
I believe it is a feature(ios design).
After restart, the absolute directory will change but the folder structure and and relative paths will remain.

**Closed by kangwang1988** 2019-02-07 14:27 UTC
Labels: tool, waiting for customer response, ⌺‬ platform-ios, ▣ platform-android

**Comment by TristanWYL** [comment] 2019-08-23 03:45
@mcplectrum I understand what you mentioned [here](https://github.com/flutter/flutter/issues/23957#issuecomment-460812527), but I cannot have access to the document directory after executing `getApplicationDocumentsDirectory()` every time I updated the ios APP from Apple Store, even though this function did work well after each normal launch. So my point is **why** I cannot have access to the document directory after each APP update.

**Comment by arutkayb** [comment] 2020-04-19 14:55
Keeping the relative path to the app documents directory and when there is a need to use the file itself, merging the relative path to recently called app documents directory and then using that absolute path is the proper way.

static Future<String> savePickedImageToAppFolder(File image) async {
    final String path = _applicationDocumentsDirectory;
    String relativePath = '/' +DateTime.now().millisecondsSinceEpoch.toString()+ Path.extension(image.path);

    String newPath = '$path' + relativePath;

    File res =  await image.copy(newPath);

    return res != null && res.existsSync() ? relativePath : null;
  }

  static String getDocumentsPathByRelativePath(String relativePath){
    return relativePath != null && relativePath.isNotEmpty ? _applicationDocumentsDirectory + relativePath : null;
  }
