### ISSUE TITLE
Path.combine is extremely slow

### ISSUE THREAD

**Issue by djphoenix** [flutter/flutter#49972] opened 2020-02-02 13:39 UTC
## Details

I'm writing an [Gerber format](https://www.ucamco.com/files/downloads/file/81/The_Gerber_File_Format_specification.pdf?00d1c5cca037edf37931d899f419e8ab) parser and viewer. While generating final Path, I reach a problem when using Path.combine to join/clip paths.

I rewrote part of [example file](https://www.ucamco.com/files/downloads/file/210/gerber_file_format_examples%2020181113.zip?00d1c5cca037edf37931d899f419e8ab) (sample_macro.gbr) using Path operations to simplify demo code. You can see resulting code in [gist](https://gist.github.com/djphoenix/775d4bd11e2c71501d2d27abbf713ee1).

Resulting output on my setup (macOS):
```
flutter: path init took 0:00:00.003862
flutter: path combine took 0:00:26.861441
```

My iPhone X reaching almost same results.

**Target Platform:** macOS
**Target OS version/browser:** 10.15.2
**Devices:** MacBook Air 13" 2017, 1.8GHz Core i5

## Logs

```
[✓] Flutter (Channel master, v1.14.7-pre.83, on Mac OS X 10.15.2 19C57, locale ru-RU)
    • Flutter version 1.14.7-pre.83 at /Volumes/JetDrive/dev/flutter/sdk/flutter
    • Framework revision e10df3c1a6 (34 часа назад), 2020-02-01 11:23:01 +0800
    • Engine revision e625e174c5
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/JetDrive/.android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Volumes/JetDrive/.android/sdk
    • Java binary at: /Volumes/JetDrive/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Volumes/JetDrive/Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (4 available)
    • PhoeniX iPhone X • xxx                                      • ios            • iOS 13.3
    • macOS            • macOS                                    • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome           • chrome                                   • web-javascript • Google Chrome 79.0.3945.130
    • Web Server       • web-server                               • web-javascript • Flutter Tools
```

**Comment by dnfield** [comment] 2020-02-02 20:03
You're doing a lot of expensive work in there.

I don't think that many path combine operations would be expected to be very fast.

Have you checked what the performance is like in a skia fiddle using comparable code in C++?

**Comment by djphoenix** [comment] 2020-02-02 22:24
> a lot of expensive work in there

That's how Gerber works. I can't limit user-generated files to keep simpler. I think about offloading work to background thread, but Path_op is unavailable from Isolates (point me if I'm wrong).

> Have you checked what the performance is like in a skia fiddle using comparable code in C++?

Now I wasn't, maybe tomorrow.

**Comment by dnfield** [comment] 2020-02-02 22:42
No, you cannot access Path APIs on a background isolate.  

I strongly suspect this is just a lot of work to do and it's not a bug - it's just not cheap.

**Comment by djphoenix** [comment] 2020-02-02 22:49
I strongly not agree, because many viewers that I've test generates any-scale (I assume vector) preview within 0.1-2 seconds. I can accept that they're strongly optimized for specific scenarios, but 30+ seconds looks very, very poor. I think 1-5s is acceptable limit, but if it's doesn't lock main thread. Is there any reason to block UI even if Path.combine called via e.g. Future? Can I move it somewhere from UI thread?

**Comment by dnfield** [comment] 2020-02-02 22:54
Path.combine isn't currently exposed as an asynchronous call, but maybe we could come up with a way to do that.

**Comment by djphoenix** [comment] 2020-02-02 23:21
Async combining will be awesome, but the key is in average performance of Path.combine. I was seen huge Sk* work in native iOS profiler, and probably have a point to bottleneck. I will return later with more details.

**Comment by chinmaygarde** [comment] 2020-02-10 19:57
There doesn't appear to be a specific ask here for the Skia team. Removing label.

**Comment by darshankawar** [comment] 2020-12-03 11:40
@djphoenix 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, can you provide a minimal complete reproducible code sample ?

**Comment by pedromassangocode** [comment] 2021-01-06 12:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:16 UTC
Labels: P4, engine, waiting for customer response
