### ISSUE TITLE
Targeting iOS 11 (Flutter default minimum) built with Xcode 15 crashes `EXC_BAD_ACCESS` when using the `Networking` framework

### ISSUE THREAD

**Issue by JacoFourie** [flutter/flutter#136060] opened 2023-10-06 06:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Compile my add and try to run it on any iOS device with iOS less than 17

### Expected results

Should still run on all devices

### Actual results

The app will just close and not run. The version compiled on the previous Xcode runs on all iOS versions

### Code sample

I can not sare my code on a public forum but here you see when doing a flutter run it compiles and sends the app to the device. But will not run and does not give any error

```console
[        ] Executing commands in
'/tmp/11B6DEEF-BC32-4701-8E4A-2B4EC6C4D636/fruitstrap-lldb-prep-cmds-4781749bcc830a01bf3326c466d1d86cea0bc844'.
[        ] (lldb)     platform select remote-'ios' --sysroot '/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7
(16H81)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]    Sysroot: /Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols
[        ]   SDK Path: "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols"
[        ] (lldb)     target create "/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos/Runner.app"
[+4832 ms] Current executable set to '/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/F29C2CCD-BFBC-49C1-8363-8B854E50BB53/Runner.app"
[ +109 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:64790"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7
(16H81)/Symbols/usr" /System "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols/System"
"/private/var/containers/Bundle/Application/F29C2CCD-BFBC-49C1-8363-8B854E50BB53"
"/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos"
"/var/containers/Bundle/Application/F29C2CCD-BFBC-49C1-8363-8B854E50BB53"
"/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos" /Developer "/Users/jacofourie/Library/Developer/Xcode/iOS
DeviceSupport/12.5.7 (16H81)/Symbols/Developer"
[  +26 ms] (lldb)     command script import
"/tmp/11B6DEEF-BC32-4701-8E4A-2B4EC6C4D636/fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.py"
[   +2 ms] (lldb)     command script add -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.safequit_command safequit
[        ] (lldb)     connect
[  +26 ms] (lldb)     run
[ +300 ms] success
[        ] (lldb)     safequit
[ +126 ms] Process 421 detached
[  +32 ms] Application launched on the device. Waiting for Dart VM Service url.
[ +721 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
[+29288 ms] The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...
[+85979 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[+2892 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
q 
quit
^C%                                                                                                                                       jacofourie@Jacos-Mac-Mini-M2 smh % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-ZA)
    • Flutter version 3.13.6 on channel stable at /Users/jacofourie/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jacofourie/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Jaco’s iPhone 14 (mobile)    • 00008110-00110C9E1105401E                • ios            • iOS 17.0.3 21A360
    • Developmet iphone 6 (mobile) • 4781749bcc830a01bf3326c466d1d86cea0bc844 • ios            • iOS 12.5.7 16H81
    • macOS (desktop)              • macos                                    • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-10-06 10:44
I run a minimal sample app on my device `iPhone 7, iOS 15.7.9` but it can run normally. I'm using `Xcode 15.0` and macOS 14.0. 

Am I correct if you have this issue on iPhone 6, iOS 12.5.7? (from your flutter doctor output)

Please confirm if there is a similar issue on a newly created Flutter project. If it only occurs on your project, please share the complete output of `flutter run -v`.

**Comment by JacoFourie** [comment] 2023-10-06 14:32
If I create a new starter app it will run on the other iOS versions yes. But not my app. I have other devices that install the app via Testfligth that have the same issue. I have my own iPhone 14 with 
iOS 17 that works fine and then a development iPhone 6 with iOS 12 that does not. Before I upgraded it worked all over. I can add you as a Testflight tester if you need to run the app to see what it does

Here is the flutter run - v output of the iPhone 6 in a file as it is too long to post here.
[iPhone6.docx](https://github.com/flutter/flutter/files/12832230/iPhone6.docx)

**Comment by JacoFourie** [comment] 2023-10-06 14:40
And here is the output of the same app on the iPhone 14 with iOS 17 that works.
[iPhone14.docx](https://github.com/flutter/flutter/files/12832298/iPhone14.docx)

**Comment by mcagrigoktas** [comment] 2023-10-07 12:47
I have the same problem on my devices.

**Comment by huycozy** [comment] 2023-10-09 05:27
<details>
<summary>Tail log</summary>

```console
[ +129 ms] ------ Debug phase ------
[        ] Starting debug of 4781749bcc830a01bf3326c466d1d86cea0bc844 (N61AP, iPhone 6 (GSM), iphoneos, arm64, 12.5.7, 16H81) a.k.a.
'Developmet iphone 6' connected through USB...
[+4205 ms] [  0%] Looking up developer disk image
[  +32 ms] [ 95%] Developer disk image mounted successfully
[  +21 ms] Symbol Path: /Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols
[ +409 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +316 ms] (lldb) command source -s 0
'/tmp/81751DCA-E9E1-4E70-9F0D-D032E2A49369/fruitstrap-lldb-prep-cmds-4781749bcc830a01bf3326c466d1d86cea0bc844'
[        ] Executing commands in
'/tmp/81751DCA-E9E1-4E70-9F0D-D032E2A49369/fruitstrap-lldb-prep-cmds-4781749bcc830a01bf3326c466d1d86cea0bc844'.
[        ] (lldb)     platform select remote-'ios' --sysroot '/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7
(16H81)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]    Sysroot: /Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols
[        ]   SDK Path: "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols"
[        ] (lldb)     target create "/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos/Runner.app"
[+4948 ms] Current executable set to '/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/2FA882A5-BBD7-4182-8E18-260A44577DE0/Runner.app"
[  +55 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:64213"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7
(16H81)/Symbols/usr" /System "/Users/jacofourie/Library/Developer/Xcode/iOS DeviceSupport/12.5.7 (16H81)/Symbols/System"
"/private/var/containers/Bundle/Application/2FA882A5-BBD7-4182-8E18-260A44577DE0"
"/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos"
"/var/containers/Bundle/Application/2FA882A5-BBD7-4182-8E18-260A44577DE0"
"/Users/jacofourie/Desktop/FlutterProjects/smh/build/ios/iphoneos" /Developer "/Users/jacofourie/Library/Developer/Xcode/iOS
DeviceSupport/12.5.7 (16H81)/Symbols/Developer"
[  +36 ms] (lldb)     command script import
"/tmp/81751DCA-E9E1-4E70-9F0D-D032E2A49369/fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.py"
[   +2 ms] (lldb)     command script add -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_4781749bcc830a01bf3326c466d1d86cea0bc844.safequit_command safequit
[        ] (lldb)     connect
[  +27 ms] (lldb)     run
[ +300 ms] success
[        ] (lldb)     safequit
[ +126 ms] Process 490 detached
[  +47 ms] Application launched on the device. Waiting for Dart VM Service url.
[ +730 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
[+29274 ms] The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...
```
</details>

@JacoFourie Based on the tail log, it looks similar to https://github.com/flutter/flutter/issues/127656. Could you check if it's also your case? (@mcagrigoktas  please also confirm this)

**Comment by JacoFourie** [comment] 2023-10-09 18:32
@huycozy, how do I check as there is no solution to the issue? 
I did not change any code. The only thing that changed was I upgraded XCode. 
I don't have time at the moment, but I will have to downgrade my XCode again

**Comment by huycozy** [comment] 2023-10-10 05:17
>how do I check as there is no solution to the issue?

What I mean is to confirm you have the same situation there (similar issues should be centralized on one issue only). 

>The only thing that changed was I upgraded XCode.

The reporter of https://github.com/flutter/flutter/issues/127656 had updated iOS version instead but it might be related. Labeling this issue as a separate one for other's input.

**Comment by wph144** [comment] 2023-10-10 11:00
The same issue happened to me. I am working under the following environment, and I actually deployed the app to the App Store today.
Xcode 15.0, macOS: Sonoma

A user reported to me that they are on iOS 16.6.1 and the app crashes immediately upon launch, preventing them from accessing the app.
16.6.1 -> Issue encountered
Upgraded to 16.7 -> Issue persists
Upgraded to 17.0.x -> Works normally

The same issue was observed on another device running iOS 16.6.1 owned by my acquaintance.

I downloaded the 16.4 simulator in Xcode and ran it in debug mode, but it executed normally.
(It seems that the real version cannot be executed on the simulator). I am stuck at this point without any further leads.

**Comment by dev-mingo** [comment] 2023-10-10 12:09
I'm also facing the same issue. 
Using Flutter 3.13.6, the latest stable one.
iOS 16 users reported that the app crashes right after launch. 
After upgrading to iOS 17, the app works again normally.
I'm just curious whether this is a Flutter issue. Hope it get's resolved soon.

**Comment by JacoFourie** [comment] 2023-10-10 13:09
My app is now working again on other IOS versions. I updated all my libraries to the latest versions and did a pod upgrade and a pod install. Now all is working again.

**Comment by wph144** [comment] 2023-10-10 14:34
In my case, the issue was with connectivity_plus 4.x.x having an iOS deployment target of 11.0. This issue was resolved in connectivity_plus 5.0.0.

https://github.com/flutter/flutter/issues/136060


<img width="846" alt="image" src="https://github.com/flutter/flutter/assets/10491866/2c3102ec-0ea3-4587-a6d6-0d7a55c1bd7a">

**Comment by stuartmorgan** [comment] 2023-10-10 15:03
Is anyone experiencing this issue **not** able to resolve it by setting the minimum deployment target of your application (in Xcode and in your Podfile) to iOS 12?

(If that is indeed necessary it seems like an Xcode bug, but we could potentially work around it with an auto-migration if the tool sees that Xcode 15 is being used.)

**Comment by JacoFourie** [comment] 2023-10-10 15:07
> In my case, the issue was with connectivity_plus 4.x.x having an iOS deployment target of 11.0. This issue was resolved in connectivity_plus 5.0.0.
> 
> #136060
> 
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/10491866/273953942-2c3102ec-0ea3-4587-a6d6-0d7a55c1bd7a.png">

Then that must be my issue also as I also use that library.  Why would it work on iOS 17 but not the others if the target was set to 11? And why is there no error. It just does not work.

**Comment by stuartmorgan** [comment] 2023-10-10 15:16
> Why would it work on iOS 17 but not the others if the target was set to 11?

It may be that Xcode is dropping unsupported `IPHONEOS_DEPLOYMENT_TARGET` values, such that rather than adjusting to the minimum possible (12.0) it uses the latest (17.0), which would result in a binary that can only launch on iOS 17+.

**Comment by JacoFourie** [comment] 2023-10-11 08:36
OK so I guess I can close the issue then Thanks all for the info and help.

**Comment by stuartmorgan** [comment] 2023-10-11 10:04
Re-opening to evaluate for an auto-migration per my comment above.

**Comment by vincendep** [comment] 2023-10-12 09:15
I have experienced the same issue after updating to Sonoma (shame on me). Apparently fixed the problem downloading Xcode 14.3.1 package, renaming to Xcode_14.3.1.app, moving to /Applications and executing 

`sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer `

**Comment by danallen88** [comment] 2023-10-19 15:19
> Is anyone experiencing this issue **not** able to resolve it by setting the minimum deployment target of your application (in Xcode and in your Podfile) to iOS 12?
> 
> (If that is indeed necessary it seems like an Xcode bug, but we could potentially work around it with an auto-migration if the tool sees that Xcode 15 is being used.)

I can confirm that this workaround does not work for us while still using Xcode 15.

The top of our `Podfile` has:
```
platform :ios, '12.0'
```

while our `project.pbxproj` has:
```
IPHONEOS_DEPLOYMENT_TARGET = 12.0;
```
sprinkled throughout it.

**Comment by stuartmorgan** [comment] 2023-10-19 16:15
@danallen88 Could you upload a complete verbose build log for a build that crashes on iOS 16 and earlier?

**Comment by shajedul-bdfare** [comment] 2023-11-06 16:13
I am facing the same issue. Jut released an app but users except ios 17 cant open the app

**Comment by praneethfdo** [comment] 2023-11-07 02:59
Happened for me as well. Lucky we caught this before releasing to production. Got it working after setting IPHONEOS_DEPLOYMENT_TARGET = 12.0;

**Comment by pban7817** [comment] 2023-11-07 04:29
I am currently facing the same issue. Just released an app but users except IOS 17 cant open the app.
I'm using XCODE 15.0.1 (15A507)
<img width="945" alt="image" src="https://github.com/flutter/flutter/assets/108317521/8b3c8a17-427d-4ff6-a068-7b1e3c0b491a">
Appreciate if someone post an answer for this.

**Comment by shajedulislam** [comment] 2023-11-07 08:41
So I fixed mine. As mentioned above about the connectivity_plus, I was not using it but I was using Inter connection checker plus which was depending on connectivity_plus. So I updated the Inter connection checker package to latest version and now problem solved. 

So the possible solutions are:

1. Check if you are using connectivity_plus package and if so then update it to the latest version which is may be 5.0.0
2. If you are not using connectivity_plus then check if any of your package is depending on it or not. If so then update that package.
3. Other than above solution run the project from xcode in real device that has ios version below 17. Xocde will throw error and open the exact file which is causing this error. Then at top (File explorer) you can see from where or which package the file belong to. Then you will understand which package is causing this.
4. Set deployment target to 12.0

I am pretty much sure any of the above 4 will solve this issue. Good luck!

**Comment by dpedrinha** [comment] 2023-11-21 03:31
Same problem here.
I updated connectivity plus and all other plugins except flutter_local_notifications and configurable_expansion_tile_null_safety because they break my code.
If the problem is the deployment target of the plugins, isn't there a way to force them all to the same version?

**Comment by jmagman** [comment] 2023-12-19 19:13
(Assuming all the reports here are related to the `connectivity_plus` crashes)

Interestingly this seems specific to `Network`, I was able to reproduce with `NWProtocolIP.Metadata` for example.  However   the `NaturalLanguage` framework was also introduced in iOS 12 and when I wrap `NLLanguageRecognizer` in an `#available` check it works correctly with a min 11 version on a phone running iOS 16.

And accessing `@available(iOS 12.0, *)` wrapped `UITextContentType.oneTimeCode` and `UITextContentType.newPassword` isn't crashing either:
https://github.com/flutter/engine/blob/2759fa3ea9180f537cf50d4b8e93978458eebbd3/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L307-L315

Here's the same reported on an Apple forum https://developer.apple.com/forums/thread/737672.  Quinn seems to think `but the range of supported deployment target versions` should be a fatal error instead of a warning, though Flutter has historically run on versions much older than the minimum one supported by Xcode.  So this is an unfortunate turn.

If this is the case then we need to always bump the minimum version of Flutter to the one supported by the latest version of Xcode.  I'll start on the project-side migration for this, and I'll start on the documentation of this policy.

**Comment by the-best-is-best** [comment] 2023-12-21 10:46
xcode 15 minimum is 12 and check apps support only ios 12 and above  then where the issue ... apple not will support ios under 12 and soon will support 14 and above only

**Comment by jmagman** [comment] 2023-12-21 22:18
> though Flutter has historically run on versions much older than the minimum one supported by Xcode. So this is an unfortunate turn.

Xcode always drops "support" for versions but historically you could target lower deployment versions and it would be stable and continue to work.  This is the first time I've seen an issue where just changing the deployment version causes any problems, even on devices running newer versions.  I very much doubt this was intentional by Apple, but they likely don't test this scenario.

I wrote a proposal to keep Flutter within the Xcode range moving forward: [flutter.dev/go/match-xcode-deployment-range](https://flutter.dev/go/match-xcode-deployment-range).

**Comment by the-best-is-best** [comment] 2023-12-22 09:27
If I need support ios lower than 12 need downgrade xcode to 14 and check
I think will need downgrade flutter  

But error from xcode not flutter can check it when make xcode build and see the error from xcode and will tell u the minimum target

**Closed** 2024-01-02 19:42 UTC
Labels: platform-ios, tool, e: OS-version specific, P1, team-ios, triaged-ios

**Comment by jmagman** [comment] 2024-01-02 21:01
https://github.com/flutter/flutter/pull/140478 (relanded with https://github.com/flutter/flutter/pull/140823)  enforced a minimum of iOS 12 and is available in the master channel, which should prevent this and similar crashes.

If you are not using the master channel you can set the version manually:
1. Open `ios/Runner.xcworkspace` in Xcode
2. In build settings select the Runner project 
3. Update the minimum iOS deployment version to 12.0

![Screenshot 2024-01-02 at 11 50 14 AM](https://github.com/flutter/flutter/assets/682784/11b3c7d7-8ae9-45ad-b9e8-56fbcf4d1a9e)

**Comment by jmagman** [comment] 2024-01-10 21:45
Flutter 3.16.6 now updates your project automatically to iOS 12, so there shouldn't be networking crashes.

**Comment by ntaworking** [comment] 2024-01-12 07:53
@jmagman 
If I would like manual update `Deployment target` what should I do?
Just change `Minimum deployments` in `Target` ->`Runner` -> `General` tab is enough?
Is need change:  `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'` and `platform :ios, '12.0'` in Podfile?

**Comment by jmagman** [comment] 2024-01-12 23:43
> @jmagman If I would like manual update `Deployment target` what should I do? Just change `Minimum deployments` in `Target` ->`Runner` -> `General` tab is enough? Is need change: `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'` and `platform :ios, '12.0'` in Podfile?

You should only need to update the Runner project minimum deployment, no changes needed in the Podfile.  If you find you needed to change something else please let me know.

**Comment by jmagman** [comment] 2024-01-19 18:20
@danallen88 interesting, I didn't see that in my testing, it seemed to be the deployment target of the app, not the frameworks, that mattered.  Was the crash in connectivity_plus or somewhere else?

**Comment by danallen88** [comment] 2024-01-19 20:35
> @danallen88 interesting, I didn't see that in my testing, it seemed to be the deployment target of the app, not the frameworks, that mattered. Was the crash in connectivity_plus or somewhere else?

Do you have any guidance on how to best determine this? I've tried running from Xcode as suggested above but had to change some settings to point Flutter at our custom entrypoint (we have multiple based on what flavor app we're building).

This is all I'm seeing:
<img width="1139" alt="Screenshot 2024-01-19 at 3 34 48 PM" src="https://github.com/flutter/flutter/assets/4910808/53e81e7b-e342-4f9f-9eaf-3ba3e3c84400">

**Comment by jmagman** [comment] 2024-01-19 20:48
That looks unrelated to this issue, and probably because your flavors aren't set up correctly, check your Configurations (see note in https://docs.flutter.dev/deployment/flavors#creating-flavors-in-ios).  You can file a new issue and I can take a look.

I recommend updating to 3.16.6 to fix the connectivity crash, it will force all your pods to iOS 12 if they are at a lower minimum.

**Comment by danallen88** [comment] 2024-01-19 20:57
I agree this is a different issue (it's my inability to run the app from Xcode the same way I would typically run it from Android Studio, probably because I'm missing something as you mentioned). I'm claiming that the app will actually crash immediately upon startup when I run our normal build through Android Studio, but I think I need to be able to run it from Xcode and not Android Studio in order to see the source of the crash if I understand correctly.

We were holding off upgrading flutter because of the breaking changes it introduces for us and hoping to resolve this in the meantime. But unless there is guidance on how to run a flavored app from Xcode directly, I'm not able to be much help in showing the root cause here.

**Comment by jmagman** [comment] 2024-01-19 21:23
> I'm claiming that the app will actually crash immediately upon startup when I run our normal build through Android Studio, but I think I need to be able to run it from Xcode and not Android Studio in order to see the source of the crash if I understand correctly.

@danallen88 is there a crash log for the device? Xcode > Window > Devices and Simulators > the crashing device > Open Recent Logs (the timestamps would match the crash)
![Screenshot 2024-01-19 at 1 22 58 PM](https://github.com/flutter/flutter/assets/682784/c87d27cb-1a9b-4994-b56a-a68da2adb2b0)

**Comment by danallen88** [comment] 2024-01-22 13:37
Unfortunately not. I appreciate you taking a look along with me! I'm thinking that if we can manage the upgrade to 3.16 and we still require that workaround, I will open a new issue. Thanks @jmagman!
