### ISSUE TITLE
Icons.keyboard_double_arrow_right shows the wrong icon

### ISSUE THREAD

**Issue by dspells** [flutter/flutter#98439] opened 2022-02-14 20:40 UTC
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (5 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

// minimal code to reproduce
const Icon(Icons.keyboard_double_arrow_right, color: Colors.black)

// actual results
![Screen Shot 2022-02-14 at 2 38 00 PM](https://user-images.githubusercontent.com/4716551/153942579-18a0b8fd-40c8-4077-bef1-23df8044262c.png)

// expected results
See https://fonts.google.com/icons?selected=Material+Icons&icon.query=keyboard_double_arrow_right

**Comment by danagbemava-nc** [comment] 2022-02-15 08:18
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-15 08:18 UTC
Labels: in triage
