### ISSUE TITLE
Hot reloading is not indicated in vscode

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#60439] opened 2020-06-27 18:44 UTC
From today 6/8/2020 the hotreloading process is not showing in the notification bar,I did not updated the flutter sdk,but a few hours before the issue ive seen a notification about "Dart sdk has been updated".
completely uninstalled and recreated a new project but the issue remains same,Only when the hotlreload is finished its logged in console `"Reloaded 0 of 495 libraries in 167ms."`

**Flutter Doctor Output**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
```

Expected Progress indication for hotreload is..
![Untitled-1](https://user-images.githubusercontent.com/39165538/85929623-1ac64380-b8d4-11ea-8a3f-2db99d40f4b0.png)

**Comment by iapicca** [comment] 2020-06-29 13:40
Hi @rajeshjeshar 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-29 13:40 UTC
