### ISSUE TITLE
After hitting a breakpoint and changing code and doing a hot restart program hangs

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#57908] opened 2020-05-24 22:39 UTC
One of my main use cases is the following:
1. Set a breakpoint 
2. run to breakpoint
3. modify code 
4. do a hot restart to debug with the new code

Unfortunately, the program hangs (I have shut down the program manual on the device ) or crashes 99% of the time and (I always work on the physical device, not an emulator). And then I can restart the program for another debug session. In other words, the hot restart is pointless for me. I am working on Windows. Sometimes if I hit F5 (resume) before hot restart I get a hot restart.

```

C:\Projects\obdchk\elm_bluetooth_bloc>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.17.0 at c:\sdks\flutter
    • Framework revision d3ed9ec945 (7 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 32-bit edition (version 1.45.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • moto g power • ZF6523C4GL • android-arm64 • Android 10 (API 29)

```

**Comment by bdlukaa** [comment] 2020-05-25 01:16
I had a issue like this one. It have happened a few times and I think the reason is that my IDE (vscode) pauses the application when a breakpoint happens. If I restart the app when it's paused, the app stops working and I can't even hot restart or reload, so I had to stop it and run it again.
Maybe it's a bug in the Flutter extension

**Comment by iapicca** [comment] 2020-05-25 12:01
Hi @ride4sun 
could you please run `flutter upgrade —force`,
If the issue persist please provide your updated `flutter doctor -v` 
your `flutter run --verbose`,
and a reproducible minimal code sample.
Thank you

**Comment by ride4sun** [comment] 2020-05-27 22:31
I tied the same on IOS after an upgrade and it just hangs with this message in the console after a code change and hot restart:
```
Performing hot restart...
Syncing files to device Jay’s iPhone...
```
flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /Users/jay/development/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jay/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Jay’s iPhone • bc987fccd61b08a374d7fd1329958f428155b60b • ios • iOS 13.4.1

• No issues found!
jay@mini obdchk % 

```

**Comment by TahaTesser** [comment] 2020-05-28 09:13
Hi @ride4sun 
Testing counter example on latest `stable` with VS Code, i don't experience any hang by following steps 
```
Set a breakpoint
run to breakpoint
modify code
do a hot restart to debug with the new code


### Breakpoint on `onPressed`
```
### Before

```
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => print('before change test'),
      ),
```

### After
```
        onPressed: () {
           print('after change test');
        },
```

logs
```
flutter: after change test
Restarted application in 979ms.
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.17.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Taha’s iPhone • 00008020-001059882212002E            • ios • iOS 13.5
    • iPhone 11     • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)

• No issues found!
``` 

</details> 
Thank you

**Comment by ride4sun** [comment] 2020-05-28 16:00
Well I see it on Android and IOS. The project has many subpackages and some generated code. Not sure if that makes a difference.

**Comment by iapicca** [comment] 2020-05-29 06:37
Hi @ride4sun 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51853) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ride4sun** [comment] 2020-05-29 17:13
That is not the same. I can debug. Just the use case I described above does not work in 95% of all cases.

**Comment by iapicca** [comment] 2020-06-03 09:28
Hi @ride4sun 
Are you experiencing the issue with VS Code, Android Studio or both?
Thank you

**Comment by ride4sun** [comment] 2020-06-03 14:19
I am normally using Android Studio. I will try Vscode and report back

**Comment by TahaTesser** [comment] 2020-06-26 15:26
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-26 15:26 UTC
Labels: in triage, waiting for customer response

**Comment by stevenspiel** [comment] 2020-08-12 18:14
With android studio, I always have to continue out of the break point before doing a hot restart/reload. Otherwise, I run into this as well.
