### ISSUE TITLE
[webview_flutter] Simulator keyboard isn't showing and hardware keyboard isn't working 

### ISSUE THREAD

**Issue by Pavel-Sulimau** [flutter/flutter#74044] opened 2021-01-15 14:19 UTC
## Steps to Reproduce

1. Make sure you use one of the recent flutter beta versions (24 or 25). I used `1.25.0-8.2.pre`.
2. Create a default flutter app and add [webview_flutter package](https://pub.dev/packages/webview_flutter/install) to it.
3. Use this tiny code snippet:
``` dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('iOS Simulator Keyboard')),
        body: WebView(
          initialUrl: 'https://google.com',
        ),
      ),
    );
  }
}
```
Here is my pubspec file contents:
``` yaml
name: webview_keyboard_ios
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

4. Run the app on an iOS simulator and put your mouse cursor into the webpage text field.
5. Observe the keywords not working.

**Expected results:**
* iOS Simulator Software keyboard is shown;
* I'm able to type text using my laptop hardware keyboard.

**Actual results:** 
* iOS Software keyboard is not showing up for Web pages' fields;
* Laptop Hardware Keyboard not working for iOS Simulator.

**PLEASE NOTE:**
the iOS simulator keyboard was working fine up until flutter `1.23.0-18.1.pre` inclusive.

**See the following video:**
![flutter_beta_1_25_webview_keyboard_ios](https://user-images.githubusercontent.com/8143332/104735478-b0cb9980-5752-11eb-8b80-817d6e7d6fe2.gif)

I also attached the sample project:
[webview_keyboard_ios.zip](https://github.com/flutter/flutter/files/5821187/webview_keyboard_ios.zip)

<details>
  <summary>Logs</summary>

**`flutter doctor -v` output:**

```
✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-BY)
    • Flutter version 1.25.0-8.2.pre at /Users/pavel_sulimau/src/open_source/flutter
    • Framework revision b0a2299859 (10 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pavel_sulimau/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • 629A4367-1BDB-4287-9F4F-CF760A7D57F6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-01-15 14:56
Hi @Pavel-Sulimau 
I see the behavior as you on `Channel stable, 1.22.5` asl well 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('iOS Simulator Keyboard')),
        body: WebView(
          initialUrl: 'https://google.com',
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios           • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision b0a2299859 (10 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-8.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision b9d06fffb2 (8 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.365, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.365 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9209319dd1 (6 hours ago), 2021-01-15 14:34:03 +0530
    • Engine revision efa768683e
    • Dart version 2.12.0 (build 2.12.0-225.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

Thanks for filing the issue.

**Comment by muhleder** [comment] 2021-02-04 17:53
The simulator keyboard is a bit of a red herring, you can switch off the hardware keyboard in the simulator with Apple-Shift-K or from the menu I/O>Keyboard>Connect Hardware Keyboard.

The actual issue is that hardware keyboards now do not work in platform views. This applies not only to the simulator but also to bluetooth keyboards used with real iOS devices.

I bisected the issue down to this PR in the engine https://github.com/flutter/engine/pull/20972

Btw, the latest flutter branch that still works is flutter-1.24-candidate.2

I'm not that familiar with the iOS code, but it looks like the new PR captures hardware key events to pass to the framework where they can be used, but it should allow them to pass through to platform views when a platform view has focus.

**Comment by muhleder** [comment] 2021-02-04 17:56
@KammererTob tagging you for visibility and in case you want to correct any of my assumptions.

**Comment by cyanglaz** [comment] 2021-02-04 19:23
CC @gspencergoog Could you take a look at the keyboard issue here? It looks like a regression due to flutter/engine#20972 based on https://github.com/flutter/flutter/issues/74044#issuecomment-773493950

**Comment by gspencergoog** [comment] 2021-02-04 19:29
Yes, I will take a look.

**Comment by cyanglaz** [comment] 2021-02-18 19:03
@gspencergoog Is there any updates on this? Let us know if you need help from the plugin team.

**Comment by gspencergoog** [comment] 2021-02-18 19:51
@cyanglaz Sorry, no updates yet. It is on my queue to look at still. I suspect it has to do with iOS not having the key event redispatch that the other platforms now have, but I haven't verified that.

**Comment by KammererTob** [comment] 2021-02-18 19:56
I had a quick glance, and it might be just as simple as to call `super` in the event functions to pass the event up the responder chain. This might restore the original functionality, but i am not sure about other side-effects this may have. 
From the documentation: 
> The default implementation of this method forwards the message up the responder chain. When creating your own subclasses, call super to forward any events that you do not handle yourself.

**Comment by Pavel-Sulimau** [comment] 2021-03-10 15:47
@gspencergoog, I'm sorry to disturb you, I'd like to ask you about the progress on this issue. Are there any news so far?

**Comment by gspencergoog** [comment] 2021-03-10 18:25
@Pavel-Sulimau No real news, but it's still being worked on.

**Comment by KammererTob** [comment] 2021-03-11 16:12
I can have a go at this if @gspencergoog is not already working on it.

**Comment by gspencergoog** [comment] 2021-03-11 20:16
@KammererTob If you'd like to take a look, please go ahead.

**Comment by KammererTob** [comment] 2021-03-21 16:09
My suggestion above seem to have fixed the issue. The relevant changes are outlined here:
https://github.com/blackhorse-one/engine/commit/7e9390f89542470f3257b57ef021cee5b4596eed

I could not find any issue by manual testing a few scenarios, but before opening a PR i would probably need some help on where to put tests (if needed) for this.

**Comment by zhenqiu1101** [comment] 2021-03-30 17:41
internal b/183659597 seems running into the same problem.

**Comment by Pashokresh** [comment] 2021-03-31 12:18
Shift+CMD+K works for me

**Comment by Pavel-Sulimau** [comment] 2021-04-01 04:20
> Shift+CMD+K works for me to show simulator keyboard

Yes, it shows the software keyboard on a simulator, but the hardware keyboard (laptop keyboard) is still not working for me with the simulator, so I can't just type anything on my laptop keyboard.

<details>
**`flutter doctor -v` output:**

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-BY)
    • Flutter version 2.0.3 at /Users/pavel_sulimau/fvm/versions/stable
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pavel_sulimau/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 1DF608D1-DBB7-4323-8791-E982CB147A6C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
</details>

**Comment by pawelknuthGelato** [comment] 2021-04-01 05:55
This is an issue for me also

**Comment by cyanglaz** [comment] 2021-04-01 17:36
@KammererTob Do you mind open a PR with the fix in https://github.com/blackhorse-one/engine/commit/7e9390f89542470f3257b57ef021cee5b4596eed and we can find someone who is familiar with that code to take a look at it. Thanks!

**Comment by KammererTob** [comment] 2021-04-01 19:56
Done!

**Comment by jorgesarabia** [comment] 2021-06-26 21:02
I have also experienced this issue and a stackoverflow user [grebennikovlmax](https://stackoverflow.com/users/16310761/grebennikovlmax) has provided me with a partial solution until this change is available on the stable channel. You can see the details here: https://stackoverflow.com/questions/68091663/bluetooth-keyboard-does-not-work-on-flutter-webview-ios-hardware-keyboard

**Comment by tomassasovsky** [comment] 2021-07-10 09:30
This is currently also an issue for me. Any updates on it being fixed?
I've tested it on both flutter 2.2.3 (stable) and 2.4.0-0.0.pre (dev).

**Comment by sangle1996** [comment] 2021-07-27 02:35
I see it work on master @tomassasovsky . I don't know how much longer this commit can be merged into the stable?

**Comment by danagbemava-nc** [comment] 2021-08-18 07:37
The issue of the simulator keyboard not showing up can be reproduced on `master 2.5.0-7.0.pre.129` and `stable 2.2.3`, however, on master, using the `hardware keyboard` works as expected. 

In the `stable` video, I start typing around the 7 second mark on my keyboard but no response.
In the `master` video, the text starts appearing when I start typing.

See attached videos:

[stable.zip](https://github.com/flutter/flutter/files/7005426/stable.zip)

[master.mov.zip](https://github.com/flutter/flutter/files/7005427/master.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.129, on macOS 11.5.1 20G80
    darwin-arm, locale en-GH)
    • Flutter version 2.5.0-7.0.pre.129 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 29c089c2ed (80 minutes ago), 2021-08-18 01:37:04 -0400
    • Engine revision b13c765675
    • Dart version 2.15.0 (build 2.15.0-24.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6 18F72
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by techouse** [comment] 2021-08-19 14:06
I've got the same issue on Flutter version 2.2.3.

**Comment by Messhias** [comment] 2021-09-22 17:04
Even in the newest versions this issue still persists.

**Comment by techouse** [comment] 2021-09-23 09:07
> Even in the newest versions this issue still persists.

I haven't encountered this issue ever since I upgraded to Flutter v2.5.0.

**Comment by Messhias** [comment] 2021-09-23 09:33
> > Even in the newest versions this issue persists.
> 
> I haven't encountered this issue ever since I upgraded to Flutter v2.5.0 and the Xcode 13.0 simulator
> 
> ```
> Version 13.0 (970)
> SimulatorKit 612
> CoreSimulator 776.3
> ```

Hi, I checked right now my version is 2.3, I'll upgrade and give it a try. Thank you

**Comment by mrbeandev** [comment] 2021-09-27 10:10
is this keyboard issue fixed?

**Comment by brianlenz** [comment] 2021-09-27 19:41
> is this keyboard issue fixed?

I can confirm it's working in Flutter 2.5.1.

**Comment by dot-wei2021** [comment] 2021-09-29 06:02
platform: Android
flutter 2.5.1
Connect Bluetooth keyboard, other keys are valid **but arrow keys do not work**.

**Comment by Kolloshe** [comment] 2022-02-22 11:12
https://stackoverflow.com/questions/70212256/soft-keyboard-stopped-working-in-flutters-webview-on-android-12/70212257#70212257?newreg=6acda42a4ce54e19a8e006f72cacc22d
 
this answer it work for me 


[webview_flutter](https://pub.dev/packages/webview_flutter) has an option to set the [platform view mode](https://docs.flutter.dev/development/platform-integration/platform-views). As described in the [README](https://pub.dev/packages/webview_flutter#android-platform-views) the composition mode can be switched from Virtual displays to Hybrid composition. This solves the problem, allows for full keyboard support and only requires Android SDK support 19 but comes with a drawback. The performance on Android 9 and lower is not as good as with the default virtual display mode.

To enable hybrid composition (copying webview's readme right now):

    Set minSdkVersion in android/app/build.gradle

 android {
     defaultConfig {
         minSdkVersion 19
     }
 }

    Put if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView(); somewhere in your application e.g. main.dart or in your StatefulWidget's initState() method.

**Comment by stuartmorgan** [comment] 2022-02-24 21:33
This was fixed in https://github.com/flutter/engine/pull/26412, the issue just didn't get closed.

**Closed by stuartmorgan** 2022-02-24 21:33 UTC
Labels: severe: regression, platform-ios, plugin, p: first party, customer: crowd, p: webview, p: webview-keyboard, has reproducible steps, P4, found in release: 2.2, found in release: 2.5
