### ISSUE TITLE
"No camera found" when using the example from "camera: ^0.10.5+9" as a dart in a project

### ISSUE THREAD

**Issue by gjcarver** [flutter/flutter#142984] opened 2024-02-06 14:57 UTC
### Steps to reproduce

I have been trying out the various examples of camera apps ([https://pub.dev/packages/camera/example](https://pub.dev/packages/camera/example), etc.), and they work as stand-alone projects, but not when integrated into another project because the camera is not being recognized.
The documentation says "Permission errors may be thrown when initializing the camera controller, and you are expected to handle them properly." but I have been unable to find a way to "handle them properly."

### Expected results

camera: ^0.10.5+9 is supposed to find the camera.

### Actual results

"No camera found."

### Code sample

<details open><I presume the error is here, somehow:>Code sample</summary>

```dart
List<CameraDescription> _cameras = <CameraDescription>[];

Future<void> main() async {
  // Fetch the available cameras before initializing the app.
  try {
    WidgetsFlutterBinding.ensureInitialized();
    _cameras = await availableCameras();
  } on CameraException catch (e) {
    _logError(e.code, e.description);
  }
  runApp(const CameraApp());
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19043.2364], locale de-DE)
    • Flutter version 3.16.9 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\carver\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.27)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33801.447
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5284.31

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\carver\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Lenovo TB X304F (mobile) • a62daa74 • android-arm64  • Android 8.1.0 (API 27)
    • Windows (desktop)        • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.2364]
    • Chrome (web)             • chrome   • web-javascript • Google Chrome 121.0.6167.87
    • Edge (web)               • edge     • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2024-02-07 08:05
Hi @gjcarver 
Which target platform are you running app on? 

Please share the entire output of `flutter run -v`. If the log is too long, please save it into a file and attach it here.

>The documentation says "Permission errors may be thrown when initializing the camera controller, and you are expected to handle them properly." but I have been unable to find a way to "handle them properly."

I think all error codes are described clearly there. You may need to use [permission_handler](https://pub.dev/packages/permission_handler) for this.

**Comment by gjcarver** [comment] 2024-02-07 10:13
I tried permission_handler yesterday, with no success.
Right now I am running it on an android tablet, in part because the web versions miss a lot of the icons, etc.
When I run the packages on their own, a small window opens, asking for permission to access, first the camera, then the audio. This doesn't happen when I transfer from one page to the camera page, and although I'm wondering if I should have it ask permission when the whole program starts, it only seems relevant when someone tries to access the camera.
[camera_error.txt](https://github.com/flutter/flutter/files/14192152/camera_error.txt)

**Comment by huycozy** [comment] 2024-02-07 11:57
I can't see `No camera found` error on your output logs, your logs look fine. Since the issue does not appear on package example but on your implemented project, it's better to ask the assistance on support channel like Stackoverflow. 

If you believe this is a bug of `camera` package, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by gjcarver** [comment] 2024-02-07 12:07
Don't think it's the `camera` package, because that is working fine on its own.
And the "production code" is just the examples, from the package, tried one after another.
It just needs to gain permission in response to a "push":

          ElevatedButton.icon(
            icon: const Icon(Icons.camera_alt),
            label: const Text('PHOTO'),
            style: ElevatedButton.styleFrom(
                backgroundColor: Colors.lightBlue[200], //elevated button background color
            ),
            onPressed: () {

              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const PhotosVideo()),
              );

            },
          ),

**Comment by huycozy** [comment] 2024-02-07 12:24
Thanks for your response but the goal of this Github repo is not to assist in personal code but to improve flutter reporting bugs or feature requests.

Please also see flutter's [community](https://flutter.dev/community) for resources and ask questions like this. Closing the issue as it doesn't seem to be a 1st party package's bug.

**Closed by huycozy** 2024-02-07 12:24 UTC
Labels: in triage
