### ISSUE TITLE
[menu_anchor.dart] MenuAnchor crashes when used as context menu and opened during didUpdateWidget.

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#150346] opened 2024-06-17 10:28 UTC
### Steps to reproduce

1. Run code sample
2. Right-click

### Expected results

Should not throw an error.

### Actual results

Throws `SchedulerBinding.instance.schedulerPhase != SchedulerPhase.persistentCallbacks`. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [MenuAnchor].
///
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const Scaffold(body: Bug()),
    );
  }
}

class Bug extends StatefulWidget {
  const Bug({super.key});

  @override
  State<Bug> createState() => _BugState();
}

class _BugState extends State<Bug> {
  Offset _position = Offset.zero;

  void _handleSecondaryTapDown(TapDownDetails details) {
    setState(() {
      _position = details.localPosition;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(50),
      child: GestureDetector(
        onSecondaryTapDown: _handleSecondaryTapDown,
        child: InnerMenuAnchor(
          position: _position,
        ),
      ),
    );
  }
}

class InnerMenuAnchor extends StatefulWidget {
  const InnerMenuAnchor({
    super.key,
    required this.position,
  });

  final Offset position;

  @override
  State<InnerMenuAnchor> createState() => _InnerMenuAnchorState();
}

class _InnerMenuAnchorState extends State<InnerMenuAnchor> {
  final MenuController _menuController = MenuController();

  @override
  void didUpdateWidget(covariant InnerMenuAnchor oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.position != oldWidget.position) {
      _menuController.open(position: widget.position);
    }
  }

  @override
  Widget build(BuildContext context) {
    return MenuAnchor(
      controller: _menuController,
      menuChildren: <Widget>[
        MenuItemButton(
          child: const Text('Text'),
          onPressed: () {},
        ),
      ],
      child: Container(
        alignment: Alignment.center,
        color: Colors.blueGrey[100],
        child: const Column(
          mainAxisAlignment: MainAxisAlignment.center,
        ),
      ),
    );
  }
}



```

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter run
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.69, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.69 on channel master at /Users/davidhicks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 124aacbaef (2 weeks ago), 2024-05-31 22:32:25 -0400
    • Engine revision d81edf635a
    • Dart version 3.5.0 (build 3.5.0-214.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.176
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-06-17 13:17
Reproducible using the code sample provided above. 


<details>
<summary>logs</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building RawGestureDetector(state: RawGestureDetectorState#f5ce9(gestures: [tap])):
OverlayPortalController.show() should not be called during build.
'package:flutter/src/widgets/overlay.dart':
Failed assertion: line 1814 pos 7: 'SchedulerBinding.instance.schedulerPhase != SchedulerPhase.persistentCallbacks'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    GestureDetector GestureDetector:file:///Users/nexus/projects/nevercode/ipad/lib/main.dart:41:14

When the exception was thrown, this was the stack:
#2      _OverlayPortalState.show (package:flutter/src/widgets/overlay.dart:1814:7)
overlay.dart:1814
#3      OverlayPortalController.show (package:flutter/src/widgets/overlay.dart:1554:13)
overlay.dart:1554
#4      _MenuAnchorState._open (package:flutter/src/material/menu_anchor.dart:569:24)
menu_anchor.dart:569
#5      MenuController.open (package:flutter/src/material/menu_anchor.dart:680:14)
menu_anchor.dart:680
#6      _InnerMenuAnchorState.didUpdateWidget (package:ipad/main.dart:70:23)
main.dart:70
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5789:55)
framework.dart:5789
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
framework.dart:3941
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
framework.dart:6907
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
framework.dart:3941
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
framework.dart:6907
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
framework.dart:3941
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
framework.dart:5642
#14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
framework.dart:5780
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (12 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.23.0-13.0.pre.242, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.242 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5187cab7bd (2 days ago), 2024-06-14 23:35:34 -0400
    • Engine revision 9779c273aa
    • Dart version 3.5.0 (build 3.5.0-266.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2024-06-17 14:51
@davidhicks980
This seems to be working as as expected according to the error message.

You can a build widget during build phase which is triggered by the secondary tap down in the sample


Try updating the open calling in a post frame callback, this is called after the widget finish building.
```dart
    SchedulerBinding.instance!.addPostFrameCallback((Duration timeStamp) {
      if (widget.position != oldWidget.position) {
        _menuController.open(position: widget.position);
      }
    });
```

**Comment by davidhicks980** [comment] 2024-06-21 15:25
Whoops sorry @TahaTesser -- I forgot to come back to this issue! Yeah, I wasn't sure whether it was an actual issue considering this is just the standard behavior of overlays. I did notice that the code for closing the menu contains a check for schedulerphase, so I wasn't sure if it was overlooked for opening or if this is expected behavior. https://github.com/flutter/flutter/blob/a3f6a2bdc7e637c9df8f14ceb31aff4edb517b89/packages/flutter/lib/src/material/menu_anchor.dart#L590

I also wasn't sure if there should be a "declarative" way of opening the menu. For example, web dialogs have an "open" parameter that will trigger their showing. But if it's expected behavior, we can close this issue! Sorry for the trouble.

**Comment by YeungKC** [comment] 2024-10-30 12:28
> Whoops sorry @TahaTesser -- I forgot to come back to this issue! Yeah, I wasn't sure whether it was an actual issue considering this is just the standard behavior of overlays. I did notice that the code for closing the menu contains a check for schedulerphase, so I wasn't sure if it was overlooked for opening or if this is expected behavior.
> 
> https://github.com/flutter/flutter/blob/a3f6a2bdc7e637c9df8f14ceb31aff4edb517b89/packages/flutter/lib/src/material/menu_anchor.dart#L590
> 
> I also wasn't sure if there should be a "declarative" way of opening the menu. For example, web dialogs have an "open" parameter that will trigger their showing, rather than users having to call a function or otherwise having to wait for a frame. But if it's expected behavior, we can close this issue! Sorry for the trouble.

#157612
I think it was overlooked.

**Comment by YeungKC** [comment] 2024-10-30 12:40
I think we should be able to close this issue, but we can wait for confirmation from @davidhicks980 first.

**Comment by TahaTesser** [comment] 2024-10-30 13:29
Closing as fixed, feel to comment below if this doesn't resolve your issue @davidhicks980

**Closed** 2024-10-30 13:29 UTC
Labels: c: crash, framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.22, found in release: 3.23
