### ISSUE TITLE
Color is not a subtype of type 'MaterialColor'

### ISSUE THREAD

**Issue by tahaali96** [flutter/flutter#33743] opened 2019-06-03 07:57 UTC
## Steps to Reproduce

1. . The following assertion was thrown building MyApp(dirty): type 'Color' is not a subtype of type 'MaterialColor'. Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
2. . The maia.dart file  [https://gist.github.com/tahaali96/366362dfaac560fe1688dd1e501d8f1a](url) 

3. . Output panel
![image](https://user-images.githubusercontent.com/29300239/58784517-0fcfaf80-85fd-11e9-9f9b-2213c6d9b248.png)

4. . Debug Console
![image](https://user-images.githubusercontent.com/29300239/58784574-31309b80-85fd-11e9-9992-048a948afd36.png)

## Logs

![image](https://user-images.githubusercontent.com/29300239/58785375-d4ce7b80-85fe-11e9-8ca7-f57d6bee3d5b.png)

flutter analyze
![image](https://user-images.githubusercontent.com/29300239/58785061-3d692880-85fe-11e9-89f9-eccc64340449.png)

...
flutter doctor -v
![image](https://user-images.githubusercontent.com/29300239/58784949-f67b3300-85fd-11e9-9b76-314ed89ed7a8.png)

...

**Comment by stuartmorgan** [comment] 2019-06-03 18:20
Duplicate of #15658

As noted there, the message saying to file a bug is itself a bug; the exception here is caused by your code passing the wrong object type to `ThemeData`.

**Closed by stuartmorgan** 2019-06-03 18:20 UTC
Labels: d: stackoverflow, f: material design, framework
