### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by m7s8n6** [flutter/flutter#109383] opened 2022-08-11 11:58 UTC
Oops; flutter has exited unexpectedly: "FileSystemException: Directory listing failed, path =
'C:\$Recycle.Bin\S-1-5-18\*' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Users\DELL\Desktop\ordrz\flutter_03.log.

**Comment by exaby73** [comment] 2022-08-11 12:34
Hello @m7s8n6. Where is your project located? And can you provide the output of `flutter doctor -v` and `flutter run -v`?

**Comment by m7s8n6** [comment] 2022-08-13 10:49
Output of flutter doctor -v

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.




------------------------------------------------------------------------------

Output of flutter run -v

[  +95 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +527 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [C:\src\flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +57 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[  +10 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +134 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +93 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] executing: C:\Users\DELL\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +64 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Multiple devices found:
[  +34 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
[   +2 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] :
[+3528 ms] 2
[  +32 ms] Skipping pub get: version match.
[ +137 ms] Generating
C:\Users\DELL\Desktop\ordrz\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +122 ms] Launching lib\main.dart on Chrome in debug mode...
[ +164 ms] Updating assets
[  +27 ms] "flutter run" took 4,328ms.

[  +11 ms] Sending crash report to Google.
[+1577 ms] Crash report sent (report ID: 935dba34e05793d8)
[   +5 ms] Oops; flutter has exited unexpectedly: "FileSystemException: Directory listing failed, path =
           'C:\$Recycle.Bin\S-1-5-18\*' (OS Error: Access is denied.
           , errno = 5)".
[  +20 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +150 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[  +15 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +137 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +6 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +1 ms] 4 weeks ago
[  +55 ms] java -version
[   +8 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +41 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +38 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +39 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +2 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +39 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products *
-utf8 -latest -prerelease -all
[  +39 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products
* -utf8 -latest -prerelease -all
[   +1 ms] [
             {
               "instanceId": "e3504987",
               "installDate": "2022-07-18T06:15:12Z",
               "installationName": "VisualStudio/17.2.6+32630.192",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.2.32630.192",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 5,
               "isComplete": false,
               "isLaunchable": false,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.17.Release",
               "channelUri": "https://aka.ms/vs/17/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelUri": "https://aka.ms/vs/17/release/channel",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.6",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-07-18T06:15:12.7884983Z",
               "catalog": {
                 "buildBranch": "d17.2",
                 "buildVersion": "17.2.32630.192",
                 "id": "VisualStudio/17.2.6+32630.192",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.2.6",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "6",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "17.2.6+32630.192",
                 "requiredEngineVersion": "3.2.2159.37022"
               },
               "properties": {
                 "campaignId": "2030:a7215d23-f206-48f1-8d4f-4f5363df1098",
                 "channelManifestId": "VisualStudio.17.Release/17.2.6+32630.192",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +4 ms] executing: reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 /v
InstallationFolder
[  +22 ms] Exit code 1 from: reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 /v
InstallationFolder
[   +1 ms] ERROR: The system was unable to find the specified registry key or value.
[  +17 ms] executing: C:\Users\DELL\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +47 ms] List of devices attached
[+2829 ms] A crash report has been written to C:\Users\DELL\Desktop\ordrz\flutter_05.log.
[   +3 ms] This crash may already be reported. Check GitHub for similar crashes.
[   +1 ms]
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Directory+listing+failed%2C+path+%3D+%27C%
3A%5C%24Recycle.Bin%5CS-1-5-18%5C%2A%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

[   +2 ms] To report your crash to the Flutter team, first read the guide to filing a bug.
[   +2 ms] https://flutter.dev/docs/resources/bug-reports

[   +1 ms] Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank
you!
[  +37 ms]
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Directory+listing+failed%2C+
OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5&body=%23%23+Command%0A%60%60%60%0Aflutter+run+-v%0A%60%60%60%0A%0A%23
%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Directory+listing+failed%2C+
OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%0A%60%60%60%0A%230++++++_Directory._fillWithDirectoryListing+%28dart%
3Aio-patch%2Fdirectory_patch.dart%3A42%3A24%29%0A%231++++++_Directory.listSync+%28dart%3Aio%2Fdirectory_impl.dart%3A243%
3A5%29%0A%232++++++ForwardingDirectory.listSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_directory.dart%3A43%3A
12%29%0A%233++++++ForwardingDirectory.listSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_directory.dart%3A43%3A1
2%29%0A%234++++++_AssetDirectoryCache.variantsFor+%28package%3Aflutter_tools%2Fsrc%2Fasset.dart%3A953%3A78%29%0A%235++++
++ManifestAssetBundle._parseAssetFromFile+%28package%3Aflutter_tools%2Fsrc%2Fasset.dart%3A792%3A37%29%0A%236++++++Manife
stAssetBundle._parseAssets+%28package%3Aflutter_tools%2Fsrc%2Fasset.dart%3A697%3A9%29%0A%237++++++ManifestAssetBundle.bu
ild+%28package%3Aflutter_tools%2Fsrc%2Fasset.dart%3A245%3A54%29%0A%3Casynchronous+suspension%3E%0A%238++++++ResidentWebR
unner._updateDevFS+%28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fresident_web_runner.dart%3A502%3A26%29%0A%3Casynchronou
s+suspension%3E%0A%239++++++ResidentWebRunner.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fisolated%2F
resident_web_runner.dart%3A287%3A41%29%0A%3Casynchronous+suspension%3E%0A%2310+++++asyncGuard.%3Canonymous+closure%3E+%2
8package%3Aflutter_tools%2Fsrc%2Fbase%2Fasync_guard.dart%3A111%3A24%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60
%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.0.5%2C+on+Microsoft+Windows+%5BVersion+10.0.22000.856%5D%2C+loca
le+en-US%29%0A++++%E2%80%A2+Flutter+version+3.0.5+at+C%3A%5Csrc%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2
F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+f1875d570e+%284+weeks+ago%29%2C+2022-07-13+11%
3A24%3A16+-0700%0A++++%E2%80%A2+Engine+revision+e85ea0e79c%0A++++%E2%80%A2+Dart+version+2.17.6%0A++++%E2%80%A2+DevTools+
version+2.12.2%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A+
+++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CDELL%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-33%2C
+build-tools+33.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava
%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A++++%E2%80%A2+Al
l+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+
Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%21%5D+Visual+Studio+-+develop+for+Windows+%28Visual+Studio+C
ommunity+2022+17.2.6%29%0A++++%E2%80%A2+Visual+Studio+at+C%3A%5CProgram+Files%5CMicrosoft+Visual+Studio%5C2022%5CCommuni
ty%0A++++%E2%80%A2+Visual+Studio+Community+2022+version+17.2.32630.192%0A++++%E2%9C%97+The+current+Visual+Studio+install
ation+is+incomplete.+Please+reinstall+Visual+Studio.%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.2%29%0A++++%E2%
80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+
from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can
+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java
+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version
+1.70.1%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CDELL%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%
A2+Flutter+extension+version+3.46.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+Windows+%28d
esktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22000.856%5D%0A++++%E2%
80%A2+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+104.0.5112.81%0A++++%E2%8
0%A2+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+104.0.1293.54%0A%0A%5B%E2
%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+1
+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.
0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%
2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2
A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+f1875d570e39de09040c8f79aa13cc56baab8db1%0A%0A&labels=tool%2C
severe%3A+crash

[ +138 ms] ensureAnalyticsSent: 123ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by exaby73** [comment] 2022-08-15 07:21
@m7s8n6 Thank for the information. This could be a possible regression of https://github.com/flutter/flutter/issues/30113. Labelling for more insights from the team

**Comment by danagbemava-nc** [comment] 2022-10-14 12:30
_Extracted crash log from flutter run -v in https://github.com/flutter/flutter/issues/109383#issuecomment-1214136901_

## Command
```
flutter run -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Access is denied.
, errno = 5
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:697:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:502:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by danagbemava-nc** [comment] 2022-10-14 12:31
Closing as duplicate of https://github.com/flutter/flutter/issues/113019

**Closed by danagbemava-nc** 2022-10-14 12:31 UTC
Labels: severe: regression, severe: crash, tool, a: build
