### ISSUE TITLE
Gray square in place of widget - only if app is instaled from Google Play Store 

### ISSUE THREAD

**Issue by lukaszSieczkowski** [flutter/flutter#67920] opened 2020-10-12 13:12 UTC
**Problem Description:**
[Gray square in place of widget - only if app is instaled from Google Play Store #67868](https://github.com/flutter/flutter/issues/67868)

**Problem cause:**
After removing in Text child widget **textAlign: TextAlign.justify,** works fine.
In this case **Text** Widget is a problem.

**Comment by TahaTesser** [comment] 2020-10-12 14:10
Hi @lukaszSieczkowski 
Looks like you have filed this issue  already 
Closing as duplicate of https://github.com/flutter/flutter/issues/67868

**Closed by TahaTesser** 2020-10-12 14:10 UTC

**Comment by lukaszSieczkowski** [comment] 2020-10-12 14:23
Yes but is closed without understanding a problem
