### ISSUE TITLE
Cannot set font size smaller than 12, text will be enlarged and truncated. No issue on 1.20.x stable, only beta

### ISSUE THREAD

**Issue by ZhangLiuCheng** [flutter/flutter#65526] opened 2020-09-04 03:14 UTC
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale zh-Hans)
    • Flutter version 1.21.0-9.2.pre at /Users/zhangliucheng/Documents/software/flutter
    • Framework revision 81a45ec2e5 (7 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zhangliucheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter`
```

**Comment by markusaksli-nc** [comment] 2020-09-10 07:11
Hi @ZhangLiuCheng 
Can you please provide your `flutter doctor -v` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by ZhangLiuCheng** [comment] 2020-09-16 07:54
@markusaksli-nc 
![WechatIMG55](https://user-images.githubusercontent.com/6800810/93308285-a47f1080-f834-11ea-8fb4-ec076c56f481.jpeg)

I'll provide  code sample  in two days，Thank you。

**Comment by ZhangLiuCheng** [comment] 2020-09-17 10:11
[flutter_app.zip](https://github.com/flutter/flutter/files/5238230/flutter_app.zip)

[video1.zip](https://github.com/flutter/flutter/files/5238235/video1.zip)

When I set the font too small, the page will refresh many times, causing problems with the page layout. There is no such problem in (Channel beta, 1.22.0 ), Thank you.

zhangliucheng@zhangliuchengdeMacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale zh-Hans)
    • Flutter version 1.22.0-12.1.pre at /Users/zhangliucheng/Documents/software/flutter
    • Framework revision 8b3760638a (33 hours ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zhangliucheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Redmi 7 (mobile) • 3689b5a    • android-arm64  • Android 9 (API 28)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 2 categories.

**Comment by markusaksli-nc** [comment] 2020-09-18 06:06
@ZhangLiuCheng Do I understand correctly that you are no longer facing this issue on the latest beta channel? I can't reproduce this behavior on latest beta or master.

**Comment by ZhangLiuCheng** [comment] 2020-09-18 07:09
There is no such problem in (Channel beta, 1.20.2), 
(Channel beta, 1.22.0-12.1.pre) have this problem,
In my development environment.

**Comment by TahaTesser** [comment] 2020-09-21 07:29
Hi @ZhangLiuCheng 
It's not clear what the issue if the issue is refresh or text enlarge, either issues are not reproducible using your code sample on the latest `beta` channel on Android Browser as well as desktop browser

In your video, you're showing desktop web with mobile preview, It doesn't reproduce there either.

Here i deployed your sample
https://competent-swanson-bf992a.netlify.app/
Run this example and see if it reproduce for tou

Using this fluter version
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8b3760638a (5 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (2 available)            
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details> 



Can you please provide clear step by step to reproduce the issue. you mention it happens to due to small font so please provide what size does it reproduce and what size does it go away, does it go away with larger font? Please explain in detail and steps to reproduce he issue on Android browser

**Comment by ZhangLiuCheng** [comment] 2020-09-21 08:01
Hi @TahaTesser 

It reproduce in Desktop Web Chrome, the Chrome version see the image below.  It hanppen where the fontSize is around under 12, the different screen font appears differently.

No problem in Safari, no matter how small the font is.

<img width="759" alt="截屏2020-09-21 下午3 41 48" src="https://user-images.githubusercontent.com/6800810/93742630-079be900-fc21-11ea-9b69-306c96f8382c.png">

The app you sent to me will also have problems on my side, below is the video.
[video-9-21.zip](https://github.com/flutter/flutter/files/5253994/video-9-21.zip)


It is ok, On any browser。
`[✓] Flutter (Channel beta, 1.20.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans)
    • Flutter version 1.20.2 at /Users/zhangliucheng/Documents/software/flutter
    • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zhangliucheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Redmi 7 (mobile)              • 3689b5a                   • android-arm64  • Android 9 (API 28)
    • zhangliucheng-iphone (mobile) • 00008030-001065691169802E • ios            • iOS 14.0
    • Web Server (web)              • web-server                • web-javascript • Flutter Tools
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 2 categories.`

-----------------------------------------------------------------------------

it happens below
`[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale zh-Hans)
    • Flutter version 1.22.0-12.1.pre at /Users/zhangliucheng/Documents/software/flutter
    • Framework revision 8b3760638a (33 hours ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zhangliucheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Redmi 7 (mobile) • 3689b5a    • android-arm64  • Android 9 (API 28)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 2 categories.`

Thank you！

**Comment by markusaksli-nc** [comment] 2020-09-22 06:03
Still can't reproduce this but the videos sent by OP seem to prove that there is some weird behavior going on here.

<img src="https://user-images.githubusercontent.com/68219924/93847432-922b2980-fcaf-11ea-8b95-aa004636b7d5.png" height="550" /><img src="https://user-images.githubusercontent.com/68219924/93847333-53956f00-fcaf-11ea-9539-2e57d2b8a392.png" height="550" />

The text on OPs machine seems to be restricted to a min size by something, causing it to get truncated. Seems like for the first frame after a rebuild before the icons show up the text is correctly sized.

<img src="https://user-images.githubusercontent.com/68219924/93847663-30b78a80-fcb0-11ea-8aeb-373c856123a7.png" height="400" />

These videos don't really show the "the page will refresh many times, causing problems with the page layout" part.

**Comment by mdebbar** [comment] 2020-10-15 20:34
Note to self: a while ago @yjbanov did a fix for tiny fonts. We may need to do a similar in canvas text measurement.

**Comment by ajbarry** [comment] 2020-10-21 23:44
This sounds very similar to #64904 which has a working repro.

**Comment by MichaelDark** [comment] 2020-10-22 16:35
To temporary fix it, use this workaround: 

```dart
extension on TextStyle {
  /// Temporary fix the following Flutter Web issues
  /// https://github.com/flutter/flutter/issues/63467
  /// https://github.com/flutter/flutter/issues/64904#issuecomment-699039851
  /// https://github.com/flutter/flutter/issues/65526
  TextStyle get withZoomFix => copyWith(wordSpacing: 0);
}
...
textStyle.withZoomFix
...
TextStyle(...).withZoomFix
...
Theme.of(context).textTheme.bodyText1.withZoomFix
```

Related:
https://github.com/flutter/flutter/issues/63467
https://github.com/flutter/flutter/issues/64904#issuecomment-699039851
https://github.com/flutter/flutter/issues/65526

**Comment by Howe-Chan** [comment] 2021-08-10 02:55
Excuse me, is this problem solved? I also encountered this problem in version 2.2.3, using html as web-renderer. According to the solution given by @MichaelDark, it still hasn't solved the problem.

**Comment by mdebbar** [comment] 2021-08-16 21:53
There seems to be multiple issues reported here, which makes it confusing.

I tried the repro app and I'm not seeing any issues. I also tried rendering text with a tiny font size, and it's working fine.

I'm going to close this issue since it's not clear what the issue exactly is. If you are still experiencing a problem, please file a new github issue with details.

**Closed by mdebbar** 2021-08-16 21:53 UTC
Labels: severe: regression, e: device-specific, framework, a: internationalization, a: typography, platform-web, passed first triage, P4
