### ISSUE TITLE
iOS17 external keyboard, Chinese input method shows abnormal

### ISSUE THREAD

**Issue by jinliyuelong** [flutter/flutter#137932] opened 2023-11-06 10:01 UTC
flutter version
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.5.2 22G91 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.84.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

------

![Snipaste_2023-11-06_18-01-04](https://github.com/flutter/flutter/assets/16810284/21932cd3-1c97-40c9-a456-d55e6b0ebf50)

**Comment by jinliyuelong** [comment] 2023-11-06 10:01
iOS17 external keyboard, Chinese input method shows abnormalities, the first input result does not display

**Comment by danagbemava-nc** [comment] 2023-11-07 06:47
This is a duplicate of https://github.com/flutter/flutter/issues/132548 which has been fixed on the master channel. 

Per our triage policy, I'll be closing this since it has already been fixed. 

Thank you

**Closed by danagbemava-nc** 2023-11-07 06:47 UTC
Labels: in triage

**Comment by jinliyuelong** [comment] 2023-11-07 11:34
Which version is repaired

**Comment by jinliyuelong** [comment] 2023-11-07 11:40
I don't want to upgrade the version, is there any solution
