### ISSUE TITLE
video_player doesn't work on flutter v1.12.2, but works on 1.11.0

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#45056] opened 2019-11-17 08:40 UTC
maybe flutter texture is broken on v1.12.2

**Comment by janmoppel** [comment] 2019-11-18 09:38
Hello @wasabia !

Thank you for posting an issue.
Can you please also provide more information on the problem? Did video_player stop playing videos at all or it behaves unexpectedly? We need to know more information what's wrong exactly to reproduce the issue.

Thank you.

**Comment by davystrong** [comment] 2019-11-18 13:55
I'm facing this issue too. Don't know if it's exactly the same but I get `MissingPluginException(No implementation found for method init on channel flutter.io/videoPlayer)` when I attempt to call `..initialize()`. To be clear, it doesn't work at all, simply throws an exception, at least in my case.

**Comment by davystrong** [comment] 2019-11-18 14:16
This may be a more general problem. I tried disabling video_player and got the same issue with shared_preferences, seems to be similar to #44161. Someone suggested running `flutter upgrade` but that didn't work (while it did upgrade, I think I was on a more recent version already).

**Comment by davystrong** [comment] 2019-11-18 14:50
After reverting the steps on https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects this fixed. I guess I may have made a mistake when I was following the steps.

**Comment by iapicca** [comment] 2019-11-18 16:31
Hi @davystrong 
if I understand correctly your issue is about `embedding` 
more than `video_player` specifically;
if so please open a separate issue 
providing the information required in the template.
thank you

**Comment by davystrong** [comment] 2019-11-19 10:53
Ok! Thanks for your response.

**Comment by iapicca** [comment] 2019-12-12 16:00
Hi @wasabia @davystrong 
are you still experiencing this issue with the latest version of Flutter?
If so please provide your updated 
`flutter doctor -v` and `flutter run --verbose`.
thank you

**Comment by davystrong** [comment] 2019-12-12 20:33
Hi, I haven't tried this again. Since I reverted the for 1.12 and it worked, I just left it at that. I assume, as you said, it was some issue with embedding (or, at least, how I did it).

**Comment by iapicca** [comment] 2019-12-13 14:07
I'm closing this issue for now, 
if you will encounter difficulties with the latest stable (or other channels)
please open a new issue with the update `flutter doctor -v `and `flutter run --verbose`
or write here an I'll reopen the issue.
thank you

**Closed by iapicca** 2019-12-13 14:07 UTC
Labels: a: video, p: first party, p: video_player, plugin, waiting for customer response
