### ISSUE TITLE
VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso

### ISSUE THREAD

**Issue by lztbwlkj** [flutter/flutter#37603] opened 2019-08-05 07:38 UTC
## command

flutter upgrade --force

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:109:99)
#4      UpgradeCommandRunner.updatePackages (package:flutter_tools/src/commands/upgrade.dart:190:32)
<asynchronous suspension>
#5      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:90:11)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:47:32)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:94:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:463:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:129:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#27     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by blasten** [comment] 2019-08-06 17:38
cc @zanderso

**Comment by zanderso** [comment] 2019-08-23 20:22
@christopherfujino It looks like this problem happened before your re-work of the `upgrade` command, so I'm not sure if this could still happen. It looks like the latest commit date is only used to print a log message, but the failure of the git command could indicate that something has gone wrong with the upgrade. wdyt?

**Comment by christopherfujino** [comment] 2019-08-23 22:16
Yeah, this is https://github.com/flutter/flutter/issues/33890. I think that the flutter doctor output here was the re-entrant flutter doctor that `flutter upgrade` calls at the end. @lztbwlkj can you verify by re-running `flutter doctor -v`? If it runs successfully, then your install successfully upgraded before the exception started, and you are fine. If not, then this is a new (though related) issue.

**Comment by christopherfujino** [comment] 2019-10-15 23:45
Seeing another instance of this:
```
Thread 0 main thread CRASHEDVersionCheckError: VersionCheckError: Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: 
  | at _runSync | (version.dart:543 )
-- | -- | --
  | at FlutterVersion._latestGitCommitDate | (version.dart:143 )
  | at FlutterVersion.frameworkCommitDate | (version.dart:133 )
  | at FlutterVersion.toString | (version.dart:110 )
  | at VersionCommand.runCommand | (version.dart:117 )
  | at <asynchronous gap> | (async )
  | at FlutterCommand.verifyThenRunCommand | (flutter_command.dart:553 )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:71 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:552 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```
on beta 1.10.7, macOS 10.15.

We should definitely catch this in the doctor and have it be a failed validator, and maybe update the version check code (right now it just throws an exception if the git command fails).

**Comment by zanderso** [comment] 2019-10-16 17:22
@christopherfujino Sorry, I'm a bit confused. Is this not a dupe of https://github.com/flutter/flutter/issues/33890 then? If the validator fails, what would the corrective user action be?

**Comment by christopherfujino** [comment] 2019-10-17 23:54
Actually, I was right the first time, the original post IS a dupe of #33890. I will open a new issue for this happening during `VersionCommand`. The temporary action for a user who is on the master channel would be to switch to dev, to get signed binaries. If they're not on master (like the example I copy-pasted), I'm not sure...we probably still want a crash report.

**Comment by zanderso** [comment] 2019-11-19 22:57
This is coming up in crash logging as folks upgrade.

**Comment by jmagman** [comment] 2020-01-02 21:50
Report on stable: https://github.com/flutter/flutter/issues/47909

**Comment by jonahwilliams** [comment] 2020-02-17 02:15
Duplicate of https://github.com/flutter/flutter/issues/50902

If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue https://github.com/flutter/flutter/issues/50902

**Closed by jonahwilliams** 2020-02-17 02:15 UTC
Labels: severe: crash, tool
