### ISSUE TITLE
AppBarTheme data not properly initialized

### ISSUE THREAD

**Issue by Toorero** [flutter/flutter#118789] opened 2023-01-19 14:48 UTC
I think the `AppBarTheme` should not return null values. For instance take the following problem:

My them of my `MaterialApp` is set to:
```
ThemeData(
    primarySwatch: Colors.indigo,
    appBarTheme: const AppBarTheme()
)
```
My `AppBar` therefore has an indigo background colour[ according to the documentation of the `backgroundColor`](https://api.flutter.dev/flutter/material/AppBar/backgroundColor.html) of the `AppBar.`
But let's say I want something to be styled the same as the `AppBar`, e.g. my `DrawerHeader`:
```
DrawerHeader(
    decoration:
        BoxDecoration(color: AppBarTheme.of(context).backgroundColor),
    child: Text(
      "DrawerHeader",
      style: AppBarTheme.of(context).toolbarTextStyle,
    )
)
```
I would expect my `DrawerHeader` now to be styled similar to my `AppBar` but that's not the case since `AppBarTheme.of(context).backgroundColor` is null, and I didn't reimplement the logic behind the `backgroundColor` switch of the `AppBar`. So I would implement that logic to be the same as in the `AppBar`. If it changes through an update I have to reimplement it again and again, and it's still no guarantee that my other stuff is styled the same as the `AppBar`

**Comment by Toorero** [comment] 2023-01-19 14:52
So in summary please implement the logic of picking the colours if something isn't initialized in the `AppBarTheme` and not in the `AppBar` itself. This would require the `AppBarTheme` to know about the surrounding `ThemeData` though.

**Comment by rydmike** [comment] 2023-01-19 21:22
Hi @Toorero, not an official reply, just helping out.

The component themes, like `AppBarTheme` in `ThemeData` by default, and all default constructors of the component themes, like  `AppBarTheme()`, that you assigned to `ThemeData.appBarTheme` all have null property values by default. This is by design, there is therefore nothing to be found in your inherited widget lookups of the theme as far as any usable values go.

If you want a particular style in the `AppBarTheme`, that you can find and use with `AppBarTheme.of(context).backgroundColor` you need to actually define it with a value in ThemeData any such those properties.

By default widgets implement, fall back to their own built in defaults, that they use when its component theme and widget property values are null.

The widgets then in their build typically look up the widget tree and use `ThemeData.colorScheme` for default colors, and e.g. `ThemeData.textTheme` for text styles.

You can do the same in custom widgets, so that if it has a component theme with a none null property, it will use it, otherwise use a fallback to some preferred theme color or text style, or whatever property it is, to a value that is your own preferred default if it has not been defined by a built-in or even custom theme extension.

Example:

```dart
DrawerHeader(
    decoration:
        BoxDecoration(color: AppBarTheme.of(context).backgroundColor) ?? Theme.of(context).colorScheme.primary,
    child: Text(
      "DrawerHeader",
      style: AppBarTheme.of(context).toolbarTextStyle ?? Theme.of(context).textTheme.bodyMedium,
    )
)
```

Above, if you actually add an `AppBarTheme` with some values for the properties in question, you would get them, otherwise you get some selected values from the ambient theme, that always has default or defined values.

Thus if you theme your app or add component themes, that only happen in one place and your custom styled `DrawerHeader` follows those theme definitions. Actually assignment happens only in one place in your app. Hope this helps and clarifies the intended usage pattern in Flutter a bit.

BR
Mike

**Comment by darshankawar** [comment] 2023-01-20 09:19
Thanks @rydmike for your detailed insights on it.
@Toorero Please check above which should clarify your case.

**Comment by Toorero** [comment] 2023-01-21 20:06
> By default widgets implement, fall back to their own built-in defaults, that they use when its component theme and widget property values are null.

Yes I understand this, but I think that's not what should be.

As I already stated in my example it's somewhat unexpected and unintuitive.

I think fallbacks should rather be implemented in the getters of the `AppBarTheme` for example, so that they can't return null, so I can theme my stuff the same as the `AppBar`. Sure I can achieve the same by carefully studying the fall-backs in place for the `AppBar`, but there is always the risk of breaking and unnecessary code duplications. I think it's just a bad design and should be fixed.

**Comment by darshankawar** [comment] 2023-01-23 05:32
Thanks for the update and feedback. Treating this as a proposal to inherit the colors if the same isn't initialized in `AppBarTheme`.

**Comment by HansMuller** [comment] 2023-01-26 18:20
MIke's wonderfully [comprehensive explanation is correct](https://github.com/flutter/flutter/issues/118789#issuecomment-1397625888), AppBarTheme is working as in intended. The approach we've taken, where themes are a way to _override_ a component's defaults, rather than defining them (something that's typically not practical), was laid out about three years ago in flutter.dev/go/material-theme-system-updates.

**Closed by HansMuller** 2023-01-26 18:20 UTC
Labels: framework, f: material design, proposal
