### ISSUE TITLE
`flutter run` failed due to 'Permission denied' when replacing signature of 'Flutter.framework' in module-type Flutter project

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#40146] opened 2019-09-10 10:31 UTC
## Steps to Reproduce

1. Upgrade flutter to 1.9.1+hotfix.2
2. Run `flutter create -t module --org com.test test1`
3. Enter the `test1` project: `cd test1` 
4. Start the ios simulator
5. Run `flutter run`, everything works fun at this time.
6. Add the plugin `device_info` in pubspec.yaml:
```
dependencies:
  device_info: ^0.4.0
```
7. Run `flutter packages get`
8. Run `flutter run`... failed!

Or clone the test project: https://github.com/yrom/test1
1. git clone https://github.com/yrom/test1.git
2. cd test1
3. flutter packages get
4. flutter run

## Logs

```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              0.9s
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           5.3s
 └─Compiling, linking and signing...                         2.3s
Xcode build done.                                            9.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    mkdir -p /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter
    "- Modules" "/Users/yrom/Downloads/test1/.ios/Pods/../Flutter/engine/Flutter.framework"
    "/Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 94440045 bytes  received 120 bytes  62960110.00 bytes/sec
    total size is 94428117  speedup is 1.00
    Stripped /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter of architectures: armv7 arm64
    Code Signing /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements
    '/Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: replacing existing signature
    /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: Permission denied
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```

Check out the full verbose log file: https://raw.githubusercontent.com/yrom/test1/master/1.log 

Flutter doctor: 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/yrom/Library/flutter
    • Framework revision 2d2a1ffec9 (3 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

...

[✓] Connected device (1 available)
    • iPhone Xʀ • 00D207ED-8863-48FA-ACE7-061D13525B03 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

```

**Comment by yrom** [comment] 2019-09-10 12:08
After investigating,  i think the root cause was the `xcode_backend.sh` will mark the files under `Flutter.framework` tobe readonly.

For someone run into this issue, try modify the `$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh` for workaround:

``` diff
--- a/packages/flutter_tools/bin/xcode_backend.sh
+++ b/packages/flutter_tools/bin/xcode_backend.sh
@@ -141,7 +141,7 @@ BuildApp() {
     mkdir "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
-    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -exec chmod a-w "{}" \;
+    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -iname '.h' -exec chmod a-w "{}" \;
   else
     RunCommand rm -rf -- "${derived_dir}/Flutter.framework"
     RunCommand cp -r -- "${flutter_framework}" "${derived_dir}"

```

**Comment by mtallenca** [comment] 2019-09-10 13:05
I'm using a flutter module inside of existing app.  The upgrade instructions at https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project have the xcode_backend.sh build phase removed.

I did a similar command in the Pods/Target Support Files/Pods-TARGET/Pods-TARGET-frameworks.sh just above the /usr/bin/codesign command.

**Comment by jmagman** [comment] 2019-09-10 17:40
Duplicate of https://github.com/flutter/flutter/issues/39507.

**Comment by jmagman** [comment] 2019-09-11 03:29
If someone can `flutter update` (you must be on the master channel to use add-to-app modules!) and let me know if the issue is fixed, that would be awesome!

**Comment by jmagman** [comment] 2019-09-11 05:01
Reopening, @OHeroJ says this is still happening.

@OHeroJ Can you run `flutter clean` before you build to make sure the old read-only files are removed?

**Comment by OHeroJ** [comment] 2019-09-11 05:13
> Reopening, @OHeroJ says this is still happening.
> 
> @OHeroJ Can you run `flutter clean` before you build to make sure the old read-only files are removed?

I see execution flutter after the clean, `.ios` folder disappeared; run `flutter build ios` the `.ios` folder appeared(regenerate);

**Comment by GodRightHand** [comment] 2019-09-11 06:15
same problem

**Comment by egenvall** [comment] 2019-09-11 07:28
@jmagman 

I can confirm that it now works in master channel for me as well.

**Comment by GodRightHand** [comment] 2019-09-11 07:41
@yrom thank you very much ,it works for me

**Comment by django-d** [comment] 2019-09-11 08:38
> After investigating, i think the root cause was the `xcode_backend.sh` will mark the files under `Flutter.framework` tobe readonly.
> 
> For someone run into this issue, try modify the `$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh` for workaround:
> 
> ```diff
> --- a/packages/flutter_tools/bin/xcode_backend.sh
> +++ b/packages/flutter_tools/bin/xcode_backend.sh
> @@ -141,7 +141,7 @@ BuildApp() {
>      mkdir "${derived_dir}/engine"
>      RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
>      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
> -    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -exec chmod a-w "{}" \;
> +    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -iname '.h' -exec chmod a-w "{}" \;
>    else
>      RunCommand rm -rf -- "${derived_dir}/Flutter.framework"
>      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}"
> ```

yes!  i'm use flutter update to 1.9 , It works thanks

**Comment by yrom** [comment] 2019-09-11 10:51
> If someone can `flutter update` (you must be on the master channel to use add-to-app modules!) and let me know if the issue is fixed, that would be awesome!
@jmagman It works fine after checking master channel

**Comment by jmagman** [comment] 2019-09-11 16:57
So to recap:
1. Looks like this is working on the master channel.
```
$ flutter upgrade
$ flutter clean
$ flutter build ios
```
2. You must be on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) to use add-to-app Flutter module features.  That means, even though this is a severe issue, there will not be a stable hotfix.  See [documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro ) for caveats.

Thank you!

**Comment by Kila2** [comment] 2019-10-09 07:57
1.7.8-hotfix.4 has same issue. Will fix it?

**Comment by jmagman** [comment] 2019-10-09 15:08
> 1.7.8-hotfix.4 has same issue. Will fix it?

The fix is in v1.10.2.  You must be on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) to use add-to-app Flutter module features.  That means, even though this is a severe issue, there will not be a stable hotfix.  See [documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro ) for caveats.

**Comment by XingXiaoWu** [comment] 2019-10-15 07:31
same problem
```
flutter channel master
flutter upgrade
flutter clean
flutter build ios
```
But the problem is still not solved

![image](https://user-images.githubusercontent.com/22769131/66809869-bf7c3d00-ef60-11e9-98ff-885f670a1de5.png)
![image](https://user-images.githubusercontent.com/22769131/66809882-cacf6880-ef60-11e9-9277-632635c3893c.png)

**Comment by Kila2** [comment] 2019-10-15 07:35
@XingXiaoWu  you should patch it locally

**Comment by XingXiaoWu** [comment] 2019-10-15 07:43
> @XingXiaoWu 您应该在本地对其进行修补

Sorry, I don't understand what you mean.
How to patch?
Not implementing the four commands mentioned above?

**Comment by Kila2** [comment] 2019-10-15 07:44
@XingXiaoWu  see this 
> > After investigating, i think the root cause was the `xcode_backend.sh` will mark the files under `Flutter.framework` tobe readonly.
> > For someone run into this issue, try modify the `$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh` for workaround:
> > ```diff
> > --- a/packages/flutter_tools/bin/xcode_backend.sh
> > +++ b/packages/flutter_tools/bin/xcode_backend.sh
> > @@ -141,7 +141,7 @@ BuildApp() {
> >      mkdir "${derived_dir}/engine"
> >      RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
> >      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
> > -    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -exec chmod a-w "{}" \;
> > +    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -iname '.h' -exec chmod a-w "{}" \;
> >    else
> >      RunCommand rm -rf -- "${derived_dir}/Flutter.framework"
> >      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}"
> > ```
> 
> yes! i'm use flutter update to 1.9 , It works thanks

**Comment by XingXiaoWu** [comment] 2019-10-15 08:02
> @XingXiaoWu use this
> 
> > > After investigating, i think the root cause was the `xcode_backend.sh` will mark the files under `Flutter.framework` tobe readonly.
> > > For someone run into this issue, try modify the `$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh` for workaround:
> > > ```diff
> > > --- a/packages/flutter_tools/bin/xcode_backend.sh
> > > +++ b/packages/flutter_tools/bin/xcode_backend.sh
> > > @@ -141,7 +141,7 @@ BuildApp() {
> > >      mkdir "${derived_dir}/engine"
> > >      RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
> > >      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
> > > -    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -exec chmod a-w "{}" \;
> > > +    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -iname '.h' -exec chmod a-w "{}" \;
> > >    else
> > >      RunCommand rm -rf -- "${derived_dir}/Flutter.framework"
> > >      RunCommand cp -r -- "${flutter_framework}" "${derived_dir}"
> > > ```
> > 
> > 
> > yes! i'm use flutter update to 1.9 , It works thanks

thanks
But I didn't find this sentence.

![image](https://user-images.githubusercontent.com/22769131/66812238-18e66b00-ef65-11e9-9b6b-3663823c6995.png)
It seems that it has changed, and does not match the above sh

**Comment by Kila2** [comment] 2019-10-15 08:10
@XingXiaoWu 1.10.15 has fixed this issue. You can post a new issue with detail error info.

**Comment by XingXiaoWu** [comment] 2019-10-15 08:14
> @XingXiaoWu 1.10.15 has fixed this issue. You can post a new issue with detail error info.

thanks :)

**Comment by XingXiaoWu** [comment] 2019-10-15 09:08
> @XingXiaoWu 1.10.15已修复此问题。您可以发布带有详细错误信息的新期刊。

I know how to fix,thanks for your help
https://github.com/flutter/flutter/issues/42725

**Comment by lifenautjoe** [comment] 2019-10-25 15:54
Even having applied the patch posted above, the app still does not build with the error

```
    /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-iphoneos/R
    unner.app/Frameworks/Flutter.framework: replacing existing signature
    /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-iphoneos/R
    unner.app/Frameworks/Flutter.framework: Permission denied
```

The channel master is also currently broken when verifying iOS signatures, so changing to master is not an option either.

**Comment by lifenautjoe** [comment] 2019-10-25 16:07
Edit: I've managed to get it to work again by not using the patch mentioned above and instead using the changes from here

https://github.com/flutter/flutter/pull/40174

**Comment by jmagman** [comment] 2019-10-25 17:52
> The channel master is also currently broken when verifying iOS signatures, so changing to master is not an option either.

What issue is tracking that?

**Comment by lifenautjoe** [comment] 2019-10-25 17:57
@jmagman https://github.com/flutter/flutter/issues/43499

**Comment by devxpy** [comment] 2019-11-08 11:39
Just leaving this here, for anyone else who might have faced this. 

The [cached_network_image](https://pub.dev/packages/cached_network_image) plugin won't work on the stable channel. You must be on the master channel. (`>= 1.10.15`).

**Comment by xiubojin** [comment] 2019-11-13 09:24
@yrom thank you very much, it works for me

**Comment by vitor-gyant** [comment] 2019-11-18 14:19
@BondarenkoStas This is a blocker when releasing an iOS app. Wouldn't it make sense to include the simple fix as an hotfix. I mean, with the latest 1.9.1+hotfix.6 I cannot release the iOS app. The wiki states that this kind of issues tend to be fixed in the stable by releasing an hotfix. Was this considered internally ?

Thanks,

**Comment by jmagman** [comment] 2019-11-18 23:05
> This is a blocker when releasing an iOS app.

@vitor-gyant The only reports for this were for add-to-app iOS apps.  You must be on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) to use add-to-app Flutter module features. That means, even though this is a severe issue, there will not be a stable hotfix. See [documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro) for caveats.

If you are seeing this for a non-add-to-app iOS app, please file a new issue and we will investigate.

**Comment by vitor-gyant** [comment] 2019-11-18 23:44
@jmagman Thanks for the quick reply.

This is happening on both scenarios and my comment was not related to app2app experimental support.

The code in https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/bin/xcode_backend.sh at line 144 and 148 sets permissions incorrectly. 

You can check that https://github.com/flutter/flutter/pull/40174 applies changes on both code paths because they're required. 

If I'm correct, this should be fixed in a new hotfix IMHO.

**Comment by jmagman** [comment] 2019-11-19 01:39
> You can check that #40174 applies changes on both code paths because they're required.

I wrote it. 😉 

> This is happening on both scenarios and my comment was not related to app2app experimental support.

Interesting, we haven't seen any reports of this that weren't related to add-to-app (`-t module`).  I would have expected a lot more reports if it were blocking iOS app releases for an entire release cycle.  I'm not sure what's special about your environment.
You can see our policy related to hot fixes here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release

**Comment by elliott-io** [comment] 2019-11-19 01:57
This is a complete showstopper. I am having this problem as well. I've run flutter clean, then flutter build ios. These are the last few log lines with errors:

```
/path to.app/Frameworks/Flutter.framework: replacing existing
    signature
/path to.app/Frameworks/Flutter.framework: Permission denied
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
```

I'm on the master channel. Here is the output from `flutter doctor -v`

```
[✓] Flutter (Channel master, v1.12.5-pre.14, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.5-pre.14 at /Users/username/Documents/dev/flutter
    • Framework revision 6e10719dc5 (27 minutes ago), 2019-11-18 17:23:30 -0800
    • Engine revision 9832bc8f2e
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)

• No issues found!
```

Any recommendations?

**Comment by jmagman** [comment] 2019-11-19 02:54
Reopening based on master channel report.

**Comment by jmagman** [comment] 2019-11-19 03:05
@elliott-io 
1. Can we get the output of:
```
$ flutter build ios --verbose
$ la -la /Users/username/Documents/dev/flutter/bin/cache/artifacts/engine/ios/Flutter.framework/Flutter 
$ ls -la ios/Flutter/Flutter.framework 
$ ls -la build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework 
```
2. If you are using plugins, paste the contents of `ios/Podfile`

**Comment by elliott-io** [comment] 2019-11-19 03:36
@jmagman Thanks for the quick response. Turns out my **Apple provisioning profile needed to be re-downloaded** (it was showing as invalid in the Apple Developer Portal, though it was set up to automatically be managed in Xcode). I can build now. 
I am using several plugins. Do you still want this output? It's quite long...

**Comment by vitor-gyant** [comment] 2019-11-19 10:08
@jmagman Thanks again for providing more information. I think I've found the issue and it was caused by switching flutter channels. My previous channel was master and I've switched to stable. It seems that the Podfile inside app/ios is not recreated after switching to stable. I'm not sure if you do expect it to be generated automatically by the flutter build command when it already exists but was created in a different channel. 

I've delete the Podfile and flutter build generated it again which solves the signing issue. 

Apologies for the noise but it was not clear for me until further debugging. Nevertheless, if you can clarify if the Podfile is expected to be re-generated after switching channel it would be great.

BR,

**Comment by jmagman** [comment] 2019-11-19 19:06
@elliott-io I don't think we need the output.  That's such an unfortunately vague error for a bad provisioning profile.  I would have hoped for something clearer from Xcode about the code signing failing, not that the there's no permission to write the file.  I created https://github.com/flutter/flutter/issues/45184 but I'm not sure how to really detect that without better errors/codes from xcodebuild.

@vitor-gyant Are you saying you generated the Podfile on the stable channel works but the one generated on master doesn't?  If so, could you file a new issue so we can investigate further?

The Podfile is not recreated.  There are pros and cons to this behavior, and you can see more at https://github.com/flutter/flutter/issues/9827 and a little bit about those files needing to be recreated at https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-project-files.

I'm going to close this again since the file permission issue still seems okay on master, barring code signing issues.

**Comment by jmagman** [comment] 2019-11-19 19:30
Another report here: https://github.com/flutter/flutter/issues/39507#issuecomment-555340755 from @mleonhard.

I suspect other issues (like @elliott-io's provisioning profile problem) are getting obscured by this error because that's the first place the codesinging issue is manifesting.  It's becoming more trouble than it's worth, I'm going to remove that `chmod`.

**Comment by jmagman** [comment] 2019-11-19 19:36
PR at https://github.com/flutter/flutter/pull/45189

**Closed** 2019-11-19 23:13 UTC
Labels: t: xcode, tool

**Comment by vitor-gyant** [comment] 2019-11-20 11:53
@jmagman Do you still need me to file a new issue now that chmod is going to be removed ?

**Comment by jmagman** [comment] 2019-11-20 18:59
> @jmagman Do you still need me to file a new issue now that chmod is going to be removed ?

@vitor-gyant If the Podfile you generated on the stable channel works but the one generated on master doesn't, a new issue would be very helpful.

**Comment by ivanesi** [comment] 2019-12-05 08:48
The same error for our app on stable channel.
```
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```
 
On master channel we have no this error and can build the app.

**Comment by endrelovas** [comment] 2019-12-13 11:15
Posted a workaround here: #39507

**Comment by jmagman** [comment] 2019-12-17 19:23
> The same error for our app on stable channel.
> 
> ```
> Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
> Engine • revision b863200c37
> Tools • Dart 2.5.0
> ```
> 
> On master channel we have no this error and can build the app.

@ivanesi The fix is on stable 1.12.13 https://flutter.dev/docs/development/tools/sdk/releases?tab=macos.  Try running `flutter upgrade`.

**Comment by darren-f5s** [comment] 2019-12-18 10:12
Upgrading to master is NOT a valid solution, as master does not deploy to Huawei devices properly. The only way is to use 1.9.1 until THAT is fixed.

**Comment by jmagman** [comment] 2019-12-18 19:09
> Upgrading to master is NOT a valid solution, as master does not deploy to Huawei devices properly. The only way is to use 1.9.1 until THAT is fixed.

https://github.com/flutter/flutter/pull/45189 is on all channels, not just master.  If you have to stay on 1.9.1, you can manually patch your Flutter SDK's `packages/flutter_tools/bin/xcode_backend.sh` to https://github.com/flutter/flutter/blob/v1.12.13-hotfixes/packages/flutter_tools/bin/xcode_backend.sh.  The Flutter SDK is a git repo, and Flutter channels are branches.  To reset, make sure you run `git checkout .` from your SDK folder before you `flutter channel` or `flutter upgrade` again (you've voided your easy-upgrade warranty at that point)

**Comment by TahaAli07** [comment] 2020-07-01 14:23
Moved from v1.9.1+hotfix.6  to  v1.11.0 .

To change flutter version to 1.11.0 just run 

`flutter version v1.11.0`

This fixed this issue for me , tried all other other highly voted solutions but none worked.

**Comment by pkmangukiya** [comment] 2021-01-16 09:11
To complete solve this! go here:- https://stackoverflow.com/a/65473410/10563627
