### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by jaybayron9** [flutter/flutter#158973] opened 2024-11-15 03:43 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1771:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1783:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1733:14)
#4      FlutterVmService.createDevFS (package:flutter_tools/src/vmservice.dart:1042:20)
#5      DevFS.create (package:flutter_tools/src/devfs.dart:512:61)
#6      FlutterDevice.setupDevFS (package:flutter_tools/src/resident_runner.dart:391:19)
#7      HotRunner._initDevFS (package:flutter_tools/src/run_hot.dart:487:23)
#8      HotRunner.attach (package:flutter_tools/src/run_hot.dart:276:41)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:808:27)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.1, on
    macOS 15.1 24B83 darwin-arm64,
    locale en-PH)
    [32m•[39m Flutter version 3.19.1 on channel
      stable at
      /Users/cal4careit-ph/development/
      flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutte
      r.git
    [32m•[39m Framework revision abb292a07e (9
      months ago), 2024-02-20 14:35:05
      -0800
    [32m•[39m Engine revision 04817c99c9
    [32m•[39m Dart version 3.3.0
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Android toolchain - develop for
    Android devices (Android SDK
    version 34.0.0)
    [32m•[39m Android SDK at
      /Users/cal4careit-ph/Library/Andr
      oid/sdk
    [32m•[39m Platform android-34, build-tools
      34.0.0
    [32m•[39m Java binary at:
      /Applications/Android
      Studio.app/Contents/jbr/Contents/
      Home/bin/java
    [32m•[39m Java version OpenJDK Runtime
      Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS
    (Xcode 16.1)
    [32m•[39m Xcode at
      /Applications/Xcode.app/Contents/
      Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google
      Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at
      /Applications/Android
      Studio.app/Contents
    [32m•[39m Flutter plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/plu
      gin/9212-flutter
    [32m•[39m Dart plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/plu
      gin/6351-dart
    [32m•[39m Java version OpenJDK Runtime
      Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /Applications/Visual
      Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 16 Plus (mobile) •
      F72E4FAE-E3B4-4D96-A865-8099F3716
      8DE • ios            •
      com.apple.CoreSimulator.SimRuntim
      e.iOS-18-1 (simulator)
    [32m•[39m macOS (desktop)         • macos
      • darwin-arm64   • macOS 15.1
      24B83 darwin-arm64
    [32m•[39m Chrome (web)            • chrome
      • web-javascript • Google Chrome
      131.0.6778.69

[32m[✓][39m Network resources
    [32m•[39m All expected network resources
      are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: abb292a07e20d696c4568099f918f6c5f330e6b0
### Plugins
audio_session-0.1.21
just_audio-0.9.41
just_audio_web-0.4.13
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pusher_channels_flutter-2.2.1
sqflite-2.3.3+1
url_launcher-6.3.1
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.4.14
video_player_avfoundation-2.6.2
video_player_web-2.3.2
wakelock_plus-1.2.8
webview_flutter-4.8.0
webview_flutter_android-3.16.3
webview_flutter_wkwebview-3.14.0

**Comment by danagbemava-nc** [comment] 2024-11-15 09:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by danagbemava-nc** 2024-11-15 09:41 UTC
Labels: in triage
