### ISSUE TITLE
DatePicker fails to render in gallery app

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4557] opened 2016-06-14 18:35 UTC
## Steps to Reproduce

Run the gallery app, and try to show the date picker component

## Logs and Crash Reports

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderVirtualViewport does not support returning intrinsic dimensions.
Calculating the intrinsic dimensions would require walking the entire child list, which cannot
reliably and efficiently be done for render objects that potentially generate their child list
during layout.
When the exception was thrown, this was the stack:
#0      RenderVirtualViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:398:9)
#1      RenderVirtualViewport.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:396:12)
#2      RenderList._computeIntrinsicHeight (package:flutter/src/rendering/list.dart:132:16)
#3      RenderList.computeMaxIntrinsicHeight (package:flutter/src/rendering/list.dart:144:12)
#4      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#6      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#7      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:762:12)
#8      RenderProxyBox.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:68:20)
#9      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#11     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#12     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:762:12)
#13     RenderProxyBox.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:68:20)
#14     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#15     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#16     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#17     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:762:12)
#18     RenderStack.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/stack.dart:305:62)
#19     RenderStack._getIntrinsicDimension (package:flutter/src/rendering/stack.dart:281:54)
#20     RenderStack.computeMaxIntrinsicHeight (package:flutter/src/rendering/stack.dart:305:12)
#21     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#22     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#23     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#24     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:762:12)
#25     RenderProxyBox.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:68:20)
#26     RenderConstrainedBox.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:223:58)
#27     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#28     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#29     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#30     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:762:12)
#31     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:210:34)
#32     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:251:12)
#33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#34     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#36     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#37     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:127:20)
#38     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#39     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#40     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#41     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#42     RenderBlock.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/block.dart:198:66)
#43     RenderBlock._getIntrinsicCrossAxis (package:flutter/src/rendering/block.dart:164:42)
#44     RenderBlock.computeMaxIntrinsicWidth (package:flutter/src/rendering/block.dart:198:16)
#45     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#46     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#47     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#48     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#49     RenderViewport.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:248:20)
#50     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#51     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#52     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#53     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#54     RenderProxyBox.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:54:20)
#55     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#56     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#57     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#58     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#59     RenderProxyBox.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:54:20)
#60     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:535:23)
#61     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:259)
#62     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:533:41)
#63     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:660:12)
#64     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:579:36)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#66     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#68     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#70     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#72     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#74     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:232:13)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#76     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:160:11)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#78     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:336:13)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#80     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#82     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#84     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#86     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1459:21)
#88     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:328:15)
#89     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1337:21)
#90     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:822:18)
#91     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:152:19)
#92     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:205:21)
#93     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:144:5)
#94     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:428:15)
#95     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:388:7)
#96     _beginFrame (file:///Users/tvolkert/project/flutter/engine/src/out/ios_debug_sim_unopt/gen/sky/bindings/dart_ui/hooks.dart:48)
The following RenderObject was being processed when the exception was fired:
  RenderIntrinsicWidth relayoutBoundary=up7 NEEDS-LAYOUT
This RenderObject had the following creator information:
  IntrinsicWidth ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey ink
  renderer] ← NotificationListener<LayoutChangedNotification> ← ClipRRect ← DecoratedBox ← Container
  ← DecoratedBox ← Container ← ⋯
This RenderObject had the following descendants (showing up to depth 5):
  RenderSemanticsGestureHandler NEEDS-LAYOUT
    RenderPointerListener NEEDS-LAYOUT
      RenderViewport NEEDS-LAYOUT
        RenderBlock NEEDS-LAYOUT
          RenderPadding NEEDS-LAYOUT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 267 pos 12: 'child.hasSize' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 812 pos 12: 'hasSize' is not true.
```

**Comment by HansMuller** [comment] 2016-06-14 18:39
Duplicate of #4538

**Closed** 2016-06-14 18:47 UTC
Labels: affects: date picker, affects: material design, customer: gallery, ⚠ bug (regression)
