### ISSUE TITLE
TestWidgetsFlutterBinding setSurfaceSize does not change values returned from MediaQuery.of(context).size

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#25577] opened 2018-12-19 20:24 UTC
We are trying to write Widget tests that test our tablet specific layouts.

`TestWidgetsFlutterBinding` `setSurfaceSize` seems to be the documented way to specify a surface size for a Widget test to run on. After setting a size with `setSurfaceSize` and using `MediaQuery.of(context).size` in our Widgets (to determine what type of layout to use), the size returned is the default size in Widgets tests (`Size(800.0, 600.0)`) instead of the size specified.

## Steps to Reproduce
1. Write a widget that does different things for device widths > x.
2. Write a widget test for that widget, using `TestWidgetsFlutterBinding` `setSurfaceSize` to specify an appropriate height and a width of x + 1.
3. Execute the test. Observe that the widget is not doing its width > x things.
4. Log or debug to view `MediaQuery.of(context).size`, and see that its `Size(800.0, 600.0)` instead of specified size.

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-CA)
    • Flutter version 1.0.0 at /Users/jrai/dev/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • iPad       • 8392d97b7b35a9c3e3bdfade51f897404ec4d112 • ios • iOS 12.0.1
    • iPad Air 2 • 5AD11829-1F07-439E-BA80-70CFDDB4B2A0     • ios • iOS 12.1 (simulator)

• No issues found!

```

**Comment by zoechi** [comment] 2018-12-20 11:35
You can provide your own `MediaQuery` with custom `MediaQueryData`.

**Comment by zoechi** [comment] 2018-12-20 11:37
Duplicate of #12994

**Closed by zoechi** 2018-12-20 11:37 UTC
