### ISSUE TITLE
[yaml] move dimensions from under properties field to under dimensions field

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#103557] opened 2022-05-12 00:44 UTC
context: https://github.com/flutter/cocoon/pull/1839#discussion_r870792041

Currently in ci.yaml, swarming dimensions such as 'cpu' is currently supplied under 'properties' field. Once https://github.com/flutter/cocoon/pull/1839 and https://flutter-review.googlesource.com/c/infra/+/29880 get merged in, we would have support for dimension fields in ci.yaml. And we would like to remove the logic of supporting dimensions under 'properties' field.

**Comment by godofredoc** [comment] 2022-10-25 18:51
Closing as duplicate of https://github.com/flutter/flutter/issues/113732

**Closed by godofredoc** 2022-10-25 18:51 UTC
Labels: team: infra, passed secondary triage
