### ISSUE TITLE
Problem with displaying emojis when attempting to layout the text painter with partially trimmed emoji.

### ISSUE THREAD

**Issue by LokeshPalani** [flutter/flutter#142037] opened 2024-01-23 09:30 UTC
### Steps to reproduce

1. Use the text in between emojis.
2. Display the text in the Container Widget using TextPainter.
3. An exception was thrown when running the sample.

### Expected results

The text should be displayed with partially trimmed emoji.

### Actual results

```
════════ Exception caught by painting library ══════════════════════════════════
The following ArgumentError was thrown while building a TextSpan:
Invalid argument(s): string is not well-formed UTF-16

When the exception was thrown, this was the stack:
#0      _NativeParagraphBuilder.addText (dart:ui/text.dart:3484:7)
#1      TextSpan.build (package:flutter/src/painting/text_span.dart:281:17)
#2      TextPainter._createParagraph (package:flutter/src/painting/text_painter.dart:1070:10)
#3      TextPainter.layout (package:flutter/src/painting/text_painter.dart:1125:64)
#4      _MyTextWidgetState.displayText (package:flutter_framework/main.dart:51:19)
#5      _MyTextWidgetState.initState (package:flutter_framework/main.dart:38:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602:55)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
...     Normal element mounting (28 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#36     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#37     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (324 frames)
#361    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#362    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#363    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (479 frames)
#842    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#843    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#844    _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:289:16)
#845    _RawViewElement.mount (package:flutter/src/widgets/view.dart:312:5)
...     Normal element mounting (7 frames)
#852    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#853    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#854    RootElement._rebuild (package:flutter/src/widgets/binding.dart:1334:16)
#855    RootElement.mount (package:flutter/src/widgets/binding.dart:1303:5)
#856    RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1256:18)
#857    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#858    RootWidget.attach (package:flutter/src/widgets/binding.dart:1255:13)
#859    WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1083:27)
#860    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1065:5)
#861    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1051:7)
#865    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by painting library ══════════════════════════════════
Invalid argument(s): string is not well-formed UTF-16
════════════════════════════════════════════════════════════════════════════════
```

### Code sample

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyTextWidget(),
        ),
      ),
    );
  }
}

class MyTextWidget extends StatefulWidget {
  const MyTextWidget({Key? key}) : super(key: key);

  @override
  _MyTextWidgetState createState() => _MyTextWidgetState();
}

class _MyTextWidgetState extends State<MyTextWidget> {
  String originalText =
      '🍕 | A long name from index | 🚀😍😜😉😊👌✨😃😂🤣❤😒😘';

  String displayedText = '';

  @override
  void initState() {
    super.initState();
    displayText();
  }

  void displayText() {
    int textLength = originalText.length;

    for (int i = textLength - 1; i >= 0; --i) {
      String label = '${originalText.substring(0, i)}...';

      final TextPainter textPainter = TextPainter(
          textAlign: TextAlign.center,
          textDirection: TextDirection.ltr,
          text: TextSpan(text: label, style: const TextStyle(fontSize: 12)));
      textPainter.layout();
      displayedText = label;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 20,
      color: Colors.yellow.shade100,
      alignment: Alignment.center,
      child: Text(
        displayedText,
        style: const TextStyle(fontSize: 12),
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Doctor output</summary>

```
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.7 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (12 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\LokeshPalani\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.8.34408.163
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.85.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.225
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.144

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.4)
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources
```
</details>

**Comment by huycozy** [comment] 2024-01-23 11:13
Hi @LokeshPalani 
Which platform are you seeing this? I checked this on Web and macOS but there is no crash, emoji also is not rendering as well.

<details>
<summary>Demo</summary>

![Screenshot 2024-01-23 at 18 12 04](https://github.com/flutter/flutter/assets/104349824/25b82d94-4034-46b8-b4be-29249601b2fc)
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (27 hours ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.19.0-9.0.pre.50, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.0-9.0.pre.50 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dea6b994e (10 hours ago), 2024-01-21 12:01:23 -0500
    • Engine revision a7b207d5a1
    • Dart version 3.4.0 (build 3.4.0-52.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by btrautmann** [comment] 2024-01-23 16:44
I'm able to reproduce this easily on an iPhone 13 mini simulator running iOS 17.0

https://github.com/flutter/flutter/assets/8343465/781cd392-b659-4dae-86bf-c24c7fbc29bf

```sh
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by huycozy** [comment] 2024-01-24 03:16
Thank @btrautmann, I can reproduce this issue now on iOS and Android. It also occurs on macOS (app) but not on Web.

| Android | iOS | MacOS | Web |
| --------------- | --------------- | --------------- | --------------- | 
❗ | ❗ | ❗ | ✅ 

✅: No Issue ❗: Issue reproduced

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (27 hours ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.19.0-9.0.pre.50, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.0-9.0.pre.50 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dea6b994e (10 hours ago), 2024-01-21 12:01:23 -0500
    • Engine revision a7b207d5a1
    • Dart version 3.4.0 (build 3.4.0-52.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Rusino** [comment] 2024-01-25 16:57
Looking at the code sample:
    for (int i = textLength - 1; i >= 0; --i) {
      String label = '${originalText.substring(0, i)}...';
You are adding a utf16 codepoints to the label from the originalText which is in general incorrect. Your originalText contains emojis that consist of more than one utf16 codepoint. When you break your text in the middle of the emoji you will get this "string is not well-formed..." error.
For instance, Emoji "🍕" is represented as two utf16 codepoints D83C DF55 . If you break it in the middle it will be incorrect.
If you really want to do something like this you should iterate your string by graphemes, not by utf16 codepoints. But it's only available on the lower lever than Flutter.
(Or Flutter could check the text for being Unicode correct and change all incorrect codepoints with replacement characters?)

**Comment by btrautmann** [comment] 2024-01-30 15:28
Thanks @Rusino! It seems like https://pub.dev/packages/characters was developed just for this purpose.

For context, the originating issue that spawned this one was https://github.com/syncfusion/flutter-widgets/issues/1611.

I _think_ the charts library is truncating user-provided text somewhere. Am I correct in saying that the charts library should use `characters` to do this, rather than methods invoked directly on a `String`?

@LokeshPalani if the above _is_ correct, is that doable on your end?

@Rusino please feel free to correct anything from the above. **Additionally,** I toyed with an approach that _removed_ emojis from the `String` being provided to the charting library so the truncation could be guaranteed to succeed. However my logic for determining if a grapheme cluster (provided by `package:characters`) represented an emoji fell short and didn't always work. Swift provides an `isEmoji` [function](https://developer.apple.com/documentation/swift/unicode/scalar/properties-swift.struct/isemoji), is this something Flutter/dart could support?

**Comment by Rusino** [comment] 2024-01-30 16:23
> I _think_ the charts library is truncating user-provided text somewhere (as done in the OP of this issue). Am I correct in saying that the charts library should use `characters` to do this, rather than methods invoked directly on a `String`?
> 
From what I see  https://pub.dev/packages/characters is the right choice.

**Comment by btrautmann** [comment] 2024-01-30 16:41
@LokeshPalani since `package:characters` is already exported by Flutter (introduced in https://github.com/flutter/flutter/pull/59620), I think this ticket can probably be closed and we can follow up in the one specific to syncfusion charts. I think the correct course of action here is to truncate based on grapheme clusters and not manually manipulate the `String`.

**Closed** 2024-01-30 23:55 UTC
Labels: framework, a: typography, a: error message, has reproducible steps, team-framework, found in release: 3.16, found in release: 3.19
