### ISSUE TITLE
Flutter pub get still fails under corporate proxy

### ISSUE THREAD

**Issue by BestAndroidTeam** [flutter/flutter#51459] opened 2020-02-26 09:26 UTC
## Steps to Reproduce

1. Install flutter on Windows.
2. Create a flutter project using "flutter create hello" (This command wile hang forever).
3. Stop the above command.
4. Run "flutter pub get -v" while under corporate proxy.

## Logs

```
[...]

C:\Users\A754885\Home\Softwares\FlutterSDK\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-C:\Users\A754885\Home\Softwares\FlutterSDK\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[ +777 ms] FINE: Pub 2.7.0
[   +4 ms] IO  : Spawning "cmd /c ver" in C:\Users\A754885\Home\IntercoWorkspace\audb\.
[  +69 ms] IO  : Finished ver. Exit code 0.
[   +1 ms]     | stdout:
[   +1 ms]     | |
[   +1 ms]     | | Microsoft Windows [version 10.0.18362.657]
[        ]     | Nothing output on stderr.
[  +74 ms] MSG : Resolving dependencies...
[  +12 ms] SLVR: fact: audb is 1.0.0+1
[   +4 ms] SLVR: derived: audb
[  +38 ms] SLVR: fact: audb depends on flutter any from sdk
[   +1 ms] SLVR: fact: audb depends on cupertino_icons ^0.1.2
[   +2 ms] SLVR: fact: audb depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting audb
[   +1 ms] SLVR:   derived: flutter_test any from sdk
[   +1 ms] SLVR:   derived: cupertino_icons ^0.1.2
[   +1 ms] SLVR:   derived: flutter any from sdk
[  +17 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/cupertino_icons.
[  +27 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: windows
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: 4A44FDCA-5162-4E03-B282-EF5ABED964ED
[        ]     | X-Pub-Environment: flutter_cli:get
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.7.0
[+21089 ms] IO  : HTTP error:
[   +2 ms]     | SocketException: OS Error: Le délai de temporisation de sémaphore a expiré.
[   +2 ms]     | , errno = 121, address = pub.dartlang.org, port = 62612
[   +1 ms]     |
[   +1 ms]     | dart:_http                                         _HttpClient.openUrl
[   +3 ms]     | package:http/src/io_client.dart 33:36              IOClient.send
[   +3 ms]     | package:pub/src/http.dart 68:39                    _PubHttpClient.send
[   +2 ms]     | package:http_retry/http_retry.dart 97:33           RetryClient.send
[   +3 ms]     | package:pub/src/http.dart 194:43                   _ThrowingClient.send
[   +5 ms]     | package:http_throttle/http_throttle.dart 33:31     ThrottleClient.send
[   +2 ms]     | ===== asynchronous gap ===========================
[   +6 ms]     | dart:async                                         _asyncThenWrapperHelper
[   +1 ms]     | package:http_throttle/http_throttle.dart           ThrottleClient.send
[   +6 ms]     | package:http/src/base_client.dart 169:38           BaseClient._sendUnstreamed
[   +1 ms]     | package:http/src/base_client.dart 32:7             BaseClient.get
[   +2 ms]     | package:http/src/base_client.dart 117:12           BaseClient.read
[   +5 ms]     | package:pub/src/source/hosted.dart 160:31          BoundHostedSource.doGetVersions
[   +1 ms]     | package:pub/src/source.dart 167:12                 BoundSource.getVersions
[   +5 ms]     | package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
[   +5 ms]     | dart:async                                         runZoned
[   +4 ms]     | package:pub/src/http.dart 272:10                   withDependencyType
[   +1 ms]     | package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
[   +1 ms]     | dart:async                                         new Future.sync
[   +2 ms]     | package:async/src/async_memoizer.dart 43:42        AsyncMemoizer.runOnce
[   +2 ms]     | package:pub/src/solver/package_lister.dart 74:58   PackageLister._versions
[   +4 ms]     | package:pub/src/solver/package_lister.dart 111:21  PackageLister.countVersions
[   +2 ms]     | package:pub/src/solver/version_solver.dart 354:44  VersionSolver._choosePackageVersion.<fn>
[   +2 ms]     | package:pub/src/utils.dart 301:39                  minByAsync
[   +4 ms]     | ===== asynchronous gap ===========================
[   +1 ms]     | dart:async                                         _asyncThenWrapperHelper
[   +1 ms]     | package:pub/src/utils.dart                         minByAsync
[   +5 ms]     | package:pub/src/solver/version_solver.dart 350:25  VersionSolver._choosePackageVersion
[   +2 ms]     | package:pub/src/solver/version_solver.dart 97:22   VersionSolver.solve
[   +1 ms]     | ===== asynchronous gap ===========================
[   +1 ms]     | dart:async                                         _asyncThenWrapperHelper
[   +1 ms]     | package:pub/src/solver/version_solver.dart         VersionSolver.solve
[   +2 ms]     | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
[   +5 ms]     | package:pub/src/log.dart 378:18                    progress
[   +1 ms]     | package:pub/src/solver.dart 32:10                  resolveVersions
[   +3 ms]     | package:pub/src/entrypoint.dart 217:24             Entrypoint.acquireDependencies
[   +4 ms]     | package:pub/src/command/get.dart 41:23             GetCommand.run
[   +1 ms]     | package:args/command_runner.dart 197:27            CommandRunner.runCommand
[   +1 ms]     | package:pub/src/command_runner.dart 171:39         PubCommandRunner.runCommand.<fn>
[   +7 ms]     | dart:async                                         new Future.sync
[   +2 ms]     | package:pub/src/utils.dart 109:12                  captureErrors.<fn>
[   +7 ms]     | package:stack_trace                                Chain.capture
[   +2 ms]     | package:pub/src/utils.dart 122:11                  captureErrors
[   +6 ms]     | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand

[...]
```

## When running flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [version 10.0.18362.657], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

## More info :

I'm on Windows 10.

I did set these env variables according to https://dart.dev/tools/pub/troubleshoot :

* HTTP_PROXY
* HTTPS_PROXY
* NO_PROXY

I can access https://pub.dev/ from my browser, and with GET using postman.

**Comment by aymericl** [comment] 2020-02-26 09:45
I have the same problem, someone has a solution ?

Thanks

**Comment by rahul-bavaliya** [comment] 2020-02-26 09:47
I also get same issue, how to resolve it in windows...!!!

**Comment by iapicca** [comment] 2020-02-26 09:54
Hi @BestAndroidTeam 
if the corporate proxy need authentication you might need self signed certificate
[[1](https://stackoverflow.com/questions/51883151/flutter-app-behind-corporate-firewall-throws-tls-error-during-packages-get), [2](https://github.com/flutter/flutter/issues/17285)]
Do the links above help?
thank you

**Comment by BestAndroidTeam** [comment] 2020-02-26 10:36
Hi @iapicca and thank you for your answer! As far as I know the proxy is using a self-signed certificate. Just in case I tried to export it and to set DART_VM_OPTIONS but it didn't work!
Anyway I don't think it's an authetication problem. I don't have any TLS/authetication error, I have a timeout!

Translating 
```
[   +2 ms]     | SocketException: OS Error: Le délai de temporisation de sémaphore a expiré.
[   +2 ms]     | , errno = 121, address = pub.dartlang.org, port = 62612
```
Gives
```
[   +2 ms]     | SocketException: OS Error: Semaphore timeout has expired.
[   +2 ms]     | , errno = 121, address = pub.dartlang.org, port = 62612
```

**Comment by iapicca** [comment] 2020-02-26 10:45
Thank you for the clarification @BestAndroidTeam

**Comment by jonahwilliams** [comment] 2020-07-21 22:03
@jonasfj are there proxy settings we could document for pub?

**Comment by jonasfj** [comment] 2020-07-21 22:24
We have documented proxy options here:
https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

But I don't think we have well-supported solution for self-signed certificates.
My intuition is that some users get the `DART_VM_OPTIONS` working, and some don't.

Feature request for self-signed certificates in https://github.com/dart-lang/pub/issues/2283
(Though it's not clear that this is what is wrong, it's very plausible, but unclear).

**Comment by jonahwilliams** [comment] 2020-07-21 22:33
I'm going to mark as a duplicate of https://github.com/flutter/flutter/issues/56607, with some indication it may not be sufficient.

**Closed by jonahwilliams** 2020-07-21 22:33 UTC
Labels: dependency: dart, tool

**Comment by tallinn1960** [comment] 2021-06-02 16:10
> We have documented proxy options here:
> https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall
> 

The proxy settings given there are wrong for Linux.

flutter pub get ignores http(s)_proxy and uses HTTP(S)_PROXY instead.
