### ISSUE TITLE
Engine rolls blocked on failing customer test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#68613] opened 2020-10-20 15:03 UTC
On the roll attempt here https://github.com/flutter/flutter/pull/68563, there are customer test failures in rainbowmonkey: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865945922589989888/+/steps/prepare_environment/0/steps/Customer_testing/0/steps/customer_testing/0/stdout?format=raw.

e.g.
```
00:03 +0: loading /b/s/w/ir/tmp/t/flutter_customer_testing.rainbowmonkey.GUWWCS/tests/test/logic/cruise_model_test.dart
| ../lib/src/progress.dart:375:11: Error: Superclass has no method named 'addListener'.
|     super.addListener(listener);
|           ^^^^^^^^^^^
| ../lib/src/progress.dart:380:11: Error: Superclass has no method named 'removeListener'.
|     super.removeListener(listener);
|           ^^^^^^^^^^^^^^
```
Maybe https://github.com/flutter/flutter/pull/67359 is related?

@Hixie @gspencergoog @goderbauer

**Comment by zanderso** [comment] 2020-10-20 15:03
Marking P0 since this is blocking sound null safety work.

**Comment by zanderso** [comment] 2020-10-20 15:50
This may be addressed by https://dart-review.googlesource.com/c/sdk/+/168487

**Comment by jason-simmons** [comment] 2020-10-20 16:17
Confirmed that this test works if I roll Dart forward to https://github.com/dart-lang/sdk/commit/5f18d498a069b4fd5cf4481065a4ed32770c7e3b

**Comment by goderbauer** [comment] 2020-10-20 23:07
Looks like this was rolled in with https://github.com/flutter/flutter/pull/68651. I am closing this.

**Closed by goderbauer** 2020-10-20 23:07 UTC
Labels: P0, engine, framework, team
