### ISSUE TITLE
Flutter for arm64 processors

### ISSUE THREAD

**Issue by afzl-wtu** [flutter/flutter#96117] opened 2022-01-04 15:20 UTC
With growing instances of arm64 processors specially ampere and resberry pi, Please make flutter available for arm64 platforms as well. I am running ubuntu on arm64 oracle cloud instance.

**Comment by bernaferrari** [comment] 2022-01-04 16:48
Flutter doesn't even fully support macOS for now, but it is coming soon.

**Comment by stuartmorgan** [comment] 2022-01-04 17:49
This is a duplicate of either https://github.com/flutter/flutter/issues/75864 or https://github.com/flutter/flutter/issues/60678 depending on what exactly you are requesting.

**Closed by stuartmorgan** 2022-01-04 17:49 UTC

**Comment by christopherfujino** [comment] 2022-01-25 21:30
> With growing instances of arm64 processors specially ampere and resberry pi, Please make flutter available for arm64 platforms as well. I am running ubuntu on arm64 oracle cloud instance.

So it's not published on the website, but you can actually use the Flutter SDK on arm64 today if you clone the repo on it.
