### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by cyberail** [flutter/flutter#156217] opened 2024-10-04 11:31 UTC
## Command
```sh
flutter run --machine --start-paused -d 00008020-000838990E01002E --devtools-server-address http://127.0.0.1:9100/ --target /Users/macintoshi/Desktop/flutter/super_app/host/lib/main_staging.dart --flavor staging
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[!] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-GE)
    • Flutter version 3.24.3 on channel stable at /Users/macintoshi/fvm/versions/3.24.3
    ! Warning: `flutter` on your path resolves to /Users/macintoshi/development/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/macintoshi/fvm/versions/3.24.3. Consider adding /Users/macintoshi/fvm/versions/3.24.3/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/macintoshi/development/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/macintoshi/fvm/versions/3.24.3. Consider adding /Users/macintoshi/fvm/versions/3.24.3/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macintoshi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/macintoshi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be insta

**Comment by darshankawar** [comment] 2024-10-04 12:23
Closing as duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by darshankawar** 2024-10-04 12:23 UTC
Labels: in triage
