### ISSUE TITLE
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'

### ISSUE THREAD

**Issue by dukaric1991** [flutter/flutter#47111] opened 2019-12-16 07:11 UTC
I upgraded to Flutter 1.12.13+hotfix5 and have these firebase packages:

  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+3

With `flutter run --debug` its works and launches, but when i try `flutter run --release` i get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> java.lang.IllegalArgumentException: Multiple entries with same key: Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String=Encoded method Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String and Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String=Encoded method Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
```

My gradle.properties file:

```
org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
```

and in build.gradle i have:

```
   buildTypes {
       release {
           signingConfig signingConfigs.release

           minifyEnabled true
           useProguard true

           proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

       }
   }
```

**Comment by iapicca** [comment] 2019-12-16 13:09
Hi @dukaric1991 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-16 13:09 UTC
