### ISSUE TITLE
Licenses display has multiple copies of the "boringssl" licence

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#18281] opened 2018-06-07 20:37 UTC
The _Licenses_ has many multiple copies of the boringssl license.

## Steps to Reproduce

1. Open the Gallery app
2. Tap the hamburger menu
3. Tap About Flutter Gallery
4. Tap View Licences
5. Enjoy reading all you can handle about the boringssl license ;)

```
[✓] Flutter (Channel master, v0.5.2-pre.77, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.5.2-pre.77 at /Users/vik/Projects/flutter
    • Framework revision c53245c61d (15 hours ago), 2018-06-06 22:57:26 -0700
    • Engine revision fca976d8c7
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio - old.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • iPhone X • 69CF3B2A-9767-4A4A-AF38-1C72492E8D80 • ios • iOS 11.4 (simulator)
```

**Comment by chinmaygarde** [comment] 2018-06-09 00:43
cc @jason-simmons, @Hixie

**Comment by Hixie** [comment] 2018-06-11 21:24
They're probably not quite identical... check the copyright dates, in particular.

**Comment by vlidholt** [comment] 2018-06-12 13:47
@Hixie ah, you might be right. There are _a lot_ of very similar ones though, but I guess it's better to be on the safe side there. :)

**Comment by dalebulmer** [comment] 2019-04-12 08:15
Is there any update on this issue?

**Comment by kjeremy** [comment] 2019-07-22 21:25
I'm seeing this in my app as well. In fact the scroll bar keeps going back up because there are so many entries for boringssl which makes it nearly impossible to scroll.

**Comment by micsan13br** [comment] 2019-08-30 15:16
Any plans to fix it?
AboutListTile is pretty much unusable otherwise ...

**Comment by Hixie** [comment] 2019-08-30 23:32
The original bug is almost certainly not a bug unless someone can confirm that they're seeing exactly identical licenses with the same copyright dates and everything.

The other issue is not the original issue; please file a separate bug for that.

**Comment by micsan13br** [comment] 2019-09-02 08:28
> The original bug is almost certainly not a bug
What about the exception that comes with AboutListTile, once you click on the "view licenses" button?

**Comment by micsan13br** [comment] 2019-09-03 17:08
@Hixie I am not sure about what to post.
I've built a new hello-world project, added a Drawer, then an AboutListTile, then I've added a SafeArea.
The license count is 380, generating a really long license text that takes forever to scroll, but which renders just fine.
In my project I have more packages and a more complex design so it will take me a while before I can sort this out.

**Comment by micsan13br** [comment] 2019-09-04 14:20
In case anyone else is running into this, check if you're using "flutter_launcher_icons"
I've commented it out and the exception is finally gone.
https://github.com/fluttercommunity/flutter_launcher_icons/issues/76

**Comment by afi-mobile** [comment] 2020-03-13 14:16
I'm waiting for an update on this issue. It seems to have been hijacked by another issue which was resolved, but the original issue of their being multiple copies of the same licence (not just boringssl) hasn't gone away. 

There should be just one copy of each licence otherwise the dialog becomes unusable and, therefore, doesn't serve the actual licence holders in the way it should.

**Comment by Hixie** [comment] 2020-03-17 20:07
As noted above, this is almost certainly not a bug unless someone can confirm that they're seeing exactly identical licenses with the same copyright dates and everything. Please post screenshots showing the duplicate licenses.

**Comment by afi-mobile** [comment] 2020-03-17 21:18
![image](https://user-images.githubusercontent.com/57636360/76902276-8f302600-6893-11ea-98f1-2b19f28eacfb.png)

Very well, then I guess by your criteria this isn't a bug so it should be closed. 

So, as responsible developers we will continue to display other developer's licences, in this completely ludicrous and unhelpful format _by design._

**Comment by Hixie** [comment] 2020-03-17 21:28
"The above copyright notice and this permission notice shall be included in all copies". I am not a lawyer, but the legal advice we have received is that what that means is that the license requires that we do this in this way. If you would like to display it differently I recommend contacting your lawyer and asking them for advice on how to do so.

**Comment by TonicArtos** [comment] 2020-05-09 09:12
An improvement would be a master detail list. Master view is a list of all packages. Detail view is a list of all licenses registered for that package name.

**Comment by Hixie** [comment] 2020-05-11 23:39
We would definitely be open to PRs that make this display more tractable.

**Comment by Hixie** [comment] 2020-05-11 23:40
Since the issue described here appears to be as intended, I'm going to close this issue, but if you would like to see a more useful license dialog please don't hesitate to file an issue showing what you'd like it to look like (e.g. UI mocks or code), and, if you would like, submit a PR to implement such changes. We are very open to such things.

**Closed by Hixie** 2020-05-11 23:40 UTC
Labels: engine
