### ISSUE TITLE
HELPME PLEASE PLEASE !!!! 

### ISSUE THREAD

**Issue by halilcapa** [flutter/flutter#52658] opened 2020-03-16 10:30 UTC
**I get an error on this code line**

googleSignIn.signInSilently (suppressErrors: false) .then ((account) {
handleSignIn (account);
}). catchError ((err) {
print ('Oturum açma hatası: $ err');
});
}

![2020-03-15_00-50-21-ee6a806ef11acd83dd3d7314685d1a2b](https://user-images.githubusercontent.com/48388384/76747481-404a9980-678a-11ea-8f12-65010c470ea5.png)

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:selfca/models/user.dart';
import 'package:selfca/pages/activity_feed.dart';
import 'package:selfca/pages/create_account.dart';
import 'package:selfca/pages/profile.dart';
import 'package:selfca/pages/search.dart';
import 'package:selfca/pages/timeline.dart';
import 'package:selfca/pages/upload.dart';
import 'package:google_sign_in/google_sign_in.dart';

final GoogleSignIn googleSignIn = GoogleSignIn();
final usersRef = Firestore.instance.collection('users');
final DateTime timestamp = DateTime.now();
User currentUser;

class Home extends StatefulWidget {
@override
_HomeState createState() => _HomeState();
}

class _HomeState extends State {
bool isAuth = false;
PageController pageController;
int pageIndex = 0;

@override
void initState() {
super.initState();
pageController = PageController();
// Detects when user signed in
googleSignIn.onCurrentUserChanged.listen((account) {
handleSignIn(account);
}, onError: (err) {
print('Error signing in: $err');
});
// Reauthenticate user when app is opened
googleSignIn.signInSilently(suppressErrors: false).then((account) {
handleSignIn(account);
}).catchError((err) {
print('Error signing in: $err');
});
}

handleSignIn(GoogleSignInAccount account) {
if (account != null) {
createUserInFirestore();
setState(() {
isAuth = true;
});
} else {
setState(() {
isAuth = false;
});
}
}

createUserInFirestore() async {
// 1) check if user exists in users collection in database (according to their id)
final GoogleSignInAccount user = googleSignIn.currentUser;
DocumentSnapshot doc = await usersRef.document(user.id).get();

if (!doc.exists) {
  // 2) if the user doesn't exist, then we want to take them to the create account page
  final username = await Navigator.push(
      context, MaterialPageRoute(builder: (context) => CreateAccount()));

  // 3) get username from create account, use it to make new user document in users collection
  usersRef.document(user.id).setData({
    "id": user.id,
    "username": username,
    "photoUrl": user.photoUrl,
    "email": user.email,
    "displayName": user.displayName,
    "bio": "",
    "timestamp": timestamp
  });

  doc = await usersRef.document(user.id).get();
}

currentUser = User.fromDocument(doc);
}

@override
void dispose() {
pageController.dispose();
super.dispose();
}

login() {
googleSignIn.signIn();
}

logout() {
googleSignIn.signOut();
}

onPageChanged(int pageIndex) {
setState(() {
this.pageIndex = pageIndex;
});
}

onTap(int pageIndex) {
pageController.animateToPage(
pageIndex,
duration: Duration(milliseconds: 300),
curve: Curves.easeInOut,
);
}

Scaffold buildAuthScreen() {
return Scaffold(
body: PageView(
children: [
// Timeline(),
RaisedButton(
child: Text('Logout'),
onPressed: logout,
),
ActivityFeed(),
Upload(),
Search(),
Profile(),
],
controller: pageController,
onPageChanged: onPageChanged,
physics: NeverScrollableScrollPhysics(),
),
bottomNavigationBar: CupertinoTabBar(
currentIndex: pageIndex,
onTap: onTap,
activeColor: Theme.of(context).primaryColor,
items: [
BottomNavigationBarItem(icon: Icon(Icons.whatshot)),
BottomNavigationBarItem(icon: Icon(Icons.notifications_active)),
BottomNavigationBarItem(
icon: Icon(
Icons.photo_camera,
size: 35.0,
),
),
BottomNavigationBarItem(icon: Icon(Icons.search)),
BottomNavigationBarItem(icon: Icon(Icons.account_circle)),
]),
);
// return RaisedButton(
// child: Text('Logout'),
// onPressed: logout,
// );
}

Scaffold buildUnAuthScreen() {
return Scaffold(
body: Container(
decoration: BoxDecoration(
gradient: LinearGradient(
begin: Alignment.topRight,
end: Alignment.bottomLeft,
colors: [
Theme.of(context).accentColor,
Theme.of(context).primaryColor,
],
),
),
alignment: Alignment.center,
child: Column(
mainAxisAlignment: MainAxisAlignment.center,
crossAxisAlignment: CrossAxisAlignment.center,
children: [
Text(
'FlutterShare',
style: TextStyle(
fontFamily: "Signatra",
fontSize: 90.0,
color: Colors.white,
),
),
GestureDetector(
onTap: login,
child: Container(
width: 260.0,
height: 60.0,
decoration: BoxDecoration(
image: DecorationImage(
image: AssetImage(
'assets/images/google_signin_button.png',
),
fit: BoxFit.cover,
),
),
),
)
],
),
),
);
}

@override
Widget build(BuildContext context) {
return isAuth ? buildAuthScreen() : buildUnAuthScreen();
}
}`

**Comment by TahaTesser** [comment] 2020-03-16 10:35
Duplicate of [#52655](https://github.com/flutter/flutter/issues/52655)

**Closed by TahaTesser** 2020-03-16 10:35 UTC
