### ISSUE TITLE
Outlined Input Border doesn't display correctly in flutter web

### ISSUE THREAD

**Issue by ahmedmgh67** [flutter/flutter#35002] opened 2019-06-24 15:23 UTC
## Steps to Reproduce
1. Use OutlinedInputBorder() in flutter web

**Comment by shihaohong** [comment] 2019-06-24 18:19
Hi, is this a duplicate of https://github.com/flutter/flutter/issues/32381? If so, please close this issue and add a thumbs up to that issue instead. Thank you!

**Comment by ahmedmgh67** [comment] 2019-06-25 05:26
okay sorry i didn't find it

**Closed** 2019-06-25 05:25 UTC
Labels: ☸ platform-web
