### ISSUE TITLE
ANDROID X INCOMPATIBILITY

### ISSUE THREAD

**Issue by kirobass** [flutter/flutter#45063] opened 2019-11-17 14:43 UTC
## Steps to Reproduce

steps to reproduce?? you re kidding me!!! just get someone to create a normal app, and compile it. add perhaps admob or firebase pub to the yaml file and it will complain about class path version incompatibility.

IM FED UP!!!!!!

1. ...Create a FLUTTER APP using android STUDIO 

Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 30, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1

2. ... Just create any app.. default app is OK. .compile it.

Result - it works
3. ... Go to your YAML file and add admob pub:

 firebase_admob: ^0.9.0+9

--> this is the latest version from the pub.dev site. 

Add the headers:
import 'package:firebase_admob/firebase_admob.dart';

ALL YOU HAD TO DO WAS TEST THE MOST OBVIOUS!!!!!!!
ITS NOT HARD!! What kind of testing do you do at Google?? This is ridiculous. 

5. I suppose you need to create a new few ads within the app. 

6. Compile:

7. You get the following error:

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:preReleaseBuild'.                       
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 22s                                                  
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        82.6s
********************************************************************************
***********
The Gradle failure may have been because of AndroidX incompatibilities in this
Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
********************************************************************************
***********
Gradle task bundleRelease failed with exit code 1

## Logs

```
```

```
```

You don't need that. Some overpaid engineer at Google could have found this. 
Wasted SO much time!!!

**Comment by piedcipher** [comment] 2019-11-17 17:25
Error message clearly mentioned this
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.

You need to migrate your project to AndroidX - https://flutter.dev/docs/development/androidx-migration

**Comment by kirobass** [comment] 2019-11-17 17:52
No. That’s not how to fix this issue.
I’ve already fixed it. In fact your email is worrying as it would have wasted more of my time.
You need to have good, smart documentation engineers or technical writers. This is very poor documentation from the side of Google.

**Comment by AfzalivE** [comment] 2019-11-17 19:49
The entitlement in this post is concerning.

Seems like OP always writes up-to-date documentation and never makes any mistakes ever.

**Comment by kirobass** [comment] 2019-11-17 19:57
Well, Im sorry if my post was harsh, but the documentation is so sloppy, if not downright irresponsible. I’m not expecting this from a multinational company.

**Comment by iapicca** [comment] 2019-11-18 12:50
Hi @kirobass 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-18 12:50 UTC
