### ISSUE TITLE
alert()/window pop up Method Not Working in iOS Webview_flutter

### ISSUE THREAD

**Issue by SyedMuhammadRehan** [flutter/flutter#134278] opened 2023-09-08 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am facing an issue with the `webview_flutter` package in my Flutter app. On Android, everything works fine. When I upload an item and try to delete it, a pop-up window appears asking for confirmation before proceeding with the deletion. However, on iOS, the pop-up window does not appear when I click on the delete button.

I have searched extensively for a solution but haven't found any relevant information or examples. I have already implemented the webview_flutter package correctly, and other functionalities are working as expected on both Android and iOS.

### Expected results

To ensure consistent behavior across both Android and iOS platforms, when a user clicks on the Delete button, a pop-up should be displayed, similar to the behavior observed on Android.

### Actual results

When an iOS user clicks on the delete button, no action or response is observed.

### Code sample

<details><summary>Code sample</summary>

```dart

    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        allowsInlineMediaPlayback: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

  onPageFinished: (String url) async {
    PreferenceUtils.seturl(url);
          if (controller0.getloginValue() == false &&
              url.contains('wp-login.php') &&
              widget.fromplash == false) {
            _controller.runJavaScript('''

      const emailInput = document.getElementById('user_login');
      const passwordInput = document.getElementById('user_pass');
      const submitButton = document.getElementById('wp-submit');
      if (emailInput && passwordInput && submitButton) {
        emailInput.value = '${PreferenceUtils.getEmail()}';
        passwordInput.value = '${PreferenceUtils.getPassword()}';
         submitButton.click();
      }
      const logout = document.getElementById('menu-item-82496');
      
    ''') }
     onWebResourceError: (WebResourceError error) {
          debugPrint('''
Page resource error:
  code: ${error.errorCode}
  description: ${error.description}
  errorType: ${error.errorType}
  isForMainFrame: ${error.isForMainFrame}
          ''');
        },
          _controller.addJavaScriptChannel(
      'Toaster',
      onMessageReceived: (JavaScriptMessage message) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(message.message)),
        );
      },
    );

    if (_controller.platform is AndroidWebViewController) {
      AndroidWebViewController.enableDebugging(true);
      (_controller.platform as AndroidWebViewController)
          .setMediaPlaybackRequiresUserGesture(false);
      (_controller.platform as AndroidWebViewController)
          .setOnShowFileSelector(_androidFilePicker);
    }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.3 21G419 darwin-x64, locale en-PK)
    • Flutter version 3.10.5 on channel stable at /Users/macbook/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.2)
    • VS Code at /Users/macbook/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 872A4BB3-0E9F-4EAD-B800-EF1A6756E944 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-08 09:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/30358

**Closed by danagbemava-nc** 2023-09-08 09:37 UTC
Labels: in triage
