### ISSUE TITLE
Flutter 3 Autofill on iOS work only in Profile mode, not on Debug and Release mode

### ISSUE THREAD

**Issue by vietstone-ng** [flutter/flutter#104058] opened 2022-05-18 09:21 UTC
## Steps to Reproduce

1. Using the code sample below, when the Login button is pressed, the Save Password is expected to be opened.
2. I already set up Associated Domains: https://developer.apple.com/documentation/xcode/supporting-associated-domains
3. I'm using VS Code, Flutter 3

**Expected results:** The Save Password dialog opens on all 3 modes: Debug, Profile, Release

**Actual results:**  The dialog opens on only Profile mode

<details>
<summary>Code sample</summary>

```dart
AutofillGroup(
            child: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  TextFormField(
                    decoration: const InputDecoration(labelText: 'Username'),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter username';
                      }
                      return null;
                    },
                    autofillHints: const [AutofillHints.username],
                  ),
                  TextFormField(
                    decoration: const InputDecoration(labelText: 'Password'),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter password';
                      }
                      return null;
                    },
                    autofillHints: const [AutofillHints.password],
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                      onPressed: () {
                        final validated = _formKey.currentState!.validate();
                        if (!validated) return;

                        TextInput.finishAutofillContext();
                      },
                      child: const Text('Login')),
                ],
              ),
            ),
          )
```
</details>

<details>
<summary>Logs</summary>

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en)
    • Flutter version 3.0.0 at /Users/vietstone-ng/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (8 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vietstone-ng/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (5 available)
    • sdk gphone arm64 (mobile) • emulator-5554                            • android-arm64  • Android 11 (API 30) (emulator)
    • Việt Ngát (mobile)        • 01e3657f507e7f2dc82a45d5a15cf1ad0755c43a • ios            • iOS 14.8.1 18H107
    • iPhone 13 Pro (mobile)    • 28F4F21C-0646-4A7B-A272-160943C3B1AA     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4
      (simulator)
    • macOS (desktop)           • macos                                    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

<details>
<summary>screenshots</summary>

| Profile mode |  Debug and Release mode | 
| -- | -- |
| ![IMG_0657](https://user-images.githubusercontent.com/744353/169004614-10311210-bf88-4fff-aa70-c7f564a5b1e7.PNG) | ![IMG_0658](https://user-images.githubusercontent.com/744353/169004598-cb2c3305-5469-4721-8722-079ede7f61aa.PNG) |
</details>

**Comment by danagbemava-nc** [comment] 2022-05-18 13:54
Hi @vietstone-ng, I tested this in debug mode and the dialog pops up usually on the first tap of the login button but subsequent taps of the login button do not pop up unless I use the `done` action button and attempt it a few more times. 

Is it the same for you or it does not appear at all except when you're in profile mode? And when you're in profile mode, how does it behave? 

The video below just captures it working for the first time

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/169057165-23566989-f2b4-4e4c-a531-43f7c8f5aad7.MP4
</details>

**Comment by vietstone-ng** [comment] 2022-05-18 23:46
Hi @danagbemava-nc , 
I've just tested on a iPhone X. It does not appear at all except when I'm in profile mode. In profile mode, the dialog pops up on both `login` or `done` button.

**Comment by danagbemava-nc** [comment] 2022-05-19 07:41
Hmm, that is rather strange. There shouldn't be any difference between calling `TextInput.finishAutofillContext()` in any of the 3 modes. 

Did you experience this behavior prior to flutter 3? 

Also, can you check on the `master` channel to see if you still experience this issue? 

I tested on a simulator and the autofill worked exactly as I described in https://github.com/flutter/flutter/issues/104058#issuecomment-1130047753.

See the video below.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/169239456-d8471bbc-2b7a-4b96-94a7-952966d89ca6.mov

 </details>

**Comment by vietstone-ng** [comment] 2022-05-19 09:58
hi @danagbemava-nc 

It works as expected on `master` channel.
The funny thing happens when I switch back to `stable`. It works!!!

Not sure that's my environment setup or what else.
But our testers experience this problem on their phones with my previous build.
Now I will put another build, hope it work on their phone :D

**Comment by danagbemava-nc** [comment] 2022-05-19 13:11
Given your recent comment, I feel it is safe to close this issue.  

If your beta testers still experience this issue after the new release, kindly leave a comment below along with the relevant steps to reproduce. 

Closing this since it seems the issue has been resolved. 

Thank you

**Closed by danagbemava-nc** 2022-05-19 13:11 UTC
Labels: in triage
