### ISSUE TITLE
[in_app_purchase] Can not complete an unfinished pending transaction on iOS on app start

### ISSUE THREAD

**Issue by Moncader** [flutter/flutter#94011] opened 2021-11-22 08:28 UTC
Several versions ago
https://github.com/flutter/plugins/pull/4035
this PR created a degradation of 
https://github.com/flutter/flutter/issues/83018

which allowed the flutter application on dart side to process something that iOS added to the payment queue on app startup.

The [#4035](https://github.com/flutter/plugins/pull/4035) author incorrectly interpreted Apple's documentation where-as yes, the document does say the app will process purchases after adding a delegate, but in the IAP guidelines
https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/setting_up_the_transaction_observer_for_the_payment_queue
it is very explicitly stated
> It is important to add the observer at launch, in application(_:didFinishLaunchingWithOptions:), to ensure that it persists during all launches of your app, receives all payment queue notifications, and continues transactions that may be processed outside the app, such as:
> * Promoted in-app purchases 
> * Background subscription renewals
> * Interrupted purchases

Ever since [#4035](https://github.com/flutter/plugins/pull/4035), all of the above features _**do not work at all**_ and any app using this plugin will not function correctly.

As a quick hack that probably is incorrect, simply re-adding
https://github.com/flutter/plugins/pull/4035/files#diff-304ecfaca1fd209465b43866fab706986bad34cea83012b3c2514397a190a9dbL76
that line to the plugin fixed the issue for us.

However, there is a chance that dart hasn't set it's methodchannels up yet, and probably the transactions need to be cached until a listener on the dart side is added and sent in received order to dart to replicate what would happen in a correct native implementation of IAP.

## Steps to Reproduce

1. Use this plugin, and create an interrupted purchase situation (kill the app in the middle of a transaction)
2. Restart the app, and notice the transaction does not get sent to the dart app.

**Expected results:** 
The transactions need to be sent to dart on app start

**Actual results:**
The first transactions that iOS sends to the app are ignored as no listener is attached to the PaymentQueue

**Comment by danagbemava-nc** [comment] 2021-11-25 13:53
Hi @Moncader, sorry for the delay. 

Something is not quite clear to me (I'm not entirely familiar with IAP, so do bear with me), at which point does cancelling the transaction cause this issue to reproduce? 
 
If you could show what happens when you attempt it, I will appreciate it. 

Thank you

**Comment by etienn01** [comment] 2021-11-25 15:43
Hi @danagbemava-nc,
Having the same/similar issue, here's what I can tell: when you make a purchase, details about it will be sent to `InAppPurchase.purchaseStream`. For each `PurchaseDetails` you receive through this stream, if its `pendingCompletePurchase` field is `true`, you'll have to call `InAppPurchase.completePurchase` to tell the store that the purchased content has been successfully delivered to the user.
If, for any reason (closing the app, crash, ...), you do not call `completePurchase`, the `PurchaseDetails` will be sent again to the stream the next time you launch the app.
The problem is that we never receive anything on the stream, even if we start listening to the stream in Dart's `main()`, making the purchase unavailable to the user and any attempt to purchase again will result in an exception:
```
PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases.)
```

**Comment by Moncader** [comment] 2021-11-26 00:44
@danagbemava-nc 
Exactly as @etienn01 says. I have nothing to add to that.
It's not about cancelling the transaction, it's about not calling complete on that transaction for any reason what-so-ever.

Once that happens, iOS will send that transaction *without waiting* to your app synchronously right after didFinishLaunching.

If any asynchronous dart code happens, it's too late, the event has already been sent to the app without any listeners attached to the PaymentQueue and you miss the event.

**Comment by danagbemava-nc** [comment] 2021-11-29 06:42
I can't seem to replicate this on my end, (perhaps due to my lack of experience with this plugin), as such I'll label it for someone with more experience to further investigate this issue.

**Comment by akshayindia** [comment] 2021-12-13 05:27
Facing the same issue with 1 week. As soon as I add this plugin my application closed and the in-app purchase IOS drawer pop up. I tried every possible way but was unable to resolve it. As soon as I open the application I didn't receive the purchase stream and was thus unable to purchase again.

**Comment by stonekase** [comment] 2021-12-17 08:33
I am also experiencing this for previously successfully purchased Items(consumables cannot be purchased more than once , then you get locked out due to non-completion)

**Comment by bladefist** [comment] 2021-12-20 21:40
Also impacting us.

**Comment by stonekase** [comment] 2021-12-21 08:02
> I am also experiencing this for previously successfully purchased Items(consumables cannot be purchased more than once , then you get locked out due to non-completion)

Edit: I used a provider and timer to resolve this by actively checking for purchases not completed using a delay timer (10 seconds) in the provider .

**Comment by antonionicolau** [comment] 2022-01-06 14:24
I'm also facing the same issue for Android and IOS
While there is not an official solution for that I added a workaround to solve this
I did the follow

When you purchase an item the listener is triggered , so what I did was:

1. Save the purchaseDetails locally ( eg. using shared_preferences )

````Dart
Future<void> saveIncompletedPurchase(PurchaseDetails purchaseDetails) async {
    final preferences = await _getInstance();
    final productId = purchaseDetails.productID;

    final purchase = {
      "purchaseID": purchaseDetails.purchaseID,
      "productID": productId,
      "localVerificationData": purchaseDetails.verificationData.localVerificationData,
      "serverVerificationData": purchaseDetails.verificationData.serverVerificationData,
      "source": purchaseDetails.verificationData.source,
      "transactionDate": purchaseDetails.transactionDate,
      "status": purchaseDetails.status.name,
      "pendingCompletePurchase": purchaseDetails.pendingCompletePurchase,
    };

    await preferences.setString(productKey, productId);

    await preferences.setString(
      "$purchaseKey$productId",
      json.encode(purchase),
    );
  }
````
**save this locally to get it later when the app start again**

2. I create a method to check for incompleted purchase ( in this case read this saved map in the shared_preferences ), call this method before the listener

````Dart
 _subscription = purchaseUpdated.listen(
      (purchaseDetailsList) {
        _listenToPurchaseUpdated(purchaseDetailsList, _inAppPurchase);
      },
      onDone: () {
        _subscription.cancel();
      },
      onError: (error) {
        log("Error : $error");
      },
    );
````

**Check incompleted purchases**
````Dart
Future<void> _checkForIncompletedPurchases() async {
    _incompletedPurchase = await _handleIncompletedPurchase.getIncompletedPurchaseFromLocalStore();
    log("Looking for incompleted purchase");
    if (_incompletedPurchase != null) {
      if (_incompletedPurchase?.status == PurchaseStatus.purchased || _incompletedPurchase?.status == PurchaseStatus.restored) {
        if (_incompletedPurchase?.pendingCompletePurchase == true) {
          log("purchasing last incompleted purchase");
          await _inAppPurchase.completePurchase(_incompletedPurchase!);
          await _handleIncompletedPurchase.removeFromIncompletedPurchases(_incompletedPurchase!.productID);
        }
      }
    }
  }
```` 

**Methods to get check and get the last incompleted purchase**
````Dart
Future<PurchaseDetails?> getIncompletedPurchaseFromLocalStore() async {
    final preferences = await _getInstance();

    final productId = preferences.getString(productKey);
    final jsonResponse = preferences.getString("$purchaseKey$productId");
    final purchase = json.decode(jsonResponse ?? '{}') as Map<String, dynamic>;

    if (purchase.containsKey("productID")) {
      return _createPurchaseDetails(purchase);
    }
  }

  PurchaseStatus getPurchaseStatusFromString(String purchaseStatus) {
    switch (purchaseStatus) {
      case "purchased":
        return PurchaseStatus.purchased;
      case "restored":
        return PurchaseStatus.restored;
      case "canceled":
        return PurchaseStatus.canceled;
      case "pending":
        return PurchaseStatus.pending;
      default:
        return PurchaseStatus.pending;
    }
  }

  PurchaseDetails _createPurchaseDetails(Map<String, dynamic> purchase) {
    final PurchaseDetails purchaseDetail = PurchaseDetails(
      purchaseID: purchase["purchaseID"].toString(),
      productID: purchase["productID"].toString(),
      verificationData: PurchaseVerificationData(
        localVerificationData: purchase["localVerificationData"].toString(),
        serverVerificationData: purchase["serverVerificationData"].toString(),
        source: purchase["source"].toString(),
      ),
      transactionDate: purchase["transactionDate"].toString(),
      status: getPurchaseStatusFromString(purchase["status"].toString()),
    );

    purchaseDetail.pendingCompletePurchase = purchase["pendingCompletePurchase"] as bool;

    final localVerificationData = json.decode(purchaseDetail.verificationData.localVerificationData);

    if (Platform.isAndroid) {
      return _createGooglePlayPurchaseDetails(localVerificationData as Map<String, dynamic>, purchaseDetail);
    }

    return purchaseDetail;
  }

  GooglePlayPurchaseDetails _createGooglePlayPurchaseDetails(Map<String, dynamic> localVerificationData, PurchaseDetails purchaseDetail) {
    return GooglePlayPurchaseDetails(
      billingClientPurchase: PurchaseWrapper(
        orderId: localVerificationData["orderId"].toString(),
        originalJson: purchaseDetail.verificationData.localVerificationData,
        packageName: localVerificationData["packageName"].toString(),
        purchaseToken: localVerificationData["purchaseToken"].toString(),
        purchaseState: PurchaseStateWrapper.purchased,
        isAcknowledged: localVerificationData["acknowledged"] as bool,
        purchaseTime: localVerificationData["purchaseTime"] as int,
        signature: 'RSASSA-PKCS1-v1_5',
        isAutoRenewing: localVerificationData["autoRenewing"] as bool,
        sku: purchaseDetail.productID,
      ),
      productID: purchaseDetail.productID,
      transactionDate: purchaseDetail.transactionDate,
      verificationData: purchaseDetail.verificationData,
      status: purchaseDetail.status,
      purchaseID: purchaseDetail.purchaseID,
    );
  }
````
Don't forgot to remove incompleted purchases saved locally when finish the purchase


It worked well for me

**Comment by pro100svitlo** [comment] 2022-02-15 10:33
So, looks like I found another way how to deal with `storekit_duplicate_product_object`.
And yes, it's not documented and sounds completely illogical 🤯 

So, according to the docs, we need to call `completePurchase` only when `status` is `purchased` or `restored`.

![image](https://user-images.githubusercontent.com/12133914/154043063-ef4353b6-3006-40de-8002-438463485688.png)

But, cos I have a lot of time and joy to work with this library (sarcasm!), I find out that if we call `completePurchase` every time we receive the status `canceled` on ios - the problem with the `PlatformException` `storekit_duplicate_product_object` - disappear.

here is part of my code from `purchaseStream` listener which made all the party:
```dart
switch (subscription.status) {
  case PurchaseStatus.canceled:
    if (Platform.isIOS) {
      _paymentService.completePurchase(subscription);
    }
    break;
  .... other casess
}
```

**Comment by sam0829** [comment] 2022-02-17 11:30
The doc says listen to `InAppPurchase.instance.purchaseStream` as soon as possible to get the callback for incomplete / interrupted purchases. I am now listening to the `purchaseStream` straight in `main()` after `WidgetsFlutterBinding.ensureInitialized();` and I still don't get anything in return. Purchase still fails by saying `storekit_duplicate_product_object`. Can any one please shed some light on how to handle interrupted purchases?

**Comment by pro100svitlo** [comment] 2022-02-17 11:56
@sam0829 have you tried the proposed [solution](https://github.com/flutter/flutter/issues/94011#issuecomment-1040110848)?

**Comment by Moncader** [comment] 2022-02-18 09:43
@pro100svitlo Your problem and this issue are separate.

This issue is about the fact that there is no way with this plugin to respond to events that are sent by StoreKit _on app startup_. It has nothing to do with cancellations.

For example, a purchase on a different device, or on the App Store needs to be handled instantly, before this plugin exposes a stream to dart (currently).

**Comment by Moncader** [comment] 2022-02-18 09:45
@stuartmorgan @danagbemava-nc

What is the status on this issue? iOS purchases are currently broken in any kind of exceptional situation and/or external purchases situation.

**Comment by sam0829** [comment] 2022-02-20 05:31
> @sam0829 have you tried the proposed [solution](https://github.com/flutter/flutter/issues/94011#issuecomment-1040110848)?

Unfortunately it's not working for my case, as for me, the purchase was interrupted which led to failure in call to `InAppPurchase.completePurchase`. Now next time when I try to initiate the purchase, I directly get the `storekit_duplicate_product_object` without any other callback like `PurchaseStatus.canceled` or something so the solution you mentioned doesn't apply here. The only correct solution here is that the plugin should return the interrupted purchase through `InAppPurchase.purchaseStream` in reliable way when we listen to it when the app starts, which it isn't doing currently.

**Comment by antonionicolau** [comment] 2022-02-20 17:18
> > @sam0829 have you tried the proposed [solution](https://github.com/flutter/flutter/issues/94011#issuecomment-1040110848)?
> 
> Unfortunately it's not working for my case, as for me, the purchase was interrupted which led to failure in call to `InAppPurchase.completePurchase`. Now next time when I try to initiate the purchase, I directly get the `storekit_duplicate_product_object` without any other callback like `PurchaseStatus.canceled` or something so the solution you mentioned doesn't apply here. The only correct solution here is that the plugin should return the interrupted purchase through `InAppPurchase.purchaseStream` in reliable way when we listen to it when the app starts, which it isn't doing currently.

did you try [this solution](https://github.com/flutter/flutter/issues/94011#issuecomment-1006632517) as well ? 
I had this problem as well and this was the solution that I tried

**Comment by atelog** [comment] 2022-02-21 18:09
@antonio-nicolau How you are saving the purchase if it fails? The app crash and it's closed. 
When making a purchase `purchaseUpdated` stream will emit: `PurchaseStatus.purchased` and at that moment you complete the purchase, and everything is good. 
The idea is that the app crash or closes at the moment when the user is making the purchase, so, the user got charged, he opens the app again, and the  `purchaseUpdated` does not emit anything, so the order can't be completed.

This is really a critical issue!!! 30% of my orders were refunded after 3 days on Goole Play, and I got many complaints from the users

**Comment by atelog** [comment] 2022-02-21 18:18
A **note** to the great contributors of this not at all not critical library of the entire flutter technology:

From https://developer.android.com/google/play/billing/integrate#fetch :
Listening to purchase updates using a [PurchasesUpdatedListener]Listening to purchase updates using a [PurchasesUpdatedListener](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener) is not sufficient to ensure your app processes all purchases. It's possible that your app might not be aware of all the purchases a user has made.

**Comment by atelog** [comment] 2022-02-21 18:19
A **note** to the great contributors of this not at all critical library of the entire flutter technology:

From https://developer.android.com/google/play/billing/integrate#fetch :
Listening to purchase updates using a [PurchasesUpdatedListener](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener) is not sufficient to ensure your app processes all purchases.

**Comment by antonio-nicolau** [comment] 2022-02-22 09:30
> @antonio-nicolau How you are saving the purchase if it fails? The app crash and it's closed. When making a purchase `purchaseUpdated` stream will emit: `PurchaseStatus.purchased` and at that moment you complete the purchase, and everything is good. The idea is that the app crash or closes at the moment when the user is making the purchase, so, the user got charged, he opens the app again, and the `purchaseUpdated` does not emit anything, so the order can't be completed.
> 
> This is really a critical issue!!! 30% of my orders were refunded after 3 days on Goole Play, and I got many complaints from the users

@atelog I'm saving the purchase at the fist moment the stream emit: `PurchaseStatus.purchased` as you can see in the image 
<img src="https://user-images.githubusercontent.com/67912928/155102785-164116a8-f505-4017-a060-00dbcbb52b0c.png">

and I show in [this comment](https://github.com/flutter/flutter/issues/94011#issuecomment-1006632517) how I save it

so basically it work this way:

when the purchase start I save it locally as `pending` 

if it fail for somehow then it keep as fail but if don't I remove it from storage

on the next app start I read the storage ( shared_preferences or other ) and if is there any pending purchase I load it and try to finish

this is a simple approach but worked for me

**Comment by antonio-nicolau** [comment] 2022-02-22 09:31
yeah it's a critical issue, I really don't get why they didn't solve it till now. Let's way to see

**Comment by atelog** [comment] 2022-02-23 15:46
@antonio-nicolau Yes, but what about this test case:

User initiates the payment process, the native billing popups appear, meanwhile the app crashes in the background, user confirms the transaction, he got charged, opens back the app, `purchaseStream` doesn't emit anything, no `PurchaseStatus.purchased`, you can even call `restorePurchases` and still nothing. Users' money is lost.

In order to test this case just exit the app after calling `buyConsumable()`:
```dart
//...
InAppPurchase.instance.buyConsumable(purchaseParam: purchaseParam);
// TESTING PURPOSE, make the app crash
Future.delayed(Duration(seconds: 3), () => exit(0));
```

**Comment by akshayindia** [comment] 2022-02-23 15:49
Hi Guys,

Your app is crashing because of other plugin issue...

For me it's Google sign in...

I've removed the Google sign in and it get resolved. 👍

Do update me on the same.

**Comment by atelog** [comment] 2022-02-23 15:54
@akshayindia Thanks for the hint. But the app may crash due to many reasons like a simple network error or the user's phone is not charged and turns off. When building software we shall make it reliable and not expect only positive cases, in special when it's about purchases.

**Comment by akshayindia** [comment] 2022-02-23 15:57
If you use copy the GitHub of In-app purchases repo and run it. It will
runs fine without any crashes.

You can use either use Google Sign In Plugin or Apple In-app purchases.

It's weird to know that flutter is made by Google and you can't use Google
sign in with Apple in app purchase 😅

Check your dependency and Install one by one to check and then update it in
the GitHub.

**Comment by akshayindia** [comment] 2022-02-23 15:58
Atelog, That's true... It is a hacks until the issue is not resolved.

**Comment by atelog** [comment] 2022-02-23 16:12
Btw,  I always call `restorePurchases` that will make `purchaseStream` to emit any not completed purchases.
It works well on Android but not on iOS, on iOS `restorePurchases` does not make `purchaseStream` to emit not completed purchases.

My code look like this:
 
```dart
final Stream purchaseUpdated = InAppPurchase.instance.purchaseStream;
_subscription = purchaseUpdated.listen((purchaseDetailsList) {
  _listenToPurchaseUpdated(purchaseDetailsList);
}, onDone: () {
  _subscription.cancel();
}, onError: (error) {
  log('P error: ${error}');
});
// restorePurchases will make purchaseStream emit any pending purchases that were not completed (acknowledged and/or consumed)
Future.delayed(Duration(seconds: 3), () async {
  await InAppPurchase.instance.restorePurchases();
});

void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
  purchaseDetailsList.forEach(
    (PurchaseDetails purchaseDetails) async {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        return;
      }
      if (purchaseDetails.status == PurchaseStatus.canceled) {
        return;
      }
      if (purchaseDetails.status == PurchaseStatus.error) {
        if (purchaseDetails.error.message == 'BillingResponse.error') {
          showFailedDialog();
        }
        return;
      }

      if (Platform.isAndroid &&
          purchaseDetails.status == PurchaseStatus.restored) {
        try {
          int originalPurchaseState = jsonDecode(
              (purchaseDetails as GooglePlayPurchaseDetails)
                  .billingClientPurchase
                  .originalJson)['purchaseState'];
          if (originalPurchaseState == 4) {
            return;
          }
        } catch (e) {}
      }

      if (purchaseDetails.status == PurchaseStatus.purchased ||
          purchaseDetails.status == PurchaseStatus.restored) {
        // Verify the purchase on server and give to user the privileges
      }

      if (purchaseDetails.pendingCompletePurchase) {
        await InAppPurchase.instance.completePurchase(purchaseDetails);
      }
      if (Platform.isAndroid &&
          purchaseDetails.status == PurchaseStatus.restored) {
        InAppPurchaseAndroidPlatformAddition androidAddition =
            InAppPurchase.instance.getPlatformAddition();
        await androidAddition.consumePurchase(purchaseDetails);
      }
    },
  );
}

```

**Closed** 2022-03-17 16:25 UTC
Labels: platform-ios, plugin, p: first party, p: in_app_purchase, passed first triage, passed secondary triage, P4
