### ISSUE TITLE
RenderBox was not laid out: RenderTransform#c521e relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE 'package:flutter/src/rendering/box.dart': Failed assertion: line 1966 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by Arulthas05** [flutter/flutter#131612] opened 2023-07-31 16:29 UTC
bottomNavigationBar: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: CurvedNavigationBar(
            index: _selectedIndex,
            height: 50,
            backgroundColor: const Color(0xFFFA0303),
            color: Color(0xFF001C38),
            buttonBackgroundColor: Color(0xFFFA0303),
            items: const <Icon>[
              Icon(
                Icons.face_rounded,
                size: 30,
                color: Colors.white,
              ),
              Icon(
                Icons.tag_faces,
                size: 30,
                color: Colors.white,
              ),
              Icon(
                Icons.tag_faces,
                size: 30,
                color: Colors.white,
              ),
              Icon(
                Icons.tag_faces,
                size: 30,
                color: Colors.white,
              ),
              Icon(
                Icons.tag_faces,
                size: 30,
                color: Colors.white,
              ),
            ],
            onTap: _onItemTapped,
          ),
        ),

**Comment by huycozy** [comment] 2023-08-01 05:45
Hi @Arulthas05
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. If the issue is only reproducible with [curved_navigation_bar](https://pub.dev/packages/curved_navigation_bar), you should report the issue to its developers/maintainers for better support there.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.

**Closed by huycozy** 2023-08-01 05:45 UTC
Labels: in triage
