### ISSUE TITLE
[web]: Flutter web support not working :(

### ISSUE THREAD

**Issue by Joshuaerinosho** [flutter/flutter#79753] opened 2021-04-05 02:14 UTC
Getting this error
![Capture](https://user-images.githubusercontent.com/38128821/113529902-a33ce780-95bc-11eb-89d0-d7759303fc5f.PNG)

**Comment by iapicca** [comment] 2021-04-05 07:40
@Joshuaerinosho 
can you provide your `flutter doctor -v`, your `flutter run -d chomre -v`(running from terminal, not from your IDE) 
and a[minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Joshuaerinosho** [comment] 2021-04-05 08:54
Alright

flutter doctor -v  (from terminal)

![0](https://user-images.githubusercontent.com/38128821/113556121-e9fa0400-95f3-11eb-93f7-757d4cac54b3.PNG)




flutter run -d chrome -v (from terminal)

![1](https://user-images.githubusercontent.com/38128821/113556264-22014700-95f4-11eb-9b34-7e585f04677f.PNG)

![2](https://user-images.githubusercontent.com/38128821/113556307-2fb6cc80-95f4-11eb-8e23-7fb04fe3baa8.PNG)


here's my ''minimal reproducible code sample'':


`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: IconButton(
          onPressed: (){
            print('you clicked the button');
          },
          icon: Icon(CupertinoIcons.smiley),
        )
      )
    );
  }
}
`


**thanks! :)**

**Comment by iapicca** [comment] 2021-04-05 10:08
@Joshuaerinosho 

> ![](https://user-images.githubusercontent.com/38128821/113556264-22014700-95f4-11eb-9b34-7e585f04677f.PNG)

please make sure you are running the command from your app folder 
and I recommend to avoid posing pictures preferring plain text or attaching it as `.txt` file

**Comment by Joshuaerinosho** [comment] 2021-04-05 11:00
**Alright**

**flutter doctor -v (from terminal)**

`C:\Users\Mr Goddy\Documents\personal app projects\my_portfolio>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.746], locale en-NG)
    • Flutter version 2.0.3 at C:\src\my\flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mr Goddy\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.55.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!

C:\Users\Mr Goddy\Documents\personal app projects\my_portfolio>
`




**flutter run -d chrome -v**

`
C:\Users\Mr Goddy\Documents\personal app projects\my_portfolio>flutter run -d chrome -v
[ +170 ms] executing: [C:\src\my\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +220 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +2 ms] executing: [C:\src\my\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[ +340 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +2 ms] 2.0.3
[ +131 ms] executing: [C:\src\my\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\src\my\flutter/] git ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +137 ms] executing: [C:\src\my\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +142 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +139 ms] executing: C:\Users\Mr Goddy\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +100 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +168 ms] executing: C:\Users\Mr Goddy\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] Skipping pub get: version match.
[+1170 ms] Generating C:\Users\Mr Goddy\Documents\personal app
projects\my_portfolio\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +538 ms] List of devices attached
[  +74 ms] List of devices attached
[ +131 ms] Launching lib\main.dart on Chrome in debug mode...
[ +285 ms] Updating assets
[+1811 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[  +20 ms] Waiting for connection from debug service on Chrome...
[+1156 ms] <- reset
[  +15 ms] C:\src\my\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\my\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\my\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\MRGODD~1\AppData\Local\Temp\flutter_tools.777465ce\flutter_tool.c6c414fb\app.dill --libraries-spec
file:///C:/src/my/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\Mr Goddy\Documents\personal app
projects\my_portfolio\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\MRGODD~1\AppData\Local\Temp\flutter_tools.777465ce\flutter_tools.b9c67006 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/src/my/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +34 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+58405 ms] Waiting for connection from debug service on Chrome... (completed in 59.5s)
[   +3 ms] Synced 29.1MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+14301 ms] Using Opening in existing browser session.

[+66535 ms] [CHROME]:
[   +9 ms] [CHROME]:DevTools listening on ws://127.0.0.1:52372/devtools/browser/c82bdf26-1971-44d0-87f9-55d89f8e6904
[+21831 ms] DwdsInjector: Received request for entrypoint at http://localhost:52302/main_module.bootstrap.js
[  +18 ms] MetadataProvider: Loading debug metadata...
[  +31 ms] MetadataProvider: Loaded debug metadata
[  +18 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52302/main_module.bootstrap.js
[+30024 ms] "flutter run" took 196,890ms.
[  +27 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a
connection, for
           example due to a firewall.
[  +27 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:542:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +114 ms] ensureAnalyticsSent: 99ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +155 ms] Shutdown hooks complete
[ +196 ms] exiting with code 1

C:\Users\Mr Goddy\Documents\personal app projects\my_portfolio>
`


**and here's my ''minimal reproducible code sample'':**

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return Scaffold(
         body: Center(
          child: IconButton(
              onPressed: (){
                print('you clicked the button');
              },
              icon: Icon(CupertinoIcons.smiley),
            ),
        ));
       }
      }`



**Thank you so much!**

**Comment by darshankawar** [comment] 2021-04-05 14:20
Looking at the error, it's a duplicate of https://github.com/flutter/flutter/issues/49482.
Please follow-up there for updates.
Closing from here.

**Closed by darshankawar** 2021-04-05 14:20 UTC
Labels: in triage
