### ISSUE TITLE
Dart extension methods are not autocompleted

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#49617] opened 2020-01-28 16:08 UTC
I have to import the file manualy every time I want to use one of my extensions from my extensionsfile

I use android studio.

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-BE)
    • Flutter version 1.12.13+hotfix.5 at /Users/vanlooverenkoen/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • F2704E51-185C-4E5F-BC54-8FB1BA3C43BE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS               • macOS                                • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome              • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server          • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

https://github.com/dart-lang/sdk/issues/40365

**Comment by iapicca** [comment] 2020-01-29 09:03
Hi @vanlooverenkoen  

I'm not sure that the issue you are describing
can be fixed within Flutter itself;

following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

and of course the counterpart  [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) 
has a  dedicated [github](https://github.com/Dart-Code/Dart-Code/issues) as well.

I'm not confident enough to assess the situation
I'd keep the issue open for now.

Thank you for the contribution

**Comment by pedromassangocode** [comment] 2020-09-25 10:43
Hi @vanlooverenkoen 
From what I can see, the issue is related to the Dart language rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).

This may be a duplicate of one of the issues in that repository, please see https://github.com/dart-lang/sdk/issues/38894.

Closing, as this isn't an issue with Flutter itself. 
Thank you

**Closed by pedromassangocode** 2020-09-25 10:43 UTC
Labels: customer: crowd, framework
