### ISSUE TITLE
[google_sign_in] Cancelling Google Sign In throws exception instead of returning null

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#64681] opened 2020-08-27 01:45 UTC
This is related to #26705 and many others. I already fixed this before on #37343 submitting this PR https://github.com/flutter/plugins/pull/1937.

I am fixing this again.

Could the owners of these files make some sort of mechanism to avoid this from happening again?

**Comment by markusaksli-nc** [comment] 2020-08-27 07:55
Is this related to https://github.com/flutter/flutter/issues/45146?

**Comment by pedromassangocode** [comment] 2020-08-27 07:58
> Could the owners of these files make some sort of mechanism to avoid this from happening again?

You can add test cases for what you're fixing to make sure it does not break again.

**Comment by feinstein** [comment] 2020-08-27 20:31
> 
> 
> Is this related to #45146?

Yes, I even forgot about that one, will include it in the PR list, thanks.

**Comment by feinstein** [comment] 2020-08-27 20:32
> 
> 
> > Could the owners of these files make some sort of mechanism to avoid this from happening again?
> 
> You can add test cases for what you're fixing to make sure it does not break again.

No, I can't. Not as far that I know of. This is related to the VM compiler not being able to know how to deliver an Exception, so you can't test the compiler running the VM.

**Comment by stuartmorgan** [comment] 2021-04-07 19:24
This seems like a duplicate of 45146, so closing to track in one place.

**Closed** 2021-04-07 19:26 UTC
Labels: a: error message, p: google_sign_in, passed first triage, plugin
