### ISSUE TITLE
flutter 2.0 web icon cannot be displayed

### ISSUE THREAD

**Issue by aiqinxuancai** [flutter/flutter#77685] opened 2021-03-09 08:37 UTC
I run command "flutter build web --release" build and publish.

The icon is displayed normally when I open the website for the first time, but when I press F5 to refresh, the icon cannot be displayed.
![image](https://user-images.githubusercontent.com/4475018/110441404-b1e6ca80-80f4-11eb-8306-20dcf457a32f.png)

When I use Ctrl+F5 refresh, it can be displayed normally again.
![GIF 2021-3-9 16-32-55](https://user-images.githubusercontent.com/4475018/110441939-4c470e00-80f5-11eb-8ae2-0175291f2be5.gif)

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.0)
[√] Connected device (2 available)

**Comment by iapicca** [comment] 2021-03-09 08:52
this issue keeps re-emerging overtime
it would be great to have a test that prevent this from happening
https://github.com/flutter/flutter/issues/76442

**Comment by pedromassangocode** [comment] 2021-03-09 08:55
Hi @aiqinxuancai 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

Somehow related to https://github.com/flutter/flutter/issues/76442

**Comment by aiqinxuancai** [comment] 2021-03-09 08:57
> Hi @aiqinxuancai
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you
> 
> Somehow related to #76442

'''[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale zh-CN)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\aiqin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.0)
    • VS Code at C:\Users\aiqin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!'''

**Comment by iapicca** [comment] 2021-03-09 09:08
@pedromassango 
using the same code sample provided [here](https://github.com/flutter/flutter/issues/76442#issue-812552676)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: Icon(Icons.image),
          ),
        ),
      ),
    );

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.165, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.165 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 698d438960 (2 hours ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>android screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/110446304-b052dd80-80c7-11eb-9806-3b907f1534b8.png)


</details>

<details>
<summary>web screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/110445804-2a369700-80c7-11eb-9d3c-d937f17e2eae.png)


</details>

<details>
<summary>linux screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/110445958-5baf6280-80c7-11eb-8d69-d06ed91b0cfd.png)


</details>

the issue does not occur with the latest master

**Comment by iapicca** [comment] 2021-03-09 09:29
@pedromassango 
with the same code sample provided [here](https://github.com/flutter/flutter/issues/76442)
run the web app locally with [dhttpd](https://pub.dev/packages/dhttpd) following commands

```console
flutter pub global activate dhttpd
cd <app directory>
flutter build web --release
cd build/web
dhttpd --port 8888
```
then paste `localhost:8888` in your browser

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: Icon(Icons.image),
          ),
        ),
      ),
    );

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.165, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.165 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 698d438960 (2 hours ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/110449099-84852700-80ca-11eb-80aa-b1847aee5677.png)

</details>

the issue does not occur with the latest master

**Comment by aiqinxuancai** [comment] 2021-03-10 03:21
> localhost:8888

This example code works fine, and I can’t determine the cause now. this problem only occurs in some browsers, edge and chrome have not reproduced.

**Comment by aiqinxuancai** [comment] 2021-03-10 03:37
> I've built the web project and still was not able to reproduce the issue: https://sad-swirles-cb426a.netlify.app/#/.
> 
> Also tried the local version but still can't reproduce it..
> 
> ![gif](https://user-images.githubusercontent.com/67424416/110477595-a50dab00-80e3-11eb-86bf-c66e8449cc0f.gif)
> 
> flutter doctor -v

I should have found the problem. This browser has a bug and the cache cannot be cleared. Whenever I press F5, the browser will load me the old "FontManifest.json" file, but when I press Ctrl+F5, it will Load a new file, and then press F5 again, the old file will still be loaded.
I press F5, ctrl+F5 repeatedly:
![3333](https://user-images.githubusercontent.com/4475018/110572634-cbd7ea00-8194-11eb-9787-ab6901af5cc6.gif)

**Comment by pedromassangocode** [comment] 2021-03-10 06:52
> > localhost:8888
> 
> This example code works fine, and I can’t determine the cause now. this problem only occurs in some browsers, edge and chrome have not reproduced.

This does not seems to be a code sample, but a link to your localhost which I cannot access.

Flutter currently support only few browsers, here is a list of supported browsers: https://flutter.dev/docs/development/platform-integration/web#which-web-browsers-are-supported-by-flutter.
Can you please provide the information about your browser?
Thank you

**Comment by aiqinxuancai** [comment] 2021-03-10 10:28
> > > localhost:8888
> > 
> > 
> > This example code works fine, and I can’t determine the cause now. this problem only occurs in some browsers, edge and chrome have not reproduced.
> 
> This does not seems to be a code sample, but a link to your localhost which I cannot access.
> 
> Flutter currently support only few browsers, here is a list of supported browsers: https://flutter.dev/docs/development/platform-integration/web#which-web-browsers-are-supported-by-flutter.
> Can you please provide the information about your browser?
> Thank you

I think this is a bug in the browser itself, because I tried to use the browser's own cache cleaning function and it couldn't be solved.

I tested my other browsers here are all working fine.

**Comment by pedromassangocode** [comment] 2021-03-10 11:05
Thank you for confirming that.

I'm going to to close this for now, please write in the comments bellow if you have any other information to share with us.
Thank you

**Closed by pedromassangocode** 2021-03-10 11:05 UTC
Labels: in triage
