### ISSUE TITLE
Xcode -- Target kernel_snapshot failed: Exception

### ISSUE THREAD

**Issue by dgaedcke** [flutter/flutter#151623] opened 2024-07-11 23:28 UTC
### Steps to reproduce

Xcode (v 15.4) -> Product -> Archive   (fails with error below)

### Expected results

It should open the organizer window and let me send the archive to testflight.  I've been blocked on this for over a week ..

### Actual results

```console
error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..6148: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313)
#1      Source.getLocation (package:kernel/ast.dart:14992)
#2      Component.getLocation (package:kernel/ast.dart:14787)
#3      _getLocationInComponent (package:kernel/ast.dart:15181)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:628)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1782)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:398)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:287)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1663)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1606)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1811)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:121)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:589)
#18     compileToKernel (package:vm/kernel_front_end.dart:489)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
Failed to package /Users/dgaedcke/dev/Touchstone/TouchstoneFlutter.
```

### Code sample

The app builds ... so I'm assuming the code is valid ... it just won't archive!

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..6148: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313)
#1      Source.getLocation (package:kernel/ast.dart:14992)
#2      Component.getLocation (package:kernel/ast.dart:14787)
#3      _getLocationInComponent (package:kernel/ast.dart:15181)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:628)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1782)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:398)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:287)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1663)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1606)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1811)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:121)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:589)
#18     compileToKernel (package:vm/kernel_front_end.dart:489)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.91.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for dgiphone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment] 2024-07-12 07:52
Hi @dgaedcke 
I see there is a similar issue case at https://github.com/flutter/flutter/issues/148352#issuecomment-2139153323 and users there said that works on Flutter master channel. Can you also switch to master channel and confirm?

**Comment by dgaedcke** [comment] 2024-07-12 17:58
Yes! -- archiving succeeded on Master channel.  Now switching to beta to see if it works there!  Stay tuned

**Comment by huycozy** [comment] 2024-07-15 06:01
I think this is similar to https://github.com/flutter/flutter/issues/144176 which was fixed on master. Since you tested and confirmed it on beta as well, the fix may be landed to stable soon, please see https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md. I will go ahead and close this as fixed. Thanks for confirming this.

**Closed by huycozy** 2024-07-15 06:01 UTC
Labels: in triage
