### ISSUE TITLE
[webview] Support for macOS

### ISSUE THREAD

**Issue by bastibense** [flutter/flutter#129350] opened 2023-06-22 14:55 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'd like to provide a way to display web content in a Flutter macOS app. For some reason this is not supported right now.

I've also tried a number of alternative packages, none of which are still either actively maintained or are missing macOS support or have some other limitations.

### Proposal

I'd like to provide a way to display web content in a Flutter macOS app. For some reason this is not supported right now.

**Comment by FusoraTech** [comment] 2023-06-22 23:55
It probably depends on this long standing feature in progress https://github.com/flutter/flutter/issues/41722

**Comment by huycozy** [comment] 2023-06-23 04:41
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/41725. Please follow up on it (and https://github.com/flutter/flutter/issues/41722) for further updates.

**Closed by huycozy** 2023-06-23 04:41 UTC
Labels: in triage
