### ISSUE TITLE
Flutter TextField on Android has bug in deleting emoji characters, each delete action can only delete half a char

### ISSUE THREAD

**Issue by WHATHELWHATHELWHATHEL** [flutter/flutter#30364] opened 2019-04-02 09:11 UTC
## Flutter TextField on Android hasbug in deleting emoji characters, each delete action can only delete half a char

It's me again ~

Flutter on Android has a bug in TextField delete.

When you have already input a string of emoji, and you press the "delete" to delete some emoji, you will encounter as following video:

[Flutter TextField delete emoji bug](https://www.youtube.com/watch?v=3aVbelPJplc)

You need to press the "delete" twice to successfully delete one emoji character.

If you only press "delete" once,  a "?" will appear in the input field.

Personally I think there may be some bugs on Flutter Android TextField encoding functions.

On the IOS platform this problem won't occur, emojis can be deleted correctly.

Demo code as follow, a very simple one.

```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text('input space in the following input field'),
            Text('to see if it can properly change line'),
            Container(
              height: 100, width: 200,
              color: Colors.indigo,
              child: TextField(
                style: TextStyle(color: Colors.white),
                keyboardType: TextInputType.multiline,
                maxLines: 3,
              ),
            ),
          ],
        ),
      ),
    );
  }
}


```

###Steps to reproduce

1. Click the blue box to focus the TextField
2. Input some emojis like 😂😂😂😂😂
3. press the delete/backspace of the soft keyboard one at a time, this problem should occur.

Flutter Analyze result as follow

```

Analyzing inputfield_no_change_line...                           
No issues found! (ran in 1.6s)

```

flutter doctor -v results as follow:

```

[✓] Flutter (Channel faceu_dev_1.0.0, v1.0.1-pre.8, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.0.1-pre.8 at /Users/yifan.chen/ByteDanceIES/flutter
    • Framework revision f1c0708bd5 (3 months ago), 2019-01-15 11:42:04 +0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yifan.chen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • MI PLAY • 4ee206d70211 • android-arm64 • Android 8.1.0 (API 27)

```

The platform this test code running is MI PLAY • 4ee206d70211. I am trying to run the code on other Android platforms, I will update the results to this issues ASAP

**Comment by HansMuller** [comment] 2019-04-02 14:53
CC @GaryQian

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-03 03:41
> CC @GaryQian

Any suggestion to this ? This problem is really a pin in the ass...
I am working on  a TextInputFormatter to filter out those half emoji, but those emoji coding is way too much complicated.

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-04 02:14
Any further update on this issues?

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-16 02:25
> CC @GaryQian

。。。sorry to trouble you, is there any update on this emoji issue?

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-04-19 02:34
@HansMuller 。。。sorry to trouble you again, is there any progress on this issue?

**Comment by GaryQian** [comment] 2019-04-19 17:49
This is a dupe of https://github.com/flutter/flutter/issues/23496, where I am more actively investigating it. I have determined that part of the cause is using the backspace key in only certain language keyboards. Specifically the Chinese keyboard is known to have this issue. Further work on this is currently in my queue after completing a few other things.

**Comment by WHATHELWHATHELWHATHEL** [comment] 2019-05-10 10:48
> #23496

Thank you for your update. I will be patiently waiting for the progress.

**Comment by GaryQian** [comment] 2019-07-23 18:17
This should have been fixed! I will close this now.

**Closed by GaryQian** 2019-07-23 18:17 UTC
Labels: a: text input, f: material design, framework
