### ISSUE TITLE
[tool_crash] FormatException: Same package name occured twice (at offset 2884)

### ISSUE THREAD

**Issue by alymohamedhassan** [flutter/flutter#54510] opened 2020-04-11 00:05 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=ZY32236TK9 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException: FormatException: Same package name occured twice (at offset 2884)
```
#0      parse (package:package_config/packages_file.dart:92:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:17:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:49:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:53:5)
#4      new PackageUriMapper (package:flutter_tools/src/compile.dart:199:116)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:647:26)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#16     _rootRun (dart:async/zone.dart:1180:38)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.17.0 at C:\Android\Flutter SDK\flutter
    • Framework revision d3ed9ec945 (4 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\east asia\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.0)
    • VS Code at C:\Users\east asia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Moto G 5 • ZY32236TK9 • android-arm • Android 7.0 (API 24)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98

**Comment by jonahwilliams** [comment] 2020-05-23 20:49
Even though this isn't an exact duplicate of https://github.com/flutter/flutter/issues/57864, still going to de-dupe since the fix is the same

**Closed by jonahwilliams** 2020-05-23 20:49 UTC
Labels: severe: crash, tool
