### ISSUE TITLE
[tool_crash] IndexError: RangeError (index): Index out of range: index should be less than 63760932: 63868567

### ISSUE THREAD

**Issue by SteNeo** [flutter/flutter#127481] opened 2023-05-24 10:18 UTC
Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+IndexError%3A+RangeError+%28index%29%3A+Index+out+of+range%3A+index+should+be+less+than+63760932%3A+63868567&body=%23%23+Command%0A%60%60%60%0Aflutter+--no-color+--no-version-check+precache%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AIndexError%3A+RangeError+%28index%29%3A+Index+out+of+range%3A+index+should+be+less+than+63760932%3A+63868567%0A%60%60%60%0A%230++++++_Uint8ArrayView.%5B%5D+%28dart%3Atyped_data-patch%2Ftyped_data_patch.dart%3A4280%3A7%29%0A%231++++++InputStream.readUint32+%28package%3Aarchive%2Fsrc%2Futil%2Finput_stream.dart%3A250%3A22%29%0A%232++++++new+ZipDirectory.read+%28package%3Aarchive%2Fsrc%2Fzip%2Fzip_directory.dart%3A49%3A34%29%0A%233++++++ZipDecoder.decodeBuffer+%28package%3Aarchive%2Fsrc%2Fzip_decoder.dart%3A19%3A30%29%0A%234++++++ZipDecoder.decodeBytes+%28package%3Aarchive%2Fsrc%2Fzip_decoder.dart%3A14%3A12%29%0A%235++++++_WindowsUtils.unzip+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fos.dart%3A509%3A42%29%0A%236++++++ArtifactUpdater._downloadArchive+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A1111%3A18%29%0A%3Casynchronous+suspension%3E%0A%237++++++EngineCachedArtifact.updateInner+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A908%3A7%29%0A%3Casynchronous+suspension%3E%0A%238++++++CachedArtifact.update+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A810%3A5%29%0A%3Casynchronous+suspension%3E%0A%239++++++Cache.updateAll+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A677%3A9%29%0A%3Casynchronous+suspension%3E%0A%2310+++++PrecacheCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fprecache.dart%3A168%3A7%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A27%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2313+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous+suspension%3E%0A%2314+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A296%3A9%29%0A%3Casynchronous+suspension%3E%0A%2315+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.10.1%2C+on+Microsoft+Windows+%5BVersion+10.0.19045.2965%5D%2C+locale+en-NA%29%0A++++%E2%80%A2+Flutter+version+3.10.1+on+channel+stable+at+C%3A%5Csrc%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+d3d8effc68+%287+days+ago%29%2C+2023-05-16+17%3A59%3A05+-0700%0A++++%E2%80%A2+Engine+revision+b4fb11214d%0A++++%E2%80%A2+Dart+version+3.0.1%0A++++%E2%80%A2+DevTools+version+2.23.1%0A%0A%5B%E2%9C%93%5D+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%5B%E2%9C%97%5D+Android+toolchain+-+develop+for+Android+devices%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5Cbasimikes%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%9C%97+cmdline-tools+component+is+missing%0A++++++Run+%60path%2Fto%2Fsdkmanager+--install+%22cmdline-tools%3Blatest%22%60%0A++++++See+https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Fcommand-line+for+more+details.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CUsers%5Cbasimikes%5CAppData%5CLocal%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%21%5D+Visual+Studio+-+develop+for+Windows+%28Visual+Studio+Community+2019+16.11.12+Preview+1.0%29%0A++++%E2%80%A2+Visual+Studio+at+C%3A%5CProgram+Files+%28x86%29%5CMicrosoft+Visual+Studio%5C2019%5CPreview%0A++++%E2%80%A2+Visual+Studio+Community+2019+version+16.11.32407.337%0A++++%E2%80%A2+The+current+Visual+Studio+installation+is+a+pre-release+version.+It+may+not+be+supported+by+Flutter+yet.%0A++++%E2%9C%97+Visual+Studio+is+missing+necessary+components.+Please+re-run+the+Visual+Studio+installer+for+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+and+include+these+components%3A%0A++++++++MSVC+v142+-+VS+2019+C%2B%2B+x64%2Fx86+build+tools%0A+++++++++-+If+there+are+multiple+build+tool+versions+available%2C+install+the+latest%0A++++++++C%2B%2B+CMake+tools+for+Windows%0A++++++++Windows+10+SDK%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2020.3%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%0D%0A%0A%5B%21%5D+Android+Studio%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cbin%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%9C%97+android-studio-dir+%3D+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cbin%0A++++%E2%9C%97+Unable+to+find+bundled+Java+version.%0A++++%E2%80%A2+Try+updating+or+re-installing+Android+Studio.%0A++++%E2%80%A2+Consider+removing+your+android-studio-dir+setting+by+running%3A%0A++++++flutter+config+--android-studio-dir%3D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.78.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5Cbasimikes%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.64.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19045.2965%5D%0A++++%E2%80%A2+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+107.0.5304.88%0A++++%E2%80%A2+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+113.0.1774.50%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%21+Doctor+found+issues+in+3+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash

**Comment by rabinacharya11** [comment] 2023-05-24 10:21
this is not the issue of flutter, its logical bug in your code

**Comment by SteNeo** [comment] 2023-05-24 10:25
Thanks for taking the time.
the error showed up while upgrading flutter.
no code was open.

**Comment by dam-ease** [comment] 2023-05-24 12:50
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
IndexError: RangeError (index): Index out of range: index should be less than 63760932: 63868567
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4280:7)
#1      InputStream.readUint32 (package:archive/src/util/input_stream.dart:250:22)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:49:34)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:509:42)
#6      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1111:18)
<asynchronous suspension>
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:908:7)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#10     PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:168:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19045.2965], locale en-NA)
    • Flutter version 3.10.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\basimikes\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\basimikes\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.12 Preview 1.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.11.32407.337
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio\bin
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = C:\Program Files\Android\Android Studio\bin
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\basimikes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by eliasyishak** [comment] 2023-07-17 14:25
Closing this issue since this seems to be corrected when running the command

`flutter --no-color --no-version-check precache`

Feel free to reopen if you are still experiencing this issue – output from my doctor results

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.13.0-3.0.pre.27, on macOS 13.4.1 22F82 darwin-arm64, locale en)
    ! Upstream repository https://github.com/eliasyishak/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/eliasyishak/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources
```

**Closed by eliasyishak** 2023-07-17 14:25 UTC
Labels: c: crash, tool, platform-windows, team-tool
