### ISSUE TITLE
TextField strange behaviour with TextInputType.number on iPhone 6s

### ISSUE THREAD

**Issue by gmaggio** [flutter/flutter#25318] opened 2018-12-13 10:15 UTC
### Issue 1:
1. Use **iOS Simulator** with device **iPhone 6s** to run the app.
2. With the top **TextFields** being focused, **scroll down until the end**.
3. The screen will scroll back up to the focused **TextField**.

### Issue 2:
1. Use **iOS Simulator** with device **iPhone 6s** to run the app.
2. Keep tapping on one **TextField**.
3. It will type a dot with every tap.

### Issue 3:
This one uses `TextInputType.text`.
1. Use **iOS Simulator** with device **iPhone 6s** to run the app.
2. Use `TextInputType.text` instead of `TextInputType.number`.
3. - Keep tapping on one **TextField**. _or_
    - Keep typing on the **keyboard**.
4. The keyboard will change from alphabets to numerals and vice versa with every taps.

This does not happen with iPhone 7 or X (those are the ones I've tested so far). Not really sure if this is an issue with the **Simulator** _only_ or does it also happen in the actual device. I don't have a device to test yet.

```dart
import 'package:flutter/material.dart';

class TextFieldTest extends StatefulWidget {
  @override
  _TextFieldTestState createState() => _TextFieldTestState();
}

class _TextFieldTestState extends State<TextFieldTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Text Field Test')),
      body: Form(
        child: SingleChildScrollView(
          child: Column(
            children: List.generate(10, (index) {
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    'Input $index',
                  ),
                  TextField(
                    autofocus: (index == 0),
                    keyboardType: TextInputType.number,
                  ),
                ],
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

<details>
<summary> Logs</summary>

```
[  +45 ms] executing: [/Users/payfazz92/Library/Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/payfazz92/Library/Flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +1 ms] executing: [/Users/payfazz92/Library/Flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [/Users/payfazz92/Library/Flutter/] git log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/payfazz92/Library/Flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +3 ms] 13 days ago
[   +1 ms] executing: [/Users/payfazz92/Library/Flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +38 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +543 ms] Unable to locate an Android SDK.
[  +18 ms] Unable to locate an Android SDK.
[  +33 ms] executing: idevice_id -h
[  +66 ms] /usr/bin/xcrun simctl list --json devices
[ +349 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +10 ms] iPhone 6s • C1406F8F-4339-4993-9BA5-44DBA7EA048F • ios • iOS 12.1 (simulator)
[   +1 ms] iPhone 7  • E8A48647-36D5-416D-B3B4-1F06836BDD44 • ios • iOS 12.1 (simulator)
[        ] iPhone X  • 876F4F65-8062-4B31-8580-9DF2CAB1553A • ios • iOS 12.1 (simulator)
[  +63 ms] "flutter run" took 969ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:249:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/payfazz92/Library/Flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

### `flutter analyze`

```
Analyzing flutter_tests...
No issues found! (ran in 2.7s)
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-ID)
    • Flutter version 1.0.0 at /Users/payfazz92/Library/Flutter
    • Framework revision 5391447fae (13 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Volumes/Mobile/Library/Android/sdk
      but Android SDK not found at this location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (3 available)
    • iPhone 6s • C1406F8F-4339-4993-9BA5-44DBA7EA048F • ios • iOS 12.1 (simulator)
    • iPhone 7  • E8A48647-36D5-416D-B3B4-1F06836BDD44 • ios • iOS 12.1 (simulator)
    • iPhone X  • 876F4F65-8062-4B31-8580-9DF2CAB1553A • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```
</details>

**Comment by goderbauer** [comment] 2019-01-04 22:30
I am unable to re-produce any of the issues described here. Can you provide a complete code example that I can just copy & paste and run that shows the issue? Maybe I didn't embed your example correctly in an app?

**Comment by gmaggio** [comment] 2019-01-07 09:03
@goderbauer The code is exactly as above run using iOS Simulator with device iPhone 6s.

**Comment by zoechi** [comment] 2019-01-07 09:06
@gmaggio  

> The code is exactly as above

Above code is not runnable. It doesn't contain `main() {...}` so that's rather unlikely.

**Comment by gmaggio** [comment] 2019-01-07 09:32
@zoechi Oo... Okay.. sorry... It was called via this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_tests/text-field.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TextFieldTest(),
    );
  }
}
```

**Comment by alexandergottlieb** [comment] 2019-03-15 09:01
I was seeing this behaviour too, but restarting the simulator fixed it.

**Comment by pedromassangocode** [comment] 2020-07-24 12:55
Hi @gmaggio 
I can't reproduce this with iPhone 6s simulator on the latest `dev` channel.

Closing as probably fixed. Please comment if you disagree and I will reopen it.


<details>
<summary> Complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TextFieldTest(),
    );
  }
}

class TextFieldTest extends StatefulWidget {
  @override
  _TextFieldTestState createState() => _TextFieldTestState();
}

class _TextFieldTestState extends State<TextFieldTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Text Field Test')),
      body: Form(
        child: SingleChildScrollView(
          child: Column(
            children: List.generate(10, (index) {
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    'Input $index',
                  ),
                  TextField(
                    autofocus: (index == 0),
                    keyboardType: TextInputType.text,
                  ),
                ],
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (9 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter
      Tools

! Doctor found issues in 1 category.
```
</details>

**Closed by pedromassangocode** 2020-07-24 12:55 UTC
Labels: P4, a: text input, e: device-specific, framework, platform-ios
