### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by FuturetheCoder** [flutter/flutter#75946] opened 2021-02-13 00:05 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel beta, 1.20.2, on Microsoft Windows [Version 10.0.19042.631], locale en-NG)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (6 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\FutureAlex\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.53.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d

**Comment by iapicca** [comment] 2021-02-13 08:04
duplicate of https://github.com/flutter/flutter/issues/69116

@FuturetheCoder 
please try this possible [solution](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)

**Comment by darshankawar** [comment] 2021-02-15 08:08
Closing this as duplicate of https://github.com/flutter/flutter/issues/69116

**Closed by darshankawar** 2021-02-15 08:08 UTC
