### ISSUE TITLE
Error using ListView + Expandable Item + TextField

### ISSUE THREAD

**Issue by rmarau** [flutter/flutter#18276] opened 2018-06-07 17:46 UTC
Using a ListView with variable size items (expandable) and a TextField input leads to:

> flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> flutter: The following assertion was thrown building NotificationListener<KeepAliveNotification>:
> flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2756 pos 14:
> flutter: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.

I'm using the beta branch v0.4.4 (tested with master as well).

To reproduce:
Follow this [gist](https://gist.github.com/rmarau/baa31a9c4032de388a2b7777c8bae27e)

1. Tap an Item to expand.
2. Tap the TextField to get focus
3. Scroll down (3 strong swipes should be enough)
4. Tap a random item to expand.
You should be hitting the assertion, in debug mode. Running in release, the assertion is not verified but the list gets clipped at the top.

This might be related to #18063: Same assertion but a different context.

**Comment by chinmaygarde** [comment] 2018-06-09 00:55
cc @Hixie, @HansMuller

**Comment by Hixie** [comment] 2018-06-12 22:41
Duplicate of https://github.com/flutter/flutter/issues/11895.

**Closed by Hixie** 2018-06-12 22:41 UTC
Labels: framework
