### ISSUE TITLE
Device freeze when open maps on certain devices

### ISSUE THREAD

**Issue by rafaelcorbellini-egsys** [flutter/flutter#35809] opened 2019-07-09 16:40 UTC
The whole device freezes, after I navigate the map for about 1/2 seconds, the device comes to restart after this, test was done more than one device and in both happened same behavior, the source code used was the example of the own maps library.

## Steps to Reproduce

1. Create a sample maps aplication.
2. Install on Moto X (gen 2) Lenovo
3. Open application and tap on maps moving screen, about 1/2 second it will freeze entire device.

I did the test using two different devices, both moto x gen 2 is factory reset (Android 6.0), only update maps app and play service (version of play service 17.7.85),

I have also tried to give the location permissions and install the application directly as an APK and in both cases the behavior has remained. 

## Logs

```
Launching lib/main.dart on XT1097 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/zzbz    ( 8266): Making Creator dynamically
I/DynamiteModule( 8266): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule( 8266): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
V/DynamiteModule( 8266): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System  ( 8266): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000009/n/armeabi-v7a
W/System  ( 8266): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000009/n/armeabi
I/Google Maps Android API( 8266): Google Play services client version: 12451000
I/Google Maps Android API( 8266): Google Play services package version: 17785018
E/GoogleMapController( 8266): Cannot enable MyLocation layer as location permissions are not granted
W/DynamiteModule( 8266): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 8266): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule( 8266): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/System  ( 8266): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a
W/System  ( 8266): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/00000008/n/armeabi

```

```
Analyzing teste_maps...                                                 
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/rafael/development/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/rafael/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/rafael/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/rafael/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/rafael/IntelliJ-181.5281.24
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • XT1097 • 0018717405 • android-arm • Android 6.0 (API 23)
```

**Comment by rafaelcorbellini-egsys** [comment] 2019-08-13 19:28
Anothers inssues, i think can be the same:

https://github.com/flutter/flutter/issues/26345
https://github.com/flutter/flutter/issues/27190

**Comment by raphaelkieling** [comment] 2019-08-23 14:29
any update? This is very serious because my app is totaly focused on maps... exactly same problem here :(

**Comment by yuridiniz** [comment] 2019-08-24 16:01
This also happens on the LG K10 Android 7, it does not happen all the time, but in the moments that happens I had to remove the battery, also makes the device very hot

**Comment by TahaTesser** [comment] 2020-03-04 15:36
Could be related [#36125](https://github.com/flutter/flutter/issues/36125)

**Comment by mshahzaib1629** [comment] 2020-05-03 09:28
Facing same issue. Tested the app on number of devices, although I have shifted to Flutter's master channel "1.18.0-9.0.pre.93" with google_maps_flutter "^0.5.27"

**Comment by cristianonescu** [comment] 2020-05-28 01:26
I have the same issue on S9+, looks like it freezes when it is resized (like when I open the keyboard)

**Comment by TahaTesser** [comment] 2021-04-29 11:48
Hi @raphaelkieling  @cristianonescu 
` Moto X (gen 2) Lenovo` & `LG K10 Android 7, ` are older devices and crash on S9+ probably not related which is much newer, if it Is not a common crash, it's unlikely they're related. 

Anyone still experiencing this issue, can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by cristianonescu** [comment] 2021-04-29 11:51
@TahaTesser this was almost a year ago.. lol. I don't even remember the context of the issue.. now that's a fast support reply :)))

**Comment by TahaTesser** [comment] 2021-05-27 12:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:49 UTC
Labels: e: device-specific, p: first party, p: maps, platform-android, plugin
