### ISSUE TITLE
flutter/plugins pubspec presubmit needs tweaking

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44749] opened 2019-11-12 19:30 UTC
Relatively recently we added a presubmit that attempts to verify that each PR increments the major, minor, or patch version in the `pubspec.yaml`.

It appears to be letting through false negatives in cases where the `pubspec.yaml` is never changed, but the `CHANGELOG` is updated: flutter/plugins#2242 

This then cascades into later false positives, where future PRs are blocked for having incremented the pubspec.yaml version "too much": flutter/plugins#2264 

_Edit: @cyanglaz mentioned that the check deliberately ignores `CHANGELOG`, so that's what should probably be fixed here._

**Comment by godofredoc** [comment] 2019-11-14 23:34
Do you know if this is a test problem or a race condition in infra?

**Comment by mklim** [comment] 2019-11-15 18:03
I haven't looked deeply into this but I think it's just an issue with the test itself. I'm pretty sure it's not catching all the changes that it should be linting for. I think it may only be checking to see if the `pubspec.yaml` file was changed and then failing then if the version upgrade wasn't right, when we should at least be checking for `CHANGELOG` too (and maybe any changed files at all).

Our entire infra has a race condition that can sort of effect his, where presubmits are run on the branch as they are and not the branch's changes applied to tip of tree master. So occasionally there are failures in post submit that "should" have gotten caught in presubmit, but the branch was too outdated to be tested in the failing state. But I don't think that's the main problem here.

**Comment by jmagman** [comment] 2019-11-19 21:13
Is this a duplicate of https://github.com/flutter/flutter/issues/15803?

**Comment by mklim** [comment] 2019-11-19 22:02
I think this has a little more information about the current state of the world than that one, it was written before we had any checks at all. But having both seems redundant. I'll close the older in favor of this one.

**Comment by stuartmorgan** [comment] 2021-05-24 23:35
We're validating across the two files now, so closing as fixed.

**Closed by stuartmorgan** 2021-05-24 23:35 UTC
Labels: passed secondary triage, plugin, team: infra
