### ISSUE TITLE
hot_reload_web_test timed out after 15 seconds twice on Linux tool_tests

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#69806] opened 2020-11-04 20:32 UTC
```
01:42 +4 ~6: test/integration.shard/hot_reload_web_test.dart: newly added code executes during hot restart                                                                                             
Running "flutter pub get" in flutter_hot_reload_test.FPQLTJ...
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":7245}}]
[{"event":"app.start","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","deviceId":"chrome","directory":"/b/s/w/ir/tmp/t/flutter_hot_reload_test.FPQLTJ","supportsRestart":true,"launchMode":"run"}}]
Launching lib/main.dart on Chrome in debug mode...
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"1","progressId":null,"message":"Syncing files to device Chrome...","finished":false}}]
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"1","progressId":null,"finished":true}}]
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:45035","launched":true}}]
Debug service listening on ws://127.0.0.1:38117/vzHejln99Tc=/ws
[{"event":"app.started","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15"}}]
[{"event":"app.debugPort","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","port":38117,"wsUri":"ws://127.0.0.1:38117/vzHejln99Tc=/ws"}}]
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"2","progressId":"hot.restart","message":"Performing hot restart...","finished":false}}]
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"3","progressId":null,"message":"Syncing files to device Chrome...","finished":false}}]
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"3","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"d35b5839-75ae-4020-a969-11312a371d15","id":"2","progressId":"hot.restart","finished":true}}]
Restarted application in 566ms.
[{"id":1,"result":{"code":0,"message":""}}]

02:21 +4 ~6 -1: test/integration.shard/hot_reload_web_test.dart: newly added code executes during hot restart [E]                                                                                      
  TimeoutException after 0:00:15.000000: Future not completed
  dart:isolate  _RawReceivePortImpl._handleMessage
  
Retry: newly added code executes during hot restart
Running "flutter pub get" in flutter_hot_reload_test.KWHECP...
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":7492}}]
[{"event":"app.start","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","deviceId":"chrome","directory":"/b/s/w/ir/tmp/t/flutter_hot_reload_test.KWHECP","supportsRestart":true,"launchMode":"run"}}]
Launching lib/main.dart on Chrome in debug mode...
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"1","progressId":null,"message":"Syncing files to device Chrome...","finished":false}}]
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"1","progressId":null,"finished":true}}]
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:41979","launched":true}}]
Debug service listening on ws://127.0.0.1:36269/1CeYz5tnC9M=/ws
[{"event":"app.started","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669"}}]
[{"event":"app.debugPort","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","port":36269,"wsUri":"ws://127.0.0.1:36269/1CeYz5tnC9M=/ws"}}]
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"2","progressId":"hot.restart","message":"Performing hot restart...","finished":false}}]
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"3","progressId":null,"message":"Syncing files to device Chrome...","finished":false}}]
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"3","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"b0826c64-268e-4708-9473-ad8bcc93a669","id":"2","progressId":"hot.restart","finished":true}}]
Restarted application in 550ms.
[{"id":1,"result":{"code":0,"message":""}}]
  TimeoutException after 0:00:15.000000: Future not completed
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864533202004186720/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout

**Comment by jmagman** [comment] 2020-11-04 20:33
First seen on https://github.com/flutter/flutter/commit/0ddb1ae7133fab86564d05e5e8f9c4ba5df10d5f @jonahwilliams

**Comment by jonahwilliams** [comment] 2020-11-04 20:53
Dupe of https://github.com/flutter/flutter/issues/69804 .

Its unrelated to that commit, I've seen this on and off since I turned them. Hoping they just go away is not a strategy

**Closed by jonahwilliams** 2020-11-04 20:53 UTC
Labels: a: tests, team, team: flakes, tool
