### ISSUE TITLE
Issues with the new `SliverAppBar.medium` and `SliverAppBar.large`

### ISSUE THREAD

**Issue by iamcosmin** [flutter/flutter#104363] opened 2022-05-22 18:48 UTC
## Introduction
Since #103962, we can use the new Material 3 medium top app bar and large top app bar, though there are a few bugs regarding the use of SliverAppBar.medium and SliverAppBar.large in both CustomScrollView and NestedScrollView.

## Split issues

- [ ] #104437 
- [x] #104440 
- [ ] #104442

**Comment by TahaTesser** [comment] 2022-05-23 09:05
Hi @iamcosmin 
This is in-depth and well explained for a first issue.

I can reproduce all the scenarios mentioned above, this might need to be split into multiple issues tho.

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 3.1.0-0.0.pre.854, on macOS 12.4 21F79 darwin-arm,
    locale en-GB)
    • Flutter version 3.1.0-0.0.pre.854 at
      /Users/tahatesser/Code/flutter_nevercode
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • Framework revision ec20ea80ad (2 days ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 12D2D2A6-4358-456B-BBDE-A7B7D5EB83D3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
	 
</details>

**Comment by iamcosmin** [comment] 2022-05-23 10:32
As I tested more, in the CustomScrollView, setting the scrollBehavior to CupertinoScrollBehavior acts as expected, it does not scroll the SliverAppBar. So I think the problem here is with the new overscroll effect of MaterialScrollBehaviour.

As per splitting issues, I think I will make 2 separate issues, one regarding CustomScrollView and one regarding NestedScrollView. Is that a good idea?

**Comment by HansMuller** [comment] 2022-05-23 16:38
CC @darrenaustin

**Comment by darrenaustin** [comment] 2022-05-23 17:47
I need some time to look into this, but @Piinks may know more about what is going on here.

**Comment by Piinks** [comment] 2022-05-23 18:07
This should be split up into individual issues.

**Comment by iamcosmin** [comment] 2022-05-23 19:44
I have split this issue into individual ones and I have updated this issue to include references to those issues.

**Comment by Piinks** [comment] 2022-05-23 22:20
Thank you! It was very helpful to be able to look at them individually - it looks like you found your way to the right composition and found a bug in https://github.com/flutter/flutter/issues/104442
I am working on a fix for it now.

**Comment by Piinks** [comment] 2022-05-24 20:11
I think we can close this issue, the remaining issues have a PR out to resolve or have been triaged and labeled properly to be followed up on. Thank you for your detailed reporting!

**Closed by Piinks** 2022-05-24 20:11 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.0, found in release: 3.1
