### ISSUE TITLE
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

### ISSUE THREAD

**Issue by libaipengl** [flutter/flutter#152063] opened 2024-07-20 09:52 UTC
### Steps to reproduce

Real iPhone 11
ISO version 17.5.1
It is normal in Android
  
<img width="1888" alt="37E985EC5203E2B6CE13AC29668B4548" src="https://github.com/user-attachments/assets/3973071f-22f5-4c8a-be32-d4f9130659b9">

### Expected results

 
Generate an image

### Actual results

Cannot generate an image

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'dart:typed_data';
import 'dart:ui' as ui;
void main() => runApp(const MaterialApp(home: CameraPage()));

class CameraPage extends StatefulWidget {
  const CameraPage({Key? key}) : super(key: key);

  @override
  CameraPagePagestate createState() => CameraPagePagestate();
}

class CameraPagePagestate extends State<CameraPage> {

  final GlobalKey globalKey = GlobalKey();



  Future<void> _capturePng(globalKeys) async {
    RenderRepaintBoundary? boundary = globalKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
    if (boundary != null) {
      try {
        // 图像捕获之前的确保
        if (!mounted) return;
        ui.Image image = await boundary.toImage(pixelRatio: 1.0);
        ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
        if (byteData != null) {
          Uint8List pngBytes = byteData.buffer.asUint8List();
          print('${pngBytes.length} ');
        } else {
          print('errot');
        }
      } catch (e) {
        print('errot：$e');
      }
    } else {
      print("errot");
    }
  }
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      backgroundColor: Colors.purple,

      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: (){
          _capturePng(globalKey);
          print('FloatingActionButton');
        },
      ),
      body: RepaintBoundary(
        key: globalKey,
        child: Center(
          child: Text("This i am "),
        ),
      ) ,

    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

 
<img width="1888" alt="37E985EC5203E2B6CE13AC29668B4548" src="https://github.com/user-attachments/assets/3eaf3421-1bb6-4f81-9e47-a08958535519">

</details>

### Logs

<details open><summary>Logs</summary>

```nehelper sent invalid result code [1] for Wi-Fi information request
Cannot start load of Task <51ACA009-6930-4A89-8A07-FD16414325DF>.<1> since it does not conform to ATS policy
Task <51ACA009-6930-4A89-8A07-FD16414325DF>.<1> finished with error [18,446,744,073,709,550,594] Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://dualstack-restios.amap.com/sdk/compliance/params, NSErrorFailingURLKey=http://dualstack-restios.amap.com/sdk/compliance/params, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <51ACA009-6930-4A89-8A07-FD16414325DF>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <51ACA009-6930-4A89-8A07-FD16414325DF>.<1>, NSUnderlyingError=0x3030ebcc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}
Cannot start load of Task <06BA5F7F-3EB0-4A3C-8FE6-4B863D5FACAC>.<4> since it does not conform to ATS policy
Task <06BA5F7F-3EB0-4A3C-8FE6-4B863D5FACAC>.<4> finished with error [18,446,744,073,709,550,594] Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://restios.amap.com/sdk/compliance/params, NSErrorFailingURLKey=http://restios.amap.com/sdk/compliance/params, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <06BA5F7F-3EB0-4A3C-8FE6-4B863D5FACAC>.<4>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <06BA5F7F-3EB0-4A3C-8FE6-4B863D5FACAC>.<4>, NSUnderlyingError=0x3030b28e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}
tcp_input [C1.1.1.1:3] flags=4 seq=1,314,572,892, ack=4,255,621,447, win=0 state=8 rcv_nxt=1,314,572,892, snd_una=3,047,883,365
tcp_input [C2.1.1:3] flags=4 seq=1,235,817,609, ack=889,518,543, win=0 state=8 rcv_nxt=1,235,817,609, snd_una=791,022,336
flutter: Capturing picture...
[ERROR:flutter/shell/common/shell.cc(1065)] The 'audio_streamer.eventChannel' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
nehelper sent invalid result code [1] for Wi-Fi information request
nehelper sent invalid result code [1] for Wi-Fi information request
flutter: FloatingActionButton
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.1 23B74 darwin-arm64,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-22 06:53
Hi @libaipengl, this has been fixed on the master channel as I could reproduce the crash on beta but on master the image was generated as expected. I tested with the code sample provided above. 

Per our triage policy, I'll be closing this since it has been fixed on the master channel. If you run into this issue on master version `3.24.0-1.0.pre.214`  and above, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2024-07-22 06:53 UTC
Labels: in triage
