### ISSUE TITLE
Migrating from flutter_driver When use integration_test,it cause 'Flutter Driver extension is taking a long time to become available'.

### ISSUE THREAD

**Issue by songtangjie** [flutter/flutter#73230] opened 2021-01-03 06:09 UTC
<details> 
<summary>code sample</summary> 

```dart
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:integration_test_example/main.dart' as app;

import '_example_test_io.dart' if (dart.library.html) '_example_test_web.dart'
    as tests;

void main() {
  
  group('integration test', () {
    setUpAll(() async {
      IntegrationTestWidgetsFlutterBinding.ensureInitialized();
    });

    testWidgets('verify text', (WidgetTester tester) async {
    // Build our app and trigger a frame.
      app.main();
      await tester.pumpAndSettle();

      await Future<void>.delayed(const Duration(seconds: 1));

      await tester.tap(find.text("RaisedButton"));
      await tester.pumpAndSettle();

      await Future<void>.delayed(const Duration(seconds: 1));

      expect(find.text('First'), findsOneWidget);
    });
  });
}
``` 

</details>
When I follow the example and tried to modify the driver code to the new integration_test, it could not run.
https://flutter.cn/docs/testing/integration-tests

<details> 
<summary>logs</summary> 

```bash
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:64672/p1y7o1D34Ks=/
VMServiceFlutterDriver: url:http://127.0.0.1:64672/p1y7o1D34Ks=/--------------webSocketUrl:ws://127.0.0.1:64672/p1y7o1D34Ks=/ws-----------
VMServiceFlutterDriver: Isolate found with number: 116146977440703
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: integration test (setUpAll)
flutter: 00:00 +0: integration test (setUpAll) [E]
flutter:   'package:integration_test/integration_test.dart': Failed assertion: line 130 pos 12: 'WidgetsBinding.instance is IntegrationTestWidgetsFlutterBinding': is not true.
flutter:   dart:core-patch/errors_patch.dart 46:39                                                        _AssertionError._doThrowNew
  dart:core-patch/errors_patch.dart 36:5                                                         _AssertionError._throwNew
  package:integration_test/integration_test.dart 130:12                                          IntegrationTestWidgetsFlutterBinding.ensureInitialized
  Users/william/Desktop/integration_test-1.0.1/example/integration_test/example_test.dart 19:44  main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 310:70                                              Declarer._setUpAll.<fn>.<fn>.<fn>
  dart:async/future.dart 512:26                                                                  Future.forEach.<fn>
  dart:async/future.dart 554:26                                                                  Future.doWhile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26                                   StackZoneSpecification._re<…>
flutter: 00:00 +0 -1: integration test (tearDownAll)
flutter: 00:00 +1 -1: Some tests failed.
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
```

</details>

**Comment by TahaTesser** [comment] 2021-01-04 11:16
Hi @songtangjie 
Can you please provide your `flutter doctor -v`  and a complete reproducible minimal code sample in a GitHub repository
Thank you

**Comment by zmeggyesi** [comment] 2021-01-04 12:27
I'm seeing the same issue under 1.22.5
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (3 weeks ago) • 2020-12-10 11:54:40 -0800
```

Strangely, it only seems to manifest when trying to run the tests under Firebase Test Lab devices?

**Comment by zmeggyesi** [comment] 2021-01-04 12:34
Actually seems to be a duplicate of #72063?

**Comment by TahaTesser** [comment] 2021-01-05 10:57
Hi @zmeggyesi 
Thanks, I wanted to double-check. With confirmation, I feel safe to close this as duplicate https://github.com/flutter/flutter/issues/72063
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-05 10:57 UTC
Labels: in triage, waiting for customer response
