### ISSUE TITLE
Support text capitalization in TextStyle

### ISSUE THREAD

**Issue by mfiels** [flutter/flutter#22695] opened 2018-10-04 21:36 UTC
Inspiration taken from [CSS text-transform](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform), which helps keep the separation between style and structure clean.

It would be nice to be able to specify how text should be capitalized when rendered via TextStyle.

Let's say UX convention is that all buttons in the application should have uppercase text.

Currently I have to do something like:
-------------------------------------------------

```dart
Text(someString.toUpperCase(), style: Theme.of(context).button),
```

Which means I have to remember to call `toUpperCase()` **everywhere** I use the button TextStyle.

I'd love to be able to do something like this instead:
-----------------------------------------------

```dart
// When setting up my application theme:
final button = TextStyle(
  transform: TextTransform.capitalize,
  ...
)
```

Now I don't have to remember to call `toUpperCase()` everywhere:

```dart
Text(someString, style: Theme.of(context).button),
```

**Comment by Hixie** [comment] 2018-10-04 22:04
The problem is that capitalisation is a really complex problem, usually best done by humans and not by computers. For example, a human would know not to capitalize the "z" in `SET FREQUENCY TO 5Hz`, but a computer would not. It also varies dramatically from language to language. So generally we would recommend doing this kind of thing in the localization (translation) pipeline rather than in the styles. If we went down the road the CSS went down, we would just be propagating a sketchy design choice.

**Comment by Hixie** [comment] 2018-10-04 22:05
(I should add that calling `toUpperCase` is equally bad -- in fact it's worse, because it doesn't have locale information, so it would, for example, never be correct for Turkish.)

**Comment by mehmetf** [comment] 2018-10-04 22:44
Yes, I was thinking about this purely from API point of view but Ian is absolutely right. This is akin to pluralization.

Turkish is a great example due to the difference between i and ı whose uppercase representation, respectively, are İ and I.

I will close this as working as intended and advise the customer to create capitalized resources that need to be translated separately.

**Closed by mehmetf** 2018-10-04 22:44 UTC
Labels: customer: fun (g3)

**Comment by aryzhov** [comment] 2019-07-10 01:40
Here's a suggestion: the support for small caps / all caps could be implemented at font face level which can be specified as `capitalization: normal | smallcaps | allcaps` in `pubspec.yaml`. If a font does not have an `allcaps` font face, it could be simulated by `toUpperCase()`, and `smallcaps` could be simulated by using different sizes of the same font. Please reopen.

**Comment by dfmiller** [comment] 2019-10-24 21:03
This should use the same rules as CSS.  If the text I'm showing does not show Turkish or frequencies then why should I be prevented from using toUpperCase or a text transformation?

**Comment by sthamaloshada** [comment] 2020-03-31 17:44
You can't do this via TextStyle.

you can use string methods,

```
.toUpperCase()
.toLowerCase()
```

Example: "Your text".toUpperCase()
