### ISSUE TITLE
Camera video size too big on only iOS

### ISSUE THREAD

**Issue by TJ543** [flutter/flutter#25383] opened 2018-12-14 18:44 UTC
I just captured video about 10 seconds by using camera plugin and uploaded to firebase storage.
On Android, size only 1.2MB but on iOS size 15.6MB.
Is there anything I can do to reduce size?

**Comment by zoechi** [comment] 2018-12-17 10:08
Duplicate of #23410

**Closed by zoechi** 2018-12-17 10:08 UTC
