### ISSUE TITLE
Map<K,V> Operator [] ignores type

### ISSUE THREAD

**Issue by paulsump** [flutter/flutter#94588] opened 2021-12-03 02:41 UTC
the class pretends to be a generic, but the parameter is Object? object, which hides errors because it ignores the type you pass in.  It's unexpected, and you need to look at the function definition to work out the reason.  The function should take a value of type K.  Also containsKey(Object? object) and others.

**Comment by paulsump** [comment] 2021-12-03 02:43
e.g. Map<String, Whatever> map;
int bug = 3;
map[bug] // should be an error.

**Comment by stuartmorgan** [comment] 2021-12-03 03:09
Duplicate of https://github.com/dart-lang/sdk/issues/47201

(In the future please file issues about Dart itself in the Dart repository; the Dart language and Dart SDK aren't part of the Flutter project.)

**Closed by stuartmorgan** 2021-12-03 03:09 UTC

**Comment by paulsump** [comment] 2021-12-03 03:14
the duplicate is closed, now this is closed.  The issue still exists though!
________________________________
