### ISSUE TITLE
Improve BottomNavigationBar.title deprecation assertion message

### ISSUE THREAD

**Issue by martipello** [flutter/flutter#70605] opened 2020-11-16 11:08 UTC
## Steps to Reproduce

Using the Bottom navigation bar, add some items using the new label property and one using the now deprecated title property, 

**Expected results:** 

Expected to see the bottom navigation bar working as normal 

**Actual results:** 

App crashes with exception items.every(BottomNavigationBarItem item) => item.label != null : Every item must have a non-null title or label

Bottom navigation bar doesn't allow for having a mismatch of items using either label or title, all items must use either title or label exclusively I'd like to use title for one of my items as i want it to look selected even when not officially selected, to be honest I think the title property shouldn't have been deprecated but maybe renamed, we the developers should just have the choice to use one or the other based on our requirements, as having a widget here is super useful

**Comment by pedromassangocode** [comment] 2020-11-16 11:18
Hi @martipello 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by martipello** [comment] 2020-11-16 13:00
> Hi @martipello
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

no, sorry I'm very busy, flutter doctor won't tell you anything its very easily reproducible even on the flutter example here https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html , if i could do that I'd probably just make a pull request, if you don't want to so be it

**Comment by HansMuller** [comment] 2020-11-16 22:46
The label and title assert/deprecation changes were made in https://github.com/flutter/flutter/pull/59127. 

I think the problem is that the assert:
```dart
assert(
  items.every((BottomNavigationBarItem item) => item.title != null) ||
  items.every((BottomNavigationBarItem item) => item.label != null),
  'Every item must have a non-null title or label',
),
```
Is checking that either all of the items have a label or they all have a title. This seems reasonable, since the idea is for developers to migrate (all at once) to the label property. Unfortunately, the error message is misleading.

**Comment by martipello** [comment] 2020-11-17 08:39
or you could let us use the title property or the label property, and just show a warning that it doesn't support tooltips

**Comment by pedromassangocode** [comment] 2020-11-17 09:50
@martipello The idea is for developers to migrate all at once as said above, because deprecated properties will be removed in the future and you don't want to face this problem later.

**Comment by martipello** [comment] 2020-11-17 10:04
@pedromassango im well aware of that im proposing that it shouldnt be deprecated as it serves a real purpose and going from using a widget to a string kills this functionality

**Comment by Piinks** [comment] 2024-09-11 21:27
BottomNavigationBar.title was removed a while ago after the deprecation period ended. I am going to close this issue since it does not exist anymore.

**Closed by Piinks** 2024-09-11 21:27 UTC
Labels: framework, f: material design, c: proposal, a: error message, P2, team-design, triaged-design
