### ISSUE TITLE
Unable to change Text's fontWeight

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#51564] opened 2020-02-27 14:43 UTC
I cannot update Text's fontWeight: setting it does nothing.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` as follows: 

``` dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(primarySwatch: Colors.blue);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: theme,
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
              style: Theme.of(context)
                  .textTheme
                  .headline6
                  .copyWith(fontWeight: FontWeight.w700),
            ),
          ],
        ),
      ),
    );
  }
}
```
3. See the text is not bold.

I'm using version 1.15.3

**Comment by VladyslavBondarenko** [comment] 2020-02-27 15:33
Hi @agordeev 
Are you experiencing this with iOS? 
checked and it's working for Android

probably related to https://github.com/flutter/flutter/issues/49492

**Comment by dnfield** [comment] 2020-02-27 21:45
This is almost certainly a duplicate of https://github.com/flutter/flutter/issues/49492 - please comment here if you are not using iOS and we will reopen.

**Closed by dnfield** 2020-02-27 21:45 UTC
Labels: waiting for customer response
