### ISSUE TITLE
page A navigator to Page B, I use ReorderableListView show a list of textfields, the textfields lost focus immediately after I tap on textfield

### ISSUE THREAD

**Issue by zxhwyp** [flutter/flutter#25839] opened 2018-12-28 12:54 UTC
```dart
void main() => runApp(MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TapClass(),
    ));

class TapClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('widget'),
        ),
        body: Center(
          child: FlatButton(
            child: Text('click me'),
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (context) => MyHomePage()));
            },
          ),
        ));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final childrens = <String>['1', '2', '3'];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('widget'),
        ),
        body: ReorderableListView(
          children: childrens.map((element) {
            return Row(
              key: ValueKey(element),
              children: <Widget>[
                Expanded(
                  child: Container(
                    margin: EdgeInsets.fromLTRB(20, 5, 20, 5),
                    decoration: BoxDecoration(
                      color: Color.fromRGBO(244, 245, 246, 1.0),
                      borderRadius: BorderRadius.all(Radius.circular(5.0)),
                    ),
                    child: TextField(
                      style: TextStyle(color: Colors.black, fontSize: 17),
                      decoration: InputDecoration(
                          contentPadding: EdgeInsets.fromLTRB(5, 5, 5, 5),
                          border: InputBorder.none,
                          hintText: 'type in'),
                    ),
                  ),
                )
              ],
            );
          }).toList(),
          onReorder: (int oldIndex, int newIndex) {
            print('oldIndex = $oldIndex, newIndex = $newIndex');
          },
        ));
  }
}
```

**Comment by zoechi** [comment] 2018-12-28 13:00
Duplicate of #25836

**Comment by zoechi** [comment] 2018-12-28 13:00
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Closed by zoechi** 2018-12-28 13:00 UTC
