### ISSUE TITLE
Android app fails to launch on API 21

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#73118] opened 2020-12-29 23:01 UTC
## Steps to Reproduce

1. Use `beta` channel (currently 1.25.0-8.1.pre]
2. Create a new project with `flutter create foobar`
3. Using a real Android 21 device (mine is a XT 1033 - MotoG 1st Edition with Android 5.0.2), `flutter run`

## Logs

<details>
<summary>Logs</summary>

```
 jckodel@mac  ~/foobar  flutter run                                                                                                             ✔  19:55:53
Multiple devices found:
XT1033 (mobile)                      • 0423490246                           • android-arm    • Android 5.0.2 (API 21)
iPod touch (7th generation) (mobile) • BDDD58F5-7397-4868-ABA8-81946FA2F9B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
Chrome (web)                         • chrome                               • web-javascript • Google Chrome 87.0.4280.88
[0]: XT1033 (0423490246)
[1]: iPod touch (7th generation) (BDDD58F5-7397-4868-ABA8-81946FA2F9B8)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 0
Launching lib/main.dart on XT1033 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        25.0s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                41.6s
E/AndroidRuntime(17794): FATAL EXCEPTION: main
E/AndroidRuntime(17794): Process: com.example.foobar, PID: 17794
E/AndroidRuntime(17794): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.foobar/com.example.foobar.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(17794): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
E/AndroidRuntime(17794): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
E/AndroidRuntime(17794): 	at android.app.ActivityThread.access$800(ActivityThread.java:148)
E/AndroidRuntime(17794): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
E/AndroidRuntime(17794): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17794): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17794): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime(17794): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17794): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17794): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(17794): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime(17794): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(17794): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2431)
E/AndroidRuntime(17794): 	at android.content.res.Resources.loadDrawable(Resources.java:2333)
E/AndroidRuntime(17794): 	at android.content.res.Resources.getDrawable(Resources.java:758)
E/AndroidRuntime(17794): 	at android.content.res.Resources.getDrawable(Resources.java:724)
E/AndroidRuntime(17794): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:493)
E/AndroidRuntime(17794): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(17794): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(17794): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
E/AndroidRuntime(17794): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:415)
E/AndroidRuntime(17794): 	at android.app.Activity.performCreate(Activity.java:5953)
E/AndroidRuntime(17794): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
E/AndroidRuntime(17794): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
E/AndroidRuntime(17794): 	... 10 more
E/AndroidRuntime(17794): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(17794): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:202)
E/AndroidRuntime(17794): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
E/AndroidRuntime(17794): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
E/AndroidRuntime(17794): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
E/AndroidRuntime(17794): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2421)
E/AndroidRuntime(17794): 	... 21 more
Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".
```

```
 jckodel@mac  ~/foobar  flutter doctor -v                                                                                                                                                                                   ✔  19:59:48
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-BR)
    • Flutter version 1.25.0-8.1.pre at /Users/jckodel/flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jckodel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/jckodel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • XT1033 (mobile)                      • 0423490246                           • android-arm    • Android 5.0.2 (API 21)
    • iPod touch (7th generation) (mobile) • BDDD58F5-7397-4868-ABA8-81946FA2F9B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2020-12-30 08:35
Hi @JCKodel 
The crash is due to xml file inyour code, it's not related to Flutter itself
```bash
E/AndroidRuntime(17794): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.foobar/com.example.foobar.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000

E/AndroidRuntime(17794): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000

E/AndroidRuntime(17794): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
```

Missing resources in your Android project, open `android` folder of your project in Android Studio, fix the error you may encounter, and then run your Flutter app 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by TahaTesser** [comment] 2020-12-30 08:53
Hi @JCKodel 
Closed by accident, does it reproduce using the emulator or any other physical device? 
Can you please provide your `flutter run --verbose` and also can you please try the `master` channel and confirm it works  or not.

`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by JCKodel** [comment] 2020-12-30 16:10
Master doctor:

<details>
<summary>Logs</summary>
```
jckodel@mac  ~  flutter doctor -v                                                                                                              ✔  12:48:00
Downloading package sky_engine...                                  611ms
Downloading flutter_patched_sdk tools...                           651ms
Downloading flutter_patched_sdk_product tools...                   486ms
Downloading darwin-x64 tools...                                  1,472ms
Downloading darwin-x64/font-subset tools...                        210ms
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on macOS 11.1 20C69 darwin-x64, locale en-BR)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/jckodel/flutter
    • Framework revision 4b83be6c23 (9 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jckodel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/jckodel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • XT1033 (mobile) • 0423490246 • android-arm    • Android 5.0.2 (API 21)
    • Chrome (web)    • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>

Executing the same test, on the same device, the same error:

```
jckodel@mac  ~/foobar  flutter run                                                                                                             ✔  13:07:25
Downloading android-arm-profile/darwin-x64 tools...                642ms
Downloading android-arm-release/darwin-x64 tools...                244ms
Downloading android-arm64-profile/darwin-x64 tools...              242ms
Downloading android-arm64-release/darwin-x64 tools...              221ms
Downloading android-x64-profile/darwin-x64 tools...                230ms
Downloading android-x64-release/darwin-x64 tools...                214ms
Downloading Web SDK...                                           1,342ms
Launching lib/main.dart on XT1033 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        34.0s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                47.9s
E/AndroidRuntime(31928): FATAL EXCEPTION: main
E/AndroidRuntime(31928): Process: com.example.foobar, PID: 31928
E/AndroidRuntime(31928): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.foobar/com.example.foobar.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(31928): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
E/AndroidRuntime(31928): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
E/AndroidRuntime(31928): 	at android.app.ActivityThread.access$800(ActivityThread.java:148)
E/AndroidRuntime(31928): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
E/AndroidRuntime(31928): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31928): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(31928): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime(31928): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31928): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31928): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(31928): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime(31928): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(31928): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2431)
E/AndroidRuntime(31928): 	at android.content.res.Resources.loadDrawable(Resources.java:2333)
E/AndroidRuntime(31928): 	at android.content.res.Resources.getDrawable(Resources.java:758)
E/AndroidRuntime(31928): 	at android.content.res.Resources.getDrawable(Resources.java:724)
E/AndroidRuntime(31928): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:493)
E/AndroidRuntime(31928): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(31928): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(31928): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
E/AndroidRuntime(31928): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:415)
E/AndroidRuntime(31928): 	at android.app.Activity.performCreate(Activity.java:5953)
E/AndroidRuntime(31928): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
E/AndroidRuntime(31928): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
E/AndroidRuntime(31928): 	... 10 more
E/AndroidRuntime(31928): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(31928): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:202)
E/AndroidRuntime(31928): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
E/AndroidRuntime(31928): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
E/AndroidRuntime(31928): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
E/AndroidRuntime(31928): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2421)
E/AndroidRuntime(31928): 	... 21 more

```

Notice: there is no change whatsoever in the project... Is just `flutter create foobar && cd foobar && flutter run`.

**Comment by JCKodel** [comment] 2020-12-30 16:16
Running on stable channel, the new project works. (but the whole point of this project is to use the Flutter web, so no stable channel for me =\ )

BTW, due to Flutter instability (even in stable channel), I don't use Android Emulator.

**Comment by TahaTesser** [comment] 2020-12-31 07:49
Hi @JCKodel 
Thanks for the information, I've seen the same issue here https://github.com/flutter/flutter/issues/69151 (closed by author)
Given ti works for you on stable, I would consider it as regression. Are you seeing this issue on any device if you've? 

Can't reproduce this on an API 21 emulator, due to the Android Studio bug. 
Thank you

**Comment by JCKodel** [comment] 2021-01-01 00:49
@TahaTesser
Samsung J4+ running Android 9 - Works fine
Asus Z00UD (ZenFone 2) running Android 6.0.1 - Works fine

I'm sorry, but I don't have any other Android 5 physical device available.

I had to buy a J4+ because of the Adreno 308 bug in Stable (Skia just rendered everything black and, altough the bug was fixed for months, you guys decided not to cherry pick it to a Stable hotfix).

I had to buy a Azus ZenFone 2 because of the weird Cortex-A53 CPU (it has some issues with Armv8-A architecture) that makes Flutter crash - a lot - in production (this device is so weird that it can overheat and reboot with a simple CSS loading animation (those made with CSS3)).

I had to buy at least 4 iPhones (but those are Apple's fault =P). There are some serious issues with CustomPainter and iPhone 5S with iOS 10 (but, since I only have 3466 users with it, I'm ok with that)

**I urge the test team to have a physical device of each supported OS version (at least major with the least revision) and make a full application that uses câmera, etc. and make the stable version only public when it passes in all those devices. Of course it is not possible to test on every version/CPU/GPU available, but at least the most commons.** 

Firebase lab would be an option (if Firebase team is willingly to support Flutter testing, that would be awsome.

Due to Android (and iOS) fragmentation, Flutter is being a pain in production, specially on 3rd world countries like mine, where most users uses cheap models and have limited internet access (they often don't update the OS because of the download size)).

**Comment by TahaTesser** [comment] 2021-01-04 07:12
Hi @JCKodel 
I also don't have an Android 5 device, so I am gonna label the issue 
Thank you

**Comment by Kleak** [comment] 2021-01-27 16:08
maybe this can be helpful https://github.com/flutter/gallery/issues/383 by commenting 
```xml
<meta-data
android:name="io.flutter.embedding.android.SplashScreenDrawable"
android:resource="@drawable/launch_background" />
```
i can now run the app

**Comment by iamchathu** [comment] 2021-02-27 06:39
I'm also getting this error for Play Store pre-test

Device specifications
Model name
P8 青春版
Manufacturer
Huawei
Android Version (SDK)
Android 5.0 (SDK 21)
Locale
en_US
Screen size
720 x 1280
Screen density (DPI)
320
RAM (total memory)
2,048 MB
OpenGL ES version
2.0
ABI
ARM64_V8
CPU
HiSilicon Hi6220

**Comment by llucax** [comment] 2021-03-11 08:01
I confirm I'm getting this using the latest Flutter stable (2.0.1).

<details><summary>`flutter doctor -v`</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_IE.UTF-8)
    • Flutter version 2.0.1 at /home/luca/software/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/luca/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/luca/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio
    • Android Studio at /home/luca/software/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/luca/software/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • LG H870 (mobile) • LGH8701d9f7a4 • android-arm64  • Android 9 (API 28)
    • Linux (desktop)  • linux         • linux-x64      • Linux
    • Chrome (web)     • chrome        • web-javascript • Chromium 88.0.4324.182 built on Debian bullseye/sid, running on Debian bullseye/sid

• No issues found!
```
</details>

I don't have a device with Android 5 but a pre-launch report in Google Play shows this crash for both API 21 and 18. The device with API 21 is the same as in the comment above, but also this device with Android 4.3 is affected:
 
Samsung Galaxy S3, Android 4.3 (SDK 18)

**Comment by itsarjunsinh** [comment] 2021-04-19 11:29
Fix for existing projects with this issue:

In android\app\src\main\res\**drawable-v21\launch_background.xml** change

`<item android:drawable="?android:colorBackground" />`

to 

```
<item>
    <color android:color="?android:colorBackground" />
</item>
```

This will fix the problem without disabling the splash screen like in some other solutions.

**Comment by JoshuaKyleLambert** [comment] 2021-04-19 23:31
itsarjunsinh's Fix worked for me. Using default project android studio, flutter master branch and api 21 on a samsung note 3.

Before this would crash on avd and the note.

**Comment by JCKodel** [comment] 2021-04-20 23:33
On a real lollipop device (a Moto G 2013), just formatted to factory defaults, automatic update off, with a brand new account (the phone in its purest form).

Flutter 2.0.5.

```
E/AndroidRuntime(16009): FATAL EXCEPTION: main
E/AndroidRuntime(16009): Process: br.art.code.meucronogramacapilar, PID: 16009
E/AndroidRuntime(16009): java.lang.RuntimeException: Unable to start activity ComponentInfo{br.art.code.meucronogramacapilar/br.art.code.meucronogramacapilar.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(16009):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
E/AndroidRuntime(16009):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
E/AndroidRuntime(16009):        at android.app.ActivityThread.access$800(ActivityThread.java:148)
E/AndroidRuntime(16009):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
E/AndroidRuntime(16009):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16009):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(16009):        at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime(16009):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16009):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(16009):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(16009):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime(16009): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(16009):        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2431)
E/AndroidRuntime(16009):        at android.content.res.Resources.loadDrawable(Resources.java:2333)
E/AndroidRuntime(16009):        at android.content.res.Resources.getDrawable(Resources.java:758)
E/AndroidRuntime(16009):        at android.content.res.Resources.getDrawable(Resources.java:724)
E/AndroidRuntime(16009):        at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:493)
E/AndroidRuntime(16009):        at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(16009):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(16009):        at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
E/AndroidRuntime(16009):        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:415)
E/AndroidRuntime(16009):        at android.app.Activity.performCreate(Activity.java:5953)
E/AndroidRuntime(16009):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
E/AndroidRuntime(16009):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
E/AndroidRuntime(16009):        ... 10 more
E/AndroidRuntime(16009): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(16009):        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:202)
E/AndroidRuntime(16009):        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
E/AndroidRuntime(16009):        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
E/AndroidRuntime(16009):        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
E/AndroidRuntime(16009):        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2421)
E/AndroidRuntime(16009):        ... 21 more
W/ActivityManager( 1003):   Force finishing activity br.art.code.meucronogramacapilar/.MainActivity
```

Using the mentioned fix by https://github.com/flutter/flutter/issues/73118#issuecomment-822395456, it now works.

**Closed** 2021-06-24 20:21 UTC
Labels: P4, e: OS Version specific, e: device-specific, engine, passed first triage, platform-android, severe: crash
