### ISSUE TITLE
unable to use the command flutter --version and flutter doctor

### ISSUE THREAD

**Issue by shagufta117** [flutter/flutter#34984] opened 2019-06-24 11:10 UTC
<img width="1107" alt="Screenshot 2019-06-24 at 16 38 02" src="https://user-images.githubusercontent.com/50261212/60014460-bb20d100-969e-11e9-903e-f85b0f06bbec.png">

**Comment by ketanm** [comment] 2019-06-24 15:31
@shagufta117 

This is not Flutter related issue but you are having issues on how tools are installed on your machine. See e.g. - https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue

Ketan

**Comment by stuartmorgan** [comment] 2019-07-18 13:06
Duplicate of #29952.

**Closed by stuartmorgan** 2019-07-18 13:06 UTC
Labels: d: stackoverflow
