### ISSUE TITLE
A problem with the flutter Web font appears as follows:

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90788] opened 2021-09-27 03:53 UTC
A problem with the flutter Web font appears as follows:
![image](https://user-images.githubusercontent.com/91245043/134842889-4a3e8589-ff10-4322-9d01-36904ef8f33a.png)

It will be normal after a while
![image](https://user-images.githubusercontent.com/91245043/134842927-a1d7d3dc-904c-4391-af3a-a9babde78d63.png)

我的程序：
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class BottomSheetDemo extends StatelessWidget {
  const BottomSheetDemo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("BottomSheet Demo"),),
      body: Center(
        child: ElevatedButton(onPressed: (){
          Get.bottomSheet(Container(child: Wrap(children: [
            ListTile(
              leading: Icon(Icons.wb_sunny_outlined),
              title: Text("白天模式"),
              onTap: (){
                Get.changeTheme(ThemeData.light());
              },

            ),
            ListTile(
              leading: Icon(Icons.wb_sunny),
              title: Text("夜间模式"),
              onTap: (){
                Get.changeTheme(ThemeData.dark());
              },
            )
          ],),));
          
        }, child:Text("BottomSheet123")),
      ),
    );
  }
}
`

**Comment by darshankawar** [comment] 2021-09-27 10:35
Duplicate of https://github.com/flutter/flutter/issues/77023

**Closed by darshankawar** 2021-09-27 10:35 UTC
Labels: in triage
