### ISSUE TITLE
Codelabs Wrong instruction 

### ISSUE THREAD

**Issue by Quelmax** [flutter/flutter#77297] opened 2021-03-04 22:09 UTC
### Wrong instruction  at the Building beautiful UIs with Flutter codelab

Following the instructions in the section 5 of the codelab, **Add a UI for composing messages**, it seems to have an incorrect instruction, in the subsection beneath: 

> Wrap the TextField inside a Flexible:
> 
> Select Row.
> Press Option+Return (macOS) or Alt+Enter (Linux and Windows) to bring up a menu, and select Wrap with widget...

When we do that it generates an error, because we wraped the Row into a Flexible, not the TextField, at first the learner following the intructions sees the difference between the code from the codelab tutorial and his IDE code, but no warning is given by the editor, however when we hit the hot reload we receive this error: 

> ======== Exception caught by widgets library =======================================================
> The following assertion was thrown while applying parent data.:
> Incorrect use of ParentDataWidget.

What gives the right result seen at the sample code is: 

> Wrap the TextField inside a Flexible:
> 
> Select **TextField** (Instead of Row).
> Press Option+Return (macOS) or Alt+Enter (Linux and Windows) to bring up a menu, and select Wrap with widget...

**Comment by darshankawar** [comment] 2021-03-05 09:47
Closing this as duplicate of https://github.com/flutter/website/issues/4881

**Closed by darshankawar** 2021-03-05 09:47 UTC
Labels: in triage
