### ISSUE TITLE
GridView behaves abnormal.

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter#29498] opened 2019-03-17 03:15 UTC
GridView is broken after commit 307848953f5d8aad0fee167d8564bac61b294104.

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2, childAspectRatio: 1.5,
          crossAxisSpacing: 1.0, mainAxisSpacing: 1.0),
        itemBuilder: (_, __) {
          return Container(color: Colors.green,);
        },
        itemCount: 200,
      ),
    ),
  ));
}
```

The simple code will reproduct it.
After scroll multiple times up and down, there will be only one green grid shown on the screen.

**Comment by tylorvan** [comment] 2019-07-03 02:55
I found the same issue in our APP two.

**Comment by SupSaiYaJin** [comment] 2019-07-03 03:51
@HansMuller I think it's a bug obviously. When will this be solved?
307848953f5d8aad0fee167d8564bac61b294104，this commit cause this.

**Comment by Fleximex** [comment] 2019-07-03 07:53
I reported the same issue here: https://github.com/flutter/flutter/issues/35458 with video showing the problem. Are you all using Samsung (Exynos) devices as well? I can't reproduce it on other (Snapdragon) physical devices or AVDs.
For now I edited my local Flutter 1.5.4 source code to revert the https://github.com/flutter/flutter/commit/307848953f5d8aad0fee167d8564bac61b294104 change and now it works normal again.

**Comment by HansMuller** [comment] 2019-07-03 15:13
CC @goderbauer

**Comment by goderbauer** [comment] 2019-07-03 17:57
@SupSaiYaJin What device were you seeing the problem on? I was unable to reproduce it on an iPhone 8 and a Pixel 2. 

I'll see if I can find one of the devices that @Fleximex mentioned to reproduce this.

**Comment by goderbauer** [comment] 2019-07-03 19:27
I just tried to reproduce this on a Samsung J7 J710M with Exynos chipset and everything is working as expected. I currently don't have access to any of the devices mentioned in https://github.com/flutter/flutter/issues/35458.

@SupSaiYaJin Please let us know what device you where seeing this on.

**Comment by SupSaiYaJin** [comment] 2019-07-04 13:47
@goderbauer Both Redmi Note 4x and Huawei Honor Magic 2 can reproduce this.

**Comment by SupSaiYaJin** [comment] 2019-07-04 13:48
I think it's device independent.

**Comment by kangwang1988** [comment] 2019-07-04 15:36
@goderbauer 
Try the debug mode instead of release one.
If you can't reproduce it, I can have a double check as I heard someone around me is also experiencing the issue.

**Comment by SupSaiYaJin** [comment] 2019-07-05 02:38
Yes, it happens in debug mode. For release mode, it's working well.

**Comment by goderbauer** [comment] 2019-07-08 16:45
I was running in debug mode on a Samsung J7 J710M with Exynos chipset and had no luck of reproducing this so far.

**Comment by chunhtai** [comment] 2019-07-19 21:31
this sounds familiar to https://github.com/flutter/flutter/issues/16125 which happened to be the bug in dart vm optimizer

**Comment by dnfield** [comment] 2019-07-24 22:23
This does seem like it might be a duplicate - adding waiting for customer response label, please update this if it's still reproducing on master.

**Comment by Fleximex** [comment] 2019-07-25 06:11
I can confirm that on the master branch (v1.8.2-pre.181) I cannot reproduce the issue on, for me, two previously affected devices: Samsung Galaxy Tab A 10.1 (2019) and Samsung Galaxy J5 (2017).

**Comment by chunhtai** [comment] 2019-07-25 20:58
I will close this issue for now, feel free to reopen if this is still an issue.

**Closed by chunhtai** 2019-07-25 20:58 UTC
Labels: framework, severe: regression, waiting for customer response
