### ISSUE TITLE
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �

### ISSUE THREAD

**Issue by TDSYNNEXBPADACH** [flutter/flutter#152164] opened 2024-07-23 13:48 UTC
### Steps to reproduce

Run below one of the Functions provided in Code Sampel Section.

Background Information:
We encountered this issue while reading data from an Excel File, but could narrow it down to happening whenever trying to put a non UTF-8 Character into a String variable.

### Expected results

The Debugger should not crash.
Instead either test2 should be printed or .toString() should throw an error.

### Actual results

Debugger crashes.

### Code sample

<details open><summary>Code sample</summary>

```dart
void makeAction() {
    dynamic test = "�";
    String test2 = test.toString();
    print(test2);
  }
  
void makeAction() {
    String test = "�";
    print(test);
  }
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: �
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[239, 191, 189, 10]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3737], locale en-DE)
    • Flutter version 3.19.4 on channel stable at C:\Tools\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (4 months ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\JBARTHE2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.183
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.113

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-24 07:08
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137025

**Closed by danagbemava-nc** 2024-07-24 07:08 UTC
Labels: in triage
