### ISSUE TITLE
[tool_crash] ProcessException: Process timed out: Command: /usr/bin/env, OS error code: -1

### ISSUE THREAD

**Issue by kendall-lu** [flutter/flutter#68311] opened 2020-10-16 15:39 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1) flutter build ios or flutter run (ios)

## Logs
ProcessException: Process timed out:
ProcessException: ProcessException: Process timed out:

## exception
ProcessException: ProcessException: Process timed out:
  Command: /usr/bin/env xcrun xcodebuild -configuration Release -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/kendalllu/Desktop/flutter_mobile/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/sq/4x9643n92cs_0ptv9vchflp80000gn/T/flutter_tools.MFBARK/flutter_build_log_pipe.oPTgGY/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:399:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:362:66)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11     _runBuildWithRetries (package:flutter_tools/src/ios/mac.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/kendalllu/flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/kendalllu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.42.1)
    • VS Code at /Users/kendalllu/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Pixel 3a (mobile) • 014AY1RR9E • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
file_picker-1.13.3
flutter_plugin_android_lifecycle-1.0.11
flutter_secure_storage-3.3.5
flutter_sodium-0.0.11
flutter_webview_plugin-0.3.11
fluttercontactpicker-2.4.3
image_picker-0.6.7+12
keyboard_visibility-0.5.6
libphonenumber-1.0.1
local_auth-0.6.3+3
open_file-3.0.1
path_provider-1.6.21
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
permission_handler-5.0.1+1
shared_preferences-0.5.12+2
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
uni_links-0.4.0
url_launcher-5.7.4
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1
vibration-1.7.1
vibration_web-1.6.2

edit: I ran these commands in a new project (flutter create ...) and commands work fine. flutter run on an android device does work but takes about 5 minutes on `Running Gradle task 'assembleDebug'`.

fix: `Issue fixed by git clone repo`. Leaving this here for others who face a similar issue

**Comment by hamdikahloun** [comment] 2020-10-16 16:30
Hi @kendall-lu 

Duplicated issue https://github.com/flutter/flutter/issues/47633

Thank you

**Comment by darshankawar** [comment] 2020-10-19 07:17
Closing this as duplicate of [47633](https://github.com/flutter/flutter/issues/47633)

**Closed by darshankawar** 2020-10-19 07:17 UTC
