### ISSUE TITLE
Camera plugin crashes in example app after permissions dialog

### ISSUE THREAD

**Issue by edwardhuerta** [flutter/flutter#26228] opened 2019-01-08 11:32 UTC
## Steps to Reproduce
1. clone the plugin (commit aa7ea2b5e232cadecbc65dca150a52eea2ede2d7)
2. run the example Android app
3. when the app launches, click on the Left-most camera
4. Deny both permissions
5. click on the the right-most camera
6. Accept the permissions
Result : The app crashes with 

```
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 0
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 1
D/SensorManager( 9835): registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,  
D/SensorManager( 9835): unregisterListener ::   
V/ActivityThread( 9835): updateVisibility : ActivityRecord{61e26d9 token=android.os.BinderProxy@2f5931c {io.flutter.plugins.cameraexample/io.flutter.plugins.cameraexample.MainActivity}} show : true
I/flutter ( 9835): Error: cameraPermission
I/flutter ( 9835): Error Message: MediaRecorderCamera permission not granted
I/Timeline( 9835): Timeline: Activity_idle id: android.os.BinderProxy@2f5931c time:4578849
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 0
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 1
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 0
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 1
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 0
D/ViewRootImpl( 9835): ViewPostImeInputStage processPointer 1
D/SensorManager( 9835): registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,  
D/SensorManager( 9835): unregisterListener ::   
V/ActivityThread( 9835): updateVisibility : ActivityRecord{61e26d9 token=android.os.BinderProxy@2f5931c {io.flutter.plugins.cameraexample/io.flutter.plugins.cameraexample.MainActivity}} show : true
I/CameraManager( 9835): Using legacy camera HAL.
D/SensorManager( 9835): registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,  
I/CameraManager( 9835): Using legacy camera HAL.
E/Camera  ( 9835): Error 2
I/RequestThread-1( 9835): Flushing all pending requests.
E/RequestQueue( 9835): cancel failed: no repeating request exists.
I/CameraDeviceState( 9835): Legacy camera service transitioning to state ERROR
I/CameraDeviceState( 9835): Legacy camera service transitioning to state CONFIGURING
E/CameraDeviceState( 9835): Cannot call configure while in state: 0
E/CameraCaptureSession( 9835): Session 0: Failed to create capture session; configuration failed
D/AndroidRuntime( 9835): Shutting down VM
E/AndroidRuntime( 9835): FATAL EXCEPTION: main
E/AndroidRuntime( 9835): Process: io.flutter.plugins.cameraexample, PID: 9835
E/AndroidRuntime( 9835): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9835): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:183)
E/AndroidRuntime( 9835): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:203)
E/AndroidRuntime( 9835): 	at io.flutter.plugins.camera.CameraPlugin$Camera$3.onOpened(CameraPlugin.java:508)
E/AndroidRuntime( 9835): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
E/AndroidRuntime( 9835): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 9835): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9835): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime( 9835): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
E/AndroidRuntime( 9835): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9835): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime( 9835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
I/flutter ( 9835): Error: CameraAccess
I/flutter ( 9835): Error Message: Illegal state encountered in camera service.
```

## Logs

```
Analyzing example...                                             
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel master, v1.1.3-pre.25, on Mac OS X 10.13.6 17G65, locale en-NL)
    • Flutter version 1.1.3-pre.25 at /Users/edward/Documents/Development/flutter
    • Framework revision 32d65fef1c (3 weeks ago), 2018-12-18 10:05:12 +0100
    • Engine revision 5af435098d
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/edward/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.
```

**Comment by zoechi** [comment] 2019-01-08 12:06
Can you provide a project as minimal reproduction?

**Comment by edwardhuerta** [comment] 2019-01-08 13:09
Hi @zoechi ,

The project I used is the example project that comes already with the plugin, so nothing special from my side that could alter the problem. I also provided which commit from the plugin is the one I ran.

**Comment by edwardhuerta** [comment] 2019-01-08 15:13
I investigated a bit more,

After the user accepts both permissions, (step 6 in my reproducible steps), the camera is initialised for the **first time**. This is expected and correct.

However, the code continues and the problem arises because in the CameraPlugin.java class:  the `onActivityResumed` of the `activityLifecycleCallbacks` variable, calls `camera.open(null)`at CameraPlugin.java:108 . This essentially is the **second time** the camera is opened, but it shouldn't, and this causes the problem.

The exception that is eventually thrown is  `android.hardware.camera2.CameraAccessException` with message `Illegal state encountered in camera service.` This is the exception being caught in CameraPlugin.java:508 .

We only found that exception by putting breakpoints in the native android code, because the native exception is being masked by the flutter platform channel exception : `java.lang.IllegalStateException: Reply already submitted`

**Comment by meJevin** [comment] 2019-08-21 12:58
Any progress on this one?

**Comment by timsneath** [comment] 2020-01-03 01:51
Assigned to @mklim on the assumption that this is the parent bug.

**Comment by mklim** [comment] 2020-01-07 20:58
Thanks for the detailed analysis @edwardhuerta, that makes this much easier to fix! It looks like the root issue is that when [we add a listener to the PermissionsRegistry in `CameraPermissions.java`](https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java#L33-L38) and send a reply within the callback, it never gets unregistered and the callback gets triggered for every single permission change, not just the first one. So we send a reply to Dart for the initial camera to say that the permission is denied, but then we send a second (broken) reply saying that the permission has been added for the original camera. Ideally there would be some way to unregister listeners here, but either way it should be straightforward to fix.

**Closed** 2020-01-10 19:20 UTC
Labels: a: quality, p: camera, p: first party, plugin, severe: crash, ▣ platform-android

**Comment by slayerjain** [comment] 2020-04-06 07:11
I'm still facing this issue on `^0.5.7+4`

**Comment by andrejvnior** [comment] 2020-04-14 20:02
Me too... App keeps crashing because of the plugin in Android. On iOS I could even install because it doesn't run.

**Comment by mklim** [comment] 2020-04-15 03:40
@slayerjain and @andrejvnior thanks for the report, would you be able to open new issues and filling out the template with more detailed information? It's likely that what you're seeing is slightly different than the problem diagnosed earlier in this bug, and it'll be easier to track this crash without the history confusing it. Feel free to cc me on it once you open them. Thanks!

**Comment by mugikhan** [comment] 2020-04-28 12:53
Camera plugin still crashing with the same error as seen above. Unable to release an app because of this.

**Comment by kw2019ltd** [comment] 2020-05-11 14:43
getting the same issue
Non-fatal Exception: java.lang.Exception: CameraException(CameraAccess, Illegal state encountered in camera service.)
       at CameraController.startImageStream(camera.dart:405)

![image](https://user-images.githubusercontent.com/47334522/81574766-e5f73f00-93ae-11ea-83c8-fa98eef55964.png)

**Comment by alfawzaan** [comment] 2020-07-28 11:45
I am also experiencing this too.

I am using camera: 0.5.6. I have tried all other higher versions but I continuing getting the same error.

Here is the code. If I comment out the controller initialization lines, My app doesn't crash.

void initializeCamera() async {
    // can be called before `runApp()`
    try {
      _camController = CameraController(
        // Get a specific camera from the list of available cameras.
        firstCamera,
        // Define the resolution to use.
        ResolutionPreset.medium,
      );

      // Next, initialize the controller. This returns a Future.
      await _camController.initialize().then((_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      }); 

    } catch (e, str) {
      print(e.toString());
      print(str.toString());
    }
  }

**Comment by kw2019ltd** [comment] 2020-10-14 12:42
got the same issue on flutter 1.22   , camera plugin 0.5.8+8

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
       at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:159)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:145)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


![Uploading image.png…]()

**Comment by Syforce** [comment] 2021-02-03 07:29
+1

**Comment by LeGoffMael** [comment] 2021-03-24 01:17
I am facing the exact same issue in camera: 0.7.0+2 and flutter 1.22.6
