### ISSUE TITLE
ci.yaml check on engine -> framework roll stuck in a pending state

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116902] opened 2022-12-12 17:51 UTC
https://github.com/flutter/flutter/pull/116898

**Comment by nehalvpatel** [comment] 2022-12-12 17:54
Taking a look.

**Comment by nehalvpatel** [comment] 2022-12-12 17:55
Can you try pushing an empty commit?

**Comment by nehalvpatel** [comment] 2022-12-12 17:58
Nvrm, looks like the commit queue failed. https://github.com/flutter/flutter/pull/116898#issuecomment-1346959474

**Comment by zanderso** [comment] 2022-12-12 18:03
Right, the PR was closed because of the pending/failing ci.yaml check. I assume the fact that that check was stuck in a pending state should be investigated.

**Comment by nehalvpatel** [comment] 2022-12-12 18:04
Ah yea, that is being tracked here: https://github.com/flutter/flutter/issues/100081

**Comment by zanderso** [comment] 2022-12-12 18:12
I'm not sure that's the same issue since the problem that this issue is about is for the first run of the check that was triggered when the PR was opened.

**Comment by nehalvpatel** [comment] 2022-12-12 18:14
Oh, I see. I will bring this up in our handoff meeting today.

**Comment by nehalvpatel** [comment] 2022-12-12 19:21
Might be related: https://github.com/flutter/flutter/issues/102402

**Comment by godofredoc** [comment] 2022-12-15 23:13
@nehalvpatel did you find something that could be causing this?

**Comment by godofredoc** [comment] 2023-01-10 23:49
This was most likely caused by github not sending the correct event to the backend as there are no checks created by cocoon. The message about removing the label because ci.yaml was not found is a configuration in github that prevents landing PRs without running tests.

To try to find a root cause we'll need to wait for it to happen again.

**Comment by godofredoc** [comment] 2023-01-10 23:49
Moving to P3 while we wait for this issue to happen again.

**Comment by keyonghan** [comment] 2024-03-21 19:05
Obsolete. Please reopen if you see this happens again.

**Closed by keyonghan** 2024-03-21 19:05 UTC
Labels: team-infra, P3
