### ISSUE TITLE
Screen flickering on Android since Flutter 3.0.0

### ISSUE THREAD

**Issue by 7mada123** [flutter/flutter#111085] opened 2022-09-07 12:10 UTC
I'm having this issue in every android app built with `flutter 3.0.0` and above, this issue is similar to #100522

flutter 3.3.0 :

https://user-images.githubusercontent.com/67849255/188844700-fcb0f2b0-289e-42c5-93f9-92020b8ba40d.mp4

flutter 2.10.5  works fine:

https://user-images.githubusercontent.com/67849255/188843005-073cbf77-cdd2-439d-9ef5-5accb63fd360.mp4

Even on other apps built with `flutter 3.0.0` and above

Google Analytics app, it was working fine however after updating :

https://user-images.githubusercontent.com/67849255/188845289-e6540d2d-c933-421a-94eb-8591f63a159b.mp4

It's been a while but I thought at the time that the problem was only with the app.

And the new gskinner - Wonderous app :

https://user-images.githubusercontent.com/67849255/188846272-a5471882-4586-44de-85ab-db9cd0acd71f.mp4

### note : 
The videos recorded above are from a physical device (samsung galaxy note 3 LTE) and the emulator seems to be less glitchy but this issue only appears on flutter apps (3.0.0 and above).

emulator : 

[untitled2.webm](https://user-images.githubusercontent.com/67849255/188856634-0c77e6a7-5d66-42f2-a897-54c8286781a0.webm)

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by danagbemava-nc** [comment] 2022-09-07 12:44
Hi @7mada123, how often does this issue reproduce for you?

I have downloaded the `Wonderous` and `Google Analytics` apps, but I cannot seem to reproduce the issue. 

Is there any condition that triggers it, or is it random?

**Comment by 7mada123** [comment] 2022-09-07 13:15
Hi @danagbemava-nc
This issue seems to only occurs on some devices, for me it occurs on samsung galaxy note 3 LTE.
I have tried to on reproduce it samsung galaxy s10 plus but every thing was working fine.

**Comment by danagbemava-nc** [comment] 2022-09-07 13:48
Thanks for the info. 

One final thing, can you share some details about the hardware of software of the galaxy note 3?

**Comment by 7mada123** [comment] 2022-09-07 14:15
The device use Qualcomm Snapdragon 800.
As for the software I use LineageOS 16.0 which isn't the official software.

**Comment by danagbemava-nc** [comment] 2022-09-08 06:46
Hi @7mada123, I believe this is a duplicate of https://github.com/flutter/flutter/issues/111085.

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-09-08 06:46 UTC
Labels: in triage
