### ISSUE TITLE
corrupted git state: flutter --version crashes VersionCheckError: Command exited with code 128

### ISSUE THREAD

**Issue by cenxingcan** [flutter/flutter#34142] opened 2019-06-10 02:16 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter 

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
fatal: bad object HEAD

```
#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:288:62)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:41)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:111:11)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#24     run (package:flutter_tools/runner.dart:51:10)
#25     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#26     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
error: non-monotonic index .git/objects/pack/pack-4f8f216597825dadce2245e0f638f9d507a2e1fe.idx
fatal: bad object HEAD


#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:94:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:463:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:129:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#27     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by stuartmorgan** [comment] 2019-06-19 04:08
Likely a corrupt/incomplete download. The combination of exit code 128 and `bad object HEAD` seems like a good candidate for catching with special-case error handling and providing a 'please try downloading again' friendly message with a toolExit instead of crashing.

**Comment by jmagman** [comment] 2019-11-14 02:31
The doctor crash is fixed with https://github.com/flutter/flutter/pull/44868.

**Comment by jonahwilliams** [comment] 2020-02-17 02:14
Duplicate of https://github.com/flutter/flutter/issues/50902

If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue https://github.com/flutter/flutter/issues/50902

**Closed by jonahwilliams** 2020-02-17 02:14 UTC
Labels: easy fix, severe: crash, t: flutter doctor, tool
