### ISSUE TITLE
want to avoid Keyboard cover in TextFormField like Native android and IOS

### ISSUE THREAD

**Issue by piseysen** [flutter/flutter#19163] opened 2018-07-09 11:47 UTC
I'm first developing mobile on flutter, So I have problem with keyboard. when I type on TextFormField, the keyboard alway cover. So I want ask how to avoid Keyboard cover.

**Comment by zoechi** [comment] 2018-07-09 11:59
That should be fixed since a while in `dev` channel and in `beta` when the next beta is released.
Use `flutter channel dev` to switch to the `dev` channel.

If this doesn't fix your issue please add a comment to get it reopened 
and also please provide more information like the output of `flutter doctor -v` and perhaps a screenshot and the code that allows to reproduce.

**Closed by zoechi** 2018-07-09 11:59 UTC
