### ISSUE TITLE
Flutter web not working on iOS web having OS version less than 14.1

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#104646] opened 2022-05-25 19:05 UTC
When testing the Flutter web app on iOS safari with OS 13.4 and 13.7, it is not working.
We tested it on OS 15.2 and 15.4, it is working fine.

Sample: https://github.com/deepak786/ios_web_issue
web build: https://deepak786.github.io/ios_web_issue_build

It also works fine on the Desktop browsers and Android web browsers.

I inspected the console using the Safari web inspector, it showed the following error:

```
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (flutter.js:23)
[Error] ReferenceError: Can't find variable: _flutter
	(anonymous function) (ios_web_issue_build:80)
```

The same issue happens with [Flutter Gallery website](https://gallery.flutter.dev/#/).

When I searched about the above error, it seems that flutter.js is declaring the variables in a way that is not supported by iOS 13.
This feature is added in iOS 14.1.
Ref: https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

Video showing the error:
https://drive.google.com/file/d/1nFupkQ2ZqHZnXDaBRuP9CO8GMXdkVCPb/view?usp=sharing

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
    • Flutter version 3.0.0 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Deepak’s iPhone (mobile) • 00008101-00117D690A80801E            • ios
      • iOS 15.4.1 19E258
    • iPhone 11 Pro (mobile)   • 56817DBD-D6E9-4308-84F2-65A261C2095C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)          • macos                                •
      darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)             • chrome                               •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-05-26 12:00
Hi @deepak786, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel.  Flutter web app does not load on ios 13.

### Flutter gallery

<img width="654" alt="image" src="https://user-images.githubusercontent.com/31410839/170482558-9fb6a8bc-1a82-43fb-ac48-fddc8be51165.png">

### flutter counter app (master)
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/31410839/170483528-2e6c03e1-a848-40b7-b8ce-d65dc2ef3440.png">

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.854, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.854 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (35 hours ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by deepak786** [comment] 2022-05-26 12:05
I also tested that it works on 14.1 but not before that.

**Comment by tvolkert** [comment] 2022-05-26 17:33
@yjbanov

**Comment by ditman** [comment] 2022-05-26 18:15
Users affected by this can sidestep the issue by using the old `index.html` syntax (by injecting the `main.dart.js` file directly, instead of using `flutter.js`).

I'm working on a fix right now. We need to use the `constructor` function instead of using `public field declarations`, as pointed out by @deepak786!

Thanks for the report!

**Comment by ditman** [comment] 2022-05-26 19:17
I'm currently testing a fix for this in the iOS simulator, as suggested by @maheshmnj.

**Closed** 2022-05-27 00:50 UTC
Labels: platform-ios, framework, platform-web, e: OS Version specific, has reproducible steps, P2, browser: safari-ios, found in release: 3.0, found in release: 3.1

**Comment by ditman** [comment] 2022-05-27 01:55
So the fix for this has landed. There are some workarounds that you can do, @deepak786:

* Switch flutter to `master`, and do a `flutter clean` and `flutter build web` again. The `flutter.js` file will use the new syntax (look for `constructor()` inside of `FlutterLoader`)
* If you want to stay in your current channel, you can. Just create a new, separate, flutter web app, and do a `flutter build web` there.
  * Inside `build/web` you'll find the new `flutter.js` that you can use in your current app. (This is more cumbersome, because every time you do a `flutter clean` you'll have to restore the `flutter.js` file coming from `master` to your old app)
 
Apologies for the breakage, and thanks for reporting!

**Comment by deepak786** [comment] 2022-05-27 07:02
@ditman Thank you for the update.

Switching to master would be a solution for now but this could break other functionalities in the app.

Any estimate about when this will land in a stable channel.

**Comment by maheshmnj** [comment] 2022-05-27 07:09
@deepak786 Fixes on the master take approximately 4 months to stabilize and land on stable you can read more about the release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
