### ISSUE TITLE
Flutter not rendering text after sitting idle (iOS)

### ISSUE THREAD

**Issue by aaronscherbing** [flutter/flutter#57676] opened 2020-05-20 14:09 UTC
We are experiencing an issue in the 1.17.1 stable release.  Our application appears to render all views correctly when the application is initially run.  However, we discovered in our TestFlight builds that once the application has been sitting idle in the background for a while, text rendering becomes very broken.  

I assume this is somehow related to the Metal transition. I was able to downgrade to 1.15.4, and we didn't experience the issue there.

This is a **major** issue that will prevent us from releasing using the newest version of Flutter.

## Details

We've seen this on at least iPhone X and 11 iOS 13.4.1 physical devices. 
We've never seen the issue in a simulator.

I wish I could give you an exact path to recreating this, but it's one of those issues that takes time to reveal itself.  So frustrating, I know...

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /usr/local/flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aaronscherbing/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Aaron’s iPhone 11 • 00008030-00040C241AFA802E            • ios • iOS 13.4.1
    • iPhone X (iOS 12) • 1F4591EB-ADF4-479D-9D58-C83861AE09D8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by aaronscherbing** [comment] 2020-05-20 14:10
Also, I _really wish_ I had a flag to disable the Metal functionality, but it seems like that flag has been removed in the latest releases.

**Comment by aaronscherbing** [comment] 2020-05-21 13:06
![Image from iOS (3)](https://user-images.githubusercontent.com/11944082/82561995-fee3bb00-9b39-11ea-915d-3b8b7156077c.png)

**Comment by TahaTesser** [comment] 2020-05-25 14:07
Hi @aaronscherbing 
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by aaronscherbing** [comment] 2020-05-26 13:58
Here's the output of `flutter run --verbose`:
[verbose-log.txt](https://github.com/flutter/flutter/files/4682700/verbose-log.txt)

I'll work on putting something simpler together as a sample project.

**Comment by aaronscherbing** [comment] 2020-05-29 17:09
Thank the Lord, I'm not the only one running into it!  Unfortunately, I haven't been able to re-create the issue in a simplified application yet.

**Comment by brianb-sf** [comment] 2020-06-01 20:41
>We're experiencing the same issue (bad rendering after idle for a long time) coinciding with the 1.17 release. For us, it doesn't seem to be just text but image assets too. It always gets fixed by restarting the app.

We are also seeing this as well. We cannot reproduce this for the life of us but like others have said it seems to only happen when the application has been running in the background for a while and restarting the app always fixes the issue.

We have seen text fail to render, certain shapes, but the application still responds to touch if you tap where the buttons should be rendered.

We use the following dependencies that I guess you could say are "rendering" related. Curious if @aaronscherbing or @madmeemo are using them as well. Might be a common link here?

`cached_network_image: ^2.0.0-rc.1`
`flutter_svg: ^0.17.4`
`flare_flutter: ^1.7.3`

We also do not see any uncaught exceptions logged to our Crashlytics reporting that would indicate what the issue is. I have reproduced this on an iPhone Xs Max, iOS 13.4.1.

**Flutter Doctor Output**
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at
      /Users/brianblanchard/workspaces/sf/mgm-mobile-indigo/vendor/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/brianblanchard/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /Users/brianblanchard/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/brianblanchard/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 • 8DA7156C-D357-46AD-86B7-47FABC28B132 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
```

**Comment by madmeemo** [comment] 2020-06-01 20:52
@brianb-sf We have the following deps:

```
cached_network_image: ^2.0.0-rc.1
flare_flutter: ^1.8.2
```

and we don't have a dependency on `flutter_svg`.

**Comment by madmeemo** [comment] 2020-06-08 23:02
Are there any updates from the flutter team (@TahaTesser)? It is quite reproducible when resuming an application after sitting idle on the background for a while. We were forced to downgrade the flutter version unfortunately.

**Comment by madmeemo** [comment] 2020-06-11 20:46
FWIW, this is the output of `flutter doctor` from our continuous build machine for our iOS builds:

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.3 at /Users/yourbase/.yourbase/workspaces/0a736cbef854/build/flutter/flutter-1.17.3/flutter
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[!] Android toolchain - develop for Android devices
    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual, while gradle downloads the missing components. This functionality will only work if the licenses in the licenses folder in ANDROID_HOME are valid.
      If the Android SDK has been installed to another location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
      Certain features, such as `flutter emulators` and `flutter devices`, will not work without the currently missing SDK components.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 3 categories.
```

**Comment by chunhtai** [comment] 2020-06-12 17:12
cc @chinmaygarde

**Comment by ened** [comment] 2020-06-12 20:22
@aaronscherbing have you looked at the workaround in https://github.com/flutter/flutter/issues/55969?

**Comment by aaronscherbing** [comment] 2020-06-12 20:39
> @aaronscherbing have you looked at the workaround in #55969?

Thanks for the suggestion!  I haven't tried that yet.  It looks like you are replacing the whole tree with a different widget when the app goes into the background.  Wouldn't that result in all the app state disappearing when the app goes into the background?  ie. The user would be taken back to the initial view whenever they background the app.

I think our application's navigation is too complex to use a technique like that.

**Comment by chinmaygarde** [comment] 2020-06-13 03:17
This issue is likely related to https://github.com/flutter/flutter/issues/55969

**Comment by ened** [comment] 2020-06-13 07:44
@aaronscherbing that is an issue and we've been integrating https://pub.dev/packages/native_state to workaround this. For most of the UI, being able to restore the route is already a big win.

Similar problems rgd. state restoration may appear on Android with the "Don't keep activities" developer option turned on, e.g. when the app is terminated while not on screen. Can also happen if a user wants to take a photo mid-way.

**Comment by hermitdave** [comment] 2020-06-20 15:41
I've noticed this issue with logo from assets folder. However user sent screenshots shows images from online source and texts not rendering
![file](https://user-images.githubusercontent.com/1896163/85205691-d0155c00-b314-11ea-82b7-aa36e16680a5.jpg)

This is how it should look
![Screenshot_20200620-150639](https://user-images.githubusercontent.com/1896163/85205704-e3282c00-b314-11ea-87cc-acca2baef668.jpg)

**Comment by Henrik-glt** [comment] 2020-06-24 05:48
I experienced the same problem when the app was launched in background because of event from Apple Watch (the app I'm working on has a WKExtension).
Caused a lot of headache when we released many of our users experienced this problem.

A "workaround" for us was to keep track of if the app has been active/in foreground.
When receiving a message from Apple Watch and the app has not been in foreground, we handle the message and then just exit the app to make sure that the app will render correctly when opened.
Far from optimal, but it seems to be working :)

**Comment by duongtruong12** [comment] 2020-06-24 10:09
I facing the same issue at #59754

**Comment by chinmaygarde** [comment] 2020-06-30 20:28
The current update on the investigation is at https://github.com/flutter/flutter/issues/55969#issuecomment-652023404.

**Comment by chinmaygarde** [comment] 2020-07-08 00:14
The fix has landed in https://github.com/flutter/engine/pull/19592

**Closed** 2020-07-08 00:14 UTC
Labels: P1, a: typography, customer: crowd, customer: product, engine, framework, platform-ios, severe: rendering

**Comment by TahaTesser** [comment] 2020-08-24 14:54
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by aaronscherbing** [comment] 2020-08-24 15:01
Sounds good.  I'll try to do that within the next few days, and I'll reference the new issue here.

**Comment by AhmedKhattab95** [comment] 2020-08-31 12:19
@madmeemo which version works for you

**Comment by AhmedKhattab95** [comment] 2020-08-31 12:22
> I experienced the same problem when the app was launched in background because of event from Apple Watch (the app I'm working on has a WKExtension).
> Caused a lot of headache when we released many of our users experienced this problem.
> 
> A "workaround" for us was to keep track of if the app has been active/in foreground.
> When receiving a message from Apple Watch and the app has not been in foreground, we handle the message and then just exit the app to make sure that the app will render correctly when opened.
> Far from optimal, but it seems to be working :)

could you provide the code for this workaround

**Comment by deepss1** [comment] 2020-09-27 02:08
It works when in debug, fails to render text when in release mode.

My users are experiencing this issue in Vivo mobile phones.

The beta channel seems to work fine though.

I will get back with more information.

**Comment by TahaTesser** [comment] 2020-09-28 13:46
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by glonaldo70** [comment] 2020-11-13 06:44
> It works when in debug, fails to render text when in release mode.
> 
> My users are experiencing this issue in Vivo mobile phones.
> 
> The beta channel seems to work fine though.
> 
> I will get back with more information.

I'm experiencing this issue some Times, my app in some cases dont render text on launch... please help me !![image](https://user-images.githubusercontent.com/47249521/99037042-34b2ab00-2583-11eb-9780-e7f66098fae0.jpeg)![image](https://user-images.githubusercontent.com/47249521/99037079-4f851f80-2583-11eb-9faf-bfb1008e63b7.jpeg),normaly it display like it ![image](https://user-images.githubusercontent.com/47249521/99037449-fd90c980-2583-11eb-8678-69df6ef404fd.png)
