### ISSUE TITLE
Firebase authentication not working in web

### ISSUE THREAD

**Issue by shivam-modi** [flutter/flutter#77772] opened 2021-03-10 06:17 UTC
# Steps to Reproduce
>> flutter upgrade
>> flutter run -d chrome

I have recently upgraded flutter, after upgrading firebase auth & google_sign_in stopped working on web version. It is working completely fine on android.
Before upgrading, authentication is working fine in both web (on beta channel) and android( stable channel)

**Login function snipet**
`  await auth.FirebaseAuth.instance
            .signInWithEmailAndPassword(email: email.trim(), password: password)
            .then((value) {
          setState(() {
            _user = value;
          });
        });`

**Create account function snipet**
` await auth.FirebaseAuth.instance
            .createUserWithEmailAndPassword(
                email: email.trim(), password: password)
            .then((value) {
          setState(() {
            _user = value;
          });
        });`

**Google Sign In snippet**
`Future<auth.FirebaseUser> _handleSignIn(
      GoogleSignInAccount googleuser) async {
    auth.FirebaseUser _user;

    setState(() {
      showSpiner = true;
    });
    final GoogleSignInAuthentication googleAuth =
        await googleuser.authentication;
    await auth.FirebaseAuth.instance
        .signInWithGoogle(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    )
        .then((value) {
      _user = value;
    });
    return _user;
  }`

After login/ sign up there should be a successful redirection to the home page
but error occurs 
**MissingPluginException(No implementation found for method signInWithEmailAndPassword on channel plugins.flutter.io/firebase_auth)**
**MissingPluginException(No implementation found for method createUserWithEmailAndPassword on channel plugins.flutter.io/firebase_auth)**
Google sign in error
[https://imgur.com/9wQYkgk.png](url)

<details>
  <summary>Logs</summary>

After running
flutter run --verbose
```[ +145 ms] executing: [/home/shivam/development/appDev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] executing: [/home/shivam/development/appDev/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +20 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +74 ms] executing: [/home/shivam/development/appDev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/shivam/development/appDev/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] executing: [/home/shivam/development/appDev/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +112 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +91 ms] executing: /home/shivam/Android/Sdk/platform-tools/adb devices -l
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +137 ms] executing: /home/shivam/Android/Sdk/platform-tools/adb devices -l
[  +22 ms] Skipping pub get: version match.
[  +75 ms] Found plugin clipboard_manager at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/clipboard_manager-0.0.4/
[  +11 ms] Found plugin cloud_firestore at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[   +9 ms] Found plugin cloud_firestore_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[  +16 ms] Found plugin emoji_picker at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/emoji_picker-0.1.0/
[  +17 ms] Found plugin firebase_auth at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.2+1/
[   +4 ms] Found plugin firebase_core at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[   +6 ms] Found plugin firebase_core_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[   +3 ms] Found plugin firebase_dynamic_links at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.6.3/
[   +3 ms] Found plugin firebase_messaging at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/
[   +3 ms] Found plugin firebase_storage at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-5.2.0/
[   +5 ms] Found plugin firebase_storage_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage_web-0.1.1+1/
[   +8 ms] Found plugin flutter_chat_bubble at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chat_bubble-1.0.2/
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +9 ms] Found plugin geolocator at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.2.1/
[   +4 ms] Found plugin geolocator_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_web-1.0.1/
[   +5 ms] Found plugin google_sign_in at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[   +4 ms] Found plugin google_sign_in_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[   +7 ms] Found plugin image_cropper at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.0/
[   +4 ms] Found plugin image_picker at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+22/
[  +33 ms] Found plugin path_provider at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +1 ms] Found plugin path_provider_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +2 ms] Found plugin path_provider_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[  +17 ms] Found plugin rate_my_app at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.7.2/
[   +6 ms] Found plugin share at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.0/
[   +1 ms] Found plugin shared_preferences at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[   +1 ms] Found plugin shared_preferences_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[   +1 ms] Found plugin shared_preferences_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[   +4 ms] Found plugin shared_preferences_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[   +1 ms] Found plugin shared_preferences_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[   +6 ms] Found plugin sqflite at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+2/
[  +12 ms] Found plugin url_launcher at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +1 ms] Found plugin url_launcher_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +2 ms] Found plugin url_launcher_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +2 ms] Found plugin url_launcher_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +1 ms] Found plugin url_launcher_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[ +191 ms] Found plugin clipboard_manager at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/clipboard_manager-0.0.4/
[   +2 ms] Found plugin cloud_firestore at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[   +2 ms] Found plugin cloud_firestore_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[   +6 ms] Found plugin emoji_picker at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/emoji_picker-0.1.0/
[   +8 ms] Found plugin firebase_auth at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.2+1/
[   +2 ms] Found plugin firebase_core at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[   +3 ms] Found plugin firebase_core_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[   +2 ms] Found plugin firebase_dynamic_links at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.6.3/
[   +1 ms] Found plugin firebase_messaging at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/
[   +3 ms] Found plugin firebase_storage at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-5.2.0/
[   +3 ms] Found plugin firebase_storage_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage_web-0.1.1+1/
[   +6 ms] Found plugin flutter_chat_bubble at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chat_bubble-1.0.2/
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +4 ms] Found plugin geolocator at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-6.2.1/
[   +2 ms] Found plugin geolocator_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_web-1.0.1/
[   +2 ms] Found plugin google_sign_in at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[   +2 ms] Found plugin google_sign_in_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[   +3 ms] Found plugin image_cropper at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.0/
[   +1 ms] Found plugin image_picker at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+22/
[  +20 ms] Found plugin path_provider at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +1 ms] Found plugin path_provider_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +1 ms] Found plugin path_provider_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[   +8 ms] Found plugin rate_my_app at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.7.2/
[   +8 ms] Found plugin share at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/share-2.0.0/
[   +1 ms] Found plugin shared_preferences at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[   +1 ms] Found plugin shared_preferences_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[   +1 ms] Found plugin shared_preferences_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[   +2 ms] Found plugin shared_preferences_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[   +1 ms] Found plugin shared_preferences_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[   +4 ms] Found plugin sqflite at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+2/
[   +8 ms] Found plugin url_launcher at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[   +1 ms] Found plugin url_launcher_linux at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[   +1 ms] Found plugin url_launcher_macos at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +1 ms] Found plugin url_launcher_web at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +1 ms] Found plugin url_launcher_windows at /home/shivam/development/appDev/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +30 ms] Generating /home/shivam/github/temp/Insta-quora-project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +201 ms] List of devices attached
[   +5 ms] List of devices attached
[ +138 ms] Launching lib/main.dart on Chrome in debug mode...
[ +610 ms] "flutter run" took 1,964ms.
[   +9 ms] Failed to bind web development server:
           SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = localhost, port = 2727
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:196:7)
           <asynchronous suspension>
           #2      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:692:22)
           <asynchronous suspension>
           #3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:500:25)
           <asynchronous suspension>
           #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>
           
           
[  +94 ms] ensureAnalyticsSent: 91ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-10 07:38
Hi @shivam-modi 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-10 07:38 UTC
Labels: in triage

**Comment by shivam-modi** [comment] 2021-03-10 07:57
Ok, @pedromassangocode I have created a new issue in FlutterFire with the required logs.
