### ISSUE TITLE
there is no profile button in screenshot.

### ISSUE THREAD

**Issue by CallmeYiombi** [flutter/flutter#157570] opened 2024-10-25 01:44 UTC
https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=ko#4
there is no profile button even context(profile) in Visibility().
I think screenshot needs to be updated.

**Comment by huycozy** [comment] 2024-10-25 08:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/157571.

**Closed by huycozy** 2024-10-25 08:37 UTC
Labels: in triage
