### ISSUE TITLE
Single page PageView isn't swipeable

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#67461] opened 2020-10-06 22:54 UTC
## Steps to Reproduce

I'm trying to implement dynamic PageViews where pages can be added by calling a function. However, if there's only a single page in a PageView, the PageView isn't swipeable. Even after adding a page to the PageView, it's still not swipeable. Behavior is reproducible on both stable and master flutter channels.

1. Run the sample code
2. App creates a single page in PageView
3. Click the PopMenuButton > 'Add Page at End'

**Sample code**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

int pageViewIndex;

class _MyHomePageState extends State<MyHomePage> {
  ActionMenu actionMenu;
  final PageController pageController = PageController();
  int currentPageIndex = 0;

  @override
  void initState() {
    super.initState();
    actionMenu = ActionMenu(this.addPageView, this.removePageView);
    addPageView(listPageView.length + 1);
  }

  addPageView(int page) {
    print('addPageView page $page');
    setState(() {
      listPageView.add(
        Container(
          child: Center(
            child: Text('Page $page'),
          ),
        ),
      );
    });
  }

  removePageView(int index) {
    print('removePageView page ${index + 1} at index $index');
    if (listPageView.length > 1)
      setState(() {
        // if in first page, navigate to next page
        // before removing current(first) page
        if (index == 0)
          navigateToPage(index + 1);
        else
          navigateToPage(index - 1);
        listPageView.removeAt(index);
      });
    else
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Last page"),
      ));
  }

  navigateToPage(int index) {
    pageController.animateToPage(
      index,
      duration: Duration(milliseconds: 300),
      curve: Curves.ease,
    );
  }

  getCurrentPage(int page) {
    pageViewIndex = page;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          actionMenu,
        ],
      ),
      body: Container(
        child: PageView(
          controller: pageController,
          onPageChanged: getCurrentPage,
          children: listPageView,
        ),
      ),
    );
  }
}

enum MenuOptions { addPageAtEnd, deletePageCurrent }
List<Widget> listPageView = List();

class ActionMenu extends StatelessWidget {
  final Function addPageView, removePageView;
  ActionMenu(this.addPageView, this.removePageView);

  @override
  Widget build(BuildContext context) {
    return PopupMenuButton<MenuOptions>(
      onSelected: (MenuOptions value) {
        switch (value) {
          case MenuOptions.addPageAtEnd:
            print('Menu button: add page ${listPageView.length + 1} at end');
            this.addPageView(listPageView.length + 1);
            break;
          case MenuOptions.deletePageCurrent:
            print('Menu button: delete current page + $pageViewIndex');
            this.removePageView(pageViewIndex);
            break;
        }
      },
      itemBuilder: (BuildContext context) => <PopupMenuItem<MenuOptions>>[
        PopupMenuItem<MenuOptions>(
          value: MenuOptions.addPageAtEnd,
          child: const Text('Add Page at End'),
        ),
        const PopupMenuItem<MenuOptions>(
          value: MenuOptions.deletePageCurrent,
          child: Text('Delete Current Page'),
        ),
      ],
    );
  }
}
```

**Expected results:** 
A page should be added in the PageView and should be swipeable.

**Actual results:** 
Checking the logs, a page has been added in `List<Widget> listPageView` for the PageView, but the PageView doesn't seem to be refreshed or swipeable even if setState() was called.

To trigger swipe function in PageView, run the app again using Hot Reload. The app will be refreshed and will determine that the PageView has two pages and is now swipeable.

**Demo**
First launch/restart, click 'Add Page'
![demo first launch](https://user-images.githubusercontent.com/4143153/95267485-f3362e00-0867-11eb-8529-aa66fcf58ef9.gif)

After clicking 'Add Page', a hot reload displays two pages in PageView
![demo after hot reload](https://user-images.githubusercontent.com/4143153/95267597-2f698e80-0868-11eb-8e45-1f0e549d289d.gif)

<details>
  <summary>Logs</summary>

```
```

```
Analyzing samplepageviewdynamic...                                      
No issues found! (ran in 3.2s)
```

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.166, on Mac OS X 10.15.7 19H2 x86_64, locale en-PH)
    • Flutter version 1.23.0-8.0.pre.166 at /Users/{USER}/Downloads/flutter
    • Framework revision aaa99f6d4e (15 hours ago), 2020-10-06 03:47:04 -0400
    • Engine revision 443cd5a1e1
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/{USER}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xs (mobile)           • 82CF4677-9933-4698-AD5C-823D6E93F283 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2020-10-07 09:07
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0
    • Web Server (web)          • web-server                               •
      web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 86.0.4240.75

• No issues found!

```

</details>

**Comment by xu-baolin** [comment] 2020-10-10 05:29
I am currently investigate this issue.

**Comment by xu-baolin** [comment] 2020-10-10 05:51
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          actionMenu,
        ],
      ),
      body: Container(
        child: PageView(
          controller: pageController,
          onPageChanged: getCurrentPage,
          children: List.from(listPageView),
        ),
      ),
    );
  }
```
After I modified the `build()` function, it worked fine.

Here you need to copy a copy of children, otherwise, it will be a reference type, and the changes of the new and old widgets cannot be recognized during rebuild-time.

Is there a need for the framework to automatically copy the copy, or update the document to explain this situation?
@HansMuller @dnfield Hi, Looking forward to your suggestions

**Comment by dnfield** [comment] 2020-10-12 03:59
This is by design. Once you give a list of widgets to the framework, it expects you to never modify that list. Ideally this would be captured in some kind of `ImmutableList` like type, but no such type is available.

**Comment by xu-baolin** [comment] 2020-10-12 05:42
> This is by design. Once you give a list of widgets to the framework, it expects you to never modify that list. Ideally this would be captured in some kind of `ImmutableList` like type, but no such type is available.

Is there any relevant document describing this? It feels easy to make this mistake.

**Comment by omatt** [comment] 2020-10-12 13:11
> This is by design. Once you give a list of widgets to the framework, it expects you to never modify that list. Ideally this would be captured in some kind of `ImmutableList` like type, but no such type is available.

The issue doesn't happen when building PageView using `PageView.build(itemBuilder)`. Modifying `itemCount` can dynamically modify the number of pages. 

Here's a sample repro for `itemBuilder`

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

int pageViewIndex;

class _MyHomePageState extends State<MyHomePage> {
  ActionMenu actionMenu;
  final PageController pageController = PageController();
  int currentPageIndex = 0;
  int pageCount = 1;

  @override
  void initState() {
    super.initState();
    actionMenu = ActionMenu(this.addPageView, this.removePageView);
  }

  addPageView() {
    setState(() {
      pageCount++;
    });
  }

  removePageView(BuildContext context) {
    if (pageCount > 1)
      setState(() {
        pageCount--;
      });
    else
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Last page"),
      ));
  }

  getCurrentPage(int page) {
    pageViewIndex = page;
  }

  createPage(int page) {
    return Container(
      child: Center(
        child: Text('Page $page'),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          actionMenu,
        ],
      ),
      body: Container(
        child: PageView.builder(
          controller: pageController,
          onPageChanged: getCurrentPage,
          itemCount: pageCount,
          itemBuilder: (context, position) {
            return createPage(position + 1);
          },
        ),
      ),
    );
  }
}

enum MenuOptions { addPageAtEnd, deletePageCurrent }
List<Widget> listPageView = List();

class ActionMenu extends StatelessWidget {
  final Function addPageView, removePageView;
  ActionMenu(this.addPageView, this.removePageView);

  @override
  Widget build(BuildContext context) {
    return PopupMenuButton<MenuOptions>(
      onSelected: (MenuOptions value) {
        switch (value) {
          case MenuOptions.addPageAtEnd:
            this.addPageView();
            break;
          case MenuOptions.deletePageCurrent:
            this.removePageView(context);
            break;
        }
      },
      itemBuilder: (BuildContext context) => <PopupMenuItem<MenuOptions>>[
        PopupMenuItem<MenuOptions>(
          value: MenuOptions.addPageAtEnd,
          child: const Text('Add Page at End'),
        ),
        const PopupMenuItem<MenuOptions>(
          value: MenuOptions.deletePageCurrent,
          child: Text('Delete Current Page'),
        ),
      ],
    );
  }
}
```
Can't we have the PageView swipeable even if it only has a single page?

**Comment by dnfield** [comment] 2020-10-12 17:50
See for example https://master-api.flutter.dev/flutter/widgets/MultiChildRenderObjectWidget/children.html - it'd be fine to update the docs on this to clarify though.

Using `itemBuilder` is different, because there's different machinery controlling the list passed to the widget and how to make sure it's different when adding or removing things.

I'm not sure what it would mean to have a swipeable page view with a single page :)

**Comment by omatt** [comment] 2020-10-12 18:04
>Using itemBuilder is different, because there's different machinery controlling the list passed to the widget and how to make sure it's different when adding or removing things.

So I guess what that means is that `PageView(children: List)` expects the List not to change.

> I'm not sure what it would mean to have a swipeable page view with a single page :)

What I meant was the behavior on creating a PageView using `PageView(children: List)` with the List only containing one Widget. The PageView created won't have a swipeable page. 

Unlike with PageView.builder(itemCount, itemBuilder) - setting itemCount to 1, the page created is swipeable. You can run both the repros that I've sent to compare the behavior.

**Comment by maheshmnj** [comment] 2022-11-25 22:27
Hi @omatt, I tried to reproduce the issue and I do notice that after adding a new page the list updates but the page is not swipable despite of calling setState. And this is working as intended as per the [current documentation](https://api.flutter.dev/flutter/widgets/PageView/PageView.html) which mentions that you cannot mutate the list passed to `PageView.children`. 

> Like other widgets in the framework, this widget expects that the children list will not be mutated after it has been passed in here. See the documentation at [SliverChildListDelegate.children](https://api.flutter.dev/flutter/widgets/SliverChildListDelegate/children.html) for more details. 


In case you need this dynamic behavior please use `Pageview.builder`

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as working as intended. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you

**Closed by maheshmnj** 2022-11-25 22:27 UTC
Labels: framework, f: material design, f: gestures, has reproducible steps, found in release: 1.22
