### ISSUE TITLE
Fix: Cupertino Icons

### ISSUE THREAD

**Issue by princekunal101** [flutter/flutter#160847] opened 2024-12-25 16:14 UTC
### Use case

When the using Cupertino Icon then that have two icons are overlapping each other on square_pencil and square_pencil_fill. This issue is continued yet.

### Proposal

square_pencil and square_pencil_fill review at once.

**Comment by danagbemava-nc** [comment] 2024-12-31 09:12
Closing this as a duplicate of https://github.com/flutter/flutter/issues/82634

**Closed by danagbemava-nc** 2024-12-31 09:12 UTC
Labels: in triage
