### ISSUE TITLE
Cannot Run on iOS 16.4 Real Device with XCode 14.2

### ISSUE THREAD

**Issue by zerowu49** [flutter/flutter#126494] opened 2023-05-11 04:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the flutter project via VSCode/XCode using iOS Real Device 16.4

Package in pubspec.yaml used that might become issue:
firebase_core: ^2.7.0
firebase_messaging: ^14.2.5
flutter_local_notifications: ^9.4.0

### Actual results

App launched but with white background app only on iOS Real Device. This error & log doesn't happen on iOS Simulator and via TestFlight app. I need to run the app on iOS Real Device to test In-App Purchase functionalities.

### Logs

<details>
<summary>Logs</summary>

```console

(lldb) 2023-05-11 11:16:31.080800+0700 Runner[707:22554] 10.3.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
10.3.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
10.3.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID 'XXX'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
[VERBOSE-2:dart_isolate.cc(143)] Could not prepare isolate.
[VERBOSE-2:runtime_controller.cc(385)] Could not create root isolate.
[VERBOSE-2:shell.cc(604)] Could not launch engine with configuration.
[TraitCollection] Class CKBrowserSwitcherViewController overrides the -traitCollection getter, which is not supported. If you're trying to override traits, you must use the appropriate API.

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6.5 21G531 darwin-arm, locale en-ID)
    • Flutter version 3.3.0 on channel stable at /Users/jonathan/fvm/versions/3.3.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone XI (mobile) • 00008030-000D785A2628C02E 

```

</details>

**Comment by darshankawar** [comment] 2023-05-11 08:49
> Package in pubspec.yaml used that might become issue: firebase_core: ^2.7.0 firebase_messaging: ^14.2.5 flutter_local_notifications: ^9.4.0

@zerowu49 Since these are firebase plugins and third party to flutter, if the issue you are reporting is occuring due to these plugins, you'll need to report in dedicated repo: https://github.com/firebase/flutterfire/issues

From the logs you shared, what is the exact error you think is not letting the app run ?


> ```
> [VERBOSE-2:dart_isolate.cc(143)] Could not prepare isolate.
> [VERBOSE-2:runtime_controller.cc(385)] Could not create root isolate.
> [VERBOSE-2:shell.cc(604)] Could not launch engine with configuration.
> ```

**Comment by zerowu49** [comment] 2023-05-12 03:38
> > Package in pubspec.yaml used that might become issue: firebase_core: ^2.7.0 firebase_messaging: ^14.2.5 flutter_local_notifications: ^9.4.0
> 
> @zerowu49 Since these are firebase plugins and third party to flutter, if the issue you are reporting is occuring due to these plugins, you'll need to report in dedicated repo: https://github.com/firebase/flutterfire/issues
> 
> From the logs you shared, what is the exact error you think is not letting the app run ?
> 
> > ```
> > [VERBOSE-2:dart_isolate.cc(143)] Could not prepare isolate.
> > [VERBOSE-2:runtime_controller.cc(385)] Could not create root isolate.
> > [VERBOSE-2:shell.cc(604)] Could not launch engine with configuration.
> > ```

I've already fix the Firebase part and still the "dart_isolate" things shows up. I think this issue is prior to the Flutter things since this issue only happen when debugging iOS Real Device, not in TestFlight iOS Real Device.

**Comment by darshankawar** [comment] 2023-05-12 05:36
We would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation that shows the log, so that it'll help us to properly analyze and address this issue.

**Comment by fighter777** [comment] 2023-05-12 08:06
Hello, you don't need xcode 14.3 for IOS 16.4 ?

Xcode 14.3 is only for macOS 13 ... 

cf : https://xcodereleases.com/

**Comment by Rexios80** [comment] 2023-05-18 12:10
Having the same issue here. Our app launches once in a blue moon and then every other time after it gets stuck outputting this:

```console
[VERBOSE-2:dart_isolate.cc(144)] Could not prepare isolate.
[VERBOSE-2:runtime_controller.cc(422)] Could not create root isolate.
[VERBOSE-2:shell.cc(609)] Could not launch engine with configuration.
```

There are no code or configuration differences between when it launches and when it fails. This started happening with Flutter 3.10.0

**Comment by Rexios80** [comment] 2023-05-18 12:19
Bad news (or good news?)... Disabling Impeller following the instructions [here](https://docs.flutter.dev/perf/impeller#ios) seems to have resolved the issue

**Comment by Rexios80** [comment] 2023-05-18 17:44
Okay I ended up having the same issue on Android. I deleted my pub cache and that seemed to fix it. For now... Will update if I continue to have issues.

**Comment by Rexios80** [comment] 2023-05-19 18:26
Okay so I may have narrowed it down to some state corruption in the debug server. I got the `Could not launch engine with configuration.` error multiple runs in a row, then all I did was reload the VSCode window (not closing VSCode) and ran it and it worked.

**Comment by zerowu49** [comment] 2023-05-27 09:08
This one is Screenshoot of Test app on real device iOS 16.4 with macOS Monterey 12.6.5. It still runs properly with the Test app code one.

![image](https://github.com/flutter/flutter/assets/22422143/8bbb4606-1f71-43b7-b72f-8450ad91d6c8)

**Comment by huycozy** [comment] 2023-05-29 04:05
@zerowu49 Since the issue doesn't appear on your test code, it may be caused by 3rd party plugin or other implementation code. 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the issue to find the cause. If you can reproduce the issue with minimal sample code, please provide it so that we may verify the issue properly. Thanks!

**Closed** 2023-06-19 04:10 UTC
Labels: waiting for customer response, in triage
