### ISSUE TITLE
[codelabs] `Building beautiful UIs with Flutter` has a typo.

### ISSUE THREAD

**Issue by gazeldx** [flutter/flutter#96355] opened 2022-01-09 04:10 UTC
## Steps to Reproduce

1. Visit https://codelabs.developers.google.com/codelabs/flutter#4
2. Search `Wrap the TextField inside a Flexible`.
3. In the first step, the `Select Row` should be replaced with `Select TextField`

<img width="1363" alt="Screen Shot 2022-01-09 at 12 10 15 PM" src="https://user-images.githubusercontent.com/1132770/148669084-d20dae7d-d11b-43cf-af9d-bda29056ead0.png">

**Comment by darshankawar** [comment] 2022-01-10 09:14
Closing this as a duplicate of https://github.com/flutter/website/issues/4881

**Closed by darshankawar** 2022-01-10 09:14 UTC
Labels: in triage
