### ISSUE TITLE
Provide the possibility to set playback speed on video player

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#57837] opened 2020-05-23 08:03 UTC
## Use case
I want my user to set playback speed of videos.

## Proposal
Exoplayer allows the developer to set the playback speed for media it plays. Flutters video player should have a function that allows this playback speed to be passed along to Exoplayer.

**Comment by TahaTesser** [comment] 2020-05-25 09:27
duplicate of https://github.com/flutter/flutter/issues/29900

**Closed by TahaTesser** 2020-05-25 09:27 UTC
