### ISSUE TITLE
CachingAssetBundle._fetchString gives poor error message

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#7715] opened 2017-01-27 23:46 UTC
Ian asked me to report this bug. Loading the asset from the .flx file appears to be failing. It would be good if we were given the asset string whose load failed.

## Logs

```
[00206.770] 09972.10019> [ERROR:dart_error.cc(16)] Unhandled exception:
[00206.770] 09972.10019> NoSuchMethodError: The getter 'buffer' was called on null.
[00206.770] 09972.10019> Receiver: null
[00206.770] 09972.10019> Tried calling: buffer
[00206.770] 09972.10019> #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
[00206.770] 09972.10019> #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
[00206.770] 09972.10019> #2      CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:148)
[00206.770] 09972.10019> #3      _RootZone.runUnary (dart:async/zone.dart:1404)
[00206.770] 09972.10019> #4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[00206.770] 09972.10019> #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[00206.770] 09972.10019> #6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[00206.770] 09972.10019> #7      _Future._completeWithValue (dart:async/future_impl.dart:477)
[00206.770] 09972.10019> #8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[00206.770] 09972.10019> #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[00206.770] 09972.10019> #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[00206.835] 09972.10019>  EXCEPTION CAUGHT BY SERVICES 
[00206.839] 09972.10019> The following message was thrown resolving a single-frame image stream:
[00206.839] 09972.10019> Unable to read data
[00206.840] 09972.10019> 
[00206.840] 09972.10019> When the exception was thrown, this was the stack:
[00206.853] 09972.10019> #0      AssetBundleImageProvider.loadAsync.<loadAsync_async_body> (package:flutter/src/services/image_provider.dart:284)
[00206.853] 09972.10019> (elided 8 frames from package dart:async)
[00206.860] 09972.10019> 
[00206.860] 09972.10019> Image provider: AssetImage(bundle: null, name: "packages/armadillo/res/Background.jpg")
[00206.860] 09972.10019> Image key: AssetBundleImageKey(bundle: PlatformAssetBundle@686690892(), name:
[00206.860] 09972.10019> "packages/armadillo/res/Background.jpg", scale: 1.0)
[00206.860] 09972.10019> 
[00206.860] 09972.10019> Another exception was thrown: Unable to read data
[00206.860] 09972.10019> Another exception was thrown: Unable to read data
```

**Comment by eseidelGoogle** [comment] 2017-01-28 01:10
Likely related to/dupe of https://github.com/flutter/flutter/issues/7115 ?

**Comment by eseidelGoogle** [comment] 2017-02-23 22:42
This is likely a very easy fix, and has occured with some frequency (causing confusion) for customer pink engineers, would be nice to fix sooner rather than later.

**Comment by abarth** [comment] 2017-02-24 18:14
@eseidelGoogle If you think something is easy to fix, consider applying the `easy fix` label.  If you think it would be nice to fix sooner rather than later, consider assigning it to a milestone that reflects.

**Closed** 2017-04-11 20:48 UTC
Labels: customer: fuschia, easy fix
