### ISSUE TITLE
[tool_crash] WipError

### ISSUE THREAD

**Issue by Insentionn** [flutter/flutter#146391] opened 2024-04-06 18:42 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WipError
```

```
```
[33m[!][39m Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
    [32m•[39m Flutter version 3.19.3 on channel stable at F:\flutter
    [33m![39m The flutter binary is not on your path. Consider adding F:\flutter\bin to your path.
    [33m![39m The dart binary is not on your path. Consider adding F:\flutter\bin to your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ba39319843 (4 weeks ago), 2024-03-07 15:22:21 -0600
    [32m•[39m Engine revision 2e4ba9c6fb
    [32m•[39m Dart version 3.3.1
    [32m•[39m DevTools version 2.31.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4170]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ba393198430278b6595976de84fe170f553cc728
### Plugins
cloud_firestore-4.16.0
cloud_firestore_web-3.11.0
firebase_core-2.28.0
firebase_core_web-2.14.0
firebase_storage-11.7.0
firebase_storage_web-3.9.0
flutter_credit_card-4.0.1
flutter_inappwebview-6.0.0
flutter_inappwebview_android-1.0.13
flutter_inappwebview_ios-1.0.13
flutter_inappwebview_macos-1.0.11
flutter_inappwebview_web-1.0.8
fluttertoast-8.2.4
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.0
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-04-08 08:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/56458

**Closed by danagbemava-nc** 2024-04-08 08:39 UTC
Labels: in triage
