### ISSUE TITLE
[plugins][camera][documentation] camera code sample is using outdated analysis

### ISSUE THREAD

**Issue by aoatmon** [flutter/flutter#96099] opened 2022-01-04 07:59 UTC
## Use case

[camera plugin](https://pub.dev/packages/camera) code sample is outdated

## To reproduce

1. clone [camera sample app](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example)
2. in `pubspec.yaml` replace `pedantic: ^1.10.0` w/   `flutter_lints: ^1.0.4`
3. run `flutter analyze`

```console

   info • Use key in widget constructors • lib/main.dart:15:7 • use_key_in_widget_constructors
   info • Avoid `print` calls in production code • lib/main.dart:38:5 • avoid_print
   info • Avoid `print` calls in production code • lib/main.dart:40:5 • avoid_print
   info • The operand can't be null, so the condition is always true • lib/main.dart:247:71 • unnecessary_null_comparison
   info • Prefer const with constant constructors • lib/main.dart:274:21 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:282:29 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:289:29 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:328:21 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:337:21 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:346:21 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:355:21 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:388:15 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:389:24 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:396:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:410:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:418:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:426:15 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:427:24 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:473:15 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:474:24 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:481:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:492:28 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:536:17 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/main.dart:537:17 • prefer_const_constructors
   info • Use a function declaration to bind a function to a name • lib/main.dart:573:11 • prefer_function_declarations_over_variables
   info • Avoid returning null for void • lib/main.dart:857:7 • avoid_returning_null_for_void
   info • Avoid returning null for void • lib/main.dart:872:7 • avoid_returning_null_for_void
   info • The operand can't be null, so the condition is always true • lib/main.dart:948:66 • unnecessary_null_comparison
   info • Use key in widget constructors • lib/main.dart:994:7 • use_key_in_widget_constructors

29 issues found. (ran in 2.2s)

```

## Proposal

update code sample w/ more recent settings

**Comment by danagbemava-nc** [comment] 2022-01-04 09:09
It looks like the camera plugin is using https://github.com/flutter/plugins/blob/master/analysis_options_legacy.yaml. It should be updated to https://github.com/flutter/plugins/blob/master/analysis_options.yaml sometime in the future. There are other plugins that are also using the legacy settings such as `google_sign_in`.

Leaving this open for further comments.

**Comment by stuartmorgan** [comment] 2022-01-04 15:22
Duplicate of https://github.com/flutter/flutter/issues/76229

**Closed by stuartmorgan** 2022-01-04 15:22 UTC
Labels: plugin, p: first party, p: camera, passed first triage
