### ISSUE TITLE
Variables vs Methods vs Functions vs Classes with build method.

### ISSUE THREAD

**Issue by KlausJokinen** [flutter/flutter#25551] opened 2018-12-19 11:00 UTC
Hello there,

I've been trying to find good documentation how a build methods should be constructed.

This is using Methods:
https://hastebin.com/pexaretave.java

This is using Classes:
https://hastebin.com/teceniculu.java

Of course you can also use Functions or variables. What is the correct way to do this? Is there some performance differences? When I should use Classes and when Methods/Functions/Variables?

Best regards,
Klaus

**Comment by zoechi** [comment] 2018-12-19 11:15
Duplicate of #19269

**Comment by zoechi** [comment] 2018-12-19 11:16
Especially this comment https://github.com/flutter/flutter/issues/19269#issuecomment-404667287

See also 

- https://stackoverflow.com/questions/51476234/subclass-a-class-that-extends-statelesswidget-or-statefulwidget-class
- https://stackoverflow.com/questions/51689435/what-scenarios-is-it-reasonable-to-use-a-function-to-define-a-widget-composition

**Closed by zoechi** 2018-12-19 11:15 UTC
