### ISSUE TITLE
Using scrollbar with static content using the listview.build causes app to crash

### ISSUE THREAD

**Issue by igloo12** [flutter/flutter#84644] opened 2021-06-15 18:23 UTC
I noticed that https://github.com/flutter/flutter/issues/42987 is marked as closed but I still encountering issues with this component. When I drag a scrollbar using a large list it causes a the attached error
![Screen Shot 2021-06-15 at 11 22 03 AM](https://user-images.githubusercontent.com/2858207/122103867-ee008a00-cdcb-11eb-89c5-307ae1cc27b6.png)
I have posted the code I am using below
 

```
final horizontalScroll = ScrollController();
    final verticalScroll = ScrollController();

    return Scrollbar(
        isAlwaysShown: true,
        controller: horizontalScroll,
        notificationPredicate: (predicate) {
          return predicate.depth == 0;
        },
        child: Scrollbar(
            isAlwaysShown: true,
            controller: verticalScroll,
            notificationPredicate: (predicate) {
              return predicate.depth == 1;
            },
            child: SingleChildScrollView(
                controller: horizontalScroll,
                scrollDirection: Axis.horizontal,
                child: SizedBox(
                    width: rightSideWidth,
                    child: Column(children: [
                      Row(children: _getHeaderWidgets()),
                      Expanded(
                          child: ListView.builder(
                        itemBuilder: (BuildContext context, int index) {
                          return getRow(index);
                        },
                        shrinkWrap: true,
                        controller: verticalScroll,
                        itemCount: _transactionsFiltered.length,
                      ))
                    ])))));
```

**Comment by TahaTesser** [comment] 2021-06-17 15:34
Hi @igloo12 
Can you please provide your `flutter doctor -v`,
Thank you

**Comment by igloo12** [comment] 2021-06-17 15:36
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale

    en-CA)

    *•** Flutter version 2.2.0 at /opt/flutter*

    *•** Framework revision b22742018b (5 weeks ago), 2021-05-14 19:12:57
-0700*

    *•** Engine revision a9d88a4d18*

    *•** Dart version 2.13.0*


[✓] Android toolchain - develop for Android devices (Android SDK version
30.0.3)

    *•** Android SDK at /Users/brandon/Library/Android/sdk*

    *•** Platform android-30, build-tools 30.0.3*

    *•** Java binary at: /Applications/Android*

*      Studio.app/Contents/jre/jdk/Contents/Home/bin/java*

    *•** Java version OpenJDK Runtime Environment (build
11.0.8+10-b944.6916264)*

    *•** All Android licenses accepted.*


[✓] Xcode - develop for iOS and macOS

    *•** Xcode at /Applications/Xcode.app/Contents/Developer*

    *•** Xcode 12.5, Build version 12E262*

    *•** CocoaPods version 1.10.1*


[✓] Chrome - develop for the web

    *•** Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
Chrome*


[✓] Android Studio (version 4.2)

    *•** Android Studio at /Applications/Android Studio.app/Contents*

    *•** Flutter plugin can be installed from:*

*      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
<https://plugins.jetbrains.com/plugin/9212-flutter>*

    *•** Dart plugin can be installed from:*

*      🔨 https://plugins.jetbrains.com/plugin/6351-dart
<https://plugins.jetbrains.com/plugin/6351-dart>*

    *•** Java version OpenJDK Runtime Environment (build
11.0.8+10-b944.6916264)*


[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)

    *•** IntelliJ at /Applications/IntelliJ IDEA.app*

    *•** Flutter plugin version 57.0.5*

    *•** Dart plugin version 211.7233*


[✓] Connected device (1 available)

    *•** Chrome (web) • chrome • web-javascript • Google Chrome
91.0.4472.106*


• No issues found!

**Comment by TahaTesser** [comment] 2021-06-18 07:31
Hi @igloo12 
Thanks for the details, After missing components in your code, I couldn't reproduce the issue on the latest `Channel stable, 2.2.2`


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final horizontalScroll = ScrollController();
  final verticalScroll = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Scrollbar(
          isAlwaysShown: true,
          controller: horizontalScroll,
          notificationPredicate: (predicate) {
            return predicate.depth == 0;
          },
          child: Scrollbar(
              isAlwaysShown: true,
              controller: verticalScroll,
              notificationPredicate: (predicate) {
                return predicate.depth == 1;
              },
              child: SingleChildScrollView(
                  controller: horizontalScroll,
                  scrollDirection: Axis.horizontal,
                  child: SizedBox(
                      width: 500,
                      child: Column(children: [
                        Row(
                          children: [
                            for (var i = 0; i < 2; i++)
                              FlutterLogo(
                                size: 200,
                                style: FlutterLogoStyle.horizontal,
                              ),
                          ],
                        ),
                        Expanded(
                            child: ListView.builder(
                          itemBuilder: (BuildContext context, int index) {
                            return Row(
                              children: [
                                FlutterLogo(
                                  size: 200,
                                  style: FlutterLogoStyle.horizontal,
                                ),
                              ],
                            );
                          },
                          shrinkWrap: true,
                          controller: verticalScroll,
                          itemCount: 15,
                        ))
                      ]))))),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>


Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by igloo12** [comment] 2021-06-22 04:19
Hi @TahaTesser the item count is too small try 300. Think the issue it is trying to draw all the rows on the scroll. When it should skip drawing on fast scrolls. My views are more complex and I have more rows 300.
Can see how slow this is with 700 rows 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final horizontalScroll = ScrollController();
  final verticalScroll = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Scrollbar(
          isAlwaysShown: true,
          controller: horizontalScroll,
          notificationPredicate: (predicate) {
            return predicate.depth == 0;
          },
          child: Scrollbar(
              isAlwaysShown: true,
              controller: verticalScroll,
              notificationPredicate: (predicate) {
                return predicate.depth == 1;
              },
              child: SingleChildScrollView(
                  controller: horizontalScroll,
                  scrollDirection: Axis.horizontal,
                  child: SizedBox(
                      width: 500,
                      child: Column(children: [
                        Row(
                          children: [
                            for (var i = 0; i < 2; i++)
                              FlutterLogo(
                                size: 200,
                                style: FlutterLogoStyle.horizontal,
                              ),
                          ],
                        ),
                        Expanded(
                            child: ListView.builder(
                              itemBuilder: (BuildContext context, int index) {
                                var childern =<Widget>[];
                                for(var i = 0; i < 7; i++){
                                  childern.add(Container(
                                    padding: EdgeInsets.all(5),
                                    child:Text("$i")
                                  ));
                                }
                                return Row(
                                  children: childern,
                                );
                              },
                              shrinkWrap: true,
                              controller: verticalScroll,
                              itemCount: 305,
                            ))
                      ]))))),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2021-06-22 06:10
Hi @igloo12 
Thanks for the code sample, I tried it on the latest `stable` on macOS and windows, aside from stutter when dragging the scrollbar or the list, nothing prints in the console log


https://user-images.githubusercontent.com/48603081/122872575-52c26400-d339-11eb-89b7-b184d03656e0.mov


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
    • Flutter version 2.2.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```

</details>

> draw all the rows during the scroll. When it should skip drawing on fast scrolls. My views are more complex and I have more rows ~300.

Since the crash seme to be with much more complex layout we can partially see the problem with code sample above, I feel safe to label the issue

**Comment by goderbauer** [comment] 2022-04-13 22:04
cc @Piinks

**Comment by Piinks** [comment] 2022-04-13 22:13
This may be a dupe of https://github.com/flutter/flutter/issues/75399, if so we should close this and follow progress in that issue.

I did notice though, this does not appear to account for the automatic scrollbars that are added on desktop. You may be seeing issues from having duplicate scrollbars on your scrollables: https://docs.flutter.dev/release/breaking-changes/default-desktop-scrollbars

**Closed** 2022-05-04 23:10 UTC
Labels: severe: crash, waiting for customer response, framework, f: scrolling, has reproducible steps, P4, found in release: 2.2, found in release: 2.3
