### ISSUE TITLE
Failed to bind web development server: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)

### ISSUE THREAD

**Issue by gh0stl0nely** [flutter/flutter#55663] opened 2020-04-26 04:59 UTC
I followed what is said on https://flutter.dev/docs/get-started/web to basically try to see my Flutter App on web but when I ran "flutter run -d chrome", the following message showed up:

 **SocketError :Failed to bind web development server: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)**

**Comment by VladyslavBondarenko** [comment] 2020-04-27 09:31
Hi @gh0stl0nely 
can you please provide your `flutter doctor -v` 
and `flutter run -d chrome --verbose`?

**Comment by gh0stl0nely** [comment] 2020-04-27 13:42
@VladyslavBondarenko This is what running `flutter doctor -v`. I dont use Xcode nor IntelliJ however. 

 gives me.

[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.13.6 17G8030, locale en-VN)
    • Flutter version 1.17.0-3.2.pre at /Users/nguyenanhthekhoi/Developer/flutter
    • Framework revision 2a7bc389f2 (5 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nguyenanhthekhoi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by gh0stl0nely** [comment] 2020-04-27 13:50
@VladyslavBondarenko This is what running `flutter run -d chrome --verbose ` gives.

[  +32 ms] executing: [/Users/nguyenanhthekhoi/Developer/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2a7bc389f28d83c581f7ddd4601588a22e12512e
[        ] executing: [/Users/nguyenanhthekhoi/Developer/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.17.0-3.2.pre-0-g2a7bc389f
[  +22 ms] executing: [/Users/nguyenanhthekhoi/Developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [/Users/nguyenanhthekhoi/Developer/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +266 ms] executing: [/Users/nguyenanhthekhoi/Developer/flutter/] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +12 ms] executing: sw_vers -productName
[  +32 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[        ] executing: sw_vers -productVersion
[  +30 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +34 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 17G8030
[  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +38 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] executing: /Users/nguyenanhthekhoi/Library/Android/sdk/platform-tools/adb devices -l
[  +15 ms] executing: /usr/bin/xcode-select --print-path
[  +20 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +6 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[   +1 ms] Xcode not found. Run 'flutter doctor' for more information.
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +6 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[  +64 ms] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] executing: /usr/bin/xcodebuild -version
[   +8 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[ +438 ms] Generating
/Users/nguyenanhthekhoi/Desktop/InStockOutOfStock-ISOS/Frontend/android/app/src/main/java/io/flutter/plugins/GeneratedPlugi
nRegistrant.java
[ +367 ms] Launching lib/main.dart on Chrome in debug mode...
[  +71 ms] "flutter run" took 1,461ms.

### **Failed to bind web development server:
SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8)**

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:221:7)
<asynchronous suspension>
#2      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:605:43)
#3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:426:44)
<asynchronous suspension>
#4      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart)
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     runZoned (dart:async/zone.dart:1536:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:407:20)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#31     _rootRun (dart:async/zone.dart:1184:13)
#32     _CustomZone.run (dart:async/zone.dart:1077:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by gilloh** [comment] 2020-05-31 12:19
Exact same issue. Following the same guide (https://flutter.dev/docs/get-started/web). Other platforms (iOS, Android) work for the same project. My details:
**flutter config**
Settings:
  enable-web: true
---
**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)
---
**Flutter devices:**
2 connected devices:

Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61
---
**flutter run -d chrome --verbose:**
[ +257 ms] Launching lib/main.dart on Chrome in debug mode...
[  +35 ms] "flutter run" took 3,298ms.
Failed to bind web development server:
SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor
servname provided, or not known, errno = 8)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      WebAssetServer.start
(package:flutter_tools/src/build_runner/devfs_web.dart:253:7)
<asynchronous suspension>
#2      WebDevFS.create
(package:flutter_tools/src/build_runner/devfs_web.dart:650:43)
#3      _ResidentWebRunner.run.<anonymous closure>
(package:flutter_tools/src/build_runner/resident_web_runner.dart:429:44)
<asynchronous suspension>
#4      _ResidentWebRunner.run.<anonymous closure>
(package:flutter_tools/src/build_runner/resident_web_runner.dart)
#5      asyncGuard.<anonymous closure>
(package:flutter_tools/src/base/async_guard.dart:111:32)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     runZoned (dart:async/zone.dart:1536:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     _ResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:403:20)
<asynchronous suspension>
#13     RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:565:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:797:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:686:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#27     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:686:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#30     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:560:7)
#31     _rootRun (dart:async/zone.dart:1184:13)
#32     _CustomZone.run (dart:async/zone.dart:1077:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1019:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by jonahwilliams** [comment] 2020-07-06 19:31
Duplicate of https://github.com/flutter/flutter/issues/53338

**Closed by jonahwilliams** 2020-07-06 19:31 UTC
Labels: platform-web, tool

**Comment by osamasado** [comment] 2020-07-29 12:08
I still have this problem when i call http.get request:
`SocketException: Failed host lookup: 'meisterclub-portal.local' (OS Error: No address associated with hostname, errno = 7)`
 `final String url = "http://meisterclub-portal.local/api/node/news";
  final response = await http.get(
      // Encode the url
      Uri.encodeFull(url),
      // only accept json response
      headers: {"Accept": "application/json", "accept-charset": "UTF-8"});`
I have added the INTERNT permision to my AndroidManifest.xml file. i try to call an API from Homested VM, that i have in my local machine.

**Comment by fikrirazzaq** [comment] 2020-09-03 01:49
This error occured when I use public wifi. But when I use a VPN, the error is gone.
