### ISSUE TITLE
InteractiveViewer content frequently "jumps" when scaled on iOS

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#66661] opened 2020-09-25 18:25 UTC
## Steps to Reproduce
Create a basic InteractiveViewer with a boundary around the contents. Run it on an iOS device (I'm testing on an iPhone X). Spend a couple minutes dragging and scaling the content around the screen. Notice that the content frequently "jumps" unnaturally rather than moving naturally with the touches.

I am not seeing this same issue when testing on a Google Pixel 3XL, leading me to believe this is an iOS-specific issue, but it could be something else about the devices, other than the OS.

Here's a simple demo app you can run on an iPhone to easily reproduce the issue:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => InteractiveViewer(
        boundaryMargin: EdgeInsets.all(500),
        child: Container(color: Colors.purple),
      ),
    );
  }
}
```

**Expected results:**
The content in the InteractiveViewer moves naturally and smoothly with the user's gestures.

**Actual results:**
Contents of the InteractiveViewer jump around unnaturally during some scale gestures. I can't determine the exact conditions that cause these jumps, since some gestures work fine, but it's easily reproducible on an iPhone X:
https://streamable.com/kz98z6

<details>
  <summary>Logs</summary>

There's nothing in the demo app's logs. Just successful build processes.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.4 at /Users/bryson/flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bryson/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone X (mobile) • 8ca2a91e9a7b3818f0cd37d0aa1c08b65921f2a9 • ios • iOS 14.0.1

! Doctor found issues in 1 category.
```

</details>

cc @justinmc

**Comment by justinmc** [comment] 2020-09-26 00:07
Thanks for reporting this.  Can you try again on master?  I wasn't able to reproduce this in the simulator or in a physical device.  I tried:

Simulator iPhone Xs running iOS 12.4.
Physical iPhone 8 running iOS 14.

A few things have changed since your version 1.20.4 so maybe that will fix it.  You could also try updating your stable, because I think that's out of date by 1 release.

**Comment by doppio** [comment] 2020-09-27 18:32
I tried upgrading to master and I'm still seeing this issue.

I did try reproducing the issue on a couple other devices (iPhone XR and iPhone 7) and was unable to reproduce it. So far I have only seen it on one iPhone X. I thought maybe the screen was defective, but I've tried using other apps with similar scaling/panning gestures and I'm not seeing the same issue. 🤔  Maybe there's nothing to be done here if it's just this one device acting up, but it is odd that I've never seen any other similar issues when testing on this device.

**Comment by TahaTesser** [comment] 2020-09-28 09:38
Unable to reprdocue it on XR

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => InteractiveViewer(
        boundaryMargin: EdgeInsets.all(500),
        child: Container(color: Colors.purple),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.385, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.385 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 73b6398932 (6 hours ago), 2020-09-28 11:07:32 +0800
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0.1

• No issues found!
```

</details> 

Can you please try web apge page similar gesture, if it is a device and also your streamable link is broken, I don't have a visual of your issue, can you please a recording of this behavior in Flutter
Thank you

**Comment by doppio** [comment] 2020-09-29 17:03
I'm not clear what you're asking for and the streamable link appears to be working for me. Are you asking for a different video @TahaTesser?

**Comment by TahaTesser** [comment] 2020-09-30 07:21
Hi @doppio 
Your straamable link doesn't work for me blob:https://imgur.com/60c95893-d1af-4826-ba16-5c31e4935330 
Please upgrade to the latest `master` and provide details from https://github.com/flutter/flutter/issues/66661#issuecomment-699897976
Thank you

**Comment by pedromassangocode** [comment] 2020-10-28 11:37
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-28 11:37 UTC
Labels: framework, in triage
