### ISSUE TITLE
DropdownMenu does not update entries and selected

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#121692] opened 2023-03-01 13:36 UTC
## Steps to Reproduce

1. Open https://dartpad.dev/?id=b3dfe00542c331d73e78e357b25be333
2. Click on the plus icon
3. Click on the dropdown menu

**Expected results:** 

Dropdown menu entries will be updated and the current selected value will be set to the last entry.

**Actual results:** 

Nothing happens

<details>
<summary>Code sample</summary>

https://dartpad.dev/?id=b3dfe00542c331d73e78e357b25be333

```dart
import 'package:flutter/material.dart';

void main() => runApp(const DropdownMenuExample());

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController selectedController = TextEditingController();
  String? selectedEntry = "0";
  final entries = ["0"];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.green),
      home: Scaffold(
        body: SafeArea(
            child: Column(
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  DropdownMenu<String>(
                    initialSelection: selectedEntry,
                    controller: selectedController,
                    label: const Text('Entries'),
                    onSelected: (String? entry) {
                      setState(() {
                        selectedEntry = entry;
                      });
                    },
                    dropdownMenuEntries: entries
                        .map((e) => DropdownMenuEntry(value: e, label: e))
                        .toList(),
                  ),
                  TextButton(
                    child: const Text("+1"),
                    onPressed: () {
                      setState(() { 
                        entries.add(entries.length.toString());
                        selectedEntry = entries.last;
                      });
                    },
                  )
                ],
              ),
            ),
          ],
        )),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```

```

```
Analyzing api...                                                        
No issues found! (ran in 0.9s)
```

```
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2673], locale de-DE)
    • Flutter version 3.7.5 on channel stable at D:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (7 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)      
    • Android SDK at D:\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Eclipse Adoptium\jdk-11.0.17.8-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.5.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33414.496
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at D:\JetBrains\apps\IDEA-U\ch-1\223.8617.56
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2673]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.56

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment] 2023-03-01 15:56
This is caused by your `entries` not being updated yet. You can try this code (may be not the most optimize algorithm, just an idea)

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const DropdownMenuExample());

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController selectedController = TextEditingController();
  String? selectedEntry = "0";
  List<String> entries = ["0"];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.green),
      home: Scaffold(
        body: SafeArea(
            child: Column(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 20),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      DropdownMenu<String>(
                        initialSelection: selectedEntry,
                        controller: selectedController,
                        label: const Text('Entries'),
                        onSelected: (String? entry) {
                          setState(() {
                            selectedEntry = entry;
                          });
                        },
                        dropdownMenuEntries: entries
                            .map((e) => DropdownMenuEntry(value: e, label: e))
                            .toList(),
                      ),
                      TextButton(
                        child: const Text("+1"),
                        onPressed: () {
                          setState(() {
                            List<String> temp = [...entries];
                            for(var i = 0; i < entries.length; i++) {
                              temp.add(entries[i]);
                            }
                            entries = [...temp];
                            selectedEntry = entries.last;
                          });
                        },
                      )
                    ],
                  ),
                ),
              ],
            )),
      ),
    );
  }
}
```
</details>

Your question is best suited for support channels like StackOverflow, so please ask the same there for other solutions if any.

Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2023-03-01 15:56 UTC
Labels: in triage

**Comment by CodeDoctorDE** [comment] 2023-03-01 16:25
@huycozy Can you please reopen the issue?
The problem also happens on your code. The selected option and the list doesn't change.

**Comment by znromonk** [comment] 2023-03-01 22:09
@CodeDoctorDE The reason it is not updating is because you are updating the list of string which is then used to map to the entry. As shown in the example in the docs, you need to create a list of `DropdownMenuEntry` and update those using setState.
 
You need to initialize it as such
```dart
  List<DropdownMenuEntry<String>> entries = [
    const DropdownMenuEntry(value: "0", label: "0")
  ];
```
, do this in setState
```dart
entries.add(
  DropdownMenuEntry(
    value: entries.length.toString(),
    label: entries.length.toString(),
  ),
);
selectedEntry = entries.last.value;
```
and finally just pass the variable like so `dropdownMenuEntries: entries,`

**Comment by leylinazi99** [comment] 2023-03-01 22:54
۱۴۰۱-۱۲-۱۱ ۱:۴۳ ‎+۰۳:۳۰ گرینویچ, znromonk ***@***.***>:

**Comment by CodeDoctorDE** [comment] 2023-03-02 06:14
On your example, the issue with the selected property also happens: https://dartpad.dev/8d0c0801dfb1fc635254472d718ded11

**Comment by CodeDoctorDE** [comment] 2023-03-02 06:14
> @CodeDoctorDE The reason it is not updating is because you are updating the list of string which is then used to map to the entry. As shown in the example in the docs, you need to create a list of `DropdownMenuEntry` and update those using setState.
> 
> You need to initialize it as such
> 
> ```dart
>   List<DropdownMenuEntry<String>> entries = [
>     const DropdownMenuEntry(value: "0", label: "0")
>   ];
> ```
> 
> , do this in setState
> 
> ```dart
> entries.add(
>   DropdownMenuEntry(
>     value: entries.length.toString(),
>     label: entries.length.toString(),
>   ),
> );
> selectedEntry = entries.last.value;
> ```
> 
> and finally just pass the variable like so `dropdownMenuEntries: entries,`

On your example, the issue with the selected property also happens: https://dartpad.dev/8d0c0801dfb1fc635254472d718ded11

**Comment by znromonk** [comment] 2023-03-02 15:31
Replace 
```dart
entries = [...entries, DropdownMenuEntry(value: i, label: i)];
```
with 
```dart
entries.add(DropdownMenuEntry(value: i, label: i));
```
I cannot say for certain why the spread operator doesn't work in this case.
