### ISSUE TITLE
`Linux web_tool_tests`  is flaky:  newly added code executes during hot restart: TimeoutException after 0:00:15.000000: Future not completed

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#85575] opened 2021-06-29 21:41 UTC
Current flaky ratio: 2.92%

Most recent failures: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2636/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2639/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2638/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2641/overview

stdout:
```
02:54 +4 ~2 -1: test/web.shard/hot_reload_web_test.dart: newly added code executes during hot restart [E]                                                                                              
  TimeoutException after 0:00:15.000000: Future not completed
```
or
```
03:30 +5 ~2 -1: test/web.shard/hot_reload_web_test.dart: newly added code executes during hot restart - canvaskit [E]                                                                                  
  TimeoutException after 0:00:15.000000: Future not completed
```

**Comment by zanderso** [comment] 2021-06-30 01:18
Duplicate of https://github.com/flutter/flutter/issues/85043

**Closed** 2021-06-30 01:20 UTC
Labels: P1, team: flakes, team: infra, tool
