### ISSUE TITLE
[web] Obscured TextField does not respect keyboardType value.

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#67391] opened 2020-10-06 08:15 UTC
Whenever I set a `TextField`'s `keyboardType: TextInputType.number` and `obscureText: true` the character keyboard opens up, but my desired keyboard type is the numerical keyboard.

This bug only happens on flutter for **web**. Android build is just fine.
I have tested this with SwiftKey and GBoard keyboards and the bug exists on both keyboards.

## Steps to Reproduce
```
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              obscureText: true,
              keyboardType: TextInputType.number,
            ),
          ],
        ),
      ),
    );
  }
}
```
Or this DartPad: https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.132, on Microsoft Windows [Version 10.0.19042.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.132 at D:\build-tools\flutter
    • Framework revision 5e97eed895 (24 hours ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\build-tools\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\build-tools\android-sdk
    • Java binary at: D:\build-tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\build-tools\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!
```

</details>

**Comment by sidrao2006** [comment] 2020-10-06 08:35
I was not able to reproduce this issue

![Screenshot_20201006-140431_Chrome.jpg](https://user-images.githubusercontent.com/66567899/95178362-fafcc080-07dc-11eb-8c21-a0392912fc72.jpg)

**Comment by darshankawar** [comment] 2020-10-06 10:49
@xclud 
How do you show the keyboard for Flutter web app ?

**Comment by xclud** [comment] 2020-10-06 10:59
I found out the code I wrote in the original message works (sorry), so the bug cannot be produced.

So, currently I am cutting a piece of my project which causes the bug and I will attach a not-working example in a zip file.

Basically I display the TextField in a Bottomsheet and a `DraggableScrollableSheet`. I paste here the code I am using:

```
return showModalBottomSheet<T>(
    context: context,
    isScrollControlled: true,
    builder: (context) => DraggableScrollableSheet(
      initialChildSize: initialChildSize,
      maxChildSize: maxChildSize,
      minChildSize: minChildSize,
      builder: (context, scrollController) {
        return CustomBottomSheet(
          title: title,
          child: builder.call(context, scrollController),
        );
      },
    ),
  );
```

**Comment by pedromassangocode** [comment] 2020-10-28 11:39
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-28 11:39 UTC
Labels: in triage
