### ISSUE TITLE
path_provider: PlatformException(channel-error, Unable to establish connection on channel., null, null) when running release build on Android

### ISSUE THREAD

**Issue by leewapadmi** [flutter/flutter#153683] opened 2024-08-19 09:14 UTC
### Steps to reproduce

In a *release* build, call getApplicationDocumentsDirectory somewhere in `main.dart` (after `WidgetsFlutterBinding.ensureInitialized();`) in order to initialize Hive (3rd party lib).

### Expected results

The app should run normally on an Android device

### Actual results

On Android, observe that the app freezes with a blank background and the following exception is shown in crashlytics:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(channel-error, Unable to establish connection on channel., null, null)
       at PathProviderApi.getApplicationDocumentsPath(messages.g.dart:86)
       at .getApplicationDocumentsDirectory(path_provider.dart:121)
       at HiveX.initFlutter(hive_extensions.dart:12)
       at .setupHive(hive_utils.dart:15)
       at .main(main.dart:118)
```

### Code sample

pubspec.yaml:

```
name: sample
description: A new Flutter project.

version: 1.2.0+683

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio Player
  just_audio: ^0.9.38

  # Bloc
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5

  # Casting
  flutter_nsd: ^1.5.0
  pure_chromecast: ^0.3.3

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1

  # Firebase
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.0.0

  # Fonts
  google_fonts: ^6.2.1

  # Freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # Image
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Networking
  http: ^1.2.1

  # Storage
  shared_preferences: ^2.2.3
  localstorage: ^5.0.0
  flutter_secure_storage: ^9.2.2

  # UI
  groovin_widgets: ^3.2.0
  flutter_widget_from_html_core: ^0.14.12
  auto_size_text: ^3.0.0
  oktoast: ^3.4.0

  # Utils
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_cache_manager: ^3.3.2
  flutter_device_type: ^0.4.0
  intl: ^0.19.0
  jiffy: ^6.3.1
  listview_utils_plus: ^0.0.3
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  timezone: ^0.9.3
  url_launcher: ^6.3.0
  uuid: ^4.4.0

  # Video Player
  chewie: ^1.8.1
  video_player: ^2.8.6

  # Webview
  flutter_custom_tabs: ^2.0.0+1
  webview_flutter: ^4.8.0

  # Workaround for gradle 8.x, should check if this has been updated properly in next months package.
  # This points to version 2.3.0
  # Github Issue: https://github.com/pikaju/flutter-maps-launcher/issues/40
  maps_launcher:
    git:
      url: https://github.com/pikaju/flutter-maps-launcher.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 13.6.6 22G630 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by huycozy** [comment] 2024-08-20 09:21
Hi @leewapadmi 
>On Android, observe that the app freezes with a blank background and the following exception is shown in crashlytics:

Are you able to reproduce this issue in `release` mode locally? Or does the issue only occur in production?

I checked this by running package [sample code](https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider/example/lib/main.dart), but the method `getApplicationDocumentsDirectory` outputs the expected result:

![Screenshot 2024-08-20 at 16 20 20](https://github.com/user-attachments/assets/b3da9273-2668-488c-ad0d-9f32510b2523)

The latest package version: `path_provider: ^2.1.4`

**Comment by leewapadmi** [comment] 2024-08-20 11:14
Thanks for the reply. This is reproducible in release mode locally. I'm using the following pubspec.yml:

```
name: sample
description: A new Flutter project.

version: 1.2.0+683

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio Player
  just_audio: ^0.9.38

  # Bloc
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5

  # Casting
  flutter_nsd: ^1.5.0
  pure_chromecast: ^0.3.3

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1

  # Firebase
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.0.0

  # Fonts
  google_fonts: ^6.2.1

  # Freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # Image
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Networking
  http: ^1.2.1

  # Storage
  shared_preferences: ^2.2.3
  localstorage: ^5.0.0
  flutter_secure_storage: ^9.2.2

  # UI
  groovin_widgets: ^3.2.0
  flutter_widget_from_html_core: ^0.14.12
  auto_size_text: ^3.0.0
  oktoast: ^3.4.0

  # Utils
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter_cache_manager: ^3.3.2
  flutter_device_type: ^0.4.0
  intl: ^0.19.0
  jiffy: ^6.3.1
  listview_utils_plus: ^0.0.3
  rxdart: ^0.27.7
  timezone: ^0.9.3
  url_launcher: ^6.3.0
  uuid: ^4.4.0

  # Video Player
  chewie: ^1.8.1
  video_player: ^2.8.6

  # Webview
  flutter_custom_tabs: ^2.0.0+1
  webview_flutter: ^4.8.0

  # Workaround for gradle 8.x, should check if this has been updated properly in next months package.
  # This points to version 2.3.0
  # Github Issue: https://github.com/pikaju/flutter-maps-launcher/issues/40
  maps_launcher:
    git:
      url: https://github.com/pikaju/flutter-maps-launcher.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
```

The issue persists with the following main.dart content:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await setupHive();
  runApp(MyApp());
}

Future setupHive() async {
  // getApplicationDocumentsDirectory called under the hood by Hive's initFlutter method
  await Hive.initFlutter();
  await Future.wait(boxes.map((box) async {
    await Hive.openBox<String>(box);
  }).toList());
}
```

**Comment by huycozy** [comment] 2024-08-21 05:56
Can you please provide a reduced sample code by removing unrelated dependencies then share it here? 

From my end, I created a new Flutter project, add dependencies as below and run Android app in release mode but couldn't reproduce the exception.

```yaml
hive: ^2.2.3
hive_flutter: ^1.1.0
path_provider: ^2.1.4
```

**Comment by merfire** [comment] 2024-08-27 08:44
I can confirm the exact same issue both on debug and release mode, but only on specific devices. For example on Samsung A13 (both Android 13 and 14) this happens 100% of the time, on some other phones like Samsung S23 and S24 this error is not reproducible.

Here is the error:
```
E/flutter (31122): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (31122): #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_android/messages.g.dart:86:7)
E/flutter (31122): <asynchronous suspension>
E/flutter (31122): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)
E/flutter (31122): <asynchronous suspension>
E/flutter (31122): #2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
E/flutter (31122): <asynchronous suspension>
E/flutter (31122): #3      initHive (package:di/data_module.dart:172:3)
E/flutter (31122): <asynchronous suspension>
E/flutter (31122): #4      main (package:app/main_dev.dart:24:3)
E/flutter (31122): <asynchronous suspension>
```

I'm still trying to create a reliable steps to reproduce, in new app with just path_provider and hive issue is not present.

**Comment by yeshu-cn** [comment] 2024-09-03 10:01
I have encountered the same issue. The app runs fine in Debug and Profile modes, but in Release mode, it returns the same error:

```
Installing build/app/outputs/flutter-apk/app-release.apk...
E/flutter (17082): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (17082): #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_android/messages.g.dart:86)
E/flutter (17082): <asynchronous suspension>
E/flutter (17082): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121)
E/flutter (17082): <asynchronous suspension>
E/flutter (17082): #2      main (package:nosugar_browser/main.dart:36)
E/flutter (17082): <asynchronous suspension>
E/flutter (17082): 
```

code:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  var dir = await getApplicationDocumentsDirectory();
```
This issue only occurs in the project I’m currently working on. I tried to create a minimal project to reproduce the issue but was unable to do so. I have no idea what’s causing this problem and am currently out of leads.

I’ve tried disabling minification and resource shrinking in the Release mode by setting:
```
minifyEnabled false
shrinkResources false
```
But this did not resolve the issue.

flutter doctor
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
[✓] Network resources

```

**Comment by leewapadmi** [comment] 2024-09-03 10:27
I was able to fix over here, but I haven't identified a root cause.

We recently migrated away from Gradle's imperative buildscript for plugins. Ensuring we were following the instructions here exactly seemed to fix the issue: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

**Comment by huycozy** [comment] 2024-09-04 03:22
Without reproduction steps, we will unfortunately have to close this issue. Please feel free to add a comment or file a new issue when you find out. Thanks!

**Closed by huycozy** 2024-09-04 03:22 UTC
Labels: in triage
