### ISSUE TITLE
In-app purchase plugin - subscription change support

### ISSUE THREAD

**Issue by 33-Elephants** [flutter/flutter#71148] opened 2020-11-24 09:59 UTC
Please add an ability to upgrade/downgrade subscriptions on Android platform: [Documentation](https://developer.android.com/google/play/billing/subscriptions#change)

Currently there is no way to pass old SKU and proration mode to in-app purchase engine.

**Comment by darshankawar** [comment] 2020-11-24 11:45
Closing this as duplicate of [32395](https://github.com/flutter/flutter/issues/32395)

**Closed by darshankawar** 2020-11-24 11:45 UTC
