### ISSUE TITLE
java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl

### ISSUE THREAD

**Issue by joshuajennysibbu** [flutter/flutter#89115] opened 2021-08-28 19:54 UTC
## Steps to Reproduce
Hai. I try to implement native code for a video view. So I use platformview. But I face some issues. and video is not playing.

<details>
<summary>log</summary>

```
problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2264].
E/MethodChannel#flutter/platform_views(21989): Failed to handle method call
E/MethodChannel#flutter/platform_views(21989): java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl
E/MethodChannel#flutter/platform_views(21989):  at android.view.Window.setWindowManager(Window.java:783)
E/MethodChannel#flutter/platform_views(21989):  at android.view.Window.setWindowManager(Window.java:765)
E/MethodChannel#flutter/platform_views(21989):  at android.widget.MediaController.initFloatingWindow(MediaController.java:150)
E/MethodChannel#flutter/platform_views(21989):  at android.widget.MediaController.<init>(MediaController.java:139)
E/MethodChannel#flutter/platform_views(21989):  at android.widget.MediaController.<init>(MediaController.java:144)
E/MethodChannel#flutter/platform_views(21989):  at com.example..NativeView.<init>(NativeView.kt:23)
E/MethodChannel#flutter/platform_views(21989):  at com.example..NativeViewFactory.create(NativeViewFactory.kt:12)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/MethodChannel#flutter/platform_views(21989):  at android.app.Dialog.dispatchOnCreate(Dialog.java:428)
E/MethodChannel#flutter/platform_views(21989):  at android.app.Dialog.show(Dialog.java:318)
E/MethodChannel#flutter/platform_views(21989):  at android.app.Presentation.show(Presentation.java:257)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(21989):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/platform_views(21989):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(21989):  at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/platform_views(21989):  at android.os.Looper.loop(Looper.java:182)
E/MethodChannel#flutter/platform_views(21989):  at android.app.ActivityThread.main(ActivityThread.java:7782)
E/MethodChannel#flutter/platform_views(21989):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(21989):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/platform_views(21989):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
W/Gralloc3(21989): allocator 3.x is not supported
E/flutter (21989): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, $Proxy1 cannot be cast to android.view.WindowManagerImpl, null, java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl
E/flutter (21989):  at android.view.Window.setWindowManager(Window.java:783)
E/flutter (21989):  at android.view.Window.setWindowManager(Window.java:765)
E/flutter (21989):  at android.widget.MediaController.initFloatingWindow(MediaController.java:150)
E/flutter (21989):  at android.widget.MediaController.<init>(MediaController.java:139)
E/flutter (21989):  at android.widget.MediaController.<init>(MediaController.java:144)
E/flutter (21989):  at com.example..NativeView.<init>(NativeView.kt:23)
E/flutter (21989):  at com.example..NativeViewFactory.create(NativeViewFactory.kt:12)
E/flutter (21989):  at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/flutter (21989):  at android.app.Dialog.dispatchOnCreate(Dialog.java:428)
E/flutter (21989):  at android.app.Dialog.show(Dialog.java:318)
E/flutter (21989):  at android.app.Presentation.show(Presentation.java:257)
E/flutter (21989):  at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (21989):  at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (21989):  at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (21989):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (21989):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (21989):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (21989):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (21989):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (21989):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21989):  at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (21989):  at android.os.Looper.loop(Looper.java:182)
E/flutter (21989):  at android.app.ActivityThread.main(ActivityThread.java:7782)
E/flutter (21989):  at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21989):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (21989):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/flutter (21989): )
E/flutter (21989): #0      StandardMethodCodec.decodeEnvelope
E/flutter (21989): #1      MethodChannel._invokeMethod
E/flutter (21989): <asynchronous suspension>
E/flutter (21989): #2      TextureAndroidViewController._sendCreateMessage
E/flutter (21989): <asynchronous suspension>
E/flutter (21989): #3      AndroidViewController.create
E/flutter (21989): <asynchronous suspension>
E/flutter (21989): #4      RenderAndroidView._sizePlatformView
E/flutter (21989): <asynchronous suspension>
E/flutter (21989):
I/Choreographer(21989): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/Choreographer(21989): Skipped 2 frames!  The application may be doing too much work on its main thread.
I/Choreographer(21989): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/Choreographer(21989): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/chatty  (21989): uid=10762(com.example.) identical 2 lines
I/Choreographer(21989): Skipped 1 frames!  The application may be doing too much work on its main thread.



```

</details>

**Comment by darshankawar** [comment] 2021-08-30 08:34
@joshuajennysibbu 
You may try to search for `java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl` error over internet to see if you get any leads on it. See [this](https://github.com/flutter/flutter/issues/25767) similar issue and check if it helps. https://github.com/flutter/flutter/issues/25767#issuecomment-638456709

**Comment by joshuajennysibbu** [comment] 2021-09-03 10:41
Still, I have an issue. I just copy-paste a code from flutter's official site. First i try with textView. Its work fine. Then I try for video view. I didn't change anything. I just replace a textView to VideoView.  This is a code...
           `init {
        val mediaController = MediaController(context)
        mediaController.setAnchorView(videoView)
        videoView!!.setMediaController(mediaController)
        videoView.setVideoPath("https://videocdn.bodybuilding.com/video/mp4/62000/62792m.mp4")
        videoView.requestFocus()
        videoView.start()
    }`

**Comment by darshankawar** [comment] 2021-09-03 13:02
@joshuajennysibbu 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue.
Thanks.

**Comment by joshuajennysibbu** [comment] 2021-09-05 13:15
`
E/MethodChannel#flutter/platform_views( 4181): Failed to handle method call
E/MethodChannel#flutter/platform_views( 4181): kotlin.KotlinNullPointerException
E/MethodChannel#flutter/platform_views( 4181): 	at com.example..NativeView.<init>(NativeView.kt:22)
E/MethodChannel#flutter/platform_views( 4181): 	at com.example..NativeViewFactory.create(NativeViewFactory.kt:11)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views( 4181): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/platform_views( 4181): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 4181): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/platform_views( 4181): 	at android.os.Looper.loop(Looper.java:182)
E/MethodChannel#flutter/platform_views( 4181): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/MethodChannel#flutter/platform_views( 4181): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 4181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/platform_views( 4181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/flutter ( 4181): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, null, null, kotlin.KotlinNullPointerException
E/flutter ( 4181): 	at com.example..NativeView.<init>(NativeView.kt:22)
E/flutter ( 4181): 	at com.example..NativeViewFactory.create(NativeViewFactory.kt:11)
E/flutter ( 4181): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/flutter ( 4181): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)
E/flutter ( 4181): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 4181): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 4181): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 4181): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 4181): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4181): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 4181): 	at android.os.Looper.loop(Looper.java:182)
E/flutter ( 4181): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/flutter ( 4181): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 4181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/flutter ( 4181): )
E/flutter ( 4181): #0      StandardMethodCodec.decodeEnvelope
E/flutter ( 4181): #1      MethodChannel._invokeMethod
E/flutter ( 4181): <asynchronous suspension>
E/flutter ( 4181): #2      AndroidViewController.create
E/flutter ( 4181): <asynchronous suspension>
E/flutter ( 4181):
I/Choreographer( 4181): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4181): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/chatty  ( 4181): uid=10775(com.example.) identical 8 lines
I/Choreographer( 4181): Skipped 1 frames!  The application may be doing too much work on its main thread.
`
1 week before I get java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl bug. But now I get  kotlin.KotlinNullPointerException.  
This is my code:

`import android.content.Context
import android.view.View
import android.widget.MediaController
import android.widget.VideoView
import io.flutter.plugin.platform.PlatformView

internal class NativeView(context: Context, id: Int, creationParams: Map<String?, Any?>?) : PlatformView {
    private val videoView: VideoView?=null

    override fun getView(): View {
        return videoView!!
    }

    override fun dispose() {}

    init {
        print("Called from init")
        val mediaController = MediaController(context)
        mediaController.setAnchorView(videoView)
        videoView!!.setMediaController(mediaController)
        videoView.setVideoPath("https://videocdn.bodybuilding.com/video/mp4/62000/62792m.mp4")
        videoView.layoutParams.height=videoView.height
        videoView.layoutParams.width=videoView.width
        videoView.requestFocus()
        videoView.start()
    }
}`

**Comment by darshankawar** [comment] 2021-09-06 05:54
> I just copy-paste a code from flutter's official site

Can you provide the link you are referring to ? We also need to see your `flutter doctor -v`.

**Comment by joshuajennysibbu** [comment] 2021-09-06 06:10
I get code from flutter's official [site.](https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-kotlin-tab)

flutter doctor -v return no issue found.
`flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.3 at /home/joshua/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/joshua/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /snap/intellij-idea-ultimate/316
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • RMX1851 (mobile) • cad2eeb2 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)  • linux    • linux-x64      • Linux
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!`

**Comment by darshankawar** [comment] 2021-09-06 06:28
@joshuajennysibbu 
Can you provide us a repo link that we can clone and run to verify this ?

**Comment by joshuajennysibbu** [comment] 2021-09-06 11:02
@darshankawar 
I fix `$Proxy1 cannot be cast to android.view.WindowManagerImpl` and nullpointerexception. But I stuck with another bug.. `java.io.FileNotFoundException: No content provider`. the app is exit when running the app. 
flutter doctor returns no issue found. 

`Launching lib/main.dart on RMX1851 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
D/SurfaceView( 7312): 95257319 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:false, mWindowStopped:true by android.view.SurfaceView.onWindowVisibilityChanged:292 android.view.View.dispatchWindowVisibilityChanged:13970 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewRootImpl.performTraversals:2340
D/SurfaceView( 7312): 95257319 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:false, mWindowStopped:false by android.view.SurfaceView.windowStopped:264 android.view.ViewRootImpl.setWindowStopped:1734 android.view.WindowManagerGlobal.setStoppedState:685 android.app.Activity.performRestart:8058 android.app.ActivityThread.performRestartActivity:4995 android.app.servertransaction.TransactionExecutor.performLifecycleSequence:248 android.app.servertransaction.TransactionExecutor.cycleToPath:206 android.app.servertransaction.TransactionExecutor.executeLifecycleState:178
D/SurfaceView( 7312): 95257319 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:true, mWindowStopped:false by android.view.SurfaceView.onWindowVisibilityChanged:292 android.view.View.dispatchWindowVisibilityChanged:13970 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewGroup.dispatchWindowVisibilityChanged:1580 android.view.ViewRootImpl.performTraversals:2340
I/SurfaceView( 7312): 95257319 Changes: creating=true format=false size=false visible=true left=false top=false
I/SurfaceView( 7312): 95257319 mSurfaceControl 150240314 mBackgroundControl 214876395 creating: SurfaceView - com.example./com.example..MainActivity
I/SurfaceView( 7312): 95257319 Cur surface: Surface(name=null)/@0x19e5932, visible=true
I/SurfaceView( 7312): 95257319 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
I/SurfaceView( 7312): 95257319 surfaceChanged -- format=4 w=1080 h=2340 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
I/SurfaceView( 7312): 95257319 surfaceRedrawNeeded
I/SurfaceView( 7312): 95257319 finishedDrawing
V/SurfaceView( 7312): Layout: x=0 y=0 w=1080 h=2340, frame=Rect(0, 0 - 1080, 2340)
D/SurfaceView( 7312): 59895368 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:false, mWindowStopped:false by android.view.SurfaceView.onAttachedToWindow:276 android.widget.VideoView.onAttachedToWindow:896 android.view.View.dispatchAttachedToWindow:19798 android.view.ViewGroup.dispatchAttachedToWindow:3449 android.view.ViewGroup.addViewInner:5245 android.view.ViewGroup.addView:5023 android.view.ViewGroup.addView:4963 android.view.ViewGroup.addView:4936
D/SurfaceView( 7312): 59895368 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:true, mWindowStopped:false by android.view.SurfaceView.onWindowVisibilityChanged:292 android.view.View.dispatchAttachedToWindow:19815 android.view.ViewGroup.dispatchAttachedToWindow:3449 android.view.ViewGroup.addViewInner:5245 android.view.ViewGroup.addView:5023 android.view.ViewGroup.addView:4963 android.view.ViewGroup.addView:4936 io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded:737
W/Gralloc3( 7312): allocator 3.x is not supported
I/Choreographer( 7312): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/SurfaceView( 7312): 59895368 Changes: creating=true format=true size=true visible=true left=true top=true
I/SurfaceView( 7312): 59895368 mSurfaceControl 228467206 mBackgroundControl 22446279 creating: SurfaceView - com.example./com.example..MainActivity
I/SurfaceView( 7312): 59895368 Cur surface: Surface(name=null)/@0xdfba6f4, visible=true
I/SurfaceView( 7312): 59895368 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
V/OppoMediaPlayer( 7312): system load
V/OppoMediaPlayer( 7312): new OppoMediaPlayer
I/OppoMediaPlayer( 7312): new mediaplayer ,packageName = com.example.
I/OppoMediaPlayer( 7312): isPlaying() isOppoCreate=false
I/OppoMediaPlayer( 7312): getMediaTimeProvider() isOppoCreate = false
I/OppoMediaPlayer( 7312): setSubtitleAnchor() isOppoCreate = false
I/OppoMediaPlayer( 7312): setDataSource(Context, Uri, headers) isOppoCreate=false
W/MediaPlayer( 7312): Couldn't open https://commondatastorage.googleapis.com/...
W/MediaPlayer( 7312): java.io.FileNotFoundException: No content provider: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
W/MediaPlayer( 7312): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1692)
W/MediaPlayer( 7312): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1522)
W/MediaPlayer( 7312): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1439)
W/MediaPlayer( 7312): 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1202)
W/MediaPlayer( 7312): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1174)
W/MediaPlayer( 7312): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1198)
W/MediaPlayer( 7312): 	at android.widget.VideoView.openVideo(VideoView.java:412)
W/MediaPlayer( 7312): 	at android.widget.VideoView.access$2200(VideoView.java:83)
W/MediaPlayer( 7312): 	at android.widget.VideoView$7.surfaceCreated(VideoView.java:694)
W/MediaPlayer( 7312): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:828)
W/MediaPlayer( 7312): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:172)
W/MediaPlayer( 7312): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
W/MediaPlayer( 7312): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
W/MediaPlayer( 7312): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2013)
W/MediaPlayer( 7312): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8202)
W/MediaPlayer( 7312): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1085)
W/MediaPlayer( 7312): 	at android.view.Choreographer.doCallbacks(Choreographer.java:908)
W/MediaPlayer( 7312): 	at android.view.Choreographer.doFrame(Choreographer.java:835)
W/MediaPlayer( 7312): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
W/MediaPlayer( 7312): 	at android.os.Handler.handleCallback(Handler.java:883)
W/MediaPlayer( 7312): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/MediaPlayer( 7312): 	at android.os.Looper.loop(Looper.java:228)
W/MediaPlayer( 7312): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
W/MediaPlayer( 7312): 	at java.lang.reflect.Method.invoke(Native Method)
W/MediaPlayer( 7312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/MediaPlayer( 7312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
I/OppoMediaPlayer( 7312): setDataSource(path, headers) isOppoCreate=false
V/MediaHTTPService( 7312): MediaHTTPService(android.media.MediaHTTPService@db06263): Cookies: null
I/OppoMediaPlayer( 7312): setDisplay() isOppoCreate=false
I/OppoMediaPlayer( 7312): setAudioAttributes() isOppoCreate = false
I/OppoMediaPlayer( 7312): setScreenOnWhilePlaying() isOppoCreate=false screenOn=true
I/OppoMediaPlayer( 7312): prepareAsync() isOppoCreate=false
V/MediaHTTPService( 7312): makeHTTPConnection: CookieManager created: java.net.CookieManager@509ff19
V/MediaHTTPService( 7312): makeHTTPConnection(android.media.MediaHTTPService@db06263): cookieHandler: java.net.CookieManager@509ff19 Cookies: null
I/SurfaceView( 7312): 59895368 surfaceChanged -- format=4 w=1080 h=2340 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
I/SurfaceView( 7312): 59895368 surfaceRedrawNeeded
I/SurfaceView( 7312): 59895368 finishedDrawing
V/SurfaceView( 7312): Layout: x=0 y=0 w=1080 h=2340, frame=Rect(0, 0 - 1080, 2340)
I/DpmTcmClient( 7312): RegisterTcmMonitor from: $Proxy0
D/AndroidRuntime( 7312): Shutting down VM
E/AndroidRuntime( 7312): FATAL EXCEPTION: main
E/AndroidRuntime( 7312): Process: com.example., PID: 7312
E/AndroidRuntime( 7312): java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
E/AndroidRuntime( 7312): 	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:946)
E/AndroidRuntime( 7312): 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:953)
E/AndroidRuntime( 7312): 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:76)
E/AndroidRuntime( 7312): 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:127)
E/AndroidRuntime( 7312): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1550)
E/AndroidRuntime( 7312): 	at io.flutter.embedding.android.FlutterImageView.onDraw(FlutterImageView.java:211)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21696)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21565)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4476)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4213)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21563)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4476)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4213)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21563)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4476)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4213)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21563)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4476)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4213)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21563)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4476)
E/AndroidRuntime( 7312): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4213)
E/AndroidRuntime( 7312): 	at android.view.View.draw(View.java:21699)
E/AndroidRuntime( 7312): 	at com.android.internal.policy.DecorView.draw(DecorView.java:859)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4125)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4029)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3796)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2013)
E/AndroidRuntime( 7312): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8202)
E/AndroidRuntime( 7312): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1085)
E/AndroidRuntime( 7312): 	at android.view.Choreographer.doCallbacks(Choreographer.java:908)
E/AndroidRuntime( 7312): 	at android.view.Choreographer.doFrame(Choreographer.java:835)
E/AndroidRuntime( 7312): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
E/AndroidRuntime( 7312): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 7312): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 7312): 	at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime( 7312): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/AndroidRuntime( 7312): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
I/Process ( 7312): Sending signal. PID: 7312 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by darshankawar** [comment] 2021-09-06 13:21
If you are using any url for the video view, check if it has any extra spaces in it. See similar issues related which are not specific to Flutter.  https://github.com/ArthurHub/Android-Image-Cropper/issues/466

Also you can do google search for `java.io.FileNotFoundException: No content provider` for similar logged issues and see if you get any leads.

**Comment by joshuajennysibbu** [comment] 2021-09-06 13:45
I try with a different device. But this is not working on my mobile-only. 
I write a code in flutter for file permission. If I use native view, I need to write a code with kotlin, or flutter code is enough

**Comment by darshankawar** [comment] 2021-09-07 06:26
For the error you are getting:

`java.io.FileNotFoundException: No content provider: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4`

Check [this](https://stackoverflow.com/questions/47005151/java-io-filenotfoundexception-no-content-provider) SO link and see if any of the underlying solutions works for you.




> I write a code in flutter for file permission. If I use native view, need to write a code with kotlin, or flutter code is enough

Please ask support questions on StackOverflow.

I am going ahead and closing this as non-issue from framework side. I tried the code mentioned in the [link](https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-kotlin-tab) as -is, which works properly.  

Since you are trying to use a video view, it may have a different use case to implement which you can try to see in the SO link I shared above. If you disagree, write in comments and I'll reopen it.  Also, your original issue you reported, `java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl` seems to have been resolved already based on one of your earlier comments above.

**Closed by darshankawar** 2021-09-07 06:26 UTC
Labels: in triage
