### ISSUE TITLE
Cannot build for web on ARM64

### ISSUE THREAD

**Issue by ntflix** [flutter/flutter#79792] opened 2021-04-05 16:42 UTC
## Steps to Reproduce

1. Fresh Debian install on ARM64 host
2. Download Flutter and add `[Flutter directory]/bin` to `PATH`:
```sh
$ git clone https://github.com/flutter/flutter
cd flutter
flutter channel dev && flutter upgrade
echo export PATH="$PATH:`pwd`/bin" >> ~/.zshrc
```
3. Create new Flutter project
```sh
cd ..
flutter create cool_project
cd cool_project
flutter config --enable-web
flutter create .
```
4. Attempt to build project for web - fails
```sh
flutter build web
```
error: `Target dart2js failed: Exception: Error: Error when reading '../../flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot': No such file or directory`

## Logs

<details>
<summary>Logs</summary>

`flutter build web --verbose`:

```sh
➜  cool_project flutter build web --verbose 
[ +211 ms] executing: uname -m
[ +120 ms] Exit code 0 from: uname -m
[   +1 ms] aarch64
[  +43 ms] executing: [/mnt/rocc/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +43 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[   +1 ms] executing: [/mnt/rocc/flutter/] git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[  +57 ms] Exit code 0 from: git tag --points-at 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
[        ] 2.1.0-12.1.pre
[ +126 ms] executing: [/mnt/rocc/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/mnt/rocc/flutter/] git ls-remote --get-url origin
[  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter
[ +169 ms] Unable to locate an Android SDK.
[  +16 ms] executing: [/mnt/rocc/flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[ +223 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +169 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +26 ms] Downloading Web SDK...
[ +804 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/711ab3fda05004ee5f6035f2a0bf099fca39a129/flutter-web-sdk-linux-x64.zip md5 hash: eUSMjcKyxHLkaHQHik0sBg==
[+5233 ms] Downloading Web SDK... (completed in 6.0s)
[   +5 ms] executing: unzip -o -q /mnt/rocc/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/711ab3fda05004ee5f6035f2a0bf099fca39a129/flutter-web-sdk-linux-x64.zip -d
/mnt/rocc/flutter/bin/cache/flutter_web_sdk
[+2387 ms] Exit code 0 from: unzip -o -q /mnt/rocc/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/711ab3fda05004ee5f6035f2a0bf099fca39a129/flutter-web-sdk-linux-x64.zip -d
/mnt/rocc/flutter/bin/cache/flutter_web_sdk
[+2109 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +142 ms] Skipping pub get: version match.
[ +371 ms] Generating /mnt/rocc/build/cool_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +121 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[ +149 ms] Compiling lib/main.dart for the Web...
[  +12 ms] Initializing file store
[  +76 ms] web_entrypoint: Starting due to {InvalidatedReason.inputChanged}
[   +4 ms] Skipping target: gen_localizations
[  +23 ms] web_entrypoint: Complete
[   +4 ms] dart2js: Starting due to {}
[+2124 ms] Persisting file store
[   +7 ms] Done persisting file store
[   +6 ms] Target dart2js failed: Exception: Error: Error when reading '../../flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot': No such file or directory
           
[  +11 ms] Compiling lib/main.dart for the Web... (completed in 2,268ms)
[        ] "flutter web" took 13,917ms.
[  +10 ms] Exception: Failed to compile application for the Web.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:86:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:91:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +7 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1
➜  cool_project 
```

## Flutter doctor output

```
➜  cool_project flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /mnt/rocc/flutter
    • Framework revision 8264cb3e8a (4 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by jonahwilliams** [comment] 2021-04-05 21:31
Duplicate of https://github.com/flutter/flutter/issues/74928

**Closed by jonahwilliams** 2021-04-05 21:31 UTC
