### ISSUE TITLE
DateFormat.E and DateFormat.EEE returning the same

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#47723] opened 2019-12-24 08:33 UTC
Spent a few hours today trying to figure out what happened to my project and apparently `DateFormat.E` and `DateFormat.EEE` Are returning the same thing even though they should not be.

`DateFormat.E` should return the abbreviated version of the weekday. (Example: `Mon`)
`DateFormat.EEE` should return the weekday. (Example: `Monday`)

```
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.5 at /Users/elias/flutter
    • Framework revision 41a911099b (in the future), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/elias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • C5EDAE24-E60A-4373-A52E-84ED09B845F9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.88
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

**Comment by shihaohong** [comment] 2019-12-24 19:04
Is this an issue with the `intl` library's [DateFormat class](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html)? If so, you might want to file an issue there instead.

Also, from what you're saying, it sounds like this might be a regression somewhere. Could you share a reproducible sample and elaborate on what is happening?

**Comment by EliasDeuss** [comment] 2019-12-25 06:01
@shihaohong Ok opened a issue: https://github.com/dart-lang/intl/issues/249

All it is
```dart 
 print(DateFormat.E().format(DateTime.now()));
```
If the current day is "Monday" it should return "Mon" but currently it's retuning "Monday"

**Comment by shihaohong** [comment] 2019-12-25 07:11
Sounds good, I’ll close this issue since it’s an issue with the intl library and not Flutter.

**Closed by shihaohong** 2019-12-25 07:11 UTC
Labels: framework
