### ISSUE TITLE
Add-to-app on iOS: Error in PathProvider ( getApplicationDocumentsDirectory() )

### ISSUE THREAD

**Issue by kundankuldeep** [flutter/flutter#132935] opened 2023-08-21 07:26 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Build an add to app flutter module
2. Create a framework from that module for IOS
3. Add that framework to Native IOS application
4. Run the IOS application, object box will not working
5. It is creating the following error

### Expected results

It should provide a valid document path for the objectbox to store files.

### Actual results

unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:42)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121)
<asynchronous suspension>
#2      ObjectBox.create (package:flutter_lib/objectBox/ObjectBoxManager.dart:28)

### Code sample

<details><summary>Code sample</summary>

```dart
  static Future<ObjectBox> create() async {
    if (_instance != null) return _instance!;

    /// store path
    /// Issue is here while getApplicationDocumentsDirectory.
    final docsDir = await getApplicationDocumentsDirectory();
    var storePath = p.join(docsDir.path, "some-db");

    /// instantiation of store
    if (Store.isOpen(storePath)) {
      final store = Store.attach(getObjectBoxModel(), storePath);
      _instance = ObjectBox._create(store);
    } else {
      final store = await openStore(directory: storePath);
      _instance = ObjectBox._create(store);
    }

    return _instance!;
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
_2023-08-17 17:41:59.439466+0530 ***********[1927:1023140] flutter: ObjectBoxIssue: message: [0]
2023-08-17 17:41:59.442221+0530 ***********[1927:1023140] flutter: Flutter: setThemeMode-> Brightness.light
2023-08-17 17:41:59.446920+0530 ***********[1927:1023140] flutter: Flutter: setThemeMode-> Brightness.light
2023-08-17 17:41:59.447347+0530 ***********[1927:1023140] flutter: ObjectBoxIssue: getDirectoryPath: arg_type: DirectoryType.applicationDocuments
2023-08-17 17:41:59.447382+0530 ***********[1927:1023140] flutter: ObjectBoxIssue: message: [0]
2023-08-17 17:41:59.447824+0530 ***********[1927:1022736] Flutter : response ACTION_DEVICE_INFO - nil)
2023-08-17 17:41:59.448239+0530 ***********[1927:1023140] flutter: ObjectBoxIssue: getDirectoryPath: replyList: null
2023-08-17 17:41:59.449447+0530 ***********[1927:1023140] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:42)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121)
<asynchronous suspension>
#2      ObjectBox.create (package:flutter_lib/objectBox/ObjectBoxManager.dart:28)
<asynchronous suspension>
#3      initObjectBox (package:flutter_lib/main.dart:66)
<asynchronous suspension>
Push Token:579793f10d2722900611b45ba7ad8ae47712a9af907edbc08ad8402edfe47ae6
2023-08-17 17:41:59.452891+0530 ***********[1927:1023140] flutter: ObjectBoxIssue: getDirectoryPath: replyList: null
2023-08-17 17:41:59.453239+0530 ***********[1927:1023140] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getDirectoryPath (package:path_provider_foundation/messages.g.dart:42)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121)
<asynchronous suspension>
#2      ObjectBox.create (package:flutter_lib/objectBox/ObjectBoxManager.dart:28)
<asynchronous suspension>
#3      initObjectBox (package:flutter_lib/main.dart:66)
<asynchronous suspension>
#4      getDlManager (package:flutter_lib/main.dart:52)
<asynchronous suspension>
#5      _ApplicationState.initEventManager (package:flutter_lib/main.dart:144)
<asynchronous suspension>_
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
• Flutter version 3.13.0 on channel stable at /Users/******/*****/FlutterDev/sdk/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision efbf63d9c6 (35 hours ago), 2023-08-15 21:05:06 -0500
• Engine revision 1ac611c64e
• Dart version 3.1.0
• DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
• Android SDK at /Users/kundankumar/Library/Android/sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14E300c
• CocoaPods version 1.12.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.70.0

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-arm64 • macOS 13.4.1 22F770820d darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
• All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by farhantandia** [comment] 2023-08-21 08:41
#132483 The same as my issue, still no solution/suggestion yet

**Comment by dam-ease** [comment] 2023-08-21 12:27
Hi @kundankuldeep. Thanks for filing this. There seems to be an already open issue describing this exact case, kindly upvote, comment and follow up on the issue for updates from the team.
Closing this as a duplicate of https://github.com/flutter/flutter/issues/132483.
Thank you!

**Closed by dam-ease** 2023-08-21 12:27 UTC
Labels: in triage

**Comment by kundankuldeep** [comment] 2023-08-22 09:21
> #132483 The same as my issue, still no solution/suggestion yet

Thanks @farhantandia, hope we get solution for this soon.
