### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\tools\flutter\bin\cache\dart-sdk\bin\pub.bat" in the search path. Command: C:\tools\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 0

### ISSUE THREAD

**Issue by Thebluedragon7** [flutter/flutter#85468] opened 2021-06-28 18:12 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\tools\flutter\bin\cache\dart-sdk\bin\pub.bat" in the search path. Command: C:\tools\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#6      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:283:34)
<asynchronous suspension>
#7      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:223:7)
<asynchronous suspension>
#8      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:133:7)
<asynchronous suspension>
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:166:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
```
```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 6.1.7601], locale en-GB)
    • Flutter version 2.2.1 at C:\tools\flutter
    • Framework revision 02c026b03c (5 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DELL-PC\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • CPH1717 (mobile) • EMB6SSYLMZRWPFGU • android-arm64  • Android 7.1.1 (API 25)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.124

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
path_provider_linux-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0

**Comment by darshankawar** [comment] 2021-06-29 10:43
Closing this as duplicate of https://github.com/flutter/flutter/issues/80418

**Closed by darshankawar** 2021-06-29 10:43 UTC
Labels: in triage
