### ISSUE TITLE
Dart snapshot generator failed with exit code -6  Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by maxisme** [flutter/flutter#89482] opened 2021-09-04 21:37 UTC
## Steps to Reproduce

```
flutter channel dev
flutter upgrade
git clone https://github.com/maxisme/notifi
cd notifi
git checkout develop
flutter build macos --release
```
(my master branch works fine)

**Expected results:** 
The app to build

**Actual results:** 
<details>
  <summary>Logs</summary>

```
===== CRASH =====
si_signo=Bus error: 10(10), si_code=2, si_addr=0x104d74240
Dart snapshot generator failed with exit code -6

Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
/Users/max/work/notifi/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 11.3.99. (in target 'FMDB' from project 'Pods')
** BUILD FAILED **

Building macOS application...                                           
Build process failed
```

`$ flutter run -d macos` works fine

```
Analyzing notifi...                                                     
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel dev, 2.6.0-0.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-0.0.pre at /usr/local/Caskroom/flutter/2.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83b9e99cfb (12 days ago), 2021-08-23 19:03:21 +0200
    • Engine revision d5adde01dd
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/max/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/max/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

**Comment by maxisme** [comment] 2021-09-05 15:56
the `stable` branch works fine just happening on `develop` and `master`.

**Comment by mraleph** [comment] 2021-09-06 09:36
Seems to blow up in closure inlining due to an attempt to inline closure at a mismatching callsite. Reduction:

```dart
void other({String something = "ok"}) {
  print(something);
}

void main(List<String> args) {
  Function x = other;
  if (x is void Function(List<String>)) {
    x(args);
  } else {
    x();
  }
}
```

**Comment by mkustermann** [comment] 2021-09-06 09:38
@dcharkes Could you take a look at this?

**Comment by dcharkes** [comment] 2021-09-06 15:29
Reproduces on master and at least way back to Dart 2.6 with `dart2native`:

```
Downloads dacoharkes$ ./dart-sdk/bin/dart --version
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"

Downloads dacoharkes$ ./dart-sdk/bin/dart2native ~/repro.dart

===== CRASH =====
si_signo=Bus error: 10(10), si_code=2, si_addr=0x10ba4e5c0

Failed to generate native files:
Generating AOT snapshot failed!
```

Fix: https://dart-review.googlesource.com/c/sdk/+/212570

**Comment by mraleph** [comment] 2021-09-07 12:21
Note for subsequent cherry pick review: probably not worth delaying stable release for a cherry pick.

Original reporter hits the bug due to a combination of two factors: 

- `main` which has named parameter
- flutter tool generating a redirecting main used by plugin registration system (desktop embedding specific).

Work-around for @maxisme would be to avoid named parameter in `main`, e.g.: 

```dart
Future<void> main() => mainImpl();

Future<void> mainImpl({bool integration: false}) async {
  // ...
}
```

and have integration tests `main` call `mainImpl(integration: true)` instead of calling `main`.

**Comment by dcharkes** [comment] 2021-09-07 14:52
Fix landed in Dart SDK.

@mraleph agreed. Especially, since no-one managed to hit it before in all the time it's been there. I'll not file a CP at all then.

@maxisme does the proposed workaround work for you in the meantime?

**Comment by maxisme** [comment] 2021-09-07 15:05
Ah nice! Thanks so much for looking into this so quickly! Really appreciate it! Will change my code!

**Comment by Hixie** [comment] 2021-09-07 22:59
Do I understand correctly that this issue is now resolved? Is there anything remaining to be done?

**Comment by dcharkes** [comment] 2021-09-08 07:35
As per discussion on mail, I also filed a CP to Dart stable, because we already have another CP request.

Besides waiting for a roll (`dart 2.15.0-89.0.dev`), nothing left to be done.

**Comment by Hixie** [comment] 2021-09-14 23:08
Sounds like we should close the bug then? :-)

**Comment by dcharkes** [comment] 2021-09-15 06:17
Fix has rolled into flutter engine and and into flutter framework.

https://github.com/flutter/engine/pull/28530
https://github.com/flutter/engine/commit/14521782d9624c3a99389e4ce3af92af2a3aff10

https://github.com/flutter/flutter/pull/89807
https://github.com/flutter/flutter/commit/481d5b6acd41642e27802cef0a283ad5ee688303

**Closed by dcharkes** 2021-09-15 06:17 UTC
Labels: severe: crash, waiting for PR to land (fixed), dependency: dart, passed first triage, P2
