### ISSUE TITLE
【Windows 7】Application freezes caused by gif images

### ISSUE THREAD

**Issue by ty5236305** [flutter/flutter#92571] opened 2021-10-27 12:07 UTC
## Steps to Reproduce

I found that the display of gif pictures will cause the application to freeze. Call Image.asset("images/test.gif") in the demo and wait for about 10 minutes. The application will freeze. There is this problem on window7, and no problem on windows10

After testing, flutter 2.2.0, 2.2.3, 2.5.1, 2.5.3 versions all have this problem, This is a serious problem on windows7

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Image.asset("images/test.gif")
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
```

```
flutter build windows

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] Connected device (4 available)

```

</details>

**Comment by HJ29** [comment] 2022-02-09 05:48
I encountered similar issue, app freeze after certain time.
However, there are only asset image and lottie animation instead of gif in my app, and the app last for around 5 mins then become freeze.

cpu and memory from task manager looks healthy,
there is a Timer.periodic function constantly do logging, the function still working even it is freeze,
so I guess app doesn't die, only UI freeze.

At the very beginning, I thought the root cause is in lottie animation,
after I removed the animation, the app last longer for around an hour, but freeze still happen.

It happens with Flutter 2.8, windows 7.
windows 10 doesn't have this issue.

**Comment by HJ29** [comment] 2022-02-17 07:56
for anyone following this issue
https://github.com/flutter/flutter/issues/89152#issuecomment-939240344
this windows patch worth a try,
it did solved my problem with my device, but i can't confirm it is a solution for everyone since i don't have large sample size to test this solution.
my testing environment is windows 7 64bit live in VMware.
i think it doesn't matter what cpu u are using.

Extra info,
after install [KB2670838](https://www.microsoft.com/en-us/download/details.aspx?id=36805), my app can't start properly and showing black screen.
then i have to install [.Net Framework 4.8(KB4503575)](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48)

while installing .Net4.8, i encountered other problems,
1. microsoft certificate related, solved by following [tutorial](https://www.youtube.com/watch?v=tFAk5S0Gpls)
2. timestamp signature related, solved by installing [KB4474419](https://www.catalog.update.microsoft.com/search.aspx?q=kb4474419), 
[related article](https://support.microsoft.com/en-us/topic/sha-2-code-signing-support-update-for-windows-server-2008-r2-windows-7-and-windows-server-2008-september-23-2019-84a8aad5-d8d9-2d5c-6d78-34f9aa5f8339)

**Comment by cbracken** [comment] 2024-03-29 21:08
Since we have announced the end of support for Windows 7, we are closing this issue.

**Closed by cbracken** 2024-03-29 21:08 UTC
Labels: engine, platform-windows, a: images, a: desktop, e: OS-version specific, P2, team-desktop, triaged-desktop
