### ISSUE TITLE
Crash when Process produce the error

### ISSUE THREAD

**Issue by LeXuanKhanh** [flutter/flutter#76990] opened 2021-03-01 15:47 UTC
The crash happen in release mode or build with Xcode, this can temporary fix by ignoring the signal using `signal(SIGPIPE, SIG_IGN)` in `applicationDidBecomeActive `and `applicationWillUnhide` in `AppDelegate`, but won't fix when building a release app

```swift
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
    override func applicationDidBecomeActive(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);//Ignore signal
    }
    
    override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }
    
    override func applicationWillUnhide(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);
    }
    
    override func applicationWillBecomeActive(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);
    }
}
```

Example code: Try to run some command that the Process will produce the error, for my case by executing npm -v

```dart
import 'package:flutter/material.dart';
import 'dart:io';

import 'package:pretty_json/pretty_json.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var text = '';

  void _incrementCounter() async {

    var result = await Process.run("npm",["-v"]);
    print(result.stdout);

    setState(() {
      text = result.stdout;
    });

    // var env = Platform.environment;
    // print(prettyJson(env));

    // setState(() {
    //   text = prettyJson(env);
    // });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              SelectableText(text),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

Flutter doctor -v:

```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-US)
    • Flutter version 1.26.0-12.0.pre at /Users/macbook/Developer/flutter
    • Framework revision a706cd2112 (7 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/macbook/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.7 19H2 darwin-x64

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-03-02 09:27
Hi @LeXuanKhanh 
closing as a duplicate of https://github.com/flutter/flutter/issues/76989
Follow up from https://github.com/flutter/flutter/issues/75911#issuecomment-788216117
Thank you

**Closed by TahaTesser** 2021-03-02 09:27 UTC
Labels: in triage

**Comment by LeXuanKhanh** [comment] 2021-03-03 14:21
Hi @TahaTesser, this is not related of that issue, @stuartmorgan comment only explain why the environment is different, but not give the solution or the explanation for this crash
You can make the crash not just execute some not found executable, but some random invalid command too like `abc`
I expected when this happen, the Process only throw an error and not crash my whole app

**Comment by stuartmorgan** [comment] 2021-03-03 14:33
> in release mode or build with Xcode

FYI, it would be helpful in future bug reports if you could be more precise about the way you are describing building and launching when it's relevant to the issue. "Release mode" and "with Xcode" are completely orthogonal things—you can build in release or debug modes with `flutter build`, `flutter run`, or the Xcode UI—so saying "release mode or with Xcode" doesn't really make sense.

**Comment by LeXuanKhanh** [comment] 2021-03-05 15:20
There are steps relevant to the way which I build and run
Release mode: I run the `flutter build macos` then run the .`app` file in Build/macos/Build/Product/Release folder
Run with XCode: press the Build button in XCode
Run with Android Studio: run debug with Android Studio (press Run or Debug button)
