### ISSUE TITLE
flutter create throws OS Error: Access is denied. , errno = 5 

### ISSUE THREAD

**Issue by edu-morgado** [flutter/flutter#70067] opened 2020-11-08 23:39 UTC
## Command
flutter --verbose create testing

## Problem explained
Im using Windows 10.

Some time ago I started having an issue when running flutter run on some of my projects. An Android build.gradle Exception would be thrown pointing out line 904, but not describing the error. I solved it temporarily by running flutter clean then flutter run again. Eventually the error would always come back, and eventually flutter clean wouldn't solve it anymore. 

Now, any flutter command that depends on copying files from flutter returns this OS Error: Access is denied. , errno = 5. I've tried changing the directory of flutter to several different folders, even with full control permission, still doesn't work. 
## I've tried
flutter clean flutter run (has solved build.gradle 904 some times on flutter run)
flutter pub cache repair (has solved build.gradle 904 some times after flutter clean didn't work)
changing flutter folder to outside and inside of Users folder because of some possible file permissions problems
flutter channel master -> flutter upgrade -> flutter channel stable -> flutter upgrade as well, and after reinstalling flutter

I'm out of ideas now :(

If I go inside the flutter/bin folder I can succesfully run flutter create, so it does look related to folder permission? 

## flutter create new_project

```
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'**my_project_directory**\android\app\src\main\res\mipmap-hdpi\ic_launcher.png',
path =
'**my_flutter_directory**\packages\flutter_tools\templates\app\android.tmpl\app\s
rc\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".)
```
The **crash report** for the following command is 

```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Eduardo\Documents\projects\dengue\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\Eduardo\Documents\projects\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:267:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:190:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:799:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#25     _templateImageDirectory (package:flutter_tools/src/template.dart)
#26     _rootRunUnary (dart:async/zone.dart:1198:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#34     loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart)
#35     _rootRunUnary (dart:async/zone.dart:1198:47)
#36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#43     readAnyConfigFileUri (package:package_config/src/package_config_io.dart)
#44     _rootRunUnary (dart:async/zone.dart:1198:47)
#45     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#50     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#51     _rootRun (dart:async/zone.dart:1190:13)
#52     _CustomZone.run (dart:async/zone.dart:1093:19)
#53     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter run on existing project
```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Eduardo\Documents\projects\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Eduardo\Documents\projects\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        66.5s
Exception: Gradle task assembleDebug failed with exit code 1
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.1139], locale en-US)
    • Flutter version 1.22.3 at C:\Users\Eduardo\Documents\projects\flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\Eduardo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

## flutter --verbose create 

```
[ +115 ms] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[  +79 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8874f21e79d7ec66d0457c7ab338348e31b17f1d
[   +1 ms] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git tag --points-at HEAD
[  +58 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.3
[   +8 ms] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +74 ms] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git rev-parse --abbrev-ref HEAD
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +63 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +46 ms] Creating project testing...
[ +101 ms]   testing\.gitignore (created)
[  +12 ms]   testing\.idea\libraries\Dart_SDK.xml (created)
[   +6 ms]   testing\.idea\libraries\KotlinJavaRuntime.xml (created)
[   +3 ms]   testing\.idea\modules.xml (created)
[   +2 ms]   testing\.idea\runConfigurations\main_dart.xml (created)
[   +2 ms]   testing\.idea\workspace.xml (created)
[  +13 ms]   testing\.metadata (created)
[   +2 ms]   testing\android\app\build.gradle (created)
[   +3 ms]   testing\android\app\src\main\kotlin\com\example\testing\MainActivity.kt (created)
[   +4 ms]   testing\android\build.gradle (created)
[   +5 ms]   testing\android\testing_android.iml (created)
[   +2 ms]   testing\android\.gitignore (created)
[   +3 ms]   testing\android\app\src\debug\AndroidManifest.xml (created)
[   +2 ms]   testing\android\app\src\main\AndroidManifest.xml (created)
[   +2 ms]   testing\android\app\src\main\res\drawable\launch_background.xml (created)
[   +4 ms]   testing\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
[+1007 ms] "flutter create" took 1,273ms.

[  +12 ms] Sending crash report to Google.
[ +898 ms] Crash report sent (report ID: 09ea4434a35f550f)
[   +2 ms] Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to

'C:\Users\Eduardo\Documents\projects\testing\android\app\src\main\res\mipmap-hdpi\ic_launcher.png',
           path =

'C:\Users\Eduardo\Documents\projects\flutter\packages\flutter_tools\templates\app\android.tmpl\app\s
           rc\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
           , errno = 5)".
[  +14 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +91 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +17 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +95 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +7 ms] executing: [C:\Users\Eduardo\Documents\projects\flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%ar
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 10 days ago
[  +59 ms] java -version
[  +71 ms] executing:
C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\platform-tools\adb.exe devices
-l
⣽[  +63 ms] List of devices attached
[   +4 ms] executing:
C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\platform-tools\adb.exe devices
-l
[  +33 ms] List of devices attached
⣻[  +31 ms] executing:
C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\tools\bin\sdkmanager --licenses
[+1434 ms] A crash report has been written to C:\Users\Eduardo\Documents\projects\flutter_03.log.
[        ] This crash may already be reported. Check GitHub for similar crashes.
[        ]
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+copy+file+to+%2
7C%3A%5CUsers%5CEduardo%5CDocuments%5Cprojects%5Ctesting%5Candroid%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap
-hdpi%5Cic_launcher.png%27%2C+path+%3D+%27C%3A%5CUsers%5CEduardo%5CDocuments%5Cprojects%5Cflutter%5C
packages%5Cflutter_tools%5Ctemplates%5Capp%5Candroid.tmpl%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Ci
c_launcher.png%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

[   +1 ms] To report your crash to the Flutter team, first read the guide to filing a bug.
[        ] https://flutter.dev/docs/resources/bug-reports

[        ] Create a new GitHub issue by pasting this link into your browser and completing the issue
template.
           Thank you!
[   +5 ms] Attempting git.io shortener:
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Cannot+c
opy+file+to+%27C%3A%5CUsers%5CEduardo%5CDocuments%5Cprojects%5Ctesting%5Candroid%5Capp%5Csrc%5Cmain%
5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27%2C+OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5&body=
%23%23+Command%0A%60%60%60%0Aflutter+--verbose+create+testing%0A%60%60%60%0A%0A%23%23+Steps+to+Repro
duce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+copy+file+to+%27C%3
A%5CUsers%5CEduardo%5CDocuments%5Cprojects%5Ctesting%5Candroid%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdp
i%5Cic_launcher.png%27%2C+OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%0A%60%60%60%0A%230+++++
+_File.throwIfError+%28dart%3Aio%2Ffile_impl.dart%3A635%3A7%29%0A%231++++++_File.copySync+%28dart%3A
io%2Ffile_impl.dart%3A340%3A5%29%0A%232++++++ForwardingFile.copySync+%28package%3Afile%2Fsrc%2Fforwa
rding%2Fforwarding_file.dart%3A30%3A50%29%0A%233++++++ForwardingFile.copySync+%28package%3Afile%2Fsr
c%2Fforwarding%2Fforwarding_file.dart%3A30%3A50%29%0A%234++++++Template.render.%3Canonymous+closure%
3E+%28package%3Aflutter_tools%2Fsrc%2Ftemplate.dart%3A267%3A18%29%0A%235++++++_LinkedHashMapMixin.fo
rEach+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A377%3A8%29%0A%236++++++Template.render+%28pac
kage%3Aflutter_tools%2Fsrc%2Ftemplate.dart%3A190%3A24%29%0A%237++++++CreateCommand._renderTemplate+%
28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate.dart%3A799%3A21%29%0A%238++++++_rootRunUnary+%28
dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%239++++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart
%3A1100%3A19%29%0A%2310+++++_FutureListener.handleValue+%28dart%3Aasync%2Ffuture_impl.dart%3A143%3A1
8%29%0A%2311+++++Future._propagateToListeners.handleValueCallback+%28dart%3Aasync%2Ffuture_impl.dart
%3A696%3A45%29%0A%2312+++++Future._propagateToListeners+%28dart%3Aasync%2Ffuture_impl.dart%3A725%3A3
2%29%0A%2313+++++Future._completeWithValue+%28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2314++
+++_AsyncAwaitCompleter.complete+%28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2315+++++_
completeOnAsyncReturn+%28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%2316+++++Template.fr
omName+%28package%3Aflutter_tools%2Fsrc%2Ftemplate.dart%29%0A%2317+++++_rootRunUnary+%28dart%3Aasync
%2Fzone.dart%3A1198%3A47%29%0A%2318+++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1100%3A19
%29%0A%2319+++++_FutureListener.handleValue+%28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%2320
+++++Future._propagateToListeners.handleValueCallback+%28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%
29%0A%2321+++++Future._propagateToListeners+%28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%2322
+++++Future._completeWithValue+%28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2323+++++_AsyncAwa
itCompleter.complete+%28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2324+++++_completeOnAs
yncReturn+%28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C
%93%5D+Flutter+%28Channel+stable%2C+1.22.3%2C+on+Microsoft+Windows+%5BVersion+10.0.18362.1139%5D%2C+
locale+en-US%29%0A++++%E2%80%A2+Flutter+version+1.22.3+at+C%3A%5CUsers%5CEduardo%5CDocuments%5Cproje
cts%5Cflutter%0A++++%E2%80%A2+Framework+revision+8874f21e79+%2810+days+ago%29%2C+2020-10-29+14%3A14%
3A35+-0700%0A++++%E2%80%A2+Engine+revision+a1440ca392%0A++++%E2%80%A2+Dart+version+2.10.3%0A%0A%5B%E
2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+30.0.1%29%0A++++%E
2%80%A2+Android+SDK+at+C%3A%5CUsers%5CEduardo%5CAppData%5CLocal%5CAndroid%5CSdk%5Ccmdline-tools%5Cla
test%5Cbin%0A++++%E2%80%A2+Platform+android-30%2C+build-tools+30.0.1%0A++++%E2%80%A2+ANDROID_HOME+%3
D+C%3A%5CUsers%5CEduardo%5CAppData%5CLocal%5CAndroid%5CSdk%5Ccmdline-tools%5Clatest%5Cbin%0A++++%E2%
80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2
%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+1.8.0_242-release-1644-b01%29%0D%0A++++%E2%
80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+4.0%29%0A++++%E2
%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plu
gin+version+48.1.2%0A++++%E2%80%A2+Dart+plugin+version+193.7361%0A++++%E2%80%A2+Java+version+OpenJDK
+Runtime+Environment+%28build+1.8.0_242-release-1644-b01%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28versi
on+1.51.0%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CEduardo%5CAppData%5CLocal%5CPrograms%5CMicros
oft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.16.0%0A%0A%5B%21%5D+Connected+device%0A++++%
21+No+devices+available%0A%0A%21+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutt
er+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash
[ +518 ms] https://git.io/JkJJa

[   +5 ms] ensureAnalyticsSent: 0ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

## Flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.1139], locale en-US)
    • Flutter version 1.22.3 at C:\Users\Eduardo\Documents\projects\flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\Eduardo\AppData\Local\Android\Sdk\cmdline-tools\latest\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\Eduardo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment] 2020-11-09 09:37
Hi @edu-morgado 
I see there's an open issue (https://github.com/flutter/flutter/issues/69116) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-09 09:37 UTC

**Comment by edu-morgado** [comment] 2020-11-09 10:20
I've tried both suggestions in those issues. I've put flutter inside the documents folder, and I've tried change to flutter stable, its not those! Doenst seem to be any of those problems, maybe something to do with Windows ? I also gave full permissions to both flutter folder and the project folder. 
Doens't seem the be the same thing happening than in the other issue

**Comment by pedromassangocode** [comment] 2020-11-09 12:23
Hi @edu-morgado 
We close duplicate issues (issues caused by the same reason) to better track it. Please post your feedback on the opened issue
