### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: 函数不正确。, errno = 1

### ISSUE THREAD

**Issue by QQ32920892** [flutter/flutter#102879] opened 2022-04-30 15:46 UTC
%23%23 Command
```
flutter pub get
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
FileSystemException: Cannot create link, OS Error: 函数不正确。
, errno = 1
```
%230      _Link.throwIfError (dart:io/link.dart:263:7)
%231      _Link.createSync (dart:io/link.dart:184:5)
%232      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%233      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%234      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1061:12)
%235      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:996:5)
%236      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
%237      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:359:5)
<asynchronous suspension>
%238      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
%239      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1194:27)
<asynchronous suspension>
%2310     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2311     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2312     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2313     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2314     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
%2315     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel flutter-2.13-candidate.4, 2.13.0-0.0.pre.677, on Microsoft Windows [版本 10.0.22000.613], locale zh-CN)
    • Flutter version 2.13.0-0.0.pre.677 at C:\Users\Supen Huang\sdk\flutter
    • Upstream repository https://ghproxy.com/https://github.com/flutter/flutter.git
    • Framework revision b7abece9cd (9 days ago), 2022-04-21 19:24:09 -0400
    • Engine revision 238eb9d7f5
    • Dart version 2.18.0 (build 2.18.0-42.0.dev)
    • DevTools version 2.12.2
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at c:\android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\Supen Huang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.613]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.41
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 2315431064a88027f9afaa1da71bfe304760e1b0
%23%23%23 Plugins
desktop_webview_window
file_saver-0.1.0
flutter_acrylic-1.0.0 2
path_provider-2.0.9
path_provider_android-2.0.13
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
tray_manager-0.1.4
url_launcher-6.1.0
url_launcher_android-6.0.16
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
webview_flutter-3.0.2
webview_flutter_android-2.8.6
webview_flutter_wkwebview-2.7.3
window_manager-0.2.2

**Comment by darshankawar** [comment] 2022-05-02 07:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by darshankawar** 2022-05-02 07:05 UTC
Labels: in triage
