### ISSUE TITLE
[web] - Image rendering in Stack

### ISSUE THREAD

**Issue by rlechetaudemy** [flutter/flutter#45405] opened 2019-11-22 17:31 UTC
```
`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;

    return Scaffold(
      backgroundColor: Colors.grey,
      body: Stack(
        children: <Widget>[
          Center(
            child: Image.asset(
              "assets/imgs/background.jpg",
              width: size.width,
              height: size.height,
              fit: BoxFit.fill,
            ),
          ),
          Center(
            child: Container(
              color: Colors.yellow,
              width: 100,
              height: 100,
            ),
          )
        ],
      ),
    );
  }
}`
```

<img width="1433" alt="Screen Shot 2019-11-22 at 14 24 12" src="https://user-images.githubusercontent.com/49245153/69446991-509abc80-0d34-11ea-86ff-c64382fea6c8.png">
As you can see, in the screenshot the iPhone version shows de Yellow container. But the web version never shows the contents of the screen.
This bug is happing now in the new version of Flutter. Previously it worked well.
I found this because I have this sample app that shows some background imagem in my login page:
https://carros-flutterweb.firebaseapp.com/#/
But now after upgrade Flutter the Form isn't show anymore.

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.8-pre.17, on Mac OS X 10.14.6 18G1012, locale
    en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] IntelliJ IDEA Community Edition (version 2019.1)
[✓] VS Code (version 1.40.0)
[✓] Connected device (4 available)

• No issues found!

```

**Comment by Ahmadre** [comment] 2019-11-25 00:09
Same Problem here! Since one version (maybe 1.12.*) it's not working anymore...

**Comment by rxlabz** [comment] 2019-11-27 19:35
@iapicca Probably a duplicate of #44845

**Comment by iapicca** [comment] 2019-11-27 20:03
HI @rlechetaudemy 
As @rxlabz pointed out this older [issue](https://github.com/flutter/flutter/issues/44845) 
references the same problem.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-11-27 20:03 UTC
Labels: a: images, framework, severe: regression, ☸ platform-web

**Comment by carlhung** [comment] 2019-12-22 16:29
it happens to me. New to flutter. didn't realize it is a bug on web only.

**Comment by fluttercorner** [comment] 2020-10-08 18:07
[How to set Background Image to Scaffold in Flutter](https://fluttercorner.com/how-to-set-background-image-to-scaffold-in-flutte/)
