### ISSUE TITLE
Slider label never goes away when clicking slider to new value

### ISSUE THREAD

**Issue by git-n-pissed** [flutter/flutter#123313] opened 2023-03-23 06:13 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on the slider instead of dragging it
3. Note that slider label never goes away.  Tested on Windows 10 and Android, but I only see the issue on Windows.

**Expected results:** The label should go away after some duration, preferably a configurable one.

**Actual results:** The label never goes away.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SliderApp());

class SliderApp extends StatelessWidget {
  const SliderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SliderExample(),
    );
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double _currentSliderValue = 20;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Slider')),
      body: Slider(
        value: _currentSliderValue,
        max: 100,
        divisions: 5,
        label: _currentSliderValue.round().toString(),
        onChanged: (double value) {
          setState(() {
            _currentSliderValue = value;
          });
        },
      ),
    );
  }
}
```

</details>

**Comment by danagbemava-nc** [comment] 2023-03-23 09:48
Reproduces using the code sample provided above. The label does disappear when you drag it but not when you click on the values. This is a desktop-only issue. 

<details>
<summary>recording</summary>

| mobile | desktop |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/227163755-df6f6728-6ff2-4b96-a818-c957901ccc31.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/227163773-f3b2b13e-5ece-47ae-babb-3137c2ea35f8.mov" /> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.8 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (2 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E                        • ios            • iOS 16.3.1 20D67
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-15.0.pre.20, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-15.0.pre.20 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2bb7b9bc4c (4 hours ago), 2023-03-23 02:04:21 -0400
    • Engine revision 10ade9e22d
    • Dart version 3.0.0 (build 3.0.0-356.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E                        • ios            • iOS 16.3.1 20D67
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 111.0.5563.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

``` 

</details>

**Comment by werainkhatri** [comment] 2023-04-09 13:54
> The label should go away after some duration, preferably a configurable one.

there is a timer, although not configurable. the issue comes up because currently when the timer ends, the slider needs to be unfocused for the value indicator to go away.

https://github.com/flutter/flutter/blob/c55d713ca88587f36c1ba279ad0a577b300446c7/packages/flutter/lib/src/material/slider.dart#L1439-L1441

<details>
<summary>if the `!hasFocus` condition is removed</summary>

https://user-images.githubusercontent.com/44755140/230776709-ab6cf008-908d-4bfe-b9e1-9d17161a6410.mov

</details>

**Comment by rydmike** [comment] 2023-04-21 19:33
It is also worth noting that the `RangeSlider` does not behave this way on desktop. Regardless of what is considered correct behavior, they should at least be the same. If the current `ValueIndicator` behavior on `Slider` when it is focused is considered correct, perhaps it should be configurable for use cases where this behavior is not desired.


@TahaTesser I'm guessing this issue is on your list too. I mentioned this difference in behavior between `Slider` and `RangeSlider` in passing in our issues discussion today.

**Comment by cruiser-baxter** [comment] 2023-05-01 22:02
Hello, I am working with technical mentors on a school project and would like to work on this bug. How can I get this assigned to myself to show that I am working on it? Thank you.

**Comment by hgraceb** [comment] 2023-05-03 10:55
It seems that nobody mentioned the `overlay`. I think the correct behavior should be taking both the `label` and the `overlay` away together.

**Comment by TahaTesser** [comment] 2023-05-03 12:42
> Hello, I am working with technical mentors on a school project and would like to work on this bug. How can I get this assigned to myself to show that I am working on it? Thank you.

Hi, I recommend taking a look at another issue. This will be fixed part as part of a bigger project under https://github.com/flutter/flutter/issues/125329

**Comment by hgraceb** [comment] 2023-05-03 12:46
I found that this line of code seems to be causing the issue: [_focusNode?.requestFocus();](https://github.com/flutter/flutter/commit/400136b007109c1fbe1ae18cc909bc7bab5abac0#diff-5e2997b459a10c94cefa730318781868c65514e25fcc8a304bb5d9ee1e5196cbR612).

```dart
void _handleChanged(double value) {
  assert(widget.onChanged != null);
  final double lerpValue = _lerp(value);
  if (lerpValue != widget.value) {
    widget.onChanged!(lerpValue);
    // _focusNode?.requestFocus();
  }
}
```

After removing this line of code, everything is running perfectly fine for me.

**Comment by cruiser-baxter** [comment] 2023-05-09 19:46
This bug no longer reproduces for me after the following PR was merged.
PR - https://github.com/flutter/flutter/commit/293715a6a40fd1e479c64ea082a4263c825661d4 
Commit - https://github.com/flutter/flutter/commit/293715a6a40fd1e479c64ea082a4263c825661d4
The PR did not specifically list bug #123313 as being fixed because it was not directly addressed and therefore the bug is still open. I looks like the overhaul of the slider customizability, eliminated the bug altogether. I think this bug should probably just be closed.

**Comment by TahaTesser** [comment] 2023-05-10 07:21
@cruiser-baxter 
Thanks for the details, based on your comment, I feel safe to close this

**Comment by hgraceb** [comment] 2023-05-10 11:56
> @cruiser-baxter Thanks for the details, based on your comment, I feel safe to close this

I tested with the latest master code 8ab782d08a2e0111a96dc3ebb0fbfe8b08757b24, but the issue still persists. 

As I mentioned [before](https://github.com/flutter/flutter/issues/123313#issuecomment-1532970016), not only the `label` is not properly hidden, but there are also problems with the display of the `overlay`. 

I really hope that everyone can be more careful when testing and closing issues.

![slider](https://github.com/flutter/flutter/assets/38378650/cf281c65-21d5-4510-bccc-107ef76e6e40)

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-2.0.pre.83, on Microsoft Windows [版本 10.0.19044.2846], locale zh-CN)
    • Flutter version 3.11.0-2.0.pre.83 on channel master at D:\Temporary\flutter\_flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8ab782d08a (11 hours ago), 2023-05-09 17:50:11 -0700
    • Engine revision 8ca16cba8c
    • Dart version 3.1.0 (build 3.1.0-89.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Flop\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\Flop\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9862592\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\Flop\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9862592
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4560
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.76.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19044.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2023-05-10 12:02
I just tested it myself, and it reproduces.

**Comment by cruiser-baxter** [comment] 2023-05-10 18:44
Apologies everyone. The bug indeed is still reproduces. It completely slipped my mind and I tested on Android instead of desktop platform where the bug reproduces. Total rookie mistake. I will be more careful next time.

**Closed** 2023-06-14 17:11 UTC
Labels: framework, f: material design, a: desktop, has reproducible steps, P4, found in release: 3.7, found in release: 3.9
