### ISSUE TITLE
Single Responsibility Principle When Using State Widgets

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#32855] opened 2019-05-16 23:57 UTC
Here is a simple example of Widget which is using state. 

```
class IncrementCounterState extends State<IncrementCounter> {
  
  @override 
  Widget build(BuildContext context) {
    return Text('Hello Counter');
  }

}

class IncrementCounter extends StatefulWidget {

  @override 
  IncrementCounterState createState() => IncrementCounterState();
  
}
```

In the above code the build function is inside the IncrementCounterState instead of IncrementCounter. It feels like the build should be inside IncrementCounter since IncrementCounterState is responsible for maintaining the state of the widget. 

Actually in the future it would be nice if we don't have to create two widgets for maintaining states. Just extends StatefulWidget and the widget will have the features for maintaining state. 

Thoughts?

**Comment by jonahwilliams** [comment] 2019-05-17 00:29
See https://github.com/flutter/flutter/issues/13938 for an extended discussion of this point.

Duplicate of https://github.com/flutter/flutter/issues/13938

**Closed by jonahwilliams** 2019-05-17 00:29 UTC
