### ISSUE TITLE
[web] RequireJS is not defined in release mode

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#56659] opened 2020-05-08 10:02 UTC
RequireJS is available when the web app is run in debug mode but not present in release mode.

The framework uses RequireJS extensively for its own purposes. But if it's already there, I would like to use it myself, too, to load my JS libraries. It seems that while this is possible in debug mode, something prevents me from using requirejs() in release mode.

## Steps to Reproduce

1. Create a Flutter Web app
2. Use RequireJS to load any library
3. Run it in both debug and release

**Expected results:**

Functioning app, using requirejs.

**Actual results:**

"requirejs is not defined" error in Chrome Dev Tools console.

```
[√] Flutter (Channel beta, v1.17.0-3.4.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.17.0-3.4.pre at E:\Android\flutter-beta
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at e:\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by TahaTesser** [comment] 2020-05-08 11:59
Hi @deakjahn 
Please take a look this [comment](https://github.com/flutter/flutter/issues/38797#issuecomment-522945924)

can you please provide your `flutter run -d Chrome --release  --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by deakjahn** [comment] 2020-05-08 13:18
More likely than not falling off the tree while shaken but it would be very good to be able to specify with a trick that I need to use it. If it's already in the framework, it would be a pity to have to include a second copy separately.

[requirejs_repro.zip](https://github.com/flutter/flutter/files/4599137/requirejs_repro.zip)
[verbose.log](https://github.com/flutter/flutter/files/4599138/verbose.log)
![Annotation 2020-05-08 150859](https://user-images.githubusercontent.com/2234271/81409289-2486c280-913f-11ea-9d4f-f1fb05d149e9.png)

**Comment by jonahwilliams** [comment] 2020-05-14 22:18
The fact that requireJS is loaded for dartdevc module loading is an implementation detail. We'll likely remove it in a future release and replace it with a faster module loader.

**Comment by deakjahn** [comment] 2020-05-14 23:53
And do you already have a candidate? I'd be glad to try it in my plugin. :-)

Anyway, this probably means even in the long run that this isn't a feature we can rely on, it's Bring Your Own Food.

**Comment by ditman** [comment] 2020-05-15 01:01
AFAIK this is the tracking issue: https://github.com/dart-lang/sdk/issues/33979, I'm going to close this one as a duplicate of the one in dart-lang/sdk. Feel free to reopen if needed!

**Closed by ditman** 2020-05-15 01:01 UTC
Labels: a: release, dependency: dart, platform-web, severe: new feature
