### ISSUE TITLE
font weights are not rendered properly on iOS 13.3

### ISSUE THREAD

**Issue by tsahnar** [flutter/flutter#60477] opened 2020-06-28 17:41 UTC
Hi!  when running our app in iPhoneX simulator - iOS version 13.5 everything works good.

In iPhone X  simulator with version **iOS 13.3**, all text with fontWeight 300 (and other weights which are not "normal") do not render properly - see photos attached. (you can see that letter spacing is not even) The fonts we are using is "Helvetica neue".

this is how we define the fonts in the pubspec.yml file:

```yaml
- family: Halvetica
  fonts:
    - asset: fonts/Helvetica45Light.ttf
    - asset: fonts/Helvetica25UltraLight.ttf
      weight: 100
    - asset: fonts/Helvetica35Thin.ttf
      weight: 300
    - asset: fonts/Helvetica55Roman.ttf
      weight: 500
    - asset: fonts/Helvetica65Medium.ttf
      weight: 600
    - asset: fonts/Helvetica85Heavy.ttf
      weight: 700
```

This is how the font family is set:
`var baseTextStyle = TextStyle(fontFamily: "Halvetica", color: AppColors.black);`

I have a config where I create a custom theme:
```dart
class AppTheme {
 static ThemeData of(context) {
   var theme = Theme.of(context);
   return theme.copyWith(...); // Here I override the default theme
 }
}
```

output from flutter doctor:

```console
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E266, locale en-IL)
    • Flutter version 1.17.3 at /Users/XXX/Desktop/Dev/tools/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

 
[✓] Connected device (3 available)            
    • sdk gphone x86 arm • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 8           • 1EAA0FC8-F445-4D6C-9030-E6E9BB21924B • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone x           • 8E1A08DD-905F-4BD2-9BAE-01702A4007C4 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

<img width="655" alt="iOS 13 3" src="https://user-images.githubusercontent.com/24475519/85954328-54a05400-b97f-11ea-89ad-3f20ccd46fc4.png">
<img width="301" alt="iOS 13 5" src="https://user-images.githubusercontent.com/24475519/85954331-566a1780-b97f-11ea-8f55-5f72b60651ac.png">

**Comment by iapicca** [comment] 2020-06-29 12:33
Hi @tsahnar 
I'm not sure if the issue is referred to [ios ignoring fontWeight](https://github.com/flutter/flutter/issues/49492) or these fonts specifically;
does this [code sample](https://gist.github.com/iapicca/e3caef057ba613e390edeaafcc720552) represent the issue you are describing?
Thank you

**Comment by tsahnar** [comment] 2020-06-29 13:11
@iapicca thanks for you response
The issue you referenced in your comment is not really like the issue we encounter.
I tried the code sample you sent- with the Google font it worked fine. When I tried the Helvetica font it does not render properly on both w100 and w300. only in "normal"... see attached images. 
![normal](https://user-images.githubusercontent.com/24475519/86009570-0cd30880-ba23-11ea-92f9-19e2d4d1eab4.png)
![w300](https://user-images.githubusercontent.com/24475519/86009576-0e043580-ba23-11ea-8ff7-d8dc8e75dd19.png)

Could this be just the font we are using is not working properly?

**Comment by TahaTesser** [comment] 2020-10-22 14:54
Hi @tsahnar  
Running on iOS 13.3 simulator, using Helvita has no issues

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData(fontFamily: 'Helvetica'),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(
            'Hello World',
            style: TextStyle(fontWeight: FontWeight.w100, fontSize: 49),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

![Simulator Screen Shot - iPhone 8 - 2020-10-22 at 20 22 33](https://user-images.githubusercontent.com/48603081/96889705-7ed4cf00-14a4-11eb-88fb-6b86ead9a791.png)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.111, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-2.0.pre.111 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision fe189baf34 (11 hours ago), 2020-10-21 22:25:53 -0400
    • Engine revision f459a86610
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)     • 722C6A4C-3FCA-4FC6-9D30-9702A0E784B8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details> 



I cannot reproduce this issue on the latest `master` channel.
Can you please upgrade to the latest  `dev` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment] 2020-11-13 11:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-13 11:59 UTC
Labels: a: typography, e: OS Version specific, engine, platform-ios
