### ISSUE TITLE
Would like support for asset directories or globbing

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#7019] opened 2016-11-26 01:58 UTC
flutter.yaml's assets support is a convenient way to add assets for both platforms.  Unclear if we want to keep it long term, but if we do it would be nice to add support for directories and/or file globbing.  Right now I'm in the process of writing a script to update my flutter.yaml when my directory of images change. :/

**Comment by eseidelGoogle** [comment] 2016-11-30 19:44
The hardest part might be implementing the "needsBuild" function, but adding globbing to AssetBundle is probably straightforward?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/asset.dart#L94

**Comment by Hixie** [comment] 2018-04-24 23:33
Duplicate of #4890.

**Closed by Hixie** 2018-04-24 23:33 UTC
