### ISSUE TITLE
[iOS]App is suspended

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#72638] opened 2020-12-19 06:54 UTC
On the iOS platform, when the user pulls down the notification center or switches to the multitasking window, the current application should be active (for example, the video will continue to play, and the animation will continue to play), but the Flutter application will be paused in these scenarios. Will be activated again when returning to the app

**Comment by TahaTesser** [comment] 2020-12-21 09:55
Hi @rs5173 
I think you're referring, the app is paused when opening the control center, and the theme doesn't update for example https://github.com/flutter/flutter/issues/43806
Also, this is a duplicate of https://github.com/flutter/flutter/issues/71051
Closing If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-21 09:55 UTC
