### ISSUE TITLE
GPU specific Scene.toImage and Picture.toImage

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#40990] opened 2019-09-20 19:33 UTC
Currently **Scene.toImage()** and **Picture.toImage()** return the image asynchronously through 'makeSnapshot'. Ideally, these would call a GPU specific version of 'makeSnapshot' and return the result synchronously so the result can be used in further drawing on the same frame.

This opens up the door for numerous effects, but can also be incorporated into 'paintImage' in conjunction with ImageShader to help speed up image tiling which currently issues a draw command for each tile.

See here for more information:
[https://github.com/flutter/engine/pull/8835#issuecomment-504135038](https://github.com/flutter/engine/pull/8835#issuecomment-504135038)

cc @Hixie @liyuqian @reed-at-google

**Comment by dnfield** [comment] 2022-03-31 16:49
Duplicate of https://github.com/flutter/flutter/issues/13498

**Comment by dnfield** [comment] 2022-06-01 04:36
I'm going to re-open this to track adding Scene.toGpuImage.

**Comment by dnfield** [comment] 2022-06-01 04:37
The linked patch above also is delaying an implementatino of ImageShader using this style of image... at least for now.

**Comment by fzyzcjy** [comment] 2022-06-25 12:58
Btw shall this be closed via https://github.com/flutter/engine/pull/33736?

**Comment by cmkweber** [comment] 2022-06-25 14:09
I believe so. Although the app I was hoping to utilize this for has long since been abandoned (along with the use case) - I do plan to create a small test using master to verify. Great work @dnfield

**Closed** 2022-06-25 14:15 UTC
Labels: engine, a: images, passed first triage, P4
