### ISSUE TITLE
[flutter_webview] I use the webview library, call js to execute localStorage, it is normal on android, and an error occurs on IOS

### ISSUE THREAD

**Issue by somta** [flutter/flutter#70451] opened 2020-11-13 09:47 UTC
I use the webview library, call js to execute localStorage, execute the following code, it can be used normally on android, and the following error occurs when running on ios：

`await controller.evaluateJavascript('window.localStorage.setItem("X-Token", "$token");')`

Exception has occurred.
PlatformException (PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'localStorage["X-Token"] = "897dcc65f569425bf4f7800ceb10a9dd";'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=SecurityError: The operation is insecure., WKJavaScriptExceptionColumnNumber=13, NSLocalizedDescription=A JavaScript exception occurred}, null))

**Comment by pedromassangocode** [comment] 2020-11-13 10:54
Hi @somta 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by sidrao2006** [comment] 2020-11-13 11:07
Hey @somta , this looks like a problem with iOS itself.

According to [this stackoverflow answer](https://stackoverflow.com/q/47832273/11626847), you  have to load local storage after the webview has finished loading.

**Comment by pedromassangocode** [comment] 2020-12-04 09:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-04 09:28 UTC
Labels: in triage, waiting for customer response
