### ISSUE TITLE
No hot reloading on saving a file when running flutter run in a terminal

### ISSUE THREAD

**Issue by mustaqimM** [flutter/flutter#138678] opened 2023-11-19 03:08 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run `flutter run` in a terminal
2. In another window, open `./lib/main.dart` in a text editor
3. Make and save a hot-reload related change

### Expected results

A saved change in `main.dart` should be reflected by initiating a hot reload. This works correctly if I press the "Play" button in vscode and Android Studio, but incorrectly when directly running `flutter run` in a terminal. It occurs for all devices.

### Actual results

I have to manually send `r` in the terminal I'm running `flutter run` to hot reload the application

### Code sample

<details><summary>Code sample</summary>

It's the default project created with `flutter create test_app` 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
$ flutter run                                                                × 1
Launching lib/main.dart on SM G925F in debug mode...
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
 -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
 -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Running Gradle task 'assembleDebug'...                             10.7s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...           4.7s
Syncing files to device SM G925F...                                 97ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on SM G925F is available at:
http://127.0.0.1:44563/NnnW7zkYt8g=/
The Flutter DevTools debugger and profiler on SM G925F is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:44563/NnnW7zkYt8g=/
I/Gralloc4(14836): mapper 4.x is not supported
W/Gralloc3(14836): mapper 3.x is not supported
W/Gralloc4(14836): allocator 4.x is not supported
W/Gralloc3(14836): allocator 3.x is not supported
I/Gralloc2(14836): Adding additional valid usage bits: 0x0
E/ion     (14836): ioctl c0044901 failed with code -1: Invalid argument

Performing hot reload...
Reloaded 1 of 697 libraries in 1,006ms (compile: 49 ms, reload: 321 ms,
reassemble: 342 ms).
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 23.10 6.5.0-10-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/mustaqim/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/mustaqim/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/mustaqim/Library/android/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/mustaqim/Library/android/android-studio
    • Flutter plugin version 76.3.1
    • Dart plugin version 222.4582
    • Java version  -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.76.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • SM G925F (mobile) • 06157df664c31326 • android-arm64  • Android 12 (API 32)
    • Linux (desktop)   • linux            • linux-x64      • Ubuntu 23.10 6.5.0-10-generic
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-20 07:12
Closing this as a duplicate of https://github.com/flutter/flutter/issues/136494

**Closed by danagbemava-nc** 2023-11-20 07:12 UTC
Labels: in triage
