### ISSUE TITLE
Strange Flutter app behavior and appearance after upgrade to v1.7.8-hotfixes

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#35943] opened 2019-07-10 23:41 UTC
I have an app made with Flutter and everything works fine. Today I upgrade my Flutter SDK to `v1.7.8-hotfixes` so that I can take the advantage to build 64bit version of it to publish on Play Store.

After the Flutter upgrate I run my app to assert that everything is working fine, but somehow I noticed some strange behavior in some part of the app:

 - My Text view become too big
 - My List of content get refreshed everytime

All the pages of my app get refreshed at least three/four times after the upgrade, I'm able to see that because the images of my items get reloaded.

**Note:** I did not changed anything, I just upgrade Flutter. Check bellow the appearance of the Text size before and after the upgrade:

**Before the upgrade**

[![Before the upgrade][1]][1]

**And here is the aprearance that it takes after the upgrade**

[![enter image description here][2]][2]

But the code still the same:

    Text(
            item.title,
            style: TextStyle(
                color: isSelected ? Colors.deepOrange: Colors.white,
                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal),
          )

The new version can cause problems for apps already published, because of these changes. Maybe you want to test all the use-case of your app, after the upgrade.

I needed to go back to the previous version `v1.5.4-hotfixes` to cotinue the development cycle, I hope the Flutter team notice that and solve it.

StackOverflow question: https://stackoverflow.com/questions/56979890/strange-flutter-app-behavior-and-appearance-after-upgrade-to-v1-7-8-hotfixes

  [1]: https://i.stack.imgur.com/A7C6f.png
  [2]: https://i.stack.imgur.com/p2QFI.png

**Comment by FullstackJack** [comment] 2019-07-11 00:49
I believe this is meant to be an improvement. This should be closed as "by design."

Announcement
https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf

Merged cupertino fixes
https://github.com/flutter/flutter/pull/31464

**Comment by LongCatIsLooong** [comment] 2019-07-11 01:34
As @FullstackJack pointed out, the text style change seems expected. If you're using `CupertinoPicker` and don't like the font size, override it in the `Text`'s `TextStyle`. 

Without a minimal example to reproduce the refresh problem, it would be difficult for us to investigate. I'm going to close the issue. Feel free to reopen it (or create a new one) if the workaround doesn't work for you, or you'd like to provide further information on the list refresh problem.

**Closed by LongCatIsLooong** 2019-07-11 01:34 UTC
