### ISSUE TITLE
List of Image show glitch when user scroll it.

### ISSUE THREAD

**Issue by hndrbrm** [flutter/flutter#88521] opened 2021-08-19 12:00 UTC
## Steps to Reproduce
<details>
  <summary>Copy this code to main.dart</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ScrollConfiguration(
          behavior: ScrollConfiguration.of(context).copyWith(
            dragDevices: {
              PointerDeviceKind.touch,
              PointerDeviceKind.mouse,
            }
          ),
          child: ListView.builder(
            itemCount: 100,
            itemBuilder: (BuildContext context, int index) {
              return Image.network(
                'https://dummyimage.com/600x399/000000/0000ff.png&text=index$index',
                fit: BoxFit.fitWidth,
              );
            },
          ),
        ),
      ),
    );
  }
}
```
</details>  

**Expected results:**
No Glitch.

**Actual results:**
Show Glitch.

Tested on macOS (glitched), android (glitched), web (no glitch).
In  macOS, resizing the window size sometime eliminate the glitch.
In android, resizing the image size sometime eliminate the glitch.

<details>
  <summary>flutter doctor -v</summary>

```zsh
[✓] Flutter (Channel dev, 2.5.0-1.0.pre, on macOS 11.4 20F71 darwin-x64, locale
    en-TL)
    • Flutter version 2.5.0-1.0.pre at /Users/anta/Mine/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 184e5871be (3 weeks ago), 2021-07-26 04:38:02 -0400
    • Engine revision a877f6fed6
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc4)
    • Android SDK at /Users/anta/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google
      Chrome.app/Contents/MacOS/google-chrome-unsafe

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 191.8593

[✓] Connected device (3 available)
    • H3223 (mobile)  • CQ3001CLTG • android-arm64  • Android 9 (API 28)
    • macOS (desktop) • macos      • darwin-x64     • macOS 11.4 20F71
      darwin-x64
    • Chrome (web)    • chrome     • web-javascript • Google Chrome
```
</details>

<details>
  <summary>Video Record on macOS (Glitched)</summary>

https://user-images.githubusercontent.com/86121106/130063760-e361297e-67c6-4386-a72d-7f9cf4016195.mp4

</details>

<details>
  <summary>Video Record on Android Device (Glitched)</summary>

https://user-images.githubusercontent.com/86121106/130064189-d56eda33-f919-4532-85c8-968108b6afd3.mp4

</details>

<details>
  <summary>Video Record on Web (No Glitch)</summary>

https://user-images.githubusercontent.com/86121106/130064485-7c661ae9-21fc-4275-ad57-958dc80c10aa.mp4

</details>

Real world application troubled by this minor glitch is Comic-Like application, like WebToon.

**Comment by maheshmnj** [comment] 2021-08-19 15:55
Hi @hndrbrm, I am able to reproduce the issue on the latest stable and the master channel  looks like this is specific to this image asset and does not reproduce with other image assets whether local or network

<details>
<summary>Output</summary>

### MacOS
https://user-images.githubusercontent.com/31410839/130100812-b18a4c76-b917-4c47-b81f-79ee0f74a37c.mov
### Web
https://user-images.githubusercontent.com/31410839/130100854-b0479eab-0c33-421f-801c-b89e154780b7.mov
### Android
https://user-images.githubusercontent.com/31410839/130100999-1aa55ff5-f929-46ba-8fb2-5772ea6b0161.mov
### IOS
https://user-images.githubusercontent.com/31410839/130100975-c23409a6-cae7-499b-8298-835afe8bb03a.mov

</details>

|  `Android`  | `IOS` | `MacOs` | `Web` |
| :---: |:---: |:---: |:---: |
|  ❌  |   ❌   | ❌   |  ✅  | 

✅ : No Issue ❌: Issue reproduced 


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.8, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.8 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (7 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```
</details>

**Comment by nt4f04uNd** [comment] 2021-08-19 16:20
Looks like a duplicate of https://github.com/flutter/flutter/issues/37578

**Comment by goderbauer** [comment] 2022-04-06 21:51
This looks like anti-aliasing at work.

For more details, see #14288

**Closed by goderbauer** 2022-04-06 21:51 UTC
Labels: framework, f: scrolling, severe: rendering, has reproducible steps, found in release: 2.2, found in release: 2.5
