### ISSUE TITLE
webview_flutter how to load https and http mixed content?

### ISSUE THREAD

**Issue by iusn** [flutter/flutter#111062] opened 2022-09-07 03:14 UTC
<details>
<summary>flutter doctor -v</summary>

```dart
Flutter (Channel stable, 3.0.2, on macOS 12.3 21E230 darwin-arm, locale
    en-CN)
    • Flutter version 3.0.2 at /Users/XX/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
```
</details>

Flutter plugin:
webview_flutter: 3.0.4

issue:
"Mixed Content: The page at 'xxxxxxx' was loaded over HTTPS, but requested an insecure image 'http://xxx.com/xxx_image.png'. This request has been blocked; the content must be served over HTTPS.", source: https://xxxxx.com

how to solved this problem?

I have find this issue, but don't have the file 

https://github.com/flutter/flutter/issues/43595

**Comment by iusn** [comment] 2022-09-07 03:22
the webview_flutter example can see this issue,
initialUrl use https web url,

http image url  insert that web

**Comment by danagbemava-nc** [comment] 2022-09-07 08:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/43595.

Kindly follow up in the linked issue for updates.

**Closed by danagbemava-nc** 2022-09-07 08:14 UTC
Labels: in triage
