### ISSUE TITLE
Flutter getting errors on simple thing. _network_image_io

### ISSUE THREAD

**Issue by Mubassir-developer** [flutter/flutter#66563] opened 2020-09-24 15:44 UTC
My Application was working fine. suddenly start displaying errors on flutter run
**flutter run output:** 
<details>
Launching lib\main.dart on SM J200F in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:132:18: Error: 'Widget' isn't a type.

      final List<Widget> imageSliders = imgList

                 ^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:139:36: Error: 'Widget' isn't a type.

                        children: <Widget>[

                                   ^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:132:41: Error: The getter 'imgList' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'imgList'.

      final List<Widget> imageSliders = imgList

                                        ^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:133:26: Error: The method 'Container' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Container'.

          .map((item) => Container(

                         ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:134:24: Error: The method 'Container' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Container'.

                child: Container(

                       ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:135:27: Error: The getter 'EdgeInsets' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'EdgeInsets'.

                  margin: EdgeInsets.all(5.0),

                          ^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:136:26: Error: The method 'ClipRRect' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'ClipRRect'.

                  child: ClipRRect(

                         ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:137:37: Error: The getter 'BorderRadius' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'BorderRadius'.

                      borderRadius: BorderRadius.all(Radius.circular(5.0)),

                                    ^^^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:137:54: Error: The getter 'Radius' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Radius'.

                      borderRadius: BorderRadius.all(Radius.circular(5.0)),

                                                     ^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:138:30: Error: The method 'Stack' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Stack'.

                      child: Stack(

                             ^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:140:27: Error: The getter 'Image' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Image'.

                          Image.network(item, fit: BoxFit.cover, width: 1000.0),

                          ^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:140:52: Error: The getter 'BoxFit' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'BoxFit'.

                          Image.network(item, fit: BoxFit.cover, width: 1000.0),

                                                   ^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:141:27: Error: The method 'Positioned' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Positioned'.

                          Positioned(

                          ^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:145:36: Error: The method 'Container' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Container'.

                            child: Container(

                                   ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:146:43: Error: The method 'BoxDecoration' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'BoxDecoration'.

                              decoration: BoxDecoration(

                                          ^^^^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:147:43: Error: The method 'LinearGradient' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'LinearGradient'.

                                gradient: LinearGradient(

                                          ^^^^^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:149:37: Error: The getter 'Color' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Color'.

                                    Color.fromARGB(200, 0, 0, 0),

                                    ^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:150:37: Error: The getter 'Color' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Color'.

                                    Color.fromARGB(0, 0, 0, 0)

                                    ^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:152:42: Error: The getter 'Alignment' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Alignment'.

                                  begin: Alignment.bottomCenter,

                                         ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:153:40: Error: The getter 'Alignment' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Alignment'.

                                  end: Alignment.topCenter,

                                       ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:156:40: Error: The getter 'EdgeInsets' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'EdgeInsets'.

                              padding: EdgeInsets.symmetric(

                                       ^^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:158:38: Error: The method 'Text' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'Text'.

                              child: Text(

                                     ^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:159:40: Error: The getter 'imgList' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'imgList'.

                                'No. ${imgList.indexOf(item)} image',

                                       ^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:160:40: Error: The method 'TextStyle' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.

                                style: TextStyle(

                                       ^^^^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:161:42: Error: The getter 'Colors' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.

                                  color: Colors.white,

                                         ^^^^^^

/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:163:47: Error: The getter 'FontWeight' isn't defined for the class 'NetworkImage'.

 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'FontWeight'.

                                  fontWeight: FontWeight.bold,

                                              ^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:

Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Running Gradle task 'assembleDebug'...                             26.9s
Exception: Gradle task assembleDebug failed with exit code 1
</details>

**fluter doctor -v Output**
<details>
$ flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-PK)
    • Flutter version 1.20.4 at C:\src\flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\KoderLabs\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\KoderLabs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • SM J200F (mobile) • 4200025fec46a3d9 • android-arm • Android 5.1.1 (API 22)

• No issues found!
</details>

**Comment by thanishkumar** [comment] 2020-09-24 17:12
same for me

**Comment by darshankawar** [comment] 2020-09-25 06:12
Hi @Mubassir-developer 
Can you try `flutter clean` and then `flutter run` to see if it works ?
If problem persists, please provide a minimal complete code sample that shows the issue.
Thanks.

**Comment by Mubassir-developer** [comment] 2020-09-25 13:43
Hey @darshankawar Sir just created a new flutter project and run the code, It's the same as before
Output:
<derails>
$ flutter run
Launching lib\main.dart on SM J200F in debug mode...
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:132:18: Error: 'Widget' isn't a type.
      final List<Widget> imageSliders = imgList
                 ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:139:36: Error: 'Widget' isn't a type.
                        children: <Widget>[
                                   ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:132:41: Error: The getter 'imgList' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'imgList'.
      final List<Widget> imageSliders = imgList                         
                                        ^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:133:26: Error: The method 'Container' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
          .map((item) => Container(
                         ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:134:24: Error: The method 'Container' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
                child: Container(
                       ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:135:27: Error: The getter 'EdgeInsets' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'EdgeInsets'.
                  margin: EdgeInsets.all(5.0),
                          ^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:136:26: Error: The method 'ClipRRect' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ClipRRect'.
                  child: ClipRRect(
                         ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:137:37: Error: The getter 'BorderRadius' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'BorderRadius'.
                      borderRadius: BorderRadius.all(Radius.circular(5.0)),
                                    ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:137:54: Error: The getter 'Radius' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Radius'.
                      borderRadius: BorderRadius.all(Radius.circular(5.0)),
                                                     ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:138:30: Error: The method 'Stack' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Stack'.
                      child: Stack(
                             ^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:140:27: Error: The getter 'Image' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Image'.
                          Image.network(item, fit: BoxFit.cover, width: 1000.0),
                          ^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:140:52: Error: The getter 'BoxFit' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'BoxFit'.
                          Image.network(item, fit: BoxFit.cover, width: 1000.0),
                                                   ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:141:27: Error: The method 'Positioned' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Positioned'.
                          Positioned(
                          ^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:145:36: Error: The method 'Container' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
                            child: Container(
                                   ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:146:43: Error: The method 'BoxDecoration' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BoxDecoration'.
                              decoration: BoxDecoration(
                                          ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:147:43: Error: The method 'LinearGradient' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'LinearGradient'.
                                gradient: LinearGradient(
                                          ^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:149:37: Error: The getter 'Color' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Color'.
                                    Color.fromARGB(200, 0, 0, 0),
                                    ^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:150:37: Error: The getter 'Color' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Color'.
                                    Color.fromARGB(0, 0, 0, 0)
                                    ^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:152:42: Error: The getter 'Alignment' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Alignment'.
                                  begin: Alignment.bottomCenter,
                                         ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:153:40: Error: The getter 'Alignment' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Alignment'.
                                  end: Alignment.topCenter,
                                       ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:156:40: Error: The getter 'EdgeInsets' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'EdgeInsets'.
                              padding: EdgeInsets.symmetric(
                                       ^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:158:38: Error: The method 'Text' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
                              child: Text(
                                     ^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:159:40: Error: The getter 'imgList' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'imgList'.
                                'No. ${imgList.indexOf(item)} image',   
                                       ^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:160:40: Error: The method 'TextStyle' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.
                                style: TextStyle(
                                       ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:161:42: Error: The getter 'Colors' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
                                  color: Colors.white,
                                         ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart:163:47: Error: The getter 'FontWeight' isn't defined for the class 'NetworkImage'.
 - 'NetworkImage' is from 'package:flutter/src/painting/_network_image_io.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/_network_image_io.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FontWeight'.
                                  fontWeight: FontWeight.bold,
                                              ^^^^^^^^^^
                                                                        
                                                                        
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        39.5s
Exception: Gradle task assembleDebug failed with exit code 1
</details>

**Comment by Mubassir-developer** [comment] 2020-09-25 13:50
Is there is any possibility that any package can break the flutter SDK file?
The last thing I was doing was testing the package [carousel_slider 2.2.1](https://pub.dev/packages/carousel_slider), After several changes and practice suddenly these errors start occurring :(

**Comment by darshankawar** [comment] 2020-09-28 06:19
@Mubassir-developer 
The plugin you mentioned is a 3rd party plugin and looking at the logs you sent, it seems to be an implementation issue and not related to Flutter.
Anyways, please provide a minimal complete reproducible code sample that shows the issue along with `pubspec.yaml`.
Thanks.

**Comment by pedromassangocode** [comment] 2020-10-21 13:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-21 13:16 UTC
Labels: in triage, waiting for customer response
