### ISSUE TITLE
[go_router] sub-route is built before parent route when mixing builder and pageBuilder

### ISSUE THREAD

**Issue by DamienMrtl** [flutter/flutter#126785] opened 2023-05-14 20:31 UTC
Using Flutter 3.10.0 and go_router 7.0.1

### Steps to reproduce

1. Create a parent route using "builder"
2. Create a sub route using "pageBuilder"
3. Access subRoute

### Expected results

Parent routes should be built before their children.

### Actual results

The sub-route gets built before his parent.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final GoRouter router = GoRouter(
    debugLogDiagnostics: true,
    initialLocation: "/page1/sub",
    routes: [
      GoRoute(path: '/', redirect: (ctx, state) => "/page1"),
      GoRoute(
        path: '/page1',
        name: 'page1',
        // redirect: (ctx, state) => "${state.matchedLocation}/sub",
        builder: (context, state) {
          print("Building parent route");
          return Scaffold(
            appBar: AppBar(
              title: Text(state.location),
            ),
            body: Center(
              child: Text(state.location),
            ),
          );
        },
        routes: [
          GoRoute(
            path: 'sub',
            pageBuilder: (context, state) {
              print("Building child route");
              return MaterialPage(
                key: state.pageKey,
                child: Scaffold(
                  appBar: AppBar(
                    title: Text(state.location),
                  ),
                  body: Center(
                    child: Text(state.location),
                  ),
                ),
              );
            },
          ),
        ],
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-CH)
    • Flutter version 3.10.0 on channel stable at C:\src\flutter_2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\morat\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.78.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-05-15 09:28
Thanks for the report. Upon running the given code sample on mobile and web, I observed that the child route is built first and then a parent.

mobile:

```
[GoRouter] Full paths for routes:
  => /
  => /page1
  =>   /page1/sub
known full paths for route names:
  page1 => /page1

[GoRouter] setting initial location /page1/sub
I/flutter (21784): Building child route
I/flutter (21784): Building parent route
[GoRouter] Using MaterialApp configuration
W/Parcel  (21784): Expecting binder but got null!
I/flutter (21784): Building parent route
```


web:

```
Building child route
Building parent route
Building child route
Building parent route
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:58438/OWJRfF8tYDw=
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-6.0.pre.63, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-6.0.pre.63 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b8f7a2a64 (7 hours ago), 2023-05-14 17:42:29 -0400
    • Engine revision 326de1d849
    • Dart version 3.1.0 (build 3.1.0-110.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by chunhtai** [comment] 2023-05-18 20:37
This looks like WIP. We don't guarantee the build order of these builder. Why is this an issue?

**Comment by DamienMrtl** [comment] 2023-05-21 18:13
@chunhtai, Work In Progress ? what does this means ? 

Build order was correct in older versions of go_router. I think build order should be constant.

In my case, my parent route screen starts a service and the child route uses it.

**Comment by agustincards14** [comment] 2023-11-02 08:13
@chunhtai Does this affect creation of Providers, and therefore a child route being unable to access the Provider that was created in its parent route? 

In my case, this is the issue.

**Comment by chunhtai** [comment] 2023-11-02 17:27
@agustincards14 Do you have a repro?

**Comment by agustincards14** [comment] 2023-11-02 18:38
@chunhtai no, and in this case I just understood how "provider is scoped" so I can't pursue this method. I will have to wrap a nested Navigator with Provider instead of using Router to navigate.

Thanks for the quick reply!

**Comment by agustincards14** [comment] 2023-11-02 19:06
@chunhtai Is this it? I understand "Provider is scoped" so I tried to pair with a nested Navigator

### Steps to reproduce
1. Wrap the widget in your parent route with Provider<Match>
2. Create a sub route
3. Push sub-route onto stack from parent (using Navigator)
4. Consume Provider<Match> in subroute

### Expected results
Provider<Match> to be accessible from subroute using Navigator

### Actual results
`ProviderNotFoundException (Error: Could not find the correct Provider<Match> above this SetFormationPage Widget`


_GoRoute_ and its sub-routes:
```dart
GoRoute(
            path: 'match',
            name: 'match',
            builder: (context, state) {
              final match = DatabaseProvider.currentMatch;
              debugPrint('built MatchPage');
              return ChangeNotifierProvider<Match>(
                create: (_) => match!,
                child: const MatchPage(),
              );
            },
            routes: [
              GoRoute(
                path: 'setFormation',
                name: 'setFormation',
                builder: (context, state) {
                  debugPrint('built SetFormationPage');
                  return const SetFormationPage();
                },
              ),
            ],
          ),
``` 


Pushing route with _Navigator_ inside MatchPage:
```dart
IconButton(
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => const SetFormationPage(),
                  ),
                );
              },
              icon: const Icon(Icons.format_overline_rounded),
            ),
```


**ProviderNotFoundException** when trying to access Provider<Match> in SetFormationPage:
```dart
class SetFormationPage extends StatelessWidget {
  const SetFormationPage({super.key});

  @override
  Widget build(BuildContext context) {
    final team = context.read<Match>().date;
```

**Comment by chunhtai** [comment] 2023-11-02 19:29
This is WAI, the GoRoute is stacking so GoRoute('match') and GoRoute('setFormation') will create two pages that stack on top of each other. Their widget trees are parallel to each other. It seems to me the provider scope should be injected above the MaterialApp instead if you want the data two be shared by two pages.

**Comment by chunhtai** [comment] 2023-12-07 18:33
closing as WAI

**Closed by chunhtai** 2023-12-07 18:33 UTC
Labels: package, has reproducible steps, P2, p: go_router, found in release: 3.10, found in release: 3.11, team-go_router, triaged-go_router, multiteam-retriage-candidate
