### ISSUE TITLE
[Web] CanvasKIT TextField typed text disappear after lostfocus

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#46499] opened 2019-12-08 14:07 UTC
```bash
[√] Flutter (Channel master, v1.13.1-pre.59, on Microsoft Windows [versÃ£o 10.0.17763.864], locale pt-BR)
• Flutter version 1.13.1-pre.59 at C:\flutter
• Framework revision e58dc16 (8 hours ago), 2019-12-06 18:21:52 -0800
• Engine revision e7b69ced2e
• Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:\Users\usuario\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: C:\android-studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
• Android Studio at C:\android-studio
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.40.2)
• VS Code at C:\Users\usuario\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.7.0

[√] Connected device (2 available)
• Chrome • chrome • web-javascript • Google Chrome 78.0.3904.108
• Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-12-09 09:42
Possible duplicate of https://github.com/flutter/flutter/issues/45955

**Comment by andredealmei** [comment] 2019-12-09 10:19
I don't understand why this is a duplicity

**Comment by yjbanov** [comment] 2019-12-12 23:24
Just to be clear, are you seeing this in Chrome 78?

**Comment by andredealmei** [comment] 2019-12-13 11:39
yes and **79** too

**Comment by zariweyo** [comment] 2020-04-04 09:06
In Flutter 1.16.3 doesn't happen. I solve this when I update flutter. I have got Chrome 80.

**Comment by iapicca** [comment] 2020-04-06 14:27
Hi @andredealmei 
are you experiencing the issue upgrading to `dev`?
Thank you

**Comment by iapicca** [comment] 2020-05-29 13:55
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:55 UTC
Labels: a: text input, e: web_canvaskit, e: web_html, engine, platform-web, waiting for customer response
