### ISSUE TITLE
Regression on `hot_mode_dev_cycle__benchmark`

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47841] opened 2019-12-26 18:37 UTC
Regression on `hotReloadMillisecondsToFrameAfterChange` since 20 Dec 2019. It seems to have started consistently going over the baseline after an [engine roll](https://github.com/flutter/flutter/commit/0db029990707cf98d79d66c45802207dce768891).

**Comment by jonahwilliams** [comment] 2019-12-30 19:57
Possibly caused by: https://github.com/flutter/flutter/commit/0db029990707cf98d79d66c45802207dce768891

**Comment by franciscojma86** [comment] 2020-01-02 20:05
Closing as duplicate of https://github.com/flutter/flutter/issues/47842

**Closed by franciscojma86** 2020-01-02 20:05 UTC
Labels: severe: performance, severe: regression, ⚠ TODAY
