### ISSUE TITLE
heightSyle needed for making Text background color height consistent

### ISSUE THREAD

**Issue by coolit** [flutter/flutter#99141] opened 2022-02-25 08:32 UTC
## Use case

Text background color height is inconsistent for non-english characters. For selected texts, we already have selectionHeightStyle to fix this, but for other cases, the problem is still there.

**Comment by darshankawar** [comment] 2022-02-28 06:49
@coolit 
Can you elaborate by providing an example where you see the issue as you mentioned `but for other cases, the problem is still there.` ?

**Comment by coolit** [comment] 2022-02-28 09:05
@darshankawar 
```
import 'package:flutter/material.dart';

void main() => runApp(Home());

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.amber,
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('Demo')),
        body: Center(
            child: Container(
                child: Text(
          "曾经的我们",
          style: TextStyle(backgroundColor: Colors.blue),
        ))),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2022-03-01 05:25
@coolit 
I tried this code sample on latest master on all platforms (mobile, web and desktop) and can see the height is consistent, as below:

<img width="127" alt="Screenshot 2022-03-01 at 10 53 35 AM" src="https://user-images.githubusercontent.com/67046386/156110209-53b8d276-dd8b-4635-afd4-086fb37dec70.png">

`Channel master, 2.11.0-0.0.pre.715`

Can you check the same on latest master and confirm ?

**Comment by coolit** [comment] 2022-03-02 06:13
@darshankawar  
Flutter 2.11.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b101bfe32f (2 weeks ago)
Problem is still there.

**Comment by darshankawar** [comment] 2022-03-03 05:26
@coolit 
Thanks for the update and patience, but you seem to have verified on latest beta which is mirror of stable in which you are still seeing the behavior, but I verified on latest master per my earlier comment on which I don't see the same behavior so maybe it is fixed on latest master, so please check on latest master and confirm.

```
flutter channel master
flutter upgrade

```

**Comment by coolit** [comment] 2022-03-03 17:00
@darshankawar 
Sorry for the trouble. I had trouble using flutter upgrade here. So normally I downloaded from Flutter official download page. And this time I tried to do flutter upgrade for several times  and despite failures, at least it now displayed as below:
Flutter 2.11.0-0.0.pre.753 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2315431064 (34 minutes ago) • 2022-03-03 08:20:52 -0800
Engine • revision 121376d39a

But the problem is still there.

**Comment by darshankawar** [comment] 2022-03-04 06:13
@coolit 
Thanks for the update. I verified this again on latest stable and master on mac and windows, but don't see the same behavior as you:

<img width="127" alt="Screenshot 2022-03-04 at 11 43 18 AM" src="https://user-images.githubusercontent.com/67046386/156709761-ada48800-d267-4883-9074-83460ba8072c.png">

What platform are you seeing this behavior on ?

**Comment by coolit** [comment] 2022-03-04 12:45
@darshankawar 
windows 10 home

**Comment by coolit** [comment] 2022-03-05 12:21
@darshankawar 
It seems other problem are also relevant to the font. e.g. the button text is bold, the chip text is inconsistent in font style, etc. See below pic. And once I specify a font in asset and use it, then all these problems are gone.
![01](https://user-images.githubusercontent.com/13397709/156882719-b8f803d8-db3f-4bc3-ba98-b90b597560b1.png)

**Comment by darshankawar** [comment] 2022-03-07 05:48
@coolit 
I also tried on Windows 10 desktop using latest stable per unable to replicate this as mentioned here https://github.com/flutter/flutter/issues/99141#issuecomment-1058867538, 

Can you provide the `"曾经的我们",` font for this or you simply copy paste it from somewhere ?
 

> And once I specify a font in asset and use it, then all these problems are gone.

Can you provide these details like font ?

**Comment by coolit** [comment] 2022-03-07 10:49
@darshankawar 
01- So far I don't know which font is used by default. Do you happen to know that?
02- I have tried to specify a third font, and again no problem was found.

**Comment by darshankawar** [comment] 2022-03-08 05:22
> So far I don't know which font is used by default. Do you happen to know that?

I believe that is Roboto. Since I am unable to replicate this per my verification, going back to your original description, are you proposing to add a `heightStyle` property ? 

Also, please confirm on which platform (e.g windows desktop, web or mobile) are you seeing this behavior.

**Comment by coolit** [comment] 2022-03-08 06:09
As I said above, I used windows 10 home.
If by default the font is the root cause, it has nothing to do with heightStyle property. 
So far it seems with the default font, there will be several problems as mentioned above. 
Will test on a new windows system if I'm available. Will let you know by then.

**Closed** 2022-03-29 12:15 UTC
Labels: waiting for customer response, in triage
