### ISSUE TITLE
Flutter appears broken on the launch of the app, and fixes itself when the code is saved.

### ISSUE THREAD

**Issue by NeuronButter** [flutter/flutter#54926] opened 2020-04-16 04:02 UTC
## Steps to Reproduce

1. Create an application using the `flutter create` tool.
1a. Not sure if it's my code or it's Flutter wrong here, but here's my code in main.dart:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
   _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int count = 0;

  @override
  Widget build(BuildContext content) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text')
      ),
      body: Center(
        child: FlatButton(
          color: Colors.greenAccent.shade400,
          child: Text('Count is $count'),
          onPressed: () {
            setState( () => count++);
          },
        ),
      )
    );
  }
}
```
2. Use the debug tool built into VS Code (assuming the Flutter extension is installed) using either F5 or the Run menu in the sidebar on the left, and run the app on a virtual device.
3. The app appears with just an unformatted button and no app bar, but the functionality of the button continues to work.
4. Save the file with _no_ changes. The app will then appear correctly.

### Debug Console
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity( 9468): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 9468): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 9468): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 9468): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 9468): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@5659d66
D/FlutterActivityAndFragmentDelegate( 9468): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation( 9468): eglMakeCurrent: 0xdc6bd280: ver 2 0 (tinfo 0xdc756ce0)
Reloaded 1 of 478 libraries in 253ms.
```

_(The `Reloaded 1 of 478 libraries in 253ms` part only appeared after the save of the file, and hot reload did it's thing. This confuses me though, as no changes were made to the file, but the file should have been originally loaded because the unformatted button loads, and it's functionality is present.)_

### flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-AU)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Neeron Bhatta\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.1)
    • VS Code at C:\Users\Neeron Bhatta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

### Before Save
![image](https://user-images.githubusercontent.com/33238007/79412952-0f0ff400-7fea-11ea-9adf-9f228202f7fc.png)
### After Save
![image](https://user-images.githubusercontent.com/33238007/79413211-abd29180-7fea-11ea-963a-af9306b3ea05.png)

## Summary
- Flutter will load `main.dart` incompletely.
- On a file change, Flutter will reload(?) `main.dart`, with the second time being successful.

**Comment by VladyslavBondarenko** [comment] 2020-04-16 09:48
Hi @NeuronButter 
I can't reproduce it with Android Studio debug, it may be an issue with 'Dart and Flutter support for VS Code', please file the issue here https://github.com/Dart-Code/Dart-Code/issues.
Closing, as this isn't an issue with Flutter itself,
if it turns out the issue is not only from the Dart extension for VSC side, please comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-16 09:48 UTC
