### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method

### ISSUE THREAD

**Issue by baoxu** [flutter/flutter#81262] opened 2021-04-27 04:13 UTC
I'm doing the Upgrading pre 1.12 Android projects，The problem has been bothering me for two days，
I've tried a lot of things and it doesn't work
https://github.com/flutter/flutter/issues/65334
https://github.com/flutter/flutter/issues/10912
Such as：
1、flutter clean，flutter packages get，flutter pub cache repair……
2、change flutter channel，restart……
3、buildTypes {
    release {
        signingConfig signingConfigs.release
        minifyEnabled true
        useProguard true
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
}
4、public class MainActivity extends FlutterActivity {
         @Override
         public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
           //super.configureFlutterEngine(flutterEngine);
         GeneratedPluginRegistrant.registerWith(flutterEngine);
      }
}
None of the above methods can solve it.

iOS works, but not with Android
All plugins report this error

flutter doctor：
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.5 at /Users/baoxu/environment/flutter
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/baoxu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/baoxu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM G9550 (mobile)          • 98899a36504851524a                   • android-arm64  • Android 9 (API 28)
    • iPhone 12 Pro Max (mobile) • 89404628-9ECC-4FEC-BEB9-B4A29EFA755F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

GeneratedPluginRegistrant：
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.deviceinfo.DeviceInfoPlugin());
      co.apperto.fastqrreaderview.FastQrReaderViewPlugin.registerWith(shimPluginRegistry.registrarFor("co.apperto.fastqrreaderview.FastQrReaderViewPlugin"));
    flutterEngine.getPlugins().add(new com.pauldemarco.flutter_blue.FlutterBluePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    flutterEngine.getPlugins().add(new io.github.ponnamkarthik.toast.fluttertoast.FlutterToastPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.geolocator.GeolocatorPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlemaps.GoogleMapsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    flutterEngine.getPlugins().add(new creativemaybeno.wakelock.WakelockPlugin());
  }
}

**Comment by dafinoer** [comment] 2021-04-27 05:02
remove dependencies when they not support for null-safety. @baoxu

**Comment by baoxu** [comment] 2021-04-27 06:10
> remove dependencies when they not support for null-safety. @baoxu

What am I going to do？These don't support it

direct dependencies:
fast_qr_reader_view  ✗0.1.6 (git)  ✗0.1.6 (git)  ✗0.1.6 (git)  ✗0.1.6 (git)  
local_cache_sync     ✗1.3.0        ✗1.3.0        ✗1.3.0        ✗1.3.0        
mbkbluetooth         ✗0.0.3 (git)  ✗0.0.3 (git)  ✗0.0.3 (git)  ✗0.0.3 (git)

**Comment by pedromassangocode** [comment] 2021-04-27 07:29
Hi @baoxu 
Please provide the complete output of your `flutter run --release --verbose`.
Thank you

**Comment by baoxu** [comment] 2021-04-27 08:04
> Hi @baoxu
> Please provide the complete output of your `flutter run --release --verbose`.
> Thank you

 flutter run --release --verbose
[  +85 ms] executing: [/Users/baoxu/environment/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [/Users/baoxu/environment/flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +99 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +50 ms] executing: [/Users/baoxu/environment/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/baoxu/environment/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/Users/baoxu/environment/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.3
[        ] executing: sw_vers -buildVersion
[  +21 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D91
[  +11 ms] executing: sysctl hw.optional.arm64
[  +10 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] executing: /Users/baoxu/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +6 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +148 ms] Exit code 0 from: xcrun xcodebuild -version
[   +3 ms] Xcode 12.4
           Build version 12D4e
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +4 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +49 ms] List of devices attached
           98899a36504851524a     device usb:339816448X product:dream2qltezc model:SM_G9550 device:dream2qltechn transport_id:1
[ +142 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.tvOS-13-2" : [
                          {
                            "availabilityError" : "runtime profile not found",
                            "dataPath" : "\/Users\/baoxu\/Library\/Developer\/CoreSimulator\/Devices\/179A8315-15DC-40D7-8934-AA7D5C56D4A2\/data",
                            "logPath" : "\/Users\/baoxu\/Library\/Logs\/CoreSimulator\/179A8315-15DC-40D7-8934-AA7D5C56D4A2",
                            "udid" : "179A8315-15DC-40D7-8934-AA7D5C56D4A2",
                            "isAvailable" : false,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p",
                            "state" : "Shutdown",
                            "name" : "Apple TV"
                          },
……

[  +20 ms] /Users/baoxu/Library/Android/sdk/platform-tools/adb -s 98899a36504851524a shell getprop
[ +117 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +111 ms] Multiple devices found:
[   +3 ms] ro.hardware = qcom
[   +8 ms] SM G9550 (mobile)          • 98899a36504851524a                   • android-arm64 • Android 9 (API 28)
[   +1 ms] iPhone 12 Pro Max (mobile) • 89404628-9ECC-4FEC-BEB9-B4A29EFA755F • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
[   +2 ms] [1]: SM G9550 (98899a36504851524a)
[        ] [2]: iPhone 12 Pro Max (89404628-9ECC-4FEC-BEB9-B4A29EFA755F)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+6779 ms] q
[  +19 ms] "flutter run" took 10,393ms.
[  +25 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:306:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:294:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1193:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:440:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +344 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by pedromassangocode** [comment] 2021-04-27 08:23
Hi @baoxu 
Please make sure you run `flutter run --release --verbose` and select the same device for the command to proceed.

**Comment by baoxu** [comment] 2021-04-27 08:47
> Hi @baoxu
> Please make sure you run `flutter run --release --verbose` and select the same device for the command to proceed.

Like this？
adb devices
List of devices attached
98899a36504851524a      device

baoxudeMBP:flutter-ops-app baoxu$ flutter run --release --verbose 98899a36504851524a
[  +87 ms] executing: [/Users/baoxu/environment/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [/Users/baoxu/environment/flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +20 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +52 ms] executing: [/Users/baoxu/environment/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/baoxu/environment/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +56 ms] executing: [/Users/baoxu/environment/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +19 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 11.2.3
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 20D91
[   +9 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +72 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] executing: /Users/baoxu/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] executing: /usr/bin/xcode-select --print-path
[   +6 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +7 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +140 ms] Exit code 0 from: xcrun xcodebuild -version
[   +2 ms] Xcode 12.4
           Build version 12D4e
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +3 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +52 ms] List of devices attached
           98899a36504851524a     device usb:339816448X product:dream2qltezc model:SM_G9550 device:dream2qltechn transport_id:1
[ +141 ms] {
……
}
[  +30 ms] /Users/baoxu/Library/Android/sdk/platform-tools/adb -s 98899a36504851524a shell getprop
[  +82 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] "flutter run" took 3,456ms.
[  +21 ms] Target file "98899a36504851524a" not found.
[   +2 ms] 
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1287:9)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:437:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +269 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
baoxudeMBP:flutter-ops-app baoxu$ 


Connect the mobile phone to run up the log：
Running Gradle task 'assembleMovi_devDebug'...
✓ Built build/app/outputs/flutter-apk/app-movi_dev-debug.apk.
Debug service listening on ws://127.0.0.1:57327/ODidQ_qgQz8=/ws
Syncing files to device SM G9550...
E/flutter ( 6450): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermission on channel flutter.baseflow.com/geolocator)
E/flutter ( 6450): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #1      MethodChannelGeolocator.checkPermission (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:37:11)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #2      LocationManager._checkGeolocationPermission.<anonymous closure> (package:flutter_ops_app/util/location/location_manager.dart)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): 
E/flutter ( 6450): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 6450): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:79:24)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #2      startApp (package:flutter_ops_app/app/app.dart:32:5)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): 
E/flutter ( 6450): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel fast_qr_reader_view)
E/flutter ( 6450): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): 
E/flutter ( 6450): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermission on channel fast_qr_reader_view)
E/flutter ( 6450): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #1      requestCameraPermission (package:fast_qr_reader_view/fast_qr_reader_view.dart:105:18)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): #2      CameraUtil.fetchAvailableCameras (package:flutter_ops_app/util/camera.dart:26:11)
E/flutter ( 6450): <asynchronous suspension>
E/flutter ( 6450): 

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter.baseflow.com/geolocator_updates:
MissingPluginException(No implementation found for method listen on channel flutter.baseflow.com/geolocator_updates)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>
====================================================================================================

**Comment by pedromassangocode** [comment] 2021-04-27 11:34
Hi @baoxu 
From what I can see, the issue is related to a 3rd party plugins rather than to Flutter itself. Please open the issue in their dedicated repositories.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-27 11:34 UTC
Labels: in triage

**Comment by RosiAlv** [comment] 2021-07-30 07:25
¿Alguna solución para el siguiente error? 
E/flutter (31723): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'
