### ISSUE TITLE
Windows Desktop - Right Shift Key triggers full caps even after releasing.

### ISSUE THREAD

**Issue by blisssan** [flutter/flutter#76063] opened 2021-02-15 12:35 UTC
## Steps to Reproduce

This happens even on a very basic app. 

1. I created a flutter app using flutter create
2. Added a TextField or TextFormField to the default counter app.
3. Run as Windows desktop app
4. Start typing text into text field, press Right Shift key to introduce an uppercase character or symbol then release & proceed typing. 

**Expected results:**
Should resume back to lower case mode. 

**Actual results:**
Continues to type in Uppercase mode as if Shift has not yet released. 

Tested in Both dev channel & master channel.

The only way to change back to lower case or normal behaviour is to press the Left Shift Key or Always use Left Shift Key for Uppercase.

<details>
  <summary>Logs</summary>

There are no errors or exceptions during build or when this issue is happening.

Flutter Analyse found no issues.

```
[√] Flutter (Channel master, 1.27.0-2.0.pre.101, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.27.0-2.0.pre.101 at D:\Flutter\flutter
    • Framework revision c2ee916a5d (9 hours ago), 2021-02-14 23:01:04 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[!] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\SanthoshKumar\AppData\Local\Android\sdk
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    X No valid Android SDK platforms found in C:\Users\SanthoshKumar\AppData\Local\Android\sdk\platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Users\SanthoshKumar\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at I:\VisualStudio
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 6.3.9600]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-02-15 12:47
Hi @blisssan 
duplicate of https://github.com/flutter/flutter/issues/75675
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-15 12:47 UTC

**Comment by blisssan** [comment] 2021-02-15 12:50
Sorry! My bad. It's the same. Didn't come up on my search.
