### ISSUE TITLE
Obscure Text (TextField) shows preview while typing in Flutter Web

### ISSUE THREAD

**Issue by vanshg395** [flutter/flutter#56979] opened 2020-05-12 08:14 UTC
## Steps to Reproduce

1. Create a flutter web project.
2. Insert a `TextField` with `obscureText` set to `true`.
3. Now typing in the field in web version shows preview of characters before turning them into black dots. It should be directly obscured like other web frameworks.

**Comment by TahaTesser** [comment] 2020-05-12 11:52
duplicate of  https://github.com/flutter/flutter/issues/51218

**Closed** 2020-05-12 11:52 UTC

**Comment by AndroidNils** [comment] 2020-06-04 18:16
@vanshg395 I already created a PR: https://github.com/flutter/flutter/pull/56794 👍
