### ISSUE TITLE
does the flutter support dart native extension

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#43229] opened 2019-10-22 00:48 UTC
Does the flutter support the dart native extension on android platform,
I use the `import 'dart-ext:library_name'` and my dynamic library compiled with android NDK, 
where to install my self library on android, the system library path or the application path with libflutter.so,   when I click my flutter app. there is an error, 

`2019-10-21 17:03:08.104 27441-27460/? E/flutter: [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unknown library tag.error: library handler failed
2019-10-21 17:03:08.104 27441-27460/? E/flutter: [ERROR:flutter/shell/common/engine.cc(193)] Could not prepare to run the isolate.
2019-10-21 17:03:08.104 27441-27460/? E/flutter: [ERROR:flutter/shell/common/engine.cc(132)] Engine not prepare and launch isolate.
2019-10-21 17:03:08.104 27441-27460/? E/flutter: [ERROR:flutter/shell/common/shell.cc(428)] Could not launch engine with configuration.`

If I delete this call of native extension, my app can run successfully, I have tested the native extension on dart, I want to realize on flutter project.  Are there some guide notes about it if flutter supported.

**Comment by stuartmorgan** [comment] 2019-10-22 01:33
No, it does not. Closing as a duplicate of #2396 (which you already found, so I'm not sure why you filed it again).

As it says there, FFI is the approach supported by Flutter.

**Closed by stuartmorgan** 2019-10-22 01:33 UTC
Labels: created via support template

**Comment by ping996** [comment] 2019-10-22 01:59
Thanks for your help, I have readed the issue, just for confirm it again.
