### ISSUE TITLE
onTapOutside in TextFormField is not showing in linux os

### ISSUE THREAD

**Issue by ritunjaykumar** [flutter/flutter#116359] opened 2022-12-01 15:46 UTC
Hi, 
Flutter Team.
in Linux Os, I am not able to use onTapOutside in TextFromField but in Windows I can use this. for both os, I am using latest SDK.
Here is Flutter Doctor for both OS.

<details>
<summary>flutter doctor - Window-10</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.6.0-7.0.pre.34, on Microsoft Windows [Version 10.0.19044.2251], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.73.1)
[√] Connected device (4 available)
[!] HTTP Host Availability
    X HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Handshake error in client
! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>flutter doctor - Linux(Ubuntu 22)</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04.1 LTS 5.15.0-53-generic, locale en_IN)                                                                                          Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

Thanks.

**Comment by danagbemava-nc** [comment] 2022-12-02 07:54
Hi @ritunjaykumar, your flutter doctor for Linux shows that you're on the `stable` channel and not the `master` channel. 

`onTapOutside` is not available on the `stable` channel yet which would explain why you can't use it on your Linux but can use it on windows(windows is using master, according to your flutter doctor output). 

You should switch to the `master` channel on Linux if you want to use it there as well. 

I'll be closing this since there's a version mismatch. 

If you still experience this issue after switching to the master channel on Linux, kindly leave a comment below and I will reopen this. 

If you reproduce this after switching to the master channel on Linux, kindly provide the updated output of `flutter doctor -v` and a minimal complete reproducible code sample. 

Thank you

**Closed by danagbemava-nc** 2022-12-02 07:54 UTC
Labels: in triage

**Comment by ritunjaykumar** [comment] 2022-12-02 08:01
thanks for your reply.

how can i use the master. I mean I need to install again from scratch.

thanks

**Comment by Hixie** [comment] 2022-12-02 08:03
@ritunjaykumar You can run `flutter channel master` to switch channels.

**Comment by ritunjaykumar** [comment] 2022-12-02 08:08
Thank you.
