### ISSUE TITLE
Module 'url_launcher' not found when building app in Xcode

### ISSUE THREAD

**Issue by MrBananaPants** [flutter/flutter#76860] opened 2021-02-26 13:14 UTC
I'm trying to build my Flutter app in Xcode but I get a "module 'url_launcher' not found" error every time.
![image](https://user-images.githubusercontent.com/41532982/109303911-bcbf7680-783b-11eb-9379-949eaa942ba8.png)
I'm opening the `Runner.xcworkspace` file and starting the build. After a few seconds, I get that error.
I've tried `flutter clean`, `pod install`, `pod update`, `pod repo update`, removing the podfiles and creating new ones,... nothing seems to work. I did however notice that when I run `flutter clean`, then `flutter pub get`, and then `pod install`, it installs `Flutter` and `url_launcher` but with very early version numbers:
![image](https://user-images.githubusercontent.com/41532982/109304386-7cacc380-783c-11eb-9482-8c8423007802.png)
Also, when I manually start an IOS simulator and run my project from VSCode, it does successfully build the app and install / run it on the simulator.

To test it yourself,  you can clone my project from here: https://github.com/MrBananaPants/StarTracker
```

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-arm, locale
    en-BE)
    • Flutter version 1.22.6 at /Users/joranvancoillie/tools/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joranvancoillie/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment] 2021-02-26 14:56
Hi @MrBananaPants 
First, make sure you're executing `flutter build ios` before Xcode and target the same IOS in Xcode and Podfile, you're targeting iOS 12 in Xcode, iOS 9 in Podfile (not sure if that's the cause, just noticed), and then build from Xcode

Changing iOS target from 12 to 9 (match Podifle) and applied my own stream ID, `flutter build ios` and Xcode archive is successful in your project

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>

**Comment by MrBananaPants** [comment] 2021-02-26 15:09
Hi, I ran `flutter build ios` and tried to build it from Xcode afterwards but got the same error. The targeting error is fixed now because Xcode suggested the changes:
![image](https://user-images.githubusercontent.com/41532982/109317333-e503a100-784c-11eb-90d4-1f9c80575256.png)

**Comment by TahaTesser** [comment] 2021-03-01 07:02
Hi @MrBananaPants 
As mentioned in https://github.com/flutter/flutter/issues/76860#issuecomment-786696773, I can build your project with those minor changes. The problem might in your pod cache

Run these in the ios directory of your project
```bash
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
```

Thank you

**Comment by MrBananaPants** [comment] 2021-03-01 16:06
@TahaTesser I ran all those commands but still get the same module not found error. A friend of mine who also tried to build the repository through Xcode also got the same error.

**Comment by densa** [comment] 2021-03-01 22:33
@MrBananaPants looks like you are on apple silicone. Try run app from terminal `flutter run`

**Comment by MrBananaPants** [comment] 2021-03-02 06:59
@densa Yes I am on Apple Silicone. Using `flutter run`, I am able to run my project on an IOS simulator but it doesn't work when building it through Xcode. However, it did work a week or so ago through Xcode and a friend of mine who has an Intel MacBook Air also gets the same module not found error so it's not related to Apple Silicone.

**Comment by TahaTesser** [comment] 2021-03-02 07:17
Hi @MrBananaPants 
Can you please try `flutter pub cache repair ` and `flutter clean` then run the app
Thank you

**Comment by MrBananaPants** [comment] 2021-03-02 11:17
@TahaTesser I've also tried that. Still the same error in Xcode.

**Comment by TahaTesser** [comment] 2021-03-02 11:38
Hi @densa 
Are you SURE you'e opening `Runner.xcworkspace` and not `Runner.xcodeproj`?

**Comment by MrBananaPants** [comment] 2021-03-02 11:39
Yes, I'm 100% sure

**Comment by densa** [comment] 2021-03-02 11:46
I think you got error because when you run from Xcode it trying build for arm64 but can't. if you look into flutter run script you will see that they add **-arch x86_64** param
https://github.com/flutter/flutter/blob/74d58105d1563e130ff196eac0f195def8214b10/packages/flutter_tools/lib/src/ios/mac.dart#L253

**Comment by TahaTesser** [comment] 2021-03-02 14:20
@MrBananaPants 
Can you please try the above solution https://github.com/flutter/flutter/issues/76860#issuecomment-788849444
Thanks

**Comment by MrBananaPants** [comment] 2021-03-02 16:54
@TahaTesser how do I tried that solution? it's just a line of code I can't execute in the terminal.

**Comment by densa** [comment] 2021-03-02 18:26
@MrBananaPants you can try this https://github.com/flutter/flutter/issues/64502#issuecomment-759165857

**Comment by MrBananaPants** [comment] 2021-03-03 06:46
@densa I tried it but it still gave me the same error.
![image](https://user-images.githubusercontent.com/41532982/109765017-8d6e8800-7bf4-11eb-917e-92bcbf10ba68.png)

**Comment by TahaTesser** [comment] 2021-03-03 07:00
Hi @MrBananaPants 
Finally, glad you solved it, I don't have M1 so I wasn't able to verify this, closing as a duplicate of https://github.com/flutter/flutter/issues/64502#issuecomment-759165857
Thank you

**Closed by TahaTesser** 2021-03-03 07:00 UTC
Labels: in triage

**Comment by kaneki666** [comment] 2021-07-13 11:19
i am stuck at this last few hours! 

It builds properly on simulaor ..builds error in iphone 8..i did everything entioned above! nothing solved it!
any help!!

• Flutter version 2.3.0-17.0.pre.121 a
 • Dart version 2.14.0
• Xcode 12.5, Build version 12E262
• CocoaPods version 1.10.1

MacBook Pro (Retina, 13-inch, Late 2013)

**Comment by TahaTesser** [comment] 2021-07-13 12:20
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
