### ISSUE TITLE
Flutter bloc null safety is not able to generate dynamic button in form ?

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#89851] opened 2021-09-10 13:13 UTC
I am currently migrating my old codes to all new version of flutter to support null safety. In my login form I have this logic. Before this it works fine. Now when I run this codes I get this error "`This Form widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.`" How it works is basically when the bloc is ready will value only then I will build the button but the text boxes are build first.

```
What I have tried is WidgetsBinding.instance?.addPostFrameCallback(
                        (_) => but it does not give any error but the button is not shown up there.
```

Here is part of my codes below.
```
Widget loginForm(BuildContext context1) {
    final _auth = Provider.of<AuthModel>(context, listen: true);
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(height: getProportionateScreenHeight(10)),
          Text(
            'USERNAME',
            style: loginFontStyle,
            textAlign: TextAlign.left,
          ),
          SizedBox(height: getProportionateScreenHeight(10)),
          buildEmailFormField(),
          SizedBox(height: getProportionateScreenHeight(20)),
          Text(
            'PASSWORD',
            style: loginFontStyle,
            textAlign: TextAlign.left,
          ),
          SizedBox(height: getProportionateScreenHeight(10)),
          buildPasswordFormField(),
          SizedBox(height: getProportionateScreenHeight(20)),
          
          Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              BlocBuilder<LoginBloc, LoginApiState>(
                  builder: (BuildContext context, LoginApiState state) {
                print("Build login  " + state.toString());
                if (state is LoginApiStateInitial) {
                  return CircularProgressIndicator();
                }
                if (state is SetIDState) {
                  
                  if (localID != "" &&
                      localID != null) {
                    return Expanded(
                        child: DefaultButton(
                      text: "LOGIN",
                      press: () {
                        print("Form Validate Status" +
                            _formKey.currentState!.validate().toString());
                        if (_formKey.currentState!.validate()) {
                          _formKey.currentState!.save();
                          if (email != "" &&
                              password != "" &&
                              password.length >= 8 &&
                              emailValidatorRegExp.hasMatch(email) &&
                              localID != "") {
                            loginBLoC.loginVerify(
                                email, password, localID);
                           
                          }
                          
                        }
                      },
                    ));
                  } else {
                    return CircularProgressIndicator();
                  }
                }

What can I do to make it work like the previous version where it was perfectly working?

```

**Comment by maheshmnj** [comment] 2021-09-10 13:24
Hi @newbieflutter, Thanks for filing the issue. 

>This Form widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
 
 The error seems to suggest that you are trying to rebuild the widgets while the framework is in the process of rebuilding the widgets.


To understand the cause of the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that should be ready to run with minimal or no code changes.

**Comment by newbieflutter** [comment] 2021-09-10 13:26
Hi Mahesh,
                   Why on the previous version of the flutter everything is perfect only now when I move to the newer version getting all this issue ? How to share the whole codes is quite complex maybe I put the whole form here ?

**Comment by newbieflutter** [comment] 2021-09-10 13:45
Hi,
     I have paste here the minimal codes let me know if you need more details then I add as I have remove most codes ready
https://pastebin.pl/view/a484e602

**Comment by maheshmnj** [comment] 2021-09-13 04:44
@newbieflutter 

> Why on the previous version of the flutter everything is perfect only now when I move to the newer version getting all this issue 

Can you share what error are you getting?

>I have paste here the minimal codes let me know if you need more details then I add as I have remove most codes ready
https://pastebin.pl/view/a484e602

your code contains a lot of Uknown variables please provide minimal and complete runnable code, that should be ready to run by pasting the code.

Thanks

**Comment by TahaTesser** [comment] 2021-10-05 08:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-10-05 08:59 UTC
