### ISSUE TITLE
[iOS] strange artefact beneath an app icon and white screen before launch screen and when closing app

### ISSUE THREAD

**Issue by nexron171** [flutter/flutter#53154] opened 2020-03-24 07:37 UTC
On iOS at app launch we can see a strange artefact beneath an app icon (see screenshot). And possibly that is the reason of blank white screen before launch screen got visible (even when darkmode is active in iOS).

<img width="379" alt="Снимок экрана 2020-03-24 в 10 27 38" src="https://user-images.githubusercontent.com/6318346/77399858-4e686d80-6dbb-11ea-93cf-6de1e9b8d763.png">

<details>
  <summary>Logs</summary>

⇒  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!

</details>

**Comment by goderbauer** [comment] 2020-03-25 21:56
I believe what you're seeing there is the splash screen of your app fading in. If you don't have a splash screen setup, that's just a white rect. Maybe try defining one to see if this goes away?

/cc @xster

**Comment by nexron171** [comment] 2020-03-26 07:32
> I believe what you're seeing there is the splash screen of your app fading in. If you don't have a splash screen setup, that's just a white rect. Maybe try defining one to see if this goes away?
> 
> /cc @xster

For example, I have the green launch screen
<img width="729" alt="Снимок экрана 2020-03-26 в 10 17 01" src="https://user-images.githubusercontent.com/6318346/77620923-75a27480-6f4c-11ea-9e64-80d030ab4b5f.png">

and that's the result in slowmo
![giphy](https://user-images.githubusercontent.com/6318346/77620954-8652ea80-6f4c-11ea-958d-907e00491094.gif)

You can see the black background with a blurry white box and then the launch green screen already transitioning to flutter app.

**Comment by nexron171** [comment] 2020-03-26 07:34
And why there is a white screen between icon transition and launch screen with dark mode?

**Comment by xster** [comment] 2020-04-01 21:48
Thanks for taking the time to record this. I do suspect we had this issue since the early days of Flutter. I'm not very sure what's causing this. I don't see any additional steps we need to handle between launch and the launchscreen storyboard based on https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app. 

I suspect we might have misconfigured something in the flutter create xcode template. Perhaps with https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/#device-screen-sizes-and-orientations.

**Comment by adeolaex** [comment] 2020-06-19 20:14
> Thanks for taking the time to record this. I do suspect we had this issue since the early days of Flutter. I'm not very sure what's causing this. I don't see any additional steps we need to handle between launch and the launchscreen storyboard based on https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app.
> 
> I suspect we might have misconfigured something in the flutter create xcode template. Perhaps with https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/#device-screen-sizes-and-orientations.

It seems to occur due to Flutter's default launch icon being transparent. 

As stated here https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

"Keep the background simple and avoid transparency. Make sure your icon is opaque, and don’t clutter the background. Give it a simple background so it doesn’t overpower other app icons nearby. You don’t need to fill the entire icon with content." 


Thanks to https://stackoverflow.com/questions/22858501/ios-app-icon-with-transparent-background-showing-black-background-on-device for the build-up

Hope this helps.

**Comment by TahaTesser** [comment] 2020-09-03 12:36
The issue is reproducible on the latest `master`

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/92115483-1d7f7080-ee10-11ea-8eff-b34e34f01209.gif)

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.65 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2032a448ed (6 hours ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPhone 11 (mobile)     • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by adeolaex** [comment] 2020-09-10 17:24
@TahaTesser 
I believe this issue was solved on another thread. 

I can't give you the link to that thread, but the shortest solution is that the default flutter app icon is transparent.

 Changing the app icon to something opaque would remove the artefact. I would advise using the [flutter launcher icon](https://pub.dev/packages/flutter_launcher_icons/versions/0.6.1l) package.

**Comment by gaaclarke** [comment] 2020-10-26 21:09
I tried to reproduce this and was able to with the following Flutter:
```
Flutter 1.24.0-2.0.pre.91 • channel master • https://github.com/flutter/flutter.git
Framework • revision cb5865d86c (6 days ago) • 2020-10-20 09:50:31 -0700
Engine • revision ea2aea1c61
Tools • Dart 2.11.0 (build 2.11.0-234.0.dev)
```

I switched the icon to be one that has no alpha for all entries
![Icon-App-83 5x83 5@2x](https://user-images.githubusercontent.com/30870216/97228467-35ca9680-1794-11eb-9e1e-4feed6beb5bb.png)

There was a slight different artifact with a small vertical bar.  Then I made a plain UIKit application and used the same icon.  I saw the exact same artifact:

![openappicon](https://user-images.githubusercontent.com/30870216/97228764-9d80e180-1794-11eb-8a44-a28253206e22.gif)

Since we behave the same as a plain UIKit application there is nothing to fix, closing as works-as-intended.  If someone has a case where we are behaving differently than plain UIKit we can reopen it.

**Closed by gaaclarke** 2020-10-26 21:09 UTC
Labels: a: quality, engine, found in release: 1.22, framework, has reproducible steps, platform-ios
