### ISSUE TITLE
Slider Assertion falied 

### ISSUE THREAD

**Issue by K0IN** [flutter/flutter#20340] opened 2018-08-08 12:19 UTC
Hei I can't get a slider to work error:
```
I/flutter ( 2020): 'package:flutter/src/material/slider.dart': Failed assertion: line 112 pos 15: 'value != null': is
I/flutter ( 2020): not true.
```

code here:
```dart
import 'package:flutter/material.dart';

class FavoriteWidget extends StatefulWidget {
  
  @override
  _FavoriteWidgetState createState() => _FavoriteWidgetState();
}

class _FavoriteWidgetState extends State<FavoriteWidget> {  
  double x = 0.0;
  @override
  Widget build(BuildContext context) {
    return new Center(
        child: 
           new Slider(
            value: x,
            onChanged: (double v){
              setState(() {
                x = v;
                print( x ); 
              });
            }
          ) 
      );
  }
}
 
class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'my app',
      home: new Scaffold(
        appBar: AppBar( 
          title: Text('Lichterkette')
        ), 
        body: new FavoriteWidget(),
      )     
    );
  }

}

void main() {
  runApp( MyApp() );
}
```

Btw I don't work when I load the code / start the debug app but if I hot load the same code with just a space at the end the code runs fine.

**Comment by zoechi** [comment] 2018-08-23 15:32
I can't reproduce with your code.
Try running `flutter clean` in your project directory or try `master` channel.

**Comment by zoechi** [comment] 2018-10-08 08:59
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 08:59 UTC
Labels: waiting for customer response
