### ISSUE TITLE
[Connectivity] Can't use Connectivity in background

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [flutter/flutter#74969] opened 2021-01-29 07:18 UTC
`Connectivity().checkConnectivity()` returns `ConnectivityResult.none` when run in background. Also tried registering the plugin in the Application class as follows:

```kotlin
ConnectivityPlugin.registerWith(registry.registrarFor("io.flutter.plugins.connectivity.ConnectivityPlugin"))
```

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-12.0.pre at /home/ishwor/Workspace/Sdk/Flutter
    • Framework revision a706cd2112 (2 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ishwor/Workspace/Sdk/Android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/ishwor/Workspace/Sdk/Android
    • ANDROID_SDK_ROOT = /home/ishwor/Workspace/Sdk/Android
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Redmi 5A (mobile) • a1868107d840 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-01-29 09:31
Hi @Ishwor-Shrestha 
How you're achieving the background process, are you using any packages? Please provide more details. 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository if needed?
Thank you

**Comment by Ishwor-Shrestha** [comment] 2021-01-29 10:23
I am accessing `Connectivity` in firebase's onBackgroundMessage

**Comment by TahaTesser** [comment] 2021-02-01 15:44
Hi @Ishwor-Shrestha 
Thanks for the details, I can see the same results but I am worried it might not possible to get connectivity info while the app is in the background. Can you please provide a similar example where the system returns such info when in the background?

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (10 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>


Thank you

**Comment by Ishwor-Shrestha** [comment] 2021-02-01 16:31
If it's not possible through this plugin, would you be able to point me to an alternative?

**Comment by TahaTesser** [comment] 2021-02-02 08:39
@Ishwor-Shrestha 
Looks like it is possible to fetch connectivity data in the background https://stackoverflow.com/questions/41828490/check-internet-connection-in-background. You can implement something similar and try calling using PlatformChannels 
I think this plugin doesn't probably call it in the background
Thamk you

**Comment by Ishwor-Shrestha** [comment] 2021-02-02 10:05
@TahaTesser thanks for the help

**Comment by MooNag** [comment] 2021-02-03 17:06
Is this something that could be added to the connectivity plugin for flutter? My guess is many apps want to be able to check for internet in the background before trying to attempt network requests to save battery and background execution time.

**Comment by MooNag** [comment] 2021-02-03 18:34
I just did a test with the background_fetch plugin (version 0.6.0) and connectivity (version 3.0.0-nullsafety.3) and checking connectivity using Connectivity().checkConnectivity() results in the correct values when running in the background (app closed). So it looks like there is at least partial background compatibility with the plugin already. I would have to test with other devices and other background compatible plugins to be sure though.

**Comment by stuartmorgan** [comment] 2021-05-27 15:25
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).

**Closed by stuartmorgan** 2021-05-27 15:25 UTC
Labels: P6, found in release: 1.22, has reproducible steps, p: connectivity, p: first party, plugin
