### ISSUE TITLE
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by KittuPatel** [flutter/flutter#93233] opened 2021-11-08 07:56 UTC
Doctor summary (to see all details, run flutter doctor -v):
Unable to find any JVMs matching version "1.8".
No Java runtime present, try --request to install.
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by mamuseferha** [comment] 2021-11-08 09:32
Hi @KittuPatel 
Can you please provide information on what the issue is, as well as your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by KittuPatel** [comment] 2021-11-08 09:38
I am trying to run the application with macOS(darwin-x64) device. Whenever I run the app, I get the following error: 

`'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.`

I tried upgrading the flutter version and it doesn't work out. 

Following is the flutter doctor -v output

`[✓] Flutter (Channel master, 2.1.0-13.0.pre.175, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.175 at /Users/patel/fluttersdk/flutter
    • Framework revision efbde443d2 (8 months ago), 2021-03-18 13:40:08 -0700
    • Engine revision c4628b709c
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 2 categories.`

**Comment by mamuseferha** [comment] 2021-11-08 10:26
@KittuPatel can you provide minimal code sample that I can test with? Also, please confirm if this is a similar issue to yours and can help you resolve your issue https://github.com/flutter/flutter/issues/76325 ?

**Comment by KittuPatel** [comment] 2021-11-08 13:51
Yes it is the same issue as [#76325](https://github.com/flutter/flutter/issues/76325), but I did not find the solution.

**Comment by mamuseferha** [comment] 2021-11-09 07:12
Hi @KittuPatel 
There is an open issue addressing the case you described => https://github.com/flutter/flutter/issues/84241.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-09 07:12 UTC
Labels: in triage
