### ISSUE TITLE
CFBundleIdentifier does not exist - Help

### ISSUE THREAD

**Issue by PedroBDantas** [flutter/flutter#43989] opened 2019-11-01 16:08 UTC
Hi everyone! I am new to flutter and programming. I am learning, and doing fine until now.
I upgraded Mac OS, and I started to receive the error

flutter build ios
2019-11-01 13:00:00.574 defaults[67052:605179] 
The domain/default pair of (/Users/pedrodantas/Documents/Projetos/teste/ios/Runner/Info,
CFBundleIdentifier) does not exist

And after that, nothing works.. I can't run the app on android studio and can't run the app in Xcode...

Have NO idea how to solve this...
I would kindly as you guys for some help! 

Thank you

* Edit: Here is my flutter doctor:

MacBook-Air-de-Pedro:~ pedrodantas$ flutter doctor -v
[!] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.15 19A602, locale
    pt-BR)
    • Flutter version 1.7.8+hotfix.4 at /Users/pedrodantas/Documents/flutter
    • Framework revision 20e59316b8 (4 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pedrodantas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

* Update:
I reinstalled flutter... I don't get the same error, but now I get a popup telling "advice_ID" can't be openned because its not certified... how do I fix this ? Thanks
In Safety and privacy I already had selection on the option to open ANY app..

**Comment by jmagman** [comment] 2019-11-02 01:08
This was fixed in https://github.com/flutter/flutter/pull/38662 in flutter v1.9.1.  You are on v1.7.8+hotfix.4.  You should [upgrade](https://flutter.dev/docs/development/tools/sdk/upgrading#upgrading-the-flutter-sdk-and-packages) to the newest stable version of flutter.
https://flutter.dev/docs/development/tools/sdk/releases?tab=macos

Closing as duplicate of https://github.com/flutter/flutter/issues/37701.

**Closed by jmagman** 2019-11-02 01:08 UTC
