### ISSUE TITLE
GoRouter not support pushNamedAndRemoveUntil and pushAndRemoveUntil. like Navigator.pushAndRemoveUntil(context, newRouteName, (route) => false);

### ISSUE THREAD

**Issue by ATHUL3120** [flutter/flutter#124313] opened 2023-04-06 12:06 UTC
[go_router] GoRouter not support pushNamedAndRemoveUntil and pushAndRemoveUntil. like Navigator.pushAndRemoveUntil(context, newRouteName, (route) => false);

**Comment by danagbemava-nc** [comment] 2023-04-06 12:19
Hi @ATHUL3120, this feature has not been implemented yet and it is being tracked in https://github.com/flutter/flutter/issues/99112. 

Kindly upvote the original issue. 

Closing this as a duplicate of the issue linked above. 

Please do not file multiple issues for the same request especially since there's an issue already tracking it. 

Thank you

**Closed by danagbemava-nc** 2023-04-06 12:19 UTC
Labels: in triage
