### ISSUE TITLE
Flutter Web with CanvasKit renders images unreadable

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#60120] opened 2020-06-23 19:38 UTC
## Steps to Reproduce

1. Use this code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Image.asset(
          "assets/image.png",
          height: 500,
        ),
      ),
    ),
  );
}

```
1. Run `flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true`.

**Expected results:** 
Image:

![image](https://user-images.githubusercontent.com/24459435/85450676-4c1fd600-b599-11ea-8891-0a760b05ad21.png)

`flutter build web`:

![Bildschirmfoto 2020-06-23 um 21 29 41](https://user-images.githubusercontent.com/24459435/85450772-72de0c80-b599-11ea-991f-484193d2b6e0.png)

**Actual results (CanvasKit):** 

![Bildschirmfoto 2020-06-23 um 21 28 48](https://user-images.githubusercontent.com/24459435/85450537-28f52680-b599-11ea-8583-80a955296581.png)

### Flutter doctor
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F96, locale
    de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)
```

Same issue with `flutter channel dev` & `flutter channel master`

**Comment by iapicca** [comment] 2020-06-24 12:36
Hi @AndroidNils 
testing the code below with the latest master
running 

<details><summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const Widget _home = MyHomePage();
  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage();
  static const String _url =
      'https://user-images.githubusercontent.com/24459435/85450676-4c1fd600-b599-11ea-8891-0a760b05ad21.png';
  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: Image.network(_url),
        ),
      );
}

```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.184, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-1.0.pre.184 at /home/francesco/development/flutter_master
    • Framework revision 61b93d25bb (7 hours ago), 2020-06-24 01:53:01 -0400
    • Engine revision 2a9fed87a7
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 6b630c3719)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Linux desktop • linux      • linux-x64      • Linux
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.106

! Doctor found issues in 2 categories.

```

</details>

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/85556574-a4091c00-b62f-11ea-9cfd-f3b198a25e76.png)

</details>

I cannot observe the behavior you described, but
with this change `Image.network( _url, height: 500, ),`
I do experience that

<details><summary>resized screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/85557216-3f9a8c80-b630-11ea-87e8-385a036bb7b3.png)


</details>

it might be a duplicate of https://github.com/flutter/flutter/issues/58355 ,
but not being sure of that I'd keep it open for now.

Thank you

**Comment by AndroidNils** [comment] 2020-06-25 11:33
@iapicca I tested again a little. So it's a little bit tricky. I either have this issue (but not #60125) or I haven't this issue (but #60125) 🤨  From my feeling, it's completely random, which option happens 😅

**Comment by nhnifong** [comment] 2020-07-01 17:24
I'm guessing that probably is a dupe of #58355 and flutter neets to set a paint filter quality anywhere resizing could happen.
`paint.setFilterQuality(CanvasKit.FilterQuality.High);`

**Comment by AndroidNils** [comment] 2020-10-07 11:10
I tested it with `1.21.0-10.0.pre.55` again and everything worked perfectly 👍  Is there anyone else, who can reproduce this issue?

**Comment by kubaprzetakiewicz** [comment] 2020-11-10 13:20
We can reproduce it on `1.24.0-8.0.pre.149 • channel master`

**Comment by yjbanov** [comment] 2020-12-04 01:24
Just tested this on current master. The issue seems to have been that we applied incorrect `FilterQuality`. If I set it to `FilterQuality.none` I see the unreadable image. If I set it to `FilterQuality.low` (which is the default) the image becomes readable. I'm considering this issue fixed.

**Closed by yjbanov** 2020-12-04 01:24 UTC
Labels: P3, a: images, customer: web10, customer: workplace, dependency: skia, e: web_canvaskit, engine, found in release: 1.20, framework, has reproducible steps, platform-web, severe: rendering

**Comment by creativecreatorormaybenot** [comment] 2021-04-01 14:35
We are definitely still experiencing this issue with all images on CavasKit (Flutter version `2.1.0-12.2.pre`).

![image](https://user-images.githubusercontent.com/19204050/113310077-5a084180-92f7-11eb-940a-32269e59b17d.png)
![image](https://user-images.githubusercontent.com/19204050/113310085-5c6a9b80-92f7-11eb-80ba-418757a3f649.png)
![image](https://user-images.githubusercontent.com/19204050/113310095-5f658c00-92f7-11eb-9b69-eb5d5dc90bed.png)
![image](https://user-images.githubusercontent.com/19204050/113310105-612f4f80-92f7-11eb-9aaa-18d1fc62e1f2.png)


From what I can tell, there is nothing to do on the user side @yjbanov, right? So we do not have to tweak the `FilterQuality` ourselves?
