### ISSUE TITLE
Spiky post_backdrop_filter_* benchmarks -- possible lab issue?

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48818] opened 2020-01-14 16:41 UTC
I'm seeing a lot of spikes in the various post_backdrop* benchmarks, and they all seem to fall on the same commits. I'm hesitantt o blame the commits; they look pretty random. Could we have a problem with one of the iOS devices?

cc @godofredoc

**Comment by godofredoc** [comment] 2020-01-14 17:08
I'll take a look

**Comment by digiter** [comment] 2020-01-14 19:03
The benchmarks only runs on mac10, we will check the attache device.

**Comment by jonahwilliams** [comment] 2020-01-14 21:28
If we suspect the problem is in the lab, then TODAY is probably not an appropriate issue for this label. @digiter can you follow up here once you've diagnosed the issue? This will block the flutter roll

**Comment by godofredoc** [comment] 2020-01-14 21:40
To discard the regression is caused by the test bed can we run a couple of iterations with a commit from 12/13/19 just before the metric spikes started?

**Comment by digiter** [comment] 2020-01-14 22:03
@jonahwilliams The device looks normal, I found an issue with signing though.

@godofredoc I'm trying that.

**Comment by flar** [comment] 2020-01-14 23:07
The spikes that go up to 16ms are a known issue with the way we manage frames on iOS. There is a small chance that a frame will trigger a wait on vsync condition while processing an OpenGL call and that is beyond our control (as far as we currently understand). Once that happens, every frame after that will continue to trigger the same wait, essentially measuring our frame times at 16ms on every frame. At some point we eventually encounter another condition and recover, but if the benchmark happens to measure one of those cascading wait runs then the results will come back as 16ms instead of the actual processing time of a couple of ms.

I could mark the entire benchmark flaky, but the CPU/GPU percentage measurements seem to be reliable and we really do want to measure those.

I could archive each "rasterizer time" benchmark, but I'm currently looking into any way we can fix the underlying condition as it is something that frequently frustrates developers and while it means we probably maintain 60fps during those cascading wait sequences, we will be rendering an extra frame behind the entire time which isn't great.

**Comment by digiter** [comment] 2020-01-14 23:54
@flar That matches my observations, I have executed the benchmark 5 times agains the PR which added the benchmark initially (https://github.com/flutter/flutter/pull/46924). There were 3 successful runs with "rasterizer time" to be ~16ms, just like you mentioned. And 2 failed runs reporting "Exception: No valid measurements found.", which sounds like flakiness in the instrument tool.

**Comment by Hixie** [comment] 2020-01-15 00:06
Does that means we should close this?

**Comment by flar** [comment] 2020-01-15 00:08
The benchmark was written independently of the fix that it was going to measure and I don't remember if the fix was in when that PR landed. In either case, the runs should currently break down into 3 categories - runs of around 1-2ms which are "successful", runs of 16ms which are "the iOS issue is botching the results" and any exception you get is a failure in the benchmark infrastructure.

**Comment by flar** [comment] 2020-01-15 00:10
The description and title talk about a lot of spiking, but I've only mentioned one cause for a particular spike seen in a subset of the benchmarks. I'd have to have more detail on "a lot of spikes in the various" to know if we have addressed the problem being seen.

**Comment by flar** [comment] 2020-01-15 00:21
Let me see if I can break it down:

`90th_percentile_frame_build_time_millis` seems noisy and probably could be rebased
`99th_percentile_frame_build_time_millis` seems pretty green of late
`average_frame_build_time_millis` seems pretty green

`90th_percentile_frame_rasterizer_time_millis` the green numbers look good, the red spikes are the 16ms problem mentioned above
`99th_percentile_frame_rasterizer_time_millis` same as 90th%
`average_frame_rasterizer_time_millis` same as 90/99th%

`cpu_percentage` seems pretty green
`gpu_percentage` looks like it had a very minor regression around the beginning of the year, should be looked into, don't think that is a TODAY issue, though

`worst_frame_build_time_millis` totally drowning in noise and mostly green, not sure how useful this one is
`worst_frame_rasterizer_time_millis` seems to suffer from the 16ms problem mentioned above

**Comment by flar** [comment] 2020-01-15 00:30
I went ahead and rebased the `90th_percentile_frame_build_time` benchmark to be slightly more forgiving and it looks pretty green. At this point all of the `build_time` benchmarks look reasonable to me except for the `worst` variant (see below).

All of the `rasterizer_time` values bounce between green and 16ms - we do need to fix the 16ms problem, but it isn't a blocker for now. I could potentially rebase them all to allow 16-18ms until we fix that issue - that way they would show up as faint green, but not red. Thoughts?

gpu_percentage is an older regression and is still mostly green. Because it is green, it isn't a blocker, but because it recently shifted from "mostly solid green" to "usually pastel green" that shift should be investigated before it becomes red (still not a blocker).

I'm open to suggestions on the `worst_build_time` benchmark. I don't see it as a regression because it is so inherently noisy. Should we accept its inherent noisiness and just have a really forgiving baseline for it? What is its value now, or with a bumped up baseline?

**Comment by flar** [comment] 2020-01-15 01:35
I removed the TODAY label per the above analysis.

**Comment by godofredoc** [comment] 2020-01-16 23:21
This requires a fix on the benchmark removing the infra label

**Comment by flar** [comment] 2020-01-16 23:32
I can't reproduce the recent regression on the gpu_percentage figures locally. I get similar results on multiple commits all throughout the time frame that this benchmark has been measured, but the results do seem to be reproducible in the devicelab.

@godofredoc is there anything that might have changed in the lab on the machines that run this benchmark that could account for the change that happened around the beginning of the year? (between 12/30 and 1/02)

The same tiny regression is seen in both benchmarks that are reporting gpu percentages.

**Comment by flar** [comment] 2020-01-16 23:35
I just noticed that https://github.com/flutter/flutter/commit/e768c92fbc6cf8bf4e1814ef950a6092bbb6f658 is right at the border between the two ranges of benchmark results and includes a number of changes to the bots.

**Comment by liyuqian** [comment] 2020-02-25 06:13
What benchmarks are spiky here, CPU/GPU usages or other metrics like frame build/raster times? I believe that CPU/GPU usages are what we're interested in, and the regression there seems to be fixed after https://github.com/flutter/flutter/commit/4f460a932bbfa66d8d19bd3cf3f5c16db17a45b4. (Maybe it's just a device lab fix.)

If other metrics are spiky, maybe we can just archive those? A bigger issue might be that the CPU/GPU usage test has been disabled in the device lab https://github.com/flutter/flutter/issues/45435#issuecomment-583631286 so we'll no longer have signals to know whether someone accidentally broke @flar's  the energy improvement.

**Comment by liyuqian** [comment] 2020-03-16 22:01
@flar : can you please confirm if the CPU/GPU usage regression is fixed after 4f460a9 (maybe it's just a device lab fix), and whether we should just archive the frame build or raster time metrics since they probably have nothing to do with your energy optimization work?

**Comment by kf6gpe** [comment] 2020-03-17 14:51
This looks like it may be getting worse. Hard to tell, but it looks like it's regressing around https://github.com/flutter/flutter/pull/52619. I'm applying the TODAY label again so that we look into it.

![Screen Shot 2020-03-17 at 7 50 30 AM](https://user-images.githubusercontent.com/1435716/76868373-07f79980-6824-11ea-8933-a1cdc602be45.png)

**Comment by flar** [comment] 2020-03-17 18:07
@kf6gpe that's a different benchmark. Wasn't the original issue specific to the post_bdf benchmarks?

**Comment by kf6gpe** [comment] 2020-03-17 23:03
Whoops! My mistake -- I think I screen-capped the wrong benchmark. I'll follow up with tomorrow's performance sweep. Thanks!

**Comment by kf6gpe** [comment] 2020-03-23 21:46
Was looking at this today in performance triage, and it looks like we're missing metrics on all of the post_backdrop_filter* benchmarks at this point. @liyuqian @flar Does that ring a bell for either of you?

**Comment by flar** [comment] 2020-03-23 21:55
I think I see the issue with the missing data. The tests were commented out in https://github.com/flutter/flutter/commit/9348aea0164e72f8b32e45f29ed9fcc8ddbb3da7

The PR was getting rid of tests that use cpu/gpu because those mechanisms are broken. Those benchmarks both produce regular ms/frame results and they also produce the `flutter gauge` CPU/GPU usage results, so was the intent to get rid of the benchmarks entirely or just to get rid of their use of the broken flutter gauge mechanism? I'll ask in that PR...

**Comment by flar** [comment] 2020-03-24 23:57
Here is the data on 3 runs of these benchmarks just before and after the fix they are guarding:

before readback fix (2eed59c1d5e0bd0ce72b28116e30d0a1092dc729):

```
Run 1:
    "average_frame_rasterizer_time_millis": 2.6578179894179916,
    "90th_percentile_frame_rasterizer_time_millis": 3.064,
    "99th_percentile_frame_rasterizer_time_millis": 20.458,
    "worst_frame_rasterizer_time_millis": 203.208,
Run 2:
    "average_frame_rasterizer_time_millis": 3.095156081808397,
    "90th_percentile_frame_rasterizer_time_millis": 3.445,
    "99th_percentile_frame_rasterizer_time_millis": 20.95,
    "worst_frame_rasterizer_time_millis": 266.472,
Run 3:
    "average_frame_rasterizer_time_millis": 2.699309650053022,
    "90th_percentile_frame_rasterizer_time_millis": 3.081,
    "99th_percentile_frame_rasterizer_time_millis": 20.079,
    "worst_frame_rasterizer_time_millis": 199.697,
```

after readback fix (67adb8954fbb661a5270dc8a1ab3123289fa27a2): 

```
Run 1:
    "average_frame_rasterizer_time_millis": 2.612356382978721,
    "90th_percentile_frame_rasterizer_time_millis": 3.056,
    "99th_percentile_frame_rasterizer_time_millis": 27.527,
    "worst_frame_rasterizer_time_millis": 203.542,
Run 2:
    "average_frame_rasterizer_time_millis": 2.524662090813094,
    "90th_percentile_frame_rasterizer_time_millis": 3.088,
    "99th_percentile_frame_rasterizer_time_millis": 19.814,
    "worst_frame_rasterizer_time_millis": 203.096,
Run 3:
    "average_frame_rasterizer_time_millis": 2.5582992545260947,
    "90th_percentile_frame_rasterizer_time_millis": 2.797,
    "99th_percentile_frame_rasterizer_time_millis": 28.368,
    "worst_frame_rasterizer_time_millis": 201.939,
```

Here is a graph. There are slight improvements in the numbers after the fix, but they are very close to the measurement noise
![Frame rasterizer times before_after fix](https://user-images.githubusercontent.com/50503328/77487774-8a69f580-6df0-11ea-94b5-a266fc926bb5.png)

**Comment by flar** [comment] 2020-03-25 00:08
Ignore previous comment - wrong benchmark...

**Comment by flar** [comment] 2020-03-25 01:52
So I ran the post_backdrop_filter benchmark before and after the fix it was measuring, but with the cpu/gpu portion commented out.

All of the "before" runs came out with every frame measuring 16ms and all but one of the "after" runs had the same thing. So, this benchmark is dominated by the issue that makes iOS apps get stuck waiting for a new vsync window.

I can run it a few more times to see if I can get reproducibility of the one non-bugged "after" number I got, and to see if I can get any non-bugged "before" numbers, but it seems that the CPU/GPU measurements from the ios gauge utility were the only really reliable results we had on this fix.

**Comment by flar** [comment] 2020-03-25 22:39
I applied the "depth=1" hack to the engine before and after the iOS extra buffer fix (https://github.com/flutter/engine/pull/14104) and was able to get some data that didn't run into the vsync wait problem. I've included a graph below of 3 runs before and after the fix. There is a measurable improvement in actual render times with the fix, but it isn't reliably recorded by the benchmark output due to the issue of locking on vsync.

![Frame times before and after iOS extra buffer fix](https://user-images.githubusercontent.com/50503328/77592092-a3d17700-6eae-11ea-8cb9-7b34a58a3a28.png)

**Comment by kf6gpe** [comment] 2020-05-04 21:32
Is this a change we want to make, then, @flar? I checked the dashboard today, and it looks like we've dropped the metrics around this, so I'm not sure what good next steps are here.

**Comment by flar** [comment] 2020-05-04 21:56
Are you referring to the depth=1 hack? That isn't meant to be a fix, just an indication of what actions are tickling the problem.

Note that https://github.com/flutter/engine/pull/17688 may soon land and might have a similar effect. Time will tell as it doesn't specifically prevent the condition, but may have an impact on how likely it is to occur.

**Comment by chinmaygarde** [comment] 2020-06-11 02:06
Triage: Unclear if this is a regression of the issue with the app waiting for a vsync intervals generating inconsistent results. Assigning a default priority for now.

**Comment by zanderso** [comment] 2020-06-18 16:49
@flar @liyuqian @digiter No results for these benchmarks are currently showing up on the dashboard.

@flar Is this issue actionable? Should we close this and/or fold this into the work on benchmark dashboard graphing/diagnostics improvements?

**Comment by flar** [comment] 2020-06-19 04:41
It's disabled until https://github.com/flutter/flutter/issues/59238

**Comment by darshankawar** [comment] 2020-12-07 13:30
Hi @flar 
Just checking to see if this still should be kept open or can be closed ?

**Closed** 2020-12-08 19:23 UTC
Labels: P4, engine, severe: performance, waiting for customer response
