### ISSUE TITLE
Text field loses its value after scrolling out of view

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#9360] opened 2017-04-13 00:54 UTC
1) Run Gallery -> Text fields
2) Rotate into landscape mode
3) Enter some text into the Name field and dismiss the keyboard
4) Scroll to the bottom of the form, and then scroll back to the top.  The Name field will now be blank.

I noticed that the framework is disposing the EditableTextState when the field scrolls out of view.  Is that a new behavior and is it intentional?

EditableTextState.dispose() also hides the keyboard, so the dispose might be causing other bugs related to showing/hiding the keyboard during scrolling and relayout (https://github.com/flutter/flutter/issues/9221, https://github.com/flutter/flutter/issues/9231)

**Comment by eseidelGoogle** [comment] 2017-04-13 01:56
@abarth would know. :)

**Comment by abarth** [comment] 2017-04-13 03:26
Duplicate of #8418

**Closed by abarth** 2017-04-13 03:26 UTC
Labels: dataloss, prod: text input

**Comment by user-kva** [comment] 2017-07-12 14:29
controller: new TextEditingController(text: person.name),
and Name field will not be blank
