### ISSUE TITLE
Bring and Add Native Splash Screen in Windows Desktop

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#119999] opened 2023-02-04 14:04 UTC
I Have Sugestion Bring and Add Native Splash Screen in Windows Desktop.

**Comment by iapicca** [comment] 2023-02-04 16:11
it would be nice to add this to the 3rd party [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) ([here](https://github.com/jonbhanson/flutter_native_splash/issues)) which is an absolute must

**Comment by darshankawar** [comment] 2023-02-06 07:22
Closing this as duplicate of https://github.com/flutter/flutter/issues/41980

**Closed by darshankawar** 2023-02-06 07:22 UTC
Labels: in triage
