### ISSUE TITLE
image-picker0.6.7, pick mp4  was converted to jpg

### ISSUE THREAD

**Issue by lyzhonghua** [flutter/flutter#60740] opened 2020-07-02 03:57 UTC
up version of 0.6.6+1
1. When pick video(like mp4) from gallery, plugin will create a cache file in my app cache dir.
2. the file path is "path: /data/user/0/com.xxx.xxx/cache/_image_picker-692713936.jpg_", the mp4 was converted to jpg.

so I switch it to lower version:
 in version 0.6.1+
 When pick video (mp4) from gallery, the picking file path is "/storage/emulated/0/DCIM/Camera/_VID_20200701_121150.mp4_". It works fine.

Platform : Android

compileSdkVersion 29 or 28
targetSdkVersion 29 or 28

**Comment by darshankawar** [comment] 2020-07-02 05:52
Closing this as duplicate of [52419](https://github.com/flutter/flutter/issues/52419)

**Closed by darshankawar** 2020-07-02 05:52 UTC
