### ISSUE TITLE
DraggableScrollableSheet is rebuilding the screen while dragging

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#67219] opened 2020-10-03 12:01 UTC
## Steps to Reproduce

DraggableScrollableSheet is rebuilding the screen while dragging the sheet and it is causing unnecessary flickers.

```dart
class MyPopUpSheet extends StatelessWidget {
  ScrollController _scrollController; //Needed for

  @override
  Widget build(BuildContext context) {
    return Material(
      child: DraggableScrollableSheet(
        initialChildSize: 0.4,
        minChildSize: 0.4,
        builder: (ctx, scrollController) {
          
         print('Rebuilding...');

          return CustomScrollView(
            controller: scrollController,
            slivers: [
              SliverToBoxAdapter(child: Container(Colors.deepOrange)),
              SliverToBoxAdapter(child: Container(Colors.red)),
              SliverToBoxAdapter(child: Container(Colors.green)),
            ],
          );
        },
      ),
    );
  }

```

**Expected results:** 
It shouldn't rebuild the widget while dragging the sheet.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.20.4 at /Users/username/Library/Application Support/fvm/versions/1.20.4
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 
[✓] Connected device (1 available)            
    • ONEPLUS A6000 (mobile) • 431e5315 • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

cc/ @TahaTesser

**Comment by ayush221b** [comment] 2020-10-03 12:28
@TahaTesser I have noticed this issue too, for a similar implementation.

**Comment by TahaTesser** [comment] 2020-10-05 11:12
I can reproduce the issue 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: MyPopUpSheet(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class MyPopUpSheet extends StatefulWidget {
  @override
  _MyPopUpSheetState createState() => _MyPopUpSheetState();
}

class _MyPopUpSheetState extends State<MyPopUpSheet> {
  ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: DraggableScrollableSheet(
        initialChildSize: 0.4,
        minChildSize: 0.4,
        builder: (ctx, scrollController) {
          print('Rebuilding...');

          return CustomScrollView(
            controller: scrollController,
            slivers: [
              SliverToBoxAdapter(
                  child: Container(
                color: Colors.deepOrange,
                height: 200,
              )),
              SliverToBoxAdapter(
                  child: Container(
                color: Colors.red,
                height: 200,
              )),
              SliverToBoxAdapter(
                  child: Container(
                color: Colors.green,
                height: 200,
                // width: 200,
              )),
            ],
          );
        },
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0 at /home/tahatesser/Code/flutter_stable
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/tahatesser/Code/sdk
    • Java binary at: /home/tahatesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/tahatesser/Code/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)

• No issues found!


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0 at /home/tahatesser/Code/flutter_beta
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/tahatesser/Code/sdk
    • Java binary at: /home/tahatesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/tahatesser/Code/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.130, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-8.0.pre.130 at /home/tahatesser/Code/flutter_master
    • Framework revision f4bad5b422 (18 hours ago), 2020-10-04 12:37:03 -0400
    • Engine revision 04a46cc656
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/tahatesser/Code/sdk
    • Java binary at: /home/tahatesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/tahatesser/Code/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by JohnnyRainbow81** [comment] 2020-10-05 13:13
Same here! I recently opened an issue at stackoverflow: [https://stackoverflow.com/questions/64101774/draggablescrollablesheet-rebuilds-all-children-every-frame-when-dragged?noredirect=1#comment113497998_64101774](url)

**Comment by ayush221b** [comment] 2020-10-23 20:49
Hi @TahaTesser any update on this? It has been 20 days.

**Comment by dnfield** [comment] 2020-10-23 21:01
I'm taking a look at this.

**Comment by dnfield** [comment] 2020-11-03 23:48
Can you try the changes in https://github.com/flutter/flutter/pull/69724 to verify they fix your issue?

**Comment by TahaTesser** [comment] 2020-11-04 13:25
Hi @ganeshrvel  @dnfield 
I can confirm  https://github.com/flutter/flutter/pull/69724 fixes this issue 

### With PR (checked  locally `git fetch upstream pull/69724/head:drag_build` & `git checkout drag_build`)

#### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/98116978-1982d400-1ecf-11eb-8514-3c8966fbfd53.gif)


```
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                582ms
Waiting for sdk gphone x86 to report its views...                   11ms
Syncing files to device sdk gphone x86...                           74ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:64348/CAszCSbiJTo=/
I/flutter (19694): Rebuilding...


```

### Latest `master` channel

#### Preview
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/98117030-31f2ee80-1ecf-11eb-868b-9ebbb4f19d7d.gif)



```
I/chatty  (19380): uid=10158(com.example.master_flutter) 1.ui identical 42 lines
I/flutter (19380): Rebuilding...
I/flutter (19380): Rebuilding...
I/chatty  (19380): uid=10158(com.example.master_flutter) 1.ui identical 41 lines
I/flutter (19380): Rebuilding...
I/flutter (19380): Rebuilding...
I/chatty  (19380): uid=10158(com.example.master_flutter) 1.ui identical 61 lines
I/flutter (19380): Rebuilding...
I/flutter (19380): Rebuilding...
I/chatty  (19380): uid=10158(com.example.master_flutter) 1.ui identical 8 lines
I/flutter (19380): Rebuilding...

```

**Comment by JohnnyRainbow81** [comment] 2020-11-22 17:43
Since I am quite new to this whole github / opensource / collaboration - universe: 

When can we except that the updated DraggableScrollableSheet will be included in a new flutter version?

If this information is already around here, i wasn't able to find it or conclude it from the links to the 'waiting for PR to land'-label or the closed branches...

**Comment by dnfield** [comment] 2020-12-01 04:53
The fix for this is being reverted since it likely caused https://github.com/flutter/flutter/issues/70690 - need a better fix.

**Comment by dnfield** [comment] 2020-12-08 19:09
I plan to look at this again, but may not be until January at this point. Removing milestone until I can reasses difficulty of a fix that doesn't create the regressions #69724 introduced.

**Comment by orenronen17** [comment] 2021-01-17 12:51
Hello, any update on this fix?

**Comment by ayush221b** [comment] 2021-01-30 06:34
@TahaTesser @dnfield We have reached the end of January as well, and this actually is an issue that is user facing. Can you please help us with it?

**Comment by Akshar-Patel** [comment] 2021-02-26 19:03
I was facing this too. But the following workaround worked perfectly. You can give it a try. 
```
var someWidget;
final draggableScrollableSheet = DraggableScrollableSheet(
          expand: false,
          initialChildSize: 0.6,
          builder: (BuildContext context, ScrollController scrollController) {
            if (someWidget == null) {
              someWidget = SomeWidget();
            }
            return someWidget;;
          },
        );
```

**Comment by TutOsirisOm** [comment] 2021-03-06 20:09
@TahaTesser I believe the labels need to be updated on this issue. There's no current PR and it's also found in the latest release.

@dnfield Any update on this? A while ago we spoke on #69724 and I mentioned simply removing the `_updateExtent();` call from `didUpdateWidget` worked for me in solving the rebuilds and the scroll lock regression. I've been using it in a development environment for almost 3 months now and have no noticed any unintended side effects. My use case is rather simple so I'm not confident in submitting a PR at risk of regression.

**Comment by TahaTesser** [comment] 2021-03-09 12:43
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```


```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.165, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.165 at /Users/tahatesser/Code/flutter_master
    • Framework revision 698d438960 (6 hours ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>

**Comment by danielseow-simplify** [comment] 2021-03-26 19:23
> I was facing this too. But the following workaround worked perfectly.
> Even though this does not prevent rebuilds, it solved the UI jank while scrolling.
> You can give it a try.
> 
> ```
> var someWidget;
> final draggableScrollableSheet = DraggableScrollableSheet(
>           expand: false,
>           initialChildSize: 0.6,
>           builder: (BuildContext context, ScrollController scrollController) {
>             if (someWidget == null) {
>               someWidget = SomeWidget();
>             }
>             return someWidget;;
>           },
>         );
> ```

Wow! Thank you very much, it does fix the issue for now with this
`
if (someWidget == null) {
               someWidget = SomeWidget();
          }
`

**Comment by TutOsirisOm** [comment] 2021-04-10 17:32
Any update on this? I wouldn't say the above workaround is the intended behavior.

**Comment by JohnnyRainbow81** [comment] 2021-04-12 22:14
> I was facing this too. But the following workaround worked perfectly.
> Even though this does not prevent rebuilds, it solved the UI jank while scrolling.
> You can give it a try.
> 
> ```
> var someWidget;
> final draggableScrollableSheet = DraggableScrollableSheet(
>           expand: false,
>           initialChildSize: 0.6,
>           builder: (BuildContext context, ScrollController scrollController) {
>             if (someWidget == null) {
>               someWidget = SomeWidget();
>             }
>             return someWidget;;
>           },
>         );
> ```

Finally! Works for me too! Thank you very much. So simple, makes me kinda feel stupid :) 
Nonetheless I hope the flutter guys will bring a clean, official solution for this...

**Comment by Vardiak** [comment] 2021-06-10 10:57
Any news ? This is a severe performance issue and the proposed solution isn't ideal...

**Comment by ayush221b** [comment] 2021-09-07 03:53
@dnfield @TahaTesser It has been a long wait, have we found any stable solution for it yet?

**Comment by cyberpwnn** [comment] 2021-12-10 23:43
Would love a solution on this. The proposed solution does not stop rebuilds down the parent tree (think complex states in screens nested in the actual sheet). It makes me sick when I think about using stream builders with this lol.

**Comment by JohnnyRainbow81** [comment] 2022-02-01 13:12
So this thread is left for dead?

**Comment by kamami** [comment] 2022-03-14 20:27
This widget is not usable at the moment at all. Not working with NestedSrcrollview and rebuilds every single frame.

**Comment by kamami** [comment] 2022-03-16 11:53
Here is a minimal code sample available using only `http` to fetch data:
https://github.com/kamami/debug_draggable_scrollable_sheet

 I hope it is helpful to you.

EDIT: You could also completely remove the data fetching and `http` and just build any list:

```
import 'package:flutter/material.dart';

class AllActivitiesSheet extends StatelessWidget {
  DraggableScrollableController controller = DraggableScrollableController();

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
        controller: controller,
        builder: (context, scrollController) {
          return Material(
            color: Colors.white,
            child: CustomScrollView(
              controller: scrollController,
              slivers: [
                SliverList(
                  delegate: SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                      print("BUILD CONTAINER");
                      return Container(
                        margin: EdgeInsets.all(20),
                        color: Colors.red,
                        height: 150.0,
                        child: Center(child: Text(index.toString())),
                      );
                    },
                  ),
                )
              ],
            ),
          );
        });
  }
}
```

Every frame "BUILD CONTAINER" is printed to console while dragging the sheet.

**Comment by kamami** [comment] 2022-03-25 10:01
Any thoughts on this?

**Comment by definitelyme** [comment] 2022-04-28 11:02
It's the end of April and nothing yet.

**Comment by PankovSerge** [comment] 2022-04-29 22:22
Same here!

**Comment by kamami** [comment] 2022-05-13 13:00
Flutter 3.0.0 nothing changed...

**Comment by bugrevealingbme** [comment] 2022-06-07 17:24
Same here.... Flutter 3.0.0

**Comment by alguintu** [comment] 2022-07-27 06:06
Still nothing. ```DraggableScrollableSheet``` is still unusable for an even slightly complex child.

**Comment by theo-michel** [comment] 2022-08-04 11:37
Still really problematic, i don't know if anyone has an idea how to make them draw attention to this problem, because it is NOT FIXED.

**Comment by kvxmmu** [comment] 2022-08-12 13:24
Still not fixed

**Comment by aytunch** [comment] 2022-08-12 13:53
Especially when the keyboard is being shown and hidden you can see several prints displaying from `DraggableScrollSheet`. This causes too much jank

**Comment by ChauCM** [comment] 2022-08-28 05:00
really need this fix, can't use for production as the bug exist

**Comment by theo-michel** [comment] 2022-08-28 10:49
Hi, I have fixed it by using the sliding up pannel, it is way smoother and doesn't generate unecessarry rebuilds.
https://pub.dev/packages/sliding_up_panel

**Comment by bogdanmarinescu** [comment] 2022-09-05 19:35
close to two years since this bug is opened. very encouraging.

**Comment by phamducmanh1452001** [comment] 2022-09-08 02:16
still occurs

**Closed** 2022-09-13 19:31 UTC
Labels: framework, f: scrolling, a: quality, customer: crowd, has reproducible steps, P4, found in release: 2.0, found in release: 2.1
