### ISSUE TITLE
[DropDownMenu] unable to reload on setState

### ISSUE THREAD

**Issue by nimeshgarg** [flutter/flutter#140492] opened 2023-12-21 00:31 UTC
### Steps to reproduce

1 - Run the code attached in the issue form. (Flutter Web)
2 - add DropDownMenu to screen making the total of atleast 2 on display.
3 - Select value for all of the dropdownMenu
4 - Remove any of the dropDownMenu by tapping the cross in that line.

### Expected results

The value of the dropDownMenu will update according to change to the Controller.

### Actual results

The Value does not update while the console logs show that controller values are updated.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class DemoCheck extends StatefulWidget {
  const DemoCheck({super.key});

  @override
  State<DemoCheck> createState() => _DemoCheckState();
}

class _DemoCheckState extends State<DemoCheck> {
  int dropDownCount = 1;
  var drop1 = TextEditingController();
  late List<TextEditingController> controller = [
    drop1,
  ];

  // static Lists
  var testingList = [
    "123",
    "234",
    "345",
  ];

  Widget medicationRow(index) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Padding(
          padding: EdgeInsets.all(18),
        ),
        DropdownMenu(
          width: 250,
          enableFilter: false,
          enableSearch: false,
          requestFocusOnTap: false,
          controller: controller[index],
          textStyle: const TextStyle(fontSize: 18),
          onSelected: (value) {
            controller[index].text = value!;
          },
          dropdownMenuEntries:
              testingList.map<DropdownMenuEntry<String>>((entry) {
            return DropdownMenuEntry(value: entry, label: entry);
          }).toList(),
        ),
        const Padding(padding: EdgeInsets.all(8)),
        IconButton(
            iconSize: 18,
            onPressed: () {
              controller.removeAt(index);
              print(controller);
              setState(() {
                dropDownCount--;
              });
            },
            icon: const Icon(
              Icons.cancel_outlined,
              size: 36,
            )),
      ],
    );
  }

  Widget medRow(index) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Padding(padding: EdgeInsets.all(18)),
        medicationRow(index),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("d"),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Column(
            children: [
              const Padding(padding: EdgeInsets.all(18)),
              for (int i = 0; i < dropDownCount; i++) medRow(i),
              const Padding(padding: EdgeInsets.all(18)),
              IconButton(
                  onPressed: () {
                    setState(() {
                      controller.add(TextEditingController());
                      dropDownCount++;
                    });
                  },
                  icon: const Icon(Icons.add)),
              const Padding(padding: EdgeInsets.all(18)),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/51132740/6de24a53-5ca2-4ddc-8139-0e3712a272eb

</details>

### Logs

<details open><summary>Logs</summary>

```console
[TextEditingController#77085(TextEditingValue(text: ┤123├, selection: TextSelection.invalid, composing: TextRange(start: -1, end: -1))), TextEditingController#b0152(TextEditingValue(text: ┤345├, selection: TextSelection.invalid, composing: TextRange(start: -1, end: -1)))]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.2 23C64 darwin-x64, locale en-AU)
    • Flutter version 3.16.3 on channel stable at /Users/gar325/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gar325/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
    • IntelliJ at /Users/gar325/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.2 23C64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-21 09:31
I believe this is a duplicate of https://github.com/flutter/flutter/issues/127568

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-12-21 09:31 UTC
Labels: in triage
