### ISSUE TITLE
firebase_admob 0.8.0+3  iOS build FAILED, android works fine

### ISSUE THREAD

**Issue by Chepond** [flutter/flutter#28521] opened 2019-02-26 18:37 UTC
Just couldn't build iOS anymore after installing `firebase_admob` `0.8.0+3`
```
Launching lib/main.dart on iPhone XS Max in debug mode...
Running Xcode build...
Xcode build done.                                            5.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-02-27 02:31:49.234 xcodebuild[78364:500868] [MT] PluginLoading: Required plug-in compatibility UUID D7881182-AD00-4C36-A94D-F45FC9B0CF85 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_GADRequest", referenced from:
          objc-class-ref in firebase_admob(FLTRequestFactory.o)
      "_GULLogBasic", referenced from:
          _FIRLogBasic in FirebaseCore(FIRLogger.o)
      "_GULResetLogger", referenced from:
          _FIRResetLogger in FirebaseCore(FIRLogger.o)
      "_GULSetLoggerLevel", referenced from:
          _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GADMobileAds", referenced from:
          objc-class-ref in firebase_admob(FLTMobileAd.o)
      "_GULLoggerRegisterVersion", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GADExtras", referenced from:
          objc-class-ref in firebase_admob(FLTRequestFactory.o)
      "_GULLoggerInitializeASL", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_GULLoggerEnableSTDERR", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GADInterstitial", referenced from:
          objc-class-ref in firebase_admob(FLTMobileAd.o)
      "_OBJC_CLASS_$_GADBannerView", referenced from:
          objc-class-ref in firebase_admob(FLTMobileAd.o)
      "_GADAdSizeFromCGSize", referenced from:
          -[FLTFirebaseAdMobPlugin callLoadBannerAdWithId:channel:call:result:] in firebase_admob(FirebaseAdMobPlugin.o)
      "_GULLoggerForceDebug", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_kGADAdSizeSmartBannerLandscape", referenced from:
          -[FLTFirebaseAdMobPlugin callLoadBannerAdWithId:channel:call:result:] in firebase_admob(FirebaseAdMobPlugin.o)
      "_GULIsLoggableLevel", referenced from:
          _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
      "_kGADAdSizeSmartBannerPortrait", referenced from:
          -[FLTFirebaseAdMobPlugin callLoadBannerAdWithId:channel:call:result:] in firebase_admob(FirebaseAdMobPlugin.o)
      "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
          objc-class-ref in firebase_admob(FLTRewardedVideoAdWrapper.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone XS Max.
```

```
[✓] Flutter (Channel master, v1.2.3-pre.50, on Mac OS X 10.14.3 18D109, locale
    en-HK)
    • Flutter version 1.2.3-pre.50 at /Users/leungsiuhang/documents/flutter
    • Framework revision f460dd60df (5 hours ago), 2019-02-26 08:08:28 -0500
    • Engine revision 9f95ef23aa
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 f7e435ac26)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 9 (API 28) (emulator)
    • iPhone XS Max            
      • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by Chepond** [comment] 2019-02-27 07:33
@zoechi 
hey bro, is there any temp solution that I can get my iOS app built?
my flutter project uses swift and kotlin support, if it really matters

**Comment by Chepond** [comment] 2019-03-04 01:50
I have god damn solved the crap.. 
I created a brand new project and add firebase_core
then everything works fine...
its quite funny i have to recreate a new project and migrate everything when i face this kind of build issues

**Comment by kathum123** [comment] 2019-03-15 20:02
please you can help me firebase_admob not  working

**Comment by kroikie** [comment] 2019-10-13 18:22
@Chepond

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/413. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:49
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-11-20 14:26
Hi @Chepond 
If you are still experiencing this issue 
with the latest version of Flutter and `firebase_admob `
could you please provide your updated  `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2019-12-13 14:19
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-12-13 14:19 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, transferred, waiting for customer response
