### ISSUE TITLE
Flutter SDK 1.22.2版本中LinearGradient 不能设置colors了

### ISSUE THREAD

**Issue by Inisit** [flutter/flutter#68556] opened 2020-10-20 03:30 UTC
Flutter SDK 1.22.2版本中LinearGradient 不能设置colors了

**Comment by SeasonLeee** [comment] 2020-10-20 03:43
What @Inisit means is that he can't set `colors` in `LinearGradient` on Flutter version 1.22.2

and I suggest you, @Inisit also provide detail `flutter doctor -v` in your comment to help investigation

**Comment by sidrao2006** [comment] 2020-10-20 03:48
Duplicate of #68566

Hey @Inisit , I found an open issue addressing this problem. Please follow up there.

Thank you

**Comment by klniu** [comment] 2020-10-20 08:32
run flutter clean command and restart IDE

https://stackoverflow.com/questions/64168427/flutter-after-flutter-1-22-update-i-am-getting-error-in-lineargradient-properti

**Comment by TahaTesser** [comment] 2020-10-20 08:56
Hi @Inisit 
This doesn't reproduce on the latest `stable` but please check https://github.com/flutter/flutter/issues/63908
<details> 
<summary>complete code sample</summary> 

```dart
  import 'package:flutter/material.dart';

  void main() => runApp(MyApp());

  class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        title: 'Material App',
        home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body: Center(
            child: Container(
              height: 100,
              decoration: BoxDecoration(
                  gradient: LinearGradient(
                      begin: Alignment.bottomCenter,
                      end: Alignment.topCenter,
                      colors: [
                    Colors.blue,
                    Colors.purple,
                  ])),
              child: Center(child: Text('Hello World')),
            ),
          ),
        ),
      );
    }
  }

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 193EBBC9-CC2A-4477-B8A0-A5F12BB51400 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

```

</details> 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-20 08:56 UTC
