### ISSUE TITLE
PageView use animateToPage and nextPage with exception caught by rendering library

### ISSUE THREAD

**Issue by hustlemickey** [flutter/flutter#47730] opened 2019-12-24 09:12 UTC
I'm using PageView to build an app:

here is my code:
```   
_pageController = PageController(initialPage: 0, keepPage: false);
Timer.periodic(Duration(seconds: 1), (timer) {
  _pageController.nextPage(duration: Duration(milliseconds: 600), curve: Curves.decelerate);
});
```
scroll to next page every sec,  it come with below exceptions, but app will keep run without crash or failed, all looks good, just some exception will keep print out. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 275 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild) - scrollOffset <= precisionErrorTolerance': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
```
The relevant error-causing widget was: 
```
  PageView file:///Users/mickeystone/wor/flutter_wtf/lib/ui/main_pages/home/banner_page.dart:28:27
When the exception was thrown, this was the stack: 
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:275:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver.dart:1165:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
...
The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#bdc3b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 750.0, remainingPaintExtent: 375.0, crossAxisExtent: 210.9, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 375.0, remainingCacheExtent: 375.0 cacheOrigin: 0.0 )
...  geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 375.0, maxPaintExtent: Infinity, hasVisualOverflow: true, cacheExtent: 375.0)
...    scrollExtent: Infinity
...    paintExtent: 375.0
...    maxPaintExtent: Infinity
...    hasVisualOverflow: true
...    cacheExtent: 375.0
...  currently live children: 2 to 2
RenderObject: RenderSliverFillViewport#bdc3b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 750.0, remainingPaintExtent: 375.0, crossAxisExtent: 210.9, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 375.0, remainingCacheExtent: 375.0 cacheOrigin: 0.0 )
  geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 375.0, maxPaintExtent: Infinity, hasVisualOverflow: true, cacheExtent: 375.0)
    scrollExtent: Infinity
    paintExtent: 375.0
    maxPaintExtent: Infinity
    hasVisualOverflow: true
    cacheExtent: 375.0
  currently live children: 2 to 2
...  child with index 2: RenderIndexedSemantics#f837d
...    needs compositing
...    parentData: index=2; layoutOffset=750.0
...    constraints: BoxConstraints(w=375.0, h=210.9)
...    semantics node: SemanticsNode#70
...      Rect.fromLTRB(0.3, 0.0, 375.0, 210.9)
...      tags: RenderViewport.twoPane
...      flags: isImage
...      textDirection: ltr
...    semantic boundary
...    size: Size(375.0, 210.9)
...    index: 2
...    child: RenderRepaintBoundary#94a04
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=375.0, h=210.9)
...      layer: OffsetLayer#2df23
...        offset: Offset(0.3, 0.0)
...      size: Size(375.0, 210.9)
...      metrics: 97.1% useful (1 bad vs 34 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#38651
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=375.0, h=210.9)
...        size: Size(375.0, 210.9)
...        child: RenderImage#3e6db
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=375.0, h=210.9)
...          size: Size(375.0, 210.9)
...          image: [1080×500]
...          fit: cover
...          alignment: center
...          invertColors: false
...          filterQuality: low
```

**Comment by ndhbr** [comment] 2020-03-19 20:31
I have the same problem. Have you found a solution?

**Comment by memtopia** [comment] 2020-03-20 02:22
Still

**Comment by MichelRahme** [comment] 2020-04-05 05:29
I currently have the same problem

**Comment by Emadeddin-eibo** [comment] 2020-04-12 14:35
Change the **Curve**, I'm using **easeIn** and it's working so far!

**Comment by dsdsharma** [comment] 2020-05-12 17:00
I am using this [plugin](https://pub.dev/packages/carousel_pro) it is giving same error. Any Solutions?

**Comment by fangsj** [comment] 2020-07-27 23:39
I have the same problem. Have you found a solution?

**Comment by ndhbr** [comment] 2020-07-28 06:29
> I have the same problem. Have you found a solution?

I live with it, because otherwise there's no Problem...

**Comment by theochampion** [comment] 2020-07-31 11:11
Any updates on this ? Having the issue with flutter stable `v1.17.5`

**Comment by pedromassangocode** [comment] 2020-09-24 12:48
Hi @hustlemickey 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by hustlemickey** [comment] 2020-09-25 01:59
> Hi @hustlemickey
> Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you

Tested on: 
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.0-12.1.pre at /Users/utopia/flutter
    • Framework revision 8b3760638a (9 天前), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

Issue not show on version 1.22.0-12.1.pre.

**Comment by pedromassangocode** [comment] 2020-09-25 07:09
Hi @hustlemickey 
Can you please provide your flutter doctor -v, your flutter run --verbose and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment] 2020-09-25 07:10
Hi @hustlemickey 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2020-09-25 07:10 UTC
Labels: f: scrolling, framework, in triage

**Comment by rakib205** [comment] 2020-10-05 17:33
Still facing this issue.

**Comment by pedromassangocode** [comment] 2020-10-12 08:26
Hi @rakib205 
Please open a new issue and complete the issue-template.
Thanks
