### ISSUE TITLE
Text selection handles are shown on top of other widgets. 

### ISSUE THREAD

**Issue by MChernetsov** [flutter/flutter#153426] opened 2024-08-14 09:38 UTC
### Steps to reproduce

1. Enter text into text field
2. Select it
3. Scroll up text field a little up for text selection controls be visible on top of app bar

### Expected results

Controls aren't visible

### Actual results

Controls is visible

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: [Colors.blue](https://colors.blue/),
        ),
        body: ListView(
          physics: BouncingScrollPhysics(
            parent: AlwaysScrollableScrollPhysics(),
          ),
          children: [
            SizedBox(height: 16),
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/f15931f8-8548-46e1-88ef-66d29690e769

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale ru-RU)

    • Flutter version 3.24.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.22.0/flutter

    • Upstream repository https://github.com/flutter/flutter.git

    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700

    • Engine revision b8800d88be

    • Dart version 3.5.0

    • DevTools version 2.37.2



[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

    • Android SDK at /Users/mchernetsov/Library/Android/sdk

    • Platform android-34, build-tools 34.0.0

    • ANDROID_HOME = /Users/mchernetsov/Library/Android/sdk

    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java

    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

    • All Android licenses accepted.



[✓] Xcode - develop for iOS and macOS (Xcode 15.4)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Build 15F31d

    • CocoaPods version 1.15.2



[✓] Chrome - develop for the web

    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome



[✓] Android Studio (version 2023.3)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/9212-flutter

    • Dart plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/6351-dart

    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)



[✓] VS Code (version 1.90.1)

    • VS Code at /Users/mchernetsov/Downloads/Visual Studio Code.app/Contents

    • Flutter extension can be installed from:

      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter



[✓] Connected device (5 available)

    • iPhone (mobile)                 • 00008101-001228542169001E            • ios            • iOS 17.5.1 21F90

    • iPhone 15 Pro Max (mobile)      • DB7D8745-5386-487B-949A-F163C9327C6B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)

    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64

    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64

    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.119



[✓] Network resources

    • All expected network resources are available.



• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-14 10:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/13182

**Closed by danagbemava-nc** 2024-08-14 10:20 UTC
Labels: in triage
