### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by Nery31** [flutter/flutter#99626] opened 2022-03-06 12:18 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:130:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:88:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:152:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:442:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:229:25)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dwds.dart:91:9)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:686:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 21.04 5.11.0-49-generic, locale fr_FR.UTF-8)
    • Flutter version 2.10.3 at /home/nery/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (il y a 4 jours), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/nery/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio-2020.3.1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio-2020.3.1/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓]

**Comment by danagbemava-nc** [comment] 2022-03-07 08:56
Duplicate of #97604

**Closed by danagbemava-nc** 2022-03-07 08:56 UTC
Labels: in triage
