### ISSUE TITLE
Text input is slow if text is very long or there are many TextSpans

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#114158] opened 2022-10-27 14:48 UTC
## Details

I have my own package with a custom `TextEditingController` that decorates strings. With the package, text input is very slow if the text has thousands of lines. I had suspected that parsing text or building `TextSpan`s was expensive, but I noticed `TextField` itself without the package was slow with long text.

App developers who want to create an app with text editing have no option but to use another framework if Flutter can handle only short text.

### Example 1

1. Copy the code below and paste it into DartPad.
2. Press the "Run" button.
3. Copy very long text and paste it into the TextField in the App.
    - e.g. [basic.dart](https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter/lib/src/widgets/basic.dart) with about 7,600 LOC.
4. Type some letters quickly.
5. Each typed letter appears in the TextField slowly.

<details>
<summary><b>Reproducible code</b></summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App();

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SizedBox.expand(
            child: TextField(maxLines: null),
          ),
        ),
      ),
    );
  }
}
```
</details>

### Example 2

I also tried a `TextEditingController` with a large number of `TextSpan`s. In the example app below, `buildTextSpan()` of `TextEditingController` returns one of two different `TextSpan`s in turn every time the cursor position changes. Each TextSpan has 10,000 lines with 5 children per line.

1. Run `flutter create bug`.
2. Replace the content of `main.dart` in the created project with the code below.
3. Run `flutter run`.
4. Move the cursor in the TextField quickly with arrow keys.
5. The text switches with delay.

It does not look like the debug and profile modes have significant difference in the responsiveness.

<details>
<summary><b>Reproducible code</b></summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatefulWidget {
  const App();

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final _controller = MyTextEditingController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SizedBox.expand(
            child: TextField(
              controller: _controller,
              maxLines: null,
              autofocus: true,
            ),
          ),
        ),
      ),
    );
  }
}

class MyTextEditingController extends TextEditingController {
  MyTextEditingController() {
    _prepareTextSpans();
  }

  final List<TextSpan> _textSpans1 = [];
  final List<TextSpan> _textSpans2 = [];
  String _text = '';
  TextSelection? _prevSelection;
  bool _flag = false;

  @override
  TextSpan buildTextSpan({
    required BuildContext context,
    TextStyle? style,
    required bool withComposing,
  }) {
    if (selection != _prevSelection) {
      _flag = !_flag;
    }
    _prevSelection = selection;

    WidgetsBinding.instance.addPostFrameCallback((_) {
      value = value.copyWith(text: _text);
    });

    return TextSpan(
      style: style,
      children: _flag ? _textSpans1 : _textSpans2,
    );
  }

  void _prepareTextSpans() {
    for (var i = 0; i < 10000; i++) {
      for (var j = 0; j < 4; j++) {
        _textSpans1.add(
          TextSpan(
            text: j.isEven ? 'aaaaa' : 'bbbbb',
            style: j.isEven ? const TextStyle(color: Colors.orange) : null,
          ),
        );
        _textSpans2.add(
          TextSpan(
            text: j.isEven ? 'aaaaa' : 'bbbbb',
            style: j.isEven ? null : const TextStyle(color: Colors.orange),
          ),
        );
      }
      _textSpans1.add(const TextSpan(text: '\n'));
      _textSpans2.add(const TextSpan(text: '\n'));
    }
    _text = _textSpans1.map((v) => v.text).join();
  }
}
```
</details>

## Logs

<details>
<summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 10.0.22000.1098], locale ja-JP)
    • Flutter version 3.3.5 on channel stable at D:\flutter\sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (8 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = D:\android\sdk
    • Java binary at: C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3\jbr\bin\java
    • Java version OpenJDK Runtime Environment JBR-17.0.4.1+7-469.62-jcef (build 17.0.4.1+7-b469.62)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\xxxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2022-10-28 11:12
Hi @kaboc, thanks for filing a detailed issue. However, I see some issues that are reflecting similar behavior: #96173, #90063. Please also see https://github.com/flutter/flutter/issues/90063#issuecomment-1163476776 which gives a hint you may wanna try.

**Comment by kaboc** [comment] 2022-10-28 12:23
@huycozy 
Thank you for the info. #96173 is about amount of memory. My issue looks more similar to #90063 that is about speed rather than memory.

The link contained in https://github.com/flutter/flutter/issues/90063#issuecomment-1163476776 you mentioned is broken, but I guess from the path in the URL that it is the link to the document of `DeltaTextInputClient`. Your suggestion to try the class sounds like an advice to avoid using the built-in `TextField` because it does not work well for long text. It is clearly an issue on the framework side, so I don't see why its users have to create their own custom text editor using DeltaTextInputClient to get around the issue. It is too much and does not seem easy, as I wrote in #112382.

> If I have to implement a text editor to achieve the above, the API of my package must be changed. In addition, thinking about the fact that even the Flutter's standard TextField created by awesome people from the Flutter team still has bugs and is far behind native text input components in terms of quality, I doubt that general developers including me can create good editors on our own.

If it is certain that fixing #90063 resolves both of the issues I explained with two examples at the top of this page, this one can be closed as a duplicate, but I'm not sure if all of those are due to the same cause.

**Comment by huycozy** [comment] 2022-10-31 03:33
Hi @kaboc, I can see this is a framework issue. It also can be reproduced on mobile and web with similar behavior.
Although issue #90063 is labeled `desktop`, I think the issue should be addressed in one issue and updated the appropriate labels for other platforms too. Please check my comment at https://github.com/flutter/flutter/issues/90063#issuecomment-1296495185.

**Comment by kaboc** [comment] 2022-10-31 10:23
@huycozy 
It sounds like a good idea to merge this one into 90063 as it already has the "P3" label as an issue with higher priority. I'm fine as long as it will be addressed, whether related issues are tackled separately or together in a single issue page.

**Comment by huycozy** [comment] 2022-10-31 10:37
@kaboc I'm going to close this issue as a duplicate of #90063. You can also leave there your comment or react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2022-10-31 10:37 UTC
Labels: in triage
