### ISSUE TITLE
Scaffold App Bar shows a back button momentarily after a Navigator.pushReplacement call, even on an empty navigator stack

### ISSUE THREAD

**Issue by kinshul** [flutter/flutter#12691] opened 2017-10-24 18:30 UTC
## Steps to Reproduce

1) Found this issue when I was trying to navigate from a screen to another using the `Navigator.pushReplacement()` call, after clearing the Navigator route stack using `Navigator.pop().` To reproduce build a two screen app, where both of the screens use a `Scaffold` with an `AppBar`.

2) In your app use 
```dart
Navigator.popUntil(context, (_) => !Navigator.canPop(context));
Navigator.pushReplacement(
      context, new MaterialPageRoute(builder: (BuildContext context) => route));
```
 to navigate from one screen to the other.

3) The observation is that the app bar shows a back button momentarily, after the route navigation is triggered. The back button disappears in a fraction of a second. No errors are thrown in the log messages.

Here is my sample app, that can be used to reproduce this issue.

```dart
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Wifi App',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new AppScaffold(isWifiOn: true),
    );
  }
}

class AppScaffold extends StatelessWidget {
  static final String wifiOnAppBarTitle = "Wifi is On";
  static final String wifiOffAppBarTitle = "Wifi is Off";

  // Is wifi on, at present
  final bool isWifiOn;
  AppScaffold({@required this.isWifiOn});

  Widget body(BuildContext context) {
    return new Center(
        child: new GestureDetector(
      child: isWifiOn ? new Icon(Icons.wifi) : new Icon(Icons.wifi_off),
      onTap: () {
        if (isWifiOn) {
          clearStackAndPushRoute(context, new AppScaffold(isWifiOn: false));
        } else {
          clearStackAndPushRoute(context, new AppScaffold(isWifiOn: true));
        }
      },
    ));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: isWifiOn
              ? new Text(wifiOnAppBarTitle)
              : new Text(wifiOffAppBarTitle)),
      body: body(context),
    );
  }
}

void clearStackAndPushRoute(BuildContext context, Widget route) {
  Navigator.popUntil(context, (_) => !Navigator.canPop(context));
  Navigator.pushReplacement(
      context, new MaterialPageRoute(builder: (BuildContext context) => route));
}
```

## Logs
No exceptions thrown

## Flutter Doctor
```
[-] Flutter (on Linux, locale en_US.UTF-8, channel google3)
    • Flutter at /google/obj/workspace/d9981df61cffad7a0e5a854147e02734/ee049f8d-e0ae-4e42-ba92-614f4524525c/blaze-out/k8-opt/bin/mobile/flutter/tools/tools.runfiles/google3
    • Framework revision null (null), null
    • Engine revision null
    • Tools Dart version null
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/google/home/kinshul/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 18.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Nexus 5X • 00da1e796fb1cf52 • android-arm • Android 6.0 (API 23)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).
```

**Comment by Hixie** [comment] 2017-10-24 20:55
Fascinating...

**Comment by xster** [comment] 2017-10-26 19:20
Wondering why there wasn't any sort of animations in the video you posted. Just out of curiosity, does this still happen if you changed https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/page.dart#L104 to zero?

I'm hypothesizing that causing rebuilds on the app bar at the beginning and at the end of the page transition is causing this.

**Comment by eseidelGoogle** [comment] 2017-10-26 20:00
I've repro'd using @kinshul's example.  @xster I attempted to change 300 to 0 in page.dart and yes it no longer shows a frame with the back button.

I suspect that it's rebuilding the "previous" route (the one we're transitioning away from) and the BackButton widget is noticing that there is a new route on the stack (that we "canPop") and thus showing itself, even though the route is in progress.

@HansMuller may also have ideas. :)

**Comment by eseidelGoogle** [comment] 2017-10-26 20:02
I suspect this code:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app_bar.dart#L336
is effectively reading from a global (the navigation stack) which has already been modified at the start of the transition.

**Comment by eseidelGoogle** [comment] 2017-10-26 20:04
So there are a bunch of workarounds which @kinshul could use, including manually telling AppBar not to show the BackButton on those routes.

I believe AppBar automaticallyImplyLeading: false will disable the automatic BackButton behavior:
https://docs.flutter.io/flutter/material/AppBar/automaticallyImplyLeading.html

**Comment by xster** [comment] 2017-10-26 20:08
You can also not animate as a workaround since I don't think it's desirable to have page transition animations on tab switches anyway

**Comment by kinshul** [comment] 2017-10-27 19:43
@xster I had disabled animations in the video I posted, as, the default (slide up) transition was unsuitable for bottom bar navigation. We probably would use a slight fade animation or no animation. I had disabled the animation by overriding the buildTransition method in MaterialPageRoute

```
class _NoAnimationsRoute<T> extends MaterialPageRoute<T> {
  _StoreManagerRoute({WidgetBuilder builder}) : super(builder: builder);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
          Animation<double> secondaryAnimation, Widget child) =>
      child;
}
```

@eseidelGoogle @xster 
Setting `transitionDuration` to 0, with or without overriding `buildTransitions()` works. 

```
class _StoreManagerRoute<T> extends MaterialPageRoute<T> {
  _StoreManagerRoute({WidgetBuilder builder}) : super(builder: builder);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
          Animation<double> secondaryAnimation, Widget child) =>
      child;

  @override
  Duration get transitionDuration => const Duration(milliseconds: 0);
}

```
This would work, but would prevent us from using any animations.

I will try to use @eseidelGoogle suggestion to disable BackButton on the app bar on routes, when we want to use the fade transition. 

@eseidelGoogle @xster Thanks for the workaround.

**Comment by Hixie** [comment] 2017-11-01 20:12
@kinshul Can you clarify if this is still a blocker for you or if the workarounds are sufficient for your immediate needs?

I expect we'll get to this sometime this quarter or early next quarter if it's not urgent.

**Comment by kinshul** [comment] 2017-11-07 18:12
@Hixie The workarounds are good enough for now.

**Comment by Hixie** [comment] 2018-04-06 19:03
What's going on here is that if a route that was still animating when it was removed finishes its animation while it's still visible, it'll rebuild, and this causes it to notice that it's no longer the first page, and so it thinks that it should show its back button.

This should get resolved as part of my Navigator refactor (which is making the history management saner internally), but that won't land for a few weeks still.

**Comment by Hixie** [comment] 2018-05-15 22:52
This is top of my list but unfortunately my list got a bit delayed recently due to non-Flutter-related issues. Moving to bucket5.

**Comment by zoechi** [comment] 2019-01-30 16:52
I was not able to reproduce with the code from the initial comment
```
[✓] Flutter (Channel master, v1.1.10-pre.205, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by zoechi** [comment] 2019-02-21 07:48
https://stackoverflow.com/questions/54801746/pushreplacement-showing-back-arrow-flutter might be related

**Comment by ChaseGuru** [comment] 2019-05-08 17:16
@Hixie @zoechi To me this item seems very high impact because it affects almost any app that pushes-replacements and shows the end user a buggy back button.

It's been here a year now, anyway this can be fixed soon?  We'll use the workaround to disable back buttons and put them in for now though.

**Comment by TahaTesser** [comment] 2020-03-25 12:47
This issue still exist

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';
import 'package:flutter/scheduler.dart' show timeDilation;

void main() {
  timeDilation = 3.0;

  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Wifi App',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new AppScaffold(isWifiOn: true),
    );
  }
}

class AppScaffold extends StatelessWidget {
  static final String wifiOnAppBarTitle = "Wifi is On";
  static final String wifiOffAppBarTitle = "Wifi is Off";

  // Is wifi on, at present
  final bool isWifiOn;
  AppScaffold({@required this.isWifiOn});

  Widget body(BuildContext context) {
    return new Center(
        child: new GestureDetector(
      child: isWifiOn
          ? new Icon(Icons.wifi, size: 100)
          : new Icon(Icons.signal_wifi_off, size: 100),
      onTap: () {
        timeDilation = 3.0;
        if (isWifiOn) {
          clearStackAndPushRoute(context, new AppScaffold(isWifiOn: false));
        } else {
          clearStackAndPushRoute(context, new AppScaffold(isWifiOn: true));
        }
      },
    ));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: isWifiOn
              ? new Text(wifiOnAppBarTitle)
              : new Text(wifiOffAppBarTitle)),
      body: body(context),
    );
  }
}

void clearStackAndPushRoute(BuildContext context, Widget route) {
  Navigator.popUntil(context, (_) => !Navigator.canPop(context));
  Navigator.pushReplacement(
      context, new MaterialPageRoute(builder: (BuildContext context) => route));
}

```

**Comment by chunhtai** [comment] 2020-03-25 21:17
can be solved by https://github.com/flutter/flutter/issues/45938

**Comment by YeungKC** [comment] 2020-12-18 18:05
I was unable to reproduce this behavior on both the iOS simulator and macOS, and it may have been fixed.

If there are no objections, I will close this issue.

cc @kinshul @eseidelGoogle @TahaTesser 

![ios](https://i.imgur.com/PY2mfDt.gif)
![mac](https://i.imgur.com/073HOep.gif)

**Comment by TahaTesser** [comment] 2020-12-21 13:07
Thanks! @YeungKC 
 I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-12-21 13:07 UTC
Labels: P4, a: quality, customer: fast (g3), f: material design, f: routes, found in release: 1.21, framework, has reproducible steps
