### ISSUE TITLE
SafeArea can cause visual artifacts on iOS

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#24578] opened 2018-11-20 21:06 UTC
```
Flutter (Channel master, v0.11.8-pre.16, on Mac OS X 10.14.1 18B75, locale en-US)
```

When using `SafeArea` with `true` for `top` and `bottom` you can get visual artifacts (garbage, flickering, etc) when "nothing" has been drawn in that area. It's particularly more prevalent if you previously allowed Flutter to draw to that space and then use a `top/bottom: true` statement later.

Screenshot:

![jpeg_20181120_093934](https://user-images.githubusercontent.com/37941/48802756-01efb800-ecc5-11e8-8b85-24582d7e416a.jpg)

**Comment by Rockvole** [comment] 2018-11-20 21:53
Looks like :
[IphoneX + SafeArea + landscape + pushReplacement = screen flicker](https://github.com/flutter/flutter/issues/22063)

**Comment by dnfield** [comment] 2018-11-21 08:44
Duplicate of https://github.com/flutter/flutter/issues/22063

**Comment by dnfield** [comment] 2018-11-21 08:44
(Please feel free to reopen if you think there's something else going on!)

**Closed by dnfield** 2018-11-21 08:44 UTC
