### ISSUE TITLE
Columns in DataTable reverse the characters in Persian words

### ISSUE THREAD

**Issue by FtADev** [flutter/flutter#66256] opened 2020-09-21 11:15 UTC
![Screenshot from 2020-09-21 14-39-05](https://user-images.githubusercontent.com/29522746/93760459-e9ca8600-fc18-11ea-9924-c38090736468.png)

Rows are correct in Persian but the columns are like this.

**Comment by TahaTesser** [comment] 2020-09-21 14:02
Hi @FtADev 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by FtADev** [comment] 2020-09-21 16:11
It just happened on flutter web! I tested on an emulator and that was ok!

flutter doctor -v
`[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.1.pre at ~/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ...
    • Platform android-30, build-tools 30.0.2
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 4.0)
    • Android Studio at ...
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Chromium 83.0.4103.97
      Arch Linux

! Doctor found issues in 2 categories.
`

flutter run -d chrome -v

`[ +116 ms] executing: [~/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[        ] executing: [~/flutter/] git tag --points-at HEAD
[  +14 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.1.pre
[   +9 ms] executing: [~/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [~/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [~/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: ~/Android/sdk/platform-tools/adb devices -l
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: ~/Android/sdk/platform-tools/adb devices -l
[  +76 ms] Found plugin flutter_dropzone at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +6 ms] Found plugin flutter_dropzone_web at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +2 ms] Found plugin flutter_keyboard_visibility at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[ +138 ms] Found plugin flutter_dropzone at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +4 ms] Found plugin flutter_dropzone_web at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +2 ms] Found plugin flutter_keyboard_visibility at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +40 ms] Generating .../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +81 ms] List of devices attached
[   +3 ms] List of devices attached
[ +109 ms] Launching lib/main.dart on Chrome in debug mode...
[  +55 ms] Updating assets
[ +118 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +6 ms] Syncing files to device Chrome...
[  +15 ms] Found plugin flutter_dropzone at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +2 ms] Found plugin flutter_dropzone_web at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[        ] Found plugin flutter_keyboard_visibility at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +34 ms] Found plugin flutter_dropzone at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +1 ms] Found plugin flutter_dropzone_web at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +1 ms] Found plugin flutter_keyboard_visibility at ~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +24 ms] Generating .../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +47 ms] <- reset
[   +6 ms] ~/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev ~/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
~/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tools.YHYCEE/flutter_tool.XGXPSJ/app.dill --libraries-spec file://~/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /tmp/flutter_tools.YHYCEE/flutter_tools.KKCYHC --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill.track.dill
--platform file://~/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12354 ms] Syncing files to device Chrome... (completed in 12,494ms, longer than expected)
[        ] Synced 35.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +468 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:40171/devtools/browser/fac04c65-401d-4db1-83ed-3b5ab5923939
[+4096 ms] Debug service listening on ws://127.0.0.1:40215/fukFPgbaFV4=

[ +255 ms] Debug service listening on ws://127.0.0.1:40215/fukFPgbaFV4=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
`

and a sample code:

`SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Directionality(
          textDirection: TextDirection.rtl,
          child: DataTable(
            columns: [
              DataColumn(
                label: Text(
                  "شرح کالا",
                ),
              ),
              DataColumn(
                label: Text(
                  "واحد کالا",
                ),
              ),
              DataColumn(
                label: Text(
                  "تعداد",
                ),
              ),
              DataColumn(
                label: Text(
                  "تاریخ نیاز",
                ),
              ),
              DataColumn(
                label: Text(
                  "نام دسته",
                ),
              ),
              DataColumn(
                label: Text(
                  "توضیحات",
                ),
              ),
            ],
            rows: List<DataRow>.generate(
              5,
              (index) => DataRow(
                color: MaterialStateProperty.resolveWith<Color>(
                    (Set<MaterialState> states) {
                  if (states.contains(MaterialState.selected))
                    return Theme.of(context)
                        .colorScheme
                        .primary
                        .withOpacity(0.08);
                  if (index % 2 == 0) return Colors.grey.withOpacity(0.3);
                  return null; // Use default value for other states and odd rows.
                }),
                cells: List<DataCell>.generate(6, (index) {
                  return DataCell(Text('Row $index'));
                }),
                selected: selected[index],
                onSelectChanged: (bool value) {
                  setState(() {
                    selected[index] = value;
                  });
                },
              ),
            ),
          ),
        ),
      ),`

**Comment by FtADev** [comment] 2020-09-21 16:21
It just happened on flutter web. I tested on an emulator and that was ok!

Here is `flutter doctor -v`

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.1.pre at .../flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at .../Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: .../android-studio-4-canary/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 4.0)
    • Android Studio at
      .../.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.65
      14223
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Chromium 83.0.4103.97
      Arch Linux

! Doctor found issues in 2 categories.

```

`flutter -d chrome -v`

```
[ +116 ms] executing: [.../flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[        ] executing: [.../flutter/] git tag --points-at HEAD
[  +14 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.1.pre
[   +9 ms] executing: [.../flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [.../flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [.../flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: .../Android/sdk/platform-tools/adb devices -l
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: .../Android/sdk/platform-tools/adb devices -l
[  +76 ms] Found plugin flutter_dropzone at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +6 ms] Found plugin flutter_dropzone_web at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +2 ms] Found plugin flutter_keyboard_visibility at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[ +138 ms] Found plugin flutter_dropzone at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +4 ms] Found plugin flutter_dropzone_web at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +2 ms] Found plugin flutter_keyboard_visibility at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +40 ms] Generating .../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +81 ms] List of devices attached
[   +3 ms] List of devices attached
[ +109 ms] Launching lib/main.dart on Chrome in debug mode...
[  +55 ms] Updating assets
[ +118 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +6 ms] Syncing files to device Chrome...
[  +15 ms] Found plugin flutter_dropzone at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +2 ms] Found plugin flutter_dropzone_web at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[        ] Found plugin flutter_keyboard_visibility at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +34 ms] Found plugin flutter_dropzone at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone-1.0.9/
[   +1 ms] Found plugin flutter_dropzone_web at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-1.0.7/
[   +1 ms] Found plugin flutter_keyboard_visibility at .../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/
[  +24 ms] Generating .../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +47 ms] <- reset
[   +6 ms] .../flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev .../flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
.../flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tools.YHYCEE/flutter_tool.XGXPSJ/app.dill --libraries-spec file://.../flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /tmp/flutter_tools.YHYCEE/flutter_tools.KKCYHC --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill.track.dill
--platform file://.../flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12354 ms] Syncing files to device Chrome... (completed in 12,494ms, longer than expected)
[        ] Synced 35.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +468 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:40171/devtools/browser/fac04c65-401d-4db1-83ed-3b5ab5923939
[+4096 ms] Debug service listening on ws://127.0.0.1:40215/fukFPgbaFV4=

[ +255 ms] Debug service listening on ws://127.0.0.1:40215/fukFPgbaFV4=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".

```

and a sample code

```dart
SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Directionality(
          textDirection: TextDirection.rtl,
          child: DataTable(
            columns: [
              DataColumn(
                label: Text(
                  "شرح کالا",
                ),
              ),
              DataColumn(
                label: Text(
                  "واحد کالا",
                ),
              ),
              DataColumn(
                label: Text(
                  "تعداد",
                ),
              ),
              DataColumn(
                label: Text(
                  "تاریخ نیاز",
                ),
              ),
              DataColumn(
                label: Text(
                  "نام دسته",
                ),
              ),
              DataColumn(
                label: Text(
                  "توضیحات",
                ),
              ),
            ],
            rows: List<DataRow>.generate(
              5,
              (index) => DataRow(
                color: MaterialStateProperty.resolveWith<Color>(
                    (Set<MaterialState> states) {
                  if (states.contains(MaterialState.selected))
                    return Theme.of(context)
                        .colorScheme
                        .primary
                        .withOpacity(0.08);
                  if (index % 2 == 0) return Colors.grey.withOpacity(0.3);
                  return null; // Use default value for other states and odd rows.
                }),
                cells: List<DataCell>.generate(6, (index) {
                  return DataCell(Text('Row $index'));
                }),
                selected: selected[index],
                onSelectChanged: (bool value) {
                  setState(() {
                    selected[index] = value;
                  });
                },
              ),
            ),
          ),
        ),
      ),
```

**Comment by FtADev** [comment] 2020-09-22 06:45
I fixed that with adding `letterSpacing: 0,` to TextStyle!
```dart
DataColumn(
                label: Text(
                  "شرح کالا",
                  style: TextStyle(
                    letterSpacing: 0,
                  ),
                ),
              ),
```

![Screenshot from 2020-09-22 10-14-16](https://user-images.githubusercontent.com/29522746/93851158-7da15e00-fcbc-11ea-87fd-8ee2a6ae43e7.png)

**Comment by TahaTesser** [comment] 2020-09-22 06:55
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Directionality(
            textDirection: TextDirection.rtl,
            child: DataTable(
              columns: [
                DataColumn(
                  label: Text(
                    "شرح کالا",
                    // style: TextStyle(
                    //   letterSpacing: 0,
                    // ),
                  ),
                ),
                DataColumn(
                  label: Text(
                    "واحد کالا",
                    // style: TextStyle(
                    //   letterSpacing: 0,
                    // ),
                  ),
                ),
                DataColumn(
                  label: Text(
                    "تعداد",
                    // style: TextStyle(
                    //   letterSpacing: 0,
                    // ),
                  ),
                ),
                DataColumn(
                  label: Text(
                    "تاریخ نیاز",
                    style: TextStyle(
                      letterSpacing: 0,
                    ),
                  ),
                ),
                DataColumn(
                  label: Text(
                    "نام دسته",
                    // style: TextStyle(
                    //   letterSpacing: 0,
                    // ),
                  ),
                ),
                DataColumn(
                  label: Text(
                    "توضیحات",
                    // style: TextStyle(
                    //   letterSpacing: 0,
                    // ),
                  ),
                ),
              ],
              rows: List<DataRow>.generate(
                5,
                (index) => DataRow(
                  color: MaterialStateProperty.resolveWith<Color>(
                      (Set<MaterialState> states) {
                    if (states.contains(MaterialState.selected))
                      return Theme.of(context)
                          .colorScheme
                          .primary
                          .withOpacity(0.08);
                    if (index % 2 == 0) return Colors.grey.withOpacity(0.3);
                    return null; // Use default value for other states and odd rows.
                  }),
                  cells: List<DataCell>.generate(6, (index) {
                    return DataCell(Text('Row $index'));
                  }),
                  // selected: selected[index],
                  onSelectChanged: (bool value) {
                    // setState(() {
                    //   selected[index] = value;
                    // });
                  },
                ),
              ),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.281, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.281 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 511367aa5a (8 hours ago), 2020-09-21 15:33:32 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (3 available)            
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
      x86_64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by mdebbar** [comment] 2022-09-27 14:34
Duplicate of https://github.com/flutter/flutter/issues/71220

**Closed by mdebbar** 2022-09-27 14:34 UTC
Labels: framework, f: material design, a: internationalization, a: quality, a: typography, platform-web, has reproducible steps, P3, found in release: 1.22
