### ISSUE TITLE
window.padding does not work on Android 9 with a notch in full screen mode

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#28414] opened 2019-02-24 08:30 UTC
In full screen mode, `window.padding.top` is `0`.

in Android 9 with a notch.(Pixel 3XL, Android 9)
![image](https://user-images.githubusercontent.com/31621968/53296955-d7c40e00-3850-11e9-8b5a-72d992728862.png)

Iphone XR
![image](https://user-images.githubusercontent.com/31621968/53296977-38534b00-3851-11e9-8d49-abf182c9c951.png)

```
[✓] Flutter (Channel master, v1.2.3-pre.18, on Mac OS X 10.13.6 17G65, locale
    zh-Hans-CN)
    • Flutter version 1.2.3-pre.18 at /Volumes/资料/flutter/flutter
    • Framework revision e0c373b3eb (25 hours ago), 2019-02-23 02:03:28 -0500
    • Engine revision 1741497a57
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • Google Pixel 3 XL • 192.168.56.101:5555                  • android-x86 •
      Android 9 (API 28)
    • iPhone XR         • A9854F16-5C9A-4435-B5A5-26A76DD35A33 • ios         •
      iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-02-25 07:34
Possible duplicate of #27268

**Comment by zoechi** [comment] 2019-02-25 07:34
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by windrunner414** [comment] 2019-02-25 14:20
only ```SystemChrome.setEnabledSystemUiOverlays([SystemUiOverlay.bottom])```
and ```print(window.padding)``` in main.dart

in MainActivity.java, add this code to onCreate
```
WindowManager.LayoutParams lp = getWindow().getAttributes();
lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES; 
getWindow().setAttributes(lp);
```

and change the sdk version to 28
[simulate a notch on Android9](https://9to5google.com/2018/03/07/how-to-simulate-display-cutout-notch-android-p-developer-preview-1-android-basics/)

**Comment by markusaksli-nc** [comment] 2020-09-15 06:25
Hi @windrunner414 
Is this still an issue on the latest stable or master version of flutter?
Thank you

**Comment by markusaksli-nc** [comment] 2020-10-07 08:44
Closing this due to timeout.

I could not repro this when I tried. If the issue reproduces on the latest stable or master with your code, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I'll re-open.

Thank you.

**Closed by markusaksli-nc** 2020-10-07 08:44 UTC
Labels: engine, framework, waiting for customer response
