### ISSUE TITLE
packages have newer versions incompatible with dependency constraints

### ISSUE THREAD

**Issue by mauricev** [flutter/flutter#109977] opened 2022-08-22 04:13 UTC
## Steps to Reproduce

1. On a Mac, create a new project in Flutter in Android Studio using current flutter from flutter stable, 3.0.5

2. Run “flutter pub upgrade” being cd'ed into the project folder

3. It complains 
```
Resolving dependencies...
  async 2.8.2 (2.9.0 available)
  boolean_selector 2.1.0
  characters 1.2.0 (1.2.1 available)
  charcode 1.3.1
  clock 1.1.0 (1.1.1 available)
  collection 1.16.0
  cupertino_icons 1.0.5
  fake_async 1.3.0 (1.3.1 available)
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.1
  flutter_test 0.0.0 from sdk flutter
  lints 2.0.0
  matcher 0.12.11 (0.12.12 available)
  material_color_utilities 0.1.4 (0.2.0 available)
  meta 1.7.0 (1.8.0 available)
  path 1.8.1 (1.8.2 available)
  sky_engine 0.0.99 from sdk flutter
  source_span 1.8.2 (1.9.1 available)
  stack_trace 1.10.0
  stream_channel 2.1.0
  string_scanner 1.1.0 (1.1.1 available)
  term_glyph 1.2.0 (1.2.1 available)
  test_api 0.4.9 (0.4.13 available)
  vector_math 2.1.2 (2.1.3 available)
No dependencies changed.
13 packages have newer versions incompatible with dependency constraints.
```
How can a fresh project already have incompatible dependency constraints?

5. Then run flutter pub outdated. It says 
```
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current   Upgradable  Resolvable  Latest   

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies: 
characters                *1.2.0    *1.2.0      *1.2.0      1.2.1    
material_color_utilities  *0.1.4    *0.1.4      *0.1.4      0.2.0    
meta                      *1.7.0    *1.7.0      *1.7.0      1.8.0    
vector_math               *2.1.2    *2.1.2      *2.1.2      2.1.3    

transitive dev_dependencies:
async                     *2.8.2    *2.8.2      *2.8.2      2.9.0    
clock                     *1.1.0    *1.1.0      *1.1.0      1.1.1    
fake_async                *1.3.0    *1.3.0      *1.3.0      1.3.1    
matcher                   *0.12.11  *0.12.11    *0.12.11    0.12.12  
path                      *1.8.1    *1.8.1      *1.8.1      1.8.2    
source_span               *1.8.2    *1.8.2      *1.8.2      1.9.1    
string_scanner            *1.1.0    *1.1.0      *1.1.0      1.1.1    
term_glyph                *1.2.0    *1.2.0      *1.2.0      1.2.1    
test_api                  *0.4.9    *0.4.9      *0.4.9      0.4.13   
all dependencies are up-to-date.
```
If all dependencies are up to date, it seems confusing that it’s not letting me get the current versions.

6. Running “flutter pub cache repair” made no difference.

7. Some online queries report that running ”flutter packages pub run build_runner ” in the project folder helps. However, I get 
```
Could not find package "build_runner". Did you forget to add a dependency?
pub finished with exit code 65
```

 8. I have also seen being asked to run “dart pub deps -s list” This says
 ```
Could not find a file named "pubspec.yaml" in "/Users/maurice/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0".
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /Users/maurice/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurice/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Volumes/backuphd/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 72277DA9-1568-4539-85BC-058A1F40B58D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment] 2022-08-22 12:57
Hello @mauricev. This is expected as package authors release new versions of packages. Flutter would upgrade these dependencies in newer stable versions as time goes on. But Flutter's release schedule doesn't allow it to have all the latest versions of all the packages at the current time. It's normal for this to happen, even with packages you've added to your own project. As a project becomes larger, you may not have the liberty of always using the latest package without breaking something somewhere. 

Since is not a bug, I am closing this issue. If you disagree, please comment and we can reopen it. Thank you.

**Closed by exaby73** 2022-08-22 12:57 UTC
Labels: in triage
