### ISSUE TITLE
iOS: Flutter run hangs on "syncing files to device"

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#70138] opened 2020-11-09 22:23 UTC
For many months I've had a problem where, when deploying to a physical iPhone, the deployment process hangs at "syncing files to device". The app is deployed and launched, but displays a blank screen.

Sometimes if I wait for literally multiple minutes, the process will complete and I can use the app. Sometimes the process never seems to complete.

This occurs pretty much every time when I run through Android Studio. It also occurs most of the time when I use `flutter run` from the command line.

The issue does not occur on an iOS simulator, Android emulator, or a physical Android device.

Flutter version:
```
Flutter 1.22.0-10.0.pre.9 • channel master • git@github.com:flutter/flutter.git
Framework • revision 8fa5c55e54 (2 months ago) • 2020-08-30 19:05:20 -0700
Engine • revision 1e302a111d
Tools • Dart 2.10.0 (build 2.10.0-76.0.dev)
```

**Comment by matthew-carroll** [comment] 2020-11-09 22:23
CC @xster @jmagman @gaaclarke

**Comment by gaaclarke** [comment] 2020-11-09 22:37
Duplicate of https://github.com/flutter/flutter/issues/65402

The problem was devfs would be waiting for a status code for an http request that would never come.  Then after a 4 minute timeout it would try again and succeed.  The underlying Dart issue hasn't been resolved, but the timeout shouldn't be 4 minutes anymore.  I'm not sure of the latest state but the timeout had to be chosen to accomodate everyone.  I had it locally set to 500ms and everything worked fine for me with the gallery.

**Closed by gaaclarke** 2020-11-09 22:37 UTC
Labels: platform-ios

**Comment by matthew-carroll** [comment] 2020-11-09 22:39
@gaaclarke is it a duplicate if I'm on iOS 13.6.1?

**Comment by gaaclarke** [comment] 2020-11-09 22:42
@matthew-carroll yep, we saw it on both iOS 13 and 14.  I think there might have been speculation that it was iOS 14 early on.

**Comment by gaaclarke** [comment] 2020-11-09 22:44
Sorry, this is the issue I meant to link: https://github.com/flutter/flutter/issues/63869

**Comment by matthew-carroll** [comment] 2020-11-09 22:46
@gaaclarke Cool, thanks. Is there a post somewhere about how I can adjust my local refresh time to 500ms? Also, that issue says it was fixed in 1.22. I'm not sure which version exactly that was, but I'm on 1.22.0-10.0.pre.9

**Comment by gaaclarke** [comment] 2020-11-09 22:51
I explained it somewhere, I can't remember where.  Here's the diff to change it:
```diff
--- a/packages/flutter_tools/lib/src/devfs.dart
+++ b/packages/flutter_tools/lib/src/devfs.dart
@@ -300,7 +300,7 @@ class _DevFSHttpWriter implements DevFSWriter {
         // (https://github.com/dart-lang/sdk/issues/43525).
         try {
           final HttpClientResponse response = await request.close().timeout(
-            const Duration(seconds: 60));
+            const Duration(milliseconds: 500));
           response.listen((_) {},
             onError: (dynamic error) {
               _logger.printTrace('error: $error');
```

**Comment by developeranshul1986** [comment] 2020-11-19 11:32
I am building the app in Flutter Stable Version 1.22.4 and running the app in simulator iOS 13.6 and white screen stick issue persist.

Please help on this as it needed urgent
