### ISSUE TITLE
ImagePicker.pickImage(source: ImageSource.gallery) returns null

### ISSUE THREAD

**Issue by ArtfulDodgerB92** [flutter/flutter#54579] opened 2020-04-12 06:09 UTC
## Steps to Reproduce

Create a flutter app.    Try and use the most basic functionality of the image_picker plugin.

**Expected results:** 

When you select an image from the gallery, it should return something to your application.   A file, or location.   Anything really.

**Actual results:**

Nothing.  The gallery launches.   You select an image.   Gallery goes away, nothing is returned to the app at all.   Just leaves null.

**My code**

```
Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    customImageFile = image.toString();
    print('customImageFile: ' + customImageFile);
}
```

**Output from code**

`customImageFile: null`

**Plugin Version**

image_picker: 0.6.5

**Flutter doctor**

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.1098], locale en-AU)
    • Flutter version 1.12.13+hotfix.5 at c:\flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Installations\AndroidSDK\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Installations\AndroidSDK\
    • Java binary at: C:\Installations\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Installations\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G970F • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by exptk3** [comment] 2020-04-12 10:34
Me too. 
There is a bug : images are not selected on Android 10 devices.

**Comment by SempaiEcchi** [comment] 2020-04-12 12:34
Inside your **stateful** widget you need an object for example

  File _image;

and then
 
  Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      _image = image;
    });
  }

**Comment by ArtfulDodgerB92** [comment] 2020-04-13 02:27
Already got this mate, and it makes no difference.   I have even tried that "retrieve lost data" crap, also nothing.  This is a fundamental flaw in the code of this plugin.  It simply doesn't work, and it is looking very much like we need a dev to look at what they have done and correct their mistakes.

```
class SinglePlayerMode extends StatefulWidget {
  @override
  SinglePlayerModeParentState createState() => SinglePlayerModeParentState();
}

class SinglePlayerModeParentState extends State<SinglePlayerMode> {

File _imageFile;

Future<File> getImage(ImageSource source) async {
    File image = await ImagePicker.pickImage(source: source);

    setState(() {
      _imageFile = image;
    });

    if (image == null) {
      await retrieveLostData();
      customImageFile = _imageFile.toString();
      print('retrieved file: ' + customImageFile);
    }
    customImageFile = image.toString();
    customImageFile2 = _imageFile.toString();
   print('customImageFile: ' + customImageFile);
   print('customImageFile2: ' + customImageFile2);
}

  Future<void> retrieveLostData() async {
    final LostDataResponse response = await ImagePicker.retrieveLostData();
    if (response.isEmpty) {
      return;
    }
    if (response.file != null) {
        setState(() {
          _imageFile = response.file;
        });
      } else {
      _retrieveDataError = response.exception.code;
      print('RETRIEVE ERROR: ' + _retrieveDataError);
    }
  }
```

Everything results in null.   This was all working perfectly until the latest flutter updates.  Every time there is a flutter update, they have done something fundamentally stupid in the backend, and release to the "stable" channel a whole mess of bad code and breaks.   exptk3 is likely correct in his comment above.   I can't verify as I have nothing else to test on, but they have likely done something dumb with regards to the code differences for Android 10 devices, or something similar.

**Comment by VladyslavBondarenko** [comment] 2020-04-13 13:35
Hi @ArtfulDodgerB92 
is https://github.com/flutter/flutter/issues/53514 your case?
or you are receiving null not only when picking from recent?

**Comment by nirajjoshi** [comment] 2020-04-13 13:47
Having similar issue.

Nokia 7.2 Android 10

Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.

**Comment by ArtfulDodgerB92** [comment] 2020-04-13 23:11
> Hi @ArtfulDodgerB92
> is #53514 your case?
> or you are receiving null not only when picking from recent?

Hi mate, thank you for your reply.    It is always null, no matter what I pick.  I know some of the images I am trying have been working in this application for over a year.    An update to Flutter and Image_Picker has broken this.

**Comment by VladyslavBondarenko** [comment] 2020-04-14 07:38
@ArtfulDodgerB92 
I tried the last version `image_picker 0.6.5` with code sample from https://pub.dev/packages/image_picker#-example-tab- 
It's working with Android 10 emulator (tried latest stable `v1.12.13+hotfix.9` and latest dev `1.18.0-dev.5.0`). @TahaTesser tried the same but with his Android 10 device, not emulator, and he can pick an image as well.
Could you try if you are experiencing this with later than `v1.12.13+hotfix.5` flutter version?
are you experiencing this with some of the previous version of `image_picker`?

**Comment by ArtfulDodgerB92** [comment] 2020-04-14 14:01
Thanks, @VladyslavBondarenko 

Here is my flutter doctor output:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.1098], locale en-AU)
    • Flutter version 1.12.13+hotfix.5 at c:\flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Installations\AndroidSDK\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Installations\AndroidSDK\
    • Java binary at: C:\Installations\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Installations\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G970F •  android-arm64 • Android 10 (API 29)
```

I started with image_picker 0.6.5 which didn't work at all.   I then started rolling back:
0.6.4
0.6.3+4

That's as far as I have got so far, there isn't really any way of knowing which versions have been tested on which flutter builds, but the fact you said 0.6.5 in your response tells me that was probably the right version to begin with.     I can keep trying to roll back over and over to retest, but it could be likely the flutter devs have done something stupid again.   Just not sure what to do from here, there must be a simple reason why it doesn't return any data.   It will be a small error in one line of backend code, I can almost feel it!

**Comment by ettiennelr** [comment] 2020-04-19 17:15
getting the same issue since upgrading to android 10

ImagePicker.pickImage(source: ImageSource.gallery always returns null

**Comment by ArtfulDodgerB92** [comment] 2020-04-26 03:10
Are we getting anywhere with this one?   Kind of need this to be able to work on Android 10.    Lots of devices run this platform.

**Comment by ettiennelr** [comment] 2020-04-29 17:45
what the eta on this fix?

**Comment by marcolazzara** [comment] 2020-05-11 10:48
> @ArtfulDodgerB92
> I tried the last version `image_picker 0.6.5` with code sample from https://pub.dev/packages/image_picker#-example-tab-
> It's working with Android 10 emulator (tried latest stable `v1.12.13+hotfix.9` and latest dev `1.18.0-dev.5.0`). @TahaTesser tried the same but with his Android 10 device, not emulator, and he can pick an image as well.
> Could you try if you are experiencing this with later than `v1.12.13+hotfix.5` flutter version?
> are you experiencing this with some of the previous version of `image_picker`?

Me too. 
Channel stable, v1.12.13+hotfix.5, on Linux, locale it_IT.UTF-8)
image_picker 0.6.5

It work both on Android 10 emulator and real devices.


Tks!!!

**Comment by nirajjoshi** [comment] 2020-05-11 12:31
> Having similar issue.
> 
> Nokia 7.2 Android 10
> 
> Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.



> Having similar issue.
> 
> Nokia 7.2 Android 10
> 
> Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.

It seems like, with use of latest version of this lib everything works fine on Android 10.
Updated to latest version **image_picker 0.6.6+1** & no more issues.

**Comment by marcolazzara** [comment] 2020-05-11 13:04
> > Having similar issue.
> > Nokia 7.2 Android 10
> > Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.
> 
> > Having similar issue.
> > Nokia 7.2 Android 10
> > Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.
> 
> It seems like, with use of latest version of this lib everything works fine on Android 10.
> Updated to latest version **image_picker 0.6.6+1** & no more issues.

With 0.6.6+1 It doesn't work for me. It work only on emulator.
No reason for that.

Wich flutter version  Do you have?

**Comment by nirajjoshi** [comment] 2020-05-11 13:08
> > > Having similar issue.
> > > Nokia 7.2 Android 10
> > > Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.
> > 
> > 
> > > Having similar issue.
> > > Nokia 7.2 Android 10
> > > Able to pick image from Gallery. However when choose image from **Recent**, it doesn't pick image & returns null.
> > 
> > 
> > It seems like, with use of latest version of this lib everything works fine on Android 10.
> > Updated to latest version **image_picker 0.6.6+1** & no more issues.
> 
> With 0.6.6+1 It doesn't work for me. It works only on emulator.
> No reason for that.
> 
> Wich flutter version Do you have?

Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G103, locale en-IN)

**Comment by VladyslavBondarenko** [comment] 2020-05-11 14:46
@marcolazzara does it persist with the current stable v1.17.0? 
if yes, with what device are you experiencing this? 
is image not picked only from recent, or from any gallery dir?

**Comment by marcolazzara** [comment] 2020-05-11 17:37
> @marcolazzara does it persist with the current stable v1.17.0?
> if yes, with what device are you experiencing this?
> is image not picked only from recent, or from any gallery dir?

Hi,

can't answer now because my app is in production so I can't upgrade.
Hope tomorrow to update on 1.17.0 with latest image_picker version.

BTW First time at all when I choose a picture, image picker fails returning to the app.
After that it's perfect.

**Comment by uzumaki258** [comment] 2020-05-18 00:27
The same with this issue:
https://github.com/flutter/flutter/issues/54947

**Comment by uzumaki258** [comment] 2020-05-18 00:31
> > @ArtfulDodgerB92
> > I tried the last version `image_picker 0.6.5` with code sample from https://pub.dev/packages/image_picker#-example-tab-
> > It's working with Android 10 emulator (tried latest stable `v1.12.13+hotfix.9` and latest dev `1.18.0-dev.5.0`). @TahaTesser tried the same but with his Android 10 device, not emulator, and he can pick an image as well.
> > Could you try if you are experiencing this with later than `v1.12.13+hotfix.5` flutter version?
> > are you experiencing this with some of the previous version of `image_picker`?
> 
> Me too.
> Channel stable, v1.12.13+hotfix.5, on Linux, locale it_IT.UTF-8
> image_picker 0.6.5
> 
> It works both on Android 10 emulator and real devices.
> 
> Tks!!!
> 
> EDIT: It doesn't work with image_picker > 0.6.5

Could you please try with a fresh emulator? (Create new emulator then run the app with it)
Thank you

**Comment by pedromassangocode** [comment] 2021-02-08 14:22
Hi @ArtfulDodgerB92 
I cannot reproduce the issue with the latest version of the plugin.

![gif](https://user-images.githubusercontent.com/67424416/107231886-1ee94080-6a21-11eb-8b9c-9ef0a23640b4.gif)


Please upgrade and try again. 

Closing this as fixed. If the issue persists, just write in the comments bellow by providing your `flutter doctor -v`, and your `pubspec.yaml`.
Thank you

**Closed** 2021-02-08 14:22 UTC
Labels: customer: crowd, p: image_picker, platform-android, plugin
