### ISSUE TITLE
TextSelectionThemeData add selectedTextColor to change color of part of text that is selected

### ISSUE THREAD

**Issue by jakusb** [flutter/flutter#151316] opened 2024-07-04 15:25 UTC
### Use case

TextSelectionThemeData add selectedTextColor to change color of part of text that is selected
It is NOT possible to change the textColor for just the text(part) that is selected.
There is no distinction between selected and unselected text.
This makes it very annoying and ugly in many cases where text is selected with a selectionColor that is close the de textColor.

### Proposal

Please add a new property selectedTextColor to TextSelectionThemeData that changes the color of the foreground color of any selected character.
![image](https://github.com/flutter/flutter/assets/9477833/5d444007-0ace-4a0b-8e24-91f60ba8011b)
See image. The 's is a test' part should get a light color, something like white for example.

**Comment by Renzo-Olivares** [comment] 2024-07-11 22:40
Closing as a duplicate of https://github.com/flutter/flutter/issues/99231 , please re-open if this is not the case.

**Closed by Renzo-Olivares** 2024-07-11 22:40 UTC
Labels: c: new feature, framework, f: material design, c: proposal, P2, team-text-input, triaged-text-input
