### ISSUE TITLE
Mac web_tool_tests failing on some machines with malformed cached chrome cipd package

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#99372] opened 2022-03-02 03:06 UTC
As part of upgrading the Chrome package in https://github.com/flutter/flutter/issues/98278, a Chromium cipd package `G-lZgp8TuOPH0ndPr62HLAzRTWcFV3RRvFjOYyPZq_4C` was uploaded that was malformed somehow that `flutter` couldn't detect the browser as a valid device.  A new one was uploaded today that tests passed with.

The engine roll https://github.com/flutter/flutter/pull/99362 failed on a `Mac web_tool_tests` with a cache hit with the malformed package:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20web_tool_tests/12828/overview

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8820852491161740497/+/u/Chrome_and_driver_dependency/ensure_installed/stdout
```
[P19159 15:21:32.857 action_plan.go:160 I] In root:
[P19159 15:21:32.857 action_plan.go:172 I]   to update:
[P19159 15:21:32.857 action_plan.go:174 I]     flutter_internal/browsers/chrome/mac-amd64 (Qe3INUxKmaLOB1bDUu7ZD8otihLlr3k4mFVuFq8R97kC -> G-lZgp8TuOPH0ndPr62HLAzRTWcFV3RRvFjOYyPZq_4C)
[P19159 15:21:32.857 instancecache.go:187 I] Using instance cache at /opt/s/cipd_cache/cache/instances
[P19159 15:21:32.858 instancecache.go:409 I] [fetch] Cache hit for flutter_internal/browsers/chrome/mac-amd64:G-lZgp8TuOPH0ndPr62HLAzRTWcFV3RRvFjOYyPZq_4C
[P19159 15:21:32.860 deployer.go:294 I] [unzip] Deploying flutter_internal/browsers/chrome/mac-amd64:G-lZgp8TuOPH0ndPr62HLAzRTWcFV3RRvFjOYyPZq_4C into /opt/s/w/ir/cache/chrome/chrome(/)
```

Malformed:
https://chrome-infra-packages.appspot.com/p/flutter_internal/browsers/chrome/mac-amd64/+/G-lZgp8TuOPH0ndPr62HLAzRTWcFV3RRvFjOYyPZq_4C

Correct:
https://chrome-infra-packages.appspot.com/p/flutter_internal/browsers/chrome/mac-amd64/+/BlBCql9ZngKYkn_tiqUUCnZKtZtbbCnsP0RgmLIn2ZwC

Does `build843-m9` need its chrome cache cleared?  Do any other builders have the wrong one cached?

Here's one that's passing that used `BlBCql9ZngKYkn_tiqUUCnZKtZtbbCnsP0RgmLIn2ZwC` https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/5090?

**Comment by godofredoc** [comment] 2022-03-02 03:18
This is strange, cipd talks to the server to resolve the hash for the tag and then downloads it or reuse the one from the cache with the correct hash.

**Comment by jmagman** [comment] 2022-03-02 03:30
Wonder how it got version 98 then since you merged that after the cipd package was fixed.
Feel free to close if this is no longer an issue.

**Comment by godofredoc** [comment] 2022-03-02 03:33
yeah, just checked and I landed the cipd package update at 1:00:00 PM PST

**Comment by jmagman** [comment] 2022-03-02 21:20
More recent failures:
https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/12857 https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/12852 https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/12850
https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/12849

https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests

**Comment by godofredoc** [comment] 2022-03-02 22:39
@CaseyHillers is this bug on your radar?

**Comment by CaseyHillers** [comment] 2022-03-02 22:54
This sounds like a common issue occurring in the mac bots. I'm going to do a cleanup of impacted bots, but do tell me if it's a larger impact.

Related issue: https://github.com/flutter/flutter/issues/99429

**Comment by CaseyHillers** [comment] 2022-03-03 01:09
As FYI, my corp machines lacks permissions to access our mac minis. I'm debugging the cert issues, but no progress.

If there's no updates, I'll reach out to the chrome labs team to get help tomorrow morning.

**Comment by godofredoc** [comment] 2022-03-03 04:08
Cleaned the caches of all the machines with failures.

**Comment by CaseyHillers** [comment] 2022-03-03 21:44
Based on https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests - This is having a large impact on our fleet with an 80% failure rate

**Comment by godofredoc** [comment] 2022-03-03 21:56
Let's add another tag `version:98.1` to the cipd package and update the references. Turns out that deleting tags is a bad idea as they are locally cached by cipd.

**Comment by CaseyHillers** [comment] 2022-03-04 17:47
Closing as this seems fixed with the revving chrome.

PRs in https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests are passing if they're rebased with the latest changes. Please re-open if this is still occurring on new PRs

**Comment by CaseyHillers** [comment] 2022-03-07 19:13
We should manually wipe the cipd caches of these bots

**Comment by godofredoc** [comment] 2022-03-18 16:52
Turns out this was caused by web_engine and adhoc tests using an incorrect version of the xcode module. It was fixed here: https://flutter-review.googlesource.com/c/recipes/+/28064

**Closed by godofredoc** 2022-03-18 16:52 UTC
Labels: team: infra, passed secondary triage, P1
