### ISSUE TITLE
Flutter Hot Restart is broken. App crashes on hot restart.

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#18339] opened 2018-06-10 10:22 UTC
This is the log generated after the crash.

```
[0x000000010716b28c] dart::ClassFinalizer::FinalizeClass(dart::Class const&)
[0x00000001074c8d8d] dart::Compiler::CompileClass(dart::Class const&)
[0x000000010721514d] dart::Class::EnsureIsFinalized(dart::Thread*) const
[0x00000001071af92c] dart::Debugger::FindBestFit(dart::Script const&, dart::TokenPosition, dart::TokenPosition, dart::Function*)
[0x00000001071afa7b] dart::Debugger::SetBreakpoint(dart::Script const&, dart::TokenPosition, dart::TokenPosition, long, long)
[0x00000001071b0362] dart::Debugger::BreakpointLocationAtLineCol(dart::String const&, long, long)
[0x00000001071b03fe] dart::Debugger::SetBreakpointAtLineCol(dart::String const&, long, long)
[0x000000010735c46d] dart::AddBreakpointCommon(dart::Thread*, dart::JSONStream*, dart::String const&)
[0x0000000107351d3a] dart::AddBreakpointWithScriptUri(dart::Thread*, dart::JSONStream*)
[0x000000010734f86e] dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
[0x000000010734fe7a] dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
[0x00000001071d006b] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
[0x00000001071fb2fe] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
[0x00000001071fb556] dart::MessageHandler::HandleOOBMessages()
[0x00000001074dfef6] Dart_HandleServiceMessages
[0x000000010702b8b3] tonic::DartMessageHandler::OnHandleMessage(tonic::DartState*)
[0x0000000106cbc1e2] fml::MessageLoopImpl::RunExpiredTasks()
[0x0000000106cbeeda] fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
[0x0000000109787e64] __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
[0x0000000109787a52] __CFRunLoopDoTimer
[0x000000010978760a] __CFRunLoopDoTimers
[0x000000010977ee4c] __CFRunLoopRun
[0x000000010977e30b] CFRunLoopRunSpecific
[0x0000000106cbf02b] fml::MessageLoopDarwin::Run()
[0x0000000106cbc319] fml::MessageLoopImpl::DoRun()
[0x0000000106cbea30] std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*)
[0x000000010e9f9661] _pthread_body
[0x000000010e9f950d] _pthread_body
Lost connection to device.
[0x000000010e9f8bf9] thread_start
-- End of DumpStackTrace
Exited (sigterm)
```

**Comment by iampawan** [comment] 2018-06-10 10:35
Flutter version - 0.5.3-pre.20. It was happening in the previous version too.

**Comment by Kartik1607** [comment] 2018-06-10 14:07
@iampawan Are you adding a new variable and initializing in the onInit?

**Comment by iampawan** [comment] 2018-06-10 14:18
I don't know why it is showing that breakpoint line but I didn't have any
active breakpoint as far as i remember. And I haven't override onInit() as
well.

**Comment by jpgilchrist** [comment] 2018-06-12 17:52
This is occurring for me as well. I had a project that I hadn't had the chance to work on in about a week. Came back to it and ran `flutter upgrade`. Now when trying to do anything with hot reload or hot restart it either fails silently (hot reload) or crashes and says "lost connection to device" (hot restart). 

This is occurring from both IntelliJ and cli `flutter run`

**Comment by jpgilchrist** [comment] 2018-06-13 18:13
So, I was playing with `flutter run` and it turns out if you use "R" to hot restart it actually works. However, if at any time you use "r" to hot reload it just doesn't work. Then, if you subsequently hit "R" after "r" it crashes with "device lost connection".

**Comment by jpgilchrist** [comment] 2018-06-15 15:29
@iampawan  @mraleph This actually appears to be fixed in IntelliJ and cli with latest upgrade. Probably can be closed.

**Comment by iampawan** [comment] 2018-06-17 03:58
@jpgilchrist I'll check it and close it. Can you tell me the version?

**Comment by iampawan** [comment] 2018-06-17 04:13
I also do think it's fixed. So, closing this issue.

**Comment by mohith7548** [comment] 2018-07-03 16:03
Sorry for reply to this closed thread. The problem still persists. ie., When the app is "Hot restarted" previous version of the app is built. I don't understand why this is happening in Flutter. Please Fix this issue soon. Because We Love #Flutter

**Comment by zoechi** [comment] 2018-07-03 16:34
@mohith7548 I have the suspicion that this is happening when you edit a file and without saving click the hot-restart button. When you explicitly save before pressing hot-restart it works (at least more often than otherwise). 
I'm not yet too sure about this because there seem to be other problems as well and it's not too reliable to reproduce. 
But worth a try pressing Ctrl+s before hot-reload.

**Comment by zoechi** [comment] 2018-08-21 06:35
@iampawan 
Please add the output of `flutter doctor -v`.

**Comment by iampawan** [comment] 2018-08-24 09:32
Moved to the different branch and fixed

**Comment by vinicioslc** [comment] 2018-11-15 12:17
Im getting this issue too...
The flutter VM from all my phones sometimes doesn't respond to refresh request needing to do a fully restart or rebuild the application. this issue starts with me at this month (november)
```
Flutter doctor -v
Waiting for another flutter command to release the startup lock...
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [versÃ£o 10.0.17134.407], locale pt-BR)
    • Flutter version 0.11.3 at C:\Users\AcheiFarmacias\AppData\Local\Android\flutter
    • Framework revision 72bf075e8d (5 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\AcheiFarmacias\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.29.0)
    • VS Code at C:\Users\AcheiFarmacias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • Redmi 4X • 0123456789ABCDEF • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-21 10:01
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Closed by zoechi** 2019-02-21 10:01 UTC
Labels: severe: crash, tool
