### ISSUE TITLE
Support Error Boundaries

### ISSUE THREAD

**Issue by shrugs** [flutter/flutter#26965] opened 2019-01-23 15:56 UTC
# Error Boundaries

## Description
Developers would like to catch errors that occur during `build` in order to provide subtree-dependent error handling. Currently, the only available UI error handling is `FlutterError.onError`, which doesn't provide information on _which_ subtree had thrown the error; only that an error was thrown during build.

## Use Case
A specific use-case: imagine a widget, `Query` that understands how to fetch a stream of data (from a remote store or cache) and render its children with that concrete data. If the `Query` widget fetches data from an incomplete cache, it could render the child with `null` in cases where the child might expect a value (ex: `Text(user.name)`). In an ideal situation, the error thrown while building that context can be caught by the parent `Query` widget, which would then render something else (like a loading state) while attempting to re-fetch the data from the remote, without having that UI error bubble up.

## Reference

https://reactjs.org/docs/error-boundaries.html

**Comment by zoechi** [comment] 2019-01-23 16:06
I think this is a duplicate of #19993 
and I'm closing for the same reason https://github.com/flutter/flutter/issues/19993#issuecomment-420768814

**Closed by zoechi** 2019-01-23 16:06 UTC

**Comment by Tbhesswebber** [comment] 2020-05-04 19:48
It seems to me that this is _not_ a duplicate of #19993, which was about having widgets that essentially manage the rendering flow.  Realistically, we shouldn't need a specialized component for it, but a lifecycle method on stateful components with something that parallels the `componentDidCatch` method provided by React.

This allows us to address a number of issues, including sending logs about errors, conditionally rendering a component while attempting to rebuild the problematic subtree, etc.  In order for developers to truly isolate subdomains within an application, we need a way to manage errors within any given scope and in order for us to gain insights about our applications, we need to be able to tap into the error handling process in a meaningful, maintainable, and scoped way.

If "x" fails, crash the whole shebang, if "y" fails, check to see if the information made it to the server before redirecting or rendering a clean subtree, if "z" fails, send a log that someone did something uncouth.
