### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software., errno = 225

### ISSUE THREAD

**Issue by mhdkadi** [flutter/flutter#102441] opened 2022-04-23 14:53 UTC
## Command
```
flutter build apk --no-tree-shake-icons --obfuscate --split-debug-info=./ProjectFolderName/debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
, errno = 225
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:71:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:315:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:314:5)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:471:13)
<asynchronous suspension>
#7      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
<asynchronous suspension>
#8      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:112:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 2.10.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM A205F (mobile) • R58M361JGKH • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.18362.30]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
### Plugins
awesome_notifications-0.7.0-beta.2
better_player-0.0.81
connectivity_plus-2.2.1
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
device_info_plus-3.2.2
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.2
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
firebase_core-1.13.1
firebase_core_web-1.6.1
firebase_messaging-11.2.10
firebase_messaging_web-2.2.9
in_app_update-3.0.0
objectbox_flutter_libs-1.4.1
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.3.0
video_player_android-2.3.0
video_player_avfoundation-2.3.0
video_player_web-2.0.7
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by aloysiousBenoy** [comment] 2022-04-23 19:00
My guess is that the anti-virus on your system is causing this issue because it could not verify some file being generated... try disabling that?? ( at your own risk)

**Comment by danagbemava-nc** [comment] 2022-04-25 10:03
Related to https://github.com/flutter/flutter/issues/61997

**Comment by christopherfujino** [comment] 2022-04-25 16:16
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/61997. Please see that issue for more information on working around this issue. Thanks!

**Closed by christopherfujino** 2022-04-25 16:16 UTC
Labels: severe: crash, tool
