### ISSUE TITLE
[linux] Support Wayland in GTK embedding

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#57932] opened 2020-05-25 09:08 UTC
## Proposal

I think that it is necessary to support Wayland someday. Therefore, I'd like to propose that. I know that you are currently working on GTK support. I also want to contribute to Linux support activities. If there is an issue that I can handle, I will handle it.

**Comment by iapicca** [comment] 2020-05-25 09:34
Hi @HidenoriMatsubayashi 
I see there's an open [issue](https://github.com/flutter/flutter/issues/41724) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jbg** [comment] 2020-06-03 11:48
The linked issue doesn't appear to have anything to do with this issue.

This issue is about targeting Wayland (allowing a Flutter app to run on a Linux system with Wayland). The linked issue is about PlatformView, which relates to embedding a native view *inside* a Flutter app.

Please re-open this issue.

**Comment by HidenoriMatsubayashi** [comment] 2020-06-03 13:10
@iapicca @jbg 

I'm sorry for late reply. I agree with @jbg's opinion. I think it is necessary to support Wayland protocol as well in the future. Current shell (GTK) seems to support X11 only.

In addition, for example, for embedded devices with ARM 64-bit CPU such as IoT products, it is supported Wayland supported (no GTK and X11). I think Flutter is also the best UI frameworks for IoT products using Linux. I am very interested in Flutter.

**Comment by jbg** [comment] 2020-06-04 05:59
Thanks for re-opening! I'm planning on doing some experiments with getting the Linux desktop embedder to run on Wayland in the coming days. Does anyone know of any existing work in this area?

**Comment by HidenoriMatsubayashi** [comment] 2020-06-04 06:09
I have already tried and I have completed a simple check Flutter run on Wayland. But I think it is good to support Wayland after the current GTK shell tasks are completed.

**Comment by jbg** [comment] 2020-06-04 06:29
Can you link some of the related issues if you know them?

**Comment by stuartmorgan** [comment] 2020-06-09 19:36
> Current shell (GTK) seems to support X11 only. Wayland is a next generation window manager.
> 
> In addition, for example, for embedded devices with ARM 64-bit CPU such as IoT products, it is ofen supported Wayland (no GTK and X11).

Adding Wayland support to the GTK embedding and having a completely new, non-GTK-based, raw Wayland embedder are two extremely different things. Which are you proposing here?

**Comment by HidenoriMatsubayashi** [comment] 2020-06-10 06:32
I'm sorry for confusing you. This proposal (issue) is Wayland support to the GTK embedding in the future. FYI, in Fedora Workstation 31 Wayland is enabled by default.

> having a completely new, non-GTK-based

By the way, I am working on that as well. Flutter is great because it makes it easy to develop and create a GUI similar to a smartphone on the IoT devices. 

Furthermore, I've already confirmed that Flutter works on Jetson Nano and Raspberry Pi 4 with ARM64 CPU.

**Comment by stuartmorgan** [comment] 2020-06-28 23:55
Since the GLFW version actually already worked under Wayland, updating labels to reflect that this is a regression.

**Comment by ZeroCool2u** [comment] 2020-07-09 01:53
Is there anyway to contribute to the effort of getting Wayland support back? Any list of issues I can work on?

**Comment by stuartmorgan** [comment] 2020-07-09 02:37
This is the only issue related to wayland support.

**Comment by ZeroCool2u** [comment] 2020-07-09 14:24
Sorry, I'm just trying to understand if there's anything else that needs to be done that I might be able to help with or is the work done by @wmww sufficient to complete support?

**Comment by stuartmorgan** [comment] 2020-07-09 14:48
> is the work done by @wmww sufficient to complete support?

I don't know what work you're referring to; I haven't seen any PRs submitted for review for Wayland support.

@robert-ancell Have you looked at Wayland at all, or would it be useful for someone to implement a Wayland FlRenderer variant?

**Comment by ZeroCool2u** [comment] 2020-07-09 15:14
@stuartmorgan You're right, there's no PR. Sorry for the confusion. I just saw this issue was mentioned by [this commit](https://github.com/wmww/flutter_engine/commit/bcb7fb5e82eadde4155455dccb7254b2de32838f). I noticed that William is a Canonical employee, so that seemed like perhaps that's the start of some official work?

**Comment by wmww** [comment] 2020-07-09 16:40
I am indeed currently working on it with Robert. It's not quite ready to PR yet, but hopefully will be soon.

**Comment by xpat** [comment] 2020-07-10 22:52
I'm getting the same error reported in issues #60339, #60032, #61125 and looking for a solution or work-around.  @domesticmouse @stuartmorgan @nicocarbone 

How I would use the idea by @BobEvans :

> Note: If I run the Flutter linux app in an environment with GDK_BACKEND=x11 then it works. (In Gnome 3 - with Wayland).

I'm using an HP Chromebook with Linux beta, Chrome Version 83.0.4103.112 (Official Build) (64-bit), running the command: $flutter run -d linux
from bash terminal

`Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

(counter:32632): Gdk-WARNING **: 18:17:06.602: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is not a native X11 window

** (counter:32632): WARNING **: 18:17:06.819: Failed to start Flutter engine: Failed to create EGL surface: Bad Native Window
`

**Comment by stuartmorgan** [comment] 2020-07-10 23:08
The simplest workaround would be to add [this change](https://github.com/flutter/flutter/pull/60654/files) to your main.cc. Once Wayland is supported, you'd need to take it out again.

**Comment by xpat** [comment] 2020-07-10 23:49
@stuartmorgan Thanks a million. That worked. 

Two days ago I read about Flutter on Linux desktop.  First I ran into trouble with the Linux Toolchain -- I had none of the requirements -- not clang, nor ninja, etc. I had a rotten time installing clang (until I install aptitude and added it that way).  Finally I thought it would work but it didn't because of this Bad Native Window problem.  So 48 hours later I finally got something to work (the counter example) running the command: flutter run -d linux.  

Thanks again!

**Comment by jwinarske** [comment] 2020-08-11 00:49
@HidenoriMatsubayashi There has been a way to build the engine as a generic library aka "embedder" for a number of years now where you need to add-on your own shell.  I have an example of this [here](https://github.com/jwinarske/flutter_wayland) and [here (yocto layer)](https://github.com/jwinarske/meta-flutter).  

Given a GLFW Shell is supported in the Engine repo, why not fork GLFW and augment it's Wayland support to suite your needs?

**Comment by stuartmorgan** [comment] 2020-08-11 01:32
@jwinarske This issue is tracking Wayland support in the GTK embedding.

**Closed** 2020-10-21 20:38 UTC
Labels: P3, a: desktop, customer: crowd, e: embedder, engine, platform-linux, severe: regression
