### ISSUE TITLE
Deferred Components for iOS, to speed up flutter engine's start

### ISSUE THREAD

**Issue by Sunyandong-CS** [flutter/flutter#87987] opened 2021-08-10 11:54 UTC
## Use case

same as Deferred Components used in android

## Proposal

I wonder if there has any posibility to support “Deferred Components” for iOS。so we can use "deferred" key word to build App.framework seprately，and we can start engine qickly with only part of frameworks。

**Comment by TahaTesser** [comment] 2021-08-10 12:05
Hi @Sunyandong-CS 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/79327
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-10 12:05 UTC
Labels: in triage
