### ISSUE TITLE
flutter build/install/run developer experience is confusing

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4497] opened 2016-06-09 19:33 UTC
Normally I like to do something like this on the command line:

```
(cd <my app path> && flutter build apk && flutter install && flutter run)
```

The problem is the app that gets installed isn't the one that's run such that if I launch my app via the command above I get a different app experience than if I launched it from the Android launcher.  ie. The installed app is in release mode but flutter run runs something in debug mode)

This is confusing.

I would like to have a way to have a single canonical/source-of-truth app - I want the app I run from the command line to always be identical (with respect to environment and code) to the one that gets installed and is launched via the Android launcher.

**Comment by devoncarew** [comment] 2016-06-09 20:12
`flutter run` will build and install the app before running it - is there a reason you're calling `build apk` and `install` manually?

`run` defaults to using `--debug` mode and `build apk` defaults to `--release` mode - it seems like when you're running the app you'd be most interested in debuggability, and when explicitly building it more interested in a deployable version. Curious to hear if this matchs your expectations?

**Comment by apwilson** [comment] 2016-06-09 21:16
I've been told that you need to build and install in order for the app/code that's on the device to be consistent.  From what I understand run just pushes over some code that is just dropped on the floor next time the app is run - is this correct?

@abarth @Hixie

**Comment by devoncarew** [comment] 2016-06-10 02:46
`flutter run` largely uses the same logic as `flutter build`; it will re-built an app as necessary before a run.

`run` does have a state that if you re-run a running app, or run `flutter refresh`, the older code is not overwritten. So if you stop that run, and then start the app manually on the device, you'll see the original dart code.

You would want to do `flutter build apk && flutter install` in that case, in order to have something which you can take around and demo.

**Comment by Hixie** [comment] 2016-06-10 05:59
Is there some way we can make `flutter run` mark the build it's updating as "obsolete" so that when the shell is run straight from the home screen, rather than via our carefully crafted intent, it fails with a message of some sort?

**Comment by abarth** [comment] 2016-06-10 06:15
Maybe the debug version shouldn't have the LAUNCHER permission.  That way it won't show up on the home screen and be confusing.

**Comment by sethladd** [comment] 2016-06-10 16:07
Imagine this scenario:

* flutter build apk && flutter install
* change some code
* flutter run --debug
* shuts down the app
* user taps the icon on the home screen

Would it be clear to the user that `flutter run --debug` was not updating/overwriting the installed app? (Maybe with --debug you always get Slow Mode banner, so that's your visual clue...)

**Comment by abarth** [comment] 2016-06-10 16:57
> user taps the icon on the home screen

1. Either we should make this step impossible by removing the LAUNCHER permission from builds created with "run", or
2. We should make builds created by "run" launched from the launcher show a message explaining how to create a release build.

**Comment by apwilson** [comment] 2016-06-10 17:18
@sethladd  No it wouldn't be clear.  I'd always expect the last 'flutter run' to be what would be running when I launch the app manually.  The debug banner would be your visual cue but unless you knew what was going on you'd wonder why the banner isn't there (like me).

If whatever flutter run does is ephemeral vs. being permanent then I think we there should be some sort of call to action to make things permanent - or a warning should be displayed indicating that the code is running in ephemeral mode and give an option to make it permanent.

**Comment by apwilson** [comment] 2016-06-10 17:21
> run does have a state that if you re-run a running app, or run flutter refresh, the older code is not overwritten. So if you stop that run, and then start the app manually on the device, you'll see the original dart code.

This is the exact problem I'm having problems wrapping my mind around.  And there's no supporting information for a reasonable developer to understand what's happening imo (of course I rarely read documentation anyway so that could be half my problem :p)

**Comment by sethladd** [comment] 2016-06-10 17:51
Thanks for the feedback!

Talked to @abarth offline, and we brainstormed ways to address this. One idea, if I recall, was to (somehow) invalidate the installed app if the developer runs `flutter run --debug`. That way, in my scenario above, on step 5 the developer would see a message like "you've changed your app since the last time you launched this. You need to re-install."

Another idea that comes to mind: the developer would need to first install some sort of Debug Container App, which hosts all the in-development apps. This DCA would be a separate launcher icon on the home screen, perhaps thus reinforcing that when developing you find your in-development apps in a different, self-contained launcher. Just a thought.

**Comment by devoncarew** [comment] 2016-06-10 18:20
> Maybe the debug version shouldn't have the LAUNCHER permission. That way it won't show up on the home screen and be confusing.

I think this would avoid the issue entirely - we'd just make the `--debug` version of the app not separately launchable. The user can use build and install if they need an independently runnable app.

**Comment by abarth** [comment] 2016-07-31 16:52
We have a notion of a "stub" app now that `--hot` uses to bootstrap.  We could make that be the thing that you get when you launch the app via the launcher.  It could have instructions for how to connect to the app to start developing it.

**Comment by Hixie** [comment] 2016-08-01 17:11
The problem is you end up with a phone full of stubs instead of release apps, so you have nothing to demo when you're out and about.

**Comment by abarth** [comment] 2016-08-01 17:13
IMHO, we should remove the expectation that "run" gives you an app installed on your device, probably by removing the launcher icon.  Instead, "install" is the thing that gives you an app installed on your device.  The expectation should be that you have whatever version you installed.

**Comment by sethladd** [comment] 2016-08-01 17:17
> we should remove the expectation that "run" gives you an app installed on your device

+1

**Comment by Hixie** [comment] 2016-08-03 00:13
The specific issue that "flutter run" shouldn't result in a launchable icon in the app tray is https://github.com/flutter/flutter/issues/5185.

There's a related issue which is what to do when someone uses the "recents" menu on Android to go back to a hot-reload app after it's quit. I fixed that in https://github.com/flutter/flutter/pull/5193.

Are there other issues we should address to consider this bug resolved?

**Comment by sethladd** [comment] 2016-09-08 16:26
cc @danrubel if you're interested in taking a crack at this. I find it strange that `flutter run --release` also installs the app. :) I wonder if we can make `run` a developer thing, and `build` a "I want to build the app", and `install` a "I want to put a built app on the phone".

If I `run`, I shouldn't have something left on the device. (until we have some sort of Dev Shell app which can host a variety of in-development flutter apps, but that's for much later :)

**Comment by Hixie** [comment] 2017-01-30 06:36
Closing in favour of the more concrete #5185.

**Closed by Hixie** 2017-01-30 06:36 UTC
Labels: dev: tool, regression
