### ISSUE TITLE
[ios] [metal] Profile mode Metal API Validation Errors

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#77643] opened 2021-03-08 22:00 UTC
Following errors are being hit:

```
2021-03-08 15:57:10.693070-0600 Runner[46398:11504702] flutter: Observatory listening on http://127.0.0.1:62200/TVd6mSApTOc=/
2021-03-08 15:57:10.973359-0600 Runner[46398:11504692] -[MTLDebugRenderCommandEncoder validateFramebufferWithRenderPipelineState:], line 1288: error 'Framebuffer With Render Pipeline State Validation
For stencil attachment, the render pipeline's pixelFormat (MTLPixelFormatInvalid) does not match the framebuffer's pixelFormat (MTLPixelFormatStencil8).
'
-[MTLDebugRenderCommandEncoder validateFramebufferWithRenderPipelineState:]:1288: failed assertion `Framebuffer With Render Pipeline State Validation
For stencil attachment, the render pipeline's pixelFormat (MTLPixelFormatInvalid) does not match the framebuffer's pixelFormat (MTLPixelFormatStencil8).
'
```

Repro instructions:

1. From CLI, in `<framework>/dev/benchmarks/macrobenchmarks` run `flutter run -d <ios_device> --profile`.
2. Quit the above command once the required `ios/Runner.xcworkspace` file is generated.
3. Run `ios/Runner.xcworkspace` from `xcode`. You hit the above errors.

When I go to `Edit Schemes > Run > Diagnostics > Disable Metal API Validation` the run succeeds.

Hit this while trying to repro: https://github.com/flutter/flutter/issues/77404

**Comment by jmagman** [comment] 2021-03-08 23:16
> 1. From CLI, in `<framework>/dev/benchmarks/macrobenchmarks` run `flutter run -d <ios_device> --profile`.
> 2. Quit the above command once the required `ios/Runner.xcworkspace` file is generated.

P.S. you can run `flutter build ios --config-only` to generate all the necessary files and build settings, but not actually compile anything.

**Comment by jmagman** [comment] 2021-03-08 23:17
Duplicate of https://github.com/flutter/flutter/issues/77397.

**Closed by jmagman** 2021-03-08 23:17 UTC
