### ISSUE TITLE
Flutter release builds (via `flutter build apk --release`) aren't optimized

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#136879] opened 2023-10-19 11:49 UTC
It seems flutter release builds result in APKs that have dex in them (from java/kotlin) that wasn't optimized.

This can be seen as follows:
```
% flutter create hello && cd hello

### Build the APK
hello %  flutter build apk --release

### Examine the R8/Proguard rules used for tree shaking
hello % cat build/app/outputs/mapping/release/configuration.txt
...
# Optimization is turned off by default. ...
-dontoptimize
...


### Examine size of resulting DEX bytecode
hello % unzip -l build/app/outputs/flutter-apk/app-release.apk | grep classes.dex
   689484  1981-01-01 01:01   classes.dex
```

The root cause is that flutter's gradle file explicitly tells the R8 to use unoptimized android proguard rules.

If we fix this via:
```diff
diff --git a/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy b/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy
index f3c1a4145c..f5950024e2 100644
--- a/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy
+++ b/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy
@@ -308,7 +308,7 @@ class FlutterPlugin implements Plugin<Project> {
                     shrinkResources isBuiltAsApp(project)
                     // Fallback to `android/app/proguard-rules.pro`.
                     // This way, custom Proguard rules can be configured as needed.
-                    proguardFiles project.android.getDefaultProguardFile("proguard-android.txt"), flutterProguardRules, "proguard-rules.pro"
+                    proguardFiles project.android.getDefaultProguardFile("proguard-android-optimize.txt"), flutterProguardRules, "proguard-rules.pro"
                 }
             }
         }
```

and rebuild we get the following:
```
hello % flutter build apk --release

hello % unzip -l build/app/outputs/flutter-apk/app-release.apk | grep classes.dex
   512376  1981-01-01 01:01   classes.dex
```

=> The `classes.dex` file shrinks by **25%** (`689484` -> `512376`).
=> Bigger apps that use various java/kotlin plugins may benefit quite significantly (compared with the hello world)

/cc @reidbaker

**Comment by mkustermann** [comment] 2023-10-19 11:55
-> Made PR https://github.com/flutter/flutter/pull/136880

**Comment by mkustermann** [comment] 2023-10-19 11:59
While debugging why the platform code wasn't shrunken I also tried to follow some instructions to use the new `postprocessing DSL block` in the gradle file that allows configuring proguard rules etc (see e.g. [here](https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/PostProcessing)).

=> Unfortunately one cannot even use such a `postprocessing` DSL block (will result in error messages from gradle build) atm due to flutter's gradle plugin using the other mechanism.
=> Why isn't this stuff configured in the actual application gradle file instead of the flutter gradle plugin injecting this?

**Comment by mkustermann** [comment] 2023-10-30 15:19
This got reverted due to build failures whose root cause is that the android gradle plugin (AGP) is outdated - it uses an old AGP with bugs in R8. Upgrading the AGP would fix this issue. See https://github.com/flutter/flutter/pull/136880#issuecomment-1785443052 for more information.

**Comment by gmackall** [comment] 2024-07-10 20:59
Assigning to myself to keep this on my radar for now. Part 2 of https://github.com/flutter/flutter/pull/136880#issuecomment-2005280424 should be accomplished soon, by https://github.com/flutter/flutter/pull/151433 and a follow up pr. The other parts shouldn't be that hard to accomplish either (1 and 3).

**Comment by mkustermann** [comment] 2024-08-15 18:32
@gmackall It seems https://github.com/flutter/flutter/pull/151433 landed now. Is this issue then unblocked?

**Comment by gmackall** [comment] 2024-08-15 19:48
> @gmackall It seems #151433 landed now. Is this issue then unblocked?

Yes, I think so. Step 1 would be to move the packages repo off of the version of AGP that has the bugged version of R8, or else we will block the framework->packages roller. I can put up a PR.

**Comment by gmackall** [comment] 2024-08-15 21:06
@mkustermann do you happen to know the first version of AGP that pulls in a fixed R8 version? Can't remember if this was mentioned somewhere. Just want to know the range that would be impacted

**Comment by mkustermann** [comment] 2024-08-16 07:21
> @mkustermann do you happen to know the first version of AGP that pulls in a fixed R8 version? Can't remember if this was mentioned somewhere. Just want to know the range that would be impacted

So the error (from https://github.com/flutter/flutter/pull/136880#issuecomment-1783313215) is about ` Unused argument with users in`. I was referred to similar bug reports that got fixed in R8: b/249884086 b/242308990  which says:

> The fix for this issue landed in R8 3.3.75 which unfortunately is not in AGP 7.3.0 (that has R8 version 3.3.70). 

=> So I would assume from AGP 7.4.0+ (**) on  this is fixed.

(**) Which requires Gradle 7.5+.

**Comment by gmackall** [comment] 2024-08-20 21:03
Upgrade in packages landed, just waiting for https://github.com/flutter/flutter/pull/152487 to land now too because I want to use some of the changes to `AndroidProject` from that PR in the new gradle error handler

**Comment by gmackall** [comment] 2024-08-20 23:01
Also I confirmed that the issue doesn't affect 7.4.0, after reproducing it following the steps in https://github.com/flutter/flutter/pull/136880#issuecomment-1785443052

**Comment by gmackall** [comment] 2024-08-21 21:03
PR up at https://github.com/flutter/flutter/pull/153868

**Closed** 2024-08-23 16:44 UTC
Labels: platform-android, tool, a: build, P2, team-tool, triaged-tool
