### ISSUE TITLE
'ui.platformViewRegistry.registerViewFactory' is missing in master channel

### ISSUE THREAD

**Issue by 461882111zzy** [flutter/flutter#42566] opened 2019-10-12 07:04 UTC
I want to use HtmlElementView in flutter web, but in master channel, the 'ui.platformViewRegistry.registerViewFactory' is missing, so HtmlElementView doesn't work!

**Comment by BondarenkoStas** [comment] 2019-10-12 10:56
Duplicate of #41563

**Closed by BondarenkoStas** 2019-10-12 10:56 UTC
