### ISSUE TITLE
TabController listener triggers with delay on swipe

### ISSUE THREAD

**Issue by migalv** [flutter/flutter#89371] opened 2021-09-02 14:07 UTC
## Steps to Reproduce
It's really simple if you go to [TabController page](https://api.flutter.dev/flutter/material/TabController-class.html) in the Flutter docs you will find the code.

Example 1:
1. You can also run `flutter create --sample=material.TabController.2 mysample` to get the starting code
2. Update the files as follows:
Add a print or some statement to know that the tab listener has been triggered:

```
tabController.addListener(() {
  print("Listener triggered...");  // <===== HERE ADD THE STATEMENT - Line: 44
  if (!tabController.indexIsChanging) {
    // Your code goes here.
    // To get index of current tab use tabController.index
  }
});
```
3. Switch between tabs by swipping

Example 2:
1. You can also run `flutter create --sample=material.TabController.2 mysample` to get the starting code
2. Transform MyStatelessWidget into StatefullWidget
```
class MyStatelessWidget extends StatefulWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  _MyStatelessWidgetState createState() => _MyStatelessWidgetState();
}

class _MyStatelessWidgetState extends State<MyStatelessWidget> {
  ...
}
```
3. Create a new variable & initialise it
```
class _MyStatelessWidgetState extends State<MyStatelessWidget> {
  String _currentTabName = ""; // <== ADD THIS
  @override
  void initState() {
    super.initState();
    _currentTabName = "Tab number 1";
  }
}
```
4. Then setState when the tabController listener is triggered
```
tabController.addListener(() {
  setState(() {
    _currentTabName = "Tab number ${tabController.index + 1}"; // <== ADD THIS
  });
});
```
5. Use the new variable as the tab content
```
TabBarView(
  children: tabs.map((Tab tab) {
    return Center(
      child: Text(
        _currentTabName, // <== HERE
        style: Theme.of(context).textTheme.headline5,
      ),
    );
  }).toList(),
),
```

**Expected results:** 
It should notify the listener as soon as the user lifts the finger from the screen

**Actual results:**
It notifies the listener with a second or so of delay

You can see a more clear example of what I mean with this gif from my app.

| Example 1 | Example 2: |
|----|----|
| ![example1](https://media0.giphy.com/media/0x5LVwErDgaFPnkUk5/giphy.gif?cid=790b7611d88bbe10dc528799e77908de9b715c47b692015f&rid=giphy.gif&ct=g) | ![example2](https://media4.giphy.com/media/hDwNRxhEXXfxFhy59r/giphy.gif?cid=790b761103705c5f5e792fff32c32be78d1ab915a45864c6&rid=giphy.gif&ct=g) |

<details>
  <summary>Logs</summary>

Flutter analyze output:
```
Analyzing mysample...                                           
No issues found! (ran in 1.9s)
```

Flutter doctor output:
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/migalv/fvm/versions/stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/migalv/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/migalv/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • ELE L29 (mobile)        • XPH0219321004488                         • android-arm64  • Android 10 (API 29)
    • iPhone de Test (mobile) • 752edcc5698148b90e86592f562100c03966333c • ios            • iOS 14.7.1
    • macOS (desktop)         • macos                                    • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-09-03 06:06
Hi @migalv Thanks for filing the issue, I am not able to reproduce the issue, the listener is invoked immediately on tab change, and also the tab changes immediately when the pointer is lifted you can also see this happening in the [example from the docs](https://api.flutter.dev/flutter/material/TabController-class.html#material.TabController.2) 
Let me know if I am missing anything.

Thanks

**Comment by migalv** [comment] 2021-09-03 12:45
Hello @maheshmnj, as I mention in my issue, this delay only happens when using the swipe gesture.

This delay happens on the listener attached to the TabController, as you can see here:
```
tabController.addListener(() {
  print("Listener triggered...");  // <===== This prints with delay on swipe
});
```

I have edited the initial issue with some more examples of this issue in play with a more visual look.

**Comment by maheshmnj** [comment] 2021-09-06 05:20
@migalv  thanks for the info, I see there is a similar issue describing this case https://github.com/flutter/flutter/issues/88875 you may follow up there for further updates. Closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it.

Thank you

**Closed by maheshmnj** 2021-09-06 05:20 UTC
Labels: in triage
