### ISSUE TITLE
Flutter Web: Zooming and scrolling. ListView wrapped in InteractiveViewer Widget

### ISSUE THREAD

**Issue by rirjkl19** [flutter/flutter#82019] opened 2021-05-07 07:54 UTC
First of all I'm a newbie in flutter so me pardon for my noob question. I have an issue that I would like to raise. I am trying to implement a scrollable list of images with a zoom feature. Here is my example code:

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyPage(),
    ),
  );
}

class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InteractiveViewer(
        child: Scrollbar(
          child: ListView.builder(
            itemCount: 10,
            itemBuilder: (context, index) => Container(
              margin: const EdgeInsets.all(10),
              height: 100,
              width: 100,
              color: Colors.red,
              child: Text("item $index"),
            ),
          ),
        ),
      ),
    );
  }
}
```

The expected result is met especially on the mobile devices. But when using this approach in the Flutter Web, things get messy. Using the mouse scroll wheel to scroll the list, the `InteractiveViewer`'s `onInteractions` event fires zooming-in the screen while also scrolling up the list.

Does this mean the scroll and pinch gesture is considered the same event?

And also, would it be possible for the Widgets to respect the InteractiveViewers event first before the ListView?

Thank you and I hope someone can englighten me in this simple issue.

Here is my flutter doctor -v

```
user@MacBook-Pro flutter_project % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.6 at /users/user/fvm/versions/stable
    • Framework revision 1d9032c7e1 (7 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-05-07 10:28
Hi @rirjkl19 
This is a known issue https://github.com/flutter/flutter/issues/70192
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/70192
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-07 10:28 UTC
Labels: in triage
