### ISSUE TITLE
[iOS] Jank when scrolling on an iPhone 14 Pro Max

### ISSUE THREAD

**Issue by notandyvee** [flutter/flutter#132144] opened 2023-08-08 18:04 UTC
## Details

I noticed my app began to have jank on my iPhone 14 pro max. It feels like it came out of nowhere. Maybe an iOS update? This feels really bad.

https://github.com/flutter/flutter/assets/1571223/6dbf1acb-d445-4941-99f0-a939a7342f8f

And this is what the dev tools shows.

<img width="1357" alt="Screenshot 2023-08-08 at 1 50 01 PM" src="https://github.com/flutter/flutter/assets/1571223/c36a66a0-9380-4ebd-a8b2-6100cabdb1c7">

I couldn't find the culprit in my app. Android works fine. iOS on this specific device doesn't work well. I am on an older version. So I upgraded to Flutter `3.10` to rule that out.

<img width="539" alt="Screenshot 2023-08-08 at 1 51 37 PM" src="https://github.com/flutter/flutter/assets/1571223/928a4236-93f2-4d4e-9ff8-1c5b3f206b15">

I created a test app because the assumption was it was something I did. Lo & behold, it appears it's the framework unless someone can point me to something I'm doing wrong.

**Exported logs**: [dart_devtools_2023-08-08_13 57 50.012.json.zip](https://github.com/flutter/flutter/files/12294540/dart_devtools_2023-08-08_13.57.50.012.json.zip)

**main.dart file**: [main.dart.zip](https://github.com/flutter/flutter/files/12294569/main.dart.zip) (create a brand new project and just use this main.dart file.)

**iOS Version**: 16.6

**Device**: iPhone 14 Pro Max

**Flutter doctor**:

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

Thanks!

**Comment by navaronbracke** [comment] 2023-08-08 19:04
This is probably a duplicate of https://github.com/flutter/flutter/issues/131319 as that also refers to iOS 16.6 specifically.

**Comment by notandyvee** [comment] 2023-08-08 19:33
Feel free to close then @navaronbracke . The additional info might be useful. Personally I think its ludicrous this is only being triaged after 2 weeks.

**Comment by danagbemava-nc** [comment] 2023-08-09 07:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/131319. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-08-09 07:24 UTC
Labels: in triage
