### ISSUE TITLE
[Windows] Default App Crashes due to minimizing and maximizing app

### ISSUE THREAD

**Issue by plplplpla** [flutter/flutter#76281] opened 2021-02-18 07:11 UTC
The app becomes Unresponsive(Not Responding) each time it's minimized and maximized  once or repeatedly
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run `flutter run`
A. Click on the taskbar to focus app window
B. Click again on the taskbar to minimize app window
Repeat A & B steps few times until the app freezes. Title bar of window shows (Not Responding)
Due to some reason the app may work nicely in the first run. Please close the window directly without using command q/Q. The terminal shows `Lost connection to device` and Rerun flutter and repeat A&B few times.

**Expected results:** 
To be able to minimize and focus fast enough without facing crash

**Actual results:** 
The app window doesn't respond until it's forcefully closed from task manager and restarted using `flutter run` command

<details>
  <summary>Logs</summary>

```
F:\Sandbox\bug>flutter run --verbose
[ +134 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +104 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[   +2 ms] executing: [C:\flutter/] git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[  +68 ms] Exit code 0 from: git tag --points-at 68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8
[   +1 ms] 1.27.0-1.0.pre
[  +71 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[   +1 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +102 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +74 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[ +135 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +105 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +83 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +132 ms] Multiple devices found:
[  +40 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1379]
[   +3 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68
[   +3 ms] [1]: Windows (windows)
[   +1 ms] [2]: Chrome (chrome)
[   +1 ms] [3]: Edge (edge)
[   +6 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] :
[+4623 ms] Q
[  +19 ms] "flutter run" took 5,134ms.
[  +16 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:308:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:296:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1210:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1131:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1026:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #8      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #12     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
           <asynchronous suspension>
           #15     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #17     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #18     runInContext (package:flutter_tools/src/context_runner.dart:75:10)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[  +16 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1


```

```
Analyzing bug...
No issues found! (ran in 4.7s)
```

```
F:\Sandbox\bug>flutter doctor -v
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.27.0-1.0.pre at C:\flutter
    • Framework revision 68c96f100e (9 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ray\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code
    • VS Code at C:\Users\ray\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1379]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!


```

</details>

**Comment by TahaTesser** [comment] 2021-02-18 08:08
Hi @plplplpla 
This has been addressed and fixed in https://github.com/flutter/flutter/issues/74797
I cannot reproduce it on the latest `master`


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.45, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-5.0.pre.45 at C:\Users\Taha\Code\flutter_master
    • Framework revision 90531179f5 (45 minutes ago), 2021-02-17 23:21:02 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 84.0.522.52
• No issues found!
```

</details>


Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`



Closing. as a duplicate of https://github.com/flutter/flutter/issues/74797
Thank you

**Closed by TahaTesser** 2021-02-18 08:08 UTC
Labels: in triage
