### ISSUE TITLE
TextField nullPointer when maxLines=0

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#11582] opened 2017-08-10 17:23 UTC
## Steps to Reproduce
When TextField has maxLines set to null, after some clicking in and out of TextField an error occurs.

```
new TextField(
    decoration: new InputDecoration(
        labelText: 'Optional note',
    ),
    maxLines: null,
)
```
## Logs
```
I/flutter (18998): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18998): The following NoSuchMethodError was thrown building _TextSelectionHandleOverlay(dirty; state:
I/flutter (18998): _TextSelectionHandleOverlayState#793c4()):
I/flutter (18998): The method 'toDouble' was called on null.
I/flutter (18998): Receiver: null
I/flutter (18998): Tried calling: toDouble()
I/flutter (18998): When the exception was thrown, this was the stack:
I/flutter (18998): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter (18998): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
I/flutter (18998): #2      double./ (dart:core-patch/double.dart:39)
I/flutter (18998): #3      _TextSelectionHandleOverlayState.build (package:flutter/src/widgets/text_selection.dart:512:49)
I/flutter (18998): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3646:27)
I/flutter (18998): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:15)
I/flutter (18998): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
I/flutter (18998): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536:5)
I/flutter (18998): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674:22)
I/flutter (18998): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18998): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (18998): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (18998): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4538:14)
I/flutter (18998): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (18998): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (18998): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568:16)
I/flutter (18998): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
I/flutter (18998): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536:5)
I/flutter (18998): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674:22)
I/flutter (18998): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18998): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (18998): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (18998): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568:16)
I/flutter (18998): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
I/flutter (18998): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3536:5)
I/flutter (18998): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3674:22)
I/flutter (18998): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18998): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (18998): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (18998): #29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4330:32)
I/flutter (18998): #30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:17)
I/flutter (18998): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (18998): #32     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (18998): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (18998): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3568:16)
I/flutter (18998): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3457:5)
I/flutter (18998): #36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2285:33)
I/flutter (18998): #37     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503:20)
I/flutter (18998): #38     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
I/flutter (18998): #39     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
I/flutter (18998): #40     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
I/flutter (18998): #41     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter (18998): #42     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter (18998): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/marcinus/flutter
    • Framework revision bbcfb8d51a (9 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/marcinus/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/marcinus/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/marcinus/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • ALE L21 • W3D7N16C16019415 • android-arm • Android 6.0 (API 23)
```

**Comment by TonyDowney** [comment] 2017-09-11 19:07
Encountered this over the weekend. Workaround for now is to manually calculate maxLines needed with a TextPainter, and update the maxLines with a call to `setState`. It would have to be run on `build`, on `TextField.onChange`, and if the font style or TextField width updates (i.e. orientation change). Simple function:

```
  int _getMaxLinesRequired(String text, double tfMaxWidth, TextStyle style){
    TextPainter textPainter = new TextPainter(
      text: new TextSpan(
        text: text,
        style: style,
      ),
      maxLines: 1,
    );
    textPainter.layout(maxWidth: tfMaxWidth);
    while (textPainter.didExceedMaxLines){
      textPainter.maxLines++;
      textPainter.layout(maxWidth: textFieldMaxWidth);
    }
    return textPainter.maxLines;
  }
```

**Comment by najeira** [comment] 2017-09-12 01:51
same as #11573

**Comment by xster** [comment] 2017-10-18 20:28
Note to self: use CompositedTransformFollower for positioning

**Comment by Hixie** [comment] 2017-10-24 23:32
or maybe something similar but directly in the paint() method using layers.

**Comment by jonahwilliams** [comment] 2018-11-27 00:55
@xster was this and https://github.com/flutter/flutter/issues/11573 fixed previously? I'm not able to reproduce

**Comment by xster** [comment] 2018-11-27 23:16
Was closed in https://github.com/flutter/flutter/pull/12833

**Closed by xster** 2018-11-27 23:16 UTC
Labels: a: text input, framework, severe: crash
