### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by gaurishbhatia** [flutter/flutter#150371] opened 2024-06-17 17:07 UTC
## Command
```sh
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\gauri\learndart\lib\wedlogin\wedlogin\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1773:7)
#1      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1725:14)
#2      VmService.callMethod (package:vm_service/src/vm_service.dart:1716:12)
#3      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:503:28)
#4      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:934:51)
#5      FlutterVmService._getIsolateRefs (package:flutter_tools/src/vmservice.dart:1017:50)
#6      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:998:54)
<asynchronous suspension>
#7      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:234:7)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#9      FlutterResidentDevtoolsHandler.serveAndAnnounceDevTools.callServiceExtensions (package:flutter_tools/src/resident_devtools_handler.dart:126:57)
<asynchronous suspension>
#10     FlutterResidentDevtoolsHandler.serveAndAnnounceDevTools (package:flutter_tools/src/resident_devtools_handler.dart:160:7)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.88, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.23.0-13.0.pre.88 on channel master at C:\Users\gauri\Downloads\flutter_windows_3.10.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c77c0cf0bc (13 days ago), 2024-06-04 11:40:20 -0400
    • Engine revision e211c43f3d
    • Dart version 3.5.0 (build 3.5.0-219.0.dev)
    • DevTools version 2.36.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\gauri\AppData\Local\Android\sdk
    • Platform android-VanillaIceCream, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.1)
    • VS Code at C:\Users\gauri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64 • Microsoft Windows [Version 10.0.22631.3737]

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: c77c0cf0bc4ae66e99de8c2dd15f21d7be4ed1d2
### Plugins
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1

**Comment by danagbemava-nc** [comment] 2024-06-18 07:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by danagbemava-nc** 2024-06-18 07:49 UTC
Labels: in triage
