### ISSUE TITLE
CupertinoTabBar and PopScope issue

### ISSUE THREAD

**Issue by cancavid** [flutter/flutter#140816] opened 2024-01-02 19:15 UTC
### Steps to reproduce

I want to add feature that when user click back button, show dialog for confirmation. I can do it with WillPopScope. But this widget is depricated now and I replaced it with PopScope, but it is not working as WillPopScope. I made canPop is false, but CuperinoTabBar can pop again and conditions not working.

### Expected results

Back button dont make anything.

### Actual results

App can pop and pop blank screen.

### Code sample

<details open><summary>Code sample</summary>

```dart
PopScope(
                canPop: false,
                onPopInvoked: (didPop) {
                  print(didPop);
                },
                child: CupertinoTabScaffold(
                  controller: tabController,
                  tabBar: CupertinoTabBar(
                    onTap: (index) {
                      if (index == tabBarController.index.value) {
                        if (index == 0) {
                          firstTabNavKey.currentState?.popUntil((r) => r.isFirst);
                        } else if (index == 1) {
                          secondTabNavKey.currentState?.popUntil((r) => r.isFirst);
                        } else if (index == 2) {
                          thirdTabNavKey.currentState?.popUntil((r) => r.isFirst);
                        } else if (index == 3) {
                          fourthTabNavKey.currentState?.popUntil((r) => r.isFirst);
                        } else if (index == 4) {
                          fifthTabNavKey.currentState?.popUntil((r) => r.isFirst);
                        }
                      }
                      tabBarController.update(index);
                    },
                    border: Border(bottom: BorderSide(color: Colors.transparent)),
                    height: 80.0,
                    backgroundColor: (darkmodeController.mode.value == 'Dark') ? MsColors.darkSecondaryBg : MsColors.lightSecondaryBg,
                    items: [
                      BottomNavigationBarItem(icon: MsBottomNavItem(icon: 'home.svg', label: 'Əsas səhifə'.tr, index: 0, selected: tabBarController.index.value)),
                      BottomNavigationBarItem(icon: MsBottomNavItem(icon: 'category.svg', label: 'Kataloq'.tr, index: 1, selected: tabBarController.index.value)),
                      BottomNavigationBarItem(icon: MsBottomNavItem(icon: 'favorite.svg', label: 'İstək listi'.tr, index: 2, selected: tabBarController.index.value, badge: wishlistController.quantity.value)),
                      BottomNavigationBarItem(icon: MsBottomNavItem(icon: 'cart.svg', label: 'Səbət'.tr, index: 3, selected: tabBarController.index.value, badge: cartController.quantity.value)),
                      BottomNavigationBarItem(icon: MsBottomNavItem(icon: 'profile.svg', label: 'Hesabım'.tr, index: 4, selected: tabBarController.index.value)),
                    ],
                  ),
                  tabBuilder: (context, index) {
                    return CupertinoTabView(
                      routes: Routes.routes,
                      navigatorKey: listOfKeys[index],
                      builder: (context) {
                        return pages[index];
                      },
                    );
                  },
                ),
              ),

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/55326192/ed9f54c2-59b8-4937-bdc8-fe55b4bd69d4

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/MIUIInput(30130): [KeyEvent] ViewRootImpl windowName 'az.masterstudio.meqamax/az.masterstudio.meqamax.MainActivity', KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=166556973000000, downTime=166556973000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:11:04.209
D/MIUIInput(30130): [KeyEvent] ViewRootImpl windowName 'az.masterstudio.meqamax/az.masterstudio.meqamax.MainActivity', KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=166557063000000, downTime=166556973000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:11:04.298
I/flutter (30130): false
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3448], locale en-US)
    • Flutter version 3.16.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34114.132
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and
      include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • 2203129G (mobile) • eafc5304 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.3448]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 120.0.6099.130
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-03 07:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139050. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-01-03 07:11 UTC
Labels: in triage
