### ISSUE TITLE
Predictive back gesture Android

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#132504] opened 2023-08-14 17:32 UTC
umbrella issue for the adding support for the Android 14 feature, Predictive back navigation.

- [x] https://github.com/flutter/flutter/issues/109513
- [x] https://github.com/flutter/flutter/issues/131961

**Comment by lukehutch** [comment] 2023-10-30 06:34
Just wanted to point out that a lot of people are going to run into this issue, since adb is already warning:

```dart
W/OnBackInvokedCallback(13376): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(13376): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```

However, if you set this value, Flutter is never even passed traditional back button push events.

I set this value, following the directions in the logs, and then promptly forgot about it. A couple of weeks later realized that the back button had stopped working in my app. It took me a whole week to track down why Flutter wasn't even receiving back button events.

**Comment by justinmc** [comment] 2023-11-03 04:52
@lukehutch Thanks for pointing this out for anyone else with this problem.  Can I ask how exactly you reproduce it?  What version of Flutter were you using?  If I just create a new Flutter app, set `enableOnBackInvokedCallback` to true, and run it on an Android emulator (API 34), the back button works.

**Comment by lukehutch** [comment] 2023-11-04 06:15
@justinmc I'm on Flutter 3.13.9.  Just tested again right now.

If I add `android:enableOnBackInvokedCallback="true"` to the `application` tag of `app/main/AndroidManifest.xml`, then the Flutter runtime is never sent back button events.

I debugged this all the way down to the method channel in Flutter, and the Back events are simply never received by Flutter.

One twist though is that if you push the Back button with this attribute added, then the app is popped when the Back button is pressed (i.e. Back returns to the home screen). In other words, it's not like the Back button does nothing at all, but it consistently closes the app. So the Android app generated by Flutter is probably still receiving the Back button, but it just doesn't do anything with it.

What this means though is that proper Back button behavior can't be implemented in Flutter, e.g. by means of a `BackButtonDispatcher` like the following, since it is never called:

```dart
/// Make back button close any open dialogs first, and only pop the route
/// if there are no dialogs open. (Default behavior is to pop the app on
/// every back button press)
class FixedBackButtonDispatcher extends RootBackButtonDispatcher {
  @override
  Future<bool> didPopRoute() async {
    // Close any open modal dialog before attempting to pop route
    if (navigatorKey.currentState?.canPop() ?? false) {
      navigatorKey.currentState!.pop();
      return true;
    }
    // Pop route, or pop app if at top level
    return super.didPopRoute();
  }
}
```

**Comment by shareefhadid** [comment] 2023-11-06 20:13
Noticed this issue as well. What is the proper way for implementing `android:enableOnBackInvokedCallback="true"` in the AndroidManifest?

As mentioned, it currently breaks the back button on android (minimizes the app instead of popping the route in my case).

**Comment by justinmc** [comment] 2023-11-12 00:11
The main predictive back PR is https://github.com/flutter/flutter/pull/132249, and it is not yet on stable (merge commit https://github.com/flutter/flutter/commit/f68d03f1cdf16dcffe2a53ae645ec87094e85d40).  I think the behavior you guys observed is expected when setting `android:enableOnBackInvokedCallback="true"` before that PR was merged.  Can you try it again on beta or master?

**Comment by lukehutch** [comment] 2023-11-12 12:09
@justinmc I can confirm that the issue is fixed on the current Flutter beta channel. Thanks!

**Comment by dawarepramod4** [comment] 2023-12-14 17:53
when will this come to Stable ..?

**Comment by justinmc** [comment] 2024-01-08 21:29
## Status update!

There are two main parts to this issue, 1. when navigating out of a Flutter app and 2. when navigating within a Flutter app.

### 1. Navigating out of the app

<img width="100" src="https://user-images.githubusercontent.com/389558/217918109-945febaa-9086-41cc-a476-1a189c7831d8.gif" />

Completed in https://github.com/flutter/flutter/pull/132249 and currently on stable (see https://github.com/flutter/flutter/commit/f68d03f1cdf16dcffe2a53ae645ec87094e85d40).

### 1. Navigating within the app

<img width="100" src="https://github.com/flutter/flutter/assets/389558/c4cf57f4-a92e-422d-9889-596d3cb87b01" />

In progress. Tracked in https://github.com/flutter/flutter/issues/131961.

Engine PR in progress: https://github.com/flutter/engine/pull/49093

TODO: Framework PR

**Closed** 2024-03-28 16:31 UTC
Labels: platform-android, f: gestures, team-design
