### ISSUE TITLE
ios intall error: no code signature found

### ISSUE THREAD

**Issue by duomoteng** [flutter/flutter#55838] opened 2020-04-28 10:28 UTC
iOS: Working well on the simulator, but when installing on physical ios devices", it shows me 
"No code signature found. 

I tried the following ways, but not working
1. `flutter clean` 
 2.`flutter create .` 
3.delete the ios folder and reconstruct it, 
4. Open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk and Open file SDKSettings.plist and check value for CODE_SIGNING_REQUIRED. If it is set 'NO' then set it 'YES'. 
5. clean DerivedData folder
6. 

```
Details

Unable to install "Runner"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011e69a81a DTDKCreateNSErrorFromAMDErrorCode + 233
	1   DTDeviceKitBase                     0x000000011e6dbf70 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000105690155 DVTInvokeWithStrongOwnership + 73
	3   DTDeviceKitBase                     0x000000011e6dbca8 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1654
	4   IDEiOSSupportCore                   0x000000011e552e91 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4165
	5   DVTFoundation                       0x00000001057c37f4 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x00000001057c5436 __DVTDispatchAsync_block_invoke + 1194
	7   libdispatch.dylib                   0x00007fff70b5a6c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff70b5b658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff70b60c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff70b615d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff70b6ac09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff70db5a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff70db4b77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.4 (Build 19E287)
Xcode 11.4.1 (16137)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/alex/development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • iPad              •          • ios • iOS 13.4
    • iPhone 11 Pro Max •  • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

```

Update；the issue is solved, because of package fluttify, but I still don’t know why it caused this issue.

**Comment by TahaTesser** [comment] 2020-04-28 13:58
Duplicate of [#53891](https://github.com/flutter/flutter/issues/53891)

**Closed by TahaTesser** 2020-04-28 13:58 UTC
