### ISSUE TITLE
App crashes when loading networkimage in gridview

### ISSUE THREAD

**Issue by sawrose** [flutter/flutter#34634] opened 2019-06-18 10:13 UTC
I am creating a gridview of images using future but during scrolling of gridview app crashes and there is not error, but just
```
Lost connection to device.
Exited (sigterm)
```

The images reappear and disappear when scrolling up and down .

I have tried using `image.network` , cached network image , fade in image, but it didn't working. I have also limited my image request to 40, but also it crashes. Image sizes are only in 20-100 kb range.

```dart
       FutureBuilder(
          future: fetchallsubcategory(),

          builder: (BuildContext context, AsyncSnapshot snapshot) {
           return snapshot.hasData ? GridView.builder(
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: 2),
                        itemCount: snapshot.data.results.length,
                        // padding: EdgeInsets.all(2.0),
                        // scrollDirection: Axis.horizontal,
                        itemBuilder: (context, int) {
                          return Card(
                            child: 
                           CachedNetworkImage(imageUrl : snapshot.data.results[int].image),
                          );
                        }
            ) :CircularProgressIndicator();
          },
        )
```

**Comment by brux88** [comment] 2019-08-06 08:33
i have the same error, are there news?

**Comment by swat-cat** [comment] 2019-08-28 14:15
Same error. Any news with it?

**Comment by wochen85** [comment] 2019-09-10 14:44
i have this error,too。

**Comment by sawrose** [comment] 2019-09-18 05:23
i am able to get rid of this problem using  plugin "flutter_pagewise" and reduce image size from server side

**Comment by jnsmith0274** [comment] 2020-04-19 21:15
Same issue here.  Using the ```Image.network( ... )``` helps, but then the images are not cached locally.  Kind of defeats the point of using ```CachedNetworkImage```.

```
Image.network(
    images[index].url,
    width: 500,
    height: 500,
    cacheWidth: 500,
    cacheHeight: 500,
    fit: BoxFit.fitHeight)
```

There's got to be better memory support for something like this in flutter.

**Comment by iapicca** [comment] 2020-04-20 13:32
Hi @jnschulze 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and  a reproducible minimal code sample.
 
Hi @sawrose  from your [message](https://github.com/flutter/flutter/issues/34634#issuecomment-532523555) I understand that the issue was the image size, is that correct?

Thank you both

**Comment by iapicca** [comment] 2020-05-29 13:36
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:36 UTC
Labels: in triage, waiting for customer response

**Comment by JigarKotak7** [comment] 2020-08-07 13:39
I have this very same issue have tried everything I could to resolve this, in fact the app was working fine a month ago and suddenly started crashing now and it is dues to memory pressure. Has anyone found a solution to this, I was very close to submitting this app to the app store & google play store. Any help would be much appreciated. 
Thank you!

**Comment by hoseyneil** [comment] 2020-12-07 21:40
I can confirm this is also happening for me, I'm on the verge of releasing so wont have time for a few weeks to push a test app.  Its started happening since I upgraded to 1.22.4.  No more info other than that.

**Comment by iapicca** [comment] 2020-12-07 22:55
@JigarKotak7 @hoseyneil 
please open a new issue providing
your `flutter doctor -v` , your `flutter run --verbose`
and most importantly a reproducible minimal code sample.
