### ISSUE TITLE
"build\host\outputs\apk\app-debug.apk" does not exist.

### ISSUE THREAD

**Issue by uncatch** [flutter/flutter#119896] opened 2023-02-03 05:59 UTC
Steps to Reproduce
after upgrade flutter to 3.7.0,
I can run a flutter application successfully,
but while running a flutter module project, i got the error :

√ Built build\host\outputs\apk\debug\app-debug.apk.
"build\host\outputs\apk\app-debug.apk" does not exist.
Error launching application on sdk gphone64 x86 64.

Version info
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22000.1455], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
✗ Visual Studio not installed; this is necessary for Windows development.
Download at https://visualstudio.microsoft.com/downloads/.
Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2022.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

flutter plugin version: 72.0.2

**Comment by huycozy** [comment] 2023-02-03 10:46
Hi @uncatch 
I'm closing this as a duplicate of #116173. Please take a look at https://github.com/flutter/flutter/issues/116173#issuecomment-1407985223 for more information. 
If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2023-02-03 10:46 UTC
Labels: in triage
