### ISSUE TITLE
Flutter app on Windows 10 is capped at 60fps, on 144hz monitor

### ISSUE THREAD

**Issue by gardc** [flutter/flutter#93058] opened 2021-11-04 14:41 UTC
It seems Flutter desktop apps are limited to 60fps, even on higher refresh rate monitors. This makes apps made with Flutter for desktop feel sluggish and laggy, which gives bad UX. It's especially bad for animation-heavy apps. 

This is the only issue keeping me from using Flutter to built desktop apps.
![Screenshot](https://user-images.githubusercontent.com/41453409/140334266-94ab1684-72bc-4e7b-ac9c-916d57a06f95.png)

**Comment by stuartmorgan** [comment] 2021-11-04 15:59
Duplicate of https://github.com/flutter/flutter/issues/49757

**Closed by stuartmorgan** 2021-11-04 15:59 UTC
