### ISSUE TITLE
TimePicker not Localized

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#63165] opened 2020-08-07 04:41 UTC
## Steps to Reproduce

1. Use the new `showTimePicker` in Flutter 1.20 while the app is localized to brazilian portuguese (using the oficial documentation, localization delegates, etc.)

```dart
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale("pt", "BR"), Locale("pt")],
      locale: const Locale("pt", "BR"),
```

**Expected results:** 

Input mode:

![image](https://user-images.githubusercontent.com/379339/89609321-e38d6f80-d84d-11ea-9445-b2c1933a5b44.png)

1. Hour and Minute are not translatable (there are no options in `showTimePicker`).
2. CANCEL is capitalized (the new Material guideline recommends it to be lowercase, right?)
3. If Ok and CANCEL are translated, why title is not? (not important, since title, ok and cancel can be manually translated)
4. Error messages are also not translatable

![image](https://user-images.githubusercontent.com/379339/89609804-45020e00-d84f-11ea-97a7-dc0c3e0f6946.png)

5. The current value should be selected when field get focus (so user just type the new value instead of having to delete it before edit)
6. Use maxlength to allow only 2 characters
7. It would be nice if we couldn't type 25 in hours, 61 in minutes, etc.
8. It would be nice if there was a ⬆ and ⬇ buttons beneath each textbox (so user can use it to increment/decrement the value instead of typing it). Or, better yet: let us provide builders for each part of those dialogs.

Dial mode:

![image](https://user-images.githubusercontent.com/379339/89609413-25b6b100-d84e-11ea-8193-b05d0de98623.png)

1. I had users complaining about the old time picker because "it was not possible to pick times other than 00 - 12". My user didn't get that it was possible to pick times from 12 to 24h because Android time picker is not user friendly (at least to some users). The fact that the new time picker hides odd hours will lead to the same kind of issue in those... less intelectual gifted users. Please, consider putting all numbers in the clock (even if it is smaller than the others). It would be a plus if we could have builders for those numbers (so we can choose fonts, etc.).

**Comment by darshankawar** [comment] 2020-08-07 09:33
There was similar [issue](https://github.com/flutter/flutter/issues/62775) that was recently fixed and closed. Also see [this](https://github.com/flutter/flutter/issues/62775#issuecomment-668617045) comment on `select time` translation.

Above issue replicable on Stable 1.20.1.

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: const [Locale("pt", "BR"), Locale("pt")],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: const Locale("pt", "BR"),
      home: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: FlatButton(
              color: Colors.red.shade200,
              child: Text('Show time picker'),
              onPressed: () {
                showTimePicker(
                  context: context,
                  initialTime: TimeOfDay.fromDateTime(
                    DateTime(2020, 7, 28, 19, 3),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by Zazo032** [comment] 2020-08-07 11:11
This is already fixed in master by https://github.com/flutter/flutter/pull/63026

**Comment by guidezpl** [comment] 2020-08-07 11:36
cc @rami-a

**Comment by rami-a** [comment] 2020-08-07 12:53
Thanks for the feedback @JCKodel. The translated strings are fixed in master with https://github.com/flutter/flutter/pull/63026 like @Zazo032 said. Also limiting to 2 characters is also fixed in master with https://github.com/flutter/flutter/pull/62803.

I'll send along the rest of your suggestion to our design team for discussion.

**Comment by HansMuller** [comment] 2020-08-07 15:11
CC @darrenaustin

**Comment by yairsafe** [comment] 2020-08-09 07:42
![Screenshot_1596958887](https://user-images.githubusercontent.com/31651758/89727382-ed20fe00-da2c-11ea-8134-fd2e450f3c16.png)

In rtl languges

**Comment by NandoSantana** [comment] 2021-06-03 03:19
how limit max and min time?

**Comment by maheshmnj** [comment] 2022-12-16 20:59
Hi @JCKodel, I verified the issue on the latest master channel and it seems to be fixed, I see all the strings in the TimePicker have been translated.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/31410839/208187703-5d44dd22-f452-4dbe-8bd5-6fafd1bd8ce5.png">

<img width="297" alt="image" src="https://user-images.githubusercontent.com/31410839/208187776-0c5240a3-2218-40ef-a939-6915cd9cccb6.png">

<details>
<summary>code samplev</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: const [Locale("pt", "BR"), Locale("pt")],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: const Locale("pt", "BR"),
      home: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: ElevatedButton(
              child: const Text('Show time picker'),
              onPressed: () {
                showTimePicker(
                  context: context,
                  initialTime: TimeOfDay.fromDateTime(
                    DateTime(2020, 7, 28, 19, 3),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as no longer reproducible.

**Comment by ChristianEdwardPadilla** [comment] 2024-10-10 15:54
Seems the Hindi localization is incorrectly placing the AM/PM buttons as if Hindi was an RTL language:

![AEoANmcV6NcNto5](https://github.com/user-attachments/assets/ab385912-4610-4d07-9a93-38907b04d380)

**Comment by huycozy** [comment] 2024-10-11 05:32
@ChristianEdwardPadilla It looks like a separate issue. I opened new issue for that https://github.com/flutter/flutter/issues/156565. Closing this as the original issue is fixed.

**Closed by huycozy** 2024-10-11 05:32 UTC
Labels: framework, f: material design, f: date/time picker, a: internationalization, has reproducible steps, found in release: 1.21
