### ISSUE TITLE
Localizations didn't work inside GridView.builder ?

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#116602] opened 2022-12-06 18:12 UTC
## Steps to Reproduce

1. Download project from my repo https://github.com/EArminjon/flutter-context-issue 
2. Execute `flutter run`
3. Go to your phone settings and change the phone locale.
4. Go back to your app and see that the top section is not updated.
5. Do a hot reload.
6. Top section is updated...

**Expected results:** 
Would see the top section refreshed as the app bar and the bottom section.

**Actual results:** 
Top section is not refresh.

<details>
<summary>Code sample</summary>

My repo contain more file useful for the test. (dependencies, l10n.yaml, arb files)
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() {
  runApp(const App());
}

class CardUsingBuilderContext extends StatelessWidget {
  const CardUsingBuilderContext({super.key});

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        // comps + default card margin 87 + 8
        mainAxisExtent: 95,
        mainAxisSpacing: 16,
        crossAxisSpacing: 16,
      ),
      cacheExtent: 0,
      shrinkWrap: true,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      itemCount: 4,
      itemBuilder: (BuildContext context, int index) {
        return Card(
          child: Center(
            child: Text(AppLocalizations.of(context)!.test),
          ),
        );
      },
    );
  }
}

class CardUsingWidgetContext extends StatelessWidget {
  const CardUsingWidgetContext({super.key});

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        // comps + default card margin 87 + 8
        mainAxisExtent: 95,
        mainAxisSpacing: 16,
        crossAxisSpacing: 16,
      ),
      cacheExtent: 0,
      shrinkWrap: true,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      itemCount: 4,
      itemBuilder: (BuildContext _, int index) {
        return Card(
          child: Center(
            child: Text(AppLocalizations.of(context)!.test),
          ),
        );
      },
    );
  }
}

class AppSettings extends ChangeNotifier {
  bool darkMode;

  AppSettings({
    this.darkMode = false,
  });

  void useDarkMode(bool value) {
    darkMode = value;
    notifyListeners();
  }
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const <Locale>[
        Locale('en'),
        Locale('fr'),
      ],
      home: Builder(
        builder: (context) {
          return Scaffold(
            appBar: AppBar(title: Text(AppLocalizations.of(context)!.test)),
            body: Column(
              children: const <Widget>[
                // Broken
                CardUsingBuilderContext(),
                Divider(),
                // Working
                CardUsingWidgetContext(),
              ],
            ),
          );
        },
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
No logs
```

```
No warnings
```

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.1 21G217 darwin-arm, locale fr-FR)
    • Flutter version 3.3.8 on channel stable at /Users/earminjon/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (4 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

At the end of the video I do a hot reload. The top section is refreshed after that.

[untitled.webm](https://user-images.githubusercontent.com/37028599/205989066-374379a1-261c-4b58-ad07-c6b31fa0f29a.webm)

**Comment by darshankawar** [comment] 2022-12-07 08:33
Thanks for the report @EArminjon 
From the code you shared, I don't see difference between `CardUsingWidgetContext` and `CardUsingBuilderContext` class, as the code seems to be same in both. Can you provide code in `CardUsingWidgetContext` that works as expected as compared to `CardUsingBuilderContext` ?

**Comment by EArminjon** [comment] 2022-12-07 08:35
> Thanks for the report @EArminjon From the code you shared, I don't see difference between `CardUsingWidgetContext` and `CardUsingBuilderContext` class, as the code seems to be same in both. Can you provide code in `CardUsingWidgetContext` that works as expected as compared to `CardUsingBuilderContext` ?

Code same, but Text widget inside didn't use the same context.

**Comment by darshankawar** [comment] 2022-12-08 06:02
Thanks for the update. Using the repo provided above, seeing the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-4.0.pre.38, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-4.0.pre.38 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 521028c808 (8 hours ago), 2022-12-07 13:46:17 -0800
    • Engine revision 67254d6e4b
    • Dart version 2.19.0 (build 2.19.0-467.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by goderbauer** [comment] 2022-12-13 23:43
@thkim1011

**Comment by thkim1011** [comment] 2023-06-28 17:04
So I've finally figured out why this doesn't rebuild on locale change. Dart seems to treat the `delegate` as not having been updated in your case. I've checked that the condition in 

https://github.com/flutter/flutter/blob/73bb959a65243639fe19de1f9abb537ce7251dc3/packages/flutter/lib/src/widgets/sliver.dart#L732

evaluates to false.

It seems like modifying the build function so that its `itemBuilder` is a different function on locale change solves this issue. For example,
```
  @override
  Widget build(BuildContext context) {
    AppLocalizations localizations = AppLocalizations.of(context)!;
    return GridView.builder(
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        // comps + default card margin 87 + 8
        mainAxisExtent: 95,
        mainAxisSpacing: 16,
        crossAxisSpacing: 16,
      ),
      cacheExtent: 0,
      shrinkWrap: true,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      itemCount: 4,
      itemBuilder: (BuildContext context, int index) {
        return Card(
          child: Center(
            child: Text(localizations.test),
          ),
        );
      },
    );
  }
```
so that your delegate is forced to update (as it uses a different `localizations` on each rebuild). 

Now I'm not exactly convinced that this is the expected behavior, as I would expect `itemBuilder` to be distinct function objects on each call to `build`, so I'll look into what I can do here.

**Comment by thkim1011** [comment] 2023-08-08 20:43
I think I'll close this as this is just the behavior of Flutter. If there aren't any changes in the `itemBuilder` it won't rebuild.

**Closed by thkim1011** 2023-08-08 20:43 UTC
Labels: framework, a: internationalization, has reproducible steps, P2, found in release: 3.3, found in release: 3.7, team-framework, triaged-framework
