### ISSUE TITLE
Optimize Dart_NotifyLowMemory when a system channel message is sent to the framework

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#59208] opened 2020-06-10 22:18 UTC
If possible, it would be best to call Dart_NotifyLowMemory _after_ the framework channel message has been handled so that any resources released by the Flutter application can be garbage collected to the fullest extent.

Some more discussion in https://github.com/flutter/flutter/issues/59182

Challenges:

- The platform channel message is async. It may take too long to complete.
- Actually benchmarking this is going to be very timing sensitive and difficult to measure.
- There is currently no evidence this actually causes a problem. We should bump priority on this if we find evidence this signfiicantly helps things for a customer.

/cc @xster @a-siva @rmacnak-google @chinmaygarde @jason-simmons @liyuqian

**Comment by xster** [comment] 2020-06-10 23:04
Minor variation: we should probably run both before the Flutter signal to pick up already orphaned references and after to "commit" Flutter's reaction to the signal. 

Also cc @gaaclarke. Once we have a comparative scenario suite, we can better quantify the relative importance of this by patching this in locally and see the native memory behavior scrolling a big image list for instance, then Flutter's behavior with a cleanup on already orphaned references and a new Flutter behavior where Flutter flushing the Dart-side image cache will also be reflected in the same "transaction"

**Comment by chinmaygarde** [comment] 2020-11-06 19:03
Duplicate of https://github.com/flutter/flutter/issues/69973

**Closed by chinmaygarde** 2020-11-06 19:03 UTC
Labels: P5, engine, framework, passed first triage, perf: memory, severe: performance
