### ISSUE TITLE
failed assertion in LayoutBuilder builder when using RenderBox.localToGlobal()

### ISSUE THREAD

**Issue by kfirufk** [flutter/flutter#31651] opened 2019-04-26 06:43 UTC
in general I'm trying to get a widget dimensions using it's GlobalKey on orientation change.

## Steps to Reproduce
created a gist:
https://gist.github.com/kfirufk/4e1de87e7e1eabfed61f58bd0664aef4

## Logs

```
I/flutter ( 4727): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4727): The following assertion was thrown building LayoutBuilder:
I/flutter ( 4727): RenderBox was not laid out: RenderFractionalTranslation#96fc2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4727): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1482 pos 12: 'hasSize'
I/flutter ( 4727): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4727): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4727): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4727):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4727): When the exception was thrown, this was the stack:
I/flutter ( 4727): #2      RenderBox.size (package:flutter/src/rendering/box.dart:1482:12)
I/flutter ( 4727): #3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2458:24)
I/flutter ( 4727): #4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2170:24)
I/flutter ( 4727): #5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2037:39)
I/flutter ( 4727): #6      _MyHomePageState.build.<anonymous closure> (package:flutter_app/main.dart:46:46)
I/flutter ( 4727): #7      OrientationBuilder._buildWithConstraints (package:flutter/src/widgets/orientation_builder.dart:48:12)
I/flutter ( 4727): #8      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:111:26)
I/flutter ( 4727): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter ( 4727): #10     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
I/flutter ( 4727): #11     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
I/flutter ( 4727): #12     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter ( 4727): #13     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1728:13)
I/flutter ( 4727): #14     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
I/flutter ( 4727): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #16     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 4727): #17     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
I/flutter ( 4727): #18     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 4727): #19     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 4727): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter ( 4727): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #41     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3032:13)
I/flutter ( 4727): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #43     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4727): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #45     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4727): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 4727): #57     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter ( 4727): #58     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter ( 4727): #59     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 4727): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter ( 4727): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4727): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 4727): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 4727): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 4727): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter ( 4727): #74     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 4727): #75     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 4727): #76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4727): (elided 10 frames from class _AssertionError and package dart:async)
I/flutter ( 4727): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

 output of running `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-IL)
    • Flutter version 1.2.1 at /Volumes/osx-storage/dev/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zoharzz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] Connected device (1 available)
    • LG H815 • LGH815f981198d • android-arm64 • Android 6.0 (API 23)

```

**Comment by NicolasDionB** [comment] 2019-10-15 19:30
Had this problem too. Any update on this? I'm using Flutter 1.10.14 on master channel.

**Comment by VladyslavBondarenko** [comment] 2020-07-29 08:32
Hi @kfirufk,
the exception is thrown because renderBoxRed doesn't have size property needed for localToGlobal, because findRenderObject() didn't return the RenderObject.

You can see in the doc https://api.flutter.dev/flutter/widgets/Element/findRenderObject.html

> This method will only return a valid result after the build phase is complete. It is therefore not valid to call this from a build method. It should only be called from interaction event handlers (e.g. gesture callbacks) or layout or paint callbacks.

<details>
 <summary>so it will work if you use it not in build function</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  GlobalKey buttonKey=GlobalKey();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:
      OrientationBuilder(builder: (context,orientation) {
        return Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text('get position'),
                onPressed: () {
                  final RenderBox renderBoxRed = buttonKey.currentContext.findRenderObject();
                  final Offset position = renderBoxRed.localToGlobal(Offset.zero);
                  print(position);
                },
              ),
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme
                    .of(context)
                    .textTheme
                    .headline4,
              ),
            ],
          ),
        );
      }),
      floatingActionButton: FloatingActionButton(
        key: buttonKey,
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

</details>

closing since this is working as intended

**Closed by VladyslavBondarenko** 2020-07-29 08:32 UTC
Labels: framework
