### ISSUE TITLE
[Impeller] `dart:ui` Images used in shaders result in wrong color sampled due to forced mipmapped sampling on Impeller

### ISSUE THREAD

**Issue by AlessandroToschi** [flutter/flutter#131194] opened 2023-07-24 15:19 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The images returned by `dart:ui` [decodeImageFromList](https://api.flutter.dev/flutter/dart-ui/decodeImageFromList.html) always have mipmaps when using the [Impeller](https://github.com/flutter/engine/blob/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/lib/ui/painting/image_decoder_impeller.cc#L289) engine.

When sampling these images in a runtime shader between Impeller and Skia, there might be a color mismatch. 
The color sampled using Impeller is wrong compared to the one sampled in Skia because different samplers are used by the two engines.
 Impeller uses by default `nearest` as mipmap filter [[1](https://github.com/flutter/engine/blob/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/impeller/display_list/display_list_dispatcher.cc#L126), [2](https://github.com/flutter/engine/blob/48b54665f5b63a61c28055712dc433d5bd4b135d/impeller/core/sampler_descriptor.h#L21C4-L21C4), [3](https://github.com/flutter/engine/blob/48b54665f5b63a61c28055712dc433d5bd4b135d/impeller/display_list/dl_dispatcher.cc#L451)], while Skia uses none [[1](https://github.com/flutter/engine/blob/48b54665f5b63a61c28055712dc433d5bd4b135d/display_list/skia/dl_sk_conversions.cc#L97), [2](https://github.com/flutter/engine/blob/48b54665f5b63a61c28055712dc433d5bd4b135d/display_list/skia/dl_sk_conversions.h#L45), [3](https://github.com/google/skia/blob/a56bc23bfec78a8c87ffcb4caf59926fccbcc2e6/include/core/SkSamplingOptions.h#L63)].

This affects shaders where sampling a source color must be precise, for example applying a LUT filter to an image.
The LUT color must be the computed one and not demanded by the shader sampler when picking a mipmap.

Attached to this issue you can find a sample project that demonstrates this issue.
If you run it on iOS using Skia, the output image is correct while using Impeller is not.

To overcome this issue, I can think of two solutions:
1. Disable mipmapping when invoking `decodeImageFromList`, as I already implemented in this [commit](https://github.com/AlessandroToschi/engine/commit/6f8ff0e6536b486237b96db07ba914660d928a29). Thus, the sample will choose the only available slice.
2. Add to the impeller sampler the possibility to define a none mipmapping filter.

### Expected results

The shader executed through Skia and Impeller produces the same output.

### Actual results

Skia produces the correct output, while Impeller doesn't.

### Code sample

<details><summary>Code sample</summary>

LUT shader example [GitHub Repo URL](https://github.com/plexagon/lut_impeller_bug/) - [ZIP](https://github.com/plexagon/lut_impeller_bug/archive/refs/heads/main.zip)

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

| Skia | Impeller |
| --- | --- |
| ![IMG_4067](https://github.com/flutter/flutter/assets/6044244/1da27d7d-b243-45bb-8309-47ffe8d2efef) | ![IMG_4066](https://github.com/flutter/flutter/assets/6044244/bd202fcc-b52a-48cd-a9f9-d833e4e77a8b) |
| <img width="563" alt="Screen Shot 2023-07-24 at 17 15 58" src="https://github.com/flutter/flutter/assets/6044244/9fc0ba68-38bc-42e3-8e6f-6cbfc8dec279"> | <img width="552" alt="Screen Shot 2023-07-24 at 17 13 30" src="https://github.com/flutter/flutter/assets/6044244/11b6d3a3-ad85-4e8e-8bb8-f2b31f97a856"> |

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale en-US)
    ! Flutter version 3.10.6
    • Framework revision 3d8478a247 (2 hours ago), 2023-07-24 10:12:39 +0200
    • Engine revision 6f8ff0e653
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Flutter download mirror https://storage.googleapis.com/clay-flutter-storage
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/aleto/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode142.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by chinmaygarde** [comment] 2023-07-24 18:24
Triage: We think this is happening because Skia generally generates mips once the images are used while Impeller generates mips eagerly. We think you'll get the same behavior with Skia if you use the image before sampling from it. This one is a bit tricky since doing this deterministically would require us to allow the caller to control when/if mips are generated.

We have a couple of issues open for assessing our mip strategy that might be relevant for discussion.
* https://github.com/flutter/flutter/issues/127697
* https://github.com/flutter/flutter/issues/123469

**Comment by jonahwilliams** [comment] 2023-07-24 19:35
I think that exposing an option for enabling mips (defaulting to true) at the lowest levels of dart:ui would be a useful feature to include. It would not help in this particular case without code changes to utilize it.

**Comment by jonahwilliams** [comment] 2023-07-24 20:54
See also: https://github.com/flutter/engine/pull/40460

**Comment by AlessandroToschi** [comment] 2023-07-25 07:44
Actually exposing the option to enable mips solves this problem as I implemented in this [commit](https://github.com/AlessandroToschi/engine/commit/6f8ff0e6536b486237b96db07ba914660d928a29).
In our app [Clay](https://app.clayeditor.com) ([iOS](https://apps.apple.com/us/app/clay-story-templates-reels/id1469553582)), disabling mipmapping without changing the sampler (mipmap filtering nearest) solved the issue for the LUT sampling.

I understand this is an edge case since we're doing deterministic sampling. 
It was blocking us from adopting Impeller since LUT sampling is a feature of our app as well as it represents a regression w.r.t. Skia.

**Comment by matanlurey** [comment] 2023-09-27 19:23
I am going to look into this issue.

It's not clear yet exactly what we want to expose (there are some considerations for "what can we support across Skia and Impeller", and "what will perform well [enough] in Impeller"), but I would like to at least be able to resolve this issue definitively (i.e. either "fixed, use X API" or "closed, working as intended, here are some possible workarounds").

Will keep folks updated.

**Comment by matanlurey** [comment] 2023-11-27 23:37
Just to make it clear, I'm unlikely to pick this up anytime soon, so unassigning.

**Comment by matanlurey** [comment] 2024-04-23 20:49
Blocked on https://github.com/flutter/flutter/issues/147259, which is the implementation issue.

**Comment by jonahwilliams** [comment] 2024-05-31 23:46
This was fixed by https://github.com/flutter/engine/pull/52779 . The re-addition of MipFilter::Base means that the nn sampling option works the same as Skia. Thanks @matanlurey  !

**Closed by jonahwilliams** 2024-05-31 23:46 UTC
Labels: engine, P2, e: impeller, team-engine, triaged-engine, slimpeller
