### ISSUE TITLE
[video_play] only play when i use airpods ?

### ISSUE THREAD

**Issue by chavesgu** [flutter/flutter#57784] opened 2020-05-22 05:18 UTC
i use video_play in my ios app.But i use `play()` to play video only work when i use airpods.
If i don't use airpods, video didn't play when i use `play()`, just `value.playing => true`.

Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at
      /Users/guchunwen/Documents/project/flutter-sdk/flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

ios 13.4.1

video_player: ^0.10.11+1

**Comment by iapicca** [comment] 2020-05-22 06:01
Hi @chavesgu 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
(while "playing" the contents in your app w/o airpods),
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by chavesgu** [comment] 2020-05-22 06:11
`flutter doctor -v`

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at
      /Users/guchunwen/Documents/project/flutter-sdk/flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/guchunwen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/guchunwen/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • iPhone        • 00008020-00183131149A002E            • ios • iOS 13.4.1
    • iPhone 11 Pro • 534B84EF-6B11-4DBA-B26E-EC75D68A9D28 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

`flutter run --verbose` 
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone is available at: http://localhost:1024

there is nothing shown when i switch airpods.

`pubspec.yaml`
video_player: ^0.10.11+1

**Comment by chavesgu** [comment] 2020-05-22 06:15
@iapicca   
just official sample

**Comment by iapicca** [comment] 2020-05-22 13:58
Hi @chavesgu 
thanks for your doctor;

can you please provide 
your full `flutter run --verbose`

If the logs are too long
you may attach it as txt file
Thank you

**Comment by chavesgu** [comment] 2020-05-25 00:55
here is full `flutter run --verbose` below.

[flutter run --verbose.txt](https://github.com/flutter/flutter/files/4674735/flutter.run.--verbose.txt)

when i play/pause video, there is nothing shown

**Comment by TahaTesser** [comment] 2020-05-26 08:06
Hi @chavesgu 
Running official example on a physical or simulator has no issue with asset video or network without airpods when testing on latest `stable` and `dev` channel

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details> 

Can you please make to uninstall this app and clone the official repository and run official exampl and try again?
Thank you

**Comment by chavesgu** [comment] 2020-05-29 00:32
@TahaTesser my flutter channel is latest `stable`,  when i use flutter `1.12.x` before,  `video_play` was work well.

**Comment by TahaTesser** [comment] 2020-05-29 07:21
Hi @chavesgu 
This only happens in Flutter? Have you tried to restart your iPhone and try again? Also please upgrade to iOS 13.5, let us know
Thank you

**Comment by chavesgu** [comment] 2020-05-30 13:00
yes，only happens in flutter， other app like bilibili is normal. I restart iphone and upgrade to iOS 13.5, it still unchanged.

**Comment by chavesgu** [comment] 2020-06-02 02:44
@TahaTesser 
Currently, only `play()` is not work. Such as `seekTo()`,when i use this api,the video is seekTo correct position, but it is still not play.

**Comment by chavesgu** [comment] 2020-08-06 01:23
@TahaTesser Hi, brother,   is this issue repaired?

**Comment by chavesgu** [comment] 2020-08-11 00:43
@TahaTesser hey! good news ! when i upgrade ios13.6 , the `play()` api is work correctly.

**Comment by TahaTesser** [comment] 2020-08-11 14:06
Hi @chavesgu 
Looks like it was your device's as we haven't similar issues popup 

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-11 14:06 UTC
Labels: P4, p: first party, p: video_player, platform-ios, plugin
