### ISSUE TITLE
AndroidView not working properly on a Samsung Galaxy S6

### ISSUE THREAD

**Issue by kunit1** [flutter/flutter#23900] opened 2018-11-03 03:37 UTC
## Steps to Reproduce
On Samsung Galaxy S6 the google maps plug in causes the device to freeze and the screen shows flickering black pixels.

Minimal Repro

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapTest extends StatelessWidget {
  final LatLng center = const LatLng(32.0, 34.9);
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: SizedBox(
          width: 300.0,
          height: 300.0,
          child: GoogleMap(
            onMapCreated: onMapCreated,
            options: GoogleMapOptions(
              cameraPosition: CameraPosition(
                target: center,
                zoom: 11.0
              )
            ),
            gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
              Factory<OneSequenceGestureRecognizer>(
                () => EagerGestureRecognizer()
              )
            ].toSet(),
          ),
        ),
      ),
    );
  }

  void onMapCreated(GoogleMapController controller) {
    controller.addMarker(MarkerOptions(
      position: LatLng(
        center.latitude, 
        center.longitude
      ),
      infoWindowText: const InfoWindowText("Test Location", 'AA')
    ));
  }

}
```

```
[√] Flutter (Channel dev, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-CA)
    • Flutter version 0.10.2 at D:\flutter
    • Framework revision d8cbb80206 (8 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\kusay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • SM G920W8 • 0216029abaa90a03 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by braulio94** [comment] 2018-11-03 16:12
I can't use `Factory` in `<Factory<OneSequenceGestureRecognizer>>` where is it coming from?

**Comment by amirh** [comment] 2018-11-04 18:31
Thanks for the report @kunit1!
Would you mind trying the android_views integration test on that device? I'm curious to see if embedding a simple view causes the same issue on the device.

From your local flutter checkout:
```
cd dev/integration_tests/android_views
flutter run
```

Does your device freeze when launching this app?

**Comment by amirh** [comment] 2018-11-04 22:07
Try running `flutter drive` in the android_views directory, it should clone the goldens repo.

**Comment by kunit1** [comment] 2018-11-04 22:36
I ran the test on the device. This is the result:
https://drive.google.com/open?id=1ZKb6zO12Sn02wyiH3bLbUU7_UntB41yc

Touching the screen causes the black portion to flicker. The device is not frozen but the view is corrupted as far as I can see. 
With google maps, similar view corruption occurs but the phone becomes unresponsive to any action including the power button. It eventually restarts on its own after a few minutes.

**Comment by amirh** [comment] 2018-11-19 23:02
It seems that this has regressed with the Skia roll at flutter/engine#6652
I'm continuing to bisect the individual Skia commits on that roll.

**Comment by amirh** [comment] 2018-11-19 23:13
The issue was introduced with google/skia@dc82994 (which also introduced #24402)

@bsalomon

**Comment by bsalomon** [comment] 2018-11-20 17:07
I ran all of Skia's image tests on a GSM (Mali) S6 and don't see any image differences when using sampler objects.

**Comment by kunit1** [comment] 2018-11-20 17:14
Just wanted to mention this issue only happens on Galaxy S6 running android 6.0.x 
Same device with android 7.0, no issue.

**Comment by bsalomon** [comment] 2018-11-20 20:01
@berosoboy Can you install this app on the LG K4 X230 and post the GL_VERSION string here?

https://play.google.com/store/apps/details?id=com.realtechvr.glview&hl=en_US

**Comment by berosoboy** [comment] 2018-11-20 20:41
Of course, @bsalomon .

Here is the screenshot:

![screenshot_20181120-174530](https://user-images.githubusercontent.com/7874200/48801522-57d75680-eceb-11e8-83ba-3d69c43bca6e.png)

**Comment by bsalomon** [comment] 2018-11-20 21:51
Thanks! Looks like it's a similar driver version to the S6 running Android 6, which has "OpenGL ES 3.1 v1.r7p0-03rel0.b596bd02e7d0169c10574b57180c8b57"

**Comment by bsalomon** [comment] 2018-11-21 20:18
I have a speculative fix for this:

https://skia-review.googlesource.com/c/skia/+/172405

It should land in Skia soon.

**Comment by tvolkert** [comment] 2018-11-24 18:36
Fixed by https://skia.googlesource.com/skia/+/a6dddeaac902114677b21cb39f423db0f5557b10 (as soon as that rolls into Flutter)

**Comment by amirh** [comment] 2018-11-25 03:07
I'm keeping this open until we confirm the Skia fix fixes the AndroidView issue.

**Comment by tvolkert** [comment] 2018-11-27 06:41
@amirh the Skia roll has landed in flutter/flutter - are you still seeing the issue?

**Comment by tvolkert** [comment] 2018-11-28 16:46
Ok, second take... can you please try `v0.11.11` (on the latest `dev` and `beta` channels - available via `flutter upgrade`)?  Thanks!

**Comment by amirh** [comment] 2018-11-28 17:03
Confirmed that this is fixed on master (for a Samsung Galaxy S6).

**Closed by amirh** 2018-11-28 17:03 UTC
Labels: a: platform-views, dependency: skia, p: first party, p: maps, severe: crash, waiting for PR to land (fixed), ▣ platform-android

**Comment by aldobm** [comment] 2018-11-29 02:18
**In Huawei VNS-L23 android 6 Works Fine, with update now. FIX Thanks**

[✓] Flutter (Channel master, v0.11.12-pre.5, on Mac OS X 10.13.6 17G65, locale
    en-EC)
    • Flutter version 0.11.12-pre.5 at /Users/aldo/flutter
    • Framework revision 06ec8d3b41 (71 minutes ago), 2018-11-28 15:56:58 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/aldo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0
      (API 26) (emulator)

**Comment by KinsomyJS** [comment] 2018-12-05 07:09
Hi，the same problem happens in Oppo R15，but my oneplus 5 is correct。
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2017.3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)
```

**Comment by huuang** [comment] 2019-03-12 10:23
> Hi，the same problem happens in Oppo R15，but my oneplus 5 is correct。
> 
> ```
> [✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> [!] iOS toolchain - develop for iOS devices (Xcode 9.2)
>     ✗ Verify that all connected devices have been paired with this computer in Xcode.
>       If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
>       To update with Brew, run:
>         brew update
>         brew uninstall --ignore-dependencies libimobiledevice
>         brew uninstall --ignore-dependencies usbmuxd
>         brew install --HEAD usbmuxd
>         brew unlink usbmuxd
>         brew link usbmuxd
>         brew install --HEAD libimobiledevice
>         brew install ideviceinstaller
>     ✗ CocoaPods installed but not initialized.
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.io/platform-plugins
>       To initialize CocoaPods, run:
>         pod setup
>       once to finalize CocoaPods' installation.
> [✓] Android Studio (version 3.2)
> [!] IntelliJ IDEA Community Edition (version 2017.3.6)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.29.1)
> [✓] Connected device (2 available)
> ```
> I created #24974

I am facing the same problem, have you solved it?

**Comment by prashantspandey** [comment] 2020-10-06 18:28
> > Hi，the same problem happens in Oppo R15，but my oneplus 5 is correct。
> > ```
> > [✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
> > [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> >     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> > [!] iOS toolchain - develop for iOS devices (Xcode 9.2)
> >     ✗ Verify that all connected devices have been paired with this computer in Xcode.
> >       If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
> >       To update with Brew, run:
> >         brew update
> >         brew uninstall --ignore-dependencies libimobiledevice
> >         brew uninstall --ignore-dependencies usbmuxd
> >         brew install --HEAD usbmuxd
> >         brew unlink usbmuxd
> >         brew link usbmuxd
> >         brew install --HEAD libimobiledevice
> >         brew install ideviceinstaller
> >     ✗ CocoaPods installed but not initialized.
> >         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
> >         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
> >         For more info, see https://flutter.io/platform-plugins
> >       To initialize CocoaPods, run:
> >         pod setup
> >       once to finalize CocoaPods' installation.
> > [✓] Android Studio (version 3.2)
> > [!] IntelliJ IDEA Community Edition (version 2017.3.6)
> >     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
> >     ✗ Dart plugin not installed; this adds Dart specific functionality.
> > [✓] VS Code (version 1.29.1)
> > [✓] Connected device (2 available)
> > ```
> > 
> > 
> > I created #24974
> 
> I am facing the same problem, have you solved it?

any solutions?
