### ISSUE TITLE
camera: ^0.9.2+2 crashes java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#89538] opened 2021-09-06 10:32 UTC
You can run the camera example app to get the same crash.
Our Android apps are all crashing when users try to upload a new profile photo ```image_picker: ^0.8.4``` is also broken.

```
E/AndroidRuntime(15001): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.polydelic.refreshme/com.polydelic.refreshme.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(15001): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4962)
E/AndroidRuntime(15001): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
E/AndroidRuntime(15001): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(15001): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15001): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15001): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime(15001): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15001): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(15001): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(15001): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15001): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(15001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(15001): Caused by: java.lang.IllegalStateException: Reply already submitted
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.0)
[✓] Connected device (2 available)
```

**Comment by TahaTesser** [comment] 2021-09-06 10:33
Hi @ollydixon 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/88598
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-06 10:33 UTC
Labels: in triage

**Comment by ollydixon** [comment] 2021-09-06 10:34
@TahaTesser no problem, this is a critical bug; I can't see any resolution; by chance do you know a working version?

**Comment by ollydixon** [comment] 2021-09-06 10:44
@TahaTesser this is a package issue, you have linked me to another issue with another package. Maybe you should reopen this since it needs to be fixed on the camera package and not ```io.flutter.embedding.engine.dart.DartMessenger$Reply.reply``` or ```local_auth```

**Comment by ollydixon** [comment] 2021-09-06 10:44
@TahaTesser ```image_picker: ^0.8.4``` also needs to be fixed, but this nightmare of flutter issues seems to miss a lot of stuff
