### ISSUE TITLE
Pub get is not working Waiting for another flutter command to release the startup lock...

### ISSUE THREAD

**Issue by DanGerHOGGISH** [flutter/flutter#63264] opened 2020-08-08 05:53 UTC
Good afternoon. I tried every step in issues like this but none of them worked for me. I reinstalled Android Studio and FLutter SDK several times. But still it is stuck (I used VPN even though did not work). Can you help me out with this ?Thank you.

**Comment by roohaani786** [comment] 2020-08-08 06:14
Hello @DanGerHOGGISH , it seems you have already a flutter run or build command running in. That is what stopping you to run pub get. Try terminating all the commands. Also run flutter doctor and have a look, if there are any issues. Let me know the whole story (what version you are using etc) so that I can help.

**Comment by DanGerHOGGISH** [comment] 2020-08-08 06:19
> Hello @DanGerHOGGISH , it seems you have already a flutter run or build command running in. That is what stopping you to run pub get. Try terminating all the commands. Also run flutter doctor and have a look, if there are any issues. Let me know the whole story (what version you are using etc) so that I can help.
![waiting](https://user-images.githubusercontent.com/67454411/89703916-d44f1480-d968-11ea-81f8-d13cf41cb409.jpg)
well i have reinstalled everything Flutter SDK 1.20.1 version and AS (4.0.1) version

**Comment by DanGerHOGGISH** [comment] 2020-08-08 07:19
![as waiting1](https://user-images.githubusercontent.com/67454411/89704863-5fcca380-d971-11ea-822f-76862eac6d00.jpg)

i created a new flutter project and it does not download anything. What should i do ?

**Comment by DanGerHOGGISH** [comment] 2020-08-08 11:12
My friends are complaining too.  is this not working properly in windows?

**Comment by DanGerHOGGISH** [comment] 2020-08-08 13:29
i have installed 1.12.13 1.17.5 1.20.0 1.20.1 none of them worked and now i cannot create in an android studio a flutter project please help me out

**Comment by DanGerHOGGISH** [comment] 2020-08-08 17:41
i tried in my 3 laptops i could not create a flutter project neither of them. but i could open the an existing flutter project but could not run pub get it just stuck. what is going on ?

**Comment by DanGerHOGGISH** [comment] 2020-08-09 03:12
![image](https://user-images.githubusercontent.com/67454411/89724076-f358af80-da17-11ea-97f6-992aefedb46a.png)

**Comment by SivaramNalliboyana** [comment] 2020-08-09 09:01
**1. open your terminal to kill running dart instances. And then run this command**
`taskkill /F /IM dart.exe`
**1. Remove lockfile**
Lockfile you can find at:
`<flutter folder>/bin/cache/lockfile`

Also try restarting your pc and shutting down your pc

**Comment by DanGerHOGGISH** [comment] 2020-08-09 10:15
> taskkill /F /IM dart.exe
Hi. I did restarted several times. Tried everything was written in the stackoverflow and github but none of them worked. I tried many times what you recommended. Thank you for your reply

**Comment by TahaTesser** [comment] 2020-08-10 13:22
Hi @DanGerHOGGISH 
This doesn't look like flutter issue since this is happening on all flutter versions 
Please raise this issue on `dart-lang/pub, on their dedicated GitHub [repository](https://github.com/dart-lang/pub/issues)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-10 13:22 UTC

**Comment by Ashok-Varma** [comment] 2020-08-10 18:25
Hi @TahaTesser can we reopen this ?
I think, the error related to flutter `waiting for another flutter command to release the startup lock..`.
As dart comes packaged with flutter, so change in flutter version also changes the dart version.
`happening on all flutter versions => happening on all dart versions`
So based on this, we can't boil down the error is from dart

Please correct me if i'm missing something, thank you.

**Comment by TahaTesser** [comment] 2020-08-11 13:42
This seems to be related to pub and something related to network for pub, as it is not reproducible for us
