### ISSUE TITLE
WidgetSpans cause incorrect line breaking with newline characters.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#39149] opened 2019-08-23 22:14 UTC
When using `WidgetSpan`s in some conditions, the text after will sometimes not wrap and continue on out of bounds.

Example (as reported by @MasiaVittorio): 
![image](https://user-images.githubusercontent.com/1887398/63626581-99699a80-c5b8-11e9-9421-a20b129f9767.png)

**Comment by GaryQian** [comment] 2019-08-23 22:16
Split off of https://github.com/flutter/flutter/pull/38699.

Repro posted there: https://pastebin.com/nWbDjq6S courtesy of @MasiaVittorio

**Comment by MasiaVittorio** [comment] 2019-08-23 23:30
@GaryQian seems odd that the issue is not happening on your device.

My device is a OnePlus 3T. Now I'm going to bed but tomorrow I'll try to test it on the emulator too.

Make sure you tap on the FAB to toggle the "\n" in the text!

**Comment by GaryQian** [comment] 2019-08-23 23:53
I have noticed it is touchy and repros on certain widths and not others from the other instance where I saw this. Different devices have different pixel ratios and screen resolutions.

**Comment by MasiaVittorio** [comment] 2019-08-24 12:43
I don't know if this helps, but here is my flutter doctor results:
https://pastebin.com/CtfDnUcv

And here the verbose one: https://pastebin.com/BC9YeFfR

And here what I see on my OP3T with the app I posted yesterday (in release mode, but it is the same in debug mode)
https://i.imgur.com/IAPi6HD.png
https://i.imgur.com/OmgymK7.png

**Comment by GaryQian** [comment] 2019-12-12 23:22
We have since landed some changes around this area, are people still seeing this happen?

**Comment by VladyslavBondarenko** [comment] 2020-02-17 12:36
It seems to be fixed, closing.
Could everyone who still has this problem please file a new issue with the exact description, code sample for reproducing and the output of `flutter doctor -v` please

**Closed by VladyslavBondarenko** 2020-02-17 12:36 UTC
Labels: a: typography, framework, waiting for customer response
