### ISSUE TITLE
Transparent emojis on Android when using a bold TextStyle

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#16582] opened 2018-04-14 02:39 UTC
Emojis are transparent (again? #11108) when using a bold TextStyle. 
Wasn't an issue before I updated from ~v0.2.1 to newest commit.

Works fine on iOS.

## Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Emoji missing Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        appBar: new AppBar(
        ),
        body: new Center(
          child: new Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              new Text(
                'Emoji: 🍜 12345',
                style: new TextStyle(fontWeight: FontWeight.w900),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

```
## Flutter Doctor
[✓] Flutter (Channel master, v0.2.12-pre.33, on Mac OS X 10.13.4 17E199, locale de-DE)
    • Flutter version 0.2.12-pre.33 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision ea30c95dc9 (2 hours ago), 2018-04-13 17:02:14 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/valauskasmodestas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.3317.48

[✓] Connected devices (2 available)
    • LG D802  • LGD8028d47a899                       • android-arm • Android 5.0.2 (API 21)
    • iPhone X • A1223CE9-152A-48EA-8C14-94C467CBF812 • ios         • iOS 11.3 (simulator)
```

**Comment by jason-simmons** [comment] 2018-04-26 22:05
This is a regression in Skia, introduced in:
    https://github.com/google/skia/commit/5ddb30862509967eca24ba3831cc11ed5396eee7

Filed https://bugs.chromium.org/p/skia/issues/detail?id=7878

**Comment by SuitMonkeyB** [comment] 2018-08-31 12:08
Has this issue gotten any further in being resolved?

**Comment by najeira** [comment] 2018-09-03 09:59
It occur with v0.5.1.

**Comment by zoechi** [comment] 2018-09-03 10:04
@najeira can you please also check in beta 0.6.0?

**Comment by bungeman** [comment] 2018-09-07 19:36
I think this was fixed in Skia with https://skia-review.googlesource.com/c/skia/+/150467 , which rolled into Flutter earlier this week.

**Comment by bungeman** [comment] 2018-09-07 22:48
Note that I've tried building the engine and running the example above with all new all the things, and I may be doing something wrong, but I'm still reproducing the original issue. Unfortunately, I can't seem to capture an skp which actually demonstrates the issue at the moment. However, putting some print statements down inside Skia shows that Skia's FreeType believes that Noto Color Emoji does not have a path, but Flutter's FreeType does seem to think that the same Noto Color Emoji does have a path. I'm not entirely sure what the difference between these FreeTypes might be, since even if I rebase Flutter's FreeType up to FreeType's (real) current master it seems to still think Noto Color Emoji has an outline. At this point I don't think Skia is really doing anything incorrectly, but something about the way FreeType is being built in Flutter maybe?

**Comment by bungeman** [comment] 2018-09-17 22:36
It appears that the Flutter build of FreeType is trying to autohint the glyph and creating an empty path instead of just bailing on the autohinting. I'm not sure why Skia's build isn't doing this, but if autohinting is forced the same behavior can be seen. I think this is an issue in FreeType (if a glyph doesn't have any outline at all it can't really be autohinted), I'll see if there's any way to work around it.

**Comment by jason-simmons** [comment] 2018-09-17 22:59
`SkScalerContext_FreeType` has code that sets the FT_LOAD_NO_AUTOHINT flag if `kForceAutohinting_Flag` is off.  But it's gated behind an `#ifdef SK_BUILD_FOR_ANDROID_FRAMEWORK`:

https://github.com/google/skia/blob/master/src/ports/SkFontHost_FreeType.cpp#L880

The emoji in this example renders as expected if I remove the `#ifdef`.

Should this code be enabled in Flutter's build of Skia?

**Comment by SuitMonkeyB** [comment] 2018-09-17 23:34
I'm so happy this issue is progressing.

**Comment by najeira** [comment] 2018-12-10 08:39
It works on v1.0.0

**Comment by zoechi** [comment] 2018-12-10 08:43
@najeira thanks for confirming.
I'm going to close.
Feel free to add a comment to have it reopened if you still experience this issue or create a new one.

**Closed by zoechi** 2018-12-10 08:43 UTC
Labels: a: typography, dependency: skia, waiting for PR to land (fixed)
