### ISSUE TITLE
ScrollBar renders incorrectly

### ISSUE THREAD

**Issue by ristiisa** [flutter/flutter#81027] opened 2021-04-23 07:00 UTC
When enough text is added to the TextField the height will grow. When text is removed so that the TextField height is shrinking the ScrollBar renders incorrectly.

![image](https://user-images.githubusercontent.com/514571/115831221-fbc40f80-a419-11eb-8576-826d10b4d6af.png)

https://user-images.githubusercontent.com/514571/115831769-b6541200-a41a-11eb-9908-f813aa774477.mp4

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Scaffold(
      body: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        ConstrainedBox(constraints: BoxConstraints(maxHeight: 200), child: Row(children: [
          Expanded(child: Scrollbar(child: TextField(
            autocorrect: false,
            enableSuggestions: false,
            keyboardType: TextInputType.multiline,
            textInputAction: TextInputAction.newline,
            maxLines: null,
            decoration: InputDecoration(
              hintText: "Message",
              border: OutlineInputBorder(borderSide: BorderSide(color: Colors.black))
            ),
          ))),
          SizedBox(width: 5),
          Container(height: 40, width: 40, child: Icon(Icons.send)),
        ]))
      ]
    ))
  );
}
```

</details>

<details>
  <summary>flutter doctor</summary>

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.1 20D74 darwin-x64, locale en-EE)
    • Flutter version 2.0.5 at /Users/silver/flutter
    • Framework revision adc687823a (7 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
</details>

**Comment by pedromassangocode** [comment] 2021-04-23 08:17
I can reproduce this issue on latest stable channel.

FYI, on latest master the TextField widget already have a built-in Scrollbar (may have been introduced by https://github.com/flutter/flutter/pull/78588/files?) but that built-in scrollbar has this same issue as well.

Cc @Piinks

**Comment by HansMuller** [comment] 2021-04-23 15:59
CC @Piinks @xu-baolin

**Comment by Piinks** [comment] 2021-04-23 16:55
This looks like a duplicate of https://github.com/flutter/flutter/issues/67690

In the attached video, it looks like  as new lines are added, the size (or pixels) of the Scrollable is changing. The Scrollbar is informed by scroll notifications, so until you scroll the scrollbar cannot update.

**Comment by pedromassangocode** [comment] 2021-05-14 12:59
Closing as duplicate of https://github.com/flutter/flutter/issues/67690. For anyone interested in this issue, please follow up in https://github.com/flutter/flutter/issues/67690 and subscribe for updates.

Thank you

**Closed by pedromassangocode** 2021-05-14 12:59 UTC
Labels: a: text input, f: material design, f: scrolling, found in release: 2.0, found in release: 2.2, framework, has reproducible steps, waiting for customer response
