### ISSUE TITLE
Code suggestion for async/dispose/setState no longer works in Flutter 3.0.2

### ISSUE THREAD

**Issue by khanahsan** [flutter/flutter#106724] opened 2022-06-28 08:00 UTC
I'm using flutter stable version 3.0.2 and dart 2.17.3. Every thing is ok as you see in below picture:

![image](https://user-images.githubusercontent.com/18083065/176125011-7be43aaa-7129-4404-826f-23f8ad68c82a.png)

Code suggestion for async/initState/dispose/setState no works in android Studio. 
below is the screenshots: 
![1](https://user-images.githubusercontent.com/18083065/176127077-aa8d1bdb-5685-401e-a1ac-a41f48473122.png)

![image](https://user-images.githubusercontent.com/18083065/176127902-752d1156-54d3-46ab-90b7-83e33d99d2a6.png)

Please look into it and resolve it

**Comment by exaby73** [comment] 2022-06-28 08:47
In your doctor output, Android Studio is asking you to install the Flutter plugin. Please install the latest version of the plugin or update it and try again.

**Comment by khanahsan** [comment] 2022-06-28 09:34
> 

![image](https://user-images.githubusercontent.com/18083065/176145692-6366dfd4-277f-4170-87b5-1dd35ce5a50c.png)
flutter and dart plugin is already updated as you see in screenshot

**Comment by khanahsan** [comment] 2022-06-28 10:21
> 

![image](https://user-images.githubusercontent.com/18083065/176155894-58148016-13d2-4c94-8ae9-e5d06ce85d8c.png)
i try in vscode it works fine in vs code. But in Android Studio i still face this problem

**Comment by exaby73** [comment] 2022-06-28 11:30
This might be a regression. Try upgrading to 3.0.3 and see if it still persists. Anyhow, this issue is a duplicate of https://github.com/dart-lang/sdk/issues/49027. Please follow up there. I'm closing this issue since it's not a bug with Flutter.

**Closed by exaby73** 2022-06-28 11:30 UTC
Labels: in triage
