### ISSUE TITLE
Flutter pauses scrolling every 90s

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11489] opened 2017-08-02 21:59 UTC
I thought I had this on file, but I can't find it.

My understanding is we currently have no hinting to the Dart VM of when we should GC (i.e. not when we're scrolling).  Last I talked to @abarth he mentioned we just GC every 90s or so, which induces a missed frame.  We could be smarter and let the Dart VM know when is a good time to GC.

FYI @a-siva

**Comment by Hixie** [comment] 2017-08-02 22:09
Dupe of https://github.com/flutter/flutter/issues/9594

**Closed by Hixie** 2017-08-02 22:09 UTC
