### ISSUE TITLE
large_image_changer_perf_android is 2.44% flaky

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#82747] opened 2021-05-17 21:27 UTC
The benchmark test large_image_changer_perf_android has a flaky ratio 2.44%, which is above our self-imposed 2% threshold.

(Creating this issue as part of the gardener rotation.)

**Comment by zanderso** [comment] 2021-05-17 21:33
This is due to https://github.com/flutter/flutter/issues/82142.

**Comment by zanderso** [comment] 2021-05-20 04:22
The cause of the flakiness has been addressed by fixing #82142, so closing this as presumed fixed.

**Closed by zanderso** 2021-05-20 04:22 UTC
Labels: P1, d: devtools, team: flakes, tool
