### ISSUE TITLE
Detect locked keychain when building

### ISSUE THREAD

**Issue by kevmo314** [flutter/flutter#115700] opened 2022-11-19 17:48 UTC
## Use case

Hi, I spent a good three hours just now trying to debug why `flutter run -v` did not work but building from XCode did. Turns out the answer is because I am running `flutter run -v` via SSH and XCode via Remote Desktop, so the keychain was locked in the SSH terminal.

There's a lot of documentation around the error that I saw, eg https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen, but turns out the answer was actually deep in the flutter docs: https://docs.flutter.dev/development/tools/vs-code#selecting-a-target-device

## Proposal

Can `flutter run` detect a locked keychain or codesign failure and either run `security unlock-keychain` automatically or surface a more useful error message?

**Comment by darshankawar** [comment] 2022-11-21 06:34
Treating this as a potential proposal and for team's insights.

**Comment by christopherfujino** [comment] 2023-07-27 19:15
@kevmo314 to clarify, the error you saw was `errSecInternalComponent` during codesigning?

If we pattern match on this error and give a more userful error message, I'm not sure we can say for sure this error is due to a locked keychain, but it would be reasonable to say it's a "possible" reason and try unlocking.

**Comment by christopherfujino** [comment] 2023-07-27 22:39
From looking at `man security`, I found:

```
security list-keychains
```

Which will list the present keychains, but not whether they are locked or not. Also, I don't know if we have a way to detect which keychain is the one with the certificate we need to codesign.

Another question, were you able to run `security unlock-keychain` remotely over ssh? I thought you needed to press a button in the UI to allow this.

**Comment by jmagman** [comment] 2024-09-10 17:28
This is a duplicate of https://github.com/flutter/flutter/issues/106876#issuecomment-1183869558

**Closed by jmagman** 2024-09-10 17:28 UTC
Labels: tool, c: proposal, P2, team-tool, triaged-tool
