### ISSUE TITLE
Nested containers behavior contradicts `Container` documentation

### ISSUE THREAD

**Issue by fctorial** [flutter/flutter#92094] opened 2021-10-19 13:47 UTC
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: TestPage()));
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: 200,
        height: 200,
        color: Colors.blue,
        child: Container(
          width: 100,
          height: 100,
          color: Colors.green,
        ),
      ),
    );
  }
}
```

This code is expected to render a green box inside a blue box, as suggested by the following line from `Container` documentation:

> If the widget has no child and no alignment, but a height, width, or constraints are provided, then the Container tries to be as small as possible given the combination of those constraints and the parent's constraints.

But instead the following is rendered:

![image](https://user-images.githubusercontent.com/58381615/137920011-02ea0c70-38de-47bd-a324-2c1d9f5dd77b.png)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: TestPage()));
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: 200,
        height: 200,
        color: Colors.blue,
        child: Container(
          color: Colors.green,
          child: Text('test'),
        ),
      ),
    );
  }
}
```
This code is expected to render some text with a green background as big as the text according to the following rule:

> Otherwise, the widget has a child but no height, no width, no constraints, and no alignment, and the Container passes the constraints from the parent to the child and sizes itself to match the child.

But instead the following is rendered:

![image](https://user-images.githubusercontent.com/58381615/137922479-c9e6f5a6-541c-4401-aea5-ad44b5326c83.png)

Is this a bug? If not, how can the actual behavior of the sdk be deduced from the `Container` api documentation:

https://api.flutter.dev/flutter/widgets/Container-class.html

**Comment by fctorial** [comment] 2021-10-20 08:24
@darshankawar I know about the workarounds. In these cases, adding alignment to the outer container causes the apps to render as expected. But the issue is that the widget are behaving in a way that doesn't match their documentation.

**Comment by darshankawar** [comment] 2021-10-21 05:58
Thanks for the update. There was a similar old issue reporting same behavior and use case, https://github.com/flutter/flutter/issues/19289 which got closed due to inactivity.


I am keeping this open for further insights from the team.

/cc @Hixie

**Comment by footurist** [comment] 2021-11-10 19:33
Any updates on this? I just spend a LONG time figuring out why this happens and I always read documentation thoroughly. It simply didn't occur to me that such a simple, fundamental aspect of the framework would still contain a bug considering how far Flutter has come. I realize Container's layout behaviour is destined to be complicated, but this is simply unintended behaviour according to the documentation and should not be done away with via a workaround imo.

**Comment by footurist** [comment] 2021-11-10 21:37
After some intense thinking and further reading of documentation I came to the conclusion that actually everything here is intended behaviour, it's just complex, caused by different layout rules for specific widgets.

For the case that another confused person comes across this issue I will explain the two situations above:


1.

> If the widget has no `child` and no alignment, but a `height`, `width`, or `constraints` are provided, then the `Container` tries to be as small as possible given the combination of those `constraints` and the parent's `constraints`.

What has been rendered as a result of the code above is actually compliant with this, because:

1. The `MaterialApp` passes the screen's `size` as tight `constraints` to the `Scaffold`.
2. The `Scaffold` now loosens these `constraints` (min: 0, max: screen's size).
3. The blue `Container` sizes itself to `Size(200, 200),` which lies within the incoming `constraints`.
4. By doing that the blue `Container` also tightened up the `constraints` for its child to `BoxConstraints(minWidth: 200, maxWidth: 200, minHeight: 200, maxHeight: 200)` again.
5. The green `Container` receives the tightened `constraints` and sizes itself accordingly.

The key here is that 

> the combination of those `constraints` and the parent's `constraints`

means that the green `Container` can't loosen up the incoming tight `constraints`. It simply doesn't have that feature.


2.

> Otherwise, the widget has a `child` but no `height`, no `width`, no `constraints`, and no `alignment`, and the `Container` passes the `constraints` from the parent to the `child` and sizes itself to match the `child`.

What has been rendered as a result of the code above is actually compliant with this, because:

1. Same steps as in the first example.
2. The green `Container` passes the incoming tight `constraints` from the blue `Container` to its `child`, the `Text` widget.
3. The `Text` widget can't loosen up the `constraints`, so it sizes itself to `Size(200, 200)` accordingly (the `fontSize` remains the same).
4. The green `Container` sizes itself to match the `child`, to `Size(200, 200)`.

The reason that adding the `alignment` property to the parent `Container` in both of these situations solves the problem is that this wraps the `child` `Container` in an `Align` widget behind the scenes, which is one of several widgets that can loosen up incoming tight `constraints`.
Other widgets that do that are the `Scaffold` and the `Center`, which extends `Align`.

The only thing I'm unsure about is if there is a quick way to determine if a widget can loosen up incoming tight constraints (I haven't read anything in the `Scaffold`'s documentation about this). Maybe this is an improvable part of the documentation overall?

Since this perfectly explains the behaviour I suggest this issue can be closed.

**Comment by darshankawar** [comment] 2021-11-11 05:34
Thanks for digging in and for the explaination.
Closing this as resolved based on above comment.

**Closed by darshankawar** 2021-11-11 05:34 UTC
Labels: framework, f: material design, d: api docs, documentation, passed first triage
