### ISSUE TITLE
[google_sign_in] Update GoogleSignIn to 6.0.0

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#101295] opened 2022-04-04 14:22 UTC
`google_sign_in` plugin does not work on an Apple M1 device, it throws the following error:

> Error (Xcode): In [/.../ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn]()(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '[/.../ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn]()' for architecture arm64

However, the issue has been fixed in GoogleSignIn 6.0.0, source: https://github.com/google/GoogleSignIn-iOS/releases/tag/6.0.0

If the plugin is updated it should work again.

**Comment by stuartmorgan** [comment] 2022-04-04 17:09
Duplicate of https://github.com/flutter/flutter/issues/86436

**Closed by stuartmorgan** 2022-04-04 17:09 UTC
