### ISSUE TITLE
Text widget show emoji'🌙' increase 100M memory

### ISSUE THREAD

**Issue by Ning-Wang** [flutter/flutter#95732] opened 2021-12-23 13:18 UTC
[flutter_emoji_memory.zip](https://github.com/flutter/flutter/files/7769449/flutter_emoji_memory.zip)

I user Flutter moudule in my iOS app。A page onely use TextWidge show  string。When string contain 🌙，memory increase  a lot. Just like the video in zip。 

Flutter module debug and release were both happened。
Test iPhone ： iPhone XS（iOS 14.6） iPhone XS max（iOS 15.1）
Flutter sdk：2.5.3
Xcode：12.5.1

Looking forward to your reply. Thanks.

**Comment by cedvdb** [comment] 2021-12-24 00:07
translated if not clear enough: When a string contains a moon emoji, memory size of the app increases by 100 MB

**Comment by Ning-Wang** [comment] 2021-12-24 13:00
不用键盘输入。
使用textwidget直接显示字符串，然后重新setstatus，让textwidget显示月亮，内存会升高。

**Comment by Ning-Wang** [comment] 2021-12-24 13:01
No keyboard input.
Use Textwidget to display the string directly, then reset setStatus so that Textwidget displays the moon, and memory will increase.

**Comment by mamuseferha** [comment] 2021-12-28 09:46
Hi @Ning-Wang, I verified this issue on the latest master and stable channel using the code sample below and it is not reproducible. The memory allocation remains the same when I added a moon emoji to the `Text` widget.

Can you please upgrade to the latest stable channel `2.8.1 `and check if the issue persists? If so, please provide your` flutter doctor -v` as well as a minimal reproducible code sample. 

<details>
<summary>output</summary>

 with moon emoji
<img src="https://user-images.githubusercontent.com/92717368/147552904-b86e133a-4730-4c7c-8efa-acca6d4b0285.png" width="1100" height="550" />

without moon emoji

<img src="https://user-images.githubusercontent.com/92717368/147552938-3b79ec82-d8c0-4ea8-8fca-52324a93c3c3.png" width="1100" height="550" />



</details>

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in a Flutter IDE). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: const Text('🌙'),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.205, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.205 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ec059c994 (3 hours ago), 2021-12-28 00:29:08 -0500
    • Engine revision 31fcaf3ce4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by Ning-Wang** [comment] 2021-12-30 07:42
I upgraded the Fluttered version to 2.8.1. The problem still exists.
The video and source code are in flutter_emoji_memory.zip

[flutter_emoji_memory.zip](https://github.com/flutter/flutter/files/7791923/flutter_emoji_memory.zip)

**Comment by Ning-Wang** [comment] 2021-12-30 07:47
Click the button '点我' string turns into the moon.
Use Xcode to view memory, memory increased after switching.


`
// import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';
// import 'package:flutter_easyrefresh/easy_refresh.dart';

class QuanziPage3 extends StatefulWidget {
  const QuanziPage3({
    Key? key,
  }) : super(key: key);

  @override
  _QuanziPageState3 createState() => _QuanziPageState3();
}

class _QuanziPageState3 extends State<QuanziPage3> {
  bool textControl = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter emoji'),
      ),
      floatingActionButton: FloatingActionButton(
          child: Container(
            color: Colors.red,
            child: const Text('点我'),
          ),
          onPressed: () {
            setState(() {
              textControl = !textControl;
            });
          }),
      body: Center(
          child: Column(
        children: [
          Text(textControl == false ? '123测试' : '🌙'),
        ],
      )),
    );
  }
}

flutter doctor
<img width="747" alt="截屏2021-12-30 下午3 46 51" src="https://user-images.githubusercontent.com/20783790/147731787-59fd678d-56c6-4250-b8e4-cb54c1e0a5da.png">
`

**Comment by Ning-Wang** [comment] 2021-12-30 07:55
Below is a screenshot of the phone compared to xcode's memory display.
If Flutter_emoji_memory.zip cannot be downloaded, take a look at these screenshots
<img width="377" alt="截屏2021-12-30 下午3 49 42" src="https://user-images.githubusercontent.com/20783790/147732219-07165eea-7285-4064-9746-9762899da23f.png">
<img width="368" alt="截屏2021-12-30 下午3 49 56" src="https://user-images.githubusercontent.com/20783790/147732236-a0e419aa-665c-4b98-b893-9b662f670419.png">
<img width="393" alt="截屏2021-12-30 下午3 48 57" src="https://user-images.githubusercontent.com/20783790/147732243-68eda5eb-741c-44ff-a695-211967466f70.png">
<img width="397" alt="截屏2021-12-30 下午3 49 14" src="https://user-images.githubusercontent.com/20783790/147732248-1f2a717d-7fb2-45c1-9539-cc845542061c.png">

**Comment by mamuseferha** [comment] 2021-12-30 08:41
Hi @Ning-Wang, I verified this on the latest stable and master channel running in profile mode and the issue is reproducible.

<details>
<summary>output</summary>

**before showing moon emoji**

<img width="1494" alt="Screen Shot 2021-12-30 at 9 29 17 AM" src="https://user-images.githubusercontent.com/92717368/147735374-541af46a-f31c-4071-a2bc-add05afe6267.png">

**after showing moon emoji**

<img width="1494" alt="Screen Shot 2021-12-30 at 9 29 37 AM" src="https://user-images.githubusercontent.com/92717368/147735383-d3beb454-ee4d-46fa-8abd-d1ea5d51a1f9.png">

**when moon emoji is replaced with text**

<img width="1494" alt="Screen Shot 2021-12-30 at 9 32 41 AM" src="https://user-images.githubusercontent.com/92717368/147735398-4c3d4551-9010-4f29-8eec-ed61a8ee75bf.png">

</details>

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: QuanziPage3(),
    );
  }
}

class QuanziPage3 extends StatefulWidget {
  const QuanziPage3({
    Key? key,
  }) : super(key: key);

  @override
  _QuanziPageState3 createState() => _QuanziPageState3();
}

class _QuanziPageState3 extends State<QuanziPage3> {
  bool textControl = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter emoji'),
      ),
      floatingActionButton: FloatingActionButton(
          child: Container(
            color: Colors.red,
            child: const Text('点我'),
          ),
          onPressed: () {
            setState(() {
              textControl = !textControl;
            });
          }),
      body: Center(
          child: Column(
        children: [
          Text(textControl == false ? '123测试' : '🌙'),
        ],
      )),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
    • iPhone 13 (mobile)      • E0F828CA-CF98-473C-8F5E-DAB4DE53A466     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.210, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.210 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 95e555344d (13 hours ago), 2021-12-30 02:29:19 +0700
    • Engine revision 01d19ceef4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
    • iPhone 13 (mobile)      • E0F828CA-CF98-473C-8F5E-DAB4DE53A466     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by Ning-Wang** [comment] 2021-12-31 08:23
On my iPhone, the memory growth after showing the moon will not be released. The increased memory remains after switching back to text. I haven't tested this on An Android phone.
My phone is an iPhone Xs. IOS 14.6.
thank you

**Comment by TahaTesser** [comment] 2021-12-31 09:53
duplicate of https://github.com/flutter/flutter/issues/69566

**Closed by TahaTesser** 2021-12-31 09:53 UTC
Labels: platform-ios, framework, a: typography, perf: memory, has reproducible steps, found in release: 2.8, found in release: 2.9
