### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by alzildan** [flutter/flutter#142031] opened 2024-01-23 05:48 UTC
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#5      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136:12)
<asynchronous suspension>
#6      ErrorHandlingFile.writeAsString.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:247:24)
<asynchronous suspension>
#7      _run (package:flutter_tools/src/base/error_handling_io.dart:559:12)
<asynchronous suspension>
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:38:3)
<asynchronous suspension>
#9      _writeCppPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:946:3)
<asynchronous suspension>
#10     writeWindowsPluginFiles (package:flutter_tools/src/flutter_plugins.dart:935:3)
<asynchronous suspension>
#11     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1176:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:378:5)
<asynchronous suspension>
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:366:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.22621.3007], locale en-ID)
    • Flutter version 3.16.8 on channel stable at C:\Users\alzil\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (6 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\alzil\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34511.84
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at C:\Users\alzil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.144

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 67457e669f79e9f8d13d7a68fe09775fefbb79f4

**Comment by dam-ease** [comment] 2024-01-23 07:33
Closing as a duplicate of https://github.com/flutter/flutter/issues/141516

**Closed by dam-ease** 2024-01-23 07:33 UTC
Labels: in triage
