### ISSUE TITLE
url_launcher example from readme throws exception in nullsafety prerelease

### ISSUE THREAD

**Issue by nohli** [flutter/flutter#71725] opened 2020-12-04 16:52 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: https://pub.dev/packages/url_launcher#encoding-urls 
3. Flutter run 

**Expected results:** 

Mailto works like in the example

**Actual results:** 

```
PlatformException(
        code: 'NOT_A_WEB_SCHEME',
        message: 'To use webview or safariVC, you need to pass'
            'in a web URL. This $urlString is not a web URL.')
```

**Responsible code:** 

```
  String urlString, {
  bool forceSafariVC,
  bool forceWebView,
  bool enableJavaScript,
  bool enableDomStorage,
  bool universalLinksOnly,
  Map<String, String> headers,
  Brightness statusBarBrightness,
  String webOnlyWindowName,
}) async {
  assert(urlString != null);
  final Uri url = Uri.parse(urlString.trimLeft());
  final bool isWebURL = url.scheme == 'http' || url.scheme == 'https';
  if ((forceSafariVC == true || forceWebView == true) && !isWebURL) {
    throw PlatformException(
        code: 'NOT_A_WEB_SCHEME',
        message: 'To use webview or safariVC, you need to pass'
            'in a web URL. This $urlString is not a web URL.');
  }
```
https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/lib/url_launcher.dart

was changed to:

```
  String urlString, {
  bool forceSafariVC = true,
  bool forceWebView = false,
  bool enableJavaScript = false,
  bool enableDomStorage = false,
  bool universalLinksOnly = false,
  Map<String, String> headers = const <String, String>{},
  Brightness? statusBarBrightness,
  String? webOnlyWindowName,
}) async {
  final Uri url = Uri.parse(urlString.trimLeft());
  final bool isWebURL = url.scheme == 'http' || url.scheme == 'https';
  if ((forceSafariVC == true || forceWebView == true) && !isWebURL) {
    throw PlatformException(
        code: 'NOT_A_WEB_SCHEME',
        message: 'To use webview or safariVC, you need to pass'
            'in a web URL. This $urlString is not a web URL.');
  }
```
https://github.com/flutter/plugins/blob/nnbd/packages/url_launcher/url_launcher/lib/url_launcher.dart

...so, since now `forceSafariVC` has become true by default, the assertion
`((forceSafariVC == true || forceWebView == true) && !isWebURL)`
is also true by default for all schemes except ` url.scheme == 'http' || url.scheme == 'https'` (isWebURL),
resulting in the example throwing the above exception.

To send a mail without this exception, you now explicitly have to pass forceSafariVC = false (which is not expected).

If I can help, I would like to open a pull request for fixing the issue.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/achim/flutter
    • Framework revision 022b333a08 (2 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/achim/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0
```

</details>

**Comment by TahaTesser** [comment] 2020-12-07 12:29
Hi @nohli 
Thanks for filing the issue, I can reproduce the issue

<details> 
<summary>code sample</summary> 

```dart
mport 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final Uri _emailLaunchUri = Uri(
      scheme: 'mailto',
      path: 'smith@example.com',
      queryParameters: {'subject': 'Example Subject & Symbols are allowed!'});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          const url = 'https://flutter.dev';
          if (await canLaunch(_emailLaunchUri.toString())) {
            await launch(_emailLaunchUri.toString(), forceSafariVC: true);
          } else {
            throw 'Could not launch ${_emailLaunchUri.toString()}';
          }
        },
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>logs</summary> 

```bash
Running "flutter pub get" in url_launcher_example...
Launching lib/main.dart on Taha’s iPad in debug mode...
 package:triage/main.dart
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile
Xcode build done.                                           30.7s
Connecting to VM Service at ws://127.0.0.1:64538/nrWE8tAwnsk=/ws
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
[38;5;244m#0      launch[39;49m
 package:url_launcher/url_launcher.dart
[38;5;248m#1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
[38;5;244m<asynchronous suspension>[39;49m
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
[38;5;244m#0      launch[39;49m
 package:url_launcher/url_launcher.dart
[38;5;248m#1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
[38;5;244m<asynchronous suspension>[39;49m
Reloaded 1 of 541 libraries in 320ms.
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
[38;5;244m#0      launch[39;49m
 package:url_launcher/url_launcher.dart
[38;5;248m#1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
[38;5;244m<asynchronous suspension>[39;49m
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
[38;5;244m#0      launch[39;49m
 package:url_launcher/url_launcher.dart
[38;5;248m#1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
[38;5;244m<asynchronous suspension>[39;49m
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
[38;5;244m#0      launch[39;49m
 package:url_launcher/url_launcher.dart
[38;5;248m#1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
[38;5;244m<asynchronous suspension>[39;49m

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
    • Web Server (web)     • web-server                • web-javascript • Flutter
      Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.91, on macOS 11.0.1 20B29 darwin-x64,
    locale en-GB)
    • Flutter version 1.25.0-5.0.pre.91 at /Users/tahatesser/Code/flutter_master
    • Framework revision 7dade22f25 (20 hours ago), 2020-12-06 21:34:04 +0530
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by nohli** [comment] 2020-12-07 12:37
> Hi @nohli 
> 
> Thanks for filing the issue, I can reproduce the issue
> 
> 
> 
> <details> 
> 
> <summary>code sample</summary> 
> 
> 
> 
> ```dart
> 
> mport 'package:flutter/material.dart';
> 
> import 'package:url_launcher/url_launcher.dart';
> 
> 
> 
> void main() => runApp(MyApp());
> 
> 
> 
> class MyApp extends StatelessWidget {
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return MaterialApp(
> 
>       title: 'Material App',
> 
>       theme: ThemeData.dark(),
> 
>       home: Home(),
> 
>     );
> 
>   }
> 
> }
> 
> 
> 
> class Home extends StatelessWidget {
> 
>   final Uri _emailLaunchUri = Uri(
> 
>       scheme: 'mailto',
> 
>       path: 'smith@example.com',
> 
>       queryParameters: {'subject': 'Example Subject & Symbols are allowed!'});
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
> 
>       appBar: AppBar(
> 
>         title: Text('Material App Bar'),
> 
>       ),
> 
>       body: Center(
> 
>         child: Container(
> 
>           child: Text('Hello World'),
> 
>         ),
> 
>       ),
> 
>       floatingActionButton: FloatingActionButton(
> 
>         child: Icon(Icons.add),
> 
>         onPressed: () async {
> 
>           const url = 'https://flutter.dev';
> 
>           if (await canLaunch(_emailLaunchUri.toString())) {
> 
>             await launch(_emailLaunchUri.toString(), forceSafariVC: true);
> 
>           } else {
> 
>             throw 'Could not launch ${_emailLaunchUri.toString()}';
> 
>           }
> 
>         },
> 
>       ),
> 
>     );
> 
>   }
> 
> }
> 
> 
> 
> ``` 
> 
> 
> 
> </details>
> 
> 
> 
> <details> 
> 
> <summary>logs</summary> 
> 
> 
> 
> ```bash
> 
> Running "flutter pub get" in url_launcher_example...
> 
> Launching lib/main.dart on Taha’s iPad in debug mode...
> 
>  package:triage/main.dart
> 
> Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
> 
> Warning: Podfile is out of date
> 
>   This can cause issues if your application depends on plugins that do not support iOS.
> 
>   See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
> 
>   If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
> 
> To regenerate the Podfile, run:
> 
>   rm ios/Podfile
> 
> Xcode build done.                                           30.7s
> 
> Connecting to VM Service at ws://127.0.0.1:64538/nrWE8tAwnsk=/ws
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
> 
> [38;5;244m#0      launch[39;49m
> 
>  package:url_launcher/url_launcher.dart
> 
> [38;5;248m#1      Home.build.<anonymous closure>[39;49m
> 
>  package:triage/main.dart
> 
> [38;5;244m<asynchronous suspension>[39;49m
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
> 
> [38;5;244m#0      launch[39;49m
> 
>  package:url_launcher/url_launcher.dart
> 
> [38;5;248m#1      Home.build.<anonymous closure>[39;49m
> 
>  package:triage/main.dart
> 
> [38;5;244m<asynchronous suspension>[39;49m
> 
> Reloaded 1 of 541 libraries in 320ms.
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
> 
> [38;5;244m#0      launch[39;49m
> 
>  package:url_launcher/url_launcher.dart
> 
> [38;5;248m#1      Home.build.<anonymous closure>[39;49m
> 
>  package:triage/main.dart
> 
> [38;5;244m<asynchronous suspension>[39;49m
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
> 
> [38;5;244m#0      launch[39;49m
> 
>  package:url_launcher/url_launcher.dart
> 
> [38;5;248m#1      Home.build.<anonymous closure>[39;49m
> 
>  package:triage/main.dart
> 
> [38;5;244m<asynchronous suspension>[39;49m
> 
> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
> 
> [38;5;244m#0      launch[39;49m
> 
>  package:url_launcher/url_launcher.dart
> 
> [38;5;248m#1      Home.build.<anonymous closure>[39;49m
> 
>  package:triage/main.dart
> 
> [38;5;244m<asynchronous suspension>[39;49m
> 
> 
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> 
> 
> <details> 
> 
> <summary>flutter doctor -v</summary> 
> 
> 
> 
> ```bash
> 
> [✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64,
> 
>     locale en-GB)
> 
>     • Flutter version 1.24.0-10.2.pre at /Users/tahatesser/Code/flutter_beta
> 
>     • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
> 
>     • Engine revision 07c1eed46b
> 
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> 
>     • Android SDK at /Users/tahatesser/Code/sdk
> 
>     • Platform android-30, build-tools 30.0.2
> 
>     • ANDROID_HOME = /Users/tahatesser/Code/sdk
> 
>     • Java binary at: /Applications/Android
> 
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_242-release-1644-b3-6915495)
> 
>     • All Android licenses accepted.
> 
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
> 
>     • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
> 
>     • Xcode 12.2, Build version 12B45b
> 
>     • CocoaPods version 1.10.0
> 
> 
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> 
> 
> [✓] Android Studio (version 4.1)
> 
>     • Android Studio at /Applications/Android Studio.app/Contents
> 
>     • Flutter plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> 
>     • Dart plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_242-release-1644-b3-6915495)
> 
> 
> 
> [✓] VS Code (version 1.51.1)
> 
>     • VS Code at /Applications/Visual Studio Code.app/Contents
> 
>     • Flutter extension version 3.17.0
> 
> 
> 
> [✓] Connected device (3 available)
> 
>     • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
> 
>     • Web Server (web)     • web-server                • web-javascript • Flutter
> 
>       Tools
> 
>     • Chrome (web)         • chrome                    • web-javascript • Google
> 
>       Chrome 87.0.4280.88
> 
> 
> 
> • No issues found!
> 
> ```
> 
> 
> 
> ```bash
> 
> [✓] Flutter (Channel master, 1.25.0-5.0.pre.91, on macOS 11.0.1 20B29 darwin-x64,
> 
>     locale en-GB)
> 
>     • Flutter version 1.25.0-5.0.pre.91 at /Users/tahatesser/Code/flutter_master
> 
>     • Framework revision 7dade22f25 (20 hours ago), 2020-12-06 21:34:04 +0530
> 
>     • Engine revision 6491c7518f
> 
>     • Dart version 2.12.0 (build 2.12.0-120.0.dev)
> 
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> 
>     • Android SDK at /Users/tahatesser/Code/sdk
> 
>     • Platform android-30, build-tools 30.0.2
> 
>     • ANDROID_HOME = /Users/tahatesser/Code/sdk
> 
>     • Java binary at: /Applications/Android
> 
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_242-release-1644-b3-6915495)
> 
>     • All Android licenses accepted.
> 
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
> 
>     • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
> 
>     • Xcode 12.2, Build version 12B45b
> 
>     • CocoaPods version 1.10.0
> 
> 
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> 
> 
> [✓] Android Studio (version 4.1)
> 
>     • Android Studio at /Applications/Android Studio.app/Contents
> 
>     • Flutter plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> 
>     • Dart plugin can be installed from:
> 
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_242-release-1644-b3-6915495)
> 
> 
> 
> [✓] VS Code (version 1.51.1)
> 
>     • VS Code at /Applications/Visual Studio Code.app/Contents
> 
>     • Flutter extension version 3.17.0
> 
> 
> 
> [✓] Connected device (3 available)
> 
>     • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
> 
>     • macOS (desktop)      • macos                     • darwin-x64     • macOS
> 
>       11.0.1 20B29 darwin-x64
> 
>     • Chrome (web)         • chrome                    • web-javascript • Google
> 
>       Chrome 87.0.4280.88
> 
> 
> 
> • No issues found!
> 
> ```
> 
> 
> 
> </details>
> 
> 

In your code it says forceSafariVC: true, which would partly be the user's fault then. The issue is if you don't set forceSafariVC at all, it crashes by default.

**Comment by TahaTesser** [comment] 2020-12-08 08:35
@nohli 
Yes, I was just testing it and forgot to remove

**Comment by pcsosinski** [comment] 2021-01-14 17:14
@nohli, assigning this to you as it looks like you're working on it in the attached plugin PR.  thanks!  let me know if there's other work I'm missing.

**Comment by stuartmorgan** [comment] 2021-02-01 19:26
Is there still an issue here after https://github.com/flutter/plugins/pull/3354 landed?

**Closed** 2021-02-04 13:20 UTC
Labels: P3, a: null-safety, found in release: 1.25, has reproducible steps, p: first party, p: url_launcher, platform-ios, plugin, severe: crash
