### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by SteplerPaulo** [flutter/flutter#112283] opened 2022-09-23 16:39 UTC
## Command
```
flutter test --coverage
```

## Steps to Reproduce
1. run flutter test --coverage

## Logs
FileSystemException: Directory listing failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:474:23)
<asynchronous suspension>
#9      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:318:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-PH)
    • Flutter version 3.3.2 on channel stable at D:\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Paulo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.2006]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 105.0.1343.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+35
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
amplify_auth_cognito-0.5.1
amplify_auth_cognito_android-0.5.1
amplify_auth_cognito_ios-0.5.1
amplify_core-0.5.1
amplify_flutter-0.5.1
amplify_flutter_android-0.5.1
amplify_flutter_ios-0.5.1
connectivity_plus-2.3.7
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.3
connectivity_plus_windows-1.2.2
flutter_barcode_scanner-2.0.0
flutter_inappwebview-5.4.3+7
flutter_jailbreak_detection-1.8.0
flutter_native_splash-2.2.9
flutter_plugin_android_lifecycle-2.0.7
flutter_secure_storage-5.1.2
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
fluttertoast-8.0.9
http_certificate_pinning-2.0.4
image_gallery_saver-1.7.1
launch_review-3.0.1
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-2.1.0
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-9.2.0
permission_handler_android-9.0.2+1
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
share_plus-4.4.0
share_plus_linux-3.0.0
share_plus_macos-3.0.1
share_plus_web-3.0.1
share_plus_windows-3.0.1
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.1.0
url_launcher-6.1.5
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
webview_flutter-3.0.4
webview_flutter_android-2.10.2
webview_flutter_wkwebview-2.9.4

**Comment by darshankawar** [comment] 2022-09-26 06:11
Closing this as duplicate of https://github.com/flutter/flutter/issues/106953

**Closed by darshankawar** 2022-09-26 06:11 UTC
Labels: in triage
