### ISSUE TITLE
After migrating to AndroidX the firebase and cloud_firestore  plugin issue 

### ISSUE THREAD

**Issue by jatinkumar11954** [flutter/flutter#47773] opened 2019-12-25 08:10 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

 info - Unused import: 'dart:io' - lib\Arrangements\Drawer.dart:1:8 - unused_import                                      info - Unused import: 'package:carigari/screens/homescreen.dart' - lib\Arrangements\Drawer.dart:4:8 - unused_import     info - Unused import: 'package:carigari/screens/privacy.dart' - lib\Arrangements\Drawer.dart:5:8 - unused_import        info - Unused import: 'package:carigari/screens/status.dart' - lib\Arrangements\Drawer.dart:6:8 - unused_import         info - Duplicate import - lib\Arrangements\Drawer.dart:7:8 - duplicate_import                                           info - Unused import: 'package:carigari/screens/status.dart' - lib\Arrangements\Drawer.dart:7:8 - unused_import         info - Unused import: 'package:flutter/material.dart' - lib\Arrangements\Drawer.dart:10:8 - unused_import               info - Unused import: 'package:carigari/Screens/splashScreen.dart' - lib\Arrangements\Drawer.dart:12:8 -                       unused_import                                                                                                    info - The declaration 'show' isn't referenced - lib\Arrangements\Drawer.dart:42:8 - unused_element                     info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:5:29 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:6:29 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:10:5 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:11:5 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:12:5 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:13:5 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:43:23 -                            non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\Arrangements\variables.dart:44:23 -                            non_constant_identifier_names                                                                                    info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\screens\Data\Account.dart:1:8 -                     unused_import                                                                                                    info - Unused import: 'package:carigari/Arrangements/sizeModification.dart' - lib\screens\Data\Account.dart:3:8 -              unused_import                                                                                                    info - Unused import: 'package:firebase_auth/firebase_auth.dart' - lib\screens\Data\Account.dart:4:8 - unused_import    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\CheckingData.dart:29:22 - missing_return                                                        info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\CheckingData.dart:72:21 -                         non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\CheckingData.dart:81:17 -                         non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\CheckingData.dart:83:18 -                         non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\CheckingData.dart:85:17 -                         non_constant_identifier_names                                                                                    info - Unused import: 'package:carigari/Arrangements/Drawer.dart' - lib\screens\Data\Register.dart:4:8 -                       unused_import                                                                                                    info - Unused import: 'package:carigari/screens/bottomNavigation.dart' - lib\screens\Data\Register.dart:6:8 -                  unused_import                                                                                                    info - Unused import: 'package:carigari/screens/homepage.dart' - lib\screens\Data\Register.dart:7:8 - unused_import     info - Duplicate import - lib\screens\Data\Register.dart:12:8 - duplicate_import                                        info - Don't import implementation files from another package - lib\screens\Data\Register.dart:13:8 -                          implementation_imports                                                                                           info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\Register.dart:46:12 -                             non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\Register.dart:60:11 -                             non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\Register.dart:166:29 - missing_return                                                           info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\about.dart:26:22 - missing_return                                                               info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\contactForm.dart:48:13 -                          non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\contactForm.dart:77:29 - missing_return                                                         info - Unused import: 'package:carigari/Arrangements/Drawer.dart' - lib\screens\Data\login.dart:2:8 - unused_import     info - Unused import: 'package:carigari/screens/bottomNavigation.dart' - lib\screens\Data\login.dart:4:8 -                     unused_import                                                                                                    info - Unused import: 'package:carigari/screens/homepage.dart' - lib\screens\Data\login.dart:5:8 - unused_import        info - Unused import: 'package:carigari/screens/status.dart' - lib\screens\Data\login.dart:6:8 - unused_import          info - Duplicate import - lib\screens\Data\login.dart:10:8 - duplicate_import                                           info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\login.dart:39:13 -                                non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\login.dart:51:13 -                                non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\login.dart:64:17 -                                non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\login.dart:105:25 - missing_return                                                              info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\notification.dart:27:22 - missing_return                                                        info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\phone.dart:20:13 -                                non_constant_identifier_names                                                                                    info - This function has a return type of 'String', but doesn't end with a return statement -                                  lib\screens\Data\phone.dart:135:10 - missing_return                                                              info - Name non-constant identifiers using lowerCamelCase - lib\screens\Data\phone.dart:148:9 -                                non_constant_identifier_names                                                                                    info - This function has a return type of 'String', but doesn't end with a return statement -                                  lib\screens\Data\phone.dart:148:9 - missing_return                                                               info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\phone.dart:181:20 - missing_return                                                              info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\Data\subscription.dart:23:22 - missing_return                                                        info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\cart.dart:79:22 - missing_return                                                                     info - Avoid using braces in interpolation when not needed - lib\screens\cart.dart:104:69 -                                    unnecessary_brace_in_string_interps                                                                              info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\contactUs.dart:26:17 - missing_return                                                                info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\help.dart:27:22 - missing_return                                                                     info - Unused import: 'package:connectivity/connectivity.dart' - lib\screens\homepage.dart:1:8 - unused_import          info - Unused import: './isConnection.dart' - lib\screens\homepage.dart:6:8 - unused_import                             info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its                instance fields are not final: HomePage.title, HomePage.uid - lib\screens\homepage.dart:8:7 -                           must_be_immutable                                                                                                info - Unused import: 'package:carigari/screens/Data/Category.dart' - lib\screens\homescreen.dart:3:8 - unused_import   info - Unused import: 'package:carigari/screens/Data/contactForm.dart' - lib\screens\homescreen.dart:4:8 -                     unused_import                                                                                                    info - Unused import: 'package:carigari/screens/contactUs.dart' - lib\screens\homescreen.dart:6:8 - unused_import       info - Unused import: 'package:carigari/screens/privacy.dart' - lib\screens\homescreen.dart:7:8 - unused_import         info - Unused import: 'package:carigari/screens/splashScreen.dart' - lib\screens\homescreen.dart:8:8 - unused_import    info - Unused import: 'package:carigari/screens/subcategory.dart' - lib\screens\homescreen.dart:9:8 - unused_import     info - Unused import: 'package:url_launcher/url_launcher.dart' - lib\screens\homescreen.dart:14:8 - unused_import       info - Duplicate import - lib\screens\homescreen.dart:15:8 - duplicate_import                                           info - Unused import: './showImage.dart' - lib\screens\homescreen.dart:16:8 - unused_import                             info - Name non-constant identifiers using lowerCamelCase - lib\screens\homescreen.dart:36:11 -                                non_constant_identifier_names                                                                                    info - Avoid using unnecessary statements - lib\screens\homescreen.dart:66:66 - unnecessary_statements                  info - Name non-constant identifiers using lowerCamelCase - lib\screens\homescreen.dart:99:10 -                                non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\homescreen.dart:185:17 - missing_return                                                              info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its                instance fields are not final: ShowImageWhenNoInternet.img - lib\screens\imageNoNet.dart:2:7 -                          must_be_immutable                                                                                                info - Unused import: 'package:carigari/screens/Data/details.dart' - lib\screens\isConnection.dart:5:8 -                       unused_import                                                                                                    info - Unused import: 'package:carigari/Arrangements/sizeModification.dart' - lib\screens\isConnection.dart:10:8 -             unused_import                                                                                                    info - Unused import: 'package:carigari/screens/bottomNavigation.dart' - lib\screens\isConnection.dart:17:8 -                  unused_import                                                                                                    info - Unused import: 'package:carigari/screens/Data/notification.dart' - lib\screens\isConnection.dart:21:8 -                 unused_import                                                                                                    info - Unused import: 'package:carigari/screens/showImage.dart' - lib\screens\isConnection.dart:23:8 - unused_import    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\isConnection.dart:65:20 - missing_return                                                             info - This function has a return type of 'Widget', but doesn't end with a return statement -                                  lib\screens\logout.dart:16:10 - missing_return                                                                   info - Unused import: 'package:expandable/expandable.dart' - lib\screens\orderConfirm.dart:5:8 - unused_import          info - Name non-constant identifiers using lowerCamelCase - lib\screens\orderConfirm.dart:18:30 -                              non_constant_identifier_names                                                                                    info - The value of the field '_dropforms' isn't used - lib\screens\orderConfirm.dart:38:7 - unused_field               info - The value of the field '_dropformSelected' isn't used - lib\screens\orderConfirm.dart:39:7 - unused_field        info - Name non-constant identifiers using lowerCamelCase - lib\screens\orderConfirm.dart:43:11 -                              non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\orderConfirm.dart:54:10 -                              non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\orderConfirm.dart:108:22 - missing_return                                                            info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\privacy.dart:27:22 - missing_return                                                                  info - Duplicate import - lib\screens\selectScreen.dart:4:8 - duplicate_import                                          info - Unused import: '../Arrangements/sizeModification.dart' - lib\screens\selectScreen.dart:7:8 - unused_import       info - Unused import: 'package:carigari/screens/homescreen.dart' - lib\screens\selectScreen.dart:8:8 - unused_import    info - Name non-constant identifiers using lowerCamelCase - lib\screens\selectScreen.dart:24:12 -                              non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\selectScreen.dart:38:11 -                              non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\selectScreen.dart:136:17 - missing_return                                                            info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its                instance fields are not final: ShowImage.img - lib\screens\showImage.dart:3:7 - must_be_immutable                info - Unused import: 'dart:io' - lib\screens\splashScreen.dart:1:8 - unused_import                                     info - Unused import: 'package:firebase_auth/firebase_auth.dart' - lib\screens\splashScreen.dart:6:8 - unused_import    info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\screens\splashScreen.dart:7:8 -                     unused_import                                                                                                    info - Unused import: './selectScreen.dart' - lib\screens\splashScreen.dart:9:8 - unused_import                         info - Unused import: 'dart:async' - lib\screens\splashScreen.dart:10:8 - unused_import                                 info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\screens\subcategory.dart:4:8 -                      unused_import                                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\subcategory.dart:29:11 -                               non_constant_identifier_names                                                                                    info - Name non-constant identifiers using lowerCamelCase - lib\screens\subcategory.dart:50:5 -                                non_constant_identifier_names                                                                                    info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -                            lib\screens\subcategory.dart:105:20 - missing_return        

[√] Flutter (Channel unknown, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\maginificient\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\maginificient\AppData\Local\Android
    • Java binary at: D:\pro\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\pro\as
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

**Comment by jatinkumar11954** [comment] 2019-12-25 08:13
unching lib\main.dart on Nokia 6 1 Plus in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:8: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:538: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:558: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:576: error: cannot find symbol
    public void onComplete(@NonNull Task<ProviderQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.ProvidersCompleteListener
:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:175: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:270: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
symbol: class NonNull
D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:435: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:487: error: cannot find symbol
public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by jatinkumar11954** [comment] 2019-12-25 08:17
the fire base plugin error and cloudstore error are been shown
while building apk and while launching
 i have aleady added in gradle.properties
 android.useAndroidX=true
android.enableJetifier=true
 and in  build.gradle 

 dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }
 in android>app 
build.gradle
  
compileSdkVersion 28
 defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "conversionguru.in.carigari"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

**Comment by jatinkumar11954** [comment] 2019-12-25 08:22
the fire base plugin error and cloudstore error are been shown
while building apk and while launching
i have aleady added in gradle.properties
android.useAndroidX=true
android.enableJetifier=true
and in build.gradle

dependencies {
classpath 'com.android.tools.build:gradle:3.5.1'
classpath 'com.google.gms:google-services:3.2.1'
}
in android>app
build.gradle

compileSdkVersion 28
defaultConfig {
// TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
applicationId "com.android.me"
minSdkVersion 21
targetSdkVersion 28
versionCode flutterVersionCode.toInteger()
versionName flutterVersionName
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
multiDexEnabled true
}

**Comment by iapicca** [comment] 2019-12-25 12:25
Hi @jatinkumar11954 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-25 12:25 UTC
