### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by mbelshe** [flutter/flutter#153531] opened 2024-08-16 00:02 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1772:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1784:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1733:14)
#4      VmService.callMethod (package:vm_service/src/vm_service.dart:1716:12)
#5      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
#6      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:601:49)
#7      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:724:37)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1841:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.22.3 on channel stable at /Users/mike/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0850beeb2 (4 weeks ago), 2024-07-16 21:43:41 -0700
    [32m•[39m Engine revision 235db911ba
    [32m•[39m Dart version 3.4.4
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/mike/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/mike/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.92.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at /Users/mike/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Pixel 3 (mobile)                • 8CCX1M87Q             • android-arm64  • Android 12 (API 31)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120
    [33m![39m Error: Browsing on the local area network for charlize’s iphone . Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    [33m![39m Error: Browsing on the local area network for Jia’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
app_settings-5.1.1
cloud_firestore-4.17.3
cloud_firestore_web-3.12.3
cloud_functions-4.7.4
cloud_functions

**Comment by huycozy** [comment] 2024-08-16 05:38
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by huycozy** 2024-08-16 05:38 UTC
Labels: in triage
