### ISSUE TITLE
TextFields do not respond to keyboard inputs on Safari

### ISSUE THREAD

**Issue by Nazacheres** [flutter/flutter#96365] opened 2022-01-09 13:14 UTC
1. On master channel
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.9.0-1.0.pre.201, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

2. Add TextField like
```
TextField(
  controller: _emailController,
  keyboardType: TextInputType.emailAddress,
  decoration: InputDecoration(hintText: S.of(context).commonEmail),
),
```

3. Running in debug and release mode, on all browsers text field responds to keyboard, but in safari (Version 14.1.2 (16611.3.10.1.6)) there is no reaction to any button on a hardware keyboard, also can't paste.

P.S. It works fine on latest stable
```
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (4 months ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0
```

**Comment by danagbemava-nc** [comment] 2022-01-10 11:13
Hi @Nazacheres, are you experiencing this issue with a hardware keyboard or the software keyboard? 

Also, there's a new version of `master` out can you upgrade to the latest and confirm if you still experience this issue? 

Thank you

**Comment by Nazacheres** [comment] 2022-01-10 11:21
The issue is reproducible with a hardware keyboard on BigSure, Safari - Version 14.1.2 (16611.3.10.1.6).
Not sure about the software keyboard. I will also try latest master later today.

**Comment by danagbemava-nc** [comment] 2022-01-10 12:53
Sorry, I assumed you were testing with `Safari` on `iOS`. 

I tested with the latest version of master and I was able to enter input into the keyboard just fine. See video below. 
Kindly confirm whether or not it works for you on latest master.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/148768670-ece5d042-f577-41ca-8315-1e4b6cf4fc6b.mov

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.296, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.296 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8dbea5e6b1 (7 hours ago), 2022-01-10 08:45:16 +0300
    • Engine revision 94786ae707
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by artificerchris** [comment] 2022-01-24 17:06
I'm seeing this issue too, I came up with this minimum reproducible example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const BugApp());
}

class BugApp extends StatelessWidget {
  const BugApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const BugPage(),
    );
  }
}

class BugPage extends StatelessWidget {
  const BugPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Bug Demo'),
      ),
      body: Stack(
        children: const [
          Center(
            child: SizedBox(
              width: 100,
              height: 64,
              child: TextField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Enter a search term',
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

I've tested this on stable, beta, and master. It only happens on beta, not on stable or master in my setup.

**Comment by danagbemava-nc** [comment] 2022-01-25 07:36
Hi @artificerchris, it looks like a similar regression was reported in https://github.com/flutter/flutter/issues/96365. It has since been fixed which is why you cannot reproduce on `master`. It is likely the fix hasn't made it to `beta` yet, which is why you can reproduce on `beta`. 

Since it is working on `master` however, I feel it is safe to close this issue as it has already been fixed and should rollout to the other branches soon enough. 

Thank you.

**Closed by danagbemava-nc** 2022-01-25 07:36 UTC
Labels: waiting for customer response, in triage
