### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by SamuvelSmik** [flutter/flutter#109673] opened 2022-08-17 07:54 UTC
## Command
```
flutter --no-color attach --machine --device-id=eb3a47d7 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:325:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 3.1.0-9.0.pre, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.1.0-9.0.pre at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f28e570c8c (9 weeks ago), 2022-06-14 13:39:33 -0500
    • Engine revision 74ee6b5afd
    • Dart version 2.18.0 (build 2.18.0-165.1.beta)
    • DevTools version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Amrit\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\Amrit\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.49)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.2019
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\Amrit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • vivo 1920 (mobile) • eb3a47d7 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.6+60
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
### Plugins
connectivity_plus-2.3.0
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.2
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
facebook_app_events-0.15.0
file_picker-4.6.1
firebase_analytics-9.1.9
firebase_analytics_web-0.4.0+14
firebase_auth-3.3.19
firebase_auth_web-3.3.16
firebase_core-1.17.1
firebase_core_web-1.6.4
firebase_crashlytics-2.8.1
firebase_messaging-11.4.1
firebase_messaging_web-2.4.1
flutter_compass-0.7.0
flutter_plugin_android_lifecycle-2.0.6
geolocator-8.2.1
geolocator_android-3.1.8
geolocator_apple-2.1.3
geolocator_web-2.1.5
geolocator_windows-0.1.1
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
sms_autofill-2.2.0
url_launcher-6.1.2
url_launcher_android-6.0.17
url_launcher_ios-6.0.16
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1

**Comment by danagbemava-nc** [comment] 2022-08-18 08:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581. 

Kindly upvote the linked issue and follow up there for updates.

**Closed by danagbemava-nc** 2022-08-18 08:14 UTC
Labels: in triage
