### ISSUE TITLE
Flutter app crashes on Android 5.0

### ISSUE THREAD

**Issue by Alsharie** [flutter/flutter#84902] opened 2021-06-19 09:17 UTC
Hello , 
I create a fresh flutter app and tried to run it on Android 5.0
everything seemed to be good but after the app installed it crashed   immediately

## Steps to Reproduce

**Expected results:** 
I should see the counter app on the screen and work

**Actual results:** 
the app crash immediately

<details>
  <summary>Logs</summary>

```
 Skipping pub get: version match.
[  +91 ms] Generating F:\test5\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +60 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +20 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +3 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +4 ms] D:\android_dev\_Flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\android_dev\_Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root D:\android_dev\_Flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\PC\AppData\Local\Temp\flutter_tools.299e1ff8\flutter_tool.d16c0287\app.dill --packages F:\test5\bug\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +16 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +17 ms] <- compile package:bug/main.dart
[  +50 ms] --------- beginning of system
           06-19 12:01:20.484 I/UsageStatsService( 1541): User[0] Flushing usage stats to disk
[  +20 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe version
[  +44 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as D:\android_dev\Android_SDK\platform-tools\adb.exe
[   +2 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe start-server
[  +33 ms] Building APK
[  +22 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from F:\test5\bug\android\gradlew.bat.
[  +17 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +140 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +2 ms] executing: [F:\test5\bug\android/] F:\test5\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=F:\test5\bug\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+4435 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +165 ms] executing: [D:\android_dev\_Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [ +160 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] d79295af24c3ed621c33713ecda14ad196fd9c31
[  +26 ms] [   +1 ms] executing: [D:\android_dev\_Flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +50 ms] [ +138 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[   +2 ms] [        ] 2.2.2
[   +1 ms] [  +11 ms] executing: [D:\android_dev\_Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] [  +96 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [D:\android_dev\_Flutter/] git ls-remote --get-url origin
[  +92 ms] [  +85 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[  +92 ms] [ +113 ms] executing: [D:\android_dev\_Flutter/] git rev-parse --abbrev-ref HEAD
[ +109 ms] [  +81 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +92 ms] [ +130 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +90 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +103 ms] [ +174 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +73 ms] [  +67 ms] Initializing file store
[ +109 ms] [  +46 ms] Skipping target: gen_localizations
[   +1 ms] [  +11 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +25 ms] D:\android_dev\_Flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\android_dev\_Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\android_dev\_Flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--no-link-platform --packages F:\test5\bug\.dart_tool\package_config.json --output-dill F:\test5\bug\.dart_tool\flutter_build\7e90a91dc203a20bfd3ab2372580a134\app.dill --depfile
F:\test5\bug\.dart_tool\flutter_build\7e90a91dc203a20bfd3ab2372580a134\kernel_snapshot.d package:bug/main.dart

[+12792 ms] [+12800 ms] kernel_snapshot: Complete
[ +694 ms] [ +735 ms] debug_android_application: Starting due to {}
[ +499 ms] [ +472 ms] debug_android_application: Complete
[ +797 ms] [ +763 ms] Persisting file store
[        ] [  +10 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [  +16 ms] "flutter assemble" took 15,179ms.
[ +307 ms] [ +269 ms] ensureAnalyticsSent: 264ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +189 ms] > Task :app:packLibsflutterBuildDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[ +108 ms] > Task :app:generateDebugBuildConfig
[   +1 ms] > Task :app:checkDebugAarMetadata
[        ] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugShaders
[        ] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +391 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[+1235 ms] > Task :app:createDebugCompatibleScreenManifests
[   +5 ms] > Task :app:extractDeepLinksDebug
[ +159 ms] > Task :app:processDebugMainManifest
[ +185 ms] > Task :app:processDebugManifest
[ +119 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +2 ms] > Task :app:javaPreCompileDebug
[   +2 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +689 ms] > Task :app:mergeDebugResources
[   +1 ms] > Task :app:checkDebugDuplicateClasses
[ +302 ms] > Task :app:mergeDebugJniLibFolders
[ +196 ms] > Task :app:validateSigningDebug
[   +7 ms] > Task :app:processDebugManifestForPackage
[ +191 ms] > Task :app:desugarDebugFileDependencies
[ +499 ms] > Task :app:compressDebugAssets
[ +198 ms] > Task :app:processDebugResources
[+1989 ms] > Task :app:mergeDebugNativeLibs
[+11947 ms] > Task :app:compileDebugKotlin
[+2355 ms] > Task :app:compileDebugJavaWithJavac
[   +3 ms] > Task :app:compileDebugSources
[+1211 ms] > Task :app:mergeDebugJavaResource
[   +2 ms] > Task :app:dexBuilderDebug
[ +794 ms] > Task :app:stripDebugDebugSymbols
[   +2 ms] Unable to strip the following libraries, packaging them as they are: libflutter.so.
[+1895 ms] > Task :app:mergeExtDexDebug
[+1886 ms] > Task :app:mergeDexDebug
[+2800 ms] > Task :app:packageDebug
[ +107 ms] > Task :app:assembleDebug
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 49s
[        ] 32 actionable tasks: 31 executed, 1 up-to-date
[ +549 ms] Running Gradle task 'assembleDebug'... (completed in 50.7s)
[  +30 ms] calculateSha: LocalDirectory: 'F:\test5\bug\build\app\outputs\flutter-apk'/app.apk
[ +540 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +5 ms] executing: D:\android_dev\Android_SDK\build-tools\30.0.3\aapt dump xmltree F:\test5\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +88 ms] Exit code 0 from: D:\android_dev\Android_SDK\build-tools\30.0.3\aapt dump xmltree F:\test5\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell am force-stop com.example.bug
[ +397 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell pm list packages com.example.bug
[ +515 ms] Installing APK.
[   +3 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 install -t -r F:\test5\bug\build\app\outputs\flutter-apk\app.apk
[+5882 ms] Performing Push Install
                    F:\test5\bug\build\app\outputs\flutter-apk\app.apk: 1 file pushed, 0 skipped. 70.0 MB/s (40748213 bytes in 0.555s)
                        pkg: /data/local/tmp/app.apk
                    Success
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 5.9s)
[   +2 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell echo -n eba8dd6aecfe082086c50a90b1b8beb20a2ca6ac >
/data/local/tmp/sky.com.example.bug.sha1
[  +76 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +77 ms] --------- beginning of main
           06-19 12:04:49.136 I/Icing   ( 2335): Indexing done com.google.android.gms-internal.3p:MobileApplication
[  +26 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation
true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[ +421 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +669 ms] Observatory URL on device: http://127.0.0.1:51769/8YquCFyb6lE=/
[   +2 ms] executing: D:\android_dev\Android_SDK\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:51769
[  +70 ms] 8138
[   +1 ms] Forwarded host port 8138 to device port 51769 for Observatory
[   +9 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:8138/8YquCFyb6lE=/
[ +439 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:8138/8YquCFyb6lE=/.
[ +125 ms] DDS is listening at http://127.0.0.1:8142/o9uKUMigC5o=/.
[  +95 ms] Successfully connected to service protocol: http://127.0.0.1:8138/8YquCFyb6lE=/

```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-US)
    • Flutter version 2.2.2 at D:\android_dev\_Flutter
    • Framework revision d79295af24 (8 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\android_dev\Android_SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • 47410e77994b99a (mobile)           • 47410e77994b99a • android-arm    • Android 4.1.2 (API 16)
    • Android SDK built for x86 (mobile) • emulator-5554   • android-x86    • Android 5.0.2 (API 21) (emulator)
    • Chrome (web)                       • chrome          • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)                         • edge            • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.

```

</details>

**Comment by behzodfaiziev** [comment] 2021-06-19 12:06
It seems you haven't  accepted  _Android licenses_
It seems to be duplicate of #73118

**Comment by behzodfaiziev** [comment] 2021-06-19 12:07
Hi, try to accept  _Android licenses_, if it didn't help this issue might be be duplicate of #73118

**Comment by behzodfaiziev** [comment] 2021-06-19 12:08
Hi, try to accept  _Android licenses_. If it didn't help,  this issue might be be duplicate of #73118

**Comment by Alsharie** [comment] 2021-06-19 20:39
@behzodfaiziev I accepted the licenses but nothing changed

**Comment by behzodfaiziev** [comment] 2021-06-19 21:01
@Alsharie that comment should probable solve an issue when using API 21: [In android\app\src\main\res\drawable-v21\launch_background.xml change](https://github.com/flutter/flutter/issues/73118#issuecomment-822395456).

**Closed** 2021-06-20 10:23 UTC
