### ISSUE TITLE
dart obfuscation has stopped working

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#22322] opened 2018-09-26 21:11 UTC
The previous version of my app I released 2 months ago I had the option for dart obfuscation enabled :
In gradle.properties I have :

    extra-gen-snapshot-options=--obfuscate

Trying to make a release build today I am just getting crashes on startup (debug mode is working fine). Removing the obfuscate line above makes the release work again. This is the log from running my app in release mode and it crashing :

	09-26 13:59:52.527   601  2389 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rockvole.kbmlviewer/.MainActivity (has extras)} from uid 10031 on display 0
	09-26 13:59:52.539   601   614 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.googlequicksearchbox (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.reflection.ReflectionReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10031)
	09-26 13:59:52.545   601   614 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 pkg=com.google.android.gms (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.google.android.googlequicksearchbox (uid 10031)
	09-26 13:59:52.562   601   828 I ActivityManager: Start proc 16578:com.rockvole.kbmlviewer/u0a150 for activity com.rockvole.kbmlviewer/.MainActivity
	09-26 13:59:52.654 15871 16185 I PBSessionCacheImpl: Deleted sessionId[69802934172932476] from persistence.
	09-26 13:59:52.686 15871 15871 W SearchServiceCore: Abort, client detached.
	09-26 13:59:52.695 15871 15871 I MicroDetector: Keeping mic open: false
	09-26 13:59:52.696 15871 15887 I DeviceStateChecker: DeviceStateChecker cancelled
	09-26 13:59:52.696 15871 16185 I AudioController: internalShutdown
	09-26 13:59:52.698 15871 16416 I MicroRecognitionRunner: Stopping hotword detection.
	09-26 13:59:52.715   236   290 I SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0
	09-26 13:59:52.719 15871 16185 I MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
	09-26 13:59:52.731 15871 15911 I MicroRecognitionRunner: Detection finished
	09-26 13:59:53.488 16578 16593 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0xe55c0020 in tid 16593 (1.ui)
	09-26 13:59:53.492   185   185 W         : debuggerd: handling request: pid=16578 uid=10150 gid=10150 tid=16593
	09-26 13:59:53.503 16598 16598 W debuggerd: type=1400 audit(0.0:1398): avc: denied { search } for name="com.rockvole.kbmlviewer" dev="dm-2" ino=26474 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
	09-26 13:59:53.516 16598 16598 W debuggerd: type=1400 audit(0.0:1399): avc: denied { search } for name="com.rockvole.kbmlviewer" dev="dm-2" ino=26474 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
	09-26 13:59:53.606 16598 16598 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
	09-26 13:59:53.606 16598 16598 F DEBUG   : Build fingerprint: 'google/volantis/flounder:7.1.1/N9F27M/4333998:user/release-keys'
	09-26 13:59:53.606 16598 16598 F DEBUG   : Revision: '0'
	09-26 13:59:53.606 16598 16598 F DEBUG   : ABI: 'arm'
	09-26 13:59:53.606 16598 16598 F DEBUG   : pid: 16578, tid: 16593, name: 1.ui  >>> com.rockvole.kbmlviewer <<<
	09-26 13:59:53.606 16598 16598 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xe55c0020
	09-26 13:59:53.606 16598 16598 F DEBUG   :     r0 e55c0021  r1 00000006  r2 d1941170  r3 e55c15d9
	09-26 13:59:53.606 16598 16598 F DEBUG   :     r4 e55c1a71  r5 00000000  r6 e55c0021  r7 d3362824
	09-26 13:59:53.606 16598 16598 F DEBUG   :     r8 00000000  r9 00000006  sl eb606200  fp eb4f9f58
	09-26 13:59:53.606 16598 16598 F DEBUG   :     ip e55c36c9  sp eb4f9ed4  lr eb3f547c  pc e55c0020  cpsr 600f0030
	09-26 13:59:53.608 16598 16598 F DEBUG   : 
	09-26 13:59:53.608 16598 16598 F DEBUG   : backtrace:
	09-26 13:59:53.610 16598 16598 F DEBUG   :     #00 pc 00000020  <anonymous:e55c0000>
	09-26 13:59:53.610 16598 16598 F DEBUG   :     #01 pc 00002478  /data/data/com.rockvole.kbmlviewer/app_flutter/vm_snapshot_instr
	09-26 13:59:53.712 15871 15871 I SearchServiceCore: Event Bus thread is disabled; marking main thread as EventBus
	09-26 13:59:53.848   601   610 I art     : Background partial concurrent mark sweep GC freed 69789(3MB) AllocSpace objects, 3(60KB) LOS objects, 33% free, 23MB/35MB, paused 1.095ms total 130.072ms
	09-26 13:59:54.070 16598 16598 E         : debuggerd: failed to kill process 16578: No such process
	09-26 13:59:54.074   601 16599 W ActivityManager:   Force finishing activity com.rockvole.kbmlviewer/.MainActivity
	09-26 13:59:54.075   185   185 W         : debuggerd: resuming target 16578
	09-26 13:59:54.076   601   619 I BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
	09-26 13:59:54.091   197   197 E lowmemorykiller: Error writing /proc/16578/oom_score_adj; errno=22
	09-26 13:59:54.119   601 13426 I ActivityManager: Process com.rockvole.kbmlviewer (pid 16578) has died
	09-26 13:59:54.119   601 13426 D ActivityManager: cleanUpApplicationRecord -- 16578
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: start new client, handoverId [0] client id [69802934172932476]
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: com.google.android.apps.gsa.shared.util.common.f: SearchServiceClient: start new client, handoverId [0] client id [69802934172932476]
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.apps.gsa.shared.util.common.e.a(SourceFile:43)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.apps.gsa.shared.util.common.e.f(SourceFile:6)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.apps.gsa.search.shared.service.SearchServiceClient.a(SourceFile:116)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.apps.gsa.search.shared.service.SearchServiceClient.mE(SourceFile:101)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.apps.gsa.nowoverlayservice.ay.h(SourceFile:18)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.libraries.gsa.d.b.o.an(SourceFile:15)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.google.android.libraries.gsa.d.b.o.handleMessage(SourceFile:23)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at android.os.Handler.dispatchMessage(Handler.java:98)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at android.os.Looper.loop(Looper.java:154)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at java.lang.reflect.Method.invoke(Native Method)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	09-26 13:59:54.155 15871 15871 W SearchServiceClient: Starting with NO_SESSION handoverId is deprecated. Just don't. You will break.
	09-26 13:59:54.155 15871 15871 W SessionLifecycleManager: Handover failed. Creating new session controller.
	09-26 13:59:54.167 15871 15871 E PBSessionCacheImpl: sessionId[69802934172932476] not persisted.
	09-26 13:59:54.171 15871 16183 I PBSessionCacheImpl: Deleted sessionId[69802934172932476] from persistence.
	09-26 13:59:54.172 15871 15871 I OptInState: There is a new client and it does not support opt-in. Dropping request.
	09-26 13:59:54.202   601 13430 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@19878b4 attribute=null, token = android.os.BinderProxy@5f77975
	09-26 13:59:54.233   601 13385 I OpenGLRenderer: Initialized EGL, version 1.4
	09-26 13:59:54.233   601 13385 D OpenGLRenderer: Swap behavior 2
	09-26 13:59:54.246 15871 15871 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
	09-26 13:59:54.246 15871 15871 I AudioController: Created new AudioSource
	09-26 13:59:54.248 15871 15871 I MicroDetectionWorker: onReady
	09-26 13:59:54.314 16516 16516 D GeckoMemoryMonitor: onTrimMemory() notification received with level 80
	09-26 13:59:54.348 15871 15944 I MicroRecognitionRunner: Starting detection.
	09-26 13:59:54.348 15871 16183 I MicrophoneInputStream: mic_starting  SR : 16000 CC : 16 SO : 1999
	09-26 13:59:54.351   236 16608 I AudioFlinger: AudioFlinger's thread 0xf2003980 ready to run
	09-26 13:59:54.355   236   290 I SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0
	09-26 13:59:54.357 15871 16183 I MicrophoneInputStream: mic_started  SR : 16000 CC : 16 SO : 1999
	09-26 13:59:54.426 16516 16516 D GeckoMemoryMonitor: onTrimMemory() notification received with level 80
	09-26 13:59:54.426 16516 16516 D GeckoMemoryMonitor: onTrimMemory() notification received with level 80
	09-26 13:59:54.451   235   235 I Zygote  : Process 16578 exited due to signal (11)
	09-26 13:59:54.534 15871 15871 I MicroDetectionWorker: onReady
	09-26 13:59:54.572 31145 16609 E NetworkScheduler: Invalid component specified.

**Comment by Rockvole** [comment] 2018-09-26 21:12
[✓] Flutter (Channel master, v0.9.4-pre.39, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.9.4-pre.39 at /work/installs/flutter
    • Framework revision 63f2fb9f5d (55 minutes ago), 2018-09-26 13:17:20 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /work/installs/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /work/installs/android-studio-3.0
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /work/installs/idea-IC-181.4445.78
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Nexus 9 • HT4B6JT00129 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.

**Comment by jason-simmons** [comment] 2018-09-27 01:04
Looks like this regressed starting at https://github.com/dart-lang/sdk/commit/de408202a5cacafd25d170fff9d232c24c8e4b5e

@a-siva @sjindel-google

**Comment by Rockvole** [comment] 2018-10-19 00:52
Strangely this problem does not appear on the Mac :

	flutter doctor -v
	[✓] Flutter (Channel master, v0.10.1-pre.89, on Mac OS X 10.13.6 17G65, locale en-CA)
		• Flutter version 0.10.1-pre.89 at /work/installs/flutter
		• Framework revision 751c083f7d (5 hours ago), 2018-10-19 03:56:18 +0800
		• Engine revision 104f057280
		• Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

	[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
		• Android SDK at /Users/david/Library/Android/sdk
		• Android NDK location not configured (optional; useful for native profiling support)
		• Platform android-28, build-tools 28.0.1
		• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
		• All Android licenses accepted.

	[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
		• Xcode at /Applications/Xcode.app/Contents/Developer
		• Xcode 9.4.1, Build version 9F2000
		• ios-deploy 1.9.2
		• CocoaPods version 1.5.3

	[✓] Android Studio (version 3.2)
		• Android Studio at /Applications/Android Studio.app/Contents
		• Flutter plugin version 29.1.1
		• Dart plugin version 181.5656
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

	[!] IntelliJ IDEA Community Edition (version 2018.2.5)
		• IntelliJ at /Applications/IntelliJ IDEA CE.app
		✗ Flutter plugin not installed; this adds Flutter specific functionality.
		• Dart plugin version 182.4999
		• For information about installing plugins, see
		  https://flutter.io/intellij-setup/#installing-the-plugins

	[✓] Connected device (1 available)
		• iPhone X • 9717A4E1-0F44-455A-979D-3CBD0B7D8BD0 • ios • iOS 11.4 (simulator)

	! Doctor found issues in 1 category.

But is still present in Linux :

	flutter doctor -v
	[✓] Flutter (Channel master, v0.10.1-pre.85, on Linux, locale en_CA.UTF-8)
		• Flutter version 0.10.1-pre.85 at /work/installs/flutter
		• Framework revision bbe8cf606e (7 hours ago), 2018-10-18 14:58:16 -0300
		• Engine revision 104f057280
		• Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

	[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
		• Android SDK at /home/david/Android/Sdk
		• Android NDK location not configured (optional; useful for native profiling support)
		• Platform android-27, build-tools 27.0.3
		• ANDROID_HOME = /home/david/Android/Sdk
		• Java binary at: /work/installs/android-studio-3.0/jre/bin/java
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
		• All Android licenses accepted.

	[✓] Android Studio (version 3.2)
		• Android Studio at /work/installs/android-studio-3.0
		• Flutter plugin version 29.1.1
		• Dart plugin version 181.5656
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

	[!] IntelliJ IDEA Community Edition (version 2018.2)
		• IntelliJ at /work/installs/idea-IC-181.4445.78
		✗ Flutter plugin not installed; this adds Flutter specific functionality.
		• Dart plugin version 182.3569.4
		• For information about installing plugins, see
		  https://flutter.io/intellij-setup/#installing-the-plugins

	[!] Connected device
		! No devices available

	! Doctor found issues in 2 categories.

**Comment by Rockvole** [comment] 2018-10-19 15:15
Tried again with a newer Linux version, but still not working.

    Flutter version 0.10.1-pre.99 at /work/installs/flutter

**Comment by sjindel-google** [comment] 2018-10-19 17:37
I am working on this now. I landed some changes a while ago which broke obfuscation, but we didn't have any test configurations with obfuscation enabled, so the regression went unnoticed.

**Comment by sjindel-google** [comment] 2018-11-07 15:10
Obfuscation has been fixed in Dart in commit e23acaaf90996b84548ea23af14730ff1a21d826, and we've added a test configuration to ensure obfuscation support in Dart doesn't regress again.

Obfuscation requires the declaration of entry-points which are otherwise not needed if they are referenced by other entry-points. This uncovered several missing entry-points in Flutter. We've added some safeguards to ensure that classes looked-up by name are declared to be entry-points in non-obfuscated mode, but Flutter may still want to add an obfuscation test configuration as well.

Also, it looks like Dart rolls into Flutter were stopped shortly before the fixes landed. Support for obfuscation will need to be cherry-picked to be available in Flutter 1.0.

**Comment by a-siva** [comment] 2018-11-08 03:05
Which CL specifically are you referring to?

**Comment by sjindel-google** [comment] 2018-11-08 11:40
e23acaaf90996b84548ea23af14730ff1a21d826

**Comment by a-siva** [comment] 2018-11-09 22:57
The change has been cherry picked into the flutter tree.

**Closed by a-siva** 2018-11-09 22:57 UTC
Labels: dependency: dart, severe: regression, tool

**Comment by Rockvole** [comment] 2018-11-20 21:17
Looks to be working now :

	Flutter (Channel master, v0.11.9-pre.3, on Linux, locale en_CA.UTF-8)
		• Flutter version 0.11.9-pre.3 at /work/installs/flutter
		• Framework revision 5251306886 (3 hours ago), 2018-11-20 10:21:36 -0800
		• Engine revision 1baf081343
		• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
