### ISSUE TITLE
Users are seeing long first-runs due to maven download step

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10211] opened 2017-05-19 20:01 UTC
We had a problem on iOS where `pod setup` would run during the first `pod install` and cause extremely long launch times.

We seem now to be hitting something similar on Android wth maven downloading dependencies the first time it's run.

Can we invoke Maven in a way such that it refuses to do that?  And also teach `flutter doctor` to explain when those dependencies haven't been downloaded?  This will move more setup stuff to setup time instead of run time where the user is surprised.

@mit-mit @collinjackson @jakobr-google

**Comment by mit-mit** [comment] 2017-05-19 20:04
Sample log I grabbed yesterday:
https://gist.github.com/mit-mit/24cf3edee20833849b9584243afe0884

The downloads end up in `~/.gradle/cache`

**Comment by DanTup** [comment] 2017-05-19 20:07
Today I'm seeing the same thing; hangs here:

```text
PS M:\Coding\Applications\flutter\examples\hello_world> flutter build -v apk
(SNIP)
[       +3 ms] License for package Android Support Repository accepted.
[       +5 ms] Preparing "Install Android Support Repository".
```

I installed via `sdkmanager` and it took an age, but did eventually complete. I presume if I'd retried/left it long enough using `flutter` it would have too.

**Comment by jakobr-google** [comment] 2017-05-22 11:22
This is different from the `pod setup` issue we had on iOS. The Maven repo itself is online, whereas CocoaPods needs a local copy of the repo.

The "problem" here is downloading the actual packages, and you'll get a similar thing on iOS when you start using plugins that depend on other pods - we have to download them the first time they're referenced.

We have one extra hurdle here for Android, in the Android SDK. If your app requires a version of the SDK that isn't currently installed, Gradle will download that version automatically (which is what's happening in @DanTup's example), and since the SDK is large, this takes quite a while.

We can't really have `flutter doctor` check for this, since it depends very much on what the individual app requires in terms of SDK and other artifacts. We pretty much have to know which app you want to build, before we can tell you if you have everything you need.

You *can* tell Gradle to not download artifacts (and/or Android SDK's) automatically, but that just makes for a horrible build experience where your build fails, and you have to manually run some other commands first to download the dependencies and make it work. And then repeat that if you change SDK versions or add a native dependency.

I'd suggest we figure out a way to keep users informed of what's going on, and why it's taking a while.

**Comment by mit-mit** [comment] 2017-05-24 11:47
I tested this on a clean macOS install (in a VM) with Android Studio. They have the exact same behavoir: After installing Android Studio, and creating your first app, the first build of an app takes a while longer as `~/.gradle/cache` has not been populated yet. Normally you don't notice this, as the downloads complete pretty fast; we just saw it at I/O due to bad networking and throttling.

**Comment by mit-mit** [comment] 2017-05-24 11:47
Closing, this is WAI

**Closed by mit-mit** 2017-05-24 11:47 UTC

**Comment by DanTup** [comment] 2017-05-24 12:12
What's WAI?

**Comment by mit-mit** [comment] 2017-05-24 12:12
Sorry, Working As Intended

**Comment by DanTup** [comment] 2017-05-24 12:15
Oh, working as intended! If it's not normally this slow, probably not an issue. I think it would be better if the message made it clear it was downloading though; "preparing to install" doesn't sound like it is; if it said downloading them the long pause wouldn't be so confusing :-)

**Comment by mit-mit** [comment] 2017-05-24 12:27
Yes, that would be better, but I think it's out of our control, deep inside gradle. I didn't get any further feedback from Android Studio either.

But in the usual case this should take no more than 10-20 seconds.

The better fix for this would be for us to manage / bundle some of these dependencies as part of setup; something we are looking into.

**Comment by sethladd** [comment] 2017-05-24 15:38
Can we print something from our tools, right before we kick off the gradle build, saying "this may take up to 60 seconds" ? Let's set expectations for our developers so they know to wait around.

**Comment by DanTup** [comment] 2017-05-24 17:01
> this may take up to 60 seconds

Based on the speeds last week and that this depends on the users internet connection, I'd probably be a bit more generous! :D "This usually takes less than 60 seconds"? "This may take a few minutes"?

**Comment by DanTup** [comment] 2017-05-24 17:02
> Yes, that would be better, but I think it's out of our control, deep inside gradle.

Oh, I thought Gradle was totally generic and the Android stuff was just in a script you'd written

> this may take up to 60 seconds

Based on the speeds last week and that this depends on the users internet connection, I'd probably be a bit more generous! :D "This usually takes less than 60 seconds"? "This may take a few minutes"?
