### ISSUE TITLE
NestedScrollView extra bottom padding

### ISSUE THREAD

**Issue by jlow94** [flutter/flutter#37152] opened 2019-07-29 04:52 UTC
## Steps to Reproduce

I'm creating a page with a `NestedScrollView` as well as a `SliverAppBar` to create a CollapsingToolbarLayout parallax effect. Everything works, but I'm getting a pretty huge margin at the bottom of the `NestedScrollView`. 

I believe it is caused by the `NestedScrollView` because wrapping a colored `Container` around it shows that the height is entirely it's own, not it's children.

Attached below are some screenshot to help visualize my problem:

Huge extra margin between widget and bottom of screen (Widget is centered)
![device-2019-07-29-132746](https://user-images.githubusercontent.com/49853787/62022335-d2eff580-b206-11e9-935b-4a0523528298.png)

`SingleChildScrollView` wraps height to content
![device-2019-07-29-132803](https://user-images.githubusercontent.com/49853787/62022339-d5eae600-b206-11e9-871a-21934f05b8eb.png)

And here is a snippet from my code (ignore override annotations as I cherry pick the relevant methods from child classes to make it more coherent):

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
          stream: bloc.dataStateStream,
          initialData: DataLoadingState(),
          builder: (context, snapshot) {
            var state = snapshot.data;

            if (state is DataLoadingState) {
              bloc.loadData();
              return _buildLoading();
            } else {
              return _buildDataLoaded();
            }
          }),
    );
  }

...........

Widget _buildDataLoaded() {
    return Container(
      child: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) {
            return [
              SliverAppBar(
                expandedHeight: 300,
                flexibleSpace: FlexibleSpaceBar(
                  background: buildHeader(),
                ),
                automaticallyImplyLeading: true,
                pinned: false,
                floating: false,
                actions: buildOptionMenu(),
              ),
            ];
          },
          body: Center(
            child: SingleChildScrollView(
              child: Container(
                child: Column(
                  children: <Widget>[buildBody()],
                ),
              ),
            ),
          )
      ),
    );
  }

....

@override
  Widget buildBody() {
    return Column(
      children: <Widget>[_buildBio()],
    );
  }

  Widget _buildBio() {
    var dataContent = Column(
      children: <Widget>[
        _buildMetadata(),
        _buildTitle(),
        Text("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tristique justo sed velit lacinia pretium. Nullam elementum mi et enim consectetur, vel efficitur neque mattis. Nunc ultricies neque enim, et auctor velit pharetra vitae. Nunc tincidunt ligula massa, sed bibendum massa posuere nec. Aliquam tempor nibh eros, eu pulvinar augue blandit a. Morbi orci ligula, bibendum vitae elit eget, convallis tempus est. Suspendisse id magna suscipit nisl tempor scelerisque. In et mi pharetra, iaculis velit eget, volutpat nisl. Donec id sapien at ligula maximus vulputate ut eget sem. Aenean sed dui at sapien euismod dignissim. Aenean eget cursus metus, ac vehicula ex.")
      ],
    );

    return Card(
        child: Padding(
            padding: const EdgeInsets.all(16),
            child: dataContent));
  }
```

Also, I think it is worth mentioning that the example widget as part of `NestedScrollView`'s documentation also has this problem when I tried to compile it, and the only other mention of this issue is found in this [ticket](https://github.com/flutter/flutter/issues/20321)

**Comment by jlow94** [comment] 2019-07-30 06:39
After building and testing it out the same code on an iPhone, seems like the problem is not existent.

Is this a bug specific to Android?

**Comment by BondarenkoStas** [comment] 2019-09-20 22:32
@jlow94 Please provide your ```flutter doctor -v``` output.

**Comment by SerhiiMeketiuk** [comment] 2019-09-26 18:48
Same problem.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2905606/65716062-b2c1a300-e09e-11e9-9dac-613d4d014cfc.gif)

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocListener(
        bloc: _productsBloc,
        listener: (BuildContext context, ProductsState state) {
          if (state is LoadedProductsState) {
            _refreshController.refreshCompleted();
            HapticFeedback.lightImpact();
          }
        },
        child: BlocBuilder<ProductsBloc, ProductsState>(
          bloc: _productsBloc,
          builder: (
            BuildContext context,
            ProductsState currentState,
          ) {
            return NestedScrollView(
              headerSliverBuilder:
                  (BuildContext context, bool innerBoxIsScrolled) => [
                ZSliverAppBar(
                  titleActionIconData: FontAwesomeIcons.search,
                  titleActionOnPressed: null,
                  headlineText: AppLocalizations.of(context)
                      .translate('features.products.title'),
                  subHeadText: _buildProductsAppBarCounter(currentState),
                )
              ],
              body: SmartRefresher(
                controller: _refreshController,
                onRefresh: () => _onRefresh(currentState),
                child: ZEmptySate(
                    type: ZEmptyStateType.empty,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
```

**Comment by Henkvanslochteren** [comment] 2019-10-06 12:22
I'm experiencing this problem aswell. What i found out while testing is that the paddig gets smaller if the 'body' content is bigger. So a longer card would output less padding. If you add enough content the padden eventually disappears. 

This problem occurs both on Android and IOS.
`[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at /Users/tim/flutter
    • Framework revision cc949a8e8b (9 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • D57BBA9A-3AED-4353-B50A-71D2BA5CE4AF • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
`
`
return NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
                backgroundColor: Colors.black,
                pinned: true,
                expandedHeight: 250,
                flexibleSpace: FlexibleSpaceBar(
                    background:SizedBox()
                ))
          ];
        },
        body: Container(color: Colors.red, child: SizedBox()),
    );
`

fill in the last Sizedbox with any content and bottom padding is added without any trace where it comes from.

**Comment by jlow94** [comment] 2019-10-07 03:41
Hi @BondarenkoStas , sorry for the very late reply, but here is my flutter doctor output. For the record, I'm on Android Studio

```
| => flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-JP)
    • Flutter version 1.9.1+hotfix.2 at /Users/jason/Developer/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jlow94** [comment] 2019-10-07 03:42
And yes, seems like the problem persists in both Android and iOS.

**Comment by devibrahimkarahan** [comment] 2019-10-21 08:39
I have the same issue

![image](https://user-images.githubusercontent.com/7039967/67189644-46189a80-f3f7-11e9-8618-0dac3e0549bb.png)

My scaffold:

```
Scaffold(
      backgroundColor: Colors.grey,
      body: NestedScrollView(
        headerSliverBuilder: (context, isScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 200,
              pinned: true,
              flexibleSpace: FlexibleSpaceBar(
                title: Text("title"),
              ),
            ),
          ];
        },
        body: PageView(
          children: <Widget>[
            ListView.builder(
              padding: EdgeInsets.zero,
              itemCount: 10,
              itemBuilder: (context, index) {
                return Card(
                  margin: const EdgeInsets.fromLTRB(12, 6, 12, 6),
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text("item"),
                  ),
                );
              },
            ),
          ],
        ),
      ),
    );
```

**Comment by Henkvanslochteren** [comment] 2019-10-26 17:06
This did not fix it in my application. Still the same problem.

**Comment by Jemaz** [comment] 2020-01-22 15:52
I can confirm @devibrahimkarahan 's solution works in my case. Many thanks :+1:

**Comment by Piinks** [comment] 2020-01-23 23:18
@Jemaz and @devibrahimkarahan I am glad the issue has been resolved for you.
@Henkvanslochteren, can you provide a runnable reproduction of your issue so we can identify what is different from some of the other samples provided here, and what the root cause may be?

**Comment by Piinks** [comment] 2020-01-23 23:19
This may be similar to #46028

**Comment by Henkvanslochteren** [comment] 2020-01-25 12:33
Thank you for the reply, even after so long :).
Use the following code to reproduce. It accually looks a lot like the issue you just mentioned. We also have this problem in a production app for months. It's not too disruptive though.

```
return NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return <Widget>[
          SliverAppBar(
              backgroundColor: Colors.blue,
              pinned: true,
              expandedHeight: 250,
              flexibleSpace: FlexibleSpaceBar(
                  background:SizedBox(
                  )
              ))
        ];
      },
      body: Container(color: Colors.white, child: SizedBox(child: Text("Hello"),)),
    );
```

```
[√] Flutter (Channel dev, v1.14.4, on Microsoft Windows [Version 10.0.18363.592], locale nl-NL)
    • Flutter version 1.14.4 at C:\flutter
    • Framework revision 5e1000cd85 (2 days ago), 2020-01-23 13:27:01 -0800
    • Engine revision 83a64b7233
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\thoek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G955F • ce07171745399c220c • android-arm64 • Android 9 (API 28)

• No issues found!
```
I also have these screenshots to show the problem.
1: Start 
2: Should stop scrolling here
3: Can scroll further than 2 (Hello is hidden under the blue bar.)
![Screenshot_20200125-131922](https://user-images.githubusercontent.com/10516786/73121104-c14d9780-3f76-11ea-8663-e268892edfb2.png)

**Comment by Piinks** [comment] 2020-01-27 18:09
@Henkvanslochteren Thank you for the reproduction info! 

Have you tried using the `SliverOverlapAbsorber/SliverOverlapInjector` to make the inner lists align correctly? 

The similar bug I mentioned (#46028) is also not using these overlap aids in the `NestedScrollView`. These widgets are helpful since the _inner_ scrollable does not know about any overlap or preceding extent that the _outer_ scrollable may have. The use of these overlap widgets is demonstrated in the api docs for [`NestedScrollView`](https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html).  

I am going to continue investigating this, but if it is successful for you, please let me know. Thanks! :)

**Comment by abdulmuaz97** [comment] 2020-01-28 00:52
hey there, If you still having the problem and have the latest version of **Flutter** which is **1.12.13+hotfix.5** then try this code..
I've no problem with it at all, **NO BOTTOM SPACE**

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: buildBody(),
    );
  }

  Widget buildBody() {
    return NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return [buildSliverAppBar()];
      },
      body: buildCenterBody(),
    );
  }

  SliverAppBar buildSliverAppBar() {
    return SliverAppBar(
      title: Text('AppBar Title'),
      centerTitle: true,
      floating: true,
      snap: true,
    );
  }

  Widget buildCenterBody() {
    return Container(
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text('One Item'),
            Text('Another Item'),
            Text('etc...'),
          ],
        ),
      ),
    );
  }
```

the **BOTTOM SPACE** can be appear in case you use **ListView** instead of **SingleChildScrollView** but just don't do that :) and you're good to go.

**Comment by Henkvanslochteren** [comment] 2020-02-02 16:48
@Piinks The new information in the docs have fixed my issues. The difference with the earlier suggestion is to add the Builder in the body together with the SliverOverlapAbsorber.

The docs are perfectly clear now so i think this issue can be closed. Happy to see this fixed/explained in the docs as it has been an issue for quite a while in our apps.

**Comment by Piinks** [comment] 2020-02-03 17:58
Hi @Henkvanslochteren! Thank you!  I am so glad to hear. I will close this then, and continue to validate through the similar issue.

**Closed by Piinks** 2020-02-03 17:58 UTC
Labels: d: examples, documentation, f: scrolling, framework
