### ISSUE TITLE
How can I listen the event when video play to end?

### ISSUE THREAD

**Issue by ZhongMingKun** [flutter/flutter#28827] opened 2019-03-04 09:29 UTC
I want to show a picture when the video play to end.But I can't listen the event.

**Comment by Ehesp** [comment] 2020-10-09 12:50
Related / Dupe: https://github.com/flutter/flutter/issues/21929

**Comment by stuartmorgan** [comment] 2023-03-19 21:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/21929, which has more discussion and votes.

**Closed by stuartmorgan** 2023-03-19 21:38 UTC
Labels: new feature, plugin, a: video, p: video_player, P4
