### ISSUE TITLE
Invoke Flutter MethodChannel from Android and wait for the result to finish

### ISSUE THREAD

**Issue by word-x** [flutter/flutter#133426] opened 2023-08-28 02:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

On Android side, I need to get a data that will be returned by Flutter side MethodChnnel.

As we know, on Flutter side, we can easily user Dart async/await() the result from Native side. But on Android side, it seems that can't use runBlocking or similar ways to wait for the callback to finish and get the returned data. Using runblocking will cause a UI frozen .

### Proposal

Can we get a new Feature to await() the callback result on Android side just as what we do on Dart?

Sometimes, we need to get the result and then assign the result to other varaibles.

### Something like

        fun getFlutterData(): String? {
            var res: String? = null
            runBlocking {
                res = suspendCoroutine {
                    channel!!.invokeMethod(flutterMethod, params, object : MethodChannel.Result {
                         override fun success(result: Any?) {
                            println("callFlutterMethod success: $result")
                             it.resume(res)
                        }

                        override fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
                            println("callFlutterMethod error: $errorCode, $errorMessage,$errorDetails")
                        }

                        override fun notImplemented() {
                        }
                    })

                }
            }
            
            
            return res

        }

Is is possible or there is some other method?

**Comment by darshankawar** [comment] 2023-08-28 09:55
@word-x 
Can you take a look at below links and check if they help to resolve / answer your case ?


https://stackoverflow.com/questions/60294547/flutter-how-to-wait-for-android-platform-channel-function-to-complete-and-retur

https://stackoverflow.com/questions/75380908/call-async-flutter-function-in-android-cant-get-return-value


https://groups.google.com/g/flutter-dev/c/QaxqevHplF4?pli=1

**Comment by stuartmorgan** [comment] 2023-08-28 10:48
> As we know, on Flutter side, we can easily user Dart async/await() the result from Native side. But on Android side, it seems that can't use runBlocking or similar ways to wait for the callback to finish and get the returned data. Using runblocking will cause a UI frozen .

Those things are not at all analogous.

> Can we get a new Feature to await() the callback result on Android side

If you want new language features in Kotlin you would need to file that against Kotlin, not Flutter. However:

> just as what we do on Dart?

What you have shown would not work in Dart. It's roughly the equivalent of:

```dart
String? thisFunctionIsNotAsync() {
  return await channel.invokeMethod(...);
}
```

which would not even compile, because you can't `await` in a function that is not `async`.

> Sometimes, we need to get the result and then assign the result to other varaibles.

And the way to do that is to do so in a async context (i.e., a coroutine in Kotlin), just as it would be in Dart. The problem you have is whatever in your code structure makes you want to use `runBlocking`—whose documentation about the limited places it should be used I encourage you to read—here. Calling across a method channel is an inherently asynchronous operation (see my previous response to you in https://github.com/flutter/flutter/issues/133369), and trying to force it to be synchronous will not work in Kotlin, just as it would not work in Dart.

Closing as a duplicate of https://github.com/flutter/flutter/issues/133369 / https://github.com/flutter/flutter/issues/28310.

**Closed by stuartmorgan** 2023-08-28 10:48 UTC
Labels: waiting for customer response, in triage

**Comment by word-x** [comment] 2023-08-29 13:35
https://github.com/flutter/flutter/issues/133369#issuecomment-1697454068
