### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by zouchuncheng** [flutter/flutter#102287] opened 2022-04-21 08:15 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:130:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:88:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:152:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:442:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:229:25)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dwds.dart:91:9)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:686:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 22.04 LTS 5.15.0-25-generic, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/zcc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/zcc/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /home/zcc/android-studio-2021.1.1.8-linux/android-studio
    • ANDROID_SDK_ROOT = /home/zcc/Android/Sdk
    • Java binary at: /home/zcc/android-studio-2021.1.1.8-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/zcc/android-studio-2021.1.1.8-linux/android-studio
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1
    • NO_PROXY contains localhost
    ! NO_PROXY does not contain 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04 LTS 5.15.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.0+20
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 45508985b1355a6a8a045024ca0d94e20cd4ac20

**Comment by danagbemava-nc** [comment] 2022-04-21 08:45
Closing as duplicate of #97604

**Closed by danagbemava-nc** 2022-04-21 08:45 UTC
Labels: in triage
