### ISSUE TITLE
Unable to Run on iOS

### ISSUE THREAD

**Issue by Jayvd** [flutter/flutter#83480] opened 2021-05-27 13:49 UTC
I tried to run on iOS but I get this deprecation message.

Any help please?? Thank you

```
/Users/jayvd/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-6.0.0/ios/Classes/FlutterLocalNotificationsPlugin.m:13:5: warning: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest [-Wdeprecated-declarations]
        UILocalNotification *_launchNotification;
        ^
    In module 'UIKit' imported from /Users/jayvd/Google Drive/SOFTWARE/cosmology/ios/Pods/Target Support Files/flutter_local_notifications/flutter_local_notifications-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked deprecated here
    @interface UILocalNotification : NSObject<NSCopying, NSCoding>
               ^
    /Users/jayvd/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-6.0.0/ios/Classes/FlutterLocalNotificationsPlugin.m:293:4: warning: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest [-Wdeprecated-declarations]
    - (UILocalNotification *)buildStandardUILocalNotification:(NSDictionary *)arguments {
       ^
    In module 'UIKit' imported from /Users/jayvd/Google Drive/SOFTWARE/cosmology/ios/Pods/Target Support Files/flutter_local_notifications/flutter_local_notifications-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked deprecated here
    @interface UILocalNotification : NSObject<NSCopying, NSCoding>
```

**Comment by urusai88** [comment] 2021-05-27 14:05
Its just deprecations, no errors, you able to run application

**Comment by TahaTesser** [comment] 2021-05-27 14:17
Hi @Jayvd 
As mentioned above, deprecation messages aren't errors and it is coming from  `flutter_local_notifications` (third-party package) 

Please provide a `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
Thank you

**Comment by Jayvd** [comment] 2021-05-27 15:01
Thank you for replying!


Flutter doctor -v

```
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!
Jayvd@Jayvds-iMac cosmology % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
    • Flutter version 2.2.0 at /Users/Jayvd/tools/flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Jayvd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 5EB3A6C6-F84E-4080-97F6-23D51270EBDC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 91.0.4472.77
`


```
Flutter run -v
```

[ +680 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11 Pro.
[   +3 ms] "flutter run" took 44,415ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +162 ms] ensureAnalyticsSent: 160ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```


pubspec.yaml
```

`name: cosmology
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2
  path_provider: ^2.0.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  permission_handler: ^8.0.0+2
  assets_audio_player: ^3.0.3+3
  flutter_local_notifications: ^6.0.0
  flutter_tags: ^0.4.9+1
  fluttertoast: ^8.0.7
  wakelock: ^0.5.2
  json_utilities: ^0.1.3
  url_launcher: ^6.0.4
  flutter_spinkit: ^5.0.0
  dotted_line: ^3.0.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoSansExtraThin
      fonts:
        - asset: fonts/MuseoSans/MuseoSans-100.otf
    - family: MuseoSansThin
      fonts:
        - asset: fonts/MuseoSans/MuseoSans-300.otf
    - family: MuseoSansRegular
      fonts:
        - asset: fonts/MuseoSans/MuseoSans-500.otf
    - family: MuseoSansSemiBold
      fonts:
        - asset: fonts/MuseoSans/MuseoSans-700.otf
    - family: MuseoSansExtraBold
      fonts:
        - asset: fonts/MuseoSans/MuseoSans-900.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

```

**Comment by TahaTesser** [comment] 2021-05-28 07:01
Hi @Jayvd
You seem to be using third-party packages, your logs also incomplete. please try to isolate the issue to Flutter-specific or package-specific issues. If the issue is from `flutter_local_notifications` or any other third-party package, please file a new issue on the package's GitHub repository, 

If the issue reproduces without third-party packages, provide details below 
Can you please provide a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
Thank you

**Comment by darshankawar** [comment] 2021-06-18 12:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-18 12:59 UTC
Labels: in triage, waiting for customer response
