### ISSUE TITLE
TabBars animate in in --release builds but not --debug builds

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10531] opened 2017-06-06 17:06 UTC
@Hixie says this is because we size a 0x0 in release builds, but not --debug builds.

This is causing bad behavior in Posse's latest app.  FYI @HansMuller

**Comment by Hixie** [comment] 2017-06-06 19:05
IMHO we need to make the implicit animation widgets not animate when there's been an app-wide geometry change. To do this we should pump a message down the entire layout tree when that happens (finally replacing the "rotate" stub), and when the implicit animation widgets hear about this they should reset themselves to their "neutral" state so that they don't animate on the next frame.

**Comment by Hixie** [comment] 2017-06-07 18:18
Source in https://github.com/flutter/flutter/issues/10542 may help.

**Comment by HansMuller** [comment] 2017-06-07 22:40
In release mode the app is often asked to layout before the engine has initialized to the point where the size of the screen is known. In that case the app is built and laid out with 0x0 constraints and then later with the screen's actual size.

The phantom tabbar scrolling seen here upon app startup is due to the scrollable tabbar's scroll offset being "corrected" once the tab bar's size is constrained to a non-zero value. The correction happens in ScrollPosition.applyNewDimensions() which calls the IdleScrollActivity method with the same name, which ballistic-scrolls the scroll offset to 0.

The phantom scroll can be worked around but not building anything until the app's size is non-zero.

This app can be used to demonstrate the problem and includes the workaround: https://gist.github.com/HansMuller/5d0e670737501b4b25e1b694325c4f4f

**Comment by eseidelGoogle** [comment] 2017-06-15 23:47
Given this has a workaround, I suspect this isn't actually a blocker?  But definitely a bug we should still fix?

**Comment by eseidelGoogle** [comment] 2017-06-19 17:57
I need to get @lukef an answer by tomorrow as to if he should workaround this, or wait for us to resolve.

**Comment by eseidelGoogle** [comment] 2017-06-20 00:34
Feedback from @alardizabal is that he would rather wait for the fix.

**Comment by alardizabal** [comment] 2017-06-20 15:21
I implemented the fix suggested by @HansMuller and I can confirm that it works for our case.

**Comment by Hixie** [comment] 2017-12-13 00:17
This is not on our short-term priority list. Moving to next milestone.

**Comment by Hixie** [comment] 2019-02-05 08:54
A better solution than my idea above, since this seems to be one of the few symptoms, would be to set things up so the animation doesn't happen in this case. I bet we're doing weird math at width zero in the tab bar.

**Comment by goderbauer** [comment] 2019-02-06 00:40
Posted a suggested fix at https://github.com/flutter/flutter/pull/27568 with a brief explanation of why this is happening.

**Closed** 2019-02-06 22:39 UTC
Labels: a: animation, customer: posse (eap), framework
