### ISSUE TITLE
[Impeller] Feedback: macOS opportunities for optimization.

### ISSUE THREAD

**Issue by isaacadariku** [flutter/flutter#134547] opened 2023-09-12 15:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

We ran the Impeller experiment on the [Reflection.app macOS app](https://flutter.dev/showcase/reflectionapp) and have seen some promising results.

# Here are a few highlights:

## Baseline Metrics (Before Implementing Impeller):

- **Frame Rate (Before):** The frame rate remained consistent, with no significant jank observed in our app.
- **Startup Jank:** On initial startup, we observed the shader compilation jank warning in DevTools.
- **SkSL Warm-up:** No SkSL warm-up data was collected, as it was redundant with Impeller.
- **Issues/Notes (Before):** No critical issues, We did notice some jank during navigation and a noticeable increase in the jank frames, but no jank warnings were issued.

## Impeller Testing Results:

- **Frame Rate (Impeller Enabled):** With Impeller enabled, the frame rate continued to perform well, showing no significant degradation.
- **Bug Testing:** Initial startup had an increase in jank but did not produce any critical bugs or jank warnings, highlighting the stability of Impeller.
- **Jank During Navigation:** While navigating through views and tabs, we did notice a slight increase in jank; however, no jank warnings were issued.
- **Horizontal Scroll:** Notably, when performing horizontal scrolls with Impeller enabled, an increase in jank was observed compared to the performance without Impeller.

## Our takeaways:

- The implementation of Impeller has generally improved the app performance. Looking at the stability of the frame rate they were consistent and low.
- There were no critical bugs or jank warnings which was a great sign.
- There was increased jank during navigation, although not alarming, it could be an area for further optimization.
- The most noticeable impact was during horizontal scrolling, where the difference in jank between Impeller-enabled and Impeller-disabled states was significant. This can be seen in the exported JSON towards the last frames

## Exported JSON Data:
Here are exports of the end result JSON data in case the Flutter team would like to dive in for a more detailed analysis.

[without_impeller_dart_devtools_2023-09-07_15_05_29.889.json](https://drive.google.com/file/d/1rQZ1F6pZfU99p3gWuwfN928SDOyr6mhl/view?usp=drive_link)

[with_impeller_dart_devtools_2023-09-07_15_48_22.232.json](https://drive.google.com/file/d/1PI5fOqfccgCSXNH1L2N-3fNox5VcoMhj/view?usp=drive_link)

We hope this is helpful, and if there are other ways we can support the Flutter team, please let us know!

**Comment by jonahwilliams** [comment] 2023-09-13 00:17
Generally we'd need to see some examples of what the app is doing during the slow frames, or even better some reproducible examples, in order to determine what improvements (if any) are possible. The timeline itself isn't enought to go off of.

**Comment by leighajarett** [comment] 2023-09-13 14:58
@isaacadariku do you think that's something you can add more color to? Perhaps a video recording?

**Comment by jonahwilliams** [comment] 2023-11-04 19:47
Because we never got any actionable data from this issue report, I'm closing it. In the future, example code can help us pinpoint performance issues.

**Closed by jonahwilliams** 2023-11-04 19:47 UTC
Labels: P2, e: impeller, team-engine, triaged-engine
