### ISSUE TITLE
Would like instructions on how to take a trace :)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17398] opened 2018-05-08 19:20 UTC
I don't see any in https://flutter.io/ui-performance/, but maybe they're somewhere else?

I'm attempting to reply to: https://github.com/flutter/flutter/issues/7053#issuecomment-383525588 and request a trace.

**Comment by zoechi** [comment] 2018-12-06 13:09
Duplicate of #4934

**Closed by zoechi** 2018-12-06 13:09 UTC
Labels: d: website - content
