### ISSUE TITLE
SliverFillRemaining goes behind SliverPersistentHeader

### ISSUE THREAD

**Issue by kndl22** [flutter/flutter#62194] opened 2020-07-24 12:33 UTC
I'm using a CustomScrollView that has this hierarchy:

1. SliverPersistentHeader
2. SliverPersistentHeader
3. SliverFillRemaining

The 1st SliverPersistentHeader isn't pinned, the 2nd SliverPersistentHeader is pinned and I expect that SliverFillRemaining will always be below the second SliverPersistentHeader.

The SliverFillRemaining contains a scrollable list and therefor it has hasScrollBody property set to true.

Currently SliverFillRemaining when builded is located below the 2nd header, but when scrolling it goes behind the 2nd header until reaching the AppBar. How can I make SliverFillRemaining to always be placed below the 2nd header?

Some code:

```
CustomScrollView(
          physics: ClampingScrollPhysics(),
          slivers: <Widget>[
            SliverPersistentHeader(
              pinned: false,
              delegate: _SliverAppBarDelegate(
                  minHeight: 0.0,
                  maxHeight: 340.0,
                  child: ClipRect(
                    child: OverflowBox(
                      alignment: Alignment.topLeft,
                      maxHeight: 340.0,
                      child: Column(
                        children: <Widget>[
                          Widget1()
                          Widget2(),
                        ],
                      ),
                    ),
                  )
              ),
            ),
            SliverPersistentHeader(
              pinned: true,
              delegate: _SliverAppBarDelegate(
                  minHeight: 50.0,
                  maxHeight: 55.0,
                  child: Column(
                    children: <Widget>[
                      Widget3(),
                    ],
                  ),
              ),
            ),
            SliverFillRemaining(
              hasScrollBody: true,
              child: Column(
                children: <Widget>[
                  Widget4(),
                ],
              ),
            )
          ],         
        ),
```

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-IL)
    • Flutter version 1.17.5 at /Users/ycal/Developer/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ycal/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 • 1811ECB0-2C0F-445B-8226-B2A9A5A0AF50 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-24 15:09
Hi @kndl22,

<details>
 <summary>I made the code sample complete</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: CustomScrollView(
          physics: ClampingScrollPhysics(),
          slivers: <Widget>[
            SliverPersistentHeader(
              pinned: false,
              delegate: Delegate1(),
            ),
            SliverPersistentHeader(
              pinned: true,
              delegate: Delegate2(),
            ),
            SliverFillRemaining(
              hasScrollBody: true,
              child: ListView(
                children: <Widget>[
                  Placeholder(
                    fallbackHeight: 1000,
                  )
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}

class Delegate1 extends SliverPersistentHeaderDelegate {
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) => Container(color: Colors.yellow);

  @override
  double get maxExtent => 150;

  @override
  double get minExtent => 50;

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) => true;
}

class Delegate2 extends SliverPersistentHeaderDelegate {
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) => Container(color: Colors.red);

  @override
  double get maxExtent => 150;

  @override
  double get minExtent => 50;

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) => true;
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/dev/flutter
    • Framework revision e64fe11542 (11 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

@kndl22 Does the screen recording represent your issue?
Top of SliverFillRemaining is hidden behind SliverPersistentHeader when it's minimized

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/88405711-4efc2980-cdd8-11ea-8acf-a9a0af80ecff.gif)

**Comment by Piinks** [comment] 2020-07-24 17:22
In the reproduction you provided, `SliverFillRemaining.hasScrollBody` is true. In this case, `SliverFillRemaining` will fill the entire screen, since a scroll view can be infinitely long. Your reproduction does not appear to have a scroll view as the child of the SFR widget, so you could use `SliverFillRemaining.hasScrollBody: false` to create the described effect.

Putting a scroll view inside of the `SliverFillRemaining` would make this a nested scrolling use case, with the scrollable list is nested inside of your `CustomScrollView`. Have you tried using a `NestedScrollView` instead?

**Comment by kndl22** [comment] 2020-07-25 09:15
@VladyslavBondarenko Hi, that's exactly the issue i'm experiencing.

@Piinks So you mean I'll have to wrap my child of SliverFillRemaining inside a NestedScrollView or replacing the existing CustomScrollView with nested one?

**Comment by Piinks** [comment] 2020-07-27 18:05
> @Piinks So you mean I'll have to wrap my child of SliverFillRemaining inside a NestedScrollView or replacing the existing CustomScrollView with nested one?

The later, replacing your `CustomScrollView` with a `NestedScrollView`. By using this widget instead, you can use the `SliverOverlap*` widgets to appropriately manage the pinned persistent header's overlap. I believe the first example in the api documentation demonstrates your use case: https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html 

> SliverOverlapAbsorber(
              // This widget takes the overlapping behavior of the SliverAppBar,
              // and redirects it to the SliverOverlapInjector below. If it is
              // missing, then it is possible for the nested "inner" scroll view
              // below to end up under the SliverAppBar even when the inner
              // scroll view thinks it has not been scrolled.

**Comment by kndl22** [comment] 2020-07-27 19:11
Hi @Piinks,
I tried replacing the CustomScrollView with NestedScrollView and achieved the same result as before. As i mentioned in my comment earlier this is the hierarchy i tried:

- Scaffold
    - AppBar
    - Body - NestedScrollView
        - Headers:
            - 1. SliverPersistentHeader 1(pinned: false)
            - 2. SliverPersistentHeader 2(pinned: true)
        - Body:
               1. Column - Widget 1(contains ListView.builder)

The Column goes behind the 2nd SPH until reaching the AppBar like shown at @VladyslavBondarenko example.
Not sure how SliverOverlap widgets can help in this case

**Comment by Piinks** [comment] 2020-07-27 20:37
I encourage you to check out the documentation on the SliverOverlap widgets:
https://api.flutter.dev/flutter/widgets/SliverOverlapAbsorber-class.html
https://api.flutter.dev/flutter/widgets/SliverOverlapInjector-class.html

Here is a recreation of your reproduction above in a NestedScrollView:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) =>
            <Widget>[
              SliverAppBar(
                pinned: false,
                backgroundColor: Colors.amber,
              ),
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  pinned: true,
                  backgroundColor: Colors.red,
                ),
              ),
            ],
          body:  Builder(
            builder: (BuildContext context) {
              return CustomScrollView(
                slivers: [
                  SliverOverlapInjector(handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context)),
                  SliverToBoxAdapter(child: Placeholder()),
                ],
              );
            }
          )       
        ),
      ),
    );
  }
}
```

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/16964204/88589386-e6968d80-d00d-11ea-8ac5-825843f339d4.gif)


As you can see, the `SliverOverlap*` widgets manage the overlap of the app bar, preventing the body of the `NestedScrollView` from going behind the SPH.

It still appears to me that everything is WAI. Has this solved your issue?

**Comment by kndl22** [comment] 2020-07-27 21:13
Not sure it's demonstrating the behaviour I'm trying to achieve, i'll add some screenshots to clarify:

This is the expanded state:
<img width="427" alt="Screen Shot 2020-07-27 at 23 58 51" src="https://user-images.githubusercontent.com/6260759/88592308-7d8f3400-d066-11ea-8bfe-9e19fbecd877.png">

This is the middle way scrolling:
<img width="436" alt="Screen Shot 2020-07-28 at 0 12 30" src="https://user-images.githubusercontent.com/6260759/88592721-1faf1c00-d067-11ea-8a09-b6692da553c8.png">

This is where the scrollable part goes behind the SilverPersistentHeader:
<img width="447" alt="Screen Shot 2020-07-27 at 23 59 37" src="https://user-images.githubusercontent.com/6260759/88592380-9a2b6c00-d066-11ea-9f91-e2495d1fca20.png">

And this is what I'm trying to achieve (Scrollable part stops right below the SilverPersistentHeader):
<img width="432" alt="Screen Shot 2020-07-27 at 23 59 18" src="https://user-images.githubusercontent.com/6260759/88592437-b16a5980-d066-11ea-955f-de802fc18b9f.png">

**Comment by Piinks** [comment] 2020-07-27 21:15
The answer is to use a NestedScrollView and implement the SliverOverlapAbsorber around the pinned SliverPersistentHeader.

**Comment by kndl22** [comment] 2020-07-27 21:33
That make the body ignore the SPH (I guess that's the expected overlap behaviour - which I'm trying to prevent)
<img width="430" alt="Screen Shot 2020-07-28 at 0 27 08" src="https://user-images.githubusercontent.com/6260759/88594262-9220fb80-d069-11ea-8fe8-553683a97db1.png">

Still bit confused about the SliverOverlapAbsorber so probably I'm missing something

**Comment by Piinks** [comment] 2020-07-28 18:00
> Seems that the SliverToBoxAdapter behave as intended only when it doesn't contain scrollable body.

The SliverToBoxAdapter was only used in the example to reproduce your test case with a Placeholder. If you have a scrollable body, you can use a SliverList instead of a SliverToBoxAdapter?

**Comment by kndl22** [comment] 2020-07-29 10:08
SliverList gives me the same result as the column before - 
![SliverList](https://user-images.githubusercontent.com/6260759/88786840-b0871400-d19b-11ea-9c6c-fd048bc346b2.gif)

My goal is to have the list scrollable behind the "Transactions" header as it happens now, and **also** to have the "Transactions" header pinned below my "Buttons" header:
![SliverList2](https://user-images.githubusercontent.com/6260759/88786978-dad8d180-d19b-11ea-84bc-fd933b063168.gif)

I adjust my layout a little bit and this is a summarise of the hierarchy I'm using:
```
Scaffold(
        appBar: AppBar(),
        body: NestedScrollView(
          physics: ClampingScrollPhysics(),
          headerSliverBuilder:  (BuildContext context, bool innerBoxIsScrolled) {
            return [
              SliverPersistentHeader(
                pinned: false,
                delegate: _SliverAppBarDelegate(
                    child: AccountGraphView()
                ),
              ),
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverPersistentHeader(
                  pinned: true,
                  delegate: _SliverAppBarDelegate(
                    child: Column(
                      children: <Widget>[
                        AccountActionsView(),
                      ],
                    ),
                  ),
                ),
              ),
            ];
          },
          body: Builder(
              builder: (BuildContext context) {
                return CustomScrollView(
                  slivers: [
                    SliverOverlapInjector(handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context)),
                    SliverPersistentHeader(
                      pinned: true,
                      delegate: _SliverAppBarDelegate(
                        child: TransactionsContainer(),
                      ),
                    ),
                    SliverList(
                      delegate: SliverChildBuilderDelegate(
                            (BuildContext context, int index) {
                          return ListTile(
                            title: Text(
                                'Sample Row',
                              style: TextStyle(
                                color: Colors.white
                              ),
                            ),
                          );
                        },
                        childCount: 30,
                      ),
                    )
                  ],
                );
              }
          )        
        ),
      )
```

**Comment by Piinks** [comment] 2020-07-29 18:58
Ah! I think I see what is happening now. You have two separate pinned persistent headers. I think the SliverOverlap* widgets would want to be accounting for both of them here. 
The transactions part is sliding under the buttons part because only the buttons are wrapped in the SliverOverlapAbsorber, which is being injected above the transactions bar. The transactions bar should be in the NestedScrollView.headerSliverBuilder as well, in that SliverOverlapAbsorber.

Rough edit to yours above:
```dart
Scaffold(
        appBar: AppBar(),
        body: NestedScrollView(
          physics: ClampingScrollPhysics(),
          headerSliverBuilder:  (BuildContext context, bool innerBoxIsScrolled) {
            return [
              SliverPersistentHeader(
                pinned: false,
                delegate: _SliverAppBarDelegate(
                    child: AccountGraphView()
                ),
              ),
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  pinned: true,
                  flexibleSpace: _SliverAppBarDelegate(
                    child: Column(
                      children: <Widget>[
                        AccountActionsView(),
                        TransactionsContainer(),
                      ],
                    ),
                  ),
                ),
              ),
            ];
          },
          body: Builder(
              builder: (BuildContext context) {
                return CustomScrollView(
                  slivers: [
                    SliverOverlapInjector(handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context)),
                    SliverList(
                      delegate: SliverChildBuilderDelegate(
                            (BuildContext context, int index) {
                          return ListTile(
                            title: Text(
                                'Sample Row',
                              style: TextStyle(
                                color: Colors.white
                              ),
                            ),
                          );
                        },
                        childCount: 30,
                      ),
                    )
                  ],
                );
              }
          )        
        ),
      )

```

I hope that works! :)

**Comment by kndl22** [comment] 2020-07-31 14:12
@Piinks You're awesome!
A small fix to your suggestion did the trick - SliverApp => SliverPersistentHeader.

The result:
![SliverList](https://user-images.githubusercontent.com/6260759/89027142-aba89880-d332-11ea-9a82-45909b214591.gif)

Since my Buttons layout background is transparent, the SliverList is visible even when scrolled off the Transactions Header. 
Probably changing the background color will solve this.

Thanks for the support!

**Comment by Piinks** [comment] 2020-08-03 18:02
Awesome! I am so glad to hear it worked out. :)
Can I close this issue then?

**Comment by kndl22** [comment] 2020-08-07 14:42
Sure :)

**Closed** 2020-08-10 16:47 UTC
Labels: d: stackoverflow, f: scrolling, found in release: 1.21, framework, has reproducible steps

**Comment by hassanfaour** [comment] 2020-11-02 21:32
@Piinks Hi, what if We are trying to do the same but with ScrollablePositionedList which doesn't have a shrinkwrap, so the  ScrollablePositionedList works but when scrolling it the SliverPersistentHeader don't contract / extend what would you recommend us do.

**Comment by ljx0520** [comment] 2021-04-27 11:02
It doesn't work if i set pinned to 'true' under the first sliver

              SliverPersistentHeader(
                pinned: false,
                delegate: _SliverAppBarDelegate(
                    child: AccountGraphView()
                ),
              ),
