### ISSUE TITLE
My Top App Bar has a incorrect color

### ISSUE THREAD

**Issue by iUnknownWs** [flutter/flutter#108432] opened 2022-07-27 12:25 UTC
My Top App Bar has a incorrect color doesn't concorde with surface color of the theme.

**Expected results: 
![image](https://user-images.githubusercontent.com/109998892/181245825-6d730119-0aea-409d-b95c-4f2f7cde5764.png)
** 

**Actual results: 
![image](https://user-images.githubusercontent.com/109998892/181245954-cb447d11-0c86-477c-bc7d-cd16cb642039.png)
As you can see the navigation bar have the correct color.
** 

</details>

<details>
  <summary>Logs</summary>

```
PS C:\Users\Will\Documents\Flutter\Tesis\tesis> flutter analyze
Analyzing tesis...                                                      
No issues found! (ran in 2.6s)
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1861, on Microsoft Windows [Versi¢n 10.0.22622.436], locale es-VE)
    • Flutter version 3.1.0-0.0.pre.1861 on channel master at C:\Users\Will\Documents\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ca6cecf034 (2 days ago), 2022-07-25 15:23:08 -0700
    • Engine revision 7f8925b1f6
    • Dart version 2.19.0 (build 2.19.0-33.0.dev)
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Will\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32630.194
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[!] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.69.2)
    • VS Code at C:\Users\Will\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Versi¢n 10.0.22622.436]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 102.0.1245.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2022-07-27 12:56
Hi @iUnknownWs, please provide a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by iUnknownWs** [comment] 2022-07-27 21:48
`import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tesis/home.dart';
import 'package:tesis/login.dart';
import 'package:tesis/theme/color_schemes.g.dart';
import 'package:tesis/theme/theme_provider.dart';

void main() {
  runApp(
    ChangeNotifierProvider<ThemeProvider>(
      child: const MyApp(),
      create: (_) => ThemeProvider()..initialize(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(builder: (context, provider, child) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Tesis',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: lightColorScheme,
        ),
        darkTheme: ThemeData(
          useMaterial3: true,
          colorScheme: darkColorScheme,
        ),
        themeMode: provider.themeMode,
        initialRoute: '/',
        routes: {
          '/': (context) => const LoginScreen(),
          '/second': (context) => const Home(),
        },
      );
    });
  }
}
`

`import 'package:flutter/material.dart';
import 'package:tesis/widgets/dialog.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
        backgroundColor: Theme.of(context).colorScheme.surface,
        // backgroundColor: Theme.of(context).colorScheme.surface,
        title: const Text('eShop'),
        centerTitle: true,
        actions: [
          PopupMenuButton(
              position: PopupMenuPosition.under,
              color: Theme.of(context).colorScheme.surface,
              elevation: 2,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4)),
              constraints: const BoxConstraints(
                minWidth: 112,
                maxWidth: 280,
              ),
              iconSize: 30,
              icon: const Icon(Icons.account_circle_outlined),
              itemBuilder: (BuildContext context) => <PopupMenuEntry>[
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        leading: const Icon(Icons.settings),
                        onTap: (() {
                          openDialog(context);
                        }),
                        title: Text(
                          'Configuración',
                          style: TextStyle(
                            color: Theme.of(context).colorScheme.onSurface,
                            fontSize: 14,
                            wordSpacing: 0.1,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ),
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        hoverColor: Theme.of(context).colorScheme.onSurface,
                        tileColor: Theme.of(context).colorScheme.surface,
                        leading: const Icon(Icons.logout_outlined),
                        onTap: (() {
                          Navigator.pushNamed(context, '/');
                        }),
                        title: Text(
                          'Sign Out',
                          style: TextStyle(
                            color: Theme.of(context).colorScheme.onSurface,
                            fontSize: 14,
                            wordSpacing: 0.1,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ),
                  ])
        ],
      ),
      bottomNavigationBar: NavigationBar(
        elevation: 2,
        surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
        labelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
        selectedIndex: index,
        onDestinationSelected: (index) => setState(() => this.index = index),
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.store_outlined),
            selectedIcon: Icon(Icons.store),
            label: 'Tienda',
          ),
          NavigationDestination(
            icon: Icon(Icons.qr_code_scanner_outlined),
            selectedIcon: Icon(Icons.qr_code_scanner),
            label: 'Escaner',
          ),
          NavigationDestination(
            icon: Icon(Icons.shopping_cart_outlined),
            selectedIcon: Icon(Icons.shopping_cart),
            label: 'Carrito',
          ),
        ],
      ),
    );
  }
}
`

**Comment by iUnknownWs** [comment] 2022-07-27 21:51
```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tesis/home.dart';
import 'package:tesis/login.dart';
import 'package:tesis/theme/color_schemes.g.dart';
import 'package:tesis/theme/theme_provider.dart';

void main() {
  runApp(
    ChangeNotifierProvider<ThemeProvider>(
      child: const MyApp(),
      create: (_) => ThemeProvider()..initialize(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(builder: (context, provider, child) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Tesis',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: lightColorScheme,
        ),
        darkTheme: ThemeData(
          useMaterial3: true,
          colorScheme: darkColorScheme,
        ),
        themeMode: provider.themeMode,
        initialRoute: '/',
        routes: {
          '/': (context) => const LoginScreen(),
          '/second': (context) => const Home(),
        },
      );
    });
  }
}

```
```

import 'package:flutter/material.dart';
import 'package:tesis/register_dialog.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({Key? key}) : super(key: key);

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  bool _visibility = true;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Container(
        decoration: const BoxDecoration(
          image: DecorationImage(
            image: AssetImage('images/background.jpg'),
            fit: BoxFit.cover,
          ),
        ),
        child: Center(
          child: Container(
            width: double.infinity,
            height: 447,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              color: Theme.of(context).colorScheme.background,
            ),
            child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  const Text(
                    'Bienvenido',
                    style: TextStyle(
                      fontWeight: FontWeight.w400,
                      fontSize: 36,
                    ),
                  ),
                  const Padding(padding: EdgeInsets.all(4.0)),
                  const Text(
                    'Ingresar',
                    style: TextStyle(
                      fontWeight: FontWeight.w400,
                      fontSize: 24,
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.all(10.0),
                  ),
                  SizedBox(
                    width: 250,
                    child: TextFormField(
                      decoration: const InputDecoration(
                        labelText: 'Usuario',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.person),
                      ),
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.all(4.0),
                  ),
                  SizedBox(
                    width: 250,
                    child: TextFormField(
                      obscureText: _visibility,
                      decoration: InputDecoration(
                        border: const OutlineInputBorder(),
                        prefixIcon: const Icon(Icons.lock),
                        labelText: 'Contraseña',
                        suffixIcon: IconButton(
                            icon: Icon(
                              _visibility
                                  ? Icons.visibility
                                  : Icons.visibility_off,
                            ),
                            onPressed: () {
                              setState(
                                () {
                                  _visibility = !_visibility;
                                },
                              );
                            }),
                      ),
                    ),
                  ),
                  const Padding(
                    padding: EdgeInsets.all(11.0),
                  ),
                  ElevatedButton(
                    style: ButtonStyle(
                      foregroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFFFFFFFF),
                      ),
                      backgroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFF6750A4),
                      ),
                    ),
                    onPressed: () {
                      Navigator.pushNamed(context, '/second');
                    },
                    child: const Text('Iniciar Sección'),
                  ),
                  const Padding(
                    padding: EdgeInsets.all(4.0),
                  ),
                  Row(mainAxisAlignment: MainAxisAlignment.center, children: [
                    const Text('Aún no te has registrado?'),
                    TextButton(
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (BuildContext context) =>
                                const RegisterDialog(),
                            fullscreenDialog: true,
                          ),
                        );
                      },
                      child: const Text(
                        'Registrate',
                        style: TextStyle(
                          color: Color(0xFF6750A4),
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ]),
                ]),
          ),
        ),
      ),
    );
  }
}

```

```
import 'package:flutter/material.dart';
import 'package:tesis/widgets/dialog.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
        backgroundColor: Theme.of(context).colorScheme.surface,
        // backgroundColor: Theme.of(context).colorScheme.surface,
        title: const Text('eShop'),
        centerTitle: true,
        actions: [
          PopupMenuButton(
              position: PopupMenuPosition.under,
              color: Theme.of(context).colorScheme.surface,
              elevation: 2,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4)),
              constraints: const BoxConstraints(
                minWidth: 112,
                maxWidth: 280,
              ),
              iconSize: 30,
              icon: const Icon(Icons.account_circle_outlined),
              itemBuilder: (BuildContext context) => <PopupMenuEntry>[
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        leading: const Icon(Icons.settings),
                        onTap: (() {
                          openDialog(context);
                        }),
                        title: Text(
                          'Configuración',
                          style: TextStyle(
                            color: Theme.of(context).colorScheme.onSurface,
                            fontSize: 14,
                            wordSpacing: 0.1,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ),
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        hoverColor: Theme.of(context).colorScheme.onSurface,
                        tileColor: Theme.of(context).colorScheme.surface,
                        leading: const Icon(Icons.logout_outlined),
                        onTap: (() {
                          Navigator.pushNamed(context, '/');
                        }),
                        title: Text(
                          'Sign Out',
                          style: TextStyle(
                            color: Theme.of(context).colorScheme.onSurface,
                            fontSize: 14,
                            wordSpacing: 0.1,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ),
                  ])
        ],
      ),
      bottomNavigationBar: NavigationBar(
        elevation: 2,
        surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
        labelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
        selectedIndex: index,
        onDestinationSelected: (index) => setState(() => this.index = index),
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.store_outlined),
            selectedIcon: Icon(Icons.store),
            label: 'Tienda',
          ),
          NavigationDestination(
            icon: Icon(Icons.qr_code_scanner_outlined),
            selectedIcon: Icon(Icons.qr_code_scanner),
            label: 'Escaner',
          ),
          NavigationDestination(
            icon: Icon(Icons.shopping_cart_outlined),
            selectedIcon: Icon(Icons.shopping_cart),
            label: 'Carrito',
          ),
        ],
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment] 2022-07-28 07:25
Hi @iUnknownWs, please provide the colorSchemes that you are using. 

As a side note, we do not need the code for your LoginPage, et al.

Please try to provide only the relevant code required to reproduce the issue without any third-party packages/dependencies. 

Thank you

**Comment by iUnknownWs** [comment] 2022-07-28 07:32
```
import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  surfaceTint: Color(0xFF6750A4),
  onErrorContainer: Color(0xFF410E0B),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFF9DEDC),
  onTertiaryContainer: Color(0xFF31111D),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFD8E4),
  tertiary: Color(0xFF7D5260),
  shadow: Color(0xFF000000),
  error: Color(0xFFB3261E),
  outline: Color(0xFF79747E),
  onBackground: Color(0xFF1C1B1F),
  background: Color(0xFFFFFBFE),
  onInverseSurface: Color(0xFFF4EFF4),
  inverseSurface: Color(0xFF313033),
  onSurfaceVariant: Color(0xFF49454F),
  onSurface: Color(0xFF1C1B1F),
  surfaceVariant: Color(0xFFE7E0EC),
  surface: Color(0xFFFFFBFE),
  onSecondaryContainer: Color(0xFF1D192B),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE8DEF8),
  secondary: Color(0xFF625B71),
  inversePrimary: Color(0xFFD0BCFF),
  onPrimaryContainer: Color(0xFF21005D),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFEADDFF),
  primary: Color(0xFF6750A4),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  surfaceTint: Color(0xFFD0BCFF),
  onErrorContainer: Color(0xFFF2B8B5),
  onError: Color(0xFF601410),
  errorContainer: Color(0xFF8C1D18),
  onTertiaryContainer: Color(0xFFFFD8E4),
  onTertiary: Color(0xFF492532),
  tertiaryContainer: Color(0xFF633B48),
  tertiary: Color(0xFFEFB8C8),
  shadow: Color(0xFF000000),
  error: Color(0xFFF2B8B5),
  outline: Color(0xFF938F99),
  onBackground: Color(0xFFE6E1E5),
  background: Color(0xFF1C1B1F),
  onInverseSurface: Color(0xFF313033),
  inverseSurface: Color(0xFFE6E1E5),
  onSurfaceVariant: Color(0xFFCAC4D0),
  onSurface: Color(0xFFE6E1E5),
  surfaceVariant: Color(0xFF49454F),
  surface: Color(0xFF1C1B1F),
  onSecondaryContainer: Color(0xFFE8DEF8),
  onSecondary: Color(0xFF332D41),
  secondaryContainer: Color(0xFF4A4458),
  secondary: Color(0xFFCCC2DC),
  inversePrimary: Color(0xFF6750A4),
  onPrimaryContainer: Color(0xFFEADDFF),
  onPrimary: Color(0xFF381E72),
  primaryContainer: Color(0xFF4F378B),
  primary: Color(0xFFD0BCFF),
);

```

**Comment by danagbemava-nc** [comment] 2022-07-28 07:57
Hi @iUnknownWs, from what I see, your code is working as intended. 
You have set an elevation of 0 for the `AppBar` which is why your `surfaceTintColor` is not visible. If you set it to any value other than 0, you should start seeing the overlay. The higher the value for elevation, the more visible the overlay is. See the screenshots below. 

<details>
<summary>screenshots</summary>

| elevation: 0 | elevation: 2 | elevation: 4 | 
| -- | -- | -- |
| <img width="726" alt="Screenshot 2022-07-28 at 07 53 59" src="https://user-images.githubusercontent.com/88313112/181452334-60167427-a894-4921-accf-d43b02c45f6b.png"> | <img width="726" alt="Screenshot 2022-07-28 at 07 54 06" src="https://user-images.githubusercontent.com/88313112/181452362-31611b8b-67a4-4cda-8543-1dbeaa8a8112.png"> | <img width="726" alt="Screenshot 2022-07-28 at 07 54 32" src="https://user-images.githubusercontent.com/88313112/181452367-486a1914-168c-409b-8d97-2f2b18b3ce53.png"> |

</details>

I'll be closing this as it is working as intended. 

Thank you

**Closed by danagbemava-nc** 2022-07-28 07:57 UTC
Labels: in triage
