### ISSUE TITLE
build ios framework command pass dart-define param in wrong format

### ISSUE THREAD

**Issue by zhao0** [flutter/flutter#81523] opened 2021-04-30 02:18 UTC
# flutter doctor
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.0)
[✓] Connected device (2 available)
```

# What I do
I want to have build-time environment variables available to code within a Flutter app. From the [docs](https://dartcode.org/docs/using-dart-define-in-flutter/), we found that dart-define may work and I pass it to the build command like this
```
flutter build ios-framework --dart-define=foo=bar --dart-define=foo1=bar1 --verbose
```
from the verbose log, I found dart-define parameters were in wrong format.

```console
[  +39 ms] Building frameworks for com.xxx.xxxAppFlutter in debug mode...
[ +117 ms]  ├─Copying Flutter.xcframework...
[ +302 ms]  ├─Copying Flutter.xcframework... (completed in 280ms)
[   +4 ms]  ├─Building App.xcframework...
[   +4 ms] executing: xcrun --sdk iphoneos --show-sdk-path
[  +17 ms]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3
.sdk
[   +7 ms] Initializing file store
[  +52 ms] debug_unpack_ios: Starting due to {InvalidatedReason.inputChanged}
[ +287 ms] Skipping target: gen_localizations
[   +2 ms] debug_unpack_ios: Complete
[ +396 ms] kernel_snapshot: Starting due to {}
[  +13 ms] /Users/xxx/tools/v2.0/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/xxx/tools/v2.0/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot
--sdk-root /Users/xxx/tools/v2.0/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter --no-print-incremental-dependencies -D["foo=bar" -D"foo1=bar1"]
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--no-link-platform --packages
/Users/xxx/code/xxx-app-flutter/xxx_app_flutter/.dart_tool/package_config.json --output-dill
/Users/xxx/code/xxx-app-flutter/xxx_app_flutter/.dart_tool/flutter_build/4f66147a7da72fe6892
6db40d5867fb8/app.dill --depfile
/Users/xxx/code/xxx-app-flutter/xxx_app_flutter/.dart_tool/flutter_build/4f66147a7da72fe6892
6db40d5867fb8/kernel_snapshot.d package:xxx_app_flutter/main.dart
```

`-D["foo=bar" -D"foo1=bar1"]` should be `-Dfoo=bar -Dfoo1=bar1`

**Comment by TahaTesser** [comment] 2021-04-30 14:00
Hi @zhao0 
Thanks for filing the issue, it's a duplicate of https://github.com/flutter/flutter/issues/76672

I tried to reproduce the issue on the `stable`, tested on add2app, the passed param never shows up, however, this seems to be fixed in later channels 

### Steps to reproduce 
1. `git clone https://github.com/flutter/samples.git`
2. Modify `amples/tree/master/add_to_app/prebuilt_module/flutter_module`add following lines in the code in the column
```dart
             Text(const String.fromEnvironment('MY_VAR')),
             Text(const String.fromEnvironment('MY_OTHER_VAR')),
```
3. Build framework
`flutter build ios-framework --dart-define=MY_VAR=MY_VALUE --dart-define=MY_OTHER_VAR=MY_OTHER_VALUE  --no-universal --output=../ios_using_prebuilt_module/Flutter/`

4. Launch the native iOS app `ios_using_prebuilt_module`

### Preview
| `Channel stable, 2.0.5` | `beta`, `dev`, `master`  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/116705509-470b8e80-a9d5-11eb-9804-c822e26c4cd2.PNG" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/116705516-47a42500-a9d5-11eb-88d2-c871d89661d7.PNG" height="450" /> |


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.5
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```
		
</details>

Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Closing as duplicate of https://github.com/flutter/flutter/issues/76672

**Closed by TahaTesser** 2021-04-30 14:00 UTC
Labels: in triage

**Comment by zhao0** [comment] 2021-05-06 03:20
@tadaspetra Thanks! It was fixed in beta channel.
