### ISSUE TITLE
Gesture callback executed with a delay of 4 seconds

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#25320] opened 2018-12-13 10:33 UTC
Hi, I am not sure if the word `responsive` in the title is correct or not. I have the following code

```dart
TextSpan(
    text: 'Click me', 
    style: TextStyle(color: Colors.blue[600]),
    recognizer: TapGestureRecognizer()..onTap = () { print('clicked'); },
),
```

This is inside a `StatelessWidget`. When I tap the `Click me` on my device, it's not always tapped successfully. 

I tapped 10 times at the beginning, only 7 lines are printed.
I tapped 10 times again, only 3 lines are printed.
I tapped 10 times again, only 4 lines are printed. 

Is this expected? 

```shell
$ flutter doctor
[✓] Flutter (Channel master, v1.0.1-pre.3, on Mac OS X 10.13.6 17G65, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2018-12-13 10:39
Did you test on different devices?

**Comment by sgon00** [comment] 2018-12-13 11:00
@zoechi sorry, no, I didn't test this on different devices. I only tested it on Android 8.1.0. You can try this on an android device to see if it's reproducible or not.

**Comment by sgon00** [comment] 2018-12-13 11:06
@zoechi hi, maybe I should change the title. It not only happens in TextSpan recognizer, I just tried a InkWell widget. It has the same "problem". I never really pay attention on this responsive behavior for all tappable widgets. To make sure the tap function code is executed, I have to wait for 4 seconds between two tap actions. If the interval between two taps are less than 4 seconds, the tap function may not be executed. I never really realized this before. Is this an expected behavior?

**Comment by jason-simmons** [comment] 2018-12-14 20:30
I played with this on a Nexus 5X but didn't notice anything unusual.

Try adding some logs to `RenderParagraph.handleEvent` inside `lib/src/rendering/paragraph.dart` within the Flutter framework.  `handleEvent` will receive the pointer events that are sent to the `TextSpan`.  Possibly some of these events aren't reaching the intended widget, or perhaps the `TapGestureRecognizer` isn't considering the event sequence to be a tap.

**Comment by zoechi** [comment] 2018-12-16 13:56
> Possibly some of these events aren't reaching the intended widget

Sounds like we would need a complete but minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-01-14 08:48
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-14 08:48 UTC
Labels: engine, f: gestures, framework, waiting for customer response
