### ISSUE TITLE
[video_player] [iOS] Audio is overlapping intermittently for multiple videos

### ISSUE THREAD

**Issue by reverie-ss** [flutter/flutter#71280] opened 2020-11-26 15:13 UTC
## Description
The app has multiple videos in a page, however there is only one `VideoPlayerController` to control the videos.
Whenever one video is played and moved to next, the audio is overlapping.
This happens only on iOS. In android, it works fine.
_This issue occurs intermittently._
## Steps to Reproduce
`VideoPlayerController _controller;`
1. Play a video using `_controller.play()`
2. Change video using `_controller = VideoPlayerController.network(url);`
3. And play the new video using `_controller.play()`

**Expected results:** 
Stop the former video and play the current one
**Actual results:**
The current one is playing and the former one audio is overlapping.
Video is playing only for current one but the audio is playing for the former one.
<details>
  <summary>Logs</summary>
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.22.2 at /Users/niteshpundra/Documents/flutter
    • Framework revision 84f3d28555 (6 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niteshpundra/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G935V (mobile) • a7821b10 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
</details>

**Comment by darshankawar** [comment] 2020-11-27 06:50
@reverie-ss 
Please provide a complete minimal reproducible code sample. Also I see that you are on stable 1.22.2, while the current stable is 1.22.4. You may try to upgrade to latest and check again if issue persists.
Thanks.

**Comment by cavedweller** [comment] 2020-11-27 14:20
I have the same issue. 

**Description** 
I am using gridview populated with a combination of images and videos (similar to what Instagram looks like when you selecting media to post)

**Issue**
click onto video, then click onto an image the audio from the video is still playing, the audio doesn't stop until the end of the video, i can click onto every image but the video doesn't dispose

**Code Snippet**

This determines what type of file is clicked

`       file = await mediaList[index].file;
        assetType = mediaList[index].type.toString();
        setState(() {
          if (assetType == 'AssetType.video') {
            _videoController = VideoPlayerController.file(file);
            _videoController.setLooping(true);
            _videoController.setVolume(100);
            _videoController.play();
            _initializeVideoPlayerFuture = _videoController.initialize();
          }
        });`

This displays the video 

`    FutureBuilder(
     future: _initializeVideoPlayerFuture,
     builder: (context, snapshot) {
     if (snapshot.connectionState ==ConnectionState.done) {
     return GestureDetector(
     onTap: () {
     setState(() {
     if (_videoController .value.isPlaying) {                                                  
    _videoController .pause();
     } else {
      _videoController.play();
     }});},`

` void dispose() {
 _videoController.dispose();
}`

logs
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18362.356], locale en-ZA)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

I am not sure if I've missed anything

**Comment by pedromassangocode** [comment] 2020-12-18 10:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-18 10:53 UTC
Labels: in triage, waiting for customer response
