### ISSUE TITLE
Would like a way to specify minimum version of Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4111] opened 2016-05-23 19:21 UTC
Presumably in the pubspec.yaml?

@collinjackson has been seeing issues with codelab users who get strange errors trying to do the codelab with an old version of flutter.  He'd like to be able to make it so the tools would complain somehow.

We discussed previously putting something extra in the pubspec.yaml for a version for flutter?  That said, I'm not sure we have a version for flutter (other than the git hash) that we're currently rolling?

**Comment by sethladd** [comment] 2016-05-23 19:47
cc @munificent @nex3 @kevmoo

**Comment by sethladd** [comment] 2016-07-19 22:38
Curious, what is specifying this? The flutter application itself?

I think the work @nex3 is doing allows us to specify a minimum version of Flutter in the pubspec.yaml

**Comment by Hixie** [comment] 2017-01-30 03:04
dupe of https://github.com/flutter/flutter/issues/3696

**Closed by Hixie** 2017-01-30 03:04 UTC
Labels: dev: tool, new feature, prod: framework
