### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for D:\Android flutter projects(OpenSource)\countdowntimer\android\gradlew.bat.

### ISSUE THREAD

**Issue by developeranshulsaboo** [flutter/flutter#70298] opened 2020-11-11 16:00 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for D:\Android flutter projects(OpenSource)\countdowntimer\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:630:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:524:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:630:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      buildGradleApp (package:flutter_tools/src/android/gradle.dart:391:43)
#8      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:101:13)
#9      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:567:28)
<asynchronous suspension>
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:591:33)
<asynchronous suspension>
#11     HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.194, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
    • Flutter version 1.24.0-8.0.pre.194 at D:\SOFTWARES\flutter
    • Framework revision 018467cdb1 (9 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\anshu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at D:\SOFTWARES\Visual Studio
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.17763.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 4.0)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • RMX1831 (mobile)  • WWEIFM5HT4FQBE5P • android-arm64 • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.18362.1139]

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8874f21e79d7ec66d0457c7ab338348e31b17f1d

**Comment by darshankawar** [comment] 2020-11-12 06:04
Closing this as duplicate of [56975](https://github.com/flutter/flutter/issues/56975)

**Closed by darshankawar** 2020-11-12 06:04 UTC
