### ISSUE TITLE
flutter doctor ,  Android studio ,(the doctor check crash)

### ISSUE THREAD

**Issue by seneargroup** [flutter/flutter#87219] opened 2021-07-28 20:06 UTC
## Steps to Reproduce

1. ...[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
 
2. ...   X FileSystemException: Exists failed, path = ''c:\program.plugins' (OS Error: The filename, directory name, or
      volume label syntax is incorrect.
      , errno = 123)
3. ...

## Logs

<details> 
<summary>flutter doctor</summary> 
	
```console
Microsoft Windows [Version 10.0.19043.1110]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hp>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''c:\program.plugins' (OS Error: The filename, directory name, or
      volume label syntax is incorrect.
      , errno = 123)
[√] VS Code (version 1.58.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.


C:\Users\hp>
```

</details>

**Comment by TahaTesser** [comment] 2021-07-29 07:55
Hi @seneargroup 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83195
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-29 07:55 UTC
Labels: in triage
