### ISSUE TITLE
FlexibleSpace in AppBar covers action/back button splash/highlight

### ISSUE THREAD

**Issue by kamilez** [flutter/flutter#14202] opened 2018-01-21 13:38 UTC
## Steps to Reproduce

Create AppBar and insert Container with some color into the flexibleSpace. See that the container covers the splash and highlight effect on the back button. If you give a container's color opacity, the highlight becomes visible.

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/kamil/Flutter
    • Framework revision 8f65fec5f5 (6 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/kamil/Programs/Android/
    • Android NDK at /home/kamil/Programs/Android/ndk-bundle
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/kamil/Programs/Android/
    • Java binary at: /home/kamil/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/kamil/Programs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • SM A320FL                 • 5203d96964e7c395 • android-arm • Android 7.0 (API 24) (emulator)
    • Android SDK built for x86 • emulator-5554    • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by Hixie** [comment] 2018-01-22 02:59
Use an Ink widget instead of Container. See the discussion in the documentation for Ink for details. Is there somewhereI should have mentioned this in the docs that I missed?

**Comment by kamilez** [comment] 2018-01-22 18:38
Which of the Ink widgets are you talking about? All of them seems to respond on user touch and I wan't a static gradient background without it. As a reference I am watching on the flutter gallery app and what I see is that on the home screen SilverAppBar menu button does not highlight or splash. In "Contact profile" view none of the bar's icons splash, neither back button in Animation view. That's why I assumed it is a bug.

**Comment by Hixie** [comment] 2018-01-22 21:28
I mean literally the widget called "Ink", though I notice now that you're on alpha and we haven't yet rolled Ink to alpha.

**Comment by kamilez** [comment] 2018-01-23 20:17
The Ink widget works fine. Might be closed I think.

**Comment by ianldgs** [comment] 2018-04-15 00:04
@Hixie the gallery app has this behavior on `Home` and on `ContactsDemo`. `IconButton`s don't ripple. Is there a workarround?

**Comment by Hixie** [comment] 2018-05-01 17:31
@ianldgs Does the Ink widget not work for you?

cc @HansMuller to investigate gallery issues reported above.

**Comment by ianldgs** [comment] 2018-05-02 12:52
@Hixie nope. 

I'm actually using a SliverAppBar, so I think its a different case of @kamilez.
The solution might be wrap the actions inside the `AppBar` widget with a new `Material`.

I tried to put the `Ink` arround the background of my `FlexibleSpaceBar`, but it didn't work. Also tried using a `Stack` with a `Material` on top of the background, but no success either.

**Comment by Hixie** [comment] 2018-05-03 00:13
@ianldgs Ok sounds like you're hitting a different problem. I recommend filing a new issue with code showing the problem you're running into.

**Comment by zoechi** [comment] 2018-07-26 17:17
Kept open for https://github.com/flutter/flutter/issues/14202#issuecomment-359521866

**Comment by Hixie** [comment] 2018-07-26 17:38
@kamilez I mean literally the widget named "Ink".

**Comment by YoussefKababe** [comment] 2018-09-12 03:06
@ianldgs @zoechi Had similar issues with my `SliverAppBar`. Was using a `Container` inside the `flexibleSpace` to have a linear gradient as background for the app bar, but it was covering the `TabBar` buttons splash. Here's what I ended up doing and it works!

```dart
flexibleSpace: Ink(
  child: Container(),
  decoration: BoxDecoration(
    gradient: LinearGradient(
      begin: Alignment(-1.5, -2.5),
      end: Alignment(1.5, 2.5),
      colors: [Colors.pink, Colors.purple[600]],
    ),
  ),
),
```

The `Ink` widget requires the `child` property to be set to a widget that will take the whole available space, otherwise build will just fail.

**Comment by kolja-esders** [comment] 2018-12-25 01:51
This does not seem to be solved at this point. As @ianldgs already pointed out, you can observe the issue by taking a look at the current behavior of the Contacts example in the Gallery app. Neither the actions nor the leading icon generate a splash effect on tap when the background image is fully visible.

When the user scrolls until the `SliverAppBar` is collapsed and the blue background is shown, the splash will be visible on tap.

Is this intended behavior? If so, what would be the best way to show a splash on tap? Wrapping the `flexibleSpace` with a `Material` for example does not work.

**Comment by iapicca** [comment] 2019-11-01 14:25
Hi @kamilez 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 14:25 UTC
Labels: a: quality, team, team: gallery
