### ISSUE TITLE
Feature request: get all photos from storage.

### ISSUE THREAD

**Issue by lixiaoyan** [flutter/flutter#14098] opened 2018-01-14 14:29 UTC
https://facebook.github.io/react-native/docs/cameraroll.html#getphotos

**Comment by zoechi** [comment] 2019-01-08 15:50
#13124 might cover this

**Comment by cyanglaz** [comment] 2019-04-26 00:18
related to https://github.com/flutter/flutter/issues/19563

**Comment by Loopex2019** [comment] 2019-07-18 10:02
Look there is a Plugin called Storage_Path in Pub.dev : [https://pub.dev/packages/storage_path](url)
You can try this Plugin and it will give you not only images , it will give you videos , audio and files (like PDF) too. The downside is that it is only available for Android . But i opened an issue on the plugin to get 
it available on ios too. you can check it too : [https://github.com/follow2vivek/StoragePath/issues/1](url).
I hope this might help.

**Comment by Loopex2019** [comment] 2019-07-18 12:56
If you want an alternative to the last Solution , you can use the Directory Object from the 
`dart:io` Library and then add a Path to the Directory Object . Here your Path should point 
at your images. NOTE : All of your images and Videos are stored in the DCIM Folder . This Folder 
stores your Gallery images and videos . So by pointing to the Path , here is an Example : 
`Directory(“storage/emulated/0/DCIM”).listSync()` . The `listSync()` Method returns the sub directories and paths of the DCIM , which gets the Images and Videos , you can add the 
`reclusive :` named Argument and set it to `true` , this is displaying the list in a reversed way .
This Path is working for Android. You can search on the web to get the iOS Path , it’s so easy to
find it . If you want to get a specific File Type like Images , you can point to it in your Path . I 
added this Solution because this can work for both : iOS And Android. And I think this is a more 
flexible way . I hope this might help too.

**Comment by cyanglaz** [comment] 2019-08-02 22:50
duplicate of https://github.com/flutter/flutter/issues/16054 closing this issue.

**Closed by cyanglaz** 2019-08-02 22:50 UTC
Labels: p: image_picker, plugin, severe: new feature
