### ISSUE TITLE
Flutter&Firestore sum of the list amaount

### ISSUE THREAD

**Issue by hisakazu-matsuo** [flutter/flutter#60878] opened 2020-07-06 02:50 UTC
I try to make the application of StockControl of Parts.
I made the Listview of the Parts qty on the screen, as below,
20 pcs
50 pcs
100 pcs

I want to show the total of them.(170pcs)
I try to add the program as follows,
but Flutter say error "type 'String' is not a subtype of type 'DocumentSnapshot'
Please adovice me how can I solve this problem.
Thank you.
------------------------------------------------------------------
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CalcIlistScreen extends StatefulWidget {
  final index2;
  final index4;

  CalcIlistScreen({@required this.index2, this.index4});

  @override
  createState() => _CalcIlistScreenState();
}

class _CalcIlistScreenState extends State<CalcIlistScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("List of Input"),
        centerTitle: true,
        backgroundColor: Colors.blueAccent,
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: StreamBuilder<QuerySnapshot>(
            stream: Firestore.instance
                .collection("stock-control")
                .where("parts-code",
                    isEqualTo: widget.index4) //index4 is parts code number
                .where("category", isEqualTo: "Input")
                .where("date", isGreaterThan: widget.index2) //index2 is date
                .orderBy("date", descending: true)
                .snapshots(),
            builder:
                (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
              if (!snapshot.hasData) return const Text("Loading...");
              return ListView(
                children:
                    snapshot.data.documents.map((DocumentSnapshot document) {

//                      var sum = snapshot.data.documents                                      //add the program
//                          .reduce((curr, next) => curr["qty"] + next["qty"]);               //add the program
//                      print(sum);                                                                               //add the program

                  return ListTile(
                    title: Text(document["qty"]),
                  );
                }).toList(),
              );
            }),
      ),
    );
  }
}
-------------------------------------------------------------------------------------

**Comment by iapicca** [comment] 2020-07-06 06:25
Hi @hisakazu-matsuo 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-06 06:25 UTC

**Comment by hisakazu-matsuo** [comment] 2020-07-06 07:19
Thank you for your quickly response.
I checked my flutter doctor, flutter run & pubspec.yaml everything goes well.
What should I do next?
