### ISSUE TITLE
Text does not render correctly on canvaskit

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#100221] opened 2022-03-16 15:06 UTC
We have created the widget to render the text with it width, but it was not rendered correctly on Chinese and some of the languages other than English. because initially the Chinese letters shown like Emoji's after that it was rendered Chinese letters. So Calculated text width was not appropriate

## Steps to Reproduce

1. Run the sample code added below
2. It shows the issue of the text rendering because the width returns 63 but the text needs 93.
3. After that hot reload renders the text correctly

**Expected results:** 

- Text initially rendered correctly on canvas kit

**Actual results:** 

- Text initially does not rendered correctly on canvas kit

<details>
<summary>Code sample</summary>

```dart

Container(
                color: Colors.red,
                height: 100,
                width: _getTextWidgetWidth(
                    '2022 年 3 月', 100, 1000, context, style: TextStyle(
                  fontSize: 15,
                )).width,
                child:
                Text('2022 年 3 月', style: TextStyle(
                  fontSize: 15,
                ),)
                )

Size _getTextWidgetWidth(
    String text, double height, double width, BuildContext context,
    {TextStyle? style}) {
  final Widget richTextWidget = Text(
    text,
    style: style,
    maxLines: 1,
    softWrap: false,
    textDirection: TextDirection.ltr,
    textAlign: TextAlign.left,
  ).build(context);

  RenderParagraph? renderObject;
  if (richTextWidget is! RichText) {
    assert(richTextWidget is RichText);
  } else {
    renderObject = richTextWidget.createRenderObject(context);
  }
  renderObject!.layout(BoxConstraints(
    minWidth: width,
    maxWidth: width,
    minHeight: height,
    maxHeight: height,
  ));

  final List<TextBox> textBox = renderObject.getBoxesForSelection(
      TextSelection(baseOffset: 0, extentOffset: text.length));
  double textWidth = 0;
  double textHeight = 0;
  for (final TextBox box in textBox) {
    textWidth += box.right - box.left;
    final double currentBoxHeight = box.bottom - box.top;
    textHeight = textHeight > currentBoxHeight ? textHeight : currentBoxHeight;
  }

  return Size(textWidth + 10, textHeight + 10);
}

```

</details>

**Ref:**

**Initial text width calculation calculate the text on below**
![Screen Shot 2022-03-16 at 8 35 24 PM](https://user-images.githubusercontent.com/44917578/158621873-795ce255-e0c2-4e9b-9c5f-32adacd6c615.png)

**But renders the text as below**
![Screen Shot 2022-03-16 at 8 35 30 PM](https://user-images.githubusercontent.com/44917578/158621940-192e9da1-a02c-4502-ac41-0d0c10247e5a.png)

**Comment by darshankawar** [comment] 2022-03-17 07:03
Closing this as duplicate of https://github.com/flutter/flutter/issues/77023

**Closed by darshankawar** 2022-03-17 07:03 UTC
Labels: in triage
