### ISSUE TITLE
The application has a green screen problem I don't know what happened

### ISSUE THREAD

**Issue by gulceselim** [flutter/flutter#108806] opened 2022-08-02 12:01 UTC
## Steps to Reproduce

Hi. Some users have a problem in the flutter app. They are using ios operation system. 

You can see the problem in the picture below.

**Expected results:**
On the page, this is not supposed to be the green stuff.

**Actual results:**
<img width="321" alt="Screen Shot 2022-08-02 at 14 57 19" src="https://user-images.githubusercontent.com/43720773/182369671-d28b0576-908a-4555-8f53-c9464726be34.png">

<details>
<summary>Code sample</summary>
</details>

<details>
  <summary>Logs</summary>
</details>

**Comment by exaby73** [comment] 2022-08-02 12:11
Hi @gulceselim, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by gulceselim** [comment] 2022-08-02 12:17
I really don't know why this is happening 

[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5 21G72 darwin-arm, locale en-TR)
    • Flutter version 3.0.3 at /Users/gulceselim/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (6 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/gulceselim/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Selim (mobile)  • 2ffd9bf5835bc3ae605a3fc87ee2b29f2d7a50a7 • ios            • iOS 15.2.1 19C63
    • macOS (desktop) • macos                                    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment] 2022-08-02 12:40
Can you provide some information on the screen this is appearing on? For example, what should the page look like, and if you're using any platform views like Google Maps for WebViews on it? If you have any user reports or analytics of what the user was doing before this occurred, please share that as well. Thank you

**Comment by gulceselim** [comment] 2022-08-02 13:00
I am using the Image.asset widget.

Unfortunately, I do not have any user's report available but I found an issue like this, let me share it with you.

https://github.com/flutter/flutter/issues/52092

**Comment by exaby73** [comment] 2022-08-02 13:30
Okay, thank you for the information. In #52092's case, it looks like an asset problem. In your case, it also might me an asset problem but why I am not closing this issue immediately is cause it seems like it only happens on some devices. I'll label this issue for some insights from the team.

**Comment by gulceselim** [comment] 2022-08-02 13:33
Okay, thank you

**Comment by zanderso** [comment] 2022-08-08 18:16
We need more information in order for this issue to be actionable. For example, is it possible to get access to the specific asset and sample app that uses them where this issue reproduces?

**Closed** 2022-08-29 19:09 UTC
Labels: platform-ios, engine, severe: rendering, a: production, r: timeout
