### ISSUE TITLE
[Android Studio][Inspector] The font size of the inspector panel is too big.

### ISSUE THREAD

**Issue by VyMajoris** [flutter/flutter#71323] opened 2020-11-27 18:42 UTC
I feel like the new(ish) inspector panel is too has everything too big and with excessive padding. It feels like it was designed for a mobile application.

I would like to see it more like the rest of Android Studio, or like the older version.

![image](https://user-images.githubusercontent.com/4342296/100477393-f4951180-30c6-11eb-9f09-179fc0bd9c99.png)

**Comment by pedromassangocode** [comment] 2020-11-30 11:18
Hi @VyMajoris
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-30 11:18 UTC
Labels: team: infra
