### ISSUE TITLE
Disable color animation for AnimatedContainer while playing Theme brightness switch animation

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#115828] opened 2022-11-22 12:41 UTC
![ExLoader_coJPKZBNVk](https://user-images.githubusercontent.com/63228361/203313803-96ac827b-1bfa-42af-8934-06ebe0642e1c.gif)

![test_window2_X2ENLe1mBD](https://user-images.githubusercontent.com/63228361/203316376-9768bb89-7b98-4ead-acf1-d8b905ec4c52.gif)

Left widget is an AnimatedContainer, right widget is an ordinary Container.

If you use theme-dependent color inside of an AnimatedContainer and update app's brightness to the opposite one then it will enlarge theme's brightness switch animation duration.

If it's an issue it should be fixed, **if it's working as intended then my suggestion is to disable color switch animation for AnimatedContainer widget while changing app's brightness**. 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

ValueNotifier<ThemeData> _theme = ValueNotifier(
  ThemeData(brightness: Brightness.dark, backgroundColor: Colors.white),
);

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeData>(
      valueListenable: _theme,
      builder: (_, theme, __) => MaterialApp(
        theme: theme,
        title: 'Material App',
        home: _Scaffold(),
      ),
    );
  }
}

class _Scaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
        backgroundColor: Theme.of(context).backgroundColor,
      ),
      backgroundColor: Colors.red,
      body: Center(
        child: Column(
          children: <Widget>[
            Row(
              children: <Widget>[
                AnimatedContainer(
                  curve: Curves.easeInOutCubic,
                  duration: const Duration(milliseconds: 175),
                  color: Theme.of(context).backgroundColor,
                  width: 50.0,
                  height: 50.0,
                  margin: const EdgeInsets.all(10.0),
                ),
                Container(
                  color: Theme.of(context).backgroundColor,
                  width: 50.0,
                  height: 50.0,
                ),
              ],
            ),
            ElevatedButton(
              onPressed: () {
                final Brightness newBrightness =
                    _theme.value.brightness == Brightness.dark
                        ? Brightness.light
                        : Brightness.dark;
                _theme.value = _theme.value.copyWith(
                  brightness: newBrightness,
                  backgroundColor: newBrightness == Brightness.dark
                      ? Colors.white
                      : Colors.black,
                );
              },
              child: const Text('switch brightness'),
            ),
          ],
        ),
      ),
    );
  }
}
```

Flutter version: 3.3.8 from stable channel

**Comment by exaby73** [comment] 2022-11-23 09:04
Hello @kirill-21. I am not sure I follow. What is the exact issue here, could you please elaborate?

**Comment by kirill-21** [comment] 2022-11-23 09:15
> Hello @kirill-21. I am not sure I follow. What is the exact issue here, could you please elaborate?

Theme switch animation is delayed for animated container widget and then extended for animated container's duration. All other widgets are animated at the same time

**Comment by exaby73** [comment] 2022-11-23 12:01
Setting the `duration` of the `AnimatedContainer` to `Duration.zero` works. This is working as intended as the animation starts late because you have the duration set to a higher value.

Since this is working as intended, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.

**Closed** 2022-11-23 12:01 UTC
Labels: r: invalid, in triage
