### ISSUE TITLE
Application content is smaller then a window content after resizing (Windows)

### ISSUE THREAD

**Issue by rootext** [flutter/flutter#59782] opened 2020-06-18 18:00 UTC
## Steps to Reproduce

1. Run `flutter config --enable-windows-desktop`
2. Create a flutter project and run on windows device
3. Resize a window

**Expected results:** 
No visual artifacts
**Actual results:** 
Application content is smaller than a window content. 
There are black lines on right and bottom side.
Application content is distorted.
![image](https://user-images.githubusercontent.com/1571180/85055441-8dfce680-b16b-11ea-8701-3624b654b284.png)

Notes: Minimizing/maximizing a window fixes the issue.

**Comment by stuartmorgan** [comment] 2020-06-18 20:14
Duplicate of https://github.com/flutter/flutter/issues/40068

**Closed by stuartmorgan** 2020-06-18 20:14 UTC
