### ISSUE TITLE
DecorationImage.onError is not called when loading invalid images

### ISSUE THREAD

**Issue by jibiel** [flutter/flutter#78925] opened 2021-03-24 01:29 UTC
## Steps to Reproduce

1. Copy the example from the docs:

https://github.com/flutter/flutter/blob/6b2283469949b224cb6f44e10c0529114569f5c4/packages/flutter/lib/src/widgets/image.dart#L858-L891

```dart
Widget build(BuildContext context) {
  return DecoratedBox(
    decoration: BoxDecoration(
      color: Colors.white,
      border: Border.all(),
      borderRadius: BorderRadius.circular(20),
    ),
    child: Image.network(
      'https://example.does.not.exist/image.jpg',
      errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
        // Appropriate logging or analytics, e.g.
        // myAnalytics.recordError(
        //   'An error occurred loading "https://example.does.not.exist/image.jpg"',
        //   exception,
        //   stackTrace,
        // );
        return const Text('😢');
      },
    ),
  );
}
```

2. Run the app.

**Expected results:** 

`Text('😢')` is rendered. No exception is raised or logged.

**Actual results:** 

Nothing is rendered in place of the image. The following message appears in the log:

```shell
════════ Exception caught by image resource service ════════════════════════════
The following SocketException was thrown resolving an image codec:
Failed host lookup: 'example.does.not.exist' (OS Error: nodename nor servname provided, or not known, errno = 8)

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://example.does.not.exist/image.jpg", scale: 1.0)
Image key: NetworkImage("https://example.does.not.exist/image.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
```

The same goes for HTTP errors, `Bad state: Insecure HTTP is not allowed by platform`, etc.

**Possibly related to:**

#69125
#69407

## Environment

```
$ flutter analyze

Analyzing flutter-app...                                             
No issues found! (ran in 4.0s)
```

```dart
$ flutter doctor -v

[✓] Flutter (Channel master, 2.1.0-13.0.pre.224, on macOS 11.2.3 20D91 darwin-x64, locale en-RU)
    • Flutter version 2.1.0-13.0.pre.224 at /Users/.../dart/flutter
    • Framework revision 5029be0b9f (71 minutes ago), 2021-03-23 16:42:20 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by pedromassangocode** [comment] 2021-03-24 08:45
Hi @jibiel 
I cannot reproduce this on latest master channel. I've tested on Android, Web and iOS.

![Screen Shot 2021-03-24 at 09 42 06](https://user-images.githubusercontent.com/67424416/112280728-9d263d00-8c85-11eb-97f7-581f6918c6f2.png)

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp() : super();

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatelessWidget(),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(),
            borderRadius: BorderRadius.circular(20),
          ),
          child: Image.network(
            'https://example.does.not.exist/image.jpg',
            errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
              // Appropriate logging or analytics, e.g.
              // myAnalytics.recordError(
              //   'An error occurred loading "https://example.does.not.exist/image.jpg"',
              //   exception,
              //   stackTrace,
              // );
              return const Text('😢');
            },
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.230, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.230 at /Users/pedromassango/Code/flutter_master
    • Framework revision 975fb0f06c (2 hours ago), 2021-03-23 21:33:05 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by jibiel** [comment] 2021-03-24 23:57
@pedromassangocode Thanks for the quick response.

I must confess, I wasn't entirely honest with you. Here is the code that causing the problem:

```dart
return Container(
  child: DecoratedBox(
    decoration: BoxDecoration(
      color: Colors.white,
      border: Border.all(),
      borderRadius: BorderRadius.circular(20),
    ),
    // NOTE: Works as expected.
    child: Image.network(
      'https://example.does.not.exist/image.jpg',
      errorBuilder: (context, exception, stackTrace) => const Text('😢'),
    ),
  ),
  decoration: BoxDecoration(
    color: Colors.white,
    borderRadius: BorderRadius.circular(20),
    // NOTE: Logs the exception and looks like renders nothing.
    image: DecorationImage(
      image: Image.network(
        'https://example.does.not.exist/image.jpg',
        errorBuilder: (context, exception, stackTrace) => const Text('😢'),
      ).image,
    ),
  ),
);
```

The latter `Image.network` logs the following message:

```shell
════════ Exception caught by image resource service ════════════════════════════
The following SocketException was thrown resolving an image codec:
Failed host lookup: 'example.does.not.exist' (OS Error: nodename nor servname provided, or not known, errno = 8)

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://example.does.not.exist/image.jpg", scale: 1.0)
Image key: NetworkImage("https://example.does.not.exist/image.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
```

Could it be the `Container` + `BoxDecoration` + `DecorationImage` conjunction-related problem or am I not using the API correctly?

**Comment by pedromassangocode** [comment] 2021-03-25 09:16
Hi @jibiel 
This is not how you are supposed to use `Image.network`, Image.network is a widget and decoration expects a `DecorationImage`. However the correct way to fails silently (don't call the `onError` function of the `DecorationImage`).

Here is a minimal repro code. It is supposed to show the warning icon.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        theme: ThemeData.dark(),
        home: Scaffold(
          body: Center(
            child: Container(
              width: 140,
              height: 140,
              decoration: BoxDecoration(
                color: Colors.grey,
                // TODO: NOTE: This silently fails.
                image: DecorationImage(
                  onError: (err, stack) => Icon(Icons.warning, size: 90, color: Colors.red),
                  image: NetworkImage('https://example.does.not.exist2/image.jpg'),
                ),
              ),
              // TODO: NOTE: This call errorBuilder.
 /*             child: Image.network('https://example.does.not.exist2/image.jpg',
                errorBuilder: (_, err, cc) => Icon(Icons.warning, size: 90),
              ),*/
            ),
          ),
        ),
      ),
    );
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.261, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.261 at /Users/pedromassango/Code/flutter_master
    • Framework revision b44e536c62 (24 minutes ago), 2021-03-24 23:09:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by jibiel** [comment] 2021-03-25 10:56
> This is not how you are supposed to use `Image.network`, `Image.network` is a widget and decoration expects a `DecorationImage`.

So IIUC, the answer is getting the `ImageProvider` instance directly via the `NetworkImage()` rather than creating `Image` widget instance and getting the `ImageProvider` instance via `Image#image`. Got it, thanks.

But the `DecorationImage#onError` is a callback and not intended to return any widgets.

```dart
DecorationImage(
  image: NetworkImage('https://example.does.not.exist2/image.jpg'),
  onError: (error, stackTrace) => print(error),
),
```
works as expected:

```shell
flutter: SocketException: Failed host lookup: 'example.does.not.exist2' (OS Error: nodename nor servname provided, or not known, errno = 8)
```

And so the question remains: how to return a fallback widget on error if I want to use an image from the internet in a `DecorationImage` and can't use `Image.network` for that?

**Comment by pedromassangocode** [comment] 2021-03-25 11:54
> But the `DecorationImage#onError` is a callback and not intended to return any widgets.

Updated my code and indeed it works.




> how to return a fallback widget on error if I want to use an image from the internet in a `DecorationImage` and can't use `Image.network` for that?

This is not possible as the `DecorationImage` is not a widget. 

Closing as it seems that there is no issue here.
Thank you

**Closed by pedromassangocode** 2021-03-25 11:54 UTC
Labels: a: images, found in release: 2.1, framework, has reproducible steps
