### ISSUE TITLE
signInWithEmailAndPassword

### ISSUE THREAD

**Issue by widanfatwa** [flutter/flutter#19508] opened 2018-07-18 09:33 UTC
when i tried to use this. FirebaseAuth.instance.signInWithEmailAndPassword(email:credEmail,password:credPassword);
the result is : 

`/AndroidRuntime(13937): java.lang.NullPointerException: null value in entry: uid=null
E/AndroidRuntime(13937): 	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
E/AndroidRuntime(13937): 	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
E/AndroidRuntime(13937): 	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
E/AndroidRuntime(13937): 	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:198)
E/AndroidRuntime(13937): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.userInfoToMap(FirebaseAuthPlugin.java:422)
E/AndroidRuntime(13937): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.mapFromUser(FirebaseAuthPlugin.java:440)
E/AndroidRuntime(13937): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.access$000(FirebaseAuthPlugin.java:25)
E/AndroidRuntime(13937): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:375)
E/AndroidRuntime(13937): 	at com.google.android.gms.tasks.zzj.run(Unknown Source)
E/AndroidRuntime(13937): 	at android.os.Handler.handleCallback(Handler.java:754)
E/AndroidRuntime(13937): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(13937): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime(13937): 	at android.app.ActivityThread.main(ActivityThread.java:6379)
E/AndroidRuntime(13937): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13937): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(13937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)`

and then my the debug apps is stopped working.
i try it from folder example on github, For google and faceebook signin is working well. except for this. 
is it a bugs or i miss something from that ?

Thank you for your attention :)

**Comment by zoechi** [comment] 2018-07-19 16:48
Please add the output of `flutter doctor -v` and the versions of the plugins you are using.

**Comment by zoechi** [comment] 2018-08-31 19:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-08-31 19:42 UTC

**Comment by zoechi** [comment] 2019-01-15 13:35
Duplicate of #13899
