### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#14422] opened 2018-02-01 21:30 UTC
## Steps to Reproduce

1. Create a project using the latest released Flutter.
2. Upgrade it from Gradle as described [here](https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1).
3. Try and run the project.
 
## Logs

I get this output from IntelliJ:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: Exit code 1 from: /Users/me/Tim/quicktimer/android/gradlew -v:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

I've tried quite a lot to solve this. In fact opening the `android` subfolder in Android Studio works fine and builds the APK without errors, so I really have no idea why this is happening. All the solutions on Google involve running `gradle wrapper` to regenerate the wrapper that will download the correct version of Gradle or something like that, but I don't know how to run `gradle`. It isn't in my `PATH`. I assume it is embedded in IntelliJ somewhere. Bit of a catch-22.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-GB, channel alpha)
    • Flutter at /Users/me/Tim/flutter
    • Framework revision 8f65fec5f5 (7 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.1.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by joshkahane** [comment] 2018-04-26 17:51
I too am experiencing this issue. Freshly setup Flutter within VS Code on macOS. Android Studio v3 installed. New Flutter project, all Android builds result in the following error:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Exit code 1 from: /Users/joshkahane/Desktop/Dart:Flutter Test/hello_world/android/gradlew -v:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Exited (sigterm)
```

**Comment by joshkahane** [comment] 2018-04-26 18:16
I resolved my issue by removing a forward slash '/' from a folder name my project was kept in. That / is translated into a ':' and it doesn't like it!

**Comment by zoechi** [comment] 2018-04-27 07:25
What's the output of `flutter doctor -v` after 

> Freshly setup Flutter

**Comment by danielborges93** [comment] 2018-05-15 14:42
1. Delete the flutter cache (installation folder > bin > cache);
1. Delete`gradle` and `gradle.bat` in `android` folder;
1. Run `flutter run` again.

This steps worked for me.

**Comment by efortuna** [comment] 2018-07-23 21:14
Slight tweak to @danielborges93's comment -- I deleted the `gradlew` file in `android` folder (along with the above steps), and it now works.

**Comment by zoechi** [comment] 2018-09-03 09:30
Closing as dup of #17280

**Closed by zoechi** 2018-09-03 09:30 UTC
Labels: severe: crash, t: gradle

**Comment by larryq** [comment] 2018-09-14 21:01
Combining @efortuna  and @danielborges93 steps above, I was also able to get past this error-- thanks.  (Does anyone know what the root cause was however?)

**Comment by TiagoHA** [comment] 2018-10-09 17:02
It did not work for me.
 I created a new project and moved the old files.

**Comment by teresawu** [comment] 2018-12-03 15:22
I had the same issue, and adding a gradle-wrapper.jar worked: /your-project/android/gradle/wrapper/gradle-wrapper.jar. you can find this jar file from any Android project

**Comment by HarveyStroud** [comment] 2019-12-22 12:35
I had this one also, tried all sorts but in the end, it turned out to be an ampersand in one of the parent directories where my project was located. Renaming the folder to remove the offending '&' fixed this issue for me.

**Comment by faiyazkhan024** [comment] 2020-03-07 15:28
Thanks @HarveyStroud it worked for me

**Comment by pauek** [comment] 2020-03-16 11:02
None of the above worked, @HarveyStroud suggestion worked. Thanks. My path had a ':' in it.

**Comment by zakiruxd** [comment] 2020-03-29 12:59
> I had this one also, tried all sorts but in the end, it turned out to be an ampersand in one of the parent directories where my project was located. Renaming the folder to remove the offending '&' fixed this issue for me.

My goodness. I spent hours and hours trying to figure this issue out and it turns out the ampersand was my issue. Incredible. Thank  you so much.

**Comment by HarveyStroud** [comment] 2020-03-29 18:44
No problem, I'm glad I could be of help :)
