### ISSUE TITLE
[tool] Android sdkmanager tool not found

### ISSUE THREAD

**Issue by Davidromerojimenez** [flutter/flutter#55791] opened 2020-04-27 23:39 UTC
```
Android sdkmanager tool not found (C:\Users\david\AppData\Local\Android\Sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.
```

**Comment by khari998** [comment] 2020-04-28 00:36
Run flutter doctor and post it here. It sounds like you just don't have Android SDK installed properly

**Comment by Davidromerojimenez** [comment] 2020-04-28 00:43
I already uninstalled it and installed the Android SDK again but it's still the same

this is my configuration 

![image](https://user-images.githubusercontent.com/8431789/80434402-51291780-88bf-11ea-8ea4-0b782e006eee.png)

**Comment by Davidromerojimenez** [comment] 2020-04-28 00:45
flutter doctor 

Downloading Gradle Wrapper...                                       0,5s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18362.778], locale es-CO)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

**Comment by khari998** [comment] 2020-04-28 00:58
Okay so its not Flutter that's broken. Its just not recognizing your Android SDK. I had the same issue before but it was months ago. So I don't remember exactly what solution I found that fixed it but I just googled "Flutter cannot recognize Android SDK." Here are the first few links that might be helpful. Youtube tutorials may also be very helpful. Always google your exact errors.

https://stackoverflow.com/questions/44485848/android-sdk-cannot-be-found-by-flutter?rq=1

https://github.com/flutter/flutter/issues/15114

https://stackoverflow.com/questions/49175231/flutter-does-not-find-android-sdk

https://www.youtube.com/watch?v=lSdcJD7vPs0

https://www.youtube.com/watch?v=Boe45t_uKwc

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:06
ok thanks,khari998 i will check the links

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:15
i see that is the android license..

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\david\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\david\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

the android sdk location is ok

**Comment by khari998** [comment] 2020-04-28 01:19
Try this 
```flutter doctor --android-licenses```
And going through the prompts. Found the solution by googling your error "X Android license status unknown." And finding someone who had the same error on github https://github.com/flutter/flutter/issues/16025

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:25
thanks khari998, but when execute this line, show this error 
flutter doctor --android-licenses

Downloading Gradle Wrapper...                                       0,5s
Android **sdkmanager** tool not found (C:\Users\david\AppData\Local\Android\Sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

**Comment by khari998** [comment] 2020-04-28 01:29
Hmm this is peculiar. I am inclined to say that the SDK is not installed in the right location but Flutter seems to recognize the SDK in the flutter doctor. Try and see if going through any of the other links I sent in my earlier response gets this working for you. If not I'll try chime in more. Also did you follow the instruction steps on https://flutter.dev/setup/#android-setup or did you go through a different set of instructions for the setup?

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:34
I have spent all day looking for a solution, I have tried everything, forums, videos, pages.
two days ago flutter was working fine, but from one moment to another this error appeared

**Comment by khari998** [comment] 2020-04-28 01:38
> I have spent all day looking for a solution, I have tried everything, forums, videos, pages.
> two days ago flutter was working fine, but from one moment to another this error appeared

All I can do is try to keep giving you links that may have solutions for you. Try this along with the other links I sent https://github.com/flutter/flutter/issues/20976

It would still help if you went through how you installed the Android SDK

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:44
Thanks, i have already intall Android SDK Tools (Obsolete), but the error is the same, 
thanks, i will try again

**Comment by khari998** [comment] 2020-04-28 01:47
Are you using a mac or pc? 

Also I found someone who said it may involve resetting your JAVA_HOME https://github.com/flutter/flutter/issues/16025#issuecomment-377219812

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:49
i have pc windows

**Comment by khari998** [comment] 2020-04-28 01:50
Okay. Also this may work as well. It may be an unspecified path https://github.com/flutter/flutter/issues/16025#issuecomment-377984231

**Comment by Davidromerojimenez** [comment] 2020-04-28 01:56
ok, i will try it

**Comment by Davidromerojimenez** [comment] 2020-04-28 02:16
thanks, but the problem is that, sdkmanager.bat not exist in the route C:\Users\MyUser\AppData\Local\Android\Sdk\tools\bin

I don't know where to get the file sdkmanager.bat

**Comment by khari998** [comment] 2020-04-28 04:47
> thanks, but the problem is that, sdkmanager.bat not exist in the route C:\Users\MyUser\AppData\Local\Android\Sdk\tools\bin
> 
> I don't know where to get the file sdkmanager.bat

Yeah I would try reinstalling Android SDK using some of the other instructions in one of my first comments. I haven't found much regarding the sdkmanager.bat file. It should come with the Android SDK when it is installed. Which leads me to believe it may be there but your path is not pointing to the right location to find it. Let me know if you reinstall it using someone the methods in my original comment and you still have the same error. Wipe Android SDK from your system first too.

**Comment by Davidromerojimenez** [comment] 2020-04-28 16:21
ok, when i tried install manually the tools android sdk, that have the sdkmanager.bat, https://github.com/flutter/flutter/issues/51712#issuecomment-593721423
later i run flutter --android-licenses and all the flutter doctor is ok, All SDK package licenses accepted. but when executed the project throws other error and that delete the managersdk android licenses again, 

Finished with error: Unable to locate gradlew script. Please check that C:\Users\david\AndroidStudioProjects\flutter_appborss\android\gradlew.bat exists or that C:\Users\david\AndroidStudioProjects\flutter_appborss\android can be read.

i think that is an big Bug of flutter

**Comment by jmagman** [comment] 2020-04-28 23:24
The original reported issue is a duplicate of https://github.com/flutter/flutter/issues/51712, as @Davidromerojimenez already figured out based on the last comment.  It's fixed for Windows in https://github.com/flutter/flutter/pull/54133, which is available in Flutter [1.18.0-dev.3.0](https://flutter.dev/docs/development/tools/sdk/releases?tab=windows) and later.

Please file a new issue for the gradlew issue.  Thanks!

**Closed by jmagman** 2020-04-28 23:24 UTC
Labels: platform-android, tool

**Comment by Davidromerojimenez** [comment] 2020-04-29 00:22
what?? the issue is not resolved.. is other error! jaj 
its not fixed,

**Comment by khari998** [comment] 2020-04-29 00:47
> ok, when i tried install manually the tools android sdk, that have the sdkmanager.bat, [#51712 (comment)](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)
> later i run flutter --android-licenses and all the flutter doctor is ok, All SDK package licenses accepted. but when executed the project throws other error and that delete the managersdk android licenses again,
> 
> Finished with error: Unable to locate gradlew script. Please check that C:\Users\david\AndroidStudioProjects\flutter_appborss\android\gradlew.bat exists or that C:\Users\david\AndroidStudioProjects\flutter_appborss\android can be read.
> 
> i think that is an big Bug of flutter

I saw that your version of Flutter in your logs is v1.12.13. Try running Flutter upgrade and switching to the dev channel to get to v 1.18.0-dev.3.0 as suggested. Please report back if this does not work.

**Comment by Davidromerojimenez** [comment] 2020-04-29 15:45
I tried with that sdk dev flutter but i have the same error

**Comment by jmagman** [comment] 2020-04-29 17:23
@Davidromerojimenez The original issue reported was "sdkmanager tool not found" which was fixed on Windows with https://github.com/flutter/flutter/pull/54133 and is available on 1.18.0-dev.3.0 and later.  You worked around the issue by following a comment on https://github.com/flutter/flutter/issues/51712#issuecomment-593721423.

It looks like you are now hitting a new issue "Unable to locate gradlew script".  Please file a new issue for this and completely fill out the template.  We don't track more than one problem in a GitHub issue as they may be duplicates of different existing issues, or may need different teams to look at them.

Thanks!

**Comment by Davidromerojimenez** [comment] 2020-05-06 20:24
the only way was by reinstalling windows, it already works

**Comment by msharma8020** [comment] 2020-05-07 21:38
@Davidromerojimenez I'm also facing the same error does re installation of the windows solve the issue? I already try all the things they mention above nothings solve the issue

**Comment by Davidromerojimenez** [comment] 2020-05-09 03:34
yes, reset the computer is the solution

**Comment by DJRahim** [comment] 2020-12-17 08:54
This the solution that worked for me :
1. Open Android-studio and go to SDK manager,
2. Select SDK tools tab,
3. Uncheck "Hide Obsolete Packages" in the bottom,
4. Check "Android SDK Tools (Obsolete)",
5. Apply.

Then when i did flutter doctor --android-licenses, it worked fine !
