### ISSUE TITLE
Horizontal Scrolling widgets dart pad examples not working on the Web

### ISSUE THREAD

**Issue by nrallakis** [flutter/flutter#101381] opened 2022-04-05 21:12 UTC
### Page URL

https://api.flutter.dev/flutter/widgets/PageView-class.html

### Describe the problem

After the breaking [changes](https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag) regarding ScrollBehaviors, it is not allowed (by default) to drag a scrolling widget with mouse drag.
As consequence, all Dart pad examples that contain a list do not scroll with mouse drag.
This is ok for vertical Lists/Grids that show a scrolling bar and scroll using the mouse's scroller.
However, for horizontal Lists/Grids/PageView, there is no horizontal scrollbar and shift+scroll doesn't work.

Examples: 
- [PageView](https://api.flutter.dev/flutter/widgets/PageView-class.html)

### Expected fix

One fix is to add ScrollConfiguration with PointerDeviceKind mouse, as discussed in the [migration](https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag) guide to allow mouse drag scrolling.

It should at least be noted somewhere inside the examples because it is confusing for new users.

**Comment by danagbemava-nc** [comment] 2022-04-06 08:39
Duplicate of #90775

**Closed by danagbemava-nc** 2022-04-06 08:39 UTC
Labels: framework, f: scrolling, d: api docs, documentation
