### ISSUE TITLE
Flutter [Web] ReorderableListView missing end icon 'handle' on Android Web

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#90029] opened 2021-09-14 06:57 UTC
Greetings,

I notice that the ReorderableListView on Android Web View is missing the touch icon at the end, it appears to be present on desktop and iPad Web.

Sample code from here:
https://api.flutter.dev/flutter/material/ReorderableListView-class.html

Expected:
![image](https://user-images.githubusercontent.com/81489824/133209528-8c2f7893-d76d-461b-8a1b-8a0fa5cc60e2.png)

Android Web:
![image](https://user-images.githubusercontent.com/81489824/133209897-bcedf4c6-551f-45b0-a87f-0f7825feb5cc.png)

<details> 
<summary>minimal code sample</summary> 

/// Flutter code sample for ReorderableListView

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.primary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.primary.withOpacity(0.15);

    return ReorderableListView(
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index++)
          ListTile(
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

</details>

<details> 
<summary>flutter doctor</summary> 

[√] Flutter (Channel master, 2.6.0-6.0.pre.71, on Microsoft Windows [Version 10.0.17763.2114], locale en-IE)
    • Flutter version 2.6.0-6.0.pre.71 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd112e551c (12 hours ago), 2021-09-13 12:13:42 -0700
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
</details>

**Comment by Mayank-9018** [comment] 2021-09-14 07:37
ReorderableListView has an attribute [buildDefaultDragHandles](https://api.flutter.dev/flutter/material/ReorderableListView/buildDefaultDragHandles.html) which default to true, and builds drag handles on desktop platforms and hold and drag behaviour on mobile device for reordering. If you want to have drag handles on mobile devices as well, you can do something like this:

```dart
return ReorderableListView(
      buildDefaultDragHandles:false,  //Remove default drag handles
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index++)
          ListTile(
            trailing: ReorderableDragStartListener(index:index,child: const Icon(Icons.drag_indicator_outlined)),   //Wrap it inside drag start event listener
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
```
**This will work on Desktop as well as mobile platforms, but it will disable hold and drag  on mobile platforms.**

Complete Example:

```dart
/// Flutter code sample for ReorderableListView

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.primary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.primary.withOpacity(0.15);

    return ReorderableListView(
      buildDefaultDragHandles:false,  //Remove default drag handles
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index++)
          ListTile(
            trailing: ReorderableDragStartListener(index:index,child: const Icon(Icons.drag_indicator_outlined)),   //Wrap it inside drag start event listener
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}
```

**Comment by maheshmnj** [comment] 2021-09-14 11:01
Hi @zambetpentru, This is the intended behavior for mobile platforms. Please see this [api docs for more on buildDefaultDragHandles](https://api.flutter.dev/flutter/material/ReorderableListView/buildDefaultDragHandles.html) 

Thanks, @Mayank-9018  for volunteering.

You may also refer this similar issue raised in the past https://github.com/flutter/flutter/issues/80553

Closing this issue as it is working as intended. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-14 11:01 UTC
Labels: in triage

**Comment by zambetpentru** [comment] 2021-09-14 12:15
Cheers thank you both!

**Comment by zambetpentru** [comment] 2021-09-14 16:54
@Mayank-9018 thanks for your detailed response. Do you know what is the official flutter way to determine the difference between mobile and desktop web? As in this case interestingly the iPad shows the drag handles but my Android phone wasn't.

**Comment by Mayank-9018** [comment] 2021-09-15 09:40
@zambetpentru You can use `Theme.of(context).platform` or
```dart
import 'dart:io' show Platform;    //Won't work on Web
print(Platform.operatingSystem);
```

**Comment by zambetpentru** [comment] 2021-09-15 10:08
Hi, @Mayank-9018 I think maybe my question wasn't as specific as it should have been. :-)

So the drag handles show on Desktop and they also show on my iPad but not on my Android phone. At the same time the iPad appears to be detected as a mobile device as it chooses the HTML renderer rather than the CanvasKit so I was trying to see how the choice was being made for the ReorderableListView handle.
