### ISSUE TITLE
support raw_keyboard_window

### ISSUE THREAD

**Issue by hayhv** [flutter/flutter#41072] opened 2019-09-23 04:41 UTC
The flutter engine on Windows OS current use android keyboard map
`#static constexpr char kAndroidKeyMap[] = "android";`
Need support keyboard map for Windows OS like `raw_keyboard_linux`, `raw_keyboard_macos`

**Comment by janmoppel** [comment] 2019-09-23 05:51
Hello @hayhv !

Thank you for posting an issue.
This may be also related to the #31945

**Comment by franciscojma86** [comment] 2019-09-25 22:28
Closing as this is a duplicate of https://github.com/flutter/flutter/issues/37710

**Closed by franciscojma86** 2019-09-25 22:28 UTC
Labels: a: text input, engine, severe: new feature, ❖ platform-windows, 🐧 platform-linux
