### ISSUE TITLE
[Stable 3.3+] Rendering issues (Artefacting / Half-rendered widgets)

### ISSUE THREAD

**Issue by hm122** [flutter/flutter#111376] opened 2022-09-11 23:16 UTC
Since the upgrade to Flutter 3.3.0, I'm getting different feedback from users that they are experiencing weird rendering issues. 

## Steps to Reproduce

1. Unfortunately, the issues are not easily reproducible, but started after the upgrade to 3.3.0.

**Expected results:** No flickering/rendering errors

**Actual results:** Flickering borders, half rendered views. Most of the time, the rendering issues seem to disappear when changing the view or tapping into the screen.

<details>
<summary>Code sample</summary>

_Sometimes_ the border of text input fields flickers. Could be related to very thin borders.

```dart
border: Border.all(width: 0.5)
```

_Sometimes_ views get half rendered when changing screen with a BottomNavigationBar.

</details>

<details>
  <summary>Logs</summary>
I have downgraded to Flutter 3.0.5 for now, therefore I can not provide `flutter analyze/doctor` info

</details>

**Comment by danagbemava-nc** [comment] 2022-09-12 09:31
Hi @hm122, what platforms are your users experiencing this issue on? 

Can you also share some screen recordings so that we can see what the issue looks like?

**Comment by onurkagan** [comment] 2022-09-13 14:59
I'm having the same problems with Android devices. The problematic flutter version is 3.3.1. Dart version 2.18.0. Android API level 32. The problem is not in debug mode. It is observed in profile and release mode. There is no error log.

**Comment by TatsuUkraine** [comment] 2022-09-13 22:52
@hm122 I'm curious if you have similar rendering issues to this one? https://github.com/flutter/flutter/issues/110885#issuecomment-1240380523

**Comment by danagbemava-nc** [comment] 2022-09-14 06:29
Hi @onurkagan, can you share some recordings along with a minimal reproducible code sample so that we can investigate this?

**Comment by hm122** [comment] 2022-09-14 06:31
It was on Android and iOS. I was able to reproduce some of the issues locally, even in the emulator. Will try to provide code & screencasts asap.

**Comment by TatsuUkraine** [comment] 2022-09-14 06:41
@hm122 yeah, I also have different render issues each time. On a video I recorded just an example how it looks like

**Comment by TatsuUkraine** [comment] 2022-09-14 08:04
@danagbemava-nc I found most simple code to reproduce it) but it may take time before you actually can see it since it happens from time to time. The video shows just most simple render issue, in the real app I'm experiencing worse UI render issues in various part of the screen. Same as before - when I'm trying to make a screen record it doesn't show what is actually going on on a screen

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('App Example'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showLicensePage(
              context: context,
              applicationIcon: Image.asset(
                'assets/flutter_icon.png',
                height: 50,
              ),
              applicationName: 'Some App Name',
              applicationVersion: '1.0.0',
            );
          },
          child: const Text('SHOW LICENCES'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

<details>
<summary>Video</summary>

</details>

**Comment by TatsuUkraine** [comment] 2022-09-17 19:40
@danagbemava-nc it seems @hm122 replied on your question, but this issue still has `waiting for response` tag

**Comment by TatsuUkraine** [comment] 2022-09-19 20:48
Copy steps to reproduce with code sample from another ticket per @exaby73 request 

## Steps to Reproduce

Try to use code sample. Scroll down and up until you see the issue with rendering. The issue can be seen from time to time. Also it can't be captured with a screen record. On a screen record UI looks good and it doesn't show what is actually going on on the screen

1. Build the app from the code sample 
2. Open the Licenses page 
3. scroll down and up multiple times until you see the issue

Another example
1. Build the app from the code sample 
2. Open bottom sheet all the way up
3. swipe down to snap bottom sheet to .5 possition
4. swipe up to expand bottom sheet fully
5. repeat 3 and 4 until you see the issue

**Expected results:** UI should render without artifacts

**Actual results:** some of UI parts aren't repainted correctly

### Additional info

Device: Pixel 5
OS: Android 13
Build mode: any

All works fine with flutter 3.0. Also scroll in 3.0 is much smoother than in 3.3

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final DraggableScrollableController _controller = DraggableScrollableController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          const SliverAppBar(
            automaticallyImplyLeading: false,
            title: Text('App Example'),
          ),
          SliverFillRemaining(
            hasScrollBody: false,
            child: Center(
              child: ElevatedButton(
                onPressed: () {
                  showLicensePage(
                    context: context,
                    applicationIcon: Image.asset(
                      'assets/flutter_icon.png',
                      height: 50,
                    ),
                    applicationName: 'Some App Name',
                    applicationVersion: '1.0.0',
                  );
                },
                child: const Text('SHOW LICENCES'),
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
      bottomSheet: MediaQuery.fromWindow(
        child: LayoutBuilder(
          builder: (context, constraints) {
            final EdgeInsets safePadding = MediaQuery.of(context).padding;
            final double minExtent = (kToolbarHeight + 8) / constraints.biggest.height;

            return DraggableScrollableSheet(
              controller: _controller,
              snapSizes: [
                minExtent,
                .5,
              ],
              snap: true,
              initialChildSize: minExtent,
              minChildSize: minExtent,
              maxChildSize: 1,
              expand: false,
              builder: (context, controller) {
                final double currentExtent = _extent ?? minExtent;
                final bool expanded = currentExtent > .9;

                return DecoratedBox(
                  decoration: const BoxDecoration(
                    boxShadow: [
                      BoxShadow(
                        blurRadius: 8.0,
                        color: Colors.black54,
                        offset: Offset(0, 4),
                      ),
                    ],
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.vertical(
                      top: Radius.circular(
                        Tween<double>(begin: 10.0, end: 0.0)
                            .chain(_curve)
                            .transform(currentExtent)
                      ),
                    ),
                    child: Material(
                      color: Theme.of(context).colorScheme.surface,
                      child: CustomScrollView(
                        controller: controller,
                        physics: const ClampingScrollPhysics(),
                        slivers: [
                          SliverPadding(
                            padding: EdgeInsets.only(
                              top: Tween(begin: 8.0, end: safePadding.top - 4)
                                  .chain(_curve)
                                  .transform(currentExtent),
                            ),
                            sliver: SliverAppBar(
                              centerTitle: true,
                              pinned: true,
                              primary: false,
                              elevation: 0,
                              leading: AnimatedSwitcher(
                                duration: const Duration(milliseconds: 300),
                                child: expanded
                                    ? const CloseButton()
                                    : null,
                              ),
                              title: const Text('Bottom sheet'),
                              backgroundColor: Theme.of(context).colorScheme.surface,
                              foregroundColor: Theme.of(context).colorScheme.onSurface,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                );
              }
            );
          }
        ),
      ),// This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Animatable<double> get _curve => CurveTween(
    curve: const Interval(.75, 1, curve: Curves.easeIn)
  );

  double? get _extent => _controller.isAttached ? _controller.size : null;
}


```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.2.1 21D62 darwin-arm, locale en)
    • Flutter version 3.3.2 on channel stable at <some path>
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at <some path>
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = <some path>
    • Java binary at: <some path>
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at <some path>
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at <some path>
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • Pixel 5 (mobile)            • ******* • android-arm64 • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 12.2.1 21D62 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>


<details>
  <summary>Videos</summary>

https://user-images.githubusercontent.com/621542/190097302-c930b049-be44-424c-bbaf-144393a1072d.mp4


https://user-images.githubusercontent.com/621542/190982542-a8923597-b6d9-41c4-a59d-313a18080927.mp4


</details>

**Comment by danagbemava-nc** [comment] 2022-09-20 06:49
Hi @TatsuUkraine, I'm curious, are you only facing this issue on a Pixel 5? 
There was a similar issue reported recently about artifacting on Pixel 5 reported in https://github.com/flutter/flutter/issues/111551. Is that similar to your case?

**Comment by TatsuUkraine** [comment] 2022-09-20 07:53
hi @danagbemava-nc . it looks similar but I can't confirm that it's exactly the same, I didn't see the render issue recorded in #111551 in our real app. 

As for devices so far I tried Pixel 2xl, Pixel 4, Pixel 5, Pixel 6 (all real devices).

Was able to reproduce this issue only on Pixel 5 and Pixel 4 (based on feedback from a friend of mine) so far.

**Comment by danagbemava-nc** [comment] 2022-09-20 13:14
Hi @TatsuUkraine, can you share the asset you used in your code sample?

**Comment by TatsuUkraine** [comment] 2022-09-20 13:20
@danagbemava-nc you can use any, I used ic_launcher.png file from regular flutter template project
![flutter_icon](https://user-images.githubusercontent.com/621542/191268661-851eb5da-9041-49cd-a52b-2bdf3453f6f9.png)

**Comment by danagbemava-nc** [comment] 2022-09-20 14:02
Hi @TatsuUkraine, I can't seem to reproduce the issue on my `Poco X3 NFC`. 

Can you check if this still reproduces for you on the `master` channel?

**Comment by TatsuUkraine** [comment] 2022-09-20 14:07
@danagbemava-nc I tried stable master and beta, everywhere I can reproduce it. On pixel 4 and 5 (only real devices), pixel 6 and pixel 2xl - all works fine

it seems it may be related to dpr but I can say for sure

**Comment by TatsuUkraine** [comment] 2022-09-20 14:57
@danagbemava-nc also I tried 3.0.5 (prev stable version) and I wasn't been able to reproduce this bug on any device there, also scroll looks much smoother on 3.0 as well

**Comment by semog** [comment] 2022-09-20 18:40
There are lots of severe rendering issues on Linux desktop. This is not just a mobile issue. It's like the anti-aliasing algorithm is broken. Just hovering the mouse across window frame borders can cause the app to re-render into an awful mess. Move it some more, and then it renders correctly. I've had to downgrade back to 3.0.5, which is very stable in its rendering.

**Comment by danagbemava-nc** [comment] 2022-09-21 07:53
@TatsuUkraine, thanks for the report. Since I can't reproduce this issue locally, I will label it for further investigation by the team. 

This seems to be a regression as all the comments in this issue state that it happened after the upgrade to 3.3 

Some of the issues can be found in https://github.com/flutter/flutter/issues/111376#issuecomment-1251532339.

**Comment by TatsuUkraine** [comment] 2022-09-21 07:54
@danagbemava-nc thanks

**Comment by WingCH** [comment] 2022-09-23 00:29
similar issues 🙏

https://github.com/flutter/flutter/issues/112151

**Comment by athul-ain** [comment] 2022-09-23 18:42
> Hi @hm122, what platforms are your users experiencing this issue on?
> **Android**
> Can you also share some screen recordings so that we can see what the issue looks like?

https://user-images.githubusercontent.com/60373551/192035011-20ec4424-3bf2-4f98-a3ba-982580d7466a.mp4

> Device: SAMSUNG S22 Ultra
> Android Version: 13
> Flutter Version: 3.3.2

**Comment by chinmaygarde** [comment] 2022-09-26 17:44
From Triage: @HansMuller Can you add the context for why @jonahwilliams was assigned? I am not sure he is currently looking into this. I'll try to get this and the linked issue reproduced.

**Comment by jonahwilliams** [comment] 2022-09-26 17:45
I asked to be assig

**Comment by jonahwilliams** [comment] 2022-09-26 17:46
Oops. I asked to be assigned last week, but that was Friday afternoon so I haven't investigated yet

**Comment by uzumaki258** [comment] 2022-09-27 03:48
I can reproduce it as well, it happened when I upgrade to 3.3+
IMG_2293.mov

**Comment by TatsuUkraine** [comment] 2022-09-27 21:06
@danagbemava-nc I just tried to turn of smooth display (to keep 60hz refresh rate) and render issues disappeared

**Comment by aarajput** [comment] 2022-10-04 17:24
Is anyone from flutter team looking at this issue? I am facing exact same issue on flutter 3.3+. I had to downgrade flutter version to 2.8 because of that. I am using pixel 4XL.

**Comment by jonahwilliams** [comment] 2022-10-04 18:04
We believe that this is related to the CP we have scheduled in https://github.com/flutter/flutter/issues/112603, however we have been unable to reproduce this particular issue. If you are experiencing this and you have a reliable reproduction, it would be helpful if you could temporarily switch to the master channel where the revert has already landed and confirm.

**Comment by TatsuUkraine** [comment] 2022-10-04 18:07
@jonahwilliams if it helps, I put code sample with steps to reproduce + video here https://github.com/flutter/flutter/issues/111376#issuecomment-1251532339

I was able to easily reproduce it on devices with refresh rate > 60hz, switching off smooth display fixes the issue

**Comment by jonahwilliams** [comment] 2022-10-04 18:08
I've tried that example and I can't reproduce it locally unforunately

**Comment by TatsuUkraine** [comment] 2022-10-04 18:11
Hm, ok, I will try master channel and check if it still there

**Comment by TatsuUkraine** [comment] 2022-10-04 18:25
it looks to me that on master channel all works fine, and the scroll also feels smoother

**Comment by aarajput** [comment] 2022-10-04 21:30
For me, it only happens on release builds. I'll check master branch as well.

**Comment by jonahwilliams** [comment] 2022-10-05 17:58
We've published a new stable hotfix that contains a fix for similar issues. Please let me know if you're still experiencing this issue after upgrading to 3.3.4

**Comment by TatsuUkraine** [comment] 2022-10-05 18:13
Need to play more with the app, but so far I don't any render issues after updating to 3.3.4

**Comment by jonahwilliams** [comment] 2022-10-05 19:01
Great! Closing this as fixed then

**Closed by jonahwilliams** 2022-10-05 19:01 UTC
Labels: severe: regression, engine, severe: rendering, P4
