### ISSUE TITLE
`Theme.of(context).accentColor` not being migrated by `dart fix`

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#89726] opened 2021-09-09 08:21 UTC
After upgrading to Flutter 2.5.0, I ran `dart fix` to rename all the deprecated `accentColor` properties.
All of them were migrated correctly expect the ones that are accessed from `Theme.of(context).accentColor`.
I've tried adding a test case + expectation for this in the master branch and it seems to also fail.

# Steps to reproduce

1. Inside a Flutter 2.5.0 project place `Theme.of(context).accentColor` somewhere to get a deprecation warning
2. Run `dart fix lib --apply`
3. The line is not migrated to `colorScheme.secondary`

It's not a big deal, since it's easy to migrate them with a "find and replace", but maybe this is an easy fix.

**Comment by TahaTesser** [comment] 2021-09-09 11:40
Hi @davidmartos96 
Thanks for filing the issue

### Investigation
Indeed `accentColor` is not picked up `dart fix`, while another deprecated API `setEnabledSystemUIOverlays` does get picked. Run the code sample below on `stable` or `master`, bundle dart, and only 1 fix suggested that is `setEnabledSystemUIOverlays`. 
If `setEnabledSystemUIOverlays` is commented, there is no fix.

### Reproducible code sample

<details> 
<summary>complete minimal runnable code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          color: Theme.of(context).accentColor,
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>



### Logs

<details> 
<summary>logs</summary> 
	
```console
tahatesser@Tahas-MacBook-Pro triage % dart fix --dry-run

Computing fixes in triage (dry run)... 18.9s
Nothing to fix!
tahatesser@Tahas-MacBook-Pro triage % 
```
	
</details>

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (30 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.219, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.219 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 58944e6b88 (9 hours ago), 2021-09-08 19:37:34 -0700
    • Engine revision 6a3b04632b
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

**Comment by HansMuller** [comment] 2021-09-09 16:58
CC @Piinks

**Comment by Piinks** [comment] 2021-09-09 17:02
@bwilkerson is this a limitation of `dart fix`? I don't know if it can identify this case.

**Comment by bwilkerson** [comment] 2021-09-09 17:46
I don't know whether `dart fix` is currently able to support this. At a superficial glance it looks like it _ought_ to be able to; the fix data for it looks right to me. I'll try to take a look at debugging it fairly soon.

**Comment by Piinks** [comment] 2021-09-09 19:01
Thanks for taking a look @bwilkerson I have filed https://github.com/dart-lang/sdk/issues/47173 in the dart repo with my findings as this appears to be an issue with the tool. I am going to close this  to track the issue there. Thanks for reporting @davidmartos96!

**Closed by Piinks** 2021-09-09 19:01 UTC
Labels: framework, f: material design, dependency: dart, has reproducible steps, found in release: 2.2, found in release: 2.6

**Comment by davidmartos96** [comment] 2021-09-09 19:10
@Piinks You are welcome!

**Comment by parmarravi** [comment] 2021-09-11 07:34
So when can we expect this fix?
