### ISSUE TITLE
Flutter search delegate dosen't work when navigate back from a route

### ISSUE THREAD

**Issue by amirfeqhi** [flutter/flutter#25937] opened 2019-01-01 08:48 UTC
I'm using Flutter `SearchDelegate` in my app and here's the code:
```dart
class NameSearch extends SearchDelegate<String> {
@override
List<Widget> buildActions(BuildContext context) {
return [
  IconButton(
    icon: Icon(Icons.clear),
    onPressed: () {
      query = "";
    },
  )
];
}

@override
Widget buildLeading(BuildContext context) {
return IconButton(
  icon: AnimatedIcon(
      icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
  onPressed: () {
    close(context, null);
  },
);
}

@override
Widget buildResults(BuildContext context) {
 return null;
}

@override
Widget buildSuggestions(BuildContext context) {
suggestionList = query.isEmpty ? [] : List.generate(nameList.length,
 (i) => nameList[i]).where((p) => p.name.startsWith(query)).toList();

return ListView.builder(
  itemBuilder: (context, index) => ListTile(
        onTap: () {
          Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (context) => DetailScreen(
                        detail: suggestionList[index],
                      )));
        },
        leading: Icon(Icons.book),
        title: RichText(
          text: TextSpan(
              text: suggestionList[index].name.substring(0, query.length),
              style: TextStyle(
                  color: Colors.black, fontWeight: FontWeight.bold),
              children: [
                TextSpan(
                    text: suggestionList[index].name.substring(query.length),
                    style: TextStyle(color: Colors.grey))
              ]),
        ),
      ),
  itemCount: suggestionList.length,
);
}
}
```

When I clicked on an item in a suggestion list, It gets me to the new detail screen and works properly. But when I want to back to the search screen, the text input become like that:
<img width="263" alt="screen shot 1397-10-10 at 23 47 57" src="https://user-images.githubusercontent.com/26363996/50571410-b13ca600-0dbe-11e9-94fe-68df9be08e4a.png">

And I can't insert any text anymore, till restart the app or go to another page and after that go back to search page again!

And here is my `DetailScreen` code:
```dart
class DetailScreen extends StatelessWidget {
final BookDetail detail;
DetailScreen({Key key, @required this.detail}) : super(key: key);

@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
    title: Text(detail.name),
  ),
  body: Padding(
    padding: EdgeInsets.all(16.0),
    child: Text(detail.description),
  ),
);
}
}
```

**Comment by zoechi** [comment] 2019-01-02 08:53
Duplicate of #23862 
Please add a comment if you think this is not a duplicate and I'll reopen.

**Closed by zoechi** 2019-01-02 08:53 UTC

**Comment by amirfeqhi** [comment] 2019-01-02 11:34
It's the same. but still no solution! Is it a bug?

**Comment by amirfeqhi** [comment] 2019-01-02 11:34
> It's the same. but still no solution! Is it a bug?

@zoechi

**Comment by amirfeqhi** [comment] 2019-01-02 11:35
> Duplicate of #23862
> Please add a comment if you think this is not a duplicate and I'll reopen.

It's the same. but still no solution! Is it a bug?

**Comment by zoechi** [comment] 2019-01-02 12:35
@amirfeqhi not sure, looks like nobody got to fully investigate yet.
Have you tried on StackOverflow? There you usually get a quicker response.

**Comment by amirfeqhi** [comment] 2019-01-02 12:57
> @amirfeqhi not sure, looks like nobody got to fully investigate yet.
> Have you tried on StackOverflow? There you usually get a quicker response.

Yes. Here: https://stackoverflow.com/questions/53991158/flutter-search-delegate-doesnt-work-when-navigate-back-from-a-route
But also no one.

**Comment by amirfeqhi** [comment] 2019-01-02 13:02
> @amirfeqhi not sure, looks like nobody got to fully investigate yet.
> Have you tried on StackOverflow? There you usually get a quicker response.

I think, It should labeled in the issues. because it's so important, and as I see, there are some others struggling with this.

**Comment by scottnimos** [comment] 2019-01-10 03:13
I have also encountered this issue. Has anyone found a solution?

**Comment by hitesh-ahuja-sc** [comment] 2019-06-14 05:00
Hi @amirfeqhi i was facing same issue so what i did is i simply copy the search.dart from material library and replace "bool get maintainState => false;" to "bool get maintainState => true;" on line number 294 it worked for me.

**Comment by UmarBhutta** [comment] 2020-05-13 20:10
Hi, Any leads on it ?
