### ISSUE TITLE
Text of the TextField shown on bottom of the app on macOS 14.0

### ISSUE THREAD

**Issue by ShawnAlisson** [flutter/flutter#128956] opened 2023-06-15 17:37 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make a TextField
2. Type

### Expected results

Only showing text on the TextField.

### Actual results

It shows the text on the bottom of the app too.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter TextField Bug on macOS',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'TextField Bug on macOS'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
<img width="776" alt="Screenshot 2023-06-15 at 9 03 07 PM" src="https://github.com/flutter/flutter/assets/73370054/0a47b14c-d66f-4c2b-b76f-4fd46b49a863">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on macOS 14.0 23A5257q darwin-arm64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/shawn/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/shawn/SDK/Android
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/shawn/SDK/Android
    • Java binary at: /Users/shawn/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5160n
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/shawn/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Shawn’s iPhone (mobile) • 00008030-001479693E84802E • ios            • iOS 17.0 21A5248v
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.0 23A5257q darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Microsoft Edge 114.0.1823.43

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-06-16 06:57
Thanks for the report @ShawnAlisson 
Although I am not on latest macOS version to verify this, but I tried on Ventura 13.4 and another lesser version 12.2.1 on which the said behavior doesn't occur, so it could be specific to macOS 14 version as you mentioned.
Before we could make this issue actionable, can you confirm text duplication occurs on latest master or beta as well ?

`flutter channel master`
`flutter upgrade`

or 

`flutter channel beta`
`flutter upgrade`

**Comment by ShawnAlisson** [comment] 2023-06-16 16:43
Thanks for your response @darshankawar 
Yes, unfortunately it's happening on both (Flutter 3.12.0-4.0.pre.100 • channel master) and (Flutter 3.12.0 • channel beta).

**Comment by darshankawar** [comment] 2023-06-19 05:31
Thanks for the update. I'll label it for now based on the report and also [this](https://github.com/flutter/flutter/issues/128956#issuecomment-1594200778) limitation currently at my end. I also tried to find as what could be causing this on latest macOS version, but couldn't find any related issue or PR.

**Comment by felixkriechbaum** [comment] 2023-06-20 19:26
Same here on stable branch.
![CleanShot 2023-06-20 at 21 25 30](https://github.com/flutter/flutter/assets/1184644/afa702a3-8875-478e-bf3c-4d3d3e060559)
Only happens when I focused the Textfield

**Comment by loic-sharma** [comment] 2023-06-22 18:08
@justinmc Would you be able to look at this bug?

**Comment by justinmc** [comment] 2023-06-22 20:37
I'll have to see when I can update my machine to macOS 14 so I can actually try this, right now I'm just speculating.  This might even be a bug in macOS 14 and not Flutter, since it's currently in preview only.

[Here is the code](https://github.com/flutter/engine/blob/a3c5a319fccb7b137949ee7f410bf2510148dd3d/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L360) where we create an NSTextInputContext on macOS.  The [coordinate system on macOS](https://developer.apple.com/library/archive/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html) has its origin in the bottom left corner, which is not coincidentally where the duplicate text is appearing.

@ShawnAlisson If you have time, could you check to see if the Flutter app can draw on top of the text?  Like I wonder if you put a big red Container in the bottom left of the app, will the text be obscured by it or appear on top of it?

Maybe there has been a change in compositing or draw order on macOS 14.

**Comment by ShawnAlisson** [comment] 2023-06-22 22:11
@justinmc I have checked it. Despite using a colored container, the text still appears on top of it. Interestingly, the previous version of my app, built on macOS 13, didn't have this issue when tested on macOS 14. Unfortunately, I no longer have access to macOS 13 to confirm if the text bug also occurs there. Could someone kindly test it on macOS 13 and let me know if the problem persists?

[flutter_text_bug_test 1.0.0.zip](https://github.com/flutter/flutter/files/11840772/flutter_text_bug_test.1.0.0.zip)

**Comment by darshankawar** [comment] 2023-06-26 08:17
> Could someone kindly test it on macOS 13 and let me know if the problem persists?

We already verified the same on Ventura 13.4 version as mentioned [here](https://github.com/flutter/flutter/issues/128956#issuecomment-1594200778) on which we were unable to replicate the reported behavior.

**Comment by ShawnAlisson** [comment] 2023-06-26 09:19
> > Could someone kindly test it on macOS 13 and let me know if the problem persists?
> 
> We already verified the same on Ventura 13.4 version as mentioned [here](https://github.com/flutter/flutter/issues/128956#issuecomment-1594200778) on which we were unable to replicate the reported behavior.

As I mentioned before, this build was created on macOS 14. Apps built on macOS 13 didn't face any issues on macOS 14. Now, I'd like to determine if apps built on macOS 14 have any problems when running on previous versions.

**Comment by NeariX67** [comment] 2023-07-09 08:51
https://www.mediafire.com/file/pgebx9qeaine3fc/Archive.zip/file

Contains a small example app (ARM64), build with MacOS 14.0 Developer Beta 3
<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 14.0 23A5286g darwin-arm64, locale en-DE)
    • Flutter version 3.10.4 on channel stable at /Users/justin/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (5 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/justin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5161b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)            
    • MyPhone 12 (mobile) • 00008101-001928EA1484001E • ios            • iOS 17.0 21A5277h
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 14.0 23A5286g darwin-arm64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by ninjawarrior1337** [comment] 2023-08-24 07:36
The issue, at least for me, seems to be fixed when building on macOS 14 Beta 6 (23A5328b).

**Comment by justinmc** [comment] 2023-08-24 16:09
@cbracken, I think you were mentioning this problem to me yesterday.

**Comment by cbracken** [comment] 2023-08-30 19:25
As of this morning's macOS 14.0 Sonoma beta7 (23A5337a) this is no longer reproducing for me.

**Comment by cbracken** [comment] 2023-09-01 01:38
Since this no longer reproduces on the most recent beta, I'm going to close this issue. Please comment if you've upgraded to macOS 14.0 Sonoma beta 7 (build 23A5337a) or later and are still experiencing this issue.

**Comment by cbracken** [comment] 2023-09-28 18:08
This is back in the macOS 14 Sonoma final release. Working on a workaround for this right now.

**Closed** 2023-09-28 20:14 UTC
Labels: a: text input, framework, f: material design, platform-mac, a: typography, a: desktop, e: OS-version specific, P1, r: fixed, team-desktop, triaged-desktop, multiteam-retriage-candidate

**Comment by cbracken** [comment] 2023-09-28 20:21
Thanks for the fix!
