### ISSUE TITLE
InteractiveViewer- web - mac trackpad - pinch zoom disables 2-finger scroll up

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#80690] opened 2021-04-19 05:08 UTC
Resize the child using 2-finger trackpad pinch -> child is magnified. Expected.
Then try using 2-finger trackpad scroll  to scroll s.t. the top of the magnified child is visible -> interprets the 2-finger scroll as a magnify gesture, so instead of scrolling, the child just gets bigger !

**Comment by biancashouse** [comment] 2021-04-19 05:19
Workaround - set the arg scaleEnabled to false if scaling is not essential.

**Comment by darshankawar** [comment] 2021-04-19 10:18
@biancashouse 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by biancashouse** [comment] 2021-04-19 23:28
Sorry, it's a bit tricky to extract a simple fragment at the moment.
My InteractiveViewer is actually inside a (horizontal) CustomScrollView.
I provide some code below this comment...

What I notice is that when scaleEnabled is true, 2 fingers does the scaling, and 3 fingers does the scroll.
Bit tricky for non-geeks, and not intuitive IMHO.

    return SizedBox(
      height: max(Responsive.screenH(context) - 80, fbe.screenPaperH+12),
      child: CustomScrollView(
        scrollDirection: Axis.horizontal,
        slivers: [
          SliverList(
            delegate: SliverChildListDelegate([
              Container(
                width: moveFloating ? Responsive.screenW(context) : fbe.screenPaperW + 12,
                height: max(Responsive.screenH(context) - 80/*APP_BAR?*/, fbe.screenPaperH + 12),
                child: InteractiveViewer(
                  transformationController: _transformationController,
                  constrained: false,
                  minScale: .5,
                  scaleEnabled: true,
                  child: _flowchartEditorWidgets(),
                ),
              ),
              if (App.editorBloc.state is Editor_Initial && selectedChildFlowchartW != null)
                Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(18.0),
                      child: Text('child flowchart preview'),
                    ),
                    selectedChildFlowchartW,
                  ],
                ),
              //if (App.editorBloc.state is! Editor_Adding_A_Step) _adviceWidget,
              if (App.editorBloc.state is Editor_Initial && selectedChildFlowchartW == null && panelW > 0)
                SizedBox(
                  width: panelW,
                  height: Responsive.screenH(context),
                  child: FittedBox(child: CommentsPanel(fbe)),
                ),
            ]),
          )
        ],
      ),
    );

**Comment by darshankawar** [comment] 2021-04-20 05:55
@biancashouse 
It seems to be from your production app, but it'll be great if a reproducible use case is provided to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment] 2021-05-12 11:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-12 11:42 UTC
Labels: in triage, waiting for customer response
