### ISSUE TITLE
url_launcher 4.0.2 is causing errors when executing on android.

### ISSUE THREAD

**Issue by bjconlan** [flutter/flutter#25131] opened 2018-12-09 10:49 UTC
## Steps to Reproduce

1. Using the [url_launcher](https://github.com/flutter/plugins/tree/master/packages/url_launcher) plugin:
run the example code calling `launch("tel://21213123123")`

(this issue is also documented on [stackoverflow](https://stackoverflow.com/questions/53497475/flutter-calling-startactivity-from-outside-of-an-activity-context-requires-th)

## Logs

```
[ +133 ms] W/.whitelabel_ap(12464): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
[   +6 ms] W/.whitelabel_ap(12464): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
[   +5 ms] W/.whitelabel_ap(12464): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
[   +2 ms] W/.whitelabel_ap(12464): Accessing hidden method Ljava/net/InetAddress;->isNumeric(Ljava/lang/String;)Z (light greylist, reflection)
[   +3 ms] W/.whitelabel_ap(12464): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
[ +182 ms] W/.whitelabel_ap(12464): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
[  +22 ms] W/.whitelabel_ap(12464): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
[        ] W/.whitelabel_ap(12464): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
[+6628 ms] E/MethodChannel#plugins.flutter.io/url_launcher(12464): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the
FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at io.flutter.plugins.urllauncher.UrlLauncherPlugin.onMethodCall(UrlLauncherPlugin.java:61)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.os.Looper.loop(Looper.java:160)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/MethodChannel#plugins.flutter.io/url_launcher(12464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[   +2 ms] E/flutter (12464): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
[        ] E/flutter (12464): PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you
want?, null)
[        ] E/flutter (12464): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
[        ] E/flutter (12464): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
[        ] E/flutter (12464): <asynchronous suspension>
[        ] E/flutter (12464): #2      launch (package:url_launcher/url_launcher.dart:66:19)
[        ] E/flutter (12464): #3      ContactItem.build.<anonymous closure> (package:whitelabel_app/screen/contacts_screen.dart:69:13)
[        ] E/flutter (12464): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
[        ] E/flutter (12464): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
[        ] E/flutter (12464): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] E/flutter (12464): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
[        ] E/flutter (12464): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
[        ] E/flutter (12464): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] E/flutter (12464): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
[        ] E/flutter (12464): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
[        ] E/flutter (12464): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
[        ] E/flutter (12464): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
[        ] E/flutter (12464): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
[        ] E/flutter (12464): #15     _invoke1 (dart:ui/hooks.dart:168:13)
[        ] E/flutter (12464): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

```

```
```

```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.0.0 at /home/bjc/Applications/flutter
    • Framework revision 5391447fae (9 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/bjc/Applications/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/bjc/Applications/android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /home/bjc/Applications/idea-IC-183.4284.148
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```

**Comment by bjconlan** [comment] 2018-12-09 10:57
I realize It's bad practice to overload issues, but I thought it should be also noted that when using 'sms:' and 'tel:' schemes it might be best to sanitize the 'url' since call/sms apps fail to load on ISO when spaces are included in url (which works fine on android). ie:
`tel:+61 3990 3939` ios ✗, android ✓.

**Comment by zoechi** [comment] 2018-12-09 13:39
Duplicate of #24866

**Closed by zoechi** 2018-12-09 13:39 UTC
