### ISSUE TITLE
[add2app] Webview Crashes When Preventing Open in New Tab

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#75760] opened 2021-02-10 04:10 UTC
## Steps to Reproduce

Flutter Webview crashes on certain devices when `NavigationDecision.prevent` is set for a link that opens a new tab. Crashes on debug and release builds on stable and beta channel.

**Expected results:** 
Clicking on link that opens a new tab should not navigate and not crash.

**Actual results:**
The app crashes.
Or, on devices that do not crash, the webview navigates to the new webpage even though navigation should be prevented.

**Steps to reproduce:**
1. Clone the demo repo (https://github.com/searchy2/FlutterWebviewLinkCrash) or use the precompile APK (https://github.com/searchy2/FlutterWebviewLinkCrash/raw/main/FlutterWebviewLinkCrash.apk)
2. Run sample app on a device that is known to crash. See list below.
3. Click the FAB button.
4. Click `Open external link`. App crashes.
5. Click `Open link in same window`. App does not crash.

https://user-images.githubusercontent.com/19896174/107462751-6a374800-6b22-11eb-94a0-c0b429db50e7.mp4

```
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
android.view.inputmethod.InputMethodManager.startInputInner (InputMethodManager.java:1625)
android.view.inputmethod.InputMethodManager.checkFocus (InputMethodManager.java:1864)
android.view.inputmethod.InputMethodManager.isActive (InputMethodManager.java:1183)
io.flutter.plugins.webviewflutter.InputAwareWebView$1.run (InputAwareWebView.java:188)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7386)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

The problem code is in `InputAwareWebView.java` line 161 - 191.
```
  private void setInputConnectionTarget(final View targetView) {
    if (containerView == null) {
      Log.e(
          TAG,
          "Can't set the input connection target because there is no containerView to use as a handler.");
      return;
    }

    targetView.requestFocus();
    containerView.post(
        new Runnable() {
          @Override
          public void run() {
            InputMethodManager imm =
                (InputMethodManager) getContext().getSystemService(INPUT_METHOD_SERVICE);
            // This is a hack to make InputMethodManager believe that the target view now has focus.
            // As a result, InputMethodManager will think that targetView is focused, and will call
            // getHandler() of the view when creating input connection.

            // Step 1: Set targetView as InputMethodManager#mNextServedView. This does not affect
            // the real window focus.
            targetView.onWindowFocusChanged(true);

            // Step 2: Have InputMethodManager focus in on targetView. As a result, IMM will call
            // onCreateInputConnection() on targetView on the same thread as
            // targetView.getHandler(). It will also call subsequent InputConnection methods on this
            // thread. This is the IME thread in cases where targetView is our proxyAdapterView.
            imm.isActive(containerView);
          }
        });
  }
```

**Crashed device list:**
Crash is not reproducible on every device all the time. For example, the app crashes everytime on one OnePlus 6T but not on another.
- OnePlus 6T A6013 
- LG Stylo 6
- LG Stylo 5
- LG G7 ThinQ
- LG K51
- LG LM-X525
- LG V40 ThinQ
- LG G8 ThinQ™
- Mi Note 10 Lite
- Redmi Note 7
- POCO X3 NFC
- HUAWEI Mate 20 lite
- HUAWEI P30 lite
- HUAWEI P30 lite
- Moto g stylus
- Moto g(7) power
- Moto g power
**Sample webpage**
https://codelesscdn.com/nocdtest/nocdapp/opentab.html

<details>
  <summary>Logs</summary>

```
Flutter 1.26.0-17.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 4b50ca7f7f (5 days ago) • 2021-02-04 19:44:27 -0800
Engine • revision 2c527d6c7e
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)
ray@MacBook-Pro flutter_module % flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
• Flutter version 1.26.0-17.3.pre at /Users/ray/Development/flutter
• Framework revision 4b50ca7f7f (5 days ago), 2021-02-04 19:44:27 -0800
• Engine revision 2c527d6c7e
• Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at /Users/ray/Development/Android/sdk
• Platform android-30, build-tools 29.0.3
• ANDROID_HOME = /Users/ray/Development/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.3, Build version 12C33
• CocoaPods version 1.10.0

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
• Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
```

</details>

**Comment by searchy2** [comment] 2021-02-10 04:12
One solution is to wrap the input manager in a null check. 

```
InputMethodManager imm =
    (InputMethodManager) getContext().getSystemService(INPUT_METHOD_SERVICE);
if (imm == null) return;
targetView.onWindowFocusChanged(true);
imm.isActive(containerView);
```

**Comment by searchy2** [comment] 2021-02-10 04:14
How would I go about making a PR for the Webview plugin with this fix?

**Comment by TahaTesser** [comment] 2021-02-10 11:09
Hi @searchy2 
This is not an issue in [hybrid composition](https://pub.dev/packages/webview_flutter#using-hybrid-composition) on Android and also on iOS which also uses hybrid composition

Can you try adding hybrid composition in it as follows and try again?

<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebviewPage extends StatefulWidget {
  final String url;

  WebviewPage({Key key, this.url}) : super(key: key);

  @override
  _WebviewPageState createState() => _WebviewPageState();
}

class _WebviewPageState extends State<WebviewPage> {
  BuildContext context;
  UniqueKey webViewKey;
  WebViewController webViewController;

  String url;
  bool loading = true;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

    this.context = context;
    this.url = widget.url;
    webViewKey = UniqueKey();
    SchedulerBinding.instance.addPostFrameCallback((_) {
      webViewController?.loadUrl(url);
    });
  }

  @override
  void dispose() {
    super.dispose();
  }

  void setLoading(bool loading) {
    this.loading = loading;
    print("Loading $loading");
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: Stack(
          children: <Widget>[
            WebView(
              key: webViewKey,
              onPageStarted: (_) => setLoading(true),
              onPageFinished: (_) => setLoading(false),
              onWebViewCreated: (controller) {
                print("Set Webview Controller");
                webViewController = controller;
              },
              initialUrl: url,
              javascriptMode: JavascriptMode.unrestricted,
              initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
              navigationDelegate: (NavigationRequest request) {
                String url = request.url;
                return NavigationDecision.navigate;
              },
            ),
            Center(
              child: Visibility(
                  visible: loading, child: CupertinoActivityIndicator()),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 4b50ca7f7f (5 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>



Thank you

**Comment by searchy2** [comment] 2021-02-10 16:40
Thanks for the suggestion @TahaTesser and I really appreciate your help triaging the issues.
Unfortunately, if hybrid composition ``WebView.platform = SurfaceAndroidWebView();` is enabled, then the webview page does not even load.

**Comment by TahaTesser** [comment] 2021-02-11 12:56
Hi @searchy2 
Thanks, I tried again with the hybrid composition, you're right.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.67, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-2.0.pre.67 at /Users/tahatesser/Code/flutter_master
    • Framework revision 78ce11d7e3 (6 hours ago), 2021-02-11 07:37:57 +0100
    • Engine revision cdc49c575b
    • Dart version 2.13.0 (build 2.13.0-25.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>


Thank you

**Comment by borislizak** [comment] 2021-03-18 19:25
HI @TahaTesser, @cyanglaz  do you have an ETA on the fix for this bug? Thank you!

**Comment by danagbemava-nc** [comment] 2021-08-16 13:36
Hi @searchy2, can you please confirm if you're still experiencing this issue? 
I tried to reproduce it with your repo but the url seems to be inactive so I'm unable to reproduce it.

![Screenshot_1629120766](https://user-images.githubusercontent.com/88313112/129572456-d26fc8e6-1302-418d-a7af-e25a76cedf4d.png)

**Comment by searchy2** [comment] 2021-08-17 05:37
Thanks for following up. I'll need to double check but my optimistic guess is that the issue is fixed.

**Comment by danagbemava-nc** [comment] 2021-08-17 06:05
@searchy2 Kindly do that at your earliest convenience and if you're still experiencing the issue kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by TahaTesser** [comment] 2021-09-08 09:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-08 09:58 UTC
Labels: severe: crash, platform-android, plugin, p: first party, a: existing-apps, p: webview, has reproducible steps, P4, severe: fatal crash, found in release: 1.22, found in release: 1.27
