### ISSUE TITLE
[add-to-app] error : Namespace not specified. Please specify a namespace in the module's build.gradle

### ISSUE THREAD

**Issue by LazyDave76** [flutter/flutter#126403] opened 2023-05-10 08:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a new android app and add a new flutter module to it using steps in option 2 : https://docs.flutter.dev/add-to-app/android/project-setup

run 'flutter pub get' in module to build .android folder

sync project in android studio

### Expected results

build is successful

### Actual results

app fails to build.  

Android studio is looking for 'namespace' setting in .android/build.gradle. adding a value manually makes the app build but this is a generated .android folder so any further runs of 'flutter pub get' to update dependencies remove any edits.

Error happens with 3.7.12-stable and 3.10.0-1.5.pre-beta

error output:

``` Script '/Users/xxx/.asdf/installs/flutter/3.12.7-stable/packages/flutter_tools/gradle/module_plugin_loader.gradle' line: 59

* What went wrong:
A problem occurred configuring root project 'Android'.
> A problem occurred configuring project ':flutter'.
   > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
      > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
        
        android {
            namespace 'com.example.namespace'
        }
        
        If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2 22D49 darwin-arm64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/xxxx/.asdf/installs/flutter/3.7.12-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • D4CEE1AF-4892-48B9-A9D2-80C1D5F6175A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available```

</details>

**Comment by huycozy** [comment] 2023-05-10 10:32
Hi @LazyDave76 
I checked this add-to-app demo on [my sample code](https://github.com/huycozy/Flutter-add-to-app-Android-native-sample) but can't see the issue. Can you try running it to see if the issue can occur or not?

**Comment by huycozy** [comment] 2023-05-10 11:29
It seems you are using AGP and Gradle version from 8.0 because I can see this issue when upgrading AGP to `8.0.0` and Gradle to `8.0`. Meanwhile, the worked version is AGP `7.2.0`/Gradle `7.3.3`.

This issue is reproducible on the latest `stable` and `master` channels. Labeling the issue for further insights. 

Sample code: [namespace-gradle-issue](https://github.com/huycozy/Flutter-add-to-app-Android-native-sample/tree/namespace-gradle-issue)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-2.0.pre.73, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-2.0.pre.73 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c5a1ea728 (7 hours ago), 2023-05-08 14:00:20 -0700
    • Engine revision 8d3a8162b3
    • Dart version 3.1.0 (build 3.1.0-86.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by reidbaker** [comment] 2023-05-10 15:06
Related to #125621 
I think this will be fixed by https://github.com/flutter/flutter/pull/126354.

**Comment by stuartmorgan** [comment] 2023-05-10 15:46
> I think this will be fixed by #126354.

Nope, that will only fix plugins.

I'm not familiar with the internals of the Android add-to-app, but I expect the namespace needs to be added to one or more of:
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/gradle/build.gradle.tmpl
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/deferred_component/build.gradle.tmpl
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/host_app_common/app.tmpl/build.gradle.tmpl
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/library_new_embedding/Flutter.tmpl/build.gradle.tmpl

**Comment by reidbaker** [comment] 2023-05-15 18:29
Using the tag 3.10.0-15.0.pre which I think is the latest stable I see the same behavior as master. 
```
mkdir fresh_create
flutter create --project-name=test_app --template=module fresh_create
cd fresh_create
flutter build apk
```

**Comment by stuartmorgan** [comment] 2023-05-15 18:34
You'd need to add the module to a non-Flutter-template app that's using AGP 8.0, if I'm understanding the issue correctly.

**Comment by stuartmorgan** [comment] 2023-05-15 18:34
You'd need to add the module to a non-Flutter-template app that's using AGP 8.0, if I'm understanding the issue correctly.

**Comment by reidbaker** [comment] 2023-05-15 18:57
Other things that probably should be fixed at the same time. 
* Compile/target sdk should be set to api 33
* settings.gradle.copy.tmpl have `evaluate(new File(settingsDir, 'include_flutter.groovy'))` which I think wont work with the move of our gradle files
* Min sdk version should be set to 19 (instead of 16) 
* `android:exported="true"` in manifest files

**Comment by reidbaker** [comment] 2023-05-15 19:08
🤦 there is an example. I will work off that

**Comment by reidbaker** [comment] 2023-05-15 19:22
To reproudce failure 
* checkout https://github.com/huycozy/Flutter-add-to-app-Android-native-sample/tree/namespace-gradle-issue
* cd my_flutter
* flutter pub get 
* flutter build aar 
* cd ..
* ./gradlew dependencies (or anything that gets a build going)

**Comment by reidbaker** [comment] 2023-05-15 20:07
Additional steps discovered 

Modify settings.gradle to include the path to your own dependencies (follow output from flutter build arr) 
Fix the host app to have a namespace (this is out of our control) `namespace 'com.example.addtoapp_androidnative'`

**Comment by reidbaker** [comment] 2023-05-15 20:36
Handing over to @camsim99 to keep this moving forward.

**Comment by camsim99** [comment] 2023-05-16 19:00
I was able to reproduce the issue and thanks to the reproduction example above and @reidbaker's suggestion to try the AGP upgrade assistant in Android Studio. I can confirm we need to add namespace to all of the `build.gradle` files in the module and in the `build.gradle` file for the app itself.

I believe I'll need to update the following:

- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/deferred_component/build.gradle.tmpl
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/gradle/build.gradle.tmpl
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/host_app_common/app.tmpl/build.gradle.tmpl

I'll work on verifying this and submitting a PR for the fix. I also will find a good place to add a note on the website in case folks run into this issue if anyone knows a good page offhand!

**Comment by camsim99** [comment] 2023-05-16 23:12
> I'll work on verifying this and submitting a PR for the fix. I also will find a good place to add a note on the website in case folks run into this issue if anyone knows a good page offhand!

Verified that modifying those works, so submitting PRs.

**Comment by milindgoel15** [comment] 2023-06-02 06:09
Is this fix for the namespace error pushed to stable?

**Comment by strongville** [comment] 2023-06-07 23:32
Sorry for commenting on a closed issue, but this still seems not included in stable version.

![changelog for Flutter 3.10.4](https://github.com/flutter/flutter/assets/1476503/e69e217a-1332-4366-8d62-2b4672e2da33)

The changelog for Flutter 3.10.4 mentions this as an included hotfix, but the error stated above still applies on this version, even when deleting manually the .android folder and running pub get again.

**Comment by camsim99** [comment] 2023-06-08 17:05
> Sorry for commenting on a closed issue, but this still seems not included in stable version.
> 
> ![changelog for Flutter 3.10.4](https://user-images.githubusercontent.com/1476503/244223450-e69e217a-1332-4366-8d62-2b4672e2da33.png)
> 
> The changelog for Flutter 3.10.4 mentions this as an included hotfix, but the error stated above still applies on this version, even when deleting manually the .android folder and running pub get again.

I believe this is true and the fix is not part of Flutter 3.10.4. Sorry about the confusion!

**Comment by MrCsabaToth** [comment] 2023-06-12 18:28
> I was able to reproduce the issue and thanks to the reproduction example above and @reidbaker's suggestion to try the AGP upgrade assistant in Android Studio. I can confirm we need to add namespace to all of the `build.gradle` files in the module and in the `build.gradle` file for the app itself.

I'm battling with this, I have a Flutter app. The upgrade agent / scripts removed the namespace from the manifest and added it to the app's `build.gradle`. The "namespace" is also present in the same `build.gradle` under the android > defaultConfig > applicationId. What module are we talking about? My app is not complicated but I count 18 modules, which are effectively Flutter plugins I depend on which that native Android parts. I'm afraid to ask (or even think about it) but am I supposed to interfere and fiddle with those 18 build.gradle files of those plugins to make this error go away?

All of the StackOverflow entries I found so far are garbage, I suspected my case would be quite common. People advise to simply remove the namespace (going against the error message) and similar things.

**Comment by camsim99** [comment] 2023-06-12 20:47
> I'm battling with this, I have a Flutter app. The upgrade agent / scripts removed the namespace from the manifest and added it to the app's `build.gradle`. The "namespace" is also present in the same `build.gradle` under the android > defaultConfig > applicationId. What module are we talking about? My app is not complicated but I count 18 modules, which are effectively Flutter plugins I depend on which that native Android parts. I'm afraid to ask (or even think about it) but am I supposed to interfere and fiddle with those 18 build.gradle files of those plugins to make this error go away?
> 
> All of the StackOverflow entries I found so far are garbage, I suspected my case would be quite common. People advise to simply remove the namespace (going against the error message) and similar things.

In Flutter modules, you need to ensure that `.andriod/build.gradle`, `.android/app/build.gradle`, and `.android/Flutter/build.gradle` files have the `namespace` property in the `android` block to get rid of the error. I'm not sure if your Flutter plugins are part of the issue. Plugin templates should have received a similar fix in https://github.com/flutter/flutter/pull/126354 as plugins also need the property in the `android` block in their `build.gradle` file for AGP 8 compatibility.

**Comment by camsim99** [comment] 2023-06-12 20:48
Closing this issue as this is fixed in `master`. https://github.com/flutter/flutter/issues/128136 filed for the cherry-pick to stable.

**Closed** 2023-06-12 20:48 UTC
Labels: platform-android, tool, a: existing-apps, has reproducible steps, P3, found in release: 3.7, found in release: 3.11

**Comment by AnhDTN** [comment] 2023-06-14 10:43
@camsim99 i was checkout master branch and still got the same error

**Comment by camsim99** [comment] 2023-06-16 19:39
@MrCsabaToth Thank you for in-depth explanation! You make a great point about developers discovering this issue in ways not directly related to using Flutter in an add-to-app context.

If you would be open to it, we would be greatly appreciative for you to answer questions about this with essentially your explanation above if you run into them so that developers can see the solution more clearly. For example:

- https://stackoverflow.com/questions/76186824/flutter-plugins-crashing-on-android-studio-flamingo-with-gradle-8-0-0
- https://stackoverflow.com/questions/76249597/flutter-firebase-app-not-running-on-android-namespace-not-specified

**Comment by camsim99** [comment] 2023-06-16 19:41
> @camsim99 i was checkout master branch and still got the same error

This is a fix for the `build.gradle` templates. You may need to re-create your Flutter modules if you still see the issue. If you are not using Flutter in an add-to-app context, see @MrCsabaToth's [explanation](https://github.com/flutter/flutter/issues/126403#issuecomment-1591486226) above!
