### ISSUE TITLE
SelectionArea spaces missing between Text widgets

### ISSUE THREAD

**Issue by c-lucera-pvotal** [flutter/flutter#111396] opened 2022-09-12 15:20 UTC
## Steps to Reproduce
1. Create a new project and paste in main.dart the following code https://gist.github.com/c-lucera-pvotal/421bc6038ce7855321ab215c6f186ae7
2. Run the project on any platform with `flutter run`.
3. Select the three line of text at once and copy it.
4. Paste the text somewhere.

**Expected results:** 
The 3 text should be separated, either with a new line or a space, ie

_**Line1 Line2 Line3**_ 

or

_**Line1 
Line2
Line3**_

**Actual results:** 
The text is pasted without anyspace

**_Line1Line2Line3_**

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SelectableWidget(),
    );
  }
}

class SelectableWidget extends StatelessWidget {
  const SelectableWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SelectionArea(
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: const [
              Text("Line1"),
              Text("Line2"),
              Text("Line3"),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
No relevant logs
```

```
l~/projects/selection_area_multiple_line$ flutter analyze
Analyzing selection_area_multiple_line...                               
No issues found! (ran in 1.2s)
~/projects/selection_area_multiple_line$ 

```

```
~/projects/selection_area_multiple_line$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale en-IT)
    • Flutter version 3.3.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pvotaltech.jfrog.io/artifactory/api/pub/pvotal-pub

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/clucera/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by exaby73** [comment] 2022-09-12 20:53
Hello @c-lucera-pvotal. I cannot reproduce this issue on the latest stable `3.3.1`. See attached screenshot.

<details>
<summary>Screenshot</summary>

![brave_9zkcHDpqf3](https://user-images.githubusercontent.com/50555895/189756404-7b20ff92-936a-470f-87ea-3e672bafbd99.png)

</details>

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.918], locale en-US)
    • Flutter version 3.3.1 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (5 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by c-lucera-pvotal** [comment] 2022-09-13 06:18
Hello @exaby73 the "copy" part is correct, the issue is that after copying if you try to paste it somewhere the resulting text should have at least a space between the text, instead it is all crammed up! 

please check this attached video:

https://user-images.githubusercontent.com/91328643/189824502-9f588e7d-c942-4895-b141-3378e6248216.mov

Of course it would be best that the Copy will keep also the new lines, but at least the text should be separated by a space after pasting, but this doesn't happens

**Comment by exaby73** [comment] 2022-09-13 07:05
Duplicate of https://github.com/flutter/flutter/issues/104548

**Closed by exaby73** 2022-09-13 07:05 UTC
Labels: in triage
