### ISSUE TITLE
How to embeded flutter to desktop app?

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#91226] opened 2021-10-04 12:58 UTC
hi,all:

We know currently flutter already supports embed to existing mobile application(android & ios), but I am not sure how to do it on desktop(macos &windows), also no any documents found.

**Comment by TahaTesser** [comment] 2021-10-04 13:05
Hi @imiskolee 
There is no support for this yet, closing as duplicate of https://github.com/flutter/flutter/issues/80339

**Closed by TahaTesser** 2021-10-04 13:05 UTC
Labels: in triage
