### ISSUE TITLE
ColorFiltered conflicts with iOS UiKitView

### ISSUE THREAD

**Issue by Mauiie** [flutter/flutter#61137] opened 2020-07-09 01:33 UTC
#### This problem can be reproduced very well on webview_flutter. My local other iOS PlatfrormView also has the same problem and cannot be displayed normally.

The following is the code I tested on webview_flutter example

`void main() => runApp(ColorFiltered(colorFilter: ColorFilter.mode(Colors.grey, BlendMode.color), child: MaterialApp(home: WebViewExample())));`

**Expected results:** 
I expect iOS to display an application with gray filters like Android

**Actual results:** 
In fact, UiKitView has become invisible and has become a solid color
<details>
  <summary>Logs</summary>

```
webview_flutter version is 0.3.22
```

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/wangxin/Library/flutter/flutter
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangxin/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • ELE AL00  • GBGDU19821001370                     • android-arm64 • Android
      10 (API 29)
    • iPhone 11 • 78C31319-E917-49FD-AE0D-D9B58C500E01 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-09 08:27
Reproduces with current master `1.20.0-3.0.pre.192`.
Used iOS 13.5 simulator and latest webview_flutter: ^0.3.22+1

**Comment by Mauiie** [comment] 2020-07-17 03:12
Is there any way to solve this problem quickly?

**Comment by RichardJCai** [comment] 2020-09-16 20:16
Did some initial investigations:

It seems like the reason the WebView becomes invisible is because the ColorFilter is applying to the OverlayView (the outermost layer in the image below) which blocks out the WebView. The OverlayView becomes opaque after being painted over and covers the layers below it.

Another interesting thing to note is that the ColorFilter is also applying to the FlutterView (the deepest layer in the image below), this does not seem to happen when the widget is not a PlatformView, tested with Text and the ColorFilter does not apply to the FlutterView.

![image](https://user-images.githubusercontent.com/25163644/93387473-4b64ac00-f837-11ea-92be-bc1242f8a5e5.png)

@iskakaushik

**Comment by iskakaushik** [comment] 2020-09-16 20:35
Some additional observations. This is because we call `saveLayer` in `color_filter_layer.cc` during `Paint`, which in-turn paints the internal node canvas of the latest offscreen layer. Given that skia isn't aware of the underlying platform view. We would likely need to do something along the lines of:

1. During pre-roll for all the single child parents of the platform view collect the intended mutations.
2. During paint avoid doing any skia operations on the aforementioned layers.
3. Apply the collected mutations during external_view_embedder->Submit.

cc: @liyuqian , @cyanglaz

**Comment by cyanglaz** [comment] 2020-09-17 02:31
cc @blasten It might be related to unobstructed platform view. (Only based on guessing)

**Comment by FernandoUFS** [comment] 2021-07-17 22:46
Is there any update for this issue? I am using Flutter v2.2.3 (stable) and I still have this problem, my application uses ColorFiltered on the screen's header and I can't put a webview anywhere.

**Comment by cyanglaz** [comment] 2022-05-26 17:59
Closing as a duplicate of https://github.com/flutter/flutter/issues/39270

**Closed by cyanglaz** 2022-05-26 17:59 UTC
Labels: platform-ios, engine, a: platform-views, has reproducible steps, P4, found in release: 1.20
