### ISSUE TITLE
GoRouter - DraggableScrollableSheet not allowing gestures to widgets in shell route. 

### ISSUE THREAD

**Issue by ignicubeLaeeq** [flutter/flutter#153673] opened 2024-08-19 06:44 UTC
### Steps to reproduce

1. Create a DraggableScrollableSheet. 
2. Place it in a shell route. 
3. Add some gesture detecting widgets like TextField in the shell route. 
4. Click on the widget in the shell route. 

### Expected results
DraggableScrollableSheet should behave the same with or without a shell route. 
The widgets on the shell route should respond to gestures as intended. 
IgnorePointer should not be used on the child to allow the gestures to widgets in the shell. 
Gestures on the child should behave independently from the gestures on the shell for example a map widget in the shell widget should not be scrolled if the list in the DraggableScrollableSheet (child) is scrolled. 

### Actual results
No gestures detected on parent. 
IgnoPointer would swipe the map if the list on DraggableScrollableSheet is scrolled. 
(Similar ticket which was previously closed for reference: [#136206](https://github.com/flutter/flutter/issues/136206))

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-08-20 07:50
It's explained as WAI (work as intended) at https://github.com/flutter/flutter/issues/136206#issuecomment-1760142316. You can see it's an implementation issue as the issue is represented with an equivalent code by Stack there.

Closing this as a duplicate.

**Closed by huycozy** 2024-08-20 07:50 UTC
Labels: in triage
