### ISSUE TITLE
Keyboard on android webview_flutter does not dismiss while input element blurs.

### ISSUE THREAD

**Issue by hhkkyy** [flutter/flutter#36250] opened 2019-07-16 10:42 UTC
Flutter1.7.8+hotfix.3 fix problem that android keyboard does not display in webview, but remains a problem that the keyboard does not dismiss while input element blurs.
![keyboard_dismiss](https://user-images.githubusercontent.com/19389352/61288023-d9d73b00-a7f8-11e9-829d-08641597fe68.gif)

The keyboard in gif is dismissed by clicking back button, it ramains displayed while input blurs.

**Comment by lakshyab1995** [comment] 2019-07-17 13:26
> Flutter1.7.8+hotfix.3 fix problem that android keyboard does not display in webview, but remains a problem that the keyboard does not dismiss while input element blurs.
> ![keyboard_dismiss](https://user-images.githubusercontent.com/19389352/61288023-d9d73b00-a7f8-11e9-829d-08641597fe68.gif)
> 
> The keyboard in gif is dismissed by clicking back button, it ramains displayed while input blurs.

It's happening for me also, early response would be helpful.

**Comment by mklim** [comment] 2019-07-18 20:20
Closing as a duplicate of flutter/flutter#36478

**Closed by mklim** 2019-07-18 20:20 UTC
