### ISSUE TITLE
Silent crash on hot reload

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#43361] opened 2019-10-23 17:58 UTC
Interestingly, running from an IDE gives us no problem at all and everything works as expected. However, when running via `flutter run -v` from the command line:

When performing a hot reload with no actual code changes, the reload is "successful" (no crash). When performing a hot reload with any changes that are in the currently visible UI, the app crashes with no warning or output.
This behavior seems very similar to the behavior reported by others (for example in https://github.com/flutter/flutter/issues/40361), but we get zero output whatsoever, unlike what others have noted.

How can we investigate further?

(Please add the customer tag `octopod`)

```
Flutter 1.10.14-pre.3 • channel unknown • unknown source
Framework • revision fa4d31b311 (2 weeks ago) • 2019-10-07 10:05:40 -0700
Engine • revision 1d62160fdb
Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)
```

**Comment by r0hnx** [comment] 2019-10-23 18:44
Which IDE are you using ?

**Comment by mtcliatt** [comment] 2019-10-23 18:48
VSCode

**Comment by HansMuller** [comment] 2019-10-25 15:31
CC @jonahwilliams - I think you're looking at this problem already..

**Comment by mtcliatt** [comment] 2019-10-25 18:02
IntelliJ also works, leading us to think the problem is only when running via command line.

**Comment by jonahwilliams** [comment] 2019-10-25 18:44
@mtcliatt   My best guess is that some part of the tooling is plumbing through --track-widget-creation, and some other part isn't. Can you try manually enabling it via the command line to see if that fixes the issue?

**Comment by jonahwilliams** [comment] 2019-10-25 18:44
Will also be helped by https://github.com/flutter/flutter/pull/43471

**Comment by mtcliatt** [comment] 2019-10-31 18:23
@jonahwilliams Thanks for the info, I'm going to try out `--track-widget-creation` today.

In the mean time, here's more detail on what we're seeing: I observed that when trying to hot restart on macOS from the command line, the app won't crash, but no changes are made. However, if I pass `--debug` when starting the application (which should be our default anyways), I can see the changes!

**Comment by mtcliatt** [comment] 2019-10-31 19:57
Actually, scratch that, hot restart isn't working for me at all.

Also, it seems that hot reload is now completely broken for us, from both IDEs and from the command line. We think this was a regression picked up in our latest Flutter roll (which put us at ed36fe5ddd).

**Comment by jonahwilliams** [comment] 2019-11-02 20:46
The cause of this failure was a change to the tool that made the observatory string detection not case-sensitive. The fix was project specific and has landed.

**Comment by jonahwilliams** [comment] 2019-11-04 21:19
The observatory string solution seems to occasionally not work, this needs  a tooling update to specify the port

**Comment by jonahwilliams** [comment] 2019-11-04 21:34
Fixed by https://github.com/flutter/flutter/pull/44027

**Comment by mtcliatt** [comment] 2019-11-06 22:35
We're seeing the observatory string change not working 100% of the time except under very specific circumstances where it works 100% of the time:

1. Be on a Mac _**desktop**_
2. Start our app (doesn't matter if via command line or IDE)
3. Before making any code changes or attempting to hot reload, perform a hot restart.
4. Hot reload should work, hot restart will pretend to work but not actually work.

**Comment by jonahwilliams** [comment] 2020-01-09 17:38
I believe this is fixed now - can you confirm @mtcliatt  ?

**Comment by JankoLancer** [comment] 2020-01-10 09:22
This is not fixed, I have this problem too.

**Comment by jonahwilliams** [comment] 2020-01-24 19:04
Closing as fixed.  @JankoLancer "I have this problem to" is not an appropriate way to comment on an issue. Please see the new issue template for an overview of some of the information needed to reproduce and fix an issue

**Closed by jonahwilliams** 2020-01-24 19:04 UTC
Labels: customer: octopod, t: hot reload, tool
