### ISSUE TITLE
Animation controller bugs

### ISSUE THREAD

**Issue by VoidZzzz** [flutter/flutter#126984] opened 2023-05-17 03:31 UTC
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 829 pos 12:
'elapsedInSeconds >= 0.0': is not true.

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:829:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1079:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1077:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:994:5)
#9      _invoke1 (dart:ui/hooks.dart:167:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:296:5)
#11     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:538:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:752:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:619:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:467:12)
#8      new InkSplash (package:flutter/src/material/ink_splash.dart:140:9)
#9      _InkSplashFactory.create (package:flutter/src/material/ink_splash.dart:62:12)
#10     _InkResponseState._createInkFeature (package:flutter/src/material/ink_well.dart:970:72)
#11     _InkResponseState._startNewSplash (package:flutter/src/material/ink_well.dart:1055:42)
#12     _InkResponseState.handleTapDown (package:flutter/src/material/ink_well.dart:1035:5)
#13     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:596:61)
#14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#15     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:596:11)
#16     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:297:5)
#17     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:274:7)
#18     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:264:25)
#19     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:244:31)
(elided 4 frames from class _FrameCallbackEntry and dart:async)

**Comment by danagbemava-nc** [comment] 2023-05-17 09:25
There are existing issues describing your error in https://github.com/flutter/flutter/issues/106277 & https://github.com/flutter/flutter/issues/88563

Closing from here as a duplicate of the issues linked above. If your issue does not reproduce or match any of the situations in the issues listed above, kindly file a new issue and provide the information requested for in the bug template. 

Thank you

**Closed by danagbemava-nc** 2023-05-17 09:25 UTC
Labels: in triage
