### ISSUE TITLE
[web] Image.network() requests an image every screen redraw when caching is disabled in the browser

### ISSUE THREAD

**Issue by Sammius** [flutter/flutter#53415] opened 2020-03-27 14:01 UTC
![rec-2](https://user-images.githubusercontent.com/29778745/77762983-0b203000-7043-11ea-813a-55f9536f1e36.gif)

My code:
```
@override
Widget build( BuildContext context ) => Scaffold(
      body: Image.network( 'https://upload.wikimedia.org/wikipedia/en/7/7b/Image_in_Glossographia.png' )
);
```

flutter doctor -v:
```
[✓] Flutter (Channel master, v1.16.3-pre.64, on Mac OS X 10.15.3 19D76, locale en-CY)
    • Flutter version 1.16.3-pre.64 at /Users/sammius/Flutter/flutter
    • Framework revision 8afc67f7f8 (16 hours ago), 2020-03-26 17:36:03 -0400
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sammius/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sammius/android
    • ANDROID_SDK_ROOT = /Users/sammius/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.7402

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by Sammius** [comment] 2020-03-29 06:50
Maybe this is the related Issue #47125

**Comment by ferhatb** [comment] 2020-03-31 16:52
Duplicate of #47125

**Closed** 2020-03-31 16:52 UTC
Labels: a: images, has reproducible steps, platform-web
