### ISSUE TITLE
dartpad code in documentation isn't updated with the version

### ISSUE THREAD

**Issue by noamraph** [flutter/flutter#89319] opened 2021-09-01 19:56 UTC
I tried to see the example at https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html and got an error.

I clicked the documentation link, which sent me to https://github.com/flutter/flutter/blob/f4abaa0735/packages/flutter/lib/src/widgets/animated_size.dart#L52.

Also, the footer says "f4abaa0735".

I discovered that the code in the documentation in this file does work. It includes

```
/// class _MyStatefulWidgetState extends State<MyStatefulWidget> with SingleTickerProviderStateMixin
...
///           vsync: this,
```

while the code in the inline dartpad didn't include this, and failed to compile because vsync wasn't defined.

It took me some time to realize that - I actually managed to fix the problem by myself, and wanted to send a pull request fixing the example, and then I discovered that the code was actually OK.

Thanks,
Noam

**Comment by TahaTesser** [comment] 2021-09-02 07:21
Hi @noamraph 
`vsync` is removed in later channels, dartpad runs on stable Flutter channel
duplicate of https://github.com/flutter/flutter/issues/83606 and see https://github.com/flutter/flutter/pull/83661 for more details

**Closed by TahaTesser** 2021-09-02 07:21 UTC
Labels: in triage
