### ISSUE TITLE
Flutter fix in IDE

### ISSUE THREAD

**Issue by llh-him** [flutter/flutter#77504] opened 2021-03-07 08:20 UTC
I have upgraded to flutter 2, and both VS Code and Android Studio got the latest plugin of flutter and dart. However, I could not find the function mentioned in flutter fix.

I am using the Crostini to run VS Code and Android Studio.

**Comment by Karlooie** [comment] 2021-03-07 09:31
same here, in VScode. 
![image](https://user-images.githubusercontent.com/10740439/110235395-0ee55380-7f30-11eb-9bad-2fdac15525b4.png)

flutter doctor output:

[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale en-GB)
    • Flutter version 2.0.0 at C:\src\flutter
    • Framework revision 60bd88df91 (4 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\carlo\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\carlo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\carlo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

**Comment by jobi-li** [comment] 2021-03-07 11:10
> same here, in VScode.
> ![image](https://user-images.githubusercontent.com/10740439/110235395-0ee55380-7f30-11eb-9bad-2fdac15525b4.png)
> 
> flutter doctor output:
> 
> [√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale en-GB)
> • Flutter version 2.0.0 at C:\src\flutter
> • Framework revision [60bd88d](https://github.com/flutter/flutter/commit/60bd88df915880d23877bfc1602e8ddcf4c4dd2a) (4 days ago), 2021-03-03 09:13:17 -0800
> • Engine revision 40441def69
> • Dart version 2.12.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\Users\carlo\AppData\Local\Android\Sdk
> • Platform android-29, build-tools 29.0.3
> • ANDROID_HOME = C:\Users\carlo\AppData\Local\Android\Sdk
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 44.0.2
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.54.1)
> • VS Code at C:\Users\carlo\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.20.0

Thanks for your reply. I am just wondering am I the only one who faces this issue since I could not find anyone getting such issue.

**Comment by pedromassangocode** [comment] 2021-03-08 08:09
Hi @llh-him 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

About the IntelliJ/Android Studio plugin
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed** 2021-03-08 08:09 UTC

**Comment by Karlooie** [comment] 2021-03-08 09:07
I opened the issue at [the suggested repository](https://github.com/Dart-Code/Dart-Code/issues/3186)

However, may be @llh-him  is having the same problem in Android Studio?

> I have upgraded to flutter 2, and both VS Code and Android Studio got the latest plugin of flutter and dart. However, I could not find the function mentioned in flutter fix.
> 
> I am using the Crostini to run VS Code and Android Studio.


If it is so, the dart-code repository [recommend](https://github.com/Dart-Code/Dart-Code/issues/new/choose) to follow the issue in flutter repository?

> Flutter SDK Issues
> Issues relating to Flutter that can be reproduced in IntelliJ/Android Studio or the command line should be reported in the Flutter SDK repository
