### ISSUE TITLE
Flutter doctor hangs and then finally prints: Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8

### ISSUE THREAD

**Issue by markushedvall** [flutter/flutter#16708] opened 2018-04-18 11:29 UTC
I have been trying to install Flutter and followed the instructions to install Flutter on macOS. Running ‘Flutter doctor’ with verbose flag first runs for a while until printing:

`Downloading Gradle Wrapper...                                1.2s`

Then it hangs for about 40 minutes and finally exits and prints:

`Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.`

I’m not sure if this is related to https://github.com/flutter/flutter/issues/12349, but with the lack of output I don’t know what is causing it and didn’t find any workaround.

Full log:
 ```
~ $ flutter doctor --verbose
Downloading Dart SDK from Flutter engine 8a6e64a8ef09f1f1af207725b40022d8d7a9dcd7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.7M  100 44.7M    0     0  2393k      0  0:00:19  0:00:19 --:--:-- 7448k
Building flutter tool...
Downloading Material fonts...                                1.7s
Downloading package sky_engine...                            1.4s
Downloading common tools...                                  2.2s
Downloading darwin-x64 tools...                              5.6s
Downloading android-arm-profile/darwin-x64 tools...          2.2s
Downloading android-arm-release/darwin-x64 tools...          2.2s
Downloading android-arm64-profile/darwin-x64 tools...        2.3s
Downloading android-arm64-release/darwin-x64 tools...        2.1s
Downloading android-x86 tools...                             4.1s
Downloading android-x64 tools...                             3.8s
Downloading android-arm tools...                             2.7s
Downloading android-arm-profile tools...                     2.4s
Downloading android-arm-release tools...                     2.5s
Downloading android-arm64 tools...                           2.6s
Downloading android-arm64-profile tools...                   2.5s
Downloading android-arm64-release tools...                   2.5s
Downloading ios tools...                                     5.8s
Downloading ios-profile tools...                             5.9s
Downloading ios-release tools...                             5.4s
Downloading Gradle Wrapper...                                1.2s
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
```

**Comment by Hixie** [comment] 2018-05-23 21:14
We believe this is fixed now. If you still see it, please file a new bug and we'll look into it.

**Closed by Hixie** 2018-05-23 21:14 UTC

**Comment by shabeer3508** [comment] 2018-06-13 06:34
`[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
exit code 255`
i have the same issue

**Comment by zoechi** [comment] 2018-06-13 07:48
@shabeer3508 the issue is closed. It's probably better to create a new issue with full information (`flutter doctor` output, information how to reproduce if possible, ...)
