### ISSUE TITLE
Navigator 2.0 support for CupertinoTabView

### ISSUE THREAD

**Issue by sunndog** [flutter/flutter#83039] opened 2021-05-20 17:27 UTC
## Use case

I would like to use Navigator 2.0 to deep link into a stack of pages within a CupertinoTabView.  I am currently looking at using https://pub.dev/packages/routemaster for a simple API which is built on top of Navigator.  The developer of that plugin indicates that he cannot include nested Navigators within CupertinoTabView because it does not support Navigator 2.0.

## Proposal

Please make the CupertinoTabView support Navigator 2.0

**Comment by webnickell** [comment] 2022-08-16 20:24
Any updates? Now I need to create self-written wrapper for api like `Navigator(pages: []) `.
Maybe, if I'll write fork for this feature, could we merge it it master?

**Comment by johnpryan** [comment] 2022-08-16 20:36
Closing as a duplicate of https://github.com/flutter/flutter/issues/99126 - you can see the latest progress on this feature in this PR: https://github.com/flutter/packages/pull/2453

**Closed by johnpryan** 2022-08-16 20:36 UTC
Labels: new feature, framework, f: cupertino, f: routes, passed first triage

**Comment by webnickell** [comment] 2022-08-16 20:57
So, if anyone like me don't use helper packages for Navigator 2.0 like go_router or anything else. You can just don't use  CupertinoTabView, because it's `build` method contain this implementation 
```
  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: widget.navigatorKey,
      onGenerateRoute: _onGenerateRoute,
      onUnknownRoute: _onUnknownRoute,
      observers: _navigatorObservers,
      restorationScopeId: widget.restorationScopeId,
    );
  }
```
So, you can just use Navigator in Cupertino tabs 
```
Navigator(
  pages: [
    CupertinoPage(
      child: YourScreen()
    )
  ],
);
```
