### ISSUE TITLE
MissingPluginException while adding to existing iOS application

### ISSUE THREAD

**Issue by anuranBarman** [flutter/flutter#23832] opened 2018-11-01 17:16 UTC
I am trying to add flutter to existing ios app. So before adding to the production app i decided to bring it some demo app. The flutter app independent is working fine in both android and ios. Even in the existing ios app its working fine except the plugin. I followed the tutorial and ran all commands like
**flutter run**,**flutter clean** but nothing made it to work in the existing app. when doing the **pod install** it's showing that it's adding the plugin and fetching the related files for it but when I am using the app its throwing the below error
```
2018-11-01 22:31:44.193838+0530 EgluDiscoverIOS[8186:2926742] flutter: Observatory listening on http://127.0.0.1:53871/
2018-11-01 22:31:49.533104+0530 EgluDiscoverIOS[8186:2926733] [VERBOSE-2:shell.cc(188)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      canLaunch (package:url_launcher/url_launcher.dart:88:25)
<asynchronous suspension>
#2      AssistantWidget.build._launchUrl (package:eglu_discover_final/assistant.dart:90:17)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:20)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:117:22)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:97:7)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:60:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:44:7)
#14     _invoke1 (dart:ui/hooks.dart:159:13)
#15     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
2018-11-01 22:32:05.187471+0530 EgluDiscoverIOS[8186:2926733] [VERBOSE-2:shell.cc(188)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      canLaunch (package:url_launcher/url_launcher.dart:88:25)
<asynchronous suspension>
#2      UpdateCard._launchUrl (package:eglu_discover_final/update_card.dart:10:17)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:20)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:117:22)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:97:7)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:60:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:44:7)
#14     _invoke1 (dart:ui/hooks.dart:159:13)
#15     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```
below is my AppDelegate.swift
```swift
import UIKit
import Flutter
import FlutterPluginRegistrant

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate,FlutterAppLifeCycleProvider {
    
    let lifeCycleDelegate=FlutterPluginAppLifeCycleDelegate()
    
    func addApplicationLifeCycleDelegate(_ delegate: FlutterPlugin) {
        lifeCycleDelegate.add(delegate)
    }
    
    var rootFlutterViewController:FlutterViewController? {
        let viewController = UIApplication.shared.keyWindow?.rootViewController
        if viewController!.isKind(of: FlutterViewController.self) {
            return viewController as? FlutterViewController
        }
        return nil
    }
    
    
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        if launchOptions == nil {
            return true
        }else {
            GeneratedPluginRegistrant.register(with: self as? FlutterPluginRegistry)
            return lifeCycleDelegate.application(application, didFinishLaunchingWithOptions: launchOptions!)
        }
    }
    
    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
        lifeCycleDelegate.applicationWillResignActive(application)
    }
    
    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
        lifeCycleDelegate.applicationDidEnterBackground(application)
    }
    
    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
        lifeCycleDelegate.applicationWillEnterForeground(application)
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
        lifeCycleDelegate.applicationDidBecomeActive(application)
    }
    
    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        lifeCycleDelegate.applicationWillTerminate(application)
    }
    
    
}
```
I am trying to use this plugin https://pub.dartlang.org/packages/url_launcher

**Comment by zoechi** [comment] 2018-11-01 17:43
Please add the output of `flutter doctor -v`.

**Comment by anuranBarman** [comment] 2018-11-01 17:47
output of flutter doctor
```
[✓] Flutter (Channel master, v0.10.2-pre.47, on Mac OS X 10.14 18A391, locale
    en-IN)
    • Flutter version 0.10.2-pre.47 at /Users/anuranbarman/Downloads/flutter
    • Framework revision 9dfc0f3aaa (8 days ago), 2018-10-24 07:22:08 +0100
    • Engine revision 2586e94122
    • Dart version 2.1.0-dev.7.1.flutter-45f9462398

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/anuranbarman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Anuran’s iPhone • e6c885b71bce76ca1Dfa3a15c4a3b5136b516b5d0 • ios • iOS
      12.0.1

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-12 20:53
Try running `flutter clean` and `flutter packages upgrade`.

If it doesn't help look up `url_launcher` in `.packages` and delete the associated path ` ~/.pub-cache/hosted/pub.dartlang.org/url_launcher-*` and run above commands again.

**Comment by zoechi** [comment] 2018-12-28 09:10
Duplicate of #16819

**Closed by zoechi** 2018-12-28 09:10 UTC
Labels: a: existing-apps, p: first party, plugin, severe: crash, waiting for customer response, ⌺‬ platform-ios

**Comment by jeffweilee** [comment] 2019-03-08 09:30
Hi @anuranBarman 
I am also trying to add flutter to existing ios app. I used your  AppDelegate.swift but having problem ``import FlutterPluginRegistrant`` 
**No such module 'FlutterPluginRegistrant'.**
I've tried ``pod install`` but there is no FlutterPluginRegistrant anywhere.
Do you have any ideas?


[✓] Flutter (Channel master, v1.3.9-pre.20, on Mac OS X 10.14 18A391, locale zh-Hant-TW)
    • Flutter version 1.3.9-pre.20 at /Users/icmdtsmc/flutter
    • Framework revision 77142b8257 (3 hours ago), 2019-03-07 22:18:15 -0800
    • Engine revision a48cd16e07
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone 7 • 17FEA699-9AD8-4062-BC9C-471BC50CF11B • ios • iOS 12.1 (simulator)

**Comment by poos** [comment] 2019-05-15 11:50
I have a common problem.

1. The simulator is normal, but the real machine will have errors


`
Command PhaseScriptExecution failed with a nonzero exit code`



2. I commented out the embed element in Run Scriot in Xcode


```

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
#"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

```


There is another error in the console when the machine is running:

```

2019-05-15 19:34:43.038873+0800 zhima[1354:88077] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2019-05-15 19:34:43.253524+0800 zhima[1354:88324] [VERBOSE-2:engine.cc(117)] Engine run configuration was invalid.
2019-05-15 19:34:43.253795+0800 zhima[1354:88324] [VERBOSE-2:FlutterEngine.mm(304)] Could not launch engine with configuration.
2019-05-15 19:34:43.426946+0800 zhima[1354:88331] flutter: Observatory listening on http://127.0.0.1:59545/xJdO9DgNi04=/

```

**Comment by poos** [comment] 2019-05-28 02:44
maybe your mac have two or more certificate in keychain.
delete one of you didn't need.

https://github.com/flutter/flutter/issues/32134

**Comment by Alok81234881** [comment] 2020-07-28 02:49
I am having the same issue. 
have you found any solution for this? @anuranBarman

**Comment by mugbug** [comment] 2021-03-08 22:50
I had a similar one and it took me a while to figure out the problem. So here's what I did:
- On iOS-side:
```swift 
// instead of using `initialRoute`
engine.run(withEntrypoint: nil, initialRoute: route)

// switch to default
engine.run()
```

- On Flutter-side
```dart
void main() => runApp(App());

class App extends StatelessWidget {
   App({Key key}) : super(key: key);

   @override
   Widget build(BuildContext context) {
     return MaterialApp(
       // instead of expecting the iOS to invoke a route
       routes: {
         '/some_custom_route': (c) => MyCustomScreen(),
       }
       // set your screen as the `home`, once you won't be inputing a custom route name
       home: MyCustomScreen(),
     );
   }
 }
```

> Note: probably there's a way to keep using route names when running the engine, but I still need to dig a little deeper to figure that out.
