### ISSUE TITLE
App with no main function fails without a "no main function" message

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#19167] opened 2018-07-09 15:22 UTC
Instead it just hangs after printing some obscura about running its isolate:

```
$ (cd ~/flutter/remove_this; flutter clean; flutter run)
Deleting 'build/'.
Launching lib/main.dart on Nexus 5 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    0.8s
Running 'gradlew assembleDebug'...                          13.6s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                 14.1s
E/flutter (31696): [ERROR:flutter/shell/common/engine.cc(151)] Could not prepare to run the isolate.
E/flutter (31696): [ERROR:flutter/shell/common/engine.cc(116)] Engine not prepare and launch isolate.
E/flutter (31696): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(136)] Could not launch engine in configuration.
Syncing files to device Nexus 5...                           5.3s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Nexus 5 is available at: http://127.0.0.1:40901/
For a more detailed help message, press "h". To quit, press "q".
```

Ideally, the app would fail early, with a simple "no main function" error message.

**Comment by zoechi** [comment] 2018-12-11 14:48
Duplicate of #21010

**Closed by zoechi** 2018-12-11 14:48 UTC
Labels: dependency: dart, tool
