### ISSUE TITLE
[Web] Elipsis overflow shows unexpected character when using custom font.

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#93685] opened 2021-11-15 21:36 UTC
Only saw this issue on flutter web - worked fine on iOS simulator. When using a custom font (for example  - DM Sans), and `TextOverflow.elipses`, the `...` will have an unexpected block character at the end.

<img width="612" alt="Screen Shot 2021-11-15 at 4 29 51 PM" src="https://user-images.githubusercontent.com/4229329/141856798-a9a219de-1584-4036-b882-0adf25042ff9.png">

## Steps to Reproduce

Run the sample app below on flutter web.

**Expected results:** 

<img width="187" alt="Screen Shot 2021-11-15 at 4 34 53 PM" src="https://user-images.githubusercontent.com/4229329/141857039-1b5d244c-6d89-4306-a833-bdfa07bc9636.png">

**Actual results:** 

<img width="232" alt="Screen Shot 2021-11-15 at 4 35 10 PM" src="https://user-images.githubusercontent.com/4229329/141857073-65a3c150-9320-4f6d-b982-5df345433454.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;

Future<ByteData> fetchFont() async {
  final response = await http.get(
    Uri.parse(
      'https://fonts.gstatic.com/s/a/e518fdb0a5c0ebe0d1d1b02a9025067837e79d235418ab9dc8366e7ce87fad55.ttf',
    ),
  );

  if (response.statusCode == 200) {
    return ByteData.view(response.bodyBytes.buffer);
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load font');
  }
}

Future<void> main() async {
  var fontLoader = FontLoader('dm_sans');
  fontLoader.addFont(fetchFont());
  await fontLoader.load();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Custom Fonts',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Custom Fonts')),
      body: const Center(
        child: SizedBox(
          width: 200,
          child: Text(
            'This elipsis overflow should be fine but it is not on web',
            style: TextStyle(
              fontFamily: 'dm_sans',
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by danagbemava-nc** [comment] 2021-11-16 08:26
Hi @johnsonmh, thanks for filing the issue. Can you please provide the output of `flutter doctor -v`? 

Thank you

**Comment by timovandeput** [comment] 2021-11-16 16:25
I confirm having the problem, and we were thoroughly confused because the extra character is valid in the custom TTF font we are using.

**Comment by timovandeput** [comment] 2021-11-16 16:31
Likely a duplicate of https://github.com/flutter/flutter/issues/90135

**Comment by danagbemava-nc** [comment] 2021-11-17 06:23
Looking through the comments of #90135, this issue does appear to be a duplicate. 
Since #90135, already has a priority label, I will be closing in favour of that issue. 

Thank you

**Closed by danagbemava-nc** 2021-11-17 06:23 UTC
Labels: waiting for customer response, in triage
