### ISSUE TITLE
RawKeyboardListener doesn't receive any events from keyboard in ios simulator

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2601] opened 2016-03-11 02:22 UTC
Maybe by design?  Is there anyway it can work?

**Comment by abarth** [comment] 2016-03-11 03:29
It's just not implemented yet.  /cc @chinmaygarde @tvolkert

**Comment by chinmaygarde** [comment] 2016-03-11 20:52
Didn't know there was another way to access the keyboard other than the keyboard service impl. Will hook this up as well.

**Comment by chinmaygarde** [comment] 2016-03-25 00:29
Postponing this till after https://github.com/flutter/flutter/issues/2887

**Comment by abarth** [comment] 2016-10-20 16:20
I'm not sure iOS has key events.  @chinmaygarde do you know where to get these events in UIKit?

**Comment by Hixie** [comment] 2017-08-22 20:27
This presumably also applies to bluetooth keyboards, et al?

cc @cbracken who has worked on iOS text input.

**Comment by AppleEducate** [comment] 2018-04-19 00:14
2 things about the keyboard on iOS in Flutter.

1. Keyboards do not respond to trackpad mode on the iPhone with 3D touch and iPad with 2 finger swipe. Cursor should move all around the text.

2. I have not found a way yet in flutter to implement keyboard carasoul (like picking a date or time by scrolling in the list in the keyboard)

Both of these are pretty well used on iOS as native functionality.

**Comment by goderbauer** [comment] 2018-12-27 00:45
@AppleEducate If you haven't already you should file separate issues for those two concerns.

/cc @gspencergoog FYI for your keyboard work.

**Comment by gaaclarke** [comment] 2020-04-07 21:17
I checked with @gspencergoog and this appears to be a duplicate of https://github.com/flutter/flutter/issues/31945

**Closed by gaaclarke** 2020-04-07 21:17 UTC
Labels: a: text input, engine, framework, platform-ios
