### ISSUE TITLE
FATAL EXCEPTION: Received image from picker that was not requested

### ISSUE THREAD

**Issue by DomingoMG** [flutter/flutter#60230] opened 2020-06-24 19:41 UTC
## Steps to Reproduce
The camera opens and allows me to select a photo in the gallery, but when I accept, the application crashes.

Plataform Android
Device: Pixel 2 and Redmi 7

```
AndroidRuntime( 5578): FATAL EXCEPTION: main
E/AndroidRuntime( 5578): Process: com.************, PID: 5578
E/AndroidRuntime( 5578): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:26 flg=0x1 }} to activity {com.************/com.************.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
E/AndroidRuntime( 5578): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime( 5578): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime( 5578): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 5578): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 5578): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 5578): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 5578): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 5578): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 5578): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 5578): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5578): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5578): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 5578): Caused by: java.lang.IllegalStateException: Received image from picker that was not requested
E/AndroidRuntime( 5578): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:495)
E/AndroidRuntime( 5578): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:434)
E/AndroidRuntime( 5578): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:413)
E/AndroidRuntime( 5578): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 5578): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 5578): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime( 5578): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime( 5578): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime( 5578): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime( 5578): 	... 11 more
I/Process ( 5578): Sending signal. PID: 5578 SIG: 9
Lost connection to device.
Exited (sigterm)

```

**Comment by TahaTesser** [comment] 2020-06-25 12:58
Hi @DomingoMG 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Swordce** [comment] 2020-07-15 01:33
I have the same problem.
![image](https://user-images.githubusercontent.com/16829238/87492830-062cce00-c67e-11ea-9a63-b84bbc711b73.png)
![image](https://user-images.githubusercontent.com/16829238/87492899-31172200-c67e-11ea-875d-677450c8b322.png)

**Comment by Swordce** [comment] 2020-07-15 01:34
E/AndroidRuntime(13053): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent {
dat=content://com.android.providers.media.documents/document/image:757031 flg=0x1 }} to activity {com.flutter.flutter_married.host/com.flutter.flutter_married.host.MainActivity}:
java.lang.IllegalStateException: Received image from picker that was not requested
[   +1 ms] E/AndroidRuntime(13053):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5587)
[        ] E/AndroidRuntime(13053):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5628)
[        ] E/AndroidRuntime(13053):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
[        ] E/AndroidRuntime(13053):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
[        ] E/AndroidRuntime(13053):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
[        ] E/AndroidRuntime(13053):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
[        ] E/AndroidRuntime(13053):     at android.os.Handler.dispatchMessage(Handler.java:110)
[   +2 ms] E/AndroidRuntime(13053):     at android.os.Looper.loop(Looper.java:219)
[   +1 ms] E/AndroidRuntime(13053):     at android.app.ActivityThread.main(ActivityThread.java:8347)
[   +1 ms] E/AndroidRuntime(13053):     at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/AndroidRuntime(13053):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[   +1 ms] E/AndroidRuntime(13053):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
[   +1 ms] E/AndroidRuntime(13053): Caused by: java.lang.IllegalStateException: Received image from picker that was not requested
[        ] E/AndroidRuntime(13053):     at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:495)
[        ] E/AndroidRuntime(13053):     at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:434)
[   +1 ms] E/AndroidRuntime(13053):     at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:413)
[        ] E/AndroidRuntime(13053):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
[        ] E/AndroidRuntime(13053):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
[   +1 ms] E/AndroidRuntime(13053):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
[   +1 ms] E/AndroidRuntime(13053):     at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
[        ] E/AndroidRuntime(13053):     at android.app.Activity.dispatchActivityResult(Activity.java:8412)
[        ] E/AndroidRuntime(13053):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5580)
[        ] E/AndroidRuntime(13053):     ... 11 more
[        ] I/Process (13053): Sending signal. PID: 13053 SIG: 9

**Comment by Swordce** [comment] 2020-07-15 01:38
The same error occurs when you run the demo directly

**Comment by TahaTesser** [comment] 2020-07-22 15:19
@Swordce  
Can you please provide and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment] 2020-09-02 09:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 09:53 UTC
Labels: in triage, waiting for customer response
