### ISSUE TITLE
Assets from outside the app directory are not handled properly

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#19791] opened 2018-07-25 23:35 UTC
When adding something like the following to pubspec.yaml:
```
flutter:
  assets:
    - ../../../../some_file
```

The flutter tool appends that full path to the `flutter_assets` directory path and ends up writing the file outside of the `flutter_assets` directory(e.g to `flutter_assets/../../../../some_file`).

Loading the asset at runtime fails.

**Comment by jonahwilliams** [comment] 2019-01-08 03:03
Are there any use cases with assets where this works as expected? If not, we should ban assets that are not under the project root

**Comment by amirh** [comment] 2019-01-08 03:49
IIRC my use-case here was to include assets from the locally cached goldens repo in the [android_views](https://github.com/flutter/flutter/tree/master/dev/integration_tests/android_views) integration test.

Agree that we should either have the tool fail immediately or properly support that.

**Comment by zoechi** [comment] 2019-01-09 17:53
#8403 looks related

**Comment by jonahwilliams** [comment] 2019-01-09 18:40
closing as a duplicate of https://github.com/flutter/flutter/issues/8403

**Closed by jonahwilliams** 2019-01-09 18:40 UTC
Labels: a: assets, tool
