### ISSUE TITLE
`pub run pigeon` gives error `Could not find a file named "pubspec.yaml" in ".../.pub-cache/hosted/pub.dartlang.org/async-2.5.0-nullsafety.1".`

### ISSUE THREAD

**Issue by ammaratef45** [flutter/flutter#71929] opened 2020-12-08 18:40 UTC
I have a new project with the following `puspec.yaml` file
```yaml
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^0.1.16
...
```

When I run `pub run pigeon` I get ``Could not find a file named "pubspec.yaml" in ".../.pub-cache/hosted/pub.dartlang.org/async-2.5.0-nullsafety.1".``

Output for `flutter doctor -v`:

> [✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.3 19D76, locale en-EG)
    • Flutter version 1.22.1 at /Users/ammaratefali/development/flutter
    • Framework revision f30b7f4db9 (9 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ammaratefali/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0
[✓] Connected device (3 available)
    • moto g power (mobile) • ZY227GBGBQ • android-arm64  • Android 10 (API 29)
    • Web Server (web)      • web-server • web-javascript • Flutter Tools
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 87.0.4280.88
! Doctor found issues in 1 category.

**Comment by darshankawar** [comment] 2020-12-09 07:50
@ammaratef45 
You seem to be on older version. Current beta is 1.24. I'd recommend to upgrade to latest and try again to see if you get same issue or not.
Thanks.

**Comment by ammaratef45** [comment] 2020-12-10 15:14
@darshankawar I've upgraded flutter and it's the same output

new `flutter doctor -v` output:

>[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.3 19D76
    darwin-x64, locale en-EG)
    • Flutter version 1.24.0-10.2.pre at /Users/ammaratefali/development/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ammaratefali/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0
[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.88
! Doctor found issues in 1 category.

**Comment by darshankawar** [comment] 2020-12-11 06:12
@ammaratef45 
It seems the issue is with pigeon's compatibility with null safety which seem to not support it yet. See [this](https://github.com/flutter/flutter/issues/71360) open issue. Does it answers your question ?

**Comment by ammaratef45** [comment] 2020-12-11 14:30
@darshankawar I'm willing to wait for #71360 to be solved and try again then, any other suggestions?

**Comment by darshankawar** [comment] 2020-12-14 05:42
@ammaratef45 
Your best bet is to wait till https://github.com/flutter/flutter/issues/71360 is fixed. I'd suggest you to follow-up in that issue for updates and any questions you may have.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-12-14 05:42 UTC
Labels: in triage
