### ISSUE TITLE
Exception in Semantics library running Jim's demo in the iOS simulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4150] opened 2016-05-24 03:36 UTC
I'm hitting this when running @jimbeveridge's demo.  Previously I was seeing it crash the iOS port with a null pointer in c++ code, but I think that's now fixed and we're just hitting a non-fatal Dart exception.

I can provide you the source code if needed.

@Hixie @tvolkert 

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/semantics.dart': Failed assertion: line 414 pos 14:
'node.parent?._dirty != true' is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      SemanticsNode.sendSemanticsTree (package:flutter/src/rendering/semantics.dart:414:14)
#2      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:158:21)
#3      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:205:21)
#4      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:144:5)
#5      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:423:15)
#6      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:383:7)
#7      _beginFrame (file:///b/build/slave/Mac_Engine/build/src/out/ios_sim_Release/gen/sky/bindings/hooks.dart:48)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Hixie** [comment] 2016-05-24 15:35
Source code and steps to reproduce would be very helpful yes.

**Comment by abarth** [comment] 2016-11-21 18:17
People keep hitting this on gitter

**Comment by sethladd** [comment] 2016-11-21 18:21
Are we still waiting on a way to repro this, or can we repro this ourselves?

**Comment by eseidelGoogle** [comment] 2016-11-21 18:40
Gitter: https://gitter.im/flutter/flutter?at=58333a1ac790e0ec5613d745

Note the Gitter report was from linux/android not iOS like my original comment.

**Comment by zoechi** [comment] 2016-11-21 18:53
https://github.com/zoechi/flutter_myapp in the issue#4150 branch 
Open the drawer with the top-left icon-button and click `Account` menu item.

**Comment by zoechi** [comment] 2016-11-23 10:24
I get this exception also with the stocks example when I click on any stock item in the main screen.

**Comment by zoechi** [comment] 2016-11-23 10:25
I copied the files into a project created with `flutter create` because the example was not included when I checked out the `flutter` repo.

**Comment by sethladd** [comment] 2017-03-17 21:01
Does this still happen?

**Comment by Hixie** [comment] 2017-06-07 17:52
Likely dupe of https://github.com/flutter/flutter/issues/7287.

**Comment by goderbauer** [comment] 2017-06-07 17:57
I can't reproduce this anymore. This code has also changed a bit in the last few weeks. If you still see this, feel free to open a new bug with steps to reproduce.

**Closed by goderbauer** 2017-06-07 17:57 UTC
Labels: prod: accessibility, prod: framework, waiting for customer response
