### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by VladimirIgorSmirnoff** [flutter/flutter#129241] opened 2023-06-21 08:06 UTC
Hi, I'm facing following issue. I would appreciate any suggestions.

## Command
```
flutter create --org com.vis.my_app my_app
```
  
## Logs
SocketException: Write failed, OS Error: Broken pipe, errno = 32
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1223:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1966:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2413:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2156:26)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2130:11)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#11     _StreamController._add (dart:async/stream_controller.dart:650:7)
#12     _StreamController.add (dart:async/stream_controller.dart:598:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:138:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:271:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2246:36)
#16     _StdSink.write (dart:io/stdio.dart:338:11)
#17     _getCodeSigningIdentityDevelopmentTeam (package:flutter_tools/src/ios/code_signing.dart:234:32)
<asynchronous suspension>
#18     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:296:25)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64 (Rosetta), locale en-GB)
    [32m•[39m Flutter version 3.10.5 on channel stable at /Library/Flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/vladimir_igor_smirnoff/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 20.0.1+9-29)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2023.1.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 74.0.4
    [32m•[39m Dart plugin version 231.9065

[32m[✓][39m VS Code (version 1.72.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.50.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 14 Pro (mobile) • 9A7EA52B-48B5-46EB-B2F1-67328EBFD78B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    [32m•[39m macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64 (Rosetta)
    [32m•[39m Chrome (web)           • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2023-06-21 10:16
Closing as duplicate of https://github.com/flutter/flutter/issues/100584

**Closed by darshankawar** 2023-06-21 10:16 UTC
Labels: in triage
