### ISSUE TITLE
Two finger pan gesture

### ISSUE THREAD

**Issue by fotiDim** [flutter/flutter#17795] opened 2018-05-22 07:58 UTC
From what I can see from issues like [this](https://github.com/flutter/flutter/issues/467) **two finger gestures** like pan or swipe are not supported. This is a blocker for developers wanting to develop custom UI interactions that use multi finger gestures.

**Comment by zoechi** [comment] 2018-08-03 13:05
You can build such gestures in Flutter yourself using https://docs.flutter.io/flutter/gestures/MultiDragGestureRecognizer-class.html
I think this is a dup of #11600

**Comment by zoechi** [comment] 2019-01-29 17:10
See also https://github.com/flutter/flutter/issues/11600#issuecomment-322057313

**Comment by zoechi** [comment] 2019-01-29 17:10
Duplicate of #11600

**Closed by zoechi** 2019-01-29 17:10 UTC
Labels: f: gestures, framework, severe: new feature
