### ISSUE TITLE
Port Flutter to Kotlin Native

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#50858] opened 2020-02-15 09:58 UTC
Petition: Port Flutter to Kotlin Native!

Let me be open and honest: Dart — the language driving Flutter — is a horrible language. In my engineering career, I have seen two languages that are outstanding: TypeScript and Kotlin. TypeScript (TS) has an incredible type system, and Kotlin is a beautifully slick and at-the-point language. I would like to see Kotlin adopting some ideas of TypeScript’s type system to make it perfect.

Kotlin Native (KN) is a cross-platform language that compiles to native code on both iOS and Android platforms. So, in that sense it would fulfill the same native-code requirement the Flutter team has chosen Dart for. Moreover, this is where KN outperforms TS since TS being just a typed facade on top if JavaScript will never reach native performance. This is why React Native will always be behind Flutter performance-wise.

KN is missing a good UI framework and this will be a major blocker for its wide adoption. Flutter is the best UI framework I have seen. Period.

Imagine Flutter being ported to Kotlin Native. I am pretty sure that this will result in an explosion of the adoption of both Flutter and Kotlin Native.

So, hereby, I demand: Port Flutter to Kotlin Native!

**Comment by bernaferrari** [comment] 2020-02-15 10:12
They haven't made this decision, in part, because kotlin is only compiled and dart allows for hot reloading. So, if you rewrite the kotlin native compiler with support for hot reload, might be the start of something.

Additionally, kotlin people are investing in the IR and Jetpack Compose which hopefully will be ported to other platforms using kotlin multiplatform eventually. I don't like dart either, but it is what we got.

**Comment by derolf** [comment] 2020-02-15 10:22
Hot reloading on Android shouldn’t be a problem since Kotlin Native can run on the JVM, so it’s just a matter of swapping classes. That would be already good enough.

For iOS, probably a “simple” Kotlin interpreter shouldn’t be that hard to do...

**Comment by stijnie2210** [comment] 2020-02-15 13:43
Why even bother putting this on the issue list, that's never going to happen

**Comment by stuartmorgan** [comment] 2020-02-15 18:26
Duplicate of #32427

**Closed by stuartmorgan** 2020-02-15 18:26 UTC
