### ISSUE TITLE
App does not render webview on release mode

### ISSUE THREAD

**Issue by ComputelessComputer** [flutter/flutter#74614] opened 2021-01-25 00:37 UTC
## Steps to Reproduce
I am not sure how to reproduce this error. But I will try to explain the details.
I am using a package called [flutter_tex](https://pub.dev/packages/flutter_tex) to render tex equations for a quiz app.
Also I am using the [wakelock](https://pub.dev/packages/wakelock) package for keeping the screen on while solving the quizzes. 

I have encountered an issue for Android where, in release mode, the app will not render the tex equations but throw an exception like the log below. I can't seem to find out where the error is coming from(the origin of this problem) and what exactly the log is telling me. I would like some help to find out what might have gone wrong. Also, I have already tried some 
solutions provided on Stackoverflow [link](https://stackoverflow.com/questions/55794348/webview-in-flutter-not-working-getting-a-platform-error) but it did not help me through this issue. I would very much appreciate some explanation of the log!

<details>
  <summary>Logs</summary>
Result from `flutter run --release --verbose` where the exception is occurring

```
[+143733 ms] E/flutter (20200): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(channel-error, Unable to establish
connection on channel., null, null)
[        ] E/flutter (20200): #0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:51)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200): #1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:22)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200): 
[  +13 ms] E/flutter (20200): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException:
Trying to create a platform view of unregistered type: plugins.flutter.io/webview
[        ] E/flutter (20200):   at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(Unknown Source:229)
[        ] E/flutter (20200):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(Unknown Source:152)
[        ] E/flutter (20200):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(Unknown Source:149)
[        ] E/flutter (20200):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
[        ] E/flutter (20200):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
[        ] E/flutter (20200):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
[   +7 ms] E/flutter (20200):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (20200):   at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/flutter (20200):   at android.os.Looper.loop(Looper.java:197)
[        ] E/flutter (20200):   at android.app.ActivityThread.main(ActivityThread.java:8167)
[        ] E/flutter (20200):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (20200):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[        ] E/flutter (20200):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
[        ] E/flutter (20200): , null, null)
[        ] E/flutter (20200): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
[        ] E/flutter (20200): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
[        ] E/flutter (20200): <asynchronous suspension>
[        ] E/flutter (20200):
```

Result from `flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ko-KR)
    • Flutter version 1.22.5 at /Users/jeongjiheon/development/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jeongjiheon/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/jeongjiheon/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1
```

</details>

**Comment by iapicca** [comment] 2021-01-25 08:07
> [+143733 ms] E/flutter (20200): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(channel-error, Unable to establish
> connection on channel., null, null)
> [        ] E/flutter (20200): #0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:51)
> [        ] E/flutter (20200): <asynchronous suspension>
> [        ] E/flutter (20200): #1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:22)
> [        ] E/flutter (20200): <asynchronous suspension>
> [        ] E/flutter (20200):

[wakelock](https://pub.dev/packages/wakelock) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/creativecreatorormaybenot/wakelock/issues)
or provide your `flutter doctor -v`, your `flutter run --release -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by TahaTesser** [comment] 2021-01-25 11:48
Hi @ComputelessComputer 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated GitHub
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins and uses `webview_flutter`,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-25 11:48 UTC
