### ISSUE TITLE
Problem with platform dependent AppBar with null-safety

### ISSUE THREAD

**Issue by pohara60** [flutter/flutter#81969] opened 2021-05-06 10:31 UTC
This code is accepted without null safety, but gives an error with null safety: `A value of type 'Widget' can't be assigned to a variable of type 'PreferredSizeWidget'.`

```
    final PreferredSizeWidget appbar = Platform.isIOS
        ? CupertinoNavigationBar(
            middle: Text(
              'Personal Expenses ',
            ),
            trailing: Row(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                GestureDetector(
                  child: Icon(CupertinoIcons.add),
                  onTap: () {},
                )
              ],
            ),
          )
        : AppBar(
            title: Text(
              'Personal Expenses ',
              style: TextStyle(fontFamily: 'OpenSans'),
            ),
            actions: <Widget>[
              IconButton(
                icon: Icon(Icons.add),
                onPressed: () {},
              ),
            ],
          );
```

**Comment by pohara60** [comment] 2021-05-06 10:33
I forgot to add my version: `Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale en-GB)`

**Comment by darshankawar** [comment] 2021-05-06 13:16
With `sdk: ">=2.12.0 <3.0.0"`:

<img width="852" alt="Screenshot 2021-05-06 at 6 44 07 PM" src="https://user-images.githubusercontent.com/67046386/117304300-378bba00-ae9b-11eb-9aed-8fd121d124f5.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (2 days ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by HansMuller** [comment] 2021-05-06 15:33
To workaround the problem, wrap CupertinoNavigationBar in a [PreferredSize](https://api.flutter.dev/flutter/widgets/PreferredSize-class.html) widget.

**Comment by pohara60** [comment] 2021-05-06 17:30
The workaround seems undesirable as I have to specify the `preferredSize`. If I declare my `appbar` as `dynamic` I do not get a compile error.

**Comment by HansMuller** [comment] 2021-05-06 18:37
The [PreferredSizeWidget ](https://api.flutter.dev/flutter/widgets/PreferredSizeWidget-class.html) interface defines a preferredSize getter which your dynamic `appbar` doesn't have. The compiler is trying to help out here :-)

**Comment by pohara60** [comment] 2021-05-06 18:49
But `CupertinoNavigationBar` has a `preferredSize` property...

**Comment by HansMuller** [comment] 2021-05-06 19:03
So it does! In fact it implements ObstructingPreferredSizeWidget which is-a PreferredSizeWidget. The expression you've written shouldn't require a workaround ... looking into it

**Comment by pohara60** [comment] 2021-05-06 19:06
Right :) As I wrote, this code works without null safety.

**Comment by goderbauer** [comment] 2021-05-06 20:27
This could be a bug in dart's type inference...

```dart
  final PreferredSizeWidget a = CupertinoNavigationBar();
  final PreferredSizeWidget b = AppBar();
  
  // No Error.
  final PreferredSizeWidget appbar = Platform.isIOS ? a : b;
  final PreferredSizeWidget appbar2 = Platform.isIOS ? a : AppBar();
  final PreferredSizeWidget appbar3 = Platform.isIOS ? CupertinoNavigationBar() : b;

  final PreferredSizeWidget appBar4;
  if (Platform.isIOS) {
    appBar4 = CupertinoNavigationBar();
  } else {
    appBar4 = AppBar();
  }
  
  // Error.
  final PreferredSizeWidget appbar5 = Platform.isIOS ? CupertinoNavigationBar() : AppBar();
```

I'll see if I can reproduce this outside the flutter framework. In the meantime, I'd go with the `appBar4` example from above as a functionally equivalent work-around.

**Comment by goderbauer** [comment] 2021-05-06 20:43
Submitted https://github.com/dart-lang/sdk/issues/45941, let's see what the dart team thinks.

**Comment by goderbauer** [comment] 2021-05-06 22:19
As was explained in https://github.com/dart-lang/sdk/issues/45941#issuecomment-833891751 this is working as designed from Dart's perspective. 

It also gave a simple work around of using an explicit case:

```dart
final PreferredSizeWidget appbar5 = (Platform.isIOS ? CupertinoNavigationBar() : AppBar()) as PreferredSizeWidget;
```

Since there's not much we can do about this on the Flutter side, I am going to close this issue.

**Closed by goderbauer** 2021-05-06 22:19 UTC
Labels: a: null-safety, dependency: dart, f: cupertino, found in release: 2.3, framework, has reproducible steps
