### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: google-chrome, OS error code: 2

### ISSUE THREAD

**Issue by amaxcz** [flutter/flutter#130251] opened 2023-07-10 10:22 UTC
## Command
```
flutter run -d linux
```

## Steps to Reproduce
1. pressed some hotkey
2. crashed
3. using chromium (not google crome) in the linux

## Logs
ProcessException: No such file or directory Command: google-chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:145:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:133:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1803:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1821:13)
#8      _rootRunUnary (dart:async/zone.dart:1407:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1407:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on Manjaro Linux 6.3.5-2-MANJARO, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.5 on channel stable at /opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /opt/android-sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /opt/android-sdk
    [32m•[39m ANDROID_SDK_ROOT = /opt/android-sdk
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_372-b07)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 15.0.7
    [32m•[39m cmake version 3.26.4
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m Connected device (1 available)
    [32m•[39m Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.3.5-2-MANJARO

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f92f44110e87bad5ff168335c36da6f6053036e6
### Plugins
auto_orientation-2.3.1
file_picker-5.2.10
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_libserialport-e421bd6ebc05c8470de1d565edf7ae279b033383
flutter_meedu_videoplayer-4.2.13
flutter_plugin_android_lifecycle-2.0.15
flutter_windowmanager-0.2.0
fullscreen_window-1.0.4
media_kit_libs_linux-1.0.2
media_kit_libs_macos_video-1.0.5
media_kit_libs_windows_video-1.0.2
media_kit_native_event_loop-1.0.6
media_kit_video-1.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.3.0
permission_handler_android-10.2.3
permission_handler_apple-9.1.0
permission_handler_windows-0.1.2
screen_brightness-0.2.2
screen_brightness_android-0.1.0+2
screen_brightness_ios-0.1.0
screen_brightness_macos-0.1.0+1
screen_brightness_windows-0.1.1
screen_retriever-0.1.6
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4
video_player-2.6.1
video_player_android-2.4.9
video_player_avfoundation-2.4.6
video_player_web-2.0.16
volume_controller-2.0.7
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
window_manager-0.3.5

**Comment by dam-ease** [comment] 2023-07-10 10:52
Closing as duplicate of https://github.com/flutter/flutter/issues/95142. Please upvote the original issue for team's attention.

**Closed** 2023-07-10 10:53 UTC
Labels: r: duplicate
