### ISSUE TITLE
Creating a plugin using 'flutter create -i swift' produces a broken project.

### ISSUE THREAD

**Issue by 0916174** [flutter/flutter#15763] opened 2018-03-20 20:41 UTC
## Steps to Reproduce

`flutter create --template=plugin -i swift health_stats`
yields
```
Creating project health_stats...
  health_stats/LICENSE (created)
  health_stats/ios/health_stats.podspec (created)
  health_stats/ios/.gitignore (created)
  health_stats/ios/Assets/.gitkeep (created)
  health_stats/health_stats.iml (created)
  health_stats/.gitignore (created)
  health_stats/android/settings.gradle (created)
  health_stats/android/.gitignore (created)
  health_stats/android/gradle.properties (created)
  health_stats/android/src/main/AndroidManifest.xml (created)
  health_stats/pubspec.yaml (created)
  health_stats/README.md (created)
  health_stats/ios/Classes/HealthStatsPlugin.m (created)
  health_stats/ios/Classes/SwiftHealthStatsPlugin.swift (created)
  health_stats/ios/Classes/HealthStatsPlugin.h (created)
  health_stats/lib/health_stats.dart (created)
  health_stats/android/build.gradle (created)
  health_stats/android/src/main/java/com/example/healthstats/HealthStatsPlugin.java (created)
  health_stats/health_stats_android.iml (created)
  health_stats/.idea/runConfigurations/example_lib_main_dart.xml (created)
  health_stats/.idea/libraries/Flutter_for_Android.xml (created)
  health_stats/.idea/libraries/Dart_SDK.xml (created)
  health_stats/.idea/modules.xml (created)
  health_stats/.idea/workspace.xml (created)
  health_stats/CHANGELOG.md (created)
Running "flutter packages get" in health_stats...     2,1s
  health_stats/example/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  health_stats/example/ios/Runner/Info.plist (created)
  health_stats/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  health_stats/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  health_stats/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  health_stats/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  health_stats/example/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  health_stats/example/ios/Runner/Base.lproj/Main.storyboard (created)
  health_stats/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  health_stats/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  health_stats/example/ios/Flutter/Debug.xcconfig (created)
  health_stats/example/ios/Flutter/Release.xcconfig (created)
  health_stats/example/ios/Flutter/AppFrameworkInfo.plist (created)
  health_stats/example/ios/.gitignore (created)
  health_stats/example/test/widget_test.dart (created)
  health_stats/example/health_stats_example.iml (created)
  health_stats/example/.gitignore (created)
  health_stats/example/.metadata (created)
  health_stats/example/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  health_stats/example/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  health_stats/example/android/app/src/main/res/drawable/launch_background.xml (created)
  health_stats/example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  health_stats/example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  health_stats/example/android/app/src/main/res/values/styles.xml (created)
  health_stats/example/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  health_stats/example/android/app/src/main/AndroidManifest.xml (created)
  health_stats/example/android/gradle/wrapper/gradle-wrapper.properties (created)
  health_stats/example/android/.gitignore (created)
  health_stats/example/android/gradle.properties (created)
  health_stats/example/android/settings.gradle (created)
  health_stats/example/pubspec.yaml (created)
  health_stats/example/README.md (created)
  health_stats/example/ios/Runner/Runner-Bridging-Header.h (created)
  health_stats/example/ios/Runner/AppDelegate.swift (created)
  health_stats/example/ios/Runner.xcodeproj/project.pbxproj (created)
  health_stats/example/lib/main.dart (created)
  health_stats/example/android/app/build.gradle (created)
  health_stats/example/android/app/src/main/java/com/example/healthstatsexample/MainActivity.java (created)
  health_stats/example/android/build.gradle (created)
  health_stats/example/health_stats_example_android.iml (created)
  health_stats/example/android.iml (created)
  health_stats/example/.idea/runConfigurations/main_dart.xml (created)
  health_stats/example/.idea/libraries/Flutter_for_Android.xml (created)
  health_stats/example/.idea/libraries/Dart_SDK.xml (created)
  health_stats/example/.idea/modules.xml (created)
  health_stats/example/.idea/workspace.xml (created)
Wrote 90 files.

Running "flutter packages get" in example...          8,3s

[✓] Flutter is fully installed. (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale nl-NL)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices is fully installed. (Xcode 9.3)
[✓] Android Studio is fully installed. (version 3.0)
[✓] VS Code is fully installed. (version 1.21.1)
[✓] Connected devices is fully installed. (1 available)

All done! In order to run your application, type:

  $ cd health_stats/example
  $ flutter run

Your main program file is lib/main.dart in the health_stats/example directory.

Your plugin code is in lib/health_stats.dart in the health_stats directory.

Host platform code is in the android/ and ios/ directories under health_stats.
To edit platform code in an IDE see https://flutter.io/platform-plugins/#edit-code.
```
then
`cd health_stats/example`

## Logs
`flutter run`
yields
```
Launching lib/main.dart on iPhone van Jeroen Meijer in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: [REMOVED]
Running pod install...                                0,9s
Running Xcode clean...                                1,0s
Starting Xcode build...
Xcode build done                                      1,2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET health_stats OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/health_stats-umbrella.h"
            ^
    /Users/jeroen/Projects/health_stats/example/ios/Pods/Target Support Files/health_stats/health_stats-umbrella.h:13:9: error: include of non-modular header inside framework module 'health_stats': '/Users/jeroen/Projects/health_stats/ios/Classes/HealthStatsPlugin.h'
    #import "HealthStatsPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'health_stats'
Could not build the precompiled application for the device.

Error launching application on iPhone van Jeroen Meijer.
```

`flutter analyze`
yields
```
Analyzing /Users/jeroen/Projects/health_stats/example...
No issues found!
Ran in 5.1s
```
## Flutter Doctor

`flutter doctor -v`
yields
```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale nl-NL)
    • Flutter version 0.1.5 at /Developer/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/jeroen/Library/Developer/Xamarin/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • ANDROID_HOME = /Users/jeroen/Library/Developer/Xamarin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 9.3, Build version 9Q127n
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0

[✓] Connected devices (1 available)
    • iPhone van Jeroen Meijer • [REMOVED] • ios • iOS 11.3
```

## EDIT
The same now also happens when creating a plugin omitting the `-i swift`. Generating any project with `--template=plugin` yields the same result.

**Comment by rmtmckenzie** [comment] 2018-03-20 22:59
I'm surprised that happens with --template=plugin, but I'm fairly sure that this is a duplicate of #15099 which has been fixed in master by #15437. And see #15031 for a related issue....
Try switching to the master channel and see if the problem still exists there (run `flutter channel master`, and maybe `flutter upgrade`).

**Comment by 0916174** [comment] 2018-03-21 12:27
Thanks for you reply. I have switched to the `master` channel and did a `flutter upgrade` (and `git pull` just to be sure). Still get the same result unfortunately.
<img width="899" alt="schermafbeelding 2018-03-21 om 13 26 57" src="https://user-images.githubusercontent.com/14292245/37709778-9006707c-2d0b-11e8-8ab6-4afcf4ab0d5c.png">

**Comment by 0916174** [comment] 2018-03-21 23:53
Hi there.
**The problem has worsened and I need flutter to work a.s.a.p. since I need to start working on an app for our business.**
Sorry for putting such urgency on it.

I wanted to tell you that I'm currently having trouble building any project that doesn't use the default code that's provided when creating a project. Doesn't matter if I use swift or not.

I've removed flutter and all brew packages that I installed when setting up flutter and reinstalled everything.
I then created a new project. `flutter run` did fine. Then, when adding the `camera` package, `flutter run` told me it couldn't find the `<camera/Camera....h>` (I forgot the last part).
Now, when building a completely new project, it can't find the flutter package at all.

```
Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode clean...                                0,9s
Starting Xcode build...
Xcode build done                                      1,1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET camera OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.m:5:
    /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 8.
```

<img width="1512" alt="schermafbeelding 2018-03-22 om 00 52 00" src="https://user-images.githubusercontent.com/14292245/37743626-4941039a-2d6b-11e8-89d1-ec4bbc77a157.png">

**Comment by 0916174** [comment] 2018-03-22 00:09
The brand new project in question:

[superdupercamera.zip](https://github.com/flutter/flutter/files/1835603/superdupercamera.zip)

**Comment by 0916174** [comment] 2018-03-22 00:38
I've cleared my `.pub-cache/hosted/pub.dartlang.org` folder and ran `flutter packages get`.
`flutter run` gave a different error this time:

```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                1,1s
Starting Xcode build...
Xcode build done                                      1,3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
    clang: error: no such file or directory: '/Users/jeroen/.pub-cache/hosted/pub.dartlang.org/camera-0.1.1/ios/Classes/CameraPlugin.m'
    clang: error: no input files
    clang: error: no such file or directory: '/Users/jeroen/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.m'
    clang: error: no input files
Could not build the application for the simulator.
Error launching application on iPhone X.
```

Then I ran `cd ios` and `pod update` and now it runs properly.
I figured flutter would do this automatically, but apparently, it doesn't.

**Comment by 0916174** [comment] 2018-03-22 00:42
After doing the above, I just added the `camera` dependency to the pubspec:
```
...
dependencies:
  flutter:
    sdk: flutter
  camera: "^0.1.1"

  # The following adds the Cupertino Icons font to your application.
...
```

`flutter run`
yields
```
Running "flutter packages get" in superdupercamera...  3,2s
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                1,0s
Running Xcode clean...                                0,9s
Starting Xcode build...
Xcode build done                                      2,4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET camera OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/camera-0.1.1/ios/Classes/CameraPlugin.m:1:
    /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/camera-0.1.1/ios/Classes/CameraPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

**Comment by adesugbaa** [comment] 2018-03-26 21:51
I am unable to add any of the following plugins:

- image_picker
- google_sign_in
- firebase_auth
- firebase_database
- firebase_storage

I had all type of compile errors related to <some_framework/some_file.h> not found.

Once I removed **use_frameworks!** from the podfile, I am able to compile and run the project.

```
target 'Runner' do
  # use_frameworks!
...
end
```

Not sure if that is a long term solution, but at least I am able to complete my code labs :-)

**Comment by 0916174** [comment] 2018-03-26 22:56
Hey there. Thanks for your help.
It seems the problem has taken a weird turn.
Now, when generating a project, a `podfile` is not generated and running `pod init` manually yields the following result:
```
[!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and the unknown UUID is being discarded.
```

The resulting `podfile`:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner

end
```

Then, `flutter run`:

```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
In file included from /Users/jeroen/Projects/animator/ios/Runner/GeneratedPluginRegistrant.m:5:
/Users/jeroen/Projects/animator/ios/Runner/GeneratedPluginRegistrant.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)
```

@Hixie Sorry for bothering you. Do you happen to know anything I can do in order to fix this? I need to create an app for a client as soon as possible.

**Comment by adesugbaa** [comment] 2018-03-26 23:41
Please switch to the beta channel. I am able to create projects with that branch...

**Comment by 0916174** [comment] 2018-03-26 23:55
Just tried it. Same things happens on the beta channel. :(

Op 27 mrt. 2018, om 01:42 heeft Ayo Adesugba <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Please switch to the beta channel. I am able to create projects with that branch...

**Comment by Hixie** [comment] 2018-03-27 04:20
cc @mravn-google @goderbauer @xster @cbracken Any ideas?

**Comment by mravn-google** [comment] 2018-03-27 13:21
Applying the fix of https://github.com/flutter/flutter/pull/15437 should work. It is not on beta yet.

**Comment by 0916174** [comment] 2018-03-28 19:16
Since a lot has changed with my installation (reinstalling everything, changing settings, etc.) I'll make a new issue, since my problem has shifted, too. Please check #16036. Sorry for bothering all you guys but this has quite some urgency.

**Closed** 2018-03-28 19:39 UTC
Labels: waiting for customer response
