### ISSUE TITLE
Misleading flutter doctor message about cocoapods

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#14293] opened 2018-01-26 18:54 UTC
Flutter doctor was giving me this message:

```
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
```

When executing `brew install cocoapods` as suggested, I got this message:

```
Error: cocoapods 1.3.1 is already installed
To upgrade to 1.4.0, run `brew upgrade cocoapods`
```

Do we need to change the doctor message and detect that it is maybe just out of date?

/cc @xster @cbracken

**Comment by goderbauer** [comment] 2018-01-26 18:59
Running `brew upgrade cocoapods` followed by `pod setup` fixed the doctor warning for me.

Some more context: This warning happened right after upgrading from Mx OS X Sierra to High Sierra.

**Comment by xster** [comment] 2018-01-26 19:16
I think we don't need people to run `pod setup` again. 

We need to split our error messaging between `pod` not being on PATH and `pod` runs but crashes (which happens after upgrading to High Sierra). 

https://github.com/CocoaPods/CocoaPods/issues/6898

In the meantime, if people find this from Google searching, the solution is to re-install CocoaPods or `brew upgrade cocoapods`

**Comment by cbracken** [comment] 2018-01-26 20:23
Out of curiosity - do you also have ruby installed via homebrew? Here's what I surmise: CocoaPods is installed as a gem inside a ruby version-specific gem dir, if ruby is updated, the current `usr/bin/ruby` will be version X and CocoaPods will be installed in version the version Y ruby dir, and you'll get a broken `pod` binary. 

This is only a theory, but I'd imagine shouldn't be too hard to verify, and if it pans out, it should also be pretty easy to change the doctor check to something like:
1. is there a `pod` binary on the PATH? If not report not installed.
2. run `pod version`, which should hopefully be enough to get it to blow up if it's in a bad state.
3. if it exits with 0, then we're set, otherwise emit an error message that it's in a bad state, plus  instructions to re-install it

**Comment by goderbauer** [comment] 2018-01-26 20:33
Ruby was not installed via homebrew on my system (it doesn't show up in `brew list`).

**Comment by cbracken** [comment] 2018-01-26 20:48
Ah that might make sense -- if High Sierra upgrades ruby, I'd imagine you could run into the same issue. In my case I notice:
pod installed at: `/Users/cbracken/.homebrew/bin/pod`

If you look at the code of that file, it looks like it tries to load the 'cocoapods' gem. I'm assuming ruby then tries to load from the appropriate lib/ruby/gems/[RUBYVERSION] directory, and if cocoapods isn't installed for the current version, you'd get brokenness.

I see the cocoapods gem installed at:
/Users/cbracken/.homebrew/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.0

**Comment by DeterminedNow** [comment] 2018-03-05 18:50
Hi folks.
I’m trying to develop an ios / Android app in flutter / Intellij but can’t yet get flutter doctor to give me a clean bill of health. I get a similar problem reported by @goderbauer at the begining of this post…

	Cocoapods not installed…

And later, after trying to brew instal cocoapods…

	Warning: cocoapods 1.4.0 is already installed

I’ve tried a few things including,

	brew link --overwrite cocoapods

which I saw posted by @dodikk under, #High Sierra: bad interpreter #6898

I’ve got Xcode 9.2 on Mac OS High Sierra 10.13 running in Virtualbox 5.2.8, under Windows 10.
I’m not as tech savvy as most of you, coming from a mainframe background so please give detail as to what I should do, if anyone could try to help please.

**Comment by HardVeur** [comment] 2018-04-01 16:45
Still have the same issue:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale de)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[!] iOS toolchain - develop for iOS devices (Xcode 9.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

The outputs:
`which pod` -> /usr/local/bin/pod
`which gem` -> /usr/bin/gem
`which ruby` -> /usr/bin/ruby
`brew link --overwrite cocoapods` -> first time it didn't gave any outputs second time ->
Warning: Already linked: /usr/local/Cellar/cocoapods/1.4.0
To relink: brew unlink cocoapods && brew link cocoapods
`brew install cocoapods` -> Warning: cocoapods 1.4.0 is already installed

So everything seems to be okay but flutter doesn't accept my cocoapods installation.
Any ideas how to fix this?!

**Comment by DeterminedNow** [comment] 2018-04-02 19:32
Thanks for your response, @xster   As requested:
`which pod` -> /usr/local/bin/pod
`which gem` -> /usr/bin/gem
`which ruby` -> /usr/bin/ruby
`brew link --overwrite cocoapods` -> Warning: Already linked: /usr/local/Cellar/cocoapods/1.4.0
To relink: brew unlink cocoapods && brew link cocoapods

Anyway, I've had the good fortune to be able to work on a new iMac.
Made all of the recommended Flutter installations and configurations.
`flutter doctor` gives me a clean bill of health now but am faced with different problems, hehe.
@xster, I'm prepared to go back to my Windows 10, VirtualBox, High Sierra setup if you'd like me to.

**Comment by xster** [comment] 2018-04-02 19:44
@DeterminedNow, just to make sure, your `flutter doctor` no longer has issues if I understand correctly right?

@HardVeur, sounds like you're still having issues. Can you show the output for `pod --version` as well? Thanks.

**Comment by DeterminedNow** [comment] 2018-04-02 20:06
@xster, `flutter doctor` on my new High Sierra iMac no longer has issues.
I still get "Cocoapods not installed" where I was working , on a Windows 10, running VirtualBox, running High Sierra. I'll continue working with it if it'd be at all helpful...

**Comment by HardVeur** [comment] 2018-04-02 20:38
@xster the output `pod --version` -> 1.4.0 
Any suggestions?

**Comment by jeppeskovbakke** [comment] 2018-04-18 10:24
This thread solved it for me:
cocoapods [#14630](https://github.com/flutter/flutter/issues/14630)
Fixing the permissions so I won't have to run flutter doctor as root, and suddenly it sees the cocoapods install...

**Comment by tolgakartal** [comment] 2018-07-29 01:58
thanks @jeppeskovbakke that solved it, but btw :) ;

if I run flutter doctor in sudo then cocoa pods still outputs as not installed 🤦‍♂️

**Comment by coood** [comment] 2018-11-12 13:41
solved it for me  cocoapods #14630

**Comment by cuichanghao** [comment] 2018-12-20 06:21
Mac high sierra cannot install to /usr/bin you need below command to install /usr/local/bin

```
sudo gem install cocoapods -n /usr/local/bin
```

**Comment by jporsay** [comment] 2019-01-01 15:17
Any update on this?

I'm getting no issues when running `flutter run` to launch the application but getting the error message when running from within _Android Studio_ or _Visual Studio Code_.

**Comment by PolymathWhiz** [comment] 2019-01-14 11:38
谢谢 @cuichanghao

**Comment by JoaoPauloCMarra** [comment] 2019-03-21 15:53
I had it previously with gem, then i fixed by:
`gem uninstall cocoapods`
and
`brew reinstall cocoapods`

**Comment by Augustpi** [comment] 2019-04-14 22:10
pod repo remove master
pod setup

**Comment by jerryzhoujw** [comment] 2019-05-27 02:45
I think I get this message because I use `rvm` to manager ruby gems.
`Warning: CocoaPods not installed. Skipping pod install.`

```
pod --version
1.5.3
which pod
~/.rvm/gems/ruby-2.2.9/bin/pod
which gem
~/.rvm/rubies/ruby-2.2.9/bin/gem
which ruby
~/.rvm/rubies/ruby-2.2.9/bin/ruby
```

**Comment by jjercTK** [comment] 2019-07-12 20:47
This worked:

> I get this message because I use `rvm` to manager ruby gems.
> `Warning: CocoaPods not installed. Skipping pod install.`
> 
> ```
> pod --version
> 1.5.3
> which pod
> ~/.rvm/gems/ruby-2.2.9/bin/pod
> which gem
> ~/.rvm/rubies/ruby-2.2.9/bin/gem
> which ruby
> ~/.rvm/rubies/ruby-2.2.9/bin/ruby
> ```
> 
> Not impact my project, i can run pod install by myself under /ios/ folder.
> 
> by the way, it should upgrade cocoapods by commands bellow.
> 
> `gem install cocoapods`
> `gem cleanup cocoapods`

This worked! It seems it's not working with `brew`, but it is working installing it with `gem`

**Comment by jerryzhoujw** [comment] 2019-08-07 17:03
By the way, this issue are gone on may environment. Maybe flutter already fix this ?

My environment:
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-CN)

**Closed** 2019-08-23 16:21 UTC
Labels: a: first hour, p: tooling, plugin, tool, ‎‍💻platform-catalina, ⌘‬ platform-mac

**Comment by lee-40square** [comment] 2019-09-04 20:27
Although this has been closed, the issue resurfaced when I updated Mojave to 10.14.6

```
Error:
Warning: CocoaPods not installed. Skipping pod install.
```

When I run `brew install cocoapods` I get
```
Error: cocoapods 1.6.0 is already installed
To upgrade to 1.7.5, run `brew upgrade cocoapods`.
```
This worked:
`brew upgrade cocoapods`
`pod setup`
` pod install`

**Comment by christopherfujino** [comment] 2019-09-04 21:12
Thanks for sharing what worked for you, @lee-40square. To be clear, the "fix" for this was just to give better `flutter doctor` warning message (the flutter tool is not going to manage users' cocoapods install). Also, the said patch was published on v1.9.4.

**Comment by tadasss** [comment] 2019-09-05 22:55
I've been having the same issue everybody in this thread, but none of the solutions work. I've been trying to install and reinstall for hours.

> adminisatorsMBP:flutter administrator$ sudo flutter doctor
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

> ! Doctor found issues in 2 categories.
adminisatorsMBP:flutter administrator$ which pod
/usr/local/bin/pod
adminisatorsMBP:flutter administrator$ which gem
/usr/bin/gem
adminisatorsMBP:flutter administrator$ which ruby
/usr/bin/ruby
adminisatorsMBP:flutter administrator$ pod setup
Setting up CocoaPods master repo

> CocoaPods 1.8.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

> For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.8.0.beta.2

> Setup completed
adminisatorsMBP:flutter administrator$

**Comment by christopherfujino** [comment] 2019-09-06 18:35
@tadasss I highly suspect that running `flutter` as root has something to do with cocoapods not being detected. As you can see from warning message at the top, running flutter as root is not supported, and I would image a lot of things would break.

**Comment by lee-40square** [comment] 2019-09-09 19:14
@christopherfujino noted on the patch being on v1.9.4. (that's why I was still getting the old message).

I understand that the tool won't manage the Cocoapods installation and I know the warning is false :-)  As far as what's causing the error, I'm not running Flutter as root.

Here's something interesting, I just rebooted my computer and ran the app from VSCode debug and got the error again. However, `flutter doctor -v` is all green and if I `flutter run` from the terminal I don't get the error. After checking a few more things I'm pretty sure that the issue is related to path and Homebrew and the Cocoapods local repo. Anyway, nothing that needs to be addressed by you guys. :-)

**Comment by Constans** [comment] 2019-10-22 22:37
Got this after upgrading to macOS Catalina. 

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.209, on Mac OS X 10.15 19A603, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

The solution of reinstalling cocoapods solved it for me.
```
brew install cocoapods
pod setup
```

**Comment by Getvc2015** [comment] 2019-10-25 01:44
Working with 

gem install cocoapods
gem cleanup cocoapods

after run the command the version show as below. 
pod --version
1.8.4

**Comment by houssem-mallat** [comment] 2019-10-26 09:41
This worked fine :
=> brew install cocoapods
=> brew upgrade cocoapods

**Comment by leijoninna** [comment] 2019-11-18 12:24
My cocoapods issue was solved when ruby and rvm were upgraded to the latest versions. After that cocoapods installed/reinstalled fine.

**Comment by ducquynhnguyeninfo** [comment] 2019-11-19 00:26
In my case, I only need to upgrade the cocoapods
`brew upgrade cocoapods `

**Comment by mkbond777** [comment] 2019-11-21 11:26
For me below dependency was creating a problem :
url_launcher: ^5.0.3

**Comment by tewshi** [comment] 2020-01-02 07:39
if you upgrade your OS, for instance Mac Mojave to Catalina you need to do
`gem uninstall cocoapods`  (to remove it if you initially installed via `gem`)
then
`brew reinstall cocoapods`

**Comment by williamromero** [comment] 2020-02-03 08:16
I had this issue but nothing worked for me, but i found this answer [link](https://stackoverflow.com/a/29177432/5424678) in a comment from 2015 but it helps me a lot, so i leave it here for anyone who helps it:

```shell
# First i tried
sudo gem install -n /usr/local/bin cocoapods
brew unlink cocoapods && brew link cocoapods

# Last i tried
rvmsudo gem install cocoapods
```
And the last one helped me to get it working again.

**Comment by Jethro87** [comment] 2020-02-06 18:33
This is happening to me as well. Nothing from this thread has fixed it, however, I am able to build and run the app without any apparent problems.

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-CA)
    • Flutter version 1.14.6 at /Users/jb/flutter
    • Framework revision fabeb2a16f (9 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Jeff’s iPhone • 5d74ad2c2d551bab66cb5ed48c075deb99ed77bc • ios • iOS 13.3
```

**Comment by williamromero** [comment] 2020-02-06 22:14
Tell me more about your problem, maybe i can help you...
Did you try this thing: **rvmsudo gem install cocoapods**

> This is happening to me as well. Nothing from this thread has fixed it, however, I am able to build and run the app without any apparent problems.
> 
> ```
> [✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-CA)
>     • Flutter version 1.14.6 at /Users/jb/flutter
>     • Framework revision fabeb2a16f (9 days ago), 2020-01-28 07:56:51 -0800
>     • Engine revision c4229bfbba
>     • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/jb/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/jb/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C504
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.41.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.8.1
> 
> [✓] Connected device (1 available)
>     • Jeff’s iPhone • 5d74ad2c2d551bab66cb5ed48c075deb99ed77bc • ios • iOS 13.3
> ```

**Comment by Jethro87** [comment] 2020-02-06 23:00
@williamromero 

Thanks. First, I did this:

```
sudo gem install -n /usr/local/bin cocoapods
brew unlink cocoapods && brew link cocoapods
```

which gave me this:

```
Successfully installed cocoapods-1.8.4
Parsing documentation for cocoapods-1.8.4
Done installing documentation for cocoapods after 3 seconds
1 gem installed
Unlinking /usr/local/Cellar/cocoapods/1.8.4... 1 symlinks removed
Linking /usr/local/Cellar/cocoapods/1.8.4... 
Error: Could not symlink bin/pod
Target /usr/local/bin/pod
already exists. You may want to remove it:
  rm '/usr/local/bin/pod'

To force the link and overwrite all conflicting files:
  brew link --overwrite cocoapods

To list all files that would be deleted:
  brew link --overwrite --dry-run cocoapods
```
I don't have rvm installed, so `rvmsudo gem install cocoapods` isn't working. But `sudo gem install cocoapods` doesn't fix it either.

**Comment by williamromero** [comment] 2020-02-06 23:03
Try to use RVM, it really helped me a lot to get it up again. Because i wasn't able to do nothing. Here is the link to learn how install RVM. I wasn't able to run that as you, try it.
[RVM Install](https://rvm.io/rvm/install)

**Comment by whittenator** [comment] 2020-03-26 01:02
Upgraded to Catalina and received the following error:
```
[!] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different
        from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
```
Trying `sudo gem install cocoapods` alone didn't work for me. So I did the following to fix the error:
1. `sudo gem install -n /usr/local/bin cocoapods`
2. `brew unlink cocoapods && brew link cocoapods --overwrite cocoapods`
3. `flutter doctor -v` 👍

**Comment by micimize** [comment] 2020-04-14 18:41
The only thing that worked for me was adding `gem "cocoapods"` to the `Gemfile`
and then `bundle install && bundle exec pod setup`.
IDK if all the install retries listed here helped at all.

**Comment by martipello** [comment] 2020-04-17 13:14
i have this issue after an update yesterday so im running Catalina 10.15.4 (19E287) my error looks like this 

Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

flutter doctor seems fine

martinseal@Martins-MacBook-Pro click_and_deliver % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!

cant run my app

**Comment by samuelsennott** [comment] 2020-04-18 00:29
I keep getting this error below and am stuck.  

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

**Comment by martipello** [comment] 2020-04-18 06:08
I followed @whittenator advice and had to restart my laptop and it worked

**Comment by samuelsennott** [comment] 2020-04-18 06:24
This worked for me: https://github.com/flutter/flutter/issues/41291#issuecomment-535117317

> Thank you.  
As per solution in #41253:
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.7.5
pod setup
>

**Comment by srburton** [comment] 2020-04-22 18:43
I am trying for days a solution to this problem and I have not been successful yet. Could someone help me?

Note: I tried all the solutions above ...

![Screenshot_1](https://user-images.githubusercontent.com/15394508/80019784-6e6c7900-84ae-11ea-92dd-6b2931c5b6db.png)

![Screenshot_5](https://user-images.githubusercontent.com/15394508/80020598-af18c200-84af-11ea-8a8d-06432c33adc3.png)

![Screenshot_7](https://user-images.githubusercontent.com/15394508/80020609-b3dd7600-84af-11ea-89fb-891cbc4070e8.png)

![Screenshot_2](https://user-images.githubusercontent.com/15394508/80020730-dcfe0680-84af-11ea-921a-d604c9be868d.png)

**Comment by RCHowell** [comment] 2020-04-24 19:14
@srburton I just ran into this issue on Catalina.

I removed the Ruby gem and installed cocoapods with homebrew.

```
brew install cocoapods
brew link --overwrite cocoapods
```

The last step is crucial to overwrite the previous symlink.

**Comment by srburton** [comment] 2020-04-24 19:34
@RCHowell 
Thanks, the more I managed to fix this code, the more my problem was that I was running the flutter in `sudo` mode.

**My solution:**  #55396

**Comment by gondar00** [comment] 2020-04-25 23:23
`cd ios`
`pod install`
`cd ..`
`flutter run`

**Comment by CareF** [comment] 2020-06-08 15:40
Running into the same problem. `pod version` blow up. Tried this: https://www.fatalerrors.org/a/can-t-find-gem-cocoapods-0.a-gem-gemnotfoundexception.html 
and it turns out uninstal cocoapods and reinstall it without sudo fixes this.

**Comment by halohoop** [comment] 2020-07-09 08:25
here my situation:
`
flutter doctor[enter]
...
[!] Xcode - develop for iOS and macOS (Xcode 11.5)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
...
`

**fixed way below**
`
brew uninstall cocoapods[enter]
...waiting to finish
sudo gem install cocoapods[enter]
...waiting to finish
flutter doctor[enter]
...all fixed
`

**Comment by avegrv** [comment] 2020-07-23 07:47
Flutter you suck, already 3 hours I have spent to fix this problem.

**Comment by paulkastel** [comment] 2020-10-29 17:21
I just had this error shown and it was because I had cocoapods installed with gem and fastlane was installed with brew. When both of them were installed with gem, then problem was solved.

**Comment by UlyssesAlves** [comment] 2020-11-28 23:26
I started getting "CocoaPods installed but not working." error on flutter doctor after upgrading to Catalina on Mac OS when I had already installed flutter development tools before installing the OS upgrade.

The error was preventing me from installing cocoapods again and from uninstalling it too, so I couldn't reinstall it.

I was able to fix it by following the step by step instructions in this answer on StackOverflow: ["ERROR: Error installing cocoapods: ERROR: Failed to build gem native extension"](https://stackoverflow.com/a/62706706/1639385)

**Comment by JFKarasu** [comment] 2020-12-04 09:11
> I am trying for days a solution to this problem and I have not been successful yet. Could someone help me?
> 
> Note: I tried all the solutions above ...
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/15394508/80019784-6e6c7900-84ae-11ea-92dd-6b2931c5b6db.png)
> 
> * POD (COMMAND...)
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/15394508/80020598-af18c200-84af-11ea-8a8d-06432c33adc3.png)
> 
> ![Screenshot_7](https://user-images.githubusercontent.com/15394508/80020609-b3dd7600-84af-11ea-89fb-891cbc4070e8.png)
> 
> * RUBY --VERSION
> 
> ![Screenshot_8](https://user-images.githubusercontent.com/15394508/80020953-35cd9f00-84b0-11ea-846d-96bd3676e3d0.png)
> 
> * GEM LIST
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/15394508/80021101-6c0b1e80-84b0-11ea-86c5-c9ad4c9fa988.png)
> 
> * BREW LIST
> 
> ![Screenshot_10](https://user-images.githubusercontent.com/15394508/80021255-9ceb5380-84b0-11ea-8671-b835dfd7b1d5.png)
> 
> * MAC VERSION - CATALINA
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/15394508/80020730-dcfe0680-84af-11ea-921a-d604c9be868d.png)

Me too. Have you solved the problem

**Comment by christopherfujino** [comment] 2020-12-04 18:36
> > I am trying for days a solution to this problem and I have not been successful yet. Could someone help me?
> > Note: I tried all the solutions above ...
> > ![Screenshot_1](https://user-images.githubusercontent.com/15394508/80019784-6e6c7900-84ae-11ea-92dd-6b2931c5b6db.png)
> > 
> > * POD (COMMAND...)
> > 
> > ![Screenshot_5](https://user-images.githubusercontent.com/15394508/80020598-af18c200-84af-11ea-8a8d-06432c33adc3.png)
> > ![Screenshot_7](https://user-images.githubusercontent.com/15394508/80020609-b3dd7600-84af-11ea-89fb-891cbc4070e8.png)
> > 
> > * RUBY --VERSION
> > 
> > ![Screenshot_8](https://user-images.githubusercontent.com/15394508/80020953-35cd9f00-84b0-11ea-846d-96bd3676e3d0.png)
> > 
> > * GEM LIST
> > 
> > ![Screenshot_9](https://user-images.githubusercontent.com/15394508/80021101-6c0b1e80-84b0-11ea-86c5-c9ad4c9fa988.png)
> > 
> > * BREW LIST
> > 
> > ![Screenshot_10](https://user-images.githubusercontent.com/15394508/80021255-9ceb5380-84b0-11ea-8671-b835dfd7b1d5.png)
> > 
> > * MAC VERSION - CATALINA
> > 
> > ![Screenshot_2](https://user-images.githubusercontent.com/15394508/80020730-dcfe0680-84af-11ea-921a-d604c9be868d.png)
> 
> Me too. Have you solved the problem

You are getting that error message because the tool is running `pod --version` and getting a non-zero exit code. This is NOT an issue with the Flutter SDK, but with Cocoapods.

I am locking this issue as this issue has been resolved. TL;DR if you hit this, you have cocoapods installed, but it was installed with a different version of ruby than you currently have active. The easiest fix is to uninstall your existing cocoapods and install a fresh one, via `sudo gem install cocoapods`.
