### ISSUE TITLE
TextField: isDense will fail when isDense=true is used with hintText

### ISSUE THREAD

**Issue by xkeyC** [flutter/flutter#123532] opened 2023-03-27 09:59 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. A TextField with hintText set will display an exception 
![image](https://user-images.githubusercontent.com/39891083/227906612-bed84f4f-40d3-4840-8534-22752d9cc9b1.png)

3.Input any text, TextField without hintText works fine.
![image](https://user-images.githubusercontent.com/39891083/227907111-4b3f31e7-d218-46ba-a75f-8493702ca18c.png)

**Expected results:** 
TextField isDense: true works fine with hintText.

**Actual results:** 
TextField isDense: true When used with hintText, isDense is invalid

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const BugTest());
}

class BugTest extends StatefulWidget {
  const BugTest({Key? key}) : super(key: key);

  @override
  State<BugTest> createState() => _BugTestState();
}

class _BugTestState extends State<BugTest> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("HintText with isDense bug"),
        ),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(14),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                SizedBox(
                  height: 42,
                  child: bgCardContainer(
                      child: const Center(
                    child: TextField(
                      decoration: InputDecoration(
                          isDense: true,

                          /// If hintText is set, the input box will be offset
                          hintText: "hintText",
                          border: InputBorder.none),
                    ),
                  )),
                ),
                const SizedBox(height: 14),
                SizedBox(
                  height: 42,
                  child: bgCardContainer(
                      child: const Center(
                    child: TextField(
                      decoration: InputDecoration(
                          isDense: true,

                          /// Without hintText everything works as expected
                          // hintText: "hintText",
                          border: InputBorder.none),
                    ),
                  )),
                ),
                const SizedBox(height: 14),
                SizedBox(
                  height: 42,
                  child: bgCardContainer(
                      child: const TextField(
                    decoration: InputDecoration(
                        isDense: false,
                        hintText: "isDense false and show hintText",
                        border: InputBorder.none),
                  )),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget bgCardContainer({required Widget child}) {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(7),
        color: Colors.grey.withAlpha(30),
      ),
      child: Center(
        child: Padding(
          padding:
              const EdgeInsets.only(top: 8, bottom: 8, left: 12, right: 12),
          child: child,
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.8 on channel stable at /Users/c/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (6 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1
    • Pub download mirror http://127.0.0.1:59776/pub
    • Flutter download mirror http://127.0.0.1:59776/storage

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/c/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

I can reproduce this problem on the master channel (Flutter 3.9.0-17.0.pre.27 Framework • revision 4a1002e2e2 (13 hours ago) • 2023-03-26 22:55:12 +0200)

**Comment by huycozy** [comment] 2023-03-27 12:02
Hi @xkeyC 
Do you mean the issue is the wrong vertical alignment of the `hintText`? If so, I think this issue is similar to https://github.com/flutter/flutter/issues/86093.

**Comment by huycozy** [comment] 2023-03-28 04:47
Thanks for your response, I can confirm the problem is on Android/iOS but it looks fine on MacOS or Web.

However, issue #86093 is labeled as a framework issue and it doesn't belong to a specific platform (although its description is to happen on the Web it is also confirmed as a general issue, see https:/ /github.com/flutter/flutter/issues/86093#issuecomment-876448142).
This may be caused by visualDensity differs across platforms in Flutter versions, see https://github.com/flutter/flutter/issues/86093#issuecomment-876539863.

Since the issue behaviors are similar and should be fixed to be compatible with the latest SDK, I will close this issue in favor of #86093, and I will leave a comment there as well. Please follow up on it for further updates.

**Closed by huycozy** 2023-03-28 04:47 UTC
Labels: in triage
