### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Função incorreta., errno = 1

### ISSUE THREAD

**Issue by rafalps** [flutter/flutter#101440] opened 2022-04-06 18:38 UTC
Command
```
flutter pub add google_fonts
```

Steps to Reproduce
1. ...
2. ...
3. ...

Logs
FileSystemException: Cannot create link, OS Error: Função incorreta.
, errno = 1
```
%230      _Link.throwIfError (dart:io/link.dart:263:7)
%231      _Link.createSync (dart:io/link.dart:184:5)
%232      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%233      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
%234      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1029:12)
%235      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
%236      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
%237      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
%238      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:357:5)
<asynchronous suspension>
%239      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
%2310     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2311     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2312     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2313     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2314     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
%2315     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft
    Windows [versÃ£o 10.0.19044.1586], locale
    pt-BR)
    • Flutter version 2.10.3 at D:\Flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks
      ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android
    devices (Android SDK version 31.0.0)
    • Android SDK at
      C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program
      Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment
      (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows
    (Ferramentas de Build do Visual Studio 2019
    16.11.10)
    • Visual Studio at C:\Program Files
      (x86)\Microsoft Visual
      Studio\2019\BuildTools
    • Ferramentas de Build do Visual Studio 2019
      version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-f
      lutter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-d
      art
    • Java version OpenJDK Runtime Environment
      (build 11.0.11 9-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at
      C:\Users\PC\AppData\Local\Programs\Microsof
      t VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) •
      emulator-5556 • android-x86    • Android 10
      (API 29) (emulator)
    • Windows (desktop)                  •
      windows       • windows-x64    • Microsoft
      Windows [versÃ£o 10.0.19044.1586]
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome
      100.0.4896.75
    • Edge (web)                         • edge
      • web-javascript • Microsoft Edge
      99.0.1150.30

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
%23%23%23 Plugins
cloud_firestore-3.1.10
cloud_firestore_web-2.6.10
firebase_analytics-9.1.2
firebase_analytics_web-0.4.0 8
firebase_auth-3.3.11
firebase_auth_web-3.3.9
firebase_core-1.13.1
firebase_core_web-1.6.1
flutter_native_splash-2.0.5
google_sign_in-5.2.4
google_sign_in_web-0.10.0 5
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
smart_auth-1.0.5

**Comment by darshankawar** [comment] 2022-04-07 06:38
Closing this as duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by darshankawar** 2022-04-07 06:38 UTC
Labels: in triage
