### ISSUE TITLE
[ios] 1.20.1, "No such module" error when referring from extension module

### ISSUE THREAD

**Issue by TabooSun** [flutter/flutter#63551] opened 2020-08-12 05:57 UTC
This issue occurs when I upgrade flutter version to 1.20.1. I have "No such module" error when the imported module (AnyCodable-FlightSchool) is used in extension module.

## Steps to Reproduce

1. Add AnyCodable-FlightSchool to the Podfile

### Podfile
```Ruby

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Plugin Pods
  pod 'AnyCodable-FlightSchool', '~> 0.2.3'
end

 target 'OneSignalNotificationServiceExtension' do
   use_frameworks!
  
 end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

</details>

2. Create a swift file for importing the module

### Notification.swift
```Swift

import Foundation
import AnyCodable

public struct TNotificationPayload: Codable {
    public var additionalData: [String: AnyCodable]
}

```

3. Create a NotificationServiceExtension
4. Up till here, building has no issue. However, if the `Notification.swift` is set to be used in ServiceExtension (Show File Inspector > Target Membership > Check `NotificationServiceExtension`), the `No such module 'AnyCodable'` will occurs after clicking build.

## Logs

flutter build ios

### flutter doctor -v
```console


[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.1 at /Users/kahwaimok/Development/flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kahwaimok/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM N960F (mobile) • 192.168.1.251:5555 • android-arm64 • Android 10 (API 29)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-08-12 08:41
Hi @...
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/63018
Please read this  comment https://github.com/flutter/flutter/issues/63018#issuecomment-670601961 & https://github.com/flutter/flutter/issues/63018#issuecomment-670759935
Please follow up on that issue, I'm closing the current one as a duplicate. 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by TabooSun** [comment] 2020-08-12 11:59
I am already using the latest Podfile.

**Comment by TahaTesser** [comment] 2020-08-12 13:57
Hi @TabooSun 
I can reproduce this issue  based on the steps,

[logs.txt](https://github.com/flutter/flutter/files/5063182/logs.txt)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     • android-arm64 • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios           • iOS 13.6
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

• No issues found!
```

</details>

**Comment by TabooSun** [comment] 2020-08-25 00:41
> Ok, added this to PodFile
> 
> ```
> target 'NAME_OF_EXTENSION_TARGET' do
>   use_frameworks!
>   use_modular_headers!
> 
>   pod 'Alamofire','~> 4.9.1'
> end
> ```
> 
> Built successfully after that

Are you able to install it? I can build it but can't install.

**Comment by amantoux** [comment] 2020-08-25 06:23
> > Ok, added this to PodFile
> > ```
> > target 'NAME_OF_EXTENSION_TARGET' do
> >   use_frameworks!
> >   use_modular_headers!
> > 
> >   pod 'Alamofire','~> 4.9.1'
> > end
> > ```
> > 
> > 
> > Built successfully after that
> 
> @amantoux Are you able to install it? I can build it but can't install.

Yes managed to install it

**Comment by TabooSun** [comment] 2020-08-29 09:08
```
Details

Unable to install "Runner"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653028
--
The bundle’s Info.plist does not contain a CFBundleVersion key or its value is not a string.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653028
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800009C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000122dbb81a DTDKCreateNSErrorFromAMDErrorCode + 233
	1   DTDeviceKitBase                     0x0000000122dfcf70 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000109c65f35 DVTInvokeWithStrongOwnership + 73
	3   DTDeviceKitBase                     0x0000000122dfcca8 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1654
	4   IDEiOSSupportCore                   0x0000000122c73e91 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4165
	5   DVTFoundation                       0x0000000109d995d4 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000109d9b216 __DVTDispatchAsync_block_invoke + 1194
	7   libdispatch.dylib                   0x00007fff7356e6c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff7356f658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff73574c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff735755d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff7357ec09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff737c9a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff737c8b77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 11.6 (16141)
```

Following @amantoux workaround, I got this error.

**Comment by TabooSun** [comment] 2020-09-09 01:50
> ```
> Details
> 
> Unable to install "Runner"
> Domain: com.apple.dt.MobileDeviceErrorDomain
> Code: -402653028
> --
> The bundle’s Info.plist does not contain a CFBundleVersion key or its value is not a string.
> Domain: com.apple.dt.MobileDeviceErrorDomain
> Code: -402653028
> User Info: {
>     DVTRadarComponentKey = 261622;
>     MobileDeviceErrorCode = "(0xE800009C)";
>     "com.apple.dtdevicekit.stacktrace" = (
> 	0   DTDeviceKitBase                     0x0000000122dbb81a DTDKCreateNSErrorFromAMDErrorCode + 233
> 	1   DTDeviceKitBase                     0x0000000122dfcf70 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
> 	2   DVTFoundation                       0x0000000109c65f35 DVTInvokeWithStrongOwnership + 73
> 	3   DTDeviceKitBase                     0x0000000122dfcca8 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1654
> 	4   IDEiOSSupportCore                   0x0000000122c73e91 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4165
> 	5   DVTFoundation                       0x0000000109d995d4 __DVT_CALLING_CLIENT_BLOCK__ + 7
> 	6   DVTFoundation                       0x0000000109d9b216 __DVTDispatchAsync_block_invoke + 1194
> 	7   libdispatch.dylib                   0x00007fff7356e6c4 _dispatch_call_block_and_release + 12
> 	8   libdispatch.dylib                   0x00007fff7356f658 _dispatch_client_callout + 8
> 	9   libdispatch.dylib                   0x00007fff73574c44 _dispatch_lane_serial_drain + 597
> 	10  libdispatch.dylib                   0x00007fff735755d6 _dispatch_lane_invoke + 363
> 	11  libdispatch.dylib                   0x00007fff7357ec09 _dispatch_workloop_worker_thread + 596
> 	12  libsystem_pthread.dylib             0x00007fff737c9a3d _pthread_wqthread + 290
> 	13  libsystem_pthread.dylib             0x00007fff737c8b77 start_wqthread + 15
> );
> }
> --
> 
> 
> System Information
> 
> macOS Version 10.15.6 (Build 19G2021)
> Xcode 11.6 (16141)
> ```
> 
> Following @amantoux workaround, I got this error.
> 
> I notice that the FLUTTER_BUILD_NAME and FLUTTER_BUILD_NUMBER is not copied to the extension module.

Workaround found for this issue by changing the Info.plist of extension module:

- Change the value of `CFBundleShortVersionString` from $(FLUTTER_BUILD_NAME) to $(MARKETING_VERSION)
- Change the value of `CFBundleVersion` from $(FLUTTER_BUILD_NUMBER) to $(CURRENT_PROJECT_VERSION)

**Comment by tp** [comment] 2020-10-11 15:20
> The bundle's Info.plist does not contain a CFBundleVersion key or its value is not a string.

@TabooSun Did you find a fix? Also running into this with Flutter 1.20.4.

**Comment by tp** [comment] 2020-10-11 16:07
We got to fix the `The bundle's Info.plist does not contain a CFBundleVersion key or its value is not a string.` error, but setting the build configuration for the `NotificationService` in Xcode as well, e.g. 

![image](https://user-images.githubusercontent.com/52437/95683571-823aa180-0bec-11eb-9611-53e84ef6b137.png)

I think before it was inherited from the parent, but this changed in https://github.com/flutter/flutter/pull/54691.

**Comment by ChetanAhuja** [comment] 2022-09-28 00:07
Any progress on this issue? Or a reliable workaround?

**Comment by darshankawar** [comment] 2024-04-10 11:30
@TabooSun 
I followed the details you mentioned in original description and ran a sample app using latest stable version (3.19.5) through Xcode with which I was able to compile and run the app without any issues.
I added the said pod, notification.swift and NSE but I am not sure how to set below you mentioned:



> 4\. However, if the `Notification.swift` is set to be used in ServiceExtension (Show File Inspector > Target Membership > Check `NotificationServiceExtension`),

Can you try this issue again at your end with latest stable to confirm if the issue you had reported persist or not ? 
If so, please provide us updated steps to properly address the issue.

**Comment by TabooSun** [comment] 2024-04-10 12:42
Unfortunately, I don't have access to that repo now, it's hard for me to reproduce it.

**Comment by darshankawar** [comment] 2024-04-11 05:24
I am going ahead and closing this due to lack of updated reproducible code sample pertaining to latest stable. If anybody in this thread still facing same issue using latest version, please open a new issue with relevant details so that we can properly address it.

**Closed by darshankawar** 2024-04-11 05:24 UTC
Labels: platform-ios, tool, t: xcode, has reproducible steps, P2, found in release: 1.20, team-ios, triaged-ios
