### ISSUE TITLE
Flutter build apk and appbundle not working as expected in release mode. Works fine in debug.

### ISSUE THREAD

**Issue by gogappi** [flutter/flutter#63454] opened 2020-08-11 04:40 UTC
## Steps to Reproduce

1. Prepare app for release as mentioned here https://flutter.dev/docs/deployment/android
2. Build apk or appbundle using flutter build apk --release --flavor dev -t lib\main_dev.dart
3. Install on device
4. While the apk works perfectly on debug mode certain api calls fail in release mode. API calls that fail are being made to aws lambda and google places.

NOTES:
a) App works perfectly in release mode using flutter run --release
b) APK and Appbundle work perfectly in release mode when compiled using Generate Signed Bundle / APK IDE on Android studio.
c) INTERNET permission has been included in AndroidManifests.xml
d) Correct keys have been provided to API providers.
e) Few network calls. For instance calls to Firebase/ Firestore is working perfectly. Network images are loading perfectly. Sign in with google and firebase is also working. 

```
```

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale en-IN)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Arvind\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Arvind\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Arvind\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Redmi K20 Pro (mobile) • a33b111e • android-arm64 • Android 10 (API 29)

• No issues found!
</details>

**Comment by tewshi** [comment] 2020-08-11 06:19
Any heads up on this, I've been stuck here for two days now.

**Comment by TahaTesser** [comment] 2020-08-11 11:47
Hi @gogappi  @tewshi 
Tried to reproduce network call issue in release mod using `flutter build apk --release --flavor dev -t lib\main_dev.dart`

[app-dev-release.apk.zip](https://github.com/flutter/flutter/files/5056730/app-dev-release.apk.zip)


<details> 
<summary>build.gradle</summary> 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.stable_flutter"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            signingConfig signingConfigs.debug
        }

        staging {
            debuggable true
            applicationIdSuffix '.staging'
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }

        release {
            signingConfig signingConfigs.debug
        }
    }

    flavorDimensions "app"
    productFlavors {

        dev {
            dimension "app"
            resValue "string","app_name","Dev FlavorTest"
            versionName "1.0"
        }

    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

``` 

</details> 

<details> 
<summary>main_dev.dart</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Stack(
        children: <Widget>[
          Center(child: CircularProgressIndicator()),
          Center(
            child: FadeInImage.assetNetwork(
              placeholder: 'assets/flutter.png',
              image: 'https://i.imgur.com/QCNbOAo.png',
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Taha>flutters doctor -v
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
• 
```

</details> 


Can you please provide  your ` flutter run --release --flavor dev -t lib\main_dev.dart -v` and a complete reproducible minimal code sample and give us more details of the issue

Thank you

**Comment by gogappi** [comment] 2020-08-11 12:34
Hi @TahaTesser

flutter **run** --release produces no errors. I encounter errors in flutter **build** --release. Do you want me to provide -v for run or build?

**Comment by TahaTesser** [comment] 2020-08-11 14:14
@gogappi 
Can you please provide a complete reproducible minimal code sample and steps by steps to reproduce 
Thank you

**Comment by gogappi** [comment] 2020-08-12 13:42
@TahaTesser 
I found the issue. The problem was that flutter build automatically shrinks the code with R8. flutter build --no-shrink solved the problem. I guess I need to add all required exceptions to the proguard-rules.pro file.

**Comment by TahaTesser** [comment] 2020-08-13 07:28
Hi @gogappi 
Glad you found the cause, it's part of release preparation, not an issue with Itself
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-13 07:28 UTC
Labels: in triage
