### ISSUE TITLE
Terminal intercepts keyboard while typing in chrome for a local deployment

### ISSUE THREAD

**Issue by benmeemo** [flutter/flutter#55337] opened 2020-04-21 21:57 UTC
## Steps to Reproduce

1. Run a flutter web program from terminal with 
```
flutter run -d chrome
```
2. Type anywhere in the resulting chrome window (for example, trying to go to a new url, or entering text in a textfield)

**Expected results:** The browser captures the keystrokes

**Actual results:** The terminal captures the keystrokes

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.14.6 at /Users/benulmer/development/flutter
    • Framework revision fabeb2a16f (3 months ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/benulmer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (3 available)
    • iPhone 8   • 0FB7FC72-6677-4D7D-87D4-38C51D4AEB8A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2020-04-22 00:40
This doesn't reproduce for me. Are you sure this is an issue with flutter and not a window manager specific problem?

I'm not sure how a CLI could steal focus from a browser

**Comment by benmeemo** [comment] 2020-04-22 01:51
I'm not sure either - this isn't a normal chrome instance though right, this is a chrome run from dart tools, which is ran from the terminal?

**Comment by jonahwilliams** [comment] 2020-04-22 02:09
its just chrome

**Comment by iapicca** [comment] 2020-04-22 08:16
Hi @benmeemo 
I tried w/ the latest master and I cannot reproduce the behaviour you are describing,
could you please run `flutter upgrade --force`,
let me know if the issue persists
Thank you

**Comment by TahaTesser** [comment] 2020-05-22 12:50
Hi @benmeemo 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution

**Closed by TahaTesser** 2020-05-22 12:50 UTC
Labels: in triage, waiting for customer response
