### ISSUE TITLE
Autocomplete replace next word

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#135412] opened 2023-09-25 10:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Put cursor in the middle of word
2) Call autocomplete window
3) Press enter to insert text from autocomplete window

### Expected results

Text from autocomplete window must be inserted without changing anything in the document

### Actual results

Text from autocomplete window replace current word

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[flutter] flutter doctor -v

```
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale ru-RU)
    • Flutter version 3.13.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\dev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] VS Code, 64-bit edition (version unknown)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.72.0
    X Unable to determine VS Code version.

[√] Connected device (5 available)
    • ZB602KL (mobile)  • J6AXB7654974VZ8 • android-arm64  • Android 9 (API 28)
    • SM T970 (mobile)  • R52N71EFXPN     • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.

• No issues found!
exit code 0
```

**Comment by dam-ease** [comment] 2023-09-25 14:29
Hi @alex9153. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by alex9153** [comment] 2023-09-28 13:58
<img width="537" alt="1" src="https://github.com/flutter/flutter/assets/353832/c3e956d7-f58e-4d4a-8cf6-87b00fd4ef4f">
<img width="585" alt="2" src="https://github.com/flutter/flutter/assets/353832/42078eef-41d9-45d5-aa2e-5245dbd13e03">
<img width="540" alt="3" src="https://github.com/flutter/flutter/assets/353832/8d39a392-030b-4cc5-bd8e-56b8427698d7">

And should be so: 

<img width="606" alt="4" src="https://github.com/flutter/flutter/assets/353832/c8ab8a51-5563-48f7-9d34-10dbc8ef4441">

**Comment by alex9153** [comment] 2023-09-28 13:59
<img width="287" alt="Снимок экрана 2023-09-28 165836" src="https://github.com/flutter/flutter/assets/353832/8b293453-f8aa-4578-8246-4f82ac634478">

**Comment by dam-ease** [comment] 2023-09-28 14:50
Hi @alex9153. This seems to be the expected behavior, the name gets selected and changed once you press enter. Do you have a different behavior in another IDE or elsewhere?

**Comment by alex9153** [comment] 2023-09-29 17:45
I'm not using another IDE. Current behaviour is not convenient. Can you fix this?

**Comment by dam-ease** [comment] 2023-10-02 07:32
Hi @alex9153. Thanks for your response. This is an expected behaviour, clicking either in the middle or at the beginning of the property selects it and replaces the property with the selected suggestion. I tested this with another IDE aside Visual Studio Code (Android Studio) and this seems to be the behaviour reproduced as well. If you have seen your suggested behaviour in works elsewhere and would like to propose this in Flutter, kindly file a detailed proposal describing this in detail.
I'd be closing this as this isn't an issue with Flutter itself, if you disagree, please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-10-02 07:32 UTC
Labels: in triage
