### ISSUE TITLE
[local_auth] Implement touchid on MacOS

### ISSUE THREAD

**Issue by marwan-at-work** [flutter/flutter#124180] opened 2023-04-05 03:06 UTC
Hi there,

The [local_auth](https://pub.dev/packages/local_auth) package currently supports TouchID and FaceID on iOS but TouchID is not implemented for MacOS. 

Would it be possible to implement a macos version that leverages TouchID? My only reference is the Go package that calls out to C code for running touchid: https://github.com/lox/go-touchid/blob/master/touchid.go

Thanks!

Marwan,

**Comment by danagbemava-nc** [comment] 2023-04-05 07:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/70270.

Kindly subscribe to the original issue for updates. Please upvote the issue as well

Thank you

**Closed** 2023-04-05 07:23 UTC
Labels: r: duplicate
