### ISSUE TITLE
<NotificationListener>scrolling issue

### ISSUE THREAD

**Issue by Moyout** [flutter/flutter#137676] opened 2023-11-01 09:30 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using the 'NotificationListener' component, the direction of vertical scrolling cannot be determined. My test is that in the vertical direction, the result of sliding up and down is the same, always' AxisDirection. down '

### Expected results

The direction of scrolling is opposite, and the result should also be opposite, rather than the same result "AxisDirection. down"

### Actual results

Always ' AxisDirection. down '

### Code sample

<details><summary>Code sample</summary>

```dart
NotificationListener<ScrollNotification>(
        onNotification: (ScrollNotification scrollNotification) {
          // debugPrint("v-------------------->${scrollNotification}");
          debugPrint(" ----------- --------->${scrollNotification.metrics.axisDirection}");
          // if (scrollNotification.metrics.axis == Axis.vertical) {
          //   if (scrollNotification is ScrollStartNotification) {
          //     // debugPrint(" -------------------->${scrollNotification}");
          //     // debugPrint(" axis-------------------->${scrollNotification.metrics.axis}");
          //     // debugPrint(" -----------2--------->${scrollNotification.metrics.axisDirection}");
          //   } else if (scrollNotification is ScrollUpdateNotification) {
          //     // debugPrint(" -----------2--------->${scrollNotification.metrics.axisDirection}");
          //   } else if (scrollNotification is ScrollEndNotification) {
          //     // debugPrint(" -----------3-------->${scrollNotification}");
          //   }
          // }

          return true;
        },)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
flutter:  ----------- --------->AxisDirection.down
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 xxxxx % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by Moyout** [comment] 2023-11-01 09:31
somebody help

**Comment by dam-ease** [comment] 2023-11-01 11:26
Hi @Moyout. Thanks for filing this. I can reproduce this on the latest `master` and `stable` channels using the sample below. This seems to be the expected behaviour https://github.com/flutter/flutter/issues/13010#issuecomment-344360204 and the documentation and example code has been updated to reflect this per this PR https://github.com/flutter/flutter/pull/123819/. You could also read through for more details on this.
Closing this as it seems to be the expected behaviour.
Thank you!

**Closed by dam-ease** 2023-11-01 11:26 UTC
Labels: in triage
