### ISSUE TITLE
CustomPainter with LinearGradient shader and blur MaskFilter show clipping error with 3.24.3

### ISSUE THREAD

**Issue by AlessandroMulloni** [flutter/flutter#155930] opened 2024-09-30 12:41 UTC
### Steps to reproduce

I am making extensive usage of custom painters in an app. A recent update from 3.22.1 to 3.24.3 broke many of my shaders.

I created below a minimal widget to reproduce the issue. 

It seems that custom painters in a sliver-based scroll view are clipped by a certain amount of pixels. The amount of clipping seems proportional to the pixels of the top app bar visible on screen.

### Expected results

This was the previous behaviour with Flutter 3.22.1

https://github.com/user-attachments/assets/2f8b1954-5bd1-43ec-877d-2b7631023a5e

### Actual results

This is the current behaviour with 3.24.3

https://github.com/user-attachments/assets/33394183-b750-4d9f-a902-bdadec0baad5

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class BlurTestWidget extends StatelessWidget {
  const BlurTestWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) => [
          const SliverAppBar(
            title: Text('Blur + Gradient Test'),
          ),
        ],
        body: CustomScrollView(
          physics: const BouncingScrollPhysics(decelerationRate: ScrollDecelerationRate.fast),
          slivers: List.filled(
            5,
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(32.0),
                child: AspectRatio(
                  aspectRatio: 2,
                  child: CustomPaint(painter: _BlurTestPainter()),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class _BlurTestPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final rect = Rect.fromLTWH(0, 0, size.width, size.height);

    final shader = const LinearGradient(
      colors: [Colors.red, Colors.blue],
    ).createShader(rect);

    var paint = Paint()
      ..shader = shader
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 10.0)
      ..strokeWidth = 20
      ..style = PaintingStyle.stroke;

    canvas.drawOval(rect, paint);
  }

  @override
  bool shouldRepaint(covariant _BlurTestPainter o) => true;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-30 13:29
Reproducible using the code sample provided above with impeller. It works as expected with skia. This worked fine in stable 3.22.3 but not on stable 3.24.3. Master has a better behavior (as compared to the current stable) but it is still not close to stable 3.22.3


| stable 3.22.3 | stable 3.24.3 | master | 
| -- | -- | -- |
| <video src="https://github.com/user-attachments/assets/685f4960-00ce-4693-bc75-481cd47e212c" /> | <video src="https://github.com/user-attachments/assets/dca416f7-b746-4f36-a5a4-11d2332411a4" /> | <video src="https://github.com/user-attachments/assets/8ac5b4ab-b030-48ea-9c9b-f4baed7d590f" /> |

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

```

```
[!] Flutter (Channel master, 3.26.0-1.0.pre.263, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.26.0-1.0.pre.263 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4fdfbd4dde (31 hours ago), 2024-09-29 02:21:39 -0400
    • Engine revision 569abc4044
    • Dart version 3.6.0 (build 3.6.0-279.0.dev)
    • DevTools version 2.40.0-dev.1

```
</details>

**Comment by chinmaygarde** [comment] 2024-09-30 17:37
@jason-simmons is going to try to reproduce this.

**Comment by jason-simmons** [comment] 2024-10-01 21:46
This appears to be related to the changes in https://github.com/flutter/engine/commit/7f8033ffa7211e951ed69dc572796c44e9263fbe.  `GaussianBlurFilterContents::RenderFilter` is rendering the content to a snapshot using a transform containing only the scale factor extracted from the original entity.

In this example, the original entity's transform also includes a translation.  The content is clipped when the snapshot is rendered without that translation.

@gaaclarke @bdero

**Comment by jonahwilliams** [comment] 2024-10-07 20:16
This seems to work for me at HEAD, was this fixed with the recent changes to the mask blur transformation? FYI @gaaclarke

**Comment by jonahwilliams** [comment] 2024-10-07 20:20
Actually, I still see that some parts of the shape are cut off:

![image](https://github.com/user-attachments/assets/a77a7e56-86b0-4500-b90b-bba9e48eaa66)


Maybe we're mis-estimating the bounds?

**Comment by jonahwilliams** [comment] 2024-10-07 22:17
![image](https://github.com/user-attachments/assets/ab7a4323-d14f-4645-8dc7-f15a81347063)

Looks like the snapshot used by the gaussian blur is shifted incorrectly:

![image](https://github.com/user-attachments/assets/0dbebfa9-fd66-4708-af79-1d882bc6a95d)

**Comment by gaaclarke** [comment] 2024-10-07 22:25
@jonahwilliams is that the input to the downsample pass or the output of the downsample pass?  Weird if it is the input since setting the sigma to 0 results in no clipping.

**Comment by jonahwilliams** [comment] 2024-10-07 22:32
Input.

**Comment by gaaclarke** [comment] 2024-10-07 22:32
Responding to my own question.  That is the snapshot which is the input to downsample pass.  There is another mechanism that will avoid the blur with a radius zero.  The following diff demonstrates the problem but bypasses all of the blur except the snapshot:
```diff
--- a/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
+++ b/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
@@ -666,6 +666,8 @@ std::optional<Rect> GaussianBlurFilterContents::GetFilterCoverage(
       Point(blur_info.local_padding.x, blur_info.local_padding.y));
 }
 
+static bool foo = true;
+
 // A brief overview how this works:
 // 1) Snapshot the filter input.
 // 2) Perform downsample pass. This also inserts the gutter around the input
@@ -712,8 +714,8 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
     return std::nullopt;
   }
 
-  if (blur_info.scaled_sigma.x < kEhCloseEnough &&
-      blur_info.scaled_sigma.y < kEhCloseEnough) {
+  if (foo || (blur_info.scaled_sigma.x < kEhCloseEnough &&
+      blur_info.scaled_sigma.y < kEhCloseEnough)) {
     Entity result =
         Entity::FromSnapshot(input_snapshot.value(),
                              entity.GetBlendMode());  // No blur to render.
```

**Comment by gaaclarke** [comment] 2024-10-08 00:22
I have a hack that fixes the math: https://github.com/flutter/engine/pull/55717. I'll clean it up tomorrow.

**Closed** 2024-10-08 22:20 UTC
Labels: c: regression, engine, c: rendering, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.24, found in release: 3.26
