### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by ranasaim3215** [flutter/flutter#69565] opened 2020-11-02 11:09 UTC
## Command
```
flutter run --machine --target lib\main.dart -d NVAEMNI7VW7S69FY --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:26:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:677:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1165:11)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:264:11)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.2 at C:\flutter
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\PACE COMPUTERS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\PACE COMPUTERS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • A1601 (mobile) • NVAEMNI7VW7S69FY • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.7.5+3001
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
app_settings-4.0.0
apple_sign_in-0.1.0
connectivity-0.4.8+6
connectivity_macos-0.1.0+5
facebook_audience_network-0.6.1
firebase_admob-0.9.3+2
firebase_analytics-5.0.14
firebase_auth-0.15.3
firebase_auth_web-0.1.3+1
firebase_core-0.4.4
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_messaging-6.0.16
flutter_facebook_login-3.0.0
flutter_keyboard_visibility-0.7.0
flutter_plugin_android_lifecycle-1.0.11
flutter_statusbarcolor-0.2.3
flutter_webview_plugin-0.3.11
google_maps_flutter-0.5.28+1
google_sign_in-4.5.1
google_sign_in_web-0.9.2
location-3.0.2
location_web-1.0.0
notification_permissions-0.4.4
onesignal_flutter-2.4.1
path_provider-1.6.22
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
rate_my_app-0.6.1+3
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.2+1
uni_links-0.4.0
url_launcher-5.4.10
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.5
video_player-0.10.11+1
video_player_web-0.1.4
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by darshankawar** [comment] 2020-11-02 11:28
@ranasaim3215 
This issue is already fixed and merged, but only available in master. Please see [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment.
Please switch to latest master and try again to see if it works.
I am going ahead and closing this as fixed. If you disagree or think the issue is still occuring on master, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-11-02 11:28 UTC
