### ISSUE TITLE
Flutter Stable 1.20.0 - iOS only - print command is adding extra new lines to every output

### ISSUE THREAD

**Issue by animeshjain** [flutter/flutter#63082] opened 2020-08-06 13:15 UTC
## Steps to Reproduce

Sample program
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      print("counter = $_counter");
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Expected results:**
```
...
flutter: counter = 0
flutter: counter = 1
flutter: counter = 2
...
```

**Actual results:** 
```
Launching lib/main.dart on 6s in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ***
Running Xcode build...
Xcode build done.                                           34.0s
Installing and launching...
Waiting for 6s to report its views...
Debug service listening on ws://localhost:60847/ws
Syncing files to device 6s...
flutter: counter = 0


flutter: counter = 1


flutter: counter = 2


flutter: counter = 3

...
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.20.0 at /Users/***/Library/flutter
    • Framework revision 840c9205b3 (33 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/***/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8580

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • A0001 (mobile)     • ***                                 • android-arm • Android 6.0.1 (API 23)
    • 6s (mobile) • *** • ios         • iOS 13.5.1

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-08-06 14:20
hI @animeshjain 
i can reproduce this issue in Android Studio but no issues in VS Code
### Android Studio 
```
Launching lib/main.dart on Taha’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running pod install...
Running Xcode build...
Xcode build done.                                           16.5s
Installing and launching...
Waiting for Taha’s iPhone to report its views...
Debug service listening on ws://localhost:51475/ws
Syncing files to device Taha’s iPhone...
flutter: counter = 0


flutter: counter = 1


flutter: counter = 2


flutter: counter = 3


flutter: counter = 4


flutter: counter = 5


flutter: counter = 6


flutter: counter = 7


flutter: counter = 8


flutter: counter = 9



```


### VS Code 

```
Launching lib/main.dart on Taha's iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           17.6s
Installing and launching...
Connecting to VM Service at ws://localhost:50989/ws
flutter: counter = 0
flutter: counter = 1
flutter: counter = 2
flutter: counter = 3
flutter: counter = 4
flutter: counter = 5
flutter: counter = 6
```


<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      print("counter = $_counter");
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0 at /Users/taha/Code/flutter_stable
    • Framework revision 840c9205b3 (34 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • SM M305F (mobile)  • 32003c30dc19668f                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details> 


Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by BoshiLee** [comment] 2020-08-07 07:12
did someone try on flutter 1.17? It work fine on android studio

**Comment by bbmanuputty** [comment] 2020-08-11 22:25
I have this same issue it's driving me crazy, stable channel latest update

**Comment by zanderso** [comment] 2020-08-17 16:47
The tool seems to be retaining a newline when the log messages come from the Dart vmservice. /cc @jonahwilliams

**Closed** 2020-08-17 19:26 UTC
Labels: P3, a: annoyance, tool

**Comment by kuhnroyal** [comment] 2020-08-17 19:31
Can this be picked into stable?
