### ISSUE TITLE
PageView overlayed inside Stack not swiping

### ISSUE THREAD

**Issue by rubinbasha** [flutter/flutter#69247] opened 2020-10-28 22:00 UTC
I am trying to create a UI that contains a Stack and as children I have PageView and SomeContent(even just a Container is enough to reproduce the issue). When having this kind of configuration then the PageView does not swipe.

## Steps to Reproduce

```
Stack(
	fit: StackFit.expand,
	children: [
		PageView.builder(
			controller: _controller,
			itemCount: 3,
			itemBuilder: (context, index) {
				var randomNr = Random().nextInt(400) + 400;
				return CachedNetworkImage(
					imageUrl: /* it.imageUrl */ "https://picsum.photos/$randomNr",
					fit: BoxFit.cover,
				);
			},
		),
		Opacity(
			opacity: .4,
			child: Container(
				color: CustomColors.black,
			),
		),
	],
)
```

**Expected results:** 
The PageView reacts to user input.

**Actual results:** 
The PageView does not react at all

**Comment by rubinbasha** [comment] 2020-10-28 22:32
I found a halfbaked solution and that is to add a GestureDetector on top of PageView
like this:
var acceptedDeltaY = MediaQuery.of(context).size.height / 50;
GestureDetector(
          onPanUpdate: (data) {
            var deltaY = data.delta.dy;
            if (deltaY < 0 && deltaY.abs() > acceptedDeltaY) {
              _controller.nextPage(
                duration: const Duration(seconds: 1),
                curve: Curves.easeIn,
              );
            }
            if (deltaY > 0 && deltaY.abs() > acceptedDeltaY) {
              _controller.previousPage(
                duration: const Duration(seconds: 1),
                curve: Curves.easeIn,
              );
            }
          },
    child: Stack (...the config above...)
)

I also did add to the PageView
physics: const NeverScrollableScrollPhysics(),

I am nonetheless disappointed that I actually had to face this issue as this should maybe have been just working out of the box. I would not consider the issue solved at this point, I just gave a workaround here for other people that might have the same issue as I have.

**Comment by ponnamkarthik** [comment] 2020-10-29 01:50
Hello @rubinbasha the issue is Opacity is covering the enter stack and its over the pageview so gestures are working with pageview

we can wrap Opacity in `IgnorePointer` which make pageview to work

```dart
Stack(
      fit: StackFit.expand,
      children: [
        PageView.builder(
          controller: _controller,
          itemCount: 3,
          itemBuilder: (context, index) {
            var randomNr = Random().nextInt(400) + 400;
            return Image.network(
              "https://picsum.photos/$randomNr",
              fit: BoxFit.cover,
            );
          },
        ),
        IgnorePointer(
          child: Opacity(
            opacity: .4,
            child: Container(
              color: Colors.black,
            ),
          ),
        )
      ],
    )
```

**Comment by darshankawar** [comment] 2020-10-29 08:02
@rubinbasha Please check above solution and see if it resolves your issue. 
Thanks.

**Comment by rubinbasha** [comment] 2020-10-29 08:51
I did try wrapping Opacity in an IgnorePointer but that unluckily did not solve the issue.

**Comment by chinmoy12c** [comment] 2020-10-29 09:50
@rubinbasha use github markdown, encapsulate your code with three back quotes( ` ).

**Comment by darshankawar** [comment] 2020-10-29 10:58
@rubinbasha 
I tried the code sample as mentioned [above](https://github.com/flutter/flutter/issues/69247#issuecomment-718307660) and was able to swipe properly without any issues.

[69247.mp4.zip](https://github.com/flutter/flutter/files/5457821/69247.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.82, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-4.0.pre.82 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e5814756a2 (2 days ago), 2020-10-27 01:47:03 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!

```

</details>

Closing this as non-issue after using the above referred updated code. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-29 10:58 UTC
Labels: in triage

**Comment by rubinbasha** [comment] 2020-10-30 10:51
@ponnamkarthik thank you for the solution, it works, hip hip hurraaaayy.

@darshankawar yep we can close the issue as now we have a solution for anyone having the same issue. The strange thing is that I have also other things overlaying/covering my PageView but from what I tested more, the Container that has a color is the one actually hijacking the pointer. That is kinda unexpected, to be honest, seems like yet another trick that gets learned only when it hurts and can't be prevented from our devs.

@chinmoy12c thank you for the hint
