### ISSUE TITLE
Flutter is keeping the previous log on mac

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#49858] opened 2020-01-31 04:54 UTC
## Steps to Reproduce

On Mac Mojave 10.14.6
1. Use android studio to create a sample flutter project
2. add print("This is the logs...."); to initState()
```
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    print("This is the logs....");
  }
```
3. Run app on an android device, "This is the logs...." is printed on console
4. Stop the app, comment out the log and run again
```
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

//    print("This is the logs....");
  }
```

**Expected results:** Log is not printed.

**Actual results:** Log is printed again
```
Launching lib/main.dart on SM J730F in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
I/flutter ( 9763): This is the logs....
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM J730F...
```

This is especially annoying when you previously saw an error, then you fix it but it still keeps popping up. It seems like this only happens on Mac and the only way to get rid of it is to restart the device.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G2022, locale en-NZ)
    • Flutter version 1.12.13+hotfix.7 at /Users/jayhuang/Development/flutter/sdk
    • Framework revision 9f5ff2306b (4 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jayhuang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jayhuang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • MotoG3            • ZY2222HDH5                               • android-arm • Android 6.0 (API 23)
    • Pengfei's iPhone  • 2256178a00be70a423115c0eeb12af7720c3f928 • ios         • iOS 12.3.1
    • iPhone 11 Pro Max • F8D17509-18C5-4B58-83DD-5A16B787C17A     • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

```

**Comment by dnfield** [comment] 2020-01-31 06:56
Duplicate of https://github.com/flutter/flutter/issues/47629

**Closed by dnfield** 2020-01-31 06:56 UTC
