### ISSUE TITLE
After upgrade socket exception crashes everywhere where use http

### ISSUE THREAD

**Issue by geovaniprodata** [flutter/flutter#127107] opened 2023-05-18 14:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create any http request, current `http: ^0.13.6 | dio: ^5.1.2 | http_parser: ^4.0.2`
2. Tried downgrade these packages
3. Tried normal flutter clean + flutter pub get
4. Tried flutter pub cache clean + flutter pub get 
5. Tried catch the SocketException but no success.
6. Only debug the error is triggering, `Flutter onError` function doesn't get him
7. Release mode the error doesn't crash or pause the App, just ignored.
8. The response from the request is returned normally

### Expected results

The response returns without any crashes or any exceptions.

### Actual results

SocketException in the lookup host address

### Code sample

<details><summary>Code sample</summary>

```dart

var response;

var statusCode;

var dio = Dio()..options.baseUrl = endpoints['spl']!;

    try {
      Response request = await dio.get(
        'ol/getmkt.php',
        queryParameters: teste
            ? {
                "codemp": idpn,
                "token": getToken(add1day: tryagain),
                "teste": testeValue,
              }
            : {
                "codemp": idpn,
                "token": getToken(add1day: tryagain),
              },
        options: Options(
          method: 'GET',
          listFormat: ListFormat.multiCompatible,
          validateStatus: (status) {
            if ([400, 401, 403, 404].contains(status)) {
              return false;
            } else {
              return true;
            }
          },
        ),
      );

      statusCode = request.statusCode;

      if (statusCode == 200) {
        response = jsonDecode(request.data);
      }
} catch (error) {
    erroModal.error = true;
    tryg = true;
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![ss SOCKET EXCP](https://github.com/flutter/flutter/assets/48528512/d27d578e-3184-4295-a8a4-a17082e126c5)

Tested the API with Insomnia works fine!!!

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-6.0.pre.37, on Microsoft Windows [versÆo 10.0.22000.1696], locale pt-BR)
    • Flutter version 3.11.0-6.0.pre.37 on channel master at F:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa117aad28 (7 days ago), 2023-05-11 10:28:08 -0700    • Engine revision f38f46f66e
    • Dart version 3.1.0 (build 3.1.0-94.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at F:\Android\android-sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = F:\Android\android-sdk
    • ANDROID_SDK_ROOT = F:\Android\android-sdk
    • Java binary at: F:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.2)
    • Visual Studio at G:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at F:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • SM M315F (mobile) • 192.168.0.76:5555 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows           • windows-x64    • Microsoft Windows [versÆo 10.0.22000.1696]
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 113.0.5672.94

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-05-19 06:29
@geovaniprodata 
Please check if your case is similar to https://github.com/flutter/flutter/issues/126650 and go through underlying comments for further reference.

**Comment by ziyadgodil** [comment] 2023-05-19 06:47
@geovaniprodata 
It looks like there can be some problem from server side try executing api in postman.
are getting proper response in postman or getting same error also in postman ?
if you are getting same error in postman also then there can be problem from server side.
and if you are getting proper response from postman then there is problem in your code make sure you have implemented packages properly and try again

**Comment by geovaniprodata** [comment] 2023-05-28 15:50
> @geovaniprodata 
> It looks like there can be some problem from server side try executing api in postman.
> are getting proper response in postman or getting same error also in postman ?
> if you are getting same error in postman also then there can be problem from server side.
> and if you are getting proper response from postman then there is problem in your code make sure you have implemented packages properly and try again

Downloaded an example case using http, the same error.

Using insomnia and postman, works fine.

**Comment by huycozy** [comment] 2023-05-29 04:17
@geovaniprodata I see there is a fix has landed recently (see https://github.com/flutter/flutter/issues/126650#issuecomment-1558206791). Can you check this again on the latest master channel to see if it's fixed or not?

Also, if the issue still persists, please:
- Make sure you have declared all internet permissions if you are checking this on mobile platforms
- Check if there is any difference between postman and dart code (header, params, proxy, etc)

**Comment by geovaniprodata** [comment] 2023-05-29 12:15
> @geovaniprodata I see there is a fix has landed recently (see [#126650 (comment)](https://github.com/flutter/flutter/issues/126650#issuecomment-1558206791)). Can you check this again on the latest master channel to see if it's fixed or not?
> 
> Also, if the issue still persists, please:
> 
> * Make sure you have declared all internet permissions if you are checking this on mobile platforms
> * Check if there is any difference between postman and dart code (header, params, proxy, etc)

I checked out, aparently it's a parse for the address host, which is throwing the common exception like ArgumentError, there's a way to get the Dart-SDK commit by the author ? it seems he solved by adding the tryParse statement.

**Comment by huycozy** [comment] 2023-05-30 04:13
@geovaniprodata Do that mean it's fixed on master channel? 

As he mentioned in that comment, it should be on Dart 3.0.2 and it's on Flutter 3.10.2. You may also check it on the latest stable as well.

**Comment by geovaniprodata** [comment] 2023-05-30 13:06
@huycozy Nope, it's on dev channel, unfortunately.

[3.1.0-155.0.dev](https://github.com/dart-lang/sdk/releases/tag/3.1.0-155.0.dev)

**Comment by huycozy** [comment] 2023-05-31 03:35
I check this with example at [fetch-data](https://docs.flutter.dev/cookbook/networking/fetch-data#complete-example) but can not see the issue. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.

**Closed** 2023-06-21 04:10 UTC
Labels: waiting for customer response, in triage
