### ISSUE TITLE
Correct CupertinoAlertDialog divider colors

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20469] opened 2018-08-10 23:57 UTC
After #18381 is merged in and is dedup'd against the similar Action Sheet work, figure out the right colors for the dividers when using the iOS barrier color (initially the dialog work was done against the material barrier color).

**Comment by matthew-carroll** [comment] 2018-08-14 20:47
Related issue:
Cupertino dialog barrier should be #66000000 #18285

**Comment by frey1esm** [comment] 2018-12-05 20:57
The divider should be drawn on first rendering. Currently it's not added until the dialog display has reached the end of the show animation. This adds a little flicker. 

Native iOS dialogs resize (shrink) slightly during the show animation, so we're missing that piece.

In addition, once the divider is shown the white background of the dialog darkens a bit, adding another little flicker.

**Comment by kerberjg** [comment] 2019-02-13 02:37
Currently I'm unable to see the dividers in CupertinoAlertDialog at all, except for some instances. Seems like something's wrong with blending, looks like the dividers are drawn in additive mode.

The following screenshots are from the Flutter Gallery in Flutter v1.2.0, iOS 12.1.3

Usual white background, dividers not showing: 
![image](https://user-images.githubusercontent.com/16939117/52682579-472c2a80-2f40-11e9-897b-58e88456ee78.png)

Dividers seem to render in additive, partially blue background:
![image](https://user-images.githubusercontent.com/16939117/52682619-5e6b1800-2f40-11e9-80c6-893d2a35c215.png)

While attempting to implement dialogs on my own, I've encountered a similar issue:
![img_e98b3c201b47-1](https://user-images.githubusercontent.com/16939117/52682723-ae49df00-2f40-11e9-8fa3-a3f96a0c2250.jpeg)

**Comment by aleor** [comment] 2019-05-30 08:55
Having the same issue as @kerberjg, am I doing something wrong? Is there any workaround for the issue?

**Comment by seasonyuu** [comment] 2019-07-15 09:28
Same as @kerberjg here

**Comment by wezzle** [comment] 2019-08-16 14:59
Any update on a fix for this? I have the same problem as @kerberjg

Weird thing though, I did get them to display a few times but can't seem to reproduce this.

**Comment by jlnr** [comment] 2019-08-25 22:04
The Cupertino dialog buttons have no pressed/highlighted state either, which makes dialogs feel more like static images right now.

I think even an inaccurate hotfix like changing _kButtonDividerColor in cupertino/dialog.dart from `Color(0x40FFFFFF)` to something like `Color(0xFFBBBBBB)` would be better than the current state where the dividers only show up on dark backgrounds.

**Comment by kerberjg** [comment] 2019-08-27 02:31
Could be related to #39215 (?)

**Comment by jlnr** [comment] 2019-09-05 19:33
@kerberjg That PR has been merged, but I still see no dividers on the master channel.

**Closed** 2019-09-11 03:40 UTC
Labels: f: cupertino, framework
