### ISSUE TITLE
app cant run at least with this 2 plugins

### ISSUE THREAD

**Issue by rubenteste** [flutter/flutter#83248] opened 2021-05-24 09:56 UTC
hi,
so in my app i'm using flutter_launcher_icons and i'm trying to use a plugin to read pdf's.
and i'm tring to run this one: flutter_plugin_pdf_viewer.

But when I run the app, it give me error, because it can't run both plugins:
(1; So, because app depends on both flutter_plugin_pdf_viewer ^1.0.7 and flutter_launcher_icons ^0.9.0, version solving failed.)

what can i do? I wanted to use this version to have the latest plugin possible

**Comment by stuartmorgan** [comment] 2021-05-24 10:28
Please see flutter.dev/community for resources where you can get help with your own code/project.

Closing as this is not a bug in Flutter.

**Closed by stuartmorgan** 2021-05-24 10:28 UTC

**Comment by rubenteste** [comment] 2021-05-24 10:42
is not my code, if u just create one new project and you just add this 2 lines to pubspec.yaml file
flutter_plugin_pdf_viewer: ^1.0.7
flutter_launcher_icons: ^0.9.0

like this:

dependencies:
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_launcher_icons: ^0.9.0

  flutter:
    sdk: flutter



the app won't run and give you this error:
So, because app_test depends on both flutter_plugin_pdf_viewer ^1.0.7 and flutter_launcher_icons ^0.9.0, version solving failed.

I didn't even write a single line of code

**Comment by stuartmorgan** [comment] 2021-05-24 10:46
Dependency version conflicts between specific versions of two third-party plugins is not a bug in Flutter. Again, so the link above for resources that can help you with you own project.
