### ISSUE TITLE
Odd menu scrolling with dropdown

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#8531] opened 2017-03-02 17:01 UTC
Dropdowns try to center their chosen value when the popup opens up. If the dropdown is placed on top of the screen (or the list of values is long enough), that's not possible. So you get a scrolling animation while the popup settles.

This is jarring at best and annoying at worst since it delays user action (can't tap on any value until the animation ends [typically a second]).

It would be great if Flutter can precompute whether the centering is possible and if not prevent the scrolling.

**Comment by abarth** [comment] 2017-03-03 04:21
Duplicate of #8266

Sorry for dropping the ball on this issue.

**Closed by abarth** 2017-03-03 04:21 UTC
Labels: customer: leafy
