### ISSUE TITLE
flutter run error

### ISSUE THREAD

**Issue by max8888888** [flutter/flutter#16581] opened 2018-04-14 01:48 UTC
## Steps to Reproduce
I am a Android developer.  Develop IDE is android stodio 3.0.1.
I upgrade Flutter to 0.2.12 in yesterday.
 
But when i running my project, It made a mistake.

## Logs

Run my application with `flutter run` , and all logs is :
*********************************************
> D:\android\git_aliyun\xlcrm>flutter run
> Launching lib/main.dart on Redmi Note 3 in debug mode...
> Initializing gradle...
> Skipping compilation. Fingerprint match.
> 
> Oops; flutter has exited unexpectedly.
*********************************************
and it's over.......

But it created a flutter_01.log in my project root director. it's here :
***********************************************
> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter run
> 
> ## exception
> 
> FormatException: FormatException: Bad UTF-8 encoding 0xe4 (at offset 9)
> 
> ```
> #0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
> #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
> #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
> #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
> #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
> #5      _rootRunUnary (dart:async/zone.dart:1134)
> #6      _CustomZone.runUnary (dart:async/zone.dart:1031)
> #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
> #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
> #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
> #10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
> #11     _StreamController._add (dart:async/stream_controller.dart:639)
> #12     _StreamController.add (dart:async/stream_controller.dart:585)
> #13     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
> #14     _rootRunUnary (dart:async/zone.dart:1138)
> #15     _CustomZone.runUnary (dart:async/zone.dart:1031)
> #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
> #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
> #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
> #19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
> #20     _StreamController._add (dart:async/stream_controller.dart:639)
> #21     _StreamController.add (dart:async/stream_controller.dart:585)
> #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
> #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
> #24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
> #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> #26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
> #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
> ```
> 
> ## flutter doctor
> 
> ```
> [✓] Flutter (Channel master, v0.2.12-pre.30, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
>     • Flutter version 0.2.12-pre.30 at D:\flutterSdk\flutter
>     • Framework revision 1c3f6a851f (21 hours ago), 2018-04-12 21:16:39 -0700
>     • Engine revision 76cb311d9c
>     • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at E:\android\studio-sdk
>     • Android NDK at E:\android\studio-sdk\ndk-bundle
>     • Platform android-P, build-tools 27.0.3
>     • ANDROID_HOME = E:\android\studio-sdk
>     • Java binary at: E:\android\as\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.0)
>     • Android Studio at E:\android\as
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> [✓] Connected devices (1 available)
>     • Redmi Note 3 • JNY969CI99999999 • android-arm64 • Android 5.0.2 (API 21)
> 
> • No issues found!
> ```
*******************************************
Flutter plugin and Dart plugin was intalled:

[flutter plugin screenshot](https://imgchr.com/i/CVIUeJ)
[dart plugin screenshot](https://imgchr.com/i/CVItL4)

**How can i fixed it ? Thanks !**

**Comment by Hixie** [comment] 2018-06-19 23:58
Duplicate of https://github.com/flutter/flutter/issues/15646

**Closed by Hixie** 2018-06-19 23:58 UTC
