### ISSUE TITLE
CustomMultiChildLayout docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6863] opened 2016-11-15 17:26 UTC
Customer feedback:
> CustomMultiChildLayout is still inpenetrable. Perhaps Dartdoc should hint at the use of LayoutId.

**Comment by abarth** [comment] 2016-11-20 04:52
More confusion about this class:

> I'm puzzled by CustomMultiChildLayout.
> I supply it a MultiChildLayoutDelegate, which has a method performLayout(Size size). I override that, but how do I actually do the layout? I can give my implementation I suppose the list of children, but actually setting width/height/x/y, I don't see how for my chldren StatelessWidgets??

**Comment by sethladd** [comment] 2016-11-21 20:49
I think this is a dupe of https://github.com/flutter/flutter/issues/5695

**Closed** 2016-11-21 20:49 UTC
Labels: easy fix, ⚠ clear documentation
