### ISSUE TITLE
Select dialog overflow issue

### ISSUE THREAD

**Issue by JhonPreston** [flutter/flutter#47214] opened 2019-12-17 13:15 UTC
If you localize your app to a language with long words for the phrases COPY, PASTE, SELECT ALL and others from the clipboard controls, the text will overflow when selecting anything that causes the controls to appear.

That's how the controls appear on Android in ua_UA/ru_RU:
DEVISES: 
Samsung Galaxy S10+
![image](https://user-images.githubusercontent.com/7803418/71011223-bab93e00-20f5-11ea-8161-5a7534102643.png)

MEIZU M6T
![image](https://user-images.githubusercontent.com/7803418/71011255-ca388700-20f5-11ea-9576-0aef07aa7621.png)

**Comment by justinmc** [comment] 2019-12-17 16:58
You're right, this is a major problem that we need to fix.

I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/35826 so we can focus the discussion over there.  Please give that issue a 👍!

**Closed by justinmc** 2019-12-17 16:58 UTC
Labels: f: material design, framework
