### ISSUE TITLE
Flutter Gallery on the Play Store is severely outdated

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#25730] opened 2018-12-24 12:55 UTC
[io.flutter.demo.gallery](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en_US) hasn't been updated for nearly 4 Months, which casts a bad image on flutter (the top comments are ridiculing flutter), and are [misleading new users](https://www.reddit.com/r/FlutterDev/comments/a8zoil/noticeable_differences_in_native_widgets_and/).

The description still says that "flutter is beta technology" too

**Comment by zoechi** [comment] 2018-12-27 14:10
Duplicate of #15533

**Closed by zoechi** 2018-12-27 14:10 UTC
