### ISSUE TITLE
PageRouteBuilder with Vertical SlideTransition Resets System NavBar Color (Unwanted)

### ISSUE THREAD

**Issue by sabetAI** [flutter/flutter#78038] opened 2021-03-12 16:29 UTC
## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    systemNavigationBarIconBrightness: Brightness.dark,
    systemNavigationBarColor: Colors.white,
  ));
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: MyWidget(),
        bottomNavigationBar: BottomNavigationBar(
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Item 1',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.settings),
              label: 'Item 2',
            ),
          ],
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Builder(
          builder: (context) => ElevatedButton(
            child: Text('Show modal bottom sheet'),
            onPressed: () => _pageTransition(context),
          ),
        ),
      ),
    );
  }

  _pageTransition(BuildContext context) {
    Navigator.of(context).push(PageRouteBuilder(
        pageBuilder: (context, animation, secondaryAnimation) => Scaffold(
              appBar: AppBar(
                title: Text('Test'),
              ),
            ),
        transitionsBuilder: (context, animation, secondaryAnimation, child) =>
            SlideTransition(
              position: Tween(begin: Offset(0.0, 1.0), end: Offset(0.0, 0.0))
                  .animate(animation),
              child: child,
            )));
  }
}
```
Click on button and press back button to previous page.

**Expected results:** 
<img src="https://user-images.githubusercontent.com/28828395/110968550-ac23fb80-8325-11eb-8749-bceb59384b75.png" width="25%" height="25%">

**Actual results:** 
<img src="https://user-images.githubusercontent.com/28828395/110884530-3b43fb80-82b3-11eb-9ab3-5897d2cf1600.png" width="25%" height="25%">

For some mysterious reason, the problem disappears if I comment out the `AppBar` in the `Scaffold` of the new page. What could be the cause?

**Comment by nt4f04uNd** [comment] 2021-03-13 14:09
i have had a similar problem https://github.com/flutter/flutter/issues/42795, the cause is automatic ui adjustment option

**Comment by sabetAI** [comment] 2021-03-13 17:02
Ah thanks @nt4f04uNd. As you suggest,
```
final WidgetsBinding binding = WidgetsFlutterBinding.ensureInitialized();
binding.renderView.automaticSystemUiAdjustment = false;
```
from https://github.com/flutter/flutter/issues/40590#issuecomment-601093769 also resolves the issue.

**Comment by darshankawar** [comment] 2021-03-15 06:55
@sabetAI 
Based on your comment above, I am going ahead and closing this as solved. If you disagree, write in commets and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-15 06:55 UTC
Labels: in triage
