### ISSUE TITLE
Set up a ProMotion Display supported iOS device in device lab

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#92444] opened 2021-10-25 20:56 UTC
iPad pro promotion display and iPhone 13 pro support variable refresh rate. To integration test this feature flutter, we would need a device that supports this feature to be set up in the device lab and run perf testing. (iPhone 13 pro or iPad promotion display)

For details of supporting variable refresh rate on iOS, see flutter.dev/go/variable-refresh-rate

**Comment by godofredoc** [comment] 2021-11-11 23:31
I'm wondering if instead of adding it to the devicelab we can order a few iPad and keep in the shared device library. What do you think?

**Comment by cyanglaz** [comment] 2021-11-12 02:56
> I'm wondering if instead of adding it to the devicelab we can order a few iPad and keep in the shared device library. What do you think?

That sounds good. @iskakaushik and I have already ordered 2 iPhone 13 pros for this. We still need set at least one device in the device lab, right? Without devicelab, we won't be able to automate the tests.

**Comment by iskakaushik** [comment] 2021-11-12 15:44
Given that we do not have any iOS devices in the device lab that support variable refresh rate, we would definitely want at least one such device in there, so we can have automated tests for when we enable this feature.

**Comment by jmagman** [comment] 2021-11-23 19:04
Is this a duplicate of https://github.com/flutter/flutter/issues/31450?

**Comment by godofredoc** [comment] 2021-11-23 19:07
Is this something that we can do on firebaselab? maintaining adhoc devices in the devicelab does not scale well and increases the current maintenance cost.

**Comment by cyanglaz** [comment] 2021-11-23 21:30
> Is this a duplicate of #31450?

I think so, clsoe this one in favor of #31450 since the other one also has discussion related to iPad Pro

**Comment by cyanglaz** [comment] 2021-11-29 18:18
The #31450 is more about querying the refresh rate. This issue is about setting up the test device.

**Comment by Hixie** [comment] 2022-02-16 00:14
Any news on this? It is blocking one of our oldest PRs, https://github.com/flutter/flutter/pull/94509.

**Comment by godofredoc** [comment] 2022-02-16 00:20
I would recommend to test locally or alternatively try to use firebase lab. Adding one off devices to the devicelab increments the maintenance cost exponentially.

**Closed** 2022-02-23 00:08 UTC
Labels: passed first triage, team: infra, passed secondary triage
