### ISSUE TITLE
Unable to run flutter app on Android emulator on MacOS

### ISSUE THREAD

**Issue by el3ankaboot** [flutter/flutter#51866] opened 2020-03-03 17:19 UTC
Hi,
I am new to flutter , I setted up android studio and wrote a very simple application.
When I try running it on the iOS simulator it runs perfectly with no problem.
However when I try to run it on Android emulator it fails and the following is shown :

```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
Checking the license for package Android SDK Build-Tools 28.0.3 in /Users/el3ankaboot/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 28 in /Users/el3ankaboot/Library/Android/sdk/licenses
Warning: License for package Android SDK Platform 28 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: /Users/el3ankaboot/Library/Android/sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

And when I run from the terminal : 

```
flutter doctor
```

I get the following 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.4 18E226,
    locale en-EG)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

I searched in this issue and tried a lot of things like : 

```
flutter doctor --android-licenses
```
But I get : 
```
A newer version of the Android SDK is required. To update, run:
/Users/el3ankaboot/Library/Android/sdk/tools/bin/sdkmanager --update
```
And when I run what is said I get the following : 
```
Warning: Could not create settings
java.lang.IllegalArgumentException
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Usage:
  sdkmanager [--uninstall] [<common args>] [--package_file=<file>] [<packages>...]
  sdkmanager --update [<common args>]
  sdkmanager --list [<common args>]
  sdkmanager --licenses [<common args>]
  sdkmanager --version

With --install (optional), installs or updates packages.
    By default, the listed packages are installed or (if already installed)
    updated to the latest version.
With --uninstall, uninstall the listed packages.

    <package> is a sdk-style path (e.g. "build-tools;23.0.0" or
             "platforms;android-23").
    <package-file> is a text file where each line is a sdk-style path
                   of a package to install or uninstall.
    Multiple --package_file arguments may be specified in combination
    with explicit paths.

With --update, all installed packages are updated to the latest version.

With --list, all installed and available packages are printed out.

With --licenses, show and offer the option to accept licenses for all
     available packages that have not already been accepted.

With --version, prints the current version of sdkmanager.

Common Arguments:
    --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK
                              containing this tool

    --channel=<channelId>: Include packages in channels up to <channelId>.
                           Common channels are:
                           0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).

    --include_obsolete: With --list, show obsolete packages in the
                        package listing. With --update, update obsolete
                        packages as well as non-obsolete.

    --no_https: Force all connections to use http rather than https.

    --proxy=<http | socks>: Connect via a proxy of the given type.

    --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.

    --proxy_port=<port #>: Proxy port to connect to.

    --verbose: Enable verbose output.

* If the env var REPO_OS_OVERRIDE is set to "windows",
  "macosx", or "linux", packages will be downloaded for that OS.
```

I also tried : 
```
sdkmanager --update
```
But got : 
```
bash: sdkmanager: command not found
```

I am now stuck because I have no prior experience in android (I am an iOS developer).
Thus I need help,
Thank in advance,
Best Regards.

**Comment by LucSouza** [comment] 2020-03-04 00:05
hey bro, same here. I break my head 2 days trying to solve this, im getting exactly same error on Linux ubuntu. Now i found a walk-through that seems to work. 

This will work without android studio, https://dev.to/jay_js/setting-up-flutter-without-android-studio-olo 

i think you could use the steps for IOS Too.

**Comment by VladyslavBondarenko** [comment] 2020-03-04 12:08
Duplicate of https://github.com/flutter/flutter/issues/51712

https://github.com/flutter/flutter/issues/51712#issuecomment-593295633 to see the 'Android SDK Tools' uncheck 'Hide obsolete Packages'

**Closed by VladyslavBondarenko** 2020-03-04 12:08 UTC

**Comment by 9r1nc3w1ll** [comment] 2020-03-26 17:42
You can follow the steps in this article https://dev.to/jay_js/setting-up-flutter-without-android-studio-olo

or simply run the command below. It fixed it for me
```sdkmanager --sdk_root=${ANDROID_HOME} tools```

**Comment by 9r1nc3w1ll** [comment] 2020-03-26 18:09
Also remove other versions of JDK and JRE leaving only version 1.8

**Comment by mrostamii** [comment] 2020-04-22 06:57
A complete procedure:

https://stackoverflow.com/a/61150826/6602159
