### ISSUE TITLE
Flutter apps crash with custom keyboard apps in iOS16

### ISSUE THREAD

**Issue by naodroid** [flutter/flutter#111550] opened 2022-09-14 12:04 UTC
## Steps to Reproduce

1. Tap a textfield
2. Change the keyboard app to Gboard
3. Input some emojis
4. Input some characters
5. Tap one of the predictive texts

**Expected results:**
It should not crash

**Actual results:**
It crashes 100%

**Details**
This happens with other keyboard apps, such as Simeji(Japanese Input) and flick.

**Related issues**
The crash log is almost the same as #111494.

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 13.0 22A5331f darwin-arm, locale
    en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

<details>
  <summary>records</summary>

https://user-images.githubusercontent.com/4728599/190141967-827912d9-80d7-46c0-8e51-2e3ff10353c0.MOV

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Korean Emoji Crash'),
        ),
        body: const Center(child: TextField()),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```

Incident Identifier: 32EE8B03-239F-4D52-9141-8372D0534269
CrashReporter Key:   d8a4ffde820fd66d2d98c7c3dfc5bea4d9a039ba
Hardware Model:      iPhone12,8
Process:             Runner [8166]
Path:                /private/var/containers/Bundle/Application/9F2B6075-D93D-4569-A733-9C5458FE80DF/Runner.app/Runner
Identifier:          com.example.flutter.text
Version:             1.0.0 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.example.flutter.text [1903]

Date/Time:           2022-09-14 19:58:00.7823 +0900
Launch Time:         2022-09-14 19:53:08.8765 +0900
OS Version:          iPhone OS 16.0 (20A362)
Release Type:        User
Baseband Version:    4.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Application Specific Information:
abort() called


Last Exception Backtrace:
0   CoreFoundation                	       0x1c14e6248 __exceptionPreprocess + 164
1   libobjc.A.dylib               	       0x1ba8b7a68 objc_exception_throw + 60
2   Foundation                    	       0x1bbe7681c _userInfoForFileAndLine + 0
3   Flutter                       	       0x107187804 -[FlutterJSONMessageCodec encode:] + 356
4   Flutter                       	       0x107187b68 -[FlutterJSONMethodCodec encodeMethodCall:] + 200
5   Flutter                       	       0x1071869c8 -[FlutterMethodChannel invokeMethod:arguments:] + 56
6   Flutter                       	       0x106c2d18c -[FlutterEngine flutterTextInputView:updateEditingClient:withState:] + 124
7   Flutter                       	       0x106c42e38 -[FlutterTextInputView updateEditingState] + 608
8   UIKitCore                     	       0x1c42f2198 -[UITextInteractionSelectableInputDelegate insertText:] + 36
9   UIKitCore                     	       0x1c3fc8398 -[UIKBInputDelegateManager _deleteBackwardAndNotify:reinsertText:] + 308
10  UIKitCore                     	       0x1c42035f8 -[UIKeyboardImpl deleteBackwardAndNotify:reinsertText:] + 208
11  UIKitCore                     	       0x1c41fc8f4 -[UIKeyboardImpl performKeyboardOutput:checkingDelegate:forwardToRemoteInputSource:] + 1212
12  UIKitCore                     	       0x1c41fc10c -[UIKeyboardImpl performKeyboardOutput:forwardToRemoteInputSource:] + 32
13  UIKitCore                     	       0x1c41f1260 __77-[UIKeyboardImpl _processInputViewControllerKeyboardOutput:executionContext:]_block_invoke + 480
14  UIKitCore                     	       0x1c421b760 -[UIKeyboardImpl _performKeyboardOutput:respectingForwardingDelegate:] + 204
15  UIKitCore                     	       0x1c41f1054 -[UIKeyboardImpl _processInputViewControllerKeyboardOutput:executionContext:] + 168
16  UIKitCore                     	       0x1c41e656c -[UIKeyboardImpl performOperations:withTextInputSource:] + 56
17  UIKitCore                     	       0x1c421f5cc __67-[UIKeyboardImpl(UIKitInternal) _performInputViewControllerOutput:]_block_invoke + 172
18  UIKitCore                     	       0x1c3a3d9b4 -[UIKeyboardTaskEntry execute:] + 208
19  UIKitCore                     	       0x1c3a3d898 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 304
20  Foundation                    	       0x1bb96b000 __NSThreadPerformPerform + 264
21  CoreFoundation                	       0x1c15b222c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
22  CoreFoundation                	       0x1c15be614 __CFRunLoopDoSource0 + 176
23  CoreFoundation                	       0x1c154251c __CFRunLoopDoSources0 + 244
24  CoreFoundation                	       0x1c1557eb8 __CFRunLoopRun + 836
25  CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
26  GraphicsServices              	       0x1fa37d368 GSEventRunModal + 164
27  UIKitCore                     	       0x1c3a0cd88 -[UIApplication _run] + 888
28  UIKitCore                     	       0x1c3a0c9ec UIApplicationMain + 340
29  Runner                        	       0x104289d00 main + 64
30  dyld                          	       0x1df881948 start + 2504

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage


Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1fdbce200 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x20de0b1ac pthread_kill + 268
2   libsystem_c.dylib             	       0x1c89c5ca0 abort + 180
3   libc++abi.dylib               	       0x20dd4db8c abort_message + 132
4   libc++abi.dylib               	       0x20dd3da80 demangling_terminate_handler() + 336
5   libobjc.A.dylib               	       0x1ba8bdeec _objc_terminate() + 144
6   libc++abi.dylib               	       0x20dd4cf28 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x20dd4fecc __cxa_rethrow + 148
8   libobjc.A.dylib               	       0x1ba8b9854 objc_exception_rethrow + 44
9   CoreFoundation                	       0x1c155d2a8 CFRunLoopRunSpecific + 808
10  GraphicsServices              	       0x1fa37d368 GSEventRunModal + 164
11  UIKitCore                     	       0x1c3a0cd88 -[UIApplication _run] + 888
12  UIKitCore                     	       0x1c3a0c9ec UIApplicationMain + 340
13  Runner                        	       0x104289d00 main + 64
14  dyld                          	       0x1df881948 start + 2504

Thread 1 name:  com.apple.uikit.eventfetch-thread
Thread 1:
0   libsystem_kernel.dylib        	       0x1fdbc7b48 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1fdbda008 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1fdbda248 mach_msg_overwrite + 388
3   libsystem_kernel.dylib        	       0x1fdbc808c mach_msg + 24
4   CoreFoundation                	       0x1c1556e00 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1c1558044 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
7   Foundation                    	       0x1bb971818 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x1bb971700 -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9   UIKitCore                     	       0x1c3b4188c -[UIEventFetcher threadMain] + 436
10  Foundation                    	       0x1bb98ace8 __NSThread__start__ + 716
11  libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
12  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 2 name:  io.flutter.1.ui
Thread 2:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c098 _pthread_cond_wait + 1276
2   Flutter                       	       0x1073b567c dart::SafepointHandler::SafepointThreads(dart::Thread*, dart::SafepointLevel) + 796
3   Flutter                       	       0x107336e60 dart::DRT_PatchStaticCall(dart::NativeArguments) + 644
4   ???                           	       0x10920295c ???
5   ???                           	       0x109202d50 ???
6   ???                           	       0x12183a5b4 ???
7   ???                           	       0x12182b834 ???
8   ???                           	       0x11758922c ???
9   ???                           	       0x1175878cc ???
10  ???                           	       0x121822254 ???
11  ???                           	       0x117340740 ???
12  ???                           	       0x117343be0 ???
13  ???                           	       0x12182216c ???
14  ???                           	       0x117340740 ???
15  ???                           	       0x117343be0 ???
16  ???                           	       0x117587628 ???
17  ???                           	       0x121822254 ???
18  ???                           	       0x117340740 ???
19  ???                           	       0x117343be0 ???
20  ???                           	       0x12182214c ???
21  ???                           	       0x117340740 ???
22  ???                           	       0x117343be0 ???
23  ???                           	       0x12182216c ???
24  ???                           	       0x117340740 ???
25  ???                           	       0x117343be0 ???
26  ???                           	       0x12182214c ???
27  ???                           	       0x117340740 ???
28  ???                           	       0x117343be0 ???
29  ???                           	       0x12182214c ???
30  ???                           	       0x117340740 ???
31  ???                           	       0x117343be0 ???
32  ???                           	       0x12182214c ???
33  ???                           	       0x117340740 ???
34  ???                           	       0x117343be0 ???
35  ???                           	       0x12182214c ???
36  ???                           	       0x117340740 ???
37  ???                           	       0x117583d48 ???
38  ???                           	       0x117581c58 ???
39  ???                           	       0x11737a2c4 ???
40  ???                           	       0x1218221e8 ???
41  ???                           	       0x117340740 ???
42  ???                           	       0x117343be0 ???
43  ???                           	       0x12182214c ???
44  ???                           	       0x117340740 ???
45  ???                           	       0x117343be0 ???
46  ???                           	       0x12182216c ???
47  ???                           	       0x117340740 ???
48  ???                           	       0x117343be0 ???
49  ???                           	       0x12182214c ???
50  ???                           	       0x117340740 ???
51  ???                           	       0x117343be0 ???
52  ???                           	       0x12182214c ???
53  ???                           	       0x117340740 ???
54  ???                           	       0x117343be0 ???
55  ???                           	       0x1218221cc ???
56  ???                           	       0x117340740 ???
57  ???                           	       0x117359a04 ???
58  ???                           	       0x12182223c ???
59  ???                           	       0x117340740 ???
60  ???                           	       0x117358d10 ???
61  ???                           	       0x1173567ec ???
62  ???                           	       0x117354910 ???
63  ???                           	       0x117353acc ???
64  ???                           	       0x11733e768 ???
65  ???                           	       0x11733d368 ???
66  ???                           	       0x11733c604 ???
67  ???                           	       0x117331344 ???
68  ???                           	       0x117330c38 ???
69  ???                           	       0x117330b38 ???
70  ???                           	       0x121811a80 ???
71  ???                           	       0x121826804 ???
72  ???                           	       0x11792e73c ???
73  ???                           	       0x11792e490 ???
74  ???                           	       0x111496a3c ???
75  ???                           	       0x1114b51e0 ???
76  ???                           	       0x1114b5090 ???
77  ???                           	       0x1114b4fbc ???
78  ???                           	       0x109202ed8 ???
79  Flutter                       	       0x1071e5148 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) + 604
80  Flutter                       	       0x107577bb4 Dart_InvokeClosure + 1496
81  Flutter                       	       0x106fedb7c flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint, unsigned long long) + 376
82  Flutter                       	       0x106fde8b8 std::__1::__function::__func<flutter::Animator::AwaitVSync()::$_3, std::__1::allocator<flutter::Animator::AwaitVSync()::$_3>, void (std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&) + 1536
83  Flutter                       	       0x107009e84 std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()() + 1208
84  Flutter                       	       0x106f0bd8c fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 1636
85  Flutter                       	       0x106f0f878 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
86  CoreFoundation                	       0x1c15aa66c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
87  CoreFoundation                	       0x1c1566ce8 __CFRunLoopDoTimer + 940
88  CoreFoundation                	       0x1c150a958 __CFRunLoopDoTimers + 288
89  CoreFoundation                	       0x1c15582dc __CFRunLoopRun + 1896
90  CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
91  Flutter                       	       0x106f0f748 fml::MessageLoopDarwin::Run() + 88
92  Flutter                       	       0x106f0e7c8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) + 208
93  libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
94  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 3 name:  io.flutter.1.raster
Thread 3:
0   libsystem_kernel.dylib        	       0x1fdbc7b48 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1fdbda008 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1fdbda248 mach_msg_overwrite + 388
3   libsystem_kernel.dylib        	       0x1fdbc808c mach_msg + 24
4   CoreFoundation                	       0x1c1556e00 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1c1558044 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
7   Flutter                       	       0x106f0f748 fml::MessageLoopDarwin::Run() + 88
8   Flutter                       	       0x106f0e7c8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) + 208
9   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
10  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 4 name:  io.flutter.1.io
Thread 4:
0   libsystem_kernel.dylib        	       0x1fdbc7b48 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1fdbda008 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1fdbda248 mach_msg_overwrite + 388
3   libsystem_kernel.dylib        	       0x1fdbc808c mach_msg + 24
4   CoreFoundation                	       0x1c1556e00 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1c1558044 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
7   Flutter                       	       0x106f0f748 fml::MessageLoopDarwin::Run() + 88
8   Flutter                       	       0x106f0e7c8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) + 208
9   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
10  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 5 name:  io.flutter.1.profiler
Thread 5:
0   libsystem_kernel.dylib        	       0x1fdbc7b48 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1fdbda008 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1fdbda248 mach_msg_overwrite + 388
3   libsystem_kernel.dylib        	       0x1fdbc808c mach_msg + 24
4   CoreFoundation                	       0x1c1556e00 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1c1558044 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1c155d1e4 CFRunLoopRunSpecific + 612
7   Flutter                       	       0x106f0f748 fml::MessageLoopDarwin::Run() + 88
8   Flutter                       	       0x106f0e7c8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) + 208
9   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
10  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 6 name:  io.worker.1
Thread 6:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 7 name:  io.worker.2
Thread 7:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 8 name:  io.worker.3
Thread 8:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 9 name:  io.worker.4
Thread 9:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 10 name:  io.worker.5
Thread 10:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 11 name:  io.worker.6
Thread 11:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c06c _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x1cf886acc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Flutter                       	       0x106f0945c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0> >(void*) + 304
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 12 name:  dart:io EventHandler
Thread 12:
0   libsystem_kernel.dylib        	       0x1fdbc9480 kevent + 8
1   Flutter                       	       0x1070f24d4 dart::bin::EventHandlerImplementation::EventHandlerEntry(unsigned long) + 448
2   Flutter                       	       0x107123cb0 dart::bin::ThreadStart(void*) + 44
3   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
4   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 13 name:  Dart Profiler ThreadInterrupter
Thread 13:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c098 _pthread_cond_wait + 1276
2   Flutter                       	       0x1072d7ffc dart::Monitor::WaitMicros(long long) + 128
3   Flutter                       	       0x10737ec48 dart::ThreadInterrupter::ThreadMain(unsigned long) + 432
4   Flutter                       	       0x1072d7984 dart::ThreadStart(void*) + 288
5   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
6   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 14 name:  Dart Profiler SampleBlockProcessor
Thread 14:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c098 _pthread_cond_wait + 1276
2   Flutter                       	       0x1072dcddc dart::SampleBlockProcessor::ThreadMain(unsigned long) + 264
3   Flutter                       	       0x1072d7984 dart::ThreadStart(void*) + 288
4   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 15:
0   libsystem_pthread.dylib       	       0x20de04b90 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x20de04b90 start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	       0x20de04b90 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x20de04b90 start_wqthread + 0

Thread 19 name:  DartWorker
Thread 19:
0   Flutter                       	       0x1073f7f7c dart::CallTargets::CreateAndExpand(dart::Zone*, dart::ICData const&) + 1852
1   Flutter                       	       0x1073f7f54 dart::CallTargets::CreateAndExpand(dart::Zone*, dart::ICData const&) + 1812
2   Flutter                       	       0x10740b64c dart::InstanceCallInstr::Targets() + 184
3   Flutter                       	       0x10752228c dart::JitCallSpecializer::VisitInstanceCall(dart::InstanceCallInstr*) + 64
4   Flutter                       	       0x1074061c0 dart::FlowGraphVisitor::VisitBlocks() + 136
5   Flutter                       	       0x1074a51c8 dart::CompilerPass_ApplyICData::DoBody(dart::CompilerPassState*) const + 24
6   Flutter                       	       0x1074a5708 dart::CompilerPass::Run(dart::CompilerPassState*) const + 452
7   Flutter                       	       0x10738f988 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) + 3016
8   Flutter                       	       0x107393d28 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) + 1368
9   Flutter                       	       0x1073947cc dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long) + 712
10  Flutter                       	       0x1073957f8 dart::BackgroundCompilerTask::Run() + 340
11  Flutter                       	       0x10737fca8 dart::ThreadPool::Worker::Main(unsigned long) + 396
12  Flutter                       	       0x1072d7984 dart::ThreadStart(void*) + 288
13  libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
14  libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8

Thread 20 name:  DartWorker
Thread 20:
0   libsystem_kernel.dylib        	       0x1fdbc841c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x20de0c098 _pthread_cond_wait + 1276
2   Flutter                       	       0x1072d7ffc dart::Monitor::WaitMicros(long long) + 128
3   Flutter                       	       0x10737fdb8 dart::ThreadPool::Worker::Main(unsigned long) + 668
4   Flutter                       	       0x1072d7984 dart::ThreadStart(void*) + 288
5   libsystem_pthread.dylib       	       0x20de056cc _pthread_start + 148
6   libsystem_pthread.dylib       	       0x20de04ba4 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000020dd510f5   x5: 0x000000016bb7aff0   x6: 0x000000000000006e   x7: 0x0000000000000001
    x8: 0x9867afc166aee040   x9: 0x9867afc371c501c0  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x00000002176be180  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000002176be260  x22: 0x0000000218a6e3a0  x23: 0x00000002807401b0
   x24: 0x0000000000000001  x25: 0x0000000000000001  x26: 0x0000000000000001  x27: 0x0000000000000000
   x28: 0x00000001e20f79e0   fp: 0x000000016bb7af60   lr: 0x000000020de0b1ac
    sp: 0x000000016bb7af40   pc: 0x00000001fdbce200 cpsr: 0x40000000
   far: 0x0000000214cf3170  esr: 0x56000080  Address size fault

Binary Images:
       0x1fdbc7000 -        0x1fdbfdffb libsystem_kernel.dylib arm64e  <a5d3b72578c33e19a765cceb22355093> /usr/lib/system/libsystem_kernel.dylib
       0x20de04000 -        0x20de0ffff libsystem_pthread.dylib arm64e  <b89b9a5b55d93e84b6d3c3da93c1cd39> /usr/lib/system/libsystem_pthread.dylib
       0x1c89a5000 -        0x1c8a24fff libsystem_c.dylib arm64e  <82c0f938e2773165a61470151c651798> /usr/lib/system/libsystem_c.dylib
       0x20dd3c000 -        0x20dd53ffb libc++abi.dylib arm64e  <e0dbf9459cc5305db096abc1cda9c8ca> /usr/lib/libc++abi.dylib
       0x1ba8a0000 -        0x1ba8e3c3f libobjc.A.dylib arm64e  <b3a78098c0fb3dcdb1ac0712762510db> /usr/lib/libobjc.A.dylib
       0x1c14dc000 -        0x1c18c0fff CoreFoundation arm64e  <42c5c91704473995b50fde4d132c2435> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1fa37c000 -        0x1fa384fff GraphicsServices arm64e  <03732ba5113235b4b09d8dd49807d246> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x1c366a000 -        0x1c4e30fff UIKitCore arm64e  <7b942fa4cb7633759972f58c14492fb4> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x104284000 -        0x10428bfff Runner arm64  <efd8f0efb007333bbcb9b1c52fcf86b7> /private/var/containers/Bundle/Application/9F2B6075-D93D-4569-A733-9C5458FE80DF/Runner.app/Runner
       0x1df86c000 -        0x1df8eee4f dyld arm64e  <341bbf646034357e8aa6e1e4b988e03c> /usr/lib/dyld
       0x1bb930000 -        0x1bc27afff Foundation arm64e  <aa92cd58561a341492f4b4120298b39a> /System/Library/Frameworks/Foundation.framework/Foundation
       0x106c18000 -        0x1087cffff Flutter arm64  <58fc1b5cd5a238bc894e79af0b07b80b> /private/var/containers/Bundle/Application/9F2B6075-D93D-4569-A733-9C5458FE80DF/Runner.app/Frameworks/Flutter.framework/Flutter
               0x0 - 0xffffffffffffffff ??? unknown-arch  <00000000000000000000000000000000> ???
       0x1cf87a000 -        0x1cf8e0ff3 libc++.1.dylib arm64e  <36bf5e0c2d4036faa0752476613f6d3f> /usr/lib/libc++.1.dylib

EOF
```

</details>

**Comment by danagbemava-nc** [comment] 2022-09-14 12:41
Hi @naodroid, thanks for filing this issue. After reviewing your crash logs and my own crash logs after using gboard, I can confirm that the two issues are the same. 
I will therefore close this as a duplicate of https://github.com/flutter/flutter/issues/111494 and update the title. 

Thank you

**Closed by danagbemava-nc** 2022-09-14 12:41 UTC
Labels: in triage
