### ISSUE TITLE
ResizeToAvoidBottomInset stopped working after upgrading to 3.10.0

### ISSUE THREAD

**Issue by dezsocsete** [flutter/flutter#126585] opened 2023-05-11 19:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

# Steps:
1. Create a scaffold with resizeToAvoidBottomInset set to true.
2. Put a Textfield into a column.
3. Tap on the textfield
4. Keyboard should pop up

# History:
I have upgraded to flutter 3.10.0. After that the resizeToAvoidBottomInset stopped working, despite it was working with flutter 3.7.11 just yesterday.

### Expected results

The keyboard should push the textfield so that it can be seen.

### Actual results

The keyboard hides the textfield.

### Code sample

<details><summary>Code sample</summary>

This code is a simplified version of what I am using, but I have tested this one too, and the same behaviour occures.

```dart
return const Scaffold(
      resizeToAvoidBottomInset: true,
      body: Column(
        children: [
          SizedBox(height: 600),
          TextField(),
        ],
      ),
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Using 3.7.11
![image](https://github.com/flutter/flutter/assets/97448158/c30f8eb1-a231-4796-832e-3a5f40e653a8)

Using 3.10.0
![image](https://github.com/flutter/flutter/assets/97448158/b9b0e93b-7be1-40aa-8925-f3501b621c61)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale hu-HU)
    • Flutter version 3.10.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\dezso\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\dezso\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 113.0.1774.35

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by a1573595** [comment] 2023-05-12 02:01
Same issue

**Comment by mminhlequang** [comment] 2023-05-12 04:43
up

**Comment by emotionalboySY** [comment] 2023-05-12 04:47
Same Issue.

Addition: It seems that whole view inset is not adjusted whenever keyboard appearence

**Comment by chauquocan** [comment] 2023-05-12 06:33
Same issue

**Comment by wownsdl13** [comment] 2023-05-12 07:10
same issue here

**Comment by darshankawar** [comment] 2023-05-12 08:38
@dezsocsete I tried running the code sample on latest stable version which although gave me the reported behavior but also showed below log in the console:

<details>
<summary> console error log </summary>

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 260 pixels on the bottom.

The relevant error-causing widget was: 
  Column Column:file:///Users/dhs/Documents/NCFlutter/flutter_app/lib/main.dart:17:13
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#1804f relayoutBoundary=up1 OVERFLOWING
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=388.3)
...  size: Size(411.4, 388.3)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================

```

</details>

Indicating a `RenderFlex overflow`. So in order to fix it, I wrapped `SizedBox` with `Expanded` as below:

```
body: Column(
        children: [
          Expanded(
            child: SizedBox(height: 600),
          ),
          TextField(),
        ],
      ),

```

Which fixed the overflow exception and also shows the textfield properly above the keyboard:


https://github.com/flutter/flutter/assets/67046386/d1ac69c6-5f79-4fa5-b556-155ec011683f

Please check the same and see if it helps in your case.

Also, everyone else facing this issue, please do not comment `same issue`, but upvote original description.

**Comment by marcingatnicki** [comment] 2023-05-12 12:04
Upgrading ScreenUtil to latest (5.8.1) and setting useInheritedMediaQuery = true fixed the issue in my app.

**Comment by darshankawar** [comment] 2023-05-12 12:25
Closing based on above comments as it seems to be related to community package and not the framework.

**Closed by darshankawar** 2023-05-12 12:25 UTC
Labels: in triage

**Comment by vito-go** [comment] 2023-05-13 16:11
I have not use screenutil package in my program. But the problem that the keyboard hides the textfield yet exists,after my upgrding to flutter 3.10 from 3.7.12.

**Comment by minhx3** [comment] 2023-05-19 04:25
> Thank you for your answer @darshankawar, I started digging what could the problem be, and I figured it out. In my case I am using the package flutter_screenutil, that now have a useInheritedMediaQuery field. I set it to true, and it is now working.
> 
> ```
> ScreenUtilInit(
>       useInheritedMediaQuery: true,
>       designSize: const Size(376, 812),
>       builder: (context, child) {
>         return const Scaffold(
>           resizeToAvoidBottomInset: true,
>           body: Column(
>             children: [
>               Spacer(),
>               TextField(),
>             ],
>           ),
>         );
>       },
>     );
> ```

Thank you very much, you saved me 3 days

**Comment by Sadhorsephile** [comment] 2023-05-27 22:25
> I have not use screenutil package in my program. But the problem that the keyboard hides the textfield yet exists,after my upgrding to flutter 3.10 from 3.7.12.

Same

**Comment by Sadhorsephile** [comment] 2023-05-30 14:33
In my case issue was caused by using of `TestWidgetsFlutterBinding.ensureInitialized().inTest`.
