### ISSUE TITLE
RawKeyboard or RawKeyboardListener doesn't work 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#26717] opened 2019-01-17 19:51 UTC
I'm trying to use RawKeyboard or RawKeyboardListener to listen keyboard delete key, in order to put the focus on the previous field if you hit the key when the filed is empty. 

I can't figure out how I can do this... TextField only have onChange and it's not called when it's already empty, and RawKeyboard or RawKeyboardListener are never called on iOS simulator or real device. 

Maybe I miss understood the usage of RawKeyboard but in that case what can I use to listen device software keyboard keys ? 

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale fr-FR)
    • Flutter version 1.0.0 at /Users/jaumard/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK at /Users/jaumard/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.3
    • Dart plugin version 183.4733

```

**Comment by zoechi** [comment] 2019-01-18 07:35
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-01-18 07:36
Duplicate of #22905

**Comment by zoechi** [comment] 2019-01-18 07:37
https://github.com/flutter/flutter/issues/14809#issuecomment-448424925 might help (didn't have a closer look)

**Closed by zoechi** 2019-01-18 07:36 UTC

**Comment by nsmith1024** [comment] 2019-08-01 00:17
is this working now? I have the same problem trying to detect power button press.

**Comment by therenca** [comment] 2020-07-13 03:57
RawKeyboardListener not working...

**Comment by bionara** [comment] 2020-08-25 18:40
Any update on this? yet another closed flutter thread with no answer...
