### ISSUE TITLE
Switch statement over an enum warns of a missing return statement.

### ISSUE THREAD

**Issue by adcaine** [flutter/flutter#47377] opened 2019-12-18 21:26 UTC
1. Define an enumeration.
2. Write a switch statement over that enumeration with every case of the enum covered.

Expected:

No default case is required.  The switch statement handles all the possibilities.

Actual:

Warning of a missing default case.

Example:

The default case is not required in the following code because the switch statement has accounted for all 7 possible values of the WeatherCondition enum.  Warnings suggest that a default case is required.

  ///
  /// Returns the [String] corresponding to the [WeatherCondition].
  ///
  /// The [WeatherCondition] is required.
  ///
  static String fromWeatherCondition(WeatherCondition weatherCondition) {
    switch (weatherCondition) {
      case WeatherCondition.cloudy:
        return "Cloudy";
      case WeatherCondition.foggy:
        return "Foggy";
      case WeatherCondition.rainy:
        return "Rainy";
      case WeatherCondition.snowy:
        return "Snowy";
      case WeatherCondition.sunny:
        return "Sunny";
      case WeatherCondition.thunderstorm:
        return "T-storm";
      case WeatherCondition.windy:
        return "Windy";
    }
  }

**Comment by stuartmorgan** [comment] 2019-12-18 23:18
> The switch statement handles all the possibilities.

It doesn't handle `null`.

Duplicate of https://github.com/dart-lang/sdk/issues/37498

**Closed by stuartmorgan** 2019-12-18 23:18 UTC

**Comment by adcaine** [comment] 2019-12-19 00:17
Thank you for your comment Stuart.

Is the Flutter team considering a @NonNull annotation or prohibiting the passing of null when a function's parameter is an Enum?

To prevent the warning, I found it necessary write a default case which throws an exception.  I believe very strongly that it be a build error to pass null into a function which requires an Enum.

For the record, this code suppresses the error.   I believe it would be better to prevent null from being passed in the first place.  BTW, an assert that the parameter is not null doesn't help.

  ///
  /// Returns the [String] corresponding to the [WeatherCondition].
  ///
  /// If null is passed, an exception is thrown.
  ///
  /// The [WeatherCondition] is required.
  ///
  static String fromWeatherCondition(WeatherCondition weatherCondition) {
    switch (weatherCondition) {
      case WeatherCondition.cloudy:
        return "Cloudy";
      case WeatherCondition.foggy:
        return "Foggy";
      case WeatherCondition.rainy:
        return "Rainy";
      case WeatherCondition.snowy:
        return "Snowy";
      case WeatherCondition.sunny:
        return "Sunny";
      case WeatherCondition.thunderstorm:
        return "T-storm";
      case WeatherCondition.windy:
        return "Windy";
      default:
        throw Exception("Must be a valid weather condition"); 
    }
  }
