### ISSUE TITLE
WhitelistingTextInputFormatter blanks out the TextFormField when entered any other character which is not white-listed

### ISSUE THREAD

**Issue by sanjay4one** [flutter/flutter#54417] opened 2020-04-10 04:51 UTC
## Steps to Reproduce

I am trying to restrict the `TextFormField` to only accept signed decimal values. I have used `WhitelistingTextInputFormatterRegExp(r'(^\-?\d*\.?\d*)$'))`  for the validation. The regex seems to be working fine. But the problem is when I try to enter any other character which should not be accepted by the `TextFormField`, the textfield becomes blank. Please refer the below code snippet.
```
TextFormField(
        key: AppKeys.emailField,
        keyboardType: TextInputType.text,
        controller: controller.emailTextController,
        inputFormatters: [
          WhitelistingTextInputFormatter(RegExp(r'(^\-?\d*\.?\d*)$')),
        ],
        maxLength: 100,
        decoration: InputDecoration(
          labelText: Strings.emailPrompt,
          counterText: '',
          prefixIcon: Icon(Icons.email),
        ),
        //validator: Validator.validateEmail,
        onSaved: (String val) {
          //_email = val;
        },
        onChanged: (String text) {
          debugPrint('value is $text');
        },
      );
```

**Expected results:** The `TextFormField` should not be blank if we enter any other character which is not whitelisted.

**Actual results:** The `TextFormField` becomes blank when we enter any other character which is not being passed to `WhitelistingTextInputFormatter`.

<details>
  <summary>Logs</summary>

Output of `flutter doctor -v`

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter_windows_v1.7.8+hotfix.4-stable\flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\AndroidSDK\Android\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-13 10:14
<details>
 <summary>complete code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  final _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextFormField(
            keyboardType: TextInputType.text,
            controller: _controller,
            inputFormatters: [
              WhitelistingTextInputFormatter(RegExp(r'(^\-?\d*\.?\d*)$')),
            ],
            maxLength: 100,
            decoration: InputDecoration(
              labelText: 'label',
              counterText: '',
              prefixIcon: Icon(Icons.email),
            ),
            //validator: Validator.validateEmail,
            onSaved: (String val) {
              //_email = val;
            },
            onChanged: (String text) {
              debugPrint('value is $text');
            },
          ),
        )
      ),
    );
  }
}
```

</details>

**Comment by pedromassango** [comment] 2020-05-14 20:54
I recently had the same issue.

**Comment by jason-simmons** [comment] 2020-06-11 01:35
`WhitelistingTextInputFormatter` removes all characters that do not match a class of characters described by the regex.  For example, `WhitelistingTextInputFormatter.digitsOnly` matches on `RegExp(r'\d+')` and will filter out any character that is not a digit.

`WhitelistingTextInputFormatter` will not work as intended with a regex that matches the full string (as seen in the example in this issue).

Try using `TextInputFormatter.withFunction` to restrict a text field to strings that match a regex like that:
```
TextInputFormatter.withFunction((oldValue, newValue) =>
    RegExp(r'(^\-?\d*\.?\d*)$').hasMatch(newValue.text) ? newValue : oldValue)
```

**Comment by sm9i** [comment] 2020-07-13 02:41
> TextInputFormatter

Thank you. It can solve the problem

**Comment by pedromassangocode** [comment] 2020-12-17 13:30
Reproducible on latest `master` and `stable` channels.

The code bellow is updated to use the latest text input API.

### Steps to reproduce

1. Run the code bellow
2. Type `12345` then type any letter.
3. **EXPECTED**: Expect the numbers to not be removed
4. **ACTUAL**: numbers are removed.


<details><summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: TextFormField(
              keyboardType: TextInputType.text,
              inputFormatters: [
                FilteringTextInputFormatter.allow(RegExp(r'^[0-9]+$')),
              ],
              maxLength: 100,
              decoration: InputDecoration(
                labelText: 'This field allows 0-9 only',
                counterText: '',
                prefixIcon: Icon(Icons.email),
              ),
              onChanged: (String text) {
                debugPrint('value is $text');
              },
            ),
          ),
        ),
      ),
    );

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.64 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 9ff4326e1f (7 hours ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by mamuseferha** [comment] 2021-10-21 07:49
Hi @sanjay4one
Thanks for filing this issue, consider using ``` TextInputFormatter.withFunction``` as suggested in this comment https://github.com/flutter/flutter/issues/54417#issuecomment-642353083
I have also included a sample code, please let me know if this resolves the issue. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: TextFormField(
              keyboardType: TextInputType.text,
              inputFormatters: [
                TextInputFormatter.withFunction((oldValue, newValue) =>
                    RegExp(r'(^\-?\d*\.?\d*)$').hasMatch(newValue.text)
                        ? newValue
                        : oldValue)
              ],
              maxLength: 100,
              decoration: InputDecoration(
                labelText: 'This field allows 0-9 only',
                counterText: '',
                prefixIcon: Icon(Icons.email),
              ),
              onChanged: (String text) {
                debugPrint('value is $text');
              },
            ),
          ),
        ),
      ),
    );

```
</details>

<details>
<summary>Output</summary>
<img src="https://user-images.githubusercontent.com/92717368/138234013-0e67f36e-1ad3-49a7-a057-a2ef22f343e5.gif" width="250" height="550" />

</details>
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.436, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.436 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 062d1e5c20 (52 minutes ago), 2021-10-21 02:48:04 -0400
    • Engine revision d4e2709791
    • Dart version 2.15.0 (build 2.15.0-233.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by danagbemava-nc** [comment] 2021-11-17 12:44
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 12:44 UTC
Labels: a: text input, waiting for customer response, framework, f: material design, has reproducible steps, found in release: 2.5, found in release: 2.6
