### ISSUE TITLE
SelectionArea does not work on  CustomPaint

### ISSUE THREAD

**Issue by jisuz** [flutter/flutter#159532] opened 2024-11-27 08:28 UTC
### Use case

SelectionArea does not work on  CustomPaint。
`SelectionArea(`
              `child: CustomPaint(`
               ` painter: MyPainter(useTextPainter),`
            `  ),`
             ` onSelectionChanged: (value) {`
                `debugPrint("onSelectionChanged: ${value}");`
             ` },`
         `   ),`

### Proposal

`SelectionArea(`
              `child: CustomPaint(`
               ` painter: MyPainter(useTextPainter),`
            `  ),`
             ` onSelectionChanged: (value) {`
                `debugPrint("onSelectionChanged: ${value}");`
             ` },`
         `   ),`

**Comment by danagbemava-nc** [comment] 2024-11-27 09:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137977

Kindly leave a thumbs up on the original issue. 

Thank you

**Closed by danagbemava-nc** 2024-11-27 09:43 UTC
Labels: in triage
