### ISSUE TITLE
CupertinoNavigationBar disappears on route swipe back

### ISSUE THREAD

**Issue by hazzo** [flutter/flutter#57872] opened 2020-05-23 20:05 UTC
## Steps to Reproduce

1. Use code sample from: [Navigation back and forward](https://flutter.dev/docs/cookbook/navigation/navigation-basics)
2. Change every `MaterialPageRoute` for `CupertinoPageRoute` and change `AppBar` for `CupertinoNavigationBar`
3. Run app
4. Navigate to second route.
5. Swipe back without lifting your finger. Keep moving your finger like you would like to abort navigation (swiping left instead of right) but still not lift your finger. Now reach a little bit further to the left and try to swipe back again to right (to pop navigation). The `CupertinoNavigationBar` should disappear.

**Sample**
![Alt Text](https://media.giphy.com/media/TigR69lv2RS6yl1Snd/giphy.gif)

**Expected results:** 
Navigation bar should not disappear on route swipe back.

**Actual results:** 
Navigation bar disappears on route swipe back.

**Version**
Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-ES)

**Comment by hazzo** [comment] 2020-05-24 11:15
Just for the record, even replacing `MaterialApp` for `CupertinoApp` and `Scaffold` for `CupertinoPageScaffold` problem persists.

**Comment by TahaTesser** [comment] 2020-05-25 11:28
duplicate of https://github.com/flutter/flutter/issues/57581

**Closed by TahaTesser** 2020-05-25 11:28 UTC
