### ISSUE TITLE
Race condition when using TabBarView animation and InheritedWidget together

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#110247] opened 2022-08-25 08:32 UTC
I'm using an InhertiedWidget to manage the state of a counter in this app. 

However, if I update the state and change tabs at the same time, the update doesn't seem to pass through to the tabs.

I asked a question on [StackOverflow first](https://stackoverflow.com/questions/73470894/tabbarview-doesnt-update-inhertiedwidget-state-if-tab-is-changed-programaticall), and it seems like there's a race condition in either my code or flutter that prevents the InhertiedWidget state from being passed down to the tabs.

**Steps to Reproduce**

1. [Run on dartpad](https://dartpad.dev/?id=41b7202409886f08b8ca8827b52dad10)
2. Go to tab B
3. Press + button

**Expected results: The tab changes to A, and the counter updates in the tab** 

**Actual results: The tab changes to A, but the counter does not update (even though the actual value changes)** 

Here's a video to explain what I mean - 
https://user-images.githubusercontent.com/19492893/186615530-d3e063c7-3583-4cc1-b3a2-cefae71fc533.mov

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MainApp());

class MainApp extends StatefulWidget {
  const MainApp({
    Key? key,
  }) : super(key: key);

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  int count = 1;

  @override
  Widget build(BuildContext context) {
    return CounterInheritedWidget(
      count: count,
      child: MaterialApp(
        home: DefaultTabController(
          length: 2,
          child: CounterTabs(
            increment: increment,
          ),
        ),
      ),
    );
  }

  void increment() {
    setState(() {
      count += 1;
    });
  }
}

class CounterInheritedWidget extends InheritedWidget {
  const CounterInheritedWidget({
    Key? key,
    required this.count,
    required Widget child,
  }) : super(key: key, child: child);

  final int count;

  static CounterInheritedWidget of(BuildContext context) {
    final CounterInheritedWidget? result =
        context.dependOnInheritedWidgetOfExactType<CounterInheritedWidget>();
    assert(result != null, 'No CounterInheritedWidget found in context');
    return result!;
  }

  @override
  bool updateShouldNotify(CounterInheritedWidget old) => count != old.count;
}

class CounterTabs extends StatelessWidget {
  final VoidCallback increment;

  const CounterTabs({Key? key, required this.increment}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    int count = CounterInheritedWidget.of(context).count;
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
            DefaultTabController.of(context)?.animateTo(0);
            increment();
          });
        },
      ),
      appBar: AppBar(
        title: Text("Actual value: $count"),
        bottom: TabBar(
          tabs: [
            Tab(text: "A"),
            Tab(text: "B"),
          ],
        ),
      ),
      body: TabBarView(
        children: [
          Center(child: Text("Tab value: $count")),
          Center(child: Text("Tab value: $count")),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • POCO F1 (mobile) • e19ec1f6 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)  • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 104.0.5112.101
    ! Error: iPad is not connected. Xcode will continue when iPad is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Sorry if this is a weird edge case that is not supported by the framework, thanks for looking through my code :)

**Comment by exaby73** [comment] 2022-08-25 15:01
Marking as duplicate of https://github.com/flutter/flutter/issues/107399. Thank you.

**Closed** 2022-08-25 15:01 UTC
Labels: in triage, r: duplicate
