### ISSUE TITLE
Child process continues to run after app is closed on linux

### ISSUE THREAD

**Issue by thiagorb** [flutter/flutter#136609] opened 2023-10-15 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the script provided below, and then check if the bash script is still running.

### Expected results

The program exits after 3 seconds, printing "Hello from bash!" a few times, and bash is terminated together with the program.

### Actual results

The program terminates, but bash keeps running in the background.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:io';

Future<void> main() async {
  final process = await Process.start('bash', ['-c', 'while true; do echo "Hello from bash!"; sleep 1; done;']);

  process.stdout.pipe(stdout);

  await Future.delayed(const Duration(seconds: 3));
  exit(0);
}
```
In order to simplify the reproduction case I ran the following docker command:
```bash
docker run --rm -i dart:3.0 bash -c '(apt-get update -y && apt-get install -y procps) > /dev/null 2>&1 && dart --disable-analytics run <(cat); ps -aux' <<'DART'
import 'dart:io';

Future<void> main() async {
  final process = await Process.start('bash', ['-c', 'while true; do echo "Hello from bash!"; sleep 1; done;']);

  process.stdout.pipe(stdout);

  await Future.delayed(const Duration(seconds: 3));
  exit(0);
}
DART
```
</details>

### Logs

<details><summary>Logs</summary>

```console
Hello from bash!
Hello from bash!
Hello from bash!
Hello from bash!
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.2  0.0   6756  2816 ?        Rs   19:21   0:00 ps -aux
root         362  0.0  0.0   3896  2816 ?        S    19:21   0:00 bash -c while true; do echo "Hello from bash!"; sleep 1; done;
root         367  0.0  0.0   2392  1152 ?        S    19:21   0:00 sleep 1
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.13.7 on channel stable at /home/thiago/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (6 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2023-10-16 10:21
Hi @thiagorb 
I checked this on my Linux machine (Ubuntu distro with the same version `22.04.3 LTS 6.2.0-34-generic`) but can't reproduce this. It's always 3 output text in the console as below:

```console
3 Hello from bash!
Lost connection to device.

Exited.
```
Did you have this issue on local machine or only on Docker container?

**Comment by thiagorb** [comment] 2023-10-16 11:02
@huycozy The issue happens on both. But just to be clear, the flutter application terminates as expected. As I showed in the logs output, the message gets printed only 3 times as well.

The only problem is that the bash script gets "re-parented" and keeps running in the background. The output is just not visible anymore because the flutter app is not there anymore to pipe the output.

So, to check that the issue is happening you really need to run `ps -aux` or some other tool to see that the bash process is still running.

**Comment by huycozy** [comment] 2023-10-17 04:27
Are you checking this on Terminal or any IDE? 

I notice the `dart` process still persists if testing this on IDE (verified on VS Code). I guess it's due to IDE's Flutter plugin holding the process somehow. But if I check this on Terminal instead, the `dart` process is released/disappears after app shutdown.

[Screencast from 17-10-2023 11:17:03.webm](https://github.com/flutter/flutter/assets/104349824/457748e0-8147-4cbc-bde9-71fe83da9b42)

On the demo video, I checked `dart` process on System Monitor and also with `ps -aux` command.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.13.7 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (7 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (version unknown)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /home/huynq/Documents/android-studio
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.16.0-11.0.pre.70, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0-11.0.pre.70 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6d5691b4c8 (24 minutes ago), 2023-10-16 03:22:18 -0400
    • Engine revision 12122eac28
    • Dart version 3.3.0 (build 3.3.0-27.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (version unknown)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /home/huynq/Documents/android-studio
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by thiagorb** [comment] 2023-10-17 06:49
@huycozy I'm not saying dart process keeps running. I'm talking about bash, the process started by my application.

[output.webm](https://github.com/flutter/flutter/assets/821208/f704fbdc-4f1b-455a-982d-acff5ba4aa68)

**Comment by huycozy** [comment] 2023-10-17 07:44
Oops, sorry! I misread that. I can see the issue now on Linux and also reproduce it on macOS as well. Moreover, if I run the sample as a Dart program, it outputs 4 messages as your result. I think this should be filed on [dart-lang/sdk](https://github.com/dart-lang/sdk) repository for better support there. 

Closing as this seems to be a Dart issue rather than a Flutter framework issue. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2023-10-17 07:44 UTC
Labels: in triage
