### ISSUE TITLE
App "Not installed for this user"

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#47468] opened 2019-12-19 17:05 UTC
A few days back, after writing some code that got my app suck in a loop reading & writing to firestore my app stopped installing to my phone. I tried running flutter upgrade/clean etc and attempted to uninstall the app from my device, (the uninstall seemed to work fine). However now when I run `flutter run` it hangs after installing to device. Running via my IDE appears to hang on step "Installing build/app/outputs/apk/app.apk...".

My app can be installed and works on an emulator so I was trying to figure out the discrepency with the emulator and my physical device. I found my app is still somehow installed on my device yet apparently not for my user:

![Screenshot_20191218-150039~2](https://user-images.githubusercontent.com/298850/71193025-490dfb00-2281-11ea-84a2-edc4c9247bc4.png)
(The circled app is my flutter app)

When I click in to the app it doesn't ever compute the sizes etc:

![Screenshot_20191218-150055](https://user-images.githubusercontent.com/298850/71193064-5f1bbb80-2281-11ea-8ca3-c13bca1cdf4b.png)

Have you guys seen this before? Any idea how I can get this off my phone (none-rooted) so I can go back to debugging with my physical device?

Thanks

**Comment by dnfield** [comment] 2019-12-19 17:14
see https://stackoverflow.com/questions/30011656/app-not-installed-for-this-user

I'm not sure how you got to this state - if you find some way to reproduce it using the flutter tooling we should address it, but for now I'm going to close this since I don't think it's a flutter bug.

**Closed by dnfield** 2019-12-19 17:14 UTC

**Comment by jimmyff** [comment] 2019-12-19 17:21
Output from flutter doctor:
```
[✓] Flutter (Channel master, v1.13.3-pre.83, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.13.3-pre.83 at /Users/jimmyff/flutter-sdk
    • Framework revision 78db965642 (7 hours ago), 2019-12-19 11:23:01 +0100
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Development/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Pixel 3 • 8B5X140C0 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

This is the last bit of flutter run:
```
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        55.7s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         7.2s
```
It hangs here and never gets further.

**Comment by jimmyff** [comment] 2019-12-19 17:26
@dnfield fair enough but this has only ever happened to me with a flutter app and happened whilst actively developing so I think it's most likley connected.

Thanks for the link but sadly android 10 doesn't have the mentioned option to uninstall for all users. I'll try to raise a bug against android for it.

**Comment by jimmyff** [comment] 2019-12-19 17:38
I've raised an issue on the Android issue tracker: https://issuetracker.google.com/issues/146535409

**Comment by dnfield** [comment] 2019-12-19 17:42
Thanks!  Please feel free to update this if it does turn out we're doing something we shouldn't (missing some flag to adb or something).
