### ISSUE TITLE
Unexplained exception when trying to use FutureBuilder with FirebaseFirestore.instance

### ISSUE THREAD

**Issue by chriscross12324** [flutter/flutter#98098] opened 2022-02-09 06:58 UTC
## Steps to Reproduce

1) Retrieve FirebaseFirestore document with 
`FirebaseFirestore.instance.collection('song-cores-demo').get()`

2) Use **FutureBuilder** with the data above

3) 4.5k repeating error log telling you to put in a bug report.

**Expected results:**
A screen showing Firebase items in a Grid

**Actual results:**
`The following assertion was thrown building _FocusTraversalGroupMarker:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4313 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.`

<details>
<summary>Code sample</summary>

```
class _HomeDiscoverSongsState extends State<HomeDiscoverSongs> {
  @override
  Widget build(BuildContext context) {
    final databaseReference = FirebaseFirestore.instance
        .collection('song-cores-demo')
        //.orderBy('songAddedDate', descending: true)
        .limit(1)
        .get();

    return SliverPadding(
      padding: EdgeInsets.symmetric(horizontal: 20),
      sliver: FutureBuilder<QuerySnapshot>(
        future: FirebaseFirestore.instance.collection('song-cores-demo').get(),
        builder: (context, snapshot) {
          return Container();
        }
      ),
      );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Title(title: "Hello", color: MaterialColor(primary value: Color(0xff2196f3))):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4313 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/chris/StudioProjects/songrecommend/lib/main.dart:33:12
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4313:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4316:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (255 frames)
#260    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#263    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:495:11)
#264    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#265    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#266    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#267    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:395:11)
...     Normal element mounting (7 frames)
#274    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#275    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#276    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#277    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#278    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#279    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#280    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#281    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#282    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#283    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

```
No issues found! (ran in 1.3s)

```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm,
    locale en-CA)
    • Flutter version 2.8.1 at /Users/chris/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16
      08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.0.0)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • SM G981W (mobile) • RFCN20HBY3B • android-arm64 • Android 12
      (API 31)
    • macOS (desktop)   • macos       • darwin-arm64  • macOS 12.2
      21D49 darwin-arm

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2022-02-09 10:08
@chriscross12324 
Looking at the error log, it definitely seems to be coming from the framework, but in order to address it properly, we would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugin, that we can directly run and it replicates the error you reported.
In your code provided, you seem to be using `cloud_firestore` which is a 3rd party plugin.

**Comment by darshankawar** [comment] 2022-02-10 05:07
Thanks for digging and identifying the root cause and glad to know you got it working. Closing this as not a Flutter issue.

**Closed by darshankawar** 2022-02-10 05:07 UTC
Labels: in triage
