### ISSUE TITLE
Wrong cursor selection when unfocus - focus on Android 5.1 

### ISSUE THREAD

**Issue by mpi3d** [flutter/flutter#61842] opened 2020-07-20 07:32 UTC
## Description

Hello, I'm working on a TextField to modify an IP address. And I would like to preselect the last digits after the last point when it is focused.
I've already done my code but there is a little problem. When my text is preselected and I press the backspace, the first time it works perfectly and erases the selection. But the other times, after an unfocus and a focus this erases the character before the selection.
I think it's a wrong cursor position. But I don't understand because I defined the affinity to TextAffinity.upstream. You can see an example with the following animation :

<img src="https://user-images.githubusercontent.com/26822551/87908609-030f5480-ca67-11ea-9d3c-49c778c6e6aa.gif" height="500">

## Steps to Reproduce

You can reproduce it with the follow code

``` dart
import "package:flutter/material.dart";

void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test"),
        ),
        body: Page(),
      ),
    );
  }
}

class Page extends StatefulWidget {
  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _focus = FocusNode();

  @override
  void initState() {
    super.initState();
    _controller.text = "192.168.0.12";
    _focus.addListener(() => _focus.hasFocus
        ? _controller.selection = TextSelection(
            baseOffset: _controller.text.lastIndexOf(".") + 1,
            extentOffset: _controller.text.length,
            affinity: TextAffinity.upstream,
          )
        : null);
  }

  @override
  void dispose() {
    _controller.dispose();
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Padding>[
        Padding(
          padding: EdgeInsets.all(10),
          child: TextField(
            controller: _controller,
            focusNode: _focus,
            decoration: const InputDecoration(
              labelText: "Test",
              suffixIcon: const Icon(Icons.router),
              border: const OutlineInputBorder(
                borderRadius: const BorderRadius.all(const Radius.circular(10)),
              ),
            ),
            keyboardType: TextInputType.datetime,
            textInputAction: TextInputAction.next,
            showCursor: false,
            onEditingComplete: () => FocusScope.of(context).nextFocus(),
          ),
        ),
        Padding(
          padding: EdgeInsets.all(10),
          child: RaisedButton(
            onPressed: () => FocusScope.of(context).unfocus(),
            child: const Text("Unfocus"),
          ),
        )
      ],
    );
  }
}
```

<details>

<summary>phone details</summary>

My phone is a HUAWEI CUN-L21 under android 5.1.

</details>

<details>

<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.66 at /home/mpi3d/flutter
    • Framework revision 54c9441723 (2 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/mpi3d/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2020-07-20 12:01
Hi @MPi3D
Even on multiple tries, i cannot reproduce this issue on Samsung device using Samsung Keyboard and Gboard. Can you please give us details on what device you experiencing this issue? or please try on emulator or device, if it reproduces or not 

<details> 
<summary>Code Sample</summary> 

```
import "package:flutter/material.dart";

void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test"),
        ),
        body: Page(),
      ),
    );
  }
}

class Page extends StatefulWidget {
  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _focus = FocusNode();

  @override
  void initState() {
    super.initState();
    _controller.text = "192.168.0.12";
    _focus.addListener(() => _focus.hasFocus
        ? _controller.selection = TextSelection(
            baseOffset: _controller.text.lastIndexOf(".") + 1,
            extentOffset: _controller.text.length,
            affinity: TextAffinity.upstream,
          )
        : null);
  }

  @override
  void dispose() {
    _controller.dispose();
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Padding>[
        Padding(
          padding: EdgeInsets.all(10),
          child: TextField(
            controller: _controller,
            focusNode: _focus,
            decoration: const InputDecoration(
              labelText: "Test",
              suffixIcon: const Icon(Icons.router),
              border: const OutlineInputBorder(
                borderRadius: const BorderRadius.all(const Radius.circular(10)),
              ),
            ),
            keyboardType: TextInputType.datetime,
            textInputAction: TextInputAction.next,
            showCursor: false,
            onEditingComplete: () => FocusScope.of(context).nextFocus(),
          ),
        ),
        Padding(
          padding: EdgeInsets.all(10),
          child: RaisedButton(
            onPressed: () => FocusScope.of(context).unfocus(),
            child: const Text("Unfocus"),
          ),
        )
      ],
    );
  }
}

``` 

</details> 
 
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/taha/Code/flutter_beta
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (5 available)            
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details> 

Thank you

**Comment by MPi3D** [comment] 2020-07-20 15:45
Hi @TahaTesser 

My phone is a HUAWEI CUN-L21 under android 5.1 with Android Keyboard (AOSP).
And sorry but I can't try on an emulator because my laptop is not powerful enough and I don't have any other phone.

Sorry

**Comment by MPi3D** [comment] 2020-07-20 17:14
Hi again @TahaTesser 

I have installed Gboard on my phone and its working perfectly! So the problem comes from Android Keyboard (AOSP) with maybe doesn't support the affinity parameter.

I let you resolve this.

**Comment by TahaTesser** [comment] 2020-07-21 08:10
I can reproduce this issue on Android 5.1 emulator 

<details> 
<summary>Code Sample</summary> 

```
import "package:flutter/material.dart";

void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test"),
        ),
        body: Page(),
      ),
    );
  }
}

class Page extends StatefulWidget {
  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _focus = FocusNode();

  @override
  void initState() {
    super.initState();
    _controller.text = "192.168.0.12";
    _focus.addListener(() => _focus.hasFocus
        ? _controller.selection = TextSelection(
            baseOffset: _controller.text.lastIndexOf(".") + 1,
            extentOffset: _controller.text.length,
            affinity: TextAffinity.upstream,
          )
        : null);
  }

  @override
  void dispose() {
    _controller.dispose();
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Padding>[
        Padding(
          padding: EdgeInsets.all(10),
          child: TextField(
            controller: _controller,
            focusNode: _focus,
            decoration: const InputDecoration(
              labelText: "Test",
              suffixIcon: const Icon(Icons.router),
              border: const OutlineInputBorder(
                borderRadius: const BorderRadius.all(const Radius.circular(10)),
              ),
            ),
            keyboardType: TextInputType.datetime,
            textInputAction: TextInputAction.next,
            showCursor: false,
            onEditingComplete: () => FocusScope.of(context).nextFocus(),
          ),
        ),
        Padding(
          padding: EdgeInsets.all(10),
          child: RaisedButton(
            onPressed: () => FocusScope.of(context).unfocus(),
            child: const Text("Unfocus"),
          ),
        )
      ],
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.83 at /home/taha/Code/flutter
    • Framework revision 9e658bc3d5 (6 hours ago), 2020-07-21 03:56:07 +0200
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      5.1.1 (API 22) (emulator)

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2022-12-15 11:06
Hi @mpi3d, this issue seems to have been fixed on the latest master channel as I cannot reproduce it there. See the demo below.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/207843592-ca157bee-e10e-4b69-b176-e22cdbf1625e.mov


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (31 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-9.0.pre.11, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-9.0.pre.11 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dbc9306380 (4 hours ago), 2022-12-14 13:53:20 -0800
    • Engine revision 0a6a4a58f4
    • Dart version 3.0.0 (build 3.0.0-21.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • SM T225 (mobile) • R9JT3004VRJ                              • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 108.0.5359.98
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

I'll be closing this issue since it has already been fixed on the latest master channel. If you still experience this issue on the master channel, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2022-12-15 11:06 UTC
Labels: a: text input, platform-android, framework, engine, f: material design, e: OS Version specific, has reproducible steps, P4, found in release: 1.21

**Comment by mpi3d** [comment] 2022-12-15 15:38
I don't have Android 5 anymore so I can't test. But I'm guessing it's fixed. Thanks
