### ISSUE TITLE
flutter build ios will package the PlatformInterface plugin Android material into ios Runner

### ISSUE THREAD

**Issue by fangwy** [flutter/flutter#123673] opened 2023-03-29 07:30 UTC
Since ios audit rules do not allow ipa files to contain other payment-related api code materials, try to use PlatformInterface to realize the separation of Android and IOS project payment-related code materials
However, in actual use, the materials of Android plug-in are still packaged into ios ipa files and need to be manually deleted, which caused me a lot of trouble

![screenshot-20230329-151906](https://user-images.githubusercontent.com/19532592/228457777-e867ee72-caf7-4e8c-8647-6ac1fe1f5c36.png)
![screenshot-20230329-151944](https://user-images.githubusercontent.com/19532592/228457819-70e0fe99-5186-4fb0-aa78-393481cd5412.png)
![20230329-152518](https://user-images.githubusercontent.com/19532592/228457944-7aae2135-cf7f-4d85-b858-263607153f1b.jpeg)

the materials of Android plug-in are still packaged into ios ipa files 

![screenshot-20230329-152341](https://user-images.githubusercontent.com/19532592/228457995-a6925fab-f9f8-4a17-9425-df9d8194a50b.png)

**Comment by stuartmorgan** [comment] 2023-03-29 11:57
Closing as a duplicate of https://github.com/flutter/flutter/issues/8230

> ![screenshot-20230329-151944](https://user-images.githubusercontent.com/19532592/228457819-70e0fe99-5186-4fb0-aa78-393481cd5412.png)

This is not actually the relevant part of the pubspec; elsewhere you must have a dependency on the implementation package, and the asserts for your dependencies are all packaged.

**Closed by stuartmorgan** 2023-03-29 11:57 UTC
Labels: team: infra
