### ISSUE TITLE
AlignedDropdown field in ButtonTheme widget adds extra padding when InputDecoration also has padding

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#132732] opened 2023-08-17 06:57 UTC
Copied from Google internal bug b/277235718:

When using a DropdownButtonFormField and want to the menu items to align with the dropdown button it is recommended to use ButtonTheme with the alignedDropdown field set to true. However, if the DropdownButtonFormField has label through InputDecoration it adds extra padding to the menu items. The padding in InputDecoration can't be set to zero because you need padding on the label and the border of the DropdownButtonFormField. I believe the padding is stacking on the DropdownMenuItem widget since it tries to align the menu items.

At minimum I believe that alignedDropdown should not add padding if an InputDecoration is present or something along that. It would be even more ideal to be able to set the padding on the menu of any DropdownButton widget.

Here is the olds github commit that I believe introduced the bug: https://github.com/flutter/flutter/pull/14849

<details>
<summary>Minimal repro example</summary>

```
import 'package:flutter/material.dart';
 
const Color darkBlue = Color.fromARGB(255, 18, 32, 47);
const List<String> list = <String>['One', 'Two', 'Three', 'Four'];
 
void main() {
  runApp(MyApp());
}
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}
 
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String dropdownValue = list.first;
 
    return Padding(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 8.0),
        child: ButtonTheme(
          alignedDropdown: true, // Comment toggle this line to see bug.
          child: DropdownButtonFormField<String>(
            value: dropdownValue,
            onChanged: (String? value) {},
            items: list.map<DropdownMenuItem<String>>((String value) {
              return DropdownMenuItem<String>(
                value: value,
                child: Text(value),
              );
            }).toList(),
            decoration: InputDecoration(
              contentPadding: const EdgeInsets.fromLTRB(16, 16, 12, 16),
              label: const Text('Decoration Label'),
              floatingLabelBehavior: FloatingLabelBehavior.always,
              errorMaxLines: 100,
              fillColor: Colors.transparent,
              enabledBorder: Borders.enabledBorder(context),
              errorBorder: Borders.errorBorder(context),
              focusedBorder: Borders.focusedBorder(context),
              focusedErrorBorder: Borders.focusedErrorBorder(context),
            ),
          ),
        ));
  }
}
 
class Borders {
  static InputBorder enabledBorder(BuildContext context) => const OutlineInputBorder(
        borderSide: BorderSide(color: Colors.yellow),
      );
 
  static InputBorder errorBorder(BuildContext context) => OutlineInputBorder(
        borderSide:
            BorderSide(color: Theme.of(context).primaryColor, width: 2),
      );
 
  static InputBorder focusedBorder(BuildContext context) => OutlineInputBorder(
        borderSide: BorderSide(color: Theme.of(context).primaryColor, width: 2),
      );
 
  static InputBorder focusedErrorBorder(BuildContext context) =>
      OutlineInputBorder(
        borderSide:
            BorderSide(color: Theme.of(context).primaryColor, width: 2),
      );
}
```

</details>

Prioritization: This would be very good to have but I don't believe it blocks.

**Comment by TahaTesser** [comment] 2023-08-17 07:48
duplicate of https://github.com/flutter/flutter/issues/123783

**Closed by TahaTesser** 2023-08-17 07:48 UTC
Labels: customer: money (g3), in triage
