### ISSUE TITLE
tried to build release apk but i got errors 

### ISSUE THREAD

**Issue by AbanoubWagih94** [flutter/flutter#53484] opened 2020-03-28 13:16 UTC
i was trying to build a release apk but i got errors below 
![Untitled](https://user-images.githubusercontent.com/32550947/77823739-0b353400-7106-11ea-98ca-0a84e04b1ee1.png)

and here my gradle and pubspec files 

![Untitled](https://user-images.githubusercontent.com/32550947/77823775-459ed100-7106-11ea-8a5d-6dfcfadeeec0.png)

![Untitled](https://user-images.githubusercontent.com/32550947/77823828-c9f15400-7106-11ea-9cb4-e0fd39435b7e.png)

![Untitled](https://user-images.githubusercontent.com/32550947/77823855-f1e0b780-7106-11ea-8efb-d05606090979.png)

![Untitled](https://user-images.githubusercontent.com/32550947/77823864-fdcc7980-7106-11ea-87fd-f0ecd6e3a787.png)

**Comment by iapicca** [comment] 2020-03-30 09:10
Hi @AbanoubWagih94  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

Please refrain from posting pictures if not necessary.
thank you

**Closed by iapicca** 2020-03-30 09:10 UTC
