### ISSUE TITLE
image_picker: FATAL EXCEPTION when choosing an image from downloads

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#21863] opened 2018-09-14 07:48 UTC
Tested on a real Pixel XL Android 9 (API 28)
image_picker version: 0.4.10
```
java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/15
```

```
D/AndroidRuntime(13697): Shutting down VM
E/AndroidRuntime(13697): FATAL EXCEPTION: main
E/AndroidRuntime(13697): Process: com.example.test, PID: 13697
E/AndroidRuntime(13697): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/15 flg=0x1 }} to activity {com.example.test/com.example.test.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/15
E/AndroidRuntime(13697): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime(13697): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime(13697): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(13697): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(13697): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(13697): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(13697): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13697): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(13697): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(13697): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13697): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(13697): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(13697): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/15
E/AndroidRuntime(13697): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime(13697): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(13697): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime(13697): 	at android.content.ContentResolver.query(ContentResolver.java:802)
E/AndroidRuntime(13697): 	at android.content.ContentResolver.query(ContentResolver.java:752)
E/AndroidRuntime(13697): 	at android.content.ContentResolver.query(ContentResolver.java:710)
E/AndroidRuntime(13697): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:117)
E/AndroidRuntime(13697): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:69)
E/AndroidRuntime(13697): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime(13697): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime(13697): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(13697): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(13697): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(13697): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(13697): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(13697): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime(13697): 	... 11 more
I/Process (13697): Sending signal. PID: 13697 SIG: 9
Application finished.
```
```
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.14 18A384a, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] Connected devices (3 available)

• No issues found!
```

**Comment by cbenhagen** [comment] 2018-09-14 08:09
As a hot-fix I changed `public_downloads` to `my_downloads` in https://github.com/flutter/plugins/blob/9616a32faf6d1066c8f633a30f0bd7dca6fe7e9e/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L66-L68

**Comment by ishaanbahal** [comment] 2018-09-23 12:50
Facing the same issue with Pixel 2XL Emulator.

**Comment by quanmltya** [comment] 2018-09-25 09:21
Got the same situation on Android O.

**Comment by amilaI** [comment] 2018-10-07 11:34
@cbenhagen Hey, I'm getting the same issue in android 8.0.0 (Phone: OnePlus3T). Your fix did not work for me. Any other workarounds ?? Please help!

**Comment by jiankai82** [comment] 2018-10-18 01:15
I am having the same issue.  Any solution?

**Comment by pojoba02** [comment] 2018-10-22 18:03
Having the same issue.

**Comment by ccoltos** [comment] 2018-10-25 14:04
I solved the issue by using streams and copying locally the file content from Uri to a cache directory. You can have a look on the [FileUtils->getPath()](https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java) method for the downloads documents case.

**Comment by jeffersonatsafe** [comment] 2018-10-26 20:38
I managed to get this working by using Downloads URI directly, like so: 

```
      } else if (isDownloadsDocument(uri)) {
          return getDataColumn(context, uri, null, null);
        }
```
replaced the following lines:
https://github.com/flutter/plugins/blob/9616a32faf6d1066c8f633a30f0bd7dca6fe7e9e/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L61-L73

I don't understand why the original code artificially replaced the Uri with 
`ContentUris.withAppendedId(Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));`
as it turns out, using the original downloads URI work too on older Android (tried on Nougat). 

I've tested with jpg, csv, and pdf files. Probably works for others too.

**Comment by quanmltya** [comment] 2018-10-27 15:13
> I managed to get this working by using Downloads URI directly, like so:
> 
> ```
>       } else if (isDownloadsDocument(uri)) {
>           return getDataColumn(context, uri, null, null);
>         }
> ```
> replaced the following lines:
> https://github.com/flutter/plugins/blob/9616a32faf6d1066c8f633a30f0bd7dca6fe7e9e/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L61-L73
> 
> I don't understand why the original code artificially replaced the Uri with
> `ContentUris.withAppendedId(Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));`
> as it turns out, using the original downloads URI work too on older Android (tried on Nougat).
> 
> I've tested with jpg, csv, and pdf files. Probably works for others too.

Tested on Oreo and getDataColumn() still return null.
Have not tested on Nougat- yet.

**Comment by quanmltya** [comment] 2018-10-29 13:56
> > I solved the issue by using streams and copying locally the file content from Uri to a cache directory. You can have a look on the [FileUtils->getPath()](https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java) method for the downloads documents case:
> > ```
> >         // DownloadsProvider
> >         else if (isDownloadsDocument(uri)) {
> > 
> >             final String id = DocumentsContract.getDocumentId(uri);
> > 
> >             if (id != null && id.startsWith("raw:")) {
> >                 return id.substring(4);
> >             }
> > 
> >             String[] contentUriPrefixesToTry = new String[]{
> >                     "content://downloads/public_downloads",
> >                     "content://downloads/my_downloads"
> >             };
> > 
> >             for (String contentUriPrefix : contentUriPrefixesToTry) {
> >                 Uri contentUri = ContentUris.withAppendedId(Uri.parse(contentUriPrefix), Long.valueOf(id));
> >                 try {
> >                     String path = getDataColumn(context, contentUri, null, null);
> >                     if (path != null) {
> >                         return path;
> >                     }
> >                 } catch (Exception e) {}
> >             }
> > 
> >             // path could not be retrieved using ContentResolver, therefore copy file to accessible cache using streams
> >             String fileName = getFileName(context, uri);
> >             File cacheDir = getDocumentCacheDir(context);
> >             File file = generateFileName(fileName, cacheDir);
> >             String destinationPath = null;
> >             if (file != null) {
> >                 destinationPath = file.getAbsolutePath();
> >                 saveFileFromUri(context, uri, destinationPath);
> >             }
> > 
> >             return destinationPath;
> > ```
> 
> Just to add to this answer, mentioned two contentUriPrefixes weren't enough in my case, had to add "content://downloads/all_downloads" as well. After that It worked on all phones.

Again, not work on my phone. File path is null. Tried my_downloads, public_downloads, all_downloads.
//I'm talking about getting real file path.

**Comment by naveedahmad99** [comment] 2018-11-06 17:16
> Ok I solved this issue, somewhat.
> For the record, I'm not a big fan of what `FileUtils.java` is doing right now.
> 
> I noticed that the issues seems to happen only in Android 8.0. It didn't exist in 7.0, and it didn't happen for me in 8.1.
> 
> Here's what I've done:
> 
> ```
>       } else if (isDownloadsDocument(uri)) {
>         final String id = DocumentsContract.getDocumentId(uri);
> 
>         if (!TextUtils.isEmpty(id)) {
>           if (id.startsWith("raw:")) {
>             return id.replaceFirst("raw:", "");
>           }
>           try {
>             final Uri contentUri =
>                 ContentUris.withAppendedId(
>                     Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));
>             return getDataColumn(context, contentUri, null, null);
>           } catch (Exception e) {
>             // Do nothing, try something else
>           }
>         }
> ```
> this goes to this section of the code:
> https://github.com/flutter/plugins/blob/9616a32faf6d1066c8f633a30f0bd7dca6fe7e9e/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L61-L73
> 
> Ultimately, I think the best way to resolve Files is to actually copy it to a temporary file somewhere else (which is what this code is doing to remote files)

Worked for me, tha

> > > I solved the issue by using streams and copying locally the file content from Uri to a cache directory. You can have a look on the [FileUtils->getPath()](https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java) method for the downloads documents case:
> > > ```
> > >         // DownloadsProvider
> > >         else if (isDownloadsDocument(uri)) {
> > > 
> > >             final String id = DocumentsContract.getDocumentId(uri);
> > > 
> > >             if (id != null && id.startsWith("raw:")) {
> > >                 return id.substring(4);
> > >             }
> > > 
> > >             String[] contentUriPrefixesToTry = new String[]{
> > >                     "content://downloads/public_downloads",
> > >                     "content://downloads/my_downloads"
> > >             };
> > > 
> > >             for (String contentUriPrefix : contentUriPrefixesToTry) {
> > >                 Uri contentUri = ContentUris.withAppendedId(Uri.parse(contentUriPrefix), Long.valueOf(id));
> > >                 try {
> > >                     String path = getDataColumn(context, contentUri, null, null);
> > >                     if (path != null) {
> > >                         return path;
> > >                     }
> > >                 } catch (Exception e) {}
> > >             }
> > > 
> > >             // path could not be retrieved using ContentResolver, therefore copy file to accessible cache using streams
> > >             String fileName = getFileName(context, uri);
> > >             File cacheDir = getDocumentCacheDir(context);
> > >             File file = generateFileName(fileName, cacheDir);
> > >             String destinationPath = null;
> > >             if (file != null) {
> > >                 destinationPath = file.getAbsolutePath();
> > >                 saveFileFromUri(context, uri, destinationPath);
> > >             }
> > > 
> > >             return destinationPath;
> > > ```
> > 
> > 
> > Just to add to this answer, mentioned two contentUriPrefixes weren't enough in my case, had to add "content://downloads/all_downloads" as well. After that It worked on all phones.
> 
> Again, not work on my phone. File path is null. Tried my_downloads, public_downloads, all_downloads.
> //I'm talking about getting real file path.

Worked for me

**Comment by vishrut2207** [comment] 2018-11-21 04:59
I have resolved this issue by applying belove code.

```
if (isDownloadsDocument(uri)) {
                final String id = DocumentsContract.getDocumentId(uri);
                if (id.startsWith("raw:")) {
                    String[] data = new String[2];
                    data[0] = id.replaceFirst("raw:", "");
                    data[1] = null;
                    return data;
                }
                Uri contentUri = uri;
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
                    contentUri = ContentUris.withAppendedId(
                            Uri.parse("content://downloads/public_downloads"), Long.valueOf(id));
                }
                return getDataColumn(context, contentUri , null, null);
            }
```

**Comment by HBiSoft** [comment] 2018-11-23 07:20
@vishrut2207 Can you please explain the following:

```
if (id.startsWith("raw:")) {
    String[] data = new String[2];
    data[0] = id.replaceFirst("raw:", "");
    data[1] = null;
    return data;
}
```
Why do you add this and should `return data;` not be `return data[0]`?

I'm just trying to understand why the issue happens in the first place and why does the above fix it?

**Comment by dschrul** [comment] 2018-12-12 21:08
Same issue here. Please fix this, I don't know how fix this locally for myself.

**Comment by ishaanbahal** [comment] 2018-12-27 17:13
Hey, if any maintainer checks this issue, please review my PR https://github.com/flutter/plugins/pull/1007 that tries to fix this issue. Thanks :)

**Comment by truongsinh** [comment] 2019-01-03 06:59
see also https://github.com/flutter/plugins/pull/986 opened 21 days ago

**Comment by zoechi** [comment] 2019-01-03 07:32
Similar to #17165

**Comment by tiholic** [comment] 2019-01-12 22:05
When can we expect a fix for this! Awaiting app release 🤞

**Comment by albertnjoku** [comment] 2019-01-14 22:06
How can I apply this change? Am using Image Picker version 0.4.12 but still face this issue.

**Comment by truongsinh** [comment] 2019-01-15 03:59
@tiholic @albertnjoku , while waiting for the fix to land, I published a community package as a drop in replacement for this. https://pub.dartlang.org/packages/image_picker_modern

**Comment by tiholic** [comment] 2019-01-16 23:34
@truongsinh it works great, thanks

**Comment by dschrul** [comment] 2019-01-17 06:12
@truongsinh thanks for fixing this, works great for android. But I think there's a problem with https://github.com/truongsinh/flutter-plugins/blob/master/packages/image_picker/ios/image_picker.podspec:
you need to rename it to image_picker_modern.podspec and also change the name inside that file to image_picker_modern. Because it's not working for ios right now.

**Comment by truongsinh** [comment] 2019-01-17 06:17
Thanks for pointing this out. Will make the change and self-tested in a moment.

**Comment by truongsinh** [comment] 2019-01-17 08:21
@dschrul https://pub.dartlang.org/packages/image_picker_modern/versions/0.4.13-1 published.

**Comment by cyanglaz** [comment] 2019-01-18 17:51
I have merged [flutter/plugins/pull/1089] that fixed this issue. The package version has been updated to 0.4.12+1. Going to close this now and if anyone discovers related crashes again, please reopen the issue.

**Closed by cyanglaz** 2019-01-18 17:51 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash, waiting for PR to land (fixed)

**Comment by willvlad** [comment] 2019-02-16 23:08
Crashing for me on Ulefone P2, using 0.4.12+1, when picking an image from the gallery

```FATAL EXCEPTION: main
E/AndroidRuntime(23871): Process: com.xxx.xxx, PID: 23871
E/AndroidRuntime(23871): java.lang.RuntimeException: Unable to resume activity {com.xxx.xxx/com.xxx.xxx.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:142567 flg=0x1 }} to activity {com.xxx.xxx/com.xxx.xxx.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
E/AndroidRuntime(23871): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3506)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2795)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(23871): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
E/AndroidRuntime(23871): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(23871): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.main(ActivityThread.java:6247)
E/AndroidRuntime(23871): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23871): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/AndroidRuntime(23871): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/AndroidRuntime(23871): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:142567 flg=0x1 }} to activity {com.xxx.xxx/com.xxx.xxx.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
E/AndroidRuntime(23871): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3474)
E/AndroidRuntime(23871): 	... 10 more
E/AndroidRuntime(23871): Caused by: java.lang.IllegalStateException: Received image from picker that was not requested
E/AndroidRuntime(23871): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:457)
E/AndroidRuntime(23871): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:396)
E/AndroidRuntime(23871): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(23871): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(23871): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(23871): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(23871): 	at android.app.Activity.dispatchActivityResult(Activity.java:6934)
E/AndroidRuntime(23871): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
E/AndroidRuntime(23871): 	... 11 more```

**Comment by cyanglaz** [comment] 2019-02-17 06:55
@willvlad Thank you for finding the crash. May I ask if you have "Don't keep activities" enabled in the debug setting in your device?

**Comment by truongsinh** [comment] 2019-02-18 14:53
@willvlad could you please share your code, step to reproduce, and/or check my previous comment and try with (forked / non-official package) https://pub.dartlang.org/packages/image_picker_modern/versions/0.4.13-1

> @dschrul https://pub.dartlang.org/packages/image_picker_modern/versions/0.4.13-1 published.

**Comment by hack4mer** [comment] 2019-03-04 12:14
Rename getPath to getPathTry in [FileUtils.java](https://raw.githubusercontent.com/coltoscosmin/FileUtils/master/FileUtils.java)
Then define getParth as following:
``
    public static String getPath(final Context context,final  Uri uri){

        String path = getPathTry(context,uri);

        if(path!=null){
            return path;
        }

        // path could not be retrieved using ContentResolver, therefore copy file to accessible cache using streams
        String fileName = getFileName(context, uri);
        File cacheDir = getDocumentCacheDir(context);
        File file = generateFileName(fileName, cacheDir);
        String destinationPath = null;
        if (file != null) {
            destinationPath = file.getAbsolutePath();
            saveFileFromUri(context, uri, destinationPath);
        }

        return destinationPath;

    }``

**Comment by diver2** [comment] 2019-03-15 17:29
please can anyone tell me how do I get to my flutter image picker FileUtils.java file?
Or, if I clone the plugin, how do I reference it? 
Seems basic, I guess it is basic, but flutter was meant for this I guess

**Comment by diver2** [comment] 2019-03-15 17:47
E/BitmapFactory(26640): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Download/cube-clipart-unit-cube-3.png (No such file or directory)
D/AndroidRuntime(26640): Shutting down VM
E/AndroidRuntime(26640): FATAL EXCEPTION: main
E/AndroidRuntime(26640): Process: com.logbkapp.app, PID: 26640
E/AndroidRuntime(26640): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/627 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }} to activity {com.logbkapp.app/com.logbkapp.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(26640): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
E/AndroidRuntime(26640): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
E/AndroidRuntime(26640): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime(26640): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
E/AndroidRuntime(26640): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26640): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(26640): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(26640): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26640): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(26640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime(26640): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(26640): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:48)
E/AndroidRuntime(26640): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
E/AndroidRuntime(26640): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:430)
E/AndroidRuntime(26640): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:372)
E/AndroidRuntime(26640): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:351)
E/AndroidRuntime(26640): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(26640): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime(26640): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(26640): 	at android.app.Activity.dispatchActivityResult(Activity.java:7256)
E/AndroidRuntime(26640): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
E/AndroidRuntime(26640): 	... 9 more

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/emiliomaciel/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emiliomaciel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/emiliomaciel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • SM G920F • 06157df6c54bcd08 • android-arm64 • Android 7.0 (API 24)

**Comment by diver2** [comment] 2019-03-15 17:49
I was trying to use image_picker latest (0.5.0+6)

**Comment by cyanglaz** [comment] 2019-03-15 18:12
@diver2 To reference a plugin locally you can add `path` attribute to the plugin inside pubspec. You can refer to https://www.dartlang.org/tools/pub/dependencies for more details.

**Comment by HBiSoft** [comment] 2019-03-15 18:20
For those who are interested, I created a gist that fixed this issue. I found this thread while searching for the crash. I'm not using flutter, but the FileUtil class is similiar.
 
I haven't had a crash in 2 months, so I think it's save to say that this will resolve your issue.

https://gist.github.com/HBiSoft/15899990b8cd0723c3a894c1636550a8

**Comment by diver2** [comment] 2019-03-15 18:59
> @diver2 To reference a plugin locally you can add `path` attribute to the plugin inside pubspec. You can refer to https://www.dartlang.org/tools/pub/dependencies for more details.

Tks, I managed to get to the java... still struggling with making this FileUtils work...

**Comment by cyanglaz** [comment] 2019-03-15 19:03
> > @diver2 To reference a plugin locally you can add `path` attribute to the plugin inside pubspec. You can refer to https://www.dartlang.org/tools/pub/dependencies for more details.
> 
> Tks, I managed to get to the java... still struggling with making this FileUtils work...

Could you explain what do you mean by `making this FileUtils work...`?

**Comment by diver2** [comment] 2019-03-15 19:14
I still get the error when using image picker - selecting an image from download folder, or an image that comes null...
I'm trying to implement now the solution from HBiSoft...

**Comment by diver2** [comment] 2019-03-15 19:27
I still get this (the root of the error, as above)
E/BitmapFactory( 9263): Unable to decode stream: java.io.FileNotFoundException: 20190315_173627.jpg (No such file or directory)
E/AndroidRuntime( 9263): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:206 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }} to activity {com.logbkapp.app/com.logbkapp.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

Even with HBISoft's FileUtil...

**Comment by cyanglaz** [comment] 2019-03-15 19:28
@diver2  could you provide a sample code to reproduce the issue. Also, what is the device that you are using. what is the Android version?

**Comment by diver2** [comment] 2019-03-15 19:32
void _getImage(BuildContext context, ImageSource source) {
    ImagePicker.pickImage(source: source, maxHeight: 400.0).then((io.File image) async {
      setState(() => _imageFile = image);
      Navigator.pop(context);
    }).catchError((onError) {
      print("WE ARE ON ERROR!!!");
      print(onError);
    });
  }

Pretty basic... 
Android 7.0 (Samsung S6)
anything else I can help?

**Comment by diver2** [comment] 2019-03-15 19:32
if I get image from camera, fine. From gallery... problem...

**Comment by diver2** [comment] 2019-03-15 20:10
my "fix" to this... on ImagePickerDelegate.java
Note I'm using HBISoft's File Util... (i did not try with the original one)
I just inserted a check for the file we got from FileUtils, and failed if that file wasn't readable.
```
private void handleChooseImageResult(int resultCode, Intent data) {
    if (resultCode == Activity.RESULT_OK && data != null) {
      //String path = fileUtils.getPathFromUri(activity, data.getData());
      String path = FileUtils.getRealPath(activity, data.getData());
      System.out.println(path);
      if ( !(new File(path).canRead() ) ) {
        finishWithSuccess(null);
        System.out.println("CANT READ");
        return;
      }
      handleImageResult(path);
      return;
    }

    // User cancelled choosing a picture.
    finishWithSuccess(null);
  }
```

**Comment by diver2** [comment] 2019-03-17 14:30
@cyanglaz @zoechi If someone walks me through the process of fixing this for image_picker, I can make the pull request/tests/commit this for everybody.
I tested with the FileUtils from image_picker, works fine. It seems it was not the fault of the FileUtils, it was just missing the test to see if the file existed. 
But there are other issues, such as the file on the gallery becoming duplicated when it works, that I still have to check.
Cheers

**Comment by cyanglaz** [comment] 2019-03-18 05:11
@diver2 Thank you for providing the reproduce steps. I'd really like to take a look at it. Do you mind create a separate issue (with all your detailed explanations here) to track this? Since this one is closed and it is hard for us to keep track of closed issues.

**Comment by diver2** [comment] 2019-03-19 10:03
@cyanglaz Done! #29594
