### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63

### ISSUE THREAD

**Issue by MohamedElMelige** [flutter/flutter#126001] opened 2023-05-03 19:06 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=59AE42A9-C0A4-4531-8F36-7CCE1D6B1768 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:449:14)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1423:15)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
```
```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-EG)
    • Flutter version 3.7.12 on channel stable at /Users/easaccair/Desktop/flutter sdk/flutter
    ! The flutter binary is not on your path. Consider adding /Users/easaccair/Desktop/flutter sdk/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/easaccair/Desktop/flutter sdk/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/easaccair/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/easaccair/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/easaccair/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 59AE42A9-C0A4-4531-8F36-7CCE1D6B1768 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
assets_audio_player-3.0.6
assets_audio_player_web-3.0.6
facebook_auth_desktop-0.0.9
firebase_auth-4.4.0
firebase_auth_web-5.3.0
firebase_core-2.9.0
firebase_core_web-2.3.0
firebase_database-10.1.0
firebase_database_web-0.2.2
flutter_facebook_auth-5.0.8
flutter_facebook_auth_web-4.1.1
flutter_secure_storage-8.0.0
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-3.0.0
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-2.0.0
google_sign_in-6.1.0
google_sign_in_android-6.1.9
google_sign_in_ios-5.6.1
google_sign_in_web-0.12.0
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.5
pay-1.1.0
pay_android-1.0.9
pay_ios-1.0.8
the_apple_sign_in-1.1.1
url_launcher-6.1.10
url_launcher_android-6.0.26
url_launcher_ios-6.1.4
url_launcher_linux-3.0.4
url_launcher_macos-3.0.4
url_launcher_web-2.0.16
url_launcher_windows-3.0.5

**Comment by danagbemava-nc** [comment] 2023-05-04 06:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80873.

Kindly subscribe to the issue above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-05-04 06:28 UTC
Labels: in triage
