### ISSUE TITLE
Material 3 NavigationBar "tap shadow" does not respect appbar height

### ISSUE THREAD

**Issue by guplem** [flutter/flutter#119231] opened 2023-01-26 12:24 UTC
## Steps to Reproduce

1. Clone the [M3 sample](https://flutter.github.io/samples/material_3.html)
2. Change the NavigationBar height, adding the parameter "height" to the widget
3. Interact with it
4. See how the shadow is not in the proper place (in this case with increased height):
![image](https://user-images.githubusercontent.com/11029629/214832935-0bbf5287-c498-4b85-9eab-f444db85d06b.png)

**Expected results:**
The shadow to be under the oval of the selected "screen". Like it is when using the default height.

**Actual results:**
The shadow seems to be always at the same distance from the top edge of the NavigationBar regardless of the widget height. 

<details>
<summary>Code sample</summary>

```dart
Scaffold(
  bottomNavigationBar: NavigationBar(
    height: Theme.of(context).navigationBarTheme.height ?? 80 * 1.75,
    selectedIndex: selectedIndex,
    onDestinationSelected: (int destNumber) {
      getProvider<AppProvider>(context, listen: false).setCurrentPageFromNavigationBar(context: context, newPage: destNumber);
    },
    destinations: [
      NavigationDestination(
        label: localizedText(context).navigationBarHomeLabel,
        icon: const Icon(Icons.home_outlined), // is there no home_outlined_rounded?
        selectedIcon: const Icon(Icons.home_rounded),
      ),
      NavigationDestination(
        label: localizedText(context).navigationBarWishlistLabel,
        icon: const Icon(Icons.favorite_border_rounded),
        selectedIcon: const Icon(Icons.favorite_rounded),
      ),
      NavigationDestination(
        label: localizedText(context).navigationBarCartLabel,
        icon: const Icon(Icons.shopping_cart_outlined), // is there no shopping_cart_outlined_rounded?
        selectedIcon: const Icon(Icons.shopping_cart_rounded),
      ),
      NavigationDestination(
        label: localizedText(context).navigationBarProfileLabel,
        icon: const Icon(Icons.person_outline_rounded),
        selectedIcon: const Icon(Icons.person_rounded),
      ),
    ],
  ),
  body: Builder(builder: (context) {
    switch (selectedIndex) {
      case 0:
        return const MainScreen(); // Any page 
      case 1:
        return const WishlistScreen(); // Any page
      case 2:
        return const CartScreen(); // Any page
      case 3:
        return const UserScreen(); // Any page
      default:
        return const MainScreen(); // Any page
    }
  }),
)
```

</details>

<details>
  <summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-150)
    • Flutter version 3.7.0 on channel stable at K:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\guple\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\guple\AppData\Local\Android\Sdk
PS K:\GitHub\TunzaaMarketplace\tunzaa_marketplace> flutter doctor -v
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-150)
    • Flutter version 3.7.0 on channel stable at K:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\guple\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\guple\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\guple\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)      
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version
      10.0.22621.1105]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.76
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.61        

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by exaby73** [comment] 2023-01-26 13:58
Hello @guplem. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by dJani97** [comment] 2023-01-26 16:10
@exaby73 the issue can be reproduced by visiting Flutter's [NavigationBar documentation](https://api.flutter.dev/flutter/material/NavigationBar-class.html) and adding `height: 50` or `height: 100` to `NavigationBar` in one of the examples.


<details><summary>Here is a complete, reproducible code sample obtained by the above method</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: NavigationExample());
  }
}

class NavigationExample extends StatefulWidget {
  const NavigationExample({super.key});

  @override
  State<NavigationExample> createState() => _NavigationExampleState();
}

class _NavigationExampleState extends State<NavigationExample> {
  int currentPageIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        height: 100,
        onDestinationSelected: (int index) {
          setState(() {
            currentPageIndex = index;
          });
        },
        selectedIndex: currentPageIndex,
        destinations: const <Widget>[
          NavigationDestination(
            icon: Icon(Icons.explore),
            label: 'Explore',
          ),
          NavigationDestination(
            icon: Icon(Icons.commute),
            label: 'Commute',
          ),
          NavigationDestination(
            selectedIcon: Icon(Icons.bookmark),
            icon: Icon(Icons.bookmark_border),
            label: 'Saved',
          ),
        ],
      ),
      body: <Widget>[
        Container(
          color: Colors.red,
          alignment: Alignment.center,
          child: const Text('Page 1'),
        ),
        Container(
          color: Colors.green,
          alignment: Alignment.center,
          child: const Text('Page 2'),
        ),
        Container(
          color: Colors.blue,
          alignment: Alignment.center,
          child: const Text('Page 3'),
        ),
      ][currentPageIndex],
    );
  }
}
```

</p>
</details>

**Comment by dJani97** [comment] 2023-01-26 16:16
@guplem in the meantime, you can work around this issue by wrapping the `NavigationBar` in a `Theme` widget and setting `splashColor` to be transparent. This will hide the splash.

```dart
Theme(
  data: Theme.of(context).copyWith(
    splashColor: Colors.transparent,
  ),
  child: NavigationBar ( ... ),
)
```

**Comment by exaby73** [comment] 2023-01-27 06:41
@guplem @dJani97 This issue seems to be fixed in the master channel. Since it's already fixed, I am closing this issue. Thank you

**Closed by exaby73** 2023-01-27 06:41 UTC
Labels: waiting for customer response, in triage
