### ISSUE TITLE
HTML file in WebViewController not loading as expected in iOS Simulator

### ISSUE THREAD

**Issue by kvernon93** [flutter/flutter#90018] opened 2021-09-13 23:59 UTC
Below the code loads several tweets in WebViews. This code works flawlessly in Android but produces a different result in iOS Simulator. No errors are produced in logs and nothing in flutter analyze pertain to this page and its classes.

## Code
Essentially I took the tweetwebview class and updated it to match current updated packages and tweaked to work with my code. The following is the tweetwebview class

```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:url_launcher/url_launcher.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TweetWebView extends StatefulWidget {
  final String tweetUrl;

  final String tweetID;

  TweetWebView({this.tweetUrl = '', this.tweetID = ''});

  TweetWebView.tweetID(String tweetID)
      : this.tweetID = tweetID,
        this.tweetUrl = '';
  TweetWebView.tweetUrl(String tweetUrl)
      : this.tweetUrl = tweetUrl,
        this.tweetID = '';

  @override
  _TweetWebViewState createState() => new _TweetWebViewState();
}

class _TweetWebViewState extends State<TweetWebView> {
  String _tweetHTML = '';
  String _filename = '';

  @override
  void initState() {
    super.initState();
    _requestTweet();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  final Completer<WebViewController> _controller =
  Completer<WebViewController>();

  _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    var child;
    //print(_tweetHTML);
    if (_tweetHTML != '' && _tweetHTML.length > 0) {
      final downloadUrl = Uri.file(_filename).toString();

      // Create the WebView to contian the tweet HTML
      final webView = WebView(
          initialUrl: downloadUrl,
          javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) async {
          // finally signal a complete() to the completer
          _controller.complete(webViewController);
        },
          navigationDelegate: (NavigationRequest request) {
          if (request.url.startsWith(downloadUrl)) {
              //print('allowing navigation to $request');
              return NavigationDecision.navigate;
            } else if (request.isForMainFrame) {
              //print('allowing navigation to $request');
              _launchURL(request.url);
              return NavigationDecision.prevent;
            } else {
              //print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
        },);

      // The WebView creates an exception: RenderAndroidView object was given an infinite size during layout.
      // To avoid that exception a max height constraint will be used. Hopefully soon the WebView will be able
      // to size itself so it will not have an infinite height.
      final box = LimitedBox(
        maxHeight: 500.0,
        child: webView,
      );

      child = box;
    } else {
      child = Text('Loading...');
    }

    return Container(child: child);
  }

  /// Download the embedded tweet.
  /// See Twitter docs: https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview
  void _requestTweet() async {
    String tweetUrl = widget.tweetUrl;
    String tweetID = '';

    if (tweetUrl == '' || tweetUrl.isEmpty) {
      if (widget.tweetID == '' || widget.tweetID.isEmpty) {
        throw new ArgumentError('Missing tweetUrl or tweetID property.');
      }
      tweetUrl = _formTweetURL(widget.tweetID);
      tweetID = widget.tweetID;
    }

    if (tweetID == '') {
      tweetID = _tweetIDFromUrl(tweetUrl);
    }

    // Example: https://publish.twitter.com/oembed?url=https://twitter.com/Interior/status/463440424141459456
    final downloadUrl = "https://publish.twitter.com/oembed?url=$tweetUrl";
    //print("TweetWebView._requestTweet: $downloadUrl");

    final jsonString = await _loadTweet(downloadUrl);
    final html = _parseTweet(jsonString);
    if (html != '') {
      final filename = await _saveTweetToFile(tweetID, html);
      setState(() {
        _tweetHTML = html;
        _filename = filename;
      });
    }
  }

  String _tweetIDFromUrl(String tweetUrl) {
    final uri = Uri.parse(tweetUrl);
    if (uri.pathSegments.length > 0) {
      return uri.pathSegments[uri.pathSegments.length - 1];
    }
    return '';
  }

  String _formTweetURL(String tweetID) {
    return "https://twitter.com/Interior/status/$tweetID";
  }

  Future<String> _saveTweetToFile(String tweetID, String html) async {
    Directory tempDir = await getTemporaryDirectory();
    String tempPath = tempDir.path;
    final filename = '$tempPath/tweet-$tweetID.html';
    File(filename).writeAsString(html);
    return filename;
  }

  String _parseTweet(String jsonString) {
    if (jsonString == '' || jsonString.isEmpty) {
      print('TweetWebView._parseTweet: empty jsonString');
      return '';
    }

    var item;
    try {
      item = json.decode(jsonString);
    } catch (e) {
      print(e);
      print('error parsing tweet json: $jsonString');
      return '<p>error loading tweet</p>';
    }

    final String html = item['html'];

    if (html == '' || html.isEmpty) {
      print('TweetWebView._parseTweet: empty html');
    }

    return html;
  }

  Future<String> _loadTweet(String tweetUrl) async {
    http.Response result = await _downloadTweet(tweetUrl);

    return result.body;
  }

  Future<http.Response> _downloadTweet(String tweetUrl) {
    return http.get(tweetUrl);
  }
}
```
Then I pass these tweets in a ListView, however, I use twitter API so forgive me but I've removed my bearer token.
```
import 'dart:convert';
import 'dart:async';
import 'dart:io';
import 'package:BWS_App/widgets/tweetwebview.dart';
import 'package:BWS_App/constants/Theme.dart';
import 'package:flutter/material.dart';
import 'package:BWS_App/widgets/navbar.dart';
import 'package:BWS_App/widgets/drawer.dart';
import 'package:http/http.dart' as http;

class Data {
  String id;
  String text;

  Data({required this.id, required this.text});

  factory Data.fromJson(Map<String, dynamic> json) {
    return Data(
        id: json['id'],
        text: json['text']
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['text'] = this.text;
    return data;
  }
}

class News extends StatefulWidget {
  News({Key? key}) : super(key: key);

  @override
  _NewsState createState() => _NewsState();
}

class _NewsState extends State<News> {
 //late Future<List<dynamic>> futureTweets;


  @override
  void initState() {
    super.initState();
    //fetchTweets();
    //futureTweets = fetchTweets();
    //print(tweets);
  }

 Future<List<dynamic>> fetchTweets() async {
   List<dynamic> tweets = [];

   var request = await http.get(Uri.parse(
       'https://api.twitter.com/2/users/1084940577848860673/tweets'), //tweets from company page 
   headers: {
     HttpHeaders.authorizationHeader: 'Bearer token goes here',
     HttpHeaders.cookieHeader: 'guest_id=guest id; personalization_id="personal id"'
   });

   if (request.statusCode == 200) {
     tweets.add(json.decode(request.body));
     return tweets;
   } else {
     return json.decode(request.reasonPhrase!);
   }

 }

 String _getTweet(dynamic account) {
   if(account == []){
     return 'No Data';
   }else{
     return account['id'].toString();
   }
 }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: Navbar(
          title: "News and Updates",
          searchBar: false,
          rightOptions: false,
        ),
        backgroundColor: NowUIColors.bgColorScreen,
        drawer: NowDrawer(currentPage: "News and Updates"),
        body: SingleChildScrollView(
            padding: EdgeInsets.all(10),
            child: FutureBuilder<List<dynamic>>(
                future: fetchTweets(),
                builder: (context, snapshot)  {
                  if (snapshot.connectionState == ConnectionState.done) {
                    if (snapshot.hasData) {
                      if(snapshot.data != null){
                        return ListView.builder(
                            scrollDirection: Axis.vertical,
                            shrinkWrap: true,
                            physics: ClampingScrollPhysics(),
                            padding: EdgeInsets.all(8),
                            itemCount: snapshot.data![0]['data'].length,
                            itemBuilder: (BuildContext context, int index) {
                              return Card(
                                  child: TweetWebView.tweetID(_getTweet(snapshot.data![0]['data'][index])),
                              );/*Card(
                                child: SingleChildScrollView(
                                  child: Column(
                                    children: <Widget>[
                                      *//*ListTile(
                                          leading: CircleAvatar(
                                              radius: 30,
                                              backgroundColor: NowUIColors.white,
                                              backgroundImage: AssetImage(
                                                  'assets/images/logo_bigger_canvas.png')),
                                          title: ,
                                      )*//*
                                      TweetWebView.tweetID(_getTweet(snapshot.data![0]['data'][index])),
                                    ],
                                  ),
                                ),
                              );*/
                            });
                      } else{
                        return Text("Is null");
                      }
                    } else {
                      return Text('No data found');
                    }
                  } else {
                    return Center(child: CircularProgressIndicator());
                  }
                })));
  }
}
```
Info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>BWS_App</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
    <key>LSApplicationQueriesSchemes</key>
          <array>
            <string>https</string>
            <string>http</string>
          </array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSLocationWhenInUseUsageDescription</key>
    <key>io.flutter.embedded_views_preview</key>
    <true/>
</dict>
</plist>
```

**Expected results:** 
As you can see this works in Android:
<img width="396" alt="Screen Shot 2021-09-13 at 6 25 58 PM" src="https://user-images.githubusercontent.com/75630330/133174156-16ce46c0-d718-4cc3-98ba-26c8305bc877.png">

**Actual results:** 
However on iOS: 
<img width="380" alt="Screen Shot 2021-09-13 at 6 11 50 PM" src="https://user-images.githubusercontent.com/75630330/133173233-4b68524b-a686-42e5-a07d-6ab3f8650812.png">

```
```

```
```

 `flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/michaelacevedo/Developer/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/michaelacevedo/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • B5AE1D2C-6C54-42FC-929D-8AF57779C6E9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by kvernon93** [comment] 2021-09-14 00:48
Forgot to mention this is in my info.plist: 
```
<key>io.flutter.embedded_views_preview</key>
    <true/>
```

**Comment by darshankawar** [comment] 2021-09-14 10:34
@kvernon93 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy and run to verify this issue.
Thanks.

**Comment by darshankawar** [comment] 2021-09-15 05:38
@kvernon93 
Thanks for the update. Still it seems to be a lot of code to process and identify where the issue could be. Can you try to isolate the issue with minimal code that contains HTML file and WebViewController ?

**Comment by kvernon93** [comment] 2021-09-15 15:19
Ok so the main issue is here:
```
@override
  Widget build(BuildContext context) {
    var child;
    //print(_tweetHTML);
    if (_tweetHTML != '' && _tweetHTML.length > 0) {
      final downloadUrl = Uri.file(_filename).toString();

      // Create the WebView to contian the tweet HTML
      final webView = WebView(
          initialUrl: downloadUrl,
          javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) async {
          // finally signal a complete() to the completer
          _controller.complete(webViewController);
        },
          navigationDelegate: (NavigationRequest request) {
          if (request.url.startsWith(downloadUrl)) {
              //print('allowing navigation to $request');
              return NavigationDecision.navigate;
            } else if (request.isForMainFrame) {
              //print('allowing navigation to $request');
              _launchURL(request.url);
              return NavigationDecision.prevent;
            } else {
              //print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
        },);
```
final downloadUrl = Uri.file(_filename).toString(); which is what is passed to the WebView Controller, returns something like this: 

> file:///data/user/0/com.example.BWS_App/cache/tweet-1437153242656428034.html

As far as I understand, this uses the API to download to tweet as an html file. In Android this loads fine but on iOS it only loads as text, as I've displayed in my OP.

In the class. If say I take the downloadUrl and put in a regular link like say downloadUrl = 'https://www.google.com/' it loads the google page in the WebView perfectly. If I use the tweetUrl which would return something like 'https://twitter.com/BelizeWater/status/1437403053875945477' it opens the tweets in an external browser on the phone.

So what I want is that iOS loads the file in the same way as Android.

**Comment by darshankawar** [comment] 2021-09-16 05:51
@kvernon93 
Thanks for the details. I created a self-contained core sample code to replicate this behavior as below:

<details>
<summary>code sample</summary>



```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MaterialApp(
    home: HelpScreen(),
  ));
}


class HelpScreen extends StatefulWidget {
  @override
  HelpScreenState createState() {
    return HelpScreenState();
  }
}

class HelpScreenState extends State<HelpScreen> {
  late WebViewController _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Help')),
      body: WebView(
        initialUrl: 'about:blank',
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
          _loadHtmlFromAssets();
        },
      ),
    );
  }

  _loadHtmlFromAssets() async {
    String fileText = await rootBundle.loadString('assets/sample.html');
    _controller.loadUrl( Uri.dataFromString(
        fileText,
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8')
    ).toString());
  }
}

```


</details>

I used a sample HTML file from here and added into assets : https://filesamples.com/formats/html. Ran the code using latest stable (2.5.0) on iOS simulator which rendered as below:

<img width="379" alt="Screenshot 2021-09-16 at 11 20 00 AM" src="https://user-images.githubusercontent.com/67046386/133556878-dc5cf246-35b3-4b5a-aa52-02e2439cee5e.png">

Can you check this at your end and see if it interprets your issue ?

**Comment by kvernon93** [comment] 2021-09-17 16:22
Hey sorry for the late reply had an issue to resolve at work.
So here I replicated your code in my code like so (in my IDE I commented out all the code that didn't match up to ur own except the class constructor):
```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TweetWebView extends StatefulWidget {
  final String tweetUrl;

  final String tweetID;

  TweetWebView({this.tweetUrl = '', this.tweetID = ''});

  TweetWebView.tweetID(String tweetID)
      : this.tweetID = tweetID,
        this.tweetUrl = '';
  TweetWebView.tweetUrl(String tweetUrl)
      : this.tweetUrl = tweetUrl,
        this.tweetID = '';

  @override
  _TweetWebViewState createState() => new _TweetWebViewState();
}

class _TweetWebViewState extends State<TweetWebView> {
  String _tweetHTML = '';
  String _filename = '';
  String tweetUrl = '';
  late WebViewController _controller;

  @override
  void initState() {
    super.initState();
    //_requestTweet();
    //if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

_loadHtmlFromAssets(String downloadUrl) async {
    String fileText = await rootBundle.loadString(downloadUrl);
    _controller.loadUrl( Uri.dataFromString(
        fileText,
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8')
    ).toString());
  }

  @override
  Widget build(BuildContext context) {
    var child;
      final downloadUrl = 'assets/sample2.html';

      final webView = WebView(
          initialUrl: 'about:blank',//downloadUrl,
          javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) async {
          _controller = webViewController;

          _loadHtmlFromAssets(downloadUrl);
        },);

      final box = LimitedBox(
        maxHeight: 500.0,
        child: webView,
      );

      child = box;

    return Container(child: child);
  }
```
This class is called like so:
```
return Card(
    child: TweetWebView.tweetID(_getTweet(snapshot.data![0]['data'][index])),
);
```
And I get this error:

> [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: assets/sample2.html
>#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
><asynchronous suspension>
>#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:27)
><asynchronous suspension>
>#2      _TweetWebViewState._loadHtmlFromAssets (package:BWS_App/widgets/tweetwebview.dart:53:23)
><asynchronous suspension>

**Comment by darshankawar** [comment] 2021-09-20 06:14
@kvernon93 
Ran your entire code sample on latest stable and worked for me as below:

<img width="376" alt="Screenshot 2021-09-20 at 11 41 03 AM" src="https://user-images.githubusercontent.com/67046386/133962598-e3822c47-f02e-4187-b6fc-9450d3413ed2.png">




> Unable to load asset: assets/sample2.html

Maybe the filename in your assets and pubspec is different. I use `sample.html`

**Comment by kvernon93** [comment] 2021-09-20 14:25
Ahh yes I forgot to include in pubspec. So this now works, however when I load the tweets they are not loaded from assets, they are dynamically loaded because my program grabs the last 10 tweets in the timeline which can change at any hour. Maybe there's a way I can load them in the assets folder and keep overwriting them?

**Comment by kvernon93** [comment] 2021-09-21 03:19
Bit of an update, so I reverted back to my original code and removed the navigationDelegate completely and now the tweets are loading like this:
<img width="376" alt="Screen Shot 2021-09-20 at 9 15 38 PM" src="https://user-images.githubusercontent.com/75630330/134106350-07431940-f2a3-43cd-be3b-a5513aa0a108.png">

This is done by changing my code back to this (not the commented out navigation delegate):
```
 @override
  Widget build(BuildContext context) {
    var child;
    if (_tweetHTML != '' && _tweetHTML.length > 0) {
      final downloadUrl = Uri.file(_filename).toString();

      // Create the WebView to contian the tweet HTML
      final webView = WebView(
          initialUrl: downloadUrl,
          javascriptMode: JavascriptMode.unrestricted,

          /*navigationDelegate: (NavigationRequest request) {
            if (request.url.startsWith(downloadUrl)) {
              print('1 allowing navigation to $request');
              return NavigationDecision.navigate;
            } else if (request.isForMainFrame) {
              print('2 allowing navigation to $request');
              _launchURL(request.url);
              return NavigationDecision.prevent;
            } else {
              print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
          }*/);

      // The WebView creates an exception: RenderAndroidView object was given an infinite size during layout.
      // To avoid that exception a max height constraint will be used. Hopefully soon the WebView will be able
      // to size itself so it will not have an infinite height.
      final box = LimitedBox(
        maxHeight: 500.0,
        child: webView,
      );

      child = box;
    } else {
      child = Text('Loading...');
    }

    return Container(child: child);
  }
```
So now this brings up 2 new problems, firstly the tweet loads all the way in the corner of the WebViews, you can see in my OP how I expect it to load as it does on Android. Second, the purpose of the navigationDelegate was so that if the use clicks a link within the WebViews I wanted it to load in a browser. I'm open to suggestions :D

**Comment by darshankawar** [comment] 2021-09-21 05:49
@kvernon93 
Thanks for digging in. I think NavigationDelegate.navigate seems to be blocking the Js redirects and hence you may be seeing the issue. If this is correct, there's a similar open issue describing the same case, https://github.com/flutter/flutter/issues/75808

You may follow-up in it for further updates.

Also, I think since your original issue seems to have been resolved for now without using NavigationDelegate, can this issue be closed ?

**Comment by kvernon93** [comment] 2021-09-22 16:14
Ok I'll try responding there and see, thank you!

**Comment by darshankawar** [comment] 2021-09-23 05:35
Thanks. I am going ahead and closing this as resolved / duplicate.

**Closed by darshankawar** 2021-09-23 05:35 UTC
Labels: in triage
