### ISSUE TITLE
Flutter Gallery app has visual artifacts when running on Pixel 5

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#111551] opened 2022-09-14 12:08 UTC
## Steps to Reproduce

1. Execute `flutter run --profile` of [Flutter Gallery](https://github.com/flutter/gallery) on Pixel 5 (Android 12)
2. Navigate through the Categories as shown on the video
3. Observe parts of the screen not redrawing when state changes; It's not possible to take a screenshot or screen recording as it actually redraws the screen correctly when trying to do so

**Expected results:** 

There should be no visual glitches/ghosting/artifacts

**Actual results:** 

Parts of the screen don't get redrawn. This happens on Pixel 5 but looks fine on Samsung S21.

We have very similar issue in our production application and were able to reproduce the same issue on Flutter Gallery app.

https://user-images.githubusercontent.com/16854239/190148702-1150d877-b620-40a6-9a57-fc76320afece.mp4

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
Running "flutter pub get" in gallery...                          1 332ms
Launching lib/main.dart on Pixel 5 in profile mode...
Running Gradle task 'assembleProfile'...                        
Shrinking has been disabled for this build due to deferred components. Shrinking is not available for multi-apk applications. This limitation is expected to be removed when Gradle plugin 4.2+ is available in Flutter.
Running Gradle task 'assembleProfile'...                           96,2s
✓  Built build/app/outputs/flutter-apk/app-profile.apk (131.9MB).
Installing build/app/outputs/flutter-apk/app.apk...                 7,5s
W/FlutterActivityAndFragmentDelegate(22576): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Pixel 5 is available at: http://127.0.0.1:53739/iUEF595Q-kE=/
The Flutter DevTools debugger and profiler on Pixel 5 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:53739/iUEF595Q-kE=/
```

```
Analyzing gallery...                                            
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale pl-PL)
    • Flutter version 3.3.1 on channel stable at /Users/dominik/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (7 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Pixel 5 (mobile)        • 08261FDD4001UE            • android-arm64  • Android 12 (API 32)
    • iPhone 12 mini (mobile) • 00008101-0001510C3CF0001E • ios            • iOS 16.0 20A362
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2022-09-15 05:09
Hi @orestesgaolin, thanks for filing the issue.
But I can not reproduce the issue on the latest `stable` and `master` channels (please see in the demo video) with `profile` mode.

I tested on my devices as below:
- Pixel 3a, Android 12
- Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225

<details>
<summary>Demo</summary>

| Pixel 3a | Samsung Galaxy Tab A7 Lite
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/190319314-b618f27c-843e-4516-9257-c8e6c91f3c98.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/190319323-27c0a01c-32bf-4087-98da-c5f73eb5e77a.mp4"/> |

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 hours ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.270, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.270 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c4c1b0b0b7 (41 minutes ago), 2022-09-14 21:22:29 -0400
    • Engine revision 3a49977f8b
    • Dart version 2.19.0 (build 2.19.0-199.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Could you please retry the issue on the latest Flutter `stable` and `master` channels to see if this issue still reproduces?
The latest Flutter stable is `3.3.2` and the master is `3.4.0-19.0.pre.270`.

**Comment by orestesgaolin** [comment] 2022-09-15 07:56
Thanks for looking at the issue. I just run the app using Flutter 3.3.2 and the issue is still there, see the video:


https://user-images.githubusercontent.com/16854239/190347108-9e930c41-b73d-48de-8597-dbecbe42f9bb.mp4



Logs:
```
Running "flutter pub get" in gallery...                          1 764ms
Launching lib/main.dart on Pixel 5 in profile mode...
Running Gradle task 'assembleProfile'...                        
Shrinking has been disabled for this build due to deferred components. Shrinking is not available for multi-apk applications. This limitation is expected to be removed when Gradle plugin 4.2+ is available in Flutter.
Running Gradle task 'assembleProfile'...                          108,2s
✓  Built build/app/outputs/flutter-apk/app-profile.apk (131.9MB).
Installing build/app/outputs/flutter-apk/app.apk...                 7,3s
W/FlutterActivityAndFragmentDelegate(25197): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Pixel 5 is available at: http://127.0.0.1:50557/ReWXu33hakw=/
The Flutter DevTools debugger and profiler on Pixel 5 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:50557/ReWXu33hakw=/
Lost connection to device.
```

I also run it on master, and this looks similar:


https://user-images.githubusercontent.com/16854239/190348183-a3ef7c58-e45f-41a6-9ca6-51e7501c9b6e.mp4

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-19.0.pre.273, on macOS 12.6 21G115 darwin-arm64, locale pl-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by huycozy** [comment] 2022-09-15 09:13
@orestesgaolin Thank you for the update. Labeling this issue for further investigation from the team.
/cc @guidezpl for thoughts.

**Comment by guidezpl** [comment] 2022-09-15 09:46
Curious bug, though I notice we're not properly animating the closing of the categories, so that should probably be fixed first.

The other issue with the images is known https://github.com/flutter/gallery/issues/755.

**Comment by iapicca** [comment] 2022-09-20 07:53
any chance that those are the same issue?
https://github.com/flutter/flutter/issues/110885
https://github.com/flutter/flutter/issues/111376
https://github.com/flutter/flutter/issues/111867

**Comment by GaryQian** [comment] 2022-09-20 17:31
@chinmaygarde Any insight into why this would happen on such a specific device?

**Comment by chinmaygarde** [comment] 2022-09-20 19:58
cc @flar @iskakaushik Could this be related to dirty region management? IIRC, there was flag to turn it off. We could test without the feature enabled to see if this is related.

**Comment by TatsuUkraine** [comment] 2022-09-21 08:14
@GaryQian there's another issue, very similar to current one, I was able to reproduce it on pixel 4 as well

**Comment by TatsuUkraine** [comment] 2022-10-05 18:19
@orestesgaolin could you try 3.3.4, I had similar glitches in our app, but after update I don't see them anymore

**Comment by TatsuUkraine** [comment] 2022-10-05 18:20
Or I may just didn't reproduce them yet after update)

**Comment by AleXoTroN** [comment] 2022-10-06 22:38
Happens on my pixel 5 too, even with published release versions.

**Comment by PieterAelse** [comment] 2022-11-03 12:27
I ran into this issue on my Pixel 5 with our app, it was sometimes not re-drawing certain parts of the screen (/items) and whenever I touched those or used a screenrecording or f.e. changed the volume they would magically disappear. I was on Flutter version 3.2.2.

I just updated to Flutter 3.3.7 and could not reproduce the glitches/artifacts anymore on my Pixel 5 👍 

(would be good is somebody else would confirm, or the Flutter team, before closing this issue)

**Comment by flar** [comment] 2022-11-03 21:40
Did anyone bisect the origin and solution of the problem so that we can double check that this was fixed intentionally?

(perhaps not explicitly for these problems, but that it was an actual bug being fixed as opposed to a change that accidentally/unintentionally avoids the condition that causes the bug).

**Comment by guidezpl** [comment] 2023-02-13 14:09
Is this still reproducible with flutter/gallery @ HEAD?

**Comment by guidezpl** [comment] 2023-02-22 11:00
2.10.0 is starting to roll out to the [Play Store](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en&gl=US). Based on comments, I'll close this issue, but please comment if this reoccurs.

**Closed by guidezpl** 2023-02-22 11:00 UTC
Labels: e: device-specific, platform-android, gallery, severe: rendering, P4
