### ISSUE TITLE
Window's alwaysUse24HourFormat not updates when settings change on iOS

### ISSUE THREAD

**Issue by johngithubby** [flutter/flutter#58040] opened 2020-05-26 21:28 UTC
Steps to reproduce:

1) Go to device settings, general, date & time and note the "24-Hour Time" setting

2) Run MediaQueryData.fromWindow(WidgetsBinding.instance.window).alwaysUse24HourFormat, the value should be correct. Don't kill the app.

3) Go again to device settings, general, date & time and switch the "24-Hour Time" setting

4) Switch back to your Flutter app

5) Run again MediaQueryData.fromWindow(WidgetsBinding.instance.window).alwaysUse24HourFormat, the value is incorrect, unchanged.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.14.6 18G4032, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.45.1)
• No issues found!

**Comment by TahaTesser** [comment] 2020-05-27 09:37
Hi @johngithubby 
You need to restart to the app,  it works fine  `beta` and `dev` channel

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final value = MediaQueryData.fromWindow(WidgetsBinding.instance.window)
        .alwaysUse24HourFormat;

    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              Text(
                'MediaQueryData.fromWindow(WidgetsBinding.instance.window).alwaysUse24HourFormat',
                textAlign: TextAlign.center,
              ),
              Text(value.toString()),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

![flutter_01](https://user-images.githubusercontent.com/48603081/83003284-b9d4f280-a02b-11ea-95d7-81654bee310d.png)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by johngithubby** [comment] 2020-05-27 13:42
That is unacceptable of course, you mean I should ask our users to restart our app in order to have the correct information?

**Comment by goderbauer** [comment] 2020-08-04 20:52
Duplicate of https://github.com/flutter/flutter/issues/13703.

**Closed by goderbauer** 2020-08-04 20:52 UTC
Labels: a: quality, engine, found in release: 1.19, has reproducible steps, platform-ios
