### ISSUE TITLE
microbenchmarks rrect_contains_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54848] opened 2020-04-15 15:11 UTC
Looks like it started with this roll https://github.com/flutter/flutter/pull/54513.

<img width="249" alt="Screen Shot 2020-04-15 at 8 11 08 AM" src="https://user-images.githubusercontent.com/1435716/79354057-c0cafa00-7ef0-11ea-9184-d74e1fc1ae66.png">

**Comment by mehmetf** [comment] 2020-04-15 16:04
@liyuqian could you take a look?

**Comment by jason-simmons** [comment] 2020-04-15 21:47
Looking at this now

**Comment by liyuqian** [comment] 2020-04-15 22:02
I think the regression is in Dart roll [d6c1398a][1]

Here's the 5 benchmark runs I get before and after [d6c1398a][1] (using `flutter run -d M --release --local-engine=android_release lib/geometry/rrect_contains_bench.dart`)

|  2d19576f| d6c1398a |
| --- | --- |
|  1.6331 | 2.2955 |
|  1.4483 | 1.3639 |
|  1.5344 | 1.7812 |
|  1.0468 | 1.0246 |
|  1.1251 | 1.9925 |

CC @a-siva 

[1]: https://github.com/flutter/engine/commit/d6c1398a3f06afe7fd9c0a68587b7d88ec84df39

**Comment by a-siva** [comment] 2020-04-15 22:25
The relevant VM cls in that range are
[https://github.com/dart-lang/sdk/commit/485c4f9364419d093d1c6a6c504823c4cf643183](https://github.com/dart-lang/sdk/commit/485c4f9364419d093d1c6a6c504823c4cf643183)
[https://github.com/dart-lang/sdk/commit/4978dcc9283cf3e7b284cfe331837029ea66383b](https://github.com/dart-lang/sdk/commit/4978dcc9283cf3e7b284cfe331837029ea66383b)
[https://github.com/dart-lang/sdk/commit/9b1205496ac8b87df531b0f08f60edf947917789](https://github.com/dart-lang/sdk/commit/9b1205496ac8b87df531b0f08f60edf947917789)
[https://github.com/dart-lang/sdk/commit/bbbabcdacd60c50bcc63b4263236483e75609d1c](https://github.com/dart-lang/sdk/commit/bbbabcdacd60c50bcc63b4263236483e75609d1c)

//cc @mkustermann @rmacnak-google @alexmarkov

**Comment by jason-simmons** [comment] 2020-04-15 22:56
Did some bisecting within that Dart roll, and the change appears to have started with https://github.com/dart-lang/sdk/commit/4978dcc9283cf3e7b284cfe331837029ea66383b.

This is similar to another GC scheduling change that affected this microbenchmark a few weeks ago (https://github.com/flutter/flutter/issues/52473).

**Comment by mehmetf** [comment] 2020-04-16 15:16
Do you guys think this is a release blocking TODAY issue? We have not been able to publish a dev release in a week.

**Comment by liyuqian** [comment] 2020-04-16 21:31
Since https://github.com/flutter/flutter/issues/52473 was closed by @rmacnak-google , I'll defer the decision to him.

**Comment by tvolkert** [comment] 2020-04-20 17:10
ping.  This is labeled TODAY and is blocking dev releases.

**Comment by a-siva** [comment] 2020-04-20 17:27
I would not consider this a release blocking issue, the benchmark is a micro benchmark which is sensitive to when a GC is triggered and the feature (parallel scavenge) that landed in https://github.com/dart-lang/sdk/commit/4978dcc9283cf3e7b284cfe331837029ea66383b changed that bit triggering the regression.

**Comment by tvolkert** [comment] 2020-04-20 17:32
Who's driving this?  We either need to re-baseline the benchmark or revert the commit - otherwise this regression will just get filed as another TODAY bug...

**Comment by liyuqian** [comment] 2020-04-20 17:34
@a-siva : is there anyone in the Dart team going to work on this? If not, I'll just rebaseline the benchmark and close this bug.

**Comment by liyuqian** [comment] 2020-04-20 18:00
Rebaselined and closing this issue according to the offline discussion with @rmacnak-google

**Closed by liyuqian** 2020-04-20 18:00 UTC
Labels: engine, perf: speed, severe: performance, severe: regression, team: benchmark
