### ISSUE TITLE
Framework features to allow apps to record/replay their state in case the OS restarts them

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7560] opened 2017-01-20 16:43 UTC
This is expected behavior of the platform, that Android will kill your background app at any time.

However the Flutter framework doesn't yet have a way to automatically resume at the correct route, etc when the app is resumed to make it appear as though it wasn't restarted.

I suspect we have an existing bug for this on file, but a short search didn't find it.  This is also bug 34098075 internally and affects customer: leafy.

**Comment by mehmetf** [comment] 2017-01-20 17:39
While it would be great to restore the app state when it is destroyed by Android, this is a very low priority bug.

To my knowledge, this might be impossible because Android actually does not (have to) call onDestroy() before destroying the activity. It might simply kill the process. On native apps, the behavior is the same. The app will look like it has restarted.

**Comment by Hixie** [comment] 2017-01-20 23:42
We should enable apps to store their current state whenever it changes meaningfully, so that they can easily come back up in the same state.

**Comment by franklinharper** [comment] 2017-01-22 18:12
@mehmetf is technically correct about onDestroy().

But the correct solution is to persist significant state changes when they happen, not just before the app is destroyed. That's what well written Android apps do.

**Comment by mehmetf** [comment] 2017-01-22 22:25
I believe this issue is becoming quite vague.

@franklinharper, we can already save relevant state in our app (such as the selected tab in shared preferences) whenever we want. You are right that apps with good UX should do this. This issue, though is about what Flutter, as a framework, can do to help with this. The only thing I can think of is to expose additional OS lifecycle methods like _onSaveInstanceState_. This request then becomes similar to #7561. 

@Hixie I am actually not sure if more can (or should) be done at framework level. I would not want Flutter to save the route and then attempt to go there when the app restarts. In an ideal world, all apps should be able to start from all of their activities or routes but in reality that rarely works because of data dependencies or expected user input or whatever reason. It would end up complicating things and causing hard to trace bugs.

**Comment by Hixie** [comment] 2017-01-22 22:41
Yeah I don't think we'd want to force this automatically on all apps.

**Comment by ScottPierce** [comment] 2017-01-23 16:33
The instance where Android saves the current app state, and then reinitializes the app to it's previous state, even after it's been purged from memory, isn't done via `onDestroy`. It's done via [onSaveInstanceState](https://developer.android.com/reference/android/app/Activity.html#onSaveInstanceState(android.os.Bundle)).

The data isn't persisted by the app, but rather, serialized to a [Parcelable](https://developer.android.com/reference/android/os/Parcelable.html). The app can then be killed from memory by the OS, and then when it opens again, the parceled data is provided to the application again via the `Bundle` in `Activity.onCreate`. The system will parcel a lot of information, i.e. backstack, and the call to `onSaveInstanceState` allows the developer to also parcel important data for that screen.

The data isn't always restored. At some point if the user hasn't opened the app (or under some other conditions), the parceled data is discarded, and thus the next time the app is opened it's previous state isn't restored.

**Comment by Hixie** [comment] 2017-02-14 18:56
Ok here's what I've learnt:

iOS has shouldSaveApplicationState / shouldRestoreApplicationState.
Android has onSaveInstanceState / onRestoreInstanceState.

It's not clear to me when shouldRestoreApplicationState and onRestoreInstanceState are invoked relative to when the Dart VM starts up. Is it predictable?

**Comment by Hixie** [comment] 2017-02-14 22:49
Based on discussions, I think the way to go is to have a field on `ui.window` which is populated with the restore data from the system before we call `void main`, and to allow dart code to write to this field, with the written data being the data sent to the system when the system asks us to save (or more proactively, on platforms that don't reliably ask us to save).

The format of this data should be whatever is most convenient for the engine (e.g. a byte array, or a JSON-encoded string, or a string-string Map, or whatever).

Once that's in place we can start hooking things up on the framework side, though I suspect by and large we won't hook much up, it'll be up to developers (which seems to be what @mehmetf wants anyway).

**Comment by mehmetf** [comment] 2017-02-15 01:14
SGTM

**Comment by sethladd** [comment] 2017-11-08 19:27
Is this a dupe of https://github.com/flutter/flutter/issues/6827 ?

**Comment by sethladd** [comment] 2017-11-08 20:08
Closing this in favor of #6827 (de-duping)

Please let me know if we want both of these issues open.

**Closed by sethladd** 2017-11-08 20:08 UTC
Labels: customer: leafy (g3), prod: framework
