### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5540 pos 12: '_children.contains(child)': is not true.

### ISSUE THREAD

**Issue by colemars** [flutter/flutter#47558] opened 2019-12-20 23:22 UTC
## Steps to Reproduce

1. I'm running `flutter run` on a repo that was working fine prior to latest flutter update.
2. Latest Xcode
3. New Build System

My googles can't find anything on this error but downgrading back to 1.9.1 fixes the issue.

**Target Platform:** iOS
**Target OS version/browser:** iOS 13.3
**Devices:** Simulator & Physical device

## Logs

```
2019-12-20 15:18:12.401779-0800 Runner[39541:400491] flutter: didComplete: /splash
2019-12-20 15:18:12.410839-0800 Runner[39541:400491] flutter: Remote config app version = "1.0.0"; package version = 1.0.0
2019-12-20 15:18:12.427134-0800 Runner[39541:400491] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4701 pos 14: '_dependents.isEmpty': is not true.
2019-12-20 15:18:12.439222-0800 Runner[39541:400511] 6.14.0 - [Firebase/RemoteConfig][I-RCN000069] Most recently fetched config is already activated.
2019-12-20 15:18:12.440042-0800 Runner[39541:400491] flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
2019-12-20 15:18:12.731443-0800 Runner[39541:400491] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5540 pos 12: '_children.contains(child)': is not true.
2019-12-20 15:18:12.736383-0800 Runner[39541:400491] flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

```
```

```
Downloading android-arm-profile/darwin-x64 tools...                 0.5s
Downloading android-arm-release/darwin-x64 tools...                 0.3s
Downloading android-arm64-profile/darwin-x64 tools...               0.3s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
Downloading android-x64-profile/darwin-x64 tools...                 0.3s
Downloading android-x64-release/darwin-x64 tools...                 0.3s
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/colemarsteller/Development/flutter
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/colemarsteller/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • A6503E01-8102-4110-B6F8-C509C01F866E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

! Doctor found issues in 1 category.
```

After running 
`flutter clean`
`flutter pub cache repair`

new output is:

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
    [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note:
    insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable 
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note:
    insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull 
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33:
    warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
    [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note:
    insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note:
    insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    /Users/colemarsteller/.pub-cache/git/music-player-0e79a28b8d5a448b89ddfb97842dbe927b400d68/ios/Classes/SwiftMusic
    PlayerPlugin.swift:250:65: warning: 'init(image:)' was deprecated in iOS 10.0: Use
    -initWithBoundsSize:requestHandler:
          songInfo[MPMediaItemPropertyArtwork] = MPMediaItemArtwork.init(image: image!)
                                                                    ^
    /Users/colemarsteller/.pub-cache/git/music-player-0e79a28b8d5a448b89ddfb97842dbe927b400d68/ios/Classes/SwiftMusic
    PlayerPlugin.swift:310:5: warning: switch covers known cases, but 'AVPlayer.TimeControlStatus' may have
    additional unknown values, possibly added in future versions
        switch (status) {
        ^
    /Users/colemarsteller/.pub-cache/git/music-player-0e79a28b8d5a448b89ddfb97842dbe927b400d68/ios/Classes/SwiftMusic
    PlayerPlugin.swift:310:5: note: handle unknown values using "@unknown default"
        switch (status) {
        ^
    /Users/colemarsteller/.pub-cache/git/music-player-0e79a28b8d5a448b89ddfb97842dbe927b400d68/ios/Classes/SwiftMusic
    PlayerPlugin.swift:364:5: warning: switch covers known cases, but 'AVPlayerItem.Status' may have additional
    unknown values, possibly added in future versions
        switch status {
        ^
    /Users/colemarsteller/.pub-cache/git/music-player-0e79a28b8d5a448b89ddfb97842dbe927b400d68/ios/Classes/SwiftMusic
    PlayerPlugin.swift:364:5: note: handle unknown values using "@unknown default"
        switch status {
        ^
    /Users/colemarsteller/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.0+1/ios/Classes/FirebaseDynam
    icLinksPlugin.m:6:9: fatal error: 'UserAgent.h' file not found
    #import "UserAgent.h"
            ^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```
To solve the above I had to run:
```
pod deintegrate
pod install
```
And now my output is back to the original log output:
```
2019-12-20 15:18:12.401779-0800 Runner[39541:400491] flutter: didComplete: /splash
2019-12-20 15:18:12.410839-0800 Runner[39541:400491] flutter: Remote config app version = "1.0.0"; package version = 1.0.0
2019-12-20 15:18:12.427134-0800 Runner[39541:400491] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4701 pos 14: '_dependents.isEmpty': is not true.
2019-12-20 15:18:12.439222-0800 Runner[39541:400511] 6.14.0 - [Firebase/RemoteConfig][I-RCN000069] Most recently fetched config is already activated.
2019-12-20 15:18:12.440042-0800 Runner[39541:400491] flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
2019-12-20 15:18:12.731443-0800 Runner[39541:400491] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5540 pos 12: '_children.contains(child)': is not true.
2019-12-20 15:18:12.736383-0800 Runner[39541:400491] flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

**Comment by colemars** [comment] 2019-12-21 22:49
Downgrading to v1.9.1 for now

**Comment by iapicca** [comment] 2019-12-22 11:15
Hi @colemars 
the errors seem to be caused by a 3rd party plugin [uni_links](https://pub.dev/packages/uni_links)
you may want to open an issue on the dedicated [github](https://github.com/avioli/uni_links/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-12-22 11:15 UTC

**Comment by piyushchauhan** [comment] 2020-05-08 20:30
I get this error when scroll through my list.view little bit rapidly. Is it a rendering issue from the framework? @iapicca

**Comment by iapicca** [comment] 2020-05-13 11:31
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
