### ISSUE TITLE
Widgets inserted to an Overlay have different ancestral InheritedWidget(s) than commonly expected

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#36220] opened 2019-07-15 22:54 UTC
This seems to be a very common source of bugs when using the Hero API:
- #213
- https://github.com/flutter/flutter/issues/34119
- https://github.com/flutter/flutter/issues/30647
- https://github.com/flutter/flutter/issues/12463

and in the framework: 
- https://github.com/flutter/flutter/issues/34640
- https://github.com/flutter/flutter/issues/35555 (not really in the same category but somewhat related)

### Workaround

As a temporary workaround, manually wrap whatever is missing inside the hero, or in its `shuttleBuilder`.
See: https://github.com/flutter/flutter/issues/30647#issuecomment-480980280

additional context: 
https://github.com/flutter/flutter/pull/6072#issuecomment-250267796

**Comment by esDotDev** [comment] 2019-10-20 15:52
I've implemented the workaround, but am still getting a line-wrap during transition, that causes my text to flicker: 
http://treefortress.com/shared/2019-10-20_09-49-24.mp4

Tied wrapping the content in Material, and DefaultTextStyle, both still result in this flicker. 

I can manually size the container to get rid of it, but these containers are variable width, depending on the size of their text, so that's not ideal.

**Comment by LongCatIsLooong** [comment] 2019-10-20 21:50
@esDotDev thanks for reporting the issue! So the workaround works for you (i.e. the text is getting the correct `TextStyle`), expect that it flickers during transition? That reminds me of https://github.com/flutter/flutter/issues/42988. 
Could you post a minimal code sample that reproduces the problem in that thread?

**Comment by pdf** [comment] 2019-12-22 23:03
We'd like to wrap a `BottomAppBar` in a `Hero`, but since `BottomAppBar` depends on having a `Scaffold` available via the context, it throws an exception on every transition, and I suspect that is due to this issue.  I cannot see a viable workaround.

**Comment by Skquark** [comment] 2020-01-23 08:26
Was still having trouble with the fix for a Text Hero using the suggested flightShuttleBuilder because it wasn't taking my from/to style font with the DefaultTextStyle, so I had to tweak it a bit and got it working for my needs.  I made it as an extension on Text just because it's prettier to use.  Here's my code:
```
extension HeroText on Text {
  Widget hero(Object tag) {
    return Hero(
      flightShuttleBuilder: (_, Animation<double> animation, HeroFlightDirection flightDirection, BuildContext fromHeroContext, BuildContext toHeroContext) {
        return AnimatedBuilder(
          animation: animation,
          child: this,
          builder: (_, _child) {
            return DefaultTextStyle.merge(
              child: _child,
              style: TextStyle.lerp(((fromHeroContext.widget as Hero).child as Text).style, ((toHeroContext.widget as Hero).child as Text).style,
                  flightDirection == HeroFlightDirection.pop ? 1 - animation.value : animation.value),
            );
          },
        );
      },
      tag: tag,
      transitionOnUserGestures: true,
      child: this,
    );
  }
}
```
So on the from page, you have something like: 
`    Text("Title as Hero", style: TextStyle(fontSize: 16.0, fontFamily: "Fira", color: Colors.blue.shade800)).hero("title"),`
and the same on the to page
`    Text("Title as Hero", style: TextStyle(fontSize: 22.0, fontFamily: "Fira", color: Colors.blue.shade500)).hero("title"),`
Now lerps the TextStyle nicely enough, but still should be fixed on the Flutter side so we don't have to hack it..

**Comment by rrousselGit** [comment] 2020-06-24 16:00
Happens with `package:animation` too https://github.com/rrousselGit/river_pod/issues/10#event-3477716646

**Comment by diego-lipinski-de-castro** [comment] 2020-08-30 05:31
wtf is happening to my text when transitioning?

**Comment by diego-lipinski-de-castro** [comment] 2020-08-30 05:32
![Gravacao-de-Tela-2020-08-30-as-0](https://user-images.githubusercontent.com/29608698/91651950-05eb6500-ea69-11ea-89c3-cc438c2de9b0.gif)

wtf is happening to my text when its transitioning?

**Comment by esDotDev** [comment] 2020-08-30 13:58
Try a " hack " fix. Something to do with Flutter measuring it like 1px diffently while in motion, putting in padding spaces seemed to work for me like 6mths ago, ymmv

**Comment by diego-lipinski-de-castro** [comment] 2020-08-30 14:07
It kinda works. But it flashes the text, like a blinking

**Comment by esDotDev** [comment] 2020-08-30 20:23
Ya, I just don't use Hero's anymore for mainly this reason, they act weird when using text. /shrug

Maybe you can stop it from wrapping and make sure it's not getting clipped?

**Comment by itmediacreations** [comment] 2020-10-23 07:16
I stopped it from wrapping using SizedBox with width: double.infinity or Expanded depends on your needs also wrapped Text inside Material so no bad background no longer occur while hero animation.

For my purpose I created separeted widget with Hero like below:

```
import 'package:flutter/material.dart';

class HeroArticle extends StatelessWidget {
  final Widget child;
  final Object tag;
  ///Provide your own TextStyle for Material transition to override style
  ///In case of Child is Text then style of Text is merged with bodyText2
  ///Otherwise bodyText2 is used
  final TextStyle textStyle;

  HeroArticle({@required this.child, @required this.tag, this.textStyle});

  @override
  Widget build(BuildContext context) {
    final TextStyle _themeStyle = Theme.of(context).textTheme.bodyText2;
    return Hero(
      tag: tag,
      child: Material(
        textStyle: textStyle ?? child is Text
            ? _themeStyle.merge((child as Text).style)
            : _themeStyle,
        type: MaterialType.transparency,
        child: child,
      ),
    );
  }
}
```
Then I'm using it like this:

Code in first screen: 

```
              HeroArticle(
                tag: articleData.subtitle.hashCode,
                child: Text(
                  articleData.subtitle,
                  textAlign: TextAlign.center,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
```

Code in next screen:

```
                      SizedBox(
                        //SizedBox used for use all available space for animation,
                        // if https://github.com/flutter/flutter/issues/36220 will close than can be removed
                        width: double.infinity,
                        child: HeroArticle(
                          tag: articleData.subtitle.hashCode,
                          child: Text(
                            articleData.subtitle,
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 17,
                              fontWeight: FontWeight.w300,
                            ),
                          ),
                        ),
                      ),
```

Hope it helped for someone.
Cheers!

**Comment by ModProg** [comment] 2021-01-31 22:54
I don't know if this is also caused by this issue:

With the Workaround in  #10667, the image keeps disappearing for one frame:
https://user-images.githubusercontent.com/11978847/106399704-8cdaaa00-641a-11eb-89f8-5c3b5745c266.mp4

**Comment by AAverin** [comment] 2021-03-13 11:33
Any update or plans for this issue? Hero animations keep blinking for me still with Flutter 2.0 released.

**Comment by JohannesPertl** [comment] 2022-01-09 16:23
It's still not working with Text. Any updates?

**Comment by Binozo** [comment] 2022-03-12 17:16
Still same bullshit

**Comment by creativecreatorormaybenot** [comment] 2022-03-12 18:26
@Binozo hi - please make sure to consider https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md.

**Comment by Binozo** [comment] 2022-03-12 18:28
@creativecreatorormaybenot please excuse my poor choice of words

**Comment by ulrikap** [comment] 2022-04-22 11:55
So i have a theory as to what may cause this flickering. During testing i found that the hero widget resizes the image during flight and for each frame, 1px would drop from either height or width. The image does however not flicker, but text does. I was able to consistently recreate the bug with a text that contained two words, and the last word would flicker. 

See gif for how the debugger complains about a large image in transit resizing:

![PR](https://user-images.githubusercontent.com/26012720/164707818-0a0c0029-897e-4704-8edd-47c96115eb52.gif)

This lead me to think that the hero widget shaves 1px from whatever widget is being transferred at some random points during transition. After some trial and error i found out that adding a blank space at the end of a text would not stutter during transit. I think this is due to the fact that the end of the text string loses 1 px and flickers, but the "flickering" part of the hero transition is on an empty text, hence not shown to the user.

Changing this:

```dart
  Hero(
      tag: 'name',
      child: Text(
          user.name,
          style: Theme.of(context).textTheme.headline6,
      ),
    ),
```
 to this 
```dart
   Hero(
      tag: 'name',
      child: Text(
          '${user.name} ', <----- notice the blank space at EOL
          style: Theme.of(context).textTheme.headline6,
      ),
    ),
```
resolved my issue.

Before fix:
![before](https://user-images.githubusercontent.com/26012720/164709171-f96b0db4-3b90-465f-8f36-c0e92de99391.gif)

After fix:
![after](https://user-images.githubusercontent.com/26012720/164709202-72d7015a-1b7e-4229-89b9-5cd427fc1b1d.gif)


Note that this *not* a fix. The core issue remains, but for flutter developers who want to make Hero text transition work without stuttering, this seems to be a workaround for now. Worked for me atleast.

**Comment by Justus-M** [comment] 2022-05-16 00:45
> ## Summary
> So i have a theory as to what may cause this flickering. During testing i found that the hero widget resizes the image during flight and for each frame, 1px would drop from either height or width. The image does however not flicker, but text does. I was able to consistently recreate the bug with a text that contained two words, and the last word would flicker.
> 
> See gif for how the debugger complains about a large image in transit resizing:
> 
> ![PR](https://user-images.githubusercontent.com/26012720/164707818-0a0c0029-897e-4704-8edd-47c96115eb52.gif)
> 
> This lead me to think that the hero widget shaves 1px from whatever widget is being transferred at some random points during transition. After some trial and error i found out that adding a blank space at the end of a text would not stutter during transit. I think this is due to the fact that the end of the text string loses 1 px and flickers, but the "flickering" part of the hero transition is on an empty text, hence not shown to the user.
> 
> ## Workaround for text
> Changing this:
> 
> ```dart
>   Hero(
>       tag: 'name',
>       child: Text(
>           user.name,
>           style: Theme.of(context).textTheme.headline6,
>       ),
>     ),
> ```
> 
> to this
> 
> ```dart
>    Hero(
>       tag: 'name',
>       child: Text(
>           '${user.name} ', <----- notice the blank space at EOL
>           style: Theme.of(context).textTheme.headline6,
>       ),
>     ),
> ```
> 
> resolved my issue.
> 
> Before workaround: ![before](https://user-images.githubusercontent.com/26012720/164709171-f96b0db4-3b90-465f-8f36-c0e92de99391.gif)
> 
> After workaround: ![after](https://user-images.githubusercontent.com/26012720/164709202-72d7015a-1b7e-4229-89b9-5cd427fc1b1d.gif)
> 
> ## Note
> The core issue remains, but for flutter developers who want to make Hero text transition work without stuttering, this seems to be a workaround for now. Worked for me atleast.

this worked for me thanks

**Comment by LongCatIsLooong** [comment] 2022-05-26 22:24
Hi @rrousselGit @fzyzcjy I checked out the https://github.com/fzyzcjy/flutter_portal project and it looks like a really promising solution to this problem. Are you ok with integrating some of its APIs into `Overlay`, as an addition to the `OverlayEntry` API? I'll be happy to create a pull request and attribute the idea to you/the flutter_portal package, and let you review it if you're ok with that.

**Comment by rrousselGit** [comment] 2022-05-26 22:41
That'd be lovely! In fact, I proposed that a long time ago (https://github.com/flutter/flutter/issues/50961) 

It'd be awesome to have that be an official solution.

**Comment by fzyzcjy** [comment] 2022-05-26 23:13
@LongCatIsLooong Sure! It would be great to be in official package!

**Comment by rrousselGit** [comment] 2022-06-01 17:44
I'm not sure if it does, but it should.

The Portal should have access to the list of associated entries, so it should be able to make them relayout right?

**Comment by fzyzcjy** [comment] 2022-06-01 23:17
+1

When PortalTarget feels its environment changes, it will tell Portal about it.

**Closed** 2023-11-26 00:07 UTC
Labels: framework, f: routes, customer: crowd, P1, team-framework
