### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by BrennoLins** [flutter/flutter#61053] opened 2020-07-08 00:54 UTC
I'm getting an error when I try to create a new flutter project on Android Studio.

## command

flutter --no-color create --template app --description A new Flutter application. --org example flutter_app

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\brenn\Documents\code\flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\src\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Acesso negado.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#25     _templateImageDirectory (package:flutter_tools/src/template.dart)
#26     _rootRunUnary (dart:async/zone.dart:1192:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#34     _ensurePackageDependencies (package:flutter_tools/src/template.dart)
#35     _rootRunUnary (dart:async/zone.dart:1192:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#43     _DefaultPub.get (package:flutter_tools/src/dart/pub.dart)
#44     _rootRunUnary (dart:async/zone.dart:1192:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#52     _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart)
#53     _rootRunUnary (dart:async/zone.dart:1192:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#55     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#56     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#57     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#58     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#59     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#60     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#61     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#62     _rootRunUnary (dart:async/zone.dart:1192:38)
#63     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#64     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#65     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#66     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#67     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#68     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#69     _rootRun (dart:async/zone.dart:1184:13)
#70     _CustomZone.run (dart:async/zone.dart:1077:19)
#71     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#72     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [versÃ£o 10.0.18362.900], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\brenn\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Obs: Acesso negado = Access denied

**Comment by jonahwilliams** [comment] 2020-07-08 01:19
You should not have installed flutter to `'C:\src\flutter\`. The tooling is likely being prevented from reading the template files by the file permissions that apply to things in the directory root. I recommend installing to Documents or elsewhere that is user readable/writable.

Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-07-08 01:19 UTC
