### ISSUE TITLE
The labeler GitHub action removes a label I explicitly added to have another team triage the PR

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#130527] opened 2023-07-13 22:11 UTC
https://github.com/flutter/flutter/pull/129739

![Screenshot from 2023-07-13 14-28-49](https://github.com/flutter/flutter/assets/7856010/e5921d13-b1de-4da5-bf8e-53b41de0cfa0)

The action removed the label, because in the config, the pattern specified for the label `platform-ios` is:

```yaml
platform-ios:
  - packages/flutter_tools/lib/src/ios/**/*
```

https://github.com/flutter/flutter/blob/master/.github/labeler.yml#L80

What is the appropriate way to add a label to a PR that does not strictly adhere to the labeler action's rules?

**Comment by christopherfujino** [comment] 2023-07-13 22:12
cc @CaseyHillers

**Comment by CaseyHillers** [comment] 2023-07-14 17:17
Duplicate of https://github.com/flutter/flutter/issues/128440

**Closed by CaseyHillers** 2023-07-14 17:17 UTC
Labels: team-infra
