### ISSUE TITLE
Sometimes integration test fails to start on iOS simulator and flutter test takes 12 minutes to time out

### ISSUE THREAD

**Issue by maBarabas** [flutter/flutter#153433] opened 2024-08-14 12:52 UTC
### Steps to reproduce

1. `flutter test integration_test` using iOS simulator

### Expected results

Test runs.

If test fails to load to the phone, then the command exits with an error straight away.

### Actual results

About 10% of the time the simulator fails to load the app. Then the test command takes 12 minutes to time out.

I was able to reproduce it both in the CircleCI cloud runners and on a local M1 Mac Mini.

I think it would be good enough if instead of timing out, the test command exited immediately on error. Then I can set up some retry logic in a script that runs the tests.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter test --flavor production integration_test

00:04 +0: loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart                                                                              Ru00:25 +0: loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart                                                                               
00:28 +0: loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart                                                                           3.1s
Xcode build done.                                           23.7s
00:29 +0: loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart                                                                               Error: Unable to launch my.app.id on F7AF702A-AA98-48AF-989A-60AAA5A3929C:
ProcessException: Process exited abnormally with exit code 4:
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch my.app.id.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "my.app.id" failed.
  Command: /usr/bin/arch -arm64e xcrun simctl launch F7AF702A-AA98-48AF-989A-60AAA5A3929C my.app.id --enable-dart-profiling --disable-vm-service-publication --enable-checked-mode
  --verify-entry-points
00:29 +0 -1: loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart [E]                                                                        
  TestDeviceException(Unable to start the app on the device.)
  package:flutter_tools/src/test/integration_test_device.dart 63:7  IntegrationTestTestDevice.start
  
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePort._handleMessage
  

To run this test again: /Users/me/development/flutter/bin/cache/dart-sdk/bin/dart test /Users/me/projects/myapp/integration_test/database/database_interface_test.dart -p vm --plain-name 'loading /Users/me/projects/myapp/integration_test/database/database_interface_test.dart'
12:04 +0 -1: loading /Users/me/projects/myapp/integration_test/database/native_migrations_test.dart                                                                            Ru12:24 +0 -1: loading /Users/me/projects/myapp/integration_test/database/native_migrations_test.dart                                                                             
12:26 +0 -1: loading /Users/me/projects/myapp/integration_test/database/native_migrations_test.dart                                                                      1,959ms
Xcode build done.                                           21.9s
12:33 +0 ~11 -1: Some tests failed.                                                  
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.3 on channel stable at /Users/me/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (4 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • test (mobile)                   • F7AF702A-AA98-48AF-989A-60AAA5A3929C • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 14.4.1 23E224 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by darshankawar** [comment] 2024-08-14 13:23
Closing this as duplicate of https://github.com/flutter/flutter/issues/105913. Please follow-up in it for further updates.

**Comment by maBarabas** [comment] 2024-08-14 13:28
This is a different issue, please reopen.

The linked issue is about the build taking too long then the timeout expiring.

This issue is about the simulator failing to launch the app, then the test command not exiting with an error code straight away.

**Comment by darshankawar** [comment] 2024-08-15 05:54
Thanks for feedback.
Can you take a look at https://github.com/dart-lang/test/tree/master/pkgs/test#timeouts and see if it helps in your case ?

**Comment by maBarabas** [comment] 2024-08-15 10:11
I'm not sure about the details of how the test tool works, but looks like the app that runs the tests is failing to launch, so chaging timeouts inside the test will have no effect.

**Comment by darshankawar** [comment] 2024-08-16 05:47
Thanks for the update. I am unable to replicate this using demo integration_test app that I ran using iOS simulator. It failed which is different issue, but the test started properly.

Can you check by running on physical device to see if you still get same timeout exception ? Maybe it is specific to simulators.

**Comment by Barabas5532** [comment] 2024-08-23 22:06
It looks like this is caused by an issue with error handling across different Zones in the test tool code. https://dart.dev/libraries/async/zones#example-errors-cant-leave-error-zones.

These reproduction steps should work on any platform. I tested with Linux.

1. set up Android Studio to debug the local copy of the `flutter_tools` package using the [guide in the wiki](https://github.com/flutter/flutter/wiki/The-flutter-tool/25d5794ecfb4b0b4537ff32cc863f7b58878f1b8#debugging-the-flutter-command-line-tool-in-android-studio). Set the working directory to an existing project with integration tests set up. Set Program arguments to `-vv test -d linux integration_test`.
2. Modify the code for testing so that the error is always thrown here: https://github.com/flutter/flutter/blob/74e250428c210054d0d0ed409c2d22c64409859b/packages/flutter_tools/lib/src/test/integration_test_device.dart#L63. This is the same error seen when the app fails to launch on the device. Since the failure to launch the app is rare, we need to temporary modify the code to reproduce the exception.
3. Modify `TestDeviceException.toString` to use block body, and put a break point on the return statement.
5. Debug the Android Studio run configuration set up earlier.

The result of `TestDevice.start` is awaited here: https://github.com/flutter/flutter/blob/74e250428c210054d0d0ed409c2d22c64409859b/packages/flutter_tools/lib/src/test/flutter_platform.dart#L555. This is in a try catch block, but the catch never runs (the printTrace messages are not in the logs). Instead the error is handled in https://github.com/dart-lang/test/blob/337c7fb0bbf01d693fb673a5ae3caa15f8e7eb09/pkgs/test_api/lib/src/backend/invoker.dart#L161. This can be seen from the backtrace when the `TestDeviceException.toString` breakpoint is hit.

**Comment by christopherfujino** [comment] 2024-08-26 18:04
> It looks like this is caused by an issue with error handling across different Zones in the test tool code. https://dart.dev/libraries/async/zones#example-errors-cant-leave-error-zones.
> 
> These reproduction steps should work on any platform. I tested with Linux.
> 
> 1. set up Android Studio to debug the local copy of the `flutter_tools` package using the [guide in the wiki](https://github.com/flutter/flutter/wiki/The-flutter-tool/25d5794ecfb4b0b4537ff32cc863f7b58878f1b8#debugging-the-flutter-command-line-tool-in-android-studio). Set the working directory to an existing project with integration tests set up. Set Program arguments to `-vv test -d linux integration_test`.
> 2. Modify the code for testing so that the error is always thrown here: https://github.com/flutter/flutter/blob/74e250428c210054d0d0ed409c2d22c64409859b/packages/flutter_tools/lib/src/test/integration_test_device.dart#L63
>    . This is the same error seen when the app fails to launch on the device. Since the failure to launch the app is rare, we need to temporary modify the code to reproduce the exception.
> 3. Modify `TestDeviceException.toString` to use block body, and put a break point on the return statement.
> 4. Debug the Android Studio run configuration set up earlier.
> 
> The result of `TestDevice.start` is awaited here:
> 
> https://github.com/flutter/flutter/blob/74e250428c210054d0d0ed409c2d22c64409859b/packages/flutter_tools/lib/src/test/flutter_platform.dart#L555
> 
> . This is in a try catch block, but the catch never runs (the printTrace messages are not in the logs). Instead the error is handled in https://github.com/dart-lang/test/blob/337c7fb0bbf01d693fb673a5ae3caa15f8e7eb09/pkgs/test_api/lib/src/backend/invoker.dart#L161. This can be seen from the backtrace when the `TestDeviceException.toString` breakpoint is hit.

Wow, thanks for the great investigative work here!

**Comment by darshankawar** [comment] 2024-08-28 06:11
Based on the analysis and findings, keeping the issue open for team's tracking.

**Closed** 2024-09-16 17:32 UTC
Labels: platform-ios, tool, framework, f: integration_test, team-tool

**Comment by christopherfujino** [comment] 2024-09-16 18:03
Thanks so much for the in depth investigation @Barabas5532. I believe I've fixed this in https://github.com/flutter/flutter/pull/154970, which you can get from pull the latest `master` branch.
