### ISSUE TITLE
Flutter Web is showing emojis in outline form instead of color

### ISSUE THREAD

**Issue by jsaulsberry-cvet** [flutter/flutter#121048] opened 2023-02-18 19:47 UTC
Steps to Reproduce: Try to display an emoji in flutter web running flutter v. 3.7.3 such as the united states flag 🇺🇸 

Notice that the Notice that Flutter Web only displays them in outline form

![Screenshot 2023-02-18 at 1 47 23 PM](https://user-images.githubusercontent.com/72142765/219885223-72288084-9418-40d7-a741-591bd4b7b999.png)

**Comment by huycozy** [comment] 2023-02-20 10:46
Hi @jsaulsberry-cvet 
I'm closing this issue as a duplicate of https://github.com/flutter/flutter/issues/119536. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thanks!

**Closed by huycozy** 2023-02-20 10:46 UTC
Labels: in triage
