### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 52440 Oops; flutter has exited unexpectedly: "FileSystemException: Failed to set file modification time, path = '/Users/mac/Documents/flutter_demo/flutter_app01/.packages' (OS Error: Operation not permitted, errno = 1)". A crash report has been written to /Users/mac/Documents/flutter_demo/flutter_app01/flutter_09.log.

### ISSUE THREAD

**Issue by Fgithup** [flutter/flutter#51688] opened 2020-02-29 06:00 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by jonahwilliams** [comment] 2020-02-29 17:46
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-29 17:46 UTC
