### ISSUE TITLE
Vertical focus traversal leaning more on left widgets

### ISSUE THREAD

**Issue by iamsahilsonawane** [flutter/flutter#115550] opened 2022-11-17 10:51 UTC
This issue is regarding focus traversals in layout for the big screens, particularly Android TV. 
Wherein, I've implemented this TV guide layout (I've explained the layout below). 

https://user-images.githubusercontent.com/47249618/202426824-9a846b63-4918-46fa-8ba2-a402c126365f.mov

Well, the problem is that, when navigating down the widgets, the focus is not traversing down to its immediate bottom widget, instead, leaning on to the bottom left ones.

<details>
  <summary>Reproducible Sample</summary>

NOTE: This example is using Mac as the device.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF12202F),
      ),
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: List.generate(
          5,
          (x) {
            return Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: List.generate(
                10,
                (i) {
                  return InkWell(
                    autofocus: x == 0 && i == 0,
                    onTap: () {},
                    child: Builder(builder: (context) {
                      final isFocused = Focus.of(context).hasPrimaryFocus;
                      return Program(
                        isFocused: isFocused,
                        text: 'Item $x,$i',
                        isBig: x == 3 && i == 0,
                      );
                    }),
                  );
                },
              ),
            );
          },
        ),
      ),
    );
  }
}

class Program extends StatelessWidget {
  const Program({
    Key? key,
    required this.isFocused,
    required this.text,
    this.isBig = false,
  }) : super(key: key);

  final bool isFocused;
  final String text;
  final bool isBig;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: isBig ? 250 : 200,
      height: 50,
      color: isFocused ? Colors.white : Colors.transparent,
      child: Text(text, style: TextStyle(color: isFocused ? Colors.black : Colors.white)),
    );
  }
}
```
</details>

<details>
<summary>Sample - Explanation & Video Demo</summary>

Explanation: If you run the code or see the demo down, with the same widths, it will traverse down like expected, but when there's an element with long width beneath, then it leans to the left. 

In this example: `Item 2,1` traverses to `Item 2,0` when pressed down.

I think it is expected, but it continues going in the back direction which makes the scrollable scroll to the left (not expected from UX POV). Is it possible, to either shift the focus to the right of it? In this case, the focus from `Item 2,1` should go to `Item 3,1` instead of `Item 3,0`.

Here's the video demo of the sample.

https://user-images.githubusercontent.com/47249618/202635908-865651c9-0b2c-4990-92cf-3e28b9415784.mov

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/iamsahilsonawane/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/iamsahilsonawane/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-11-17 12:47
Hello @iamsahilsonawane. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by iamsahilsonawane** [comment] 2022-11-18 06:35
@exaby73 I've updated the description with a reproducible sample, an explanation, and a video demo (of the sample). 

Thanks for the support!

**Comment by huycozy** [comment] 2022-11-18 07:44
@iamsahilsonawane thanks for providing a [minimal sample code](https://github.com/flutter/flutter/issues/115550#issue-1453130459). This issue is reproducible on the latest `stable` and `master` channels.

<details>
<summary>Demo video</summary>

https://user-images.githubusercontent.com/104349824/202648136-87e74243-98d8-4011-a1de-c2f42d3f78d7.mov

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (23 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.6.0-5.0.pre.25, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.6.0-5.0.pre.25 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5487a7debf (21 minutes ago), 2022-11-17 22:23:12 -0500
    • Engine revision 39f546585b
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • SM T225 (mobile) • R9JT3004VRJ                              • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7 19H12
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by goderbauer** [comment] 2022-11-22 23:18
cc @gspencergoog

**Comment by iamsahilsonawane** [comment] 2022-11-25 05:26
@goderbauer you've added the P6 label which is "unlikely to address". I think that's because the behavior is expected right? If so, is there any workaround?

**Comment by gspencergoog** [comment] 2022-11-29 23:18
Thanks for the report!  There appear to be two things going on here.

1) A genuine bug in the directional traversal algorithm: it was ordering candidate nodes arbitrarily in some cases, instead of sorting them according to distance to center of the bounding box. This causes it to sometimes pick a widget that is further away than the closest eligible widget (in this case, the one to the left instead of the one in the same column). This is fixed in https://github.com/flutter/flutter/pull/116230

2) Because your long widget on the bottom left extends off the edge of the scroll area, when it receives focus it is attempting to bring the beginning of its bounding box into view in the scrollable area, causing the scrollable area to scroll to the left. The only good workaround I can think of for this is to clip your widget at the boundary of the scrollable area, which isn't really all that easy to do. (In this exact repro example, the fix above will actually prevent the wrong widget from being focused in the first place, so it won't scroll anymore, but it would be easy to make another example where it did) I could present an argument that scrolling it into view is a better UI anyhow, but I realize that's not any help to you if you or your designer disagree.

For posterity, here's the test app I used when fixing the bug:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static const int cols = 3;
  static const int rows = 3;
  late final List<bool?> focus;

  @override
  void initState() {
    super.initState();
    focus = List<bool?>.generate(rows * cols, (int _) => null);
  }

  Widget makeBox(int row, int col) {
    final int index = row * rows + col;
    return HighlightedBox(
      width: index == 3 ? 150 : 100,
      height: index == 1 ? 150 : 100,
      label: index.toString(),
      color: Colors.primaries[index],
      onFocusChanged: (bool isFocused) => focus[index] = isFocused,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Directionality(
          textDirection: TextDirection.ltr,
          child: FocusTraversalGroup(
            policy: WidgetOrderTraversalPolicy(),
            child: FocusScope(
              debugLabel: 'Scope',
              child: Column(
                children: <Widget>[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: <Widget>[
                      makeBox(0, 0),
                      makeBox(0, 1),
                      makeBox(0, 2),
                    ],
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      makeBox(1, 0),
                      makeBox(1, 1),
                      makeBox(1, 2),
                    ],
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      makeBox(2, 0),
                      makeBox(2, 1),
                      makeBox(2, 2),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class HighlightedBox extends StatefulWidget {
  const HighlightedBox({
    super.key,
    required this.label,
    required this.width,
    required this.height,
    required this.color,
    this.onFocusChanged,
  });

  final String label;
  final double width;
  final double height;
  final ValueChanged<bool>? onFocusChanged;
  final Color color;

  @override
  State<HighlightedBox> createState() => _HighlightedBoxState();
}

class _HighlightedBoxState extends State<HighlightedBox> {
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode(debugLabel: widget.label);
  }

  void _focusChanged(bool focus) {
    setState(() {
      if (focusNode.hasPrimaryFocus) {
        debugPrint('Node ${focusNode.debugLabel} has focus');
      }
      widget.onFocusChanged?.call(focus);
    });
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      focusNode: focusNode,
      onFocusChange: _focusChanged,
      child: Container(
        alignment: Alignment.center,
        width: widget.width,
        height: widget.height,
        decoration: ShapeDecoration(
          color: widget.color,
          shape: RoundedRectangleBorder(
            side: focusNode.hasPrimaryFocus ? const BorderSide(width: 2) : BorderSide.none,
          ),
        ),
        child: Text(widget.label),
      ),
    );
  }
}
```

**Comment by iamsahilsonawane** [comment] 2022-11-30 11:21
Thank you @gspencergoog for your reply and fixes. I had a look at the pull, it looks very predictive now, thank you for that. I will have some tests with your given fixture to continue with the work :)

Thanks again!

**Closed** 2022-12-01 23:41 UTC
Labels: framework, f: focus, has reproducible steps, P6, found in release: 3.3, found in release: 3.6
