### ISSUE TITLE
Zawgyi font incorrect in TextField

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40962] opened 2019-09-20 11:16 UTC
In flutter 1.9.1,
Unicode is correctly showed in TextField for that thank you Flutter Team. But, for Zawgyi Users, Zawgyi Font is incorrectly showed. 

How to solve this problem.

**Comment by escamoteur** [comment] 2019-09-20 11:23
Hi, could you please add the output of `flutter doctor`
Also please add a screenshot so that we see what you mean and decribe in detail what's wrong.

**Comment by uwaiphyoaung** [comment] 2019-09-20 11:35
Unicode
![device-2019-09-20-180042](https://user-images.githubusercontent.com/50459946/65323922-b18d0380-dbd0-11e9-8a85-9fe97cef9d29.png)

Zawgyi
![device-2019-09-20-180323](https://user-images.githubusercontent.com/50459946/65324116-455ecf80-dbd1-11e9-9b68-6e787f94c314.png)

**Comment by escamoteur** [comment] 2019-09-20 11:45
DO you mean Zawgyi should like the Uni code version? Sorry  I can't read Zawgyi

**Comment by mrkyaing** [comment] 2019-09-20 15:31
TextField control is build-in set only for Unicode TypeFace in flutter. if so,can we override or remove this typeface?

**Comment by uwaiphyoaung** [comment] 2019-09-23 02:49
C:\flutterdev\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\flutterdev\flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MIT-170\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\MIT-170\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
Process finished with exit code 0

**Comment by TahaTesser** [comment] 2020-04-30 13:50
Hi @uwaiphyoaung 
Are you still experiencing this issue with latest `stable` channel?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-06-05 12:22
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by min-wai** [comment] 2020-06-05 17:38
So what's happening Zawgyi and Unicode doesn't like each other. Although Unicode is preferred, many devices still have Zawgyi.
With Flutter, we could apply Unicode font to the entire app, and users will see correct Burmese whether or not they have Zawgyi or Unicode. But when it comes to input fields, Zawgyi users will not see correct Burmese since they have Zawgyi keyboards. 
So this is a huge issue to overcome for devs trying to support both languages.

**Comment by TahaTesser** [comment] 2020-07-16 13:40
This is difficult to understand to  reproduce even when enabling Burmese on the device. Will need someone wo understands Burmese

**Comment by Hixie** [comment] 2020-07-28 23:30
@uwaiphyoaung Is it specifically the text field that is the problem? For example if you show exactly the same text in the same font in the text field and in a Text widget do you get different results?

**Comment by min-wai** [comment] 2020-08-11 04:44
> @uwaiphyoaung Is it specifically the text field that is the problem? For example if you show exactly the same text in the same font in the text field and in a Text widget do you get different results?

Even if you use the same text in the same font, it wouldn't matter because Zawgyi users use Zawgyi keyboard, so it would still appear incorrect Burmese with dotted circles. 
I am thinking of creating a custom textfield that detects whether user's system font is Zawgyi or not and apply Zawgyi to just textfield so it would appear correctly if user's font is Zawgyi.
But I don't know how to apply Zawgyi on specific text field.

**Comment by min-wai** [comment] 2020-08-11 04:50
@TahaTesser We don't really have to enable Burmese. When text strings are in Burmese, flutter applies Unicode Burmese, regardless of the font user device has. Btw, I understand Burmese. Let me know how I can help.

**Comment by Hixie** [comment] 2020-08-11 23:18
I think fundamentally we're unlikely to support Zawgyi. We've designed around Unicode support, and Zawgyi itself is deprecated at this point. I would recommend working exclusively with Unicode fonts and encouraging users to use Unicode keyboards.

I understand that this is awkward currently and that this is therefore not what you want to hear. My apologies.

In theory we don't particularly look at the data from the keyboard, and you can set whatever font you want in a text field (text fields aren't particularly special, they render text using TextPainter just like the Text widget). So you could use Zawgyi fonts throughout the system and it should "just work".

**Comment by min-wai** [comment] 2020-08-12 09:31
@Hixie We have supported Zawgyi keyboards in text fields using [flutter_mdetect](https://pub.dev/packages/flutter_mdetect) package by detecting Zawgyi first and using text style with Zawgyi font. 
And we use Unicode throughout the whole app, so users wouldn't have to worry about what font they are using.
There should be other solutions as well. But I think this can be closed for now. Thanks.

**Comment by Hixie** [comment] 2020-08-13 03:50
Nice! Glad to hear things are working for you.

**Closed by Hixie** 2020-08-13 03:50 UTC
Labels: a: internationalization, a: text input, a: typography, f: material design, framework, passed first triage
