### ISSUE TITLE
Show warning when nesting Scaffolds

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#23106] opened 2018-10-15 17:00 UTC
Using nested Scaffolds can cause unexpected behaviors that rush new issues into this repository,
to prevent further issue reports related, I suggest an assertion in the Scaffold Class just for Debug Mode:

```
assert(() {
  assert(context.ancestorWidgetOfExactType(Scaffold) == null);
});
```

These are some of the issues:

- https://github.com/flutter/flutter/issues/23051
- https://github.com/flutter/flutter/issues/20289
- https://github.com/flutter/flutter/issues/12084
- https://github.com/flutter/flutter/issues/20295

**Comment by zoechi** [comment] 2018-12-20 15:59
#12084 is about fixing nested Scaffold which I left open.
I closed the other issues that are caused by nested Scaffolds.

Either nesting Scaffolds is supported, then it should be fixed, 
or it should cause an error or at least be documented as not-supported.

**Comment by goderbauer** [comment] 2019-01-03 23:37
Related: https://github.com/flutter/flutter/issues/22349

/cc @HansMuller Do you have an opinion if nested Scaffold is something that should be supported or should we discourage people more actively from nesting them?

**Comment by HansMuller** [comment] 2019-01-03 23:51
Scaffolds were not intended to be nested. We should sort out the use cases that cause developers to use nested scaffolds and explain how address those cases without nesting.  Having done that, and assuming that there aren't some legitimate nested scaffold use cases that we aren't aware of, we should probably introduce the assert and include one of our titanic error messages that explains what's wrong and how to avoid it.

**Comment by davidmartos96** [comment] 2019-01-09 13:04
@HansMuller One of the use cases, which I guess multiple people try to achieve, is the bottom navigation bar behaviour of CupertinoTabView + CupertinoTabScaffold with Material widgets. It maintains a Navigator in each tab, and the state of each tab is preserved using Offstages in a Stack.
To implement this in with the Material implementation would require to use a scaffold to display the bottom bar and then a nested scaffold in each tab to possibly display a different AppBar according to the current tab.  
This issue regarding this behaviour is #18740, which doesn't seem to get much attention.
I don't know about other use cases, but this is one I encountered with.

**Closed** 2019-01-15 16:16 UTC
Labels: f: material design, framework

**Comment by chickenblood** [comment] 2019-11-27 23:11
David's use case mentioned on January 8 is the exact use case that I am trying to support too. There does not seem to be a good alternative to this, so before making this an error, an alternative pattern for supporting tabs that can contain nested navigation should be documented.

**Comment by HansMuller** [comment] 2019-11-27 23:32
@chickenblood I'm sorry, I should have retracted my old comment about nested Scaffolds, as I did here: https://github.com/flutter/flutter/issues/18740#issuecomment-516035360

I wrote an article about nested scaffolds and navigators, and building something roughly comparable to tabbed web browsing: https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386

**Comment by chickenblood** [comment] 2019-11-27 23:42
@HandMuller excellent. That's exactly the tutorial that I've been following 👍

**Comment by hawkinsjb1** [comment] 2020-06-29 21:09
There still seems to be no documented support for multiple offstage navigators without using nested scaffolds. I have found other use cases for nesting scaffolds, such as a top-level scaffold intended for snackbars on top of all child screens. IMO I don't see why we should restrict people to using 1 scaffold per screen when each particular element of the scaffold may not be related to one another state-wise (different appbars across bottom navigation screens, different FABs across bottom navigation screens, top-level scaffold using snackbars to display generic error handling, etc.). Manually implementing appbars and FABs using a mixture of stacks, alignments, or columns is inconsistent and messy

**Comment by anhln8x** [comment] 2020-08-27 08:33
I favor nested scaffolding, implementing generic app bar with parameter configuration is really complicated.

**Comment by goashwin** [comment] 2020-09-01 08:40
+1 The app we're building has differing bottomNavigationBars, appBars, and floatingActionButtons on different screens/tabs.

Using a single Scaffold means the parent BLoC has to have full knowledge of child BloCs. With nested Scaffolds, each child can build its own screen.

We also use a single global Scaffold in main.dart to show global snackbars.

**Comment by mehmetf** [comment] 2020-09-17 15:39
> Top-level scaffold intended for snackbars on top of all child screens

That's not a good idea. If a FAB belongs to a child scaffold, snackbar would not be able to interact with it. There's a reason why snackbars are tied to scaffolds.

There's a better upcoming solution for this. Follow: https://github.com/flutter/flutter/issues/62921

**Comment by hungrymonkey** [comment] 2020-09-19 16:40
duplicate https://github.com/flutter/flutter/issues/11350

**Comment by chamartt** [comment] 2021-01-11 15:34
@HansMuller thank you for the good article you've made.
In my case, I have to change `AppBar `content depending the current tab ; so, if I understand well, I should have to implement it ine the only one `Scaffold `which is in the top level.
How to achieve this ?

Currently, I saw that I have one top `Scaffold `for the `IndexedStack `and one `Scaffold `by page as body of my `IndexedStack`.
The second Scaffold allows me to give the correct AppBar...

Thank your for your help.
