### ISSUE TITLE
onlaunch keep on firing when app has multiple widgets that implement firebase msg

### ISSUE THREAD

**Issue by ettiennelr** [flutter/flutter#56244] opened 2020-05-03 16:36 UTC
onLaunch: (Map<String, dynamic> message)

This keeps on firing when I transition between multiple widgets that has firebase messaging on it. Same messages then keeps delivering causing a loop

**Comment by TahaTesser** [comment] 2020-05-04 09:30
Hi @ettiennelr 
For what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [GitHub](https://github.com/FirebaseExtended/flutterfire/issues). 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-04 09:30 UTC
