### ISSUE TITLE
Flutter gets upset when running under C locale

### ISSUE THREAD

**Issue by paulcbetts** [flutter/flutter#14241] opened 2018-01-24 01:09 UTC
When Flutter is running in CI under a minimalist Docker container that bizarrely decided to use C as its locale setting, many commands blow up

## Steps to Reproduce

1. `docker run -ti circleci/android:api-27-alpha bash`
1. `git clone https://github.com/flutter/flutter && export PATH="$PATH:$PWD/flutter/bin"`
1. `flutter create foo`

Crashes with:

```
## exception

ArgumentError: Invalid argument(s): Invalid locale 'C.UTF-8'

#0      Intl._throwLocaleError (package:intl/intl.dart:231)
#1      Intl.verifiedLocale (package:intl/intl.dart:225)
#2      Intl.verifiedLocale (package:intl/intl.dart:210)
#3      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:486)
#4      new NumberFormat.decimalPattern (package:intl/src/intl/number_format.dart:175)
#5      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:103)
#6      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:103)
#7      getElapsedAsMilliseconds (package:flutter_tools/src/base/utils.dart:111)
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:217)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
```

**Comment by Hixie** [comment] 2018-01-25 21:40
cc @HansMuller in case you know anything about how Intl might care about the system locale

**Comment by Hixie** [comment] 2018-05-23 21:02
Duplicate of https://github.com/flutter/flutter/issues/11151

**Closed by Hixie** 2018-05-23 21:02 UTC
