### ISSUE TITLE
Calling Flutter MethodChannel from Android(Kotlin) side gets Kotlin.Unit

### ISSUE THREAD

**Issue by word-x** [flutter/flutter#133369] opened 2023-08-25 23:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
Just press the button on home page to call Native side method.

### Expected results

Android side can directly get the data returned by Flutter side.

### Actual results

When we call 
channel.invokeMethod(flutterMethod, params)
it return Kotlin.Unit.

After we tested with Kotlin Coroutine, we found that the data Flutter returned was actually emitted in success(result: Any?) 

```
channel.invokeMethod(flutterMethod, params, object : MethodChannel.Result {
                          override fun success(result: Any?) {
                                println("Execution thread2-1: ${Thread.currentThread()}")
                                println("callFlutterMethod success: $result")                           
                            }
                           ......
                        })
                    }
```

### Code sample
I have created a minimal project that anyone run the repo. I have tested on my PC that it can show the issue.
https://github.com/word-x/ro_test

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs
I/System.out(11191): Android side received io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1@93c2d9b
I/System.out(11191): Execution thread01: Thread[main,5,main]
I/System.out(11191):  Execution thread02: Thread[main,5,main]
I/System.out(11191):  run MethodChannel.Result
I/System.out(11191): Android received final result:               //**Comment: the function to call Flutter method returned but get no value.**
I/flutter (11191): Call from Android side is received: MethodCall(getDownloadInfo, {001: }).
I/flutter (11191): Flutter side returned download info:AAAAAAAAAA
I/System.out(11191): Execution thread2-1: Thread[main,5,main]
I/System.out(11191): MethodChannel.Result， success: AAAAAAAAAA   **//Value received but the function has already returned null. I tried runblocking/coroutine/join(), etc..., but not solve it.**

### Flutter Doctor output
Doctor summary (to see all details, run flutter doctor -v):                                                                                                                             
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.18363.2274], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)                        
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)                  
    X cmdline-tools component is missing                                                      
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`                               
      See https://developer.android.com/studio/command-line for more details.                 
    X Android license status unknown.                                                         
      Run `flutter doctor --android-licenses` to accept the SDK licenses.                     
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 2022.3)                                                           
[√] Proxy Configuration                                                                       
[√] Connected device (1 available)

**Comment by stuartmorgan** [comment] 2023-08-26 01:10
Please provide a complete reproducible test case; without being able to see the code involved, there's no way to evaluate whether the behavior is correct. The steps provided above are not nearly specific enough for us to reproduce, since methods can return almost anything.

> Doctor output
> ```
> [Paste your output here]
> ```

Please provide all of the requested information when reporting an issue; it's hard to investigate an issue when we don't know things like what version of Flutter you are using.

**Comment by word-x** [comment] 2023-08-26 09:11
Minimal project:

[https://github.com/word-x/ro_test](https://github.com/word-x/ro_test)
Please check the code:

1. lib/channel/flutter_method.dart
2. ro_plugin/android/src/main/kotlin/com/wordx/ro_plugin/channel/CallFlutterMethod.kt3. 

flutter doctor has been checked. Please just check my code.

**Comment by stuartmorgan** [comment] 2023-08-26 11:43
> flutter doctor has been checked.

That does not provide us the information that is in the output. I would encourage you to consider that we have developed the template based on the experience of triaging literally thousands of issues, so there is a reason we ask for the information we do.

> Please just check my code.

We'll be happy to investigate once we have all of the information we've requested. Issues that are missing important information are generally not a good investment of the Flutter team's (finite) time.

**Comment by word-x** [comment] 2023-08-26 12:36
> > flutter doctor has been checked.
> 
> That does not provide us the information that is in the output. I would encourage you to consider that we have developed the template based on the experience of triaging literally thousands of issues, so there is a reason we ask for the information we do.
> 
> > Please just check my code.
> 
> We'll be happy to investigate once we have all of the information we've requested. Issues that are missing important information are generally not a good investment of the Flutter team's (finite) time.

Thanks for your quick response. I am sorry that I seldom sumit issue on Github. I will provide more information as the  template.

**Comment by stuartmorgan** [comment] 2023-08-26 18:06
What are the steps to reproduce with the project you linked to? It's not even runnable as-is since there's no Android directory in the application, and if I add one, the code crashes with a null pointer dereference in the provided project when trying to call (since the channel is never set up). Please provide *exact steps* to reproduce the problem with that project.

**Comment by word-x** [comment] 2023-08-26 19:47
> What are the steps to reproduce with the project you linked to? It's not even runnable as-is since there's no Android directory in the application, and if I add one, the code crashes with a null pointer dereference in the provided project when trying to call (since the channel is never set up). Please provide _exact steps_ to reproduce the problem with that project.

I updated the repo. The repo missed android folder due to network problem.

**Comment by stuartmorgan** [comment] 2023-08-26 20:11
This code is all behaving correctly. It looks like you've edit the original description to contain logging which also shows that it behaves correctly (i.e., we are seeing the same results). The title of the issue says that the result you are getting is `Kotlin.Unit`, but that's not the case as shown in the log:
> I/System.out(11191): MethodChannel.Result， success: AAAAAAAAAA

You've annotated the log with this:
 
> //Value received but the function has already returned null.

It seems like this issue is a misunderstanding of how the async callback API works. The comment there is incorrect; the function doesn't *return* anything, because it's a void function. The result comes via a callback, and your logging shows it doing that correctly.

The other line you've annotated, which starts "Android received final result" is incorrect code in the provided example, because it's printing a value before the value is set. There is nothing "final" about the state when it it is printed; it is in fact guaranteed to just print whatever the variable is initialized to as written.

Closing as there is no Flutter bug here.

**Closed by stuartmorgan** 2023-08-26 20:11 UTC

**Comment by word-x** [comment] 2023-08-26 23:19
Is the callback in channel!!.invokeMethod(flutterMethod,params,**callback**) a MUST to get the Flutter side data?

I remember I once called Flutter side method with no callback assigned and it returned value (sorry I can't provide a repo). But I don't know why I can't do it now.

Some online article also shows some examples with no callback assigned.

[https://stackoverflow.com/questions/55520563/call-flutter-function-from-android-part-of-the-app](https://stackoverflow.com/questions/55520563/call-flutter-function-from-android-part-of-the-app)
[https://medium.com/software-engineers-toolbox/call-flutter-from-native-android-via-platform-channel-in-4-steps-3151f6535d2f](https://medium.com/software-engineers-toolbox/call-flutter-from-native-android-via-platform-channel-in-4-steps-3151f6535d2f)

**Comment by word-x** [comment] 2023-08-26 23:27
It's best to directly get the Flutter side data. 

Otherwise, we need to await the data in _override fun success(result: Any?) {}._  I tried runBlocking/CoroutineScope()+Job.wait() /Thread(), etc... the channel!!.invokeMethod, it doesn't work. 

My understanding is that once the Main/UiThread is blocked, the process to receive Flutter side data is also terminated. I am a pure Flutter developer and have little knowledge in Kotlin. 

What's the right way to wait the Flutter side returned data in Kotlin?

**Comment by stuartmorgan** [comment] 2023-08-26 23:56
> It's best to directly get the Flutter side data.

I don't know what you mean by "directly". If you mean synchronously, that's not possible. You can follow https://github.com/flutter/flutter/issues/28310, but we currently have no plans to add support for that due to significant issues with potential deadlocks.

> Otherwise, we need to await the data in _override fun success(result: Any?)

Yes, implementing the callback is the only way to get the response data.

> My understanding is that once the Main/UiThread is blocked, the process to receive Flutter side data is also terminated.

I don't know what you mean by "terminated", but it is certainly the case that if you block the thread that would receive the response, it won't, because there's no way to receive the message if you're preventing the runloop from doing so.

> What's the right way to wait the Flutter side returned data in Kotlin?

I'm not sure what you mean by "the right way"; how you structure your own asynchronous Kotlin code to fit your use case is up to you to decide. For help with your own code, consider one of the resources at https://flutter.dev/community#community-grid.

**Comment by word-x** [comment] 2023-08-27 00:04
Thank you very much. I will try based on your information.

**Comment by word-x** [comment] 2023-08-27 00:49
This is not work. I am trying to find a way to await the Flutter return value and at the same time not blcok the Main.
fun callFlutterMethod(flutterMethod: String, params: Map<String, String>): String? {
    var res: String? = null
    val deferred = CompletableDeferred<String>()
    var job = CoroutineScope(Main).launch {
        channel!!.invokeMethod(flutterMethod, params, object : MethodChannel.Result {

            override fun success(result: Any?) {
                println("MethodChannel.Result， success: $result")
                deferred.complete(result.toString())

            }

            override fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
                println("callFlutterMethod error: $errorCode, $errorMessage,$errorDetails")

            }

            override fun notImplemented() {
                println("callFlutterMethod error: notImplemented")

            }
        })

    }
    runBlocking {
        launch {
            res=deferred.await()
        }
    }


    println("Android received result: $res")

    return res
}
