### ISSUE TITLE
Firebase Admob ad_not_loaded even though ad was loaded.

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#25022] opened 2018-12-06 09:25 UTC
Firebase Admob ad_not_loaded even though ad was loaded.
isolation: Android and iOS

ERROR: 
Error on Android
``` Console
I/Ads     ( 5084): Ad is not visible. Not refreshing ad.
I/Ads     ( 5084): Scheduling ad refresh 60000 milliseconds from now.
```
Error on iOS
```Console
Exception has occurred.
PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)
```
DEBUG CONSOLE: 
`( 7041): Ad is not visible. Not refreshing ad.`

CODE: 
``` Dart
import 'package:flutter/material.dart';
import 'package:firebase_admob/firebase_admob.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyAppState> {
  

@override
  void initState() {
    super.initState();
    print("Coins: $_coins");
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
    RewardedVideoAd.instance.listener =
        (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      print("RewardedVideoAd event $event");
      if (event == RewardedVideoAdEvent.rewarded) {
        setState(() {
          _coins += rewardAmount - 6;
        });
        print("Coins: $_coins");
      }
    };
  }

  playAd() {
    if (_coins == 0) {
      RewardedVideoAd.instance.show();
      print("Coins $_coins");
    } else {
      setState(() {
        _coins += -1;
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      print("Coins $_coins");
    }
  }

@override 
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("My App"),
        ),
        body:
        Center(
          child: FlatButton(
            child: Text("Play ad"),
            onPressed: () => playAd(),
          )
        ),
    );
  }

}

```

REPRODUCE: 
Setup admob environment as instructed at [Dart packages: firebase_admob](https://pub.dartlang.org/packages/firebase_admob)

FIX: 
```dart
playAd() {
    if (_coins == 0) {
      setState(() {
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      RewardedVideoAd.instance.show();
      print("Coins $_coins");
    } else {
      setState(() {
        _coins += -1;
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      print("Coins $_coins");
    }
  }
```

SUGGESTION: 
Add .load() to end of the streams, especially for `RewardedVideoAd`

_Originally posted by @JosephDunivan in https://github.com/flutter/flutter/issue_comments#issuecomment-444805824_

**Comment by JosephDunivan** [comment] 2018-12-06 19:17
Is it possible the admob example ad is set up for 1 ad every 60000 milliseconds in the settings?
Received error on Android
``` Console
I/Ads     ( 5084): Ad is not visible. Not refreshing ad.
I/Ads     ( 5084): Scheduling ad refresh 60000 milliseconds from now.
```

**Comment by JosephDunivan** [comment] 2018-12-08 05:37
I've been investigating this over and over again. 
```dart
RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
```
This function behaves like a future async await, but `RewardedVideoAd.instance.show();` does not wait for return value before execution. Results in execution error and in some cases infinite loops for state.

**Comment by kleinpetr** [comment] 2019-03-20 07:50
Use listener 

```
RewardedVideoAd.instance.listener = (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      if (event == RewardedVideoAdEvent.rewarded) {
        .....
      }

      if (event == RewardedVideoAdEvent.loaded) {
        setState(() {
          _videoLoaded = true;
        });
      }
    };
```

**Comment by JosephDunivan** [comment] 2019-03-20 08:21
.... Could you explain what setting the variable  `_videoLoaded` to `true` does? An actual call to admob needs to happen. The issue is `RewardedVideoAd.instance.show();` will allow itself to be called before an actually ad has loaded. Any method of loading the video does not stop this. The plugin needs to its listener to include the load response before proceeding to the show event. That's a job for the flutter plugin team and I would consider it a bug. It should be impossible to call .show before an ad is loaded. They shouldn't even be separate events (there would be no reason so show an ad that hasn't loaded).

**Comment by febg11** [comment] 2019-05-11 20:15
Using kleinpetr answer this works for me. 

  }else if(event == RewardedVideoAdEvent.loaded){
            RewardedVideoAd.instance.show();
  }

**Comment by JosephDunivan** [comment] 2019-05-11 21:14
The issue is the function will attempt to execute show before the load function actually returns its promise.  I’ll explain in more detail when I have time. Whether you use set state or a listen has no different affect.

**Comment by febg11** [comment] 2019-05-11 21:20
I never said the future not waiting was not a problem, but the using the RewardedVideoAd.instance.listener is a temporary solution that does work for me. The plugin is still in beta.

**Comment by kroikie** [comment] 2019-10-13 18:39
@JosephDunivan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/554. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:54
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-22 14:33
Hi @JosephDunivan
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-15 12:26
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 12:26 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, waiting for customer response

**Comment by nikhilishwarkulal** [comment] 2019-12-25 19:00
I found a possible solution. Im not sure if this is going to help anyways. I used 
"RewardedVideoAd.instance.show();" inside a loaded listener.

```
  RewardedVideoAd.instance.listener =
                                (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
                              if(event == RewardedVideoAdEvent.loaded){
                                RewardedVideoAd.instance.show();
                              }
                              if (event == RewardedVideoAdEvent.rewarded) {

                              
                            };
```

**Comment by teza222** [comment] 2020-04-09 02:05
I found the solution you have to add the targetInfo parameter

RewardedVideoAd.instance.load(myAdMobAdUnitId, targetingInfo);

RewardedVideoAd.instance.listener =(RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
         if(event == RewardedVideoAdEvent.loaded){
                 RewardedVideoAd.instance.show();
         }
         if (event == RewardedVideoAdEvent.rewarded) {

         }
       };


MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
  keywords: <String>['flutterio', 'beautiful apps'],
  contentUrl: 'https://flutter.io',
  birthday: DateTime.now(),
  childDirected: false,
  designedForFamilies: false,
  gender: MobileAdGender.male, // or MobileAdGender.female, MobileAdGender.unknown
  testDevices: <String>[], // Android emulators are considered test devices
);
