### ISSUE TITLE
Using providers dependency

### ISSUE THREAD

**Issue by DeepakGurav44** [flutter/flutter#78837] opened 2021-03-23 04:16 UTC
I/flutter (29016): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (29016): The following assertion was thrown building ChangeNotifierProvider<AddBidPageProvider>(message:
I/flutter (29016): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 6002 pos 12:
I/flutter (29016): 'renderObject.child == child': is not true.\nSee also: https://flutter.dev/docs/testing/errors,
I/flutter (29016): dirty, renderObject: RenderErrorBox#8551f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (29016): DETACHED):
I/flutter (29016): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4195 pos 12: '!_dirty': is not
I/flutter (29016): true.
I/flutter (29016): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (29016): more information in this error message to help you determine and fix the underlying cause.
I/flutter (29016): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (29016):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter (29016): The relevant error-causing widget was:
I/flutter (29016):   ChangeNotifierProvider<AddBidPageProvider>
I/flutter (29016):
lib/…/home/add_auction_page.dart:228
I/flutter (29016): When the exception was thrown, this was the stack:
I/flutter (29016): #2      Element.rebuild
package:flutter/…/widgets/framework.dart:4195
I/flutter (29016): #3      ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:4474
I/flutter (29016): #4      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4469
I/flutter (29016): #5      Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
I/flutter (29016): #6      Element.updateChild
package:flutter/…/widgets/framework.dart:3303
I/flutter (29016): #7      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4520
I/flutter (29016): #8      Element.rebuild
package:flutter/…/widgets/framework.dart:4189
I/flutter (29016): #9      StatelessElement.update
package:flutter/…/widgets/framework.dart:4576
I/flutter (29016): #10     Element.updateChild
package:flutter/…/widgets/framework.dart:3293

**Comment by pedromassangocode** [comment] 2021-03-23 07:28
Hi @DeepakGurav44 
From what I can see, the issue is related to a 3rd party package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-23 07:28 UTC
Labels: in triage
