### ISSUE TITLE
TextField does not work with multiple Navigator

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#12397] opened 2017-10-04 07:46 UTC
## Steps to Reproduce

- Tap the TextField and enter text.
- Change tab to `Right`
- Tap the TextField and enter text.
- Change tab to `Left`
- Tap the TextField
  - Android sim: Keyboard does not open, text selection works.
  - iOS sim: Can not focus to the TextField.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(new MaterialApp(
    home: new CupertinoTabScaffold(
      tabBar: new CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          new BottomNavigationBarItem(
            icon: new Icon(Icons.directions_car),
            title: new Text('Left'),
          ),
          new BottomNavigationBarItem(
            icon: new Icon(Icons.directions_railway),
            title: new Text('Right'),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return new MaterialApp(
          home: new Scaffold(
            appBar: new AppBar(
              title: new Text(index == 0 ? 'Left' : 'Right'),
            ),
            body: new Container(
              child: new TextField(),
            ),
          ),
        );
      },
    ),
  ));
}
```

When using CupertinoTabBar and BottomNavigationBar, multiple Navigators often required for each tabs to push pages.

In the example, I use MaterialApp because it includes Navigator.

## Logs

No exception.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 7bfa3c5676 (31 hours ago), 2017-10-02 17:32:00 -0700
    • Engine revision e3404b81a5
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34
```

**Comment by eseidelGoogle** [comment] 2018-01-18 04:12
@xster did a bunch of work recently on multiple-navigator setups, specifically for handling iOS style navigations and may have some updates here?

**Comment by xster** [comment] 2018-01-18 20:44
Thanks for catching. There's indeed something broken. I can reproduce.

**Comment by pedia** [comment] 2018-02-01 07:09
How about this issue now?

**Comment by xster** [comment] 2018-02-01 08:42
The issue is observed in the focus node mechanism. Though I have no solution currently. 

@pedia, did you notice other navigation issues or is it text input related as well?

**Comment by pedia** [comment] 2018-02-01 09:43
@xster I am not sure.
I have tried saving all FocusNode, and call 
```dart
FocusScope.of(context).requestFocus();
```

got:
```
When the exception was thrown, this was the stack:
#2      FocusScopeNode._setFocus (package:flutter/src/widgets/focus_manager.dart:289:12)
#3      FocusScopeNode.requestFocus (package:flutter/src/widgets/focus_manager.dart:253:5)
#4      FocusM.onChange (/Users/odd/wa/flutter/offer/lib/t.dart:35:35)
#5      FocusWrap.onChange (/Users/odd/wa/flutter/offer/lib/t.dart:19:12)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:140:21)
#7      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:103:5)
#8      FocusManager._update (package:flutter/src/widgets/focus_manager.dart:450:20)
(elided 4 frames from class _AssertionError and package dart:async)
```

**Comment by xster** [comment] 2018-02-02 01:07
Yes, it's the same issue as the text input focus

**Comment by xster** [comment] 2018-02-02 03:02
Fix is on the way

Small note: @najeira, you can use a [CupertinoTabView](https://docs.flutter.io/flutter/cupertino/CupertinoTabView-class.html) instead of putting a whole MaterialApp inside of each `tabBuilder`

**Comment by pedia** [comment] 2018-02-02 08:26
@xster The unmerged PR worked for me.

**Comment by pedia** [comment] 2018-02-19 13:10
Will this PR be merged?

**Closed** 2018-02-21 20:51 UTC
Labels: prod: framework, prod: routes, prod: text input, waiting for PR to land (fixed)

**Comment by dvaldivia** [comment] 2019-01-21 00:34
Issue is still happening, I reported it on #25933 

On 1.0.0 is quite random, on 1.1.9 is happening a lot.
