### ISSUE TITLE
Custom font not rendering bold font weight in iOS 14.5

### ISSUE THREAD

**Issue by burhanrashid52** [flutter/flutter#87551] opened 2021-08-03 05:20 UTC
## Steps to Reproduce

1. Creat flutter count app.
2. Update the main.dart with following code.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Demo"),
        ),
        body: Center(
          child: Column(
            children: [
              Text(
                '𝒮𝒽𝓇𝓊𝓉𝒽𝒾',
                style: TextStyle(
                  fontWeight: FontWeight.normal,
                ),
              ),
              Text(
                '𝒮𝒽𝓇𝓊𝓉𝒽𝒾',
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
``` 

</details>

| **Expected results:** The text should render bold font as it does in Android. It works fine in android but not on iOS | **Actual results:** custom font bold version is not visible on iOS |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/14251963/127961885-efb94b37-d916-4d55-939e-d7dca62439fd.png" height="450" /> | <img src="https://user-images.githubusercontent.com/14251963/127961941-161f2675-d39f-48b5-b3f9-f46a024ae144.png" height="450" /> |

**Comment by TahaTesser** [comment] 2021-08-03 11:21
Hi @burhanrashid52 
This is a duplicate of https://github.com/flutter/flutter/issues/62001, I can reproduce on iOS & macOS, there are other issue on web and Linux

Closing as duplicate of https://github.com/flutter/flutter/issues/62001

**Closed by TahaTesser** 2021-08-03 11:21 UTC
Labels: in triage
