### ISSUE TITLE
curser not work right with arabic (flutter web)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#52654] opened 2020-03-16 07:13 UTC
It works well in English but bad Arabic 
![ezgif-7-28faf42ecc4e](https://user-images.githubusercontent.com/31797198/76731385-010a5180-6766-11ea-99c6-99c783f692a6.gif)

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
    • Flutter version 1.14.6 at C:\flutter\flutter
    • Framework revision fabeb2a16f (7 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

</details>

**Comment by TahaTesser** [comment] 2020-03-16 07:43
Hi @mahmoudsalah37 

You need to set `textDirection: TextDirection.rtl` for Arabic

### Check out this code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(
            textDirection: TextDirection.rtl,
          ),
        ),
      ),
    );
  }
}

```

**Comment by mahmoudsalah37** [comment] 2020-03-16 12:37
> Hi @mahmoudsalah37
> 
> You need to set `textDirection: TextDirection.rtl` for Arabic
> 
> ### Check out this code sample
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Material App',
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Material App Bar'),
>         ),
>         body: Center(
>           child: TextField(
>             textDirection: TextDirection.rtl,
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
when I used rtl with (English and Arabic) cursor become so bad like in below GIF:-
---------------------------------------------------------------------
I want cursor work well with any text language and direction.
![2](https://user-images.githubusercontent.com/31797198/76758855-38dbbe00-6793-11ea-9d50-ad30ff0ef31c.gif)

**Comment by TahaTesser** [comment] 2020-03-16 14:38
Duplicate of [#47745](https://github.com/flutter/flutter/issues/47745)
Please follow up this issue 
Thank you

**Closed by TahaTesser** 2020-03-16 14:38 UTC
Labels: in triage
