### ISSUE TITLE
[url_launcher][Android]  When using gestures navigation, web browser returns to the application will have a black screen.

### ISSUE THREAD

**Issue by WingCH** [flutter/flutter#61072] opened 2020-07-08 06:43 UTC
```yaml
url_launcher: ^5.5.0
```
```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            onPressed: _launchURL,
            child: Text('Show Flutter homepage'),
          ),
        ),
      ),
    );
  }
}

_launchURL() async {
  const url = 'https://flutter.dev';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

```
> Android 10

When using gestures navigation, web browser returns to the application will have a `black screen`.
[![Alt text](https://img.youtube.com/vi/xbkrorFRXAU/0.jpg)](https://www.youtube.com/watch?v=xbkrorFRXAU)

Traditional Android navigation is normal.
[![Alt text](https://img.youtube.com/vi/vtjRiFo4KUY/0.jpg)](https://www.youtube.com/watch?v=vtjRiFo4KUY)

iOS is also normal

**Comment by darshankawar** [comment] 2020-07-08 07:11
Hi @WingCH,
Can you please provide a video or gif showing the issue ? When I tap on `Show Flutter homepage`, it opens `flutter.dev` website and then I opened the side bar navigation as shown below, then what's the next step to replicate the issue ?

![61072](https://user-images.githubusercontent.com/67046386/86888656-2b6a8b00-c118-11ea-97d0-a36ed48fadd8.png)

**Comment by WingCH** [comment] 2020-07-08 07:14
Thanks for your quick help.

When using gestures navigation, web browser returns to the application will have a black screen.
> https://www.youtube.com/watch?v=xbkrorFRXAU

Traditional Android navigation is normal.
> https://www.youtube.com/watch?v=vtjRiFo4KUY

**Comment by darshankawar** [comment] 2020-07-08 07:36
Hi @WingCH,
I can't replicate the issue (or not sure where exactly do you see the black screen). I tried it on latest dev channel and with latest version of `webview_flutter`. 

[61072_gest.mp4.zip](https://github.com/flutter/flutter/files/4889132/61072_gest.mp4.zip)

**Comment by WingCH** [comment] 2020-07-08 07:47
Please try swipe bottom bar to navigation.

> https://photos.app.goo.gl/13UccX11VypHTn358

**Comment by darshankawar** [comment] 2020-07-08 09:26
Issue replicable on Samsung S10 (OS 10) device (ie device that has gesture navigations). When `swipe from bottom` gesture is selected from Phone Settings -> Display -> Navigationbar -> Full Screen gestures (more options) and when user swipes from web browser to flutter screen, a black screen flashes.
I tested on latest dev channel and with latest version of `url_launcher` plugin. (also observed on previous version of plugin).

[61072.mp4.zip](https://github.com/flutter/flutter/files/4889783/61072.mp4.zip)

**Comment by exaby73** [comment] 2022-12-02 13:20
I cannot reproduce this issue on `Master (3.7.0-2.0.pre.9)`. If you can reproduce this issue, please comment and I can reopen the issue. Closing as fixed for the same reason

**Closed by exaby73** 2022-12-02 13:20 UTC
Labels: e: device-specific, platform-android, framework, engine, plugin, p: first party, f: gestures, p: url_launcher, has reproducible steps, P4, found in release: 1.20
