### ISSUE TITLE
a problem about TextField

### ISSUE THREAD

**Issue by wulongfang** [flutter/flutter#47973] opened 2019-12-30 09:34 UTC
```
 @override
  Widget build(BuildContext context) {
    final textFieldWidth = max(_minWidth, _textFieldWidth);
    final screenWidth = MediaQuery.of(context).size.width;
    widget.controller.text = "bbbbb";
    Log.log("min height = $_minHeight");
    return Container(
      height: _minHeight,
      width: textFieldWidth,
      decoration: BoxDecoration(
        color: Color(0xff00ff00),
      ),
      child:  TextField(
          maxLines: 1,
          focusNode: _focusNode,
          textAlign: TextAlign.center,
          controller: widget.controller,
          style: textStyle,
          cursorWidth: 1,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
              hintStyle: textStyle,
              hintText: "aaaaa",
              border: InputBorder.none
          )
      ),
    );
  }
```

above is the code .
but the text is above TextField area  instead of in TextField area.
when i delete hintText：“aaaaa” code .it turns out ok

**Comment by iapicca** [comment] 2019-12-30 13:42
Hi  @wulongfang 
I'm not sure to understand what behavior is unexpected,
does this code represent the issue

<details>
	<summary>code sample</summary>

```dart 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String _fromInit = 'from init';
  static const String _fromBuild = 'from build';
  static const String _hint = 'hint text';

  static TextEditingController _controller;
  static TextEditingController _controller2;

  @override
  void initState() {
    _controller = TextEditingController();
    _controller2 = TextEditingController();
    _controller.text = _fromInit;
    super.initState();
  }

  @override
  void dispose() {
    _controller?.dispose();
    _controller = null;
    _controller2?.dispose();
    _controller2 = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print(_controller.text);
    _controller.text = _fromBuild;
    print(_controller.text);
    return Scaffold(
      body: Column(
        children: <Widget>[
        ListTile(
            title: TextField(
              textAlign: TextAlign.center,
              controller: _controller,
              decoration: InputDecoration(
                hintText: _hint,
              ),
            ),
            trailing: IconButton(
              icon: Icon(Icons.delete),
              onPressed: () => _controller.clear(),
            ),
          ),
          ListTile(
            title: TextField(
              textAlign: TextAlign.center,
              controller: _controller2,
              decoration: InputDecoration(
                hintText: _hint,
              ),
            ),
            trailing: IconButton(
              icon: Icon(Icons.delete),
              onPressed: () => _controller2.clear(),
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

thank you

**Comment by VladyslavBondarenko** [comment] 2020-02-14 15:21
@wulongfang 
I hope you've solved the issue.
Closing as the issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Closed by VladyslavBondarenko** 2020-02-14 15:21 UTC
Labels: a: text input, f: material design, framework, waiting for customer response
