### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart':

### ISSUE THREAD

**Issue by GattoExpress999** [flutter/flutter#115915] opened 2022-11-23 12:23 UTC
I had to reinstall Flutter, Android Studio, Sdk, recreate phone emulator, recreate all my Flutter project.

I reinstalled everything to have a new, perfectly working environment.

My app works, but I see that error in log. It is linked to locale data and my app is not able to read the correct locale info from device.

## Steps to Reproduce

Just running my app.

**Expected results:** 

No error

**Actual results:** 

```
Launching lib\0_main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
D/FlutterLocationService( 6491): Creating service.
D/FlutterLocationService( 6491): Binding to location service.
E/flutter ( 6491): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart': Failed assertion: line 1840 pos 15: '<optimized out>': is not true.
E/flutter ( 6491): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6491): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6491): #2      new Locale.fromSubtags (dart:ui/platform_dispatcher.dart:1840:15)
E/flutter ( 6491): #3      PlatformDispatcher._updateLocales (dart:ui/platform_dispatcher.dart:762:29)
E/flutter ( 6491): #4      _updateLocales (dart:ui/hooks.dart:64:31)
E/flutter ( 6491): 
Debug service listening on ws://127.0.0.1:58700/eZdECN4hxJo=/ws
Syncing files to device Android SDK built for x86...
E/flutter ( 6491): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart': Failed assertion: line 1840 pos 15: '<optimized out>': is not true.
E/flutter ( 6491): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6491): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6491): #2      new Locale.fromSubtags (dart:ui/platform_dispatcher.dart:1840:15)
E/flutter ( 6491): #3      PlatformDispatcher._updateLocales (dart:ui/platform_dispatcher.dart:762:29)
E/flutter ( 6491): #4      _updateLocales (dart:ui/hooks.dart:64:31)
E/flutter ( 6491): 
I/zygote  ( 6491): Do partial code cache collection, code=24KB, data=27KB
I/zygote  ( 6491): After code cache collection, code=24KB, data=27KB
I/zygote  ( 6491): Increasing code cache capacity to 128KB
I/zygote  ( 6491): Do partial code cache collection, code=61KB, data=50KB
I/zygote  ( 6491): After code cache collection, code=61KB, data=50KB
I/zygote  ( 6491): Increasing code cache capacity to 256KB
```

<details>
<summary>Code sample</summary>

```
```

</details>

<details>
  <summary>Logs</summary>

```
```

flutter analyze bar spins for 15 min without output.

```
```

```
[√] Flutter (Channel master, 3.6.0-7.0.pre.18, on Microsoft Windows [Versione 10.0.19044.2251], locale it-IT)
    • Flutter version 3.6.0-7.0.pre.18 on channel master at C:\Users\Utente\Desktop\Cestino2\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2921ca0c48 (33 hours ago), 2022-11-21 21:43:26 -0500
    • Engine revision 8dd8e092e4
    • Dart version 2.19.0 (build 2.19.0-415.0.dev)
    • DevTools version 2.19.0

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Utente\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\Utente\Desktop\Cestino2\Android 2\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\Utente\Desktop\Cestino2\Android 2\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Versione 10.0.19044.2251]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment] 2022-11-24 05:30
Hi @GattoExpress999 
Does this issue happen on the Flutter default sample project (counter app)? If not so, can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by GattoExpress999** [comment] 2022-11-24 09:05
Yes it happens with Flutter default sample project as well, tested right now, this is the log:

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/flutter (12031): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart': Failed assertion: line 1840 pos 15: '<optimized out>': is not true.
E/flutter (12031): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (12031): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (12031): #2      new Locale.fromSubtags (dart:ui/platform_dispatcher.dart:1840:15)
E/flutter (12031): #3      PlatformDispatcher._updateLocales (dart:ui/platform_dispatcher.dart:762:29)
E/flutter (12031): #4      _updateLocales (dart:ui/hooks.dart:64:31)
E/flutter (12031): 
E/flutter (12031): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart': Failed assertion: line 1840 pos 15: '<optimized out>': is not true.
E/flutter (12031): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (12031): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (12031): #2      new Locale.fromSubtags (dart:ui/platform_dispatcher.dart:1840:15)
E/flutter (12031): #3      PlatformDispatcher._updateLocales (dart:ui/platform_dispatcher.dart:762:29)
E/flutter (12031): #4      _updateLocales (dart:ui/hooks.dart:64:31)
E/flutter (12031): 
Debug service listening on ws://127.0.0.1:51456/ImVCkDBlb6o=/ws
Syncing files to device Android SDK built for x86...
I/zygote  (12031): Do partial code cache collection, code=24KB, data=27KB
I/zygote  (12031): After code cache collection, code=24KB, data=27KB
I/zygote  (12031): Increasing code cache capacity to 128KB
I/zygote  (12031): Do partial code cache collection, code=61KB, data=50KB
I/zygote  (12031): After code cache collection, code=61KB, data=50KB
I/zygote  (12031): Increasing code cache capacity to 256KB
D/EGL_emulation(12031): eglMakeCurrent: 0xa7b846c0: ver 2 0 (tinfo 0x9327f5d0)

```

**Comment by huycozy** [comment] 2022-11-24 12:29
@GattoExpress999 thanks for your response.
From the log, I can see you are running app on an emulator. Can you try running app on a physical device if possible? Also, please provide the output of `flutter run -v`. Thank you!

**Comment by GattoExpress999** [comment] 2022-11-25 09:49
On physical device the bug doesn't come out:

```
Launching lib\main.dart on 5024D EEA in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Debug service listening on ws://127.0.0.1:53240/s6t13a5OXI8=/ws
Syncing files to device 5024D EEA...
D/        (13557): Gralloc Register  w:720, h:1440, f:0x1, usage:0xb00, ui64Stamp:34370, sSize:4149248, line = 2106
D/        (13557): Gralloc Register  w:720, h:1344, f:0x1, usage:0xb00, ui64Stamp:34382, sSize:3870720, line = 2106
D/        (13557): Gralloc UnRegister  w:720, h:1344, f:0x1, usage:0xb00, ui64Stamp:34346 line = 2218
D/        (13557): Gralloc UnRegister  w:720, h:1344, f:0x1, usage:0xb00, ui64Stamp:34382 line = 2218
```

**Comment by huycozy** [comment] 2022-11-25 12:21
@GattoExpress999 It seems the issue is only reproducible on emulator. I tried running the default Flutter project but can not reproduce this issue with `Pixel 4, API 31`. 

Can you retry again on the latest Flutter stable channel `3.3.9` to check if this is a regression issue? And retry with another Android emulator (different API versions) if possible? Thank you!

**Comment by GattoExpress999** [comment] 2022-11-25 15:04
```
Flutter channels:
  master
  beta
* stable

Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

```

News!
I tried to reinstall android 8 system image and guess what? the bug disappeared. It has been hard to understand how to because there was no way to delete image but it was always available as already downloaded. I found a "show package details" that permitted me to delete the image and so download it again.

Anyway, all the Flutter development environment is absolutelly crazy and awful. Android studio is complicated and it's not made for flutter. Very very annoying framework.

**Comment by huycozy** [comment] 2022-11-28 03:31
Perhaps the issue is only reproducible with your old system image on the Android emulator. Android emulator has quite a few limitations that even native Android app development also faces (see https://stackoverflow.com/a/1115855/5921933).

Closing the issue as it's solved. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2022-11-28 03:31 UTC
Labels: in triage
