### ISSUE TITLE
Running Gradle task 'assembleDebug' Forever...

### ISSUE THREAD

**Issue by rkmax** [flutter/flutter#50507] opened 2020-02-10 21:59 UTC
```
❯ flutter doctor -v                                                                                                                                              ─╯
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.utf8)
    • Flutter version 1.12.13+hotfix.7 at /opt/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/rkmax/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/rkmax/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.6015.39
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```
## Steps to Reproduce

1. Today just run flutter upgrade and the project stop woring
1. after executing flutter run, just get stuck

**Expected results:** 

the application get execute on the emulator like before

**Actual results:** 

get stuck on gradle task assumbleDebug

<details>

```
❯ flutter run --verbose                                                                                                                                          ─╯
[  +15 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[   +4 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] executing: /home/rkmax/Android/Sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /home/rkmax/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:2
[  +13 ms] /home/rkmax/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] Found plugin flutter_statusbar_manager at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_statusbar_manager-1.0.2/
[  +36 ms] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[   +1 ms] Found plugin shared_preferences_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+3/
[   +1 ms] Found plugin shared_preferences_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+2/
[  +30 ms] Found plugin flutter_statusbar_manager at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_statusbar_manager-1.0.2/
[  +11 ms] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[        ] Found plugin shared_preferences_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+3/
[        ] Found plugin shared_preferences_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+2/
[  +31 ms] Generating /home/rkmax/Development/my-project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +12 ms] ro.hardware = ranchu
[  +21 ms] Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with
           "--enable-software-rendering".
[   +9 ms] Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
[   +5 ms] executing: /home/rkmax/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -s flutter
[   +3 ms] executing: /home/rkmax/Android/Sdk/platform-tools/adb version
[  +15 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/rkmax/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/rkmax/Android/Sdk/platform-tools/adb start-server
[   +7 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /home/rkmax/Development/my-project/android/gradlew.
[   +4 ms] executing: /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java -version
[  +36 ms] Exit code 0 from: /home/rkmax/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +2 ms] executing: [/home/rkmax/Development/my-project/android/] /home/rkmax/Development/my-project/android/gradlew -Pverbose=true
-Ptarget=/home/rkmax/Development/my-project/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x64
assembleDebug
[+3423 ms] Starting a Gradle Daemon, 11 busy and 6 stopped Daemons could not be reused, use --status for details
[+3495 ms] > Configure project :shared_preferences_macos
[        ] WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
[        ] The current default is 'false'
```
</details>

**Comment by matheust3** [comment] 2020-02-11 04:16
Estou com o mesmo problema

https://github.com/flutter/flutter-intellij/issues/4366

**Comment by matheust3** [comment] 2020-02-11 05:46
It returned to work after changing the linux kernel. It seems that after the update linux-zen did not work well with the flutter. The build froze after a while. The solution was to switch to linux-lts.

**Comment by dnfield** [comment] 2020-02-11 07:17
Are you on Linux 5.5?  I strongly suspect this is a duplicate of https://github.com/flutter/flutter/issues/49185 - please feel free to comment here if that is not the case and I will reopen.

**Closed by dnfield** 2020-02-11 07:17 UTC
