### ISSUE TITLE
flutter doctor reports /user/bin/chromium is not executable - but project runs correctly

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#80234] opened 2021-04-11 20:47 UTC
I have just installed flutter 2.0. I setup a linux device and activated desktop support.

Running "flutter doctor" I receive an error which says I can find chromium at /usr/bin/chromium
but reports that it is not executable.   
However I can run "./chromium" when I am in "/usr/bin" dictory. When I am in my $HOME
directory and execute chromium, it runs correctly.
================================================
leemke@penguin:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /user/bin/chromium)
    ! /user/bin/chromium is not executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
leemke@penguin:~$ flutter devices
2 connected devices:

Google Pixelbook (mobile) • emulator-5554 • android-x64 • Android 9 (API 28)
Linux (desktop)           • linux         • linux-x64   • Linux
leemke@penguin~$ 
=================================
However,
created a new project (p1) ran "dart migrate,,," and "flutter run -d linux"

during initial run it reinstalled android tools v29. Version 30 was already installed
(latest android studio was just installed before installing flutter)

the application ran without a problem.

rerunning "flutter doctor" still report an error that chromium is not executable.
###

it seems the "flutter doctor" report is in error.

**Comment by iapicca** [comment] 2021-04-11 21:14
@leemke 
try adding to your path `export CHROME_EXECUTABLE=/usr/bin/chromium `

**Comment by pedromassangocode** [comment] 2021-04-12 12:15
Closing as duplicate of https://github.com/flutter/flutter/issues/77900.

**Closed by pedromassangocode** 2021-04-12 12:15 UTC
Labels: in triage

**Comment by leemke** [comment] 2021-04-12 15:22
Sorry. I did not mention it in my first post. 

I already have CHROME_EXECUTABLE set to "/usr/bin/chromium". Flutter did not detect
the executable without that setting.

**Comment by leemke** [comment] 2021-04-12 20:52
My mistake. I mis-coded the directory for chromium. I defined it as "/user/bin". And I thought I had coded /usr/bin
Thanks for your support
