### ISSUE TITLE
Support switching to Material Symbols New icon library

### ISSUE THREAD

**Issue by tarcyys** [flutter/flutter#152528] opened 2024-07-30 02:00 UTC
### Use case

Support switching to Material Symbols New icon library

These are two different official icon sets from Google, using the same underlying designs. Material Symbols is the current set, introduced in April 2022, built on variable font technology. Material Icons is the classic set, but no longer updated. More details below.

### Proposal

Support switching to Material Symbols New icon library

These are two different official icon sets from Google, using the same underlying designs. Material Symbols is the current set, introduced in April 2022, built on variable font technology. Material Icons is the classic set, but no longer updated. More details below.

**Comment by danagbemava-nc** [comment] 2024-07-30 07:12
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102560

**Closed by danagbemava-nc** 2024-07-30 07:12 UTC
Labels: in triage
