### ISSUE TITLE
Can't use firebase emulator in integration test

### ISSUE THREAD

**Issue by eyalkutz** [flutter/flutter#88278] opened 2021-08-16 14:05 UTC
## Steps to Reproduce

1. create a flutter project
2. add firebase
3. start the emulator
4. run the following before some test:
```dart
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // change host and port to match your firebase emulator
  const host = '192.168.0.110';
  firestore.useFirestoreEmulator(host, 8080);
  await auth.useAuthEmulator(host, 9099);
  functions.useFunctionsEmulator(host, 5001);
```

**Expected results:** 
I expected the app to connect to the emulator and run the tests
**Actual results:** 
I got an error:
```Unhandled Exception: Bad state: Can't call test() once tests have begun running.```
<details>
  <summary>Logs</summary>

I don't know how to produce logs for an integration test. I will edit the question if necessary
```
```

```
Analyzing filma...                                                      

   info - Duplicate import - integration_test\sign_in_test.dart:9:8 - duplicate_import
   info - Unused import: 'package:cached_network_image/cached_network_image.dart' - lib\customer\my_tickets.dart:2:8 - unused_import
   info - Unused import: 'package:filma/tmdb.dart' - lib\customer\my_tickets.dart:4:8 - unused_import
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was      
          deprecated after v1.26.0-18.0.pre. - lib\customer\order.dart:197:18 - deprecated_member_use
   info - The value of the local variable 'ref' isn't used - lib\manager\add_screening.dart:139:11 - unused_local_variable
   info - Unused import: 'package:animations/animations.dart' - lib\manager\change_permissions.dart:1:8 - unused_import
   info - Unused import: 'tmdb.dart' - lib\models.dart:8:8 - unused_import
   info - The operand can't be null, so the condition is always true - lib\models.dart:46:32 - unnecessary_null_comparison
   info - Unused import: 'package:cached_network_image/cached_network_image.dart' - lib\movie_tile.dart:6:8 - unused_import
   info - Unused import: 'tmdb.dart' - lib\movie_tile.dart:7:8 - unused_import
   info - Unused import: 'package:cached_network_image/cached_network_image.dart' - lib\screenings.dart:3:8 - unused_import
   info - Unused import: 'tmdb.dart' - lib\screenings.dart:12:8 - unused_import
   info - The value of the local variable 'userCredential' isn't used - lib\sign_in.dart:175:24 - unused_local_variable
   info - The value of the local variable 'userCredential' isn't used - lib\sign_in.dart:282:22 - unused_local_variable
   info - Unused import: 'package:flutter/material.dart' - test\widget_test.dart:8:8 - unused_import
   info - Unused import: 'package:flutter_test/flutter_test.dart' - test\widget_test.dart:9:8 - unused_import
   info - Unused import: 'package:filma/main.dart' - test\widget_test.dart:11:8 - unused_import

17 issues found. (ran in 46.4s)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-001)
    • Flutter version 2.2.3 at C:\developement\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\developement\AndroidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\developement\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\אייל קוץ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-08-16 14:27
Hi @eyalkutz 
I am not sure the Firebase emulator suppose to work with `integration_test`, have you tried using the emulator in the regular 
 test?
  
The issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-16 14:27 UTC
Labels: in triage

**Comment by eyalkutz** [comment] 2021-08-16 14:44
@TahaTesser according to the [docs](https://firebase.flutter.dev/docs/testing/testing#integration-tests-using-the-firestore-emulator) the emulator is supposed to work with integration tests.
I will open an issue in the FlutterFire repository
