### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by aidenlangley** [flutter/flutter#133065] opened 2023-08-22 18:16 UTC
## Command
```
flutter run -t lib/main.dev.dart -d chrome --dart-define=SUPABASE_URL=<cut> --dart-define=SUPABASE_ANON_KEY=<cut>
```

## Steps to Reproduce
1. Upgrade to latest flutter SDK.
2. Just from a regular development workflow

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1928:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2493:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2464:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:959:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:978:49)
#5      FlutterVmService._flutterToggle (package:flutter_tools/src/vmservice.dart:756:41)
#6      FlutterVmService.flutterToggleProfileWidgetBuilds (package:flutter_tools/src/vmservice.dart:791:9)
#7      ResidentHandlers.debugToggleProfileWidgetBuilds (package:flutter_tools/src/resident_runner.dart:896:33)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1831:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.0, on Arch Linux 6.4.11-arch2-1, locale en_GB.UTF-8)
    [32m•[39m Flutter version 3.13.0 on channel stable at /usr/local/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    [32m•[39m Engine revision 1ac611c64e
    [32m•[39m Dart version 3.1.0
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /home/aiden/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: /opt/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /usr/bin/chromium

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 15.0.7
    [32m•[39m cmake version 3.27.1
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Arch Linux 6.4.11-arch2-1
    [32m•[39m Chrome (web)    • chrome • web-javascript • Chromium 116.0.5845.96 Arch Linux

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8
### Plugins
app_links-3.4.3
path_provider-2.1.0
path_provider_android-2.1.0
path_provider_foundation-2.3.0
path_provider_linux-2.2.0
path_provider_windows-2.2.0
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.3
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
sign_in_with_apple-5.0.0
sign_in_with_apple_web-1.0.1
url_launcher-6.1.12
url_launcher_android-6.0.38
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.18
url_launcher_windows-3.0.7
webview_flutter-4.2.2
webview_flutter_android-3.9.3
webview_flutter_wkwebview-3.7.3

**Comment by darshankawar** [comment] 2023-08-23 06:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102994

**Closed by darshankawar** 2023-08-23 06:03 UTC
Labels: in triage
