### ISSUE TITLE
Can't build my first app 

### ISSUE THREAD

**Issue by satyam-442** [flutter/flutter#29119] opened 2019-03-10 04:33 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## command
flutter run
## exception
String: Exit code 1 from: E:\flutter\first_app\android\gradlew.bat -v:
Unzipping C:\Users\Son of lord shiva\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip to C:\Users\Son of lord shiva\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:249)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:180)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:97)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:90)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:84)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:86)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:270)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:401)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#28     new Future.sync (dart:async/future.dart:222)
#29     CommandRunner.run (package:args/command_runner.dart:109)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:49)
#39     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#40     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v0.2.9, on Microsoft Windows [Version 10.0.17134.590], locale en-IN)
    • Flutter version 0.2.9 at C:\flutter
    • Framework revision 487e6bc91e (11 months ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Son of lord shiva\AppData\Local\Android\sdk
    • Android NDK at C:\Users\Son of lord shiva\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • A37f • 73aa6858 • android-arm64 • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.
```

**Comment by habeebul** [comment] 2019-03-10 09:56
Looks like problem with zip file gradle-4.10.2-all.zip . Delete and download it again.
Or
Check you have access to this folder
 C:\Users\Son of lord shiva.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip

**Comment by jonahwilliams** [comment] 2019-10-15 19:31
Duplicate of https://github.com/flutter/flutter/issues/40517

**Closed by jonahwilliams** 2019-10-15 19:31 UTC
Labels: t: gradle, tool, ❖ platform-windows
