### ISSUE TITLE
widget inspector is not working 

### ISSUE THREAD

**Issue by uc-dve** [flutter/flutter#84774] opened 2021-06-17 13:36 UTC
## Steps to Reproduce

1. open command palette on Vscode and run Inspect Widget
2. after the widget inspector is open click on the simulator to inspect it.

It is giving the below error on debug console.

![image](https://user-images.githubusercontent.com/28289763/122406425-76368900-cf9e-11eb-981e-e6cdd37f7dcd.png)

below is mu flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/dhirooverma/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhirooverma/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A567039B-5E4A-4CA2-B71A-A5241E072492 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G73 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 91.0.4472.106

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-18 08:04
Hi @uc-dve 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by TahaTesser** [comment] 2021-07-01 10:38
This actually seems to be a Framework inspector issue, after this issue, similar issues were filed and I realized, it's not the plugin 


@uc-dve 
To address the issue, can you please copy/paste complete  logs instead of instead on the latest Flutter stable

**Comment by TahaTesser** [comment] 2021-07-23 12:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-23 12:59 UTC
