### ISSUE TITLE
[tool_crash] StateError: Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by shidarun1** [flutter/flutter#85609] opened 2021-06-30 10:36 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Cannot add event after closing
```
#0      _StreamController.add (dart:async/stream_controller.dart:553:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
#2      AppConnection.runMain (package:dwds/src/connections/app_connection.dart:33:22)
#3      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:669:25)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H114 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/shirun/development/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/shirun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ✗ Xcode 11.5.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
path_provider_linux-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.3
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
video_player-2.1.6
video_player_web-2.0.1
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by darshankawar** [comment] 2021-06-30 11:47
Closing this as duplicate of https://github.com/flutter/flutter/issues/59757

**Closed by darshankawar** 2021-06-30 11:47 UTC
