### ISSUE TITLE
flutter web - move between two monitors

### ISSUE THREAD

**Issue by fiurthorn** [flutter/flutter#90853] opened 2021-09-28 05:23 UTC
Hi,

writing a flutter web app on windows.
I have two monitors (external and laptop device).

moving the chrome debug view from one monitor to the other destroys the layout.

<img width="650" alt="flutter_web_ok" src="https://user-images.githubusercontent.com/13510039/135027508-d5a90f65-c446-44f9-8416-f6fadb9a0ab9.png">

<img width="542" alt="flutter_web_nok" src="https://user-images.githubusercontent.com/13510039/135027504-58db9edb-3af8-4670-a71d-4192f993a528.png">

move it back or start on the other monitor (include F5 reload) fix it.

**Comment by danagbemava-nc** [comment] 2021-09-28 08:59
Hi @fiurthorn 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by fiurthorn** [comment] 2021-09-28 09:41
main.dart

```dart
import 'package:flutter/material.dart';

void main() async => runApp(Example());

class Example extends StatelessWidget {
  Example({Key? key}) : super(key: key) {
    WidgetsFlutterBinding.ensureInitialized();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("title"),
        ),
        body: Align(
          alignment: const Alignment(0, -1 / 3),
          child: SingleChildScrollView(
            child: SizedBox(
              width: 400,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const SizedBox(height: 64.0),
                  Icon(
                    Icons.umbrella,
                    size: 100,
                    color: Theme.of(context).primaryColor,
                  ),
                  const SizedBox(height: 64.0),
                  TextFormField(),
                  const SizedBox(height: 8.0),
                  TextFormField(),
                  const SizedBox(height: 8.0),
                  TextFormField(),
                  const SizedBox(height: 8.0),
                  Row(
                    children: [
                      TextButton(
                        onPressed: () {},
                        child: const Text("Forgot password"),
                      ),
                      const Expanded(child: SizedBox()),
                      TextButton(
                        onPressed: () {},
                        child: const Text("Register a Team"),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8.0),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

index.html: 

```html
<!DOCTYPE html>
<html>

<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="purchase2pay_client">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <title>purchase2pay_client</title>
  <link rel="manifest" href="manifest.json">
</head>

<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
         application. For more information, see:
         https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>
</body>

</html>
```

* [flutter_doctor.txt](https://github.com/flutter/flutter/files/7242825/flutter_doctor.txt)
* [flutter_logfile.txt](https://github.com/flutter/flutter/files/7242826/flutter_logfile.txt)

<img width="481" alt="flutter_web_nok" src="https://user-images.githubusercontent.com/13510039/135063130-119d4c33-1bed-4298-9d1a-64f884ed193f.png">

<img width="578" alt="flutter_web_ok" src="https://user-images.githubusercontent.com/13510039/135063131-7a605251-f863-4224-90a5-9a6cbd937cdd.png">

**Comment by fiurthorn** [comment] 2021-09-28 09:43
@danagbemava-nc i think it's the difference resolution, dpi, etc. Settings between the monitors.

**Comment by danagbemava-nc** [comment] 2021-09-28 11:49
Hi @fiurthorn, this issue is known and is being tracked [here](https://github.com/flutter/flutter/issues/77605).

Kindly follow up there for more information. 

Closing as duplicate of #77605

**Closed by danagbemava-nc** 2021-09-28 11:49 UTC
Labels: in triage
