### ISSUE TITLE
weird behaviours in growable lists with different types both extends the same topclass

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#130673] opened 2023-07-16 02:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try 1-4 has code sample and log below in `Code samples` section individually.

### Try 1 `var`

exception on compile: 

```log
[ +312 ms] lib/ui/chips_chooser.dart:67:52: Error: The argument type 'ActionChip' can't be assigned to the parameter type 'Chip'.
[        ]  - 'ActionChip' is from 'package:flutter/src/material/action_chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/action_chip.dart').
[        ]  - 'Chip' is from 'package:flutter/src/material/chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/chip.dart').
[        ]         child: Wrap(children: selectedChoices..add(editButton)));
```

### Try 2 `List<Chip>`

same exception will be thrown if `var` is changed to `List<Chip>`.

### Try 3 `List<Widget>` or `List<StatelessWidget>`

if change `var` to `List<Widget>` or `List<StatelessWidget>` which both chips extends, compile passed, but runtime error: 

```log
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building ChipsChooser(dirty, state: ChipsChooserState#6cc02):
type 'ActionChip' is not a subtype of type 'Chip' of 'value'

The relevant error-causing widget was: 
  Wrap ChipsChooser:file:///Users/hoarfroster/Desktop/hoarfroster_flutter/lib/screen/posts/editor_content/editor.dart:149:12
When the exception was thrown, this was the stack: 
#0      List.add (dart:core-patch/growable_array.dart)
#1      ChipsChooserState.build (package:hoarfroster_flutter/ui/chips_chooser.dart:67:48)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093:32)
#9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
===================================================================
```

#### Try 4 `as Widget`

compile passed, run passed. While flutter extension in AndroidStudio will have analysis warning: `Unnecessary Cast`.

<img width="691" alt="image" src="https://github.com/flutter/flutter/assets/41184947/9977b38f-3979-4448-a13e-3dc7828814c6">

### Expected results

step 1 and step 3 and step 4 should have the same output.

### Actual results

see steps to reproduce

### Code sample

<details><summary>Code sample for try 1</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  var chips = data.map((e) => Chip(label: Text(e.toString()))).toList();
  chips.add(ActionChip(onPressed: (){}, label: Text("edit")));
}
```

```log
lib/main.dart:7:13: Error: The argument type 'ActionChip' can't be assigned to the parameter type 'Chip'.
 - 'ActionChip' is from 'package:flutter/src/material/action_chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/action_chip.dart').
 - 'Chip' is from 'package:flutter/src/material/chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/chip.dart').
  chips.add(ActionChip(onPressed: (){}, label: Text("edit")));
            ^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```
</details>

<details><summary>Code sample for try 2</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  List<Chip> chips2 = data.map((e) => Chip(label: Text(e.toString()))).toList();
  chips2.add(ActionChip(onPressed: (){}, label: Text("edit")));
}
```

```log
lib/main.dart:7:14: Error: The argument type 'ActionChip' can't be assigned to the parameter type 'Chip'.
 - 'ActionChip' is from 'package:flutter/src/material/action_chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/action_chip.dart').
 - 'Chip' is from 'package:flutter/src/material/chip.dart' ('/usr/local/Caskroom/flutter/3.10.2/flutter/packages/flutter/lib/src/material/chip.dart').
  chips2.add(ActionChip(onPressed: (){}, label: Text("edit")));
             ^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```
</details>

<details><summary>Code sample for try 3</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  List<Widget> chips3 = data.map((e) => Chip(label: Text(e.toString()))).toList();
  chips3.add(ActionChip(onPressed: (){}, label: Text("edit")));
}
```

```log
Building macOS application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'ActionChip' is not a subtype of type 'Chip' of 'value'
#0      List.add (dart:core-patch/growable_array.dart)
#1      main (package:tmp/main.dart:7:10)
#2      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Syncing files to device macOS...                                   222ms
```
</details>

<details><summary>Code sample for try 4</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  List<StatelessWidget> chips4 = data.map((e) => Chip(label: Text(e.toString()))).toList();
  chips4.add(ActionChip(onPressed: (){}, label: Text("edit")));
}
```

```log
Building macOS application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'ActionChip' is not a subtype of type 'Chip' of 'value'
#0      List.add (dart:core-patch/growable_array.dart)
#1      main (package:tmp/main.dart:7:10)
#2      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Syncing files to device macOS...                                   222ms
```
</details>

<details><summary>Code sample for try 5</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  var chips5 = data.map((e) => Chip(label: Text(e.toString())) as Widget).toList();
  chips5.add(ActionChip(onPressed: (){}, label: Text("edit")));
}
```

```log
Building macOS application...
Syncing files to device macOS...                                   222ms
```

Try 5 run successfully without any exception thrown.
</details>

### Screenshots or Video

not applicable

### Logs

see steps to reproduce

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-x64, locale
    en-US)
    • Flutter version 3.10.3 on channel stable at
      /usr/local/Caskroom/flutter/3.10.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (6 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

- Android Studio v231.8109.175.2311.10205233
  - flutter extension v74.0.4
  - dart extension v231.9065
</details>

**Comment by huycozy** [comment] 2023-07-17 10:54
Hi @PassionPenguin 
Your 1st sample code be converted to Dart as below:

<details>
<summary>Dart sample code</summary>

```dart
abstract class A {
}

class B extends A {
	final int counter;

  B({required this.counter});
}
class C extends A {
	final int counter;

  C({required this.counter});
}

void main() {
  var data = [1, 2, 3, 4, 5, 6];

  var chips = data.map((e) => B(counter: e)).toList();
	chips.add(C(counter: 1));
}

```
</details>

And you can see this belongs to Dart, not on framework. And I think it works as intended since Dart is type-safe. Please see https://dart.dev/language/type-system for more information or re-open the issue on [Dart SDK](https://github.com/dart-lang/sdk) for further questions. 

Closing the issue as it's not a framework issue.

**Closed by huycozy** 2023-07-17 10:54 UTC
Labels: in triage
