### ISSUE TITLE
Use RasterCache where possible even when we have embedded views enabled.

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#38903] opened 2019-08-20 18:20 UTC
We can still cache if we do not have any mutations to the embedded views.

**Comment by mklim** [comment] 2019-10-21 21:46
From an offline discussion, we can also avoid caching if there are no embedded views in the hierarchy, even if they're enabled in general. We'll need to check in `Preroll` or earlier. It may be also be possible to turn the cache on or off for a specific subtree depending on the presence of an embedded view.

/cc @cyanglaz @amirh

**Comment by mklim** [comment] 2019-10-30 22:28
@amirh and I have been debugging the breakage in flutter/engine#13360 a little bit to try and figure out what necessitated the rollback.

First, it is a real issue. The test (which was added after the patch landed) is catching a major rendering bug.

| Expected | Actual |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4615911/67902766-326fe100-fb27-11e9-8a5b-385fc0a0d31b.png" height="300" alt="expected"/> | <img src="https://user-images.githubusercontent.com/4615911/67902785-3d2a7600-fb27-11e9-9a7b-9495c6fe375c.png" height="300" alt="actual"/> |

Second, the patch itself _appears_ to be "working," at least it's doing everything I wrote it do. From what I can tell the issue is either a bug in the RasterCache or my assumptions about how caching a layer tree should work being wrong.

This is a slightly simplified version of the problem layer tree.

```
             +------+
             | Root |
             +-+--+-+
               |  |
        +------+  +-----+
        |               |
        v               v
+-------+------+    +---+----------+
| #3 (Opacity) |    | #6 (Opacity) |
+-------+------+    +------+-------+
        |                  |
        |                  |
        v                  |
+-------+------+   +-------+--------+
| #4 (Picture) |   | #10 (Transform)|
+--------------+   +----+--------+--+
                        |        |
                        |        |
               +--------+        +--------+
               |                          |
               v                          v
       +-------+----------+      +--------+-----+
       |#8 (Platform View)|      | #9 (Picture) |
       +------------------+      +--------------+

```

**Without this patch**, layers 4 and 10 both _almost_ try to prepare the RasterCache but decide not to based on platform views being enabled. Everything works.

**With this patch**, layer 4 succeeds in preparing the cache and gets and uses a  `RasterCacheResult` later. Layer 10 still decides not to prepare the cache with an entry since it has a PlatformView in its children. Then the test fails like the above images. I can avoid this failure if I manually patch `RasterCache::Get` to always fail to return a real result, so it's the actual use of the cache that's causing the issue and not any unforeseen side effects from preparing it.

@liyuqian do you mind taking a look and seeing if anything jumps out at you?

**Comment by mklim** [comment] 2019-10-31 23:22
Seems unlikely, but I'm starting to suspect that this is a bug in the test harness. I can't reproduce the failure if I copy the test case into an app and then run it on iOS. The buggy behavior appears to depend on the order of GL calls.

**Comment by liyuqian** [comment] 2019-11-05 18:17
Adding a little more details: Michael and I did a bunch of hacks around node `#4` and it suddenly changes how `#8, #9` are rendered. That shouldn't happen unless there's a bug in SwiftShader. That triggered us to question the SwiftShader and try to run the test directly on an iOS device. The test passed on iOS so we suspect the issue is in SwiftShader. @mklim : can you please link to the SwiftShader issue if you filed one?

**Comment by mklim** [comment] 2019-11-05 18:23
@liyuqian thanks for the extra context. I haven't filed a SwiftShader bug yet, sorry. I wanted to try and get this down to a really simple repro case first and so far I haven't had the time.

**Comment by mklim** [comment] 2019-11-06 01:02
This is an issue with GL, either GL itself or SwiftShader. @chinmaygarde helped us all look into this today by writing a copy of the test that renders on the CPU instead of using ShiftShader (flutter/engine#13700). I patched the raster cache PR on top of it without any changes (mklim/engine@33ae5e9aa626d4df89944940502aa82c9b66466c) and the software tests passed completely fine while the GL ones failed. I also verified that the software backend was using the raster cache by modifying the raster cache tests to run on the software backend as well, and they still passed (mklim/engine@aba9ed1b73d97eafeee5ce2b4ff8716cfeed1ddc).

@chinmaygarde pointed out that this could be a broader issue having to do with GL itself and not just something localized to the test harness, so the PR is still too risky to land. He's offered to spend some time debugging this more tomorrow to try and root cause it further.

**Closed** 2019-11-09 01:14 UTC
Labels: a: platform-views, engine, ⌺‬ platform-ios
