### ISSUE TITLE
Inspected variable not keeping the old variable values until expanded in VSCode

### ISSUE THREAD

**Issue by pinguluk** [flutter/flutter#90332] opened 2021-09-18 21:33 UTC
## Steps to Reproduce

1. Have an object (a list for example with 10 items)
2. Use ```inspect(list)```
3. Remove some items from the list (6 for example)
4. Expand the ```inspected variable``` from the VSCode

**Expected results:**
```
<inspected variable>
  ...
  _value:List (10 items)
  ...
  length: 10
  ...
```

**Actual results:**
```
<inspected variable>
  ...
  _value:List (4 items)
  ...
  length: 4
  ...
```

After expanding the inspected variable and you remove another items from the list, the expanded inspected variable is remaining the same (even if you shrink back and expand again the inspected variable in the debug console).

If you do ```inspect(list.length)``` instead before you remove any items and then you remove some, you'll see that the list.length is keeping the original value, which is correct.

Basically if you inspect an **object**, the data from it will be reflected and keeped in the debug console, **only** when you expand it for the first time. Until you expand for the first time, the _inspected variable_ (object) will keep changing, until you expand it at least once.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale ro-RO)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pinguluk\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\pinguluk\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\pinguluk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-09-20 10:23
Hi @pinguluk 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-20 10:23 UTC
Labels: in triage
