### ISSUE TITLE
[google_maps_flutter] Different polygons beahviour between iOS and Android

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter#133336] opened 2023-08-25 17:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create new empty flutter project
2. Add `google_maps_flutter: ^2.4.0` package
3. Include specific custom platform code as per [documentation](https://pub.dev/packages/google_maps_flutter)
4. Execute the example code on iOS and on Android

### Expected results

We expect that both platforms provide the same UI result in terms of polygons render.

### Actual results

On iOS the polygon is rendered correctly in terms of fill color and area. On Android polygon hasn't the fill color and the area is completely different.

iOS
![image](https://github.com/flutter/flutter/assets/12233746/bf7cb193-f062-46a4-a207-3da87801f24d)

Android
![image](https://github.com/flutter/flutter/assets/12233746/0b4551f9-8050-4280-925e-5624f3325669)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(45.6971495, 10.9738558),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: GoogleMap(
          mapType: MapType.hybrid,
          initialCameraPosition: _kGooglePlex,
          polygons: {
            Polygon(
                polygonId: PolygonId('testPolygon3'),
                fillColor: Colors.red.withOpacity(0.5),
                strokeColor: Colors.red,
                points: const [
                  LatLng(45.6971495, 10.9738558),
                  LatLng(45.6964301, 10.9738558),
                  LatLng(45.695351, 10.9737699),
                  LatLng(45.6948114, 10.9725683),
                  LatLng(45.6946915, 10.9712808),
                  LatLng(45.6945117, 10.9698217),
                  LatLng(45.6945117, 10.9683626),
                  LatLng(45.6944517, 10.9663885),
                  LatLng(45.6936124, 10.9650152),
                  LatLng(45.6924733, 10.9645002),
                  LatLng(45.691574, 10.9642427),
                  LatLng(45.6906747, 10.9639852),
                  LatLng(45.6894755, 10.9637277),
                  LatLng(45.688816, 10.9633844),
                  LatLng(45.6877967, 10.9627836),
                  LatLng(45.6868374, 10.9621828),
                  LatLng(45.6856981, 10.9613245),
                  LatLng(45.6839592, 10.9608095),
                  LatLng(45.6850985, 10.9596937),
                  LatLng(45.6856981, 10.9578913),
                  LatLng(45.6852784, 10.9572046),
                  LatLng(45.6838393, 10.9571188),
                  LatLng(45.6834795, 10.9556597),
                  LatLng(45.6831797, 10.9537714),
                  LatLng(45.6821603, 10.9524839),
                  LatLng(45.6808411, 10.9507673),
                  LatLng(45.6799416, 10.9501665),
                  LatLng(45.6788622, 10.9500807),
                  LatLng(45.677363, 10.9513681),
                  LatLng(45.6762235, 10.9541147),
                  LatLng(45.6767633, 10.9551447),
                  LatLng(45.6776628, 10.9542864),
                  LatLng(45.6789821, 10.9533422),
                  LatLng(45.6796418, 10.9522264),
                  LatLng(45.681021, 10.9534281),
                  LatLng(45.6815607, 10.9547155),
                  LatLng(45.6818005, 10.9569471),
                  LatLng(45.6821004, 10.9581487),
                  LatLng(45.6829998, 10.9586637),
                  LatLng(45.6815607, 10.960037),
                  LatLng(45.6805413, 10.9620111),
                  LatLng(45.6790421, 10.9626978),
                  LatLng(45.6775429, 10.9630411),
                  LatLng(45.6764634, 10.9641569),
                  LatLng(45.6758037, 10.9657877),
                  LatLng(45.6750841, 10.967161),
                  LatLng(45.6755638, 10.9687059),
                  LatLng(45.6764634, 10.9697359),
                  LatLng(45.677363, 10.9708517),
                  LatLng(45.6783824, 10.9709375),
                  LatLng(45.6798217, 10.9715383),
                  LatLng(45.6799416, 10.9728258),
                  LatLng(45.6801215, 10.9746282),
                  LatLng(45.6802414, 10.9760874),
                  LatLng(45.6807212, 10.977804),
                  LatLng(45.6819205, 10.9793489),
                  LatLng(45.6832397, 10.9799497),
                  LatLng(45.6841991, 10.9806364),
                  LatLng(45.6850985, 10.9815805),
                  LatLng(45.6867175, 10.9819238),
                  LatLng(45.6878567, 10.9815805),
                  LatLng(45.6865975, 10.9797781),
                  LatLng(45.6879766, 10.9792631),
                  LatLng(45.6891158, 10.9784906),
                  LatLng(45.6904948, 10.9777181),
                  LatLng(45.691514, 10.9785764),
                  LatLng(45.6936124, 10.9781473),
                  LatLng(45.6945117, 10.977289),
                  LatLng(45.6957706, 10.9766882),
                  LatLng(45.6970895, 10.9760874),
                  LatLng(45.6973893, 10.9745424),
                  LatLng(45.7172886, 10.9747141),
                  LatLng(45.7169889, 10.9724825),
                  LatLng(45.7169889, 10.9698217),
                  LatLng(45.71609, 10.9679334),
                  LatLng(45.7156106, 10.9660452),
                  LatLng(45.714412, 10.9648435),
                  LatLng(45.7131534, 10.9625261),
                  LatLng(45.7122545, 10.961582),
                  LatLng(45.7114154, 10.9602945),
                  LatLng(45.7097972, 10.9572046),
                  LatLng(45.7094376, 10.9561746),
                  LatLng(45.7081789, 10.9534281),
                  LatLng(45.7072199, 10.9517114),
                  LatLng(45.7063208, 10.9481924),
                  LatLng(45.7056615, 10.9450167),
                  LatLng(45.7048224, 10.9414976),
                  LatLng(45.7041031, 10.9394377),
                  LatLng(45.703144, 10.9365194),
                  LatLng(45.7024247, 10.9338587),
                  LatLng(45.699967, 10.9300821),
                  LatLng(45.6974492, 10.929138),
                  LatLng(45.6957706, 10.928108),
                  LatLng(45.6939122, 10.9262197),
                  LatLng(45.6821004, 10.9239881),
                  LatLng(45.6798816, 10.9147184),
                  LatLng(45.6785024, 10.9125727),
                  LatLng(45.6768232, 10.9106844),
                  LatLng(45.6748442, 10.9087961),
                  LatLng(45.6726851, 10.9091394),
                  LatLng(45.6712457, 10.9097402),
                  LatLng(45.6697463, 10.9105127),
                  LatLng(45.6679469, 10.911886),
                  LatLng(45.6659676, 10.913431),
                  LatLng(45.664408, 10.9153192),
                  LatLng(45.6627284, 10.9202974),
                  LatLng(45.6615287, 10.9247606),
                  LatLng(45.6604489, 10.9293955),
                  LatLng(45.6594891, 10.9339445),
                  LatLng(45.6581694, 10.9393518),
                  LatLng(45.6587093, 10.944845),
                  LatLng(45.6588292, 10.9518831),
                  LatLng(45.6585293, 10.9551447),
                  LatLng(45.6582893, 10.9603803),
                  LatLng(45.6579894, 10.9675043),
                  LatLng(45.6582293, 10.9726541),
                  LatLng(45.6578694, 10.9769457),
                  LatLng(45.6572095, 10.9817522),
                  LatLng(45.6574495, 10.9875028),
                  LatLng(45.6570295, 10.9920519),
                  LatLng(45.6571495, 10.9956568),
                  LatLng(45.6587093, 10.99909),
                  LatLng(45.6604489, 11.0008066),
                  LatLng(45.6637482, 11.0020082),
                  LatLng(45.6674071, 11.0049265),
                  LatLng(45.670526, 11.0061281),
                  LatLng(45.6743644, 11.0089605),
                  LatLng(45.677243, 11.0089605),
                  LatLng(45.6791021, 11.0089605),
                  LatLng(45.6815007, 11.0090463),
                  LatLng(45.6858181, 11.0095613),
                  LatLng(45.6922934, 11.009733),
                  LatLng(45.6948714, 11.010248),
                  LatLng(45.6978689, 11.010248),
                  LatLng(45.7036235, 11.0096472),
                  LatLng(45.7059013, 11.0093897),
                  LatLng(45.7084786, 11.0093038),
                  LatLng(45.7116551, 11.009218),
                  LatLng(45.7132733, 11.008703),
                  LatLng(45.7148914, 11.0069006),
                  LatLng(45.7159701, 11.0014932),
                  LatLng(45.7170488, 10.9947126),
                  LatLng(45.7167492, 10.9906786),
                  LatLng(45.7169889, 10.9836405),
                  LatLng(45.7173485, 10.9775465),
                  LatLng(45.7172886, 10.9747141),
                  LatLng(45.6971495, 10.9738558),
                ])
          },
          onMapCreated: (GoogleMapController controller) {
            _controller.complete(controller);
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale
    en-IT)
    • Flutter version 3.13.0 on channel stable at /Users/enrico/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (10 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/enrico/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        •
      android-x64    • Android 12 (API 32) (emulator)
    • iPhone 14 Pro (mobile)       • F016F473-ED89-4DC8-91DE-F9337B22828D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                •
      darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)                 • chrome                               •
      web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-08-25 20:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/132000

The plugin is just passing the data to the Google Maps SDK; inconsistencies between the Android and iOS SDKs are outside of the Flutter team's control, so all we can do is adjust documentation. If you believe the Android behavior itself is a bug, you'd need to report it to the Google Maps team.

**Closed by stuartmorgan** 2023-08-25 20:35 UTC
