### ISSUE TITLE
ArgumentError: Invalid argument(s): Invalid locale 'C.UTF-8'

### ISSUE THREAD

**Issue by srisusil** [flutter/flutter#16104] opened 2018-03-30 17:43 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Invalid locale 'C.UTF-8'

```
#0      Intl._throwLocaleError (package:intl/intl.dart:231)
#1      Intl.verifiedLocale (package:intl/intl.dart:225)
#2      Intl.verifiedLocale (package:intl/intl.dart:210)
#3      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:486)
#4      new NumberFormat.decimalPattern (package:intl/src/intl/number_format.dart:175)
#5      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:114)
#6      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:114)
#7      getElapsedAsMilliseconds (package:flutter_tools/src/base/utils.dart:122)
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:234)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#24     main (file:///home/dracula/Desktop/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (Channel beta, v0.2.3, on Linux, locale C.UTF-8)
    • Flutter version 0.2.3 at /home/dracula/Desktop/flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5
      

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /media/dracula/msk/SOFTWARES/programming lang/idea-IU-181.4203.550
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

! Doctor found issues in 3 categories.
```

**Comment by Hixie** [comment] 2018-05-23 21:02
Duplicate of https://github.com/flutter/flutter/issues/11151

**Closed by Hixie** 2018-05-23 21:02 UTC
Labels: severe: crash, tool
