### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2

### ISSUE THREAD

**Issue by varunpai314** [flutter/flutter#142864] opened 2024-02-03 16:38 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:169:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:157:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1812:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1830:13)
#8      _rootRunUnary (dart:async/zone.dart:1407:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1407:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3085], locale en-IN)
    [32m•[39m Flutter version 3.16.9 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (9 days ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\paiva\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34024.191
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.86.0)
    [32m•[39m VS Code at C:\Users\paiva\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.82.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m SM G610F (mobile) • 52009385b8d574fd • android-arm    • Android 8.1.0 (API 27)
    [32m•[39m Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3085]
    [32m•[39m Edge (web)        • edge             • web-javascript • Microsoft Edge 121.0.2277.98

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
desktop_webview_auth-0.0.15
firebase_auth-4.17.3
firebase_auth_web-5.9.3
firebase_core-2.25.3
firebase_core_web-2.11.3
firebase_dynamic_links-5.4.12
flutter_plugin_android_lifecycle-2.0.17
geocoding-2.1.1
geocoding_android-2.1.2
geocoding_ios-2.1.1
geolocator-10.1.0
geolocator_android-4.5.1
geolocator_apple-2.3.5
geolocator_web-2.2.1
geolocator_windows-0.2.2
google_maps_flutter-2.5.3
google_maps_flutter_android-2.6.2
google_maps_flutter_ios-2.4.1
google_maps_flutter_web-0.5.4+3
google_sign_in-6.2.1
google_sign_in_android-6.1.21
google_sign_in_ios-5.7.3
google_sign_in_web-0.12.3+2
location-5.0.3
location_web-4.2.0

**Comment by huycozy** [comment] 2024-02-05 09:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/95142. Meanwhile, you can work around this by installing Google Chrome as the hint from flutter doctor output.

**Closed by huycozy** 2024-02-05 09:02 UTC
Labels: in triage
