### ISSUE TITLE
Flutter web - splash screen - weird behavior

### ISSUE THREAD

**Issue by Bonissauro** [flutter/flutter#86824] opened 2021-07-21 23:12 UTC
As a flutter web app usually takes a bit of time to be loaded for the first time, I'm trying to show a message in its splash screen to notify the user that the thing is not frozen e that time is a regular behavior.

To achieve that, I just put these few lines of code on web/index.html

```
    <div style="text-align: center; position: absolute; top: 40%; width: 100%">
        <center>
            <p style="font-weight: bolder;">Carregando o catálogo...</p>
            <p>Na primeira execução, isso pode demorar cerca de 20 a 30 segundos.<br/>Seja paciente! ;-)</p>
        </center>
    </div>
```

It's a matter of fact that message is shown, but, it's color/size changes in a mysterious way along the process, and I just can't figure out the reason. Take a look at this:

https://i.stack.imgur.com/yIym3.gif

Does anyone have any clue of what is happening and how to solve it?

10x in advance for any help.

**Comment by TahaTesser** [comment] 2021-07-22 12:14
HI @Bonissauro 
When you run the first it loads regular text after that flutter loads it's web bundles which makes your text change then Flutter view is loaded

You can confirm this by commenting Flutter part and the text stays as it is 
<details> 
<summary>index.html</summary> 

```html
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="stable_flutter">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <title>stable_flutter</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <div style="text-align: center; position: absolute; top: 40%; width: 100%">
    <center>
      <H1 style="color: blueviolet;">LOADING.....</H1>
    </center>
</div>

  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <!-- <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing ?? reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script> -->
</body>
</html>

```

</details>

I am no web expert but i tried `:not` css properties, still change is made by Flutter
```html

  <title>stable_flutter</title>
  <link rel="manifest" href="manifest.json">
  <style>
    :not(#my_loading_title) {
      font-size: 200;
      min-block-size: 200;
      max-block-size: 200;
      color: red; font-family: 'Courier New', Courier, monospace; 
    }
  </style>
</head>
<body>
  <div style="text-align: center; position: absolute; top: 40%; width: 100%">
    <center>
      <H1 title="my_loading_title">LOADING.....</H1>
    </center>
</div>
```

Since Flutter doesn't officially support splash screen on web https://github.com/flutter/flutter/issues/48468
Any html hack could have unexpected behavior, you might get better help  on Stackoverflow on how to prevent this.
Closing, thank you

**Comment by TahaTesser** [comment] 2021-07-22 12:14
See https://github.com/flutter/flutter/issues/48468#issuecomment-678741556

**Closed by TahaTesser** 2021-07-22 12:14 UTC
Labels: in triage
