### ISSUE TITLE
Crash on Tabview interacting with TextField

### ISSUE THREAD

**Issue by lucashilles** [flutter/flutter#19587] opened 2018-07-20 01:46 UTC
## Steps to Reproduce

I'm trying to use tabs to navigate between multiple forms, at my first program I used the example at the cookbook, using the default controller. The problem occurs if I tap at the TextField on the first tab, then I go to the last tab and when I return to the first tab my program crashes, showing only a white screen, at my console I receive an huge exception stack.

The only way I find to solve this problem was create a custom controller with a listener that remove the focus from the forms when navigating between tabs.

## My code
```Dart
import 'package:dnd_cs/tabs/charInfo.dart';
import 'package:dnd_cs/tabs/charSkills.dart';
import 'package:dnd_cs/tabs/charEquip.dart';

class NewSheetForm extends StatefulWidget {
  @override
  _NewSheetFormState createState() => new _NewSheetFormState();
}

class _NewSheetFormState extends State<NewSheetForm> {
  CharInfo charInfoTab = new CharInfo();
  CharSkills charSkillsTab = new CharSkills();
  CharEquip charEquipTab = new CharEquip();

  @override
  Widget build(BuildContext context) {
    return new DefaultTabController(
        length: 3,
        child: new Scaffold(
          appBar: new AppBar(
            title: new Text('Dados do personagem'),
            bottom: new TabBar(
              tabs: [
                new Tab(
                  icon: new Icon(Icons.perm_identity),
                ),
                new Tab(
                  icon: new Icon(Icons.description),
                ),
                new Tab(
                  icon: new Icon(Icons.work),
                ),
              ],
            ),
          ),
          body: TabBarView(
              physics: new NeverScrollableScrollPhysics(),
              children: [charInfoTab, charSkillsTab, charEquipTab]),
        ),
    );
  }
}
```
First tab
```Dart
import 'package:flutter/material.dart';

class CharInfo extends StatefulWidget {
  @override
  _CharInfoState createState() => new _CharInfoState();
}

class _CharInfoState extends State<CharInfo>{
  GlobalKey<FormState> _formKey = new GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return new Container(
      child: new SafeArea(
        top: false,
        bottom: false,
        child: new Form(
          key: _formKey,
          autovalidate: true,
          child: new ListView(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            children: <Widget>[
              new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.person),
                  hintText: 'Seu nome',
                  labelText: 'Nome',
                ),
              ),
              new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.whatshot),
                  hintText: 'Neutro',
                  labelText: 'Alinhamento',
                ),
              ),
              new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.translate),
                  hintText: 'Idioma comum',
                  labelText: 'Idiomas',
                ),
              ),
              new TextFormField(
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  icon: const Icon(Icons.trending_up),
                  //hintText: 'Idioma comum',
                  labelText: 'Nível',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Second and third tabs
```Dart
import 'package:flutter/material.dart';

class CharSkills extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(
      child: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Icon(
              Icons.business_center,
              size: 160.0,
              color: Colors.red,
            ),
            new Text('Second Tab'),
          ],
        ),
      ),
    );
  }
}
```
## Logs

```
Showing Moto G 4 logs:
I/flutter ( 2926): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2926): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 2926): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14:
I/flutter ( 2926): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 2926): 
I/flutter ( 2926): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2926): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2926): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2926):   https://github.com/flutter/flutter/issues/new
I/flutter ( 2926): 
I/flutter ( 2926): When the exception was thrown, this was the stack:
I/flutter ( 2926): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart)
I/flutter ( 2926): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2809:5)
I/flutter ( 2926): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 2926): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:865:18)
I/flutter ( 2926): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4513:35)
I/flutter ( 2926): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4279:5)
I/flutter ( 2926): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4653:11)
I/flutter ( 2926): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2926): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2926): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2926): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2926): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2926): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2926): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2926): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2926): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter ( 2926): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2926): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2926): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2926): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2926): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2926): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2926): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2926): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter ( 2926): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
I/flutter ( 2926): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter ( 2926): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter ( 2926): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 2926): #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 2926): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 2926): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 2926): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 2926): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 2926): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 2926): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 2926): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #77     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 2926): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 2926): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 2926): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2926): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2926): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2926): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 2926): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 2926): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 2926): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2926): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2926): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 2926): #95     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 2926): #96     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 2926): (elided 2 frames from class _AssertionError)
I/flutter ( 2926): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 2926): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
I/flutter ( 2926): Another exception was thrown: type 'RenderErrorBox' is not a subtype of type 'RenderSemanticsGestureHandler'
I/flutter ( 2926): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
I/flutter ( 2926): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#1290f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 2926): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
I/flutter ( 2926): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#1290f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4039 pos 14: '_dependents.isEmpty': is not true.
I/flutter ( 2926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2240 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
```

**Comment by zoechi** [comment] 2018-07-20 06:36
Please add the output of `flutter doctor -v`.
This issue should be fixed. Please ensure you have the latest Flutter version
```sh
flutter upgrade
```
If you are on latest `beta` and still can reproduce please try with the `dev` or `master` channel.
```sh
flutter channel dev
flutter doctor
```

**Comment by zoechi** [comment] 2018-07-20 06:40
I believe this is a duplicate of #11895

**Closed by zoechi** 2018-07-20 06:40 UTC
