### ISSUE TITLE
Running multiple engines in same process crashes in Windows

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#75101] opened 2021-01-31 21:38 UTC
The issue here is that all angle contexts backed by single display share same state, which is not thread safe. Possible solution is to create separate eglDisplay instance for each engine.

**Comment by stuartmorgan** [comment] 2021-01-31 21:50
Duplicate of https://github.com/flutter/flutter/issues/53372

**Closed by stuartmorgan** 2021-01-31 21:50 UTC
