### ISSUE TITLE
[camerax] Preview flickering when calling setState

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#140567] opened 2023-12-23 09:57 UTC
### What package does this bug report belong to?

camerax

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details open><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  camera:
    dependency: "direct main"
    description:
      name: camera
      sha256: "7fa53bb1c2059e58bf86b7ab506e3b2a78e42f82d365b44b013239b975a166ef"
      url: "https://pub.dev"
    source: hosted
    version: "0.10.5+7"
  camera_android:
    dependency: transitive
    description:
      name: camera_android
      sha256: "7215e38fa0be58cc3203a6e48de3636fb9b1bf93d6eeedf667f882d51b3a4bf3"
      url: "https://pub.dev"
    source: hosted
    version: "0.10.8+15"
  camera_android_camerax:
    dependency: "direct main"
    description:
      path: ".."
      relative: true
    source: path
    version: "0.5.0+24"
  camera_avfoundation:
    dependency: transitive
    description:
      name: camera_avfoundation
      sha256: "3c8dd395f18722f01b5f325ddd7f5256e9bcdce538fb9243b378ba759df3283c"
      url: "https://pub.dev"
    source: hosted
    version: "0.9.13+8"
  camera_platform_interface:
    dependency: "direct main"
    description:
      name: camera_platform_interface
      sha256: b6a568984254cadaca41a6b896d87d3b2e79a2e5791afa036f8d524c6783b93a
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  camera_web:
    dependency: transitive
    description:
      name: camera_web
      sha256: d4c2c571c7af04f8b10702ca16bb9ed2a26e64534171e8f75c9349b2c004d8f1
      url: "https://pub.dev"
    source: hosted
    version: "0.3.2+3"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      sha256: fedaadfa3a6996f75211d835aaeb8fede285dae94262485698afd832371b9a5e
      url: "https://pub.dev"
    source: hosted
    version: "0.3.3+8"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "706b5707578e0c1b4b7550f64078f0a0f19dec3f50a178ffae7006b0a9ca58fb"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  espresso:
    dependency: "direct dev"
    description:
      name: espresso
      sha256: a11b88c61209d873735bdf3f263ab63ce28459f8d6b6ee78257b2307a7c2edf2
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_driver:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      sha256: b068ffc46f82a55844acfa4fdbb61fad72fa2aef0905548419d97f0f95c456da
      url: "https://pub.dev"
    source: hosted
    version: "2.0.17"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  fuchsia_remote_debug_protocol:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "3a7812d5bcd2894edf53dfaf8cd640876cf6cef50a8f238745c8b8120ea74d3a"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.4"
  integration_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "9528f2f296073ff54cb9fee677df673ace1218163c3bc7628093e7eed5203d41"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: a6e590c838b18133bb482a2745ad77c5bb7715fb0451209e1a7567d416678b8e
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: ae68c7bfcd7383af3629daafb32fb4e8681c7154428da4febcff06200585f102
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: f4f88d4a900933e7267e2b353594774fc0d07fb072b47eedcd5b54e1ea3269f8
      url: "https://pub.dev"
    source: hosted
    version: "2.1.7"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      sha256: "14a00e794c7c11aa145a170587321aedce29769c08d7f58b1d141da75e3b1c6f"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  sync_http:
    dependency: transitive
    description:
      name: sync_http
      sha256: "7f0cd72eca000d2e026bcd6f990b81d0ca06022ef4e32fb257b30d3d1014a961"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "5c2f730018264d276c20e4f1503fd1308dfbbae39ec8ee63c5236311ac06954b"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  video_player:
    dependency: "direct main"
    description:
      name: video_player
      sha256: e16f0a83601a78d165dabc17e4dac50997604eb9e4cc76e10fa219046b70cef3
      url: "https://pub.dev"
    source: hosted
    version: "2.8.1"
  video_player_android:
    dependency: transitive
    description:
      name: video_player_android
      sha256: "3fe89ab07fdbce786e7eb25b58532d6eaf189ceddc091cb66cba712f8d9e8e55"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.10"
  video_player_avfoundation:
    dependency: transitive
    description:
      name: video_player_avfoundation
      sha256: "01a57940e1dabc8769ccd457c4ae9ea50274e7d5a7617f7820dae5fe1d8436ae"
      url: "https://pub.dev"
    source: hosted
    version: "2.5.3"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      sha256: be72301bf2c0150ab35a8c34d66e5a99de525f6de1e8d27c0672b836fe48f73a
      url: "https://pub.dev"
    source: hosted
    version: "6.2.1"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      sha256: ab7a462b07d9ca80bed579e30fb3bce372468f1b78642e0911b10600f2c5cb5b
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: c538be99af830f478718b51630ec1b6bee5e74e52c8a802d328d9e71d35d2583
      url: "https://pub.dev"
    source: hosted
    version: "11.10.0"
  web:
    dependency: transitive
    description:
      name: web
      sha256: afe077240a270dcfd2aafe77602b4113645af95d0ad31128cc02bce5ac5d5152
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0"
  webdriver:
    dependency: transitive
    description:
      name: webdriver
      sha256: "3c923e918918feeb90c4c9fdf1fe39220fa4c0e8e2c0fffaded174498ef86c49"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
sdks:
  dart: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"
```

</details>

### Steps to reproduce

1. Run the camerax example app
2. Add the following to the initState of the widget that builds the camera preview
```dart
Timer.periodic(Duration(milliseconds: 100), (_) {
    setState(() => {});
});
```

### Expected results

The camera preview should not flicker. The `camera_android` implementation doesn't flicker when rebuilding.

### Actual results

The camera preview flickers/flashes on every build. When building a real time detection algorithm over the camera frames this is really noticeable.

### Code sample

The code sample is the example app within the camerax android implementation.

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/22084723/6c2f94d9-3cff-4dd2-985e-9afef14a09dc

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on Fedora Linux 38 (Workstation Edition) 6.6.6-100.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/david/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/david/Android/Sdk/
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/david/opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/david/opt/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/david/opt/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.6.6-100.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-27 10:53
Reproducible using the camerax example app. This does not happen with the regular android package as reported above. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (7 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 120.0.6099.129
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
  
```
[!] Flutter (Channel master, 3.18.0-18.0.pre.30, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-18.0.pre.30 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f15364efe4 (8 hours ago), 2023-12-26 21:57:40 -0500
    • Engine revision 2c04f3e2af
    • Dart version 3.3.0 (build 3.3.0-262.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 120.0.6099.129
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by mossmana** [comment] 2023-12-27 18:21
@camsim99 Would you be able to link any other examples or documentation on camera preview?

**Comment by camsim99** [comment] 2023-12-27 19:02
My gut feeling here is that by calling `setState` so frequently and causing the camera preview to rebuild, we are also causing [`createCamera`](https://github.com/flutter/packages/blob/36a7b99381f85e86914e82c75fc7d9038ed96cca/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L242) to be called which is where all of the CameraX `UseCase`s (including the preview one) we use to perform camera functions are configured and bound to [the lifecycle that CameraX uses to manage the camera](https://developer.android.com/training/camerax/architecture#lifecycles). This operation is expensive, which is the primary reason why we chose to do it once in the `createCamera` method versus in other methods that may be called multiple times (except the video capture `UseCase` since it is most expensive and is lazily bound in case it is never used). This follows the recommendation in the [CameraX docs](https://developer.android.com/training/camerax/architecture#combine-use-cases) of limiting your binding to one call.

What this means in terms of this issue is that the problem described will be hard to avoid by using the CameraX library in the most performant way we can, given the structure of the platform interface of this plugin. We do not manage the camera, so we must at some point bind the `UseCase`s and moving this operation out to methods where the `UseCase`s are immediately needed may slow down those individual operations.

Thus, I think this issue would only be actionable if more context can be provided to justify why we may want to make that tradeoff.

**Comment by davidmartos96** [comment] 2023-12-27 19:11
@camsim99 
The use case on the Flutter app would be to be able to draw at a high refresh rate on top of the camera preview every time a particular object is detected by processing the camera frames.
It works fine on the camera_android , so when trying out the camerax implementation this flickering behavior was really noticeable.

This drawing on top implies calling setState, not sure if there would be a way to avoid that.

**Comment by davidmartos96** [comment] 2023-12-27 19:17
I'm not familiar with how a native app is developed with the CameraX library, but I feel such side effect for initializing/creating the camera on the Flutter build step can get very confusing to Flutter developers.
It's "common say" that rebuilding a widget should not create side effects when the state is the same.

**Comment by camsim99** [comment] 2023-12-27 19:23
@davidmartos96 Ah okay I see what you're saying. We will have to dig a bit deeper into `camera_android` to see why it doesn't behave the same and experiment with ways we may be able to work around it, either on the Flutter app's end or on the plugin's side (either if the binding is not the cause like I predict or if moving the calls out of `createCamera` helps immensely).

**Comment by camsim99** [comment] 2024-01-04 20:12
> The use case on the Flutter app would be to be able to draw at a high refresh rate on top of the camera preview every time a particular object is detected by processing the camera frames.

@davidmartos96 After re-reading your use case, we wonder if using image streaming to retrieve frames (via [`onStreamedFrameAvailable`](https://github.com/flutter/packages/blob/e57318508e95f59c7aec7dc0dbf1fbe5ff75b5e5/packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart#L188) to render the preview in your app could help solve this issue. As I mentioned above, CameraX obscures away refreshing and building the preview, so it could be difficult for us to control it like we do in `camera_android`.

**Comment by davidmartos96** [comment] 2024-01-04 20:18
@camsim99 Wouldn't that cause the same issue? Calling setState inside that function would flicker as well, right?

The real time processing algorithm would process the frames and then it would update a real time UI on top of the camera preview with certain information. For that setState would have to be used.

**Comment by camsim99** [comment] 2024-01-04 21:35
@davidmartos96 Can you explain why `setState` would have to be used? Why can't you listen to the `onStreamedFrameAvailable` Stream events to update the UI as needed?

**Comment by davidmartos96** [comment] 2024-01-04 21:58
@camsim99 I'd provide and example, maybe I'm not explaining myself correctly.

This strategy is essentially what we are using with camera_android and it works just fine. Our expectations would be that it would work roughly similar in the Dart/Flutter side without flickering 

Pseudocode:

```
StatefulWidget {
  
  initState() {
     controller.onCameraFrame((frame) {
         final newInfo = processFrame(frame);
         setState(() => info = newInfo);
     })
  }
  
  build() {
      return Stack([
          CameraPreview(),
          RealtimeInfo(info)
      ]);
  }
}
```

**Comment by camsim99** [comment] 2024-01-10 19:40
I'll need to repro this on my end to debug the cause. I still believe [my initial theory](https://github.com/flutter/flutter/issues/140567#issuecomment-1870556239) is correct, which means we would need to find a workaround on the Flutter app side. Either way, though, it is likely inefficient to have the camera preview rebuilding frequently, and I would (and will locally) try to separate the `RealtimeInfo` stateful widget from the `CameraPreview` widget (that could be stateless I believe) to avoid that.

**Comment by charannplay** [comment] 2024-01-22 08:35
Hi @camsim99. Did you get a chance to check what's causing the issue

**Comment by camsim99** [comment] 2024-01-29 23:53
Apologies for the delay.

I was able to reproduce this issue with app of structure similar to what was [described above](https://github.com/flutter/flutter/issues/140567#issuecomment-1877816320) by using a counter every time the listener picks up an event to make the app redraw, causing the widget to flicker.

However, I think I was able to fix this by separating the widget that relies on setState (in my case, my counter; in the case above, the `RealtimeInfo(info)` widget) from the preview widget (which I made stateless).

Going to work on modifying the camera example app to demonstrate that this (or something similar) works, as I think this was be a preferred approach for the use case this issue describes.

**Comment by xfqwdsj** [comment] 2024-01-30 03:33
@camsim99 I can't think of a structure that can separate onCameraFrame and setState. 🤔 Do you have any suggestions? 🙂

**Comment by camsim99** [comment] 2024-01-30 23:36
After further digging, I've determined that

1. Building the preview causes a call to the native side of the plugin to be made (see [source](https://github.com/flutter/packages/blob/5b48c446976fd5f61316d58ab3fcc9888423c2e6/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L734)) and this call is awaited to build the preview, so this could be behind the flicker.
2. A solution to this issue is to **not** build preview directly in the build method of your Widget. The [camera preview](https://github.com/flutter/packages/blob/5b48c446976fd5f61316d58ab3fcc9888423c2e6/packages/camera/camera/lib/src/camera_preview.dart#L12) is a stateless widget, and there's no need to re-initialize it after it has been built as far as I can see, even with `camera_android`, though it seems to work.

@xfqwdsj At a high level, this is my example:

```dart
class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  CameraController? controller;

  /// Preview widget.
  Widget? preview;

  /// Frame info.
  String? info;
  
  @override
  void initState() {
     _buildPreview();
    super.initState();
  }

  void _buildPreview() async {
    controller = CameraController(...);
    await controller!.initialize();

    // Build preview.
    preview = CameraPreview(controller!);

    // Start image stream.
    controller!.startImageStream((frame) {
      final newInfo = processFrame(frame);
      setState(() => info = newInfo);
    });
  }
  
  @override
  Widget build(...) {
      return Stack(children: [
          preview == null ? const Text('No preview available :(') : preview!,
          RealtimeInfo(info) // custom widget
      ]);
  }
}
```

**Comment by camsim99** [comment] 2024-01-30 23:37
Given these findings, I think the actionable item here is to properly document in the plugin (likely in the README) that it is recommended not to build the camera preview directly in the build method of a Widget, as it may not be performant.

**Comment by davidmartos96** [comment] 2024-01-30 23:48
@camsim99 Thanks for digging into it, after looking at the source code call in the build, the problem could be that a the future is being recreated every build. Couldn't this be handled properly with a StatefulWidget that reuses the Future and only recreates it when cameraId changes? I haven't actually tried it, so I might be wrong and creating the future there is intended.
 https://github.com/flutter/packages/blob/5b48c446976fd5f61316d58ab3fcc9888423c2e6/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L526

About FutureBuilder: https://stackoverflow.com/a/52249579

**Comment by camsim99** [comment] 2024-01-30 23:53
I'm not deeply familiar with `FutureBuilder`s and I recall it being a recommendation being made to me based on the fact that we have to check certain conditions to ensure the preview is ready to build. I can try that out and see if it works :)

**Comment by davidmartos96** [comment] 2024-01-31 00:02
@camsim99 One easy solution could be replacing lines such as the following:

https://github.com/flutter/packages/blob/5b48c446976fd5f61316d58ab3fcc9888423c2e6/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L519

with:

```dart
this._lifecycleBindingFuture = _bindPreviewToLifecycle(cameraId);
```

And then use the cached `_lifecycleBindingFuture` Future in the `FutureBuilder`.
That alone might actually be enough.

**Comment by camsim99** [comment] 2024-01-31 00:06
I was trying out the first solution, but it is starting to require a lot of refactor which isn't necessarily bad, but not sure how much it would cause the logic between the plugin code and this stateful widget to get entangled. Let me try caching the `Future`.

**Comment by camsim99** [comment] 2024-01-31 00:14
@davidmartos96 Ok I just tried the caching approach, and this does not work -- same issue as before.

**Comment by davidmartos96** [comment] 2024-01-31 00:19
@camsim99 That's unfortunate. Do you refer to the refactor issue or the flicker issue?

I guess as a last resort, your workaround could be documented, although having to cache a widget is not considered a good practice, and usually means that something underneath can be cached instead.

I might look into it sometime this week.

Thanks again!

**Comment by camsim99** [comment] 2024-01-31 00:22
@davidmartos96 I'm referencing the flicker issue with the caching approach. I'm about to re-attempt the Stateful widget approach and will report back.

> I guess as a last resort, your workaround could be documented, although having to cache a widget is not considered a good practice, and usually means that something underneath can be cached instead.

That makes sense to me, but I may need to get your help and/or reach out for help to find a better workaround since I'm not too familiar here. If you look into it, would love to hear your updates and of course would welcome a fix! I'll continue to look into it on my end, as well, before resorting to documentation.

**Comment by camsim99** [comment] 2024-01-31 00:33
> Couldn't this be handled properly with a StatefulWidget that reuses the Future and only recreates it when cameraId changes?

Ah this didn't work either :( This [group of lines](https://github.com/flutter/packages/blob/5b48c446976fd5f61316d58ab3fcc9888423c2e6/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L529-L533) that makes the preview `Widget` a`SizedBox.shrink()` while the `Future` is waiting to be completed is causing the flicker, I confirmed. Will need to look into other possible ways to handle building the preview after the Future is completed.

**Comment by camsim99** [comment] 2024-01-31 00:46
After talking to @khanhnwin about an approach here, another way to fix this issue could be changing the conditions under which we check the `Future` at all. Meaning, we may only need the `_bindPreviewToLifecycle` future if we are building the preview for the first time, i.e. not trying to resume the preview after pausing it (for which this `Future` is also used).

This would be a straightforward fix, just need to think through any other cases where we would then be not checking this `Future` when we would need to.

**Comment by camsim99** [comment] 2024-01-31 01:03
After more conversation, I'm not sure that we need the `Future` at all given that if we expect and require users to initialize the camera controller before calling `buildPreview`, all the necessary conditions should be met. Further, once the preview is paused via `pausePreview`, then `resumePreview` should be called, not `buildPreview`, so we wouldn't need the `Future` in that case either.

Thus at this moment, I think a good path forward is changing `buildPreview` to just return the `Texture` without a `FutureBuilder`. Perhaps we could warn users if they have not yet initialized the camera controller if they do try to call `buildPreview` before doing so.

**Comment by davidmartos96** [comment] 2024-01-31 07:21
@camsim99 That sounds great and easier.
Thanks for investigating! Looking forward to the fix.

**Closed** 2024-02-01 20:43 UTC
Labels: platform-android, p: camera, has reproducible steps, P1, team-android, triaged-android, found in release: 3.16, found in release: 3.18
