### ISSUE TITLE
[desktop-windows]Unable to input chinese into TextFormField on Windows7 OS,with Sogou IME\Baidu IME

### ISSUE THREAD

**Issue by 15563988825** [flutter/flutter#93851] opened 2021-11-18 09:49 UTC
![138072681-79586a2d-feb8-4614-84da-2d0893211953](https://user-images.githubusercontent.com/4360198/142391388-a8b3a5ae-5f37-40bc-a2ba-13aced6bc98d.gif)

Appear on WIndows7 OS,It'1 ok on WIndow10 OS

Steps:

1. Focus the text field
2. Ensure IME is set to sogou
3. Input some text (e.g. nihao). The candidates list will appear. Arrow keys work for navigating the candidates list.
4. Either click the candidate or press enter.

**Comment by 15563988825** [comment] 2021-11-18 09:52
Flutter Doctor -v
I've tried stable cahnnel and the problem still happen.
![image](https://user-images.githubusercontent.com/4360198/142391894-6c6645db-206a-443e-9d87-3bc40642c626.png)

**Comment by darshankawar** [comment] 2021-11-18 11:56
@15563988825 
This issue was recently fixed and merged into master, https://github.com/flutter/flutter/issues/92164
You'll need to switch to latest master to see the functionality working.

```
flutter channel master
flutter upgrade
```

Closing this as a duplicate of already fixed issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-11-18 11:56 UTC
Labels: in triage

**Comment by 15563988825** [comment] 2021-11-19 01:16
I tested,it has bean fixed in master,
Thanks!!
