### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by Sardorbee** [flutter/flutter#144526] opened 2024-03-04 06:32 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=CE49ROWGOR797DG6 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2237:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:886:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:572:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:875:13)
#16     Future._completeWithValue (dart:async/future_impl.dart:647:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#18     _rootRun (dart:async/zone.dart:1399:13)
#19     _CustomZone.run (dart:async/zone.dart:1301:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 3.16.5 on channel stable at D:\programm\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: D:\programm\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2023.1)
    • Android Studio at D:\programm\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.86.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] Connected device (5 available)
    • 2201117SG (mobile)           • CE49ROWGOR797DG6 • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1052]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 122.0.2365.66

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
fijkplayer-0.11.0
file_picker-5.5.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_phone_direct_caller-2.1.1
flutter_plugin_android_lifecycle-2.0.17
flutter_sound-9.2.13
flutter_sound_web-9.2.13
fluttertoast-8.2.4
fluwx-3.13.1
image_picker-0.8.9
image_picker_android-0.8.9+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.9+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
open_filex-4.4.0
package_info_plus-4.2.0
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
photo_manager-2.8.1
sqflite-2.3.2
url_launcher-6.2.4
url_launcher_android-6.2.2
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1
video_player-2.8.2
video_player_android-2.4.11
video_player_avfoundation-2.5.2
video_player_web-2.1.3
webview_flutter-4.5.0
webview_flutter_android-3.14.0
webview_flutter_wkwebview-3.10.2

**Comment by danagbemava-nc** [comment] 2024-03-04 10:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371

**Closed by danagbemava-nc** 2024-03-04 10:32 UTC
Labels: in triage
