### ISSUE TITLE
Range Error:  Value not in range

### ISSUE THREAD

**Issue by sudha-anecure** [flutter/flutter#70257] opened 2020-11-11 02:22 UTC
Hi - we got this error from a user using our app built on 1.22.0 version of flutter. Here is the stack trace reported on crahslytics from the screen. This is a screen where the user is shown a single text field to enter his username. I assume he tried to select a portion of the text using touch and faced this error.

Error:
RangeError: Value not in range: 19
Stack trace:
#0 _StringBase.substring (dart:core-patch/string_patch.dart:393)
#1 _selectionAwareTextManipulation (package:flutter/src/services/text_formatter.dart:416)
#2 FilteringTextInputFormatter.formatEditUpdate (package:flutter/src/services/text_formatter.dart:220)
#3 EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:2142)
#4 EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:2310)
#5 TextSelectionOverlay._handleSelectionHandleChanged (package:flutter/src/widgets/text_selection.dart:601)
#6 TextSelectionOverlay._buildHandle. (package:flutter/src/widgets/text_selection.dart:532)
#7 _TextSelectionHandleOverlayState._handleDragUpdate (package:flutter/src/widgets/text_selection.dart:697)
#8 DragGestureRecognizer._checkUpdate. (package:flutter/src/gestures/monodrag.dart:431)
#9 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183)
#10 DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:431)
#11 DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:286)
#12 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77)
#13 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:122)
#14 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
#15 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120)
#16 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106)
#17 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358)
#18 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338)
#19 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267)
#20 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295)
#21 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240)
#22 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213)
#23 _rootRunUnary (dart:async/zone.dart:1206)
#24 _CustomZone.runUnary (dart:async/zone.dart:1100)
#25 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
#26 _invoke1 (dart:ui/hooks.dart:265)
#27 _dispatchPointerDataPacket (dart:ui/hooks.dart:174)
Device parameters:
id: QP1A.190711.020
androidId: c4b9bef95b366509
board: dandelion
bootloader: unknown
brand: Redmi
device: dandelion
display: QP1A.190711.020
fingerprint: Redmi/dandelion_global/dandelion:10/QP1A.190711.020/V12.0.6.0.QCDMIXM:user/release-keys
hardware: mt6762
host: c3-miui-ota-bd145.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2006C3LG
product: dandelion_global
tags: release-keys
type: user
versionBaseOs:
versionCodename: REL
versionIncremental: V12.0.6.0.QCDMIXM
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-09-01
Application parameters:
version: 2.5.1
environment: ApplicationProfile.release
Custom parameters:

The above is the only information I have since this is on a production device of an end user.

I thought this was the same as #49989 but was told this is different and to open a new issue.

**Comment by LongCatIsLooong** [comment] 2020-11-11 03:11
Thanks for reporting this issue! I assume the user name text field is a single-line text field? Did you add additional `inputFormatters` to that text field?

**Comment by sudha-anecure** [comment] 2020-11-11 03:21
No inputformatters. Here is the code:

**Comment by pedromassangocode** [comment] 2020-11-20 12:47
Hi @sudha-anecure 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample? Make sure your code is minimal and runnable.

Thank you

**Comment by sudha-anecure** [comment] 2020-11-23 18:06
Hi @pedromassangocode - as I had indicated above - this happens on our production app that was released a month ago. Since then we have internally upgraded flutter to the latest stable version, so our flutter doctor -v is not relevant. I have provided build information in the ticket above. I have no personal repro - as explained, we capture this error via crashlytics logging of our production app. But this does happen as reported by many users on this forum and should be fixed as a framework error without a consistent repro being required.

**Comment by rizentium** [comment] 2021-03-27 14:04
I found it also in my code

```dart
lastWordIs(String payload) {
    String word = payload.split(' ').last;

   // fixed the Range Error: Value not in range issue
    if (word.isEmpty) {
      return WordType.none;
    }

    switch (word.substring(0, 1)) {
      case '@':
        return WordType.a1;
      case '#':
        return WordType.a2;
      default:
        return WordType.none;
    }
  }
```

and fix it by using this code
```dart
if (word.isEmpty) {
  return WordType.none;
}
```

Because `word` is an empty string and cannot get the first char from that string.

Maybe you can check the empty string condition from your string because empty string is not `null` and `null` is not empty string

**Comment by MerdanDev** [comment] 2023-01-21 17:20
@sudha-anecure you showed device with this chip below:

> hardware: mt6762

I am having a lot of crashes with this chip devices, most of crashes are releted to appbundle split for versioning chip types.
Maybe we need expert about appbundle to solve this king of crash.
About 70-80% of devices are with this chip **Mediatek MT6762** in my google play console crashes and ANRs.

**Comment by LongCatIsLooong** [comment] 2023-01-23 04:28
The crash site no longer exists in the framework codebase, and as far as I can tell the new code doesn't have this OOB issue. Closing.

**Closed by LongCatIsLooong** 2023-01-23 04:28 UTC
Labels: a: text input, severe: crash, framework, passed first triage, P4
