### ISSUE TITLE
[image_picker] Failed to load image when selecting image from third-party app

### ISSUE THREAD

**Issue by sed1ka** [flutter/flutter#112783] opened 2022-10-03 04:58 UTC
### Issue Description
Failed to load image when selecting image from third-party app.

### Reproduce steps:
Android Platform
1. Select an image from ImageSource.gallery
2. After the library is opened, then open File Manager or any other application in the side menu to get the image.
3. Choose an Image.
4. After selecting the image, the XFile variable will be null.

https://user-images.githubusercontent.com/83001459/193504314-74e84557-1fef-464b-aa5e-4b3a0f7a9558.mp4

### Simple Code
```
    final XFile imageFile = await _picker.pickImage(
      source: imageSource,
    );

    if (imageFile != null) {
      print('#cropImage imageFile name: ${imageFile.name} | ${imageFile.path}');
      final List<dynamic> croppedImageFile = await _cropImage(File(imageFile.path));
      _inProcess = true;
      return croppedImageFile;
    } else {
      print('#cropImage imageFile null | failed');
      return <dynamic>[null, 'selected image failed to load'];
    }
```

### Version:
image_picker: ^0.8.5+3
flutter: 
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment] 2022-10-03 10:51
@sed1ka Which device are you having this issue on? Please try running this [`image_picker`'s sample code](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) to see if the issue is reproducible. 
Thank you!

**Comment by sed1ka** [comment] 2022-10-07 11:00
After try running [image_picker's sample code](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example)
Finally, I found that the bug occurred because our app set launchMode to android:launchMode="singleInstance" in AndroidManifest <activity>

**Comment by huycozy** [comment] 2022-10-07 12:45
@sed1ka Given your last message, I feel safe to close this issue due to the issue coming from your implementation, if you disagree please write in the comments and I will reopen it. Thank you!

**Closed by huycozy** 2022-10-07 12:45 UTC
Labels: in triage
