### ISSUE TITLE
plugin(google_sign_in): use Object type for GoogleSignInAccount operator

### ISSUE THREAD

**Issue by evan361425** [flutter/flutter#104378] opened 2022-05-23 01:30 UTC
When using [mockito](https://pub.dev/packages/mockito) for GoogleSignInAccount, the static analyzer starts complaint:

    'Mock.==' ('bool Function(Object)') isn't a valid concrete implementation of 'GoogleSignInAccount.==' ('bool Function(dynamic)').

Which means it should be Object in the `operator ==`'s argument.

**Comment by evan361425** [comment] 2022-05-23 01:41
I think using [firebase_auth_mocks](https://pub.dev/packages/firebase_auth_mocks) can fix this issue.

**Comment by danagbemava-nc** [comment] 2022-05-23 06:56
Hi @evan361425, this is a duplicate of https://github.com/flutter/flutter/issues/101895, which has just been fixed. 

Closing from here as duplicate thank you.

**Closed by danagbemava-nc** 2022-05-23 06:56 UTC
Labels: in triage
