### ISSUE TITLE
[in_app_purchase] applicationUserName not passed through to obfuscatedAccountId in play API

### ISSUE THREAD

**Issue by abs0** [flutter/flutter#64560] opened 2020-08-25 14:18 UTC
PurchaseParam.applicationUserName is now ignored by the google play server API.

The google play API has changed and the accountId parameter in https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder has been replaced by obfuscatedAccountId.

in_app_purchase links against an older com.android.billingclient:billing without support for obfuscatedAccountId. It passes applicationUserName as accountId which is now ignored by google.

Replacing accountId with obfuscatedAccountId and updating the com.android.billingclient:billing dependency allows applicationUserName to pass through to google. (See flutter/plugins#2961 )

**Comment by JaviCore** [comment] 2021-02-17 06:26
Hi, any updates regarding this issue? Would really help if I could use obfuscatedAccountId instead of having to mess up with my backend server to store purchase tokens and the likes for my app's users. 
I can see https://github.com/flutter/plugins/pull/2961 the merge failed and has been pending review for like almost 3 weeks

**Comment by abs0** [comment] 2021-02-23 23:09
> Hi, any updates regarding this issue? Would really help if I could use obfuscatedAccountId instead of having to mess up with my backend server to store purchase tokens and the likes for my app's users.
> I can see [flutter/plugins#2961](https://github.com/flutter/plugins/pull/2961) the merge failed and has been pending review for like almost 3 weeks
> 
> Thanks

Its now over six months since I submitted the original ticket & suggested patch. We've been maintaining our own patched copy of the plugin which has been working for us fine (syncing with the main repo as versions changed). I'm happy to make it public if it would be of any interest pending this being resolved in the main repo.

**Comment by JaviCore** [comment] 2021-02-24 02:53
It would be really helpful if so, could simplify lots of really unnecessary work and async calls to the server if we could use obfuscatedAccountId again.

Thanks

**Comment by vintage** [comment] 2021-03-04 10:48
Seems like it's been fixed in `0.5.0` by https://github.com/flutter/plugins/commit/088bdee478d9a33a1b398f8da2595bf359041cc6#diff-b9164a9759e52cfc3eaa8e54563a6ebc7f26270ccf327ce22930c793d2f5526eR249

**Comment by JaviCore** [comment] 2021-03-05 04:29
@vintage thanks for the heads up!

**Comment by abs0** [comment] 2021-03-08 14:57
@vintage likewise - just need to get everything migrated to flutter 2 now :)

**Comment by vintage** [comment] 2021-03-11 12:53
I've just finished adding new functionality to my app and the `obfuscatedExternalAccountId` is correctly handled by the plugin. I'm able to read the value on the backend side by reading the response from purchase API. Just in time! :)

**Comment by mvanbeusekom** [comment] 2021-03-16 08:46
Closing this issue as the problem is addressed in version 0.5.0. Please let me know if I overlooked something and I will be happy to reopen it.

**Closed by mvanbeusekom** 2021-03-16 08:46 UTC
Labels: a: release, p: first party, p: in_app_purchase, passed first triage, plugin
