### ISSUE TITLE
Scrollbar does not align well on iPhones in Horizontal orientation

### ISSUE THREAD

**Issue by TomassMaximum** [flutter/flutter#47294] opened 2019-12-18 06:25 UTC
## Steps to Reproduce

1. Modify the flutter gallery app, inside material/backdrop_demo.dart, remove the horizontal padding from the ListView(so the problem can be visible).
2. Run the app on an iPhone.
3. Rotate iPhone to horizontal orientation, scroll the list and observe the scroll bar. The scroll bar does not align to the right of the ListView, and block the content.
![IMG_0020](https://user-images.githubusercontent.com/14291993/71060653-0674f180-21a1-11ea-8a80-710c29d999b9.PNG)
I have tested it on iPads and Android phones, they all worked perfectly.
This problem is causing my app's scroll bar blocking some of the scrollable contents which is not expected.

**Target Platform:** iOS
**Target OS version/browser:** iOS 12.4.1
**Devices:** iPhone Xs

## Logs

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.6 at /Users/chuangkegongchang/flutter/flutter
    • Framework revision 18cd7a3601 (7 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chuangkegongchang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Pixel 3a    • 942AY0J30K                               • android-arm64 • Android 10 (API 29)
    • ITHOAD01008 • 502b79899779568a0a171fc8a8c19c7e63d845a8 • ios           • iOS 13.1.3

• No issues found!

```

**Comment by HansMuller** [comment] 2019-12-18 18:37
CC @LongCatIsLooong

**Comment by iapicca** [comment] 2020-03-16 15:16
Hi @TomassMaximum 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment] 2020-03-20 08:37
Hi @TomassMaximum 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by TahaTesser** [comment] 2020-03-20 08:39
Accidentally closed, my bad

**Comment by LongCatIsLooong** [comment] 2020-03-20 20:32
This is a duplicate of https://github.com/flutter/flutter/issues/25802. Closing.

**Closed by LongCatIsLooong** 2020-03-20 20:32 UTC
Labels: a: fidelity, e: device-specific, f: cupertino, f: scrolling, framework, waiting for customer response, ⌺‬ platform-ios
