### ISSUE TITLE
Hope there is a standard program upgrade plan

### ISSUE THREAD

**Issue by wb1992321** [flutter/flutter#63622] opened 2020-08-13 01:51 UTC
During the desktop development process, I encountered a problem. How do I need to implement the program upgrade function? At the same time, it can be adapted to Windows and Mac. If possible, I hope to provide a set of standard program upgrade solutions for flutter, including standard solutions for Android, IOS, macOS, Windows and Linux. At the same time, there seems to be a problem in the packaging process of Windows, that is, "flutter build windows" may only be executed once in the current system boot state and it must be restarted before it can be executed again.

I am using the latest version on the master branch

```
Flutter 1.21.0-10.0.pre.55 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 54f21ec7aa (14 小时前) • 2020-08-12 08:01:03 -0400
Engine • revision ccfc7e5179
Tools • Dart 2.10.0 (build 2.10.0-11.0.dev)
```

Of course, there is still a compilation problem. I can only compile Windows products on Windows. In fact, I hope to compile all products on macOS. I don't know if there is a solution.

> Note: from Google Translate

**Comment by stuartmorgan** [comment] 2020-08-13 04:47
> How do I need to implement the program upgrade function?

There are no plans to include software update within Flutter itself; there are many possible options, and they depend on how someone chooses to do distribution in general. Stores, for instance, generally handle updating.

We encourage the community to create plugins that interface with existing native update solutions (Squirrel, Sparkle, etc.).

> "flutter build windows" may only be executed once in the current system boot state and it must be restarted before it can be executed again.

This is definitely not the case in general. I have never seen this, nor have there been any reports of it. If you have a reproducible case, please file an issue with details.

> I can only compile Windows products on Windows. In fact, I hope to compile all products on macOS.

You can follow https://github.com/flutter/flutter/issues/59735. As noted there, we currently have no plans to support this.


Since the main request here seems to be about software update, which is out of scope for Flutter itself, closing.

**Closed by stuartmorgan** 2020-08-13 04:47 UTC

**Comment by wb1992321** [comment] 2020-08-13 07:39
May I ask why the product of "flutter build windows" is not an installable program, and the exe file found in Release cannot leave the current location (it cannot be sent, unless the entire Runner folder is sent), if unified compilation cannot be solved Can a solution to generate installable programs provide? Because I don't have the foundation of Windows development, or I can assist in generating the program installation package through "VS Studio".

<img width="367" alt="001" src="https://user-images.githubusercontent.com/10239402/90107282-29c95e00-dd7b-11ea-92a1-f9f0bedf6e2e.png">
<img width="352" alt="截屏2020-08-13 下午3 36 06" src="https://user-images.githubusercontent.com/10239402/90107300-2d5ce500-dd7b-11ea-929b-a4052aa7f166.png">
<img width="230" alt="截屏2020-08-13 下午3 36 17" src="https://user-images.githubusercontent.com/10239402/90107310-2f26a880-dd7b-11ea-9bc8-53893b0558ae.png">
