### ISSUE TITLE
NotificationListener<ScrollNotification> not triggers ScrollUpdateNotification when gesture.moveBy positive values

### ISSUE THREAD

**Issue by mdikcinar** [flutter/flutter#124108] opened 2023-04-04 09:28 UTC
I have a pull to refresh widget that uses  NotificationListener<ScrollNotification> to understand the scroll positon, It works well on devices but when i try to test this code i could not.
```dart 
 bool _onNotification(ScrollNotification notification, PullToRefreshCubit pullToRefreshCubit) {
    if (notification is ScrollUpdateNotification) {
      if (notification.metrics.outOfRange) {
        final position = notification.metrics.pixels;
        pullToRefreshCubit.updateScrollPosition(position: position.abs());
      } else {
        pullToRefreshCubit.updateScrollPosition(position: 0);
      }
    }

    return false;
  }
  ````
  I have tryed everything that i could, i even check scroll_notification_test.dart file. But when i try to pull down scroll to positive values. NotificationListeners is not triggering any ScrollUpdateNotification it returns OverscrollNotification.
```dart
      final listViewFirstItemCenter = tester.getCenter(find.text('Item 1'));

      final gesture = await tester.startGesture(listViewFirstItemCenter);
      await tester.pump(const Duration(seconds: 1));
      await gesture.moveBy(Offset(listViewFirstItemCenter.dx, 150), timeStamp: Duration(seconds: 1));
      await tester.pump(const Duration(seconds: 1));
```
How can i test my code?

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. On the tests first test works as expected and prints position: 150
3. On the second test i expect  position: -150 and out of range: true but its not triggering any ScrollUpdateNotification it triggers OverscrollNotification.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: NotificationListener<ScrollNotification>(
          onNotification: _onNotification,
          child: ListView(
            children: List.generate(
                20,
                (index) => Padding(
                      padding: const EdgeInsets.all(8),
                      child: ListTile(
                        title: Text('Item $index'),
                      ),
                    )),
          ),
        ),
      ),
    );
  }

  bool _onNotification(ScrollNotification notification) {
    if (notification is ScrollUpdateNotification) {
      final position = notification.metrics.pixels;
      print('position: $position');
      if (notification.metrics.outOfRange) {
        print('out of range: true');
      }
    }

    return false;
  }
}

```

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:notificationlistener/main.dart';

void main() {
  testWidgets('Notification listener negative test', (tester) async {
    await tester.pumpWidget(const MyApp());
    final listViewFirstItemCenter = tester.getCenter(find.text('Item 1'));

    final gesture = await tester.startGesture(listViewFirstItemCenter);
    await tester.pump(const Duration(seconds: 1));
    await gesture.moveBy(Offset(listViewFirstItemCenter.dx, -150));
    await tester.pump(const Duration(seconds: 1));
  });

  testWidgets('Notification listener positive test', (tester) async {
    await tester.pumpWidget(const MyApp());
    final listViewFirstItemCenter = tester.getCenter(find.text('Item 1'));

    final gesture = await tester.startGesture(listViewFirstItemCenter);
    await tester.pump(const Duration(seconds: 1));
    await gesture.moveBy(Offset(listViewFirstItemCenter.dx, 150));
    await tester.pump(const Duration(seconds: 1));
  });
}

```
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.3 22E252 darwin-arm64, locale en-TR)
    • Flutter version 3.7.3 on channel stable at /Users/mdikcinar/fvm/versions/3.7.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mdikcinar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Mustafa iPhone’u (mobile) •  • ios            • iOS 16.3.1 20D67
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-04-04 10:51
@mdikcinar 
I think based on the document for the class https://api.flutter.dev/flutter/widgets/NotificationListener-class.html, you cannot receive the notification at the same level of where it was dispatched and maybe that's the reason you are not getting expected behavior.
To dispatch notifications, use the [Notification.dispatch](https://api.flutter.dev/flutter/widgets/Notification/dispatch.html) method and see if it helps in your case ?

**Comment by mdikcinar** [comment] 2023-04-04 11:35
Where should i use that [Notification.dispatch](https://api.flutter.dev/flutter/widgets/Notification/dispatch.html) method, in my case?

**Comment by mdikcinar** [comment] 2023-04-04 11:55
I solved the issue with adding OverscrollNotification case for my listener. Its only works while testing, so i can test my widget.
```dart
  bool _onNotification(ScrollNotification notification) {
    if (notification is ScrollUpdateNotification) {
      if (notification.metrics.outOfRange) {
        final position = notification.metrics.pixels;
        pullToRefreshCubit.updateScrollPosition(position: position.abs());
      } else {
        pullToRefreshCubit.updateScrollPosition(position: 0);
      }
    } else if (notification is OverscrollNotification) {
      final overscroll = notification.overscroll;
      pullToRefreshCubit.updateScrollPosition(position: overscroll.abs());
    }

    return false;
  }
```

**Comment by darshankawar** [comment] 2023-04-05 05:37
Good to know the issue is resolved. Closing as such.

**Closed by darshankawar** 2023-04-05 05:37 UTC
Labels: in triage
