### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28

### ISSUE THREAD

**Issue by AliRadwan** [flutter/flutter#93644] opened 2021-11-15 07:12 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=63D4F427-BA67-4EC8-A91D-BEEC9153E39D --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28
```
#0      _RandomAccessFile.writeFrom.<anonymous closure> (dart:io/file_impl.dart:849:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-EG)
    • Flutter version 1.22.6 at /Users/aliradwan/Developer/old/flutter
    • Framework revision 9b2d32b605 (10 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aliradwan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/aliradwan/Library/Java/JavaVirtualMachines/openjdk-17/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17+35-2724)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.0

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 212.5632

[✓] Connected device (2 available)
    • Lenovo A7020a48 (mobile)   • FIPZ6PCIGAL7WKHM                     • android-arm64 • Android 6.0 (API 23)
    • iPhone 12 Pro Max (mobile) • 63D4F427-BA67-4EC8-A91D-BEEC9153E39D • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    ! Error: Ali Radwan is busy: Waiting for Device. Xcode will continue when Ali Radwan is finished. (code -10)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 5.2.2+51
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
audio_service-0.16.2+1
audio_session-0.0.11
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-1.0.0
esys_flutter_share-1.0.2
facebook_app_events-0.10.0
firebase_analytics-6.3.0
firebase_analytics_web-0.1.1
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_crashlytics-0.2.4
firebase_messaging-7.0.3
flutter_isolate-1.0.0+15
flutter_local_notifications-3.0.3
flutter_media_notification-1.2.6
fluttertoast-7.1.8
just_audio-0.6.15+1
just_audio_web-0.2.3
package_info-0.4.3+4
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
purchases_flutter-2.0.3
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
webview_flutter-1.0.7

**Comment by mamuseferha** [comment] 2021-11-15 08:11
Hi @AliRadwan 
It looks like you are on an outdated version of flutter, could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by mamuseferha** [comment] 2021-11-15 10:05
@AliRadwan 
There's an open issue addressing the case you described https://github.com/flutter/flutter/issues/54213.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-15 10:05 UTC
Labels: waiting for customer response
