### ISSUE TITLE
font not properly shown. while using the Open Sans Font.

### ISSUE THREAD

**Issue by divyeshDev** [flutter/flutter#116247] opened 2022-11-30 04:37 UTC
it is showing like that.

![Screenshot 2022-11-30 at 10 03 07 AM](https://user-images.githubusercontent.com/104503242/204708847-394b0ea0-6a93-44f3-a5e9-3f55687cc9f5.png)

Code snippet : 

```
`  TextStyle customTextStyle({
    Color textColor,
    FontWeight fontWeight,
    double fontSize,
  }) {
    return TextStyle(
      color: textColor,
      fontWeight: fontWeight,
      fontSize: fontSize,
      fontFamily: 'OpenSans',
    );
  }`

```

**Comment by BlackStriker99** [comment] 2022-11-30 06:46
@divyeshDev please check it's a duplicate of

https://github.com/flutter/flutter/issues/90135

https://github.com/flutter/flutter/issues/76473

**Comment by huycozy** [comment] 2022-11-30 09:52
Closing as duplicate issue mentioned above (#76473). Please follow up on it for further updates.

**Closed by huycozy** 2022-11-30 09:52 UTC
Labels: in triage
