### ISSUE TITLE
Cursor does not move on entering full-width space in TextField (3.22.0)

### ISSUE THREAD

**Issue by cafelafe** [flutter/flutter#149099] opened 2024-05-26 05:42 UTC
### Steps to reproduce

1. Add TextField
2. Enter full-width space using the keyboard

### Expected results

that the cursor moves

### Actual results

The cursor does not move when entering full-width spaces on iOS as shown in the attached video.
It worked in 3.19.6.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('TextField Example'),
        ),
        body: TextField(),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/103257145/b55d3ece-d3c7-4975-8422-0ff3d12ddff1

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studioのコピー2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • xxxxのiPhone (mobile)            • 00008120-000675C21E33401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.77

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-05-27 09:40
@cafelafe 
Is it a Kana input language you are using ? What is the expected behavior upon following the replication steps ?
Can you provide a short video from previous version where it worked ?

**Comment by cafelafe** [comment] 2024-05-27 12:22
@darshankawar 
> @cafelafe Is it a Kana input language you are using ? What is the expected behavior upon following the replication steps ? Can you provide a short video from previous version where it worked ?

Yes, it is a Kana input language
Flutter version 3.19.6 will look like the video below.

https://github.com/flutter/flutter/assets/103257145/94efa229-5a28-493e-b680-90618265e897

**Comment by darshankawar** [comment] 2024-05-28 05:55
Thanks for the update. Using above details, I was able to verify and replicate the reported behavior. Looks like it is related to unicode text.
Also learned more about full-width space:

`Full-width is used for fields where you will need to type Japanese letters (your mail address, etc.)—in which case, the alphanumeric must be input using full-width. `

Since it worked in latest stable but not in current, I'll label this as regression.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (5 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.23.0-8.0.pre.8, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.23.0-8.0.pre.8 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8fd8e66de4 (4 hours ago), 2024-05-26 21:49:30 -0400
    • Engine revision 469193ef0e
    • Dart version 3.5.0 (build 3.5.0-191.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by jochendev** [comment] 2024-05-28 17:31
still in 3.22.1

**Comment by mafreud** [comment] 2024-05-29 02:16
Same happened in Japanese

**Comment by ttorii20** [comment] 2024-05-31 10:59
We are experiencing the same problem in our project as well. 

This issue is currently labeled for iOS, but it actually affects all platforms, including Android, macOS, and Web. For example, the cursor in a TextField does not move correctly when entering full-width spaces on any of these platforms. Given the widespread impact, I would greatly appreciate it if the priority for resolving this issue could be elevated. 

```
% flutter --version
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (9 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```

**Comment by koji-1009** [comment] 2024-06-06 05:46
The following fixes are included in flutter 3.22. As far as the comments and code are concerned, tabs and half-width spaces are judged as ‘hasTrailingSpaces’, but full-width spaces are not.
Are the various languages with non-half-width spaces affected? 

https://github.com/flutter/flutter/blob/3.22.1/packages/flutter/lib/src/painting/text_painter.dart#L352-L356
https://github.com/flutter/flutter/pull/143954

---

This problem affects text input, so it is a very serious problem that affects a lot of users. As long as this problem exists, non-alphabetical areas should not be updated to Flutter 3.22.

**Comment by koji-1009** [comment] 2024-06-06 09:07
Hi @darshankawar,
This regression is happening in the Flutter code and should affect all platforms.

Web

https://github.com/flutter/flutter/assets/17231507/5bf07dc0-a043-4a69-8a9f-a6f2c30fa01b

Android

[case.webm](https://github.com/flutter/flutter/assets/17231507/18573d58-da99-4c30-bd90-ba9bc3a309ad)

As shown in the video, when half-width and full-width spaces are mixed in the text, the behavior is very confusing. The title of the issue should reflect that this problem affects not only iOS, but also the web and Android.

Thanks.

**Comment by koji-1009** [comment] 2024-06-07 01:37
I have checked the Unicode Zs category and the same problem exists in all codes except `U+0020`, `U+00A0` and `U+202F`.

https://www.compart.com/en/unicode/category/Zs

The behavior of the three characters was compared between Flutter 3.19 and Flutter 3.22. Text is copied and pasted multiple times. Then I type `abc`.

Flutter 3.19.6

https://github.com/flutter/flutter/assets/17231507/a9006a97-348c-414b-bc7b-a0c375c6404c

Flutter 3.22.2

https://github.com/flutter/flutter/assets/17231507/699bd85f-0d5c-4b85-b455-ca502f38696c

**Comment by shiyishiaa** [comment] 2024-06-20 16:34
Same bug. Waiting for it to be handled. :(

**Closed** 2024-07-26 19:55 UTC
Labels: a: text input, c: regression, platform-ios, a: internationalization, customer: crowd, has reproducible steps, P2, team-text-input, triaged-text-input, found in release: 3.22, found in release: 3.23

**Comment by DaigoWakabayashi** [comment] 2024-08-01 05:54
I encountered the same problem but I can confirm that it has already been fixed in the master channel.
Big thanks to all contributors.

https://github.com/user-attachments/assets/03eb6848-2f8e-40ff-b606-564d4843f1a9

<details>

<summary>flutter doctor -v</summary>

```shell
[✓] Flutter (Channel master, 3.24.0-1.0.pre.388, on macOS 14.6 23G80 darwin-arm64, locale en-JP)
    • Flutter version 3.24.0-1.0.pre.388 on channel master at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f064c3e5c0 (88 minutes ago), 2024-07-31 23:55:31 -0400
    • Engine revision f546fef7d7
    • Dart version 3.6.0 (build 3.6.0-102.0.dev)
    • DevTools version 2.37.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at 
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)

[✓] Network resources

• No issues found!
```
</details>
