### ISSUE TITLE
Flutter running at the iphone：Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string 

### ISSUE THREAD

**Issue by DamonRao** [flutter/flutter#134513] opened 2023-09-12 08:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、run on the iPhone
2、special words
3、Bad UTF-8

### Expected results

"singer_id":563,"song_title":"奥云格日乐 - 跟着扎西去西藏","singer_name":"奥云格日乐","pinyin_first":"�","

### Actual results

Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: flutter: ║ "singer_id":563,"singer_name":"°ÂÔÆ¸ñÈÕÀÖ","pinyin_first":"�","alb. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[102, 108, 117, 116, 116, 101, 114, 58, 32, 226, 149, 145, 32, 95, 49, 47, 229, 165, 165, 228, 186, 145, 230, 160, 188, 230, 151, 165, 228, 185, 144, 32, 45, 32, 232, 183, 159, 231, 157, 128, 230, 137, 142, 232, 165, 191, 229, 142, 187, 232, 165, 191, 232, 151, 143, 46, 109, 112, 51, 34, 44, 34, 115, 105, 110, 103, 101, 114, 95, 105, 100, 34, 58, 53, 54, 51, 44, 34, 115, 105, 110, 103, 101, 114, 95, 110, 97, 109, 101, 34, 58, 34, 194, 176, 195, 130, 195, 148, 195, 134, 194, 184, 195, 177, 195, 136, 195, 149, 195, 128, 195, 150, 34, 44, 34, 112, 105, 110, 121, 105, 110, 95, 102, 105, 114, 115, 116, 34, 58, 34, 239, 191, 189, 34, 44, 34, 97, 108, 98]

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: flutter: ║ _1/奥云格日乐 - 跟着扎西去西藏.mp3","singer_id":563,"singer_name":"°ÂÔÆ¸ñÈÕÀÖ","pinyin_first":"�","alb. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:

**Comment by dam-ease** [comment] 2023-09-12 12:00
Hi @DamonRao. Thanks for filing this issue. From your comments, I deduce you are trying to render a text and getting an error message. I tried reproducing this on an iPhone 14 Pro (iOS 16.4) with the code sample below and couldn't reproduce this.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: PopScope(
        child: Scaffold(
          appBar: AppBar(title: const Text('Sample')),
          body: const ExpansionTileExample(),
        ),
      ),
    );
  }
}

class ExpansionTileExample extends StatelessWidget {
  const ExpansionTileExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Text(
            '"singer_id":563,"song_title":"奥云格日乐 - 跟着扎西去西藏","singer_name":"奥云格日乐","pinyin_first":"�","')
      ],
    );
  }
}

``` 

</p>
</details>

<details><summary>Screenshot</summary>
<p>

![Simulator Screenshot - iPhone 14 Pro - 2023-09-12 at 12 54 55](https://github.com/flutter/flutter/assets/53122008/3699d3f0-1ee0-40f0-baf0-6599cc1c6711)


</p>
</details>  

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.3 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 13 Pro (mobile)      • 14B6FEE4-2F1C-401F-8804-A5115D7A6DA2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.211, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-14.0.pre.211 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69f6e7d15d (16 hours ago), 2023-09-11 00:50:38 -0400
    • Engine revision 7e41b064eb
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 13 Pro (mobile)      • 14B6FEE4-2F1C-401F-8804-A5115D7A6DA2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details> 

Please when opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue as with the information provided, I'm unable to reproduce this issue. Once you update the issue with more information as mentioned above, please write in the comments and I will re-open this for further discussion. 
Thanks!

**Closed by dam-ease** 2023-09-12 12:00 UTC
Labels: in triage

**Comment by kmatsumotoA** [comment] 2023-09-14 03:49
I also have a similar problem  
```
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: flutter: GIF89a����,D;. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[102, 108, 117, 116, 116, 101, 114, 58, 32, 71, 73, 70, 56, 57, 97, 1, 0, 1, 0, 239, 191, 189, 0, 0, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 0, 0, 44, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 68, 1, 0, 59]
```

**Comment by dam-ease** [comment] 2023-09-14 04:50
Hi @kmatsumotoA. Please provide the information as mentioned here https://github.com/flutter/flutter/issues/134513#issuecomment-1715590834 so we could triage this properly

**Comment by ditman** [comment] 2023-11-02 18:44
Reported again here: https://github.com/flutter/flutter/issues/137025

This seems to have to do with using `print` in the app, which goes to the tool and then crashes.
