### ISSUE TITLE
Building a program with a syntax error works fine as long as you build twice.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19287] opened 2018-07-11 23:27 UTC
Reproduction steps:
1. `flutter create test`
2. replace the `lib/main.dart` with:
```dart
import 'package:flutter/widgets.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Placeholderrr(); // Typo is intentional!
  }
}
```
3. compile it once with `flutter build apk --debug` and see an error message.
4. compile it again with the same command, and see it succeed (as below)

This will really help with fixing syntax errors while coding!  We just have to compile twice! :+1: 

```
(home/gspencer:master) -- test > flutter build apk --debug
Running "flutter packages get" in test_reload...             0.6s
Initializing gradle...                                       1.0s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleDebug'...                               
compiler message: lib/main.dart:9:18: Error: Method not found: 'Placeholderrr'.
compiler message:     return const Placeholderrr();
compiler message:                  ^
Compiler failed on lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/google/home/gspencer/code/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 450

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/usr/local/google/home/gspencer/code/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Gradle build failed: 1
(home/gspencer:master) -- test > flutter build apk --debug
Initializing gradle...                                       1.0s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleDebug'...                           8.5s
Built build/app/outputs/apk/debug/app-debug.apk.

```

**Comment by zoechi** [comment] 2018-07-12 09:46
Does your Flutter version include this fix already #18800?

**Comment by gspencergoog** [comment] 2018-07-12 15:45
Yes, it includes 75b737ff695afba5ec8b4e313c130c520b3651fb.  I'm using the master branch HEAD revision from yesterday.

**Comment by zoechi** [comment] 2019-02-14 16:56
I think this is a duplicate of #23121 and https://github.com/dart-lang/sdk/issues/35666 which was fixed 13 days ago.

**Closed by zoechi** 2019-02-14 16:56 UTC
Labels: tool

**Comment by zoechi** [comment] 2019-02-14 16:58
Just checked and can not reproduce
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```
