### ISSUE TITLE
'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 464 pos 12: 'lastDetails is DragUpdateDetails': is not true.

### ISSUE THREAD

**Issue by rgr** [flutter/flutter#90437] opened 2021-09-21 07:49 UTC
## Steps to Reproduce

Like in other previous issues (https://github.com/flutter/flutter/issues/25142, https://github.com/flutter/flutter/issues/66240), I have a crash caused by the scroll bar but only on iOS on a DropdownButtonFormField.

<details>
<summary>code sample</summary>

```dart
import 'package:async_redux/async_redux.dart';
import 'package:flutter/material.dart';

import '../../../helpers.dart';
import '../../../localization.dart';
import '../../../redux/user_actions.dart';
import '../../../theme.dart';

class UserDropDown extends StatefulWidget {
  const UserDropDown({
    Key? key,
    required this.label,
    required this.field,
    required this.items,
    required this.selected,
  }) : super(key: key);

  final String field;
  final List<DropdownMenuItem> items;
  final String label;
  final dynamic selected;

  @override
  _UserDropDownState createState() => _UserDropDownState();
}

class _UserDropDownState extends State<UserDropDown> {
  dynamic _selected;

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _selected = widget.selected;
  }

  void _updateUser(field, value, context) {
    if (field == 'gender') {
      StoreProvider.dispatch(context, UserUpdateAction(gender: value));
    } else if (field == 'birth') {
      StoreProvider.dispatch(context, UserUpdateAction(birth: value));
    } else if (field == 'education') {
      StoreProvider.dispatch(context, UserUpdateAction(education: value));
    } else if (field == 'context') {
      StoreProvider.dispatch(context, UserUpdateAction(context: value));
    } else if (field == 'language') {
      StoreProvider.dispatch(context, UserUpdateAction(language: value));
    } else if (field == 'nationality') {
      StoreProvider.dispatch(context, UserUpdateAction(nationality: value));
    } else if (field == 'timezone') {
      StoreProvider.dispatch(context, UserUpdateAction(timezone: value));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: App.size(60, context),
      margin: EdgeInsets.symmetric(
        vertical: App.margin(context) / 2,
      ),
      padding: EdgeInsets.only(
        bottom: App.size(10, context),
        left: App.padding(context),
        right: App.padding(context),
      ),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(App.radius()),
        color: AppTheme.colorGrey[200],
      ),
      child: Center(
        child: Row(
          children: <Widget>[
            SizedBox(
              width: App.size(110, context),
              child: Padding(
                padding: EdgeInsets.only(
                  top: App.size(10, context),
                ),
                child: Text(
                  widget.label,
                  style: Theme.of(context).textTheme.subtitle1?.apply(
                        fontSizeFactor: App.fontFactor(context),
                      ),
                  softWrap: false,
                  overflow: TextOverflow.fade,
                ),
              ),
            ),
            SizedBox(width: App.size(20, context)),
            Expanded(
              child: DropdownButtonFormField<dynamic>(
                items: widget.items,
                value: _selected,
                isDense: App.isLarge(context) ? false : true,
                onChanged: (value) {
                  setState(() {
                    _selected = value;
                  });
                  _updateUser(widget.field, value, context);
                },
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null) {
                    return AppLocalizations.of(context).i18n('error.form.empty');
                  }

                  return null;
                },
                decoration: InputDecoration(
                  hintText: AppLocalizations.of(context).i18n('common.form.dropdown.select'),
                  hintStyle: Theme.of(context).textTheme.subtitle1?.apply(
                        color: AppTheme.colorGrey[900],
                        fontSizeFactor: App.fontFactor(context),
                      ),
                  errorStyle: Theme.of(context).textTheme.subtitle1?.apply(
                        fontSizeFactor: App.fontFactor(context),
                        color: AppTheme.colorError,
                      ),
                  contentPadding: EdgeInsets.only(
                    top: App.isSmall(context) ? -4 : 10,
                  ),
                  border: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  errorBorder: InputBorder.none,
                  focusedErrorBorder: InputBorder.none,
                  disabledBorder: InputBorder.none,
                ),
                isExpanded: true,
                iconEnabledColor: AppTheme.colorAccent,
                dropdownColor: AppTheme.colorGrey[200],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

```dart
import 'package:flutter/material.dart';

import '../../../data/sources/local_api.dart';
import '../../../helpers.dart';
import '../../../localization.dart';
import '../../../theme.dart';
import '../loading/loading_widget.dart';
import 'user_dropdown_widget.dart';

class Nationality extends StatelessWidget {
  Nationality({Key? key, required this.nationality}) : super(key: key);

  final String? nationality;

  List<DropdownMenuItem<String>> _buildItems(data, context) {
    List<DropdownMenuItem<String>> items = [];
    data.forEach((iso, name) {
      items.add(DropdownMenuItem<String>(
        value: iso,
        child: Text(
          name,
          style: Theme.of(context).textTheme.subtitle1?.apply(fontSizeFactor: App.fontFactor(context)),
        ),
      ));
    });

    return items;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<dynamic>(
      future: LocalApi.getData('/lang/' + App.locale(context) + '/nationalities.json'),
      builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
        Widget child;

        if (snapshot.hasData) {
          child = UserDropDown(
            label: AppLocalizations.of(context).i18n('onboarding.personal.nationality'),
            field: 'nationality',
            selected: this.nationality,
            items: _buildItems(snapshot.data, context),
          );
        } else if (snapshot.hasError) {
          child = Text(
            AppLocalizations.of(context).i18n('error.asset.title.nationalities'),
            style: Theme.of(context)
                .textTheme
                .subtitle1
                ?.apply(fontSizeFactor: App.fontFactor(context), color: AppTheme.colorError),
          );
        } else {
          child = Loading();
        }

        return child;
      },
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
Analyzing ios...                                                        
No issues found! (ran in 3.9s)
```

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-arm, locale fr-FR)
    • Flutter version 2.5.1 at /Users/rgr/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/rgr/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone de Raphaël (mobile) • 555e5664f6e9a581deba0a0f33dd56436e9a4d1a • ios            • iOS 14.7.1 18G82
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment] 2021-09-21 08:36
Hi @rgr, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exact steps to reproduce the issue. The code sample shared above contains a lot of unknown variables, I modified the above code to reduce the unknown variables but could not reproduce the crash or see any exception.


<details>
<summary>modified code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(Nationality(
    nationality: '2',
  ));
}

class Nationality extends StatelessWidget {
  const Nationality({Key? key, required this.nationality}) : super(key: key);

  final String? nationality;

  List<DropdownMenuItem<String>> _buildItems(data, context) {
    List<DropdownMenuItem<String>> items = [];

    data.forEach((String iso) {
      items.add(DropdownMenuItem<String>(
        value: '$iso',
        child: Text(
          'item $iso',
          style:
              Theme.of(context).textTheme.subtitle1?.apply(fontSizeFactor: 20),
        ),
      ));
    });

    return items;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.grey.shade100,
        body: Center(
          child: FutureBuilder<dynamic>(
            future: Future.delayed(Duration(seconds: 1), () {
              return true;
            }),
            builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
              Widget child;

              if (snapshot.hasData) {
                child = UserDropDown(
                  label: 'onboarding.personal.nationality',
                  field: 'nationality',
                  selected: this.nationality,
                  items: _buildItems(
                      List.generate(20, (index) => index.toString()).toList(),
                      context),
                );
              } else if (snapshot.hasError) {
                child = Text(
                  'error.asset.title.nationalities',
                  style: Theme.of(context)
                      .textTheme
                      .subtitle1
                      ?.apply(fontSizeFactor: 20, color: Colors.red),
                );
              } else {
                child = Center(
                  child: CircularProgressIndicator(),
                );
              }

              return child;
            },
          ),
        ),
      ),
    );
  }
}

class UserDropDown extends StatefulWidget {
  const UserDropDown({
    Key? key,
    required this.label,
    required this.field,
    required this.items,
    required this.selected,
  }) : super(key: key);

  final String field;
  final List<DropdownMenuItem> items;
  final String label;
  final dynamic selected;

  @override
  _UserDropDownState createState() => _UserDropDownState();
}

class _UserDropDownState extends State<UserDropDown> {
  dynamic _selected;

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _selected = widget.selected;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 20,
      margin: EdgeInsets.symmetric(
        vertical: 20,
      ),
      padding: EdgeInsets.only(
        bottom: 20,
        left: 20,
        right: 20,
      ),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          color: Colors.grey.withOpacity(0.2)),
      child: Center(
        child: Row(
          children: <Widget>[
            SizedBox(
              width: 20,
              child: Padding(
                padding: EdgeInsets.only(
                  top: 20,
                ),
                child: Text(
                  widget.label,
                  style: Theme.of(context).textTheme.subtitle1?.apply(
                        fontSizeFactor: 20,
                      ),
                  softWrap: false,
                  overflow: TextOverflow.fade,
                ),
              ),
            ),
            SizedBox(width: 20),
            Expanded(
              child: DropdownButtonFormField<dynamic>(
                items: widget.items,
                value: _selected,
                // isDense: true,
                onChanged: (value) {
                  setState(() {
                    _selected = value;
                  });
                  // _updateUser(widget.field, value, context);
                },
                autovalidateMode: AutovalidateMode.onUserInteraction,
                decoration: InputDecoration(
                  hintText: 'common.form.dropdown.select',
                  hintStyle: Theme.of(context).textTheme.subtitle1?.apply(
                        color: Colors.grey,
                        fontSizeFactor: 1,
                      ),
                  errorStyle: Theme.of(context).textTheme.subtitle1?.apply(
                        fontSizeFactor: 20,
                        color: Colors.red,
                      ),
                  contentPadding: EdgeInsets.only(
                    top: 20,
                  ),
                  border: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  errorBorder: InputBorder.none,
                  focusedErrorBorder: InputBorder.none,
                  disabledBorder: InputBorder.none,
                ),
                isExpanded: true,
                iconEnabledColor: Colors.green,
                dropdownColor: Colors.blue,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by rgr** [comment] 2021-09-21 14:25
Thanks for the quick reply @maheshmnj. I recreated a very simple widget with no variables and it still crashes on iOS.

```dart
import 'package:flutter/material.dart';

class DropTest extends StatefulWidget {
  const DropTest({Key? key}) : super(key: key);

  @override
  _DropTestState createState() => _DropTestState();
}

class _DropTestState extends State<DropTest> {
  String name = 'john';

  List<DropdownMenuItem<String>> _buildItems() {
    List options = ['john', 'lisa', 'robert', 'marie', 'jane', 'bruce', 'elton', 'june', 'raph', 'margot'];
    List<DropdownMenuItem<String>> items = [];
    options.forEach((name) {
      items.add(DropdownMenuItem<String>(
        value: name,
        child: Text(name),
      ));
    });

    return items;
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      items: _buildItems(),
      onChanged: (value) async {
        setState(() {
          this.name = value!;
          print(this.name);
        });
      },
      value: this.name,
      validator: (value) => value == null ? 'Please fill in your name' : null,
    );
  }
}
```

**Comment by maheshmnj** [comment] 2021-09-22 05:16
@rgr please share the output of `flutter doctor -v` I verified on the latest stable `2.5.1` by increasing the list size to make it scrollable and it seems to work fine(no exception or crash).



https://user-images.githubusercontent.com/31410839/134287090-dec1b997-563b-4867-97d6-c7c7c422c5d8.mov





<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          DropTest(),
          SizedBox(height: 100),
        ],
      )),
    );
  }
}

class DropTest extends StatefulWidget {
  const DropTest({Key? key}) : super(key: key);

  @override
  _DropTestState createState() => _DropTestState();
}

class _DropTestState extends State<DropTest> {
  String name = 'item 2';
  List options = List.generate(20, (index) => 'item $index').toList();

  List<DropdownMenuItem<String>> _buildItems() {
    List<DropdownMenuItem<String>> items = [];
    options.forEach((name) {
      items.add(DropdownMenuItem<String>(
        value: name,
        child: Text(name),
      ));
    });

    return items;
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      items: _buildItems(),
      onChanged: (value) async {
        setState(() {
          this.name = value!;
          print(this.name);
        });
      },
      value: this.name,
      validator: (value) => value == null ? 'Please fill in your name' : null,
    );
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      94.0.4606.54

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2021-09-22 05:17
@rgr, I verified on the latest stable `2.5.1` by increasing the list size to make it scrollable and it seems to work fine(no exception or crash).



https://user-images.githubusercontent.com/31410839/134287090-dec1b997-563b-4867-97d6-c7c7c422c5d8.mov





<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          DropTest(),
          SizedBox(height: 100),
        ],
      )),
    );
  }
}

class DropTest extends StatefulWidget {
  const DropTest({Key? key}) : super(key: key);

  @override
  _DropTestState createState() => _DropTestState();
}

class _DropTestState extends State<DropTest> {
  String name = 'item 2';
  List options = List.generate(20, (index) => 'item $index').toList();

  List<DropdownMenuItem<String>> _buildItems() {
    List<DropdownMenuItem<String>> items = [];
    options.forEach((name) {
      items.add(DropdownMenuItem<String>(
        value: name,
        child: Text(name),
      ));
    });

    return items;
  }

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      items: _buildItems(),
      onChanged: (value) async {
        setState(() {
          this.name = value!;
          print(this.name);
        });
      },
      value: this.name,
      validator: (value) => value == null ? 'Please fill in your name' : null,
    );
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      94.0.4606.54

• No issues found!
```
</details>

**Comment by rgr** [comment] 2021-09-22 05:52
Ok so do you have any recommendations about debugging this further since I still have the bug with such a simple example and you don't ?

**Comment by rgr** [comment] 2021-09-22 07:34
Here is the stack trace I get...


flutter: [2021-09-22 09:33:10.527290 | Catcher | INFO] ---------- ERROR ----------
flutter: [2021-09-22 09:33:10.528323 | Catcher | INFO] 'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 464 pos 12: 'lastDetails is DragUpdateDetails': is not true.
flutter: [2021-09-22 09:33:10.528883 | Catcher | INFO]
flutter: [2021-09-22 09:33:10.530365 | Catcher | INFO] ------- STACK TRACE -------
flutter: [2021-09-22 09:33:10.531266 | Catcher | INFO] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
flutter: [2021-09-22 09:33:10.531488 | Catcher | INFO] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
flutter: [2021-09-22 09:33:10.531685 | Catcher | INFO] #2      DragScrollActivity.dispatchScrollUpdateNotification
package:flutter/…/widgets/scroll_activity.dart:464
flutter: [2021-09-22 09:33:10.531920 | Catcher | INFO] #3      ScrollPosition.didUpdateScrollPositionBy
package:flutter/…/widgets/scroll_position.dart:899
flutter: [2021-09-22 09:33:10.532291 | Catcher | INFO] #4      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1243
flutter: [2021-09-22 09:33:10.533119 | Catcher | INFO] #5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
flutter: [2021-09-22 09:33:10.533522 | Catcher | INFO] #6      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
flutter: [2021-09-22 09:33:10.533638 | Catcher | INFO] #7      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
flutter: [2021-09-22 09:33:10.534724 | Catcher | INFO] #8      _rootRun (dart:async/zone.dart:1428:13)
flutter: [2021-09-22 09:33:10.535030 | Catcher | INFO] #9      _CustomZone.run (dart:async/zone.dart:1328:19)
flutter: [2021-09-22 09:33:10.535419 | Catcher | INFO] #10     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
flutter: [2021-09-22 09:33:10.535836 | Catcher | INFO] #11     _invoke (dart:ui/hooks.dart:166:10)
flutter: [2021-09-22 09:33:10.536175 | Catcher | INFO] #12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: [2021-09-22 09:33:10.536580 | Catcher | INFO] #13     _drawFrame (dart:ui/hooks.dart:129:31)

**Comment by maheshmnj** [comment] 2021-09-22 07:46
@rgr, Can you please verify if the issue is occurring on any specific ios version or device? Also, does it reproduce on other platforms like android/web/desktop?

Thanks

**Comment by rgr** [comment] 2021-09-22 07:58
ok I found the origin of the problem it is with StoreConnector, but only on iOS (it works on android, i don't dev for web and desktop).

So this does not work. It produces the crash...
```dart
class MyApp extends StatelessWidget {
    return StoreConnector(
      converter: (Store<AppState> store) => store.state,
      builder: (BuildContext context, AppState state) {
        Sentry.configureScope(
          (scope) => scope.user = SentryUser(
            id: state.user.id.toString(),
            email: state.user.email == '' ? 'guest' : state.user.email,
          ),
        );

        return GestureDetector(
          onTap: () {
            // Close keyboard on touch anywhere
            FocusManager.instance.primaryFocus?.unfocus();
          },
          child: OverlaySupport(
            child: MaterialApp(
              title: 'xxx,
              theme: AppTheme.theme,
              debugShowCheckedModeBanner: false,
              localizationsDelegates: localizationsDelegates,
              supportedLocales: [
                const Locale('en', 'EN'),
                const Locale('fr', 'FR'),
              ],
              navigatorKey: App.navKey,
              navigatorObservers: [BotToastNavigatorObserver()],
              builder: BotToastInit(),
              initialRoute: state.user.id != 0 ? state.meta.route : '/login',
              onGenerateRoute: RouteManager.generateRoute,
            ),
          ),
        );
      },
    );
  }
}
```

and this does work...
```dart
class MyApp extends StatelessWidget {
        return GestureDetector(
          onTap: () {
            // Close keyboard on touch anywhere
            FocusManager.instance.primaryFocus?.unfocus();
          },
          child: OverlaySupport(
            child: MaterialApp(
              title: 'xxx,
              theme: AppTheme.theme,
              debugShowCheckedModeBanner: false,
              localizationsDelegates: localizationsDelegates,
              supportedLocales: [
                const Locale('en', 'EN'),
                const Locale('fr', 'FR'),
              ],
              navigatorKey: App.navKey,
              navigatorObservers: [BotToastNavigatorObserver()],
              builder: BotToastInit(),
              initialRoute: state.user.id != 0 ? state.meta.route : '/login',
              onGenerateRoute: RouteManager.generateRoute,
            ),
          ),
        );
  }
}
```

So I found the origin but I have no idea why it makes it crash...

**Comment by maheshmnj** [comment] 2021-09-22 09:12
@rgr `StoreConnector` seems to be a third-party plugin and unfortunately, we do not provide support to issues caused by a third-party plugin. Probably you should try filing the issue in the dedicated repository and see if that helps.

Closing this issue as invalid, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-22 09:12 UTC
Labels: in triage

**Comment by rgr** [comment] 2021-09-22 09:55
My bad I was sure StoreConnector was from the flutter framework... Thanks for your reply @maheshmnj !
