### ISSUE TITLE
Android app, scrolling is super jagged, slow Raster

### ISSUE THREAD

**Issue by maxim-saplin** [flutter/flutter#107380] opened 2022-07-10 20:18 UTC
The app has large selectable rich text spans wrapped in scrollable. Haven't seen the issues on Flutter 2+ and Galaxy Note 10 (Snapdragon), the issue appeared on Flutter 3 and Galaxy S22 (Exynos).

https://user-images.githubusercontent.com/7947027/178160805-7b6f6e87-80af-4986-9b0e-8988941760bb.mp4

**Target Platform: Android 12, One UI 4.1, June 1, 2022 Google Play system Updates**
**Devices: Samsung Galaxy S22, Exynos 2200,  SM-S902B/DS**

## Logs

<details>
<summary>Logs</summary>

[dart_devtools_2022_7_10-1657484036392000.json.zip](https://github.com/flutter/flutter/files/9079804/dart_devtools_2022_7_10-1657484036392000.json.zip)

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-BY)
    • Flutter version 3.0.4 at /private/var/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /private/var/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM S901B (mobile) • R3CT209M59R • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2022-07-11 08:28
Hi @maxim-saplin, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by maxim-saplin** [comment] 2022-07-11 09:39
Here we go, please find minimal repro case and Dev Tools/Performance export.

[bug.zip](https://github.com/flutter/flutter/files/9082740/bug.zip)
[dart_devtools_2022_7_11-1657531512725000.json.zip](https://github.com/flutter/flutter/files/9082741/dart_devtools_2022_7_11-1657531512725000.json.zip)

Please note that there's some inconsistency in stutters, on one occasion you can get little to no lags, in other cases you get plenty of stuttering. You might want to scroll a bit and try launching the app several times. The logs come from the time when scrolling is laggy.

**Comment by exaby73** [comment] 2022-07-11 11:50
Helo @maxim-saplin. This looks like an optimization issue on your end. You are using a single widget, `SelectableText` in this case, that is very large and wrapped in a `SingleChildScrollView`. This is causing Flutter to re-build the entire widget every frame which is causing the lag you see. Try to split the one large widget into multiple widgets. For example: if your requirement is to display a large amount of text, maybe split the text into multiple paragraphs and render each paragraph in a `ListView.builder`. That way, Flutter can only build what needs to be built and not all the text at once which will fix this issue you are experiencing.

As for it occurring only in Flutter 3, I was unable to re-produce that part. I was able to notice lag in Flutter 2.10.5 as well. All in all, you should try to split your one very large widget into smaller pieces and use a `ListView.builder` instead of a `SingeChildScrollView`.

Upon further investigation, this issue (https://github.com/flutter/flutter/issues/59404) seems to highlight the same issue. You can use the solution I suggested above as a workaround until this gets fixed. Closing this issue as a duplicate. You can try to follow up and post your findings on the original issue.

**Closed** 2022-07-11 11:51 UTC
Labels: in triage

**Comment by maxim-saplin** [comment] 2022-07-11 12:09
@exaby73 , I don't think that rebuilding widget (UI thread) is the cause of issues, on the contrary Raster thread gets slow and frame take 50+ ms to draw.

ListView.builder, virtual scrolling won't allow text selection across 'invisible' sections of lazily built widgets.

Did you have a chance to check the performance logs?

Speaking of the root cause (Flutter 2 vs Flutter 3 or Snapdragon or Exynos) and whether the issue persisted before... Unfortunately I don't have my Snapdragon device to check, though I'm sure scrolling issues where not present in the app built with Flutter 2.5 when ran on Galaxy Note 10 as I use my app daily and always notice freezes.

**Comment by exaby73** [comment] 2022-07-12 06:15
@maxim-saplin I see your point there. Though this issue still does seem like a duplicate of https://github.com/flutter/flutter/issues/59404. Maybe posting your findings there might yield better results.
