### ISSUE TITLE
Could not hide ad immediately after displaying ad on flutter

### ISSUE THREAD

**Issue by ganessaa** [flutter/flutter#21474] opened 2018-09-06 01:18 UTC
We have created the following class to display AdMob on flutter.

```dart
    import 'package:firebase_admob/firebase_admob.dart';
    import 'package:xxxxx/models/const.dart';
    
    class Ads {
      static BannerAd _bannerAd;
    
      static init() {
        FirebaseAdMob.instance.initialize(appId: Const.adAppId);
      }
    
      static BannerAd createBannerAd() {
        return new BannerAd(
          adUnitId: Const.adUnitId,
          size: AdSize.banner,
          targetingInfo: targetingInfo,
          listener: (MobileAdEvent event) {
            print("@@@ $event @@@");
          },
        );
      }
    
      static void showBanner() {
        if (_bannerAd == null) {
          _bannerAd = createBannerAd();
        }
    
        print('@@@ load @@@');
        _bannerAd.load().then((load) {
          print('@@@ show @@@');
          _bannerAd.show(anchorType: AnchorType.bottom);
        });
      }
    
      static void hideBanner() {
        print('@@@ dispose @@@');
        _bannerAd?.dispose();
        print('@@@ null @@@');
        _bannerAd = null;
      }
    
      static final MobileAdTargetingInfo targetingInfo = new MobileAdTargetingInfo(
        testDevices: Const.testDevices,
        keywords: Const.keywords,
        birthday: new DateTime.now(),
        gender: MobileAdGender.female,
      );
    }
```

The following values are correctly defined in the Const class.

`adAppId`, `adUnitId`, `testDevices`, `keywords`

`init()` is called immediately after startup.
`showBanner()` will be called when showing the ad.
`hideBanner()` will be called when hiding the ad.

These will work as expected in most cases.

But after `_bannerAd.show()` is called, the ad will not be hidden if `hideBanner()` is called before the listener receives `MobileAdEvent.loaded`.

[OK]
`_bannerAd.show()` -> receive `MobileAdEvent.loaded` -> `hideBanner()`
flutter: @@@ load @@@
flutter: @@@ show @@@
flutter: @@@ MobileAdEvent.loaded @@@
flutter: @@@ dispose @@@
flutter: @@@ null @@@

[NG]
`_bannerAd.show()` -> `hideBanner()` -> (receive `MobileAdEvent.loaded`)
flutter: @@@ load @@@
flutter: @@@ show @@@
flutter: @@@ dispose @@@
flutter: @@@ null @@@

This trouble occurred in ASUS Z017DA. iPad mini, iPhone 6 Plus and iPhone 4S were hidden normally at any timing. We can not test all models, but it may be a problem only for Android.

How can we avoid this if we do?

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.7.5, on Mac OS X 10.13.6 17G65, locale ja)
    • Flutter version 0.7.5 at /Applications/flutter
    • Framework revision eab5cd9853 (6 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxxxx/src/android-sdks
    • Android NDK at /Users/xxxxx/src/android-sdks/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxxxx/src/android-sdks
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • ASUS Z017DA   • XXXXXXXXXXXXXXX                          • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 6 Plus • xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios           • iOS 11.4.1

• No issues found!
```

**Comment by AnandGupta7866** [comment] 2019-01-28 09:13
How to hide ads if we navigate to another page before the ad is loaded?????

**Comment by LatinaIsaac** [comment] 2019-02-27 15:51
bump

**Comment by jsplashindia** [comment] 2019-06-08 10:14
Is there any solution to this problem yet?

**Comment by d-apps** [comment] 2019-07-05 16:36
Same, I can't hide banner from the screen.

**Comment by zukinaru** [comment] 2019-07-15 09:24
any idea about how to hide / remove banner immediately ?

**Comment by Piotr-Retman** [comment] 2019-09-04 22:56
I was fighting with this problem same like you but the solution for this to hide Ad should be like this:

1) Consider creating methods which will  
a) provide the Banner for your app 
b) dispose. 

2) Add ad to your view in` initialState() `not `build()` method (So It should be more like StatefulWidget than StatelessWidget where you use Ads)
3) Override  `dispose()` method for your component view where you will call the dispose method on your Ad
4) Done - when you 'travel' from one Route to another it will show and hide the Ad

**Comment by izinin** [comment] 2019-09-25 20:03
@Piotr-Retman : it looks like your advice is "theoretically it should work" . in reality i hit the problem with exactly the same scheme as you suggested. My ad banner is defined in the application singleton. In addition to that i have a flag which i check in OnLoaded callback to know if i need immediatelly close the banner after loading. That prevents some missynchronisation issue during page navigation . It works nicely in debug mode but in release published Ad behaviour is different it cannot not hide at all. I think the problem is more serious than it looks. **The behaviour of ad plugin is different in release and debug mode.**

`
// in the app singleton  class
  BannerAd _myBanner;
  bool _bannerHidden;

void showAdBanner({VoidCallback onLoaded, VoidCallback onError}) {
    if(_myBanner != null) {
      return;
    }
    _bannerHidden = false;
    _myBanner = BannerAd(
....
        listener: (MobileAdEvent event) async {
          if (event == MobileAdEvent.loaded && onLoaded != null) {
            if(_bannerHidden){
               hideAdBanner();
            }else{
               onLoaded();
            }
          } else if (event == MobileAdEvent.failedToLoad && onError != null) {
..
          }
        });
    _myBanner..load()..show(anchorType: AnchorType.bottom);
  }

  void hideAdBanner() {
    _bannerHidden = true;
    _myBanner?.dispose();
    _myBanner = null;
  }


`

**Comment by kroikie** [comment] 2019-10-13 18:52
@ganessaa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/669. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:34
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iTikoz** [comment] 2020-04-27 22:11
workaround is: using "this.mounted" property of state class before showing the add

```
  _bannerAd = createBannerAd();
    _bannerAd
  ..load().then((loaded) {
    if (loaded && this.mounted) {
      _bannerAd..show();
    }
  });
```

**Comment by jacaTM** [comment] 2020-05-28 22:42
I managed to resolve it by creating a boolean that sets to true when I call my function hideBanner(), and checking if it's true when the banner event is loaded. Look at my code:

`BannerAd _createBanner(){
    return BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      targetingInfo: getTargetInfo(),
      listener: (MobileAdEvent event) {
        if (event == MobileAdEvent.loaded)
          if(disposed)_bannerAd.dispose();
          else _bannerAd.show(
              anchorOffset: kBottomNavigationBarHeight+15.0,
              anchorType: AnchorType.bottom
          );
      }
    );
  }

  void displayBanner() async {
    disposed = false;
    if(_bannerAd == null) _bannerAd = _createBanner();
    _bannerAd.load();
  }

  void hideBanner() async {
    await _bannerAd?.dispose();
    disposed = true;
    _bannerAd = null;
  }`

**Comment by BoHellgren** [comment] 2020-11-09 14:35
I have spent many hours debugging this _dispose_ problem. And found a perfect solution: Don't use the firebase_admob plugin! Use the admob_flutter  plugin instead. Very easy to use and works like a dream.

**Comment by srsudar** [comment] 2021-02-04 04:40
jacaTM's answer hides the ad for me correctly (finally!), but I'm occasionally getting this error:

```
'package:firebase_admob/firebase_admob.dart': Failed assertion: line 249 pos 12: '_allAds[id] != null': is not true.
```

Has anyone figured out how to resolve this? Not sure where I'm going wrong.

**Comment by FonzTech** [comment] 2021-03-23 18:00
@srsudar I fixed this error by adding a line like this:
`print("FixForHashcode " + DateTime.now().millisecondsSinceEpoch.toString());`
so the `id` variable will change "forcefully".
Let us know.

**Comment by stuartmorgan** [comment] 2021-05-25 19:18
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).

**Closed by stuartmorgan** 2021-05-25 19:18 UTC
Labels: P4, p: firebase, p: firebase_admob, p: first party, plugin, transferred
