### ISSUE TITLE
DevFS sync failed. Lost connection to device - Flutter v1.10.6-pre.29

### ISSUE THREAD

**Issue by edufolly** [flutter/flutter#41092] opened 2019-09-23 11:26 UTC
## Steps to Reproduce

1. Run the app in iOS Simulator

In Android works great.

## Logs

[full log](https://drive.google.com/open?id=1r5DIDinvOZy9Bj2SJ3WN-OIoQGFU0hYT)
```
[   +9 ms] Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50731
[        ] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50731
[        ] Syncing files to device iPhone Xs Max... (completed in 2.215ms, longer than expected)
[   +3 ms] "flutter run" took 64.013ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:485:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#54     _rootRunUnary (dart:async/zone.dart:1132:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1132:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#66     Future._complete (dart:async/future_impl.dart:512:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:204:14)
#68     _rootRun (dart:async/zone.dart:1120:38)
#69     _CustomZone.run (dart:async/zone.dart:1021:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#80     _rootRun (dart:async/zone.dart:1120:38)
#81     _CustomZone.run (dart:async/zone.dart:1021:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#88     _StreamController.close (dart:async/stream_controller.dart:622:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1836:21)
#90     _rootRunUnary (dart:async/zone.dart:1136:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#96     _StreamController._add (dart:async/stream_controller.dart:640:7)
#97     _StreamController.add (dart:async/stream_controller.dart:586:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale pt-BR)
    • Flutter version 1.10.6-pre.29 at /Users/edufolly/Documents/flutter
    • Framework revision 919cc97f6a (3 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edufolly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/edufolly/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • iPhone Xs Max • 923ECBA9-8B6F-4065-8DEF-287A3E13D356 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • Chrome        • chrome                               • web-javascript • Google Chrome 76.0.3809.132
    • Server        • web                                  • web-javascript • Flutter Tools

• No issues found!
```

**Comment by christopherfujino** [comment] 2019-09-23 20:13
@edufolly I'm not able to reproduce this, I'm wondering does this happen for you every single time or is it intermittent?

**Comment by zanderso** [comment] 2019-09-24 17:11
I'm having trouble making sense of the stack trace in https://github.com/flutter/flutter/issues/41092#issue-497039767. We should investigate whether there is an orthogonal tool issue that results in confusing stack traces.

**Comment by christopherfujino** [comment] 2019-10-11 17:00
@edufolly could you try upgrading to the latest master and seeing if you still hit this? I'm not sure if I fixed this particular issue, but there was a bug I fixed in which we were port forwarding twice, and I imagine that could have caused all kinds of weird behavior.

**Comment by edufolly** [comment] 2019-10-11 22:21
@christopherfujino no problem with the updated master version.

```[✓] Flutter (Channel master, v1.10.15-pre.85, on Mac OS X 10.15 19A583, locale pt-BR)```

**Comment by christopherfujino** [comment] 2019-10-11 22:24
I'm going to optimistically close this then, thanks!

**Closed by christopherfujino** 2019-10-11 22:24 UTC
Labels: e: device-specific, severe: crash, tool, ⌺‬ platform-ios
