### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Program Files\Java\jre-1.8\bin\bin\bin\java" in the search path. Command: C:\Program Files\Java\jre-1.8\bin\bin\bin\java, OS error code: 0

### ISSUE THREAD

**Issue by CanIhave1cupoftea** [flutter/flutter#139964] opened 2023-12-12 08:20 UTC
## Command
```
flutter create app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Program Files\Java\jre-1.8\bin\bin\bin\java" in the search path. Command: C:\Program Files\Java\jre-1.8\bin\bin\bin\java, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:377:51)
#5      Java.version.<anonymous closure> (package:flutter_tools/src/android/java.dart:139:44)
#6      Java.version (package:flutter_tools/src/android/java.dart:179:5)
#7      Java.version (package:flutter_tools/src/android/java.dart)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:510:41)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.19045.3693], locale en-PH)
    [32m•[39m Flutter version 3.16.3 on channel stable at C:\Programming\Flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0366e0a3f (6 days ago), 2023-12-05 19:46:39 -0800
    [32m•[39m Engine revision 54a7145303
    [32m•[39m Dart version 3.2.3
    [32m•[39m DevTools version 2.28.4

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.85.0)
    [32m•[39m VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.78.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.61

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by dam-ease** [comment] 2023-12-12 08:29
Hi @CanIhave1cupoftea.
This is a duplicate of https://github.com/flutter/flutter/issues/139180, which was already just fixed in https://github.com/flutter/flutter/pull/139614 and has been nominated for cherrypicking into stable at https://github.com/flutter/flutter/issues/139699.

**Closed by dam-ease** 2023-12-12 08:29 UTC
Labels: in triage
