### ISSUE TITLE
[in_app_purchase] android subscribe alpha-testing error "consume_purchase_failed"

### ISSUE THREAD

**Issue by ale-getman** [flutter/flutter#51777] opened 2020-03-02 16:36 UTC
The application is in the play store, for the new version added the **in_app_purchase** plugin. And try it on the alpha version for subscriptions.
It is impossible to see in the debug, since the subscription is visible only on the alpha version from the market.
Here's what print shows
`ProductDetailsResponse productDetailResponse =
        await _connection.queryProductDetails(_kProductIdsAndroid.toSet());`
After this code, when the screen starts, productDetails.error! = Null, since it does not fall into the desired if.
But on the button there is a product and price, and when trying to buy a subscription, the standard google play market window appears for subscribing, after a purchase in the listener
![image](https://user-images.githubusercontent.com/6009175/75696835-4128f900-5cbd-11ea-9541-72de052c9077.png)

 **I get stuck on an error,but at the same time the user becomes active.**
IN APP PURCHASE CODE: consume_purchase_failed
IN APP PURCHASE DETA: Invalid token.
IN APP PURCHASE MESS: BillingResponse.developerError
IN APP PURCHASE SOUR: IAPSource.GooglePlay

Why is this so and what am I doing wrong, since it seems to me that everything has been done to the manuals.
Help me please.)

**Comment by jovanovski** [comment] 2020-04-03 16:58
I have the same exact issue in Alpha. Will try moving it to Beta and see if it works, will get back to you.

**Comment by hatano0x06** [comment] 2020-04-17 13:06
I have a same problem and cannot release by this issue.
I want to know What version can be ok, and When those this fix.

**Comment by jovanovski** [comment] 2020-04-17 13:16
For me the fix was just to wait. Once uploading a alpha/beta build, and making sure I had the same build number on my test phone, I had to wait for ~12 hours for everything to propagate, and then it worked flawlessly.

**Comment by hatano0x06** [comment] 2020-04-17 13:18
I'm very happy to hear it.
I will silent release to beta version and check it by myself too

Thank you!

**Comment by renefloor** [comment] 2021-04-14 11:50
@ale-getman is this still an issue for you? We could not reproduce this, so we guess this was solved by waiting a little bit for the purchase to become available in the play store.

**Comment by pedromassangocode** [comment] 2021-05-07 11:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 11:09 UTC
Labels: p: first party, p: in_app_purchase, plugin, waiting for customer response
