### ISSUE TITLE
[video_player] Playing video using Byte data (uint8list)

### ISSUE THREAD

**Issue by markgrancapal** [flutter/flutter#59387] opened 2020-06-13 07:57 UTC
I'm using flutter web, and I have an html.file that contains the video.

**Comment by thedejifab** [comment] 2020-09-01 17:15
Any progress on this feature?

**Comment by mhbdev** [comment] 2020-10-19 08:46
I just got the blob data out of `html.File` using `html.FileReader` and gave it to an `html.VideoElement` src but it is not working :( That works fine in a simple html file. I tried to give blob string to VideoController.network dataSource but it does not work either.

```html
<html>
<body>
<video src="data:application/octet-stream................"></video>
</body>
</html>
```

Can anybody explain how to load Uin8List or blob data to a simple video player! (Web)

**Comment by AlaaEldeenYsr** [comment] 2020-11-22 21:42
How can i do this in flutter mobile ?

**Comment by mikron123** [comment] 2020-11-22 22:13
> I just got the blob data out of `html.File` using `html.FileReader` and gave it to an `html.VideoElement` src but it is not working :( That works fine in a simple html file. I tried to give blob string to VideoController.network dataSource but it does not work either.
> 
> ```
> <html>
> <body>
> <video src="data:application/octet-stream................"></video>
> </body>
> </html>
> ```
> 
> Can anybody explain how to load Uin8List or blob data to a simple video player! (Web)
> 
> **Update:**
> Convert your Uint8List to blob data then use `VideoPlayerController.network` to load blob string to VideoElement src. (This works fine for video_player_web)
> You can also upload your videos then use the upload url to load the video from the internet.

How did you convert the Uint8List to Blob data?

**Comment by AlaaEldeenYsr** [comment] 2020-12-13 14:40
Any updates in this feature

**Comment by devanflores** [comment] 2021-01-21 03:56
Hey @mhbdev could you give us a little bit of code to show how to do this? I'm definitely stuck

**Comment by yaizudamashii** [comment] 2021-02-01 03:07
@devanflores 
https://stackoverflow.com/questions/65821003/flutter-web-playing-uint8list-n-videoplayer/65834130

**Comment by krish-bhanushali** [comment] 2021-03-10 06:53
I tried doing this, uploaded video file in web using file picker. I got the bytes in Uintlist and converted into blob and passed it into video controller. Although problem I am facing is it only plays audio somehow. Can anyone suggest a way to solve this?

**Comment by laxkarparas1** [comment] 2021-06-04 10:09
https://stackoverflow.com/questions/65821003/flutter-web-playing-uint8list-n-videoplayer/65834130

this is not working in my case 

final blob = html.Blob([decryptedBytes]);
     url = await html.Url.createObjectUrlFromBlob(blob);
     
     it throws this error
     
     [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: UnimplementedError
E/flutter (30797): #0      Url.createObjectUrlFromBlob (package:universal_html/src/html/api/history.dart:175:5)
E/flutter (30797): #1      _MyHomePageState.decryptFile (package:flutter_screenshot/main.dart:214:27)
E/flutter (30797): <asynchronous suspension>
E/flutter (30797): #2      _MyHomePageState.perfomEncryptionTasks (package:flutter_screenshot/main.dart:147:5)
E/flutter (30797): <asynchronous suspension>

**Comment by laxkarparas1** [comment] 2021-06-04 10:09
https://stackoverflow.com/questions/65821003/flutter-web-playing-uint8list-n-videoplayer/65834130

this is not working in my case 

final blob = html.Blob([decryptedBytes]);
     url = await html.Url.createObjectUrlFromBlob(blob);
     
     it throws this error
     
     [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: UnimplementedError
E/flutter (30797): #0      Url.createObjectUrlFromBlob (package:universal_html/src/html/api/history.dart:175:5)
E/flutter (30797): #1      _MyHomePageState.decryptFile (package:flutter_screenshot/main.dart:214:27)
E/flutter (30797): <asynchronous suspension>
E/flutter (30797): #2      _MyHomePageState.perfomEncryptionTasks (package:flutter_screenshot/main.dart:147:5)
E/flutter (30797): <asynchronous suspension>

**Comment by laxkarparas1** [comment] 2021-06-04 10:22
> How can i do this in flutter mobile ?

did you find answer for this ......?

**Comment by thanh-vo-opun-ai** [comment] 2022-01-26 00:55
@laxkarparas1 
Here is the solution
https://stackoverflow.com/questions/51485755/how-get-url-createobjecturlblob-to-work-in-safari

**Comment by RobertApikyan** [comment] 2022-03-01 15:43
Yes, but is there a solution for mobile ? Can we play Uint8List data using the video player ?

**Comment by stuartmorgan** [comment] 2023-05-21 17:14
Duplicate of https://github.com/flutter/flutter/issues/53017

**Closed by stuartmorgan** 2023-05-21 17:14 UTC
Labels: new feature, plugin, p: video_player, passed first triage, P5
