### ISSUE TITLE
Flutter fails to load ANY images from internet

### ISSUE THREAD

**Issue by tomkochi** [flutter/flutter#31548] opened 2019-04-24 11:13 UTC
As my own code failed to load images from internet using `Image.network('url')`, I tried this sample code from Flutter.io

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://picsum.photos/250?image=9',
        ),
      ),
    );
  }
}

```

It fails, too. irrespective of whatever image url I provide.

## Error log

Error log starts with
```
I/flutter ( 6840): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 6840): The following SocketException was thrown resolving an image codec:
I/flutter ( 6840): Failed host lookup: 'picsum.photos' (OS Error: No address associated with hostname, errno = 7)
I/flutter ( 6840):
I/flutter ( 6840): When the exception was thrown, this was the stack:
I/flutter ( 6840): #0      NetworkImage._loadAsync 
package:flutter/…/painting/image_provider.dart:490
I/flutter ( 6840): <asynchronous suspension>
I/flutter ( 6840): #1      NetworkImage.load 
package:flutter/…/painting/image_provider.dart:475
I/flutter ( 6840): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:285
I/flutter ( 6840): #3      ImageCache.putIfAbsent 
package:flutter/…/painting/image_cache.dart:157
I/flutter ( 6840): #4      ImageProvider.resolve.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:285
I/flutter ( 6840): #5      SynchronousFuture.then 
package:flutter/…/foundation/synchronous_future.dart:38
I/flutter ( 6840): #6      ImageProvider.resolve 
package:flutter/…/painting/image_provider.dart:283
I/flutter ( 6840): #7      _ImageState._resolveImage 
package:flutter/…/widgets/image.dart:631
I/flutter ( 6840): #8      _ImageState.didChangeDependencies 
package:flutter/…/widgets/image.dart:606
I/flutter ( 6840): #9      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:386
```
goes on and ends with

```
I/flutter ( 6840): #336    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter ( 6840): #337    ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3716
I/flutter ( 6840): #338    ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3711
I/flutter ( 6840): #339    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter ( 6840): #340    Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter ( 6840): #341    RenderObjectToWidgetElement._rebuild 
package:flutter/…/widgets/binding.dart:933
I/flutter ( 6840): #342    RenderObjectToWidgetElement.mount 
package:flutter/…/widgets/binding.dart:904
I/flutter ( 6840): #343    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
package:flutter/…/widgets/binding.dart:850
I/flutter ( 6840): #344    BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2253
I/flutter ( 6840): #345    RenderObjectToWidgetAdapter.attachToRenderTree 
package:flutter/…/widgets/binding.dart:849
I/flutter ( 6840): #346    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
package:flutter/…/widgets/binding.dart:736
I/flutter ( 6840): #347    runApp 
package:flutter/…/widgets/binding.dart:780
I/flutter ( 6840): #348    main
package:gotaste/main.dart:3
I/flutter ( 6840): #349    _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
I/flutter ( 6840): #354    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
I/flutter ( 6840): #355    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
I/flutter ( 6840): #356    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 6840): (elided 4 frames from package dart:async)
I/flutter ( 6840):
I/flutter ( 6840): Image provider: NetworkImage("https://picsum.photos/250?image=9", scale: 1.0)
I/flutter ( 6840): Image key: NetworkImage("https://picsum.photos/250?image=9", scale: 1.0)
```

I am stuck. Can't move on, please help.

**Comment by tomkochi** [comment] 2019-04-24 11:23
Its loads images successfully on iPhone. Its Android device showing error. I am testing with Nexus 5X APIQ.

**Comment by wyattbiker** [comment] 2019-04-24 15:11
Work for me on Android emulator. The message is Failed host lookup: 'picsum.photos' (OS Error: No address associated with hostname, errno = 7)
Make sure your device browser can access this page. could be something DNS related.

![Screen Shot 2019-04-24 at 11 06 11 AM](https://user-images.githubusercontent.com/930478/56670628-30612d00-6681-11e9-9493-aa19ff0b0819.png)

**Comment by jason-simmons** [comment] 2019-04-24 18:16
Also check that the Android app has the `INTERNET` permission enabled in its manifest.

The default Flutter app template enables `INTERNET` permission for debug/profile modes (to support the Dart observatory) but not release mode.

**Comment by tomkochi** [comment] 2019-04-26 09:25
I checked the AndroidManifest.xml it has a line:
<uses-permission android:name="android.permission.INTERNET"/>

**Comment by tomkochi** [comment] 2019-04-26 09:26
I checked AndroidManifext.xml, and it has a line:
`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by minh98** [comment] 2019-04-26 15:58
u can check another url images,
it seem a issue about host :))

**Comment by tomkochi** [comment] 2019-04-27 13:02
Same result for every image url I used. I think this is something with the phone settings, like the phone is not permitted to look up the internet. How can I make sure?

**Comment by wyattbiker** [comment] 2019-04-27 14:23
By the way there are two folder where, AndroidManifest.xml appears my machine is in this folder:   android/app/src/profile 
android/app/src/debug

Make sure you have the permissions in both

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flloadimage">
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```

Also Here somethings else to try see if phone has problem.
Login to adb shell while device is launched (or plugged in) and ping the website.

E.g. should look something like this
```
~$ adb shell
generic_x86:/ $ ping picsum.photos
PING picsum.photos (104.37.178.1) 56(84) bytes of data.
64 bytes from 104.37.178.1: icmp_seq=1 ttl=254 time=17.6 ms
64 bytes from 104.37.178.1: icmp_seq=2 ttl=254 time=22.4 ms
^C
--- picsum.photos ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5012ms
rtt min/avg/max/mdev = 13.638/19.442/24.621/3.508 ms
generic_x86:/  <press ctrl-d to exit to your prompt>
```

Other ideas
- Try on another wifi such as a cafe.
- Do  a flutter clean command to rebuild
- Install on another computer

**Comment by EdgarEscobedoHdz** [comment] 2019-07-30 01:00
Are you using an Android emulator? If so, do you have internet connection? 

I had the same problem, and the main problem was a configuration with the DNS of my computer, the android emulator was not able to connect to the internet, I had to use the Google's DNS on my computer '8.8.8.8 and 8.8.4.4' and then close the emulator, open up again and it solved the problem.

**Comment by marcuslow** [comment] 2019-08-22 18:07
DNS solved it for me. The bug is with the Android emulator then?

**Comment by QTTQ** [comment] 2019-09-27 07:27
I had the same problem.

**Comment by Fravahr** [comment] 2019-10-15 11:01
The problem is with the android image that you are using. with another version of android probably android 9.0 this will be OK.
I had same problem and just using android 9 instead of android 10 has solved my  problem.

**Comment by BondarenkoStas** [comment] 2019-10-16 15:14
@tomkochi was the issue solved?

**Comment by iapicca** [comment] 2019-11-08 09:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 09:52 UTC
Labels: a: images, waiting for customer response

**Comment by JubairSayeedLinas** [comment] 2019-11-12 08:44
i have a same issue. After permission the image is not loading in my Android Phone. There is working network connection and all is fine but the image is not showing in the app.

**Comment by Arjunraj-k** [comment] 2020-02-04 13:45
i have the same problem even with INTERNET permission. doesn't work in profile mode too. there is no error, it's just blank.

**Comment by vishalpawar048** [comment] 2020-02-04 16:26
I have same issue. Internet is working, All permissions are set still, image is not loading also not giving any error. Please help..

**Comment by iapicca** [comment] 2020-02-06 09:14
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by yaronlevi** [comment] 2020-04-17 20:36
I am also experiencing this...
