### ISSUE TITLE
Does flutter have a contextual action bar (CAB) equivalent, a way to sort a list of files by date modified or even a way to get frames from a video to be used as thumbnail?  

### ISSUE THREAD

**Issue by asapJ** [flutter/flutter#19344] opened 2018-07-13 13:51 UTC
have been geting use cases that requires either of those, but Haven't found how any of that can be implemented yet. 
Who else sees a need for those features?

**Comment by zoechi** [comment] 2018-07-13 15:38
Any screenshot or link to more details what the appearance and behavior?

**Comment by asapJ** [comment] 2018-07-13 16:39
![screenshot_2018-07-13-17-32-16](https://user-images.githubusercontent.com/33837248/42702961-ee5f566e-86c2-11e8-9403-0b780121d539.png)

For the CAB, see the attached screen shot of how it works
Another example is selecting multiple items from a grid
Check this link too..
http://www.technotalkative.com/contextual-action-bar-cab-android/

For the sorting files by date modified Its quite explanatory same with generating thumbnails from video frames

**Comment by asapJ** [comment] 2018-07-13 16:58
@zoechi

**Comment by zoechi** [comment] 2018-07-16 07:18
Sounds like a dup of #13205

**Comment by asapJ** [comment] 2018-07-18 15:55
If there be a package that solves these issues, it would sure be an added layer of sweetness to our dear flutter

**Comment by zoechi** [comment] 2018-12-18 13:34
Duplicate of #13205

**Closed by zoechi** 2018-12-18 13:34 UTC
Labels: will need additional triage, would be a good package
