### ISSUE TITLE
DropdownButton bad behaviour when tapped and keyboard is showing

### ISSUE THREAD

**Issue by rexhvelaj** [flutter/flutter#150378] opened 2024-06-17 19:09 UTC
### Steps to reproduce

There was an issue previously with no solution here (https://github.com/flutter/flutter/issues/22075) but none of the suggestions the thread worked. I haven't confirmed that the issue happens on android but it does happen everytime on iOS. Was previously on Flutter version 3.16.0 and upgraded to 3.22.0 to see if it was fixed in a new release and still happening. The steps to recreate are as follows on a physical iOS device:  

1. Have a text input and a dropdown button on the same page/form
2. Click on the text input to have the keyboard popup
3. Click on the dropdown button with the keyboard open

### Expected results

Expect the keyboard to close and the dropdown button still be open/selectable 

### Actual results

Keyboard hides and the dropdown button also closes/hides. The user needs to click the dropdown button again in order to get the dropdown to show again and be able to select an option.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:mercury/constants/AppConstants.dart';

void main() => runApp(const DropdownButtonApp());

class ExampleSelectInput extends StatelessWidget {
  final String? labelText;
  final dynamic value;
  final List<dynamic>? selectedItems;
  final Map<dynamic, String>? items;
  final void Function(dynamic)? onChanged;
  final void Function(dynamic)? onTap;
  final double height;
  final int errorMaxLines;
  final GlobalKey dropdownKey = GlobalKey();

  ExampleSelectInput({
    required this.labelText,
    required this.items,
    super.key,
    this.value,
    this.height = 70,
    this.selectedItems = const [],
    this.onChanged,
    this.onTap,
    this.errorMaxLines = 1,
  });

  void onTapped() {
    if (onTap != null) {
      onTap!(this);
    }
  }

  List<DropdownMenuItem<dynamic>> itemsAsDropdownMenuItemList(BuildContext context) {
    List<DropdownMenuItem<dynamic>> formattedItems = [];
    this.items?.entries.toList().forEach((item) {
      formattedItems.add(DropdownMenuItem<dynamic>(
        key: Key('single-${item.value}'),
        value: item.key,
        child: Text(
          item.value,
        ),
      ));
    });

    return formattedItems;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      key: key,
      height: height + (12 * errorMaxLines),
      padding: EdgeInsets.only(top: 4),
      child: DropdownButtonFormField(
        isExpanded: true,
        key: dropdownKey,
        autovalidateMode: AutovalidateMode.always,
        items: itemsAsDropdownMenuItemList(context),
        value: this.value,
        decoration: InputDecoration(
          labelText: labelText,
        ),
        onChanged: (dynamic val) {
          if (onChanged != null) {
            this.onChanged!(val);
          }
        },
        onTap: () {
          onTapped();
        },
      ),
    );
  }
}

class ExampleTextInput extends StatelessWidget {
  final String? labelText;
  final void Function(String?)? onChanged;
  final void Function()? onTap;
  final void Function(String?)? onSaved;
  final bool? enabled;
  final double height;
  final int errorMaxLines;

  ExampleTextInput({
    required this.labelText,
    super.key,
    this.height = 70,
    this.onChanged,
    this.onTap,
    this.onSaved,
    this.enabled,
    this.errorMaxLines = 1,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      height: this.height + (12 * this.errorMaxLines),
      padding: EdgeInsets.only(top: 4),
      child: TextFormField(
        enabled: this.enabled,
        // obscureText: this.isPassword && !this.isVisible,
        decoration: InputDecoration(
          labelText: this.labelText,
        ),
        onTap: this.onTap != null ? () => this.onTap!() : null,
        onTapOutside: (pointerDownEvent) {
          FocusManager.instance.primaryFocus?.unfocus();
        },
        onSaved: this.onSaved,
      ),
    );
  }
}

class DropdownButtonApp extends StatelessWidget {
  const DropdownButtonApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('DropdownButton Sample')),
        body: DropdownButtonExample(),
      ),
    );
  }
}

class DropdownButtonExample extends StatefulWidget {
  const DropdownButtonExample({super.key});

  @override
  State<DropdownButtonExample> createState() => _DropdownButtonExampleState();
}

class _DropdownButtonExampleState extends State<DropdownButtonExample> {
  Widget _descriptionInput() {
    return ExampleTextInput(
      labelText: "Description",
      onChanged: (value) {},
    );
  }

  Widget _protocolInput() {
    return ExampleSelectInput(
      labelText: "Protocol",
      items: PortTriggerProtocol.toMap(),
      onChanged: (value) {},
    );
  }

  Widget _startPortInput() {
    return ExampleTextInput(
      labelText: "External Start Port",
      errorMaxLines: MediaQuery.of(context).size.shortestSide >= 800 ? 1 : 2,
      onChanged: (value) {},
    );
  }

  Widget _endPortInput() {
    return ExampleTextInput(
      labelText: "External End Port",
      errorMaxLines: MediaQuery.of(context).size.shortestSide >= 800 ? 1 : 2,
      onChanged: (value) {},
    );
  }

  Widget _portraitLayout() {
    return Column(children: [
      _descriptionInput(),
      _protocolInput(),
      Row(children: [
        Expanded(child: _startPortInput()),
        SizedBox(width: 8),
        Expanded(child: _endPortInput()),
      ]),
    ]);
  }

  @override
  Widget build(BuildContext context) {
    return _portraitLayout();
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/29893122/c4742c43-9b5a-424e-a29a-e03c6a0717fd

</details>

### Logs

<details open><summary>Logs</summary>

```console
[logs.txt](https://github.com/user-attachments/files/15875805/logs.txt)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
brexhvelaj@MCBREXHVE-7Y6F4 ios % flutter doctor -v
[!] Flutter (Channel [user-branch], 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-CA)
    ! Flutter version 3.22.0 on channel [user-branch] at /Users/brexhvelaj/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 5dcb86f68f (6 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/brexhvelaj/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Brendon’s iPhone (mobile)       • 00008110-000258E13AF2801E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.61

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jeanpaulattard** [comment] 2024-06-17 20:17
If you are using material 3, consider using [DropdownMenu](https://api.flutter.dev/flutter/material/DropdownMenu-class.html) instead of [DropdownButton](https://api.flutter.dev/flutter/material/DropdownButton-class.html) class.

In which case, the keyboard will not close and the dropdown menu will open.

To fix the latter, you can use TapRegion with FocusManager to unfocus the keyboard.

**Comment by rexhvelaj** [comment] 2024-06-17 21:09
@jeanpaulattard I tried to use the DropdownMenu class but it has the same issue. I updated the example code to use a DropdownButtonFormField as thats what is being used in the app due to the ability to add validators, would prefer to have this work using the DropdownButtonFormField class. 

Can you give an example of what you mean using TapRegion with FocusManager? I have tried using TapRegion and unfocusing using the FocusManager but it didn't change anything either. 

From my testing I have not been able to get it working regardless of the focus and only see the issue happening when the keyboard closes so it does seem to be related to the way the keyboard interacts with the page.

**Comment by danagbemava-nc** [comment] 2024-06-18 09:34
Hi @rexhvelaj, I just tested your code sample on iOS with stable 3.22.2 and I can't seem to reproduce the issue? See the recording below. 

Is there something I'm missing?

https://github.com/flutter/flutter/assets/88313112/48accfef-ac43-4f27-b75f-fdcfd3dace4a

**Comment by jeanpaulattard** [comment] 2024-06-18 16:32
@danagbemava-nc can you share the code you've used to achieve that?

I haven't managed to achieve those results (running latest flutter, 3.22.2)

```children: <Widget>[
            TextFormField(),
            DropdownMenu<int>(
              enableSearch: false,
              label: Text('dropdown'),
              width: MediaQuery.of(context).size.width - 32,
              dropdownMenuEntries: [
                DropdownMenuEntry<int>(
                  value: 1,
                  label: 'one',
                ),
                DropdownMenuEntry<int>(
                  value: 2,
                  label: 'two',
                ),
                DropdownMenuEntry<int>(
                  value: 3,
                  label: 'three',
                ),
              ],
            )
          ],
```

With the above code, I've achieved the following on an iOS simulator

https://github.com/flutter/flutter/assets/7465421/7094d3b6-a745-4911-8c55-7c3785f527f1

@rexhvelaj Wrapping the DropdownMenu in a tap region like below on the flip side, does close the keyboard, because it unfocus the form field

```
children: <Widget>[
            TextFormField(),
            TapRegion(
              onTapInside: (event) {
                FocusManager.instance.primaryFocus?.unfocus();
              },
              child: DropdownMenu<int>(
                   ... // your menu 
              ),
            ),
          ],
```

https://github.com/flutter/flutter/assets/7465421/606e2d4c-f484-46c6-94c2-741b88f32eb8

**Comment by danagbemava-nc** [comment] 2024-06-19 06:19
Hi @jeanpaulattard, I just run the code sample that was provided in https://github.com/flutter/flutter/issues/150378#issue-2358053745. I didn't make any changes aside adding the material import. Can you try this on a physical device to see if it works as expected?

**Comment by rexhvelaj** [comment] 2024-06-19 16:48
@danagbemava-nc @jeanpaulattard I have updated the example code and have it showing the error consistently now if you could confirm. After doing more testing it seems as though the select input is redrawing when the keyboard closes due to this line `errorMaxLines: MediaQuery.of(context).size.shortestSide >= 800 ? 1 : 2`. This is the most code I can show as I am not able to share more detailed code as per my companies policy. Does this error make sense and its just something I am doing wrong that is causing it or is it still an issue regarding the way flutter redraws the input?

**Comment by jeanpaulattard** [comment] 2024-06-20 05:46
> Hi @jeanpaulattard, I just run the code sample that was provided in [#150378 (comment)](https://github.com/flutter/flutter/issues/150378#issue-2358053745). I didn't make any changes aside adding the material import. Can you try this on a physical device to see if it works as expected?

Apologies for the late reply @danagbemava-nc I don't have a physical iphone to test, however that behaviour is also happening on my Android device.

**Comment by danagbemava-nc** [comment] 2024-06-20 06:52
Hi @rexhvelaj, with the updated code sample, your issue appears to be the global key. It changes anytime the page rebuilds which leads to the `Dropdown` closing before you can interact with it. You can check this by adding this in your `ExampleSelectInput` build method `print('global key: ${dropdownKey}');`

You can then try removing the dropdownKey from the `DropdownButtonFormField` and compare the two behaviours. 

> Apologies for the late reply @danagbemava-nc I don't have a physical iphone to test, however that behaviour is also happening on my Android device.

@jeanpaulattard, what code sample were you using?

**Comment by jeanpaulattard** [comment] 2024-06-20 12:19
@danagbemava-nc I was testing the code sample mentioned https://github.com/flutter/flutter/issues/150378#issuecomment-2176520394

It's a basic scaffold with those items as children to the column

**Closed** 2024-07-11 07:08 UTC
Labels: waiting for customer response, in triage
