### ISSUE TITLE
Compile Flutter Engine xcode build settings

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#94657] opened 2021-12-04 12:14 UTC
When I compile flutter engine for iOS platform, how to set xcode build settings, 
such as Weak References in Manual Retain Release

**Comment by stuartmorgan** [comment] 2021-12-04 13:57
Duplicate of https://github.com/flutter/flutter/issues/94658

**Closed by stuartmorgan** 2021-12-04 13:57 UTC
