### ISSUE TITLE
Flutter linux pre135  Failed to create EGL surface: Bad Native Window

### ISSUE THREAD

**Issue by BobEvans** [flutter/flutter#60032] opened 2020-06-22 23:38 UTC
Upon upgrading to 1.20...pre132 and then pre135, I get the errors 

"not a native X11 window", and
Failed to create EGL surface: Bad Native Window

Flutter doctor says everything is fine.

Here is the trace.
```
flutter -v run -d linux
[  +85 ms] executing: [/home/parallels/Documents/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] eaf9ff738aa771e8a46385440c867193e8b2ec9e
[        ] executing: [/home/parallels/Documents/flutter/] git tag --contains
HEAD
[ +138 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/home/parallels/Documents/flutter/] git describe --match
*.*.*-*.*.pre --first-parent --long --tags
[   +8 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent
--long --tags
[        ] 1.20.0-0.0.pre-135-geaf9ff738a
[   +5 ms] executing: [/home/parallels/Documents/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/parallels/Documents/flutter/] git ls-remote
--get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/home/parallels/Documents/flutter/] git rev-parse
--abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +52 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +10 ms] executing: /home/parallels/Android/Sdk/platform-tools/adb devices -l
[  +54 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +94 ms] Found plugin url_launcher_fde at
/home/parallels/Documents/flutter/.pub-cache/git/flutter-desktop-embedding-b0794
faf2c000576515aee56ca6bb5bee64cece4/plugins/flutter_plugins/url_launcher_fde/
[   +5 ms] Found plugin flutter_local_notifications at
/home/parallels/Documents/flutter/.pub-cache/git/flutter_local_notifications-e63
dd131ef20199512949b1c5a7134fb3185daae/flutter_local_notifications/
[   +5 ms] Found plugin android_alarm_manager at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/android_ala
rm_manager-0.4.5+11/
[  +53 ms] Found plugin path_provider at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er-1.6.11/
[   +1 ms] Found plugin path_provider_linux at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er_linux-0.0.1+1/
[   +1 ms] Found plugin path_provider_macos at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er_macos-0.0.4+3/
[  +13 ms] Found plugin sqflite at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3
.1/
[  +11 ms] Found plugin url_launcher at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r-5.4.11/
[        ] Found plugin url_launcher_macos at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r_macos-0.0.1+7/
[   +1 ms] Found plugin url_launcher_web at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r_web-0.1.1+6/
[   +3 ms] Found plugin workmanager at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager
-0.2.2/
[   +8 ms] Found plugin taqo_email_plugin at
/home/parallels/Documents/git/taqo_survey/taqo_client/plugins/email/
[   +1 ms] Found plugin taqo_time_plugin at
/home/parallels/Documents/git/taqo_survey/taqo_client/plugins/time/
[  +39 ms] Found plugin url_launcher_fde at
/home/parallels/Documents/flutter/.pub-cache/git/flutter-desktop-embedding-b0794
faf2c000576515aee56ca6bb5bee64cece4/plugins/flutter_plugins/url_launcher_fde/
[   +1 ms] Found plugin flutter_local_notifications at
/home/parallels/Documents/flutter/.pub-cache/git/flutter_local_notifications-e63
dd131ef20199512949b1c5a7134fb3185daae/flutter_local_notifications/
[   +6 ms] Found plugin android_alarm_manager at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/android_ala
rm_manager-0.4.5+11/
[  +25 ms] Found plugin path_provider at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er-1.6.11/
[   +1 ms] Found plugin path_provider_linux at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er_linux-0.0.1+1/
[   +2 ms] Found plugin path_provider_macos at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provid
er_macos-0.0.4+3/
[   +7 ms] Found plugin sqflite at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3
.1/
[   +8 ms] Found plugin url_launcher at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r-5.4.11/
[   +1 ms] Found plugin url_launcher_macos at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r_macos-0.0.1+7/
[   +1 ms] Found plugin url_launcher_web at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launche
r_web-0.1.1+6/
[   +3 ms] Found plugin workmanager at
/home/parallels/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/workmanager
-0.2.2/
[   +4 ms] Found plugin taqo_email_plugin at
/home/parallels/Documents/git/taqo_survey/taqo_client/plugins/email/
[        ] Found plugin taqo_time_plugin at
/home/parallels/Documents/git/taqo_survey/taqo_client/plugins/time/
[  +59 ms] Generating
/home/parallels/Documents/git/taqo_survey/taqo_client/android/app/src/main/java/
io/flutter/plugins/GeneratedPluginRegistrant.java
[  +75 ms] Starting incremental build...
[   +1 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +2 ms] complete
[   +3 ms] Launching lib/main.dart on Linux desktop in debug mode...
[   +3 ms] /home/parallels/Documents/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/parallels/Documents/flutter/bin/cache/artifacts/engine/linux-x64/frontend_
server.dart.snapshot --sdk-root
/home/parallels/Documents/flutter/bin/cache/artifacts/engine/common/flutter_patc
hed_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.ZJSGUF/flutter_tool.CRFHZU/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field
-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/cache.dill.track.dill
[  +13 ms] Building Linux application...
[  +13 ms] <- compile package:taqo_client/main.dart
[   +1 ms] executing: [build/linux/debug/] cmake -G Ninja
-DCMAKE_BUILD_TYPE=Debug
/home/parallels/Documents/git/taqo_survey/taqo_client/linux
[  +68 ms] -- Configuring done
[  +16 ms] -- Generating done
[        ] -- Build files have been written to:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug
[  +32 ms] executing: ninja -C build/linux/debug install
[   +8 ms] ninja: Entering directory `build/linux/debug'
[+8005 ms] [1/6] Generating
/home/parallels/Documents/git/taqo_survey/taqo_client/linux/flutter/ephemeral/libflutter_linux_gtk.so,
fl_basic_message_channel.h, fl_binary_codec.h, fl_binary_messenger.h, fl_dart_project.h, fl_engine.h,
fl_json_message_codec.h, fl_json_method_codec.h, fl_message_codec.h, fl_method_call.h, fl_method_channel.h,
fl_method_codec.h, fl_method_response.h, fl_plugin_registrar.h, fl_plugin_registry.h,
fl_standard_message_codec.h, fl_standard_method_codec.h, fl_string_codec.h, fl_value.h, fl_view.h,
flutter_linux.h, _phony_
[        ] [ +103 ms] executing: [/home/parallels/Documents/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] eaf9ff738aa771e8a46385440c867193e8b2ec9e
[        ] [        ] executing: [/home/parallels/Documents/flutter/] git tag --contains HEAD
[        ] [ +170 ms] Exit code 0 from: git tag --contains HEAD
[        ] [   +1 ms] executing: [/home/parallels/Documents/flutter/] git describe --match *.*.*-*.*.pre
--first-parent --long --tags
[        ] [  +20 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [        ] 1.20.0-0.0.pre-135-geaf9ff738a
[        ] [   +7 ms] executing: [/home/parallels/Documents/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/parallels/Documents/flutter/] git ls-remote --get-url origin
[        ] [  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +66 ms] executing: [/home/parallels/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [   +6 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +8 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +125 ms] Initializing file store
[   +2 ms] [  +15 ms] Done initializing file store
[        ] [  +63 ms] Skipping target: gen_localizations
[   +9 ms] [+2467 ms] Skipping target: kernel_snapshot
[        ] [+1684 ms] Skipping target: unpack_linux
[        ] [        ] invalidated build due to missing files:
/home/parallels/Documents/git/taqo_survey/taqo_client/DOES_NOT_EXIST_RERUN_FOR_WILDCARD893431881
[        ] [ +406 ms] debug_bundle_linux_assets: Starting due to {InvalidatedReason.inputMissing}
[        ] [ +274 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force
rerun. for more information see #56466.
[        ] [  +17 ms] debug_bundle_linux_assets: Complete
[        ] [ +380 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +9 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 5,518ms.
[        ] [ +135 ms] ensureAnalyticsSent: 131ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +512 ms] [2/5] Building CXX object CMakeFiles/taqo.dir/flutter/generated_plugin_registrant.cc.o
[ +124 ms] [3/5] Building CXX object CMakeFiles/taqo.dir/my_application.cc.o
[ +168 ms] [4/5] Linking CXX executable taqo
[        ] [4/5] Install the project...
[  +20 ms] -- Install configuration: "Debug"
[   +7 ms] -- Installing: /home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/taqo
[        ] -- Set runtime path of
"/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/taqo" to "$ORIGIN/lib"
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/icudtl.dat
[   +7 ms] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +151 ms] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/lib/liburl_launcher_fde_plugin.
so
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/FontManifes
t.json
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/packages/cu
pertino_icons
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/packages/cu
pertino_icons/assets
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/packages/cu
pertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/AssetManife
st.json
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/sent
iment_neutral.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/paco
256.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/sent
iment_dissatisfied.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/sent
iment_very_satisfied.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/sent
iment_very_dissatisfied.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/assets/sent
iment_satisfied.png
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/fonts
[   +5 ms] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/fonts/Mater
ialIcons-Regular.ttf
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing:
/home/parallels/Documents/git/taqo_survey/taqo_client/build/linux/debug/bundle/data/flutter_assets/kernel_blob
.bin
[  +56 ms] Building Linux application... (completed in 9.2s)
[ +167 ms] (taqo:11351): Gdk-WARNING **: 16:34:48.692: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is
not a native X11 window
[  +70 ms] ** (taqo:11351): WARNING **: 16:34:48.764: Failed to start Flutter engine: Failed to create EGL
surface: Bad Native Window
```

**Comment by stuartmorgan** [comment] 2020-06-23 01:36
> Flutter doctor says everything is fine.

`flutter doctor` is only intended to ensure that you have everything you need to build successfully; what you are encountering is a runtime failure.

> `[ +167 ms] (taqo:11351): Gdk-WARNING **: 16:34:48.692: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is
not a native X11 window`

Are you using Wayland, by any chance?

What distro+version of Linux are you running?

**Comment by BobEvans** [comment] 2020-06-23 07:24
Yes, I am using Gnome with Wayland.  
I am running Debian 10 on a Parallels VM with Gnome 3.30.2.

If I run it with Gnome on X.org, it launches and works with just an error about libEGL being unable to auth to DRI2.

**Comment by BobEvans** [comment] 2020-06-23 08:36
Note: If I run the Flutter linux app in an environment with GDK_BACKEND=x11 then it works.

**Comment by stuartmorgan** [comment] 2020-06-23 12:42
This is a duplicate of https://github.com/flutter/flutter/issues/57932 then.

**Closed by stuartmorgan** 2020-06-23 12:42 UTC
Labels: P4, a: desktop, engine, platform-linux, severe: crash
