### ISSUE TITLE
ERROR PUB

### ISSUE THREAD

**Issue by Ralle001** [flutter/flutter#14267] opened 2018-01-25 13:52 UTC
D:\git\flutter>flutter doctor
Updating flutter tool...
The system can't find the route.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

**Comment by cbracken** [comment] 2018-01-30 17:15
Thanks for reporting! Can you try running `flutter doctor --verbose` and paste the log here?

**Comment by zoechi** [comment] 2018-03-20 07:18
dup of #15014  ?

**Comment by zoechi** [comment] 2019-01-16 11:06
Duplicate of #15014

**Closed by zoechi** 2019-01-16 11:06 UTC
Labels: tool

**Comment by emmanuelJet** [comment] 2019-05-14 20:07
https://pub.dartlang.org/ refuse to open. It has been saying "This site can’t be reached"
