### ISSUE TITLE
Submit a web form with enter key (maybe onEnterPressed: TextFormField)

### ISSUE THREAD

**Issue by mark-zs** [flutter/flutter#61110] opened 2020-07-08 17:20 UTC
In accordance with standard UI practice I would like to detect an enter key while TextFormField has focus and use it to submit the form.  Maybe a property `onEnterPressed:` like there is `onFieldSubmitted:`

**Comment by TahaTesser** [comment] 2020-07-09 07:35
duplicate ofhttps://github.com/flutter/flutter/issues/55583

**Closed by TahaTesser** 2020-07-09 07:35 UTC
