### ISSUE TITLE
Crash only in Android release version

### ISSUE THREAD

**Issue by andra1eu** [flutter/flutter#15989] opened 2018-03-27 18:41 UTC
I get this crash in the release version of the app and I can't find the cause since the stack trace apparently doesn't help this much
```
E/flutter ( 7686): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 7686): TFA Error: #lib5::WebApiClient::loginWithEmailAndPassword
E/flutter ( 7686): #0      WebApiClient.loginWithEmailAndPassword (package:redux/data/web_api_client.dart:0)
E/flutter ( 7686): #1      AppRepository.loginWith (package:redux/data/app_repository.dart:52)
E/flutter ( 7686): <asynchronous suspension>
E/flutter ( 7686): #2      LoginMiddleware.handle (package:redux/middleware/login.dart:27)
E/flutter ( 7686): <asynchronous suspension>
E/flutter ( 7686): #3      MiddlewareBuilder.add.<anonymous closure> (package:built_redux/src/middleware.dart:37)
E/flutter ( 7686): #4      MiddlewareBuilder.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:built_redux/src/middleware.dart:53)
E/flutter ( 7686): #5      ActionDispatcher.call (package:built_redux/src/action.dart:32)
E/flutter ( 7686): #6      new AuthViewModel.initialized.<anonymous closure>.<anonymous closure> (package:redux/containers/auth_connector.dart:29)
E/flutter ( 7686): #7      LoginButton.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:redux/presentation/login/login_button.dart:45)
E/flutter ( 7686): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478)
E/flutter ( 7686): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530)
E/flutter ( 7686): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
E/flutter ( 7686): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161)
E/flutter ( 7686): #12     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123)
E/flutter ( 7686): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
E/flutter ( 7686): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147)
E/flutter ( 7686): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121)
E/flutter ( 7686): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101)
E/flutter ( 7686): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64)
E/flutter ( 7686): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48)
E/flutter ( 7686): #19     _invoke1 (dart:ui/hooks.dart:134)
E/flutter ( 7686): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91)
```

**Comment by jason-simmons** [comment] 2018-03-28 18:29
The "TFA Error" is coming from Dart 2 type flow analysis

@a-siva

**Comment by a-siva** [comment] 2018-03-28 19:55
Could you post some instructions on how we can reproduce this crash, access to your app or a snippet of code that triggers the crash would be helpful.

**Comment by kevmoo** [comment] 2018-03-28 20:08
Could you run `flutter packages pub deps`

That will tell us the versions of `redux` you're using...

**Comment by alexmarkov** [comment] 2018-04-16 16:49
Most likely, this bug is a duplicate of https://github.com/flutter/flutter/issues/16182 and fixed in the latest Flutter/master.

@andra1eu, could you test your application on the latest flutter (master channel) and check if the crash is still there?

**Comment by andra1eu** [comment] 2018-04-17 04:03
I will. Thanks.

**Comment by alexmarkov** [comment] 2018-05-21 17:12
Closing this issue as duplicate to https://github.com/flutter/flutter/issues/16182 and fixed.
@andra1eu, please reopen this issue if there is still a problem.

**Closed by alexmarkov** 2018-05-21 17:12 UTC
Labels: dependency: dart, waiting for customer response
