### ISSUE TITLE
Engine failing to roll to Framework on dart fix test errors

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128527] opened 2023-06-08 19:35 UTC
Started following the Dart -> Engine roll here https://github.com/flutter/engine/pull/42657

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_slow/12784/overview

```
Failed when applying fixes to /b/s/w/ir/x/w/flutter/packages/flutter_test/test_fixes/flutter_test/binding/live_test_widgets_flutter_binding.dart
Expected:
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_test/flutter_test.dart';

void main() {
  final binding = LiveTestWidgetsFlutterBinding.ensureInitialized();
  binding.runTest(
    () async { },
    () { },
  );
}


Actual (original code was unchanged):
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_test/flutter_test.dart';

void main() {
  final binding = LiveTestWidgetsFlutterBinding.ensureInitialized();
  binding.runTest(
    () async { },
    () { },
    // Changes made in https://github.com/flutter/flutter/pull/89952
    timeout: Duration(minutes: 30),
  );
}
```

**Comment by zanderso** [comment] 2023-06-08 19:52
@eyebrowsoffire noticed the commit https://dart.googlesource.com/sdk.git/+/fb0b1393583544867703f124766d5dc300e4bffa, which by eyeball seems to be a likely culprit. cc @bwilkerson @scheglov

**Comment by zanderso** [comment] 2023-06-08 19:52
cc @DanTup

**Comment by DanTup** [comment] 2023-06-08 20:42
I'll try and repro locally, but I think this might be coincidentally fixed in the change I just pushed to https://dart-review.googlesource.com/c/sdk/+/308080.

In the bad commit above, I added an optimisation to skip some work if there are not any fixes. I did this by calling an existing function `hasFixes()`, but that's not checking DataDriven fixes (it checks `FixProcessor.nonLintMultiProducerMap` but we also have `BulkFixProcessor.nonLintMultiProducerMap`).

This means data driven fixes would work only if the diagnostic that triggers them happened to also have a different (non-data-driven) correction producer. I noticed this because I applied some additional optimisations and it broke some data-driven tests for the same reason.

**Comment by DanTup** [comment] 2023-06-08 20:49
I've confirmed the fix included in https://dart-review.googlesource.com/c/sdk/+/308080 will fix this:

### Current dart-lang/sdk master:

```
PS C:\Dev\Google\flutter\packages\flutter_test\test_fixes\flutter_test\binding>  & 'C:\Dev\Dart SDKs\Nightly\bin\dart' C:\Dev\Google\dart-sdk\sdk\pkg\dartdev\bin\dartdev.dart fix .\live_test_widgets_flutter_binding.dart --dry-run
Computing fixes in live_test_widgets_flutter_binding.dart (dry run)...
Nothing to fix!
```

### With https://dart-review.googlesource.com/c/sdk/+/308080

```
PS C:\Dev\Google\flutter\packages\flutter_test\test_fixes\flutter_test\binding>  & 'C:\Dev\Dart SDKs\Nightly\bin\dart' C:\Dev\Google\dart-sdk\sdk\pkg\dartdev\bin\dartdev.dart fix .\live_test_widgets_flutter_binding.dart --dry-run
Computing fixes in live_test_widgets_flutter_binding.dart (dry run)...

1 proposed fix in 1 file.

live_test_widgets_flutter_binding.dart
  deprecated_member_use_from_same_package • 1 fix

To fix an individual diagnostic, run one of:
  dart fix --apply --code=deprecated_member_use_from_same_package .\live_test_widgets_flutter_binding.dart

To fix all diagnostics, run:
  dart fix --apply .\live_test_widgets_flutter_binding.dart
PS C:\Dev\Google\flutter\packages\flutter_test\test_fixes\flutter_test\binding> 
```

**Comment by DanTup** [comment] 2023-06-08 22:05
The fix has landed in https://github.com/dart-lang/sdk/commit/f1e3bfcef54a5880b1e489855bf601dfe8bee9a3

**Comment by zanderso** [comment] 2023-06-09 14:23
We can try to roll in the fix in https://github.com/dart-lang/sdk/commit/f1e3bfcef54a5880b1e489855bf601dfe8bee9a3 after the Dart SDK is rolled incrementally following the fix to the tool test discussed in https://github.com/flutter/flutter/issues/128546.

**Comment by DanTup** [comment] 2023-06-10 09:05
I think this fix landed in flutter/engine in https://github.com/flutter/engine/pull/42716 and is being rolled here in https://github.com/flutter/flutter/pull/128627 (that PR is all green except for the current build status, so I think that confirms the fix solved the issue). 

(So I think this can be closed once https://github.com/flutter/flutter/pull/128627 is merged).

**Comment by eyebrowsoffire** [comment] 2023-06-10 18:15
It's actually this engine -> framework roll that contains the fix: https://github.com/flutter/flutter/pull/128643

If that lands succesfully, we can close this issue.

**Comment by DanTup** [comment] 2023-06-10 18:33
Oops, yeah - not sure what I looked at there, it clearly wasn't in the one I linked.

Thanks!

**Comment by eyebrowsoffire** [comment] 2023-06-10 22:18
Looks like the roll was a success! I think we can close this as fixed.

**Closed by eyebrowsoffire** 2023-06-10 22:18 UTC
Labels: framework, dependency: dart, P0
