### ISSUE TITLE
[Web] When maxLines is null in a textfield, last line of textfield shows multi-byte chars cut-off.

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#70181] opened 2020-11-10 14:33 UTC
## Steps to Reproduce
1. Enter multiple lines of multi-byte characters in the textField

**Expected results:**
All text will be shown

**Actual results:** 
The bottom of the text is hidden.

![ストーリー プロッター - Google Chrome 2020_11_10 23_26_06](https://user-images.githubusercontent.com/7422251/98687429-0f6c4400-23ad-11eb-8f33-606d62dfe5e8.png)

<details>
`flutter doctor -v`
```
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1171], locale ja-JP)
    • Flutter version 1.23.0-18.1.pre at C:\src\flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1) 
    • Android SDK at C:\Users\hatadev\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\hatadev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.63
```
</details>

```

**Comment by darshankawar** [comment] 2020-11-11 06:37
@hatano0x06 Tried a series of emojis in a simple textfield and it shows me below:

<img width="1071" alt="Screenshot 2020-11-11 at 12 04 21 PM" src="https://user-images.githubusercontent.com/67046386/98777156-3e6ad000-2416-11eb-8198-3dce5838c745.png">

If we use `maxLines` property and set to 4 and use same emojis again, it shows all of them properly, as below:

<img width="1054" alt="Screenshot 2020-11-11 at 12 05 00 PM" src="https://user-images.githubusercontent.com/67046386/98777197-53476380-2416-11eb-9aa0-10fdc5f40e67.png">

Which one from above correctly interpretes your issue ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.193

• No issues found!


```

</details>

**Comment by hatano0x06** [comment] 2020-11-11 12:53
@darshankawar 
I don't put any restrictions on the input, so I set it to infinite ( maxLines: null )
the problem happens when is maxLines is null

**Comment by darshankawar** [comment] 2020-11-11 13:48
<img width="1206" alt="Screenshot 2020-11-11 at 7 16 15 PM" src="https://user-images.githubusercontent.com/67046386/98819049-6546f780-2452-11eb-8eac-5f44920d59df.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.149, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-8.0.pre.149 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8e7748e74c (2 days ago), 2020-11-08 20:32:04 -0800
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.193

• No issues found!


```

</details>

**Comment by mdebbar** [comment] 2020-11-19 22:33
Duplicate of https://github.com/flutter/flutter/issues/64792

**Closed** 2020-11-19 22:33 UTC
Labels: a: text input, a: typography, assigned for triage, found in release: 1.24, has reproducible steps, passed first triage, platform-web
