### ISSUE TITLE
[Android] HardwareKeyboard audioVolumeUp/Down It doesn't work.

### ISSUE THREAD

**Issue by khjde1207** [flutter/flutter#95121] opened 2021-12-12 17:59 UTC
![ezgif-6-a1022d18b458](https://user-images.githubusercontent.com/18232924/145723859-c88f69eb-5f71-49d7-9c12-6e2d75a41da6.gif)

1. flutter create testkeyboard
2. cd testkeyboard 
3. edit main.dart 

```dart
//---  add to 65 line ----
bool volumeControll(KeyEvent event) {
    if (event is KeyDownEvent) {
      if (event.logicalKey == LogicalKeyboardKey.audioVolumeUp) {
        setState(() {
          _counter++;
        });
      }
      if (event.logicalKey == LogicalKeyboardKey.audioVolumeDown) {
        setState(() {
          _counter--;
        });
      }
    }
    return true;
  }

  bool rawControll(RawKeyEvent event) {
    print("rawControll]]]]]");
    return false;
  }

  @override
  void initState() {
    // TODO: implement initState
    HardwareKeyboard.instance.addHandler(volumeControll);
    RawKeyboard.instance.addListener(rawControll);
    super.initState();
  }

  @override
  void dispose() {
    HardwareKeyboard.instance.removeHandler(volumeControll);
    RawKeyboard.instance.removeListener(rawControll);
    super.dispose();
  }
```
4. press the volume button 
5. Nothing happens. 
6. Tap the TextField in the center of the screen 
7. press the volume button 
8. observe the counter increments

This only happens when you run the app for the first time.

---

dartPad : https://dartpad.dev/e61753674bb8ef6dfb600da1a21067a2

---
<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.0, on Manjaro Linux 5.10.79-1-MANJARO, locale ko_KR.UTF-8)
    • Flutter version 2.8.0 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4일 전), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/khjde1207/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /opt/android-studio-beta/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio-beta
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • Redmi Note 9S (mobile) • 96b8bd05 • android-arm64 • Android 12 (API 31)
```
</details>

**Comment by danagbemava-nc** [comment] 2021-12-13 09:58
Duplicate of #71144

Please follow up there for more information

**Closed by danagbemava-nc** 2021-12-13 09:58 UTC
Labels: in triage
