### ISSUE TITLE
[Web] Flutter Demo Page (and web app) renders incorrectly on iOS Instagram WebView 

### ISSUE THREAD

**Issue by Cuiboy** [flutter/flutter#88505] opened 2021-08-19 08:29 UTC
## Steps to Reproduce

1. Create any new flutter project. 
2. Deploy the template to the web.
3. Open this link on iOS Instagram from a user's profile after adding it as their website. 

**Expected results:**
The Flutter Demo App should show up normally. 

**Actual results:**
On first launch (after a fresh install of Instagram so all cache had been cleared), the Flutter Demo Page top and bottom had all been cut off (screenshot links attached below): 

[Error Screenshot 1](https://drive.google.com/file/d/1zWsRjTHZoipJb5BzTUe99SLdjE7RAF59/view?usp=sharing)

Additionally, it seems as if the website had been stuck on loading: 
[Error Screenshot 2](https://drive.google.com/file/d/1owxVzUmt6KUsXL6tN-1IAvfQUfoYZYoI/view?usp=sharing)

Additionally, the reason I came across this was because I deployed my personal website built with Flutter Web and the following shoes the expected result vs. actual result: 
[Expected Website UI](https://drive.google.com/file/d/10MfI7JhqrhP4Rgog91PuiMWU8rShwUAc/view?usp=sharing)
[Error Website UI on Instagram WebView](https://drive.google.com/file/d/1GYntFX-4emI8aFRhcC_PdBYhxfGGquwv/view?usp=sharing)

I don't know if this would be an Instagram issue or a Flutter issue, but all other websites seem to be running normally on instagram browser, which is why I am creating a bug report. 

For testing, the website links are:
[Flutter Demo Page](http://staking-nation.surge.sh)
[Personal Website](https://patrickcui.com)

**Comment by TahaTesser** [comment] 2021-08-19 12:32
Hi @Cuiboy 
This is a known issue, see https://github.com/flutter/flutter/issues/86776, results might not exactly but it is same cause, you can post your results in the original issue as well 
closing as a duplicate of https://github.com/flutter/flutter/issues/86776

**Closed by TahaTesser** 2021-08-19 12:32 UTC
Labels: in triage
