### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by wintersawcher** [flutter/flutter#77310] opened 2021-03-05 01:57 UTC
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#4      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:51)
#5      FlutterProject._readManifest (package:flutter_tools/src/project.dart:218:34)
#6      FlutterProjectFactory.fromDirectory.<anonymous closure> (package:flutter_tools/src/project.dart:48:55)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#8      FlutterProjectFactory.fromDirectory (package:flutter_tools/src/project.dart:47:21)
#9      FlutterProject.current (package:flutter_tools/src/project.dart:87:61)
#10     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1001:81)
#11     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:351:21)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _runZoned (dart:async/zone.dart:1630:10)
#19     runZoned (dart:async/zone.dart:1550:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\vudoa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\Reviewfinish\flutter_appchatfinish\pubspec.yaml'

**Comment by pedromassangocode** [comment] 2021-03-05 08:25
Duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by pedromassangocode** 2021-03-05 08:25 UTC
Labels: in triage
