### ISSUE TITLE
Failed assertion: line 5333 pos 16: 'child is! ParentDataElement<ParentData>': is not true.

### ISSUE THREAD

**Issue by meetpatel1243** [flutter/flutter#131656] opened 2023-08-01 09:13 UTC

**Comment by dam-ease** [comment] 2023-08-01 09:21
Hi @meetpatel1243  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-08-01 09:21 UTC
Labels: in triage
