### ISSUE TITLE
Flutter doctor instructions for SDK update incorrect

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#28230] opened 2019-02-20 23:10 UTC
While running `flutter upgrade` and `flutter doctor`, the doctor tells me to update `sdkmanager`. When updating sdkmanager, I see an exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>
```
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.2.2-pre.24, on Mac OS X 10.13.6 17G3025, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /Users/rischpater/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```
```
rischpater-macbookair:~/Downloads/bookmarker
$ ls
README.md	bookmarker.iml	lib		pubspec.yaml
android		ios		pubspec.lock
rischpater-macbookair:~/Downloads/bookmarker
$ /Users/rischpater/Library/Android/sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 5 more
rischpater-macbookair:~/Downloads/bookmarker
```

**Comment by zoechi** [comment] 2019-02-21 08:09
Might be rather a Java setup issue than a Flutter issue

- https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a
- https://github.com/flutter/flutter/issues/16025#issuecomment-377545368
- https://github.com/flutter/flutter/issues/16452#issuecomment-380580196
- https://github.com/NativeScript/nativescript-cli/issues/3139#issuecomment-358832687

**Comment by EArminjon** [comment] 2019-04-13 21:40
Same issue:
Windows 10 : flutter getting started installation / demo
Intelij idea 2019  - Java 12 - Android sdk 28

**Comment by georgreen** [comment] 2019-05-11 19:17
@EArminjon Your java version betrays you. 

This might be of help:
https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a

**Comment by EArminjon** [comment] 2019-05-11 19:42
Yes i fortgot to going back here, i took java 8

**Comment by rainedAllNight** [comment] 2019-05-17 03:43
Android Studio -> Preferences ->System Setting ; Add the requires Android SDK 28 and the Android BuildTools 28.0.3

**Comment by AnasSafi** [comment] 2019-07-20 01:35
1- Android SDK version 28

Android Studio -> SDK Manager -> SDK Platforms tab -> Select Android 9.0 Pie and press ok to download it

2- Android BuildTools version 28.0.3

Android Studio -> SDK Manager -> SDK Tools tab -> Select Show Package Details -> Under Android SDK Build-Tools section select 28.0.3 and press ok to download it

then restart cmd then test fluter doctor again

**Comment by theo1201** [comment] 2019-08-25 08:37
> 1- Android SDK version 28
> 
> Android Studio -> SDK Manager -> SDK Platforms tab -> Select Android 9.0 Pie and press ok to download it
> 
> 2- Android BuildTools version 28.0.3
> 
> Android Studio -> SDK Manager -> SDK Tools tab -> Select Show Package Details -> Under Android SDK Build-Tools section select 28.0.3 and press ok to download it
> 
> then restart cmd then test fluter doctor again

i'm failed ,why ?

**Comment by patelkrunal78** [comment] 2019-10-02 17:34
I had a similar problem this morning (trying to build for Android using Unity3D). I ended up uninstalling JDK9 and installing Java SE Development Kit 8u144. Hope this helps.

Find more at Here https://icetutor.com/question/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-annotation-xmlschema

**Comment by joshi1983** [comment] 2019-10-02 22:06
The problem is unrelated to flutter even though I encountered it while trying to get flutter to work.

The problem is that the package corresponding with javax/xml/bind/annotation/XmlSchema was removed from the latest versions of Java run times.  The fix is to run SDK Manager in Java 8 or 1.8(1.8 and 8 are meaningfully the same as Java versions).

In other words, be sure that running "java -version" outputs a number that is less than "1.9".  If it outputs 9, ...13, install JRE or JDK 8 and point your PATH environment variable at it.  Remember also to reopen your terminal windows so the environment variable changes take effect.

**Comment by timsneath** [comment] 2020-01-02 23:30
Closing this, since the workaround is included below and the solution is outside of Flutter.

**Closed by timsneath** 2020-01-02 23:30 UTC
Labels: tool, ▣ platform-android

**Comment by AbhishekTF2020** [comment] 2020-09-29 06:55
> 1- Android SDK version 28
> 
> Android Studio -> SDK Manager -> SDK Platforms tab -> Select Android 9.0 Pie and press ok to download it
> 
> 2- Android BuildTools version 28.0.3
> 
> Android Studio -> SDK Manager -> SDK Tools tab -> Select Show Package Details -> Under Android SDK Build-Tools section select 28.0.3 and press ok to download it
> 
> then restart cmd then test fluter doctor again

I have tried above too but still

flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

**Comment by sajjadG** [comment] 2020-10-17 15:32
Installing `Android SDK Command-line Tools` solved this problem for some people. [https://github.com/flutter/flutter/issues/57017#issuecomment-696559427](https://github.com/flutter/flutter/issues/57017#issuecomment-696559427)

**Comment by Juan-Camilorr** [comment] 2020-10-22 18:12
> La instalación `Android SDK Command-line Tools`resolvió este problema para algunas personas (incluido yo). [# 57017 (comentario)](https://github.com/flutter/flutter/issues/57017#issuecomment-696559427)

Muchas gracias, me ayudaste demasiado!.
Problema solucionado.

**Comment by pankaj4u4m** [comment] 2021-01-30 17:07
https://www.edoardovignati.it/solved-flutter-android-licenses-exception/

**Comment by roeniss** [comment] 2021-02-05 06:00
@sajjadG Thank you sir

**Comment by kalmecak** [comment] 2021-03-07 18:54
Running 
```
$ flutter doctor --android-licenses
```
Worked for me

**Comment by viswa-source** [comment] 2021-05-18 05:47
Just install java1.8 SDK It'll work

**Comment by shocknawe** [comment] 2021-05-23 12:27
had this error, and this fix worked for me:
(mac)
https://stackoverflow.com/a/64389804/8007293

**Comment by skyzhp** [comment] 2021-06-16 06:44
> had this error, and this fix worked for me:
> (mac)
> https://stackoverflow.com/a/64389804/8007293

this work for me

**Comment by flutterq** [comment] 2021-06-17 02:09
All Possible Working Solution Added Here [[Solved] Exception in thread “main” java.lang.NoClassDefFoundError in flutter](https://fluttercorner.com/exception-in-thread-main-java-lang-noclassdeffounderror-in-flutter/)

**Comment by felipepalma1** [comment] 2021-07-28 21:55
> Installing `Android SDK Command-line Tools` solved this problem for some people (me included). [#57017 (comment)](https://github.com/flutter/flutter/issues/57017#issuecomment-696559427)

This works. Thank you very much.
