### ISSUE TITLE
iOS build stops issuing "Multiple commands produce /path/to/derived/data/simulator/Runner.app/Runner

### ISSUE THREAD

**Issue by vijaykanta** [flutter/flutter#54067] opened 2020-04-06 06:22 UTC
I know this issue pre exists before and people have managed to fix it by two methods. However both those two methods don't help me, and I think mine is a peculiar issue, please help, I am printing the logs below.

Also, the flutter run --verbose command was not entirely printed in console and looks too big to include here, so I cut short to the last red output only.

## Steps to Reproduce

1. Run `flutter run`.
2. Update the files as follows: pubspec.yaml include firebase_auth_ui, cloud_firestore, google_sign_in, firebase_storage, image_picker 
3. Look at the console output 

**Expected results:** 
Executed the application on iPhone simulator and console output saying 'Installing and launching on iPhone simulator'

**Actual results:** 
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                             20.9s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           26.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    error: Multiple commands produce '/Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/build/ios/Debug-iphonesimulator/Runner.app/Runner':
    1) Target 'Runner' has copy command from '/Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/ios/Runner/Runner' to
    '/Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/build/ios/Debug-iphonesimulator/Runner.app/Runner'
    2) Target 'Runner' has link command with output '/Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/build/ios/Debug-iphonesimulator/Runner.app/Runner'

    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator
    platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS
    Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: duplicate output file '/Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/build/ios/Debug-iphonesimulator/Runner.app/Runner' on task: Ld
    /Users/vijaykumarkanta/AndroidStudioProjects/firebase_firestore_app/build/ios/Debug-iphonesimulator/Runner.app/Runner normal x86_64 (in target 'Runner' from project
    'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

<details>
  <summary>Logs</summary>

```
          
[  +22 ms] Could not build the application for the simulator.
[   +5 ms] Error launching application on iPhone 11 Pro Max.
[  +13 ms] "flutter run" took 53,314ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:715:18)
#3      _rootRunUnary (dart:async/zone.dart:1155:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:295:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1155:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1147:13)
#20     _CustomZone.run (dart:async/zone.dart:1040:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:942:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:982:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
Analyzing firebase_firestore_app...                                     

   info • Unused import: 'package:firebasefirestoreapp/childtask.dart' • lib/booklist.dart:7:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: BookList._currentUser •
          lib/booklist.dart:22:7 • must_be_immutable
   info • The value of the field '_varName' isn't used • lib/myfile.dart:27:23 • unused_field
   info • The value of the field '_varName' isn't used • lib/myfile.dart:49:8 • unused_field
   info • This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method • lib/myFile:57:8 • must_call_super
   info • The declaration '_varName' isn't referenced • lib/myfile.dart:130:16 • unused_element
   info • The value of the local variable 'taskId' isn't used • lib/myfile.dart:396:17 • unused_local_variable
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:406:34 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:430:35 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:442:31 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:481:30 • await_only_futures
   info • The declaration '_getBooks' isn't referenced • lib/myfile.dart:605:11 • unused_element
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/myfile.dart:11:8 • unused_import
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/myfile.dart:12:8 • unused_import
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:36:8 • unused_field
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:40:8 • unused_field
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:42:28 • unused_field
   info • The value of the local variable 'myVar' isn't used • lib/myfile.dart:174:11 • unused_local_variable
   info • The declaration '_myVar' isn't referenced • lib/myfile.dart:209:8 • unused_element
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/myfile.dart:7:8 • unused_import
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/myfile.dart:9:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyClass._currentUser •
          lib/childtasklist.dart:22:7 • must_be_immutable
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:27:23 • unused_field
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:44:8 • unused_field
   info • The value of the field '_myVar' isn't used • lib/myfile.dart:48:8 • unused_field
   info • This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method • lib/myfile.dart:54:8 • must_call_super
   info • The declaration '_myVar' isn't referenced • lib/myfile.dart:127:16 • unused_element
   info • The declaration '_myFnc' isn't referenced • lib/myfile.dart:224:3 • unused_element
   info • The declaration '_myVar' isn't referenced • lib/myfile.dart:298:3 • unused_element
   info • The value of the local variable 'myVar' isn't used • lib/myfile.dart:311:11 • unused_local_variable
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:319:28 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:342:29 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:354:25 • await_only_futures
   info • 'await' applied to 'DocumentReference', which is not a 'Future' • lib/myfile.dart:393:24 • await_only_futures
   info • 'await' applied to 'CollectionReference', which is not a 'Future' • lib/myfile.dart:462:24 • await_only_futures
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/main.dart:2:8 • unused_import
   info • Unused import: 'package:firebasefirestoreapp/myfile.dart' • lib/main.dart:4:8 • unused_import
   info • Duplicate import • lib/main.dart:14:8 • duplicate_import
   info • The value of the field '_myVar' isn't used • lib/main.dart:98:7 • unused_field
   info • The declaration '_myVar' isn't referenced • lib/main.dart:177:8 • unused_element
   info • The declaration '_myFnc' isn't referenced • lib/main.dart:196:10 • unused_element
   info • The value of the local variable 'myVar' isn't used • lib/main.dart:359:12 • unused_local_variable
   info • The value of the local variable 'myVar' isn't used • lib/main.dart:361:10 • unused_local_variable
   info • The value of the local variable 'myVar' isn't used • lib/main.dart:476:12 • unused_local_variable
   info • The value of the local variable 'myVar' isn't used • lib/main.dart:478:10 • unused_local_variable
   info • 'await' applied to 'CollectionReference', which is not a 'Future' • lib/myfile.dart:48:25 • await_only_futures
   info • Unused import: 'dart:io' • lib/myfile.dart:11:8 • unused_import
   info • Unused import: 'dart:async' • lib/myfile.dart:12:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/myfile.dart:13:8 • unused_import
   info • Unused import: 'package:qr_flutter/qr_flutter.dart' • lib/myfile.dart:11:8 • unused_import
   info • Unused import: 'dart:io' • lib/myfile.dart:13:8 • unused_import
   info • The value of the local variable 'name' isn't used • lib/myfile.dart:110:12 • unused_local_variable
   info • The value of the local variable 'amount' isn't used • lib/myfile.dart:111:12 • unused_local_variable


```

```
[✓] Flutter (Channel master, v1.16.2-pre.28, on Mac OS X 10.15.4 19E266, locale en-IN)
    • Flutter version 1.16.2-pre.28 at /Users/vijaykumarkanta/development/flutter
    • Framework revision 9a9c32e02f (2 weeks ago), 2020-03-20 11:51:01 -0400
    • Engine revision 8dbb8ca70b
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 1bab476834)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vijaykumarkanta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/vijaykumarkanta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • EF92624B-9734-4D00-8200-828E5953904C • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 2 categories.

```

</details>

**Comment by iapicca** [comment] 2020-04-06 10:08
Hi @vijaykanta 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-06 10:08 UTC
