### ISSUE TITLE
[firebase_messaging] custom sound on notification does not work on api 26

### ISSUE THREAD

**Issue by orgio** [flutter/flutter#39016] opened 2019-08-22 00:20 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment] 2019-09-04 12:40
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.

Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.

**Comment by orgio** [comment] 2019-09-04 12:52
Thank you for looking my issue next time i will do more understandable

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 4, 2019 at 8:42 PM, Stanislav Bondarenko<notifications@github.com> wrote:   
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.

Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.

**Comment by orgio** [comment] 2019-09-06 01:40
on api 26 default notification sound ringing, on api 22 it is working fine

**Comment by orgio** [comment] 2019-09-06 01:45
![Capture](https://user-images.githubusercontent.com/27058809/64394921-04bc6d80-d08b-11e9-9ef2-5d312b9d89d0.PNG)

**Comment by BondarenkoStas** [comment] 2019-09-06 09:22
@orgio Please provide your ```flutter doctor -v``` output, it's needed to know exactly in which version you encounter the issue etc. Are there any errors in logs or it just doesn't play? Can you specify which device do you use to test it?

**Comment by orgio** [comment] 2019-09-09 00:22
![Capture](https://user-images.githubusercontent.com/27058809/64496754-02505280-d2db-11e9-9090-bca0ee7291ed.PNG)

**Comment by orgio** [comment] 2019-09-09 00:25
firebase_messaging: ^5.1.2
and building on lg g5 VS987(API 26) also AVD nexus 6p (API 26)

**Comment by orgio** [comment] 2019-09-09 00:26
![Capture](https://user-images.githubusercontent.com/27058809/64496816-7f7bc780-d2db-11e9-8fad-ffce3982c5db.PNG)

**Comment by orgio** [comment] 2019-09-09 00:27
thank you for response

**Comment by RaashVision** [comment] 2019-10-06 04:13
It's already been reported in another issue #26005.
It's been more then 9months still no workaround. I think it's related to Notification channel in Android after API>26.

**Comment by BondarenkoStas** [comment] 2019-10-06 13:54
Thank you @RaashVision ! I think it will make sense to close this one to avoid duplication, @orgio please follow #26005.

**Closed by BondarenkoStas** 2019-10-06 13:54 UTC
Labels: p: firebase_messaging, plugin, ▣ platform-android

**Comment by RaashVision** [comment] 2019-10-07 04:22
I have found temporary workaround. The issue is because of notification channel after API>=26. I check the official Android notification channel page https://developer.android.com/training/notify-user/channels
, they mention that,

"When you target Android 8.0 (API level 26), you must implement one or more notification channels. If your targetSdkVersion is set to 25 or lower, when your app runs on Android 8.0 (API level 26) or higher, it behaves the same as it would on devices running Android 7.1 (API level 25) or lower."

So just go to your android/build.gradle , change the targetSdkversion to 25. Then clean the solution then rebuild it. Your custom sound for your notification will works now. The problem with FCM Custom sound after API> 26 is still exist so let this issue open. I really need to make this custom sound works that's why I come out with this hacky solution. Might be not a good solution but it solved the problem. Hope it helpful for you too.

**Comment by kroikie** [comment] 2019-10-13 19:34
@orgio

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1045. Any further collaboration will be done there.
