### ISSUE TITLE
fire_Store problem

### ISSUE THREAD

**Issue by khalidsaleh** [flutter/flutter#52053] opened 2020-03-05 22:33 UTC
Running "flutter pub get" in fire_base_app...                      21.3s
Launching lib\main.dart on SM G532F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_auth'.
> Could not resolve all artifacts for configuration ':firebase_auth:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.3.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar'.
         > Premature end of Content-Length delimited message body (expected: 30629071; received: 6553552
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':firebase_auth' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not find method implementation() for arguments [project ':firebase_auth_web'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 42s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment] 2020-03-06 07:50
Hi @khalidsaleh 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-06 07:50 UTC
