### ISSUE TITLE
crash while running  : flutter run -d chrome,  And and not being able to use Firebase host

### ISSUE THREAD

**Issue by DanielMohammadii** [flutter/flutter#85912] opened 2021-07-05 15:57 UTC
Hi , when I Run flutter run -d chrome , I get the below messages. So I have been running flutter run web-server. but now  I wanted to deploy the app on firebase host and found out  I cant run flutter run -d chrome --release as well. 
**Actual results:** 
Oops; flutter has exited unexpectedly: "ProcessException: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

  Command: C:\Users\abc\AppData\Local\Google\Chrome\Application\chrome.exe
  --user-data-dir=C:\Users\abc\AppData\Local\Temp\flutter_tools.1c3112c3\flutter_tools_chrome_device.e0eea77b
  --remote-debugging-port=6753 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi
  --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:14965".
A crash report has been written to D:\Starup App\Laughbit\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+application+has+failed+to+start+because+its+side-by-side+configuration+is+incorrect.+Please+see+the+application+event+log+or+use+the+command-line+sxstrace.exe+tool+for+more+detail.%0D%0A%0A++Command%3A+C%3A%5CUsers%5Cabc%5CAppData%5CLocal%5CGoogle%5CChrome%5CApplication%5Cchrome.exe+--user-data-dir%3DC%3A%5CUsers%5Cabc%5CAppData%5CLocal%5CTemp%5Cflutter_tools.1c3112c3%5Cflutter_tools_chrome_device.e0eea77b+--remote-debugging-port%3D6753+--disable-background-timer-throttling+--disable-extensions+--disable-popup-blocking+--bwsi+--no-first-run+--no-default-browser-check+--disable-default-apps+--disable-translate+http%3A%2F%2Flocalhost%3A14965

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jc64R
<details>
  <summary>Logs</summary>

[  +79 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +115 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[ +125 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +6 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +52 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +148 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +103 ms] executing: C:\Users\abc\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +66 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +122 ms] Multiple devices found:
[  +32 ms] Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
[   +3 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.64
[  +53 ms] [1]: Chrome (chrome)
[   +2 ms] [2]: Edge (edge)
[   +4 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 

No issues found! (ran in 6.2s)

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\abc\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\abc\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\abc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!

</details>

**Comment by darshankawar** [comment] 2021-07-06 08:06
@DanielMohammadii 
This is same issue you raised as below:

https://github.com/flutter/flutter/issues/85542
https://github.com/flutter/flutter/issues/85911
https://github.com/flutter/flutter/issues/81125

Please check the responses in each of the above that has a link to check if it helps to resolve your issue or not.
Closing this as duplicate of https://github.com/flutter/flutter/issues/85542

**Closed by darshankawar** 2021-07-06 08:06 UTC
Labels: in triage
