### ISSUE TITLE
TextStyle's `decorationThickness` property not taking effect

### ISSUE THREAD

**Issue by reza00farjam** [flutter/flutter#159550] opened 2024-11-27 13:16 UTC
### Steps to reproduce

Run the sample code provided and you will notice that `Text` widgets with different `decorationThickness`s have the same thickness.

### Expected results

It is expected based on the `decorationThickness` property [documentation](https://api.flutter.dev/flutter/painting/TextStyle/decorationThickness.html) to have different thickness for different values.

### Actual results

Same thickness for `Text` widgets with different `decorationThickness`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      home: ExampleApp(),
    ),
  );
}

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              '0.1 Thickness',
              style: TextStyle(
                fontSize: 24,
                color: Colors.blue,
                decorationThickness: 0.1,
                decorationColor: Colors.blue,
                decoration: TextDecoration.underline,
                decorationStyle: TextDecorationStyle.solid,
              ),
            ),
            Text(
              '1 Thickness',
              style: TextStyle(
                fontSize: 24,
                color: Colors.blue,
                decorationThickness: 1,
                decorationColor: Colors.blue,
                decoration: TextDecoration.underline,
                decorationStyle: TextDecorationStyle.solid,
              ),
            ),
            Text(
              '2.85 Thickness',
              style: TextStyle(
                fontSize: 24,
                color: Colors.blue,
                decorationThickness: 2.85,
                decorationColor: Colors.blue,
                decoration: TextDecoration.underline,
                decorationStyle: TextDecorationStyle.solid,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/bb0caa0d-403e-477a-b17c-2e88d089c175)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22621.4317], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\reza\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\reza\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33801.468
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\reza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.101.20241031

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-11-28 07:07
@reza00farjam Thanks for the report. I verified this on latest master version running on android emulator and observed that the decorationThickness is rendered properly, as shown below:

<img width="317" alt="Screenshot 2024-11-28 at 12 34 45 PM" src="https://github.com/user-attachments/assets/00e1a7d0-55cb-4322-b372-84266a929e0b">

Below is another case with bigger thickness:

<img width="185" alt="Screenshot 2024-11-28 at 12 36 25 PM" src="https://github.com/user-attachments/assets/c5d32699-d9e7-4004-a60e-41a7728f7ff8">

Since this works as intended in master, I'll close this as resolved.

**Closed by darshankawar** 2024-11-28 07:07 UTC
Labels: in triage

**Comment by reza00farjam** [comment] 2024-11-28 08:19
Thank you, @darshankawar, for checking it out.  
Apologies for not clarifying earlier, but the issue is occurring specifically on the **web** build.

I also upgraded my SDK to the latest stable version, but the problem persists on the web build. Below is the updated `flutter doctor -v` output:

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22621.4317], locale en-US)
    • Flutter version 3.24.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\reza\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\reza\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33801.468
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\reza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.101.20241031

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

Let me know if you'd like further refinements!

**Comment by darshankawar** [comment] 2024-11-28 11:12
@reza00farjam 
Please run on latest master as it works in it for web as well:

<img width="278" alt="Screenshot 2024-11-28 at 4 41 06 PM" src="https://github.com/user-attachments/assets/1a115d62-2ed0-44c0-aec9-cc92c84021f9">

The fix will most probably roll out in next release of stable.
