### ISSUE TITLE
 java.lang.IllegalStateException: Reply already submitted in camera plugin in flutter 

### ISSUE THREAD

**Issue by Priyanshu078** [flutter/flutter#112465] opened 2022-09-27 12:15 UTC
![Screenshot 2022-09-27 174132](https://user-images.githubusercontent.com/66347715/192523256-dcb0382f-2a88-4084-9cf1-c005df8ab0f7.png)

This is the issue and I am not able to figure it out how to resolve it.

**Comment by darshankawar** [comment] 2022-09-27 12:27
Closing as duplicate of https://github.com/flutter/flutter/issues/88598

**Closed by darshankawar** 2022-09-27 12:27 UTC
Labels: in triage
