### ISSUE TITLE
'Unable to load asset: AssetManifest.json' during testing

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#81236] opened 2021-04-26 22:02 UTC
We have an app that is going through the process of modularing. We have a module called 'design_system' that contain all apps fonts, images, multi purpose widgets, etc... We also have a main module that is the glue for all the modules.

Well, since we started this process we started to find this erro while executing our tests:

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown while resolving an image:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#3af05(), devicePixelRatio: 3.0,
  locale: en_US, textDirection: TextDirection.ltr, platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: This test will fail, but why?
```

The projects works FINE on devices but fails ONLY during testing.  We tried every single solution on #56242 without success.
To help the flutter team debug the problem, I've created a small sample app on github that shows the problem ocurring:

https://github.com/shinayser/asset_not_loading/tree/master

Just clone the project on your machine and then:

1. `flutter pub` get inside both modules (main_app and design system)
2. cd main_app and then `flutter test`

Running the tests with `flutter test --no-test-assets` is a workaround for this sample app, but doesn't sovle all the problems in the real world, because some screens depends on the assets contained. We have a case where one of our screens depends on the loading of a Lottie asset. This screen's test always fail if we use the flag above.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [versÃ£o 10.0.19042.928], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (3 available)
```

EDIT: We found a terrible workaround that can lead to the cause of this issue: we had to replace all of our assets to the modules that make use of them. So, in resume: the problem is that if your assets are used in module A but they are located in module B, the tests will fail, but the app will run fine. For so, a bug in the framework?

**Comment by TahaTesser** [comment] 2021-04-27 08:28
Hi @shinayser 
Thanks for filing the issue, weird that the test fails, I can reproduce it on all Flutter channels


<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 0941968447 (12 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at C:\Users\Taha\Code\flutter_dev
    • Framework revision 0941968447 (12 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.101, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.101 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff2dde2c7f (3 hours ago), 2021-04-26 22:35:45 -0700
    • Engine revision afd9c397a5
    • Dart version 2.14.0 (build 2.14.0-43.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```
		
</details>

**Comment by irvine5k** [comment] 2021-04-27 13:18
I suffer from this bug since last year, one workaround that my team encountered was creating a class to load the assets, so we can stub the asset load.

```
class AnimationService {
  const AnimationService();

  Future<ui.Image> loadImage({
    BuildContext context,
    String path,
  }) async {
    final imageData = await DefaultAssetBundle.of(context).load(path);

    final codec = await ui.instantiateImageCodec(
      imageData.buffer.asUint8List(),
    );
    final frame = await codec.getNextFrame();
    final image = frame.image;

    return image;
  }
}
```

Use this class to load the image for Lottie.

In the tests:

```
when(
      _animationService.loadImage(
        context: anyNamed('context'),
        path: '{path_here}',
      ),
    ).thenAnswer(
      (_) => Future.value(
        _loadImage()
      ),
    );
  });

Future<ui.Image> _loadImage(
  WidgetTester tester,
  String path,
) async {
  final imageData = await rootBundle.load(path);

  final codec = await tester.runAsync(
    () async => await ui.instantiateImageCodec(
      imageData.buffer.asUint8List(),
    ),
  );

  final frameInfo = await tester.runAsync(codec.getNextFrame);

  return frameInfo.image;
}

```

**Comment by erickzanardo** [comment] 2021-04-27 15:05
I took a look on this, and it seems that the behavior of flutter test is correct according to the [docs about sharing assets through packages](https://github.com/flutter/flutter/issues/81236)

On your example, you are using an asset from a package, directly on your application. To do that it seems that it is needed to declare the assets from the package on your pubspec.

If you use an asset, inside your on package on a widget for example, then import it and use that widget inside the app, then no additional config is needed on the app's pubspec.

The docs also suggest that if the assets would be exposed from the package,  they should be put under the lib folder, I haven't tested that specifically, but that seems like a good way of adding the assets to be available for other projects.

I have [sent a PR](https://github.com/shinayser/asset_not_loading/pull/1) to your reproducible example trying to explain a little better this comment. On that PR I added changes where the tests pass now with the two approaches I mentioned here, both a shareable asset from the package, and a widget which uses the asset "internally" .

Either way, I am unsure how running the app works, from what I understood from the docs, it should break just like the tests did.

Hope this helped

**Comment by shinayser** [comment] 2021-04-27 15:20
I just foudn the root cause of the bug:

* The problem is caused when the `assets` tag is missing on the pubspec of the module using the assets.

I just added a dummy.jpg on the `main_app` module and now every test passes properly. You can check the workaround on the `workaround` branch of the project I posted on the top post, or you can go [here](https://github.com/shinayser/asset_not_loading/tree/workaround)

So, in resume: when there is no asset on the module, the AssetManifest.json creation is skipped?

**Comment by erickzanardo** [comment] 2021-04-27 16:27
Interesting! To be sure I have reread the docs and indeed if the asset is listed on the pubspec of a package, it should be available on the app asset loader.

So it seems that you are correct, apparently if there is no `assets` key, with some entries there, the entire `AssetsManifest.json` is not created.

@christopherfujino any thoughts about this? Seems to be a behavior on the Flutter tool.

**Comment by shinayser** [comment] 2021-04-27 18:14
Seem that there is another a very similar issue here #60012

**Comment by jonahwilliams** [comment] 2021-04-28 03:55
Fixed via https://github.com/flutter/flutter/pull/81341 , thank you @erickzanardo !

**Closed by jonahwilliams** 2021-04-28 03:55 UTC
Labels: a: assets, a: tests, found in release: 2.0, found in release: 2.2, found in release: 2.3, framework, has reproducible steps
