### ISSUE TITLE
Text Cropping in Flutter.

### ISSUE THREAD

**Issue by udaykumaruking** [flutter/flutter#68701] opened 2020-10-21 11:45 UTC
![image](https://user-images.githubusercontent.com/32547287/96714786-507dc380-13c0-11eb-82ce-d72268ea8b5e.png)

I am creating a portfolio website but I started to face this issue my text is cropping. At **HI, I'm Uday Kumar**.

`Text(
            'Hi I\'m Uday Kumar👋',
            style: GoogleFonts.montserrat(
              textStyle: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.w400,
              ),
            ),
          ),`

This above code is the snippet I developed for creating that text. The text is as a child in the column widget.

[Repository  Link](https://github.com/udaykumaruking/portfolio_landing_page)

**Comment by darshankawar** [comment] 2020-10-21 12:55
@udaykumaruking I was able to replicate the issue when it shows the text cut-off at the bottom. But if you try to run below command, then the text renders properly (ignore the font rendering)

`flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true`

<img width="493" alt="Screenshot 2020-10-21 at 6 22 18 PM" src="https://user-images.githubusercontent.com/67046386/96721892-609aa080-13ca-11eb-91e6-af94a4dea38e.png">

This seem to indicate that it's related to skia rendering. There's another similar issue open, [67327](https://github.com/flutter/flutter/issues/67327) which works with above command and doesn't if we only run `flutter run -d chrome`.

I am going ahead and closing this as duplicate, since the issue is with how skia is rendering the text. 
If you disagree, write in comments and I'll reopen. Meantime, you can continue to use above command to compile and run your web app.

**Closed by darshankawar** 2020-10-21 12:55 UTC

**Comment by udaykumaruking** [comment] 2020-10-21 13:07
`flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true`

If I run the above-mentioned command in the command prompt once is it suffice and will it work for all projects or should I need to run the command for each and every project.

**Comment by darshankawar** [comment] 2020-10-21 13:32
Not for all projects. And use it only if you are facing rendering issues. If your widgets are rendering properly, you may use the regular command.

**Comment by udaykumaruking** [comment] 2020-10-21 13:34
@darshankawar Thanks for the help.

**Comment by udaykumaruking** [comment] 2020-10-21 13:36
@darshankawar I do have one doubt,

I have a row it has two children text and icon I want the row to take size dynamically based on text widget width and icon width.
