### ISSUE TITLE
[web] onSubmitted of TextField invoked if another TextField is clicked

### ISSUE THREAD

**Issue by a-marenkov** [flutter/flutter#49785] opened 2020-01-30 11:48 UTC
In browsers `onSubmitted` of `TextField` invoked on `Enter` and if another `TextField` is clicked.

Expected: 
- on `Enter` clicked - `onSubmitted` invocation;
- on another `TextField` clicked - only focus change (without `onSubmitted` invocation).

## Steps to Reproduce
```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.all(24.0),
      child: Material(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(hintText: 'TextField #1'),
              onSubmitted: (text) {
                print('TextField #1 onSubmitted: $text');
              },
            ),
            TextField(
              decoration: InputDecoration(hintText: 'TextField #2'),
              onSubmitted: (text) {
                print('TextField #2 onSubmitted: $text');
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.13.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by yjbanov** [comment] 2020-01-30 23:58
@a-marenkov The current behavior was implemented this way on purpose. Can you explain why you'd like a different behavior? Is it preventing you from implementing something?

/cc @nturgut

**Comment by kunit1** [comment] 2020-01-31 01:12
I tested the supplied sample code and this is what I observed on master:
1. Click inside of text-field to focus
   a. text-field is now focused (good)
2. click outside of text-field on a blank space.
   a. text-field is now unfocused (good)
   b. onSubmitted fires automatically (?)

I don't know if this is a bug or is this the intended behavior with regards to the onSubmitted firing.

**Comment by a-marenkov** [comment] 2020-01-31 08:34
@yjbanov @kunit1 

`onSubmitted` firing automatically makes sense to me as well and i would not have filed the issue, but:

1. It has different behavior on mobile - `onSubmitted` is not firing automatically if you tap another `TextField`.
2. It has different behavior on web if opened with mobile (tested on android in chrome app) - `onSubmitted` is not firing automatically if you tap another `TextField`.
3. Docs aren't clear about when `onEditingComplete` and `onSubmitted` are called. It says `Called when the user submits editable content (e.g., user presses the "done" button on the keyboard)` - but what are the other ways to "*submit editable*"?

@yjbanov Here are couple of cases in which this behavior is bad:

1. I have 2 TextFields. One for email, the other for password. 

I want on enter pressed 
- in email move focus to password;
- in password perform request.

So i put this logic either `onEditingComplete` or `onSubmitted`

-> user enters email 
-> preses enter and enters password 
-> then decides to correct email (user mistyped email or wants to enter different email)
-> user clicks email TextField and here is the problem, it fires `onSubmitted` and thus the request

2. I have 3 TextFields. 

I want on enter pressed move focus to next TextField, so i put this logic either `onEditingComplete` or `onSubmitted`.

-> user enters text in first TextField 
-> preses enter and enters text in second TextField 
-> then decides to correct text in first TextField
-> user clicks on first TextField and here is the problem - for half a second the third TextField gets focused and then first TextField gets focused (it looks buggy for user)


Maybe, there's another way to implement cases above that i don't know. 
On mobile i don't face this problems with this implementation.

**Comment by a-marenkov** [comment] 2020-01-31 12:43
**Update** In the second case above to reproduce the bug it might take more than one click on another TextField. Try switching between TextFields back and forth (requires at least 3 TextFields).

**Comment by a-marenkov** [comment] 2020-02-03 11:12
@yjbanov Another case would be:

I have at least 2 TextFields in a ListView (somewhere at the end of it).

I want on enter pressed move focus to next TextField, so i put this logic either onEditingComplete or onSubmitted.

-> user scrolls downwards and enters text in first TextField
-> then decides to scoll upwards by dragging
-> drags the ListView, and here is the problem - ListView would scroll upwards by dragging and also would autoscroll downwards to second TextField (because it gets focused as user taps blanc space).
It looks buggy.

**Comment by ja2375** [comment] 2020-03-20 16:10
I think this should be considered severe because it affects user experience.

I have a web app (this only happens on web) that is basically a form. If i add the `onFieldSubmitted` property to any of the `TextFormFields` then, when the user types something into a field and moves to the next one, the `onFieldSubmitted` gets triggered. That submits the form making the user think (s)he did something wrong.

That shouldn't happen as it makes no sense.

**Comment by nturgut** [comment] 2020-03-23 23:51
Thanks for filing the issue. 

As you also observed the current design submits the field when focus changes. Here is a summary of what happens during the life cycle of text editing:
- When user clicks in a field a [connection](https://github.com/flutter/flutter/blob/3e63411256cc88afc48044aa5ea06c5c9c6a6846/packages/flutter/lib/src/services/text_input.dart#L770) is created between the engine and the framework. 
- Information about the text field (location, font, id) sent through this connection.
- The connection life cycle starts with focus.

We decided to [end](https://github.com/flutter/flutter/blob/5005824763e1e581f3afede54bb9c85a9c42f8c5/packages/flutter/lib/src/services/system_channels.dart#L169) the text input connection's life cycle from the engine side whenever field blurs. Any event triggering a blur in a type of browser will trigger the connection's close hence will trigger on submit. Here is a table summarizes what closes the connection. (Yes, is for connection close signal)

  | Desktop Browsers | Safari IOS | Chrome Android
-- | -- | -- | --
on tab/window change | NO | YES | YES
when another element clicked | YES | NO | NO
when the virtual keyboard is closed | - | YES | NO
when app sent to background | - | YES  | YES 

For example, when a user is using a non-flutter-web website and editing a field, moving between tabs won't change the focus/blur state of an input field, so we carried that behavior. However clicking an empty area other than the page will blur an input field, so we used it as a signal to close the connection.

As you would realize each text field acts individually. A submit action shows a field is done with editing. 

The main reason for decision was to keep a clear state of the framework-engine connection. 

For your application, for desktop browsers are these items are the requirements:
- Enter to trigger onSubmit
- Clicking on another area (which will make the text field lose focus) not to trigger onSubmit
- Clicking on another textfield not to trigger onSubmit
- Do you have any additional requirements for mobile web?

**Can you achieve this functionality** by using a [form](https://api.flutter.dev/flutter/widgets/Form-class.html#widgets.Form.1) which wraps all the text fields in the page and checking if the form should be submitted or not using [onChanged](https://api.flutter.dev/flutter/widgets/Form/onChanged.html) method? Please let me know if this will work for you so we can discuss further options.

**Comment by a-marenkov** [comment] 2020-03-26 12:29
@nturgut 

Hi!

Sorry for delay with response.

The requirements for desktop browsers you've listed should be enough.

The requirements for mobile web would be the same with addition that forms should be unfocused without invoking onSubmit when the virtual keyboard is closed and when app sent to background.

Speaking of using a form - i don't really understand how it can be used to solve the problem, since OnChanged is not invoked on Enter pressed. 
Maybe if you provide a snippet with an example, i'll see how this helps.

Thanks!

**Comment by ja2375** [comment] 2020-04-03 07:33
@nturgut That behaviour you described (onSubmit is only triggered on user hitting enter) is the correct one for me. Anything else i think does not make sense for a normal/correct user experience.

**Comment by mdebbar** [comment] 2020-04-09 21:03
The `onSubmitted` callback is working as intended. From the [docs](https://api.flutter.dev/flutter/material/TextField/onSubmitted.html):

> Called when the user indicates that they are done editing the text in the field.

That being said, I agree that the naming is confusing. And that's a framework-wide issue that's not specific to the web. Please file a separate issue that's not web-specific to ask for either renaming the method or introducing a new one that does what you want.

**Comment by a-marenkov** [comment] 2020-04-11 14:53
> The `onSubmitted` callback is working as intended. From the [docs](https://api.flutter.dev/flutter/material/TextField/onSubmitted.html):
> 
> > Called when the user indicates that they are done editing the text in the field.
> 
> That being said, I agree that the naming is confusing. And that's a framework-wide issue that's not specific to the web. Please file a separate issue that's not web-specific to ask for either renaming the method or introducing a new one that does what you want.

Hi @mdebbar 

That is very frustarting, but it is what it is.

I don't think that renaming onSubmit will do any good, it'd a breaking change. 
Clarifing what onSubmit means and how it behaives (on a different platforms) in the docs, should be done though (maybe it should be done as a part of this issue).

Well, i guess, i have to open another issue.

I don't feel comfortable closing this issue unless the new issue is filed and accepted.

**Comment by bambinoua** [comment] 2020-05-05 07:45
Hi, I think I met the problem with undesired submit using `flutter web`. My case is I have a TextField used for search. When I type something in TextField the `cross` icon is become visible in `suffixIcon` (to clear). I **do not do** search and just click the `cross` to clear entered input and.. ta-dam `onSubmitted` is called and search executed... but I **don't need** it! So how can I fix this?

P.S. Of course I can use `RawKeyboardListener` but I am not sure how this will work under mobile device?

**Comment by nturgut** [comment] 2020-06-03 21:08
Thanks again for filing the issue. This functionality took a lot of attention and other issues are also filed related to the behavior mentioned in the comment(https://github.com/flutter/flutter/issues/49785#issuecomment-602921296). Therefore we changed the behavior in [PR](https://github.com/flutter/engine/pull/18743)

The close connection logic will stay the same for mobile browsers. For desktop browsers, the text field won't finalize text editing when the user clicks other areas on the page (on blur). @kunit1 

However, the onSubmitted will get triggered if another TextFormField is clicked since there will be only one open text connection at a time.

**Comment by jlubeck** [comment] 2020-06-04 14:34
@nturgut can you explain what is the use case for having `onSubmitted` be called when you click on another TextFormField ? I'm having a hard time understand why it is not ONLY called when the Done button is tapped or when Enter is pressed. 

I know the doc says 

`Called when the user indicates that they are done editing the text in the field.`

But that sounds precisely like what `onEditingComplete` should be doing.

On the other hand, the doc for `onEditingComplete` says:

`Called when the user submits editable content (e.g., user presses the "done" button on the keyboard).`

So as you can imagine, that is SUPER confusing. Submitting gets called when done editing, and Editing gets called when user submits... 🤯

Can you please clarify what would be the proper way to handle an action ONLY when Done button on mobile or Enter key on Desktop are used?

Thank you so much

**Comment by a-marenkov** [comment] 2020-06-04 16:29
> Thanks again for filing the issue. This functionality took a lot of attention and other issues are also filed related to the behavior mentioned in the comment([#49785 (comment)](https://github.com/flutter/flutter/issues/49785#issuecomment-602921296)). Therefore we changed the behavior in [PR](https://github.com/flutter/engine/pull/18743)
> 
> The close connection logic will stay the same for mobile browsers. For desktop browsers, the text field won't finalize text editing when the user clicks other areas on the page (on blur). @kunit1
> 
> However, the onSubmitted will get triggered if another TextFormField is clicked since there will be only one open text connection at a time.

Thanks a lot! Really appreciate the work you've done!

**Comment by nturgut** [comment] 2020-06-04 20:19
@jlubeck I understand the confusion. You are right the documentation is not descriptive and leads to confusion. We should also have the behavior described per platform if there is a difference between them. 

I'll discuss this with other member worked on text editing this week and update this issue (and the documentations).

**Comment by kunit1** [comment] 2020-06-08 22:47
@nturgut It is fine that now the textfield will not submit its content when click on other parts of the page. But shouldn't the text-field lose focus just like any other standard web text-field? The change in this [PR](https://github.com/flutter/engine/pull/18743) caused a regression in my opinion as now the text field will not lose focus when clicking away.

**Comment by NicolasDionB** [comment] 2020-06-15 19:00
Maybe it's a noob question but: where can I find in which version of Flutter will this update be found? I know it's been merged but I have a hard time finding when it's available in Flutter :) Thanks!

**Comment by nturgut** [comment] 2020-06-26 01:48
Sorry for the late reply. I checked with developers who frequently worked on text editing.

The current API: 
(1) Both onEditingComplete and onSubmitted are called at the same time. 
(2) onSubmitted (which has the value) is indicates user the text editing is complete. 
(3) onEditingComplete is for overriding the default behavior of focus changes.

PR(https://github.com/flutter/engine/pull/18743) is added to put web in sync with the current API documentation.

As also suggested by @kunit1:  If TextFields do not lose focus when other areas are clicked (mouse click or touch) by the user so web scenarios will be hard to implement. We need either the existing onEditingComplete callback to act differently than the onSubmit callback, and notify these blur event. Or we need to add a new callback to support development. 

I am working on a document discussing these options.  I'll add a link here.

**Comment by NicolasDionB** [comment] 2020-06-28 14:22
That's good to hear. Though the onSubmited beeing called when we click outside the editing field is kinda strange. We should at least receive a value saying what caused the "submission". In my opinion, changing focus out of the field is not a mark of submission but I understand someone might see it differently. For me, hitting the "enter" or "send" button would be submission, nothing else. In any case, if we can receive the cause of the said submission, that would be fine so just adding an argument to the handler would work for me.

**Comment by NicolasDionB** [comment] 2020-07-10 12:33
@nturgut I see your PR was merged. Is it available now? If so, how can I know in which version I can find the fix? Thanks

**Comment by ironpotter** [comment] 2020-07-15 14:51
Found some workaround, that emulates onSubmit action and losing focus doesn't trigger onSubmit.

`TextFormField(
        controller: controller,
        autovalidate: true,
        maxLines: null,
        validator: (value) {
          if(value.contains('\n')){
            String strWithoutEnter = controller.text.substring(0,controller.text.length - 1);
            controller.text = strWithoutEnter;

            controller.selection = TextSelection.fromPosition(TextPosition(offset: controller.text.length));
            _makeSomeLogic();
          }
        },
        textInputAction: TextInputAction.search,
        decoration: InputDecoration(
          hintText: description,
          border: InputBorder.none,
          focusedBorder: InputBorder.none,
        ),
      ),`

**Comment by sayurikunugi** [comment] 2020-07-16 19:19
@ironpotter 
Thank you, your solution works for me!
Just 1 thing, if the user inputs enter in the middle of text, it's not working right, so, I changed
```
            String strWithoutEnter = controller.text.substring(0,controller.text.length - 1);
            controller.text = strWithoutEnter;
```
to
```
                            final strWithoutEnter = searchController.text
                                .replaceAll('\n', '');
```

**Comment by ironpotter** [comment] 2020-07-19 06:06
@sayurikunugi Thank you. You're right.

**Comment by pedromassangocode** [comment] 2020-09-21 12:40
Hi @a-marenkov 
I cannot reproduce this on latest `master` channel.

<details><summary>sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Padding(
          padding: EdgeInsets.all(50),
          child: Container(
            color: Colors.white,
            padding: const EdgeInsets.all(24.0),
            child: Material(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  TextField(
                    decoration: InputDecoration(hintText: 'TextField #1'),
                    onSubmitted: (text) {
                      print('TextField #1 onSubmitted: $text');
                    },
                  ),
                  TextField(
                    decoration: InputDecoration(hintText: 'TextField #2'),
                    onSubmitted: (text) {
                      print('TextField #2 onSubmitted: $text');
                    },
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.269 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

Closing this as probably fixed. Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-09-21 12:40 UTC
Labels: P4, a: text input, framework, platform-web
