### ISSUE TITLE
Flutter in Dartpad  runs much faster than flutter CLI run command

### ISSUE THREAD

**Issue by ansarizafar** [flutter/flutter#47925] opened 2019-12-28 18:22 UTC
I am working with flutter for web but flutter run command is painfully slow. It almost impossible to use an old machine or a cloud Ide to develop a flutter web application.  Why Flutter in Dartpad complies and run much faster than flutter CLI run command? Is it because flutter create command creates a project with support for all platforms?  

Can we make flutter run command faster for web projects like Dartpad If this proposal in accepted https://github.com/flutter/flutter/issues/47924

**Comment by jonahwilliams** [comment] 2019-12-28 19:02
This is a known issue with the current web toolchain performance. Removing support for other platforms from your project will have no effect on compile times.

You might try the new experimental compiler. It does not current support debugging so it is off by default, but the performance should be much better. To enable, run flutter config --enable-web-incremental-compiler

**Comment by ansarizafar** [comment] 2019-12-29 05:14
Thanks for the hint. Is Dartpad using new experimental compiler?

**Comment by jonahwilliams** [comment] 2019-12-29 05:50
No, but it is only compiling a single file, so it is much faster

**Comment by bernaferrari** [comment] 2020-01-01 21:37
I just tested the new experimental compiler and it is waaay faster. Still a bit buggy and slower than emulator or physical device, but way improved.

**Comment by jonahwilliams** [comment] 2020-01-10 02:51
For now, closing as a duplicate of https://github.com/flutter/flutter/issues/41951

**Closed by jonahwilliams** 2020-01-10 02:51 UTC
Labels: tool
