### ISSUE TITLE
Make sure platform views are isolated from the engine's GL context

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41620] opened 2019-09-30 16:44 UTC
On iOS we may be passing control to a platform view while the GPU and platform threads are merged and the engine's GL context is current.
If the platform view does not change threads before using GL (which seems to be the case on recent versions of Google Maps) the platform view and the engine may be polluting each others GL state.

I believe this is the root cause for https://github.com/flutter/flutter/issues/34509

**Comment by darren-f5s** [comment] 2019-10-01 06:41
Is there any chance we can have a faster turnaround for this than December? It is (Like other people complaining) quite a crucial feature of our application

**Comment by sergicastellsague** [comment] 2019-10-03 10:24
Is this related with these crashes?

![image](https://user-images.githubusercontent.com/5736310/66119331-bbebcc00-e5d8-11e9-8d90-935df5a9f5ec.png)

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000002c84298a0

**Comment by darren-f5s** [comment] 2019-10-04 13:00
For anyone that manages to stumble across this - my current 'fix' is to house the GoogleMap controller in a basic Widget, with the proper dispose calls for the controller. Then, whenever I make a context change (In my case it's changing the map layer, but it could be also navigating to other pages), I dispose of the Widget and reload it.

 It's a complete waste of resources, but I found that it stops the app from crashing (Which I suppose is better)

Hope this helps someone

**Comment by sergicastellsague** [comment] 2019-10-04 13:04
@darren-f5s  Do you have a consistent way to make the app crash? If so, we'll try your approach and compare before and after your approach

**Comment by darren-f5s** [comment] 2019-10-04 13:12
I don't have time to create an example repository - however, this is what I've done:

* SETUP *
- House the GoogleMap Widget inside another Widget (as stated above), I will call it "MapDisplay"
- Create a `Singleton` which initializes a `Stream Controller` (Code below)
- Create a `Settings` page which will allow the user to select a map layer type
- Have the `MapDisplay` page listen to the StreamController, which calls `updateState`, setting the map layer to the index specified

* PROCESS *
- On the `Settings` page, call `localStream.changeMapType(/*INDEX NUMBER*/)` - which should execute the Stream and make the map change the layer type
- Go back to the map screen
- REPEAT UNTIL CRASH (Usually 1-9 times, I found it crashes faster on newer iOS devices)


** Stream Singleton Code **
```
import 'dart:async';

final LocalStream localStream = new LocalStream._private();

class LocalStream {
  LocalStream._private();
  bool isInit = false;

  StreamController _mapTypeController;
  Stream<void> get mapTypeStream =>
      _mapTypeController.stream.asBroadcastStream();

  void changeMapType(int index) {
    _mapTypeController?.sink?.add(index);
  }

  void init() {
    if (isInit) {
      return;
    }
    isInit = true;
    _mapTypeController = StreamController<void>.broadcast();
  }

  void dispose() {
    isInit = false;
    try {
      _mapTypeController?.close();
    } catch (_) {}
  }
}
```

**Comment by darren-f5s** [comment] 2019-10-08 05:31
Any word on this?

**Comment by burkard** [comment] 2019-10-16 23:15
> 
> 
> For anyone that manages to stumble across this - my current 'fix' is to house the GoogleMap controller in a basic Widget, with the proper dispose calls for the controller. Then, whenever I make a context change (In my case it's changing the map layer, but it could be also navigating to other pages), I dispose of the Widget and reload it.
> 
> It's a complete waste of resources, but I found that it stops the app from crashing (Which I suppose is better)
> 
> Hope this helps someone

Solved for me (tested on Android only).
Thanks!!

**Comment by darren-f5s** [comment] 2019-10-17 08:27
@burkard I've tested on both Android and iOS in production environments (It's actually far worse on iOS side), so it should be fine.

**Comment by rdev-software** [comment] 2019-10-19 23:13
> For anyone that manages to stumble across this - my current 'fix' is to house the GoogleMap controller in a basic Widget, with the proper dispose calls for the controller. Then, whenever I make a context change (In my case it's changing the map layer, but it could be also navigating to other pages), I dispose of the Widget and reload it.
> 
> It's a complete waste of resources, but I found that it stops the app from crashing (Which I suppose is better)
> 
> Hope this helps someone

Can you show example ? GoogleMapsController does not have dispose method, and and simple placing Google Maps widget into Container (basic widget) does not work either. 

What about proper fix anyway ?

**Comment by darren-f5s** [comment] 2019-10-21 10:45
The GoogleMap's Widget will automatically dispose (it seems) if the parent widget is disposed. So all you need to do is dispose the widget that contains the GoogleMap widget (Should just be an empty widget).
```
                        (Dispose this)
Page -> EmptyMapsHolderWidget -> GoogleMaps
```

**Comment by cyanglaz** [comment] 2019-11-15 20:56
This is fixed with https://github.com/flutter/engine/pull/13812. I'm going to close the issue.
If the same issue has been found after applying https://github.com/flutter/engine/pull/13812, please feel free to leave comment on the issue with details.

**Comment by cyanglaz** [comment] 2019-11-19 00:05
The commit is reverted due to a regression: https://github.com/flutter/flutter/issues/45098
Reopen the issue

**Comment by mklim** [comment] 2019-11-19 00:09
The revert is pending in flutter/engine#13906.

**Comment by cyanglaz** [comment] 2019-12-04 00:51
Push the milestone to Feb 2020 because we need to land some tests to catch regression(https://github.com/flutter/flutter/pull/45411) before we can land the fix for this.

**Comment by shorben07** [comment] 2020-01-03 13:13
From my understanding, after https://github.com/flutter/engine/pull/9491 changes,  each notification `UIApplicationDidReceiveMemoryWarningNotification` on iOS can cause a crash. Because `context->freeGpuResources();` will clear resources for other GL consumers(assuming they don't have their own GL contexts and/or threads)

**Comment by sanekyy** [comment] 2020-02-05 17:39
Hi there. We fixed crash in our project. I described our workaround [here](https://github.com/flutter/flutter/issues/49093#issuecomment-582365851).

**Comment by cyanglaz** [comment] 2020-02-21 22:22
I apologize for the delay. Pushing the milestone to June.

**Comment by oligazar** [comment] 2020-03-03 12:16
> For anyone that manages to stumble across this - my current 'fix' is to house the GoogleMap controller in a basic Widget, with the proper dispose calls for the controller. Then, whenever I make a context change (In my case it's changing the map layer, but it could be also navigating to other pages), I dispose of the Widget and reload it.
> 
> It's a complete waste of resources, but I found that it stops the app from crashing (Which I suppose is better)
> 
> Hope this helps someone

@darren-f5s Would you please provide a code snippet illustrating your workaround, because your explanation doesn't quite make sense to me. You didn't say if `MapDisplay` widget should be a stateful or stateless one, and `GoogleMapController` doesn't have anything like `dispose` or `close` methods, so I didn't get what `the proper dispose calls for the controller` means.

**Comment by cyanglaz** [comment] 2020-06-11 04:17
This is fixed by https://github.com/flutter/engine/pull/18601
I'm closing the issue.

**Closed by cyanglaz** 2020-06-11 04:17 UTC
Labels: P3, a: platform-views, platform-ios, plugin

**Comment by vanlooverenkoen** [comment] 2021-02-12 12:51
@ghost is it possible to create a small example project. Because I can't get your solution to work.
