### ISSUE TITLE
flutter webview_flutter Remove scrollbar

### ISSUE THREAD

**Issue by freedemocracy** [flutter/flutter#133738] opened 2023-08-31 06:40 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

android in the webview's default scrollbar is really ugly ah, so you can use the following code to remove the

webView.setHorizontalScrollBarEnabled(false);//Horizontal not shown
webView.setVerticalScrollBarEnabled(false); //Vertical not shown 

flutter webview_flutter No android-like setting options.

There is also no way to set the focus of the webview and whether the keyboard is displayed or not.

flutter is fond of providing half-baked products, flutter is almost 10 years since its release, what is your team doing, how I wish I was your boss!

### Proposal

I hope your developers will just copy the functionality of android webview and provide full functionality.

**Comment by danagbemava-nc** [comment] 2023-08-31 10:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/62464.

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-08-31 10:21 UTC
Labels: in triage

**Comment by freedemocracy** [comment] 2023-08-31 11:11
> Closing this as a duplicate of #62464.
> 
> Kindly subscribe to the original issue for updates.
> 
> Thank you

3 years and no solution to this problem and still have the nerve to close my issue

**Comment by Hixie** [comment] 2023-08-31 16:36
The issue isn't closed, it's still open and being tracked in https://github.com/flutter/flutter/issues/62464.

**Comment by Hixie** [comment] 2023-08-31 16:42
@freedemocracy "flutter is fond of providing half-baked products, flutter is almost 10 years since its release, what is your team doing, how I wish I was your boss" is the kind of comment that is a violation of our code of conduct. i have applied a 30-day ban. Please review our [code of conduct](https://github.com/flutter/flutter/blob/main/CODE_OF_CONDUCT.md) before commenting further, in particular, take note that comments must be kind, kind. courteous, and welcoming at all times.
