### ISSUE TITLE
Flutter does not create a web folder when you build for web

### ISSUE THREAD

**Issue by nerdy-plutonian-ng** [flutter/flutter#81482] opened 2021-04-29 16:50 UTC
## Steps to Reproduce

I can successfully build and launch the template flutter app in Chrome using Android Studio. However I want to add icons, manifest files etc to the folder but I cant find it. The android and ios folders are there but the web's is not. I am on flutter version 2.0.4 stable channel.

<details>

  <summary>Logs</summary>

```
[  +72 ms] executing: [C:\flutter_sdk\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] executing: [C:\flutter_sdk\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +39 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +38 ms] executing: [C:\flutter_sdk\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter_sdk\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [C:\flutter_sdk\flutter/] git rev-parse --abbrev-ref HEAD
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] executing: C:\Users\23355\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +41 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +81 ms] Skipping pub get: version match.
[ +122 ms] Generating D:\productivity\apps\flutter_projects\learn\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":17144}}]
[{"event":"app.start","params":{"appId":"4f433b5b-d1d4-44ce-9fce-9519f9cdf16b","deviceId":"chrome","directory":"D:\\productivity\\apps\\flutter_projects\\learn\\hello_world","supportsRestart":true,"launchMode":"run"}}]
[ +124 ms] This application is not configured to build on the web.
[        ] To add web support to a project, run `flutter create .`.
[   +1 ms] Launching lib\main.dart on Chrome in debug mode...
[  +99 ms] Updating assets
Waiting for connection from debug service on Chrome...
[{"event":"app.progress","params":{"appId":"4f433b5b-d1d4-44ce-9fce-9519f9cdf16b","id":"0","progressId":null,"message":"Waiting for connection from debug service on Chrome...","finished":false}}]
[ +365 ms] <- reset
[   +8 ms] C:\flutter_sdk\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter_sdk\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter_sdk\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\23355\AppData\Local\Temp\flutter_tools.87dd7476\flutter_tool.75263701\app.dill --libraries-spec file:///C:/flutter_sdk/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\productivity\apps\flutter_projects\learn\hello_world\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\23355\AppData\Local\Temp\flutter_tools.87dd7476\flutter_tools.ce924444 --filesystem-scheme org-dartlang-app --initialize-from-dill build\f58ed05f7a6fba8f3451773989665e4b.cache.dill.track.dill --platform file:///C:/flutter_sdk/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[{"event":"app.progress","params":{"appId":"4f433b5b-d1d4-44ce-9fce-9519f9cdf16b","id":"0","progressId":null,"finished":true}}]
[+17923 ms] Synced 29.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +269 ms] Using Opening in existing browser session.

[ +407 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:57278/devtools/browser/1c976cdd-a845-4e7a-a628-36bea1b47ab4
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:57228","launched":true}}]
[ +614 ms] DwdsInjector: Received request for entrypoint at http://localhost:57228/main_module.bootstrap.js
[  +13 ms] MetadataProvider: Loading debug metadata...
[  +29 ms] MetadataProvider: Loaded debug metadata
[  +15 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:57228/main_module.bootstrap.js
[+6003 ms] DevHandler: Debug service listening on ws://127.0.0.1:57327/i37G7QlpkYE=/ws

[   +7 ms] Debug service listening on ws://127.0.0.1:57327/i37G7QlpkYE=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[{"event":"app.started","params":{"appId":"4f433b5b-d1d4-44ce-9fce-9519f9cdf16b"}}]
Debug service listening on ws://127.0.0.1:57327/i37G7QlpkYE=/ws
[{"event":"app.debugPort","params":{"appId":"4f433b5b-d1d4-44ce-9fce-9519f9cdf16b","port":57327,"wsUri":"ws://127.0.0.1:57327/i37G7QlpkYE=/ws"}}]
[{"id":0,"result":{"value":"windows","type":"","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1","type":"","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"true","type":"","method":"ext.flutter.debugAllowBanner"}}]
[{"id":6,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":7,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.show"}}]
[{"id":8,"result":{"enabled":"true","type":"","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":9,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":12,"result":{"enabled":"false","type":"","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-04-30 07:45
Hi @nerdy-plutonian-ng 
Can you please elaborate more? It is not clear what the problem is.
Can you please provide the steps to reproduce along with the actual vs expected results?
Thank you

**Comment by nerdy-plutonian-ng** [comment] 2021-04-30 11:22
Steps to Reproduce

Create a new flutter project
Select Chrome from the flutter devices dropdown.
Run app(No changes made to the default app)
App launches as expected in Chrome, however no web folder is created in project

**Comment by pedromassangocode** [comment] 2021-04-30 11:27
> App launches as expected in Chrome, however no web folder is created in project

Please elaborate on where do you expect the web folder to be created. I just ran the `flutter create xyz` command and it does generates the web folder in `xyz/web`.

**Comment by nerdy-plutonian-ng** [comment] 2021-04-30 11:53
So the project is "flutter_app" and I expect "flutter_app/web".

I just realised creating the app via command, i get the web folder. Creating in the app in Android Studio does not create the web folder. I'm up to date as well. Perhaps this is more Android Studio than Flutter.

Thanks.

**Comment by pedromassangocode** [comment] 2021-04-30 13:37
Hi @nerdy-plutonian-ng 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-30 13:37 UTC
Labels: in triage
