### ISSUE TITLE
TextField can't be edited when obscureText is true on certain older Xiaomi devices

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#27353] opened 2019-01-31 12:35 UTC
TextField can not edit if I set `obscureText:true`
flutter version:.`v1.1.5-pre5`

**Comment by zoechi** [comment] 2019-01-31 13:01
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by hahafather007** [comment] 2019-01-31 14:39
My code just like this:
```
            TextField(
                obscureText: true,
                controller: controller,
                style: TextStyle(fontSize: 14, color: AppColor.colorText1),
                decoration: InputDecoration(
                  hintStyle:
                      TextStyle(fontSize: 14, color: AppColor.colorText3),
                  hintText: hideText,
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.only(left: 16),
                ),
                inputFormatters: [
                  LengthLimitingTextInputFormatter(16),
                ],
              )
```
If I set `obscureText:false `, it's ok. And if I roll back flutter to `v1.1.5-pre4`, it's ok too!
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.5-pre.6, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by hahafather007** [comment] 2019-01-31 14:42
> TextField can not edit if I set `obscureText:true`
> flutter version:.`v1.1.5-pre5`

I was wrong, the bug's version is `v1.1.5-pre6`

**Comment by zoechi** [comment] 2019-01-31 15:51
Can you please make the code a complete runnable (still minimal) example that can just be copied to `lib/main.dart` and executed (incl `void main() {...}`.

**Comment by hahafather007** [comment] 2019-02-01 05:20
I don't why the same code has different results.

**Comment by hahafather007** [comment] 2019-02-01 15:58
I found the conditions for the bug is that set app's `ThemeData` with `platform: TargetPlatform.iOS`, and set `TextField` with `obscureText: true`, run in Android, the bug will reappear.
@zoechi

**Comment by zoechi** [comment] 2019-02-08 16:10
Can you please make the reproduction self-contained and runnable.
Currently it requires additional imports and also from custom files like `import 'common_import.dart';`

**Comment by hahafather007** [comment] 2019-02-11 01:55
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        platform: TargetPlatform.iOS,
      ),
      home: MyHomePage(title: 'Flutter Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: TextField(
          obscureText: true,
          style: TextStyle(fontSize: 16, color: Colors.black),
        ),
      ),
    );
  }
}
```
@zoechi

**Comment by SubutaDan** [comment] 2019-02-11 04:42
I have encountered what I think is the same issue.  I would describe the problem as: TextField doesn't respond to long press when obscureText is set to true.  In that case paste can't be used.  Keyboard input seems to work as expected.

**Comment by zoechi** [comment] 2019-02-11 06:31
Thanks @hahafather007 I was able to reproduce with 
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by pepegich** [comment] 2019-02-20 06:16
reproduced on nexus 5 android 6, nexus 5 android 4.4.4,

not reproduced on pixel 2 android 9
reproduced if platform specified as TargetPlatform.iOS

**Comment by chunhtai** [comment] 2019-06-18 18:05
Is this still an issue except the selection is disabled by default? I can still type in password using above example.

**Comment by justinmc** [comment] 2019-08-02 17:37
This seems fixed to me (at least on master).  See @chunhtai's work on https://github.com/flutter/flutter/pull/34676.  I'm going to close this, but feel free to reopen if anyone sees the problem still.

**Comment by troyzhao** [comment] 2019-08-21 11:14
i have the  same issue on flutter v1.9.1. and on the MI 6 (小米6）android device。if set obscureText to true, then I can't enter any characters.

**Comment by justinmc** [comment] 2019-08-21 15:20
@GaryQian Do you have a MI 6 (or something similar) that I could try this on?

**Comment by justinmc** [comment] 2019-08-21 18:41
@troyzhao I tried this on a MI 9 and it worked fine on master.  Can you try this code on master on your device and let us know if it works?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: TextField(obscureText: true),
        ),
      ),
    );
  }
}
```

**Comment by RemmoYu** [comment] 2019-08-29 02:13
@justinmc  I tried this on a MI 5s Plus and MI mix3, it still doesn't work on master.

➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.6-pre.70, on Mac OS X 10.15 19A536g, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.37.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by justinmc** [comment] 2019-08-29 15:24
Ok I'll reopen.  It seems that this happens on certain older Xiaomi devices.  I'll update the title as well.

**Comment by mofada** [comment] 2019-09-02 07:00
I have the same problem. device info:
```
[ro.product.brand]: [Xiaomi]
[ro.product.model]: [MI 9]
[ro.miui.ui.version.code]: [8]
[ro.miui.ui.version.name]: [V10]
[ro.build.version.release]: [9]
[ro.build.version.sdk]: [28]
[ro.build.version.security_patch]: [2019-06-01]
```

![device-2019-09-02-144617](https://user-images.githubusercontent.com/22286246/64095276-f9b6c400-cd90-11e9-9346-28dbf2bbdcb2.gif)

##  source-code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('app'),
        ),
        body: Center(
          child: TextFormField(
            obscureText: true,
          ),
        ),
      ),
    );
  }
}
```


## flutter-doctor-v
```
[√] Flutter (Channel master, v1.9.6-pre.4, on Microsoft Windows [Version 10.0.18362.295], locale zh-CN)
    • Flutter version 1.9.6-pre.4 at D:\flutter
    • Framework revision 17813975a9 (8 days ago), 2019-08-24 17:06:36 -0400
    • Engine revision deca2c0da8
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\Community
    • Visual Studio Community 2019 version 16.1.29102.190

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\android-studio canary
    • Flutter plugin version 38.1.3
    • Dart plugin version 191.8348
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[√] Connected device (2 available)
    • MI 9    • 99312af • android-arm64 • Android 9 (API 28)
    • Windows • Windows • windows-x64   • Microsoft Windows [Version 10.0.18362.295]

• No issues found!
```

**Comment by RemmoYu** [comment] 2019-09-11 07:23
It should be fixed with stable channel v1.9.1+hotfix.2

**Comment by GaryQian** [comment] 2019-09-16 22:48
@RemmoYu Do you know if this is fixed for older xiaomi devices in particular? Was there a specific change that went in to fix it?

If this was actively fixed and verified, we can close this!

**Comment by RemmoYu** [comment] 2019-09-18 01:26
I have tried with  stable channel v1.9.1+hotfix.2, and i didn't have this issue for my  xiaomi devices now. but i don't know is there a specific change that went in to fix it.

**Comment by GaryQian** [comment] 2019-09-18 14:39
Ok, well I will close this for now. If anyone is still seeing this, comment and I will reopen!

**Closed by GaryQian** 2019-09-18 14:39 UTC
Labels: a: text input, framework

**Comment by marcianobandeira** [comment] 2020-04-19 21:55
same error in ios iPhone 11 physical and simulator

**Comment by sam-parks** [comment] 2020-04-19 22:16
I'm seeing this error on a physical iphone 6s

**Comment by albertshrpv** [comment] 2020-04-20 14:46
Same issue on iOS version 13.4.1 iPad and iPhone. Flutter 1.17.0 channel beta.

**Comment by asimolmez** [comment] 2020-04-20 22:17
Same issue on iOS

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-6.0.pre.91, on Mac OS X 10.15.4 19E266,
    locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (4 available)

**Comment by justinmc** [comment] 2020-04-21 01:06
I see this problem as well.  I've created a new issue since this one isn't necessarily related: https://github.com/flutter/flutter/issues/55259.

**Comment by wslaimin** [comment] 2020-04-21 07:05
> I'm seeing this error on a physical iphone 6s, master channel

I also see this errror on iphone 6s

**Comment by asimolmez** [comment] 2020-04-21 09:22
a temporary solution:
```
flutter channel beta

flutter upgrade
```

**Comment by justinmc** [comment] 2020-04-21 19:36
This is actually already fixed in the latest master, as of https://github.com/flutter/flutter/pull/55243.  I've closed the other issue.
