### ISSUE TITLE
Apps with null safety throw

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#68433] opened 2020-10-18 10:44 UTC
The fix for https://github.com/flutter/flutter/issues/59879 just landed via https://github.com/flutter/flutter/commit/a83755763499472053b5af8acc0f53b8727a4826. We now seem to have a issue with simple material apps (`example/hello_world` doesn't throw):

## Repro steps:

1. `flutter create foobar`
1. Edit `pubspec.yaml` to change `sdk: ">=2.7.0 <3.0.0"` to `sdk: ">=2.11.0-0.0 <3.0.0"`
1. Replace the contents of `lib/main.dart` with:
    ```dart
    import 'package:flutter/material.dart';

    void main() {
    runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
        home: Scaffold(
            body: Center(
            child: Text('Material Hello'),
            ),
        ),
        );
      }
    }
    ```
1. Run `flutter run --enable-experiment=non-nullable`

**Expected result**: no errors

**Actual result**: Three errors

```
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:61913/ktKfMJw2gr4=/
D/EGL_emulation(17133): eglMakeCurrent: 0xe81a7ba0: ver 3 0 (tinfo 0xe010f620)
D/eglCodecCommon(17133): setVertexArrayObject: set vao to 0 (0) 1 0
I/flutter (17133): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17133): The following _TypeError was thrown during a scheduler callback:
I/flutter (17133): type 'Null' is not a subtype of type 'EngineLayer' of 'function result'
I/flutter (17133):
I/flutter (17133): When the exception was thrown, this was the stack:
I/flutter (17133): #0      SceneBuilder._pushPhysicalShape (dart:ui/compositing.dart)
I/flutter (17133): #1      SceneBuilder.pushPhysicalShape (dart:ui/compositing.dart:577:5)
I/flutter (17133): #2      PhysicalModelLayer.addToScene (package:flutter/src/rendering/layer.dart:1988:29)
I/flutter (17133): #3      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17133): #4      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17133): #5      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1164:5)
I/flutter (17133): #6      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17133): #7      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17133): #8      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1164:5)
I/flutter (17133): #9      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17133): #10     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17133): #11     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1609:5)
I/flutter (17133): #12     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:765:5)
I/flutter (17133): #13     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:231:37)
I/flutter (17133): #14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:447:18)
I/flutter (17133): #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:907:13)
I/flutter (17133): #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:309:5)
I/flutter (17133): #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (17133): #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (17133): #19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (17133): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (17133): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17133): Another exception was thrown: type 'Null' is not a subtype of type 'EngineLayer' of 'function result'

```

## SDK version

```
mit-macbookpro4:nulltest mit$ flutter --version
Flutter 1.23.0-19.0.pre.95 • channel master • https://github.com/flutter/flutter.git
Framework • revision a837557634 (30 minutes ago) • 2020-10-18 06:12:02 -0400
Engine • revision 499a70f5e2
Tools • Dart 2.11.0 (build 2.11.0-234.0.dev)
```

**Comment by mit-mit** [comment] 2020-10-18 10:45
cc @chinmaygarde @a14n not clear to me from that log if this is in the engine or the framework

**Comment by RalphBergmannKMB** [comment] 2020-10-18 12:21
I run into the same issue. It works if you remove `Scaffold` or replace it with `CupertinoPageScaffold`.

This works for me:
```
void main(List<String> args) {
  final String? mode = 'null';
  print('mode: $mode');

  runApp(
    MaterialApp(
      home: CupertinoPageScaffold(
        child: Center(
          child: Text(mode ?? 'mode is null :-('),
        ),
      ),
    ),
  );
}
```

**Comment by jonahwilliams** [comment] 2020-10-18 16:44
I encountered a similar issue in https://github.com/flutter/flutter/issues/68377, fix is to just adjust the type signature . It seems like null assertions do not run on the native binding code

**Comment by TahaTesser** [comment] 2020-10-19 14:48
<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        35.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.7s
Waiting for RMX2001 to report its views...                          11ms
I/.example.fooba(17284): ProcessProfilingInfo new_methods=396 is saved saved_to_disk=1 resolve_classes_delay=5000
Syncing files to device RMX2001...                                 403ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on RMX2001 is available at: http://127.0.0.1:54286/ByBqfXLB-yY=/
I/flutter (17284): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17284): The following _TypeError was thrown during a scheduler callback:
I/flutter (17284): type 'Null' is not a subtype of type 'EngineLayer' of 'function result'
I/flutter (17284): 
I/flutter (17284): When the exception was thrown, this was the stack:
I/flutter (17284): #0      SceneBuilder._pushPhysicalShape (dart:ui/compositing.dart)
I/flutter (17284): #1      SceneBuilder.pushPhysicalShape (dart:ui/compositing.dart:577:5)
I/flutter (17284): #2      PhysicalModelLayer.addToScene (package:flutter/src/rendering/layer.dart:1988:29)
I/flutter (17284): #3      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17284): #4      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17284): #5      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1164:5)
I/flutter (17284): #6      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17284): #7      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17284): #8      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1164:5)
I/flutter (17284): #9      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:440:5)
I/flutter (17284): #10     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1027:15)
I/flutter (17284): #11     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1609:5)
I/flutter (17284): #12     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:765:5)
I/flutter (17284): #13     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:231:37)
I/flutter (17284): #14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:447:18)
I/flutter (17284): #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:907:13)
I/flutter (17284): #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:309:5)
I/flutter (17284): #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (17284): #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (17284): #19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (17284): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (17284): ════════════════════════════════════════════════════════════════════════════════════════════════════
V/PhoneWindow(17284): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@5188d14, this = DecorView@bb5d681[MainActivity]
D/Surface (17284): Surface::connect(this=0x79c32fc000,api=1)
I/SurfaceView(17284): 242482098 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
D/Surface (17284): Surface::connect(this=0x797291d000,api=1)
D/mali_winsys(17284): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (17284): Surface::setBufferCount(this=0x79c32fc000,bufferCount=4)
D/mali_winsys(17284): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl(17284): setSurfaceViewCreated, created:true
I/SurfaceView(17284): 242482098 surfaceChanged -- format=4 w=1080 h=2400 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
D/SurfaceView(17284): updateScreenMode w:1080 h:2400 ViewRoot w:1080 h:2400
D/SurfaceView(17284): try to resquest 60Hz
D/ViewRootImpl(17284): set screen refresh mode 1 due to SurfaceView-242482098
D/SurfaceView(17284): updateScreenMode w:1080 h:2400 ViewRoot w:1080 h:2400
D/SurfaceView(17284): try to resquest 60Hz
W/Gralloc3(17284): mapper 3.x is not supported
E/gralloc (17284): Arm Module v1.0
E/ion     (17284): ioctl c0044901 failed with code -1: Invalid argument
W/gralloc (17284): WARNING: internal format modifier bits not mutually exclusive. AFBC basic bit is always set, so extended AFBC support bits must always be checked.
I/Choreographer(17284): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/flutter (17284): Another exception was thrown: type 'Null' is not a subtype of type 'EngineLayer' of 'function result'

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.95, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.23.0-19.0.pre.95 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a837557634 (29 hours ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 193EBBC9-CC2A-4477-B8A0-A5F12BB51400 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 86.0.4240.80

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment] 2020-10-19 17:50
https://github.com/flutter/engine/pull/21959 should fix this issue.

**Comment by pcsosinski** [comment] 2020-10-19 18:50
@chinmaygarde @jonahwilliams should this be caught in with automated tests running in sound mode?  or do we need to run them with the null safety flag?  @gspencergoog fyi

**Comment by jonahwilliams** [comment] 2020-10-19 18:51
We're currently disabling sound null safety in presubmit, because it used to not work. We should turn the flag on once this lands.

I don't think any engine tests have null safety enabled

**Comment by chinmaygarde** [comment] 2020-10-19 18:56
> I don't think any engine tests have null safety enabled

All tests in the native test harness run with sound null-safety enabled. The Dart tests, scenarios apps and the cirrus framework presubmits need to be updated.

**Comment by jonahwilliams** [comment] 2020-10-19 19:09
OK, in that case, it just means this methods were never called

**Comment by chinmaygarde** [comment] 2020-10-19 19:16
I just checked that this would have been caught in the Dart test harness instead of the native one. I'll update that harness to use default to sound null safety as well. Will update the scenarios app while I am at it.

**Comment by mit-mit** [comment] 2020-10-20 07:37
This appears to now work as of this mornings flutter master (Flutter `1.24.0-2.0.pre.86`,  channel master, revision `dde20448f7`) 🙌.

@chinmaygarde @jonahwilliams @zanderso are there any other known issues yet to land fixes for, or can we close this?

**Comment by jonahwilliams** [comment] 2020-10-20 07:39
A few more: https://github.com/flutter/flutter/issues/68562

and 

https://github.com/flutter/flutter/issues/68561

**Comment by zanderso** [comment] 2020-10-20 15:10
The next attempt to roll into the internal repo will probably uncover additional items, so let's leave this open.

**Comment by goderbauer** [comment] 2020-10-20 23:31
Framework fixes for sound null safety are in https://github.com/flutter/flutter/pull/68642 and https://github.com/flutter/flutter/pull/68661.

**Comment by franklinyow** [comment] 2020-10-21 18:12
The framework fixed has merged, anything else needed before this can be closed?

**Comment by goderbauer** [comment] 2020-10-21 20:13
I just confirmed that what @mit-mit reported in this issue is fully working now on master with the latest framework fixes. I'll close this issue.

**Closed by goderbauer** 2020-10-21 20:13 UTC
Labels: P2, a: null-safety, customer: product, engine, found in release: 1.23, has reproducible steps, waiting for PR to land (fixed)
