### ISSUE TITLE
[Google Maps] GoogleMap overlapping AppBar when scrolling up

### ISSUE THREAD

**Issue by vini2001** [flutter/flutter#41239] opened 2019-09-25 00:51 UTC
On some devices, the maps display fine. However, some times, when I scroll to the very bottom and scroll up slowly, the map overlap App Bar instead of start disappearing from my view (as the other widgets).

I've tested it in more than 4 different devices and simulators, and nothing happens. However it does happen on my friend's iPhone, I don't know why but it's the only widget which overlaps, all the others are scrolling up normally.

https://i.stack.imgur.com/lAmL9.png

````
           Container(
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.width,
                child: GoogleMap(
                  onMapCreated: (mapController) {
                    _mapController = mapController;
                    try {
                      _addMarker();
                    } catch (e) {
                      print(e.toString());
                      _scaffoldKey.currentState.showSnackBar(
                          buildSnackBar('Request location error'));
                    }
                  },
                  markers: _markers,
                  mapType: MapType.normal,
                  scrollGesturesEnabled: false,
                  initialCameraPosition: CameraPosition(target: LatLng(_lead.latitude, _lead.longitude)),
                )),

Edit:

flutter doctor:
````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale
    pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment] 2019-09-25 08:15
What do you mean by scrolling up? I don't see any ScrollView in your code.

I don't understand *the map overlap App Bar instead of start disappearing from my view*

Please tell us which version of map_view you are using? Check pubspec.lock

please provide us the output of `flutter doctor` and give us more context. 
Otherwise we cannot help you.

**Comment by vini2001** [comment] 2019-09-25 09:59
> What do you mean by scrolling up? I don't see any ScrollView in your code.
> 
> I don't understand _the map overlap App Bar instead of start disappearing from my view_
> 
> Please tell us which version of map_view you are using? Check pubspec.lock
> 
> please provide us the output of `flutter doctor` and give us more context.
> Otherwise we cannot help you.

Please, check this record: https://drive.google.com/file/d/1BBIABFhxyTJWDGgpG5IKurNmmn3k8Uun/view?usp=sharing

I'm using the latest version of map_view and flutter doctor doesn't present any issues. There is a Scroll View, I just didn't send the entire code.

**Comment by escamoteur** [comment] 2019-09-25 10:06
Thanks, this is really helpfull for us. Does this happen on iOS and Android?

**Comment by vini2001** [comment] 2019-09-25 10:12
> Thanks, this is really helpfull for us. Does this happen on iOS and Android?

Actually I can't say for sure, I couldn't reproduce the bug either on my 2 android devices or IOS Simulators. The record I sent you was made by my boss

**Comment by escamoteur** [comment] 2019-09-25 10:16
I guess this is related to #30336 which both use platform views.
The video looks like iOS.
Could you ask on which Phone and which iOS version?

**Comment by vini2001** [comment] 2019-09-25 10:27
> I guess this is related to #30336 which both use platform views.
> The video looks like iOS.
> Could you ask on which Phone and which iOS version?

Yes, of course, when he answers me I get back to you, thank you

**Comment by vini2001** [comment] 2019-09-25 12:50
> I guess this is related to #30336 which both use platform views.
> The video looks like iOS.
> Could you ask on which Phone and which iOS version?

iPhone X Latest iOS version

**Comment by TahaTesser** [comment] 2020-09-16 11:33
Hi @vini2001 
I am unable to reproduce this using your code in  listview 

Please check out this code sample

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: [
          Text('Test App'),
          Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.width,
            child: GoogleMap(
              mapType: MapType.hybrid,
              initialCameraPosition: _kGooglePlex,
              onMapCreated: (GoogleMapController controller) {
                _controller.complete(controller);
              },
            ),
          ),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
          Image.network('https://i.imgur.com/QCNbOAo.png'),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a27c242b0e (5 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.7
    • iPhone 11 (mobile)     • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details> 


Are you still experiencing this issue? 
If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by markusaksli-nc** [comment] 2020-10-07 09:07
Closing this as probably fixed.

If there is still something to be done here let me know and I'll reopen.

**Closed by markusaksli-nc** 2020-10-07 09:07 UTC
Labels: P4, a: platform-views, f: scrolling, framework, p: first party, p: maps, platform-ios, plugin, severe: rendering, waiting for customer response
