### ISSUE TITLE
[tool_crash] IndexError: RangeError (index): Index out of range: index should be less than 74182578: 74183277

### ISSUE THREAD

**Issue by SteNeo** [flutter/flutter#127515] opened 2023-05-24 18:46 UTC
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ... open cmd
2. ... flutter upgrade
3. ... results in the error below

## Logs
IndexError: RangeError (index): Index out of range: index should be less than 74182578: 74183277
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4280:7)
#1      InputStream.readUint32 (package:archive/src/util/input_stream.dart:250:22)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:49:34)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:509:42)
#6      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1111:18)
<asynchronous suspension>
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:908:7)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#10     PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:168:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19045.2965], locale en-NA)
    [32m•[39m Flutter version 3.10.1 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d3d8effc68 (8 days ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [32m•[39m Android SDK at C:\Users\basimikes\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Users\basimikes\AppData\Local\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.12 Preview 1.0)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    [32m•[39m Visual Studio Community 2019 version 16.11.32407.337
    [32m•[39m The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2020.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[33m[!][39m Android Studio
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio\bin
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m android-studio-dir = C:\Program Files\Android\Android Studio\bin
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.
    [32m•[39m Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at C:\Users\basimikes\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.88
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2023-05-25 07:08
Closing as duplicate of https://github.com/flutter/flutter/issues/127481

**Closed by darshankawar** 2023-05-25 07:08 UTC
Labels: in triage
