### ISSUE TITLE
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility. Building plugin cloud_firestore...

### ISSUE THREAD

**Issue by ranahardik28** [flutter/flutter#83906] opened 2021-06-03 16:07 UTC
```console

Note: F:\softwares\flutter_windows_1.17.5-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:C:\Users\hardik\Desktop\progran\soearn\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:50: AAPT: error: resource xml/provider_paths (aka com.example.soearn:xml/provider_paths) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 57s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Exception: The plugin cloud_firestore could not be built due to the issue above.
```

**Comment by ranahardik28** [comment] 2021-06-03 16:08
i unable to solve this error

**Comment by TahaTesser** [comment] 2021-06-04 11:13
Hi @ranahardik28 
The issue isn't related to  Flutter, please see this [SO](https://stackoverflow.com/questions/49684685/errorno-resource-found-that-matches-the-given-name-at-resource-with-value).

`Note: F:\softwares\flutter_windows_1.17.5-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.` is just. deprecated message, not an error.  This would also be related to Flutterfire rather than Flutter itself

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-04 11:13 UTC
Labels: in triage

**Comment by ranahardik28** [comment] 2021-06-04 11:32
So how i solve this problem?

**Comment by TahaTesser** [comment] 2021-06-08 12:00
Update your Flutterfire packages and Flutter, Test the issue with and without Flutterfire,
