### ISSUE TITLE
shared_preferences doesn't remove key when application is in detached state

### ISSUE THREAD

**Issue by VarmaTech** [flutter/flutter#60294] opened 2020-06-25 17:05 UTC
I have a json in particular key key_data , but on app exist i need to remove it , but when i call below  nothing is happening as i reopen app data is showing . below is my code 

```
    final sharedPrefs = await SharedPreferences.getInstance();
    Logs.debug("Contains Keys : ${sharedPrefs.getKeys()}");
    sharedPrefs.remove('key_data');

also added  sharedPrefs.reload(); but still no use 
```

[✓] Flutter (Channel dev, 1.19.0-5.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-5.0.pre  
    • Framework revision c264b70ec3 (2 weeks ago), 2020-06-08 09:27:34 -0700
    • Engine revision c7f9725521
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 87c5e3612b)

**Comment by VladyslavBondarenko** [comment] 2020-06-25 17:46
Hi @VarmaTech 
could you provide your `flutter doctor -v` to see also what device are you testing?
and complete reproducible code sample (with used json value)

I can't reproduce it when using `shared_preferences: ^0.5.7+3` with current dev `1.20.0-1.0.pre`

Code sample
```
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () async {
            SharedPreferences prefs = await SharedPreferences.getInstance();
            String val = 'test';
            print("Contains Keys : ${prefs.getKeys()}");
            await prefs.setString('key_data', val);
            print("Contains Keys : ${prefs.getKeys()}");
            await prefs.remove('key_data');
            print("Contains Keys : ${prefs.getKeys()}");
          },
          child: Text('Button'),
        ),
      ),
    ),
  ));
}
```

log
```
I/flutter (28438): Contains Keys : {}
I/flutter (28438): Contains Keys : {key_data}
I/flutter (28438): Contains Keys : {}
```

do you have the same result with this?

**Comment by VarmaTech** [comment] 2020-06-26 04:20
tried like this . 
SharedPreferences prefs = await SharedPreferences.getInstance();
await  prefs.remove('key_data'); here only some issue coming not able to catcher error ,
print('success');

**Comment by VladyslavBondarenko** [comment] 2020-06-26 05:31
@VarmaTech 
could you provide a complete minimal reproducible code sample?

**Comment by VarmaTech** [comment] 2020-06-26 05:38
I tried as a standalone project for you but it is working , but its not working in production project . in which i cant share the source code here . but i am using same code as above only . 

 here is the sample code when app is detached i am calling this method 
 logout() async {
    for (final key in logoutKeys) {
      SharedPreferences sharedPrefs = await SharedPreferences.getInstance();
      Logs.debug("Contains Keys : ${sharedPrefs.getKeys()}");
      Logs.debug("checking for  key : $key");
      if (sharedPrefs.containsKey(key)) {
        try {
          await sharedPrefs.remove(key);
          Logs.debug("Removed key : $key ");
          Logs.debug("Current Keys : ${sharedPrefs.getKeys()}");
        } catch (err) {
          err.toString();
        }
      }else{
      Logs.debug("No key : $key");
      }
    }
  }

in which one key is key_data in logoutKeys but when app is removed i will check for key_data to show . as its showing data after its been removed. 
or else is there a way to get logs , so that i can share it

**Comment by VarmaTech** [comment] 2020-06-26 06:09
i found out that : 
code in lib : 
 ```
/// Removes an entry from persistent storage.
  Future<bool> remove(String key) => _setValue(null, key, null);

  Future<bool> _setValue(String valueType, String key, Object value) {
    final String prefixedKey = '$_prefix$key';
    if (value == null) {
      _preferenceCache.remove(key);
      return _store.remove(prefixedKey);
    } else {
      if (value is List<String>) {
        // Make a copy of the list so that later mutations won't propagate
        _preferenceCache[key] = value.toList();
      } else {
        _preferenceCache[key] = value;
      }
      return _store.setValue(valueType, prefixedKey, value);
    }
  }


```

 return _store.remove(prefixedKey); this method is occurring issue

**Comment by VladyslavBondarenko** [comment] 2020-06-26 14:24
<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MaterialApp(
    initialRoute: '/',
    routes: {
      '/': (context) => FirstScreen(),
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatefulWidget {
  @override
  _FirstScreenState createState() => _FirstScreenState();
}

class _FirstScreenState extends State<FirstScreen> {
  String buttonText = 'check keys';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: ListView(
        children: [
          RaisedButton(
            child: Text('Launch screen'),
            onPressed: () {
              Navigator.pushNamed(context, '/second');
            },
          ),
          RaisedButton(
            child: Text(buttonText),
            onPressed: () async {
              SharedPreferences prefs = await SharedPreferences.getInstance();
              setState(() {
                buttonText = prefs.getKeys().toString();
              });
            },
          ),
        ],
      ),
    );
  }
}


class SecondScreen extends StatefulWidget {
  @override
  _SecondScreenState createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  List logoutKeys = [
    'key_data'
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: ListView(
          children: [
            RaisedButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: Text('Go back!'),
            ),
            RaisedButton(
              onPressed: () async {
                SharedPreferences prefs = await SharedPreferences.getInstance();
                String val = 'test';
                print("Contains Keys : ${prefs.getKeys()}");
                await prefs.setString('key_data', val);
                print("Contains Keys : ${prefs.getKeys()}");
              },
              child: Text('add key_data'),
            ),
          ]
      ),
    );
  }

  @override
  void dispose() async {
    super.dispose();
    for (final key in logoutKeys) {
      SharedPreferences sharedPrefs = await SharedPreferences.getInstance();
      print("Contains Keys : ${sharedPrefs.getKeys()}");
      print("checking for  key : $key");
      if (sharedPrefs.containsKey(key)) {
        try {
          await sharedPrefs.remove(key);
          print("Removed key : $key ");
          print("Current Keys : ${sharedPrefs.getKeys()}");
        } catch (err) {
          err.toString();
        }
      }else{
        print("No key : $key");
      }
    }
  }
}
```

</details>

if you launch second screen, press 'add key_data', press 'go back', press second button on the first screen - it'll show empty  list - key is removed on dispose the second page. 
if you open second page, add key, close app, open again and tap 'check keys' - it'll show {key_data} - dispose wasn't called.

@VarmaTech is it your case? could you edit the code sample and if it isn't?

**Comment by VarmaTech** [comment] 2020-06-26 15:36
code sample modified : 
````
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MaterialApp(
    initialRoute: '/',
    routes: {
      '/': (context) => FirstScreen(),
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatefulWidget {
  @override
  _FirstScreenState createState() => _FirstScreenState();
}

class _FirstScreenState extends State<FirstScreen> with WidgetsBindingObserver {
  String buttonText = 'check keys';
 List logoutKeys = ['key_data'];
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print("State of APP : ${state}");

    if (state == AppLifecycleState.detached) {
      // _notification = state;
      // setState(() {});
      appClose().then((value) {
        print("Logout successfully done");
      });
      // StorageUtils().save(StorageUtils.app_user_login_data, null);
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Future<void> initState() {
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: ListView(
        children: [
          RaisedButton(
            child: Text('Launch screen'),
            onPressed: () {
              Navigator.pushNamed(context, '/second');
            },
          ),
          RaisedButton(
            child: Text(buttonText),
            onPressed: () async {
              SharedPreferences prefs = await SharedPreferences.getInstance();
              setState(() {
                buttonText = prefs.getKeys().toString();
              });
            },
          ),
        ],
      ),
    );
  }

   appClose() async {
    for (final key in logoutKeys) {
      SharedPreferences sharedPrefs = await SharedPreferences.getInstance();
      print("Contains Keys : ${sharedPrefs.getKeys()}");
      print("checking for  key : $key");
      if (sharedPrefs.containsKey(key)) {
        try {
          await sharedPrefs.remove(key);
          print("Removed key : $key ");
          print("Current Keys : ${sharedPrefs.getKeys()}");
        } catch (err) {
          err.toString();
        }
      } else {
        print("No key : $key");
      }
    }
  }
}

class SecondScreen extends StatefulWidget {
  @override
  _SecondScreenState createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: ListView(children: [
        RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
        RaisedButton(
          onPressed: () async {
            SharedPreferences prefs = await SharedPreferences.getInstance();
            String val = 'test';
            print("Contains Keys : ${prefs.getKeys()}");
            await prefs.setString('key_data', val);
            print("Contains Keys : ${prefs.getKeys()}");
          },
          child: Text('add key_data'),
        ),
      ]),
    );
  }


}

````

**Comment by VladyslavBondarenko** [comment] 2020-07-27 11:42
Reproduces with `shared_preferences: ^0.5.8`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.38, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.38 at /Users/nevercode/dev/flutter
    • Framework revision 8e0eee9008 (4 hours ago), 2020-07-26 23:38:01 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Redmi Note 7 (mobile) • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS (desktop)       • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)      • web-server • web-javascript • Flutter Tools
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by Sempakonka** [comment] 2020-09-10 12:11
Hi  @VarmaTech 

When an app gets detached one of the first things that gets shut down is the method channel that flutter uses to communicate with the native code of plug-ins. Therefore it can’t communicate with the native side, which is why your request to remove the data is not working. This is handled inside the Flutter engine itself and not directly related to the shared_preferences plugin. It's the way flutter works, and you will notice this in every plug-in.

You do have a workaround for this.
When you close the app it first goes in an “inactive state”. Calling your request when the app gets in an inactive state, thus before the “detached state”, will complete your request. An inactive state however does get called more often. [See here the documentation.](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html)

**Comment by Sempakonka** [comment] 2020-09-10 12:14
Hi @VarmaTech 

When an app gets detached one of the first things that gets shut down is the method channel that flutter uses to communicate with the native code of plug-ins. Therefore it can’t communicate with the native side, which is why your request to remove the data is not working. The shutdown of the method channel is handled inside the Flutter engine itself and is not directly related to the shared_preferences plugin. It's the way flutter works, and you will notice this in every plug-in.

You do have a workaround for this.
When you close the app it first goes in an “inactive state”. Calling your request when the app gets in an inactive state, thus before the “detached state”, will complete your request. An inactive state however does get called more often. [See here the documentation.](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html)

**Comment by amirh** [comment] 2020-09-16 17:45
closing per @Sempakonka's comment

**Closed by amirh** 2020-09-16 17:45 UTC
Labels: found in release: 1.21, framework, has reproducible steps, p: shared_preferences, plugin
