### ISSUE TITLE
ListView.builder() malfunctions inside an Expanded/Column/SingleChildScrollView widget.

### ISSUE THREAD

**Issue by abayomiAkanji** [flutter/flutter#77527] opened 2021-03-07 18:07 UTC
Although `ListView.builder()` is meant to draw only the visible items of a list (on the screen), I noticed that it works like the normal ListView() when it's wrapped inside another widget like `Expanded`, `Column` and `SingleChildScrollView`. It draws all items at once.

Is there a way to make ListView.builder() work as expected even when wrapped inside another widget?

**Comment by iapicca** [comment] 2021-03-07 20:21
@abayomiAkanji 

> Although `ListView.builder()` is meant to only draw the visible items of a list. I noticed that it works like the normal ListView() when it's wrapped inside another widget like `Expanded`, `Column` and `SingleChildScrollView`. It draws all items at once.

I cannot reproduce the behavior you are describing
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Column(
            children: [
              Expanded(
                child: ListView.builder(
                  itemBuilder: (context, index) => MyWidget(index),
                ),
              ),
            ],
          ),
        ),
      ),
    );

class MyWidget extends StatefulWidget {
  MyWidget(this.index) : super(key: ValueKey(index));
  final index;
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  void initState() {
    print('### initializing: ${widget.index} ###');

    super.initState();
  }

  @override
  void dispose() {
    print('### disposing: ${widget.index} ###');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print('### building: ${widget.index} ###');
    return Center(
      child: FlutterLogo(
        size: MediaQuery.of(context).size.shortestSide,
      ),
    );
  }
}

```

</details>
<details>
<summary>doctor</summary>

```cocnsole
[✓] Flutter (Channel master, 2.1.0-11.0.pre.145, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.145 at /home/francesco/snap/flutter/common/flutter
    • Framework revision a0ba646408 (2 days ago), 2021-03-05 22:09:03 -0500
    • Engine revision f751d04fa0
    • Dart version 2.13.0 (build 2.13.0-107.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.72 snap

! Doctor found issues in 1 category.

```

</details>

if the code sample I provided does not represent the issue
please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by iapicca** [comment] 2021-03-07 20:42
@abayomiAkanji 

> Although `ListView.builder()` is meant to only draw the visible items of a list. I noticed that it works like the normal ListView() when it's wrapped inside another widget like `Expanded`, `Column` and `SingleChildScrollView`. It draws all items at once.

I cannot reproduce the behavior you are describing
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyHomePage()));

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const ValueKey('MyHomePage'));

  @override
  Widget build(BuildContext context) => Material(
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                child: SizedBox.fromSize(
                  size: MediaQuery.of(context).size * .5,
                  child: ListView.builder(
                    itemBuilder: (context, index) => MyWidget(index),
                  ),
                ),
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                child: SizedBox.fromSize(
                  size: MediaQuery.of(context).size * .5,
                  child: ListView.builder(
                    itemBuilder: (context, index) => MyWidget(
                      index,
                      color: Colors.red,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      );
}

class MyWidget extends StatefulWidget {
  MyWidget(this.index, {this.color = const Color.fromRGBO(0, 0, 255, 1)})
      : super(key: ValueKey(index * color.value));
  final int index;
  final Color color;
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  void initState() {
    print('### initializing: ${widget.color} ->${widget.index} ###');

    super.initState();
  }

  @override
  void dispose() {
    print('### disposing: ${widget.color} ->${widget.index} ###');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print('### building: ${widget.color} ->${widget.index} ###');
    return ColoredBox(
      color: widget.color.withOpacity(.2),
      child: Center(
        child: Text(
          '${widget.index}',
          textScaleFactor: 20,
        ),
      ),
    );
  }
}

```

</details>
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.145, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.145 at /home/francesco/snap/flutter/common/flutter
    • Framework revision a0ba646408 (2 days ago), 2021-03-05 22:09:03 -0500
    • Engine revision f751d04fa0
    • Dart version 2.13.0 (build 2.13.0-107.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.72 snap

! Doctor found issues in 1 category.

```

</details>

if the code sample I provided does not represent the issue
please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by abayomiAkanji** [comment] 2021-03-07 21:19
Hi @iapicca Many thanks for your response.

My use-case is like what I have below. I couldn't wrap the first `ListView` in a `SizedBox` because I need it to scroll along with the preceding `Text` widget in its column.

```
class MyHomePage extends StatelessWidget {
   MyHomePage() : super(key: const ValueKey('MyHomePage'));

  final ScrollController scrollController = ScrollController();

  @override
  Widget build(BuildContext context) => Material(
    child: Column(
      children: [
        Expanded(
          child: SingleChildScrollView(
            controller: scrollController,
            child: Column(
              children: [

                Text('Header', style: TextStyle(fontSize: 40, color: Colors.black),),

                ListView.builder(
                  itemBuilder: (context, index) => MyWidget(index),
                  shrinkWrap: true,
                  primary: false,
                  itemCount: 1000,
                ),

              ],
            ),

          ),
        ),
        Expanded(
          child: SingleChildScrollView(
            child: SizedBox.fromSize(
              size: MediaQuery.of(context).size * .5,
              child: ListView.builder(
                itemBuilder: (context, index) => MyWidget(
                  index,
                  color: Colors.red,
                ),
              ),
            ),
          ),
        ),
      ],
    ),
  );
}
```

**Comment by abayomiAkanji** [comment] 2021-03-08 13:33
Hi @iapicca were you able to replicate the issue?

**Comment by iapicca** [comment] 2021-03-08 14:19
@abayomiAkanji 
 its's not an issue with flutter, just a problem with your implementation,
 simply for your use case SingleChildScrollView is the wrong tool for the job
 <details>
<summary>new code sampled</summary>

 ```dart
 import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyHomePage()));

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const ValueKey('MyHomePage'));

  @override
  Widget build(BuildContext context) => Material(
        child: Column(
          children: [
            Expanded(
              child: CustomScrollView(
                slivers: [
                  const SliverToBoxAdapter(
                    child: Text(
                      'Header',
                      style: TextStyle(fontSize: 40, color: Colors.black),
                    ),
                  ),
                  SliverToBoxAdapter(
                    child: SizedBox(
                      height: MediaQuery.of(context).size.height * .5,
                      child: ListView.builder(
                        itemBuilder: (context, index) => MyWidget(
                          index,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                child: SizedBox(
                  height: MediaQuery.of(context).size.height * .5,
                  child: ListView.builder(
                    itemBuilder: (context, index) => MyWidget(
                      index,
                      color: Colors.red,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      );
}

class MyWidget extends StatefulWidget {
  MyWidget(this.index, {this.color = const Color.fromRGBO(0, 0, 255, 1)})
      : super(key: ValueKey(index * color.value));
  final int index;
  final Color color;
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  void initState() {
    print('### initializing: ${widget.color} ->${widget.index} ###');

    super.initState();
  }

  @override
  void dispose() {
    print('### disposing: ${widget.color} ->${widget.index} ###');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print('### building: ${widget.color} ->${widget.index} ###');
    return ColoredBox(
      color: widget.color.withOpacity(.2),
      child: Center(
        child: Text(
          '${widget.index}',
          textScaleFactor: 20,
        ),
      ),
    );
  }
}

```

</details>

**Comment by abayomiAkanji** [comment] 2021-03-08 18:12
Many thanks for your time, @iapicca 

Replacing `SingleChildScrollView` by `CustomScrollView` (as suggested in your code sample) and `ListView.builder` by `SliverList` fixed the issue. Consequently, I didn't have to wrap the "list" widget with `SizedBox` and `SliverToBoxAdapter` - since I now use `SliverList`.

Now, only the visible items of the "list" are drawn (on the screen) and all children of `CustomScrollView` scroll together (as I wanted).

Thanks again.

**Comment by iapicca** [comment] 2021-03-08 19:54
@abayomiAkanji 
Maybe you found an actual bug:
do you mind to reopen the issue?

@TahaTesser 
to reproduce: 
- open the dartpad sample from a phone
- try scroll the blue number
- compare the behavior with desktop browser

**Comment by abayomiAkanji** [comment] 2021-03-08 21:02
Using the [code sample](https://dartpad.dartlang.org/e43800c7b792cce682676e0a1ddf92e4), a scroll on the blue number doesn't automatically scroll the header `Text`. 
This is tested on Chrome & Safari desktop browsers.

**Comment by pedromassangocode** [comment] 2021-03-09 10:17
Hi @iapicca  
https://github.com/flutter/flutter/issues/77527#issuecomment-793030880 does not seems to be related to the issue filled by the author, do you mind filling another issue for that?

Since the actual issue was already solved, I suggest to close this and file a new issue described in https://github.com/flutter/flutter/issues/77527#issuecomment-793030880.
Thank you

**Comment by iapicca** [comment] 2021-03-09 10:57
@pedromassangocode 

> I suggest to close this and file a new issue described in [#77527 (comment)](https://github.com/flutter/flutter/issues/77527#issuecomment-793030880).

alright, I will
you may go ahead and close this on

**Closed** 2021-03-09 11:42 UTC
Labels: in triage, waiting for customer response
