### ISSUE TITLE
webview_flutter doesn't support keyborad

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#33241] opened 2019-05-23 09:21 UTC
1. We are going to use webview_flutter and version is latest version which is 0.3.7+1.
2. We embed our H5 application to the webview of our flutter application, so far we faced a problem the keyboard can not be popup. the keyboard popup works fine within firefox, chrome or any other browser within mobile device. 

here is the information of our flutter development environment.
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by calvinmuller** [comment] 2019-05-23 19:31
The problem with flutter is the keyboard. Unfortunately they only looking to fix this issue around October of this year. see #19718

**Comment by mklim** [comment] 2019-07-18 20:22
Closing as a duplicate of #19718.

**Closed by mklim** 2019-07-18 20:22 UTC
