### ISSUE TITLE
Flutter Windows : CMake Error, Build step for pdfium failed: 1

### ISSUE THREAD

**Issue by aihamhasan** [flutter/flutter#80774] opened 2021-04-20 07:33 UTC
Hi, I am getting this Error while building for windows in debug Mode.
Tried Recreating  Windows folder to solve, dint work.

```console
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)


Exception: Unable to generate build files
Exited (sigterm)
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 1.26.0-1.0.pre at C:\Users\Avin Ronson\flutter
    • Framework revision 63062a6443 (4 months ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Avin Ronson\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Avin Ronson\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Avin Ronson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```
	
</details>

Flutter Verbose:

<details> 
<summary>logs</summary> 

```console
[   +3 ms]     'https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/4482/pdfium-windows-x64.zip'
[   +1 ms]     Found bundle for host github.com: 0x777f10 [serially]
[   +1 ms]     Re-using existing connection! (#0) with host github.com
[   +1 ms]     Connected to github.com (13.234.210.38) port 443 (#0)
[   +1 ms]     GET
[   +1 ms]     /bblanchon/pdfium-binaries/releases/download/chromium/4482/pdfium-windows-x64.zip
[   +4 ms]     HTTP/1.1
[   +1 ms]     Host: github.com
[   +2 ms]     User-Agent: curl/7.71.1
[   +1 ms]     Accept: */*
[   +1 ms]     Mark bundle as not supporting multiuse
[        ] CUSTOMBUILD : The requested URL returned error : 404 Not Found
[D:\DSI_projects\sanjali_app\build\windows\pdfium-download\pdfium-download.vcxproj]
[   +4 ms]     Closing connection 0
[   +1 ms]     schannel: shutting down SSL/TLS connection with github.com port 443
[        ]            --- LOG END ---
[  +28 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
[  +11 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066:Custom build for
'D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-download.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-update.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-patch.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-configure.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-build.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-install.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\0ecaae8c88dde8a2694367e826a40e0d\pdfium-download-test.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\ec03b754b8ea7596a9f0e938292ada90\pdfium-download-complete.rule;D:\DSI_projects\sanjali_app\build\windows\pdfium-download\CMakeFiles\57a292f3ade5fbc031fcdb0caf5563c7\pdfium-download.rule' exited with code 1.    
[D:\DSI_projects\sanjali_app\build\windows\pdfium-download\pdfium-download.vcxproj]
[   +9 ms] -- Configuring incomplete, errors occurred!
[   +5 ms] See also "D:/DSI_projects/sanjali_app/build/windows/CMakeFiles/CMakeOutput.log".
[   +1 ms]   Build step for pdfium failed: 1
[   +3 ms] Call Stack (most recent call first):
[   +2 ms]   flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:23 (download_project)
[  +61 ms] Building Windows application... (completed in 94.3s)
[   +5 ms] Exception: Unable to generate build files
[  +12 ms] "flutter run" took 1,04,563ms.
```

</details>

**Comment by TahaTesser** [comment] 2021-04-20 08:53
Hi @aihamhasan 
Looks like you're running an older version

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by aihamhasan** [comment] 2021-04-20 10:30
Hi, the issue seems to be coming from [Printing package ](https://github.com/DavBfr/dart_pdf/issues/646)

**Comment by TahaTesser** [comment] 2021-04-20 10:35
Hi @aihamhasan 
Given your last message I feel safe to close this issue, if you disagree please write in the comments
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-20 10:35 UTC
Labels: in triage
