### ISSUE TITLE
AndroidX Flutter plugin dependency settings (e.g. image_picker ^0.5.0+3 break on AndroidX)

### ISSUE THREAD

**Issue by iKK001** [flutter/flutter#28207] opened 2019-02-20 13:31 UTC
Using `image_picker: ^0.5.0+3`

I have a problem with my Android App (iOS works fine).

Trying to launch my Flutter App in VSCode, I get the following error message (see long text below...).

It must have something to do with the Android update that I did yesterday. I went from `grade-3.2.1` to `grade-3.3.1` (and by the way, also did update Kotlin to 1.3.21) inside Android Studio.

Also, I did migrate to AndroidX [(as described here)](https://developer.android.com/jetpack/androidx/migrate).

Before this Android gradle-update and X-migration, I had `image_picker 0.5.0+3` running fine. After Android update, I can only get `image_picker 0.4.12+1` working (but no longer `0.5.0+3`).

I suspect AndroidX-migration must have something to do with this. (because setting the gradle back 
to `3.2.1` does not help).

How could I set back the Android-X migration ??

Here is the error message when using `image_picker: ^0.5.0+3` :

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Error detected in pubspec.yaml:
#/properties/flutter: unallowed additional property asserts
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java:42: error: cannot find symbol
      throw  RuntimeException(e);
             ^
  symbol:   method RuntimeException(IOException)
  location: class ImageResizer
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java:87: error: cannot find symbol
    ByteArrayOutputStream outputStream =  ByteArrayOutputStream();
                                          ^
  symbol:   method ByteArrayOutputStream()
  location: class ImageResizer
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java:93: error: cannot find symbol
    File imageFile =  File(externalFilesDirectory, "/scaled_" + imageName);
                      ^
  symbol:   method File(File,String)
  location: class ImageResizer
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java:94: error: cannot find symbol
    FileOutputStream fileOutput =  FileOutputStream(imageFile);
                                   ^
  symbol:   method FileOutputStream(File)
  location: class ImageResizer
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:29: error: cannot find symbol
    final MethodChannel channel =  MethodChannel(registrar.messenger(), CHANNEL);
                                   ^
  symbol:   method MethodChannel(BinaryMessenger,String)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:33: error: cannot find symbol
    final ExifDataCopier exifDataCopier =  ExifDataCopier();
                                           ^
  symbol:   method ExifDataCopier()
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:34: error: cannot find symbol
    final ImageResizer imageResizer =  ImageResizer(externalFilesDirectory, exifDataCopier);
                                       ^
  symbol:   method ImageResizer(File,ExifDataCopier)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:37: error: cannot find symbol
         ImagePickerDelegate(registrar.activity(), externalFilesDirectory, imageResizer);
         ^
  symbol:   method ImagePickerDelegate(Activity,File,ImageResizer)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:41: error: cannot find symbol
    final ImagePickerPlugin instance =  ImagePickerPlugin(registrar, delegate);
                                        ^
  symbol:   method ImagePickerPlugin(Registrar,ImagePickerDelegate)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:67: error: cannot find symbol
          throw  IllegalArgumentException("Invalid image source: " + imageSource);
                 ^
  symbol:   method IllegalArgumentException(String)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:79: error: cannot find symbol
          throw  IllegalArgumentException("Invalid video source: " + imageSource);
                 ^
  symbol:   method IllegalArgumentException(String)
  location: class ImagePickerPlugin
/Users/stephankorner/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.5.0+3/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:82: error: cannot find symbol
      throw  IllegalArgumentException("Unknown method " + call.method);
             ^
  symbol:   method IllegalArgumentException(String)
  location: class ImagePickerPlugin
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
         *********************************************************
WARNING: This version of image_picker will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by zoechi** [comment] 2019-02-20 14:12
Looks to me like the AndroidX migration is incomplete.

Did you add
```
android.useAndroidX=true
android.enableJetifier=true
```
to `gradle.properties`

**Comment by iKK001** [comment] 2019-02-20 14:33
Yes, I did. Thanks for helping. I actually found out that there were other plugins in my project that were not compatible to AndroidX. And I have the App upNrunning now with AndroidX but, of course, the need for using the old-plugin-versions as stated on this [AndroidX-compatibility page](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility). I have a general question about AndroidX: What is the current recommendation for Flutter projects - should you migrate to AndroidX or should you still not ?? (I understand that it is up to anybody to decide whether using older plugin-versions with AndroidX is an option or using the newest plugin-versions without AndroidX (i.e. with appCompat). What would you recommend today ?

**Comment by zoechi** [comment] 2019-02-20 14:58
@mklim might be able to give some advice

**Comment by mklim** [comment] 2019-02-22 00:16
I'm really sorry that this has been such a frustrating breakage.

> I have a general question about AndroidX: What is the current recommendation for Flutter projects - should you migrate to AndroidX or should you still not ?? (I understand that it is up to anybody to decide whether using older plugin-versions with AndroidX is an option or using the newest plugin-versions without it (i.e. still with appCompat). What would you recommend today ?

Ultimately I don't think I can give a blanket recommendation across all apps. The old support libraries are deprecated, so I'd recommend using AndroidX in most cases going forward. But there may be specific  concerns around an app that make it better to stay on the old libraries right now instead. Like if it's depending on a plugin that isn't compatible with AndroidX yet, or if there just isn't any capacity to make a migration at all right now.

It sounds like the underlying problem you hit here is a duplicate of #27901, so I'm going to close this issue.

**Closed by mklim** 2019-02-22 00:16 UTC
Labels: p: tooling, plugin, t: gradle, tool
