### ISSUE TITLE
Script '/Users/user/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

### ISSUE THREAD

**Issue by PProtonzz** [flutter/flutter#135209] opened 2023-09-21 08:51 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm trying to run my existing app in the new system and getting this error.

### Actual results

FAILURE: Build failed with an exception.

* Where:
Script '/Users/pranavfulkari/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/pranavfulkari/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by PProtonzz** [comment] 2023-09-21 11:22
> Hi @PProtonzz When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly.
> 
> More specifically, please provide the information indicated below:
> 
> * Please check if the issue occurs on a newly created Flutter project. If it is not, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> * The output of `flutter doctor -v`
> * Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

Issue occurs on only this project, new flutter project runs smoothly.

**Comment by huycozy** [comment] 2023-09-22 03:36
Please provide the entire output of `flutter run -v` and the remaining information indicated in the [previous comment](https://github.com/flutter/flutter/issues/135209#issuecomment-1729339532) that will help to investigate the issue better.

**Comment by eltontay** [comment] 2023-09-24 04:12
Im facing this exact same issue too

**Comment by nfuenmamelt** [comment] 2023-09-24 14:06
I have the same issue, I created a new proyect and can build the appbundle well, but with my real proyect i get this issue

**COMMAND flutter build appbundle**
➜  jmj_labor git:(master) ✗ flutter build appbundle                         
Downloading Material fonts...                                      431ms
Downloading Gradle Wrapper...                                       28ms
Downloading package sky_engine...                                   78ms
Downloading flutter_patched_sdk tools...                           168ms
Downloading flutter_patched_sdk_product tools...                   127ms
Downloading linux-x64 tools...                                   1,925ms
Downloading linux-x64/font-subset tools...                          68ms
Downloading android-arm-profile/linux-x64 tools...                 671ms
Downloading android-arm-release/linux-x64 tools...                 823ms
Downloading android-arm64-profile/linux-x64 tools...               750ms
Downloading android-arm64-release/linux-x64 tools...               743ms
Downloading android-x64-profile/linux-x64 tools...                 795ms
Downloading android-x64-release/linux-x64 tools...                 666ms
Resolving dependencies... 
  archive 3.3.0 (3.4.2 available)
  args 2.3.1 (2.4.2 available)
> async 2.11.0 (was 2.9.0)
  bloc 7.2.1 (8.1.2 available)
> boolean_selector 2.1.1 (was 2.1.0)
> characters 1.3.0 (was 1.2.1)
> collection 1.18.0 (was 1.16.0)
  cross_file 0.3.2 (0.3.3+5 available)
  crypto 3.0.2 (3.0.3 available)
  cupertino_icons 1.0.4 (1.0.6 available)
  ffi 1.1.2 (2.1.0 available)
  file 6.1.2 (7.0.0 available)
  flutter_bloc 7.3.3 (8.1.3 available)
  flutter_lints 1.0.4 (2.0.3 available)
  flutter_plugin_android_lifecycle 2.0.5 (2.0.16 available)
  geocoding 2.0.4 (2.1.0 available)
  geocoding_platform_interface 2.0.1 (3.0.0 available)
  http 0.13.4 (1.1.0 available)
  http_parser 4.0.0 (4.0.2 available)
  icons_launcher 1.1.8 (2.1.3 available)
  image 3.1.3 (4.1.0 available)
  image_picker 0.8.4+11 (1.0.4 available)
  image_picker_for_web 2.1.6 (3.0.1 available)
  image_picker_platform_interface 2.4.4 (2.9.1 available)
  js 0.6.4 (0.6.7 available)
  lints 1.0.1 (2.1.1 available)
  location 4.4.0 (5.0.3 available)
  location_platform_interface 2.3.0 (3.1.2 available)
  location_web 3.1.1 (4.2.0 available)
> matcher 0.12.16 (was 0.12.12)
> material_color_utilities 0.5.0 (was 0.1.5) (0.8.0 available)
> meta 1.10.0 (was 1.8.0)
> path 1.8.3 (was 1.8.2)
  path_provider_linux 2.1.5 (2.2.1 available)
  path_provider_platform_interface 2.0.3 (2.1.1 available)
  path_provider_windows 2.0.5 (2.2.1 available)
  petitparser 4.4.0 (6.0.1 available)
  platform 3.1.0 (3.1.2 available)
  plugin_platform_interface 2.1.2 (2.1.6 available)
  process 4.2.4 (5.0.0 available)
  provider 6.0.2 (6.0.5 available)
  shared_preferences 2.0.13 (2.2.1 available)
  shared_preferences_android 2.0.11 (2.2.1 available)
  shared_preferences_ios 2.1.0 (2.1.1 available)
  shared_preferences_linux 2.1.0 (2.3.1 available)
  shared_preferences_macos 2.0.3 (2.0.5 available)
  shared_preferences_platform_interface 2.0.0 (2.3.1 available)
  shared_preferences_web 2.0.3 (2.2.1 available)
  shared_preferences_windows 2.1.0 (2.3.1 available)
> source_span 1.10.0 (was 1.9.0)
> stack_trace 1.11.1 (was 1.10.0)
> stream_channel 2.1.2 (was 2.1.0)
> string_scanner 1.2.0 (was 1.1.1)
> test_api 0.6.1 (was 0.4.12)
  typed_data 1.3.0 (1.3.2 available)
  universal_io 2.0.4 (2.2.2 available)
> vector_math 2.1.4 (was 2.1.2)
+ web 0.2.1-beta
  win32 2.4.1 (5.0.8 available)
  xdg_directories 0.2.0+1 (1.0.3 available)
  xml 5.3.1 (6.4.2 available)
  yaml 3.1.1 (3.1.2 available)
Changed 15 dependencies!
48 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

../../../../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../../../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../../../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Running Gradle task 'bundleRelease'...                             10.8s
Gradle task bundleRelease failed with exit code 1

I'm working on ubuntu 22.04

**OUTPUT OF FLUTTER DOCTOR -V**
➜  jmj_labor git:(master) ✗ flutter doctor -v      
[   +3 ms] Could not interpret results of "git describe": 3.15.0-6.0.pre.69
[   +9 ms] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +16 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +51 ms] executing: /opt/android-studio/jbr/bin/java -version
[  +51 ms] Exit code 0 from: /opt/android-studio/jbr/bin/java -version
[        ] openjdk version "17.0.6" 2023-01-17
           OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
           OpenJDK 64-Bit Server VM (build 17.0.6+0-17.0.6b829.9-10027231, mixed mode)
[   +6 ms] executing: /opt/android-studio/jbr/bin/java -version
[  +54 ms] Exit code 0 from: /opt/android-studio/jbr/bin/java -version
[        ] openjdk version "17.0.6" 2023-01-17
           OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
           OpenJDK 64-Bit Server VM (build 17.0.6+0-17.0.6b829.9-10027231, mixed mode)
[  +24 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8bc223e3e5cc919bada837ecc0afdc546969a79e
[        ] executing: [/opt/flutter/] git symbolic-ref --short HEAD
[   +2 ms] Exit code 0 from: git symbolic-ref --short HEAD
[        ] master
[        ] executing: [/opt/flutter/] git fetch https://github.com/flutter/flutter.git --tags -f
[+1127 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags -f
[        ] From https://github.com/flutter/flutter
            * branch                  HEAD       -> FETCH_HEAD
[        ] executing: [/opt/flutter/] git tag --points-at 8bc223e3e5cc919bada837ecc0afdc546969a79e
[  +14 ms] Exit code 0 from: git tag --points-at 8bc223e3e5cc919bada837ecc0afdc546969a79e
[   +1 ms] executing: [/opt/flutter/] git describe --match *.*.* --long --tags 8bc223e3e5cc919bada837ecc0afdc546969a79e
[  +24 ms] Exit code 0 from: git describe --match *.*.* --long --tags 8bc223e3e5cc919bada837ecc0afdc546969a79e
[        ] 3.15.0-5.0.pre-69-g8bc223e3e5
[   +1 ms] executing: [/opt/flutter/] git symbolic-ref --short HEAD
[   +3 ms] Exit code 0 from: git symbolic-ref --short HEAD
[        ] master
[   +6 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 9 hours ago
[  +16 ms] executing: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --version
[  +26 ms] Exit code 0 from: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --version
[        ] openjdk 11.0.20.1 2023-08-24
           OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
           OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
[   +7 ms] executing: /home/nfuenma/Android/SDK/platform-tools/adb devices -l
[  +16 ms] [✓] Flutter (Channel master, 3.15.0-6.0.pre.69, on Ubuntu 22.04.3 LTS 6.2.0-33-generic, locale en_US.UTF-8)
[        ]     • Flutter version 3.15.0-6.0.pre.69 on channel master at /opt/flutter
[        ]     • Upstream repository https://github.com/flutter/flutter.git
[        ]     • Framework revision 8bc223e3e5 (9 hours ago), 2023-09-23 22:14:20 -0700
[        ]     • Engine revision 2daf5e7bb2
[        ]     • Dart version 3.2.0 (build 3.2.0-191.0.dev)
[        ]     • DevTools version 2.28.0-dev.12
[  +12 ms] List of devices attached
[  +36 ms] executing: /home/nfuenma/Android/SDK/platform-tools/adb devices -l
[   +8 ms] List of devices attached
[+1542 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[        ]     • Android SDK at /home/nfuenma/Android/SDK
[        ]     • Platform android-33, build-tools 31.0.0
[        ]     • ANDROID_HOME = /home/nfuenma/Android/SDK
[        ]     • Java binary at: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
[        ]     • All Android licenses accepted.
[        ] [✓] Chrome - develop for the web
[        ]     • Chrome at google-chrome
[        ] [✓] Linux toolchain - develop for Linux desktop
[        ]     • Ubuntu clang version 14.0.0-1ubuntu1.1
[        ]     • cmake version 3.22.1
[        ]     • ninja version 1.10.1
[        ]     • pkg-config version 0.29.2
[        ] [✓] Android Studio (version 2022.3)
[        ]     • Android Studio at /opt/android-studio
[        ]     • Flutter plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
[        ]     • Dart plugin can be installed from:
[        ]       🔨 https://plugins.jetbrains.com/plugin/6351-dart
[        ]     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
[        ] [✓] VS Code (version unknown)
[        ]     • VS Code at /snap/code/current
[        ]     • Flutter extension version 3.72.0
[        ]     ✗ Unable to determine VS Code version.
[        ] [✓] Connected device (2 available)
[        ]     • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-33-generic
[        ]     • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110
[        ] [✓] Network resources
[        ]     • All expected network resources are available.
[        ] • No issues found!
[   +6 ms] "flutter doctor" took 3,095ms.
[ +226 ms] ensureAnalyticsSent: 216ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by nikolaj808** [comment] 2023-10-05 07:03
I have the exact same issue as nfuenmamelt

**Comment by ali-1989** [comment] 2023-10-14 21:38
this error is for flutter codes and is not for android.

**Comment by huycozy** [comment] 2023-10-16 03:33
For anyone facing this issue: The error mentioned in the original comment is just the final error from the Flutter tool implying that an error occurred in the internal Gradle build tool. It can be due to many reasons that need the output of `flutter run -v` to know more clearly.

For @nfuenmamelt output above, it may be caused by the method params of the package he used `file-6.1.2` have been changed across versions, see https://pub.dev/packages/file/changelog

For better support, please open a new issue and provide all the information in the issue template so that we can verify it properly. Closing this issue from here.

**Closed by huycozy** 2023-10-16 03:33 UTC
Labels: waiting for customer response, in triage
