### ISSUE TITLE
[go_router] Navigating back does not update router location since `go_router` 5.2.0 

### ISSUE THREAD

**Issue by ndelanou** [flutter/flutter#115913] opened 2022-11-23 10:12 UTC
Just switched to `go_router` 5.2.0 from 5.1.9

My app is using `ShellRoute` and `GoRoute` with only `builder:` (no `pageBuilder:`)

The problem I face is that, after upgrading to 5.2.0, the getter `location`from my `GoRouter`instances does not update after navigating back from a child page.

To navigate back, I either:
```dart
GoRouter.of(context).pop();
```
or
```dart
Navigator.of(context).pop();
```

To get the current location:
```dart
final router = GoRouter.of(context);
final currentLocation = router.location;
```

I get different errors in my project related to navigation with this issue since I use the current location to navigate in my app.

</details>

<details>
  <summary>Logs</summary>

```
╰─ flutter analyze
Analyzing mobile...
No issues found! (ran in 2.9s)
```

```
╰─ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale en-FR)
    • Flutter version 3.3.8 on channel stable at xxxxxxxxxxxxxxxxxxxxxxxxxx
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at xxxxxxxxxxxxxxxxxxxxxxxxxx
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 067BF70E-951D-4615-BD8A-11DF75B16A74 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-23 13:15
Hi @ndelanou,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this issue.

Thank you

**Comment by conghaonet** [comment] 2022-11-23 15:15
I had the same problem.

Code Example:

// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.go('/details'),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <ElevatedButton>[
            ElevatedButton(
              onPressed: () => context.pop(),
              child: const Text('Go back to the Home screen'),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by bit-void** [comment] 2022-11-23 20:01
I'm seeing this issue with 5.1.9 and 5.2.0. With `ShellRoute` with nested children set up like this:

```dart
  final _router = GoRouter(
    initialLocation: "/plants",
    routes: [
      ShellRoute(
        builder: (context, state, child) {
          return AppScaffold(
            child: child,
          );
        },
        routes: <RouteBase>[
          GoRoute(
            path: '/plants',
            pageBuilder: (context, state) =>
                const NoTransitionPage(child: ExploreTab()),
            routes: [
              GoRoute(
                path: ":id",
                builder: (context, state) {
                  return PlantScreen(id: state.params["id"]!);
                },
              )
            ],
          ),
          GoRoute(
            path: '/garden',
            pageBuilder: (context, state) =>
                const NoTransitionPage(child: GardenTab()),
            routes: [
              GoRoute(
                path: ":id",
                builder: (context, state) {
                  return PlantScreen(id: state.params["id"]!);
                },
              )
            ],
          ),
        ],
      ),
    ],
  )
```

I end up unable to renavigate to to the same `id` if I go back and forth from a list view to a details view. 

Here is a video showing this issue:

https://user-images.githubusercontent.com/161737/203636179-6476e923-cae3-4734-85cc-b688e18d242f.mov

And here is the full log:

```
Performing hot restart...
Syncing files to device iPhone 14 Pro Max...
Restarted application in 580ms.
[GoRouter] INFO: 2022-11-23 14:59:59.002560 Full paths for routes:

[GoRouter] INFO: 2022-11-23 14:59:59.007496 setting initial location /plants
[GoRouter] INFO: 2022-11-23 14:59:59.265585 Using MaterialApp configuration
flutter: initializing garden
[GoRouter] INFO: 2022-11-23 15:00:23.489184 going to /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
[GoRouter] INFO: 2022-11-23 15:00:24.618979 popping /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
[GoRouter] INFO: 2022-11-23 15:00:25.401664 going to /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
[GoRouter] INFO: 2022-11-23 15:00:26.184702 going to /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
[GoRouter] INFO: 2022-11-23 15:00:27.434981 going to /plants/3dc16cea-61f0-4bcc-8e04-1c6e252ca1d6
[GoRouter] INFO: 2022-11-23 15:00:28.786222 popping /plants/3dc16cea-61f0-4bcc-8e04-1c6e252ca1d6
[GoRouter] INFO: 2022-11-23 15:00:29.735863 going to /plants/3dc16cea-61f0-4bcc-8e04-1c6e252ca1d6
[GoRouter] INFO: 2022-11-23 15:00:30.468003 going to /plants/3dc16cea-61f0-4bcc-8e04-1c6e252ca1d6
[GoRouter] INFO: 2022-11-23 15:00:31.802194 going to /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
[GoRouter] INFO: 2022-11-23 15:00:32.805591 popping /plants/5544f692-5d74-46b1-b167-94e85cb7e95f
```

**Comment by jauntybrain** [comment] 2022-11-24 01:01
I have the same issue, GoRouter 5.2.0. Are there any known solutions yet?

**Comment by lukaszdebowski** [comment] 2022-11-24 08:36
This same issue also is present on the go_router package official example of the ShellRoute (`examples/shell_route.dart`) - navigating to a details page in TabA, then going back using the app bar back button, and navigating again to the details page on the same tab doesn't work. (also, the url is not updated after going back from the details screen)

**Comment by danagbemava-nc** [comment] 2022-11-24 10:04
Reproducible using the code sample in https://github.com/flutter/flutter/issues/115913#issuecomment-1325234799
It is also reproducible using the shell_route example from the package examples. 

This is likely a regression, although I'm not sure on which version the issue appeared. 

Labeling for further investigation

<details>
<summary>recordings</summary>

https://user-images.githubusercontent.com/88313112/203755613-42963e15-2c65-4db3-b246-09b7d7edeea6.mp4
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.1.1 20B101
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.6.0-7.0.pre.45, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.6.0-7.0.pre.45 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d0352f55db (9 hours ago), 2022-11-23 20:01:26 -0500
    • Engine revision 9b2895724c
    • Dart version 2.19.0 (build 2.19.0-424.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.1.1 20B101
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

**Comment by mregandla** [comment] 2022-11-24 14:42
I did not see this issue in 4.5.1. But from 5.0.0, I see this.

**Comment by vinay416** [comment] 2022-11-24 15:20
> I did not see this issue in 4.5.1. But from 5.0.0, I see this.

Yeah you are right I almost check all version above 5.0.0 and all have the issues.

**Comment by ValentinVignal** [comment] 2022-11-25 07:34
I think this is a duplicate of https://github.com/flutter/flutter/issues/115832

**Comment by danagbemava-nc** [comment] 2022-11-25 13:14
Closing this in favor of https://github.com/flutter/flutter/issues/115832.

Kindly follow up in the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2022-11-25 13:14 UTC
Labels: severe: regression, p: first party, package, has reproducible steps, p: go_router, found in release: 3.3, found in release: 3.6
