### ISSUE TITLE
FileSystemException: Cannot resolve symbolic links, path = 'D:\Єагв\path\adb.exe' (OS Error: The system cannot find the specified path.

### ISSUE THREAD

**Issue by Vodeninja** [flutter/flutter#144500] opened 2024-03-02 05:46 UTC
### Steps to reproduce

flutter doctor -v

### Actual results

error

### Logs

<details open>
<summary>Logs</summary>

```console
empty
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

FileSystemException: Cannot resolve symbolic links, path = 'D:\Єагв\path\adb.exe' (OS Error: The system cannot find the specified path.
, errno = 3)
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:826:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:357:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:145:41)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:155:36)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#10     androidSdk (package:flutter_tools/src/globals.dart:69:39)
#11     generateCommands (package:flutter_tools/executable.dart:185:25)
#12     main.<anonymous closure> (package:flutter_tools/executable.dart:92:11)
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:53:13)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

</details>

**Comment by Vodeninja** [comment] 2024-03-02 05:47
![image](https://github.com/flutter/flutter/assets/62830084/b91d6ebb-3e8e-4d5f-bd77-c935d894407b)

**Comment by danagbemava-nc** [comment] 2024-03-04 07:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/59770.

**Closed by danagbemava-nc** 2024-03-04 07:28 UTC
Labels: in triage
