### ISSUE TITLE
Flutter firebase background handler is not working

### ISSUE THREAD

**Issue by bilalgodesto** [flutter/flutter#85028] opened 2021-06-22 09:24 UTC
I am using  firebase_messaging: ^10.0.0.
When app is in background. I receive the notification but background handler is not called.
Background Modes
  ```
<key>UIBackgroundModes</key>
  <array>
  <string>audio</string>
  <string>processing</string>
  <string>fetch</string>
  <string>remote-notification</string>
  </array>
```
Push notification 
are enabled in my Xcode.

Here is my main.dart file.

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('TTEST CALLED');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: false,
    badge: false,
    sound: false,
  );
  Eraser.clearAllAppNotifications();
  Eraser.resetBadgeCountAndRemoveNotificationsFromCenter();
  print('MAIN');
  runApp(MyApp());
}

```
Here is flutter doctor 

```
```

```

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
    • Flutter version 2.2.1 at /Users/bilalrabbi/flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bilalrabbi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Bilal Rabbi’s iPhone (mobile) • 00008030-001004D80146802E • ios            • iOS 14.2
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 91.0.4472.106

```

</details>

**Comment by TahaTesser** [comment] 2021-06-22 09:26
Hi @bilalgodesto 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-22 09:26 UTC
Labels: in triage

**Comment by bilalgodesto** [comment] 2021-06-22 10:15
It seems like flutter issue as background messages should be handled but if you consider it firebase issue i have also posted on firebase. Thanks
