### ISSUE TITLE
Hot reload does not work automatically. Have to manually run it

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#6553] opened 2016-10-27 10:19 UTC
When running IntelliJ or Atom, the file changes are not reflected till I manually hit the hot reload icon in IntelliJ or the Reload button in Atom.

Even running flutter --run has the same behavior, I have to press R and then hot reload works.

Looks like the file watcher isn't working? B
## Logs

This log may be a red herring as I don't thinks related to the bug, but Atom, IntelliJ and flutter run all cause this to show up.

```
Starting device daemon...
Launching loader on iPhone 6...
CoreSimulatorBridge: LaunchServices: no bundle found with identifier com.apple.MobileSMS
com.apple.CoreSimulator.SimDevice.AB99FA55-DC63-4011-AF53-40AAC2C798F2.launchd_sim[5233] (UIKitApplication:com.yourcompany.MyFirstFlutterApp[0x3c01]: Service exited due to signal: Terminated: 15
CoreSimulatorBridge: Requesting launch of com.yourcompany.MyFirstFlutterApp with options: {
        arguments =     (
            "--flx=/Users/FaisalAbid/Development/workspace/MyFirstFlutterApp/build/app.flx",
            "--dart-main=/Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter/packages/flutter/bin/loader/loader_app.dart",
            "--packages=/Users/FaisalAbid/Development/workspace/MyFirstFlutterApp/.packages",
            "--enable-checked-mode",
            "--start-paused",

            "--observatory-port=8100"
        );
        environment =     {
        };
    }
SpringBoard: Application 'UIKitApplication:com.yourcompany.MyFirstFlutterApp[0x3c01]' exited abnormally via signal.
assertion failed: 16B2548a 12H141: libxpc.dylib + 59338 [AF8FA08F-353B-303B-A08E-AEBB3C60A640]: 0x7d
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.

```
## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision 949e27ae8f (16 hours ago), 2016-10-26 19:11:55
    • Engine revision 7e5d63513a
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-N, build-tools 24.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • iPhone 6 • AB99FA55-DC63-4011-AF53-40AAC2C798F2 • ios (simulator)
```

**Comment by eseidelGoogle** [comment] 2016-10-27 13:01
This is currently intended behavior.  There is no watcher.  That said, I think having reload-on-save wired up could be a useful feature.  I'll retitle the bug.

**Comment by FaisalAbid** [comment] 2016-10-27 13:03
Oh I see! From the demos I thought it was done automatically on save. That's cool, I can hook up a keyboard shortcut to it. 

Thanks!

**Comment by mit-mit** [comment] 2016-10-27 13:09
@FaisalAbid, to add a custom keyboard shortcut for hot reload in IntelliJ:

1. go to preferences
1. select Keymap in the menu
1. enter 'flutter' in the search field
1. right-click on 'Flutter Hot Reload' and select 'Add Keyboard Shortcut'

**Comment by eseidelGoogle** [comment] 2016-10-27 13:10
Yeah, I re-wired mine to command-R (hot reload) and command-shift-R (hot restart) due to muscle-memory from using Atom for so long. :)  I believe there has been discussion in other bugs of adding some non-conflicting default keybindings for these over in https://github.com/flutter/flutter-intellij/issues.

**Comment by mit-mit** [comment] 2016-10-27 13:12
> I believe there has been discussion in other bugs of adding some non-conflicting default keybindings for these

Yup: https://github.com/flutter/flutter-intellij/issues/335

**Comment by Hixie** [comment] 2016-11-24 22:31
Does this require anything on the Flutter side, or is it just an IntelliJ issue?

**Comment by Hixie** [comment] 2017-02-27 21:38
Closing since this is working as intended. Feel free to file a bug if you want a specific change, describing the change you would like.

**Closed by Hixie** 2017-02-27 21:38 UTC
Labels: dev: tool
