### ISSUE TITLE
Should support manually growing an overflowing bottom sheet

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#497] opened 2015-11-19 20:35 UTC
We do this:

> Bottom sheets slide up from the bottom of the screen and initially cover a portion of the screen.
> The initial height of a bottom sheet is relative to the height of the list items (or grid rows) it contains. A bottom sheet should not initially have a height beyond its 16:9 ratio keyline, depending on how much content it contains.

We don't do this:

> Bottom sheets may be swiped up to fill the height of the screen, with content that then scrolls internally.
> 
> When displaying a long list, modal bottom sheets can scroll internally and expand past the 16:9 keyline.

The spec talks about how far it can grow in its rested state:

> When displaying menu items, fully-expanded modal bottom sheets maintain a minimum 8dp distance from the bottom of the app bar.

I believe the above means _non-fully-expanded_ modal bottom sheets. If you expand fully, you're supposed to take over the toolbar:

> Fully-expanded modal bottom sheets provide an X in the app bar.

https://www.google.com/design/spec/components/bottom-sheets.html

**Comment by Hixie** [comment] 2015-11-19 21:08
One thing we could do here is for BottomSheet (previously _BottomSheetDragController) to put a Block inside itself and use that to determine the max height (right now the height is passed in).

**Comment by Hixie** [comment] 2016-04-18 17:40
@HansMuller sounds like there's starting to be demand for this, FWIW.

**Comment by apwilson** [comment] 2016-04-18 17:43
Hit this issue today.  Kind of annoying as I then need to wrap my content in a Block which then disables the modal bottom sheet pull up/down behaviour

**Comment by RyanAfrish7** [comment] 2018-05-13 08:41
An year after, Is there a way or possibly a workaround to achieve this?

**Comment by HansMuller** [comment] 2018-05-14 16:40
Wow, this issue has been around for longer than a year and [BottomAppBar](https://material.io/design/components/app-bars-bottom.html) has a critical dependency on BottomSheet.  I'll put this lacuna on our list of tasks for this summer.

**Comment by sir-boformer** [comment] 2018-07-17 13:54
I really hope that this will be implemented. without it, bottom sheets are quite useless, especially in landscape mode.

Here is a working link to the material spec: https://material.io/design/components/sheets-bottom.html#behavior

This video shows the behavior: https://material.io/design/assets/1mYYvVz_dCIx0bRyY_VV4hOs9709f1ESb/modal-behavior-dismissal-close.mp4

**Comment by dnfield** [comment] 2018-09-04 18:37
I'll take a look at this.

**Comment by ThinkDigitalRepair** [comment] 2018-09-26 01:34
Just showing my support for the need for this issue to be resolved. Looking for something like the Google voice contact section. In this photo, it's nearly expanded to the top and the icon is moving to the side.
![screenshot_20180925-170425_google play services](https://user-images.githubusercontent.com/23037821/46052074-94267600-c0f1-11e8-892f-8deed51520dd.jpg)
![screenshot_20180925-170434_google play services](https://user-images.githubusercontent.com/23037821/46052082-9e487480-c0f1-11e8-9cf7-d11ed872220b.jpg)

**Comment by dnfield** [comment] 2018-09-27 16:03
I have been working on this and making some progress, but it still needs some work.  The linked PR is open and anyone is welcome to provide some feedback on the API/behaviors!

**Comment by ThinkDigitalRepair** [comment] 2018-09-27 16:07
@dnfield how do we review these as beta/alpha testing end users not familiar with the internal mechanics of testing PRs?

**Comment by dnfield** [comment] 2018-09-27 16:11
You could try to pull it down locally, but I believe there are aspects of it that might be broken right now.  At this point, I'm thinking more in terms of how the API works and what the code is doing.  But you're welcome to clone my branch locally and run it.

**Comment by ThinkDigitalRepair** [comment] 2018-09-27 16:13
Nobody like to cut a good edge more than me, but that's a little too cutting edge for me 😄

**Comment by vmihalachi** [comment] 2018-11-15 19:57
This tweet made me think it was already possible to achieve this result 
https://twitter.com/flutterio/status/1063129504053321728?s=21

**Comment by ricnaaru** [comment] 2018-12-17 05:10
I created this workaround, but maybe it's not that smooth, but I think it's worth it

https://pub.dartlang.org/packages/scrollable_bottom_sheet

**Comment by ThinkDigitalRepair** [comment] 2018-12-17 05:19
Hey, thanks. I'll check this out when I get a chance!

**Comment by FrantisekGazo** [comment] 2019-01-08 21:12
any updates on this issue?

**Comment by dnfield** [comment] 2019-01-23 06:55
Sorry for the delay - I'm back to working on this again.  See https://github.com/flutter/flutter/pull/21896

**Comment by leen-nobbas** [comment] 2019-01-28 17:59
When can we except a proper scrolling `BottomSheet` as there is only half baked bottom sheet in the release version!

**Comment by ThinkDigitalRepair** [comment] 2019-01-28 18:13
Hey hey, them is fighting words... They do a good job. It was.... A
"starter" bottom sheet :D

**Comment by leen-nobbas** [comment] 2019-01-28 18:16
@ThinkDigitalRepair no fight, just eagerly waiting!

**Comment by Zazo032** [comment] 2019-03-04 10:15
Any updates on this?

**Comment by dnfield** [comment] 2019-03-06 00:23
The PR that fixes this is currently in review.

**Comment by khalithartmann** [comment] 2019-03-06 17:48
any updates on this ?

**Comment by dnfield** [comment] 2019-03-26 23:35
Latest update - I'm going to refactor part of the existing PR into a smaller more generic widget that will then be re-integrated into that PR.

**Comment by tossaro** [comment] 2019-04-06 12:16
this is cool https://github.com/tossaro/bottom_sheet_stateful

**Comment by ride4sun** [comment] 2019-04-24 23:52
2 years later and still counting ...  
Any new ETA from this. Was just running into this.

**Comment by dnfield** [comment] 2019-04-25 00:20
It's really really close! :)  The PR that fixes this is going through a final review right now.

**Closed** 2019-04-26 21:12 UTC
Labels: f: material design, framework, severe: new feature

**Comment by sir-boformer** [comment] 2019-04-26 21:15
Nice one, thanks for getting this done!

**Comment by ride4sun** [comment] 2019-04-26 23:26
@dnfield is this on Master?

**Comment by dnfield** [comment] 2019-04-26 23:36
Yup!

**Comment by ThinkDigitalRepair** [comment] 2019-04-26 23:42
Excellent. Does it support automatically growing according to its child's
height?

**Comment by racknoris** [comment] 2019-04-27 08:14
Anyone used it and could please upload a gif?

**Comment by MarkOSullivan94** [comment] 2019-04-27 12:21
Gif preview would be perfect

**Comment by mrmko** [comment] 2019-04-27 18:29
Works nicely. One issue I'm encountering someone else has mentioned: 
[https://github.com/flutter/flutter/pull/30058#issuecomment-483299346](url)

> "Looks like there is a slight problem.
If maxChildSize is set to 1.0 and actual fractional value of the parent is less than 1.0 (child can't fill parent completly), then once DraggableScrollableSheet reaches its max it won't scroll back down."

**Comment by dnfield** [comment] 2019-04-27 20:22
@mrmko sorry I missed that.  Can you open a new issue with a reproduction of the issue and tag me?

**Comment by mrmko** [comment] 2019-04-27 21:33
@dnfield Cheers, All done!

#31739

**Comment by ride4sun** [comment] 2019-04-29 23:25
Is there a description of what kind of new behavior we should expect @mrmko. It looks like the bottom sheet is still using half of the screen.

**Comment by perez-danilo** [comment] 2019-05-13 12:40
> Is there a description of what kind of new behavior we should expect @mrmko. It looks like the bottom sheet is still using half of the screen.

Here too

**Comment by dnfield** [comment] 2019-05-13 16:54
@ride4sun and @perez-danilo - if you're having an issue with this can you open a new ticket?  Feel free to tag me.  

Right now you should be able to make a scrolling sheet work, and it should not get locked into place.  Please provide the expected behavior you're not seeing and a reproduction in the bug you file and we can look into it.

**Comment by ldelafuente** [comment] 2019-05-14 11:26
Is this still available only on Master or is already available on the last stable release?

**Comment by ldelafuente** [comment] 2019-05-14 11:26
@dnfield Is this still available only on Master or is already available on the last stable release?

**Comment by dnfield** [comment] 2019-05-14 13:44
Only part of it made it to stable.  The next dev release will have the rest.

**Comment by HoneyBadger999** [comment] 2019-05-17 10:54
is there any example or description on how to use it actually?
i'm returning it with showBottomSheet function, the DraggableScrollableSheet works well on top of bottom sheet as expected but doesnt affect the bottom sheet?
i mean shouldnt it scroll the bottomSheet up and down too? or do we have to use it independently, how?

my code:

```
_scaffoldKey.currentState.showBottomSheet(
      (context){

return DraggableScrollableSheet(

             initialChildSize: 0.5,
                        maxChildSize: 1,
                        minChildSize: 0.25,
                        builder:
                            (BuildContext context, ScrollController scrollController) {
                          return ListView.builder(
                                  controller: scrollController,
                                  itemCount: 25,
                                  padding: EdgeInsets.all(0.0),
                                  itemBuilder: (BuildContext context, int index) {
                                    return ListTile(title: Text('Item $index'));
                                  },
                          );
    
                            });

});
```

**Comment by ThinkDigitalRepair** [comment] 2019-05-24 17:00
It would be nice to see this make it into the Flutter Gallery as well.

**Comment by ThinkDigitalRepair** [comment] 2019-05-24 17:01
@dnfield so it's in master? It slipped in quietly. I'll try to figure out how to use it.

**Comment by ThinkDigitalRepair** [comment] 2019-05-24 22:41
Yeah, It doesn't seem to be any different from the standard BottomSheet for me either.

**Comment by Scopewriter** [comment] 2019-10-02 06:58
Setting the property isScrollControlled = true, makes the bottom sheet expand above the half of the screen. The below example takes up the whole screen:

`await showModalBottomSheet<void>(
        context: context,
        builder: (BuildContext context) {
          return Container(height: double.infinity, width: double.infinity, color: Colors.red,);
        },
        isScrollControlled: true,
        backgroundColor: Colors.transparent);`

**Comment by ductranit** [comment] 2019-12-04 10:34
> Setting the property `isScrollControlled = true`, makes the bottom sheet expand above the half of the screen. The below example takes up the whole screen:
> 
> `await showModalBottomSheet<void>( context: context, builder: (BuildContext context) { return Container(height: double.infinity, width: double.infinity, color: Colors.red,); }, isScrollControlled: true, backgroundColor: Colors.transparent);`

Setting `isScrollControlled = true` can make the bottom sheet takes the whole screen, but it doesn't allow to scroll content inside the bottom sheet like Webview, Listview, NestedScrollView, CustomScrollView
Is there any idea to resolve this?

**Comment by ride4sun** [comment] 2019-12-05 19:32
@dnfield  Its kind of weird that you can not provide a link to proper documentation here. I just gave up on it and used something else. I would guess when adding new feature documentation should be done at the same time. Instead we are just guessing. Not good for the acceptance of flutter and the process.
Just my 2 Cents.

**Comment by dnfield** [comment] 2019-12-05 20:11
The documentation is at https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html

If you feel like it's deficient in some way we can certainly update it :)

**Comment by dnfield** [comment] 2019-12-05 20:12
We also have https://api.flutter.dev/flutter/material/showModalBottomSheet.html e.g. that explains `isScrollControlled`.
