### ISSUE TITLE
Flutter app cannot be scrolled with TeamViewer

### ISSUE THREAD

**Issue by lazarvgd** [flutter/flutter#98974] opened 2022-02-23 12:13 UTC
Few months ago I updated my flutter version to 2.5.3 and recently I noticed that I cannot scroll the app on a remote device using TeamViewer, but I can click it using TeamViewer, the app reacts to clicks, but scrolling is not possible, but I can scroll it on the device, without any issues.
The console log that I am getting while scrolling in TeamViewer is :

```
I/ViewRootImpl@ef07da6[MainActivity](10095): ViewPostIme pointer 0
I/ViewRootImpl@ef07da6[MainActivity](10095): ViewPostIme pointer 1

```
Can you please help me to solve this issue? Please let me know if any additional information is required.

My current flutter doctor:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/svarog/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/svarog/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/svarog/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/svarog/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • SM G970F (mobile)                     • RF8M728WTMP   • android-arm64  • Android 12 (API 31)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-02-25 06:34
Hi @lazarvgd, Thanks for filing the issue. Is this issue in a flutter web or desktop app? if so this is an intended behavior scrolling is disabled by default on web and Desktop, since this change https://github.com/flutter/flutter/pull/81569 to mimic the native behaviour. please see the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) for more details.

**Comment by lazarvgd** [comment] 2022-02-25 07:10
@maheshmnj  Thanks for the response, it is a mobile app that runs on android devices. I tested this with multiple devices Samsung s10e, Samsung A50, Xiaomi note 10 pro.

Please let me know if you need any additional information.

Thanks

**Comment by blackbusters** [comment] 2022-02-25 07:24
I have the same issues as well.

I'm developing android app and install Teamviewer Quick Support on device, then I remoted it using PC or another phone.

When testing, other apps and home OS (including settings panel) can scroll, but only on my apps it can't scroll at all (I've tested with my 2 different apps built with flutter).

My flutter doctor :

`[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1466], locale en-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability`

**Comment by blackbusters** [comment] 2022-02-25 07:49
As pointed out by @maheshmnj before, it becomes issue started with flutter 2.5 because of changing mouse scroll behaviour and I found a solution here :
https://stackoverflow.com/questions/69232764/flutter-web-cannot-scroll-with-mouse-down-drag-flutter-2-5

The last bottom solution works good for me, basically we just need to add drag devices with scroll behaviour, and that can be achieved in main.dart :

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scrollBehavior: MaterialScrollBehavior().copyWith(
        dragDevices: {PointerDeviceKind.mouse, PointerDeviceKind.touch, PointerDeviceKind.stylus, PointerDeviceKind.unknown},
      ),
      ...


```

Hope it helps.

**Comment by maheshmnj** [comment] 2022-02-25 09:10
Closing as solved, In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-25 09:10 UTC
Labels: in triage
