### ISSUE TITLE
Color table filter support in canvas

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#54788] opened 2020-04-14 22:17 UTC
Long story, only partly a feature request. I'd like to get some feedback from somebody with actual knowledge. :-)

Support for color table filters (1D transfer functions for RGB channels and even 3D) was dropped from Skia about two years ago. I complained back then but Skia's engineers were competely uninterested and unimpressed, they claimed nobody used it, they didn't want to support it any more, period. Flutter wasn't a thing back then, otherwise it probably would have been a strong argument. So, as Flutter was based on a later Skia version, it didn't have that from the beginning.

Sadly, this omission means that a whole lot of color/image manipulations are simply not possible now. We have color matrix filters but nothing else. No arbitrary gamma (canned sRGB is present but that's practically nothing), no way to make the equivalent of curves of photo editing programs (a multitude of image filters rely on these), no way to provide reasonable contrast/brightness manipulation, no way to use Photoshop-style gradient maps, no possibility to implement things like SVG's `feComponentTransfer`.

It can be worked around with a large amount of work (I implemented my own in OpenGL/WebGL) but that doesn't integrate with the canvas and requires async calls to a platform channel, which might be prohibitively slow and not supported inside a `CustomPainter`, for instance. What's even more unfortunate, the original sources removed were rather small and simple, the operations required very simple and straightforward GLSL/SkSL support, so I don't think anything was really gained by their removal in the first place.

Is there any chance to have this back?

**Comment by deakjahn** [comment] 2020-04-15 10:21
Come to think of it, about the same applies to image filters. Skia has the support for convolution filters and all we get is a canned blur. There is no possibility of any displacment filter, sharpen, various distortions, anything.

To put it into a diferent perspective, mobile development with Xamarin and SkiaSharp offers all these as trivial operations. A simple example:

    private void Unsharpen(SKCanvas canvas, SKBitmap bitmap, float gain) {
      float[] UnsharpKernel = {
          -0.00391f, -0.01563f, -0.02344f, -0.01563f, -0.00391f,
          -0.01563f, -0.06250f, -0.09375f, -0.06250f, -0.01563f,
          -0.02344f, -0.09375f,  1.85980f, -0.09375f, -0.02344f,
          -0.01563f, -0.06250f, -0.09375f, -0.06250f, -0.01563f,
          -0.00391f, -0.01563f, -0.02344f, -0.01563f, -0.00391f
        };

      using (var paint = new SKPaint {
        ImageFilter = SKImageFilter.CreateMatrixConvolution(new SKSizeI(5, 5), UnsharpKernel, gain, 0, SKPointI.Empty, SKMatrixConvolutionTileMode.Clamp, true),
      })
        canvas.DrawBitmap(bitmap, 0, 0, paint);
    }

And we're stuck without them. Sad, if you ask me, very sad...

**Comment by pedromassangocode** [comment] 2020-11-26 10:37
Hi @deakjahn 
I'm not sure if I understood this issue right. can you elaborate in short, what this issue is about?
Thank you

**Comment by deakjahn** [comment] 2020-11-26 11:25
Support for some features was removed from Skia years ago that they labeled as not required (sadly, they based their decision on **their** use of Skia, or those packages they saw the source code from). Back in those days, Skia was mostly used internally, to power Chrome and I don't know what else inside Google. Third parties were not really accounted for, much less those third parties where Skia people didn't even know what was actually required and used by developers. There was one such non-transparent third party, Xamarin with its (contributed but endorsed) SkiaSharp support but, for obvious reasons, Skia engineers couldn't care less. SkiaSharp simply removed those features from their wrapper implementation one by one, too, not being able to do anything else.

Flutter was not a thing back then, so I couldn't argue that "look, there is a whole world of people out there that might need some of these features and you can't really judge whether they will need it or not, so please, don't cripple existing functionality".

So, unfortunately, I'm afraid those things are gone forever now. As I mentioned in the OP, it can be worked around but it's not a workaround, it's creating your complete parallel implementation. Instead of a single class in Skia, I had to write my own OpenGL/WebGL based picture manipulation package to rely on. My OP was more like a plea to someone who is inside Flutter to see if there is any chance, ever, to incorporate things that are left out from Skia, maybe to put it back for Flutter's own use somehow. But I don't hold my breath, of course. Still, this means that Flutter, which itself might have different requirements than Skia in general, will be forever stuck with what Skia people decide to support.

The post was specifically about picture manipulation because practically everything that's needed for sophisticated picture tweaking (think Instagram-like filters or Photoshop-like modifications) are completely butchered, nothing left. I know that not every single developer out there needs those, for sure, but removing something that was already there and no, it didn't mean a very heavy bloat of megabytes carried along with little use, well, sad... :-))

**Comment by pedromassangocode** [comment] 2020-11-26 13:18
I'm not sure if this will be added back, so Cc @Hixie to better handle this issue.

**Comment by deakjahn** [comment] 2020-11-26 17:02
I'm not sure, either. :-)

**Comment by Hixie** [comment] 2020-11-26 20:22
Would arbitrary programmable shaders solve this use case for you?

**Comment by deakjahn** [comment] 2020-11-26 21:39
You mean writing my own GLSL code? Sure, that would be the best. That's actually what I do now, with the added complexity that I have to cater for my own GL environment on the platform side and send the bitmap over and back on the platform channel, which is far from optimal. If it could be incorporated into the usual Skia operations (CanvasKit strictly on the web, of course), that would be wonderful.

**Comment by jonahwilliams** [comment] 2024-08-13 03:40
We're not going to write this particular filter in the engine, but we will be exposing mechanisms to make writing these filters much simpler. Closing as dupe of https://github.com/flutter/flutter/issues/16296

**Closed by jonahwilliams** 2024-08-13 03:40 UTC
Labels: c: new feature, engine, d: stackoverflow, P3, team-engine, triaged-engine
