### ISSUE TITLE
Unhandled Exception on flutter web first run

### ISSUE THREAD

**Issue by HoseinHaqiqian** [flutter/flutter#37584] opened 2019-08-04 16:12 UTC
Unhandled exception:
    FormatException: Unexpected character (at character 1)
    Not Found
    ^

    #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)
    #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)
    #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)
    #3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)
    #4      JsonDecoder.convert  (dart:convert/json.dart:493:36)
    #5      JsonCodec.decode  (dart:convert/json.dart:151:41)
    #6      jsonDecode  (dart:convert/json.dart:94:10)
    #7      parse 
    package:source_maps/parser.dart:27
    #8      Sources.scriptParsed  (package:dwds/src/debugging/sources.dart:55:19)
     <asynchronous suspension>
    #9      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
    #10     CastStreamSubscription._onData  (dart:_internal/async_cast.dart:81:11)
    #11     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
    #12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
    #13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)
    #14     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:68:11)
    #15     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)
    #16     WipDomain.eventStream.<anonymous closure>.<anonymous closure>  
    (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
    #17     _HandlerEventSink.add  (dart:async/stream_transformers.dart:228:7)
    #18     _SinkTransformerStreamSubscription._handleData  
    (dart:async/stream_transformers.dart:120:24)
    #19     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
    #20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
    #21     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
    #22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
    #23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
    #24     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
    #25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
    #26     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)
    #27     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by blasten** [comment] 2019-08-06 17:59
cc @jonahwilliams

**Comment by jonahwilliams** [comment] 2019-08-06 18:03
Issues is tracked https://github.com/dart-lang/webdev/issues/514

**Comment by jonahwilliams** [comment] 2019-08-13 00:48
Looks like this was fixed in https://github.com/dart-lang/webdev/issues/514. @jakemac53 could you do a release of dwds soon so we can pick it up?

**Comment by jakemac53** [comment] 2019-08-13 14:51
We are almost ready for a release, waiting for a resolution on https://github.com/flutter/devtools/issues/918

**Comment by vsmenon** [comment] 2019-08-15 21:10
@jonahwilliams - the fixed is landed, but we need a new dwds rolled in?

**Comment by jonahwilliams** [comment] 2019-08-15 21:17
Yes, we're not able to roll in dwds because the devtools dependency is tightly constrained by mockito: https://github.com/flutter/devtools/pull/923

**Comment by vsmenon** [comment] 2019-08-22 20:47
@jonahwilliams - the devtools issue appears closed.  Anything more to do here?

**Comment by jonahwilliams** [comment] 2019-08-22 22:29
We need a new release of devtools/dwds

**Comment by vsmenon** [comment] 2019-08-22 22:37
@jacob314 @grouma - can we do another release of the above?

**Comment by grouma** [comment] 2019-08-22 22:50
I think we are blocked by this if I'm not mistaken: https://github.com/dart-lang/webdev/pull/600

@devoncarew is looking to do a new release then we can publish a new version of dwds.

**Comment by jakemac53** [comment] 2019-09-04 20:02
@grouma do you know the status here, is this confirmed fixed and released?

**Comment by grouma** [comment] 2019-09-04 20:10
I did a publish of DWDS last week so this should be resolved.

**Comment by jakemac53** [comment] 2019-09-05 16:50
Ok, I am going to close this then as it should be resolved

**Closed by jakemac53** 2019-09-05 16:50 UTC
Labels: dependency: dart, ☸ platform-web
