### ISSUE TITLE
Critical: [Web Safari] (MacOS & iOS) won't render video player

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#116352] opened 2022-12-01 14:49 UTC
```
Flutter 3.3.9
video_player: 2.4.8
```

Currently we cannot release on Web because of this 1 bug.

When using the video player on Safari using the canvis-kit renderer it doesn't display while inside a Clip (ClipRR, ClipOval, etc).

There is a temporary solution mentioned here https://github.com/flutter/flutter/issues/80401

But looking at the DOM in canvis-kit there is no 'clip' or reference to clip path.

<img width="365" alt="Screenshot 2022-12-01 at 15 45 06" src="https://user-images.githubusercontent.com/6940726/205082287-d32ab7a8-cc12-44ae-97f4-6209445cfb61.png">

The JS solution is also noted here https://jsfiddle.net/yjbanov/nh9jzLba/42/

But how can we do this using canvis-kit?

Using the HTML renderer isn't an option as there are many bugs with it.

We can't ignore clip as that is an essential design in out app. 

<img width="613" alt="Screenshot 2022-12-01 at 15 47 49" src="https://user-images.githubusercontent.com/6940726/205082925-eed1964a-ec10-44b8-8375-e655066d8ea5.png">

I doubt it will be in the Flutter master until next Summer.

What is the solution?

**Comment by exaby73** [comment] 2022-12-02 08:14
Hello @ollydixon. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by ollydixon** [comment] 2022-12-02 09:26
@exaby73 

Testing on beta channel I can confirm that it works. 
When should we expect this in release? Since it's critical to many people.

--

There is a secondary bug where ClipRRect has no effect on all browsers but ClipOval does but I guess that can be another update. :-/

**Comment by ollydixon** [comment] 2022-12-02 09:27
Test code
```

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: _App(),
    ),
  );
}

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _BumbleBeeRemoteVideo(),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      videoPlayerOptions: VideoPlayerOptions(),
    );

    playThis();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 320,
      height: 200,
      color: Colors.green,
      child: AspectRatio(
        aspectRatio: _controller.value.aspectRatio,
        child: ClipRRect(
          borderRadius: BorderRadius.circular(8),
          child: VideoPlayer(_controller),
        ),
      ),
    );
  }

  Future<void> playThis() async {
    await _controller.setLooping(true);
    await _controller.setVolume(0.0);
    await _controller.initialize();
    _controller.play();
  }
```
}

**Comment by exaby73** [comment] 2022-12-02 10:39
You can check the [cherrypick process](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process) for this. Since this is fixed, I will close this issue as a duplicate of https://github.com/flutter/flutter/issues/80401. Thank you

**Closed by exaby73** 2022-12-02 10:39 UTC
Labels: in triage

**Comment by exaby73** [comment] 2022-12-02 10:48
I cannot be certain unfortunately. You can request a cherry-pick with the above link. There is a template you can fill, and it may be considered for the next hotfix.

**Comment by ollydixon** [comment] 2022-12-02 10:49
@exaby73 where is the template, perhaps I can nudge them!

**Comment by exaby73** [comment] 2022-12-02 13:29
You can find it [here](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process)

**Comment by exaby73** [comment] 2022-12-06 14:24
We'll have to wait for the team to look at it :) Thank you for the CP request
