### ISSUE TITLE
How can i stream my rtsp ip camera in my flutter app?

### ISSUE THREAD

**Issue by Asncodes-80** [flutter/flutter#72732] opened 2020-12-21 18:46 UTC
Hi friends, I’m developing our flutter app and we want to stream and show ip cameras with “rtsp” protocol on it, but I don’t know what is proper way to develop that. I have use vlc_player package in my app but is not very good and compatible with me, specially when i build apk and run it on Android device in section camera it crashed quickly! Vlc_player is not proper for our app. Plz help me about this problem.

**Comment by realrk69** [comment] 2020-12-21 18:55
Copy of https://github.com/flutter/flutter/issues/24960

flutter_vlc_player is pretty stable and works well. I would recommend posting an issue in their forum since this issue is related to the plugin or your implementation of it. Also, check out fijkplayer as recommended in the link above.

**Comment by Asncodes-80** [comment] 2020-12-21 20:07
> Copy of https://github.com/flutter/flutter/issues/24960
> 
> 
> 
> flutter_vlc_player is pretty stable and works well. I would recommend posting an issue in their forum since this issue is related to the plugin or your implementation of it. Also, check out _fijkplayer_ as recommended in the link above.


Thank you bro🙏
I will test Fijk plugin in my project, but still i have a lot of error with vlc_player plugin.

**Comment by darshankawar** [comment] 2020-12-22 07:05
Closing this as duplicate of https://github.com/flutter/flutter/issues/24960

**Closed by darshankawar** 2020-12-22 07:05 UTC
