### ISSUE TITLE
Make sure the framework correctly handles the view focus events. 

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#144235] opened 2024-02-27 16:58 UTC
## Use case

As part of https://github.com/flutter/flutter/issues/137443 a new API its being added to the engine to report back view focus changes. The framework should properly react to such events. 

## Proposal
For an example app please use this flutter web app: https://github.com/tugorez/flutter_focus. It has two "mains" one that doesn't use the events `main.dart` and one that kinda mimics what the framework should do with these events `main_with_focus_handlers.dart`. 

At least in web the behaviors I'd expect are:

### The app should not be focused by default
Today the material app assumes it has focus, hence starts reacting to keyboard events. This can be seen by starting the app and pressing `tab`. Flutter consumes the tab when it shouldn't as it is not the main but a guest app.  

### Pushing a new route should not result in that route gaining focus by default. 
When a new route is pushed flutter claims focus https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/navigator.dart#L239. Instead it should first verify if the view wrapping the app has view focus, if not it should not move the focus to the route. 

### Enabling semantics should not result in the app gaining focus
@yjbanov  to elaborate but when semantics is enabled it results in the app gaining focus. This should not be the case. Flutter should do nothing (focus wise) when semantics is enabled.

**Comment by ditman** [comment] 2024-03-18 23:02
There's a POC of this here:

* https://github.com/flutter/flutter/pull/143259

**Comment by ditman** [comment] 2024-07-11 21:33
Maybe duplicate of https://github.com/flutter/flutter/issues/151251 ?

**Closed** 2024-07-11 23:33 UTC
Labels: framework, f: focus, team-framework
