### ISSUE TITLE
CustomScrollView and SliverPersistentHeader Unexpected Behavior

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#72336] opened 2020-12-15 06:39 UTC
## Steps to Reproduce

<details> <summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MySliverDemo(),
    );
  }
}

class MySliverDemo extends StatefulWidget {
  MySliverDemo({Key key}) : super(key: key);

  @override
  _MySliverDemoState createState() => _MySliverDemoState();
}

class _MySliverDemoState extends State<MySliverDemo> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: CustomScrollView(
        primary: true,
        slivers: [
          SliverPersistentHeader(
            pinned: true,
            floating: false,
            delegate: _SliverAppBarDelegate(
              minHeight: kToolbarHeight,
              maxHeight: 200,
              child: Container(
                color: Colors.blue,
                child: FittedBox(
                  fit: BoxFit.cover,
                  child: ConstrainedBox(
                    constraints: BoxConstraints(
                      minHeight: kToolbarHeight,
                    ),
                    child: FlutterLogo(),
                  ),
                ),
              ),
            ),
          ),
          SliverToBoxAdapter(
            child: Column(
              children: List.generate(
                20,
                (index) => Container(
                  height: 100,
                  child: Text(
                    "Tile $index",
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _SliverAppBarDelegate extends SliverPersistentHeaderDelegate {
  const _SliverAppBarDelegate({
    @required this.minHeight,
    @required this.maxHeight,
    @required this.child,
  })  : assert(minHeight != null),
        assert(maxHeight != null),
        assert(child != null);

  final double minHeight;
  final double maxHeight;
  final Widget child;

  @override
  double get minExtent => minHeight;

  @override
  double get maxExtent => maxHeight;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return SizedBox.expand(child: child);
  }

  @override
  bool shouldRebuild(_SliverAppBarDelegate oldDelegate) {
    if (identical(oldDelegate, this)) return false;
    return minHeight != oldDelegate.minHeight ||
        maxHeight != oldDelegate.maxHeight ||
        child != oldDelegate.child;
  }
}
```
</details>

**Expected results:** 

The most recent `stable` release `1.22.5` has my expected behavior where the `child` in the `SliverPersistentHeader` is contained within the header.

<img height="720" src="https://user-images.githubusercontent.com/3614291/102179256-d5db9c80-3e74-11eb-83ab-f25b33ca9694.gif">

**Actual results:** 

With the most recent `dev` build `1.25.0-8.0.pre` and a few releases prior to that, this is how the exact same code behaves. I'd expect the old behavior.

<img height="720" src="https://user-images.githubusercontent.com/3614291/102179465-323ebc00-3e75-11eb-8983-111bc9761a6b.gif">

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

Old (Expected Behavior)
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at C:\Users\albie\Dev\flutter
    • Framework revision 7891006299 (4 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\albie\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.0)
    • VS Code at C:\Users\albie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0
```

New (Unexpected Behavior)
```
[√] Flutter (Channel master, 1.25.0-9.0.pre.41, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.25.0-9.0.pre.41 at C:\Users\albie\Dev\flutter
    • Framework revision d075b979f8 (3 days ago), 2020-12-11 15:02:33 -0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\albie\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.0)
    • VS Code at C:\Users\albie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0
```
</details>

**Comment by pedromassangocode** [comment] 2020-12-15 11:20
I was able to reproduce the issue on latest master channel. The same code works fine as said above.

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.57, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-9.0.pre.57 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision f37969638d (8 hours ago), 2020-12-14 22:18:03 -0500
    • Engine revision 1749dbcc1b
    • Dart version 2.12.0 (build 2.12.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

<details><summary>flutter doctor (stable)</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (5 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by HansMuller** [comment] 2020-12-15 19:57
CC @Piinks

**Comment by Piinks** [comment] 2020-12-22 20:11
Bisected to #66700 cc @liyuqian

**Comment by Piinks** [comment] 2020-12-22 20:19
It looks like this is intentional behavior.
Default clip behaviors were intentionally changed to `Clip.none` as part of a unification of clipping across Flutter.
See https://flutter.dev/go/clip-behavior for more information.

You can fix your code for the desired behavior by setting the `clipBehavior` of the `FittedBox`:
```dart
FittedBox(
  clipBehavior: Clip.hardEdge,
  ...,
),
```

I am going to close this since it is intentional, if you feel that there is something else here that needs attention, let us know, and we can re-open! :)

**Closed by Piinks** 2020-12-22 20:19 UTC
Labels: f: scrolling, found in release: 1.25, framework, has reproducible steps, passed first triage, severe: regression
