### ISSUE TITLE
ImagePicker.pickImage max size using long side and short side

### ISSUE THREAD

**Issue by thierrypin** [flutter/flutter#55907] opened 2020-04-28 22:05 UTC
Hello, I'm using the ImagePicker.pickImage method and noticed that there is no way to limit the image size while keeping its orientation.

[https://github.com/flutter/plugins/tree/master/packages/image_picker](https://github.com/flutter/plugins/tree/master/packages/image_picker))

Being more specific, if I want to limit the input images to fullHD, I should use `ImagePicker.pickImage(..., maxHeight: 1080.0, maxWidth: 1920.0)`. But if the user takes a photo with an upright phone (or just taking and image with portrait orientation), the height should be 1920 and the width, 1080. I noticed that when this happens, the plugging automatically rotates the image 90º. This would be OK if I had a way to know that it had been rotated.

I propose a way to pass the maximum size respecting the image's original orientation. Something like longSide and shortSide. When obtaining the image, the function should be able to detect the orientation and resize accordingly.

**Comment by pedromassangocode** [comment] 2021-02-12 13:28
Still a valid proposal since is was not implemented in `image_picker: ^0.6.7+22`.

**Comment by ydag** [comment] 2021-05-17 11:28
I think this issue is fixed with the following PRs. [#3835](https://github.com/flutter/plugins/pull/3835) and [#3873](https://github.com/flutter/plugins/pull/3873)

Please let me know if the problem still occurs.

**Comment by mvanbeusekom** [comment] 2021-05-17 11:32
Closing the issue as it should be solved by the pull requests mentioned in the previous comment. 

If the issue still persists please let us know and I would be happy to reopen it.

**Comment by ydag** [comment] 2021-05-17 11:40
I misunderstand the problem but it seems it is still a valid issue. I reproduced it with iPhone 6s iOS 14.2.

**Comment by ydag** [comment] 2021-05-17 12:18
> the plugging automatically rotates the image 90º

I realized that as I mentioned above the rotation problem is solved by these PRs. I just found a small mistake (which will be fixed with the latest PR that I will send) that happens when you use the camera.

But I am not sure what do you mean by "the plugging automatically rotates the image 90º"? Does this occur when you capture the photo? Or after click the `Use Photo` button? @thierrypin

**Comment by TahaTesser** [comment] 2021-06-11 12:20
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-06-11 12:20 UTC
Labels: p: first party, p: image_picker, passed first triage, plugin, proposal, severe: new feature
