### ISSUE TITLE
Toggle Platform Mode gives red error screen in iOS emulator

### ISSUE THREAD

**Issue by Winghin2517** [flutter/flutter#16560] opened 2018-04-13 07:27 UTC
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

> I created a new flutter project. Then I went to the flutter inspector and clicked on "Toggle Platform Mode". 

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

![screen shot 2018-04-13 at 09 18 03](https://user-images.githubusercontent.com/7094734/38721747-9be5e024-3efb-11e8-9e30-1d6367c3cf3f.png)

## Logs

Run your application with `flutter run` and attach all the log output.

```
Launching lib/main.dart on iPhone X in debug mode...
Syncing files to device iPhone X...
Switched platform rendering to Android.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building SlideTransition(animation: AnimationController#cf714(⏭
1.000; paused; for MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20,
1.00)➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
_AnimatedState#162a1):
'package:flutter/src/rendering/object.dart': Failed assertion: line 1792 pos 12: '() {
final AbstractNode parent = this.parent;
if (parent is RenderObject)
return parent._needsCompositing;
return true;
}()': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

```

```
When the exception was thrown, this was the stack:
#2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart)
#3      RenderObject.attach (package:flutter/src/rendering/object.dart:1232:7)
#4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2588:11)
#5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:128:13)
#6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1077:11)
#7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2583:7)
#8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4652:18)
#9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4496:35)
#10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2957:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:18)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#63     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#70     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#71     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#72     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 3 frames from class _AssertionError and package dart:async)
```

```
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: Tried to paint a RenderObject before its compositing bits were updated.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3099 pos 12: '_ancestorChain.length == 1': is not true.
Switched platform rendering to iOS.
```

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-ZA)
    • Flutter version 0.2.8 at /Users/WingHinChan/Documents/FlutterSDK/flutter
    • Framework revision b397406561 (10 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/WingHinChan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2016.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices (1 available)
    • iPhone X • FE19AC9F-A4B4-4AE7-9D06-9DD21DDFEBAE • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by fangnow** [comment] 2018-09-27 01:40
I believe I am experiencing this as well. It is rendered my development completely to zero as I am trying to figure out the issue.

**Comment by fangnow** [comment] 2018-09-27 02:12
Here is the issue I've filed https://github.com/flutter/flutter/issues/22333

**Comment by zoechi** [comment] 2018-12-10 15:55
Duplicate of #24029 (has most activity and information)

**Closed by zoechi** 2018-12-10 15:55 UTC
Labels: framework, severe: crash, ⌺‬ platform-ios
