### ISSUE TITLE
TabBar will scroll more than one tab at a time with strong flings

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#9724] opened 2017-05-02 17:49 UTC
## Steps to Reproduce

* Run the flutter_gallery app
* Navigate to the "Buttons" demo
* Switch between tabs by flinging them with a high-velocity fling

## Expected behavior

You expect to only switch one tab at a time, no matter how hard you fling

## Actual behavior

A strong-enough fling will scroll more than one tab at a time.  See https://youtu.be/VPUzUzXUq3A for example

**Comment by tvolkert** [comment] 2017-05-02 17:50
@HansMuller

**Comment by tvolkert** [comment] 2017-05-02 21:02
Just tested on iOS, and this is Android-only

**Comment by Hixie** [comment] 2017-12-12 20:51
I just checked this and it still happens to some extent: the next page bounces into view briefly. We should fix this as part of our Material work in the coming months.

**Comment by csells** [comment] 2020-01-09 16:45
@tvolkert can you be more specific -- how "high" a "high velocity" are we talking about here? Is it scary high? Do you need a running start? : )

**Comment by tvolkert** [comment] 2020-01-10 05:11
No, it's just a quick flick.

**Comment by VladyslavBondarenko** [comment] 2020-03-27 16:16
Reproduced. Flutter master  v1.16.3-pre.56.
https://flutter.github.io/gallery/#/demo/tabs

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17024977/77776599-e6ce4e80-7056-11ea-9a01-cfed28511060.gif)

**Comment by VladyslavBondarenko** [comment] 2020-07-27 15:22
I can't reproduce it on Android 9 (API 28) device (tried with current master `1.21.0-6.0.pre.38`, beta `1.20.0-7.2.pre` and stable `1.17.1`).

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.38, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.38 at /Users/nevercode/dev/flutter
    • Framework revision 8e0eee9008 (5 hours ago), 2020-07-26 23:38:01 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

Closing as fixed. If you disagree, please write in comments and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-27 15:22 UTC
Labels: P4, f: material design, f: scrolling, framework, has reproducible steps, platform-android
