### ISSUE TITLE
maybe a bug, the console suggested to report this - 

### ISSUE THREAD

**Issue by amoyastudio** [flutter/flutter#131635] opened 2023-07-31 22:25 UTC
Card
```
ScheduleList.dart:332
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: _RenderInkFeatures#44371 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
box.dart:1
Failed assertion: line 1966 pos 12: 'hasSize'

The relevant error-causing widget was
Card
```

**Comment by thisisjaymehta** [comment] 2023-08-01 03:52
Please share minimal reproducible example.

**Comment by darshankawar** [comment] 2023-08-01 07:25
@amoyastudio 
Although the console log suggests to create a new bug, but apart from the log, we also need minimal reproducible code sample to properly evaluate and address the bug reported. Without it, we won't be able to make the issue actionable.
If you have concrete code sample and steps to replicate, use the new issue [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml), fill out requested details.


Closing for now due to lack of details.

**Closed by darshankawar** 2023-08-01 07:25 UTC
Labels: in triage
