### ISSUE TITLE
bin/tasks/commands_test.dart is flaky

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11502] opened 2017-08-03 14:22 UTC
The devicelab test bin/tasks/commands_test.dart is flaky. I had thought this was contention over a hard-coded service protocol port, but it's still failing after we switched to using any open port.

```
flutter drive --use-existing-app http://127.0.0.1:8100/ --keep-app-running --driver test_driver/commands_none_test.dart
drive:stdout: Using device Moto G 4.
drive:stdout: Will connect to already running application instance.
drive:stdout: 00:00 [32m+0[0m: (setUpAll)[0m
drive:stderr: [info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8100/
drive:stderr: [trace] FlutterDriver: Looking for the isolate
drive:stderr: [trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
drive:stderr: [info ] FlutterDriver: Connected to Flutter application.
drive:stdout: 00:00 [32m+0[0m: check that we are in normal mode[0m
drive:stdout: 00:00 [32m+0[0m[31m -1[0m: check that we are in normal mode [1m[31m[E][0m[0m
drive:stdout:   Expected: 'log: paint'
drive:stdout:     Actual: ''
drive:stdout:      Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: log: paint ...
drive:stdout:   
drive:stdout:   package:test                               expect
drive:stdout:   test_driver/commands_none_test.dart 20:5   main.
drive:stdout:   ===== asynchronous gap ===========================
drive:stdout:   dart:async                                 _Completer.completeError
drive:stdout:   test_driver/commands_none_test.dart 22:3   main.
drive:stdout:   ===== asynchronous gap ===========================
drive:stdout:   dart:async                                 _asyncThenWrapperHelper
drive:stdout:   test_driver/commands_none_test.dart 19:53  main.
```

**Comment by Hixie** [comment] 2017-08-03 18:54
Yeah, I keep meaning to check out the problem.

**Comment by Hixie** [comment] 2017-08-07 21:00
I see all kinds of failures in the logs.

**Comment by Hixie** [comment] 2017-08-07 23:30
I cannot repro this locally.

**Comment by Hixie** [comment] 2017-08-22 23:33
Reassigning to Carlo since he's been working on this. @B3rn475 feel free to unassign if you aren't working on it.

**Comment by B3rn475** [comment] 2017-08-23 02:24
It is confirmed that we are connecting to the wrong app during tests.
```
drive:stdout:   Expected: 'log: paint'
drive:stdout:     Actual: 'keyboard_resize'
drive:stdout:      Which: is different.
drive:stdout:             Expected: log: paint ...
drive:stdout:               Actual: keyboard_r ...
```
See https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci81MDY2NzUwMDYzOTQ0YTI3ZDFjZjdkMzNlNmI0YmEwZWU0ODg1MTMxDAsSBFRhc2sYgICAgICAyAsM

**Comment by B3rn475** [comment] 2017-08-23 15:47
It happens when the `commands_test` and `integration_ui` run on the same machine

**Closed** 2017-09-01 01:04 UTC
