### ISSUE TITLE
Crash issue with flutter_xmpp after release build in Android.

### ISSUE THREAD

**Issue by karthik9596** [flutter/flutter#58567] opened 2020-06-03 07:54 UTC
Hi.. i am using this library (flutter_xmpp: ^0.0.32) for chat server.but My app got crash after get the release build by using this command(flutter build apk --release) in Android.

when i am using this command (flutter build apk --no-shrink) in android.my app not getting any crashes.but its crash when i use (flutter build apk --release).

**Comment by iapicca** [comment] 2020-06-03 08:02
Hi @karthik9596 
From what I can see, the issue is related to a [3rd party plugin](pub.dev/packages/flutter_xmpp) rather than to Flutter itself. 
Please open the issue in the dedicated [repository](https://github.com/aldiferdiyan/flutter_xmpp/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-03 08:02 UTC
