### ISSUE TITLE
in flutter web, embed a table in singlechildscrollview or ListView, using mouse to drag will cause error.

### ISSUE THREAD

**Issue by zhushuihua** [flutter/flutter#77211] opened 2021-03-04 04:45 UTC
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
          child: Table(
        defaultColumnWidth: IntrinsicColumnWidth(),
        children: [
          for (var i = 0; i < 100; i++)
            TableRow(
              children: [
                Text(
                  '$i',
                  style: TextStyle(fontSize: 25),
                )
              ],
            )
        ],
      )),
    );
  }
}
```
</details>

the following is the error:
```console
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50475/dart_sdk.js:5334:11)
    at Object.assertFailed (http://localhost:50475/dart_sdk.js:5270:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50475/dart_sdk.js:165955:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50475/dart_sdk.js:165404:36)
    at http://localhost:50475/dart_sdk.js:165339:44
    at http://localhost:50475/dart_sdk.js:165308:16
    at http://localhost:50475/dart_sdk.js:165007:11
```

**Comment by zhushuihua** [comment] 2021-03-04 04:49
This is happening in beta version 1.26.x and flutter 2.0 stable.
But it is working properly with 1.25.0-8.3.pre

**Comment by pedromassangocode** [comment] 2021-03-04 08:19
Hi @zhushuihua 
I cannot reproduce this issue on latest master and stable channel.

![gif](https://user-images.githubusercontent.com/67424416/109932245-3cc95e80-7cca-11eb-9caf-81b60b32d1b3.gif)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.97, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-11.0.pre.97 at /Users/pedromassango/Code/flutter_master
    • Framework revision c14c8d8177 (86 minutes ago), 2021-03-03 21:40:34 -0800
    • Engine revision 72bbc5d92c
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 2.0.0 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 60bd88df91 (14 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by zhushuihua** [comment] 2021-03-04 08:32
Please use your left mouse to drag and swipe up and down.

**Comment by zhushuihua** [comment] 2021-03-04 08:44
Simply left-click the list and drag the list up and down several times, the error will appear in the console.

**Comment by kubatatami** [comment] 2021-03-04 12:40
I have same issue in two projects after update to flutter 2.0 stable. Dragging ListView is the easiest way to reproduce but it also happens randomly in many other situation like `FlatButton` clicks.
Tested in chrome and Safari on Big Sur.

**Comment by pedromassangocode** [comment] 2021-03-04 13:51
I still cannot reproduce this scrolling the list using left-click + dragging.

![gif](https://user-images.githubusercontent.com/67424416/109973679-022aea80-7cf9-11eb-9225-2ff028f02da7.gif)

**Comment by zhushuihua** [comment] 2021-03-04 14:29
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-SG)
    • Flutter version 2.0.0 at /Users/zhushuihua/flutter
    • Framework revision 60bd88df91 (21 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhushuihua/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Comment by zhushuihua** [comment] 2021-03-04 14:30
Could please click and drag it up and down more times.

**Comment by zhushuihua** [comment] 2021-03-04 14:32
Actually, I have even tried my second macbook. Initially, it seems to be ok but after a while the error came out...

**Comment by zhushuihua** [comment] 2021-03-04 15:17
https://user-images.githubusercontent.com/16815523/109985481-c0716280-7d3f-11eb-90d1-f1973381ef7e.mp4

**Comment by zhushuihua** [comment] 2021-03-04 16:33
Please understand that when I use my macbook pro 15 inch, it is very easy to show up. But for my macbook pro 13 inch, it is not so frequent, sometimes I need to try more time to get the error message, but surely, it will come up. Please also try more devices at your side to verify this issue.

**Comment by yjbanov** [comment] 2021-03-04 23:29
There are several issue pointing to the same apparent cause: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+PointerDataConverter+label%3Aplatform-web

**Comment by zhushuihua** [comment] 2021-03-05 01:06
It seems the problem persists in flutter version 2.01.

**Comment by zhushuihua** [comment] 2021-03-14 09:28
The problem is still there for version flutter 2.02.

**Comment by zhushuihua** [comment] 2021-03-17 09:40
it seems the dev version  2.1.0-12.1.pre doesn't have this issue. So far, everything is running fine.

**Comment by mdebbar** [comment] 2021-03-22 16:48
This is a duplicate of https://github.com/flutter/flutter/issues/75280. The fix will be included in the next hotfix release.

**Closed by mdebbar** 2021-03-22 16:48 UTC
Labels: assigned for triage, engine, f: gestures, passed first triage, platform-web, severe: crash
