### ISSUE TITLE
Cannot call write after a stream was destroyed Error

### ISSUE THREAD

**Issue by odleo** [flutter/flutter#43063] opened 2019-10-19 16:15 UTC
C:\Users\User>flutter doctor -v
'git rev-parse HEAD' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Checking Dart SDK version...
O termo 'Unblock-File' não é reconhecido como nome de cmdlet, função, arquivo d
e script ou programa operável. Verifique a grafia do nome ou, se um caminho tiv
er sido incluído, veja se o caminho está correto e tente novamente.
Em linha:1 caractere:13

translated:

> C: \ Users \ User> flutter doctor -v
> 'git rev-parse HEAD' is not recognized as an internal command
> or external, an operable program, or a batch file.
> Checking Dart SDK version ...
> The term 'Unblock-File' is not recognized as cmdlet name, function, d file.
> and script or operable program. Check the spelling of the name or, if a path has
> If you have been included, see if the path is correct and try again.
> In line: 1 character: 13

+ Unblock-File <<<<  -Path 'C:\src\flutter/bin/internal/update_dart_sdk.ps1'; &
 'C:\src\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nu
l' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Downloading android-arm-profile/windows-x64 tools...                5,5s
Downloading android-arm-release/windows-x64 tools...                4,2s
Downloading android-arm64-profile/windows-x64 tools...              6,2s
Downloading android-arm64-release/windows-x64 tools...              5,2s
Downloading android-x86 tools...                                   66,7s
Downloading android-x64 tools...                                   68,2s
Downloading android-arm tools...                                   32,1s
Downloading android-arm-profile tools...                           17,3s
Downloading android-arm-release tools...                           12,3s
Downloading android-arm64 tools...                                 34,1s
Downloading android-arm64-profile tools...                         20,0s
Downloading android-arm64-release tools...                         16,8s
Downloading package sky_engine...                                   3,9s
Downloading common tools...                                        43,0s
Downloading common tools...                                        42,9s
Downloading windows-x64 tools...                                  217,1s (!)
[ÔêÜ] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [vers├â┬úo
    6.1.7601], locale pt-BR)
    ÔÇó Flutter version 1.9.1+hotfix.5 at C:\src\flutter
    ÔÇó Framework revision 1aedbb1835 (2 days ago), 2019-10-17 08:37:27 -0700
    ÔÇó Engine revision b863200c37
    ÔÇó Dart version 2.4.0

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0.

**Comment by kunit1** [comment] 2019-10-19 17:54
The error message is telling you that flutter requires PowerShell 5.0 or newer. Did you make sure to update your PowerShell version?

**Comment by aatikakhan** [comment] 2019-10-19 20:22
No, it's working very well

**Comment by odleo** [comment] 2019-10-20 14:30
> No, it's working very well

![image](https://user-images.githubusercontent.com/44352026/67161025-fb325080-f32c-11e9-87ca-ccb47de22bff.png)

**Comment by odleo** [comment] 2019-10-20 14:35
> No, it's working very well

`[11:33:11] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at t.Analyzer.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:42295)
	at t.Analyzer.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:37584)
	at Promise (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:42103)
	at new Promise (<anonymous>)
	at t.Analyzer.sendRequest (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:41915)
	at t.Analyzer.editGetAssists (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:277620)
	at t.AssistCodeActionProvider.<anonymous> (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:371758)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:371297
	at new Promise (<anonymous>)
	at r (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:371042)
	at t.AssistCodeActionProvider.provideCodeActions (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:371599)
	at r.codeActionProviders.filter.map.r (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:414410)
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:414401)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:413854
	at new Promise (<anonymous>)
	at r (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.5.1\out\dist\extension.js:1:413599)
	at t.RankingCodeActionProvider.provideCode…
`

**Comment by iapicca** [comment] 2019-10-21 08:56
Hi @odleo 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Also would be helpful to know if the powershell  version you are using 
complies with the requirements (thanks @kunit1 for the suggestion)
Thank you

**Comment by odleo** [comment] 2019-10-21 11:15
> Hi @odleo
> can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Also would be helpful to know if the powershell version you are using
> complies with the requirements (thanks @kunit1 for the suggestion)
> Thank you

`C:\Users\User>flutter doctor -v
'git rev-parse HEAD' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nu
l' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.
` 

I'll try to update PowerShell.

**Comment by odleo** [comment] 2019-10-21 11:57
> Hi @odleo
> can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Also would be helpful to know if the powershell version you are using
> complies with the requirements (thanks @kunit1 for the suggestion)
> Thank you

I have update PowerShell, and the doctor -v still the same.

**Comment by iapicca** [comment] 2019-10-21 12:03
Hi again @odleo 
I can't see a readable `flutter doctor -v`
would you mind to post it again, 
for what I understand your issue itself
is running this command, am I correct?

**Comment by odleo** [comment] 2019-10-21 12:08
> Hi again @odleo
> I can't see a readable `flutter doctor -v`
> would you mind to post it again,
> for what I understand your issue itself
> is running this command, am I correct?

The result of `flutter doctor -v` is:

`'git rev-parse HEAD' is not recognized as an internal or external command.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nu
l' nÆo ‚ is not recognized as an internal or external command.`

**Comment by odleo** [comment] 2019-10-21 12:13
> Hi again @odleo
> I can't see a readable `flutter doctor -v`
> would you mind to post it again,
> for what I understand your issue itself
> is running this command, am I correct?

The console has a formatting issue, please wait a moment.

**Comment by odleo** [comment] 2019-10-21 12:17
> Hi again @odleo
> I can't see a readable `flutter doctor -v`
> would you mind to post it again,
> for what I understand your issue itself
> is running this command, am I correct?

`Flutter doctor -v`:

`C:\Users\User>flutter doctor -v
'git rev-parse HEAD' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nu
l' is not recognized as an internal or external command.
[ÔêÜ] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [vers├â┬úo
    6.1.7601], locale pt-BR)
    ÔÇó Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    ÔÇó Framework revision 20e59316b8 (3 months ago), 2019-07-18 20:04:33 -0700
    ÔÇó Engine revision fee001c93f
    ÔÇó Dart version 2.4.0

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0.
1)
    ÔÇó Android SDK at C:\Users\User\AppData\Local\Android\sdk
    ÔÇó Android NDK location not configured (optional; useful for native profili
ng
      support)
    ÔÇó Platform android-29, build-tools 29.0.1
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Android Studio (version 3.4)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin version 39.0.1
    ÔÇó Dart plugin version 183.6270
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    ÔÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
      2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    ÔÇó For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ÔÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    ÔÇó For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins`

**Comment by iapicca** [comment] 2019-10-21 12:20
Hi again @odleo 
I suspect that there might be something wrong with your flutter installation;
I also suspect that some kind of customization might have occurred in your terminal,
but if so it is something related to the terminal itself rather than flutter.

Could you please delete your current installation and follow this [link](https://flutter.dev/docs/get-started/install) for a fresh one?
Thank you

**Comment by odleo** [comment] 2019-10-21 13:43
> Hi again @odleo
> I suspect that there might be something wrong with your flutter installation;
> I also suspect that some kind of customization might have occurred in your terminal,
> but if so it is something related to the terminal itself rather than flutter.
> 
> Could you please delete your current installation and follow this [link](https://flutter.dev/docs/get-started/install) for a fresh one?
> Thank you

Hi, I'm updating Flutter, if the error still I reinstall,  since now thanks!

**Comment by iapicca** [comment] 2019-10-22 07:49
Hi again @odleo 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2019-10-22 07:49 UTC

**Comment by tounoussiKhalid** [comment] 2020-05-04 18:16
In my case, restarting VSCode and the problem is gone ..
