### ISSUE TITLE
Completer completed from ui.window.onBeginFrame not completing on iOS 

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7433] opened 2017-01-11 01:20 UTC
## Steps to Reproduce

Sync to 90d18fa.

Use the following program (yes, it happens on the third frame scheduled from within a `Timer`):

```dart
import 'dart:async';
import 'dart:ui' as ui;

Future<Null> main() async {
  Completer<Null> c;
  ui.window.onBeginFrame = (_) {
    print('>>> Frame fired!');
    c.complete();
  };

  c = new Completer<Null>();
  ui.window.scheduleFrame();
  await c.future;

  c = new Completer<Null>();
  ui.window.scheduleFrame();
  await c.future;

  c = new Completer<Null>();
  new Timer(new Duration(seconds: 1), () {
    ui.window.scheduleFrame();
  });
  await c.future;

  print('>>>>>>> Done <<<<<<<<');
}
```

You should expect ">>> Frame fired!" appear three times, followed by ">>>>>>> Done <<<<<<<<". On Android this works as expected. On iOS, however, you will not see the "Done" message.

### Android:

```
Observatory listening on http://127.0.0.1:53529/

The Observatory debugger and profiler is available at: http://127.0.0.1:53529/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
I/flutter (  926): >>> Frame fired!
I/flutter (  926): >>> Frame fired!
I/flutter (  926): >>> Frame fired!
I/flutter (  926): >>>>>>> Done <<<<<<<<
```

Hurray! \o/

### iOS:

```
>>> Frame fired!
Observatory listening on http://127.0.0.1:53978/
subsystem: com.apple.UIKit, category: Touch, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
>>> Frame fired!

The Observatory debugger and profiler is available at: http://127.0.0.1:53978/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
>>> Frame fired!
```

No "Done" :( 

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/yjbanov/code/flutter/flutter
    • Framework revision 6333e6abee (4 hours ago), 2017-01-10 13:14:38
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/yjbanov/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • ANDROID_HOME = /Users/yjbanov/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[-] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • iPhone • 27012caf2fc18320e768018c805c56363b297202 • ios • iOS 10.0.1 (14A403)

Action item after this is fixed:

- [ ] Search for `"https://github.com/flutter/flutter/issues/7433"` in our codebase and remove the workarounds

/cc @johnmccutchan @chinmaygarde @Hixie

**Comment by Hixie** [comment] 2017-01-11 01:25
I wonder what happens if you just have the timer one, with a longer delay. i.e. are the two earlier frames just needed to get us past some point where we're triggering frames from the engine?

**Comment by goderbauer** [comment] 2017-01-11 19:49
I am seeing the same issue while running a flutter_driver test in JIT mode in the iOS simulator. Even though the completer in `_waitForElement()` is marked as completed [1], the associated future never completes.

I am about to add a workaround for this by scheduling a Timer just before completing the completer. 

FYI, I don't see any issues related to this when running the same test in JIT on an Android emulator.

[1] https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension.dart#L171

**Comment by chinmaygarde** [comment] 2017-01-11 20:45
Update: Verified that the display link awaits are always being serviced in a timely manner on iOS. In the offending cases, the platform layer never gets the call to await on the link.

**Comment by eseidelGoogle** [comment] 2017-01-11 21:13
I see we're making a workaround.  Do we know where the root cause is now?  Is this believed to be a flutter bug?  a Dart VM bug?  An iOS bug?

**Comment by chinmaygarde** [comment] 2017-01-11 21:42
We have identified the issue. Will post a patch in a bit.

**Comment by yjbanov** [comment] 2017-01-11 22:30
I added an action item to the description of this issue to clean-up the workarounds.

**Comment by chinmaygarde** [comment] 2017-01-11 22:34
Patch posted.

**Comment by yjbanov** [comment] 2017-01-11 23:02
Thanks, @chinmaygarde ! Let's close when the fix is in the main repo and we have removed the workarounds.

**Closed** 2017-01-13 02:56 UTC
Labels: prod: engine, ⌺‬ platform-ios
