### ISSUE TITLE
[web][html] In some cases Tooltip does not correctly size to fit message

### ISSUE THREAD

**Issue by azbuky** [flutter/flutter#74810] opened 2021-01-27 13:50 UTC
## Steps to Reproduce

1. Create a new project
2. Add the following Tooltip:
```
            Tooltip(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(color: Colors.black),
              textStyle: TextStyle(color: Colors.red),
              message:
                  'Some text\t TEXT\nText\t\t\t TEXT | TEXT | TEXT | TEXT | TEXT | TEXT',
              child: Text('Some Text'),
            ),
```
3. Run `flutter run -d chrome --web-renderer html`
4. Hover over text to show tooltip

**Expected results:** 

![Screenshot from 2021-01-27 15-27-30](https://user-images.githubusercontent.com/567277/105998738-a34cd280-60b5-11eb-908f-23726c1db052.png)

**Actual results:** 

![Screenshot from 2021-01-27 15-26-34](https://user-images.githubusercontent.com/567277/105998796-acd63a80-60b5-11eb-98c6-15d1ea515087.png)

Works as expected when stating with `flutter run -d chrome --web-renderer html --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_RICH_TEXT=false --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=false`

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-13.0.pre.194 at /home/azbuky/fvm/versions/master
    • Framework revision 71aec53acb (8 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/azbuky/Devel/Sdks/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/azbuky/Devel/Sdks/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /home/azbuky/Devel/Sdks/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/azbuky/Devel/Sdks/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Nexus 5X (mobile) • 026128a95bb02d50 • android-arm64  • Android 8.1.0 (API 27)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-01-27 15:38
Hi @azbuky 
This looks like a regression on the `master` channel, no issue on `dev `with `flutter run -d chrome --web-renderer html` 


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Tooltip(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(color: Colors.black),
          textStyle: TextStyle(color: Colors.red),
          message:
              'Some text\t TEXT\nText\t\t\t TEXT | TEXT | TEXT | TEXT | TEXT | TEXT',
          child: Text('Some Text'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/tahatesser/Code/flutter_master
    • Framework revision 71aec53acb (5 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thanks for filing the issue.

**Comment by azbuky** [comment] 2021-01-27 16:05
Hi @TahaTesser 

When testing on `dev` a part of text is missing.

Screenshot

![Screenshot from 2021-01-27 17-49-29](https://user-images.githubusercontent.com/567277/106016603-4b6b9700-60c8-11eb-8f05-2074b111821a.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-12.0.pre at /home/azbuky/fvm/versions/dev
    • Framework revision a706cd2112 (13 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/azbuky/Devel/Sdks/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/azbuky/Devel/Sdks/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /home/azbuky/Devel/Sdks/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/azbuky/Devel/Sdks/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Nexus 5X (mobile) • 026128a95bb02d50 • android-arm64  • Android 8.1.0 (API 27)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
</details>

**Comment by azbuky** [comment] 2021-01-31 12:43
Hi @mdebbar, thank you for looking into this issue. Converting tabs to spaces would invalidate the use of tabs in the first place. I was using them to align multiple two column lines in the Tooltip, which would be impossible with spaces unless a monospaced font is used. 

I guess matching behavior  with other platforms is more important thought, so I will just switch to a custom widget for my use case. Too bad the Tooltip widget doesn't accept a content widget instead of just a string as it is quite handy on web for displaying extra information.

**Comment by darshankawar** [comment] 2022-11-24 12:59
Verified this issue using latest versions and observed that the tooltip is now displayed correctly and as expected:

<img width="426" alt="Screenshot 2022-11-24 at 6 21 04 PM" src="https://user-images.githubusercontent.com/67046386/203790239-ce05b6ac-601f-4bd1-ac13-323439b208c9.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (25 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.6.0-7.0.pre.49, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.6.0-7.0.pre.49 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cb234730a1 (53 minutes ago), 2022-11-24 07:03:41 -0500
    • Engine revision c46300a661
    • Dart version 2.19.0 (build 2.19.0-428.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing as fixed.

**Closed by darshankawar** 2022-11-24 12:59 UTC
Labels: severe: regression, framework, engine, f: material design, platform-web, e: web_html, has reproducible steps, P4, found in release: 1.26
