### ISSUE TITLE
I want to create mix player with one audio and video file play together at same time

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [flutter/flutter#65994] opened 2020-09-17 04:29 UTC
I am trying to play video and audio at same time in flutter by using

**assets_audio_player: ^2.0.9+2 ==> For assets audio file playing
audioplayers: ^0.16.1 ==> for URL audio file playing
video_player: 0.10.12+2 ==> for URL Video file playing**

but when play audio and video in same time at same screen that time video was stack and video volume is stopped.

Thanks

**Comment by pedromassangocode** [comment] 2020-09-17 07:54
Hi @bhallaramdhatarwal 
As far as I know it is not possible to play video and audio at the same time. They both play sound so unless you are building for desktop (which does not seems the case here) you can't do that on mobile devices.

Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml` a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-17 07:54 UTC

**Comment by bhallaramdhatarwal** [comment] 2020-09-17 08:52
@pedromassangocode  Thanks.

I know. But i want to play video in mute volume and audio with sound and also, Is it possible to play audio in background like in android **doInBackground thread** and video in foreground or one play in UI thread and other in background thread.

**Comment by bhallaramdhatarwal** [comment] 2020-09-17 08:53
@pedromassangocode  Please reopen this issue.

**Comment by pedromassangocode** [comment] 2020-09-17 11:40
From my knowledge on native Android development and as far as I know, it is clearly not possible to play audio and video at the same time on Android (and maybe on iOS). Android has only one output for audio and it cannot be used by two sources at the same time.

This will still kept closed because you are using non Flutter plugins. If you disagree, please share a minimal reproducible complete code sample that does not uses third-party plugins and the steps to reproduce the issue and I will reopen it.

Thank you

**Comment by bhallaramdhatarwal** [comment] 2020-09-17 12:13
I am trying to play video and audio at same time in flutter by using

assets_audio_player: ^2.0.9+2 ==> For assets audio file playing
video_player: 0.10.12+2 ==> for URL Video file playing

but when play audio and video in same time at same screen that time video was stack and video volume is stopped. 
and if I used URL for audio & video. And audio player library for audio play that time smoothly play both audio and video

Thanks
