### ISSUE TITLE
Could not get cmap table size, while loading Iocons

### ISSUE THREAD

**Issue by Shoaibkhan786** [flutter/flutter#25319] opened 2018-12-13 10:19 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment] 2018-12-13 10:22
Duplicate of #23645

**Closed by zoechi** 2018-12-13 10:22 UTC

**Comment by Shoaibkhan786** [comment] 2018-12-13 10:37
> Duplicate of #23645

What was the solution because I did not get it?

**Comment by zoechi** [comment] 2018-12-13 10:43
It's just the same issue as already reported. 
#23645 is still open.

**Comment by Shoaibkhan786** [comment] 2018-12-14 05:17
Any idea why is it happening? I tried a lot to figure out the issues.

**Comment by ManuelWandeto** [comment] 2019-06-29 13:18
I was getting the same problem when doing;
Icon(
                  Icons.add_alarm,
                  color: Colors.green,
                ),

after running 'flutter clean' on the root of the project folder i don't get this issue anymore,

**Comment by rajyadavnp** [comment] 2019-11-14 04:01
Finally, I fixed my issue.
My asset names had spaces in their names. Renaming it by removing white spaces solved the problem

**Comment by kwent** [comment] 2020-02-05 02:42
If your app rely on the use of default material fonts and your commented out `uses-material-design` in your `pubspec.yaml` then the app will crash. Solution is to set `uses-material-design: true` in `pubspec.yaml`
