### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios'

### ISSUE THREAD

**Issue by mu7mmd** [flutter/flutter#148307] opened 2024-05-14 10:19 UTC
### Steps to reproduce

1. Add image_picker: ^1.1.1 to pubspec.yaml
2. flutter clean
3. flutter pub get
4. cd ios
5. rm -rf Pods Podfile.lock
6. pod cache clean --allpod
7. pod install
8. flutter run

### Expected results

Application build successfully and opening the app

### Actual results

Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios' /Users/user/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 12.7.4 21H1123 darwin-x64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] VS Code (version 1.86.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by mu7mmd** [comment] 2024-05-14 14:24
@darshankawar, Thank you for your response. When I downgraded to version 3.19.6, I encountered the same issue. However, when I further downgraded to version 3.19.5, the problem was resolved and it functioned correctly.

**Comment by mu7mmd** [comment] 2024-05-14 14:43
I apologize for any confusion. Just to clarify, the issue did not exist before upgrading, and the app was functioning properly on version 3.19.5. However, after upgrading to a newer version, the problem emerged, and even when downgrading back to 3.19.6 and 3.19.5, the issue persisted.

**Comment by loic-sharma** [comment] 2024-05-14 19:45
This might have been caused by the Swift Package Manager migration, /cc @vashworth

**Comment by loic-sharma** [comment] 2024-05-14 20:18
I wasn't able to reproduce this using Xcode 15.0 and newer. I suspect this only happens on Xcode 14.

Could you try the following workarounds:

1. Could you try pinning to `package:image_picker_ios` version 0.8.10 or older? This is before Swift Package Manager support was added
2. Could you try upgrading to Xcode 15.0 or newer?

Please let us know which of these options, if any, fix this issue. That'll help us understand this build error better.

**Comment by hectorvillag** [comment] 2024-05-15 01:10
I have the same problem after updating to flutter 3.22.0
<img width="1192" alt="image" src="https://github.com/flutter/flutter/assets/23240517/f8c9eb7c-9dbc-4728-8673-5ebcb7a105ad">

**Comment by rabinacharya11** [comment] 2024-05-15 15:21
I am facing the same issue after updating to flutter 3.22.0 

<img width="875" alt="Screen Shot 2024-05-15 at 21 06 39" src="https://github.com/flutter/flutter/assets/72679799/fcce4490-f7ee-47fd-89b0-c32fc7805650">

**Comment by loic-sharma** [comment] 2024-05-15 16:39
@hectorvillag @rabinacharya11 Could you try the workarounds listed above?

> 1. Could you try pinning to `package:image_picker_ios` version 0.8.10 or older? This is before Swift Package Manager support was added
> 2. Could you try upgrading to Xcode 15.0 or newer?
>
> Please let us know which of these options, if any, fix this issue. That'll help us understand this build error better.

**Comment by tienle219** [comment] 2024-05-15 17:44
> I am facing the same issue after updating to flutter 3.22.0
> 
> <img alt="Screen Shot 2024-05-15 at 21 06 39" width="875" src="https://private-user-images.githubusercontent.com/72679799/330864005-fcce4490-f7ee-47fd-89b0-c32fc7805650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3OTUzMDAsIm5iZiI6MTcxNTc5NTAwMCwicGF0aCI6Ii83MjY3OTc5OS8zMzA4NjQwMDUtZmNjZTQ0OTAtZjdlZS00N2ZkLTg5YjAtYzMyZmM3ODA1NjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE3NDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4N2FiMDcwY2E0NDQ2NjQ0Yjg0Y2RkMjFmNGQ3NGZiMDRiMDQ1MDMzODgyMmY3ZjMyZGIzZTM0ZGY0ZmM2Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHEdKRVKW1Y4HxfjBx9Adovk-jKUD-7r-6hblka8cPs">

I also have the same issue, do you have a solution?

**Comment by vashworth** [comment] 2024-05-15 19:18
Can anyone confirm if upgrading to Xcode 15 resolves the issue?

**Comment by hectorvillag** [comment] 2024-05-15 23:55
> Can anyone confirm if upgrading to Xcode 15 resolves the issue?
It seems to work, when I changed it to use xcode 15 in this task everything worked correctly
<img width="285" alt="image" src="https://github.com/flutter/flutter/assets/23240517/231fa324-4f25-48df-8a2b-ae15274a9888">

**Comment by rajatiota** [comment] 2024-05-16 10:17
> I am facing the same issue after updating to flutter 3.22.0
> 
> <img alt="Screen Shot 2024-05-15 at 21 06 39" width="875" src="https://private-user-images.githubusercontent.com/72679799/330864005-fcce4490-f7ee-47fd-89b0-c32fc7805650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTQ4OTYsIm5iZiI6MTcxNTg1NDU5NiwicGF0aCI6Ii83MjY3OTc5OS8zMzA4NjQwMDUtZmNjZTQ0OTAtZjdlZS00N2ZkLTg5YjAtYzMyZmM3ODA1NjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNTdhMzg1NjBiOTA1ZjM4NmU3NGEwZjJhNWUxZGE0MzY1MzY1ZDY1YWZiZDMzZThjMjRkNGYxMDhhZDhkZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MkjygUbNlqaRidIxccH_Tz5lUS5tJTu-AVL_7I4XptI">

i Am also getting same error after flutter pub upgrade
and try all available given solutions

**Comment by EmmyTechnology** [comment] 2024-05-16 12:10
Running Xcode build...
Xcode build done.                                           433.2s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios'
/Users/xxxx/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).


Has anyone resolve the similar problem here

**Comment by BurakAkten** [comment] 2024-05-16 12:19
Hi, 
I tried to create ipa by using Azure CI-CD but I got the same error. I tried both flutter version that you mentioned above (3.19.5 and 3.19.6) then same error I got.

Error: 
Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios'
/Users/runner/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7

**Comment by EmmyTechnology** [comment] 2024-05-16 13:08
> Hi, I tried to create ipa by using Azure CI-CD but I got the same error. I tried both flutter version that you mentioned above (3.19.5 and 3.19.6) then same error I got.
> 
> Error: Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios' /Users/runner/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7
> 
> I think it is caused by auto update for inner libraries.
> 
> If you add image_picker_ios-0.8.10+1 as dependency_overrides the problem will fixed.

How do you add that, because I am using flutter

**Comment by BurakAkten** [comment] 2024-05-16 13:24
> > Hi, I tried to create ipa by using Azure CI-CD but I got the same error. I tried both flutter version that you mentioned above (3.19.5 and 3.19.6) then same error I got.
> > Error: Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios' /Users/runner/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7
> > I think it is caused by auto update for inner libraries.
> > If you add image_picker_ios-0.8.10+1 as dependency_overrides the problem will fixed.
> 
> How do you add that, because I am using flutter

--------
In pubsec.yaml file add this;
`dependency_overrides:
        image_picker_ios: 0.8.10+1
`

**Comment by vashworth** [comment] 2024-05-16 19:16
Issue should be resolved with latest version of image_picker_ios (image_picker_ios-0.8.10+2). Try `flutter pub upgrade`

**Comment by EmmyTechnology** [comment] 2024-05-17 17:29
> > > Hi, I tried to create ipa by using Azure CI-CD but I got the same error. I tried both flutter version that you mentioned above (3.19.5 and 3.19.6) then same error I got.
> > > Error: Lexical or Preprocessor Issue (Xcode): Redefinition of module 'image_picker_ios' /Users/runner/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.11+1/ios/image_picker_ios/Sources/image_picker_ios/include/module.modulemap:0:7
> > > I think it is caused by auto update for inner libraries.
> > > If you add image_picker_ios-0.8.10+1 as dependency_overrides the problem will fixed.
> > 
> > 
> > How do you add that, because I am using flutter
> 
> In pubsec.yaml file add this; `dependency_overrides: image_picker_ios: 0.8.10+1 `

it works for me. Thanks

**Comment by loic-sharma** [comment] 2024-05-20 16:50
Please let us know if anyone can reproduce this issue after using `flutter pub upgrade`!

**Closed** 2024-06-10 17:08 UTC
Labels: platform-ios, waiting for customer response, p: image_picker, t: xcode, package, has reproducible steps, team-ios, found in release: 3.22
