### ISSUE TITLE
Dashed lines

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#9641] opened 2017-04-27 17:49 UTC
Implement common graphics options like fillpattern (I'd expect to see it as a property on Paint), or expose a method for user-defined Shaders to be used for adding complex stroking/filling operations.

Something like:

https://developer.apple.com/reference/coregraphics/cgcontext/1456334-setfillpattern

**Comment by sethladd** [comment] 2017-04-27 17:51
Can you give a few details on what the use case is? Thanks!

**Comment by gavindoughtie** [comment] 2017-04-27 17:54
https://docs.google.com/drawings/d/1GdnpumvTsGcTjRbh2tYf2LPFUFiklktUfggYsbEusuY/edit?usp=sharing

**Comment by sethladd** [comment] 2017-04-27 17:58
Nice! Bonus points for the diagrams. Very cool.

**Comment by Hixie** [comment] 2017-04-27 18:32
Is this just about dashed lines, or something else?

**Comment by gavindoughtie** [comment] 2017-04-29 00:04
Dashed lines is the current case (we want them for some Aplos charts), but imagine somebody who wants to implement drawings.google.com in Flutter.

**Comment by gavindoughtie** [comment] 2017-04-29 00:18
https://fiddle.skia.org/c/@skpaint_path_1d_path_effect

**Comment by Hixie** [comment] 2017-04-30 05:55
I recommend filing one issue per specific request. I'm focusing this one on dashed lines.

I don't think we should expose dedicated dashed lines APIs. It goes contrary to our design principles, which is to expose features that are fast and features which cannot be done any other way. Dashed lines are, as I understand it, quite slow, and can already be done (just do the dashing manually and draw the resulting path). I don't think we should expose a dedicated dashed line API because it will make people think that the feature is fast when it isn't.

**Comment by abarth** [comment] 2017-04-30 16:06
Let's double-check the performance to put some numbers behind fast and slow.  I think it would be useful to know the performance ratio between the following:

 1. Drawing a undashed line.
 2. Drawing a dashed line with a stroke style.
 3. Drawing a dashed line with individual drawRect calls.

**Comment by abarth** [comment] 2017-04-30 16:08
Specifically, your argument is the strongest when (2) and (3) are close to each other but far from (1).  If (1) and (2) are close but far from (3), then we might want to add support for (2).

**Comment by abarth** [comment] 2017-04-30 16:14
(Maybe (3) should be a Path)

**Comment by abarth** [comment] 2017-04-30 16:16
Looks like Skia already has a similar benchmark in DashBench.  We can ask them what it shows.

**Comment by abarth** [comment] 2017-04-30 16:23
Looks like they have a specialized GPU ops for dashed lines and circles (see GrDashOp), which makes use a the fragment shader.

**Comment by Hixie** [comment] 2017-04-30 17:07
I completely agree that if (1) and (2) are closer to each other than (2) and some variant of (3), then it makes sense to expose a dedicated API.

**Comment by Hixie** [comment] 2017-08-04 18:45
Dupe of 4858.

**Closed by Hixie** 2017-08-04 18:45 UTC
Labels: customer: mulligan (g3), new feature, prod: engine

**Comment by nsreenath** [comment] 2018-03-09 19:36
> Looks like Skia already has a similar benchmark in DashBench. We can ask them what it shows.

@abarth Did you get the benchmark result ?

**Comment by abarth** [comment] 2018-03-09 20:15
> Did you get the benchmark result ?

I did not.

**Comment by csga5000** [comment] 2018-05-10 20:18
> Looks like they have a specialized GPU ops for dashed lines and circles (see GrDashOp), which makes use a the fragment shader.

That sounds like it should be performant enough..

Does flutter provide access to that by any means?  I.E. using that hardware accelerated drawing of dashed lines.

Regardless, this is clearly a feature people are going to want, and that should be convenient to use. 
 Android, iOS, and web support dashed lines, when one of those developers comes to flutter and sees it isn't an option in the BorderStyles enum they go "Wow, flutter doesn't have dashed borders yet?  That's an indicator that it's missing some key features alternatives have".

As a note of the prevelance of dashed lines, even the editor I'm using to type right now is displaying a dashed line above "Attach files" and below the text editing area.

The example use case I have is that there a page that graphically displays data with colored boxes positioned based on certain values, the color indicates which "driver" pertains to the item being displayed by the box.  You can change drivers using a dropdown as you plan things out, but until they're saved the client wants to indicate that it's a "drafted" selection of driver by putting a dashed line around the box.  This should be as easy as adding a border to the box.

Am I correct in understanding I have to do something like use a canvas and paint a path?  That seems like a poor experience for flutter developers wanting to do something usually trivial.

**Comment by zhen1991** [comment] 2018-12-14 15:11
how do I create a dotter circle with custom painter in flutter. I use this code it gives me a normal circle but I want to have a dotted circle:!!
    canvas.DashedCircle(Offset(-A, LEN), 170, paint);
thnx :)

**Comment by zoechi** [comment] 2018-12-14 15:54
@zhen1991 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
