### ISSUE TITLE
Text glitch in the gallery app

### ISSUE THREAD

**Issue by Chris1234567899** [flutter/flutter#17507] opened 2018-05-11 12:52 UTC
I recently tested the Gallery App from the Play Store on my Lenovo Vibe K5 (Android 5.1.1) using the latest version in the Play Store (0.4.2). When I go to the animation screen and scroll a bit around, all text in the whole app becomes flickering triangles and stays this way. Clicking back or opening new pages several times can sometimes reinitialise the normal font, but it seems rather random. Here are some screens:
![screenshot_2018-05-10-20-15-54](https://user-images.githubusercontent.com/12623865/39925148-2a387256-54f0-11e8-8b67-0297a3154f10.png)
![screenshot_2018-05-10-20-16-04](https://user-images.githubusercontent.com/12623865/39925149-2a5a6172-54f0-11e8-84af-6c66ec272c26.png)
![screenshot_2018-05-10-20-15-43](https://user-images.githubusercontent.com/12623865/39925150-2a7c8b44-54f0-11e8-8185-cca6fa87dac2.png)
![screenshot_2018-05-10-20-15-49](https://user-images.githubusercontent.com/12623865/39925151-2a93267e-54f0-11e8-985c-d0b90dcb3e82.png)

**Comment by mahasadhu** [comment] 2018-05-13 07:50
I'm facing the same issue, Xiaomi Redmi 3 -  5.1.1 - MIUI 8
Sometimes even the app is closing after the white screen (not often though)

**Comment by riterrani** [comment] 2018-05-30 13:14
This is happening in my app too, this is not happening only in the gallery. Android 5.1.1 too

**Comment by HansMuller** [comment] 2018-05-30 13:22
@riterrani - could you let us know the specific Android devices you're seeing this on?

**Comment by riterrani** [comment] 2018-05-30 13:35
Lenovo A6020l37. In this case is also related to an animation I think, this happened playing with a SliverAppBar.

**Comment by HansMuller** [comment] 2018-05-30 13:41
@riterrani - The description of this bug implies that text rendering is failing everywhere. Is that true for your app, or I you only seeing the failure in a specific scenario? If it's the latter, and you can share the code that causes the problem, that would help.

**Comment by riterrani** [comment] 2018-05-30 16:29
I can't reproduce it now with my code. But this issue happened me with the "animations" example in the gallery.
I found another user reporting the same problem https://github.com/flutter/flutter/issues/17654
Another issue with animations and text glitching, same example https://github.com/flutter/flutter/issues/13817

And maybe this issue is related too https://github.com/flutter/flutter/issues/14459 ?

**Comment by zoechi** [comment] 2018-06-12 08:03
https://github.com/flutter/flutter/issues/18269#issuecomment-396495119 says it is fixed in master.
@Chris1234567899 can you confirm?
I haven't found a concrete PR that was supposed to fix that.

**Comment by Chris1234567899** [comment] 2018-06-12 15:35
@zoechi 
updated to v0.5.5-pre.6 and could not notice the issue anymore. Excellent.

**Comment by zoechi** [comment] 2018-06-12 16:30
Great, then I'll close.

**Closed by zoechi** 2018-06-12 16:30 UTC
Labels: a: typography, e: device-specific, team: gallery

**Comment by Pash237** [comment] 2019-03-18 22:13
Got an another glitch during startup.
Both text and image (at the top) are screwed up.
After the first widget rebuild it redraws fine (for example, if you type a character in TextField), but until then it looks like on screenshot:
![IMG_6735](https://user-images.githubusercontent.com/277626/54567116-d5824900-49e3-11e9-9cb2-00795092279d.PNG)

**Comment by bennibau** [comment] 2019-04-10 14:30
I have the same problem actually. I disappears as soon as I tap the screen and the list view scrolls.
![IMG_0946](https://user-images.githubusercontent.com/6883178/55887471-da36b900-5bad-11e9-96cf-56466deb8ecb.png)

**Comment by HansMuller** [comment] 2019-04-10 19:55
@Pash237, @bennibau - This issue was supposed to have been fixed some time ago (https://github.com/flutter/flutter/issues/17507#issuecomment-396634515). What version of flutter are you using? Can you include the output of `flutter doctor`?

**Comment by bennibau** [comment] 2019-04-11 06:31
It happens only on the device (iPhone X), not on the simulator:

**Flutter Doctor**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Flutter Version**
`flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (8 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)`
