### ISSUE TITLE
Validation not working for fields outside screen

### ISSUE THREAD

**Issue by dankop123** [flutter/flutter#17385] opened 2018-05-08 09:38 UTC
## Steps to Reproduce
1. Create a form with a list view and add a global key to a form
2. Add a TextFormField with a validator
3. Add some more widgets so the form is big enough that the TextFormField is outside screen when you scroll to bottom
4. Add a button and inside onPressed call _formKey.currentState.validate()
5. Run application
6. In TextFormField input text that shouldn't pass validation
7. Scroll to bottom and press the button
8. Scroll to the TextFormField
9. Validation message is not displayed and _formKey.currentState.validate() returns true

**Comment by Aman-US-Punjabi** [comment] 2018-05-10 09:53
Facing the same problem with some wired behavior, on submit button pressed:
1. Off screen fields go black because of null value. and validation method get skip and submit values without validating these fields.
2. Sometime, randomly few fields go blank and like in  step 1 these fields do not go throw validation.

This is happening only if form goes off screen in ListView

**Comment by Aman-US-Punjabi** [comment] 2018-05-10 23:30
Able to find a temporary solution for this problem:

By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView in side the form.

**Comment by zoechi** [comment] 2018-07-27 09:32
Do https://docs.flutter.io/flutter/widgets/PageStorage-class.html or https://docs.flutter.io/flutter/widgets/AutomaticKeepAliveClientMixin-class.html make this work?

**Comment by krngd2** [comment] 2019-01-03 07:13
> Able to find a temporary solution for this problem:
> 
> By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView in side the form.

This solved the issue but flutter need to resolve it. I did not understand why its not working until i saw this thread.

**Comment by Gailbear** [comment] 2019-05-02 18:00
Can confirm this is still happening.

**Comment by PhamTruongHung** [comment] 2019-09-10 10:48
> Able to find a temporary solution for this problem:
> 
> By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView inside the form.

Thank you, It's work.

**Comment by OoiBP** [comment] 2020-03-19 14:34
> Able to find a temporary solution for this problem:
> 
> By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView in side the form.

It works, thanks a lot

**Comment by justinmc** [comment] 2020-03-23 16:58
@goderbauer Do you know if this is a bug or is it expected based on some optimization that ListView is doing?

Here is a reproduction on dartpad: https://dartpad.dartlang.org/9f69b296ea0a2ca5818422a7f64f3059

<img width="200" src="https://user-images.githubusercontent.com/389558/77341920-a7b59b80-6cec-11ea-9b3f-9974ce20dc32.gif" />

**Comment by goderbauer** [comment] 2020-03-23 17:38
> is it expected based on some optimization that ListView is doing

Yes and No. ListView disposes widgets that are not visible for performance reasons. However, widgets can request to be kept alive even if they are not visible and I would have expected the textfield to keep itself alive.

Looks like we are only keeping it alive while it has focus: 

https://github.com/flutter/flutter/blob/58cad787d89cc12e72f1f0ec3f1df6a9796ef029/packages/flutter/lib/src/widgets/editable_text.dart#L1125

I bet, if you change that line to always return true this problem would go away. That's probably not a proper fix for this bug, but a starting point to confirm that not keeping it alive is the problem.

**Comment by justinmc** [comment] 2020-03-23 23:47
Yes, I set that line to true and it fixed the problem!  Thanks for the pointer.

I'll take a stab at a more nuanced solution and tag you for review.

For anyone with this problem, another thing to note is that this problem will go away if you provide a TextEditingController to the field.

**Comment by justinmc** [comment] 2020-03-24 22:44
I made an attempt at fixing this in https://github.com/flutter/flutter/pull/53137#issuecomment-603349723, but it seems that the best solution here is just to use a controller if you are in this situation.  We don't want to keep the memory around for all TextFields that have ever been changed if it won't matter to the developer.

**Closed by justinmc** 2020-03-24 22:44 UTC
Labels: a: text input, f: scrolling, framework

**Comment by FrankDupree** [comment] 2020-07-31 14:02
Experienced the same thing, didn't even know this was the problem, until i saw this title show up on google then it dawned on me that yeah, its only the fields that are visible that actually run.

**Comment by Alexddsilva** [comment] 2020-07-31 15:16
I'm still facing this problem ;(

**Comment by FrankDupree** [comment] 2020-07-31 15:26
> > Able to find a temporary solution for this problem:
> > By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView inside the form.
> 
> Thank you, It's work.

@Alexddsilva  try this, it worked for me

**Comment by Alexddsilva** [comment] 2020-07-31 15:54
> > > Able to find a temporary solution for this problem:
> > > By wrapping up the form in SingleChildScrollView and using Column Widget at the place of ListView inside the form.
> > 
> > 
> > Thank you, It's work.
> 
> @Alexddsilva try this, it worked for me

@FrankDupree  thanks,  this is temporaly solving the problem, i hope they fix ListView.

**Comment by Sam-Guru-In-Training** [comment] 2021-03-18 13:59
Still an issue, solution worked for me too.  Not top of Google though!

**Comment by DanilYusupov** [comment] 2021-03-23 15:12
As @justinmc already mentioned, You have to provide `TextEditingController` to the field which will be disposed because of `ListView` productivity...

So, just add 
`final TextEditingController textController = TextEditingController();`
and 

```
TextFormField(
  controller: textController,
  ...
)
```

**Comment by justinmc** [comment] 2021-03-24 21:57
I'm going to lock this to prevent the solution from getting buried.  If you are having this problem, see the comment just [above](https://github.com/flutter/flutter/issues/17385#issuecomment-804985123) here.  If you continue to have a problem, please open a new issue.
