### ISSUE TITLE
Pub get failing on beta channel

### ISSUE THREAD

**Issue by cirediew** [flutter/flutter#56527] opened 2020-05-07 07:49 UTC
## Steps to Reproduce

I'm running `flutter pub get` and I get the following dependency error when on the beta channel:
```
Running "flutter pub get" in my_app...           


The current Flutter SDK version is 1.17.0-3.4.pre.

Because my_app depends on provider >=4.1.0 which requires Flutter SDK version >=1.17.0, version solving failed.
pub get failed (1; Because my_app depends on provider >=4.1.0 which requires Flutter SDK version >=1.17.0, version solving failed.)
Process finished with exit code 1
```

Which seems odd to me because I would think `1.17.0-3.4.pre` would be `>=1.17.0`.
Is this a bug or am I forced to switch to Stable?

## Logs

Running flutter upgrade and it's up to date
```
flutter upgrade                                               
Flutter is already up to date on channel beta
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (5 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

flutter doctor -v
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/eric/Development/flutter
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/eric/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/192.6392135/Android Studio
      3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6254973/Android Studio
      4.0 Preview.app/Contents
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6423924/Android Studio
      4.1 Preview.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPhoneX          • XXXXXXX • ios • iOS 13.4
    • iPhone 11 Pro Max • DBB8224B-6D0D-4144-8753-80A2FD56DCD0     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

```

**Comment by TahaTesser** [comment] 2020-05-07 11:28
Hi @cirediew 
Created a new project on `beta` channel and `provider: ^4.1.0` has no conflict

```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.0
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (4 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!


``` 

</details>

**Comment by VladyslavBondarenko** [comment] 2020-05-29 07:24
Closing as duplicate of https://github.com/flutter/flutter/issues/56278

**Closed by VladyslavBondarenko** 2020-05-29 07:24 UTC
Labels: in triage, waiting for customer response
