### ISSUE TITLE
[windows desktop] Korean Input doesn't work as expected

### ISSUE THREAD

**Issue by kabyeon** [flutter/flutter#74812] opened 2021-01-27 14:22 UTC
I uses 1.26.0-13.0.pre.194.

my input sequence.
ㄱ ㅏ ㄴ ㅏ ㄷ ㅏ

expected result
가나다

actual result 
다

![image](https://user-images.githubusercontent.com/1699070/106004380-81c00b00-60f6-11eb-9aaa-ef343853d256.png)

When I input Korean message, I can input only the last letter

**Comment by stuartmorgan** [comment] 2021-01-27 15:59
Please provide your `flutter doctor -v` output; changes to Windows IME landed very recently, so we need to know the exact engine version you are using.

/cc @cbracken

**Comment by kabyeon** [comment] 2021-01-27 16:30
C:\Users\kabyeon\dev\dart\textinput>flutter doctor -v
[√] Flutter (Channel master, 1.26.0-13.0.pre.194, on Microsoft Windows [Version 10.0.19042.746], locale ko-KR)
    • Flutter version 1.26.0-13.0.pre.194 at C:\Users\kabyeon\dev\dart\flutter
    • Framework revision 71aec53acb (11 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\kabyeon\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\kabyeon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!

**Comment by TahaTesser** [comment] 2021-01-28 09:53
Hi @kabyeon 
Thanks for providing the details,  I can reproduce using Korean input on Windows.


### Preview
#### Windows
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/106120577-8d561500-617c-11eb-8318-3390afb32f7a.gif)
#### Web
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/106119048-c3929500-617a-11eb-8ac2-79ce8d6b5f94.gif)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Form(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              TextField(
                decoration: InputDecoration(
                  hintText: "Hint ",
                ),
              ),
              TextField(
                decoration: InputDecoration(
                  hintText: "Hint ",
                ),
              ),
              TextField(
                decoration: InputDecoration(
                  hintText: "Hint ",
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 



```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-13.0.pre.194 at C:\Users\Taha\Code\flutter_master
    • Framework revision 71aec53acb (28 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.231, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-13.0.pre.231 at C:\Users\Taha\Code\flutter_master
    • Framework revision 29e604e241 (64 minutes ago), 2021-01-28 00:04:03 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```

</details>

Thank you

**Comment by cbracken** [comment] 2021-03-01 20:33
This appears to be happening because we're incorrectly interpreting `WM_IME_COMPOSITION` events of type `GCS_RESULTSTR` as a trigger to end composing (as is generally the case with Japanese/Chinese input) rather than a trigger to commit the composing region and shift the composing region to a new character on receipt of the next `WM_IME_COMPOSITION` event of type `GCS_COMPSTR`.

I've started on a fix.

**Comment by cbracken** [comment] 2021-03-01 22:20
Fix it out in flutter/engine#24713. I'll send a followup which will adjust the cursor position during composing; right now it's on the left of the composing region rather than right.

**Closed** 2021-03-02 18:14 UTC
Labels: P4, a: desktop, a: internationalization, a: text input, f: material design, found in release: 1.26, framework, has reproducible steps, platform-windows

**Comment by cbracken** [comment] 2021-03-02 18:17
This has landed in the engine. 

There's a separate fix for a regression where suppression of IME keydown events with keycode 229 [was deleted](https://github.com/flutter/engine/pull/23465/files#diff-a85c8141ed41c80633ead050389bc33164a928f1b3c284cada1beec4d09af41aL386-L391) as part of flutter/engine#23465. Framework PR https://github.com/flutter/flutter/pull/77039 will fix that.

**Comment by cbracken** [comment] 2021-03-04 06:01
This rolled to the framework on master in https://github.com/flutter/flutter/pull/77204
