### ISSUE TITLE
Flutter TextField KeyBoard Focus App Crash

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#23720] opened 2018-10-30 07:37 UTC
1 : Two TextField . For  Login Page
2. First TextField KeyBoard IS SimpleChinese ,not click done then I focus PassWordField ,Crash

Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel unknown, v0.10.1, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade 

> cocoapods

        pod setup
[✓] Android Studio (version 3.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-10-30 07:43
Can you please add the error output?

**Comment by zoechi** [comment] 2018-10-30 07:44
#16792, #22201 might be related.

**Comment by lichentao** [comment] 2018-10-30 09:04
Application Specific Information:*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {0, 13} out of bounds; string length 0'Last Exception Backtrace:0   CoreFoundation                  0x00000001d3073ef8 0x00000001d2f56000 + 11711921   libobjc.A.dylib                 0x00000001d2241a40 0x00000001d223b000 + 272002   CoreFoundation                  0x00000001d2f78ac4 0x00000001d2f56000 + 1420203   CoreFoundation                  0x00000001d2f66cdc 0x00000001d2f56000 + 688284   UIKitCore                       0x00000001ff4555ec 0x00000001ff2c7000 + 16317245   UIKitCore                       0x00000001ff444c58 0x00000001ff2c7000 + 15637366   UIKitCore                       0x00000001ff4ae6c4 0x00000001ff2c7000 + 19964847   UIKitCore                       0x00000001ff4acdd4 0x00000001ff2c7000 + 19901008   UIKitCore                       0x00000001ff4ad7ac 0x00000001ff2c7000 + 19926209   UIKitCore                       0x00000001ff444c0c 0x00000001ff2c7000 + 156366010  UIKitCore                       0x00000001ff456cd0 0x00000001ff2c7000 + 163758411  Flutter                         0x00000001036ee154 0x00000001036d8000 + 9045212  Flutter                         0x00000001036ef658 0x00000001036d8000 + 9583213  Flutter                         0x00000001036e1ef0 0x00000001036d8000 + 4068814  Flutter                         0x00000001036fe5f4 0x00000001036d8000 + 15717215  Flutter                         0x000000010373ab10 0x00000001036d8000 + 40424016  Flutter                         0x000000010370b818 0x00000001036d8000 + 21096817  Flutter                         0x000000010370cac0 0x00000001036d8000 + 21574418  CoreFoundation                  0x00000001d3002bf0 0x00000001d2f56000 + 70756819  CoreFoundation                  0x00000001d3002920 0x00000001d2f56000 + 70684820  CoreFoundation                  0x00000001d3002154 0x00000001d2f56000 + 70485221  CoreFoundation                  0x00000001d2ffd030 0x00000001d2f56000 + 68408022  CoreFoundation                  0x00000001d2ffc5b8 0x00000001d2f56000 + 68140023  GraphicsServices                0x00000001d526d584 0x00000001d5262000 + 4646824  UIKitCore                       0x00000001ff62c7ac 0x00000001ff2c7000 + 356138825  Runner                          0x00000001027da964 0x00000001027d0000 + 4336426  libdyld.dylib                   0x00000001d2abcc0c 0x00000001d2abc000 + 3084Binary Images:0x00000001027d0000 - 0x0000000102ea7fff Runner arm64  <7721faaddacf33a7af1c74c7b82cce1e> /var/containers/Bundle/Application/7C1F22AF-9462-4FC6-8161-C59EB31904ED/Runner.app/Runner0x00000001036d8000 - 0x0000000103daffff Flutter arm64  <32ec0ae5f4d839328d6f9f669f40b62b> /private/var/containers/Bundle/Application/7C1F22AF-9462-4FC6-8161-C59EB31904ED/Runner.app/Frameworks/Flutter.framework/Flutter0x00000001d223b000 - 0x00000001d29c3fff libobjc.A.dylib arm64  <68e1654579453adf836a5248bae87f45> /usr/lib/libobjc.A.dylib0x00000001d2abc000 - 0x00000001d2ae6fff libdyld.dylib arm64  <9ba12f5f79783f8da614501b6de70962> /usr/lib/system/libdyld.dylib0x00000001d2f56000 - 0x00000001d32bbfff CoreFoundation arm64   /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation0x00000001d5262000 - 0x00000001d5275fff GraphicsServices arm64   /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices0x00000001ff2c7000 - 0x00000002003e7fff UIKitCore arm64  <9e0817dfc8923453af6a1f226e1a97dd> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
--
*** Term

**Comment by zoechi** [comment] 2018-10-30 09:10
Can you try to copy it in a way so that formatting is retained. Currently it's an unreadable mess.

**Comment by zoechi** [comment] 2018-12-11 14:38
Duplicate of #22201

**Closed by zoechi** 2018-12-11 14:38 UTC
