### ISSUE TITLE
Logs not showing on ios

### ISSUE THREAD

**Issue by santervo** [flutter/flutter#42410] opened 2019-10-10 08:00 UTC
Debug print/loggings are not shown on iOS console, when running on device. 

They don't show up when running via `flutter run` or VSCode.

However logs show when running via XCode, and also in the Dart Devtools.

This happened to me after updating to most recent flutter and Xcode versions.

## Steps to Reproduce

1. Create new flutter app
2. Add few `print`'s in the code
3. Run app with `flutter run` on ios device
4. Logs don't get printed in the terminal.

**Target Platform:** iOS
**Target OS version/browser:** Mac OS 10.4.6
**Devices:** IPad 2018

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-FI)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.39.0)
[✓] Connected device (1 available)
```

**Comment by sageata** [comment] 2019-10-10 13:23
I face the same issue on  flutter channel dev

**Comment by ketanm** [comment] 2019-10-11 21:33
@santervo you may get more response on StackOverflow.

In order to print from Flutter app, you do need to write via logger, so all logs will be captured in console. You can use `logging` package to do it.

**Comment by TheChileanKink** [comment] 2019-10-12 04:38
@santervo I'm having the exact same issue on Master Branch!


> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.10.15-pre.93, on Mac OS X 10.14.6 18G95, locale en-CL)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.0)
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.38.1)
> [✓] Connected device (1 available)
> 
> • No issues found!

**Comment by prodhe** [comment] 2019-10-12 21:29
Same issues for me.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale en-SE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by TheChileanKink** [comment] 2019-10-13 05:43
Only happens on physical devices! It prints just fine on the Simulator.

**Comment by t3o** [comment] 2019-10-13 20:16
Exakt the same here.
iPhone 8 and iPad mini 4 (both v13.1.2) doen't show the print() or printDebug() messages. The output works fine on the emulator (iPhone 11 Pro Max).

**Comment by ThrowJojo** [comment] 2019-10-14 03:27
I'm having the same issue on stable with physical devices. Simulators are working fine and showing logs though.

**Comment by tojoNozomi** [comment] 2019-10-16 08:39
Same issue for me.
The devices is iPhone Xr (iOS 13.1.2) which only print the wrong infos in debug mode, but the simulator works.
If I run by the Xcode it prints all infos.
```
[✓] Flutter (Channel master, v1.10.15-pre.137, on Mac OS X 10.14.6 18G103, locale
    zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)
```

**Comment by ketanm** [comment] 2019-10-16 13:10
@tojoNozomi  - If you do not have a specific reason to use `master` then I would suggest you to switch to `stable` branch and try with the latest (`v1.9.1+hotfix4`) or previous version (`v1.9.1+hotfix2`) and confirm what is going on.

Also, are you using `logging` or `developer` package to log or just print()? (see also - https://flutter.dev/docs/testing/code-debugging#logging)

If you are using correct way to log and still have issues then try to ask on StackOverflow as you may get better support there. People have already asked questions like this - https://stackoverflow.com/questions/49940719/how-to-log-data-to-the-flutter-console

**Comment by lgArlequin** [comment] 2019-10-16 15:36
Same here with VS Code, I think the problem started after updating to ios13 on the device.

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G103, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)
```

**Comment by seb-almeida** [comment] 2019-10-16 15:44
Same thing here, I can confirm this started after updating to iOS 13 :
`[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[!] VS Code (version 1.36.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
`

**Comment by christopherfujino** [comment] 2019-10-18 18:24
Hi thanks for reporting this! This is a duplicate of https://github.com/flutter/flutter/issues/41133, so I will close this issue in favor of that one. Please follow there for updates!

**Closed by christopherfujino** 2019-10-18 18:24 UTC
Labels: t: hot reload, tool, ⌺‬ platform-ios

**Comment by cmaccarone** [comment] 2019-11-08 17:46
same problem trying to build on iPhone XR. working fine on a simulator just not on the actual device.

**Comment by xellDart** [comment] 2019-11-17 18:13
same here

**Comment by Xgamefactory** [comment] 2019-11-19 16:29
same here

**Comment by Baileypollard** [comment] 2019-11-23 17:41
This is still happening to me... This is a fairly big problem

**Comment by fgiraudo** [comment] 2019-11-23 19:38
Same here, fairly big problem indeed.

**Comment by mikhey777** [comment] 2019-11-29 12:43
same here

**Comment by niypoo** [comment] 2019-12-07 09:41
same here , I'm on ios 13 ,

**Comment by fvisticot** [comment] 2019-12-08 10:47
same hire, iOS13 with reald iphone XS

**Comment by christopherfujino** [comment] 2019-12-09 18:26
@niypoo, @fvisticot, et al, I closed this issue as it was a duplicate of https://github.com/flutter/flutter/issues/41133. Please see that issue for further context (it was fixed on master, the fix is currently on beta and will be on the next stable release).

**Comment by valterh4ck3r** [comment] 2020-08-05 19:25
Same here

**Comment by Alexfuse** [comment] 2020-10-06 06:36
Same here, Logs not showing on ios after updating xcode 12.0.1 and ios to 14. flutter 1.22.0

**Comment by christianr11** [comment] 2021-01-13 11:34
When you run your app, look for Observatory debugger and profiler, then click the link. Then go to terminal and check your logs. This worked for me im using Xcode 12.3
'An Observatory debugger and profiler on your iPhone is available at: http://localhost:57176'
