### ISSUE TITLE
Flutter AutoComplete in bottomSheet should show in upside on textfield

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#117836] opened 2022-12-31 09:36 UTC
i want to add autocomplete in bottomsheet butt its suggestion invisible. so if autocomplete added in bottom sheet suggestion need to show upside to text field.
```
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {

  const
  AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        bottomSheet: AutocompleteBasicExample(),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
    'aardvark',
    'bobcat',
    'chameleon',
    'aardvark',
    'bobcat',
    'chameleon',
    'aardvark',
    'bobcat',
    'chameleon',
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}
```

**Comment by darshankawar** [comment] 2023-01-02 07:22
@abdulrehmananwar 
There's an [open proposal](https://github.com/flutter/flutter/issues/74509) to customize the autocomplete options, so your case is similar to that issue. I suggest you to follow-up in it for further updates. https://github.com/flutter/flutter/issues/74509#issuecomment-821974292
Closing this as a duplicate.

**Closed by darshankawar** 2023-01-02 07:22 UTC
Labels: in triage

**Comment by gnprice** [comment] 2023-06-29 00:04
I've filed a more detailed proposal for this specific feature:
* #129748

This thread can now be thought of as a duplicate of that one.
