### ISSUE TITLE
 flutter: error MissingPluginException(No implementation found for method signInWithCredential on channel plugins.flutter.io/firebase_auth)

### ISSUE THREAD

**Issue by Palbitiger** [flutter/flutter#36012] opened 2019-07-11 20:42 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

 not working

```
```

**Comment by BondarenkoStas** [comment] 2019-09-29 01:47
Duplicate of #28874. @Palbitiger Please try https://github.com/flutter/flutter/issues/28874#issuecomment-486359780.

**Closed by BondarenkoStas** 2019-09-29 01:47 UTC
