### ISSUE TITLE
Failed to build using Master channel (android, linux), issues with a package: flutter_svg-0.19.2+1

### ISSUE THREAD

**Issue by ProgrammingLife** [flutter/flutter#76873] opened 2021-02-26 17:55 UTC
1. Trying to run: `flutter run -d linux`
2. `flutter doctor -v` without any errors

## Logs

<details>
<summary>flutter doctor -v</summary>
$ flutter doctor -v   
[✓] Flutter (Channel master, 1.27.0-9.0.pre.110, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-9.0.pre.110 at /home/denis/flutter
    • Framework revision 666c950989 (69 minutes ago), 2021-02-26 08:46:00 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/denis/Android/Sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /home/denis/mylab/programs/android-studio-2/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.15.4
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/denis/mylab/programs/android-studio-2/android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
</details>

<details>
<summary>flutter run -d linux </summary>

$ flutter run -d linux    
Launching lib/main.dart on Linux in debug mode...
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
ERROR:         context != null ? Localizations.localeOf(context, nullOk: true) : null,
ERROR:                                                           ^^^^^^ 
ERROR: ../../../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
ERROR:   static Locale localeOf(BuildContext context) {                 
ERROR:                 ^^^^^^^^                                         
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:1083:7: Error: Struct 'ENUMLOGFONTEX' is empty. Empty structs are undefined behavior.
ERROR: class ENUMLOGFONTEX extends Struct {                             
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2807:7: Error: Struct 'BLUETOOTH_PIN_INFO' is empty. Empty structs are undefined behavior.
ERROR: class BLUETOOTH_PIN_INFO extends Struct {                        
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2932:7: Error: Struct 'EXCEPINFO' is empty. Empty structs are undefined behavior.
ERROR: class EXCEPINFO extends Struct {}                                
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2938:7: Error: Struct 'PROPERTYKEY' is empty. Empty structs are undefined behavior.
ERROR: class PROPERTYKEY extends Struct {}                              
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2945:7: Error: Struct 'PROPVARIANT' is empty. Empty structs are undefined behavior.
ERROR: class PROPVARIANT extends Struct {}                              
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2950:7: Error: Struct 'SAFEARRAY' is empty. Empty structs are undefined behavior.
ERROR: class SAFEARRAY extends Struct {}                                
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2957:7: Error: Struct 'CLSID' is empty. Empty structs are undefined behavior.
ERROR: class CLSID extends Struct {}                                    
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2964:7: Error: Struct 'STATSTG' is empty. Empty structs are undefined behavior.
ERROR: class STATSTG extends Struct {}                                  
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/structs.dart:2971:7: Error: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Empty structs are undefined behavior.
ERROR: class NLM_SIMULATED_PROFILE_INFO extends Struct {}               
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:23:7: Error: Struct 'Utf8' is empty. Empty structs are undefined behavior.
ERROR: class Utf8 extends Struct {                                      
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:16:7: Error: Struct 'Utf16' is empty. Empty structs are undefined behavior.
ERROR: class Utf16 extends Struct {                                     
ERROR:       ^                                                          
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
ERROR:   final int totalSize = count * sizeOf<T>();                     
ERROR:                                 ^                                
Building Linux application...                                           
Exception: Build process failed
</details>

**Comment by dcharkes** [comment] 2021-02-26 18:01
The `ffi` and `win32` errors are a duplicate of https://github.com/flutter/flutter/issues/76705.

**Comment by ProgrammingLife** [comment] 2021-02-26 18:14
Ok, I've done: ```flutter pub upgrade --major-versions```
And now I have only two errors:
```
$ flutter run -d linux                
Launching lib/main.dart on Linux in debug mode...
ERROR: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59: Error: No named parameter with the name 'nullOk'.
ERROR:         context != null ? Localizations.localeOf(context, nullOk: true) : null,
ERROR:                                                           ^^^^^^ 
ERROR: ../../../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
ERROR:   static Locale localeOf(BuildContext context) {                 
ERROR:                 ^^^^^^^^                                         
Building Linux application...                                           
Exception: Build process failed
```

**Comment by ProgrammingLife** [comment] 2021-02-26 18:20
Looks android build is also broken:
```
flutter build appbundle

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^        
../../../../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {                        
                ^^^^^^^^                                                
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/denis/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/denis/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 43s                                                  
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                       104.9s
Gradle task bundleRelease failed with exit code 1
```

**Comment by darshankawar** [comment] 2021-03-01 07:02
@ProgrammingLife 
The error seems to be coming from `flutter_svg` plugin:

`pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,`

I'd suggest you to follow-up in dedicated repo for updates : https://github.com/dnfield/flutter_svg/issues
Check [this](https://github.com/flutter/flutter/issues/75172) similar closed issue and the underlying comments and see if they help.
Closing from here.

**Closed by darshankawar** 2021-03-01 07:02 UTC
Labels: in triage
