### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by wqjuser** [flutter/flutter#136536] opened 2023-10-13 13:25 UTC
## Command
```
flutter run -d macos
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1928:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2493:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2464:14)
#3      FlutterVmService.createDevFS (package:flutter_tools/src/vmservice.dart:1133:20)
#4      DevFS.create (package:flutter_tools/src/devfs.dart:516:61)
#5      FlutterDevice.setupDevFS (package:flutter_tools/src/resident_runner.dart:393:19)
#6      HotRunner._initDevFS (package:flutter_tools/src/run_hot.dart:449:23)
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:41)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.13.6 on channel stable at /Users/wenqingjie/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    [32m•[39m Engine revision a794cf2681
    [32m•[39m Dart version 3.1.3
    [32m•[39m DevTools version 2.25.0
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/wenqingjie/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m ANDROID_HOME = /Users/wenqingjie/Library/Android/sdk
    [32m•[39m Java binary at: /Users/wenqingjie/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 15.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A240d
    [31m✗[39m Unable to get list of installed Simulator runtimes.
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /Users/wenqingjie/Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    [32m•[39m IntelliJ at /Users/wenqingjie/Applications/IntelliJ IDEA Ultimate.app
    [32m•[39m Flutter plugin version 72.1.4
    [32m•[39m Dart plugin version 223.8888

[33m[!][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [32m•[39m NO_PROXY is localhost,127.0.0.1,LOCALHOST
    [32m•[39m NO_PROXY contains localhost
    [32m•[39m NO_PROXY contains 127.0.0.1
    [33m![39m NO_PROXY does not contain ::1

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 14.0 23A344 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8
### Plugins
app_links-3.4.3
audio_session-0.1.16
audioplayers-5.1.0
audioplayers_android-4.0.1
audioplayers_darwin-5.0.1
audioplayers_linux-3.0.0
audioplayers_web-4.0.0
audioplayers_windows-3.0.0
desktop_webview_window-0.2.3
file_picker-5.5.0
flutter_plugin_android_lifecycle-2.0.16
just_audio
just_audio_web-0.4.8
just_audio_windows
network_info_plus-4.0.2
package_info_plus-4.1.0
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
screen_retriever-0.1.9
shared_preferences-2.2.1
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.3
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
sign_in_with_apple-5.0.0
sign_in_with_apple_web-1.0.1
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.20
url_launcher_windows-3.0.7
webview_flutter-4.2.3
webview_flutter_android-3.10.0
webview_flutter_wkwebview-3.7.4
window_manager-0.3.6

**Comment by dam-ease** [comment] 2023-10-13 13:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102994

**Closed by dam-ease** 2023-10-13 13:48 UTC
Labels: in triage
