### ISSUE TITLE
`Container` does not clip edges of `DecorationImage` with `ColorFilter` in Flutter 3.24.0

### ISSUE THREAD

**Issue by berkaayildiz** [flutter/flutter#153118] opened 2024-08-08 19:21 UTC
### Steps to reproduce

1. Create a new project
2. Create a `Container` widget that has `DecorationImage` with `colorFilter` property and apply `borderRadius`
3. Run the app

### Expected results

`borderRadius` should be applied to the `Container` just like it was back in version 3.22.3.

### Actual results

`borderRadius` is not applied to the `Container` in the version 3.24.0, also wrapping widget with `ClipRect` didn't work.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});
  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter 3.24.0')),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            image: DecorationImage(
              colorFilter: ColorFilter.mode(
                Colors.black.withOpacity(0.4),
                BlendMode.darken,
              ),
              image: const NetworkImage(
                'http://images.pexels.com/photos/346529/pexels-photo-346529.jpeg',
              ),
              fit: BoxFit.cover,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| 3.22.0 | 3.24.0 |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/83f56480-c11a-4b1b-8d5f-24a47f9ad638"> | <img width="400" src="https://github.com/user-attachments/assets/4a123865-0324-4480-bd31-94deec069c20">

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (9 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by synstin** [comment] 2024-08-09 05:05
same issue

**Comment by DFelten** [comment] 2024-08-09 07:41
Could be the same issue like this one: https://github.com/flutter/flutter/issues/153146

**Comment by huycozy** [comment] 2024-08-09 09:30
Thanks for the report. I can also reproduce this issue on iOS simulator only `iPhone 15 Pro, iOS 17.5`. It doesn't appear on my physical device `iPhone 7, iOS 15.8`. 

But this seems to be fixed on master channel as I don't see it any more:

<details>
<summary>Screenshot</summary>


<img width="400" src="https://github.com/user-attachments/assets/c33b3308-bf39-4188-a0c4-c7d0bcd3d304">


</details>

Flutter master version: `Channel master, 3.24.0-1.0.pre.525`. Please switch to master channel and confirm this. Thanks!

**Comment by berkaayildiz** [comment] 2024-08-09 10:10
Thanks, just switched to the master channel (`3.24.0-1.0.pre.527 • channel master`) as you suggested and the issue is no longer present. Closing this as fixed.

**Comment by huycozy** [comment] 2024-08-09 10:44
Reopen this for the team's attention since this implementation code is quite common and may consider raising a stable hotfix for this.

### Additional tests
- The issue also happens on Flutter beta channel `3.24.0-0.2.pre`
    - stable `3.24.0` ❗
    - beta `3.24.0-0.2.pre` ❗
    - master `3.24.0-1.0.pre.525` ✅
    ✅: No Issue ❗: Issue reproduced

- The issue doesn't happen if I disable Impeller

<details>
<summary>flutter doctor -v (stable, beta, master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-x64, locale en-VN)
    • Flutter version 3.24.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
```

```console
[!] Flutter (Channel beta, 3.24.0-0.2.pre, on macOS 14.6 23G80 darwin-x64, locale en-VN)
    • Flutter version 3.24.0-0.2.pre on channel beta at /Users/huynq/Documents/GitHub/flutter_beta
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c6b7e9ca4 (10 days ago), 2024-07-30 14:26:44 +0700
    • Engine revision 6e4deceb38
    • Dart version 3.5.0 (build 3.5.0-323.2.beta)
    • DevTools version 2.37.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

```console
[!] Flutter (Channel master, 3.24.0-1.0.pre.525, on macOS 14.6 23G80 darwin-x64, locale en-VN)
    • Flutter version 3.24.0-1.0.pre.525 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 76107bdf50 (4 hours ago), 2024-08-08 16:50:40 -0700
    • Engine revision 0520889683
    • Dart version 3.6.0 (build 3.6.0-130.0.dev)
    • DevTools version 2.38.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

</details>

**Comment by jason-simmons** [comment] 2024-08-09 19:32
This was fixed by https://github.com/flutter/engine/commit/b2bdd68ede150443693888751c5f4899d9eae222

**Comment by ChrisElliotUK** [comment] 2024-08-14 10:18
I have been finding this with BlendMode.dstATop. But seems to be fine with darken


```
Container(
      height: 100,
      width: 100,
      clipBehavior: Clip.hardEdge,
      decoration: BoxDecoration(
        color: Colors.black,
        image: DecorationImage(
          image: const AssetImage(
           ‘assets/my_image.png,
          ),
          fit: BoxFit.cover,
          colorFilter: ColorFilter.mode(
            Colors.black.withOpacity(0.5),
            BlendMode.dstATop,
          ),
        ),
        borderRadius: BorderRadius.circular(20.r),
      ),
),
```

**Comment by jonahwilliams** [comment] 2024-08-28 03:49
This should be fixed in the latest hotfix. If you're still seeing this issue on the latest 3.24 please file a new (as it may be a different issue).

**Closed by jonahwilliams** 2024-08-28 03:49 UTC
Labels: c: regression, engine, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.24
