### ISSUE TITLE
Tool Crash - _TypeError: type 'String' is not a subtype of type 'int?' in type cast

### ISSUE THREAD

**Issue by dodidev** [flutter/flutter#149106] opened 2024-05-26 12:54 UTC
## command

flutter build ipa --release -t lib/main_dev.dart --dart-define-from-file .dev.env --flavor dev --export-method development --no-codesign -v

## exception

_TypeError: type 'String' is not a subtype of type 'int?' in type cast

### Expected results

The final output will be an unsigned IPA file located in the build/ios/ipa

### Actual results

```
[  +24 ms] A crash report has been written to /Users/name/project/flutter_05.log
[        ] This crash may already be reported. Check GitHub for similar crashes.
[        ] https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27String%27+is+not+a+subtype+of+type+%27int%3F%27+in+type+cast
           
[        ] To report your crash to the Flutter team, first read the guide to filing a bug.
[        ] https://flutter.dev/docs/resources/bug-reports
           
[        ] Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
[  +10 ms]


[  +32 ms] ensureAnalyticsSent: 28ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

### Logs

<details open><summary>Logs</summary>

```console
#0      BuildIOSArchiveCommand._parseImageAssetContentsJson (package:flutter_tools/src/commands/build_ios.dart:188:26)
#1      BuildIOSArchiveCommand._validateIconAssetsAfterArchive (package:flutter_tools/src/commands/build_ios.dart:315:60)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:435:7)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-ID)
    • Flutter version 3.22.1 on channel stable at /Users/home/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/home/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/home/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (5 available)
    • Dodi’s Phone (mobile)           • c63c63ef5ecb2421fb7875aad7b29492c7a985fe • ios            • iOS 15.8.2 19H384
    • iPhone 15 Pro Max (mobile)      • B73075D1-A0AA-4BCC-B801-C0C7FB8D6482     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Microsoft Edge 125.0.2535.67

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dodidev** [comment] 2024-05-26 17:32
In my case, the issue was caused by an incorrect data type for the "version" value within the "info" object. The JSON structure causing the problem was:
`
{
  "info": {
    "version": 1,
    "author": "xcode"
  }
}
`
The "version" key should have a string value instead of an integer.

**Comment by darshankawar** [comment] 2024-05-27 10:20
Looks like it is resolved based on above comment. Closing as such.

**Comment by abal1000x** [comment] 2024-05-28 06:57
> Looks like it is resolved based on above comment. Closing as such.

I think Its not, theres an update on xcode.
The `version` field is change from `1` to `'1.1'`.

The problematic script is in here
https://github.com/flutter/flutter/blob/47f463c382c3529c5f06504a9aea53519caaca8a/packages/flutter_tools/lib/src/commands/build_ios.dart#L189

![a](https://github.com/flutter/flutter/assets/117799228/4903ca94-9197-43db-80bf-106dfeb7c592)

That cast to `int?` whill throws an exception since its `String`.

Need more confirmation on other user of macos.

**Comment by darshankawar** [comment] 2024-05-28 12:59
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment] 2024-05-28 13:01
@dodidev Can you provide us a reproducible code sample or steps to replicate that will trigger the reported crash ?

**Closed** 2024-06-18 14:08 UTC
Labels: waiting for customer response, in triage
