### ISSUE TITLE
 java.lang.NullPointerException Attempt to invoke virtual method 'void android.view.Surface.release()

### ISSUE THREAD

**Issue by zakiso** [flutter/flutter#58767] opened 2020-06-05 08:53 UTC
Dear developers:
I have a fragment in an activity. This fragment contains a flutterView rendered using textureView. When I exit from this page, occasionally a crash occurs.

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.Surface.release()' on a null object reference
io.flutter.embedding.android.FlutterTextureView.disconnectSurfaceFromRenderer

io.flutter.embedding.android.FlutterTextureView.disconnectSurfaceFromRenderer (FlutterTextureView.java:211)
io.flutter.embedding.android.FlutterTextureView.detachFromRenderer (FlutterTextureView.java:166)
io.flutter.embedding.android.FlutterView.detachFromFlutterEngine (FlutterView.java:797)
com.binance.dev.sylas.SkylineFragment.onDestroyView (SkylineFragment.java:412)
androidx.fragment.app.Fragment.performDestroyView (Fragment.java:2811)
androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:954)
androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1238)
androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:1303)
androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java:2659)
androidx.fragment.app.FragmentManagerImpl.dispatchDestroy (FragmentManagerImpl.java:2644)
androidx.fragment.app.FragmentController.dispatchDestroy (FragmentController.java:329)
androidx.fragment.app.FragmentActivity.onDestroy (FragmentActivity.java:366)
androidx.appcompat.app.AppCompatActivity.onDestroy (AppCompatActivity.java:233)
com.binance.dev.base.activity.BaseActivity.onDestroy (BaseActivity.java:290)
com.binance.dev.baseext.activity.BaseAppActivity.onDestroy (BaseAppActivity.java:163)
com.binance.dev.activities.marketdetail.MarketDetailActivity.onDestroy (MarketDetailActivity.java:1337)
android.app.Activity.performDestroy (Activity.java:7056)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1154)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4297)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4328)
android.app.ActivityThread.-wrap6 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1604)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:165)
android.app.ActivityThread.main (ActivityThread.java:6375)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:912)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:802)
```

**Comment by TahaTesser** [comment] 2020-06-05 09:31
Hi @zakiso 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample.
Thank you

**Comment by pengrad** [comment] 2020-06-25 06:20
Hey @TahaTesser, this is same as https://github.com/flutter/flutter/issues/50950
And there are 2 PRs opened to fix it https://github.com/flutter/engine/pull/18338,  https://github.com/flutter/engine/pull/18295

Because of this crash we have to downgrade to Flutter 1.12 version
Any chance to merge one of these PRs?

**Comment by TahaTesser** [comment] 2020-06-26 15:12
Closing as duplicate of https://github.com/flutter/flutter/issues/50950

**Closed by TahaTesser** 2020-06-26 15:12 UTC
Labels: in triage
