### ISSUE TITLE
Android camera native preview is rendered above all others widgets

### ISSUE THREAD

**Issue by Nico3652** [flutter/flutter#110997] opened 2022-09-05 15:55 UTC
I have implemented a native camera for Android in my flutter app for many use cases I needed. 
This is a regression because since the latest release (Flutter 3.0 I think), the camera preview displayed through ```AndroidView``` (platform view) is drawn above all others widgets I have in my stack after it.

Here is the preview of flutter my widgets with the ```AndroidView``` behind : 

![5c62ec45-bc45-475f-b68f-5d2a0557c265](https://user-images.githubusercontent.com/50270977/188484000-cbdf34ef-4824-4422-906f-c79d5db99a0e.JPG)

And then when the camera is initialized : 

![552c433d-2e41-4a02-9abd-5d0b60a3ac86](https://user-images.githubusercontent.com/50270977/188484021-3cf96989-3245-4bbc-87af-20e73015571f.JPG)

The camera is now drawn above widgets whereas this is the first widget in my stack. 
This is only happening with camera for now, I have reproduced the same scenario with other platform view widget and this is working fine since this [issue](https://github.com/flutter/flutter/issues/103630) was recently closed.
Platform view widgets are now correctly renderer except for the camera, but I couldn't find why on both side (flutter/kotlin)

Here is the full project which can be clone and run : 
https://github.com/Nico3652/camera_native_android

VERSION :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

TESTS : 

These screen shot were taken on Samsung A10 on Android 11 but reproductible on other real device I own

**Comment by danagbemava-nc** [comment] 2022-09-06 08:01
Reproducible using the code sample in https://github.com/Nico3652/camera_native_android

The code sample works as expected on stable 2.10.5

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/188578455-8ca04366-dc47-4367-9bd9-20f4924cbd95.mp4
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host https://cocoapods.org/ is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by
      peer

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 104.0.5112.101
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.86, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.86 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a04e6b7618 (2 hours ago), 2022-09-06 02:08:10 -0400
    • Engine revision 623b80157c
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 104.0.5112.101

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment] 2022-09-06 13:43
In the short term, while we investigate why this isn't getting automatic fallback, you should be able to work around this by using [Hybrid Composition](https://github.com/flutter/flutter/wiki/Hybrid-Composition) (replacing `initSurfaceAndroidView` with `initExpensvieAndroidView; the docs will be updated soon).

**Comment by Nico3652** [comment] 2022-09-06 15:01
@stuartmorgan  I tried initExpensiveAndroidView according the docs but this is also not working

```
PlatformViewLink(
                        viewType: viewType,
                        surfaceFactory: (BuildContext context,
                            PlatformViewController controller) {
                          return PlatformViewSurface(
                            controller: controller,
                            hitTestBehavior: PlatformViewHitTestBehavior.opaque,
                            gestureRecognizers: const <
                                Factory<OneSequenceGestureRecognizer>>{},
                          );
                        },
                        onCreatePlatformView:
                            (PlatformViewCreationParams params) {
                          return PlatformViewsService.initExpensiveAndroidView(
                            id: params.id,
                            viewType: viewType,
                            layoutDirection: TextDirection.ltr,
                            creationParams: creationParams,
                            creationParamsCodec: const StandardMessageCodec(),
                          )
                            ..addOnPlatformViewCreatedListener(
                                params.onPlatformViewCreated)
                            ..create();
                        },
                      )
```

**Comment by stuartmorgan** [comment] 2022-09-06 15:09
Not working in what way?

**Comment by Nico3652** [comment] 2022-09-06 15:22
Sorry I answered too fast.  The camera render was the same in my main project (above) but then I tried on this example project and it was working with the ```PlatformViewLink```

Thank you for this solution

**Comment by stuartmorgan** [comment] 2022-09-06 19:52
I've verified locally that the camera preview view is dynamically adding a `SurfaceView`, so I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/109690.

If you want to continue to use Virtual Display instead of switching to Hybrid Composition, I've verified that adding a dummy `SurfaceView` to your `CameraView` will trigger fallback, as expected:

```
    <android.view.SurfaceView
        android:layout_width="0dip"
        android:layout_height="0dip"
        android:visibility="gone"
        android:id="@+id/workaround_view"/>
```

Once it's back on Virtual Display though, it hits a new (in Flutter 3.0) assertion for VD that you're not creating the view using the `Context` provided in to the platform view factory though, so you'd need to adjust your factory accordingly if you want to continue to use VD.

**Closed by stuartmorgan** 2022-09-06 19:52 UTC
Labels: severe: regression, platform-android, engine, a: platform-views, has reproducible steps, P3, found in release: 3.3, found in release: 3.4
