### ISSUE TITLE
Running gradlew clean on the outer project makes the Flutter module not build

### ISSUE THREAD

**Issue by xster** [flutter/flutter#36111] opened 2019-07-13 00:44 UTC
From the outer project of add-to-app, ./gradlew clean. Then ./gradlew assembleDebug no longer works

```
./gradlew assembleDebug                                                                                                                                                            1846ms  Fri Jul 12 17:42:15 2019

> Task :flutter:compileflutterBuildDebugArm
Running "flutter pub get" in t130_leaf_flutter...                   0.5s
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/xster/development/test/t130_leaf_flutter/.android/Flutter/build/intermediates/flutter/debug/android-arm/snapshot_blob.bin.d' (OS Error: No such file or directory, errno = 2)
```

Can fix by manually going into the module and flutter building it or by going into the module and flutter cleaning it.

**Comment by TahaTesser** [comment] 2021-09-24 15:03
I can't reproduce the issue using the official Add2APP sample `fullscreen`.


Logs includes `Unable to strip the following libraries, packaging them as they are: libflutter.so.` but app still builds fine

### Actual Results
<details> 
<summary>logs</summary> 
	
```console
tahatesser@Tahas-MacBook-Pro android_fullscreen % ./gradlew clean         

> Configure project :espresso
WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
4 actionable tasks: 2 executed, 2 up-to-date
tahatesser@Tahas-MacBook-Pro android_fullscreen % ./gradlew assembleDebug 

> Configure project :espresso
WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Task :app:processDebugMainManifest
[androidx.test.espresso:espresso-core:3.1.1] /Users/tahatesser/.gradle/caches/transforms-2/files-2.1/4011603d8f6b8811e302377762dacd95/espresso-core-3.1.1/AndroidManifest.xml Warning:
        Package name 'androidx.test.espresso' used in: androidx.test.espresso:espresso-core:3.1.1, androidx.test.espresso:espresso-idling-resource:3.1.1.
[androidx.test.espresso:espresso-contrib:3.1.0] /Users/tahatesser/.gradle/caches/transforms-2/files-2.1/4706f8f963ee1d9178f116bcb83da71a/espresso-contrib-3.1.0/AndroidManifest.xml Warning:
        Package name 'com.removeme' used in: androidx.test.espresso:espresso-contrib:3.1.0, androidx.test.espresso:espresso-accessibility:3.1.0.

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libflutter.so.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 0s
81 actionable tasks: 80 executed, 1 up-to-date
tahatesser@Tahas-MacBook-Pro android_fullscreen %
```
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (7 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 12.0 21A5522h darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	
</details>

**Comment by danagbemava-nc** [comment] 2021-11-03 09:54
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-03 09:54 UTC
Labels: tool, t: gradle, a: existing-apps, r: timeout
