### ISSUE TITLE
Can't get cloud functions to work

### ISSUE THREAD

**Issue by ericel** [flutter/flutter#31403] opened 2019-04-22 04:30 UTC
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0
  cloud_functions: ^0.1.2+1
  firebase_core: ^0.3.4
  cloud_firestore: ^0.9.13+1
  scoped_model: ^1.0.1
  rxdart: ^0.21.0
```

App works well without cloud_functions: ^0.1.2+1. But When I include functions, do get packages and restart application, app breaks with no debugging errors.

**Comment by naiveai** [comment] 2019-06-19 10:39
Could you provide the output of `flutter doctor -v` and describe in a little more detail exactly what happens? Is there simply no output at all? Is there a non-descriptive error?

**Comment by BondarenkoStas** [comment] 2019-10-17 14:00
@ericel was the issue resolved?

**Comment by iapicca** [comment] 2019-11-08 09:44
Hi @ericel 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:44 UTC
Labels: waiting for customer response
