### ISSUE TITLE
flutter keeps to print 2 empty line

### ISSUE THREAD

**Issue by BoshiLee** [flutter/flutter#54931] opened 2020-04-16 06:05 UTC
flutter print 2 empty line when using print

![Screen Shot 2020-04-16 at 2 03 50 PM](https://user-images.githubusercontent.com/20209263/79420234-1aafea80-7feb-11ea-883d-f616fc5fc0d5.png)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-6.0.pre.41, on Mac OS X 10.15.4 19E287, locale en-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

**Comment by VladyslavBondarenko** [comment] 2020-04-16 07:16
Hi @BoshiLee 
provide please minimal complete code sample to reproduce your case.
Checked with master v1.18.0-6.0.pre.42 on Mac OS X 10.15.4, can't see `print` printing empty lines

**Comment by BoshiLee** [comment] 2020-04-17 04:30
I just using a simple print.

`class SimpleBlocDelegate extends BlocDelegate {
  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    print(transition);
  }
}`


The [pretty_dio_logger](https://pub.dev/packages/pretty_dio_logger) has same issue too.
![Screen Shot 2020-04-17 at 12 29 34 PM](https://user-images.githubusercontent.com/20209263/79532247-206b0600-80a7-11ea-8474-9b642165d670.png)

My college's computer doesn't has the issue. Here is his doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hant-TW)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by BoshiLee** [comment] 2020-04-17 06:01
I think this issue only occurred in Channel master, v1.18.0-6.0.pre.41, because beta, v1.17.0 is fine.


[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-TW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
![Screen Shot 2020-04-17 at 2 00 42 PM](https://user-images.githubusercontent.com/20209263/79536993-dd635f80-80b3-11ea-8479-bed83c8c387b.png)

**Comment by VladyslavBondarenko** [comment] 2020-04-17 12:50
@BoshiLee 
I reproduced it with `1.18.0-dev.5.0`, but I can't reproduce it with current master `v1.18.0-6.0.pre.64`. 
I hope it's fixed and there is no need to track the issue, closing.
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-17 12:50 UTC
Labels: in triage
