### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by KhanhPhanN** [flutter/flutter#112782] opened 2022-10-03 04:29 UTC
## Command
```
flutter run --no-sound-null-safety
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1606:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2078:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2049:14)
#3      FlutterVmService.createDevFS (package:flutter_tools/src/vmservice.dart:895:20)
#4      DevFS.create (package:flutter_tools/src/devfs.dart:428:61)
#5      FlutterDevice.setupDevFS (package:flutter_tools/src/resident_runner.dart:400:18)
#6      HotRunner._initDevFS (package:flutter_tools/src/run_hot.dart:373:22)
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:213:40)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:656:26)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 2.2.3 at D:\Project\Setting\Flutter\flutter
    • Framework revision f4abaa0735 (1 year, 3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Setting\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Setting\Sdk
    • Java binary at: D:\Setting\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\Setting\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 105.0.1343.53

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 2b9537c783063d0459b6282a218658a6955938d9
### Plugins
cloud_firestore-3.1.5
cloud_firestore_web-2.6.5
firebase_core-1.10.6
firebase_core_web-1.5.3
fullscreen-1.0.3
path_provider_linux-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
webview_flutter-2.0.10

**Comment by danagbemava-nc** [comment] 2022-10-03 10:38
Closing as duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by danagbemava-nc** 2022-10-03 10:38 UTC
Labels: in triage
