### ISSUE TITLE
Missing android permissions in path_provider documentation

### ISSUE THREAD

**Issue by dartat** [flutter/flutter#112857] opened 2022-10-04 11:14 UTC
Hi spent a lot of time with the [path_provider ](https://pub.dev/packages/path_provider) package because there is no trace in the ReadMe that on Android 10 it is required to add the following permissions in the AndroidManifest:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

```
without that the function `getApplicationDocumentsDirectory()` crashes with the following error (that does not explain the real issue):
`[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`

Could you please add this to prevent other people to waste time?
Have a nice day

**Comment by huycozy** [comment] 2022-10-04 11:43
Hi @dartat, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide `path_provider` version you are using and the output of `flutter doctor -v` as well.

**Comment by dartat** [comment] 2022-10-04 12:31
**path_provider version**: 2.0.11

**flutter doctor output:**
```
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.2075], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)      
[√] Connected device (4 available)
[√] HTTP Host Availability

```
I was trying to reproduce the issue on a fresh project and it works without those permissions.
Then i went back to my project launched flutter pub get, removed the permissions and it works there too.
So it was a problem on my side, sorry for the inconvenience. I even tried 3 times adding and removing the permissions to verify before posting here, but didn't try the good old "turn off and back on"

**Comment by huycozy** [comment] 2022-10-05 02:00
@dartat Thanks for your confirmation. Closing the issue from here as it's working as intended.

**Closed by huycozy** 2022-10-05 02:00 UTC
Labels: in triage
