### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by shafrin95** [flutter/flutter#75683] opened 2021-02-09 04:47 UTC
## Command
```
flutter run --machine --target lib\main.dart -d emulator-5554 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#5      isAppUsingAndroidX (package:flutter_tools/src/android/gradle.dart:799:21)
#6      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:623:17)
#7      injectPlugins (package:flutter_tools/src/plugins.dart:1165:11)
<asynchronous suspension>
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:264:11)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Whoami\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Whoami\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • SM A115F (mobile)       • R9JN50JXXVJ   • android-arm • Android 10 (API 29)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983

**Comment by iapicca** [comment] 2021-02-09 07:37
duplicate of https://github.com/flutter/flutter/issues/69116

**Comment by pedromassangocode** [comment] 2021-02-09 07:51
Closing as duplicate of https://github.com/flutter/flutter/issues/69116.

**Closed by pedromassangocode** 2021-02-09 07:51 UTC
