### ISSUE TITLE
[Impeller] pixelated Text widget with foreground Paint

### ISSUE THREAD

**Issue by ArAmM7** [flutter/flutter#134670] opened 2023-09-13 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a Text widget that is wrapped by a ShaderMask widget 
2. create another Text widget and add the foreground parameter to its style
3. run the app with impeller disabled and then enabled

### Expected results

apps with Impeller enabled should have the same behavior as with it disabled

### Actual results

when impeller is enabled, text with foreground paint is pixelated and paint behavior is changed(the emoji is also painted over).

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'Skia vs Impeller'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  static const goldGradient = LinearGradient(colors: [
    Colors.red,
    Colors.green,
    Colors.blue,
  ]);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'ShaderMask',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            ShaderMask(
              blendMode: BlendMode.srcATop,
              shaderCallback: (bounds) => goldGradient.createShader(bounds),
              child: Text(
                'You have pushed the button this many times: ✌🏻',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
            ),
            const SizedBox(height: 64),
            Text(
              'style foreground Paint',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            Text(
              'You have pushed the button this many times: ✌🏻',
              style: Theme.of(context).textTheme.headlineMedium!.copyWith(
                    foreground: Paint()
                      ..shader = goldGradient.createShader(
                        Rect.fromLTWH(
                          0,
                          0,
                          MediaQuery.of(context).size.width,
                          Theme.of(context).textTheme.headlineMedium!.height!,
                        ),
                      )
                      ..blendMode = BlendMode.srcATop,
                  ),
            ),
          ],
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

| Skia | Impeller |
| ------------- | ------------- |
| <img src="https://github.com/flutter/flutter/assets/29163975/e4322281-1705-42e5-934f-c657f4529bda" alt="Simulator Screenshot - iPhone 14 Pro - 2023-09-13 at 20 18 31" width="400" height="auto"> | <img src="https://github.com/flutter/flutter/assets/29163975/c2df7bc6-573a-4cd9-b728-142c626e89f0" alt="Simulator Screenshot - iPhone 14 Pro - 2023-09-13 at 20 13 09" width="400" height="auto"> |

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-AM)
    • Flutter version 3.13.3 on channel stable at /Users/aram/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (7 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aram/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • AA55DA63-C3BF-4848-90DD-34C749483247 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2023-09-13 16:54
Duplicate of https://github.com/flutter/flutter/issues/132928

**Closed by jonahwilliams** 2023-09-13 16:54 UTC
