### ISSUE TITLE
Font Changes in iOS 13.0 and Flutter 1.9

### ISSUE THREAD

**Issue by bcurley2314** [flutter/flutter#41101] opened 2019-09-23 14:09 UTC
I've noticed quite a big change in the default font output while running Flutter 1.9 on iOS 13.0 both on a device debug, a profile and release build, as well as the iOS 13.0 simulator on the most upgraded xCode.

See before/after screenshots below (before is the top/after is the below):
![text-bug-1](https://user-images.githubusercontent.com/35980864/65432418-22a70380-dde9-11e9-8d02-72b9991a0063.png)
![text-bug-2](https://user-images.githubusercontent.com/35980864/65432422-22a70380-dde9-11e9-8ee7-4a2eb32022d0.png)

From what I can tell with just crude eye-balling and rough photoshop overlays is that the underlying letterSpacing has definitely changed or is being executed in a different manner. This is happening throughout my testing while turning off all internal app themeing as well. This is happening on the default Roboto font with no changes, just a normal ListTile() with a Text() title, but can also be seen in almost all other font renderings throughout the app.

I also can't confirm, but I'm trying to test older versions, that the font size has changed as well. It seems like the dp conversion might be off with iOS 13? All the fonts seem to be smaller across the board, like I'm looking at my app through a much higher resolution screen.

Flutter Doctor just in case:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/briancurley/Documents/Rydr/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/briancurley/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • iPhone 8          • 5A26C06D-929B-42BE-8BDE-7E2EAEB524F5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • iPhone 11 Pro Max • D3C8AFA8-56B3-4857-AC07-45BAFD63E13B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
```

**Comment by bitizen248** [comment] 2019-09-24 08:38
I got same problem. Easiest solution is get official SF Font, add them to assets and set that font family.

Fonts you can get here:
https://developer.apple.com/fonts/
https://developer.apple.com/design/downloads/SF-Font-Pro.dmg

Example:
```
fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700 # Bold
```

```
class TitleAndPriceStyle extends TextStyle {
  TitleAndPriceStyle({Color color = FourFreshColors.text})
      : super(
          fontWeight: FontWeight.bold,
          fontSize: 21,
          fontFamily: "SF Pro Display",
          letterSpacing: 0.36,
          color: color,
        );
}
```

**Comment by bcurley2314** [comment] 2019-09-24 14:26
@bitizen248 This seems like a bigger problem than just swapping of fonts. I tried your solution and the letterSpacing (kerning for us designerly types) is still way off, as well as the default sizing of fonts.

This leads me to believe that it's a deeper issue with the rendering of the density-independent pixels on the new Apple screens/simulators on iOS 13.

**Comment by bitizen248** [comment] 2019-09-24 15:16
@bcurley2314 yes, there is much bigger problem with letter spacing. As quick fix i got styles with proper letter spacing as intended in guide lines.

https://gist.github.com/bitizen248/9a0a3990571abeab2f4f2745b669ffa4

**Comment by HansMuller** [comment] 2019-09-24 15:45
CC @LongCatIsLooong @justinmc

**Comment by justinmc** [comment] 2019-09-24 22:44
Here's my comparison.  I just created a simple app with a UILabel in the center, and a Flutter Cupertino app with a TextField inside of a Center.  Clearly different.

| iOS 13 Native | Flutter |
| ------------- | ------- |
| <img width="465" alt="Screen Shot 2019-09-24 at 3 36 55 PM" src="https://user-images.githubusercontent.com/389558/65555441-890f4d00-dee1-11e9-985e-11d343d15985.png"> | <img width="463" alt="Screen Shot 2019-09-24 at 3 36 41 PM" src="https://user-images.githubusercontent.com/389558/65555440-890f4d00-dee1-11e9-8130-fc8ed08dd6b6.png"> |

**Comment by bcurley2314** [comment] 2019-09-25 02:02
@justinmc yes, that is exactly the issue and that example shows the problem.

**Comment by GaryQian** [comment] 2019-09-30 23:44
I am not aware of any changes to the way we handle anything related to letter spacing recently, though from what I have seen here it looks like Apple updated/changed their fonts, although there is also evidence pointing to something deeper.

Does native text in the same font also have less letter spacing in iOS 13?

**Comment by justinmc** [comment] 2019-10-03 15:52
I will try to write a native iOS app and post screenshots of it running on iOS 13 and 11.3 as well.

**Comment by pd4d10** [comment] 2019-10-06 02:44
Same here. Default font display seems quite different in iOS 13.

Took some screenshots of [a real world app](https://github.com/pd4d10/git-touch):

### iOS 12.2 vs iOS 13.0

<img src="https://user-images.githubusercontent.com/9524411/66263373-4411e180-e824-11e9-9e56-c0cf2a6a3580.png" width="320" /><img src="https://user-images.githubusercontent.com/9524411/66263372-43794b00-e824-11e9-96ca-db5612bf9a9b.png" width="320" />

**Comment by matthewlloyd** [comment] 2019-10-07 16:20
The default fonts now look especially bad if the user has turned on "Bold Text" under Settings -> Display & Brightness.

**Comment by sebastienwozny** [comment] 2019-10-11 12:31
Same problem for me here, just updated this morning, and my app is super ugly.
<img width="292" alt="Capture d’écran 2019-10-11 à 14 30 38" src="https://user-images.githubusercontent.com/17139786/66651634-cd198600-ec33-11e9-9c1d-407390aa0b88.png">
<img width="335" alt="Capture d’écran 2019-10-11 à 14 30 51" src="https://user-images.githubusercontent.com/17139786/66651640-d0147680-ec33-11e9-9c41-0722f5fff7b8.png">

Did you find a solution ?

**Comment by bcurley2314** [comment] 2019-10-11 16:50
No solution yet. Still waiting for update

**Comment by bcurley2314** [comment] 2019-10-13 00:50
@HansMuller is this not a high priority ticket? I would've suspected with Flutter being so UI-forward, this would've been picked up pretty quickly

**Comment by justinmc** [comment] 2019-10-14 16:36
I've been planning to dig into this more by comparing with native apps on iOS 13 and below when I get the time.  I think there are some questions to answer in order to decide what to do here:

Do these font changes happen in native apps before/after iOS 13?
How do native apps handle the size difference if so?
Should Flutter's default font match the native default font exactly on the current platform?
Or, should Flutter's default font look exactly the same on every device regardless of the device's iOS version?

**Comment by fl0cke** [comment] 2019-10-14 17:21
I'd say it should match the native font rendering because that's what users expect. Other native apps seem to be unaffected by the font changes in iOS13. 

However, since font rendering is clearly broken at the moment on iOS (to a point where it is not just a small visual annoyance), finding the root cause should be the main priority.

**Comment by justinmc** [comment] 2019-10-14 17:26
Yeah sounds like something has changed in iOS that affects Flutter's font but not native font, if that's true.  I agree we should figure out what is causing that.

**Comment by GaryQian** [comment] 2019-10-14 18:18
Agree this is quite important, I will find time to dig into this.

**Comment by GaryQian** [comment] 2019-10-14 21:11
So after some light investigation, I can confirm that we are indeed getting average glyph widths roughly 1-1.5 logical pixels smaller on iOS 13 on a default text style.

**Comment by GaryQian** [comment] 2019-10-14 22:44
There is indeed a font difference. The font we fall back to using on 12 is "SF UI Text". On 13, we find "AppleSystemUIFont".

It is still unclear if these are actually the same font or real changes to the available fonts. This opens up the realm of font fallback as potential causes for this.

**Comment by GaryQian** [comment] 2019-10-14 23:49
https://github.com/flutter/flutter/issues/40184 may be related.

**Comment by florent-huran** [comment] 2019-10-15 14:48
Temporary solution: set your own `letterSpacing` value in your TextStyle to set the font approximately as expected. 
But it has to be something flutter handle without needing any action from our side, so looking for a fix too!

**Comment by GaryQian** [comment] 2019-10-15 22:47
Additional discoveries: The AppleSystemUIFont is what is being returned by `systemFontOfSize` in Apple's UIFont. This font does not contain separate versions for different font weights, so when we set it to bold, the font uses Skia's fakebold, which does not adjust the letter spacing.

The SF fonts were a complete family, so they were able to handle the varying font sizes and weights.

Setting the default font to "Helvetica" in LibTxt platform_mac.mm seemed to fix this by using a more complete font with proper weight adjustments. However, the native default font is not Helvetica, so this is not a valid fix.

**Comment by justinmc** [comment] 2019-10-16 16:39
Is that bold problem still what's causing the difference in [my side by side example above]
(https://github.com/flutter/flutter/issues/41101#issuecomment-534776993), even though I'm not explicitly changing the font weight?

**Comment by GaryQian** [comment] 2019-10-18 21:10
Another update, I have confirmed that we are correctly resolving the proper typeface from the font at the minikin level, and that although Apple may have changed the underlying name of the system default font, it still should be based off of the same SF fonts as before. Everything seems to be flowing smoothly except for the fact that the glyph advances we get from the hbtypeface just seems to be smaller/wrong.

At this point, I suspect the issue may lie in the harfbuzz. I'll look through harfbuzz and see if there is any information there, and i'll upgrade harfbuzz for good measure.

**Comment by GaryQian** [comment] 2019-10-23 21:06
Harfbuzz upgrade did not fix this particular bug, but it did bring minor layout improvements. Will continue to look.

**Comment by GaryQian** [comment] 2019-10-23 23:50
https://github.com/flutter/engine/pull/13321 Should fix this!

**Comment by GaryQian** [comment] 2019-10-24 22:30
It turns out that although flutter/engine#13321 fixes this for iOS13, it causes regressions in layout across the board in non-ios fonts/devices. I will see if I can come up with an alternative or more specific fix for this. For example, this is the result of our kerning test, which has obviously incorrect spacing in the small text: 
![image](https://user-images.githubusercontent.com/1887398/67530178-24c3e280-f673-11e9-8ed0-52705e5a3324.png)

**Comment by fl0cke** [comment] 2019-10-25 07:43
This looks like one of those bugs that are a nightmare to track down. Good job 👍

**Comment by GaryQian** [comment] 2019-10-25 20:58
I have updated flutter/engine#13321 with a version that seems to fix this bug as well as prevent the crazy spacing I posted above. Will require a manual engine roll to fix the tests and goldens as this changes the layout by a tiny barely-perceivable amount. As this is a potentially risky change, I will be attempting to land this on Monday.

**Comment by lamatatwany** [comment] 2019-10-28 06:48
@GaryQian How to get your update? do i need to install new version of flutter? if yes can you please tell me which version to download?

**Closed** 2019-10-28 18:09 UTC
Labels: a: typography, e: device-specific, engine, f: cupertino, f: material design, framework, severe: regression, ⌺‬ platform-ios

**Comment by GaryQian** [comment] 2019-10-28 18:11
I have just committed the change to the Flutter engine. It will take a few hours to roll into the framework (as long as all tests pass), where it will be available on the master channel (`flutter channel master`). I will post an update later when it is rolled into framework.

**Comment by matthewlloyd** [comment] 2019-10-28 19:07
Wonderful, thanks! Is there any chance of a hotfix to stable? iOS 13 now has 80%+ adoption (see e.g. https://david-smith.org/iosversionstats/) so this is an immediate, severe, and universal issue for Flutter developers.

**Comment by GaryQian** [comment] 2019-10-28 19:44
cc @kf6gpe any thoughts on hotfix viability?

**Comment by GaryQian** [comment] 2019-10-28 22:51
As of https://github.com/flutter/flutter/commit/c08de65b37bdda866a37d47fe430ceef5b3eecf5, this is now in master.

**Comment by matthewlloyd** [comment] 2019-10-29 17:50
The horizontal compression of the AppBar title in the iOS 12.4 stable channel looks wrong, and will render badly if the user has bold fonts enabled system-wide in accessibility settings. Even though it may occasionally create overflow, I'd argue a hotfix would still be an improvement.

The fix for that app would probably be to reduce the padding between the hamburger / search icons and the title, or change the layout so the long title has enough space. The current layout likely already has that same overflow issue on some other devices.

Creating occasional slight overflow may be the lesser of two evils. This is how my app's UI looks on one user's iOS 13 device currently. He has bold fonts turned on in accessibility. All the text is almost unreadable. It has been like this for him since iOS 13 came out over a month ago. Without a hotfix, he will be waiting a long time. It's embarrassing.

![image2](https://user-images.githubusercontent.com/2041996/67793883-0c2c4180-fa52-11e9-9d99-f5962665bccc.png)

**Comment by GaryQian** [comment] 2019-10-29 18:13
@TheJulianJES Do you think you can provide a small code snippet of the app bar that is overflowing with this fix? I would like to replicate this and hopefully fix this. Based on our tests, the fix should provide near identical spacing, but if this is not the case, we should fix it. It would be helpful to know if you are using any custom fonts or anything.

@matthewlloyd We are currently considering this for a hotfix.

**Comment by TheJulianJES** [comment] 2019-10-29 18:41
@GaryQian Sure, will take a few minutes though.

**Comment by TheJulianJES** [comment] 2019-10-29 19:09
Here is a example with the text cut off on "iOS 13.2 - master channel", but not on "iOS 12.4 - beta channel"
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('This is a really long text text text text ab'),
        ),
      ),
    );
  }
}
```
![Bildschirmfoto 2019-10-29 um 20 07 14](https://user-images.githubusercontent.com/6409465/67800715-0c473400-fa88-11e9-8f49-a2913a4ca7d8.png)

**Comment by sebastienwozny** [comment] 2019-10-29 19:40
On your screenshot, there is less space on the left on iOS 13 (in case you haven’t seen it 🤓)

**Comment by TheJulianJES** [comment] 2019-10-29 19:41
@sebastienwozny Yeah, I guess the trailing " ..." automatically added take more space than the "ab" on iOS 12.
It's the same code on both.

**Comment by GaryQian** [comment] 2019-10-29 22:07
To a quick explanation of what the fix actually does:

We now provide minikin's custom advance calculation instead of using the harfbuzz one. The custom one was written because harfbuzz's one was not producing good values when heavy hinting was used. However, the implementation of it was not quite correct as LinearTextFlag needed to be enabled to prevent it from rounding advances to ints.

Since we now use a different algorithm, we should be less CoreText/OpenType dependent, which can lead to a change from previous behavior. (The following has not bee verified yet) Behavior should now be more similar cross platforms, but this also means that iOS may see slightly differing layouts. I am currently investigating if this is better or worse, since it is hard to say what is "correct" in this case. All I can say for sure now is that this is an improvement in behavior compared to before the fix. The fixed version does properly take into account things like ligatures, so it is still fully functional.

**Comment by GaryQian** [comment] 2019-11-01 18:15
In the near term, I think we will end up keeping the now landed behavior. I recognize that  switching the way we calculate glyph advances to a completely different system has, for certain fonts, increased the spacing compared to what we do for iOS 12. Since this is one of the only approaches that can accommodate both iOS 13 and 12 (as well as Android), this is far better than regressing significantly on iOS 13.

Behavior on iOS < 12 and Android looks to be unchanged. I will continue to look at this to see if adjustments can be made to fully bring iOS 13 back in line with iOS < 12, but in the short term, if you are experiencing text that is slightly too wide, I recommend adding a small negative `letterSpacing` to the `TextStyle` that should temporarily work around this issue until a permanent fully working solution is found.

I'm going to close this bug in favor of tracking this problem in a dedicated separate thread.
The new issue is here: https://github.com/flutter/flutter/issues/43998
Please feel free to continue conversation here, but new information would be welcome in the new issue!

Thanks for everyone's contribution and help in (kind of) fixing this!

**Comment by fredriccliver** [comment] 2019-11-29 06:59
Is there any way to block the effect of 'Bold Text' setting in Dart side?

**Comment by RobinManoli** [comment] 2019-11-29 10:05
Is this fixed on stable?

With this setting on ios 13.1 the default font looks horrible.
> The default fonts now look especially bad if the user has turned on "Bold Text" under Settings -> Display & Brightness.

And on the label of SnackBarAction it's not possible to change fonts, which means getting stuck with this font.

**Comment by dark-chocolate** [comment] 2019-11-30 14:31
I am not able to see special characters in iOS now, works perfectly on Android. Is this thread relevant to following issue or should I create a new one?

Code:

```
Text(
  "➠",
  style: TextStyle(fontSize: 70),
)
```

Screenshot:

![image](https://user-images.githubusercontent.com/40364434/69901763-3c833a80-1386-11ea-8fc5-4704abfa1095.png)

**Comment by matthewlloyd** [comment] 2019-12-03 01:10
> Is this fixed on stable?
> 
> With this setting on ios 13.1 the default font looks horrible.

No, there has been no hotfix to v1.9.1 since hotfix 6. This issue remains unfixed on stable. It has been over a month since the Flutter team mentioned it was being considered for a hotfix, so there is presumably no hope of that happening and we'll have to wait for v1.10 or v1.11.

**Comment by justinmc** [comment] 2019-12-04 20:44
@dark-chocolate Can you open a new issue for that and tag myself and @GaryQian?

I tried it and I'm seeing the same problem.  It happened only on an iOS 13 device or simulator.  It worked fine on Android and an iOS 11 simulator.

**Comment by dark-chocolate** [comment] 2019-12-05 01:53
@justinmc , yes you're right, the code works fine in iOS 11 and on Android, it just doesn't work in iOS 13. 
Created the issue here:

https://github.com/flutter/flutter/issues/46136

**Comment by justinmc** [comment] 2019-12-05 21:13
Looks great, thank you!

**Comment by hishboy** [comment] 2019-12-12 03:38
@justinmc & @GaryQian. Thanks so much for looking into this. The font size still seems broken on iOS. It looks great on simulator but on device the font is still small. I'm using flutter from latest master.

**Comment by justinmc** [comment] 2019-12-16 20:45
@hishboy There are still some cases where the text doesn't match and they're being tracked in this issue: https://github.com/flutter/flutter/issues/43998.

**Comment by anhhtz** [comment] 2020-01-15 05:07
Can someone help me how to declare **AvenirNext** font on iOS ?
I tried this way but it 's not work:

```
fontFamily: "AvenirNext-Regular" // this work with React Native, but Flutter not.
fontFamily: "AvenirNext"
```

**Comment by Faiyyaz** [comment] 2020-01-22 04:10
Is this solved in current flutter version 1.12.13 + v5 hotifx?

**Comment by Faiyyaz** [comment] 2020-01-22 06:59
> Is this solved in current flutter version 1.12.13 + v5 hotifx?

Use RichText widget for now to avoid the bug.

**Comment by justinmc** [comment] 2020-01-22 18:26
This fix here should have gone into v1.10.15 via https://github.com/flutter/flutter/commit/c08de65b37bdda866a37d47fe430ceef5b3eecf5, but there are still related problems being tracked in https://github.com/flutter/flutter/issues/43998.

**Comment by deezaster** [comment] 2020-05-28 06:04
> > Is this solved in current flutter version 1.12.13 + v5 hotifx?
> 
> Use RichText widget for now to avoid the bug.

your proposal is brilliant and works. you saved my project!

**Comment by MobileMon** [comment] 2020-08-10 12:54
I'm having problems with this on the iOS 14 Beta. It's working fine on iOS 13. Just giving a heads up to the Flutter team as they may need to make some changes for iOS 14

**Comment by kf6gpe** [comment] 2020-08-10 15:22
@xster @jmagman I don't know if this is still a problem with 1.20 or not, but FYI.

**Comment by jmagman** [comment] 2020-08-10 16:34
@MobileMon does https://github.com/flutter/flutter/issues/60034 cover it?  If not, please open a new issue for iOS 14 only so we can keep track of it in https://github.com/flutter/flutter/issues/61047.
Thanks!

**Comment by MobileMon** [comment] 2020-08-17 12:16
@jmagman no it doesn't cover it. It's not related to symbols. The whole San Francisco font is not working as mentioned here: https://github.com/flutter/flutter/issues/61858

Not sure why that issue was closed but this is definitely a huge, glaring issue

**Comment by xster** [comment] 2020-08-17 16:23
That issue is being tracked in https://github.com/flutter/flutter/issues/60013. Should be fixed this week.
