### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started. 

### ISSUE THREAD

**Issue by Leonardo01** [flutter/flutter#98890] opened 2022-02-22 01:57 UTC
hi ! I got this error when trying to launch my app on windows  

I´m on windows 10 pro  64bits  version

Error waiting for a debug connection: The log reader stopped unexpectedly, or never started. 
Error launching application on Windows.

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [versÃ£o 10.0.19044.1526], locale pt-BR)
    • Flutter version 2.10.1 at C:\Users\Cyborg\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Cyborg\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Cyborg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment] 2022-02-22 08:15
Duplicate of https://github.com/flutter/flutter/issues/97086 since this is related to `VS 2020 17.1.0` about not being able to flutter run

**Comment by maheshmnj** [comment] 2022-02-22 08:36
Closing based on the above comment

**Closed by maheshmnj** 2022-02-22 08:36 UTC
Labels: in triage
