### ISSUE TITLE
[Android Only] Flutter view renders blank when there is semi-transparent Android overlay on top

### ISSUE THREAD

**Issue by wugeo0824** [flutter/flutter#61845] opened 2020-07-20 07:55 UTC
Currently we are facing a Flutter blank screen issue during app development. In our project, we need to add Flutter to an existing app, and re-use existing native APIs via Flutter channels.

## Steps to Reproduce

The issue happens with the following activity back stack:
top: opaque Android activity
middle: semi-transparent Android activity
bottom: FlutterActivity

Code has been uploaded to https://github.com/wugeo0824/flutter_bug

1. run the app via `flutter run`
2. On the home page (FlutterActivity), click the bottom right floating button to show the transparent overlay
3. On the transparent overlay page(normal Android Activity), click the button `Click Here` to go to next page, notice that at this moment Flutter view is still visible underneath this overlay page.
4. On the top opaque page(normal Android Activity), click `Go Back` to go back.
5. Back on the transparent overlay page, notice that now the Flutter view underneath this overlay is now just black.

**Expected results:** 
Flutter view should still be rendered underneath the transparent overlay page.

**Actual results:** 
Flutter view stopped rendering, and shows up as blank screen.

<details>
  <summary>Logs</summary>

```
```

```
Analyzing bug...
No issues found! (ran in 4.0s)
```

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.6 19G73, locale en-SG)
    • Flutter version 1.17.4 at /Users/xijun.li/Workspace/flutter
    • Framework revision 1ad9baa8b9 (5 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xijun.li/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xijun.li/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by csells** [comment] 2020-07-21 23:22
@xster @jmagman thoughts about this one?

**Comment by jason-simmons** [comment] 2020-07-22 01:09
This is happening because the `MainActivity` is in the started state but not the resumed state after you press the "Go Back" button.

The `FlutterActivity` superclass will pause the Flutter engine in the `onPause` activity callback.  The engine will stop rendering when it is paused.  It will start rendering again when the `FlutterActivity.onResume` callback happens and it invokes `LifecycleChannel.appIsResumed()`.  But that does not happen until the `TransparentOverlayActivity` is destroyed and the `MainActivity` moves to the foreground.

**Comment by wugeo0824** [comment] 2020-07-22 02:51
> This is happening because the `MainActivity` is in the started state but not the resumed state after you press the "Go Back" button.
> 
> The `FlutterActivity` superclass will pause the Flutter engine in the `onPause` activity callback. The engine will stop rendering when it is paused. It will start rendering again when the `FlutterActivity.onResume` callback happens and it invokes `LifecycleChannel.appIsResumed()`. But that does not happen until the `TransparentOverlayActivity` is destroyed and the `MainActivity` moves to the foreground.

@jmagman thanks for the reply. 
does that mean the above usecase will not be supported by Flutter now?
something we noticed is that, if we use cached engine, the 2nd time we enter this scenario, the Flutter view will actually be rendered underneath

**Comment by wugeo0824** [comment] 2020-07-22 02:51
btw, I have tried this in the latest beta Flutter, and the bug is still reproducible

**Comment by VladyslavBondarenko** [comment] 2020-07-22 08:02
Reproduces with current stable `1.17.5`, beta `1.20.0-7.2.pre`, dev `1.21.0-1.0.pre`, master `1.21.0-2.0.pre.94`.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.94, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.94 at /Users/nevercode/dev/flutter
    • Framework revision adc9dde3ba (9 hours ago), 2020-07-21 16:17:23 -0700
    • Engine revision 5a73d4dc25
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (4 available)            
    • Redmi Note 7 (mobile) • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS (desktop)       • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)      • web-server • web-javascript • Flutter Tools
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2020-07-22 18:36
This is a design choice in the Flutter Android embedding libraries.  `FlutterActivity` suspends and resumes rendering in the Flutter engine during the `onPause` and `onResume` activity lifecycle events.

If rendering needs to continue when another activity is placed above the Flutter activity, then you would want to stop rendering in `onStop` and resume rendering in `onStart`.  You could try doing this in a `FlutterActivity` subclass or implementing a custom activity that calls Flutter engine APIs similar to how `FlutterActivity` operates.

**Comment by wugeo0824** [comment] 2020-07-23 06:01
thanks @jmagman , I just tried calling `this.flutterEngine.lifecycleChannel.appIsResumed()` inside `FlutterActivity` subclass's `onStart` and it fixed the bug!
just want to confirm, what are the possible issues caused by this? so we can keep an eye on that during testing

**Comment by blasten** [comment] 2020-08-12 23:16
@wugeo0824 you can also override `onPause` and `onResume`  or create your custom Activity if you don't want this behavior. Would that help?

**Comment by TahaTesser** [comment] 2020-09-04 13:35
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-09-04 13:35 UTC
Labels: engine, found in release: 1.17, found in release: 1.20, found in release: 1.21, has reproducible steps, platform-android
