### ISSUE TITLE
Add shared_preferences sync method

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#27490] opened 2019-02-04 11:42 UTC
I have sometimes the problem that SharedPreferences `preferenceCache` isn't in sync with the device prefs. To handle this error it would be nice to have a function to updated (or sync) the `preferenceCache`.

**Comment by wouterhardeman** [comment] 2019-02-04 14:54
Had this issue myself as well. This is especially an issue in Add2App use cases when the host platform changes to shared preferences.

I've implemented a `refreshCache()` function locally. I'll make a pull request somewhere this week after I've added tests.

**Comment by The-Redhat** [comment] 2019-02-04 14:56
Ok thanks !

**Comment by zoechi** [comment] 2019-02-07 16:21
Looks like a duplicate of #22016

**Closed** 2019-05-31 22:51 UTC
Labels: p: first party, p: shared_preferences, plugin, severe: new feature
