### ISSUE TITLE
MissingPluginException for path_provider -Android(iOS working fine)

### ISSUE THREAD

**Issue by expertdev-designer** [flutter/flutter#86016] opened 2021-07-07 11:23 UTC
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

**Comment by amankhantakeoff** [comment] 2021-07-08 06:14
Manually giving the directory for Android worked from me @expertdev-designer . See this example:-

Directory dir = Directory('/storage/emulated/0/SaveIt/Youtube');

dir.listSync()

**Comment by TahaTesser** [comment] 2021-07-08 09:30
Hi @expertdev-designer 
Just tried the latest  `path_provider: ^2.0.2` on Android running API 30, no such issue 

### Code sample
https://pub.dev/packages/path_provider/example

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20      • android-arm64  • Android 10 (API 29)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.51]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```

</details>

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by expertdev-designer** [comment] 2021-07-10 12:14
Hii @TahaTesser Thanks for quick response

I am already using latest version path_provider: ^2.0.2

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 2.2.0 at /Users/mac-2/Documents/sdks/flutter
    • Framework revision b22742018b (8 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac-2/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • Redmi Note 7S (mobile)  • 265ac434                                 • android-arm64  • Android 9 (API 28)
    • Elint’s iPhone (mobile) • caeedac25a54fc67101807449f92effc8f753851 • ios            • iOS 14.5.1
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 91.0.4472.114
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

**Comment by TahaTesser** [comment] 2021-07-12 07:59
Hi @expertdev-designer 
Can you please upgrade to the latest Flutter stable and provide `flutter run --verbose` logs running the minimal code sample, tap to call `getApplicationDocumentsDirectory` while running the app
Thank you

**Comment by jtmuller5** [comment] 2021-07-21 12:28
I had this same error when using Hive and flutter_facebook_auth together. My issue was that I hadn't performed the [Android setup for the facebook plugin](https://facebook.meedu.app/#/android).

@expertdev-designer The error you mention was being thrown when I called Hive.initFlutter() since Hive uses path_provider under the hood.

**Comment by codebombi** [comment] 2021-07-25 14:42
> I had this same error when using Hive and flutter_facebook_auth together. My issue was that I hadn't performed the [Android setup for the facebook plugin](https://facebook.meedu.app/#/android).
> 
> @expertdev-designer The error you mention was being thrown when I called Hive.initFlutter() since Hive uses path_provider under the hood.

I have the same problem. How to solve the problem?

**Comment by TahaTesser** [comment] 2021-08-17 13:41
The packages mentioned are  third-party packages

@expertdev-designer 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-08-17 13:41 UTC
Labels: waiting for customer response, in triage
