### ISSUE TITLE
Keyboard overlaps alertdialog

### ISSUE THREAD

**Issue by BarbaricGamester** [flutter/flutter#15123] opened 2018-03-04 06:02 UTC
When I open the keyboard in an alertdialog the keyboard overlaps the dialog which is pretty inconvenient as the user can't even see what he is typing.

**Comment by fractalemagic** [comment] 2018-03-04 08:52
Dupe of #7032, there's a fix in there aswell. Just note the last comment about using `mediaQuery.viewInsets` rather than `mediaQuery.padding`.

**Comment by Hixie** [comment] 2018-03-12 02:49
Closing as duplicate.

**Closed by Hixie** 2018-03-12 02:49 UTC
