### ISSUE TITLE
Flutter installation as per https://docs.flutter.dev/get-started/install/windows results in bogus Android Studio "new project" dialogue and launching the default created app results in "Exception: No Windows desktop project configured." and a bogus (=unhelpful unrelevant) url

### ISSUE THREAD

**Issue by via-lars** [flutter/flutter#95266] opened 2021-12-14 16:02 UTC
## Steps to Reproduce

1. Follow https://docs.flutter.dev/get-started/install/windows to get build support for Windows (btw. you advertise Desktop apps yet Windows is in Beta and one can't build Linux apps on Windows per your documentation. Just because "every" other web "developer" is a boasting lier you shouldn't mimic them. Such false claims are fraud.)
2. Follow https://docs.flutter.dev/get-started/editor?tab=androidstudio (this is the "Next" step from 1. as of writing this report)
3. Read and try to follow https://docs.flutter.dev/get-started/test-drive?tab=androidstudio (btw.: it's "New Flutter Project" in AS as of this writing and not "Create New Flutter Project").

The dialogue looks like 

![image](https://user-images.githubusercontent.com/23217105/146031721-1474087a-44d4-44d5-8eac-5f14d45daae1.png)

An "Install SDK…" button is missing.

I entered the path to where I extracted the downloaded zip from 1. (which also already exists in the PATH environment variable).

From a former installation of a colleague but who only remembers installation took him half a day I expect the following screen:

![image](https://user-images.githubusercontent.com/23217105/146032232-d4ceb239-85f7-4a4a-8438-f2b1c0637675.png)

4. Once I entered the path, clicked next and filled the form (btw.: advanced settings are autofilled from the prose Project Name such as the Module Name but is done as CamelCase. When wanting to "Finish" the wizard, that Module Name is invalid and requested to be snail_case. If you have a prose text and an auto converter and validifyer, make them compatible) I am shown the editor, select the target platform from the dropdown and I click "run" as per the screenshot in the link from 3.

5. the resulting console message is:
`Launching lib\main.dart on Windows in debug mode...
Exception: No Windows desktop project configured. See https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app to learn about adding Windows support to a project.` (btw: that url is very unhelpful).

## Logs

<details>
<summary>Logs</summary>

```
flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over
time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional
                            diagnostic information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Usage: flutter config [arguments]
-h, --help                                      Print this usage information.
    --[no-]analytics                            Enable or disable reporting anonymously tool usage statistics and crash
                                                reports.
    --clear-ios-signing-cert                    Clear the saved development certificate choice used to sign apps for iOS
                                                device deployment.
    --android-sdk                               The Android SDK directory.
    --android-studio-dir                        The Android Studio install directory.
    --build-dir=<out/>                          The relative path to override a projects build directory.
    --[no-]enable-web                           Enable or disable Flutter for web. This setting will take effect on the
                                                master, dev, beta, and stable channels.
    --[no-]enable-linux-desktop                 Enable or disable beta-quality support for desktop on Linux. This
                                                setting will take effect on the master, dev, beta, and stable channels.
                                                Newer beta versions are available on the beta channel.
    --[no-]enable-macos-desktop                 Enable or disable beta-quality support for desktop on macOS. This
                                                setting will take effect on the master, dev, beta, and stable channels.
                                                Newer beta versions are available on the beta channel.
    --[no-]enable-windows-desktop               Enable or disable beta-quality support for desktop on Windows. This
                                                setting will take effect on the master, dev, beta, and stable channels.
                                                Newer beta versions are available on the beta channel.
    --[no-]enable-windows-uwp-desktop           Enable or disable Flutter for Windows UWP. This setting will take effect
                                                on the master and dev channels.
    --[no-]single-widget-reload-optimization    Enable or disable Hot reload optimization for changes to class body of a
                                                single widget. This setting will take effect on the master, dev, and
                                                beta channels.
    --[no-]enable-android                       Enable or disable Flutter for Android. This setting will take effect on
                                                the master, dev, beta, and stable channels.
    --[no-]enable-ios                           Enable or disable Flutter for iOS. This setting will take effect on the
                                                master, dev, beta, and stable channels.
    --[no-]enable-fuchsia                       Enable or disable Flutter for Fuchsia. This setting will take effect on
                                                the master channel.
    --[no-]enable-custom-devices                Enable or disable Early support for custom device types. This setting
                                                will take effect on the master and dev channels.
    --clear-features                            Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.

Settings:
  enable-windows-desktop: true

Analytics reporting is currently enabled.
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1387], locale de-DE)
    • Flutter version 2.8.0 at C:\Users\Hansen\Downloads\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Hansen\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.0)
    • VS Code at C:\Users\Hansen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1387]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.53

! Doctor found issues in 2 categories.
```

</details>

Note wrt flutter doctor ouput: as per the instructions from 1. the cmdline-tools were not required to be installed

Btw.: fix all the "btw" issues I mentioned.

**Comment by stuartmorgan** [comment] 2021-12-14 16:13
> 1. btw. you advertise Desktop apps yet [...] one can't build Linux apps on Windows per your documentation.

Arbitrary cross-compilation from every host platform to every target platform is not a required bar for supporting something. Feel free to file a new feature request for that host/target pair however (it has not been requested so far).

> Just because "every" other web "developer" is a boasting lier you shouldn't mimic them. Such false claims are fraud.

Please review our code of conduct before engaging further here.

> 5\. btw: that url is very unhelpful

This piece is a duplicate of https://github.com/flutter/flutter/issues/94398; it's fallout from a restructure of the website.

> Btw.: fix all the "btw" issues I mentioned.

Please file individual issues for unrelated problems. It's impossible to effectively track multiple unrelated requests or bug reports in a single issue.

**Comment by darshankawar** [comment] 2021-12-15 07:05
> Please file individual issues for unrelated problems.

@via-lars Since this sounds to be documentation issues related to installation guide being referred from website,  I think the issues you reported need to be filed in website repo : 

<img width="314" alt="Screenshot 2021-12-15 at 12 32 46 PM" src="https://user-images.githubusercontent.com/67046386/146139163-a650f322-8008-4a0b-9cb5-cd6a9c481d13.png">


Clicking on it directs you to dedicated repo.

Also, as mentioned in above comment, you may follow-up in https://github.com/flutter/flutter/issues/94398 for incorrect url issue.

Closing from here.

**Closed by darshankawar** 2021-12-15 07:05 UTC
Labels: in triage
