### ISSUE TITLE
Flutter web fonts behave oddly in different broswers(firefox).

### ISSUE THREAD

**Issue by Leostina** [flutter/flutter#50631] opened 2020-02-12 09:41 UTC
Hi, I encountered this problem while testing the web on firefox. Top/bottom of some text are cropped by 'something'. The font with this bug are 'MontserratSemibold' family. This font displays in firefox looks more like 'MontserratBold' to me.

[BUGS in **firefox**]-------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/60214417/74321493-7638de80-4dd6-11ea-8618-00e7158adbdd.png)
![image](https://user-images.githubusercontent.com/60214417/74321501-7b962900-4dd6-11ea-8316-2353b533bfbf.png)
![image](https://user-images.githubusercontent.com/60214417/74321516-7f29b000-4dd6-11ea-9ce2-76f320eb4769.png)
![image](https://user-images.githubusercontent.com/60214417/74321531-8486fa80-4dd6-11ea-9f43-c175387a96f2.png)

[Normal behaviors in **Chrome**]-----------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/60214417/74321624-b13b1200-4dd6-11ea-9005-b6aaaa685337.png)
![image](https://user-images.githubusercontent.com/60214417/74321630-b5ffc600-4dd6-11ea-9dee-e6c56fced520.png)
![image](https://user-images.githubusercontent.com/60214417/74321634-b9934d00-4dd6-11ea-8343-0e3dc2f4eecd.png)
![image](https://user-images.githubusercontent.com/60214417/74321659-c57f0f00-4dd6-11ea-9d07-05577aa34a6c.png)

**The problematic fonts**
[Montserrat.zip](https://github.com/flutter/flutter/files/4191032/Montserrat.zip)

pubspec.ymal

 fonts:
      - family: MontserratRegular
        fonts:
          - asset: assets/fonts/MontserratRegular.ttf

      - family: MontserratMedium
        fonts:
          - asset: assets/fonts/MontserratMedium.ttf

      - family: KarbonSemibold
        fonts:
          - asset: assets/fonts/KarbonSemibold.ttf

      - family: KarbonMedium
        fonts:
          - asset: assets/fonts/KarbonMedium.ttf

      - family: MontserratSemibold
        fonts:
          - asset: assets/fonts/MontserratSemiBold.ttf

      - family: KarbonLight
        fonts:
          - asset: assets/fonts/KarbonLight.ttf

      - family: MontserratBold
        fonts:
          - asset: assets/fonts/MontserratBold.ttf

      - family: KarbonRegular
        fonts:
          - asset: assets/fonts/KarbonRegular.ttf

THANK YOU IN ADVANCE!

**Comment by VladyslavBondarenko** [comment] 2020-02-12 10:15
Hi @Leostina 
can you please check if this is still an issue on the master channel?

Duplicate of https://github.com/flutter/flutter/issues/49946

**Comment by CXZ7720** [comment] 2020-02-13 19:28
I think this is related with UserAgent.
I opened my web page using Firefox`(Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0)`.
I changed UserAgent String using [browser extension](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) and the browser renders page differently.

Here are caputred part of my site which was built with flutter too.(I'm on flutter beta channel v1.14.6)
All Font-famliy was set to "Noto Sans KR" from [google fonts](https://fonts.google.com/specimen/Noto+Sans+KR).

1. Default(Nothing changed)
![Firefox](https://user-images.githubusercontent.com/29659112/74469511-28100200-4ee0-11ea-81c2-967f8505b5bc.png)

2. Same browser, just changed user agent to chrome. (`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36`)
![chrome](https://user-images.githubusercontent.com/29659112/74469593-4d047500-4ee0-11ea-9706-5238a9d5fbf3.png)

Depends on User Agent String, site rendered differently.
You can find the firefox-specific feature like **narrower line spacing, bottom-cropped characters like "g", "p", ", (comma)"** .
Not only english characters but also korean characters are rendered weird.

**Comment by UnicornsOnLSD** [comment] 2020-02-13 21:50
This has fixed my text clipping issues too.

![image](https://user-images.githubusercontent.com/44349936/74481486-b8cbeb00-4eaa-11ea-9435-c4b8db56eb94.png)

![image](https://user-images.githubusercontent.com/44349936/74481510-c8e3ca80-4eaa-11ea-8574-97f9e7111e4a.png)

**Comment by mdebbar** [comment] 2020-03-05 19:06
This looks like it's the same as https://github.com/flutter/flutter/issues/49946.

**Closed by mdebbar** 2020-03-05 19:06 UTC
Labels: a: typography, waiting for customer response, ☸ platform-web
