### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\manup\Desktop\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by ManuPulido27** [flutter/flutter#69606] opened 2020-11-02 21:24 UTC
Hi, im having an issue after upgrading flutter, i cant use the command flutter pub get. And i also cant find the file C:\Users\manup\Desktop\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat..
Can anyone please help?

## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\manup\Desktop\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:295:34)
<asynchronous suspension>
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:219:15)
#9      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:117:17)
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:151:11)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.3 at C:\Users\manup\Desktop\Flutter\flutter
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\manup\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\manup\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
assets_audio_player-2.0.10
assets_audio_player_web-2.0.9+2
firebase_admob-0.9.3+4
firebase_core-0.4.5
firebase_core_web-0.1.1+2
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
share_files_and_screenshot_widgets-1.0.3
url_launcher-5.6.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1

**Comment by darshankawar** [comment] 2020-11-03 07:16
Closing this as duplicate of [60880](https://github.com/flutter/flutter/issues/60880)

**Closed by darshankawar** 2020-11-03 07:16 UTC
