### ISSUE TITLE
The drawer can be dragged underneath the endDrawer

### ISSUE THREAD

**Issue by blac3777** [flutter/flutter#34151] opened 2019-06-10 07:52 UTC
## Bug

![34151](https://media.giphy.com/media/mEbpffMqjpfCPTdR0T/giphy.gif)

## Steps to Reproduce

1. [Add a drawer & endDrawer to a scaffold](https://gist.github.com/blac3777/e3ad5279fd074f7e1fc9d9cd16cd1992).
2. Gently flick the endDrawer open.
3. BEFORE the endDrawer finishes its opening animation, QUICKLY flick the drawer open.
4. Now the endDrawer overlays the drawer, i.e., they are simultaneously share the screen...

I thought that this bug (#19704) was fixed long ago (#20015), but it seems that it was only diluted. Can you come up w/ a way to fix it?

## Logs

```
No issues found! (ran in 2.4s)
```

```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.503], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.34.0)
[√] Connected device (1 available)
```

**Comment by CountPablo** [comment] 2019-06-12 01:29
It's worth noting that it can only happen that way and not the other way round (endDrawer under drawer).
Easily reproducible with the following code:

```import 'package:flutter/material.dart';

class Test extends StatefulWidget{
  @override
  TestState createState() => TestState();
}

class TestState extends State<Test> with SingleTickerProviderStateMixin{
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
        child: new Text('Test'),
      ),
      drawer: new Drawer(
        child: new Container(
          color: Colors.blue,
        ),
      ),
      endDrawer: new Drawer(
        child: new Container(
          color: Colors.yellow,
        ),
      ),
    );
  }
}
```

## Flutter Doctor

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

**Comment by LiteCatDev** [comment] 2019-07-17 15:28
I can confirm that this bug is present in Flutter 1.7.8+hotfix.3.

**Comment by lsi8** [comment] 2019-12-09 00:28
Why hasn't this been fixed, or even addressed yet? Has anyone discovered a work around?

**Comment by lsi8** [comment] 2019-12-09 06:15
It only happens when the finger is flicked & lifted off before reaching the half way point.

**Comment by TahaTesser** [comment] 2020-05-05 16:01
Hi @blac3777 
Not able to reproduce this issue on latest `dev` channel

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (12 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129

• No issues found!
``` 

</details> 


Are you still experiencing this issue n latest stable?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-27 08:26
Closing as fixed.
If you disagree, please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-05-27 08:26 UTC
Labels: f: material design, framework, waiting for customer response
