### ISSUE TITLE
[in_app_purchase][Android] 'queryPastPurchases' returns empty list

### ISSUE THREAD

**Issue by vietgameplay** [flutter/flutter#107937] opened 2022-07-19 15:53 UTC
- in_app_purchase ^3.0.6
- in_app_purchase_android: 0.2.3+1

I use 'queryPastPurchases' for query existing purchase, It returns empty list. 

```
if (Platform.isAndroid) {
      final InAppPurchaseAndroidPlatformAddition androidPlatform = InAppPurchase.instance.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
      final QueryPurchaseDetailsResponse purchaseResponse = await androidPlatform.queryPastPurchases();
      print("xxx:${purchaseResponse.pastPurchases.length}");    // ------------------>return 0
      for (var purchase in purchaseResponse.pastPurchases) {
        PurchaseWrapper billingClientPurchase = purchase.billingClientPurchase;

        if (!billingClientPurchase.isAutoRenewing) {
          // Subscription is cancelled and will not renew when it expires. You should still deliver/ enable the content.
        }

        // Verify the purchase and deliver the content.
      }
    }
```
----------------------------------------------

But when I add native code into my app(eg: add code and Billing 5.0 into MainActivity Android then It can get last purchases normally)
source kotlin:
```
        val params = QueryPurchasesParams.newBuilder().setProductType(BillingClient.ProductType.SUBS)
        billingClient.queryPurchasesAsync(
            params.build(),
        ) { billingResult, list ->
            print(list.size) // ------------------>return 2
        }
```

**Comment by danagbemava-nc** [comment] 2022-07-20 12:57
Hi @vietgameplay, I believe this is a duplicate of https://github.com/flutter/flutter/issues/107454. 

`queryPastPurchases` and `restorePurchases` both call the same API on the native android side, and the issue lies with the current implementation of `queryPurchasesAsync` on the native side of the plugin which is being addressed in https://github.com/flutter/plugins/pull/6106. 

I'll be closing this as a duplicate for now, but in case this issue is not resolved after https://github.com/flutter/plugins/pull/6106 is merged, we can revisit this issue. 

Thank you

**Closed by danagbemava-nc** 2022-07-20 12:57 UTC
Labels: in triage
