### ISSUE TITLE
Customizable date format beyond locale in date picker

### ISSUE THREAD

**Issue by haomun0731** [flutter/flutter#140368] opened 2023-12-19 08:07 UTC
### Use case

The current Flutter date picker functionality limits date format customization to the locale, which may not align with users' preferences. This feature request aims to enhance the date picker by introducing a `DateFormat` parameter. This parameter would allow users to independently customize the date format according to their system preferences, providing greater flexibility in date-time representation.

Refer to the attached screenshot for a visual representation of the current limitation:

![Date Picker Issue](https://github.com/flutter/flutter/assets/65224274/7481cbac-6210-4f5c-8832-2560abdc0425)

Users may have distinct system date-time formats, as exemplified in the iOS screenshot below:

![iOS Date Format](https://github.com/flutter/flutter/assets/65224274/71c920b1-52e5-4332-82ee-bba64b6fc2e4)

**Minimal Project Available for Testing:** A minimal project describing the issue in the [FlutLab editor](https://flutlab.io/editor/49fa2af7-5101-45cb-afaa-83eba2ff722f).

### Proposal

**1. Add dateFormat Parameter:**
- Introduce a new parameter named `dateFormat` to the `showDatePicker` function.
- The `dateFormat` parameter should accept a `DateFormat` object representing the desired date format.

**2. Fallback to Locale:**
- If `dateFormat` is not provided, the date picker should fall back to using the `locale` for formatting.

**Comment by danagbemava-nc** [comment] 2023-12-19 09:31
Closing this as a duplicate of https://github.com/flutter/flutter/issues/83302

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-19 09:31 UTC
Labels: in triage
