### ISSUE TITLE
flutter_gallery_ios__transition_perf is flaky

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#62081] opened 2020-07-23 01:15 UTC
Keeps failing with timeout.
```
2020-07-22T11:17:29.725770: stderr: VMServiceFlutterDriver: Connected to Flutter application.
2020-07-22T11:17:34.739591: stderr: VMServiceFlutterDriver: waitForCondition message is taking a long time to complete...
2020-07-22T11:29:29.353095: stdout: 12:00 [32m+0[0m[31m -1[0m: flutter gallery transitions (setUpAll) [1m[31m[E][0m[0m
stdout: 
2020-07-22T11:29:29.353935: stdout:   TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
```
[flutter_gallery_ios__transition_perf_50b87dc_8.log](https://github.com/flutter/flutter/files/4963418/flutter_gallery_ios__transition_perf_50b87dc_8.log)

**Comment by jmagman** [comment] 2020-07-23 01:22
<img width="46" alt="Screen Shot 2020-07-22 at 6 22 06 PM" src="https://user-images.githubusercontent.com/682784/88244309-45dc5280-cc48-11ea-866d-784c5af1a5a6.png">

**Comment by zanderso** [comment] 2020-07-23 02:21
Marking this P0 because missing benchmark regressions would be bad. Assigning @blasten to report back on attempting to repro manually on mac-1.

/cc @keyonghan @godofredoc for infra
/cc @liyuqian @kf6gpe for help debugging the benchmark and/or to watch out for glitches in the benchmark dashboard.

**Comment by blasten** [comment] 2020-07-23 19:23
@keyonghan is trying to reset state on the Macs

**Comment by keyonghan** [comment] 2020-07-23 19:43
Reboot & rm .pub-cahche make mac1 stable to pass the test.
Tried testing on mac6, and the issue is reproduced.
By taking a screen shot on mac6 device, finding a pop up window of `Sofware Update`. Will try removing the log and see if it solves the problem.

**Comment by keyonghan** [comment] 2020-07-23 21:42
After removing the dialog on mac6. Test passes. Will check other failed bots/devices.

**Comment by keyonghan** [comment] 2020-07-24 00:55
Have walked through all bots that failed this test, removing all dialogs if any.
The issue related to infra should be fixed.

**Comment by chinmaygarde** [comment] 2020-07-27 17:36
The last few runs of the benchmark have passed. Can we mark this as fixed?

**Comment by chinmaygarde** [comment] 2020-07-27 17:38
The benchmark is still marked flaky.

**Comment by keyonghan** [comment] 2020-07-27 18:01
SGTM to mark as fixed. Closing. https://github.com/flutter/flutter/pull/62348 to remove flaky flag.

**Comment by keyonghan** [comment] 2020-07-30 16:57
It seems still flaky. Just did a quick check of the log: 
```Task failed with the following reason:
Timeout waiting for task completion: Future not completed
Deleting build/ directories, if any.
2020-07-29T23:14:13.881662: Agent ID: flutter-devicelab-mac-22020-07-29T23:14:14.303170: Observatory listening on http://127.0.0.1:20000/
2020-07-29T23:14:14.529221: Running task with a timeout of null.```

@digiter Do you mind help take a look?

<img width="41" alt="Screen Shot 2020-07-30 at 9 54 09 AM" src="https://user-images.githubusercontent.com/54558023/88951430-d0294580-d24a-11ea-801a-b8438cb732a6.png">

**Comment by keyonghan** [comment] 2020-07-30 17:53
unassign myself as I am not looking at the issue.

**Comment by zanderso** [comment] 2020-07-30 19:53
I dropped the priority on this because while the test is still flaky, it is much less flaky than before, to the extent that we are probably getting useful benchmark numbers again.

**Comment by keyonghan** [comment] 2020-07-30 19:57
Gonna submit https://github.com/flutter/flutter/pull/62348 when tests pass.

**Comment by zanderso** [comment] 2020-08-13 21:32
Can this be closed?

**Comment by keyonghan** [comment] 2020-08-13 21:36
Yes. Test had been marked not flaky. Closing.

**Closed by keyonghan** 2020-08-13 21:36 UTC
Labels: P3, engine, passed secondary triage, platform-ios, team, team: flakes, team: infra
