### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by abrathovde** [flutter/flutter#19331] opened 2018-07-13 02:27 UTC
**Steps to recreate**
1. Run Android emulator with app open
2. In Android Studio open `Flutter Inspector`
3. Click `Toggle Platform Mode` twice

**Error message**
```
I/flutter (15306): The following assertion was thrown building _CupertinoBackGestureDetector<dynamic>(state:
I/flutter (15306): _CupertinoBackGestureDetectorState<dynamic>#72c3a):
I/flutter (15306): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1792 pos 12: '() {
I/flutter (15306):       final AbstractNode parent = this.parent;
I/flutter (15306):       if (parent is RenderObject)
I/flutter (15306):         return parent._needsCompositing;
I/flutter (15306):       return true;
I/flutter (15306):     }()': is not true.
```
**Stack trace snippet**
```
I/flutter (15306): #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart)
I/flutter (15306): #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1232:7)
I/flutter (15306): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2631:11)
I/flutter (15306): #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:128:13)
I/flutter (15306): #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1077:11)
I/flutter (15306): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2626:7)
I/flutter (15306): #8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4669:18)
I/flutter (15306): #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4513:35)
I/flutter (15306): #10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2974:5)
```

**Comment by devoncarew** [comment] 2018-07-18 15:51
I don't think this is Inspector related - I think the toggling the platform setting is either tickling a bug in the framework, or violating some expectation. I think `framework` is the right area here.

**Comment by zoechi** [comment] 2018-09-07 11:55
#16560 looks similar

**Comment by zoechi** [comment] 2018-12-10 15:54
Duplicate of #24029 (has most activity and information)

**Closed by zoechi** 2018-12-10 15:54 UTC
Labels: framework, severe: crash
