### ISSUE TITLE
Navigator pop parameter can not be String

### ISSUE THREAD

**Issue by hongwei78** [flutter/flutter#87262] opened 2021-07-29 09:15 UTC
Navigator.of(context).pop('cart');
It's not worked.

**Expected results:** 
page closed

**Actual results:** 
Unhandled Exception: type 'String' is not a subtype of type 'bool?' of 'result'
Navigator pop not work 

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'String' is not a subtype of type 'bool?' of 'result'
#0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
#1      _RouteEntry.pop 
package:flutter/…/widgets/navigator.dart:3085
#2      NavigatorState.pop 
package:flutter/…/widgets/navigator.dart:5077
#3      GoodsDetailPage.detailBottom.<anonymous closure>.<anonymous closure> 
package:igocctv/…/goods/goodsdetail_page.dart:391
#4      GoodsDetailPage.detailBottom.<anonymous closure>.<anonymous closure> 
package:igocctv/…/goods/goodsdetail_page.dart:388
#5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:989
#6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#7      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:607
#8      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:296
#9      BaseTapGestureRecognizer.<…>

Flutter 2.2.3
flutter/packages/flutter/lib/src/widgets/routes.dart
line 636:  bool didPop(T? result) {
T's type is bool,is not String

**Comment by maheshmnj** [comment] 2021-07-29 09:47
Hi @hongwei78, 
Thanks for filing the issue, Please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by navaronbracke** [comment] 2021-07-29 10:48
`NavigatorState.pop()` has a type parameter. Did you provide String as the type parameter? According to the error, the type is bool (pop() takes a nullable type, hence the error reports bool?)

**Comment by maheshmnj** [comment] 2021-07-29 12:56
From the error, I believe you are passing incorrect type at someplace, Could you please provide a minimal code sample that you are having issue with to better address this issue?

ps: If you run the code sample above you would see it working without any errors.

**Comment by maheshmnj** [comment] 2021-07-30 05:14
@navaronbracke, yes I did pass a string, Most probably the type requires `bool?` and you are passing a `bool` could you please share your sample code so that I can understand what the actual issue is?

**Comment by hongwei78** [comment] 2021-08-02 03:25
> Hi @hongwei78,
> Thanks for filing the issue, I believe you are trying to return a string on pop, If so could you please try this code sample
> 
> code sample
> ```
> import 'package:flutter/material.dart';
> import 'dart:async';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>         title: 'Flutter Demo',
>         theme: ThemeData(primarySwatch: Colors.blue),
>         home: Popview(title: 'title'));
>     //  MyHomePage(title: 'App title'));
>   }
> }
> 
> class Popview extends StatefulWidget {
>   const Popview({Key? key, required this.title}) : super(key: key);
> 
>   final String title;
>   @override
>   _PopviewState createState() => _PopviewState();
> }
> 
> class _PopviewState extends State<Popview> {
>   String stringFromActivity = 'Send Data on Pop';
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             Text(
>               stringFromActivity,
>               style: const TextStyle(fontSize: 20.0),
>               textAlign: TextAlign.center,
>             ),
>             Container(
>               height: 20.0,
>             ),
>             ElevatedButton(
>               child: const Text('tap me'),
>               onPressed: () => _push(),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> 
>   Future _push() async {
>     String results = await Navigator.of(context)
>         .push(MaterialPageRoute(builder: (BuildContext context) {
>       return SecondScreen();
>     }));
> 
>     if (results != null) {
>       setState(() {
>         print('Data received on pop $results');
>       });
>     }
>   }
> }
> 
> class SecondScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Selecte Smily'),
>       ),
>       body: ListView.builder(
>         itemBuilder: (context, i) {
>           return ListTile(
>             title: Text('item $i'),
>             onTap: () {
>               Navigator.of(context).pop('SEND THIS');
>             },
>           );
>         },
>         itemCount: 20,
>       ),
>     );
>   }
> }
> ```
> 
> if you are still facing the issue, then please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.
> 
> Thank you.

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:async';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        onGenerateRoute: Router.generateRoute,
        initialRoute: RouteName.first,
        theme: ThemeData(primarySwatch: Colors.blue),
        home: Popview(title: 'title'));
    //  MyHomePage(title: 'App title'));
  }
}

class Popview extends StatefulWidget {
  const Popview({Key? key, required this.title}) : super(key: key);

  final String title;
  @override
  _PopviewState createState() => _PopviewState();
}

class _PopviewState extends State<Popview> {
  String stringFromActivity = 'Send Data on Pop';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              stringFromActivity,
              style: const TextStyle(fontSize: 20.0),
              textAlign: TextAlign.center,
            ),
            Container(
              height: 20.0,
            ),
            ElevatedButton(
              child: const Text('tap me'),
              onPressed: () => _push(),
            )
          ],
        ),
      ),
    );
  }

  Future _push() async {
    Object? results = await Navigator.of(context).pushNamed(RouteName.second);

    if (results != null) {
      setState(() {
        print('Data received on pop $results');
      });
    }
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Selecte Smily'),
      ),
      body: ListView.builder(
        itemBuilder: (context, i) {
          return ListTile(
            title: Text('item $i'),
            onTap: () {
              Navigator.of(context).pop('SEND THIS');
            },
          );
        },
        itemCount: 20,
      ),
    );
  }
}

class RouteName {
  static const String first = 'first';
  static const String second = 'second';
}

class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case RouteName.first:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: 'first'),
            builder: (_) => Popview(
                  title: 'first',
                ));
      case RouteName.second:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: settings.name),
            builder: (_) => SecondScreen());
      default:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: settings.name),
            builder: (_) => Scaffold(
                  body: Center(
                    child: Text('No route defined for ${settings.name}'),
                  ),
                ));
    }
  }
}

/// Pop路由
class PopRoute extends PopupRoute {
  PopRoute({required this.child});

  Widget child;

  final Duration _duration = Duration(milliseconds: 300);

  @override
  Color? get barrierColor => null;

  @override
  bool get barrierDismissible => true;

  @override
  String? get barrierLabel => null;

  @override
  Duration get transitionDuration => _duration;

  @override
  Widget buildPage(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation) {
    return child;
  }
}
`

this code can show the error.

**Comment by hongwei78** [comment] 2021-08-02 03:40
Hi @maheshmnj 
Thank you for your reply.
I tried your sample code is worked, but I need rewirte router, so I change the code sample and the issue can be repeated.

<details>
<summary>code sample</summary>

import 'package:flutter/cupertino.dart';

import 'package:flutter/material.dart';

import 'dart:async';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        onGenerateRoute: Router.generateRoute,
        initialRoute: RouteName.first,
        theme: ThemeData(primarySwatch: Colors.blue),
        home: Popview(title: 'title'));
    //  MyHomePage(title: 'App title'));
  }
}

class Popview extends StatefulWidget {
  const Popview({Key? key, required this.title}) : super(key: key);

  final String title;
  @override
  _PopviewState createState() => _PopviewState();
}

class _PopviewState extends State<Popview> {
  String stringFromActivity = 'Send Data on Pop';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              stringFromActivity,
              style: const TextStyle(fontSize: 20.0),
              textAlign: TextAlign.center,
            ),
            Container(
              height: 20.0,
            ),
            ElevatedButton(
              child: const Text('tap me'),
              onPressed: () => _push(),
            )
          ],
        ),
      ),
    );
  }

  Future _push() async {
    Object? results = await Navigator.of(context).pushNamed(RouteName.second);

    if (results != null) {
      setState(() {
        print('Data received on pop $results');
      });
    }
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Selecte Smily'),
      ),
      body: ListView.builder(
        itemBuilder: (context, i) {
          return ListTile(
            title: Text('item $i'),
            onTap: () {
              Navigator.of(context).pop('SEND THIS');
            },
          );
        },
        itemCount: 20,
      ),
    );
  }
}

class RouteName {
  static const String first = 'first';
  static const String second = 'second';
}

class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case RouteName.first:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: 'first'),
            builder: (_) => Popview(
                  title: 'first',
                ));
      case RouteName.second:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: settings.name),
            builder: (_) => SecondScreen());
      default:
        return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: settings.name),
            builder: (_) => Scaffold(
                  body: Center(
                    child: Text('No route defined for ${settings.name}'),
                  ),
                ));
    }
  }
}

/// Pop路由
class PopRoute extends PopupRoute {
  PopRoute({required this.child});

  Widget child;

  final Duration _duration = Duration(milliseconds: 300);

  @override
  Color? get barrierColor => null;

  @override
  bool get barrierDismissible => true;

  @override
  String? get barrierLabel => null;

  @override
  Duration get transitionDuration => _duration;

  @override
  Widget buildPage(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation) {
    return child;
  }
}

</details>

**Comment by maheshmnj** [comment] 2021-08-02 05:27
@hongwei78 thanks for the complete reproducible code I checked your code the issue is that the type is mismatched 

You are expecting the CupertinoPageRoute to take bool here `<bool>`
```
return CupertinoPageRoute<bool>(
            settings: RouteSettings(name: 'first'),
            builder: (_) => Popview(
                  title: 'first',
                ));
```

And while popping the widget you are passing a String 
```
onTap: () {
              Navigator.of(context).pop('SEND THIS'); /// either pass a boolean value or changing the type in CupertinoPageRoute to String.
            },
```            
You have to make sure both types are the same. Feel free to comment if you need any further clarification, Closing this issue as invalid if you disagree please comment with your reasoning and I will reopen it.
Thank you.

**Closed by maheshmnj** 2021-08-02 05:27 UTC
Labels: in triage
