### ISSUE TITLE
Add footer Widget property to ReorderableListView

### ISSUE THREAD

**Issue by DebugTheCode** [flutter/flutter#60987] opened 2020-07-07 13:30 UTC
## Use case

I would like to suggest the following: add a `header` like property, but instead being a non-reorderable top `Widget` in the list, a non-reorderable bottom `Widget` in the list.

## Proposal
So I propose to add a `footer` property to `ReorderableListView`

**Comment by TahaTesser** [comment] 2020-07-07 13:33
duplicate of https://github.com/flutter/flutter/issues/21195

**Closed by TahaTesser** 2020-07-07 13:33 UTC

**Comment by DebugTheCode** [comment] 2020-07-07 13:34
@TahaTesser thanks, I was too fast. Sorry.
