### ISSUE TITLE
use Isolate increase double memory

### ISSUE THREAD

**Issue by HXiaoMing** [flutter/flutter#136864] opened 2023-10-19 05:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

source code:

https://github.com/HXiaoMing/memory_profile_issue.git

1.run profile mode
![image](https://github.com/flutter/flutter/assets/22089782/4909e541-60cf-463d-9650-c7df51d99988)

2.open flutter DevTools, switch to memory chart.
![image](https://github.com/flutter/flutter/assets/22089782/bf46ce75-4afc-46b3-a2fd-c7892cbd91f0)

3.click [startIsolate] button, memory chart increase double memory.
![image](https://github.com/flutter/flutter/assets/22089782/09bd1969-2079-49ba-8126-96315ef74163)

before click [startIsolate]:
RSS 184.91MB 
Allocated 57.54MB 
Dart/Flutter 40.14MB 
Dart/Flutter Native 0.3KB
![image](https://github.com/flutter/flutter/assets/22089782/a6917d70-4e92-403a-9648-2b07bb1b4452)

after click [startIsolate]:
RSS 189.14MB 
Allocated 115.11MB 
Dart/Flutter 82.80MB 
Dart/Flutter Native 20.8KB
![image](https://github.com/flutter/flutter/assets/22089782/5dd393d7-f53b-4dc3-b442-47936a37bb8e)

3.click [closeIsolate] button, isolate memory release.

![image](https://github.com/flutter/flutter/assets/22089782/cde46aa5-d1d3-45c3-a11b-180799436ebd)

### Expected results

after click [startIsolate] button, memory will increase 30 kb?

![image](https://github.com/flutter/flutter/assets/22089782/15ffb652-2e80-4a20-9488-531ebf1f11e1)

### Actual results

after click [startIsolate] button, memory chart increase double memory. it is too terrible.

RSS 184.91MB  -> 189.14MB
Allocated 57.54MB -> 115.11MB
Dart/Flutter 40.14MB -> 82.80MB
Dart/Flutter Native 0.3KB -> 20.8KB

![image](https://github.com/flutter/flutter/assets/22089782/b92af0f1-d37e-41b9-9b64-f9f7b5faec57)

### Code sample

source code:

https://github.com/HXiaoMing/memory_profile_issue.git

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

tt@ttdeMac-mini-2 flutterGithub % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.3 22E252 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.6 on channel stable at /Users/tt/tech/flutter/flutter_3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tt/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • 22081212C (mobile) • 22f5cad5 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)    • macos    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment] 2023-10-19 09:18
Thanks for the report. Reproduced this issue on the latest stable/master channels (verified on Android and macOS platforms).

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.13.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (11 hours ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.16.0-13.0.pre.43, on macOS 14.0 23A344 darwin-x64, locale en-VN)
    • Flutter version 3.16.0-13.0.pre.43 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c881808ed2 (50 minutes ago), 2023-10-19 02:20:19 +0000
    • Engine revision 8d51b64e94
    • Dart version 3.3.0 (build 3.3.0-41.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Giraffe.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by mraleph** [comment] 2023-10-19 09:33
I would suspect accounting / display issue in DevTools (e.g. counting each isolate memory usage and not each isolate group memory usage). Note how RSS does *not* actually increase by 40Mb. The comment in the docs is correct - `Isolate.spawn` has base memory overhead measured in hundreds of kilobytes.

**Comment by HXiaoMing** [comment] 2023-10-20 02:31
> I would suspect accounting / display issue in DevTools (e.g. counting each isolate memory usage and not each isolate group memory usage). Note how RSS does _not_ actually increase by 40Mb. The comment in the docs is correct - `Isolate.spawn` has base memory overhead measured in hundreds of kilobytes.

I agree with your viewpoint. but start an isolate, RSS 184.91MB increase 189.14MB is to be expected?

**Comment by mraleph** [comment] 2023-10-20 07:01
Well some increase is expected - though I would recommend just profiling it using external tools rather than Dev Tools  (because service server is running in the same process as your application it will affect memory usage of the app). So build `--release` build and then use `adb shell dumpsys meminfo` to get memory information instead.

**Comment by chinmaygarde** [comment] 2023-10-23 18:21
Closing this as the resident set increases are as expected.

**Closed by chinmaygarde** 2023-10-23 18:21 UTC
Labels: engine, dependency: dart, perf: memory, has reproducible steps, team-engine, found in release: 3.13, found in release: 3.16
