### ISSUE TITLE
[proposal] provide a way to prevent DataRow to receive focus

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#74022] opened 2021-01-15 06:48 UTC
i have a DataTable and added textfield in each cell. i have two columns and three rows . when i press tabkey its not working properly or when i use up and down arrow key it not work properly

**Comment by pedromassangocode** [comment] 2021-01-15 09:55
Hi @abdulrehmananwar 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by abdulrehmananwar** [comment] 2021-01-15 10:37
D:\tag\flutter_datatable>flutter doctor -v
[√] Flutter (Channel master, 1.26.0-2.0.pre.365, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-2.0.pre.365 at D:\flutter
    • Framework revision 9209319dd1 (2 hours ago), 2021-01-15 14:34:03 +0530
    • Engine revision efa768683e
    • Dart version 2.12.0 (build 2.12.0-225.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

--- below is source code

import 'package:flutter/material.dart';
void main() => runApp(MyApp());
/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatelessWidget(),
      ),
    );
  }
}
/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return DataTable(
      columns: const <DataColumn>[
        DataColumn(
          label: Text(
            'Name',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Qty',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
      ],
      rows: const <DataRow>[
        DataRow(
          cells: <DataCell>[
            DataCell(
            TextField(
            )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
      ],
    );
  }
}

**Comment by abdulrehmananwar** [comment] 2021-01-15 10:42
issue #1   tab key press 2 times instead 1 time for focus to next widget.
issue #2  up and down keys i want to move focus to up row and down row.

**Comment by pedromassangocode** [comment] 2021-01-15 13:01
I was able to reproduce this issue.

> issue #1 tab key press 2 times instead 1 time for focus to next widget.

This is caused by the `TableRowInkWell` used by `DataRow` , it catch the focus that is supposed to be forwarded to the second TextField. To avoid breaking changes, this should be fixed by exposing the `canRequestFocus` from TableRowInkWell to DataCell so that users can set it to `false` to avoid it from receiving focus.

> issue #2 up and down keys i want to move focus to up row and down row.

For this, please open a new issue. We don't track more than one issue in the same place since they are expected to be fixed in different places and PRs.

<details>
<summary>flutter doctor -v</summary>

```bash
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.364, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.364 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision fb9e485dd8 (6 hours ago), 2021-01-15 01:39:02 -0500
    • Engine revision efa768683e
    • Dart version 2.12.0 (build 2.12.0-225.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by abdulrehmananwar** [comment] 2021-01-16 06:05
Thanks for your kind response. kindly please share some piece of code to resolve issue #1 thanks

**Comment by ThijsBoudrez** [comment] 2021-03-20 22:12
> I was able to reproduce this issue.
> 
> > issue #1 tab key press 2 times instead 1 time for focus to next widget.
> 
> This is caused by the `TableRowInkWell` used by `DataRow` , it catch the focus that is supposed to be forwarded to the second TextField. To avoid breaking changes, this should be fixed by exposing the `canRequestFocus` from TableRowInkWell to DataCell so that users can set it to `false` to avoid it from receiving focus.
> 

How to achieve this?
Related: https://github.com/flutter/flutter/issues/72879#issue-773915406

**Closed** 2021-04-20 18:10 UTC
Labels: f: material design, framework, passed first triage, proposal, severe: new feature
