### ISSUE TITLE
Web: HTML page touch handling broken when using embedding

### ISSUE THREAD

**Issue by dowski** [flutter/flutter#159083] opened 2024-11-18 16:58 UTC
### Steps to reproduce

1. Follow the [official instructions](https://docs.flutter.dev/platform-integration/web/embedding-flutter-web#embedded-mode) to embed Flutter on a web page
2. Deploy the site with embedded Flutter widgets
3. Try to use the site on a mobile device

### Expected results

I expect that the page will function normally on mobile browsers.

### Actual results

Other than the Flutter widget on the page, no other elements respond to touch interactions. This includes selecting text, pressing buttons, etc. The issue repros on both Chrome and Firefox mobile on my real Android device and also in Chrome on an Android emulator.

### Code sample

<details open><summary>Code sample</summary>

I created a Github repo with a sample app that demonstrates the issue.

https://github.com/dowski/web_embedding_mobile_bug

Clone that repo and then:

1. `cd web_embedding_mobile_bug`
2. `flutter build web`
3. `cd build/web`
4. `python -m http.server 8080`

You'll need to open the page in a mobile browser - there is no issue using the page on desktop. You can use a real device on the same local network as the machine hosting the page or an Android emulator on that machine pointing to `http://10.0.2.2:8080`.
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

No interesting log output.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale
    en-US)
    • Flutter version 3.24.4 on channel stable at
      /Users/christian/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (4 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/christian/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  •
      Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dowski** [comment] 2024-11-18 17:12
I think this might have been reported previously in https://github.com/flutter/flutter/issues/152838 which was closed.

**Comment by dowski** [comment] 2024-11-18 17:57
A really weird aspect of this bug - if you tap on the HTML button repeatedly, on the 22nd tap, the touch will be handled ... 🤯 That's repeatable across page reloads. It also repros on the site I was working on where I first noticed this bug.

Another thing I noticed on the site where I first encountered this - if I move the Flutter element "below the fold" such that I have to scroll down to get to it, the bug doesn't happen.

**Comment by dowski** [comment] 2024-11-18 19:45
Okay, I found a workaround. I added a DOM breakpoint in the Chrome DevTools for modifications to the `body` element. I noticed after the 21st click, the `flt-semantics-placeholder` was getting removed. I did a google search for that which led me to https://github.com/flutter/flutter/issues/54647.

After reading about the workaround in that issue, I added this hack to my TypeScript/JavaScript code:

```typescript
document.querySelector("flt-semantics-placeholder")?.remove();
```

Touch interactions are no longer blocked.

**Comment by darshankawar** [comment] 2024-11-19 06:08
Thanks for the report @dowski 
It mostly is a duplicate of https://github.com/flutter/flutter/issues/149002. A workaround is as mentioned [here](https://github.com/flutter/flutter/issues/156491#issuecomment-2436043975).  I will close in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-11-19 06:08 UTC
Labels: in triage
