### ISSUE TITLE
Flutter, TextFormField, onFieldSubmitted syntax behaviour

### ISSUE THREAD

**Issue by joedonchev** [flutter/flutter#117206] opened 2022-12-16 08:49 UTC
Unexpected behaviour of onFieldSubmitted, based on 2 different syntax.

1. This works on press Enter on a physical keyboard:
`onFieldSubmitted: (String value){
     _submit();
},`

2. This does not work on press Enter on a physical keyboard:
`onFieldSubmitted: (String value) => _submit,`

Flutter version 3.3.5

**Comment by exaby73** [comment] 2022-12-16 09:14
Hello @joedonchev. You can fix this with this syntax:

```dart
onFieldSubmitted: (value) => _submit(),
```

This is expected as you are returning a reference to the `_submit` function and not actually calling it. Closing this issue as this is not a bug with Dart/Flutter. Thank you

**Closed by exaby73** 2022-12-16 09:14 UTC
Labels: in triage
