### ISSUE TITLE
Unable to open extrenal app.

### ISSUE THREAD

**Issue by Ghoral** [flutter/flutter#95397] opened 2021-12-16 12:22 UTC
I am unable to open external app from url. Works perfectly in versions previous than  Android 12, but facing issue in android 12.

**Comment by maheshmnj** [comment] 2021-12-16 13:03
Hi @Ghoral  it would be great if you can update the issue description to clearly describe the issue along with  the output of `flutter doctor -v` and steps to reproduce the issue.

**Comment by Ghoral** [comment] 2021-12-16 13:44
Hi,
I have added this on Android.xml
`<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
			<intent-filter android:autoVerify="true">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https" />
			</intent-filter>`
I wanted to open google class on button click.
if goolge class is not installed than go to web else open the app.

this is my google class function 
`launch('https://classroom.google.com/u/0/h', )

flutter doctor report -> 
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale
    en-NP)
    • Flutter version 2.8.0 at /Applications/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/myname/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Users/my namel/Downloads/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      96.0.4664.110

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment] 2021-12-17 04:11
Thanks for the info @Ghoral.

> `launch('https://classroom.google.com/u/0/h', )

This link will mainly launch the URL in the browser because of the HTTPS scheme and if that URL is valid deep link URL then it will launch the app associated with that URL if it is installed. I am not sure if that is a valid URL scheme you should be using, probably you should ask this question on StackOverflow and you might find an answer. There is nothing URL launcher can do about it. Closing as this issue doesn't seem to describe a bug or a feature request.

Thank you.

**Closed by maheshmnj** 2021-12-17 04:11 UTC
Labels: in triage
