### ISSUE TITLE
crash on windows-x64

### ISSUE THREAD

**Issue by gnf** [flutter/flutter#34141] opened 2019-06-10 00:31 UTC
## Steps to Reproduce

1. Run desktop example on windows-x64 platform
2. Minimize the window
3. Crash occurs

## Logs

```
```

```
```

```
```

**Comment by gnf** [comment] 2019-06-10 00:36
[fix_issues_34141.patch.txt](https://github.com/flutter/flutter/files/3270166/fix_issues_34141.patch.txt)
I tried to fix it briefly.

**Comment by stuartmorgan** [comment] 2019-06-10 03:04
Duplicate of #30668

**Closed by stuartmorgan** 2019-06-10 03:04 UTC
Labels: e: desktop, ❖ platform-windows
