### ISSUE TITLE
Issue with unzipping .zip file while running the application

### ISSUE THREAD

**Issue by GuptaTanay** [flutter/flutter#19166] opened 2018-07-09 14:56 UTC
I am quite new to flutter, just started today and installed flutter zip and was coding with Visual studio code and made a Hello World app.
When I run hello world app, it shows me an error pasted below:

E:\Flutter Projects\flutter_one>flutter run
Launching lib/main.dart on Lenovo A6000 in debug mode...
Initializing gradle...                                          /
Oops; flutter has exited unexpectedly: "Exit code 1 from: E:\Flutter Projects\flutter_one\android\gradlew.bat -v:
Deleting directory C:\Users\Tanay Gupta\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1
Unzipping C:\Users\Tanay Gupta\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip to C:\Users\Tanay Gupta\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.io.FileNotFoundException: C:\Users\Tanay Gupta\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1\lib\native-platform-windows-i386-0.14.jar (The process cannot access the file because it is being used by another process)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.gradle.wrapper.Install.unzip(Install.java:227)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".
Sending crash report to Google.
Crash report sent (report ID: 69b217f9f2ec266d)
Crash report written to E:\Flutter Projects\flutter_one\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.

I have also tried to download another zip file and unzip it manually but same error is popping up.
Please help me, I have a deadline to complete the project in 2 days.

**Comment by GuptaTanay** [comment] 2018-07-09 14:57
flutter doctor command:


E:\Flutter Projects\flutter_one>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.25.0)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by GuptaTanay** [comment] 2018-07-09 14:57
flutter doctor -v command:

E:\Flutter Projects\flutter_one>flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
    • Flutter version 0.5.1 at C:\flutter\flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\Tanay Gupta\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Lenovo A6000 • 3a14488 • android-arm64 • Android 5.0.2 (API 21)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment] 2018-07-10 08:08
Could be caused by the space in the user name `Tanay Gupta.gradle`

**Comment by Tynoe** [comment] 2018-08-09 16:52
Hello new to Flutter too. i have been trying to solve this issuer to no resolve...tried all possible solutions but still getting this 

$ flutter install (or run)
Initializing gradle...                                          \
Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\code\tinology\android\gradlew.bat -v:
Unzipping C:\Users\Tynoe\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip
to C:\Users\Tynoe\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".
Sending crash report to Google.


$ flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.125], locale en-US)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.2.2 (API 17) (emulator)

! Doctor found issues in 1 category.

has anyone one came across such?

**Comment by zoechi** [comment] 2018-09-03 07:56
Closing as dup of #15721
Please upvote and follow there.

**Closed by zoechi** 2018-09-03 07:56 UTC
Labels: severe: crash, t: gradle, tool
