### ISSUE TITLE
Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74202] opened 2021-01-18 19:59 UTC
platform_views_scroll_perf_ios__timeline_summary is failing consistently in ios14.2 and xcode 12.3:

```
♦ /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Flutter.framework/Flutter -r -o /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             ♦ codesign --force --verbose --sign 586F97A3FD6A22CEA961BD998E8F935D80B3CF5E -- /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Runner.app/Frameworks/App.framework/App
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (arm64) [io.flutter.flutter.app]
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             ♦ codesign --force --verbose --sign 586F97A3FD6A22CEA961BD998E8F935D80B3CF5E -- /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             /opt/s/w/ir/cache/flutter sdk/dev/benchmarks/platform_views_layout/build/ios/Profile-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 arm64) [io.flutter.flutter]
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout: 
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout: 
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             ** BUILD FAILED **
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout: 
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout: 
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             The following build commands failed:
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             	PhaseScriptExecution Thin\ Binary /Users/swarming/Library/Developer/Xcode/DerivedData/Runner-einjmwmtmclywafwhebewyeryzaa/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh
[platform_views_scroll_perf_ios__timeline_summary] [STDOUT] stdout:             (1 failure)
```

**Comment by godofredoc** [comment] 2021-01-18 19:59
Link to a build:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20platform_views_scroll_perf_ios__timeline_summary/215

Link to list of builds:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20platform_views_scroll_perf_ios__timeline_summary

**Comment by godofredoc** [comment] 2021-01-18 20:00
\cc @xster @jmagman

**Comment by jmagman** [comment] 2021-01-19 19:02
We have some user reports of this, which were duped to https://github.com/flutter/flutter/issues/70422.

**Comment by godofredoc** [comment] 2021-01-19 19:33
I closed https://github.com/flutter/flutter/issues/70422 because I thought it was fixed when the test execution step was being nooped and marking everything green.

**Comment by jmagman** [comment] 2021-01-19 19:34
I'm going to re-open that one since users duplicated to it may already be subscribed.
Closing as duplicate of https://github.com/flutter/flutter/issues/70422.

**Closed by jmagman** 2021-01-19 19:34 UTC
Labels: passed first triage, team, team: infra
