### ISSUE TITLE
[web] Appearance is different when using Column and ListView (ListView is more "blurry")

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#62291] opened 2020-07-26 11:28 UTC
Hello,

I did not find anything in documentation regarding it, so I am assuming it can be a bug.

## Steps to Reproduce

Using for instance divider in Column and in ListView in flutter web.

**Expected results:** 

Same appearance.

**Actual results:** 

This is using Text and Divider in ListView (not preferable appearance):

![ListView appearance](https://user-images.githubusercontent.com/54472480/88477796-4d9b4000-cf43-11ea-8bf3-75cc817f6916.PNG)

This is using Text and Divider in Column (preferable appearance):

![Column appearance](https://user-images.githubusercontent.com/54472480/88477798-4f650380-cf43-11ea-966c-bebde264b476.PNG)

<details>
  <summary>Flutter doctor</summary>

[√] Flutter: is fully installed. (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.18362.959], locale pl-PL)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[√] Chrome - develop for the web: is fully installed.
[√] Android Studio: is fully installed. (version 3.5)
[√] Connected device: is fully installed. (3 available)

</details>

**Comment by pedromassangocode** [comment] 2020-07-27 11:00
Hi @mordivgor 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you

**Comment by mordivgor** [comment] 2020-07-27 19:48
Hi @pedromassango ,
Good point :)
Looks like the problem is with Container when it has Border defined (if no Border, then we have always 'blurry' behavior).

<details>
 <summary> Example </summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          color: Colors.white,
          border: Border.all(
            color: Colors.grey,
            width: 0.5
          ),
        ),
        child: _fine()
      )
    );
  }

  Widget _wrong() {
    return ListView.builder(
      scrollDirection: Axis.vertical,
      shrinkWrap: true,
      itemCount: 2,
      itemBuilder: (context, index) {
        return Column(
          children: [
            _divider(),
            Text('Lorem ipsum')
          ],
        );
      },
    );
  }

  Widget _fine() {
    List<Widget> _tiles = [];
    for (int i = 0; i < 2; i++) {
      _tiles.add(_divider());
      _tiles.add(Text('Lorem ipsum'));
    }
  
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: _tiles
    );
  }

    Widget _divider() {
    return Divider(
      color: Colors.grey[400],
      endIndent: 24.0,
      indent: 24.0,
      thickness: 1.0,
    );
  }
}
```
</details>

**Comment by pedromassangocode** [comment] 2020-07-28 07:44
I was able to reproduce in `1.21.0-1.0.pre`.

Looks like there is two issues here: the `Border` in the `Container` is making the text "blurry" and the `Divider` looks different when placed in a `ListView` or `Column`.

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (13 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by movieator** [comment] 2020-08-07 11:10
Hi, same issue for me in master channel. 

Flutter doctor -v:

> [√] Flutter (Channel master, 1.21.0-6.0.pre.142, on Microsoft Windows [Version 10.0.18362.720], locale el-GR)
    • Flutter version 1.21.0-6.0.pre.142 at C:\src\flutter
    • Framework revision d261f1ef58 (4 days ago), 2020-08-03 00:59:36 -0400
    • Engine revision 083282e33b
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 365525432a)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Panos\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Panos\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0
[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

**Comment by markusaksli-nc** [comment] 2020-09-10 07:04
It looks like layout can somehow make the text blurry in general (this affects the AppBar title as well).

Tested on the latest master `1.22.0-10.0.pre.121`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.121, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.121 at C:\Development\flutter_master
    • Framework revision 6c1a29e54c (6 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>
<details>
 <summary>Code sample from #65484</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: ListView(
          children: [
            Text(
              'Sample Text', // rendered by DomCanvas
              style: TextStyle(fontSize: 24),
            ),
            Row(
              children: [
                // rendered by BitmapCanvas
                Text(
                  'Sample Text',
                  style: TextStyle(
                    fontSize: 24,
                  ),
                ),
                SizedBox(
                  width: 100,
                  child: TextFormField(
                    maxLines: null,
                    style: TextStyle(fontSize: 24),
                  ),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}
```
</details>

![image](https://user-images.githubusercontent.com/68219924/92692381-be0fec00-f34c-11ea-9fd9-f20122237a27.png)

I see that https://bugs.chromium.org/p/chromium/issues/detail?id=1040222 is still open and I can only repro this on Chromium browsers (Chrome, new Edge). I'm assuming this means that https://github.com/flutter/engine/pull/15649 didn't fix this in all cases?

The browser scale effect from https://github.com/flutter/flutter/issues/60442 applies here as well and https://github.com/flutter/flutter/issues/58159 should be related.

**Comment by mizuirot** [comment] 2020-09-10 14:15
Hi @markusaksli-nc 
Thank you for your advice,

I can't reproduce this issue with sample code by @mordivgor ..
but my sample code is still replicable.

Firefox in my environment has a little different rendering. ( BitmapCanvas is just a little blurry)

<img width="287" alt="capture_of_firefox" src="https://user-images.githubusercontent.com/69755373/92742432-93f51300-f3ba-11ea-8af0-ae16712ba41d.png">

![image](https://user-images.githubusercontent.com/69755373/92742565-b7b85900-f3ba-11ea-83c1-d12c8e28322b.png)


<details>
<summary>code</summary>

```
class MyHomePage extends StatelessWidget {
  MyHomePage({String title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample Text'),
      ),
      body: ListView(
        children: [
          Text(
            'Sample Text', // rendered by DomCanvas
            style: TextStyle(fontSize: 24),
          ),
          Row(
            children: [
              Text('Sample Text',
                  style: TextStyle(fontSize: 24)), // rendered by BitmapCanvas
              SizedBox(
                width: 100,
                child: TextFormField(
                  maxLines: null,
                  style: TextStyle(fontSize: 24),
                ),
              )
            ],
          )
        ],
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.109, on Microsoft Windows [Version 10.0.19041.508], locale ja-JP)
    • Flutter version 1.22.0-10.0.pre.109 at C:\tools\flutter
    • Framework revision e682ec711a (23 hours ago), 2020-09-09 10:52:27 +0200
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 2 categories.
```
</details>

Thanks,

**Comment by darshankawar** [comment] 2022-11-08 12:20
Verified this issue using latest versions and confirmed that the reported behavior is not replicable using any of the code sample provided above.

<img width="431" alt="Screenshot 2022-11-08 at 5 43 57 PM" src="https://user-images.githubusercontent.com/67046386/200562106-282fec92-6d5a-4601-af02-17b2c602e3bc.png">
<img width="1001" alt="Screenshot 2022-11-08 at 5 46 02 PM" src="https://user-images.githubusercontent.com/67046386/200562113-cd432939-d473-4c9f-ae37-2b2e896e6799.png">
<img width="1199" alt="Screenshot 2022-11-08 at 5 47 46 PM" src="https://user-images.githubusercontent.com/67046386/200562116-855ec0a2-3c6d-4c2d-9b24-3c11c0896c6c.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.5.0-12.0.pre.168, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.168 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1432a9c5d (4 hours ago), 2022-11-07 19:17:03 -0600
    • Engine revision e7d7edab98
    • Dart version 2.19.0 (build 2.19.0-374.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing this as fixed.

**Closed by darshankawar** 2022-11-08 12:20 UTC
Labels: framework, a: typography, platform-web, e: web_html, has reproducible steps, P4, found in release: 1.20, found in release: 1.21, found in release: 1.22
