### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Das System kann die angegebene Datei nicht finden., errno = 2

### ISSUE THREAD

**Issue by kuntergunt** [flutter/flutter#125487] opened 2023-04-25 12:36 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. Follow the Flutter "Get Started" procedure
2. Use Visual Studio Code, as recommended
3. Proceed until step 3: Test Drive, which creates your first flutter app -> error, cannot create directory "lib"
4. Do it again in a VSC command prompt, same error
5. Create the directory "lib" and run again, -> again error, this time cannot create file "lib\main.dart" 
6. Delete directory "lib"
7. Run again, this time success!

I am posting this to help you fix this issue, though I somehow finally had success.
My user directory does not have any spaces or special characters.
I did not do any fixes, just tried to narrow down the error. At the end I would suggest the system was in the same state as in the beginning. But suddenly it succeeded. Strange behaviour.

I also tried to execute the command "flutter create --template app --overwrite .  " from command prompt, because by default VSC uses Powershell. But I got to the same result.

## Logs
FileSystemException: Cannot create file, OS Error: Das System kann die angegebene Datei nicht finden.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.createSync (dart:io/file_impl.dart:289:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:287:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:286:5)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:288:28)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      Template.render (package:flutter_tools/src/template.dart:248:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:489:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:512:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:351:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1555], locale de-AT)
    [32m•[39m Flutter version 3.7.12 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4d9e56e694 (7 days ago), 2023-04-17 21:47:46 -0400
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[31m[✗][39m Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\...\AppData\Local\Android\sdk
    [32m•[39m Platform android-33-ext5, build-tools 33.0.2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    [32m•[39m Visual Studio Professional 2022 version 17.5.33516.290
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m VS Code (version 1.77.3)
    [32m•[39m VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.62.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.58

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by kuntergunt** [comment] 2023-04-25 12:41
Problems are not solved. Doing a Run -> Start Debuggung resulted in

Flutter failed to write to a file at "C:\Users\...\test\flutter\flutter_application_1\.dart_tool\dartpad\web_plugin_registrant.dart". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

Exited (1)

**Comment by darshankawar** [comment] 2023-04-25 12:56
Closing as a duplicate of https://github.com/flutter/flutter/issues/98066 (and may be https://github.com/flutter/flutter/issues/65242) based on original tool crash error log reported. Please follow-up in linked issues for further updates.

**Closed by darshankawar** 2023-04-25 12:56 UTC
Labels: in triage
