### ISSUE TITLE
DART FILES CORRUPTED on hot reload !!!

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#77601] opened 2021-03-08 15:09 UTC
flutter version 2.0.1 makes dart files 
 unreadable,undeletable,unrenamable,uncopyable,unmovable, etc ..
dev sys: win 10
editor: vs code latest version,
channel: stable

Steps to reprodoce: 
try to edit dart file,
press CTRL+s to save the file && press r to hot reload (as fast as possible)
, doing this many times will CORRUPT random dart file,
i am not sure it from vs code or flutter, but it wasn't happens in the past weeks with same vs code version ..

**Comment by TahaTesser** [comment] 2021-03-08 15:24
Hi @imeDevelopers 
When editing a new project's `main.dart` tons of times and doing `hot reload`, I see no issue

> unreadable,undeletable,unrenamable,uncopyable,unmovable, etc ..

There possibility that Antivirus detecting some odd behaviour and locking the files 
Please whitelist/disable the Antivirus for Flutter, Dart, project and related files and try again.

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45
• No issues found
```

</details>

Thank you

**Comment by imeDevelopers** [comment] 2021-03-08 15:29
@TahaTesser 
> There possibility that Antivirus detecting some odd behaviour and locking the files
> Please whitelist/disable the Antivirus for Flutter, Dart, project and related files and try again.

i've disabled firewall,anti virus,scanned my pc, fixed the drive, restarted my pc, the file is corrupted and it's the 3rd time this happens from two days ago ..

please create more than one file .. !
and import one of them in two or more files
out or inside folders inside lib

and try again,
thank you.

**Comment by TahaTesser** [comment] 2021-03-09 09:04
Hi @imeDevelopers 
I just tried multiple files, still can't see any in VS code on the latest `stable` on Windows 10

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • google sdk (mobile) • emulator-5554 • android-arm    • Android 4.3.1 (API 18) (emulator)
    • Windows (desktop)   • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)        • chrome        • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)          • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

</details>

Can you please provide your `flutter doctor -v` and `flutter run --verbose` with hot reload logs and errors if possible, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by imeDevelopers** [comment] 2021-03-14 08:48
What i mean of (as fast as possible) is to try making the compiler finds errors during there's no errors , just the VS Code saving the file .. , here is the problem ..

save the file & press r the compiler will tell you that there errors, but actually there's no errors ..

and this happens because the analyzer didn't yet analyzed the file..

the compiler tell me that there's errors in many imported files too , please try to make this situiation

**Comment by TomTruyen** [comment] 2021-03-15 11:41
@imeDevelopers if I understand correctly the issue seems to be that VS code detects issues in files that are not there. Like for example detecting imports as errors. I have had this issue with VS code a few times aswel. For me personally it usually happens after I do `flutter clean` You can usually fix it by doing:

 `flutter pub get`

in your terminal. This gets all the packages again and should fix the issue. Maybe it would also be a good idea to test your issue in Android Studio? This will at least rule out either Flutter as being the issue or VS Code, depending on the outcome.

**Comment by imeDevelopers** [comment] 2021-03-15 13:35
@TomTruyen of course this is not true,

i am very old developer so i know if its really pub problem or not ..

just try to press ctrl+s and during or before file being saved press r, the compiler will output errors ..

if you pressed r again everything will be fine ..,

the problem is in the first r , it damage my dart files ..

**Comment by TahaTesser** [comment] 2021-03-22 07:26
Hi @imeDevelopers 

> just try to press ctrl+s and during or before file being saved press r, the compiler will output errors ..

Doing exactly you said, I can see no errors in VS Code when hot reload on Android

<details> 
<summary>flutter doctor -v</summary> 

```bash
PS C:\Users\Taha> flutters doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 4d7946a68d (3 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45
• No issues found!
PS C:\Users\Taha>
```

</details>

Can you please make sure it's not a local issue on your setup, maybe reinstalling the flutter plugin?
Thank you
(Sorry for the delayed response I was on vacation)

**Comment by pedromassangocode** [comment] 2021-04-14 10:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-14 10:45 UTC
Labels: in triage, waiting for customer response
