### ISSUE TITLE
[WEB][Shared preferences] Data is cached even though it was cleared via Devtools (Local Storage)

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#115532] opened 2022-11-17 07:09 UTC
## Steps to Reproduce

1. Open the app on another tab
2. Clear Sharepreferences data on the 2nd tab
3. Go back to the 1st tab, the data is still available despite empty local storage

**Expected results:** Data is cleared on both tabs

**Actual results:** The data is still available despite empty local storage

https://user-images.githubusercontent.com/51567674/202379382-39ff7cea-0a87-4584-9b3a-93fb60b8f0bb.mov

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var text = '';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: [
              Text(text),
              const SizedBox(
                height: 10,
              ),
              TextButton(
                child: const Text('Save Shared Preference'),
                onPressed: () {
                  SharedPreferences.getInstance().then((pref) =>
                      pref.setString('TEST', 'THIS IS THE TEST DATA'));
                },
              ),
              const SizedBox(
                height: 10,
              ),
              TextButton(
                child: const Text('Show Shared Preference'),
                onPressed: () async {
                  final data = await SharedPreferences.getInstance()
                      .then((pref) => pref.getString('TEST'));
                  setState(() {
                    text = data ?? 'DATA IS CLEARED';
                  });
                },
              ),
              const SizedBox(
                height: 10,
              ),
              TextButton(
                child: const Text('Clear Shared Preference'),
                onPressed: () {
                  SharedPreferences.getInstance().then((pref) => pref.clear());
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel unknown, 3.0.5, on macOS 12.1 21C52 darwin-arm, locale en-VN)
    • Flutter version 3.0.5 at /Users/mht/flutter
    • Upstream repository unknown
    • Framework revision f1875d570e (4 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
                                                                                                                                                                                         Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mht/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

! Doctor found issues in 1 category.

```

</details>

**Comment by exaby73** [comment] 2022-11-17 12:37
## Triage report

I can reproduce this issue with `shared_preferences: ^2.0.15`. 

#### Steps to reproduce:

- Use the code sample OP provided in https://github.com/flutter/flutter/issues/115532#issue-1452832505
- Click on `Save Shared Preference`
- Open Chrome Devtools -> Application -> Local Storage and clear the data saved there
- Click on `Show Shared Preference` and notice that the previous data (which was previously saved in Local Storage) is retrieved.

**Comment by stuartmorgan** [comment] 2022-11-17 13:26
This is a slight variant of https://github.com/flutter/flutter/issues/101691; closing as a duplicate since it's caused by the same core behavior of the plugin.

**Closed by stuartmorgan** 2022-11-17 13:26 UTC
Labels: plugin, platform-web, p: shared_preferences, has reproducible steps, found in release: 3.3, found in release: 3.6
