### ISSUE TITLE
Unable to build signed APK or app bundle using CI or Terminal fails with Androidx and firestore issue

### ISSUE THREAD

**Issue by finkcloud** [flutter/flutter#69873] opened 2020-11-05 12:25 UTC
HERE IS MY ACTION FILE
// STARTS

```
name: EarlyReader PlayStore Release

on:
  push:
    branches: [master]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.3
        with:
          versionSpec: "5.2.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.3
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  build:
    name: Build APK and Create release
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.2"
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  release:
    name: Release app to internal track
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get appbundle from artifacts
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.philencripted.earlyread
          releaseFile: app-release.aab
          track: internal
          whatsNewDirectory: distribution/whatsnew


```

//ENDS

<details><summary>HERE IS MY PUB.YAML</summary>

```
name: EarlyRead
description: Story reading app for Kids by Philencripted solutions.

version: 99.99.99+99

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  intro_views_flutter: "^2.8.1"
  fluttertoast: ^7.0.2
  toast: ^0.1.5
  intent: ^1.4.0
  flutter_tts: 1.0.0
  flutter_paystack: "1.0.4+1"
  shared_preferences: "^0.4.2"
  url_launcher: ^5.4.2
  webview_flutter: ^0.3.20
  # firebase_auth: ^0.18.1+1

  # Add the dependency for the Firebase Core Flutter SDK
  # firebase_core: ^0.4.0+9
  # cloud_firestore: ^0.12.0+5
  # cloud_firestore: ^0.8.2+3
  firebase_core: "^0.5.0+1"
  cloud_firestore: "^0.14.1+3"
  # firebase_auth: ^0.15.3
  firebase_auth: "^0.18.1+2"
  google_sign_in: "^4.5.1"
  # google_sign_in: ^4.5.3

  # Add the dependency for the FlutterFire plugin for Google Analytics
  # firebase_analytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```
</details>

<details><summary>After build using github action. it fails with the error below</summary>

```
Run flutter build apk --build-name =1.0.1 --release --split-per-abi
Running Gradle task 'assembleRelease'...                        
WARNING: [Processor] Library '/home/runner/.gradle/caches/modules-2/files-2.1/io.flutter/flutter_embedding_release/1.0.0-b8752bbfff0419c8bf616b602bc59fd28f6a3d1b/756aebd7349bab6060fbc9f31be4ffa8e567c227/flutter_embedding_release-1.0.0-b8752bbfff0419c8bf616b602bc59fd28f6a3d1b.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

 Example of androidX reference: 'androidx/annotation/NonNull'

 Example of support library reference: 'android/support/annotation/NonNull'

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings


warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release




warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release

warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release

warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.


3 warnings

warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

Note: Some input files use or override a deprecated API.


Note: Recompile with -Xlint:deprecation for details.
Note: /opt/hostedtoolcache/flutter/1.22.2-stable/x64/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':app:stripReleaseDebugSymbols'.

> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 59s
Running Gradle task 'assembleRelease'...                          239.9s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...                     
The plugin cloud_firestore could not be built due to the issue above.
Error: Process completed with exit code 1.
```
</details>

**Comment by pedromassangocode** [comment] 2020-11-05 14:18
Hi @finkcloud 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-05 14:18 UTC
Labels: team: infra
