### ISSUE TITLE
cannot run app on android

### ISSUE THREAD

**Issue by bbbeep** [flutter/flutter#25725] opened 2018-12-24 03:16 UTC
## Steps to Reproduce

1. ...Open android emulator build-in Android Studio
2. ...run app either on cmd or with Android Studio IDE
3. ...
```
ERROR in gradle folder--"cannot find or load java.se.ee"
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "/Users/hpark/AndroidStudioProjects/myapp/android/gradlew" exited abnormally:
오류: 기본 클래스 java.se.ee을(를) 찾거나 로드할 수 없습니다.
  Command: /Users/hpark/AndroidStudioProjects/myapp/android/gradlew -v
```

**Comment by jagdishjadeja** [comment] 2018-12-24 05:52
you dont have java installed ?

**Comment by bbbeep** [comment] 2018-12-24 08:01
I do, I've compiled and ran programs in Java just few days ago.

My app works perfectly on iOS emulator, so I thought that it was some sort of problem with jdk and Android Studio.

**Comment by zoechi** [comment] 2018-12-24 11:41
Please add the output of `flutter doctor -v`.

**Comment by bbbeep** [comment] 2018-12-25 15:37
I get all of the checks. it works perfectly fine for ios emulator, but when i try to connect to android emulator from android studio, it doesnt work.


![image](https://user-images.githubusercontent.com/37920434/50424384-32b7a400-08a6-11e9-8887-31b62e141609.png)

**Comment by zoechi** [comment] 2018-12-27 08:08
@bbbeep is there more error output than what you posted in the initial comment?

**Comment by bbbeep** [comment] 2019-01-01 04:57
No..that's it.

**Comment by zoechi** [comment] 2019-01-02 07:09
@bbbeep https://github.com/flutter/flutter/issues/16093#issuecomment-390489264 might help.

**Comment by zoechi** [comment] 2019-01-28 09:39
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-28 09:39 UTC
Labels: severe: crash, t: gradle, tool, waiting for customer response

**Comment by kangwang1988** [comment] 2019-01-28 09:45
It seems that `/Users/hpark/AndroidStudioProjects/myapp/android/gradlew -v` fails.
I think it's probably not a flutter issue, but I'm not sure as I can't reproduce it.
@bbbeep 
You can run the gradlew command directly from the terminal to see what happens, google/stackoverflow is a better place for this problem.
It's always welcome to add more information by commenting below, if it can be detected by flutter_tools(like flutter doctor), we will be very happy to refactor it.
Thank you again~
