### ISSUE TITLE
Crash when aligning TextField by baseline

### ISSUE THREAD

**Issue by kevinengel** [flutter/flutter#24705] opened 2018-11-25 01:06 UTC
I would like to have a TextField and a button in a Row together, aligned by baseline.  This causes a crash due to an unimplemented function in `package:flutter/src/material/input_decorator.dart`.

```dart
import 'package:flutter/material.dart';

void main() => runApp(Main());

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Attendance',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.baseline,
          textBaseline: TextBaseline.alphabetic,
          children: [
            Expanded(child:TextField()),
            Container(width: 16.0),
            RaisedButton(child: Text('REFRESH')),
          ],
        ),
      ),
    );
  }
}
```
Output:

```
I/flutter (25288): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25288): The following assertion was thrown during performLayout():
I/flutter (25288): not implemented
I/flutter (25288): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 966 pos 12: 'false'
```

flutter doctor -v:
```
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 0.11.9 at C:\Users\Admin\Desktop\flutter
    • Framework revision d48e6e433c (4 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Pixel XL • HT7470204168 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment] 2018-11-26 09:53
Might be the same underlying cause as #23377

**Comment by goderbauer** [comment] 2018-12-03 21:34
The asserting that's triggering is here: https://github.com/flutter/flutter/blob/c8ff617fd8cf72f8ec5b107fb6729feb22fd101d/packages/flutter/lib/src/material/input_decorator.dart#L965-L968

That means @zoechi hunch is correct. I am going to de-dup the issues.

**Comment by goderbauer** [comment] 2018-12-03 21:38
@HansMuller, who submitted the assert :)

**Comment by HansMuller** [comment] 2018-12-03 23:39
That function wasn't implemented because at the time it wasn't possible to. Here are my notes from a year ago, when I was working on it:

> ... I thought this would work:

```
  double _lineHeight(double width, List<RenderBox> boxes) {
    double aboveBaseline = 0.0;
    double belowBaseline = 0.0;
    for (RenderBox box in boxes) {
      if (box == null)
        continue;
      final double baseline = box.getDistanceToBaseline(TextBaseline.alphabetic);
      aboveBaseline = math.max(baseline, aboveBaseline);
      belowBaseline = math.max(box.getMinIntrinsicWidth(width) - baseline, belowBaseline);
    }
    return aboveBaseline + belowBaseline;
  }
```
> If fails in a complex assertion due to the call to getDistanceToBaseline().  I assume that it's enforcing this documented limitation:
> 
> Only call this function after calling layout on this box. You are only allowed to call this from the parent of this box during that parent's performLayout or paint functions.
> 
> I noticed this in flex.dart, which should need to do the same baseline-aligned line-height thing:
> // TODO(ianh): Support baseline alignment.

Apparently this is still an open TODO: 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/flex.dart#L511

**Comment by bzd2000** [comment] 2019-03-27 08:51
Is this going to be solved?

**Comment by justinmc** [comment] 2019-04-02 22:37
@bzd2000 I'm hoping to take a look at this when I get some time.  I'm trying to clean up a bunch of TextField related problems.

**Comment by Chesong-Lee-Hospii** [comment] 2019-04-03 03:37
@justinmc thanks that would be appreciated. I ran into the same issue on Android Studio with Flutter plugin version 33.3.1 and Dart plugin version 182.5215.

**Comment by GaryQian** [comment] 2019-04-06 00:24
https://github.com/flutter/flutter/pull/30069 includes a fix for the `assert(false...)`, and I believe Justin is also working on a more thorough fix for this. Whichever lands first (probably Justin's) will fix this, since my patch may take longer as it is part of a much bigger change.

**Closed** 2019-04-11 16:32 UTC
Labels: customer: crowd, f: material design, framework, severe: crash

**Comment by justinmc** [comment] 2019-04-11 16:34
This should work now with the above PR.

@GaryQian FYI that PR includes the 1 commit that I cherry picked from you.

**Comment by imply-wh** [comment] 2019-05-30 08:16
Is there a solution to this problem?My Flutter current version is 1.5.4

**Comment by justinmc** [comment] 2019-05-30 16:27
This should be fixed as of v1.4.17.  If you're seeing it on 1.5.4 then let us know how to reproduce it if you can.

**Comment by andersonptf-work** [comment] 2019-06-19 09:21
I'm having the same problem. Here is my code snippet:
`      body: SingleChildScrollView(
        child: Container(
          margin: EdgeInsets.all(15.1),
          child: Form(
            key: _formKey,
            autovalidate: _autoValidate,
            child: ListView(
              children: <Widget>[
                ListTile(
                  title: TextFormField(
                    decoration: const InputDecoration(labelText: 'Product Barcode'),
                    keyboardType: TextInputType.text,
                  ),
              ],
            ),
          ),
      ),
`
Runnning on version:
1.5.4-hotfix.2_ • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by andersonptf-work** [comment] 2019-06-19 09:46
> I'm having the same problem. Here is my code snippet:
> ` body: SingleChildScrollView( child: Container( margin: EdgeInsets.all(15.1), child: Form( key: _formKey, autovalidate: _autoValidate, child: ListView( children: <Widget>[ ListTile( title: TextFormField( decoration: const InputDecoration(labelText: 'Product Barcode'), keyboardType: TextInputType.text, ), ], ), ), ),`
> Runnning on version:
> 1.5.4-hotfix.2_ • channel stable • https://github.com/flutter/flutter.git
> Framework • revision [7a4c334](https://github.com/flutter/flutter/commit/7a4c33425ddd78c54aba07d86f3f9a4a0051769b) (7 weeks ago) • 2019-04-29 11:05:24 -0700
> Engine • revision 52c7a1e849
> Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

The problem seems to be the SingleChildScrollView container. After removing it I don't have the problem anymore.

**Comment by justinmc** [comment] 2019-06-19 21:41
@andersonptf-work Do you need the SingleChildScrollView?  I tried your code and couldn't find anything that looked like a bug.  If something seems broken let me know.
