### ISSUE TITLE
Double clicking the photo button in image_picker fires underlying `onTap`

### ISSUE THREAD

**Issue by slimyjimmy** [flutter/flutter#80348] opened 2021-04-13 08:09 UTC
Hey there,
I'm having a little difficulty with the image_picker package. 
When double clicking the button to take a photo, it seems that that the second click in the native layer is being registered by the "old" screen that we initiated image_picker's `getImage` from. Whatever happens to be below the "take photo" button of the native layer, gets clicked.

## Steps to Reproduce

1. Clone the following minimal reproducable example project: https://github.com/slimyjimmy/image_picker_crash_mvp
2. Run app on iOS
3. Click "click here" button (to add an image)
4. Image should be added successfully
5. Click "click here" button again (you might have to scroll down a bit)
6. Now, when taking another photo, click the button which takes the photo (in the native screen produced by image_picker) twice in a row very fast (double-click, that is).
7. You then should get informed by the Fluttertoast that the onTap method of the underlying widget (GestureDetector) has been fired from the native screen (by double-clicking it)
8. Step 7 is confirmed when you select "Use photo" and are taken back - Because you are actually not really taken back but rather taken to another screen (Navigator.of(context).push in onTap of underlying widget again).

**Expected results:**
A double click in the photo-taking layer shouldn't be registered by the underlying screen / shouldn't fire an underlying GestureDetector's `onTap`

**Actual results:**
Double clicking the button to take a photo fired the `onTap` of an underlying GestureDetector which happened to be placed at the same coordinates.

<details>
  <summary>Logs</summary>

```
[   +1 ms] Application launched on the device. Waiting for observatory port.
[+1312 ms] Observatory URL on device: http://127.0.0.1:51520/
[  +14 ms] Attempting to forward device port 51520 to host port 55294
[   +1 ms] executing: /Users/djimonnowak/development/flutter/bin/cache/artifacts/usbmuxd/iproxy 55294:51520 --udid 00008020-001B78803AF0402E
[ +319 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[   +2 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make
your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[ +721 ms] Forwarded port ForwardedPort HOST:55294 to DEVICE:51520
[   +1 ms] Forwarded host port 55294 to device port 51520 for Observatory
[  +13 ms] Installing and launching... (completed in 22.9s)
[   +6 ms] Caching compiled dill
[  +70 ms] Connecting to service protocol: http://127.0.0.1:55294/
[ +151 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:55294/.
[  +93 ms] DDS is listening at http://127.0.0.1:55303/xVxwfbACt4I=/.
[  +51 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[        ] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make
your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[  +37 ms] Successfully connected to service protocol: http://127.0.0.1:55294/
[ +978 ms] DevFS: Creating new filesystem on the device (null)
[  +46 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/CCB50DB3-AC12-4C24-B269-AA7118B7AEAF/tmp/image_picker_crash_mvpRo6VnC/image_picker_crash_mvp/)
[   +6 ms] Updating assets
[  +98 ms] Syncing files to device Djimon’s iPad...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] <- recompile package:image_picker_crash_mvp/main.dart 1f008481-0e79-408b-a77a-2b33411d7537
[        ] <- 1f008481-0e79-408b-a77a-2b33411d7537
[  +53 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Djimon’s iPad... (completed in 61ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +17 ms] Connected to _flutterView/0x109824e20.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Djimon’s iPad is available at: http://127.0.0.1:55303/xVxwfbACt4I=/
[        ] 
           Flutter DevTools, a Flutter debugger and profiler, on Djimon’s iPad is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A55303%2FxVxwfbACt4I%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+2369 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[+6335 ms] [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver
_initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}

```

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale en-DE)
    • Flutter version 2.0.4 at /Users/djimonnowak/development/flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/djimonnowak/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Djimon’s iPad (mobile) • 00008020-001BXXXXXXXXXXXX            • ios            • iOS 14.3
    • iPhone 12 (mobile)     • D3425BC3-F0C5-4DE0-9C48-7CXXXXXXXXXX • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-04-13 09:12
Hi @slimyjimmy 
This is a known issue https://github.com/flutter/flutter/issues/28335
Closing as duplicate of https://github.com/flutter/flutter/issues/28335
Thank you

**Closed by TahaTesser** 2021-04-13 09:12 UTC
Labels: in triage
