### ISSUE TITLE
flutter create crashes in windows desktop directory "OS Error: The system cannot find the file specified"

### ISSUE THREAD

**Issue by ayushkumarak** [flutter/flutter#40700] opened 2019-09-17 19:05 UTC
[flutter_01.log](https://github.com/flutter/flutter/files/3623021/flutter_01.log)
content of the log:

## command
```
flutter create prac_app
```
## exception
```
FileSystemException: FileSystemException: Creation failed, path = 'C:\Users\Ayush Kumar\Desktop\development\flutter\prac_app' (OS Error: The system cannot find the file specified.
, errno = 2)

```
```
#0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
#1      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      Template.render (package:flutter_tools/src/template.dart:71:17)
#3      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:623:21)
#4      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:546:23)
<asynchronous suspension>
#5      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:397:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:487:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#16     _rootRun (dart:async/zone.dart:1120:38)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.8.3, on Microsoft Windows [Version 10.0.17763.737], locale en-IN)
    [32m•[39m Flutter version 1.8.3 at G:\SOFTWARES\flutter
    [32m•[39m Framework revision e4ebcdf6f4 (7 weeks ago), 2019-07-27 11:48:24 -0700
    [32m•[39m Engine revision 38ac5f30a7
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\Ayush Kumar\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 38.2.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[33m[!][39m IntelliJ IDEA Community Edition (version 2018.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by nandubatchu** [comment] 2019-09-17 19:09
[flutter_01.log](https://github.com/flutter/flutter/files/3623037/flutter_01.log)

**Comment by jonahwilliams** [comment] 2019-09-17 19:12
Please follow the issue template when filling bugs, including describing the issue in the issue title and include both the crash report and `flutter doctor -v` in the issue body.

**Comment by Mravuri96** [comment] 2019-09-17 19:24
## command

flutter upgrade --continue --no-version-check

## exception

UnsupportedError: Unsupported operation: Cannot modify unmodifiable map

```
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:262:5)
#1      _DefaultProcessUtils._environment (package:flutter_tools/src/base/process.dart:516:20)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:415:20)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:430:35)
<asynchronous suspension>
#4      UpgradeCommandRunner.precacheArtifacts (package:flutter_tools/src/commands/upgrade.dart:247:41)
<asynchronous suspension>
#5      UpgradeCommandRunner.runCommandSecondHalf (package:flutter_tools/src/commands/upgrade.dart:144:11)
<asynchronous suspension>
#6      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:78:13)
<asynchronous suspension>
#7      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:56:32)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:519:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.3-pre.70, on Mac OS X 10.15 19A558d, locale en-US)
    • Flutter version 1.10.3-pre.70 at /Users/maheshwarravuri/Development/flutter
    • Framework revision a50eda8f5a (15 minutes ago), 2019-09-17 19:22:28 +0200
    • Engine revision 63873d9f42
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7799f424f4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/maheshwarravuri/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M392r
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.15 19A558d
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ayushkumarak** [comment] 2019-09-17 19:50
when i change my directory of my source project it works correctly...but it give error while running the root project from my desktop

**Comment by BondarenkoStas** [comment] 2019-09-17 20:23
@nandubatchu @Mravuri96 I believe your comments point to the #40694 issue, but not related to the current one.

**Comment by VladyslavBondarenko** [comment] 2020-05-08 15:47
@ayushkumarak 
It could be related to the white space in your path `Ayush Kumar` if 
> when i change my directory of my source project it works correctly...but it give error while running the root project from my desktop

But I can't reproduce it with current stable v1.17.0 on windows,
Closing as fixed.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.

**Closed by VladyslavBondarenko** 2020-05-08 15:47 UTC
Labels: platform-windows, severe: crash, tool
