### ISSUE TITLE
Unsupported operation: dart:isolate is not supported on dart4web

### ISSUE THREAD

**Issue by jayeshindianic** [flutter/flutter#80493] opened 2021-04-15 06:40 UTC
Flutter web is working on desktop browser but issues on mobile browser
even in release or debug mode , its just stuck 
`Unsupported operation: dart:isolate is not supported on dart4web`
just show this error nothing else,
i have alredy try to remove all print(). but its not working

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

• No issues found!
```

```
name: xyz
description: xyz
version: 3.2.2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl:
  intl_translation:
  barcode_scan:
  google_maps_flutter:
  google_maps: ^5.1.0
  connectivity:
  share:
  http:
  google_fonts: ^1.1.2
  firebase_analytics: ^7.1.1
  firebase: 7.3.0
  firebase_dynamic_links: ^0.8.0
  shared_preferences:
  get: ^3.26.0
  auto_size_text: ^2.1.0
  cached_network_image:
  url_launcher:
  flutter_html:
  font_awesome_flutter:
  carousel_pro:
  nice_button:
  sentry_flutter:
  http: any
  collection: ^1.14.6
  json_annotation:
  intl: ^0.16.1
  timeago: ^2.0.2
  rxdart: any
  protobuf: ^1.1.1



dev_dependencies:
  pedantic:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_goldens:
    sdk: flutter

publish_to: none

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

```

**Comment by TahaTesser** [comment] 2021-04-15 09:04
Hi @jayeshindianic 
This might be caused by one of the packages you're using. can you please reproduce the issue with a new project without third-party packages?



If the problem persists,  Can you please provide your `flutter run -d chrone --verbose` logs running the new project ?
Thank you

**Comment by jayeshindianic** [comment] 2021-04-15 12:43
when i paste localhost address in ios simulator its just showen white screen 
```
[+50184 ms] DwdsInjector: Received request for entrypoint at
http://localhost:57726/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +9 ms] MetadataProvider: Loaded debug metadata
[   +3 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:57726/main_module.bootstrap.js
[+26766 ms] DwdsInjector: Received request for entrypoint at
http://localhost:57726/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata
[   +3 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:57726/main_module.bootstrap.js
```

**Comment by jayeshindianic** [comment] 2021-04-15 12:46
```
[+316463 ms] Performing hot restart...
[   +1 ms] Skipping target: gen_localizations
[        ] complete
[   +7 ms] Scanned through 825 files in 7ms
[        ] Waiting for connection from debug service on Chrome...
[        ] <- recompile org-dartlang-app:/web_entrypoint.dart 860c9f17-431c-4116-ae9e-c76ad144e99d
[        ] <- 860c9f17-431c-4116-ae9e-c76ad144e99d
[  +21 ms] Waiting for connection from debug service on Chrome... (completed in 22ms)
[        ] Synced 0.0MB.
[        ] <- accept
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +6 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +70 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[        ] DwdsVmClient: Successful hot restart
[        ] Performing hot restart... (completed in 111ms)
[        ] Restarted application in 111ms.
[+13271 ms] Performing hot restart...
[   +1 ms] Skipping target: gen_localizations
[        ] complete
[   +7 ms] Scanned through 825 files in 7ms
[        ] Waiting for connection from debug service on Chrome...
[        ] <- recompile org-dartlang-app:/web_entrypoint.dart fa40b2d1-9a1b-4b87-bc90-0b871ec10517
[        ] <- fa40b2d1-9a1b-4b87-bc90-0b871ec10517
[  +20 ms] Waiting for connection from debug service on Chrome... (completed in 21ms)
[        ] Synced 0.0MB.
[        ] <- accept
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +5 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +72 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[   +1 ms] DwdsVmClient: Successful hot restart
[        ] Performing hot restart... (completed in 111ms)
[        ] Restarted application in 111ms.
[ +292 ms] Error: Unsupported operation: dart:isolate is not supported on dart4web
                        at Object.throw_ [as throw] (http://localhost:57726/dart_sdk.js:5334:11)
                        at Object._unsupported (http://localhost:57726/dart_sdk.js:60561:15)
                        at Function.get current [as current]
(http://localhost:57726/dart_sdk.js:60321:23)
                        at Function.set enableTimelineLogging [as enableTimelineLogging]
                        (http://localhost:57726/dart_sdk.js:186982:155)
                        at init

(http://localhost:57726/packages/ninja_app_client/screen/wifi_information.dart.lib.js:41642:48)
                        at init.next (<anonymous>)
                        at http://localhost:57726/dart_sdk.js:39032:33
                        at _RootZone.runUnary (http://localhost:57726/dart_sdk.js:38889:58)
                        at _FutureListener.thenAwait.handleValue
(http://localhost:57726/dart_sdk.js:33875:29)
                        at handleValueCallback (http://localhost:57726/dart_sdk.js:34435:49)
                        at Function._propagateToListeners (http://localhost:57726/dart_sdk.js:34473:17)
                        at _Future.new.[_completeWithValue] (http://localhost:57726/dart_sdk.js:34315:23)
                        at async._AsyncCallbackEntry.new.callback
(http://localhost:57726/dart_sdk.js:34338:35)
                        at Object._microtaskLoop (http://localhost:57726/dart_sdk.js:39176:13)
                        at _startMicrotaskLoop (http://localhost:57726/dart_sdk.js:39182:13)
                        at http://localhost:57726/dart_sdk.js:34689:9

```

**Comment by TahaTesser** [comment] 2021-04-16 07:05
Hi @jayeshindianic 
Looks like you're still running your existing app, can you please reproduce with the issue in a new project without third-party packages

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run -web-server --verbose` logs running the minimal code sample?
Thank you

**Comment by jayeshindianic** [comment] 2021-04-19 10:34
@TahaTesser without any third party package its working, but in my case i need package and now how can i find which package is reflected?

i have added  flutter run -chrome --verbose.
```
[   +3 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +3 ms] complete
[  +12 ms] Scanned through 824 files in 11ms
[        ] Waiting for connection from debug service on Chrome...
[   +1 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 2dea5cca-5242-4b8d-951d-b13682bb63de
[        ] <- 2dea5cca-5242-4b8d-951d-b13682bb63de
[  +24 ms] Waiting for connection from debug service on Chrome... (completed in 24ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[  +11 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[ +124 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[  +13 ms] DwdsVmClient: Successful hot restart
[        ] Performing hot restart... (completed in 205ms)
[        ] Restarted application in 206ms.
[+2560 ms] [debug] Event 1f3bd9c30aec4360b3dfe392da8e2127 was sent successfully.
```

**Comment by TahaTesser** [comment] 2021-04-20 06:26
Hi @jayeshindianic 
Make a backup of the project,  try removing packages, isolate the package that's causing the issue
For issues related to third-party packages, please file an issue on their dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-20 06:26 UTC
Labels: in triage
