### ISSUE TITLE
`flutter doctor -v` crashes from Dart.jar archive error

### ISSUE THREAD

**Issue by brendan-duncan** [flutter/flutter#96018] opened 2022-01-01 22:49 UTC
I'm the author of the archive library, which flutter doctor is using. I was informed about `flutter doctor -v` failing because it fails decoding Dart.jar with the archive library, https://github.com/brendan-duncan/archive/issues/177.

The problem was because Dart.jar had an archive comment that was not a valid string, and the library wasn't robust about catching that. I updated the archive library to 3.1.8 to catch that error. But I don't know how to update flutter's pub cache to make sure it's using the latest version of the library for flutter doctor to verify the fix with flutter.

**Comment by danagbemava-nc** [comment] 2022-01-03 07:11
Related issue: https://github.com/flutter/flutter/issues/94060

/cc @christopherfujino

**Comment by TahaTesser** [comment] 2022-01-03 10:01
@christopherfujino 
I have attempted to upgrade packagers using `flutter update-packages --force-upgrade` but there are issues from `dds` and not all packages are migrated

**Comment by mandudeman** [comment] 2022-01-06 02:43
Were guys able to solve this issue? If yes, can you specifically explain how you go about doing it? I am new to Flutter and I am encountering the same problem. Your answer will be a big help. Thanks a lot.

**Comment by TahaTesser** [comment] 2022-01-07 08:22
https://github.com/flutter/flutter/issues/96240 is tracking issue from https://github.com/flutter/flutter/issues/96018#issuecomment-1003981594

**Comment by TahaTesser** [comment] 2022-01-10 09:05
Using https://github.com/flutter/flutter/pull/96258 I tried updating packages and the issue is resolved, 
I am closing this for original as update issue is resolved and should be landed in https://github.com/flutter/flutter/pull/96325

**Closed by TahaTesser** 2022-01-10 09:05 UTC
Labels: tool, t: flutter doctor, passed first triage

**Comment by christopherfujino** [comment] 2022-01-10 18:56
@TahaTesser I was out of office, thanks for driving this!
