### ISSUE TITLE
[windows] dropdownbutton keyboard issue

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#78880] opened 2021-03-23 16:58 UTC
to open dropdown item by keyboard up arrow, the items are shown after selecting item and press enter key i'm getting below issue

```
Unable to parse JSON message:
The document is empty.

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during a platform message callback:[39;49m
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 746 pos 9: 'context != null'


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
[39;49m

```

```
```
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      FocusNode.rect[39;49m
[38;5;244m#3      DirectionalFocusTraversalPolicyMixin._sortAndFilterVertically.<anonymous closure>[39;49m
[38;5;244m#4      _insertionSort[39;49m
[38;5;244m#5      mergeSort[39;49m
[38;5;244m#6      DirectionalFocusTraversalPolicyMixin._sortAndFilterVertically[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Lost connection to device.
Exited (sigterm)
```
```

**Comment by selvam920** [comment] 2021-03-23 16:58
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.868], locale en-US)
    • Flutter version 2.1.0-12.2.pre at D:\SW\flutter_master\flutter
    • Framework revision 5bedb7b1d5 (6 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\SW\sdk-tools-windows-4333796
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0 Preview 1.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.10.31025.218
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Jack Selvam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.868]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.57

**Comment by darshankawar** [comment] 2021-03-24 07:40
@selvam920 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue, along with your `pubspec.yaml`.
Thanks.

**Comment by selvam920** [comment] 2021-03-24 09:47
DropdownButtonFormField(
              autofocus: true,
              hint: Text(
                  'Please choose a location'), // Not necessary for Option 1
              value: _selectedLocation,
              onChanged: (newValue) {
                FocusScope.of(context).requestFocus(FocusNode());
                setState(() {
                  _selectedLocation = newValue;
                });
              },
              items: _locations.map((location) {
                return DropdownMenuItem(
                  child: new Text(location),
                  value: location,
                );
              }).toList(),
            )

**Comment by selvam920** [comment] 2021-03-24 09:47
found the issue, onchanged event i'm using
FocusScope.of(context).requestFocus(FocusNode());
this is causing the issue.

**Comment by selvam920** [comment] 2021-03-24 09:49
i'm closing the issue

**Comment by selvam920** [comment] 2021-03-24 17:44
Unable to change the dropdownitem by arrow up/down with enter key

**Comment by darshankawar** [comment] 2021-03-25 07:00
@selvam920 
I think you are mixing two issues. The original issue related to `Unable to parse JSON message:` seems to be fixed per your earlier comment and now the `Unable to change the dropdownitem by arrow up/down with enter key` seems to be a different issue similar to https://github.com/flutter/flutter/issues/78105. Please follow-up in 78105 for further updates, or file a new issue by providing all required details. 

Closing this as the original issue is resolved. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-03-25 07:01 UTC
Labels: in triage
