### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by mnaveedpaki** [flutter/flutter#155067] opened 2024-09-12 05:25 UTC
## Command
```sh
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```console

```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.2, on macOS 14.6 23G80 darwin-arm64, locale en-PK)
    [32m•[39m Flutter version 3.24.2 on channel stable at /Users/bbt/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4cf269e36d (8 days ago), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/bbt/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[32m[✓][39m VS Code (version 1.93.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m iPhone (mobile)                 • 00008020-0006555621E2002E • ios            • iOS 17.6.1 21G93
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6 23G80 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.121
    [33m![39m Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    [33m![39m Error: Browsing on the local area network for My Phone. Ensure the device is unlo

**Comment by danagbemava-nc** [comment] 2024-09-12 07:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by danagbemava-nc** 2024-09-12 07:40 UTC
Labels: in triage
