### ISSUE TITLE
Web Build Busted After Upgrade

### ISSUE THREAD

**Issue by corepuncher** [flutter/flutter#148728] opened 2024-05-21 01:14 UTC
### Steps to reproduce

I used to be able to build and run web fine. Then I tried to fix the deprecated serviceWorkerVersion deal, and now the build will not run in a browser without many errors (see below).

### Expected results

It should run in the browser.

### Actual results

Several errors now.

### Code sample

First I tried to address the flutter_service_worker_version error, and now when I build, in my index.html I have double quotes around the version value like this:

```
  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = ""1234567899"";
  </script>
```

So then I manually delete the double quotes, and I still have the following errors:

flutter.js:3 Uncaught (in promise) FlutterLoader.load requires _flutter.buildConfig to be set

```
  <script>
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.load({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function (engineInitializer) {
          engineInitializer.initializeEngine().then(function (appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>

```

So it's like whack-a-mole at this point.

Any ideas what the root cause of this is?  I used to be able to build web app fine, until upgrades.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22621.3593],
    locale en-US)
    • Flutter version 3.22.0 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (12 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)       
    • Android SDK at C:\Users\...\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by navaronbracke** [comment] 2024-05-21 08:53
I think you're missing the `build config` and `flutter loader initialization` parts.

So the `{{flutter_js}}` (setting up _flutter.loader) and `{{flutter_build_config}}` (setting up _flutter.buildConfig) template tokens

See https://docs.flutter.dev/platform-integration/web/bootstrapping

**Comment by danagbemava-nc** [comment] 2024-05-21 11:02
Hi @corepuncher, can you try https://github.com/flutter/flutter/issues/148728#issuecomment-2122113190 to see if it helps? 

If it does not, can you share the errors that you get in your console?

Thank you

**Comment by corepuncher** [comment] 2024-05-21 22:03
> Hi @corepuncher, can you try [#148728 (comment)](https://github.com/flutter/flutter/issues/148728#issuecomment-2122113190) to see if it helps?
> 
> If it does not, can you share the errors that you get in your console?
> 
> Thank you

Thanks for the replies all. 

I actually fixed it by doing this:
`flutter create --platforms web .
`

Then I added a couple lines back to my index.html that I had previously.  I think my version got so far behind it needed quite an overhaul.

**Comment by huycozy** [comment] 2024-05-22 05:06
@corepuncher Looks like you solved the issue so I will close this. If it reoccurs, please share a sample code (your index.html file and necessary files to reproduce the issue) along with the error stack trace that may help us investigate the issue further. Thanks!

**Closed by huycozy** 2024-05-22 05:06 UTC
Labels: in triage
