### ISSUE TITLE
Flutter PlatformView  on Android 6.0 the default background is black

### ISSUE THREAD

**Issue by coltorchen** [flutter/flutter#26505] opened 2019-01-14 03:46 UTC
i try to use PlatformView to expose a native Android ListView as a Flutter Widget.
when i run example on Android 7.0+,ListView background looks good.  
(Mobile device: Redmi Note 4X - MIUI 9.6 - Android 7.0)
![image](https://user-images.githubusercontent.com/24756502/51095596-e00c4080-17f0-11e9-8122-f08b9c2d376c.png)

but when i run example on Android 6.0, ListView background is black, maybe the background color's alpha is 0 ?
(Mobile device: Redmi Note 4 - MIUI 10 - Android 6.0 )
![image](https://user-images.githubusercontent.com/24756502/51095695-8e17ea80-17f1-11e9-91a3-c2d321bd4613.png)

#######################################################################
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2019-01-14 08:09
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce or in this case perhaps a project published to GitHub.

**Comment by figo-fe** [comment] 2019-03-13 08:35
I have the same problem. @zoechi @linuxomk 
flutter code:
```
class Demo extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Container(
      child: AndroidView(
        viewType: 'nativeViewDemo'
      ),
    );
  }
}
```

Android code:
```
public class DemoView {
    public static void registerWith(Registrar registrar) {
        registrar.platformViewRegistry().registerViewFactory("nativeViewDemo", new NativeViewFactory(registrar.messenger()));
    }
}

public class NativeViewFactory extends PlatformViewFactory {
    private final BinaryMessenger messenger;

    public NativeViewFactory(BinaryMessenger messenger) {
        super(StandardMessageCodec.INSTANCE);
        this.messenger = messenger;
    }

    @Override
    public PlatformView create(Context context, int id, Object args) {
        return new NativeView(context, messenger, id);
    }
}

class NativeView implements PlatformView {
    @Override
    public View getView() {
        return new FrameLayout();
    }
}


```
The background is darkGray in Android 6.0, but white above 6.0
It may can not run directly, but it can show what I mean.

**Comment by lzdon** [comment] 2019-03-16 05:57
same issue. i used AndroidView to show barrage, its background is white and video below is invisiable

**Comment by lzdon** [comment] 2019-03-18 09:00
i solve this temporarily by using reflection .
```
    override fun getView(): View {
        try {
            makeWindowTransparent()
        } catch (e: Exception) {
            Log.d("LiveDanmakuView", "makeWindowTransparent failed: $e")
        }
        return mDanmakuView
    }

    private fun makeWindowTransparent() {
        mDanmakuView.post {
            var parent = mDanmakuView.parent
            while (parent != null && parent.parent != null) {
                parent = parent.parent
            }
            val decorView = parent.javaClass.getDeclaredMethod("getView").invoke(parent)
            val windowField = decorView.javaClass.getDeclaredField("mWindow")
            windowField.isAccessible = true
            val window = windowField.get(decorView) as Window
            windowField.isAccessible = false
            window.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
        }
    }
```

**Comment by HustLion** [comment] 2019-04-16 08:03
> i solve this temporarily by using reflection .
> 
> ```
>     override fun getView(): View {
>         makeWindowTransparent()
>         return mDanmakuView
>     }
> 
>     private fun makeWindowTransparent() {
>         mDanmakuView.post {
>             try {
>                 var parent = mDanmakuView.parent ?: return@post
>                 while (parent?.parent != null) {
>                     parent = parent.parent
>                 }
>                 val decorView = parent.javaClass.getDeclaredMethod("getView").invoke(parent)
>                 val windowField = decorView.javaClass.getDeclaredField("mWindow")
>                 windowField.isAccessible = true
>                 val window = windowField.get(decorView) as Window
>                 windowField.isAccessible = false
>                 window.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
>                 log(window.toString())
>             } catch (e: Exception) {
>                 Log.d("LiveDanmakuView", "makeWindowTransparent failed: $e")
>             }
>         }
>     }
> ```

Could you provide a java version? Thank you very much!

**Comment by HustLion** [comment] 2019-04-16 10:44
The method @lzdon provided works, but for dynamic content like lottie animation, the animation will fails to clear its frames, resulting in all frames painted one over another. Is there any way to get PlatformView provide a transparent background by default?

**Comment by PenF00k** [comment] 2019-06-29 10:00
I'm trying to use flutter_lottie plugin and it gives me gray background color on android. Could someone please provide a workaround for this?

**Comment by codeRemoverA** [comment] 2019-07-26 02:37
Since i can't use flutter_lottie,it gives me white background color on android,I have to replac all lottie animation with videos,Could someone please help me?

**Comment by darshankawar** [comment] 2020-12-02 11:02
@coltorchen since I don't have the specific device with 6.0 OS to verify this, but can you confirm if this is still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment] 2020-12-23 09:27
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:27 UTC
Labels: P4, a: platform-views, e: OS Version specific, e: device-specific, engine, platform-android, waiting for customer response

**Comment by bashcious** [comment] 2021-07-05 15:41
Hi am currently facing this same issue, I want to show a widget from native and make the Android view background transparent, i tried on mobile device and it works fine, but when run on android tv marshmallow 6.0 API level 23, the background is always black. I am using flutter 1.22.6 and i also tried the method provided by @lzdon; it throws an exception `failed: java.lang.NoSuchFieldException: No field mWindow in class Lcom/android/internal/policy/PhoneWindow$DecorView; (declaration of 'com.android.internal.policy.PhoneWindow$DecorView' appears in /system/framework/framework.jar:classes2.dex) `
