### ISSUE TITLE
flutter debug problem

### ISSUE THREAD

**Issue by yznc** [flutter/flutter#71292] opened 2020-11-27 01:01 UTC
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3599 pos 12: '!_debugLocked': is not true.

**Comment by Abhishek01039** [comment] 2020-11-27 04:17
Hello @yznc 
can you please provide `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
Thanks

**Comment by darshankawar** [comment] 2020-11-27 07:25
@yznc 
We would need more details on the issue you are facing. Sharing only the error won't help to figure what exactly the problem is. Please provide above requested details.

**Comment by yznc** [comment] 2020-11-28 05:09
Performing hot restart...
Syncing files to device iPhone 11...
Restarted application in 1,374ms.

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3529 pos 12: 'route != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:3529:12)
#3      Navigator.push (package:flutter/src/widgets/navigator.dart:1795:34)
#4      OrderCard.build.<anonymous closure> (package:ruhaili_eshop/Widgets/orderCard.dart:28:19)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#eaed7
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(187.0, 313.5)
  finalLocalPosition: Offset(187.0, 189.5)
  button: 1
  sent tap down

**Comment by Abhishek01039** [comment] 2020-11-28 05:22
hello @yznc 
please provide the minimal reproduction code.
Thanks

**Comment by yznc** [comment] 2020-11-28 05:25
boss what do you mean by (minimal reproduction code)

**Comment by Abhishek01039** [comment] 2020-11-29 17:20
@yznc https://stackoverflow.com/help/minimal-reproducible-example

**Comment by pedromassangocode** [comment] 2020-12-23 09:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:11 UTC
Labels: in triage, waiting for customer response
