### ISSUE TITLE
[Impeller] Follow CmdPool best practices from ARM documentation.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133198] opened 2023-08-23 21:42 UTC
<small>_note: edited by @matanlurey._</small>

@jonahwilliams:

> Today we reset individual cmd buffers, but that can be really slow. We should follow the best practices in https://arm-software.github.io/vulkan_best_practice_for_mobile_developers/samples/performance/command_buffer_usage/command_buffer_usage_tutorial.html and create 1 cmd pool per thread/per frame. Once the pool usage is complete (via fence waiter), we can reset and recycle.
>
> <details>
>
> <summary>CMD buffer reset accounts for most of cmd pool creation time right now:</summary>
>
> ![image](https://github.com/flutter/flutter/assets/8975114/6b96964f-ffe7-46d7-96ad-87f2fc881f6c)
> </details>

---

To reproduce this:

```shell
# Don't use a unopt build, as we will be profiling C++ code.
cd $ENGINE
./flutter/tools/gn --android --android-cpu=arm64 --enable-vulkan --no-stripped --no-lto

# "fl" is a local flutter tool, i.e. $FRAMEWORK
fl run --local-engine=$ENGINE/out/android_debug_arm64 --local-engine-host=host_debug_unopt_arm64
```

`dev/integration_tests/flutter_gallery/android/app/build.gradle` in the `android { ... }` section:

```diff
+    packagingOptions{
+        doNotStrip "**/*.so"
+    }
```

`dev/integration_tests/flutter_gallery/android/app/src/main/AndroidManifest.xml`:

```diff
+        <meta-data
+            android:name="io.flutter.embedding.android.EnableImpeller"
+            android:value="true" />
```

**Comment by gaaclarke** [comment] 2023-08-23 21:47
Here i the table from that document:

Mode | Request + Reset command buffers (ms) | Total capture (ms) | Contribution
-- | -- | -- | --
Reset pool | 53.3 | 11 877 | 0.45 %
Reset buffers | 140.29 | 12 087 | 1.16 %
Allocate and free | 3 319.25 | 11 513 | 28.8 %

The "Reset pool" is only marginally better than resetting buffers.  We just started resetting buffers.  If we don't see positive results there, refactoring to resetting pools may not be worth the effort.

**Comment by jonahwilliams** [comment] 2023-08-23 21:48
If you reset the entire pool, you don't have to reset it during the raster task, you can reset it on a background thread.

**Comment by gaaclarke** [comment] 2023-08-23 22:03
> If you reset the entire pool, you don't have to reset it during the raster task, you can reset it on a background thread.

In order to be able to reset it on background thread you have to make sure that isn't being used on another thread.  I think you are proposing to make that guarantee by instead having a pool per frame.  Today we are sharing a pool across frames.  My concern is that creating and deleting pools may be a step backwards versus recycling the pool and paying the synchronization cost.

After the change where we recycle command buffers, has the resetting of command buffers shown up as something that takes a significant amount of time?

**Comment by jonahwilliams** [comment] 2023-08-23 22:04
> In order to be able to reset it on background thread you have to make sure that isn't being used on another thread. I think you are proposing to make that guarantee by instead having a pool per frame. Today we are sharing a pool across frames. My concern is that creating and deleting pools may be a step backwards versus recycling the pool and paying the synchronization cost.

We can guarantee this by using the FenceWaiter/ResourceManager

**Comment by jonahwilliams** [comment] 2023-08-29 22:42
@matanlurey

**Comment by matanlurey** [comment] 2023-08-29 22:52
Some notes from talking to @jonahwilliams:

- Command _pools_ (memory behind the buffer) are what create Command _buffers_, which in turn creates _commands_.
- Command pools have threading restrictions: they can only be used by 1 thread at a time.
- So, we create 1 command pool per thread, and re-use them by resetting individual command buffers; not as they come in, but the next time we need to use them, i.e. lazily `garbageCollectIfEnabled`.

**Problem**: Resetting individual command buffers is slow, and [ARM says not to do it](https://arm-software.github.io/vulkan_best_practice_for_mobile_developers/samples/performance/command_buffer_usage/command_buffer_usage_tutorial.html), and because of the threading restrictions we have to use our (important) raster thread to do this resetting (it can't happen in a background thread).

**Solution**: Change the architecture so we create one command pool, per thread, per frame, and when the frame is done, we stop creating command buffers from that particular command pool, let the buffers finish (using the fence waiter), and _then_ it's safe to move the command pool to a background thread to do the reset (so the expensive work happens off the raster thread).

You can see an example of this working in a hacky way in <https://github.com/flutter/engine/pull/45179>. A better way would be with a class called `ResourceManager`; it's a matter of figuring out where this stuff gets stored and how to use that API.

To reproduce this problem, look in the CPU profile in Android Studio, and you will see the "garbage collect commands buffers" - I could even add a trace event to be able to see it individual frames. It's not 1ms here and there though, it's a couple 100 microseconds _per_ raster thread, and it adds up.

Some sample apps that show this problem acutely are Flutter Wonderous, or anything with lots of offscreen rendering, like the Shrine App in Flutter gallery.

**Comment by gaaclarke** [comment] 2023-08-30 15:41
@matanlurey  mostly sounds good to me.  Here are a few clarifying points.

> Resetting individual command buffers is slow, and [ARM says not to do it](https://arm-software.github.io/vulkan_best_practice_for_mobile_developers/samples/performance/command_buffer_usage/command_buffer_usage_tutorial.html),

What it says is a bit more nuanced.  It says "Don't Call [vkResetCommandBuffer()](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkResetCommandBuffer.html) on a high frequency call path."  It's not clear if once per frame is a high frequency however the measurements do say that it is faster to reset the pool.

> Change the architecture so we create one command pool, per thread, per frame, and when the frame is done, we stop creating command buffers from that particular command pool, let the buffers finish (using the fence waiter), and then it's safe to move the command pool to a background thread to do the reset

I believe it is key that you recycle the command buffer pools otherwise you may get into a case that is similar to the problem case from ARM's documentation with allocating and freeing.  You could even possibly implement this with 2 pools where multiple frames are using the same pool but you ping-pong between, using one of them while cleanup is happening on the other.  Having a smaller number of pools is probably preferable to N pools.

> (so the expensive work happens off the raster thread).

I don't believe we have any data that suggests resetting a pool is expensive.  It might just be setting a pointer.

**Comment by matanlurey** [comment] 2023-08-30 22:12
@gaaclarke:

> What it says is a bit more nuanced. It says "Don't Call [vkResetCommandBuffer()](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkResetCommandBuffer.html) on a high frequency call path." It's not clear if once per frame is a high frequency however the measurements do say that it is faster to reset the pool.

Thanks! My guess from talking to Jonah is we shouldn't be calling it on our main render loop (we aren't), so I think we're in agreement here.

> I don't believe we have any data that suggests resetting a pool is expensive.

I think the traces posted suggest that (combined with the ARM guidance you x-referenced)?

I'll try not to get too invested in a particular solution and we can benchmark and make sure it's actually providing a benefit before landing a PR.

**Comment by jonahwilliams** [comment] 2023-08-31 01:13
I think if for whatever reason it was faster to reset / recycle individual buffers that would be fine - however the real key here is being able to move that work out of the raster task runner.

**Comment by gaaclarke** [comment] 2023-08-31 16:03
I don't think we have measurements for resetting the command pool, right?  Because we aren't currently doing it.  It's possible that resetting the pool is way faster than resetting individual buffers.  Resetting the individual buffer may require mutexs around communicating with the pool, whereas resetting the pool has different threading requirements and may have none.  That would mean moving it off the raster thread isn't a big deal.
Ultimately it isn't a huge deal but the simpler design may function as-good-as or better here based on what I've seen.  I could be wrong but it's worth checking.

**Comment by matanlurey** [comment] 2023-09-13 01:01
Some notes for myself since I'm still having a tough time finding the magic formula:

- Many of the approaches I've taken I've been fragile in terms of what objects are destructed in what order; in particular when multiple threads are involved (i.e. a thread trying to join itself), and when dealing with `vk::[Object]`s.

- There are three different places I see different failures:

  - On Linux
  - On Mac (with MoltenVK)
  - On Android

- Often failures are caught by the Vulkan validation layer, but not always. For example:

  ```
  E/flutter ( 9072): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
  E/flutter ( 9072): --- Vulkan Debug Report  ----------------------------------------
  E/flutter ( 9072): |                Severity: Error
  E/flutter ( 9072): |                    Type: { Validation }
  E/flutter ( 9072): |                 ID Name: UNASSIGNED-Threading-MultipleThreads
  E/flutter ( 9072): |               ID Number: 337425955
  E/flutter ( 9072): |       Queue Breadcrumbs: [NONE]
  E/flutter ( 9072): |  CMD Buffer Breadcrumbs: [NONE]
  E/flutter ( 9072): |         Related Objects: CommandPool [443103185994131] [UNNAMED]
  E/flutter ( 9072): |                 Trigger: Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x1930000000193, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x141cb623 | THREADING ERROR : vkCmdPipelineBarrier(): object of type VkCommandPool is simultaneously used in thread 502505200816 and thread 507189087408
  ```

---

## Ways to test

### Android

```shell
# $FRAMEWORK is a checkout of flutter/flutter.
cd $FRAMEWORK/dev/integration_tests/flutter_gallery

# Local tool alias.
fl run \
  --local-engine=$ENGINE/out/android_debug_unopt_arm64 \
  --local-engine-host=$ENGINE/out/host_debug_impeller_vulkan \
  --enable-impeller
```

Errors are usually hard crashes, or validation errors (see above).

### MacOS (Host)

```shell
ninja -j1000 -C ../out/host_debug_impeller_vulkan impeller_unittests

# A sampling of tests what have in particular failed across runs (versus running all)
../out/host_debug_impeller_vulkan/impeller_unittests \
  --gtest_filter="Play/AiksTest.CanRenderTiledTextureDecal/Vulkan:Play/RendererTest.CanCreateCPUBackedTexture/Vulkan:CommandEncoderVKTest.*"
```

### Linux

I've been mostly relying on CI, though I did get a VM setup w/ X-server that can run similar to MacOS.

**Closed** 2023-09-16 04:20 UTC
Labels: P1, e: impeller, team-engine, triaged-engine
