### ISSUE TITLE
FlutterFragment forced to visiable when Activity resumed

### ISSUE THREAD

**Issue by zxjzerg** [flutter/flutter#105203] opened 2022-06-02 08:28 UTC
I use FlutterFragment as a Tab in my application. After I upgrade Flutter to 3.0.0 I meet an issue that if the FlutterFragment is set to hidden, when the Activity resumes, the FlutterFragment will become visiable. 
This not happen when I use Flutter 2.10.5.

[Project for reproducing this issue](https://github.com/zxjzerg/FlutterFragmentIssueDemo)

<img src="https://user-images.githubusercontent.com/2309828/171587009-362cecfe-eb61-49a1-8b65-116a38b8e62d.gif" width="250"/>

I read the souce code of FlutterActivityAndFragmentDelegat in Flutter 3.0.0 and find out when the Fragment's onStart is called, it set the FlutterView to visiable. This changes are introduced by [#30897](https://github.com/flutter/engine/pull/30897).

```java
void onStart() {
  Log.v(TAG, "onStart()");
  ensureAlive();
  doInitialFlutterViewRun();
  // This is a workaround for a bug on some OnePlus phones. The visibility of the application
  // window is still true after locking the screen on some OnePlus phones, and shows a black
  // screen when unlocked. We can work around this by changing the visibility of FlutterView in
  // onStart and onStop.
  // See https://github.com/flutter/flutter/issues/93276
  flutterView.setVisibility(View.VISIBLE);
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6.5 20G527 darwin-x64, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by zxjzerg** [comment] 2022-06-02 08:29
@ColdPaleLight pls check this

**Comment by exaby73** [comment] 2022-06-02 09:46
I can replicate this behavior. Though one thing to note, I have noticed that when I tap on "Recent apps" button, then immediately go back to the app, the view is still invisible. It's when I tap on the "Home" button, then resume the app is when this bug occurs.

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (12 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1035, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1035 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3d62732d60 (2 hours ago), 2022-06-01 00:14:14 -0400
    • Engine revision 0d1057ef7b
    • Dart version 2.18.0 (build 2.18.0-157.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by ColdPaleLight** [comment] 2022-07-12 07:22
Closing it var linked PR

**Comment by ColdPaleLight** [comment] 2022-08-24 10:28
https://github.com/flutter/engine/pull/30897#discussion_r953493956

**Comment by Nayuta403** [comment] 2022-08-30 06:44
There are two issues to be addressed here：

1. `flutterView.getVisibility()`  sometimes it's not accurate, use `flutterView.isShown()` is more accurate. 

For example, nesting a FlutterFragment in FragmentA and setting FragmentA to View.GONE , it does not work for FlutterFragment. `flutterView.getVisibility()` is still VISIBLE. 

https://github.com/flutter/engine/blob/51d14176b6dad39ca707f7916cf528c2aacd6652/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L605

![image](https://user-images.githubusercontent.com/40540394/187365766-cba5b348-9b6e-4b6f-8823-cbff7568e3d6.png)

This problem can be reproduced in this project [code](https://github.com/chdo002/float_fragment.git) ：d6dad6cbaabacc68f43406a50fc216c9fa752ccc


3.  `flutterView.setVisibility(View.GONE)` does not work for FlutterSurfaceView. We need to set Visibility extra to FlutterSurfaceView. 

After calling `flutterView.setVisibility(View.GONE)`, switching from the background to the foreground flutterview will still be displayed.For `FlutterSurfaceView`, setting `View.GONE` to the current `FlutterView` will not take effect since it is not in the view tree.


![image](https://user-images.githubusercontent.com/40540394/187367495-286b382b-6b2b-48c2-8015-ce7390c92b68.png)

This problem can be reproduced in this project [code](https://github.com/chdo002/float_fragment.git) ：main
 
This problem was solved when I changed it to texture

For these two questions, I will finish [PR](https://github.com/flutter/engine/pull/35767) later

**Closed** 2023-07-06 19:08 UTC
Labels: c: regression, platform-android, waiting for customer response, engine, a: existing-apps, has reproducible steps, P2, found in release: 3.0, found in release: 3.1
