### ISSUE TITLE
Decoding Json object List<dynamic> as List<string> fails without an feedback to the developer

### ISSUE THREAD

**Issue by Witted** [flutter/flutter#98253] opened 2022-02-11 12:50 UTC
When casting from a Json list object to a list<String>, instead of failing to cast, the process silently fails without any warnings or errors to identify what is going wrong. 

## Steps to Reproduce

Take the below factory and model:
```
class Topic {
  int? id;
  String name;
  String displayName;
  int? parentId;
  List<String>? contentThemes;
  List<String>? channels;

  Topic({this.id, required this.name, required this.displayName, this.parentId, this.contentThemes, this.channels});

  factory Topic.fromJson(Map<String, dynamic> json) {
    var topic = Topic(
      id: json['id'] as int?,
      name: json['name'] as String,
      displayName: json['displayName'] as String,
      parentId: json['parentId'] as int?,
      contentThemes: json['contentThemes'] as List<String>?,
      channels: json['channels'] as List<String>?,
    );

    return topic;
  }
}
```
**Expected results:** 

The expectation is that flutter is able to identify that json['contentThemes'] is not a complex object and cast it from List<dynamic> to List<String> 

OR if it is unable to, it should throw an error to the developer to highlight the failure to cast. 

**Actual results:** 
When trying to cast List<dynamic> to List<String> (contentThemes, channels) it stops execution and silently fails to complete the task so the data is never returned.

The work around currently is to treat this as a complex object and do something like this:
```
class Topic {
  int? id;
  String name;
  String displayName;
  int? parentId;
  List<String>? contentThemes;
  List<String>? channels;

  Topic({this.id, required this.name, required this.displayName, this.parentId, this.contentThemes, this.channels});

  factory Topic.fromJson(Map<String, dynamic> json) {
    var topic = Topic(
      id: json['id'] as int?,
      name: json['name'] as String,
      displayName: json['displayName'] as String,
      parentId: json['parentId'] as int?,
      contentThemes: (json['channels'] as List?)?.map((item) => item as String)?.toList(),
      channels: (json['contentThemes'] as List?)?.map((item) => item as String)?.toList()
    );

    return topic;
  }
}
```

This feels pretty clunky and overly verbose but at the very least there should be some better error handling in flutter to handle failing to cast a json property to a object field as the currently result is very unfriendly for the developer

**Comment by stuartmorgan** [comment] 2022-02-11 20:29
Issues with Dart itself need to be filed [against dart](https://github.com/dart-lang/sdk), not Flutter.

You haven't provided a complete test case, just a code fragment, so it's not clear how you came to this conclusion. If you have a reproducible case where you don't get an error (see below), you should include the entire repro case in the issue you file again Dart, since in general the premise that there's no error is not correct.

> The expectation is that flutter is able to identify that json['contentThemes'] is not a complex object and cast it from List to List

Dart is strongly typed. It doesn't "identify" things, it follows deterministic typing rules. `List<dynamic>` is not assignable to `List<String>` because that violate the type rules.

> OR if it is unable to, it should throw an error to the developer to highlight the failure to cast.

I see the following (as expected) when making a simple complete test case passing `List<dynamic>` data to the code you provided:
```
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>?' in type cast
```


> The work around currently is to treat this as a complex object and do something like this:
> 
> ```
> ...
>       contentThemes: (json['channels'] as List?)?.map((item) => item as String)?.toList(),
> ...
> ```
> 
> This feels pretty clunky and overly verbose

FYI there is a much less verbose option for this exact purpose: the `cast<>` operator:
```
(json['contentThemes'] as List<dynamic>?)?.cast<String>()
```

Closing as everything here is at the Dart level, not the Flutter level.

**Closed by stuartmorgan** 2022-02-11 20:29 UTC
Labels: in triage
