### ISSUE TITLE
[macOS] BottomNavigationBar ignores style after 4+ Navigation Bar Items.

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#112653] opened 2022-09-29 17:12 UTC
## Steps to Reproduce

1. Run`flutter create --platform=macos bottom_nav`
2. Paste this into lib/main.dart
<details>
<summary>
lib/main.dart
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: 'abc'),
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: 'abc'),
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: 'abc'),
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: 'abc'),
        ],
      ),
    ),
  ));
}
```

</details>
3. Run `flutter run -d macos`

**Expected**
![Screen Shot 2022-09-29 at 9 54 53 AM](https://user-images.githubusercontent.com/44445638/193095838-25675121-486a-422c-b2d1-3a43a8c6fcc4.png)
- 4 icons and labels styled in the same way as the screenshot above.

**Actual**
![Screen Shot 2022-09-29 at 10 12 21 AM](https://user-images.githubusercontent.com/44445638/193096733-61a1e0c5-e902-427f-80d6-72724f728970.png)
- Icons and labels are now white 
- Labels are now missing on the N > 1 BottomNavigationbarItems

**Comment by danagbemava-nc** [comment] 2022-09-30 09:04
Turns out this is a duplicate of https://github.com/flutter/flutter/issues/27753.

As such I'll be closing this in favor of #27753.

**Closed by danagbemava-nc** 2022-09-30 09:04 UTC
Labels: waiting for customer response, in triage
