### ISSUE TITLE
when opening textField app either reloads or throws android exception for android.view.inputmethod.BaseInputConnection.setComposingRegion

### ISSUE THREAD

**Issue by kobi666** [flutter/flutter#96614] opened 2022-01-13 17:49 UTC
## Steps to Reproduce

1. Add Textfield in the center of a Scaffold
2a. if autoFocus is true, issue will happen immidielty
2b. tap on the textField, once keyboard is up issue will occur

when I did this inside an opened drawer,
flutter presented the following exception:

PlatformException (PlatformException(error, Attempt to invoke virtual method 'boolean android.view.inputmethod.BaseInputConnection.setComposingRegion(int, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.inputmethod.BaseInputConnection.setComposingRegion(int, int)' on a null object reference

The full exception:

Exception has occurred.
PlatformException (PlatformException(error, Attempt to invoke virtual method 'boolean android.view.inputmethod.BaseInputConnection.setComposingRegion(int, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.inputmethod.BaseInputConnection.setComposingRegion(int, int)' on a null object reference
    at io.flutter.plugin.editing.ListenableEditingState.setComposingRange(ListenableEditingState.java:141)
    at io.flutter.plugin.editing.ListenableEditingState.setEditingState(ListenableEditingState.java:158)
    at io.flutter.plugin.editing.ListenableEditingState.<init>(ListenableEditingState.java:61)
    at io.flutter.plugin.editing.TextInputPlugin.setTextInputClient(TextInputPlugin.java:423)
    at io.flutter.plugin.editing.TextInputPlugin$1.setClient(TextInputPlugin.java:133)
    at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:75)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
    at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
))

**Expected results:** 
keyboard will come up and the textfield will be edited...

**Actual results:** 
in the case of an empty scaffold, it reloads the app.

when I open it from a drawer, it does not reload the app, but after the exception occurs no text editing can be done.
in the case of the drawer, the issue only occurs if there is already some text in the appended controller.

<details>
<summary>Code sample</summary>

here is the test scaffold i'm using:

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by kobi666** [comment] 2022-01-13 17:50
sorry the form was a bit messy.
here is the flutter doctor output:
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.18363.1316], locale en-IL)
    • Flutter version 2.8.1 at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Kobs\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.3
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Kobs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.1316]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!


I don't know how to attach the whole analyze output here as it's too long

**Comment by kobi666** [comment] 2022-01-14 00:34
please close,
this is a duplicate of https://github.com/flutter/flutter/issues/96570

**Comment by danagbemava-nc** [comment] 2022-01-14 07:31
Duplicate of #96570

**Closed by danagbemava-nc** 2022-01-14 07:31 UTC
Labels: in triage
