### ISSUE TITLE
Dart test returned: Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by jeremybeal11** [flutter/flutter#72452] opened 2020-12-16 18:08 UTC
## Context
Working on a project that views data in the CSV and stores it all in a list. Before, when testing out the file: `dart data_file.dart` it was able to return the content that I requested to be printed showed in the terminal. Now i am constanly seeing the following error:

```
Unable to spawn isolate: ../flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
  import 'dart:ui' as ui show Paint, Path, Canvas;
         ^
  ../flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' as ui;
         ^
  ../flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_sheet.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
```

I have ran the following command: `dart run test` and recieved the following:
```
Precompiling executable... (11.8s)
Precompiled test:test.
00:14 +0 -1: loading test/widget_test.dart [E]                                                                                                         
  Failed to load "test/widget_test.dart":
  Unable to spawn isolate: ../flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
  import 'dart:ui' as ui show Paint, Path, Canvas;
         ^
  ../flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' as ui;
         ^
  ../flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_sheet.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
  ../flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show lerpDouble;
         ^
00:14 +0 -1: Some tests failed.   
 ```

## Enviroment
- VScode
- macOSX 
- flutter version:
```flutter --version
Flutter 1.25.0-9.0.pre.88 • channel master • https://github.com/flutter/flutter.git
Framework • revision e24e763872 (6 hours ago) • 2020-12-16 07:33:03 -0500
Engine • revision e9f2f0eaea
Tools • Dart 2.12.0 (build 2.12.0-157.0.dev)
```

Any solutions, tips or help will be greatly appreciated!

**Comment by jonahwilliams** [comment] 2020-12-16 23:50
If you test depends on `flutter` or `dart:ui`, you need to use `flutter test`, not `dart` or `pub` commands.

**Comment by jeremybeal11** [comment] 2020-12-17 16:26
Thanks @jonahwilliams, and by doing so i have the following error:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following HiveError was thrown attaching to the render tree:
Box not found. Did you forget to call Hive.openBox()?

When the exception was thrown, this was the stack:
#0      HiveImpl._getBoxInternal (package:hive/src/hive_impl.dart:170:7)
#1      HiveImpl.box (package:hive/src/hive_impl.dart:181:33)
#2      _MyAppState.initState (package:app/main.dart:50:25)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4821:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3386:20)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1211:16)
#8      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1189:5)
#9      RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1203:7)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2777:33)
#12     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1110:19)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:321:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#16     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:977:9)
#19     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#20     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:964:27)
#21     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#25     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#26     main.<anonymous closure> (file://.../app/test/widget_test.dart:16:18)
#27     main.<anonymous closure> (file://.../app/test/widget_test.dart:14:48)
#28     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace) 
```

I do have the box opened in the initilaizer. I personally think it's a possible issue with the dart SDK inside flutter because when i run `dart file.dart` with out even importing `'dart:io'; it get the same return as before `Error: Not found: 'dart:ui'`

**Comment by darshankawar** [comment] 2020-12-18 06:25
@jeremybeal11 
Can you provide a complete reproducible code sample along with steps you take which shows this issue ?

**Comment by jeremybeal11** [comment] 2020-12-18 16:23
file name: `drinklist.dart`
```
import 'dart:io';
import 'package:csv/csv.dart' as csv;
//import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

List drinkNames = [];
List drinkDesc = [];
File myData = new File('./myCSV.csv');

//Box _drinkList;

void main() {
  //Hive.registerAdapter(MenuAdapter());
  getDrinkNames();
  getDrinkDesc();
}

getDrinkNames() {
  List<List<dynamic>> csv = csvToList(myData);
  for (int i = 0; i < csv.length; i++) {
    drinkDesc.add(csv[i][1]);
    drinkNames.add(csv[i][0]);
    
  }
  print(drinkNames);
}

getDrinkDesc() {
  List<List<dynamic>> csv = csvToList(myData);
  for (int i = 0; i < csv.length; i++) {
    drinkDesc.add(csv[i][1]);
  }
  //print(drinkDesc);
}

List<List> csvToList(File myData) {
  csv.CsvToListConverter c =
      new csv.CsvToListConverter(eol: "\r\n", fieldDelimiter: ",");
  List<List> listCreated = c.convert(myData.readAsStringSync());
  return listCreated;
}
```

All i did was run `dart drinklist.dart` and recieved the error.

**Comment by darshankawar** [comment] 2020-12-21 06:40
@jeremybeal11 
Thanks for the code sample. By running `dart drinklist.dart` I see below in console log:

```
dhs@Dhss-MacBook-Pro testapp % dart test/drinklist.dart
../../Fluttersdk/flutter/packages/flutter/lib/src/foundation/basic_types.dart:9:1: Error: Not found: 'dart:ui'
export 'dart:ui' show VoidCallback;
^
../../Fluttersdk/flutter/packages/flutter/lib/src/foundation/binding.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show SingletonFlutterWindow, Brightness, PlatformDispatcher, window;
       ^
../../Fluttersdk/flutter/packages/flutter/lib/src/foundation/debug.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Brightness;
       ^
../../Fluttersdk/flutter/packages/flutter/lib/src/foundation/key.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues;
       ^


```

By running `flutter test test/drinklist.dart`, I get below error:

```
dhs@Dhss-MacBook-Pro testapp % flutter test test/drinklist.dart
00:02 +0 -1: loading /Users/dhs/Documents/NCFlutter/testapp/test/drinklist.dart [E]                                                                                                           
  Failed to load "/Users/dhs/Documents/NCFlutter/testapp/test/drinklist.dart": Cannot open file, path = './myCSV.csv' (OS Error: No such file or directory, errno = 2)
  dart:io                    _File.readAsStringSync
  test/drinklist.dart 39:45  csvToList
  test/drinklist.dart 19:29  getDrinkNames
  test/drinklist.dart 14:3   main
  
00:02 +0 -1: Some tests failed.   
```

What's the expected result by running both type of commands ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.86 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

**Comment by jeremybeal11** [comment] 2020-12-21 14:43
Hey @darshankawar thanks for looking into it. The expected behavior is that it's supposed to return the list created from the CSV. I surprisingly enough worked when I kept running the file(almost got excited) but resume to display the above errors. 

When I ran the flutter test command I have received the same errors as you have. 

when running `flutter doctor -v` i got this:

```
flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.45, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.45 at /Users/.../flutter
    • Framework revision e24e763872 (5 days ago), 2020-12-16 07:33:03 -0500
    • Engine revision e9f2f0eaea
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/.../Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

I'm just not sure why it randomly displayed the list(as it should) and all of a sudden returned the error. 

my speculation is that it's something to do with the Dart SDK thats inside the flutter package, but not entirely sure just yet.

**Comment by jonahwilliams** [comment] 2021-01-05 18:14
Closing because this is not a bug. flutter test is for flutter programs, dart test is for dart programs.

**Closed by jonahwilliams** 2021-01-05 18:14 UTC
Labels: a: tests, dependency: dart, found in release: 1.26, has reproducible steps, passed first triage, tool

**Comment by Vrushti24** [comment] 2021-03-15 15:35
Is this issue still open because facing the same issue but still haven't found any solution @jonahwilliams

**Comment by pstricks-fans** [comment] 2021-03-17 07:18
The same issue here.

**Comment by palikollar** [comment] 2021-03-18 06:21
I got the same issue with a brand new flutter app, running the _test/widget_test.dart_ in android studio.

> Android Studio 4.1.2
> Build #AI-201.8743.12.41.7042882, built on December 20, 2020
> Runtime version: 1.8.0_242-release-1644-b01 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

```
C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --enable-asserts C:\projects\flutter-research\unit_testing\test\widget_test.dart
/C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/bottom_navigation_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
/C:/src/flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^

Process finished with exit code 254
```

flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio (version 4.1.0)
> [√] IntelliJ IDEA Community Edition (version 2020.3)
> [√] VS Code (version 1.54.3)
> [√] Connected device (3 available)
> 
> • No issues found!

**Comment by Crazy-MT** [comment] 2021-03-23 05:59
The same issue here.

**Comment by jhionan** [comment] 2021-05-03 23:03
I had this issue, and was the wrong import path
for example:
instead of importing
import 'package:buzzao_ble_protocol/src/models/session.dart';
it imported the package file where export this file.

**Comment by ollolollollooloo** [comment] 2021-07-07 14:13
same here

**Comment by evaisse** [comment] 2021-07-13 16:46
Same problem here, 

I was launching a flutter test command, but at some point, for no reason, those errors start to pop.

I am definitely using a "flutter" command, 

`flutter drive -d emulator-5554 --target=test_integration/driver/app_target.dart --driver=/Users/my/app/test_integration/tests/intialize/splashscreen_test.dart --dart-define=MOCK_SESSION_ID=6160edc03437c894.07960931`

```
Running "flutter pub get" in application_fr_kador_02...          1 312ms
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        10,9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1 488ms
I/flutter (10759): Observatory listening on http://127.0.0.1:40189/Kdwqk8Y8CIE=/
Installing build/app/outputs/flutter-apk/app.apk...              1 488ms
I/flutter (10759): Observatory listening on http://127.0.0.1:40189/Kdwqk8Y8CIE=/
/usr/local/opt/flutter/packages/flutter/lib/src/cupertino/action_sheet.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
/usr/local/opt/flutter/packages/flutter/lib/src/cupertino/bottom_tab_bar.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
/usr/local/opt/flutter/packages/flutter/lib/src/cupertino/colors.dart:5:8: Error: Not found: 'dart:ui'
```


**Flutter doctor below**

```
$ flutter doctor -v

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /usr/local/opt/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/evaisse/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE Manu (mobile)     • 3106633b7f0a4a8cb24c445801b913b39a9d1b33 • ios            • iOS 14.6
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
