### ISSUE TITLE
http is  very slow

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#20419] opened 2018-08-10 09:50 UTC
http response is very slow

**Comment by zoechi** [comment] 2018-08-23 08:48
Can you please provide more information about to reproduce?
Can you please elaborate on "slow"?
Is this only in debug or also in release mode?
What requests are you making to what server?
Is the name resolution slow or the data transfer?

Please also add the output of `flutter doctor -v`.

**Comment by lyqiai** [comment] 2018-08-23 08:51
updated flutter SDK solution to the problem，thinks

**Comment by zoechi** [comment] 2018-09-02 09:39
Does this mean the problem is solved?

**Comment by zoechi** [comment] 2018-10-08 09:13
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 09:13 UTC
Labels: waiting for customer response

**Comment by Kings9924** [comment] 2019-04-25 19:00
it means fetch data from url is very very slow. it takes more than one minute to get info form the url

**Comment by Kings9924** [comment] 2019-04-25 19:00
can anyone help solve this issues thanks in advance

**Comment by natebosch** [comment] 2019-04-25 19:04
This is almost certainly not an issue that can be solved in `package:http`. Please verify that using `curl` or some other request is faster and then reproduce the problem with `dart:io` directly and file an issue against the SDK repo with reproduction instructions. If you can't repro with `dart:io` and believe it is this package that is causing the slowdown reply here with repro instructions.

**Comment by xXUlquiXx** [comment] 2019-09-13 15:35
Maybe something is related with modsecurity and apache, some config make's the requests slow.
I Have the same problem, and searching on google i found that explanation, but no idea how to solve.

**Comment by HumbleCarl** [comment] 2020-01-24 07:07
How can I fix slow http request?

**Comment by babang1da** [comment] 2020-02-12 12:34
same problem

**Comment by wanjm** [comment] 2020-12-18 05:08
same problem why it is closed;

**Comment by leszekkrol** [comment] 2020-12-28 12:10
Any update?

**Comment by yusufnadar** [comment] 2020-12-30 20:25
> Any update?

Do you have any solution dude?

**Comment by DartPads** [comment] 2021-02-14 17:23
Please reopen. http calls are indeed very slow on emulator. The same URLs are at expected speed when opened using a browser, however take upwards of 2-3 minutes when called with http.

**Comment by KanybekMomukeyev** [comment] 2021-04-12 06:27
Same here, post is tooo slow.

**Comment by xwaxes01** [comment] 2021-04-22 13:25
Same problem here as well. We have two apps, one in native Android(Java), and the other in Flutter, being served from the same API and the native app takes less than a second to call API while flutter one takes nearly two seconds.
