### ISSUE TITLE
App crash quickly when start on iOS17

### ISSUE THREAD

**Issue by heijianye** [flutter/flutter#156635] opened 2024-10-12 05:59 UTC
### Steps to reproduce

This issue happens online app running on iOS 17, but I can not reproduce on iOS by hand.
We catch this issue by bug report of ios app.

### Expected results

App do not crash on iOS 17.

### Actual results

App will crash probably on iOS17 during start process.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>The Crash thread information for this issue is as follows: </summary>

```console
Thread 29 Crashed:
0 AGXMetalG15 0x00000002313f2b58 0x230f58000 + 4827992 (<redacted> + 2100)
1 (null) 0x000000000000007f 0x0 + 127
2 AGXMetalG15 0x00000002313b7520 0x230f58000 + 4584736 (<redacted> + 1720)
3 AGXMetalG15 0x00000002313b6e5c 0x230f58000 + 4583004 (<redacted> + 92)

4 Flutter 0x000000010af7b858 0x10aa40000 + 5486680
impeller::TextureMTL::OnSetContents(unsigned char const*, unsigned long, unsigned long) (in Flutter) ([texture_mtl.mm:96](http://texture_mtl.mm:96/))

5 Flutter 0x000000010ad9edb0 0x10aa40000 + 3534256
impeller::Texture::SetContents(std::_fl::shared_ptr<fml::Mapping const>, unsigned long, bool) (in Flutter) ([texture.cc:41](http://texture.cc:41/))

6 Flutter 0x000000010afb3518 0x10aa40000 + 5715224
flutter::ImageDecoderImpeller::UploadTextureToStorage(std::_fl::shared_ptr<impeller::Context> const&, std::_fl::shared_ptr<SkBitmap>, std::_fl::shared_ptr<fml::SyncSwitch> const&, impeller::StorageMode, bool) (in Flutter) ([image_decoder_impeller.cc:428](http://image_decoder_impeller.cc:428/))

7 Flutter 0x000000010afb2bfc 0x10aa40000 + 5712892
std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'(), std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1::operator()() const::'lambda'()>, void ()>::operator()() (in Flutter) (function.h:359)

8 Flutter 0x000000010ad28f08 0x10aa40000 + 3051272
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) ([message_loop_impl.cc:128](http://message_loop_impl.cc:128/))

9 Flutter 0x000000010ad2c6bc 0x10aa40000 + 3065532
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) ([message_loop_darwin.mm:86](http://message_loop_darwin.mm:86/))

10 CoreFoundation 0x0000000191958a2c 0x1918a1000 + 752172 (<redacted> + 32)
11 CoreFoundation 0x00000001919586d0 0x1918a1000 + 751312 (<redacted> + 1004)
12 CoreFoundation 0x000000019195822c 0x1918a1000 + 750124 (<redacted> + 288)
13 CoreFoundation 0x00000001918f4888 0x1918a1000 + 342152 (<redacted> + 1856)
14 CoreFoundation 0x00000001918f3cd8 0x1918a1000 + 339160 (CFRunLoopRunSpecific + 608)
15 Flutter 0x000000010ad2c7a8 0x10aa40000 + 3065768
fml::MessageLoopDarwin::Run() (in Flutter) ([message_loop_darwin.mm:52](http://message_loop_darwin.mm:52/))

16 Flutter 0x000000010ad2be20 0x10aa40000 + 3063328
void* std::_fl::__thread_proxy[abi:v15000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::Thread::Thread(std::_fl::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>>(void*) (in Flutter) (thread:295)

17 libsystem_pthread.dylib 0x00000001ee37606c 0x1ee370000 + 24684 (_pthread_start + 136)
```

</details>

### Flutter Doctor output

<details open><summary>App is build on server by Jenkins, so I can not get the information of  doctor output immediately, will add later, but it can be confirmed that flutter version 3.19.3.</summary>

```console

```

</details>

**Comment by iapicca** [comment] 2024-10-12 11:46
> but it can be confirmed that flutter version 3.19.3.

@heijianye 
this version is more than 6 months old, does the issue occur with the latest stable?

**Comment by darshankawar** [comment] 2024-10-14 07:10
@heijianye 
Based on the error log provided, it looks similar to https://github.com/flutter/flutter/issues/141554 which was closed citing [this](https://github.com/flutter/flutter/issues/141554#issuecomment-2322936775) as the reason.
If you have concrete steps to replicate along with reproducible code sample, please provide us the same, so as to make the issue actionable.
Closing for now based on the linked comment.

**Closed by darshankawar** 2024-10-14 07:10 UTC
Labels: in triage
