### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by Ismailhamroun90** [flutter/flutter#159747] opened 2024-12-03 20:10 UTC
## Command
```sh
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1465:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1332:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:933:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:682:48)
#7      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:660:43)
#8      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:483:25)
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:508:29)
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:369:37)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.5, on Microsoft Windows [version 10.0.17134.1304], locale fr-CH)
    • Flutter version 3.24.5 on channel stable at C:\Nouveau dossier\flutter_windows_3.24.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Atelier\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35521.163
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at C:\Users\Atelier\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.103.20241202

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.17134.1304]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2024-12-04 07:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-12-04 07:18 UTC
Labels: in triage
