### ISSUE TITLE
Text widget should have 'ellipsis' property, And text if too long should hide the long part or 'ellipsis' 

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#974] opened 2015-12-17 09:02 UTC

**Comment by tain335** [comment] 2015-12-17 09:14
![Uploading Screenshot_2015-12-17-17-12-43.png…]()

**Comment by tain335** [comment] 2015-12-17 09:17
![screenshot_2015-12-17-17-12-43](https://cloud.githubusercontent.com/assets/5304597/11865884/0e464bd8-a4e2-11e5-8a8a-c291c99d6400.png)

**Comment by eseidelGoogle** [comment] 2015-12-17 16:35
Hard to tell what's going on in the picture.  The red likely indicates an exception happened during widget construction, I might recommend checking `flutter logs` to be sure.

That said, this seems like a very reasonable request of our Text widget.

**Comment by HansMuller** [comment] 2016-02-29 23:49
I think this is a duplicate of https://github.com/flutter/flutter/issues/417

**Comment by abarth** [comment] 2016-05-04 03:55
Duplicate of #417

**Closed by abarth** 2016-05-04 03:55 UTC
Labels: ⚠ brand new feature
