### ISSUE TITLE
most of the cards in the <elided application> have some weird garbled text

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#53263] opened 2020-03-25 15:38 UTC
https://b.corp.google.com/issues/152100618

**Comment by kf6gpe** [comment] 2020-04-07 17:13
Googler hasn't been able to reproduce due to setup / configuration problems while sheltering-in-place. Perhaps escalate to @cbracken, who may have a similar setup and can try?

**Comment by kf6gpe** [comment] 2020-04-14 18:15
gentle ping to @cbracken and @chinmaygarde; is there an update here?

**Comment by chinmaygarde** [comment] 2020-04-14 18:19
No update since I would not reproduce it in the test harness. I also don't expect to make progress reproducing this on device till I get back to the office.

**Comment by kf6gpe** [comment] 2020-04-21 18:15
Direction from upstream filer is for us to review some linked bugs on the upstream request.

**Comment by kf6gpe** [comment] 2020-04-28 16:49
@chinmaygarde, did you have any luck with the linked bugs on the upstream request yet?

**Comment by Hixie** [comment] 2020-05-12 22:52
I'm going to close this. The upstream bug was sent back to the customer for a repro.

**Closed by Hixie** 2020-05-12 22:52 UTC
Labels: customer: dream (g3), engine, severe: customer critical
