### ISSUE TITLE
CFBundle Version error with iOS when creating Plugins

### ISSUE THREAD

**Issue by itsyashjoshi** [flutter/flutter#35510] opened 2019-07-03 05:26 UTC
> Bundles without a CFBundleVersion are invalid and can’t be properly installed on devices or simulators. CoreSimulator now checks and rejects such bundles earlier in the process with a clearer error message. (49892531 ~[Apple](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes)   

## Problem
When we create flutter plugin, flutter creates an example flutter application to test the plugin, and when we try to run the same, Xcode don't let it build as Apple have updated CoreSimulator properties and apps without CFBunndle Versions will directly crash.
Although flutter enters `$(FLUTTER_BUILD_NUMBER)` as `CFBundleVersion` but `FLUTTER_BUILD_NUMBER` is not mentioned anywhere.

### Way to reproduce:
* Create new flutter Plugin
* Open terminal > `cd example` > `flutter run` (Select your iOS simulator prior this)
This will give you the error 
 
### Temprory Solution
(**If you are planning to keep Xcode Beta version in your system**)
* Open `Runner.xcworkspace` in Xcode
* Select `Runner`>`Target`
* Remove `$(FLUTTER_BUILD_NUMBER)` from Build 
* Replace `1.0.0.0` also replace `Version` to `1.0.0`
* Hit `Run`
(**If you can throw beta in trash**)
* Move Xcode Beta to trash
* Quit Xcode and Simulator
* cd  /Library`
* Delete `Developer` folder (or rename for precaution)
* Open Xcode
* It will ask you to install some files, hit `Allow`.
This will install required files for Xcode 10 and you will be able to run things without hassle.

 ---
Please fix this problem so that till the time of release of Xcode 11, we won't have to face the same issue.

**Comment by jmagman** [comment] 2019-07-26 21:46
Temporary workaround in pubspec:
```
version: 1.0.0+1.0.0
```
`flutter clean`
Duplicate of https://github.com/flutter/flutter/issues/34477, fix incoming (apologies for the forward-duplication, you filed before that one!)

**Closed by jmagman** 2019-07-26 21:46 UTC
