### ISSUE TITLE
Blur effect are gone after upgrade flutter

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#72228] opened 2020-12-13 09:42 UTC
I am using this repo for fantastic blur effect transition effect: https://github.com/fluttercandies/ripple_backdrop_animate_route

But when upgrade flutter ,the blur effect are gone.....

I am totally missed here, what should I do?? Flutter just uprade their APIs so fast and most of time it will break some lib that I use, But I am not very familliar with **every single lib**.

Does anyone could help me why the blur effect are gone after flutter upgrade???

**Comment by yash1200** [comment] 2020-12-13 12:02
I tried this package and didn't get any error while running it's example in web.
Flutter doctor -v
```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.42, on Linux, locale en_IN.utf8)
    • Flutter version 1.25.0-9.0.pre.42 at /home/yash/flutter
    • Framework revision a76bb1a08e (29 hours ago), 2020-12-12 00:17:51 -0700
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/yash/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/yash/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-beta

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0
    • cmake version 3.19.1
    • ninja version 1.10.1
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /home/yash/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.66 beta
```

**Comment by iapicca** [comment] 2020-12-13 18:14
@jinfagang 
can you provide your `flutter doctor -v` and a minimal code sample that does not rely on 3rd party packages

**Comment by jinfagang** [comment] 2020-12-14 02:49
@ianloic @iapicca My flutter version is:

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.42, on Linux, locale zh_CN.utf8)
    • Flutter version 1.25.0-9.0.pre.42 at /home/users/development/flutter
    • Framework revision a76bb1a08e (29 hours ago), 2020-12-12 00:17:51 -0700
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)
```

I think the minimal code is the example project inside:  https://github.com/fluttercandies/ripple_backdrop_animate_route

it previously have beautiful blur effect as you can see 

![image](https://user-images.githubusercontent.com/21303438/102034828-f31f5500-3df9-11eb-9b0c-ec2c5a99f36c.png)


But after upgrde, the blur effect are gone, became transparent. I don;t know why and I post a issue of that lib but author doesn;t response.

**Comment by pedromassangocode** [comment] 2020-12-14 08:42
Hi @jinfagang 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercandies/ripple_backdrop_animate_route).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-14 08:42 UTC
