### ISSUE TITLE
Can't tap on specific TextSpan with GestureRecognizer in driver tests.

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#67123] opened 2020-10-02 09:41 UTC
## Steps to Reproduce

```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text.rich(TextSpan(
            text: 'Something something something. ',
            children: [
              TextSpan(
                text: 'Tap me.',
                recognizer: TapGestureRecognizer()
                  ..onTap = () => print('Hello there!'),
              ),
            ],
          )),
        ),
      ),
    );
  }
}
```

**Expected results:** I'm able to write a `driver.tap(finder.byText('Tap me.'))` or anything else to test whether clicking a link does what I want it to do.

**Actual results:** I can't make driver tests tap exactly on this link.

```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (3 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

**Comment by darshankawar** [comment] 2020-10-02 10:26
@Albert221 
Flutter driver doesn't yet fully support `RichText` widget implementation. Please see [this](https://github.com/flutter/flutter/pull/48809) PR for reference along with this comment.

**Comment by darshankawar** [comment] 2020-10-02 10:26
closed by accident and typed in too early -)

**Comment by Albert221** [comment] 2020-10-02 10:34
Hm, okay, I then gotta wait for a fix for that. For now I'll just transform this `RichText` to a `Row` which isn't ideal but will serve as a temporary fix.

But I'm not sure why did you mark the issue as 'waiting for customer response' :)

**Comment by darshankawar** [comment] 2020-10-02 10:43
@Albert221 Friday distraction.. :-).

Closing as duplicate of [62489](https://github.com/flutter/flutter/issues/62489)

**Closed by darshankawar** 2020-10-02 10:43 UTC
Labels: in triage
