### ISSUE TITLE
[Web] Accessibility broken

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#82779] opened 2021-05-18 03:55 UTC
Using JAWS with flutter web app seems pretty broken.

Navigation with arrow keys kind of announces most of the semantic widgets but tab navigation is broken and pressing enter or space on buttons for example doesn't work at all.

In my opinion flutter for web is not accessible at all at the moment and therefore pretty much a no go for any serious web application.

I hope this is just a bug and can be addressed easily.

You can reproduce it with the default flutter web start app and latest JAWS on Windows 10 in all browsers.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.56.1)
[√] Connected device (2 available)

**Comment by TahaTesser** [comment] 2021-05-18 12:25
Hi @BerndWessels 
This is a duplicate of https://github.com/flutter/flutter/issues/75881
Closing, thank you

**Closed by TahaTesser** 2021-05-18 12:25 UTC
Labels: in triage
