### ISSUE TITLE
Make "Shift" + scrolling wheel to be horizontal scroll on Win10

### ISSUE THREAD

**Issue by fufesou** [flutter/flutter#112910] opened 2022-10-05 04:21 UTC
## Use case

Easy horizontal scroll.

## Proposal

Scrolling wheel while pressing "Shift" is equal to "Horizontal Scroll" on Win10.

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final ScrollController horizontal = ScrollController();
    final ScrollController vertical = ScrollController();
    return Scrollbar(
        controller: vertical,
        thumbVisibility: true,
        trackVisibility: true,
        child: Scrollbar(
            controller: horizontal,
            thumbVisibility: true,
            trackVisibility: true,
            notificationPredicate: (notif) => notif.depth == 1,
            child: SingleChildScrollView(
              controller: vertical,
              child: SingleChildScrollView(
                controller: horizontal,
                scrollDirection: Axis.horizontal,
                child: SizedBox(
                  width: 1920,
                  height: 1080,
                  child: Container(
                    decoration: const BoxDecoration(
                      gradient: LinearGradient(
                          colors: [
                            Colors.blue,
                            Colors.red,
                          ],
                          begin: FractionalOffset(0.0, 0.0),
                          end: FractionalOffset(1.0, 1.0),
                          stops: [0.0, 1.0],
                          tileMode: TileMode.clamp),
                    ),
                  ),
                ),
              ),
            )));
  }
}

```

**Comment by darshankawar** [comment] 2022-10-05 10:34
Closing this as duplicate of https://github.com/flutter/flutter/issues/75180

**Closed by darshankawar** 2022-10-05 10:34 UTC
Labels: new feature, framework, f: scrolling, platform-windows, proposal, a: desktop, a: mouse
