### ISSUE TITLE
[url_launcher] iOS Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by hchaviano** [flutter/flutter#156979] opened 2024-10-16 13:56 UTC
### Steps to reproduce

1- Create a basic Flutter app (Counter)
2- Add url_launcher package (any version)
3- Add the corresponding configuration for iOS following the official doc
4- Try to launch a Facebook page like: `launchUrl(Uri.parse('https://facebook.com/ebonymag')); `
5- Run the app on iOS

### Expected results

The page should be opened in Safari without issues

### Actual results

![Screenshot 2024-10-16 at 10 53 25 AM 3](https://github.com/user-attachments/assets/b5ad9e36-523b-49bf-ad83-c6a9a2f71c93)

### Code sample

<details open><summary>Code sample</summary>

```dart
launchUrl(Uri.parse('https://facebook.com/ebonymag'));
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.2 23C64 darwin-arm64, locale en-UY)
    • Flutter version 3.24.3 on channel stable at /Users/haironchaviano/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/haironchaviano/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/haironchaviano/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Hairon’s iPhone (mobile)        • 00008130-001260E82E04001C • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.101

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by stuartmorgan** [comment] 2024-10-16 18:49
Duplicate of https://github.com/flutter/flutter/issues/89949 and https://github.com/flutter/flutter/issues/83243.

**Closed by stuartmorgan** 2024-10-16 18:49 UTC
