### ISSUE TITLE
Hot Reloading on Real Device

### ISSUE THREAD

**Issue by StaleExam19** [flutter/flutter#93857] opened 2021-11-18 12:45 UTC
I can't see hot reloading option with real device. Is hot reloading available using real device?
![image](https://user-images.githubusercontent.com/94615588/142417401-fed04430-b212-4274-82fd-000d4a9be4f0.png)

**Comment by danagbemava-nc** [comment] 2021-11-18 13:44
Hi @StaleExam19, hot reloading is possible on real devices, there is however an issue with `Vivo` devices, which is currently being tracked here https://github.com/flutter/flutter/issues/82520. 

Kindly follow up there for more information. 

Closing as duplicate of https://github.com/flutter/flutter/issues/82520.

**Closed by danagbemava-nc** 2021-11-18 13:44 UTC
Labels: in triage
