### ISSUE TITLE
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack traces to the framework, such as during tests.

### ISSUE THREAD

**Issue by rohitp20** [flutter/flutter#124308] opened 2023-04-06 07:49 UTC
```
package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 192 pos 7: 'line != '===== asynchronous gap ===========================''

The relevant error-causing widget was: 
  PlantsApp PlantsApp:file:///home/rohit/AndroidStudioProjects/plants_finder/lib/main.dart:12:33
When the exception was thrown, this was the stack: 
#2      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:192:7)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:871:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:52:28)
#8      Iterable.toList (dart:core/iterable.dart:470:12)
#9      StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:93:10)
#10     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:1077:54)
#11     DiagnosticsStackTrace._applyStackFilter (package:flutter/src/foundation/assertions.dart:1273:43)
#12     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1249:17)
#13     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:732:22)
#14     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2958:17)
#15     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2961:8)
#16     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1294:56)
#17     DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2972:77)
#18     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1650:13)
#19     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1679:6)
#20     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1639:18)
#21     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:934:44)
#22     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#23     _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:9)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (13 frames)
#42     _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (9 frames)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#53     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#54     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#55     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#56     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#57     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#58     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#59     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#63     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building UncontrolledProviderScope:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  UncontrolledProviderScope UncontrolledProviderScope:file:///home/rohit/.pub-cache/hosted/pub.dev/flutter_riverpod-2.3.2/lib/src/framework.dart:250:12
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4692:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4695:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (7 frames)
#12     _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (9 frames)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#23     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#24     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#25     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#27     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#28     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#29     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#33     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
E/flutter ( 9772): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2685 pos 20: '_debugCurrentBuildTarget == context': is not true.
E/flutter ( 9772): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 9772): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 9772): #2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2685:20)
E/flutter ( 9772): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2689:12)
E/flutter ( 9772): #4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
E/flutter ( 9772): #5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
E/flutter ( 9772): #6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)

======== Exception caught by widgets library E/flutter ( 9772): #7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
=======================================================
E/flutter ( 9772): #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 9772): #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 9772): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter ( 9772): 
The following assertion was thrown building ProviderScope(state: ProviderScopeState#cb315):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ProviderScope ProviderScope:file:///home/rohit/AndroidStudioProjects/plants_finder/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4692:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4695:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#6      _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (9 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#18     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#19     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#21     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#22     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#23     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4692:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4695:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
```

**Comment by danagbemava-nc** [comment] 2023-04-06 08:55
Hi @rohitp20, this is caused by one of your packages. See https://stackoverflow.com/a/73770713 for how you can get the proper stack trace so you can fix the error on your side. 

Closing from here as this is not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2023-04-06 08:55 UTC
Labels: in triage
