### ISSUE TITLE
PUB_HOSTED_URL and  FLUTTER_STORAGE_BASE_URL in ~/.bashrc is invalid 

### ISSUE THREAD

**Issue by chenls** [flutter/flutter#70591] opened 2020-11-16 07:05 UTC
I am using Flutter in China.I add environment variables to the ~/.bashrc file:

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
 
I press F5 directly in VS Code and I will be stuck to running "fluent pub get" in xxx ..., But it is normal to execute fluent run in the terminal. I found out that add environment variables to /etc/profile the is OK.

**Comment by TahaTesser** [comment] 2020-11-16 14:38
Hi @chenls 
If it is running normal with `flutter run` in the terminal, it might be VS Code 


Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-16 14:38 UTC
