### ISSUE TITLE
can not connected my Device

### ISSUE THREAD

**Issue by TomWang1** [flutter/flutter#104306] opened 2022-05-21 03:16 UTC
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
    ! Device AEAXBB1A30000622 is not authorized.
      You might need to check your device for an authorization dialog.
    ! Error: fly的iPhone is not paired with your computer. To use fly的iPhone with Xcode, unlock it and choose to trust this computer when prompted. (code -9)
[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment] 2022-05-23 07:17
@TomWang1 
Kindly check out the comment in https://github.com/flutter/flutter/issues/99628#issuecomment-1072910852 to see if it helps. Closing as duplicate of https://github.com/flutter/flutter/issues/99628

If that comment doesn't help, kindly leave a comment below and I will reopen.

**Closed by darshankawar** 2022-05-23 07:17 UTC
Labels: in triage
