### ISSUE TITLE
How to enlarge and play the html 5 video in android, and can enlarge and play the full screen video normally in ios

### ISSUE THREAD

**Issue by xuelangjie** [flutter/flutter#134099] opened 2023-09-06 03:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

> 使用webview_flutter 包裹一个vue项目的单页，有一个视频播放功能，在ios上面可以直接放大视频全屏播放，android上面点击放大无效

Use webview_flutter to wrap a single page of a Vue project. There is a video playback function. On iOS, you can directly enlarge the video and play it in full screen. On Android, clicking to zoom in does not work.

### Proposal

> 希望可以提供这个功能或api指引

I hope you can provide this function or API guidance

**Comment by LinXunFeng** [comment] 2023-09-06 08:15
Not yet supported, but probably soon by [flutter/packages #3879](https://github.com/flutter/packages/pull/3879).

**Comment by danagbemava-nc** [comment] 2023-09-06 08:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/27101

**Closed by danagbemava-nc** 2023-09-06 08:48 UTC
Labels: in triage

**Comment by xuelangjie** [comment] 2023-09-06 10:13
我想知道这个问题现在是否解决，或者是否有解决方案，我目前看文档没有发现怎么解决
