### ISSUE TITLE
[video_player] Add option to specify the rate of VideoPlayerValue updates

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#96526] opened 2022-01-12 13:38 UTC
## Use case

Currently the rate of updates for the `VideoPlayerValue` of the `VideoPlayerController` is set to a hardcoded 500ms in `_applyPlayPause()`.

There is no way to get faster updates (i.e. every millisecond).

## Proposal

Add a new configuration option to `VideoPlayerOptions` that is passed to the Timer in `_applyPlayPause()`, which defaults to the current value `const Duration(milliseconds: 500)`.

**Comment by danagbemava-nc** [comment] 2022-01-12 14:03
Hi @navaronbracke, I'm curious, can you share a bit more about your use case that requires that you may need faster updates to the VideoPlayerValue?

**Comment by navaronbracke** [comment] 2022-01-12 14:13
I am building a video timeline widget with a line that indicates the current position in the video while it is playing. Currently it jumps every 500ms (because the video player value is the position source). I'd like to make it smoother. I'm not sure if an implicitly animated widget would be a good solution to smoothen out the gaps between updates.

**Comment by stuartmorgan** [comment] 2022-01-12 14:51
Duplicate of https://github.com/flutter/flutter/issues/90080

**Closed by stuartmorgan** 2022-01-12 14:51 UTC
Labels: in triage
