### ISSUE TITLE
Shift-Digit Shortcuts are broken on macOS

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#90167] opened 2021-09-16 03:39 UTC
## Shift Keyboard Key not detected

A while ago, almost all keyboard shortcuts in our app stopped working. Now, I investigated it and realized that **shift** is completely broken.

That is, any `shortcuts` that use shift do not work. That applies both to `SingleActivator` as well as `LogicalKeySet`; [`LogicalKeyboardKey.shift`](https://api.flutter.dev/flutter/services/LogicalKeyboardKey/shift-constant.html) simply seems to be broken. This happens to our users on Chrome using any device (Windows laptop, Macbook, w/e).

---

```dart
SingleActivator(
  LogicalKeyboardKey.keyA,
)
```

Is detected but:

```dart
SingleActivator(
  LogicalKeyboardKey.keyA,
  shift: true,
)
```

is not detected. All the other modifiers still work.

## Steps to Reproduce

1. Run `flutter create bug --platforms=web`.
2. Update `main.dart` as follows:

<details><summary>Click to expand code snippet</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shift is broken',
      shortcuts: const {
        SingleActivator(
          LogicalKeyboardKey.keyA,
          control: true,
        ): PrintIntent(false),
        SingleActivator(
          LogicalKeyboardKey.keyA,
          shift: true,
        ): PrintIntent(true),
      },
      actions: {
        PrintIntent: CallbackAction<PrintIntent>(onInvoke: (intent) {
          if (intent.shift) {
            // This is never called.
            print('Shift is working');
            return;
          }
          print('Control is working.');
        }),
      },
      builder: (context, child) {
        return const Focus(
          autofocus: true,
          child: Placeholder(),
        );
      },
    );
  }
}

class PrintIntent extends Intent {
  const PrintIntent(this.shift);

  final bool shift;
}
```

</details>

3. Run `cd bug` and `flutter run -d chrome`.
4. Focus the window.
5. Press CTRL + A.
6. Press SHIFT + A.

**Expected results:** `Control is working.` and then `Shift is working.`

**Actual results:** `Control is working.` only.

<details>
  <summary>Logs</summary>

```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 374ms.
Control is working.
Control is working.
Control is working.
```

```
[✓] Flutter (Channel dev, 2.6.0-5.1.pre, on Microsoft Windows [Version 10.0.19042.1165], locale en-150)
    • Flutter version 2.6.0-5.1.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f2903d3da5 (7 days ago), 2021-09-08 12:44:29 -0700
    • Engine revision 0bd9be379a
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Connected device (3 available)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
```

</details>

**Comment by maheshmnj** [comment] 2021-09-16 09:56
Hi @creativecreatorormaybenot, Thanks for filing the issue. I am able to replicate the issue on the latest stable `2.5.0` as well as the latest `master 2.6.0-6.0.pre.114`. Shift shortcuts work perfectly fine on the older version (stable 2.2.3) this can be verified with the below code sample.

It seems like this is a regression introduced in https://github.com/flutter/flutter/pull/80756

For the code sample below which looks for keybindings `ctrl+N` or `shift+N`

The keybinding `shift+N` works if N is pressed first followed by shift. But this doesn't work for the above example  which uses `SingleActivator`

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Colors.blue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: HomeworkPane(name: 'Homework'),
        ),
      ),
    );
  }
}

class NewHomeworkIntent extends Intent {
  const NewHomeworkIntent({required this.name});

  final String name;
}

class HomeworkPane extends StatefulWidget {
  const HomeworkPane({Key? key, required this.name}) : super(key: key);

  final String name;

  @override
  _HomeworkPaneState createState() => _HomeworkPaneState();
}

class _HomeworkPaneState extends State<HomeworkPane> {
  final List<String> _homework = <String>[];

  void _createNewHomework(String name) {
    print('Creating new homework $name');
    setState(() {
      _homework.add(name);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.keyN):
            NewHomeworkIntent(name: '${widget.name} ${_homework.length + 1}'),
        LogicalKeySet(LogicalKeyboardKey.shift, LogicalKeyboardKey.keyN):
            NewHomeworkIntent(name: '${widget.name} ${_homework.length + 1}'),
      },
      child: Actions(
        actions: <Type, Action<Intent>>{
          NewHomeworkIntent: CallbackAction<NewHomeworkIntent>(
              onInvoke: (NewHomeworkIntent intent) =>
                  _createNewHomework(intent.name)),
        },
        child: Focus(
          autofocus: true,
          child: Column(
            children: <Widget>[
              const Text('List of Homework'),
              ..._homework.map<Widget>((String name) => Text(name)).toList(),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>


<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel master, 2.6.0-6.0.pre.114, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.114 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd1892f04f (4 hours ago), 2021-09-15 22:17:02 -0700
    • Engine revision 5a09f16031
    • Dart version 2.15.0 (build 2.15.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter_dev
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
</details>

**Comment by creativecreatorormaybenot** [comment] 2021-09-16 14:26
@maheshmnj should I create a separate issue for the "Option (or Alt) ⌥" key?

**Comment by HansMuller** [comment] 2021-09-16 16:28
CC @justinmc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2021-09-16 17:37
@dkwingsmt it looks like when <kbd>Shift</kbd> is pressed the logical key reported for <kbd>A</kbd> is `0x00000041` and we're expecting `0x00000061`:

```
flutter: event: RawKeyUpEvent#e4f4e(logicalKey: LogicalKeyboardKey#00041(keyId: "0x00000041", keyLabel: "A", debugName: "Key A"), physicalKey: PhysicalKeyboardKey#70004(usbHidUsage: "0x00070004", debugName: "Key A")), candidatesByKey: null, candidatesByNull: null
flutter: {LogicalKeyboardKey#00061(keyId: "0x00000061", keyLabel: "A", debugName: "Key A"): [_ActivatorIntentPair#cec76(activator: Control + Key A, intent: PrintIntent#891c9), _ActivatorIntentPair#f9136(activator: Shift + Key A, intent: PrintIntent#3908e)]}
```

**Comment by justinmc** [comment] 2021-09-16 17:46
I also took a quick look at tracking down the PR that caused this, but to me it looks like it was something before both https://github.com/flutter/flutter/pull/78522 and https://github.com/flutter/flutter/pull/80756.  I was able to reproduce the bug on the commit before eb73516 from https://github.com/flutter/flutter/pull/78522.

Also just to note, the built-in shortcuts related to shift in [DefaultTextEditingShortcuts](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart) still work fine for whatever reason.

**Comment by maheshmnj** [comment] 2021-09-17 04:24
> @maheshmnj should I create a separate issue for the "Option (or Alt) ⌥" key?

Yes, if the issue is reproducible. Please file that as a separate issue.

**Comment by amanv8060** [comment] 2021-09-22 15:43
I am also facing this issue 
```
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2e647(physicalKey: PhysicalKeyboardKey#7001f(usbHidUsage: "0x0007001f", debugName: "Digit 2"), logicalKey: LogicalKeyboardKey#00032(keyId: "0x00000032", keyLabel: "2", debugName: "Digit 2"), character: null, timeStamp: 6:44:15.501000) and the recorded logical key LogicalKeyboardKey#00040(keyId: "0x00000040", keyLabel: "@", debugName: "At")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'
```

**Comment by cbracken** [comment] 2022-02-08 23:17
@dkwingsmt is this still an issue? Is there a status update?

**Comment by dkwingsmt** [comment] 2022-02-08 23:24
I haven't tested it but I think this have been fixed by https://github.com/flutter/flutter/pull/94827.

**Comment by edwardaux** [comment] 2022-02-09 00:15
I'm not the OP, but FWIW I just upgraded from 2.8 (stable) to 2.10 (stable). 

The following code which listens for `⌘⇧F` now works (it was NOT working in 2.8):
```
SingleActivator(LogicalKeyboardKey.keyF, meta: true, shift: true)
```

**Comment by FMorschel** [comment] 2022-04-25 14:22
For me, building for windows (Portuguese (Brazilian ABNT2) keyboard layout) got me that:
- Sometimes all `CTRL`  + `DigitX` would work just fine, other times none, Sticky Keys is buggy on my notebook and I couldn't figure that out (maybe this has something to do with it?),
- When I try to use `ALT` none of the digits presses are detected, and
- When using `SHIFT` only the `Digit6` works for some random reason.

<details>
  <summary>My <code>flutter doctor -v </code></summary>

```dart
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [version 10.0.19044.1645], locale fr-FR)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\felip\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\felip\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\felip\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by stephanwesten** [comment] 2022-06-17 11:53
Using Flutter version:
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (4 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604

On MacOS Montery (12.2.1) - Apple Silicon. Qwerty keyboard

Following does not seem to work in Chrome:
SingleActivator(LogicalKeyboardKey.add)
SingleActivator(LogicalKeyboardKey.digit8, shift: true) 

Shortcuts without shift do work, for example SingleActivator(LogicalKeyboardKey.minus) does work

**Comment by dkwingsmt** [comment] 2022-07-14 20:39
This should have been fixed on macOS and Windows. Web is WIP. 

For aggregated tracking, see https://github.com/flutter/flutter/issues/100456.

**Comment by LucasXu0** [comment] 2023-03-04 05:18
Hey, @dkwingsmt.

>  such as SingleActivator(LogicalKeyboardKey.digit8, shift: true) for the US keyboard "asterisk".

If we replace the `LogicalKeyboardKey.asterisk` with `LogicalKeyboardKey.digit8` for this case, then how can we customize the keyboard in which `LogicalKeyboardKey.digit8` is not representing `LogicalKeyboardKey.asterisk`?

**Comment by dkwingsmt** [comment] 2023-08-24 22:02
The Web part should have been fixed with https://github.com/flutter/engine/pull/34625, Nov 2022. This issue should have been fixed. If anyone has encountered this issue lately, feel free to reply or open a new issue with `flutter doctor --verbose`.

**Closed** 2023-09-14 22:08 UTC
Labels: a: text input, c: regression, waiting for customer response, framework, has reproducible steps, P2, found in release: 2.5, found in release: 2.6, team-desktop, triaged-desktop
