### ISSUE TITLE
Android App Crashes when using Heat Maps with empty data

### ISSUE THREAD

**Issue by ShaunAtSense** [flutter/flutter#153909] opened 2024-08-22 07:57 UTC
### Steps to reproduce

```dart
heatmaps: <Heatmap>{
  Heatmap(
    heatmapId: const HeatmapId('Default'),
    data: _heat,
    gradient: const HeatmapGradient(
      <HeatmapGradientColor>[
        HeatmapGradientColor(
          Color.fromARGB(255, 132, 255, 0),
          0.2,
        ),
        HeatmapGradientColor(
          Color.fromARGB(255, 234, 255, 0),
          0.4,
        ),
        HeatmapGradientColor(
          Color.fromARGB(255, 255, 123, 0),
          0.6,
        ),
        HeatmapGradientColor(
          Color.fromARGB(255, 255, 0, 0),
          0.8,
        ),
        HeatmapGradientColor(
          Color.fromARGB(255, 48, 0, 138),
          1,
        ),
      ],
    ),
    maxIntensity: 1,
    radius: HeatmapRadius.fromPixels(_heatRadius),
  ),
},
```

### Expected results

Heat maps to display as per iOS

### Actual results

App crashes with attached error log

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/AndroidRuntime(31245): java.lang.IllegalArgumentException: No input points.
E/AndroidRuntime(31245): 	at com.google.maps.android.heatmaps.HeatmapTileProvider$Builder.weightedData(HeatmapTileProvider.java:209)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.HeatmapBuilder.setWeightedData(HeatmapBuilder.java:29)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.Convert.interpretHeatmapOptions(Convert.java:760)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.HeatmapsController.addJsonHeatmap(HeatmapsController.java:73)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.HeatmapsController.addHeatmaps(HeatmapsController.java:39)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.GoogleMapController.updateInitialHeatmaps(GoogleMapController.java:711)
E/AndroidRuntime(31245): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMapReady(GoogleMapController.java:220)
E/AndroidRuntime(31245): 	at com.google.android.gms.maps.zzag.zzb(com.google.android.gms:play-services-maps@@18.2.0:1)
E/AndroidRuntime(31245): 	at com.google.android.gms.maps.internal.zzas.zza(com.google.android.gms:play-services-maps@@18.2.0:5)
E/AndroidRuntime(31245): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime(31245): 	at android.os.Binder.transact(Binder.java:1219)
E/AndroidRuntime(31245): 	at m.bcn.c(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:8)
E/AndroidRuntime(31245): 	at com.google.maps.api.android.lib6.impl.cg.run(:com.google.android.gms.policy_maps_core_dynamite@242625207@242625203042.655323672.655323672:17)
E/AndroidRuntime(31245): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(31245): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31245): 	at android.os.Looper.loopOnce(Looper.java:230)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0 on channel stable at /Users/developer/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (6 available)
    • SM S928B (mobile)               • RFCX603ZL5H               • android-arm64  • Android 14 (API 34)
    • iDev (mobile)                   • 00008120-000C2CA41E80201E • ios            • iOS 17.6.1 21G93
    • iFone (mobile)                  • 00008130-000859911432001C • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.84

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-22 10:48
Hi @ShaunAtSense, I just tested the plugin heatmap example app and it worked as expected. Please provide a complete minimal reproducible code sample along with the version of `google_maps_flutter` you're using so that we can properly investigate this issue. 

Thank you

**Comment by ShaunAtSense** [comment] 2024-08-22 13:37
Hi @danagbemava-nc, it appears to be that if the "data" list is empty, then the App crashes. In iOS nothing gets displayed if the data is empty. Seemingly, I only load data once the map is created.

In my case:
`data: _heat,` is empty upon loading and then populated.

**Comment by danagbemava-nc** [comment] 2024-08-23 07:09
It appears that the android library requires the list to not be empty as seen here
https://github.com/googlemaps/android-maps-utils/blob/dd85f6f455909e3350b7c7e7b36f95ef4761b2c5/library/src/main/java/com/google/maps/android/heatmaps/HeatmapTileProvider.java#L209

@ShaunAtSense, according to the doc comment, the list should not be empty. So you should probably delay the creation of the heat map until you have the data to display. Unfortunately, it doesn't appear that the plugin can handle this for you.  See https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/Heatmap/data.html

I'll be closing this since it appears to be working as intended. 

Thank you

**Closed by danagbemava-nc** 2024-08-23 07:09 UTC
Labels: in triage
