### ISSUE TITLE
[webview_flutter_web] JS interop and package:web migration

### ISSUE THREAD

**Issue by shrijanRegmi** [flutter/flutter#148680] opened 2024-05-20 15:35 UTC
### Use case

The package [webview_flutter_web](https://pub.dev/packages/webview_flutter_web) package is holding us back in using WASM for our application.

### Proposal

I would like to request the migration of [webview_flutter_web](https://pub.dev/packages/webview_flutter_web) to JS interop and package:web as soon as possible, so that we can start using WASM.

**Comment by cedvdb** [comment] 2024-05-20 15:41
duplicate

**Comment by danagbemava-nc** [comment] 2024-05-21 07:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139749

**Closed by danagbemava-nc** 2024-05-21 07:59 UTC
Labels: in triage
