### ISSUE TITLE
ImagePicker loses EXIF when resizing via maxWidth or maxHeight

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#12921] opened 2017-11-08 08:38 UTC
Hi, i'm using the plugin: 
https://github.com/flutter/plugins/tree/master/packages/image_picker

for get images and photo. I'm using it also with maxWidth and maxHeight.

Is possible have the exif metadata before the resize?

How can i do it?

Thanks

**Comment by roughike** [comment] 2017-11-09 06:41
What info do you specifically need?

There's no currently an API for this, but I'm interested in implementing it.

**Comment by romaluca** [comment] 2017-11-09 08:35
I need:
Make, Model, FNumber, SpectralSensitivity, ExposureTime, FocalLength, GPSLatitude, GPSLongitude

I also wrote this flutter plugin: 

[https://github.com/romaluca/exif_flutter](https://github.com/romaluca/exif_flutter)

(it is a bad port of this: []( https://pub.dartlang.org/packages/exifdart) )

It works but only when i not specify maxHeight or maxWidth in image picker

**Comment by roughike** [comment] 2017-11-09 09:01
Ah, I see.

The EXIF data is lost since when you use `maxWidth` or `maxHeight`, a scaled version of the image is created and saved on the filesystem. This is so that we don't actually downscale the original picture in the users gallery, which might result in angry users. 

So, in the case of `maxWidth` or `maxHeight` being used, the EXIF data should be copied from the _original_ image to the _scaled_ one. This needs a new version of the _image\_picker_ plugin.

**Comment by ko2ic** [comment] 2018-11-01 08:32
I fixed it. #866

Please check if you are fixing what you are imagining.

**Comment by eseidelGoogle** [comment] 2018-11-26 17:16
I've written notes about how to add exif on iOS/Android to: https://github.com/flutter/flutter/issues/10533#issuecomment-441719073 . I suspect all of these exif bugs are the same root cause and easy to fix.

**Comment by btastic** [comment] 2018-12-13 13:55
I am experiencing the same issue after resizing the image on android, exif data is lost (can confirm it atleast for orientation). Any news on this?

**Comment by lifenautjoe** [comment] 2019-03-20 14:20
Still experiencing this issue with `image_picker: 0.5.0+3`

**Comment by cyanglaz** [comment] 2019-05-14 22:23
I'm fixing this in https://github.com/flutter/plugins/pull/1586
I will create a separate PR to copy GPS data after this PR is merged in

**Comment by cyanglaz** [comment] 2019-05-20 20:44
flutter/plugins#1586 is merged, you can use the latest version. Image picked now has the EXIF data copied from the original photo.

**Closed by cyanglaz** 2019-05-20 20:44 UTC
Labels: p: first party, p: image_picker, plugin
