### ISSUE TITLE
Dependency errors on Firebase Plugins after upgrading flutter 

### ISSUE THREAD

**Issue by ginuxone** [flutter/flutter#54289] opened 2020-04-08 18:08 UTC
Hello,
## Steps to Reproduce
1. Add this to your pubspec.yaml
#Firebase 
  firebase_auth: ^0.11.1+7
  firebase_core: ^0.4.0+6 
  firebase_analytics: ^3.0.3
  firebase_database: ^3.0.3
  cloud_firestore: ^0.12.5+2
  firebase_messaging: ^5.1.5
  firebase_storage: ^3.1.1

I'm using on android/build.gradle
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'
    }
and this on my android/app/build.gradle
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-messaging:20.1.3'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.android.support:multidex:1.0.3' 
}
Yesterday it was running fine and i havent added anything yet.

**Actual results:**

<details>
  <summary>Logs</summary>

flutter run --verbose
[  +32 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +77 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +115 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.9-0-gf139b11009
[   +7 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[  +94 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +150 ms] executing: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +31 ms] Exit code 0 from: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           950b8c27               device product:beryllium model:POCOPHONE_F1 device:beryllium transport_id:1
[  +20 ms] C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe -s 950b8c27 shell getprop
[ +147 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\
[  +28 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.1+4\
[  +40 ms] Found plugin emoji_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +12 ms] Found plugin firebase_analytics at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-3.0.3\
[  +71 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+7\
[  +52 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +49 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +45 ms] Found plugin firebase_database at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.3\
[   +4 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-5.1.6\
[  +88 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.1\
[  +53 ms] Found plugin flutter_plugin_android_lifecycle at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\
[  +41 ms] Found plugin geocoder at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geocoder-0.2.1\
[  +37 ms] Found plugin geolocator at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-5.3.0\
[   +4 ms] Found plugin google_api_availability at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.2\
[   +2 ms] Found plugin google_maps_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+13\
[   +1 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.1+3\
[   +7 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.3+1\
[  +38 ms] Found plugin location at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[   +1 ms] Found plugin location_permissions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location_permissions-2.0.4+1\
[  +11 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
[  +34 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[  +12 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[  +74 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +2 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[   +3 ms] Found plugin simple_auth_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\simple_auth_flutter-2.0.4\
[  +82 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[  +51 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\
[  +75 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[   +4 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[ +122 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\
[  +15 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.1+4\
[ +110 ms] Found plugin emoji_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +74 ms] Found plugin firebase_analytics at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-3.0.3\
[  +54 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+7\
[   +3 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +4 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +65 ms] Found plugin firebase_database at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.3\
[  +78 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-5.1.6\
[  +88 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.1\
[  +70 ms] Found plugin flutter_plugin_android_lifecycle at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\
[  +38 ms] Found plugin geocoder at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geocoder-0.2.1\
[   +1 ms] Found plugin geolocator at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-5.3.0\
[   +2 ms] Found plugin google_api_availability at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.2\
[   +2 ms] Found plugin google_maps_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+13\
[  +44 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.1+3\
[   +7 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.3+1\
[  +44 ms] Found plugin location at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[   +2 ms] Found plugin location_permissions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location_permissions-2.0.4+1\
[  +40 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
[  +31 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[   +7 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[   +2 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\     
[  +41 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[   +2 ms] Found plugin simple_auth_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\simple_auth_flutter-2.0.4\
[   +2 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[   +9 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\
[  +35 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[  +68 ms] Generating D:\Source\night_shift_official\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +35 ms] ro.hardware = qcom
[  +88 ms] Launching lib\main.dart on POCOPHONE F1 in debug mode...
[  +16 ms] executing: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe -s 950b8c27 shell -x logcat -v time -t 1
[ +207 ms] Exit code 0 from: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe -s 950b8c27 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           04-08 20:03:08.836 E/chromium( 3059): [ERROR:raster_decoder.cc(868)]   RasterDecoderImpl: Context reset detected after
           MakeCurrent.
[  +82 ms] executing: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +1 ms] executing: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe -s 950b8c27 logcat -v time -T 04-08 20:03:08.836      
[  +77 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +20 ms] executing: C:\Users\ginit\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +81 ms] Building APK
[  +35 ms] Running Gradle task 'assembleDebug'...
[   +8 ms] gradle.properties already sets `android.enableR8`
[  +31 ms] Using gradle from D:\Source\night_shift_official\android\gradlew.bat.
[  +33 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +126 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +4 ms] executing: [D:\Source\night_shift_official\android\] D:\Source\night_shift_official\android\gradlew.bat -Pverbose=true
-Ptarget=D:\Source\night_shift_official\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+1752 ms] > Configure project :app
[   +1 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[   +5 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[  +60 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[+18601 ms] Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.google.firebase,
artifactId=firebase-measurement-connector-impl, version=16.0.1), toArtifact=Artifact(groupId=com.google.firebase,
artifactId=firebase-analytics), toArtifactVersionString=[16.0.1])
[   +3 ms] FAILURE: Build failed with an exception.
[  +39 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[        ] > In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[16.0.       
[   +3 ms]   1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
[   +2 ms]   Dependency failing: com.google.firebase:firebase-measurement-connector-impl:16.0.1 -> com.google.firebase:firebase-analy
[   +1 ms]   tics@[16.0.1], but firebase-analytics version was 16.5.0.
[   +1 ms]   The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art       
[   +2 ms]   ifact with the issue.
[  +83 ms]   -- Project 'app' depends onto com.google.firebase:firebase-core@16.0.1
[  +39 ms]   -- Project 'app' depends onto com.google.firebase:firebase-measurement-connector-impl@16.0.1
[   +1 ms]   -- Project 'app' depends onto com.google.firebase:firebase-analytics@16.5.0
[   +1 ms]   -- Project 'app' depends on project 'firebase_analytics' which depends onto com.google.firebase:firebase-analytics@16.5.       
[   +1 ms]   0
[        ]   For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep       
[   +1 ms]   endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://       
[   +1 ms]   github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
[  +68 ms]   uild.gradle file.
[  +12 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan toget full insights.
[  +41 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 20s
[  +77 ms] Running Gradle task 'assembleDebug'... (completed in 21,0s)
[   +5 ms] "flutter run" took 24.193ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

flutter analyze
Analyzing night_shift_official...                                       

   info - The declaration '_userDescription' isn't referenced - lib\_Shared\userBasics.dart:85:8 - unused_element
   info - Unused import: 'l10n/messages_all.dart' - lib\localizations\localizations.dart:4:8 - unused_import
   info - This function has a return type of 'Future<AppLocalizations>', but doesn't end with a return statement -
          lib\localizations\localizations.dart:7:35 - missing_return
   info - The value of the local variable 'localeName' isn't used - lib\localizations\localizations.dart:9:18 - unused_local_variable       
   info - Unused import: 'package:night_shift_official/user/searching/searchPage.dart' - lib\root_page.dart:24:8 - unused_import
   info - Unused import: 'package:firebase_auth/firebase_auth.dart' - lib\user\otherUserProfile.dart:1:8 - unused_import
   info - The value of the field '_otherUid' isn't used - lib\user\otherUserProfile.dart:18:10 - unused_field
   info - The declaration '_userInfo' isn't referenced - lib\user\profile\profile.dart:151:10 - unused_element
   info - The declaration '_placesListView' isn't referenced - lib\user\profile\profile.dart:160:10 - unused_element
   info - The value of the local variable 'colore' isn't used - lib\user\profile\subscribersList.dart:14:15 - unused_local_variable

flutter doctor -v 
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Versione 10.0.18362.720], locale it-IT)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (9 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ginit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\ginit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • POCOPHONE F1 • 950b8c27 • android-arm64 • Android 10 (API 29)

• No issues found!
</details>

Hope you guys can help me out on this since i've already tried to change google play services and i think it might be related to [this](https://github.com/flutter/flutter/issues/54198) but i'm not quite sure.

**Comment by iapicca** [comment] 2020-04-09 06:29
Hi @ginuxone 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-09 06:29 UTC

**Comment by ginuxone** [comment] 2020-04-09 07:59
the problem is Flutter related.
Anyway i found the solution [in this thread](https://github.com/flutter/flutter/issues/50566#issuecomment-584697565)
Thanks anyway!
