### ISSUE TITLE
when scrolling do setState, the scrolling anmiation become not smoothly

### ISSUE THREAD

**Issue by zhancheng** [flutter/flutter#32543] opened 2019-05-11 06:27 UTC
as the title description

```dart
_scrollController.addListener(() {
      setState((){
          //do something here 
      })
});
```

**Comment by NMNguyen** [comment] 2019-12-02 08:19
@zhancheng 
Are you have a solution to this case?
Sometimes I want to set the opacity of AppBar when scrolling but it not smooth.

**Comment by zoeyfan** [comment] 2020-01-03 15:46
Unfortunately there isn't enough information on this bug to reproduce the issue. 
If you are still experiencing this issue, please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`.

**Comment by VladyslavBondarenko** [comment] 2020-02-14 14:01
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of flutter `doctor -v` please.

**Comment by zhancheng** [comment] 2020-06-12 03:38
@NMNguyen you can try this
```
flexibleSpace: LayoutBuilder(
   builder: (BuildContext context, BoxConstraints constraints){
   }
}
```

**Comment by VladyslavBondarenko** [comment] 2020-06-12 12:03
Complete reproducible code sample

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  ScrollController _scrollController;

  @override
  void initState() {
    _scrollController = ScrollController();
    _scrollController.addListener(() {
      setState((){
        //do something here
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: ListView.builder(
        itemCount: 300,
        controller: _scrollController,
        itemBuilder: (context, index) {
          return ListTile(title: Text("Index : $index"));
        },
      ),
      ),
    );
  }
}
```

**Comment by Baluds** [comment] 2020-09-20 16:46
Having the same issue , setstate interrupts the scrolling animation.

**Comment by FacePalmDev** [comment] 2021-01-18 19:48
I'm also having the same issue

**Comment by ariefwijaya** [comment] 2021-01-23 00:44
I also facing the same issue

**Comment by OmarMach** [comment] 2021-05-26 12:48
Anything about this yet?

**Comment by stjfk** [comment] 2022-01-02 18:12
i have same issue

**Comment by maheshmnj** [comment] 2022-12-28 03:31
Hi @zhancheng, I tried this code sample, But I am not able to reproduce the issue.

Without setState | With SetState 
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/209751603-6f03ae0c-8c23-498c-91ed-9a3b2339fc71.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/209751551-c0b24ddf-42dc-4e58-8a9a-5433bf119114.mov' width=180/> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


There is not enough reproducible code sample to investigate this issue further.  I am closing this issue for now. Anyone who is affected by this issue, Please feel free to file a new issue with more details or share a minimal and complete reproducible code sample to investigate this issue further.

**Closed by maheshmnj** 2022-12-28 03:31 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 1.21
