### ISSUE TITLE
Flutter compiler spend too much memory

### ISSUE THREAD

**Issue by Dorbmon** [flutter/flutter#57851] opened 2020-05-23 13:42 UTC
![image](https://user-images.githubusercontent.com/17807931/82732168-1b504500-9d3e-11ea-9829-9c21c57873f4.png)
Dart.exe spend too much memory.I think there must be a memory leak.
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
    • Flutter version 1.17.1 at E:\flutter
    • Framework revision f7a6a7906b (11 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dorbmon\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

**Comment by wdaglb** [comment] 2020-05-25 01:50
+1
cpu memory 100%

**Comment by Dorbmon** [comment] 2020-05-25 04:12
> +1
> cpu memory 100%

It doesn't happen on master channel.

**Comment by TahaTesser** [comment] 2020-05-25 11:14
duplicate of https://github.com/flutter/flutter/issues/56569

**Closed by TahaTesser** 2020-05-25 11:14 UTC
