### ISSUE TITLE
https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md"

### ISSUE THREAD

**Issue by gucheng808913** [flutter/flutter#45759] opened 2019-11-28 06:36 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by janmoppel** [comment] 2019-11-28 07:15
Hello @gucheng808913 !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-11-28 07:15 UTC
