### ISSUE TITLE
Image picker crashes app in some cases

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27920] opened 2019-02-14 07:21 UTC
I don't what the cause is but I have the following stack traces:

```
Google Pixel 2 XL (taimen), Android 9
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3785)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3817)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1809)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6680)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4361)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3774)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess (ImagePickerDelegate.java:481)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult (ImagePickerDelegate.java:401)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:375)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:210)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:143)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
  at android.app.Activity.dispatchActivityResult (Activity.java:7462)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4354)
```
```
Motorola Moto G(4) Plus (athene_f), Android 6.0
Report 1 of 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3121)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3152)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2495)
  at android.app.ActivityThread.access$900 (ActivityThread.java:154)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1354)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5443)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:728)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:618)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3720)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3107)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult (ImagePickerDelegate.java:457)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult (ImagePickerDelegate.java:396)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:375)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:210)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:143)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
  at android.app.Activity.dispatchActivityResult (Activity.java:6470)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3716)
```

```
LGE Nexus 5 (hammerhead), Android 6.0
Report 1 of 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3103)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3134)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2481)
  at android.app.ActivityThread.-wrap11 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3699)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3089)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess (ImagePickerDelegate.java:481)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onRequestPermissionsResult (ImagePickerDelegate.java:365)
  at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult (FlutterPluginRegistry.java:191)
  at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult (FlutterActivityDelegate.java:129)
  at io.flutter.app.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:137)
  at android.app.Activity.dispatchRequestPermissionsResult (Activity.java:6582)
  at android.app.Activity.dispatchActivityResult (Activity.java:6460)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3695)
```

```
LGE Nexus 5 (hammerhead), Android 6.0
Report 1 of 2

java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3103)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3134)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2481)
  at android.app.ActivityThread.-wrap11 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3699)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3089)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess (ImagePickerDelegate.java:481)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult (ImagePickerDelegate.java:401)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:375)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:210)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:143)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
  at android.app.Activity.dispatchActivityResult (Activity.java:6456)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3695)
```

**Comment by Hixie** [comment] 2019-02-14 07:22
(Note that these reports aren't all the same exception and aren't all the same stacks. There might be multiple unrelated problems here.)

**Comment by zoechi** [comment] 2019-02-14 07:26
These looks similar #26676, #23788, #21871, #21102, #18700, #17950

**Comment by tudor07** [comment] 2019-03-18 08:42
Our users report a lot of crashes when trying to take pictures. We noticed this a few times but can't reproduce consistently, seems to be pretty random. I don't have any logs unfortunately because it seems these crashes are not picked up by Crashlytics. There are definitely some issues with this image_picker plugin and it seems there are no other alternatives for taking pictures.

@Hixie @zoechi  Can you guys share any progress you've made on investigating these crashes ?

**Comment by tudor07** [comment] 2019-03-18 16:42
@Hixie @zoechi 

I managed to get some logs.
This is what I get in Xcode logs:

`2019-03-18 15:43:36.048422+0200 Runner[1682:789246] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <FlutterViewController: 0x151d0ea70>.'
*** First throw call stack:
(0x236901ea4 0x235ad1a50 0x263637a24 0x26363a0bc 0x26363a720 0x26363a014 0x26363a350 0x10069b530 0x10069b064 0x100a31e78 0x100a508b0 0x100a54a8c 0x100aab554 0x100a61260 0x100a64640 0x236892718 0x236892448 0x236891c7c 0x23688cb58 0x23688c0e0 0x238b05584 0x263becc00 0x100237338 0x23634abb4)
libc++abi.dylib: terminating with uncaught exception of type NSException`

App crahses in `ImagePickerPlugin.m` at line `111` in method `showCamera`:

`[_viewController presentViewController:_imagePickerController animated:YES completion:nil];`

**Comment by jacob-hutchings** [comment] 2019-03-21 14:35
We are seeing a decent number of these crashes. Here is one of the tracebacks:

> Caused by java.lang.IllegalStateException: Received image from picker that was not requested
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:457)
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:396)
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
>        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
>        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
>        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
>        at android.app.Activity.dispatchActivityResult(Activity.java:6276)
>        at android.app.ActivityThread.deliverResults(ActivityThread.java:3706)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3094)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3153)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514)
>        at android.app.ActivityThread.access$900(ActivityThread.java:175)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:135)
>        at android.app.ActivityThread.main(ActivityThread.java:5425)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:928)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:723)

**Comment by DK15** [comment] 2019-04-09 09:31
I am facing similar issue while trying to take a picture using _Android emulator(Nexus 6P, Marshmallow) and Android device Redmi 4 on MM._ When I capture an image and select tick mark button, as shown in below screenshot,  app crashes with below exception:

![Screen Shot 2019-04-09 at 2 11 21 PM](https://user-images.githubusercontent.com/16548367/55789341-c882e200-5ad7-11e9-989e-d0bc14827d94.png)


```
E/AndroidRuntime( 8402): FATAL EXCEPTION: main
E/AndroidRuntime( 8402): Process: com.quickcarl.qcflutterpro, PID: 8402
E/AndroidRuntime( 8402): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.quickcarl.qcflutterpro/com.quickcarl.qcflutterpro.MainActivity}: **java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data**
E/AndroidRuntime( 8402): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
E/AndroidRuntime( 8402): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
E/AndroidRuntime( 8402): 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
E/AndroidRuntime( 8402): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
E/AndroidRuntime( 8402): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8402): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 8402): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime( 8402): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8402): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime( 8402): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime( 8402): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime( 8402): 	at com.quickcarl.qcflutterpro.MainActivity.onActivityResult(MainActivity.kt)
E/AndroidRuntime( 8402): 	at android.app.Activity.dispatchActivityResult(Activity.java:6428)
E/AndroidRuntime( 8402): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
E/AndroidRuntime( 8402): 	... 9 more
```

Code :

```
void _checkCameraPermission() {
    PermissionHandler()
        .checkPermissionStatus(PermissionGroup.camera)
        .then((status) {
      if (status == PermissionStatus.granted) {
        getImage(ImageSource.camera);
      } else {
        _askCameraPermission();
      }
    });
  }

  void _askCameraPermission() {
    PermissionHandler()
        .requestPermissions([PermissionGroup.camera]).then(_onStatusRequested);
  }

  void _onStatusRequested(Map<PermissionGroup, PermissionStatus> value) {
    final status = value[PermissionGroup.camera];
    if (status == PermissionStatus.granted) {
      getImage(ImageSource.camera);
    }
  }
```
```
  Future uploadFile(imageFile) async {
//    String fileName = DateTime.now().millisecondsSinceEpoch.toString();
    String fileName = "images/" + new Uuid().v4() + ".jpg";
    StorageReference reference = FirebaseStorage.instance.ref().child(fileName);
    StorageUploadTask uploadTask = reference.putFile(imageFile);

    await uploadTask.onComplete.then((value) {
      reference.getDownloadURL().then((result) {
        // result is the file URL
        if (result != null) {
          setState(() {
            isLoading = false;
          });
          onSendMessage(result, 2);
        }
      });
    });
  }
```
Flutter doctor:
```

[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.3.8 at
      /Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API
      23) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 6.0 (API
      23) (emulator)

! Doctor found issues in 1 category.
```

**Comment by opensourcegps** [comment] 2019-04-13 10:51
Still happening with image_picker 0.5.3+1.

LGE LG Stylo 4 (cv7a), Android 8.1:
````
java.lang.RuntimeException: 
 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3654)
 
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3694)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2906)
 
  at android.app.ActivityThread.-wrap11 (Unknown Source)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1611)
 
  at android.os.Handler.dispatchMessage (Handler.java:106)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6651)
 
  at java.lang.reflect.Method.invoke (Method.java)
 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
Caused by: java.lang.RuntimeException: 
 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4345)
 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3626)
 
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3694)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2906)
 
  at android.app.ActivityThread.-wrap11 (Unknown Source)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1611)
 
  at android.os.Handler.dispatchMessage (Handler.java:106)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6651)
 
  at java.lang.reflect.Method.invoke (Method.java)
 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
Caused by: java.lang.NullPointerException: 
 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess (ImagePickerDelegate.java:2)
 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult (ImagePickerDelegate.java:17)
 
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:13)
 
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:18)
 
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:6)
 
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:2)
 
  at android.app.Activity.dispatchActivityResult (Activity.java:7295)
 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4341)
 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3626) 
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3694)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2906)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1611)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6651) 
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
````

More than 40 crashes like this in console of various devices/android versions.

**Comment by cyanglaz** [comment] 2019-04-28 03:53
The crashes mentioned in the issue should be fixed by 0.5.3+2 
https://github.com/flutter/plugins/pull/1509

The iOS crash mentioned by @tudor07 is unrelated to this thread. @tudor07 Could you check if your issue is fixed with the latest version of the image_picker. If it is still not fixed, could you fire another issue with details on how your crash can be reproduced with a `flutter doctor -v` 
I am closing this issue now and if activity related crashes are still found after updating to 0.5.3+2 or above, please reopen this issue or open another one.

**Closed by cyanglaz** 2019-04-28 03:53 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash

**Comment by qeehong** [comment] 2019-08-21 10:33
@cyanglaz 
The issue is still there for version 0.6.1+3.
Only happens when picking up from camera.

Like mentioned by @tudor07 , the crash is not picked up by crashlytics.
I have even reset default app for camera, and try other camera app. The result is still the same.

I know that there is `retrieveLostData` but I do not know how to make it up in my situation.
The image_picker is on different page, and when the crash happened it reset the app and brings it to the homepage. Any insight will be appreciated. Thank you.

**Comment by NewITCorp** [comment] 2019-08-22 08:48
I am here to report the same result as @qeehong 
The issue is still there for version 0.6.1+3.
Only happens when picking up from camera.

**Comment by CarrieUp** [comment] 2019-10-21 08:21
The issue is still is still there even I'm using 0.6.1+8.
my error is like this 
`W/System  (30883): A resource failed to call close.
E/AndroidRuntime(30883): FATAL EXCEPTION: DefaultDispatcher-worker-5
E/AndroidRuntime(30883): Process:XXXX, PID: 30883
E/AndroidRuntime(30883): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30883):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/AndroidRuntime(30883):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(30883):        at XXXXXX$onActivityResult$1$invokeSuspend$$inlined$let$lambda$1.invokeSuspend(MainActivity.kt:95)
E/AndroidRuntime(30883):        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(30883):        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
E/AndroidRuntime(30883):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(30883):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30883):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(30883):        at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(30883):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30883):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(30883):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (30883): Sending signal. PID: 30883 SIG: 9
Lost connection to device.
`

And my mainActivity is like this 

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)
    when (requestCode) {
      LOGIN_CODE ->
        if (resultCode == RESULT_OK) {
          if (LoginManager.getInstance().loginService.isLoggedIn) {
            try{
              GlobalScope.launch {
                async {
                  var ls = LoginManager.getInstance().loginService
                  var response = ls.authRequest<AuthResponse<TokenResult>>(AUTH_PROVIDER_NAME)
                  return@async response.getToken()
                }.await().let {
                  withContext(Dispatchers.Main) {
                    methodResult?.success(it)
                  }
                }
              }
            } catch(){

            }
          }
        } else {
          methodResult?.success("")
        }

      LOGOUT_CODE ->
        if (resultCode == RESULT_OK) {
          methodResult?.success(true)
        }

      REQUEST_CODE_TAKE_IMAGE_WITH_CAMERA -> {
        if (data != null && resultCode != RESULT_OK) {
          methodResult?.success("")
        }
      }

      REQUEST_CODE_CHOOSE_IMAGE_FROM_GALLERY -> {
        if (data != null && resultCode != RESULT_OK) {
          methodResult?.success("")
        }
      }

      else -> {
        methodResult?.success(false)
      }
    }
  }`
`

**Comment by CarrieUp** [comment] 2019-11-18 04:33
any update to this issue?

**Comment by AresVampire** [comment] 2020-04-29 14:04
I am still facing this problem when I try to capture an image with the camera and tap on ok, then it crashes the app.

```
static Future<File> pickImageFromCamera() {
    return ImagePicker.pickImage(source: ImageSource.camera);
  }
```

My phone is Galaxy S10e, android version 10. I found that it only crashes on the phone without external storage like SD card.

**Comment by Vercris** [comment] 2021-07-14 18:30
I also have the same problem and the package page is not so explicit.
