### ISSUE TITLE
need a way to pop specific dialog in flutter

### ISSUE THREAD

**Issue by RafidKhan** [flutter/flutter#128023] opened 2023-06-01 07:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Navigator.pop(context) usually pops latest route/dialog/snackbar or whatever is currently shoing up. In this case I request for a feature that allows to dismiss specific dialog.

### Proposal

Let's say I have two alert dialog with specific keys:

GlobalKey dialogOneKey = GlobalKey();
  GlobalKey dialogTwoKey = GlobalKey();

  AlertDialog? dialogOne;

  AlertDialog? dialogTwo;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    dialogOne = AlertDialog(
      key: dialogOneKey,
      title: const Text("Alert 1"),
    );

    dialogTwo = AlertDialog(
      key: dialogTwoKey,
      title: const Text("Alert 2"),
    );
  }

This is the view: 
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          showDialog(
              context: context,
              barrierDismissible: false,
              builder: (context) {
                return dialogOne!;
              });
          showDialog(
              context: context,
              barrierDismissible: false,
              builder: (context) {
                return dialogTwo!;
              });
          await Future.delayed(const Duration(seconds: 2));
          Navigator.pop(dialogOneKey.context); /// this is invalid code. I am just suggesting a way 
        },
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

on floating action button tap boths dialogs open. After a delay of 2 seconds I want to pop dialog one, which is behind the dialog two.

**Comment by danagbemava-nc** [comment] 2023-06-01 10:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/62960. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-06-01 10:54 UTC
Labels: in triage
