### ISSUE TITLE
IDE support for Windows and Linux native plugins.

### ISSUE THREAD

**Issue by Piero512** [flutter/flutter#79179] opened 2021-03-27 01:22 UTC
## Use case

I would like to request docs, guides, or anything official on how to get the best development experience while writing Linux and Windows plugins.

The situation (as of Flutter 2.1.0-12.1.pre, channel dev), is that an example project is necessary to be able to even build the plugin,
and the plugin's CMakeLists.txt by itself is not able to allow IDEs like CLion to properly detect and index the plugin code (and provide relevant autocomplete), as it is missing the apply_standard_settings function defined in the flutter app's CMakeLists.txt for each platform, and the engine headers. 

## Proposal

I would like that the desktop plugin template for Linux and Windows use a CMakeLists.txt that gives an IDE clear targets to compile and better documentation on the generated targets.

**Comment by stuartmorgan** [comment] 2021-03-27 09:38
> an example project is necessary to be able to even build the plugin

As explained in the Discord discussion, this is fundamental to how Flutter plugins are designed, on all platforms.

The issue for desktop is that this isn't currently documented the way it is for iOS and Android.

**Comment by Piero512** [comment] 2021-03-27 14:20
Can't they be designed differently? It seems to me that if the desktop build system allowed for plugins as shared objects (or DLLs) with a function to instanciate the C++/GObject plugin (as an opaque pointer) though the factory function (I think the plugins already expose a extern C function returning a plugin instance), and make flutter tool copy engine headers to the project would work.

**Comment by stuartmorgan** [comment] 2021-03-27 22:57
> Can't they be designed differently?

Theoretically, yes. If you have a specific proposal for how to accomplish that without making the common case less efficient and the `flutter` tool significantly more complex, you could file a new issue with specific details. The current design exists for a reason; it was not a bug or an accident.

But that's completely unrelated to the title and the rest of the description of this issue; needing to open in the context of an app project and having IDE support are orthogonal.

> It seems to me that if the desktop build system allowed for plugins as shared objects (or DLLs)

They already are.

> with a function to instanciate the C++/GObject plugin (as an opaque pointer) though the factory function (I think the plugins already expose a extern C function returning a plugin instance)

That's not quite what it does, but yes, that's not unlike what it already has.

> and make flutter tool copy engine headers to the project would work.

See my comments above.

But my point is that:

> I would like that the desktop plugin template for Linux and Windows use a CMakeLists.txt that gives an IDE clear targets to compile

already exists. You just have to open the project in the plugin template that's intended to be a CMake root, which is the example. The plugin library is a clear target within that project.

**Comment by stuartmorgan** [comment] 2021-03-27 22:58
> > Can't they be designed differently?
> 
> Theoretically, yes. If you have a specific proposal for how to accomplish that without making the common case less efficient and the `flutter` tool significantly more complex, you could file a new issue with specific details. The current design exists for a reason; it was not a bug or an accident.
> 
> But that's completely unrelated to the title and the rest of the description of this issue; needing to open in the context of an app project and having IDE support are orthogonal.
> 
> > It seems to me that if the desktop build system allowed for plugins as shared objects (or DLLs)
> 
> They already are.
> 
> > with a function to instanciate the C++/GObject plugin (as an opaque pointer) though the factory function (I think the plugins already expose a extern C function returning a plugin instance)
> 
> That's not quite what it does, but yes, that's not unlike what it already has.
> 
> > and make flutter tool copy engine headers to the project would work.
> 
> See my comments above.
> 
> But my point is that:
> 
> > I would like that the desktop plugin template for Linux and Windows use a CMakeLists.txt that gives an IDE clear targets to compile
> 
> already exists. You just have to open the project in the plugin template that's intended to be a CMake root, which is the example. The plugin library is a clear target within that project.

What's missing is the documentation that says that, as exists for mobile.

**Comment by sgehrman** [comment] 2021-08-29 22:24
Spent the whole weekend trying to get VSCode to work with C++ intellisense for my plugin.  Nothing works.  Could someone tell me how to develop linux plugins with intellisense?  I have a federated plugin currently.  It works, but I can't type code if it doesn't show me errors.

**Comment by stuartmorgan** [comment] 2023-03-06 01:58
This is documented now on https://docs.flutter.dev/development/packages-and-plugins/developing-packages#edit-plugin-package do closing as resolved.

**Closed by stuartmorgan** 2023-03-06 01:58 UTC
Labels: plugin, platform-windows, platform-linux, proposal, a: desktop, documentation, passed first triage, P4
