### ISSUE TITLE
Flutter causes Mac OS Crash 3

### ISSUE THREAD

**Issue by buyildir** [flutter/flutter#91294] opened 2021-10-05 11:42 UTC
Hi,

I'm using flutter now for the last 2years on my machine. A few weeks ago I had the same problem like i have it again - but i do not have any clue why and how to resolve it.

When I run the "flutter run" command, the XCode Build is working and for some seconds i can see the next task "compiling, signing and...." and then suddenly it causes my Mac OS reboot. It happens now every time which makes me impossible to work on flutter. It is same as a few weeks ago.

Specs from my machine: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) - System Version: macOS 11.6 (20G165) - Kernel Version: Darwin 20.6.0
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)

I've already created an issue for this problem here but after it was resolved magically the issue was closed.
This is the issue I have created: here
I read some posts that some applications may cause a "kernel panic" but I'm not sure which app this is. And why does this happen now? (like here )

Any idea? Any help from your side? @darshankawar any further points were I can look at?

I have added some text files from the crash report - I hope this helps. if you see some sensitive data please be so kind and delete it.

hi @stuartmorgan - please do not just close the issue. I just had a conversation with the apple support guys and they're telling me that this is not something simulator-related. in fact I've tried to open the Xcode project and build the app there. I did not face any issues there. any idea why? why is crashing when I'm running the "flutter run" command in vscode and not when I'm building the via Xcode with the respective simulated device?

Hopefully, we can fix this quickly.

Thank you
[crash_01.txt](https://github.com/flutter/flutter/files/7285485/crash_01.txt)
[crash_02.txt](https://github.com/flutter/flutter/files/7285486/crash_02.txt)
[crash_03.txt](https://github.com/flutter/flutter/files/7285487/crash_03.txt)
!

**Comment by maheshmnj** [comment] 2021-10-05 13:12
Hi @buyildir, Thanks for filing the issue. Please share the complete output of `flutter doctor -v`. 
 
 A couple of  questions 
 -  Does the reboot happens when building the application from a specific IDE /  All IDE's
 -  Doe the issue reproduce when running a native IOS app (not a flutter app)? 
 -  Does the Android app compile and run on an Emulator? 
 -  Does flutter build fine on other similar macs?
 - Do you have any Anti virus installed on your system? 
   if yes there is a related issue: https://github.com/flutter/flutter/issues/70596 
  Please provide the above info to investigate further.
  
  
  
  Thanks

**Comment by buyildir** [comment] 2021-10-05 13:33
hi @maheshmnj 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.60.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
xyz@MacBook-Pro timesheetapp % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.5.2 at /Users/xyz/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 2 categories.


Does the reboot happens when building the application from a specific IDE / All IDE's
- I'm using VSCode. Problem occurs when running the "flutter run" and "flutter build ios" command.
 
Doe the issue reproduce when running a native IOS app (not a flutter app)?
- I have not tested a native IOS app but i have opened the previously generated xcode project from my flutter app and I'm able to run the simulator from xcode. I'll test another native ios app later.

Does the Android app compile and run on an Emulator?
- did not test it. this case is not necessary for me.

Does flutter build fine on other similar macs?
- not tested yet. but the build has worked previously on older MacOS and also on other Mac. Need to test it on other machine with latest code.

Do you have any Anti virus installed on your system?
- yes i have McAfee installed. did not find any solution/idea to my issue in #70596

thank you

**Comment by stuartmorgan** [comment] 2021-10-05 13:36
Closing as a duplicate of https://github.com/flutter/flutter/issues/91251. Please don't deliberately file duplicate issues because you disagree with the outcome; I can reply to your comment there.

**Closed by stuartmorgan** 2021-10-05 13:36 UTC
Labels: in triage

**Comment by buyildir** [comment] 2021-10-05 13:48
hi @stuartmorgan @maheshmnj  so what am i supposed to do now? both issues are closed now. if closed issues are still read, reviewed and answered then ok - sorry for creating a duplicate.

**Comment by maheshmnj** [comment] 2021-10-05 13:53
@buyildir  as mentioned please follow up on the original issue. Also additionally please check if disabling the anti-virus makes any difference.

Thanks
