### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by yusufvarli** [flutter/flutter#82378] opened 2021-05-12 19:15 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#9      PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale tr-TR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\prome\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\prome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Mi 9T (mobile) • a542cced • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)     • edge     • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: cc9b78fc5c4a4d2d51316d9626523336230a89a9
### Plugins
cloud_firestore-2.1.0
cloud_firestore_web-2.0.1
firebase_auth-1.1.4
firebase_auth_web-1.1.2
firebase_core-1.1.1
firebase_core_web-1.0.3
firebase_storage-8.0.6
firebase_storage_web-1.0.6
flutter_plugin_android_lifecycle-2.0.1
fluttertoast-8.0.6
google_maps_flutter-2.0.3
image_picker-0.7.5
image_picker_for_web-2.0.0
path_provider_linux-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0

**Comment by darshankawar** [comment] 2021-05-13 07:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/60880

**Closed by darshankawar** 2021-05-13 07:41 UTC
Labels: in triage
