### ISSUE TITLE
when can use Homebrew to install Flutter?

### ISSUE THREAD

**Issue by goalidea** [flutter/flutter#25662] opened 2018-12-21 14:12 UTC
when can use Homebrew to install Flutter?

**Comment by zoechi** [comment] 2018-12-21 15:16
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Duplicate of #14050

**Closed by zoechi** 2018-12-21 15:16 UTC

**Comment by dvska** [comment] 2019-08-22 18:47
https://github.com/MiderWong/homebrew-flutter
https://github.com/flschweiger/homebrew-flutter
