### ISSUE TITLE
iOS release  Flutter.framework is too large.   375.8M

### ISSUE THREAD

**Issue by taoyali** [flutter/flutter#53896] opened 2020-04-03 04:04 UTC
iOS release  Flutter.framework is too large.   375.8M in flutter SDK path: flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework

flutter version: 
   macOS 10.15.3
   Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
   Framework • revision 0b8abb4724 (7 weeks ago) • 2020-02-11 11:44:36 -0800
   Engine • revision e1e6ced81d
   Tools • Dart 2.7.0## Steps to Reproduce

file is too large is Flutter SDK:
   release  375.8:
          path:  flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework
  debug  95M:
           path: flutter/bin/cache/artifacts/engine/ios/Flutter.framework
  profile 66.8M
           flutter/bin/cache/artifacts/engine/ios-profile/Flutter.framework

quesion： 
          1.My understanding is that the release version should take less space than the debug part 
itself
          2. Why is it so big.  i can not understand.

thanks

**Comment by TahaTesser** [comment] 2020-04-03 07:47
Please check this [answer](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077) for your answer

Duplicate of [#47101](https://github.com/flutter/flutter/issues/47101)

**Closed by TahaTesser** 2020-04-03 07:47 UTC
