### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by iam-Arvind** [flutter/flutter#25116] opened 2018-12-08 15:24 UTC
When I run in android studio it showing following error :
```
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\Arvind\AndroidStudioProjects\my_flutter_app\android\gradlew.bat -v
```

**Comment by zoechi** [comment] 2018-12-09 14:34
Please add the output of `flutter doctor -v`.

Is this with a new project or an existing project after a Flutter upgrade?

**Comment by iam-Arvind** [comment] 2018-12-10 13:16
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.16299.785], locale en-IN)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (10 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Arvind\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.4892.1

[√] VS Code (version 1.26.1)
    • VS Code at C:\Users\Arvind\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
![screenshot 10](https://user-images.githubusercontent.com/44140257/49734963-e700da00-fcab-11e8-99ee-d49334c39a7c.png)

**Comment by zoechi** [comment] 2018-12-10 13:36
Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
and then run again?

**Comment by zoechi** [comment] 2018-12-10 13:36
Duplicate of #13645

**Closed by zoechi** 2018-12-10 13:36 UTC

**Comment by guoxiaojun001** [comment] 2019-01-12 08:09
i have the same question,
ProcessException: ProcessException: Process "F:\github\flutterProject\zhihu-flutter\android\gradlew.bat" exited abnormally:
Unzipping C:\Users\HP\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip to C:\Users\HP\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: F:\github\flutterProject\zhihu-flutter\android\gradlew.bat -v

**Comment by zoechi** [comment] 2019-01-12 12:45
@guoxiaojun001  might be a corrupted download file. Try deleting the file mentioned in the error message and try again.

**Comment by Azandowski** [comment] 2019-06-11 08:53
> Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> and then run again?

Hi, can you help me? I can not find this .gradle\wrapper.... in my users\myname\ I want fix it or unzip or replace but I do not know where is it???? can you send screen please?

**Comment by hassanMetwally** [comment] 2019-07-02 23:11
completely solution with android studio, but not intlijIdea

**Comment by CodePhilanthropist** [comment] 2019-08-30 10:17
@zoechi 

> Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> and then run again?

It doesn't work on my end. I deleted the .zip file
When I tried to run the app, it says:

Initializing Gradle...

and loads infinitely

**Comment by CodePhilanthropist** [comment] 2019-08-30 11:08
@zoechi 

> Can you please try deleting this directory ![image](https://ser-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> and then run again?

I tried deleting it and run the sample app. I stuck on "Initializing Gradle..." when I open the wrapper\dists\ directory another   C:\Users\$Username\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2.zip  is created. Is internet connection a problem? Because I'm having a spotty connection.

**Comment by ujjwaltwitx** [comment] 2019-11-05 13:55
go to your wrapper file and delete the directory called as gradle.4.50.all(something like this) and run the program again

**Comment by Erwinn7** [comment] 2019-12-18 04:17
> Pouvez-vous essayer de supprimer ce répertoire , puis relancer?![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)

it's work for me . thank you

**Comment by Mwamitovi** [comment] 2019-12-18 16:29
> go to your wrapper file and delete the directory called as gradle.4.50.all(something like this) and run the program again

This worked out quite well. Thanks, @ujjwaltwitx

**Comment by irenejohn997** [comment] 2020-01-28 21:10
Please i need help,i have done all this steps,but mine is still not working,this time is not showing me any error but starts launching,running Gradle task debug and then stops,showing nothing

**Comment by irenejohn997** [comment] 2020-01-30 11:17
![Screenshot (18)](https://user-images.githubusercontent.com/41710028/73445210-75299b00-435a-11ea-91c6-e02df9e28e42.png)
![Screenshot (19)](https://user-images.githubusercontent.com/41710028/73445213-765ac800-435a-11ea-97b6-2846e07a16a5.png)
Please what do i do

**Comment by r0ly4udi** [comment] 2020-02-21 13:19
please help me a new bie flutter....
when done install, i running but this error : 
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by udeshyaG** [comment] 2020-04-19 10:21
> Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> and then run again?

Thank you... It worked for me

**Comment by PayalKshirsagar** [comment] 2020-04-29 13:35
@zoechi Could you please tell me what to do for solving the same problem in Linux based system?
System: Ubuntu 18.04.4 LTS

Visual studio code:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-45-generic

Problem:
![error-f](https://user-images.githubusercontent.com/44032541/80601029-df7dd480-8a4a-11ea-8dfd-d22768cd5839.png)

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.9 at
      /home/payal/flutter_linux_v1.12.13+hotfix.9-stable/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/payal/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/payal/Android
      /android-studio-ide-192.6392135-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at /home/payal/Android
      /android-studio-ide-192.6392135-linux/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Aqua Ace • J580A1ZR5A200038 • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 2 categories.

I want to setup flutter without  using Android studio.

**Comment by IT-zakriabilal** [comment] 2020-05-16 00:31
> Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> and then run again?

thank you very much, its work for me :)

**Comment by shakthi-cheeniabs** [comment] 2020-06-06 08:30
This is because the file is corrupted so delete the existing gradle file
.grade/wrapper/dist will be a hidden file and there will be several such folders in project,android folder and your home

Find the folder and delete the corrupted file and run it

**Comment by osunkoyadavid** [comment] 2020-06-06 21:04
> i have the same question,
> ProcessException: ProcessException: Process "F:\github\flutterProject\zhihu-flutter\android\gradlew.bat" exited abnormally:
> Unzipping C:\Users\HP.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip to C:\Users\HP.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew
> 
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:219)
> at java.util.zip.ZipFile.(ZipFile.java:149)
> at java.util.zip.ZipFile.(ZipFile.java:163)
> at org.gradle.wrapper.Install.unzip(Install.java:214)
> at org.gradle.wrapper.Install.access$600(Install.java:27)
> at org.gradle.wrapper.Install$1.call(Install.java:74)
> at org.gradle.wrapper.Install$1.call(Install.java:48)
> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> at org.gradle.wrapper.Install.createDist(Install.java:48)
> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Command: F:\github\flutterProject\zhihu-flutter\android\gradlew.bat -v

Try re downloading the gradle 4.1 file, i re downloaded it and it works fine with me.
Hope it helps

**Comment by osunkoyadavid** [comment] 2020-06-06 21:04
> > i have the same question,
> > ProcessException: ProcessException: Process "F:\github\flutterProject\zhihu-flutter\android\gradlew.bat" exited abnormally:
> > Unzipping C:\Users\HP.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip to C:\Users\HP.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew
> > Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> > at java.util.zip.ZipFile.open(Native Method)
> > at java.util.zip.ZipFile.(ZipFile.java:219)
> > at java.util.zip.ZipFile.(ZipFile.java:149)
> > at java.util.zip.ZipFile.(ZipFile.java:163)
> > at org.gradle.wrapper.Install.unzip(Install.java:214)
> > at org.gradle.wrapper.Install.access$600(Install.java:27)
> > at org.gradle.wrapper.Install$1.call(Install.java:74)
> > at org.gradle.wrapper.Install$1.call(Install.java:48)
> > at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> > at org.gradle.wrapper.Install.createDist(Install.java:48)
> > at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> > at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> > Command: F:\github\flutterProject\zhihu-flutter\android\gradlew.bat -v
> 
> Try re downloading the gradle 4.1 file, i re downloaded it and it works fine with me.
> Hope it helps

Also rename the corrupt zip file

**Comment by elgeho** [comment] 2020-07-08 12:18
please help me
![image](https://user-images.githubusercontent.com/60629432/86917549-83f45500-c125-11ea-8c61-dd7b9aeb7c32.png)
![image](https://user-images.githubusercontent.com/60629432/86917720-dafa2a00-c125-11ea-8e14-e0509269021d.png)

**Comment by osunkoyadavid** [comment] 2020-07-22 13:29
i can help you
delete the gradle-4.1-all.zip  file or any gradle zip file and download the same one again, hope that helps you

**Comment by Sandeep-peddi** [comment] 2020-08-29 08:53
There must be error while downloading Graddle File. Check the following code in the gradle/wrapper/gradle-wrapper.properties

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-6.6.1-all.zip

In my case there is a additional '' after 'https' and the number was older version, But correcting it worked for me. U can refer the below website to know the latest available version of file type "all.zip" and Update the number or whole link properly and as it is around 130 mb. you need to have an active internet connection and wait for a while by pressing Run once. There is no need to worry until u see any red lines.

https://services.gradle.org/distributions/

![Gradle_Download_Error](https://user-images.githubusercontent.com/70323980/91633089-2680d400-ea03-11ea-93b4-74a788ee531c.jpg)

**Comment by osunkoyadavid** [comment] 2020-08-29 08:58
Sir or Ma, I don't have that problem anymore but i have an error opening my
emulator
Nexus 5X API 30 process was killed
Can you help me fix it

**Comment by themhrao** [comment] 2020-08-29 12:32
Can Someone help me



[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by osunkoyadavid** [comment] 2020-08-30 14:46
connect to the internet and run the same command. It looks like you are not
connected. Also show me the results of flutter doctor -v

**Comment by bmnidhin** [comment] 2020-09-17 10:50
> 
> 
> @zoechi
> 
> > Can you please try deleting this directory ![image](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)
> > and then run again?
> 
> It doesn't work on my end. I deleted the .zip file
> When I tried to run the app, it says:
> 
> Initializing Gradle...
> 
> and loads infinitely

Helped. Thank you

**Comment by ghulamghousdev** [comment] 2020-11-14 15:30
@zoechi 

Can you please try deleting this directory
![](https://user-images.githubusercontent.com/405837/49735924-e7d44480-fc88-11e8-821f-1194cf9d81bb.png)


It worked for me.

**Comment by Belal-Adam-Hassan** [comment] 2020-12-10 01:05
help
![new errors in flutter android studio](https://user-images.githubusercontent.com/74950915/101707779-eec30700-3a9c-11eb-8599-0d22b97e5905.PNG)

**Comment by Belal-Adam-Hassan** [comment] 2020-12-10 01:10
Guys, I have another problem. I already installed Flutter, Dart in the Android Studio Plugin, but this problem appears to me saying you need to install them What is happening.

![flutter doctor errors from vs code terminal android studio](https://user-images.githubusercontent.com/74950915/101708052-917b8580-3a9d-11eb-9867-459013b5f1b3.PNG)

![flutter and dart plugin installed in android studio](https://user-images.githubusercontent.com/74950915/101708107-a5bf8280-3a9d-11eb-837f-4f71ed4f1d10.PNG)

**Comment by ghulamghousdev** [comment] 2020-12-11 16:42
@Belal-Adam-Hassan  this is a problem with the latest versions. They are installed but you will receive the output that it is not installed. Don't worry it's just a bug :)

**Comment by osunkoyadavid** [comment] 2020-12-18 13:59
i'm using a macbook now so thanks 🙏 but no worries 😉

**Comment by manoj251** [comment] 2021-02-19 22:53
i am using macOs catalina 10.15.6 version n i am facing this awkward error please somebody help me nothing is worked for me i have to make project in flutter for my college .......please somebody help me 
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:225)
at java.util.zip.ZipFile.(ZipFile.java:155)
at java.util.zip.ZipFile.(ZipFile.java:169)
at org.gradle.wrapper.Install.unzip(Install.java:214)
at org.gradle.wrapper.Install.access$600(Install.java:27)
at org.gradle.wrapper.Install$1.call(Install.java:74)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by osunkoyadavid** [comment] 2021-06-13 21:12
Try changing your gradle zip file to the latest version.
Try again, that's the best advice I could give you for now.
