### ISSUE TITLE
[web] make root path configurable

### ISSUE THREAD

**Issue by anantaramdas** [flutter/flutter#68686] opened 2020-10-21 06:43 UTC
## Steps to Reproduce

1. Create flutter web project as per https://codelabs.developers.google.com/codelabs/web-url-launcher/#11
2. deploy on web site with relative path i.e. https://example.com/some/app/context/
3. follow above url - page loaded incorrectly

**Expected results:** 
Website should work or at least I as developer should be able to specify some parameter for application which helps it to determinate that app is actually in /some/app/context from the roow

**Actual results:** 

Page showed incorrectly

**Comment by TahaTesser** [comment] 2020-10-21 10:23
Hi @anantaramdas 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by anantaramdas** [comment] 2020-10-21 15:25
@TahaTesser find it below:

````
flutter doctor -v
Downloading android-arm-profile/windows-x64 tools...                1.3s
Downloading android-arm-release/windows-x64 tools...                0.6s
Downloading android-arm64-profile/windows-x64 tools...              0.7s
Downloading android-arm64-release/windows-x64 tools...              0.6s
Downloading android-x64-profile/windows-x64 tools...                0.7s
Downloading android-x64-release/windows-x64 tools...                0.6s
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-18.1.pre at D:\Tools\flutter-beta
    • Framework revision 198df796aa (6 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\anant\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.48

! Doctor found issues in 1 category.
````

**Comment by TahaTesser** [comment] 2020-10-22 08:59
Hi @anantaramdas 
Can you deploy a simple HTML to the same relative path and test it?  Does it load? If yes, can you please open the Flutter app from the same path and look for console errors and provide it here

**Comment by azbuky** [comment] 2020-10-22 11:26
@anantaramdas 
Have you set the base path in your index.html file?

```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    Fore more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/some/app/context/">
...
```

**Comment by anantaramdas** [comment] 2020-10-22 18:38
@TahaTesser what do you mean simple HTML? How can I get it generated?

**Comment by anantaramdas** [comment] 2020-10-22 18:38
@azbuky thanks will try tomorrow morning

**Comment by pedromassangocode** [comment] 2020-11-13 12:00
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by anantaramdas** [comment] 2020-11-13 12:05
@azbuky unfortunately that context root is not available before deployment. I'm talking regarding uploading files to IPFS for example. I get hash code generated

**Comment by anantaramdas** [comment] 2020-11-13 12:06
@pedromassangocode kindly reopen this issue as it is still relevant. Sorry was little busy last days

**Comment by anantaramdas** [comment] 2020-11-13 12:08
@azbuky what I'm looking for is to set somewhere in Flutter configs that it should accept relative context (i.e. '.') and not root domain (i.e. '/'). AFAIK React does support this.

**Comment by azbuky** [comment] 2020-11-16 10:03
> @azbuky unfortunately that context root is not available before deployment. I'm talking regarding uploading files to IPFS for example. I get hash code generated

@anantaramdas in that case I would try removing `<base href="/some/app/context/">` from `index.html`. Flutter should be able to handle a relative context but you will probably not be able to use a [custom URL strategy](https://github.com/flutter/flutter/issues/33245#issuecomment-705095853) so you are stuck with `#` in your URL.

Also the service worker will most likely not work properly (#68449) so I would disable it (or fix the generated implementation).

**Comment by mdebbar** [comment] 2020-11-19 22:55
@azbuky thanks for the input! You are right.

@anantaramdas let us know if @azbuky's suggestions worked for you.

**Comment by anantaramdas** [comment] 2020-11-20 00:19
Will check this weekend and update you, thanks!

**Comment by derolf** [comment] 2021-01-20 11:37
I removed `<base href="/">` from `index.html` and that seems to work.

**Comment by pedromassangocode** [comment] 2021-02-10 10:18
Updating this to make it a proposal for Flutter to allow configurable path as mentioned in https://github.com/flutter/flutter/issues/68686#issuecomment-727874066 and suggested by https://github.com/flutter/flutter/issues/75771.

**Comment by skoehler** [comment] 2021-02-10 10:21
Please be aware that there are currently two different problems:

- The generated index.html contains `<base href="/">`
- The generated `flutter_service_worker.js` contains the following paths, one of which is absolute:
  ```
  const CORE = [
    "/",
  "main.dart.js",
  "index.html",
  "assets/NOTICES",
  "assets/AssetManifest.json",
  "assets/FontManifest.json"];
  ```

I am not sure what to do about the `"/"`. Maybe `""` or even `"."` is suitable to make it relative as well.

**Comment by mdebbar** [comment] 2021-02-11 17:59
@pedromassango would you mind clarifying what exactly is the proposal? The root path is already configurable through `index.html`. If you have a `<base href="/my/root/path">` it should work as expected. If there are problems with that, please file github issues with details.

The only issue, that I'm aware of, is the service worker one tracked [here](https://github.com/flutter/flutter/issues/68449).

**Comment by skoehler** [comment] 2021-02-11 18:16
> @pedromassango would you mind clarifying what exactly is the proposal? The root path is already configurable through `index.html`. If you have a `<base href="/my/root/path">` it should work as expected. If there are problems with that, please file github issues with details.
> 
> The only issue, that I'm aware of, is the service worker one tracked [here](https://github.com/flutter/flutter/issues/68449).

"Configurable through `index.html`" is not really a true statement. `index.html` is not a configuration file. It's part of the generated output. The path in `index.html` should be derived from some configuration file.
Yes, the problem can be mended by applying some manual correction to index.html after the flutter build process has finished. The proposal is to have the path be part of the build process. For example, then the index.html can also be put into the proper subfolder when debugging locally.

**Comment by derolf** [comment] 2021-02-11 21:33
It should work regardless where index.html ends up.

**Comment by mdebbar** [comment] 2021-02-11 21:47
The `index.html` file is not auto-generated during the build process. It's generated when you create the project as part of the project boilerplate. It comes with "/" as the default root path.

After project creation, it's up to you to do whatever you want with it. Flutter doesn't control or modify the `index.html` file.

**Comment by skoehler** [comment] 2021-02-11 21:57
> The `index.html` file is not auto-generated during the build process. It's generated when you create the project as part of the project boilerplate. It comes with "/" as the default root path.

I apologize. I missed that file. I changed the path in `web/index.html`. Even when running locally in debug mode, the configured path is added. So indeed this seem to be working as intended.

**Comment by pedromassangocode** [comment] 2021-02-12 12:17
> @pedromassango would you mind clarifying what exactly is the proposal? The root path is already configurable through `index.html`. If you have a `<base href="/my/root/path">` it should work as expected. If there are problems with that, please file github issues with details.
> 
> The only issue, that I'm aware of, is the service worker one tracked [here](https://github.com/flutter/flutter/issues/68449).

Sorry, I didn't realize that the changes should be made in `index.html`. So this issue seems to be solved.

@anantaramdas can you please confirm that?
Thank you

**Comment by slavap** [comment] 2021-03-02 05:11
@mdebbar 
Is there any other way to configure it without using index.html ? Let's say I don't know how my compiled web app will be deployed. Of course I may ask a person who is deploying the app to web server to always change index.html, but prefer not to do that. For example the better way is to set somehow this "base href" from the code in main() based on html.window.location.href
Also how it will work if <base href="/"> is commented out in index.html ? Should service worker be changed somehow in that case as well?

**Comment by pedromassangocode** [comment] 2021-03-24 12:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:52 UTC
Labels: a: quality, a: release, assigned for triage, f: routes, passed first triage, platform-web, proposal, severe: new feature, waiting for customer response
