### ISSUE TITLE
Can the Flutter team make the keyboard stick to the bottom?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#124002] opened 2023-04-03 10:12 UTC
Can the Flutter team make the keyboard stick to the bottom? 

I hope the Flutter team can do this, because my keyboard disappears and pops up again.

When I finish typing and click the button, my keyboard disappears and pops up again.

I wish the Flutter team made the keyboard always stay at the bottom.

**Comment by danagbemava-nc** [comment] 2023-04-05 06:39
Hi @mycar98765. please provide a complete minimal reproducible code sample so that we can investigate this issue. The code sample you provided is not complete. 

Thank you

**Comment by mycar98765** [comment] 2023-04-05 09:55
@danagbemava-nc  what kind of code do you want? By the way, it is the chat message bar. What I want to do is like WhatsApp chat screen. When the send message button is clicked, the keyboard doesn't disappear and pop up again.

**Comment by danagbemava-nc** [comment] 2023-04-06 06:44
A runnable code sample that shows the issue you're facing. The code sample that you provided above is not runnable. It doesn't have to be your project code, just a small sample that reproduces the bug will do.

Thank you

**Comment by mycar98765** [comment] 2023-04-06 08:51
@danagbemava-nc ok, here's the code you should be able to run:

```
Scaffold(
   appBar: AppBar(
    …
  ),
  body: Column(
    mainAxisSize: MainAxisSize.min,
     children: [
      Expanded(
        child: Stack(
          children: [
            …
             Align(
               alignment: Alignment.bottomCenter,
               child: Row(
               children: [
                 Expanded(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        …
                        Row(
                          children: [
                            Expanded(
                              child: TextField(
                                …
                              ),
                            ),
                            isLoading
                                ? const CircularProgressIndicator()
                                : Container(
                                    decoration: BoxDecoration(
                                      color: …,
                                      shape: BoxShape.circle,
                                    ),
                                    child: IconButton(
                                      onPressed: …,
                                      icon: …,
                                  ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      …
    ],
  ),
),
```

**Comment by danagbemava-nc** [comment] 2023-04-06 13:26
I used some part of your code sample and when I tap the send button, the keyboard doesn't go anywhere. See the recording below. 

Without a complete code sample that reproduces the bug we won't be able to do anymore here. 

https://user-images.githubusercontent.com/88313112/230391834-c6bdd102-1c63-4776-b0ea-31828801235c.MP4

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({
    super.key,
  });

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Expanded(
            child: Stack(
              children: [
                Align(
                  alignment: Alignment.bottomCenter,
                  child: Row(
                    children: [
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Row(
                              children: [
                                const Expanded(
                                  child: TextField(),
                                ),
                                isLoading
                                    ? const CircularProgressIndicator()
                                    : IconButton(
                                        onPressed: () {
                                          setState(() {
                                            isLoading = true;
                                          });

                                          Future.delayed(const Duration(seconds: 3),
                                              () {
                                            setState(() {
                                              isLoading = false;
                                            });
                                          });
                                        },
                                        icon: const Icon(Icons.send),
                                      ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                )
              ],
            ),
          )
        ],
      ),
    );
  }
}
```
</details>

**Comment by mycar98765** [comment] 2023-04-07 07:41
Is this because I added this in my `StatefulWidget`?:
```
@override
void initState() {
  super.initState();
  focusNode.requestFocus();
}
```

**Comment by danagbemava-nc** [comment] 2023-04-10 06:58
That is unlikely to be issue since that line of code should only run when the widget is first initialized. 

In its current state, this issue is not actionable for us since no valid repro has been provided. As such I'm going to close this issue.

Please file a new issue when you're able to come up with a reduced test case that we can use to reproduce the issue so that we can investigate it. 

Thank you

**Closed by danagbemava-nc** 2023-04-10 06:58 UTC
Labels: in triage
