### ISSUE TITLE
[web] Not allowed to load local resource

### ISSUE THREAD

**Issue by lukergthorpe** [flutter/flutter#56000] opened 2020-04-30 01:57 UTC
Describe your issue and include the command you're running, flutter_web version, browser version
I have a flutter project,
I have run the commands as follows.

flutter channel beta
flutter upgrade
flutter config --enable-web
flutter create .
flutter run -d chrome

Chrome proceeds to open but the page is just blank.

If I start a new Flutter project and do the exact same it all works fine.

Any suggestions would be greatly appreciated.

![image](https://user-images.githubusercontent.com/54824514/80664289-bd7f6300-8ad9-11ea-907d-8eb95564b186.png)

**Comment by jonahwilliams** [comment] 2020-04-30 03:16
Please include the output of `flutter doctor -v`

You might also need to check the chrome console for errors

**Comment by lukergthorpe** [comment] 2020-04-30 03:27
Ok, yep there's a dozen chrome errors.

![image](https://user-images.githubusercontent.com/54824514/80668720-f1608580-8ae5-11ea-8a01-c864e1b4eba9.png)

Output from flutter doctor -v

[√] Flutter (Channel beta, v1.17.0-3.3.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-AU)
    • Flutter version 1.17.0-3.3.pre at C:\src\flutter
    • Framework revision 0da1ab0922 (33 hours ago), 2020-04-28 11:02:34 -0700
    • Engine revision 376ad6a64b
    • Dart version 2.8.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\luket\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\luket\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome              • chrome        • web-javascript • Google Chrome 81.0.4044.129
    • Web Server          • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment] 2020-04-30 03:30
can you try and put together a minimal example that reproduces this? Are you importing code from absolute paths or something like that?

**Comment by lukergthorpe** [comment] 2020-04-30 03:33
I'm very new to all this. I guess I can start adding a few chunks of code to the base flutter app and see when it breaks.

**Comment by jonahwilliams** [comment] 2020-04-30 04:13
if this reproduces by running your project, you could also share it or a subset of it on Github or another open source hosting site. I could try and run it to reproduce the problem.

**Comment by VladyslavBondarenko** [comment] 2020-04-30 08:18
Duplicate of https://github.com/flutter/flutter/issues/55779

**Comment by MarchMore** [comment] 2020-05-03 18:56
I also had this issue. It was caused by an absolute path after "import" in one of my dart files. It was like `import 'file:///C:/pathToAnotherDartFile.dart`. I didn't intentionally write this import like this. It appears to have been changed automatically. So maybe this is also the reason in your case.

After I changed it to a relative path, I didn't had this issue (after `flutter clean)` anymore.

**Comment by TahaTesser** [comment] 2020-05-22 13:51
Hi @lukergthorpe 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-05-22 13:51 UTC
Labels: in triage, waiting for customer response

**Comment by yugantkadu** [comment] 2020-07-27 08:32
> I also had this issue. It was caused by an absolute path after "import" in one of my dart files. It was like `import 'file:///C:/pathToAnotherDartFile.dart`. I didn't intentionally write this import like this. It appears to have been changed automatically. So maybe this is also the reason in your case.
> 
> After I changed it to a relative path, I didn't had this issue (after `flutter clean)` anymore.

I was facing the same error. The reason behind it is probably flutter changed my **import path** from 
`import 'package:bmicalculatorapp/components/reusable_card.dart'; ` to **relative path** 
`import 'file:///C:/Users/AndroidStudioProjects/bmi_calculator_app/lib/components/reusable_card.dart';` 
while shifting my files from root to another directory.

Then I removed the relative path and added **package path** and the code runs perfectly.
