### ISSUE TITLE
  firebase_auth: 0.8.4 codeAutoRetrievalTimeout callback still called after FireBaseAuth.signOut()

### ISSUE THREAD

**Issue by silversquall** [flutter/flutter#31360] opened 2019-04-20 15:30 UTC
Hello,

flutter doctor:
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
...
I am facing a potential issue with firebase_auth: 0.8.4.
FireBaseAuth.instance.verifyPhoneNumber(codeAutoRetrievalTimeout : mycalBack()....) 
The callback is called after FireBaseAuth.signOut()

I would expect it not to be triggered after signing out.
Is this a bug ?

thx.

**Comment by BondarenkoStas** [comment] 2019-10-17 13:35
@silversquall is it the same with firebase_auth 0.14.0+5?

**Comment by iapicca** [comment] 2019-11-08 09:42
Hi @silversquall 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:42 UTC
Labels: p: firebase, p: firebase_auth, waiting for customer response
