### ISSUE TITLE
[image_picker] Image picker returns `null` when selecting image from other apps when using `singleInstance`

### ISSUE THREAD

**Issue by DomantasZav** [flutter/flutter#76856] opened 2021-02-26 11:40 UTC
## Steps to Reproduce

This code snippet returns null only when selecting image from Google Photos:
```
await ImagePicker().getImage(
      source: ImageSource.gallery,
      imageQuality: 70,
      maxWidth: 2048,
      maxHeight: 2048,
    );
```

And I get this message in log cat:
```
E/UpdateManager.Error( 5083): com.google.android.play.core.install.InstallException: Install Error(-3): The API is not available on this device. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_API_NOT_AVAILABLE)
```

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.22.6 at C:\Users\Domantas\AppData\Local\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Domantas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • motorola one vision (mobile) • ZY3265BDQZ • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment] 2021-02-26 13:34
Hi @DomantasZav 
Can you please try a different device?  Make sure you're using the latest stable `image_picker: **^0.6.7+22**
I can't reproduce it on a Oneplus or Realme device

<details> 
<summary>code runnable sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          final file = await ImagePicker().getImage(
            source: ImageSource.gallery,
            imageQuality: 70,
            maxWidth: 2048,
            maxHeight: 2048,
          );

          print(file.path);
        },
      ),
    );
  }
}

``` 

</details>

Printing path of the picked file 
```bash
D/ActivityThread(19231): pid:19231 tid:19231 doframe Callback
I/flutter (19231): /storage/emulated/0/Android/data/com.example.stable_flutter/files/Pictures/scaled_image_picker7560935096891424193.jpg
```


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.22.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • IN2011 (mobile)                    • c9d8ee0c      • android-arm64 • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by DomantasZav** [comment] 2021-03-01 10:08
Found the issue:
It only happens on android devices and if `launchMode` in `AndroidManifest` is set to `singleInstance`
The error I provided was caused by something else.
So there is no indication of error. It just returns null.

**Comment by TahaTesser** [comment] 2021-03-02 07:34
Hi @DomantasZav 
Thanks for the details, I can reproduce it with `singleIntance`

<details>
<summary>logs</summary>

```bash
Launching lib/main.dart on IN2011 in debug mode...
 package:triage/main.dart
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
W/DisplayEventDispatcher(12154): dispatcher 0x764c0b6fb0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(12154): dispatcher 0x75fc09fed0 ~ ignoring unknown event type 0x6d746f6e
Connecting to VM Service at ws://127.0.0.1:51314/6OwUI-aX26c=/ws
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=false inTouchMode=true
W/DisplayEventDispatcher(12154): dispatcher 0x764c0b6fb0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(12154): dispatcher 0x75fc09fed0 ~ ignoring unknown event type 0x6d746f6e
D/ActivityThread(12154): pid:12154 tid:12154 doframe Callback
D/OpScreenModeManager(12154): setRefreshRate parent io.flutter.embedding.android.FlutterView{1f9461f VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(12154): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{595c5be V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager(12154): setRefreshRate parent io.flutter.embedding.android.FlutterView{1f9461f VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(12154): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{595c5be V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/DecorView(12154): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@480458[MainActivity]
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=true inTouchMode=true
D/OpScreenModeManager(12154): setRefreshRate parent io.flutter.embedding.android.FlutterView{1f9461f VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(12154): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{595c5be V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
W/DisplayEventDispatcher(12154): dispatcher 0x75fc09fed0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(12154): dispatcher 0x764c0b6fb0 ~ ignoring unknown event type 0x6d746f6e
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=false inTouchMode=true
W/DisplayEventDispatcher(12154): dispatcher 0x764c0b6fb0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(12154): dispatcher 0x75fc09fed0 ~ ignoring unknown event type 0x6d746f6e
D/DecorView(12154): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@480458[MainActivity]
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=true inTouchMode=true
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=false inTouchMode=true
D/ActivityThread(12154): pid:12154 tid:12154 doframe Callback
E/flutter (12154): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'path' was called on null.
E/flutter (12154): Receiver: null
E/flutter (12154): Tried calling: path
[38;5;244mE/flutter (12154): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248mE/flutter (12154): #1      Home.build.<anonymous closure>[39;49m
 package:triage/main.dart
E/flutter (12154): <asynchronous suspension>
[38;5;248mE/flutter (12154): #2      Home.build.<anonymous closure> (package:triage/main.dart)[39;49m
 package:triage/main.dart
[38;5;244mE/flutter (12154): #3      _InkResponseState._handleTap[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter (12154): #4      _InkResponseState.build.<anonymous closure>[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter (12154): #5      GestureRecognizer.invokeCallback[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244mE/flutter (12154): #6      TapGestureRecognizer.handleTapUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter (12154): #7      BaseTapGestureRecognizer._checkUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter (12154): #8      BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter (12154): #9      PrimaryPointerGestureRecognizer.handleEvent[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244mE/flutter (12154): #10     PointerRouter._dispatch[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter (12154): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure>[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter (12154): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)[39;49m
[38;5;244mE/flutter (12154): #13     PointerRouter._dispatchEventToRoutes[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter (12154): #14     PointerRouter.route[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter (12154): #15     GestureBinding.handleEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter (12154): #16     GestureBinding.dispatchEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter (12154): #17     RendererBinding.dispatchEvent[39;49m
 package:flutter/…/rendering/binding.dart
[38;5;244mE/flutter (12154): #18     GestureBinding._handlePointerEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter (12154): #19     GestureBinding._flushPointerEventQueue[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter (12154): #20     GestureBinding._handlePointerDataPacket[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter (12154): #21     _rootRunUnary (dart:async/zone.dart:1206:13)[39;49m
[38;5;244mE/flutter (12154): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter (12154): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)[39;49m
[38;5;244mE/flutter (12154): #24     _invoke1 (dart:ui/hooks.dart:265:10)[39;49m
[38;5;244mE/flutter (12154): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)[39;49m
E/flutter (12154):
D/OpScreenModeManager(12154): setRefreshRate parent io.flutter.embedding.android.FlutterView{1f9461f VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(12154): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{595c5be V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager(12154): setRefreshRate parent io.flutter.embedding.android.FlutterView{1f9461f VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(12154): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{595c5be V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/DecorView(12154): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@480458[MainActivity]
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=true inTouchMode=true
W/DisplayEventDispatcher(12154): dispatcher 0x75fc09fed0 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(12154): dispatcher 0x764c0b6fb0 ~ ignoring unknown event type 0x6d746f6e
D/ViewRootImpl[MainActivity](12154): windowFocusChanged hasFocus=false inTouchMode=true

```

</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • IN2011 (mobile) • c9d8ee0c • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

</details>

**Comment by ArturAntin** [comment] 2021-03-19 12:08
I had the same issue. Changed launchMode to `singleTask`, now everything works as it should.

**Comment by Babwenbiber** [comment] 2021-03-30 09:42
When I put the launchMode to singleTask and chose the Photo category, then the debugger disconnects from the app and when I pick the image the app crashes.
Might be related to #71261

**Comment by flutterone** [comment] 2021-06-17 18:03
Same issue image_picker: ^0.8.0+3

**Comment by eerbee** [comment] 2021-08-29 21:11
Same issue here, im using image_picker: ^0.8.3+3 on my android simulator Pixel 3a API 23 with launchMode :  ``singleTop.`
but im try on my another android simulator which is Pixel 4 API 26, is working properly

**Comment by mho79** [comment] 2021-11-15 09:02
Same issue image_picker ^0.8.4+4

Any updates on this?

**Comment by Babwenbiber** [comment] 2021-11-15 09:45
> Same issue image_picker ^0.8.4+4
> 
> Any updates on this? Can will this be fixed? Or is using `singleTask` the only option for now?

No solution for now. In general vote up the issue to get more attention of the flutter team. The issues will get solved depending on time needed to fix the issue and the number of upvotes of an issue.

**Comment by idish** [comment] 2022-07-30 15:36
+1 for fixing this issue, I spent quite bit of time to understand that there is even a problem, as this bug only occurs when choosing external providers in the picker. The core issue is definitely hard to guess (the launch mode of main activity).

**Comment by OlehMarchenko95** [comment] 2022-08-03 14:25
I had the same issue. Changed launchMode to singleTask, as a temporary workaround.

Hope this will be fixed, it's quite frustrating issue.

**Comment by BWhiteApps** [comment] 2022-12-01 20:44
Having the same issue here, took me all day to figure this out. I'm not sure if this will ever be fixed due to the nature of how the ImagePicker works.

**Comment by sed1ka** [comment] 2022-12-15 03:37
The same issue here with ImagePicker 0.8.6

**Comment by danagbemava-nc** [comment] 2023-01-06 12:59
Reproduces on the latest versions of flutter with `image_picker: ^0.8.6`


<details>
<summary>complete sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

  File? _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            const Text('Hello World'),
            if(_image != null)
              Text(_image?.path ?? 'No image selected'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () async {
          final file = await ImagePicker().pickImage(
            source: ImageSource.gallery,
            imageQuality: 70,
            maxWidth: 2048,
            maxHeight: 2048,
          );

          setState(() {
            _image = File(file!.path);
          });

          print(file?.path);
        },
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • adb-5dd3be00-22GXB2._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                      • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)           • chrome                                     • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.7.0-14.0.pre.52, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0-14.0.pre.52 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 507062032f (13 hours ago), 2023-01-06 01:13:18 +0100
    • Engine revision 5bd90d6e77
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • adb-5dd3be00-22GXB2._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                      • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                                     • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by RicharC293** [comment] 2023-01-10 19:49
Same issue

**Comment by larssn** [comment] 2023-02-06 15:15
It also returns null with the default `launchMode` of `singleTop`.
However it seems periodic. Sometimes it returns null, sometimes not. Some images always return null, some never return null (size does **not** seem related to this). Seems to be worse in debug mode than in release mode (if it happens at all in release mode).

This plugin has had it's share of problems 🙄

cc @TahaTesser Can I lure you in here? 🙂 Might be easy to reproduce using a few images on Google drive.

**Comment by TahaTesser** [comment] 2023-02-06 15:29
@larssn 
Thanks for the details. Updated the title.

**Comment by stuartmorgan** [comment] 2023-04-13 15:32
> This leads me to believe that this issue is a bug in the Android Image Picker.

Based on further investigation, it looks like this is expected behavior rather than a bug, as described [here](https://stackoverflow.com/a/49993984). If the calling app forbids other activities it its task, then it can't get results from other activities.

We can document this in the plugin's README to help avoid people being surprised by it.

**Comment by larssn** [comment] 2023-04-13 17:41
@stuartmorgan That doesn't explain why it periodically works, or periodically doesn't.

**Comment by stuartmorgan** [comment] 2023-04-13 17:53
@larssn Your issue is different than this one; it has both different conditions and different behavior. It should be filed as a new issue; renaming this one to cover a different case was incorrect.

**Closed** 2023-04-21 17:44 UTC
Labels: platform-android, plugin, p: image_picker, documentation, has reproducible steps, P4, found in release: 3.3, found in release: 3.7
