### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, path = 'E:\simplifii_app\.dart_tool\flutter_build\6d67f216ac021eaf7fbece1c81ff1038' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by imaditya123** [flutter/flutter#58362] opened 2020-05-31 11:03 UTC
## Command
```
flutter --quiet assemble --depfile E:\simplifii_app\build\app\intermediates\flutter\debug/flutter_build.d --output E:\simplifii_app\build\app\intermediates\flutter\debug -dTargetFile=E:\simplifii_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Exists failed, path = 'E:\simplifii_app\.dart_tool\flutter_build\6d67f216ac021eaf7fbece1c81ff1038' (OS Error: Access is denied.
, errno = 5)
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:11)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:474:26)
#4      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _runZoned (dart:async/zone.dart:1619:10)
#12     runZoned (dart:async/zone.dart:1539:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Aditya Rathore\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\Aditya Rathore\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • POCO F1 • e4fa9cff • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
flutter_plugin_android_lifecycle-1.0.7
image_picker-0.6.6+1
shared_preferences-0.5.7+1
shared_preferences_macos-0.0.1+8
shared_preferences_web-0.1.2+5
upi_pay-0.2.1
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+4
webview_flutter-0.3.21

**Comment by jonahwilliams** [comment] 2020-05-31 20:17
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-05-31 20:17 UTC
