### ISSUE TITLE
flutter web can't run and flutter android can't hot reload

### ISSUE THREAD

**Issue by NTN9115** [flutter/flutter#50426] opened 2020-02-09 04:42 UTC
## Steps to Reproduce

when I try run 
```
 flutter run -d web-server --web-port=10000 -v
```
## Logs

```
[  +28 ms] executing: [/home/ning/.sdk/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/home/ning/.sdk/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +9 ms] executing: [/home/ning/.sdk/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/ning/.sdk/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/home/ning/.sdk/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +30 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /home/ning/.sdk/a-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           564c6b3d0305           device usb:1-2 product:daisy model:Mi_A2_Lite device:daisy_sprout transport_id:1
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +164 ms] Found plugin path_provider at /home/ning/.sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-1.6.0/
[ +102 ms] Found plugin path_provider at /home/ning/.sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-1.6.0/
[  +62 ms] Generating /home/ning/dev/flutter/qmanager/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +88 ms] Launching lib/main.dart on Web Server in debug mode...
[        ] Building application for the web...
[ +146 ms] Found plugin path_provider at /home/ning/.sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-1.6.0/
[+7784 ms] Starting daemon...
[ +206 ms] Initializing inputs
[ +266 ms] Building new asset graph...
[+1444 ms] Building new asset graph completed, took 1.4s

[+60074 ms] Checking for unexpected pre-existing outputs....
[        ] Checking for unexpected pre-existing outputs. completed, took 1ms

[        ] Initializing inputs
[        ] Building new asset graph...
[        ] Building new asset graph completed, took 1.4s
[        ] Checking for unexpected pre-existing outputs....
[        ] Checking for unexpected pre-existing outputs. completed, took 1ms
[+5065 ms] Building application for the web... (completed in 75.0s)
[   +1 ms] "flutter run" took 75,512ms.
Failed to connect to build daemon.
The daemon either failed to start or was killed by another process.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:727:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:548:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:638:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

 
and when I run

```
flutter run -v
```
## Logs

```
[  +36 ms] executing: [/home/ning/.sdk/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/home/ning/.sdk/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +9 ms] executing: [/home/ning/.sdk/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/ning/.sdk/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +52 ms] executing: [/home/ning/.sdk/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /home/ning/.sdk/a-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           564c6b3d0305           device usb:1-2 product:daisy model:Mi_A2_Lite device:daisy_sprout transport_id:1
[  +36 ms] /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell getprop
[ +108 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +156 ms] Found plugin sqflite at /home/ning/.sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.2.0/
[ +109 ms] Found plugin sqflite at /home/ning/.sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.2.0/
[  +60 ms] Generating /home/ning/dev/flutter/ykd/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = qcom
[  +41 ms] Launching lib/main.dart on Mi A2 Lite in debug mode...
[   +8 ms] executing: /home/ning/.sdk/a-sdk/build-tools/29.0.3/aapt dump xmltree /home/ning/dev/flutter/ykd/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/ning/.sdk/a-sdk/build-tools/29.0.3/aapt dump xmltree /home/ning/dev/flutter/ykd/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.ykd" (Raw: "com.example.ykd")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="ykd" (Raw: "ykd")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.ykd.MainActivity" (Raw: "com.example.ykd.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=29)
                     E: action (line=30)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=32)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=39)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell -x logcat -v time -t 1
[ +167 ms] Exit code 0 from: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-09 12:35:04.001 D/NetworkController.MobileSignalController(1)( 1913): updateTelephony: hasService=true ss=SignalStrength: 99 0 -120 -160 -120 -160 -1 25 -91 -9 166
           2147483647 0 2147483647 99 255 2147483647 gsm|lte use_rsrp_and_rssnr_for_lte_level  [-120, -115, -110, -100] [-113, -103, -97, -89]
[  +13 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb version
[   +1 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 logcat -v time -T 02-09 12:35:04.001
[  +21 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/ning/.sdk/a-sdk/platform-tools/adb
[   +2 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb start-server
[   +5 ms] Building APK
[  +19 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /home/ning/dev/flutter/ykd/android/gradlew.
[   +1 ms] /home/ning/dev/flutter/ykd/android/gradlew mode: 33261 rwxr-xr-x.
[   +3 ms] executing: /opt/android-studio/jre/bin/java -version
[  +81 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +1 ms] executing: [/home/ning/dev/flutter/ykd/android/] /home/ning/dev/flutter/ykd/android/gradlew -Pverbose=true -Ptarget=/home/ning/dev/flutter/ykd/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+4866 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :sqflite:preBuild UP-TO-DATE
[        ] > Task :sqflite:preDebugBuild UP-TO-DATE
[        ] > Task :sqflite:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :sqflite:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[        ] > Task :sqflite:compileDebugShaders UP-TO-DATE
[        ] > Task :sqflite:generateDebugAssets UP-TO-DATE
[        ] > Task :sqflite:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[        ] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :sqflite:generateDebugResValues UP-TO-DATE
[        ] > Task :sqflite:compileDebugRenderscript NO-SOURCE
[        ] > Task :sqflite:generateDebugResources UP-TO-DATE
[        ] > Task :sqflite:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :sqflite:checkDebugManifest UP-TO-DATE
[        ] > Task :sqflite:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :sqflite:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :sqflite:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :sqflite:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :sqflite:javaPreCompileDebug UP-TO-DATE
[        ] > Task :sqflite:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :sqflite:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :sqflite:processDebugJavaRes NO-SOURCE
[        ] > Task :sqflite:bundleLibResDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :sqflite:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :sqflite:createFullJarDebug UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :sqflite:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :sqflite:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :sqflite:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :sqflite:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:assembleDebug UP-TO-DATE
[        ] > Task :sqflite:extractDebugAnnotations UP-TO-DATE
[        ] > Task :sqflite:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :sqflite:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :sqflite:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :sqflite:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :sqflite:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[        ] > Task :sqflite:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[        ] > Task :sqflite:bundleDebugAar UP-TO-DATE
[        ] > Task :sqflite:compileDebugSources UP-TO-DATE
[        ] > Task :sqflite:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 4s
[        ] 58 actionable tasks: 3 executed, 55 up-to-date
[   +9 ms] Running Gradle task 'assembleDebug'... (completed in 5.0s)
[  +35 ms] calculateSha: LocalDirectory: '/home/ning/dev/flutter/ykd/build/app/outputs/apk'/app.apk
[  +63 ms] calculateSha: reading file took 62us
[ +476 ms] calculateSha: computing sha took 475us
[   +4 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +2 ms] executing: /home/ning/.sdk/a-sdk/build-tools/29.0.3/aapt dump xmltree /home/ning/dev/flutter/ykd/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +6 ms] Exit code 0 from: /home/ning/.sdk/a-sdk/build-tools/29.0.3/aapt dump xmltree /home/ning/dev/flutter/ykd/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.ykd" (Raw: "com.example.ykd")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="ykd" (Raw: "ykd")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.ykd.MainActivity" (Raw: "com.example.ykd.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=29)
                     E: action (line=30)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=32)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=39)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[        ] Stopping app 'app.apk' on Mi A2 Lite.
[        ] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell am force-stop com.example.ykd
[ +265 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell pm list packages com.example.ykd
[  +76 ms] package:com.example.ykd
[   +2 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell cat /data/local/tmp/sky.com.example.ykd.sha1
[  +43 ms] 4c39d61d72897935af8dd7269880df790d327a8d
[        ] Latest build already installed.
[        ] Mi A2 Lite startApp
[   +2 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.ykd/com.example.ykd.MainActivity
[ +118 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.ykd/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1270 ms] Observatory URL on device: http://127.0.0.1:45175/D7u-R5G1T0o=/
[   +1 ms] executing: /home/ning/.sdk/a-sdk/platform-tools/adb -s 564c6b3d0305 forward tcp:0 tcp:45175
[   +6 ms] 36495
[        ] Forwarded host port 36495 to device port 45175 for Observatory
[  +11 ms] Connecting to service protocol: http://127.0.0.1:36495/D7u-R5G1T0o=/
[ +691 ms] Successfully connected to service protocol: http://127.0.0.1:36495/D7u-R5G1T0o=/
[   +2 ms] Sending to VM service: getVM({})
[  +10 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Qualcomm Technologies, Inc MSM8953, operatingSystem: android, targetCPU: arm64, version:
2.8.0-dev.5.0.flutter-fc3af737c7 (Fri Jan 24 09:53:26 2020 +0000) on "android_arm64", _profilerMode: VM, _...
[   +4 ms] Sending to VM service: getIsolate({isolateId: isolates/3119334385958767})
[   +3 ms] Sending to VM service: _flutter.listViews({})
[  +33 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7ca7fe5520, isolate: {type: @Isolate, fixedId: true, id: isolates/3119334385958767, name:
main.dart$main-3119334385958767, number: 3119334385958767}}]}
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: ykd})
[  +15 ms] Result: {type: Isolate, id: isolates/3119334385958767, name: main, number: 3119334385958767, _originNumber: 3119334385958767, startTime: 1581222911829, _heaps: {new:
{type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[ +181 ms] Result: {type: FileSystem, name: ykd, uri: file:///data/user/0/com.example.ykd/code_cache/ykdKWIWOU/ykd/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.ykd/code_cache/ykdKWIWOU/ykd/)
[   +2 ms] Updating assets
[  +87 ms] Syncing files to device Mi A2 Lite...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +9 ms] /home/ning/.sdk/flutter/bin/cache/dart-sdk/bin/dart /home/ning/.sdk/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/ning/.sdk/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tool.EYRCHL/app.dill --packages /home/ning/dev/flutter/ykd/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
[   +7 ms] <- compile package:ykd/main.dart
```

stuck at compile package:ykd/main.dart

## flutter doctor 

```
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.6 at /home/ning/.sdk/flutter
    • Framework revision fabeb2a16f (12 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ning/.sdk/a-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/ning/.sdk/a-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] Connected device (3 available)
    • Mi A2 Lite • 564c6b3d0305 • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome       • web-javascript • Chromium 80.0.3987.87 Arch Linux
    • Web Server • web-server   • web-javascript • Flutter Tools

• No issues found!
```

## linux version

```
Linux ningn2 5.5.2-1-ck-zen #1 SMP PREEMPT Wed, 05 Feb 2020 00:24:45 +0000 x86_64 GNU/Linux
```

I tried use lts linux kernel(4.9) , works fine.

**Comment by TahaTesser** [comment] 2020-02-10 11:11
Hi @NTN9115 
Please checkout this possible [#50352 Comment](https://github.com/flutter/flutter/issues/50352#issuecomment-583649468)
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-02-10 11:15
@NTN9115 
Closing the current one as duplicate of https://github.com/flutter/flutter/issues/50352
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-02-10 11:15 UTC
Labels: waiting for customer response
