### ISSUE TITLE
Theme won't copy and change the brightness from light to dark

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#9871] opened 2017-05-07 00:39 UTC
I'm expecting to copy and change the theme from light to dark on another page. Is this allowed to change the brightness in this location? 

## Steps to Reproduce

1. Use this code.
```
import 'package:flutter/material.dart';

final ThemeData _themeData = new ThemeData(
  brightness: Brightness.light,
  primarySwatch: Colors.deepOrange,
  accentColor: Colors.deepPurpleAccent,
  buttonColor: Colors.purple,
);

void main() {
  runApp(new MyApp());
}

/// Material App Root
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: _themeData,
      title: 'Flutter Demo',
      home: new MyHomePage(title: 'Home Page'),
      routes: <String, WidgetBuilder>{
        AnotherPage.routeName: (BuildContext context) =>
        new AnotherPage(title: "Another Page"),
      },
    );
  }
}

/// place: "/"
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Container(
        child: new Row(
          children: <Widget>[
            new RaisedButton(
              child: new Text("Home Button"),
              onPressed: _onPress,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _onPress,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),);
  }

  void _onPress() {
    Navigator.of(context).pushNamed(AnotherPage.routeName);
  }
}

/// place: "/AnotherPage"
class AnotherPage extends StatefulWidget {
  AnotherPage({Key key, this.title}) : super(key: key);
  static const String routeName = "/AnotherPage";
  final String title;

  @override
  _AnotherPageState createState() => new _AnotherPageState();
}

class _AnotherPageState extends State<AnotherPage> {
  @override
  Widget build(BuildContext context) {
    var widgetsWithAnotherTheme = new Theme(
        data: _themeData.copyWith(
          buttonColor: Colors.amber,
        ),
        child: new RaisedButton(
          child: new Text("Go"),
          onPressed: () {},
        )
    );

    return new Theme(
      data: _themeData.copyWith(
        brightness: Brightness.dark,
        buttonColor: Colors.cyan,
      ),
      child: new Scaffold(
        appBar: new AppBar(
          title: new Text(widget.title),
        ),
        body: new Container(
          child: new Row(
            children: <Widget>[
              new RaisedButton(
                child: new Text("Another Button"),
                onPressed: () {},
              ),
              widgetsWithAnotherTheme,
            ],
          ),
        ),
        floatingActionButton: new FloatingActionButton(
          onPressed: () {},
          tooltip: 'Add',
          child: new Icon(Icons.add),
        ),
      ),
    );
  }
}
```
2. Check the class `_AnotherPageState`, and notice the _themeData.copyWith(brightness: brightness: Brightness.dark, ) change. 

3. This will not change the brightness.

Result on another page, I'm expecting it to be dark becaue I added Brightness.dark.
<img width="325" alt="screen shot 2017-05-06 at 5 29 53 pm" src="https://cloud.githubusercontent.com/assets/1326504/25776947/1c188134-3282-11e7-970a-ff495c516593.png">

## Logs

```
Brandons-MacBook-Pro:MyTheme2 branflake2267$ flutter analyze
Analyzing /Users/branflake2267/Documents/workspace-idea/MyTheme2...
No issues found!
Ran in 4.0s
Brandons-MacBook-Pro:MyTheme2 branflake2267$ 
```

## Flutter Doctor

```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision d1e895224e (20 hours ago), 2017-05-05 21:44:46 -0700
    • Engine revision 1b01211ee6
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • iPhone SE • 1C15BC7F-DA25-4E71-B479-B601B549CAA0 • ios • iOS 10.3 (simulator)


```

**Comment by Hixie** [comment] 2017-05-07 02:33
Yeah, this is something we should definitely fix. Dupe of https://github.com/flutter/flutter/issues/9148.

**Closed by Hixie** 2017-05-07 02:33 UTC

**Comment by jinfagang** [comment] 2018-06-01 07:08
Still got this problem:
```
    themeData = globalThemeData.copyWith(brightness: Brightness.dark);

```
won't change theme to dark like this

**Comment by zoechi** [comment] 2018-06-14 07:43
@jinfagang that seems unrelated. Can you please create a new issue with full information about how to reproduce?

**Comment by nailgilaziev** [comment] 2018-08-01 18:31
it's something magic or I don't understand something. 

if I do _copyWith_ like this It still not work
```
var app = AppStateContainer.of(context);
    var themeData = ThemeData(
      accentColor: Colors.lightGreen,
      errorColor: Colors.deepOrange,
      buttonColor: Colors.lightGreen,
    );
    Widget screen;
    if (app.state.user != null)
      screen = MainScreen();
    else {
      screen = LoginScreen();
      themeData = themeData.copyWith(brightness: Brightness.dark);
    }

    return new MaterialApp(
      theme: themeData,
      home: screen,
    );
```

but if I set brightness directly in constructor - all is fine

**Comment by zoechi** [comment] 2018-08-22 16:31
@LRNZ09 #9148 is where this is tracked.

**Comment by PiN73** [comment] 2019-07-31 10:30
Is it still relevant?

According to [docs](https://flutter.dev/docs/cookbook/design/themes#extending-the-parent-theme) we can extend parent theme using `Theme.of(context).copyWith(...)`

However it doesn't work for brightness:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text('[default]'),
                onPressed: () {},
              ),
              Theme(
                data: ThemeData(
                  brightness: Brightness.dark,
                ),
                child: RaisedButton(
                  child: Text('ThemeData'),
                  onPressed: () {},
                ),
              ),
              Theme(
                data: Theme.of(context).copyWith(
                  brightness: Brightness.dark,
                ),
                child: RaisedButton(
                  child: Text('Theme.of(context).copyWith'),
                  onPressed: () {},
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

shows
![](https://user-images.githubusercontent.com/18294052/62204974-06618a00-b397-11e9-81d9-1929d9ffe6b3.png)
i.e. changing brightness using `copyWith` doesn't affect child brightness.

Checked on stable channel
```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (12 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

and master
```
Flutter 1.8.2-pre.242 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9bb7142ef7 (13 hours ago) • 2019-07-30 14:45:00 -0700
Engine • revision c41bbc63d9
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 1e43d65d4a)
```
