### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by Awesome-T** [flutter/flutter#73055] opened 2020-12-28 20:39 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:418:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:483:5)
<asynchronous suspension>
#3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale ru-RU)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at c:\Users\shent\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\shent\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\shent\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • SM N960F (mobile) • 2aaa49c4473f7ece • android-arm64  • Android 10 (API 29)
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
### Plugins
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-1.0.0
flutter_keyboard_visibility-4.0.2
flutter_keyboard_visibility_web-1.0.1
flutter_native_timezone-1.0.4
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+17
image_picker_for_web-0.1.0+2
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
permission_handler-5.0.1+1
phone_number-0.6.3
qrscan-0.2.21
sensors-0.4.2+6
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
sqflite-1.3.2+1
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment] 2020-12-29 07:09
Closing this as duplicate of https://github.com/flutter/flutter/issues/72702

**Closed by darshankawar** 2020-12-29 07:09 UTC
