### ISSUE TITLE
The TextField widget cannot implement an auto-complete prompt, similar to Android's AutoCompleteTextView.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#53393] opened 2020-03-27 05:11 UTC
The TextField widget cannot implement an auto-complete prompt, similar to Android's AutoCompleteTextView.

**Comment by TahaTesser** [comment] 2020-03-27 08:01
Duplicate of [#46824](https://github.com/flutter/flutter/issues/46824)

**Closed by TahaTesser** 2020-03-27 08:01 UTC
