### ISSUE TITLE
Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by dhmani** [flutter/flutter#15861] opened 2018-03-23 12:05 UTC
From URL: https://flutter.io/get-started/codelab/index.md

**Comment by mit-mit** [comment] 2018-03-23 12:15
Can you elaborate on what the issue is, please?

**Comment by Phrohdoh** [comment] 2018-03-23 15:00
@mit-mit That link is a 404.

**Comment by mit-mit** [comment] 2018-03-23 15:14
Where did you find it? The actual page is https://flutter.io/get-started/codelab/.

The `.md` file is the source code of the page.

**Comment by Herohtar** [comment] 2018-03-24 05:41
@mit-mit This issue is the result of what happens when someone clicks the "File Issue" link on that page and then hits "Submit new issue" without typing anything...

Source of the link:
```
<a href="https://github.com/flutter/flutter/issues/new?title=Issue from website page Write Your First Flutter App&amp;body=From URL: https://flutter.io/get-started/codelab/index.md&amp;labels=dev: docs - website" class="btn btn-sm">
```

**Comment by mit-mit** [comment] 2018-03-24 13:00
@Herohtar, thanks, yup that is likely what happened. But as no actual issue has been mentioned, I'm going to close this.

**Closed by mit-mit** 2018-03-24 13:00 UTC
