### ISSUE TITLE
Please support iOS simulator in release mode

### ISSUE THREAD

**Issue by sma** [flutter/flutter#54098] opened 2020-04-06 15:14 UTC
I want to add Flutter to an existing iOS framework (not an application).

I created a flutter module and used `flutter build ios-framework --universal --no-profile --no-debug --output Frameworks` to create `App.framework` and the  `Flutter.framework`.

I don't need the profile mode.

I cannot use the debug mode, because I cannot assume that users of my framework have Flutter installed and/or are aware of the fact that I'm using Flutter. It's an implementation detail I do not want to expose.

But release mode doesn't support the simulator and without simulator support the development experience is poor and it is difficult to explain to the customer why the simulator isn't available.

Please support building the a release mode Flutter framework for the iOS simulator (that is please support the x86_64 architecture in addition to the arm7 and arm64 architecture).

**Comment by TahaTesser** [comment] 2020-04-06 15:30
Duplicate of [#11754](https://github.com/flutter/flutter/issues/11754)

**Closed by TahaTesser** 2020-04-06 15:30 UTC
