### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28

### ISSUE THREAD

**Issue by kinan96** [flutter/flutter#84604] opened 2021-06-14 23:24 UTC
## Command
```
flutter build ios --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: No space left on device, errno = 28
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:606:14)
#2      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:131:16)
#3      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:81:17)
#4      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#5      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#6      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:423:23)
<asynchronous suspension>
#7      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:93:43)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-EG)
    • Flutter version 1.20.2 at /Users/kinan/Desktop/flutter
    • Framework revision bbfbf1770c (10 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+8
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
ext_storage-1.0.3
firebase_analytics-6.0.0
firebase_analytics_web-0.1.1
firebase_auth-0.18.0+1
firebase_auth_web-0.3.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_messaging-7.0.0
firebase_storage-4.0.0
flutter_downloader-1.5.2
flutter_local_notifications-1.5.0+1
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-7.1.6
google_maps_flutter-0.5.31
image_picker-0.6.7+7
open_file-3.0.3
path_provider-1.6.22
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
path_provider_windows-0.0.4+1
permission-0.1.7
share-0.6.5
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
simple_connectivity-0.1.1
url_launcher-5.5.3
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.3+1

**Comment by darshankawar** [comment] 2021-06-15 08:16
Closing this as duplicate of https://github.com/flutter/flutter/issues/54213

**Closed by darshankawar** 2021-06-15 08:16 UTC
Labels: in triage
