### ISSUE TITLE
Flaky Fuchsia build failure on LUCI

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#43020] opened 2019-10-18 17:51 UTC
Seeing a (flaky) failure during Fuchsia build on Linux host occuring during `../../flutter/tools/fuchsia/gen_package.py` run. This repros at https://github.com/flutter/engine/commit/67de0bf44b80dda972fb8cecbdf1f48f4fa57aac.

Log output:
```
[62/85] ACTION //flutter/shell/platform/fuchsia/flutter:flutter_aot_runner(//build/toolchain/fuchsia:fuchsia)
FAILED: flutter_aot_runner_far.manifest flutter_aot_runner.far 
python ../../flutter/tools/fuchsia/gen_package.py --pm-bin /b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/tools/pm --package-dir /b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far --signing-key /b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/development.key --far-name flutter_aot_runner
stat : no such file or directory
==================== Manifest contents =========================================
lib/libsyslog.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libsyslog.so
lib/libc++abi.so.1=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libc++abi.so.1
lib/libc++.so.2=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libc++.so.2
lib/libunwind.so.1=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libunwind.so.1
lib/libc.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libc.so
lib/libvulkan.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libvulkan.so
lib/libfdio.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libfdio.so
lib/libmemfs.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libmemfs.so
lib/ld.so.1=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/ld.so.1
lib/libasync-default.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libasync-default.so
lib/libtrace-engine.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libtrace-engine.so
lib/libtrace-provider-so.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libtrace-provider-so.so
lib/libzircon.so=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/lib/libzircon.so
meta/flutter_aot_runner.cmx=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/meta/flutter_aot_runner.cmx
meta/package=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/meta/package
data/observatory.tar=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/data/observatory.tar
data/flutter_aot_runner.dartprofilersymbols=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/data/flutter_aot_runner.dartprofilersymbols
data/icudtl.dat=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/data/icudtl.dat
bin/app=/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far/bin/app

==================== End manifest contents =====================================
Traceback (most recent call last):
  File "../../flutter/tools/fuchsia/gen_package.py", line 110, in <module>
    sys.exit(main())
  File "../../flutter/tools/fuchsia/gen_package.py", line 97, in main
    subprocess.check_output(pm_command_base + ['build'])
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/tools/pm', '-o', '/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64', '-k', '/b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/development.key', '-m', '/b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far.manifest', 'build']' returned non-zero exit status 1
```

Specifically, the failing command is:
```
/b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/tools/pm -o /b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64 -k /b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/development.key -m /b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far.manifest build
```

/cc @iskakaushik

**Comment by jason-simmons** [comment] 2019-10-18 18:07
Duplicate of https://github.com/flutter/flutter/issues/42468

**Closed by jason-simmons** 2019-10-18 18:07 UTC
Labels: customer: fuchsia, engine, team: flakes
