### ISSUE TITLE
libEGL warning in linux desktop app

### ISSUE THREAD

**Issue by pskink** [flutter/flutter#57013] opened 2020-05-12 16:32 UTC
setup: 

```
$> flutter --version
Flutter 1.19.0-1.0.pre.43 • channel master • https://github.com/flutter/flutter.git
Framework • revision c969b8af7b (18 hours ago) • 2020-05-11 15:28:10 -0700
Engine • revision ada8a0fd64
Tools • Dart 2.9.0 (build 2.9.0-8.0.dev a6d06b59ec)

```
## Steps to Reproduce

1. Run `flutter -d linux run`.

**Expected results:**
app is shown

**Actual results:**
main window is blank and the following warning appears:

`libEGL warning: failed to create a pipe screen for i965`

seems like a problem in the newest `libflutter_linux_glfw.so` (from 1.19 flutter version - in 1.14 everything was working fine)

**Comment by stuartmorgan** [comment] 2020-05-12 19:44
This is below the level of Flutter; if your system doesn't have a working EGL, the GLFW embedding cannot run.

The reason that this wasn't true before was that we were—incorrectly—failing to specific that EGL was required, which only worked because of bug in GL libraries that has been fixed in more recent versions (meaning that if we don't specify EGL, the embedding would fail to run on newer systems).

You'll need to resolve this at your system level; searches for that error message suggest the problem is likely either in your EGL library, or a driver.

**Closed by stuartmorgan** 2020-05-12 19:44 UTC

**Comment by pskink** [comment] 2020-05-12 20:00
would it be possible to find what version introduced that breaking change? my previous version (1.14) was working fine but it was 3 months old and I wanted to make some upgrade... I already tried to fix egl lib but I failed so I think for now the only solution is to downgrade...

**Comment by stuartmorgan** [comment] 2020-05-12 20:02
It was likely https://github.com/flutter/engine/pull/16924

**Comment by pskink** [comment] 2020-05-12 20:05
thanks a lot!
