### ISSUE TITLE
[in_app_purchase] Migrate Android Billing Client to Billing Library version 4 or Newer

### ISSUE THREAD

**Issue by smith897** [flutter/flutter#110742] opened 2022-09-01 03:16 UTC
The Google Play Console currently shows the following warning when using the latest version

`We've detected that this app is using an old version of Google Play Billing. By November 1, 2022, all app updates must use Billing Library version 4 or newer. Update to Billing Library 4 before this date.`

I believe this is the dependency that needs to be updated? https://github.com/flutter/plugins/blob/a87497f1399cf6b074dc98563168569d8f738348/packages/in_app_purchase/android/build.gradle#L38

**Comment by stuartmorgan** [comment] 2022-09-01 03:32
> The Google Play Console currently shows the following warning when using the latest version

You aren't using the latest version if you are seeing that warning; you need to `flutter pub upgrade` so that you have the current version of the `in_app_purchase_android` implementation package.

> I believe this is the dependency that needs to be updated? https://github.com/flutter/plugins/blob/a87497f1399cf6b074dc98563168569d8f738348/packages/in_app_purchase/android/build.gradle#L38

That link is to a version of the repository that's more than a year old. The current version is https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L56

Closing as a duplicate of https://github.com/flutter/flutter/issues/88664

**Closed by stuartmorgan** 2022-09-01 03:32 UTC
