### ISSUE TITLE
WebView can not load two different urls.

### ISSUE THREAD

**Issue by liujinchaoDS** [flutter/flutter#40078] opened 2019-09-09 08:54 UTC
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(WebPage());

class WebPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _WebPageState();
  }
}

class _WebPageState extends State<WebPage> {
  String url = "https://flutter.dev/";

  void _changeUrl() {
    setState(() {
      this.url = "https://github.com/flutter/flutter";
    });
  }

  @override
  Widget build(BuildContext context) {
    print("url:" + url);
    return MaterialApp(
        theme: ThemeData(primarySwatch: Colors.blue),
        home: Scaffold(
          appBar: AppBar(
            title: Text("WebPage"),
          ),
          body: WebView(
            initialUrl: url,
            javascriptMode: JavascriptMode.unrestricted,
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _changeUrl,
            child: Icon(Icons.replay),
          ),
        ));
  }
}
```

In the code above, I print the url message at the first line in build method. And here, the url is right, but the webView has no effect.
I use the webview_flutter lib, and the version is 0.3.13;

**Comment by BondarenkoStas** [comment] 2019-09-09 10:59
@liujinchaoDS Please provide your ```flutter doctor -v```

**Comment by romatallinn** [comment] 2019-09-09 18:26
@BondarenkoStas I do have a similar issue; some pages are loaded, some are not. The issue happens on iOS. Cannot check on Android at the moment.

```
[✓] Flutter (Channel unknown, v1.9.6, on Mac OS X 10.14.6 18G87, locale en-NO)
    • Flutter version 1.9.6 at /Users/rsirokov/Projects/Plugins/flutter
    • Framework revision 35de8d5278 (12 days ago), 2019-08-28 16:49:49 +0300
    • Engine revision f8c4546eb4
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/rsirokov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • iPhone X • XXX-XXX-XXX • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

```

**Comment by liujinchaoDS** [comment] 2019-09-10 06:36
> @liujinchaoDS Please provide your `flutter doctor -v` output

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/ljc/Flutter/flutter-stable-1.0.0
    • Framework revision 20e59316b8 (8 周前), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ljc/Android/Sdk
    • Android NDK at /home/ljc/Android/Sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /mnt/A/AndroidStudio/as-3.6/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /mnt/A/AndroidStudio/as-3.6
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.4)
    • Android Studio at /mnt/A/AndroidStudio/as-3.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ljc/Android/as-3.5
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

**Comment by sarimk80** [comment] 2019-09-10 09:39
What you are looking for is WebController.
This Video might help: https://www.youtube.com/watch?v=RA-vLF_vnng

```
class _MyHomePageState extends State<MyHomePage> {
  String URL;
  WebViewController _controller;

  @override
  void initState() {
    URL = 'https://flutter.dev/';

    super.initState();
  }

  void _click() async {
    await _controller.loadUrl("https://github.com/flutter/flutter");
  }

  @override
  Widget build(BuildContext context) {
    print(URL);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          width: 500,
          child: WebView(
            onWebViewCreated: (WebViewController c) {
              _controller=c;
            },
            javascriptMode: JavascriptMode.unrestricted,
            initialUrl: URL,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _click,
        child: Icon(Icons.ac_unit),
      ),
    );
  }
}

```

**Comment by romatallinn** [comment] 2019-09-10 09:53
I have solved my issue; it was caused by the HTTP protocol in my URL. The iOS does not handle it by default. Thus, I had to allow it by manually adding a parameter into `Info.plist`.

```XML
<key>NSAppTransportSecurity</key> <dict> <key>NSAllowsArbitraryLoads</key> <true/>
<key>NSAllowsArbitraryLoadsInWebContent</key> <true/> </dict>
```

**Comment by darshankawar** [comment] 2020-06-19 07:13
@liujinchaoDS  the code sample provided by @sarimk80 seem to resolve the issue you mentioned originally. I tested it on latest `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter` and it loads different url upon FAB click using `WebViewController`.

[40078.mp4.zip](https://github.com/flutter/flutter/files/4802951/40078.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>code sample -v</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(WebPage());

class WebPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _WebPageState();
  }
}

class _WebPageState extends State<WebPage> {
  String url;
  WebViewController webViewController;

  @override
  void initState() {
    url = "https://flutter.dev/";
    super.initState();

  }

  void _click() async {
    await webViewController.loadUrl("https://github.com/flutter/flutter");
  }

//  void _changeUrl() {
//    setState(() {
//      this.url = "https://github.com/flutter/flutter";
//    });
//  }

  @override
  Widget build(BuildContext context) {
    print("url:" + url);
    return MaterialApp(
        theme: ThemeData(primarySwatch: Colors.blue),
        home: Scaffold(
          appBar: AppBar(
            title: Text("WebPage"),
          ),
          body: WebView(
            onWebViewCreated: (WebViewController c) {
              webViewController=c;
            },
            javascriptMode: JavascriptMode.unrestricted,
            initialUrl: url,
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _click,
            child: Icon(Icons.replay),
          ),
        ));
  }
}
```

</details>

Closing this issue since, using `WebViewController` we are able to load different urls properly. Feel free to reopen this issue if you think otherwise.

**Closed by darshankawar** 2020-06-19 07:13 UTC
Labels: d: api docs, p: webview, platform-ios, plugin
