### ISSUE TITLE
[Mac OS] Android Studio Flutter console weird behavior (two line breaks after each line and limited output)

### ISSUE THREAD

**Issue by Fleximex** [flutter/flutter#66635] opened 2020-09-25 09:05 UTC
I'm using Android Studio 4 on a MacBook and in the Run window every Flutter line (lines that start with `Flutter:`) has two line breaks after it. Other lines don't have this issue.
<details>
<summary>Example</summary>

```
flutter: method: GET


flutter: responseType: ResponseType.json


flutter: followRedirects: true


flutter: connectTimeout: 30000


flutter: receiveTimeout: 30000


flutter: extra: {}


```
</details>

Another issue is that the output is limited to `Flutter:`. Normally the console outputs something like ` I/flutter ( 6731):`.

<details>
<summary>Flutter Doctor output</summary>

```
*hidden*-MBP ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/*hidden*/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/*hidden*/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • *hidden*’s iPhone (mobile) • 00008030-001019263CA0402E • ios • iOS 13.6

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2020-09-25 15:08
Hi @Fleximex 
Just tried to print logs in Android Studio, no line breaks
```
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           26.8s
Waiting for iPhone 11 to report its views...
Debug service listening on ws://127.0.0.1:60649/SZloD82Nyfg=/ws
Syncing files to device iPhone 11...
flutter: test
flutter: test
flutter: test
flutter: test
flutter: test
flutter: test

```

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    print('test');
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      14.0.1
    • iPhone 11 (mobile)     • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details> 

Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by Fleximex** [comment] 2020-09-28 07:47
@TahaTesser 

I just tested it with the default Flutter project of version 1.20.4. I added a print statement to the `_incrementCounter()` method and every line has 2 line breaks after it:

<details>
<summary>Console Flutter output</summary>

```
flutter: counter: 1


flutter: counter: 2


flutter: counter: 3


flutter: counter: 4



```
</details>

**Comment by TahaTesser** [comment] 2020-09-28 09:21
Hi @Fleximex 
Just tried on the physical device I was able to reproduce the on the `stable` channel
However then I tried on beta, it doesn't reproduce anymore

```
Launching lib/main.dart on Taha’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...
Xcode build done.                                           19.7s
Installing and launching...
Waiting for Taha’s iPhone to report its views...
Debug service listening on ws://localhost:58659/ws
Syncing files to device Taha’s iPhone...
flutter: test
flutter: test
flutter: test
flutter: test
flutter: test
flutter: test
flutter: test

```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.7 19H2, locale
    en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8b3760638a (12 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0.1

• No issues found!

```

</details> 


I cannot reproduce this issue on the latest `beta` channel.
Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`


This was fixed in https://github.com/flutter/flutter/issues/63082

**Comment by Fleximex** [comment] 2020-09-28 11:35
I can confirm that the beta build does not have this issue. I now see it has already been mentioned before. It is a shame that the stable build still has this issue though.

@TahaTesser you can close this issue.

**Closed** 2020-09-28 13:13 UTC
Labels: in triage
