### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50434/LKJqQ0QZ9xg=/ws

### ISSUE THREAD

**Issue by Rehan164** [flutter/flutter#33900] opened 2019-06-05 06:01 UTC
I am using visual studio code and keep getting this

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50434/LKJqQ0QZ9xg=/ws
Exited (sigterm)

Then it shows a white screen on my android sim.
Need some help.

**Comment by Rehan164** [comment] 2019-06-05 06:01
Btw I just started to use flutter so pls help.

**Comment by DanTup** [comment] 2019-06-05 12:16
Did you create an Android emulator using Q level API?

If so, I think this is a dupe of https://github.com/flutter/flutter/issues/33050

**Comment by harrysummer** [comment] 2019-06-12 18:44
Thanks @DanTup . I have exactly the same problem and use API level 28 solves my problem.

**Comment by liugangnhm** [comment] 2019-06-20 08:46
same issue when i use iphone 6s with ios 12.2

**Comment by Rehan164** [comment] 2019-06-24 06:13
> Did you create an Android emulator using Q level API?
> If so, I think this is a dupe of #33050. Try creating one using API level 28 to see if that solves the issue until there's a fix.

Thanks man. Got it working. Sorry for the late response. ;)

**Closed** 2019-06-24 06:14 UTC

**Comment by MehdiBukhari** [comment] 2019-12-26 08:03
> Did you create an Android emulator using Q level API?
> 
> If so, I think this is a dupe of #33050. Try creating one using API level 28 to see if that solves the issue until there's a fix

solved by this.
