### ISSUE TITLE
appName = null

### ISSUE THREAD

**Issue by blondie63** [flutter/flutter#47620] opened 2019-12-22 16:16 UTC
Hi, i'm using package_info 0.4.0+13
this my pubspec.yaml:
name: catalogo.mobi.flutter
description: CATALOGO.MOBI Flutter project.
version: 2.7.0+1

using:
```
import 'package:package_info/package_info.dart';

PackageInfo packageInfo = await PackageInfo.fromPlatform();

String appName = packageInfo.appName;
String packageName = packageInfo.packageName;
String version = packageInfo.version;
String buildNumber = packageInfo.buildNumber;
```

I get all right values but appName is always = null
also rebuilding Xcode build folder..

whats wrong ?

**Comment by iapicca** [comment] 2019-12-23 10:09
Hi @blondie63 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by blondie63** [comment] 2019-12-23 13:38
Hi, first test was on my code and i've found issue only for appName
Then is test example plugin code: (https://github.com/flutter/plugins/tree/master/packages/package_info/example)
this is screenshot for app running on my mac:
<img width="1283" alt="FL-pack-info" src="https://user-images.githubusercontent.com/1261851/71360722-030eab00-2591-11ea-9497-38cba8eab026.png">

flutter doctor -v
`
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale it-IT)
    • Flutter version 1.12.13+hotfix.5 at /Users/mauro/Documents/SDK/flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/mauro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPad Pro (11-inch) • 271E614C-7A42-47BB-A95E-795BBDB20840 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
`
flutter run --verbose
[FL-pack-info-log.txt](https://github.com/flutter/flutter/files/3995132/FL-pack-info-log.txt)

Thanks

**Comment by azol** [comment] 2019-12-25 13:23
same issue. iOS appName is always null :( Android is OK.

Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.1 19B88, locale en-GB)

```
void main() => runApp(NoAppName());

class NoAppName extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('NoAppName'),
        ),
        body: FutureBuilder(
            future: PackageInfo.fromPlatform(),
            builder: (BuildContext context, snapshot) {
              if (snapshot.hasData) {
                String appName = snapshot.data.appName;
                String version = snapshot.data.version;
                return Center(child: Text('$appName: $version'));
              } else {
                return Center(
                  child: CircularProgressIndicator(),
                );
              }
            }),
      ),
    );
  }
}
```

**Comment by blondie63** [comment] 2020-01-18 07:59
Someone has found solution for this issue ?

**Comment by LeoAiolia** [comment] 2020-03-02 07:16
same issue. iOS appName is alway null, package_info: ^0.4.0+14, Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)

![图片](https://user-images.githubusercontent.com/16910025/75653398-7838e380-5c98-11ea-8c3c-32f81df6d60a.png)

**Comment by sgehrman** [comment] 2020-03-24 02:23
just discovered this bug today.  Very annoying.  Is there a work around?

**Comment by blondie63** [comment] 2020-03-30 08:40
> Use: CFBundleDisplayName
> 
> Info.plist
> 
> ```
> <key>CFBundleDisplayName</key>
> <string>Your App Name Here</string>
> ```

ok but this is a workaround, right ? appName always null is a bug of this plugin, right ?

**Comment by HugoHeneault** [comment] 2020-04-01 14:33
This is a duplicate of https://github.com/flutter/flutter/issues/42510

More details on why this is happening on [this answer](https://github.com/flutter/flutter/issues/42510#issuecomment-583622026).

You should use `CFBundleDisplayName ` as said above :)

**Comment by iapicca** [comment] 2020-04-03 10:30
Hi @blondie63 
as @HugoHeneault pointed out there's an open [issue](https://github.com/flutter/flutter/issues/42510) addressing the case you described.

Please follow up on that issue,
I'm closing the current one as duplicate.

If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-03 10:30 UTC
Labels: p: first party, p: package_info, platform-ios, plugin
