### ISSUE TITLE
download files inside webview flutter

### ISSUE THREAD

**Issue by Sathi789888** [flutter/flutter#51996] opened 2020-03-05 06:27 UTC
i have a webview (webview_flutter 0.3.19+9 plugin) .when user goes to webview and click a link to download a file nothing is happening.

**Comment by TahaTesser** [comment] 2020-03-05 07:44
duplicate of [39321](https://github.com/flutter/flutter/issues/39321)

**Closed by TahaTesser** 2020-03-05 07:44 UTC
