### ISSUE TITLE
[Android] Support for native spell checkers in flutter

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#65009] opened 2020-09-01 10:10 UTC
Native spell checkers are the easiest way to use auto correction and spell check with very less to no work for implementation. Yet they are very powerful and since no values are hard coded, its adaptive.
This feature is critical for any app expecting user inputs.

**Comment by sidrao2006** [comment] 2020-09-01 10:29
This issue includes #34688 which focuses only on iOS and #40682 which focuses on web.

**Comment by pedromassangocode** [comment] 2020-09-01 11:51
Hi @sidrao2006 
Not sure if I understood it clearly this issue. Is this a proposal to support spell checkers for Android devices? please elaborate more about this.

**Comment by sidrao2006** [comment] 2020-09-01 13:02
@pedromassangocode thanks for replying
Yes, this is a proposal for spell checkers mainly Android. But support for all platforms is needed.

**Comment by dnfield** [comment] 2020-09-02 06:04
This would probably make the most sense as a plugin.

I don't think anyone on the team has bandwidth right now to take on a new plugin, but if there's a good third party implementation perhaps we could get it reviewed as a Flutter Favorite or something like that.

**Comment by dnfield** [comment] 2020-09-02 06:05
I'm going to close this as a duplicate of #34688 which mentions Android in the comments as well.

**Closed by dnfield** 2020-09-02 06:05 UTC
Labels: a: text input, platform-android, proposal, severe: new feature, would be a good package

**Comment by sidrao2006** [comment] 2020-09-02 10:28
Requesting support for native auto replace as well which are very well integrated in Android native apps and should definitely be there in flutter. Preferably in the framework itself as it is a core feature

@dnfield , can you please reopen this issue?

**Comment by dnfield** [comment] 2020-09-02 15:33
I'm not sure what you mean by autoreplace, but sounds like that should be a new issue.

What does this issue add that the linked duplicate doesn't already?  We try not to keep duplicate issues open as it makes triage more challenging.

**Comment by sidrao2006** [comment] 2020-09-03 03:39
![20200903_090832.jpg](https://user-images.githubusercontent.com/66567899/92068660-1ed77b80-edc5-11ea-9096-458e0fdb620e.jpg)

An example of auto replace in Samsung keyboard

**Comment by sidrao2006** [comment] 2020-09-03 03:41
@dnfield I feel this is a core functionality that is to be implemented in the framework itself rather than the plugin

**Comment by dnfield** [comment] 2020-09-03 14:52
I'm still not sure if I'm clear which feature auto-replace is (Android documentation link would probably be helpful), but we should probably open a separate bug to track it if it's a different feature.

**Comment by sidrao2006** [comment] 2020-09-03 14:55
Sorry, I tried to reproduce it again and found out that Samsung keyboard 's auto replace does work even now
