### ISSUE TITLE
Released Flutter web app missing LICENSE asset

### ISSUE THREAD

**Issue by eleazargan** [flutter/flutter#60896] opened 2020-07-06 09:56 UTC
## Steps to Reproduce

1. Run `flutter build web`.
2. Run `npx serve` in build/web folder
3. Open localhost url in browser.

**Expected results:** 
```
/build/web
  assets
    AssetManifest.json
    FontManifest.json
    LICENSE
    fonts
      MaterialIcons-Regular.ttf
      <other font files>
    <image files>
  index.html
  main.dart.js
  main.dart.js.map

```
This is the expected files and folders after compile as found in https://flutter.dev/docs/deployment/web#building-the-app-for-release

**Actual results:** 
<img width="951" alt="Screenshot 2020-07-06 at 5 54 25 PM" src="https://user-images.githubusercontent.com/22090264/86580809-c9901100-bfb1-11ea-9b90-4b9f40b1650c.png">

This is the result I get after running compiled Flutter web app.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-06 12:14
True for current beta `1.19.0-4.3.pre` and master `1.20.0-3.0.pre.130`. 
But the NOTICES file is generated in assets

**Comment by eleazargan** [comment] 2020-07-06 12:27
@VladyslavBondarenko  Correct me if i’m wrong. What I understand from your explanation is that LICENSE file won’t be generated into the assets anymore and instead replaced with NOTICES file. If so, why does the app still looked for LICENSE file from the asset?

**Comment by VladyslavBondarenko** [comment] 2020-07-06 14:10
@eleazargan 
I can't see that app is looking for LICENSE file

![image](https://user-images.githubusercontent.com/17024977/86602403-453a8f80-bfab-11ea-964a-012e45737741.png)

Could you provide your `flutter doctor -v`?

**Comment by eleazargan** [comment] 2020-07-06 14:39
<img width="981" alt="Screenshot 2020-07-06 at 10 37 48 PM" src="https://user-images.githubusercontent.com/22090264/86605469-54383680-bfd9-11ea-9590-e2efe777b56e.png">

@VladyslavBondarenko  Here's the result from `flutter doctor -v` on my device. I'm not developing for mobile app so I reckon I would not need Xcode and Android toolchain.

**Comment by eleazargan** [comment] 2020-07-06 15:33
<img width="1440" alt="Screenshot 2020-07-06 at 11 31 00 PM" src="https://user-images.githubusercontent.com/22090264/86611102-c6f8e000-bfe0-11ea-9251-efb5b54122a3.png">

Using the setup of Flutter version that I have, I've created a new app just to make sure it is not because of the issue with the current app that I am working on. It still happened even in a new and freshly created app. The example above is run with `flutter run -d chrome --release`

**Comment by VladyslavBondarenko** [comment] 2020-07-06 16:16
@eleazargan 
I see this now, when running with beta and when doing regular refresh (not hard reload).
But I can't see this when running with dev or master. Can you confirm that LICENSE in not looked for with other flutter versions?

**Comment by ferhatb** [comment] 2020-07-06 22:16
Related to https://github.com/flutter/flutter/pull/57871

**Comment by eleazargan** [comment] 2020-07-07 01:42
@VladyslavBondarenko
Yep. Building the app with `master` seem to have solved the issue. Also, the issue does not appear when building with `beta` version `1.7.5`. However, once I upgraded to `1.19.0-4.3.pre` on `beta`, the issue persist.

**Comment by eleazargan** [comment] 2020-07-07 01:45
<img width="875" alt="Screenshot 2020-07-07 at 9 25 14 AM" src="https://user-images.githubusercontent.com/22090264/86685666-4533a180-c036-11ea-90d2-8d006bbadb44.png">

I would like to also get a clear understanding on whether this piece of information from the Flutter documentation website is still relevant. 
1. Has Flutter web support past the development period?
2. Can we safely use `master` or `stable` channel to build our Flutter for web app?

**Comment by yjbanov** [comment] 2020-07-09 22:35
@jonahwilliams Could this be due to existing apps picking up the old file? Is there a migration guide for the rename (if necessary)?

**Comment by jonahwilliams** [comment] 2020-07-09 23:02
The aggregate LICENSE file is being renamed to NOTICES. If the flutter_service_worker.js was generated incorrectly it will contain an entry for `"assets/LICENSE"` instead of `""assets/NOTICES"` - but updating the former to the latter will fix it (at least until you build the next time).

Sorry for the trouble here, I missed the rename working through all the other platforms so the web service worker was updated later: https://github.com/flutter/flutter/pull/58890

> Could this be due to existing apps picking up the old file?

No, its just a regular bug

**Comment by jonahwilliams** [comment] 2020-07-09 23:03
Duplicate of https://github.com/flutter/flutter/issues/57904

**Comment by jmagman** [comment] 2020-07-15 00:53
@jonahwilliams should this be closed? Was it fixed with https://github.com/flutter/flutter/pull/58890?

**Comment by jonahwilliams** [comment] 2020-07-15 00:54
Yes, also the website has been updated with https://github.com/flutter/website/pull/4325

**Closed by jonahwilliams** 2020-07-15 00:54 UTC
Labels: P4, documentation, framework, platform-web, tool
