### ISSUE TITLE
[firebase_auth] Support sign in with Apple

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#46848] opened 2019-12-12 07:28 UTC
Sign in with apple should be added, Firebase Auth now supports it.

<img width="673" alt="Screen Shot 2019-12-11 at 11 28 18 PM" src="https://user-images.githubusercontent.com/13773566/70691447-f5425700-1c6d-11ea-866d-06b7a58616ff.png">

**Comment by EliasDeuss** [comment] 2019-12-12 07:31
Here are the links to the apis for the supported platforms:
[iOS](https://firebase.google.com/docs/auth/ios/apple?authuser=0)
[Android](https://firebase.google.com/docs/auth/android/apple?authuser=0)
[Web](https://firebase.google.com/docs/auth/web/apple?authuser=0)

**Comment by iapicca** [comment] 2019-12-12 12:59
Hi @EliasDeuss 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-12 12:59 UTC
