### ISSUE TITLE
flutter emulator --launch opens emulator at wrong resolution with older versions of Android SDK emulator tool

### ISSUE THREAD

**Issue by jensjoha** [flutter/flutter#23988] opened 2018-11-06 09:06 UTC
## Steps to Reproduce

Creating an android emulator through flutter creates one with a small screen somehow.

1. $ flutter emulator --create
2. $ flutter emulator --launch flutter_emulator
3. Looks too small
![screenshot](https://user-images.githubusercontent.com/20773519/48052399-1c477300-e1a8-11e8-8047-da6d6756c144.png)
4. Opening avd manager from android studio gives me this (notice for instance 'android null'):
![screenshot](https://user-images.githubusercontent.com/20773519/48052540-83652780-e1a8-11e8-8ce9-b76a03206f62.png)
5. Launching it from avd manger is the same as launching via flutter command line
6. Pressing edit in avd manger, folowed by 'finish' without changing anything changes it to this: 
![screenshot](https://user-images.githubusercontent.com/20773519/48052698-fff80600-e1a8-11e8-9244-5b9950103144.png) (i.e. seemingly making it take more space on disk, but nothing else changed), but now, launching it gives me this:
![screenshot](https://user-images.githubusercontent.com/20773519/48052777-30d83b00-e1a9-11e8-8211-6a6493e8d59a.png)

Looking at my .android/avd dir, the content of 'config.ini' has changed; 'userdata.img' is the same; 'sdcard.img' was created.

Playing around with 'config.ini' it seems that adding "skin.name=1080x1920" to the one created by flutter emulator --create does the trick...

flutter doctor -v:
```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.3-pre.104, on Linux, locale en_US.UTF-8)
    • Flutter version 0.10.3-pre.104 at [pathto]/flutter/flutter
    • Framework revision 7e652d1dba (8 hours ago), 2018-11-05 20:00:19 -0500
    • Engine revision 3374f4cce0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at [pathto]/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: [pathto]/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 2.3)
    • Android Studio at [pathto]/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ue-2017.3
    • Flutter plugin version 20.0.2
    • Dart plugin version 173.4700

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /opt/intellij-ue-2018.1
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment] 2018-11-06 20:46
Thanks for the investigation! Can you try running `flutter emulators --create -v` and finding the call to `adb` that creates the emulator?

We don't pass a lot of args for the creation, maybe we need to add some more

https://github.com/flutter/flutter/blob/48c00dc7d75780615abb7cd82c44792ce3dda19a/packages/flutter_tools/lib/src/emulator.dart#L112-L121

**Comment by jensjoha** [comment] 2018-11-07 08:32
That command isn't traced (no tracing in runSync in local_process_manager.dart) --- printing it myself yields
```
-----
Executable: [pathto]/Android/Sdk/tools/bin/avdmanager
Arguments: [create, avd, -n, temp]
Working directory: null
-----
Executable: [pathto]/Android/Sdk/tools/bin/avdmanager
Arguments: [create, avd, -n, flutter_emulator, -k, system-images;android-27;google_apis_playstore;x86, -d, pixel]
Working directory: null
-----
```

It seems from
https://stackoverflow.com/questions/32914660/create-an-emulator-with-a-decent-size-from-command-line
https://issuetracker.google.com/issues/37137534
https://stackoverflow.com/questions/43614908/android-emulator-from-command-line-has-weird-resolution

that the workaround is probably to launch it differently, e.g. in one of these two ways:
```
[pathto]/Android/Sdk/tools/emulator -avd flutter_emulator -skin pixel -skindir [pathto]/Android/Sdk/skins/
[pathto]/Android/Sdk/tools/emulator -avd flutter_emulator -skin 1080x1920
```

**Comment by DanTup** [comment] 2019-01-04 12:01
@jensjoha Sorry, I did search and send some emails but didn't get anywhere.

I'm not sure if the issue is with how we're launching, or creating. Could you compare your ini files (for a freshly-created, broken image) to the below? I created this with the same args you gave above (`avdmanager create avd -n flutter_emulator_foo -k "system-images;android-27;google_apis_playstore;x86" -d pixel`):

### flutter_emulator_foo.ini
```ini
avd.ini.encoding=UTF-8
path=/Users/dantup/.android/avd/flutter_emulator_foo.avd
path.rel=avd/flutter_emulator_foo.avd
target=android-27
```

### config.ini
```ini
PlayStore.enabled=false
abi.type=x86
avd.ini.encoding=UTF-8
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.cpu.arch=x86
hw.dPad=no
hw.device.hash2=MD5:524882cfa9f421413193056700a29392
hw.device.manufacturer=Google
hw.device.name=pixel
hw.gps=yes
hw.lcd.density=480
hw.lcd.height=1920
hw.lcd.width=1080
hw.mainKeys=no
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-27/google_apis_playstore/x86/
tag.display=Google Play
tag.id=google_apis_playstore
```

### hardware-qemu.ini
```ini
hw.cpu.arch = x86
hw.cpu.model = qemu32
hw.cpu.ncore = 2
hw.ramSize = 1536
hw.screen = multi-touch
hw.mainKeys = false
hw.trackBall = false
hw.keyboard = false
hw.keyboard.lid = false
hw.keyboard.charmap = qwerty2
hw.dPad = false
hw.rotaryInput = false
hw.gsmModem = true
hw.gps = true
hw.battery = true
hw.accelerometer = true
hw.gyroscope = true
hw.audioInput = true
hw.audioOutput = true
hw.sdCard = true
disk.cachePartition = true
disk.cachePartition.path = /Users/dantup/.android/avd/flutter_emulator_foo.avd/cache.img
disk.cachePartition.size = 66m
test.quitAfterBootTimeOut = -1
hw.lcd.width = 1080
hw.lcd.height = 1920
hw.lcd.depth = 16
hw.lcd.density = 480
hw.lcd.backlight = true
hw.gpu.enabled = true
hw.gpu.mode = host
hw.gpu.blacklisted = no
hw.initialOrientation = portrait
hw.camera.back = emulated
hw.camera.front = none
vm.heapSize = 384
hw.sensors.light = true
hw.sensors.pressure = true
hw.sensors.humidity = true
hw.sensors.proximity = true
hw.sensors.magnetic_field = true
hw.sensors.magnetic_field_uncalibrated = true
hw.sensors.gyroscope_uncalibrated = true
hw.sensors.orientation = true
hw.sensors.temperature = true
hw.useext4 = true
hw.arc = false
hw.arc.autologin = false
kernel.path = /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86//kernel-ranchu
kernel.newDeviceNaming = yes
kernel.supportsYaffs2 = no
disk.ramdisk.path = /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86//ramdisk.img
disk.systemPartition.initPath = /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86//system.img
disk.systemPartition.size = 2562m
disk.vendorPartition.initPath = /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86//vendor.img
disk.vendorPartition.size = 800m
disk.dataPartition.path = /Users/dantup/.android/avd/flutter_emulator_foo.avd/userdata-qemu.img
disk.dataPartition.initPath = /Users/dantup/.android/avd/flutter_emulator_foo.avd/userdata.img
disk.dataPartition.size = 2g
disk.encryptionKeyPartition.path = /Users/dantup/.android/avd/flutter_emulator_foo.avd/encryptionkey.img
PlayStore.enabled = false
avd.name = flutter_emulator_foo
fastboot.forceColdBoot = false
```

**Comment by jensjoha** [comment] 2019-01-04 12:11
`flutter_emulator_foo.ini` has a different path (one with my username in it)
`config.ini` is the same
`hardware-qemu.ini` I don't have that file before launching. After it's this:
```
hw.cpu.arch = x86
hw.cpu.model = qemu32
hw.cpu.ncore = 2
hw.ramSize = 1024
hw.screen = multi-touch
hw.mainKeys = false
hw.trackBall = false
hw.keyboard = false
hw.keyboard.lid = false
hw.keyboard.charmap = qwerty2
hw.dPad = false
hw.rotaryInput = false
hw.gsmModem = true
hw.gps = true
hw.battery = true
hw.accelerometer = true
hw.gyroscope = true
hw.audioInput = true
hw.audioOutput = true
hw.sdCard = true
disk.cachePartition = true
disk.cachePartition.path = /path/to/.android/avd/flutter_emulator_foo.avd/cache.img
disk.cachePartition.size = 66m
hw.lcd.width = 320
hw.lcd.height = 480
hw.lcd.depth = 16
hw.lcd.density = 480
hw.lcd.backlight = true
hw.gpu.enabled = true
hw.gpu.mode = host
hw.gpu.blacklisted = no
hw.initialOrientation = portrait
hw.camera.back = emulated
hw.camera.front = none
vm.heapSize = 256
hw.sensors.light = true
hw.sensors.pressure = true
hw.sensors.humidity = true
hw.sensors.proximity = true
hw.sensors.magnetic_field = true
hw.sensors.magnetic_field_uncalibrated = true
hw.sensors.gyroscope_uncalibrated = true
hw.sensors.orientation = true
hw.sensors.temperature = true
hw.useext4 = true
kernel.path = /path/to/Android/Sdk/system-images/android-27/google_apis_playstore/x86//kernel-ranchu
kernel.newDeviceNaming = yes
kernel.supportsYaffs2 = no
disk.ramdisk.path = /path/to/Android/Sdk/system-images/android-27/google_apis_playstore/x86//ramdisk.img
disk.systemPartition.initPath = /path/to/Android/Sdk/system-images/android-27/google_apis_playstore/x86//system.img
disk.systemPartition.size = 2562m
disk.vendorPartition.initPath = /path/to/Android/Sdk/system-images/android-27/google_apis_playstore/x86//vendor.img
disk.vendorPartition.size = 200m
disk.dataPartition.path = /path/to/.android/avd/flutter_emulator_foo.avd/userdata-qemu.img
disk.dataPartition.initPath = /path/to/.android/avd/flutter_emulator_foo.avd/userdata.img
disk.dataPartition.size = 2g
disk.encryptionKeyPartition.path = /path/to/.android/avd/flutter_emulator_foo.avd/encryptionkey.img
PlayStore.enabled = false
avd.name = flutter_emulator_foo
```
noticably
```
hw.lcd.width = 320
hw.lcd.height = 480
```

is different from yours.

**Comment by DanTup** [comment] 2019-01-04 12:36
If you open Android Studio, then Tools -> Device Manager then click "Create Virtual Device", what does the Pixel entry look like in the "Select Hardware" dialog? Mine looks like this:

<img width="1008" alt="screenshot 2019-01-04 at 12 30 00 pm" src="https://user-images.githubusercontent.com/1078012/50688243-789a0800-101c-11e9-80d2-6865cae091b9.png">

Also, if you go back to the device list and click the Edit button on a broken emulator, then click "Show Advanced Settings" and scroll down, what do you see in the Skin section? I see "pixel_silver":

<img width="627" alt="screenshot 2019-01-04 at 12 35 51 pm" src="https://user-images.githubusercontent.com/1078012/50688415-4e951580-101d-11e9-9fb6-53cfc6c08193.png">

If I open the file `/Users/dantup/Library/Android/sdk/skins/pixel_silver/layout` then it shows the display as 1080x1920. Does this all match yours?

**Comment by jensjoha** [comment] 2019-01-04 12:41
So in trying a newer system image in #23989 I think my emulator was updated and the problem seemingly have gone away. I'm currently trying to see if I can extract my old emulator (and emulator version) from a backup...

**Comment by jensjoha** [comment] 2019-01-04 14:31
With both the old and new emulator:
First screen looks similar; second screen says "pixel" instead of "pixel_silver", ~/Android/Sdk/skins/pixel/layout says
```
    display {
      width 1080
      height 1920
      x 0
      y 0
    }
```

The old emulator has version `26.1.4-4266726 (KVM 12.0.0)`. Launching stuff created with `flutter emulator --create` looks too small. 

The new emulator is version `28.0.22-5194135 (KVM 12.0.0)`. Launching stuff created with `flutter emulator --create` looks as it should. 

So there's probably just a bug in the (apparently old) emulator --- maybe the emulator version can be checked and a hint to update it issues if it's old? :/

**Comment by DanTup** [comment] 2019-01-08 10:56
Aha, thanks for tracking it down! I've updated the title to make it more descriptive - I agree a `doctor` hint may be worthwhile.

Btw, how did you check the version of emulator? Running `emulator --version` etc. doesn't seem to work, it just complains I didn't get it an AVD.

**Comment by jensjoha** [comment] 2019-01-08 11:07
With an emulator up and running there is a "More" button (an icon with 3 dots in my machine). Clicking that brings up a "Extended controls" dialog. From there there's a "Bug report" pane which states the emulator version... That of cause doesn't help in finding the version programatically to possibly issue a hint :/

Update:
`./emulator -version` (notice the one dash only) gives me
```
Android emulator version 28.0.22.0 (build_id 5194135) (CL:0514023f0a9dfa2f6382c333f2fb30e3a17fd074)
Copyright (C) 2006-2017 The Android Open Source Project and many others.
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
```

**Comment by DanTup** [comment] 2019-01-08 11:20
Aha - that's one thing I didn't try! I also re-discovered that `emulator` is also picky about the working directory!

```
dantup-macbookpro:~ dantup$ emulator -version
  [4627060160]:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at ../emulator/lib64/qt/lib
  Could not launch '/Users/dantup/../emulator/qemu/darwin-x86_64/qemu-system-i386': No such file or directory

dantup-macbookpro:~ dantup$ cd ~/Library/Android/sdk/tools 
dantup-macbookpro:tools dantup$ emulator -version
  Android emulator version 27.3.10.0 (build_id 4969155) (CL:751f3c993c814a52adf144c159615ce457c2d282)
```

**Comment by tvolkert** [comment] 2020-01-13 05:22
@DanTup is this bug still relevant?

**Comment by DanTup** [comment] 2020-01-13 16:34
I suspect not. I couldn't repro, but based on https://github.com/flutter/flutter/issues/23988#issuecomment-451433807 I think the problem my have gone away with an Android SDK update.

If @jensjoha hasn't seen this again since and nobody else has reported it (the top comment here has no 👍 's), I think we can probably close it.

**Comment by tvolkert** [comment] 2020-01-13 16:36
Thanks.  I'm going to close it.  @jensjoha feel free to file a new issue with repro details if you encounter this again.

**Closed by tvolkert** 2020-01-13 16:36 UTC
Labels: tool, waiting for customer response
