### ISSUE TITLE
[google_maps_flutter] Unable to show current location indicator

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter#59708] opened 2020-06-17 20:26 UTC
## Steps to Reproduce

1. add `google_maps_flutter: ^0.5.28+1` to `pubspec.yaml`
2. `myLocationEnable = true`
```dart
GoogleMap(
            myLocationEnabled: true,
            //Compass disabled due to this issue https://github.com/flutter/flutter/issues/37588
            //TODO: enable compass when issue is solved
            compassEnabled: false,
            mapToolbarEnabled: false,
            tiltGesturesEnabled: false,
            markers: _markers,
            polylines: _polylines,
            mapType: _mapType,
            initialCameraPosition: initialLocation,
            onMapCreated: onMapCreated,
            myLocationButtonEnabled: false,
            zoomControlsEnabled: false,
          )
```
3. add android location permissions on `AndroidManifest.xml`
```xml
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

**Expected results:** 
See current location dot on map. Tested on a Samsung real device, the same listed by `flutter doctor -v` command

**Actual results:** 
No current location dot is showed

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/flutter/flutter/files/4794940/logs.txt)

```
enricobenedos@MBP-di-Enrico wamii_app % flutter doctor -v 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-IT)
    • Flutter version 1.17.3 at /Users/enricobenedos/SDKs/flutter
    • Framework revision b041144f83 (13 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/enricobenedos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A520F • 52105e03ea34247d • android-arm64 • Android 8.0.0 (API 26)
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-06-18 11:04
Hi @enricobenedos 
could you provide complete minimal reproducible code sample?
may be related to https://github.com/flutter/flutter/issues/30171

**Comment by enricobenedos** [comment] 2020-06-18 11:08
Hi @VladyslavBondarenko,
at the moment the problem are two (related?):
* current position indicator is not showed
* Android does not ask any permissions when opening map page even if I added the permissions to manifest
I will provide to give you a complete sample, anyway I think that a clean created app with the provided code added on main page can simulate the problem.

**Comment by enricobenedos** [comment] 2020-06-18 18:43
Here the sample [repo](https://github.com/enricobenedos/flutter_google_maps_location_bug)

**Comment by VladyslavBondarenko** [comment] 2020-06-19 10:09
@enricobenedos what I see it looks exactly as https://github.com/flutter/flutter/issues/30171.
I thought you mean some your custom location indicator. MyLocation button isn't shown initially, but it's shown once you allow location permission (yes, android doesn't ask it by default and this is tracking in mentioned issue, you need to ask it programmatically, I tried simply with manual allowing in app settings and reloading app after this). Once I tap the myLocation button, map is moved to it and I can see current location indicator.
Can you confirm that it's the same what you're experiencing?

**Comment by enricobenedos** [comment] 2020-06-19 16:18
@VladyslavBondarenko your are right about allowing permissions manually from app settings. Now location button and actual position tag is showed as expected!

>you need to ask it programmatically

can you please explain me how to do it? 

I don't need to show myLocation button but only my current location in my project, anyway I think it is related with #30171. Hope that it solved as soon as possible.

**Comment by ziphawkteamusa** [comment] 2020-06-20 06:45
> ## Steps to Reproduce
> 1. add `google_maps_flutter: ^0.5.28+1` to `pubspec.yaml`
> 2. `myLocationEnable = true`
> 
> ```dart
> GoogleMap(
>             myLocationEnabled: true,
>             //Compass disabled due to this issue https://github.com/flutter/flutter/issues/37588
>             //TODO: enable compass when issue is solved
>             compassEnabled: false,
>             mapToolbarEnabled: false,
>             tiltGesturesEnabled: false,
>             markers: _markers,
>             polylines: _polylines,
>             mapType: _mapType,
>             initialCameraPosition: initialLocation,
>             onMapCreated: onMapCreated,
>             myLocationButtonEnabled: false,
>             zoomControlsEnabled: false,
>           )
> ```
> 
> 1. add android location permissions on `AndroidManifest.xml`
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> 
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
> ```
> 
> **Expected results:**
> See current location dot on map. Tested on a Samsung real device, the same listed by `flutter doctor -v` command
> 
> **Actual results:**
> No current location dot is showed
> 
> Logs
> [logs.txt](https://github.com/flutter/flutter/files/4794940/logs.txt)
> 
> ```
> enricobenedos@MBP-di-Enrico wamii_app % flutter doctor -v 
> [✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-IT)
>     • Flutter version 1.17.3 at /Users/enricobenedos/SDKs/flutter
>     • Framework revision b041144f83 (13 days ago), 2020-06-04 09:26:11 -0700
>     • Engine revision ee76268252
>     • Dart version 2.8.4
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/enricobenedos/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.46.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.11.0
> 
> [✓] Connected device (1 available)
>     • SM A520F • 52105e03ea34247d • android-arm64 • Android 8.0.0 (API 26)
> ```

have the exact same config. using location package and getting permissions at runtime as well as AndroidManifest. However, **unable to view the MyLocation button**. iOS version works error free.  Haven't tried the minimal version referred to above but a cursory look does suggest I have similar code.

**Comment by ziphawkteamusa** [comment] 2020-06-20 06:55
> I tried simply with manual allowing in app settings and reloading app after this
In my case, only this trick works, although my app ask for permission before loading map. Also, I have set android permissions and using the `location` package.

**Comment by VladyslavBondarenko** [comment] 2020-06-22 09:19
@enricobenedos 
set `myLocationButtonEnabled: false,` to not show the button. You can use https://pub.dev/packages/permission_handler for handling permissions

@ziphawkteamusa 
you haven't set it to `myLocationButtonEnabled: false,` right?

> not showing 'MyLocation` button normally

do you mean it's not shown with location permission enabled? is it shown after restarting app / hot restart?

**Comment by ziphawkteamusa** [comment] 2020-06-23 17:18
> @enricobenedos
> set `myLocationButtonEnabled: false,` to not show the button. You can use https://pub.dev/packages/permission_handler for handling permissions
> 
> @ziphawkteamusa
> you haven't set it to `myLocationButtonEnabled: false,` right?
> 
> > not showing 'MyLocation` button normally
> 
> do you mean it's not shown with location permission enabled? is it shown after restarting app / hot restart?

myLocation button is true. And I am seeing it when deployed on iPhone.

**Comment by TahaTesser** [comment] 2020-06-25 06:06
Hi @enricobenedos 
it's not for asking for location permission, hence not showing location button even when you set 
```
        myLocationEnabled: true,
        myLocationButtonEnabled: true,
```

Closing as duplicate of https://github.com/flutter/flutter/issues/30171

**Closed by TahaTesser** 2020-06-25 06:06 UTC
Labels: in triage

**Comment by Nazarii77** [comment] 2021-07-28 14:00
My case: location working correctly and moves to my coordinates, BUT: after first install I do not see the blue dot of gps location! On every other opening of the app it works perfectly. Please advice!
