### ISSUE TITLE
App semantic version name is ignored when built 

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#27589] opened 2019-02-06 11:50 UTC
If you try to build an app with semantic version name on your pubspec.yaml such as  `version: 1.0.0-beta.1` or `version: 1.0.0-alpha.1` won't be recognized and 1.0 will be set instead on both Android and iOS builds.

Some things I've already tried:

- Double quotes in the version
- Use em-hyphen before semantic name
- Use underscore before semantic name (this is invalid and not recognized as a version name)

However, it is possible to override it by using the `flutter build` command, i.e:
```
flutter build apk --build-name=1.0.0-beta.1 --build-number=1234
```
```
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.2 18C54, locale pt-PT)
    • Flutter version 1.2.0 at /Users/miguelruivo/DevTools/flutter
    • Framework revision 06b979c4d5 (12 days ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/miguelruivo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone XS Max             • DAC4E456-49FC-4D74-A35E-5113D9A69C09 • ios
      • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-07 13:04
Can you reproduce with a project created with a recent Flutter version?

https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated could be the cause.

**Comment by kangwang1988** [comment] 2019-02-07 14:45
Fail to reproduce this issue using latest master:
```
KyleWongdeMacBook-Pro:hello_flutter kylewong$ flutter build apk --build-name=1.0.0-beta.1 --build-number=1234
Running "flutter packages get" in hello_flutter...                  0.4s
Initializing gradle...                                              1.1s
Resolving dependencies...                                           1.9s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      24.4s
Built build/app/outputs/apk/release/app-release.apk (4.7MB).
KyleWongdeMacBook-Pro:hello_flutter kylewong$ ~/Library/Android/sdk/build-tools/28.0.3/aapt dump badging build/app/outputs/apk/release/app-release.apk
package: name='com.example.helloflutter' versionCode='1234' versionName='1.0.0-beta.1' platformBuildVersionName='1.0.0-beta.1' compileSdkVersion='28' compileSdkVersionCodename='9'
sdkVersion:'16'
targetSdkVersion:'28'
application-label:'hello_flutter'
application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
application: label='hello_flutter' icon='res/mipmap-mdpi-v4/ic_launcher.png'
launchable-activity: name='com.example.helloflutter.MainActivity'  label='' icon=''
feature-group: label=''
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
main
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160' '240' '320' '480' '640'
native-code: 'armeabi-v7a'
KyleWongdeMacBook-Pro:hello_flutter kylewong$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.1-pre.117, on Mac OS X 10.14.4 18E174f, locale en-CN)
    • Flutter version 1.2.1-pre.117 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 2aad59314f (14 hours ago), 2019-02-06 16:53:16 -0800
    • Engine revision 3c118b6c3b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 631c550ff9)
```

**Comment by kangwang1988** [comment] 2019-02-07 14:45
@miguelpruivo 
Feel free to comment if you can reproduce this issue using the latest master.

**Comment by miguelpruivo** [comment] 2019-02-07 15:13
@kangwang1988 by looking at your log you are building with
>flutter build apk --build-name=1.0.0-beta.1 --build-number=1234
As I've mentioned, it doesn't happen when you override it by building with that. However, if you just run `flutter build apk --release` normally and have specified in your pubspec.yaml a semantic version name it won't be set on the built ipa/apk.

**Comment by kangwang1988** [comment] 2019-02-07 16:09
@miguelpruivo 
Paste your pubspec.yaml here please.

**Comment by miguelpruivo** [comment] 2019-02-07 16:16
@kangwang1988 I believe what you are looking for are these lines eventually:

```
version: 1.0.0-beta.1
 
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
```

**Comment by zoechi** [comment] 2019-02-07 17:56
#16857 looks related

**Comment by zoechi** [comment] 2019-02-07 17:57
Have you tried with something like `version: 2.0.0-beta.1` to check if the `pubspec.yaml` version is used at all?

**Comment by miguelpruivo** [comment] 2019-02-07 18:08
@zoechi yes. No changes. It ignores any kind of semantic label unless explicitly in a build command argument.

**Comment by zoechi** [comment] 2019-02-08 10:10
> yes. No changes. It ignores any kind of semantic label

That sounds like it doesn't take the version from `pubspec.yam` at all.

**Comment by miguelpruivo** [comment] 2019-02-08 10:13
> > yes. No changes. It ignores any kind of semantic label
> 
> That sounds like it doesn't take the version from `pubspec.yam` at all.

Exactly. As long as it contains a semantic label. Otherwise it is fine.

**Comment by kangwang1988** [comment] 2019-02-10 12:51
@miguelpruivo 
Sorry for misunderstanding, I've reproduce the issue as you said and file a pr to resolve it.

**Comment by miguelpruivo** [comment] 2019-02-15 15:44
@kangwang1988 I'm on dev 1.2.1 which looks to have your PR merged for this issue but even though it's working fine on Android, iOS always displays 1.0.0.1 regardless of having a semantic version or not. This should be re-opened.

**Comment by bantunesptech** [comment] 2019-02-15 15:47
> @kangwang1988 I'm on dev 1.2.1 which looks to have your PR merged for this issue but even though it's working fine on Android, iOS always displays 1.0.0.1 regardless of having a semantic version or not. This should be re-opened.

Same problem for me, even when I use the command line (with arg --build-name ), the version for iOS is always 1.0.0.1.

I'm on dev 1.2.1.

**Comment by kangwang1988** [comment] 2019-02-16 05:13
@miguelpruivo  @bantunesptech 
It's as designed.
// See CFBundleShortVersionString at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

**Comment by zoechi** [comment] 2019-02-17 12:55
@kangwang1988 

From your link

> The release version number is a string composed of three period-separated integers. 

How can it show `1.0.0.1.` (4 integers instead of 3)?

**Comment by miguelpruivo** [comment] 2019-02-17 13:00
@kangwang1988 as I've already pointed, it's currently fine on Android with your PR.

However not only it doesn't show a semantic name (i.e., `1.0.0-beta.1` or whatsoever) nor it adds the build number.  As @zoechi mentioned, I believe that sticking with `1.0.0.1`, no matter what, is not the solution. 

Thank you.

**Comment by zoechi** [comment] 2019-02-17 13:10
> it doesn't show a semantic name (i.e., `1.0.0-beta.1`

So the expected result would be `1.0.0`, right?

**Comment by miguelpruivo** [comment] 2019-02-17 13:13
> > it doesn't show a semantic name (i.e., `1.0.0-beta.1`
> 
> So the expected result would be `1.0.0`, right?

`1.0.0-beta.1` or any other semantic name, actually, since `CFBundleShortString` on iOS is a string. That is already being done with Android.

**Comment by zoechi** [comment] 2019-02-17 13:21
I couldn't find a `CFBundleShortString`, only a `CFBundleShortVersionString` and that is defined as

> The release version number is a string composed of three period-separated integers. 

In the link provided by @kangwang1988 above (https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349)
Any other format than `x.x.x` (where `x` are integer values) violates this format.

**Comment by miguelpruivo** [comment] 2019-02-17 13:30
> I couldn't find a `CFBundleShortString`, only a `CFBundleShortVersionString` (...)

Edited my answer, that's what I'm talking about.

**Comment by kangwang1988** [comment] 2019-02-17 13:33
In iOS, build-number refers to 
CFBundleVersion
```
CFBundleVersion (String - iOS, macOS) specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle.

The build version number should be a string comprised of three non-negative, period-separated integers with the first integer being greater than zero—for example, 3.1.2. The string should only contain numeric (0-9) and period (.) characters. Leading zeros are truncated from each integer and will be ignored (that is, 1.02.3 is equivalent to 1.2.3). The meaning of each element is as follows:

The first number represents the most recent major release and is limited to a maximum length of four digits.
The second number represents the most recent significant revision and is limited to a maximum length of two digits.
The third number represents the most recent minor bug fix and is limited to a maximum length of two digits.
If the value of the third number is 0, you can omit it and the second period.

While developing a new version of your app, you can include a suffix after the number that is being updated; for example 3.1.3a1. The character in the suffix represents the stage of development for the new version. For example, you can represent development, alpha, beta, and final candidate, by d, a, b, and fc. The final number in the suffix is the build version, which cannot be 0 and cannot exceed 255. When you release the new version of your app, remove the suffix.
```

build-name refers to:
CFBundleShortVersionString
```
CFBundleShortVersionString (String - iOS, macOS) specifies the release version number of the bundle, which identifies a released iteration of the app.

The release version number is a string composed of three period-separated integers. The first integer represents major revision to the app, such as a revision that implements new features or major changes. The second integer denotes a revision that implements less prominent features. The third integer represents a maintenance release revision.

The value for this key differs from the value for CFBundleVersion, which identifies an iteration (released or unreleased) of the app.

This key can be localized by including it in your InfoPlist.strings files.
See also NSHumanReadableCopyright.
```

**Comment by zoechi** [comment] 2019-02-17 13:59
@kangwang1988 what about https://github.com/flutter/flutter/issues/27589#issuecomment-464453672 ?

**Comment by kangwang1988** [comment] 2019-02-17 14:53
Though so,
```
CFBundleShortVersionString

CFBundleShortVersionString (String - iOS, macOS) specifies the release version number of the bundle, which identifies a released iteration of the app.

The release version number is a string composed of three period-separated integers. The first integer represents major revision to the app, such as a revision that implements new features or major changes. The second integer denotes a revision that implements less prominent features. The third integer represents a maintenance release revision.

The value for this key differs from the value for CFBundleVersion, which identifies an iteration (released or unreleased) of the app.

This key can be localized by including it in your InfoPlist.strings files.

See also NSHumanReadableCopyright.
```

However, I noticed that 4 segments are available at AppStore:
![image](https://user-images.githubusercontent.com/817851/52914729-d9e51480-3306-11e9-9e7b-6df03f44f293.png)

**Comment by zoechi** [comment] 2019-02-17 15:49
@kangwang1988 

> However, I noticed that 4 segments are available at AppStore:

But creating `1.0.0.1` from `1.0.0-beta.1` doesn't seem to be a good idea to me.
There is no limitation what the string after `x.x.x` can be except that it can only be empty or start with `-` or `+`. 

For example what would `1.0.0+5b9c.13` or `1.0.0-5b9c.13` result in?

The docs say 3 integers separated by docs. I'd stick with that and drop the rest.

**Comment by kangwang1988** [comment] 2019-02-17 15:54
@zoechi 
Let's leave this issue open.
I will update the implementation if more deterministic is acquired.

**Comment by loolooii** [comment] 2019-06-05 11:36
Changing `1.0.0+1` to `1.0.1+1` doesn't seem to update the version either when I'm using `flutter build appbundle`. Overriding it with `--build-number=1.0.1` seems to make Play Store Console _not_ complain about having the same version, but `App info` on my device still shows `1.0.0`. Play Store Console shows `101` as `Version code` though. I think something is not right here.

**Comment by abilkhaiyr** [comment] 2019-06-05 18:56
Are there any updates? This bug is preventing me from updating the app on Play Store. For me it doesn't work even with `--build-name=2.0.0 --build-number=2019060600` and hardcoding the version in `build.gradle`. It builds with the old version. Maybe it was cached? But iOS works just fine

**Comment by loolooii** [comment] 2019-06-06 15:29
It used to work at least with overriding `build-name=xxx` (which is not ideal, but OK), but now when I use it together with `--flavor xxx`, it completely ignores `build-name` and always builds version `1`.

First of all why are flutter commands `build-name` and `build-number` instead of `versionName` and `versionNumber`.

Second, why is this still not working correctly? The build command should just take the `version` value from `pubspec.yaml` file and do it correctly, which it does not now.

I love Flutter, but there is just so many things going wrong every time I make some progress. I just can't update my app in Play Store.

@kangwang1988 @zoechi any updates on this?

**Comment by abilkhaiyr** [comment] 2019-06-07 04:35
@loolooii what version of flutter are you using and channel? I want to update wit `build-name` and `build-number` at least and release the update for my app

**Comment by loolooii** [comment] 2019-06-07 07:46
@abilkhaiyr I'm now just overriding `build-number` and it works, like this: `build-number=xxx`. I don't override build name. Previously I had `build-name=1.0.0-alpha` and that didn't seem to work. I'm confusing these two anyway. I'm just doing what works. I think this could be much easier if it just takes the version from `pubspec.yaml`.

**Comment by abilkhaiyr** [comment] 2019-06-07 11:15
@loolooii Thanks! But doesn't work for me. It just does not update the version number, whatever I try. Before that I had to just update the version in `pubspec.yaml`, ubt it just stopped working. Idk why

**Comment by abilkhaiyr** [comment] 2019-06-07 15:28
@loolooii I have deleted `build` folder inside of the project folder, ran `flutter clean` and it started working!

**Comment by loolooii** [comment] 2019-06-07 15:48
@abilkhaiyr you mean changing in `pubspec.yaml` started working or overriding?

**Comment by abilkhaiyr** [comment] 2019-06-07 17:21
@loolooii yeap. Now I just run `flutter build apk -t lib/main_prod.dart` and it picks up the version and build number from`pubspec.yaml`. Also, I am using `package_info 0.4.0+4` in project. In About Screen I am showing the version of the app with this `_appVersion = packageInfo.version;`

**Comment by loolooii** [comment] 2019-06-08 14:10
@abilkhaiyr Thanks! Going to try that.

**Comment by eseidelGoogle** [comment] 2020-01-10 17:07
Flutter provides some very basic integration between the `flutter` tools and the underlying iOS, Android build tools.  --build-name is one such integration which is wired up one way on Android and another way on iOS (due in part to the different constraints of the platforms) and presumably won't be wired up at all on Web. :)

I'm not sure there is a ton more we can do here.  We could remove the --build-number or --build-name features, but realistically probably best is to close this bug for now.  Patches are welcome to improve the behavior of Flutter's `flutter build` wrappers around Gradel or XCode, but it's unlikely our team will get to this specific bug any time soon.

Thank you very much for reaching out.  Please feel empowered to file a new bug if you're still having issues.  But my suspicion is that this is never an area Flutter will be perfect at due to the constraints of the underlying build systems Flutter sits on top of.

**Closed by eseidelGoogle** 2020-01-10 17:07 UTC
Labels: tool, waiting for PR to land (fixed)
