### ISSUE TITLE
Avoid calling Dart_New in engine - it's slow.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50997] opened 2020-02-18 23:22 UTC
Devicelab cull_opacity_perf__timeline_summary test failing with 30 second timeout exception.

```
2020-02-18T15:06:37.185691: stderr: [  +37 ms] VMServiceFlutterDriver: Waiting for service extension
2020-02-18T15:06:37.354258: stderr: [ +168 ms] VMServiceFlutterDriver: Connected to Flutter application.
2020-02-18T15:07:06.827425: stdout: [+29473 ms] 00:30 [32m+0[0m[31m -1[0m: cull_opacity_perf [1m[31m[E][0m[0m
2020-02-18T15:07:06.829451: stdout: [   +2 ms]   TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
```
[cull_opacity_perf__timeline_summary_bcacd06_2.log](https://github.com/flutter/flutter/files/4222206/cull_opacity_perf__timeline_summary_bcacd06_2.log)

Failing on engine roll https://github.com/flutter/flutter/commit/bcacd06f6958529d2de8ab0c0b571626877cd51d

**Comment by jmagman** [comment] 2020-02-19 00:56
@jason-simmons says:
> The cull_opacity test regressed starting at https://github.com/flutter/engine/commit/4941ff7bf608e0bca764e1edad769a3f8cca797f.  A call to driver.traceAction is timing out in the benchmark's flutter_driver script.
...
> The `getVMTimeline` call made by flutter_driver is now taking 28.5 seconds.  Before it was taking 18.7 seconds.

**Comment by dnfield** [comment] 2020-02-19 01:26
Right now working theory is that new dart API is logging more timeline events, making the timeline about 50% bigger, which is taking about 33% logger to download, and is just enough to make our timeout too short ot download the timeline.

The bigger problem is that this also results in a 20% drop in performance on the benchmark.  @jason-simmons @rmacnak-google and @bkonyi are going to sync up on that further.

**Comment by dnfield** [comment] 2020-02-19 01:28
We may want to consider reverting the upstream dart change that removed the API (dart-lang/sdk@082aece5f400c9405bcfd2cf6ec512d930433f30) and then revert flutter/engine@4941ff7

**Comment by jason-simmons** [comment] 2020-02-19 02:03
The additional timeline events are coming from the `Dart_NewStringFromCString` call added to provide the name of the default private constructor.

Tried patching `DartWrappable::CreateDartWrapper` to create the string once and use a persistent handle afterward.  With that change the timeline size and the `getVMTimeline` latency now match what they were before https://github.com/flutter/engine/commit/4941ff7.

However, the `average_frame_build_time_millis` metric for the `cull_opacity` benchmark is still around 20% higher for `Dart_New` compared to the old `Dart_AllocateWithNativeFields` API.

**Comment by dnfield** [comment] 2020-02-19 05:18
The cull opacity benchmark creates tons of objects every single frame.

It seems like there's just now a lot more overhead from calling constructors on those objects where we used to not.

It'd be interesting to see if we can figure out which constructors we're calling and if some of them are doing some unnecessary work - it'd also be nice if there was just some Dart API to avoid doing the double hop from native -> dart -> native -> dart to construct an object and initialize fields. It seems more likely to me that the double hop is what is hurting performance here rather than that some randomc onstructor is doing tons of work.

**Comment by dnfield** [comment] 2020-02-19 05:19
Sorry, not tons of objects, but it's basically just an animation that creates a bunch of objects with new parameters each frame.

**Comment by dnfield** [comment] 2020-02-19 17:31
I've opened a revert while we look into making this work.  I'm going to re-purpose this bug to track the actual cause of the regression.

**Comment by dnfield** [comment] 2020-02-19 20:56
https://github.com/flutter/flutter/pull/51071 landed the revert that's expected to take this off the TODAY list.  Once it passes I'll remove the label.

**Comment by dnfield** [comment] 2020-02-20 04:04
Doing a little digging on this.  The code impacted by the dart change falls on a very hot path we use to return arguments and instantiate objects.

**Comment by dnfield** [comment] 2020-02-20 06:32
https://github.com/flutter/engine/compare/master...dnfield:picture_dart has a rough approach to removing all of the `tonic::DartWrappable::CreateDartWrapper` calls that can possibly occur during the run of this benchmark.  It instead creates the objects in Dart code, passes the raw Dart_Handle over to native, and claims the Dart_Handle for the wrappable in the places we used to create the dart object.

Testing on a Pixel 4 results in nearly equal performance.  Will have to investigate further on a Moto G4 which is our reference device for this benchmark.

**Comment by chinmaygarde** [comment] 2020-02-20 06:32
The discussion today seemed to indicate that it was not the execution of the constructor that was particularly expensive but its lookup (and the creation of the intermediate strings which we can avoid using Jasons earlier patch so thats a solved problem).  Ryan's suggestion was to perform the allocation in Dart code to ameliorate some of these costs. This is a tractable problem as the engine knows all points at which it can create Dart objects from native code. In any case, we should circle back and consult with Siva when he gets back as of some the guarantees provided by Dart_New seemed important for efforts like NNDB.

**Comment by chinmaygarde** [comment] 2020-02-20 06:35
> creates the objects in Dart code

This seems preferable to playing fast and loose with object allocation. We should generalize to all objects created by the engine though.

**Comment by dnfield** [comment] 2020-02-20 06:36
Yes, I believe this approach can be generalized - I've covered some of the hotspots, but there are a few objects remaining. 

I'd also like validation from a VM developer that I'm not doing something just as bad or worse in my patch than what we're doing today :)

**Comment by chinmaygarde** [comment] 2020-02-20 06:40
> I'd also like validation from a VM developer

@rmacnak-google suggested this today so I think we are on the right track. @jason-simmons concern was there there are some points where we may need to construct lists of these objects but even that can be generalized away.

> but there are a few objects remaining.

We could just `[[deprecate]]` `Dart_New...` and `Dart_Allocate..` and/or remove their tonic wrappers. That way, we can pretty much ensure we cannot construct objects from native code accidentally.

**Comment by dnfield** [comment] 2020-02-20 06:44
I think for now just deleting DartWrappable::CreateDartWrapper should be enough.

**Comment by chinmaygarde** [comment] 2020-02-20 06:46
Just for this benchmark or generally?

**Comment by dnfield** [comment] 2020-02-20 06:56
Generally.  This benchmark was particularly affected, but we should avoid replacing the current fast path with a slow path - and there's no good way to refactor the current path AFAICT - unless there's some magic the VM can do to recognize this constructor is empty and the object has no fields to initialize and avoid doing any expensive lookups more than once.

**Comment by dnfield** [comment] 2020-02-20 06:57
Basically, we hit the path we're touching a _lot_ on every frame, to pretty much do anything.

**Comment by chinmaygarde** [comment] 2020-02-20 07:10
> Generally. This benchmark was particularly affected, but we should avoid replacing the current fast path with a slow path...

I meant go one step further and also make `Dart_New` unusable as there is no fast way of making it work. I could still bypass tonic and write code that uses `Dart_New` directly if you removed only CreateDartWrapper.

**Comment by jason-simmons** [comment] 2020-02-20 19:28
Tried running the cull_opacity benchmark with the `dnfield/picture_dart` branch on a Moto G4.  The `build_time_millis` metrics were roughly equal to the current master that uses `Dart_AllocateWithNativeFields`.

**Comment by dnfield** [comment] 2020-02-20 21:07
https://github.com/flutter/engine/pull/16713 should cover enough of the regression to be landable again.  I'll break out other parts of my larger patch into smaller PRs, since some stuff is requiring a bigger refactor (images and paragraph in particular).

**Comment by dnfield** [comment] 2020-02-20 22:37
Repurposing this bug again - VM may be able to optimize Dart_New, but it seems like we have another work around available that would be preferable.  Rather than opening a new bug, keep this one for the context.

**Comment by jmagman** [comment] 2020-02-20 23:31
cull_opacity_perf failing again on https://github.com/flutter/flutter/commit/0b5667ac12b073295403780bd3a38fd88db7a273

**Comment by bkonyi** [comment] 2020-02-20 23:34
> cull_opacity_perf failing again on [0b5667a](https://github.com/flutter/flutter/commit/0b5667ac12b073295403780bd3a38fd88db7a273)

That's a roll that only contains changes ~2 day old and doesn't contain the reverts.

**Comment by jmagman** [comment] 2020-02-20 23:36
Looks like this issue was repurposed away from the cull_opacity_perf__timeline_summary test failure.  I'll file a new issue.

**Closed** 2020-03-03 05:30 UTC
Labels: dependency: dart, engine
