### ISSUE TITLE
LinearGradient rendering is broken on Web

### ISSUE THREAD

**Issue by Danesz** [flutter/flutter#59461] opened 2020-06-15 10:21 UTC
Please check the [screenshots](https://imgur.com/a/CgYdkhG).

Linear gradient rendering is broken on Web:
```            
Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment(-0.4, -0.8),
                stops: [0.0, 0.5, 0.5, 1],
                colors: [
                  Colors.red.withAlpha(150),
                  Colors.red.withAlpha(150),
                  Colors.grey.withAlpha(150),
                  Colors.grey.withAlpha(150), 
                ],
                tileMode: TileMode.repeated,
              )
              ),
            ),
```

## Steps to Reproduce

1. Create a basic Flutter.
2. Creating a widget with linear gradient. E.g. like this:
```            
Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment(-0.4, -0.8),
                stops: [0.0, 0.5, 0.5, 1],
                colors: [
                  Colors.red.withAlpha(150),
                  Colors.red.withAlpha(150),
                  Colors.grey.withAlpha(150),
                  Colors.grey.withAlpha(150), 
                ],
                tileMode: TileMode.repeated,
              )
              ),
            ),
```

**Expected results:** 
The gradient should be rendered properly (check screenshot)

**Actual results:** 
The gradient is broken, only visible for a bit in one of the corners.

<details>
  <summary>Logs</summary>

### flutter run --verbose
```
flutter_app danesz$ /Users/danesz/apps/flutter/bin/flutter run -d chrome --verbose
[  +12 ms] executing: [/Users/danesz/apps/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e853155c7e36264514970dd6b67eb110fd394f78
[   +1 ms] executing: [/Users/danesz/apps/flutter/] git tag --contains HEAD
[ +194 ms] Exit code 0 from: git tag --contains HEAD
[   +4 ms] 1.19.0-2.0.pre
           1.19.0-3.0.pre
           1.19.0-4.0.pre
           1.19.0-4.1.pre
           1.19.0-5.0.pre
           1.20.0-0.0.pre
[  +12 ms] executing: [/Users/danesz/apps/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/danesz/apps/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +66 ms] executing: [/Users/danesz/apps/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G5033
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] executing: /Users/danesz/Library/Android/sdk/platform-tools/adb devices -l
[  +16 ms] executing: /usr/bin/xcode-select --print-path
[  +11 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Users/danesz/apps/xcode/Xcode11.3.1.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[  +98 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C505
[   +2 ms] executing: xcrun --find xcdevice
[   +8 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Users/danesz/apps/xcode/Xcode11.3.1.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +46 ms] List of devices attached

// ----  TONS OF DEVICES on the list

[  +15 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +213 ms] Generating /Users/danesz/work/sources/flutter/flutter_app/flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +124 ms] Launching lib/main.dart on Chrome in debug mode...
[  +66 ms] Updating assets
[  +87 ms] Syncing files to device Chrome...
[  +38 ms] Generating /Users/danesz/work/sources/flutter/flutter_app/flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +27 ms] <- reset
[   +8 ms] /Users/danesz/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --old_gen_heap_size=2000 /Users/danesz/apps/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/danesz/apps/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/73/sk6pc0lx2bl9zzvlq8htldr40000gn/T/flutter_tools.T2HAsD/flutter_tool.35PG9A/app.dill
--libraries-spec file:///Users/danesz/apps/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
/var/folders/73/sk6pc0lx2bl9zzvlq8htldr40000gn/T/flutter_tools.T2HAsD/flutter_tools.troZxy --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill.track.dill --platform
file:///Users/danesz/apps/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[ +261 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+17110 ms] Syncing files to device Chrome... (completed in 17,433ms, longer than expected)
[   +1 ms] Synced 22.6MB.
[        ] <- accept
[ +343 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56688/devtools/browser/2d2b9df9-53c5-488a-a24e-dae64c9b00e5
[+3414 ms] Debug service listening on ws://127.0.0.1:56720/60HWuJ_3s2A=

[ +524 ms] Debug service listening on ws://127.0.0.1:56720/60HWuJ_3s2A=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".


```

### flutter doctor
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.14.6 18G5033, locale en-BE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!

```

</details>

**Comment by iapicca** [comment] 2020-06-15 11:23
Hi @Danesz 
testing the code below with the latest master

<details>
  <summary>sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const _home = MyHomePage();
  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage();

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: Container(
            width: 100,
            height: 100,
            decoration: BoxDecoration(
                gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment(-0.4, -0.8),
              stops: [0.0, 0.5, 0.5, 1],
              colors: [
                Colors.red.withAlpha(150),
                Colors.red.withAlpha(150),
                Colors.grey.withAlpha(150),
                Colors.grey.withAlpha(150),
              ],
              tileMode: TileMode.repeated,
            )),
          ),
        ),
      );
}

```

</details>

<details>
  <summary>screenshots</summary>

![standard web](https://user-images.githubusercontent.com/45637986/84651442-a6be8f80-af12-11ea-9a53-c695e3af070f.png)

![image](https://user-images.githubusercontent.com/45637986/84651910-614e9200-af13-11ea-821e-aab54489ae56.png)

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.42 at /Users/nevercode/development/flutter_master
    • Framework revision 401690a64f (2 days ago), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>

I obtain your same results,
please not that the results with 
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`
are identical to to `flutter run -d chrome`

Thank you

**Comment by ferhatb** [comment] 2020-06-15 16:15
Duplicate of https://github.com/flutter/flutter/issues/45505

**Closed by ferhatb** 2020-06-15 16:15 UTC
Labels: a: images, engine, found in release: 1.20, has reproducible steps, platform-web, severe: rendering
