### ISSUE TITLE
Execution failed for task ':contacts_service:verifyReleaseResources'.

### ISSUE THREAD

**Issue by tbenjamin1** [flutter/flutter#159752] opened 2024-12-03 21:41 UTC
### Steps to reproduce

**The error occurs when attempting to build the Android release APK and states:**

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

Note: /Users/Benjamin/.pub-cache/hosted/pub.dev/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 5644 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':contacts_service:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/Benjamin/Downloads/koipay-app-new-designs/build/contacts_service/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
Running Gradle task 'assembleRelease'...                          106.7s
Gradle task assembleRelease failed with exit code 1

### Actual results

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

Note: /Users/Benjamin/.pub-cache/hosted/pub.dev/contacts_service-0.6.3/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 5644 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':contacts_service:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/Benjamin/Downloads/koipay-app-new-designs/build/contacts_service/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
Running Gradle task 'assembleRelease'...                          106.7s
Gradle task assembleRelease failed with exit code 1

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment] 2024-12-04 07:31
This is caused by the `contact_service` plugin and as such this should be reported on their repo. The plugin has not had any updates in 3 years so I would not recommend using it in your project. 

Closing from here as this is caused by a third-party plugin. 

Thank you

**Closed by danagbemava-nc** 2024-12-04 07:31 UTC
Labels: in triage
