### ISSUE TITLE
Android overscroll glow is in wrong place when using SliverAppBar

### ISSUE THREAD

**Issue by balazsgerlei** [flutter/flutter#12033] opened 2017-09-11 13:31 UTC
When using a SliverAppBar, FlexibleSpace and SliverList Widgets to achieve the collapsong Toolbar scrolling trick of the Material Design, the animation which signals that the beginning of the list (while scrolling upwards) is reached is displayed incorrectly on top of the AppBar/Toolbar. It should be displayed below it instead, as it is with the normal Android Views.

**Comment by balazsgerlei** [comment] 2017-09-11 15:20
This is the Material design animation at the top of the list (and correctly below the Toolbar) I am talking about:
![Example](https://i.stack.imgur.com/pFNeq.png)

**Comment by g-balas** [comment] 2019-03-26 14:39
Any news for this issue ? @Hixie @goderbauer

**Comment by creativecreatorormaybenot** [comment] 2019-07-21 21:49
When the app bar is floating, this does not make any sense from a Material Design stand point.  
The app bar is elevated and thus, there should be **no** way for the overscroll glow to appear above the app bar.

In general, the app bar scrolling behavior is far from the Material Design spec, i.e. snapping should scroll the content and not move independently from the content, see YouTube Android app.  
Additionally, I do not understand how partial elevation is supposed to make sense. When `forceElevated` is set to `false`, the app bar suddenly becomes elevated when content is scrolled below it and before that it is on the same z height.
@HansMuller 

Another issue related to overscroll glow and Material Design is #36349.

**Comment by Piinks** [comment] 2020-03-26 17:15
I have looked at this for a bit now and I think the best way to achieve this is by using a `NestedScrollView`. This will explicitly place the `SliverAppBar` on the outside of the primary scrollable, and the glow effect will happen below it as expected. Here is a code sample:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(title: Text('Demo'))
          ];
        },
        body: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(child: Container(color: Colors.red, height: 100),),
            SliverToBoxAdapter(child: Container(color: Colors.amber, height: 100),),
            // ... more slivers
          ],
        ),
      )
    );
  }
}
```

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/16964204/77675596-5dc9f100-6f4a-11ea-8e98-732b9c254d1f.gif)


There may be a way to manually compose another solution, but (after making a couple of attempts) it would probably be overly complex and unfriendly, especially since this works right out of the box. :)

I don't think there is a way to have this automagically work in a single `CustomScrollView`. 

A `SliverAppBar` is really just a `SliverPersistentHeader` under the hood, they can be placed anywhere in a `CustomScrollView`, at the top, the middle, the bottom, so the expected behavior is a bit unclear. For example, see https://github.com/flutter/flutter/issues/37529 as an example of `SliverAppBar`s being used in positions other than the first.

Furthermore, `SliverAppBar `shouldn't know about the `GlowingOverscrollIndicator` or vice versa. This is explained further in the style guide under [Avoid complecting (braiding multiple concepts together)](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-complecting-braiding-multiple-concepts-together). 

I am going to close this since there appears to be a working solution. Please don't hesitate to comment on the issue and let us know why if you feel that this should be looked at further. Thanks!

**Comment by nioncode** [comment] 2020-04-03 19:52
@Piinks Thanks for the example, unfortunately this does not work for floating `SliverAppBar`s, because they simply do not float anymore. Is there a workaround for showing the overscroll indicator at the correct position while using a floating AppBar?

**Comment by Piinks** [comment] 2020-04-03 21:00
> @Piinks Thanks for the example, unfortunately this does not work for floating `SliverAppBar`s, because they simply do not float anymore. Is there a workaround for showing the overscroll indicator at the correct position while using a floating AppBar?

There is actually an issue tracking this: https://github.com/flutter/flutter/issues/17518
I am hoping to have a solution soon. :)

**Comment by nioncode** [comment] 2020-04-03 22:17
@Piinks thanks for the fast response! Actually I'm not using a `NestedScrollView`, but a `CustomScrollView`, since `NestedScrollView` allows to scroll the last sliver up very far (maybe this has something to do with my use of `flexibleSpace`) instead of only allowing it to scroll until there is no more content.

Are you planning to solve the wrong glow offset also for `CustomScrollView`? Maybe there is a way to provide a custom offset that the `CustomPainter` can take into account? I briefly played around with this by copying `_GlowingOverscrollIndicatorPainter` and overriding its `paint` method with:
```dart
  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.translate(0, 120.0);
    _paintSide(canvas, size, leadingController, axisDirection,
        GrowthDirection.reverse);
    canvas.restore();
    _paintSide(canvas, size, trailingController, axisDirection,
        GrowthDirection.forward);
  }
```

Maybe the `ScrollBehavior` or `ScrollConfiguration` can be updated to allow adding a `paintOffset` or something like that? This would require to know the size of the offending widget though (which in my case is easy, since it is always the height of the `AppBar` + `SafeArea` padding, which is fix), but it is probably not so easy in every case.

**Comment by nioncode** [comment] 2020-04-04 09:28
I created a gist of my modifications if anyone is interested to pick this up as a workaround: https://gist.github.com/nioncode/ed5793d1f9801c92bb02b536b28ea759

The offset to use can be supplied from the parent widget, so it should be possible to adapt it for all kinds of views.

Result:
![Peek 2020-04-04 11-23](https://user-images.githubusercontent.com/3159451/78423520-24d6fe00-7667-11ea-9dcb-f4687a22e0ed.gif)

**Comment by Piinks** [comment] 2020-04-06 17:30
Ah! That sounds viable to me! I had not thought about developers supplying the offset manually, I was only considering it automatically working. Let me test this a bit and I may be able to implement it. :) Thanks for the feedback!

**Comment by Piinks** [comment] 2020-04-06 19:50
It looks like the gist you provided is achieving this affect by hard-coding knowledge of specific render objects into the layout methods of other render objects, like
https://gist.github.com/nioncode/ed5793d1f9801c92bb02b536b28ea759#file-customglowingoverscrollindicator-dart-L37 

This is what I described earlier as [Avoid complecting (braiding multiple concepts together)](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-complecting-braiding-multiple-concepts-together) from our style guide, so I don't think this approach will work as a potential fix in the Flutter framework.

I think there is a way this can work though. I am going to re-open this and continue to investigate a manual approach over the automagical I was trying to achieve earlier.

**Comment by Piinks** [comment] 2020-04-08 22:59
So I've taken a look at trying to manually offset the glow a couple of ways.

I considered an approach similar to the gist @nioncode provided above, which in practice would look something like this:
```dart
ScrollConfiguration(
  behavior: OffsetGlowBehavior( // extends ScrollBehavior, instantiates GlowingOverscrollIndicator
    leadingOffset: 50.0,
    trailingOffset: 10.0,
    color: Colors.blue, // would need to be included
    physics: // would need to be included
  ),
  child: CustomScrollView(
    physics: ... // would be overridden by the ScrollConfiguration
    slivers: ...
  ),
)
```

This has some drawbacks though.
- Creating a `ScrollBehavior` just to offset one potential widget (which may not be present) isn't a great approach, especially since the `ScrollBehavior` is responsible for implementing other factors like `ScrollPhysics`.
- The `ScrollPhysics` specified by the `ScrollBehavior` would override that of the `CustomScrollView`, which seems confusing to me.

---

I also considered making it possible to just provide the ability to offset the glow and let developers build it as part of their `CustomScrollView`. This would look something like this:
```dart
GlowingOverscrollIndicator(
  axisDirection: // required
  color: // required
  leadingOffset: 50.0,
  trailingOffset: 10.0,
  child: CustomScrollView(
    physics: ScrollPhysics(), // needed to override default Glow
    slivers: ...
  ),
)
```

This is also not without its drawbacks.
- Developers would have to provide the `AxisDirection` and `Color`
- The `ScrollPhysics` would need to be overridden __in the case where there would be a default glow__ so there would not be two `GlowingOverscrollIndicator`s in different positions.

---


In both cases, developers would have to calculate the offset themselves, which is not as simple as just the app bar height. 
  - For example, in the gist @nioncode used: 
```dart
MediaQuery.of(context).padding.top + AppBar().preferredSize.height
```

---

Ultimately, this works automatically if you use a `NestedScrollView`. It has been pointed out that there is a bug in `NestedScrollView` that needs to be fixed for floating `SliverAppBar`s, so I think focusing on fixing that is the answer here. That way it will work just as it should for everyone, without the extra leg work.

@nioncode I am glad you were able to create a custom `ScrollBehavior` that works to solve the problem for you. Perhaps you might consider publishing it as a packages on `pub.dev`?

I feel that this is pretty well covered now, so I am going to close this again.

**Closed by Piinks** 2020-04-08 22:59 UTC
Labels: customer: crowd, f: material design, f: scrolling, framework, would be a good package

**Comment by nioncode** [comment] 2020-04-09 21:43
@Piinks thanks for taking the time to look into this, although unfortunately the issue could not be solved in a clean enough way to make it into the framework.

Two follow-up questions:
1. `NestedScrollView` unfortunately behaves a bit different from `CustomScrollView` in case the content of the slivers is not bigger than the whole viewport's plus the expanded AppBar's height: when using `NestedScrollView`, the view can always be scrolled to completely hide the AppBar, although the body does not require scrolling. Is there a way to disable this, i.e. scroll the Widget of `persistedHeaderBuilder` only if the body does not fit into the viewport? I also asked this on SO: https://stackoverflow.com/questions/61126348/how-to-prevent-nestedscrollview-from-scrolling-if-body-is-small

If this could be solved, then I guess there would be no reason for me not to switch to `NestedScrollView` (except of the floating AppBar bug that you mention, which will hopefully be fixed in the future.

If this turns out to not be possible, then I have another question on how to maybe make providing a package to solve this for `CustomScrollView` easier:

2. For reducing the maintenance burden, would you accept a PR that adds `leadingPaintOffset` and `trailingPaintOffset` variables to `GlowingOverscrollIndicator` so that these values could at least be supplied from the outside instead of re-implementing the whole class outside of the framework? This would tremendously simplify providing a package for this. I'm also still investigating if it might be a viable approach to use a `NotificationListener`, which could change the paint offset by calling a method on `OverscrollIndicatorNotification` (which already has something similar with the `disallowGlow` method). What do you think about that?

**Comment by Piinks** [comment] 2020-04-09 22:02
> 1. `NestedScrollView` unfortunately behaves a bit different from `CustomScrollView` in case the content of the slivers is not bigger than the whole viewport's plus the expanded AppBar's height: when using `NestedScrollView`, the view can always be scrolled to completely hide the AppBar, although the body does not require scrolling. Is there a way to disable this, i.e. scroll the Widget of `persistedHeaderBuilder` only if the body does not fit into the viewport? I also asked this on SO: https://stackoverflow.com/questions/61126348/how-to-prevent-nestedscrollview-from-scrolling-if-body-is-small

If I am understanding correctly, I think you may be looking for the `SliverOverlapAbsorber/SliverOverlapInjector` widgets. The [api docs for `NestedScrollView`](https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html) have some sample code that illustrates how to use them. By using these widgets, the size of the *outer* sliver is inserted into the *inner* scrollable so the offset is correct for the inner body.

> (except of the floating AppBar bug that you mention, which will hopefully be fixed in the future.

I am actually working on this right now! 😄 

> 1. For reducing the maintenance burden, would you accept a PR that adds `leadingPaintOffset` and `trailingPaintOffset` variables to `GlowingOverscrollIndicator` so that these values could at least be supplied from the outside instead of re-implementing the whole class outside of the framework? This would tremendously simplify providing a package for this. I'm also still investigating if it might be a viable approach to use a `NotificationListener`, which could change the paint offset by calling a method on `OverscrollIndicatorNotification` (which already has something similar with the `disallowGlow` method). What do you think about that? Using a notification would also allow this to be used to offset `ScrollBar`s, which should also be painted at the wrong place as of now (this I have not checked though, but it just crossed my mind while grepping through the source code for usages of the different `ScrollNotification`s).

Contributions are always welcome! I think that sounds reasonable to me to just add offset parameters to the `GlowingOverscrollIndicator`. Feel free to ping me on such a PR if you want to submit it! :)
