### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by joukhar** [flutter/flutter#141792] opened 2024-01-18 19:00 UTC
### Steps to reproduce

when app is initilized but the window still black 
i was typing in vscode and then the app poped up so fast in debug mode
and then this error come out and the problem here is :
delete btn and copy past doesn't work, i didnt test all of buttons

### Expected results

keyboard btns should function well .

### Actual results

some keyboard btns are not working

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#4b44d(physicalKey: PhysicalKeyboardKey#a2fb3(usbHidUsage: "0x00070012", debugName: "Key O"), logicalKey: LogicalKeyboardKey#3a61f(keyId: "0x0000006f", keyLabel: "O", debugName: "Key O"), character: null, timeStamp: 3:24:26.073000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:471:16)
hardware_keyboard.dart:471
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
hardware_keyboard.dart:482
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:605:5)
hardware_keyboard.dart:605
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1053:37)
hardware_keyboard.dart:1053
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
platform_channel.dart:223
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
binding.dart:567
#8      _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
channel_buffers.dart:228
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu 22.04.3 LTS 6.5.0-14-generic, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/joukhar/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/joukhar/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/146/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /snap/android-studio/146
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.80.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-14-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by bleroux** [comment] 2024-01-18 19:12
Thanks for your feedback.
Closing this is issue as a duplicate of https://github.com/flutter/flutter/issues/125975.

**Closed by bleroux** 2024-01-18 19:12 UTC
