### ISSUE TITLE
My Game App Got Slow when i got 1.20 version

### ISSUE THREAD

**Issue by wesleyviana** [flutter/flutter#63151] opened 2020-08-07 00:58 UTC
## Details

**Target Platform:1.20
**Target OS version/browser:Android
**Devices:Android

## Logs
Hey guys, whats up!
I am coding a game using flame engine, 
so in this code we have Timer, Durations a lot. 
when i got 1.20 version the game came very slow..
so a fix downgrade for the 1.17 version and works fine. 

thanks for all support.

```
```

```
```

**Comment by darshankawar** [comment] 2020-08-07 13:01
Hi @wesleyviana,
Are you on 1.20 of master or stable ?
Can you share exactly how the app has slowed down, like, a video / gif comparing both versions?
Thanks.

**Comment by wesleyviana** [comment] 2020-08-12 13:07
> Hi @wesleyviana,
> Are you on 1.20 of master or stable ?
> Can you share exactly how the app has slowed down, like, a video / gif comparing both versions?
> Thanks.

Hello, 

i am using a 1.20.1  stable channel. 
what a notice are, everthing i use duration , has something legs, a minimal slow motion. 
exemple:                 
      _pageController.animateToPage(_currentPage - 1, duration: Duration(milliseconds: 1000), curve: Curves.easeOutQuint);

when we using pageview.. 
when i using  a lib confetti, too. https://pub.dev/packages/confetti

**Comment by wesleyviana** [comment] 2020-08-12 13:15
I think is something wrongs in my code, maybe garbage objects, i am doing  some tests..

**Comment by wesleyviana** [comment] 2020-08-12 18:18
Some updates,    i discovery where are a slow issues problems. 
I am using a image 600 kb,  1536 w  x 5200 h.
in 1.17 version, in my J5  samsung phone,  runs ok. 
but in a 1.20, stable or master  cause somes legs ..

**Comment by erickzanardo** [comment] 2020-08-12 18:23
I wonder if something regarding image manipulation has changed between those version on Android.

@wesleyviana can you also test if this happens on other platforms?

**Comment by wesleyviana** [comment] 2020-08-12 18:29
> I wonder if something regarding image manipulation has changed between those version on Android.
> 
> @wesleyviana can you also test if this happens on other platforms?

hey @erickzanardo 
i will try run in macOs, thanks  for all advices.

**Comment by wesleyviana** [comment] 2020-08-14 19:03
with help to flame comunity, we discovery running in release mode, the legs and slow  dont happens . 
only debug mode have that problem.

**Comment by erickzanardo** [comment] 2020-08-14 20:15
> with help to flame comunity, we discovery running in release mode, the legs and slow dont happens .
> only debug mode have that problem.

If the issue was indeed solved by that @wesleyviana maybe you could close the issue? :)

**Comment by darshankawar** [comment] 2020-08-17 05:32
@wesleyviana,
Per your comment, do you feel the issue is resolved or related to Flutter version ?
Thanks.

**Comment by wesleyviana** [comment] 2020-08-19 20:37
is totally related to flutter version 1.20. 
only  release mode reduce the slow issues.

**Comment by erickzanardo** [comment] 2020-08-19 21:35
In the past week we have had a couple of people saying that they are experiencing perfomance problems on the Flame discord server after upgrading to 1.20+.

After some time digging on this, the community discovered the exact commit that caused the perfomance regression: https://github.com/flutter/engine/commit/f46dde1f06e11b18fb07f51cfc93286bdda3eaa6 (thanks to @christopherfujino and @Jiack214 for tracking this!!!)

It also seems that this issue is related to what @wesleyviana is experiencing: https://github.com/flutter/flutter/issues/63876

We have also opened an issue on Flame repository to track this, so let me reference it here https://github.com/flame-engine/flame/issues/448

I am trying to discover what feature/condition on Flame that causes this perfomance issue, as it is not every time that this issue arise, if I find anything, I will report here.

**Comment by christopherfujino** [comment] 2020-08-19 23:26
Thanks for filing this @wesleyviana. I am going to close this as a duplicate of https://github.com/flutter/flutter/issues/63876. Please follow that issue for discussion and updates.

**Closed by christopherfujino** 2020-08-19 23:26 UTC
Labels: in triage
