### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by oussaid1** [flutter/flutter#75087] opened 2021-01-31 11:41 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.25.0-8.3.pre at
      /home/oussaid/snap/flutter/common/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/oussaid/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 5d36f2e7f5387b6c751449258ade8e4e6edf99be
### Plugins
integration_test

**Comment by iapicca** [comment] 2021-01-31 13:47
@oussaid1 
can you provide the logs for this crash

possible duplicate of https://github.com/flutter/flutter/issues/72522

**Comment by TahaTesser** [comment] 2021-02-01 09:16
Hi @oussaid1 
This being track in Flutter snap repository https://github.com/canonical/flutter-snap/issues/23
duplicate of the following issues
https://github.com/flutter/flutter/issues/73976
https://github.com/flutter/flutter/issues/75073
https://github.com/flutter/flutter/issues/74985
Please follow up on the tracking issue 
Thank you

**Closed by TahaTesser** 2021-02-01 09:16 UTC

**Comment by iapicca** [comment] 2021-02-06 18:33
this is a snap installation issue, follow up [here](https://github.com/canonical/flutter-snap/issues/23)
