### ISSUE TITLE
fontFamily in ThemeData doesn't work anymore in Flutter 1.12

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#46863] opened 2019-12-12 09:49 UTC
```dart
MaterialApp(
  ...
  theme: ThemeData(
    fontFamily: 'my-font-family',
  )
  ...
```

This used to work before, after upgrading to Flutter 1.12 my custom font is not used anymore. I have to specify `fontFamily` in `TextStyle` for each of my widgets instead.

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/tudor/dev/flutter
    • Framework revision 27321ebbad (32 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro • 332C8E72-5F12-4719-B917-2A2687F7FB42 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2019-12-12 13:29
Hi @tudor07 
I'm not calling it a solution,
but a possible workaroud is using the new package [google_fonts](https://pub.dev/packages/google_fonts)
thank you

**Comment by tudor07** [comment] 2019-12-12 14:42
@iapicca It doesn't matter where the font comes from, also I use a paid font which is not available on Google Fonts.

**Comment by tudor07** [comment] 2019-12-12 14:46
Maybe this introduces issue: https://github.com/flutter/flutter/pull/42366

**Comment by iapicca** [comment] 2019-12-12 15:07
Hi again @tudor07 
could you please run
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by tudor07** [comment] 2019-12-12 15:12
@iapicca Already tried that, did not work.
Also tried removing ~/.pub-cache, removing pods... clean from Xcode/Android Studio

**Comment by HansMuller** [comment] 2019-12-12 15:16
CC @darrenaustin

**Comment by darrenaustin** [comment] 2019-12-12 19:50
It's possible my change (https://github.com/flutter/flutter/pull/42366) broke this (my apologies if so). However, I can't reproduce the issue as you describe it. Here is a modified demo app that sets a default font family as well as a special case title style. To run it, you will need to have to have Mansalva (https://fonts.google.com/specimen/Mansalva) and Big Shoulders Display (https://fonts.google.com/specimen/Big+Shoulders+Display) setup as assets for the app (or replace the references with fonts that you do have).

```dart
import 'package:flutter/material.dart';

void main() => runApp(FontFamilyTest());

class FontFamilyTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        fontFamily: 'Mansalva',
        textTheme: TextTheme(
          title: TextStyle(fontFamily: 'Big Shoulders Display'),
        ),
      ),
      home: FontFamilyTestPage(title: 'Flutter Demo Home Page'),
    );
  }
}

class FontFamilyTestPage extends StatefulWidget {
  FontFamilyTestPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _FontFamilyTestPageState createState() => _FontFamilyTestPageState();
}

class _FontFamilyTestPageState extends State<FontFamilyTestPage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
              style: Theme.of(context).textTheme.title,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            RaisedButton(
              child: const Text('Button'),
              onPressed: () {},
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

Which yields:

![FontFamily](https://user-images.githubusercontent.com/19588/70743677-20ac5c80-1cd5-11ea-9c5c-c52b13872621.png)

Which shows Mansalva being used for everything except the 'You have pushed...' text which uses the title style which is using Big Shoulders Display.

Can you try this with your fonts and see if you see the same problem? Or can you give us a test case that we can use to repro it?  Thanks.

**Comment by avioli** [comment] 2019-12-13 04:25
I'm experiencing an app crash when a custom font is used.

```
2019-12-13 15:01:24.329096+1100 Runner[40874:1750268] [VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
2019-12-13 15:01:24.329305+1100 Runner[40874:1750268] [VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0
```

Ran `flutter clean` and `flutter pub cache repair`. No change, although the repair screwed a couple of firebase plugins that I had to fix, but unrelated.

Will test with fresh project as per @darrenaustin suggestion above and report back.

**Comment by tudor07** [comment] 2019-12-13 07:44
@darrenaustin No need to apologize.
Your example works, and I also found a solution for my problem.
So I have a custom theme where I change multiple fields in the `TextTheme`:

```
ThemeData(
  canvasColor: Colors.white,
  scaffoldBackgroundColor: Colors.white,
  fontFamily: 'my-custom-font',
  textTheme: TextTheme(
    display1: const TextStyle(
      fontSize: 17,
    ),
    display2: const TextStyle(
      fontSize: 22,
    ),
    display3: const TextStyle(
      fontSize: 27,
    ),
    body1: Theme.of(context).textTheme.body1.merge(
          const TextStyle(
            color: kMyColor,
          ),
        ),
    body2: const TextStyle(
      fontSize: 17,
    ),
    button: const TextStyle(
      fontSize: 17,
      fontWeight: FontWeight.w600,
    ),
    overline: const TextStyle(
      fontSize: 10,
    ),
  ),
)
```

Before upgrading, this worked fine. After upgrading I need to add the `fontFamily` property to `body1` also, like this:

```
    ...
    body1: Theme.of(context).textTheme.body1.merge(
          const TextStyle(
            color: kMyColor,
            fontFamily: 'my-custom-font',
          ),
        ),
    ...
```

And now it works everywhere in the app like before. Not sure if this change was intentional, for me it seems like a resonable solution, so if this was intentional you can close this issue. Would be nice to have this written somewhere in the documentation that `body1`'s `fontFamily` overrited `ThemeData`'s `fontFamily` IMHO.

**Comment by darrenaustin** [comment] 2019-12-14 00:40
Ah I see the problem then. It is a little subtle, but the issue is that for `body1` in the example above it uses:

```dart
Theme.of(context).textTheme.body1.merge(...
```

In this case the `context` that is being referenced doesn't see the MaterialApp that is being defined here. Therefore `Theme.of(context)` will return the default Material theme data. In the default Material theme, all text styles have their family set to 'Roboto'. When you then take that and merge with your changes (the color set to `kMyColor`), the family of 'Roboto' will be set on the resulting style. Because this has been set it will not be overridden by the `fontFamily` in the `ThemeData` constructor. The other styles pick up the 'fontFamily' value because they didn't have one set on them.

The reason this worked before is the `fontFamily` parameter to the `ThemeData` constructor used to always override any font family settings on a given text style. This was the bug I was trying to fix with my change (see #34915). The `fontFamilly` should only be used as a default when none has been set on the style.

So the change was intentional, but breaking your use case was not. If I had realized this would be breaking, I definitely would have gone through our breaking change process. At this point as you have a reasonable solution to the problem, I am going to go ahead and close this out. Thanks for the report and following up with us.

**Closed by darrenaustin** 2019-12-14 00:40 UTC
Labels: a: assets, a: typography, f: material design, framework, severe: regression

**Comment by yelkamel** [comment] 2020-02-29 14:09
Hello so we couldn't use Theme.of(context).fontFamily directly ? 
I prefer to set the size directly and not using textTheme...

**Comment by iapicca** [comment] 2020-03-02 15:03
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by tudor07** [comment] 2020-03-03 07:16
@yelkamel What's stopping you from settings size directly?

**Comment by stevenyix** [comment] 2020-03-04 06:33
the output from flutter doctor -v below.

when i attempt to create a ThemeData instance, the fontFamily property is not available and I get a compile error.  screenshot from IntelliJ:

![image](https://user-images.githubusercontent.com/7738085/75851634-07c8ba00-5d9f-11ea-871b-64e562a93395.png)


[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/steve/Documents/Dev/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • C56A840C-CCD4-4234-84C3-6EB9752C6597 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by tudor07** [comment] 2020-03-04 07:20
@stevenyix Looks like `fontFamily` is not defined in `copyWith` method. Why do you use `copyWith`? Just create your theme:

```
MaterialApp(
    theme: ThemeData(
        ...
        fontFamily: 'MyFontFamily'
        ...
    )
)
```

**Comment by stevenyix** [comment] 2020-03-06 16:52
@tudor07 i'll try that.  my understanding of using copyWith was to use it so i could inherit and overwrite existing ThemeData properties without having to define every single one of them again.

**Comment by devibrahimkarahan** [comment] 2020-04-14 22:15
Any update on copyWith method?

**Comment by jorwan** [comment] 2020-08-03 17:22
**fontFamily** from **ThemeData** _properties_ is not working for me either.

Any update ?

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)  
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

**Comment by parthi22** [comment] 2020-08-13 17:42
Not sure, if this is the right approach, but I'm using it as below in my theme file.
![image](https://user-images.githubusercontent.com/959571/90168185-5cdf1200-ddba-11ea-8d01-12b6656dbbf9.png)

**Comment by dcchristopher** [comment] 2020-09-04 17:34
It doesn't matter what I do (I even tried @parthi22 's suggestion), the font family simply does not apply to Text widgets throughout the app. I even filled in every text style property possible in the theme (including the Cupertino overrides) and it still didn't make a difference. In fact, I have a feeling my theme doesn't make much of a difference altogether. I suspect BuildContext issues but I did make sure that I'm not creating new contexts deeper in the app. I'm sure I'll figure this out one day. For now, the only thing that works is to set the fontFamily on individual Text widgets' textStyle properties.

**Comment by ShehabSN** [comment] 2020-10-06 20:26
This is still an issue in Flutter v1.22.0, fontFamily in ThemeData does not work globally

**Comment by pratikbutani** [comment] 2020-11-09 06:11
Any clue to set Font globally?

**Comment by pratikbutani** [comment] 2020-11-09 07:13
Tried on **Flutter (Channel stable, 1.22.3,**

I have just done some changes as follows:

1. Paste some fonts file in your **assets** folder for example **Courgette-Regular.ttf**:

2. Edit your **pubspec.yaml:** as below:

         # example:
         fonts:
           - family: myFontFamily
             fonts:
               - asset: fonts/Courgette-Regular.ttf
 
3. set **fontFamily** in **ThemeData** In your **MaterialApp** tag of `main.dart`:

       return MaterialApp(
         title: 'Flutter Demo',
         debugShowCheckedModeBanner: false,
         theme: ThemeData(
           primarySwatch: Colors.blue,
           visualDensity: VisualDensity.adaptivePlatformDensity,
           fontFamily: 'myFontFamily', // JUST ADD FONT FAMILY HERE...
         ),
         home: MyHomePage(title: 'Flutter Demo Home Page'),
       );

Thank you
