### ISSUE TITLE
Semantics focus moves to first element after the focused widget is updated

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#66237] opened 2020-09-21 04:54 UTC
b/169000364

Repro case:

```dart
class TapBox extends StatelessWidget {
  TapBox({Key key}) : super(key: key);
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          // action button
          IconButton(icon: const BackButtonIcon(), onPressed: () {}),
        ],
      ),
      body: TapboxA(),
    );
  }
}
 
class TapboxA extends StatefulWidget {
  TapboxA({Key key}) : super(key: key);
 
  @override
  _TapboxAState createState() => _TapboxAState();
}
 
class _TapboxAState extends State<TapboxA> {
  bool _active = false;
 
  final pageViewKey = GlobalKey();
  final pageController = PageController(initialPage: 0, viewportFraction: 0.15);
 
  void _handleTap() {
    setState(() {
      _active = !_active;
    });
  }
 
  @override
  Widget build(BuildContext context) {
    return _active
        ? _buildPageView(
      context,
    )
        : Semantics(
      label: 'PageView widget',
      onTap: _handleTap,
      excludeSemantics: true,
      child: _buildPageView(
        context,
      ),
    );
  }
 
  Widget _buildPageView(BuildContext context) {
    return PageView.builder(
      key: pageViewKey,
      controller: pageController,
      allowImplicitScrolling: true,
      itemCount: 20,
      itemBuilder: (_, index) => _buildItem(
        context,
        index: index,
      ),
    );
  }
 
  Widget _buildItem(
      BuildContext context, {
        int index,
      }) {
    return Semantics(
      label: 'label',
      button: true,
      excludeSemantics: true,
      onTap: () async {
        await _animateToPage(index);
        _handleTap();
      },
      child: Center(child: const Text('text')),
    );
  }
 
  Future<void> _animateToPage(int page) {
    return pageController.animateToPage(
      page,
      duration: const Duration(milliseconds: 400),
      curve: Curves.easeInOut,
    );
  }
}
```

Steps:

- Enter TapBox page, and enable accessibility mode.
- Moving the accessibility focus to the page view by swiping right.
- Double tap, the accessibility focus will automatically focus on the action button on app bar.
    - (Expected: Focus on the first element in the page view)
- Moving the accessibility focus to the first element in the page view by swiping right.
- Double tap, the accessibility focus will automatically focus on the action button on app bar again.
    - (Expected: Focus on the page view)

**Comment by TahaTesser** [comment] 2020-09-21 10:58
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TapboxA(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class TapBox extends StatelessWidget {
  TapBox({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          // action button
          IconButton(icon: const BackButtonIcon(), onPressed: () {}),
        ],
      ),
      body: TapboxA(),
    );
  }
}

class TapboxA extends StatefulWidget {
  TapboxA({Key key}) : super(key: key);

  @override
  _TapboxAState createState() => _TapboxAState();
}

class _TapboxAState extends State<TapboxA> {
  bool _active = false;

  final pageViewKey = GlobalKey();
  final pageController = PageController(initialPage: 0, viewportFraction: 0.15);

  void _handleTap() {
    setState(() {
      _active = !_active;
    });
  }

  @override
  Widget build(BuildContext context) {
    return _active
        ? _buildPageView(
            context,
          )
        : Semantics(
            label: 'PageView widget',
            onTap: _handleTap,
            excludeSemantics: true,
            child: _buildPageView(
              context,
            ),
          );
  }

  Widget _buildPageView(BuildContext context) {
    return PageView.builder(
      key: pageViewKey,
      controller: pageController,
      allowImplicitScrolling: true,
      itemCount: 20,
      itemBuilder: (_, index) => _buildItem(
        context,
        index: index,
      ),
    );
  }

  Widget _buildItem(
    BuildContext context, {
    int index,
  }) {
    return Semantics(
      label: 'label',
      button: true,
      excludeSemantics: true,
      onTap: () async {
        await _animateToPage(index);
        _handleTap();
      },
      child: Center(child: const Text('text')),
    );
  }

  Future<void> _animateToPage(int page) {
    return pageController.animateToPage(
      page,
      duration: const Duration(milliseconds: 400),
      curve: Curves.easeInOut,
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.269 at /Users/tahatesser/Code/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X
      10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by chunhtai** [comment] 2020-09-21 17:44
Replied to the internal bug, waiting for their response.

**Comment by Hixie** [comment] 2020-09-22 22:21
Sounds like this is working as intended? Should we close this? It wasn't obvious from the internal bug what the expected change in behaviour was.

**Comment by chunhtai** [comment] 2020-09-22 22:33
close a WAI, the fix will be on the customer side

**Closed by chunhtai** 2020-09-22 22:33 UTC
Labels: P2, a: accessibility, customer: money (g3), found in release: 1.22, framework, has reproducible steps, platform-ios
