### ISSUE TITLE
[Mobile] Hide all characters in a TextField, when obscureText is true

### ISSUE THREAD

**Issue by hongquanvn1998** [flutter/flutter#95416] opened 2021-12-16 17:44 UTC
I need a config like boolean field can make hide all characters when i type on keyboard into textfield. It's very nice

**Comment by darshankawar** [comment] 2021-12-17 08:11
@hongquanvn1998 
Currently, if we set `obscureText: true` and type in textfield, it first shows the char and then obscures it. Are you saying to fully obscure the text while typing ?

**Comment by hongquanvn1998** [comment] 2021-12-17 10:04
yes. it my issue. I want to fully obscure the text while typing.

**Comment by Chinmay-KB** [comment] 2021-12-17 11:38
Maybe instead of having a boolean, it can have an enum, ObscureType.NONE, ObscureType.FULL, ObscureType.ON_TYPE ?

**Comment by darshankawar** [comment] 2021-12-17 13:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80109. Please follow-up in it for further updates.

**Closed by darshankawar** 2021-12-17 13:25 UTC
Labels: in triage
