### ISSUE TITLE
Text selection doesn't show selected text

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10910] opened 2017-06-22 19:30 UTC
On Android, open the Flutter Gallery app and navigate to "Text fields". Enter text in the Phone Number field. Select the text. Change the selection with the blue bubbles. The selected text no longer appears as selected.

![image](https://user-images.githubusercontent.com/1227763/27452143-7416d7ee-5746-11e7-99ae-43fbfdbb6c72.png)

**Comment by jason-simmons** [comment] 2017-06-22 21:29
This is coming from the _UsNumberTextInputFormatter in Gallery, which applies the parentheses/dashes/etc. to the phone number on each text update.

_UsNumberTextInputFormatter always collapses the selection range to a single text position, causing the selection highlight to disappear.

Some options:
  * Change _UsNumberTextInputFormatter to adjust both ends of the selection range instead of collapsing
  * Update the position of the selection handles (or hide them) if a formatter alters the selection

**Comment by TahaTesser** [comment] 2020-07-21 14:47
This issue isn't reproducible on Samsung device 

![flutter_02](https://user-images.githubusercontent.com/48603081/88069463-1e757f00-cb8f-11ea-9239-3f18ac632b37.png)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (7 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details> 


Closing, as the issue is old and there is no device specific info. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-21 14:47 UTC
Labels: P4, a: text input, framework
