### ISSUE TITLE
Flutter web DropdownButton hover stays at current version

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#96226] opened 2022-01-06 15:40 UTC
This issue is about the DropdownButton.
https://api.flutter.dev/flutter/material/DropdownButton-class.html
A code example can be found also at the linked website.

The problem is that after selecting something the hover stays. The gray hover overlay is still there. It should dissapear.
The problem is on the current master commit. Fortunately it is still working on the stable channel.

Here is my doctor -v:
[√] Flutter (Channel master, 2.9.0-1.0.pre.256, on Microsoft Windows [Version 10.0.19043.1415], locale de-DE)
    • Flutter version 2.9.0-1.0.pre.256 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45726a8458 (15 hours ago), 2022-01-05 20:00:17 -0500
    • Engine revision 36eafae59d
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by TahaTesser** [comment] 2022-01-06 15:51
duplicate of https://github.com/flutter/flutter/issues/94605

**Closed by TahaTesser** 2022-01-06 15:51 UTC
