### ISSUE TITLE
[web]Flutter For Web Https  Uncaught Instance of 'minified:p'

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#35717] opened 2019-07-08 03:35 UTC
![image](https://user-images.githubusercontent.com/3982317/60781261-3b9e0200-a174-11e9-8c85-ba418a9daeee.png)
When i run  flutter for web in chrome, this error is was always in the console log.

I guess this error is because https？

**Comment by icatalud** [comment] 2019-07-11 16:41
I have the same the error. Working on Windows 10 webdev 2.2.0.

I'm not sure how to reproduce the error though, since at the beginning the starting flutter_web project was working fine. If I delete all the complexity and build just a simple Text widget, the problem still occurs.

#34235

**Comment by kevmoo** [comment] 2019-07-11 18:56
Duplicate of https://github.com/flutter/flutter/issues/34235

**Closed by kevmoo** 2019-07-11 18:56 UTC
Labels: ☸ platform-web

**Comment by wedcel** [comment] 2019-07-15 08:11
This problem is still

**Comment by icatalud** [comment] 2019-07-15 16:43
Yes, #34235 is also closed, I do not know why they leave them closed with no explanation.
