### ISSUE TITLE
Exception thrown when binaryMessenger.setMessageHandler called within EventChannel's receiveBroadcastStream method.

### ISSUE THREAD

**Issue by vikramkapoor** [flutter/flutter#40032] opened 2019-09-07 15:31 UTC
@dnfield 

**Steps to reproduce**
I got the following exception on iOS while on master and dev flutter channels after runApp() had already been called. I added WidgetFlutterBinding.ensureInitialized() at the start of Main() as well as in the background Isolate entry function . This issue is not reproducible on Android on master and dev flutter channels or on stable channel on iOS. I am working on minimal repro code.

**Logs**
```
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> 
package:flutter/…/services/binary_messenger.dart:73
#1      defaultBinaryMessenger 
package:flutter/…/services/binary_messenger.dart:86
#2      EventChannel.binaryMessenger 
package:flutter/…/services/platform_channel.dart:484
#3      EventChannel.receiveBroadcastStream.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:504
<asynchronous suspension>
#4      _runGuarded  (dart:async/stream_controller.dart:805:24)
#5      _BroadcastStreamController._subscribe  (dart:async/broadcast_stream_controller.dart:213:7)
#6      _ControllerStream._createSubscription  (dart:async/stream_controller.dart:818:19)
#7      _StreamImpl.listen  (dart:async/stream_impl.dart:472:9)
#8      FlutterIsolate._isolateInitialize 
package:flutter_isolate/flutter_isolate.dart:104
#9      _flutterIsolateEntryPoint 
package:flutter_isolate/flutter_isolate.dart:132
#10     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)
#11     _rootRun  (dart:async/zone.dart:1124:13)
#12     _CustomZone.run  (dart:async/zone.dart:1021:19)
#13     _runZoned  (dart:async/zone.dart:1516:10)
#14     runZoned  (dart:async/zone.dart:1500:12)
#15     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)
#16     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
#17     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
``

**Comment by vikramkapoor** [comment] 2019-09-07 15:49
@dnfield 

**Steps to reproduce**
I got the following exception on iOS while on master and dev flutter channels after runApp() had already been called. I added WidgetFlutterBinding.ensureInitialized() at the start of Main() as well as in the background Isolate entry function . This issue is not reproducible on Android on master and dev flutter channels or on stable channel on iOS.


**Logs**
```
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> 
package:flutter/…/services/binary_messenger.dart:73
#1      defaultBinaryMessenger 
package:flutter/…/services/binary_messenger.dart:86
#2      EventChannel.binaryMessenger 
package:flutter/…/services/platform_channel.dart:484
#3      EventChannel.receiveBroadcastStream.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:504
<asynchronous suspension>
#4      _runGuarded  (dart:async/stream_controller.dart:805:24)
#5      _BroadcastStreamController._subscribe  (dart:async/broadcast_stream_controller.dart:213:7)
#6      _ControllerStream._createSubscription  (dart:async/stream_controller.dart:818:19)
#7      _StreamImpl.listen  (dart:async/stream_impl.dart:472:9)
#8      FlutterIsolate._isolateInitialize 
package:flutter_isolate/flutter_isolate.dart:104
#9      _flutterIsolateEntryPoint 
package:flutter_isolate/flutter_isolate.dart:132
#10     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)
#11     _rootRun  (dart:async/zone.dart:1124:13)
#12     _CustomZone.run  (dart:async/zone.dart:1021:19)
#13     _runZoned  (dart:async/zone.dart:1516:10)
#14     runZoned  (dart:async/zone.dart:1500:12)
#15     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)
#16     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
#17     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
``

**Comment by dnfield** [comment] 2019-09-07 16:35
Can you share the code that reproduces this?

Calling anything on widgetsbinding from a background isolate seems suspicious.

**Comment by vikramkapoor** [comment] 2019-09-10 03:26
I have eliminated the use of Background isolate from my application so I don't face this issue anymore. The odd thing is that I can't repro it even if I un-comment the code below that spawns the isolate. I did a "flutter clean" and "flutter packages get". May be that did something. I will investigate it a bit more tomorrow.
```
  @override
  Widget build(BuildContext context) {
    switch (authStatus) {
      case AuthStatus.notDetermined:
        return _buildWaitingScreen();

      case AuthStatus.notSignedIn:
        return SignInScreen();

      case AuthStatus.signedIn:
        if((appState.user.hotelId == null) || (appState.user.hotelId.isEmpty)) {
          return _getHotelCode();
        }
        else {
          if ((Globals.receivePort == null) || (broadcastReceivePort == null)) {
 //port for this main isolate to receive messages.
            Globals.receivePort = ReceivePort();
/*
            print("Spawning isolate 1");
            FlutterIsolate.spawn(isolate1, Globals.receivePort.sendPort).then((
                data) =>
            Globals.isolate = data);
            broadcastReceivePort =  Globals.receivePort.asBroadcastStream();
        }
*/
          return HomePage(broadcastReceivePort);
        }
    }
  }


void isolate1(SendPort sendPort) async {
  //WidgetsFlutterBinding.ensureInitialized();
  Firestore firestore = Firestore.instance;
  ReceivePort newIsolateReceivePort = ReceivePort();
  StreamSubscription<QuerySnapshot> mgrPanicStream;

  BgGlobals.beaconInfo = "";
  sendPort.send(newIsolateReceivePort.sendPort);
  BgGlobals.boPanic = false;

  newIsolateReceivePort.listen((data) {
    //
    // Process the message
    //
    debugPrint("ISOLATE:Received $data");
 if (data.toString().startsWith("userId:")) {
      BgGlobals.userId = data.toString().substring(8).trim();
    }  else if (data.toString().startsWith("sosEmail:")) {
      BgGlobals.sosEmail = data.toString().substring(10).trim();
    } else if (data.toString().startsWith("sosSMS:")) {
      BgGlobals.sosSMS = data.toString().substring(9).trim();
    } else if (data.toString().startsWith("userEmail:")) {
      BgGlobals.userEmail = data.toString().substring(10).trim();
    } else if (data.toString().startsWith("userName:")) {
      BgGlobals.userName = data.toString().substring(10).trim();
    } else if (data.toString().startsWith("roomRoomId:")) {
      BgGlobals.roomRoomID = data.toString().substring(11).trim();
    } else if (data.toString().startsWith("taskRoomId:")) {
      BgGlobals.taskRoomID = data.toString().substring(11).trim();
    }
  });
}
```

**Comment by telinx** [comment] 2019-09-10 09:33
Same problem after upgrade flutter.
```
[✓] Flutter (Channel master, v1.10.2-pre.12, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.10.2-pre.12 at /home/yucang/git/flutter
    • Framework revision 77f71ef48f (8 hours ago), 2019-09-10 10:32:27 +0900
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/yucang/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/yucang/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/yucang/software/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Redmi 6A • 8835d2d87d25 • android-arm • Android 8.1.0 (API 27)
```

**Comment by dnfield** [comment] 2019-09-10 15:55
@telinx  - a small reproduction would be much appreciated.  AFAICT there isn't a reproduction for this issue yet.

**Comment by dnfield** [comment] 2019-09-10 15:56
@vikramkapoor - hope you don't mind, I moved the body of your second post into the top post, which looked like just the blank template, and removed the now duplicate post.

**Comment by xster** [comment] 2020-04-29 19:08
Is this issue iOS specific?

**Comment by markusaksli-nc** [comment] 2020-08-18 12:42
Without any additional information there is really nothing to do here. 
I'm closing this issue as solved for the author, since they can't repro it anymore.

Could everyone who still has this problem please file a new issue with the exact description of what happens, your logs,  `flutter doctor -v`, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by markusaksli-nc** 2020-08-18 12:42 UTC
Labels: framework
