### ISSUE TITLE
[Impeller] Stack + Positioned + Transform with FilterQuality clips the widget.

### ISSUE THREAD

**Issue by AlessandroToschi** [flutter/flutter#131182] opened 2023-07-24 10:37 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The following hierarchy clips the child when rotated using the Impeller renderer:
`Stack --> Positioned --> Transform.rotate with FilterQuality --> Solid Color Container`

```
Stack(
  fit: StackFit.expand,
  children: [
    Positioned.fromRect(
      rect: Rect.fromLTWH(0.0, 0.0, 500.0, 500.0),
      child: Transform.rotate(
        angle: 0.4,
        filterQuality: FilterQuality.low,
        child: Container(color: Colors.green),
      ),
    ),
```

### Expected results

The solid color container should not be clipped.

### Actual results

The solid color container is clipped.

This affects only the Impeller renderer and not the Skia one.
Removing the `FilterQuality` solves the issue.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _rotation = 0.0;

  static const _width = 500.0;
  static const _height = 500.0;

  static const _sliderBottom = 48.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final x = (constraints.maxWidth - _width) / 2.0;
          final y = (constraints.maxHeight - _sliderBottom - _height) / 2.0;
          return Stack(
            fit: StackFit.expand,
            children: [
              Positioned.fromRect(
                rect: Rect.fromLTWH(x, y, _width, _height),
                child: Transform.rotate(
                  angle: _rotation,
                  filterQuality: FilterQuality.low,
                  child: Container(color: Colors.green),
                ),
              ),
              Positioned(
                left: 0.0,
                right: 0.0,
                bottom: _sliderBottom,
                child: Slider(
                  value: _rotation,
                  min: 0.0,
                  max: math.pi * 2.0,
                  onChanged: (rotation) => setState(
                    () => _rotation = rotation,
                  ),
                ),
              )
            ],
          );
        },
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

# Impeller

![IMG_4065](https://github.com/flutter/flutter/assets/6044244/d82046a7-aba5-40ec-b8c7-576db57d30d2)

# Skia

![IMG_4064](https://github.com/flutter/flutter/assets/6044244/ecb0caf4-fd7e-4972-847b-c942f644b9d6)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale en-US)
    ! Flutter version 3.10.6
    • Framework revision 3d8478a247 (2 hours ago), 2023-07-24 10:12:39 +0200
    • Engine revision 6f8ff0e653
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Flutter download mirror https://storage.googleapis.com/clay-flutter-storage
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/aleto/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode142.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment] 2023-07-24 12:17
Hi @AlessandroToschi. Thanks for filing this issue. I am able to reproduce this on the latest `master` and `stable` channels. 

| Impeller | Skia |
|--------|--------|
| <img src="https://github.com/flutter/flutter/assets/53122008/456e8289-8a39-4883-b36d-27a5dbbc8ef8"> | <img src="https://github.com/flutter/flutter/assets/53122008/07b382c8-51ed-40f7-8674-853ec50ed9d6"> | 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.6 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (12 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.13.0-8.0.pre.65, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.13.0-8.0.pre.65 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9c10151508 (2 hours ago), 2023-07-24 11:26:05 +0200
    • Engine revision 4734a709cb
    • Dart version 3.1.0 (build 3.1.0-333.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by chinmaygarde** [comment] 2023-07-24 18:19
FilterQuality.low introduces a new image filter and we have seen instance of this causing an unrelated issue with Impeller. We are tracking in https://github.com/flutter/flutter/issues/130355 and it has a pending PR out for the fix. We should consider cherry picking that. But closing this as a duplicate.

**Comment by jason-simmons** [comment] 2023-07-24 22:06
https://github.com/flutter/engine/pull/43943 actually causes a regression in this app.

When applying the rotation, the child widget is rendered at a different location with that PR.

@bdero 

| With PR #43943 | Without PR #43943 |
| ----- | ----- |
| ![with_pr_43943](https://github.com/flutter/flutter/assets/14226037/839b56a3-917e-49a9-b9be-1152eaef1c3e) | ![without_pr_43943](https://github.com/flutter/flutter/assets/14226037/5d191e46-6639-484b-a32d-2542cda37ee9) |

**Comment by jason-simmons** [comment] 2023-07-24 23:03
The original clipping issue appears to be unrelated to https://github.com/flutter/flutter/issues/130355.

I can reproduce it on an iOS device in landscape mode.  If I drag the slider and release the pointer, then the background of the slider is sometimes painted as opaque, causing it to partially cover the green widget.

Tried bisecting and noticed that this started with the introduction of partial repaint (https://github.com/flutter/engine/commit/20be523fb62651955d70985c1c94369987263b16)

@jonahwilliams

**Comment by jonahwilliams** [comment] 2023-07-24 23:07
If partial repaint is causing this issue to surface, then _generally_ that means its a bounds computation somewhere. To debug this, we could check what regions of the screen are being repainted.

**Comment by bdero** [comment] 2023-07-25 05:25
@jason-simmons I suspect that Impeller is culling out the transformed layer because the EntityPass culling logic doesn't take matrix filters into account. In other words, whenever the dirty region doesn't overlap with the untransformed layer (i.e. when the slider widget visually updates but the rotation of the layer doesn't change), it gets culled.

**Comment by jonahwilliams** [comment] 2023-07-31 18:30
Comparing Impeller/Skia on ToT and I still see that the green rectangle is rendered differently then with the Skia backend (FYI @bdero )

## Skia
<img src="https://github.com/flutter/flutter/assets/8975114/847694f1-da0d-43c3-a720-9baa4754c497" width="300"/>

## Impeller
<img src="https://github.com/flutter/flutter/assets/8975114/c7474c20-0868-4904-bfc3-eba1459517c8" width="300"/>


Now looking at partial repaint, the dirty rect  is computed as the bounds of the slider, however this ignores the fact that the rectangle is beneath it (or over it, I tried both approaches). I'm not sure if these bounds are being computed in DL, but by Impeller only ever gets the dirty rect so its not necessarily making any different decisions here.


<img src="https://github.com/flutter/flutter/assets/8975114/265d5242-1a89-403a-87cf-830cb9ba5dae" width="400"/>

FYI @knopp , is partial repaint supposed to be able to alpha composite with the backdrop? I had thought it was an all or nothing sort of approach.

**Comment by knopp** [comment] 2023-07-31 18:37
Partial repaint is definitely not supposed to alpha composite.

**Comment by jonahwilliams** [comment] 2023-07-31 18:39
Thanks, I suspect this is probably still a bounds computation issue then. Still investigating.

**Comment by jonahwilliams** [comment] 2023-07-31 19:05
Adding some debug logging and looking at the values while one corner of the rectangle is pointed straight down. They look about the same.

Impeller:

```
[VERBOSE-2:compositor_context.cc(192)] Impeller Clip Rect72,2256,1026,219
[VERBOSE-2:compositor_context.cc(192)] Impeller Clip Rect72,2256,1026,218
```

Skia:

```
[VERBOSE-2:compositor_context.cc(169)] Skia Clip Rect72,2249,1026,218
[VERBOSE-2:compositor_context.cc(169)] Skia Clip Rect72,2260,1026,192
```

So perhaps we're computing the bounds wrong?

**Comment by knopp** [comment] 2023-07-31 19:11
Same rotation (PI/4). Both angle and dimensions seem wrong.
| Skia  | Impeller |
| ------------- | ------------- |
| ![](https://github.com/flutter/flutter/assets/96958/ba739c29-9943-48a4-afc7-49302a702c7b) | ![](https://github.com/flutter/flutter/assets/96958/278abf4e-c0ce-4031-a62c-43389628a884) |

**Comment by jonahwilliams** [comment] 2023-07-31 19:29
Yeah, that seems like an issue.

I think I've narrowed this down to a potential culling issue in the Impeller backend. Partial repaint damage rects are computed identically for both backends. We should see that the image filtered rect intersects with this and paint it as normal, but Impeller is culling it out entirely

**Comment by knopp** [comment] 2023-07-31 19:52
@jonahwilliams, this is what causes the problem:

https://github.com/flutter/engine/blob/5b70ff0cfc6b36f964126bb8c269b25ea520a8d5/impeller/entity/entity_pass.cc#L109-L111

The coverage gets clipped to render target size, but that doesn't take into account that it will be later rendered rotated.

**Comment by knopp** [comment] 2023-07-31 19:54
Well, part of the problem at least - rasterization. There seems to be  similar things somewhere that breaks the culling.

**Comment by knopp** [comment] 2023-07-31 20:49
This might be tricky - because in this case only the image filter knows the rotation matrix.

**Comment by bdero** [comment] 2023-07-31 21:23
Yeah we need to add the ability to instantiate the filter graph with deferred inputs in order to handle this correctly: https://github.com/flutter/flutter/issues/130355#issuecomment-1632917871

The short term hack to sidecar `FilterContents` mentioned in that comment wouldn't work very well in practice, since it's possible for users to compute multiple filters together in the API.

I pulled that comment into a separate issue and added ideas for querying for transformed bounds: https://github.com/flutter/flutter/issues/131632

**Comment by knopp** [comment] 2023-07-31 21:29
Yeah, I was wondering if there is a way to instantiate filter before having the contents in order to calculate the coverage limit correctly. I guess that answers my question.

**Comment by jonahwilliams** [comment] 2023-08-01 23:42
I think I might be misunderstanding the issue a bit, I'm not sure why we don't have enough information to do this today. At the point where we're querying the coverage to cull, we've already constructed the filter and given it an entity. We should know the exact bounds, no? Or is the problem more in the computation of the coverage limit? 

Given that the coverage limit is itself an optimiation for culling (?) could we instead disable this if we know a matrix filter is present? 

Another piece of data, the coverage limit doesn't just cause the issue with partial repaint, it also causes the rendering of the matrix filter to be "smaller" than with Skia.

### Impeller

![flutter_06](https://github.com/flutter/flutter/assets/8975114/bf6a39f0-6699-428e-b4bd-3c86d6f34559)

### Skia

![flutter_05](https://github.com/flutter/flutter/assets/8975114/54c0b77e-5afd-49e4-bfc1-d93b667fc4ab)

### Impeller w/ Coverage Limit disabled

![flutter_04](https://github.com/flutter/flutter/assets/8975114/cd86b71f-dc2f-4cb0-9e73-5aca00a66420)

**Comment by knopp** [comment] 2023-08-02 02:19
I think the filter is constructed in `CreateContentsForSubpassTarget`, which is after the coverage limit has been applied.

**Comment by knopp** [comment] 2023-08-02 02:25
Also I don't think the matrix is smaller. It's the subpass texture size that is smaller (because the width clipped to parent pass render target width), so when it is later painted rotated by image filter it just looks smaller.

If you take the rectangle after rotatation and make it square with same center it should be exact the same size as skia.

**Closed** 2023-09-14 17:07 UTC
Labels: platform-ios, engine, c: rendering, has reproducible steps, P1, e: impeller, found in release: 3.10, team-engine, triaged-engine, found in release: 3.13
