### ISSUE TITLE
`initSurfaceAndroidView` uses Virtual Display as fallback mode

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#107313] opened 2022-07-08 15:29 UTC
(This is a summary of my current understanding; it's possible there are mistakes here.)

Prior to Flutter 3.0, we had two modes for Android PlatformViews:
- Virtual Display: min SDK version 20, lots of limitations around non-trivial views (no a11y support, some secondary controls in webviews didn't work, etc.)
    - This was selected using `initAndroidView`, which mapped to `TextureAndroidViewController`.
- Hybrid Composition: min SDK version 19: has threading implications, and performance on Android <10 is poor, but highly compatible.
    - This was selected using `initSurfaceAndroidView`, which mapped to `SurfaceAndroidViewController`.

In 3.0 we added a new mode (it doesn't have a formal name, but [the initial PR for it](https://github.com/flutter/engine/pull/31198) refers to "hybrid composition rendered as a texture layer", so I'm going to call it Texture Layer Hybrid Composition for now). The theory was that this would be strictly better than both modes and would thus replace both, and it was landed that way. But since then, various regressions were discovered and changes were made to the flow, most notably the recent https://github.com/flutter/engine/pull/33599

In the new flow, AFAICT, the modes are:
- Texture Layer Hybrid Composition: min SDK version 23, and doesn't work with SurfaceView. Also apparently [doesn't handle transparency on SDK <29](https://github.com/flutter/flutter/issues/104686#issuecomment-1156763554)
    - This is selected using either `initSurfaceAndroidView` or `initAndroidView` if the SDK and view type requirements are met.
- Virtual Display: now selected as a fallback for `initSurfaceAndroidView` or `initAndroidView` for SDK <23 or for `SurfaceView` native views.
- Hybrid Composition: now selected with `initExpensiveAndroidView`.

If this is correct, there are some pretty bad effects from the current state, for plugins that previously used Hybrid Composition. They now either use the new TLHC mode (which was the initial goal, when it was thought that this was a transparent update), or with the most recent change fall back **to Virtual Display**. So for instance `webview_flutter` (which we had previous switched to default to HC), which we don't want to be using VD due to the significant limitations, now does in some cases, in which case we unexpectedly:
  - dropped support for SDK 19, and
  - will have functionality regressions in SDK 20-22

And the only way to fix that would be to fully switch it to HC again (`initExpensiveAndroidView`), which means we wouldn't get the new behavior mode even when it would be supported.

I don't think this is a good state to leave the transition in. I see two better options:
1. Revert the behavioral change for `initSurfaceAndroidView` (so it goes back to using HC) and add a new explicit opt-in to the new mode.
1. Keep track of whether `initSurfaceAndroidView` or `initAndroidView` was originally called, and restructure things so that the fallback in unsupported cases is either to VD or HC depending on what was originally called, so that existing HC plugins don't have behavioral changes on SDK 20-22.

/cc @bparrishMines @cyanglaz @GaryQian @dnfield @Hixie for thoughts.

**Comment by josephcrowell** [comment] 2022-07-11 01:33
FYI a context check to ensure that the context from the view factory's 

```flutter
override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {}
```

within the View/Activity is failing a check in https://github.com/flutter/engine/pull/33599 when that is the context that is being passed.

The error is: 

```Unexpected platform view context. When constructing a platform view in the factory, use the context from PlatformViewFactory#create, view id: 0```

So this has been broken somehow in https://github.com/flutter/engine/pull/33599.

**Comment by GalacticTitan** [comment] 2022-07-12 13:23
Any workaround for this ?

**Comment by stuartmorgan** [comment] 2022-07-12 13:40
> Any workaround for this ?

Could you elaborate on your question? There are different possible outcomes a plugin author might want; without knowing what your goal is we can't say if there's a way of achieving it in the short term.

**Comment by cyanglaz** [comment] 2022-07-12 19:23
I think option 1 is acceptable and safe.
I'm not fully understand option 2. By "keep track of", did you mean (when initSurfaceAndroidView is used)each plugin needs to keep track of the original method and does the fullback manually? If so, this requirement might be too implicit as I'm not sure how we can force the plugin author to do that without introducing a breaking change.

**Comment by stuartmorgan** [comment] 2022-07-12 19:31
> I do not fully understand option 2. By "keep track of", did you mean (when initSurfaceAndroidView is used)each plugin needs to keep track of the original method and does the fullback manually?

No, sorry for being unclear; I mean that we would change the current logic of "if TLHC isn't supported, fall back to VD" to instead fall back to:
- VD if the plugin called `initAndroidView` (and thus was using VD prior to Flutter 3)
- HC if the plugin called `initSurfaceAndroidView` (and thus was using HC prior to Flutter 3)

So in option 2 plugins would still be auto-converted to TLHC when TLHC is supported (this has pros and cons, but was the original Flutter 3 intent), but the fallback case would be to the Flutter 2 behavior for that plugin.

**Comment by cyanglaz** [comment] 2022-07-12 19:49
Ah I got it. It was pretty clear in your issue summary I just didn't connect that part with the solution 2. So for option 2, we would need also to add a flag for user to opt out of using the TLHC in case they want to explicitly use the old mode for any reason.

For option 1, can we make TLHC to be the default and user can optionally disable that and fallback to HC? 
Because TLHC is already default in Flutter 3.0. We can essentially add this flag as a way for user to fallback to the old behavior if they need to. Is there any drawback of doing so?

**Comment by stuartmorgan** [comment] 2022-07-12 20:43
> So for option 2, we would need also to add a flag for user to opt out of using the TLHC in case they want to explicitly use the old mode for any reason.

We already provide a way to fully switch from TLHC to HC. We don't have a way to fully switch to VD, but it's not clear that anyone needs that option.

> For option 1, can we make TLHC to be the default

Anything where TLHC is the default isn't option 1 :) Option 1 is specifically reverting the Flutter 3.0 behavior of changing what mode the existing calls (`initAndroidView` and `initSurfaceAndroidView`) do.

> user can optionally disable that and fallback to HC

I'm not sure what "disable and fallback" means, since those are two very different things. Plugin authors explicitly disabling TLHC in favor of HC when writing their plugins is already possible (`initExpensiveAndroidView`). Fallback is something that happens at runtime, not plugin authoring time. So I'm not sure what you're suggesting exactly.

**Comment by cyanglaz** [comment] 2022-07-12 23:48
Ok, so my understanding now is that we don't change the behavior of `initAndroidView`, which defaults to TLHC and fallback to VD.

And the 2 options both replace VD to HC as the fallback behavior of `initSurfaceAndroidView`
In option 1, the HC plugin author uses a flag to enable TLHC explicitly.
In option 2, TLHC is enabled implicitly, the HC plugin author uses a different method (`initExpensiveAndroidView`) to disable TLHC

With option 1:
If the plugin is migrating from flutter 3, it is hard for the plugin to detect this change and might think they are using TLHC but actually are using HC. 
If the plugin is migrating from prior to flutter 3, they won't experience any change by default. They will have to opt-in TLHC.
If most of the platform view plugins support flutter 3, I think this option might cause plugin author unaware of this change and keeping their platform view with HC while they actually want TLHC, which seems very bad?

With option 2:
If the plugin is migrating from flutter 3, the only change is the fallback of `initSurfaceAndroidView` becomes HC instead of VD, which is a good improvement in most of cases. 
If the plugin is migrating from prior to flutter 3, we implicitly opted-in TLHC for them, which might cause breakage that is hard to detect. (visual artifacts, a11y etc) However, if TLHC is eventually the tech we want to push, this might be better. (For example, more plugins using it results more feedbacks)
If we know most of the platform view plugins already support flutter 3, I like option 2 better. (We might be able to do some query to check that?)

**Comment by josephcrowell** [comment] 2022-07-12 23:59
> Any workaround for this ?

The above initExpensiveAndroidView is probably what you're looking for. It sounds undesirable but this actually reverts it to the Hybrid Composition method from Flutter 2 that most people were previously using on the affected type of plugins.

**Comment by stuartmorgan** [comment] 2022-07-13 13:12
> Ok, so my understanding now is that we don't change the behavior of initAndroidView

In option 2 we don't change it. In option 1, we revert it to always using VD just as we revert `initAndroidSurfaceView` to always using HC, thus restoring Flutter 2.x behavior for existing methods. So in option 1 *all* plugin authors would need to opt in to TLHC explicitly (just as HC was originally introduced as an opt-in, not by changing the behavior of existing plugins).

We could consider what you're suggesting an an option 3: auto-switch plugins that are using VD, but don't auto-switch HC.

> If we know most of the platform view plugins already support flutter 3, I like option 2 better. (We might be able to do some query to check that?)

I don't see any way to get clear data on this unfortunately. We have no way of knowing from the code of a plugin whether it's using TLHC because the plugin author evaluated it and decided it worked for them so didn't opt out, or because they were automatically opted in. I would expect that the vast majority is the latter given that there wasn't a lot of communication around this (since it was supposed to be a silent upgrade). As a data point here: we're still evaluating what we should do about two of our major plugins (maps due to the missed redraw issue, and webview due to transparency regressions on older Android versions); if 1P plugins are still in flux from this transition, we should assume that many 3P plugins are as well.

We have some information from bugs, but it's hard to extrapolate from that. E.g., we know about the transparency issue now, but we don't know how many plugins rely on transparency support. We know about the maps update issue, but not how many other TextureView plugins might be affected by the same problem (or how common TextureView is as the native platform view type).

> If the plugin is migrating from prior to flutter 3, we implicitly opted-in TLHC for them, which might cause breakage that is hard to detect. (visual artifacts, a11y etc) However, if TLHC is eventually the tech we want to push, this might be better.

Yes, I see this as the core question: do we want to continue to strongly push a transition to TLHC because of the benefits it has—even knowing that there are also regressions—and require impacted plugins to explicitly switch back to an older mode, or do we reverse course because of the unexpected regressions, and essentially revert to 2.x behaviors but with TLHC re-launched as an opt-in mode?

Currently I'm leaning toward the former. I think the latter would have been better if we had known in advance about the issues and could have launched 3.0 with opt-in, but given that we already launched it as a default behavior—and I think have missed the reasonable window to revert in a cherry-pick—avoiding a second round of major behavioral changes in the next release is probably the better option.

**Comment by bparrishMines** [comment] 2022-07-15 01:29
>  As a data point here: we're still evaluating what we should do about two of our major plugins (maps due to the missed redraw issue, and webview due to transparency regressions on older Android versions); if 1P plugins are still in flux from this transition, we should assume that many 3P plugins are as well.

I would also add that `google_mobile_ads` is also having issues with impressions due to TLHC: https://github.com/googleads/googleads-mobile-flutter/issues/580

> Yes, I see this as the core question: do we want to continue to strongly push a transition to TLHC because of the benefits it has—even knowing that there are also regressions—and require impacted plugins to explicitly switch back to an older mode, or do we reverse course because of the unexpected regressions, and essentially revert to 2.x behaviors but with TLHC re-launched as an opt-in mode?

Assuming the issues with TLHC can be worked around, I think the former would be the better option as well. I'm just afraid of ending up in a situation where none of our 1P plugins use TLHC, but it remains as the default. But, it is hard to predict if more issues will rise. Correct me if I'm wrong, but as of now

1. **GoogleMaps** still needs to use VD/HC.
2. **WebView** defaults to TLHC, but switches to HC with transparent backgrounds.
3. **Google Mobile Ads** uses TLHC, but impressions are broken. This should be a p1 problem if TLHC is continued to be used. However, HC is unusable with `ListView`s because of performance and VD doesn't work.

**Comment by stuartmorgan** [comment] 2022-07-15 14:51
> 1. **GoogleMaps** still needs to use VD/HC.

For now, yes, the plan is to move it to HC. I would expect that we'll continue to use it as a test case to try to address TLHC issues though, in the hopes of eventually moving it to TLHC (ideally with HC fallback for older devices rather than VD).

> 2. **WebView** will default to TLHC, but switches to HC with transparent backgrounds.

That's our current plan. This would mean that most of the time our most-used (AFAIK) platform-view-based plugin would be using TLHC, which I think mitigates the concern about 1P usage.

(This could change if we find new major issues, but on the other hand I would expect major issues in webview to be reported pretty quickly, so it's promising that we don't have more.)

> 3. **Google Mobile Ads** uses TLHC, but impressions are broken. This should be a p1 problem if TLHC is continued to be used. However, HC is unusable with `ListView`s because of performance and VD doesn't work.

This seems like another case where I would expect reverting to HC to be a short-term solution, with the goal of making whatever changes are needed (either in TLHC or in the plugin itself) in the medium term to allow it to adopt TLHC.

> But, it is hard to predict if more issues will rise.

Agreed; that's definitely a concern. On the other hand, the best way to find issues any as-yet undiscovered issues is for it to be the default, and if plugin authors have a clear way of opting out if they hit unresolvable issues that mitigates the downsides (beyond the initial pain of the defaults having changed, which unfortunately already happened when we shipped 3.0).

**Comment by josephcrowell** [comment] 2022-07-16 09:37
> revert to 2.x behaviors but with TLHC re-launched as an opt-in mode?

This sounds like the best option which will alleviate the growing frustration from the community most efficiently.

No one asked for these changes and in the pursuit of better performance, unilateral decisions were made in a totalitarian manner which may not be in the best interests of 90% of the people who use platform views. It should be an option, not a forced change which is untenable in most instances. The person making the change assumed the only thing being pushed through platform views were opengl  surfaces, which just isn't even close to the case. These Map SDKs force us to use whole activities with widgets created by Flutter, Here Maps, Maplibre, Google Maps, etc with no option to rewrite their entire functionality in Flutter. The Flutter map plugins are community created and use the native SDK. The SDK creators have no intention of making anything specifically for Flutter and thus aren't providing a level of access or stabilty to their SDKs which make replacing the widgets inserted in to their activities a good choice. Thus, the forced change and resulting available options aren't an option at all for us. By forcing this choice upon us, the creator was effectively forcing us to choose something other than Flutter.

**Comment by stuartmorgan** [comment] 2022-07-16 11:18
> which may not be in the best interests of 90% of the people who use platform views

If you have other specific examples of plugins that don't work in TLHC mode, please file new issues for each one (and tag me in them). Specific, concrete data about where it does and does not work will be useful in making a decision here (while invented numbers are not).

> The person making the change assumed the only thing being pushed through platform views were opengl surfaces

I don't know how you came to this conclusion; it's not a true statement. But let's keep this constructive by focusing on outcomes, not people. Examples of plugins that don't work, with detailed repro steps, will let us better gauge the scope of issues.

> with no option to rewrite their entire functionality in Flutter

Rewriting functionality in Flutter is--explicitly--not the use case for PlatformViews, so this isn't relevant to this issue.

**Comment by josephcrowell** [comment] 2022-07-16 17:18
You need me to make my own individual issues at Flutter for all the issues linked to here? 

https://github.com/flutter/flutter/issues/103630 

People are linking to the Flutter issue and then closing the issue on their own repo even though the issue isn't resolved. I can count 36 linked issues on that page including mine and more are incoming as more people upgrade to flutter 3.

Here's mine on my repo. https://github.com/AnnonAU/flutter_mapbox_turn_by_turn/issues/1 It "works" sort of with expensive view on Flutter 3 but some physical devices are failing with random errors that never occurred before such as crashes with no error and an error about failing  to compile an OpenGL shader when the map activity initializes. There is an error on close about TLHC never being initialized when I never used TLHC. Some errors (not these ones) occur only in release mode and I have no idea what errors because I have no debug symbols/stacktrace.

RE: None of this happened before on 2.15.10 and if I downgrade to flutter 2, these errors go away. We'll need all this working eventually though as some of the plugins we use (flutter_secure_storage for example) are continuing development only on Flutter 3.

**Comment by stuartmorgan** [comment] 2022-07-17 11:32
> You need me to make my own individual issues at Flutter for all the issues linked to here?
> 
> #103630

See https://github.com/flutter/flutter/issues/103630#issuecomment-1183504718

> People are linking to the Flutter issue and then closing the issue on their own repo even though the issue isn't resolved.

If people treat a single issue as a catch-all for a lot of potentially unrelated problems, it's very hard to know what has and has not been fixed (as demonstrated by that issue).

> Here's mine on my repo. [...] It "works" sort of with expensive view on Flutter 3 but some physical devices are failing with random errors that never occurred before

Again, please file **a new issue**. What you describe in that last sentence is entirely unrelated to both #103630 and this issue (since you're not using TLHC in that scenario), so needs a new issue tracking it.

This issue is only about the specific problem of `initSurfaceAndroidView` now using VD in some cases instead of either TLHC (the intended new behavior) or HC (as a fallback). *One possible solution* to that issue would have the effect of making more widespread changes, but that doesn't mean it should be treated as an umbrella bug covering every regression in Flutter 3 Android platform views.

**Comment by josephcrowell** [comment] 2022-07-18 05:12
> If people treat a single issue as a catch-all for a lot of potentially unrelated problems, it's very hard to know what has and has not been fixed (as demonstrated by that issue).

No they're all describing the same problem. They're just listing the symptoms slightly differently based on which symptoms affect them the most on their test devices. This same problem is just that low level and wide reaching. Some problems may be separate but until functionality is reverted we won't know for sure how many of these issues were caused by this change. If after your fix, there are still new issues with my code, I would prefer to revisit submitting those issues then.

TLHC breaks different things based on the version of Android it's being run against (and Android SDK version it's being compiled against) and generally should be treated as an optional, experimental feature until all the bugs are worked out. The actual issue in all the reported instances is the fact that it pulls an OpenGL surface out of the view hierarchy completely and it overlays the entire application with the surface:

- At it's proper width and height but with top and left coordinates at 0 on Android 10 and higher.
- At it's proper width and height with the correct coordinates on 10 and lower.

It pulls the surface out of the Android activity and leaves the remaining activity components underneath on all versions of Android.  The only difference is what I listed above. 

This is the symptom that most people are reporting and what was reported in the original issue. IIUC TLHC isn't even working correctly for the use case that it was created for.

Before creating a list of new issues, maybe reverting would be the best option as you said:

> In option 1, we revert it to always using VD just as we revert `initAndroidSurfaceView` to always using HC, thus restoring Flutter 2.x behavior for existing methods. So in option 1 _all_ plugin authors would need to opt in to TLHC explicitly (just as HC was originally introduced as an opt-in, not by changing the behavior of existing plugins).

This would be advisable because this will ensure the majority of the current issues caused by these changes are resolved and then encourage creating issues for the remaining cases afterwards.

**Comment by stuartmorgan** [comment] 2022-07-18 11:29
@josephcrowell Please see my latest comment in https://github.com/flutter/flutter/issues/103630, and follow up there if you have more to add about that issue. I would like to keep this issue focused on what I filed it to track: undesired switch from HC to VD in fallback mode.

**Comment by xster** [comment] 2022-07-21 09:02
I understand the toggle on the platform view itself now with initExpensiveAndroidView etc. I understand that the default platform view will be TLHC. 

For web view, it seems like there's no toggle and it'll just use TLHC by default?

For Google Maps, it looks like there is a toggle, but I don't really understand what it's toggling in between. I couldn't figure it out from the doc https://github.com/flutter/plugins/blob/89eff491b1daac4e4baf11f1270c674b74137435/packages/google_maps_flutter/google_maps_flutter/lib/src/google_map.dart#L73

**Comment by stuartmorgan** [comment] 2022-07-21 13:59
@xster I filed https://github.com/flutter/flutter/issues/108106 to track and discuss our 1P plugin changes.

**Comment by rlee1990** [comment] 2022-08-17 03:36
Any timeline on when this will be fixed in Stable? This is a major issue.

**Comment by stuartmorgan** [comment] 2022-08-17 11:50
> Any timeline on when this will be fixed in Stable?

The PRs to change fallback behavior haven't landed on `master` yet.

> This is a major issue.

Can you describe the specific problem (including affected plugin(s)) you are having that you are expecting this issue to fix? Some other issues have referenced this one in cases where it's not actually relevant.

**Comment by MarkAlexanderDev** [comment] 2022-09-05 15:16
From my side, I am using the plugin [arcore_flutter_plugin](https://pub.dev/packages/arcore_flutter_plugin) that is using an `AndroidView` and with the latest stable version of Flutter, it is impossible to place or resize the widget correctly. 
I have to use the 2.10.5 flutter version to make it work as expected.

**Comment by stuartmorgan** [comment] 2022-09-05 16:25
@MarkAlexanderDev Please file a new issue with details. This issue will only change (rare) fallback logic.

**Comment by wangying3426** [comment] 2022-09-19 06:59
@stuartmorgan Could you help me with a few questions?
 1. Hybrid Composition uses ImageReader to render the Flutter page, but can we use FlutterTextureView to replace FlutterImageView directly? why not?
 2. TLHC improved platform views performance, does that mean only improved performance on Android < 10 ? Whether there is performance improvement on Android >= 10?

**Closed** 2022-09-21 15:57 UTC
Labels: severe: regression, platform-android, engine, plugin, P3
