### ISSUE TITLE
Just an Idea. Can you put android and ios folders together into one folder called "output" ? 

### ISSUE THREAD

**Issue by tananga** [flutter/flutter#79251] opened 2021-03-29 04:54 UTC
## Proposal

Just an Idea. Can you put android and ios folders together into one folder called "output" ? If in the future someone creates another platform the project structure will be messy. Thank you for your time. It's just a suggestion.

**Comment by nt4f04uNd** [comment] 2021-03-29 04:59
duplicate of https://github.com/flutter/flutter/issues/71400

**Comment by pedromassangocode** [comment] 2021-03-29 09:20
Closing as duplicate of https://github.com/flutter/flutter/issues/71400.

**Closed by pedromassangocode** 2021-03-29 09:20 UTC
Labels: in triage
