### ISSUE TITLE
Support Google Play Billing Library 4.1

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#102613] opened 2022-04-26 23:57 UTC
The in_app_purchase plugin currently support 3.0.2 from 11/24/2020.

4.1 is the latest version:
https://developer.android.com/google/play/billing/release-notes#4-1

cc @GaryQian

**Comment by stuartmorgan** [comment] 2022-04-27 00:17
Closing as a duplicate of https://github.com/flutter/flutter/issues/88664 since we're already tracking there.

**Closed** 2022-04-27 00:18 UTC
Labels: platform-android, plugin, p: in_app_purchase, P3
