### ISSUE TITLE
[in_app_purchase] in_app_purchase_android - Exception on json parsing in SkuDetailsWrapperFromJson introduced in 0.1.4+7

### ISSUE THREAD

**Issue by TomTom0815** [flutter/flutter#90606] opened 2021-09-23 16:19 UTC
## Steps to Reproduce

1. Take the example from the official documentation: https://pub.dev/packages/in_app_purchase/example
2. Set up the application, IAP products and test account as described in https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/in_app_purchase/example/README.md#android
3. Test/debug the example on your device

With the version [0.1.4+6](https://pub.dev/packages/in_app_purchase_android/versions/0.1.4+6) the example runs fine.
With the version [0.1.4+7](https://pub.dev/packages/in_app_purchase_android/versions/0.1.4+7) the example is throwing an exception.

The code that changed is in **\lib\src\billing_client_wrappers\sku_details_wrapper.g.dart**
```
    introductoryPriceMicros: json['introductoryPriceMicros'] as String? ?? '',
```
changed to 
```
    introductoryPriceMicros:
        json['introductoryPriceAmountMicros'] as String? ?? '',
```
**Expected results:** 
no Exception in both version

**Actual results:** 
Exception in newer version 0.1.4+7 from Sept-20

**Comment by TahaTesser** [comment] 2021-09-24 07:38
This is a duplicate of 
https://github.com/flutter/flutter/issues/90509.

Please see [this](https://github.com/flutter/flutter/issues/90509#issuecomment-924748571) issue comment for further reference.
Closing from here.

**Closed by TahaTesser** 2021-09-24 07:38 UTC
Labels: in triage
