### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by come219** [flutter/flutter#117203] opened 2022-12-16 04:51 UTC
## Command
```
flutter drive \ --driver=test_driver/integration_test_driver.dart \ --target=integration_test/alert_test.dart --dart-define=EMAIL=secret \ --dart-define=PASS=secret/
```

## Steps to Reproduce
1. Connect Samsung Duos Phone 
2. Have these libraries in Application
3. Run Integration test

## Logs
HttpException

"HttpException: Connection closed before full header was received, uri"

https://github.com/flutter/flutter/issues?q=is%3Aissue+HttpException%3A+Connection+closed+before+full+header+was+received%2C+uri+%3D+http%3A%2F%2F127.0.0.1%3A64759%2Fbg6LZ71nTfg%3D%2Fws

Flutter Doctor: 

[✓] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19045.2251], locale en-GB)
    • Flutter version 2.10.5 at C:\Users\user\flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • SM A700FD (mobile) • 3ca4f48a • android-arm    • Android 6.0.1 (API 23)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 108.0.5359.124
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 108.0.1462.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.60+160
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
appsflyer_sdk-6.5.2+2
cloud_firestore_web-2.8.10
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_dynamic_links-4.3.11
firebase_messaging-13.1.0
firebase_messaging_web-3.2.0
flutter_facebook_sdk-1.0.0
flutter_plugin_android_lifecycle-2.0.5
flutter_secure_storage-5.0.2
flutter_secure_storage_linux-1.1.0
flutter_secure_storage_macos-1.1.0
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
geocoding-2.0.5
geolocator-9.0.1
geolocator_android-4.1.1
geolocator_apple-2.2.1
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_api_headers-1.3.0
google_maps_flutter-2.2.0
google_maps_flutter_android-2.1.10
google_maps_flutter_ios-2.1.11
google_sign_in-5.4.0
google_sign_in_android-6.0.1
google_sign_in_ios-5.4.0
google_sign_in_web-0.10.2
image_picker-0.8.5
image_picker_android-0.8.4+11
image_picker_for_web-2.1.6
image_picker_ios-0.8.4+11
integration_test
location-4.4.0
location_web-3.1.1
mobile_scanner-1.1.2
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
plain_notification_token-0.0.4
share-2.0.4
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2+1
store_redirect-2.0.1
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.3.0
video_player_android-2.3.2
video_player_avfoundation-2.3.2
video_player_web-2.0.8
wakelock-0.6.1+2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.8.5
webview_flutter_wkwebview-2.7.2

**Comment by darshankawar** [comment] 2022-12-16 07:03
Closing as duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by darshankawar** 2022-12-16 07:03 UTC
Labels: in triage

**Comment by LastMonopoly** [comment] 2023-02-02 13:36
Same here,

sample code: https://github.com/flutter/samples/tree/main/testing_app

flutter drive --driver=integration_test/driver.dart --target=integration_test/app_test.dart
flutter drive --driver=integration_test/driver.dart --target=integration_test/state_mgmt_test.dart
flutter drive --driver=integration_test/perf_driver.dart --target=integration_test/perf_test.dart --profile --trace-startup

commands start with "flutter drive ..." all end with
"Oops; flutter has exited unexpectedly: "HttpException: Connection reset by peer ..."

**Comment by LastMonopoly** [comment] 2023-02-02 13:36
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-x64, locale
en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.74.3)
[!] Proxy Configuration
! NO_PROXY is not set
[✓] Connected device (4 available)
[✓] HTTP Host Availability
