### ISSUE TITLE
stock_build_iteration microbenchmark regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46162] opened 2019-12-05 16:48 UTC
Since at least https://github.com/flutter/flutter/pull/45722, although it looks like it was drifting up before that. Minor increase; may be a candidate for rebasing.

**Comment by jason-simmons** [comment] 2019-12-05 18:24
In the benchmark history, there was a noticeable increase starting with https://github.com/flutter/flutter/commit/afb8f382110dc17ed0b44eda4a41612c518fee77

**Comment by dkwingsmt** [comment] 2019-12-05 21:12
I merged a PR https://github.com/flutter/flutter/pull/46113 just now, hoping to reduce the overhead. Let's see if it helps...

**Comment by cyanglaz** [comment] 2019-12-05 21:29
@kf6gpe Did you mean stock_layout_iteration? I don't see any red in the stock_build_iteration bench mark.

**Comment by dkwingsmt** [comment] 2019-12-06 00:04
I experimented by adding a `print` to every method that got changed during the PR https://github.com/flutter/flutter/pull/45722 and none of them is called each iteration, other than a few `if` statements. I believe the increase either comes from other causes, or there is nothing else I can further optimize.

**Comment by kf6gpe** [comment] 2019-12-06 17:01
I did, thank you @cyanglaz. @dkwingsmt Maybe w should rebaseline, then?

**Comment by goderbauer** [comment] 2019-12-06 22:37
We could also try reverting the change in question to see if it makes any difference? In theory, #45722 should not change performance characteristics.

**Comment by liyuqian** [comment] 2019-12-09 23:05
I see that `microbenchmarks_ios stock_build_iteration` has gone down, but `microbenchmarks stock_build_iteration` is still higher than before (~6200 vs ~5700)? It seems to me that the regression happens anywhere between https://github.com/flutter/flutter/commit/6eb0a0e3715c6eeb7a2733f74cf6e741fe796ef6 and https://github.com/flutter/flutter/commit/475ee89879834fc3d79da5f3250bd88e91f19ef8 because the data is missing in between.

**Closed** 2019-12-09 23:12 UTC
Labels: f: scrolling, framework, severe: performance, severe: regression, ⚠ TODAY
