### ISSUE TITLE
Getting Error :Got TLS error trying to find package cupertino_icons at https://pub.dartlang.org. while running command flutter create app

### ISSUE THREAD

**Issue by hemangitandel** [flutter/flutter#25321] opened 2018-12-13 10:38 UTC
## Steps to Reproduce

1. flutter create newapp
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment] 2018-12-13 10:41
Duplicate of #15014

**Closed by zoechi** 2018-12-13 10:41 UTC
