### ISSUE TITLE
[tool_crash] _TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))

### ISSUE THREAD

**Issue by Y0ngg4n** [flutter/flutter#155420] opened 2024-09-19 18:03 UTC
## Command
```sh
flutter run -d chrome
```

## Steps to Reproduce
I dont know

## Logs
_TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))
```console
#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56)
#1      _loadDwdsDirectory (package:flutter_tools/src/isolated/devfs_web.dart:1234:45)
#2      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:270:15)
<asynchronous suspension>
#3      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:860:22)
<asynchronous suspension>
#4      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:328:19)
<asynchronous suspension>
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.1, on NixOS 24.05 (Uakari) 6.10.1-zen1, locale de_DE.UTF-8)
    • Flutter version 3.24.1 on channel stable at /nix/store/ivslg1wbqmfcfhaxabdi36bd3cjvhnbq-flutter-wrapped-3.24.1-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (), 1970-01-01 00:00:00
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /nix/store/1ifczz962acxbph2hrqjqjd0csf414ns-android-sdk-env/share/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /nix/store/1ifczz962acxbph2hrqjqjd0csf414ns-android-sdk-env/share/android-sdk
    • ANDROID_SDK_ROOT = /nix/store/1ifczz962acxbph2hrqjqjd0csf414ns-android-sdk-env/share/android-sdk
    • Java binary at: /nix/store/xy53lk4001h814d7dwh8f52wcqxrn7rp-openjdk-17.0.11+9/lib/openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+9-nixos)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /run/current-system/sw/bin/chromium-browser

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.2
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • NixOS 24.05 (Uakari) 6.10.1-zen1
    • Chrome (web)    • chrome • web-javascript • Chromium 128.0.6613.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.12+14
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: nixpkgs000000000000000000000000000000000
### Plugins
device_info_plus-10.1.2
flutter_compass-0.8.0
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
geolocator-13.0.1
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
isar_flutter_libs-3.1.0+1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
sqlite3_flutter_libs-0.5.24
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
vibration-2.0.0

**Comment by danagbemava-nc** [comment] 2024-09-20 07:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153238

**Closed by danagbemava-nc** 2024-09-20 07:23 UTC
Labels: in triage
