### ISSUE TITLE
Focus moves to `ModalScopeState` instead of an app’s `FocusScope` when you click outside of a `TextField`

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#97389] opened 2022-01-27 18:13 UTC
I’m working on fixing some focus issues in Flutter DevTools (https://github.com/flutter/devtools/issues/3457) which prevent a user from being able to perform keyboard shortcuts. 

### Actual behavior
* Focus is on the app’s root scope, and a user can perform keyboard shortcuts.
* User clicks into a `TextField`. Now the focus is on the `TextField` and a user can still perform keyboard shortcuts. 
* User clicks out of the `TextField`. Focus moves to `ModalScopeState` and the ability to perform keyboard shortcuts is lost. 

### Expected behavior
Clicking outside of the TextField returns focus to the app’s root scope, and a user can still perform keyboard shortcuts.

### How to reproduce 
Here is a gist with a simple example where this issue can be seen: https://gist.github.com/elliette/d31aec75e000b3e2497a10d61bc6da0c

* Create a flutter app, and replace `main.dart` with the code in the gist. *Note: There is currently an issue with DartPad and `package:flutter/services.dart`, so DartPad won’t work for this example.*
* Run the app with `flutter run -d chrome`
* Try clicking around the app and hitting the ESC key. The app should register that ESC was hit. 
* Then, comment in the `TextField` and reload the app. 
* This time, click around the app and hit the ESC key. The app should register that ESC was hit up until you click into and out of the `TextField`. Now the app will no longer register ESC being pressed. 

### Notes
I see that unfocusing of the `TextField` after clicking out of it was introduced with https://github.com/flutter/flutter/pull/82575, which calls `unfocus` when a mouse event doesn’t contact a focused node. However, since Flutter DevTools uses `MaterialApp`, calling `unfocus` should return focus to the app’s `FocusScope` (see https://docs.flutter.dev/development/ui/advanced/focus#unfocusing). 

I wonder if the underlying issue is the same as https://github.com/flutter/flutter/issues/97013?

**Comment by busslina** [comment] 2022-07-04 15:13
Here the same issue. I try to always capture focus with a hierarchical structure and when I click outside a textfield focus is gained by a focus node with "_ModalScopeState<dynamic> Focus Scope" as debug label.

My first doubt is which element introduces this modal scope. Is it Material App? Is it scaffodl?
My second doubt is how to disable this Focus Sscope?

![imagen](https://user-images.githubusercontent.com/73592852/177181851-7c313258-b77b-4f53-b562-94a89fb8225c.png)

**Comment by busslina** [comment] 2022-07-07 14:03
It is Material App that adds this Focus Scope. Adding a Focus widget above Material App allows you to not lost focus (on that root node) when clicked outside TextField and _ModalScopeState FocusScope gains the focus. Still not the desired behavior.
Make no sense to have controlled the focus with a hierarchical tree structure which leaf is the textfield (or any other widget) and transfer the focus to Material App (_ModalScopeState) when clicked outside textfield (breaking the focus node tree below Material App).

I found some tricky ways to counter that behavior, but I want to resolve this in a acceptable way. Seems that I will have to dig into MaterialApp code.

Any suggestion will be rewarded.

**Comment by simonbengtsson** [comment] 2022-09-21 16:57
Ran into this as well today and assume it is an issue for all desktop and web apps using keyboard shortcuts? Tried the workaround @busslina mentioned, but caused the TextField not to loose focus when clicking outside of it.

Steps to reproduce (in example below)
1. Tap space key and observe the logs that shows that this keyboard shortcut works
2. Enter some text in the text field
3. Click anywhere in the app outside of text field
4. Tap space and observe that the keyboard shortcut no longer works

<details>
<summary>Simplified example</summary>
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shortcut Issue Demo',
      home: CallbackShortcuts(
        bindings: {
          const SingleActivator(LogicalKeyboardKey.space): () {
            print('Space was pressed');
          }
        },
        child: Focus(
          autofocus: true,
          child: Scaffold(
            backgroundColor: Colors.pink,
            body: Column(
              children: const [
                Text(
                    '1. Tap space and observe the logs that shows that this keyboard shortcut works\n2. Enter some text in the text field below\n3. Click anywhere in the app outside of text field\n4. Tap space and observe that the keyboard shortcut no longer works'),
                TextField(
                  decoration: InputDecoration(hintText: 'Enter some text...'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by bleroux** [comment] 2023-04-17 13:07
There are two code samples in this issue.
For both of them, the issue can be fixed by adding a `FocusScope`:

<details>
<summary>Updated @elliette's code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  debugFocusChanges = true;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Keyboard Shorcut Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return CounterShortcuts(
      onEscDetected: _incrementCounter,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Demo'),
        ),
        body: Center(
          child: Row(
            children: <Widget>[
              const Spacer(),
              // TODO: Uncomment the below. With a TextField,
              // if you click into the TextField and out of it
              // then clicking ESC no longer works.
              const Expanded(
                child: TextField(),
              ),
              const Spacer(),
              const Text(
                'You have pushed ESC this many times:',
              ),
              Text('$_counter'),
              const Spacer(),
            ],
          ),
        ),
      ),
    );
  }
}

final incrementKeySet = LogicalKeySet(LogicalKeyboardKey.escape);

class IncrementIntent extends Intent {}

class CounterShortcuts extends StatelessWidget {
  const CounterShortcuts({
    Key? key,
    required this.child,
    required this.onEscDetected,
  }) : super(key: key);
  final Widget child;
  final VoidCallback onEscDetected;

  @override
  Widget build(BuildContext context) {
    return FocusableActionDetector(
      autofocus: true,
      shortcuts: {
        incrementKeySet: IncrementIntent(),
      },
      actions: {
        IncrementIntent: CallbackAction(onInvoke: (e) => onEscDetected.call()),
      },
      child: FocusScope(
        child: child,
      ),
    );
  }
}

```
</details>

<details>
<summary>Updated @simonbengtsson’s code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shortcut Issue Demo',
      home: CallbackShortcuts(
        bindings: {
          const SingleActivator(LogicalKeyboardKey.space): () {
            print('Space was pressed');
          }
        },
        child: const FocusScope(
          autofocus: true,
          child: Scaffold(
            backgroundColor: Colors.pink,
            body: Column(
              children: [
                Text(
                    '1. Tap space and observe the logs that shows that this keyboard shortcut works\n2. Enter some text in the text field below\n3. Click anywhere in the app outside of text field\n4. Tap space and observe that the keyboard shortcut no longer works'),
                TextField(
                  decoration: InputDecoration(hintText: 'Enter some text...'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

When clicking outside of a `TextField` default `TextField.onTapOutside` implementation is to call `FocusNode.unfocus()` which `disposition` parameter is set to `UnfocusDisposition.scope` by default (documented as "Focus the nearest focusable enclosing scope of this node").
If the app did not define its own `FocusScope` the closest one is the one created by the `MaterialApp` navigator and this one is above the shortcut definition in both code samples.

As this is not obvious it would be great to improve the default behavior (for instance adding automatically some `FocusScope` but it might worsen the API flexibility) or maybe document this better (for instance by mentioning that `CallbackShortcuts` and `FocusableActionDetector` do not add there own `FocusScope`).

@gspencergoog Do you think updating the documentation is the safest change or do you think it would make sense for `CallbackShortcuts` and `FocusableActionDetector` to insert a `FocusScope`?

**Comment by gspencergoog** [comment] 2023-04-17 18:05
I think updating the documentation is the right course here.  Adding a `FocusScope` to either of those would totally break the focus traversal of any app that has those someplace other than the very top of the widget tree, since it would restrict the focus traversal to the new scope.

**Comment by bleroux** [comment] 2023-05-09 08:53
Since this issue was filed, https://github.com/flutter/flutter/pull/107262 introduces `TextField.onTapOutside` callback which can be used to override the default behavior when a text field is unfocused.

So there are two possible solutions for this issue:

- Adding a `FocusScope` widget. But this makes sense only when the shortcuts are defined near the top of the widget tree, see https://github.com/flutter/flutter/issues/97389#issuecomment-1511308216.

- Providing a `TextField.onTapOutside` callback which calls `FocusNode.requestFocus` on the expected focus node.

Closing this issue because customizing the `TextField` unfocused behavior is already commented on https://api.flutter.dev/flutter/material/TextField/onTapOutside.html

**Closed by bleroux** 2023-05-09 08:53 UTC
Labels: a: text input, d: api docs, a: desktop, documentation, f: focus, P4
