### ISSUE TITLE
Flutter Web - Firefox scrolls extremely slow

### ISSUE THREAD

**Issue by strenkml** [flutter/flutter#77714] opened 2021-03-09 16:07 UTC
I found issue #67972 which is closed but it seems that the issue is still present.

Note: This only seems to happen with a mouse, scrolling with a track pad works fine.

## Steps to Reproduce
1. Created a new flutter project and run "flutter config --enable-web"
2. Replaced main.dart with the following code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> cards = [];

  _MyHomePageState() {
    for (var i = 0; i < 200; i++) {
      cards.add(Card(
        child: ListTile(
          title: Text("Card #$i"),
        ),
      ));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ListView(
          children: cards,
        ),
      ),
    );
  }
}
```

3. Run "flutter build web"
4. Run "cd build/web"
5. Run "python -m http.server 80"
6. Open Firefox and navigate to http://localhost
7. Open Chrome and naviagate to http://localhost

**Expected results:**
When scrolling down the page Firefox and Chrome should scroll the same amount.

**Actual results:**
Firefox scrolls noticeably slower than Chrome does 

<details>
  <summary>Logs</summary>
[√] Flutter (Channel master, 2.1.0-11.0.pre.165, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 2.1.0-11.0.pre.165 at E:\Documents\Programming\Flutter\flutter
    • Framework revision 698d438960 (9 hours ago), 2021-03-09 07:53:21 +0100
    • Engine revision 2441c476a6
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\flyer_zf1eab6\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\flyer_zf1eab6\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\flyer_zf1eab6\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!

flutter analyze output:
Analyzing web...
No issues found! (ran in 0.6s)

</details>

**Comment by darshankawar** [comment] 2021-03-10 10:33
Verified and replicable using latest master. The scroll using mouse is noticeably slow in Firefox as compared to chrome.



https://user-images.githubusercontent.com/67046386/110615797-ce990600-81b9-11eb-9d52-93df9735cd75.mov




<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.179, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.179 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 07e04484ea (4 hours ago), 2021-03-09 20:10:05 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.2
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by andyduke** [comment] 2021-03-21 20:24
Slow scrolling occurs due to the fact that Flutter relies on `WheelEvent.deltaMode` in the browser to determine the scroll mode. In Firefox it is equal to `DOM_DELTA_PIXEL`, i.e. per-pixel scrolling. A workaround might be to override the `WheelEvent.deltaMode` property, along with the `WheelEvent.deltaX` and `WheelEvent.deltaY` properties, to specify the delta mode `DOM_DELTA_LINE` and multiply the scroll delta by 3.

If you paste the code below into your `web/index.html` file before the closing `</head>` tag, then mouse wheel scrolling will be like in Chrome. 

```html
  <script>
    // Patch wheel deltaMode
    (function() {
      function overrideProp(obj, name, descriptor) {
        var prevDescriptor = Object.getOwnPropertyDescriptor(obj, name);
      
        if (!!descriptor.get) {
          var _get = descriptor.get;
          descriptor.get = function() {
            var value = (!!prevDescriptor && !!prevDescriptor.get) ? prevDescriptor.get.call(this) : null;
            return _get.call(this, value);
          }
        }
        if (!!descriptor.set) {
          var _set = descriptor.set;
          descriptor.set = function(value) {
            if (_set(value) !== false && (!!prevDescriptor && !!prevDescriptor.set)) {
              prevDescriptor.set.call(this, value);
            }
          }
        }
      
        Object.defineProperty(obj, name, descriptor);
      }
      
      var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
      if (isFirefox) {
        var syntheticEvent = new WheelEvent("syntheticWheel", {"deltaX": 4, "deltaMode": 0});
        if (syntheticEvent.deltaMode == 0) {
          overrideProp(WheelEvent.prototype, 'deltaMode', {
            get: function(value) {
              return 1; // DOM_DELTA_LINE
            }
          });
          overrideProp(WheelEvent.prototype, 'deltaX', {
            get: function(value) {
              return value * 3; // 3 per scroll
            }
          });
          overrideProp(WheelEvent.prototype, 'deltaY', {
            get: function(value) {
              return value * 3; // 3 line per scroll
            }
          });
        }
      }
    })();
  </script>
```

**Comment by mdebbar** [comment] 2021-11-01 15:36
I'm unable to reproduce this issue in Firefox on Mac. Is this still happening? Or am I misunderstanding the issue?

**Comment by maheshmnj** [comment] 2021-12-06 12:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-06 12:09 UTC
Labels: waiting for customer response, framework, severe: performance, f: scrolling, platform-web, perf: speed, a: mouse, has reproducible steps, browser: firefox, P3, found in release: 2.1
