### ISSUE TITLE
Error when trying to build for iPad iOS device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3411] opened 2016-04-19 20:15 UTC
This is using a up-to-date master as of now.

Output from running via Atom:

```
flutter run --no-checked --debug-port=16204 --start-paused --device-id b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb • flutter logs
map/ • debug
Running 'pub get' in map...                            -\|/-\|/-\|/1.1s
Running lib/main.dart on iPad...
Unzipping Xcode project to local directory...
Xcode project created in /Users/sethladd/flutter/map/ios/.
[....] Waiting for iOS device to be connected
[....] Using J81AP 'iPad' (b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb).
------ Install phase ------
[  0%] Found J81AP 'iPad' (b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb) connected through USB, beginning install
[  5%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/ to device
[  5%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[  6%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/ to device
[  6%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/CodeResources to device
[  7%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x.png to device
[  8%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[  8%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@3x.png to device
[  9%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[ 10%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x.png to device
[ 10%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[ 11%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@3x.png to device
[ 12%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[ 12%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@2x.png to device
[ 13%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@3x.png to device
[ 14%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[ 14%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[ 15%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[ 16%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/embedded.mobileprovision to device
[ 17%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/ to device
[ 17%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/ to device
[ 18%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/ to device
[ 19%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/CodeResources to device
[ 19%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/app.flx to device
[ 21%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/FlutterApplication to device
[ 29%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/Info.plist to device
[ 29%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/icudtl.dat to device
[ 34%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Info.plist to device
[ 34%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/ to device
[ 35%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[ 36%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/Info.plist to device
[ 36%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[ 37%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/PkgInfo to device
[ 38%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Runner to device
[ 49%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/ServiceDefinitions.json to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2016-04-19 13:11:46.177 ios-deploy[27388:2809344] [ !! ] Error 0xe8008015: ·Qyˇˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install ios/.generated/build/Release-iphoneos/Runner.app on b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb.
Error running application on iPad.
```

Output running via command line:

```
~/flutter/map $ flutter -d iPad run
Uploading .generated package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - Error occurred: PackageInspectionFailed
Running lib/main.dart on iPad...
[....] Waiting for iOS device to be connected
[....] Using J81AP 'iPad' (b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb).
------ Install phase ------
[  0%] Found J81AP 'iPad' (b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb) connected through USB, beginning install
[  5%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/ to device
[  5%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[  6%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/ to device
[  6%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/CodeResources to device
[  7%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x.png to device
[  8%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[  8%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@3x.png to device
[  9%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[ 10%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x.png to device
[ 10%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[ 11%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@3x.png to device
[ 12%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[ 12%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@2x.png to device
[ 13%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@3x.png to device
[ 14%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[ 14%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[ 15%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[ 16%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/embedded.mobileprovision to device
[ 17%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/ to device
[ 17%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/ to device
[ 18%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/ to device
[ 19%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/CodeResources to device
[ 19%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/app.flx to device
[ 21%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/FlutterApplication to device
[ 29%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/Info.plist to device
[ 29%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/icudtl.dat to device
[ 34%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Info.plist to device
[ 34%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/ to device
[ 35%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[ 36%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/Info.plist to device
[ 36%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[ 37%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/PkgInfo to device
[ 38%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/Runner to device
[ 49%] Copying /Users/sethladd/flutter/map/ios/.generated/build/Release-iphoneos/Runner.app/ServiceDefinitions.json to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2016-04-19 14:53:52.618 ios-deploy[46157:2890534] [ !! ] Error 0xe8008015: ·
                                                                            Qyˇˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install ios/.generated/build/Release-iphoneos/Runner.app on b0f7081e6f02d7e3b573bf6afcb64e61ed8b86bb.
Error running application on iPad.
```

**Comment by sethladd** [comment] 2016-04-19 20:18
XCode is telling me "Could not find Developer Disk Image" when I try the Run button in XCode. My iPad is running iOS 9.3 and the Deployment Target in Xcode is set to 8.0. I think the Deployment Target is the default for newly created flutter apps.

**Comment by chinmaygarde** [comment] 2016-05-09 22:29
Looks like a code signing issue. Duplicate of https://github.com/flutter/flutter/issues/2952

**Closed by chinmaygarde** 2016-05-09 22:29 UTC
Labels: affects: tools, ⌺‬ platform-ios, ⚠ bug
