### ISSUE TITLE
The engine -> framework roller is >67 commits behind

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#62139] opened 2020-07-23 16:44 UTC
https://github.com/flutter/flutter/pull/62080 is the current roll PR and it doesn't appear to be going well.

Assigning @flar who is the current engine sheriff, and @jason-simmons who is shepherding a manual Dart VM roll.

**Comment by a-siva** [comment] 2020-07-23 17:04
Can the engine->framework auto roller be stopped, the framework and engine trees closed until this is resolved ?

**Comment by zanderso** [comment] 2020-07-23 17:22
This will probably be blocked on https://github.com/flutter/flutter/issues/62146

**Comment by zanderso** [comment] 2020-07-23 17:24
I've switched the engine autoroller to dry-run. I don't believe we have the ability to close the engine tree. Maybe @tvolkert knows if we can.

**Comment by tvolkert** [comment] 2020-07-23 17:29
We don't have the ability to truly close either tree - only by asking on chat channels / email for people to hold off on committing.

**Comment by zanderso** [comment] 2020-07-23 17:42
The engine tree is also red on https://github.com/flutter/flutter/issues/62146, so no one will be landing anything until that is resolved.

**Comment by jason-simmons** [comment] 2020-07-23 17:43
The Dart SDK associated with the pending engine roll PR (https://github.com/flutter/flutter/pull/62080) is version `2.9.0-21.0.dev.flutter-a3815b6590`.  So flutter_tools can resolve its dependencies and build without causing the problem seen in https://github.com/flutter/flutter/issues/62146.

However, the roll is failing because some framework/tooling tests are timing out.  I can reproduce one of the errors by running:
* cd `dev/devicelab`
* ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t smoke_test_success

This will show a series of VM service errors and will fail to complete.  Currently investigating why this started happening.

**Comment by jason-simmons** [comment] 2020-07-23 18:05
Bisected the start of the `smoke_test_success` failure to a Dart->engine roll (https://github.com/flutter/engine/commit/183dccecd2765e9a66b1d8fa1250ffd096d6c21c)

**Comment by zanderso** [comment] 2020-07-23 18:20
@jason-simmons Let's prepare a revert of that roll, notify the Dart team, and disable the auto-roller.

**Comment by jason-simmons** [comment] 2020-07-23 19:50
It looks like the test failure started with https://github.com/dart-lang/sdk/commit/157ebfe50f399c59a20d603acdf5143ceaa4cccf in the Dart SDK

@bkonyi

**Comment by bkonyi** [comment] 2020-07-23 20:00
A workaround for these failures is to pass `--disable-dart-dev` to the `dart` process. I'll take a look into the actual failure.

**Comment by flar** [comment] 2020-07-23 22:14
It looks like our LWE builds are failing due to an analyzer sdk mismatch.

**Comment by zanderso** [comment] 2020-07-23 22:53
@flar The builder may have pulled and cached the dev tag for 2.10. @christopherfujino might know whether that's the case here.

**Comment by zanderso** [comment] 2020-07-24 22:50
The engine has rolled forward. The engine tree still has some redness, but that is being tracked separately, so I will close this.

**Comment by christopherfujino** [comment] 2020-07-24 23:01
> The engine has rolled forward. The engine tree still has some redness, but that is being tracked separately, so I will close this.

Isn't this tracking the engine -> framework roll? Isn't that still blocked? https://github.com/flutter/flutter/blob/master/bin/internal/engine.version

**Comment by zanderso** [comment] 2020-07-24 23:04
Ah, right. It is still blocked. Let's leave this open until we can restart the auto-roller. Thanks!

**Comment by chinmaygarde** [comment] 2020-07-27 17:34
Triage: This is complicated by the 2.10 Dart roll and a lot of folks are already on this.

**Comment by Hixie** [comment] 2020-07-28 22:39
What's the status here?

**Comment by christopherfujino** [comment] 2020-07-28 22:43
The engine roller has been re-enabled. Closing the issue.

**Closed by christopherfujino** 2020-07-28 22:43 UTC
Labels: P0, engine
