### ISSUE TITLE
AppBar in Material3 ignores ThemeData

### ISSUE THREAD

**Issue by elliotrtd** [flutter/flutter#110763] opened 2022-09-01 07:56 UTC
With Flutter 3.3 now supporting the AppBar and IconButtons for Material 3 it seems the appbar now ignores the app default theme data. 

Firstly - the AppBar color no longer uses the primaryswatch color

Secondly - I use IconThemeData in my AppBarTheme to change the color of the back button, but this is also ignored

It's possible to define the AppBar color within the AppBar (I define this as a custom class), but to solve the back button I had to completely override the leading with a custom widget and then also only show this on pages where we CAN pop. 

## Steps to Reproduce

In MaterialApp ThemeData define primary swatch color and also add AppBarTheme.

Set useMaterial3 : true

define IconThemeData for the AppBarTheme with a color other than black. 

Code sample below

**Expected results:** 

- AppBar should be the color of the primaryswatch
- BackButton on subsequent pages should use the color defined in the IconThemeData (as is true in 3.0.5)

**Actual results:** 

- AppBar is white
- BackButton is always black when useMaterial3 is true

**Screenshots:**
| useMaterial3 = true |  useMaterial3 = false |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/43793032/187861594-dd3b7346-2fa5-40e9-87f4-0fe82c529430.png" /> | <img src="https://user-images.githubusercontent.com/43793032/187861890-038e57d4-cbca-4f58-ba67-b85e27f9faef.png" /> |

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        appBarTheme: AppBarTheme(
            iconTheme: IconThemeData(
          color: Colors.orange,
        )),
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text("Go to next page"),
          onPressed: () {
            Navigator.push(context, MaterialPageRoute(builder: (BuildContext context) {
              return Scaffold(
                appBar: AppBar(
                  title: Text(widget.title),
                ),
                body: Center(
                  child: Text("Back Button is not orange"),
                ),
              );
            }));
          },
        ),
      ),
    );
  }
}

```

</details>

**Comment by danagbemava-nc** [comment] 2022-09-01 13:10
Hi @elliotrtd, this issue appears to have been fixed on the master channel as I cannot reproduce this there. See the screenshots below. 

<details>
<summary>screenshots</summary>

| stable | master |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/187921503-ebabfc4a-0c71-4f45-8c95-0e6b7a0fa3dc.png" /> | <img src="https://user-images.githubusercontent.com/88313112/187921494-e7119c20-a875-4063-8c24-c6cb32572613.png" /> |

</details>

Per our triage policy, I'll be closing this as it does not reproduce on the master channel. 

If you are able to reproduce this on the master channel, kindly leave a comment below and I will reopen this. 


Thank you

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2608, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2608 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 759d0e1b20 (62 minutes ago), 2022-08-31 23:07:20 -0700
    • Engine revision b149eea0a3
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by danagbemava-nc** 2022-09-01 13:10 UTC
Labels: in triage

**Comment by abhishek-joflee** [comment] 2022-09-13 07:11
When will the new version will release, with this fix??
