### ISSUE TITLE
Could not find io.flutter:flutter_embedding_profile

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#63874] opened 2020-08-16 01:59 UTC
## Steps to Reproduce

I use manual https://flutter.dev/docs/development/add-to-app/android/project-setup#add-the-flutter-module-as-a-dependency
And after last step after edit app/build.gradle I run project and get

`
![image](https://user-images.githubusercontent.com/1562329/90324857-a7a88780-df7c-11ea-9a50-2f23a03a90b0.png)

`

## Logs

if I comment 57 line debugImplementation 'com.example.my_flutter:flutter_debug:1.0'  project will start without problem.

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)

• No issues found!

```

**Comment by Abhishek01039** [comment] 2020-08-16 08:58
Duplicate of https://github.com/flutter/flutter/issues/41281

**Comment by markusaksli-nc** [comment] 2020-08-17 11:25
Hi @Alexufo 
Could you see if https://github.com/flutter/flutter/issues/41281#issuecomment-568154647 or any of the other mentioned solutions in #41281 fix the issue for you?
Thank you

**Comment by Alexufo** [comment] 2020-08-17 13:50
Deleted gradle folder in project and in the module folder. gradlew cleanBuildCache  for both - the same problem  :-(

**Comment by markusaksli-nc** [comment] 2020-08-17 14:08
Alright, then I'm going to close this as a likely duplicate of https://github.com/flutter/flutter/issues/39707. 

Follow up on that issue for updates on this.

**Closed by markusaksli-nc** 2020-08-17 14:08 UTC
Labels: in triage
