### ISSUE TITLE
Caret performance is poor, high GPU time per frame.

### ISSUE THREAD

**Issue by sommestad** [flutter/flutter#24522] opened 2018-11-19 15:22 UTC
When writing to TextFields in my Flutter application, I am seeing serious drops in performance while typing. The frame rate goes from 60 -> 25 fps (and red bars). 

Oddly enough, if using a single-line textfield and typing "outside" the screen, the frame rate goes back up to ~60 (with no red bars in perf monitor). (Could also be related to number of characters, but that seems less likely given my observations).

From what I can see, the surrounding widgets does not seem to have any substantial impact, i.e. it happens on both simpler and more complex screens.

The sluggish performance is even more obvious when using the label decorations that comes with material TextFields.
However, I am seeing the same on both Cupertino and Material textfields. I have also tried with very "clean" textfields, i.e. without any text controllers or similar attached to it.

Is this expected? Or could there be any issues with the TextField widget?
(I do not see any behavior like this in native or even web applications I've built.)

## Steps to Reproduce

1. Create a `StatefulWidget` and add a `TextField` to it. In my case, the hierarchy is ~3-4 levels deep before appending the `TextField`. 
2. Start typing in the `TextField` (I've tested both on iOS 8 device and on iPhone 7 simulator).
3. To see differences in performance; make the textfield single line with a fixed width.

## Logs

```
Launching lib/main.dart on iPhone 7 in debug mode...
Starting Xcode build...
Xcode build done.                                           10,2s
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:

let db = Firestore.firestore()
let settings = db.settings
settings.areTimestampsInSnapshotsEnabled = true
db.settings = settings

With this change, timestamps stored in Cloud Firestore will be read back as Firebase Timestamp objects instead of as system Date objects. So you will also need to update code expecting a Date to instead expect a Timestamp. For example:

// old:
let date: Date = documentSnapshot.get("created_at") as! Date
// new:
let timestamp: Timestamp = documentSnapshot.get("created_at") as! Timestamp
let date: Date = timestamp.dateValue()

Please audit all existing usages of Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do<…>
Syncing files to device iPhone 7...
[VERBOSE-2:FlutterObservatoryPublisher.mm(145)] FlutterObservatoryPublisher is ready!

```

```
Analyzing my_app...                                         

   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/screens/account.dart:3:8 • unused_import
   info • Unused import: 'package:my_app/screens/widgets/credits.dart' • lib/screens/create_thread.dart:4:8 • unused_import
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement • lib/screens/login.dart:166:3 • missing_return
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/screens/thread.dart:17:7 • must_be_immutable
   info • Avoid using braces in interpolation when not needed • lib/screens/thread.dart:178:32 • unnecessary_brace_in_string_interps


```

```
[✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.14.1 18B75, locale sv-SE)
    • Flutter version 0.11.3 at /Users/my_user/Dev/Libs/flutter
    • Framework revision 72bf075e8d (9 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/my_user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616

[✓] Connected device (2 available)
    • Iphone S • <obfuscated> • ios • iOS 12.1
    • iPhone 7 • <obfuscated>     • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-12 14:05
Can you please add a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by sommestad** [comment] 2018-12-21 07:32
Sure thing. I stripped away a lot from an actual class, to try and make sure I keep things intact:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class FormPage extends StatefulWidget {

  const FormPage({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => _CreateThreadState();
}

class _CreateThreadState extends State<FormPage> {
  final titleTextController = TextEditingController();
  final titleFocus = FocusNode();
  final messageTextController = TextEditingController();
  final messageFocus = FocusNode();
  final bazTextController = TextEditingController();
  final bazFocus = FocusNode();

  bool _isLoading = false;

  _CreateThreadState();

  @override
  void dispose() {
    titleTextController.dispose();
    messageTextController.dispose();
    bazTextController.dispose();
    titleFocus.dispose();
    messageFocus.dispose();
    bazFocus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: Container(
        child: SingleChildScrollView(
          padding: EdgeInsets.all(20.0),
          child: Column(
            children: <Widget>[
              Container(
                child: buildFirst(context),
                margin: EdgeInsets.only(bottom: 20.0),
              ),
              Container(
                child: buildSecond(),
                margin: EdgeInsets.only(bottom: 20.0),
              ),
              Container(
                child: buildThird(),
                margin: EdgeInsets.only(bottom: 20.0),
              ),
              buildSubmitButton(),
            ],
          ),
        ),
      ),
    );
  }

  Widget buildFirst(BuildContext context) {
    return TextField(
      controller: titleTextController,
      focusNode: titleFocus,
      maxLines: 1,
      textCapitalization: TextCapitalization.sentences,
      keyboardType: TextInputType.text,
      decoration: InputDecoration(
        labelText: 'Thing',
      ),
      onSubmitted: (value) {
        FocusScope.of(context).requestFocus(messageFocus);
      },
      textInputAction: TextInputAction.next,
      enabled: !_isLoading,
    );
  }

  Widget buildSecond() {
    return TextField(
      controller: messageTextController,
      focusNode: messageFocus,
      maxLines: null,
      textCapitalization: TextCapitalization.sentences,
      keyboardType: TextInputType.multiline,
      decoration: InputDecoration(
        labelText: 'Other thing',
      ),
      enabled: !_isLoading,
    );
  }

  Widget buildSubmitButton() {
    if (_isLoading) {
      return Container(
        padding: EdgeInsets.all(10.0),
        child: SizedBox(
          height: 20.0,
          width: 20.0,
          child: CircularProgressIndicator(),
        ),
      );
    }
    return Container(
      width: double.infinity,
      child: FlatButton(
        onPressed: () => {},
        child: Text("Button"),
      ),
    );
  }

  Widget buildThird() {
    var placeholder = "";
    return TextField(
      controller: bazTextController,
      focusNode: bazFocus,
      maxLines: 1,
      keyboardType: TextInputType.number,
      decoration: InputDecoration(
          labelText: 'Baz',
          helperText: 'Baz',
          hintText: placeholder
      ),
      enabled: !_isLoading,
    );
  }
}
```

I've tried ☝️ on device and am seeing the same behavior; sluggish text input (at ~30 fps) with plenty of red bars. One text gets longer or at least goes beyond the width of the screen, it's up to 60 fps.

**Comment by zoechi** [comment] 2018-12-21 07:46
Looks similar to #14242

**Comment by dougsatch** [comment] 2019-04-19 14:28
I've found the problem - textCapitalization: TextCapitalization.sentences

With that in place, the performance is awful (not always, but most of the time, and when the text field is empty so its capitalizing the first letter). When I remove it, all is good.

**Comment by dougsatch** [comment] 2019-05-17 13:50
Looks like this is related https://github.com/flutter/flutter/issues/31138

**Comment by StephanCassel** [comment] 2019-05-22 08:14
I have removed all my  textCapitalization: TextCapitalization.sentences and it seems to be better for a while but heavy TextField lags are frequently showing up again. Yesterday I hade a 10+ sec hang on my iPad pro.
Many users, using my app, say that they have difficulty to enter text. Another user was not able to Sign-up on a iPhone 6.
This issue has become very serious and I really hope the problem is solved very soon. Not only serious for me but for the Flutter community in general

**Comment by monajafi** [comment] 2019-06-04 09:00
I've opened an issue #33833 about textField widget high cpu usage in iOS simulator maybe that affects the app performance too

**Comment by rvhamed** [comment] 2019-11-04 16:24
I have same issue when the TextFormField widget is focused and its cursor is blinking.
![flutter_issue](https://user-images.githubusercontent.com/29680697/68137821-d6e58f00-ff3c-11e9-89a0-6695df9aaa38.png)

**Comment by liyuqian** [comment] 2019-11-21 00:53
CC our text experts @GaryQian and @jason-simmons

**Comment by GaryQian** [comment] 2019-11-22 00:41
Tried this in Flutter Gallery, am indeed seeing a slow frame whenever the caret is drawn/not drawn. I will double check the caching to ensure we are not doing duplicate work and using the cached caret positions properly

**Comment by GaryQian** [comment] 2019-12-10 21:28
Should be fixed by https://github.com/flutter/flutter/pull/46720

We were passing in a zero rect caret prototype, causing the caching system to be marked dirty on each caret draw.

**Comment by GaryQian** [comment] 2019-12-12 23:32
Another textfield performance bug, linking for reference: https://github.com/flutter/flutter/issues/33833

**Closed** 2019-12-19 21:46 UTC
Labels: a: text input, customer: crowd, engine, framework, severe: performance
