### ISSUE TITLE
<elided> leaking memory when playing a Youtube Video

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#44444] opened 2019-11-08 15:14 UTC
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=40877. Conversation should occur there.

/cc @cbracken @iskakaushik.

**Comment by kf6gpe** [comment] 2019-11-08 17:44
Escalated to P1 in the Fuchsia issue tracker; escalating here.

**Comment by cbracken** [comment] 2019-11-13 00:23
Closing this as it's no longer assigned to anyone on the team. If and when it's reassigned to us we can open a new issue.

**Comment by fmeawad** [comment] 2019-11-13 19:02
We are noticing issues with flutter's garbage collection related to this issue that @rmacnak-google is looking at. Should we reopen this issue or create a new one?

**Comment by kf6gpe** [comment] 2019-11-13 19:27
Let's reopen this one, if it's on the same monorail bug. What are you seeing?

**Comment by Hixie** [comment] 2019-11-27 00:29
Let's create a new bug and clearly state what's going on, what the steps to reproduce are, let's assign it according to who is working on it, etc. Right now with this bug I've no idea what the problem is that we should be solving.

**Closed by Hixie** 2019-11-27 00:29 UTC
Labels: customer: fuchsia, dependency: dart, engine, plugin, severe: customer critical
