### ISSUE TITLE
Undefined name 'visibleForTesting' used as an annotation

### ISSUE THREAD

**Issue by egorges** [flutter/flutter#31103] opened 2019-04-16 02:42 UTC
![image](https://user-images.githubusercontent.com/47680522/56178065-2f703180-5fd7-11e9-9b6b-4cdfa9db7f4a.png)

VSCode is reporting several problems on standard firebase_app.dart

Apparently the app is still working perfectly. I can't precise when this happened, but seem to have happened after run: flutter --profile

Thanks in advance.

**Comment by egorges** [comment] 2019-04-20 21:06
Workaround: changed firebase_core.dart.

Before:
`part 'src/firebase_app.dart';
part 'src/firebase_options.dart';`

Now:
`part 'src/firebase_options.dart';
part 'src/firebase_app.dart';`

**Comment by escamoteur** [comment] 2019-10-01 19:46
Hi, sorry for the late reply, I would like to ask does this problem still exist?

**Comment by iapicca** [comment] 2019-11-08 09:15
Hi @egorges 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:15 UTC
Labels: waiting for customer response
