### ISSUE TITLE
[flutter_plugin_android_lifecycle] could not resolve ... gradle:4.3.1., after adding Google Maps plugin

### ISSUE THREAD

**Issue by Kartmax13** [flutter/flutter#132046] opened 2023-08-07 11:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Trying to build a cross platform connected device Google Maps enabled App using flutter framework on Android Studio Flaming 2022.2.1 Patch 2, without success. The flutter run works seemlessly until device dependency google_maps_flutter: ^2.4.0 is used under pubspec.yaml. Also after added this in pubspec.yaml `flutter_plugin_android_lifecycle: ^2.0.15`, the issue is still here.
This is the final look of this area in pubspec.yaml.

`dependencies:`
`  http: ^0.13.6flutter:`
`    sdk: flutter`
`  flutter_localizations:`
`    sdk: flutter`
`  google_maps_flutter: ^2.4.0`
`  google_fonts: ^4.0.4`
`  flutter_plugin_android_lifecycle: ^2.0.15`

I have made this additional steps, without find a solution:

### Step 1
Changed on <myapp>/android/gradle/wrapper/gradle-wrapper.properties this line 
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip `
that was 
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.3.1-bin.zip`
that can be changed also from Project Structure -> Gradle Version (not Plugin version).

### Step 2
Also deleting both .gradle directory, module and project level... and invalidating cache, nothing to do. I'm quite sure that flutter_plugin_android_lifecycle: ^2.0.15 is in origin corrupted, or something like this. – 

### Expected results

iOS build is every time ok, also Android was perfect before Google Maps was added.
Please note that I have a strange issue, with my system PATH. Doctor tell me that I have an Issue, but the PATH is perfect and built for iOS is ok. I will write another post for this strange issue.

Coming back to this question, I searched for solutions over the web, hoping someone can help me to find a way.
I have also posted the issue on stackoverflow here: [https://stackoverflow.com/questions/76837737/android-studio-flamingo-android-lifecycle-issue-with-android-devices-after-addi]

### Actual results

After adding Google Maps in my Flutter project, I have no problem with iOS, but with Android I have got the issue:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_plugin_android_lifecycle'.
> Could not resolve all files for configuration ':flutter_plugin_android_lifecycle:classpath'.
   > Could not find com.android.tools.build:gradle:4.3.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.3.1/gradle-4.3.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/4.3.1/gradle-4.3.1.pom
     Required by:
         project :flutter_plugin_android_lifecycle
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_plugin_android_lifecycle' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_plugin_android_lifecycle' of type org.gradle.api.Project.

### Code sample

<details><summary>android/build.gradle. As you can see I have added both [ mavenCentral() ] and [ maven { url "https://maven.google.com" } ]

</summary>

```dart
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://maven.google.com" }

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        //implementation 'com.google.gms:google-services:3.0.0'

    }

}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://maven.google.com" }

    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

</details>

### Screenshots or Video

<details>
<summary>This is Adroid Project Structure settings</summary>

https://i.stack.imgur.com/gH8F0.png

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale it-IT)
    • Flutter version 3.10.6 on channel stable at /Users/maxmac/Development/flutter
    ! Warning: `flutter` on your path resolves to /Users/MaxMac/Development/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/maxmac/Development/flutter.
      Consider adding /Users/maxmac/Development/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/MaxMac/Development/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/maxmac/Development/flutter. Consider
      adding /Users/maxmac/Development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/maxmac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 14 (API 34) (emulator)
    • iPhone 14 (mobile)           • 387BA0EA-FD06-4ABE-82E3-40FAE3AEBEDE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2023-08-08 07:51
I can't reproduce this issue on my side. I see you have solved this issue yourself (in your SO question). It seems the issue is caused by a cached `flutter_plugin_android_lifecycle` version. Closing this as solved.

**Closed by huycozy** 2023-08-08 07:51 UTC
Labels: in triage

**Comment by Kartmax13** [comment] 2023-08-08 11:21
@huycozy thanks for your message. If you think the issue was for a cached version, I will be happy to know te source of this... anyway, this problem could be useful to think about a something like a check-up for wrong cached plugin, because ad you can read, there are no way to understood that the problem was this.
