### ISSUE TITLE
recipe infra failure: retcode: -9

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#68322] opened 2020-10-16 18:43 UTC
Both engine and framework LUCI tasks have been hitting `recipe infra failure: retcode: -9` for weeks.

Related failed builds:
Egnine:
[Step('OS info') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7284)
[recipe infra failure: Infra Failure: Step('Ensure checkout cache') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7233)
[recipe infra failure: Infra Failure: Step('reset XCode') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7241)
[Step('Delete mac deriveddata') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7315)
Framework:
[recipe infra failure: Infra Failure: Step('Checkout flutter/flutter.git fetch') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test/404)
[recipe infra failure: Infra Failure: Step('reset XCode') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_host_with_custom_build_test/402)

## Links
- [LUCI issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1148035)
- [vpython issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1176980)

**Comment by keyonghan** [comment] 2020-10-16 18:51
OOM might cause the failure. https://github.com/flutter/flutter/issues/67934 to collect OS related info in both before and after task execution.
However in this build https://ci.chromium.org/p/flutter/builders/prod/Mac%20plugin_test/403, no suspicious leaked processes or high cpu/mem usage when hitting the error.

**Comment by chinmaygarde** [comment] 2020-10-16 20:09
Setting priority to match the duplicate that was closed. This failure is blocking rolls that then unblock the sound null-safety effort.

**Comment by keyonghan** [comment] 2020-10-16 20:21
Manually triggered `Mac Android Debug Engine` to open the tree for now.

**Comment by keyonghan** [comment] 2020-10-19 17:50
fuchsia builds hit this error as well on Catalina. Still triaging. Nathan from fuchsia side is looking too.

**Comment by chinmaygarde** [comment] 2020-10-20 07:29
From triage of user reported flakes on presubmits, the following instances were reported:
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866439818177248288/+/steps/OS_info/0/logs/execution_details/0
* https://ci.chromium.org/p/flutter/builders/prod/Mac%20Android%20Debug%20Engine/7271

Not sure if this is related but @zanderso mentioned this could be related to leaking processes on the bots.

**Comment by keyonghan** [comment] 2020-10-20 16:54
> Not sure if this is related but @zanderso mentioned this could be related to leaking processes on the bots.

https://github.com/flutter/flutter/issues/68137 is been worked on for leaking processes.

**Comment by keyonghan** [comment] 2020-10-20 22:58
We haven't diagnosed what exactly causes this error. But this happened only on mac 10.15.6, and one possible trial is to upgrade bots to 10.15.7.
Based on recent 30 commit runs, we haven't hit this error from Engine repo, but once from framework.
Keeps monitoring/triaging.

**Comment by keyonghan** [comment] 2020-10-22 17:45
Filed [1141517](https://bugs.chromium.org/p/chromium/issues/detail?id=1141517) to try upgrading 5 bots to 10.15.7 to further monitor/triage.

**Comment by keyonghan** [comment] 2020-10-22 23:04
5 bots are finished upgrading. Will keep monitoring.

**Comment by keyonghan** [comment] 2020-10-22 23:07
Most likely this is related to catalina 10.15.6 leaking memory and killing the processes, and not related to flutter infra. We don't know what can be done to fix this issue. Have asked help from luci/chrome side, but still no clear answer. Will monitor the bots upgrading to see if it helps.

**Comment by chinmaygarde** [comment] 2020-10-23 01:21
Thanks for the investigation. The frequency of this is significantly lower today and this is not blocking the tree. I am lowering the priority. Will readjust on an ongoing basis.

**Comment by keyonghan** [comment] 2020-10-29 18:09
We now have 16 10.15.7 bots  available, and still no -9 error on these bots yet.
Will keep monitoring. If still true, will update the remaining 10.15.6 ones.

**Comment by zanderso** [comment] 2020-10-29 18:21
Is this a different one? https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/5574

**Comment by keyonghan** [comment] 2020-10-29 18:39
It's the same. We have seen this before as well. It happened on bot 801-m9, which is a 10.15.6 bot.

**Comment by keyonghan** [comment] 2020-10-29 21:41
New failures are captured in 10.15.7 bots as well..
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7493
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7490
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/5576

**Comment by zanderso** [comment] 2020-10-30 23:18
This is still happening quite a lot, so I am escalating back to P0

**Comment by zanderso** [comment] 2020-10-30 23:20
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7528
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/5611

**Comment by chinmaygarde** [comment] 2020-11-04 17:54
https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/10338
https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/10340

**Comment by godofredoc** [comment] 2020-11-06 02:40
Updating to 10.15.7 didn't fix the problem, here are two more failures that happened on 11/05:

* https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7599
* https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/5674

**Comment by godofredoc** [comment] 2020-11-06 02:45
Let's expand the os info to print the entire list of tasks instead of just the top list.

**Comment by keyonghan** [comment] 2020-11-11 21:53
https://flutter-review.googlesource.com/c/recipes/+/8586 to collect all top process list.
https://bugs.chromium.org/p/chromium/issues/detail?id=1148035 to ask help from chromium side.

**Comment by kf6gpe** [comment] 2020-11-19 22:00
Gentle ping --- @keyonghan --- this is still open as a P0. Are we working it at that level of alarm? Or should we re-evaluate importance and priority?

**Comment by keyonghan** [comment] 2020-11-19 22:09
Sorry should have updated earlier. I don't think we are working on this issue at a P0 level.
We are still not sure about the root cause yet, and may not find one in the near future.
Marking as p2 as this is still happening frequently.

**Comment by Piinks** [comment] 2020-12-03 00:05
This reproduced in

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20gradle_plugin_light_apk_test/900/overview

and 

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20gradle_plugin_bundle_test/898/overview

**Comment by godofredoc** [comment] 2020-12-03 00:08
We do have more info about this. The problem is the mac catalina malware scanner detecting python 2.7 as malware and killing it.

**Comment by godofredoc** [comment] 2020-12-03 00:09
We don't know how to prevent that yet. @jmagman any suggestions about disabling the malware scanner or adding python to the allow list?

**Comment by jmagman** [comment] 2020-12-03 00:19
I didn't know such a thing existed.  Do we know what process is killing it?  Should be able to tell from the logs (if you take a sysdiagnose and give me an approximate timestamp I may be able to tell).

How is the python script run and launched?  Is it a LaunchAgent?

**Comment by godofredoc** [comment] 2020-12-03 01:19
It is run using LaunchAgent:

````
2020-11-24 13:22:45.743135-0800 0x2bf5     Default     0x0                  0      0    kernel: (AppleSystemPolicy) initiating malware scan (activeRulesVersion: 16468102647681047563 lastScanVersion: 16468102647681047563 chgtime: 1606252965 lastFileScanTime: 1606252959 pid: 859 info_path: /opt/s/w/ir/cache/vpython/69c089/bin/python proc_path: /opt/s/w/ir/cache/vpython/69c089/bin/python
2020-11-24 13:22:45.780208-0800 0x2bf8     Default     0x0                  358    0    rapportd: (CoreUtils) [com.apple.CoreUtils:CUSystemMonitor] Rotating identifier changed timer: 20:D8:AF:B1:D4:B7 -> 89:7A:68:16:04:7C
2020-11-24 13:22:45.780239-0800 0xbbb      Default     0x0                  358    0    rapportd: (CoreUtils) [com.apple.rapport:RPRemoteDisplayDaemon] Bluetooth address changed: 89:7A:68:16:04:7C
2020-11-24 13:22:45.780251-0800 0xbbb      Default     0x0                  358    0    rapportd: (CoreUtils) [com.apple.rapport:RPRemoteDisplayDaemon] Local device changed: ID 69DE639C-9652-4CC6-BDF4-D0BD06E232FC, PI 89:7A:68:16:04:7C, Md 'Macmini8,1'
2020-11-24 13:22:45.857721-0800 0x2bc9     Error       0x0                  153    0    syspolicyd: (libsqlite3.dylib) [com.apple.libsqlite3:logging-persist] cannot open file at line 43353 of [378230ae7f]
2020-11-24 13:22:45.857723-0800 0x2bc9     Error       0x0                  153    0    syspolicyd: (libsqlite3.dylib) [com.apple.libsqlite3:logging-persist] os_unix.c:43353: (2) open(/var/db/DetachedSignatures) - No such file or directory
2020-11-24 13:22:45.922254-0800 0x2bf9     Default     0x0                  0      0    kernel: (AppleSystemPolicy) initiating malware scan (activeRulesVersion: 16468102647681047563 lastScanVersion: 16468102647681047563 chgtime: 1606252965 lastFileScanTime: 1605685744 pid: 887 info_path: /opt/s/w/ir/cache/vpython/a95c68/bin/python2.7 proc_path: /opt/s/w/ir/cache/vpython/a95c68/bin/python2.7
2020-11-24 13:22:45.922383-0800 0x2bc9     Error       0x0                  153    0    syspolicyd: Unable (errno: 2) to read file at <private> for pid: 887 process path: <private> library path: (null)
2020-11-24 13:22:45.922400-0800 0x2bc9     Error       0x0                  153    0    syspolicyd: Terminating process due to Malware rejection: 887, <private>
2020-11-24 13:22:45.922411-0800 0x2bc9     Default     0x0                  0      0    kernel: build_userspace_exit_reason: illegal flags passed from userspace (some masked off) 0x141, ns: 9, code 0x8
2020-11-24 13:22:45.922440-0800 0x2bf9     Default     0x0                  0      0    kernel: (AppleSystemPolicy) Sleep interrupted, signal 0x100
2020-11-24 13:22:45.922452-0800 0x2bf9     Default     0x0                  0      0    kernel: (AppleSystemPolicy) Security policy would not allow process: 887, /opt/s/w/ir/cache/vpython/a95c68/bin/python2.7
```

**Comment by jmagman** [comment] 2020-12-03 01:26
Has it been [quarantined by Gatekeeper](https://developer.apple.com/forums/thread/663456)?  What's the output of 
```
xattr /opt/s/w/ir/cache/vpython/a95c68/bin/python2.7
```

I know @christopherfujino had fun with this kind of problem when he was working on Catalina adoption:
https://github.com/christopherfujino/catalina-crasher-demo/blob/master/README.md
https://github.com/flutter/flutter/issues/33890
https://github.com/flutter/flutter/pull/38325

**Comment by pcsosinski** [comment] 2020-12-03 21:33
bumping to P1 as this continues to cause build issues

**Comment by godofredoc** [comment] 2020-12-07 18:43
@christopherfujino do you know how it was fixed for the flutter tools? @keyonghan any updates from the chromium team?

**Comment by jmagman** [comment] 2020-12-07 19:50
The fix to `flutter` tooling was very specific to `flutter upgrade` deleting the dart SDK:
https://github.com/flutter/flutter/pull/38325
```
The actual cause is calling the Flutter tool re-entrantly, which deletes the current Dart SDK (which the flutter upgrade process is using), after which any forked sub-processes would be killed (code -9 from the VersionCheckError message) by the macOS anti-malware software. See #33890 and dart-lang/sdk#37662 for more info.
```

**Comment by christopherfujino** [comment] 2020-12-07 20:09
> The fix to `flutter` tooling was very specific to `flutter upgrade` deleting the dart SDK:
> #38325
> 
> ```
> The actual cause is calling the Flutter tool re-entrantly, which deletes the current Dart SDK (which the flutter upgrade process is using), after which any forked sub-processes would be killed (code -9 from the VersionCheckError message) by the macOS anti-malware software. See #33890 and dart-lang/sdk#37662 for more info.
> ```

This is correct. Also from that PR description:

> This PR breaks up the flutter upgrade flow into two parts, the second half invoked re-entrantly via the hidden flag flutter upgrade --continue. This fixes the issue because after there are no steps following the re-entrant call of flutter upgrade --continue from the first dart process.

It appears that for the Flutter tool, it was spawning a sub-process from a Dart process in memory that was different from the file on disk. It seems plausible we're having a similar problem with vpython.

**Comment by jmagman** [comment] 2020-12-07 20:13
@godofredoc Can we confirm Gatekeeper is off?
```
spctl --status
```
should return `assessments disabled`

**Comment by christopherfujino** [comment] 2020-12-07 20:15
per luci users, gatekeeper is indeed off.

**Comment by keyonghan** [comment] 2020-12-08 00:23
Talked offline with Jonathan from chromium side. He suggested add `xattr` logging against vpython and any other files that are being launched by vypthon.
I will try adding log from recipe side, but vpython side logging may also needed.

**Comment by goderbauer** [comment] 2020-12-14 18:15
I noticed quite a few of these flakes during my gardening rotation, here's another example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20SDK%20Drone/31653/overview

**Comment by chunhtai** [comment] 2020-12-14 19:39
several other instances:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_lint_mac/1020/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20customer_testing/1011/overview

**Comment by keyonghan** [comment] 2020-12-23 23:49
Submitted https://flutter-review.googlesource.com/c/recipes/+/9541 to collect `xattr` info.

**Comment by bharat-1809** [comment] 2020-12-27 08:17
Another instance of the same issue: Mac module_host_with_custom_build_test fails
`recipe infra failure: Infra Failure: Step('Checkout flutter/flutter.git fetch') (retcode: -9)`
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_host_with_custom_build_test/2081/overview

**Comment by chinmaygarde** [comment] 2021-01-02 12:36
There is a significant uptick in instances of this issue now:
![Screen Shot 2021-01-02 at 4 34 48 AM](https://user-images.githubusercontent.com/44085/103457403-eaf95d80-4cb3-11eb-99ae-5c29fabf9f2a.png)

* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Android%20AOT%20Engine/8240/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Android%20Debug%20Engine/8246/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Android%20Debug%20Engine/8249/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/8278/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/6367/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/6360/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/6362/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/6363/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/8299/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Web%20Engine/3193/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Web%20Engine/3197/overview

**Comment by keyonghan** [comment] 2021-01-08 17:57
We are reaching out to Apple to see if anything can be done. At the same time, we are considering to implement auto-rerun for such failed builds as a workaround.

**Comment by godofredoc** [comment] 2021-01-08 18:48
What repro steps are we planning to share?

**Comment by keyonghan** [comment] 2021-01-08 19:17
Per discussion with Jonathan, we are checking in to see if it is possible to turn malware scan off. Haven't shared any steps to repro as it is not easy to repro locally.

**Comment by keyonghan** [comment] 2021-01-14 23:38
A workaround was submitted to auto rerun framework -9 builds: https://github.com/flutter/cocoon/pull/1054.
A PR to auto rerun engine builds to follow.

**Comment by keyonghan** [comment] 2021-01-21 20:08
At the same time, filed b/178107079 for Macops team

**Comment by godofredoc** [comment] 2021-01-26 18:25
@keyonghan can you please update progress in this issue?

**Comment by keyonghan** [comment] 2021-01-26 19:09
Workaround (auto rerun failed tasks):
- [ ] post-submit builds sdk repo
- [ ] pre-submit builds in sdk repo
- [ ] pre/post submit builds in engine repo

At the same time, we are looking for a more efficient way for rerun: currently it pulls/checks all build results every three minutes, which makes it difficult to scale. An alternative way to auto-rerun a task whenever its status changes will switch the logic from pull to push, making the process scalable.

 We also filed http://b/178107079 to `macops` team to see if any fix is possible.

**Comment by godofredoc** [comment] 2021-01-26 19:21
Let's prioritize retries in the engine postsubmit for the workaround and then let's focus on finding a fix for the problem. If the workaround is not straightforward we may not want to spend too much time on something will be removed as soon as the final fix is ready.

**Comment by keyonghan** [comment] 2021-02-01 23:55
Auto rerun has been implemented for sdk and engine post builders.

**Comment by iskakaushik** [comment] 2021-02-02 18:20
I still see some failures that are inline with this:

1. https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/8802
2. https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/3694
3. https://ci.chromium.org/p/flutter/builders/prod/Mac%20Android%20AOT%20Engine/8737


@keyonghan I would've expected the auto-rerun to have de-flaked them. Any idea why this might still be happening?

**Comment by zanderso** [comment] 2021-02-03 00:20
Sorry to pile on, but it looks like there are still some -9's on "Mac Web Engine" with no retries going: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine

**Comment by keyonghan** [comment] 2021-02-03 00:30
@iskakaushik After you reported the issue, I have triaged, and created a test version, which is running. Rerun seems work fine.
@zanderso For the builder Mac Web Engine, a rerun was triggered for commit `f94cf140c52c0cc3769d9281d5579e935886fbac`. We current are limiting the rerun number to be 1: https://devops-console-oss.corp.google.com/flutter/cocoon/+/master:app_dart/lib/src/datastore/cocoon_config.dart;l=220.

Do you want to increase the retry limit?

**Comment by godofredoc** [comment] 2021-02-03 00:32
The infra failures will still show up on that view and I think they will close the tree until the retry completes and passes. The current workaround only removes the need to manually retry.

**Comment by zanderso** [comment] 2021-02-03 00:32
@keyonghan Let's see how much mileage we get out of setting it to 2 =)

**Comment by godofredoc** [comment] 2021-02-08 19:24
The mitigation steps are not helping too much setting this one as P0 to root cause and fix.

**Comment by keyonghan** [comment] 2021-02-08 19:36
> The mitigation steps are not helping too much setting this one as P0 to root cause and fix.

I see both engine and framework auto rerun have been implemented and helped open the tree with a pass of the auto rerun. What do you mean by not helping too much? Do you have any example like keep the tree closed?

**Comment by chinmaygarde** [comment] 2021-02-08 20:03
This issue continues to show up frequently during presubmit runs. Are there plans to apply mitigations to presubmits as well?

For reference:
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857037138341048976/+/steps/Ensure_checkout_cache/0/logs/execution_details/0
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856545520623906592/+/steps/Ensure_checkout_cache/0/logs/execution_details/0

**Comment by godofredoc** [comment] 2021-02-08 20:03
> > The mitigation steps are not helping too much setting this one as P0 to root cause and fix.
> 
> @godofredoc I see both engine and framework auto rerun have been implemented and helped open the tree with a pass of the auto rerun. What do you mean by not helping too much? Do you have any example like keep the tree closed?

The retries is only a mitigation removing the need to manually retry on post-submit but the problem is still there. Presubmit workflows, rollers, and now devicelab are still facing the problem affecting the development workflows.

E.g. 63% of builders failed in the last run:

![image](https://user-images.githubusercontent.com/54371434/107274521-5cd86b80-6a05-11eb-9d43-7715324962e7.png)

All the purples here:

https://ci.chromium.org/p/flutter/g/devicelab_staging/console

**Comment by godofredoc** [comment] 2021-02-08 20:15
We have been spending most of the time on mitigating the issue and we have not made too much progress on root causing and fixing the real issue. With the mitigation for postsubmit I'd recommend that we change focus to replicating the issue and root causing the problem.

**Comment by godofredoc** [comment] 2021-02-08 22:03
@keyonghan can we try to correlate exit code -9 with quarantine events?

Events table structure:
```
~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 ".schema LSQuarantineEvent"
```

Events table data: 

```
/usr/bin/sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 "select * from LSQuarantineEvent"
```

To do the correlation we can use: 

* https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20complex_layout_ios__start_up/340
* https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9
* User swarming

Looking at the events from  2021-02-08 11:32 AM (PST) 2021-02-08 11:34 AM (PST)

**Comment by keyonghan** [comment] 2021-02-08 22:10
Will take a look.

People seem hitting exactly the same issue as us, and already filed in [apple forum](https://developer.apple.com/forums/thread/663456).

**Comment by keyonghan** [comment] 2021-02-08 22:42
Checked on mac9, seems no quarantine events are available:

```
/usr/bin/sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 "select * from LSQuarantineEvent"
Error: no such table: LSQuarantineEvent
```

```
du -hs ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2 
 0B	/Users/swarming/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2
```

**Comment by jmagman** [comment] 2021-02-09 00:48
What was the result of the xattr checks? I only see the execution details for steps like https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857037138341048976/+/steps/python_xattr_info/0/logs/execution_details/0 not the stdout.

**Comment by keyonghan** [comment] 2021-02-09 00:55
Right, there is no output info of command xattr.

**Comment by godofredoc** [comment] 2021-02-09 20:41
Here is another replication script: https://github.com/rust-lang/cargo/issues/7821#issuecomment-586093799

**Comment by jmagman** [comment] 2021-02-10 20:07
I just upgraded to Big Sur on my machine and I see vpython -9 kills running `gclient sync`, does all this come back to `vpython` being unsigned (is that what's being used to run the LUCI scripts?)
```
$ codesign -vvv --deep --strict  chromium/depot_tools/vpython
chromium/depot_tools/vpython: code object is not signed at all
```

**Comment by godofredoc** [comment] 2021-02-10 21:24
We have several variants of the problem:

1. vpython, git, etc not being signed. This affects developer laptops but don't affect luci bots because they have gatekeeper disabled.
2. vpython, git, python, etc being killed by malware scanner. This happens when a running binary is replaced on disk and fixed by using disabling SIP(disabling SIP is not an option for our bots).
3. dart, pub, flutter deps, xcrun being scheduled for a malware scan and actually starting the scan on a different task killing the subprocess running the binaries and reported as the binary/directory was not found. This is potentially happening because we are always using the same path for checkouts and downloads of binaries.

**Comment by godofredoc** [comment] 2021-02-17 02:37
For the engine:

* 36% of the failures are caused by xcode reset being killed
* 54% of the failures are cause by the vpython being killed.

We'll start by solving the vpython problem reinstalling the cipd package and putting it in front of the path.

**Comment by godofredoc** [comment] 2021-02-17 04:03
Actually the 36% failure rate attributed to xcode are not related to "xcode reset" but to depot_tools/autoninja and vpython/python

**Comment by christopherfujino** [comment] 2021-02-17 19:07
I upgraded vpython yesterday to pick up a bugfix that will hopefully fix this https://chrome-internal-review.googlesource.com/c/infradata/config/+/3620375. I am monitoring failures, but so far nothing...

**Comment by godofredoc** [comment] 2021-02-18 02:43
Also landed non deterministic python|vpython paths change  in the engine https://flutter-review.googlesource.com/c/recipes/+/10660. We may need to monitor the framework repository builders and if the error does not happen in a few days I can revert the recipes change.

**Comment by christopherfujino** [comment] 2021-02-18 17:38
Haven't seen this happen in the last 36 hours, so I'm optimistically closing this.

**Comment by christopherfujino** [comment] 2021-02-22 17:29
This hasn't happened since my vpython upgrade last week Thursday, February 18, so I'm closing this issue.

**Closed by christopherfujino** 2021-02-22 17:29 UTC
Labels: P0, passed first triage, passed secondary triage, team: infra
