### ISSUE TITLE
Proposal to add `label` property for `Placeholder` 

### ISSUE THREAD

**Issue by Arno-Z** [flutter/flutter#100204] opened 2022-03-16 10:07 UTC
PlaceHolder widgets ar very useful when designing the layout of an app. But when showing a layout to stakeholders they don't give much context, and are often in need clarification. 

## Proposal

Add an optional 'label' parameter to the PlaceHolder widget. When filled the Placeholder will show the label text at a convenient place. For example:

```
return const SingleChildScrollView(
      child: SizedBox(
        child: Placeholder(
          fallbackHeight: 2000,
          label: "ToDo List",
        ),
      ),
    );
```

**Comment by M97Chahboun** [comment] 2022-03-16 21:39
I will work on it

**Comment by M97Chahboun** [comment] 2022-03-17 17:29
@HansMuller 
Exactly, but its preferable to add Text Widget
Thank you.

**Comment by M97Chahboun** [comment] 2022-03-17 18:35
@HansMuller 
I need your help please,
When I want to pass test I get this error

```
Running "flutter pub get" in flutter...                         
Because every version of flutter_goldens from sdk depends on vector_math 2.1.1 and flutter depends on vector_math 2.1.2, flutter_goldens from sdk is forbidden.
So, because flutter depends on flutter_goldens from sdk, version solving failed.
pub get failed (1; So, because flutter depends on flutter_goldens from sdk, version solving failed.)
```
Thank you

**Comment by M97Chahboun** [comment] 2022-03-17 21:31
@HansMuller 
when I try to pass test for child widget I get an error, can you help me please,
I think this error caused by Text widget, require a default Directionality widget

**Test get error**
```
testWidgets('Placeholder child widget', (WidgetTester tester) async {   
    await tester.pumpWidget(const Placeholder());
    expect(find.text('Label'), findsNothing);
    await tester.pumpWidget(const Placeholder(child: Text('Label')));
    expect(find.text('Label'), findsOneWidget);
  });
```
**Test passed**
```
testWidgets('Placeholder child widget', (WidgetTester tester) async {   
    await tester.pumpWidget(const Placeholder());
    expect(find.text('Label'), findsNothing);
    await tester.pumpWidget(const Placeholder(child: Text('Label',textDirection: TextDirection.rtl,)));
    expect(find.text('Label'), findsOneWidget);
  });
```

**The error**

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Text("Label"):
No Directionality widget found.
RichText widgets require a Directionality widget ancestor.
The specific widget that could not find a Directionality ancestor was:
  RichText
The ownership chain for the affected widget is: "RichText ← Text ← CustomPaint ← LimitedBox ←
  Placeholder ← [root]"
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
top of your application widget tree. It determines the ambient reading direction and is used, for
example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.

When the exception was thrown, this was the stack:
#0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:283:7)
#1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:303:4)
#2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:5569:37)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5624:28)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6429:11)
...     Normal element mounting (7 frames)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#19     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#21     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#22     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1175:5)
#23     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1189:7)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#25     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#26     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1128:19)
#27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#30     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#33     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#34     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#35     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#38     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#39     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#40     main.<anonymous closure> (file:///Users/mac/Developer/clone_flutter/flutter/packages/flutter/test/widgets/placeholder_test.dart:63:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Placeholder child widget

✖ Placeholder child widget
Exited (1)

```

**Comment by TahaTesser** [comment] 2022-03-24 09:03
Closing as https://github.com/flutter/flutter/pull/100372 has landed

**Closed by TahaTesser** 2022-03-24 09:03 UTC
Labels: severe: new feature, framework, f: material design, proposal
