### ISSUE TITLE
Support `--route` on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4703] opened 2016-06-22 22:14 UTC
I have not tried on iOS Device.
Works on an Android device (--debug mode, did not try emulator or other modes).

```
cd examples/flutter_gallery
flutter run --route /buttons
```

Should load up to the "Buttons" demo (lib/demo/buttons_demo.dart), but just takes you to the Gallery main page instead.

**Comment by tvolkert** [comment] 2016-06-24 18:38
Still a TODO:

https://github.com/flutter/flutter/pull/1334/files#diff-4f315bf6a753b56d231e6d32c3e78f08R171
https://github.com/flutter/flutter/pull/1334/files#diff-4f315bf6a753b56d231e6d32c3e78f08R421

**Comment by Hixie** [comment] 2017-01-31 05:18
Marking this milestone 3, because we should have parity with iOS.

**Comment by eseidelGoogle** [comment] 2017-01-31 16:07
I think we won't probably end up using this until we expose the route to the IDEs, etc.  I've never seen someone use this feature as is.  https://github.com/flutter/flutter/issues/4701

**Comment by Hixie** [comment] 2017-01-31 20:33
Agreed. We could also get parity by just removing the Android side. I just want to make sure we have parity my m3.

**Comment by Hixie** [comment] 2017-11-21 23:01
Moving to m4 because this doesn't fit our current priority list, though it's sad that that means we won't have parity by m3.

**Comment by eseidelGoogle** [comment] 2017-11-22 03:18
Should we remove (or disable) --route on android to match?

We do have support for deep linking on our list of priorities and fixing something like this might end up as part of someone trying to test such.  That said, I definitely support punting given no customer has asked for this to my knowledge.

**Comment by Hixie** [comment] 2017-11-22 21:55
SGTM. I'll look at what it will take when I work on routes.

**Comment by xster** [comment] 2018-10-23 01:38
It does seem like IOSDevice.startApp is ignoring its `route` parameter. Though I agree. Not super high priority.

**Comment by lawonga** [comment] 2019-05-16 23:17
Having the same issue as well 🤷‍♂

**Comment by fotiDim** [comment] 2020-06-08 14:34
Is there a corresponding issue for Flutter Web?

**Comment by pedromassangocode** [comment] 2020-08-26 14:22
I can confirm that the issue still exist on latest `master` channel. Tested with [Flutter Gallery](https://github.com/flutter/gallery).

![Screen Shot 2020-08-26 at 15 19 17](https://user-images.githubusercontent.com/67424416/91315367-85e6a600-e7af-11ea-87de-c17672fa37ea.png)

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.81, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.81 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 8c8b91069d (77 minutes ago), 2020-08-26 06:03:05 -0700
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro Max (mobile) • B2A481C0-B2C1-495A-9ECA-0D3778F2FCD3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by pedromassangocode** [comment] 2020-09-18 06:59
I was about to fill a new issue but thread does not make it clear if this will be removed or extended.

If we are not going to remove this on Android, we need to document this somewhere that this is only supported on Android if we want to add support for other platforms in the future https://github.com/flutter/flutter/issues/46065#issuecomment-694627612.

This feature is currently mentioned in the Navigator class API docs, but it does not explicitly says on what platform this feature is supported.

https://github.com/flutter/flutter/blob/d26268bb9e6d713a73d6148da7fa75936d442741/packages/flutter/lib/src/widgets/navigator.dart#L1259-L1267

**Comment by xster** [comment] 2020-09-23 18:59
@DanielEdrisian here's another one to take a look at. It's just a bug in our tooling in iOS. 

It starts off in https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/commands/run.dart;l=61 and goes through https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/resident_runner.dart;l=638 then https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/ios/devices.dart;l=308 at which point we just dropped the `route` argument. By contrast, Android does it right in https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/android/android_device.dart;l=543. 

We just need to add it to our launch arguments in https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/ios/devices.dart;l=365 like Android does it in 
https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/android/android_device.dart;l=639

**Comment by jmagman** [comment] 2022-02-15 01:31
This will also require an engine change.  On Android, the engine reads off the launch arg and then calls `flutterView.setInitialRoute(route)`
https://github.com/flutter/engine/blob/8714a2448fa9b42e6f353fa6d40085a8942b64ea/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L347-L355

On iOS, the launch arg passed in from the tool needs to be parsed in the engine, like this
https://github.com/flutter/engine/blob/171458e8038f2c840b4388212a197b8a40470c89/shell/common/switches.cc#L294-L295

and used in [`-[FlutterViewController sharedSetupWithProject:initialRoute:]`](https://github.com/flutter/engine/blob/4a3e7a5b72363c1f363d3000d04719c6938d963f/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L188-L189) if `initialRoute` is nil like this
https://github.com/flutter/engine/blob/19a19cd50b0eeae03b0880719bc13d48e1804c9e/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L697-L698
See also #20468

**Comment by jmagman** [comment] 2022-02-15 01:36
Also, don't forget to add the launch args to the iOS simulator https://github.com/flutter/flutter/blob/1ae5dd194c3341cba1e0a24533f0434a9180f3a8/packages/flutter_tools/lib/src/ios/simulators.dart#L468

**Closed** 2022-03-07 19:31 UTC
Labels: platform-ios, tool, framework, f: routes, passed first triage, has reproducible steps, P4, found in release: 1.22
