### ISSUE TITLE
webview_flutter ImageReader_JNI warnings

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#70291] opened 2020-11-11 14:18 UTC
**W/ImageReader_JNI(26803): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers**

Does this message have to do with the use of hybrid composition?

Android 8.1
flutter 1.22.3
webview_flutter 1.0.7

**Comment by TahaTesser** [comment] 2020-11-11 14:57
Hi @mdmota 
Please reply to your original issue https://github.com/flutter/flutter/issues/70290
Closing as duplicate of https://github.com/flutter/flutter/issues/70290
Thank you

**Closed by TahaTesser** 2020-11-11 14:57 UTC
