### ISSUE TITLE
my Flutter page can not show

### ISSUE THREAD

**Issue by MrBMask** [flutter/flutter#94983] opened 2021-12-10 02:59 UTC
xcode print
```
2021-12-10 09:42:35.181810+0800 MyApp_flutter[8192:3751169] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2021-12-10 09:42:35.182114+0800 MyApp_flutter[8192:3751169] Metal API Validation Enabled
2021-12-10 09:42:35.240189+0800 MyApp_flutter[8192:3751169] Writing analzed variants.
2021-12-10 09:42:35.244068+0800 MyApp_flutter[8192:3751530] [VERBOSE-2:engine.cc(194)] Engine run configuration was invalid.
2021-12-10 09:42:35.244349+0800 MyApp_flutter[8192:3751530] [VERBOSE-2:shell.cc(576)] Could not launch engine with configuration.
2021-12-10 09:42:35.352376+0800 MyApp_flutter[8192:3751559] flutter: Observatory listening on http://127.0.0.1:50022/-E6ccbSLJl4=/

```

flutter run print
```
Resolving dependencies...
  characters 1.1.0 (1.2.0 available)
  json_annotation 4.1.0 (4.4.0 available)
  json_serializable 5.0.2 (6.1.1 available)
  pubspec_parse 1.1.0 (1.2.0 available)
  vector_math 2.1.0 (2.1.1 available)
Got dependencies in /Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools!
Package flutter_wrapper is currently active at path "/Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools".
Activated flutter_wrapper 0.0.1 at path "/Users/bmask/Desktop/sohu-code/MPTC-Flutter/flutterw/tools".
================================================
target packages:

================================================
Multiple devices found:
Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30)
(emulator)
Bmask (mobile)                     • 00008101-0005505C00E1401E            • ios         • iOS 15.1.1 19B81
iPhone 12 (mobile)                 • 2BF72B4D-5471-4D82-9ECD-65C9FA2E62BD • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
[1]: Android SDK built for x86 (emulator-5554)
[2]: Bmask [(00008101-0005505C00E1401E)](url)
[3]: iPhone 12 (2BF72B4D-5471-4D82-9ECD-65C9FA2E62BD)

```

### flutter doctor print
```
[✓] Flutter (Channel unknown, 2.5.2, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.2 at /Users/bmask/.flutter_sdks/2.5.2
    • Upstream repository unknown
    • Framework revision 3595343e20 (2 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/bmask/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code (version 1.45.1)
    • VS Code at /Users/bmask/Desktop/sohu-code/MPTC-iOS/PINOperation-Distribution/Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30)
      (emulator)
    • Bmask (mobile)                     • 00008101-0005505C00E1401E            • ios            • iOS 15.1.1 19B81
    • iPhone 12 (mobile)                 • 2BF72B4D-5471-4D82-9ECD-65C9FA2E62BD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93
    ! Error: Bmask is busy: Making the device ready for development. Xcode will continue when Bmask is finished. (code -10)

! Doctor found issues in 1 category.
```

###screen shot

https://user-images.githubusercontent.com/11421328/145509867-8c335c7b-7e0c-41ab-ae7b-b28cad003c02.mp4

###Build Export
[Build MyApp_flutter_2021-12-10T09-42-12.txt](https://github.com/flutter/flutter/files/7689796/Build.MyApp_flutter_2021-12-10T09-42-12.txt)

**Comment by darshankawar** [comment] 2021-12-10 07:20
@MrBMask 
Assuming you are using add2app scenario, can you provide complete minimal code sample that we can use to verify this ? You may create a demo repo and share github link of it here that we can clone and run.
Also follow this [document](https://docs.flutter.dev/development/add-to-app/android/project-setup) and see if you have properly set up the project.

**Comment by MrBMask** [comment] 2021-12-14 02:23
@darshankawar here is my code url https://github.com/MrBMask/FluttterDemo

**Comment by MrBMask** [comment] 2021-12-14 03:14
@darshankawar  I tried to upgrade the flutter version. This issue is not resolved I don't know why. The same code Colleagues don't have this problem

**Comment by darshankawar** [comment] 2021-12-14 07:11
Can you provide complete steps to replicate this behavior after cloning the repo ?
Thanks.

**Comment by MrBMask** [comment] 2021-12-14 07:15
@darshankawar first clone repo These are my step 
1. cd my_flutter
2.flutter pub get
3.cd MyApp_flutter
4.pod install
Then run the app

**Comment by darshankawar** [comment] 2021-12-15 05:44
@MrBMask 
Thanks for the steps. I followed it and ran it on iOS simulator which compiled and built the app properly for me:

<img width="364" alt="Screenshot 2021-12-15 at 11 12 33 AM" src="https://user-images.githubusercontent.com/67046386/146130113-794bef1a-8eb1-46b7-913e-0afcb45b6d13.png">

But I don't see `Show Flutter` button as shown in your video.

Are you facing same issue as https://github.com/flutter/flutter/issues/94554 ?

**Comment by Bmask00** [comment] 2021-12-15 06:36
@darshankawar  Yes  , I facing same issue as #94554 .
this is my anthor account. I will repaly you with this account. Thank you

**Comment by Bmask00** [comment] 2021-12-15 06:39
@darshankawar  Yes  , I facing same issue as #94554 .
this is my anthor account. I will repaly you with this account. Thank you

**Comment by Bmask00** [comment] 2021-12-15 06:39
@darshankawar  Yes  , I facing same issue as #94554 .
this is my anthor account. I will repaly you with this account. Thank you

**Comment by darshankawar** [comment] 2021-12-16 04:59
closing this as duplicate of https://github.com/flutter/flutter/issues/94554

**Closed by darshankawar** 2021-12-16 04:59 UTC
Labels: waiting for customer response, in triage
