### ISSUE TITLE
`Mac_android run_release_test` fails with `unexpected element (uri:"", local:"base-extension")`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#105715] opened 2022-06-09 17:47 UTC
Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20run_release_test/5121/overview
<img width="1185" alt="Screen Shot 2022-06-09 at 10 45 59 AM" src="https://user-images.githubusercontent.com/54558023/172911114-28550d81-fe0d-4523-847c-57682640b4ad.png">

Manually quarantined for now.

**Comment by drewroengoogle** [comment] 2022-06-14 17:14
It seems that the recipe is failing at [this point](https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone.py;l=140?q=file:recipes%2Fdevicelab%2Fdevicelab_drone.py) consistently on Mac18.

@keyonghan What steps would you recommend taking in order to find more information around why this machine is causing issues?

**Comment by keyonghan** [comment] 2022-06-14 18:51
@blasten Could you help identify the issue? I see error `Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>` from gradle. Considering this happens only on mac18, could it be related to some bad cache on this bot?

```
run: starting...
[run_release_test] [STDOUT] Executing "/opt/s/w/ir/x/w/recipe_cleanup/tmpq6sq0tro/flutter sdk/bin/flutter --suppress-analytics run --release -d ZY2245NMBT lib/main.dart" in "/opt/s/w/ir/x/w/recipe_cleanup/tmpq6sq0tro/flutter sdk/dev/integration_tests/ui" with environment {BOT: false, LANG: en_US.UTF-8}
[run_release_test] [STDOUT] run:stdout: Running "flutter pub get" in ui...                               2,343ms
[run_release_test] [STDOUT] run:stdout: Launching lib/main.dart on Moto G 4 in release mode...
[run_release_test] [STDOUT] run:stdout: Running Gradle task 'assembleRelease'...                        
[run_release_test] [STDOUT] run:stderr: Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
[run_release_test] [STDOUT] run:stdout: Running Gradle task 'assembleRelease'...
```

**Comment by keyonghan** [comment] 2022-06-15 21:16
This seems related to unhealthy bot. Dup with https://github.com/flutter/flutter/issues/105715.

**Comment by christopherfujino** [comment] 2022-06-22 18:53
@keyonghan I'm also seeing this mac-17 https://ci.chromium.org/ui/p/flutter/builders/try/Mac_android%20run_release_test/1467/overview This failed two times in a row on my PR https://github.com/flutter/flutter/pull/100982/checks?check_run_id=7010404855

**Comment by christopherfujino** [comment] 2022-06-22 18:54
> This seems related to unhealthy bot. Dup with #105715.

Oh wait, I think this is the wrong link, maybe you meant https://github.com/flutter/flutter/issues/104747?

**Comment by christopherfujino** [comment] 2022-06-22 20:56
Marking this a p1 as I think it's now blocking all PRs

**Comment by keyonghan** [comment] 2022-06-22 22:00
A rerun on mac-17 passes: https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac_android%20entrypoint_dart_registrant/1949/overview.

Created https://github.com/flutter/flutter/issues/106442 to track mac-13.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4834995 to move mac13 to staging, and add one more bot mac-19 to try.

**Comment by christopherfujino** [comment] 2022-06-27 16:29
> Every tasks `Mac_android run_release_test` on mac-17 are still failing (see https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-17). My 2 current PRs are constantly failing on `run_release_test`.

ditto this, I'm re-adding to infra ticket queue, cc flutter infra rotation @godofredoc

**Comment by keyonghan** [comment] 2022-06-27 17:03
I cleaned up the cache on mac17 again, and this should be unblocked considering we have one more bot mac-19 which runs okay.
If this issue keeps happening, I will skip the test in pre-submit.

**Comment by christopherfujino** [comment] 2022-06-27 17:08
> I cleaned up the cache on mac17 again, and this should be unblocked considering we have one more bot mac-19 which runs okay. If this issue keeps happening, I will skip the test in pre-submit.

Thanks Keyong!

**Comment by christopherfujino** [comment] 2022-06-27 20:13
> I cleaned up the cache on mac17 again, and this should be unblocked considering we have one more bot mac-19 which runs okay. If this issue keeps happening, I will skip the test in pre-submit.

@keyonghan Looks like mac-17 got in a bad state again https://ci.chromium.org/ui/p/flutter/builders/try/Mac_android%20run_release_test/1550/overview

It must be some other builder getting this in a bad state. To try to unblock, I will re-run

**Comment by keyonghan** [comment] 2022-06-28 00:50
I am disabling the test: https://github.com/flutter/flutter/pull/106709

**Comment by keyonghan** [comment] 2022-06-28 20:05
Test is disabled in https://github.com/flutter/flutter/pull/106709, moving out of ticket queue for android triage. Removing P1 as this is not blocking.

**Comment by GaryQian** [comment] 2022-08-09 17:36
cc @camsim99 who experienced this locally

**Comment by keyonghan** [comment] 2022-08-19 21:31
This is happening on mac35 consistently, and causing 3 flakes today. Bumping to P1 to match flake policy:
<img width="1221" alt="Screen Shot 2022-08-19 at 2 29 20 PM" src="https://user-images.githubusercontent.com/54558023/185709894-16a9d2a5-bf44-4318-9e71-c29da888f3a3.png">

**Comment by keyonghan** [comment] 2022-08-19 22:30
Now both `Mac_android run_release_test` and `Mac_arm64_android run_release_test` are flaky across multiple testbeds:
<img width="295" alt="Screen Shot 2022-08-19 at 3 29 21 PM" src="https://user-images.githubusercontent.com/54558023/185715244-056e3588-5673-4ae4-964b-428a5703ef67.png">

Marking them as flaky: https://github.com/flutter/flutter/pull/109890

**Comment by stuartmorgan** [comment] 2022-08-23 17:12
Comments about this warning on the internet in general suggest there may be a cache issue involved here; could we try a clean image for any bot still hitting this and see if that fixes it?

**Comment by GaryQian** [comment] 2022-08-23 17:14
Since the flakiness coincides with my ci.yaml upgrades at https://github.com/flutter/flutter/commit/357755f968fa89f29d9bded4e6d099fddf55a80e, this may be a transient flakiness issue as it has since recovered.

**Comment by keyonghan** [comment] 2022-08-30 17:38
> @keyonghan Is this still showing up anywhere, or can we close it?

No, I am not seeing this issue recently. Seem those two tests are running okay in the staging pool. The flake bot should be able to bring them back once validated for recent 50 runs. If we believe the issue is fixed, please feel free to close.

> Also, from a future-proofing standpoint: if it was a case where we just needed to do clean builds, is there a way to trigger that in a PR? E.g., a landmine file like Chromium uses?

Yeah, we are tracking something similar in https://github.com/flutter/flutter/issues/101710.

**Comment by stuartmorgan** [comment] 2022-08-30 19:29
Sounds good, closing as it looks like there's nothing left to track here.

If we get more instances that don't resolve after cleaning the bot cache we can re-open.

**Comment by keyonghan** [comment] 2022-08-31 17:27
I cleaned up the bot cache (/opt/s/c) and cipd_cache (/opt/s/cipd_cache) on mac-20 yesterday, but still see the failure today: https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_android%20run_release_test/6331/overview

@stuartmorgan @GaryQian What other cache we can try cleaning?

**Comment by stuartmorgan** [comment] 2022-08-31 17:30
My understanding is that what we'd want is for the build itself to be clean (i.e., not re-using the build output dir from a previous run).

**Comment by keyonghan** [comment] 2022-08-31 17:37
The cleanup actually helped. See Mac-35: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-35
Before cleaning up, it failed: https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_arm64_android%20run_release_test/1617/overview
After cleaning up, it succeeds: https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_arm64_android%20run_release_test/1625/overview

I am wondering if the mac-20 one has polluted cache since the cleanup yesterday? I am trying to understand what cached values or the output dir (you mentioned) we should keep them clean.

**Comment by stuartmorgan** [comment] 2022-08-31 17:49
The theory (which was speculative, so if it's happening again could easily be wrong) was that this was caused by re-using a build directory that was previously built with one version of the native toolchain (e.g., gradle) but was now being built with a different version. The timing seemed to coincide with a tool version change, so it seemed reasonable.

Unless @GaryQian landed another tool version change since yesterday, it sounds like there's something else going on.

**Comment by keyonghan** [comment] 2022-08-31 18:08
Based on the fact that both mac-21 and mac-35 got back to normal after cleaning up caches, I tried cleaning up mac-20 one more time. An led run suggests the bot is passing the test: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/7d0389f67f2cd5eead18670d0b1f581f0d40735cc2270de052f41356831d234d/+/build.proto

Will monitor a bit on the test/bot before closing.

**Closed** 2022-08-31 21:07 UTC
Labels: platform-android, P1
