### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by DaichiFujiwara** [flutter/flutter#128561] opened 2023-06-09 06:37 UTC
## Command
```
flutter --no-color run --machine --device-id=adb-100420a6-iAFlrz._adb-tls-connect._tcp --start-paused --profile --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:280:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1702], locale ja-JP)
    • Flutter version 3.7.7 on channel stable at C:\Users\Fujiwara\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (3 months ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Fujiwara\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\Fujiwara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • BZ02 (mobile)     • adb-100420a6-iAFlrz._adb-tls-connect._tcp • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows                                   • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome                                    • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge                                      • web-javascript • Microsoft Edge 114.0.1823.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ad6cd72c040113b47ee9055e722606a490ef0da
### Plugins
flutter_inappwebview-5.7.2+3
flutter_localization-0.1.11
flutter_plugin_android_lifecycle-2.0.9
image_picker-0.8.7+1
image_picker_android-0.8.6+6
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+2
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.5
shared_preferences-2.1.1
shared_preferences_android-2.1.0
shared_preferences_foundation-2.2.0
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
ssh2-2.2.3
webview_flutter-4.0.7
webview_flutter_android-3.4.5
webview_flutter_wkwebview-3.2.3

**Comment by darshankawar** [comment] 2023-06-09 07:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/118400

**Closed by darshankawar** 2023-06-09 07:56 UTC
Labels: in triage
