### ISSUE TITLE
TextSpan showing splited letters when adding style (in arabic utf8)

### ISSUE THREAD

**Issue by abdalmonem** [flutter/flutter#88944] opened 2021-08-26 09:52 UTC
i notice today this issue , specially with "Aarabic" , wen i use a nested text span inside RichText and add a style parameter to each letter each letter showed as a separated block , this is a runable example code :

<img src="https://user-images.githubusercontent.com/9139030/130942202-861f8803-d390-46bc-875a-7b6954318aee.PNG" width="300"> :

```
return Scaffold(
      body: Center(
        child: Column(
          children: [
            Container(
              child: RichText(
                text: TextSpan(
                    style: TextStyle(color: Colors.black, fontSize: 18),
                    children: [
                      TextSpan(text: 'س', ),
                      TextSpan(text: 'ل', ),
                      TextSpan(text: 'ا', ),
                      TextSpan(text: 'م', ),
                    ]
                ),
              ),
            ),
            Container(
              child: RichText(
                text: TextSpan(
                    style: TextStyle(color: Colors.black, fontSize: 18),
                    children: [
                      TextSpan(text: 'س', style: TextStyle()),
                      TextSpan(text: 'ل', style: TextStyle()),
                      TextSpan(text: 'ا', style: TextStyle()),
                      TextSpan(text: 'م', style: TextStyle()),
                    ]
                ),
              ),
            ),
          ],
        ),
      ),
    );

```

channel : master
Target Platform: IOS
Target OS version: 14.7
Devices: Iphone 7

flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.2 at /Users/abdalmonem/flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abdalmonem/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

**Comment by abdalmonem** [comment] 2021-09-05 14:03
@maheshmnj
salam alykum ,  any progress on this issue ?

**Comment by maheshmnj** [comment] 2021-09-06 07:12
@abdalmonem, The issues that are being worked on or will likely be worked on in near future will have a priority assigned, You can read more about how the issues are prioritized here: https://github.com/flutter/flutter/wiki/Issue-hygiene

**Comment by GaryQian** [comment] 2021-09-10 19:36
This issue is a duplicate of https://github.com/flutter/flutter/issues/73108

I'm going to close this to merge the two issues.

Some heads up, this is a known issue and unfortunately not an issue that can easily be resolved. When applying separate styles, each separate "run" is handled independently without context of surrounding text. For now, it is best to avoid splitting connected words with different styles when possible if you wish to maintain the ligature connection.

**Closed by GaryQian** 2021-09-10 19:36 UTC
Labels: platform-android, platform-ios, framework, engine, platform-mac, a: internationalization, a: typography, has reproducible steps, found in release: 2.2, found in release: 2.6
