### ISSUE TITLE
Flutter doesn't want to create an emulator

### ISSUE THREAD

**Issue by cjdenio** [flutter/flutter#55971] opened 2020-04-29 16:32 UTC
Yes, this is a bug report. Yet another, in a sea of thousands. Bug reports can often be vague, user-specific, and altogether frustrating. I've tried my best to do as much research as possible before submitting this issue. I'd like you to know that you're doing an awesome job! :tada: 

## Issue

When I try to create an emulator on Ubuntu 20.04, Flutter crashes. It appears as though it can't find `avdmanager`, and attempts to run `null list device -c` instead of `avdmanager list device -c`. `flutter doctor -v` shows no issues.

## Steps to Reproduce

1. Run `flutter emulators --create`
2. Observe

## Logs

Here's the problematic part of `flutter emulators --create -v`'s output:
```
executing: /home/cjdenio/android-sdk/emulator/emulator -list-avds
Exit code 0 from: /home/cjdenio/android-sdk/emulator/emulator
-list-avds
executing: null list device -c
"flutter emulators" took 138ms.
```
## Crash report:
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

### command

flutter emulators --create

### exception

ArgumentError: Invalid argument(s): Cannot find executable for null.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#3      EmulatorManager._getPreferredAvailableDevice (package:flutter_tools/src/emulator.dart:144:46)
#4      EmulatorManager.createEmulator (package:flutter_tools/src/emulator.dart:82:33)
<asynchronous suspension>
#5      EmulatorsCommand._createEmulator (package:flutter_tools/src/commands/emulators.dart:88:31)
#6      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:49:13)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

### flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/cjdenio/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/cjdenio/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/cjdenio/android-sdk/cmdline-tools/latest
    • Java binary at: /home/cjdenio/jdk-14.0.1/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.1+7)
    • All Android licenses accepted.

[ ! ] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[ ! ] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by aseef17** [comment] 2020-04-30 01:15
From what I can see, you don’t seem to have android studio installed. That might be required to create an emulator. 
Try installing android studio for Ubuntu and see if that works for you.
You can use this [Guide](https://stackoverflow.com/questions/39928340/how-to-start-an-android-emulator-in-ubuntu-16-04)

**Comment by iapicca** [comment] 2020-04-30 07:12
Hi @aseef17 
I can experience the same behaviour with both the latest stable and the latest master

```console
 nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter emulator -h                                                                                  ✔  1065  10:08:28
List, launch and create emulators.

Usage: flutter emulators [arguments]
-h, --help      Print this usage information.
    --launch    The full or partial ID of the emulator to launch.
    --create    Creates a new Android emulator based on a Pixel device.
    --name      Used with flag --create. Specifies a name for the emulator being created.

Run "flutter help" to see global options.
 nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter_master emulators --create                                                                    ✔  1066  10:08:56
Failed to create emulator 'flutter_emulator'.

Error: AVD not created.

You can find more information on managing emulators at the links below:
  https://developer.android.com/studio/run/managing-avds
  https://developer.android.com/studio/command-line/avdmanager
```

```console
  nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter doctor -v                                                                                    ✔  1067  10:09:20
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.12.13+hotfix.9 at /Users/nevercode/development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

• No issues found!
```

```console
nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter_master doctor -v                                                                             ✔  1068  10:10:07
[✓] Flutter (Channel master, 1.18.0-9.0.pre.73, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-9.0.pre.73 at /Users/nevercode/development/flutter_master
    • Framework revision bd6ccb606a (8 hours ago), 2020-04-29 16:31:42 -0700
    • Engine revision 2db3276573
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 726d3c7725)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

Thank you for reporting this

**Comment by cjdenio** [comment] 2020-04-30 12:55
It is true that I don't have Android Studio installed, and that will certainly be my next step if this isn't resolved. I haven't installed it due to space constraints. (My SSD is split between Ubuntu and Windows) However, it doesn't seem like this issue is due to my not having Android Studio installed. I'd be interested to see where in the Flutter code it's coming up with `null` instead of `avdmanager` 🤔

**Comment by jonahwilliams** [comment] 2020-05-05 20:15
I wonder if we're missing a check for `avdmanager` in the doctor, or we're looking it up in a way that inadvertently requires android studio.

**Comment by christopherfujino** [comment] 2020-05-05 20:15
> I'd be interested to see where in the Flutter code it's coming up with `null` instead of `avdmanager` 🤔

Looks like it's in your stack trace:

`#3      EmulatorManager._getPreferredAvailableDevice (package:flutter_tools/src/emulator.dart:144:46)`

Which looks like:

```dart
    final List<String> args = <String>[
      getAvdManagerPath(globals.androidSdk),
      'list',
      'device',
      '-c',
    ];
    final RunResult runResult = processUtils.runSync(args,
        environment: globals.androidSdk?.sdkManagerEnv);
    if (runResult.exitCode != 0) {
      return null;
    }
```

We should check first if `getAvdManagerPath()` returns null.

**Comment by christopherfujino** [comment] 2020-05-05 20:16
To @jonahwilliams's point, it looks like avdmanager doesn't come bundled with the command-line only android sdk, but does with the android studio bundle:

https://developer.android.com/studio/command-line/avdmanager

**Comment by cjdenio** [comment] 2020-05-05 20:17
I did have `avdmanager` installed, and I could (semi-successfully) create emulators from the command-line.

**Comment by jonahwilliams** [comment] 2020-05-05 20:17
The lookup is here: https://github.com/flutter/flutter/blob/c587d73ec65da16a7360bfb67c15aca6d707e5d6/packages/flutter_tools/lib/src/android/android_sdk.dart#L298

So we definitely need a doctor check for this

**Comment by jonahwilliams** [comment] 2020-05-05 20:18
alternatively, we could fallback to calling `avdmanager` if its on the PATH

**Comment by jonahwilliams** [comment] 2020-05-05 20:39
So the concrete changes are:

1. Add a doctor check that we can locate avdmanager, and that ProcessManager.canRun returns true.
2. If locateAvdManger returns null, check if avdmanager is on the path. If we still can't find it, toolExit instead of crashing

**Comment by jonahwilliams** [comment] 2020-05-30 01:33
I've fixed the case where we crash when avd is missing. Still need to add some doctor logic and instructions for downloading

**Comment by pedromassangocode** [comment] 2020-12-16 13:20
I cannot reproduce this on latest `master` and `stable` channel.
@jonahwilliams is there any pending work to close this one?
@jonahwilliams can we close this and open another one for the remaining work you may have? 

I'm closing this for now, since the original issue does not reproduces on latest master and stable. Feel free to reopen if necessary.

<details><summary>flutter doctor</summary>

```
/Users/pedromassango/dev/SDKs/flutter_stable/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (6 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Closed by pedromassangocode** 2020-12-16 13:20 UTC
Labels: found in release: 1.12, found in release: 1.18, has reproducible steps, platform-android, tool
