### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:55548/ws

### ISSUE THREAD

**Issue by Panseng** [flutter/flutter#32402] opened 2019-05-09 12:14 UTC
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 28) (emulator)

**Comment by Panseng** [comment] 2019-05-09 12:17
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:56616/ws

**Comment by Panseng** [comment] 2019-05-09 13:05
![image](https://user-images.githubusercontent.com/48272139/57455598-0d986080-729e-11e9-814d-9929716cded7.png)
this enviroment

**Comment by Luquatic** [comment] 2019-05-09 20:49
I have the same problem, have you found a solution yet?

**Comment by Chance722** [comment] 2019-05-10 02:37
> I have the same problem, have you found a solution yet?
> 
> **EDIT:**
> I had the same problem using Android 9.x and fixed it by using an older version.
> 
> I'm currently using 7.1.1 and that works fine for me.

thanks a lot!

**Comment by DanTup** [comment] 2019-06-05 12:22
This looks like a dupe of https://github.com/flutter/flutter/issues/33050 then.

**Closed by DanTup** 2019-06-05 12:22 UTC
