### ISSUE TITLE
Flutter build web --web-renderer html always generates a canvaskit folder resulting in large app bundle

### ISSUE THREAD

**Issue by The-RootCause** [flutter/flutter#146381] opened 2024-04-06 02:34 UTC
### Steps to reproduce

flutter build web --web-renderer html 

### Expected results

No canvaskit folder or smaller bundle size

### Actual results
Check the screenshot below
Canvaskit folder taking 20MB of the bundle size. Is it normal to be this big ? i have read 1.5MB or 2MB on other threads ? I have tried Flutter 3.19, 3.20, 3.21 all of them using html or canvasKit web renderer and it's always a folder 20MB big where skwasm is 3.2MB and canvaskit is 6.7MB

### Code sample

flutter sample app 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Screenshot 2024-04-06 at 04 28 43](https://github.com/flutter/flutter/assets/142636323/637e21fe-072b-491a-ba52-d49d766b02b5)

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-FR)
    • Flutter version 3.19.5 on channel stable at /Users/amine/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (9 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/amine/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15C5028h
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.14768

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Users/amine/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.14768

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • 1248A3EA-3818-49B9-BC9D-6A59E5A05C56 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment] 2024-04-08 08:09
Closing this as duplicate of https://github.com/flutter/flutter/issues/126738. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-04-08 08:09 UTC
Labels: in triage
