### ISSUE TITLE
 Could not resolve com.android.tools.build:gradle:3.1.2.

### ISSUE THREAD

**Issue by Iampato** [flutter/flutter#22470] opened 2018-09-29 15:08 UTC
```
$ flutter build apk
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\Alicembugua\Desktop\whatsapp\android\gradlew.bat app:properties:
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 1s

Please review your Gradle project setup in the android/ folder.
```

**Comment by Iampato** [comment] 2018-09-29 15:08
$ gradle --version

------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Windows 8.1 6.3 amd64

**Comment by Iampato** [comment] 2018-09-29 15:13
$ flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 0.8.2 at C:\Flutter\flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk\
    • Java binary at: C:\Program Files\Java\jdk1.8.0_181\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    X Android license status unknown.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

**Comment by Iampato** [comment] 2018-09-29 15:14
please help😓😓😓

**Comment by S1r-Lanzelot** [comment] 2018-10-02 19:30
@zoechi it is:
```
{USER_HOME}\Documents\Scratchpad>flutter create foo
Creating project foo...
  foo\.gitignore (created)
  foo\.idea\libraries\Dart_SDK.xml (created)
  foo\.idea\libraries\Flutter_for_Android.xml (created)
  foo\.idea\modules.xml (created)
  foo\.idea\runConfigurations\main_dart.xml (created)
  foo\.idea\workspace.xml (created)
  foo\.metadata (created)
  foo\android\app\build.gradle (created)
  foo\android\app\src\main\java\com\example\foo\MainActivity.java (created)
  foo\android\build.gradle (created)
  foo\android\.gitignore (created)
  foo\android\app\src\main\AndroidManifest.xml (created)
  foo\android\app\src\main\res\drawable\launch_background.xml (created)
  foo\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  foo\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  foo\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  foo\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  foo\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  foo\android\app\src\main\res\values\styles.xml (created)
  foo\android\gradle\wrapper\gradle-wrapper.properties (created)
  foo\android\gradle.properties (created)
  foo\android\settings.gradle (created)
  foo\ios\Runner\AppDelegate.h (created)
  foo\ios\Runner\AppDelegate.m (created)
  foo\ios\Runner\main.m (created)
  foo\ios\Runner.xcodeproj\project.pbxproj (created)
  foo\ios\.gitignore (created)
  foo\ios\Flutter\AppFrameworkInfo.plist (created)
  foo\ios\Flutter\Debug.xcconfig (created)
  foo\ios\Flutter\Release.xcconfig (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  foo\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  foo\ios\Runner\Base.lproj\Main.storyboard (created)
  foo\ios\Runner\Info.plist (created)
  foo\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  foo\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  foo\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  foo\lib\main.dart (created)
  foo\foo.iml (created)
  foo\foo_android.iml (created)
  foo\pubspec.yaml (created)
  foo\README.md (created)
  foo\test\widget_test.dart (created)
Running "flutter packages get" in foo...                     4.8s
Wrote 65 files.

[√] Flutter is fully installed. (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
[√] Android toolchain - develop for Android devices is fully installed. (Android SDK 27.0.3)
[√] Android Studio is fully installed. (version 3.2)
[√] VS Code is fully installed. (version 1.27.2)
[√] Connected devices is fully installed. (1 available)

All done! In order to run your application, type:

  $ cd foo
  $ flutter run

Your main program file is lib/main.dart in the foo directory.
{USER_HOME}\Documents\Scratchpad>cd foo
{USER_HOME}\Documents\Scratchpad\foo>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.1s
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: {USER_HOME}\Documents\Scratchpad\foo\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Connect to 127.0.0.1:8888 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Connect to 127.0.0.1:8888 [/127.0.0.1] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Please review your Gradle project setup in the android/ folder.
```

**Comment by jrodryb** [comment] 2018-10-03 20:42
Worked for me by adding mavenCentral() and gradle plugin version 3.2.0 in

**flutter_app\android\build.gradle**:
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}
...
```

And gradle version 4.6 in

**flutter_app\android\gradle\wrapper\gradle-wrapper.properties**:

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

**Comment by S1r-Lanzelot** [comment] 2018-10-04 13:32
Still no luck - I ended up just using a linux distro to develop in.

**Comment by Iampato** [comment] 2018-10-04 20:17
> 
> 
> Is this the same with a new project after `flutter create foo`?

**Comment by Iampato** [comment] 2018-10-04 20:43
Final solve this

`allprojects {
    repositories {
        google()
        jcenter()
		maven { url 'https://maven.google.com' }
    }
}`

#add this to your build.gradle file

**Comment by bangq** [comment] 2018-10-05 10:44
> Final solve this
> 
> `allprojects { repositories { google() jcenter() maven { url 'https://maven.google.com' } } }`
> 
> #add maven { url 'https://maven.google.com' } this to your build.gradle file

Still no luck 

`buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by JokerHYC** [comment] 2018-10-09 03:45
same issue here.

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.2.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve com.android.tools.build:gradle:3.1.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.2/gradle-3.1.2.pom'.
               > Read timed out
Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by creator1134** [comment] 2018-10-15 12:34
> mavenCentral()

adding mavenCentral() does the trick

**Comment by JokerHYC** [comment] 2018-10-22 10:31
solved this.
by delete http and https proxy in global gradle.properties document

**Comment by wuknife** [comment] 2018-11-01 11:17
solved too by shutdown shadowsocks.

**Comment by arashonline** [comment] 2018-12-05 07:16
> solved too by shutdown shadowsocks.

How did you do it?

**Comment by Stargator** [comment] 2018-12-06 20:56
I am having this issue as well. Occurs when I run `flutter create foo`.

I have Gradle 4.10.2 and Flutter 1.0.0

**Comment by dev-mush** [comment] 2018-12-10 13:04
I'm having this problem as well, apparently the `com.android.tools.build:gradle:3.1.2` is missing from any google repository, adding mavenCentral() resolves by picking it from a maven repository which doesn't belong to google. 
Is this safe?

**Comment by zoechi** [comment] 2018-12-10 13:39
@dev-mush Try changing it to `3.2.1` in `android/build.gradle` in `buildscript/dependencies/classpath`

**Comment by Djintelbe** [comment] 2018-12-11 04:21
I have the same issue. I have tried several proposition but did not solve my problem.
 Help please!

**Comment by zoechi** [comment] 2018-12-11 06:39
@Djintelbe 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by enjoyinwind** [comment] 2018-12-11 09:19
I have the same issue too. Help please!

**Comment by Stargator** [comment] 2018-12-11 13:21
Initially I was in a corporate network. I went home and tried again, it was successful.

Then went back to the corporate network and tried again, it worked.

**Comment by philip97hd** [comment] 2018-12-18 01:16
I have the same issue too!! Any Help please!!!

**Comment by mehrankasebvatan** [comment] 2019-01-03 05:47
> solved this.
> by delete http and https proxy in global gradle.properties
> file.

Thanke You

**Comment by zoechi** [comment] 2019-01-03 06:36
@Iampato are you still seeing this?

**Comment by mehrankasebvatan** [comment] 2019-01-03 06:54
> @Iampato are you still seeing this?

No

**Comment by NatnaelAB** [comment] 2019-01-07 11:43
adding `maven { url 'https://maven.google.com' }` to `C:\Program Files\flutter\packages\flutter_tools\gradle`  solved it!

**Comment by Iampato** [comment] 2019-04-04 05:35
> 
> 
> @Iampato are you still seeing this?

Downloaded gradle 4.11.1 issue fixed

**Comment by vivekvardhanadepu** [comment] 2019-04-06 16:12
upgrading gradle would solve the issue

**Comment by AlbertHumbert** [comment] 2019-04-17 09:02
same issue, after upgrade android studio and flutter.
I tried all the solutions I found but none of them work.

then I begin to check the old versions of gradle in .gradle/wrapper/dists (because I solved another problem in this way when I set up flutter sdk the first time).
and finally 4.4 worked for me.

note that plugin version may also need to change, I set it to an old version I used(3.1.2),
see https://developer.android.google.cn/studio/releases/gradle-plugin.html#updating-plugin

**Comment by yinMengxin** [comment] 2019-05-15 04:09
> please help😓😓😓
你这个问题解决了吗？

**Comment by Somya-Bansal** [comment] 2019-05-17 13:12
I get this error while running my flutter project that uses google maps API. There is no problem running the first app from docs.

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "C:\Personal Projects\Flutter\maps2\android\gradlew.bat" exited abnormally:

> Configure project :google_maps_flutter

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_maps_flutter'.
> Could not resolve all artifacts for configuration ':google_maps_flutter:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.3.2.
     Required by:
         project :google_maps_flutter
      > Could not resolve com.android.tools.build:gradle:3.3.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.2/gradle-3.3.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.2/gradle-3.3.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`


I have tried every workaround I came across. :(

**Comment by Somya-Bansal** [comment] 2019-05-20 05:37
One thing that I was missing was the gradle bin path in my System Variables. I had it only in my user variable PATH.
**Downloading gradle 4.10 and adding the same to System Environment Variable PATH did it for me.**

**Comment by wangchao1002** [comment] 2019-06-04 08:31
> > please help😓😓😓
> > 你这个问题解决了吗？

嗯很

**Comment by bernardohrl** [comment] 2019-06-05 13:01
I just created the app and tried to run the app for the first time. Got the same error:

```
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find
```
<br>


## **What I have tried**
* Add ```mavenCentral()``` and ```maven { url 'https://maven.google.com' }```
* Using ``` build:gradle:3.1.2 ```
* Using Gradle 4.11.1

None of the options above worked. 

But, I have some doubts about @JokerHYC's answare. I'm using and corporate network, so it probably can be an proxy issue.
 

> solved this.
> by delete http and https proxy in global gradle.properties
> file.


Can anyone explain better how I can do this?

**Comment by digikin** [comment] 2019-07-12 14:17
Installing gradle itself solved my issue.  
```
$ brew install gradle
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://services.gradle.org/distributions/gradle-5.5.1-all.zip
==> Downloading from https://downloads.gradle.org/distributions/gradle-5.5.1-all.zip
######################################################################## 100.0%
🍺  /usr/local/Cellar/gradle/5.5.1: 14,030 files, 242.4MB, built in 34 seconds
$ gradle -v

Welcome to Gradle 5.5.1!

Here are the highlights of this release:
 - Kickstart Gradle plugin development with gradle init
 - Distribute organization-wide Gradle properties in custom Gradle distributions
 - Transform dependency artifacts on resolution

For more details see https://docs.gradle.org/5.5.1/release-notes.html


------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Mac OS X 10.14.5 x86_64
```
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
[{"event":"app.progress","params":{"appId":"07650874-e6b8-470d-b845-679052a5149c","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...

Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 6245): eglMakeCurrent: 0xae554600: ver 3 0 (tinfo 0xae552b20)
```

**Comment by cqpaul** [comment] 2019-09-03 16:50
Who knows the right answer, I am in this trouble.

**Comment by almaystroOo** [comment] 2019-09-03 22:04
any tips, I am stuck on this

**Comment by Djintelbe** [comment] 2019-09-04 09:58
This answers solved mine https://github.com/flutter/flutter/issues/22470#issuecomment-445026734. So, change your network and try another

**Comment by MikeQin** [comment] 2019-09-19 05:26
Hi guys,

I have encountered the same problem. How did I solve it?

### The root cause is corporate firewall. You need to set proxy in gradle.properties, like this:

> systemProp.http.proxyHost=proxy.company.com
> systemProp.http.proxyPort=443
> systemProp.http.proxyUser=userid
> systemProp.http.proxyPassword=password
> systemProp.http.auth.ntlm.domain=domain


In addition, make sure your JAVA_HOME is set to Java 1.8 home.

### update sdkmanager 
`sdkmanager --update`

### accept all android licenses:
`flutter doctor --android-licenses`

### finally, validate
`flutter doctor -v`
You should be able to see all is clear by now

Good luck.

**Comment by sugubei** [comment] 2019-10-04 10:15
https://blog.csdn.net/qq_41788782/article/details/102083874

**Comment by freakaziod210** [comment] 2019-10-18 04:14
I tried changing the files like some suggested but still had problems. I upgraded gradle and it's now working like a charm

**Comment by DevonTomatoSandwich** [comment] 2019-12-10 10:13
Tried everything in this thread and nothing worked. I Started getting a lot of gradle issues after splitting the apk (would not recommend) but it could also be from migrating to androidx :(

**Comment by A1Gard** [comment] 2020-01-08 13:34
For **Iranian** people: We need use **proxy** or **VPN** to building app.

**Comment by blasten** [comment] 2020-01-14 23:02
It might be useful to add a doctor check that verifies that a user can connect to all the hosts the flutter tool depends on. Either directly or indirectly. Some examples: the pub host, GCP bucket, Google Maven, cocoapod server and so on. Any objection or concern @timsneath, @tvolkert, @zanderso ?

**Comment by zanderso** [comment] 2020-01-15 17:52
Adding that check to the doctor sgtm. Could you go ahead and file an issue for that and we can track it in the doctor project. Thanks!

**Comment by jonahwilliams** [comment] 2020-02-04 23:20
Now that the tracking issue has been filled, I'm going to close this one

**Closed by jonahwilliams** 2020-02-04 23:20 UTC
Labels: severe: crash, t: gradle, tool

**Comment by hamid-zp** [comment] 2020-04-09 09:42
Solved by disable the http and https socks proxy. I used a VPN instead
