### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'E:\demofile\Flutter\App\ohos_flutterdemo\demo3\ohos\har\flutter_embedding.har', OS Error: The system can not find the file specified, errno = 2  flutter_embedding.har.release.10 这个文件系统有，但找的是flutter_embedding.har.release.12

### ISSUE THREAD

**Issue by wanlingyun** [flutter/flutter#142881] opened 2024-02-04 08:13 UTC
## Command
```
flutter build hap --target-platform ohos-arm64 --local-engine-src-path=E:\demofile\Flutter\App\huawei\flutter_engine\src --local-engine=ohos_release_arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to 'E:\demofile\Flutter\App\ohos_flutterdemo\demo3\ohos\har\flutter_embedding.har', OS Error: The system can not find the file specified。
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.copySync (dart:io/file_impl.dart:349:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:32:50)
#3      cleanAndCopyFlutterRuntime (package:flutter_tools/src/ohos/hvigor.dart:542:17)
#4      OhosHvigorBuilder.flutterBuildPre (package:flutter_tools/src/ohos/hvigor.dart:728:5)
<asynchronous suspension>
#5      OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:646:5)
<asynchronous suspension>
#6      BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:50:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.12, on Microsoft Windows [版本 10.0.22000.2538], locale zh-CN)
    [32m•[39m Flutter version 3.7.12 on channel stable at D:\Program Files\flutterHarmony
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (7 months ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m OpenHarmony toolchain - develop for OpenHarmony devices
    [32m•[39m OpenHarmony Sdk location: D:\huaweiSDK\openharmony, available api versions has [9]
    [32m•[39m hdc version 1.2.0
    [32m•[39m ohpm version 1.2.0
    [32m•[39m signTool location:E:\demofile\Flutter\App\developtools_hapsigner\autosign

[31m[✗][39m Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\Android\AndroidSdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: D:\Program Files\java\jdk-20\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 20.0.1+9-29)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Professional 2022 17.7.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    [32m•[39m Visual Studio Professional 2022 version 17.7.34024.191
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at D:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.2538]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f468f3366c26a5092eb964a230ce7892fda8f2f8

**Comment by hyiso** [comment] 2024-02-04 08:50
The Flutter SDK is a fork for HarmonyOS, this issue must be filed to https://gitee.com/openharmony-sig/flutter_flutter/issues

**Comment by danagbemava-nc** [comment] 2024-02-05 10:04
Closing this as a possible duplicate of https://github.com/flutter/flutter/issues/100082. 

You may also want to file an issue on the open harmony repo as it appears to be using an older version of flutter and possibly the tool as well.

**Closed by danagbemava-nc** 2024-02-05 10:04 UTC
Labels: in triage
