### ISSUE TITLE
[bug][ios] BottomSheet with an image

### ISSUE THREAD

**Issue by andrea689** [flutter/flutter#30565] opened 2019-04-05 16:34 UTC
When open a BottomSheet with an image, the image is not loaded and all text in the app disappear.

If I put the app in background and reopen it, the image is loaded correctly and the text reappear.

I attach the code and a gif to show the problem.

[Demo code](https://gist.github.com/andrea689/9b19d4285cd49b946936a12aaf5f76ba)

![example](https://user-images.githubusercontent.com/5927329/55641982-856ef900-57cf-11e9-9a6f-a6b96a9b7fa5.gif)

### flutter analyze
```
Analyzing map_street_names_problem...                                   
No issues found! (ran in 2.9s)
```

### flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /Users/andrea/Development/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone di andrea • 4143d720cc928612c001b4f8ddb0eb2d7ecd5d5a • ios • iOS 11.4.1
```

**Comment by hariprasadiit** [comment] 2019-04-06 10:27
does your `info.plist` contain `io.flutter.embedded_views_preview`?

**Comment by andrea689** [comment] 2019-04-06 11:23
@hariprasadiit yes, because in the real app I use a map. Now, I tested this code without `io.flutter.embedded_views_preview` and the app work correctly!

**Comment by hariprasadiit** [comment] 2019-04-06 17:02
@HansMuller can we close this as dupe of #27561 ?

**Comment by zoeyfan** [comment] 2020-01-03 03:54
Per comments above, the issue no longer seems to repro after removing io.flutter.embedded_views_preview. Closing it for now.

**Closed by zoeyfan** 2020-01-03 03:54 UTC
Labels: f: material design, framework, severe: rendering
