### ISSUE TITLE
`flutter attach` crashes on iOS

### ISSUE THREAD

**Issue by YoungJam** [flutter/flutter#32189] opened 2019-05-07 09:04 UTC
## command

flutter attach

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/mac/Development/flutter_master
    • Framework revision 7a4c33425d (7 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (2 available)
    • iPhone Xs • 48A89E82-FD4D-4B65-8692-BBDB0520F01E • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone Xʀ • 0E27C4F1-726B-4263-9F85-09CFE04D8C4B • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zzyy3321** [comment] 2019-05-08 06:25
after the Dart upgrade(Maybe),I have the same problem 
---
Flutter crash report; 

## command

flutter attach -d BEBDED2C-8B07-4D2C-9CC0-1008F491B6C4

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-HK)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/zhangyang/Desktop/SourceCode/flutter
    [32m•[39m Framework revision 7a4c33425d (8 天前), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/zhangyang/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/zhangyang/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/zhangyang/Library/Android/sdk
    [32m•[39m Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.33.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xs Max • BEBDED2C-8B07-4D2C-9CC0-1008F491B6C4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by zzyy3321** [comment] 2019-05-09 08:21
well, switch flutter to master channel and upgrade, can fix it.

in your flutter SDK folder
```
$ flutter channel master
$ flutter upgrade
```

**Comment by gscool** [comment] 2019-05-10 07:43
> well, switch flutter to master channel and upgrade, can fix it.
> 
> in your flutter SDK folder
> 
> ```
> $ flutter channel master
> $ flutter upgrade
> ```

I have the  same question,and I switch to master channel and upgrade,but it can not work.

**Comment by YoungJam** [comment] 2019-05-10 14:40
> > well, switch flutter to master channel and upgrade, can fix it.
> > in your flutter SDK folder
> > ```
> > $ flutter channel master
> > $ flutter upgrade
> > ```
> 
> I have the same question,and I switch to master channel and upgrade,but it can not work.

Switch to stable channel is work.

**Comment by gscool** [comment] 2019-05-11 01:24
> > > well, switch flutter to master channel and upgrade, can fix it.
> > > in your flutter SDK folder
> > > ```
> > > $ flutter channel master
> > > $ flutter upgrade
> > > ```
> > 
> > 
> > I have the same question,and I switch to master channel and upgrade,but it can not work.
> 
> Switch to stable channel is work.

I tried all the channels, but all had the same question.

**Comment by armadilov** [comment] 2019-05-21 06:47
I had issues on stable channel, but I just tried that on 'dev' channel and it's working fine there:

`Flutter (Channel dev, v1.6.0, on Mac OS X 10.14.4 18E226, locale en-PL)`

**Comment by shenyuexin** [comment] 2019-06-27 12:35
I have the same question on Flutter version 1.5.4-hotfix.2

**Comment by janmoppel** [comment] 2019-10-15 07:43
Hello @YoungJam !

Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment] 2019-11-08 10:45
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by joshuadeguzman** [comment] 2019-11-22 13:48
`flutter attach` works okay on the stable channel, v1.9.1+hotfix.6. However, as of the moment, not working on the latest master channel. 

Here's the error.
```
NoSuchMethodError: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
```

Hope it helps.

**Comment by iapicca** [comment] 2019-11-22 15:07
Hi @joshuadeguzman 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by joshuadeguzman** [comment] 2019-11-22 15:33
Hi @iapicca, 

Thanks for the quick response. 

This is the exact codebase I'm trying to run on the master channel via `flutter attach`.
https://github.com/joshuadeguzman/devfest-flutter-to-native

Switching to the latest stable channel introduced this error:
23465

**Comment by joshuadeguzman** [comment] 2019-11-26 07:01
Hi, do we have any updates on this?

**Comment by jmagman** [comment] 2020-01-23 02:01
Duplicate of https://github.com/flutter/flutter/issues/40225, fixed in https://github.com/flutter/flutter/pull/32126 in 1.6.0.

**Closed by jmagman** 2020-01-23 02:01 UTC
Labels: severe: crash, severe: regression, tool, ⌺‬ platform-ios
