### ISSUE TITLE
Textfiled have a onTapOutside func, I override this func to unfocus textfiled but not work

### ISSUE THREAD

**Issue by luohao123** [flutter/flutter#125411] opened 2023-04-24 14:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

this is my textfiled:

```
TextField(
                        controller: _textController,
                        cursorColor: getThemeColorOnPrimaryContainer(context),
                        decoration: InputDecoration(
                            isCollapsed: true,
                            border: InputBorder.none,
                            hintText: "Messages..."),
                        focusNode: _inputFocusNode,
                        keyboardType: TextInputType.multiline,
                        textInputAction: widget.textInputAction,
                        maxLines: 5,
                        minLines: 1,
                        onSubmitted:
                            widget.textInputAction == TextInputAction.go
                                ? _handleSendPressedString
                                : null,
                        onChanged: widget.options.onTextChanged,
                        style: TextStyle(
                            color: getThemeColorOnPrimaryContainer(context)),
                        onTap: widget.options.onTextFieldTap,
                        onTapOutside: _handleTapInputOutside,
                        textCapitalization: TextCapitalization.sentences,
                      ),
```

the `onTapOutside` function is really annoying, I wannt textfiled tapped to pop up softkeyboard, but not the outside of textfiled,

so I override it, but it still keeps pops up soft keyboard

```
  void _handleTapInputOutside(PointerDownEvent e) {
    // widget.options.onTextFieldTap!();
    debugPrint("tap outside do nothing?");
    FocusScope.of(context).unfocus();
  }
```

### Expected results

I need textfiled onTapOutside do not popup keyboard

### Actual results

no

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by superciccio** [comment] 2023-04-24 15:09
Hi,

I just tried and it works as intended, you need to use **_inputFocusNode** and in your method do  **_focusNode.unfocus();**

That's all :)

**Comment by huycozy** [comment] 2023-04-25 06:01
@luohao123 There are several ways to handle this. You can use above solution as @superciccio mentioned. Or wrap your parent widget (outside area) with a `GestureDetector` and request focus when tapping on it.

Closing this issue since it works as intended. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Thanks!

**Closed by huycozy** 2023-04-25 06:01 UTC
Labels: in triage
