### ISSUE TITLE
Flutter IOS connect with firebase

### ISSUE THREAD

**Issue by ekahoggy** [flutter/flutter#53083] opened 2020-03-23 09:11 UTC
Hello everyone.
I ask that you please help fix this.

I run on Android and it works, but for iOS, Firebase doesn't want to be connected.

this is my error.

`2020-03-23 16:06:47.741442+0700 Bolong[95722:414976] flutter: Observatory listening on http://127.0.0.1:57868/UUfr8O6UpF4=/
2020-03-23 16:06:47.760548+0700 Bolong[95722:414956] 6.19.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60301000 started
2020-03-23 16:06:47.761003+0700 Bolong[95722:414956] 6.19.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-03-23 16:06:48.040753+0700 Bolong[95722:414948] 6.19.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2020-03-23 16:06:48.066761+0700 Bolong[95722:414947] 6.19.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-03-23 16:06:49.812497+0700 Bolong[95722:414948] 6.19.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-03-23 16:06:49.875485+0700 Bolong[95722:414958] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
#0      UserBloc.getUserData (package:bolong/blocs/user_bloc.dart:39:28)
<asynchronous suspension>
#1      _HomePageState.initState.<anonymous closure> (package:bolong/pages/home.dart:220:10)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#7      Future._complete (dart:async/future_impl.dart:514:7)
#8      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
#9      _rootRun (dart:async/zone.dart:1122:38)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
2020-03-23 16:06:49.879102+0700 Bolong[95722:414958] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
#0      BookmarkBloc.getData (package:bolong/blocs/bookmark_bloc.dart:17:28)
<asynchronous suspension>`

<img width="811" alt="info" src="https://user-images.githubusercontent.com/12228588/77300484-aef69c80-6d20-11ea-9a55-d9a0c1031897.png">
<img width="807" alt="google service" src="https://user-images.githubusercontent.com/12228588/77300497-b322ba00-6d20-11ea-8e8b-765f6ca4f08d.png">

**Comment by iapicca** [comment] 2020-03-23 11:43
Hi @ekahoggy 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-23 11:43 UTC
