### ISSUE TITLE
After iOS is upgraded to 17, TextField cannot be entered on the keyboard.

### ISSUE THREAD

**Issue by wuwenwei5566** [flutter/flutter#133908] opened 2023-09-02 13:07 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

TextField Input text

### Expected results

Normal input text

### Actual results

Unable to enter text properly

### Code sample

```dart
TextField(
          autofocus: widget.autofocus,
          textAlign: widget.textAlign,
          controller: widget.controller,
          keyboardAppearance: widget.keyboardAppearance ?? _checkThemeDrak(),
          focusNode: widget.focusNode,
          scrollController: widget.scrollController,
          keyboardType: widget.keyboardType,
          textInputAction: widget.textInputAction,
          scrollPhysics: widget.scrollPhysics,
          selectionControls: widget.selectionControls,
          maxLines: widget.maxLines,
          maxLength: widget.maxLength,
          minLines: widget.minLines,
          cursorHeight: setCursorHeight(),
          cursorColor: widget.cursorColor ?? ThemeColor.themeColor(context),
          style: widget.style,
          enableInteractiveSelection: widget.enableInteractiveSelection,
          //onTap: widget.onTap,
          decoration: widget.decoration,
          onEditingComplete: widget.onEditingComplete,
          onAppPrivateCommand: widget.onAppPrivateCommand,
          onSubmitted: widget.onSubmitted,
          onChanged: widget.onChanged,
          inputFormatters: widget.inputFormatters,
          scrollPadding: widget.scrollPadding,
          textAlignVertical: widget.textAlignVertical,
          obscureText: widget.obscureText,
          obscuringCharacter: widget.obscuringCharacter,
          readOnly: widget.readOnly,
          clipBehavior: widget.clip,
        ),

``` 
### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/52393077/be3acac9-b9de-41dc-bb9e-c80f84a21ecf

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[!] Flutter (Channel [user-branch], 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.2 on channel [user-branch] at /Users/wuwenwei/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ff5b5b5fa6 (9 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.
```

**Comment by benzidane027** [comment] 2023-09-02 23:52
did you try with another keyboard apps ??

**Comment by wuwenwei5566** [comment] 2023-09-03 02:03
> did you tried with another keyboard apps ??

No, not other apps, not even the ones I wrote in swift.

**Comment by wuwenwei5566** [comment] 2023-09-04 03:22
> did you tried with another keyboard apps ??

**Comment by wuwenwei5566** [comment] 2023-09-04 03:23
How can this problem be solved?

**Comment by wuwenwei5566** [comment] 2023-09-04 03:26
I used the simplest example, and that's what happens
https://github.com/flutter/flutter/assets/52393077/fd1e5aeb-09ce-4a39-9840-391bbf3fd9a5
![1693794127](https://github.com/flutter/flutter/assets/52393077/b3ead7e7-955a-4528-ace4-089c9721b026)

**Comment by dam-ease** [comment] 2023-09-04 11:41
Hi @wuwenwei5566. Thanks for filing this. Please can you test with other keyboard languages to check with which keyboard languages this issue occurs?

**Comment by wuwenwei5566** [comment] 2023-09-04 13:10
This bug appears in the Chinese nine-gong grid keyboard

**Comment by wuwenwei5566** [comment] 2023-09-04 13:10
@dam-ease

**Comment by wuwenwei5566** [comment] 2023-09-05 08:08
@dam-ease This bug will appear on any Chinese keyboard. Do you know how to fix this bug?

**Comment by huycozy** [comment] 2023-09-05 09:33
I can reproduce this issue on iPhone 14 Pro, iOS 17.0 (emulator) with Chinese keyboard (Simplified - Pinyin). The code sample is only using a minimal `TextField()` widget.

### Additional info
- If I switch to another keyboard (English, Japanese) and then switch back to Chinese keyboard, the issue doesn’t happen (but only sometimes). Let's watch the demo video below.

- Also, I see there is exception stack trace from the output console.

- As confirmed by @dam-ease, the issue doesn't appear on iOS 16.4.

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/738c2161-53b2-4918-b54d-18ac02ef22e0

</details>

<details>
<summary>Output exception</summary>

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.updateEditingState:
Range end 2 is out of text of length 1
'package:flutter/src/services/text_input.dart':
Failed assertion: line 965 pos 12: 'range.end >= 0 && range.end <= text.length'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      TextEditingValue._textRangeIsValid (package:flutter/src/services/text_input.dart:965:12)
#3      new TextEditingValue.fromJSON (package:flutter/src/services/text_input.dart:790:12)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1851:57)
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#9      _invoke2 (dart:ui/hooks.dart:202:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
(elided 2 frames from class _AssertionError)

call:
  MethodCall(TextInputClient.updateEditingState, [1, {selectionBase: 1, composingExtent: 2,
  selectionAffinity: TextAffinity.downstream, text: n, selectionIsDirectional: false,
  selectionExtent: 1, composingBase: 1}])
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Range end 1 is out of text of length 0

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (12 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-14.0.pre.93, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-14.0.pre.93 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef9befc9da (33 hours ago), 2023-09-03 11:23:20 -0700
    • Engine revision fbc6f4a540
    • Dart version 3.2.0 (build 3.2.0-131.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by vashworth** [comment] 2023-09-05 21:34
@hellohuanlin or @cyanglaz Can either of you take a look at this?

**Comment by zhangyanzhu88** [comment] 2023-09-06 05:19
@dam-ease![上传image.png...]()
I think this is probably caused by you guys fixing the ios17 text auto-correction problem

**Comment by zhangyanzhu88** [comment] 2023-09-06 05:22
@dam-ease I think this is probably caused by you guys fixing the ios17 text auto-correction problem

https://github.com/flutter/flutter/issues/132763 - Fixes auto-correction position in iOS 17.

**Comment by stuartmorgan** [comment] 2023-09-06 13:44
> @dam-ease I think this is probably caused by you guys fixing the ios17 text auto-correction problem
> 
> #132763 - Fixes auto-correction position in iOS 17.

So you were not able to reproduce this on iOS 17 with a version of Flutter before that fix landed?

**Comment by hellohuanlin** [comment] 2023-09-06 18:27
@zhangyanzhu88 thanks for the finding. Let me quickly verify this, and revert if needed.

**Comment by zhangyanzhu88** [comment] 2023-09-07 02:24
@stuartmorgan It is easily reproducible.
with flutter3.13.1, it is possible to operate a Chinese keyboard for the first time

**Comment by zhangyanzhu88** [comment] 2023-09-07 02:33
@hellohuanlin thanks,look forward to your reply

**Comment by zhangyanzhu88** [comment] 2023-09-07 02:42
@stuartmorgan @hellohuanlin I tried flutter version 3.13.0 and didn't have this problem, but flutter version 3.13.1 have this problem

**Comment by litang0908** [comment] 2023-09-07 08:05
Same problem, here is some info:

**Flutter Version**
```
 Flutter version 3.13.1 on channel stable at /Users/tangyc/Documents/softs2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 weeks ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

```

**iPhone System Version:**
![image](https://github.com/flutter/flutter/assets/44760239/7010d141-1ad7-495f-aa64-92317e148042)


Here is the video:

https://github.com/flutter/flutter/assets/44760239/011fedb5-a2f9-446e-b2ec-4afead808fc9

**Closed** 2023-09-07 20:11 UTC
Labels: a: text input, c: crash, platform-ios, a: internationalization, e: OS-version specific, has reproducible steps, P1, team-ios, found in release: 3.13, found in release: 3.14
