### ISSUE TITLE
Baseline alignment breaks intrinsic height

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#65895] opened 2020-09-15 22:34 UTC
### Steps to reproduce

Run the following app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ColoredBox(
          color: Color(0xffffffff),
          child: Row(
            textDirection: TextDirection.ltr,
            crossAxisAlignment: CrossAxisAlignment.baseline,
            children: [
              BoxedBaseline(width: 50, height: 50, baseline: 25),
              BoxedBaseline(width: 100, height: 100, baseline: 10),
              BoxedBaseline(width: 100, height: 100, baseline: 90),
            ],
          ),
        ),
      ],
    );
  }
}

class BoxedBaseline extends LeafRenderObjectWidget {
  const BoxedBaseline({this.width, this.height, this.baseline});

  final double width;
  final double height;
  final double baseline;

  @override
  RenderObject createRenderObject(BuildContext context) {
    return RenderBoxedBaseline(
      width: width,
      height: height,
      baseline: baseline,
    );
  }

  @override
  void updateRenderObject(BuildContext context, RenderBoxedBaseline renderObject) {
    renderObject
      ..width = width
      ..height = height
      ..baseline = baseline;
  }
}

class RenderBoxedBaseline extends RenderBox {
  RenderBoxedBaseline({
    double width,
    double height,
    double baseline,
  }) {
    this.width = width;
    this.height = height;
    this.baseline = baseline;
  }

  double _width;
  double get width => _width;
  set width(double value) {
    _width = value;
    markNeedsLayout();
  }

  double _height;
  double get height => _height;
  set height(double value) {
    _height = value;
    markNeedsLayout();
  }

  double _baseline;
  double get baseline => _baseline;
  set baseline(double value) {
    _baseline = value;
    markNeedsLayout();
  }

  @override
  double computeMinIntrinsicWidth(double height) => width;

  @override
  double computeMaxIntrinsicWidth(double height) => width;

  @override
  double computeMinIntrinsicHeight(double width) => height;

  @override
  double computeMaxIntrinsicHeight(double width) => height;

  @override
  double computeDistanceToActualBaseline(TextBaseline _) => baseline;

  @override
  bool get sizedByParent => true;

  @override
  void performResize() {
    size = constraints.constrainDimensions(width, height);
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    Paint paint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1
      ..color = Color(0xff000000);
    Rect rect = offset & size;
    context.canvas.drawRect(rect.deflate(0.5), paint);
    paint.color = Color(0xffff0000);
    context.canvas.drawLine(
      offset + Offset(0, baseline),
      offset + Offset(size.width, baseline),
      paint,
    );
  }
}
```

That app produces the following, correctly:

![boxes](https://user-images.githubusercontent.com/15253456/93271227-9ca56a80-f767-11ea-9d2f-261efb3fb115.png)

... then apply the following change to the app:

```diff
@@ -11,6 +11,7 @@ class BugReport extends StatelessWidget {
       children: [
         ColoredBox(
           color: Color(0xffffffff),
+          child: IntrinsicHeight(
             child: Row(
               textDirection: TextDirection.ltr,
               crossAxisAlignment: CrossAxisAlignment.baseline,
@@ -21,6 +22,7 @@ class BugReport extends StatelessWidget {
               ],
             ),
           ),
+        ),
       ],
     );
   }
```

... and refresh the app.

### Expected behavior

You expect the same behavior as before you added the `IntrinsicHeight` wrapper.

### Actual behavior

The `Row` reports its intrinsic height incorrectly, 'causing the app to look like this:

![boxes](https://user-images.githubusercontent.com/15253456/93271498-45ec6080-f768-11ea-9864-3adac9880806.png)

### Diagnosis

`RenderBox.computeDistanceToActualBaseline()` only works post-layout.  There's currently no way in the framework for a `RenderBox` to say "if I were size S, then my baseline would be B".  Thus, when the `Row` is asked for its intrinsic height, which is affected by the would-be baselines of its children, it has no way of knowing their would-be baselines.

### Flutter version

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.153, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.22.0-10.0.pre.153 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 2e643651a9 (4 days ago), 2020-09-11 23:07:03 -0400
    • Engine revision 16b900b63e
    • Dart version 2.10.0 (build 2.10.0-117.0.dev)
```

**Comment by tvolkert** [comment] 2020-09-15 23:45
Given the current framework APIs, there's no way to solve this -- we'd need to augment the framework in some way.

One way to solve this would be to add a `RenderBox.computeWouldBeDistanceToBaseline(Size size)` or some such named method.  The semantics of the method would be "if I were given the specified size, my baseline would be X".  We would provide a default base implementation that returned null (don't support baseline) as well as implementations in stuff like [`RenderProxyBoxMixin`](https://github.com/flutter/flutter/blob/ea039ed3f9370bd03749c0e9aad401d1d7d486da/packages/flutter/lib/src/rendering/proxy_box.dart#L66)...

The drawbacks are:

1. Render object would have a new method that they need to worry about implementing.  But it would at least be no worse than today, since the only call-sites of the new method would be new code paths that were introduced to fix broken behavior today (like [`RenderFlex._getIntrinsicSize()`](https://github.com/flutter/flutter/blob/ea039ed3f9370bd03749c0e9aad401d1d7d486da/packages/flutter/lib/src/rendering/flex.dart#L509))
1. It would introduce a third layout code path (current two are `performLayout()` and the `compute...Intrinsic...()` methods)

**Comment by znjameswu** [comment] 2020-09-17 03:14
I thought this was by design when I was reading RenderFlex's code. Glad to hear you guys are going to fix this contract.

But the proposed way sounds strange. In my understanding, any valid implementation of `RenderBox.computeWouldBeDistanceToBaseline(Size size)` would be equivalent to `performLayout()` with `BoxContraints.tight(size)` and then `computeDistanceToActualBaseline()`, because it is requesting the very same piece of layout information, no more and no less. This is different to `compute...Intrinsic...` that implies some inherent properties across layouts.

From personal point of view, I don't quite get the idea of intrinsic computation instead of a full-blown speculative layout...

**Comment by TahaTesser** [comment] 2020-09-17 07:39
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ColoredBox(
          color: Color(0xffffffff),
          child: IntrinsicHeight(
            child: Row(
              textDirection: TextDirection.ltr,
              crossAxisAlignment: CrossAxisAlignment.baseline,
              children: [
                BoxedBaseline(width: 50, height: 50, baseline: 25),
                BoxedBaseline(width: 100, height: 100, baseline: 10),
                BoxedBaseline(width: 100, height: 100, baseline: 90),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

class BoxedBaseline extends LeafRenderObjectWidget {
  const BoxedBaseline({this.width, this.height, this.baseline});

  final double width;
  final double height;
  final double baseline;

  @override
  RenderObject createRenderObject(BuildContext context) {
    return RenderBoxedBaseline(
      width: width,
      height: height,
      baseline: baseline,
    );
  }

  @override
  void updateRenderObject(
      BuildContext context, RenderBoxedBaseline renderObject) {
    renderObject
      ..width = width
      ..height = height
      ..baseline = baseline;
  }
}

class RenderBoxedBaseline extends RenderBox {
  RenderBoxedBaseline({
    double width,
    double height,
    double baseline,
  }) {
    this.width = width;
    this.height = height;
    this.baseline = baseline;
  }

  double _width;
  double get width => _width;
  set width(double value) {
    _width = value;
    markNeedsLayout();
  }

  double _height;
  double get height => _height;
  set height(double value) {
    _height = value;
    markNeedsLayout();
  }

  double _baseline;
  double get baseline => _baseline;
  set baseline(double value) {
    _baseline = value;
    markNeedsLayout();
  }

  @override
  double computeMinIntrinsicWidth(double height) => width;

  @override
  double computeMaxIntrinsicWidth(double height) => width;

  @override
  double computeMinIntrinsicHeight(double width) => height;

  @override
  double computeMaxIntrinsicHeight(double width) => height;

  @override
  double computeDistanceToActualBaseline(TextBaseline _) => baseline;

  @override
  bool get sizedByParent => true;

  @override
  void performResize() {
    size = constraints.constrainDimensions(width, height);
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    Paint paint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1
      ..color = Color(0xff000000);
    Rect rect = offset & size;
    context.canvas.drawRect(rect.deflate(0.5), paint);
    paint.color = Color(0xffff0000);
    context.canvas.drawLine(
      offset + Offset(0, baseline),
      offset + Offset(size.width, baseline),
      paint,
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.204, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.204 at /Users/tahatesser/Code/flutter_master
    • Framework revision b2b5f2636a (17 hours ago), 2020-09-16 08:02:06 -0700
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 85.0.4183.102
    ! Error: Taha’s iPhone is busy: Copying cache files from device. Xcode will continue when Taha’s iPhone is finished. (code -10)

• No issues found!


```

</details>

**Comment by goderbauer** [comment] 2020-11-09 22:21
While it's a missing feature that we can't compute the intrinsics for baseline metrics, it's also a bug that we silently produce an unexpected result. Given our own documentation for [computeMinIntrinsicWidth](https://master-api.flutter.dev/flutter/rendering/RenderBox/computeMinIntrinsicWidth.html) under "When the intrinsic dimensions cannot be known" we should be throwing in the intrinsics methods of RenderFlex if we can't calculate the metrics when the alignment is baseline. We already due that in other places of the framework, see for example the `_canComputeIntrinsics` check in `RenderParagraph`:

https://github.com/flutter/flutter/blob/e3bb51fa1f68cc4b88f02d0ce45bba6b166a4549/packages/flutter/lib/src/rendering/paragraph.dart#L370-L391

While obviously not a fix for this issue, I wonder how breaking it would be to actually add such an assert to RenderFlex to at least tell people upfront that what they are doing is not supported instead of silently ignoring the baseline...

**Comment by TahaTesser** [comment] 2022-12-14 12:18
Hey @goderbauer!
Given adding assertion wasn't a breaking issue. I feel safe to close this issue, as fixed.
Please reopen if you want to take further action on this issue.

**Closed by TahaTesser** 2022-12-14 12:18 UTC
Labels: framework, a: layout, has reproducible steps, P4, found in release: 1.22
