### ISSUE TITLE
[Camera] Added support for flash/torch mode in iOS and Android

### ISSUE THREAD

**Issue by nombrekeff** [flutter/flutter#66252] opened 2020-09-21 10:25 UTC
Hello, I have been looking all over the place for a way of using flash with Flutter camera. But have been unsuccessful.

#### Question
Is there any way of using flash with flutter camera? Or are you working on it?

#### What I've tried
I have tried a couple of plugins, including flash_camera and lamp, none of them work.

If I manually start the lamp on my phone, when I open the camera in flutter app it turns off.

#### My Usage

We need to use it in a project at work, it's quite a critical feature as our customers need to take pictures at night and can't without a flash/lamp.

#### Versions
Flutter: 1.17.5 
Camera: 0.5.7+2

I'm sorry if this has been reported before or you have already explained it. But have not been able to find it.

Cheers!

**Comment by TahaTesser** [comment] 2020-09-21 13:20
Hi @nombrekeff 
There is a PR to add this feature, it mentions some closed issues, so I am labelling and it should be closed when https://github.com/flutter/plugins/pull/2837 is landed, meanwhile you can git dependency to use PR code . Follow this https://github.com/flutter/plugins/pull/2837#issuecomment-661188756
Thank you

**Comment by nombrekeff** [comment] 2020-09-21 13:30
Wonderful stuff, thanks a lot for the quick reply 👍  I will try the PR code and wait for it to land before using it in production.

**Comment by mvanbeusekom** [comment] 2020-12-15 09:40
Duplicate of #19845

**Closed by mvanbeusekom** 2020-12-15 09:40 UTC
Labels: p: camera, p: first party, passed first triage, plugin, severe: new feature, waiting for PR to land (fixed)
