### ISSUE TITLE
Windows desktop App TextField widget 使用小键盘输入数字时会出现问题

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#53146] opened 2020-03-24 02:58 UTC
## 在 Flutter desktop Windows  App 运行时发现问题：
1. TextField widget 使用小键盘输入数字时会出现问题，比如按‘4’键 光标会左移一位，‘7’键会回到第一个字符位置 
 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-03-24 07:53
Using Google Translate 

"TextField widgets have problems entering numbers using the keypad, such as pressing the '4' key, the cursor will move to the left, and the '7' key will return to the first character position"

**Comment by stuartmorgan** [comment] 2020-03-24 13:44
Duplicate of #51431

**Closed by stuartmorgan** 2020-03-24 13:44 UTC
Labels: a: text input, framework, waiting for customer response, ❖ platform-windows
