### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for D:\flutter\simoki\android\gradlew.bat.

### ISSUE THREAD

**Issue by Ester-coder** [flutter/flutter#67220] opened 2020-10-03 12:57 UTC
## Command
```
flutter build apk --target-platform android-arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for D:\flutter\simoki\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:114:26)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#15     _rootRun (dart:async/zone.dart:1184:13)
#16     _CustomZone.run (dart:async/zone.dart:1077:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 6.1.7601], locale id-ID)
    • Flutter version 1.17.5 at D:\Android\flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\PENGELOLA\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\PENGELOLA\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\PENGELOLA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_database-3.1.6
flutter_facebook_login-3.0.0
google_sign_in-4.4.2
google_sign_in_web-0.8.4
shared_preferences-0.5.6+3
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4

**Comment by iapicca** [comment] 2020-10-03 14:48
possible duplicate of https://github.com/flutter/flutter/issues/56975

**Comment by darshankawar** [comment] 2020-10-05 09:54
@Ester-coder 
Please upgrade to latest stable as suggest above and try again to see if it works.
If problem persists, please follow-up in [56975](https://github.com/flutter/flutter/issues/56975).
closing as duplicate.

**Closed by darshankawar** 2020-10-05 09:54 UTC
