### ISSUE TITLE
[Draft] Passing a null iconAlignment value to the ButtonStyleButton*.icon() constructor(s) returns an error.

### ISSUE THREAD

**Issue by denisbganev** [flutter/flutter#159240] opened 2024-11-21 02:26 UTC
### Summary
Passing a null/-able iconAlignment value to the ButtonStyleButton*.icon() constructor(s) returns an error.

### Code Sample:
```
Widget customButton({
	required String label, 
	Icon? buttonIcon, 
	IconAlignment? iconAlignment, }) {

	return ElevatedButton.icon( 
		label: Text(label), 
		icon: buttonIcon, 
		iconAlignment: iconAlignment ); 
}
```

### Expected Results:
`iconAlignment` would be nullable, as `icon` is nullable and has a default fallback returning an iconless constructor.

### Actual Results:
**Error Message**
___
> Error: The argument type 'IconAlignment?' can't be assigned to the parameter type 'IconAlignment' because 'IconAlignment?' is nullable and 'IconAlignment' isn't.
___

### Flutter Doctor output:
n/a

**Comment by navaronbracke** [comment] 2024-11-21 07:39
What Flutter version are you using?

If I paste the following into Dartpad, it does not reproduce:

```dart
  Widget customButton({
    required String label,
    Icon? buttonIcon,
    IconAlignment? iconAlignment,
  }) {
    return ElevatedButton.icon(
      label: Text(label),
      icon: buttonIcon,
      iconAlignment: iconAlignment,
      onPressed: null, // Added this line, since it is a required argument
    );
  }
```

Instead, I get `The argument type 'IconAlignment?' can't be assigned to the parameter type 'IconAlignment' because 'IconAlignment?' is nullable and 'IconAlignment' isn't.` which is expected behavior when running with null-safety.

I used the current stable channel to test this (Flutter 3.24 / Dart 3.5) but this should also work on older versions of Dart, that support sound null safety.

**Comment by bleroux** [comment] 2024-11-21 07:55
It would probably makes sense to update the title and the description to make it clear that the problem reported here is not a runtime error but a null-safety issue related to ButtonStyleButton.iconAligment not allowing null value.

**Comment by huycozy** [comment] 2024-11-21 09:07
@denisbganev As I can see from the given sample code, the error is working as intended, the current `iconAlignment` is non-nullable (Flutter version `3.27.0-1.0.pre.573`):

https://github.com/flutter/flutter/blob/f7869a47993d49ce640dbd7b719d551a4e00ccf2/packages/flutter/lib/src/material/button_style_button.dart#L161

Unless you come up with a more suitable use case or simply propose what you pointed out in the `Expected result` section. So can you please update the issue's title and description to ensure we are on the same page here?

**Comment by bleroux** [comment] 2024-12-04 05:17
Closing as fixed by https://github.com/flutter/flutter/pull/158503

**Closed by bleroux** 2024-12-04 05:17 UTC
Labels: waiting for customer response, in triage
