### ISSUE TITLE
[firebase_messaging] Push message onMessage is different from onLaunch/onResume

### ISSUE THREAD

**Issue by josejbarneto** [flutter/flutter#37375] opened 2019-08-01 08:21 UTC
Im using:
firebase_messaging: ^5.1.2

Sending same msg, when app is foreground

`onMessage`

>I/flutter (27310):  - ON MESSAGE NOTIFICATION - {notification: {title: Notification title, body: Notification body}, data: {origin: NEXTCADDY, id: 18208, body: Data body, tipo: h, title: data title, click_action: FLUTTER_NOTIFICATION_CLICK}}

When app is background and I click the notification .

`onResume`

>I/flutter (27310):  - ON RESUME NOTIFICATION - {notification: {}, data: {tipo: h, google.original_priority: high, google.sent_time: 1564646918915, google.delivered_priority: high, origin: NEXTCADDY, body: Data body, title: Data title, click_action: FLUTTER_NOTIFICATION_CLICK, google.message_id: 0:1564646918938454%3ae01afb3ae01afb, collapse_key: com.nextcaddy.nextapp, google.ttl: 2419200, from: 765388977506, id: 18208}}

As you can see the notification is empty.

This is supposed to be fixed in [fix message structure from intent #957](https://github.com/flutter/plugins/pull/957) but im still having troubles, any help?

**Comment by BondarenkoStas** [comment] 2019-09-19 22:58
@josejbarneto Do you still encounter the issue? Can you try with upgraded version of firebase_messaging? And please provide your ```flutter doctor -v```.

**Comment by iapicca** [comment] 2019-11-11 16:15
Hi @josejbarneto 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 16:15 UTC
Labels: waiting for customer response
