### ISSUE TITLE
SingleChildScrollView glitching after keyboard overlap with material3

### ISSUE THREAD

**Issue by nicoladev02** [flutter/flutter#121458] opened 2023-02-25 19:02 UTC
## Steps to Reproduce

**I encountered this bug only using material 3**

1. Execute `flutter run` on the code sample
2. Tap on the TextField, wait for the keyboard to open.
3. Scroll to the bottom of the page with the keyboard open.
4. Tap on the "done" keyboard button to close the keyboard
5. When the keyboard is closed the page will automatically scroll to the top causing a glitch if trying to scroll later (see the video example)

**Expected results:** 
No glitch

**Actual results:**
Glitch on scroll even if the screen should not be scrollable.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: SafeArea(
          child: SingleChildScrollView(
            child: Column(
              children: [
                const Text('SCROLL BUG EXAMPLE'),
                TextFormField(
                  decoration: const InputDecoration(hintText: 'Input test'),
                ),
                Container(
                  color: Colors.black,
                  height: 600,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

```
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-IT)
    • Flutter version 3.7.5 on channel stable at /Users/nicolamazzocato/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (3 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nicolamazzocato/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • RMX3363 (mobile)           • adb-3b119d40-vOPpSc._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 9E40BDA8-8B3A-45F3-B407-2812A617FF62       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                                     • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/101998560/221374920-5743de10-baf6-4320-8410-c2b563a9a75b.mp4

**Comment by AbhishekDoshi26** [comment] 2023-02-25 19:25
https://user-images.githubusercontent.com/52591247/221375799-3e1dfc31-6338-4f01-85e3-c3edbb5dda65.mov

I tested it, but was not able to reproduce.

CC: @stuartmorgan

**Comment by nicoladev02** [comment] 2023-02-25 19:39
@stuartmorgan 
Don't know if it is because you're on an emulator. 
Try to close the keyboard through the done keyboard button when page is scrolled down (don't scroll up manually).
I also tried with another device (Samsung galaxy s6 lite 2020)

https://user-images.githubusercontent.com/101998560/221376361-cb919146-5cfd-444f-9d4a-422408e00d32.mp4

**Comment by stuartmorgan** [comment] 2023-02-25 21:43
> CC: @stuartmorgan

Why was I cc'd? I don't know what action you are looking for from me here.

**Comment by huycozy** [comment] 2023-02-27 13:12
I also can not reproduce this issue on my device (`Samsung Galaxy Tab A7 Lite, Android 13 OneUI 5.0, SM-T225`). Perhaps there is a necessary step that I may miss it. 

<details>
<summary>Demo video (not reproduce)</summary>

https://user-images.githubusercontent.com/104349824/221572367-3e07c3ae-8d69-4f67-b3d6-7e9d070824b0.mp4

</details>

@nicoladev02 It seems your Samsung device is on Android 12, doesn't it? Can you be more specific on `Steps to reproduce`?

**Comment by nicoladev02** [comment] 2023-02-27 13:27
@huycozy I just updated the issue steps. 
I tried on two devices, the first running android 12 and the second running Android 13.

I think you can't reproduce the issue because you press the keyboard done button when the page is already scrolled to the top. Try to press the done keyboard after the page has been scrolled to the bottom. Increase the container height if you're testing on a large screen.

if I failed to explain myself let me know, thank you :)

**Comment by huycozy** [comment] 2023-02-28 09:15
Thanks for providing more information but I still can not reproduce this. 

To make this clearer, I added a ScrollBar and increased the black Container height to 1200:

<details>
<summary>Demo (no issue)</summary>

https://user-images.githubusercontent.com/104349824/221806755-bb801e89-6e3d-42f1-994f-fb0b596f3232.mov

</details>

Verified on the both latest Flutter channels: stable 3.7.5 and master 3.8.0-17.0.pre.39.

Which gesture did you perform after closing the keyboard (from 0:08 in video timeline), just pulling down?

**Comment by nicoladev02** [comment] 2023-02-28 10:04
This is so weird.. yeah after closing the keyboard I just pull down. 

I tried again with the Pixel 6 Pro emulator running Android 13 and had a similar result

https://user-images.githubusercontent.com/101998560/221818235-4e96e483-9d7c-4dce-b039-ab61bf402422.mov

---

And this result with a Realme GT running Android 12


https://user-images.githubusercontent.com/101998560/221819361-e67dac3e-263f-4e49-a4ee-50b889aa3aab.mp4

---

Setting the useMaterial3 flag to false I didn't encounter any problems

https://user-images.githubusercontent.com/101998560/221821121-05edf888-13b8-4f12-ac5c-344bd39c2b03.mp4

**Comment by huycozy** [comment] 2023-03-01 08:28
@nicoladev02 It seems to be a device-specific issue. And I see the issue is more visible on your Realme GT device rather than on your other devices. Are you able to reproduce this issue with the Android native project on your device?

**Comment by nicoladev02** [comment] 2023-03-01 09:08
@huycozy You're right it is more visible on the Realme, I just tried with the Android native project and I noticed the same issue

**Comment by huycozy** [comment] 2023-03-01 12:42
@nicoladev02 Thanks for confirming. It seems to be a specific-device's issue so we are unfortunately not sure how to resolve this issue.

We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! 

Thanks for your contribution!

**Closed by huycozy** 2023-03-01 12:42 UTC
Labels: in triage
