### ISSUE TITLE
Video disappears on iOS when any other native view comes up on top of the app

### ISSUE THREAD

**Issue by alexandranb** [flutter/flutter#60769] opened 2020-07-02 13:43 UTC
Hello everybody! 
I have the same issue that is described here in this issue, that was closed. Could someone help me? Or how was this issue solved?
I am running the last stable flutter version.
Thank you in advance!

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.5 at /Users/evonomix/flutter
    • Framework revision 8af6b2f038 (2 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1
```
https://github.com/flutter/flutter/issues/55783
This issue apparently was closed but the issue still exists.

**Comment by VladyslavBondarenko** [comment] 2020-07-02 16:29
Hi @alexandranb 
what device are you using? does it persist with current beta?

**Comment by VladyslavBondarenko** [comment] 2020-07-03 08:45
@alexandranb 
I can reproduce it with [example project](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example) on current stable `1.17.5`, but not with current beta `1.19.0-4.3.pre`.
You can use beta, or wait until the fix comes to stable.
Closing since there is not need to track the issue

**Closed by VladyslavBondarenko** 2020-07-03 08:45 UTC
Labels: in triage, waiting for customer response
