### ISSUE TITLE
Perf tests need 2 versions: (1) the app is freshly installed (2) the app is already installed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#68728] opened 2020-10-21 17:50 UTC
The performance metrics could be very different between those 2 versions so we need to track both and prevent regressions in either case.

Related issues: https://github.com/flutter/flutter/issues/68367, https://github.com/flutter/flutter/issues/68718

**Comment by jonahwilliams** [comment] 2020-10-21 18:11
What are these tests actually measuring?

**Comment by liyuqian** [comment] 2020-10-21 18:18
For most perf tests, here's the list of metrics that we reported:
```
'average_frame_build_time_millis',
'worst_frame_build_time_millis',
'90th_percentile_frame_build_time_millis',
'99th_percentile_frame_build_time_millis',
'average_frame_rasterizer_time_millis',
'worst_frame_rasterizer_time_millis',
'90th_percentile_frame_rasterizer_time_millis',
'99th_percentile_frame_rasterizer_time_millis',
'average_vsync_transitions_missed',
'90th_percentile_vsync_transitions_missed',
'99th_percentile_vsync_transitions_missed',
'average_cpu_usage',
'average_gpu_usage',
'average_memory_usage',
'90th_percentile_memory_usage',
'99th_percentile_memory_usage',
```

**Comment by jonahwilliams** [comment] 2020-10-21 18:21
I mean what are you measuring with full install versus uninstalled.

**Comment by liyuqian** [comment] 2020-10-21 18:40
We would have a copy of these metrics with full install, and a copy of these metrics with app uninstalled. We can track their regressions separately, and compare their difference.

**Comment by jonahwilliams** [comment] 2020-10-21 18:44
Do you expect separate regressions? I do not think we can add ~11 more startup tests, these are already expensive

**Comment by liyuqian** [comment] 2020-10-21 18:52
Most regressions are kind of unexpected or we won't land the PR. The reason of adding more versions of perf tests here would be exactly the same as that of https://github.com/flutter/flutter/issues/68367: the behaviors are different and we want perf tests to safeguard all of them.

Of course, I'm not saying that we should add them immediately while our lab is under pressure. We can certainly add more later when we have a more capable device lab, or maybe when Firebase Test Lab is ready. This is similar to how we handled the perf dashboard scalibility issue: we didn't add more perf metrics when Cocoon dashboard was a bottleneck; when Skia perf solves that bottleneck, we then add many more metrics for the same amount of tests we ran.

**Comment by jonahwilliams** [comment] 2020-10-21 19:15
If we didn't have to run the test ~5 times, we could probably get away with adding these now. How much of the previous fluctuations were due to the first time startup getting mixed into subsequent launch start up?

**Comment by liyuqian** [comment] 2020-10-22 23:16
I'm not sure. Will investigate when I get some time.

**Comment by Hixie** [comment] 2021-03-10 00:57
Given our focus on first-launch performance I think second-launch performance will not matter as much, so I'm going to close this for now.

**Closed by Hixie** 2021-03-10 00:57 UTC
Labels: P4, passed first triage, severe: performance, team
