### ISSUE TITLE
[in_app_purchases][MAJOR ISSUES] completePurchase method doesn't work, pendingCompletePurchase is always true, purchaseUpdatedStream won't update on refunds & pending then declined situation 

### ISSUE THREAD

**Issue by TheWCKD** [flutter/flutter#51773] opened 2020-03-02 16:07 UTC
Hello, I want to submit some of the major issues I'm encountering with in_app_purchases plugin. Below are all of them and the steps I managed to reproduce them.

**1. completePurchase method doesn't work**

- _Clicked always accept card, payment successful, verified purchase locally, called iap.completePurchase(boughtItem), but then queryPastPurchases returns pendingCompletePurchase = true, as if the completePurchase method hasn't been called._

```dart  
if (verified) {
 iap.completePurchase(event.item.last);
         yield BoughtPremium();
          } else {
            yield NoPremium(
                message: 'There was an error with your purchase',
                messageType: MessageType.ErrorMessage);
}
```
![image](https://user-images.githubusercontent.com/37099416/75692129-bf7d9f00-5cad-11ea-969f-6eb2ff06c064.png)

**2. pendingCompletePurchase is always true (related to 1)**
- _As I mentioned before, even though I'm calling completePurchase on the boughtItem, the pendingCompletePurchase is still true, which causes GooglePlayStore to refund the purchase after 3 days. This is a major issue._

**3. purchaseUpdatedStream won't emit any value if the InAppPurchase was REFUNDED & REVOKED - related to #51296 & #37823**

- _This is also a major issue. After I test-purchase an item, if I go to GooglePlayConsole, refund & revoke it, the purchaseUpdatedStream won't emit any value regarding this action, thus the user can use the premium features of my application even after the refund has been issued._-

**4. queryPastPurchases will emit a status.purchased item even it if the item was REFUNDED & REVOKED or in Pending then Declined status**

-_The item shows again and again into the queryPastPurchases list even though it has been cancelled, refunded, revoked, leaving me the only programatically solution to cancel the item purchase - iap.ConsumeItem(). If I bought an item with 'Pending then Declined' card method, the purchaseUpdatedStream will only emit the pending status, and will get stuck like that (won't emit declined status even though into the PlayConsole it says Payment Declined). The queryPastItems will also get stuck with the item having the pending status. Another major issue, since the only way to dismiss this is by calling the consumedItem again programatically, then erase the line of code._

**What's really interesting is that Pending then Accepted card method works fine, the purchaseUpdatedStream emitting the Purchased status after the payment is eventually completed.**

```dart 
if (verified) {
            iap.completePurchase(response.pastPurchases.last);
            // iap.consumePurchase(response.pastPurchases.last);
            yield Premium();
          } else {
            yield NoPremium(
                message: 'There was an error with your purchase',
                messageType: MessageType.ErrorMessage);
          }
        } else if (response
                .pastPurchases.last.billingClientPurchase.purchaseState ==
            PurchaseStateWrapper.pending) {
          // iap.consumePurchase(response.pastPurchases.last);
          yield NoPremium(
              message: 'Pending purchase, please wait',
              messageType: MessageType.PendingMessage);
        } else if (response.pastPurchases.last.status == PurchaseStatus.error) {
          yield NoPremium(
              message: 'There was an error with your purchase',
              messageType: MessageType.ErrorMessage);
        }
```

I'm using in_app_purchase: ^0.3.1+1 with Flutter 1.12.13+hotfix.7.

**Comment by geek2driod** [comment] 2020-03-05 00:20
@TheWCKD if your testing it on android then you have use consumePurchase method. completePurchase method is only for Ios.

**Comment by LHLL** [comment] 2020-04-18 00:58
It should be fixed in version: 0.3.2+1

**Closed by LHLL** 2020-04-18 00:58 UTC
Labels: p: first party, p: in_app_purchase, plugin, severe: regression

**Comment by KazakovKirill** [comment] 2020-04-18 21:31
I'm using 0.3.2+1 and it still not fixed 👎 :-(

**Comment by JoeFigure** [comment] 2020-04-22 09:26
Using 0.3.2+2, not working for me either.

Mine is a purchase of an iOS subscription. Pending remains after completePurchase method.

**Comment by TheWCKD** [comment] 2020-04-22 09:39
@LHLL Please reopen the issue as it seems it's not fixed.

**Comment by LHLL** [comment] 2020-04-22 18:40
You already have multiple incomplete transactions in the queue, the fix was intended to prevent it from happening. To unblock the user from current state is not the intention for the PR.

To unblock you from current state you can follow these steps

Find following method defined in InAppPurchasePlugin.m and replace the implementation:
- (void)handleTransactionsUpdated:(NSArray<SKPaymentTransaction *> *)transactions {
    // This will remove all old transactions regardless of states.
    for (SKPaymentTransaction *transaction in transactions) {
        [[SKPaymentQueue defaultQueue] finishTransaction:transaction];
    }
}
Launch your app on the test device one.
Restore the implementation of the above method:
- (void)handleTransactionsUpdated:(NSArray<SKPaymentTransaction *> *)transactions {
  NSMutableArray *maps = [NSMutableArray new];
  for (SKPaymentTransaction *transaction in transactions) {
    [maps addObject:[FIAObjectTranslator getMapFromSKPaymentTransaction:transaction]];
  }
  [self.callbackChannel invokeMethod:@"updatedTransactions" arguments:maps];
}
Add a new transaction and verify.

**Comment by poqueque** [comment] 2020-05-01 22:10
If the user initiates purchasing an item in iOS and cancels the request when iOS request confirmation, the incomplete transaction remains in the queue. So the last version (0.3.3) does not prevents this blocking situation to happen.

**Comment by LHLL** [comment] 2020-05-06 01:05
@poqueque Yes, you are right, 0.3.3 doesn’t prevent this from happening. And it's client app's responsibility to finish a transaction. For example, if a client app decided to log this behavior for future debugging or marketing analysis, then the only way they understand this is happening is to check the status of a failed transaction to be cancelled.

**Comment by joniaiuser** [comment] 2020-05-11 08:36
> @poqueque Yes, you are right, 0.3.3 doesn’t prevent this from happening. And it's client app's responsibility to finish a transaction. For example, if a client app decided to log this behavior for future debugging or marketing analysis, then the only way they understand this is happening is to check the status of a failed transaction to be cancelled.

Hi, can I check, how do we handle the incomplete/pending transactions on actual users without writing native code? Is the method exposed in the plugin?

**Comment by faiyyazs** [comment] 2020-05-11 18:06
I try to call finishTransaction & getting the error "The transaction with transactionIdentifer:(null) does not exist. Note that if the transactionState is purchasing, the transactionIdentifier will be nil(null)"
I have plenty of zombie queued transactions, most states are purchased, some are null. I even tried finishing transaction for only the purchased states but no luck. There is no way to proceed to clear previous stuck transactions even with the above trick. Also the case where use cancel's the request it gets stuck in pending.

**Comment by LHLL** [comment] 2020-05-11 22:05
@faiyyazs You can follow the steps here:
https://github.com/flutter/flutter/issues/51773#issuecomment-617958468

**Comment by LHLL** [comment] 2020-05-11 22:30
@joniaiuser Yes, but a little bit more complicated. Let's assume you have a purchase service similar to the follow one:
```
class PurchaseService{
    final _connection = InAppPurchaseConnection();

    const PurchaseService(){
          _connection.purchaseUpdatedStream.listen((detail) {
               ...
              if (detail. status == PurchaseStatus.error &&
                  detail.error. domain == 'SKErrorDomain'
                  detail.error. code == 2) {
                  // If a transaction's state is failed and error is cancelled, then it's a 'bad' transaction 
                 // from previous version.
                  _connection.completePurchase(detail);
              }
              ...
          });    
    }
}
```
SKErrorDomain is the domain of the NSError object thrown when the user cancelled the transaction:
https://developer.apple.com/documentation/storekit/skerrordomain?language=objc

2(SKErrorPaymentCancelled) is the code of the NSError object thrown when the user cancelled the transaction:
https://developer.apple.com/documentation/storekit/skerrorcode?language=objc

**Comment by JayM96** [comment] 2020-05-24 04:25
@LHLL 
If i'm making a purchase for subscription which kind of like a 1 month / 1 year subscription. which i think is non consumable. 

So still i need to call the consumePurchase for android and completePurchase method for ios?

Do i have to call these methods for subscriptions or not?

**Comment by LHLL** [comment] 2020-05-25 23:16
@JayM96 on iOS `completePurchase` needs to be called regardless of product type. 

@cyanglaz Can you help answer the Android one?

**Comment by cyanglaz** [comment] 2020-05-25 23:47
@JayM96 
On Android, for non-consumable items, you don't need to call consumePurchase; However, you still need to call completePurchase on Android after delivering the content(subscription in your case)

**Comment by perez-danilo** [comment] 2020-08-29 12:31
Hello, for me to buy with IOS does not work, it is in pendingCompletePurchase and even the complete process is not done shopping.
