### ISSUE TITLE
webview_flutter support load finish callback

### ISSUE THREAD

**Issue by Lihsin** [flutter/flutter#27069] opened 2019-01-25 06:39 UTC
Please create a load finish callback at webview_flutter. 
I need it to show CircularProgressIndicator.

**Comment by hanxu317317** [comment] 2019-01-25 07:00
i have used webview before, it has a loading api. u can use.

**Comment by zoechi** [comment] 2019-02-18 08:11
Duplicate of #27013

**Closed by zoechi** 2019-02-18 08:11 UTC
Labels: waiting for customer response
