### ISSUE TITLE
There are multiple heroes that share the same tag within a subtree

### ISSUE THREAD

**Issue by maninwindow** [flutter/flutter#61745] opened 2020-07-17 17:13 UTC
# My code

`BottomNavBar` code is given below:

```
@override
  Widget build(BuildContext context) {
    List<Widget> _bottomtabs = [
      ItemsList(),
      ContactsList(),
      Profile(),
    ];
    return Scaffold(
        bottomNavigationBar: BottomNavigationBar(
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Text('Home'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.monetization_on),
              title: Text('Contacts'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person),
              title: Text('Profile'),
            ),
          ],
          onTap: _onItemTap,
          currentIndex: _selectedIndex,
        ),
        body: IndexedStack(
          children: _bottomtabs,
          index: _selectedIndex,
        ));
  }
```

# Issue

`ItemsList` and `ContactsList` are a  list of clickable items. After adding `IndexedStack` to prevent sending HTTP request while tabs are being switched from one another, whenever a list item is clicked, destination page turns black and throws following exception:

```
`I/flutter (  526): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (  526): The following assertion was thrown during a scheduler callback:
I/flutter (  526): There are multiple heroes that share the same tag within a subtree.
I/flutter (  526): Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
I/flutter (  526): have a unique non-null tag.
I/flutter (  526): In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
I/flutter (  526): ├# Here is the subtree for one of the offending heroes: Hero
I/flutter (  526): 
I/flutter (  526): When the exception was thrown, this was the stack:
I/flutter (  526): #0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:266:11)
I/flutter (  526): #1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:277:8)
I/flutter (  526): #2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:296:21)
I/flutter (  526): #3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5929:16)
I/flutter (  526): #18     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #20     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #22     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #24     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #25     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5929:16)
I/flutter (  526): #26     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #28     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #30     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #32     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #33     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #34     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #36     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #38     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #40     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #42     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #44     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #46     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #48     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #50     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #51     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5929:16)
I/flutter (  526): #52     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #59     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5929:16)
I/flutter (  526): #60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #64     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #66     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #68     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #69     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #70     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #71     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #72     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #74     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #76     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #78     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #85     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
I/flutter (  526): #88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:309:15)
I/flutter (  526): #89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
I/flutter (  526): #90     Element.visitChildElements (package:flutter/src/widgets/framework.dart:3130:5)
I/flutter (  526): #91     Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:312:13)
I/flutter (  526): #92     HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:830:53)
I/flutter (  526): #93     HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:805:11)
I/flutter (  526): #94     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (  526): #95     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
I/flutter (  526): #96     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (  526): #100    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (  526): #101    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (  526): (elided 3 frames from dart:async)
I/flutter (  526): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  526): Another exception was thrown: There are multiple heroes that share the same tag within a subtree.
```

Any idea to solve this issue? 

Thanks in advance

**Comment by xu-baolin** [comment] 2020-07-20 03:13
Hi, @maninwindow, Can you please provide your flutter doctor -v your flutter run --verbose and a complete reproducible minimal code sample
Thank you

**Comment by markusaksli-nc** [comment] 2020-08-28 11:47
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by markusaksli-nc** 2020-08-28 11:47 UTC
Labels: f: material design, framework, waiting for customer response

**Comment by aliak00** [comment] 2020-10-06 22:58
This is happening to me as well. I was using an array of widgets and as soon as I switch to an `IndexedStack` I got this error. This is the diff of the code switch:

```diff
@@ -45,13 +45,6 @@ class App extends ConsumerWidget {
 }
 
 class MainScreen extends ConsumerWidget {
-  final _screens = <Widget>[
-    HoodScreen(),
-    PeepsScreen(),
-    HoodScreen(),
-    PeepsScreen(),
-  ];
-
   @override
   Widget build(BuildContext context, ScopedReader watch) {
     final appState = watch(appStateNotifierProvider.state);
@@ -59,7 +52,15 @@ class MainScreen extends ConsumerWidget {
       appBar: AppBar(
         title: Text('${describeEnum(appState.screen)}'),
       ),
-      body: _screens[appState.appScreenIndex],
+      body: IndexedStack(
+        index: appState.appScreenIndex,
+        children: [
+          HoodScreen(),
+          PeepsScreen(),
+          HoodScreen(),
+          PeepsScreen(),
+        ],
+      ),
       bottomNavigationBar: BottomBarNavigation(
         onBarItemTap: (index) {
           context.read(appStateNotifierProvider).screenIndex = index;
```

Each screen in the index stack has a button that calls `Navigator.pushName` of a "settings page" that has a _single_ `FloatingActionButton` on it.

I "fixed" the issues by settings the `heroTag` on the `FloatingActionButton` to `null`.

**Comment by aliak00** [comment] 2020-10-06 23:52
Repro:

```dart
class App2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      home: Home2(),
    );
  }
}

class Home2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(
        index: 0,
        children: [
          Page1(),
          Page2(),
        ],
      ),
    );
  }
}

class Common extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: FloatingActionButton(
            child: Text('yo'),
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(
                builder: (context) {
                  return Blah();
                },
              ));
            }));
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Common(),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Common(),
    );
  }
}

class Blah extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('two')),
      body: Center(child: Text('Hello')),
    );
  }
}
```

Both pages are in the stack, and both pages have a floating action button, so they're both in the tree. Clicking one of the floating button leads to the error though. I'm not sure I understand why that happens?

**Comment by markusaksli-nc** [comment] 2020-10-07 08:15
@aliak00 If this is what you mean
```
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
```
Then this is clearly documented in [heroTag](https://api.flutter.dev/flutter/material/FloatingActionButton/heroTag.html):

> If this is not explicitly set, then there can only be one FloatingActionButton per route (that is, per screen), since otherwise there would be a tag conflict (multiple heroes on one route can't have the same tag). The material design specification recommends only using one floating action button per screen.

**Comment by aliak00** [comment] 2020-10-07 13:14
@markusaksli-nc I'm confused because I guess I'm not sure what a screen is. Does that mean there can only be one `FloatingActionButton` in any of the subtrees that start from `MaterialApp(home: )` or from `Scaffold(body: )` or either?

And if that's true then why does it only trigger *after* `FloatingActionButton` is clicked? The only thing that happens when that's clicked is that `Page3` is *added* to the subtree of the current page, and `Page3` does not have a `FloatingActionButton` in it?

Am I correct in that each page in the sample code above is it's own subtree? And if so then why does the `Common` widget in the subtree of `Page1` conflict with the `Common` widget in the subtree of `Page2`?

**Comment by markusaksli-nc** [comment] 2020-10-08 06:50
@aliak00 The first route (means the same thing as screen here) corresponds to whatever is pushed by a [`Navigator`](https://api.flutter.dev/flutter/widgets/Navigator-class.html) when the app loads. `MaterialApp` is a convenience Widget that has a lot of the most common things needed in an app (`Navigator`, `Directionality`, `Theme `etc). 

The first screen pushed by the `Navigator` in `MaterialApp` can be defined in a number of different ways (see [initialRoute](https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html)), though `home: ` is probably the most common and has the least boilerplate.

Your FAB does not add to the first route subtree, `Navigator.push` makes the `Navigator` push an entirely new route with its own subtree on top of the current one. Not sure what you meant by `Page3`, 

So in answer to your subtree question: **no**, the only two route subtrees in this app are the initial route (everything in `Home2`) and the subtree of the route that gets pushed when you press the FAB (everything in `Blah`). The conflict is just having two FABs without unique `heroTag`s in the subtree of the initial route during the `MaterialPageRoute` transition that happens when you press them.

FABs are animated using [`Hero`](https://api.flutter.dev/flutter/widgets/Hero-class.html) and every `Hero` needs a unique `tag`. This is what allows FABs to transition smoothly if you have them on multiple pages (if you only have one they have the same `tag` by default).

<details>
 <summary>Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
    title: 'Sample',
    home: FirstRoute(),
  ));

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => SecondRoute(),
          ),
        ),
        child: Icon(Icons.add),
      ),
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: Text("Press the FAB to push a new route with a different FAB"),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => Navigator.pop(context), label: Text("Pop"),icon: Icon(Icons.arrow_back),
      ),
      appBar: AppBar(
        title: Text('Second Route'),
      ),
      body: Center(
        child: Text("Press the FAB to pop this route"),
      ),
    );
  }
}
```
</details>

**Comment by aliak00** [comment] 2020-10-08 09:01
> Not sure what you meant by Page3

Sorry, I meant `Blah`.

> during the MaterialPageRoute transition

Ahhh. Ok I think that was the missing link in my head :)

@markusaksli-nc Thank you for taking the time to explain this :D

**Comment by WilliamMuchampa** [comment] 2021-03-23 19:56
> @aliak00 If this is what you mean
> 
> ```
> The following assertion was thrown during a scheduler callback:
> There are multiple heroes that share the same tag within a subtree.
> 
> Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
> In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
> ```
> 
> Then this is clearly documented in [heroTag](https://api.flutter.dev/flutter/material/FloatingActionButton/heroTag.html):
> 
> > If this is not explicitly set, then there can only be one FloatingActionButton per route (that is, per screen), since otherwise there would be a tag conflict (multiple heroes on one route can't have the same tag). The material design specification recommends only using one floating action button per screen.

Thats the error a getting exactly though they are not FAB, they inkwell

**Comment by aliak00** [comment] 2021-03-24 10:57
@WilliamMuchampa are there no FABs anywhere in the tree of widgets that are involved in the transition?

**Comment by kamleshwebtech** [comment] 2021-05-16 18:07
I am not using any heroTag in my entire app but still getting error at the compile time "There are multiple heroes that share the same tag within a subtree" kindly suggest what is the issue and how can I solve it. Thanks.

**Comment by kamleshwebtech** [comment] 2021-07-24 16:03
> I am not using any heroTag in my entire app but still getting error at the compile time "There are multiple heroes that share the same tag within a subtree" kindly suggest what is the issue and how can I solve it. Thanks.

@goevexx goevexx, any suggestion? Kindly share. Thanks.

**Comment by goevexx** [comment] 2021-07-25 16:08
> > I am not using any heroTag in my entire app but still getting error at the compile time "There are multiple heroes that share the same tag within a subtree" kindly suggest what is the issue and how can I solve it. Thanks.
> 
> @goevexx goevexx, any suggestion? Kindly share. Thanks.

I got the same error. I was using fapbuttons without initializing hertag. Setting hero tag solved it. 
So my suggestion: use hero tags on widgets which might expect a hero tag.
