### ISSUE TITLE
gpu pthread crash

### ISSUE THREAD

**Issue by blackox626** [flutter/flutter#42391] opened 2019-10-10 03:51 UTC
![image](https://user-images.githubusercontent.com/648502/66539647-5b6e0900-eb5b-11e9-8436-712721e6ae13.png)

## Stacktrace:

```
validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).'
```
## Flutter Doctor
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.3, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.3 at /Users/blackox626/Library/Flutter/v1.9.1+hotfix.3/flutter
    • Framework revision a72edc2706 (2 weeks ago), 2019-09-25 15:41:01 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/blackox626/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] Connected device (1 available)
    • yishang`s iPhone • c820d23d00cecba50aa4a48f1fbd34a774cbba40 • ios • iOS 13.1.2

! Doctor found issues in 2 categories.
```

**Comment by janmoppel** [comment] 2019-10-10 10:21
Hello @blackox626 !

Thank you for posting an issue.
Without additional input, it is hard to investigate such cases. Can you please provide more information, such as:
1) Steps to reproduce the error;
2) Some sample code that can be used to reproduce the error, if possible;
3) Full stacktrace of the error, in the text format, so that it would be easier to debug;
4) Output of the `flutter doctor -v` command?

Thank you.

**Comment by zilijonas** [comment] 2019-10-10 19:25
I have the same issue.

```Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (13 days ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0```

Output from `flutter doctor -v` (do not mind the Android issues, I am currently testing this only on iOS):
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale en-LT)
    • Flutter version 1.9.1+hotfix.4 at /Users/lijonas/Documents/development/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Linas Jonas’s iPhone • c1461296a64d22dda8af93ce9c91a8909f3cf5a0 • ios • iOS 13.1.2
    • iPhone 11 Pro Max    • D76AB791-7014-4A4C-A1F7-E5D5DC76DA41     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

Stacktrace:
```
2019-10-10 22:21:54.980574+0300 Runner[759:106093] Metal GPU Frame Capture Enabled
2019-10-10 22:21:54.980850+0300 Runner[759:106093] Metal API Validation Enabled
2019-10-10 22:21:55.240605+0300 Runner[759:106288] flutter: Observatory listening on http://127.0.0.1:52219/sgI_c4JamPk=/
2019-10-10 22:21:59.050156+0300 Runner[759:106277] flutter: AddCategory { category: Burgers }
2019-10-10 22:21:59.064872+0300 Runner[759:106277] flutter: Transition { currentState: CategoriesState { list: [], length: 0 }, event: AddCategory { category: Burgers }, nextState: CategoriesState { list: [Instance of 'Category'], length: 1 } }
validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).'
```

**Comment by blackox626** [comment] 2019-10-12 02:56
> Hello @blackox626 !
> 
> Thank you for posting an issue.
> Without additional input, it is hard to investigate such cases. Can you please provide more information, such as:
> 
> 1. Steps to reproduce the error;
> 2. Some sample code that can be used to reproduce the error, if possible;
> 3. Full stacktrace of the error, in the text format, so that it would be easier to debug;
> 4. Output of the `flutter doctor -v` command?
> 
> Thank you.

no idea how to reproduce the crash 
no more stacktrace 

in my case ,   use gridview to show item card list ,each card  contanins image(from network) and text widget ,when fast scroll, the crash maybe occure.

**Comment by blackox626** [comment] 2019-10-14 09:30
![image](https://user-images.githubusercontent.com/648502/66741489-415c5f80-eea8-11e9-9800-b628a666dbe1.png)

**Comment by johngray1965** [comment] 2019-10-15 11:20
I'm seeing this too.  I only saw it after an upgrade to to iOS 13.  I see it on an ipad.   I'm doing a lot of drag-n-drop.  If I do the drag-n-drop operations rapid-fire, I can crash the app with this error in about 30 seconds.  Note I have vanilla gesture detector as well as the drag-n-drop, the drag-n-drop may have nothing to do with it.

**Comment by songfei** [comment] 2019-11-07 01:26
same issue!

app to background, and  to  foreground.

validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).'


`flutter doctor -v
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
    • Flutter version 1.10.14 at /Users/songfei/flutter
    • Framework revision 1946fc4da0 (4 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)


Checking Android licenses is taking an unexpectedly long time...⣾^C(env) FLYSONG-MC1:log songfei$ flutter doctor -v
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
    • Flutter version 1.10.14 at /Users/songfei/flutter
    • Framework revision 1946fc4da0 (4 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/songfei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is git.code.oa.com,r.tnpm.oa.com,*.mnet2.com,127.0.0.1,localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • songfei’s iPhone XS • 00008020-001C3C440C2A002E            • ios • iOS 13.1.3
    • iPhone 11 Pro Max   • 1DF06F00-D757-4051-93F2-84061CC59960 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 1 category.`

**Comment by johngray1965** [comment] 2019-11-08 12:29
I started see this after updating to iOS 13, still saw it on iOS 13.1, I'm now on iOS 13.2 and it appears to be gone.  I could make the crash happen fairly quickly.  I've spent much longer with iOS 13.2 then I could go before, and have not seen the problem.  If it crops up again, I'll report back.

Can anyone else confirm that the problem goes away on iOS 13.2?

**Comment by johngray1965** [comment] 2019-11-08 12:34
Ugh, I spoke to soon, just reproduce the issue on 13.2

**Comment by macmatrix** [comment] 2019-11-25 23:12
Same problem here with a real iOS device 13.1. My problem comes up when I receive a notification and I try to show up an alert dialog on foreground. Here is the code

```
void firebaseCloudMessaging_Listeners() {
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print('---------------on message $message');

        if (appData.isIOS) {
          title = message['aps']['alert']['title'] ?? 'Notification';
          content = message['aps']['alert']['body'] ??
              'There is a new xx. Check it out';
        } else {
          title = message['notification']['title'] ?? 'Notification';
          content = message['notification']['body'] ??
              'There is a new xx. Check it out';
        }
        showDialog(
            context: context,
            builder: (BuildContext context) => ShowDialogToDismiss(
                title: title,
                content: content,
                buttonText: 'CLOSE'));
      },

class ShowDialogToDismiss extends StatelessWidget {
  final String content;
  final String title;
  final String buttonText;

  ShowDialogToDismiss({this.title, this.buttonText, this.content});

  @override
  Widget build(BuildContext context) {
      return CupertinoAlertDialog(
          title: Text(
            title,
          ),
          content: new Text(
            this.content,
          ),
          actions: <Widget>[
            CupertinoDialogAction(
              isDefaultAction: true,
              child: new Text(
                buttonText[0].toUpperCase() +
                    buttonText.substring(1).toLowerCase(),
              ),
              onPressed: () {
                Navigator.of(context).pop();
              },
            )
          ]);
  }
}
```

Here is the error

> validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).'

**Comment by mauhcs** [comment] 2019-12-02 06:14
Any update in this crash?

**Comment by ifehrim** [comment] 2019-12-24 03:57
Same Issue:
validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).'


➜  lool git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en)
    • Flutter version 1.12.13+hotfix.5 at /Users/fehrim/tools/flutter
    • Framework revision 27321ebbad (13 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fehrim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/fehrim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Alm iPhone • 399afbc982439a1e63e7fe70ae27538e8d2696e6 • ios • iOS 13.3

• No issues found!

**Comment by Black-Horse** [comment] 2020-01-06 21:38
Same issue here. Thankful for any hints!

**Comment by BharathMG-ShareChat** [comment] 2020-01-13 16:32
We are also experiencing the same crash. No widget information or anything. Just a single line log,

```
validateFunctionArguments:3485: failed assertion `Vertex Function(#main): argument vertexBuffer.0[0] from buffer(15) with offset(32756) and length(32768) has space for 12 bytes, but argument has a length(60).
```

**Comment by BharathMG-ShareChat** [comment] 2020-01-14 07:00
It looks like, this assertion fails in debug mode, when XCode has "Metal enabled". Once we disable that, we are not able to reproduce this issue. Not sure how this issue started happening suddenly though.

**Comment by DhavalRKansara** [comment] 2020-01-27 08:56
I am also facing the same issuess.

**Comment by devSC** [comment] 2020-02-05 03:38
same issue.

**Comment by isaaknewton** [comment] 2020-02-06 19:36
same here.

flutter doctor -v
`[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-CH)
    • Flutter version 1.12.13+hotfix.7 at /Users/isaak/Developer/flutter
    • Framework revision 9f5ff2306b (11 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/isaak/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • iPhone Xr • 00008020-001A49861A83002E            • ios • iOS 13.3
    • iPhone 11 Pro Max                        • A801E977-723C-44AB-8525-88B0DEAC4063 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!`

**Comment by wesleydashner** [comment] 2020-02-12 17:32
same issue here

**Comment by wasabia** [comment] 2020-02-16 06:04
same issue 
[✓] Flutter (Channel master, v1.15.3-pre.17, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.0)

**Comment by wasabia** [comment] 2020-02-16 06:18
> Disabling Metal API Validation fixed this for me, at least as a workaround for now.
> 
> In Xcode, Command-Option-R -> Options, set Metal API Validation to "disabled"

work for me

**Comment by RRAVITEJA** [comment] 2020-03-13 16:40
> Disabling Metal API Validation fixed this for me, at least as a workaround for now.
> 
> In Xcode, Command-Option-R -> Options, set Metal API Validation to "disabled"

This worked for me,
Thank you

**Comment by iapicca** [comment] 2020-03-15 10:30
Hi @blackox626 
does @wesleydashner [solution](https://github.com/flutter/flutter/issues/42391#issuecomment-585322391) work for you?
Thank you

**Comment by MeshkaniMohammad** [comment] 2020-03-23 23:41
@iapicca it wasn't helpful for me

**Comment by iapicca** [comment] 2020-04-22 10:25
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-22 10:25 UTC
Labels: engine, platform-ios, severe: crash, waiting for customer response
