### ISSUE TITLE
Incorrect Type Promotion in Flutter Web profile/release mode

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#100135] opened 2022-03-15 13:16 UTC
Take the following classes as example:
```dart
abstract class Base {}

class Child1 extends Base {
  final bool isChild1 = true;
}

class Child2 extends Base {}
```

Checking for the type *as well as* for a field of that type, will cause an incorrect type promotion in flutter web `profile` and `release` mode, but not in `debug` mode:

```dart
  List<Base> children = [
    Child1(),
    Child2(),
  ];

  List<Base> onlyChild2 = [];
  for (final child in children) {
    // NOTE: without the added "&& child.isChild1" everything works fine
    if (false == (child is Child1 && child.isChild1)) {
      onlyChild2.add(child);
    }
  }

  // Will print "true" in debug, but "false" in profile
  print(onlyChild2.first is Child2);

  // EDIT: What is arguably worse is the following:
  // Will print "false" in debug, but "true" in profile
  print(onlyChild2.first is Child1);
```

Here is a minimal flutter example:

<details>
<summary>Executable example</summary>

```dart

import 'package:flutter/material.dart';

abstract class Base {}

class Child1 extends Base {
  final bool isChild1 = true;
}

class Child2 extends Base {}


void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool? correctType;

// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '', // TODO add title
      home: Scaffold(
        // Adding green / red color to highlight difference
        backgroundColor: (correctType == null) //
            ? null
            : correctType!
                ? Colors.green
                : Colors.red,
        body: Center(
          child: FloatingActionButton(onPressed: () {
            List<Base> children = [
              Child1(),
              Child2(),
            ];

            List<Base> onlyChild2 = [];
            for (final child in children) {
              // NOTE: without the added "&& child.isChild1" everything works fine
              if (false == (child is Child1 && child.isChild1)) {
                onlyChild2.add(child);
              }
            }

            setState(() {
              correctType = onlyChild2.first is Child2;
              // Will print "true" in debug, but "false" in profile
              print(correctType);

              // EDIT: What is arguably worse is the following:
              // Will print "false" in debug, but "true" in profile
              print(onlyChild2.first is Child1);
            });
          }),
        ),
      ),
    );
  }
}
```
</details>

Run in `debug`:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/24209580/158385360-79efdd29-c031-40cc-a44f-8063cb3e1ecc.png">

Run in `profile` or `release`:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/24209580/158385231-c8a9847c-67d9-46c8-8194-b9c621eb9232.png">

This occurs in the latest master:

<details>
  <summary>Doctor</summary>

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.886, on macOS 12.1 21C52 darwin-arm, locale en-DE)
    • Flutter version 2.11.0-0.0.pre.886 at /Users/omni/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2bd3e0d914 (5 hours ago), 2022-03-15 04:20:15 -0400
    • Engine revision 6c02eaea3a
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/omni/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/omni/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/omni/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by jason-simmons** [comment] 2022-03-15 21:24
@mraleph

**Comment by mraleph** [comment] 2022-03-15 21:39
Given that it's Flutter Web likely dart2js issue. /cc @sigmundch @rakudrama

**Comment by sigmundch** [comment] 2022-03-15 23:09
Thanks so much for the report and for the carefully reduced repro. It is extremely helpful for us when the problem is so well isolated. Thank you!

This is clearly a bug in dart2js's type propagation algorithm. I'll try to see if we can carry over this bug to the Dart SDK repo, otherwise I'll open a new one there to track this.

**Comment by sigmundch** [comment] 2022-03-15 23:14
I wasn't able to transfer it, but here is the corresponding bug: https://github.com/dart-lang/sdk/issues/48571

**Comment by sigmundch** [comment] 2022-04-06 16:54
A [fix landed][1] in the Dart SDK to address this bug, so I'm closing this issue. It will take some time for the fix to make it into the stable channel, but it should be available in the flutter main branch in the next few days.

[1]: https://github.com/dart-lang/sdk/commit/017e0f7224bb92cba7ff74e5dcfecdbfb639f43f

**Closed by sigmundch** 2022-04-06 16:54 UTC
Labels: dependency: dart, platform-web, blocked
