### ISSUE TITLE
Navigator.canPop() returns incorrect values on iOS under certain conditions

### ISSUE THREAD

**Issue by jaanus** [flutter/flutter#154710] opened 2024-09-06 08:38 UTC
### Steps to reproduce

1. Check out the example project to demonstrate this bug: https://github.com/jaanus/nav_can_pop
2. Run it as-is on iOS simulator or device. Navigate between the child and home view a few times. Observe that everything is correct.
3. Put the app to background while looking at the child view.
4. Bring the app to foreground.
5. Go to home view.

### Expected results

Navigator.canPop() should always report a correct value for the home view, and home view should never render a back button.

### Actual results

Home view is incorrectly rendering a back button on iOS.

This happens because I have this line in my widget’s `build`:

`final brightness = MediaQuery.platformBrightnessOf(context);`

This will cause an unwanted `build` call when putting the app to background on iOS. Inside that `build` call, `navigator.canPop()` is reporting an incorrect value for the root view.

However, when I ask for `ModalRoute.of(context)`, the behavior of the app changes: `build` is called more frequently and `navigator.canPop()` is reporting correct values.

### Code sample

Please check out the entire small sample project: https://github.com/jaanus/nav_can_pop

Here is the heart of the issue:

```dart
class MyScaffold extends StatelessWidget {
  const MyScaffold({
    super.key,
    required this.title,
    required this.child,
  });

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    // This media query is causing unwanted “build” call when putting the app to background on iOS
    final brightness = MediaQuery.platformBrightnessOf(context);
    final navigator = Navigator.maybeOf(context);
    final String? canPop;
    if (navigator != null) {
      canPop = navigator.canPop() ? "true" : "false";
    } else {
      canPop = "(navigator not found)";
    }

    String impliesAppBarDismissal = "(n/a)";

    // Simply uncommenting the following part of code will change the app behavior to be correct.
    // build() is called more frequently and Navigator.canPop() will report correct values.
    // final route = ModalRoute.of(context);
    // if (route != null) {
    //   impliesAppBarDismissal = route.impliesAppBarDismissal ? "true" : "false";
    // } else {
    //   impliesAppBarDismissal = "(route not found)";
    // }

    // canPop should be false for HomeView and true for ChildView.
    // But in the rogue build call when putting app to background for iOS,
    // canPop is reported as true for both HomeView and ChildView.

    debugPrint(
      "MyScaffold build. Brightness: $brightness. Child type: ${child.runtimeType.toString()}. Navigator canPop: $canPop. ModalRoute impliesAppBarDismissal: $impliesAppBarDismissal",
    );
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        leading: canPop == "true" ? _BackButton() : null,
      ),
      body: child,
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/b4ca9a49-8f37-47dc-878e-2b16b6ec697e

</details>

### Logs

<details open><summary>Logs</summary>

Here are the logs from the above debug print. Note that `brightness` is reported repeatedly as both `dark` and `light` which also seems incorrect, as the device brightness did not actually change.

```console
(this is the initial situation, all correct)
flutter: MyScaffold build. Brightness: Brightness.light. Child type: HomeView. Navigator canPop: false. ModalRoute impliesAppBarDismissal: (n/a)
flutter: MyScaffold build. Brightness: Brightness.light. Child type: ChildView. Navigator canPop: true. ModalRoute impliesAppBarDismissal: (n/a)
(at this point, I put the app to background)
flutter: MyScaffold build. Brightness: Brightness.dark. Child type: HomeView. Navigator canPop: true. ModalRoute impliesAppBarDismissal: (n/a)
flutter: MyScaffold build. Brightness: Brightness.dark. Child type: ChildView. Navigator canPop: true. ModalRoute impliesAppBarDismissal: (n/a)
flutter: MyScaffold build. Brightness: Brightness.light. Child type: HomeView. Navigator canPop: true. ModalRoute impliesAppBarDismissal: (n/a)
flutter: MyScaffold build. Brightness: Brightness.light. Child type: ChildView. Navigator canPop: true. ModalRoute impliesAppBarDismissal: (n/a)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
jaanus@studio ~> flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale et-EE)
    • Flutter version 3.24.1 on channel stable at /Users/jaanus/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/jaanus/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/jaanus/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode-15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhone 15 Pro (mobile)          • 398D50A2-1837-412F-95C0-1C92ED907B66 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for JK iPhone 11 Pro. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for JK iPhone 15 Pro. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment] 2024-09-06 10:15
Closing as duplicate of https://github.com/flutter/flutter/issues/149555. I see that you have commented in that issue. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-09-06 10:15 UTC
Labels: in triage
