### ISSUE TITLE
[web][video_player] Unable to adjust asset video progress by using VideoProgressIndicator widget

### ISSUE THREAD

**Issue by ToniMHeinonen** [flutter/flutter#107281] opened 2022-07-08 07:16 UTC
VideoProgressIndicator does not seem to work in web with asset video files. When you adjust the progress bar, the video just starts playing from the beginning. I am currently using version 2.4.5.

### Steps to Reproduce

1. Download and run video_player package example from https://github.com/flutter/plugins
2. Adjust asset video progress bar

**Expected result:** Video should play from the adjusted progress position.

**Actual result:** Video starts playing from the beginning.

EDIT 1: I just noticed that if I reload the page, the progress bar starts working correctly. There seems to be something wrong when it is initialized for the first time.

**Comment by ToniMHeinonen** [comment] 2022-07-08 07:29
I just noticed that if I reload the page, the progress bar starts working correctly. There seems to be something wrong when it is initialized for the first time.

**Comment by maheshmnj** [comment] 2022-07-08 10:07
Hi @ToniMHeinonen, Thanks for filing the issue. I am able to reproduce the issue on the latest stable and the master channel with`video_player: ^2.4.5`. On Seeking the video progress bar to any position the progress bar jumps to the start position (Duration.zero) and the video restarts. Also it works properly for the first time and the subsequent progressbar drag fails. This is reproducible only on the web and it works fine on other platforms (IOS/Android).

Web | Android
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/177969041-7f70436c-e09b-49ee-9217-18426cfbb0ea.mov' width=240/> | <video src='https://user-images.githubusercontent.com/31410839/177969054-0af03fd4-35ee-4c6c-9618-0579a7b2c98d.mov' width=180/> 


There was a similar issue filed in the past, but for videos loaded from the network https://github.com/flutter/flutter/issues/93486

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1494, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1494 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 829bddf616 (3 hours ago), 2022-07-04 03:49:08 -0400
    • Engine revision e78ed7f1c9
    • Dart version 2.18.0 (build 2.18.0-251.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


cc: @ditman

**Comment by stuartmorgan** [comment] 2022-07-13 18:38
This is a duplicate of the issue referenced above. In particular, from the last comment:

> The default Flutter web server (when you do flutter run) does not support range requests either.

**Closed by stuartmorgan** 2022-07-13 18:38 UTC
Labels: plugin, p: first party, platform-web, p: video_player, has reproducible steps, found in release: 3.0, found in release: 3.1

**Comment by maheshmnj** [comment] 2022-07-20 16:16
> This is a duplicate of the issue referenced above. In particular, from the last comment in that issue: 

Anyone who is encountering this issue see: https://github.com/flutter/flutter/issues/93486#issuecomment-987469571

**Comment by ditman** [comment] 2022-07-21 01:23
Would it make sense to document this in the package [README](https://pub.dev/packages/video_player_web)? @stuartmorgan

**Comment by stuartmorgan** [comment] 2022-07-21 02:14
Seems worth at least putting in the `video_player_web` README, which we already link to for some additional details in the main README. If people aren't finding it there, we can add something more to the app-facing README later.

**Comment by ditman** [comment] 2022-07-21 03:30
Let's try this: https://github.com/flutter/plugins/pull/6128
