### ISSUE TITLE
Firebase has not been correctly initialized. Have you added the "GoogleService-Info.plist" file to the project? 

### ISSUE THREAD

**Issue by saravanans55** [flutter/flutter#89643] opened 2021-09-08 09:22 UTC
I have included a GoogleService-Info.plist in the "ios/Runner/" folder. but still facing this issue while build/run the app. I tried all the ways, flutter clean, invalidate and restart, flutter get, flutter upgrade, removed the ios folder, removed and add the podfile, podfile.lock. No Luck... Anyone please help me?

Error Log:
========
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           28.1s
Debug service listening on ws://127.0.0.1:56340/eT56OFzr0F8=/ws
Syncing files to device iPhone 12 Pro Max...
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. Have you added the "GoogleService-Info.plist" file to the project? 

Flutter doctor Log:
==============
Doctor summary (to see all details, run flutter doctor -v):
Unable to find any JVMs matching version "1.8".
Unable to find any JVMs matching version "1.8".
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-IN)
⣯Unable to find any JVMs matching version "1.8".                                                                                                                                                      [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2021-09-08 09:36
Hi @saravanans55 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-08 09:36 UTC
Labels: in triage
