### ISSUE TITLE
After switching to v1.7.8+hotfix.3 Google's Pre-launch report shows Android compatibility warnings

### ISSUE THREAD

**Issue by opensourcegps** [flutter/flutter#36915] opened 2019-07-25 04:22 UTC
After upgrading to stable, v1.7.8+hotfix.3, Google Play console shows "Android compatibility" pre-launch report warnings for flutter app. 

Looks like related to Accessibility, any hints what to do about these warnings?

![android_warnings](https://user-images.githubusercontent.com/7678445/61845487-a28a1d80-aecd-11e9-8062-95aa741fc7ee.png)

Full stacks of 4 warnings:

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:122)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.AccessibilityBridge.<init>(Unknown Source:153)
	at io.flutter.view.FlutterView.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:11)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.AccessibilityBridge.<init>(Unknown Source:153)
	at io.flutter.view.FlutterView.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:101)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.AccessibilityBridge.<init>(Unknown Source:153)
	at io.flutter.view.FlutterView.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:30)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.AccessibilityBridge.<init>(Unknown Source:153)
	at io.flutter.view.FlutterView.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /home/flutter/flutter_linux_v1.7.8-hotfix.3-stable
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0
```
```
compileSdkVersion 28
minSdkVersion 21
targetSdkVersion 28
```

**Comment by haroonkhan9426** [comment] 2019-07-27 17:25
Facing the same issue.

**Comment by richgoldmd** [comment] 2019-08-02 13:26
I'm having the same issue with v1.7.8+hotfix.4:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /devtools/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/richardgoldstein/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/richardgoldstein/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/richardgoldstein/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 5F916D8D-6F88-476F-B3DB-6EE6EB552888 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

```

**Comment by AdornaR** [comment] 2019-08-06 11:43
Facing the same issue here. This error is only thrown in Google Play.

**Comment by AdornaR** [comment] 2019-08-06 15:13
Okay, I don't know how, I opened the MainActivity file and there appeared a message at the top bar on Android Studio, telling me to specify an Android version for the project (I had it on my Gradle file, version 29), but I clicked on it, specified the version 29 and... It worked!
This is the first time that message appeared for me there, so I don't know how exactly it appeared. 
I think maybe is this: [](https://stackoverflow.com/questions/53992118/unresolved-reference-android-on-new-flutter-project) , because that was the last thing I did on my project before retrying building a new App Bundle.

**Comment by richgoldmd** [comment] 2019-08-06 15:29
@AdornaR Are you saying that updating the sdk version to 29 resolved this issue?

**Comment by AdornaR** [comment] 2019-08-06 22:14
@richgoldmd For me, it worked

**Comment by opensourcegps** [comment] 2019-08-08 01:21
I'm not sure just setting blindly SDK version to 29 is a good solution. This API level feels too risky for production at the moment. Setting API version to 28 didn't help.

**Comment by nitneuq33** [comment] 2019-08-17 07:56
same issue ...

**Comment by Damandroid** [comment] 2019-08-27 15:58
+1 to this. Want to release my app publicly but not sure if I should because of these warnings.

**Comment by opensourcegps** [comment] 2019-08-28 13:03
@richgoldmd thanks for info, much appreciated. 
I can also confirm that there were no problems/crashes related to this issue by just ignoring the warnings.

**Comment by jejerome** [comment] 2019-09-26 13:48
same issue using Flutter 1.9.1+hotfix.2, thanks for finding that info!

**Comment by garshom** [comment] 2019-10-08 21:50
am facing the same issue with flutter v1.9.1+hotfix.4 

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(AccessibilityViewEmbedder.java:457)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(AccessibilityViewEmbedder.java:411)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(AccessibilityViewEmbedder.java:66)
	at io.flutter.view.AccessibilityBridge.<init>(AccessibilityBridge.java:391)
	at io.flutter.view.FlutterView.onAttachedToWindow(FlutterView.java:725)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(AccessibilityViewEmbedder.java:428)
	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.<init>(AccessibilityViewEmbedder.java:411)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(AccessibilityViewEmbedder.java:66)
	at io.flutter.view.AccessibilityBridge.<init>(AccessibilityBridge.java:391)
	at io.flutter.view.FlutterView.onAttachedToWindow(FlutterView.java:725)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iapicca** [comment] 2020-01-16 10:46
Hi @opensourcegps 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment] 2020-03-06 12:07
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

Thank you

**Comment by sanuzzi** [comment] 2020-03-09 23:36
@TahaTesser I did what you asked and I created a new issue because it still happens. Other person closed it. Can you reopen this one then? The warnings still appear. Thank you!

**Comment by charkala** [comment] 2020-03-16 00:41
I'm facing this issue as well (same pre-launch report as @UnDer-7 's post), manually installed releases work fine on physical devices, however, once downloaded from the play store (closed track) the app just shows a blank white screen.

Tested on Samsung devices only:
- Doesn't work on S10/S20 (Android 10)
- Works on Z-Flip(Android 10), S9 (Android 9) and prior models.

**Comment by canewsin** [comment] 2020-03-16 06:17
same issue on `Flutter 1.12.13+hotfix.8`

**Comment by sajjad-hk** [comment] 2020-04-13 21:22
Same issue on `Flutter 1.12.13+hotfix.9`

**Comment by MartinCCota** [comment] 2020-05-04 00:45
Same error in pre-launch for me. This is my flutter version:

Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

Any solutions please ? Need to publish my app but I'm concerned about this errors on the pre-launch.

Thanks.

**Comment by canewsin** [comment] 2020-05-04 01:14
> Same error in pre-launch for me. This is my flutter version:
> 
> Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
> Engine • revision af51afceb8
> Tools • Dart 2.7.2
> 
> Any solutions please ? Need to publish my app but I'm concerned about this errors on the pre-launch.
> 
> Thanks.
> 

This does not effect user facing code release build, you don't have to worry about errors.

**Comment by nohli** [comment] 2020-05-13 11:21
Same issue (for some time now) with two apps, latest flutter stable, build with Codemagic, tried compileSdkVersion/ targetSdkVersion 28 and 29.

**Comment by opensourcegps** [comment] 2020-05-13 11:29
Please see https://github.com/flutter/flutter/issues/36915#issuecomment-525668810 and just ignore the warnings.

**Comment by TahaTesser** [comment] 2020-05-13 15:23
Issue reopened due to crowd label and no official confirmation that this issue can be closed

**Comment by diegoporfirio** [comment] 2020-06-08 11:44
Same issue on  stable v1.17.0, on Mac OS X10.15.5.
Framework revision e6b34c2b5c - 2020-05-02

**Comment by teekamsuthar** [comment] 2020-06-09 05:35
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.19041.264], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

```

Same issue here as well

**Comment by chinmaygarde** [comment] 2020-06-11 02:35
This issue can be closed. [As mentioned in a previous comment](https://github.com/flutter/flutter/issues/36915#issuecomment-525668810), while reflection is used to access these APIs, their use is guarded. It is unclear if Flutter should have a policy on never using reflection at the embedding layers or if such a policy is even feasible. cc @xster for followup on that.

**Closed by chinmaygarde** 2020-06-11 02:35 UTC
Labels: a: error message, a: production, customer: crowd, engine, platform-android

**Comment by dipakchandranp** [comment] 2021-05-14 10:55
Faced this same issue again. Fixed by updating the `targetSdkVersion` value. By default when I created the flutter app the version was **`29`**, updated this to **`30`** and everything got fixed.

Changed in `/my_app/android/app/build.gradle`

> From:  `targetSdkVersion 29`
> To: `targetSdkVersion 30`

<img width="1366" alt="Screenshot 2021-05-14 at 4 21 57 PM" src="https://user-images.githubusercontent.com/5057513/118261124-c2d70200-b4d0-11eb-9008-052033cc14f6.png">
