### ISSUE TITLE
flutter.io search results can fail

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4188] opened 2016-05-25 19:01 UTC
I searched for `ScrollableGrid`:
```
https://flutter.io/search/?cx=007067728241810524621%3Agm6vraqlc8c&ie=UTF-8&hl=en&q=ScrollableGrid
```

Clicking on the first link produced:

![screenshot](https://cloud.githubusercontent.com/assets/1377460/15552596/fe8eedec-226f-11e6-910a-8285b839c9dd.png)

Browsing to http://docs.flutter.io/flutter/material/ScrollableGrid-class.html doesn't cause any trouble.

Is `Search` turning up obsolete links?

**Comment by eseidelGoogle** [comment] 2016-05-25 19:13
It's a question of https vs. http.  @sethladd looked at this a while back iirc.

**Comment by sethladd** [comment] 2016-05-25 19:24
Sorry about this. I don't know why Google thinks we have https for our docs.

Since I don't know why, and I haven't been able to figure it out, and we want SSL anyway, we might as well just get SSL working for docs.flutter.io this quarter. :)

I'm going to close this as a dupe of https://github.com/flutter/flutter/issues/3889

**Closed by sethladd** 2016-05-25 19:24 UTC
Labels: affects: dev experience, affects: website, ⚠ bug, ⚠ clear documentation
