### ISSUE TITLE
[camera] CameraException(error, No capture session available for current capture session) using external USB camera

### ISSUE THREAD

**Issue by vp-prilitya** [flutter/flutter#119041] opened 2023-01-24 03:25 UTC
I found this error on android 12. but it works on android 8.

**Comment by darshankawar** [comment] 2023-01-24 06:55
Closing as duplicate of https://github.com/flutter/flutter/issues/106049. Please follow-up in it for further updates. You may share your findings in that issue for better tracking.

**Closed by darshankawar** 2023-01-24 06:55 UTC
Labels: in triage
