### ISSUE TITLE
Failed assertion: line 230 pos 15: 'data != null': is not true

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#22028] opened 2018-09-19 10:33 UTC
```
I/flutter (16829): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16829): The following assertion was thrown building AvailabilityDetail(dirty, state:
I/flutter (16829): AvailabilityDetailPageState#3c6d4):
I/flutter (16829): 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
I/flutter (16829): true.
I/flutter (16829): 
I/flutter (16829): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16829): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16829): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16829):   https://github.com/flutter/flutter/issues/new
I/flutter (16829): 
I/flutter (16829): When the exception was thrown, this was the stack:
I/flutter (16829): #2      new Text (package:flutter/src/widgets/text.dart:230:15)
I/flutter (16829): #3      getAppBar (package:sipaper/CustomAppBar.dart:16:12)
I/flutter (16829): #4      AvailabilityDetailPageState.build (package:sipaper/pi_chart_detail_view.dart:122:15)
I/flutter (16829): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (16829): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (16829): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (16829): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (16829): #98     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (16829): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (16829): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (16829): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (16829): #102    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4579:32)
I/flutter (16829): #103    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (16829): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #105    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (16829): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #109    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (16829): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16829): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (16829): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (16829): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (16829): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (16829): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (16829): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (16829): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (16829): #127    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (16829): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (16829): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (16829): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (16829): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (16829): #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (16829): #133    _invoke (dart:ui/hooks.dart:128:13)
I/flutter (16829): #134    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (16829): (elided 2 frames from class _AssertionError)
```

**Comment by berosoboy** [comment] 2018-09-19 13:16
You need to provide a String or a TextSpan to the Text constructor

**Comment by berosoboy** [comment] 2018-09-19 13:58
Understood. The string is null at the moment you call the constructor.
I think your issue is a duplicate of #11545.
See the Hixie suggestion on the comments.

Or if you really want to display a Text widget, you can use the null-aware operator:
```dart
Text(theString ?? '')
```

Hope it help you.

**Comment by zoechi** [comment] 2018-09-24 19:03
Merging with #11545

**Closed by zoechi** 2018-09-24 19:03 UTC

**Comment by zoechi** [comment] 2018-09-24 19:04
@viratshukla perhaps you are using a `FutureBuilder` and assume having a valid value in `build()` while actually the value is only available later when the `Future` completes and `build()` is called again.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by waffles9992** [comment] 2018-11-21 03:03
Yo Im a noob and I got this error because I had some pages with an optional title param. It wasn't giving me warning or failure on compile because I was giving the Text a variable argument that hadn't been set yet. Then I never set it in the constructor for the page

**Comment by raviiroid** [comment] 2020-03-13 06:20
set delay up on dialog.....

Future.delayed(Duration(milliseconds: 50));
