### ISSUE TITLE
primaryColor: Colors.white 设置白色主题无效

### ISSUE THREAD

**Issue by GYP1995** [flutter/flutter#94151] opened 2021-11-24 09:55 UTC
```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
如上所示，我按照文档设置primaryColor为白色之后，重新加载app，主题没有改变，是什么原因呢

Per Google translate:
As shown above, after I set the primaryColor to white according to the document, I reloaded the app and the theme did not change. What is the reason?

**Comment by maheshmnj** [comment] 2021-11-25 10:00
Please see this https://github.com/flutter/flutter/issues/89839#issuecomment-919437144

**Comment by danagbemava-nc** [comment] 2021-11-25 10:49
Closing as this is intended behavior based on https://github.com/flutter/flutter/issues/89839#issuecomment-919437144.

Thank you

**Closed by danagbemava-nc** 2021-11-25 10:49 UTC
Labels: in triage
