### ISSUE TITLE
Feature Resolution for #26500/26499

### ISSUE THREAD

**Issue by mposch-Z** [flutter/flutter#73513] opened 2021-01-07 22:44 UTC
## Use case

The iOS keyboard hides text fields defined in a ReorderableListView nested in a Scaffold.  I have a BottomAppBar that needs to dock to the keyboard when the keyboard is displayed, but also need to keep focus on the selected TextFormField.  I have workarounds for all of this but nothing super clean that I'm happy with.  This is a direct question regarding #26499 /#26500 ... Was there a formally adopted outcome from these conversations as applying the proposed code resolves my issue(s)?  It looks like nothing was ever merged with master.  If flutter provides a means of addressing these issues I've had no luck making sense of it.

  

## Proposal
    
Please just point me towards the flutter feature to accommodate this scenario if there was an adopted outcome from #26499 or #26500

**Comment by TahaTesser** [comment] 2021-01-08 10:29
Hi @mposch-Z 
PR was closed and the issue is still open. 
Duplicate of  https://github.com/flutter/flutter/issues/26499
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-08 10:29 UTC

**Comment by mposch-Z** [comment] 2021-01-14 19:06
Hi Taha -

I've followed up on said issue but it hasn't had much activity.  Forgive me as this is the first time I'm looking into open source contributions like this....  Can anything be done on the other issue to bring some attention to it? If not and you recommend re-opening THIS post to revive the conversation, I'm all for it.

**Comment by TahaTesser** [comment] 2021-01-15 12:44
@mposch-Z 
Please add thumbs-up reaction https://github.com/flutter/flutter/issues/26499#issue-398688755 in the existing to raise it
