### ISSUE TITLE
I have an issue migrating my flutter project to Androidx. I always get the message 'no usage found'

### ISSUE THREAD

**Issue by ibeduifeoma** [flutter/flutter#84841] opened 2021-06-18 08:34 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-06-18 13:04
Closing this as self-duplicate of https://github.com/flutter/flutter/issues/84789.
Please don't create multiple issues for same reason.

**Closed by darshankawar** 2021-06-18 13:04 UTC
Labels: in triage
