### ISSUE TITLE
ListView with shrinkwrap overscrolls out of bounds

### ISSUE THREAD

**Issue by git2321231** [flutter/flutter#89717] opened 2021-09-09 06:45 UTC
After upgrade to Flutter 2.5.0,The default behavior of ListView has changed. If shrinkwrap is set to true, the boundary will be exceeded when dragging down, and I can't find a solution.

Source code (base on Flutter demo application):
```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Container(
          color: Colors.red,
          child: ListView.separated(
              shrinkWrap: true,
              itemBuilder: (BuildContext cxt, int index) {
                return Text(index.toString());
              },
              separatorBuilder: (BuildContext cxt, int index) {
                return const Divider();
              },
              itemCount: 10),
        ));
  }
}
```

When draging down:

<img src="https://user-images.githubusercontent.com/11640176/132635996-5eaaa9c1-7463-457a-a0ec-f95242fb4f20.png" width ="300">

```
flutter doctor -v:
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5 20G71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.0 at /Users/hanshow/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (24 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hanshow/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Eric的iPhone (mobile)   • 848a623cc8b97cb9f228d7bcdab7cfb3e927f6a1 • ios            • iOS 14.6
      18F72
    • iPhone 11 Pro (mobile) • A644453F-7AF6-4F01-8BDA-3BD4BDADADA5     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                                   • web-javascript • Google
      Chrome 93.0.4577.63

• No issues found!

```

**Comment by maheshmnj** [comment] 2021-09-09 09:57
Hi @git2321231, Thanks for filing the issue, I am able to replicate the issue on the latest stable 2.5.0 and it seems to working fine on `2.2.3`  so this seems to be a regression. This issue is reproducible on the latest `master 2.6.0-1.0.pre` as well.

2.2.3 | 2.5.0
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/132663904-ff1ea03c-390b-40bf-a426-1a7c4b14add9.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/132663884-bffdc167-be57-4702-b8be-0f8185c1355c.mov' width=180/>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter_dev
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (28 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>



This issue seems related to https://github.com/flutter/flutter/issues/86584

**Comment by Piinks** [comment] 2021-09-09 16:00
Hey @git2321231 thanks for reporting! I suspect this may be from https://github.com/flutter/flutter/pull/87143, investigating now. :)

**Comment by Piinks** [comment] 2021-09-09 16:50
Can you share the expected behavior @git2321231? 
Do you think that the list should not overscroll?
Or should it overscroll with the red background extending to fill the space?

I have confirmed this was caused by #87143, which resolved this issue https://github.com/flutter/flutter/issues/10949

**Comment by Piinks** [comment] 2021-09-09 16:53
Also a potential expectation: That the red box stays the same size and the overscroll sees the end content disappear within the bonds of the box.

**Comment by git2321231** [comment] 2021-09-09 17:09
@Piinks Thank you for your reply. I think listview should scroll within its parent widget(red container). And whether dragging up or down, it should have the same performance. In the current version 2.5.0, scrolling up will not exceed the top boundary, but scrolling down will exceed the bottom boundary, which is strange. Hope to see fixes in future releases. thank you.

**Comment by git2321231** [comment] 2021-09-09 17:29
In most app designs, the red container in the example may be designed as a background with rounded corners and outer margins to wrap the list content.  we use shrinkwrap to make the outer container close to the content.Therefore, it is not expected to exceed the boundary when dragging.:(

**Comment by Piinks** [comment] 2021-09-09 17:36
Thank you for the additional context!

**Comment by Piinks** [comment] 2021-09-20 22:22
The fix is in #90419 :)

**Comment by git2321231** [comment] 2021-10-09 03:03
@Piinks @maheshmnj 
Today, I switched to the master branch and updated it to the latest version 2.6.0-12.0.pre.281, but this problem still hasn't been solved. I checked the branch submission record and confirmed that the #90419 solution to this problem has been merged into the master branch, but the list content will still exceed the boundary. You can try again using the code above.

At present, the project of our company cannot be released because of this bug. We sincerely hope to solve this problem as soon as possible. Thank you very much:)

```
flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.281, on macOS 11.5 20G71 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.281 at /Users/hanshow/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45ffcc646d (6 hours ago), 2021-10-08 17:18:02 -0400
    • Engine revision 597516c2fe
    • Dart version 2.15.0 (build 2.15.0-178.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hanshow/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • TC601 GWL (mobile)     • A521201901769                        • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro (mobile) • EB193F60-B00D-4778-802E-C89AC2C63952 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

**Comment by git2321231** [comment] 2021-10-09 06:47
@Piinks After looking at your test example, I found the difference. In your example, the reason why you passed the test is that you have specified the height of the container as 150. If you do so, specifying shrinkwrap is meaningless. You should verify without specifying the height of the parent container.

Your test example:
```
Directionality(
          textDirection: TextDirection.ltr,
          child: MediaQuery(
            data: const MediaQueryData(),
            child: Column(
              children: <Widget>[
                Container(height: 100, color: const Color(0x00000000)),
                Container(
                  height: 150,
                  color: const Color(0xFFF44336),
                  child: ListView.builder(
                    shrinkWrap: true,
                    physics: const BouncingScrollPhysics(
                        parent: AlwaysScrollableScrollPhysics()),
                    itemBuilder: (BuildContext context, int index) =>
                        Text('Item $index'),
                    itemCount: 10,
                  ),
                ),
                Container(height: 100, color: const Color(0x00000000)),
              ],
            ),
          ),
        )


```

**Closed** 2021-10-20 18:01 UTC
Labels: severe: regression, framework, f: material design, waiting for PR to land (fixed), f: scrolling, a: layout, has reproducible steps, r: fixed, found in release: 2.5, found in release: 2.6, regression identified
