### ISSUE TITLE
 My first widget, a round image widget.  

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#1021] opened 2015-12-24 12:34 UTC
But I thing the code is too long. Do you have any idea help me sort the code?

[round_image.txt](https://github.com/flutter/flutter/files/71733/round_image.txt)

**Comment by abarth** [comment] 2015-12-24 17:36
The reason the code is so long is that you're not making use of any of the machinery available to you.  For example, why not integrate with BoxPainter, BoxDecoration, and backgroundImage?  You should be able to draw a round image using a BoxShape.circle combined with a backgroundImage.

**Comment by abarth** [comment] 2016-01-02 03:56
I'm going to close this issue because it's not a bug report.  Happy to chat about your widget on IRC sometime.  We're on #flutter on freenode.

**Closed by abarth** 2016-01-02 03:56 UTC
