### ISSUE TITLE
A Border can only draw strokeAlign different than BorderSide.strokeAlignInside on borders with uniform colors

### ISSUE THREAD

**Issue by m4tuna** [flutter/flutter#147979] opened 2024-05-08 14:09 UTC
### What package does this bug report belong to?

platform

### What target platforms are you seeing this bug on?

iOS, Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Set border radius to 0
2. Set stroke align to CENTER or OUTSIDE
3. Have different widths

### Expected results

Expecting the stroke and border to render with these settings.

### Actual results

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
A Border can only draw strokeAlign different than BorderSide.strokeAlignInside on borders with
uniform colors.

### Code sample

<details open><summary>Code sample</summary>

```dart
border: Border(
  top: BorderSide(color: Colors.amber, width: 10, strokeAlign: 1.0),
  right: BorderSide(color: Colors.amber, width: 10, strokeAlign: 1.0),
  bottom: BorderSide.none,
  left: BorderSide(color: Colors.amber, width: 10, strokeAlign: 1.0),
),

border: Border(
  top: BorderSide(color: Colors.amber, width: 10, strokeAlign: 0.0),
  right: BorderSide(color: Colors.amber, width: 10, strokeAlign: 0.0),
  bottom: BorderSide.none,
  left: BorderSide(color: Colors.amber, width: 10, strokeAlign: 0.0),
),
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
A Border can only draw strokeAlign different than BorderSide.strokeAlignInside on borders with
uniform colors.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-05-09 05:59
Hi @m4tuna 
This is working as intended. You are passing `BorderSide.none` which has `strokeAlignInside` by default and causes the error at: 

https://github.com/flutter/flutter/blob/076e701f4693c7f3215281e4896ae8349ae8474b/packages/flutter/lib/src/painting/box_border.dart#L676-L679

Closing this as it's WAI. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2024-05-09 05:59 UTC
Labels: in triage
