### ISSUE TITLE
Tall cards cast an abnormally large shadow

### ISSUE THREAD

**Issue by gnawf** [flutter/flutter#14114] opened 2018-01-16 08:42 UTC
## Steps to Reproduce

The height of the first `Card` in the sample code is exaggerated to illustrate the issue; the issue can be seen with some shorter cards. The second, smaller card is only there for comparison; the shadow cast by it is normal.

I'm encountering this bug when displaying long posts written by users.

<img src="https://user-images.githubusercontent.com/9077461/34974928-4b731c6a-faf4-11e7-9296-18391c79a63f.png" height=410/>

Code to reproduce:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Bug'),
        ),
        body: new ListView(
          children: <Widget>[
            // Bad card
            new Container(
              margin: const EdgeInsets.all(16.0),
              child: new Card(
                child: new Container(
                  height: 4000.0,
                ),
              ),
            ),
            // Good card
            new Container(
              margin: const EdgeInsets.all(16.0),
              child: new Card(
                child: new Container(
                  height: 50.0,
                ),
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
```

## Logs

Running `flutter run` and `flutter analyze` did not output anything.

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NZ, channel master)
    • Flutter at /Users/gnawf/flutter
    • Framework revision 6a42ed3f55 (3 days ago), 2018-01-12 15:12:26 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /usr/local/opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' to enable developer mode.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.3.1)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31

[✓] Connected devices
    • iPhone 8 • 533B1ADF-56E5-4A63-9319-1F704E8845E0 • ios • iOS 11.2 (simulator)
```

**Comment by tlarsen7572** [comment] 2018-01-21 01:39
I have seen this in my app as well.  It uses cards to create a kind of custom calendar view.  The difference in shadows is obvious when a tall card and a short card end at the same position.
![simulator screen shot - iphone 7 - 2018-01-20 at 20 37 08](https://user-images.githubusercontent.com/13069719/35189871-ffe16fbe-fe21-11e7-8caf-e99c30e2db3f.png)

**Comment by Hixie** [comment] 2018-01-21 02:14
We recently (late last week) changed some of the logic around painting outside the bounds of widgets (which shadows do). Does this still happen on master?

**Comment by tlarsen7572** [comment] 2018-01-21 02:25
I just tried it on the master branch and I don't see a change in the behavior of the shadows.

**Comment by fractalemagic** [comment] 2018-01-21 02:35
Yeah I just pulled master and ran the sample code, the issue is still present.

Here's the relevant output of `flutter doctor` if it's of any help.

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NZ, channel master)
    • Flutter version 0.0.21-pre.287 at /Users/gnawf/flutter
    • Framework revision 159db5ca44 (4 hours ago), 2018-01-20 14:43:23 -0800
    • Engine revision e45eb692b1
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06
```

**Comment by Hixie** [comment] 2018-01-21 09:36
Thanks. If this is blocking your app, please contact @sethladd. Our current plan is to look at this in a few months.

cc @jason-simmons who will probably end up looking at it.

**Comment by markusaksli-nc** [comment] 2020-10-01 08:36
Closing this as fixed.

**Closed by markusaksli-nc** 2020-10-01 08:36 UTC
Labels: P4, engine
