### ISSUE TITLE
##Regional differentiation ## TextInput.finishAutofillContext() doesn't bring up the system prompt-iOS

### ISSUE THREAD

**Issue by lidong-jimi** [flutter/flutter#153261] opened 2024-08-12 03:46 UTC
### Steps to reproduce

Apple app site association has been correctly configured.
After calling TextInput.finishAutofillContext(), there was no pop-up of the save password mode box.
(Is it related to the region that it works well in Japan but not in China?)

### Expected results

Japanese client can use the emulator (iphone 15 iOS 17.5) normally.
After uploading to Testflight, it can also be used normally on iOS 17.5.1 phones in Japan for testing.

<img width="291" alt="截屏2024-08-12 12 29 33" src="https://github.com/user-attachments/assets/250d6090-6ab8-42e7-880f-4f947e8e646a">

### Actual results

I am using the same version of the simulator in China and cannot use it properly. There is no modal box popping up.
After uploading to Testflight, it failed to pop up properly on iOS 16 and iOS 17 phones in China during testing.

### Code sample

<details open><summary>Code sample</summary>

```dart
AutofillGroup(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    CommonTextFiled(
                        title: "メールアドレス",
                        autofillHints: const [AutofillHints.email],
                        inputType: TextInputType.emailAddress,
                        controller: controller.emailController.value,
                        placeholder: "メールアドレスを入力してください",
                        textLength: 200),
                    Container(height: 24.w),
                    Obx(() => CommonTextFiled(
                          title: "パスワード",
                          autofillHints: const [AutofillHints.password],
                          controller: controller.passwordController.value,
                          placeholder: "パスワードを入力してください",
                          obscureText: controller.obscureTextValue.value,
                          textLength: 200,
                        )),
                    Container(height: 26.w),
                    CustomElevatedButton(
                        text: 'ログイン',
                        onPressed: () => TextInput.finishAutofillContext()),
                  ],
                ),
              )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.2 23C64 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.24.0 on channel stable at
      /Users/apple/Library/Flutter/flutter_3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPhone 15 (mobile)              • B4C452ED-AD9A-4F12-9D45-009334CC99B5 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • iPhone 15 Pro Max (mobile)      • 770ED060-AFCE-4CE5-A128-F94205178663 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-12 10:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/116889

This isn't really a regional issue but an issue with autofill in flutter on iOS in general.

**Closed by danagbemava-nc** 2024-08-12 10:33 UTC
Labels: in triage
