### ISSUE TITLE
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.

### ISSUE THREAD

**Issue by game-r** [flutter/flutter#83317] opened 2021-05-25 00:58 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "windows_x64"
pid=11356, thread=16972, isolate_group=main(00000191F5C24F10), isolate=(nil)(0000000000000000)
isolate_instructions=191f4f70000, vm_instructions=7ff6b8a6fa70
  pc 0x00007ff6b8bf6426 fp 0x00000026429fe100 Unknown symbol
-- End of DumpStackTrace
the Dart compiler exited unexpectedly.

```
```

</details>

> 

> 

>

**Comment by deveshgarg-max** [comment] 2021-05-25 04:09
Can you elaborate on your problem what kind of issue are you facing? 
also, provide
flutter doctor -v

**Comment by TahaTesser** [comment] 2021-05-25 12:36
Closing as duplicate of https://github.com/flutter/flutter/issues/82431
Please follow up there

**Closed by TahaTesser** 2021-05-25 12:36 UTC
Labels: in triage
