### ISSUE TITLE
Slow rendering performance

### ISSUE THREAD

**Issue by kamrancr7** [flutter/flutter#28893] opened 2019-03-05 16:53 UTC
Whenever i run my app on a physical device i continuously get the following message in my log
And also the performance of app in my physical device is very slow it stuck a lot

W/IInputConnectionWrapper( 9186): finishComposingText on inactive InputConnection
W/FlutterTextInput( 9186): method not implemented
W/FlutterTextInput( 9186): method not implemented
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=7), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=5), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=4), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=7), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=5), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=4), app behavior is wrong
V/InputMethodManager( 9186): onWindowFocus: io.flutter.view.FlutterView{49ad53f VFE...... .F...... 0,0-720,1344} softInputMode=16 first=false flags=#81810100
I/SurfaceView( 9186): updateWindow -- setFrame, this = io.flutter.view.FlutterView{49ad53f VFE...... .F....I. 0,0-720,1344}
I/SurfaceView( 9186): Punch a hole(dispatchDraw), this = io.flutter.view.FlutterView{49ad53f VFE...... .F...... 0,0-720,1344}
W/RenderThread( 9186): type=1400 audit(0.0:447416): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=7), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=5), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=4), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=7), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=5), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=4), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=7), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=5), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=6), app behavior is wrong
E/        ( 9186): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=4), app behavior is wrong

**Comment by freeler** [comment] 2019-03-22 08:46
me too

**Comment by ervansanjaya** [comment] 2019-05-17 16:38
I'm confirming this issue on Flutter: 1.5.4-hotfix.2

CPH1725 Android API 25

With Dart and Flutter 3.0.2

Any suggestion please

**Comment by fauzipadlaw** [comment] 2019-08-14 08:35
facing the same issue

**Comment by fauzipadlaw** [comment] 2019-08-16 08:44
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/efzet/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/efzet/Android/Sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /home/efzet/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • CPH1729 • EQ8SJFTGWK9PWCLV • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-24 12:16
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by kamrancr7** [comment] 2019-09-25 15:47
this issue is persisting on specific device, i also tried on different device and it is working fine.

**Comment by escamoteur** [comment] 2019-09-25 16:03
Can you please list the devices with their OS version where this behaviour occurs?

**Comment by kamrancr7** [comment] 2019-09-25 16:28
Device Model: Oppo A83
OS version: Android 7.1 (Nougat)

**Comment by nashihu** [comment] 2019-12-08 15:56
hello, it also occur on Oppo F5 with OS Version 7.1.1

**Comment by escamoteur** [comment] 2019-12-21 18:12
@kamrancr7 @nashihu could you please add the output of `flutter doctor -v`?

**Comment by nashihu** [comment] 2019-12-21 21:07
here @escamoteur 
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.765], locale en-ID)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\username\flutter\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\as\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by kamrancr7** [comment] 2019-12-22 14:59
@escamoteur that issue i'm facing with my previous device, i also mentioned that device in my previous comment. Now i have other device and on that i'm not facing that issue.

**Comment by escamoteur** [comment] 2019-12-22 15:50
@nashihu You are on a quite old Flutter version. The current one is v1.12.13+hotfix.5 please run a `flutter upgrade` and try again.

@kamrancr7 Please add the `flutter doctor -v output`

**Comment by kamrancr7** [comment] 2019-12-22 16:43
@escamoteur please check:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\FlutterUpg\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Kamran\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\Kamran\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • CPH1819 • DMUGUK9DMZJBHIVW • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-12-25 16:22
I Changed the title to 'Slow rendering performance' because as I understand it that is the real problem.
Could all of you try switching to the master channel and check if it still appears?
Also a List of all Devices with the OS version where this is a problem would be helpful to find a pattern

**Comment by nashihu** [comment] 2020-01-08 22:13
hello. After I upgrade flutter to v1.12.13+hotfix.5 and make sure that the project is using androidx, the problem disappear

**Comment by iapicca** [comment] 2020-01-14 10:57
Hi @kamrancr7 
Are you still experiencing the issue with the latest stable version of Flutter?
If so, can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by iapicca** [comment] 2020-02-21 11:30
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-21 11:30 UTC
Labels: a: text input, e: device-specific, severe: performance, severe: rendering, waiting for customer response, ▣ platform-android
