### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by bchauca** [flutter/flutter#35912] opened 2019-07-10 20:57 UTC
Hi i am starting developing in flutter, i am trying to add an icon on a textfield but its not aligned.

```
class TabProfile extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("assets/background_startapp.png"),
            fit: BoxFit.cover
          )
        ),
        child: SafeArea(
          child: Column(
            children: <Widget>[
              Container(height: 180),
              Container(
                color: Colors.white,
                child: TextField(
                  style: TextStyle(fontSize: 14.0),
                  decoration: InputDecoration(
                    //contentPadding: EdgeInsets.only(top: 15), // i have to add this to fix the problem
                    hintText: 'Email',
                    prefixIcon: Icon(Icons.mail_outline, size: 20),
                  ),
                )
              )
            ]
          )
        )
      )
    );
  }
}
```

<img width="1416" alt="Screen Shot 2019-07-10 at 15 49 50" src="https://user-images.githubusercontent.com/52761756/61004319-5cf51e80-a32b-11e9-9081-eb7e8d22907b.png">

**Comment by kush3107** [comment] 2019-07-11 08:50
No this is not a bug, I think you should `Stack` widget and wrap your icon inside a `Position` widget. This will work exactly like the `position: absolute` works in CSS.

**Comment by bchauca** [comment] 2019-07-11 15:57
> No this is not a bug, I think you should `Stack` widget and wrap your icon inside a `Position` widget. This will work exactly like the `position: absolute` works in CSS.

But if you add an OutlineInputBorder or if you use icon(not preffixIcon) then the icon and the text is aligned.

**Comment by BondarenkoStas** [comment] 2019-09-29 19:52
@bchauca Did you find a solution?

**Comment by iapicca** [comment] 2019-11-11 13:49
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-11 13:49 UTC
Labels: d: stackoverflow, framework, waiting for customer response
