### ISSUE TITLE
When do hot restart , flutter lost connection to device.

### ISSUE THREAD

**Issue by takemuseki** [flutter/flutter#81966] opened 2021-05-06 09:38 UTC
A huge thank you to the Flutter team for doing such a great job!😄😆

 When I hot restart my App, the following message will be displayed. And flutter lost connection to device.

```console
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
```

On iOS simulator: iPhone 12 Pro max : iOS 14.4

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91
    darwin-arm, locale ja-JP)
    • Flutter version 2.0.6 at
      /Users/takemuseki/WorkSpace/sdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29
      17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.3)
    • Android SDK at /Users/takemuseki/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 633A49D6-2095-4FD0-920D-74B8A0CBB9AF
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)               • chrome
      • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>

**Comment by TahaTesser** [comment] 2021-05-06 12:06
Hi @TahaTesser 
Thanks for filing the issue, I cannot reproduce the issue on the same `stable` channel  on the iOS simulator

Might be related https://github.com/flutter/flutter/issues/81834

**Comment by Nolence** [comment] 2021-05-07 01:59
Same issue on one of my older projects. Only happens to me on iOS. Tried `stable`, `dev` and `beta` channels and all the same result.

<details>
  <summary>flutter doctor -v</summary>
  
```console
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.3.0-0.1.pre at /Users/katzen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (11 days ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/katzen/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Users/katzen/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 43878B80-FE7A-443A-83AB-50BBE76EFFBE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
</details>

**Comment by osaxma** [comment] 2021-05-07 15:35
Same issue here on `2.0.6 stable` with iOS. Whenever I hot restart, I get the error shown in the log below.

It only happens when running on VS Code. If I use `flutter run` in the terminal, I don't face the issue.  Also this only happens on one of my apps, which has several packages. The counter app works fine. 

Log after hitting hot restart:
```
[+15549 ms] Skipping target: gen_localizations
[        ] complete
[  +11 ms] Scanned through 625 files in 8ms
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:XXXX/main.dart f5af5ef7-29f7-49ac-8695-a1db6f81b149
package:XXX/main.dart:1
[        ] <- f5af5ef7-29f7-49ac-8695-a1db6f81b149
[  +97 ms] Updating files.
[  +28 ms] DevFS: Sync finished
[        ] Synced 38.1MB.
[        ] <- accept
[ +315 ms] Hot restart performed in 453ms.
[   +2 ms] Restarted application in 462ms.
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
[ +527 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///Users/osaxma/Library/Developer/CoreSimulator/Devices/20902D63-402D-4024-A9C1-FA78D26B16B1/data/Containers/Data/Application/CE6188B7-7923-4B9B-878A-337A5D26755E/tmp/XXX9SNJjL/XXX/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
Exited (sigterm)
```


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.6 at /Users/osaxma/fvm/versions/stable
    • Framework revision 1d9032c7e1 (8 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/osaxma/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 20902D63-402D-4024-A9C1-FA78D26B16B1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
</details>

**Comment by takemuseki** [comment] 2021-05-08 07:43
Hi @osaxma 

If you don't mind me asking, could you tell me what package you are using?

**Comment by osaxma** [comment] 2021-05-08 23:07
Hi @takemuseki 

No problem, I'm using the following :

```
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.0 
  firebase_auth: ^1.0.0 
  firebase_storage: ^8.0.0

  sembast: ^3.0.2

  provider: ^5.0.0

  cached_network_image: ^3.0.0-nullsafety
  image_cropper: ^1.4.0 
  file_picker: ^3.0.0
```

**Comment by traed** [comment] 2021-05-09 16:35
I was playing around with google maps and started having the same issue, only my app crashes at startup. This started after I installed `google_maps_flutter: ^2.0.3`. I have since removed that package but the app still crashes.

```
Launching lib/main.dart on iPhone 11 in debug mode...
lib/main.dart:1
Xcode build done.                                           14.0s
Connecting to VM Service at ws://127.0.0.1:55357/q9884S0HJ-A=/ws
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Lost connection to device.
Exited (sigterm)
```

<details><summary>Flutter doctor</summary>
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-SE)
    • Flutter version 2.0.6 at /usr/local/flutter
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattias/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • F1AE8C78-D585-47F2-B55E-A76B31F0E04A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
</details>

**Comment by osaxma** [comment] 2021-05-11 18:14
@Nolence thanks a lot for reporting. After upgrading all the firebase packages to their latest versions, I'm not facing the issue anymore. 

Though this issue still keeps me uncomfortable how a package can cause flutter to break without any helpful error message or an indication to which package.

**Comment by takemuseki** [comment] 2021-05-12 11:47
@Nolence @osaxma  
😆thanks a lot for reporting .  After upgrading all the firebase packages to their latest versions, I'm not facing the issue anymore!

**Comment by jmagman** [comment] 2021-05-17 23:00
Closing.

**Closed by jmagman** 2021-05-17 23:00 UTC
Labels: customer: crowd, passed first triage, severe: crash, tool
