### ISSUE TITLE
[webView] response to events from the widget above it

### ISSUE THREAD

**Issue by beydeng** [flutter/flutter#73926] opened 2021-01-14 07:29 UTC
1 as i use two  container in the Stack, the overlap part will response the only top widget event. 

`child: Stack(
    children: [
      Positioned(
          left: 100,
          top: 100,
          width: 100,
          height: 100,
          child: GestureDetector(
            onTap: (){
              print('black_0F_nineth');
            },
            child: Container(
              color: Dpcolor.black_0F_nineth,
            ),
          )
      ),
      Positioned(
        left: 100,
        top: 120,
        width: 100,
        height: 100,
        child: GestureDetector(
          onTap: (){
            print('blue_00_nineth');
          },
          child: Container(
            color: Dpcolor.blue_00_nineth,
          ),
        )
      )
    ],
  ),`

import 'package:webview_flutter/webview_flutter.dart';
2 but as i use a WebView widget in in the Stack,the overlap part will response both top widget event and WebView js event.

`Stack(
          children: [
            Positioned(
              left: 20,
              top: Utils.topHeight()+20,
              width: ScreenUtil.getInstance().screenWidth - 40,
              height: _h,
              child: Card(
                child: Container(
                  height: _h,
                  child: WebView(
                  ),
                ),
              ),
            ),
            Positioned(
              left: 0,
              bottom: 0,
              width: Utils.screenWidth(),
              height: 100,
              child: GestureDetector(
                behavior:HitTestBehavior.opaque,
                onTap: (){
                  print('ssss');
                },
                child: Container(
                  color: Dpcolor.black_0F_nineth,
                ),
              ),
            ),
          ],
        )`

**Comment by pedromassangocode** [comment] 2021-01-14 07:36
Hi @beydeng 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by beydeng** [comment] 2021-01-15 05:41
flutter doctor -v
[✓] Flutter (Channel unknown, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/dengpan/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dengpan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dengpan/Library/Android
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 91758AC4-A806-4B14-B5D4-2C25E6D3A87E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    ! Error: PanX is not connected. Xcode will continue when PanX is connected.
      (code -13)

! Doctor found issues in 2 categories.

**Comment by beydeng** [comment] 2021-01-15 05:42
pubspec.yaml

  cupertino_icons: ^1.0.0
  fish_redux: ^0.3.4
  flutter_easyloading: ^2.2.1
  flustars: ^0.3.3
    # https://github.com/Sky24n/sp_util
  sp_util: ^1.0.1
  fluro : ^1.7.8
  cached_network_image: ^2.4.1
  webview_flutter: ^1.0.7

**Comment by pedromassangocode** [comment] 2021-01-15 08:19
Hi @beydeng 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? The code above is not complete and contains compilation errors as well.
Thank you

**Comment by beydeng** [comment] 2021-01-22 03:08
https://github.com/beydeng/webview_stack_demo.git

the address of demo

**Comment by beydeng** [comment] 2021-01-22 03:44
the yellow widget can triggering event to webview.

**Comment by beydeng** [comment] 2021-01-22 07:00
![image](https://user-images.githubusercontent.com/7223164/105457512-ebd54c00-5cc1-11eb-910c-49076f841c7d.png)
![image](https://user-images.githubusercontent.com/7223164/105457824-643c0d00-5cc2-11eb-8fe8-3ff950067016.png)

Does this mean that WebView is actually on top of Black Contain, but in the first image it looks like it's underneath it?

**Comment by pedromassangocode** [comment] 2021-01-22 07:30
Hi @beydeng 
I was able to reproduce the issue.

![gif](https://user-images.githubusercontent.com/67424416/105460031-7b133d00-5c8b-11eb-9744-5dd0b3abfc0e.gif)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by pedromassangocode** [comment] 2021-01-22 15:01
Closing as duplicate of https://github.com/flutter/flutter/issues/58659. Please follow up on that issue.
Thank you

**Closed by pedromassangocode** 2021-01-22 15:01 UTC
Labels: a: platform-views, f: gestures, found in release: 1.22, has reproducible steps, p: webview, platform-ios
