### ISSUE TITLE
Android "java.lang.IndexOutOfBoundsException" when TextEditingController clear() called

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#10817] opened 2017-06-18 07:58 UTC
I have a search box with an attached clear button. When the clear button is pressed the search box should be cleared. 

![image](https://user-images.githubusercontent.com/7585117/27259037-cebddd5c-5401-11e7-9300-13f2399e6d05.png)

This is the `TextEditingController` &  the `TextField` set up.
![image](https://user-images.githubusercontent.com/7585117/27259057-5f2a067c-5402-11e7-8f4b-3388e18dba47.png)

![image](https://user-images.githubusercontent.com/7585117/27259071-9e2e7d80-5402-11e7-8aea-49592a277da6.png)

![image](https://user-images.githubusercontent.com/7585117/27259080-cd3de458-5402-11e7-96d8-d2564164961b.png)

When the clear button is pressed the controller `clear()` method is called which results in an exception in the Android Simulator and on an actual device as well (Samsung Galaxy A3/Andoid 6.0.1).

Framework • revision 3b6d84b083 (2 days ago) • 2017-06-16 12:58:23 -0700
Engine • revision 784e975672 Tools • Dart 1.24.0-dev.6.7

Let me know if you need any additional info.

  

E/MethodChannel#flutter/textinput( 4187): Failed to handle method call
E/MethodChannel#flutter/textinput( 4187): java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
E/MethodChannel#flutter/textinput( 4187): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
E/MethodChannel#flutter/textinput( 4187): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
E/MethodChannel#flutter/textinput( 4187): 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
E/MethodChannel#flutter/textinput( 4187): 	at android.text.Selection.setSelection(Selection.java:76)
E/MethodChannel#flutter/textinput( 4187): 	at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:147)
E/MethodChannel#flutter/textinput( 4187): 	at io.flutter.plugin.editing.TextInputPlugin.onMethodCall(TextInputPlugin.java:66)
E/MethodChannel#flutter/textinput( 4187): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter/textinput( 4187): 	at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:643)
E/MethodChannel#flutter/textinput( 4187): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 4187): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/textinput( 4187): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter/textinput( 4187): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#flutter/textinput( 4187): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 4187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#flutter/textinput( 4187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jason-simmons** [comment] 2017-06-19 23:48
Duplicate of https://github.com/flutter/flutter/issues/10748

The fix for this should be rolled out now

**Closed by jason-simmons** 2017-06-19 23:48 UTC
