### ISSUE TITLE
Samsung keyboard duplicates

### ISSUE THREAD

**Issue by 33-Elephants** [flutter/flutter#57471] opened 2020-05-18 09:31 UTC
Hello,
It seems the problems with Samsung keyboard are not fixed in Flutter v1.17.1.
When you type a text in text field and predictive text is turned on, sometimes text is duplicated.
The issue is reproducible on Samsung S8, S9 and S10 and other models

Here are two scenarios when the duplication is 100% reproducible:

1. 
- Text field contains preset text
- Tap on it to bring keyboard
- Add space and then remove space by pressing backspace
- Try to enter any char
- **Result:** preceding word is duplicated

2. 
- Text field contains preset text
- Tap on it to bring keyboard
- Add space and then remove space by pressing backspace
- Try to enter any char
- **Result:** preceding word is duplicated

```
flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/artem/Development/android-studio-projects/fluttter-meeting-client/flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/artem/Development/android-sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/artem/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/artem/Development/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • SM G973F • RF8N323VP9D • android-arm64 • Android 10 (API 29)

• No issues found!
Process finished with exit code 0
```

Here is the code for the first case:
```
import 'package:flutter/material.dart';

class AppExperimentalWidget extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return AppExperimentalWidgetState();
  }

}

class AppExperimentalWidgetState extends State {

  TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Ink(
          color: Colors.white,
          child: TextField(
            controller: controller
          )
        )
      )
    );
  }

}

```

Here is the code for the second case:
```
import 'package:flutter/material.dart';

class AppExperimentalWidget extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return AppExperimentalWidgetState();
  }

}

class AppExperimentalWidgetState extends State {

  TextEditingController controller = TextEditingController(text: "hello");

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Ink(
          color: Colors.white,
          child: TextField(
            controller: controller
          )
        )
      )
    );
  }

}

```

**Comment by TahaTesser** [comment] 2020-05-18 10:24
Hi @33-Elephants 
Testing the issue, it does reproduce `Channel stable, v1.17.1` but looks like this is fixed in `beta` and `dev` channels 

Please upgrade to `beta` or `dev` and try again 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-11.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 2738a1148b (5 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11  • B00B6F4E-B1CE-44F3-B81E-3EC6D639B008 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details> 

Closing as it seems to be fixed
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-18 10:24 UTC
