### ISSUE TITLE
[MacOS 14.0 & Xcode15] "failed to write to a file" error during build

### ISSUE THREAD

**Issue by wanyangye** [flutter/flutter#135199] opened 2023-09-21 04:40 UTC
### Steps to reproduce

I experienced a compilation error after upgrading to MacOS 14.0 Xcode15。
<details><summary>[Edited to hide, as this picture is of an unrelated warning]</summary>
![WX20230921-123454@2x](https://github.com/flutter/flutter/assets/44550529/ab7c06d8-8929-4d3a-88c2-98135ff114e8)
</details>

### Expected results

[buildinfo.log](https://github.com/flutter/flutter/files/12680261/buildinfo.log)

### Actual results

[buildinfo.log](https://github.com/flutter/flutter/files/12680242/buildinfo.log)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// Flutter code sample for [TextField].

class ObscuredTextFieldSample extends StatelessWidget {
  const ObscuredTextFieldSample({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 250,
      child: TextField(
        inputFormatters: [
          FilteringTextInputFormatter.deny(RegExp("[\u4e00-\u9fa5]")),
        ],
        autofocus: false,
        obscureText: true,
        keyboardType: TextInputType.visiblePassword,
        textInputAction: TextInputAction.next,
        decoration: InputDecoration(
          border: OutlineInputBorder(),
          labelText: 'Password',
        ),
      ),
    );
  }
}

class TextFieldExampleApp extends StatelessWidget {
  const TextFieldExampleApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Demo')),
        body: const Center(
          child: ObscuredTextFieldSample(),
        ),
      ),
    );
  }
}

void main() => runApp(const TextFieldExampleApp());

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![WX20230921-123454@2x](https://github.com/flutter/flutter/assets/44550529/e9d8cd59-c927-4f76-8176-d8acf67472c7)

</details>

### Flutter Doctor output

<details>
<summary>flutter doctor -v</summary>
<pre>
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.10.2, on macOS 14.0 23A339 darwin-arm64, locale
    zh-Hans-CN)
    ! Flutter version 3.10.2 on channel unknown at
      /Users/steven/Steven/Work/DevelopTools/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
Attempting to reach github.com...⣻
[!] Network resources             
    ✗ A network error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 4 categories.
</pre>
</details>

**Comment by ImagineBoom** [comment] 2023-09-21 09:09
I have also encountered this issue. May I ask if there is a solution?

**Comment by wanyangye** [comment] 2023-09-21 09:13
> I have also encountered this issue. May I ask if there is a solution?

MacOS 14.0 & Xcode15?

**Comment by huycozy** [comment] 2023-09-21 09:51
@wanyangye @ImagineBoom  I haven't had macOS 14.0 yet but I found [this answer](https://github.com/mogol/flutter_secure_storage/issues/600#issuecomment-1700770033) that you can try ti see if it works. 

If it doesn't work, please confirm:
- Does the issue happen on a newly created Flutter project (counter app)? 
- Please upgrade your Flutter SDK to the latest stable or master channel and retry to see if the result is different.
```
flutter channel master
flutter upgrade
```
- Please provide the entire output of `flutter run -v` on the reproducible sample code.

Thanks!

**Comment by ImagineBoom** [comment] 2023-09-21 09:54
> > I have also encountered this issue. May I ask if there is a solution?
> 
> MacOS 14.0 & Xcode15?

MacOS 13.5.2 
Xcode15.0

**Comment by wanyangye** [comment] 2023-09-21 10:10
> @wanyangye @ImagineBoom I haven't had macOS 14.0 yet but I found [this answer](https://github.com/mogol/flutter_secure_storage/issues/600#issuecomment-1700770033) that you can try ti see if it works.
> 
> If it doesn't work, please confirm:
> 
> * Does the issue happen on a newly created Flutter project (counter app)?
> * Please upgrade your Flutter SDK to the latest stable or master channel and retry to see if the result is different.
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> * Please provide the entire output of `flutter run -v` on the reproducible sample code.
> 
> Thanks!

[flutterInfo.log](https://github.com/flutter/flutter/files/12683293/flutterInfo.log)

this file is flutter run -v info

**Comment by ImagineBoom** [comment] 2023-09-21 10:26
> > @wanyangye @ImagineBoom I haven't had macOS 14.0 yet but I found [this answer](https://github.com/mogol/flutter_secure_storage/issues/600#issuecomment-1700770033) that you can try ti see if it works.
> > If it doesn't work, please confirm:
> > 
> > * Does the issue happen on a newly created Flutter project (counter app)?
> > * Please upgrade your Flutter SDK to the latest stable or master channel and retry to see if the result is different.
> > 
> > ```
> > flutter channel master
> > flutter upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Please provide the entire output of `flutter run -v` on the reproducible sample code.
> > 
> > Thanks!
> 
> [flutterInfo.log](https://github.com/flutter/flutter/files/12683293/flutterInfo.log)
> 
> this file is flutter run -v info

[flutterInfo2.log](https://github.com/flutter/flutter/files/12683452/flutterInfo2.log)

env: MacOS 13.5.2, Xcode15.0

Thanks!

**Comment by wanyangye** [comment] 2023-09-21 10:38
error: Sandbox: rsync.samba(44082) deny(1) file-write-create /Users/steven/Steven/Work/Code/PrintHub/Client/flutter/client/build/macos/Build/Products/Debug/FlutterMacOS.framework (in target 'Flutter Assemble' from project 'Runner')
Flutter failed to write to a file at "/Users/steven/Steven/Work/Code/PrintHub/Client/flutter/client/build/macos/Build/Products/Debug/.last_build_id".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
Try running:
  sudo chown -R $(whoami) /Users/steven/Steven/Work/Code/PrintHub/Client/flutter/client/build/macos/Build/Products/Debug/.last_build_id

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by ImagineBoom** [comment] 2023-09-21 10:46
Sorry, I just re-sent the log a moment ago, use the new prj's log.

**Comment by stuartmorgan** [comment] 2023-09-21 14:22
I've retitled this to be about the error, since it was reported as a build error, and hidden the screenshot of the unrelated and harmless warning.

@ImagineBoom Please file a new issue about the warning you are seeing, since that's not related to the error.

**Comment by cbracken** [comment] 2023-09-21 18:23
I ran across this in a couple Xcode/Sonoma betas. It disappeared for one developer beta (maybe the 6th beta), then reappeared in a later one. I can repro on last week's release candidates.

**Comment by cbracken** [comment] 2023-09-21 19:01
After testing with Xcode Version 15.0 (15A240d), I'm still seeing this error both in Flutter and non-Flutter app builds that are built from the command-line.

**Comment by wanyangye** [comment] 2023-09-22 02:09
> @wanyangye I notice this is indeed permission error on your output log (at `flutterInfo.log`) at [#135199 (comment)](https://github.com/flutter/flutter/issues/135199#issuecomment-1729268952). I don't see the initial **warning** (at `buildinfo.log`) there, though.
> 
> > [        ] [   +1 ms] Flutter failed to write to a file at "/Users/steven/Steven/Work/Code/PrintHub/Client/flutter/client/build/macos/Build/Products/Debug/.last_build_id".
> > [        ]            Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
> > [        ]            Try running:
> > [        ]              sudo chown -R $(whoami) /Users/steven/Steven/Work/Code/PrintHub/Client/flutter/client/build/macos/Build/Products/Debug/.last_build_id
> 
> You can try the following suggestion to see if it works.
> 
> @ImagineBoom I can see the same Warning on your output log (at `flutterInfo2.log`), the build is succeeded however.
> 
> Regarding the initial warning, I will label this for other's input.
> 
> Initial warning (from output log files)
> ```
> [  +37 ms] 2023-09-21 18:35:45.108 xcodebuild[18082:138468] [MT] DVTAssertions: Warning in
> /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisionin
> g/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
> [        ] Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
> [        ] Function: createItemModels(for:itemModelSource:)
> [        ] Thread:   <_NSMainThread: 0x600002620240>{number = 1, name = main}
> [        ] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
> ```

its not work。I've followed the advice, and it's not working. I have just upgraded to MacOS14 Xcode15 to run the flutter project when this prompt appears, before the latest version of MacOS13 and the latest version of Xcode14, there is no problem.

**Comment by wanyangye** [comment] 2023-09-22 02:42
I uninstalled Xcode 15 and used XCode 14.3 and now the flutter project is built properly.

<img width="1205" alt="image" src="https://github.com/flutter/flutter/assets/44550529/f0d9816f-6b59-47f2-97ab-fd6bdf0426e9">

Is flutter only supported up to 10.14? I need to be compatible with 10.13, is that OK?

**Comment by ImagineBoom** [comment] 2023-09-22 03:09
> I've retitled this to be about the error, since it was reported as a build error, and hidden the screenshot of the unrelated and harmless warning.
> 
> @ImagineBoom Please file a new issue about the warning you are seeing, since that's not related to the error.

OK, I have filed this issue #135277

Thanks!

**Comment by cbracken** [comment] 2023-09-22 17:35
@wanyangye the error you're experiencing is unrelated to the warning here
```
2023-09-21 11:25:40.187 xcodebuild[84698:3805495] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)                                   
Thread:   <_NSMainThread: 0x13e609ea0>{number = 1, name = main}                                                                                     
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
```

It's due to this error:
```
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Runner' from project 'Runner')
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Flutter Assemble' from project 'Runner') 
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Flutter Assemble' from project 'Runner')
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Pods-Runner' from project 'Pods')
```

which was filed in: https://github.com/flutter/flutter/issues/132755
and was fixed in: https://github.com/flutter/flutter/pull/132803

This is caused by an issue in CocoaPods, which was fixed in: https://github.com/CocoaPods/CocoaPods/pull/12009

However, as far as I'm aware, they haven't yet published a new release that includes their fix, so you'll need to rely on our workaround.

Please make sure you've got the latest Flutter version installed. You _may_ need to switch `master` branch, but I believe this has been cherry-picked to stable (though not sure if we've published that stable version yet).

Closing as a duplicate of #132755.

**Closed by cbracken** 2023-09-22 17:35 UTC
Labels: platform-mac, a: desktop, a: build, e: OS-version specific, P2, team-desktop, triaged-desktop

**Comment by cbracken** [comment] 2023-09-22 17:38
> Is flutter only supported up to 10.14? I need to be compatible with 10.13, is that OK?

This is off-topic for this bug; however, you can see our [Supported deployment platforms](https://docs.flutter.dev/reference/supported-platforms) page for details. Short answer: 10.14 (Mojave) is the minimum required version today. If you need support for older versions of macOS, you'll need to use an older version of Flutter (and possibly older version of Xcode).

**Comment by acamue** [comment] 2023-09-29 07:21
https://www.youtube.com/watch?v=VQIn41rFVAc
