### ISSUE TITLE
[webview_flutter] App Store Connect: The app references non-public selectors in webview_flutter_wkwebview.framework

### ISSUE THREAD

**Issue by Axort** [flutter/flutter#105486] opened 2022-06-07 00:52 UTC
I've been uploading builds to TestFlight without any problems until today, I have 34 builds with no issues. Today I tried to upload a new build and I'm getting an error related to `webview_flutter_wkwebview`. The .xcarchive file is generated with no issues but the problem is when uploading the build to TestFlight.

In the morning, developer.apple.com was in maintenance, I don't know if it has to do with the new things Apple announced in WWDC 2022.

## Steps to Reproduce

I can't share the project since it's private but what I can tell:
* iOS and Android app
* 2 flavors: dev and prod

1. Execute `flutter build ipa -t lib/main_dev.dart --flavor dev --build-name=1.0 --build-number=35` 
2. Execute `open build/ios/archive/Runner.xcarchive`, this will open the Organizer in Xcode. 
3. Press on Distribute App

**Expected results:** 

Upload the build successfully

**Actual results:** 

![Captura de Pantalla 2022-06-06 a la(s) 19 41 51](https://user-images.githubusercontent.com/4009741/172272031-32169b80-7e4c-46e9-a3e2-c50db61ba894.png)

<details>
<summary>Code sample</summary>

```dart
// Not related to code
```

</details>

<details>
  <summary>Logs</summary>

```
// Not related to code
```

```
// Not related to code
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
    ! Error: iPhone de Adriana is busy: Preparing the watch for development via iPhone de Adriana. Xcode will continue when iPhone de Adriana is finished. (code -10)
    ! Error: Alex is not connected. Xcode will continue when Alex is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2022-06-07 01:17
Duplicate of https://github.com/flutter/flutter/issues/105472

**Closed by stuartmorgan** 2022-06-07 01:17 UTC

**Comment by preteambuy** [comment] 2022-06-07 05:48
i used an older version of xcode 13.2.1 and was able to submit to the app store successfully
