### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by mohamad72** [flutter/flutter#141522] opened 2024-01-14 08:54 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile F:\flutterProjects\oa.erpfluttermobile\build\app\intermediates\flutter\debug/flutter_build.d --output F:\flutterProjects\oa.erpfluttermobile\build\app\intermediates\flutter\debug -dTargetFile=F:\flutterProjects\oa.erpfluttermobile\lib\main_dev.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC81NGE3MTQ1MzAzZjBkZDlkMGY5MzQyNGEyZTEyNGViNGFiZWY1MDkxLw== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#7      List.forEach (dart:core-patch/growable_array.dart:416:8)
#8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:251:14)
#9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:196:12)
#10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:149:39)
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:609:30)
#12     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:51)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.17763.4974], locale en-US)
    • Flutter version 3.16.4 on channel stable at F:\sdkandroidstudio\3.10\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (5 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://nexus3.dotin.ir/repository/pub-web.flutter/
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at F:\sdkandroidstudio\Sdk\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] Connected device (3 available)
    • 22071212AG (mobile) • TKC6S4W8U4YT4DKZ • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.17763.4974]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 120.0.6099.217

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.125.8+24
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
### Plugins
connectivity_plus-5.0.2
device_info_plus-9.1.1
device_safety_info-0.0.2
file_picker-6.1.1
flutter_file_manager_android-1.2.1
flutter_file_manager_ios-1.1.1
flutter_file_manager_macos-1.1.1
flutter_file_manager_web-1.1.1
flutter_file_saver-0.6.2
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_native_splash-2.3.9
flutter_plugin_android_lifecycle-2.0.17
flutter_windowmanager-0.2.0
integration_test
local_auth-2.1.7
local_auth_android-1.0.36
local_auth_ios-1.1.5
local_auth_windows-1.0.10
open_file-3.3.2
package_info_plus-4.2.0
pasteboard-0.2.0
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.1.0
permission_handler_android-12.0.1
permission_handler_apple-9.2.0
permission_handler_html-0.1.0+2
permission_handler_windows-0.2.0
url_launcher-6.2.2
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1

**Comment by dam-ease** [comment] 2024-01-15 09:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by dam-ease** 2024-01-15 09:18 UTC
Labels: in triage
