### ISSUE TITLE
The radio button "selector indicator" is not centered in web mobile

### ISSUE THREAD

**Issue by guplem** [flutter/flutter#113087] opened 2022-10-07 06:22 UTC
## Steps to Reproduce

1. Create an app with radio buttons to select.
2. Deploy it for web
3. Open the app in chrome mobile app

**Expected results:** The radio buttons "selector" to be visually aligned at the center of the radio button.

**Actual results:** The "select indicator" is misaligned. Not in the center of the radio button:

I have tried with Material 2 and Material 3 with the same results. So, if fixed, it should be made sure that the [Material 3 integration](https://github.com/flutter/flutter/issues/111450) is fixed as well.

![Screenshot_2022-10-07-07-40-19-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/11029629/194476454-a7c92b4e-60d7-4e53-b2de-e43d7f0949ad.jpg)

<details>
  <summary>Logs</summary>

flutter run --verbose:
It runs with no issues. I can't add the output because the issue becomes too long.

flutter analyze:
```
   info - Depend on referenced packages - lib\models\group_fs.dart:6:8 - depend_on_referenced_packages
   info - Unused import: 'package:things/models/user_fs.dart' - lib\models\group_fs.dart:8:8 - unused_import
   info - A value of type 'void' can't be returned by the 'onError' handler because it must be assignable to 'FutureOr<DocumentReference<GroupFS>>' - lib\models\group_fs.dart:51:57 - invalid_return_type_for_catch_error
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:51:57 - avoid_print
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:53:9 - avoid_print
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:57:71 - avoid_print
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:59:9 - avoid_print
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:69:67 - avoid_print
   info - Avoid `print` calls in production code - lib\models\group_fs.dart:70:5 - avoid_print
   info - Name non-constant identifiers using lowerCamelCase - lib\models\group_fs.g.dart:9:12 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\models\group_fs.g.dart:17:22 - non_constant_identifier_names
   info - Unused import: 'package:firebase_auth/firebase_auth.dart' - lib\models\thing_fs.dart:4:8 - unused_import
   info - Depend on referenced packages - lib\models\thing_fs.dart:8:8 - depend_on_referenced_packages
   info - A value of type 'void' can't be returned by the 'onError' handler because it must be assignable to 'FutureOr<DocumentReference<ThingFS>>' - lib\models\thing_fs.dart:68:85 - invalid_return_type_for_catch_error
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:68:85 - avoid_print
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:70:9 - avoid_print
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:74:99 - avoid_print
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:76:9 - avoid_print
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:86:95 - avoid_print
   info - Avoid `print` calls in production code - lib\models\thing_fs.dart:87:5 - avoid_print
   info - Name non-constant identifiers using lowerCamelCase - lib\models\thing_fs.g.dart:9:12 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\models\thing_fs.g.dart:28:22 - non_constant_identifier_names
   info - Unused import: 'dart:ui' - lib\models\user_fs.dart:1:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\models\user_fs.dart:5:8 - unused_import
   info - Depend on referenced packages - lib\models\user_fs.dart:9:8 - depend_on_referenced_packages
   info - Unused import: 'package:flutter/foundation.dart' - lib\models\user_fs.dart:10:8 - unused_import
   info - Avoid `print` calls in production code - lib\models\user_fs.dart:52:26 - avoid_print
   info - Avoid `print` calls in production code - lib\models\user_fs.dart:53:32 - avoid_print
   info - Name non-constant identifiers using lowerCamelCase - lib\models\user_fs.g.dart:9:11 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\models\user_fs.g.dart:18:22 - non_constant_identifier_names
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\pages\group_details_page.dart:1:8 - unused_import
   info - Prefer typing uninitialized variables and fields - lib\pages\group_details_page.dart:24:14 - prefer_typing_uninitialized_variables
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: GroupSelectorPage.user - lib\pages\group_selector_page.dart:12:7 - must_be_immutable    
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: HubPage.usersCollection - lib\pages\hub_page.dart:14:7 - must_be_immutable
   info - Avoid `print` calls in production code - lib\pages\hub_page.dart:32:11 - avoid_print
   info - Avoid `print` calls in production code - lib\pages\hub_page.dart:40:11 - avoid_print
   info - Prefer typing uninitialized variables and fields - lib\pages\thing_details_page.dart:21:14 - prefer_typing_uninitialized_variables
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: BlurEffectWithDecorations.blur, BlurEffectWithDecorations.opacity,
          BlurEffectWithDecorations.child, BlurEffectWithDecorations.borderRadius, BlurEffectWithDecorations.color, BlurEffectWithDecorations.borderOpacity, BlurEffectWithDecorations.borderWidth - lib\poy\blur_effect.dart:5:7 -     
          must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: GlassMorphismCapsule.child - lib\poy\blur_effect.dart:68:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: CenterColumnDynamicPadding.child - lib\poy\center_column_dynamic_padding.dart:3:7 -     
          must_be_immutable
   info - Prefer typing uninitialized variables and fields - lib\poy\center_column_dynamic_padding.dart:4:7 - prefer_typing_uninitialized_variables
   info - Don't access members with `this` unless avoiding shadowing - lib\poy\extensions\duration_extensions.dart:7:40 - unnecessary_this
   info - Don't access members with `this` unless avoiding shadowing - lib\poy\extensions\duration_extensions.dart:8:40 - unnecessary_this
   info - Don't access members with `this` unless avoiding shadowing - lib\poy\extensions\duration_extensions.dart:9:25 - unnecessary_this
   info - Prefer typing uninitialized variables and fields - lib\poy\full_screen_glass_morphism_dialog.dart:8:7 - prefer_typing_uninitialized_variables
   info - Prefer typing uninitialized variables and fields - lib\poy\full_screen_semi_opaque_dialog.dart:6:7 - prefer_typing_uninitialized_variables
   info - Avoid `print` calls in production code - lib\poy\utils\debug.dart:5:5 - avoid_print
   info - Use interpolation to compose strings and values - lib\poy\utils\debug.dart:5:11 - prefer_interpolation_to_compose_strings
   info - Avoid `print` calls in production code - lib\poy\utils\debug.dart:9:5 - avoid_print
   info - Use interpolation to compose strings and values - lib\poy\utils\debug.dart:9:11 - prefer_interpolation_to_compose_strings
   info - Use interpolation to compose strings and values - lib\poy\utils\debug.dart:13:16 - prefer_interpolation_to_compose_strings
   info - Unused import: 'dart:math' - lib\theme\custom_theme.dart:1:8 - unused_import
   info - Prefer declaring const constructors on `@immutable` classes - lib\views\things_list.dart:14:3 - prefer_const_constructors_in_immutables
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ActiveThing.user - lib\widgets\active_thing.dart:7:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SelectedGroup.user - lib\widgets\selected_group.dart:9:7 - must_be_immutable
   info - Prefer declaring const constructors on `@immutable` classes - lib\widgets\text_form_field_custom.dart:5:3 - prefer_const_constructors_in_immutables

56 issues found. (ran in 1.5s)
```

flutter doctor -v:
```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.22621.521], locale en-US)
    • Flutter version 3.3.3 on channel stable at K:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (9 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\guple\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.521]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-10-07 11:13
@guplem I can not reproduce the issue on the latest `stable` and `master` channels using sample code from https://api.flutter.dev/flutter/material/Radio-class.html.
I also tested with both Material 2 and Material 3 but didn't see the issue.

<details>
<summary>Demo</summary>

<img width="551" alt="Screen Shot 2022-10-07 at 18 05 36" src="https://user-images.githubusercontent.com/104349824/194540037-ad95fbd1-c6a9-47bf-9e33-07427cba7a36.png">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-3.0.pre.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-3.0.pre.5 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ca314afd0 (12 minutes ago), 2022-10-06 23:06:11 -0400
    • Engine revision a4174f29a7
    • Dart version 2.19.0 (build 2.19.0-286.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • SM T225 (mobile)           • R9JT3004VRJ                              • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)            • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7 19H12
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 106.0.5249.103
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, you can retry on a new flutter stable version `3.3.4` or the latest master channel `3.5.0` to see if the issue is still reproducible.

**Comment by guplem** [comment] 2022-10-07 12:34
> @guplem I can not reproduce the issue on the latest `stable` and `master` channels using sample code from https://api.flutter.dev/flutter/material/Radio-class.html. I also tested with both Material 2 and Material 3 but didn't see the issue.

I cannot see the issue either in Chrome desktop. I only see it in the chrome app for android (haven't tested in the emulator, only in deployed app).

I could reproduce it with the following code:

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

enum SingingCharacter { lafayette, jefferson }

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  SingingCharacter? _character = SingingCharacter.lafayette;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Card(
          clipBehavior: Clip.antiAlias,
          child: ListTile(
            title: const Text('Lafayette'),
            trailing: Radio<SingingCharacter>(
              value: SingingCharacter.lafayette,
              groupValue: _character,
              onChanged: (SingingCharacter? value) {
                setState(() {
                  _character = value;
                });
              },
            ),
          ),
        ),
        Card(
          clipBehavior: Clip.antiAlias,
          child: ListTile(
            title: const Text('Thomas Jefferson'),
            trailing: Radio<SingingCharacter>(
              value: SingingCharacter.jefferson,
              groupValue: _character,
              onChanged: (SingingCharacter? value) {
                setState(() {
                  _character = value;
                });
              },
            ),
          ),
        ),
      ],
    );
  }
}
```

As you can see, the differences with the [Radio class demo](https://api.flutter.dev/flutter/material/Radio-class.html) are:

- ListTiles using the trailing for the Radio class button.
- ListTiles surrounded by a Card widget with the parameter clipBehavior: Clip.antiAlias.

You can see screenshots of mobile (first) and desktop (second and third) here:
![Screenshot_2022-10-07-14-31-41-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/11029629/194554221-b170eec6-6334-4832-89a7-5aa9b3bf9098.jpg)

![2022-10-07 14_32_17-things – main dart](https://user-images.githubusercontent.com/11029629/194554275-c42e9a43-fb9b-44d2-b164-d001549327dc.png)

![2022-10-07 14_32_41-Flutter Code Sample](https://user-images.githubusercontent.com/11029629/194554302-848558ff-91cb-42a2-ae96-3038a15f202a.png)

**Comment by huycozy** [comment] 2022-10-10 03:16
>ListTiles surrounded by a Card widget with the parameter clipBehavior: Clip.antiAlias.

@guplem when using your modified sample code with above change, the issue is reproducible even on desktop browser when using `HTML` renderer. On mobile browser, it uses `HTML` renderer as default. See this for reference: https://docs.flutter.dev/development/platform-integration/web/renderers

You can use `RadioListTile` that may solve the issue with `Clip.antiAlias` usage (HTML renderer)

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

enum SingingCharacter { lafayette, jefferson }

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  SingingCharacter? _character = SingingCharacter.lafayette;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Card(
          clipBehavior: Clip.antiAlias,
          child: RadioListTile<SingingCharacter>(
            title: const Text('Lafayette'),
            value: SingingCharacter.lafayette,
            groupValue: _character,
            onChanged: (SingingCharacter? value) {
              setState(() {
                _character = value;
              });
            },
          ),
        ),
        Card(
          clipBehavior: Clip.antiAlias,
          child: RadioListTile<SingingCharacter>(
            title: const Text('Thomas Jefferson'),
            value: SingingCharacter.jefferson,
            groupValue: _character,
            onChanged: (SingingCharacter? value) {
              setState(() {
                _character = value;
              });
            },
          ),
        ),
      ],
    );
  }
}
```
</details>

**Comment by guplem** [comment] 2022-10-10 10:52
> the issue is reproducible even on desktop browser when using `HTML` renderer

You are right, using the command `flutter build web --release --verbose --web-renderer html` the issue is fully consistent with the mobile browser.



> On mobile browser, it uses `HTML` renderer as default. See this for reference: https://docs.flutter.dev/development/platform-integration/web/renderers

**Switching the renderer with the command `flutter build web --release --verbose --web-renderer canvaskit` fixed all the issues!**

The site says, "The CanvasKit renderer is fully consistent with Flutter mobile and desktop, has faster performance with higher widget density, but adds about 2 MB in download size.", so I'm in! Is there no other trade-off?

I was experiencing some other issues with other widgets as I continued to develop the app:
![Screenshot_2022-10-10-11-38-04-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/11029629/194849912-7b868757-4cff-4e64-8e01-c1b8e59df2fe.jpg)

This is its code:
```
        child: Stack(
          children: [
            widget.user.photoURL != null
                ? Positioned.fill(
                    child: CircleAvatar(
                    backgroundImage: Image.network(widget.user.photoURL!, fit: BoxFit.fill).image,
                  ))
                : Positioned.fill(child: Icon(Icons.person, color: Color(widget.user.colorSelected))),
            if (hovering) Positioned.fill(child: Icon(Icons.remove_circle_rounded, color: Theme.of(context).colorScheme.error)),
          ],
        )
```

Those were fully fixed, switching to the CanvasKit renderer as well.
![Screenshot_2022-10-10-11-49-54-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/11029629/194850064-b926950a-7bea-4ae3-9cee-afab5e054e42.jpg)

Comparing, I see that the weird issue that I had with some text looking kinda' funny has been fixed as well!

I haven't tried switching to `RadioListTile` tough. CanvasKit seems to be the path I want to take, since it also seems to provide me more "liberty" and apparently less "headaches".

Is there any plan to fix this issue with html renderer? I do not know if it is worth it... 

.

**Comment by huycozy** [comment] 2022-10-11 02:31
@guplem 
I see there's an open issue addressing the case you described #76879 (HTML renderer issue) (let's see demo in https://github.com/flutter/flutter/issues/76879#issuecomment-1230918240)

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2022-10-11 02:31 UTC
Labels: in triage
