### ISSUE TITLE
[flutter_markdown]: Some badges cannot be rendered

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#81719] opened 2021-04-20 12:51 UTC
Some badges and the `img` tag cannot be rendered correctly.

[README](https://raw.githubusercontent.com/realkimmy/realkimmy/master/README.md)

**Comment by danagbemava-nc** [comment] 2021-09-03 10:55
Hi @realkimmy, can you please confirm if you're still experiencing this issue? 

And if you are, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by realkimmy** [comment] 2021-09-21 09:18
<img src="https://raw.githubusercontent.com/realkimmy/realkimmy/master/Hi.gif" width="30px" />

**Comment by danagbemava-nc** [comment] 2021-09-21 11:19
Hi @realkimmy, according to https://github.com/flutter/flutter/issues/87857#issuecomment-897967883 this should be expected.

Since that issue also describes a situation similar to yours, I'm going to close this as a duplicate. 

Feel free to follow up over there. 

Thank you

**Closed** 2021-09-21 11:19 UTC
Labels: package, p: flutter_markdown
