### ISSUE TITLE
[InteractiveViewer] Hard to scale when two fingers tap down at the same time

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#63320] opened 2020-08-09 06:37 UTC
## Steps to Reproduce

Comes from https://github.com/justinmc/flutter-go/issues/5 . Using the demo provided by @justinmc or write a interactive widget by myself.

## Logs
flutter doctor:
<details>
    <summary>logs</summary>

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-10 15:16
Hi @AlexV525 
Could you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates this behavior? Justin's repo contains a lot of ancillary code. It would also be helpful if you could describe the expected behavior vs actual behavior and clarify what device you tested this on.
Thank you

**Comment by HansMuller** [comment] 2020-08-10 15:20
CC @justinmc

**Comment by AlexV525** [comment] 2020-08-10 15:37
> Could you provide a minimal reproducible code sample

Sure. And I forgot to record a GIF for this issue. I'll add them tomorrow.

**Comment by AlexV525** [comment] 2020-08-11 02:12
I made a minimum demo from justin's. https://gist.github.com/AlexV525/8d0a14b9b489548f833c2ad296ba9619 (It can run directly from the dartpad but maybe it's not the same behavior on the FFW).

Also a GIF to tell how hard the scale is. It's too large so I put it on my server. http://www.alexv525.com/Kapture%202020-08-11-10-03-22.gif

**Comment by AlexV525** [comment] 2020-08-11 02:25
I noticed that `Stack` might prevent pointer events, but I tried again within the constrained size, and it seems not related.

**Comment by markusaksli-nc** [comment] 2020-08-11 09:44
I can repro this on both a physical device when tapping at different times(SM G950F) 

<img src="https://user-images.githubusercontent.com/68219924/89882547-a8819800-dbcf-11ea-9abd-bc4c766453c6.gif" height="400" />

and an Android 11 emulator when tapping at the same time.

<img src="https://i.gyazo.com/d25d5d5597a4b789455ff0a7cbac9439.gif" height="400" />

Labeling as reproducible on the latest master `1.21.0-8.0.pre.140`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.140, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.140 at C:\Development\flutter_master
    • Framework revision c8d051295a (5 hours ago), 2020-08-11 00:26:02 -0400
    • Engine revision a62703778b
    • Dart version 2.10.0 (build 2.10.0-5.0.dev e2a67723ca)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-08-11 10:08
Actually this just is a duplicate of https://github.com/flutter/flutter/issues/63006. Closing to track it there.

**Closed by markusaksli-nc** 2020-08-11 10:08 UTC
Labels: a: fidelity, f: gestures, f: material design, found in release: 1.21, framework, has reproducible steps
