### ISSUE TITLE
[tool_crash] ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. Command: C:\Users\ASUS\dev\flutter\bin\cache\dart-sdk\bin\dart.exe, OS error code: 225

### ISSUE THREAD

**Issue by IndraW02** [flutter/flutter#104143] opened 2022-05-19 05:04 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
 Command: C:\Users\ASUS\dev\flutter\bin\cache\dart-sdk\bin\dart.exe, OS error code: 225
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:793:37)
#7      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:679:14)
#8      _RecompileRequest._run (package:flutter_tools/src/compile.dart:379:16)
#9      _CompilationRequest.run (package:flutter_tools/src/compile.dart:355:30)
#10     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:716:23)
#11     _rootRunUnary (dart:async/zone.dart:1434:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#18     _rootRun (dart:async/zone.dart:1418:47)
#19     _CustomZone.run (dart:async/zone.dart:1328:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#22     _rootRun (dart:async/zone.dart:1426:13)
#23     _CustomZone.run (dart:async/zone.dart:1328:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
```
```
[✓] Flutter (Channel dev, 2.13.0-0.2.pre, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
    • Flutter version 2.13.0-0.2.pre at C:\Users\ASUS\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8662e22bac (4 weeks ago), 2022-04-20 08:21:52 -0700
    • Engine revision 24a02fa5ee
    • Dart version 2.17.0 (build 2.17.0-266.5.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 101.0.1210.47

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: f994b769743368b36b9c03fb359f62230b60ab92
### Plugins
android_intent-0.3.7+3
barcode_scan-2.0.2
flutter_plugin_android_lifecycle-2.0.6
geolocator-5.3.2+2
google_api_availability-2.0.4
local_auth-1.1.11
location_permissions-3.0.0+1
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
permission_handler-8.3.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.2+1
trust_location-2.0.13

**Comment by danagbemava-nc** [comment] 2022-05-19 08:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/61997. Kindly see the linked issue for some workarounds. 

Thank you

**Closed by danagbemava-nc** 2022-05-19 08:59 UTC
Labels: in triage
