### ISSUE TITLE
Freebsd support

### ISSUE THREAD

**Issue by dimstr** [flutter/flutter#97125] opened 2022-01-24 10:06 UTC
How can I run my flutter app on the FreeBsd?

**Comment by danagbemava-nc** [comment] 2022-01-24 11:38
The dart VM doesn't have support for this at the moment. See https://github.com/dart-lang/sdk/issues/10260. 

Closing as duplicate of https://github.com/dart-lang/sdk/issues/10260.

**Closed by danagbemava-nc** 2022-01-24 11:38 UTC
Labels: in triage
