### ISSUE TITLE
Flutter 2.5 Scrolling Bug with PageView

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#89674] opened 2021-09-08 18:39 UTC
When a pageview is use inside a scrolling widget, I'm not able to scroll horizontally with the page view.

**Only in Flutter Web**

## Steps to Reproduce

<details>
<summary>code sample</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: SingleChildScrollView(
          child: SizedBox(
            height: 200,
            child: PageView.builder(
              itemBuilder: (context, index) => Container(
                child: Text('$index'),
                color: (index == 0) ? Colors.red : Colors.blue,
              ),
              itemCount: 2,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Expected results:** 
Be able to change page when dragging the page.
It works for mobile but **not on the web**.

**Actual results:** 
Nothing happen, no error, no log
<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [version 10.0.19043.1202], locale fr-CA)
    • Flutter version 2.5.0 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (13 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
```

</details>

**Comment by iandis** [comment] 2021-09-08 21:54
This bug apparently occurs on `ListView` too when `scrollDirection` is set to `Axis.horizontal`.

**Comment by danagbemava-nc** [comment] 2021-09-09 06:54
Hi @wer-mathurin as per [this comment](https://github.com/flutter/flutter/issues/88910#issuecomment-911787859), a breaking change was made with regards to the behaviour on desktop. Can you follow the link the comment and see if the fix works for you? 

Thank you

**Comment by exitist** [comment] 2021-09-09 08:23
i've updated to 2.5.0 stable this morning and faced scrolling issue on desktop debug build..
The issue is very clear. Scrolling just doesn't work at all. Tested on m1 macbook air Big Sur 11.5.2. Is it my own problem? I got no way to figure out. I downgraded to 2.2.3 stable, and all the things work perfect now [:
No single error or message in console. No single one, just don't work both horizontal and vertical scroll. Hope this comment reach to the team! [:

**Comment by danagbemava-nc** [comment] 2021-09-09 08:28
@exitist as I stated in my comment above, there is a breaking change in the behaviour of scrollables on desktop. Kindly follow the directions in the link below and see if it fixes your issue. Thank you

https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag

**Comment by iandis** [comment] 2021-09-09 17:03
@danagbemava-nc you're right, it's a breaking change scrollables behaviour on desktop. when I tried running the web on mobile, the dragging feature comes back. However I spotted weird logs when using nested scrollables. Here's a sample code of my app
```dart
PageView(
  controller: _pageController,
  onPageChanged: _onPageChanged,
  children: [
     CustomScrollView(
        slivers: [
           SliverToBoxAdapter(ListView), // horizontal
           SliverToBoxAdapter(ListView), // horizontal
           SliverToBoxAdapter(ListView), // horizontal
         ],
      ),
      CustomScrollView(
         slivers: [
            SliverToBoxAdapter(ListView), // horizontal
            SliverToBoxAdapter(ListView), // horizontal
         ],
      ),
...
```
Now say I'm on the first page of the `PageView`, it works normally. But when moving to the next page and scroll the page, here's the log
```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:40789/_TSo5xl7SPE%3D/ws
Debug service listening on ws://127.0.0.1:40789/_TSo5xl7SPE=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:40789/_TSo5xl7SPE=/ws
[log] _TransformedPointerDownEvent#285cc(position: Offset(476.0, 923.0))

════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/flutter/src/widgets/scrollbar.dart 1315:9                                <fn>
packages/flutter/src/widgets/scrollbar.dart 1338:14                               [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1257:14                               [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                       notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 814:7                    [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 748:5                    [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 611:12                   [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 462:12                   forward
packages/flutter/src/widgets/scrollbar.dart 1567:46                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 206:27                    [_dispatch]
packages/flutter/src/widgets/notification_listener.dart 122:19                    visitAncestor
packages/flutter/src/widgets/scroll_notification.dart 31:18                       visitAncestor
packages/flutter/src/widgets/framework.dart 4133:39                               visitAncestorElements
packages/flutter/src/widgets/notification_listener.dart 138:13                    dispatch
packages/flutter/src/widgets/scroll_activity.dart 94:90                           dispatchScrollUpdateNotification
packages/flutter/src/widgets/scroll_position.dart 899:5                           didUpdateScrollPositionBy
packages/flutter/src/widgets/scroll_position_with_single_context.dart 221:7       pointerScroll
packages/flutter/src/widgets/scrollable.dart 718:16                               [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 199:7                  resolve
packages/flutter/src/gestures/binding.dart 446:29                                 handleEvent
packages/flutter/src/gestures/binding.dart 420:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 278:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                 [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1018:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 182:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 307:14                                    [_handleWheelEvent]
lib/_engine/engine/pointer_binding.dart 571:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 288:87                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
The AnimationController notifying status listeners was: AnimationController#e29ad(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The provided ScrollController is currently attached to more than one ScrollPosition.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The provided ScrollController is currently attached to more than one ScrollPosition.
════════════════════════════════════════════════════════════════════════════════
```
To prevent these logs showing up, I decided to add `ScrollController` to each `CustomScrollView`s. Nonetheless, the app runs normally. I just have no idea what actually causes the error logs showing up.

**Comment by wer-mathurin** [comment] 2021-09-09 17:38
On my side after applying the general guidance of the migration guide, everything run as before.   Since @iandis have a different bug.  Maybe this can be a better idea to create it own bug to track it properly?

**Comment by danagbemava-nc** [comment] 2021-09-10 06:01
@wer-mathurin, you're right. 

@iandis since you seem to be experiencing a different issue, kindly open a new issue and feel free to tag me. 

Closing based on [this comment](https://github.com/flutter/flutter/issues/89674#issuecomment-916302961)

**Closed by danagbemava-nc** 2021-09-10 06:01 UTC
Labels: in triage
