### ISSUE TITLE
Relax type annotation requirement for literals and constructor initialization

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3872] opened 2016-05-11 22:08 UTC
In cases when a variable is initialized using a literal (`String`, `int`, `bool`, `double`, `List`, `Map`) or a constructor initialization type annotations do not contribute to type safety, but have net negative effect on code readability:

```dart
String greeting = 'Hello, World!';
double d = 4.5;
MyAwesomeWidget widget = new MyAwesomeWidget();
final Map<String, List<int>> measurements = <String, List<int>>{};
```

The following has as much type safety but better readability:

```dart
var greeting = 'Hello, World!';
var d = 4.5;
var widget = new MyAwesomeWidget();
final measurements = <String, List<int>>{};
```

Type annotations still contribute to type safety when the initializing expression is missing (i.e. `null`) or is non-trivial:

```dart
String greeting;
String greeting = null;
String greeting = condition ? hello : goodbye;
String greeting = fetchGreeting();
```

**Comment by sethladd** [comment] 2016-05-11 23:56
Using a type annotation can prevent an incorrect reassignment.

![screen shot 2016-05-11 at 4 56 30 pm](https://cloud.githubusercontent.com/assets/5479/15200180/571a2f4e-1799-11e6-9484-31ddbe18ab87.png)

**Comment by yjbanov** [comment] 2016-05-12 00:34
@sethladd I believe strong mode will not allow that. In strong mode you have to be `dynamic` to be able to do that.

**Comment by yjbanov** [comment] 2016-05-12 00:36
Also, generally, I'd prefer using `final` as a variable's value rarely changes in practice. Today, with having to annotate the type, I am punished for using `final` (see the `measurements` example above).

**Comment by sethladd** [comment] 2016-05-12 00:36
Nice. Confirmed! (and I learned that DartPad now has a Strong Mode checkbox)

![screen shot 2016-05-11 at 5 36 52 pm](https://cloud.githubusercontent.com/assets/5479/15200798/f53e4f34-179e-11e6-9125-916e930f6b14.png)

**Comment by abarth** [comment] 2016-05-12 02:24
@Hixie , grand arbiter of Flutter style.

**Comment by jimbeveridge** [comment] 2016-05-12 21:49
+1. We stopped duplicating the variable type last summer for `final` variables (but not for `var` variables.) I'm not aware of any problems this has caused now that the analyzer issues have been resolved.

**Comment by Hixie** [comment] 2016-05-12 23:52
I think having types everywhere is a simple rule. Simple rules lead to better habits and thus more efficient development because you don't have to think about it.

It also makes maintenance easier. For example:

```dart
   // day 1
   var greeting = 'Hello';

   // day 2, let's move that into a function:
   var greeting = getGreeting(); // oops, now we have to give the type.
```

Having types sometimes be on the left and sometimes be on the right makes the code harder to read:

```dart
  String greeting = getGreeting();
  var greetings = <String>['hi', 'hello'];
```

Several aspects of our style are explicitly about being able to scan code by just reading the left edge. You can tell where blocks and expressions begin and end, you can tell the types of all the variables, etc, all by just scanning the left edge. "var" works against this, because now you sometimes have to go to the right to see what types are around. In the example above, scanning just the left edge you might be left with the impression that there's a String and some cheap variable, as opposed to a String and a potentially quite expensive Map.

It also makes code annoying inconsistent. For example:
```dart
String greeting1;
String greeting2 = condition ? hello : goodbye;
var greeting3 = 'Hello';
String greeting4 = fetchGreeting();
```

It doesn't work for int and double literals because the literal isn't enough information to be able to tell if the variable should be "int", "double", or "num". (We don't want to have to use `num` because we want to avoid polymorphic call sites.)

It also won't work once we have union types, for similar reasons.

Once we have a formatter, we can make the formatter turn `var` into explicit types for you, so if you really want to avoid giving types while coding, we should probably just go down that route. That way you don't have to worry about it when coding, but the code itself still has all the readability benefits.

Now on the other hand what would be really good would be if the compiler could do the opposite: enforce a declared type on a literal. For example, if I say:

```dart
   final Map<Metric, double> measurements = {};
```

...then the compiler should force the created map to be a `Map<Metric, double>` rather than a `Map<dynamic, dynamic>`. (You should still be able to force it to the latter explicitly, of course.) This would solve a whole bunch of problems at once, for example, it would allow:

```dart
   double x = 0;
```

Note that our style guide only really applies to people working on Flutter framework code. Flutter consumers can have their own style.

**Comment by yjbanov** [comment] 2016-05-13 00:45
> It also makes maintenance easier.
> Once we have a formatter, we can make the formatter turn var into explicit types for you, so if you really want to avoid giving types...

The problem is not having to type. I believe code size is second to readability. Readability contributes to maintainability more than conciseness. So I would actually _not_ want the formatter to do the conversion.

> Having types sometimes be on the left and sometimes be on the right makes the code harder to read

I agree that this is a tradeoff, but a tiny one. I've seen a lot of code that mixes types with `var` and it has yet to become an issue, other than when the expression type is not obvious, which is addressed by this proposal. The only issue was that you used to lose type safety in the pre-strong mode world. Today, that issue has been eliminated.

> able to scan code by just reading the left edge

What good are types without knowing what variables they are attached to? I would actually prefer type annotations on the right, because the variable's name and location are more important than its type. In fact, types on the left obscure variable declarations because the variable names are not aligned.

> It also makes code annoying inconsistent

Not necessarily. The proposed rules is not to enforce `var`, but to make types optional. In your example it would be better to annotate `greeting3` for consistency with the adjacent strings. Also, series of local variable declarations like that are rare compared to stand-alone local declarations. That mostly happens for field declarations, which are untouched by this proposal.

> literal isn't enough information to be able to tell if the variable should be "int", "double", or "num"

It is. Every literal has a concrete type (`1` is always `int`, `1.2` is always `double`), and if you want to pass an `int` or a `double` as a `num`, both are Liskov-substitutable. Additionally, strong mode ensures that you cannot assign a `double` to an `int` even if that `int` is declared using `var` ([check this out](https://dartpad.dartlang.org/601570579766a9dd5561c3f7606d7cf2) - you'll have to click the bottom-right "Strong mode" box).

> would be really good [...] if the compiler [...] enforce[d] a declared type on a literal

Having some responsible level of type coercion would be great, but not for your example. In your example you could have the literal express both the value and the type in one go. Type coercion is interesting in other areas, such as instantiating a custom implementation of `Map` using a plain map literal, but that's beyond the scope of this issue.

> I think having types everywhere is a simple rule.

True, but in this case the tradeoff is too big for me. This rule would be much simpler than, say, the collection of rules we have for braces:

* [braces for long functions/methods](https://github.com/flutter/website/blob/master/style-guide.md#use-braces-for-long-functions-and-methods)
* [no braces for one line long statements](https://github.com/flutter/website/blob/master/style-guide.md#avoid-using-braces-for-one-line-long-control-structure-statements)
* [extra rule when no braces used](https://github.com/flutter/website/blob/master/style-guide.md#separate-the-if-expression-from-its-statement)
* [braces for map literals](https://github.com/flutter/website/blob/master/style-guide.md#use-braces-for-long-functions-and-methods)

**Comment by Hixie** [comment] 2016-05-13 07:10
I fundamentally disagree that omitting the types makes it more readable. Anything that requires that the reader think about what's going on by definition is harder to read than something that's obvious. `var` by definition means you have to think about what's going on compared to having an explicit type.

I read Dart code that uses `var` all the time (e.g. a lot of the Dart core libraries and libraries that we depend on like `test`) and I find it _significantly_ harder to read than if the types are explicit.

The type is the most important part of the variable when what you're trying to do is understand what's fundamentally going on. It's critical that you see whether this or that variable is an integer, likely to be a smi, vs a String, vs a List of ints, vs a List of Maps of giant Elements or whatnot. You need the types to be able to reason about the likely performance of the function. If you scan the left edge of a function and you see only ints and ifs, then you know that you likely don't have any loops (maybe recursion), and that you likely don't have to worry about O(N^2) algorithms, and that you probably are using trivial amounts of memory. If you see that all the types are RenderObjects then you know that even if the function is short, you still need to check what calls it's making, and you know that you'll likely have to deal with lots of memory usage. If you see Lists around, you know that you should be wary of O(N) calls to, e.g., `single`, and depending on the type, you might determine that the memory usage is likely to be comparatively gigantic. If you see Maps around you know you have to be wary of people indexing into the map multiple times for the same key when they could be caching the value, and that you've essentially given up trying to keep things small. You can tell a whole lot just by scanning the left edge and seeing what types are around.

Variable names mean nothing when you're scanning thousands of lines of code. It's only when you're actually in the function editing it that you need worry about the actual _names_ of the variables. Flutter's framework at this point is tens of thousands of lines of code. Scanning through the code is something everyone on the team should be doing regularly to get a feel for what the framework's footprint and structure are. You just can't sensibly do that if scanning through files requires jumping back and forth between type declarations, literals in assignments, etc.

Regarding some of your other points:

* Our rules are intended to remove doubt in how to write the code. As such. we shouldn't leave things optional. Whatever rule we want, it should be clear cut for every case what the code should look like, such that a formatter can make that call automatically. The proposed rule does not lend itself well to this, since it would be context sensitive and in some cases would require judgement about what is more readable.

* For the num/int/double case, `var` introduces inconsistency in that if you want an `int`-typed variable, you can use `var`, but if you want a `num`-typed variable, you can't. It's even worse with things like `RenderBox` vs `RenderClip`, where you often want the variable to be the less tight type, but basing it on literals would give you the tightest type. This essentially forces the rule to be more complex -- use `var` unless you somehow know the type you'd get isn't the right one -- which leads to even less consistent code.

* I don't understand why you think having the literal's type determined from the variable's type would be worse than having the variable's type determined from the literal.

(I don't really see what you mean about the braces. Those all basically boil down to two rules: use braces for blocks, not statements or expressions; and distinguish empty blocks from empty maps. Even if they were complex rules, the existence of complex rules is an argument in favour of fixing _those_ rules, not introducing more complexity. The "it's not worse than what we have already" maxim, due to the error on measuring how bad things are, over time leads to worsening of the average. The "is it the best we can do" maxim is how we get improvement over time.)

**Comment by yjbanov** [comment] 2016-05-13 16:00
Since this is not about type safety, but personal preferences, I'd be ok with closing this. However, there are 4 people in favor of this proposal, so I'm hesitating.

**Comment by Hixie** [comment] 2016-05-20 22:04
Closing this for now. If we can get the VM to imply types from the declaration (LHS) to the definition (RHS) then I think we should consider removing the requirements on types on the definition. The left hand side needs to be explicit to enable code scanning, though, as described above.

**Closed by Hixie** 2016-05-20 22:04 UTC
Labels: affects: dev experience
