### ISSUE TITLE
[Flutter Web] The cursor in TextField is dropped to next line on macOS.

### ISSUE THREAD

**Issue by namel3ssguy** [flutter/flutter#151388] opened 2024-07-08 00:01 UTC
### Steps to reproduce

1. Create a Flutter Web project on macOS.
2. Add a TextField like this one: `TextField(maxLines: 5)`
3. Change Input Source on to Japanese or Vietnamese.
4. Type the some text. 

### Expected results

The cursor should be at the end of the text.

### Actual results

The cursor is dropped to next line.

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(maxLines: 5)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="1624" alt="Screenshot 2024-07-03 at 20 02 55" src="https://github.com/flutter/flutter/assets/9659760/d98dfa63-dc74-4857-9745-9a44c8987e1a">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/minhnguyen/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/minhnguyen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Minh’s iPhone (mobile)          • 00008101-000261E618782C3A            • ios            • iOS 17.5.1 21F90
    • iPhone 15 (mobile)              • 5BA3DEE4-36EC-4BE7-87C1-84D67CFDF837 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2024-07-08 09:38
Hi @namel3ssguy 
I checked this issue on my end with Chrome browser on macOS but couldn't see this issue. Instead, I see another issue (the highlighted blue underline and the suggestion list are rendering at wrong position). This seems to be a side-effect issue of https://github.com/flutter/flutter/issues/151097, I reported it at https://github.com/flutter/flutter/issues/151097#issuecomment-2213519003)
 
![Screenshot 2024-07-08 at 16 23 37](https://github.com/flutter/flutter/assets/104349824/a96c5782-8ad7-4d31-8d65-94a070d8fe76)

I don't see the suggestion list on your screenshot compared to your demo. I typed the same text but the suggestion list appears on my end. Could you share the text you typed step-by-step?

**Comment by namel3ssguy** [comment] 2024-07-08 15:06
Hi @huycozy,

> I don't see the suggestion list on your screenshot compared to your demo. I typed the same text but the suggestion list appears on my end. Could you share the text you typed step-by-step?

I didn't do anything particularly. You can create a new flutter web project, add a TextField as I described. Maybe it just doesn't occur on your mac.

> Also, are you building/running web in html renderer? If it's, there is a similar issue https://github.com/flutter/flutter/issues/148271.

Yes, I build the web in html renderer. The issue is similar, the difference is the cursor is dropped to next line on my mac. Do we intend to fix the issue you mentioned?

**Comment by huycozy** [comment] 2024-07-09 04:00
>Yes, I build the web in html renderer. The issue is similar, the difference is the cursor is dropped to next line on my mac. 

https://github.com/flutter/flutter/issues/148271 is the same issue, you can look into its demo video at the first comment and see the cursor also is dropped to the next line. Closing this as a duplicate of that issue, please follow it for updates. 

>Do we intend to fix the issue you mentioned?

That issue has been prioritized as `P3`, please see [Priorities](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#priorities).

**Closed by huycozy** 2024-07-09 04:00 UTC
Labels: in triage
