### ISSUE TITLE
crash when run flutter_view example 

### ISSUE THREAD

**Issue by guogailee** [flutter/flutter#10198] opened 2017-05-19 08:13 UTC
`

## command

flutter run

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xc3 (at offset 130)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:486)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:96)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#11     _StreamController._add (dart:async/stream_controller.dart:628)
#12     _StreamController.add (dart:async/stream_controller.dart:574)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#14     _rootRunUnary (dart:async/zone.dart:1132)
#15     _CustomZone.runUnary (dart:async/zone.dart:1012)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:757)
#20     _StreamController._add (dart:async/stream_controller.dart:628)
#21     _StreamController.add (dart:async/stream_controller.dart:574)
#22     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.14393], channel alpha)
    • Flutter at C:\e_code\flutter\flutter
    • Framework revision dc4ca8db83 (7 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\e_code\android_sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\e_code\android_ide\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\e_code\android_ide
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[-] IntelliJ IDEA Ultimate Edition (version 15)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • MX4 • 75UBBKS228QC • android-arm • Android 5.1 (API 22)

```
`

**Comment by mravn-google** [comment] 2017-05-19 08:33
Does this error happen for `flutter_view` only?

**Comment by guogailee** [comment] 2017-05-19 08:40
yes.Others work good,except the layers example,because there is not "lib\main.dart".In fact,i am interested in  how to  architect an app with flutter.

**Comment by guogailee** [comment] 2017-05-19 08:40
@mravn-google

**Comment by mravn-google** [comment] 2017-05-19 09:00
Was a flutter log file created in the `flutter_view` folder? If so, please include that file in this issue.

FYI: the `layers` example is a bit different in that there are multiple targets for your `flutter run` command, like
```
flutter run -t widgets/hello_world.dart
flutter run -t raw/spinning_square.dart
```
`flutter run` is basically a synonym for `flutter run -t lib/main.dart`

**Comment by guogailee** [comment] 2017-05-19 09:36
@mravn-google 
[flutter_01.txt](https://github.com/flutter/flutter/files/1013735/flutter_01.txt)
thx for the command explain.

**Comment by mit-mit** [comment] 2017-06-08 16:29
Looks like a dupe of https://github.com/flutter/flutter/issues/7779; closing

**Closed by mit-mit** 2017-06-08 16:29 UTC

**Comment by NawazS** [comment] 2019-01-27 07:49
I had the same problem. Using ENG-UK windows.

Changing my project encoding to UTF-8 also fixed the problem.

File -> Other Settings -> Settings For New Project, then find "File Encodings", change Project Encoding to UTF-8.
