### ISSUE TITLE
Failed assertion: line 935 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.

### ISSUE THREAD

**Issue by harsh47sharma** [flutter/flutter#70281] opened 2020-11-11 09:37 UTC
I'm trying to add textstyle to selected day of the week but it throws this error:

```
The following assertion was thrown building AnimatedDefaultTextStyle(duration: 200ms, inherit: true, color: MaterialColor(primary value: Color(0xfff44336)), weight: 700, softWrap: wrapping at box width, overflow: clip, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedDefaultTextStyleState#869ff(ticker active)):
'package:flutter/src/painting/text_style.dart': Failed assertion: line 935 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  WeekdaySelector file:///C:/Flutter/apps/connected_society/connected_society/lib/createevents/createclass.dart:696:20
When the exception was thrown, this was the stack: 
#2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:935:12)
#3      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:218:41)
#4      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#5      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#6      _AnimatedDefaultTextStyleState.build (package:flutter/src/widgets/implicit_animations.dart:1651:21)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/painting/text_style.dart': Failed assertion: line 935 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.
The relevant error-causing widget was: 
  WeekdaySelector file:///C:/Flutter/apps/connected_society/connected_society/lib/createevents/createclass.dart:696:20
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15706): aa0

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building AnimatedDefaultTextStyle(duration: 200ms, inherit: true, color: MaterialColor(primary value: Color(0xfff44336)), weight: 700, softWrap: wrapping at box width, overflow: clip, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedDefaultTextStyleState#bf183(ticker active)):
'package:flutter/src/painting/text_style.dart': Failed assertion: line 935 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  WeekdaySelector file:///C:/Flutter/apps/connected_society/connected_society/lib/createevents/createclass.dart:696:20
When the exception was thrown, this was the stack: 
#2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:935:12)
#3      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:218:41)
#4      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#5      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#6      _AnimatedDefaultTextStyleState.build (package:flutter/src/widgets/implicit_animations.dart:1651:21)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/painting/text_style.dart': Failed assertion: line 935 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.
The relevant error-causing widget was: 
  WeekdaySelector file:///C:/Flutter/apps/connected_society/connected_society/lib/createevents/createclass.dart:696:20
════════════════════════
```

Here is my code: 

```
> WeekdaySelector(
>               selectedElevation: 4,
>               selectedTextStyle: TextStyle(
>                 color: Colors.red,
>                 fontWeight: FontWeight.bold),//**This is throwing error**
>               shortWeekdays: ["Sun", "Mon", "Tu", "Wed", "Thu", "Fri", "Sat"],
>               fillColor: Colors.grey.shade200,
>               selectedFillColor: Constants.themeRedColor,
>               onChanged: (int day) {
>                 setState(() {
>                   final index = day % 7;
>                   daysOfWeekList[index] = !daysOfWeekList[index];
>                 });
>               },
>               values: daysOfWeekList,
>             ),
```

**Comment by harsh47sharma** [comment] 2020-11-11 09:38
Thanks in advance!!

**Comment by pedromassangocode** [comment] 2020-11-11 09:49
Hi @harsh47sharma 
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
Thank you

**Comment by harsh47sharma** [comment] 2020-11-11 10:15
Hi, 
here is my flutter doctor -v: 
Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-IN)
    • Flutter version 1.22.2 at C:\Flutter\flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\harsh\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.50.0)
    • VS Code at C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.


Here is the reproducible code sample:

Please add weekday_selector: ^0.4.0 to your pubspec.yaml file.

import 'package:flutter/material.dart';
import 'package:weekday_selector/weekday_selector.dart';

class MyGroupsPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyGroupsPageState();
  }
}

class _MyGroupsPageState extends State<MyGroupsPage> {

  List<bool> daysOfWeekList = List<bool>();

  @override
  void initState() {
    super.initState();
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: ListView(
            children: [
              Container(
                child: WeekdaySelector(
                  selectedElevation: 4,
                  selectedTextStyle: TextStyle(
                      color: Colors.red,
                      fontWeight: FontWeight.bold),//This is throwing error
                  shortWeekdays: ["Sun", "Mon", "Tu", "Wed", "Thu", "Fri", "Sat"],
                  fillColor: Colors.grey.shade200,
                  selectedFillColor: Colors.red,
                  onChanged: (int day) {
                    setState(() {
                      final index = day % 7;
                      daysOfWeekList[index] = !daysOfWeekList[index];
                    });
                  },
                  values: daysOfWeekList,
                ),
              )
            ],
          )),
    );
  }
}

**Comment by pedromassangocode** [comment] 2020-11-11 10:59
Hi @harsh47sharma 
I need a minimal complete code that I can copy/paste and run it. The you provided does not compile to me.

**Comment by harsh47sharma** [comment] 2020-11-11 11:42
Hi @pedromassangocode ,
Sorry my bad. Here is the code you can run:

Before that please add  weekday_selector: ^0.4.0 to your pubspec.yaml file


import 'package:flutter/material.dart';
import 'package:weekday_selector/weekday_selector.dart';

class MyGroupsPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyGroupsPageState();
  }
}

class _MyGroupsPageState extends State<MyGroupsPage> {
     
  List<bool> daysOfWeekList = List<bool>();

  @override
  void initState() {
    super.initState();
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: ListView(
            children: [
              Container(
                child: WeekdaySelector(
                  selectedElevation: 4,
                  selectedTextStyle: TextStyle(
                      color: Colors.red,
                      fontWeight: FontWeight.bold),//This is throwing error
                  shortWeekdays: ["Sun", "Mon", "Tu", "Wed", "Thu", "Fri", "Sat"],
                  fillColor: Colors.grey.shade200,
                  selectedFillColor: Colors.red,
                  onChanged: (int day) {
                    setState(() {
                      final index = day % 7;
                      daysOfWeekList[index] = !daysOfWeekList[index];
                    });
                  },
                  values: daysOfWeekList,
                ),
              )
            ],
          )),
    );
  }
}

**Comment by pedromassangocode** [comment] 2020-11-11 14:29
Hi @harsh47sharma 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/smaho-engineering/weekday_selector).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by maheshmnj** [comment] 2022-05-18 05:32
This is reproducible on stable and the master channel using the third party plugin `weekday_selector` but the error logs seems to point issue in the framework

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:weekday_selector/weekday_selector.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyGroupsPage(),
    );
  }
}

class MyGroupsPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyGroupsPageState();
  }
}

class _MyGroupsPageState extends State<MyGroupsPage> {
  List<bool> daysOfWeekList = <bool>[];

  @override
  void initState() {
    super.initState();
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
    daysOfWeekList.add(false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: ListView(
        children: [
          Container(
            child: WeekdaySelector(
              selectedElevation: 4,
              selectedTextStyle: TextStyle(
                  color: Colors.red,
                  fontWeight: FontWeight.bold), //This is throwing error
              shortWeekdays: ["Sun", "Mon", "Tu", "Wed", "Thu", "Fri", "Sat"],
              fillColor: Colors.grey.shade200,
              selectedFillColor: Colors.red,
              onChanged: (int day) {
                setState(() {
                  final index = day % 7;
                  daysOfWeekList[index] = !daysOfWeekList[index];
                });
              },
              values: daysOfWeekList,
            ),
          )
        ],
      )),
    );
  }
}

```
</details> 

<details>
<summary>logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
objc[1684]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x219aee098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046942c8). One of the two will be used. Which one is undefined.
objc[1684]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x219aee0e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104694318). One of the two will be used. Which one is undefined.
objc[1684]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x219aedeb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046944f8). One of the two will be used. Which one is undefined.
objc[1684]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x219aedf00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104694548). One of the two will be used. Which one is undefined.
objc[1684]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x219aedf50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104694598). One of the two will be used. Which one is undefined.
objc[1684]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x219aedfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1046945e8). One of the two will be used. Which one is undefined.
objc[1684]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x219aedff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104694638). One of the two will be used. Which one is undefined.
objc[1684]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x219aee040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104694688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0019553C36F2001E }
{ platform:macOS, arch:x86_64, id:00008103-0019553C36F2001E }
Connecting to VM Service at ws://127.0.0.1:49825/DB51TKjosfA=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building AnimatedDefaultTextStyle(duration: 200ms, inherit: true, color: MaterialColor(primary value: Color(0xfff44336)), weight: 700, softWrap: wrapping at box width, overflow: clip, dirty, state: _AnimatedDefaultTextStyleState#658fd(ticker active)):
'package:flutter/src/painting/text_style.dart': Failed assertion: line 1070 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
WeekdaySelector
When the exception was thrown, this was the stack
#2      TextStyle.lerp
#3      TextStyleTween.lerp
#4      Tween.transform
#5      Animatable.evaluate
#6      _AnimatedDefaultTextStyleState.build
#7      StatefulElement.build
#8      ComponentElement.performRebuild
#9      StatefulElement.performRebuild
#10     Element.rebuild
#11     BuildOwner.buildScope
#12     WidgetsBinding.drawFrame
#13     RendererBinding._handlePersistentFrameCallback
#14     SchedulerBinding._invokeFrameCallback
#15     SchedulerBinding.handleDrawFrame
#16     SchedulerBinding._handleDrawFrame
#17     _invoke (dart:ui/hooks.dart:148:13)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#19     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
    • Flutter version 3.1.0-0.0.pre.419 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2eed8cbf93 (2 weeks ago), 2022-04-28 22:29:06 -0400
    • Engine revision dfdfe0b3b0
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by LongCatIsLooong** [comment] 2022-10-03 20:27
Closing this in favor of https://github.com/flutter/flutter/issues/43358

**Closed by LongCatIsLooong** 2022-10-03 20:27 UTC
Labels: framework, a: error message, p: third party, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
