### ISSUE TITLE
GPU Hang Error using Impeller on iPads with iPadOS 16

### ISSUE THREAD

**Issue by ronjb** [flutter/flutter#153574] opened 2024-08-16 15:57 UTC
### Steps to reproduce

We can reliably reproduce the bug in our app in a number of different ways, usually related to showing a dialog or sheet. I've tried to create a sample app that exhibits the same problem, but haven't been successful so far.

In our app we only see the problem on iPads (various models) with iPadOS 16. We have not been able to reproduce the problem on iPads with iOS 15 or iOS 17.

It also only happens in release (and profile builds), and only if Impeller is turned on.

Once the GPU Hang Error occurs the app is in a state that cannot recover. The screen may still be flickering, but the app is unresponsive.

### Expected results

Expected the app to work without GPU Hang Errors.

### Actual results

I explained this in the Steps to Reproduce section.

### Code sample

<details open><summary>Code sample</summary>

```dart
// Sorry have not been able to create sample code with reproducible steps.
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/97f119ce-3f14-4ee4-8c43-74613a94d2e2

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPad Pro (9.7-inch) in profile mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 6MDE8399G4
Xcode build done.                                           330.2s
(lldb) 2024-08-16 09:19:10.082504-0600 LifeBible[1000:126893]  - <AppMeasurement>[I-ACS036001] Analytics screen reporting is disabled. UIViewController transitions will not be logged.
10.29.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
<SKPaymentQueue: 0x281b01f50>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
10.29.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
10.29.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.29.0 started
10.29.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Crashlytics] Version 10.29.0
AllFilesDownloadedMessage: All files have been downloaded
SKAdNetwork: Error while updating conversion value: Error Domain=SKANErrorDomain Code=10 "(null)"
[catalog] Unable to list voice folder
[catalog] Unable to list voice folder
[catalog] Unable to list voice folder
flutter: Running on iPad Pro (9.7 inch, WiFi) with IOS 16.7.10, deviceUid: iPad6,3-m4n3b3gyurrkebow
10.29.0 - [FirebaseInAppMessaging][I-IAM180004] Runtime is already active, resume is just a no-op
<Warning>: The value for FacebookAdvertiserIDCollectionEnabled is currently set to FALSE so you're sending app events without collecting Advertiser ID. This can affect the quality of your advertising and analytics results.
[Default] Error enumerating unfinished transactions for first transaction listener: Error Domain=ASDErrorDomain Code=509 "No active account" UserInfo={NSLocalizedDescription=No active account}
[Default] Error enumerating unfinished transactions: Error Domain=ASDErrorDomain Code=509 "No active account" UserInfo={NSLocalizedDescription=No active account}
[Default] Error enumerating unfinished transactions: Error Domain=ASDErrorDomain Code=509 "No active account" UserInfo={NSLocalizedDescription=No active account}
[tcp] tcp_input [C3.1.1:3] flags=[R] seq=2142595793, ack=0, win=0 state=CLOSED rcv_nxt=2142595793, snd_una=1526351081
[tcp] tcp_input [C3.1.1:3] flags=[R] seq=2142595793, ack=0, win=0 state=CLOSED rcv_nxt=2142595793, snd_una=1526351081
[tcp] tcp_input [C4.1.1:3] flags=[R] seq=102426126, ack=0, win=0 state=CLOSED rcv_nxt=102426126, snd_una=1347026923
[tcp] tcp_input [C4.1.1:3] flags=[R] seq=102426126, ack=0, win=0 state=CLOSED rcv_nxt=102426126, snd_una=1347026923
[tcp] tcp_output [C5.1.7:3] flags=[R.] seq=2238385353, ack=2352025247, win=3984 state=CLOSED rcv_nxt=2352025247, snd_una=2238385353
10.29.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
10.29.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
10.29.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
[tcp] tcp_input [C5.1.9:3] flags=[R] seq=1082911873, ack=0, win=0 state=LAST_ACK rcv_nxt=1082911873, snd_una=3170096304
[tcp] tcp_input [C5.1.9:3] flags=[R] seq=1082911873, ack=0, win=0 state=CLOSED rcv_nxt=1082911873, snd_una=3170096304
[tcp] tcp_input [C5.1.9:3] flags=[R] seq=1082911873, ack=0, win=0 state=CLOSED rcv_nxt=1082911873, snd_una=3170096304
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
+ 24,896 total before I killed the app

Application finished.

Exited.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/ronbooth/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ronbooth/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPad Pro (9.7-inch) (mobile)        • 094e82e131d5a9986b781a26021e01462fbaf5d6 • ios            • iOS 16.7.10
      20H350
    • iPad mini (6th generation) (mobile) • 83DEA262-C309-4387-B30F-47BA6D7C5184     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                    • darwin-arm64   • macOS 14.6.1
      23G93 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                    • darwin         • macOS 14.6.1
      23G93 darwin-arm64
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome
      127.0.6533.120
    ! Error: Browsing on the local area network for Test iPhone SE. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Ron’s iPad Pro. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Ron’s iPad mini. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2024-08-16 17:38
Is this happening with a platform view on the screen? If so it could be related to https://github.com/flutter/flutter/issues/153041 , which hasn't been cherry picked yet.

**Comment by ronjb** [comment] 2024-08-16 18:49
@jonahwilliams,

We do use a platform view (for a web browser) in one part of the app, but this issue happens without that part of the app ever being used.

If we could get to a branch with the fix, we'd be happy to test with it.

**Comment by ronjb** [comment] 2024-08-16 19:02
Looks like maybe Flutter stable 3.24.1 is close to release with the fix?
https://github.com/flutter/engine/commits/flutter-3.24-candidate.0/

**Comment by jonahwilliams** [comment] 2024-08-16 21:56
Great! It should be in the next hotfix release, though I don't know exactly when that goes out.

**Comment by jonahwilliams** [comment] 2024-08-16 23:44
Closing as duplicate of https://github.com/flutter/flutter/issues/153041

**Closed by jonahwilliams** 2024-08-16 23:44 UTC

**Comment by mtallenca** [comment] 2024-08-22 17:13
I'm working with @ronjb on this.  While master channel did resolve the issue, 3.24.1 does not.  We narrowed the commit in master that resolved the issue to [flutter/engine#54121](https://github.com/flutter/engine/pull/54121).  

If we set FLTUseFlutterMetalLayer to true in the plist using 3.24.1 the issues appears to be resolved. Is this flag safe to use in production?  I see that there is a commit - retain cycle in FlutterMetalLayer (https://github.com/flutter/engine/pull/54119) which is also not in 3.24.1

**Comment by jonahwilliams** [comment] 2024-08-22 17:38
The flag is not safe to use on 3.24 unless you have no platform views. The retain cycle will cause OOM

**Comment by mtallenca** [comment] 2024-08-22 17:42
Got it.  And (https://github.com/flutter/engine/pull/54119) fixes that.  Any chance that fix is added to 3.24.2 ?

**Comment by jonahwilliams** [comment] 2024-08-22 17:47
I don't like cherry picking feature changes. The fact that it fixes a bug for you is concerning, because it is almost certainly a bug we are not aware of.

Is there a chance for a minimal repro we could test with?

**Comment by mtallenca** [comment] 2024-08-22 18:02
Unfortunately - haven't been able to create a minimal repro.  Reminiscent of [flutter/engine#51855](https://github.com/flutter/engine/pull/51855).  Will post video of what we're seeing on an iPad mini 4 (iOS 15.8.3) and 
iPad Pro (32GB, Wi-Fi, 9.7in, iOS 16.8.10)

**Comment by mtallenca** [comment] 2024-08-22 18:24
iPad mini 4 - notice Genesis 1 at the top - navigate to another location via dialogs and the text in the pill is corrupted.  Going to device home and back to the app you'll see a repaint that is correct.  Same GPU hang logs... Then rebuilding with <key>FLTUseFlutterMetalLayer</key><true/> in info.plist, no text corruption:

https://github.com/user-attachments/assets/991010fd-7c81-41e1-882d-40cf5dfe7140

**Comment by joknjokn** [comment] 2024-09-02 15:35
We're seeing a lot of errors related to this in production (high percentage of our iOS users). It seems to be more frequent on older iPhones, and we can some times reproduce it manually on a physical iPhone 7. 

For us, it happens at app start (we run a Lottie loading animation), and the user is stuck. 

(We really hope this can get cherry picked and released very soon.)

**Comment by jonahwilliams** [comment] 2024-09-02 17:09
If you're experiencing a problem that is similar to this then you will need to file a new big with repro instructions.

We have already cherry picked what we thought was the fix for this bug. So either we've got it wrong or you're experiencing a different issue with similar symptoms.

At any rate, we do not have enough information

**Comment by jonahwilliams** [comment] 2024-09-02 17:19
If that is the commit that is causing the issue for you, then good news, we can cherry pick the fix

**Comment by mtallenca** [comment] 2024-09-12 21:04
Testing 3.24.3 that includes #154564

1. The GPU hang on the old iPad Pros no longer hangs in the same place and our app continues to work. However, at the point where the app did hang previously we are seeing the display corrupted during the animation. After the animation, the display looks correct. See video.  We are still seeing GPU hangs as we continue to use the app though.

https://github.com/user-attachments/assets/25cb0227-377a-4cf1-9ad0-b170a7b5c885

2. The GPU hang on iPhone 6s still happens at the same place.

3. The font corruption has not been fixed. Commit [839ba6b3e395a905ae10c37db05976352c1eb250](https://github.com/flutter/flutter/commit/839ba6b3e395a905ae10c37db05976352c1eb250) introduced this regression. We see this issue on iPad mini 4 most consistently.  Sending the app to the background, bringing it back to the foreground causes a repaint and seems to fix the issue. See video - font in pill at top of display.

https://github.com/user-attachments/assets/c031da39-5a07-4068-9fe2-196349979ef3

4) Is FLTUseFlutterMetalLayer safe to turn on in 3.24.3? We don't see the crashes or font corruption with that on - but we do see a reproducible instance of a line that is under a menu dialog is being drawn on the dialog.

**Comment by jonahwilliams** [comment] 2024-09-12 21:06
FLTUseFlutterMetalLayer is not safe to turn on. Sorry, if ypu're still having issues you need to update to the beta.

**Comment by mtallenca** [comment] 2024-09-12 21:42
Got it.  Testing beta channel 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.26.0-0.1.pre, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
[✓] Connected device (6 available)
[✓] Network resources

Seeing a crash where we previously saw the GPU hang

Launching lib/main.dart on Michael’s iPad (2) in profile mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 6MDE8399G4
Running Xcode build...
 └─Compiling, linking and signing...                         7.4s
Xcode build done.                                           28.9s
(lldb) 2024-09-12 14:38:54.937499-0700 LifeBible[6693:1436680] <SKPaymentQueue: 0x280361720>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
[Firebase/Crashlytics] Version 11.0.0
database path: /var/containers/Bundle/Application/BB2C2EC0-57AD-4A3E-9BBF-2B72C68EC92B/LifeBible.app/Frameworks/flutter_downloader.framework/FlutterDownloaderDatabase.bundle/download_tasks.sql
AllFilesDownloadedMessage: All files have been downloaded
[catalog] Unable to list voice folder
[catalog] Unable to list voice folder
[catalog] Unable to list voice folder
flutter: Running on iPad Pro (9.7 inch, WiFi+LTE) with IOS 16.7.10, deviceUid: iPad6,4-or3u5azgav0fvmv8
<Warning>: The value for FacebookAdvertiserIDCollectionEnabled is currently set to FALSE so you're sending app events without collecting Advertiser ID. This can affect the quality of your advertising and analytics results.
[connection] nw_connection_get_connected_socket_block_invoke [C9] Client called nw_connection_get_connected_socket on unconnected nw_connection
TCP Conn 0x283073b60 Failed : error 0:50 [50]
[[FirebaseCore]] 11.0.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
[[FirebaseMessaging]] 11.0.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[[FirebaseInAppMessaging]] 11.0.0 - [FirebaseInAppMessaging][I-IAM180004] Runtime is already active, resume is just a no-op
[[FirebaseAnalytics]] 11.0.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.11.0.0 started
[[FirebaseAnalytics]] 11.0.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Installing and launching...                                        48.7s
[tcp] tcp_output [C11.1.1.7:3] flags=[R.] seq=3060586021, ack=987702472, win=4092 state=CLOSED rcv_nxt=987702472, snd_una=3060586021
[[FirebaseAnalytics]] 11.0.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
A Dart VM Service on Michael’s iPad (2) is available at: http://127.0.0.1:51743/DzU49FfoanE=/
[[FirebaseAnalytics]] 11.0.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
[[FirebaseAnalytics]] 11.0.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
The Flutter DevTools debugger and profiler on Michael’s iPad (2) is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51743/DzU49FfoanE=/
[connection] nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for ep2.facebook.com:443
[connection] nw_resolver_start_query_timer_block_invoke [C1.1.2] Query fired: did not receive all answers in time for ep2.facebook.com:443
[connection] nw_resolver_start_query_timer_block_invoke [C5.1.1] Query fired: did not receive all answers in time for graph.facebook.com:443
[connection] nw_resolver_start_query_timer_block_invoke [C6.1.1] Query fired: did not receive all answers in time for graph.facebook.com:443
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x1c1a5d40c 0x1badb9c28 0x1c1bec3fc 0x1c1be8df8 0x1c1a676e4 0x105abf640 0x105ae4520 0x105ae8658 0x1c1b15bb0 0x1c1ad6de4 0x1c1a800fc 0x1c1ac95bc 0x1c1acdd20 0x1f92e1998 0x1c3d6034c 0x1c3d5ffc4 0x1c9ce6ddc 0x10038d7c4 0x1df27c344)
libc++abi: terminating due to uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001fc9c3198 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1fc9c3198 <+8>:  b.lo   0x1fc9c31b4               ; <+36>
    0x1fc9c319c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1fc9c31a0 <+16>: mov    x29, sp
    0x1fc9c31a4 <+20>: bl     0x1fc9beb70               ; cerror_nocancel
Target 0: (LifeBible) stopped.
Lost connection to device.

**Comment by RubyRook** [comment] 2024-09-13 04:26
In my case, `showModalBottomSheet` above `WebViewWidget` still has GPU error in some points:
+ Content inside `ModalBottomSheet`:
    - `ListView.builder` [works fine]
    - `CustomScrollView` [works fine]
    - `SingleChildScrollView` [GPU error]
 
It ok, I can switch to `CustomScrollView`. But, if `SingleChildScrollView` also fixed it would be great.

**Comment by jonahwilliams** [comment] 2024-09-13 04:32
So I can only guarantee something is fixed if I have a repro to work from, otherwise individuals testing on master/beta or bisecting isn't sufficient to guarantee that a change cherry picked into stable will fix things (because different changes can interact). 

I think in this case we're not going to find more low hanging fruit, and its likely that if you need the flutter metal layer to fix the problems you'll have to wait to the next stable, or downgrade until you have a working version again.

**Comment by mtallenca** [comment] 2024-09-14 00:53
I have a small repo that will reproduce the crash.  We weren't using any platform views directly, but using a package that was using PointerInterceptor which creates a childless platform view.  When used in a dialog on a older ipad (slower?) there is a crash in BringLayersIntoView.  Assuming it's a timing issue as it may take a couple of dialog shows/closes to get the crash in the sample repo.  We have more widgets/animation in our app so we see the crash almost every dialog close.

https://github.com/mtallenca/pointer
