### ISSUE TITLE
Navigator.of(context).restorablePushNamed is not returning future and not returning and valid result

### ISSUE THREAD

**Issue by SITARAM-LAB** [flutter/flutter#91282] opened 2021-10-05 03:43 UTC
Navigator.of(context).restorablePushNamed is not returning future and not returning and valid result,
IDEA IDE shows this method does not return any future but your documentation shows it return future.
here is your documentation 

[https://api.flutter.dev/flutter/widgets/Navigator/restorablePushNamed.html](url)

My code for push and pop is

for push :

final result =  Navigator.of(context).restorablePushNamed('/demo/lists');

for pop :

Navigator.pop(context, 'yo');

So when I run it, and print the result it gives me r+3, r+4

**Comment by danagbemava-nc** [comment] 2021-10-05 08:53
Hi @SITARAM-LAB 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by SITARAM-LAB** [comment] 2021-10-05 09:10
Hi,
following are two,

Navigator.pushNamed is working fine but
Navigator.of(context).restorablePushNamed is not returning valid
result

kindly check if possible.


final result = await Navigator.pushNamed(
  context,
    '/demo/lists'   //this is working
  )






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Atul>flutter doctor -v
[âˆš] Flutter (Channel master, 2.6.0-12.0.pre.22, on Microsoft Windows
[Version
    6.3.9600], locale en-US)
    â€¢ Flutter version 2.6.0-12.0.pre.22 at
      C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter
    â€¢ Upstream repository https://github.com/flutter/flutter.git
    â€¢ Framework revision 83dfb2237a (2 weeks ago), 2021-09-17 23:48:04
-0400
    â€¢ Engine revision 31792e0340
    â€¢ Dart version 2.15.0 (build 2.15.0-120.0.dev)



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%






C:\Users\Atul>flutter run --verbose
[ +130 ms] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
-c
log.showSignature=false log -n 1 --pretty=format:%H
[ +122 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 83dfb2237a22ad92c38e345b3aa85aeecae732aa
[   +1 ms] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
tag
--points-at 83dfb2237a22ad92c38e345b3aa85aeecae732aa
[  +82 ms] Exit code 0 from: git tag --points-at
83dfb2237a22ad92c38e345b3aa85aeecae732aa
[   +4 ms] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
describe --match *.*.* --long --tags
83dfb2237a22ad92c38e345b3aa85aeecae732aa
[ +139 ms] Exit code 0 from: git describe --match *.*.* --long --tags
83dfb2237a22ad92c38e345b3aa85aeecae732aa
[   +1 ms] 2.6.0-11.0.pre-22-g83dfb2237a
[  +17 ms] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +195 ms] executing:
[C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter/] git
rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required,

skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping
update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping

update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping

update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +122 ms] executing:
C:\Users\Atul\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +99 ms] List of devices attached
[  +14 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required,

skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping

update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping

update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +72 ms] "flutter run" took 395ms.
[  +37 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +6 ms]
           #0      FlutterCommand.validateCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1391:11)
           #1      RunCommand.validateCommand
           (package:flutter_tools/src/commands/run.dart:456:19)
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1232:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand
           (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>

 (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand

 (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[ +267 ms] ensureAnalyticsSent: 262ms
[   +5 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

C:\Users\Atul>

**Comment by danagbemava-nc** [comment] 2021-10-05 09:33
Hi @SITARAM-LAB, the information that you have provided is not enough for me to act on. 

Kindly provide a complete minimal reproducible code sample that demonstrates what issue you're running into. 

`flutter run -v` needs to be run from your project directory. 

Thank you

**Comment by SITARAM-LAB** [comment] 2021-10-05 10:25
hi,

//screen1.dart

final result= Navigator.of(context).restorablePushNamed(
  '/demo/lists',
); //after calling pop it returns r+3, r+4

//screen2.dart  with named route '/demo/lists'

Navigator.pop(context, 'yo'); //code for poping screen

//it should return the result 'yo' but it returns r+3, r+4


following is flutter d
octor -v run from project root

C:\Users\Atul\Documents\flutter_projects\gallery-master\gallery-master>flutter
d
octor -v
[ΓêÜ] Flutter (Channel master, 2.6.0-12.0.pre.22, on Microsoft Windows
[Version
    6.3.9600], locale en-US)
    ΓÇó Flutter version 2.6.0-12.0.pre.22 at
      C:\Users\Atul\Documents\flutter\flutter_windows_2.2.3-stable\flutter
    ΓÇó Upstream repository https://github.com/flutter/flutter.git
    ΓÇó Framework revision 83dfb2237a (2 weeks ago), 2021-09-17 23:48:04
-0400
    ΓÇó Engine revision 31792e0340
    ΓÇó Dart version 2.15.0 (build 2.15.0-120.0.dev)

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK version
30.0.
2)
    ΓÇó Android SDK at C:\Users\Atul\AppData\Local\Android\sdk
    ΓÇó Platform android-30, build-tools 30.0.2
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    ΓÇó All Android licenses accepted.

[ΓêÜ] Chrome - develop for the web
    ΓÇó Chrome at C:\Program Files
(x86)\Google\Chrome\Application\chrome.exe

[ΓêÜ] Android Studio (version 4.0)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ΓÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ΓÇó Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[ΓêÜ] IntelliJ IDEA Community Edition (version 2021.2)
    ΓÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community
Edition
      2021.2
    ΓÇó Flutter plugin version 59.0.4
    ΓÇó Dart plugin version 212.4746.57

[ΓêÜ] VS Code, 64-bit edition (version 1.60.2)
    ΓÇó VS Code at C:\Program Files\Microsoft VS Code
    ΓÇó Flutter extension version 3.15.0

[ΓêÜ] Connected device (2 available)
    ΓÇó Chrome (web) ΓÇó chrome ΓÇó web-javascript ΓÇó Google Chrome
94.0.4606.7
1
    ΓÇó Edge (web)   ΓÇó edge   ΓÇó web-javascript ΓÇó Microsoft Edge
94.0.992.3
7

ΓÇó No issues found!

C:\Users\Atul\Documents\flutter_projects\gallery-master\gallery-master>

**Comment by danagbemava-nc** [comment] 2021-10-05 12:30
@SITARAM-LAB, `restorablePushNamed` is working as intended. If you look at the method signature, it not intended to return a future. Whereas `pushNamed/push`, etc, return futures since they are intended to return futures.

`restorablePushNamed`

```dart
 @optionalTypeArgs
  String restorablePushNamed<T extends Object?>(
    String routeName, {
    Object? arguments,
  }) {
    assert(routeName != null);
    assert(debugIsSerializableForRestoration(arguments), 'The arguments object must be serializable via the StandardMessageCodec.');
    final _RouteEntry entry = _RestorationInformation.named(
      name: routeName,
      arguments: arguments,
      restorationScopeId: _nextPagelessRestorationScopeId,
    ).toRouteEntry(this, initialState: _RouteLifecycle.push);
    _pushEntry(entry);
    return entry.restorationId!;
  }
```

`pushNamed`

```dart
 @optionalTypeArgs
  static Future<T?> pushNamed<T extends Object?>(
    BuildContext context,
    String routeName, {
    Object? arguments,
  }) {
    return Navigator.of(context).pushNamed<T>(routeName, arguments: arguments);
  }
```

You can check the api docs for more information https://api.flutter.dev/flutter/widgets/Navigator/restorablePushNamed.html

Closing as this is the intended behaviour.

Thank you

**Closed by danagbemava-nc** 2021-10-05 12:30 UTC
Labels: in triage

**Comment by SITARAM-LAB** [comment] 2021-10-05 12:43
Future was mentioned in the official documentation.
It doesn't matter.
But it's returning r+3 not needed string value.

**Comment by danagbemava-nc** [comment] 2021-10-05 13:08
The documentation also states this 

```json
The method returns an opaque ID for the pushed route that can be used by the RestorableRouteFuture to gain access to the actual Route object added to the navigator and its return value. You can ignore the return value of this method, if you do not care about the route object or the route's return value.
```

You can look up `RestorableRouteFuture` here https://api.flutter.dev/flutter/widgets/RestorableRouteFuture-class.html
