### ISSUE TITLE
How to load PDF file from URL without downloading

### ISSUE THREAD

**Issue by AbirAhsan** [flutter/flutter#60834] opened 2020-07-04 15:48 UTC
I want to fetch a PDF file from a URL and want to show in my flutter App. And when it's loading from URL, then want to show the percentage bar (How much has been done).

I used `advance_pdf_viewer 1.1.6` but there are no option to show percentage bar.

_**Is it possible? If possible, please someone write me a code for this.**_

> Here is my code-

```
import 'package:flutter/material.dart';
import 'package:advance_pdf_viewer/advance_pdf_viewer.dart';

class PdfScreen extends StatelessWidget {
  PdfScreen(this.link);
  final String link;

  loadDocument() async {
    try {
      PDFDocument document;
      document = await PDFDocument.fromURL(link);
      return document;
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    print(link);
    return SafeArea(
      child: FutureBuilder(
        future: loadDocument(),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.hasData) {
            final Color _whiteCream = Color.fromRGBO(250, 245, 228, 1);
            final Color _darkBlue = Color.fromRGBO(0, 68, 69, 1);
            return Scaffold(
              appBar: AppBar(
                title: Row(
                  children: <Widget>[
                    Image.asset(
                      "assets/images/boi.jpg",
                      color: _whiteCream,
                      height: 32.0,
                      width: 32.0,
                      fit: BoxFit.cover,
                    ),
                    SizedBox(
                      width: 5.0,
                    ),
                    Text('বই বাজার')
                  ],
                ),
                backgroundColor: _darkBlue,
              ),
              body: PDFViewer(
                document: snapshot.data,
                lazyLoad: false,
                scrollDirection: Axis.vertical,
                zoomSteps: 5,
              ),
            );
          }
          return Scaffold(
            body: Container(
              color: Color.fromRGBO(250, 245, 228, 1),
              child: Center(
                child: CircularProgressIndicator(
                  backgroundColor: Color.fromRGBO(250, 245, 228, 1),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
```

**Comment by iapicca** [comment] 2020-07-06 07:26
Hi @AbirAhsan 
From what I can see, the issue is related to the 3rd party plugin [advance_pdf_viewer](https://pub.dev/packages/advance_pdf_viewer) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/lohanidamodar/pdf_viewer).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-06 07:26 UTC
Labels: created via support template

**Comment by JALTESHGJ** [comment] 2020-12-23 06:18
I have tried so many times the pdf file with HTTP is working fine for me but if I requested with HTTPS then it's not going to be loading. 
![image](https://user-images.githubusercontent.com/36148900/102965893-ca434200-4514-11eb-99cf-0b8fe8db4391.png)

**Comment by iapicca** [comment] 2020-12-23 09:44
@JALTESHGJ 
could you please open a new issue providing
your `flutter doctor -v,` your `flutter run -v`, your `pubspec.yaml`
and most importantly
a minimal reproducible code sample that does not use 3rd party plugins,
