### ISSUE TITLE
Facing issues in creating iOS build for flutter app

### ISSUE THREAD

**Issue by manmohan00008** [flutter/flutter#51910] opened 2020-03-04 06:06 UTC
I  have created an App using flutter and build is working fine on Android. But while creating iOS build, was getting lots of errors. Rectified many error but still the build is not successful. The error is :

```
linker command failed with exit code 1 (use -v to see invocation) : 26 duplicate symbols for architecture x86_64
```

The error is appearing while creating app from xCode. The steps for the same are as follows:

Imported the Runner.xcworkspace in xCode.
Made certificates setting and tried building the code.
Got the above error.
While creating app via cmd with the following command:

`flutter build ios -v main_production.dart`

It is showing the following error:

```
Application not configured for iOS

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:62:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_pat
```

Flutter doctor shows the following :

```
 Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/manmohan/Desktop/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
```

**Comment by VladyslavBondarenko** [comment] 2020-03-04 12:28
Hi @manmohan00008 could you specify what Xcode version do you use?

**Comment by VladyslavBondarenko** [comment] 2020-03-04 12:41
Hi @manmohan00008 
try https://github.com/flutter/flutter/issues/44305#issuecomment-557074487,
your issue seems to be a duplicate of https://github.com/flutter/flutter/issues/44571
please follow on the mentioned, closing current one
if you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-03-04 12:41 UTC
