### ISSUE TITLE
🐛 Failed assertion in the scheduler callback (semantics.dart line 3023 pos 16)

### ISSUE THREAD

**Issue by FrazeColder** [flutter/flutter#99832] opened 2022-03-09 15:40 UTC
## Steps to Reproduce

I have created a repository in order to check where to problem is coming from. I found out, it is due to using a `RichText` widget with a `TextSpan` and a `TapGestureRecognizer` which opens a URL. However, this problem only occurs when all of the widgets I mentioned are wrapped up in a `FormBuilderCheckbox`. You can download my repo I have provided to reproduce the bug. Because I am not able to understand what the problem is and the exceptions means, I have created this ticket.

Can you please help me to solve this issue? I would like to be able to create a checkbox with text which also opens the browser to the terms and contions if you tap on them.

[Here you can download my repo.](https://github.com/FrazeColder/checkbox_debug)

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3023 pos 16: 'node.parent ==
null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3023:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on iPhone 13 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:60778/96VIfHcvjPI=/

```

```
Analyzing checkbox_debug...                                             
No issues found! (ran in 2.7s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale de-DE)
    • Flutter version 2.10.3 at /usr/local/Caskroom/flutter/2.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jantrier/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 2042D746-4755-4638-8014-92CC2D15D4EE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-03-10 07:16
@FrazeColder 
Thanks for the report. The code you shared in the repo seems to have third party packages and `FormBuilderCheckbox` seems to be coming from `flutter_form_builder`. Can you try by removing the said package code and just use core framework code to see if issue still persists ?
If so, can you provide a complete minimal reproducible code sample without any third party plugin code that still triggers the error you are reporting ?



> it is due to using a `RichText` widget with a `TextSpan` and a `TapGestureRecognizer` which opens a URL.

Can you provide a minimal code sample involving these widgets that triggers the error ?

**Comment by FrazeColder** [comment] 2022-03-11 18:57
@darshankawar 

Here is a minimal reproducible code sample without the `flutter_form_builder` library (just with the `url_launcher` extension) which works perfectly:
```
RichText(
    text: TextSpan(
    children: [
        const TextSpan(
        text:
            'But it works when being by itself without the FormBuilderCheckbox ',
        style: TextStyle(color: Colors.black),
        ),
        TextSpan(
        text: 'Terms and Conditions',
        style: const TextStyle(color: Colors.blue),
        recognizer: TapGestureRecognizer()
            ..onTap = () async {
            const url = "https://google.de";
            if (await canLaunch(url)) {
                launch(url, forceWebView: true);
            }
            },
        ),
    ],
    ),
),
```

But as soon, as you wrap the code above in a `FormBuilderCheckbox(...)` widget, this error gets produced. I do agree with you, that the error _seems_ to come from the `flutter_form_builder` library. 

However, the `flutter/src/semantics/semantics.dart` class is a core framework file. Can you at least tell me what the problem there is because I do not understand the error which get's thrown at `semantics.dart`.

**Comment by darshankawar** [comment] 2022-03-14 06:00
@FrazeColder 
Thanks for the update. I looked at the error and it seems to be an issue with semantics / accessibility and seem to be specific to iOS only. The reason this only happen in ios is because ios simulator has semantics turned on by default.

Below is a minimal code sample that replicates the issue:

```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:url_launcher/url_launcher.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isTermsReadChecked = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: CheckboxListTile(
          value: _isTermsReadChecked,
          selected: _isTermsReadChecked,
          onChanged: (val) {
            setState(
                  () {
                _isTermsReadChecked = !_isTermsReadChecked;
              },
            );
          },
          title: RichText(
            text: TextSpan(
              children: [
                const TextSpan(
                  text:
                  'But it works when being by itself without the FormBuilderCheckbox ',
                  style: TextStyle(color: Colors.black),
                ),
                TextSpan(
                  text: 'Terms and Conditions',
                  style: const TextStyle(color: Colors.blue),
                  recognizer: TapGestureRecognizer()
                    ..onTap = () async {
                      const url = "https://google.de";
                      if (await canLaunch(url)) {
                        launch(url, forceWebView: true);
                      }
                    },
                ),
              ],
            ),
          ),
        )
    );
  }
}

```

When there is a RichText with gesture recognizer in a CheckboxListTile, it will cause a conflict because CheckboxListTile is consider as a giant button semantics node that absorb its children and RichText is also declare itself as a standalone semantics node.

In your case, using Checkbox instead of CheckboxListTile will trigger the same error.

In order to implement checkbox + richText properly, check out [this](https://api.flutter.dev/flutter/material/CheckboxListTile-class.html) document and specially `Semantics in CheckboxListTile` section in it and see how it is implemented and check if it helps to overcome the issue.

**Comment by FrazeColder** [comment] 2022-03-14 09:36
@darshankawar alright, thank you very much! At least, I now know, whats the problem is! I will try to implement it the way you suggested!

**Comment by darshankawar** [comment] 2022-03-15 05:04
I am going ahead and closing this for now, as we provided you the example on how to implement the said usage. If you face any issues, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-03-15 05:04 UTC
Labels: in triage
