### ISSUE TITLE
stock_build_iteration microbenchmark regression

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#39060] opened 2019-08-22 15:57 UTC
It appears that 9aea03f (https://github.com/flutter/flutter/pull/37024) introduced a ~2% regression in the stock_build_iteration microbenchmark:

<img width="228" alt="Screen Shot 2019-08-22 at 8 51 51 AM" src="https://user-images.githubusercontent.com/15253456/63530013-8bcdeb00-c4ba-11e9-9541-15c8651e461a.png">

**Comment by Hixie** [comment] 2019-11-08 22:05
Spoke to @LongCatIsLooong just now, they said they would look into it.

**Comment by LongCatIsLooong** [comment] 2019-11-13 00:07
The commit introduced a ~4.5% regression in stock_build_iteration microbenchmark per my test results. Reverting.

**Comment by goderbauer** [comment] 2019-11-13 01:18
@LongCatIsLooong Before we revert this: Were you able to figure out why the Builder is soo much slower? Since this is a Microbenchmark, it may be insightful to run the Profiler from Observatory over this.

**Comment by goderbauer** [comment] 2019-11-13 01:22
Another idea: Can we remove the performance hit if we change the SliverFillViewport to only use the Builder approach if you actually use a viewportFraction != 1.0?

**Comment by goderbauer** [comment] 2019-11-13 02:15
Hm, I guess we still need the builder even in the viewportfraction == 1.0 case to figure out the viewportextend.

**Comment by LongCatIsLooong** [comment] 2019-11-19 20:12
Profiling revealed that using `LayoutBuilder` and `SliverLayoutBuilder` are currently more expensive than approaches that create specialized render objects (in this case, `RenderSliverFillViewport`).
One of the reasons is when an ancestor `Element` is marked dirty, in the latter case we can skip laying out and painting entirely if not needed, whereas `LayoutBuilder`s have to mark at least their own render objects need layout and need paint. That adds `~0.04` ms to the benchmark. Also the layout builder introduced an additional `0.01~0.02 ms` overhead during the layout phase (Layout - Layout.Build), presumably because its render object has to propagate the `markNeedsLayout` all the way up to the closest re-layout boundary and all the dirty render objects have to re-layout and repaint.

```
 | Phases       | RenderSliverFillViewport (ms) |       | SliverLayoutBuilder (ms) |       |
 |--------------+-------------------------------+-------+--------------------------+-------|
 | Total        |                         1.161 | 1.162 |                    1.238 | 1.257 |
 | Frame        |                         0.939 | 0.961 |                    1.045 | 1.042 |
 |--------------+-------------------------------+-------+--------------------------+-------|
 | Build        |                         0.773 | 0.790 |                    0.721 | 0.714 |
 |--------------+-------------------------------+-------+--------------------------+-------|
 | Layout       |                         0.004 | 0.004 |                    0.113 | 0.119 |
 | Layout.Build |                             - |     - |                    0.103 | 0.100 |
 |--------------+-------------------------------+-------+--------------------------+-------|
 | Paint        |                         0.004 | 0.004 |                    0.020 | 0.019 |
 | Compositing  |                         0.043 | 0.044 |                    0.069 | 0.069 |




```

**Comment by goderbauer** [comment] 2019-11-19 20:39
Could we avoid the extra cost by caching the SliverLayoutBuilder widget and only re-instantiating it if things that are closured into the builder are changing?

**Comment by LongCatIsLooong** [comment] 2019-11-22 23:39
I tried the widget caching idea. if I also cache the tabs used in the `TabView`, it completely short circuits the layout phase and brings the performance to on par with the original non-layout-builder implementation (with tabs cached). But if I do not cache the tabs, then I'll have to invalidate the `SliverLayoutBuilder` cache every time because the child delegate always returns `false`:
```
  @override
  bool shouldRebuild(covariant SliverChildListDelegate oldDelegate) {
    return children != oldDelegate.children;
  }
```

**Comment by LongCatIsLooong** [comment] 2019-11-25 23:25
Closing the issue now that the pull request is reverted.

**Closed by LongCatIsLooong** 2019-11-25 23:25 UTC
Labels: f: scrolling, framework, severe: performance, severe: regression
