### ISSUE TITLE
IOS crash when the Photos privacy settings change

### ISSUE THREAD

**Issue by magax** [flutter/flutter#57209] opened 2020-05-14 13:22 UTC
My app crashes when I change the "Photos" permission.

## Steps to Reproduce

1. Create and run a flutter project with `<key>NSPhotoLibraryUsageDescription</key>
	<string></string>` in your `Info.plist` file.
2. Go to the iOS `Settings > Privacy > Photos > YourApp` then change the value either to `Never` or `Read and Write`.

**Expected results:** Changing the permission as expected.

**Actual results:** In the debug console: `Lost connection to device.
Exited (sigterm)`

<details>
  <summary>Logs</summary>

No issues found! (ran in 10.8s)

[✓] Flutter (Channel dev, 1.18.0-12.0.pre, on Mac OS X 10.15.4 19E287, locale en-AR)
    • Flutter version 1.18.0-12.0.pre at /Users/magax/Documents/dev/Flutter/tools/flutter
    • Framework revision c2b7342ca4 (8 days ago), 2020-05-06 23:16:03 +0800
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/magax/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/magax/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Magax’s iPhone • cd583d10f1eef699e8dbea8d962a8126c19aa24c • ios • iOS 13.4

• No issues found!

</details>

**Comment by TahaTesser** [comment] 2020-05-14 14:19
Hi @magax 
Are you using `image_picker` or this happen in any new project? 
can you please provide your `flutter run --verbose` with crash logs? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by magax** [comment] 2020-05-14 15:20
> Hi @magax
> Are you using `image_picker` or this happen in any new project?
> can you please provide your `flutter run --verbose` with crash logs?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

I was initially using `image_picker` but I found out that the same issue was still happening after removing out every bit of code related to this package, that's why I didn't mention it. So nothing useful to be found in my code. The app just crashes when I change the Photos permission.

I tried to add my `flutter run --verbose` but Github is telling me that my comment is too long even though I wrapped the logs between tags to visually minimize the comment. I am sorry I'm not properly used to Github yet.

**Comment by TahaTesser** [comment] 2021-01-15 15:48
Following the steps, I can crash reproduce the crash 

<details>
<summary>code sample</summary>

```dart
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/basic.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Image Picker Demo',
      home: MyHomePage(title: 'Image Picker Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  PickedFile _imageFile;
  dynamic _pickImageError;
  bool isVideo = false;
  VideoPlayerController _controller;
  VideoPlayerController _toBeDisposed;
  String _retrieveDataError;

  final ImagePicker _picker = ImagePicker();
  final TextEditingController maxWidthController = TextEditingController();
  final TextEditingController maxHeightController = TextEditingController();
  final TextEditingController qualityController = TextEditingController();

  Future<void> _playVideo(PickedFile file) async {
    if (file != null && mounted) {
      await _disposeVideoController();
      if (kIsWeb) {
        _controller = VideoPlayerController.network(file.path);
        // In web, most browsers won't honor a programmatic call to .play
        // if the video has a sound track (and is not muted).
        // Mute the video so it auto-plays in web!
        // This is not needed if the call to .play is the result of user
        // interaction (clicking on a "play" button, for example).
        await _controller.setVolume(0.0);
      } else {
        _controller = VideoPlayerController.file(File(file.path));
        await _controller.setVolume(1.0);
      }
      await _controller.initialize();
      await _controller.setLooping(true);
      await _controller.play();
      setState(() {});
    }
  }

  void _onImageButtonPressed(ImageSource source, {BuildContext context}) async {
    if (_controller != null) {
      await _controller.setVolume(0.0);
    }
    if (isVideo) {
      final PickedFile file = await _picker.getVideo(
          source: source, maxDuration: const Duration(seconds: 10));
      await _playVideo(file);
    } else {
      await _displayPickImageDialog(context,
          (double maxWidth, double maxHeight, int quality) async {
        try {
          final pickedFile = await _picker.getImage(
            source: source,
            maxWidth: maxWidth,
            maxHeight: maxHeight,
            imageQuality: quality,
          );
          setState(() {
            _imageFile = pickedFile;
          });
        } catch (e) {
          setState(() {
            _pickImageError = e;
          });
        }
      });
    }
  }

  @override
  void deactivate() {
    if (_controller != null) {
      _controller.setVolume(0.0);
      _controller.pause();
    }
    super.deactivate();
  }

  @override
  void dispose() {
    _disposeVideoController();
    maxWidthController.dispose();
    maxHeightController.dispose();
    qualityController.dispose();
    super.dispose();
  }

  Future<void> _disposeVideoController() async {
    if (_toBeDisposed != null) {
      await _toBeDisposed.dispose();
    }
    _toBeDisposed = _controller;
    _controller = null;
  }

  Widget _previewVideo() {
    final Text retrieveError = _getRetrieveErrorWidget();
    if (retrieveError != null) {
      return retrieveError;
    }
    if (_controller == null) {
      return const Text(
        'You have not yet picked a video',
        textAlign: TextAlign.center,
      );
    }
    return Padding(
      padding: const EdgeInsets.all(10.0),
      child: AspectRatioVideo(_controller),
    );
  }

  Widget _previewImage() {
    final Text retrieveError = _getRetrieveErrorWidget();
    if (retrieveError != null) {
      return retrieveError;
    }
    if (_imageFile != null) {
      if (kIsWeb) {
        // Why network?
        // See https://pub.dev/packages/image_picker#getting-ready-for-the-web-platform
        return Image.network(_imageFile.path);
      } else {
        return Semantics(
            child: Image.file(File(_imageFile.path)),
            label: 'image_picker_example_picked_image');
      }
    } else if (_pickImageError != null) {
      return Text(
        'Pick image error: $_pickImageError',
        textAlign: TextAlign.center,
      );
    } else {
      return const Text(
        'You have not yet picked an image.',
        textAlign: TextAlign.center,
      );
    }
  }

  Future<void> retrieveLostData() async {
    final LostData response = await _picker.getLostData();
    if (response.isEmpty) {
      return;
    }
    if (response.file != null) {
      if (response.type == RetrieveType.video) {
        isVideo = true;
        await _playVideo(response.file);
      } else {
        isVideo = false;
        setState(() {
          _imageFile = response.file;
        });
      }
    } else {
      _retrieveDataError = response.exception.code;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: !kIsWeb && defaultTargetPlatform == TargetPlatform.android
            ? FutureBuilder<void>(
                future: retrieveLostData(),
                builder: (BuildContext context, AsyncSnapshot<void> snapshot) {
                  switch (snapshot.connectionState) {
                    case ConnectionState.none:
                    case ConnectionState.waiting:
                      return const Text(
                        'You have not yet picked an image.',
                        textAlign: TextAlign.center,
                      );
                    case ConnectionState.done:
                      return isVideo ? _previewVideo() : _previewImage();
                    default:
                      if (snapshot.hasError) {
                        return Text(
                          'Pick image/video error: ${snapshot.error}}',
                          textAlign: TextAlign.center,
                        );
                      } else {
                        return const Text(
                          'You have not yet picked an image.',
                          textAlign: TextAlign.center,
                        );
                      }
                  }
                },
              )
            : (isVideo ? _previewVideo() : _previewImage()),
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Semantics(
            label: 'image_picker_example_from_gallery',
            child: FloatingActionButton(
              onPressed: () {
                isVideo = false;
                _onImageButtonPressed(ImageSource.gallery, context: context);
              },
              heroTag: 'image0',
              tooltip: 'Pick Image from gallery',
              child: const Icon(Icons.photo_library),
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(top: 16.0),
            child: FloatingActionButton(
              onPressed: () {
                isVideo = false;
                _onImageButtonPressed(ImageSource.camera, context: context);
              },
              heroTag: 'image1',
              tooltip: 'Take a Photo',
              child: const Icon(Icons.camera_alt),
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(top: 16.0),
            child: FloatingActionButton(
              backgroundColor: Colors.red,
              onPressed: () {
                isVideo = true;
                _onImageButtonPressed(ImageSource.gallery);
              },
              heroTag: 'video0',
              tooltip: 'Pick Video from gallery',
              child: const Icon(Icons.video_library),
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(top: 16.0),
            child: FloatingActionButton(
              backgroundColor: Colors.red,
              onPressed: () {
                isVideo = true;
                _onImageButtonPressed(ImageSource.camera);
              },
              heroTag: 'video1',
              tooltip: 'Take a Video',
              child: const Icon(Icons.videocam),
            ),
          ),
        ],
      ),
    );
  }

  Text _getRetrieveErrorWidget() {
    if (_retrieveDataError != null) {
      final Text result = Text(_retrieveDataError);
      _retrieveDataError = null;
      return result;
    }
    return null;
  }

  Future<void> _displayPickImageDialog(
      BuildContext context, OnPickImageCallback onPick) async {
    return showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: Text('Add optional parameters'),
            content: Column(
              children: <Widget>[
                TextField(
                  controller: maxWidthController,
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  decoration:
                      InputDecoration(hintText: "Enter maxWidth if desired"),
                ),
                TextField(
                  controller: maxHeightController,
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  decoration:
                      InputDecoration(hintText: "Enter maxHeight if desired"),
                ),
                TextField(
                  controller: qualityController,
                  keyboardType: TextInputType.number,
                  decoration:
                      InputDecoration(hintText: "Enter quality if desired"),
                ),
              ],
            ),
            actions: <Widget>[
              FlatButton(
                child: const Text('CANCEL'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
              FlatButton(
                  child: const Text('PICK'),
                  onPressed: () {
                    double width = maxWidthController.text.isNotEmpty
                        ? double.parse(maxWidthController.text)
                        : null;
                    double height = maxHeightController.text.isNotEmpty
                        ? double.parse(maxHeightController.text)
                        : null;
                    int quality = qualityController.text.isNotEmpty
                        ? int.parse(qualityController.text)
                        : null;
                    onPick(width, height, quality);
                    Navigator.of(context).pop();
                  }),
            ],
          );
        });
  }
}

typedef void OnPickImageCallback(
    double maxWidth, double maxHeight, int quality);

class AspectRatioVideo extends StatefulWidget {
  AspectRatioVideo(this.controller);

  final VideoPlayerController controller;

  @override
  AspectRatioVideoState createState() => AspectRatioVideoState();
}

class AspectRatioVideoState extends State<AspectRatioVideo> {
  VideoPlayerController get controller => widget.controller;
  bool initialized = false;

  void _onVideoControllerUpdate() {
    if (!mounted) {
      return;
    }
    if (initialized != controller.value.initialized) {
      initialized = controller.value.initialized;
      setState(() {});
    }
  }

  @override
  void initState() {
    super.initState();
    controller.addListener(_onVideoControllerUpdate);
  }

  @override
  void dispose() {
    controller.removeListener(_onVideoControllerUpdate);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (initialized) {
      return Center(
        child: AspectRatio(
          aspectRatio: controller.value?.aspectRatio,
          child: VideoPlayer(controller),
        ),
      );
    } else {
      return Container();
    }
  }
}
```
</details>


<details>
<summary>logs</summary>

```bash
ample/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 32%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/vm_snapshot_data to device
[        ] [ 32%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/isolate_snapshot_data to device
[ +501 ms] [ 33%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[   +1 ms] [ 33%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[+3459 ms] [ 40%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/NOTICES to device
[ +102 ms] [ 40%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[        ] [ 41%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/ to device
[        ] [ 41%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/ to device
[        ] [ 41%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/ to device
[        ] [ 41%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf to device
[        ] [ 42%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/ to device
[        ] [ 42%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf to device
[ +158 ms] [ 42%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/Info.plist to device
[        ] [ 43%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/libswiftDarwin.dylib to device
[  +71 ms] [ 43%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/libswiftQuartzCore.dylib to device
[  +52 ms] [ 43%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreAudio.dylib to device
[  +71 ms] [ 44%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/image_picker.framework/ to device
[        ] [ 44%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/image_picker.framework/_CodeSignature/ to device
[        ] [ 44%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/image_picker.framework/_CodeSignature/CodeResources to device
[        ] [ 44%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/image_picker.framework/image_picker to device
[   +2 ms] [ 45%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/image_picker.framework/Info.plist to device
[        ] [ 45%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/libswiftFoundation.dylib to device
[+1427 ms] [ 48%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Frameworks/libswiftCoreMedia.dylib to device
[  +32 ms] [ 48%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/AppIcon20x20~ipad.png to device
[        ] [ 48%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/embedded.mobileprovision to device
[  +20 ms] [ 48%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/AppIcon20x20@2x~ipad.png to device
[        ] [ 49%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/PkgInfo to device
[        ] [ 49%] Copying /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[ +318 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +24 ms] [ 60%] TakingInstallLock
[  +75 ms] [ 65%] PreflightingApplication
[  +58 ms] [ 65%] InstallingEmbeddedProfile
[   +9 ms] [ 70%] VerifyingApplication
[ +181 ms] [ 75%] CreatingContainer
[   +7 ms] [ 80%] InstallingApplication
[  +14 ms] [ 85%] PostflightingApplication
[   +5 ms] [ 90%] SandboxingApplication
[  +18 ms] [ 95%] GeneratingApplicationMap
[  +75 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +144 ms] ------ Debug phase ------
[        ] Starting debug of 00008020-001059882212002E (N841AP, iPhone XR, iphoneos, arm64e) a.k.a. 'Taha’s iPhone' connected through USB...
[ +252 ms] [  0%] Looking up developer disk image
[  +19 ms] [ 95%] Developer disk image mounted successfully
[ +757 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +133 ms] (lldb) command source -s 0 '/tmp/899FCED5-7552-4C87-94D6-C620EC8BAE1D/fruitstrap-lldb-prep-cmds-00008020_001059882212002E'
[        ] Executing commands in '/tmp/899FCED5-7552-4C87-94D6-C620EC8BAE1D/fruitstrap-lldb-prep-cmds-00008020_001059882212002E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols"
[        ] (lldb)     target create "/Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app"
[+6497 ms] Current executable set to '/Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/E4FA1E6F-10C6-4BAE-9768-2BEAA08FEFEA/Runner.app"
[ +494 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:65498"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/usr" /System "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/E4FA1E6F-10C6-4BAE-9768-2BEAA08FEFEA" "/Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos" "/var/containers/Bundle/Application/E4FA1E6F-10C6-4BAE-9768-2BEAA08FEFEA" "/Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/image_picker_example/build/ios/iphoneos" /Developer "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/Developer"
[  +22 ms] (lldb)     command script import "/tmp/899FCED5-7552-4C87-94D6-C620EC8BAE1D/fruitstrap_00008020_001059882212002E.py"
[   +9 ms] (lldb)     command script add -f fruitstrap_00008020_001059882212002E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001059882212002E.safequit_command safequit
[        ] (lldb)     connect
[  +54 ms] (lldb)     run
[ +212 ms] success
[        ] (lldb)     safequit
[ +129 ms] Process 2521 detached
[  +67 ms] Application launched on the device. Waiting for observatory port.
[  +17 ms] Attempting to forward device port 61470 to host port 65505
[        ] executing: /Users/tahatesser/Code/flutter_stable/bin/cache/artifacts/usbmuxd/iproxy 65505:61470 --udid 00008020-001059882212002E
[+1014 ms] Forwarded port ForwardedPort HOST:65505 to DEVICE:61470
[ +134 ms] Installing and launching... (completed in 23.9s)
[   +1 ms] Caching compiled dill
[ +171 ms] Connecting to service protocol: http://localhost:65505
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[  +42 ms] Successfully connected to service protocol: http://localhost:65505
[   +3 ms] Waiting for Taha’s iPhone to report its views...
[   +5 ms] Waiting for Taha’s iPhone to report its views... (completed in 3ms)
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[  +13 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/8E722E81-FC41-4BE8-A511-188005CDBACE/tmp/image_picker_exampleSSu6oM/image_picker_example/)
[   +1 ms] Updating assets
[ +140 ms] Syncing files to device Taha’s iPhone...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:triage/main.dart 2173f8b0-2a8b-40a9-a214-f3626cc6bb0a
[        ] <- 2173f8b0-2a8b-40a9-a214-f3626cc6bb0a
[  +61 ms] Updating files
[  +99 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Taha’s iPhone... (completed in 167ms)
[   +1 ms] Synced 1.7MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x124046020.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://localhost:65505
[+4324 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/8E722E81-FC41-4BE8-A511-188005CDBACE/tmp/image_picker_exampleSSu6oM/image_picker_example/)
[ +261 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 61,470ms.
[ +161 ms] ensureAnalyticsSent: 155ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 0
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.365, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.365 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9209319dd1 (7 hours ago), 2021-01-15 14:34:03 +0530
    • Engine revision efa768683e
    • Dart version 2.12.0 (build 2.12.0-225.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.3
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by ydag** [comment] 2021-05-07 12:36
I couldn't reproduce the issue. Have you tested with the latest version? @magax

**Comment by darshankawar** [comment] 2021-06-04 13:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-04 13:08 UTC
Labels: found in release: 1.22, found in release: 1.26, has reproducible steps, p: first party, p: image_picker, platform-ios, plugin, severe: crash, severe: fatal crash, waiting for customer response
