### ISSUE TITLE
"ideviceinfo" cannot be opened because the developer cannot be verified. (Flutter)

### ISSUE THREAD

**Issue by Sgk3217** [flutter/flutter#44549] opened 2019-11-10 22:49 UTC
![Screen Shot 2019-11-10 at 3 48 49 PM](https://user-images.githubusercontent.com/11779141/68552208-9f119800-03d1-11ea-9b0a-28915b67ea0d.png)

**Comment by iapicca** [comment] 2019-11-11 11:26
Hi @Sgk3217 
could you please provide your `flutter doctor -v`
and the output of `flutter run --verbose` or `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by Sgk3217** [comment] 2019-11-11 20:18
> Hi @Sgk3217
> could you please provide your `flutter doctor -v`
> and the output of `flutter run --verbose` or `flutter build --verbose` ?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Please refrain
> from posting pictures if not necessary.
> Thank you

My flutter doctor -v output was:

[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale
    en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/seamuskean/Developer/flutter
    • Framework revision cc949a8e8b (6 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/seamuskean/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment] 2019-11-12 07:46
Hi again @Sgk3217 
could you please provide also the output of `flutter run --verbose` ?
It would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by WB3Tech** [comment] 2019-11-12 19:54
@iapicca , I ran into the same issue, here is the output of commands:


[my-user-name]@My-MacBook-Pro hello_layouts % flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/[my-user-name]/Documents/DevTools/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/[my-user-name]/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

 
ideviceinfo returned an error:                



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:228:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)



[my-user-name]@My-MacBook-Pro hello_layouts % flutter run --verbose
[  +22 ms] executing: [/Users/[my-user-name]/Documents/DevTools/flutter/] git log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/Users/[my-user-name]/Documents/DevTools/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a0916
[  +18 ms] executing: [/Users/[my-user-name]/Documents/DevTools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [/Users/[my-user-name]/Documents/DevTools/flutter/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +88 ms] executing: [/Users/[my-user-name]/Documents/DevTools/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +245 ms] executing: /Users/[my-user-name]/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/[my-user-name]/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +11 ms] executing: /Users/[my-user-name]/Documents/DevTools/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[+1892 ms] "flutter run" took 2,169ms.
ideviceinfo returned an error:



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:228:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#5      DeviceManager.getDevices (package:flutter_tools/src/device.dart:126:11)
#6      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:169:34)
<asynchronous suspension>
#7      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:515:48)
<asynchronous suspension>
#8      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:279:21)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1500:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#46     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by WB3Tech** [comment] 2019-11-12 19:59
@iapicca , as a work around, I went into the Mac System Preferences --> Security & Privacy, and at the bottom where it says "Apps Downloaded From", I have selected "App Store and Identified Developers".  Underneath that, there was a message asking to allow flutter.dev to access the "ideviceinfo" and I allowed it.

**Comment by jmagman** [comment] 2019-11-13 02:53
@christopherfujino The libimobiledevice binaries should be signed as of [v1.9.1+hotfix.4](https://github.com/flutter/flutter/pull/41504), right?

**Comment by jmagman** [comment] 2019-11-13 02:56
Probably the same as https://github.com/flutter/flutter/issues/42969.

**Comment by woreshiper** [comment] 2019-11-13 11:02
same here this my flutter doctor report
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale
    en-SD)
⢿
Sending crash report to Google.
⣻Crash report sent (report ID: 2a22c8e0667e5ed1)
Oops; flutter has exited unexpectedly.
 
Checking Java status is taking a long time...⣻Unhandled exception:
Invalid argument(s): Cannot find executable for /Users/worshiper/Desktop/development/tools/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#12     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#23     _doctorText (package:flutter_tools/runner.dart:201:19)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _doctorText (package:flutter_tools/runner.dart:197:27)
#26     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#28     _createLocalCrashReport (package:flutter_tools/runner.dart:164:37)
#29     _handleToolError (package:flutter_tools/runner.dart:134:33)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#46     Future._complete (dart:async/future_impl.dart:512:7)
#47     Stream.fold.<anonymous closure> (dart:async/stream.dart:801:18)
#48     _rootRun (dart:async/zone.dart:1120:38)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#51     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#52     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#53     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#54     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#55     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#56     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#57     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#58     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#59     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#60     _rootRun (dart:async/zone.dart:1120:38)
#61     _CustomZone.run (dart:async/zone.dart:1021:19)
#62     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#63     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#64     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#65     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#66     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#67     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#68     _rootRun (dart:async/zone.dart:1120:38)
#69     _CustomZone.run (dart:async/zone.dart:1021:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#76     _Uint8ListConversionSink.close (dart:_http/http_impl.dart:577:13)
#77     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#78     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#79     _rootRun (dart:async/zone.dart:1120:38)
#80     _CustomZone.run (dart:async/zone.dart:1021:19)
#81     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#82     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#83     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#84     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#85     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#86     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#87     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#88     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#89     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#90     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#91     _rootRun (dart:async/zone.dart:1120:38)
#92     _CustomZone.run (dart:async/zone.dart:1021:19)
#93     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#94     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#95     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#96     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#97     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#98     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#99     _rootRun (dart:async/zone.dart:1120:38)
#100    _CustomZone.run (dart:async/zone.dart:1021:19)
#101    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#102    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#103    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#104    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#105    _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#106    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#107    _StreamController.close (dart:async/stream_controller.dart:622:5)
#108    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#109    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#110    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#111    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#112    _rootRunUnary (dart:async/zone.dart:1132:38)
#113    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#114    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#115    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#116    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#117    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#118    _StreamController._add (dart:async/stream_controller.dart:640:7)
#119    _StreamController.add (dart:async/stream_controller.dart:586:5)
#120    _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#121    _rootRunUnary (dart:async/zone.dart:1132:38)
#122    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#123    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#124    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#125    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#126    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#127    _StreamController._add (dart:async/stream_controller.dart:640:7)
#128    _StreamController.add (dart:async/stream_controller.dart:586:5)
#129    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#130    _rootRun (dart:async/zone.dart:1120:38)
#131    _CustomZone.run (dart:async/zone.dart:1021:19)
#132    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#133    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#134    _rootRun (dart:async/zone.dart:1124:13)
#135    _CustomZone.run (dart:async/zone.dart:1021:19)
#136    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#137    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#138    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#139    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#140    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by jmagman** [comment] 2019-11-13 18:33
Duplicate of https://github.com/flutter/flutter/issues/42969.
See https://github.com/flutter/flutter/issues/42969#issuecomment-553225752.

@woreshiper You are hitting https://github.com/flutter/flutter/issues/43398

**Closed by jmagman** 2019-11-13 18:33 UTC
Labels: tool, waiting for customer response, ‎‍💻platform-catalina
