### ISSUE TITLE
Flexible text overflow ellipsis (softWrap false)

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#26006] opened 2019-01-03 09:29 UTC
Internal: b/137284394

I want to cut overflowing text with ellipsis (hard, not soft).

```dart
Flexible(
  child: Text(
    'some-text',
    overflow: TextOverflow.ellipsis,
    softWrap: false,
  ),
)
```
Result looks like that:
![bildschirmfoto 2019-01-03 um 10 23 08](https://user-images.githubusercontent.com/40127061/50630638-e45b7280-0f41-11e9-82c0-d0d29d7452a3.png)

The `softWrap: false` has **no impact for TextOverflow.ellipsis**. For the other two options it's working fine:

`overflow: TextOverflow.fade`
![bildschirmfoto 2019-01-03 um 10 22 47](https://user-images.githubusercontent.com/40127061/50630636-e3c2dc00-0f41-11e9-99f8-7b1fde882864.png)

`overflow: TextOverflow.clip`
![bildschirmfoto 2019-01-03 um 10 22 58](https://user-images.githubusercontent.com/40127061/50630637-e45b7280-0f41-11e9-8e02-58d27ca02bf6.png)

**Comment by zoechi** [comment] 2019-01-03 10:21
`softWrap` is for multiline. I'm not sure I understand what you're asking for.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by YAPPDEF** [comment] 2019-01-03 10:35
@zoechi softWrap has an impact for TextOverflow.fade and TextOverflow.clip (if false, the cut is hard at the end of the available space). For TextOverflow.ellipsis this is not working.

I want my text to be wrapped at the end of the available space and not somewhere in the text where it can be wrapped easily (eg. after a completed word)

**Comment by justinmc** [comment] 2019-01-04 07:30
Good catch, reproduced and confirmed that this is a bug.

![screenshot_1546586840](https://user-images.githubusercontent.com/389558/50677567-73958280-1035-11e9-95a2-91c330a06901.png)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  HomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flexible text overflow ellipsis (softWrap false)'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              ' * Correctly wraps to the next line when overflow is clip. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
              overflow: TextOverflow.clip,
              softWrap: true,
            ),
            Text(
              ' * Correctly wraps to the next line when overflow is fade. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
              overflow: TextOverflow.fade,
              softWrap: true,
            ),
            Text(
              ' * Should wrap to the next line when ellipsis, but it does not! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
              overflow: TextOverflow.ellipsis,
              softWrap: true,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by programmerAbc** [comment] 2019-01-15 07:07
another bug about Text widget,
when i use Text widget which have a very long text with following config inside a fixed size container,overflowed text will render outside of container

overflow: TextOverflow.clip,
softWrap: true,


```
class MyApp5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Layout',
      home: Scaffold(
          body: Container(
        width: double.infinity,
        height: double.infinity,
        child: Center(
            child: Container(
          width: 200,
          height: 100,
          // red box
          child: Text(
            "very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text very long text ",
            overflow: TextOverflow.clip,
            softWrap: true,
          ),
          color: Colors.red,
          padding: new EdgeInsets.all(10.0),
        )),
        color: Colors.orange,
        padding: new EdgeInsets.all(20.0),
      )),
    );
  }
}
```
![2019-01-15 150626](https://user-images.githubusercontent.com/4393948/51164245-49ff1580-18d7-11e9-8ce7-11daabbe7952.jpg)

**Comment by zoechi** [comment] 2019-01-15 07:21
@programmerAbc that looks like #25025

**Comment by zekunyan** [comment] 2019-05-10 06:08
@justinmc I have the same question about Text Widget. When i set `overflow: TextOverflow.ellipsis`, the `softWrap: true` will not work !

**Comment by ravenblackx** [comment] 2019-07-11 17:15
There's an additional concern here, that reusing softWrap to indicate the behavior you want for truncation is problematic. For example, assuming this bug was fixed as described, if I *want*
```
lorem ipsum ratherlongword edge    |
break lorem ipsum ratherlongword   |
edge break lorem ipsum ratherlo... |
```

I set softWrap: true and I get the current behavior
```
lorem ipsum ratherlongword edge    |
break lorem ipsum ratherlongword   |
edge break lorem ipsum...          |
```

I set softWrap: false and I'd get
```
lorem ipsum ratherlongword edge br |
eak lorem ipsum ratherlongword edg |
e break lorem ipsum ratherlongw... |
```

Neither of which resembles what I was hoping for.

I think a better mechanism would be to add TextOverflow.lateEllipsis, TextOverflow.lateFade and TextOverflow.lateClip as options, that way you could select the wrap and overflow behaviors separately.

(Added bonus, it wouldn't alter any pre-existing behaviors.)

**Comment by Kavantix** [comment] 2019-07-30 13:51
I'm also running into this problem with text on a single line, when there is a dash or space in it the ellipsis acts strangely like described above.
Also the size of the text widget is the size it would be if the ellipsis would work as expected.

In my opinion when maxLines is 1 softWrap should have no effect no matter what other settings you have.

**Comment by Hixie** [comment] 2019-08-06 21:38
cc @chunhtai

**Comment by Hixie** [comment] 2019-08-06 21:39
The problem here is that softWrap is implemented as a hack in RenderParagraph. We should implement it in the engine (adding an `enum WrapStyle { softWrap, noWrap }` and an parameter `WrapStyle wrapStyle` to `ParagraphStyle`), and then pass it through from `RenderParagraph`.

fyi @goderbauer @GaryQian

**Comment by chunhtai** [comment] 2019-08-06 22:11
@ravenblackx There is the concern that if we have the lateEllipsis, we might see line jumping around when you changing the maxline for example
if we have
```
one
twoooooooooo
```
if we have maxline = 2
it will looks like
```
one
twooo....
```
however if user change max line to one, the second line will jump up
```
one two....
```

cc @Hixie

**Comment by chunhtai** [comment] 2019-08-06 22:53
Another thing we should figure out is what does softwrap: false mean.
If we set aside the overflow ellipsis, softwrap means the softbreaks at all in our current implementation.

However, It seems like people are expecting softwrap means we hard wrap the paragraph disregarding the word boundaries.

For example
```
a very very very very very very very very long line
```
with softwrap= false, what we currently have will be
```
a very very very very very very very very long line
```

but people expected
```
a very ver
y very ver
y very ver
y very ver
y long line
```

**Comment by chunhtai** [comment] 2019-10-03 16:28
duplicate of https://github.com/flutter/flutter/issues/18761

**Closed by chunhtai** 2019-10-03 16:28 UTC
Labels: a: quality, a: typography, customer: dream (g3), framework
