### ISSUE TITLE
LongPress bleeds through nested InkWells

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#52673] opened 2020-03-16 16:12 UTC
With this sample app:

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Conversation Gallery')),
      backgroundColor: Colors.grey,
      body: Center(
        child: Card(
          child: InkWell(
            onTap: () => null,
            child: Container(
              width: 240,
              height: 180,
              child: InputChip(
                onPressed: () => null,
                label: const Text('Tap'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

- Clicking on "Tap" chip executes ripple animation only on the chip, as expected.
- Clicking on container behind executes animation only on the container.
- Long pressing the chip starts the animation on the chip but then bleeds through to the container, which is unexpected.

**Comment by HansMuller** [comment] 2020-03-16 16:26
@perclasson - is this related to the issue you were trying to fix with https://github.com/flutter/flutter/issues/30182 (reverted in https://github.com/flutter/flutter/pull/43391)?

**Comment by mehmetf** [comment] 2020-03-17 01:35
This got upgraded to blocker because it is causing Material UX review to fail for customer:money.

**Comment by perclasson** [comment] 2020-03-17 10:07
@HansMuller It is not related to https://github.com/flutter/flutter/issues/https://github.com/flutter/flutter/issues/41461. In 41461 the issue was that the delete icon had its ripple behind the chip.

**Comment by shihaohong** [comment] 2020-03-17 16:15
It seems to be more than just `InputChip`s. Even nesting an InkWell in another InkWell reproduced this behavior.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Conversation Gallery')),
      backgroundColor: Colors.grey,
      body: Center(
        child: Card(
          child: InkWell(
            onTap: () => print('outer tap'),
            onLongPress: () => print('outer long press'),
            child: Container(
              width: 240,
              height: 180,
              child: Center(
                child: InkWell(
                  onTap: () => print('inner tap'),
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text('Inkwell child'),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by shihaohong** [comment] 2020-03-17 19:39
This seems related to https://github.com/flutter/flutter/issues/18450

**Comment by dkwingsmt** [comment] 2020-03-17 20:50
Thanks for the investigation! Yes, the problem is that `InkWell`'s splash is started at `TapGR.onTapDown`, which does _not_ require gesture to be accepted, since it can be triggered by `didExceedDeadline`. Therefore `onTapDown` from two gesture recognizers can be called without being prevented by the arena. 

Everything seems to work as they're intended but they combined badly...

**Comment by dkwingsmt** [comment] 2020-03-17 23:02
I think it requires some new mechanism in the gesture system to get `onTapDown`s coordinated. +cc @goderbauer

**Comment by Hixie** [comment] 2020-03-17 23:09
This is a duplicate of https://github.com/flutter/flutter/issues/14417; the solution is probably one of the ideas in https://github.com/flutter/flutter/issues/14417#issuecomment-520264166.

**Comment by shihaohong** [comment] 2020-03-18 17:10
I got something working similarly [using a Stack widget](https://gist.github.com/shihaohong/8f2b1a63d88f2683b5f1434246b10ebb) (props to @justinmc this out yesterday). Would that suffice as a workaround?

**Comment by mehmetf** [comment] 2020-03-18 23:20
That's the workaround we proposed as well. Feel free to close this as a duplicate.

**Comment by shihaohong** [comment] 2020-03-19 00:35
Will close as a duplicate. Thank you!

**Closed by shihaohong** 2020-03-19 00:35 UTC
Labels: customer: money (g3), f: material design, framework, severe: customer blocker
