### ISSUE TITLE
[Go_router] Constructor called when push/go on nested navigation.

### ISSUE THREAD

**Issue by ntaworking** [flutter/flutter#140437] opened 2023-12-20 02:14 UTC
Firstly, sorry for my English.
### Steps to reproduce

1. Implement nested navigation within BottomNavigationBar.
2. Change tab bottom through push/go function.

### Expected results

Constructor of destination page is not called.

### Actual results

Constructor of destination page is called.
Because I initialize several dependency in constructor, I didn't expect this.

### Code sample

<details open><summary>Code sample</summary>

```dart
    // Copyright 2013 The Flutter Authors. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  
  import 'package:flutter/material.dart';
  import 'package:go_router/go_router.dart';
  
  /// This sample app shows an app with two screens.
  ///
  /// The first route '/' is mapped to [HomeScreen], and the second route
  /// '/details' is mapped to [DetailsScreen].
  ///
  /// The buttons use context.go() to navigate to each destination. On mobile
  /// devices, each destination is deep-linkable and on the web, can be navigated
  /// to using the address bar.
  void main() => runApp(const MyApp());
  
  final _parentKey = GlobalKey<NavigatorState>();
  final _shellKey = GlobalKey<NavigatorState>();
  
  final currentIndex = ValueNotifier(0);
  
  /// The route configuration.
  final GoRouter _router = GoRouter(
    navigatorKey: _parentKey,
    initialLocation: '/home',
    routes: <RouteBase>[
      ShellRoute(
        navigatorKey: _shellKey,
        builder: (BuildContext context, GoRouterState state, child) {
          return Scaffold(
            body: child,
            bottomNavigationBar: ListenableBuilder(
                listenable: currentIndex,
                builder: (context, child) {
                  return BottomNavigationBar(
                    items: const [
                      BottomNavigationBarItem(
                        icon: Icon(Icons.home),
                        label: '',
                      ),
                      BottomNavigationBarItem(
                        icon: Icon(Icons.details),
                        label: '',
                      ),
                    ],
                    currentIndex: currentIndex.value,
                    selectedItemColor: Colors.red,
                    onTap: (index) {
                      if (index == 1) {
                        context.go('/details');
                      } else {
                        context.go('/home');
                      }
                      currentIndex.value = index;
                    },
                  );
                }),
          );
        },
        routes: <RouteBase>[
          GoRoute(
            path: '/home',
            builder: (BuildContext context, GoRouterState state) {
              return HomeScreen();
            },
          ),
          GoRoute(
            path: '/details',
            builder: (BuildContext context, GoRouterState state) {
              return DetailsScreen();
            },
          ),
        ],
      ),
    ],
  );
  
  /// The main app.
  class MyApp extends StatelessWidget {
    /// Constructs a [MyApp]
    const MyApp({super.key});
  
    @override
    Widget build(BuildContext context) {
      return MaterialApp.router(
        routerConfig: _router,
      );
    }
  }
  
  /// The home screen
  class HomeScreen extends StatelessWidget {
    /// Constructs a [HomeScreen]
    HomeScreen({super.key}) {
      print('>>>> Called $this constructor');
    }
  
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        appBar: AppBar(title: const Text('Home Screen')),
        body: const Center(
          child: Text('HOME SCREEN'),
        ),
      );
    }
  }
  
  /// The details screen
  class DetailsScreen extends StatelessWidget {
    /// Constructs a [DetailsScreen]
    DetailsScreen({super.key}) {
      print('>>>> Called $this constructor');
    }
  
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        appBar: AppBar(title: const Text('Details Screen')),
        body: const Center(
          child: Text('DETAIL SCREEN'),
        ),
      );
    }
  }


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console


>>>> Called DetailsScreen constructor // When change to DetailsScreen on BottomNavigationBar.

>>>> Called HomeScreen constructor // When back to DetailsScreen on BottomNavigationBar.

>>>> Called DetailsScreen constructor // When change to DetailsScreen on BottomNavigationBar.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.0 23A344 darwin-arm64, locale en-VN)
    • Flutter version 3.16.3 on channel stable at /Users/nta-trongpq/fvm/versions/3.16.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/my_user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/my_user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos                     • darwin-arm64  • macOS 14.0 23A344 darwin-arm64
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by ntaworking** [comment] 2023-12-20 02:18
@chunhtai Can you check this issue.
Thank you!

**Comment by dam-ease** [comment] 2023-12-20 10:58
Thanks for filing this @ntaworking
I can reproduce this on the latest `master` and `stable` channels, but this seems to me as to be working as expected.

> Constructor of destination page is not called.

Is there any reason behind this or a reference to the docs where this shouldn't be called?

**Comment by ntaworking** [comment] 2023-12-21 01:59
> Thanks for filing this @ntaworking I can reproduce this on the latest `master` and `stable` channels, but this seems to me as to be working as expected.
> 
> > Constructor of destination page is not called.
> 
> Is there any reason behind this or a reference to the docs where this shouldn't be called?

@dam-ease Thanks for response.
Assume I initialize `HomeController` and `DetailsController` via `GetIt` package in the constructor.
If the constructor is called twice or more times, that will cause these controllers re-initialize and I will get an error from `GetIt`:
```
already registered inside getit
```

**Comment by chunhtai** [comment] 2023-12-21 22:20
This is expected, since the build method is called during when push and go, creating the widget object should be fast. you should not have side effect in widget constructor.

closing as WAI

**Closed by chunhtai** 2023-12-21 22:20 UTC
Labels: f: routes, package, has reproducible steps, p: go_router, team-go_router, found in release: 3.16, found in release: 3.18

**Comment by ntaworking** [comment] 2023-12-22 02:51
@chunhtai 
Please explain why the constructor's widget is called when I push/ go, and why it's expected behavior?
Obviously it's messing with my logic.
The builder widget should be called if it does not exist in the widget tree. If it already exists, why is it still being called back?
I wonder why a widget that has already been initialized must be reinitialized when pushed/go?
p/s: Sorry for my English.

**Comment by ntaworking** [comment] 2023-12-26 02:20
For those facing this problem, I recommend using `auto_route`.
I use it and this problem does not recur.

**Comment by chunhtai** [comment] 2023-12-26 17:41
@ntaworking 
Widget's build or Builder.builder method can be called for any reason during a frame. It should be fast if nothing changes. If you are writing the build method, it should not have any side effect. If the use case require you to have side effect when widget is first build, you should probably convert it into a statefulwidget and put the logic in initState, or didChangeDependencies if it require inherited look up

**Comment by ntaworking** [comment] 2023-12-27 07:21
OK. I got it.
I will see this as how `go_router` works.
Thanks for response.
I will close this post.

**Comment by ntaworking** [comment] 2024-01-03 06:52
@chunhtai 
>  you should probably convert it into a statefulwidget and put the logic in initState
If use initState function, you will facing the same issue.
When change tab to `UserPage` tab and back to `HomePage` then `HomePage` will re-initialize.
```
final router = GoRouter(
    initialLocation: home,
    routes: [
      ShellRoute(
        builder: (context, state, child) => const DashboardPage(),
        routes: [
          GoRoute(path: home, builder: (context, child) => const HomePage()),
          GoRoute(
            path: user,
            builder: (context, child) => const UserPage(),
            routes: [
              GoRoute(
                path: userDetail,
                builder: (context, child) => const UserDetailPage(),
              ),
            ],
          ),
        ],
      ),
    ],
  );
  ```
  
`print('>>>>>> initState of $this is triggered.');` in this class will triggered multiple times when change tab.
  ```
  class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  @override
  void initState() {
    super.initState();
    print('>>>>>> initState of $this is triggered.');
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            context.push(AppRouter.user);
          },
          child: const Text('To User Page'),
        ),
      ),
    );
  }
}
```
DashBoard class:
```
class DashboardPage extends StatefulWidget {
  const DashboardPage({super.key});

  @override
  State<DashboardPage> createState() => _DashboardPageState();
}

class _DashboardPageState extends State<DashboardPage> {
  final currentIndex = ValueNotifier(0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: ListenableBuilder(
        listenable: currentIndex,
        builder: (context, child) {
          return BottomNavigationBar(
            items: const [
              BottomNavigationBarItem(
                icon: Icon(Icons.home),
                label: '',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.details),
                label: '',
              ),
            ],
            currentIndex: currentIndex.value,
            onTap: (int index) {
              currentIndex.value = index;

            },
            selectedItemColor: Colors.red,
            unselectedItemColor: Colors.black,

          );
        }
      ),
      body: ListenableBuilder(
        listenable: currentIndex,
        builder: (context, child) {
          return currentIndex.value == 0 ? const HomePage() : const UserPage();
        }
      ),
    );
  }
}
```

**Comment by ntaworking** [comment] 2024-01-03 06:55
<H4>This issue should be considered a bug, not expected behavior.<H4>
