### ISSUE TITLE
Regression: Const constructors don't work for widgets on master

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#44858] opened 2019-11-13 23:40 UTC
The title says it all:
On master, const constructors simply do not work anymore for widgets.

Consider the following snippet:

```dart
// test/my_test.dart
import 'package:flutter/cupertino.dart';

void main() {
  print(identical(const SizedBox(), const SizedBox()));
  print(identical(const A(), const A()));
}

class A  {
  const A();
}
```

executed using `flutter test test/my_test.dart`

This will print:

```dart
false
true
```

when the expected result is:

```dart
true
true
```

This issue happens on the master branch, but not on stable.

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.11.1-pre.39, on Mac OS X 10.14.5 18F132, locale en-FR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.39.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by zanderso** [comment] 2019-11-14 15:42
@HansMuller @a-siva

**Comment by jonahwilliams** [comment] 2019-11-14 15:57
@jacob314 

This only happens when track-widget-creation is enabled

**Comment by jacob314** [comment] 2019-11-14 16:01
This has always been a side effect of the --track-widget-creation.
There isn't a way around it unless we modified the implementation of identical to lie which could have other unintended side effects.

You still get the const canonicalization that matters most for widgets just not full const canonicalization.
For example:
```dart
void main() {
  Widget buildWidget() {
    return const SizedBox()
  }
  var w1 = buildWidget();
  var w2 = buildWidget();
  print(identical(w1, w2));
}
```
will print `true`.

**Comment by jonahwilliams** [comment] 2019-11-14 16:03
This is only a debug mode feature so it wont effect running applications (and it was previously the default for IDEs).

It sounds like  it has some confusing behavior for tests though, so perhaps we should turn it off there?

**Comment by rrousselGit** [comment] 2019-11-14 16:13
It's not just confusing, it's a behavior change, which can generate false negative or false positives.

I noticed this issue because I have a test that looks like:

```dart
await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: const MyConsumer(),
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: const MyConsumer(),
  ),
);

expect(find.text('1'), findsOneWidget);
```

And the test failed on _stable_ but succeeded on _master_.

**Comment by jacob314** [comment] 2019-11-14 16:19
I would instead encourage people to fix any tests that fail with --track-widget-creation and pass without it. Having --track-widget-creation on for tests will let us do a better job showing errors reported as part of tests. 
Something seems a bit odd about your code if you can't find the text '1' in that case but you could with --track-widget-creation off.
My isn't the slightly different MyConsumer widget getting the updated inherited value?

Btw to work around the error you can write:
```dart
const consumer = MyConsumer();
await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: consumer,
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: consumer,
  ),
);

expect(find.text('1'), findsOneWidget);
```

**Comment by rrousselGit** [comment] 2019-11-14 16:40
Of course, this can be worked around by caching the instance manually and not using const.
But that's not the point.

This issue means that `const` behaves differently in debug vs release mode, which is heavily unexpected.

If I didn't have a CI that runs tests on both stable and master, I would have missed that fact and deployed the code in production with a critical bug.

Also, I wouldn't expect people to naturally write the workaround when they can use the `const` variant.
It's unlikely that people will find this issue naturally, and therefore likely that they'll have an unexpected weakness in their tests.

**Comment by rrousselGit** [comment] 2019-11-14 16:42
Outside of tests, this behavior will also confuse debug tools like:
- Android Studio's spinner that show which widgets are rebuilding
- devtools' timeline

**Comment by jacob314** [comment] 2019-11-14 16:43
perhaps the best practice is to generally run tests in both debug and release mode to ensure that code will work in release and debug mode.
You could also easily write code that depends on some other debug only functionality in Flutter. For example, all getters in Flutter that start with the word debug will behave differently in debug and release mode.

**Comment by jacob314** [comment] 2019-11-14 16:44
Based on the very small number of tests in package:flutter that had to be tweaked to work with both --track-widget-creation and without it, I expect this may not actually be a large issue in practice.
Had you previously exclusively run your tests from the command line rather than from an IDE?

**Comment by rrousselGit** [comment] 2019-11-14 16:46
> perhaps the best practice is to generally run tests in both debug and release mode to ensure that code will work in release and debug mode.

As far as I'm aware, there's no way to run widget tests in release mode.

> Had you previously exclusively run your tests from the command line rather than from an IDE?

I only use the command line to run tests

**Comment by jacob314** [comment] 2019-11-14 16:47
I wrote the Android Studio spinners that show which widgets are rebuilding. That *requires* `--track-widget-creation`. That feature is disabled any time this feature is disabled as the data it relies on is unavailable.
Because const widgets created on the same exact source code location have the same const object, that feature works just fine with --track-widget-creation for all common cases.

The impact on the DevTools timeline is minimal. We have benchmarked running the flutter tests with and without --track-widget-creation and there is not a significant performance delta.

**Comment by jacob314** [comment] 2019-11-14 16:49
Less advanced users who run tests from the IDE have been seeing the behavior that caused your test to fail for about a year.

**Comment by rrousselGit** [comment] 2019-11-14 16:50
> Because const widgets created on the same exact source code location have the same const object, that feature works just fine with --track-widget-creation for all common cases.

You mean, it's based on the line the const is invoked?

**Comment by rrousselGit** [comment] 2019-11-14 16:55
I suppose that if it's based on the line used, it's not _too_ bad, due to how `build` works.

Alright, I'll update my CI to also run tests with `--no-track-widget-creation`. But that's still very surprising.

**Comment by jacob314** [comment] 2019-11-14 17:42
Correct, the performance impact in practice is negligible given how build works.

Circling back on the original example. I think there is a bug in `MyConsumer` or `MyInheritedWidget` that this test running with `--track-widget-creation` has exposed so I would really encourage tracking that down rather than ignoring the error. Perhaps there is a missing lifecycle check in your code. As written, I expect you will see failing hot reloads when you change 'value' any time `MyConsumer` is not const or if  you added a little bit of whitespace to the code. You should not write widgets that only work properly if their children are const but it is fine to write widgets that run faster if their children are const.

Here is another way you can write the code so it 
could do that
```dart
Widget buildTree(int value) {
  return MyInheritedWidget(
    value: value,
    child: const MyConsumer(),
  );
}

await tester.pump(buildTree(0));

expect(find.text('0'), findsOneWidget);

await tester.pump(buildTree(1));

expect(find.text('1'), findsOneWidget);
```

**Comment by rrousselGit** [comment] 2019-11-14 17:56
> Circling back on the original example.

That's actually the opposite. There was indeed a bug, but "tack-widget-creation" hid it instead of revealing it – hence the danger.

Because this made `const` widgets rebuild all the time, even when they shouldn't. And that test was asserting that the const widget was indeed rebuilding.
But in reality, in release mode, the widget wasn't rebuilding. The thing is, `--track-widget-creation` forced it to rebuild.

**Comment by rrousselGit** [comment] 2019-11-14 18:01
Maybe `--track-widget-creation` should be disabled by default in a CI environment?

**Comment by rrousselGit** [comment] 2019-11-14 18:12
Alternatively, maybe we need a lint rule for tests, like "avoid_const_widgets_in_test".

**Comment by jacob314** [comment] 2019-11-14 18:17
If you need to write a regression test for a bug that is only exposed due to const then you should write your test like
```dart
Widget buildTree(int value) {
  return MyInheritedWidget(
    value: value,
    child: const MyConsumer(),
  );
}

await tester.pump(buildTree(0));

expect(find.text('0'), findsOneWidget);

await tester.pump(buildTree(1));

expect(find.text('1'), findsOneWidget);

```
That will match the behavior in a typical app with and without --track-widget-creation for that example.
In the more typical cases, writing const widgets in tests is generally harmless so the lint would be a bit heavy handed and would conflict with other lints telling you to use const when possible.

**Comment by rrousselGit** [comment] 2019-11-14 18:22
>  the lint would be a bit heavy handed and would conflict with other lints telling you to use const when possible.

That's already a problem because of another issue related to consts anyway: https://github.com/dart-lang/sdk/issues/38934
This coverage issue already conflicts with "prefer_const".
So maybe "prefer_const" should just ignore widgets in the test folder. Then a "avoid_const_widgets_in_test" wouldn't conflict with "prefer_const"

**Comment by rrousselGit** [comment] 2019-11-14 18:29
More broadly, my main concern about this issue is that `provider` recommends to use `const MyWidget` quite heavily.

So quite like:

```dart
await tester.pump(
  MyProvider(
    value: 0,
    child: const MyConsumer(),
  ),
);
```

can be used quite often.

I'll mention it on the readme of `provider` just in case. But it's likely that users of `provider` will fall for this too.

**Comment by jacob314** [comment] 2019-11-14 23:46
@pq Ok I have an idea for a lint that won't false positive too much.
The lint will just warn about defining exactly the same widget as a constant expression at two locations in the same test. That will fix the mystery failures but not false positive on the other more harmless cases where adding an `const` in a test will behave as expected.

**Comment by jacob314** [comment] 2019-11-15 00:49
i don't think the label "severe-regression" is accurate given this has been enabled for a year in IDEs without a bug report.

**Comment by rrousselGit** [comment] 2019-11-16 19:15
Just thinking about it:

Would it be possible to wrap these constructor calls in a fake function instead?

Such that:

```dart
await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: const MyConsumer(),
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: const MyConsumer(),
  ),
);

expect(find.text('1'), findsOneWidget);
```

is replaced by:

```dart
MyConsumer _myConsumer() => const MyConsumer();

await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: _myConsumer(),
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: _myConsumer(),
  ),
);

expect(find.text('1'), findsOneWidget);
```

This would still give the location of where the widget was instantiated, but it wouldn't have such an unexpected impact.

**Comment by jacob314** [comment] 2019-11-17 00:57
yes that is an equally fine way to ensure that the MyConsumer widget used in the test is identical.

**Comment by rrousselGit** [comment] 2019-11-17 01:51
I think there's a misunderstanding.
I'm suggesting that the "track-widgets" flag induce such transformation automatically, not that we'd write that manually.

Something similar to a Babel script for example

**Comment by jacob314** [comment] 2019-11-17 03:29
You don't want to introduce that transformation automatically as you have defeated the purpose of track-widget-creation in that you no longer know where the `MyConsumer` widget was created.
Now both `MyConsumer` widget show up as being created on line 1 of the snippet instead of at lines 4 and 12.

**Comment by rrousselGit** [comment] 2019-11-17 10:46
We would still know that they are created on line 4 and 12 instead of 1 using the stacktrace.

The location of where they were created would be the second entry on the stacktrace instead of the first entry, which points to line 4 & 12.

**Comment by jacob314** [comment] 2019-11-17 17:57
We should document how the kernel transformer works so people have a better mental model of what is going on. The kernel transformer is not relying on the stacktrace at all to add that information. That is a great thing as using the stacktrace would be far too slow to enable this by default in debug mode and wouldn't solve the const issue anyway as even if you captured the stack traces you would have no way of dealing with conflicts where the same const widget is created at multiple locations because both const widgets would correspond to identical objects.
What is really happening is the kernel transformer (similar to a Java bytecode transformer) is directly injecting the creation locations as an extra hidden named argument to the widget constructors. The result of running the kernel transformer is that your source code is conceptually rewritten as:
```dart
await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: const MyConsumer(location: 4),
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: const MyConsumer(location: 11),
  ),
);

expect(find.text('1'), findsOneWidget);
```

That refactor to use a helper function will result in the following code which clarifies why the creation locations no longer match the locations in the build methods.
```dart
MyConsumer _myConsumer() => const MyConsumer(location: 1);

await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: _myConsumer(),
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: _myConsumer(),
  ),
);

expect(find.text('1'), findsOneWidget);
```

Some more background: if we using stacktraces that still would work as we can't associate the stack traces correctly to the constant object as both constant objects would be identical so the best we could say is the locatio is one of a list of values.

What we could do would be intentionally leave the creation locations ambiguous for cases where there are multiple widgets in the same file with the same const expression. This would mean that we would generate the code:
```dart
await tester.pump(
  MyInheritedWidget(
    value: 0,
    child: const MyConsumer(location: [4,11]),
    location: 2,
  ),
);

expect(find.text('0'), findsOneWidget);

await tester.pump(
  MyInheritedWidget(
    value: 1,
    child: const MyConsumer(location: [4,11]),
    location: 9,
  )
);

expect(find.text('1'), findsOneWidget);
```
Here we would now know that we don't know the exact location of the MyConsumer constructors but we could guess it by disambiguating based on the location of the parent (MyInheritedWidget). This would make the const canonicalization of const objects within a single library work robustly but would still break const cannonicalization across files. The main cost is we would need extra heuristics to disambiguate the creation locations based on the locations of their parents which might have some confusing false positives in debugging tools like the inspector.

**Comment by zanderso** [comment] 2019-11-18 17:16
> We should document how the kernel transformer works so people have a better mental model of what is going on.

@jacob314 Where should we put that documentation?

**Comment by jacob314** [comment] 2019-11-18 17:25
Here's the issue tracking adding documentation for this.
https://github.com/flutter/website/issues/3247

**Comment by zanderso** [comment] 2019-11-18 17:35
Thanks! I'll go ahead and close this one, and interested folks can track the documentation issue.

**Closed by zanderso** 2019-11-18 17:35 UTC
Labels: a: annoyance, severe: new feature, tool
