### ISSUE TITLE
Windows application does not display window when windows directory was generated with `flutter create . --platforms=windows`

### ISSUE THREAD

**Issue by TUGTEN** [flutter/flutter#116699] opened 2022-12-08 05:41 UTC
Flutter Doctor:
```
> flutter doctor -v
[√] Flutter (Channel master, 3.7.0-4.0.pre.38, on Microsoft Windows
    [Version 10.0.22000.1098], locale en-US)
    • Flutter version 3.7.0-4.0.pre.38 on channel master at
      C:\Users\XXXXX\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 521028c808 (8 hours ago), 2022-12-07
      13:46:17 -0800
    • Engine revision 67254d6e4b
    • Dart version 2.19.0 (build 2.19.0-467.0.dev)
    • DevTools version 2.20.0

[√] Windows Version (Installed version of Windows is version 10 or
    higher)

[√] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
    • Android SDK at C:\Users\XXXXX\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at   
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome  
      executable.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools
    2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual       
      Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio      
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\XXXXX\AppData\Local\Programs\Microsoft VS    
      Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft       
      Windows [Version 10.0.22000.1098]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge  
      108.0.1462.42

[√] HTTP Host Availability
    • All required HTTP hosts are available
```
Steps to Reproduce: 
1. `flutter clean  .`
2. Delete all platform folders eg:- `android`, `windows`, `web`, etc .
3. `flutter create  .  --platform windows`
4. `flutter build windows`
5. Launch build/windows/runner/Release/application.exe

The application successfully launches (Task Manager confirms the process) however, fails to open a window. This Project runs perfectly fine in debug mode.

After looking at `windows/runner/main.cpp`, it was found that the `Win32Window::window.createAndShow()` function was split into `Win32Window::window.create()` and `Win32Window::window.show()` but the `flutter create  .  --platform windows` fails to generate this in the main.cpp.

This is the default `main.cpp`:

```
...
  if (!window.Create(L"XXXXXX", origin, size))
  {
    return EXIT_FAILURE;
  }

  window.SetQuitOnClose(true);

  ::MSG msg;
  while (::GetMessage(&msg, nullptr, 0, 0))
  {
    ::TranslateMessage(&msg);
    ::DispatchMessage(&msg);
  }

  ::CoUninitialize();
  return EXIT_SUCCESS;
...
```

Fixing it this way works:
```
  if (!window.Create(L"XXXXX", origin, size))
  {
    return EXIT_FAILURE;
  }


//Fix Begin: Use the Show method
  if (!window.Show())
  {
    return EXIT_FAILURE;
  }
//Fix End
  
  window.SetQuitOnClose(true);

  ::MSG msg;
  while (::GetMessage(&msg, nullptr, 0, 0))
  {
    ::TranslateMessage(&msg);
    ::DispatchMessage(&msg);
  }

  ::CoUninitialize();
  return EXIT_SUCCESS;
```

**Comment by exaby73** [comment] 2022-12-08 11:16
## Triage report

I can reproduce this. Initially, when generating the project, the `main.cpp` has `CreateAndShow` and after deleting `.\windows` then running `flutter create . --platforms=windows`, the `main.cpp` only has the `Create` method.

Reproduced on `Master (3.7.0-4.0.pre.38)`

**Comment by stuartmorgan** [comment] 2022-12-08 17:11
main.cpp is only supposed to have `Create()`; `Show()` is in runner/flutter_window.cpp as a first frame callback handler. Is your Flutter application throwing an exception before first run in release mode?

> Reproduced on Master (3.7.0-4.0.pre.38)

@exaby73 Did you reproduce the main window not showing up, or only the code inspection of main.cpp? Because the latter isn't a bug.

**Comment by loic-sharma** [comment] 2022-12-08 20:31
+1 to Stuart's comment. Here's that first frame callback that shows the window: https://github.com/flutter/flutter/blob/003608f182ff93fa83596c57bfb43c43ce8c0c4d/examples/hello_world/windows/runner/flutter_window.cpp#L34-L36

Could you verify that code is there? It's possible you ran into this issue by updating `runner/main.cpp` but not `runner/flutter_window.cpp`. I wasn't able to reproduce this issue using these steps on the latest master commit:

```
flutter create z
cd z
Remove-Item android -Recurse -Force ; Remove-Item windows -Recurse -Force ; Remove-Item windows -Recurse -Force
flutter create . --platform windows
flutter run -d windows --release
```

This opened a Window as expected.

**Comment by stuartmorgan** [comment] 2022-12-08 21:56
I checked since I was curious if my intuition about possible ways of getting this was correct, and it is the case that the flow change transformed very early exceptions (e.g., something in `main` throwing before `runApp`, which I've seen people do leading to "empty window" issue reports) from "an empty window opens and nothing ever draws in it" to "no window ever opens".

So I strongly suspect this is a bug in the specific project's Dart code, not in the local copy of `flutter_window.cpp`.

**Comment by exaby73** [comment] 2022-12-09 09:35
Yeah I can open a window. If the code generated being different from when the project is initially generated is not a bug, then this issue does not seem valid to me. @TUGTEN as per https://github.com/flutter/flutter/issues/116699#issuecomment-1343423975, this is mostly probably an issue with the code in your project. I am closing this issue but if you are able to reproduce this issue in a new Flutter project and can provide detailed reproduction steps, please comment with those and I can reopen the issue. Thank you

**Closed by exaby73** 2022-12-09 09:35 UTC
Labels: tool, platform-windows, a: desktop, has reproducible steps, P4, found in release: 3.3, found in release: 3.7

**Comment by AlexSensey** [comment] 2023-01-28 12:46
For me, after the build, the project from the folder (exe file) is launched only the first time. It does not start the next time, but there are processes in the task manager.
exe debug file runs without problems. Created other projects from scratch, same problem.
I tried to run it on other computers, and there, too, only the first run, then everything. After renaming the folder, it starts again and also once.

**Comment by riccardo-lomazzi** [comment] 2023-02-27 22:14
I can confirm this issue happens to me as well on Flutter 3.7.0, with a project created on 2.10.
I've upgraded to Flutter 3.7.5 and tried to implement the Version Information and Dark Mode for Windows 11 fixes, so I've deleted the following files:

- `windows/runner/CMakeLists.txt`
- `windows/runner/win32_window.cpp`
- `windows/runner/win32_window.h`
- `windows/runner/Runner.rc`

and then ran `flutter create --platforms=windows . -v --org=MyOrg`

What happened is that it generated all the files correctly, minus the `win32_window.cpp` file, where the following instruction was missing from the `Create` method, before `return true;`:

https://github.com/flutter/flutter/blob/003608f182ff93fa83596c57bfb43c43ce8c0c4d/examples/hello_world/windows/runner/flutter_window.cpp#L34-L36

I hope this gets fixed for anybody who tries to create a Windows project.

**Comment by stuartmorgan** [comment] 2023-02-27 22:47
@riccardo-lomazzi 

> What happened is that it generated all the files correctly, minus the `win32_window.cpp` file, where the following instruction was missing from the `OnCreate` method, before `return true;`:

Not having that line is the correct behavior, as explained above.

If you replace arbitrary sub-portions of the template, there is no guarantee that the result will work. If you want to create a hybrid of old and new parts of the runner, it's up to you to do so in a way that creates a working application.

**Comment by MakinoharaShoko** [comment] 2023-03-11 17:38
I have created a new flutter application using flutter new project. It works fine in debug mode, but after release, it only starts the application process but does not show the window (the flutter application can be found in task manager). The way to reproduce this is to create a new flutter application using the vs code plugin, then run `flutter build windows`.

**Comment by MakinoharaShoko** [comment] 2023-03-15 10:19
> I have created a new flutter application using flutter new project. It works fine in debug mode, but after release, it only starts the application process but does not show the window (the flutter application can be found in task manager). The way to reproduce this is to create a new flutter application using the vs code plugin, then run `flutter build windows`.

I found a simple way to solve it, but I think this can only be a temporary solution.
```c++
...
  if (!window.Create(L"XXXXX", origin, size))
  {
    return EXIT_FAILURE;
  }
// Add this line can show the window.
window.Show();
```

In addition，I see the callback in `flutter_window.cpp` called the Show method, but it is not in effect.
https://github.com/flutter/flutter/blob/003608f182ff93fa83596c57bfb43c43ce8c0c4d/examples/hello_world/windows/runner/flutter_window.cpp#L34-L36

I tried to print a log in the callback
```c++
  flutter_controller_->engine()->SetNextFrameCallback([&]() {
    std::cout<<"Callback"<<std::endl;
    this->Show();
  });
```
However, no log is printed.
![image](https://user-images.githubusercontent.com/30483415/225264706-ef5795b0-5faa-4fc5-922f-a810eccdef0f.png)

The `Callback` log outputted normally in debug mode.
![image](https://user-images.githubusercontent.com/30483415/225279796-e949ad33-7301-4178-8837-1f299205197f.png)
