### ISSUE TITLE
[add to app] Keypad is overlapping on TextFormField when add to app Android

### ISSUE THREAD

**Issue by DisIsGAndhi** [flutter/flutter#47107] opened 2019-12-16 05:07 UTC
We have implemented bottom sheet in our application. Bottom sheet have some TextFormFields, so in order to enter some text we need keyboard so bottom sheet has to go up with some bottom padding. So for that i have calculated keyboard height and giving padding dynamically when presence of keyboard is there. It works fine in flutter application. But after attaching to android application height returning zero as we are using routes in application.That means its not getting re builded after keyboard presence. So can anyone help with this.

Steps to reproduce:

-> Add Flutter application to existing android application
-> Create a bottom sheet along with some TextFormFields
-> Click on that field then keyboard will open but it overlaps on the bottom sheet.

flutter doctor.
```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.13.6 17G9016, locale en-IN)
    • Flutter version 1.9.1+hotfix.6 at /Users/gandhi/Downloads/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gandhi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment] 2019-12-16 13:01
Hi @DisIsGAndhi 
can you please provide your `flutter run --verbose` 
and a minimal code sample or the steps to reproduce the problem?
Thank you

**Comment by DisIsGAndhi** [comment] 2019-12-17 05:01
Steps to reproduce:

-> Add Flutter application to existing android application
-> Create a bottom sheet along with some TextFormFields
-> Click on that field then keyboard will open but it overlaps on the bottom sheet.

**Comment by sumujain1995** [comment] 2019-12-17 12:15
Also suffering the same kind of issue while using routes, I have ListView which contains textFormFields and when keyboard appears on clicking on any textFormField ListView  is not scrolling up so that the textFormField is visible.
With the same structure but without using routes, ListView is getting scrolled.

**Comment by xster** [comment] 2019-12-18 21:32
Is it that the widget isn't rebuilding on the framework side or we're incorrectly reporting the safe area / insets like https://github.com/flutter/flutter/issues/46060 seems to point to.

**Comment by DisIsGAndhi** [comment] 2019-12-20 06:36
@iapicca and @xster 
     clone the projects from links given below
Flutter :
https://github.com/DisIsGAndhi/TextFormField-Example.git
Android:
https://github.com/rahuldevanavar91/flutter_demo_existing_app.git

After running these projects you can see two applications installed namely flutter and android.
Now you can see the difference after clicking on TextFormField.

**Comment by rahuldevanavar91** [comment] 2019-12-20 06:52
@iapicca @xster @dnfield 
The issue is keypad is overlapped with the text form field for add to app.

Reprodicible code 
Flutter : [https://github.com/DisIsGAndhi/TextFormField-Example.git]
Android: https://github.com/rahuldevanavar91/flutter_demo_existing_app.git

when we flutter directly keypad is not overlapping with text form filed,  it scrolls up.

but same  code added android add top, keypad is overlapping with text form field

**Comment by xster** [comment] 2020-01-07 05:52
I suspect it's the same issue as https://github.com/flutter/flutter/issues/46060

**Comment by rahuldevanavar91** [comment] 2020-01-15 12:23
@xster @dnfield  any updates on this

**Comment by matthew-carroll** [comment] 2020-01-29 23:01
@rahuldevanavar91 I looked at the example Android project you linked, but that project is using the old v1 of the Android embedding, not the new v2 embedding:

https://github.com/rahuldevanavar91/flutter_demo_existing_app/blob/master/app/src/main/java/com/news/android/view/activity/MainActivity.java

Would you mind migrating your app to the v2 embedding and then let us know if this issue still happens?

**Comment by matthew-carroll** [comment] 2020-02-12 23:22
I'm going to tentatively close this issue assuming that the problem does not exist in the v2 embedding. If it does, please re-open the ticket with appropriate `flutter doctor` output and a minimal project that reproduces the issue.

**Closed by matthew-carroll** 2020-02-12 23:22 UTC
Labels: a: existing-apps, a: text input, engine, framework, severe: regression, waiting for customer response, ▣ platform-android
