### ISSUE TITLE
Idle App is Crashing - SIGSEGV

### ISSUE THREAD

**Issue by pyetti** [flutter/flutter#25717] opened 2018-12-23 18:38 UTC
The app starts fine, but crashes after sitting idly for a couple minutes.

**Terminal output**
```
Initializing hot reload...
Syncing files to device LM Q610 FGN...
Reloaded 6 of 461 libraries in 26,698ms.
I/FirebaseAuth(24969): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(24969): [FirebaseAuth:] Preparing to create service connection to gms implementation
F/libc    (24969): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 25204 (com.deyvoo), pid 24969 (com.deyvoo)

Build fingerprint: 'lge/cv5a_lao_com/cv5a:8.1.0/OPM1.171019.019/182981732f2ca:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 24969, tid: 25204, name: com.deyvoo  >>> com.deyvoo <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0 8affd974  r1 8affd9c0  r2 624b69dc  r3 00000008
    r4 8affd968  r5 8d88d8e4  r6 8bb40021  r7 e8b4b660
    r8 efc3b130  r9 efc3b130  sl efc382f0  fp e8b4b6a0
    ip 8affdfbc  sp e8b4b09c  lr ef201cd3  pc aa5aedc0  cpsr 600d0010
backtrace:
    #00 pc 00018dc0  /system/lib/libc.so (sigsetjmp+136)
    #01 pc ef201cd1  <unknown>
Lost connection to device.

```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/peteryetti/development/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/peteryetti/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/devTools/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/devTools/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/devTools/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • LM Q610 FGN • LMQ610TA35997ea • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Details**
```
Dependencies 
- flutter: 1.0.0+1
- firebase_auth: 0.6.6
- cloud_firestore: 0.8.2+3
- firebase_storage: 1.0.4
- google_sign_in: ^3.2.4
```
Android Config
- I have to set `multiDexEnabled true` in `app/build.gradle` due to `cloud_firestore` dependency

**Comment by vipinagrahari** [comment] 2019-03-18 06:50
Any progress on this issue?

**Comment by daveparks23** [comment] 2019-03-26 00:29
I am having the same issue on the same device.  Thanks for any help.

**Comment by thenotoriousdev** [comment] 2019-04-02 20:39
+1 I am also having the same issue of app crashing consistently. Please let me know if someone comes up with some solution.

**Comment by anuj7sharma** [comment] 2019-04-03 12:13
Facing same issue while hitting API

Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 28546

**Comment by tensor-programming** [comment] 2019-05-03 20:30
Seeing the same issue myself.

**Comment by kroikie** [comment] 2019-10-13 18:36
@pyetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/531. Any further collaboration will be done there.

**Comment by bernaferrari** [comment] 2019-10-13 21:44
This issue has no relation to firebase.

**Comment by iapicca** [comment] 2019-10-22 13:56
Given this [comment ](https://github.com/FirebaseExtended/flutterfire/issues/531#issuecomment-541462787)I'm reopening this issue.

Hi @pyetti
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-15 12:30
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 12:30 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: crash, transferred, waiting for customer response

**Comment by mraleph** [comment] 2020-03-23 22:06
Duplicate of #27077
