### ISSUE TITLE
Hide the soft keyboard when using the physical keyboard

### ISSUE THREAD

**Issue by taehyongi** [flutter/flutter#89340] opened 2021-09-02 04:06 UTC
I am a Korean developer. Please forgive me for my poor English.

I'm using Textfield to type with an external bluetooth keyboard.
In the emulator, input is done well with the keyboard of the PC, not the soft keyboard.
However, when I connected to an actual Android device and typed on a Bluetooth keyboard, the same problem as the attached video occurred. (My device is Samsung gallaxy s10e)
As in the video, each time you press a key, the soft key flashes and appears and disappears repeatedly.

![KakaoTalk_20210902_125834068](https://user-images.githubusercontent.com/6735863/131780026-6b401b7c-9269-4c9b-a01f-5763cdfca619.gif)

Any way to fix it?

[source code]

I have created a new very simple project.

```
import 'package:flutter/material.dart';

class KeyboardTest extends StatefulWidget {
  @override
  _KeyboardTestState createState() => _KeyboardTestState();
}

class _KeyboardTestState extends State<KeyboardTest> {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: Container(
      padding: EdgeInsets.symmetric(horizontal: 30),
      child: TextField(),
    ));
  }
}
```

**Comment by TahaTesser** [comment] 2021-09-02 08:55
Hi @taehyongi 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/44681
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-02 08:55 UTC
Labels: in triage

**Comment by taehyongi** [comment] 2021-09-06 02:19
> Hi @taehyongi
> I see there's an open issue addressing the case you described.
> Please follow up on that issue, Closing as duplicate of #44681
> If you disagree, please write in the comments and I will reopen it.
> Thank you

I agree to close the issue.
Do you have specific plans to fix the issue?

**Comment by aleripe** [comment] 2021-09-11 06:03
I have the same problem and it really affects my users as it's a writing app and most of the job is done on an external keyboard. Is there a workaround at the moment?
