### ISSUE TITLE
Pigeon plugin: Is it possible to add api docs over each public method?

### ISSUE THREAD

**Issue by prasadsunny1** [flutter/flutter#113021] opened 2022-10-06 10:25 UTC
## Use case
I am using pigeon plug-in. I was wondering if I can write documentation for each public method using ///.

**Comment by stuartmorgan** [comment] 2022-10-06 14:08
Duplicate of https://github.com/flutter/flutter/issues/53191.

**Closed** 2022-10-06 15:17 UTC
Labels: in triage
