### ISSUE TITLE
Cursor always at the front when first typing some emojis

### ISSUE THREAD

**Issue by shaqima123** [flutter/flutter#50563] opened 2020-02-11 14:36 UTC
## Steps to Reproduce

The cursor often is stuck at the beginning of the TextField when first typing some emojis 

Repro:

Open any flutter TextField 
Type emoji characters, preferably ones with zero-width-joiners such as 👩‍🚀
Cursor is stuck at front, and tapping in the text works (new text shows up correctly, backspacing works) but the cursor does not appear in the right spot.

this is familiar with the issue #24266 but not the same at all, such as he says the nation flags will cause this problem, but i can't reproduce it.

I have tried many emojis to reproduce, and I found that these emojis would cause the problem,and I printed out the code units to look for the law.

👩‍🚀,[55357, 56425, 8205, 55357, 56960] runes:3,length:5

👩‍❤️‍💋‍👩,[55357, 56425, 8205, 10084, 65039, 8205, 55357, 56459, 8205, 55357, 56425] runes:8,length:11

👨‍👩‍👦‍👦,[55357, 56424, 8205, 55357, 56425, 8205, 55357, 56422, 8205, 55357, 56422] runes:7,length:11
👨🏾‍🤝‍👨🏻,[55357, 56424, 55356, 57342, 8205, 55358, 56605, 8205, 55357, 56424, 55356, 57339] runes:7,length:12

👨‍👦,[55357, 56424, 8205, 55357, 56422] runes:3,length:5

👩‍👦,[55357, 56425, 8205, 55357, 56422] runes:3,length:5

it seems that the emojis which make use of zero width joiners,(code 8205),will easily cause the problem,but not all. I also found that these emojis wont cause the problem,such as:

👩‍❤️‍👨,[55357, 56425, 8205, 10084, 65039, 8205, 55357, 56424] runes:6,length:8
🏌🏿‍♀️,[55356, 57292, 55356, 57343, 8205, 9792, 65039] runes:5,length:7
🏊‍♀️,[55356, 57290, 8205, 9792, 65039] runes:4,length:5
🏄🏻‍♂️,[55356, 57284, 55356, 57339, 8205, 9794, 65039] runes:5,length:7
🇨🇳,[55356, 56808, 55356, 56819] runes:2,length:4

so, what kind of emojis will cause it and why these problem occurs？
**Expected results:** 
expect the cursor can stay at the correct position.
**Actual results:** 
![image](https://user-images.githubusercontent.com/15865350/74246012-d66c4980-4d1e-11ea-8c7d-537af90edd1f.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by HansMuller** [comment] 2020-02-11 16:32
CC @GaryQian  @justinmc

**Comment by justinmc** [comment] 2020-02-11 21:42
@shaqima123 What channel are you on and what keyboard are you using?  I'm not seeing this bug on master when using Gboard on a physical Pixel 2.  If I search for one of the emojis listed in the keyboard and insert it, I can then continue typing and the cursor goes in the correct place.

**Comment by shaqima123** [comment] 2020-02-12 03:41
@justinmc I tried it on the Channel stable, v1.12.13+hotfix.8, and my system is iOS 13.3.1.(it also occurs in iOS 12). I used the official system keyboard of emoji. 
It will cause the bug only when you typing the first emoji string in the textfield, if you continue typing and the cursor will go in the correct place. You can try this emoji 👩‍🚀,and you will see the result as the image above.

**Comment by justinmc** [comment] 2020-02-19 00:12
Thanks, I was able to reproduce this on an iOS 13 simulator using those steps.  I'll add this to my list of text input bugs.

**Comment by justinmc** [comment] 2020-04-21 20:00
@TahaTesser Are you sure this is a regression, and do you know when it started if so?

**Comment by TahaTesser** [comment] 2020-04-22 08:58
Hi @shaqima123 
I must've labelled it regression since mentioned issue is older than this issue. Older issue has been closed for a while.

**Comment by justinmc** [comment] 2020-04-22 18:28
@TahaTesser Thanks, I missed that issue reference.  It's close enough, I'll keep the regression flag for now.

It looks like this bug should be fixed when https://github.com/flutter/flutter/pull/53381 is done.

**Comment by TahaTesser** [comment] 2020-07-08 14:36
@justinmc 
Is this safe to close? since PR look like merged
Thank you

**Comment by justinmc** [comment] 2020-07-08 15:28
Unfortunately it's not fixed.  I just tried it and the bug still exists.  We should have everything we need to fix it at least, now that #53381 is merged.

**Comment by VladyslavBondarenko** [comment] 2020-07-29 08:53
Persists with current master `1.21.0-6.0.pre.90`. Tried with iOS 13.6 simulator

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/dev/flutter
    • Framework revision 531ee9452a (85 minutes ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by mazzonem** [comment] 2022-10-14 09:39
This issue is still happening on the latest stable (3.3.4)

**Comment by maheshmnj** [comment] 2022-12-30 22:52
Reproducible on stable 3.3 and master 3.7

https://user-images.githubusercontent.com/31410839/210116539-57e7d155-19e1-4f58-8d6d-b5c711c91900.mov


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.all(16.0),
              child: TextField(),
            ),
            ElevatedButton(
                onPressed: () {
                  FocusScope.of(context).unfocus();
                },
                child: const Text('Unfocus'))
          ],
        ),
      );
}

```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by gnprice** [comment] 2023-03-11 08:01
This reproduces for me on Android, too, in the same way as on iOS.

I've investigated and have a draft fix. I'll send a PR soon.

**Comment by gnprice** [comment] 2023-03-12 01:56
> I've investigated and have a draft fix. I'll send a PR soon.

This is #122480.

**Comment by gnprice** [comment] 2023-03-12 02:23
> I also found that these emojis wont cause the problem,such as:

For three of these emoji the issue actually reproduces for me:

> 🏌🏿‍♀️,[55356, 57292, 55356, 57343, 8205, 9792, 65039] runes:5,length:7
> 🏊‍♀️,[55356, 57290, 8205, 9792, 65039] runes:4,length:5
> 🏄🏻‍♂️,[55356, 57284, 55356, 57339, 8205, 9794, 65039] runes:5,length:7

just like it does for the other emoji mentioned.

For these two, I confirm the issue doesn't reproduce:

> 👩‍❤️‍💋‍👩,[55357, 56425, 8205, 10084, 65039, 8205, 55357, 56424] runes:6,length:8
> 🇨🇳,[55356, 56808, 55356, 56819] runes:2,length:4

The pattern there is that their length is a power of 2. The reason that affects the repro is this logic:

https://github.com/flutter/flutter/blob/5887b430c815a7802935511120f23db7c3aa3986/packages/flutter/lib/src/painting/text_painter.dart#L1111-L1115

The issue is triggered only when the search in that loop reaches past the beginning of the text. When the emoji's length is a power of 2, the search eventually tries exactly the whole emoji, and stops there before going any farther.

The original report of this issue was several years ago, so it's quite possible that the behavior was different then.

**Closed** 2023-03-28 03:16 UTC
Labels: a: text input, severe: regression, framework, f: material design, passed first triage, has reproducible steps, found in release: 3.3, found in release: 3.7
