### ISSUE TITLE
`dart fix` is not detecting auto-fixable problems for Flutter

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#94267] opened 2021-11-26 23:50 UTC
I'm filing the issue here since most of the undetected problems appear to be for flutter specific lints such as:
- Prefer const with constant constructors. 
- Use key in widget constructors.
- Avoid unnecessary containers.
 
**To reproduce:**
- create a new flutter project
- remove `const` keyword in line 27 (i.e. `home: MyHomePage(title: "Flutter Demo Home Page"),`)
- run `flutter analyze` to see the problem or it'll appear in the IDE problems tab. 
- run `dart fix --dry-run` _(edited: I had `flutter` here by mistake)_
- It'll report `Nothing to fix!` 

**version:**
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by mamuseferha** [comment] 2021-11-29 09:19
Hi @osaxma, this looks like a dart issue. Please file this in the dedicated repository https://github.com/Dart-Code/Dart-Code/issues

Closing this as it is not a flutter issue, if you disagree please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-11-29 09:19 UTC
Labels: in triage

**Comment by DanTup** [comment] 2021-11-29 10:09
@mamuseferha just fyi - the repo linked above is for the _VS Code extension_ for Dart/Flutter, the repo for the Dart SDK (which contains the `"dart fix"` command) is https://github.com/dart-lang/sdk.

For issues that seem to only occur in VS Code, Dart-Code is the right repo - but if they can be reproduced in other editors (like Android Studio/IntelliJ) or from the command line with `dart` or `flutter` commands, it's usually not.

It's not always obvious though, so if you're ever unsure if something may be the VS Code extension or not and want my opinion, feel free to ping me :-)

**Comment by mamuseferha** [comment] 2021-11-29 10:31
Thank you for the clarification @DanTup
