### ISSUE TITLE
Flutter Ios Simulator in catalina material not showing

### ISSUE THREAD

**Issue by shirokun20** [flutter/flutter#68442] opened 2020-10-18 15:42 UTC
I have tired flutter in catalina 10.15.7 with xcode 12 not showing... but with xcode 11 working

<img width="520" alt="Screen Shot 2020-10-18 at 22 48 13" src="https://user-images.githubusercontent.com/15245975/96373028-20ea7380-1194-11eb-8aeb-f20421a37c8f.png">

**Comment by aissat** [comment] 2020-10-18 18:03
@shirokun20 same issues #68434

**Comment by sidrao2006** [comment] 2020-10-19 02:10
Duplicate of #68399

Hey @shirokun20 
I found an open issue addressing this problem, please close this issue and follow up over there.

Thanks

**Closed** 2020-10-19 02:35 UTC
