### ISSUE TITLE
Remove the hotkey 't' terminal command to show widget tree

### ISSUE THREAD

**Issue by AvatarDevs** [flutter/flutter#75994] opened 2021-02-14 04:53 UTC
no one i have ever talked to willingly uses this hotkey. It's always accidental, followed by a quick sentence across the office "man thats so annoying, i hate when i press that."  and quite frankly, a lot of mental cursing, and a strong experience of anger. "Why is this happening", i ask myself.  "theres the widget inspector, i dont even need this".  It runs, no way to stop it, often printing hundreds and hundreds of lines. Quitting the terminal and relaunching is my only path towards solace. 

Please, for the love of god, remove the terminal command 't'

**Comment by nt4f04uNd** [comment] 2021-02-14 06:31
workaround - use ide instead of terminal =)

**Comment by jonahwilliams** [comment] 2021-02-14 20:33
Duplicate of https://github.com/flutter/flutter/issues/33184

**Closed by jonahwilliams** 2021-02-14 20:33 UTC
