### ISSUE TITLE
TextField max length property and  inputFormatters: [LengthLimitingTextInputFormatter(10)] not working.They can't limited text lenght.

### ISSUE THREAD

**Issue by KhayyamA47** [flutter/flutter#65625] opened 2020-09-11 10:55 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by KhayyamA47** [comment] 2020-09-11 10:56
And it happened after i update Flutter.

**Comment by darshankawar** [comment] 2020-09-11 11:31
Hi @KhayyamA47,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by KhayyamA47** [comment] 2020-09-11 12:02
[✓] Flutter (Channel master, 1.22.0-2.0.pre.80, on Mac OS X 10.15.4 19E287, locale az-US)
    • Flutter version 1.22.0-2.0.pre.80 at /Users/voida/Downloads/flutter
    • Framework revision 5a2153d340 (2 weeks ago), 2020-08-26 04:16:07 -0400
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/voida/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • Mi MIX 2 (mobile) • 13e26609   • android-arm64  • Android 9 (API 28)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2020-09-11 13:49
@KhayyamA47 will also need a minimal reproducible code sample.
Thanks.

**Comment by KhayyamA47** [comment] 2020-09-11 13:58
Widget textFields() {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;
    double boxHeight = height * 0.3;
    double textFieldFont = height * 0.022;
    double ovalTextFields = height * 0.05;
    double iconSize = height * 0.03;
    double iconWidth = height * 0.044;

    return Container(
        height: boxHeight,
        width: width,
        child: MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaleFactor: 1.0,
          ),
          child:
          Column(
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Container(
                      width: width * 0.8,
                      child: TextField(
                          maxLength: 15,
                          maxLengthEnforced: true,
                          cursorColor: Colors.white,
                          controller: textController,
                          inputFormatters: [
                            LengthLimitingTextInputFormatter(15),
                          ],
                          focusNode: Theme.of(context).platform == TargetPlatform.android ? null : _nodeText,
                          style: TextStyle(color: Colors.white, fontSize: textFieldFont),
                          decoration: InputDecoration(
                            filled: true,
                            contentPadding: EdgeInsets.only(left: textFieldFont + iconSize, top: textFieldFont, bottom: textFieldFont, right: textFieldFont),
                            fillColor: Colors.white30,
                            hintStyle: TextStyle(color: Colors.white, fontSize: textFieldFont),
                            focusedBorder: OutlineInputBorder(
                              borderSide: BorderSide(color: Color(0x000000)),
                              borderRadius: BorderRadius.circular(ovalTextFields),
                            ),
                            enabledBorder: UnderlineInputBorder(
                              borderSide: BorderSide(color: Color(0xff4DC4C4C4)),
                              borderRadius: BorderRadius.circular(ovalTextFields),
                            ),
                          ),
                          keyboardType: TextInputType.text)),
                  Container(
                    margin: EdgeInsets.only(top: textFieldFont, left: textFieldFont / 2),
                    width: iconWidth,
                    child: Icon(
                      Icons.account_box,
                      size: iconSize,
                      color: Colors.red,
                    ),
                  )
                ],
              ),
            ],
          ),
        ));
  }

**Comment by KhayyamA47** [comment] 2020-09-11 14:27
No, it's not my own method.Even i remove 
inputFormatters: [
                            LengthLimitingTextInputFormatter(15),
                          ] this, max length property not working.

**Comment by darshankawar** [comment] 2020-09-14 06:39
@KhayyamA47 I tried your code on latest master and was able to see the field limiting the text after 15 chars.

[65625.mp4.zip](https://github.com/flutter/flutter/files/5216523/65625.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.136, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.136 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 53f9653e6b (3 days ago), 2020-09-10 20:20:04 -0700
    • Engine revision e831433a20
    • Dart version 2.10.0 (build 2.10.0-112.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

```

</details>

**Comment by goashwin** [comment] 2020-09-15 17:05
maxLength is not enforcing on Android for us. We've tried dev and master channels both. Not able to figure out why. Works on iOS.

**Comment by MichaelPriebe** [comment] 2020-09-30 19:29
I am having this problem on dev, LETTERS will not enforce, anything else will enforce. Besides the point there seems to be ghost characters that you have to delete if you typed anything after it was enforced.
https://gfycat.com/SimilarSphericalAlaskanmalamute

**Comment by darshankawar** [comment] 2020-10-05 10:39
There's similar open issue describing this case, [67236](https://github.com/flutter/flutter/issues/67236).
Please follow-up there for updates.
Closing this as duplicate.

**Closed by darshankawar** 2020-10-05 10:39 UTC
Labels: in triage, waiting for customer response

**Comment by haduyphuong** [comment] 2020-12-07 03:10
It it same
