### ISSUE TITLE
Track timers in failing widget tests

### ISSUE THREAD

**Issue by saltmueller** [flutter/flutter#37786] opened 2019-08-07 15:58 UTC
Currently, when a widget test fails because there are "unexpected" timers running, it can get cumbersome to track down where the offending timers are actually created. 

This is the assert: 

https://github.com/flutter/flutter/blob/677b7c15c3883f90de4d9a3f5267033e8fffa766/packages/flutter_test/lib/src/binding.dart#L1052

It would be useful to provide information where the timers were create, e.g. for each timer that is created in FakeAsync the stacktrace could be captured. When the assert fails that information could be dumped.

**Comment by goderbauer** [comment] 2019-08-14 22:31
Dupe of https://github.com/flutter/flutter/issues/4237.

**Closed by goderbauer** 2019-08-14 22:31 UTC
