### ISSUE TITLE
Instalei o package:mask_text_input_formatter/mask_text_input_formatter.dart

### ISSUE THREAD

**Issue by fhlsoares** [flutter/flutter#66206] opened 2020-09-20 07:02 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (URI scheme not allowed): "file:///C:/flutter/carros_web/lib/pages/despesa/despesa_insert.dart"
```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:188:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:155:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:180:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel master, 1.20.0, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)
    • Flutter version 1.20.0 at C:\src\flutter
    • Framework revision 5995661777 (3 months ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\androidstudio
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:/androidstudio
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at C:\Users\Fábio\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Edge       • edge       • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 599566177736e6b30af922a8f06e8a260acafc36

**Comment by iapicca** [comment] 2020-09-20 12:59
possible solutions
https://github.com/flutter/flutter/issues/64492#issuecomment-680100884
https://github.com/flutter/flutter/issues/59924#issuecomment-678287123

duplicate of https://github.com/flutter/flutter/issues/65376

**Comment by darshankawar** [comment] 2020-09-21 08:18
Hi @fhlsoares,
Please try above listed solutions  to see if they work for you.
Also, there's similar open issue describing your case, as listed above [65376](https://github.com/flutter/flutter/issues/65376)
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-21 08:18 UTC
