### ISSUE TITLE
Latest flutter in master TextFormField not working on Android

### ISSUE THREAD

**Issue by mjaffa-figure** [flutter/flutter#26626] opened 2019-01-16 06:28 UTC
## Steps to Reproduce

1. Put a TextFormField anywhere in the application
2. Run on Android
3. Can't click on the TextFormField to edit the field.

```
flutter doctor -v    
[✓] Flutter (Channel master, v1.1.10-pre.76, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.10-pre.76 at /Users/matthewjaffa/flutter
    • Framework revision 684d050791 (24 minutes ago), 2019-01-16 01:01:51 -0500
    • Engine revision fdfb0e72f0
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 d9944433af)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/matthewjaffa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM N950U         • --                     • android-arm64 • Android 8.0.0 (API 26)
    • Matthew’s iPhone • --- • ios           • iOS 12.1.2
    • iPhone 6s Plus   • 7C8EE389-CCF6-4EBA-9AC4-AD0FE4498B3D     • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by Hixie** [comment] 2019-01-16 07:05
I have a fix in https://github.com/flutter/flutter/pull/26629

**Comment by zoechi** [comment] 2019-01-16 07:14
Duplicate of #26563

**Comment by xster** [comment] 2019-01-16 20:39
Sorry for the breakage. @zoechi, I think this is still a dupe of #26563.

**Closed by xster** 2019-01-16 20:39 UTC
Labels: f: material design, framework, severe: regression, waiting for PR to land (fixed), ▣ platform-android, ⚠ TODAY
