### ISSUE TITLE
Infinite loop in TextField with some inputFormatters (iOS)

### ISSUE THREAD

**Issue by fredriks** [flutter/flutter#13961] opened 2018-01-06 14:20 UTC
## Steps to Reproduce

1. Run [examples/flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) on iOS (physical device or simulator)
2. Open "Text fields" under "Material Components"
3. Enter one or more numbers into the "Phone Number" field
4. Hit backspace
5. The input field goes into a loop where it repeatedly removes and adds the last character.

![output](https://user-images.githubusercontent.com/1616517/34640550-151e4aa8-f2fd-11e7-98ce-540f065effef.gif)

## Logs

```
[        ] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[        ] An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8103/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+253478 ms] [DEVICE LOG] 2018-01-06 15:52:03.678301+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4633, Description: Loading Preferences From System CFPrefsD For Search List
[+13924 ms] [DEVICE LOG] 2018-01-06 15:52:17.602866+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4634, Description: Loading Preferences From System CFPrefsD For Search List
[   +8 ms] [DEVICE LOG] 2018-01-06 15:52:17.611380+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4635, Description: Loading Preferences From System CFPrefsD For Search List
[ +234 ms] [DEVICE LOG] 2018-01-06 15:52:17.845901+0200  localhost Runner[24134]: (UIKit) Can't find keyplane that supports type 5 for keyboard iPhone-PortraitChoco-PhonePad; using 2024220450015396792_PortraitChoco_iPhone-Complex-Pad_Default
[  +63 ms] [DEVICE LOG] 2018-01-06 15:52:17.900540+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4636, Description: Loading Preferences From System CFPrefsD For Search List
[        ] [DEVICE LOG] 2018-01-06 15:52:17.901476+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4637, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.901791+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4638, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.901973+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc4639, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.902255+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463a, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.902480+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463b, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.902748+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463c, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.903001+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463d, Description: Updating Key-Value Observers Of Preferences
[   +1 ms] [DEVICE LOG] 2018-01-06 15:52:17.903195+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463e, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2018-01-06 15:52:17.903453+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc463f, Description: Updating Key-Value Observers Of Preferences
[   +1 ms] [DEVICE LOG] 2018-01-06 15:52:17.906445+0200  localhost Runner[24134]: (Runner) Created Activity ID: 0xc58b0, Description: Loading Preferences From System CFPrefsD For Search List
[        ] [DEVICE LOG] 2018-01-06 15:52:17.907627+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] activate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1
[        ] [DEVICE LOG] 2018-01-06 15:52:17.907921+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] activate feedback engine 0x6000000bec60, clientCount: 0 -> 1
[        ] [DEVICE LOG] 2018-01-06 15:52:17.907992+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] activating engine
[        ] [DEVICE LOG] 2018-01-06 15:52:17.908409+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] feedback engine <_UIFeedbackSystemSoundEngine: 0x6000000bec60: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating
[        ] [DEVICE LOG] 2018-01-06 15:52:17.910005+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] feedback engine <_UIFeedbackSystemSoundEngine: 0x6000000bec60: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running
[+3359 ms] [DEVICE LOG] 2018-01-06 15:52:21.273835+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] activate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2
[        ] [DEVICE LOG] 2018-01-06 15:52:21.273875+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] activate feedback engine 0x6000000bec60, clientCount: 1 -> 2
[        ] [DEVICE LOG] 2018-01-06 15:52:21.274731+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] deactivate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1
[        ] [DEVICE LOG] 2018-01-06 15:52:21.274782+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] deactivate feedback engine 0x6000000bec60, clientCount: 2 -> 1
[+2656 ms] [DEVICE LOG] 2018-01-06 15:52:23.928718+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] activate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2
[        ] [DEVICE LOG] 2018-01-06 15:52:23.928799+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] activate feedback engine 0x6000000bec60, clientCount: 1 -> 2
[   +6 ms] [DEVICE LOG] 2018-01-06 15:52:23.929589+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] deactivate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1
[   +2 ms] [DEVICE LOG] 2018-01-06 15:52:23.929682+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] deactivate feedback engine 0x6000000bec60, clientCount: 2 -> 1
[+3667 ms] [DEVICE LOG] 2018-01-06 15:52:27.608269+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] activate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2
[        ] [DEVICE LOG] 2018-01-06 15:52:27.608319+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] activate feedback engine 0x6000000bec60, clientCount: 1 -> 2
[   +2 ms] [DEVICE LOG] 2018-01-06 15:52:27.609012+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:FeedbackActivation] deactivate generator <_UIKeyboardFeedbackGenerator: 0x600000125fa0: prepared=1> with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1
[        ] [DEVICE LOG] 2018-01-06 15:52:27.609054+0200  localhost Runner[24134]: (UIKit) [com.apple.UIKit:Feedback] deactivate feedback engine 0x6000000bec60, clientCount: 2 -> 1
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-SE, channel master)
    • Flutter at /Users/fsimon/flutter
    • Framework revision a414fb458d (28 hours ago), 2018-01-06 12:02:33 +0100
    • Engine revision 12e0e38a8b
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.8d7219a5b6a7c2505ff57f23e7cf80da4c724512

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/fsimon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • iPhone X                  • 1C6CECD0-0E72-489F-90D7-197A80D82B98 • ios         • iOS 11.2 (simulator)
```

**Comment by fredriks** [comment] 2018-01-06 14:52
I did some digging around and since the [formatter in question](https://github.com/flutter/flutter/blob/c669c62ecf138bb4038928a72550bc6ae2c6d79a/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart#L213-L252) works on Android I'm inclined to think the issue might be with the framework or the engine.

Looking at the messages passed between the framework and the engine just to compare Android and iOS. When hitting backspace iOS goes into a loop where the engine sends a `TextInputClient.updateEditingState` and the framework sends back a `TextInput.setEditingState`, adding and removing the last character.

Based on `updateEditingState` I found that reverting [flutter/engine#3995](https://github.com/flutter/engine/pull/3995) fixes the loop but I don't know if that might introduce regressions.

Since it works fine with some formatters (such as the `WhitelistingTextInputFormatter.digitsOnly`) the issue might be related to the fact that Android and iOS passes slightly different values for selection, composing and affinity for the same operations, causing the formatter to throw the framework and the engine out of sync.

**Comment by Hixie** [comment] 2018-01-07 19:21
cc @cbracken

**Comment by fredriks** [comment] 2018-01-08 11:55
Whops! This appears to be a duplicate of  #12782 and #12347. Feel free to close 😄

**Comment by cbracken** [comment] 2018-01-08 16:42
Thanks for reporting, and for your analysis! Closing as dupe of the above. Please feel free to thumbs-up those issues (which we use to help prioritise issues)

**Closed by cbracken** 2018-01-08 16:42 UTC
Labels: prod: text input

**Comment by Abgaryan** [comment] 2018-05-30 08:45
@cbracken  Issue still exists
