### ISSUE TITLE
split_config.arm64_v8a.apk!libflutter.so

### ISSUE THREAD

**Issue by RelappsStudio** [flutter/flutter#146888] opened 2024-04-17 12:27 UTC
### Steps to reproduce

No steps available. Crash tracking unfortunately cannot catch this one.

### Expected results

That app does not crash

### Actual results

Since April there started happening visible crashes in play console.
<img width="624" alt="image" src="https://github.com/flutter/flutter/assets/69040991/30d7de07-df68-4d96-addb-b75c3aa98036">
```
backtrace:
  #00  pc 0x0000000000094184  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x0000000000438844  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #02  pc 0x00000000004654cc  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #03  pc 0x0000000000451d1c  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #04  pc 0x0000000000448e78  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #05  pc 0x0000000000448f6c  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #06  pc 0x0000000000449240  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #07  pc 0x0000000000448c34  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #08  pc 0x00000000006d14e0  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #09  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #10  pc 0x00000000006cc224  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #11  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #12  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #13  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #14  pc 0x00000000006cc4d4  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #15  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #16  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #17  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #18  pc 0x00000000006cc224  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #19  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vnmy.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #20  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #21  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #22  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #23  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #24  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #25  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #26  pc 0x00000000006cc224  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #27  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #28  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #29  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #30  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #31  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #32  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #33  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #34  pc 0x00000000006cc224  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #35  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #36  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #37  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #38  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #39  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #40  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #41  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #42  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #43  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #44  pc 0x00000000006cc224  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #45  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #46  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #47  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #48  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #49  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #50  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #51  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #52  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #53  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #54  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #55  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #56  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #57  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #58  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #59  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #60  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #61  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #62  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #63  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #64  pc 0x00000000006d1730  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #65  pc 0x00000000006ccaa8  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #66  pc 0x00000000006d0028  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #67  pc 0x00000000006ca9f0  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #68  pc 0x000000000078ff10  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #69  pc 0x000000000078fa38  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #70  pc 0x0000000000790d28  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #71  pc 0x000000000079082c  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #72  pc 0x000000000079c638  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #73  pc 0x00000000004660c4  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #74  pc 0x0000000000469e18  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #75  pc 0x0000000000018e8c  /system/lib64/libutils.so (android::Looper::pollInner(int)+1276)
  #76  pc 0x000000000001892c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+124)
  #77  pc 0x00000000000192a4  /system/lib64/libandroid.so (ALooper_pollOnce+100)
  #78  pc 0x0000000000469f28  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #79  pc 0x0000000000467e04  /data/app/~~DFe8M2lpgeWA_BpYXM2SbQ==/vn.my.application-gxo4-ConCGxeljI7Ej9z3w==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #80  pc 0x0000000000101d0c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #81  pc 0x0000000000095ae0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
  
  sometimes the stack trace differs for example:
  

backtrace:
  #00  pc 0x0000000000051a3c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x0000000000438844  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #02  pc 0x00000000004654cc  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #03  pc 0x0000000000451fac  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #04  pc 0x0000000000909c48  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #05  pc 0x0000000000790030  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #06  pc 0x000000000078fa38  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #07  pc 0x0000000000790d28  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #08  pc 0x000000000079082c  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #09  pc 0x00000000004660c4  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #10  pc 0x0000000000469e18  /data/app/~~w_h4x678uJlFbuS893htvg==/vn.my.application-Hjz_sA77nJi772SqP7Kdaw==/split_config.arm64_v8a.apk!libflutter.so (BuildId: 3514e66bbee2689909245c0b27f3f66a56add544)
  #11  pc 0x0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #12  pc 0x0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #13  pc 0x00000000001589b4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #14  pc 0x000000000046c514  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
```
  
  These are devices that are affected by this:
  
<img width="1274" alt="image" src="https://github.com/flutter/flutter/assets/69040991/d1a995aa-bdfb-4e1e-a7f7-acd82ae3aba6">

The issue really started to affect users since beginning of April
<img width="975" alt="image" src="https://github.com/flutter/flutter/assets/69040991/c6d2ea42-4878-464a-b9a7-4e06d315322a">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.19.0, on macOS 13.5.2 22G91 darwin-arm64, locale en-CZ)
    ! Flutter version 3.19.0 on channel [user-branch] at /Users/username/tools/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment] 2024-04-18 06:54
Thanks for the report @RelappsStudio 
Based on the stacktrace you shared, it most probably looks similar to https://github.com/flutter/flutter/issues/125090.
Are you using platform-views in your app ?
In your stacktrace, do you see any line `Check failed: fml::jni::CheckException` ?

**Comment by RelappsStudio** [comment] 2024-04-18 09:05
yes we do use platform views and the error is happening on this thread 

[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1594)] Check failed: fml::jni::CheckException(env).

**Comment by darshankawar** [comment] 2024-04-18 11:52
Thanks for the update. Closing this as duplicate of https://github.com/flutter/flutter/issues/125090. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-04-18 11:52 UTC
Labels: in triage
