### ISSUE TITLE
Text selection bug when typing on iOS

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#66460] opened 2020-09-23 15:19 UTC
![output](https://user-images.githubusercontent.com/6655696/94032750-8c713900-fdc0-11ea-894f-b0dc50e3a730.gif)

When entering text after a selection is made on iOS, the text sporadically becomes selected again for a few seconds. Could not repro on an Android device

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.318, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-DE)
    • Flutter version 1.22.0-10.0.pre.318 at /Users/plg/development/flutter-dev
    • Framework revision 6b39acdc53 (3 hours ago), 2020-09-23 08:27:04 -0400
    • Engine revision 3e7ca5b869
    • Dart version 2.10.0 (build 2.10.0-156.0.dev) 
```

**Comment by LongCatIsLooong** [comment] 2020-09-23 20:22
Duplicate of #63130. The selection highlight is in fact autocorrect highlight.  On iOS it has the same base color as the selection color (but different opacity IIRC).

**Closed by LongCatIsLooong** 2020-09-23 20:22 UTC
Labels: a: text input, f: cupertino, f: material design, platform-ios
