### ISSUE TITLE
SocketException: Connection failed (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by shuyanzi** [flutter/flutter#32602] opened 2019-05-13 06:28 UTC
## Steps to Reproduce
void main() {
  // add interceptors
  dio.interceptors..add(CookieManager(CookieJar()))..add(LogInterceptor());
  (dio.transformer as DefaultTransformer).jsonDecodeCallback = parseJson;
  dio.options.receiveTimeout = 15000;
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
      (client) {
    client.findProxy = (uri) {
      //proxy to my PC(charles)
      return "PROXY xx.xx.xx.xx:8888";
    };
  };
  runApp(MyApp());
}

## Logs

```
flutter: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Permission denied, errno = 13), address = xx.xx.xx.xx, port = 8888
```

**Comment by kangwang1988** [comment] 2019-05-13 08:33
@shuyanzi 
Are you facing this issue when trying to proxy the traffic on your mobile phone with Charles setup on your machine(Mac etc)?

**Comment by shuyanzi** [comment] 2019-05-13 08:41
> @shuyanzi
> Are you facing this issue when trying to proxy the traffic on your mobile phone with Charles setup on your machine(Mac etc)?

yes,I want to see the package information on Charles

**Comment by shuyanzi** [comment] 2019-05-13 08:43
> @shuyanzi
> Are you facing this issue when trying to proxy the traffic on your mobile phone with Charles setup on your machine(Mac etc)?

yes,I want to see the package information on Charles

**Comment by cakipaul** [comment] 2019-05-20 22:56
> If your AndroidManifest.xml is missing this line:
> 
> <uses-permission android:name="android.permission.INTERNET"/>
> ...then when we try to hook up the observatory port we will get an error 13 (permission denied).
> 
> We should catch this case and explain what to do about it.

Duplicate of #2138

**Comment by cakipaul** [comment] 2019-05-20 22:57
If your AndroidManifest.xml is missing this line:
```xml
<uses-permission android:name="android.permission.INTERNET"/>
```
...then when we try to hook up the observatory port we will get an error 13 (permission denied).
We should catch this case and explain what to do about it.

Duplicate of #2138

**Comment by kangwang1988** [comment] 2019-05-26 07:09
@shuyanzi 
I've reproduced this error by removing the ` <uses-permission android:name="android.permission.INTERNET"/>` section, just as @cakipaul  said.
<img width="1671" alt="Screen Shot 2019-05-26 at 3 05 22 PM" src="https://user-images.githubusercontent.com/817851/58378537-e3e27780-7fc7-11e9-9897-ef2cf124b462.png">

When the android.permissions.INTERNET is specified in the AndroidManifest.xml, I've catched the flutter http traffic using Charles, as below:
<img width="1667" alt="Screen Shot 2019-05-26 at 3 03 13 PM" src="https://user-images.githubusercontent.com/817851/58378541-17bd9d00-7fc8-11e9-971a-1afd33f13a0d.png">

I'm closing this issue now.
If you are still seeing this issue, comment below and I will reopen this issue.

**Closed by kangwang1988** 2019-05-26 07:09 UTC

**Comment by shuyanzi** [comment] 2019-05-30 07:46
@kangwang1988 Thank you very much, I add <uses-permission android:name="android.permission.INTERNET"/>, and code as your pic, succeed!
@cakipaul 谢谢你有缘人

**Comment by shuyanzi** [comment] 2019-05-30 09:49
@kangwang1988 但是我请求使用dio时，如下图，为什么抓包不成功呢？
![image](https://user-images.githubusercontent.com/20119779/58624588-288d4c00-8303-11e9-8a46-e93c2cb24bd2.png)

**Comment by mufan2010** [comment] 2020-02-02 07:55
我居然也遇到这样的问题了，debug没问题，

**Comment by JonasCaps** [comment] 2020-06-28 17:49
I am facing the same problem. Your solution does work for me.
![errorrr](https://user-images.githubusercontent.com/34658659/85954538-a937d500-b967-11ea-908a-309cb5b9b12c.png)
