### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by vino144** [flutter/flutter#110168] opened 2022-08-24 12:05 UTC
Oops; flutter has exited unexpectedly: "HttpException: Invalid request method, uri = http://localhost:4444/session".

while running in flutter drive --driver=test_driver/integration_test.dart --target=integration_test/pages/home_page_test.dart -d web-server

I already started the chrome driver in chromedriver --port=4445

In my machine port -4444 running in another task.

Can some help me fix this issue.

**Comment by darshankawar** [comment] 2022-08-24 12:20
Closing this as duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by darshankawar** 2022-08-24 12:20 UTC
Labels: in triage
