### ISSUE TITLE
Why .android folder and .ios folder be covered when I run 'Package Get'

### ISSUE THREAD

**Issue by FitzLu** [flutter/flutter#34701] opened 2019-06-19 06:38 UTC
I create a project, contains .android folder and .ios folder. I write some code in them, but when I modify pubspec.yaml and run 'Package Get', .android folder and .ios folder will be recreated and all my code in them are deleted.

**Comment by jmagman** [comment] 2019-06-19 19:32
Looks like a duplicate of https://github.com/flutter/flutter/issues/32883.

**Closed by jmagman** 2019-06-19 19:32 UTC
