### ISSUE TITLE
Move the platform folders to platfrom folder.

### ISSUE THREAD

**Issue by abinvs-2019** [flutter/flutter#132890] opened 2023-08-19 12:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Its is little bit difficult to mange whole folder structures in a project template. It includes android, iOS, web, windows, macos and every platform folder. Now what i am suggesting is creating a folder for platforms and moving the all platform folders inside to look more organised way.

### Proposal

<img width="249" alt="Screenshot 2023-08-19 at 5 45 59 PM" src="https://github.com/flutter/flutter/assets/77786587/1b376048-fa6d-4e41-aa7a-c2c7951b9d27">

**Comment by stuartmorgan** [comment] 2023-08-19 13:21
Closing as a duplicate of https://github.com/flutter/flutter/issues/71400

**Closed by stuartmorgan** 2023-08-19 13:21 UTC
