### ISSUE TITLE
Android Q error=13, Permission denied.

### ISSUE THREAD

**Issue by kadnan0900** [flutter/flutter#71553] opened 2020-12-02 11:39 UTC
i am using this library flutter_video_compress 0.3.7+8 and i Just change targetSdkVersion 29 to 28 in build.gradle
It worked for me.But when i uploaded the release build on app store and i changed targetSdkVersion 29 and then get this error appear please help me to solve this issue.
```
D/FFmpeg  (29138): ffmpeg is ready!
E/FFmpeg  (29138): Exception while trying to run: [/data/user/0/appus.tagit/files/ffmpeg, -noautorotate, -i, /data/user/0/appus.tagit/app_flutter/Movies/TagitProof/proof1/1606908760998.mp4, -vcodec, h264, -crf, 28, -movflags, +faststart, -vf, scale=1280:-2, -preset:v, ultrafast, -b:v, 1000k, /storage/emulated/0/Android/data/appus.tagit/files/flutter_video_compress/1606908760998.mp4]
E/FFmpeg  (29138): java.io.IOException: Cannot run program "/data/user/0/appus.tagit/files/ffmpeg": error=13, Permission denied
```

**Comment by TahaTesser** [comment] 2020-12-02 12:14
Hi @kadnan0900 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rurico/flutter_video_compress/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-02 12:14 UTC
