### ISSUE TITLE
Rich Text Editor Very important！

### ISSUE THREAD

**Issue by freedemocracy** [flutter/flutter#67039] opened 2020-10-01 08:21 UTC
flutter team so slothful，Haven't implemented this widget for 5 years！

**Comment by darshankawar** [comment] 2020-10-01 08:39
Closing as duplicate of [12675](https://github.com/flutter/flutter/issues/12675)

**Closed by darshankawar** 2020-10-01 08:39 UTC

**Comment by freedemocracy** [comment] 2020-10-01 11:21
> 结束于[12675的副本](https://github.com/flutter/flutter/issues/12675)

Zefyr ----Not a good choice
