### ISSUE TITLE
Unable to log arbitrary unicode characters from iOS

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10218] opened 2017-05-19 22:41 UTC
I printed the semantics tree (press "S" after `flutter run`) to my terminal. When I do that while my app is running on iOS, I get something that's really hard to read:

```
 \M-b\M^T\M^TSemanticsNode(1; Rect.fromLTRB(0.0, 0.0, 320.0, 568.0) scaled by 2.0x)
   \M-b\M^T\M^\SemanticsNode(2; Rect.fromLTRB(0.0, 0.0, 320.0, 568.0))
   \M-b\M^T\M^B \M-b\M^T\M^TSemanticsNode(3; Rect.fromLTRB(0.0, 0.0, 320.0, 568.0); SemanticsAction.tap)
   \M-b\M^T\M^TSemanticsNode(4; Rect.fromLTRB(0.0, 0.0, 320.0, 568.0))
     \M-b\M^T\M^\SemanticsNode(5; Rect.fromLTRB(84.0, 314.0, 236.0, 330.0) (clipped); "Button tapped 0 times.")
     \M-b\M^T\M^\SemanticsNode(6; Rect.fromLTRB(46.5, 36.0, 269.5, 60.0) (clipped); "Flutter Demo Home Page")
     \M-b\M^T\M^\SemanticsNode(7; Rect.fromLTRB(248.0, 496.0, 304.0, 552.0) (clipped); SemanticsAction.tap; "Increment")
     \M-b\M^T\M^TSemanticsNode(8; Rect.fromLTRB(0.0, 0.0, 320.0, 20.0) (clipped); SemanticsAction.tap)
```

The same machine with the same terminal connected to Android looks much nicer and is soo much easier to read:
```
I/flutter (23483): SemanticsNode(0; Rect.fromLTRB(0.0, 0.0, 1440.0, 2392.0))
I/flutter (23483):  └SemanticsNode(1; Rect.fromLTRB(0.0, 0.0, 411.4, 683.4) scaled by 3.5x)
I/flutter (23483):    ├SemanticsNode(2; Rect.fromLTRB(0.0, 0.0, 411.4, 683.4))
I/flutter (23483):    │ └SemanticsNode(3; Rect.fromLTRB(0.0, 0.0, 411.4, 683.4); SemanticsAction.tap)
I/flutter (23483):    └SemanticsNode(4; Rect.fromLTRB(0.0, 0.0, 411.4, 683.4))
I/flutter (23483):      ├SemanticsNode(5; Rect.fromLTRB(134.7, 373.7, 276.7, 389.7) (clipped); "Button tapped 0 times.")
I/flutter (23483):      ├SemanticsNode(6; Rect.fromLTRB(16.0, 40.0, 242.0, 64.0) (clipped); "Flutter Demo Home Page")
I/flutter (23483):      └SemanticsNode(7; Rect.fromLTRB(339.4, 611.4, 395.4, 667.4) (clipped); SemanticsAction.tap; "Increment")
```

Given that the difference is Android vs. iOS with all other variables the same I am suspecting this is a problem with how we process logs from iOS. Maybe we don't support unicode in logs for iOS?

**Comment by goderbauer** [comment] 2017-05-19 22:47
Yeah, looks like its a general unicode logging problem from iOS. I added this line to one of my flutter apps:
```dart
print('Three Spades: ♠♠♠');
```

Running on iOS shows this in the log:
```
Three Spades: \M-b\M^Y\240\M-b\M^Y\240\M-b\M^Y\240
```

Running on Android shows this:
```
I/flutter (24456): Three Spades: ♠♠♠
```

Changing the title to reflect the general problem.

**Comment by goderbauer** [comment] 2017-05-19 22:54
More datapoints:

When I view the device log in the Console app, the characters show up correctly:
![screen shot 2017-05-19 at 3 50 18 pm](https://cloud.githubusercontent.com/assets/1227763/26269705/551e0a48-3cab-11e7-8b4a-8565a2dcb4b6.png)

When viewing the log with `idevicesyslog`, it's messed up again:
```
May 19 15:51:08 iPod-touch Runner(libsystem_asl.dylib)[1216] <Notice>: Three Spades: \M-b\M^Y\240\M-b\M^Y\240\M-b\M^Y\240
```

**Comment by eseidelGoogle** [comment] 2017-09-28 22:04
@cbracken might know, he was in this code recently for iOS 11 compatibility.

**Comment by cbracken** [comment] 2017-10-12 21:53
@goderbauer thanks for the digging. 

Based on the symptoms and the fact that this is working in Console.app, seems likely to be a string encoding issue in `idevicesyslog`. As a quick check, I tried running in the simulator (which uses /usr/bin/log for logging) and things work fine there, which supports this hypothesis.
![screen shot 2017-10-12 at 14 51 33](https://user-images.githubusercontent.com/351029/31521094-14f4a862-af5d-11e7-9bf1-43d9df3139d6.png)

**Comment by goderbauer** [comment] 2017-10-14 04:30
The simulator has a different problem though: https://github.com/flutter/flutter/issues/12544

**Comment by cbracken** [comment] 2017-10-14 05:07
Took a look at that issue. It's purely a `flutter_tools` regex issue unrelated to this one.

**Comment by sfraize** [comment] 2018-01-10 15:54
Just been diagnosing this.   If this is a libmobiledevice problem, it looks like it's being address (or not) over here: https://github.com/libimobiledevice/libimobiledevice/issues/594

Another data-point:

The first line below is what I get out of Console.app on MacOS 10.12.6, and the second line is what I get from idevicesyslog:

default 09:59:01.422838 -0500	Runner	*Unicode-Log_Test: heart: ❤
Jan 10 09:59:01 SMF-iPhone-6s Runner(Flutter)[1101] : *Unicode-Log_Test: heart: \M-b\M^]\M-$

Note that "\M-b\M^]\M-$" are not terminal encoded bytes -- they are the actual 7-bit bytes BACKSLASH / LETTER-M / DASH / LETTER-b / BACKSLASH, etc, coming straight out of idevicesyslog. They come out that way on the screen or when output is redirected to a file. So *something* in the pipeline is processing the unicode high-bytes coming from iOS and mangling them into "printable" 7-bit ascii. I suppose it's theoretically possibly Console.app is re-processing "\M-b..." text-strings back into unicode, but I doubt it.

So either this is a libmobiledevice / idevicesyslog problem, or a flutter/dart problem that only shows up when running from iOS/arm64 code, but not with with Android or x86 simulator code.

**Comment by cbracken** [comment] 2018-01-10 17:12
Based on the discussion on libimobiledevice/libimobiledevice#594, it sounds like they stay out of the string encoding business altogether. As you say, there are a few possibilities: one is that Console.app and possibly `/usr/bin/log` implement some sort of cleverness. It's also possible that one of Flutter's iOS logging mechanisms needs tweaking.

It's worth noting that Flutter uses different code paths and logging mechanisms for each of:
* Android devices and emulators: adb
* iOS physical devices: libimobiledevice
* iOS < 11 simulators: scraping simulator syslog
* iOS >= 11 simulators: /usr/bin/log

I should have logged which iOS version I'd used above. Based on the device name, it was likely iOS 11, in which case, we rely on /usr/bin/log for simulator logs (for iOS 10 and earlier, Flutter reads from syslog).

**Comment by cbracken** [comment] 2018-01-10 17:52
Some additional notes: as seen in the code above, the Dart string to char* conversion is common across all platforms, but the logging calls themselves differ. On iOS, we use syslog calls (as opposed to say, ASL pre-iOS 10 and os_log on iOS 10 and later). 

The syslog RFC [explicitly documents](https://tools.ietf.org/html/rfc5424#section-6.4) that the encoding *should* be UTF-8 and that the application should escape byte values below 32. Apple doesn't document the encoding, but does explicitly state that `syslog` message contents are manipulated as described in the RFC:
> Newlines and other non-printable characters embedded in the message string are printed in an alternate format.  This prevents someone from using non-printable characters to construct misleading log messages in an output file.  Newlines are printed as "\n", tabs are printed as "\t".  Other control characters are printed using a caret ("^") representation, for example "^M" for carriage return.

Also from the RFC:
> If a syslog application encodes MSG in UTF-8, the string MUST start with the Unicode byte order mask (BOM), which for UTF-8 is ABNF %xEF.BB.BF.  The syslog application MUST encode in the "shortest form" and MAY use any valid UTF-8 sequence.

We should verify we include the BOM in the decoding in the engine.

**Comment by sfraize** [comment] 2018-01-10 18:17
Ah, the BOM.   Hadn't thought of security concerns for syslog but that makes sense.  Playing with /usr/bin/syslog, I can generate a UTF-8 heart in the log no problem, but the utility may be adding the BOM, not the underlying API call.   For completeness, I also tested  logging  "\M-b\M^]\M-$" and saw no fancy decoding - came through as text, even in Console.app.

**Comment by cbracken** [comment] 2018-01-10 18:17
Fantastic -- alright. I've confirmed that we're *not* adding the BOM today, so I'll give this a go today and see if it resolves the issue.

**Comment by cbracken** [comment] 2018-01-11 01:44
The bad news: adding the BOM doesn't appear to work. I just get a leading `\M-o\M-;\M-?` logged, which looks like the BOM using the same encoding we see elsewhere.

> For completeness, I also tested logging "\M-b\M^]\M-$" and saw no fancy decoding - came through as text, even in Console.app.

I see that behaviour in Console.app -- similarly I see emoji from Flutter `print()` statements appearing in Console.app, but not on the console. `syslog(1, "\\")` outputs `\134` in the log as read by `idevicesyslog` and `cfgutil`. I haven't tested on a pre-iOS 10 simulator, but I'd expect the same there. 

The escaped backslash suggests they may be doing encoding on their end (e.g. for security reasons descibed on the man page) then decoding in the client (Console.app and /usr/bin/log). The encoding they're using looks pretty simple, a bit of poking at it suggests:
`\M^x`: `x + 0x40` (for bytes in range 0x80 to 0x9f)
`\M-x`: `x + 0x80` (for bytes in range 0xa0 to 0xf7)
`\ddd`: ddd is an octal representation of the byte (used for `\134` (backslash), `\240` (`0xa0`, which would otherwise map to `\M^ `))

It wouldn't be too hard to do similar decoding when dumping the logs from `flutter`, though it'd be nice to (a) find a better way around the issue, or (b) find an API to do the decoding for us in case they change the encoding, and to deal with edge-cases/malformed logs, etc.

**Comment by sfraize** [comment] 2018-01-11 15:53
Another data-point: I just noticed the Observatory doesn't show this problem when getting bytes from iOS/arm64.  I'm guessing it's because it has access to a pure stdout stream vs a syslog stream.

```
flutter_assets:main():stdout> *System:   iOS
flutter_assets:main():stdout> *Version:  11.2.1
flutter_assets:main():stdout> *Virtual:  false
flutter_assets:main():stdout> *HostName: SMF-iPhone-6sp
flutter_assets:main():stdout> *     Release: 17.3.0
flutter_assets:main():stdout> *     Machine: iPhone8,2
flutter_assets:main():stdout> *     Version: Darwin Kernel Version 17.3.0: Mon Nov  6 21:19:15 PST 2017; root:xnu-4570.32.1~1/RELEASE_ARM64_S8000
flutter_assets:main():stdout> HEARTLAND-❤-HEARTLAND no-BOM
flutter_assets:main():stdout> HEARTLAND-❤-HEARTLAND UTF-16 BOM
flutter_assets:main():stdout> ¿HEARTLAND-❤-HEARTLAND UTF-8 BOM
```

**Comment by cbracken** [comment] 2018-01-11 17:17
> I'm guessing it's because it has access to a pure stdout stream vs a syslog stream.

Correct - syslog is just the platform-specific mechanism we use for pushing print statements back to the `flutter` tool for iOS apps. I'm having trouble finding it, but II believe there's an open bug (as suggested by the TODO I'd added in the code) to have the target app host a log service on a port, proxy that port to the host OS, and read Flutter output there instead of via platform-specific logging.

**Comment by cbracken** [comment] 2018-01-12 23:21
I've landed #14075, which fixes this. If Apple ever makes `/usr/bin/log` useable against iOS devices, we should definitely move to that and let them handle the decoding.

**Closed by cbracken** 2018-01-12 23:21 UTC
Labels: ⌘‬ platform-mac, ⌺‬ platform-ios

**Comment by scugn1zz0** [comment] 2019-03-27 20:33
@cbracken 
My flutter app, for some reason can't produce logs (on macos) longer than a certain number of characters. It just truncate the word when the maximum has been reached and append three dots `...`.

Is there a way to get full log on macos from iOS?
Thanks

**Comment by cbracken** [comment] 2019-05-03 06:18
@scugn1zz0 thanks for reporting this -- please file a new issue for this with details since this issue is specific to the character encoding used in Apple's syslogs.
