### ISSUE TITLE
InkWell deactivate() disposes of splashes

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5456] opened 2016-08-17 16:23 UTC
If you have a `Material` that simply changes its position within a list and if it has an ongoing `InkSplash` animation, the splash will be disposed of.

**Comment by Hixie** [comment] 2017-01-04 20:39
https://github.com/flutter/flutter/issues/6751 could be a dupe.

**Comment by dragostis** [comment] 2017-01-05 07:45
To the best of my knowledge, that is probably a dupe since that's how I discovered this bug.

**Comment by eseidelGoogle** [comment] 2017-02-03 19:05
How can I reproduce this to test if this is still true?

**Comment by dragostis** [comment] 2017-02-03 20:55
@eseidelGoogle Interchanging two `InkWell` that have splashes would stop the splashes from rendering. I can try to minimise this tomorrow morning.

**Comment by zoechi** [comment] 2019-01-14 16:05
To reproduce I used

```dart
import 'package:flutter/material.dart';

import 'package:flutter/scheduler.dart' show timeDilation;

void main() {
  timeDilation = 4.0;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> _materials;

  @override
  void initState() {
    const onTapDelay = 120; // to see at least the start of the ripple
    super.initState();
    _materials = [
      Material(
          key: ValueKey('1'),
          child: InkWell(
              onTap: () => Future.delayed(
                  const Duration(milliseconds: onTapDelay),
                  () => setState(() => _materials.add(_materials.removeAt(0)))),
              child: SizedBox(
                child: Center(child: Text('Material 1')),
                height: 150,
              ))),
      Material(
          key: ValueKey('2'),
          child: InkWell(
              onTap: () => Future.delayed(
                  const Duration(milliseconds: onTapDelay),
                  () => setState(
                      () => _materials.insert(0, _materials.removeAt(1)))),
              child: SizedBox(
                child: Center(child: Text('Material 2')),
                height: 150,
              )))
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            Expanded(
              child: ListView(children: _materials.toList()),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by Hixie** [comment] 2020-02-26 00:44
Duplicate of https://github.com/flutter/flutter/issues/6751

**Closed by Hixie** 2020-02-26 00:44 UTC
Labels: a: animation, a: quality, f: material design, framework
