### ISSUE TITLE
drawImage causes Picture.toImage to  fail on WEB 

### ISSUE THREAD

**Issue by kickwaxapps** [flutter/flutter#71848] opened 2020-12-07 16:33 UTC
**Steps to Reproduce**

1. Create a new flutter DartPad and cut and paste the contents of main.dart reference in the gist below.
[https://gist.github.com/kickwaxapps/7e05b0c6b193d93540b80d70457b5463](https://gist.github.com/kickwaxapps/7e05b0c6b193d93540b80d70457b5463)

2. Run the new DartPad

**Expected results:**

Except to see no errors in console, and for `Picture.toImage `to work.

**Actual results:**
Picture.toImage fail with and error.

Browser console log contains the following error:

```
dart_sdk.js:5816 Uncaught (in promise) Error: [object Event]
    

    at Object.createErrorWithStack (dart_sdk.js:4218)
    at Object._rethrow (dart_sdk.js:36441)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36437)
    at Object._microtaskLoop (dart_sdk.js:36297)
    at _startMicrotaskLoop (dart_sdk.js:36303)
    at dart_sdk.js:32051
```
![image](https://user-images.githubusercontent.com/29279210/101377354-b72b4380-387f-11eb-93c8-5cd3db5934ea.png)

**Comment by darshankawar** [comment] 2020-12-08 06:44
@kickwaxapps 
`Picture.toImage` doesn't seem to support web yet. Please see [this](https://github.com/flutter/flutter/issues/42767) open issue. You may go ahead and close this if the open issue answers your question as why it's failing on web.

**Comment by kickwaxapps** [comment] 2020-12-08 13:44
At the very least the non-support should be reflected in the error message.

Through experimenting, I found that toImage only failed when  Canvas.drawImage*(...)  is included in the picture recorder. (Other Canvas,draw commands did not results in any error) This made me think the problem could be related to the recently closed Image.toBtyeData problem (sry can;t find issue number)

The code above worked in earlier versions of flutter.  I'm happy to close, but it's not at all clear to me that it;s the same issue you referenced.

**Comment by darshankawar** [comment] 2020-12-08 13:55
@kickwaxapps 
`The code above worked in earlier versions of flutter.`. You mean the same code worked in earlier version ? Can you provide the flutter version if possible where it worked and not working in the version you are on along with your current `flutter doctor -v` ?

**Comment by kickwaxapps** [comment] 2020-12-08 15:46
The demo I provided   in Dar pad, which looks to be based on Flutter 1.23.0-18.1.pre Dart SDK 2.10.4. 

(Locally I am using:
Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/jbc/sdk/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta

 and have the same error, but with different code)

But yes the same code I provided worked 6 months ago. Sorry I can;t be sure of the version)


Also I noticed that the comments on https://github.com/flutter/flutter/issues/42767 say that Pictire.toImage has now been implemented. Is it available somewhere?

**Comment by yjbanov** [comment] 2020-12-08 17:37
The HTML renderer (used by DartPad) does not support `Picture.toImage`. CanvasKit renderer does support it, but it requires that the image is downloadable via XHR or `fetch()`, and therefore is subject to CORS rules.

The error in the repro code does not seem to be related to images. It uses `NetworkImage`, which relies on `PaintingBinding` to get to the image codec, which is not available without bootstrapping the framework bindings. I added `WidgetsFlutterBinding.ensureInitialized();` as the first line in the `main()` function and I see that the issue is due to CORS limits on the https://letstalkscience.ca server that's serving the image (when running with `--web-renderer=canvaskit`). This is what Chrome prints in the console:

```
Access to XMLHttpRequest at 'https://letstalkscience.ca/sites/default/files/styles/x_large/public/2020-03/Cow.jpg' from origin 'http://localhost:42713' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I'm documenting how to deal with this situation in this PR: https://github.com/flutter/website/pull/5061.

Closing the issue as there doesn't seem like we can do anything beyond improving docs.

**Comment by yjbanov** [comment] 2020-12-08 17:37
(feel free to reopen if you think my assessment is incorrect)

**Closed by yjbanov** 2020-12-08 17:37 UTC
Labels: in triage

**Comment by kickwaxapps** [comment] 2020-12-08 19:01
Thank you for those details. It's very much appreciated. I added WidgetsFlutterBinding.ensureInitialized() as you indicated, but didn't see any additional warnings.

It might be that it was dumb of me to show a repro using Dartpad as it has added a layer I didn't consider as I was forced to get the image via NetworkImage... In my actual use case I am loading images from the assets folder and I end up  with the same message:  (also running on the web). I don't think CORS would come into play in this scenario. On the other hand, I can't say which renderer I am using. 

dart_sdk.js:5816 Uncaught (in promise) Error: [object Event]
    
    at Object.createErrorWithStack (dart_sdk.js:4218)
    at Object._rethrow (dart_sdk.js:36441)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:36437)
    at Object._microtaskLoop (dart_sdk.js:36297)
    at _startMicrotaskLoop (dart_sdk.js:36303)
    at dart_sdk.js:32051

Locally I am using: 
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] Connected device (2 available)

**Comment by gibahjoe** [comment] 2020-12-13 17:24
Its still an issue that using the default renderer (There is no canvaskit.wasm in the network list so I assume its not canvaskit), Picture.toimage does not work. It throws the exact error that OP posted. 

> Closing the issue as there doesn't seem like we can do anything beyond improving docs.

@yjbanov , I disagree with the above. What can be done is support Picture.toImage on the default renderer or provide an alternative.

**Comment by hatano0x06** [comment] 2020-12-23 04:15
I'm facing the same problem.
I was hoping that a newer version would solve the problem, but it seems not it.

```
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (10 days ago) • 2020-12-13 23:19:13 +0800    
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)
```
