### ISSUE TITLE
[M1] Application won't run on simulator 

### ISSUE THREAD

**Issue by Tejaswgupta** [flutter/flutter#85902] opened 2021-07-05 12:09 UTC
## Steps to Reproduce

Run flutter application on M1 device with MacOS 12 and flutter stable branch
## Logs

<details>
<summary>Logs</summary>

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 74ABA90D-A4AF-43F4-8CF6-5D08BCD775B4
CrashReporter Key:   049F5925-4F1E-898F-F227-6699FD1241BD
Hardware Model:      MacBookPro17,1
Process:             Runner [74009]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/4EF34ACE-C668-417B-A067-12F6E638000E/data/Containers/Bundle/Application/4128C5D8-3AB0-4CA4-943D-1DF8470C17DA/Runner.app/Runner
Identifier:          com.therecspot.recspot.test
Version:             0.9.0 (21)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [72141]
Coalition:           com.apple.CoreSimulator.SimDevice.4EF34ACE-C668-417B-A067-12F6E638000E [5731]
Responsible Process: SimulatorTrampoline [72120]

Date/Time:           2021-07-05 17:36:30.5151 +0530
Launch Time:         2021-07-05 17:36:30.3336 +0530
OS Version:          macOS 12.0 (21A5268h)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes: 0x0000000000000001, 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4310188032
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file                 100e84000-100f4c000    [  800K] r-x/r-x SM=COW  ...t_id=5e5d19d1
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [74009]

Triggered by Thread:  0

Application Specific Information:

Thread 0 Crashed:
0   ???                           	    0x7ff7ffd24118 ???
1   <translation info unavailable>	       0x101013a3c ???
2   dyld                          	       0x2010c2a32 dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 890
3   dyld                          	       0x2010c16b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
4   dyld                          	       0x2010c14b4 start + 388
5   dyld                          	       0x2010bc000 ???

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffd11984 ???
1   ???                           	    0x7ff7ffd29320 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000010906baf8  rcx: 0x0000000000000000  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000109723000
   r8: 0x01d49309683a0006   r9: 0x0000000000000000  r10: 0x0000000109723000  r11: 0x000000010952c010
  r12: 0x0000000000000000  r13: 0x000000010952c060  r14: 0x0000000201130080  r15: 0x0000000000000000
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0x0000000101002d98 tmp1: 0x0000000101002090 tmp2: 0x00000002010dba13

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2010bc000 -        0x201123fff dyld (*) <1051784a-31a4-3307-b922-6e65e511ff69> /usr/lib/dyld

EOF

-----------
Full Report
-----------

{"app_name":"Runner","timestamp":"2021-07-05 17:36:30.00 +0530","app_version":"0.9.0","slice_uuid":"e65cbacf-2b4f-3a34-b833-1c96f7a84185","build_version":"21","platform":7,"bundleID":"com.therecspot.recspot.test","share_with_app_devs":1,"is_first_party":0,"etl_key":"3","bug_type":"309","os_version":"macOS 12.0 (21A5268h)","incident_id":"74ABA90D-A4AF-43F4-8CF6-5D08BCD775B4","name":"Runner"}
{
  "uptime" : 16000,
  "procLaunch" : "2021-07-05 17:36:30.3336 +0530",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 209,
  "modelCode" : "MacBookPro17,1",
  "coalitionID" : 5731,
  "osVersion" : {
    "train" : "macOS 12.0",
    "build" : "21A5268h",
    "releaseType" : "User"
  },
  "captureTime" : "2021-07-05 17:36:30.5151 +0530",
  "incident" : "74ABA90D-A4AF-43F4-8CF6-5D08BCD775B4",
  "pid" : 74009,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "Runner",
  "procPath" : "\/Users\/USER\/Library\/Developer\/CoreSimulator\/Devices\/4EF34ACE-C668-417B-A067-12F6E638000E\/data\/Containers\/Bundle\/Application\/4128C5D8-3AB0-4CA4-943D-1DF8470C17DA\/Runner.app\/Runner",
  "bundleInfo" : {"CFBundleShortVersionString":"0.9.0","CFBundleVersion":"21","CFBundleIdentifier":"com.therecspot.recspot.test"},
  "storeInfo" : {"deviceIdentifierForVendor":"7BF2BB51-03AD-516D-A5E2-52E9A681B88E","thirdParty":true},
  "parentProc" : "launchd_sim",
  "parentPid" : 72141,
  "coalitionName" : "com.apple.CoreSimulator.SimDevice.4EF34ACE-C668-417B-A067-12F6E638000E",
  "crashReporterKey" : "049F5925-4F1E-898F-F227-6699FD1241BD",
  "responsiblePid" : 72120,
  "responsibleProc" : "SimulatorTrampoline",
  "wakeTime" : 337,
  "sleepWakeUUID" : "FEFF3866-4CEC-47AA-9FAA-88D155984039",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4310188032\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file                 100e84000-100f4c000    [  800K] r-x\/r-x SM=COW  ...t_id=5e5d19d1",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":74009},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4310188032\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file                 100e84000-100f4c000    [  800K] r-x\/r-x SM=COW  ...t_id=5e5d19d1",
  "asi" : {"dyld":[]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":2,"task_for_pid":4},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":462985,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":0},"r12":{"value":0},"rosetta":{"tmp2":{"value":8607611411},"tmp1":{"value":4311752848},"tmp0":{"value":4311756184}},"rbx":{"value":4446403320},"r8":{"value":131891957713207302},"r15":{"value":0},"r10":{"value":4453445632},"rdx":{"value":1},"rdi":{"value":0},"r9":{"value":0},"r13":{"value":4451385440},"rflags":{"value":643},"rax":{"value":0},"rsp":{"value":4453445632},"r11":{"value":4451385360},"rcx":{"value":0},"r14":{"value":8607957120,"symbolLocation":0,"symbol":"dyld4::gProcessInfo"},"rsi":{"value":0}},"frames":[{"imageOffset":140703125618968,"imageIndex":0},{"imageOffset":4311824956,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":27186,"symbol":"dyld4::prepareSim(dyld4::RuntimeState&, char const*)","symbolLocation":890,"imageIndex":1},{"imageOffset":22197,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":244,"imageIndex":1},{"imageOffset":21684,"symbol":"start","symbolLocation":388,"imageIndex":1},{"imageOffset":0,"imageIndex":1}]},{"id":462990,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":140703125543300,"imageIndex":0},{"imageOffset":140703125639968,"imageIndex":0}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8607481856,
    "size" : 425984,
    "uuid" : "1051784a-31a4-3307-b922-6e65e511ff69",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1048K resident=0K(0%) swapped_out_or_unallocated=1048K(100%)\nWritable regions: Total=154.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=154.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    732K      180 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       12.8M        6 \nVM_ALLOCATE (reserved)              64K        4         reserved VM address space (unallocated)\n__DATA                              20K        2 \n__DATA_CONST                        92K        2 \n__LINKEDIT                         360K        4 \n__TEXT                             720K        2 \ndyld private memory               1024K        1 \nmapped file                        5.8G       34 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              6.0G      247 \nTOTAL, minus reserved VM space     6.0G      247 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "60c88ac7e7d17206e1f95943"
      },
      "deploymentId" : 250000052
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "60ca460c10d03d047ed95dfe"
      },
      "deploymentId" : 250000082
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "60c8a862e7d17206e1f95953"
      },
      "deploymentId" : 250000112
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 250000092
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro17,1, BootROM 7429.0.133.121.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_wifi, wl0: May 11 2021 22:21:31 version 18.20.284.1.7.8.108 FWID 01-9dd86976
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

```
```

[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-arm, locale en-IN)
    • Flutter version 2.2.3 at /Users/tejasw/dev/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tejasw/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5155e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 4EF34ACE-C668-417B-A067-12F6E638000E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 91.0.4472.114

! Doctor found issues in 2 categories.

```
```

</details>

**Comment by TahaTesser** [comment] 2021-07-05 13:46
Hi @Tejaswgupta 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/85545
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-05 13:46 UTC
Labels: in triage
