### ISSUE TITLE
Error with ': Flutter_paystack: compileDebugKotlin'

### ISSUE THREAD

**Issue by Khurshidbek18** [flutter/flutter#78727] opened 2021-03-21 13:05 UTC
Hi everyone I came across the following error when launching the flutter. I read all the information on the internet but could not find any definite solution. Please help

```
C:\Users\User\AndroidStudioProjects\flutter_app\avex\android>flutter run
Changing current working directory to: C:\Users\User\AndroidStudioProjects\flutter_app\avex
Launching lib\main.dart on Redmi Note 8 in debug mode...
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a depr
ecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\android\src\main\java\com\roughike\facebooklogin\facebooklogin\FacebookLoginPlugin.java uses or overr
ides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (33, 88): Unresolved reference
: VERSION_NAME
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (37, 36): Unresolved reference
: VERSION_CODE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 28s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       153.1s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by iapicca** [comment] 2021-03-21 15:07
@Khurshidbek18 

those seem to me  warnings rather than error (generated by 3rd party plugins)
```bash
Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a depr
ecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\android\src\main\java\com\roughike\facebooklogin\facebooklogin\FacebookLoginPlugin.java uses or overr
ides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (33, 88): Unresolved reference
: VERSION_NAME
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (37, 36): Unresolved reference
: VERSION_CODE
```
and the error

```bash
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.
```

is evidently caused by [flutter_paystack](https://pub.dev/packages/flutter_paystack) which is a 3rd party plugin, 
please open an issue in the dedicated [github](https://github.com/wilburt/flutter_paystack/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by Khurshidbek18** [comment] 2021-03-22 08:45
> @Khurshidbek18
> 
> those seem to me warnings rather than error (generated by 3rd party plugins)
> 
> ```shell
> Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a depr
> ecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\android\src\main\java\com\roughike\facebooklogin\facebooklogin\FacebookLoginPlugin.java uses or overr
> ides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (33, 88): Unresolved reference
> : VERSION_NAME
> e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.2+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (37, 36): Unresolved reference
> : VERSION_CODE
> ```
> 
> and the error
> 
> ```shell
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> ```
> 
> is evidently caused by [flutter_paystack](https://pub.dev/packages/flutter_paystack) which is a 3rd party plugin,
> please open an issue in the dedicated [github](https://github.com/wilburt/flutter_paystack/issues)
> or provide your `flutter doctor -v`, your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

C:\Users\User\AndroidStudioProjects\flutter_app\app>flutter doctor -v
[√] Flutter (Channel master, 2.1.0-13.0.pre.192, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-13.0.pre.192 at C:\src\flutter
    • Framework revision c0bcb4fc16 (2 days ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Redmi Note 8 (mobile) • 11730a78 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)            • edge     • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!

C:\Users\User\AndroidStudioProjects\flutter_app\app>

**Comment by iapicca** [comment] 2021-03-22 08:49
@Khurshidbek18
can you provide the information listed [above](https://github.com/flutter/flutter/issues/78727#issuecomment-803877914) 

> is evidently caused by [flutter_paystack](https://pub.dev/packages/flutter_paystack) which is a 3rd party plugin,
> please open an issue in the dedicated [github](https://github.com/wilburt/flutter_paystack/issues)
> or provide your `flutter doctor -v`, your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
> #### without 3rd party plugins

**Comment by Khurshidbek18** [comment] 2021-03-22 09:02
> @Khurshidbek18
> can you provide the information listed [above](https://github.com/flutter/flutter/issues/78727#issuecomment-803877914)
> 
> > is evidently caused by [flutter_paystack](https://pub.dev/packages/flutter_paystack) which is a 3rd party plugin,
> > please open an issue in the dedicated [github](https://github.com/wilburt/flutter_paystack/issues)
> > or provide your `flutter doctor -v`, your `flutter run -v`
> > and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> > #### without 3rd party plugins

Hi there! First of all thank you for your help

Can you help me find the error if I open a friend on my computer via Anydesk or google remote?

**Comment by darshankawar** [comment] 2021-03-22 12:19
@Khurshidbek18 
As mentioned by @iapicca above, the error seems to be coming from a 3rd party plugin you are using:
```

`* What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> Compilation error. See log for more details`
```

The issue seems to be related to the `flutter_paystack` plugin you are using and you need to open this issue in that plugin's repository.

Closing from here, as it doesn't seem to be related to Flutter. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-22 12:19 UTC
Labels: in triage

**Comment by Khurshidbek18** [comment] 2021-03-22 12:35
> @Khurshidbek18
> As mentioned by @iapicca above, the error seems to be coming from a 3rd party plugin you are using:
> 
> ```
> 
> `* What went wrong:
> Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> > Compilation error. See log for more details`
> ```
> 
> The issue seems to be related to the `flutter_paystack` plugin you are using and you need to open this issue in that plugin's repository.
> 
> Closing from here, as it doesn't seem to be related to Flutter. If you disagree, write in comments and I'll reopen it.
> Thanks.

Hi please open the topic my problem is on flutter

**Comment by iapicca** [comment] 2021-03-22 12:47
> Hi please open the topic my problem is on flutter

 @Khurshidbek18 
 as mentioned [above](https://github.com/flutter/flutter/issues/78727#issuecomment-803599618) 
> is evidently caused by [flutter_paystack](https://pub.dev/packages/flutter_paystack) which is a 3rd party plugin,
> please open an issue in the dedicated [github](https://github.com/wilburt/flutter_paystack/issues)

if you believe that the issue is caused by flutter instead please provide

> a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
> ## without 3rd party plugins
