### ISSUE TITLE
Using go router,, getting issue when passing Data within nested Shell Route getting error as path not exist but when remove extra params in nested route and then pass it works fine but with params giving error path not correct

### ISSUE THREAD

**Issue by muhammadarslannasr** [flutter/flutter#140775] opened 2024-01-01 13:27 UTC
### Steps to reproduce

// class for handling app routes
```
class AppRouter {
  static final rootNavigatorKey = GlobalKey<NavigatorState>();
  static final shellNavigatorKey = GlobalKey<NavigatorState>();

  static final GoRouter _router = GoRouter(
    navigatorKey: rootNavigatorKey,
    initialLocation: Routes.splash,
    routes: [
      /// * initial route screen
      GoRoute(
        name: Routes.splash,
        path: Routes.splash,
        builder: (context, state) => const WelcomeSplashIndex(),
      ),

      /// * signup routes
      GoRoute(
        name: Routes.signUpStartScreen,
        path: Routes.signUpStartScreen,
        builder: (context, state) => const SignUpStartScreen(),
      ),

      GoRoute(
        name: Routes.pinCodeResetScreen,
        path: Routes.pinCodeResetScreen,
        builder: (context, state) => const PinCodeResetScreen(),
      ),

      GoRoute(
        name: Routes.bottomNavigationBarScreen,
        path: Routes.bottomNavigationBarScreen,
        builder: (context, state) => const BottomNavigationBarWidget(
          child: HomeScreen(),
        ),
      ),

      GoRoute(
        name: Routes.rewardIntroDefaultScreen,
        path: Routes.rewardIntroDefaultScreen,
        parentNavigatorKey: rootNavigatorKey,
        builder: (context, state) => RewardIntroDefault(
          navigationData: state.extra as EventNavigationData,
        ),
      ),

      GoRoute(
        name: Routes.questions,
        path: Routes.questions,
        parentNavigatorKey: rootNavigatorKey,
        builder: (context, state) => const Questions(),
      ),

      GoRoute(
        name: Routes.resultScreen,
        path: Routes.resultScreen,
        parentNavigatorKey: rootNavigatorKey,
        builder: (context, state) => const ResultScreen(),
      ),

      GoRoute(
        name: Routes.rewardEventSurveyResult,
        path: Routes.rewardEventSurveyResult,
        parentNavigatorKey: rootNavigatorKey,
        builder: (context, state) => const RewardEventSurveyResult(),
      ),

**Error came in Shell route when passing Data in route**
      ShellRoute(
        navigatorKey: shellNavigatorKey,
        builder: (BuildContext context, GoRouterState state, Widget child) {
          return BottomNavigationBarWidget(child: child);
        },
        routes: [
          GoRoute(
            name: Routes.homeScreen,
            path: Routes.homeScreen,
            builder: (context, state) => const HomeScreen(),
          ),
          GoRoute(
            name: Routes.rewardsHomeScreen,
            path: Routes.rewardsHomeScreen,
            builder: (context, state) => const RewardsHomeScreen(),
            routes: [
              GoRoute(
                name: Routes.eventTabsListScreen,
                path: Routes.eventTabsListScreen,
                pageBuilder: (BuildContext context, GoRouterState state) {
                  return CustomTransitionPage<void>(
                    transitionDuration: const Duration(milliseconds: 600),
                    reverseTransitionDuration: const Duration(milliseconds: 600),
                    key: state.pageKey,
                    child: const EventTabsListScreen(), /**/ here when pass params like state.extra as Map<String, dynamic>**.  **Receive Error this path not exit but when remove params navigation works fine**
                    transitionsBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
                      const begin = Offset(1.0, 0.0);
                      const end = Offset.zero;
                      const curve = Curves.easeInOutQuart;

                      var tween = Tween(begin: begin, end: end).chain(CurveTween(curve: curve));

                      var offsetAnimation = animation.drive(tween);

                      return SlideTransition(position: offsetAnimation, child: child);
                    },
                  );
                },
              ),
            ],
          ),
          GoRoute(
            name: Routes.channelHomeScreen,
            path: Routes.channelHomeScreen,
            builder: (context, state) => const ChannelHomeScreen(),
          ),
          GoRoute(
            name: Routes.walletHomeScreen,
            path: Routes.walletHomeScreen,
            builder: (context, state) => const WalletHomeScreen(),
          ),
          GoRoute(
            name: Routes.myBProfileHomeScreen,
            path: Routes.myBProfileHomeScreen,
            builder: (context, state) => const ProfileScreen(),
          ),
        ],
      ),
    ],
    observers: [
      NavigationObserver(),
    ],
  );

  static GoRouter get router => _router;
}

```

Used above code and passing data in nested route but when check it gave error route not exist and when remove the extra params it works fine.

### Expected results

Params should pass in nested route 

### Actual results

Getting Error this path not exist when passing params

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-01-02 09:52
@muhammadarslannasr 
Can you provide the complete error that is thrown ?
Also, in order to properly address the issue, please provide complete runnable reproducible code sample that we can directly copy paste and run.
Also, provide your go_router version and flutter doctor -v.

**Comment by muhammadarslannasr** [comment] 2024-01-02 10:15
Sure give me few minutes

> @muhammadarslannasr Can you provide the complete error that is thrown ? Also, in order to properly address the issue, please provide complete runnable reproducible code sample that we can directly copy paste and run. Also, provide your go_router version and flutter doctor -v.

**Comment by muhammadarslannasr** [comment] 2024-01-02 10:23
Below i have added two screenshots one about error which I am getting path not exist but If i remove params it start working fine.

second contain the code how I am passing from Shell route in nested routes.

@darshankawar 

![image](https://github.com/flutter/flutter/assets/52801821/1610c6f8-f92a-498b-ab33-54e9e88c55d8)
![image](https://github.com/flutter/flutter/assets/52801821/545a03e9-578d-4f52-abc4-07a5b542ed6a)

**Comment by darshankawar** [comment] 2024-01-03 05:31
@muhammadarslannasr 
I think you are hitting https://github.com/flutter/flutter/issues/117368 and a workaround is mentioned  https://github.com/flutter/flutter/issues/117368#issuecomment-1587721015 that you can check if it works in your case or not.
Closing for now, as duplicate of the linked issue.

**Closed by darshankawar** 2024-01-03 05:31 UTC
Labels: in triage
