### ISSUE TITLE
[Impeller] Impeller uses more memory than skia when sliding the page in android applications.

### ISSUE THREAD

**Issue by FridayAutum** [flutter/flutter#157497] opened 2024-10-24 08:43 UTC
### Steps to reproduce

1.Open the application.
2.Slide the page.
3.Capture profile memory snapshots by using Flutter devtool.
I found the difference in my android application,then I retested this in flutter-wonderous-app, the phenomenon is consistent.
The average memory data of impeller is always higher than skia.
This problem is more obvious in my app, which is about 20MB higher in comparison.
Here is the "Dart Heap" data captured in the flutter-wonderous-app.
Device1
**Impeller** 
![image](https://github.com/user-attachments/assets/8e9327c9-a64c-4988-91b7-2ceb50876413)

**Skia**
![image](https://github.com/user-attachments/assets/3b7301d7-f226-424d-b0d7-492c13bda676)

Device2
**Impeller**
![image](https://github.com/user-attachments/assets/1fed4906-4575-4aa2-82bd-cd09eaacd6dc)

**Skia**
![image](https://github.com/user-attachments/assets/2d3ea388-f8e5-4243-871e-20289812dabc)

### Code sample

https://github.com/gskinnerTeam/flutter-wonderous-app

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Device1:Redmi K70 Pro  OS:Xiaomi HyperOS(Android)
Device2:Oneplus 11  OS:ColorOS(Android)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

[✓] Flutter (Channel master, 3.27.0-1.0.pre.205, on Ubuntu 24.04.1 LTS 6.8.0-47-generic, locale zh_CN.UTF-8)
    • Flutter version 3.27.0-1.0.pre.205 on channel master at /home/mi/workspace/devkit/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bade5591bf (8 小时前), 2024-10-23 16:35:10 -0700
    • Engine revision 73c54fadf5
    • Dart version 3.7.0 (build 3.7.0-58.0.dev)
    • DevTools version 2.40.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/mi/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/mi/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.28.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2024.2)
    • Android Studio at /home/mi/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/mi/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-47-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.100

[✓] Network resources
    • All expected network resources are available.

</details>

**Comment by huycozy** [comment] 2024-10-24 12:02
I checked this on my device Pixel 7, Android 14 but couldn't see the issue. Tested on Flutter stable `3.24.3` and master `3.27.0-1.0.pre.206`, Dart Heap is around 20 to 21 MB with and without Impeller.

In your report, the gap of Dart Heap w/wo Impeller on the first device is also minimal and may not be noticeable (24.5 vs 25.3 MB). However, the gap becomes more apparent on the second device (28.6 vs 21 MB). Keeping this as a device-specific issue.

**Comment by FridayAutum** [comment] 2024-10-24 12:49
I use another device retesting this issue,through using " adb shell dumpsys meminfo com.gskinner.flutter.wonders |grep "TOTAL PSS" " .
I tested the memory information when the page was stationary or sliding,the results were somewhat unexpected.
**skia**
![image](https://github.com/user-attachments/assets/9ef1c71e-0f57-4e93-aa2a-db7e4b62c859)
**Impeller**
![image](https://github.com/user-attachments/assets/49ce6b7d-b8e0-4529-af97-c803880f5a95)

**Comment by jonahwilliams** [comment] 2024-10-24 16:45
@FridayAutum impeller doesn't impact dart heap (except indirectly via rendering more/less frames) and dart heap doesn't include any native objects

**Comment by FridayAutum** [comment] 2024-10-25 01:58
Thanks for the correction.I found that the range of the memory information obtained by "adb shell dumpsys meminfo" on different mobile phones is also different, which may have interfered with the data I got. I will submit this problem to my team to see where the specific differences are.

**Comment by FridayAutum** [comment] 2024-10-25 09:29
n the overall test, I used a script that can slide pages stably and test the memory information every second, and found a possible memory leak problem.The overall PSS memory usage shows a curve-like upward trend which also exists in my application.I ran the same test on both the stable branch and the master branch.The problem still exists in the master branch, but it will be better than the stable branch.

adb shell dumpsys meminfo com.gskinner.flutter.wonders | grep "TOTAL PSS"

**Stable**
![kQQzUiPU3Z](https://github.com/user-attachments/assets/c6090ed2-5e3c-43f8-b945-cb97866a7b20)
![KsTr6DAlmM](https://github.com/user-attachments/assets/62e0a243-8b7d-4335-87f7-c11e872d7fd8)
**Master**
![CrBDHggfCc](https://github.com/user-attachments/assets/a6fafd5e-427d-4b3a-97ed-9163a2d25e13)
![kyJX59aPmP](https://github.com/user-attachments/assets/45ed56c9-2cef-4c2c-a586-651d119a975f)

**Comment by FridayAutum** [comment] 2024-10-25 11:00
This is how i test this issue.

https://github.com/user-attachments/assets/3f2a27a3-0ded-4c6f-aad7-0a194897d976

**Comment by FridayAutum** [comment] 2024-10-28 03:07
We tested our own app and Wonderous app on different phones and found that this problem exists on both.

**Comment by jonahwilliams** [comment] 2024-10-28 17:51
@FridayAutum what are the numbers comapred to Skia? its difficult for me to tell what the actual diff is?

**Comment by FridayAutum** [comment] 2024-10-29 01:44
In terms of memory growth rate, Impeller using Vulkan as backend has a higher growth rate than the other two(Skia,Impeller+OpenGLES). I think it may be a problem in the memory allocation and recycle mechanism related to Vulkan?
Skia(1)
![iC1TSgG0Xf](https://github.com/user-attachments/assets/948ff575-0ea5-4333-9a50-1950cf56aa8a)
Skia(2)
![uSRw8kTzov](https://github.com/user-attachments/assets/969311e6-495d-48c4-a2b4-f4028a61bf18)
Impeller Vulkan(1)
![xWFVXzbSIv](https://github.com/user-attachments/assets/f891a9a9-677c-4819-b0d1-71913da7a62a)
Impeller Vulkan(2)
![5PA8WMLVvX](https://github.com/user-attachments/assets/f758371e-c5ff-4535-807e-4c79188dc323)
Impeller Opengles(1)
![cyMFUuIbKG](https://github.com/user-attachments/assets/6b0439ba-993d-46bd-b76f-9b23a31caf29)
Impeller Opengles(2)
![aJvF9DrWLi](https://github.com/user-attachments/assets/d55b0bd6-8bf3-44ad-bb69-12159636d207)

**Comment by jonahwilliams** [comment] 2024-11-02 22:58
Some notes from testing on my end:

* I don't see any evidence for a memory leak though, memory usage is stable, and increases in memory usage correlate with how the application loads and caches large images.
* I see very different allocation behavior, which I'd sort of expect given that these are entirely different backends. There may be some more opportunity to tune the Vulkan backend behavior.

It looks like on Impeller we start with a larger initial memory usage (possibly from the initial image upload) and then drop down. Whereas skia starts very low and then jumps up as it decodes more images. I'll need to look more into finding a breakdown of the graphics memory usage so I can correctly attribute the allocation to the different parts of our backend.

### Impeller Vulkan 

![image](https://github.com/user-attachments/assets/12273c99-07ee-42bc-afc7-2a1c285e67d2)


### Skia

![image](https://github.com/user-attachments/assets/4bdc41ed-c173-4368-8038-b6f3c1780c1f)

**Comment by jonahwilliams** [comment] 2024-11-02 23:15
I was able to get the memory usage to more closely match skia by adjusting the initial size of our VMA heap. I suspect that the defaults we are using are not optimal for an Android application and need adjustment. The initial pool size for the VMA allocator is 256 MB.

```
diff --git a/impeller/renderer/backend/vulkan/allocator_vk.cc b/impeller/renderer/backend/vulkan/allocator_vk.cc
index 18ef93d8e6..43d0e3815c 100644
--- a/impeller/renderer/backend/vulkan/allocator_vk.cc
+++ b/impeller/renderer/backend/vulkan/allocator_vk.cc
@@ -14,6 +14,7 @@
 #include "impeller/renderer/backend/vulkan/device_buffer_vk.h"
 #include "impeller/renderer/backend/vulkan/formats_vk.h"
 #include "impeller/renderer/backend/vulkan/texture_vk.h"
+#include "third_party/swiftshader/include/vulkan/vulkan_core.h"
 #include "vulkan/vulkan_enums.hpp"
 
 namespace impeller {
@@ -84,6 +85,7 @@ static PoolVMA CreateBufferPool(VmaAllocator allocator) {
   VmaPoolCreateInfo pool_create_info = {};
   pool_create_info.memoryTypeIndex = memTypeIndex;
   pool_create_info.flags = VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT;
+  pool_create_info.minBlockCount = 1;
 
   VmaPool pool = {};
   result = vk::Result{::vmaCreatePool(allocator, &pool_create_info, &pool)};
@@ -145,6 +147,7 @@ AllocatorVK::AllocatorVK(std::weak_ptr<Context> context,
   allocator_info.device = device_holder->GetDevice();
   allocator_info.instance = instance;
   allocator_info.pVulkanFunctions = &proc_table;
+  allocator_info.preferredLargeHeapBlockSize = 64;
```

![image](https://github.com/user-attachments/assets/4c48fa8c-2e16-4306-9a7a-8389bd75c4dc)

**Comment by jonahwilliams** [comment] 2024-11-02 23:19
I think with some adjustments we can actually use much less memory than the existing Skia backend.

**Comment by FridayAutum** [comment] 2024-11-05 02:47
I also found a problem still exists in version 3.24.4 but fixed in master.The application's memory usage data keeps growing due to frequent page switching, from the initial 291MB to the final 890MB.(I used a script that can perform the action in the video)(Test time:1 Hour)

Similar problems also exist in my application.Is there any way to circumvent or fix this in the stable version(3.24.4)?

https://github.com/user-attachments/assets/fb9770f7-c4ba-4758-b9da-e289003d3e66

Begin
![cZyh4039Br](https://github.com/user-attachments/assets/b99fb8f1-5ff7-490b-a996-1ff827bd39b6)
End
![U1xd4tJbPZ](https://github.com/user-attachments/assets/179beedf-2df4-42fa-b2cb-fdace9452c5f)

**Comment by jonahwilliams** [comment] 2024-11-05 03:30
I'm not certain, we've done a lot of work since 3.24. You might check if the current beta 3.27 (I think) reproduces the issue or not.

**Comment by FridayAutum** [comment] 2024-11-05 03:59
Much appreciated,It will not reproduce in 3.27-pre.

**Comment by jonahwilliams** [comment] 2024-11-06 00:49
@FridayAutum changes to the VMA settings landed in 7edcacb4d5cbd4866e21d869c1d0c70d8897a30c . I've run locally and I believe memory usage is closer to Skia levels, but it would be great if you could test that out as well too.

**Comment by FridayAutum** [comment] 2024-11-12 03:01
I think it is not appropriate to set "preferredLargeHeapBlockSize" to 4M. I added this change to my application, which will cause frame drops(stable 3.24.4).I am not sure that whether this problem will reproduce in master(3.27).But After I changed this value to 32M, the problem was solved.It may be necessary to consider a more appropriate value to regulate the behavior of memory allocation.

**Comment by jonahwilliams** [comment] 2024-11-12 03:12
I'm not backporting these changes to 3.24, I would only evaluate against master channel for now.

I have no doubt that a larger block size would be better for certain applications, and a smaller one would be better for others. There is not going to be a universally optimal block size.

The 4 MB value matches what Skia uses with Vulkan on Android and is as good of a starting point as any.

**Comment by Yerdna1** [comment] 2024-11-26 12:13
I have similar problem in flutter_web App, where I have long ListView.Builder about 500 checkboxes... I have in Firefox 2GB ram only with scrolling up and down, in flutter 3.16.9 no problem with this...problem most in firefox

**Comment by jonahwilliams** [comment] 2024-12-04 21:56
Closing as fixed

**Closed by jonahwilliams** 2024-12-04 21:56 UTC
Labels: e: device-specific, platform-android, engine, P2, e: impeller, team-engine, triaged-engine
