### ISSUE TITLE
[cloud_firestore] ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized

### ISSUE THREAD

**Issue by MrMagloire** [flutter/flutter#48817] opened 2020-01-14 16:40 UTC
### Steps to Reproduce
I created a function to save data on cloud_firestore, there is so much data that the application crashes from a moment, so to remedy it I create an Isolate in order to do the processing in another thread. But I have a problem with Isolate.
### Logs
![image](https://user-images.githubusercontent.com/9309214/72362373-f7735780-36ea-11ea-827d-191fae7a5ba0.png)

ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)

**Though I have put WidgetsFlutterBinding.ensureInitialized(); in main as below**

**Comment by iapicca** [comment] 2020-01-15 08:46
Hi @MrMagloire 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

Please refrain from posting pictures if not necessary.
thank you

**Closed by iapicca** 2020-01-15 08:46 UTC

**Comment by eliaweiss** [comment] 2020-01-31 15:58
This not related to FlutterFire ,
I tried to use the package https://github.com/arrrrny/tesseract_ocr and run the thread using this: 
https://github.com/flutter/flutter/blob/master/examples/layers/services/isolate.dart

> 
> When I run the isolate example , it works, but when I run the tesseract extractText I get:
> 
> ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
> E/flutter (17761): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
> E/flutter (17761): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
> E/flutter (17761): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
> E/flutter (17761): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
> E/flutter (17761): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
> E/flutter (17761): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
> E/flutter (17761): #4      extractText (package:flutter_opencv/src/core.dart:57:22)
> E/flutter (17761): <asynchronous suspension>
> E/flutter (17761): #5      Calculator.run (package:flutter_opencv_example/IsolateExample.dart:58:28)
> E/flutter (17761): #6      CalculationManager._calculate (package:flutter_opencv_example/IsolateExample.dart:214:16)
> E/flutter (17761): #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:310:17)
> E/flutter (17761): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by iapicca** [comment] 2020-02-06 08:11
@eliaweiss 
it looks like a 3rd party issue,
you might want to open an issue [here](https://github.com/arrrrny/tesseract_ocr/issues)

Please do not post in closed issue,
but open a new issue instead
thank you

**Comment by SpanishOnion** [comment] 2020-03-19 16:51
same issue, I can't use the third-party plugin in isolate. Once the third-party plugin is referenced, this error will be reported
