### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by XXBLADEX** [flutter/flutter#154982] opened 2024-09-11 07:25 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner

**Comment by danagbemava-nc** [comment] 2024-09-11 09:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153471

**Closed by danagbemava-nc** 2024-09-11 09:45 UTC
Labels: in triage

**Comment by andrewkolos** [comment] 2024-09-11 17:01
This is specifically a duplicate of https://github.com/flutter/flutter/issues/154903 (I see VmService.getVM in the call stack).

If you have a reliable way to reproduce this crash, please let us know.
