### ISSUE TITLE
Reconsider adding support for 32-bit builds

### ISSUE THREAD

**Issue by SeniorPlayer** [flutter/flutter#80105] opened 2021-04-09 09:03 UTC
Since flutter 2.0 starts to support desktop application，we should reconsider adding support for 32-bit builds on windows and linux. Because there are still many devices using 32-bit systems.

**Comment by stuartmorgan** [comment] 2021-04-09 19:05
The windows portion of this is a duplicate of https://github.com/flutter/flutter/issues/37777. I'm not sure if there's a Linux issue already.

**Closed** 2022-03-15 17:39 UTC
Labels: severe: new feature, platform-linux, proposal, a: desktop, passed first triage, P5
