### ISSUE TITLE
Unable to attain an output after running main.dart I/flutter (15748): Observatory listening on ************************************

### ISSUE THREAD

**Issue by dhimaspp** [flutter/flutter#81801] opened 2021-05-04 02:26 UTC
debug console:
![observatory](https://user-images.githubusercontent.com/66865624/116954378-1029c700-acba-11eb-82b7-b7624f96a53a.PNG)

flutter run verbose:
![Capture](https://user-images.githubusercontent.com/66865624/116954394-1c158900-acba-11eb-86a0-b0bb37350ef0.PNG)

flutter doctor -v:
![flutter doctor -v](https://user-images.githubusercontent.com/66865624/116954686-d7d6b880-acba-11eb-974a-bcfc30d919d4.PNG)

**Comment by pedromassangocode** [comment] 2021-05-04 06:54
Thanks for filling this.

There is an opened issue (https://github.com/flutter/flutter/issues/81196) similar to this one so I going to close this as a duplicate. Please follow up on that issue for updates.

This seems to be caused by Vivo devices as the other issue is also related to a vivo device.
Cc @jonahwilliams 

Thank you

**Closed by pedromassangocode** 2021-05-04 06:54 UTC
Labels: in triage
