### ISSUE TITLE
[Request] Add return type info to doc for FocusOnKeyCallback

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#45367] opened 2019-11-21 23:21 UTC
This is the DartDoc & declaration of `FocusOnKeyCallback`:

```
/// Signature of a callback used by [Focus.onKey] and [FocusScope.onKey]
/// to receive key events.
///
/// The [node] is the node that received the event.
typedef FocusOnKeyCallback = bool Function(FocusNode node, RawKeyEvent event);
```

The callback has a return type of `bool`, but how that value will be used is not clear. (Sorry if this is an obvious one :p)

**Comment by iapicca** [comment] 2019-11-22 09:48
Hi @mtcliatt 
I don't pretend to understand all the reasons for choosing `bool` as return type,
but my best guess is that is the "lightest" return you can have;
in [this](https://dartpad.dartlang.org/8d5d381e0a53af734e1d151f7dc66322) example
without returning `bool` wouldn't be possible to use `.then`.
Does this answer your question?
thank you

**Comment by mtcliatt** [comment] 2019-11-25 02:24
Hey @iapicca, thanks for the response!
The "lightest" return type definitely makes sense, although I wonder if `void` might be more "lightweight". 

[Here](https://dartpad.dartlang.org/3804af4b33f2d097d57e9789c27020e5) is the same example but this one uses a `void` return type and appears to work the same way. Would using `void` instead of `bool` work in this case?

**Comment by Quijx** [comment] 2020-02-13 18:01
It is explained in the doc of the `onKey` attribute of the `Focus` Widget:

> /// Key events are first given to the [FocusNode] that has primary focus, and
  /// if its [onKey] method return false, then they are given to each ancestor
  /// node up the focus hierarchy in turn. If an event reaches the root of the
  /// hierarchy, it is discarded.

But I agree that it would be good if it was also explained on `FocusOnKeyCallback`.

**Comment by cv692001** [comment] 2020-09-15 15:58
Hey @kf6gpe @mtcliatt @iapicca @AyushBherwani1998  , I will love to contribute to this :)
It is going to be my first Contribution so can you please help me out .

So, basically I have to change the datatype from bool to void or any other change you can suggest , it will be very nice of you :)

**Comment by iapicca** [comment] 2020-09-15 16:22
@cv692001
I believe the issue is about providing details in the documentation for the typedef [FocusOnKeyCallback](https://api.flutter.dev/flutter/widgets/FocusOnKeyCallback.html)
rather than apply changes to latter, maybe @TahaTesser can give you more details

**Comment by cv692001** [comment] 2020-09-15 16:48
thanks @iapicca , for your response.

@TahaTesser can you please help me in this case , it will be very nice of you :)

**Comment by MrBirb** [comment] 2021-07-29 05:44
@TahaTesser Looks like the api has changed. This now returns a KeyEventResult which is documented.

**Comment by TahaTesser** [comment] 2021-07-29 10:13
@MrBirb Thanks!

Closing as this is no longer  a valid  doc issue

**Closed by TahaTesser** 2021-07-29 10:13 UTC
Labels: d: api docs, documentation, easy fix, framework, passed first triage, proposal
