### ISSUE TITLE
'Unsupported operation: Infinity or NaN toInt. Error thrown' in SliverGridRegularTileLayout.getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#147284] opened 2024-04-24 05:43 UTC
We are on Flutter 3.19.5 and we are sporadically getting the following report on production:
<details><summary>Stack trace</summary>
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unsupported operation: Infinity or NaN toInt. Error thrown .
       at double.~/(dart:core)
       at SliverGridRegularTileLayout.getMinChildIndexForScrollOffset(sliver_grid.dart:215)
       at RenderSliverGrid.performLayout(sliver_grid.dart:596)
       at RenderObject.layout(object.dart:2575)
       at RenderSliverEdgeInsetsPadding.performLayout(sliver_padding.dart:139)
       at RenderSliverPadding.performLayout(sliver_padding.dart:361)
       at RenderObject.layout(object.dart:2575)
       at RenderViewportBase.layoutChildSequence(viewport.dart:601)
       at RenderViewport._attemptLayout(viewport.dart:1555)
       at RenderViewport.performLayout(viewport.dart:1464)
       at RenderObject._layoutWithoutResize(object.dart:2414)
       at PipelineOwner.flushLayout(object.dart:1051)
       at PipelineOwner.flushLayout(object.dart:1064)
       at RendererBinding.drawFrame(binding.dart:582)
       at WidgetsBinding.drawFrame(binding.dart:991)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:448)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1386)
       at SchedulerBinding.handleDrawFrame(binding.dart:1311)
       at SchedulerBinding._handleDrawFrame(binding.dart:1169)
</details>

There is no more contextual information so we don't know which component causes this.
All of the reports we got affect Android 11 only (we have users with all the other versions as well, but this issue seems not to occur there).

Might be related to https://github.com/flutter/flutter/issues/105630.

**Comment by danagbemava-nc** [comment] 2024-04-24 09:07
This is indeed a duplicate of #105630 

Please feel free to add any additional information you get in that closing. 

Closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-04-24 09:07 UTC
Labels: in triage
