### ISSUE TITLE
Vertical Stepper inside ListView / CustomScrollView is scrolled to the beginning when press on step

### ISSUE THREAD

**Issue by ezraaaa** [flutter/flutter#39488] opened 2019-08-29 14:31 UTC
## Steps to Reproduce
1. Create a long list of steps (exceeding the screen size) in CustomScrollView (with ClampingScrollPhysics)
2. Scroll down to the last step (or anything overflowed)
3. Click on it
4. It jumps back to the top

P/S: It jumps everywhere with NestedScrollView

![ezgif com-optimize](https://user-images.githubusercontent.com/12880287/63477284-098ff780-c4b7-11e9-9f5c-7ffad2f32b26.gif)

## Logs
```
Ezras-MacBook-Pro:codecumbers ezragunn$ flutter analyze
Analyzing codecumbers...                                                
No issues found! (ran in 14.5s)
```

```
Ezras-MacBook-Pro:codecumbers ezragunn$ flutter doctor -v
[✓] Flutter (Channel master, v1.9.6-pre.67, on Mac OS X 10.14.6 18G87, locale
    en-GB)
    • Flutter version 1.9.6-pre.67 at
      /Users/ezragunn/private-develop/SDKs/flutter
    • Framework revision 73b798b260 (15 hours ago), 2019-08-28 16:01:47 -0700
    • Engine revision 728ff715e8
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ezragunn/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9
      (API 28) (emulator)

• No issues found!

```

**Comment by HansMuller** [comment] 2019-08-29 16:22
If you could provide a small self-contained app that demonstrates the problem that would help. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by ezraaaa** [comment] 2019-08-30 01:31
@HansMuller here's the self-contained app that demonstrates the problem
[https://gist.github.com/ezraaaa/a4394737a092af88ff55e9945d24d5f2](url)

**Comment by ezraaaa** [comment] 2019-09-18 07:17
@HansMuller just checking, is there any fixes/ workaround for this issue?

**Comment by duranapdan** [comment] 2020-04-06 11:16
is this problem resolved? I have the same problem.

**Comment by ezraaaa** [comment] 2020-04-07 08:17
it's not @duranapdan, i couldn't find a way to do a temp fix too

**Comment by duranapdan** [comment] 2020-04-07 10:33
I found the solution. "NestedScrollView" solves the problem

**Comment by ezraaaa** [comment] 2020-04-07 14:40
not really. whenever you tap on steps in the middle, the step will jump up to the top of the screen.

![nested_scroll_view](https://user-images.githubusercontent.com/12880287/78682488-a0170900-7920-11ea-8297-797301902621.gif)

**Comment by Piinks** [comment] 2020-07-11 00:53
I think this is a duplicate of https://github.com/flutter/flutter/issues/36163
I am going to close this one since the other has more upvotes and therefore higher priority ranking. :)
If you think this is not a duplicate, let us know and we'll re-open!
Thanks!

**Closed by Piinks** 2020-07-11 00:53 UTC
Labels: f: material design, f: scrolling, found in release: 1.18, framework, has reproducible steps
