### ISSUE TITLE
FutureBuilder Widget runs many times unintentionally

### ISSUE THREAD

**Issue by mehmetozanguven** [flutter/flutter#27847] opened 2019-02-12 17:58 UTC
## Steps to Reproduce

Hi,
My FlutterBuilder widget runs many times so it connects the backend many times unintentionally.
1. In my application: there are many Card widget in my ListView widget and user can click one of the cards
2. After clicking I am running showModalBottomSheet. In that BottomSheet, I am showing some extra information about the car which was clicked.
3. Problem starts here: In that BottomSheet there is a FutureBuilder widget, and this widget is calling many times when I open that BottomSheet or when I close that BottomSheet. (In addition, don't understand why FutureBuilder is called when bottomSheet opens)
4. Here is the dart code:

```dart
class SampleWidget extends StatefulWidget {
  @override
  SampleWidgetState createState() => SampleWidgetState();
}

class SampleWidgetState extends State<SampleWidget> {
     @override
  Widget build(BuildContext context) {
    print("\n$_log 1) build method");
    print("");
    return Form(
      key: _formKey,
      child: ListView(
        shrinkWrap: true,
        padding: EdgeInsets.all(8.0),
        children: <Widget>[
             FutureBuilder(
            future: _someFunction(), /// this is another backend call, which corrects in a prober way, I am creating cards according to the this response
            builder: (BuildContext context, AsyncSnapshot snapshot){
              if (snapshot.hasData){
                bool isUserHasItem = someClass.isUserHasItems(snapshot.data);
                return isUserHasItem ? builldCard() : buildListDeviceErrorText(context, "noItem");
              }else{
                return buildListDeviceErrorText(context, "loading");
              }
            }
          )
        ]
   }


   builldCard() {
    List<Widget> devicesListWidget = List();
    _commonPropertySingleton.getDevicesList().forEach((elem) => devicesListWidget.add(deviceListItem(elem))); /// this list is for card, works correctly
    return Column(
      children: devicesListWidget,
    );
  }

  deviceListItem(DevicesList deviceItem) {
    return
      Card(
        child: InkWell(
          child: ListTile(
            title: Text(
              Localization.of(context).getText(text: "deviceName"),
              style: TextStyle(color: Theme.of(context).primaryColorDark),
            ),
            subtitle: Text(
              deviceItem.getDeviceName(),
            ),
            trailing: Icon(Icons.subdirectory_arrow_right),
          ),
          onTap: () => showBottomModalSheetToUser(deviceItem),
        ),
      );
  }

   showBottomModalSheetToUser(DevicesList deviceItem){
    print("\n$_log showBottomModalSheet runs");
    print("");
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context){
          return ListView(
            children: <Widget>[
              FutureBuilder<String>(
               ///This Future Builder is called MANY TIMES !!!!
                future: _someFunction(),
                builder: (context, asynData){
                  print("\n$_log FlutterBuilder runs in showBottomModalSheet method");
                  print("");
                  if  (asynData.hasData){
                    print("$_log : response: ${asynData.data}");
                    return Text(asynData.data);
                  }else if (asynData.hasError){
                    print("$_log : error: ${asynData.error}");
                    return Text(asynData.error.toString());
                  }else{
                    return Text("loading");
                  }
                },
              )
            ],
          );
        });
  }


}
````

## Logs

```
[   +1 ms] I/flutter (28865): SampleWidgetState showBottomModalSheet runs
[        ] I/flutter (28865): 
[  +37 ms] I/flutter (28865): ServiceProvider : post to this url https://....
[  +35 ms] I/flutter (28865): 
[        ] I/flutter (28865): SampleWidgetState FlutterBuilder runs in showBottomModalSheet method
[        ] I/flutter (28865): 
[  +24 ms] I/flutter (28865): ServiceProvider : post to this url https://....
[   +6 ms] I/flutter (28865): 
[        ] I/flutter (28865): SampleWidgetState FlutterBuilder runs in showBottomModalSheet method
[        ] I/flutter (28865): 
[  +29 ms] I/flutter (28865): ServiceProvider : post to this url https://....
[   +4 ms] I/flutter (28865): 
[        ] I/flutter (28865): SampleWidgetState FlutterBuilder runs in showBottomModalSheet method


```

```
```

### Flutter Doctor
Note: Ignore IntelliJ IDEA, I am not using that IDE for flutter
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.31.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

```

**Comment by zoechi** [comment] 2019-02-12 18:03
https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html

> The future must have been obtained earlier, e.g. during State.initState, State.didUpdateConfig, or State.didChangeDependencies. It must not be created during the State.build or StatelessWidget.build method call when constructing the FutureBuilder. If the future is created at the same time as the FutureBuilder, then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.
> 
A general guideline is to assume that every build method could get called every frame, and to treat omitted calls as an optimization.

Closing as working as intended.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Closed by zoechi** 2019-02-12 18:03 UTC

**Comment by wisnuwijo** [comment] 2019-08-13 02:04
Does this mean we can't prevent the FutureBuilder from rerun unintentionally?

**Comment by frank06** [comment] 2019-12-20 18:47
@wisnuwijo Yes you can, and the answer is in `FutureBuilder`'s implementation of `didUpdateWidget`: If you pass different instances of your future the builder will be fired multiple times. If you understand what exactly is happening and how to fix it with different approaches, I wrote about it here: https://flutterigniter.com/future-async-called-multiple-times/
