### ISSUE TITLE
flutter firebase database not working in release mode for android but for ios is working

### ISSUE THREAD

**Issue by usaikoo** [flutter/flutter#89361] opened 2021-09-02 10:33 UTC
I am using Firebase database as a back-end server for flutter app, the app is working in debug mode for android and IOS. but it is not working in release mode for android only. IOS is working not only in release or debug mode. Although the code base is same for UI and widget are correct, the android release is not reading the data from Firebase database.

**Comment by TahaTesser** [comment] 2021-09-02 10:37
Hi @usaikoo 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-02 10:37 UTC
Labels: in triage
