### ISSUE TITLE
The boldness of the custom font with emoji on iOS changes when scrolling

### ISSUE THREAD

**Issue by JWo1F** [flutter/flutter#131418] opened 2023-07-27 16:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code on iOS
1. Add a custom font (google_fonts or put the fonts in a folder), the problem is reproduced in either option
2. Create a CustomScrollView with SliverList.separated, preferably using the cupertino set (haven't tested in others).
3. Inside the element, place the text (I will attach the style below).

```dart
Text(
  visibleStatus.displayName(),
  strutStyle: const StrutStyle(forceStrutHeight: true),
  style: const TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF131313)),
  textAlign: TextAlign.start
)
```

### Expected results

The font is displayed correctly, with the same boldness as specified in the Text element.

### Actual results

The font is displayed incorrectly, you can clearly see places where it is displayed poorly (too bold, letters lose their shape). Scrolling down the text normalizes the font, scrolling up the font loses its shape.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:google_fonts/google_fonts.dart';
import 'dart:math';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
        width: 600,
        child: CupertinoApp(
            theme: CupertinoThemeData(
                brightness: Brightness.light,
                textTheme: CupertinoTextThemeData(
                    textStyle: GoogleFonts.openSans()
                        .copyWith(color: CupertinoColors.black))),
            home: CupertinoTabScaffold(
                tabBar: CupertinoTabBar(
                  items: const <BottomNavigationBarItem>[
                    BottomNavigationBarItem(
                      icon: Icon(CupertinoIcons.home),
                    ),
                    BottomNavigationBarItem(
                      icon: Icon(CupertinoIcons.search),
                    ),
                    BottomNavigationBarItem(
                      icon: Icon(CupertinoIcons.add),
                    ),
                    BottomNavigationBarItem(
                      icon: Icon(CupertinoIcons.heart),
                    ),
                    BottomNavigationBarItem(
                      icon: Icon(CupertinoIcons.profile_circled),
                    ),
                  ],
                ),
                tabBuilder: (context, index) {
                  return MyWidget();
                })));
  }
}

const _chars = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
Random _rnd = Random();

String getRandomString(int length) => String.fromCharCodes(Iterable.generate(
    length, (_) => _chars.codeUnitAt(_rnd.nextInt(_chars.length))));

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: CustomScrollView(
        slivers: [
          SliverList.separated(
            itemCount: 50,
            separatorBuilder: (context, index) => const SizedBox(height: 20),
            itemBuilder: (context, index) {
              String emoji = index % 10 == 0 ? "with emoji⚡️" : '';

              return Text("Text $emoji ${getRandomString(400)}");
            },
          )
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
https://github.com/flutter/flutter/assets/1540715/92f85d47-ed13-4e0e-86fc-f89ffb54f8b6
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale ru-GE)
    • Flutter version 3.10.6 on channel stable at /Users/jwo1f/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 недели назад), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jwo1f/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/jwo1f/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • JWo1F (mobile)             • 00008030-001E25091110402E            • ios            • iOS 16.5.1 20F75
    • iPhone 14 Pro Max (mobile) • C3DA140B-67E6-40B9-95F0-2465470E262A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by JWo1F** [comment] 2023-07-27 16:27
Here are screenshots of the bug:

**With emoji on the screen:**
<img width="327" alt="image" src="https://github.com/flutter/flutter/assets/1540715/d9493c09-d35e-4f5a-b508-5a7b204ea80d">

**Without emoji on screen:**
<img width="327" alt="image" src="https://github.com/flutter/flutter/assets/1540715/2c344a7a-994d-4a74-82e8-e3c4982dc851">

**Comment by danagbemava-nc** [comment] 2023-07-28 07:32
This is indeed a duplicate of https://github.com/flutter/flutter/issues/126514. 

Closing this since it has already been fixed on the master channel.

**Closed by danagbemava-nc** 2023-07-28 07:32 UTC
Labels: in triage
