### ISSUE TITLE
FlexibleSpaceBar's title locates below AppBar and overlaps with bottom when SliverAppBar's bottom is given

### ISSUE THREAD

**Issue by hanstar17** [flutter/flutter#132110] opened 2023-08-08 03:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

As titled. See the sample code and videos below.

### Expected results

Title is located in the AppBar properly, even when bottom is provided.

### Actual results

Title is located below the AppBar, overlapping with the bottom widget (TabBar), when bottom is provided.

### Code sample

<details><summary>Code sample</summary>
With bottom, title is located below the app bar unexpectedly:

```dart
void main() {
  runApp(const TestApp());
}

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<String> tabs = ['Discussions', 'About'];

    return MaterialApp(
      home: DefaultTabController(
        length: tabs.length,
        child: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) => [
            const SliverAppBar(
              pinned: true,
              expandedHeight: 200,
              flexibleSpace: FlexibleSpaceBar(
                collapseMode: CollapseMode.pin,
                title: Text(
                  "Reasonably Long Title",
                  style: TextStyle(color: Colors.black),
                ),
              ),
              bottom: TabBar(
                tabs: tabs.map((tab) => Tab(text: tab)).toList(),
              ),
            ),
          ],
          body: TabBarView(
            children: tabs.map((tab) => Center(child: Text(tab))).toList(),
          ),
        ),
      ),
    );
  }
}
```

Without bottom, title is located in app bar correctly:
```dart
void main() {
  runApp(const TestApp());
}

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<String> tabs = ['Discussions', 'About'];

    return MaterialApp(
      home: DefaultTabController(
        length: tabs.length,
        child: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) => [
            const SliverAppBar(
              pinned: true,
              expandedHeight: 200,
              flexibleSpace: FlexibleSpaceBar(
                collapseMode: CollapseMode.pin,
                title: Text(
                  "Reasonably Long Title",
                  style: TextStyle(color: Colors.black),
                ),
              ),
              // bottom: TabBar(
              //   tabs: tabs.map((tab) => Tab(text: tab)).toList(),
              // ),
            ),
          ],
          body: TabBarView(
            children: tabs.map((tab) => Center(child: Text(tab))).toList(),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

With bottom:

[[SliverAppBar with bottom]](https://github.com/flutter/flutter/assets/5125332/7ffae04c-d661-4ee4-9143-07053e6fab87)

Without bottom:

[[SliverAppBar without bottom]](https://github.com/flutter/flutter/assets/5125332/585acb7f-3314-444d-a595-005f9ef94867)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.13.0-0.2.pre on channel beta at /Users/hanstar/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac71592bc6 (3 weeks ago), 2023-07-18 14:53:57 -0600
    • Engine revision e14db68a86
    • Dart version 3.1.0 (build 3.1.0-262.2.beta)
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.81.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.71.20230801

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 11F38E6A-C0AA-4FD9-9CD0-1C06E64A4861 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment] 2023-08-08 11:20
Hi @hanstar17. Thanks for filing this issue. I am able to reproduce this on the latest `master` and `stable` channels. This seems to be similar to https://github.com/flutter/flutter/issues/25723. Closing this in favour of the already open issue. Kindly comment, upvote and follow up on the issue for updates. If you disagree with this, kindly comment here and I'd reopen this.

**Closed by dam-ease** 2023-08-08 11:20 UTC
Labels: in triage
