### ISSUE TITLE
FlutterFragmentActivity getting attached to FlutterEngine even before my plugin got attached to FlutterEngine

### ISSUE THREAD

**Issue by desusai7** [flutter/flutter#131767] opened 2023-08-02 13:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We've been using Android Activity Life Cycle Callbacks to determine if an application is in an opened state or in a backgrounded state as shown [here](https://gist.github.com/desusai7/7897ecde4e2bb831374af5b7d12ec22e) within a Flutter Plugin.

And we are registering for the Activity Life Cycle Callbacks in the `onAttachedToEngine` of the `FlutterPlugin` implementation on the Android Side.

So we rely hugely on the Activity Life Cycle Callbacks `onActivityStarted` and `onActivityStopped` to deduce if the application is opened or background state. 

And even if one of those callbacks isn't triggered, the entire sequence of events would be failed.  We are having this implementation working perfectly fine when the MainActivity on the Android module is extending `FlutterActivity`, but if it extends `FlutterFragmentActivity` it is breaking. 

On further debugging, I've noticed that `onActivityStarted` isn't getting triggered on the initial app launch, because `FlutterFragmentActivity` is getting attached to the `FlutterEngine` even before the Flutter Plugin got attached to the Flutter Engine which means that `onActivityStarted` is triggered even before Flutter plugin registered for that call back. 

Is there a better way to register for activity life cycle callbacks other than the way I am doing right now? (I do not think so, because we cannot guarantee whether the plugin or activity gets attached to the Flutter engine first)

But why is that in case of `FlutterActivity`, FlutterPlugin get registered first always and activity is registered later ?

Is this a bug in the Flutter itself ?

### Expected results

`FlutterFragmentActivity` as well to get attached with the `FlutterEngine` only after all the `FlutterPlugin` are registered with the engine.

### Actual results

`FlutterFragmentActivity` is getting attached with the `FlutterEngine` even before all the `FlutterPlugin` are registered with the engine.

### Code sample

<details><summary>Code sample</summary>

[Repository with sample code](https://github.com/desusai7/lifecycle_events/tree/main)

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Repository with screenshots](https://github.com/desusai7/lifecycle_events/tree/main)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/desusaivenkat/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/desusaivenkat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/desusaivenkat/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-08-02 13:58
Hi @desusai7. Thanks for filing this issue. Please can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), reproduction steps and the output of your `flutter doctor -v`

**Comment by desusai7** [comment] 2023-08-10 16:32
Hey @dam-ease, 

I've created a [repo](https://github.com/desusai7/lifecycle_events/tree/main) with a sample flutter plugin to demonstrate the issue and updated the [README.md](https://github.com/desusai7/lifecycle_events/blob/main/README.md) to include complete details about how to reproduce the issue along with screenshots.

Updated the description of the issue to contain the output of `flutter doctor -v`

**Comment by dam-ease** [comment] 2023-08-11 09:21
Hi @desusai7. Thanks for your response and detailed explanation. Trying to reproduce this issue on the latest versions of flutter:
`onActivityStarted` is not triggered on the initial launch of the application in both cases i.e when the `MainActivity` is extending `FlutterFragmentActivity` and when `MainActivity` is extending `FlutterActivity`

| `MainActivity` is extending `FlutterFragmentActivity` | `MainActivity` is extending `FlutterActivity` |
|--------|--------|
| <img width="724" alt="Screenshot 2023-08-11 at 10 13 41" src="https://github.com/flutter/flutter/assets/53122008/1117d664-55a0-4fec-9099-0a2f9a715edb"> | <img width="724" alt="Screenshot 2023-08-11 at 10 14 39" src="https://github.com/flutter/flutter/assets/53122008/2a39f3b9-52ef-4974-bded-c3e168e88c84"> | 

Can you confirm this is the case in newer versions? Or kindly let me know if I misunderstood this.

**Comment by desusai7** [comment] 2023-08-11 10:49
In the above comment for one of the images in the description it is mentioned that `Main Activity` is extending `FlutterFragmentActivity` but in the image it can be seen that it is actually extending `FlutterActivity` and for the other image, you've attached the image of `main.dart` file instead of the `MainActivity.java`. May be this can be an err while writing down the comment, but just wanted to bring it to your notice so that we are aligned on the same.

I had also observed that we are filtering the logs to show only the logs printed to the console by `System.out` but there is also a part of the UI saying that it is `showing 5 of 10`. Are we missing any logs which were printed earlier in this case ?

**Comment by desusai7** [comment] 2023-08-11 10:49
@dam-ease, I've just upgraded to version 3.10.6 (previously I was on 3.10.5) of Flutter and I am still observing that the `onActivityStarted` callback is missing when the `MainActivity` is extending the `FlutterFragmentActivity`. 

I've tested this on a real device as well along with emulator and I am seeing the difference in the behaviour consistently on both emulator and real device.

**Comment by dam-ease** [comment] 2023-08-11 14:54
Hi @desusai7. Thanks for pointing the errors out, that was an error from me when uploading the screenshots (changed that now). I was trying to point out that in both cases `onActivityStarted` seemed to have not been triggered on the initial launch. Are you still able to reproduce `onActivityStarted` on the initial launch in both cases on the latest versions?

**Comment by desusai7** [comment] 2023-08-11 18:10
Hey @dam-ease, 

Yes, I am still observing the issue that `onActivityStarted` is not triggered on the initial launch of the application when the MainActivity is extending `FlutterFragmentActivity`.

And I was able to reproduce this issue on both emulators and real device as well

**Comment by dam-ease** [comment] 2023-08-14 07:22
> But why is that in case of FlutterActivity, FlutterPlugin get registered first always and activity is registered later ?
Is this a bug in the Flutter itself ?

Hi @desusai7. Thanks for confirming. Since this seems to be the case in both cases and not only peculiar to `FlutterFragmentActivity`, this might be the expected behaviour. If I seem to be misinterpreting your issue, kindly let me know

**Comment by desusai7** [comment] 2023-08-14 07:41
Hey @dam-ease, 

> I was trying to point out that in both cases onActivityStarted seemed to have not been triggered on the initial launch. Are you still able to reproduce onActivityStarted on the initial launch in both cases on the latest versions?

No, this isn't the case with me. I am seeing different behaviours between `FlutterFragmentActivity` and `FlutterActivity`. 

In the case of `FlutterActivity`, I see `onActivityStarted` being triggered on the initial launch on both real devices and simulators. 

Whereas in the case of `FlutterFragmentActivity`, `onActivityStarted` is not triggered on the initial launch on both real devices and simulators. 

I am still seeing this difference in the behaviours between the usage of `FlutterActivity` and `FlutterFragmentActivity` on the latest version (3.10.6) of Flutter. 

Hope this is clear now

**Comment by dam-ease** [comment] 2023-08-14 09:04
Thanks for your response @desusai7. I understand you now. I seem to be reproducing the same with both `FlutterActivity` and `FlutterFragmentActivity`. Tested on the latest `master` and `stable` channels. I'd label this for more insights.

**Comment by desusai7** [comment] 2023-08-14 10:24
Thank you very much @dam-ease for looking into this and moving it further !

**Comment by gmackall** [comment] 2023-08-31 18:27
@gspencergoog I believe you recently dug into the intricacies of application lifecycle, do you have any advice or suggestions for the Android team on this bug

**Comment by desusai7** [comment] 2023-09-12 05:24
@gspencergoog / @gmackall, Can you help me with a reference to a PR (or) a particular class/part in the code which can help me dig to the bottom of the issue and I can contribute to it ?

**Comment by gspencergoog** [comment] 2023-09-12 14:59
@gmackall Sorry, I don't: the app lifecycle stuff I was working on was for surfacing the lifecycle changes the Framework, not for plugins, and I didn't really touch the Android implementation, since it already had application lifecycle support.

**Comment by reidbaker** [comment] 2023-09-14 18:55
We are not digging into this issue right now but here is some code in our packages repo that depends on the app lifecycle. Hopefully you can find a work around for what you are facing. https://github.com/flutter/packages/blob/050ad152bee61f66548486adc36da999bfd86e31/packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java#L121

**Comment by mossmana** [comment] 2024-04-08 19:51
@desusai7 [FlutterFragmentActivity](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java) has almost 90% of the same/similar code as [FlutterActivity](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java) but they haven't necessarily been kept in sync over time. I'll look into where there might be a discrepancy and cycle back. However, based on the comment in `FlutterFragmentActivity`, use of `FlutterActivity` is preferred. So, if your use case does not require `FlutterFragmentActivity`, I'd suggest using `FlutterActivity` in the meantime.

**Comment by mossmana** [comment] 2024-04-08 21:13
I noticed that FlutterActivity extends from [Activity](https://developer.android.com/reference/android/app/Activity.html), but FlutterFragmentActivity extends from [FragmentActivity](https://developer.android.com/reference/androidx/fragment/app/FragmentActivity) which extends from [ComponentActivity](https://developer.android.com/reference/androidx/activity/ComponentActivity). Modern apps should probably never extend directly from Activity.

**Comment by mossmana** [comment] 2024-04-09 18:51
It also appears that FlutterActivity directly implements [LifeCycleOwner](https://developer.android.com/reference/androidx/lifecycle/LifecycleOwner) but FlutterFragmentActivity relies indirectly on the LifeCycleOwner implementation as provided  in ComponentActivity. I will dig further.

**Comment by mossmana** [comment] 2024-04-09 20:03
> We are not digging into this issue right now but here is some code in our packages repo that depends on the app lifecycle. Hopefully you can find a work around for what you are facing. https://github.com/flutter/packages/blob/050ad152bee61f66548486adc36da999bfd86e31/packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java#L121

@reidbaker @stuartmorgan GoogleMapsPlugin is referencing FlutterLifecycleAdapter, but that doesn't seem to exist in the engine (main) and results in an `error: cannot find symbol.` when I try to copy over the [import](https://github.com/flutter/packages/blob/050ad152bee61f66548486adc36da999bfd86e31/packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java#L19) to the sample code provided. Do you happen to know where it lives now or if it was replaced by something else?

**Comment by stuartmorgan** [comment] 2024-04-09 20:12
It's from https://github.com/flutter/packages/tree/main/packages/flutter_plugin_android_lifecycle

**Comment by mossmana** [comment] 2024-04-09 22:30
As far as I can tell, there is no action that needs to be taken by the Flutter team to address this issue at this time. See https://github.com/desusai7/lifecycle_events/pull/1.

However, we should probably provide better documentation on how to make lifecycle aware plugins. I didn't include instructions in my PR on how to make the `lifecycle_events` depend on `flutter_plugin_android_lifecycle` as I did not spend additional time investigating.

**Comment by mossmana** [comment] 2024-04-09 22:34
@stuartmorgan @reidbaker I'm inclined to close this issue, but could use a second/third opinion.

**Comment by mossmana** [comment] 2024-04-29 18:27
@desusai7 I created a new [issue](https://github.com/flutter/flutter/issues/147540) to update our documentation. Closing this issue for now.

**Closed** 2024-04-29 18:27 UTC
Labels: platform-android, engine, P1, team-android, triaged-android
