### ISSUE TITLE
[Web] require.js:1961 Not allowed to load local resource: file:///F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/quote.dart

### ISSUE THREAD

**Issue by NullByte08** [flutter/flutter#62763] opened 2020-08-03 02:34 UTC
## Steps to Reproduce

1. move a file under the lib folder, to any other newly created package inside the lib folder. (quote.dart in my case)
2. import statements( wherever used for the moved file) will be changed to the file path of the moved file. Eg. " import "file:///F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/quote.dart"
3. Run the app on `Chrome`, webpage will not load. And only a blank white webpage is shown.

**Expected results:** 
Webpage should render
**Actual results:** 
Blank white webpage.
<details>
  <summary>Logs</summary>

Run window in Android Studio does not log anything. But, checking the error on developer tools in chrome 
``` 
require.js:1961 Not allowed to load local resource: file:///F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/nav_bar.dart
req.load @ require.js:1961
require.js:1961 Not allowed to load local resource: file:///F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/quote.dart
req.load @ require.js:1961
require.js:143 Uncaught Error: Script error for "F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/nav_bar.dart", needed by: packages/aboutme/home_page.dart
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
require.js:143 Uncaught Error: Script error for "F:/Flutter/FlutterProjects/aboutme_website/about_me/lib/elements/quote.dart", needed by: packages/aboutme/home_page.dart
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-08-03 12:51
Hi @NullByte08 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by NullByte08** [comment] 2020-08-04 00:52
`flutter doctor -v` 

```
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.21.0-1.0.pre at F:\Flutter\FlutterSDK\flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Cheenu\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Cheenu\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Cheenu\AppData\Local\Android\Sdk
    • Java binary at: F:\Win10\Android Win 10\Android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at F:\Win10\Android Win 10\Android studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at F:\Win10\IntelliJ\IntelliJ IDEA Community Edition 2019.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 1 category.
```
`flutter run --verbose`

```
[ +178 ms] executing: [F:\Flutter\FlutterSDK\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +159 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f25bd9c55c48c139524139b477d04b13e9f36b2c
[   +2 ms] executing: [F:\Flutter\FlutterSDK\flutter/] git tag --contains HEAD
[ +349 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-1.0.pre
           1.21.0-5.0.pre
[  +17 ms] executing: [F:\Flutter\FlutterSDK\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [F:\Flutter\FlutterSDK\flutter/] git ls-remote --get-url origin
[  +71 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +357 ms] executing: [F:\Flutter\FlutterSDK\flutter/] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +84 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: C:\Users\Cheenu\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +88 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +157 ms] Multiple devices found:
[  +34 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +3 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89
[   +4 ms] [0]: Web Server (web-server)
[   +1 ms] [1]: Chrome (chrome)
[   +5 ms] Please choose one:
[        ]  [0|1]
[        ] : 
[+7915 ms] 1
[+1630 ms] Found plugin path_provider at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[ +161 ms] Found plugin path_provider_linux at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +71 ms] Found plugin path_provider_macos at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[+1604 ms] Found plugin path_provider at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +5 ms] Found plugin path_provider_linux at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[ +144 ms] Generating F:\Flutter\FlutterProjects\aboutme_website\about_me\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +389 ms] Launching lib\main.dart on Chrome in debug mode...
[  +76 ms] Updating assets
[+2780 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +18 ms] Syncing files to device Chrome...
[  +40 ms] Found plugin path_provider at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +3 ms] Found plugin path_provider_linux at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +51 ms] Found plugin path_provider at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +2 ms] Found plugin path_provider_linux at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at F:\Flutter\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +32 ms] Generating F:\Flutter\FlutterProjects\aboutme_website\about_me\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[+2304 ms] <- reset
[ +241 ms] F:\Flutter\FlutterSDK\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev F:\Flutter\FlutterSDK\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root F:\Flutter\FlutterSDK\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\Cheenu\AppData\Local\Temp\flutter_tools.a12734f\flutter_tool.5ed899f6\app.dill --libraries-spec
file:///F:/Flutter/FlutterSDK/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root C:\Users\Cheenu\AppData\Local\Temp\flutter_tools.a12734f\flutter_tools.f8b6d234 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill
--platform file:///F:/Flutter/FlutterSDK/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +26 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+49943 ms] Syncing files to device Chrome... (completed in 52,638ms, longer than expected)
[   +1 ms] Synced 30.5MB.
[   +2 ms] <- accept
[   +3 ms] Caching compiled dill
[+1898 ms] [CHROME]:
[  +11 ms] [CHROME]:DevTools listening on ws://127.0.0.1:64299/devtools/browser/347ef7dd-645e-4a60-9fab-a89949fd82fd
[+29290 ms] "flutter run" took 99,045ms.
[  +10 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
[  +41 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:512:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:588:37)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #4      _rootRunUnary (dart:async/zone.dart:1198:47)
           #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #13     _rootRunUnary (dart:async/zone.dart:1198:47)
           #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #20     _rootRun (dart:async/zone.dart:1190:13)
           #21     _CustomZone.run (dart:async/zone.dart:1093:19)
           #22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +258 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +12 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by TahaTesser** [comment] 2020-08-04 08:10
Hi @NullByte08 
Not able to reproduce this issue on latest `dev` 

Things i tried
1. tried moving quote.dar to elements folder in VS Code, no issue while chrome was closed and also while chrome was running
2. tried moving quote.dar to elements folder in Android Studio, no issue while chrome was closed and also while chrome was running

Page loads every time

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.160 at /Users/taha/Code/flutter_master
    • Framework revision 31ee51a302 (8 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!

```

</details> 


I cannot reproduce this issue on latest dev channel.
Can you upgrade to dev and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by NullByte08** [comment] 2020-08-04 08:24
@TahaTesser I ran flutter upgrade about two days ago on the dev channel after I faced the issue, issue persisted back then.
Please try these steps, after closing chrome:
1. There are two files a.dart and b.dart. and both are under lib folder.
2. make another package under the lib folder ( say xyz).
3. There should be an import statement in file a.dart , that imports the file b.dart. 
4. Now move the file b.dart from under lib folder to the newly created package using darg and drop.
5. The import statement would change to path of the file b.dart in your system. Example, _import 'file:///C:/project_folder/lib/xyz/B.dart'_ 
6. Now run the chrome.
 You should get the error, and website should not load.

**Comment by TahaTesser** [comment] 2020-08-05 09:08
Hi @NullByte08 
i can reproduce the issue following steps https://github.com/flutter/flutter/issues/62763#issuecomment-668457556 , this is only happening Android Studio

![image](https://user-images.githubusercontent.com/48603081/89393293-3a008e00-d728-11ea-9a2a-6e0eed9458df.png)

###  Android Studio, Import is changed to local file system, when we drag the b.dart and drop it into xyz folder

```
import 'package:flutter/material.dart';
import 'file:///C:/Users/Taha/AndroidStudioProjects/master_flutter/lib/xyz/b.dart';
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FAB(),
    );
  }
}
```

###  VS Code, no import issues, when we drag the b.dart and drop it into xyz folder
```
import 'package:flutter/material.dart';
import 'package:master_flutter/xyz/b.dart';
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FAB(),
    );
  }
}
```

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel master, 1.21.0-6.0.pre.160, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-6.0.pre.160 at C:\Code\flutter
    • Framework revision 31ee51a302 (33 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details> 


Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-05 09:08 UTC
Labels: in triage
