### ISSUE TITLE
Flutter windows desktop screen comes up blank with 2 monitors connected to laptop

### ISSUE THREAD

**Issue by npatriquin** [flutter/flutter#149709] opened 2024-06-05 02:55 UTC
### Steps to reproduce

1. Windows desktop
2. Connect 2 monitors through a hub to a laptop
3. Compile and run flutter with VSCODE
4. Windows desktop display often comes up blank or largely blank

### Expected results

Posting this to let people know how to circumvent the problem. Took me weeks before I discovered the problem. If you stop and restart flutter several times it finally works with both monitors attached.
All works fine when disconnecting one of the two connected monitors.
All works fine in Android or Android emulator mode.
Circumvent by disconnecting one monitor from the hub and then restart Flutter. Then reconnect the monitor.
Once it works, you might not have to disconnect to start the next time.
I tried many different configurations regarding windows desktop parms, sizes, etc..
Seems consistent to me so hopefully someone who knows this code can easily reproduce.

flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.0)
[√] VS Code, 64-bit edition (version 1.86.2)
[√] VS Code, 64-bit edition (version 1.90.0-insider)
[√] Connected device (1 available)
[√] Network resources
• No issues found!

### Actual results

windows desktop screen comes up blank

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.0)
[√] VS Code, 64-bit edition (version 1.86.2)
[√] VS Code, 64-bit edition (version 1.90.0-insider)
[√] Connected device (1 available)
[√] Network resources

• No issues found!

</details>

**Comment by huycozy** [comment] 2024-06-05 10:55
Hi @npatriquin 
I don't have a Windows laptop but I have a Macbook with two monitors as below:

<img width="484" alt="Screenshot 2024-06-05 at 17 46 59" src="https://github.com/flutter/flutter/assets/104349824/36892080-c367-44f9-aa3e-58f5e3f7daed">

`LG` is the main monitor. When I run Flutter macOS app, the window can be displayed normally on main monitor.

There is something that needs to be clarified, please help to provide it:
1. What is your `main` monitor? Does this issue relate to this thing? (you can try switch the main/primary monitor and retry). If this factor is the cause, please check this https://github.com/flutter/flutter/issues/137321#issuecomment-1780946083 to see if it helps (check if you have PowerToys installed and some other experimental settings).
2. Does the issue occur on a newly created Flutter project? (To make sure no 3rd plugins affect this)
3. When the issue occurs, do you notice special warnings/exception logs from the output console where project runs?

**Comment by npatriquin** [comment] 2024-06-12 23:10
Sorry for delay in response. Problem did not reoccur until today. 

You were correct, when **I turned off PowerToys the screen showed correctly**.

**Comment by huycozy** [comment] 2024-06-13 03:45
Nice to know it's solved. Closing the issue

**Closed by huycozy** 2024-06-13 03:45 UTC
Labels: in triage
