### ISSUE TITLE
[IOS13][flutter run] ios-display issue / module importing failed

### ISSUE THREAD

**Issue by he2lec** [flutter/flutter#40542] opened 2019-09-16 01:32 UTC
I'm using `flutter run` on Mac OS Mojave, Xcode 11, and a ios 13.1 beta device on usb.
I tried on Xcode 10.3, on stable, beta, dev channels, and with ios-display 1.9.4 and 1.10.0-beta.3.

On flutter stable channel :

```
2019-09-16 01:04:44.142 ios-deploy[21322:293363] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Could not install build/ios/iphoneos/Runner.app on b54286e56fea33387fc501ba1c20f90ee4b7be96.
Try launching Xcode and selecting "Product > Run" to fix the problem:
```

Product>Run on Xcode  works great, but `flutter run` not (meaning no hot reloading).

It seems to be partially fixed on master channel thanks to #40398 , however on master i get:

```
Xcode build done.                                           20,4s
error: module importing failed: invalid pathname
Installing and launching...
```

Only the launch screen shows up on the device.

**Comment by jgrandchavin** [comment] 2019-09-16 07:58
Hello,

Exactly same issue. And build work directly from Xcode. The problem happened with flutter command.

**Comment by christopherfujino** [comment] 2019-09-16 16:28
Thanks for filing this! I am currently working on a fix for this. I am closing this issue as a duplicate of [#40448](https://github.com/flutter/flutter/issues/40448), please follow that issue for updates.

**Closed by christopherfujino** 2019-09-16 16:28 UTC
Labels: t: hot reload, tool, ⌺‬ platform-ios
