### ISSUE TITLE
[Windows] Strange behavior with FocusNode

### ISSUE THREAD

**Issue by TheCGDF** [flutter/flutter#62216] opened 2020-07-24 19:01 UTC
## Steps to Reproduce

Full code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      theme: ThemeData.dark(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final focusNode = FocusNode();
  final txtController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          focusNode: focusNode,
          autofocus: true,
          controller: txtController,
          onSubmitted: (token) => setState(() {
            txtController.clear();
            focusNode.requestFocus();
          }),
        ),
      ),
    );
  }
}
```

Just run it. Input "aaa" and press Enter, then input "bbb". **Do not touch mouse.**

**Expected results:** 

TextField's content: bbb
It works correctly on Andorid. 
If delete code `focusNode.requestFocus();`, it works correctly too.

**Actual results:** 

TextField's content: aaabbb
<details>
  <summary>Logs</summary>

 flutter doctor -v
```
[√] Flutter (Channel master, 1.21.0-6.0.pre.17, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.21.0-6.0.pre.17 at D:\Software\flutter
    • Framework revision e64fe11542 (18 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Software\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Software\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.6.5)
    • Visual Studio at D:\Software\VS2019
    • Visual Studio Enterprise 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Software\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.17763.1039]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2020-07-24 19:17
Duplicate of https://github.com/flutter/flutter/issues/59140

**Closed by stuartmorgan** 2020-07-24 19:17 UTC
