### ISSUE TITLE
[desktop] Isolate task causes high CPU usage 

### ISSUE THREAD

**Issue by xinlake** [flutter/flutter#85745] opened 2021-07-02 02:21 UTC
## Details
After an isolated task is started, the CPU usage increases rapidly and remains at a high level even if the task is done. Here is my test code

``` dart
import 'dart:io';
import 'dart:isolate';

import 'package:flutter/material.dart';

class IsoTestPage extends StatefulWidget {
  IsoTestPage({required this.title});

  final String title;

  @override
  _IsoTestState createState() => _IsoTestState();
}

class _IsoTestState extends State<IsoTestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () async => Isolate.spawn(_isoHttpGet, null),
          child: Text("test isolate http get"),
        ),
      ),
    );
  }
}

void _isoHttpGet(dynamic notUsed) async {
  var client = new HttpClient();
  client.findProxy = HttpClient.findProxyFromEnvironment;
  client.badCertificateCallback = (certificate, host, port) => true;

  var request = await client.getUrl(Uri.parse("https://github.com"));
  var response = await request.close();

  print(response.statusCode);
  client.close();
}
```

The CPU usage is normal when the isolated task is not started.
![Screenshot 2021-07-02 095245](https://user-images.githubusercontent.com/31364428/124210176-8f524480-db1d-11eb-930d-2fbd97db5d67.png)

After an isolated task is started (click the button).
![Screenshot 2021-07-02 095357](https://user-images.githubusercontent.com/31364428/124210220-a09b5100-db1d-11eb-9a8c-b57b28ea3f24.png)

This problem may be related to [#78517](https://github.com/flutter/flutter/issues/78517), To reduce the interference I have modified the source code of the Win32 event loop ({project-root}\windows\runner\run_loop.cpp).

```c++
void RunLoop::Run() {
  MSG msg;
  while (GetMessage(&msg, nullptr, 0, 0)) {
    TranslateMessage(&msg);
    DispatchMessage(&msg);
  }
}
```

## Enviroment
![Screenshot 2021-07-02 085539](https://user-images.githubusercontent.com/31364428/124209845-e4da2180-db1c-11eb-95ff-eea1205fcd33.png)

**Comment by Jazzykhan** [comment] 2021-07-02 02:36
Hi, you are doing flutter desktop, can you answer my question please?
is it possible to move a full folder from one place to another in flutter desktop?
thanks

**Comment by xinlake** [comment] 2021-07-02 03:49
@Jazzykhan What about listing the files and directories of the folder, copying each element to another place, deleting them?

**Comment by xinlake** [comment] 2021-07-06 02:52
I update Flutter to 2.2.3, refresh the project, and the problem persists.
![2 2 3](https://user-images.githubusercontent.com/31364428/124533674-5b409180-de45-11eb-9552-ad1c4efbfae4.png)

Still caused a high CPU usage.
![2 2 3-refresh](https://user-images.githubusercontent.com/31364428/124535062-18cc8400-de48-11eb-8666-23551d60e383.png)

**Comment by TahaTesser** [comment] 2021-07-06 08:53
Hi @xinlake 
Thanks for filing the issue,  Indeed the CPU usage increases rapidly even with a single click, and when clicking multiple times the whole system slows down as the CPU  usage gets really high. 

We are able to reproduce the CPU usage on multiple desktop platforms


Used the following minimal code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:io';
import 'dart:isolate';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: IsoTestPage(
        title: 'Test',
      ),
    );
  }
}



class IsoTestPage extends StatefulWidget {
  IsoTestPage({required this.title});

  final String title;

  @override
  _IsoTestState createState() => _IsoTestState();
}

class _IsoTestState extends State<IsoTestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () async => Isolate.spawn(_isoHttpGet, null),
          child: Text("test isolate http get"),
        ),
      ),
    );
  }
}

void _isoHttpGet(dynamic notUsed) async {
  var client = new HttpClient();
  client.findProxy = HttpClient.findProxyFromEnvironment;
  client.badCertificateCallback = (certificate, host, port) => true;

  var request = await client.getUrl(Uri.parse("https://github.com"));
  var response = await request.close();

  print(response.statusCode);
  client.close();
}
``` 

</details>

### Windows 
|    |  CPU Usage Preview | 
| :---: | :---: | 
| Single click |  <img src="https://user-images.githubusercontent.com/48603081/124567027-43b8d700-de4c-11eb-86fd-6ec2dd4cffd8.png"  />	|
| Multiple clicks | <img src="https://user-images.githubusercontent.com/48603081/124566984-369be800-de4c-11eb-88e2-1cd32a10084d.png"  /> |





|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.51]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.84, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.4.0-1.0.pre.84 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 691fa19dd7 (2 hours ago), 2021-07-06 02:06:04 -0400
    • Engine revision c1ce39ecb7
    • Dart version 2.14.0 (build 2.14.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.51]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.64

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced



### macOS (intel)

|    |  CPU Usage Preview | 
| :---: | :---: | 
| Single click |  <img src="https://user-images.githubusercontent.com/48603081/124567480-b75ae400-de4c-11eb-9f2e-448e8c4a1965.png"  />	|
| Multiple clicks | <img src="https://user-images.githubusercontent.com/48603081/124567466-b3c75d00-de4c-11eb-9542-94972172151f.png"  /> |


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.84, on macOS 12.0 21A5268h
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.84 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 691fa19dd7 (2 hours ago), 2021-07-06 02:06:04 -0400
    • Engine revision c1ce39ecb7
    • Dart version 2.14.0 (build 2.14.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced


### macOS (M1)

|    |  CPU Usage Preview | 
| :---: | :---: | 
| Multiple clicks | <img src="https://user-images.githubusercontent.com/48603081/124571736-be83f100-de50-11eb-8745-84e0a264725d.png"  /> |


Reproduced on Flutter master 2.4

### Linux

|    |  CPU Usage Preview | 
| :---: | :---: | 
| Single click |  <img src="https://user-images.githubusercontent.com/48603081/124568179-5253be00-de4d-11eb-8188-2d453a10bf2b.png"  />	|
| Multiple clicks | <img src="https://user-images.githubusercontent.com/48603081/124568185-5384eb00-de4d-11eb-9949-684b0234fca6.png"  /> |





|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.84, on Pop!_OS 21.04
    5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.4.0-1.0.pre.84 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 691fa19dd7 (2 hours ago), 2021-07-06 02:06:04 -0400
    • Engine revision c1ce39ecb7
    • Dart version 2.14.0 (build 2.14.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04
      5.11.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced

When running the same code on the web, CPU usage spikes aren't observed, even with multiple clicks

**Comment by xinlake** [comment] 2021-07-06 12:41
@TahaTesser
Thank you for making this problem clear

**Comment by yixiaco** [comment] 2021-07-30 10:26
// Isolate will not be actively released
```dart
Isolate lsolate = await Isolate.spawn(_isoHttpGet, null);
lsolate.kill();
```
A quick way to create isolate is compute()
```dart
import 'package:flutter/foundation.dart';
compute(_isoHttpGet, null);
```

**Comment by yixiaco** [comment] 2021-07-30 10:28
![image](https://user-images.githubusercontent.com/30982989/127640094-069d746a-301b-4caa-a664-e80f58f002a1.png)
The isolate that has not been released is recorded here

**Comment by clarkezone** [comment] 2021-08-05 14:06
@knopp ring any bells?

**Comment by knopp** [comment] 2021-08-05 14:11
The flutter event loop has nothing to do with isolates, which have their own dart loop. So it's probably completely unrelated to https://github.com/flutter/flutter/issues/78517 (also if it happens to other platforms).  Seems that it is reproducible though? I'll take a look, possibly today.

**Comment by knopp** [comment] 2021-08-07 13:21
This seems to be a problem between HTTP client, streams and IOService dispatch. For example if the response is drained before closing the client, CPU load is fine (`response.drain();`). Also if the client is closed with `force=true`, it will terminate the stream and the isolate will quit without issues, again, no CPU load.

So the bottom line is, you either need to actually read the response, or close the client with `force=true`. Otherwise you get 100% CPU load on the isolate. I'm not sure if this is intentional behavior, it is possible that it just slipped under the radar, since most of the time when you get HTTP response you want to read it too.

**Comment by xinlake** [comment] 2021-08-07 15:26
It seems that it was my mistake, there is no basis to show that it causes by isolate, this problem will occur even if I don’t use isolate.

I have tested it again without isolate, as @knopp said, the CPU load will be fine if the response is read before closing the client. But, if close the client only with `client.close(force: true);` (without `response.drain();`) the CPU load is still high.

**Comment by knopp** [comment] 2021-08-07 15:29
`client.close(force: true);` fixes the CPU load for me (both in original and in new isolate), but it might be OS specific. (tested on macOS)

**Comment by LiveRock** [comment] 2021-08-24 09:32
On the Mac M1, the MacOS desktop app runs ok with normal CPU.
But on Windows 10, the app runs with VERY HIGH CPU load.
I can't find the source of the issue.
Anyone facing this as well.
I am on

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

flutter doctor:
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-SG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)
```

**Comment by Slyklaw** [comment] 2021-08-29 15:47
> Anyone facing this as well.

Yes, with just the starter template app, Windows 10 CPU load isn't good on 2.2.3. Performance on Beta channel (2.5.0) is great.

**Comment by xinlake** [comment] 2021-08-30 07:21
I refreshed the test project and did a simple test, found that the CPU load problem can be solved by `respond.drain();` or `HttpClient.close(force: true)`. It is code mistake, or you may improve the HttpClient API or documents ^^.
``` dart
  var client = new HttpClient()
    ..findProxy = HttpClient.findProxyFromEnvironment
    ..badCertificateCallback = (certificate, host, port) => true;

  var request = await client.getUrl(Uri.parse("https://github.com"));
  var respond = await request.close();
  respond.drain(); // add this

  client.close(force: true); // or add this 
```

**Comment by xinlake** [comment] 2021-08-30 07:25
I think is issue can be closed ^^.

**Comment by knopp** [comment] 2021-08-30 07:27
Indeed. If there are other CPU issues please open separate issue. This is caused by network socket not being read from which shouldn't under normal use of HttpClient()/

**Closed by knopp** 2021-08-30 07:27 UTC
Labels: engine, severe: performance, platform-mac, platform-windows, platform-linux, a: desktop, has reproducible steps, P4, found in release: 2.2, found in release: 2.4
