### ISSUE TITLE
Expose controller and focus node to AutoComplete widget

### ISSUE THREAD

**Issue by KaushikGupta007** [flutter/flutter#150616] opened 2024-06-21 14:21 UTC
### Use case

The current implementation of the AutoComplete widget in Flutter does not expose the text editing controller and focus node. This leads to several issues:

- I need to make my controller equal to the AutoComplete controller, which is not intuitive.
- When the AutoComplete widget is not visible, it disposes of the controller, causing errors if I try to change the value through my controller.
Specifically, the following error occurs:
`A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.`

### Proposal

Expose the `TextEditingController` and `FocusNode` used by the `AutoComplete` widget. This will allow developers to manage these objects themselves, preventing unwanted disposal and making it easier to control the widget’s behavior programmatically.

```dart
class CustomAutoComplete extends StatelessWidget {
  final TextEditingController controller = TextEditingController();
  final FocusNode focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return AutoComplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        // Your options logic here
      },
      controller: controller, // Proposed property
      focusNode: focusNode, // Proposed property
    );
  }
}
```
**Benefits**

- Prevents disposal of the controller and focus node.
- Allows greater flexibility and control over the AutoComplete widget.
- Aligns with other Flutter widgets that expose their controllers and focus nodes.

**Related Pull Request**
There was a related pull request (PR #146995)  that attempted to address this issue, but there hasn't been any recent activity on it. It proposed changes to expose the controller and focus node in the AutoComplete widget. However, it seems to be stalled.

**Comment by huycozy** [comment] 2024-06-24 06:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/146994. Please follow up on it for updates.

**Closed by huycozy** 2024-06-24 06:22 UTC
Labels: in triage
