### ISSUE TITLE
Upgrade flutter sdk version to 1.22.0-1.0.pre and Dart SDK An error occurred when version 2.10.0

### ISSUE THREAD

**Issue by InTheClodus** [flutter/flutter#75312] opened 2021-02-03 03:53 UTC
LinearGradient is used for the effect of gradient colors, but after I upgraded, colors cannot be used. View the source code like this

```dart
  const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);
```
The required of the LinearGradient method is missing one @
As a result, colors cannot be used when using this component

**Comment by thisisamank** [comment] 2021-02-03 05:36
Try restarting IDE, or invalidating the cache of IDE, it should work then.

**Comment by pedromassangocode** [comment] 2021-02-03 07:11
Duplicate of https://github.com/flutter/flutter/issues/63908. See https://github.com/flutter/flutter/issues/63908#issuecomment-674902435.

**Closed by pedromassangocode** 2021-02-03 07:11 UTC

**Comment by InTheClodus** [comment] 2021-02-03 07:31
> Try restarting IDE, or invalidating the cache of IDE, it should work then.

Thanks for your answer

**Comment by InTheClodus** [comment] 2021-02-03 07:32
> Duplicate of #63908. See [#63908 (comment)](https://github.com/flutter/flutter/issues/63908#issuecomment-674902435).

Thank you for your answer, next time I will search for similar questions before Issues
