### ISSUE TITLE
Make SVG file support built in to flutter

### ISSUE THREAD

**Issue by deyar4** [flutter/flutter#55229] opened 2020-04-20 20:06 UTC
Please make SVG support built in to flutter because the packages that are available for SVG support have some problems in which you can only use SVG's like a widget and cannot be applied to certain areas of your application such as box Decoration images and etc... Thanks.

**Comment by goderbauer** [comment] 2020-04-22 22:09
Duplicate of https://github.com/flutter/flutter/issues/15501, we currently have no plans to add this. I would suggest filing issues with the svg package if you find support lacking for the things you want to do.

**Closed by goderbauer** 2020-04-22 22:09 UTC
Labels: framework, severe: new feature
