### ISSUE TITLE
Update image to 2.1.7

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#43216] opened 2019-10-21 21:59 UTC
The `image` dependency should be updated to `2.1.7` from `2.1.4`. I could not figure out where the dependencies are *auto-generated*, hence, I did not create a pull request.

Here are the occurences: https://github.com/flutter/flutter/search?l=YAML&q=image%3A+2.1.4+%23+THIS+LINE+IS+AUTOGENERATED+-+TO+UPDATE+USE+%22flutter+update-packages+--force-upgrade%22

**Comment by Hixie** [comment] 2019-12-02 17:31
This will happen when we next roll packages, as it says in the files linked to above. Feel free to submit a PR to do it.

I'm closing this as a dupe of https://github.com/flutter/flutter/issues/37985 for now.

**Closed by Hixie** 2019-12-02 17:31 UTC
Labels: proposal
