### ISSUE TITLE
Library not loaded: @rpath/Flutter.Framework

### ISSUE THREAD

**Issue by jacob-chapman** [flutter/flutter#48035] opened 2020-01-01 14:05 UTC
The application runs fine on Android Emulators and iOS simulators, however will instantly crash on startup on a physical iOS Device. 

## Steps to Reproduce

1. Create a new Flutter Application
2. Attempt to run it on a physical iOS Device
3. Fails on Startup after trusting the cert.

**iOS**
**13.3.1**
**iPhone 8+**

## Logs

Attached
[FlutterRunLog.docx](https://github.com/flutter/flutter/files/4014136/FlutterRunLog.docx)

```console
✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132,
    locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/jchapman/development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jchapman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/jchapman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview 3.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b02)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/jchapman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5900203/Android
      Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/jchapman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.5916306/Android
      Studio 3.6 Preview.app/Contents
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/jchapman/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Jacob’s iPhone    • 05b0b2b5c004689dbfcd867cfc2cd3aa582c43b4 • ios • iOS
      13.3.1
    • iPhone 11 Pro Max • 1B108115-3383-48CF-B446-06A6831AA10D     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)


```

**Comment by jmagman** [comment] 2020-01-31 21:22
This was created first, but it's a duplicate of https://github.com/flutter/flutter/issues/49504 which has more information.

**Closed by jmagman** 2020-01-31 21:22 UTC
Labels: severe: crash, t: xcode, tool, ⌺‬ platform-ios

**Comment by chenyongze** [comment] 2020-02-16 14:56
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/95E1306B-2047-4AA1-8593-0A87457E3874/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/95E1306B-2047-4AA1-8593-0A87457E3874/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/95E1306B-2047-4AA1-8593-0A87457E3874/Runner.app/Frameworks/Flutter.framework/Flutter'

(lldb)

**Comment by Dimitross** [comment] 2020-02-18 16:52
Any progress to fix this bug??

**Comment by jmagman** [comment] 2020-02-18 19:24
See comment at https://github.com/flutter/flutter/issues/49504#issuecomment-581554697.
> This is an issue with iOS 13.3.1 on a real device, not the simulator. This should not impact apps that are already distributed to the App Store (meaning: your customers are not hitting this crash).
> 
> This is not an issue Flutter can work around. ALL dynamic frameworks (not in the iOS SDK) are having this problem. See:
> 
> * [#49504 (comment)](https://github.com/flutter/flutter/issues/49504#issuecomment-580966141)
> * https://forums.developer.apple.com/message/404653
> * https://stackoverflow.com/questions/60015309/running-ios-apps-causes-runtime-error-for-frameworks-code-signature-invalid
> * [Alamofire/Alamofire#3051](https://github.com/Alamofire/Alamofire/issues/3051)
> * [mapbox/mapbox-gl-native-ios#157](https://github.com/mapbox/mapbox-gl-native-ios/issues/157)
> 
> You can:
> 
> 1. Use a non-Personal Team provisioning profile.
> 2. Run on the 13.3.1 simulator.
> 3. Test on a real iOS device running 13.3 or lower.
> 
> You can indicate you are also hitting this by adding a 👍 to this issue. Please do not add "me too" comments; all iOS developers on 13.3.1 are hitting this issue.
> 
> We've escalated to Apple (FB7562472) and will let you know if we hear anything.

**Comment by xloc** [comment] 2020-03-02 09:54
There's an update in [#49504 (comment)](https://github.com/flutter/flutter/issues/49504#issuecomment-592767041). Hope that would help you also.

> - Install the beta profile on your test device and install iOS 13.4 beta 3.
> - Wait for iOS 13.4 to be released.

**Comment by ColemanTO** [comment] 2020-04-04 20:24
I just installed iOS 13.4 and my Flutter app no longer crashes on Start up.
