### ISSUE TITLE
 AppLifecycleState.detached Not being called (Flutter version 2.2.2, Android 11)

### ISSUE THREAD

**Issue by yashwon1** [flutter/flutter#84713] opened 2021-06-16 15:48 UTC
case AppLifecycleState.detached:
        print('LIFECYCLE: $state');
        break;

Instead I get a message: Lost Connection

**Comment by TahaTesser** [comment] 2021-06-17 08:25
Hi @yashwon1 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/57594
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-17 08:25 UTC
Labels: in triage
