### ISSUE TITLE
Black screen with the latest Flutter alpha

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#589] opened 2015-11-25 19:12 UTC
```
git pull
remote: Counting objects: 142, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 142 (delta 65), reused 64 (delta 64), pack-reused 67
Receiving objects: 100% (142/142), 27.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (91/91), completed with 44 local objects.
From https://github.com/flutter/flutter
   7be58b1..f91c3df  alpha      -> origin/alpha
   1d0e193..a368cd7  master     -> origin/master
```

Do you know of what might have changed between 7be58b1 and f91c3df that might cause this? I can still tap buttons to get Ink Splashes, but despite trying a couple themes, my app remained on a black screen. (Black text on black background.)

I could look into this more if needed, but for now, I'm reverting back to 7be58b1. (I'm using `pub run flutter_tools run_mojo`)

**Comment by abarth** [comment] 2015-11-25 20:41
`pub run flutter_tools run_mojo`  <--- That shouldn't work.

Instead, just use the `flutter run_mojo`, where `flutter` is the script in `bin/flutter`.  We don't use `pub run` anymore.

**Comment by abarth** [comment] 2015-11-25 20:52
I was able to reproduce the issue on Android (but not on Linux).  Investigating.

**Comment by abarth** [comment] 2015-11-25 21:31
Fixed in https://github.com/flutter/engine/commit/980f874405175d28085bd5cb61995f4a91818326.  We'll need to publish the engine for you to get a new binary with the fix.  Given that it's thanksgiving tomorrow, that will probably happen early next week.

**Closed by abarth** 2015-11-25 21:31 UTC
Labels: affects: mojo

**Comment by afandria** [comment] 2015-11-25 22:32
Thanks @abarth.

Regarding `flutter run_mojo`, I do a dependency path import on flutter_tools, which is why `pub run flutter_tools run_mojo` works. I haven't done set the path to flutter's bin directory yet, so I have been relying on `pub run` to execute these scripts. I plan to move forward in the future, just not at this time.

**Comment by abarth** [comment] 2015-11-25 22:33
Ok.  Yeah, I guess that will work.  It will just be slow to run because `pub run` disables a bunch of optimizations if you have a path dependency.
