### ISSUE TITLE
Mac presubmit queues are out of SLO

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#114656] opened 2022-11-04 01:38 UTC
I've had several PRs the past 2 weeks be out of SLO (stuck in queue for 2 hours). I don't send PRs during the peak hours, and I expect this is worse for those contributing during those hours.

Example PR: https://github.com/flutter/flutter/pull/114646 (first commit was queued for 2 hours)

**Comment by godofredoc** [comment] 2022-11-04 03:36
2h is probably too much but a huge increase in execution|queue time is expected  after https://github.com/flutter/flutter/issues/113539 where we are explicitly cleaning the local xcode cache

**Comment by godofredoc** [comment] 2022-11-04 16:58
Setting as P1 seems like mac capacity is at 100% utilization from 6:00AM PST to 5:00PM PST.

Next step we need to identify if this is normal usage or something strange is happening.

**Comment by godofredoc** [comment] 2022-11-04 17:04
From the data it seems like we've always had peeks of 30M 100% utilization at ~9:00AM PST but we started to have 3+ peeks per day on 10/17/2022. Things got really bad on 10/24/2022 where we started with 100% utilization from 9:00 to 5:00

**Comment by keyonghan** [comment] 2022-11-04 17:21
The local cache cleanup happened on 10/19 (https://github.com/flutter/flutter/pull/113729), the queue time (90th%) was <1min for 10/19-10/24.
The queue time started increasing from 10/25
10/25-10/26: 2.13 min
10/26-10/27: 42.25 min
10/17-10/28: 43.43 min
10/28-11/04: 28.4 min

**Comment by keyonghan** [comment] 2022-11-04 17:27
One correlated change per the timing is the quota increase (cl/483782210). @godofredoc Are you comfortable with a revert?

**Comment by godofredoc** [comment] 2022-11-04 17:32
> One correlated change per the timing is the quota increase (cl/483782210). @godofredoc Are you comfortable with a revert?
That change is supposed to help. Can we take a look if the repo sync time has increased? if cold checkouts are >7m then please do not revert.

**Comment by godofredoc** [comment] 2022-11-04 17:46
Ths is 

> 0/17-10/28: 58.68 min



> 



> The local cache cleanup happened on 10/19 (#113729), the queue time (90th%) was <1min for 10/19-10/24.
> The queue time started increasing from 10/25
> 10/25-10/26: 6.06 min
> 10/26-10/27: 60.5 min
> 10/17-10/28: 58.68 min
> 10/28-11/04: 85.27 min

Can you please post daily data for: 10/25, 10/27, 11/03?

**Comment by keyonghan** [comment] 2022-11-04 17:46
The engine source checkout was not improved with this quota increase CL. It has been taking 5-7 mins before and after. See 
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20clang-tidy?cursor=id%3E8799256324311980481&limit=200
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Unopt?cursor=id%3E8799256222795131969&limit=200
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine?cursor=id%3E8799256222304648017&limit=200
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20clang-tidy?cursor=id%3E8799263756679076865&limit=200

**Comment by godofredoc** [comment] 2022-11-04 17:50
That is expected, cl/483782210 fixes peek quota whith checkouts taking 40mins in try.

5-7 mins is expected in cold checkouts if we are getting consistent 5-7 mins checkouts then that is a bug that need to be fixed.

**Comment by keyonghan** [comment] 2022-11-04 17:56
> Can you please post daily data for: 10/25, 10/27, 11/03?

10/25: 6 min
10/27: 58 min
11/03: 100 min

**Comment by godofredoc** [comment] 2022-11-04 18:00
Are this 90th percentiles? can we also get the 50th?

**Comment by keyonghan** [comment] 2022-11-04 18:07
Here are the comparison between 90th and 50th, plus the build number:
date.     90th      50th     No. of builds
10/25.   6            0           1192
10/26.   60          15         1983
10/27.    58          21         2046
11/03.    100        7            2493

**Comment by keyonghan** [comment] 2022-11-04 18:12
When did you enable the Mac engine v2 builders?

**Comment by godofredoc** [comment] 2022-11-04 18:21
Nice, in this case the 50th %tile is giving us a better signal.

* The 10/26 increase in the 90th %tile could be caused by https://github.com/flutter/engine/pull/37051 
* The 11/03 increase in the 90th %tile could be caused by https://github.com/flutter/engine/pull/37274

Higher queue times are expected in engine_v2 under the current conditions because they require multiple bots to complete.

The decrease in the 50th percentile which I believe most of the legacy builds will fit into, except for engine_v2, web engine and fuchsia builders was caused by the following PRs:

* https://github.com/flutter/engine/pull/37246
* https://flutter.googlesource.com/infra/+/f36c28ca89027e3d80d18e68c6e8c5e82fea4e7e
* cl/483782210

**Comment by godofredoc** [comment] 2022-11-04 18:57
Probably we are making thing a bit worse for a short period of time ~4h while we re-allocate mac machines to different pools.

The plan to address the queue time is as follows:

- [ ] Fix checkout caches in mac builders
- [ ] Remove the flag to always clean the xcode caches. The caches of all the machines should be clean by now and some - logic has been added to cleanup the cache only when using simulator runtimes. 
- [ ] Ensure https://flutter.googlesource.com/recipes/+/e02f2b41ba98db6d230fee81689e4a6e89526453 is CP to stable and beta versions of recipes
- [ ] Use linux machines for orchestrators in engine_v2

**Comment by godofredoc** [comment] 2022-11-04 19:15
@khyati82 this is the impact we were expecting during the transition of legacy to engine_v2.

**Comment by godofredoc** [comment] 2022-11-04 19:59
CPs of https://flutter.googlesource.com/recipes/+/e02f2b41ba98db6d230fee81689e4a6e89526453  to stable and beta:

* https://flutter-review.googlesource.com/c/recipes/+/35601
* https://flutter-review.googlesource.com/c/recipes/+/35600

**Comment by keyonghan** [comment] 2022-11-04 20:27
https://chrome-internal-review.googlesource.com/c/infradata/config/+/5074772 to move half (8) bots from staging to try.

**Comment by keyonghan** [comment] 2022-11-04 20:32
> Use linux machines for orchestrators in engine_v2

Do you mean to use linux VMs to host Mac engine_v2 builders?

**Comment by godofredoc** [comment] 2022-11-04 20:44
> > Use linux machines for orchestrators in engine_v2
> 
> Do you mean to use linux VMs to host Mac engine_v2 builders? @godofredoc

The current implementation will make this look weird. Basically I meant to change https://github.com/flutter/engine/blob/main/.ci.yaml#L327 to use a linux machine rather than mac. Which I believe requires to change `Mac mac_android_aot_engine` to `Linux mac_android_aot_engine`

**Comment by godofredoc** [comment] 2022-11-05 01:49
CL to default to not cleaning source code caches in Web Engine builds: https://flutter-review.googlesource.com/c/recipes/+/35661

**Comment by gaaclarke** [comment] 2022-11-08 00:24
I'm not sure how you are distributing mac resources but fwiw https://flutter-review.git.corp.google.com/c/recipes/+/35760 should lower mac clang-tidy bot execution 5-10m.  The number of linted files is going from 800->600.  Hopefully that helps a bit.

**Comment by keyonghan** [comment] 2022-11-23 20:07
Queue time drops to 20mins for past two weeks. Moving to TD for further optimization track.

**Closed** 2023-03-03 02:51 UTC
Labels: team: infra
