### ISSUE TITLE
Regression in skwasm benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144622] opened 2024-03-05 17:37 UTC
SkiaPerf flagged some regressions in skwasm benchmarks last week.

https://flutter-flutter-perf.skia.org/e/?begin=1707761887&end=1709659446&keys=Xccd896008d9cebd528f259c8c18ce490&requestType=0&selected=commit%3D39546%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dbench_material3_scroll_semantics.skwasm.drawFrameDuration.average%252Ctest%253Dweb_benchmarks_skwasm%252C&xbaroffset=39546

On https://github.com/flutter/flutter/pull/144208

Maybe? https://github.com/flutter/engine/pull/50928 cc @eyebrowsoffire

**Comment by eyebrowsoffire** [comment] 2024-03-05 17:38
Duplicate of https://github.com/flutter/flutter/issues/144254

**Closed by eyebrowsoffire** 2024-03-05 17:38 UTC
Labels: team-web
