### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by vallerydelexy** [flutter/flutter#158499] opened 2024-11-12 08:22 UTC
## Command
```sh
flutter run --machine --start-paused -d 00008110-000435503E2A401E --devtools-server-address http://127.0.0.1:9100/ --target /Users/rizki.aprita/Documents/projects/ca-esign-mobile/lib/main.dart --dart-define-from-file=.vscode/env.json
```

## Steps to Reproduce
1. run the app from vscode to iphone 13

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.0.1 24A348 darwin-arm64, locale en-ID)
    • Flutter version 3.24.1 on channel stable at /Users/rizki.aprita/Documents/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rizki.aprita/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • joko.setiawan’s iPhone (mobile) • 00008110-000435503E2A401E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849
### Plugins
alh_pdf_view-2.0.1
alh_pdf_view_android-2.0.0
alh_pdf_view_ios-2.0.0
app_integrity_checker-1.0.5
app_links-3.4.3
barcode_scan2-4.2.4
camera-0.10.5+2
camera_android-0.10.8+2
camera_avfoundation-0.9.13+2
camera_web-0.3.1+4
device_info_plus-10.1.2
file_picker-5.5.0
firebase_core-2.32.0
firebase_core_web-2.18.1
firebase_dynamic_links-5.5.7
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_file_dialog-3.0.1
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.15
flutter_windowmanager-0.2.0
freerasp-6.7.0
geolocator-13.0.1
geolocator_android-4.1.4
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
get_radio_version_plugin-1.0.0
google_mlkit_commons-0.8.1
google_mlkit_text_recognition-0.13.1
image_cropper-8.0.2
image_cropper_for_web-6.0.2
image_picker-0.8.7+5
image_picker_android-0.8.6+19
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
local_auth-2.2.0
local_auth_android-1.0.40
local_auth_darwin-1.3.1
local_auth_windows-1.0.8
open_file-3.3.2
package_info_plus-8.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
pdf_render-1.4.10
permission_handler-10.2.0
permission_handler_android-10.2.1
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
root_jailbreak_sniffer-1.0.6
safe_device-1.1.8
share_plus-7.2.2
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
webview_flutter-4.2.1
webview_flutter_android-3.7.1
webview_flutter_wkwebview-3.4.4

**Comment by danagbemava-nc** [comment] 2024-11-12 08:31
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-11-12 08:31 UTC
Labels: r: duplicate

**Comment by vallerydelexy** [comment] 2024-11-12 09:36
https://github.com/flutter/flutter/issues/150131

**Comment by vallerydelexy** [comment] 2024-11-16 08:12
> @vallerydelexy Can you confirm this is fixed after following these instructions?
> 
> System Settings -> Privacy & Security -> Local Network -> [Find your IDE] -> Toggle ON, then restart your phone.

yeah i already confirmed it here https://github.com/flutter/flutter/issues/150131#issuecomment-2470042067
its working.

but maybe better error message would help us developers
