### ISSUE TITLE
[Skia / CanvasKit] Buttons doesn't work with browser zoom < 50% anymore.

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#66118] opened 2020-09-18 14:54 UTC
## Steps to reproduce
1. Copy this code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Center(
        child: RaisedButton(
          onPressed: () => print("Pressed!"),
          child: Text("Button"),
        ),
      ),
    );
  }
}
```
2. Run flutter web with skia
3. Set browser zoom to < 50%
4. Try to press the button --> `onPressed` will never be called + onHover doesn't work

**Expected results:** 
Buttons should work as expected.

**Actual results:** 
![Button-Bug](https://user-images.githubusercontent.com/24459435/93612022-52262700-f9cf-11ea-9b33-d48d99ea0214.gif)

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.55, on Mac OS X 10.15.5 19F101,
    locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.0)
[✓] Connected device (3 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone
      von Roland is connected. (code -13)

• No issues found!
```

</details>

**Comment by AndroidNils** [comment] 2020-09-18 14:54
Maybe this bug is related to #66117

**Comment by TahaTesser** [comment] 2020-09-18 15:20
Hi @AndroidNils 
Unable to reproduce this issue using release mode or debug mode 

`flutter run --debug --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome`
`flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome`

Tried on the latest `Channel master, 1.22.0-10.0.pre.252,` channel, looks you're on an older `Channel master, 1.21.0-10.0.pre.55` channel.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48603081/93614491-d7213880-f9ef-11ea-8062-ea6cf4b23f27.gif)
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Center(
        child: RaisedButton(
          onPressed: () => print("Pressed!"),
          child: Text("Button"),
        ),
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.252, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.252 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 78929661fb (5 minutes ago), 2020-09-18 08:08:30 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.102

• No issues found!
```

</details> 


I cannot reproduce this issue on the latest `master` channel.
Can you please upgrade to the latest  `master` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`


Thank you

**Comment by TahaTesser** [comment] 2020-10-14 12:37
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 12:37 UTC
Labels: in triage
