### ISSUE TITLE
cloud_firestore-2.5.4 | path_provider-2.0.6 uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#93501] opened 2021-11-11 20:16 UTC
### Steps to Reproduce
Create a new project
Add dependency for cloud_firestore: ^2.5.4 | path_provider: ^2.0.5 
flutter run or flutter build apk

### Logs

```console
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.5.4\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.6\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

```

```console
PS C:\MyDartProjects\appjazz\appjazzmobile> flutter doctor -v[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [versÃ£o 10.0.22000.318], locale pt-BR)
    • Flutter version 2.6.0-11.0.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (8 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\isaque\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.1)
    • VS Code at C:\Users\isaque\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.22000.318]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!
```

**Comment by stuartmorgan** [comment] 2021-11-12 01:07
Duplicate of https://github.com/flutter/flutter/issues/93389

Issues with third-party plugins (like `cloud_firestore`) need to be reported to their developers, not to the Flutter project.

**Closed by stuartmorgan** 2021-11-12 01:07 UTC
