### ISSUE TITLE
iOS: VoiceControl: Scroll down & scroll up commands are not working

### ISSUE THREAD

**Issue by lavinov-mercury** [flutter/flutter#98500] opened 2022-02-15 14:06 UTC
## Steps to Reproduce

1. Clone [repository](https://github.com/lavinov-mercury/scroll_a11y_issue) or copy-paste example below
2. Enable VoiceControl (Settings -> Accessibility -> Voice Control) 
3. Run app
4. Say `Scroll down` or `Scroll Up`
5. Observe app's behavior

**Expected results:** 
ListView scrolls when command recognized 

**Actual results:** 
Bubble with recognized command appears, however, app doesn't react

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemBuilder: (context, index) => ListTile(title: Text('Tile $index')),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Sorry, `flutter run --verbose` prints so much info, my terminal just trims most of it :(
```

```
Analyzing scroll_a11y_issue...                                          
No issues found! (ran in 1.9s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

I know this issue is a duplicate, however original [issue](https://github.com/flutter/flutter/issues/80711) was closed, & i have no idea how to re-open it. Also, as i understood, fix was merged earlier, but then for some reason it was reverted

**Comment by darshankawar** [comment] 2022-02-16 07:55
Verified this behavior using latest stable and master and the VoiceControl doesn't seem to work properly. I did see it scroll down one time when I said `scroll down` and it did scroll as shown in below screenshot you'll see the list was scrolled, but it isn't consistent. Also `scroll up` doesn't scroll.

<img width="346" alt="Screenshot 2022-02-16 at 1 23 58 PM" src="https://user-images.githubusercontent.com/67046386/154220186-b4e0e39e-7efa-48b0-acce-f7d35abd2c25.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.581, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.581 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2097fe64f0 (37 minutes ago), 2022-02-16 06:20:22 +0200
    • Engine revision 4ea2394b8d
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2022-02-16 07:56
May be related to: https://github.com/flutter/flutter/issues/75887

/cc @chunhtai

**Comment by goderbauer** [comment] 2022-02-16 22:59
Closing this as duplicate of https://github.com/flutter/flutter/issues/80711.

**Closed by goderbauer** 2022-02-16 22:59 UTC
Labels: platform-ios, framework, engine, a: accessibility, has reproducible steps, found in release: 2.10, found in release: 2.11
