### ISSUE TITLE
The linux system app testing in flutter is missing dependencies which flutter doctor couldn't figure out.

### ISSUE THREAD

**Issue by galanteria01** [flutter/flutter#66414] opened 2020-09-23 03:57 UTC
![Screenshot from 2020-09-23 09-24-05](https://user-images.githubusercontent.com/58800160/93965076-cde0f480-fd7e-11ea-86a9-529e028a6df1.png)
This are the error faced by me

By running flutter doctor -v
![Screenshot from 2020-09-23 09-26-51](https://user-images.githubusercontent.com/58800160/93965134-f36dfe00-fd7e-11ea-9780-c55ddbc45b69.png)

Need help with adding commands to install all dependencies regarding linux desktop app building

**Comment by TahaTesser** [comment] 2020-09-23 08:46
Hi @galanteria01 
This might be caused by your older dependencies, please update them and try again 
```
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
```

If the problem with persists, Can you please provide your `flutter doctor -v` **with update** and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by stuartmorgan** [comment] 2020-09-23 13:52
> This might be caused by your older dependencies, please update them and try again

@galanteria01 It looks like you installed the Flutter snap, is that correct? (If so, this isn't possible.)

Have you altered `linux/flutter/CMakeLists.txt` in any way? If not I'm not sure how this would be happening; line 24 in an unmodified file is [gtk+-3.0](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/linux.tmpl/flutter/CMakeLists.txt#L24), and `flutter doctor` [does check for that](https://github.com/flutter/flutter/blob/70bd819c52a992eec3bc326c9457b263d625a0ef/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L56).

**Comment by TahaTesser** [comment] 2020-09-23 15:37
That's interesting, I didn't notice Snap installation, I was thinking distro might be pulling older dependencies like git or node

**Comment by stuartmorgan** [comment] 2020-09-23 15:43
> I was thinking distro might be pulling older dependencies

Even if that were the case, `flutter doctor` does version checks for the Linux tools and libraries. So if `doctor` is showing everything as fine, but the version of one or more of the things it's checking doesn't actually work for Flutter, that would still be a bug.

**Comment by galanteria01** [comment] 2020-09-24 02:37
> > This might be caused by your older dependencies, please update them and try again
> 
> @galanteria01 It looks like you installed the Flutter snap, is that correct? (If so, this isn't possible.)
> 
> Have you altered `linux/flutter/CMakeLists.txt` in any way? If not I'm not sure how this would be happening; line 24 in an unmodified file is [gtk+-3.0](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/linux.tmpl/flutter/CMakeLists.txt#L24), and `flutter doctor` [does check for that](https://github.com/flutter/flutter/blob/70bd819c52a992eec3bc326c9457b263d625a0ef/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L56).


Yes did a snap installation,But didn't to any change in any file. Testing a android app work fine but just linux app have this issue.

**Comment by TahaTesser** [comment] 2020-09-24 06:12
Hi @galanteria01 
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` your complete `flutter run -d --verbose`  logs
Thank you

**Comment by stuartmorgan** [comment] 2020-09-24 13:01
Oh wait, your screenshot shows the error coming from `/usr/share/cmake[...]`. That's outside of the snap, so would rely on what's installed at the OS level rather than inside the snap.

@MarcusTomlinson What's the next step in debugging how this is happening? I'm don't know the full details of how the IDE/snap integration works.

**Comment by MarcusTomlinson** [comment] 2020-09-24 13:18
Currently only the VS Code extension has proper supports for the flutter snap ([I'm still working on expanding that support](https://github.com/flutter/flutter-intellij/issues/4746#issuecomment-671469900)).

@galanteria01, you may need to remove the snap and use flutter [the non-snap way](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually) for the time being.

I think the `flutter doctor` command from the terminal is (rightly) picking up the dependancies you need from the snap but the IDE is (wrongly) looking for them on your system. Thus, those dependancies will need to be installed via apt (once you've replaced the flutter snap with non-snap flutter, run `flutter doctor` again to see which dependancies those are).

**Comment by stuartmorgan** [comment] 2020-09-24 15:24
Ah, sorry; I thought there was support for both IDEs, and the work was to make it simpler and more generalizable.

**Comment by galanteria01** [comment] 2020-09-26 09:37
Things are working as usual.. Dependencies have updated as i added some dev repositories too!
Thanks to you sir!

**Comment by TahaTesser** [comment] 2020-09-28 07:28
Hi @galanteria01 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-28 07:28 UTC
Labels: in triage

**Comment by stuartmorgan** [comment] 2020-09-28 15:21
> Currently only the VS Code extension has proper support for the flutter snap

@csells Should we really be recommending the snap as the primary installation mechanism at this point if it doesn't work with one of our supported editors?

**Comment by csells** [comment] 2020-09-28 17:39
I understand that @marcustomlinson has a fix in the works. perhaps he can provide status on that fix.

**Comment by MarcusTomlinson** [comment] 2020-09-28 17:43
Will PR tomorrow.
