### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:62359/3XFQsmwBQTY=/ws

### ISSUE THREAD

**Issue by bobhob314** [flutter/flutter#36115] opened 2019-07-13 03:03 UTC
# Steps to Reproduce
This error is happening for me on Windows 10, with my emulation with Android Studio when I run my project. The app builds and starts running, but then loses the connection between the console and the phone, so I can't do hot reloads.

# Logs
```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.7s
Resolving dependencies...                                           2.2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.8s
Built build\app\outputs\apk\debug\app-debug.apk.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:62359/3XFQsmwBQTY=/ws
```
# Flutter Doctor
'''
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.14393], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!
'''

I've been through several similar threads but haven't found a solution. Would appreciate any support.

**Comment by Lucas0Braz** [comment] 2019-07-13 21:59
Do you use the default emulator that comes with android studio?
If yes, i had the same issue and installed a new emulator that solved the problem

**Comment by bobhob314** [comment] 2019-07-13 23:17
I installed the newest OS on the Nexus 5 I think, is that what you mean? @Lucas0Braz

**Comment by Lucas0Braz** [comment] 2019-07-13 23:44
No, try to create a new emulator in android virtual devices

**Comment by bobhob314** [comment] 2019-07-15 01:54
@Lucas0Braz that's what i did before. I'm doing it again now as per your advice, but I had to create my own emulator Nexus 5x previously as well.

**Comment by DanTup** [comment] 2019-07-23 07:16
Are you using a Q/API29 emulator? If so, and downgrading to P/28 resolves the issue, then this is likely a dupe of #33050.

**Closed** 2019-08-15 10:14 UTC
Labels: waiting for customer response
