### ISSUE TITLE
Using autofocus in TextField throws an assertion

### ISSUE THREAD

**Issue by ogawabrfc** [flutter/flutter#49978] opened 2020-02-02 21:01 UTC
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,619ms.
I/flutter (13967): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (13967): The following assertion was thrown while dispatching notifications for FocusNode:
I/flutter (13967): RenderBox was not laid out: RenderEditable#20ad4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (13967): 'package:flutter/src/rendering/box.dart':
I/flutter (13967): Failed assertion: line 1687 pos 12: 'hasSize'
I/flutter (13967): 
I/flutter (13967): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13967): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13967): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13967):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13967): 
I/flutter (13967): When the exception was thrown, this was the stack:
I/flutter (13967): #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
I/flutter (13967): #3      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:1729:40)
I/flutter (13967): #4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1415:7)
I/flutter (13967): #5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1441:7)
I/flutter (13967): #6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1707:5)
I/flutter (13967): #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter (13967): #8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:808:5)
I/flutter (13967): #9      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1401:12)
I/flutter (13967): (elided 12 frames from class _AssertionError and package dart:async)
I/flutter (13967): 
I/flutter (13967): The FocusNode sending notification was:
I/flutter (13967):   FocusNode#b8017
```

**Comment by TahaTesser** [comment] 2020-02-02 21:14
@ogawabrfc This might help https://stackoverflow.com/questions/59382235/flutter-throws-an-error-when-i-use-text-field-with-auto-focus

**Comment by dnfield** [comment] 2020-02-02 22:52
@gspencergoog - is there a better error we could throw in this case?

**Comment by gspencergoog** [comment] 2020-02-03 15:55
I'd be more curious as to why it's happening.  It's trying to calculate the box for a renderbox that hasn't been laid out.  We could protect against that by making sure that `hasSize` is true before doing the calculation, but I'm not sure what the side effects of that might be (it might never get calculated, or maybe it would just defer until it has been laid out).

**Comment by gspencergoog** [comment] 2020-02-03 16:17
Actually, I think we could safely check `hasSize`, and then just let it reschedule the check (it is going to reschedule it anyhow).

**Comment by gspencergoog** [comment] 2020-02-03 17:15
Actually, I believe that this will be fixed by https://github.com/flutter/flutter/pull/48922.

**Comment by gspencergoog** [comment] 2020-02-03 17:16
And this bug is a duplicate of https://github.com/flutter/flutter/issues/47235

**Closed by gspencergoog** 2020-02-03 17:16 UTC
Labels: a: error message, f: focus, framework

**Comment by cedvdb** [comment] 2021-05-25 18:11
I'm having this bug where :

 - navigator 2.0 is used to display pages on top of each other
 - there is a text field with autofocus true and a focusNode
 
 the error happens when adding a page to the stack of page on top of the current one
