### ISSUE TITLE
Please tell us when TextInputFormatter will be fixed?

### ISSUE THREAD

**Issue by woozbooz** [flutter/flutter#39976] opened 2019-09-06 13:47 UTC

**Comment by HansMuller** [comment] 2019-09-06 14:58
This regression was introduced in an August 19th engine roll: #38855.
The engine PR that's causing the problem is flutter/engine#9498.

It was reported in #39047, #39182, #39485, #39487, #39223, #39738

This issue was fixed late last week, see #39523, and flutter/engine#11720.

Closing this one as a duplicate.

**Closed** 2019-09-06 14:59 UTC
Labels: a: text input, f: material design, framework
