### ISSUE TITLE
[Sentry] Update pub.dev package to current repo version

### ISSUE THREAD

**Issue by jamie1192** [flutter/flutter#61420] opened 2020-07-14 06:09 UTC
The pub.dev page for the package lists the current version of the package being 3.0.1, while the repo is currently up to version 5, and states that "Versions below 4.0.0 are deprecated.".

**Comment by TahaTesser** [comment] 2020-07-14 09:43
duplicate of https://github.com/flutter/flutter/issues/58575

**Closed by TahaTesser** 2020-07-14 09:43 UTC
