### ISSUE TITLE
Issue when syncs app on phone

### ISSUE THREAD

**Issue by cronos88** [flutter/flutter#18363] opened 2018-06-11 17:25 UTC
I have an issue with the synchronization of the app on my cell phone. I make a new app with some text and then I run it on my cell phone and it looks good. Then I change for example the background color and save the file. Automatically makes the hot reloading and the new background color appears on my cell phone. When I stop everything in Visual Studio Code and I disconnect the cell phone, when I see the app again, the last change I made (background color change) does not appear. And so it always happens, when I make several code changes, when I stop the debug and disconnect the cell phone, it does not reflect the last change that was made, when reviewing the app again being disconnected from the computer. It's like it does not save the last synchronization it did. I already tried it in IntelliJ Idea and the same thing happens. I have Flutter 0.4.4 beta 3, Linux Elementary OS, the latest version of the flutter plugin in Visual Studio Code and IntelliJ.

**Comment by zoechi** [comment] 2018-06-11 19:22
This is working as intended. Hot-reload changes are just loaded into the Dart VM but not added to the installed app.
@Hixie is this planned to be changed?

**Comment by Hixie** [comment] 2018-06-11 19:50
It's definitely an issue we see people run into a lot...

cc @a-siva @aam @rmacnak-google @cbracken, what do you think of writing a transaction log to the device when we do a hot reload, and on a debug build startup, if there's such a log, applying those changes? That would reduce this confusion people run into all the time.

**Comment by aam** [comment] 2018-06-18 13:53
Sounds doable, but somehow it feels brittle. Debug startup time will regress if you have sizeable journal of incremental files. We currently only keep last incremental kernel file on the device, so keeping all of them since beginning of debugging session will consume more storage space on the device.

**Comment by goderbauer** [comment] 2018-12-29 02:20
Dupe of https://github.com/flutter/flutter/issues/12174.

**Closed by goderbauer** 2018-12-29 02:20 UTC
Labels: framework, t: hot reload, tool
