### ISSUE TITLE
Gridview inside pageview giving jank on scrolling pageview

### ISSUE THREAD

**Issue by chaudharydeepanshu** [flutter/flutter#108998] opened 2022-08-04 21:59 UTC
## Details

1.  I'm working on a specific calendar package for my app needs and for that I'm using grid view inside pageview for the scrolling navigation behavior but the pageview scrolling behavior is causing a lot of janks as it has to rebuild the 42 elements of gridview every time pageview is scrolled. 

So am I doing anything wrong here? Is grid view shouldn't be used for such types of applications? Also, how do other calendar packages or date pickers attain such a smooth behavior even during the debug mode.

2.  The short example gist -> https://gist.github.com/chaudharydeepanshu/c1e3fe0386cb464514f62b73305962ee **(Note this is just an example)**

3.  Device recording:-

https://user-images.githubusercontent.com/85361211/182958616-4aa98956-bad0-441f-ba37-e83fcf1c210b.mp4

4.  Dart Timeline - https://drive.google.com/file/d/1r1kbbBUoey3BocZ82jirN21WTBgYX9ip/view?usp=sharing

5. Dart DevTools- https://drive.google.com/file/d/1cMQgrCayrLkkjGAMK1zIWuvOa6iwc1Eu/view?usp=sharing

https://user-images.githubusercontent.com/85361211/182958597-111f448d-bf79-4787-b257-cd819e48568c.mp4

**Target Platform: Android**
**Target OS version/browser: 12**
**Devices: Redmi Note 10  Pro**

## Logs

<details>
<summary>Logs</summary>

```
Analyzing flutter_jank...
No issues found! (ran in 2.8s)
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.2092, on Microsoft Windows [Version 10.0.22622.450], locale en-US)
    • Flutter version 3.1.0-0.0.pre.2092 on channel master at C:\dev\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0377468d59 (2 hours ago), 2022-08-04 15:30:10 -0400
    • Engine revision 9ec11a0550
    • Dart version 2.19.0 (build 2.19.0-64.0.dev)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\deepa\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\deepa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Redmi Note 10 Pro (mobile) • d0646b2f • android-arm64  • Android 12 (API 32)
    • Windows (desktop)          • windows  • windows-x64    • Microsoft Windows [Version 10.0.22622.450]
    • Chrome (web)               • chrome   • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)                 • edge     • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you.

**Comment by BrianCraig** [comment] 2022-08-05 01:23
Hi! 
I've just made a revision on your gist, i see two main performance problems.
1. check the diff on https://gist.github.com/BrianCraig/23b68df986ef6d1b84bdf46aeed9bbae/revisions
When you use any Builder (in this case `PageView`) the instantiated Widgets are built on the fly as required, so for example, if you have 100 pages, and it is on the first page, the second one isn't created, so when you slide to the right, flutter creates the second page. It is easier if you let the controller mantain its current page, and render based on the index.
Also i gave the controller a long number of pages, and made it start in the middle.

2. `getDatesForACalendarMonthAsUTC` is computed for each day on each month and seems quite intensive, try computing it once per month. (Check itemBuilder of the GridView).

hope it helps you, Brian

**Comment by chaudharydeepanshu** [comment] 2022-08-05 11:47
@BrianCraig Thanks for looking into this but I know that it easy with with your approach but actually the problem is that I don't want to provide fixed length of months to the page view builder and I only want to add items when user swipes left of right. I want the same experience of date pickers.

Also, thanks for noticing getDatesForACalendarMontgAsUTC. I forgot to put it above builder when creating example but even with that change the jank is still there.

**Comment by exaby73** [comment] 2022-08-05 13:30
In your code, the `PageView` builds the entire widget when scrolling. The `GridView` is built completely on the slightest scroll. This is working as expected. I suggest that you try Stackoverflow or other communities you can find on https://flutter.dev/community. Since this is not a bug or a feature request, I am closing this issue. If you disagree, please comment and we can reopen it. Thank you

**Closed by exaby73** 2022-08-05 13:30 UTC
Labels: in triage

**Comment by BrianCraig** [comment] 2022-08-05 15:10
@chaudharydeepanshu If you want to provide a fixed number of months just define it in the size, in the example i provided i set it to `10000`, just a random number, you can use `12` if you want, and you will have 12 months. If you want an infinite calendar just use a size near to infinite, just as i did (i dont think anybody will scroll 5000 months)

**Comment by chaudharydeepanshu** [comment] 2022-08-06 07:04
> @chaudharydeepanshu If you want to provide a fixed number of months just define it in the size, in the example i provided i set it to `10000`, just a random number, you can use `12` if you want, and you will have 12 months. If you want an infinite calendar just use a size near to infinite, just as i did (i dont think anybody will scroll 5000 months)

After tinkering a while I actually think you are right. Also I don't think I have any other options as I have tried all methods and only custom scroll view will work but it has its own disadvantages like setting offset on orientation change. So the best bet here is pageview with big item count.

**Comment by chaudharydeepanshu** [comment] 2022-08-06 07:08
Also if anyone arrives on this thread in future looking for performance then I suggest that they is use pageview.custom with AutomatickeepAliveClientMixin as that will prevent pageview from building again and again on scroll.
