### ISSUE TITLE
Add a model presentation style option and allow UIModalPresentationStyle.pageSheet

### ISSUE THREAD

**Issue by erf** [flutter/flutter#80450] opened 2021-04-14 19:23 UTC
## Use case

I noticed that in iOS 13, model views are presented partially over the current window by default and does not cover the whole screen. `UIModalPresentationStyle.pageSheet` is chosen by the system for iOS. I like this presentation style alot.

## Proposal

I would like to see a similar modal presentation style option on Flutter. Either on `CupertinoPageRoute`, or even better to `MaterialPageRoute` (as i already use it). Or perhaps the system default could be used. That is on iOS, a presentation style similar to `UIModalPresentationStyle.automatic` would be used.

**Comment by erf** [comment] 2021-04-21 15:47
Using the iOS `pageSheet` modal presenetation style, the user is able to swipe the view down in order to close the it. I think this behaviour would also be great.

**Comment by MitchellGoodwin** [comment] 2024-10-16 22:52
Closing as a dupe of #42560

**Closed by MitchellGoodwin** 2024-10-16 22:52 UTC
Labels: c: new feature, platform-ios, framework, f: material design, f: cupertino, c: proposal, team-design, triaged-design
