### ISSUE TITLE
while using this package in my flutter application, m getting this error

### ISSUE THREAD

**Issue by swarankargaurav1** [flutter/flutter#60498] opened 2020-06-29 07:46 UTC
Note: C:\flutter_sdk_stable\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.11\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by darshankawar** [comment] 2020-06-29 11:35
Hi @swarankargaurav1,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-17 15:30
Duplicate of https://github.com/flutter/flutter/issues/60986

**Closed by VladyslavBondarenko** 2020-07-17 15:30 UTC
Labels: in triage, waiting for customer response
