### ISSUE TITLE
setting null text to TextEditingController doesn't behave as expected

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#55460] opened 2020-04-23 14:12 UTC
Create a TextEditingController, use it with a TextField, write some text and then try to delete this text by setting text to null:

    textEditingController.text = null;

Setting text to controller is implemented as:

    set text(String newText) {
      value = value.copyWith(
        text: newText,
        selection: const TextSelection.collapsed(offset: -1),
        composing: TextRange.empty,
      );
    }

But the copyWith method handles null in it's own way:

     TextEditingValue copyWith({
       String text,
       TextSelection selection,
       TextRange composing,
     }) {
       return TextEditingValue(
         text: text ?? this.text, // !!!!!!!
         selection: selection ?? this.selection,
         composing: composing ?? this.composing,
       );
     }

All steps are reasonable, but the result is totally unexpected. Suggestion:

    set text(String newText) {

      if (newText == null) {
         value = TextEditingValue.empty();
         return;
      }

      value = value.copyWith(
        text: newText,
        selection: const TextSelection.collapsed(offset: -1),
        composing: TextRange.empty,
      );
    }

Or something in that sense.

Le docteur obligatoire:

```
tomucha@tomucha-mx:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
... etc.
```

**Comment by TahaTesser** [comment] 2020-04-23 14:46
duplicate of. [#34847](https://github.com/flutter/flutter/issues/34847)

**Closed by TahaTesser** 2020-04-23 14:46 UTC
