### ISSUE TITLE
Flutter generates XCode projects using the Legacy Build system (XCode 10)

### ISSUE THREAD

**Issue by seamusmc** [flutter/flutter#26097] opened 2019-01-04 23:52 UTC
## Steps to Reproduce

1. From VSCode use the Flutter: New Project command.
2. Enter myapp for the project name, let Flutter build the project files
3. Use XCode to open the project
4. In the toolbar output there is a yellow hammer indicating the use of the legacy build system.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/959232/50717019-7b572600-1039-11e9-98e8-6f59c12585a4.png">

Please provide a mechanism so that the generated XCode projects to use the new build system, if we are using XCode 10. Its simply better in every way. 

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10

**Comment by madfingo** [comment] 2019-03-19 23:51
+1 Are there any expectations for this?

I'm hoping that having flutter use the new build system would severely reduce the build time on CIs such as Travis.

**Comment by FlashJonas** [comment] 2019-05-09 09:18
+1 on this. the legacy build is not fast, and how long will it be supported? will it give rise to other issues going forward?

**Comment by jmagman** [comment] 2019-05-31 21:49
The legacy build system was explicitly adopted with https://github.com/flutter/flutter/pull/21901/commits/231784ecf6a38b47ec1994609da1bbbb3fe5e99adue to conflicting outputs between build phases related to CocoaPods. I will be switching back to the build system with https://github.com/flutter/flutter/issues/20685.

**Comment by jmagman** [comment] 2019-05-31 21:55
Closing for now. You can track progress in #20685.

**Closed by jmagman** 2019-05-31 21:55 UTC
Labels: severe: new feature, t: xcode, tool

**Comment by fotiDim** [comment] 2020-11-05 18:25
I created a Flutter plugin (Flutter 1.22.3) and it was set by default to be using the Legacy Build system. I wanted to include an `xcframework` and this is not supported with the legacy build system. I had to manually switch to the new build system for the .xcodeproj

**Comment by jmagman** [comment] 2020-11-05 19:18
>  it was set by default to be using the Legacy Build system

@fotiDim
1. You mean in the plugin example project?
2. How did you fix it (what's the diff, which file actually changed?).
3. What was the exact error message?  Was it the legacy build system or the legacy build location?

**Comment by fotiDim** [comment] 2020-11-05 19:29
@jmagman 
1. yes
2. I fixed it by switching to the new build System on .xcodeproj. Then I switched to the beta channel and the problem came back even with the new build System. I am still trying to narrow it down.
3. Error is: <unknown>:0: error: unable to load standard library for target
    'arm64-apple-ios9.0-simulator'

**Comment by jmagman** [comment] 2020-11-05 20:05
On 1.22.3:
```
$ flutter create --platforms=ios -t plugin test_plugin
Creating project test_plugin...
...
Host platform code is in the ios directories under test_plugin.
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.
$ open test_plugin/example/ios/Runner.xcworkspace
```
File > Workspace Settings...

<img width="535" alt="Screen Shot 2020-11-05 at 12 02 32 PM" src="https://user-images.githubusercontent.com/682784/98290637-cb1d1600-1f5e-11eb-8e33-8a697a46a7f2.png">

Build system is New, not legacy.
@fotiDim What reproduction steps am I missing here?

**Comment by fotiDim** [comment] 2020-11-05 20:10
@jmagman I believe you are opening the workspace instead of the project.

```
flutter --version
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (7 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

```
flutter create --org com.mycompany --template=plugin --platforms=android,ios myplugin
```

```
open myplugin/example/ios/Runner.xcodeproj 
```

Go to File -> Project Settings -> Advanced

<img width="1392" alt="Screenshot 2020-11-05 at 21 08 28" src="https://user-images.githubusercontent.com/2326415/98291301-31c82100-1fab-11eb-846a-2e91ac3001bd.png">

**Comment by jmagman** [comment] 2020-11-05 21:26
@fotiDim That's the build location, not the build system.  You're hitting https://github.com/flutter/flutter/issues/57083.
