### ISSUE TITLE
box.dart: Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

### ISSUE THREAD

**Issue by Storch72** [flutter/flutter#74260] opened 2021-01-19 20:29 UTC
Hello, we are receiving the following exception trying to display a CupertinoDialogAction and as the message alludes to, we need more information to help us determine what we are doing wrong.   The code in homePage.dart is pretty simple:

```
line 91: 
   showDialog(context: context, builder: (_) {
        return CupertinoAlertDialog(
            title: Text(message.title),
            content: Text(message.body),
            actions: _actionButtons(context, message)
        );
      });
```
```
line 111:
actionButtonList.add( CupertinoDialogAction(
          child: Text( message.buttonName ),
          onPressed: () => _launchURL( message.buttonUrl )
      ) );
```
Please see included Exception2.txt for details. 
[Exception2.txt](https://github.com/flutter/flutter/files/5838463/Exception2.txt)

**---Start of Message stating to file bug report---**
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

```
The relevant error-causing widget was: 
  CupertinoDialogAction file:///D:/Projects/fluttermobile/lib/src/view/homePage.dart:111:29
When the exception was thrown, this was the stack: 
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:320:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2429:58)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#5      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)

```

**Comment by darshankawar** [comment] 2021-01-20 07:56
@Storch72 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
I tried a sample code based on snippet you provided, on iPhone 12 max simulator using latest master version, which opened `cupertinoAlertDialog` and then the url properly without any issues. Obviously, I don't know the exact use case you have.

<details>
<summary>code sample</summary>

```
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: ElevatedButton(
        child: Text('Tap'),
        onPressed: () {
          _showCupertinoDialog(context);
        },
      )),
    );
  }

  void _showCupertinoDialog(BuildContext context) {
    showDialog(
        context: context,
        builder: (_) {
          return CupertinoAlertDialog(
            title: Text('Title'),
            content: Text('Body'),
            actions: <Widget>[
              CupertinoDialogAction(
                child: Text('Close me!'),
                onPressed: () {
                  _launchURL();
                },
              )
            ],
          );
        });
  }

  _launchURL() async {
    const url = 'https://flutter.dev';
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
}

```

</details>

Also, from the log you shared, 
```

I/flutter (29064): on message {notification: {title: Refrigerator Off, body: Home - Refrigerator met the threshold for 5 consecutive seconds, most recently using 0.000 kWatts during the 13:14:04 second}, data: {body: Home - Refrigerator met the threshold for 5 consecutive seconds, most recently using 0.000 kWatts during the 13:14:04 second, title: Refrigerator Off, click_action: FLUTTER_NOTIFICATION_CLICK}}

======== Exception caught by rendering library =====================================================
```

I see that you tap on Notification. Does the error occur after you tap on it ?

**Comment by Storch72** [comment] 2021-01-21 14:58
Hello.  Here is flutter doctor output and attached is the entire file.  It's obviously not feasible to include all the imports but hopefully this is enough for you. Also to add to the report.  I was receiving the assert running on Pixel 3 with the Android 9.0 (Pie) on Windows.  
-Jon
[homePage.dart.txt](https://github.com/flutter/flutter/files/5850102/homePage.dart.txt)

λ flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.5 at C:\frameworks\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\frameworks\andriod\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\frameworks\andriod\sdk
    • ANDROID_SDK_ROOT = D:\frameworks\andriod\emmulators
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.48.2)
    • VS Code at C:\Users\jstorchevoy\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

**Comment by darshankawar** [comment] 2021-01-22 06:23
@Storch72 
From your file I assume it is your production code. We would need a[ minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste without any 3rd party plugins and run in IDE to see the issue you are getting.

**Comment by tkeithblack** [comment] 2021-01-27 18:49
I am seeing the same thing when calling FittedBox on an Image() inside an AppBar. The odd thing is that this only occurs the first time this page is loaded. If I exit and re-display the page it works find until I restart the app. Every time the app is restarted and I enter this page I again get this error.

`return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        title: GestureDetector(
          child: Padding(
            padding: const EdgeInsets.only(top: 8.0, right: 10, bottom: 8),
            child: FittedBox(child: Image.asset('assets/my_logo.png')),
          ),
          onLongPress: () => _doSomething(), 
        ),
      ),
      body:
`

**Error Message:**
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
FittedBox
lib/pages/buy_number_page.dart:60
When the exception was thrown, this was the stack
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio
package:flutter/…/rendering/box.dart:320
#3      RenderFittedBox.performLayout
package:flutter/…/rendering/proxy_box.dart:2433
#4      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
#5      RenderPadding.performLayout
package:flutter/…/rendering/shifted_box.dart:207
#6      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
...
The following RenderObject was being processed when the exception was fired: RenderFittedBox#76ad3 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderFittedBox#76ad3 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=222.0, 0.0<=h<=Infinity)
    size: MISSING
    fit: contain
    alignment: center
    textDirection: ltr
    child: RenderSemanticsAnnotations#4a496 relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(0.0, 0.0)
        child: RenderImage#40dce relayoutBoundary=up19 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(0.0, 0.0)
            image: null
            alignment: center
            invertColors: false
            filterQuality: low

**Comment by tkeithblack** [comment] 2021-01-27 18:50
Here's my flutter doctor:

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/keithblack/GitHub/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/keithblack/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM G935T (mobile)  • 548f2e88                             • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 5s (mobile) • D97EF8E0-2B11-4C1B-AE4E-2EE2BC4AEA42 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone X (mobile)  • C8B5F576-AC4F-4F5E-BD66-148280F0E844 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by darshankawar** [comment] 2021-01-28 06:19
@Storch72 
Thanks for the code sample. I tried it and was able to see the assertion failing. But I think I know why it must be throwing that error.
Since you wrapped `image` with `FittedBox`,  the `FittedBox` widget scales and positions it's child based on the `fit` value. By default it uses `fit: BoxFit.contain` which uses the fit area as large and as much as possible and not knowing where to stop before rendering it's child (an image in this case).

We can resolve it by passing `height` and `width` to the image which instructs FittedBox's child to use only provided dimensions.

```
appBar: AppBar(
        title: GestureDetector(
          child: Padding(
            padding: const EdgeInsets.only(top: 8, right: 10, bottom: 8),
            child: FittedBox(
              child: Image.asset('assets/Flutter-Cover.png', width: 400, height: 100),
            ),
          ),
         onLongPress: () {
           Navigator.push(
             context,
             MaterialPageRoute(builder: (context) => SecondRoute()),
           );
         },
        )
      ),
```

Above code sample renders the image without throwing the assertion failure.

I am going ahead and closing this. If you disagree or think it's still not working, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-01-28 06:19 UTC
Labels: in triage, waiting for customer response
