### ISSUE TITLE
Using opaque background color on CupertinoTabBar breaks containing TextFields

### ISSUE THREAD

**Issue by SaschaZ** [flutter/flutter#30396] opened 2019-04-02 18:55 UTC
After the last Flutter update to `v1.2.1` the `CupertinoTextField` has a focus issue.

steps to reproduce:
- creating `CupertinoTabBar` with an opaque `backgroundColor`
- placing a `CupertinoTextField` inside the `CupertinoTabBar`
- tapping inside the `CupertinoTextField`

expected result:
- keyboard shows up
- `CupertinoTextField` gets focused

actual result:
- keyboard shows up
- `CupertinoTextField` gets focused
- keyboard disappears
- `CupertinoTextField` looses focus

workarounds:
- setting the `backgroundColor` of `CupertinoTabBar` to a transparent color (at least 0xFE....)
OR
- setting `resizeToAvoidBottomInset` to `false` (`CupertinoTabScaffold`)

Demo App:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(DemoApp());

class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BottomBar Bug Demo',
      home: CupertinoTabScaffold(
          tabBar: CupertinoTabBar(
            backgroundColor: Color(0xFF000000),
            items: <BottomNavigationBarItem>[
              BottomNavigationBarItem(title: Text("1"), icon: Icon(Icons.map)),
              BottomNavigationBarItem(
                  title: Text("2"), icon: Icon(Icons.title)),
              BottomNavigationBarItem(
                  title: Text("3"), icon: Icon(Icons.details)),
              BottomNavigationBarItem(
                  title: Text("4"), icon: Icon(Icons.ac_unit)),
            ],
          ),
          tabBuilder: (context, index) => CupertinoTabView(
                builder: (BuildContext context) {
                  return Center(
                      child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 50.0),
                    child: CupertinoTextField(
                      decoration: BoxDecoration(
                          border: Border.all(),
                          borderRadius: BorderRadius.circular(5.0)),
                    ),
                  ));
                },
              )),
    );
  }
}
```

Flutter Doctor ouput:
```
flutter doctor --verbose
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale de_DE.utf8)
    • Flutter version 1.2.1 at /home/sz/Downloads/flutter
    • Framework revision 8661d8aecd (vor 7 Wochen), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/sz/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /opt/intellij-idea-ce
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] Connected device (1 available)
    • Pixel • FA69V0303889 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by LongCatIsLooong** [comment] 2019-06-23 23:08
This seems to have been fixed on `master`, I'm not able to reproduce it with the sample code. Could you verify on `master` @SaschaZ?

**Closed** 2019-07-16 14:32 UTC
Labels: f: cupertino, severe: regression, waiting for customer response
