### ISSUE TITLE
Render glitch when Paint uses ImageFilter on all platforms except web 

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#57180] opened 2020-05-14 02:26 UTC
I'm seeing a rendering bug on Android that does not appear on iOS. The issue occurs when painting with a blur in a `CustomPainter`.

The offending `Paint` configuration is:

```
blurPaint = Paint()
          ..imageFilter = ImageFilter.blur(sigmaX: 10, sigmaY: 10)
          ..color = Colors.red;
```

On iOS, we see the expected result:

![paint-bug-repro_ios](https://user-images.githubusercontent.com/7259036/81885590-81271a80-954f-11ea-99a1-74f609f3b4f4.png)

However, on Android, whether using an emulator or a physical device, we see this:

![paint-bug-repro_android](https://user-images.githubusercontent.com/7259036/81885611-8c7a4600-954f-11ea-81b6-b21b0b632d7d.png)

There appears to be some kind of quadrant artifact in the rendered result.

Flutter version:

Flutter 1.19.0-2.0.pre.15 • channel master • https://github.com/flutter/flutter.git
Framework • revision c969b8af7b (2 days ago) • 2020-05-11 15:28:10 -0700
Engine • revision ada8a0fd64
Tools • Dart 2.9.0 (build 2.9.0-8.0.dev a6d06b59ec)

Repro project:

https://github.com/matthew-carroll/flutter_bug_repro_57180

**Comment by matthew-carroll** [comment] 2020-05-14 02:28
CC @liyuqian

**Comment by matthew-carroll** [comment] 2020-05-15 04:01
FYI @timsneath @csells this bug may become highly visible in a video in the next month or two :)

**Comment by liyuqian** [comment] 2020-05-15 18:51
Also CC Skia experts @brianosman @briansalomon . Flutter should issue the exact same SkCanvas commands so something inside Skia or GPU driver should be responsible for the difference. Could this be a problem on Android because iOS either uses Metal or a very old version of OpenGL?

**Comment by bsalomon** [comment] 2020-05-15 19:46
I wonder if it has something to do with padding around the input to the image filter being different. I notice that here:
https://github.com/flutter/engine/blob/1c8ee9856bffbc637670d372ac4a88bd11368f46/lib/ui/painting/image_filter.cc#L56

clamp tiling is used. The Android image looks like what I'd expect if the input image to the blur was a red circle where the circle went right up to the edge or just beyond the edge of the image.

**Comment by matthew-carroll** [comment] 2020-05-15 20:26
Generally speaking, painting operations in a `CustomPainter` are not confined by the incoming `size`. So while the problem might be the edges of the owning `CustomPaint` widget, I would expect painting operations to work just fine, even if they exceed that size. For example, as it stands today, I could easily draw entire shapes or curves that sit completely outside the supposed bounds of the `CustomPaint` widget. If the blur is being confined by the widget bounds then I think that's functionally a bug as compared to other canvas behavior.

**Comment by matthew-carroll** [comment] 2020-05-15 20:45
@liyuqian I checked out 1.12:

```
Flutter 1.12.0 • channel unknown • unknown source
Framework • revision 9323a623bd (6 months ago) • 2019-11-08 21:35:17 -0500
Engine • revision 2f69e38160
Tools • Dart 2.7.0

```

The iOS version still looks fine in the simulator. I can't test a physical iPhone right now because apparently I have to upgrade my whole OSX to deploy to the current version of my iPhone.

My Android project is incompatible with versions of Flutter that early. This is probably due to the v2 embedding work. So I can't test back that far. But if you'd like to investigate earlier Android versions, I included a minimal reproduction project in my original post. You could copy/paste the widget code.

**Comment by jason-simmons** [comment] 2020-05-16 02:16
If I run the app on Android with `--enable-software-rendering` the results look similar to the iOS image shown above.

I can also produce a result similar to iOS by changing the engine to build the `SkBlurImageFilter` using `kClampToBlack_TileMode`.

The engine switched from the default `kClampToBlack` to `kClamp` a long time ago (https://github.com/flutter/engine/commit/e6c117d0fbfd2d9c873a018222af537d12b94f75).

@brianosman do you recall why that change was made?

**Comment by brianosman** [comment] 2020-05-16 13:09
It looks like that was to fix https://github.com/flutter/flutter/issues/13280, where some cuptertino blurring effects were behaving differently near the edges of the screen/layer than the middle (because the blur was pulling in the black, darkening the result).

**Comment by emmett-deen** [comment] 2020-11-20 18:13
This looks like a duplicate of [#56476](https://github.com/flutter/flutter/issues/56476)

**Comment by emmett-deen** [comment] 2020-11-20 18:25
Adding some images from my own project showing this issue with high sigma blur values (80 for x & y). Only the iOS simulator is showing the desired result.

Physical iOS device running iOS 14.2
![IMG_4208](https://user-images.githubusercontent.com/7634149/99835944-5982c180-2b33-11eb-9587-c4aaf93921ea.PNG)

Android Emulator Pixel_2_API_29
![Screenshot_1605896342](https://user-images.githubusercontent.com/7634149/99836099-96e74f00-2b33-11eb-9313-3eea7cfb2104.png)

iOS Simulator running iOS 14.2
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-20 at 13 19 41](https://user-images.githubusercontent.com/7634149/99836182-b5e5e100-2b33-11eb-869b-c4186c633490.png)

**Comment by TahaTesser** [comment] 2020-12-07 14:45
Hi 
I can reproduce on iOS as well as Android

| iOS | Android |
| --------------- | --------------- |
![Simulator Screen Shot - iPhone 12 - 2020-12-07 at 19 46 33](https://user-images.githubusercontent.com/48603081/101364603-c4b8eb80-38c8-11eb-80ab-616dd0235806.png) | ![Screenshot_2020-12-07-20-11-03-60_f0a5da16151fb602eeacb67ea37fa49e](https://user-images.githubusercontent.com/48603081/101364737-e74b0480-38c8-11eb-88cd-f8dd518eec58.jpg)


<details> 
<summary>code sample</summary> 

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: CustomPaint(
        painter: MyPainter(),
      )),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Paint blurPaint = Paint()
      ..imageFilter = ImageFilter.blur(sigmaX: 10, sigmaY: 10)
      ..color = Colors.red;

    canvas.drawCircle(Offset(10, 10), 100, blurPaint);
  }

  @override
  bool shouldRepaint(MyPainter oldDelegate) => false;

  @override
  bool shouldRebuildSemantics(MyPainter oldDelegate) => false;
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.92, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.92 at /Users/tahatesser/Code/flutter_master
    • Framework revision 90f08769a3 (2 hours ago), 2020-12-07 12:33:03 +0100
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • C303B5A5-D598-4CAC-8ACC-09BF07A191DC • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

• No issues found!```

</details>


Related https://github.com/flutter/flutter/issues/56476  https://github.com/flutter/flutter/issues/39623#issuecomment-656596365

**Comment by flar** [comment] 2020-12-07 21:25
There are a number of issues that affect ImageFilters. One proposal to add functionality to aid with some of the problems is expressed in https://github.com/flutter/flutter/issues/71871

It looks like this issue should be entirely handled by that new functionality, but the example code here will require the addition of a new parameter (a TileMode) when creating the blur.

**Comment by flar** [comment] 2020-12-10 22:39
Using the new `TileMode.decal` value in the `ImageFilter.blur()` constructor should fix this problem.

See https://github.com/flutter/engine/pull/22982
See https://github.com/flutter/flutter/issues/71871

**Closed by flar** 2020-12-10 22:39 UTC
Labels: P3, customer: product, engine, found in release: 1.25, has reproducible steps, severe: rendering

**Comment by TahaTesser** [comment] 2020-12-11 06:48
For web issue https://github.com/flutter/flutter/issues/58546
