### ISSUE TITLE
firebase_auth error 

### ISSUE THREAD

**Issue by inzy47** [flutter/flutter#31394] opened 2019-04-21 18:04 UTC
I'm creating a blog app, while creating new user I got following error. Please somebody help me with this, it's kinda urgent.

**I/flutter ( 1603): 'file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.4+5/lib/src/firebase_auth.dart': Failed assertion: line 103 pos 12: 'email != null': is not true.**

The above message displays in terminal when ever I wanted to create a new user in my flutter app.

flutter doctor -v (output)

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.32.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • SM A730F • 52006211bea2a4ab • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by ogarvey** [comment] 2019-04-23 10:02
It's going to be difficult to help without any code that shows how you're creating the user.

But from the error message, it looks the email address you're trying to create the user with isn't being sent for some reason.

**Comment by BondarenkoStas** [comment] 2019-10-17 13:59
@inzy47 was the issue resolved?

**Comment by iapicca** [comment] 2019-11-08 09:43
Hi @inzy47 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:43 UTC
Labels: waiting for customer response
