### ISSUE TITLE
Why not use FlutterEngineGroup on macos and windows?

### ISSUE THREAD

**Issue by seeuli** [flutter/flutter#118246] opened 2023-01-10 13:41 UTC
@gaaclarke @ColdPaleLight @cbracken @jmagman

**Comment by stuartmorgan** [comment] 2023-01-10 14:39
Closing as a duplicate of https://github.com/flutter/flutter/issues/95076

Please don't ping individual people when filing issues; our triage process will route issues.

**Closed by stuartmorgan** 2023-01-10 14:39 UTC
