### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by lxgogogo** [flutter/flutter#86145] opened 2021-07-09 03:37 UTC
## Command
```
flutter --no-color attach --machine --device-id=5ENDU19411003366 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:318:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.18363.1556], locale zh-CN)
    • Flutter version 2.0.6 at D:\FlutterStudy\flutter
    • Framework revision 1d9032c7e1 (2 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Xxugle\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\Android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (3 available)
    • PCT AL10 (mobile) • 5ENDU19411003366 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 91.0.864.48

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.dynamic_form
**iOS bundle identifier**: com.example.dynamicForm
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3

**Comment by darshankawar** [comment] 2021-07-09 09:53
@lxgogogo 
A similar issue was fixed: https://github.com/flutter/flutter/issues/74632
Can you try to upgrade to latest stable (2.2.3) or to latest master and check again to see if same error occurs or not ?
Also, I am going ahead and closing this as duplicate of https://github.com/flutter/flutter/issues/84898
If after upgrading to latest, you still see the same error, comment on above linked issue.

**Closed by darshankawar** 2021-07-09 09:53 UTC
Labels: in triage
