### ISSUE TITLE
TextField, using the scanner device, can't recognize the return key automatically added by the system, and the onChange method can't detect the newline. . . ,

### ISSUE THREAD

**Issue by jicg** [flutter/flutter#35531] opened 2019-07-03 15:04 UTC
TextField, using the scanner device  can not identify the system automatically added the Enter key, the onChange method also does not detect line breaks. . . Is there any good way to solve this problem?

Scanner device is android 5.0 system

**Comment by fgario** [comment] 2019-07-04 01:45
I have the exact some issue but on Android 6.0

**Comment by jicg** [comment] 2019-07-04 01:51
What method did you use to solve this problem?

**Comment by fgario** [comment] 2019-07-04 02:29
Could not solve it, i still have the issue. 
I commented to bump it.

**Comment by jicg** [comment] 2019-07-17 01:02
@justinmc  Is there any temporary solution to this problem?

**Comment by justinmc** [comment] 2019-07-17 15:22
Not that I can think of...  When does the system add a line break automatically?  I'll try to reproduce this.

**Comment by jicg** [comment] 2019-07-17 16:23
@justinmc ，Thank you for your reply。
I am using the flutter to implement the function of entering barcodes into the application using a barcode scanner device. 
The barcode scanner device can append a line break.
Flutter‘s TextFeild can get scanned barcodes, but can't handle line breaks.
On the android system, it can be processed by setOnEditorActionListener on the EditText. 
I look forward to your giving you a good way. 
Thank you.

**Comment by justinmc** [comment] 2019-08-02 20:32
I don't think I can reproduce this.  I can definitely help if you want to dig into this yourself though.

You might want to look at what TextEditingValue is coming from the engine when a problematic newline is entered:

https://github.com/flutter/flutter/blob/4e3698fb5dcbf8a88135403a9ac19e2b6b3f39ac/packages/flutter/lib/src/services/text_input.dart#L655-L661

If it looks correct at that point, you'll have to [compile the engine locally](https://github.com/flutter/flutter/wiki/Compiling-the-engine) and try to check what's coming from the device.

**Comment by kf6gpe** [comment] 2020-01-06 18:52
@jicg, were you able to answer @justinmc';s question? Is this still happening with the latest stable release?

**Comment by jicg** [comment] 2020-01-08 13:28
I can't answer this question, I don't know how to compile the local engine, this is too difficult for me. I tested this issue and it still exists in the latest version

**Comment by jicg** [comment] 2020-01-08 13:29
I have used native development to solve the problem.

**Comment by TahaTesser** [comment] 2020-06-05 14:31
Hi @jicg 
Since you have moved and issue  reproducible without any additional information 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-06-05 14:31 UTC
Labels: a: text input, f: material design, framework
