### ISSUE TITLE
[Web]Unhandled exception: Invalid argument(s): Expected a library reference to be valid but was `null`

### ISSUE THREAD

**Issue by wangning08115** [flutter/flutter#102855] opened 2022-04-29 23:24 UTC
## Steps to Reproduce

1. Execute `flutter run`  on Chrome 
```
Running "flutter pub get" in icr-fe-flutter5.0...
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Unhandled exception:
Invalid argument(s): Expected a library reference to be valid but was `null`.
#0      BinaryPrinter.writeLibraryReference (package:kernel/binary/ast_to_binary.dart:987:7)
#1      BinaryPrinter.writeLibraryDependency (package:kernel/binary/ast_to_binary.dart:1129:5)
#2      BinaryPrinter.writeLibraryDependencies (package:kernel/binary/ast_to_binary.dart:1111:7)
#3      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1051:5)
#4      Library.accept (package:kernel/ast.dart:557:38)
#5      BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:451:10)
#6      BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:756:9)
#7      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:595:7)
#8      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#9      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
#10     IncrementalSerializer.serialize (package:front_end/src/fasta/incremental_serializer.dart:308:13)
#11     IncrementalSerializer.writePackagesToSinkAndTrimComponent (package:front_end/src/fasta/incremental_serializer.dart:158:24)
#12     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:699:29)
#13     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:576:13)
<asynchronous suspension>
#14     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1154:11)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```
## And 【flutter doctor -v】 show info all right.

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19043.1645], locale zh-CN)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (4 available)
    • AGM3 AL09HN (mobile) • AE5HNU1B09401636 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)    • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)         • chrome           • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)           • edge             • web-javascript • Microsoft Edge 100.0.1185.50
```

**Comment by maheshmnj** [comment] 2022-05-02 06:18
Hi @wangning08115, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.
Duplicate of https://github.com/flutter/flutter/issues/99321 (closed)

Thanks

**Closed** 2022-05-23 07:10 UTC
Labels: waiting for customer response, in triage
