### ISSUE TITLE
[Camera plugin] Image capture not respecting device orientation on iOS

### ISSUE THREAD

**Issue by jsalhi** [flutter/flutter#25475] opened 2018-12-17 20:11 UTC
When taking a picture with the camera plugin, it does not seem to ever be able to take a landscape picture when the device is rotated. Not sure if there is some setting that needs to be enabled or configuration issue

Device is iPhone 8 (MQ6K2LL/A)
iOS 12.0.1

This looks like the same issue, on android: #21545
Might also be a duplicate of: #16587

See screenshot of camera plugin example below: 

![screenshot_20181217-120218](https://user-images.githubusercontent.com/5790254/50112341-db556c00-01f3-11e9-8086-73bb3bcf9f9e.png)

Flutter doctor output: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.0.1-pre.72, on Mac OS X 10.14.1 18B75, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-18 08:12
Duplicate of #17606

**Comment by zoechi** [comment] 2018-12-18 08:13
There is a PR waiting to be approved.
Please add a comment to have this issue reopened if you don't think this is a duplicate.

**Closed by zoechi** 2018-12-18 08:12 UTC
