### ISSUE TITLE
Text widget auto converts some strings to emoji/symbol(?) upon render

### ISSUE THREAD

**Issue by json469** [flutter/flutter#62636] opened 2020-07-31 01:47 UTC
Text widget automatically converts some strings to emoji/symbol(?) upon rendering on web (tested on Chrome and Safari) and mobile (tested on iOS only for now).
I have found out that "edge" and "ember" seems to be converting itself to some kind of symbol/emoji(?).
I've been searching the web for similar issues but found none - am I going mad or could someone explain or replicate this? 😆

I've just found out while working on a flutter web and thought it was only for web but it turns out it affects mobile too (which I'm highly doubtful of)! Also tried adding a generic :) to see if it converts to an emoji, but it doesn't seem to do that.

In Code:
`Text('To wisdom belongs the intellectual apprehension of eternal things; to knowledge, the rational knowledge of temporal things.')`
On Web:
<img width="911" alt="Screen Shot 2020-07-31 at 1 33 22 PM" src="https://user-images.githubusercontent.com/42906681/88991166-0098de80-d334-11ea-9b58-38de83a4f24d.png">

In Code:
`Text('To wisdom belongs the intellectual apprehension of eternal things; to knowledge, the rational knowledge of temporal things. :) ember')`
On iOS:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-31 at 13 39 39](https://user-images.githubusercontent.com/42906681/88991041-adbf2700-d333-11ea-9d20-603b7b2bddeb.png)

I am on latest Flutter Master channel.

**Comment by json469** [comment] 2020-07-31 02:02
UPDATE: I'm confident that the culprit is my imported font [Font Awesome](https://fontawesome.com/v4.7.0/icon/edge). If this is the case, how should one prevent this from happening?

**Comment by TahaTesser** [comment] 2020-07-31 10:14
Hi @json469 
Are you using [font_awesome_flutter](https://pub.dev/packages/font_awesome)
If that's the cause of the use, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/font_awesome_flutter/issues). or open issue on whichever font awesome flutter package you're using 

If the problem persist without using third party packages,  Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment] 2020-08-25 15:25
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 15:25 UTC
Labels: in triage
