### ISSUE TITLE
[linux] Full IME support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30662] opened 2019-04-08 02:58 UTC
Text input in the Linux shell is currently minimal; we need full unicode support using system IMEs. The details for that will likely depend on the toolkit we end up using for the shell.

**Comment by chopikus** [comment] 2019-07-21 21:30
So, now, while the unicode in flutter's embedder is not fully supported, you can use go-embedder, which works really good.
https://github.com/go-flutter-desktop/go-flutter

**Comment by stuartmorgan** [comment] 2020-04-23 05:43
@robert-ancell In GTK, is this actually separate from getting text input working, or do IMEs just feed into the system that you'll be getting the text input from already?

**Comment by robert-ancell** [comment] 2020-05-13 04:59
> @robert-ancell In GTK, is this actually separate from getting text input working, or do IMEs just feed into the system that you'll be getting the text input from already?

I can confirm based on https://github.com/flutter/engine/pull/18314 that text input is connecting the the IMEs that GTK abstracts, so this is basically the same thing. There might be some additional work to make sure the more complex IMEs work but for basic methods it should just work.

**Comment by csells** [comment] 2020-05-19 18:44
duplicate of https://github.com/flutter/flutter/issues/54853

**Closed by csells** 2020-05-19 18:44 UTC
Labels: a: desktop, engine, platform-linux
