### ISSUE TITLE
Tree is still closed after GoB outage, clicking the button to re-run jobs fails

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88197] opened 2021-08-13 23:02 UTC
The tree was closed for some time due to a GoB outage. Chat messages indicate that the outage is resolved, but attempts to rerun the failing jobs on the cocoon dashboard are failing.

**Comment by godofredoc** [comment] 2021-08-13 23:34
Some tasks have already one success but there are also several failures. The retry logic does not allow to retry when there is already a successful tasks but it is also conflicting with the dashboard status validation which gets only the latest task.

![image](https://user-images.githubusercontent.com/54371434/129427117-9543b27f-a5a6-4112-ae0b-46431ca9a293.png)

**Comment by godofredoc** [comment] 2021-08-14 00:01
The builds were manually retried to reopen the tree. Setting the priority as P2

**Comment by godofredoc** [comment] 2021-08-14 00:03
The logic for the retries and the build state are not consistent:

* Retry logic does not allow to retry a build if at least one build for the commit and task have succeeded.
* The status task-commit status is calculated using the latest build for that given commit and task.

We need to make the logic consistent.

**Comment by yusufm** [comment] 2021-08-14 00:21
Which of the 2 options should be used everywhere? 

If we are not as concerned about test flakiness (vs. infra flakiness), then taking any(successful build) for a commit's task, is appropriate.

**Comment by godofredoc** [comment] 2021-08-16 19:23
@zanderso @jonahwilliams @jmagman what would be the correct status calculation for a cell in the flutter dashboard?

1.- any successful build for a given commit and test = pass.
2.- if last build for a commit + build is successful = pass, any other state = fail.

**Comment by zanderso** [comment] 2021-08-16 19:28
If the failures will be properly accounted for by the flake reduction process, then I think (1) would be the least confusing.

**Comment by godofredoc** [comment] 2021-08-23 18:06
We'll need to change the buildservice calculate cumulative status to pass if there is at least one successful task:

https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/service/build_status_provider.dart;l=54

**Comment by godofredoc** [comment] 2021-08-25 00:04
Turns out the datastore keeps only the last task data. The current datastore model was adapted from the first cocoon implementation and is not optimized for the current use cases.

To address the foundational datastore design issues, we'll need to redesign the data model for the current use cases.

**Comment by godofredoc** [comment] 2023-06-13 18:45
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.

**Comment by zanderso** [comment] 2023-06-20 17:11
@godofredoc was there some other issue to track the work you outlined in https://github.com/flutter/flutter/issues/88197#issuecomment-905054629 ?

**Comment by keyonghan** [comment] 2023-07-20 18:39
> @godofredoc was there some other issue to track the work you outlined in [#88197 (comment)](https://github.com/flutter/flutter/issues/88197#issuecomment-905054629) ?

The culprit of the problem was the scheduler: it re-scheduled multiple builds even if there was already an earlier `pass` build.

We have landed several fixes to improve the scheduler, and the issue hasn't been reproduced for months. 

To close here, created https://github.com/flutter/flutter/issues/131008 to track all task statuses from datastore side.

**Closed by keyonghan** 2023-07-20 18:39 UTC
Labels: team-infra, P2
