### ISSUE TITLE
Reordarable list can be dismissable.

### ISSUE THREAD

**Issue by amitshinde110113** [flutter/flutter#48197] opened 2020-01-05 05:47 UTC
## Proposal

Add new feature to Reaordarable list.
Make reorerable list dismissable. Each list item can reorderable and aslo dimissable.

**Comment by hoshinokanade** [comment] 2020-01-05 18:00
Did you tried using [Dismissable](https://api.flutter.dev/flutter/widgets/Dismissible-class.html) with ReordarableListView?
```
ReorderableListView(
  onReorder: (int oldIndex, int newIndex) => {} // do sth,
  children: [
    Dismissable(
       key: //All children of ReorderableListView must have a key and so as Dismissable
       child: ListTile(
         // ...
       )
    )
  ]
)
```

**Comment by dnfield** [comment] 2020-01-06 04:22
It's not entirely clear what you want to do here.  It's also not clear if @hoshinokanade solves your problem.  Can you update this with some more details?

**Comment by VladyslavBondarenko** [comment] 2020-02-14 15:36
Closing since the issue is still without answer
@amitshinde110113 feel free to comment or create a new one

**Closed by VladyslavBondarenko** 2020-02-14 15:36 UTC
Labels: f: material design, f: scrolling, framework, severe: new feature, waiting for customer response
