### ISSUE TITLE
strongly hope that webview_flutter supports desktop!

### ISSUE THREAD

**Issue by 826327700** [flutter/flutter#141082] opened 2024-01-08 02:47 UTC
### Use case

I am currently developing a desktop application, and some of its features are developed using web technologies, which need to be embedded into Flutter layouts.

### Proposal

For developers who have a deep love for Flutter, developing desktop applications with Flutter is undoubtedly the most convenient choice. However, Flutter currently has many shortcomings when it comes to desktop applications, and one of the most influential ones is WebView. In enterprise-level projects, many functionalities rely on web-based implementations, and it may be necessary to pass messages between JavaScript and Dart. So far, I haven't found any suitable solutions for embedding WebView in desktop applications, and I really hope that the official team can address this issue.

**Comment by jwinarske** [comment] 2024-01-08 03:09
@826327700 I've started an open source webview plugin targeting CEF.  It's for my custom Auto embedder.  The plug-in code follows the standard pattern, and source code wise is near identical to a Windows plug-in.  Not generic desktop but a starting point for others to follow.  Should be published mid/late February.

en.m.wikipedia.org/wiki/Chromium_Embedded_Framework

**Comment by heath3n** [comment] 2024-01-08 03:14
This has been a long-standing request; upvoting one of the existing issues is preferred to creating a new one:

* https://github.com/flutter/flutter/issues/41725
* https://github.com/flutter/flutter/issues/37597
* https://github.com/flutter/flutter/issues/41726

**Comment by danagbemava-nc** [comment] 2024-01-08 10:23
Closing this as a duplicate of the issues linked in https://github.com/flutter/flutter/issues/141082#issuecomment-1880330219

Please upvote the issues linked above.

**Closed by danagbemava-nc** 2024-01-08 10:23 UTC
Labels: in triage
