### ISSUE TITLE
Shortcuts widget consumes keys that should be consumed by descendant widgets

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#143011] opened 2024-02-06 20:57 UTC
## Steps to reproduce

Run the following app, type into the text field, then try to move the text cursor back and forth with the left and right arrow keys:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MaterialApp(home: BugReport()));
}

class BugReport extends StatelessWidget {
  const BugReport({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Shortcuts(
        shortcuts: const <ShortcutActivator, Intent>{
          SingleActivator(LogicalKeyboardKey.arrowRight): PrintMessageIntent(),
        },
        child: Actions(
          actions: <Type, Action<Intent>>{
            PrintMessageIntent: PrintMessageAction.instance,
          },
          child: const Padding(
            padding: EdgeInsets.all(100),
            child: Center(
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}

class PrintMessageIntent extends Intent {
  const PrintMessageIntent();
}

class PrintMessageAction extends ContextAction<PrintMessageIntent> {
  static final PrintMessageAction instance = PrintMessageAction();

  @override
  void invoke(PrintMessageIntent intent, [BuildContext? context]) {
    print('this is a message');
  }
}
```

## Expected behavior

Since the text field has the focus, you expect the right key events to be directed to the text field and not to the shortcuts widget.

## Actual behavior

When you hit the right arrow key, the `PrintMessageAction` gets invoked, _and the text cursor is not moved to the right_.

## Flutter version

```
[✓] Flutter (Channel main, 3.20.0-2.0.pre.6, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
    • Flutter version 3.20.0-2.0.pre.6 on channel main at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f8a77225f3 (2 days ago), 2024-02-04 14:28:18 +0000
    • Engine revision f34c658b96
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0
```

**Comment by gspencergoog** [comment] 2024-02-06 22:09
> I'm guessing the official answer will be to override the default binding at the WidgetsApp layer (via [WidgetsApp.shortcuts](https://api.flutter.dev/flutter/widgets/WidgetsApp/shortcuts.html))

Yes, that seems like the right answer. You can get the map of default shortcuts from [`WidgetsApp.defaultShortcuts`](https://api.flutter.dev/flutter/widgets/WidgetsApp/defaultShortcuts.html), and replace the ones you want to change.

**Comment by gspencergoog** [comment] 2024-02-06 22:10
Closing as working as intended.

**Closed by gspencergoog** 2024-02-06 22:10 UTC
Labels: a: text input, f: focus, P2, fyi-framework

**Comment by justinmc** [comment] 2024-02-06 22:33
If you see any docs about this that should change let me know though!
