### ISSUE TITLE
App is crashing for Flutter is added to existing app

### ISSUE THREAD

**Issue by rahuldevanavar91** [flutter/flutter#37234] opened 2019-07-30 11:13 UTC
I have added flutter is added to existing app.eveverthing is working fine, but flutter is on some devices specifically with android OS 6.0 and below with the following exception.

`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.manash.purplle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.manash.purplle-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
`

build. gradle  in Native app
`        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
`

Flutter doctor 

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)

```

@xster @matthew-carroll , please help out we are facing this issue in production.

**Comment by stuartmorgan** [comment] 2019-07-30 14:48
You need `hotfix.4`

Duplicate of #35838

**Comment by rahuldevanavar91** [comment] 2019-08-30 09:49
@stuartmorgan 

I have upgraded to `[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-IN)`
But still, I am facing the issue

**Comment by xster** [comment] 2019-08-30 18:38
How are you making the integration? Is it via include_flutter.groovy or by building aars? 

Can you drag drop your apk into Android Studio and show us the contents of the apk?

cc @blasten

**Comment by blasten** [comment] 2019-08-30 20:14
I looks like think the issue is that you are telling NDK to build APKs for 'x86' and 'x86_64', but Flutter doesn't support either on release mode. We plan to add support for 'x86_64' soon though. See https://github.com/flutter/flutter/issues/9253#issuecomment-523239868

**Comment by xster** [comment] 2019-08-30 20:47
ah ok, let's just merge it into https://github.com/flutter/flutter/issues/39520

**Comment by rahuldevanavar91** [comment] 2019-08-31 05:39
@xster 

I am using `flutter build appbundle --target-platform android-arm,android-arm64` build bundle. and included include_flutter.groovy .

Contents of APK
<img width="1038" alt="Screenshot 2019-08-31 at 10 59 18 AM" src="https://user-images.githubusercontent.com/12570474/64059672-c9c7bf00-cbde-11e9-82fb-f91ca20584c1.png">


Any workaround to solve this issue.on production, its impacting may users.

<img width="1152" alt="Screenshot 2019-08-31 at 11 06 00 AM" src="https://user-images.githubusercontent.com/12570474/64059734-b23d0600-cbdf-11e9-8d2e-944e076a8074.png">

**Comment by xster** [comment] 2019-09-04 19:39
I'm not sure I understand. It sounds like there are 3 concepts mixed together. 

1- Are you building a Flutter app or a Flutter module? By referencing include_flutter.groovy, it sounds like you're building an app around a Flutter module but `flutter build appbundle` is invoked on an app. 

2- Are you publishing an APK to the Play Store or an AAB? You mentioned `flutter build appbundle` which produces a .aab but you showed the contents of an .apk. Which .apk are you showing and how did you build it? 

3- The .apk you're showing has more architectures than what you provided as Flutter dependencies. You'd want to specify the supported architectures in your downstream app's gradle which uses Flutter rather than doing anything in Flutter itself (by using ndk.abiFilters for instance)

**Comment by rahuldevanavar91** [comment] 2019-09-05 07:20
@xster 

1. We are adding flutter into our existing native app, so we build` Flutter  module`.
2. we are publishing `appbundle`  to play store.
3.   Already added the NDK flitter in app/gradle file   `ndk.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'`

aab file analyser.

![image](https://user-images.githubusercontent.com/12570474/64320209-a7b5ae80-cfdb-11e9-928d-ee70a44cc9c9.png)

**Comment by xster** [comment] 2019-09-06 02:51
1- understood
2- right, but you're not using `flutter build appbundle` to build your native app that uses the Flutter module right? `flutter build appbundle` only builds Flutter apps.
3- added a note to #32862 to clearly document that Flutter doesn't support building AOT x86 or x64 outputs. In your case, you'd have to filter those abis out. Also, can you let us know which Xiaomi devices are x86 in your userbase?

**Comment by rahuldevanavar91** [comment] 2019-09-10 09:38
1-We are added flutter into our exiting android app as module 
2- yes `flutter build appbundle` only build the flutter module,so generate aab for app we build app bundle for native android application.
3- There are many Xiaomi (Redmi 5 pro,Redmi 5A,Redmi 7 pro )
    Os version Android 9 - 31%, 8-26%,,7-26%,6-11%,Other-6%
            


For this error is in /**lib/arm64**
`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.manash.purplle-mC-3yH6mM3hZLZxFbgvqoA==/base.apk"],nativeLibraryDirectories=[/data/app/com.manash.purplle-mC-3yH6mM3hZLZxFbgvqoA==/lib/arm64, /system/lib64]]] couldn't find "libflutter.so"
`

**Comment by xster** [comment] 2019-09-10 20:58
> For this error is in /lib/arm64

Ummm, this is curious. Can you help us get a minimum reproducible case with a test project? Is this happening on all devices?

Also cc @jason-simmons. Wondering if `--icu-native-lib-path=" + applicationInfo.nativeLibraryDir`  may point to incorrect places on some OEMs.

**Comment by blasten** [comment] 2019-09-10 23:22
@rahuldevanavar91 if you have one of these devices, could you print the value of `applicationInfo.nativeLibraryDir`? Also, would you mind trying to reproduce this issue with a regular Flutter app? e.g. try this:

```
flutter create my_app
flutter build appbundle
```
Read https://developer.android.com/studio/command-line/bundletool#generate_apks to generate the APK from the app bundle, then deploy the APK to the device and confirm if this causes the issue.

**Comment by rahuldevanavar91** [comment] 2019-09-13 07:25
@blasten We do not have the physical device with us, we are getting the crash log on production.
I will add `applicationInfo.nativeLibraryDir` log to the production app and let you know.

**Comment by rahuldevanavar91** [comment] 2019-09-13 11:04
```
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.manash.purplle-1/base.apk"],
nativeLibraryDirectories=[/data/app/com.manash.purplle-1/lib/arm64, /vendor/lib64, /system/lib64]]] 
couldn't find "libflutter.so"
```


nativeLibraryDir -  `/data/app/com.manash.purplle-1/lib/arm64

```

Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.manash.purplle-1/base.apk", zip file "/data/app/com.manash.purplle-1/split_config.x86.apk", zip file "/data/app/com.manash.purplle-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.manash.purplle-1/lib/x86, /vendor/lib, /system/lib]]] 
couldn't find "libflutter.so"
```

NativeLibraryDir- /`data/app/com.manash.purplle-1/lib/x86
`

**Comment by rahuldevanavar91** [comment] 2019-09-18 07:18
@blasten @xster  any update on this, we have a high impact of this crash

**Comment by wakakajp** [comment] 2019-09-27 11:09
excuse me, is there any progress on this issue?

**Comment by blasten** [comment] 2019-09-30 16:39
Hey @rahuldevanavar91. I sent this bug to the team that works on App Bundles. I don't have an answer at the moment. Based on what the log says, these devices are loading native libraries from `lib/arm64` instead of `lib/arm64-v8a`.

**Comment by blasten** [comment] 2019-09-30 17:00
@rahuldevanavar91. In the meanwhile, could you attach the full stacktrace, package name and version code? 

https://support.google.com/googleplay/android-developer/answer/6083203?hl=en

**Comment by rahuldevanavar91** [comment] 2019-10-01 06:46
```
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.manash.purplle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.manash.purplle-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
io.flutter.view.FlutterMain.startInitialization

```


```

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.manash.purplle <<<

backtrace:
  #00  pc 000000000004d320  /data/app/com.manash.purplle-1/split_config.arm64_v8a.apk

```
Package name - com.manash.purplle 
version code - 244

**Comment by blasten** [comment] 2019-10-02 20:45
I sent this issue to the App Bundle team. In the meanwhile, make sure the AAB does not contain x86 and x86_64 variants in release mode since that would result in crash:
```.diff
-ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
+ndk.abiFilters 'armeabi-v7a','arm64-v8a'
```

Follow https://github.com/flutter/flutter/issues/9253 for support for 'x86_64'.

**Comment by rahuldevanavar91** [comment] 2019-10-03 14:15
@blasten 
if we exclude `'x86','x86_64'` app will not be available for these devices, around 5% of our user base fill into this category.

When we can expect this issue to get solved.

**Comment by blasten** [comment] 2019-10-03 15:12
So far, it appears that these devices don't support App Bundles correctly.  I will update as I find out more.

**Comment by blasten** [comment] 2019-10-03 17:32
@rahuldevanavar91  I would suggest you follow the steps outlined on https://developer.android.com/studio/build/configure-apk-splits and upload multiple APKs to the Play Store.

I'm closing the issue as there's a workaround. Feel free to reopen the issue if the crashes continue after publishing multiple APKs.

**Closed by blasten** 2019-10-03 17:32 UTC
Labels: a: existing-apps, severe: crash, ▣ platform-android

**Comment by rahuldevanavar91** [comment] 2019-10-03 17:41
@blasten 

Thanks for update . Please let us know one you fix app bundle issue ..I think uploading multiple APKs is not right way .

**Comment by rahuldevanavar91** [comment] 2019-10-15 11:24
@blasten  As you suggested,
`NDK ABI` filters as 
`        ndk.abiFilters 'armeabi-v7a', 'arm64-v8a'
`

but still, it's crashing 

```
 dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.manash.purplle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.manash.purplle-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
io.flutter.view.FlutterMain.startInitialization

```

`OPP, LGE, and SAMSUNG devices `

**Comment by plecesne** [comment] 2019-10-18 17:04
Do you have a list of the devices (and SDK version) that experience those crashes?
