### ISSUE TITLE
Firebase does not sort items by date correctly

### ISSUE THREAD

**Issue by AlexDeveloper007** [flutter/flutter#78790] opened 2021-03-22 15:36 UTC
I am filtering some documents by date / time to retrieve the most recent items first.

However, when adding a new item to the list it is added correctly, but when restarting the app the list is redone and the items are arranged at random, which should not be happening because I am ordering by date.

It could be that I am doing this to add these items to the list.

**I'm doing it like this:**
```

Future<void> _addListernerFavoritos() async{
      favoritosModel.limparLista();
      List<String> listaBackp = [];
    
      FirebaseFirestore.instance
          .collection("usuarios")
          .doc(usuario.idUsuario)
          .collection("favoritos")
          .orderBy("data", descending: true)
          .snapshots()
          .listen((snapshot) {
    
        snapshot.docChanges.forEach((change) async{
          String idEmpresa = change.doc.id;
    
          switch (change.type) {
            case DocumentChangeType.added:
            //========== quando um favorito for adicionado ==========
    
              DocumentSnapshot docEmp = await FirebaseFirestore.instance
                  .collection("empresas")
                  .doc(idEmpresa)
                  .get();
    
              Empresa empresa = Empresa.fromDocumentSnapshot(docEmp);
              if(!favoritosModel.listFavoritos.contains(empresa)){
                //favoritosModel.addFavoritos(empresa);
                favoritosModel.insertFavorito(0, empresa);
              }
    
              break;
            case DocumentChangeType.modified:
            //========== modificado ==========
              break;
            case DocumentChangeType.removed:
            //========== removido ==========
              favoritosModel.removeWhere(idEmpresa);
              listaBackp.add(idEmpresa);
              break;
          }
        });
    
        //_sort();
      });
    }
```

**The model I'm using to update the list is this:**

    class FavoritosModel = _FavoritosModel with _$FavoritosModel;
    
    abstract class _FavoritosModel with Store{
    
      @observable
      ObservableList<Empresa> listFavoritos = ObservableList();
    
      @action
      void insertFavorito(int index, Empresa value){
        listFavoritos.insert(index, value);
      }
    
      @action
      void addFavoritos(Empresa value) {
        listFavoritos.add(value);
      }
    
      @action
      void removeWhere(String idEmpresa){
        listFavoritos.removeWhere((empresa) => idEmpresa == empresa.idEmpresa);
      }
    
      @action
      void limparLista(){
        listFavoritos.clear();
      }
    
      @action
      void attEmpresa(int index, Empresa value){
        listFavoritos.removeWhere((empresa) => empresa.idEmpresa == value.idEmpresa);
        listFavoritos.insert(index, value);
      }
    
    }

**My listView looks like this:**

    @override
      Widget build(BuildContext context) {
    
        return Container(
          color: Cores.COR_CINZA_BACKGROUND,
          child: Observer(
            builder: (_){
              FavoritosModel favoritosModel = GetIt.I<FavoritosModel>();
              ObservableList<Empresa> listFavoritos = favoritosModel.listFavoritos;
    
              if(listFavoritos.length == 0){
                return Container(
                  margin: EdgeInsets.only(left: 16, right: 16),
                  child: Center(
                    child: TextApp(
                      text: "Você ainda não adicionou nenhuma empresa aos favoritos",
                      fontSize: 16,
                      textColor: Cores.COR_DARK_LIGTH,
                      fontFamily: "OpenSans",
                      centralizar: true,
                    ),
                  ),
                );
              }
              return ListView.builder(
                //reverse: true,
                itemCount: listFavoritos.length,
                itemBuilder: (context, index){
    
                  Empresa empresa = listFavoritos[index];
    
                  if(empresa == null){
                    return Container();
                  }
    
                  return GestureDetector(
                    onTap: (){
                      push(context, TelaEmpresa(empresa: empresa));
                    },
                      child: CardEmpresa(empresa: empresa, favoritos: true,));
                },
              );
    
            },
          ),
        );
    
      }
In my view everything is correct, I do not understand why it is not sorting by date. can anybody help me?

**I have already tried to save the date in these two ways and neither works:**

    Timestamp getDataFiltro(){
      var now = new Timestamp.now();
      return now;
    }
    
    String getDateNow(){
      var now = new DateTime.now();
      return now.toString();
    }

**Comment by pedromassangocode** [comment] 2021-03-23 07:31
Hi @AlexDeveloper007 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-23 07:31 UTC
Labels: in triage
