### ISSUE TITLE
Class function attribute 'call' breaks in web release mode with null values

### ISSUE THREAD

**Issue by Guru-Zachw** [flutter/flutter#151978] opened 2024-07-18 17:50 UTC
### Steps to reproduce

<details open><summary>Steps to reproduce</summary>

1.  create a fresh flutter app
2.  create a simple "builder" class that takes an argument 'call' as an argument. This attribute should be a function that has a nullable argument.
3.  create an instance of the class where the provided function null checks the nullable argument to ensure that it is not null and use the value in any way.
4. Call the function somewhere with the nullable value being null, note that you will have to do .call as the call override is not determined to be valid by the linter.
5. compile in any web renderer in release mode.
6. Watch it recieve a null error. If these instructions do not work, attempt to run it in the build function and have the builder build a widget.

</details>

### Expected results

<details open><summary>Expected Results</summary>
Multiple Valid results are possible, but non occured

1. The linter says 'call must be an overridden function on the class' or something to that effect
2. Allow the call function to be called is if it is overriding the call class
3. .call is callable without errors on all platforms, still not making the class callable.

</details>

### Actual results

<details open><summary>Actual Result</summary>

3 occurs on android(release or otherwise) and on web debug (that's all I tested)

Web release (any renderer) successfully compiles, but when the function is called it throws a 'Null check operator used on a null value' error, despite the null value having been checked before use.

</details>
### Code sample

<details open><summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TestWidget(),
    );
  }
}

class BuilderThing {
  final Widget Function(BuildContext context, double? height) call;
  BuilderThing(this.call);
}

class TestWidget extends StatelessWidget {
  final double? height;
  const TestWidget({super.key, this.height});


  @override
  Widget build(BuildContext context) {
    final builder = BuilderThing((BuildContext context, double? height) {
      double scale = 1;
      if (height != null) {
        scale = height + 1;
      }
      return Transform.scale(
        scale: scale,
        child: Container(
          color: Colors.red,
          height: 100,
          width: 100,
        ),
      );
    });
    return Center(child: builder.call(context, height));
  }
}

```
</details>

### Screenshots or Video

<details open><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/bbef9218-0fd7-4135-b4f4-23283999c9d9)
</details>

### Logs

<details open><summary>Logs</summary>
Run from VSCode web release html 

```console
Null check operator used on a null value
js_primitives.dart:28     at Pe.$2 (http://localhost:44261/main.dart.js:49575:24)
js_primitives.dart:28     at Gg.$2 (http://localhost:44261/main.dart.js:49491:23)
js_primitives.dart:28     at yP.Z (http://localhost:44261/main.dart.js:49573:39)
js_primitives.dart:28     at yD.b2 (http://localhost:44261/main.dart.js:45820:18)
js_primitives.dart:28     at yD.ft (http://localhost:44261/main.dart.js:45796:9)
js_primitives.dart:28     at yD.oU (http://localhost:44261/main.dart.js:45756:10)
js_primitives.dart:28     at yD.Dt (http://localhost:44261/main.dart.js:45757:18)
js_primitives.dart:28     at yD.qC (http://localhost:44261/main.dart.js:45794:11)
js_primitives.dart:28     at yD.ee (http://localhost:44261/main.dart.js:45793:6)
js_primitives.dart:28     at pZ.oc (http://localhost:44261/main.dart.js:45680:3)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on Linux Mint 20.2
    9.4.0-189-generic, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at
      /home/zachw/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05
      22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK
    version 35.0.0)
    • Android SDK at /home/zachw/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /home/zachw/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.23+9-post-Ubuntu-1ubuntu120.04.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK
      licenses.
      See
      https://flutter.dev/docs/get-started/install/linux#android-set
      up for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-set
      up for detailed instructions).

[✓] VS Code (version 1.91.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.2
      5.4.0-189-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome
      126.0.6478.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2024-07-19 07:35
Thanks for the report. I was able to replicate the reported error in release mode.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (33 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.24.0-1.0.pre.197, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.197 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0bac2be379 (76 minutes ago), 2024-07-19 00:15:26 -0400
    • Engine revision ea1e53a4e8
    • Dart version 3.6.0 (build 3.6.0-55.0.dev)
    • DevTools version 2.37.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by jason-simmons** [comment] 2024-07-19 18:08
Reproduced this on the current Flutter head (Dart SDK `3.6.0-55.0.dev`).

The `(height != null)` check is evaluating as true even though `height` is null.

This still happens when building with `--dart2js-optimization=O1`.  It isn't a recent regression.

@sigmundch

**Comment by sigmundch** [comment] 2024-07-19 18:42
Thanks for the nice reproduction! 

As you noted in your description, I also believe this issue is only happening for a field named `call`. That resonates because of the special treatment `call` has in the compilers to support making objects invocable when they have a method named `call`. (and there was some historical support in the past to include getters named call as well)

I filed https://github.com/dart-lang/sdk/issues/56293 to track the underlying dart2js issue on the Dart SDK repo.

**Comment by biggs0125** [comment] 2024-07-22 17:52
A fix was just pushed to the Dart SDK in https://github.com/dart-lang/sdk/commit/629d170962a3be20aab318864527bc6f73eeaba7

**Comment by a-siva** [comment] 2024-07-24 21:05
@biggs0125 does the fix above need to be cherry picked into the stable branch ?

**Comment by biggs0125** [comment] 2024-07-31 22:34
We've decided against cherrypicking this change into the stable branch. Until the fix is available, there are two fairly easy workarounds in this situation.
GIven this code:
```
class A {
  Function get call => ...;
}
void main() {
  A().call();
}
```
You can:
1) Avoid having a getter named 'call' that returns a Function.
```
class A {
  Function get doCall => ...;
}
void main() {
  A().doCall();
}
```
2) Bind the result of the getter to a variable and then call that variable.
```
class A {
  Function get call => ...;
}
void main() {
  final toCall = A().call;
  toCall();
}
```

**Comment by a-siva** [comment] 2024-08-07 20:39
Can this issue be closed as fixed ?

**Comment by yjbanov** [comment] 2024-08-15 18:21
Thanks for fixing this in the compiler. Closing the Flutter-side issue.

**Closed by yjbanov** 2024-08-15 18:21 UTC
Labels: dependency: dart, platform-web, has reproducible steps, blocked, team-web, found in release: 3.22, found in release: 3.24
