### ISSUE TITLE
`android:enableOnBackInvokedCallback="true"` in Android manifest is not supported by `flutter create`

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#135815] opened 2023-10-01 00:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If you put `android:enableOnBackInvokedCallback="true"` in your `application` element of your `android/app/src/main/AndroidManifest.xml`, then you are enabling a new predictive gesture-based back mode, which requires support on the Android side.

https://stackoverflow.com/a/73782321/3950982

This disables the Back button events even being sent through to Flutter, which means that pressing the Back button pops the entire app, every time.

As I understand it, this will become the default in the future, and yet `flutter create . --platforms=android` does not create code that works with this model of Back button behavior.

### Expected results

`flutter create` should create Android code that can handle the new predictive gesture-based Back mode, ensuring that events are still sent through to Flutter if `android:enableOnBackInvokedCallback="true"` is in the manifest file.

### Actual results

`android:enableOnBackInvokedCallback="true"` in the Android manifest file completely disables Back button events from being sent to Flutter, based on the default code generated by `flutter create`.

### Code sample

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.13.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.27.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-01 02:17
Closing as a duplicate of https://github.com/flutter/flutter/issues/132504

**Closed by stuartmorgan** 2023-10-01 02:17 UTC
