### ISSUE TITLE
[video_player] Video does not play in iOS web

### ISSUE THREAD

**Issue by Leffe108** [flutter/flutter#83005] opened 2021-05-20 10:36 UTC
In response to [47030](https://github.com/flutter/flutter/issues/47030#issuecomment-841419012), here is a reproducable example that fulfills:
* Flutter video_player do not play on iOS Safari
* HTML5 do play the video on iOS Safari 
* The video plays fine in both flutter video_player and html5 on other tested platforms (Chrome on Android, Chrome on Windows and Firefox on windows). 

The two iOS devices that I have tested on are:
* iPhone SE (model A1723) with iOS 14.4.2
* iPad pro (model A2230) with iOS 14.5.1

## Steps to Reproduce

1. Run `flutter create bug_video`.
2. Update the files as follows: 

In pubspec.yaml add these two dependencies:
```
  video_player: 2.1.1
  url_launcher: 6.0.4
```

In web/index.html update base to desired base url for hosting location.

<details>
  <summary>lib/main.dart</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Video demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _playIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            if (kIsWeb)
              ElevatedButton(
                  onPressed: () async {
                    // Go to html5.html on same host as index.html is served at
                    Uri uri = Uri.base;
                    String path = uri.path.replaceAll('index.html', '');
                    if (!path.endsWith('/')) path += '/';
                    path += 'html5.html';
                    uri = uri.replace(path: path, fragment: null);
                    if (await canLaunch(uri.toString())) {
                      launch(uri.toString());
                    }
                  },
                  child: Text('Go to HTML player')),
            Text('W'),
            MyVideoPlayer(
                key: Key('video $_playIndex'),
                url:
                    'https://teckensprakslexikon.su.se/movies/11/w-11943-tecken.mp4'),
            Text('Video is CC-BY-NC-SA 2.5 from Svenskt Teckenspråkslexikon'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.play_arrow),
        onPressed: () {
          setState(() {
            this._playIndex += 1;
          });
        },
      ),
    );
  }
}

class MyVideoPlayer extends StatefulWidget {
  final String url;

  const MyVideoPlayer({Key? key, required this.url}) : super(key: key);

  @override
  _MyVideoPlayerState createState() => _MyVideoPlayerState();
}

class _MyVideoPlayerState extends State<MyVideoPlayer> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    _initController();
    super.initState();
  }

  void _initController() async {
    _controller = VideoPlayerController.network(widget.url);
    await _controller.initialize();
    _controller.setVolume(0);
    setState(() {
      _controller.play();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: _controller.value.isInitialized
          ? _controller.value.aspectRatio
          : 16 / 9,
      child: _controller.value.isInitialized
          ? VideoPlayer(_controller)
          : Container(
              color: Colors.black,
              child: Center(
                child: CircularProgressIndicator(),
              ),
            ),
    );
  }
}
```

</details>

<details>
  <summary>web/html5.html</summary>

```dart
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <title>bug_video html5 version</title>
  <style>
    body {
      margin: 0;
      text-align: center;
    }
  </style>
</head>
<body>
  <p>W</p>
  <video 
    autoplay
    playsinline
    controls
    src="https://teckensprakslexikon.su.se/movies/11/w-11943-tecken.mp4"
  ></video>
  <p>Video is CC-BY-NC-SA 2.5 from Svenskt Teckenspråkslexikon</p>
</body>
</html>
```

</details>

3. Deploy web build or use [my deployment](https://tspquiz.se/bug-47030/) (`flutter build web`) and open in Safari on iPhone or iPad
4. Now the video should play 
5. To open the HTML5 video player press on the button above the video or go to https://tspquiz.se/bug-47030/html5.html

**Expected results:** 
I expect the video to play after it has been loaded on iOS devices. 

**Actual results:** 
It does not play in flutter video_player.

<details>
  <summary>Logs</summary>

```
Analyzing bug_video...
No issues found! (ran in 5.8s)
```

```
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19041.985], locale sv-SE)
    • Flutter version 2.2.0 at C:\Users\Leif\Programmering\Libraries\flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Leif\Programmering\Android\android-sdks
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 32-bit edition (version 1.56.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```

</details>

**Comment by ModWU** [comment] 2021-05-20 10:53
I have one more question with `vidio_player`: 
`Vidio_player` cannot save previous video buffers using the `seekTo(Duration position)` function.

**Comment by TahaTesser** [comment] 2021-05-20 15:23
Hi @Leffe108 
It is a duplicate of https://github.com/flutter/flutter/issues/47030, you can post your reproducible steps in the original issue, we don't need a separate issue for steps
Closing as duplicate of https://github.com/flutter/flutter/issues/47030

**Closed by TahaTesser** 2021-05-20 15:23 UTC
Labels: in triage

**Comment by Leffe108** [comment] 2021-05-20 17:32
Sorry, I thought you wanted it as a separate issue. I'll make a reply in that issue then.
