### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yazdanofskii** [flutter/flutter#134130] opened 2023-09-06 12:02 UTC
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1136:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1134:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1051:5)
#9      _invoke1 (dart:ui/hooks.dart:158:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:337:5)
#11     _beginFrame (dart:ui/hooks.dart:101:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:568:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:265:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:171:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController.fling (package:flutter/src/animation/animation_controller.dart:712:12)
#7      DrawerControllerState.open (package:flutter/src/material/drawer.dart:638:17)
#8      DrawerControllerState._handleDragCancel (package:flutter/src/material/drawer.dart:569:7)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#10     DragGestureRecognizer._checkCancel (package:flutter/src/gestures/monodrag.dart:545:7)
#11     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:460:9)
#12     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:465:9)
#13     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:471:5)
#14     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:394:7)
#15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:465:19)
#21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#23     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#24     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#27     _invoke1 (dart:ui/hooks.dart:158:13)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _FrameCallbackEntry)

**Comment by dam-ease** [comment] 2023-09-06 12:29
Hi @yazdanofskii 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-09-06 12:29 UTC
Labels: in triage
