### ISSUE TITLE
VSCode auto-imports for widget snippets include src files

### ISSUE THREAD

**Issue by bryanoltman** [flutter/flutter#108441] opened 2022-07-27 15:13 UTC
## Details

When using the `StatefulWidget`/`StatelessWidget`/`Widget with Animation Controller` snippets provided by the VS Code Flutter plugin, imports from `package:flutter/src/widgets` are used instead of `package:flutter/material.dart` or `package:flutter/widgets.dart`.

## To Reproduce

0. Install VS Code and the Flutter plugin.
1. Create a new Dart file in VS Code.
2. Type 's' to show the Flutter Widget snippets provided by the plugin.
3. Select any one of the Flutter Widget snippets.

### Expected Behavior

Non-src files (material.dart or widgets.dart) are added as imports.

### Actual Behavior

Files from the src directory (`package:flutter/src/widgets/container.dart`, `package:flutter/src/widgets/framework.dart`) are added as imports.

**Comment by huycozy** [comment] 2022-07-28 07:15
Hi @bryanoltman 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by huycozy** 2022-07-28 07:15 UTC
Labels: in triage

**Comment by bryanoltman** [comment] 2022-07-28 16:27
Thanks for pointing me in the right direction! Filed https://github.com/Dart-Code/Dart-Code/issues/4075.
