### ISSUE TITLE
flutter build doesn't work for appbundle with few flavor dimensions

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#92316] opened 2021-10-22 09:15 UTC
Given two flavor dimensions: `app` and `type`

* `example` being in the `app` dimension
* `prod` being in the `type` dimension

and Flutter build command: `flutter build appbundle --release --flavor exampleProd --verbose` `flutter_tools` is looking for the AAB file in:

* `build/app/outputs/bundle/release/app.aab`
* `build/app/outputs/bundle/release/app-release.aab`
* `build/app/outputs/bundle/exampleprodRelease/app.aab`
* `build/app/outputs/bundle/exampleprodRelease/app-exampleprod-release.aab`

And it's **actually** located in`build/app/outputs/bundle/exampleProdRelease/app-example-prod-release.aab` therefore the command fails to complete sucessfully.

```
Gradle build failed to produce an .aab file. It's likely that this file was generated under (...)/build, but the tool couldn't find it.
```

Related `flutter_tools` source code:

https://github.com/flutter/flutter/blob/cf885c12ea5f157efa65a2ef63f7728c2949dced/packages/flutter_tools/lib/src/android/gradle.dart#L850-L888

```
Flutter 2.5.1 • channel unknown • unknown source
Framework • revision ffb2ecea52 (5 weeks ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2
```

**Comment by danagbemava-nc** [comment] 2021-11-17 12:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Albert221** [comment] 2021-11-18 06:55
Here are the steps to reproduce the issue:

1. Create a new project `flutter create aab_multidim_flavor`
2. Add the following code to `android/app/build.gradle` inside the `android {}`:

```groovy
flavorDimensions "app", "type"

productFlavors {
    example {
        dimension "app"
    }

    prod {
        dimension "type"
    }
}
```

Notice how Flutter produces APK no problem and AAB fails to be produced:

```
➜  aab_multidim_flavor flutter build appbundle --flavor exampleProd

💪 Building with sound null safety 💪

Removed unused resources: Binary resource data reduced from 33KB to 19KB: Removed 41%
Running Gradle task 'bundleExampleProdRelease'...                   5.3s
Gradle build failed to produce an .aab file. It's likely that this file was
generated under /Users/albert/Projects/Personal/aab_multidim_flavor/build, but
the tool couldn't find it.
```

```
➜  aab_multidim_flavor flutter build apk --flavor exampleProd

💪 Building with sound null safety 💪

Running Gradle task 'assembleExampleProdRelease'...              1,623ms
✓  Built build/app/outputs/flutter-apk/app-exampleprod-release.apk (15.5MB).
```

---

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-PL)
    • Flutter version 2.5.3 at /Users/albert/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/albert/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

**Comment by maheshmnj** [comment] 2021-11-18 07:00
reopening the issue for further investigation.

**Comment by maheshmnj** [comment] 2021-11-18 10:45
thanks for the reproducible steps @Albert221, I can replicate the same behavior apk builds but the `appbundle` fails, but I am not really sure why the flavor is specified as `--flavor exampleprod`  instead of `--flavor example` or `-- flavor prod`. Keeping this issue open for further investigation from the team.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 19EA5268-C931-4C3A-ACC6-71D3E849C450 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.45

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.719, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.719 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 34dbee66de (3 days ago), 2021-11-14 18:46:02 -0500
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 19EA5268-C931-4C3A-ACC6-71D3E849C450 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.45

• No issues found!
```
</details>



<details>
<summary>logs</summary>

```

💪 Building with sound null safety 💪

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Removed unused resources: Binary resource data reduced from 26KB to 19KB: Removed 28%
Running Gradle task 'bundleExampleprodRelease'...                  46.7s
Gradle build failed to produce an .aab file. It's likely that this file was generated under
/Users/mahesh/Development/counter_app/build, but the tool couldn't find it.
```

</details>

**Comment by Albert221** [comment] 2021-11-18 10:49
This is because those are two [different flavor dimensions](https://developer.android.com/studio/build/build-variants#flavor-dimensions).

Let's say we're building a multi-tenant application using a single codebase, but separating tenants with the `app` flavor dimension. The `type` flavor dimension specifies which environment (API urls, keys, etc.) should be used. So I can have a `--flavor googleProd` for a production env app for Google and `--flavor spotifyDev` for a development env app for Spotify.

Is it clear now? :)

**Comment by maheshmnj** [comment] 2021-11-18 10:52
Yes @Albert221,

Thanks

**Comment by christopherfujino** [comment] 2021-11-30 23:14
cc @blasten

**Comment by blasten** [comment] 2021-12-15 20:13
In the APK case, this was solved by copying the APK to a known location. See https://github.com/flutter/flutter/commit/e61ab4a8324abb0dde014755b6e916d4120cec21 

It would just need the same workaround for App Bundles.

**Comment by GaryQian** [comment] 2022-06-07 17:46
Since appbundles are the preferred way to build Android apps, this seems to be more relevant now.

@blasten any interest/bandwith to add the workaround to appbundles?

**Comment by namidan** [comment] 2022-10-28 04:20
I saw this same issue, but only in the CI (GitHub Actions w/ Ubuntu Latest). 

macOS local `flutter build appbundle` worked just fine with build flavors. 

The root of the issue for me was that my flavors were all in caps (e.g. "PROD", "STG").

On macOS the build output was this: `build/app/outputs/bundle/STGRelease/app-STG-release.aab`, and somehow it was found.

In the CI, running Ubuntu I got the `Gradle build failed to produce an .aab file. It's likely that this file was generated under...` error.

The source referenced above has `buildInfo.lowerCasedFlavor` and  `camelCase(buildInfo.modeName)` which gave me an idea. I renamed my flavors to "prod" and "stg", and the resulting outputs were successfully found on both macOS and in the CI.

**Comment by flodaniel** [comment] 2023-02-24 11:11
We are facing the same issue, but we are using only a single flavorDimension:

```gradle
    flavorDimensions "app"

    productFlavors {
        ...
        prod {
            dimension "app"
            resValue "string", "app_name", "Pave Commute"
        }
    }
```

The aab is produced in `android/app/build/outputs/bundle/prodRelease/app-prod-release.aab`.
I am not yet 100% sure why it is not picking up this specific aab. 

Also this ticket and https://github.com/flutter/flutter/issues/65264 look very similar.

**Closed** 2023-05-19 15:00 UTC
Labels: platform-android, tool, a: build, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
