### ISSUE TITLE
RangeError (length): Invalid value: Valid value range is empty: 0. Error thrown Instance of 'ErrorDescription'. _GrowableList.first

### ISSUE THREAD

**Issue by nikitadol** [flutter/flutter#70612] opened 2020-11-16 13:56 UTC
I am getting errors in Crash Analytics

```console
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
RangeError (length): Invalid value: Valid value range is empty: 0. Error thrown Instance of 'ErrorDescription'.
_GrowableList.first (_GrowableList.java)
RenderParagraph.assembleSemanticsNode (RenderParagraph.java:436)
_SwitchableSemanticsFragment.compileChildren (_SwitchableSemanticsFragment.java:3717)
_SwitchableSemanticsFragment.compileChildren (_SwitchableSemanticsFragment.java:3709)
RenderObject._updateSemantics (RenderObject.java:2631)
PipelineOwner.flushSemantics (PipelineOwner.java:1081)
RendererBinding.drawFrame (RendererBinding.java:441)
WidgetsBinding.drawFrame (WidgetsBinding.java:914)
RendererBinding._handlePersistentFrameCallback (RendererBinding.java:302)
SchedulerBinding._invokeFrameCallback (SchedulerBinding.java:1117)
SchedulerBinding.handleDrawFrame (SchedulerBinding.java:1055)
SchedulerBinding._handleDrawFrame (SchedulerBinding.java:971)
```

On HUAWEI Y9 Prime 2019, Pixel 2

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-BY)
    • Flutter version 1.22.3 at /Users/nikitadold/development/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nikitadold/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/nikitadold/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Users/nikitadold/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/nikitadold/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 202.8070
```

</details>

**Comment by pedromassangocode** [comment] 2020-11-17 10:45
Hi @nikitadol 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
Is there any additional log you can provide?
 Do you have any minimal complete reproducible code sample that may reproduce this issue?
Thank you

**Comment by nikitadol** [comment] 2020-11-17 11:49
Hi @pedromassangocode 
I would really like to provide at least something, but I do not have such a phone
And I don't quite understand the error conditions

**Comment by pedromassangocode** [comment] 2020-11-18 06:24
Hi @nikitadol
Please provide your `flutter doctor -v`?

**Comment by nikitadol** [comment] 2020-11-18 07:07
Hi @pedromassangocode 

```console
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-BY)
    • Flutter version 1.22.3 at /Users/nikitadold/development/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nikitadold/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/nikitadold/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Users/nikitadold/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/nikitadold/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

```

**Comment by pedromassangocode** [comment] 2020-11-18 14:13
Those logs are similar to https://github.com/FirebaseExtended/flutterfire/issues/3907#issuecomment-717187957.

Hi @nikitadol 
I'm not sure if this issue as something to do with Flutter since this may be cause by your code.
Will leave this opened for further investigation.

**Comment by nikitadol** [comment] 2020-11-18 14:15
> Those logs are similar to FirebaseExtended/flutterfire#3907 (comment).

Hi @pedromassangocode 

In your link, you can see that the crash occurs in code that is not inside Flutter
I have a slightly different case

**Comment by goderbauer** [comment] 2020-11-18 22:54
/cc @chunhtai I think you fixed this crash recently?

@nikitadol Can you check whether this is still happening on master?

**Comment by chunhtai** [comment] 2020-11-19 01:14
yes this should be fixed

**Comment by nikitadol** [comment] 2020-11-19 06:43
@goderbauer 
I will be able to check only when it is in stable

When will this happen?

**Comment by pedromassangocode** [comment] 2020-11-19 07:47
Hi @nikitadol 
You can see the Flutter release process at https://github.com/flutter/flutter/wiki/Release-process.

**Comment by nikitadol** [comment] 2020-11-19 08:02
@pedromassangocode 
Thanks

Anyway, I look forward to updating Flutter in stable
Otherwise I can not check

**Comment by goderbauer** [comment] 2020-11-20 23:38
Since there's nothing for us to do, I am going to close this. Feel free to re-open if the issue persists once the change hit stable.

**Closed by goderbauer** 2020-11-20 23:38 UTC
Labels: framework, passed first triage, severe: crash

**Comment by dheeraj2dj** [comment] 2020-12-07 19:27
Am on stable flutter, and I have the same issue

<summary>
`flutter doctor -v`
<description>
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-IN)
    • Flutter version 1.22.4 at /Users/dheeraj2dj/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dheeraj2dj/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</description>
</summary>

**Comment by chunhtai** [comment] 2020-12-07 20:49
@dheeraj2dj  do you have a repro to reproduce the crash?

**Comment by pph7** [comment] 2021-02-18 10:50
> Hi @nikitadol
> You can see the Flutter release process at https://github.com/flutter/flutter/wiki/Release-process.

Unortunately this document does not exist any more. Can we learn about the process anywhere else?

**Comment by ammaratef45** [comment] 2021-07-12 16:59
I'm using flutter `2.0.4` and I got similar error (logs below)
Should I open a new issue for that?

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: RangeError (index): Invalid value: Valid value range is empty: 1. Error thrown Instance of 'ErrorDescription'.
       at _GrowableList.[](_GrowableList.java)
       at _PrePairingDialogState.<fn>(_PrePairingDialogState.java:62)
       at _InkResponseState._handleTap(_InkResponseState.java:991)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:182)
       at TapGestureRecognizer.handleTapUp(TapGestureRecognizer.java:607)
       at BaseTapGestureRecognizer._checkUp(BaseTapGestureRecognizer.java:296)
       at BaseTapGestureRecognizer.handlePrimaryPointer(BaseTapGestureRecognizer.java:230)
       at PrimaryPointerGestureRecognizer.handleEvent(PrimaryPointerGestureRecognizer.java:475)
       at PointerRouter._dispatch(PointerRouter.java:93)
       at PointerRouter.<fn>(PointerRouter.java:138)
       at _LinkedHashMapMixin.forEach(_LinkedHashMapMixin.java)
       at PointerRouter._dispatchEventToRoutes(PointerRouter.java:136)
       at PointerRouter.route(PointerRouter.java:122)
       at GestureBinding.handleEvent(GestureBinding.java:381)
       at GestureBinding.dispatchEvent(GestureBinding.java:361)
       at RendererBinding.dispatchEvent(RendererBinding.java:278)
       at GestureBinding._handlePointerEventImmediately(GestureBinding.java:316)
       at GestureBinding.handlePointerEvent(GestureBinding.java:280)
       at GestureBinding._flushPointerEventQueue(GestureBinding.java:238)
       at GestureBinding._handlePointerDataPacket(GestureBinding.java:221)
```
