### ISSUE TITLE
BorderRadius.circular should be a const constructor

### ISSUE THREAD

**Issue by sma** [flutter/flutter#99263] opened 2022-02-28 07:21 UTC
As of Flutter 2.11, the `BorderRadius.circular` constructor isn't `const` but I think, it could be. Other constructors are.

This would allow something like this:

```
const FluentContextMenu({Key? key, required this.items, this.borderRadius = const BorderRadius.circular(8)}) : super(key: key);
```

As a workaround, I have to do this:

```
const FluentContextMenu({Key? key, required this.items, this.borderRadius = const BorderRadius.all(Radius.circular(8))}) : super(key: key);
```

**Comment by darshankawar** [comment] 2022-02-28 11:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98575.
Please see https://github.com/flutter/flutter/issues/98575#issuecomment-1041488980 for more details and further reference.

**Closed by darshankawar** 2022-02-28 11:48 UTC
Labels: in triage
