### ISSUE TITLE
TextField cursor goes to beginning each time after edit

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#52773] opened 2020-03-17 23:13 UTC
**issue:** cursor writes at the beginning of text. Also can't put mouse cursor in any other place but the first line, have to use keyboard to move the cursor in the proper position in body of textfield.

**code:**
```dart
import 'package:ampstor/data/blocs/blocs.dart';
import 'package:ampstor/ui/common/index.dart';
import 'package:ampstor/sdk/ampstor_sdk.dart';
import 'package:ampstor/generated/i18n.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';

class TextSrcTextField extends StatefulWidget {
  const TextSrcTextField({
    Key key,
    @required this.text,
  }) : super(key: key);

  final TextElement text;

  @override
  _TextSrcTextFieldState createState() => _TextSrcTextFieldState();
}

class _TextSrcTextFieldState extends State<TextSrcTextField> {
  TextElement text;

  final _contoller = TextEditingController();
  final _link = TextEditingController();

  @override
  void didUpdateWidget(TextSrcTextField oldWidget) {
    if (oldWidget.text.elementId != widget.text.elementId) {
      _init();
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  void initState() {
    _init();
    super.initState();
  }

  void _init() {
    text = widget.text;
    _contoller.text = text.src;
    _link.text = text?.link ?? '';
  }

  final delay = Debouncer();

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: <Widget>[
          Container(
            margin: EdgeInsets.only(bottom: 10),
            padding: EdgeInsets.only(left: 10),
            decoration: BoxDecoration(
              //color: Colors.white,
              borderRadius: BorderRadius.all(Radius.circular(4.0)),
              border: Border.all(
                  // color: Colors.grey,
                  width: 0.2,
                  color: Colors.grey[500]),
            ),
            child: TextField(
              style: TextStyle(fontSize: 13),
              controller: _contoller,
              maxLines: null,
              keyboardType: TextInputType.multiline,
              decoration: InputDecoration(
                  enabledBorder: UnderlineInputBorder(
                    borderSide: BorderSide(color: Colors.transparent),
                  ),
                  focusedBorder: UnderlineInputBorder(
                    borderSide: BorderSide(color: Colors.transparent),
                  ),
                  //contentPadding: EdgeInsets.only(bottom: 13),
                  hintStyle: TextStyle(
                    fontSize: 9,
                  ),
                  hintText: I18n.of(context).editorTextSource),
              onChanged: (val) => delay.run(() => _editSrc(context)),
              onEditingComplete: () => _editSrc(context),
            ),
          ),
          Tooltip(
            message: 'Please include http://',
            textStyle: TextStyle(fontSize: 9, color: Colors.white),
            child: Container(
              height: 30,
              padding: EdgeInsets.only(left: 10),
              decoration: BoxDecoration(
                //color: Colors.white,
                borderRadius: BorderRadius.all(Radius.circular(4.0)),
                border: Border.all(
                    // color: Colors.grey,
                    width: 0.2,
                    color: Colors.grey[500]),
              ),
              child: TextField(
                style: TextStyle(fontSize: 13),
                controller: _link,
                decoration: InputDecoration(
                  isDense: true,
                    enabledBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                    focusedBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                    //contentPadding: EdgeInsets.only(bottom: 13),
                    hintStyle: TextStyle(
                      fontSize: 13,
                    ),
                    hintText: I18n.of(context).editorCta_link),
                onChanged: (val) => delay.run(() => _editLink(context)),
                onEditingComplete: () => _editLink(context),
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _editSrc(BuildContext context) {
    final db = GetIt.instance.get<DatabaseService>();
    final currentValue = widget.text.src;
    final newValue = _contoller.text;
    BlocProvider.of<EditorBloc>(context).add(TrackChange(
      action: () {
        db.storyDao.editText(widget.text.copyWith(src: newValue));
        if (_contoller.text != newValue) _contoller.text = newValue;
      },
      undo: () {
        db.storyDao.editText(widget.text.copyWith(src: currentValue));
        if (_contoller.text != currentValue) _contoller.text = currentValue;
      },
    ));
  }

  void _editLink(BuildContext context) {
    final db = GetIt.instance.get<DatabaseService>();
    final currentValue = widget.text.link;
    final newValue = _link.text;
    BlocProvider.of<EditorBloc>(context).add(TrackChange(
      action: () {
        db.storyDao.editText(widget.text.copyWith(link: newValue));
        if (_link.text != newValue) _link.text = newValue;
      },
      undo: () {
        db.storyDao.editText(widget.text.copyWith(link: currentValue));
        if (_link.text != currentValue) _link.text = currentValue;
      },
    ));
  }
}
```

**Comment by mariamhas** [comment] 2020-03-17 23:15
cc @nturgut

**Comment by nturgut** [comment] 2020-03-18 00:00
Thanks for filing the issue. A few questions:

1) Which flutter channel are you using, can you share the flutter doctor -v output?
2) Which browser are you using?
3) I assume this error didn't happen on the Flutter Mobile Apps but only on Flutter Web? Is it correct?

**Comment by marince00** [comment] 2020-03-19 13:44
[✓] Flutter (Channel master, v1.15.20, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.15.20 at /users/marinatrajkovska/flutter
    • Framework revision 4049889d9e (8 days ago), 2020-03-10 20:05:41 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marinatrajkovska/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

The issue happens only on **Flutter Web**. 
**Browser**: Chrome

**Comment by nturgut** [comment] 2020-03-30 22:40
Thanks for the information provided. In the latest master I tried the text field provided in the code jointly with our material text demo (I only used some part of the code you provided.) I was able to use the mouse as intended and cursor was also in the right place every-time, I didn't observed any problems. The code:

```
// Copyright 2019 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

import 'package:flutter/services.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;

import 'package:gallery/l10n/gallery_localizations.dart';

// BEGIN textFieldDemo

class TextFieldDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: Text(GalleryLocalizations.of(context).demoTextFieldTitle),
      ),
      body: TextFormFieldDemo(),
    );
  }
}

class TextFormFieldDemo extends StatefulWidget {
  const TextFormFieldDemo({Key key}) : super(key: key);

  @override
  TextFormFieldDemoState createState() => TextFormFieldDemoState();
}

class PersonData {
  String name = '';
  String phoneNumber = '';
  String email = '';
  String password = '';
}

class PasswordField extends StatefulWidget {
  const PasswordField({
    this.fieldKey,
    this.hintText,
    this.labelText,
    this.helperText,
    this.onSaved,
    this.validator,
    this.onFieldSubmitted,
  });

  final Key fieldKey;
  final String hintText;
  final String labelText;
  final String helperText;
  final FormFieldSetter<String> onSaved;
  final FormFieldValidator<String> validator;
  final ValueChanged<String> onFieldSubmitted;

  @override
  _PasswordFieldState createState() => _PasswordFieldState();
}

class _PasswordFieldState extends State<PasswordField> {
  bool _obscureText = true;

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      key: widget.fieldKey,
      obscureText: _obscureText,
      cursorColor: Theme.of(context).cursorColor,
      maxLength: 8,
      onSaved: widget.onSaved,
      validator: widget.validator,
      onFieldSubmitted: widget.onFieldSubmitted,
      decoration: InputDecoration(
        filled: true,
        hintText: widget.hintText,
        labelText: widget.labelText,
        helperText: widget.helperText,
        suffixIcon: GestureDetector(
          dragStartBehavior: DragStartBehavior.down,
          onTap: () {
            setState(() {
              _obscureText = !_obscureText;
            });
          },
          child: Icon(
            _obscureText ? Icons.visibility : Icons.visibility_off,
            semanticLabel: _obscureText
                ? GalleryLocalizations.of(context)
                    .demoTextFieldShowPasswordLabel
                : GalleryLocalizations.of(context)
                    .demoTextFieldHidePasswordLabel,
          ),
        ),
      ),
    );
  }
}

class TextFormFieldDemoState extends State<TextFormFieldDemo> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  PersonData person = PersonData();

  void showInSnackBar(String value) {
    _scaffoldKey.currentState.hideCurrentSnackBar();
    _scaffoldKey.currentState.showSnackBar(SnackBar(
      content: Text(value),
    ));
  }

  bool _autoValidate = false;

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final GlobalKey<FormFieldState<String>> _passwordFieldKey =
      GlobalKey<FormFieldState<String>>();
  final _UsNumberTextInputFormatter _phoneNumberFormatter =
      _UsNumberTextInputFormatter();

  void _handleSubmitted() {
    final form = _formKey.currentState;
    if (!form.validate()) {
      _autoValidate = true; // Start validating on every change.
      showInSnackBar(
        GalleryLocalizations.of(context).demoTextFieldFormErrors,
      );
    } else {
      form.save();
      showInSnackBar(GalleryLocalizations.of(context)
          .demoTextFieldNameHasPhoneNumber(person.name, person.phoneNumber));
    }
  }

  String _validateName(String value) {
    if (value.isEmpty) {
      return GalleryLocalizations.of(context).demoTextFieldNameRequired;
    }
    final nameExp = RegExp(r'^[A-Za-z ]+$');
    if (!nameExp.hasMatch(value)) {
      return GalleryLocalizations.of(context)
          .demoTextFieldOnlyAlphabeticalChars;
    }
    return null;
  }

  String _validatePhoneNumber(String value) {
    final phoneExp = RegExp(r'^\(\d\d\d\) \d\d\d\-\d\d\d\d$');
    if (!phoneExp.hasMatch(value)) {
      return GalleryLocalizations.of(context).demoTextFieldEnterUSPhoneNumber;
    }
    return null;
  }

  String _validatePassword(String value) {
    final passwordField = _passwordFieldKey.currentState;
    if (passwordField.value == null || passwordField.value.isEmpty) {
      return GalleryLocalizations.of(context).demoTextFieldEnterPassword;
    }
    if (passwordField.value != value) {
      return GalleryLocalizations.of(context).demoTextFieldPasswordsDoNotMatch;
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final cursorColor = Theme.of(context).cursorColor;
    const sizedBoxSpace = SizedBox(height: 24);
    final _contoller = TextEditingController();

    void _editSrc(BuildContext context) {
      print('edit is called');
    }

    return Scaffold(
      key: _scaffoldKey,
      body: Form(
        key: _formKey,
        autovalidate: _autoValidate,
        child: Scrollbar(
          child: SingleChildScrollView(
            dragStartBehavior: DragStartBehavior.down,
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                sizedBoxSpace,
                TextField(
                  style: TextStyle(fontSize: 13),
                  controller: _contoller,
                  maxLines: null,
                  keyboardType: TextInputType.multiline,
                  decoration: InputDecoration(
                    enabledBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                    focusedBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                    //contentPadding: EdgeInsets.only(bottom: 13),
                    hintStyle: TextStyle(
                      fontSize: 9,
                    ),
                    hintText: 'some hint text',
                  ),
                  onChanged: (val) => _editSrc(context),
                  onEditingComplete: () => _editSrc(context),
                ),
                sizedBoxSpace,
                TextFormField(
                  cursorColor: cursorColor,
                  decoration: InputDecoration(
                    filled: true,
                    icon: Icon(Icons.phone),
                    hintText: GalleryLocalizations.of(context)
                        .demoTextFieldWhereCanWeReachYou,
                    labelText: GalleryLocalizations.of(context)
                        .demoTextFieldPhoneNumber,
                    prefixText: '+1 ',
                  ),
                  keyboardType: TextInputType.phone,
                  onSaved: (value) {
                    person.phoneNumber = value;
                  },
                  maxLength: 14,
                  maxLengthEnforced: false,
                  validator: _validatePhoneNumber,
                  // TextInputFormatters are applied in sequence.
                  inputFormatters: <TextInputFormatter>[
                    WhitelistingTextInputFormatter.digitsOnly,
                    // Fit the validating format.
                    _phoneNumberFormatter,
                  ],
                ),
                sizedBoxSpace,
                TextFormField(
                  cursorColor: cursorColor,
                  decoration: InputDecoration(
                    filled: true,
                    icon: Icon(Icons.email),
                    hintText: GalleryLocalizations.of(context)
                        .demoTextFieldYourEmailAddress,
                    labelText:
                        GalleryLocalizations.of(context).demoTextFieldEmail,
                  ),
                  keyboardType: TextInputType.emailAddress,
                  onSaved: (value) {
                    person.email = value;
                  },
                ),
                sizedBoxSpace,
                TextFormField(
                  cursorColor: cursorColor,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: GalleryLocalizations.of(context)
                        .demoTextFieldTellUsAboutYourself,
                    helperText: GalleryLocalizations.of(context)
                        .demoTextFieldKeepItShort,
                    labelText:
                        GalleryLocalizations.of(context).demoTextFieldLifeStory,
                  ),
                  maxLines: 3,
                ),
                sizedBoxSpace,
                TextFormField(
                  cursorColor: cursorColor,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    labelText:
                        GalleryLocalizations.of(context).demoTextFieldSalary,
                    suffixText:
                        GalleryLocalizations.of(context).demoTextFieldUSD,
                  ),
                  maxLines: 1,
                ),
                sizedBoxSpace,
                PasswordField(
                  fieldKey: _passwordFieldKey,
                  helperText:
                      GalleryLocalizations.of(context).demoTextFieldNoMoreThan,
                  labelText:
                      GalleryLocalizations.of(context).demoTextFieldPassword,
                  onFieldSubmitted: (value) {
                    setState(() {
                      person.password = value;
                    });
                  },
                ),
                sizedBoxSpace,
                TextFormField(
                  cursorColor: cursorColor,
                  decoration: InputDecoration(
                    filled: true,
                    labelText: GalleryLocalizations.of(context)
                        .demoTextFieldRetypePassword,
                  ),
                  maxLength: 8,
                  obscureText: true,
                  validator: _validatePassword,
                ),
                sizedBoxSpace,
                Center(
                  child: RaisedButton(
                    child: Text(
                        GalleryLocalizations.of(context).demoTextFieldSubmit),
                    onPressed: _handleSubmitted,
                  ),
                ),
                sizedBoxSpace,
                Text(
                  GalleryLocalizations.of(context).demoTextFieldRequiredField,
                  style: Theme.of(context).textTheme.caption,
                ),
                sizedBoxSpace,
              ],
            ),
          ),
        ),
      ),
    );
  }
}

/// Format incoming numeric text to fit the format of (###) ###-#### ##
class _UsNumberTextInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final newTextLength = newValue.text.length;
    final newText = StringBuffer();
    int selectionIndex = newValue.selection.end;
    int usedSubstringIndex = 0;
    if (newTextLength >= 1) {
      newText.write('(');
      if (newValue.selection.end >= 1) selectionIndex++;
    }
    if (newTextLength >= 4) {
      newText.write(newValue.text.substring(0, usedSubstringIndex = 3) + ') ');
      if (newValue.selection.end >= 3) selectionIndex += 2;
    }
    if (newTextLength >= 7) {
      newText.write(newValue.text.substring(3, usedSubstringIndex = 6) + '-');
      if (newValue.selection.end >= 6) selectionIndex++;
    }
    if (newTextLength >= 11) {
      newText.write(newValue.text.substring(6, usedSubstringIndex = 10) + ' ');
      if (newValue.selection.end >= 10) selectionIndex++;
    }
    // Dump the rest.
    if (newTextLength >= usedSubstringIndex) {
      newText.write(newValue.text.substring(usedSubstringIndex));
    }
    return TextEditingValue(
      text: newText.toString(),
      selection: TextSelection.collapsed(offset: selectionIndex),
    );
  }
}

// END

```

I assume, rather than the flutter web engine, the issue is in the application.

I am closing the issue please reopen it if you can generate in [flutter_gallery](https://github.com/flutter/gallery) text editing demo.

**Closed by nturgut** 2020-03-30 22:40 UTC
Labels: a: text input, f: material design, framework, waiting for customer response, ☸ platform-web
