### ISSUE TITLE
Project cannot run.error is resource fork, Finder information, or similar detritus not allowed     Command /usr/bin/codesign failed with exit code 1

### ISSUE THREAD

**Issue by ZAREMYDREAM** [flutter/flutter#37461] opened 2019-08-02 06:47 UTC
我这边创建一个新的项目可以正常运行，但是当我连了真机或者同时开着安卓和iOS模拟器的时候，重启as和模拟器，再在iOS真机或者模拟器运行项目就会出现这样的问题（安卓可以正常运行）

I am creating a new project here to run normally, but when I connect to the real machine or open the Android and iOS simulator at the same time, restart the as and emulator, and then run the project on the iOS real machine or emulator. Such a problem (Android can run normally)
![F43598679BCFC6310A729F381109784C](https://user-images.githubusercontent.com/23189248/62350184-7eb18200-b534-11e9-8157-1b852f727cd2.png)

**Comment by BondarenkoStas** [comment] 2019-09-19 14:55
Duplicate of #26123, so closing it. If you disagree, please feel free to comment and I will re-open it.

**Closed by BondarenkoStas** 2019-09-19 14:55 UTC
