### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by shahdmahmmoud** [flutter/flutter#157459] opened 2024-10-23 18:46 UTC
## Command
```sh
flutter --no-color attach --machine --device-id=emulator-5554 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```console
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:357:17)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-GB)
    • Flutter version 3.24.3 on channel stable at C:\RAHALA\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\hpenv\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35303.130
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2024.1.4
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.2)
    • VS Code at C:\Users\hpenv\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • sdk gphone16k x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)             • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)                  • chrome        • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)                    • edge          • web-javascript • Microsoft Edge 130.0.2849.46

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0850beeb25f6d5b10426284f506557f66181b36
### Plugins
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
firebase_auth-5.3.1
firebase_auth_web-5.13.2
firebase_core-3.6.0
firebase_core_web-2.18.1
flutter_plugin_android_lifecycle-2.0.23
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.10
google_maps_flutter_ios-2.13.1
google_maps_flutter_web-0.5.10
google_sign_in-6.2.1
google_sign_in_android-6.1.33
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+2

**Comment by danagbemava-nc** [comment] 2024-10-24 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by danagbemava-nc** 2024-10-24 07:02 UTC
Labels: in triage
