### ISSUE TITLE
Target kernel_snapshot failed: Exception: The value of -DDartDefines is not formatted correctly. The value must be a JSON-encoded list of strings but was: [flutter.inspector.structuredErrors=true] build failed.

### ISSUE THREAD

**Issue by beingbsal** [flutter/flutter#60423] opened 2020-06-27 13:05 UTC
Target kernel_snapshot failed: Exception: The value of -DDartDefines is not formatted correctly.
The value must be a JSON-encoded list of strings but was:
[flutter.inspector.structuredErrors=true]
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by radeklat** [comment] 2020-06-27 16:28
Not sure if this applies given the lack of context, but I hit the same issue just now and fixed it by switching to the latest stable version of flutter (`flutter channel stable; flutter upgrade`). I was using `1.16.3` and today the Flutter plugin in AndroidStudio has been updated and a vaguely remember seeing "17" in the version number. Which made me think it will require also Flutter of version `1.17.x`. After the upgrade to latest stable (`1.17.4` at the time of writing), the problem has disappeared.

**Comment by TahaTesser** [comment] 2020-06-29 12:08
Hi @radeklat 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by radeklat** [comment] 2020-07-01 16:39
Hi @TahaTesser. Unfortunately I can't because I no longer observe this issue. Additionally, it was not a code issue as I did not change anything. I only observed a Flutter plugin update and then the reported issue. Maybe @beingbsal can be of more help.

**Comment by PranayNizampuram** [comment] 2020-07-07 05:15
I was facing the same issue. @radeklat 's suggestion fixed it - https://github.com/flutter/flutter/issues/60423#issuecomment-650582670

I am no longer able to reproduce it.

**Comment by TahaTesser** [comment] 2020-07-22 15:26
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-22 15:26 UTC
Labels: in triage
