### ISSUE TITLE
[Web] Scroll doesn't work when dragging `SelectableText` widget

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#83492] opened 2021-05-27 15:45 UTC
## Steps to Reproduce

Modify the `main.dart` return statement to the following:
```dart
Scaffold(
  body: Scrollbar(
  child: SingleChildScollView(
  child: Column(
  column: <Widget>[
  SelectableText('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore  
  magna aliqua. Mattis molestie a iaculis at erat. Mi bibendum neque egestas congue quisque egestas. Elit ut aliquam purus sit 
  amet luctus venenatis lectus. Tortor at auctor urna nunc. Arcu odio ut sem nulla pharetra diam sit. Volutpat commodo sed 
  egestas egestas fringilla phasellus faucibus. Enim lobortis scelerisque fermentum dui. Egestas quis ipsum suspendisse ultrices 
  gravida dictum fusce ut placerat. Facilisi cras fermentum odio eu feugiat pretium. Sit amet nisl suscipit adipiscing bibendum 
  est ultricies.'),
  SizedBox(height: 30),
  SelectableText('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore  
  magna aliqua. Mattis molestie a iaculis at erat. Mi bibendum neque egestas congue quisque egestas. Elit ut aliquam purus sit 
  amet luctus venenatis lectus. Tortor at auctor urna nunc. Arcu odio ut sem nulla pharetra diam sit. Volutpat commodo sed 
  egestas egestas fringilla phasellus faucibus. Enim lobortis scelerisque fermentum dui. Egestas quis ipsum suspendisse ultrices 
  gravida dictum fusce ut placerat. Facilisi cras fermentum odio eu feugiat pretium. Sit amet nisl suscipit adipiscing bibendum 
  est ultricies.'),
  SizedBox(height: 30),
  SelectableText('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore  
  magna aliqua. Mattis molestie a iaculis at erat. Mi bibendum neque egestas congue quisque egestas. Elit ut aliquam purus sit 
  amet luctus venenatis lectus. Tortor at auctor urna nunc. Arcu odio ut sem nulla pharetra diam sit. Volutpat commodo sed 
  egestas egestas fringilla phasellus faucibus. Enim lobortis scelerisque fermentum dui. Egestas quis ipsum suspendisse ultrices 
  gravida dictum fusce ut placerat. Facilisi cras fermentum odio eu feugiat pretium. Sit amet nisl suscipit adipiscing bibendum 
  est ultricies.'),
      ],  
    ),  
  ), 
 ),
);
```

**Expected results:**
For the scroll to work where the dragging activity is happening.

**Actual results:**
Scroll doesn't work when scrolling within the boundaries of the `SelectableText` widget. 

<details>
  <summary>Logs</summary>

My `flutter doctor -v` output
```
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ziyad\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\ziyad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.66

! Doctor found issues in 1 category.
```
</details>

**Comment by ZiyadF296** [comment] 2021-05-27 15:46
Also please note that I am talking about the web here and you should run it on the web.

**Comment by TahaTesser** [comment] 2021-05-28 09:07
Hi @ZiyadF296 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/78024
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-28 09:07 UTC
Labels: in triage
