### ISSUE TITLE
[web] Keyboard does not show up with TextField on iOS

### ISSUE THREAD

**Issue by aloisdeniel** [flutter/flutter#32763] opened 2019-05-15 15:03 UTC
## Steps to Reproduce

1. Put a `TextField` in a `flutter_web` project
2. Build and serve with `webdev serve` (make sure your firewall is open for the served address).
3. Open the resulting website from an iOS device or simulator (Chrome or Safari).
4. Tap on the field
5. No keyboard is displayed to the user

## Sample

[issue_sample.zip](https://github.com/flutter/flutter/files/3183151/issue_sample.zip)

```dart
import 'package:flutter_web/material.dart';

void main() {
  runApp(IssueApp());
}

class IssueApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: MaterialApp(
      theme: ThemeData(
        platform: TargetPlatform.android,
      ),
      title: 'Issue',
      home: Page(),
    ));
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField();
  }
}
```

**Comment by aloisdeniel** [comment] 2019-05-15 15:37
By changing the values from the hidden `input` tag from `flutter_web_ui/lib/src/engine/text_editing.dart`, the keyboard seems more reactive, but I didn't find a combination that makes the tag invisible to the user while working.

## Example tweak

`flutter_web_ui/lib/src/engine/text_editing.dart`

```dart
void _styleEditingElement(html.HtmlElement domElement) {
  domElement.style
    ..position = 'fixed'
    ..whiteSpace = 'pre';
  if (_debugVisibleTextEditing) {
    domElement.style
      ..bottom = '0'
      ..right = '0'
      ..font = '24px sans-serif'
      ..color = 'purple'
      ..backgroundColor = 'pink';
  } else {
    domElement.style
      //..overflow = 'hidden'
      //..transform = 'translate(0px, -100px)'
      // width and height can't be zero because then the element would stop
      // receiving edits when its content is empty.
      ..width = '100px'
      ..height = '100px';
  }
  if (browserEngine == BrowserEngine.webkit) {
    // TODO(flutter_web): Remove once webkit issue of paragraphs incorrectly
    // rendering (shifting up) is resolved. Temporarily force relayout
    // a frame after input is created.
    html.window.animationFrame.then((num _) {
      domElement.style
        ..position = 'absolute'
        ..top = '0'
        ..right = '0';
    });
  }
}
```

**Comment by wasiliysoft** [comment] 2019-05-30 07:39
confirm the problem on the physical iphone 5s iOS 12.3

**Comment by AppleEducate** [comment] 2019-06-19 18:30
Happening on iPhone X iOS 12

**Comment by AppleEducate** [comment] 2019-06-19 19:01
Here is an example on the login screen: https://appleeducate.github.io/tasks_clone/#/

**Comment by AppleEducate** [comment] 2019-06-19 19:12
If you long press and try to paste and then tap on the text field some times you can get the keyboard to come up and accept input.

**Comment by alesms** [comment] 2019-07-03 16:55
hi, could you have news about the issue?
I saw that @yjbanov move to the near-term goal but today it still present.

**Comment by yjbanov** [comment] 2019-07-16 03:54
The update is that text editing is undergoing a little redesign. We're actually trying something along the lines of what @aloisdeniel is suggesting. @nturgut might have more details on this.

**Comment by dbacinski** [comment] 2019-07-17 21:27
We are betting on Flutter Web and the issues with iOS inputs makes us really worry. Almost no website can work without reliable inputs. We can deal with repackaging and lack of plugins. But lack of properly working inputs on iOS is a deal-breaker. I hope we will have visible progress here.

**Comment by nturgut** [comment] 2019-07-17 22:25
Yes, proper working input is definitely a must. As @yjbanov mentioned we are undergoing a redesign which will also enable clipboard.

**Comment by sgon00** [comment] 2019-07-31 12:21
Hi, sorry to interrupt. Any nicer workaround than @aloisdeniel 's tweak? I have waited some time before posting this comment. This is the only bug stopping our web app to publish. Thanks a lot.

**Comment by AppleEducate** [comment] 2019-07-31 14:11
This also happens on the iPad Pro. Any version of mobile safari

**Comment by nturgut** [comment] 2019-08-02 20:05
We are working on a rewrite for text editing now. Meanwhile, as a temporary solution, can you try to enable autofocus on the TextFormField?

**Comment by AppleEducate** [comment] 2019-08-02 22:21
Sure thing! I’ll see what I can do

**Comment by yxj1988821** [comment] 2019-08-05 07:49
I have this problem too, what can I do, how to fix it

**Comment by gamegrd** [comment] 2019-08-07 05:00
I have this problem toooooooooooo

**Comment by creomobile** [comment] 2019-08-07 21:51
We started to build web app on flutter_web, but this issue doesn't allow us to try it in production with real users. I tried to fix it, but ios safary policy doesn't allow to set the focus even in flutter_web entry point for events: flutter_web_ui ... src/engine/pointer_binging.dart _addEventListener. It seems that it should be fixed in dart_html.
Do you have any estimates for it please?

**Comment by AppleEducate** [comment] 2019-08-07 23:44
I’m working on a html text field wrapper for Flutter web. But would love this issue fixed soon.

**Comment by OlehMarchenko95** [comment] 2019-08-08 08:52
Hi guys, Fixed this issue.
This is [url for pull request](https://github.com/flutter/flutter_web/pull/122/commits)
Or on my [fork of flutter web](https://github.com/OlehMarchenko95/flutter_web)

Please check it for yourself.

**Comment by sgon00** [comment] 2019-08-20 19:00
@OlehMarchenko95 thank you very much for the pull request. I am currently using the flutter mainline for web dev since flutter_web is now merged into flutter master. Because your PR merge is blocked, do you know how I can try it in the flutter master web version? Thanks a lot.

**Comment by nturgut** [comment] 2019-08-20 19:23
Thanks @OlehMarchenko95 for your contribution!

Just heads up, we are sending out the PRs for enhanced text editing this week. Clipboard will also be available after these PRs are in.

**Closed** 2019-08-23 00:35 UTC
Labels: a: text input, ☸ platform-web

**Comment by oshochawla17** [comment] 2020-08-20 20:52
I am still facing this issue in chrome/ safari on ios

**Comment by sanekyy** [comment] 2020-11-18 21:02
Same issue on web iOS ( master channel )

**Comment by nturgut** [comment] 2020-11-18 22:30
@sanekyy this issue is resolved a while back. I think the root cause will be different for the current problem you are experiencing. Can you create a new issue? Can you also add flutter doctor logs and also the device and safari versions that you are testing on?

Thanks for commenting on the issue.

**Comment by voodoo420** [comment] 2020-12-09 13:02
The keyboard is not displayed on iOs < 13 if autofocus is enabled

**Comment by rmill777** [comment] 2020-12-31 06:45
I have this issue as well
