### ISSUE TITLE
[tool_crash] _CastError: (#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39))

### ISSUE THREAD

**Issue by ket3613** [flutter/flutter#119885] opened 2023-02-03 02:33 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39))
```
#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale ko-KR)
    • Flutter version 3.7.1 on channel stable at C:\tools\flutter
    ! The flutter binary is not on your path. Consider adding C:\tools\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\tools\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (33 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\ket36\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Users\ket36\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443
    • Flutter plugin version 72.0.2
    • Dart plugin version 221.6096
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\ket36\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 109.0.1518.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 5 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
path_provider_linux-2.1.7
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2

**Comment by ket3613** [comment] 2023-02-03 02:37
한글 입력시 오류 재기동후 정상확인

**Comment by danagbemava-nc** [comment] 2023-02-03 07:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/119084.

**Closed by danagbemava-nc** 2023-02-03 07:25 UTC
Labels: in triage
