### ISSUE TITLE
CameraPreview freeze when resume to app after open another camera app.

### ISSUE THREAD

**Issue by ltvu93** [flutter/flutter#34786] opened 2019-06-20 10:49 UTC
## Steps to Reproduce
1. Run app in [this tutorial](https://flutter.dev/docs/cookbook/plugins/picture-using-camera).
2. Go to home screen.
3. Open another camera app.
4.  Go back to my camera app.

[![Video](https://img.youtube.com/vi/RJAypWNqsvY/0.jpg)](https://www.youtube.com/watch?v=RJAypWNqsvY)

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.7.5-pre.21, on Microsoft Windows [Version 10.0.17763.557], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Does anyone know how to fix it?

**Comment by BondarenkoStas** [comment] 2019-10-04 11:14
@ltvu93 is it the same while using current flutter stable and camera 0.5.5+1? What the device did you use to test?

**Comment by iapicca** [comment] 2019-11-08 14:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 14:56 UTC
Labels: p: camera, plugin, waiting for customer response

**Comment by frencojobs** [comment] 2020-08-26 06:13
This error seems to be occurring on a Huawei Y9 device. The camera plugin version is `^0.5.8+5`. Do everything as in the tutorial, open another camera app and the camera preview is froze when I go back into the app. 

Here is a detailed flutter doctor result:
```
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.1 at /home/frenco/snap/flutter/common/flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/frenco/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/frenco/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/frenco/Documents/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • JKM LX2 (mobile) • - • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by maikeriva** [comment] 2021-06-21 21:06
Same thing is happening on my setup.

**Steps to reproduce**
- Build and test app from code below
- Camera works
- Switch to another application which uses the camera (default camera app is fine)
- Get back to app
- Error occurs

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.4 at /home/micheleriva/snap/flutter/common/flutter
    • Framework revision b1395592de (3 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/micheleriva/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • ONEPLUS A6003 (mobile) • 51568b47 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
**Code**
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:native_device_orientation/native_device_orientation.dart'; // Used to fix the camera rotation which is out of sync with OS rotation

List<CameraDescription> cameras = [];

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Necessary for camera plugin
  cameras = await availableCameras();
  runApp(TestApp());
}

class TestApp extends StatelessWidget {
  static const String _title = 'Test';
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: TestHome(),
    );
  }
}

class TestHome extends StatefulWidget {
  const TestHome({Key? key}) : super(key: key);

  @override
  State<TestHome> createState() => _TestHomeState();
}

class _TestHomeState extends State<TestHome> {
  CameraController? controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras[0], ResolutionPreset.max);
    controller!.initialize().then((_) {
      // Lock camera orientation, we'll use a resizedbox to rotate it
      controller!
          .lockCaptureOrientation(DeviceOrientation.portraitUp)
          .then((_) {
        controller!.addListener(() {
          if (mounted) setState(() {});
          // if (controller!.value.hasError) {
          //   showInSnackBar(
          //       'Camera error ${cameraController.value.errorDescription}');
          // }
        });
        // If the controller is updated then update the UI.
        if (mounted) {
          setState(() {});
        }
      });
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  static const _nativeDeviceOrientationToQuarterTurns = {
    NativeDeviceOrientation.portraitUp: 0,
    NativeDeviceOrientation.landscapeRight: 1,
    NativeDeviceOrientation.portraitDown: 2,
    NativeDeviceOrientation.landscapeLeft: 3,
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Stack(
        // fit: StackFit.expand,
        alignment: Alignment.bottomCenter,
        children: [
          controller!.value.isInitialized
              ? Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            child: FittedBox(
              fit: BoxFit.cover,
              clipBehavior: Clip.hardEdge,
              child: SizedBox(
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.height,
                child: NativeDeviceOrientationReader(builder: (context) {
                  final orientation =
                  NativeDeviceOrientationReader.orientation(context);
                  return RotatedBox(
                    quarterTurns: _nativeDeviceOrientationToQuarterTurns[
                    orientation]!,
                    child: CameraPreview(controller!),
                  );
                }),
              ),
            ),
          )
              : Container(), // Dummy
          Positioned(
            bottom: 20,
            child: ElevatedButton(
              style: ElevatedButton.styleFrom(
                shape: const StadiumBorder(),
                textStyle: const TextStyle(fontSize: 20),
              ),
              onPressed: null,
              child: Text('Hello'),
            ),
          ),
        ],
      ),
    );
  }
}
```
**AndroidStudio log**
```
Launching lib/main.dart on ONEPLUS A6003 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:33381/T87_5YPofFQ=/ws
Syncing files to device ONEPLUS A6003...
I/CameraManagerGlobal(11178): Connecting to camera service
I/Camera  (11178): [FPS Range Available] is:[15, 15]
I/Camera  (11178): [FPS Range Available] is:[7, 30]
I/Camera  (11178): [FPS Range Available] is:[30, 30]
I/Camera  (11178): [FPS Range] is:[7, 30]
W/Camera  (11178): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
W/Gralloc3(11178): allocator 3.x is not supported
I/Gralloc2(11178): Adding additional valid usage bits: 0x8202400
I/NDOP    (11178): listening using window listener
E/CameraCaptureSession(11178): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(11178): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:456: Camera 0: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:827)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1139)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:737)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:239)
E/CameraCaptureSession(11178): 	at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession(11178): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession(11178): 	at android.os.Looper.loop(Looper.java:214)
E/CameraCaptureSession(11178): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/CameraCaptureSession(11178): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(11178): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/CameraCaptureSession(11178): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
E/CameraCaptureSession(11178): Caused by: android.os.ServiceSpecificException: cancelRequest:456: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(11178): 	at android.os.Parcel.createException(Parcel.java:2085)
E/CameraCaptureSession(11178): 	at android.os.Parcel.readException(Parcel.java:2039)
E/CameraCaptureSession(11178): 	at android.os.Parcel.readException(Parcel.java:1987)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:658)
E/CameraCaptureSession(11178): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
E/CameraCaptureSession(11178): 	... 11 more
W/com.cheqr(11178): Long monitor contention with owner main (11178) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 252ms
```
Feels like a permissions issue. Any ideas?

**Comment by maikeriva** [comment] 2021-06-21 21:41
Tried on another phone, same result but different AndroidStudio log.

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.4 at /home/micheleriva/snap/flutter/common/flutter
    • Framework revision b1395592de (3 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/micheleriva/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Mi MIX 2 (mobile) • eb69a946 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```
**AndroidStudio log**
```
I/com.test(  596): Background concurrent copying GC freed 69437(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/4MB, paused 217us total 101.682ms
I/com.test(  596): Background concurrent copying GC freed 69629(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/4MB, paused 243us total 102.537ms
E/Camera  (  596): Error 2
I/RequestThread-0(  596): Flushing all pending requests.
I/RequestQueue(  596): Repeating capture request cancelled.
W/RequestHolder(  596): Capture failed for request: 0
I/CameraDeviceState(  596): Legacy camera service transitioning to state ERROR
E/RequestQueue(  596): cancel failed: no repeating request exists for request id: 0
E/BufferQueueProducer(  596): [SurfaceTexture-1-596-5] cancelBuffer: BufferQueue has been abandoned
I/chatty  (  596): uid=10293(com.test) Binder:596_6 identical 3 lines
E/BufferQueueProducer(  596): [SurfaceTexture-1-596-5] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(  596): [SurfaceTexture-1-596-5] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(  596): [SurfaceTexture-1-596-5] cancelBuffer: BufferQueue has been abandoned
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:596_6(  596): type=1400 audit(0.0:13018): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=19082 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:596_6(  596): type=1400 audit(0.0:13020): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=19082 scontext=u:r:untrusted_app:s0:c37,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (  596): Access denied finding property "vendor.camera.aux.packagelist"

```
