### ISSUE TITLE
Flutter 2.5.3：Can not slide when using vsyor operation, but can click

### ISSUE THREAD

**Issue by azhon** [flutter/flutter#93526] opened 2021-11-12 05:47 UTC
Flutter 2.5.3：Can not slide when using vsyor operation, but can click.
Flutter 2.2.3：No problem
Vysor Version：Vysor Free Version 4.1.102 (Runtime 4.1.77)
Flutter doctor：
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by danagbemava-nc** [comment] 2021-11-12 08:04
> Can not slide when using vsyor operation

Hi @azhon, can you please explain what you mean by the above? If possible, kindly add a video demonstrating what you're seeing. 

Please provide a complete minimal reproducible code sample as well. 

Thank you

**Comment by azhon** [comment] 2021-11-12 09:06
<img width="1025" alt="project" src="https://user-images.githubusercontent.com/20559556/141439489-4d001c0f-d7ff-4b8c-9f79-221f6de05520.png">
- When the project Flutter sdk is set to 2.2.3, you can use Vysor to slide and click. Here are the steps:
<img width="300" src="https://user-images.githubusercontent.com/20559556/141440408-ca4039b3-a2ef-4eb8-b066-9b1589d78b73.gif" />
- When the project Flutter sdk is set to 2.5.3, you cannot use Vysor to slide, you can only click. Here are the steps:
<img width="300" src="https://user-images.githubusercontent.com/20559556/141439585-52e2609d-8618-4bfa-915f-7585c62f23ac.gif" />

**Comment by maheshmnj** [comment] 2021-11-12 09:18
duplicate of https://github.com/flutter/flutter/issues/90177

**Comment by danagbemava-nc** [comment] 2021-11-12 09:51
Hi @azhon, can you follow #90177 and  see if you still experience the issue?

**Closed** 2021-12-08 05:09 UTC
Labels: waiting for customer response, in triage
