### ISSUE TITLE
tvos

### ISSUE THREAD

**Issue by LeeeYudE** [flutter/flutter#152860] opened 2024-08-05 10:57 UTC
## Command
```
flutter assemble --no-version-check --output=/Users/charcolee/Library/Developer/Xcode/DerivedData/Runner-cojvfjdqirbwiyaeqtdwaxxyykal/Build/Products/Debug-appletvos/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS17.5.sdk -dSplitDebugInfo= -dTreeShakeIcons=true -dTrackWidgetCreation=false -dDartObfuscation=false -dAction=build -dFrontendServerStarterPath= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=C6689C7CCE67A1CC173318374240E23C7C778AFA debug_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      NativeAssets._buildIOS (package:flutter_tools/src/build_system/targets/native_assets.dart:291:68))
```
#0      NativeAssets._buildIOS (package:flutter_tools/src/build_system/targets/native_assets.dart:291:68)
#1      NativeAssets.build (package:flutter_tools/src/build_system/targets/native_assets.dart:85:32)
<asynchronous suspension>
#2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_

**Comment by darshankawar** [comment] 2024-08-05 11:44
Likely the error is coming from:

https://github.com/flutter/flutter/blob/a3bbb24dd5d1e88c5b76e9528ce6ee7e2dbd740f/packages/flutter_tools/lib/src/build_system/targets/native_assets.dart#L290

And mostly, no support for tvOS target so likely the issue is same as https://github.com/flutter/flutter/issues/136754

Do we need to open a new issue for tvOS support just as visionOS https://github.com/flutter/flutter/issues/136754#issuecomment-1927782231

/cc @dcharkes

**Comment by dcharkes** [comment] 2024-08-05 11:50
Duplicate of the mentioned issue. VisionOS is not yet supported. And the error messages in various places in Flutter are rough. Please refer to the linked issue for discussion or contribution solutions.

**Comment by darshankawar** [comment] 2024-08-05 11:56
Closing as duplicate.

**Closed by darshankawar** 2024-08-05 11:56 UTC
Labels: waiting for customer response, in triage
