### ISSUE TITLE
[Flutter Test] Cannot tap on icon button when testing widgets

### ISSUE THREAD

**Issue by ngocmanh1609** [flutter/flutter#78502] opened 2021-03-18 03:17 UTC
## Steps to Reproduce

I follow this [Codelabs](https://codelabs.developers.google.com/codelabs/flutter-app-testing?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#5) to practice testing. But I cannot pass the test that tap on Favorite button.

**Expected results:**
The test in Codelabs should pass.

**Actual results:**
Do step tap on Favorite button doesn't work

**Comment by pedromassangocode** [comment] 2021-03-18 09:29
Hi @ngocmanh1609 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample that you are using?
Thank you

**Comment by ngocmanh1609** [comment] 2021-03-19 02:02
Hi @pedromassangocode 
This is my `flutter doctor -v`
```
Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.2 19C57 darwin-x64, locale
    en-VN)
    • Flutter version 2.0.2 at /Users/manhtran/Desktop/flutter/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/manhtran/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/manhtran/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.2
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ! Xcode 11.5.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
```

And I'm using resource of this Codelabs to perform test. Here is failed test case:
```dart
Widget createHomeScreen() => ChangeNotifierProvider<Favorites>(
      create: (context) => Favorites(),
      child: MaterialApp(
        home: HomePage(),
      ),
    );

testWidgets('Testing IconButtons', (tester) async {
  await tester.pumpWidget(createHomeScreen());
  expect(find.byIcon(Icons.favorite), findsNothing);
  await tester.tap(find.byIcon(Icons.favorite_border).first);
  await tester.pumpAndSettle(Duration(seconds: 1));
  expect(find.text('Added to favorites.'), findsOneWidget);
  expect(find.byIcon(Icons.favorite), findsWidgets);
  await tester.tap(find.byIcon(Icons.favorite).first);
  await tester.pumpAndSettle(Duration(seconds: 1));
  expect(find.text('Removed from favorites.'), findsOneWidget);
  expect(find.byIcon(Icons.favorite), findsNothing);
});
```

I run test by using command `flutter run test/screens/home_test.dart` (run on simulator)

**Comment by pedromassangocode** [comment] 2021-03-19 07:56
I copied the required code from the Codelab and I cannot reproduce this issue.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:provider/provider.dart';

class HomePage extends StatelessWidget {
  static String routeName = '/';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Testing Sample'),
        actions: <Widget>[
          TextButton.icon(
            style: TextButton.styleFrom(primary: Colors.white),
            onPressed: () {
              Navigator.pushNamed(context, '/favoritesPageRouteName');
            },
            icon: Icon(Icons.favorite_border),
            label: Text('Favorites'),
          ),
        ],
      ),
      body: ListView.builder(
        itemCount: 100,
        cacheExtent: 20.0,
        padding: const EdgeInsets.symmetric(vertical: 16),
        itemBuilder: (context, index) => ItemTile(index),
      ),
    );
  }
}

class ItemTile extends StatelessWidget {
  final int itemNo;

  const ItemTile(
      this.itemNo,
      );

  @override
  Widget build(BuildContext context) {
    var favoritesList = Provider.of<Favorites>(context);

    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: ListTile(
        leading: CircleAvatar(
          backgroundColor: Colors.primaries[itemNo % Colors.primaries.length],
        ),
        title: Text(
          'Item $itemNo',
          key: Key('text_$itemNo'),
        ),
        trailing: IconButton(
          key: Key('icon_$itemNo'),
          icon: favoritesList.items.contains(itemNo)
              ? Icon(Icons.favorite)
              : Icon(Icons.favorite_border),
          onPressed: () {
            !favoritesList.items.contains(itemNo)
                ? favoritesList.add(itemNo)
                : favoritesList.remove(itemNo);
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(favoritesList.items.contains(itemNo)
                    ? 'Added to favorites.'
                    : 'Removed from favorites.'),
                duration: Duration(seconds: 1),
              ),
            );
          },
        ),
      ),
    );
  }
}

class Favorites extends ChangeNotifier {
  final List<int> _favoriteItems = [];

  List<int> get items => _favoriteItems;

  void add(int itemNo) {
    _favoriteItems.add(itemNo);
    notifyListeners();
  }

  void remove(int itemNo) {
    _favoriteItems.remove(itemNo);
    notifyListeners();
  }
}

Widget createHomeScreen() => ChangeNotifierProvider<Favorites>(
  create: (context) => Favorites(),
  child: MaterialApp(
    routes: {
      HomePage.routeName: (context) => HomePage(),
      '/favoritesPageRouteName': (context) => Scaffold(),
    },
    initialRoute: '/',
  ),
);

void main() {
  testWidgets('Testing IconButtons', (tester) async {
    await tester.pumpWidget(createHomeScreen());
    expect(find.byIcon(Icons.favorite), findsNothing);
    await tester.tap(find.byIcon(Icons.favorite_border).first);
    await tester.pumpAndSettle(Duration(seconds: 1));
    expect(find.text('Added to favorites.'), findsOneWidget);
    expect(find.byIcon(Icons.favorite), findsWidgets);
    await tester.tap(find.byIcon(Icons.favorite).first);
    await tester.pumpAndSettle(Duration(seconds: 1));
    expect(find.text('Removed from favorites.'), findsOneWidget);
    expect(find.byIcon(Icons.favorite), findsNothing);
  });
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.0.2 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by ngocmanh1609** [comment] 2021-03-19 08:24
oh, do you run the test by using command `flutter run test/screens/home_test.dart`? 🙏 
Could you please try on my repo? https://github.com/sleepylee/learn-flutter-test

**Comment by pedromassangocode** [comment] 2021-03-19 11:42
Hi @ngocmanh1609 
The tests are still passing!


```
MacBook-Pro-de-MacBook:learn-flutter-test pedromassango$ flutters run test/screens/home_test.dart
Using hardware rendering with device sdk gphone x86 64. If you notice graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching test/screens/home_test.dart on sdk gphone x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                       164.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              2,385ms
I/flutter ( 8693): 00:00 +0: Group test home widget Scrolling should perform correctly
Syncing files to device sdk gphone x86 64...                     1,116ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on sdk gphone x86 64 is available at:
http://127.0.0.1:62341/EhSsWqW61UY=/

Flutter DevTools, a Flutter debugger and profiler, on sdk gphone x86 64 is available at:
http://127.0.0.1:9108?uri=http%3A%2F%2F127.0.0.1%3A62341%2FEhSsWqW61UY%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
I/flutter ( 8693): 00:06 +1: Group test home widget Test tap on Favorite an Item
I/flutter ( 8693): 00:12 +2: All tests passed!

```

**Comment by ngocmanh1609** [comment] 2021-03-22 03:50
Oh sorry, the repo has been updated the test case to pass.
This is actual failed case:
```dart
testWidgets('Testing IconButtons', (tester) async {
  await tester.pumpWidget(createHomeScreen());
  expect(find.byIcon(Icons.favorite), findsNothing);
  await tester.tap(find.byIcon(Icons.favorite_border).first);
  await tester.pumpAndSettle(Duration(seconds: 1));
  expect(find.text('Added to favorites.'), findsOneWidget);
  expect(find.byIcon(Icons.favorite), findsWidgets);
  await tester.tap(find.byIcon(Icons.favorite).first);
  await tester.pumpAndSettle(Duration(seconds: 1));
  expect(find.text('Removed from favorites.'), findsOneWidget);
  expect(find.byIcon(Icons.favorite), findsNothing);
});
```

And here is the log when I try to run the test:
```
learn-flutter-test git:(master) ✗ flutter run test/screens/home_test.dart
Launching test/screens/home_test.dart on Mi Note 10 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        13.7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 5.2s
I/flutter (25010): 00:00 +0: Group test home widget Testing IconButtons
Syncing files to device Mi Note 10...                               69ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Mi Note 10 is available at: http://127.0.0.1:62094/nuGuGx5w1Zg=/

Flutter DevTools, a Flutter debugger and profiler, on Mi Note 10 is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A62094%2FnuGuGx5w1Zg%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
I/flutter (25010): (The following exception is now available via WidgetTester.takeException:)
I/flutter (25010): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (25010): The following TestFailure object was thrown running a test:
I/flutter (25010):   Expected: exactly one matching node in the widget tree
I/flutter (25010):   Actual: _TextFinder:<zero widgets with text "Added to favorites." (ignoring offstage widgets)>
I/flutter (25010):    Which: means none were found but one was expected
I/flutter (25010): 
I/flutter (25010): When the exception was thrown, this was the stack:
I/flutter (25010): #4      main.<anonymous closure>.<anonymous closure> (file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart:30:7)
I/flutter (25010): <asynchronous suspension>
I/flutter (25010): <asynchronous suspension>
I/flutter (25010): (elided one frame from package:stack_trace)
I/flutter (25010): ...
I/flutter (25010): 
I/flutter (25010): This was caught by the test expectation on the following line:
I/flutter (25010):   file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart line 30
I/flutter (25010): The test description was:
I/flutter (25010):   Testing IconButtons
I/flutter (25010): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25010): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (25010): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (25010): The following TestFailure object was thrown running a test:
I/flutter (25010):   Expected: exactly one matching node in the widget tree
I/flutter (25010):   Actual: _TextFinder:<zero widgets with text "Added to favorites." (ignoring offstage widgets)>
I/flutter (25010):    Which: means none were found but one was expected
I/flutter (25010): 
I/flutter (25010): When the exception was thrown, this was the stack:
I/flutter (25010): #4      main.<anonymous closure>.<anonymous closure> (file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart:30:7)
I/flutter (25010): <asynchronous suspension>
I/flutter (25010): <asynchronous suspension>
I/flutter (25010): (elided one frame from package:stack_trace)
I/flutter (25010): ...
I/flutter (25010): 
I/flutter (25010): This was caught by the test expectation on the following line:
I/flutter (25010):   file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart line 30
I/flutter (25010): The test description was:
I/flutter (25010):   Testing IconButtons
I/flutter (25010): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25010): 00:03 +0: Group test home widget Testing IconButtons [E]
I/flutter (25010):   Test failed. See exception logs above.
I/flutter (25010):   The test description was: Testing IconButtons
I/flutter (25010):   
I/flutter (25010): 00:03 +0 -1: Some tests failed.
```

**Comment by ngocmanh1609** [comment] 2021-03-22 03:51
it's so weird because it's passed on your side but me 🤔

**Comment by pedromassangocode** [comment] 2021-03-22 07:23
> Oh sorry, the repo has been updated the test case to pass.

Is this still a valid issue? Is the test case in the codelab still failing for you?

**Comment by ngocmanh1609** [comment] 2021-03-22 07:55
> Is this still a valid issue? Is the test case in the codelab still failing for you?

yes, the test in the codelab is still failing. [Above](https://github.com/flutter/flutter/issues/78502#issuecomment-803741514) is the failed log 🙏

**Comment by pedromassangocode** [comment] 2021-03-22 08:43
> yes, the test in the codelab is still failing.

I'm not sure if you are running the exact same code as the one in the codelab. You code in https://github.com/flutter/flutter/issues/78502#issuecomment-802645517 seems to be different from the one in the codelab. 


<details>
<summary>logs</summary>

```bash
Launching test/screens/home_test.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.2s
Xcode build done.                                           25.8s
flutter: 00:00 +0: Group test home widget Scrolling should perform correctly
flutter: (The following exception is now available via WidgetTester.takeException:)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:    
flutter:   Expected: no matching nodes in the widget tree               
flutter:   Actual: _TextFinder:<exactly one widget with text "Item 0" (ignoring offstage widgets):
flutter: Text-[<'text_0'>]("Item 0", dependencies: [DefaultTextStyle, MediaQuery])>
flutter:    Which: means one was found but none were expected           
flutter:                                                                
flutter: When the exception was thrown, this was the stack:             
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///Users/pedromassango/Desktop/learn-flutter-test/test/screens/home_test.dart:22:7)
flutter: <asynchronous suspension>                                      
flutter: <asynchronous suspension>                                      
flutter: (elided one frame from package:stack_trace)                    
flutter: ...                                                            
flutter:                                                                
flutter: This was caught by the test expectation on the following line: 
flutter:   file:///Users/pedromassango/Desktop/learn-flutter-test/test/screens/home_test.dart line 22
flutter: The test description was:                                      
flutter:   Scrolling should perform correctly                           
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:    
flutter:   Expected: no matching nodes in the widget tree               
flutter:   Actual: _TextFinder:<exactly one widget with text "Item 0" (ignoring offstage widgets):
flutter: Text-[<'text_0'>]("Item 0", dependencies: [DefaultTextStyle, MediaQuery])>
flutter:    Which: means one was found but none were expected           
flutter:                                                                
flutter: When the exception was thrown, this was the stack:             
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///Users/pedromassango/Desktop/learn-flutter-test/test/screens/home_test.dart:22:7)
flutter: <asynchronous suspension>                                      
flutter: <asynchronous suspension>                                      
flutter: (elided one frame from package:stack_trace)                    
flutter: ...                                                            
flutter:                                                                
flutter: This was caught by the test expectation on the following line: 
flutter:   file:///Users/pedromassango/Desktop/learn-flutter-test/test/screens/home_test.dart line 22
flutter: The test description was:                                      
flutter:   Scrolling should perform correctly                           
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:02 +0: Group test home widget Scrolling should perform correctly [E]
flutter:   Test failed. See exception logs above.                       
  The test description was: Scrolling should perform correctly
flutter:                                                                
flutter: 00:02 +0 -1: Group test home widget Test tap on Favorite an Item
Syncing files to device iPhone 12 Pro Max...                       209ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:53799/FkIhfjQbw7k=/

Flutter DevTools, a Flutter debugger and profiler, on iPhone 12 Pro Max is available at:
http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A53799%2FFkIhfjQbw7k%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
flutter: 00:07 +1 -1: Some tests failed.
```
</details>



I've copied the exact same code from the codelab (in https://github.com/flutter/flutter/issues/78502#issuecomment-802630324) please try that code to see if it the tests passes.

**Comment by ngocmanh1609** [comment] 2021-03-24 03:59
Hi @pedromassangocode , sorry for late reply.
I have copied exactly your code from [your comment](https://github.com/flutter/flutter/issues/78502#issuecomment-802630324) to test, but it's still failed on my side.

Here is the test log:
```
flutter run test/screens/home_test.dart                  
Launching test/screens/home_test.dart on Mi Note 10 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        14.9s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 6.6s
I/flutter (23744): 00:00 +0: Testing IconButtons                        
Activating Dart DevTools...                                      2,246ms
Syncing files to device Mi Note 10...                               75ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Mi Note 10 is available at:
http://127.0.0.1:61287/OzdqXg4A5Uo=/

Flutter DevTools, a Flutter debugger and profiler, on Mi Note 10 is available at:
http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A61287%2FOzdqXg4A5Uo%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
I/flutter (23744): (The following exception is now available via WidgetTester.takeException:)
I/flutter (23744): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (23744): The following TestFailure object was thrown running a test:
I/flutter (23744):   Expected: exactly one matching node in the widget tree
I/flutter (23744):   Actual: _TextFinder:<zero widgets with text "Added to favorites." (ignoring offstage widgets)>
I/flutter (23744):    Which: means none were found but one was expected
I/flutter (23744): 
I/flutter (23744): When the exception was thrown, this was the stack:
I/flutter (23744): #4      main.<anonymous closure> (file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart:113:5)
I/flutter (23744): <asynchronous suspension>
I/flutter (23744): <asynchronous suspension>
I/flutter (23744): (elided one frame from package:stack_trace)
I/flutter (23744): ...
I/flutter (23744): 
I/flutter (23744): This was caught by the test expectation on the following line:
I/flutter (23744):   file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart line 113
I/flutter (23744): The test description was:
I/flutter (23744):   Testing IconButtons
I/flutter (23744): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23744): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (23744): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (23744): The following TestFailure object was thrown running a test:
I/flutter (23744):   Expected: exactly one matching node in the widget tree
I/flutter (23744):   Actual: _TextFinder:<zero widgets with text "Added to favorites." (ignoring offstage widgets)>
I/flutter (23744):    Which: means none were found but one was expected
I/flutter (23744): 
I/flutter (23744): When the exception was thrown, this was the stack:
I/flutter (23744): #4      main.<anonymous closure> (file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart:113:5)
I/flutter (23744): <asynchronous suspension>
I/flutter (23744): <asynchronous suspension>
I/flutter (23744): (elided one frame from package:stack_trace)
I/flutter (23744): ...
I/flutter (23744): 
I/flutter (23744): This was caught by the test expectation on the following line:
I/flutter (23744):   file:///Users/manhtran/Desktop/flutter/practice/learn-flutter-test/test/screens/home_test.dart line 113
I/flutter (23744): The test description was:
I/flutter (23744):   Testing IconButtons
I/flutter (23744): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23744): 00:03 +0: Testing IconButtons [E]
I/flutter (23744):   Test failed. See exception logs above.
I/flutter (23744):   The test description was: Testing IconButtons
I/flutter (23744):   
I/flutter (23744): 00:03 +0 -1: Some tests failed.

```

**Comment by pedromassangocode** [comment] 2021-03-24 07:03
Does the test fails if you run it on Android Emulator?

**Comment by ngocmanh1609** [comment] 2021-03-24 08:01
it's failed on both emulator and real device, my device Xiaomi Mi 10 fyi 🙏

**Comment by nt4f04uNd** [comment] 2021-08-15 22:45
It could be fixed on master, see https://github.com/flutter/flutter/issues/78749#issuecomment-899116788

**Comment by nt4f04uNd** [comment] 2021-12-16 22:20
I ran the code sample from https://github.com/flutter/flutter/issues/78502#issuecomment-802630324 on real device on latest stable and couldn't reproduce the issue.

@ngocmanh1609 can you see if it is solved for you as well?

**Closed** 2022-01-06 23:10 UTC
Labels: a: tests, waiting for customer response, framework, passed first triage, integration_test
