### ISSUE TITLE
Android Environment: Issues with WidgetSpan Display in Arabic Language

### ISSUE THREAD

**Issue by xbl113lbw** [flutter/flutter#146977] opened 2024-04-18 09:17 UTC
### Steps to reproduce

1、flutter  3.19.5
2、Create a list
3、Create a rich text widget

When using Text.rich with rich text layouts in an Android environment set to Arabic, I am experiencing some confusing behaviors with list numbering and text direction. I have set the text direction to right-to-left (RTL). Using TextSpan, the numbering displays correctly following the RTL order. However, when I switch to using WidgetSpan, the behavior seems uncontrolled and does not align with the expected RTL sequence.

This is my first time encountering this issue, and I am unsure if I am making a mistake. Please correct me if I am wrong.

### Expected results

In a right-to-left (RTL) layout, especially in Arabic, I expect that both TextSpan and WidgetSpan should adhere to the RTL direction consistently. All text and widget elements should align correctly and display in the order they are added, with the numbering or sequence of list items appearing correctly from right to left. This should ensure a seamless and intuitive user experience for Arabic-speaking users, with all inline elements behaving uniformly under RTL settings.

### Actual results

Currently, while TextSpan elements respect the right-to-left (RTL) text direction correctly, displaying numbering and text in the expected order, WidgetSpan elements do not behave as anticipated. When using WidgetSpan within a Text.rich setup, the elements appear to be rendered out of control and do not follow the RTL sequence. This discrepancy leads to a confusing user interface, particularly for lists where numbers or widgets appear in the wrong order, disrupting the natural reading flow for Arabic-speaking users.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: DemoPage(),
    );
  }
}

class DemoPage extends StatefulWidget {
  const DemoPage({super.key});

  @override
  State<DemoPage> createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  List demo = [
    {"val": "1الفاتحة", "idx": 1},
    {"val": "2الفاتحة", "idx": 2},
    {"val": "3الفاتحة", "idx": 3},
    {"val": "4الفاتحة", "idx": 4},
    {"val": "5الفاتحة", "idx": 5},
    {"val": "6الفاتحة", "idx": 6},
    {"val": "7الفاتحة", "idx": 7},
  ];

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Directionality(
        textDirection: TextDirection.rtl,
        child: Text.rich(
          TextSpan(
            children: [
              ...demo.map((item) {
                return TextSpan(
                  children: [
                    TextSpan(text: item["val"]),
                    TextSpan(text: item["idx"].toString(), style: const TextStyle(color: Colors.red)),
                    WidgetSpan(
                      child: Text(
                        item["idx"].toString(),
                        textDirection: TextDirection.rtl,
                        style: const TextStyle(color: Colors.blue),
                      ),
                    )
                  ],
                );
              }).toList(),
            ],
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [version 10.0.22631.3447])
    • Flutter version 3.19.5 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at C:\Users\xbl113lbw\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • ANDROID_HOME = C:\Users\xbl113lbw\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 4.2)
    • Android Studio at D:\androidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at D:\IntelliJ IDEA 2023.1.1
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[√] Connected device (4 available)
    • SM A2360 (mobile) • R5CW31KASSK • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [版本 10.0.22631.3447]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 123.0.6312.106
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-18 10:27
I believe this is a duplicate of  https://github.com/flutter/flutter/issues/54400.

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-04-18 10:27 UTC
Labels: in triage
