### ISSUE TITLE
Flutter instructions are all messed up! 

### ISSUE THREAD

**Issue by Joebeazelman** [flutter/flutter#113578] opened 2022-10-17 22:40 UTC
Flutter instructions for getting started are all wrong.  The download and unzip instructions don't work when you try to create run **flutter create** or **flutter doctor**.  In both cases, flutter immediately reports the error:

```
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to install Flutter, see the instructions at:
       https://flutter.dev/get-started
```

The correct instructions are to use git to download the repository, but the documentation says it's only for advanced scenarios.  

Come on Google!  You guys are almost as bad as Microsoft.  I'd cut you guys some slack, but you're a multibillion-dollar company with too much power in your hands!

## Steps to Reproduce

Follow your own getting started instructions. 

## Logs

<details>
<summary>Logs</summary>

```
```

Do you guys understand the concept of privacy?  The dump contains personally identifiable data.

```
 Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale
    en-US)
```

</details>

**Comment by exaby73** [comment] 2022-10-18 10:03
Hello @Joebeazelman. In the [System Requirements](https://docs.flutter.dev/get-started/install/macos#system-requirements) section, it's clearly mentioned that git is required for the installation of Flutter. 

The advanced use case you're mentioning is for [downloading the source code directly from Git](https://docs.flutter.dev/get-started/install/macos#system-requirements). Nowhere is it mentioned that you can install Flutter without git installed.

Due to above reasons, I am closing this issue. Thank you.

**Comment by Joebeazelman** [comment] 2022-10-18 19:41
> Hello @Joebeazelman. In the [System Requirements](https://docs.flutter.dev/get-started/install/macos#system-requirements) section, it's clearly mentioned that git is required for the installation of Flutter.
> 
> The advanced use case you're mentioning is for [downloading the source code directly from Git](https://docs.flutter.dev/get-started/install/macos#system-requirements). Nowhere is it mentioned that you can install Flutter without git installed.

You didn't read the issue carefully. It has nothing to do with Git.  I already had it installed before following the instructions.  Let me reiterate the issue more clearly:

The documentation instructs the user to perform the following steps:

1. Download Flutter SDK bundle depending on your platform and its architecture.
2. Extract the folder to a "desired" location. 
3. Add Flutter bin folder  to the system's path

After completing them, it instructs the user to execute the following command to ensure everything is correctly installed.

`
$ flutter doctor
`
Doing so, however, results in the following error  message:

```
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to install Flutter, see the instructions at:
       https://flutter.dev/get-started
```

Clearly, the installation instructions are either incorrect, or there's something wrong with the downloaded archive!  Replacing Steps 1 and 2 with the following, however, does work, but the documentation considers it to be an advanced option:

`$ git clone https://github.com/flutter/flutter.git -b stable`

**Comment by exaby73** [comment] 2022-10-19 08:12
Could you tell me which directory you are extracting it to?

**Comment by Joebeazelman** [comment] 2022-10-19 23:58
I extracted the folder to my download folder and copied it to my user home directory.d

**Comment by exaby73** [comment] 2022-10-20 13:43
I cannot reproduce this. I have downloaded a new zip file, extracted into my home folder and ran `flutter doctor` with the binary in `~/flutter/bin/flutter`. Am I missing a step here? _Tested on MacOS 12.6 on M1 Macbook Air_

**Closed** 2022-11-10 14:16 UTC
Labels: waiting for customer response, in triage
