### ISSUE TITLE
App bar and tab bar, where the app bar hides when you scroll up

### ISSUE THREAD

**Issue by themindstorm** [flutter/flutter#29561] opened 2019-03-18 19:08 UTC
[This](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1cx_CQC_pYOeAxmJAoEIjGnZNAWQzz-O1%2Ftabs-scrolling-1.mp4) is the desired behaviour (video from [Tabs - Material.io](https://material.io/design/components/tabs.html#behavior)). This works in the same way as the Android WhatsApp application. When you scroll down, the app bar gets hidden, while the tab bar always stays in view. When you scroll back up, the app bar shows again smoothly.

[This is the code to recreate](https://github.com/themindstorm/flutter-autohide-tabbar-problem). (See [GIF](https://github.com/themindstorm/flutter-autohide-tabbar-problem/blob/master/tabbar.gif) here for a demonstration of the problem)

## Here is the basic structure:
- MaterialApp
  - DefaultTabController
    - Scaffold
      - NestedScrollView
        - _headerSliverBuilder:_ **SliverAppBar**
          - _bottom:_ **TabBar**
        - _body:_ **TabBarView**

## Problems/issues
- `snap: true` is necessary, although I do not want a snapping behaviour
- Content gets hidden when you change tabs – This can probably be solved using the `SafeArea` widget. (See [GIF](https://github.com/themindstorm/flutter-autohide-tabbar-problem/blob/master/tabbar.gif) here)

I also have also tried switching to a `Stateful` widget for controlling tabs, but that did not make any difference. I do not think it should make a difference.

## Related stackoverflow question
https://stackoverflow.com/questions/55187332/flutter-tabbar-and-sliverappbar-that-hides-when-you-scroll-down

The answer does not solve the problem completely.

## Possible related issues
- https://github.com/flutter/flutter/issues/17518
- https://github.com/flutter/flutter/issues/22475

**Comment by iRbouh** [comment] 2019-03-22 01:46
Hi, you need to use [SliverOverlapAbsorber/SliverOverlapInjector](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html), the following code works for me:

```dart
@override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        body: DefaultTabController(
          length: _tabs.length, // This is the number of tabs.
          child: NestedScrollView(
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              // These are the slivers that show up in the "outer" scroll view.
              return <Widget>[
                SliverOverlapAbsorber(
                  // This widget takes the overlapping behavior of the SliverAppBar,
                  // and redirects it to the SliverOverlapInjector below. If it is
                  // missing, then it is possible for the nested "inner" scroll view
                  // below to end up under the SliverAppBar even when the inner
                  // scroll view thinks it has not been scrolled.
                  // This is not necessary if the "headerSliverBuilder" only builds
                  // widgets that do not overlap the next sliver.
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  child: SliverSafeArea(
                    top: false,
                    sliver: SliverAppBar(
                      title: const Text('Books'),
                      floating: true,
                      pinned: true,
                      snap: false,
                      primary: true,
                      forceElevated: innerBoxIsScrolled,
                      bottom: TabBar(
                        // These are the widgets to put in each tab in the tab bar.
                        tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                      ),
                    ),
                  ),
                ),
              ];
            },
            body: TabBarView(
              // These are the contents of the tab views, below the tabs.
              children: _tabs.map((String name) {
                return SafeArea(
                  top: false,
                  bottom: false,
                  child: Builder(
                    // This Builder is needed to provide a BuildContext that is "inside"
                    // the NestedScrollView, so that sliverOverlapAbsorberHandleFor() can
                    // find the NestedScrollView.
                    builder: (BuildContext context) {
                      return CustomScrollView(
                        // The "controller" and "primary" members should be left
                        // unset, so that the NestedScrollView can control this
                        // inner scroll view.
                        // If the "controller" property is set, then this scroll
                        // view will not be associated with the NestedScrollView.
                        // The PageStorageKey should be unique to this ScrollView;
                        // it allows the list to remember its scroll position when
                        // the tab view is not on the screen.
                        key: PageStorageKey<String>(name),
                        slivers: <Widget>[
                          SliverOverlapInjector(
                            // This is the flip side of the SliverOverlapAbsorber above.
                            handle:
                                NestedScrollView.sliverOverlapAbsorberHandleFor(
                                    context),
                          ),
                          SliverPadding(
                            padding: const EdgeInsets.all(8.0),
                            // In this example, the inner scroll view has
                            // fixed-height list items, hence the use of
                            // SliverFixedExtentList. However, one could use any
                            // sliver widget here, e.g. SliverList or SliverGrid.
                            sliver: SliverFixedExtentList(
                              // The items in this example are fixed to 48 pixels
                              // high. This matches the Material Design spec for
                              // ListTile widgets.
                              itemExtent: 60.0,
                              delegate: SliverChildBuilderDelegate(
                                (BuildContext context, int index) {
                                  // This builder is called for each child.
                                  // In this example, we just number each list item.
                                  return Container(
                                      color: Color((math.Random().nextDouble() *
                                                      0xFFFFFF)
                                                  .toInt() <<
                                              0)
                                          .withOpacity(1.0));
                                },
                                // The childCount of the SliverChildBuilderDelegate
                                // specifies how many children this inner list
                                // has. In this example, each tab has a list of
                                // exactly 30 items, but this is arbitrary.
                                childCount: 30,
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
```

**Comment by themindstorm** [comment] 2019-03-22 03:04
@iRbouh 
Thank you for your answer. This seems to be the closest the solve the problem, but the problem is still that `snap: true` is required for the app bar to show up when you scroll from any position on the screen, unfortunately

**Comment by cholojuanito** [comment] 2019-03-23 23:53
@themindstorm 
Glad you found an answer! Also, if you change `snap = true` then it works but it is slightly delayed.

**Comment by themindstorm** [comment] 2019-03-24 11:19
How exactly is it working for you? For me, `snap: true` is required

**Comment by themindstorm** [comment] 2019-03-26 14:11
@iRbouh 
Sorry to disturb you, but is there anything that can be done to remove this white space above the list? I believe it is being created by the `sliverOverlapAbsorberHandleFor`.
![image](https://user-images.githubusercontent.com/34677361/55003849-18f83b00-5014-11e9-8d72-26d82982329e.png)

**Comment by cholojuanito** [comment] 2019-03-26 15:28
@themindstorm
It's being caused by the `SliverPadding` widget

**Comment by themindstorm** [comment] 2019-03-27 12:52
@cholojuanito 
Thanks! BTW, I tested the app on a physical Android device, and the space above the list (as seen in the image of my previous post) is not there. Not that I'm complaining.

So the problem seems to be because of the iPhone notch

**Comment by cholojuanito** [comment] 2019-03-27 15:46
@themindstorm
Okay, so it changes between devices then it's probably the `SafeArea` widget. I think if you move it around (higher or lower in the widget tree) you'll be able to find the right setup for all devices

**Comment by themindstorm** [comment] 2019-03-28 04:02
@cholojuanito 
Okay, thank you for your help

**Comment by themindstorm** [comment] 2019-03-30 05:25
There was also one more issue (on iPhone X only):
The last few containers will never come into view (not sure why). This can be fixed by wrapping the `SliverFixedExtentList` with

```
SliverPadding(
    padding: EdgeInsets.only(bottom: 200),  // <-- change to 150 maybe
    sliver: ...
)
```

And for the iPhone X safe area issue, I just added these lines to the `NestedScrollView.sliverOverlapAbsorberHandleFor()`:

```
handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
child: SliverSafeArea(
    top: false,
    bottom: false,
    sliver: SliverAppBar(
        ...
    )
    ...
)
```

I haven't tested this on any rectangular-shaped phone yet.

**Comment by Dacarnix** [comment] 2019-04-03 16:49
Do we know if the 'snap' feature will be fixed so it scrolls back (down) on scroll up, and doesn't wait for it to stop first? (IE - in the Android Play Music app).

**Comment by themindstorm** [comment] 2019-04-15 14:25
@Dacarnix 
Sorry, but I have no idea. I've asked the same question on reddit and stackoverflow, but I didn't get any 100% working answers:

- https://stackoverflow.com/questions/55187332/flutter-tabbar-and-sliverappbar-that-hides-when-you-scroll-down
- https://www.reddit.com/r/FlutterDev/comments/b23sc9/is_this_tab_behaviour_possible_in_flutter_taken/
- https://www.reddit.com/r/Flutter/comments/b2jroh/how_do_you_make_this_sliverappbartabbar_layout/

There are also a few other issues to follow:

- #17518
- #22475

**Comment by lucasavila00** [comment] 2019-07-04 21:17
The problem is because at[ this line ](https://github.com/flutter/flutter/blob/93edc014aea42e957a6f487376e33972db6188ef/packages/flutter/lib/src/rendering/sliver_persistent_header.dart#L464)(and any other that reads the scrolloffset from constraints) the offstet returned is only the one relative to the "headerSliverBuilder" portion and not the "body" portion.

I don't know how to inject the correct value there but it seems that it would be the fix.
Also, when using a ScrollController on a NestedScrollView what you get when acessing position is also only the header scroll, not the header+body scroll.

I don't know how but they should be receiving the correct values...

**Comment by azuddin** [comment] 2019-09-16 16:31
> Hi, you need to use [SliverOverlapAbsorber/SliverOverlapInjector](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html), the following code works for me ([Gist](https://gist.github.com/iRbouh/219a81b3f2e32c3ef725972b45627f2e)) :
> 
> ```dart
> @override
>   Widget build(BuildContext context) {
>     return Material(
>       child: Scaffold(
>         body: DefaultTabController(
>           length: _tabs.length, // This is the number of tabs.
>           child: NestedScrollView(
>             headerSliverBuilder:
>                 (BuildContext context, bool innerBoxIsScrolled) {
>               // These are the slivers that show up in the "outer" scroll view.
>               return <Widget>[
>                 SliverOverlapAbsorber(
>                   // This widget takes the overlapping behavior of the SliverAppBar,
>                   // and redirects it to the SliverOverlapInjector below. If it is
>                   // missing, then it is possible for the nested "inner" scroll view
>                   // below to end up under the SliverAppBar even when the inner
>                   // scroll view thinks it has not been scrolled.
>                   // This is not necessary if the "headerSliverBuilder" only builds
>                   // widgets that do not overlap the next sliver.
>                   handle:
>                       NestedScrollView.sliverOverlapAbsorberHandleFor(context),
>                   child: SliverSafeArea(
>                     top: false,
>                     sliver: SliverAppBar(
>                       title: const Text('Books'),
>                       floating: true,
>                       pinned: true,
>                       snap: false,
>                       primary: true,
>                       forceElevated: innerBoxIsScrolled,
>                       bottom: TabBar(
>                         // These are the widgets to put in each tab in the tab bar.
>                         tabs: _tabs.map((String name) => Tab(text: name)).toList(),
>                       ),
>                     ),
>                   ),
>                 ),
>               ];
>             },
>             body: TabBarView(
>               // These are the contents of the tab views, below the tabs.
>               children: _tabs.map((String name) {
>                 return SafeArea(
>                   top: false,
>                   bottom: false,
>                   child: Builder(
>                     // This Builder is needed to provide a BuildContext that is "inside"
>                     // the NestedScrollView, so that sliverOverlapAbsorberHandleFor() can
>                     // find the NestedScrollView.
>                     builder: (BuildContext context) {
>                       return CustomScrollView(
>                         // The "controller" and "primary" members should be left
>                         // unset, so that the NestedScrollView can control this
>                         // inner scroll view.
>                         // If the "controller" property is set, then this scroll
>                         // view will not be associated with the NestedScrollView.
>                         // The PageStorageKey should be unique to this ScrollView;
>                         // it allows the list to remember its scroll position when
>                         // the tab view is not on the screen.
>                         key: PageStorageKey<String>(name),
>                         slivers: <Widget>[
>                           SliverOverlapInjector(
>                             // This is the flip side of the SliverOverlapAbsorber above.
>                             handle:
>                                 NestedScrollView.sliverOverlapAbsorberHandleFor(
>                                     context),
>                           ),
>                           SliverPadding(
>                             padding: const EdgeInsets.all(8.0),
>                             // In this example, the inner scroll view has
>                             // fixed-height list items, hence the use of
>                             // SliverFixedExtentList. However, one could use any
>                             // sliver widget here, e.g. SliverList or SliverGrid.
>                             sliver: SliverFixedExtentList(
>                               // The items in this example are fixed to 48 pixels
>                               // high. This matches the Material Design spec for
>                               // ListTile widgets.
>                               itemExtent: 60.0,
>                               delegate: SliverChildBuilderDelegate(
>                                 (BuildContext context, int index) {
>                                   // This builder is called for each child.
>                                   // In this example, we just number each list item.
>                                   return Container(
>                                       color: Color((math.Random().nextDouble() *
>                                                       0xFFFFFF)
>                                                   .toInt() <<
>                                               0)
>                                           .withOpacity(1.0));
>                                 },
>                                 // The childCount of the SliverChildBuilderDelegate
>                                 // specifies how many children this inner list
>                                 // has. In this example, each tab has a list of
>                                 // exactly 30 items, but this is arbitrary.
>                                 childCount: 30,
>                               ),
>                             ),
>                           ),
>                         ],
>                       );
>                     },
>                   ),
>                 );
>               }).toList(),
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> ```

when changing tab after scrolling on another tab, the scroll position will follow, how would you fix that?

**Comment by themindstorm** [comment] 2019-09-17 12:10
@azuddin 
Are you facing the problem shown in [this GIF](https://github.com/themindstorm/flutter-autohide-tabbar-problem/blob/master/tabbar.gif)?

**Comment by azuddin** [comment] 2019-09-17 14:14
> @azuddin
> Are you facing the problem shown in [this GIF](https://github.com/themindstorm/flutter-autohide-tabbar-problem/blob/master/tabbar.gif)?

sort of. my behaviour more like this

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8788888/65049493-6a1c3280-d998-11e9-80f6-818c22fbeb42.gif)


here's the code:

```
import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: NewsScreen(),
    );
  }
}

class NewsScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _NewsScreenState();
}

class _NewsScreenState extends State<NewsScreen> {
  final List<String> listItems = [];

  final List<String> _tabs = <String>[
    "Featured",
    "Popular",
    "Latest",
  ];

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        body: DefaultTabController(
          length: _tabs.length, // This is the number of tabs.
          child: NestedScrollView(
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              // These are the slivers that show up in the "outer" scroll view.
              return <Widget>[
                SliverOverlapAbsorber(
                  // This widget takes the overlapping behavior of the SliverAppBar,
                  // and redirects it to the SliverOverlapInjector below. If it is
                  // missing, then it is possible for the nested "inner" scroll view
                  // below to end up under the SliverAppBar even when the inner
                  // scroll view thinks it has not been scrolled.
                  // This is not necessary if the "headerSliverBuilder" only builds
                  // widgets that do not overlap the next sliver.
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  child: SliverSafeArea(
                    top: false,
                    sliver: SliverAppBar(
                      title: const Text('Books'),
                      floating: true,
                      pinned: true,
                      snap: true,
                      primary: true,
                      forceElevated: innerBoxIsScrolled,
                      bottom: TabBar(
                        // These are the widgets to put in each tab in the tab bar.
                        tabs: _tabs
                            .map((String name) => Tab(text: name))
                            .toList(),
                      ),
                    ),
                  ),
                ),
              ];
            },
            body: TabBarView(
              // These are the contents of the tab views, below the tabs.
              children: _tabs.map((String name) {
                return SafeArea(
                  top: false,
                  bottom: false,
                  child: Builder(
                    // This Builder is needed to provide a BuildContext that is "inside"
                    // the NestedScrollView, so that sliverOverlapAbsorberHandleFor() can
                    // find the NestedScrollView.
                    builder: (BuildContext context) {
                      return CustomScrollView(
                        // The "controller" and "primary" members should be left
                        // unset, so that the NestedScrollView can control this
                        // inner scroll view.
                        // If the "controller" property is set, then this scroll
                        // view will not be associated with the NestedScrollView.
                        // The PageStorageKey should be unique to this ScrollView;
                        // it allows the list to remember its scroll position when
                        // the tab view is not on the screen.
                        key: PageStorageKey<String>(name),
                        slivers: <Widget>[
                          SliverOverlapInjector(
                            // This is the flip side of the SliverOverlapAbsorber above.
                            handle:
                                NestedScrollView.sliverOverlapAbsorberHandleFor(
                                    context),
                          ),
                          SliverPadding(
                            padding: const EdgeInsets.all(8.0),
                            // In this example, the inner scroll view has
                            // fixed-height list items, hence the use of
                            // SliverFixedExtentList. However, one could use any
                            // sliver widget here, e.g. SliverList or SliverGrid.
                            sliver: SliverFixedExtentList(
                              // The items in this example are fixed to 48 pixels
                              // high. This matches the Material Design spec for
                              // ListTile widgets.
                              itemExtent: 100.0,
                              delegate: SliverChildBuilderDelegate(
                                (BuildContext context, int index) {
                                  // This builder is called for each child.
                                  // In this example, we just number each list item.
                                  return Column(
                                    children: <Widget>[
                                      Container(
                                        height: 90,
                                        width: double.infinity,
                                        color: Colors.blueGrey,
                                        child: Column(
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          children: <Widget>[
                                            Text('$index'),
                                          ],
                                        ),
                                      ),
                                      SizedBox(height: 10),
                                    ],
                                  );
                                },
                                // The childCount of the SliverChildBuilderDelegate
                                // specifies how many children this inner list
                                // has. In this example, each tab has a list of
                                // exactly 30 items, but this is arbitrary.
                                childCount: 30,
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by themindstorm** [comment] 2019-09-19 19:51
@azuddin 
The white space at the top is likely being caused by a `SafeArea` along with the iPhone X notch (if I'm not mistaken). I managed to fix this in my app.

Take a look at this file: https://github.com/holt-soundboard/holt-soundboard-mobile/blob/master/lib/pages/home_page.dart#L28

```
Scaffold(
  drawer: AppDrawer(),
  body: DefaultTabController(
    length: soundsProvider.getCharacters().length,
    child: NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            child: SliverSafeArea(
              top: false,
              bottom: false,
              sliver: Appbars.primary(context) // <-- This is just a sliver app bar which is pinned and floating
            ),
          )
        ];
      },
      body: TabBarView(
        children: <Widget>[
          for (var character in soundsProvider.getCharacters()) 
            SafeArea(
              top: false,
              bottom: false,
              child: Builder(
                builder: (BuildContext context) {
                  return CustomScrollView(
                    key: PageStorageKey<String>(character),
                    slivers: <Widget>[
                      SliverOverlapInjector(
                        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                      ),
                      SliverPadding(
                        padding: EdgeInsets.all(PaddingValues.main),
                        sliver: SoundsGrid(
                          character: character,
                          isFavoritesGrid: false
                        )
                      ),
                      SliverToBoxAdapter(
                        child: Footer(),
                      )
                    ],
                  );
                }
              ),
            )
        ],
      )
    ),
  )
);
```

I'm using a sliver grid, not a list, but I think they work similarly.

Try using this code and see if it works. It's working fine for me on all devices.

**Comment by azuddin** [comment] 2019-09-20 03:27
@themindstorm yup it fix the extra space problem. but the scroll problem still presents. I've created an issue for this https://github.com/flutter/flutter/issues/40740

**Comment by CountPablo** [comment] 2019-11-05 20:30
Any updates on the original issue here?

**Comment by AlptugYaman** [comment] 2019-12-11 22:48
```
return DefaultTabController(
      length: 3,
      child: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerboxisScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 205,
              floating: false,
              pinned: false,
              automaticallyImplyLeading: false,
              backgroundColor: Theme.of(context).primaryColor,
              flexibleSpace: FlexibleSpaceBar(background: _profilebg()),
            ),
            SliverPersistentHeader(
              delegate: _SliverAppBarDelegate(
                  TabBar(
                    labelColor: Theme.of(context).accentColor,
                    labelStyle: TextStyle(fontWeight: FontWeight.bold),
                    unselectedLabelStyle:
                        TextStyle(fontWeight: FontWeight.normal),
                    indicatorColor: Theme.of(context).accentColor,
                    unselectedLabelColor: Colors.grey,
                    tabs: <Widget>[
                      Tab(
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[Text('145'), Text('Photos')],
                          ),
                        ),
                      ),
                      Tab(
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[Text('754'), Text('Following')],
                          ),
                        ),
                      ),
                      Tab(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[Text('56'), Text('Followers')],
                        ),
                      ),
                    ],
                  ),
                  Theme.of(context).primaryColor),
              pinned: true,
              floating: true,
            )
          ];
        },
        body: TabBarView(controller: tabController,
            children: <Widget>[
              UserPhotos(),
              Following(),
              Followers(),
            ]),
      ),
    );
```

i have same issue. In tabbarview i get some datas from an api with FutureBuilder but my slivers do not work. Any suggestion? Thanks.

**Comment by Piinks** [comment] 2020-01-23 23:01
The original issue here is a duplicate of #17518. I am going to close this so that discussion and changes can be tracked in one bug. 
There appears to be concern about white space issues here as well. I would recommend opening a new issue that can be dedicated to specifically addressing that. Thanks! :)

**Closed by Piinks** 2020-01-23 23:01 UTC
Labels: f: material design, framework

**Comment by kaxp** [comment] 2020-12-22 08:17
If anyone wants to refer a working code sample for whatsapp type floating sliverappbar with tabs, here it is -> https://dartpad.dev/0955dcf876ba24619b86d49ec50788cc?

![sliverappbar](https://user-images.githubusercontent.com/25891817/102865715-2f872c80-445c-11eb-9315-020b444d9ce5.gif)

**Comment by kmanadkat** [comment] 2021-06-27 07:26
> If anyone wants to refer a working code sample for whatsapp type floating sliverappbar with tabs, here it is -> https://dartpad.dev/0955dcf876ba24619b86d49ec50788cc?
> ![ezgif](https://user-images.githubusercontent.com/25891817/102871405-67926d80-4464-11eb-9af5-9f2e0daf6e73.gif)

Your solution doesnot solve : 
> Content gets hidden when you change tabs – This can probably be solved using the SafeArea widget. (See GIF here)

Keep the Text at top instead at center and you will see the issue

**Comment by kmanadkat** [comment] 2021-06-27 10:11
I tried to address all the points in [this](https://stackoverflow.com/a/68149981/7475099) stackoverflow answer. Thanks to beautiful [Flutter docs for NestedScrollView](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html#widgets.NestedScrollView.1)

**Comment by rashmisridar** [comment] 2021-07-20 05:01
@kmanadkat Tried your dart pad example. 
Getting this error https://stackoverflow.com/questions/58339739/nestedscrollview-issue-throwing-error-when-switching-between-two-screens . Do you have any idea about this? Thanks .

**Comment by kmanadkat** [comment] 2021-07-20 16:05
> @kmanadkat Tried your dart pad example.
> Getting this error https://stackoverflow.com/questions/58339739/nestedscrollview-issue-throwing-error-when-switching-between-two-screens . Do you have any idea about this? Thanks .

I rechecked the dartpad code, seems it is still working. Have you tried any of the solutions mentioned in stackoverflow link you shared?

I have not encountered this error before. Perhaps, data to be populated in list is empty maybe that is why you are seeing that error. Preload the data before somewhere in Model and then load the widget with data from Model.

**Comment by rashmisridar** [comment] 2021-07-21 07:00
Solved the issue with the help of this code
body: TabBarView(controller: _tabController, children: [
            CustomScrollView(
              controller: _scrollController,
              slivers: <Widget>[SliverToBoxAdapter(child: Container())],
            ),
            CustomScrollView(
              controller: _scrollController,
              slivers: <Widget>[SliverToBoxAdapter(child: Container())],
            ),
            CustomScrollView(
              controller: _scrollController,
              slivers: <Widget>[SliverToBoxAdapter(child: Container())],
            ),
          ]),
          
          Referred from link https://github.com/flutter/flutter/issues/51205
          
          Now how to hide the silver app bar title?  Do you have any idea about this? Thanks.
