### ISSUE TITLE
[image_picker] preferredCameraDevice is ignored on Android (Native and Web)

### ISSUE THREAD

**Issue by EmanueleVinci** [flutter/flutter#105780] opened 2022-06-10 14:55 UTC
**Steps to reproduce**
- Install latest image_picker: ^0.8.5+3
- Calling ImagePicker.pickImage opens camera in front mode, but I call it passing CameraDevice.rear.

**Code example**
`await ImagePicker.pickImage(
        source: ImageSource.camera,
        imageQuality: 60,
        preferredCameraDevice: CameraDevice.rear);`

**Comment by huycozy** [comment] 2022-06-13 04:35
Hi @EmanueleVinci
From my understanding, you are mentioning `front facing (CameraDevice.front)` and would like to pass `preferredCameraDevice: CameraDevice.front` to `pickImage()`, right?

**Comment by EmanueleVinci** [comment] 2022-06-13 06:42
> Hi @EmanueleVinci From my understanding, you are mentioning `front facing (CameraDevice.front)` and would like to pass `preferredCameraDevice: CameraDevice.front` to `pickImage()`, right?

It wasn't clear, sorry. Edited

**Comment by huycozy** [comment] 2022-06-13 12:52
@EmanueleVinci 

> Calling ImagePicker.pickImage opens camera in front mode, but I call it passing CameraDevice.rear.

So confusing here. 

The default `preferredCameraDevice` is `CameraDevice.rear`:
https://github.com/flutter/plugins/blob/40c991a710c5d458018753550275e5d8a578ddfa/packages/image_picker/image_picker/lib/image_picker.dart#L208

```dart
Future<XFile?> pickImage({
    required ImageSource source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    CameraDevice preferredCameraDevice = CameraDevice.rear,
  })
```

As my understanding, you are trying to pass `CameraDevice.front` to `preferredCameraDevice`, right?
But when the camera opened, the `rear` camera opened instead of `font` camera, right?

Providing an image for more detail:

![main-qimg-2ece30d04b83a1a7b62d17290b5a442d-lq](https://user-images.githubusercontent.com/104349824/173357748-35de4430-9a57-4445-aadd-d2645e500cf4.jpeg)

**Comment by EmanueleVinci** [comment] 2022-06-13 13:59
@huycozy No, I want to open the rear camera, but I can't. Doesn't matter what I pass, it always opens the front camera. I'm testing on a Galaxy s10 with Android 12

**Comment by huycozy** [comment] 2022-06-14 02:42
@EmanueleVinci, thanks for clarifying.
I found that there's an issue addressing the case you described #96114, and see https://github.com/flutter/flutter/issues/96114#issuecomment-1005435481 that explained the cause of this.

Forward information:
https://github.com/flutter/plugins/blob/6255da36c61438b96b23aabab09a163f8152c80f/packages/image_picker/image_picker/lib/image_picker.dart#L49

>   /// Defaults to [CameraDevice.rear]. Note that Android has no documented parameter for an intent to specify if
  /// the front or rear camera should be opened, this function is not guaranteed
  /// to work on an Android device.

Closing this issue as above explanation. Thanks!

**Closed by huycozy** 2022-06-14 02:42 UTC
Labels: in triage
