### ISSUE TITLE
if the MediaData textScaleFactor is bigger than 1.0, then the datepicker will overflower

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#23286] opened 2018-10-19 08:21 UTC
_Originally posted by @CaiJingLong in 
https://github.com/flutter/flutter/issues/20171#issuecomment-431284368

flutter doctor -v
----
```
flutter doctor -v
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.10.0 at /Users/caijinglong/Library/Flutter/flutter
    • Framework revision d954ae6850 (10 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/caijinglong/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/caijinglong/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-10-19 08:47
Please add the output of `flutter doctor -v`.

**Comment by gabrc52** [comment] 2018-12-11 02:55
Duplicate of #20171

**Comment by zoechi** [comment] 2018-12-11 06:13
Duplicate of #20171

**Closed** 2018-12-11 06:13 UTC
Labels: f: date/time picker, framework
