### ISSUE TITLE
Textfield does not respect TextInputFormatter

### ISSUE THREAD

**Issue by coder-Aayush** [flutter/flutter#107223] opened 2022-07-07 10:33 UTC
## Issue

Hi, I am using `TextField` and some Input Formatters for validating the regex. When I type the letters then it automatically changes to some other number instead of preventing to input. I have attached video recording for clear reference. 

## Sample Code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: FieldClass(),
    );
  }
}

class FieldClass extends StatelessWidget {
  const FieldClass({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(30.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('TextField Demo'),
            TextField(
              inputFormatters: [
                FilteringTextInputFormatter.deny(RegExp(r'[A-Za-z]')),
                FilteringTextInputFormatter.allow(
                    RegExp(r'(0|[1-9][0-9]?|150)$')),
              ],
              keyboardType: TextInputType.number,
            ),
          ],
        ),
      ),
    );
  }
}
```

## Video Reference 

https://user-images.githubusercontent.com/47755613/177753678-cd8f95a0-1fc2-491d-9492-6f71c68c7317.MP4

**Comment by maheshmnj** [comment] 2022-07-07 12:44
Hi @coder-Aayush, Thanks for filing the issue. I am able to repro the issue on the latest stable and the master channel.

https://user-images.githubusercontent.com/31410839/177776300-97599613-e673-411e-a307-66676545bd72.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1494, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1494 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 829bddf616 (3 hours ago), 2022-07-04 03:49:08 -0400
    • Engine revision e78ed7f1c9
    • Dart version 2.18.0 (build 2.18.0-251.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by coder-Aayush** [comment] 2022-07-08 06:30
@LongCatIsLooong I changed the range my regex which is between 1 to 150, still facing same issue if I typed number greater than 150.
regex: `RegExp(r'(1|[1-9][0-9]?|150)$'))`

**Comment by LongCatIsLooong** [comment] 2022-07-08 23:39
Ah I see what you are trying to do. `FilteringTextInputFormatter` doesn't actually prevent the user from entering banned patterns. It only replaces banned patterns with the supplied `replacementString` (by default an empty string), such that when someone pastes a paragraph into the input field only the banned words will be filtered out, instead of rejecting the paragraph as a whole. 
IOW, `FilteringTextInputFormatter` is not the right `TextInputFormatter` for the job.

**Comment by LongCatIsLooong** [comment] 2022-07-08 23:42
`TextInputFormatter` is simply a wrapper around a function of type `(TextEditingValue, TextEditingValue) => TextEditingValue`. You can simply create a custom `TextInputFormatter` that does what you want, i.e., return the `oldValue` if the pattern doesn't match.

**Comment by LongCatIsLooong** [comment] 2022-07-08 23:46
Duplicate of https://github.com/flutter/flutter/issues/78100

**Closed by LongCatIsLooong** 2022-07-08 23:46 UTC
Labels: a: text input, framework, f: material design, documentation, has reproducible steps, found in release: 3.0, found in release: 3.1
