### ISSUE TITLE
kDebug mode is always return false in production mode ios flutter

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#98851] opened 2022-02-21 05:58 UTC

**Comment by danagbemava-nc** [comment] 2022-02-21 10:58
This is working as intended. 

Kindly see https://api.flutter.dev/flutter/foundation/kDebugMode-constant.html for more information. 

Closing as this is WAI.

Thank you

**Closed by danagbemava-nc** 2022-02-21 10:58 UTC
Labels: in triage
