### ISSUE TITLE
textInputAction not available for keyboardType:TextInputType.number

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#22854] opened 2018-10-09 08:38 UTC
Is there no possibility to display a done button (textInputAction: TextInputAction.done) for a number input (keyboardType: TextInputType.number)?

**Comment by Xavjer** [comment] 2018-10-09 13:10
I just tried with current master and beta branch on an android device and was able to display the done button (Also tried with others like newLine)... in addition it is the default textInputAction used.

Could you please state which version you are using and attach a screenshot?

**Comment by YAPPDEF** [comment] 2018-10-09 13:18
@Xavjer thanks!
Sorry I didn't test it on Android. The issue happens on iOS for me (emulator iPhone XS w/ iOS 12.0) 

`[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale de-CH)`

```
TextField(
        ...
        keyboardType: TextInputType.number,
        textInputAction: TextInputAction.done, 
);
```

![textinputaction](https://user-images.githubusercontent.com/40127061/46671826-1aed4f80-cbd6-11e8-8214-c344509d410f.png)

**Comment by Xavjer** [comment] 2018-10-10 07:04
Okay then,

On iOS, the done action is not supported for number inputs, even in native applications.

In native applications, you would normally use an `inputAccessoryView` and add an `UIToolBar` to it, containing the done button. [StackOverflow Link with this example](https://stackoverflow.com/questions/584538/how-to-show-done-button-on-iphone-number-pad/11382044)

This widget does not exist yet for flutter, but is on the roadmap somewhere.

This is also an issue for multiline textFields, as you have no way to insert a newLine and having a done button at the same time.

For your purpose, it looks as if you have to enter a 6digit code, you can therefore:
a. Automatically continue when the last digit was entered. 
b. Implement a gesture recognizer for a tab outside of the number keypad to close it
c. Write an own ToolBar that automatically pops-up when you open the number keypad

**Comment by YAPPDEF** [comment] 2018-10-10 07:20
Thanks @Xavjer I just checked https://github.com/flutter/flutter/issues/12220 (sorry just saw it now)

I already implemented a.), but it would be nice to have a done button. Let's see when or if iOS will support this out-of-the-box.. 😄

**Comment by imranismail** [comment] 2019-05-29 11:48
This affects old android keyboards as well

**Comment by MsXam** [comment] 2019-08-26 11:33
Is there any update to this, i.e a roadmap of when/if InputAccessoryView  widget will be provided ? We have some screens whereby using Keyboard Actions plugin doesnt work and there is no way to have **NEWLINE** and ability to close the on screen keyboard. We cannot provide any gestures for the user to tap outside as on certain screens, there is just a series  multiline textfields which can grow depending on the content and thus no way to dismiss the keyboard ...

**Comment by thomashbailey** [comment] 2019-10-09 18:14
The https://pub.dartlang.org/packages/keyboard_actions is the best solution I have seen so far but the animation is janky.  Is there a way to have the view that contains the done button appear at the same rate and animation curve as the keyboard.  I would love to use this library but my skin crawls everyone time I see it.

**Comment by diegoveloper** [comment] 2019-10-09 18:18
I'm going to continue working on this package these days, anyway, PRs are open :)

**Comment by maks** [comment] 2019-12-02 02:54
This seems to be a duplicate of #12220

**Comment by justinmc** [comment] 2020-04-22 15:42
It does look like this is a duplicate of https://github.com/flutter/flutter/issues/12220. It looks like that one was closed because there's no way to do this in native iOS right now.

**Closed by justinmc** 2020-04-22 15:42 UTC
Labels: a: fidelity, a: text input, framework, platform-ios
