### ISSUE TITLE
iOS Devices, iOS 13.4, WebView does not response to Gesture Recognizer after several horizontal scrolls

### ISSUE THREAD

**Issue by binjiayou66** [flutter/flutter#57489] opened 2020-05-18 13:44 UTC
```console
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Applications/flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andy/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • xxxxxxxx • ios • iOS 13.4

```

``` dart
class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    final url = 'https://item.m.jd.com/product/31611781966.html';
    return Scaffold(
      appBar: AppBar(
        title: Text('WebView Demo'),
      ),
      body: WebView(
        initialUrl: url,
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
  }
}
```

The codes shown above load banner pictures scrolling horizontally. After running on iOS real devices and scroll the banner pictures horizontally several times, the whole page stops responding to the user's operation.

**Comment by iapicca** [comment] 2020-05-18 14:51
Hi @binjiayou66 
the url loads on android doesn't work on ios

<details>
  <summary>yaml</summary>

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.21
```

</details>

<details>
  <summary>logs</summary>

```bash
[        ] Waiting for observatory port to be available...
[+3298 ms] Observatory URL on device: http://127.0.0.1:49224/MVXTFv70J4E=/
[  +32 ms] Connecting to service protocol: http://127.0.0.1:49224/MVXTFv70J4E=/
[ +300 ms] Successfully connected to service protocol: http://127.0.0.1:49224/MVXTFv70J4E=/
[   +1 ms] Waiting for iPhone 8 to report its views...
[  +17 ms] Waiting for iPhone 8 to report its views... (completed in 16ms)
[  +40 ms] DevFS: Creating new filesystem on the device (null)
[  +34 ms] DevFS: Created new filesystem on the device
(file:///Users/nevercode/Library/Developer/CoreSimulator/Devices/D5F70F31-B488-4454-9539-320B5551D92A/data/Containers/Data/Application/188F8CC2-F2F8-4716-A625-BAF9D47ED25C/tmp/st
ablePjYdSA/stable/)
[   +3 ms] Updating assets
[ +202 ms] Syncing files to device iPhone 8...
[   +4 ms] Scanning asset files
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:stable/main.dart 91c3fa3e-270d-4c72-9f60-b254927af843
[        ] <- 91c3fa3e-270d-4c72-9f60-b254927af843
[ +140 ms] Updating files
[ +125 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 8... (completed in 281ms)
[   +3 ms] Synced 0.9MB.
[   +2 ms] <- accept
[   +4 ms] Connected to _flutterView/0x7fafcb83f020.
[   +4 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +3 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:49224/MVXTFv70J4E=/
[ +599 ms] [VERBOSE-2:platform_view_layer.cc(24)] Trying to embed a platform view but the PrerollContext does not support embedding
[   +6 ms] [VERBOSE-2:platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ +287 ms] [VERBOSE-2:platform_view_layer.cc(24)] Trying to embed a platform view but the PrerollContext does not support embedding
[   +2 ms] [VERBOSE-2:platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding

```

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.90, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.19.0-2.0.pre.90 at /Users/nevercode/development/flutter_master
    • Framework revision f64f6e2b6b (5 hours ago), 2020-05-18 05:42:01 -0400
    • Engine revision 2bd71fb60a
    • Dart version 2.9.0 (build 2.9.0-9.0.dev b560016446)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • iPhone 8   • D5F70F31-B488-4454-9539-320B5551D92A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by binjiayou66** [comment] 2020-05-19 01:13
> Hi @binjiayou66
> the url loads on android doesn't work on ios
> 
> yaml
> logs
> doctor
> thank you


The problem you mentioned can be solved through the following operation：

Currently apps need to opt-in for the UIViews embedding preview on iOS by adding a boolean property to the Info.plist (key=io.flutter.embedded_views_preview value=YES).

**Comment by binjiayou66** [comment] 2020-05-19 01:18
Can someone provide some solutions?

**Comment by hughgr** [comment] 2020-05-19 03:55
samething happened here.  webview freezed after serveral scrolls on IOS 13.4

I’m strongly confused that how FL webview passed QA test considering this is an easy reproduced bug

**Comment by awkwardsky** [comment] 2020-05-20 07:21
also have same issue. 
webview freezed after serveral scrolls on ios 13.4.1
but it works fine on ios 13.3

**Comment by a251115100** [comment] 2020-05-21 11:03
some vertical scrolls also can make webview freezed,on ios 13.5

**Comment by cyanglaz** [comment] 2020-05-21 22:53
possibly related to https://github.com/flutter/flutter/issues/53490

**Comment by qinglongy** [comment] 2020-05-23 05:32
> ## also have same issue.
> webview freezed after serveral scrolls on ios 13.4.1
> but it works fine on ios 13.3
> ios 13.5 , It's still not working

me too!!! in android work fine,but in ios 13.4.1-13.5 not working.

**Comment by gcemcw4** [comment] 2020-05-29 15:11
same problem

**Comment by jiangyubao** [comment] 2020-06-04 07:53
me too

**Comment by constantinescur** [comment] 2020-06-04 08:33
This is a really serious problem...

**Comment by constantinescur** [comment] 2020-06-04 08:34
That's a critical issue.

**Comment by jiangyubao** [comment] 2020-06-05 11:54
how to resolve this problem ?

**Comment by cyanglaz** [comment] 2020-06-24 18:59
Closing this as it is a duplicate of https://github.com/flutter/flutter/issues/53490

**Closed by cyanglaz** 2020-06-24 18:59 UTC
Labels: P4, found in release: 1.19, has reproducible steps, p: first party, p: webview, platform-ios, plugin
