### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by NaynaAsodariya** [flutter/flutter#155398] opened 2024-09-19 09:34 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008120-0014241902DB401E --start-paused --dart-define=flavor=dev --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/asodariya/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/asodariya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Users/asodariya/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • Nayna Asodariya’s iPhone (mobile) • 00008120-0014241902DB401E • ios    • iOS 17.6.1 21G93
    • Mac Designed for iPad (desktop)   • mac-designed-for-ipad     • darwin • macOS 15.0 24A335 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
### Plugins
app_settings-5.1.1
background_downloader-8.5.5
connectivity_plus-6.0.5
cronet_http-1.3.2
cupertino_http-1.5.1
device_info_plus-10.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-11.3.2
firebase_analytics_web-0.5.10+1
firebase_core-3.5.0
firebase_core_web-2.18.1
firebase_crashlytics-4.1.2
firebase_messaging-15.1.2
firebase_messaging_web-3.9.1
firebase_performance-0.10.0+7
firebase_performance_web-0.1.7+1
firebase_remote_config-5.1.2
firebase_remote_config_web-1.7.1
flutter_background_service-5.0.10
flutter_background_service_android-6.2.7
flutter_background_service_ios-5.0.3
flutter_blue_plus-1.32.12
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_native_splash-2.4.1
flutter_pcm_sound-1.2.2
flutter_plugin_android_lifecycle-2.0.22
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
google_sign_in-6.2.1
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
image_editor-1.5.1
image_editor_common-1.1.2
image_editor_ohos-0.0.9
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
intercom_flutter-8.1.3
intercom_flutter_web-1.1.2
jni-0.10.1
network_info_plus-6.0.1
open_settings_plus-0.3.3
opus_flutter-3.0.3
opus_flutter_android-3.0.1
opus_flutter_ios-3.0.1
opus_flutter_web-3.0.3
opus_flutter_windows-3.0.0
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
qr_code_scanner-1.0.1
share_plus-10.0.2
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.1
video_player_android-2.7.3
video_player_avfoundation-2.6.1
video_player_web-2.3.2
webview_flutter-4.9.0
webview_flutter_android-3.16.7
webview_flutter_wkwebview-3.15.0

**Comment by danagbemava-nc** [comment] 2024-09-19 10:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-09-19 10:03 UTC
Labels: in triage
