### ISSUE TITLE
Setting composing range to TextRange.collapsed(0) on macOS breaks text input

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#64741] opened 2020-08-27 18:32 UTC
## Steps to Reproduce

1. Clone https://github.com/memspace/zefyr.git
2. Go to `packages/zefyr/example` and run with `flutter run -d macOS`
3. Click on "Embedded in a form" example
4. In the middle multiple field (that's ZefyrEditor) type in `abc` and press `Enter`

**Expected results:** 

`Enter` should've added a new line

**Actual results:** 

No new line appears. 
While debugging I noticed that in my `TextInputClient.updateEditingValue` I get unexpected control characters when pressing `Enter` (`13` (`\r`) instead of `10` (`\n`)), `Delete` (adds `8` code unit to the text) and arrow keys also modify the text itself instead of changing selection.

I scanned through the standard EditableTextState implementation and couldn't find anything that would indicate any issues in the way I set up input connection or handle updates.

When I use regular multiline TextField everything looks correct there and no special characters are present.

In the attached logs at the very end I have some `print`ed statements for the raw text code units I receive from the platform side.

<details>
  <summary>Logs</summary>

Logs were too big for a Github comment, so here is Gist:
https://gist.github.com/pulyaevskiy/5a1b28545994f0dae73185ba476c5929

```
$ flutter analyze
Analyzing example...
No issues found! (ran in 3.2s)
```

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.93, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.0-2.0.pre.93 at /Users/anatoly/Projects/flutter
    • Framework revision f35a8b7470 (14 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/anatoly/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/anatoly/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-29" "build-tools;28.0.3"
      or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 1 category.
```

</details>

**Comment by pulyaevskiy** [comment] 2020-08-28 04:08
I found a fix for my issue - I had hardcoded initial value for `composing` range as `0` which was causing this weird behavior in the text input plugin. After setting it to `-1` everything works as expected.

Even though my issue is resolved it still seems like something can be improved on the Flutter side of things so I'll keep this open. At least adding validation for `composing` range to prevent this from happening. I'm still not sure why would this have such a weird impact on the plugin's behavior.

**Comment by markusaksli-nc** [comment] 2020-08-28 09:17
Hi @pulyaevskiy 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to demonstrate this issue? The example contains a lot of ancillary code from this third-party package.
Thank you

**Comment by pulyaevskiy** [comment] 2020-08-28 16:33
Sure, I was able to reproduce this with standard TextField.

Steps:

1. Create a new app with `flutter create`
2. Replace contents of `main.dart` with the below snippet
3. Run the app in macOS
4. Press "Set composing to 0" button
5. Type something in the input. Try pressing `Enter` and `Delete` keys.

Expected result: `Enter` adds a new line. `Delete` removes a character.
Actual result: `Enter` adds a `\r` and `Delete` adds some other special character to the `text` value.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                controller: _controller,
                maxLines: 4,
              ),
              SizedBox(height: 16),
              RaisedButton(
                child: Text('Set composing to 0'),
                onPressed: () {
                  _controller.value = _controller.value
                      .copyWith(composing: TextRange.collapsed(0));
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-08-31 08:17
Hi @pulyaevskiy 
Thanks for providing a code sample and steps to reproduce the issue 

I can reproduce the issue but there are no special characters when the `Delete `  key is pressed, it just doesn't delete and `Enter` doesn't add a new line 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision ce40de69b7 (11 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.139, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.139 at C:\Code\flutter_master
    • Framework revision c0ea00ed3f (3 hours ago), 2020-08-30 22:20:16 -0700
    • Engine revision bada9fc5f3
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by pulyaevskiy** [comment] 2020-08-31 20:04
If you `print` the editing `text.codeUnits` you should be able to see it.

**Comment by stuartmorgan** [comment] 2020-09-14 14:43
macOS apparently considers an empty composing range (as distinct from an invalid composing range, which -1 represents in Flutter) to be an active composition, and adjusts key handling accordingly.

@gspencergoog I'm not sure how composition is handled in Flutter exactly. Should an empty range and an invalid range be considered the same thing, or is this actually WAI?

**Comment by cbracken** [comment] 2020-10-20 00:36
@stuartmorgan @gspencergoog Empty composing regions make sense on desktop -- and probably on iOS too when working with a physical keyboard. You can imagine the case where you start composing, type in a character, realise it was a typo and hit backspace. Your composing region will be empty, but they're still composing. We should probably verify this works on all platforms (done for Linux GTK embedder).

**Comment by cbracken** [comment] 2020-10-20 00:37
If I get some time after Windows, I could take a look at this -- or maybe @justinmc if he has time?

**Comment by stuartmorgan** [comment] 2020-10-20 12:43
> Empty composing regions make sense on desktop

The described behavior here is WAI then, right? E.g., delete shouldn't do anything in an active, empty compose.

**Comment by cbracken** [comment] 2020-10-22 00:54
> The described behavior here is WAI then, right? E.g., delete shouldn't do anything in an active, empty compose.

Alright did some testing and have the behaviour. 

Here's the setup:
1. Begin typing in a new composing range; characters are entered.
2. Press backspace to get the composing range down to empty again.

At this point you're still composing.
* If you type a character, it is entered into the composing range. 
* If you press backspace or delete, the compose is aborted and the delete/backspace behaves as though you weren't composing.

Worth noting that so long as a single character remains in the composing range, hitting delete at the end or backspace at the start is a no-op and composing is not aborted. Once you

Just veriried and the Linux embedder currently does this correctly.

**Comment by justinmc** [comment] 2020-10-26 17:00
I'll add this to my list as well, but feel free to jump on it if I haven't assigned myself.

**Comment by a-wallen** [comment] 2022-08-05 23:37
This thread is composed of three different issues with reproducible steps 
1. https://github.com/flutter/flutter/issues/64741#issuecomment-682840033
2. https://github.com/flutter/flutter/issues/64741#issuecomment-714091119
3. https://github.com/flutter/flutter/issues/64741#issuecomment-944622305

**Comment by a-wallen** [comment] 2022-08-05 23:39
- [ ] @pulyaevskiy the steps that you provided in https://github.com/flutter/flutter/issues/64741#issuecomment-682840033 are no longer reproducible. Unless you object, I will consider the original issue resolved.

**Comment by a-wallen** [comment] 2022-08-05 23:42
- [ ] @justinmc the bug you provided [here](https://github.com/flutter/flutter/issues/64741#issuecomment-944622305) looks like a dupe https://github.com/flutter/flutter/issues/91859. If so, it'll be fixed by https://github.com/flutter/flutter/issues/30725.

**Comment by a-wallen** [comment] 2022-08-06 00:12
- [ ] @cbracken the steps provided are no longer able to reproduce the behavior that you mentioned. It must have been fixed by a PR that I can't find.

**Closed by a-wallen** 2022-08-06 00:12 UTC
Labels: a: text input, engine, platform-mac, a: desktop, has reproducible steps, P4, found in release: 1.22
