### ISSUE TITLE
After I added google_maps_flutter: ^0.5.24 to my pubspec.yaml file I got this message "Couldnt read LocalFile .....Please Verify that this file has read permission and try again.

### ISSUE THREAD

**Issue by berloop** [flutter/flutter#51117] opened 2020-02-20 13:25 UTC
So I added latest google_maps_flutter package to my project and I got this message and an exit code of 1:  **"Couldn't read file LocalFile: 'C:\Users\administrator\Documents\flutter_windows_v1.12.13+hotfix.7-stable\flutter\. pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0. 5\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt' even though it exists. Please verify that this file has read permission and try again.**

Heres my flutter doctor summary Output
`$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.42.1)
[!] Connected device
    ! No devices available

`

**Comment by TahaTesser** [comment] 2020-02-20 13:32
Could be related to [#47933](https://github.com/flutter/flutter/issues/47933)

**Comment by TahaTesser** [comment] 2020-02-20 13:40
Hi @berloop 
Could you please try possible [Solution](https://github.com/flutter/flutter/issues/47933#issuecomment-573631022)?
Thank you

**Comment by berloop** [comment] 2020-02-20 13:47
> Hi @berloop
> Could you please try possible Solution?
> Thank you
>Im working on it, Thank you

**Comment by berloop** [comment] 2020-02-20 14:47
The proposed solution doesn't work, am still getting the error

**Comment by TahaTesser** [comment] 2020-02-20 14:51
Hi @berloop 
There is a already duplicate of this as mention [above](https://github.com/flutter/flutter/issues/51117#issuecomment-589024011)
Please follow that issue and put a thumbs up there 
Thank you

**Closed by TahaTesser** 2020-02-20 14:51 UTC
