### ISSUE TITLE
unable to access device tokens in firebase cloud messaging

### ISSUE THREAD

**Issue by girish4474** [flutter/flutter#58309] opened 2020-05-30 11:02 UTC
I was able to access the device tokens for sending a notification when they are in the main collection. But unable to access them when they are inside a subcollection can anyone help me with that?

it's working fine for a collection 
![Screenshot (175)](https://user-images.githubusercontent.com/35487674/83326516-56003300-a292-11ea-8279-07d8f73de2e9.png)

But getting issue when it is in sub collection
![Screenshot (176)](https://user-images.githubusercontent.com/35487674/83326518-57316000-a292-11ea-816a-b1d03059351b.png)

**Comment by iapicca** [comment] 2020-06-01 09:55
Hi @girish4474 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-01 09:55 UTC
Labels: created via support template
