### ISSUE TITLE
InputDecoration prefixIcon and suffixIcon disappear

### ISSUE THREAD

**Issue by mo5tone** [flutter/flutter#37690] opened 2019-08-06 13:46 UTC
## Steps to Reproduce

1. add a TextField that hold a prefix icon without color property to AppBar as title;
2. when tap TextField, the prefix icon disappeared;
3. set a color to icon or make TextField unfocused, the prefix icon appear again.
```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        primaryColor: Colors.blue,
      ),
      home: DemoPage(),
    );
  }
}

class DemoPage extends StatefulWidget {
  @override
  _DemoPageState createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  bool _isSearching;
  @override
  void initState() {
    super.initState();
    _isSearching = false;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: _isSearching
            ? TextField(
                decoration: InputDecoration(
                  prefixIcon: Icon(Icons.search),
                  border: InputBorder.none,
                ),
              )
            : Text('Demo Page'),
        actions: [
          IconButton(
            icon: Icon(_isSearching ? Icons.close : Icons.search),
            onPressed: () {
              setState(() {
                _isSearching = !_isSearching;
              });
            },
          ),
        ],
      ),
      body: Container(),
    );
  }
}
```
![giphy](https://user-images.githubusercontent.com/8422976/62544369-38408800-b892-11e9-9cf3-4bdb130fa481.gif)

## Logs

No error logs shown in console. 

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale
    en-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/menjiefu/Library/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/menjiefu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • B98F09B0-5F8A-479D-8A61-6FC5F1219C9A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by BaderEddineOuaich** [comment] 2019-08-06 14:00
Hi there, try to switch the whole AppBar for both states. here is an example:
<pre>
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        primaryColor: Colors.blue,
      ),
      home: DemoPage(),
    );
  }
}

class DemoPage extends StatefulWidget {
  @override
  _DemoPageState createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  bool _isSearching;
  @override
  void initState() {
    super.initState();
    _isSearching = false;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _isSearching ?
<strong> AppBar(
        leading: IconButton(
            icon: Icon(Icons.close),
            onPressed: ()
            {
               setState(()=> _isSearching = false);
            },
        ),
        title: Container(
          child: TextField(
            autofocus: true,
            onChanged: (String value)=>print("Query: $value"),
            style: TextStyle(
              fontSize: 18,
            ),
            decoration: InputDecoration(
              hintText: "Search...",
              border: InputBorder.none,
              hintStyle: TextStyle(
                color: Colors.white.withAlpha(100),
              ),
            ),
          ),
        ),
  )
            :
 AppBar(
       title:Text('Demo Page'),
        actions: [
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () {
              setState(() {
                _isSearching = !_isSearching;
              });
            },
          ),
        ],
      ),
</strong>
      body: Container(),
    );
  }
}
</pre>
<hr>
<em>Hope it helps. good day!</em>
<hr>

**Comment by mo5tone** [comment] 2019-08-06 14:36
> Hi there, try to switch the whole AppBar for both states. here is an example:
> 
> class App extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Demo',
>       theme: ThemeData(
>         primaryColor: Colors.blue,
>       ),
>       home: DemoPage(),
>     );
>   }
> }
> 
> class DemoPage extends StatefulWidget {
>   @override
>   _DemoPageState createState() => _DemoPageState();
> }
> 
> class _DemoPageState extends State {
>   bool _isSearching;
>   @override
>   void initState() {
>     super.initState();
>     _isSearching = false;
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: _isSearching ?
> ** AppBar(
>         leading: IconButton(
>             icon: Icon(Icons.close),
>             onPressed: ()
>             {
>                setState(()=> _isSearching = false);
>             },
>         ),
>         title: Container(
>           child: TextField(
>             autofocus: true,
>             onChanged: (String value)=>print("Query: $value"),
>             style: TextStyle(
>               fontSize: 18,
>             ),
>             decoration: InputDecoration(
>               hintText: "Search...",
>               border: InputBorder.none,
>               hintStyle: TextStyle(
>                 color: Colors.white.withAlpha(100),
>               ),
>             ),
>           ),
>         ),
>   )
>             :
>  AppBar(
>        title:Text('Demo Page'),
>         actions: [
>           IconButton(
>             icon: Icon(Icons.search),
>             onPressed: () {
>               setState(() {
>                 _isSearching = !_isSearching;
>               });
>             },
>           ),
>         ],
>       ),
> **
>       body: Container(),
>     );
>   }
> }
> _Hope it helps. good day!_

thx for reply. but ur demo code is just another way to fix the issue temporarily.
my focus is InputDecoration.prefix/suffixIcon not works as expected without specified color.

**Comment by jessiwu** [comment] 2020-02-06 10:14
same issue here

**Comment by Eimji** [comment] 2020-02-20 08:52
Use suffix (or prefix) instead of suffixIcon (or prefixIcon) ! It works for my application.

**Comment by dipbhi** [comment] 2020-04-24 11:36
I noticed issue. Setting color for the icon widget seems to be a good workaround.

**Comment by TahaTesser** [comment] 2020-05-08 14:12
Issue still exist 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-13.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 8fbfe1cfbf (35 hours ago), 2020-05-06 17:36:01 -0700
    • Engine revision d6aa099de7
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by he0119** [comment] 2020-11-11 16:18
Is there any update?

**Comment by Amitpatil215** [comment] 2020-12-06 20:24
By default ```PrefixIcon``` using ```themeData.primaryColor``` when focused.
https://github.com/flutter/flutter/blob/1aafb3a8b9b0c36241c5f5b34ee914770f015818/packages/flutter/lib/src/material/input_decorator.dart#L1998-L1999

as reproducible steps provided app bar also uses ```primaryColor``` as a ```backgroundColor```. That's the reason on focusing text field ```prefixIcon``` is not visible.

CC: @HansMuller 
Considering ```themeData.primaryColorDark``` instead of ```themeData.primaryColor``` may resolve this issue. Not sure what should be used in that place as we migrating according to [Theme System Updates](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.2hl3s1i2nq6o) .

**Comment by pedromassangocode** [comment] 2021-01-13 13:57
Issue is still valid on latest master and stable channel.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.313, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.313 at /Users/pedromassango/Code/flutter_master
    • Framework revision 1cb0a24a46 (8 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-11-29 10:11
Hi everyone, this doesn't look like a bug. 

Since the prefixIcon is using the proper scheme and placing it in a matching color appbar is not ideal. This applies to any widget, not just suffixIcon here.  if you wanna keep the widget in the appbar with matching focused color, customize the color of the icon with MaterialState would be the way to go.

Closing as input decoration for suffixIcon/prefixicon is following material guidelines.

**Closed by TahaTesser** 2021-11-29 10:11 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.26
