### ISSUE TITLE
onTapCancel  how to control it 

### ISSUE THREAD

**Issue by CooolWolf** [flutter/flutter#140208] opened 2023-12-15 09:06 UTC
### Steps to reproduce

onTapCancel always fires before the other gestures. I have no control over when this gesture is executed, and sometimes I don't want it to fire

### Expected results

In a push-and-swipe gesture, onTapDown fires first, then onTapCancel, then onHorizontalDragUpdate. But that's not what I want, I want onTapCancel not to be triggered in this flow, I want onTapDown and then onHorizontalDragUpdate, can I do that in the trigger logic of onTapCancel, Don't just cause onTapCancel to fire because onHorizontalDragUpdate is coming, or can I avoid onTapCancel to fire because onHorizontalDragUpdate in this process

### Actual results

In a push-and-swipe gesture, onTapDown fires first, then onTapCancel, then onHorizontalDragUpdate. But that's not what I want, I want onTapCancel not to be triggered in this flow, I want onTapDown and then onHorizontalDragUpdate, can I do that in the trigger logic of onTapCancel, Don't just cause onTapCancel to fire because onHorizontalDragUpdate is coming, or can I avoid onTapCancel to fire because onHorizontalDragUpdate in this process

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]

 onHorizontalDragUpdate: (details) {
        _controller.updateLeftWidth(index, update4Curr: details.primaryDelta);
        logger.d("onHorizontalDragUpdate ${details.primaryDelta}");
        logger.d("localPosition dx ${details.localPosition.dx}");
      },
      onHorizontalDragEnd: (details) {
        _controller.resetLeftWidth(index);
      },
      onTapDown: (details) {
        _controller.updateLeftWidth(index, update4Dft: details.localPosition.dx);
      },
      onTapUp: (details) {
        _controller.resetLeftWidth(index);
      },
      onTapCancel: () {
          _controller.resetLeftWidth(index);
      },



```

</details>

first ：onTapDown  then：onTapCancel  then：onHorizontalDragUpdate

**Comment by dam-ease** [comment] 2023-12-15 11:20
Thanks for filing this @CooolWolf.
The code sample you provided is incomplete, Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, a single `main.dart` file we can run on our end?

**Comment by moffatman** [comment] 2023-12-15 14:29
onTap* competes with onHorizontalDrag*. So the tap always has to be cancelled before the drag starts. Could you use onHorizontalDragStart instead of onTapDown?

**Comment by CooolWolf** [comment] 2023-12-18 02:26
> Thanks for filing this @CooolWolf. The code sample you provided is incomplete, Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, a single `main.dart` file we can run on our end?

`import 'package:flutter/material.dart';
import 'package:learning_flutter/test/CustomWidthUpdateGesture.dart';

void main() {
 runApp(MyApp());
}

class MyApp extends StatelessWidget {
 @override
 Widget build(BuildContext context) {
   return MaterialApp(
     title: 'Flutter Demo',
     theme: ThemeData(primarySwatch: Colors.blue),
     home: Scaffold(
       appBar: AppBar(title: Text('Flutter Demo Home Page')),
       body: Echo(text: 'hello world'),
     ),
   );
 }
}

class Echo extends StatelessWidget {
 const Echo({
   Key? key,
   required this.text,
   this.backgroundColor = Colors.grey,
 }) : super(key: key);

 final String text;
 final Color backgroundColor;

 @override
 Widget build(BuildContext context) {
   return Center(
     child: Container(
       color: backgroundColor,
       child: 
       // CustomGestureExample(),


       GestureDetector(
         onHorizontalDragUpdate: (details) {
           print("----1");
         },
         onHorizontalDragEnd: (details) {
           print("----2");
         },
         onTapDown: (details) {
           print("----3");
         },
         onTapUp: (details) {
           print("----4");
         },
         onTapCancel: () {
           print("----5");
         },
         child: Container(
           padding: const EdgeInsets.only(bottom: 1.0, top: 1.0),
           child: Row(
             children: [
               Container(
                 width: 300,
                 height: 300,
                 decoration: const BoxDecoration(
                   borderRadius: BorderRadius.only(
                     topRight: Radius.circular(15.0),
                     bottomRight: Radius.circular(15.0),
                   ),
                 ),
                 child: Row(
                   children: const [
                     SizedBox(width: 20, height: 10),
                     // NoteWidget(note, UISpec.colorTextWhite, 24.minSp, 2.0),
                     // SizedBox(width: 10.0, height: height - padding * 2),
                   ],
                 ),
               ),
               Container(
                 width: 20, //手势容错宽度
                 height: 10,
                 color: Colors.transparent,
               )
             ],
           ),

           // color: Colors.red,
         ),
       ),
     ),
   );
 }
}`

This is a demo use case, as you and we talked about, my gesture is press and then drag to the right, and you see the print order is 3,5,1, but in this set of gestures, I don't want to trigger 5, which is Cancel, or I want to control its call

**Comment by CooolWolf** [comment] 2023-12-18 02:34
> onTap* competes with onHorizontalDrag*. So the tap always has to be cancelled before the drag starts. Could you use onHorizontalDragStart instead of onTapDown?
With onHorizontalDragStart, the feature is not good, which means the user experience is not good or even wrong. I think this is not desirable

**Comment by dam-ease** [comment] 2023-12-18 07:57
Thanks for your response @CooolWolf.
According to the docs,

> This is called after [onTapDown], and instead of [onTapUp] and [onTap], if the tap gesture did not win.

This seems to be the respected behaviour, per https://github.com/flutter/flutter/issues/140208#issuecomment-1857973661, can you help with more details on the issues you are facing with `onHorizontalDragStart`?

**Comment by CooolWolf** [comment] 2023-12-18 08:06
> Thanks for your response @CooolWolf. According to the docs,
> 
> > This is called after [onTapDown], and instead of [onTapUp] and [onTap], if the tap gesture did not win.
> 
> This seems to be the respected behaviour, per [#140208 (comment)](https://github.com/flutter/flutter/issues/140208#issuecomment-1857973661), can you help with more details on the issues you are facing with `onHorizontalDragStart`?
In this set of gestures, first press and then swipe to the right, I want to control the trigger logic of OntapCancel, for example, in this set of cases, he does not trigger, all other times need to trigger. I was hoping for something like: onTapDown, onHorizontalDragUpdate would do. I hope that in this set of gestures, I don't trigger onTapCancel

**Comment by dam-ease** [comment] 2023-12-19 07:19
Thanks for your response @CooolWolf 
Seeing that this seems to be working as stated in the documentation, I think this would pass as more of a proposal for a wanted capability. Can you please file a separate issue using the appropriate new issue template and fill out the requested details as to what you are proposing, so that we can address this issue properly?

I'll be closing this as this seems to be working as expected, if you disagree, please comment and I'll reopen this.

Thank you!

**Closed by dam-ease** 2023-12-19 07:19 UTC
Labels: in triage
