### ISSUE TITLE
[iOS] Issue with displayed value in TextField using korean 10 Key keyboard

### ISSUE THREAD

**Issue by LeGoffMael** [flutter/flutter#115739] opened 2022-11-21 05:25 UTC
This issue appears only on iOS devices, android seems to be working just fine.
When using a korean qwerty keyboard there is no problem either.

## Steps to Reproduce

1. Execute `flutter run` on the code sample on an iOS device 
2. Use a korean keyboard of 10 Key type (/Settings/General/Keyboards/Keyboards/Korean/10 Key)
3. Enter in the input those keys, in the order
  a) `ㅂ ㅍ` -> `.` -> `ㅡ` -> `ㅣ` -> `.`, repeat this 2 or 3 times
  b) `ㅇ` -> `ㅣ` -> `ㄴ ㄹ` -> `ㄴ ㄹ` -> `.` -> `ㅣ` -> `ㅅ ㅎ` -> `ㄱ` -> `.` -> `ㅣ` -> `ㅣ`

**Expected results:** 

a) the input should displayed `봐봐`
b) the input should displayed `이렇게`

**Actual results:** 

a) the input display `봐ㅂ봐` (repeating `a)` pattern continuously won't change the input value, `봐ㅂ봐` will always be displayed)
b) the input display `이ㄹ게`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(8),
            child: TextField(),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

There is no logs after the line:
```
[ +338 ms] The Flutter DevTools debugger and profiler on Iphone 13 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:61608/K5tJ83yLHi8=/
```

```
legoffmael@Maels-Mac-mini example_korean_10_key % flutter analyze
Analyzing example_korean_10_key...                              
No issues found! (ran in 1.4s)
```

```
legoffmael@Maels-Mac-mini example_korean_10_key % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-KR)
    • Flutter version 3.3.8 on channel stable at /Users/legoffmael/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/legoffmael/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • SM A716S (mobile)  • R3CN606Q31R               • android-arm64  • Android 12 (API 31)
    • Iphone 13 (mobile) • 00008030-000A19913650802E • ios            • iOS 16.1.1 20B101
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

| issue on iOS |  working fine on Android 12 |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/22376981/202970952-4ffee6cb-de25-4d96-b123-061be5762d3f.mov" /> | <video src="https://user-images.githubusercontent.com/22376981/202971014-b9032ad7-245b-48b9-abdc-c985c385fc76.mp4" />

| issue on iOS | working fine on Android 12 |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/22376981/202971212-2d13f2e9-fe9a-47cd-a566-a3b488bb12a6.MP4" /> | <video src="https://user-images.githubusercontent.com/22376981/202971248-669ae13e-a4b8-40f3-857a-e1027f8daa61.mp4" /> |

**Comment by danagbemava-nc** [comment] 2022-11-21 13:16
Hi @LeGoffMael, I believe this is a duplicate of https://github.com/flutter/flutter/issues/112369.

Kindly follow up in the issue linked above for updates. 

If you disagree, kindly leave a comment below and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2022-11-21 13:16 UTC
Labels: in triage
