### ISSUE TITLE
Official Material Backdrop Widget Support

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#89923] opened 2021-09-11 18:03 UTC
## Use case

Taken from Backdrop "Usage" documentation: "A backdrop is composed of two surfaces: a back layer and a front layer. The back layer displays actions and context, and these control and inform the front layer's content."

## Proposal

Official material documentation on the component [here](https://material.io/components/backdrop).

**Comment by nt4f04uNd** [comment] 2021-09-11 19:31
Duplicate of https://github.com/flutter/flutter/issues/17563

**Closed** 2021-09-11 19:39 UTC
