### ISSUE TITLE
When an organization name has a space, XCode project does not get created properly

### ISSUE THREAD

**Issue by kylehayes** [flutter/flutter#23064] opened 2018-10-14 06:23 UTC
## Steps to Reproduce

1. After opening Visual Studio Code
2. Set your Flutter settings for organization to have a space, such as your full name e.g. Robert Smith
3. Create a new project from the command palette
4. After the project is done being created, debug the project and notice that the below error occurs.

## Logs
```
Launching lib/main.dart on iPhone X in debug mode...
2018-10-13 23:22:12.154 xcodebuild[11057:3072166] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 381. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2018-10-13 23:22:12.155 xcodebuild[11057:3072166] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 381. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2018-10-13 23:22:12.155 xcodebuild[11057:3072166] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Missing ';' on line 381" UserInfo={NSDebugDescription=Missing ';' on line 381}}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/khayes/src/flutter_bug/ios/Runner.xcodeproj cannot be opened because the project file cannot be parsed.
Exit code 74 from: /usr/bin/xcodebuild -list
Exited (sigterm)
```
After some brief investigation, it appears this has to do with a malformed metadata file in the XCode project. Removing the space from the organization fixes the issue and the project can then be built successfully.

**Comment by zoechi** [comment] 2019-02-18 15:59
@DanTup can you reproduce with VSCode?

I created with `flutter create  --org "Robert Smith" flutter_23064_orgname_with_space` and couldn't reproduce any issues.

**Comment by DanTup** [comment] 2019-02-18 16:13
> @DanTup can you reproduce with VSCode?

I cannot. I set org to `my test` and the project seemed to come out fine, and launches without error. It looks like the space was stripped from the org before it was written to any of the files:

<img width="422" alt="screenshot 2019-02-18 at 4 11 38 pm" src="https://user-images.githubusercontent.com/1078012/52963523-ecf3f500-3397-11e9-9f36-b3b55d098441.png">

@kylehayes Are you able to find the org name inside the created files (likely inside the `Runner.xcodeproj` folder) to see what it looks like there?

**Comment by kangwang1988** [comment] 2019-02-18 16:15
Maybe fixed after: https://github.com/flutter/flutter/pull/27471/files

**Comment by DanTup** [comment] 2019-02-18 16:31
Yep, could be. I just tried on stable and it wrote this:

<img width="562" alt="screenshot 2019-02-18 at 4 30 39 pm" src="https://user-images.githubusercontent.com/1078012/52964585-90460980-339a-11e9-9414-c72f6bf96932.png">

I'm not sure why the original code (#27471) didn't handle it, but it is now fixed 👍

**Closed by DanTup** 2019-02-18 16:31 UTC
Labels: severe: crash, tool, ⌺‬ platform-ios
