### ISSUE TITLE
project creating failed

### ISSUE THREAD

**Issue by rifad90** [flutter/flutter#60786] opened 2020-07-02 18:33 UTC
## exception

TemplateException: Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}
                            ^

```
#0      Renderer.visitVariable (package:mustache/src/renderer.dart:101:9)
#1      VariableNode.accept (package:mustache/src/node.dart:45:43)
#2      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#3      List.forEach (dart:core-patch/growable_array.dart:283:8)
#4      Renderer.render (package:mustache/src/renderer.dart:58:13)
#5      Template.render (package:mustache/src/template.dart:40:14)
#6      Template.renderString (package:mustache/src/template.dart:33:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:172:77)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      Template.render (package:flutter_tools/src/template.dart:124:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:623:21)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:546:23)
<asynchronous suspension>
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:397:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#29     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.1282], locale en-US)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at G:\Flutter\flutter
    [32m•[39m Framework revision 68587a0916 (10 months ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\Rifad\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Android Studio (version 4.0)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 47.1.2
    [32m•[39m Dart plugin version 193.7361
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[32m[✓][39m VS Code (version 1.46.1)
    [32m•[39m VS Code at C:\Users\Rifad\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.12.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by thatsenam** [comment] 2020-07-02 19:55
Download Android Studio and install it.

**Comment by stuartmorgan** [comment] 2020-07-02 23:23
Your tree is partially on an old version, and partially on a recent version, which is not a supported configuration.

Duplicate of #43734

**Closed by stuartmorgan** 2020-07-02 23:23 UTC

**Comment by rifad90** [comment] 2020-07-03 08:30
I tried several time. Even I installed android studio once again. But still got same error.

**Comment by thatsenam** [comment] 2020-07-03 08:40
flutter doctor --android-licenses

and make sure your android sdk is located at C:\Users\Rifad\AppData\Local\Android\sdk

**Comment by rifad90** [comment] 2020-07-03 09:39
Thanks guys. After download latest flutter sdk my problem solved. Thanks u all

**Comment by stuartmorgan** [comment] 2020-07-03 13:13
@thatsenam This issue has nothing to do with Android Studio or the Android SDK.

**Comment by thatsenam** [comment] 2020-07-03 13:19
@stuartmorgan Flutter doctor clea
Rly says Android SDK is missing.

**Comment by stuartmorgan** [comment] 2020-07-03 14:44
@thatsenam The Android SDK is not required to run `flutter create`.
