### ISSUE TITLE
[tool_crash] _TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))

### ISSUE THREAD

**Issue by coffeeispower** [flutter/flutter#158467] opened 2024-11-11 18:45 UTC
## Command
```sh
flutter run -d chrome
```

## Logs
_TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))
```console
#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56)
#1      _loadDwdsDirectory (package:flutter_tools/src/isolated/devfs_web.dart:1234:45)
#2      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:270:15)
<asynchronous suspension>
#3      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:860:22)
<asynchronous suspension>
#4      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:328:19)
<asynchronous suspension>
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.4, on NixOS 24.05 (Uakari) 6.6.40, locale ja_JP.UTF-8)
    [32m•[39m Flutter version 3.24.4 on channel stable at /nix/store/zf7xhls5bkwnibp4mzid7ly0d5by7a13-flutter-wrapped-3.24.4-sdk-links
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision nixpkgs000 (55 years ago), 1970-01-01 00:00:00
    [32m•[39m Engine revision db49896cf2
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /nix/store/dabnidpswgpl187s25ag5gayv9ibqr7i-androidsdk/libexec/android-sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_SDK_ROOT = /nix/store/dabnidpswgpl187s25ag5gayv9ibqr7i-androidsdk/libexec/android-sdk
    [32m•[39m Java binary at: /nix/store/zmj3m7wrgqf340vqd4v90w8dw371vhjg-openjdk-17.0.7+7/lib/openjdk/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+7-nixos)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = google-chrome-stable

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 17.0.6
    [32m•[39m cmake version 3.30.4
    [32m•[39m ninja version 1.12.1
    [32m•[39m pkg-config version 0.29.2

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • NixOS 24.05 (Uakari) 6.6.40
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.126

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: nixpkgs000000000000000000000000000000000
### Plugins
package_info_plus-8.1.0
path_provider-2.1.5
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
sentry_flutter-8.9.0

**Comment by huycozy** [comment] 2024-11-12 05:46
Duplicate of https://github.com/flutter/flutter/issues/153238

**Closed by huycozy** 2024-11-12 05:46 UTC
Labels: in triage
