### ISSUE TITLE
Issue while generating apk 

### ISSUE THREAD

**Issue by IamArmaan** [flutter/flutter#70432] opened 2020-11-13 04:36 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_native_web:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/arman/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d0480e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/arman/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d0480e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

* What went wrong:
A problem occurred configuring root project 'flutter_native_web'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
 ```
here is my flutter doctor -v

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.22.2 at /Users/arman/Developer/flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/arman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available
```

**Comment by TahaTesser** [comment] 2020-11-13 09:48
Hi @IamArmaan 
You seem to be missing SDK in your app -> android -> `local.properties` 
Make sure you have locations specified like this
```
sdk.dir=/Users/tahatesser/Code/sdk
flutter.sdk=/Users/tahatesser/Code/flutter
```

If you the problem persists after making changes,  Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by IamArmaan** [comment] 2020-11-13 11:43
hi , i already specified but still issue persist 
sdk.dir=/Users/arman/Library/Android/sdk
flutter.sdk=/Users/arman/Developer/flutter
here is result of flutter build apk --verbose
[ +101 ms] 174 actionable tasks: 153 executed, 21 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task
':flutter_native_web:verifyReleaseResources'.
[        ] > A failure occurred while executing
com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ] 
/Users/arman/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d048
0e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
[   +1 ms] 
/Users/arman/.gradle/caches/transforms-2/files-2.1/a528b13ac93e64cafa3d048
0e2c93207/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/ttcIndex not found.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2m 28s
[ +583 ms] Running Gradle task 'assembleRelease'... (completed in 150.3s, longer
than expected)
[   +3 ms] The built failed likely due to AndroidX incompatibilities in a
plugin. The tool
           is about to try using Jetfier to solve the incompatibility.
[  +11 ms] Building plugin flutter_native_web...
[  +10 ms] Running Gradle task 'assembleAarRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from
/Users/arman/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_
native_web-1.0.3/android/gradlew.
[        ]
/Users/arman/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_
native_web-1.0.3/android/gradlew mode: 33261 rwxr-xr-x.
[   +4 ms] executing:
[/Users/arman/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter
_native_web-1.0.3/android/]
/Users/arman/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_
native_web-1.0.3/android/gradlew
-I=/Users/arman/Developer/flutter/packages/flutter_tools/gradle/aar_init_s
cript.gradle -Pflutter-root=/Users/arman/Developer/flutter
-Poutput-dir=/Users/arman/Desktop/Arman/API/nyletech_driver/build/app
-Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Pfont-subset=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+3830 ms] 
                    > Configure project :
                    WARNING: The option setting 'android.enableR8=true' is
                    experimental and unsupported.
                    The current default is 'false'
                    Consider disabling R8 by removing 'android.enableR8=true'
                    from your gradle.properties before publishing your app.


                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project
                    'flutter_native_web'.
                    > SDK location not found. Define location with sdk.dir in
                    the local.properties file or with an ANDROID_HOME
                    environment variable.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run
                    with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 3s
[   +2 ms] Running Gradle task 'assembleAarRelease'... (completed in 3.8s)
[   +1 ms] 
           > Configure project :
           WARNING: The option setting 'android.enableR8=true' is experimental
and unsupported.
           The current default is 'false'
           Consider disabling R8 by removing 'android.enableR8=true' from your
gradle.properties before publishing your app.
           
[   +1 ms] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'flutter_native_web'.
           > SDK location not found. Define location with sdk.dir in the
local.properties file or with an ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 3s
           
[  +11 ms] "flutter apk" took 155,627ms.
[  +10 ms] The plugin flutter_native_web could not be built due to the issue
above.
[   +4 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      buildPluginsAsAar
(package:flutter_tools/src/android/gradle.dart:848:7)
           #2      _asyncErrorWrapperHelper.errorCallback
           (dart:async-patch/async_patch.dart:91:64)
           #3      _rootRunBinary (dart:async/zone.dart:1214:47)
           #4      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #5      _FutureListener.handleError
(dart:async/future_impl.dart:157:20)
           #6      Future._propagateToListeners.handleError
           (dart:async/future_impl.dart:708:47)
           #7      Future._propagateToListeners
(dart:async/future_impl.dart:729:24)
           #8      Future._completeError (dart:async/future_impl.dart:537:5)
           #9      _AsyncAwaitCompleter.completeError
           (dart:async-patch/async_patch.dart:47:15)
           #10     buildGradleAar
(package:flutter_tools/src/android/gradle.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #19     _DefaultProcessUtils.run
(package:flutter_tools/src/base/process.dart)
           #20     _rootRunUnary (dart:async/zone.dart:1198:47)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #22     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #23     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #24     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #26     _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #27     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #28     _run (package:flutter_tools/src/base/error_handling_io.dart)
           #29     _rootRunUnary (dart:async/zone.dart:1198:47)
           #30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #31     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #32     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #33     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #34     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #35     Future.wait.<anonymous closure>
(dart:async/future.dart:414:23)
           #36     _rootRunUnary (dart:async/zone.dart:1198:47)
           #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #38     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #39     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #40     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #42     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #43     _rootRun (dart:async/zone.dart:1190:13)
           #44     _CustomZone.run (dart:async/zone.dart:1093:19)
           #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #46     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #49     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #50     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +261 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by TahaTesser** [comment] 2020-11-13 13:51
Hi @IamArmaan 
Can you remove `flutter_native_web` and try again? 
If the problem persists, please provide  a complete reproducible minimal code sample
Thank you

**Comment by IamArmaan** [comment] 2020-11-16 05:38
Yes , removing flutter_native_web , fixed the issue..

**Comment by TahaTesser** [comment] 2020-11-16 07:11
Hi @IamArmaan 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/PonnamKarthik/FlutterWebView/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-16 07:11 UTC
Labels: in triage
