### ISSUE TITLE
Integration tests: I cannot get the status of a CheckboxListTile

### ISSUE THREAD

**Issue by LostInDarkMath** [flutter/flutter#83572] opened 2021-05-28 19:40 UTC
## Steps to Reproduce

The important part of my integration test:
```dart
final checkbox = find.byType(Checkbox).first;

expect(tester.getSemantics(checkbox), matchesSemantics(
  isChecked: true,
  isEnabled: true,
));

await tester.tap(checkbox);
await tester.pumpAndSettle();

expect(tester.getSemantics(checkbox), matchesSemantics(
  isChecked: false,
  isEnabled: true,
));
```

This works fine for `Checkbox` widgets, but not for `CheckboxListTile` widgets.

**Expected results:** 
All tests passed.

**Actual results:** 
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: has semantics with actions: [] with flags:
[SemanticsFlag:SemanticsFlag.isChecked,
SemanticsFlag:SemanticsFlag.isEnabled]
  Actual: SemanticsNode:<SemanticsNode#251(merge boundary ⛔️,
Rect.fromLTRB(20.0, 271.9, 340.0, 327.9), actions: [tap], flags:
[hasEnabledState, isEnabled, isFocusable], label: "Foo",
textDirection: ltr)>
   Which: actions were: [tap]
```

<details>
  <summary>Flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WILLI\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\WILLI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Mi A2 Lite (mobile) • c1c1eca99806 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-05-31 12:37
Hi @LostInDarkMath 
I am getting the following error when your code in a integration test
```
I/flutter ( 9727): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
╞════════════════════════════════════════════════════
I/flutter ( 9727): The following StateError was thrown running a test:
I/flutter ( 9727): Bad state: No element
I/flutter ( 9727): 
```

Can you please provide a complete reproducible minimal code sample 
Thank you

**Comment by LostInDarkMath** [comment] 2021-06-01 06:20
Hi @TahaTesser ,
thank you for your quick response. 

Here is my complete code:

## pubspec.yaml
Nothing special here, I just added the test libraries from the flutter sdk:
```yaml
name: checkboxlistview
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.16.8
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

## main.dart
A simple column with four `CheckboxListTile` widgets.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool friendship = true;
  bool longTermDating = true;
  bool shortTermDating = true;
  bool hookup = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(
            'title',
            style: Theme.of(context).textTheme.headline5,
            textAlign: TextAlign.center,
          ),
          Text('text'),
          CheckboxListTile(
            title: Text('friendship'),
            secondary: Icon(Icons.people),
            controlAffinity: ListTileControlAffinity.leading,
            value: friendship,
            onChanged: (bool? value) => setState(() => friendship = value!),
          ),
          CheckboxListTile(
            title: Text('long_term_dating'),
            secondary: Icon(Icons.people),
            controlAffinity: ListTileControlAffinity.leading,
            value: longTermDating,
            onChanged: (bool? value) => setState(() => longTermDating = value!),
          ),
          CheckboxListTile(
            title: Text('short_term_dating'),
            secondary: Icon(Icons.people),
            controlAffinity: ListTileControlAffinity.leading,
            value: shortTermDating,
            onChanged: (bool? value) => setState(() => shortTermDating = value!),
          ),
          CheckboxListTile(
            title: Text('hookup'),
            secondary: Icon(Icons.people),
            controlAffinity: ListTileControlAffinity.leading,
            value: hookup,
            onChanged: (bool? value) => setState(() => hookup = value!),
          ),
          ElevatedButton(
            onPressed: (){},
            child: Text('save_and_next'),
          ),
        ],
      ),
    );
  }
}
```

## test_driver/integration_test.dart
```dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```

## integration_test/my_integration_test.dart
A simple test that should verify that the checkboxes are unchecked if the user clicks on it.
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:checkboxlistview/main.dart' as app;

void main() {
  group('end-to-end tests', () {
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    testWidgets('demo test', (WidgetTester tester) async {
      app.main();
      await tester.pumpAndSettle();

      final checkboxFriendship = find.byType(Checkbox).at(0);

      expect(tester.getSemantics(checkboxFriendship), matchesSemantics(
        isChecked: true,
        isEnabled: true,
      ));
      await tester.tap(checkboxFriendship);
      await tester.pumpAndSettle();
      expect(tester.getSemantics(checkboxFriendship), matchesSemantics(
        isChecked: false,
        isEnabled: true,
      ));
    });
  });
}
```

## Complete error message
```
Running Gradle task 'assembleDebug'...                             25,9s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 9,7s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50919/Yr9z_6H8ap0=/
VMServiceFlutterDriver: Isolate found with number: 248866619671835
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (18202): 00:00 +0: end-to-end tests demo test
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (18202): (The following exception is now available via WidgetTester.takeException:)
I/flutter (18202): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (18202): The following TestFailure object was thrown running a test:
I/flutter (18202):   Expected: has semantics with actions: [] with flags: [SemanticsFlag:SemanticsFlag.isChecked,
I/flutter (18202): SemanticsFlag:SemanticsFlag.isEnabled]
I/flutter (18202):   Actual: SemanticsNode:<SemanticsNode#6(merge boundary ⛔️, Rect.fromLTRB(0.0, 192.5, 360.0, 248.5),
I/flutter (18202): actions: [tap], flags: [hasEnabledState, isEnabled, isFocusable], label: "friendship",
I/flutter (18202): textDirection: ltr)>
I/flutter (18202):    Which: actions were: [tap]
I/flutter (18202):
I/flutter (18202): When the exception was thrown, this was the stack:
I/flutter (18202): #4      main.<anonymous closure>.<anonymous closure> (file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart:17:7)
I/flutter (18202): <asynchronous suspension>
I/flutter (18202): <asynchronous suspension>
I/flutter (18202): (elided one frame from package:stack_trace)
I/flutter (18202): ...
I/flutter (18202):
I/flutter (18202): This was caught by the test expectation on the following line:
I/flutter (18202):   file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart line 17
I/flutter (18202): The test description was:
I/flutter (18202):   demo test
I/flutter (18202): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (18202): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends,
whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (18202): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (18202): The following TestFailure object was thrown running a test:
I/flutter (18202):   Expected: has semantics with actions: [] with flags: [SemanticsFlag:SemanticsFlag.isChecked,
I/flutter (18202): SemanticsFlag:SemanticsFlag.isEnabled]
I/flutter (18202):   Actual: SemanticsNode:<SemanticsNode#6(merge boundary ⛔️, Rect.fromLTRB(0.0, 192.5, 360.0, 248.5),
I/flutter (18202): actions: [tap], flags: [hasEnabledState, isEnabled, isFocusable], label: "friendship",
I/flutter (18202): textDirection: ltr)>
I/flutter (18202):    Which: actions were: [tap]
I/flutter (18202):
I/flutter (18202): When the exception was thrown, this was the stack:
I/flutter (18202): #4      main.<anonymous closure>.<anonymous closure> (file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart:17:7)
I/flutter (18202): <asynchronous suspension>
I/flutter (18202): <asynchronous suspension>
I/flutter (18202): (elided one frame from package:stack_trace)
I/flutter (18202): ...
I/flutter (18202):
I/flutter (18202): This was caught by the test expectation on the following line:
I/flutter (18202):   file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart line 17
I/flutter (18202): The test description was:
I/flutter (18202):   demo test
I/flutter (18202): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (18202): 00:04 +0: end-to-end tests demo test [E]
I/flutter (18202):   Test failed. See exception logs above.
I/flutter (18202):   The test description was: demo test
I/flutter (18202):
I/flutter (18202): 00:05 +0 -1: end-to-end tests (tearDownAll)
W/heckboxlistvie(18202): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
Failure Details:
Failure in method: demo test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: has semantics with actions: [] with flags:
[SemanticsFlag:SemanticsFlag.isChecked,
SemanticsFlag:SemanticsFlag.isEnabled]
  Actual: SemanticsNode:<SemanticsNode#6(merge boundary ⛔️,
Rect.fromLTRB(0.0, 192.5, 360.0, 248.5), actions: [tap], flags:
[hasEnabledState, isEnabled, isFocusable], label: "friendship",
textDirection: ltr)>
   Which: actions were: [tap]

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart:17:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///D:/Projekte/checkboxlistview/integration_test/my_integration_test.dart line 17
The test description was:
  demo test
═════════════════════════════════════════════════════════════════

end of failure 1



I/flutter (18202): 00:05 +1 -1: Some tests failed.
```

How can I access the checked state of the `CheckboxListTile`?

**Comment by TahaTesser** [comment] 2021-06-01 10:32
Hi @LostInDarkMath 
After looking deeply, this looks duplicate of https://github.com/flutter/flutter/issues/41645
We're getting mismatch semantics, so test won't pass even in regular `flutter_test`

**Closed by TahaTesser** 2021-06-01 10:32 UTC
Labels: in triage

**Comment by LostInDarkMath** [comment] 2021-06-01 10:45
@TahaTesser Thank you very much! I hope this will be fixed soon :)
