### ISSUE TITLE
Flutter analyze ignores analysis_options.yaml glob rules.

### ISSUE THREAD

**Issue by ohir** [flutter/flutter#15904] opened 2018-03-24 14:57 UTC
Flutter analyze does NOT obey [analysis_options.yaml](https://www.dartlang.org/guides/language/analysis-options) glob rules. It allows only for full path excludes. (This may affect #15902 and #12726) 

## Steps to Reproduce
```
# create new app exapp; change dir to exapp
% flutter create exapp ; cd exapp

# generate analysis_options.yaml and exclude OFF/** path there 
% echo -e 'analyzer:\n  exclude:\n    - OFF/**\n    - OFF/baddart.dart'> analysis_options.yaml

# make the OFF/ dir with two bad dart files in it
% mkdir OFF
% echo 'noneSuchType x = 0;'> OFF/fail.dart
% echo 'noneSuchType x = 0;'> OFF/baddart.dart

# call analyzer
% flutter analyze
    error • Undefined class 'noneSuchType' at OFF/fail.dart:1:1 • undefined_class
    1 issue found.
```

## Logs
N/A

## Flutter Doctor
```[✓] Flutter (Channel beta, v0.1.5, on Linux, locale pl_PL.utf8)
    • Flutter version 0.1.5 at /testbed/lib/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /testbed/lib/Android/Sdk
    • Android NDK at /testbed/lib/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.2
    • ANDROID_HOME = /testbed/lib/Android/Sdk
    • Java binary at: /testbed/lib/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /testbed/lib/Android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by zoechi** [comment] 2018-03-26 16:17
Which directory contains the `analysis_options.yaml` and what's the exclude rule?

**Comment by ohir** [comment] 2018-03-26 21:43
@zoechi Precisely as stated in the 'steps to reproduce': 
file is in the fresh project dir 'exapp' and contains
```
analyzer:
  exclude:
    - OFF/**
    - OFF/baddart.dart
```
The error `noneSuchType at OFF/fail.dart:1:1` tells us that while analyzer skips the `OFF/baddart.dart` as it should, it analyzes the `fail.dart` file it should not. Whole `OFF/` path is excluded per `- OFF/**` rule. Analyzer should not step into that dir at all.

**Comment by escamoteur** [comment] 2018-04-20 19:32
seems to be the same like this one https://github.com/dart-lang/sdk/issues/28754

**Comment by ohir** [comment] 2018-04-20 20:00
@escamoteur The same cause but discussion there digressed.
Possible places of culprit are:
```
dart-sdk/lib/analyzer/lib/src/lint/linter.dart#122
dart-sdk/lib/analyzer/lib/source/path_filter.dart#24
dart-sdk/lib/analyzer/lib/src/util/glob.dart#39 <- Glob constructor
```
I am too fresh to Dart and too short of time to analyze analyzer further.

**Comment by ohir** [comment] 2018-04-20 20:35
Just checked with `Flutter 0.3.2 • channel dev` and `Framework • revision 44b7e7d3f4`
Now **Analyzer picks up globs from opening example.**

P.S. **beware of YAML** formating slips (do not affect OP example).
Do we really need to fight yaml almost 20 years into XXI century? Toml or even xml, please.

**Comment by escamoteur** [comment] 2018-04-22 16:12
It only works partially. As you can test with this project https://github.com/escamoteur/rx_command/tree/problem_with_analyzer

If I exclude the whole `excample` or `example\lib` folder it works. but if I only exclude `example\lib\json` it doesn't.

**Comment by DanTup** [comment] 2018-04-23 08:58
Probably it's this issue -> https://github.com/dart-lang/sdk/issues/28754

**Comment by ohir** [comment] 2018-04-23 10:47
OK. I am reopening this. For me it *mostly* works, until it does not. DanTup's pointer seem relevant.

**Comment by zoechi** [comment] 2018-07-17 10:13
I think this should be reported in dart-lang/sdk. 
I don't think this is specific to Flutter. @ohir what do you think?

**Comment by DanTup** [comment] 2018-07-17 10:51
Isn't this just a dupe of https://github.com/dart-lang/sdk/issues/28754?

My guess is if you put the same code into a non-Flutter `.dart` script and run `dartanalyze` on it you'll see the same thing?

**Comment by ohir** [comment] 2018-07-17 17:25
1st - AFAIR it was partially **resolved** with some subsequent flutter/master.

*Partially* because paths specified in `analysis_options.yaml` are valid from the **`cwd`** of the tool
(from where flutter analyze ran) not from the `analysis_options.yaml` file location.
So either one needs to have `analysis_options.yaml` in the top (project) dir with paths crafted to the **.** *and* run `analyze` from there, or specify paths relative to `lib` and run `analyze` inside `lib/` (my current usage).

I just checked above with Dart **2.0.0-dev.61.0.flutter-c95617b19c** and it works as described, so I am closing this particular bug now.

So - while there are annoying quirks - there is a way to exclude subpath.

P.S. If and when someone will start to refactor analysis tool, I'd suggest the **.toml** for the configuration dsl.

**Comment by zoechi** [comment] 2018-08-31 19:39
Bot acted weird - closing again

**Closed by zoechi** 2018-08-31 19:39 UTC
