### ISSUE TITLE
Execution failed for task ':app:packageDebug'.

### ISSUE THREAD

**Issue by EdogaCE** [flutter/flutter#63771] opened 2020-08-14 12:40 UTC
~~~
Running "flutter pub get" in e_commerce...                          4.2s

C:\Users\USER\Desktop\commerce\e_commerce>flutter run
Launching lib\main.dart on M5 in debug mode...
Running Gradle task 'assembleDebug'...


FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:packageDebug'.

> Several variant outputs are configured to use the same file name "resources-debug.ap_", filters : MAIN:MAIN



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 1m 48s
Running Gradle task 'assembleDebug'...                            111.0s
Exception: Gradle task assembleDebug failed with exit code 1
~~~

**Comment by Abhishek01039** [comment] 2020-08-14 14:20
Make sure you have followed all the steps carefully.
if yes then try `flutter clean`, and `flutter run -v` 
still the problem is there then please send `flutter doctor -v` and `flutter run -v `
Thanks

**Comment by TahaTesser** [comment] 2020-08-14 15:15
Hi @EdogaCE 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by EdogaCE** [comment] 2020-08-14 22:20
> Make sure you have followed all the steps carefully.
> if yes then try `flutter clean`, and `flutter run -v`
> still, the problem is there then please send `flutter doctor -v` and `flutter run -v ` and `build.gradle` file as well
> Thanks

adriod gradle
~~~buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
~~~
app gradle
~~~def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.e_commerce"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}

apply plugin: 'com.google.gms.google-services'

~~~
C:\Users\USER\Desktop\commerce\e_commerce>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.3.9600], locale
    en-US)
    • Flutter version 1.17.1 at C:\Users\USER\Desktop\flutter
    • Framework revision f7a6a7906b (3 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\USER\Desktop\commerce\e_commerce>flutter run -v
[ +129 ms] executing: [C:\Users\USER\Desktop\flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[ +296 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[   +3 ms] executing: [C:\Users\USER\Desktop\flutter/] git tag --contains HEAD
[ +785 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
           1.17.2
           1.17.3
           1.17.4
           1.17.5
[  +59 ms] executing: [C:\Users\USER\Desktop\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[ +197 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] origin/stable
[   +4 ms] executing: [C:\Users\USER\Desktop\flutter/] git ls-remote --get-url origin
[ +155 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +578 ms] executing: [C:\Users\USER\Desktop\flutter/] git rev-parse --abbrev-ref HEAD
[ +105 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +7 ms] stable
[ +355 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +176 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[ +209 ms] List of devices attached
[  +14 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +328 ms] No supported devices connected.
[  +60 ms] "flutter run" took 1,342ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main
(file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3
)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:168:12)

hope i sent the right folders

**Comment by EdogaCE** [comment] 2020-08-14 22:33
> Hi @EdogaCE
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

C:\Users\USER\Desktop\commerce\e_commerce>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.3.9600], locale
    en-US)
    • Flutter version 1.17.1 at C:\Users\USER\Desktop\flutter
    • Framework revision f7a6a7906b (3 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by EdogaCE** [comment] 2020-08-14 22:34
flutter clean worked for me.. 

its no more showing the error

> Make sure you have followed all the steps carefully.
> if yes then try `flutter clean`, and `flutter run -v`
> still, the problem is there then please send `flutter doctor -v` and `flutter run -v ` and `build.gradle` file as well
> Thanks

flutter clean did  the magic.. thanks

**Comment by Abhishek01039** [comment] 2020-08-15 19:08
oh that's great 
so now you can close the issue @EdogaCE 
Thanks

**Closed** 2020-08-15 23:04 UTC
Labels: in triage
