### ISSUE TITLE
[android] TextField with TextInputType.number has keyboard issue

### ISSUE THREAD

**Issue by zancheng** [flutter/flutter#73388] opened 2021-01-06 03:20 UTC
## Steps to Reproduce

1. Two TextField widgets are used, one of which is set to the input number.
2. The focus is in name, and the display keyboard is ordinary keyboard. Click the number input box, and the focus moves to the number input box, but the keyboard does not change to number input.
3. For another mobile phone, it is normal in the second step, but if you put away the keyboard after number gets the focus and displays the number input, and then click the name input box to get the focus, the keyboard will display the number input.

https://user-images.githubusercontent.com/20456859/103724669-d8628980-500f-11eb-9893-fa1fa4f2a237.mp4

<img height="720" src="https://user-images.githubusercontent.com/20456859/103724990-94bc4f80-5010-11eb-8e3a-b9ab48eeb119.jpg">

https://user-images.githubusercontent.com/20456859/103724687-e7e1d280-500f-11eb-86b4-1766261931d7.mp4

<img height="720" src="https://user-images.githubusercontent.com/20456859/103725218-0eecd400-5011-11eb-8105-3f74b01d4fd1.jpg">

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() {
//  debugPaintSizeEnabled = !true;
  runApp(MyApp());
}


class MyApp extends StatefulWidget {
  MyApp({
    Key key,
  }) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}
class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Home'),
        ),
        body: FocusTestRoute(),
      )
    );
  }
}

class FocusTestRoute extends StatefulWidget {
  @override
  _FocusTestRouteState createState() => new _FocusTestRouteState();
}

class _FocusTestRouteState extends State<FocusTestRoute> {
  FocusNode focusNode1 = new FocusNode();
  FocusNode focusNode2 = new FocusNode();
  FocusScopeNode focusScopeNode;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(16.0),
      child: Column(
        children: <Widget>[
          TextField(
            autofocus: true,
            focusNode: focusNode1,//关联focusNode1
            decoration: InputDecoration(
                labelText: "name"
            ),
          ),
          TextField(
            focusNode: focusNode2,//关联focusNode2
            keyboardType: TextInputType.number,
            decoration: InputDecoration(
                labelText: "number"
            ),
          ),
        ],
      ),
    );
  }
}

```
</details>

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment] 2021-01-06 10:09
Hi @zancheng 
It seems that you are using an old version of Flutter.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, then please provide your `flutter doctor -v` outputs.
Thank you

**Comment by zancheng** [comment] 2021-01-07 02:27
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code
[√] Connected device (1 available)
```

https://user-images.githubusercontent.com/20456859/103843509-e9c09a00-50d2-11eb-95b4-9785b7c4016c.mp4

**Comment by pedromassangocode** [comment] 2021-01-07 11:17
I cannot reproduce this issue on Xiaomi Redmi 5 Plus (Android 8.1) nor on Android emulator (Android 10). Leaving this opened for further investigation.

For anyone that have the device mentioned in the OP please try to reproduce this issue and share your outputs.
Thank you

<img height="720" src="https://user-images.githubusercontent.com/67424416/103886693-2d6ed000-50e2-11eb-8e94-2d0f346fef4d.gif">

<details><summary>flutter doctor (master)</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.222, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.222 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 655cd1e2a6 (3 hours ago), 2021-01-07 03:19:03 -0500
    • Engine revision 7f00e2f6c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by baofei12** [comment] 2021-01-29 08:36
hi, HUAWEI Mate 20（android 10）   HUAWEI P30 Pro（android 10） ，That's the problem, too。 

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by simplezhli** [comment] 2021-03-29 01:37
@pedromassangocode Found that [Baidu input](https://play.google.com/store/apps/details?id=com.baidu.input) exists this kind of problem, other normal.

**Comment by zmm2tysu** [comment] 2021-04-02 08:55
@simolus3 Me too!

**Comment by ramonpaolo** [comment] 2021-07-18 15:26
Hi, i have the same problem with my Xiaomi redmi note 8.
Before i dont have this problem, but, now, after than i do build(release and debug),  i had this problem
(sorry for poor english)

**Comment by ramonpaolo** [comment] 2021-07-18 15:37
Hi, i fixed this problem, enable optimization MIUI and resolved it

**Comment by tao-glow** [comment] 2021-07-31 04:29
> I cannot reproduce this issue on Xiaomi Redmi 5 Plus (Android 8.1) nor on Android emulator (Android 10), tested on master and stable channel. Leaving this opened for further investigation.
> 
> For anyone that have the device mentioned in the OP please try to reproduce this issue and share your outputs.
> Thank you
> 
> <img alt="" height="720" src="https://user-images.githubusercontent.com/67424416/103886693-2d6ed000-50e2-11eb-8e94-2d0f346fef4d.gif">
> 
> flutter doctor (master)
> ```
> /Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
> [✓] Flutter (Channel master, 1.26.0-2.0.pre.222, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
>     • Flutter version 1.26.0-2.0.pre.222 at /Users/pedromassango/dev/SDKs/flutter_master
>     • Framework revision 655cd1e2a6 (3 hours ago), 2021-01-07 03:19:03 -0500
>     • Engine revision 7f00e2f6c5
>     • Dart version 2.12.0 (build 2.12.0-179.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/pedromassango/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [!] Xcode - develop for iOS and macOS (Xcode 12.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.1, Build version 12A7403
>     ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] IntelliJ IDEA Community Edition (version 2020.3.1)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 52.1.5
>     • Dart plugin version 203.6912
> 
> [✓] VS Code (version 1.51.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (4 available)
>     • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
>     • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
>     • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
>     • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88
> 
> ! Doctor found issues in 1 category.
> Process finished with exit code 0
> ```
> 
> flutter doctor

This can be reproduce with [baidu input](https://srf.baidu.com/default/), The baidu input may have compatibility issue but it work right on Android native

**Comment by pedromassango** [comment] 2021-08-02 13:38
@TahaTesser

**Comment by camsim99** [comment] 2023-08-17 18:25
@huycozy We believe this issue may be fixed on the latest `master`. Can you try to reproduce this issue with it and close out this issue if so?

**Comment by zancheng** [comment] 2023-08-18 06:34
> @huycozy We believe this issue may be fixed on the latest `master`. Can you try to reproduce this issue with it and close out this issue if so?

Now the function is normal

**Comment by huycozy** [comment] 2023-08-18 07:21
@camsim99 I check this issue on master channel with my device `Realme 6, Android 11` and confirm the issue doesn't appear anymore. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (25 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-7.0.pre.19, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-7.0.pre.19 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 03664d0acb (19 minutes ago), 2023-08-18 04:58:20 +0200
    • Engine revision 866b43f656
    • Dart version 3.2.0 (build 3.2.0-83.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

@zancheng Thanks for confirming this. Closing the issue as fixed.

**Closed by huycozy** 2023-08-18 07:21 UTC
Labels: a: text input, e: device-specific, platform-android, framework, f: material design, P3, team-android, triaged-android, fyi-framework, multiteam-retriage-candidate
