### ISSUE TITLE
Flutter APK crashes with Android log error when updating NetworkImage

### ISSUE THREAD

**Issue by grafnu** [flutter/flutter#1472] opened 2016-01-29 16:00 UTC
I received this error multiple times while running my app, but I don't have a lot of information on what's triggering it. All the app does is periodically receive remote updates and then updates a NetworkImage with the new contents.  I'm adding this now for tracking -- my next steps are to create a more reproducible test-case.

relevant bit from "adb logcat"

E/System  (30957): Uncaught exception thrown by finalizer
E/System  (30957): java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
E/System  (30957):  at org.chromium.mojo.bindings.AutoCloseableRouter.finalize(AutoCloseableRouter.java:111)
E/System  (30957):  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
E/System  (30957):  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
E/System  (30957):  at java.lang.Thread.run(Thread.java:818)

**Comment by sethladd** [comment] 2016-01-29 16:02
Thanks for any info you can provide!

**Comment by Hixie** [comment] 2016-04-01 23:47
looks like a dupe of https://github.com/flutter/flutter/issues/2950

**Comment by abarth** [comment] 2017-01-26 19:32
Closing as dup.

**Closed by abarth** 2017-01-26 19:32 UTC
