### ISSUE TITLE
[iOS] Text selection doesn't match native behaviour

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#92966] opened 2021-11-03 08:04 UTC
## Use case

This would apply to any selectable text in flutter. This could be `SelectableText()` or text fields, etc.

On iOS, the button selection behaviour is quite complex when compared to Flutter's allowing a range of selections such as a word or a whole line/paragraph. Flutter simple toggles between selecting and not selecting the text. Below is video comparing Flutter to native iOS apps:

https://user-images.githubusercontent.com/63734405/140024423-f57c847f-ad37-44ce-8d9b-cd1764cd35dd.mp4

<details>
<summary>Code sample for Flutter app in the video above</summary>

<br>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: Login()));
}

class Login extends StatefulWidget {
  const Login({Key? key}) : super(key: key);

  @override
  State<Login> createState() => _LoginState();
}

class _LoginState extends State<Login> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: TextFormField(),
        ),
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

<br>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.566, on macOS 12.0 21A344
    darwin-arm, locale en-AE)
    • Flutter version 2.6.0-12.0.pre.566 at
      /Users/hadymashhour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 607d7934c7 (4 hours ago), 2021-11-02 21:23:01 -0700
    • Engine revision 6095a13678
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hadymashhour/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0 21A344 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

```

</details>

## Proposal

To match the iOS text selection behaviour as iOS users are used to it and Flutter apps might feel out of place to the user and cause confusion.

**Comment by maheshmnj** [comment] 2021-11-03 10:31
Hi @HadyMash, Thanks for filing the issue. I can reproduce the difference. The additional options on text selection seem to be based on the context where the text is being selected, for instance in safari you wouldn't get those additional options, while in reminders you will.

I could see three differences
-  double tap on IOS sometimes selects the whole text, I haven't been able to find that pattern when that happens, while in flutter double tap only selects the tapped word
- on long-press, the cursor stops blinking and increases in size on iOS and restores to old size, and starts blinking when the input leaves contact with the screen. While in flutter the cursor always blinks with the same size
- It is not necessary to drag the handles to modify the text selection on IOS, dragging the selected text also modifies the selected area. On the other hand in flutter dragging the selected text animates the text with a horizontal scroll.
 
IOS | Flutter
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/140043300-55fcc5a4-20c1-47cf-bc57-398b71a03edc.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/140043313-c86e080e-60e8-4d56-898c-45d873affdb9.mov' width=180/>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.555, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.555 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 067386d706 (25 hours ago), 2021-11-02 05:13:04 -0400
    • Engine revision 76b4caeafe
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by HadyMash** [comment] 2021-11-03 10:57
@maheshmnj 
>     * double tap on IOS sometimes selects the whole text, I haven't been able to find that pattern when that happens, while in flutter double tap only selects the tapped word

I think that is based on whether you already selected or not. I think the pattern is as follows: The first double tap selects a word, triple tapping the word selection will select the whole line (not sure if it's a line or paragraph). If the text is not selected and you triple tap it will select the a word (double tap) then the third tap (if it is quick enough such as pressing 3 times in a row) will change the word selection to line/paragraph (not sure again I'll have to test in the 'Notes' section in reminders. The quick triple tap at the start is the equivalent to double tapping then tripple tapping.

Do you think this is correct?

**Comment by HadyMash** [comment] 2021-11-03 11:41
@maheshmnj 
> The additional options on text selection seem to be based on the context where the text is being selected, for instance in safari you wouldn't get those additional options, while in reminders you will.

What do you mean by "additional options"? Do you mean the 'copy', 'cut', 'paste', etc. or the selection behaviour?

I was able to get the double tap, triple tap and double tap drag to work in Reminders, Notes (notes app and notes in reminder), and Safari. Notes isn't available on the simulator so I tested it on a real device. But seems text selection isn't dependent on context from what I refer if that's what you meant by additional options.

https://user-images.githubusercontent.com/63734405/140052314-b8978f70-4213-4a75-8685-c71cf01678ff.MOV

https://user-images.githubusercontent.com/63734405/140052338-586401ba-b316-4467-91a9-72d740823687.MOV

I also want to add on to this:
> If the text is not selected and you triple tap it will select the a word (double tap) then the third tap (if it is quick enough such as pressing 3 times in a row) will change the word selection to line/paragraph (not sure again I'll have to test in the 'Notes' section in reminders. The quick triple tap at the start is the equivalent to double tapping then tripple tapping.

After the whole paragraph is selected, double tapping brings back the selection to a word. So double tapping selects a word and triple tapping a paragraph regardless of what's already selected

I can verify triple tapping selects the whole paragraph. If it's a line long it will appear to select just a line but if it's more than one line it will select the whole paragraph. If the text field doesn't allow the text to wrap such as in Safari, then it selects the entire line or body of text.

**Comment by maheshmnj** [comment] 2021-11-03 12:21
> I think that is based on whether you already selected or not. I think the pattern is as follows: The first double tap selects a word, triple tapping the word selection will select the whole line (not sure if it's a line or paragraph). If the text is not selected and you triple tap it will select the a word (double tap) then the third tap (if it is quick enough such as pressing 3 times in a row) will change the word selection to line/paragraph (not sure again I'll have to test in the 'Notes' section in reminders. The quick triple tap at the start is the equivalent to double tapping then tripple tapping.

yes with triple tap its selecting the whole text

**Comment by maheshmnj** [comment] 2021-11-03 12:22
> What do you mean by "additional options"? Do you mean the 'copy', 'cut', 'paste', etc. or the selection behaviour?

Yes I am referring to copy, cut options

**Comment by justinmc** [comment] 2021-11-22 21:36
We should get these right, I'm on board with this.  Hopefully we will refactor these kinds of gestures to use Intents soon, but either way I'll put this on my list and we should make it match native.

**Comment by oboard** [comment] 2021-12-12 08:28
![Uploading IMG_20211212_162605.jpg…]()
Text selection doesn't match native behaviour on Android too.We need more behaviour on Flutter.

**Comment by oboard** [comment] 2021-12-12 08:30
![IMG_20211212_162605](https://user-images.githubusercontent.com/23210180/145705688-36373b04-7f9c-423a-9f41-44a9f65dd2ef.jpg)

It is on Android That text selection doesn't match native behaviour too.
We need more behaviour on Flutter.

**Comment by jmagman** [comment] 2021-12-13 18:09
> It is on Android that text selection doesn't match native behaviour too.

Please file a new issue, this one is tracking iOS.

**Comment by gnprice** [comment] 2023-05-17 21:12
In general it's best to file separate issues for specific distinct problems. An umbrella or omnibus issue is harder to act on.

Breaking down the issues in this thread:

---

The triple-tap issue appears to be this:
* #123415 

If you try the triple-tap gesture in the middle of a relatively long word — so that you're far from the nandles that appear after the second tap — then it works great. So what's needed isn't implementing the gesture (that's already been done), but fixing the bug #123415 that often prevents it from working.


> * on long-press, the cursor stops blinking and increases in size on iOS and restores to old size, and starts blinking when the input leaves contact with the screen. While in flutter the cursor always blinks with the same size

I don't reproduce the cursor increasing in size in a native iOS app.

I also don't reproduce the cursor continuing to blink in Flutter. It looks like this may have been the issue reported and fixed here:
* #105454 
* #107221



> * It is not necessary to drag the handles to modify the text selection on IOS, dragging the selected text also modifies the selected area. On the other hand in flutter dragging the selected text animates the text with a horizontal scroll.

I don't reproduce that iOS behavior.

If you have only a small piece of text selected, the behavior can look like that because the handles have wide touch targets, much wider than they're drawn — it's easy to hit one of the handles and drag it. But if you select something longer (perhaps roughly 10+ letters) and try to drag from the middle of it, the selection doesn't change.

The behavior you do get when you drag the middle of the text, in a single-line text input, is that nothing happens. So that is a difference from the Flutter behavior, where it scrolls.

This is one case where I'm not sure it'd actually be better to match the native iOS behavior, though: it seems more frustrating as a user. Also, even iOS doesn't have that behavior consistently: in a *multi*-line text input, dragging from the middle of a text selection does scroll, vertically. Flutter matches that behavior.

---

Closing this because the part that seems to still be open is covered by #123415. If someone's seeing other problems with text selection, please file specific issues for them, filling out all the information in the issue template, and that will make it possible to address them.

Similarly if someone is interested in having a drag in the middle of a text selection match iOS precisely, by doing nothing in a single-line input while still scrolling in a multi-line input, please file that as its own issue.

**Closed by gnprice** 2023-05-17 21:12 UTC
Labels: a: text input, platform-ios, framework, a: fidelity, a: quality, proposal, passed first triage, P4

**Comment by gnprice** [comment] 2023-05-17 21:19
> if someone is interested in having a drag in the middle of a text selection match iOS precisely, by doing nothing in a single-line input while still scrolling in a multi-line input

Ah, and in fact there's already an issue for this:
* #25553

(Which I see I've already thumbs-upped, even though I was dubious of the version above. I guess the context in that issue made it make more sense to me. One of the benefits of separate threads for separate issues is that it makes more room for describing each one in detail :slightly_smiling_face:)

**Comment by justinmc** [comment] 2023-05-18 00:21
Thank you for breaking this down @gnprice!
