### ISSUE TITLE
xcodebuild: error: unable execute utility "xcodebuild" because it requires a newer version of macOS.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#100985] opened 2022-03-29 18:47 UTC
On commit https://github.com/flutter/engine/pull/31915

```
xcodebuild: error: unable execute utility "/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild" because it requires a newer version of macOS.
[E 2022-03-29 10:53:42] original error: exit status 70

goroutine 1:
#0 mac_toolchain/install.go:170 - main.finalizeInstall.func1()
  reason: failed when invoking xcodebuild -runFirstLaunch
```
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/12726

`os` property is set to `Mac-12` but the task ran on macOS 10.15 bot [build812-m9](https://chromium-swarm.appspot.com/bot?id=build812-m9).

Engine tree is closed.

**Comment by CaseyHillers** [comment] 2022-03-29 19:33
The underlying issue is https://github.com/flutter/flutter/issues/95037 which is blocked on finishing the migration off the LUCI scheduler to the Cocoon scheduler.

We should land an empty commit now that the LUCI configs have propagated to kick the builds with the correct xcode, os, and caches

**Comment by CaseyHillers** [comment] 2022-03-29 19:45
I was incorrect. This PR is in the engine, which already migrated to the Cocoon scheduler. The issue is in the Cocoon scheduler not passing dimensions on post-submit builds.

I'm following up in https://github.com/flutter/cocoon/pull/1690 to fix the scheduler bug.

**Comment by CaseyHillers** [comment] 2022-03-29 20:14
Cocoon scheduler PR fixed the dimensions being passed. Current issue is the beta hotfix is taking up the Mac 12 capacity, so we're not seeing the builds get picked up immediately. The reason landing an empty commit didn't work is the ci.yaml roller broke on this commit.

Next issue is to fix the ci.yaml caches for xcode 13 to get the ci.yaml roller going again.

**Comment by CaseyHillers** [comment] 2022-03-29 20:57
To recap from chat rooms, the engine tree isn't necessarily blocked on the roller failing, but this may cause corruption in the caches. This will result in flaky tests and extra xcode wipes which increases overall build time.

I sent https://flutter-review.googlesource.com/c/infra/+/28440 to update the starlark to work with the xcode PR, and added the ci.yaml fixes in https://github.com/flutter/engine/pull/32325

**Comment by CaseyHillers** [comment] 2022-03-29 21:54
Engine tree is green again, and ci.yaml roller should be green. Closing.

**Comment by yjbanov** [comment] 2022-03-30 21:18
It's not fully green yet. It went from red to severely flaky :)

**Comment by yjbanov** [comment] 2022-03-30 21:19
Am I commenting on the right issue? :thinking:

**Comment by yjbanov** [comment] 2022-03-30 21:19
My bad, I was thinking https://github.com/flutter/flutter/issues/97303

**Closed by yjbanov** 2022-03-30 21:20 UTC
Labels: team: infra, P0
