### ISSUE TITLE
Long press options moved up with TextField multi line

### ISSUE THREAD

**Issue by Dead96** [flutter/flutter#34643] opened 2019-06-18 15:06 UTC
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextField maxLines bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('TextField maxLines bug'),
        ),
        body: Center(
          child: ListView(
            children: <Widget>[
              TextField(
                decoration: InputDecoration(
                  labelText: 'Text 1',
                ),
              ),
              TextField(
                decoration: InputDecoration(
                  labelText: 'Text 2',
                ),
                maxLines: 20,
              ),
              TextField(
                decoration: InputDecoration(
                  labelText: 'Text 3',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
## Explanation

If you long press the "Text 1" or the "Text 3" field, the options are displayed correctly, but if you long presso the "Text 2" field, the options are moved up.

## Screenshot

![Screenshot_1560869238](https://user-images.githubusercontent.com/30490572/59695266-3dfee300-91ea-11e9-8e4c-4225ab71da07.png)

## Logs

[flutter run verbose.txt](https://github.com/flutter/flutter/files/3302105/flutter.run.verbose.txt)

```
Analyzing textfieldbug...
No issues found! (ran in 2.4s)
```

```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.557], locale en-GB)
    • Flutter version 1.6.3 at C:\flutter
    • Framework revision bc7bc94083 (4 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\andrea.russo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\andrea.russo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by mizio** [comment] 2019-07-22 08:45
Same problem, very useful if fixed.

**Comment by Dead96** [comment] 2019-10-18 10:31
Now the options are close to TextField, but sometimes the last option is partially cut off the screen, especially on low resolution devices.

**Comment by TahaTesser** [comment] 2020-06-05 13:39
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment] 2021-01-19 15:22
Closing as duplicate of https://github.com/flutter/flutter/issues/59229

**Closed by TahaTesser** 2021-01-19 15:22 UTC
Labels: P4, a: quality, a: text input, f: material design, found in release: 1.19, framework, has reproducible steps
