### ISSUE TITLE
Minor suggestion: Firebase Crashlytics plugin: Crashlytics() is exposed

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#31460] opened 2019-04-23 00:56 UTC
Crashlytics() is exposed, and there is Crashlytics.instance
If i understand correctly, the constructor should be private so that devs do not try to use it on accident, and of course it doesn't achieve the right result.

**Comment by BondarenkoStas** [comment] 2019-10-16 14:56
@neiljaywarner please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close this issue.

**Comment by iapicca** [comment] 2019-11-08 09:44
Hi @neiljaywarner  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:44 UTC
Labels: waiting for customer response
