### ISSUE TITLE
Cannot type in textfield after back navigation

### ISSUE THREAD

**Issue by tlarsen7572** [flutter/flutter#14840] opened 2018-02-23 10:45 UTC
## Steps to Reproduce

I am using onGenerateRoute to perform navigation.  My onGenerateRoute method creates MaterialPageRoute objects with `maintainState: false`.  When navigating backwards, TextField widgets can no longer be focused and edited.  [This Gist](https://gist.github.com/tlarsen7572/fdd91e2818c89430f87785371cb96f6a) produces the issue.  When the home page first loads, its TextField can be edited.  When you navigate to Next and then go back, the TextField can no longer be edited.

## Flutter Doctor

```
✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel master)
    • Flutter version 0.1.3-pre.46 at /Users/tlarsen/flutter
    • Framework revision f914e701c5 (4 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/tlarsen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • iPhone 7 • B3ECB1A2-524B-4C57-801A-C34AE83D617E • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by cbracken** [comment] 2018-03-01 07:57
@tlarsen7572 thanks for reporting!

/cc @xster -- I'm almost certain this is a dupe but I suspect you'll be able to find it and link to it quicker than me :)

**Comment by manbach** [comment] 2018-07-09 12:58
Anything new here ?
I have the same issues. Im using an textfield to allow user comments. If the user uploads an Image (switches to gallery or camera) and comes back the textfield seems unselectable and uneditable on IOS.

**Comment by mortkane** [comment] 2018-07-20 14:56
Same problem here!

**Comment by henrik-d** [comment] 2018-07-20 20:33
I have the same problem with Flutter v0.5.1, also on Android. The problem only occurs with `maintainState: false`

**Comment by zoechi** [comment] 2018-12-06 11:54
Still reproduces

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-AT)
    • Flutter version 1.0.0 at /Users/zoechi/flutter/flutter
    • Framework revision 5391447fae (6 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-12-28 13:59
similar to #19750

**Comment by zoechi** [comment] 2019-01-28 17:39
Closing as duplicate of #23862 because it has more upvotes

**Closed by zoechi** 2019-01-28 17:39 UTC
Labels: a: text input, f: routes, framework, ⌺‬ platform-ios
