### ISSUE TITLE
Apple New IPhone Mirroring Scrolling Issue

### ISSUE THREAD

**Issue by mosabalrsaheed** [flutter/flutter#155318] opened 2024-09-17 19:38 UTC
### Steps to reproduce

Update to the latest IOS/Macos versions 
Start a session of Iphone Mirroring
Run a flutter application in the mirrored iphoned

### Expected results

Application scrolling pages shoud scroll as expected

### Actual results

Nothing is being scrolled at all.

### Code sample

<details open><summary>Code sample</summary>

```dart
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.26.0-0.1.pre, on macOS 15.0 24A335 darwin-arm64, locale en-SA)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.2.1)
[✓] VS Code (version 1.93.1)
[✓] VS Code (version 1.89.0-insider)
[✓] Connected device (6 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by Ssiswent** [comment] 2024-09-18 06:26
The same, have you found any solutions?

**Comment by danagbemava-nc** [comment] 2024-09-18 06:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153897. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-09-18 06:53 UTC
Labels: in triage
