### ISSUE TITLE
Flutter run installs apk both in normal and work profile - add arg to flutter run

### ISSUE THREAD

**Issue by afijal** [flutter/flutter#49516] opened 2020-01-26 20:52 UTC
It doesn't matter whether you run your app using flutter run or by android studio or visual code - it always gets installed in both work profile and normal one.

I think it would be good to have a possibility to add a flag to restrict it from being installed everywhere

**Comment by jmagman** [comment] 2020-02-05 00:44
Duplicate of https://github.com/flutter/flutter/issues/20324.

**Closed by jmagman** 2020-02-05 00:44 UTC
Labels: framework, proposal, severe: new feature, tool, ▣ platform-android
