### ISSUE TITLE
Improve Android V2 Migration guide

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#44171] opened 2019-11-05 10:21 UTC
For Kotlin projects there's no migration info at https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects.

The migrated `MainActivity.kt`, as on latest master (`v1.10.15-pre.404`) should look like this:

```kt
package [your.package.name]

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

Also, the migration docs seem to be wrong as the Kotlin equivalent of the Java code on the wiki doesn't work (it's missing the `override` and some `import` parts).

If your `MianActivity.kt` is like this:

```kt
package [your.package.name]

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
```

you will get runtime errors like:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

The line that is causing that issue in my project is:

```dart
SharedPreferences _prefs = await SharedPreferences.getInstance();
```

I had to force the migration because I couldn't run my app, as `shared_preferences` uses V2 embedding, caused by https://github.com/flutter/flutter/pull/44026.

cc/ @blasten @xster

**Comment by iapicca** [comment] 2019-11-05 10:37
https://github.com/flutter/flutter/issues/44161

**Comment by Zazo032** [comment] 2019-11-05 13:05
This message is still appearing after the migration, but it's not clear how to fix it:
```
W/FlutterEngine(28940): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@9f006d2) but could not find and invoke the GeneratedPluginRegistrant.
```

**Comment by xster** [comment] 2019-11-05 17:41
Uh oh, thanks for pointing it out. We're definitely going to improve the wiki. Though it seems like a bug currently since shared_preferences still supports the old embedding https://github.com/flutter/plugins/blob/master/packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java

cc @blasten

**Comment by xster** [comment] 2019-11-05 19:03
@Zazo032 can you paste your flutter doctor -v outputs here? Not clear what exact version of flutter you're on.

**Comment by xster** [comment] 2019-11-05 22:17
This is a bug. Leaving this for the documentation part but the bug is solved in #44161

**Comment by fauzipadlaw** [comment] 2019-11-06 03:28
same problem, `flutter doctor -v`:

```
[√] Flutter (Channel master, v1.10.15-pre.419, on Microsoft Windows [Version 10.0.17134.950], locale en-US)
    • Flutter version 1.10.15-pre.419 at C:\src\flutter
    • Framework revision 02aac5072c (5 hours ago), 2019-11-05 14:38:09 -0800
    • Engine revision 0928c1af2f
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\fauzi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\fauzi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] VS Code, 64-bit edition (version 1.37.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • CPH1729 • EQ8SJFTGWK9PWCLV • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by Zazo032** [comment] 2019-11-06 09:08
> @Zazo032 can you paste your flutter doctor -v outputs here? Not clear what exact version of flutter you're on.

Sorry, I have already upgraded from `v1.10.15-pre.404` to `v1.10.15-pre.424`.

**Comment by ZionPi** [comment] 2019-11-06 14:18
`flutter doctor -v` shows no errors, caused by 

> SharedPreferences _prefs = await SharedPreferences.getInstance()

**Comment by cmkweber** [comment] 2019-11-12 20:50
For java projects, the migration guide currently suggests editing **MainActivity.java** to:

```
package [your.package.name];

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity { }
```

But new projects created through **flutter create -a java** create **MainActivity.java** with:

```
package [your.package.name];

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}

```

Using this updated **MainActivity.java** was necessary for me to not receive **MissingPluginException**s. Perhaps the migration guide should be updated, or is this subject to change?

**flutter doctor -v**
```
[√] Flutter (Channel master, v1.10.17-pre.61, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.10.17-pre.61 at C:\flutter
    • Framework revision d39e2bb776 (2 hours ago), 2019-11-12 10:27:58 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0
```

**Comment by xster** [comment] 2019-11-13 05:15
All other comments in this issue still stand. Specifically for @cmkweber's comment https://github.com/flutter/flutter/issues/44171#issuecomment-553108125, based on where you are on master, the `GeneratedPluginRegistrant.registerWith(flutterEngine);` line should not be necessary. 

@matthew-carroll thoughts?

**Comment by matthew-carroll** [comment] 2019-11-13 05:19
@xster is there a particular question in this thread for me to address? It looks like most of this is abut a bug that we think is fixed?

**Comment by xster** [comment] 2019-11-13 05:51
The post I linked to. The user is on 1.10.17-pre.61 which I think manually calling GeneratedPluginRegistrant.registerWith(flutterEngine) shouldn't have been necessary

**Comment by matthew-carroll** [comment] 2019-11-13 22:12
@cmkweber I checked out v1.10.17-pre.61 (d39e2bb776) and created a new Flutter project with Java that uses the device_info plugin.

My project builds, deploys, and runs as expected with the following implementation for `MainActivity`:

```java
package io.flutter.repro_plugin_bug_java;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {}
```

Can you please try creating another new project to verify that the problem occurs?

Also, which plugin(s) are you trying to use in your project?

**Comment by cmkweber** [comment] 2019-11-14 00:10
@matthew-carroll - I was not able to reproduce this with a new project, so I went looking for differences that could be causing it. I noticed that the **GeneratedPluginRegistrant.java** looked different than the one in my original project even though I used the same plugins.

For instance firebase_core was listed as:
`io.flutter.plugins.firebase.core.FirebaseCorePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebase.core.FirebaseCorePlugin"));`

In the new project it was listed as:
`flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());`

I was able to determine the reason is my original project was using slightly older versions of the same plugins, even though there is no version specified, eg:
`cloud_firestore: cloud_functions:`

I had to delete **pubspec.lock** to force pub to use the new versions, so this is potentially a bug in pub I can try to find a reproducible for. I can confirm though that after forcing plugin upgrades the empty **MainActivity** class works.

**Comment by matthew-carroll** [comment] 2019-11-14 00:14
Thanks for re-checking. I'm not sure if that situation with plugins is intended behavior or a bug, but @amirh or @mklim might know.

But WRT to the Flutter tool and the new embedding, it looks like the issue is resolved. @xster should we close this ticket, or do you want to leave it open for the documentation requests?

**Comment by xster** [comment] 2019-11-14 02:33
@cmkweber your described plugin difference is the standard expected behavior. `flutter packages get` will not change the package code you get even if you ask for the latest version in pubspec.yaml since a specific version was locked in your pubspec.lock as you noticed. 

Though even with `io.flutter.plugins.firebase.core.FirebaseCorePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebase.core.FirebaseCorePlugin"));`, it's a bit concerning that you would get the MissingPluginExceptions issue. Do you still know the version fo firebase core your pubspec.lock pointed to?

**Comment by cmkweber** [comment] 2019-11-14 18:08
These were the relevant firebase and share preferences versions...

cloud_firestore: 0.12.9+6
cloud_functions: 0.4.1+2
firebase_analytics: 5.0.2
firebase_auth: 0.14.0+5
firebase_core: 0.4.0+3
firebase_crashlytics: 0.1.0+3
firebase_storage: 3.0.6
shared_preferences: 0.5.4+3

**Comment by workerbee22** [comment] 2020-01-20 23:05
Documentation here https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Currently says this:

![image](https://user-images.githubusercontent.com/5154664/72762538-136b8180-3c34-11ea-984a-eda224f0ab25.png)

So firstly the code shown is incorrect, existing projects have **android:name** and not just **name**

New project created with flutter create 1.12.x seem to still use the line:

**android:name="io.flutter.app.FlutterApplication"**

So this guidance is confusing. Why do new projects (created with 1.12.x) use an android:name value, but the documentation for migration says to remove it?

**Comment by woprandi** [comment] 2020-01-23 11:15
I'm there because I also detected an issue between the migration guide and the code generated when creating a new flutter project. The `MainActivity` class is supposed to be empty when v2 is enabled ( the default). 
That explains why plugin is registered twice and why remove the `MainActivity` content fix the issue.

**Comment by xster** [comment] 2020-03-11 20:36
There are a lot of things mixed in this thread and some are temporary from pre-1.12 launch. Taking note as I read the various items:

- Kotlin code has been added to the wiki
- fixed override
- all plugin issues reported above are transient and fixed with the various first party plugins' latest versions
- the java template vs guide inconsistency is now gone. For reading between the lines, it's now no longer needed to either use FlutterApplication and explicitly call FlutterMain.startInitialization(this) or explicitly call GeneratedPluginRegistrant.registerWith(this) (or even have a FlutterActivity subclass unless you want to do something special in it).
- all MissingPluginException issues should be fixed now. If you still see any, please file a separate bug with repro steps.
- fixed the AndroidManifest.xml discrepancy. For reading between the lines, using FlutterApplication is no longer necessary (but doesn't hurt either).
- the double plugin registration is a big issue. Tracking follow-up work on https://github.com/flutter/flutter/issues/50004

Thanks all for your reviews and feedbacks.

**Closed by xster** 2020-03-11 20:36 UTC
Labels: a: existing-apps, customer: crowd, documentation, framework, ▣ platform-android
