### ISSUE TITLE
flutter run always rebuilds, doesn't find built executable

### ISSUE THREAD

**Issue by rgisi** [flutter/flutter#53237] opened 2020-03-25 10:38 UTC
Hi everybody.

When I run `flutter run --no-build` (for ios), it rebuilds the executable anyways and then tells me:
`Could not find the built application bundle at build/ios/iphoneos/Runner.app. Error launching application on <my iPhone>.` This makes sense because there is no `Runner.app` but only a `<application name>.app` in that directory. 

I can workaround by running `flutter run --user-application-binary <path-to-file>`.

**Comment by VladyslavBondarenko** [comment] 2020-03-25 11:27
@rgisi 
Could you provide your `flutter doctor -v`?

**Comment by rgisi** [comment] 2020-03-25 13:08
```    flutter doctor -v
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E224g, locale en-CH)
    • Flutter version 1.15.17 at /Users/.../flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that
      location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

 
[✓] Connected device (1 available)            
    • myiPhone • 89b02340c9b8642b1ab0d975c9c0455538e66848 • ios • iOS 12.4.5
```

**Comment by jonahwilliams** [comment] 2020-03-25 13:37
Duplicate of https://github.com/flutter/flutter/issues/41793

**Closed by jonahwilliams** 2020-03-25 13:37 UTC
Labels: tool, ⌺‬ platform-ios
