### ISSUE TITLE
"FileSystemException: Cannot copy file to 'C:\....\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Acesso negado. , errno = 5)".

### ISSUE THREAD

**Issue by RMXJR** [flutter/flutter#59637] opened 2020-06-17 03:31 UTC
```bash
C:\Users\Usuario>cd Desktop

C:\Users\Usuario\Desktop>flutter create --org br.com.ciolfi testando
Creating project testando...
  testando\.gitignore (created)
  testando\.idea\libraries\Dart_SDK.xml (created)
  testando\.idea\libraries\Flutter_for_Android.xml (created)
  testando\.idea\libraries\KotlinJavaRuntime.xml (created)
  testando\.idea\modules.xml (created)
  testando\.idea\runConfigurations\main_dart.xml (created)
  testando\.idea\workspace.xml (created)
  testando\.metadata (created)
  testando\android\app\build.gradle (created)
  testando\android\app\src\main\kotlin\br\com\ciolfi\testando\MainActivity.kt (created)
  testando\android\build.gradle (created)
  testando\android\testando_android.iml (created)
  testando\android\.gitignore (created)
  testando\android\app\src\debug\AndroidManifest.xml (created)
  testando\android\app\src\main\AndroidManifest.xml (created)
  testando\android\app\src\main\res\drawable\launch_background.xml (created)
  testando\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\Usuario\Desktop\testando\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path ='C:\src\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Acesso negado.
, errno = 5)".

A crash report has been written to C:\Users\Usuario\Desktop\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/Jf5AA

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jf5Ax
```

**Comment by RMXJR** [comment] 2020-06-17 03:32
C:\Users\Usuario>flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o 10.0.18362.900], locale pt-BR)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (12 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Usuario\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Usuario\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2020-06-17 08:43
possibly related to
https://github.com/flutter/flutter/issues/58529
https://github.com/flutter/flutter/issues/58928
https://github.com/flutter/flutter/issues/20579 (closed)

**Comment by jmagman** [comment] 2020-06-17 19:10
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```

**Comment by RMXJR** [comment] 2020-06-18 19:22
> possivelmente relacionado a
> [# 58529 ](https://github.com/flutter/flutter/issues/58529)
> [# 58928 ](https://github.com/flutter/flutter/issues/58928)
> [# 20579](https://github.com/flutter/flutter/issues/20579) (fechado)
> [# 50880](https://github.com/flutter/flutter/issues/50880)

como resolvo isso ?

**Comment by jonahwilliams** [comment] 2020-07-06 19:12
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-07-06 19:12 UTC
Labels: severe: crash, tool
