### ISSUE TITLE
Context menu API

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#30976] opened 2019-04-12 18:08 UTC
## Objective
Design a set of API for context menu that meets the following requirements:
- Easy and intuitive for developers to apply to their custom widgets
- Provide default context menu for certain widgets:
  - EditableText
  - SelectableText (upcoming)
  - _(Please add more)_
- Widgets with default context menu should allow override
- Menu should be rendered in proper style, which should be apparent to widgets
  - In a material app it should be rendered in Material PopupMenu
  - In a desktop app or on Web, it should be rendered in native menu (long-term goal)

**Comment by dkwingsmt** [comment] 2019-05-31 22:35
Progress as of 5/31/2019, https://github.com/flutter/flutter/pull/33685

## What's in this PR

![1](https://user-images.githubusercontent.com/1596656/58737182-7b274080-83b5-11e9-97da-e682481e189e.gif)

As shown in the GIF above, this PR contains the following features:
- Show a context menu when right clicking an editable text
- Correctly control focus and selection
- Change menu item according to context, and implement them
- Stall the style of text field when context menu is shown

Feature-wise this should be close to complete as a first phase, except for perhaps the following features:
- [ ] Shortcut
- [ ] Submenus

Please correct me if we have plan for more.

## Remaining question
### How to design the API for rendering control?

There are two dimensions of extensibility, which are independent from each other:
- Control the content: We should give some widgets (such as editable text) a default menu, while also allowing developers to extend it
- Control the rendering: The menu should be able to render in multiple ways, such as Material popup menu, other design languages, as well as native system menu, and this should be transparent to the widget.

This is why `EditableText` has two new parameters in this PR:
- `TextContextMenuFactory contextMenuFactory` controls content
- `RenderContextMenu renderContextMenu` controls render

It makes sense to add `contextMenuFactory` here, but `renderContextMenu` should really be configured for the entire app. I wonder what the idiomatic way is for this (should I design another class that has static method `.of`?)

### Will `RenderContextMenu` work for native menu?
I would really like to make it work on at least one platform before confirming. I assume GLFW doesn't support this and we can only test it on Mac.

### How to design API for menu entry?
It will very likely depend on the upcoming `Action` API.

**Comment by krisgiesing** [comment] 2019-06-03 17:43
Just so I understand the direction here: is the intention that (at least initially) the context menu would be drawn by Flutter rather than by the platform? This has the observable effect of needing to draw within Flutter's window, rather than at an edge where some of the rendering occurs outside the window.

**Comment by dkwingsmt** [comment] 2019-06-03 17:51
@krisgiesing Menu drawn by Flutter will be used on Android, or as a fallback (e.g. on GLFW).
The long-term plan is to eventually use native menu when possible, such as on Desktops and on Web.
Also +cc @stuartmorgan @gspencergoog

**Comment by dkwingsmt** [comment] 2019-08-05 17:53
Update as of 8/5/2019: 

Development on this has been paused.

Multiple problems were found. One of them is https://github.com/flutter/flutter/issues/34025, which severely affects user experience, but I'm not aware of solution or workaround unless we re-implement modals into multiple activities (?). 

I'm still planning to come back and implement a non-extensible context menu that supports basic operations at some point.

**Comment by gspencergoog** [comment] 2019-11-13 23:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/31955

**Closed by gspencergoog** 2019-11-13 23:52 UTC
Labels: a: desktop, framework, severe: new feature
