### ISSUE TITLE
Flutter console 't' command crashes (timeout)

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#17302] opened 2018-05-04 19:26 UTC
Run the gallery, start the bottom app bar demo, type 't' at the console.

After loads of output the app crashes:
```
TimeoutException: Request to Dart VM Service timed out: ext.flutter.debugDumpRenderTree({isolateId: isolates/71568905})
```

**Comment by zoechi** [comment] 2019-01-18 11:16
I couldn't reproduce
```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)
```

**Comment by jonahwilliams** [comment] 2019-03-24 20:12
I'm not able to reproduce, I believe this was fixed with the timeout removal

**Closed by jonahwilliams** 2019-03-24 20:12 UTC
Labels: tool
