### ISSUE TITLE
Gallery, Shrine, Dark theme: quantity selector doesn't match theme of Shrine

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5699] opened 2016-09-01 16:04 UTC
Open gallery, turn on Dark Mode, open shrine, select an item, and then open the Quantity selector:

![screenshot_20160901-090255](https://cloud.githubusercontent.com/assets/5479/18174639/0edd96f2-7023-11e6-9c47-7714f88213e3.png)

**Comment by sethladd** [comment] 2016-09-01 16:49
Also, Pesto:

![screen shot 2016-09-01 at 9 49 13 am](https://cloud.githubusercontent.com/assets/5479/18176180/62cc479e-7029-11e6-9ddb-d3c578183ffe.png)

**Comment by HansMuller** [comment] 2016-09-01 16:57
This is a duplicate of https://github.com/flutter/flutter/issues/5572

The underlying problem is non-trivial, see the comments for #5572

**Closed by HansMuller** 2016-09-01 16:57 UTC
Labels: customer: gallery, from: review, ⚠ bug

**Comment by sethladd** [comment] 2016-09-01 16:59
Thanks for de-duping :)
