### ISSUE TITLE
App crash if I create custom build type and build flutter application from android project

### ISSUE THREAD

**Issue by ngminhduong** [flutter/flutter#63374] opened 2020-08-10 09:57 UTC
As you known current flutter project not yet support custom build type (only support for debug, release, profile)
So I tried to create custom build type from build.gradle
```
    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            signingConfig signingConfigs.debug
        }

        staging {
            debuggable true
            applicationIdSuffix '.staging'
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }

        release {
            signingConfig signingConfigs.debug
        }
    }
```
And build flutter project from android project. (build android folder)
That allow us build with custom build type.
But with latest flutter release 
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.14.6 18G95, locale en-VN)
    • Flutter version 1.20.1 at /Users/flutter
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

```
It crash when I try to build staging due to
```
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: Build fingerprint: 'samsung/d1xx/d1:10/QP1A.190711.020/N970FXXS5CTG1:user/release-keys'
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: Revision: '23'
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: ABI: 'arm64'
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: Timestamp: 2020-08-10 16:51:08+0700
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: pid: 21258, tid: 21258, name: _flavor.staging  >>> com.fossil.flutter_app_test_flavor.staging <<<
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: uid: 10498
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG: Abort message: '[FATAL:flutter/shell/common/shell.cc(264)] Check failed: vm. Must be able to initialize the VM.
    '
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x0  0000000000000000  x1  000000000000530a  x2  0000000000000006  x3  0000007fee36ec00
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000080
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x8  00000000000000f0  x9  00000077bfd895e0  x10 0000000000000000  x11 0000000000000001
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x12 000000001cdde6b0  x13 0000000000000002  x14 0000000000000000  x15 0000000000000000
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x16 00000077bfe578c0  x17 00000077bfe34880  x18 00000077c3822000  x19 00000000000000ac
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x20 000000000000530a  x21 00000000000000b2  x22 000000000000530a  x23 00000000ffffffff
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x24 0000007fee371c38  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     x28 0000007fee3700c0  x29 0000007fee36ecb0
2020-08-10 16:51:08.582 21304-21304/? A/DEBUG:     sp  0000007fee36ebe0  lr  00000077bfde8330  pc  00000077bfde8360
2020-08-10 16:51:08.583 21304-21304/? A/DEBUG: backtrace:
2020-08-10 16:51:08.583 21304-21304/? A/DEBUG:       #00 pc 0000000000083360  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 13817077d0d892b63e2f982cf91d02fa)
2020-08-10 16:51:08.583 21304-21304/? A/DEBUG:       #01 pc 00000000002bcc80  /data/app/com.fossil.flutter_app_test_flavor.staging-rA9-QAfmUP2mkPL4nb8gGQ==/lib/arm64/libflutter.so (BuildId: b57a4557f090fa1289c835f596bfba88439338c8)
```
This crash happen after I update flutter. It seem work with previous release.

**Comment by TahaTesser** [comment] 2020-08-11 11:11
Hi @ngminhduong 
Just tried reproducing this issue on latest `stable`, no issues

<details> 
<summary>Code Sample</summary> 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.stable_flutter"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            signingConfig signingConfigs.debug
        }

        staging {
            debuggable true
            applicationIdSuffix '.staging'
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }

        release {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

``` 

</details> 

<details> 
<summary>logs</summary> 

```
Executing tasks: [:app:assembleStaging] in project C:\Users\Taha\AndroidStudioProjects\stable_flutter\android

> Task :app:compileFlutterBuildStaging
> Task :app:packLibsflutterBuildStaging
> Task :app:preBuild UP-TO-DATE
> Task :app:preStagingBuild UP-TO-DATE
> Task :app:compileStagingAidl NO-SOURCE
> Task :app:checkStagingManifest
> Task :app:compileStagingRenderscript NO-SOURCE
> Task :app:generateStagingBuildConfig
> Task :app:cleanMergeStagingAssets UP-TO-DATE
> Task :app:mergeStagingShaders
> Task :app:compileStagingShaders
> Task :app:generateStagingAssets
> Task :app:mergeStagingAssets
> Task :app:copyFlutterAssetsStaging
> Task :app:mainApkListPersistenceStaging
> Task :app:generateStagingResValues
> Task :app:generateStagingResources
> Task :app:createStagingCompatibleScreenManifests
> Task :app:processStagingManifest
> Task :app:mergeStagingResources
> Task :app:processStagingResources
> Task :app:compileStagingKotlin
> Task :app:checkStagingDuplicateClasses
> Task :app:javaPreCompileStaging
> Task :app:compileStagingJavaWithJavac
> Task :app:compileStagingSources
> Task :app:transformClassesWithDexBuilderForStaging
> Task :app:desugarStagingFileDependencies
> Task :app:processStagingJavaRes NO-SOURCE
> Task :app:validateSigningStaging
> Task :app:signingConfigWriterStaging
> Task :app:mergeStagingJniLibFolders
> Task :app:mergeStagingJavaResource
> Task :app:mergeStagingNativeLibs

> Task :app:stripStagingDebugSymbols
Compatible side by side NDK version was not found.
Unable to strip library 'C:\Users\Taha\AndroidStudioProjects\stable_flutter\build\app\intermediates\merged_native_libs\staging\out\lib\arm64-v8a\libflutter.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\Users\Taha\AndroidStudioProjects\stable_flutter\build\app\intermediates\merged_native_libs\staging\out\lib\armeabi-v7a\libflutter.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.

> Task :app:mergeExtDexStaging
> Task :app:mergeDexStaging
> Task :app:packageStaging
> Task :app:assembleStaging

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 18s
31 actionable tasks: 30 executed, 1 up-to-date

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Taha>flutters doctor -v
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
• 
```

</details>

**Comment by ngminhduong** [comment] 2020-08-11 11:26
Hi @TahaTesser 


Can you help to run my example from attachment
[flutter_app_test_flavor.zip](https://github.com/flutter/flutter/files/5056629/flutter_app_test_flavor.zip)

I also include log when I run app with staging build type.
```

08/11 18:23:56: Launching 'app' on samsung SM-N970F.
$ adb shell am start -n "com.fossil.flutter_app_test_flavor.staging/com.fossil.flutter_app_test_flavor.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.fossil.flutter_app_test_flavor.staging.test | com.fossil.flutter_app_test_flavor.staging
Waiting for application to come online: com.fossil.flutter_app_test_flavor.staging.test | com.fossil.flutter_app_test_flavor.staging
Connected to process 21022 on device 'samsung-sm_n970f-R58N11VD1ZH'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.fossil.flutter_app_test_flavor.staging is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Waiting for application to come online: com.fossil.flutter_app_test_flavor.staging.test | com.fossil.flutter_app_test_flavor.staging
Connecting to com.fossil.flutter_app_test_flavor.staging
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.fossil.flutter_app_test_flavor.staging is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Connected to the target VM, address: 'localhost:8602', transport: 'socket'
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1461)
E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
    [ERROR:flutter/runtime/dart_vm.cc(247)] Could not setup VM data to bootstrap the VM from.
    [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
A/flutter: [FATAL:flutter/shell/common/shell.cc(264)] Check failed: vm. Must be able to initialize the VM.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21022 (_flavor.staging), pid 21022 (_flavor.staging)
Disconnected from the target VM, address: 'localhost:8602', transport: 'socket'
```

**Comment by ngminhduong** [comment] 2020-08-11 13:04
Hi @TahaTesser
Can you reproduce issue from my example?

**Comment by TahaTesser** [comment] 2020-08-12 07:35
<details> 
<summary>logs</summary> 

```
08/12 13:02:21: Launching 'app' on samsung SM-M305F.
$ adb shell am start -n "com.fossil.flutter_app_test_flavor.staging/com.fossil.flutter_app_test_flavor.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4330 on device 'samsung-sm_m305f-32003c30dc19668f'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ActivityThread: setConscryptValidator
    setConscryptValidator - put
E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
    [ERROR:flutter/runtime/dart_vm.cc(247)] Could not setup VM data to bootstrap the VM from.
    [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
A/flutter: [FATAL:flutter/shell/common/shell.cc(264)] Check failed: vm. Must be able to initialize the VM.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4330 (_flavor.staging), pid 4330 (_flavor.staging)

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1) 
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

</details>

**Comment by ngminhduong** [comment] 2020-08-12 08:21
Hi @TahaTesser 
This is blocked issue for us to release.
I think this issue should be mark as blocked issue and should be fixed asap.

**Comment by ngminhduong** [comment] 2021-02-26 09:00
Hi, any update for this issue.

**Comment by huycozy** [comment] 2022-12-28 11:14
@ngminhduong This issue seems to have been fixed on the latest `stable` and `master` channels since I can not see the crash anymore. 

Please try running below updated sample code (be compatible with new Flutter versions) and confirm if this issue is fixed.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.92, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.92 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4e08ebb2bf (2 hours ago), 2022-12-27 19:31:24 -0500
    • Engine revision 8294e2693a
    • Dart version 3.0.0 (build 3.0.0-66.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

[flutter_app_test_flavor.zip](https://github.com/flutter/flutter/files/10313837/flutter_app_test_flavor.zip)

**Comment by ngminhduong** [comment] 2023-02-07 09:51
Hi @huycozy 
I found the crash have been resolved
But could you consider support build command from flutter for custom build type
Example: flutter build apk --staging

**Comment by huycozy** [comment] 2023-02-07 10:53
@ngminhduong You can try with `--flavor <flavor-name>` (please see https://docs.flutter.dev/deployment/flavors#launching-your-app-flavors as reference)

**Comment by ngminhduong** [comment] 2023-02-09 06:24
@huycozy We need different build type for the same flavor
Example: 
App1:
- flutter build apk --flavor App1 --staging
- flutter build apk --flavor App1 --release

App2:
- flutter build apk --flavor App2 --staging
- flutter build apk --flavor App2 --release

**Comment by huycozy** [comment] 2023-02-13 04:01
@ngminhduong I'm not sure I can understand that proposal currently but the issues should be solved separately. Since this issue no longer occurs, I will close this issue from here. 

With regard to build type for flavor issue, I recommend checking existing issues, if there is no one similar to your case, please file a [proposal issue](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) so that we may verify the issue.

Thank you!

**Closed by huycozy** 2023-02-13 04:01 UTC
Labels: severe: crash, platform-android, tool, dependency: dart, a: build, a: release, has reproducible steps, P4, found in release: 1.20
