### ISSUE TITLE
Clarify iOS Flutter view integration into existing apps

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#13767] opened 2017-12-25 01:43 UTC
Hello , I have seen the flutter_view sample ,but I want to know how to embed a FlutterView inside an Android and an iOS app from zero. I can not find any documents to tell me what should do .

My exsiting project is a huge one , it is impossible to run flutter create to make a new project .
I just want to call a fullter view from my exisiting swift view ,what I need is a step-by-step guide .
If there is a no-storyboard sample ,maybe we can learn it clearly.

1. Using the IntelliJ to edit and generate a App.framework ,and drag it to existing project , right?
Could we change the naem of App.framework? Could we embed multiple App.framework ?(Because we have a lot business teams ,we want to isolate the codes.)
2. After embed App.framework and Flutter.framework, what should be set?
3. Is there only one FlutterViewController ? as the only entrance of Flutter world?
4. Why there is a flutter_assets file ? Why not embed all images into the App.framewok?
5. What does the App.framework do? 
6. Sometime the variables in Generated.xcconfig are not put into the iOS project, how to set it menually?
7. If someone get my App.framework file, how to prevent he to use it in his project?
8. How to init a FlutterViewController in an swift UIViewController of existing project? or it can only be init in the AppDelegate?

9. I copy the whole Flutter folder of flutter_view sample to my existing iOS project , add the pods of flutter and  embeded the framework.
self.navigationController?.pushViewController(FlutterViewController(), animated: true), there is only one whitescreen, any other things I should do?

**Comment by xster** [comment] 2018-01-03 17:44
Since there's already a generic issue for documenting Flutter embedding #8945, let's turn this into specific questions for iOS integration

**Comment by xster** [comment] 2018-01-03 17:45
cc @cbracken

**Comment by zoechi** [comment] 2018-12-03 17:35
Should this be moved to flutter/website?

**Comment by xster** [comment] 2019-01-04 23:48
@matthew-carroll this is probably a dupe of something. I tagged your a2a project tentatively but feel free to merge or cleanup.

**Comment by jmagman** [comment] 2019-10-16 23:47
@gaaclarke

**Comment by jmagman** [comment] 2019-10-16 23:53
We've added more features and documentation since the end of 2017. https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios should answer some of these.

> 2. After embed App.framework and Flutter.framework, what should be set?

You should not need to manually embed either framework in your existing application.  This is handled by CocoaPods.

> 4. Why there is a flutter_assets file ? Why not embed all images into the App.framewok?

This was removed with https://github.com/flutter/flutter/pull/26630.

> 5. What does the App.framework do? 

That's your compiled dart code.

> 6. Sometime the variables in Generated.xcconfig are not put into the iOS project, how to set it menually?

You should no longer need to use Generated.xcconfig in your existing app.

> 8. How to init a FlutterViewController in an swift UIViewController of existing project? or it can only be init in the AppDelegate?

It does not need to be from the AppDelegate.  See https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#write-code-to-use-flutterviewcontroller-from-your-host-app.

**Comment by xster** [comment] 2019-10-26 03:33
Thanks for looping back to this @jmagman. Since this was a combo question-issue from 2017 (and we've probably spoken since @realcarlos), I'll close this issue. Please feel free to open other issues if you run into issues with your integration!

**Closed by xster** 2019-10-26 03:33 UTC
Labels: a: existing-apps, d: website - content, engine, ⌺‬ platform-ios
