### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'streamListen' was called on null.Receiver: nullTried calling: streamListen("Extension")

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#75688] opened 2021-02-09 06:59 UTC
## Command
```
flutter --no-color run --machine --device-id=3d21e2bf --profile --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:60536 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'streamListen' was called on null.
Receiver: null
Tried calling: streamListen("Extension")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1513:21)
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1318:11)
#3      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1309:11)
#4      ResidentRunner.serveAndAnnounceDevTools (package:flutter_tools/src/resident_runner.dart:1301:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel 0201nested, 1.26.0-18.0.pre.216, on Microsoft Windows [Version 10.0.17763.1518], locale en-US)
    • Flutter version 1.26.0-18.0.pre.216 at F:\flutter_dev\src_new\flutter
    • Framework revision 105eb2ff93 (4 hours ago), 2021-02-09 11:10:04 +0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • CPH2091 (mobile)  • 3d21e2bf • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.17763.1518]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 88.0.4324.146

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: e1bdf2c00a7c4433a47803178d6a1210fcaf3197

**Comment by pedromassangocode** [comment] 2021-02-09 08:04
Duplicate of https://github.com/flutter/flutter/issues/75466.

**Closed by pedromassangocode** 2021-02-09 08:04 UTC
Labels: severe: crash, tool
