### ISSUE TITLE
[in_app_purchase] _$BillingResponseEnumMap doesn't contain the NETWORK_ERROR (Error Code 12)

### ISSUE THREAD

**Issue by serhii-k** [flutter/flutter#135540] opened 2023-09-27 00:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Steps to reproduce

There is an unhandled NETWORK_ERROR (Error Code 12) in _$BillingResponseEnumMap.

[https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.g.dart#L9](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.g.dart#L9)

Docs:
[https://developer.android.com/google/play/billing/errors#network_error_error_code_12](https://developer.android.com/google/play/billing/errors#network_error_error_code_12)

### Logs

<details><summary>Logs</summary>

```console
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Invalid argument(s): `12` is not one of the supported values: -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8
#00 pc 0x3b9433 com.example ($enumDecode [enum_helpers.dart:83]) (BuildId: 349b90035e514d04af40333aa39dd131)
#01 pc 0x3bb8ef com.example (BillingResponseConverter.fromJson [billing_client_wrapper.dart:432]) (BuildId: 349b90035e514d04af40333aa39dd131)
#02 pc 0x3bb803 com.example (_$BillingResultWrapperFromJson [billing_response_wrapper.g.dart:12]) (BuildId: 349b90035e514d04af40333aa39dd131)
#03 pc 0x3bb767 com.example (new BillingResultWrapper.fromJson [billing_response_wrapper.dart:40]) (BuildId: 349b90035e514d04af40333aa39dd131)
#04 pc 0x63aa8f com.example (_$ProductDetailsResponseWrapperFromJson [product_details_wrapper.g.dart:35]) (BuildId: 349b90035e514d04af40333aa39dd131)
#05 pc 0x728c73 com.example (BillingClient.queryProductDetails [product_details_wrapper.dart:127]) (BuildId: 349b90035e514d04af40333aa39dd131)
#06 pc 0x69a33f com.example (_SuspendState._createAsyncStarCallback.<anonymous closure> [async_patch.dart:379]) (BuildId: 349b90035e514d04af40333aa39dd131)
#07 pc 0x2973df com.example (_FutureListener.handleValue [zone.dart:1661]) (BuildId: 349b90035e514d04af40333aa39dd131)
#08 pc 0x6bdeab com.example (Future._propagateToListeners.handleValueCallback [future_impl.dart:784]) (BuildId: 349b90035e514d04af40333aa39dd131)
#09 pc 0x292f8b com.example (Future._propagateToListeners [future_impl.dart:813]) (BuildId: 349b90035e514d04af40333aa39dd131)
#10 pc 0x2942df com.example (Future._completeWithValue [future_impl.dart:584]) (BuildId: 349b90035e514d04af40333aa39dd131)
#11 pc 0x69a983 com.example (_SuspendState._returnAsyncNotFuture [async_patch.dart:365]) (BuildId: 349b90035e514d04af40333aa39dd131)
#12 pc 0x69a33f com.example (_SuspendState._createAsyncStarCallback.<anonymous closure> [async_patch.dart:379]) (BuildId: 349b90035e514d04af40333aa39dd131)
#13 pc 0x2973df com.example (_FutureListener.handleValue [zone.dart:1661]) (BuildId: 349b90035e514d04af40333aa39dd131)
#14 pc 0x6bdeab com.example (Future._propagateToListeners.handleValueCallback [future_impl.dart:784]) (BuildId: 349b90035e514d04af40333aa39dd131)
#15 pc 0x292f8b com.example (Future._propagateToListeners [future_impl.dart:813]) (BuildId: 349b90035e514d04af40333aa39dd131)
#16 pc 0x2942df com.example (Future._completeWithValue [future_impl.dart:584]) (BuildId: 349b90035e514d04af40333aa39dd131)
#17 pc 0x69aabb com.example (_SuspendState._returnAsync [async_patch.dart:350]) (BuildId: 349b90035e514d04af40333aa39dd131)
#18 pc 0x69a33f com.example (_SuspendState._createAsyncStarCallback.<anonymous closure> [async_patch.dart:379]) (BuildId: 349b90035e514d04af40333aa39dd131)
#19 pc 0x2973df com.example (_FutureListener.handleValue [zone.dart:1661]) (BuildId: 349b90035e514d04af40333aa39dd131)
#20 pc 0x6bdeab com.example (Future._propagateToListeners.handleValueCallback [future_impl.dart:784]) (BuildId: 349b90035e514d04af40333aa39dd131)
#21 pc 0x292f8b com.example (Future._propagateToListeners [future_impl.dart:813]) (BuildId: 349b90035e514d04af40333aa39dd131)
#22 pc 0x2942df com.example (Future._completeWithValue [future_impl.dart:584]) (BuildId: 349b90035e514d04af40333aa39dd131)
#23 pc 0x29424b com.example (Future._asyncCompleteWithValue.<anonymous closure> [future_impl.dart:657]) (BuildId: 349b90035e514d04af40333aa39dd131)
#24 pc 0x293a0b com.example (_microtaskLoop [schedule_microtask.dart:40]) (BuildId: 349b90035e514d04af40333aa39dd131)
#25 pc 0x6bc963 com.example (_startMicrotaskLoop [schedule_microtask.dart:49]) (BuildId: 349b90035e514d04af40333aa39dd131)
#26 pc 0x29397b com.example (_startMicrotaskLoop [schedule_microtask.dart:44]) (BuildId: 349b90035e514d04af40333aa39dd131)
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-27 07:40
Thanks for drawing our attention to this. 

Labeling for the team's attention.

**Comment by tbm98** [comment] 2023-10-12 05:19
I have same issue.
Got noticed from firebase crashes

**Comment by nadrolinux** [comment] 2023-10-13 21:27
+1. I noticed the same issue.

**Comment by putnokiabel** [comment] 2023-10-20 09:36
Experiencing the same issue!

Ideally the fix for this wouldn't just add handling for error code 12, but would _also_ make sure that unknown error codes are caught under an "unknown error" case or similar, instead of just crashing the app, making the package more future-proof and preventing issues like this from popping up again.

**Comment by usamanisarAHADTECH** [comment] 2023-10-26 08:08
i am using billing library com.android.billingclient:billing:6.0.1 and in_app_purchase: ^3.1.11,
getting this error on while getting the products 
inAppPurchase.queryProductDetails(getProductIdsOnly(storeProductIds).toSet());

Where the issue is 
I/flutter (17215): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (17215): Invalid argument(s): `12` is not one of the supported values: -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8
I/flutter (17215): #0      $enumDecode (package:json_annotation/src/enum_helpers.dart:83:5)
I/flutter (17215): #1      BillingResponseConverter.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:432:12)
I/flutter (17215): #2      _$BillingResultWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_response_wrapper.g.dart:12:12)
I/flutter (17215): #3      new BillingResultWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_response_wrapper.dart:40:12)
I/flutter (17215): #4      _$ProductDetailsResponseWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/product_details_wrapper.g.dart:35:32)
I/flutter (17215): #5      new ProductDetailsResponseWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/product_details_wrapper.dart:127:7)
I/flutter (17215): #6      BillingClient.queryProductDetails (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:153:42)
I/flutter (17215): <asynchronous suspension>
I/flutter (17215): #7      BillingClientManager.runWithClient (package:in_app_purchase_and
I/flutter (17215): ----------------------------------------------------

**Comment by putnokiabel** [comment] 2023-10-26 10:02
Anyone know if there is a previous version I can downgrade to in the meantime that does not have this issue?

**Comment by usamanisarAHADTECH** [comment] 2023-10-26 12:10
Their are several ways to fix this issue for now, as we know this is related to internet connection, you can add internet check on this **inAppPurchase.queryProductDetails(getProductIdsOnly(storeProductIds));**.
Secondly you can wrap this in try and catch block and you can also fix this to downgrade your billing library to 
 **"com.android.billingclient:billing5.2.1"**. 
I hope this will work, thanks.

**Comment by putnokiabel** [comment] 2023-10-27 08:48
Thank you for your suggestions @usamanisarAHADTECH ! 😄

**Comment by nadrolinux** [comment] 2023-10-30 15:07
@putnokiabel imo the best solution at now is apply this patch yourself on downloaded/cached library:
https://github.com/flutter/packages/pull/5120/files

**Closed** 2023-10-30 22:23 UTC
Labels: platform-android, p: in_app_purchase, package, good first issue, P2, team-android, triaged-android, fyi-ecosystem
