### ISSUE TITLE
Cannot archive/ build ipa of flutter app after adding Apple Watch Extension in ios

### ISSUE THREAD

**Issue by sayan-futurehook** [flutter/flutter#110075] opened 2022-08-23 11:50 UTC
## Problem
I added a WatchOS app to iOS in my Flutter project following these reference https://docs.flutter.dev/development/platform-integration/ios/apple-watch and https://medium.com/@ferrazrx/flutter-apple-watch-swift-b43110dc4545. After that I was not able to run app from VSCode for iOS, but from Xcode I was able to build on my device in debug mode. Now when I am using Archive to ship the app to AppStore I am getting the following error, I even tried to build ipa using `flutter build ipa --release` , but it showed similar error.
![Screenshot 2022-08-23 at 4 49 23 PM](https://user-images.githubusercontent.com/110037874/186148495-b7d5e823-c152-4f74-afe0-d4e93720cd6e.png)

## Steps to Reproduce

Adding WatchOS app in Xcode to iOS app following https://docs.flutter.dev/development/platform-integration/ios/apple-watch

<details>
  <summary>Logs</summary>

`flutter run -v`

```
           
[   +1 ms] Error (Xcode): unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator'
           
[        ] Error (Xcode): Couldn't look up product type 'com.apple.product-type.application.watchapp2' in domain 'iphonesimulator': Couldn't load spec with identifier 'com.apple.product-type.application.watchapp2' in domain 'iphonesimulator'
           
[        ] Error (Xcode): unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator'
           
[        ] Error (Xcode): Couldn't look up product type 'com.apple.product-type.watchkit2-extension' in domain 'iphonesimulator': Couldn't load spec with identifier 'com.apple.product-type.watchkit2-extension' in domain 'iphonesimulator'
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on Sayan's iPhone.
[   +1 ms] "flutter run" took 18,282ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +45 ms] ensureAnalyticsSent: 44ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

`flutter doctor -v`

```
mac_mini@Mac-minis-Mac-mini curious_fly % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mac_mini/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac_mini/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 18.0.2+9-61)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Users/mac_mini/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • Sayan's iPhone (mobile)     • FA837FE1-E666-439D-8063-7069EC941B15 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-08-23 12:59
Closing as duplicate of https://github.com/flutter/flutter/issues/92294

**Closed** 2022-08-23 12:59 UTC
Labels: in triage, r: duplicate
