### ISSUE TITLE
Web - Invalid value in Timepicker (input mode) changes input field size.

### ISSUE THREAD

**Issue by Itzuko** [flutter/flutter#103353] opened 2022-05-09 18:09 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample or open [Dartpad example](https://dartpad.dev/?id913731a95aca676eef367372e822b769)
2. When I change the timepicker to manual input mode and then give invalid values like hours > 24 or Minutes > 60 then the size of the invalid box changes and shrinks. (see images)

**Expected results:** 
The expected result would be that the box does not get smaller, when the value is invalid.
![flutter_bug_expected](https://user-images.githubusercontent.com/49077286/167469825-38c851ff-7726-4d68-b4c4-b60427f310e0.png)
**Actual results:** 
The Box gets smaller when an invalid value is used.
![flutter_bug](https://user-images.githubusercontent.com/49077286/167469821-0c2f2a53-c3bb-4af8-a138-4a4b74fc1397.png)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter TimePicker',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() {
    return _MyHomePageState();
  }
}

class _MyHomePageState extends State<MyHomePage> {
  TimeOfDay selectedTime = TimeOfDay.now();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter TimePicker"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                _selectTime(context);
              },
              child: Text("Choose Time"),
            ),
            Text("${selectedTime.hour}:${selectedTime.minute}"),
          ],
        ),
      ),
    );
  }

  _selectTime(BuildContext context) async {
    final TimeOfDay? timeOfDay = await showTimePicker(
      context: context,
      initialTime: selectedTime,
      initialEntryMode: TimePickerEntryMode.dial,
    );
  }
}

```

</details>

**Tested on**
- stable 2.10.5
- beta 2.13.0 - 0.3.pre

**Comment by darshankawar** [comment] 2022-05-10 07:19
Thanks for the report. This seems to be only occuring on web and that too using canvaskit, as, using html rendering, it works as expected along with on mobile (ios) and desktop (macos):

1. Web - canvaskit:

<img width="354" alt="Screenshot 2022-05-10 at 12 42 53 PM" src="https://user-images.githubusercontent.com/67046386/167571305-e21968e3-cd95-438a-9b1c-77a65dfd141e.png">

2. Web - html, mobile and macOS:

<img width="321" alt="Screenshot 2022-05-10 at 12 35 05 PM" src="https://user-images.githubusercontent.com/67046386/167571357-d81418bf-0912-462d-85c5-c1b9f98cade6.png">

<img width="321" alt="Screenshot 2022-05-10 at 12 35 05 PM" src="https://user-images.githubusercontent.com/67046386/167571460-eb9d5614-bc4f-4f4c-8a3e-51df25ecaeba.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.5 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.1006, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.1006 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f86dfdd2b7 (69 minutes ago), 2022-05-10 10:24:08 +0530
    • Engine revision 8774c24f65
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by yjbanov** [comment] 2022-05-12 18:09
According to #103635 this is related to https://github.com/flutter/flutter/issues/75837, possibly a duplicate.

**Comment by hterkelsen** [comment] 2022-10-19 21:48
Duplicate of https://github.com/flutter/flutter/issues/110563

**Closed by hterkelsen** 2022-10-19 21:48 UTC
Labels: framework, engine, f: date/time picker, platform-web, e: web_canvaskit, has reproducible steps, P4, found in release: 2.10, found in release: 2.13
