### ISSUE TITLE
STS_GLApi : DTS, ODTC are not allowed for Package 

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#51721] opened 2020-03-01 03:02 UTC
When I was debugging this error messaging coming on my console. Network is connected, Location is enable. Why is that? Is that issue on Firestore?

```
D/libGLESv2(11719): STS_GLApi : DTS, ODTC are not allowed for Package : com.demo.dev
W/zygote64(11719): Skipping duplicate class check due to unrecognized classloader
I/DynamiteModule(11719): Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3
I/DynamiteModule(11719): Selected local version of com.google.android.gms.flags
W/DynamiteModule(11719): Local module descriptor class for providerinstaller not found.
D/ConnectivityManager(11719): requestNetwork; CallingUid : 10868, CallingPid : 11719
I/DynamiteModule(11719): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(11719): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/zygote64(11719): find the special shared library, skip check
I/zygote64(11719): find the special shared library, skip check
I/zygote64(11719): Failed to open app image /data/app/com.google.android.gms-hB2cPXA9qy2DYi6Ad6koKA==/oat/arm64/base.art Failed to open '/data/app/com.google.android.gms-hB2cPXA9qy2DYi6Ad6koKA==/oat/arm64/base.art'
W/BiChannelGoogleApi(11719): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@d4dec1
V/NativeCrypto(11719): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
D/NetworkSecurityConfig(11719): No Network Security Config specified, using platform default
I/ProviderInstaller(11719): Installed default security provider GmsCore_OpenSSL
D/ConnectivityManager(11719): requestNetwork; CallingUid : 10868, CallingPid : 11719
W/BiChannelGoogleApi(11719): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@d4dec1
D/FirebaseAuth(11719): Notifying id token listeners about user ( 9zD91GkB5aX8jd4m428nVwOg8yB3 ).
W/Firestore(11719): (21.3.0) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.
I/zygote64(11719): Do full code cache collection, code=120KB, data=84KB
I/zygote64(11719): After code cache collection, code=107KB, data=62KB
I/zygote64(11719): Do partial code cache collection, code=124KB, data=73KB
I/zygote64(11719): After code cache collection, code=124KB, data=73KB
I/zygote64(11719): Increasing code cache capacity to 512KB
D/ViewRootImpl@24391fb[MainActivity](11719): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 495703769088} changed=false
I/System.out(11719): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(11719): (HTTPLog)-Static: isSBSettingEnabled false
E/StorageException(11719): StorageException has occurred.
E/StorageException(11719): Object does not exist at location.
E/StorageException(11719):  Code: -13010 HttpResult: 404
E/StorageException(11719): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(11719): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(11719): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(com.google.firebase:firebase-storage@@17.0.0:455)
E/StorageException(11719): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(com.google.firebase:firebase-storage@@17.0.0:435)
E/StorageException(11719): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(com.google.firebase:firebase-storage@@17.0.0:426)
E/StorageException(11719): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@17.0.0:280)
E/StorageException(11719): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@17.0.0:294)
E/StorageException(11719): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@17.0.0:70)
E/StorageException(11719): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@17.0.0:62)
E/StorageException(11719): 	at com.google.firebase.storage.GetDownloadUrlTask.run(com.google.firebase:firebase-storage@@17.0.0:74)
E/StorageException(11719): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/StorageException(11719): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/StorageException(11719): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by JosepBove** [comment] 2020-03-01 21:37
Hi @bhanuka96 
on what OS are you debugging?
Could you please provide your `flutter build -verbose`?
Thank you

**Comment by iapicca** [comment] 2020-03-02 08:28
Hi @bhanuka96 

if you believe the issue is caused by [cloud_firestore](https://pub.dev/packages/cloud_firestore)
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

otherwise 
could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

thank you

**Comment by gaiousantonio0909** [comment] 2020-03-09 00:03
I also have that problem but in ios it seems working fine. but when I run it on android it crashes giving a response in the console log.
D/libGLESv2(13279): STS_GLApi : DTS, ODTC are not allowed for Package : com.mypackage

**Comment by iapicca** [comment] 2020-03-09 12:52
Hi @gaiousantonio0909 
could you please provide the [info](https://github.com/flutter/flutter/issues/51721#issuecomment-593280235) needed,
thank you

**Comment by jbcaveman** [comment] 2020-03-11 18:23
I am having this issue. I will attach my info.

[flutter_doctor.txt](https://github.com/flutter/flutter/files/4320043/flutter_doctor.txt)
[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/4320044/flutter_run_verbose.txt)

[pubspec.txt](https://github.com/flutter/flutter/files/4320049/pubspec.txt)

**Comment by wolfc01** [comment] 2020-04-29 10:59
Using android studio, start a new flutter project.  Start debug, I get the following on the debug console:

Launching lib\main.dart on SM G930F in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
D/FlutterActivity(32167): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(32167): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(32167): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(32167): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(32167): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@7aeda21
D/FlutterActivityAndFragmentDelegate(32167): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:53114/D6oz9sUb_4o=/ws
Syncing files to device SM G930F...
**D/libGLESv2(32167): STS_GLApi : DTS, ODTC are not allowed for Package : nl.test.flutterapp**

The app runs apparently fine, despite the message in bold above.

[flutter_doctor_verbose.txt](https://github.com/flutter/flutter/files/4551221/flutter_doctor_verbose.txt)

**Comment by mthan160** [comment] 2020-06-15 12:24
I get the same issue on my SM-G935F model - perhaps it is linked to the phone in use

**Comment by wibimaster** [comment] 2020-06-28 16:34
Same here ; phone SM A520F (Samsung Galaxy A5 2017)
But no crash and the app' runs fine ; just the error on the android studio console...

**Comment by gaiousantonio0909** [comment] 2020-06-29 16:47
> Same here ; phone SM A520F (Samsung Galaxy A5 2017)
> But no crash and the app' runs fine ; just the error on the android studio console...

I have solved this issue way longer. Check your build flutter clean and rebuild.

**Comment by sohan42** [comment] 2020-08-10 07:20
> I have solved this issue long ago. Check your build flutter clean and rebuild.
Can you explain more about how did you solved this issue. i'm having a same issue. 
_(Error_ waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on SM A500H.)

**Comment by SulaimanDev11** [comment] 2020-09-03 12:22
i also faced the same issue while using geolocator^3.0.1 package to get the current position of mobile, the issue was that, i keep the locationAccuracy.high instead of locationAccuracy.low
by replacing high to low i solved my problem.
Position position = await getCurrentPosition(desiredAccuracy: LocationAccuracy.low);

**Comment by awaik** [comment] 2020-10-25 09:29
in my case, it was errors in build.gradle files
check all that you should do here https://firebase.flutter.dev/docs/installation/android
and in Firebase (image attached)
<img width="574" alt="Screenshot 2020-10-25 at 12 27 40" src="https://user-images.githubusercontent.com/5330807/97103457-ab176800-16bd-11eb-9854-fa6e1db4ffb6.png">

**Comment by Osmel1999** [comment] 2021-01-10 02:55
i had the same issue, and i was checking the documentation and my problem was the MinSDK Version, i go to android/app/build.gradle and there i chage the [minSdkVersion: 16] to  [minSdkVersion: 21], 'cause firebase need that at least MinSDK Version 19.

**Comment by stuartmorgan** [comment] 2021-04-07 19:54
This issue seems to be about two completely unrelated error log messages at the same time, one from OpenGL, and one from a network failure in Firebase internals. Neither seems at all related to the google_sign_in plugin.

For anyone else seeing either of the errors, if you have repro steps for it that do not involve third-party plugins please file a new issue (just about the one specific issue you are seeing). Closing this issue as it's gotten confused as to which issue is "the issue" people are referring to.

**Closed by stuartmorgan** 2021-04-07 19:54 UTC
Labels: p: first party, p: google_sign_in, platform-android, plugin, severe: crash
