### ISSUE TITLE
[local_auth] support localizedFallbackTitle in IOSAuthMessages

### ISSUE THREAD

**Issue by kaparray** [flutter/flutter#53205] opened 2020-03-24 23:26 UTC
Add support localizedFallbackTitle in IOSAuthMessages.

This field in IOS local_auth plugin.
![IMG_59C475EFD4DC-1](https://user-images.githubusercontent.com/31259204/77486135-f6c01580-6e3f-11ea-88f2-45d62b099a65.jpeg)

**Comment by kaparray** [comment] 2020-03-24 23:29
How request code review in my PR?

**Comment by TahaTesser** [comment] 2020-03-25 11:09
Hi @kaparray 

You can review from here in your PR

<img width="516" alt="Screenshot 2020-03-25 at 4 39 11 PM" src="https://user-images.githubusercontent.com/48603081/77530373-39710480-6eb7-11ea-8e8b-555e72996fa2.png">

Thank you for your contribution

**Comment by kaparray** [comment] 2020-04-19 11:45
@TahaTesser Do you know the updates? I need this functionality in my production app!

**Comment by abdulrojak288** [comment] 2020-09-22 03:19
why can't I use the localized Fallback Title in IOSAuthMessages function ????

**Comment by stuartmorgan** [comment] 2021-04-02 20:08
Closing as a duplicate of https://github.com/flutter/flutter/issues/34638

**Closed by stuartmorgan** 2021-04-02 20:08 UTC
Labels: P5, p: first party, p: local_auth, platform-ios, plugin, severe: new feature, waiting for PR to land (fixed)
