### ISSUE TITLE
Plugin google_maps_flutter: animateCamera doesn't work on iPhone (Simulator?)

### ISSUE THREAD

**Issue by Tobi696** [flutter/flutter#70033] opened 2020-11-07 19:30 UTC
```dart
onMapCreated: (controller) => setState(() {
  googleMapController = controller;
  controller.moveCamera(
      CameraUpdate.newCameraPosition(CameraPosition(
    target: LatLng(0, 0),
    zoom: 1,
  )));
  controller
      .animateCamera(CameraUpdate.newLatLngBounds(
    LatLngBounds(
      southwest: LatLng(minLatitude, minLongitude),
      northeast: LatLng(maxLatitude, maxLongitude),
    ),
    80,
  ));
}),
```

This code works perfectly fine on Android Emulator, but on IOs Simulator, the CameraPosition is only changed to LatLng(0,0), but the animateCamera(CameraUpdate.newLatLngBounds(LatLngBounds(...))) doesn't work.

**Comment by TahaTesser** [comment] 2020-11-09 08:47
Hi @Tobi696 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`  and a complete reproducible minimal code sample
Thank you

**Comment by Tobi696** [comment] 2020-11-17 12:28
Sorry for my long delay, it took me some time to reproduce the issue in a small application.
Please check out [google_maps_minimal](https://github.com/Tobi696/google_maps_minimal) and follow the README to reproduce the issue.

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G46c darwin-x64, locale en-AT)
    • Flutter version 1.22.4 at /Users/tobias/flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to
      that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • C9799704-2248-4DE3-8C78-EBAEFE538733 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

```

**Comment by TahaTesser** [comment] 2020-11-18 09:40
Hi @Tobi696 
I can reproduce it on an iOS simulator and partially on a physical device 
The main issue is animate camera work inside `onMapCreated`, you can call the same code after the map is created from a button or something, it works fine. Duplicate of https://github.com/flutter/flutter/issues/34473

- #### Simulator often doesn't work
- #### iOS Physical doesn't work in the first run but when hot reload, it seems to work
- #### Works on Android


[ Simulator | iOS Physical | Android  |
| --------------- | --------------- | --------------- |
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/99510895-97ee7400-29ad-11eb-8043-a0be7791ae3f.gif) | ![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/99511389-34b11180-29ae-11eb-92a8-ab89c14d6ed2.gif) | ![Screen Recording 2020-11-18 at 2 44 25 PM](https://user-images.githubusercontent.com/48603081/99512888-03394580-29b0-11eb-9f26-74193541f08d.gif)


Here I simplified your big code sample into a small minimal code sample 
 
<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(0, 0),
    zoom: 1,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);

          controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
        },
      ),
    );
  }
}

```

</details>




I see there's an open issue addressing the case you described. 
Duplicate of https://github.com/flutter/flutter/issues/34473
[Workaound](https://github.com/flutter/flutter/issues/34473#issuecomment-592962722)
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-18 09:40 UTC
Labels: in triage

**Comment by Anas-jed** [comment] 2021-04-26 09:59
@TahaTesser you said to implement animate camera on OnMapCreated, i am struggling it with scenario where after OnMapCreated is called and then in app i give some new address and try to update animate camera with mapController and it doesn't working even after hot reload...
<details>
<summary>Flutter Doctor</summary>

 ```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/slashglobal/flutter
    • Framework revision b1395592de (4 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/slashglobal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • d6d4129a0eafa3d177d3847ef794d8287a785e67 • ios • iOS 14.4.2

• No issues found!

```
</details> 

I already checked similar issues,  #34473 , #70600 , #70033

<details>
<summary>Minimal Code to Display</summary>

    CameraPosition cameraPosition = new CameraPosition(
        target: LatLng(latLng.latitude, latLng.longitude), zoom: 14);
   
    await mapControllerr
        .animateCamera(CameraUpdate.newCameraPosition(cameraPosition));
</details>

**Comment by TahaTesser** [comment] 2021-04-26 12:57
@Anas-jed 
I have updated the issue https://github.com/flutter/flutter/issues/34473#issuecomment-824759178
