### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'toFilePath' was called on null.Receiver: nullTried calling: toFilePath()

### ISSUE THREAD

**Issue by fagottino** [flutter/flutter#52914] opened 2020-03-19 23:18 UTC
Hi, can someone tell me where's theproblem with building my existing project with flutter web?

There's the log. Thank you so much!

## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Versione 10.0.18363.720], locale it-IT)
    • Flutter version 1.15.17 at C:\flutterBETA
    • Framework revision 2294d75bfa (13 days ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\tools
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.0)
    • VS Code at C:\Users\antoo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
connectivity-0.4.8+1
connectivity_macos-0.1.0+1
path_provider-1.6.5
path_provider_macos-0.0.4
shared_preferences-0.5.6+2
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4

**Comment by jonahwilliams** [comment] 2020-03-19 23:20
Duplicate of https://github.com/flutter/flutter/issues/52803

I recommend using `dev` channel for web development

**Comment by fagottino** [comment] 2020-03-19 23:57
Hi @jonahwilliams, i read all the existing issues but no one of replies fit to me. Even if the problem is the same.
I tried also the solution in [https://github.com/flutter/devtools/issues/1497](url), I checked on my pc looking the folder in `~$Home\AppData\Roaming\Pub\Cache\global_packages\devtools` to delete it but i can't find it.

**Comment by jonahwilliams** [comment] 2020-03-20 03:50
This is a different issue

**Closed** 2020-03-20 05:20 UTC
Labels: tool, ☸ platform-web

**Comment by AttSee** [comment] 2020-03-20 10:33
I tried all the issues 1.15.17 to 1.16.1
Same problem.


ERROR - 2020-03-20 12:31:23.634307
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
createInjectedHandler.<fn>.<fn> (package:dwds/src/handlers/injected_handler.dart:35:39)



ERROR - 2020-03-20 12:24:48.050782
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
createInjectedHandler.<fn>.<fn> (package:dwds/src/handlers/injected_handler.dart:37:39)



 flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel dev, v1.16.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.16.1 at /home/attia/Porgram/flutter
    • Framework revision e6b0f5f238 (33 hours ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/attia/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/attia/Porgram/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/attia/Porgram/android-studio
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by jmagman** [comment] 2020-03-20 17:28
@AttSee The fix was merged a few hours ago and so far is only available on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

**Comment by NicTanghe** [comment] 2020-03-21 10:21
thx dude.

**Comment by penguin3d** [comment] 2020-03-27 05:17
So, what is the status?  Why are all related tickets closed when the issue obviously persists?
