### ISSUE TITLE
Android Embedding Migration docs page is giving page not found message.

### ISSUE THREAD

**Issue by srihariash999** [flutter/flutter#106087] opened 2022-06-16 06:01 UTC
I wanted to do some maintenance work on  an old flutter project and it had a warning that android v1 embedding is not functional anymore which my project was using.

```━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /Users/srihari/Downloads/local_hero-master/example/android/app/src/main/AndroidManifest.xml uses
  `android:name="io.flutter.app.FlutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Build failed due to use of deprecated Android v1 embedding.
```

I followed the link it gave me in the error to view the documentation on how to migrate. But the webpage is giving me a page not found type message. 

 [This](https://docs.flutter.dev/go/android-project-migration) is the link in question. I will attach a few screenshots just to be clear. 

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/101564310/174001408-253de79e-edad-4b33-8b00-90e187564263.png">

Why was this documentation removed ? And if it was removed for a reason, I think the warning/error message should be updated with the new link.

Also, if I google the migration documentation, it takes me to the same mentioned link and it gives 404 that way too. 

Please look into this. Thanks.

**Comment by danagbemava-nc** [comment] 2022-06-16 08:38
Duplicate of https://github.com/flutter/website/issues/7267

**Closed by danagbemava-nc** 2022-06-16 08:38 UTC
Labels: in triage
