### ISSUE TITLE
sdkmanager.bat and gradlew.bat are deleted by antivirus on windows

### ISSUE THREAD

**Issue by thesparkvision** [flutter/flutter#56628] opened 2020-05-08 03:26 UTC
I am trying to install flutter without using Android Studio. I am following [this article](https://medium.com/@quicky316/install-flutter-sdk-on-windows-without-android-studio-102fdf567ce4) for reference.  

1. I installed the flutter SDK from official site. 
2. Then I installed OpenJDK which was facing some issues. So using some advice from a facebook group, I installed from [this site](https://adoptopenjdk.net/).
3. I installed the android SDK from official site. That also faced issues. So using some stackoverflow answer, I downloaded a previous version of SDK .  
4. Everything worked fine till now. I set all the environment variables. I set the path. I run sdkmanager --list. It worked correctly
5. Then I ran ```sdkmanager “system-images;android-27;default;x86_64”``` . It gave me error that "repositories.cfg" not found. I resolved this error by creating this file in desired location
6. Then another error came that "unable to find package system-image" . I found no answer on Internet addressing it. I was trying to resolve this and opened the sdkmanager.bat file and it disappeared from my folder. Now I am again extracting the tools folder but everytime I run sdkmanager, the file disappears. What to do?

**Comment by Andy-Python-Programmer** [comment] 2020-05-08 03:42
Hi @thesparkvision try downloading the latest version of android studio not the android sdk tools.
I hope this helps :)

**Comment by thesparkvision** [comment] 2020-05-08 04:00
Hi sir, actually first I was trying to do setup using Android Studio only. But there also issues are coming.

I want that I be able to use Android Studio but I don't need an Android Virtual Device. Instead I want to directly test my app on Android smartphone. 

So I excluded the Virtual Device (1 GB) during installation. Then I went through next steps and downloaded the SDK files , installed the flutter ,dart extensions.
My project opened. 

Now when I ran , ```flutter doctor```, it caused me problem in Android toolchain. I searched over the Internet . They told me to download the Obsolete packages. I did that also. Still I faced issues in the Android Studio. So I tried the without Android Studio way. In that also, sdkmanager is causing issues.

**Comment by Andy-Python-Programmer** [comment] 2020-05-08 04:07
@thesparkvision try uninstalling all the things including android studio and flutter with sdk tools and then do a fresh install of everything.
1. Android Studio — Uncheck the virtual device option
2. Flutter — Download the flutter zip file and extract it in the c:/src/ folder 
3. Licence — run `flutter doctor` and find the command written after the sdk tools to agree the package license and agree all of them.
4. Run `flutter doctor` again and this time the external device should be connected.
If everything comes with a check mark in the front of it except vs code if you are not using it then it should work.

**Comment by Andy-Python-Programmer** [comment] 2020-05-08 04:13
Try creating and running the sample project of flutter and run it before modifying and of the code.
1. `flutter create sample_check`
2. `cd sample_check`
3. `flutter run`

After the apk is built the app will start automatically on your device.
You must enable developer options in your android device.

Do this step first !important

1. Tap your build number of your android device 7 times and then you will be a developer.
2. Go to advance developer options to enable USB debugging.

If everything is done step by step it should work.

**Comment by VladyslavBondarenko** [comment] 2020-05-08 09:14
Thank you @Andy-Python-Programmer !
@thesparkvision does it help?

**Comment by thesparkvision** [comment] 2020-05-08 09:31
I went through the steps. Everything worked smoothly. Faced no problem. When I ran flutter doctor , it did not give me errors it was giving ne in past.

But, I got no message for licenses. So I went over the internet to see the command to accept licenses. I ran ```flutter doctor --android-licenses ``` . But it gave me sdkmanager missing error.  Before running this command, sdkmanager was present. I went through the folder and checked, it was missing in real.

In without android studio installation also , I am facing the same problem.

**Comment by VladyslavBondarenko** [comment] 2020-05-08 13:16
@thesparkvision 
does it help https://github.com/flutter/flutter/issues/51712#issuecomment-600394582?

**Comment by jainsid2305** [comment] 2020-05-08 19:21
I m also facing the same problem as yours @thesparkvision.
Did u get any solution?

**Comment by thesparkvision** [comment] 2020-05-09 07:24
This was not working earlier but now it worked. I had Obsolete packages Installed.

 I uninstalled them. Then again installed them and  ran ```flutter doctor -v```. This time it worked and it showed to run the command to accept licenses.

Now when I ran ```flutter doctor --android-licenses```. It again did not work properly. It thrown me error that repositories.cfg not found and 5 packages licenses not accepted. I have seen this error before also. At that time, I had made a repositories.cfg file but it only increased the problem I think.

What is your take on this? I have attached the screenshot for clarity
![licenseerror](https://user-images.githubusercontent.com/40954160/81467129-2fe7f580-91f4-11ea-8e1c-65f8f5453aa6.png)

**Comment by thesparkvision** [comment] 2020-05-10 08:14
Update to the issue. I ran ```flutter doctor --android-licenses``` yesterday and was waiting for response on github for the issue of licenses not accepted.

Today, I again try to run ```flutter doctor -v``` to see what error it gives me. I gave the message that ```Android license status unknown```. So i ran ```flutter doctor --android-licenses``` to again try to accept licenses and now it is showing ```sdkmanager not found```. This is the same issue that happened with me before and because of it I am unable to move forward. 

I have attached the error message . I checked using the File explorer, sdkmanager.bat file is again missing whereas it was present yesterday

![sdk not found again](https://user-images.githubusercontent.com/40954160/81494177-507f8080-92c4-11ea-840f-ce4c3a9f5c8d.png)

**Comment by thesparkvision** [comment] 2020-05-10 08:17
@jainsid2305 I have not got solution to the problem yet. But I have found a tool https;//flutlab.io which I can use for learning and testing flutter apps and later build them until I get a solution to this issue to continue my learning journey.

**Comment by VladyslavBondarenko** [comment] 2020-05-11 09:59
@thesparkvision 
is `sdkmanager.bat` missing after you installed [Android SDK Tools via Android Studio](https://github.com/flutter/flutter/issues/51670#issuecomment-597253505)  right?

**Comment by jainsid2305** [comment] 2020-05-11 10:12
@thesparkvision i have also installed android studio on linux currently. And it is working fine.
But if u find any solution. Plz let me know.

**Comment by Andy-Python-Programmer** [comment] 2020-05-11 11:29
Hi @thesparkvision try this:
Probably all the contents of the sdk/tools folder are missing as well?

Best method to solve this issue is to go to the sdk/temp folder. There you will find a zip file with a name like "tools_r24.0.1-windows" (version number will be different)

Copy it to someplace and extract it. Inside the extracted folder you'll have a folder named 'tools'

Copy that folder to sdk/ and replace the current tools folder in sdk/

And voila! SDK and AVD will work again and all your virtual devices will be restored!

I hope this helps. Let me know.

**Comment by Andy-Python-Programmer** [comment] 2020-05-15 05:22
Did it work ?

**Comment by ElmouradiAmine** [comment] 2020-05-16 09:09
I have the same issue what the hell is happening? I believe antivirus or windows defender automatically deletes the SDK manager bat file. :(

**Comment by codelearner2020** [comment] 2020-05-18 22:56
@thesparkvision  Hey I am facing the same problem, the sdkmagar.bat file is getting deleted automatically and I've not been able to set up flutter. Do tell me if you find a solution to this!

**Comment by Andy-Python-Programmer** [comment] 2020-05-19 00:40
Hi @thesparkvision sdk manager installs all the required packages when it is running for the first time. It creates a `temp` folder in which it contains all the packages. Your os might not allow `sdkmanager.bat` to create files. It is happening because it is stored in `c:/` directory. It also happens if you try to paste a folder to `c:/` so, try running `sdkmanager.bat` as administrator.

**Comment by codelearner2020** [comment] 2020-05-19 22:26
@thesparkvision you said you're working with flutlab for now,is it working fine ? with me, it is showing some unexpected errors that shouldn't be there.

**Comment by codelearner2020** [comment] 2020-05-20 19:27
If anyone here is able to solve this problem then please do tell.

**Comment by thesparkvision** [comment] 2020-05-21 10:53
@Andy-Python-Programmer I @codelearner2020  I tried to do whatever possible. But it didn't work. I was using Windows 7 . So then I shifted my flutter installation to Windows 10 OS. One of my friends told me some steps to do the installation. I followed along and flutter got installed
I installed git and set its path to make it available everywhere ``C:\Program Files\Git\bin` in System variables

I made `C:/src` folder and then I extracted flutter sdk to this folder .  
Then I went to System variables and set in path this 2 lines:
 ```
C:\src\flutter\bin\cache\dart-sdk\bin
 C:\src\flutter\bin
```
 Then I had installed Java SE 8 JDK in the system and set its path in a different variable 
` JAVA_HOME` to `C:\Program Files\Java\jdk1.8.0_251` .

Then I finally installed Android Studio inside the `C:/src/Android/Android Studio folder. `
Then I set the path of `ANDROID_HOME` variable to this `C:\src\Android\Android Studio

Then I opened Android Studio, it installed the respective packages one by one. I installed the Android SDK at a separate location here `C:\Users\user\Android\Sdk` using Android Studio .  Then I installed the Flutter and Dart plugins through the next window. 

I ran  `flutter doctor`. Still some issues were coming. I went to SDKManager window and installed more files like build tools latest, Google Play services , updates .

Then I ran flutter doctor, it went okay. I have to separately run `flutter doctor --android-licenses` and all licenses got accepted. 

I got a green light. Some issues were coming in running the flutter apps but by srtackoverflow I came over them. So in my case, it didn't worked because of sdkmanager.bat file on Windows7 and I shifted everything to a different PC.

**Comment by thesparkvision** [comment] 2020-05-21 10:55
> 
> 
> @thesparkvision you said you're working with flutlab for now,is it working fine ? with me, it is showing some unexpected errors that shouldn't be there.

Hi @codelearner2020 , let me know your problem . I even generated apks on flutlab. It worked fine for me . Maybe I can help you out

**Comment by thesparkvision** [comment] 2020-05-21 10:57
> 
> 
> @thesparkvision
> is `sdkmanager.bat` missing after you installed [Android SDK Tools via Android Studio](https://github.com/flutter/flutter/issues/51670#issuecomment-597253505) right?

@VladyslavBondarenko  Yeah and sometimes it becomes missing on trying to accept android-licenses or just after running flutter doctor or opening the sdkmanager.bat file mistakenly

**Comment by codelearner2020** [comment] 2020-05-21 12:51
> > @thesparkvision you said you're working with flutlab for now,is it working fine ? with me, it is showing some unexpected errors that shouldn't be there.
> 
> Hi @codelearner2020 , let me know your problem . I even generated apks on flutlab. It worked fine for me . Maybe I can help you out

hey, actually it is showing a lot of errors when I tried to edit my pubsec.yaml file for using AssetImage. Do you know how I'll be able to solve this ?

**Comment by VladyslavBondarenko** [comment] 2020-05-21 13:22
@codelearner2020 could you provide your `flutter doctor -v`?
have you noticed when sdkmagar.bat is deleted, after what your actions?

**Comment by codelearner2020** [comment] 2020-05-21 19:27
> @codelearner2020 could you provide your `flutter doctor -v`?
> have you noticed when sdkmagar.bat is deleted, after what your actions?

flutter doctor shows only one issue, android licence status unknown.

**Comment by VladyslavBondarenko** [comment] 2020-05-22 06:50
@codelearner2020 
`flutter doctor -v` shows us your flutter version, operating system, connected devices. In some issues other info from the command may be useful as well.
does https://github.com/flutter/flutter/issues/51670#issuecomment-597253505 solve your android licenses issue and deleted sdkmanager.bat issue?

**Comment by mechnilesh** [comment] 2020-05-23 09:36
I am facing this same problem since 6 days. Can anyone help?

**Comment by Andy-Python-Programmer** [comment] 2020-05-23 09:40
Hi @mechnilesh did you try all the solutions mentioned above. Try the latest solution it works.

**Comment by mechnilesh** [comment] 2020-05-23 09:48
> Hi @mechnilesh try all the solutions mentioned above. Try the latest solution it works.

Hlo

> Hi @mechnilesh try all the solutions mentioned above. Try the latest solution it works.

Hlo, yes i have tried everything except changing my pc ..it is still not working...i did  every thing

**Comment by thesparkvision** [comment] 2020-05-23 10:22
> 
> 
> > > @thesparkvision you said you're working with flutlab for now,is it working fine ? with me, it is showing some unexpected errors that shouldn't be there.
> > 
> > 
> > Hi @codelearner2020 , let me know your problem . I even generated apks on flutlab. It worked fine for me . Maybe I can help you out
> 
> hey, actually it is showing a lot of errors when I tried to edit my pubsec.yaml file for using AssetImage. Do you know how I'll be able to solve this ?

I think you are following London App Brewery course? You can mention your code github link. I will look into it . I have done the AssetImage part on flutlab. Try to erase the comments. The comments hinder you from seeing the main code. There are a lot of comments in the .yaml file and check the indentation once.

**Comment by mechnilesh** [comment] 2020-05-23 10:27
> Hi @mechnilesh try all the solutions mentioned above. Try the latest solution it works.

hlo @Andy-Python-Programmer i have tried everything except changing my pc

**Comment by mechnilesh** [comment] 2020-05-23 12:37
I got the solution in my case an Antivirus was deleting the sdkmanager file from bin folder,I unistalled the antivirus and recovered the sdkmanger file and updated the sdkmanager then accepted all licensess and then hip hip hurreyy.
Try this solution guys.

**Comment by dinhan1192** [comment] 2020-05-24 05:35
So, I ve figured out how to keep sdkmanager from getting deleted.
sdkmanager file is actuall .bat file and it can get deleted abnormally. So, in my case, I just get the sdkmanager.bat file into the whitelist of anti virus program.
After that, I give permission to sdkmanager by going into it's properties and choose Security. At this time, if you do not know which one you should give permission, thus give them all Full Control.
Finally, I run sdkmanager.bat file by Run as Administration. Meanwhile, I also run the flutter doctor -v and flutter doctor --android-licenses. And well, I was able to accept all the licenses !!!

Well, that's it !!!!
For those, who do not want to reinstall Android Studio to get the sdkmanager.bat file, you can go into \Android\Sdk\.temp\ folder to get the commandlinetools zip files. Extract it to get the tools folder, replace the tools folder with the tools folder in Android\Sdk. Now, you get the sdkmanager, do as I wrote and I hope you can accept the licenses !
 
 but now, another problem come in, it is that, the gradlew.bat somehow vanished weirdly !!!!

**Comment by dinhan1192** [comment] 2020-05-24 06:04
Well, it seems it all turns out to be the cause of anti virus program.
Though the gradlew.bat file is put in to White List, it is still considered a SUSPICIOUS file ! So, you need to turn off your anti virus program COMPLETELY !!!!
Now, my flutter run great !!!

**Comment by VladyslavBondarenko** [comment] 2020-05-25 07:50
Thank you for the input, I'm glad that it's solved, closing. 
If you disagree, please write in the comments and I will reopen it.

**Closed by VladyslavBondarenko** 2020-05-25 07:50 UTC
Labels: platform-android, platform-windows, tool

**Comment by adrobnych** [comment] 2020-06-06 12:42
> > > @thesparkvision you said you're working with flutlab for now,is it working fine ? with me, it is showing some unexpected errors that shouldn't be there.
> > 
> > 
> > Hi @codelearner2020 , let me know your problem . I even generated apks on flutlab. It worked fine for me . Maybe I can help you out
> 
> hey, actually it is showing a lot of errors when I tried to edit my pubsec.yaml file for using AssetImage. Do you know how I'll be able to solve this ?

Please try again, flutlab's syntax-checking logic was updated recently and should not block pubspec editing.

**Comment by jasjyot-kaur** [comment] 2020-06-20 13:01
Hii@VladyslavBondarenko
I have still not resolved this issue,sdkmanager.bat is getting delete again and again,can you please help me out??
Also there is no antivirus but still its getting deleted.

**Comment by ElmouradiAmine** [comment] 2020-06-20 19:59
Try to disable your anti-virus and windows defender

Le sam. 20 jui. 2020 à 14:02, jasjyot-kaur <notifications@github.com> a
écrit :

**Comment by jasjyot-kaur** [comment] 2020-06-20 20:16
@ElmouradiAmine Thanks for replying.
I don't have any anti virus and I have already disabled the windows defender and firewall,but there are no changes, it's getting delete again and again, also I have try running it as a administrator

**Comment by ElmouradiAmine** [comment] 2020-06-20 20:18
Try to use a previous version of Android studio

Le sam. 20 jui. 2020 à 21:16, jasjyot-kaur <notifications@github.com> a
écrit :

**Comment by jasjyot-kaur** [comment] 2020-06-20 20:30
There was same issue with 3.6 too.. Right now I am using android 4.0

**Comment by jasjyot-kaur** [comment] 2020-06-20 20:32
Also, I don't have any issues in running android application... This issue is coming only while running flutter application

**Comment by ElmouradiAmine** [comment] 2020-06-20 20:37
Yeh I understand. The problem is when you try to accept the licenses on
flutter to make it work righg

Le sam. 20 jui. 2020 à 21:32, jasjyot-kaur <notifications@github.com> a
écrit :

**Comment by jasjyot-kaur** [comment] 2020-06-20 20:42
Before it was working fine, I have accepted all the licenses too, but then this error came, but now how to resolve this error??
Am stuck due to this and not able to work

**Comment by VladyslavBondarenko** [comment] 2020-06-22 07:35
@jasjyot-kaur 
please file a separate issue for this with filling out template

**Comment by TonyAjay18** [comment] 2020-07-24 05:35
> So, I ve figured out how to keep sdkmanager from getting deleted.
> sdkmanager file is actuall .bat file and it can get deleted abnormally. So, in my case, I just get the sdkmanager.bat file into the whitelist of anti virus program.
> After that, I give permission to sdkmanager by going into it's properties and choose Security. At this time, if you do not know which one you should give permission, thus give them all Full Control.
> Finally, I run sdkmanager.bat file by Run as Administration. Meanwhile, I also run the flutter doctor -v and flutter doctor --android-licenses. And well, I was able to accept all the licenses !!!
> 
> Well, that's it !!!!
> For those, who do not want to reinstall Android Studio to get the sdkmanager.bat file, you can go into \Android\Sdk.temp\ folder to get the commandlinetools zip files. Extract it to get the tools folder, replace the tools folder with the tools folder in Android\Sdk. Now, you get the sdkmanager, do as I wrote and I hope you can accept the licenses !
> 
> but now, another problem come in, it is that, the gradlew.bat somehow vanished weirdly !!!!

Hii I even uninstalled my anti virus and even the sdkmanager.bat file is getting deleted everytime.So i cant able to accept my android licenses and run my flutter:((.Kindly help me to sort out this issue.

**Comment by gauravcsecu** [comment] 2020-07-27 13:15
I was thinking because of some system Antivirus working there, usually batch file contains some unwanted code may be harmful to a system that's why well still I can't find any solution and when I copy-paste batch file from another project it deleted before my eyes like magic

**Comment by akanksha4715** [comment] 2020-07-30 19:13
I have tried every solution listed here still facing the same problem, sdkmanager just vanishes. I don't think that antivirus is deleting it because this time i tried installing while my antivirus software was turned off.

**Comment by thesparkvision** [comment] 2020-07-30 19:33
@akanksha4715 There is a possibility that there maybe some hidden antivirus in your system which got installed due to some software installation. Recently I was contacted by two persons. They told that they found some hidden antivirus software which was deleting the file. Please check once if this is also happening in your case.

**Comment by akanksha4715** [comment] 2020-08-03 12:18
@thesparkvision I guess you were right. I found those hidden antiviruses. Deleted them. Downloaded everything again and boom it works! Thank you.

**Comment by syedhadi18** [comment] 2020-08-25 20:16
> @thesparkvision I guess you were right. I found those hidden antiviruses. Deleted them. Downloaded everything again and boom it works! Thank you.

can you please tell me? how did you find out those hidden antiviruses?

**Comment by Ujjawalmaurya** [comment] 2020-10-12 19:56
> Update to the issue. I ran `flutter doctor --android-licenses` yesterday and was waiting for response on github for the issue of licenses not accepted.
> 
> Today, I again try to run `flutter doctor -v` to see what error it gives me. I gave the message that `Android license status unknown`. So i ran `flutter doctor --android-licenses` to again try to accept licenses and now it is showing `sdkmanager not found`. This is the same issue that happened with me before and because of it I am unable to move forward.
> 
> I have attached the error message . I checked using the File explorer, sdkmanager.bat file is again missing whereas it was present yesterday
> 
> ![sdk not found again](https://user-images.githubusercontent.com/40954160/81494177-507f8080-92c4-11ea-840f-ce4c3a9f5c8d.png)

Same here. In my case, SDK manager.bat file gets deleted again and again. I disabled my antivirus and Windows Defender. But problem still same.
What to do

**Comment by Andy-Python-Programmer** [comment] 2020-10-21 03:06
Try reinstalling flutter?

**Comment by vitorcortinovis** [comment] 2021-04-30 11:32
I had the same problem with the files `gradlew.bat` and `sdkmanager.bat` ... Following the tips of this and other Github topics, I found that I had antivirus installed that were removing these files.

After uninstalling, on Android Studio I reinstalled the SDK and my projects worked normally on Flutter!
