### ISSUE TITLE
Flutter web Google Sign in gives id_token null 

### ISSUE THREAD

**Issue by s4rath07** [flutter/flutter#154335] opened 2024-08-29 12:47 UTC
### Steps to reproduce

1.

    final GoogleSignIn _googleSignIn = GoogleSignIn(
   
    forceCodeForRefreshToken: true,
    scopes: [
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/bigquery',
      'https://www.googleapis.com/auth/userinfo.email',
      'https://www.googleapis.com/auth/userinfo.profile',
    ],
      );

2. After that use the googlesign in 

`

     Future<void> _handleSignIn() async {
        try {
           GoogleSignInAccount? account = await _googleSignIn.signIn();
           log("$account");
          if (account != null) {
            GoogleSignInAuthentication auth = await account.authentication;
            log("Id token : ${auth.idToken}");
            log("Access token: ${auth.accessToken}");
            String? serverAuthCode = account.serverAuthCode;
            log("Server Auth Code: $serverAuthCode");
            if (serverAuthCode != null) {
              final tokenResponse = await _exchangeCodeForTokens(serverAuthCode);
          if (tokenResponse != null) {
            final accessToken = tokenResponse['access_token'];
            final idToken = tokenResponse['id_token'];
            final refreshToken = tokenResponse['refresh_token'];
            log("Access Token: $accessToken");
            log("ID Token: $idToken");
            log("Refresh Token: $refreshToken");
            _sendTokensToBackend(idToken, accessToken, refreshToken);
              } else {
               log("Failed to obtain tokens.");
             }
            }
          }
         } catch (error) {
           print(error);
         }
       }

`

3. added the meta tag inside the index.html 

`<meta name="google-signin-client_id" content="4323432432.apps.googleusercontent.com">`

### Expected results

There is no id_token and serverauthcode but only access token is there.

### Actual results

It should have given the access token, id token and server auth code

### Code sample

1.

    final GoogleSignIn _googleSignIn = GoogleSignIn(
   
    forceCodeForRefreshToken: true,
    scopes: [
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/bigquery',
      'https://www.googleapis.com/auth/userinfo.email',
      'https://www.googleapis.com/auth/userinfo.profile',
    ],
      );

2. After that use the googlesign in 

`

     Future<void> _handleSignIn() async {
        try {
           GoogleSignInAccount? account = await _googleSignIn.signIn();
           log("$account");
          if (account != null) {
            GoogleSignInAuthentication auth = await account.authentication;
            log("Id token : ${auth.idToken}");
            log("Access token: ${auth.accessToken}");
            String? serverAuthCode = account.serverAuthCode;
            log("Server Auth Code: $serverAuthCode");
            if (serverAuthCode != null) {
              final tokenResponse = await _exchangeCodeForTokens(serverAuthCode);
          if (tokenResponse != null) {
            final accessToken = tokenResponse['access_token'];
            final idToken = tokenResponse['id_token'];
            final refreshToken = tokenResponse['refresh_token'];
            log("Access Token: $accessToken");
            log("ID Token: $idToken");
            log("Refresh Token: $refreshToken");
            _sendTokensToBackend(idToken, accessToken, refreshToken);
              } else {
               log("Failed to obtain tokens.");
             }
            }
          }
         } catch (error) {
           print(error);
         }
       }

`

3. added the meta tag inside the index.html 

`<meta name="google-signin-client_id" content="4323432432.apps.googleusercontent.com">`

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4037], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by s4rath07** [comment] 2024-08-29 12:49
I am using google_sign_in: ^6.2.1

**Comment by danagbemava-nc** [comment] 2024-08-29 13:38
Closing this as a duplicate of https://github.com/flutter/flutter/issues/20903#issuecomment-1735878336

**Closed by danagbemava-nc** 2024-08-29 13:38 UTC
Labels: in triage

**Comment by s4rath07** [comment] 2024-08-30 09:38
my issue was on flutter web not on android
