### ISSUE TITLE
Rendering issue on windows while running widget test

### ISSUE THREAD

**Issue by spmsana004** [flutter/flutter#108726] opened 2022-08-01 09:49 UTC
Problem occurs only in widget test on windows. While running the application in windows debug/release mode render issue is not observed.

**Widget creation file.**
```
import 'package:flutter/material.dart';

class RenderingIssue extends StatelessWidget {
  const RenderingIssue();

  @override
  Widget build(BuildContext context) {
    return _buildBody(context);
  }

  Widget _buildBody(BuildContext context) {
    return Container(
      width: 215,
      child: _buildButton(context),
    );
  }

  Widget _buildButton(BuildContext context) {
    return SizedBox(
        height: 32.0,
        child:  TextButton(
              style: TextButton.styleFrom(
                shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.zero),
                backgroundColor: const Color.fromRGBO(0, 104, 180, 1.0),
                onSurface: const Color.fromRGBO(110, 180, 68, 1.0),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: const <Widget>[
                  Text('Start the test to'),
                ],
              ),
              onPressed: null,
            ));
  }
}
```

**Widget test file. File name - testFile.dart**
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../../test_utils/widget_test_util.dart';
import 'RenderingIssue.dart';

void main() {
  setUp(() {
    WidgetTestUtil.registerCommonDependencies();
  });

  testWidgets('verify SectionTabColumnWidget with MultiPumpWidget',
      (WidgetTester tester) async {
    await tester.pumpWidget(
        WidgetTestUtil.buildTestableWidget(Scaffold(body: const RenderingIssue())));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 100));
    expect(find.byType(RenderingIssue), findsOneWidget);
  });
}
````
### UI created and looks like.
![image](https://user-images.githubusercontent.com/110387296/182126776-29dfdcc9-3cc4-494b-a577-8f4a345fcfde.png)

### Widget test Result - Issue occurred when run from android studio using Run testFile.dart 
![image](https://user-images.githubusercontent.com/110387296/182120053-b1c212e7-ab6e-4570-852d-f455e5c8b984.png)

### flutter run --flavor dev -t Result - Run as expected without issue
![image](https://user-images.githubusercontent.com/110387296/182120327-2e63f76a-4358-46f2-9b7a-d71fc6998227.png)

**Similar issue reported early - https://github.com/flutter/flutter/issues/92888**

**Comment by maheshmnj** [comment] 2022-08-02 07:13
@spmsana004 thanks for filing the issue, Your code sampel is incomplete , Please share `WidgetTestUtil` class to investigate furrther. Additionally try wrapping your widget in a MediaQuery and define the size constraint.

**Comment by spmsana004** [comment] 2022-08-02 07:46
> @spmsana004 thanks for filing the issue, Your code sampel is incomplete , Please share `WidgetTestUtil` class to investigate furrther. Additionally try wrapping your widget in a MediaQuery and define the size constraint.

Now updated test file. use this.

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'abc.dart'; //source file

void main() {
  testWidgets('verify SectionTabColumnWidget with MultiPumpWidget',
      (WidgetTester tester) async {
    await tester.pumpWidget(buildTestableWidget(
        const Scaffold(body: RenderingIssue())));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 100));
    expect(find.byType(RenderingIssue), findsOneWidget);
  });
}

Widget buildTestableWidget(Widget widget) {
  return MediaQuery(
      data: const MediaQueryData(),
      child: MaterialApp(
          home: widget));
}

```

**Comment by maheshmnj** [comment] 2022-08-03 05:58
@spmsana004 The issue with your test is you are wrapping `RenderingIssue` in a `scaffold`, Removing that should resolve the issue.

The corrected test should look as below
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sample/main.dart';

void main() {
  testWidgets('verify SectionTabColumnWidget with MultiPumpWidget',
      (WidgetTester tester) async {
    await tester.pumpWidget(buildTestableWidget(RenderingIssue()));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 100));
    expect(find.byType(RenderingIssue), findsOneWidget);
  });
}

Widget buildTestableWidget(Widget widget) {
  return MediaQuery(
      data: const MediaQueryData(), child: MaterialApp(home: widget));
}

```

Closing as this is not a bug in flutter.

**Closed** 2022-08-03 05:58 UTC
Labels: in triage

**Comment by spmsana004** [comment] 2022-08-03 07:28
### source file :

```
import 'package:flutter/material.dart';

class RenderingIssue extends StatelessWidget {
  const RenderingIssue();

  @override
  Widget build(BuildContext context) {
    return _buildBody(context);
  }

  Widget _buildBody(BuildContext context) {
    return Container(
        child: Column(children: [
      Container(
        width: 215,
        child: _buildButton(context),
      )
    ]));
  }

  Widget _buildButton(BuildContext context) {
    return SizedBox(
        height: 32.0,
        child: TextButton(
            style: TextButton.styleFrom(
              shape:
                  const RoundedRectangleBorder(borderRadius: BorderRadius.zero),
              backgroundColor: const Color.fromRGBO(0, 104, 180, 1.0),
              onSurface: const Color.fromRGBO(110, 180, 68, 1.0),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: const <Widget>[
                Text('Start the test to'),
              ],
            ),
            onPressed: null));
  }
}

```

### test file :

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:go2/ui/desktop/widget/monitor/abc.dart';

void main() {
  testWidgets('verify SectionTabColumnWidget with MultiPumpWidget',
      (WidgetTester tester) async {
    await tester.pumpWidget(buildTestableWidget(
        const RenderingIssue()));
    await tester.pumpAndSettle();
    await tester.pump(const Duration(seconds: 100));
    expect(find.byType(RenderingIssue), findsOneWidget);
  });
}

Widget buildTestableWidget(Widget widget) {
  return MediaQuery(
      data: const MediaQueryData(),
      child: MaterialApp(
          home: widget));
}

```
Now it is reproducing...!!

**Comment by spmsana004** [comment] 2022-08-04 04:35
Any update on this ?

**Comment by maheshmnj** [comment] 2022-08-04 10:01
@spmsana004 This is working as intended, The overflow in your first scenario is mainly due to the Text widget  in a Row.
Flutter test uses Ahem fault which are wider than normal font  see: https://github.com/flutter/flutter/issues/33404#issuecomment-519252794. 

So the test failure is normal However you can either scaleDown the fontSize or use your custom font as defined in the linked comment.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sample/main.dart';

void main() {
  final TestWidgetsFlutterBinding binding =
      TestWidgetsFlutterBinding.ensureInitialized();
  testWidgets('verify SectionTabColumnWidget with MultiPumpWidget',
      (WidgetTester tester) async {
    await tester.binding.setSurfaceSize(Size(800, 400));
    tester.binding.window.platformDispatcher.textScaleFactorTestValue = 0.8;
    await tester.pumpWidget(buildTestableWidget(const RenderingIssue()));
    await tester.pumpAndSettle();
    expect(find.byType(RenderingIssue), findsOneWidget);
    await tester.binding.setSurfaceSize(null);
  });
}

Widget buildTestableWidget(Widget child, {Size size = const Size(600, 800)}) {
  return MaterialApp(
    home: child,
  );
}

```

**Comment by spmsana004** [comment] 2022-08-04 13:55
> ```dart
>  await tester.binding.setSurfaceSize(null);
> ```

Still scenario-2 is not covered. Any update on this ?

**Comment by pgn001** [comment] 2022-08-07 18:33
Hi @maheshmnj 
Few months back all passed widget tests are started failing now. UI looks fine. Only widget tests are giving render issue.
As you said in above comment, below line helps
tester.binding.window.platformDispatcher.textScaleFactorTestValue = 0.2;

But this shrinks the text. Then onTap is not happening on above the shrinked text.

In recent update, is flutter test font updated? Few months back I didn't face any issue. 
And how to handle onTap for the textScaleFactor changed case?

**Comment by maheshmnj** [comment] 2022-08-08 09:44
@spmsana004 The test I mentioned above should work for your second scenario too. Your second code sample is using DropdownWidget which is a material widget and must me wrapped with a Material Component. Heres the code sample for scenario 2 with Material Widget wrapped around and the [above test](https://github.com/flutter/flutter/issues/108726#issuecomment-1205035859) passes successfully.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

class RenderingIssue extends StatelessWidget {
  const RenderingIssue();

  @override
  Widget build(BuildContext context) {
    return _buildBody(context);
  }

  Widget _buildBody(BuildContext context) {
    return Material(
      child: Container(
          child: Column(children: [
        Container(
          width: 215,
          child: _buildButton(context),
        ),
        Container(
            width: 215,
            child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
              items: [],
              onChanged: (value) {},
            )))
      ])),
    );
  }

  Widget _buildButton(BuildContext context) {
    return SizedBox(
        height: 32.0,
        child: TextButton(
            style: TextButton.styleFrom(
              shape:
                  const RoundedRectangleBorder(borderRadius: BorderRadius.zero),
              backgroundColor: const Color.fromRGBO(0, 104, 180, 1.0),
              onSurface: const Color.fromRGBO(110, 180, 68, 1.0),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: const <Widget>[
                Text('Start the test to'),
              ],
            ),
            onPressed: null));
  }
}

```
</details> 

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter test
Running "flutter pub get" in sample...                           2,456ms
00:07 +1: All tests passed!                                                                                     
mahesh@Maheshs-MacBook-Air-M1 sample % 
```

**Comment by maheshmnj** [comment] 2022-08-08 09:45
@pgn001 for your case we would need a minimal and complete code sample to investigate further. I would suggest filinga new issue so that we could take a look at it separately.
