### ISSUE TITLE
Compiling flutter/engine on Windows

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#28720] opened 2019-03-01 11:52 UTC
Do we support [compiling the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine) on Windows?

Looks like the build script has some issues with paths on Windows:

```
C:\src\flt\engine\src>python flutter\tools\gn --unoptimized
gn gen --check in out\host_debug_unopt
Traceback (most recent call last):
  File "C:/src/flt/engine/src/flutter/build/git_revision.py", line 42, in <module>
    sys.exit(main())
  File "C:/src/flt/engine/src/flutter/build/git_revision.py", line 34, in main
    'HEAD',
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
ERROR at //flutter/common/version/version.gni:15:7: Script returned non-zero exit code.
      exec_script("$flutter_root/build/git_revision.py",
      ^----------
Current dir: C:/src/flt/engine/src/out/host_debug_unopt/
Command: C:/src/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe -- C:/src/flt/engine/src/flutter/build/git_revision.py --repository C:/src/flt/engine/src/flutter
Returned 1.
See //flutter/common/version/BUILD.gn:5:1: whence it was imported.
import("version.gni")
^-------------------
See //flutter/shell/common/BUILD.gn:108:5: which caused the file to be included.
    "$flutter_root/common/version",
    ^-----------------------------
```

```
C:\src\flt\engine\src>C:/src/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe -- C:/src/flt/engine/src/flutter/build/git_revision.py --repository C:/src/flt/engine/src/flutter
Traceback (most recent call last):
  File "C:/src/flt/engine/src/flutter/build/git_revision.py", line 42, in <module>
    sys.exit(main())
  File "C:/src/flt/engine/src/flutter/build/git_revision.py", line 34, in main
    'HEAD',
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\src\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

```
C:\src\flt\engine\src>dir C:/src/flt/engine/src/flutter/build/
Parameter format not correct - "src".
```

But this would work:

```
C:\src\flt\engine\src>dir C:\src\flt\engine\src\flutter\build\
```

Apparently we do not have build integration for Windows yet: https://github.com/flutter/flutter/issues/138.

**Comment by Qiyu8** [comment] 2019-09-29 06:50
Six month passed, No one want to fix this issue? I have the same issue here.

**Comment by thavlik** [comment] 2020-04-24 00:51
Just encountered this issue.

**Comment by Flashee** [comment] 2020-05-10 01:29
I've got the issue as well.

**Comment by Akora-IngDKB** [comment] 2020-05-10 16:32
Got same issue after updating to 1.17.0 beta

**Comment by Basher7** [comment] 2020-05-10 17:30
Got same issue after updating to 1.17.0 stable

**Comment by Syaidrian** [comment] 2020-05-10 20:49
got same issue, can anyone help?

**Comment by rezaei99m** [comment] 2020-05-14 12:34
me too got the same issue after upgrading to flutter v1.17.1 stable channel.

**Comment by satyamraj123** [comment] 2020-05-15 05:30
me too, someone help, i think this is causing bugs in my app

**Comment by godwinaden** [comment] 2020-05-15 07:49
I am having same issue after upgrading to v1.17.1 stable channel

**Comment by SandeepRana1001** [comment] 2020-05-15 22:45
Having the Same Issue After Upgrading Flutter to 1.17.1. 
Anyone if they know the solution kindly help

**Comment by ariefwijaya** [comment] 2020-05-16 18:35
Same here, having same issue after upgrading to v1.17.1 stable channel

**Comment by godwinaden** [comment] 2020-05-30 13:26
An fix to this yet, my project relays on flutter 1.17.1, if i downgrade it, lots of things will change and i need google map on my app

**Comment by deakjahn** [comment] 2020-07-03 09:50
@dcharkes The doc clearly says so: https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web-on-windows
But still, after more than a year, not a iota has changed here.

**Comment by deakjahn** [comment] 2020-07-04 11:10
Now that Windows has a complete Linux subsytem and installing a Linux is literally just a few mouse clicks away, probably there is no longer a need to struggle with this. I moved on to a Linux. Here is the list of what I experienced:

* Ubuntu 18.04, don't go any further. Although the [doc](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) mentions that some scripts are version-dependent, it fails to specify which, so you only know if you do the full process and learn at the ver end that you need to start all over again.

* When you install `depot_tools`, make sure you run `gclient` without arguments, just like the description mentions for Windows. It forgets to mention for Linux but it **is** required.

**Comment by thavlik** [comment] 2020-07-18 14:57
So right now, the solution to building on Windows is to use Linux instead? 😅 Honestly that sounds like a great idea, but there are situations where native Windows is the only choice.

**Comment by deakjahn** [comment] 2020-07-18 18:54
@thavlik Somebody told me he had success: https://github.com/flutter/flutter/issues/61440 I tried again and failed.

**Comment by stuartmorgan** [comment] 2020-07-19 01:50
> So right now, the solution to building on Windows is to use Linux instead?

There are CI bots that build the engine on Windows for every PR and every commit. A number of Flutter engine developers build regularly on Windows.

The issue here is not "it's impossible to build the engine on Windows", it's "there is some (currently unknown) configuration that causes issues for some people when building on Windows".

**Comment by deakjahn** [comment] 2020-07-19 11:46
@stuartmorgan And in our quest to determine those configuration issues, can we start from the actual error message we all seem to get? :-) I'll write up my Windows process, just like the Linux under Windows above, starting for the umpteenth time.

**Comment by deakjahn** [comment] 2020-07-19 11:48
This time for the original Windows setup. It's mostly the same as the one described by the Flutter team, obviously, but we might find the difference in the end.

Here is the list of what I experienced as I moved on:

## Visual Studio

* Download and install. It’s enough to install C++ development. Uncheck the Windows SDK.
* Download the SDK separately, and uncheck everything but _Debugging Tools for Windows_.

If you use VS for other development, it’s not a problem if the SDK or other parts are also installed. They’re not _required_ for compiling the engine, that’s all.

## Depot_tools

* (Download)[https://storage.googleapis.com/chrome-infra/depot_tools.zip] and extract
* add the extracted folder to front of PATH
* `gclient -v` (this is missing from the docs, important! -v is just for verbose so that you can see if it gets stuck). The running ends with the help screen showing commands and options.
* `where python` and verify that `python.bat` precedes `python.exe`

## Git
* `git bash`
And in the new Git console:
* `git config --global user.name "YOUR GITHUB NAME"`
* `git config --global user.email "YOUR GITHUB EMAIL"`
* `git config --global core.autocrlf false`
* `git config --global core.filemode false`
* `git config --global color.ui true`
* `exit`
These will be stored in `c:\Users\name\.gitconfig`.

## GitHub

Fork https://github.com/flutter/engine. Set up your key:

* `git bash`
And in the new Git console:
* `ssh-keygen -t rsa -b 4096 -C "YOUR GITHUB EMAIL"` (just reply Enter to the first question to use the default filename)
* `eval $(ssh-agent -s)`
* `ssh-add ~/.ssh/id_rsa` (yes, using Linux path)
* Add the contents of `c:\Users\name\.ssh\id_rsa.pub`  to your _GitHub account > Settings > SSH and GPG keys._
* `ssh -T git@github.com`, accept the fingerprint if it matches the one in the docs: https://docs.github.com/en/github/authenticating-to-github/testing-your-ssh-connection
* `exit`

## Download the source

* `mkdir engine`
* `cd engine`
* You can create the `.gclient` file in the [docs](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment), from Windows using your favorite text editor
* `gclient sync -j1 -v` (it takes quite some time but at least the verbose switches will show you what it does; there will be a longish step after the last downloaded package (wuffs), so wait for the end patiently)
* If git complains about access rights, either you start to troubleshoot the issue or you can simply revert to https access (instead of key-based) in `.gclient`:
```
"url": "https://github.com/<your_name_here>/engine.git",
```
For a one off download, it’s tempting to go the easy way but if you want to build regularly, it pays off to troubleshoot the issue.

**Comment by deakjahn** [comment] 2020-07-19 12:39
@thavlik Thomas, this is my current write-up and the error I get. Does it resemble your problem?

**Comment by deakjahn** [comment] 2020-07-19 12:59
If I assemble the command that`git_revision.py` tries to call:

    git -C <repo-path> rev-parse HEAD

it runs all right and returns the long code.

**Comment by deakjahn** [comment] 2020-07-23 11:08
@stuartmorgan This looks like a major scripting error on Windows. If I add `Shell=True` to the `subprocess.check_output()` in `git_revision.py`, that particular error goes away. And it stops at the next one. It looks like calling external executables is done in a way that's not cross-patform safe in any way.

**Comment by stuartmorgan** [comment] 2020-07-23 15:59
@deakjahn I'm not sure why you pinged me in that comment.

> This looks like a major scripting error on Windows. [...] It looks like calling external executables is done in a way that's not cross-patform safe in any way.

If you've identified the problem, then by all means please provide a description or a PR.

> If I add `Shell=True` to the `subprocess.check_output()` in `git_revision.py`, that particular error goes away.

Running commands through the shell is bad practice unless there's a very, very specific need to do it, and makes cross-platform, or even just cross-machine, issues dramatically more likely. There is nothing in that command that should require being run through the shell. Whatever the underlying issue you are encountering is, adding `shell=True` is a workaround, not a viable solution.

**Comment by deakjahn** [comment] 2020-07-23 16:15
It was just an idea. You mentioned a few days ago that there were situations where it worked, all the other contributors seemed to be of the idea that it doesn't. :-)

This is one single, small call from a very large, very interspersed, very complex toolchain. I don't know if you're inside Google and whether you routinely use this chain to build or not. I'm not, I would just need to use it to compile the engine to test other PRs I might possibly want to contribute. I think I can safely assume that Flutter people who are familiar with the toolchain has a much better chance to find out what's wrong with it, although the fact that this issue is more than a year old isn't very promising. :-)

I don't have the solution, unfortunately, that single test with `Shell` was just an attempt. As I can see, all problems stem from Python calling external executables. They don't return or don't return their stdout properly. I had some hope that mentioning the general direction might trigger some ideas from some of the contributors that could lead towards a solution, that's all.

**Comment by stuartmorgan** [comment] 2020-07-23 16:36
>  that there were situations where it worked, all the other contributors seemed to be of the idea that it doesn't.

You can't extrapolate from "people who have found and commented in a bug about a specific build failure" to "all other contributors". The former is, by its nature, not at all a representative sample.

It sounds like you believe that it works in rare cases and for everyone else it fails; the opposite is true. Not only do plenty of people successfully build Windows regularly, but we have repeatedly—using several completely different CI systems based on different images—set up working Windows automated builds without any special steps, and without hitting the error described in this issue.

> I think I can safely assume that Flutter people who are familiar with the toolchain have a much better chance to find out what's wrong with it

If there were people on the Flutter team hitting this issue, that would likely be true. But it is very hard to debug a problem without being able to reproduce it.

**Comment by deakjahn** [comment] 2020-07-23 16:55
> It sounds like you believe that it works in rare cases and for everyone else it fails;

I most certainly was before you chimed in because from the OP to the many comments saying me, too, me, too, there was no other opinion present. You were the first one to tell otherwise. :-)

**Comment by stuartmorgan** [comment] 2020-07-23 17:10
> to the many comments saying me, too, me, too

FWIW, the stream of me-too comments in May do not actually appear to be about this issue; many refer to updating to a specific version of Flutter, which makes no sense in the context of an issue about compiling the engine from source.

**Comment by deakjahn** [comment] 2020-07-23 17:18
Then I was misled.

Anyway, I try to find out the cause, I can see that Python actually calls the external commands and those commands execute all right, only that the calling script doesn't get the exit status and the output correctly. And even if shell isn't good to use normally, it does help in this particular case, so I need to find out what makes the non-shell case fail here.

**Comment by deakjahn** [comment] 2020-07-24 16:21
Actual compilation errors:

```
output: Unhandled exception:
Could not generate version
#0      getVersion.<anonymous closure> (file:///d:/Android/engine/src/third_party/dart/utils/compiler/create_snapshot_entry.dart:19:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#6      Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
#7      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by deakjahn** [comment] 2020-07-24 21:58
@thavlik Thomas, if you're still interested in it. I finally managed to compile on Windows and modified my description to include the necessary steps.

**Comment by kf6gpe** [comment] 2020-12-09 22:46
Currently documented at https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows. @cbracken I think you or @stuartmorgan have done this recently. When you have time, could you please update the wiki?

**Comment by Sunbreak** [comment] 2020-12-10 09:47
> Currently documented at https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows.

Possible related https://github.com/flutter/flutter/issues/61440

**Comment by stuartmorgan** [comment] 2020-12-10 12:04
@kf6gpe See my comments above; the issue isn't that the wiki is out of date, it's that there is some people seem to have path issues that most people (including our CI) don't have, and so far we don't know why.

If at some point we figure out what the configuration issue for people hitting this is, then we can document it (or adjust scripts). But currently we don't know what it is, so I have no idea what I would update the wiki with.

**Comment by eggfly** [comment] 2021-07-29 06:42
This maybe caused by we didn't  install the git for windows. Install a standalone git in
https://www.git-scm.com/download/win and add this git into PATH environment
```cmd
C:\Users\name>where git
C:\Program Files\Git\cmd\git.exe
C:\Users\name\depot_tools\git.bat
```

**Comment by cbracken** [comment] 2022-04-26 18:08
Closing this issue. Rationale:
* There haven't been any additional comments/updates in ~8 months.
* The comments appear to have described a collection of potentially unrelated issues, including documentation issues, rather than any one specific issue, and several of them are likely to have been fixed or are out of date at this point, given how many changes to our build have landed in the last year.
* The engine has been building locally for engine developers and on our bots for some time.

For anyone still experiencing issues compiling the engine on Windows, I'd encourage you to file a new issue with:
* Repro steps.
* The specific error message you're seeing, or if you see an issue with the exact same error message as you're getting, add a thumbs-up, but please don't add other unrelated errors to the same issue, instead file a new one.

**Closed by cbracken** 2022-04-26 18:08 UTC
Labels: engine, platform-windows, documentation, passed first triage, P4
