### ISSUE TITLE
Crash in dwds when establishing a connection to chrome devtools debugger (?)

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83056] opened 2021-05-20 20:59 UTC
```
Thread 0 main threadStateError: Bad state: No context with the running Dart application.
at RemoteDebuggerExecutionContext.id(execution_context.dart:55)
at <asynchronous gap>(async)
at AppInspector._getExtensionRpcs(inspector.dart:501)
at <asynchronous gap>(async)
at AppInspector._initialize(inspector.dart:93)
at <asynchronous gap>(async)
at AppInspector.initialize(inspector.dart:156)
at <asynchronous gap>(async)
at ChromeProxyService.createIsolate(chrome_proxy_service.dart:222)
at <asynchronous gap>(async)
```

@grouma @jacob314 

This is a top tool crasher on 2.2 stable.

**Comment by jonahwilliams** [comment] 2021-05-20 21:35
IIRC something similar was happening before when there was a page refresh, and the fix was perhaps to poll for the application to re-initialize?

It would be great if these bad state errors didn't crash the tool and instead were resilient to what might be transient issues. i.e. polling/retry/et cetera

At the very least, crashing with more info would be good

**Comment by christopherfujino** [comment] 2021-10-05 22:11
closing as a dupe of https://github.com/flutter/flutter/issues/60495

**Closed by christopherfujino** 2021-10-05 22:11 UTC
Labels: tool, platform-web, severe: fatal crash, found in release: 1.22
