### ISSUE TITLE
Both Scrolled Directions Data viewer for desktop app.

### ISSUE THREAD

**Issue by ara-kurd-dev** [flutter/flutter#115813] opened 2022-11-22 05:52 UTC
## Use case

I'm creating a desktop app that contains a data viewer which has to be scrolled in both direction (horizontal and vertical), I solved this situation by nesting two SingleChildScrollView but when more data is viewed it get more janks and it is missing frames so I tried ListView.builder to reduce this high performance but it gets so confusing when I want to be in both directions and not achievable.

## Proposal

Like I said before I solved them by nesting two SingleChildScrollView but if there is a solution more efficient, it would be much easier and more friendly for desktop developers.

**Comment by huycozy** [comment] 2022-11-22 11:37
@ara-kurd-dev Please check these issues (already filed with details info and discussion) to see if they are similar to this proposal: #49109, #30770

**Comment by goderbauer** [comment] 2022-11-22 23:28
@Piinks

**Comment by Piinks** [comment] 2022-11-29 00:18
This is a duplicate of the linked issues, so I am going to close it. This is currently in development, you can follow the 2D Scrolling project for more info. https://github.com/orgs/flutter/projects/32

**Closed by Piinks** 2022-11-29 00:18 UTC
Labels: waiting for customer response, in triage
