### ISSUE TITLE
Cannot access flutter_logs: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111428] opened 2022-09-13 00:19 UTC
When I try to open one of the `module_test_ios-objc-*.zip` logs: 

https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios/18504
<img width="403" alt="Screen Shot 2022-09-12 at 5 17 52 PM" src="https://user-images.githubusercontent.com/682784/189780581-bdc61c85-4a07-4d4d-b169-ef4ff722369c.png">

I get this error:
https://storage.googleapis.com/flutter_logs/flutter/51480144-4898-40f7-a00c-ae941ba8cb94/module_test_ios/51480144-4898-40f7-a00c-ae941ba8cb94/module_test_ios-objc-2022-09-12T15:59:17.080327.zip
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```

I am logged in.

**Comment by sealesj** [comment] 2022-09-13 14:26
Awaiting exemption approval for log access on bug b/245402084

**Comment by sealesj** [comment] 2022-09-19 18:08
Closing as duplicate of https://github.com/flutter/flutter/issues/111048

**Closed by sealesj** 2022-09-19 18:08 UTC
Labels: team: infra, P3
