### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by DTharaka** [flutter/flutter#70021] opened 2020-11-07 08:51 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hamdikahloun** [comment] 2020-11-07 09:24
Hi @DTharaka 

You should reply to the first issue you reported (https://github.com/flutter/flutter/issues/69978).

I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/69978. Please share the code snippet on that issue instead of creating another one.

Thank you

**Closed by hamdikahloun** 2020-11-07 09:24 UTC
