### ISSUE TITLE
Something didn't work as expect along WindowCompat.setDecorFitsSystemWindows

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#115421] opened 2022-11-16 09:22 UTC
## Steps to Reproduce

Android API 28

1. Copy and paste dart / gradle and kotlin codes
2. Execute `flutter run` on the code sample 
3. See that bottom bar is not visible
4. Click on the floating button to enable or not the fix.

The fix didn't feet my app needs but it show that flutter can handle system navigation bar padding.

**Expected results:** 
We should see the flutter bottom bar above the android system bottom bar.

**Actual results:** 
We see the flutter bottom bar behind the android system bottom bar.

As I see : the Kotlin method WindowCompat.setDecorFitsSystemWindows force the content to fit at the phone border (which is actually what I want). But, in addition, I'm looking to a way to position widget above the android system bar. Flutter seems to be able to achieve that but only with the double scaffold hack. My question is how the double scaffold fix work ? I saw that MediaQuery paddings are equal to zero, that's why i didn't understand well...

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool withDoubleScaffold = false;

  void swapMode() => setState(() => withDoubleScaffold = !withDoubleScaffold);

  @override
  Widget build(BuildContext context) {
    print("Home 1 paddings");
    print("viewPadding: ${MediaQuery.of(context).viewPadding.bottom}");
    print("padding: ${MediaQuery.of(context).padding.bottom}");

    if (withDoubleScaffold) {
      /// This fix the issue but this is weird (double scaffold...)
      return Scaffold(
        body: Page1(callback: swapMode),
      );
    } else {
      /// This should work...
      return SafeArea(
        top: false,
        child: Page1(callback: swapMode),
      );
    }
  }
}

class Page1 extends StatelessWidget {
  final VoidCallback callback;

  const Page1({Key? key, required this.callback}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print("Home 2 paddings");
    print("viewPadding: ${MediaQuery.of(context).viewPadding.bottom}");
    print("padding: ${MediaQuery.of(context).padding.bottom}");

    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: callback,
        child: const Icon(Icons.swap_horiz),
      ),
      body: Container(
        color: Colors.orange,
      ),
      bottomNavigationBar: BottomNavigationBar(
        elevation: 0,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(icon: Icon(Icons.home), label: "Home"),
          BottomNavigationBarItem(icon: Icon(Icons.shop), label: "Shop"),
          BottomNavigationBarItem(icon: Icon(Icons.settings), label: "Settings"),
        ],
      ),
    );
  }
}
```

MainActivity.kt
```kotlin
package com.example.untitled5

import io.flutter.embedding.android.FlutterActivity
import androidx.core.view.WindowCompat

class MainActivity : FlutterActivity() {
    override fun onPostResume() {
        super.onPostResume()
        // Used to let the app control system color (status bar, bottom nav bar)
        WindowCompat.setDecorFitsSystemWindows(window, false)
    }
}
```

android/app/build.gradle
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.untitled5"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.8.0' //add this line
}
```

</details>

<details>
  <summary>Logs</summary>

WindowCompat.setDecorFitsSystemWindows remove paddings
```
I/flutter (16214): WithDoubleScaffold: false
I/flutter (16214): Home 1 paddings
I/flutter (16214): viewPadding: 0.0
I/flutter (16214): padding: 0.0
I/flutter (16214): Home 2 paddings
I/flutter (16214): viewPadding: 0.0
I/flutter (16214): padding: 0.0

I/flutter (16214): WithDoubleScaffold: true
I/flutter (16214): Home 1 paddings
I/flutter (16214): viewPadding: 0.0
I/flutter (16214): padding: 0.0
I/flutter (16214): Home 2 paddings
I/flutter (16214): viewPadding: 0.0
I/flutter (16214): padding: 0.0
```

```
```

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale fr-FR)
    • Flutter version 3.3.8 on channel stable at /Users/earminjon/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM G950F (mobile) • ce10171ac4e0c93504 • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

Android API 28

https://user-images.githubusercontent.com/37028599/202139332-f130e0dc-0419-43d7-99f3-619194ad30f9.mp4

**Comment by danagbemava-nc** [comment] 2022-11-16 13:29
Hi @EArminjon, I'm not sure if this is an issue with flutter.  It seems to me like the api you're using on the native android side might not be backward compatible with versions below android 11. 

I tested the code sample you provided on android 11 and it worked as expected but on android 10 and 9, I run into the issues you ran into. 

Can you confirm that the api you're using is backward-compatible with android versions lower than 11?

<details>
<summary>recordings</summary>

| android 9 | android 11 |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/202192768-620685a3-54c3-4382-9383-a1f11d3e9b4d.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/202192780-ec8cef62-7292-4f35-97b3-68a899b554ac.mp4" /> |

</details>

**Comment by EArminjon** [comment] 2022-11-16 15:23
@danagbemava-nc yes I confirm using API 28 (Android 9). I believed that it was normal because of this lib but flutter seems to be able to position well a widget above the system bottom bar. I want to know how :/ ?

**Comment by danagbemava-nc** [comment] 2022-11-17 07:00
Hi @EArminjon, I'm not sure I completely understand. Could https://github.com/flutter/engine/blob/5bbf070c3f9d2be477258fdd9bafed5346907248/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L662 be what you're looking for?

**Comment by EArminjon** [comment] 2022-11-17 14:52
> Hi @EArminjon, I'm not sure I completely understand. Could https://github.com/flutter/engine/blob/5bbf070c3f9d2be477258fdd9bafed5346907248/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L662 be what you're looking for?

This is already inside flutter i think. 

What i'm looking for : How flutter achieve well to display my bottom bar above the android system bar in my example. How a double scaffold can fix the issue in the first video.

**Comment by danagbemava-nc** [comment] 2022-11-18 09:28
> This is already inside flutter i think.

Yes, it already is. 

> What i'm looking for : How flutter achieve well to display my bottom bar above the android system bar in my example. How a double scaffold can fix the issue in the first video.

I'm sorry, but I still do not understand your request. Please provide more details about what you want to achieve and be as clear as possible. 

Thank you

**Comment by EArminjon** [comment] 2022-11-18 09:52
@danagbemava-nc as you see on my first video, i would see my flutter bottom navigation bar. With the kotlin library that I've added, the MediaQuery.of(context).padding and viewPadding are equal to zero. I didn't know how flutter can successfully with a double scaffold position a widget above the native bottom bar. I reproduce that but without a double scaffold. I would do that with the kotlin library enabled.

It seems like flutter is able to find a bottom padding value but i didn't know how.

**Comment by danagbemava-nc** [comment] 2022-11-18 13:49
Hi @EArminjon, can you try modifying the `onPostResume` in your `MainActivity.kt` file to see if you're able to see the bottom nav bar. I don't think the API you're trying to use is backwards-compatible, so you may need to handle the cases for devices older than android 11. 

```kotlin
 override fun onPostResume() {
        super.onPostResume()
        // Used to let the app control system color (status bar, bottom nav bar)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            window.setDecorFitsSystemWindows(false); //also tried with true
        } else {
            window.setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN, WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
        }
    }
```

**Comment by danagbemava-nc** [comment] 2022-11-18 13:49
Hi @EArminjon, can you try modifying the `onPostResume` in your `MainActivity.kt` file to see if you're able to see the bottom nav bar. I don't think the API you're trying to use is backwards-compatible, so you may need to handle the cases for devices older than android 11. 

```kotlin
 override fun onPostResume() {
        super.onPostResume()
        // Used to let the app control system color (status bar, bottom nav bar)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            window.setDecorFitsSystemWindows(false); //also tried with true
        } else {
            window.setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN, WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
        }
    }
```

**Comment by EArminjon** [comment] 2022-11-18 14:59
Actually i already have something like that.  I kept the first if and put a condition in my code to handle in different manner my theme based on Android API number.

But, i created this issue to understand how the double scaffold trick work.

**Comment by danagbemava-nc** [comment] 2022-11-21 07:03
Hi @EArminjon, I believe the best place for this type of question will be StackOverflow. 

Given that this issue is caused by using a native API that doesn't seem to be backward compatible with older versions of android, I'm not sure what flutter can do. 

In light of the above, I'll be closing this issue. Kindly see https://flutter.dev/community#grid for places where you can ask such questions. 

Thank you

**Closed by danagbemava-nc** 2022-11-21 07:03 UTC
Labels: in triage
