### ISSUE TITLE
[Feature Request / Improvement Request ] Faster way of converting a Picture to an Image

### ISSUE THREAD

**Issue by Mesota22** [flutter/flutter#90542] opened 2021-09-22 19:27 UTC
## Use case
I started creating an app for writing down notes on your tablet using a pen. For this, I used a `CustomPaint` (with `canvas.drawLine()`) in combination with a `GestureDetector`. After some Lines, the app gets extreme frame drops and is unusable, so I converted the lines into images every few hundred offsets.
Here some of the relevant code:
```dart
ui.PictureRecorder recorder = ui.PictureRecorder();
// some code inbetween...
ui.Picture picture = recorder.endRecording();
ui.Image newImage = await picture.toImage(
         ....
      );
```
Now the problem with this method is that I am getting a really strong frame drop every time `toImage()` gets called.
### Recording of the issue in **Release Mode**:
![Peek 2021-09-22 21-12](https://user-images.githubusercontent.com/68391822/134407369-9efa2166-884d-41aa-b683-e50b164ad433.gif)
     
## Proposal
In the Flutter docs, there is mentioned that  _**['This is a slow operation that is performed on a background thread.'](https://api.flutter.dev/flutter/dart-ui/Scene/toImage.html)**_.
But I wanted to request a faster and more efficient way of converting a Picture to an Image.

**Comment by chinmaygarde** [comment] 2021-09-27 18:18
Instead of multiple `drawLine` calls, have you considered the effects of expressing the polyline as a single path and then using a single `drawPath` call? See https://github.com/flutter/flutter/issues/23461#issuecomment-432815662 for details on a similar issue.

**Comment by chinmaygarde** [comment] 2021-09-27 18:19
Closing this a duplicate of the linked issue.

**Closed by chinmaygarde** 2021-09-27 18:19 UTC
Labels: engine, dependency: dart, a: images, proposal, passed first triage, perf: speed
