### ISSUE TITLE
TableView on Flutter web app does not show vertical or horizontal scrollbars

### ISSUE THREAD

**Issue by davoutuk** [flutter/flutter#145467] opened 2024-03-20 14:28 UTC
### Steps to reproduce

Experimenting with TableView and cannot get the Flutter web app to scroll in any direction

### Expected results

Demo app has 8 x columns and 35 x rows and on Flutter web I would expect the view to show vertical and horizontal scrollbars.  

### Actual results

No scrollbars visible

### Code sample

<details open><summary>Code sample</summary>

```dart

class MainWindow extends StatefulWidget {
  const MainWindow({Key? key}) : super(key: key);
  @override
  State<MainWindow> createState() => _MainWindowState();
}
class _MainWindowState extends State<MainWindow> {

  final _dowTitle = ['','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

  ScrollController _horizController = ScrollController();
  ScrollController _vertController = ScrollController();

  Widget _taskTile(String aTitle, String aSubTitle) {
    return Card(
      elevation: 9.0,
      child: ListTile(
        title: Text(aTitle),
        subtitle: Text(aSubTitle),
        leading: Icon(Icons.task),
        trailing: Icon(Icons.forward),
      ),
    );
  }

  TableSpan _columnBuilder(int index) {
    final aColWidth = index == 0 ? 120.0 : 450.0;
    return TableSpan(
        extent: FixedTableSpanExtent(aColWidth),
        backgroundDecoration: TableSpanDecoration(border: TableSpanBorder(leading: BorderSide(color: Colors.grey), trailing: BorderSide(color: Colors.grey))),
        padding: TableSpanPadding(leading: 10.0, trailing: 10.0),
      recognizerFactories:
    );
  }

  TableSpan _rowBuilder(int index) {
    return TableSpan(extent: const FixedTableSpanExtent(100.0));
  }

  TableViewCell _cellBuilder(TableVicinity aVicinity) {
    if (aVicinity.xIndex == 0) {
      if (aVicinity.yIndex  == 0) {
        return TableViewCell(child: Container(),);
      } else {
        return TableViewCell(child: Center(child: Text('Day part')),);
      }
    } else {
      if (aVicinity.yIndex == 0) {
        return TableViewCell(child: Center(child: Text(_dowTitle[aVicinity.xIndex])),);
      }
      return TableViewCell(child: Center(child: _taskTile('aTitle', 'aSubTitle')),);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Expanded(
        flex: 1,
        child: TableView.builder(
          horizontalDetails:   ScrollableDetails.horizontal(controller: _horizController, ),
          verticalDetails:   ScrollableDetails.vertical(controller: _vertController,),
          columnCount: 8,
          rowCount: 35,
          pinnedColumnCount: 1,
          pinnedRowCount: 1,
          columnBuilder: _columnBuilder,
          rowBuilder: _rowBuilder,
          diagonalDragBehavior: DiagonalDragBehavior.none,
          cellBuilder: (context, vicinity) {
            return _cellBuilder(vicinity);
          },
        ),
      )
    ],);
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/25985256/e36e6071-04eb-4f5f-b3d5-6f98f32231ea)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4170], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)                        
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web                                                 
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.8)
[√] Android Studio (version 2021.1)                                              
[√] Android Studio (version 2023.1)                
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] Connected device (3 available)                 
[√] Network resources             
                                  
• No issues found!   
```

</details>

**Comment by davoutuk** [comment] 2024-03-20 14:41
I may have found a solution. Can you confirm that this approach is correct?

I've created my own custom MaterialScrollBehavoiur and then wrapped this around TableView.

```
class MyScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    // etc.
  };
}

  @override
  Widget build(BuildContext context) {
    return ScrollConfiguration(
      behavior: MyScrollBehavior(),
      child: Column(children: [
        Expanded(
          flex: 1,
          child: TableView.builder(
            horizontalDetails:   ScrollableDetails.horizontal(controller: _horizController, ),
            verticalDetails:   ScrollableDetails.vertical(controller: _vertController,),
            columnCount: 8,
            rowCount: 35,
            pinnedColumnCount: 1,
            pinnedRowCount: 1,
            columnBuilder: _columnBuilder,
            rowBuilder: _rowBuilder,
            diagonalDragBehavior: DiagonalDragBehavior.none,
            cellBuilder: (context, vicinity) {
              return _cellBuilder(vicinity);
            },
          ),
        )
      ],),
    );
  }

```

**Comment by huycozy** [comment] 2024-03-21 06:44
Hi @davoutuk 
Yes, your above solution is correct. You should also add a `Scrollbar` widget that wraps around your TableView, see https://github.com/flutter/flutter/issues/139840#issuecomment-1854493712.

Closing the issue as a duplicate of https://github.com/flutter/flutter/issues/139840.

**Closed by huycozy** 2024-03-21 06:44 UTC
Labels: in triage
