### ISSUE TITLE
Framework tree closed on corrupt zip file or bot cache?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123519] opened 2023-03-27 05:10 UTC
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20hot_mode_dev_cycle_win__benchmark/9172/overview

```
[2023-03-26 20:58:30.160066] [STDOUT] stderr: [   +4 ms] Flutter could not download and/or extract https://storage.googleapis.com/flutter_infra_release/flutter/685fbc6f4d9db8026c56ee1a177bb10cc09f884b/android-x64-release/windows-x64.zip. Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
[2023-03-26 20:58:30.160066] [STDOUT] stderr:            The original exception was: FileSystemException: Cannot open file, path = 'C:\opt\s\w\ir\x\w\recipe_cleanup\tmpn7iaa0r9\flutter sdk\bin\cache\downloads\storage.googleapis.com\flutter_infra_release\flutter\685fbc6f4d9db8026c56ee1a177bb10cc09f884b\android-x64-release\windows-x64.zip' (OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
[2023-03-26 20:58:30.160066] [STDOUT] stderr:            , errno = 225).
```

**Comment by MP00** [comment] 2023-03-27 17:03
In my pc (windows 10) SO blocked the file suspecting trojan (Wacatab.B!ml.)

![image](https://user-images.githubusercontent.com/24235471/228010650-b634e37e-9875-42c0-bd38-147a4ac20c57.png)

**Comment by Hixie** [comment] 2023-03-27 19:11
We received a report that the flutter_windows_3.7.8-stable.zip file is giving a similar error. The reported  hash256 value of that file as downloaded was d8d68004229c13ac763ed6023389ef8e2d49db26b059e4834402e21c1b4610c9.

**Comment by Hixie** [comment] 2023-03-27 19:21
@drewroengoogle tells me that is the hash in storage, so it's not a corruption-on-download issue or MITM attack.

**Comment by Hixie** [comment] 2023-03-27 19:34
Uploading https://storage.googleapis.com/flutter_infra_release/flutter/685fbc6f4d9db8026c56ee1a177bb10cc09f884b/android-x64-release/windows-x64.zip to virustotal.com did not find any issues in the file. I couldn't upload https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.7.8-stable.zip because that file is too big.

**Comment by gspencergoog** [comment] 2023-03-27 19:52
On my Windows machine, I get the same threat assessment for `gen_snapshot`.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8867023/228051273-603ae62a-a6b3-4cac-b0dc-3533c33f46b4.png">

**Comment by timsneath** [comment] 2023-03-27 20:00
We should go through this: https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide?view=o365-worldwide

**Comment by gspencergoog** [comment] 2023-03-27 20:17
<img width="239" alt="image" src="https://user-images.githubusercontent.com/8867023/228056674-9335bcb5-d6ee-41a1-9eb7-127b1d16451b.png">

**Comment by gspencergoog** [comment] 2023-03-27 20:36
When I run an app with Stable 3.7.7 or 3.7.6, I also get the above "cloud security scan" notification.

**Comment by gspencergoog** [comment] 2023-03-27 20:48
I've submitted `windows-x64.zip` to MS for analysis. So far, it claims to have found no issues with the file, but it's pending "final determination".

<img width="827" alt="image" src="https://user-images.githubusercontent.com/8867023/228063129-f8b770af-5210-4c2f-97a9-50b670443fc0.png">

**Comment by gspencergoog** [comment] 2023-03-27 20:51
The upload size is limited to 500MB, so I can't upload the whole distribution.  Maybe I'll try compiling an app in release mode and uploading that, assuming it triggers the "cloud security scan" on its own.

**Comment by gspencergoog** [comment] 2023-03-27 21:03
It seems to only do the "cloud security scan" the first time the compiled program is run, if I build it, but it happens every time if I `flutter run` it.

**Comment by drewroengoogle** [comment] 2023-03-27 21:17
@gspencergoog Have you seen the initial "Threat Quarantined" popup on any other versions of the `gen_snapshot` artifact?

**Comment by drewroengoogle** [comment] 2023-03-27 21:38
> https://storage.googleapis.com/flutter_infra_release/flutter/685fbc6f4d9db8026c56ee1a177bb10cc09f884b/android-x64-release/windows-x64.zip

It seems that the [3.7.7 release artifact](https://storage.googleapis.com/flutter_infra_release/flutter/1837b5be5f0f1376a1ccf383950e83a80177fb4e/android-x64-release/windows-x64.zip) does not trigger the quarantine like the 3.7.8 version does.

**Comment by gspencergoog** [comment] 2023-03-27 21:59
Okay, now when I download the original file in the OP above: 

https://storage.googleapis.com/flutter_infra_release/flutter/685fbc6f4d9db8026c56ee1a177bb10cc09f884b/android-x64-release/windows-x64.zip

I no longer get a quarantine notice for it, and I'm able to unpack the file with no issues. So either some malicious actor has transparently replaced the file on the server with a non-offensive version, or MS has updated their online virus definitions. I'm hoping for the latter, but we'll have to check for the former.

**Comment by gspencergoog** [comment] 2023-03-27 22:00
Also, to further support the idea that MS updated their virus definitions, the file that I originally downloaded to test this _also_ no longer triggers the notice.

**Comment by gspencergoog** [comment] 2023-03-27 22:03
And the files are identical (have the same sha256 sum).

**Comment by Hixie** [comment] 2023-03-28 00:18
We're rebuilding the relevant files just to be sure.

**Comment by FusoraTech** [comment] 2023-03-28 12:38
We got the same false positive. The cause was tracked down to an install package using Inno Setup containing a deletion clause like:

[InstallDelete]
Type: filesandordirs; Name: "{app}\Resources\SomeFolder"

Once that deletion clause was removed the false positive ended.

Any deletion clause added to a test triggered it again.

**Comment by drewroengoogle** [comment] 2023-03-28 15:47
@godofredoc Verified via GCS audit logs that the artifact was not modified after the initial creation of the artifact during this build: https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/20852

**Comment by gspencergoog** [comment] 2023-03-28 17:28
I got back the results from the original submission to MS, with the result "Not Malware".

<img width="1106" alt="Screenshot 2023-03-28 at 10 27 29 AM" src="https://user-images.githubusercontent.com/8867023/228320308-f87e5fe1-19fd-48b6-a9ba-49160948d3bd.png">

**Comment by Hixie** [comment] 2023-03-28 17:39
@FusoraTech Fascinating, thanks for that data point.

Given that this seems to have been a fluke transient bug in Windows Defender, I'm going to close this issue. Thanks for everyone's help in tracking it down.

**Comment by Hixie** [comment] 2023-03-29 16:22
Published a postmortem at https://github.com/flutter/flutter/wiki/Postmortem:-Windows-Defender-alert-on-2023-03-26

**Comment by jmagman** [comment] 2023-03-31 23:18
Tree is closed, seems to be happening again?

https://ci.chromium.org/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/7840
https://ci.chromium.org/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/7839
https://ci.chromium.org/p/flutter/builders/prod/Windows_android%20hot_mode_dev_cycle_win__benchmark/9292
https://ci.chromium.org/p/flutter/builders/prod/Windows_android%20flutter_gallery_win__compile/9291

**Comment by godofredoc** [comment] 2023-03-31 23:22
@christopherfujino how is the tool downloading files in windows? wget | curl | or some powershell?

**Comment by jmagman** [comment] 2023-03-31 23:37
I think that code is here, I'm not sure how dart implements that on Windows.
https://github.com/flutter/flutter/blob/e4e1444b26109c8ef0a080c40cd0ce599ffc8025/packages/flutter_tools/lib/src/cache.dart#L1156-L1157

**Comment by godofredoc** [comment] 2023-03-31 23:45
Updates:

* The file is correct, it downloads and extracts correctly on my windows machine.
* Defender complaints about trying to run a binary downloaded from the internet.
* Defender does not find any malware in the artifact.

**Comment by godofredoc** [comment] 2023-03-31 23:52
A led retry using an identical build configuration fails with the same file:

https://chromium-swarm.appspot.com/task?id=6152d9a31054f110

**Comment by godofredoc** [comment] 2023-04-01 00:23
Update:

Running `powershell Get-MpThreatDetection` in win-4 bot shows that defender has been flagging different files since 3/26.

```
ActionSuccess                  : True
AdditionalActionsBitMask       : 0
AMProductVersion               : 4.18.2302.7
CleaningActionID               : 2
CurrentThreatExecutionStatusID : 1
DetectionID                    : {54A89D5C-4B06-4887-879F-C32B57E8DFF3}
DetectionSourceTypeID          : 3
DomainUser                     : FLUTTER-WIN-4\swarming
InitialDetectionTime           : 3/26/2023 2:39:54 PM
LastThreatStatusChangeTime     : 3/26/2023 2:40:29 PM
ProcessName                    : C:\opt\s\w\ir\x\w\recipe_cleanup\tmp2it1c_5k\flutter sdk\bin\cache\dart-sdk\bin\dart.exe
RemediationTime                : 3/26/2023 2:40:29 PM
Resources                      : {file:_C:\opt\s\w\ir\x\w\recipe_cleanup\tmp2it1c_5k\flutter sdk\bin\cache\downloads\storage.googleapis.com\flutter_infra_releas 
                                 e\flutter\685fbc6f4d9db8026c56ee1a177bb10cc09f884b\android-x64-release\windows-x64.zip}
ThreatID                       : 2147814524
ThreatStatusErrorCode          : 0
ThreatStatusID                 : 3
PSComputerName                 :
```

and 

```
ActionSuccess                  : True
AdditionalActionsBitMask       : 0
AMProductVersion               : 4.18.2302.7
CleaningActionID               : 2
CurrentThreatExecutionStatusID : 1
DetectionID                    : {A67D0368-5EFC-4184-BB17-4B2502DBAB62}
DetectionSourceTypeID          : 3
DomainUser                     : FLUTTER-WIN-4\swarming
InitialDetectionTime           : 3/31/2023 4:03:11 PM
LastThreatStatusChangeTime     : 3/31/2023 4:03:39 PM
ProcessName                    : C:\opt\s\w\ir\x\w\recipe_cleanup\tmptzyj5rr6\flutter sdk\bin\cache\dart-sdk\bin\dart.exe
RemediationTime                : 3/31/2023 4:03:39 PM
Resources                      : {file:_C:\opt\s\w\ir\x\w\recipe_cleanup\tmptzyj5rr6\flutter sdk\bin\cache\downloads\storage.googleapis.com\flutter_infra_releas
                                 e\flutter\a109903148725d475f0664f09cb2baaf93bfc8c8\android-arm64-release\windows-x64.zip}
ThreatID                       : 2147735503
ThreatStatusErrorCode          : 0
ThreatStatusID                 : 3
PSComputerName                 :
```

**Comment by godofredoc** [comment] 2023-04-01 00:31
Defender module for reference:

https://learn.microsoft.com/en-us/powershell/module/defender/?view=windowsserver2022-ps

**Comment by godofredoc** [comment] 2023-04-01 02:05
Replication command:

`led get-build 8785152086348462785 | led edit-system -p 20 | led launch -modernize`

**Comment by Hixie** [comment] 2023-04-11 23:13
I'm going to close this for now, since we're not actively working on it and are unlikely to make useful progress any time soon given that the behaviour does not reproduce reliably (or at all, it seems, right now). When (if) we run into it in the future, we should see if the logging is sufficient, and if not, add more, until such time as we have enough information to do something useful.

**Closed by Hixie** 2023-04-11 23:13 UTC
Labels: tool, team: infra, passed secondary triage, P2
