### ISSUE TITLE
Flutter application having flutter version 3.13.6 run on Xcode 15 ,iOS-17 on physical device launch Xcode each time

### ISSUE THREAD

**Issue by sandip247** [flutter/flutter#136183] opened 2023-10-09 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run flutter application on Android studio 
Xcode 15
iOS -17 physical iPhone device
observed each time launched Xcode

### Expected results

Run application from studio not need to launch Xcode each time

### Actual results

Xcode Launch on each run from studio 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="1629" alt="Screenshot 2023-10-09 at 10 24 11 AM" src="https://github.com/flutter/flutter/assets/39800156/3e8c9088-2546-4acd-b7fe-aafa1aa39bc8">
<img width="1650" alt="Screenshot 2023-10-09 at 10 23 02 AM" src="https://github.com/flutter/flutter/assets/39800156/1a9b4e75-65ee-4b7c-a189-3b4618e39d12">
<img width="1381" alt="Screenshot 2023-10-09 at 10 22 30 AM" src="https://github.com/flutter/flutter/assets/39800156/78fe69ed-438c-48ac-8494-4877249ae8fb">
<img width="1418" alt="Screenshot 2023-10-09 at 10 21 41 AM" src="https://github.com/flutter/flutter/assets/39800156/395cafe9-6b78-4c41-a741-bf7300cf1c3d">
<img width="1647" alt="Screenshot 2023-10-09 at 10 21 33 AM" src="https://github.com/flutter/flutter/assets/39800156/9a6b074b-1c7a-4497-baae-2df66717d816">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-09 10:29
Duplicate of https://github.com/flutter/flutter/issues/133465

**Closed by stuartmorgan** 2023-10-09 10:29 UTC

**Comment by Altanbold** [comment] 2023-10-12 08:56
any solution here?
