### ISSUE TITLE
TextField MaxLines is required when MinLines is set

### ISSUE THREAD

**Issue by sylviedaey** [flutter/flutter#117524] opened 2022-12-22 10:17 UTC
## Steps to Reproduce

1. Use TextField widget
```
TextField(
              keyboardType: TextInputType.multiline,
              minLines: 2,
              onChanged: vm.onCommentChanged,
              decoration: InputDecoration(
                border: InputBorder.none,
                hintStyle: context.textTheme.getBodyMedium(),
              ),
            ),
```
3. Set _minLines: 2_ **without** adding maxLines:null

**Expected results:** 
TextField is loaded correctly since maxLines is not optional.

**Actual results:** 
Failed assertion, fixed when we add maxLines:null in the TextField
![image](https://user-images.githubusercontent.com/11648458/209111219-c2216594-693e-443f-bb01-a16f76ba2ba1.png)

<details>
<summary>Flutter version</summary>
Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18a827f393 (3 months ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

</details>

**Comment by darshankawar** [comment] 2022-12-22 12:56
@sylviedaey 
Thanks for the report.
According to minLines [documentation](https://api.flutter.dev/flutter/material/TextField/minLines.html):

`if the value is set, it must be greater than zero. If the value is greater than 1, [maxLines](https://api.flutter.dev/flutter/material/TextField/maxLines.html) should also be set to either null or greater than this value.`

So in your case, since you have `minLines: 2`, you will need to use `maxLines` and should set it to `null` or greater than 2. With that change, the said error doesn't occur.

With that said, closing as this is not a bug according to documentation. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-12-22 12:56 UTC
Labels: in triage
