### ISSUE TITLE
Listview.builder inside AlertDialog displays nothing

### ISSUE THREAD

**Issue by ConProgramming** [flutter/flutter#21322] opened 2018-09-01 18:12 UTC
```
          return AlertDialog(
            title: Text('Dialog Name'),
            content: new ListView.builder(
              itemBuilder: (BuildContext context, int index) {
                new  Text("hi");

              },
              itemCount: 2,
              padding: EdgeInsets.all(0.0),
              shrinkWrap: true,
            ),
            actions: <Widget>[
              FlatButton(
                child: Text('SAVE'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
              FlatButton(
                child: Text('CANCEL'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          );
```

This is the code for my alertdialog. There should be two lines of text saying "hi", but it's just empty. I don't really think a screenshot is necessary, and there are no errors being thrown. The content is just an empty listview.

EDIT:
`Flutter doctor -v` output

```
[✓] Flutter (Channel unknown, v0.5.1, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.5.1 at /Users/conneraldrich/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

\Error executing simctl: -6
dyld: Symbol not found: _SimDeviceBootKeyDisabledJobs
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Expected in: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
 in /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
                                                                                      [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/conneraldrich/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Community Edition (version 2016.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • E6830 • 611896418 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment] 2018-09-01 18:41
Please add the output of `flutter doctor -v`.

**Comment by ConProgramming** [comment] 2018-09-01 19:08
@zoechi There you go

**Comment by zoechi** [comment] 2018-09-04 08:57
With your code I get
```
I/flutter (21317): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21317): The following assertion was thrown during performLayout():
I/flutter (21317): RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
I/flutter (21317): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter (21317): defeats the point of viewports being lazy.
I/flutter (21317): If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
I/flutter (21317): to achieve that effect by just giving the viewport loose constraints, without needing to measure its
I/flutter (21317): intrinsic dimensions.
```
because the dialog content size is not limited.
Do you not get this exception?
Can you please provide a more complete reproduction?

**Comment by zoechi** [comment] 2018-10-08 09:15
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 09:15 UTC
Labels: waiting for customer response
