### ISSUE TITLE
Opening or closing a TextField causes MaterialPageRoute to rebuild the page

### ISSUE THREAD

**Issue by zbarryte-luminopia** [flutter/flutter#37878] opened 2019-08-08 17:43 UTC
## Steps to Reproduce

1. Create a new flutter project, and replace the contents of your `main.dart` file with the following:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: (settings) {
        final settingsName = settings.name;
        switch (settingsName) {
          case '/':
            return MaterialPageRoute(builder: (context) => Page(), settings: settings);
          default:
            throw Exception('No route found for settings named $settingsName');
        }
      },
    );
  }
}

class Page extends StatelessWidget {
  final pageProperty = PageProperty();

  @override
  Widget build(BuildContext context) {
    print('Rebuilding Page...');
    return Material(
      child: Center(
        child: TextField(
          decoration: InputDecoration(
            filled: true,
            fillColor: Colors.pink,
          ),
        ),
      ),
    );
  }
}

class PageProperty {
  PageProperty() {
    print('Constructing PageProperty...');
  }
}

```

2. Launch the application on an iOS device or simulator.
3. Observe the logs. Note that a log has been made for the call to `Page.build` and for the constructor of the `PageProperty`.  Note how many of these logs their are.
4. Tap the pink text field to bring up the keyboard.
5. Observe the logs. Note that an additional log has been made for the call to `Page.build` and for the constructor of the `PageProperty`.
6. Dismiss the keyboard.
7. Observe the logs. Not that yet another log has been made for the call to `Page.build` and for the constructor of the `PageProperty`.
8. Continue bringing up the keyboard via the text field and dismissing it to cause more logs to appear.

## Issue Description

It appears that the text field is not obeying the contract of `ModalRoute.buildPage` -- from the documentation:
```
/// This method is only called when the route is first built, and rarely
  /// thereafter. In particular, it is not automatically called again when the
  /// route's state changes unless it uses [ModalRoute.of]. For a builder that
  /// is called every time the route's state changes, consider
  /// [buildTransitions]. For widgets that change their behavior when the
  /// route's state changes, consider [ModalRoute.of] to obtain a reference to
  /// the route; this will cause the widget to be rebuilt each time the route
  /// changes state.
```

When the text field is tapped, or when the keyboard is dismissed, the underlying call to `SystemChannels.textInput.invokeMethod<void>('TextInput.show');` or `SystemChannels.textInput.invokeMethod<void>('TextInput.hide');` respectively is triggering `_ModalScopeState.didChangeDependencies`, which is causing the root widget to be rebuilt in this case.

This issue is especially detrimental if the root widget relies upon a `TextEditingController` with some default value.  If, for example, you add the following property to the sample `Page` widget...

```
final textFieldController = TextEditingController(text: 'Initial Text');
```

...and then pass that controller into the `TextField`, the result is that the text field value will always change back to `Initial Text` when the user dismisses the keyboard.

## Output of `flutter doctor -v`

```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/me/Library/Flutter/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (3 available)
    • iPad (6th generation) • 202F104D-EDCF-4D89-851A-881F062C4760 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • macOS                 • macOS                                • darwin-x64     • Mac OS X
      10.14.5 18F132
    • web                   • web                                  • web-javascript • Google Chrome
      75.0.3770.142 


• No issues found!
```

**Comment by xiejibiao** [comment] 2019-08-10 04:12
I tried to add it ' final textFieldController = TextEditingController(text: 'Initial Text'); ', but it didn't work.

**Comment by xiejibiao** [comment] 2019-08-10 04:13
I tried to add it ' final textFieldController = TextEditingController(text: 'Initial Text'); ', but it didn't work. Is it because of version problem that I use v1.5.0?

**Comment by xiejibiao** [comment] 2019-08-10 04:15
I tried to add it ' final textFieldController = TextEditingController(text: 'Initial Text'); ', but it didn't work. Is it because of version problem that I use v1.5.0?

Output of flutter doctor -v

`[✓] Flutter (Channel unknown, v1.5.0, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
    • Flutter version 1.5.0 at /Users/xjb/Desktop/DevelopmentToot/flutter
    • Framework revision a18226d066 (4 months ago), 2019-04-16 00:16:17 -0400
    • Engine revision 9970fb5500
    • Dart version 2.2.1 (build 2.2.1-dev.4.2 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xjb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.`

**Comment by zbarryte-luminopia** [comment] 2019-08-12 13:42
@xiejibiao - The following is valid in `v1.7.8+hotfix.4`.

```
class Page extends StatelessWidget {
  final textFieldController = TextEditingController(text: 'Something');
  final pageProperty = PageProperty();

  @override
  Widget build(BuildContext context) {
    print('Rebuilding Page...');
    return Material(
      child: Center(
        child: TextField(
          controller: textFieldController,
          decoration: InputDecoration(
            filled: true,
            fillColor: Colors.pink,
          ),
        ),
      ),
    );
  }
}
```

The main point of this defect, however, is that the `TextField` widget incorrectly causes the `MaterialPageRoute` widget to rebuild the page.  The defect has only been confirmed on the version listed in the defect description.

**Comment by dotronglong** [comment] 2019-08-23 12:16
I had similar problem recently, and I can see the is a way to work around that from the parent always sends the same widget to children. I am not sure this is a bug or not, however, from my perspective I assume this is a bug, as children stateless widget should not affect parent widget. Hope we can have a better solution.
```
class MyApp extends StatelessWidget {
    final Page _page = Page();
    // ...
    return MaterialPageRoute(builder: (context) => _page, settings: settings);
```

**Comment by zbarryte-luminopia** [comment] 2019-08-23 13:37
@dotronglong - Yes, caching does seem to be a work-around for the issue, though, of course, non-ideal.  I'm caching in a similar way as a work-around (via a custom extension of `MaterialPageRoute`, similar to what some have mentioned in issue [31150](https://github.com/flutter/flutter/issues/31150)) until this issue is resolved by the Flutter team (I hope soon! It's a pretty detrimental issue!).  This is definitely a defect, because the behavior breaks a contract.

**Comment by rrousselGit** [comment] 2019-08-28 17:09
That's expected.
The keyboard appeared/disappeared, and therefore the screen size changed, which updates MediaQuery and some other widgets.

**Comment by zbarryte-luminopia** [comment] 2019-08-29 14:05
@rrousselGit - Though the keyboard appearing/disappearing causes specific widgets, like `Scaffolds`, to resize, it's unfortunately not true that that action causes the screen size to change.  `MediaQuery.size` does not change between builds, so this behavior is not expected.  This defect appears to be caused by a broken contract in `ModalRoute.buildPage`, which is causing the entire widget tree to be rebuilt; it is only expected that certain widgets respond to this action and trigger their own rebuilds.

**Comment by amirtabasi** [comment] 2019-09-27 09:08
tnx  to https://github.com/flutter/flutter/issues/27351#issuecomment-459561163 my problem solved! but i confused ! because some issue in this subject closed some another still open but no one said what is the solution !! is it a bug !?!

for me, i have a main page with a textfield for search and after on submit of textfield, navigate to another page, and in the second page i have textfield again but in this page after on submit, listview Items change and keyboard hide, 
in this position if i touch on textfield page rebuild and listview goes back to first state ! 

![untitled](https://user-images.githubusercontent.com/55507206/65756973-04ac0c80-e123-11e9-966a-7352e5d7bf30.gif)

**Comment by zbarryte-luminopia** [comment] 2019-09-30 13:06
@amirtabasi - Yes, this is still a bug.  It is unclear why the related issues are closed, since the problem isn't solved.  I think it is an error that they are closed.

It sounds like the problem you have is caused by the root page being triggered to reload by a keyboard on a different page.  The action seems to be triggered by the keyboard, as described in this issue.

**Comment by rrousselGit** [comment] 2019-09-30 13:57
@zbarryte-luminopia The change is not on MediaQuery.size but on the padding values.

The bottom padding is increasing, which requires to update MediaQuery, which implies a `setState` and therefore a rebuild of the associated widget tree.

Although it's arguably not optimal, it's not a bug.

It can be optimized, but strictly speaking, the gain is very small.

**Comment by searchy2** [comment] 2019-09-30 19:55
How do you propose building complex apps with multiple page level blocs and nested navigation when MaterialPageRoute clears the state when the keyboard is shown?
For example, I have Post Page and a User Profile Page. You can navigate from the Post Page to the User Profile page via a MaterialPageRoute. The User Profile page can exist independent to the Post Page and can be navigated to directly. This means each page has it's own bloc. 
When I navigate to the User Profile page, the keyboard is managed correctly. However, when I navigate to the User Profile page via a MaterialPageRoute, the User Profile page bloc is cleared anytime the keyboard shows! The only way to preserve the state seems to be putting the User Profile bloc above the MaterialPageRoute navigation which doesn't make sense. 

Copied from #26004 :
This is a huge problem and prevents building complex Flutter applications. When the user navigates to a page via MaterialPageRoute, the keyboard causes MaterialPageRoute to rebuild!! This means it doesn't matter if you use a Stateless or Stateful widget, you will lose all state because MaterialPageRoute is at the root.
The only way to prevent this from happening is to put everything in a top level bloc above ANY navigation. This means complex apps cannot be built because there is can only be one top level bloc and there cannot be page level blocs because their state can be lost.

**Comment by rrousselGit** [comment] 2019-09-30 20:17
> How do you propose building complex apps with multiple page level blocs and nested navigation when MaterialPageRoute clears the state when the keyboard is shown?

The build method being called again should _never_ have such an impact.
If, in your app, it does, then it's because _your code_ is bugged because of a misuse of the build method.

In Flutter, the method "build" could be called thousands of times a second that it shouldn't have any impact on the behavior of your app.
If that's not the case for you, then you're likely missing a StatefulWidget somewhere.

**Comment by searchy2** [comment] 2019-09-30 20:23
The problem is that the Stateful Widget exists as a "Page" you can navigate to via MaterialPageRoute. 
Here's the hierarchy:
Page 1 ⭢ MaterialPageRoute
                                            ⮡  Page 2 (Stateful Widget)
Whenever the keyboard appears, Page 2 gets rebuilt even though it's a Stateful Widget! This causes it to lose it's state :(

**Comment by searchy2** [comment] 2019-09-30 20:30
OK, the solution seems to be caching the widget either outside the MaterialPageRoute or as an initial data value inside a StatefulWidget. I'm happy there is a solution for the time being but it's definitely not ideal.

**Comment by rrousselGit** [comment] 2019-10-02 08:43
Okey I've made the necessary changes to fix this issue. I'll open a PR today.

But it's important to note that this issue still shouldn't have any impact on your app. If it did cause undesired side effects on your side, then you have a bug, even with this being optimized away.

**Comment by zbarryte-luminopia** [comment] 2019-10-02 14:24
Thank you, @rrousselGit !

**Comment by EugenePisotsky** [comment] 2019-10-03 06:36
@rrousselGit, in my case animation is janky when the keyboard is opening along with it. doesn't rebuilding all the tree has any impact on the animation?
(without keyboard it's smooth)

**Comment by Martibis** [comment] 2019-10-03 17:41
I utilize the GoogleMap Widget, opening the keyboard by tapping TextField causes my StateFul Widget to completely rebuild (including the  map tiles) and run initState (where I reset the markers in my case).

**Comment by jonataslaw** [comment] 2019-10-06 01:15
> Okey I've made the necessary changes to fix this issue. I'll open a PR today.
> 
> But it's important to note that this issue still shouldn't have any impact on your app. If it did cause undesired side effects on your side, then you have a bug, even with this being optimized away.

I do not have a bug, I have a complex application (I believe the largest project made in Flutter, with over 200 screens). Main Screen is a feed that can have maps, videos, music, images and text. Now imagine the user scrolling through 500 items, clicking on a user's avatar, entering their profile and sending a message, with each message the keyboard opens and closes and 500 items with images, maps and videos are reconstructed. Not even the stout smartphone can handle it.
This is not a bug of my app, but a Flutter bug, the state of previous screens should not be rebuilt under any circumstances, and opening and closing the keyboard should not change the state of all widgets below MaterialApp.
If Flutter can't fix it, it should go back to beta, as it wouldn't be a production-ready framework.

**Comment by rrousselGit** [comment] 2019-10-06 14:33
> with each message the keyboard opens and closes and 500 items with images, maps and videos are reconstructed. Not even the stout smartphone can handle it.

This issue is unrelated to images/maps/videos being reconstructed. 

I insist on saying that if this issue is causing problems on your side, then you should look deeper into the problem because it's unlikely to be what you think it is.

Take this snippet:

```dart
FutureBuilder(
  future: fetchSomething(),
  builder: ...
)
```

or:

```dart
MyWidget(
  key: UniqueKey(),
);
```

With these, opening the keyboard *will* cause problems. But that's not _this issue_ the problem, it's these snippets that are bugged.

What's happening here is that this issue only reveals these problems. Fixing the rebuild issue on keyboard open/close won't make your problems disappear. It'll only hide them.

**Closed** 2019-10-09 23:32 UTC
Labels: f: material design, framework

**Comment by amitkot** [comment] 2019-10-23 11:58
@rrousselGit 
I believe this is not just an optimization, rather an actual bug that you fixed.
It is, in my opinion, surprising behaviour that the PageRouteBuilder is called every time a TextField is clicked.
It is different than not putting expensive tasks inside the build() function, in this case the dependencies for the Page itself might be recreated.

See, for example, [this code](https://gist.github.com/amitkot/b3c94fa172e2a6541707fe837646fd0d). A Page ctor receives a Bloc as a dependency. Assuming the Bloc accesses an expensive API on creation, normal use of the page that might include multiple interactions with the text field which will be expensive and surprising.

**Comment by binghandsom** [comment] 2020-01-01 15:03
> > How do you propose building complex apps with multiple page level blocs and nested navigation when MaterialPageRoute clears the state when the keyboard is shown?
> 
> In Flutter, the method "build" could be called thousands of times a second that it shouldn't have any impact on the behavior of your app.
> 
> If that's not the case for you, then you're likely missing a StatefulWidget somewhere.

I couldn't agree with you,even though flutter build quickly,it can lead to great problem,I have lot of network inside page's building in my project,and the network request my server,if too many requests
ceaselessly come into being my server will got a catastrophy

**Comment by rrousselGit** [comment] 2020-01-01 15:09
> I couldn't agree with you,even though flutter build quickly,it can lead to great problem,I have lot of network inside page's building in my project,and the network request my server,if too many requests
ceaselessly come into being my server will got a catastrophy

Then you have a bug.

You likely fell for: https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

**Comment by joabh** [comment] 2020-03-03 15:59
> 
> 
> > with each message the keyboard opens and closes and 500 items with images, maps and videos are reconstructed. Not even the stout smartphone can handle it.
> 
> This issue is unrelated to images/maps/videos being reconstructed.
> 
> I insist on saying that if this issue is causing problems on your side, then you should look deeper into the problem because it's unlikely to be what you think it is.
> 
> Take this snippet:
> 
> ```dart
> FutureBuilder(
>   future: fetchSomething(),
>   builder: ...
> )
> ```
> 
> or:
> 
> ```dart
> MyWidget(
>   key: UniqueKey(),
> );
> ```
> 
> With these, opening the keyboard _will_ cause problems. But that's not _this issue_ the problem, it's these snippets that are bugged.
> 
> What's happening here is that this issue only reveals these problems.
> **Fixing the rebuild issue on keyboard open/close won't make your problems disappear. It'll only hide them.**

I am using a future builder to return a widget and am experiencing the same problem with focusing on textboxes cause the build function to re-run, preventing any input from being able to happen. Are you saying that there is a known bug with the future builder or that it is something in my code that is causing this?

**Comment by shaimo** [comment] 2020-05-08 08:27
I just ran into the same issue. @dotronglong @zbarryte-luminopia how can I use the caching workaround when using a named route?

**Comment by midnight-cigarettes** [comment] 2021-01-03 04:16
> > I couldn't agree with you,even though flutter build quickly,it can lead to great problem,I have lot of network inside page's building in my project,and the network request my server,if too many requests
> > ceaselessly come into being my server will got a catastrophy
> 
> Then you have a bug.
> 
> You likely fell for: https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

This was a year ago, but thanks for this one. 
This solved my problem. No more global keys for my TextField.

**Comment by okelloEnos** [comment] 2021-06-18 17:56
Am still confused to call this issue a bug or a misuse of the widget by my encounter on this issue i managed to retrieve the solution by getting rid of MediaQuery

**Comment by pinguluk** [comment] 2021-06-24 12:50
> Am still confused to call this issue a bug or a misuse of the widget but my encounter on this issue i managed to retrieve the solution by getting rid of MediaQuery .

I got the same issue and solution, **but**, it seems that **every** `MediaQuery.of(context)` is triggered, which means that every widget/page that contains `MediaQuery.of(context)` in the build method, will be triggered.

Example:
Main **page A** contains in the build a MediaQuery.of(context) and a button.
The button opens a new widget/page via 
```
Navigator.of(context).push(
    MaterialPageRoute(
        builder: (context) => PageB(),
    ),
),
```

**Page B** contains a `MediaQuery.of(context)` and a button too.
Again, the button opens a new widget/page via the Navigator & MaterialPageRoute, called Page C.

In **page C** you have a input field.
When you click the input field, the keyboard opens and **every** `MediaQuery.of(context)`, meaning that **all** the pages (page A and Page B) will be rebuilt.

Does anyone know a solution for this? I don't want all the pages to be rebuilt, if i'm another route.
