### ISSUE TITLE
Unable to run "adb"

### ISSUE THREAD

**Issue by KumarMonisankarBasu** [flutter/flutter#84722] opened 2021-06-16 18:24 UTC
## Steps to Reproduce

1. ...flutter doctor
2. ...
3. ...

## Logs

PS C:\Users\KUMAR MONISANKAR> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.572], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Android\sdk\platform-tools\adb.exe

! Doctor found issues in 1 category.
![Screenshot (9)](https://user-images.githubusercontent.com/73847877/122272443-2f915200-cefe-11eb-930e-47a4f2855532.png)
![Screenshot (10)](https://user-images.githubusercontent.com/73847877/122272445-315b1580-cefe-11eb-9bd5-fa18e908bebc.png)
![Screenshot (11)](https://user-images.githubusercontent.com/73847877/122272448-31f3ac00-cefe-11eb-93c2-c477ca736bb9.png)

**Comment by darshankawar** [comment] 2021-06-17 07:59
Closing this as duplicate of https://github.com/flutter/flutter/issues/72101

**Closed by darshankawar** 2021-06-17 07:59 UTC
Labels: in triage
