### ISSUE TITLE
TypeError: dart.global.firebase.auth is not a function

### ISSUE THREAD

**Issue by bcagarwal** [flutter/flutter#78980] opened 2021-03-24 16:29 UTC
## Steps to Reproduce

1.	Create a flutter app with web support enabled
2.	Add firebase core and auth dependencies in the pubspec.yaml
3.	Add an ElevatedButton and add onPressed event to the button
4.	On Firebase console, create a project and add app for iOS, Android and Web
5.	Complete necessary configuration for iOS, Android and Web in the Flutter app
6.	Enabled Anonymous Authentication in the firebase project under Sign-in method
7.	Add the below async/await function on the onPressed event of the button
 
```
Future<void> _signInAnonymously() async {
      final userCredentials =  await FirebaseAuth.instance.signInAnonymously();
      print('${userCredentials.user!.uid}');
  }
```

There is auto generated dart file (**generated_plugin_registrant.dart**) during the setup of the flutter project with above steps

The content as follows

```
//
// Generated file. Do not edit.
//

// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_auth_web/firebase_auth_web.dart';
import 'package:firebase_core_web/firebase_core_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  FirebaseAuthWeb.registerWith(registrar);
  FirebaseCoreWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}
```

**Expected results:** 

Uid should be printed in the console

**Actual results:** 

```
TypeError: dart.global.firebase.auth is not a function
    at Object.getAuthInstance (http://localhost:59963/packages/firebase_auth_web/src/interop/auth.dart.lib.js:974:70)
    at new firebase_auth_web.FirebaseAuthWeb.new (http://localhost:59963/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:432:27)
    at firebase_auth_web.FirebaseAuthWeb.__.delegateFor (http://localhost:59963/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:75:14)
    at Function.instanceFor (http://localhost:59963/packages/firebase_auth_platform_interface/src/types.dart.lib.js:1520:77)
    at firebase_auth.FirebaseAuth.__.get [_delegate] (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:100:135)
    at firebase_auth.FirebaseAuth.__.signInAnonymously (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:246:68)
    at signInAnonymously.next (<anonymous>)
    at runBody (http://localhost:59963/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:59963/dart_sdk.js:37260:7)
    at firebase_auth.FirebaseAuth.__.signInAnonymously (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:245:20)
    at _signInAnonymously (http://localhost:59963/packages/time_tracker/app/sign_in/sign_in_page.dart.lib.js:702:74)
    at _signInAnonymously.next (<anonymous>)
    at runBody (http://localhost:59963/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:59963/dart_sdk.js:37260:7)
    at sign_in_page.SignInPage.new.[_signInAnonymously] (http://localhost:59963/packages/time_tracker/app/sign_in/sign_in_page.dart.lib.js:701:20)
at ink_well._InkResponseState.new.[_handleTap] (http://localhost:59963/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:59963/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:169:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:59963/packages/flutter/src/gestures/recognizer.dart.lib.js:456:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
    at http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
    at LinkedMap.new.forEach (http://localhost:59963/dart_sdk.js:25048:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
    at pointer_router.PointerRouter.new.route (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:330:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:59963/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:59963/dart_sdk.js:173249:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:59963/dart_sdk.js:155201:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:59963/dart_sdk.js:155815:49)
    at http://localhost:59963/dart_sdk.js:156224:26
    at http://localhost:59963/dart_sdk.js:156183:16
    at http://localhost:59963/dart_sdk.js:155908:11
```

Output of **flutter run --verbose**

```
The details are mentioned in the attached document as I am facing some formatting issue here
```

Output of **flutter analyze**

```
Analyzing time_tracker...                                               
No issues found! (ran in 11.3s)
```

Output of **flutter doctor -v**

```
The details are mentioned in the attached document as I am facing some formatting issue here
```

**Attachment**

[flutter web app error.docx](https://github.com/flutter/flutter/files/6198930/flutter.web.app.error.docx)

Please let me know if any other details are required.

Thank you.

**Comment by iapicca** [comment] 2021-03-24 17:04
@bcagarwal 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment] 2021-03-25 08:34
@bcagarwal 
This seems to be an issue With FirebaseAuth and web, for which you need to open this issue in dedicated repo as mentioned above.
Closing from here as not a Flutter issue.

**Closed by darshankawar** 2021-03-25 08:34 UTC
Labels: in triage

**Comment by bcagarwal** [comment] 2021-03-25 08:41
@darshankawar Rather giving an opportunity to explain the issue further and provide additional details as requested by @iapicca , it is sad to see that the issue has been closed abruptly. It would have been better if the team had at least evaluated the details requested and then taken action.

**Comment by iapicca** [comment] 2021-03-25 08:57
@bcagarwal 
I'm sure the issue will be reopen if proven valid
so far seems to points at an error with your implementation or a bug with firebase
either way not in the scope of this repo

if you believe this is a bug with flutter please provide the info requested [above](https://github.com/flutter/flutter/issues/78980#issuecomment-805999773)

> [...] provide your `flutter doctor -v`, your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by bcagarwal** [comment] 2021-03-25 10:34
@iapicca Thank you so much for your reply. I added this in Firebase github. Will wait for them to come back.

**Comment by darshankawar** [comment] 2021-03-25 11:11
> @darshankawar Rather giving an opportunity to explain the issue further and provide additional details as requested by @iapicca , it is sad to see that the issue has been closed abruptly. It would have been better if the team had at least evaluated the details requested and then taken action.

@bcagarwal Hi, I didn't close the issue abruptly, but only after going through the stacktrace you provided which were pointing to Firebase classes and methods. I apologize if you thought it wasn't the case.

Also, I quickly glanced through the stacktrace again and found a similar SO [link](https://stackoverflow.com/questions/63248596/flutter-web-firebase-typeerror-dart-global-firebase-firestore-is-not-a-function) which might be useful. It doesn't point to `dart.global.firebase.auth`, but to `dart.global.firebase.firestore`, but see if the solutions mentioned in it helps to resolve your issue.

Have a good day !
