### ISSUE TITLE
SliverList is there an error

### ISSUE THREAD

**Issue by Bedroome** [flutter/flutter#65839] opened 2020-09-15 10:11 UTC
In the sliver_list.dart(104) ChildAfter(firstChild) in this code, is it wrong?
```dart
if (childScrollOffset(firstChild) == null) {
    int leadingChildrenWithoutLayoutOffset = 0;
    while (childScrollOffset(earliestUsefulChild) == null) {
      earliestUsefulChild = childAfter(firstChild);
      leadingChildrenWithoutLayoutOffset += 1;
    }

    collectGarbage(leadingChildrenWithoutLayoutOffset, 0);
    assert(firstChild != null);
}
```
```dart
earliestUsefulChild = childAfter(firstChild);
// maybe
earliestUsefulChild = childAfter(earliestUsefulChild);
```

**Comment by pedromassangocode** [comment] 2020-09-15 11:05
Hi @Bedroome 
Not sure, is it causing any problem in your code?

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample with actual vs expected results?
Thank you

**Comment by Bedroome** [comment] 2020-09-15 11:08
Not yet, but I see it here like an endless loop

**Comment by pedromassangocode** [comment] 2020-09-15 11:39
Hi @Bedroome 
If it causes some unexpected behavior in your code please open an issue by filling the issue template.

Closing this as this does not seems to be an issue with Flutter.
Thank you

**Closed by pedromassangocode** 2020-09-15 11:39 UTC
Labels: in triage

**Comment by jerrywell** [comment] 2020-11-02 03:50
this issue is also been fixed in https://github.com/flutter/flutter/issues/66198
