### ISSUE TITLE
Flutter text Align issue

### ISSUE THREAD

**Issue by bryan-ibrahim** [flutter/flutter#17960] opened 2018-05-28 09:55 UTC
I'm using a TextField and have set its alignment to center.
`body: new Container(
         color: Colors.blue,
         child: new Center(
           child: new TextField(
             decoration: new InputDecoration(
               hintText: "Anything goes here"
             ),
             textAlign: TextAlign.center,
           ),
         ),
       ),`

However, I have noticed that after I enter the first character, the cursor blinks at the beginning of the text field, after that the position stays at the center. This is only view-able after inputting the first character.

**Comment by Aniki312** [comment] 2018-05-28 10:43
looks like a dup of #17625 and #17945 ?

**Comment by g123k** [comment] 2018-05-28 11:29
Please switch to the `dev` channel to see if it's fixed.

**Comment by Aniki312** [comment] 2018-05-29 09:46
@g123k 

I switch to dev channel and the issue seems not fixed yet.
```
[✓] Flutter (Channel dev, v0.4.5-pre.69, on Mac OS X 10.13.4 17E202, locale zh-Hant-TW)
```

**Comment by jason-simmons** [comment] 2018-06-26 22:19
Duplicate of https://github.com/flutter/flutter/issues/18483

**Closed by jason-simmons** 2018-06-26 22:19 UTC
