### ISSUE TITLE
Some build benchmarks increasing above our predetermined threshold.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#36853] opened 2019-07-24 16:29 UTC
See material_app_win_compile,  build_benchmark_second_debug_millis, and flutter_fallery_android_compile on https://flutter-dashboard.appspot.com/benchmarks.html. We should investigate or consider rebaselining (I'm inclined to suggest rebaselining this time, and monitoring more closely, FWIW).

**Comment by jason-simmons** [comment] 2019-07-24 18:44
The increased time for `flutter_gallery_android__compile` and `flutter build apk` started with https://github.com/flutter/flutter/commit/242a4225a1bfc726360e7d0f26325d5ac4d30891

@blasten

**Comment by franciscojma86** [comment] 2019-07-31 22:00
@blasten have you had a chance to look at this? Seems like material_app_win__compile is the only one still red

**Comment by blasten** [comment] 2019-07-31 22:09
The feature that was causing this regression was disabled on Friday. It looks like something else changed after https://github.com/flutter/flutter/commit/ef146f63bb4bad33b4ff3d0504671ab173f0c1f2 and caused the regression?

**Comment by franciscojma86** [comment] 2019-07-31 22:10
@zanderso

**Comment by zanderso** [comment] 2019-07-31 22:29
https://github.com/flutter/flutter/commit/ef146f63bb4bad33b4ff3d0504671ab173f0c1f2 refactored analytics collection, which should be disabled on bots. Not sure how that could have affected build times by 10s even if it was enabled.

**Comment by franciscojma86** [comment] 2019-08-02 23:50
I just ran basic_material_app__win_compile locally several times, with both https://github.com/flutter/flutter/commit/ef146f63bb4bad33b4ff3d0504671ab173f0c1f2 and https://github.com/flutter/flutter/commit/c469b1fea92dfae21c0d641106220cc4823a16b7 against a green CL, and https://github.com/flutter/flutter/commit/ef146f63bb4bad33b4ff3d0504671ab173f0c1f2 was consistently slower than the others. @zanderso would you be able to take a closer look?

**Comment by franciscojma86** [comment] 2019-08-03 00:02
Actually, I just ran the tests against https://github.com/flutter/flutter/commit/24f483cf25aab43a389a64f15bf9cc1aee130f47 which is the commit previous to https://github.com/flutter/flutter/commit/ef146f63bb4bad33b4ff3d0504671ab173f0c1f2, and turned out to be much slower, even though it's green on the dashboard. @dkwingsmt can you please take a look?

**Comment by dkwingsmt** [comment] 2019-08-03 00:19
@franciscojma86 I'd be glad to help, although I don't really know where to start when my commit is the _previous_ commit of a performance increase.

**Comment by blasten** [comment] 2019-08-03 00:25
If you try to sync to 30eec11, is it still slow? Are you testing on Windows?

**Comment by franciscojma86** [comment] 2019-08-03 00:32
Yeah I'm testing on windows. I'll test with that commit later today.

@dkwingsmt it might be possible that the test recorded on your commit was a lucky green, but actually introduced the regression. Maybe run some local tests to verify?

**Comment by franciscojma86** [comment] 2019-08-05 16:22
@blasten I just tested  with https://github.com/flutter/flutter/commit/30eec11e7ddcdd44324cbe0cdfd719c0f7b33594 and it is also slow. It's actually the slowest I've tested. Do you think it might be the culprit?

**Comment by zanderso** [comment] 2019-08-05 16:37
https://github.com/flutter/flutter/commit/30eec11e7ddcdd44324cbe0cdfd719c0f7b33594 was a revert, so it is probably not the culprit here. https://github.com/flutter/flutter/commit/24f483cf25aab43a389a64f15bf9cc1aee130f47 seems like the most relevant commit. Re-assigning to @dkwingsmt

**Comment by jonahwilliams** [comment] 2019-08-05 19:43
All of these benchmarks have pretty clear bimodal behavior. This is a known issue with our devicelab configuration and shouldn't be a TODAY issue

**Comment by dkwingsmt** [comment] 2019-08-05 19:54
Sorry I've never dealt with compile time before. What is the suggested approach of investigation here?

**Comment by dkwingsmt** [comment] 2019-11-15 00:23
It seems to me that these benchmarks are green, either they were janky or they have been rebaselined. Therefore I'm closing it.

**Closed by dkwingsmt** 2019-11-15 00:23 UTC
Labels: a: build, severe: performance, tool
