### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by helinyu** [flutter/flutter#103120] opened 2022-05-05 09:32 UTC
## Command
```
flutter run -d chrome --web-port 52539
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.793, on macOS 12.3.1 21E258 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.13.0-0.0.pre.793 at /Users/xiaoniu/sofeware/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8fc22a7df2 (7 天前), 2022-04-28 02:44:04 -0400
    • Engine revision 67940eb620
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xiaoniu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/xiaoniu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5464c5bac742001448fe4fc0597be939379f88ea

**Comment by danagbemava-nc** [comment] 2022-05-05 10:19
Hi @helinyu, it would appear that the error message is missing from your post, can you provide it? 

Possible duplicate of https://github.com/flutter/flutter/issues/79748

**Closed** 2022-05-26 11:10 UTC
Labels: waiting for customer response, in triage
