### ISSUE TITLE
[webview_flutter] V4.0 crashing web apps emloying iframes - unable to create enough overlay surfaces

### ISSUE THREAD

**Issue by pavel604** [flutter/flutter#120413] opened 2023-02-10 00:20 UTC
This is a weird one: Either `webview_flutter` V4.0.x or its dependencies are causing rendering issues on web with the following errors:

```      
Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once. You may experience incorrect rendering.
```

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/canvaskit/embedded_views.dart:411:12
_context.pictureRecorders.length == _overlays.length
is not true


When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/canvaskit/embedded_views.dart 411:58                           submitFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/canvaskit/rasterizer.dart 36:33                                draw
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/canvaskit/renderer.dart 349:16                                 renderScene
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/platform_dispatcher.dart 645:14                                render
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/ui/window.dart 107:50                                                         render
packages/flutter/src/rendering/view.dart 240:15                                                                                compositeFrame
packages/flutter/src/rendering/binding.dart 520:18                                                                             drawFrame
packages/flutter/src/widgets/binding.dart 865:13                                                                               drawFrame
packages/flutter/src/rendering/binding.dart 381:5                                                                              [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1289:15                                                                            [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1218:9                                                                             handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1076:5                                                                             [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/platform_dispatcher.dart 1168:13                               invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/platform_dispatcher.dart 218:5                                 invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/initialization.dart 190:45                                     <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
════════════════════════════════════════════════════════════════════════════════
```

This problem is persistent between Flutter V3.0 and V3.7 , Windows and Mac, Chrome and Edge (didn't try other browsers).

**The `webview_flutter` V3.0.4 does not cause this error, only V4.0 does, and only on Web (iOS and Android work perfectly fine with both V3.0.4 and V4.0)**.

What also is funny, is that I'm not even using `webview_flutter` on the web - I'm using `IFrameElement()`, so I don't understand where this problem is coming from.

Any help troubleshooting is appreciated.

## How to reproduce:

- clone [this repo](https://github.com/13302296C/flutter_rte) and run example in the browser
- toggle between layouts using FAB in bottom right corner
- branch `0.1.0-dev.5.1` is based on webview_flutter V3.0.4 - everything works
- branch `master` is based on V4.0.2 - it fails when you toggle between layouts

Thanks in advance.

**Comment by darshankawar** [comment] 2023-02-10 08:38
@pavel604 
Thanks for the report. I was able to replicate the reported behavior using the repo provided and it only occurs using canvaskit rendering and not with html rendering. That led me to think that the issue may not be specific to webview_flutter because below are couple of similarly reported issues that you can take a look for your further reference:

https://github.com/flutter/flutter/issues/118159
https://github.com/flutter/flutter/issues/104970

These indicates the underlying issue could be canvaskit + web. So once these are fixed, you can run through your scenario once again to see if it resolves the issue at your end too.

Also, in order to properly narrow it down to webview_flutter, would be good to provide only minimal but complete reproducible code sample that doesn't depend on external packages.

**Comment by pavel604** [comment] 2023-02-10 16:35
Ahhhh, :) Thanks, @darshankawar Will be watching.

**Comment by pavel604** [comment] 2023-02-10 17:45
Actualy, I'll keep it open for now, I think...

**Comment by pavel604** [comment] 2023-02-11 01:13
@darshankawar I was able to confirm that this bug has something to do with the `PointerInterceptor` widget. After removing all `PointerInterceptor`s, the rendering issue on Web is now gone (but that's not solving my problem, obviously). Will be looking closer at this.

**Comment by darshankawar** [comment] 2023-02-13 05:23
@pavel604 
I think it is best to follow-up in above linked similar issues because the root-cause seems to be related to `PointerInterceptor`. Once those are fixed, your issue most probably would be fixed as well. I'll close this in favor of the linked issues.

**Closed by darshankawar** 2023-02-13 05:23 UTC
Labels: in triage

**Comment by pavel604** [comment] 2023-02-14 21:28
Just for the record:

Code that was causing the crash:

```dart
return Positioned.fill(
          child: Listener(
              onPointerUp: (e) {
               //
              },
              child: PointerInterceptor(child: const SizedBox.expand())),
        );
```

Workaround:

```dart
Size? patchSize;

// ... 

          var scrollPatchKey = GlobalKey();
          WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
            patchSize = scrollPatchKey.currentContext!
                .findRenderObject()!
                .paintBounds
                .size;
          });
          return Positioned.fill(
            key: scrollPatchKey,
            child: Listener(
                onPointerUp: (e) {
                  //
                },
                child: PointerInterceptor(
                    child: SizedBox.fromSize(size: patchSize))),
          );
```
