### ISSUE TITLE
Color of Japanese text conversion box is invisible

### ISSUE THREAD

**Issue by junka-0** [flutter/flutter#145952] opened 2024-03-29 02:06 UTC
### Steps to reproduce

1. Prepare a flutter project (flutter version 3.7.7)
2. Run iPad simulator (iOS 17.2)
3. Enable `I/O > Keyboard > Connect Hardware Keyboard`
4. Type some Japanese-kana text and try to convert it to Kanji

### Expected results

I would like to know how to customize the text color and background color of the suggestion box.

### Actual results

It is hard for users to see which suggestion is selected because the text color and background color of suggestion box are almost the same.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Demo Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/109844522/3414c0da-2e29-49eb-ba12-d540d6d64147

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-03-29 at 11 00 01](https://github.com/flutter/flutter/assets/109844522/07408588-8e08-4a3a-a5b9-e8d4ddb6fbb8)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 14.3 23D56 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment] 2024-03-29 02:57
> [✓] Flutter (Channel stable, 3.7.7, on macOS 14.3 23D56 darwin-arm64, locale ja-JP)

I believe this is fixed in a newer version of Flutter. Could you check if this works on the latest stable?

**Comment by LongCatIsLooong** [comment] 2024-03-29 02:59
> I would like to know how to customize the text color and background color of the suggestion box.

Is this a feature request, or you would like to use the default text color (instead of the white color that made the candidate text invisible) for the currently selected IME candidate?

**Comment by junka-0** [comment] 2024-03-29 04:00
@LongCatIsLooong 

> I believe this is fixed in a newer version of Flutter. Could you check if this works on the latest stable?

I confirmed that it works fine on new version of flutter. Thank you 🙇 

> Is this a feature request, or you would like to use the default text color (instead of the white color that made the candidate text invisible) for the currently selected IME candidate?

It is not a request. 
But if there is a way other than upgrading Flutter version, I would like to know it.

**Comment by LongCatIsLooong** [comment] 2024-03-29 04:13
Ah I thought you wanted to change the candidate text to use a custom color.  Closing as a duplicate of https://github.com/flutter/flutter/issues/132548

**Closed by LongCatIsLooong** 2024-03-29 04:13 UTC
