### ISSUE TITLE
[video_player] Does not play audio-only files on iOS

### ISSUE THREAD

**Issue by rgb1380** [flutter/flutter#90429] opened 2021-09-21 02:18 UTC
The audio-only files do not play with the plug-in in iOS. I have tested this with m4a, mp3 and wav file formats using these files:

[mp3 file](https://firebasestorage.googleapis.com/v0/b/classnika-dev.appspot.com/o/mov_bbb.mp3?alt=media&token=708099cb-a232-411a-a448-2dfe480d27c7)
[m4a file](https://firebasestorage.googleapis.com/v0/b/classnika-dev.appspot.com/o/mov_bbb.m4a?alt=media&token=45cd0165-3fa3-429b-8d6e-aa9d8de0ba4c)
[wav file](https://firebasestorage.googleapis.com/v0/b/classnika-dev.appspot.com/o/mov_bbb.wav?alt=media&token=5bbbe04c-3b22-4070-9782-fe9c0b9041b5)

These files play fine on Android and in Web.

I have simply used the example that comes with the plug-in to replicate the issue. Simply replace 
``` dart
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      closedCaptionFile: _loadCaptions(),
      videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
    );
```
with 
``` dart
    _controller = VideoPlayerController.network(<url_of_any_of_the_above_files>);
```

The controller's initialize() method does not complete and does not return any error. The issue can be replicated on the iOS simulator (iOS 14.5) and a physical device (iOS 14.7).

**Comment by danagbemava-nc** [comment] 2021-09-21 07:18
Hi @rgb1380,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by rgb1380** [comment] 2021-09-21 08:20
@danagbemava-nc 

The min reproducible code sample is the plug-in's own example. Please use any of the files I have provided in the original post to check this out. You should be able to quickly verify whether you can reproduce the problem before trying to look at possible environmental issues.

Nothing conspicuous about flutter doctor log except that I have not upgraded to the latest version yet.

✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/ramtin/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ramtin/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86    • Android 9 (API 28) (emulator)
    • Anahita’s iPad (mobile)            • 9e1b263539ddbb60981f604445a0b1df8ab6641e • ios            • iOS 14.7.1
    • iPhone 12 Pro Max (mobile)         • 5505DBD6-C21D-4768-BE89-49224883D6AA     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                       • chrome                                   • web-javascript • Google Chrome 93.0.4577.82
    ! Error: Anahita’s iPad is busy: Copying cache files from device. Xcode will continue when Anahita’s iPad is finished. (code -10)

• No issues found!
ramtin@MBP-2100 functions % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/ramtin/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ramtin/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)         • 5505DBD6-C21D-4768-BE89-49224883D6AA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!

**Comment by danagbemava-nc** [comment] 2021-09-21 10:07
Hi @rgb1380, the plugin is working as intended. 

It is not designed to support `audio` files although it does work for android. 

Kindly see this comment https://github.com/flutter/flutter/issues/38480#issuecomment-570458759.

Closing as this is the intended behaviour. 

Thank you.

**Closed** 2021-09-21 10:07 UTC
Labels: in triage

**Comment by rgb1380** [comment] 2021-09-22 00:48
This is not working as 'intended' if you believe the documentation. Under supported formats the documentation says: 
'On iOS, the backing player is AVPlayer. The supported formats vary depending on the version of iOS, AVURLAsset class has audiovisualTypes that you can query for supported av formats.'

Audio formats do form part of the list suggested by the documentation.

May I suggest two alternatives?
1. Support audio formats as per documentation (this is the desirable outcome). The underlying player supports audio on iOS. Supporting audio in iOS homogenises the behaviour of the plug-in that works with audio formats on Android and Web.
2.  Or update the documentation: make it clear that the plug-in does not support audio formats on iOS (and will not?). Make sure that the initialize() method terminates gracefully with an error for unsupported media. Currently, on iOS initialize() does not complete nor throws an error.

Also since we are on the topic of initialize() not returning gracefully, can you check why video_player is unable to initialize() this video? It does not complete the initialize() method and it does not return an error either, which suggests to me there is a bigger problem with error handling. 

[MP4 video with audio does not initialise](https://filesamples.com/samples/video/mp4/sample_1280x720_surfing_with_audio.mp4)

**Comment by danagbemava-nc** [comment] 2021-09-22 06:20
> Or update the documentation: make it clear that the plug-in does not support audio formats 

There is already an issue requesting that, it just hasn't been done yet. Kindly see this issue https://github.com/flutter/flutter/issues/75636

You can comment under it so that it gets some more attention.

> Also since we are on the topic of initialize() not returning gracefully, can you check why video_player is unable to initialize() this video? It does not complete the initialize() method and it does not return an error either, which suggests to me there is a bigger problem with error handling.

This is a different issue than `[video_player]  Does not play audio-only files on iOS`, kindly file a new issue to track that and feel free to tag me in it. 

Thank you
