### ISSUE TITLE
StreamBuilder passing wrong data to list sometimes causing brief error

### ISSUE THREAD

**Issue by pkitatta** [flutter/flutter#49279] opened 2020-01-22 07:32 UTC
This is my code

Why does the error `Another exception was thrown: FormatException: Invalid number (at character 1)` occur on my screen for a few microseconds before all is back to normal. Sometimes it doesn't even occur. Below is my StreamBuilder function:

```
_delivered() {
    print('In the delivered function:${resId},${customerId}, ');
    return StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance
            .collection('restaurants')
            .document(resId)
            .collection('customers')
            .document(customer)
            .collection('orders')
            .where('deliveryTime', isGreaterThan: '')
            .snapshots(),
        builder: (context, snapshot) {
          print('Does snapshop have data? ${snapshot.hasData}');
          if (!snapshot.hasData) return Container();

          List deliveredListFromServer = snapshot.data.documents;
          return Expanded(
            child: ListView(
              shrinkWrap: true,
              children: deliveredListFromServer.map((item) {
                print('document id: ${item.documentID}');
                return InkWell(
                  child: SizedBox(
                    height: 50,
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        SizedBox(
                          width: 80,
                          child: Text(
                            item['orderBy']['username'],
                            textAlign: TextAlign.center,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                        ),
                        SizedBox(
                          width: 5,
                        ),
                        Expanded(
                          child: ListView(
                            scrollDirection: Axis.horizontal,
                            children: item['order'].map<Widget>((item) {
                              return SizedBox(
                                width: 80,
                                child: Align(
                                  alignment: Alignment.centerLeft,
                                  child: Text(
                                    '${item['qty']} ${item['drinkName']}',
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                              );
                            }).toList(),
                          ), //
                        ),
                        SizedBox(
                          width: 5,
                        ),
                        SizedBox(
                          width: 60,
                          child: Text(DateFormat('h:mm a').format(
                              DateTime.fromMillisecondsSinceEpoch(
                                  int.parse(item['deliveryTime'])))),
                        )
                      ],
                    ),
                  ),
                  onTap: () {
                    _deliveredDetail(item);
                  },
                );
              }).toList(),
            ),
          );
        });
  }
```

This is my console:

```
I/flutter (11506): In the delivered function:XufIsxA8a24lLhO6gTr1,zMrQmcoQwci9bVVRo6tx, 
I/flutter (11506): Does snapshop have data? true
I/flutter (11506): document id: 1579534059562
I/flutter (11506): document id: 1579595374166
I/flutter (11506): Another exception was thrown: FormatException: Invalid number (at character 1)
I/flutter (11506): Does snapshop have data? true
I/flutter (11506): document id: 1579534059562
```

From the console, I don't event understand why it's bringing `document id: 1579595374166` from the database. Only `document id: 1579534059562` has a deliveryTime set. The database has 6 records, only one has a deliveryTime set. Others are empty `""` strings.

So after a few milliseconds everything works as expected i.e. the proper UI with only one item for the database showing on the screen. It looks like everything is back to normal the second time the stream returns only one document. In fact the only time it doesn't bring the red screen is when the console looks like this:

```
I/flutter (11506): In the delivered function:XufIsxA8a24lLhO6gTr1,zMrQmcoQwci9bVVRo6tx, 
I/flutter (11506): Does snapshop have data? false
I/flutter (11506): Does snapshop have data? true
I/flutter (11506): document id: 1579534059562
```

Which also means the streamBuilder is passing incorrect data to the list (and probable source of error). Why is the query returning the wrong results sometimes?!

Full error:
```
I/flutter (11506): In the delivered function:XufIsxA8a24lLhO6gTr1,zMrQmcoQwci9bVVRo6tx, 
I/flutter (11506): Does snapshop have data? true
I/flutter (11506): Does snapshop have error? false
I/flutter (11506): document id: 1579534059562
I/flutter (11506): document id: 1579595374166
I/flutter (11506): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11506): The following FormatException was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
I/flutter (11506): _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#f2dda):
I/flutter (11506): Invalid number (at character 1)
I/flutter (11506): 
I/flutter (11506): ^
I/flutter (11506): 
I/flutter (11506): The relevant error-causing widget was:
I/flutter (11506):   StreamBuilder<QuerySnapshot>
I/flutter (11506):   file:///C:/Users/Paul/AndroidStudioProjects/plotavenue_dev/lib/pages/hangouts/bar-detail.dart:1216:12
I/flutter (11506): 
I/flutter (11506): When the exception was thrown, this was the stack:
I/flutter (11506): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:7)
I/flutter (11506): #1      int.parse (dart:core-patch/integers_patch.dart:55:14)
I/flutter (11506): #2      _BarState._delivered.<anonymous closure>.<anonymous closure> (package:plotavenue_dev/pages/hangouts/bar-detail.dart:1279:39)
I/flutter (11506): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
I/flutter (11506): #4      ListIterable.toList (dart:_internal/iterable.dart:221:19)
I/flutter (11506): #5      _BarState._delivered.<anonymous closure> (package:plotavenue_dev/pages/hangouts/bar-detail.dart:1288:18)
I/flutter (11506): #6      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (11506): #7      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (11506): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (11506): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (11506): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #11     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (11506): #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (11506): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #34     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #44     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1288:36)
I/flutter (11506): #45     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1220:34)
I/flutter (11506): #46     Iterable.forEach (dart:core/iterable.dart:279:30)
I/flutter (11506): #47     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1246:24)
I/flutter (11506): #48     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1191:7)
I/flutter (11506): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #50     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (11506): #51     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (11506): #52     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter (11506): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #106    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #110    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #114    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #118    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #120    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (11506): #121    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (11506): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #125    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #139    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11506): Does snapshop have data? true
I/flutter (11506): Does snapshop have error? false
I/flutter (11506): document id: 1579534059562
I/flutter (11506): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11506): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #145    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #149    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #153    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #157    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11506): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #161    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11506): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11506): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11506): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11506): #165    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (11506): #166    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (11506): #167    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (11506): #168    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (11506): #169    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (11506): #170    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (11506): #174    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (11506): #175    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (11506): (elided 3 frames from package dart:async)
I/flutter (11506): 
I/flutter (11506): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11506): Another exception was thrown: A RenderFlex overflowed by 99750 pixels on the bottom.
```

**Comment by markusaksli-nc** [comment] 2020-09-25 10:15
Hi @pkitatta
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).

Closing, as this isn't an issue with Flutter itself. 
If you disagree, please write in the comments and provide a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by markusaksli-nc** 2020-09-25 10:15 UTC
Labels: framework
