### ISSUE TITLE
Shared preferences error when opening app through another Activity

### ISSUE THREAD

**Issue by gcostaapps** [flutter/flutter#99638] opened 2022-03-06 17:20 UTC
Hi, I'm having problem when trying to start my app through another Activity.

I have a broadcast receiver that fires my secondary activity  (not the MainActivity), that secondary activity has a initialization of shared preferences before calling runApp(), when I try to get the instance of shared preferences i got this error:

```
E/flutter ( 9420): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 9420):
```

I have this problem in debug mode (also in profile and release). All issues related to that error that I found was related only to profile or release mode.

Using  `shared_preferences: ^2.0.13`

## Steps to Reproduce

<details>
<summary>SecondaryActivity</summary>

```
class SecondaryActivity : FlutterActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun getDartEntrypointFunctionName(): String = "secondaryMain"

    override fun getDartEntrypointLibraryUri(): String = "package:apppackage/main.dart"

}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +19 ms] W/ActivityThread(10075): handleWindowVisibility: no activity for token android.os.BinderProxy@64a33a6
[  +45 ms] D/eglCodecCommon(10075): setVertexArrayObject: set vao to 0 (0) 0 0
[        ] D/EGL_emulation(10075): eglCreateContext: 0xe19e7980: maj 3 min 0 rcv 3
[  +13 ms] D/eglCodecCommon(10075): setVertexArrayObject: set vao to 0 (0) 0 0
[        ] D/EGL_emulation(10075): eglCreateContext: 0xe19e79e0: maj 3 min 0 rcv 3
[   +4 ms] D/HostConnection(10075): HostConnection::get() New Host Connection established 0xd6444840, tid 10205
[        ] D/HostConnection(10075): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
[        ] D/EGL_emulation(10075): eglMakeCurrent: 0xe19e79e0: ver 3 0 (tinfo 0xd98e8290)
[   +8 ms] D/PathProviderPlugin(10075): Use TaskQueues.
[  +29 ms] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +6 ms] D/TransportRuntime.SQLiteEventStore(10075): Storing event with priority=DEFAULT, name=FIREPERF for destination cct
[   +5 ms] D/TransportRuntime.JobInfoScheduler(10075): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) is already scheduled. Returning...
[  +49 ms] D/HostConnection(10075): HostConnection::get() New Host Connection established 0xb29f9730, tid 10204
[        ] D/HostConnection(10075): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
[   +2 ms] D/EGL_emulation(10075): eglMakeCurrent: 0xe19e7980: ver 3 0 (tinfo 0xd98e8ea0)
[  +22 ms] D/eglCodecCommon(10075): setVertexArrayObject: set vao to 0 (0) 0 0
[   +1 ms] D/EGL_emulation(10075): eglCreateContext: 0xbbaa72a0: maj 3 min 0 rcv 3
[   +1 ms] D/EGL_emulation(10075): eglMakeCurrent: 0xbbaa72a0: ver 3 0 (tinfo 0xd98e8ea0)
[   +3 ms] D/EGL_emulation(10075): eglMakeCurrent: 0xe19e7980: ver 3 0 (tinfo 0xd98e8ea0)
[  +39 ms] D/EGL_emulation(10075): eglMakeCurrent: 0xe19e7980: ver 3 0 (tinfo 0xd98e8ea0)
[  +46 ms] D/EGL_emulation(10075): eglMakeCurrent: 0xe1945480: ver 3 0 (tinfo 0xbb9ab580)
[  +44 ms] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[   +1 ms] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[   +1 ms] W/etracker.mytim(10075): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[ +336 ms] D/FRCPlugin(10075): Sending fetchTimeout: 60
[ +351 ms] I/flutter (10075): localStorage
[  +26 ms] E/flutter (10075): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
[        ] E/flutter (10075):

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [versÃ£o 10.0.19043.1526], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.0)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

**Comment by stuartmorgan** [comment] 2022-03-06 19:07
Duplicate of https://github.com/flutter/flutter/issues/98473

See https://github.com/flutter/flutter/issues/98473#issuecomment-1041895729 for the solution.

**Closed by stuartmorgan** 2022-03-06 19:07 UTC
