### ISSUE TITLE
Flutter project not run after upgrade dart 3.0.0

### ISSUE THREAD

**Issue by Nurullah1995** [flutter/flutter#104485] opened 2022-05-24 06:23 UTC
./../flutter_sdk_2022/flutter/.pub-cache/hosted/pub.dartlang.org/oktoast-3.1.5/lib/src/core/toast.dart:170:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter_sdk_2022/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
../../flutter_sdk_2022/flutter/.pub-cache/hosted/pub.dartlang.org/oktoast-3.1.5/lib/src/widget/container.dart:45:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter_sdk_2022/

**Comment by maheshmnj** [comment] 2022-05-24 08:27
Hi @ibrahimalpha, Thanks for filing the issue. If you look closely at each warning, It seems to point issues in code in third-party libraries.

>../../flutter_sdk_2022/flutter/.pub-cache/hosted/pub.dartlang.org/oktoast-3.1.5/lib/src/widget/container.dart:45:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

For instance this points issue in `oktoast` plugin.

These warnings are reproducible only in flutter 3 due to [clean up in BindingApis](https://github.com/flutter/flutter/pull/89451). 
To get rid of these warnings the plugin authors need to run `dart fix --apply` and publish a new release. However, these are just warnings they should not interrupt the build process. To investigate the compilation failure we would need the complete output of `flutter run -v` (in a text file as the output will be long) along with the output of `flutter doctor -v`

See similar issue for context: https://github.com/flutter/flutter/issues/103561

Closing as duplicate of the above linked issue

**Closed by maheshmnj** 2022-05-24 08:27 UTC
Labels: in triage
