### ISSUE TITLE
[url_launcher_web] Cannot launch url with scheme `tel`

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#60293] opened 2020-06-25 16:54 UTC
Currently there is no way to open a `tel:961234567` url on the web

This is a functionality that has been added to both Android and iOS and is needed because on a mobile device, browsing a website, we may want to open the phone app with the correct phone number

**Comment by ditman** [comment] 2020-06-25 22:02
Duplicate of https://github.com/flutter/flutter/issues/58553 (being worked on Discord, and the PR above!)

**Closed by ditman** 2020-06-25 22:02 UTC
Labels: platform-web

**Comment by ditman** [comment] 2020-06-30 20:07
This feature is now published, on `url_launcher_web 0.1.2`
