### ISSUE TITLE
Not found flutter plugin 

### ISSUE THREAD

**Issue by ThuraMaung** [flutter/flutter#75963] opened 2021-02-13 09:48 UTC
I installed Android Studio from jet brain toolbox . After that , I install flutter from Stable channel . When I run flutter doctor command in command prompt, flutter cannot found flutter plugin even after installing plugin in Android Studio.

**[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.6 at C:\Flutter\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\Lenovo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Lenovo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.**

**Comment by iapicca** [comment] 2021-02-13 10:03
duplicate of https://github.com/flutter/flutter/issues/75918

**Comment by elbeicktalat** [comment] 2021-02-13 10:04
I had the same error but when I switching to beta channel all ok.

**Comment by darshankawar** [comment] 2021-02-15 08:13
@elbeicktalat 
Seems your issue is resolved. For further reference, check out [this](https://github.com/flutter/flutter/issues/75918#issuecomment-778993808) comment.
Closing as resolved.

**Closed by darshankawar** 2021-02-15 08:13 UTC
