### ISSUE TITLE
canvas screen is blurred red

### ISSUE THREAD

**Issue by jameheller98** [flutter/flutter#133652] opened 2023-08-30 10:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Upgrade flutter 3.13.1
Before version not show bug

### Expected results

Screen not blurred red

### Actual results

Screen blurred red

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback(
      (_) {
        LoadingOverlay.of(context).show();
        LoadingOverlay.of(context).hide();
      },
    );

    return Scaffold(
        backgroundColor: Colors.yellow,
        body: SizedBox(
          height: double.infinity,
          width: double.infinity,
          child: Stack(
            alignment: Alignment.center,
            children: [
              Container(
                height: 300,
                width: 500,
                color: Colors.red,
              ),
              RepaintBoundary(
                child: CustomPaint(
                  isComplex: true,
                  willChange: false,
                  foregroundPainter: Painter(),
                  child: Container(
                    height: 200,
                    width: 200,
                    color: Colors.transparent,
                  ),
                ),
              ),
            ],
          ),
        ));
  }
}

class Painter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paintFill = Paint()
      ..style = PaintingStyle.fill
      ..isAntiAlias = false
      ..shader = null
      ..color = Colors.white;

    canvas.drawPath(
      Path()..addRect(Rect.largest),
      paintFill,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}

double getHeightDevice() {
  final viewDevice = WidgetsBinding.instance.platformDispatcher.views.first;
  final devicePixelRatio = viewDevice.devicePixelRatio;
  final physicalHeight = viewDevice.physicalSize.height;

  return physicalHeight / devicePixelRatio;
}

class LoadingOverlay {
  static late BuildContext context;
  static OverlayEntry? overlayEntry;
  static Timer? _timerCountDown;
  static Timer? _timerLoadingOverlay;
  final Duration defaultLoadingDuration;

  LoadingOverlay({
    required this.defaultLoadingDuration,
  });

  static LoadingOverlay of(
    BuildContext contextWidget, {
    Duration duration = const Duration(seconds: 3),
  }) {
    context = contextWidget;

    return LoadingOverlay(defaultLoadingDuration: duration);
  }

  void show({hasBarrier = true}) {
    hide();

    assert(overlayEntry == null);

    _timerCountDown = Timer.periodic(const Duration(milliseconds: 1), (timer) {
      if (timer.tick >= defaultLoadingDuration.inMilliseconds) {
        _timerCountDown?.cancel();
      }
    });

    overlayEntry = OverlayEntry(
      builder: (context) {
        return Scaffold(
          backgroundColor: Colors.transparent,
          body: Stack(
            children: [
              if (hasBarrier)
                const ModalBarrier(
                  dismissible: false,
                  color: Color.fromRGBO(0, 0, 0, 0.7),
                ),
              Center(
                child: SizedBox(
                  height: getHeightDevice(),
                  child: Lottie.asset('assets/loading.json'),
                ),
              ),
            ],
          ),
        );
      },
    );

    Overlay.of(context).insert(overlayEntry!);
  }

  void hide({void Function()? callback}) {
    if (_timerCountDown != null && _timerCountDown!.isActive) {
      _timerLoadingOverlay = Timer(defaultLoadingDuration, () {
        overlayEntry?.remove();
        overlayEntry = null;

        if (callback != null) {
          callback();
        }

        _timerLoadingOverlay?.cancel();
      });

      _timerCountDown!.cancel();
    } else {
      overlayEntry?.remove();
      overlayEntry = null;

      if (callback != null) {
        callback();
      }
    }
  }

  void trigger() {
    show();
    hide();
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/32564261/d8ac9833-87c7-4b9d-8188-356fe5fdd08d

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.2 22D49 darwin-arm64, locale
    en-VN)
    • Flutter version 3.13.1 on channel stable at
      /Users/mac/Desktop/Flutter/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (7 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 4B3B4EC2-6722-4FFF-8A41-3E1AD7CC813E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-08-30 12:02
Hi @jameheller98. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by jameheller98** [comment] 2023-08-30 16:56
I have updated code in Code example, you can check and run. Its will produce bug.

**Comment by dam-ease** [comment] 2023-08-31 08:02
Hi @jameheller98. Thanks for your response. I'm unable to reproduce this on the latest versions of flutter. From the video attached, this seems to be a familiar issue with impeller which has been fixed. Can you upgrade to the latest flutter versions `3.13.2` to see if this issue reproduces. Also, try running without impeller and kindly share your results.


https://github.com/flutter/flutter/assets/53122008/1414568b-40ac-4703-b9f4-b75fefaac457

**Comment by dam-ease** [comment] 2023-09-04 12:32
Thanks for confirming. I'd be closing this as fixed.

**Closed by dam-ease** 2023-09-04 12:32 UTC
Labels: in triage
