### ISSUE TITLE
Flutter crash on production app: java.lang.RuntimeException Caused by: java.lang.ClassCastException

### ISSUE THREAD

**Issue by yushanapp** [flutter/flutter#51026] opened 2020-02-19 09:00 UTC
Google play crash report shows that many users crash in use, but I can't reproduce it;
The complete crash log is as follows：

```
java.lang.RuntimeException: 

  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2814)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2892)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1613)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:176)
  at android.app.ActivityThread.main (ActivityThread.java:6635)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)
Caused by: java.lang.ClassCastException: 
  at io.flutter.embedding.android.FlutterSplashView.onRestoreInstanceState (FlutterSplashView.java:103)
  at android.view.View.dispatchRestoreInstanceState (View.java:17732)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3747)
  at android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3753)
  at android.view.View.restoreHierarchyState (View.java:17710)
  at com.android.internal.policy.PhoneWindow.restoreHierarchyState (PhoneWindow.java:2142)
  at android.app.Activity.onRestoreInstanceState (Activity.java:1129)
  at android.app.Activity.performRestoreInstanceState (Activity.java:1084)
  at android.app.Instrumentation.callActivityOnRestoreInstanceState (Instrumentation.java:1261)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2787)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2892)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1613)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:176)
  at android.app.ActivityThread.main (ActivityThread.java:6635)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)
```

flutter doctor is  as fllow:

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14 18A391, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)
```

**Comment by tp** [comment] 2020-03-04 21:00
@yushanapp Probably a duplicate of #47635

**Comment by chinmaygarde** [comment] 2020-06-13 00:38
It looks like [this cast of the state parcelable](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/embedding/android/FlutterSplashView.java#L101) needs to be checked. Should be an easy fix. cc @xster @gaaclarke

**Comment by darshankawar** [comment] 2020-12-04 10:04
@yushanapp 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, can you provide a reproducible code sample for non-prod environment ?
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-30 10:47
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:47 UTC
Labels: P4, e: embedder, easy fix, engine, platform-android, severe: crash, waiting for customer response
