### ISSUE TITLE
List view items hidden behing sliver app bar

### ISSUE THREAD

**Issue by Kailash-777** [flutter/flutter#58139] opened 2020-05-28 04:08 UTC
List view items are getting hidden behind Sliver app bar when in minimised position. I have attached my main.dart file in text as well as a file. 

`import 'package:flutter/material.dart';

void main() => runApp(
  new MaterialApp(
    home: FloatingBar()
  )
);

class FloatingBar extends StatefulWidget {
  @override
  _FloatingBarState createState() => _FloatingBarState();
}

class _FloatingBarState extends State<FloatingBar> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 150,
              pinned: true,
              floating: false,
              snap: false,
              forceElevated: true,
              flexibleSpace: FlexibleSpaceBar(
                centerTitle: true,
                title: Text("Items"),
              ),
              iconTheme: IconThemeData(
                  color: Colors.white
              ),
            )
          ];
        },
        body: ListView.builder(itemCount: 10,itemBuilder: (BuildContext context, int index) {
          return Card(
            color: Colors.white,
            child: ListTile(
              title: Text("Movie", style: TextStyle(color: Colors.black),),
              subtitle: Text("This is a movie"),
            ),
          );
        })
        ,
      ),
    );
  }
}
`

[main.zip](https://github.com/flutter/flutter/files/4693168/main.zip)

**Comment by VladyslavBondarenko** [comment] 2020-05-28 11:25
Hi @Kailash-777 
with provided code sample I can't see an issue. Could you provide your `flutter doctor -v` and screenshots/screen recording of it together with description of expected result?

**Comment by Kailash-777** [comment] 2020-05-28 12:07
If you scroll up, the items get hidden behind the app bar.

**Comment by Kailash-777** [comment] 2020-05-28 12:16
As you can see from the screenshots uploaded, the item 0 gets hidden behind the appbar.

![Screenshot (31)](https://user-images.githubusercontent.com/34036909/83140081-16f3a580-a10b-11ea-9703-fa3fbf176bb4.png)
![Screenshot (32)](https://user-images.githubusercontent.com/34036909/83140085-1bb85980-a10b-11ea-944b-a09982cea1cd.png)
![Screenshot (33)](https://user-images.githubusercontent.com/34036909/83140094-1f4be080-a10b-11ea-9eb8-0f909639adff.png)

**Comment by VladyslavBondarenko** [comment] 2020-05-28 12:45
This is intended behaviour https://api.flutter.dev/flutter/material/SliverAppBar-class.html,
what would you expect?

**Comment by VladyslavBondarenko** [comment] 2020-05-28 12:55
Closing as duplicate of https://github.com/flutter/flutter/issues/58164

**Closed by VladyslavBondarenko** 2020-05-28 12:55 UTC
Labels: in triage, waiting for customer response
