### ISSUE TITLE
Automatically Create indicies as required for Firestore

### ISSUE THREAD

**Issue by jamiethain** [flutter/flutter#55517] opened 2020-04-24 00:46 UTC
When working in Debug mode of a flutter application you will often get a message... 

"Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: https://<biglongstringofcharacters>

There should be a "warning" and the index should create itself. 

In Data driven applications your never sure of all the compound indicies required to complete the application. 

We have dynamic filtering that is dynamically read from a dynamic database.  And there can be any number of combinations of indicies required.

**Comment by iapicca** [comment] 2020-04-24 07:54
Hi @jamiethain 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-24 07:54 UTC

**Comment by jamiethain** [comment] 2020-04-24 15:36
Francesco,

This is true for all languages, that Firestore when it needs an index,
requires manual input.

https://stackoverflow.com/questions/50207339/cloud-firestore-failed-precondition-the-query-requires-an-index

https://firebase.google.com/docs/firestore/query-data/indexing

Firestore needs to have "automatic compound index creation"

Jamie
