### ISSUE TITLE
Gallery: App Bar shadows disappear when transitioning between home and components

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5502] opened 2016-08-19 17:22 UTC
Open Gallery. Scroll up to collapse the app bar. Tap a component (e.g. Cards).

Notice the shadow on the app bar disappears, the transition into cards completes, and then the shadow reappears.

Tested on a Nexus 5 and 5X.

**Comment by sethladd** [comment] 2016-08-19 17:22
I can make a movie if you like. Please let me know if you don't see this happening.

**Comment by eseidelGoogle** [comment] 2016-08-19 17:25
iirc @abarth told me this is the same root cause as https://github.com/flutter/flutter/issues/5231 which we just need to reduce for Skia.

**Comment by chinmaygarde** [comment] 2016-08-22 18:40
Duplicate of https://github.com/flutter/flutter/issues/5231. Raster cache not accounting for the shadow.

**Closed by chinmaygarde** 2016-08-22 18:40 UTC
Labels: customer: gallery, ⚠ bug
