### ISSUE TITLE
[Web] Some `HtmlElementView` disappears in the list if the parent container has some color

### ISSUE THREAD

**Issue by gowtham-xseed** [flutter/flutter#114060] opened 2022-10-26 08:46 UTC
## Steps to Reproduce

1. Execute `flutter run -d chrome --no-sound-null-safety` on the code sample 
2. You can see that 15 rows on the screen
3. Click on the `Toggle Color` button to change the container background color
4. You can see only 7 rows on the screen, Remaining items are hidden behind the container. [PFA]

**Expected results:** 
HtmlElementView  always displays

**Actual results:** 
Some HtmlElementView disappears if it is more than 8 HtmlElementView and the container has some color. 

<details>
<summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:universal_html/html.dart';
import 'package:universal_html/js.dart' as js;
import 'package:universal_ui/universal_ui.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyWidget(),
    );
  }
}

class MyWidget extends StatefulWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  Color bgColor = Colors.transparent;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          const SizedBox(height: 20),
          OutlinedButton(
            onPressed: () {
              setState(() {
                bgColor = bgColor == Colors.transparent
                    ? Colors.yellow
                    : Colors.transparent;
              });
            },
            child: const Text('Toggle Color'),
          ),
          const SizedBox(height: 20),
          for (int i = 1; i <= 15; i++) ...{
            Container(
              color:
                  bgColor, // If we remove color for this container, all the HtmlElementView are visible.
              child: HtmlView(i.toString()),
            ),
          },
          Container(
            color:
                bgColor, // If we remove color for this container, all the HtmlElementView are visible.
            child: HtmlView('End...'),
          ),
        ],
      ),
    );
  }
}

class HtmlView extends StatelessWidget {
  const HtmlView(this.text, {Key? key}) : super(key: key);
  final String text;

  @override
  Widget build(BuildContext context) {
    final String elementId = generateRandomString(5);

    ui.platformViewRegistry.registerViewFactory(
      elementId,
      (int viewId) => DivElement()
        ..id = elementId
        ..innerText = text,
    );

    return Container(
      child: SizedBox(
        height: 20,
        width: 15,
        child: HtmlElementView(
          viewType: elementId,
        ),
      ),
    );
  }
}

String generateRandomString(int length) {
  const _chars =
      'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  Random _rnd = Random();

  return String.fromCharCodes(Iterable.generate(
      length, (_) => _chars.codeUnitAt(_rnd.nextInt(_chars.length))));
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/gowtham/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/gowtham/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/goutham/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/54016506/197978031-1a865cca-5dec-4f98-9944-7b38faeed128.mov

**Comment by exaby73** [comment] 2022-10-26 18:28
Hello @gowtham-xseed. I can reproduce this issue in stable but it seems to be fixed in master. Please upgrade to the master channel to get the fix. Since it's already fixed, I am closing this issue. Thank you.

**Closed** 2022-10-26 18:28 UTC
Labels: in triage, r: fixed
