### ISSUE TITLE
Hot reload always back to initialRoute

### ISSUE THREAD

**Issue by BangPei** [flutter/flutter#83328] opened 2021-05-25 08:24 UTC
Hi, i just upgrade flutter from 2.0.5 to 2.2.0 (stable channel).
i'm still using Navigator.pushNamed for navigating the route.
when i press CTRL+S (save) my application always back to initial route, it happen since i upgrade flutter.
any suggestion how to fix this? 

i'm using VS Code for my code editor.

**Comment by TahaTesser** [comment] 2021-05-25 13:42
Hi  @BangPei 
Just tied official [sample](https://flutter.dev/docs/cookbook/navigation/named-routes#interactive-example) for `Navigate with named routes` . Also tried on Windows

No issue when debugging on the stable channel in VS Code



https://user-images.githubusercontent.com/48603081/119507955-f9860580-bd77-11eb-963b-3011980a8c10.mov


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by BangPei** [comment] 2021-05-26 01:48
> Hi @BangPei
> Just tied official [sample](https://flutter.dev/docs/cookbook/navigation/named-routes#interactive-example) for `Navigate with named routes` . Also tried on Windows
> 
> No issue when debugging on the stable channel in VS Code
> 
>  Screen.Recording.2021-05-25.at.4.39.41.PM.mov 
> flutter doctor -v

hi @TahaTesser thanks for your response, have you tried on web app? after hot restart the url lose and back to initialroute.

**Comment by BangPei** [comment] 2021-05-26 01:50
> is this related to #79241?

hi @ConcenTech yes this is what i mean.
thanks for your help, i'm going to preview on this.

**Comment by TahaTesser** [comment] 2021-05-26 06:37
Hi @BangPei 
Closing as duplicate of https://github.com/flutter/flutter/issues/79241

**Closed by TahaTesser** 2021-05-26 06:37 UTC
Labels: in triage
