### ISSUE TITLE
dyld: Library not loaded:  When using nested target in xcode, and same is working fine with main target runner

### ISSUE THREAD

**Issue by krsolutions** [flutter/flutter#29932] opened 2019-03-25 19:10 UTC
dyld: Library not loaded: @rpath/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout
  Referenced from: /Users/reddy/Library/Developer/CoreSimulator/Devices/5013BB7B-FF61-4F04-BDF8-AE7E6511327E/data/Containers/Bundle/Application/21228428-8C32-4EF7-960D-3D68215679CD/gadikota_srikanth_reddy.app/gadikota_srikanth_reddy
  Reason: image not found
(lldb)

**Comment by escamoteur** [comment] 2019-09-24 17:07
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

If so please explain more in detail what you are trying to do

Thanks a lot

**Comment by Kiruel** [comment] 2019-10-05 12:32
This bug still happen:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.12, on Mac OS X 10.14.6 18G95, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (4 available)

• No issues found!
```
Trying to install the app on iOS device like this:
`flutter build ios`
then `flutter install`
and this is the error:

```
[  +17 ms] executing: [flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0e605cc4dd83137f785769dea5e8ae7da1afb361
[        ] executing: [flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.12-0-g0e605cc4d
[   +5 ms] executing: [flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +16 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[  +88 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.0
           Build version 11A420a
[  +48 ms] executing: /sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /sdk/platform-tools/adb devices -l
[        ] List of devices attached
           LMG710EMbc8d0e2d       device usb:17825792X product:judyln_lao_com model:LM_G710 device:judyln
           transport_id:3
[  +14 ms] executing:
flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +178 ms] /usr/bin/xcrun simctl list --json devices
[ +141 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +25 ms] executing: /usr/bin/plutil -convert json -o -
/ios/Runner/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/ios/Runner/Info.plist
[        ]
{"CFBundleName":"name_project","CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","CFBundleInfoDictionaryVersio
n":"6.0","UIMainStoryboardFile":"Main","CFBundleVersion":"$(CURRENT_PROJECT_VERSION)","UILaunchStoryboardName"
:"LaunchScreen","CFBundleExecutable":"$(EXECUTABLE_NAME)","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrien
tations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandsc
apeRight"],"CFBundleDisplayName":"AtomicDEX","CFBundleLocalizations":["zh_TW","zh","zh_CN","English","fr","de"
],"UIViewControllerBasedStatusBarAppearance":false,"CFBundlePackageType":"APPL","CFBundleSignature":"????","NS
CameraUsageDescription":"Camera permission is required for barcode scanning.","NSFaceIDUsageDescription":"Why
is my app authenticating using face
id?","CFBundleDevelopmentRegion":"en","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait
","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLand
scapeRight"],"CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)"}
[  +15 ms] Installing com.example to iPhone de -...
[   +1 ms] executing:
flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
--list-apps
[  +10 ms] dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from:
             flutter/bin/cache/artifacts/ideviceinstaller/ideviceins
             taller
             Reason: image not found
[   +3 ms] executing:
flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller -i
build/ios/iphoneos/Runner.app
[  +13 ms] dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from:
             flutter/bin/cache/artifacts/ideviceinstaller/ideviceins
             taller
             Reason: image not found
[   +1 ms] Process exited abnormally:
           dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from:

flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
             Reason: image not found
[   +8 ms] "flutter install" took 657ms.
Install failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      InstallCommand.runCommand (package:flutter_tools/src/commands/install.dart:45:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by Kiruel** [comment] 2019-10-05 13:17
And I just notice: with `flutter run` the application running but without logs. I can't see any logs from flutter in the terminal. (only happen on ios). Probably because of the new `Xcode 11.0`.

**Comment by escamoteur** [comment] 2019-10-05 14:53
Am I right that its an iOS 13 phone? There the missin debug output is a known bug.

So this happens if you try a flutter install, not a flutter run, Do I understand this correctly?

Could this be your problem? https://stackoverflow.com/questions/55389080/xcode-10-2-failed-to-run-app-on-simulator-with-ios-10

**Comment by Kiruel** [comment] 2019-10-05 16:57
Exactly an iPhone 13.1.2
Yes `flutter install` I have this error.
If I use `flutter run` it's ok.
I don't think it's related to this issue. https://stackoverflow.com/questions/55389080/xcode-10-2-failed-to-run-app-on-simulator-with-ios-10
Probably flutter missing something on iOS 13 and iPhone device.

**Comment by escamoteur** [comment] 2019-10-05 17:58
Does it only happen on real phones?

**Comment by Kiruel** [comment] 2019-10-05 19:54
Yes.

**Comment by Kiruel** [comment] 2019-10-05 19:54
Tested on simulation iPhone XR and it works.

**Comment by escamoteur** [comment] 2019-10-05 21:13
Do you have the chance to test it with another phone?

**Comment by escamoteur** [comment] 2019-10-05 21:14
Does it also happen with a newly created project?

**Comment by Kiruel** [comment] 2019-10-05 21:29
Yes I just test same error.

**Comment by Nitaaq** [comment] 2019-10-11 08:21
same problem here, multiple iphones tested with the same result

**Comment by jmagman** [comment] 2019-10-23 17:50
Duplicate of https://github.com/flutter/flutter/issues/42877.

**Closed by jmagman** 2019-10-23 17:50 UTC
Labels: severe: crash, tool, ⌺‬ platform-ios
