### ISSUE TITLE
regression in async handling in tests 

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#75155] opened 2021-02-01 18:23 UTC
In the 1.26 rc 17, this test passes:

```dart
// @dart=2.9
import 'dart:async';
import 'package:flutter_test/flutter_test.dart';

Future<void> main() async {
  tearDown(() async {
    await ensureLoaded();
  });

  testWidgets('ensureLoaded', (tester) async {
    await ensureLoaded();
  });
}

Future<void> _theFuture;

Future<void> ensureLoaded() async {
  if (_theFuture != null) {
    return _theFuture;
  }

  Future<void> loadInternal() async {
    await null;
  }

  _theFuture = loadInternal();
  await _theFuture;
}
```

But this test times out:

```dart
// @dart=2.12
import 'dart:async';
import 'package:flutter_test/flutter_test.dart';

Future<void> main() async {
  tearDown(() async {
    await ensureLoaded();
  });

  testWidgets('ensureLoaded', (tester) async {
    await ensureLoaded();
  });
}

Future<void>? _theFuture;

Future<void> ensureLoaded() async {
  if (_theFuture != null) {
    return _theFuture!;
  }

  Future<void> loadInternal() async {
    await null;
  }

  _theFuture = loadInternal();
  await _theFuture;
}
```

A very similar issue is blocking the internal google roll against master.

**Comment by jamesderlin** [comment] 2021-02-01 18:57
On stable (1.22.6 with Dart 2.10.5), just changing:
```dart
  if (_theFuture != null) {
    return _theFuture;
  }
```
to:
```dart
  if (_theFuture != null) {
    return await _theFuture;
  }
```
causes the test to timeout.

**Comment by dnfield** [comment] 2021-02-01 19:01
This was caused by https://github.com/dart-lang/sdk/commit/14032a6209e091dcd755582aa0edfa6a860427da

I'd like to get a repro that doesn't involve flutter_test, and see if this behavior change was fully anticipated by the upstream CFE change. If so, we probably want at least some kind of lint to guard against this, if not we want to fix it upstream.

This is a P0 because it is blocking the flutter roll.

**Comment by dnfield** [comment] 2021-02-01 19:21
```dart
// @dart=2.12
import 'package:test/test.dart';
import 'package:fake_async/fake_async.dart' hide fakeAsync;

Future<void> main() async {
  tearDown(() async {
    await ensureLoaded();
  });

  test('without ft', () async {
    FakeAsync()
      ..run((FakeAsync localFakeAsync) async {
        await ensureLoaded();
      })
      ..flushMicrotasks();
  });
}

Future<void>? _theFuture;

Future<void> ensureLoaded() async {
  if (_theFuture != null) {
    return _theFuture!;
  }

  Future<void> loadInternal() async {
    await null;
  }

  _theFuture = loadInternal();
  await _theFuture;
}
```

fails with just `FakeAsync`. See if I can distill further.

**Comment by dnfield** [comment] 2021-02-01 19:58
Without FakeAsync:

```dart
// @dart=2.12
import 'dart:async';
import 'dart:collection';

import 'package:test/test.dart';

Future<void> main() async {
  tearDown(() async {
    await ensureLoaded();
  });

  test('without ft', () async {
    final Queue<void Function()> microtasks = Queue<void Function()>();
    final Zone zone = Zone.current.fork(
      specification: ZoneSpecification(
        scheduleMicrotask: (_, __, ___, microtask) {
          microtasks.add(microtask);
        },
      ),
    );

    zone.run(() async {
      await ensureLoaded();
    });

    print(microtasks);
    while (microtasks.isNotEmpty) {
      microtasks.removeFirst()();
    }

  });
}

Future<void>? _theFuture;

Future<void> ensureLoaded() async {
  if (_theFuture != null) {
    return _theFuture!;
  }

  Future<void> loadInternal() async {
    await null;
  }

  _theFuture = loadInternal();
  await _theFuture;
}
```

@lrhn Is this expected to fail now?

**Comment by dnfield** [comment] 2021-02-01 20:02
@johnniwinther @eernstg as well

**Comment by zanderso** [comment] 2021-02-01 20:03
Revert on dart-lang/sdk master is here: https://dart-review.googlesource.com/c/sdk/+/181860

**Comment by dnfield** [comment] 2021-02-01 20:05
For  some more context - this pattern comes up in Flutter tests when someone initially awaits a future in a `testWidgets` test, and then later awaits the same future again. The second attempt at listening to the result of the future never completes.

**Comment by pcsosinski** [comment] 2021-02-01 21:02
cc @franklinyow

**Comment by a-siva** [comment] 2021-02-01 23:46
https://dart-review.googlesource.com/c/sdk/+/181860 has landed a revert on Dart master.

**Comment by pcsosinski** [comment] 2021-02-02 04:00
removing cp label here as it's covered on the Dart side

**Comment by lrhn** [comment] 2021-02-02 11:18
I don't actually know how `test` zones work, but I'm also fairly sure I've seen this precise code before and concluded that it's unsafe.

Yes, the code is expected to hang. It's simply not doing what it intends to do, and it should be fixed.

If I add a `print` where you add to the queue, where you remove from the queue, and where the queue-loop ends, I get:
```
Adding task. Queue size: 1

Removing task: Queue size: 0

Loop done

Adding task. Queue size: 1
```
This shows that something is added to the queue *after* it thought it was done processing. That microtask will never fire, and since something is waiting for it, the code hangs.

One thing the code does wrong is that it doesn't actually run the scheduled functions in the correct zone. Change the handler to:
```dart
          scheduleMicrotask: (_, __, actualZone, microtask) {
            microtasks.add(actualZone.bindCallback(microtask));
          },
```
(that also calls `registerCallback`, which you should for async callbacks). Doesn't fix the problem, though, but could cause issues with other zones if they rely on `registerCallback` being called or the correct zone being used.

The `tearDown` callback is not run in the created zone. That's not surprising, `tearDown` is called before the zone exists. It's also run after the test function has returned and the fake microtask loop has completed, so that's where the late add to the `zone`'s microtask queue comes from. The `_future` is created in that zone and uses it for its `scheduleMicrotask` to report its result. Since the custom microtask loop has long ended, the `await` waiting for that never completes.

If I were to write it, I'd do something like:
```dart
// @dart=2.12
import 'dart:async';
import 'dart:collection';

import 'package:test/test.dart';

Future<void> main() async {
  tearDown(() async {
    await ensureLoaded();
  });

  test('without ft', () async {
    final Queue<void Function()> microtasks = Queue<void Function()>();
    bool scheduled = false;
    final Zone zone = Zone.current.fork(
      specification: ZoneSpecification(
        scheduleMicrotask: (s, p, z, microtask) {
          microtasks.add(z.bindCallback(microtask));
          if (!scheduled) {
            scheduled = true;
            p.scheduleMicrotask(s.parent!, () {
              while (microtasks.isNotEmpty) {
                microtasks.removeFirst()();
              }
              scheduled = false;
            });
          }
        },
      ),
    );

    zone.run(() async {
      await ensureLoaded();
    });

    expect(microtasks, isNotEmpty);
    await Future(() {});
    expect(microtasks, isEmpty);
  });
}

Future<void>? _theFuture;

Future<void> ensureLoaded() async {
  if (_theFuture != null) {
    return _theFuture!;
  }

  Future<void> loadInternal() async {
    await null;
  }

  _theFuture = loadInternal();
  await _theFuture;
}
```

**Comment by eernstg** [comment] 2021-02-02 11:35
It looks like we're reverting a bug fix (https://dart-review.googlesource.com/c/sdk/+/175310) because it reveals that some tests are buggy. The fact that the test also times out if `return _theFuture!;` is changed to `return await _theFuture!;` also shows that the given example is highly sensitive to scheduling (that's what @lrhn calls 'unsafe'), so the pre-175310 semantics doesn't make them safe, they're just lucky. So I think we should get 175310 landed at some point.

**Comment by dnfield** [comment] 2021-02-02 22:36
I think the fix for this will need to be in `fake_async` then.

I have no objection to relanding this functionality - I think some of the revert going on was to unblock some internal rolls. I think it would be ideal to fix fake_async before relanding this functionality, and making sure that rolls to the right places (this repo and the internal monorepo) before relanding the change, unless there's an urgent need to reland it.

**Comment by dnfield** [comment] 2021-02-02 22:39
The only part of that code sample you provided that might be challenging is the `scheduled` idea. 

`fake_async` wants to control all microtask scheduling so that they can be flushed in a controlled manner, and test expectations can be validated before/after a future completes.

**Comment by dnfield** [comment] 2021-02-02 22:41
In other words, it is not clear to me how we can let the test framework for Flutter control microtask flushing here - your example assumes that microtasks need to bea ble to fire sooner than we might want.

**Comment by lrhn** [comment] 2021-02-03 10:13
It's impossible to control "all microtask scheduling". If your framework depends on doing that, it will fail.

* You can always call `Zone.root.scheduleMicrotask`.
* If you have a `Future` completed in the root zone (or some other foreign zone), then calling `thatFuture.then(...)` will schedule a microtask in that zone. Such futures are sometimes provided by the platform libraries.<sup>1</sup>
* If you receive a `RawReceivePort` event, it's handled in the root zone. If it does anything async, that gets scheduled in the root zone.

Also, not all future callbacks are triggered by a scheduled microtask at all. Some are triggered directly by other futures completing.

At most, you can provide tools for users to control their own microtasks, as long as they stay within some fixed usage scenario. You can't prevent other code from going beyond that, and you need to be ready for that to happen.
(I do think the test framework's usage of zones should be changed so you can declare a test in a zone, and it then *runs* in that zone, possibly in a child zone with extra test information. The current behavior is completely unpredictable.)

The minimal fix I'd do in this situation is probably to have a "flushMicrotasks" operation that empties the new microtask queue, and *also* call that in the `tearDown` callback. At least things will happen.

As a larger change, I'd introduce dynamic scopes where the events are manually controlled, and have some automatic scheduling when outside of such a scope, something like:
```dart
test("whatnot", () {
  fake_async.controlScope((controller) {
     do some stuff.
     controller.flushQueue();
     do more stuff 
  });
});
```
and if the fake microtask queue is *not* empty and *not* inside a control scope, then it's automatically scheduled to run at some point anyway. A scheduled microtask which never runs is a bad error mode. It's better to have run and thrown than to never have run at all.



<sup>1</sup>: I actually want to change this, so that it uses the zone of the listener to schedule the listener, but if there is more than one listener, it will likely only use the zone of the first one, so you still won't be sure that something runs in a specific zone's microtask queue. Haven't happened yet, and maybe never will, because any attempt to change which zones does what breaks a lot of fragile tests.

**Comment by jamesderlin** [comment] 2021-02-03 10:57
> (I do think the test framework's usage of zones should be changed so you can declare a test in a zone, and it then _runs_ in that zone, possibly in a child zone with extra test information. The current behavior is completely unpredictable.)

Yeah... also see https://github.com/flutter/flutter/issues/57600 and https://github.com/dart-lang/test/issues/1023.

One thing I don't understand about all of this is how/why did the test originally pass?  Dumb luck?

**Comment by lrhn** [comment] 2021-02-03 13:34
Yes, dumb luck and implementation details. 

The problematic future (let's call it `f1`) is created and completed inside the fake async zone.
It's an instance of the internal `_Future` class, which most futures are.

The `tearDown` callback is `async` and returns a different future (`f2`), which is created in the outer zone.  That's also a `_Future`.

With the existing behavior, the `return` of `f1` would not listen to `f1`. It would instead return it as-is and complete `f2` directly with `f1` (like calling `Completer.complete`, but using internal private methods).

That completion [recognizes `f1` as an internal `_Future`](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/future_impl.dart#L522) which has already been completed with a value. That's a "safe" case, so it just [completes `f2` with the same value](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/future_impl.dart#L507) (picked out of the `f1` future using a private getter), which means that the zone of `f1` never comes into play. The zone of `f2` is then used to schedule reporting that value to the registered listeners of `f2`.

With the new semantics, or if you write `return await ...`, the async function waits for the result of the `f1` future.
That means attaching a listener to the future &mdash; or really, since the future is already completed, scheduling a microtask to report the value to the `then` callback. That microtask uses the zone of the `f1` future.

The zone of the `f1` future is broken, it doesn't respect arbitrary calls to `scheduleMicrotask`, but the former approach gets lucky and dodges that brokenness due to an internal optimization in the `_Future._complete` method.

**Comment by dnfield** [comment] 2021-02-03 17:19
So does this mean that `fakeAsync`'s `flushMicrotasks` is fundamentally broken? https://github.com/dart-lang/fake_async/blob/3ccb51ff90eee2d480aabbe89990a199f19fc97e/lib/fake_async.dart#L177-L195

**Comment by lrhn** [comment] 2021-02-04 16:27
I'd say ... yes. It's fundamentally broken. 
I wanted to say "fundamentally fragile", but it has none of the affordances you'd need to make it safe.

If you have a zone which overrides schedule microtask with its own scheduler, then it *needs* to run all scheduled microtasks eventually. That, or perhaps throw synchronously when anything tries to schedule a microtask. Otherwise things get stuck.

If you run arbitrary code (any code not under part of the framework) in that zone, then it might schedule microtasks events again at *any later time*. If you create a future and store it for late (like here). If you start a timer task and then do microtasks in there. If you simply store `Zone.current` and reuse it later (which library code can do for any number of reasons).

The idea in fake_async seems to be that when you have flushed the microtask queue, then all computation in the zone is done.
That's not correct. You cannot, ever, predict when all computation in a zone is done. Someone, somewhere, might have stored the `Zone` along with a (properly registered) callback, and will then call it in two hours (I thing fake_async does handle timers), or when an HTTP request completes, or a port even arrives.

The only way to use fake_async safely is to ensure that *nothing* which happens inside the test can possibly leak. That doesn't sound viable (as the current example shows, caching anything which contains a zone is a problem).

It's fine to have a "flush microtasks" function, but it cannot be the *only* way to make microtasks run. There has to be a backup solution like the `schedule` trick I introduced above. You can still flush if you want to, then the scheduled backup will just find an empty queue.

**Comment by zanderso** [comment] 2021-02-04 17:16
I filed https://github.com/dart-lang/fake_async/issues/32 and pointed to the discussion here.

Since the revert has landed, the cause of the issue seems to be understood, and a few options for fixes have been identified, I will close this issue. We may also want internal issues to track migrating the internal tests to any new APIs resulting from the resolution of https://github.com/dart-lang/fake_async/issues/32.

So the sequence would be:
1. Address https://github.com/dart-lang/fake_async/issues/32
2. Migrate tests.
3. Reland https://dart-review.googlesource.com/c/sdk/+/175310

Please correct me if I've misunderstood something =)

**Closed by zanderso** 2021-02-04 17:16 UTC
Labels: P0, a: tests, dependency: dart, passed first triage, severe: regression
