### ISSUE TITLE
error about shared_preferences_android-2.1.1

### ISSUE THREAD

**Issue by AhhhhDong** [flutter/flutter#124858] opened 2023-04-14 11:02 UTC
when I build my project(dependence shared_preferences),two error about java 1.8,but my project,
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    },
it doesn't work

**Comment by stuartmorgan** [comment] 2023-04-14 11:21
Duplicate of https://github.com/flutter/flutter/issues/124839

**Closed by stuartmorgan** 2023-04-14 11:21 UTC
