### ISSUE TITLE
Restore the "physical model" shadow rendering implementation

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8639] opened 2017-03-08 01:18 UTC
It was temporarily disabled by https://github.com/flutter/flutter/pull/8636

The problem can be demo'd with the gallery Shrine app, see https://github.com/flutter/flutter/issues/8635

@jason-simmons

**Comment by Hixie** [comment] 2017-03-08 07:35
This also improved some of the performance benchmarks, most notably the average rasterizer frame time (though it made the worst case worse again). Presumably this is because painting shadows is now cheaper but we do it more often? If I'm right, maybe we can cache the shadows that get painted a few times? The regression here (which this revert reverted) is tracked in https://github.com/flutter/flutter/issues/8501.

**Comment by eseidelGoogle** [comment] 2017-03-28 21:52
I believe @jason-simmons did this?  Speculatively closing.

**Closed by eseidelGoogle** 2017-03-28 21:52 UTC
Labels: customer: gallery, prod: framework, prod: material design, regression
