### ISSUE TITLE
Flutter plugin for Android does not get onDestroy() application events - using plugin api v2 : ActivityAware.onDetachedFromActivity() and FlutterPlugin.onDetachedFromEngine()

### ISSUE THREAD

**Issue by evaisse** [flutter/flutter#124201] opened 2023-04-05 12:59 UTC
I'm writing an Android Plugin and I need to hook some of my logic into the `onDestroy()` event of the Android activity lifecycle.

**It seems that this app lifecycle event is never propagated to android plugin code**, despite some parts of the documentation mentioning otherwise. 

If I do unsterdand the direction pointed by the documentation `PluginRegistry.Registrar.addViewDestroyListener()` : https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html#addViewDestroyListener(io.flutter.plugin.common.PluginRegistry.ViewDestroyListener)

The deprecated API mention to migrate on both `onDetachedFromActivity()` and `onDetachedFromEngine()` to get the similar behavior.

> Adds a callback allowing the plugin to take part in handling incoming calls to [Activity.onDestroy()](https://developer.android.com/reference/android/app/Activity.html?is-external=true#onDestroy()).
This registrar is for Flutter's v1 embedding. The concept of View destruction does not exist in the v2 embedding. However, plugins in the v2 embedding can respond to [ActivityAware.onDetachedFromActivityForConfigChanges()](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html#onDetachedFromActivityForConfigChanges()) and [ActivityAware.onDetachedFromActivity()](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html#onDetachedFromActivity()), which indicate the loss of a visual context for the running Flutter experience. Developers should implement [ActivityAware](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html) for their [FlutterPlugin](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html) if such callbacks are needed. Also, plugins can respond to [FlutterPlugin.onDetachedFromEngine(FlutterPlugin.FlutterPluginBinding)](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html#onDetachedFromEngine(io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding)), which indicates that the given plugin has been completely disconnected from the associated Flutter experience and should clean up any resources. 

I append some logs with the `FlutterPluginActivity`tag, to see the resulting behavior, on each lifecycle events expected from the stop of the application.

```dart
class HellodestroyPlugin: FlutterPlugin, MethodCallHandler, ActivityAware {
  /// The MethodChannel that will the communication between Flutter and native Android
  ///
  /// This local reference serves to register the plugin with the Flutter Engine and unregister it
  /// when the Flutter Engine is detached from the Activity
  private lateinit var channel : MethodChannel

  override fun onAttachedToActivity(binding: ActivityPluginBinding) {
    Log.d(TAG, "onAttachedToActivity")
  }

  override fun onDetachedFromActivityForConfigChanges() {
    Log.d(TAG, "onDetachedFromActivityForConfigChanges")
  }

  override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
    Log.d(TAG, "onReattachedToActivityForConfigChanges")
  }

  override fun onDetachedFromActivity() {
    Log.d(TAG, "onDetachedFromActivity")
  }

  override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    Log.d(TAG, "onAttachedToEngine")
    channel = MethodChannel(flutterPluginBinding.binaryMessenger, "hellodestroy")
    channel.setMethodCallHandler(this)
  }

  override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
    if (call.method == "getPlatformVersion") {
      result.success("Android ${android.os.Build.VERSION.RELEASE}")
    } else {
      result.notImplemented()
    }
  }

  override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    Log.d(TAG, "onDetachedFromEngine")
    channel.setMethodCallHandler(null)
  }
}
```

And also from the main activity of the flutter container

```dart
class MainActivity: FlutterActivity() {
    override fun onDestroy() {
        Log.d(TAG, "onDestroy from MainActivity: FlutterActivity")
        super.onDestroy()
    }
}
```

Thank you for reading me so far :), and thanks for helping me !

## Steps to Reproduce

1. Execute `flutter run` on Android with the following repo : https://github.com/evaisse/demo-flutter-plugin-android-issue-on-destroy
2. `cd example`
3. `flutter run lib/main.dart`
4. Just let the application start and **kill it** on the android device
5. Check logcat with the tag `FlutterPluginActivity` to see that you won't see the onDestroy() callbacks when application is killed

**Expected results:** 

```
-  onAttachedToEngine
-  onAttachedToActivity
-  onDestroy from MainActivity: FlutterActivity
-  onDetachedFromActivity
-  onDetachedFromEngine
```

**Actual results:** 

```
---------------------------- PROCESS STARTED (11553) for package com.example.hellodestroy_example ----------------------------
2023-04-05 10:33:27.721 11553-11553 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToEngine
2023-04-05 10:33:27.721 11553-11553 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToActivity
---------------------------- PROCESS ENDED (11553) for package com.example.hellodestroy_example ----------------------------
---------------------------- PROCESS STARTED (12269) for package com.example.hellodestroy_example ----------------------------
2023-04-05 10:34:36.570 12269-12269 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToEngine
2023-04-05 10:34:36.570 12269-12269 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToActivity
2023-04-05 10:35:00.785 12269-12269 FlutterPluginActivity   com.example.hellodestroy_example     D  onDestroy from MainActivity: FlutterActivity
---------------------------- PROCESS ENDED (12269) for package com.example.hellodestroy_example ----------------------------
---------------------------- PROCESS STARTED (2468) for package com.example.hellodestroy_example ----------------------------
2023-04-05 10:32:41.876  2468-2468  FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToEngine
2023-04-05 10:32:41.876  2468-2468  FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToActivity
2023-04-05 10:33:01.886  2468-2468  FlutterPluginActivity   com.example.hellodestroy_example     D  onDestroy from MainActivity: FlutterActivity
2023-04-05 10:33:01.898  2468-2468  FlutterPluginActivity   com.example.hellodestroy_example     D  onDetachedFromActivity
---------------------------- PROCESS ENDED (2468) for package com.example.hellodestroy_example ----------------------------
```

You can see there the event `onDetachedFromEngine` is never called, and on top of that, logs results are not consistents between several attempts.

<details>
  <summary>Logs</summary>

Build logs for `flutter run lib/main.dart` --verbose available as attachment in the following file : https://github.com/evaisse/demo-flutter-plugin-android-issue-on-destroy/blob/master/example/out.log.txt

---

logs for `flutter analyze`

```
Analyzing example...                                                    
No issues found! (ran in 2.8s)

```

---

logs for `flutter doctor -v`

```
[!] Flutter (Channel unknown, 3.3.10, on macOS 12.5.1 21G83 darwin-x64, locale fr-FR)
    ! Flutter version 3.3.10 on channel unknown at /usr/local/opt/flutter
    ! Upstream repository unknown
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/evaisse/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/evaisse/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chromium.app/Contents/MacOS/Chromium

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/evaisse/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Users/evaisse/Library/Application Support/JetBrains/Toolbox/apps/IDEA-E/ch-0/221.5921.29/IntelliJ IDEA Edu.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,*.local,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (4 available)
    • SM G965F (mobile)              • 220938ee09057ece          • android-arm64  • Android 10 (API 29)
    • macOS (desktop)                • macos                     • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                   • chrome                    • web-javascript • Chromium 90.0.4401.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2023-04-06 05:03
Hi @evaisse
This issue seems to have been fixed on the latest stable channel (`3.7.10`) as I cannot reproduce it there. 

```
2023-04-06 11:58:00.165 18514-18514 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToEngine
2023-04-06 11:58:00.166 18514-18514 FlutterPluginActivity   com.example.hellodestroy_example     D  onAttachedToActivity
2023-04-06 11:58:11.504 18514-18514 FlutterPluginActivity   com.example.hellodestroy_example     D  onDestroy from MainActivity: FlutterActivity
2023-04-06 11:58:11.512 18514-18514 FlutterPluginActivity   com.example.hellodestroy_example     D  onDetachedFromActivity
2023-04-06 11:58:11.514 18514-18514 FlutterPluginActivity   com.example.hellodestroy_example     D  onDetachedFromEngine
```

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (2 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-22.0.pre.49, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-22.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f3e8ae7d51 (75 minutes ago), 2023-04-05 18:48:03 -0700
    • Engine revision 610cdf0ae1
    • Dart version 3.0.0 (build 3.0.0-411.0.dev)
    • DevTools version 2.23.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I'll be closing this issue since it has already been fixed on the stable channel. If you still experience this issue on the stable channel, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-04-06 05:03 UTC
Labels: in triage
