### ISSUE TITLE
HTML Widget

### ISSUE THREAD

**Issue by lemonboston** [flutter/flutter#15244] opened 2018-03-07 16:26 UTC
Hello,
I know that the question has been asked before about the possible support for rendering html content simirarly as the native platforms do, and that the answer was that it wasn't planned: https://github.com/flutter/flutter/issues/25 https://github.com/flutter/flutter/issues/7311

But I've also seen the comment by @DaveShuckerow from Dec 2017 https://github.com/flutter/flutter_markdown/issues/19#issuecomment-350358715 that there is a plan to release a widget that is being used and developed internally at Google.

Being able to show html content is a critical part of our small project now and we don't really have the resources to develop this on our own.
So I would like to ask whether it would be possible for you guys to make that widget available in it's current state? Like a preview version, or even just a gist that we could use clearly at our own risk without any guarantees. It would be a big help for us.

(If you didn't want to publish it publicly yet, but maybe can send it in private, my email is: gabor.keszthelyi@gmail.com)

Thanks for any response in advance

**Comment by Hixie** [comment] 2018-03-07 17:44
This is the best that's available currently: https://github.com/dart-flitter/flutter_webview_plugin

Long-term this is a duplicate of https://github.com/flutter/flutter/issues/730.

**Closed by Hixie** 2018-03-07 17:44 UTC

**Comment by lemonboston** [comment] 2018-03-07 19:36
@Hixie I am not sure I get this correctly but this request is not about what is usually called a WebView. It's about having a formatted output from a plain html content (without js, css, anything), just as what the Markdown widget does. So I am talking about a 'passive' Widget.

Android can do it with turning the html into a Spanned with a util and then displaying it in a TextView: https://stackoverflow.com/a/2116191/4247460
I see Flutter has RichText which also has TextSpan, so I wonder if a similar approach could work here as well. Having something that creates TextSpan from html.

Regarding flutter_webview_plugin, as I see it can only load urls, not ready static content.
And as I understand #730 is about making it possible to add that WebView in the widget tree anywhere (if that's what inline means).

I assume this 'static' Html content widget is a much simpler undertaking than the WebView. Or is the plan to handle both cases in an upcoming WebView? To display 'local' plain html text content and to load pages as well?

**Comment by Hixie** [comment] 2018-03-07 23:10
I don't understand exactly what you're asking for. What would you want this widget to do if it was given something like `<marquee><video src="foo.mp4"></video><input></marquee>` ?

**Comment by lemonboston** [comment] 2018-03-08 16:33
@DaveShuckerow thanks a lot! Good to hear it! I will be watching the repository.

@Hixie - only a subset of html tags about text formatting / styling / structure would be supported, the rest is either ignored or exception thrown. Hyperlink is usually supported as well.
So this is a special usage of html, I couldn't find a standard term for this now.
But it is probably better put as 'Support of html tags in formatting text'.
[This](https://developer.android.com/guide/topics/resources/string-resource.html) Android docs about string assets call it 'Styling with HTML markup`.
Html tags in javadoc may be another example.
The tags supported by the Html-util+TextView on Android is not documented but listed in an answer [here](https://stackoverflow.com/a/45146556/4247460).
As for iOS, which I am not familiar with, [here](https://stackoverflow.com/questions/2454067/display-html-text-in-uitextview) is an answer on their solution for html tags in text view.
And I also came accross this: http://doc.qt.io/archives/qt-4.8/richtext-html-subset.html

Just as a side note, after trying to look this topic up now, it looks like for me that a standard specification may be missing, or could potentially be useful, to define subset(s) of html tags for basic text styling. So that producer and renderer of these kind of contents could state their compliance. New MIME types could be assigned for them.
Not sure why it doesn't exist. Any idea? I don't know much about html, maybe because it wouldn't be obvious how to select those subsets.

(Note: I am going to edit the title of the ticket.)

**Comment by Hixie** [comment] 2018-03-08 17:08
Ah, so not so much HTML as some new format that happens to be reminiscent of HTML in some small ways.

Implementing that should be relatively simple, just write a spec that describes the format, then implement it, generating widgets as your output. It's not something we want to do as a first-class primitive since there's so many formats that could be picked and no particular reason to pick any one of them, but we already have a package for doing something similar with markdown, so there is precedent for a non-first-class package. If you're happy to wait to see what Dave is talking about, that may well solve your problem. Or you are welcome to create your own.

**Comment by lemonboston** [comment] 2018-03-08 18:31
Yep, we are probably going to wait to see the widget from Dave and the team if our schedule allows it, or find some workaround if it doesn't.

**Comment by Katarn** [comment] 2018-03-09 21:46
@lemonboston you can try this solution: https://gist.github.com/Katarn/588725dce850c81da8a551f92fb0923a

**Comment by lemonboston** [comment] 2018-03-12 18:22
Thanks @Katarn ! I've just tried and `<br>..</br>` sections didn't result in new lines for some reason for me, but this code certainly looks like something that we could build on if we need to create our own solution. Thanks a lot!

**Comment by nsreenath** [comment] 2018-05-22 15:23
@DaveShuckerow github.com/google/flutter.widgets is still empty. Is the work going on ?

**Comment by Sub6Resources** [comment] 2018-08-15 19:12
For those that stumble across this thread, I've created a package that may help solve this: https://pub.dartlang.org/packages/flutter_html

**Comment by hathibelagal-dev** [comment] 2019-03-06 20:02
I couldn't find any package that supports CSS. So I created one.

If you want to be able to be able to quickly style your text using CSS, here's a package that may help: https://pub.dartlang.org/packages/css_text

**Comment by daohoangson** [comment] 2019-06-14 06:45
I have released another plugin for this https://pub.dev/packages/flutter_widget_from_html. Any serious app that renders HTML will use some custom widgets so this plugin was designed for easy extensibility.

**Comment by ali-thowfeek** [comment] 2020-05-04 07:46
For those who come across this thread, even at this time, this issue can still be relevant in some cases. So I'm adding another package to the discussion.

[simple_html_css](https://pub.dev/packages/simple_html_css)

Not only you can use this to display html and CSS text, you can also override CSS styles as per your wish.
