### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by spich** [flutter/flutter#119311] opened 2023-01-27 03:34 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:434:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:433:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:916:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1376:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-arm64, locale hr-HR)
    • Flutter version 3.7.0 on channel stable at /Users/igorsepic/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/igorsepic/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
app_links-3.4.1
appinio_social_share-0.2.0
assets_audio_player-3.0.6
assets_audio_player_web-3.0.6
audio_session-0.1.13
audioplayers-2.0.0
audioplayers_android-1.1.4
audioplayers_darwin-2.0.0
audioplayers_linux-1.0.3
audioplayers_web-2.1.1
audioplayers_windows-1.1.2
blue_thermal_printer-1.2.3
cached_video_player-2.0.3
cloud_firestore-4.3.1
cloud_firestore_web-3.2.1
contact_picker_web-4.7.0
file_picker-5.2.5
firebase_app_check-0.1.1+8
firebase_app_check_web-0.0.7+11
firebase_auth-4.2.5
firebase_auth_web-5.2.4
firebase_core-2.4.1
firebase_core_web-2.1.0
firebase_dynamic_links-5.0.11
firebase_in_app_messaging-0.7.0+10
firebase_messaging-14.2.1
firebase_messaging_web-3.2.11
firebase_storage-11.0.10
firebase_storage_web-3.3.19
flutter_document_picker-5.1.0
flutter_email_sender-5.2.0
flutter_local_notifications-13.0.0
flutter_plugin_android_lifecycle-2.0.7
flutter_share_me-1.4.0
flutter_sms-2.3.3
flutter_sound-9.2.13
flutter_sound_web-9.2.13
fluttercontactpicker-4.7.0
geocoding-2.0.5
geolocator-9.0.2
geolocator_android-4.1.4
geolocator_apple-2.2.3
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.3
google_maps_flutter_android-2.4.2
google_maps_flutter_ios-2.1.13
google_sign_in-5.4.3
google_sign_in_android-6.1.4
google_sign_in_ios-5.5.1
google_sign_in_web-0.10.2+1
image_gallery_saver-1.7.1
image_picker-0.8.6
image_picker_android-0.8.5+4
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+5
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.7
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
qr_code_scanner-1.0.1
share_plus-6.3.0
smart_auth-1.0.8
speech_to_text-6.1.1
speech_to_text_macos-1.0.2
sqflite-2.2.3
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.10
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by darshankawar** [comment] 2023-01-27 07:01
Closing this as duplicate of https://github.com/flutter/flutter/issues/65242. 
Also, this issue looks like was trigerred due to cache, so maybe reinstalling the sdk could be tried to see if the issue gets resolved or not.

**Closed by darshankawar** 2023-01-27 07:01 UTC
Labels: in triage
