### ISSUE TITLE
Failed Assertion Bug 

### ISSUE THREAD

**Issue by zmcgrath96** [flutter/flutter#21624] opened 2018-09-10 01:21 UTC
I/flutter (30887): The following assertion was thrown building TouchController(dirty):
I/flutter (30887): 'package:flutter/src/widgets/basic.dart': Failed assertion: line 3349 pos 15: 'direction != null':
I/flutter (30887): is not true.

This was called while dealing with the Flex widget using a Render Box several children down.

**Comment by zoechi** [comment] 2018-09-11 10:39
You are probably not using a `Scaffold`.
In this case you need to provide https://docs.flutter.io/flutter/widgets/Directionality-class.html for some widgets to work.

Tentatively closing as working as intended.
If the suggestion doesn't help please provide more informations about how to reproduce and I'll reopen.

**Closed by zoechi** 2018-09-11 10:39 UTC
