### ISSUE TITLE
HTTP error 424: Failed Dependency ，Will not be able to Building flutter tool

### ISSUE THREAD

**Issue by DriverWang** [flutter/flutter#28501] opened 2019-02-26 09:36 UTC
flutter doctor

Downloading Dart SDK from Flutter engine f1f19bba8f0089490962316867bd222727510ac5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71.3M  100 71.3M    0     0  5024k      0  0:00:14  0:00:14 --:--:-- 4720k
Building flutter tool...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

**Comment by zoechi** [comment] 2019-02-26 09:42
Duplicate of #28498

**Closed by zoechi** 2019-02-26 09:42 UTC

**Comment by chenglu** [comment] 2019-02-26 14:43
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.
