### ISSUE TITLE
[android_alarm_manager] findAppBundlePath crash NullPointerException on terminated mode

### ISSUE THREAD

**Issue by CoderJava** [flutter/flutter#76835] opened 2021-02-26 01:56 UTC
This crash happen when I'm used plugin firebase_messaging and android_alarm_manager. Crash happen when my app run on terminated mode in Android 10.

<details>
    <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-EC)
    • Flutter version 1.25.0-8.3.pre at /Users/yudisetiawan/fvm/versions/beta
    • Framework revision 5d36f2e7f5 (6 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yudisetiawan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```
</details>

<details>
    <summary>pubspec.yaml</summary>

```
name: isapp
description: Aplikasi Nusawork.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+26 # Android
# version: 1.2.1+20 # IOS

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Flutter plugin for Firebase Cloud Messaging.
  firebase_messaging: ^8.0.0-dev.11

  # Flutter plugin for Firebase Crashlytics.
  firebase_crashlytics: ^0.2.3+1

  # Flutter plugin for Firebase Core, enabling connection to muliple Firebase apps.
  firebase_core: ^0.5.3

  # Flutter plugin for accessing the Android AlarmManager service, and running
  # Dart code in the background when alarms fire.
  android_alarm_manager: ^0.4.5+20

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/translations/

```
</details>

<details>
    <summary>log error</summary>

```
Fatal Exception: java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3556)
       at android.app.ActivityThread.access$1300(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
aused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
       at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:2)
       at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:8)
       at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:17)
       at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:21)
       at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:20)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
       at android.app.ActivityThread.access$1300(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Comment by darshankawar** [comment] 2021-02-26 08:46
@CoderJava 
Can you provide steps to replicate the crash including a minimal reproducible code sample ?

**Comment by CoderJava** [comment] 2021-02-26 09:02
@darshankawar I'm used android alarm manager to run schedule reminder attendance. So, on the weekdays it will be show an notification for clock in and clock out. And also I'm used firebase messaging for another feature. 

After do a little bit research I found something that when I removed plugin firebase messaging this crash not happening.

Steps to reproduce:
• Start run app
• Kill or terminated app. And wait until android alarm manager run.
• And when android alarm manager run on terminated mode my app will be crashed.

<details>
    <summary>main.dart</summary>

```
import 'dart:async';
import 'dart:io';
import 'dart:isolate';

import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/cupertino.dart';
import 'package:isapp/app.dart';

void triggerReminderAttendance() async {
  final now = DateTime.now();
  final isolateId = Isolate.current.hashCode;
  /// Run schedule reminder attendance
  // var notificationHandler = NotificationHandler();
  // await notificationHandler.initReminderAttendance();
  // notificationHandler.doTriggerReminderAttendance();
  print("[$now] trigger reminder attendance! isolate=${isolateId} function='$triggerReminderAttendance'");
}

void main() async {
  var triggerReminderAttendanceId = 1000;
  if (Platform.isAndroid) {
    await AndroidAlarmManager.initialize();
  }
  runZonedGuarded(
    () {
      runApp(App());
    },
    (error, stacktrace) {
      debugPrint('runZonedGuarded: Caught error in my root zone.');
      FirebaseCrashlytics.instance.recordError(error, stacktrace);
    },
  );
  if (Platform.isAndroid) {
    await AndroidAlarmManager.periodic(
      const Duration(hours: 3),
      triggerReminderAttendanceId,
      triggerReminderAttendance,
    );
  }
}
```
</details>

**Comment by darshankawar** [comment] 2021-02-26 11:24
@CoderJava 
So if you purely only use `android_alarm_manager` code, this crash doesn't occur, but as soon as you add `firebase_messaging` plugin in `pubspec.yaml`, compile and run your app, it crashes ?

It seems you are hitting https://github.com/flutter/flutter/issues/64458 which has been fixed and merged. I see that you are on older version of beta. Can you upgrade to latest beta or latest master and try again to see if issue persists or not ?

**Comment by CoderJava** [comment] 2021-02-26 11:42
@darshankawar Ok. I will try it.

**Comment by sidharathjain2** [comment] 2021-02-27 17:30
I am facing the same issue with the combination of example app and flutter_local_notification (https://pub.dev/packages/android_alarm_manager). Once killed off


![error](https://user-images.githubusercontent.com/63875151/109336291-2c0f8780-7889-11eb-96cc-16492ce553a6.jpeg)


It shows an error in the console

I/FlutterBackgroundExecutor(24917): Starting AlarmService...
E/AndroidRuntime(24917): FATAL EXCEPTION: main
E/AndroidRuntime(24917): Process: com.dexterous.flutter_local_notifications_example, PID: 24917
E/AndroidRuntime(24917): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(24917): at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(24917): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(24917): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24917): at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(24917): at android.app.ActivityThread.main(ActivityThread.java:7080)
E/AndroidRuntime(24917): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24917): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(24917): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
E/AndroidRuntime(24917): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917): at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(24917): at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(24917): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(24917): ... 8 more
I/FlutterBackgroundExecutor(25150): Starting AlarmService...
E/AndroidRuntime(25150): FATAL EXCEPTION: main
E/AndroidRuntime(25150): Process: com.dexterous.flutter_local_notifications_example, PID: 25150
E/AndroidRuntime(25150): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(25150): at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(25150): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(25150): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25150): at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(25150): at android.app.ActivityThread.main(ActivityThread.java:7080)
E/AndroidRuntime(25150): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25150): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(25150): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
E/AndroidRuntime(25150): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150): at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(25150): at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(25150): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(25150): ... 8 more
-------------------------------------------------------------------------------------------------------
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!

And after some time my android shows a message  Filed to start several times . Restore it by clearing history?
---------------------------------------------------------------------------------------------------

My main.dart file 

import 'dart:isolate';
import 'dart:math';
import 'dart:ui';

import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';

/// The [SharedPreferences] key to access the alarm fire count.
const String countKey = 'count';

/// The name associated with the UI isolate's [SendPort].
const String isolateName = 'isolate';

/// A port used to communicate from a background isolate to the UI isolate.
final ReceivePort port = ReceivePort();

/// Global [SharedPreferences] object.
SharedPreferences prefs;

Future<void> main() async {
  // TODO(bkonyi): uncomment
  WidgetsFlutterBinding.ensureInitialized();

  // Register the UI isolate's SendPort to allow for communication from the
  // background isolate.
  IsolateNameServer.registerPortWithName(
    port.sendPort,
    isolateName,
  );
  prefs = await SharedPreferences.getInstance();
  if (!prefs.containsKey(countKey)) {
    await prefs.setInt(countKey, 0);
  }
  runApp(AlarmManagerExampleApp());
}

/// Example app for Espresso plugin.
class AlarmManagerExampleApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: _AlarmHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class _AlarmHomePage extends StatefulWidget {
  _AlarmHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _AlarmHomePageState createState() => _AlarmHomePageState();
}

class _AlarmHomePageState extends State<_AlarmHomePage> {
  int _counter = 0;

  @override
  void initState() {
    super.initState();
    AndroidAlarmManager.initialize();

    // Register for events from the background isolate. These messages will
    // always coincide with an alarm firing.
    port.listen((_) async => await _incrementCounter());
  }

  Future<void> _incrementCounter() async {
    print('Increment counter!');

    // Ensure we've loaded the updated count from the background isolate.
    await prefs.reload();

    setState(() {
      _counter++;
    });
  }

  // The background
  static SendPort uiSendPort;

  // The callback for our alarm
  static Future<void> callback() async {
    print('Alarm fired!');

    // Get the previous cached count and increment it.
    final prefs = await SharedPreferences.getInstance();
    int currentCount = prefs.getInt(countKey);
    await prefs.setInt(countKey, currentCount + 1);

    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName(isolateName);
    uiSendPort?.send(null);
  }

  @override
  Widget build(BuildContext context) {
    final textStyle = Theme.of(context).textTheme.headline4;
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Alarm fired $_counter times',
              style: textStyle,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Total alarms fired: ',
                  style: textStyle,
                ),
                Text(
                  prefs.getInt(countKey).toString(),
                  key: ValueKey('BackgroundCountText'),
                  style: textStyle,
                ),
              ],
            ),
            ElevatedButton(
              child: Text(
                'Schedule periodic Alarm',
              ),
              key: ValueKey('RegisterOneShotAlarm'),
              onPressed: () async {
                await AndroidAlarmManager.periodic(
                  const Duration(seconds: 5),
                  // Ensure we have a unique alarm ID.
                  Random().nextInt(pow(2, 31)),
                  callback,
                  exact: true,
                  wakeup: true,
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by pedromassangocode** [comment] 2021-03-24 12:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:46 UTC
Labels: in triage, waiting for customer response
