### ISSUE TITLE
In iOS version 17.2, when moving the input focus in a WebView, an unknown area appears at the top of the screen.

### ISSUE THREAD

**Issue by wonbaejeon** [flutter/flutter#140683] opened 2023-12-28 02:02 UTC
### Steps to reproduce

In iOS version 17.2, when moving the input focus in a WebView, an unknown area appears at the top of the screen.
Please refer to the video.

I am aware that setting 'resizeToAvoidBottomInset' of the scaffold to false prevents the UI from being resized by the keyboard, so the issue is not reproducible.
However, I want the bottom button to be positioned above the keyboard when the body size changed.

This issue is not reproducible on Android, and it occurs only on iOS version 17.2.

To summarize:
* No issues on all Android versions.
* No issues on iOS versions below 17.2.
* Issues observed on iOS version 17.2.
* This issue is reproducing in all versions of the flutter_inappwebview and webview_flutter plugins.

I believe this may be an issue on the Flutter side due to the OS version update. Your thoughts on this matter are appreciated.

### Expected results

When moving the keyboard focus, there should be no unknown area appearing at the top of the screen

### Actual results

In iOS version 17.2, when moving the keyboard focus, an unknown area appears at the top of the screen

### Code sample

<details open><summary>Code sample</summary>

**[Dart code]**
```dart

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    var controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.blue)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            return NavigationDecision.navigate; //changed it to this, and it works now
          },
        ),
      )
      ..loadFlutterAsset('assets/test2.html');

    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: WebViewWidget(controller: controller),
        ),
      )
    );
  }
}

```

**[Web code]**
```javascript
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Mobile Keyboard Inputs</title>
    <style>
    html,body{
        /* height:100%; */
    }
    html{
        background-color:orange;
    }
    body{
        background-color:green;
    }
    body * {
        background-color:yellow;
    }
    .container{
        position:relative;
        height:100%;
    }
    .btnBottom{
        position:fixed;
        width:100%;
        bottom:0;
        left:0;
    }
         h2 {
            position: fixed;
            top: 0;
            left: 50%;
            transform: translateX(-50%);
            background-color: white; /* 타이틀 배경색을 설정 */
            padding: 10px; /* 타이틀 여백 설정 */
            margin: 0; /* 기본 마진 제거 */
        }
        input {
            margin-bottom: 10px; /* 각 input 요소 사이에 여백 추가 */
            width: calc(100% - 20px); /* 화면 가로폭에서 20px을 뺀 만큼의 너비로 설정 */
            padding: 5px; /* 각 input 요소의 여백 설정 */
        }
    </style>
</head>
<body>

<h2>Mobile Keyboard Inputs Example</h2>

<div class="container">
<form action="/submit" method="post">
        <label for="input0">Input Box 0:</label>
        <input type="text" id="input0" name="input0" placeholder="Type something..." />

        <br>

        <label for="input1">Input Box 1:</label>
        <input type="text" id="input1" name="input1" placeholder="Type something..." />

        <br>

        <label for="input2">Input Box 2:</label>
        <input type="number" id="input2" name="input2" pattern="\d*" placeholder="number" />

        <br>

        <label for="input3">Input Box 3:</label>
        <input type="number" id="input3" name="input3" pattern="\d*" placeholder="number" />

        <br>

        <button type="submit" class="btnBottom">버튼</button>
</form>
</div>

</body>
</html>

```

</details>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Monosnap screencast2 2023-12-28 10-33-57](https://github.com/flutter/flutter/assets/45409353/d901b126-f5e6-465b-b474-963462bdaebc)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-arm64,
    locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-28 11:19
Please do not file multiple issues for the same bug.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/140501

**Closed by danagbemava-nc** 2023-12-28 11:19 UTC
Labels: in triage
