### ISSUE TITLE
FutureBuilder fires twice

### ISSUE THREAD

**Issue by KlausJokinen** [flutter/flutter#27728] opened 2019-02-09 16:38 UTC
FutureBuilder fires twice.

```
void main() {
  runApp(Test());
}

Future<bool> testFuture() {
  debugPrint('testFuture');
  return Future.delayed(Duration(milliseconds: 2000));
}

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder<bool>(
        future: testFuture(),
        builder: (context, snapshot) {
          return Container();
        });
  }
}

```

```
flutter doctor -v
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.14393], locale fi-FI)
    • Flutter version 1.2.0 at C:\flutter
    • Framework revision 06b979c4d5 (2 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Pyry\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.31.0)
    • VS Code at C:\Users\Pyry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment] 2019-02-09 19:59
Duplicate of https://github.com/flutter/flutter/issues/19952 , see https://github.com/flutter/flutter/issues/19952#issuecomment-413170447 and https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html

**Closed by jonahwilliams** 2019-02-09 19:59 UTC

**Comment by Harbdollar** [comment] 2020-01-18 08:50
Read this post, I think it should be helpful [](https://medium.com/saugo360/flutter-my-futurebuilder-keeps-firing-6e774830bc2)
