### ISSUE TITLE
[tool]: Output inconsistently piped to stdout/stderr

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#98220] opened 2022-02-10 23:28 UTC
Via one of our [customers on Twitter](https://twitter.com/ancientdevelop2/status/1491839467212222471)...

Why does the flutter upgrade command display lots of text in red when there are no errors?
![image](https://user-images.githubusercontent.com/2319867/153513591-375c302d-2430-4478-80dd-5d1b7a5ac056.png)

The offending line is here (and a couple of others). It's unclear why we redirect stdout to stderr here. 
https://github.com/flutter/flutter/blob/ea6025ca499178576090ace1e5162364d1273390/bin/internal/shared.bat#L104

(I don't quite understand what's going on with the stream redirection [here](https://github.com/flutter/flutter/blob/ea6025ca499178576090ace1e5162364d1273390/bin/internal/shared.bat#L55-L60), so perhaps that's related.)

**Comment by christopherfujino** [comment] 2022-02-11 20:04
> The offending line is here (and a couple of others). It's unclear why we redirect stdout to stderr here.

we redirect to stderr so that tools that are wrapping the flutter command line tool and parsing the output don't get broken by diagnostic logs.

**Comment by christopherfujino** [comment] 2022-02-23 02:32
Closing as working as intended

**Closed by christopherfujino** 2022-02-23 02:32 UTC
Labels: tool, a: quality
