### ISSUE TITLE
conditionnal platform assets

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#149272] opened 2024-05-29 20:57 UTC
### Use case

in `pubspec.yaml` I have the following assets:
```
  assets:
    - assets/other/foo.txt
    - assets/other/bar.jpg
    - assets/bin/mac/my_bin
    - assets/bin/windows/my_bin.exe
```
So on Windows, my app contains a useless MacOS binary and on MacOS my  app contains a useless Windows binary

Can we add a way to declare assets for specific platforms?

### Proposal

```
  assets:
    - assets/other/foo.txt
    - assets/other/bar.jpg
    mac:
         - assets/bin/mac/my_bin
    windows:
         - assets/bin/windows/my_bin.exe
```

**Comment by darshankawar** [comment] 2024-05-30 07:51
Closing this as duplicate of https://github.com/flutter/flutter/issues/65065 and  https://github.com/flutter/flutter/issues/8230.

**Closed by darshankawar** 2024-05-30 07:51 UTC
Labels: in triage
