### ISSUE TITLE
Android split/multi window freeze

### ISSUE THREAD

**Issue by bit-garden** [flutter/flutter#7152] opened 2016-12-05 03:26 UTC
On android N, with split screen or freeform windows, It seems the rendering process freezes. 

You can reproduce this easily by opening your flutter app, have an indeterminate progress bar or spinner(for constant animation), then open a second app in the other half. When you focus on the other app, you can see the animations freeze. 

When you focus back onto the flutter app, the animations continue as if they haven't frozen at all(not from where they appeared to be frozen) It seems like the animation timers are still going, but the rendering isn't.

**Comment by eseidelGoogle** [comment] 2016-12-05 16:18
@jason-simmons might know.

**Comment by Hixie** [comment] 2017-11-21 22:48
This does not currently fit with our priorities. cc @sethladd can you clarify if you think this would be important for the current milestone?

**Comment by eseidelGoogle** [comment] 2017-11-21 22:50
I believe I added this due to it being a crasher, but I agree we should punt this from M3.

**Comment by goderbauer** [comment] 2018-12-27 20:09
This doesn't seem to reproduce anymore. I am closing this for now. Feel free to reopen with more information if this is still an issue for you.

**Closed by goderbauer** 2018-12-27 20:09 UTC
Labels: engine, framework, ▣ platform-android
