### ISSUE TITLE
Second last TabBarView child's dispose not being called consistently

### ISSUE THREAD

**Issue by videah** [flutter/flutter#19768] opened 2018-07-25 15:29 UTC
## Steps to Reproduce

The dispose method for tab content appears to be called inconsistently. I need to cancel a stream in a tab and this works fine on the Android emulator but on my actual phone dispose wont be called when you swipe to the tab on the right and that tab is the last one in the bar. This has me believe this could be an issue related to screen size.

Due to the inconsistency of this issue these steps will most likely do not apply to all devices. The device where this occurs for me is a Galaxy S8.

1. Override dispose() on the second last child of TabBarView to print to console
2. Swipe from the second last tab to go to the last tab
3. Nothing gets printed
4. Swipe left from the second last tab
5. Gets printed

The following example demonstrates the issue when ran on a Galaxy S8.
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(home: new TabPage());
  }
}

class TabPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          title: Text("TabBarView Bug"),
          bottom: TabBar(
            tabs: <Widget>[
              Tab(text: "1st Tab"),
              Tab(text: "2nd Last Tab"),
              Tab(text: "Last Tab")
            ],
          ),
        ),
        body: TabBarView(
          children: <Widget>[
            TestTab(tabName: "Tab 1"),
            // This tab doesn't get disposed when swiping to Tab 3.
            TestTab(tabName: "Tab 2"),
            TestTab(tabName: "Tab 3")
          ],
        ),
      ),
    );
  }
}

class TestTab extends StatefulWidget {
  final String tabName;

  const TestTab({Key key, this.tabName}) : super(key: key);

  @override
  TestTabState createState() => new TestTabState();
}

class TestTabState extends State<TestTab> {
  // Both dispose() and initState() for Tab 2 wont be called when swiping
  // between Tab 2 and Tab 3, at least on a Galaxy S8.

  @override
  void dispose() {
    print("Disposed ${widget.tabName}");
    super.dispose();
  }

  @override
  void initState() {
    print("Created ${widget.tabName}");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text("${widget.tabName}"),
    );
  }
}
```

## Logs

```
No issues found! (ran in 2.8s)
```

```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.547], locale en-GB)
    • Flutter version 0.5.1 at D:\Users\Ruairidh\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Users\Ruairidh\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (2 available)
    • SM G950F                  • ce041714f361753d03 • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554      • android-x86   • Android 8.0.0 (API 26) (emulator)
```

**Comment by VladyslavBondarenko** [comment] 2020-03-26 14:42
Hi @videah 
is it still an issue? I can't reproduce it with my device

**Comment by iapicca** [comment] 2020-04-22 10:39
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-22 10:39 UTC
Labels: f: material design, f: scrolling, framework, waiting for customer response
