### ISSUE TITLE
local_auth: _CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by HugHunter** [flutter/flutter#88350] opened 2021-08-17 12:14 UTC
## Steps to Reproduce

```dart
void main() async {
    var localAuth = LocalAuthentication();
    bool didAuthenticate = await localAuth.authenticate( // Error occurs here
        stickyAuth: true,
        localizedReason: 'Please authenticate.');
    if (didAuthenticate) {
      runApp(MyApp());
  }
}

```
**Expected results:** 

Password or biometric input prompt

**Actual results:** 

I get this error message:
` _CastError (Null check operator used on a null value)`

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/x/x/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone (mobile)  • ios            • iOS 14.7.1
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 92.0.4515.159

</details>

**Comment by stuartmorgan** [comment] 2021-08-17 13:01
You aren't calling `WidgetsFlutterBinding.ensureInitialized();`. Closing as a duplicate of https://github.com/flutter/flutter/issues/78028

**Closed by stuartmorgan** 2021-08-17 13:01 UTC
