### ISSUE TITLE
Failed to create server socket

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#5591] opened 2016-08-25 13:48 UTC
## Steps to Reproduce
- Create a normal Flutter project with the Atom creator project
- Remove the internet permission in the manifest
- Run the app
## Flutter Doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/kleak/flutter
    • Framework revision 9a0a0d9903 (13 days ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /home/kleak/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38
```
## Logs and Crash Reports

```
vm-service: Error: Unhandled exception:
SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
#0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:511)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by eseidelGoogle** [comment] 2016-08-25 13:50
This is expected behavior.  But perhaps we could handle this better?  Not sure if you can detect if you have the internet permission?  Or maybe where-ever we kick off the service isolate from should catch this and suggest adding internet permission?  I guess this is the same bug as https://github.com/flutter/flutter/issues/2138 ?

**Comment by Kleak** [comment] 2016-08-25 13:52
yep @eseidelGoogle same error exact sorry

**Comment by eseidelGoogle** [comment] 2017-02-03 21:36
This is a duplicate of https://github.com/flutter/flutter/issues/2138.

**Closed by eseidelGoogle** 2017-02-03 21:36 UTC
