### ISSUE TITLE
Platform channel not working in existing project 

### ISSUE THREAD

**Issue by rahuldevanavar91** [flutter/flutter#26838] opened 2019-01-21 06:38 UTC
I am adding flutter to my existing android project. To get data from my existing android project to flutter project I am using Platform channel.

Android side
```java
    private static final String PLATFORM_CHANNEL = "platfrom.channel.message/info";


FlutterView flutterView = Flutter.createView(
                    MainActivity.this,
                    getLifecycle(),
                    "route1"
            );
            FrameLayout.LayoutParams layout = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            addContentView(flutterView, layout);
            layout.topMargin = 20;

  GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());
        new MethodChannel(flutterView, PLATFORM_CHANNEL).setMethodCallHandler(
                new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        switch (call.method) {
                            case "getMessage":
                                result.success("Hello From Android ");
                                break;
                            default:
                                result.notImplemented(); // INFO: not implemented

                                break;
                        }
                    }
                }
        );
```

**Flutter side**

```dart
static const plafromChannel = const MethodChannel("platfrom.channel.message/info");

 Future<String> getMessage() async {
    String msg;
    msg = await plafromChannel.invokeMethod("getMessage");
    return msg;
  }
```

> I am getting the following exception

`MissingPluginException(No implementation found for method getMessage on channel platfrom.channel.message/info)
`

**Comment by wouterhardeman** [comment] 2019-01-21 13:33
I see multiple typos in your code. Is `platfrom.channle.message/info` the correct name of the channel? Does it correspond with the value of `PLATFORM_CHANNEL` in your Android code?

**Comment by zoechi** [comment] 2019-01-21 14:06
@rahuldevanavar91 Please provide a minimal reproduction ideally shared as GitHub repo.

**Comment by rahuldevanavar91** [comment] 2019-01-21 14:07
> I see multiple typos in your code. Is `platfrom.channle.message/info` the correct name of the channel? Does it correspond with the value of `PLATFORM_CHANNEL` in your Android code?

Yes ..both ..Updated the question

**Comment by rahuldevanavar91** [comment] 2019-01-21 14:09
@zoechi I have the production code ..
I will create one sample app ,I will share that one

**Comment by rahuldevanavar91** [comment] 2019-01-21 14:53
@zoechi 
Please check this code `https://github.com/rahuldevanavar91/flutter_demo_existing_app.git`

**Comment by rahuldevanavar91** [comment] 2019-01-23 05:14
@jason-simmons  Yes its showing logs, but why it's not showing on view?

**Comment by wouterhardeman** [comment] 2019-01-23 12:18
@rahuldevanavar91 How are you running the application? The error you are getting could be because you are running the flutter application directly instead of the original Android application.

**Comment by alinhayati** [comment] 2019-04-03 11:29
The issue is not with the platform not working but with your implementation. In your `getState` method you should call `setState` if you want the page to update and show the text message from native android:

**Comment by dnfield** [comment] 2020-01-10 06:06
Closing as resolved.  Starting a future in initState and then not setting state when it resolves will mean your widget doesn't get rebuilt after the value changes.  @alinhayati's answer is correct.

**Closed by dnfield** 2020-01-10 06:06 UTC
Labels: a: existing-apps, engine, p: framework, plugin, severe: crash, waiting for customer response
