### ISSUE TITLE
Not able to add proguard-rules for flutter plugin

### ISSUE THREAD

**Issue by gvsakhil** [flutter/flutter#152114] opened 2024-07-22 17:07 UTC
### Steps to reproduce

1. Create a flutter plugin
2. In android folder we don't have the app folder where we need to add config for proguard-rules

I am unable to find documentation or any info on how to add proguard-rules.pro for a Flutter plugin. In a Flutter plugin, we don't have an app folder with a build.gradle file as we do in standard Flutter applications. I've been looking into how to achieve this but haven't found relevant information.

Any guidance on adding ProGuard rules in a Flutter plugin would be greatly appreciated.

### Expected results

Able to add proguard-rules.pro for flutter plugin

### Actual results

Not able to add this proguard-rules.pro for flutter plugin

```dart
buildTypes {
        release {
            signingConfig = signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

### Code sample

<details open><summary>Code sample</summary>

```dart
buildTypes {
        release {
            signingConfig = signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.3 on channel stable at /Users/akhilgrandhi/Documents/configuration/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (6 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/akhilgrandhi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79
      darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome
      126.0.6478.183
    ! Error: Browsing on the local area network for akhil’s iPad. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-07-23 07:35
Closing as duplicate of https://github.com/flutter/flutter/issues/136909. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-07-23 07:35 UTC
Labels: in triage
