### ISSUE TITLE
BackdropFilter doesn't constrain blurred area

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#16614] opened 2018-04-16 04:45 UTC
## Steps to Reproduce

Here is a `build()` method that results in a fullscreen blur when a blur area of `125.0` units wide was expected.

```dart
    @override
    Widget build(BuildContext context) {
    return new BackdropFilter(
      filter: new ImageFilter.blur(sigmaX: 3.0, sigmaY:3.0),
      child: new Container(
        width: 125.0,
        height: double.infinity,
        color: const Color(0xAA234060),
        child: new Padding(
          padding: const EdgeInsets.only(top: 16.0),
          child: new Column(
            children: [
              new Expanded(
                child: new Icon(
                  Icons.refresh,
                  color: Colors.white,
                  size: 40.0,
                ),
              )]
              ..addAll(_createDayButtons()),
          ),
        ),
      ),
    );
  }
```

Also, this behavior was working fine for me a week or so ago.  I'm guessing that I upgraded Flutter since then and that's why it's now broken.

This issue occurs in both the iOS simulator and the Android emulator. I haven't tried on a physical device.

This is a possible dup of
https://github.com/flutter/flutter/issues/16144

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.11, on Mac OS X 10.12.6 16G29, locale en-US)
    • Flutter version 0.2.11 at [redacted]/Libs/flutter
    • Framework revision f408bb06f9 (5 days ago), 2018-04-10 14:27:53 -0700
    • Engine revision 6474647f52
    • Dart version 2.0.0-dev.46.0.flutter-ef926f98f5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at [redacted]/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by matthew-carroll** [comment] 2018-04-16 05:06
I've tried downgrading Flutter as far as 1.9 and I'm still seeing the issue.  Maybe I'm downgrading Flutter incorrectly?  I'm checking out older versions of the git repo.

**Comment by rostopira** [comment] 2019-02-28 09:46
I have same issue on dev and master channels, but beta channels is just fine

**Comment by andreidiaconu** [comment] 2019-04-01 21:41
I just upgraded to Flutter beta 1.3.8 and this started happening. Seems like the Blur effect is applied to the whole parent and any bounds are ignored. `Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-RO)`

**Comment by andreidiaconu** [comment] 2019-04-01 21:50
I switched to stable and the problem is gone, but then found this https://github.com/flutter/flutter/issues/29070 which is most likely the cause. Anyone stumbling into the same problem should try to wrap the BackdropFilter in a ClipRect, as described in the issue.

**Comment by mmahkamov** [comment] 2019-05-12 15:21
The problem wasn't there in 1.2.1 but appeared after upgrading to `Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-UZ)`

**Comment by MiaYi** [comment] 2019-06-20 22:53
I solve it by wrap `BackdropFilter` with `ClipRect`.
```
ClipRect(
    child: BackdropFilter(
        ...
    )
)
```

This is mentioned in the `BackdropFilter` class document.

**Comment by caseyryan** [comment] 2019-06-27 14:34
> I solved it by wrap `BackdropFilter` with `ClipRect`.
> 
> ```
> ClipRect(
>     child: BackdropFilter(
>         ...
>     )
> )
> ```
> 
> This is mentioned in the `BackdropFilter` class document.

I can confirm, it works, but there is also one problem though. If I do it inside a PageView, it looks good until I try to swipe the page. While it moves the whole page gets blurred

**Comment by ma-rp** [comment] 2020-04-27 15:24
Hi @caseyryan Im experiencing the same issue with the PageView, did you managed to solve it?

**Comment by TahaTesser** [comment] 2020-08-26 14:00
Hi @matthew-carroll 
Are you still experiencing this issue?   `ClipRect` does solve the issue when it comes to `BackdropFilter`

**Comment by matthew-carroll** [comment] 2020-08-26 23:19
It's been a while since I filed this, so I'm not sure what my goal was :)

It looks like @caseyryan mentioned an issue with clipping, too. Should that be resolved before closing this ticket?

**Comment by TahaTesser** [comment] 2020-09-08 12:48
Since the issue isn't reproducible withoClipReact and you don't remember your gaol. I feel safe to close the issue 
@caseyryan please file a new issue and provide all the details 
 If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-08 12:48 UTC
Labels: engine, framework
