### ISSUE TITLE
Flutter Engine Web won't start: Expected a value of type 'SkTypeface', but got one of type 'Null'

### ISSUE THREAD

**Issue by Eufranio** [flutter/flutter#76534] opened 2021-02-22 15:17 UTC
## Steps to Reproduce

1. I've just ran the debug configuration for Chrome on my project. It suddenly won't load the app anymore. I suspect this happened after an SDK/flutter update.

## Logs

<details>
<summary>Logs</summary>

```
Launching lib\main_dev.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:52479/18qfs8NCb_w=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:52479/18qfs8NCb_w=/ws
Error: Expected a value of type 'SkTypeface', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5331:11)
    at Object.castError (http://localhost:5000/dart_sdk.js:5302:15)
    at dart.AnonymousJSType.new.as (http://localhost:5000/dart_sdk.js:7144:51)
    at Array.[dartx.add] (http://localhost:5000/dart_sdk.js:15544:11)
    at _engine.SkiaFontCollection.new.ensureFontsLoaded (http://localhost:5000/dart_sdk.js:139677:147)
    at ensureFontsLoaded.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:39029:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:38886:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:33872:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34432:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34470:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34312:23)
    at http://localhost:5000/dart_sdk.js:33523:46
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:38886:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:33872:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34432:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34470:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34312:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:34335:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:39173:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:39179:13)
    at http://localhost:5000/dart_sdk.js:34686:9
ERROR - 2021-02-22 12:11:20.269411
GET /dart_sdk.js:7144:51?_ijt=hrsapstqdfgkrjl5q3aj569qsa
Error thrown by handler.
FormatException: Illegal scheme character (at character 5)
dart_sdk.js:7144:51
    ^

dart:core                                                 _Uri.resolve
package:flutter_tools/src/isolated/devfs_web.dart 503:57  WebAssetServer._resolveDartFile
package:flutter_tools/src/isolated/devfs_web.dart 395:17  WebAssetServer.handleRequest
package:dwds/src/handlers/injector.dart 110:32            DwdsInjector.middleware.<fn>.<fn>

```

```
D:\Dev\IdeaProjects\morada-dos-sonhos>flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-17.2.pre, on Microsoft Windows [versÃ£o 10.0.19041.804], locale pt-BR)
    • Flutter version 1.26.0-17.2.pre at D:\Dev\Android\flutter
    • Framework revision 79b49b9e10 (3 weeks ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Dev\Android
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Dev\Android
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```

</details>

I've updated Flutter and still get the error. Logs & versions:

<details>
<summary>Logs</summary>

```
Launching lib\main_dev.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:55204/s03fY0--AGE=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:55204/s03fY0--AGE=/ws
Error: Expected a value of type 'SkTypeface', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5342:11)
    at Object.castError (http://localhost:5000/dart_sdk.js:5313:15)
    at dart.AnonymousJSType.new.as (http://localhost:5000/dart_sdk.js:7155:51)
    at Array.[dartx.add] (http://localhost:5000/dart_sdk.js:15681:11)
    at _engine.SkiaFontCollection.new.ensureFontsLoaded (http://localhost:5000/dart_sdk.js:140115:147)
    at ensureFontsLoaded.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:39157:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:39014:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34440:23)
    at http://localhost:5000/dart_sdk.js:33651:46
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:39014:58)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:34440:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:34463:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:39301:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:39307:13)
    at http://localhost:5000/dart_sdk.js:34814:9

```

```
D:\Dev\IdeaProjects\morada-dos-sonhos>flutter doctor -v
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [versÃ£o 10.0.19041.804], locale pt-BR)
    • Flutter version 1.27.0-4.0.pre at D:\Dev\Android\flutter
    • Framework revision f8cd24de95 (6 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Dev\Android
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Dev\Android
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2021-02-23 07:03
@Eufranio 
Ran a sample code on latest dev and didn't get the issue you mentioned.

<img width="1272" alt="Screenshot 2021-02-23 at 12 31 01 PM" src="https://user-images.githubusercontent.com/67046386/108811356-2426bd80-75d3-11eb-9c58-0ff3f4287a9f.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-4.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f8cd24de95 (6 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)          • 5200763ebcfa861f                     •
      android-arm    • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.


```

</details>

Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?



> 1. I suspect this happened after an SDK/flutter update.

Can you also elaborate what previous version you were on and what version upgraded to ?

**Comment by pedromassangocode** [comment] 2021-03-17 13:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-17 13:41 UTC
Labels: in triage, waiting for customer response

**Comment by Sanape** [comment] 2021-03-21 10:10
I am getting the same error when i reload my app after terminating my debuig session and then running the app again.
It is happening with a web porject (using chrome).
Error: Expected a value of type 'SkTypeface', but got one of type 'Null'


this is where the app is stopping:
![image](https://user-images.githubusercontent.com/39309288/111901025-63023480-8a14-11eb-8de4-967960ca9f4c.png)


[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
    • Flutter version 2.0.2 at C:\SDK\flutter
    • Framework revision 8962f6dc68 (10 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\AndroidStudio
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\Equipo 2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

**Comment by sanyakuznezov** [comment] 2021-04-02 17:13
I got this error due to font recognition
 fonts:
    - family: Old
      fonts:
        - asset: fonts/oldeng.ttf
