### ISSUE TITLE
[Bug] runJavaScriptReturningResult('document.documentElement.outerHTML')

### ISSUE THREAD

**Issue by swarajkumarsingh** [flutter/flutter#127286] opened 2023-05-21 11:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Here just execute the JavaScript line, **window.document.getElementsByTagName('html')[0].outerHTML;** to get html content of the page 
2. final html = await webViewController.runJavaScriptReturningResult(
        "window.document.getElementsByTagName('html')[0].outerHTML;"
   );
   print(html);
   
   // More code ...

### Expected results

The expected result was in the form of readable html format, 

**I/flutter ( 5503): <html lang="en" class="dark-theme"><head>
I/flutter ( 5503):   <meta charset="utf-8">
I/flutter ( 5503):   <title>NeetCode.io</title>
I/flutter ( 5503):   <meta name="description" content="A better way to prepare for coding interviews.">
I/flutter ( 5503):   <base href="/">
I/flutter ( 5503):   <meta name="viewport" content="width=device-width, initial-scale=1.0">
I/flutter ( 5503):   <style type="text/css">svg:not(:root).svg-inline--fa {
I/flutter ( 5503):   overflow: visible;**

### Actual results

 "\u003Chtml lang=\"en\" class=\"dark-theme\">\u003Chead>\n  \u003Cmeta charset=\"utf-8\">\n  \u003Ctitle>NeetCode.io\u003C/title>\n  \u003Cmeta name=\"description\" content=\"A better way to prepare for coding interviews.\">\n  \u003Cbase href=\"/\">\n  \u003Cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  \u003Cstyle type=\"text/css\">svg:not(:root).svg-inline--fa

### Code sample

<details><summary>Code sample</summary>

```dart
final html = await webViewController.runJavaScriptReturningResult(
        "window.document.getElementsByTagName('html')[0].outerHTML;"
);

print(html);

// More code ...
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/89764448/acd27ea3-6960-4743-8767-e3fec4f9b9e2)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
   Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2788], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by swarajkumarsingh** [comment] 2023-05-21 11:57
# The Perfect Solution 💕

## The Problem:
1. Don't know why but webview plugin just encodes the html and returns in a weird format, the reason for this is still a mystery.

## The Solution:
1. If the WebView is in Android the plugin just encodes it. so will jsonDecode the html, and this should do the job, the full code is below.

## Solution Code:
- Here we are adding an extension function to the webViewController, which jsonDecodes the html, only if it is in Android and returns it.

```
import 'dart:io';
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML')
        .then((value) {
      if (Platform.isAndroid) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}

```

Thank you.
Swaraj Kumar Singh.

**Comment by stuartmorgan** [comment] 2023-05-21 16:32
Closing as a duplicate of https://github.com/flutter/flutter/issues/80328

**Closed by stuartmorgan** 2023-05-21 16:32 UTC
