### ISSUE TITLE
Flutter web shows different focus behavior on Android and iOS

### ISSUE THREAD

**Issue by MarcVanDaele90** [flutter/flutter#145601] opened 2024-03-22 15:50 UTC
### Steps to reproduce

Below is a simple Flutter application containing basically a Row with

- a TextField
- an ElevatedButton (wrapped in a TextFieldTapRegion)

When selecting the TextField, I see a blinking cursor and an enabled border. (OK)

However, I observe some differences when clicking the button:

- on pc (Chrome) and Android (Chrome): clicking the button does not impact the focused state of the TextField (as expected given the TextFieldTapRegion)
- on iOS (both Safari and Chrome): clicking the button removes the focus of the TextField

Any ideas why this happens?
(I also posted the same question to [stackoverflow](https://stackoverflow.com/questions/78198951/flutter-web-shows-different-focus-behavior-on-android-and-ios) but I think this is an actual bug)

### Expected results

The TextField should not loose focus when pressing the button

### Actual results

The TextField looses focus when pressing the button

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyHomePage extends StatefulWidget {
  const MyHMyHomePageomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Row(
        children: <Widget>[
          Expanded(
            child: MyInputField(),
          ),
          Expanded(
            child: TextFieldTapRegion(
              child: ElevatedButton(
                onPressed: () {},
                child: Text("A button"),
              ),
            ),
          ),
        ],
      ),
    );
  }
}


class MyInputField extends StatelessWidget {
  final TextEditingController controller = TextEditingController();

  FocusNode focusNode = FocusNode();

  MyInputField({Key? key}) : super(key: key) {
    focusNode.requestFocus();
  }
  
  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      child: TextField(
        controller: controller,
        textAlign: TextAlign.center,
        autofocus: true,
        textInputAction: TextInputAction.none,
        showCursor: true,
        enabled: true,
        focusNode: focusNode,
        keyboardType:TextInputType.none, //no system keyboard
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on Linux Mint 20.2 5.15.0-56-generic, locale en_US.UTF-8)
    • Flutter version 3.19.4 on channel stable at /home/marc/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (2 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/marc/Android/Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2022.1)
    • Android Studio at /home/marc/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.74.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.2 5.15.0-56-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.111

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-03-25 06:57
@MarcVanDaele90 
Can you check [this](https://github.com/flutter/flutter/issues/98199#issuecomment-1216935947) and see if it helps in your case or not ?

**Comment by MarcVanDaele90** [comment] 2024-03-25 08:46
If I understand the referenced issue correctly, the suggestion is to use a TextFieldTapRegion.  
However, I'm already using the TextFieldTapRegion.
Or is there something else I should try?

Can you confirm (or not) that you reproduce the issue?

**Comment by darshankawar** [comment] 2024-03-26 06:10
Thanks for the update @MarcVanDaele90 
I tried on iOS device running on safari browser and Samsung device running on chrome and below are observations:

1. By running given code sample as-is, tapping on textfield to enable it (even though `autofocus` is true which doesn't show blinking cursor), and then tapping on button, the cursor goes away in iOS safari, while the cursor remains and keeps blinking on Samsung chrome.

2. Removing `TextFieldTapRegion` and then running on both devices + browsers gives same result, ie, the cursor goes away after tapping on the button.

Keeping this issue open for team's input / tracking.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.21.0-14.0.pre.29, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.21.0-14.0.pre.29 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a8345d5399 (4 hours ago), 2024-03-25 21:07:30 -0400
    • Engine revision 3c881b75cc
    • Dart version 3.4.0 (build 3.4.0-268.0.dev)
    • DevTools version 2.34.0-dev.12
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by MarcVanDaele90** [comment] 2024-04-02 13:19
@htoor3  Can you reconsider the P2 priority? If not, can you suggest a (temporary) work-around?

**Comment by huycozy** [comment] 2024-04-11 09:28
I think this is a duplicate of https://github.com/flutter/flutter/issues/143384 which also happens with TextFieldTapRegion.

**Comment by darshankawar** [comment] 2024-04-11 09:35
@htoor3 Hello, is it ok to close this issue in favor of linked one above and follow-up in it ?

**Comment by MarcVanDaele90** [comment] 2024-04-11 11:43
Seems indeed the same issue.  
I think the example mentioned here is simpler than the example in the other issue so it might be worthwhile top add it there too (since it might make analysis easier?)

OK to close this one.

**Comment by htoor3** [comment] 2024-04-11 18:09
Closed - duplicate of https://github.com/flutter/flutter/issues/143384

**Closed by htoor3** 2024-04-11 18:09 UTC
Labels: a: text input, framework, platform-web, f: focus, has reproducible steps, P2, browser: safari-ios, team-web, triaged-web, found in release: 3.19, found in release: 3.21
