### ISSUE TITLE
App gets stuck at blank screen - `Could not launch engine with configuration`

### ISSUE THREAD

**Issue by rymesaint** [flutter/flutter#88407] opened 2021-08-18 04:58 UTC
When running the app on physical device it got stuck at installing and launching and only blank white screen appear.

iOS : 14.7.1
xcode : 12.5 or 13 beta still not fix the problem
Emulator : working properly
Info.plist information for local networking  still not working

flutter clean or recreate ios folder using flutter create . did not help, i'm running out option

<details>
  <summary>Logs</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ID)
    • Flutter version 2.2.3 at /Users/ridwanfauzan/Documents/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ridwanfauzan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone Testing (mobile) • 8b4b2dd0e3ca37ed268847ee5c745201027ef939 • ios            • iOS 14.7.1
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by rymesaint** [comment] 2021-08-18 05:01
8.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[        ] 8.3.0 - [Firebase/Analytics][I-ACS025036] App Delegate Proxy is disabled
[  +10 ms] 8.3.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
[  +10 ms] 8.3.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
[        ] 8.3.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
[  +46 ms] [VERBOSE-2:shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[        ] [VERBOSE-2:dart_isolate.cc(170)] Could not prepare isolate.
[        ] [VERBOSE-2:runtime_controller.cc(382)] Could not create root isolate.
[        ] [VERBOSE-2:shell.cc(571)] Could not launch engine with configuration.
[   +8 ms] Observatory URL on device: http://127.0.0.1:53332/

Forwarded port ForwardedPort HOST:57031 to DEVICE:53332
[        ] Forwarded host port 57031 to device port 53332 for Observatory
[   +5 ms] Caching compiled dill
[ +119 ms] Connecting to service protocol: http://127.0.0.1:57031/
[ +184 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:57031/.
[  +69 ms] DDS is listening at http://127.0.0.1:57034/JedQqwtZ4wM=/.

**Comment by TahaTesser** [comment] 2021-08-18 08:09
Hi @rymesaint 
Thanks for filing the issue

> flutter clean or recreate ios folder using flutter create . did not help, i'm running out option

Instead of cleaning an existing project or creating an ios folder, can you please try to reproduce the issue using a new project without using third-party packages?

`flutter create myapp`
`cd myapp` (add your team id to run the app on physical device)
`flutter run -v > run.log` (this will copy your logs in a file, please drop this file in the comments below)

Thank you

**Comment by rymesaint** [comment] 2021-08-18 08:27
still blank with new project without any third party packages
[run.log](https://github.com/flutter/flutter/files/7005735/run.log)

**Comment by TahaTesser** [comment] 2021-08-18 11:32
Hi @rymesaint 
I just tried a physical device with `iOS 14.7.1` and it runs fine when new or exisitng project on the latest `stable` and `master` channels

### Logs
[run.log](https://github.com/flutter/flutter/files/7006817/run.log)

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.7.1
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.130, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.130 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d83fba1a22 (4 hours ago), 2021-08-18 03:02:04 -0400
    • Engine revision a27da3eeb6
    • Dart version 2.15.0 (build 2.15.0-24.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.7.1 18G82
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

```

</details>



Your issue looks similar to https://github.com/flutter/flutter/issues/67222

**Comment by MateusHBR** [comment] 2021-08-18 14:09
here is happening the same...
all member of my team too.

**Comment by MateusHBR** [comment] 2021-08-18 14:11
A workaround that works here is running on the xcode but you do not have the power of hot reload.

**Comment by rymesaint** [comment] 2021-08-18 14:16
> Hi @rymesaint
> I just tried a physical device with `iOS 14.7.1` and it runs fine when new or exisitng project on the latest `stable` and `master` channels
> 
> ### Logs
> [run.log](https://github.com/flutter/flutter/files/7006817/run.log)
> 
> flutter doctor -v
> Your issue looks similar to #67222

deleting flutter_tools.stamp did not work, using new download from flutter.dev its work only using xcode with terminal still the same error

**Comment by TahaTesser** [comment] 2021-08-18 15:15
Hi @rymesaint 
I just tried again, I still can't reproduce on a smaller app, when loading Flutter Gallery, which is much bigger, still doesn't get stuck, and only a blank page for a short time which has been there before 

On stable channel

https://user-images.githubusercontent.com/48603081/129923720-093f9be4-c76f-4527-9e40-cce33fcfccc8.mov



On master channel

https://user-images.githubusercontent.com/48603081/129923762-135a5d9d-6b1e-4f11-a26e-5226e33b03bf.MP4




Does this something happen if you wait few seconds on the blank screen? App closes or stays as it is?

**Comment by daniloapr** [comment] 2021-08-18 16:11
> Does this something happen if you wait few seconds on the blank screen? App closes or stays as it is?

I am having the same issue on iPhone with iOS 14.7.1. I just created a new empty project and tried to run it from Xcode, and a white screen appears on the device and stays there forever. This is the log on Xcode's terminal:

```
2021-08-18 12:39:52.752284-0300 Runner[598:57834] Metal API Validation Enabled
2021-08-18 12:39:52.859326-0300 Runner[598:57834] Warning: Unable to create restoration in progress marker file
2021-08-18 12:39:52.880041-0300 Runner[598:58099] [VERBOSE-2:shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
2021-08-18 12:39:52.880256-0300 Runner[598:58099] [VERBOSE-2:dart_isolate.cc(170)] Could not prepare isolate.
2021-08-18 12:39:52.881257-0300 Runner[598:58099] [VERBOSE-2:runtime_controller.cc(382)] Could not create root isolate.
2021-08-18 12:39:52.881453-0300 Runner[598:58099] [VERBOSE-2:shell.cc(571)] Could not launch engine with configuration.
2021-08-18 12:39:52.937794-0300 Runner[598:58113] flutter: Observatory listening on http://127.0.0.1:56483/AtRT5SAt0vA=/
```

From VSCode, running `flutter run`, I get the following output:
```
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3,6s
Xcode build done.                                            7,9s
(lldb) 2021-08-18 13:08:44.148257-0300 Runner[634:67422] [VERBOSE-2:shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:dart_isolate.cc(170)] Could not prepare isolate.             
[VERBOSE-2:runtime_controller.cc(382)] Could not create root isolate.   
[VERBOSE-2:shell.cc(571)] Could not launch engine with configuration.   
Installing and launching...                                         9,2s
```

Although it says `Installing and launching`, it just keeps on the white screen. It works normally on Simulator with iOS 14.5.

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
[✓] VS Code (version 1.59.0)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment] 2021-08-18 17:32
`Invalid kernel binary format version.` generally means there's a mismatch between the version of Flutter used to build the app, and the dart VM version.  Or something else in the artifacts cache is corrupted.

> using new download from flutter.dev its work only using xcode with terminal still the same error

@rymesaint You mean you deleted your Flutter cache, downloaded it again from the website, and still see the same error?

@MateusHBR @daniloapr can we get your `flutter doctor -v`?

> A workaround that worked here is running on the xcode but you do not have the power of hot reload.

@MateusHBR you only see it from the terminal, not from Xcode?

For anyone reproducing this, can you zip up and attach your entire project directory?  This will include your actual app, so you may want to reproduce with a newly created `flutter create`d app.

**Comment by ristiisa** [comment] 2021-08-18 19:11
> For anyone reproducing this, can you zip up and attach your entire project directory? This will include your actual app, so you may want to reproduce with a newly created `flutter create`d app.

https://wetransfer.com/downloads/f40ce2c9dc3913c2941a1ca3bb6149a420210818190534/9769a3deb4b9be1afcc64505c1d9132920210818190554/d1516c

I changed branch to master and back to stable.

**Comment by jmagman** [comment] 2021-08-18 19:44
@ristiisa Can you just attach the zip to GitHub?  What's your `flutter doctor -v`?

**Comment by ristiisa** [comment] 2021-08-18 20:18
> @ristiisa Can you just attach the zip to GitHub? What's your `flutter doctor -v`?

The folder is 160MB, github shows me an error(I did not crop it, that is the entire message):
<img width="161" alt="Screenshot 2021-08-18 at 23 02 51" src="https://user-images.githubusercontent.com/514571/129964468-bc55150a-4456-42a4-afa7-d6bd69d1f690.png">

What I interpret as "file too large".

I can solve the issue with deleting flutter folder and downloading the latest stable pack, but the problem is back after switching to master.

`Flutter 2.5.0-7.0.pre.139` was on the master branch I switched to.

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)
```

**Comment by jmagman** [comment] 2021-08-18 20:42
@ristiisa The wetransfer link doesn't open for me, can you share it another way?
That `flutter doctor` output is missing `-v`

**Comment by MateusHBR** [comment] 2021-08-18 21:39
> `Invalid kernel binary format version.` generally means there's a mismatch between the version of Flutter used to build the app, and the dart VM version. Or something else in the artifacts cache is corrupted.
> 
> > using new download from flutter.dev its work only using xcode with terminal still the same error
> 
> @rymesaint You mean you deleted your Flutter cache, downloaded it again from the website, and still see the same error?
> 
> @MateusHBR @daniloapr can we get your `flutter doctor -v`?
> 
> > A workaround that worked here is running on the xcode but you do not have the power of hot reload.
> 
> @MateusHBR you only see it from the terminal, not from Xcode?
> 
> For anyone reproducing this, can you zip up and attach your entire project directory? This will include your actual app, so you may want to reproduce with a newly created `flutter create`d app.

i saw the problem on Vscode and terminal. In xcode it works fine.

A solution that i found is run the project once on xcode, stop xcode running, after that try run on terminal or vscode and the problem got solved.

Flutter version:
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

flutter foctor -v:
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale pt-BR)
    • Flutter version 2.2.3 at /Users/mateusramalho/development/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mateusramalho/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
```

**Comment by jmagman** [comment] 2021-08-18 23:46
@MateusHBR

> For anyone reproducing this, can you zip up and attach your entire project directory? This will include your actual app, so you may want to reproduce with a newly created `flutter create`d app.

**Comment by jmagman** [comment] 2021-08-19 01:52
I'm able to reproduce this by downgrading from any other channel to stable.

On stable 2.2.3 downloaded from the website `bin/cache/artifacts/engine/ios/Flutter.xcframework` contains:
```
ios-armv7_arm64
ios-x86_64-simulator
```
However, when you downgrade from any other channel to stable it instead contains:
```
ios-arm64_armv7
ios-arm64_x86_64-simulator
ios-armv7_arm64
ios-x86_64-simulator
```
It contains the newer `ios-arm64_x86_64-simulator` from https://github.com/flutter/flutter/pull/85642 in 2.4.0-4.0.pre, and it contains the newer Xcode 12 style `ios-arm64_armv7` https://github.com/flutter/infra/pull/473.

Sure enough I can see the Flutter.framework Info.plist `FlutterEngine` being embedded in the app does not match the engine hash from stable 2.2.3.  And when I `rm -rf bin/cache/artifacts/engine/ios*` and then `flutter clean` it doesn't reproduce.

Another version of old cache files not being cleaned up.

### Steps to reproduce
```
$ cd path/to/flutter/sdk
$ rm -rf bin/cache/artifacts/engine/ios*
$ git checkout 2.5.0-1.0.pre
$ cd ~/Desktop
$ flutter create bug
$ cd bug
$ flutter run
...
An Observatory debugger and profiler on iPad is available at
```

```
$ cd path/to/flutter/sdk
$ ls bin/cache/artifacts/engine/ios/Flutter.xcframework
Info.plist                 ios-arm64_armv7            ios-arm64_x86_64-simulator
$ git checkout 2.2.3
$ flutter precache --no-web --no-linux --no-windows --no-macos --no-fuchsia
$ ls bin/cache/artifacts/engine/ios/Flutter.xcframework
Info.plist                 ios-arm64_x86_64-simulator ios-x86_64-simulator
ios-arm64_armv7            ios-armv7_arm64
$ cd ~/Desktop/bug
$ flutter clean
$ flutter run
...
[VERBOSE-2:shell.cc(93)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:dart_isolate.cc(170)] Could not prepare isolate.
[VERBOSE-2:runtime_controller.cc(382)] Could not create root isolate.
[VERBOSE-2:shell.cc(576)] Could not launch engine with configuration.
```

**Comment by jmagman** [comment] 2021-08-19 01:59
The stale artifacts problem was fixed by https://github.com/flutter/flutter/pull/85075 available on 2.4.0-0.0.pre.

**Comment by jmagman** [comment] 2021-08-19 02:04
> ### Workaround
> ```
> $ rm -rf path/to/flutter/sdk/bin/cache/artifacts/engine/ios*
> $ flutter clean
> $ flutter run
> ```

@MateusHBR @rymesaint @daniloapr Can you confirm this workaround works for you?

**Comment by rymesaint** [comment] 2021-08-19 02:45
> > ### Workaround
> > ```
> > $ rm -rf path/to/flutter/sdk/bin/cache/artifacts/engine/ios*
> > $ flutter clean
> > $ flutter run
> > ```
> 
> @MateusHBR @rymesaint @daniloapr Can you confirm this workaround works for you?

ok this one solve the problem thanks

**Comment by ristiisa** [comment] 2021-08-19 05:50
> @ristiisa The wetransfer link doesn't open for me, can you share it another way?

https://drive.google.com/file/d/1_Eh305syqpAHbKJILHy33srA8y4Sa2Qm/view?usp=sharing

> That `flutter doctor` output is missing `-v`

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/silver/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/silver/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 92.0.4515.131

```

**Comment by jmagman** [comment] 2021-08-19 16:40
Closing as duplicate of https://github.com/flutter/flutter/issues/85062.  The workaround is to stay on the beta channel until the next stable, or to run the following after switching to 2.2.3:
```
$ rm -rf path/to/flutter/sdk/bin/cache/artifacts/engine/ios*
$ flutter clean
$ flutter run
```

**Closed by jmagman** 2021-08-19 16:40 UTC
Labels: platform-ios, tool, customer: crowd, passed first triage
