### ISSUE TITLE
[Feature Request] Markers and animations in google_maps_flutter 

### ISSUE THREAD

**Issue by sajphon** [flutter/flutter#31717] opened 2019-04-27 03:30 UTC
It would be awesome, if animated markers and possibility to animate maraker position updates (easing in between two marker position updates) were added. 

As of now I didn't find any way to efficiently ease between two marker positions (besides being one position update behind and updating the position in x steps in between manually in a loop).

**Comment by stuartmorgan** [comment] 2023-07-20 18:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/33430 since that's where most of the discussion and votes ended up.

**Closed by stuartmorgan** 2023-07-20 18:38 UTC
Labels: c: new feature, a: animation, p: maps, package, c: proposal, team-ecosystem, P3, triaged-ecosystem
