### ISSUE TITLE
An app with just android_alarm_manager fails to build

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#27441] opened 2019-02-02 21:03 UTC
I've created a new app, and added `android_alarm_manager` to its dependencies, and added needed lines in `AndroidManifest.xml`, and I'm getting this:

```
Launching lib/main.dart on Moto G Play in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:54: error: unexpected element <service> found in <manifest><application><activity>.
  /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:59: error: unexpected element <receiver> found in <manifest><application><activity>.

  Command: /home/gabriel/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/55a52b25bffd06ddbd65193b513e1923/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/gabriel/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/gabriel/Projects/notificaciones/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/gabriel/Projects/notificaciones/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.example.notificaciones\
          -0\
          apk\
          --output-text-symbols\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
  Output:  /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:54: AAPT: error: unexpected element <service> found in <manifest><application><activity>.

  /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml:59: AAPT: error: unexpected element <receiver> found in <manifest><application><activity>.

  Command: /home/gabriel/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/55a52b25bffd06ddbd65193b513e1923/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/gabriel/Android/Sdk/platforms/android-27/android.jar\
          --manifest\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/home/gabriel/Projects/notificaciones/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /home/gabriel/Projects/notificaciones/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.example.notificaciones\
          -0\
          apk\
          --output-text-symbols\
          /home/gabriel/Projects/notificaciones/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 11s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by gabrc52** [comment] 2019-02-02 21:06
The package's example builds successfully

**Comment by wouterhardeman** [comment] 2019-02-02 21:09
Can you post the output of `flutter doctor -v`?

You probably need to update the `targetSdkVersion` and `compileSdkVersion` to 28 in `android/app/build.gradle`. And possibly need to migrate to AndroidX.

**Comment by gabrc52** [comment] 2019-02-02 22:05
Output of `flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.1.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.8 at /home/gabriel/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/gabriel/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_192-b26)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /home/gabriel/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.3684.101
    • Flutter plugin version 31.2.2
    • Dart plugin version 182.3569.4

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /home/gabriel/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/181.5087.20
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[✓] Connected device (1 available)
    • Moto G Play • 192.168.1.72:5555 • android-arm • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
```

**Comment by wouterhardeman** [comment] 2019-02-02 22:12
The problem is in the `AndroidManifest.xml` file. The `<service>` and `<receiver>` you need to add need to be inside `<application>`, not `<activity>`. See: https://developer.android.com/guide/topics/manifest/service-element

**Comment by gabrc52** [comment] 2019-02-02 22:20
Thanks, after updating `targetSdkVersion` and `compileSdkVersion` to 28 it's building successfully.

This should be added to the documentation.

**Comment by mklim** [comment] 2019-02-06 02:31
Closing as a duplicate of #27106.

**Closed by mklim** 2019-02-06 02:31 UTC
