### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by maks** [flutter/flutter#108852] opened 2022-08-03 02:12 UTC
## Command
```
flutter run --machine --start-paused --dart-define PREVIEW_READER_MODE=true -d web-server --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-server-debug-injected-client-protocol ws --devtools-server-address http://127.0.0.1:9100/ --target lib/main_preview.dart
```

## Steps to Reproduce
This is exactly the same as #94193 except the bot had already closed and locked it.

In VSCode use the following launch config:
```
{
      "name": "My Web App",
      "request": "launch",
      "type": "dart",
      "deviceId": "web-server",
      "program": "lib/main.dart",
      "toolArgs": [
        "--dart-define",
        "MY_MODE=true"
      ]
    },
```
And run the launch config. At least half the time Flutter command crashes with the error below, including the url text I used to open this issue.

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:696:16)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04 LTS 5.15.0-41-generic, locale en_AU.UTF-8)
    • Flutter version 3.0.5 at [redacted]fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at [redacted]/apps/android
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at:[redacted]/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at [redacted]/apps/android-studio
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.69.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-3.4.0
cloud_firestore_web-2.8.0
cloud_functions-3.3.3
cloud_functions_web-4.3.1
connectivity_plus-2.3.6
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.3
connectivity_plus_windows-1.2.2
device_info_plus-4.0.1
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-3.0.1
firebase_auth-3.5.0
firebase_auth_web-4.1.0
firebase_core-1.20.0
firebase_core_web-1.7.1
firebase_dynamic_links-4.3.3
flutter_secure_storage-5.0.2
flutter_secure_storage_linux-1.1.0
flutter_secure_storage_macos-1.1.0
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
google_sign_in-5.4.0
google_sign_in_android-6.0.1
google_sign_in_ios-5.4.0
google_sign_in_web-0.10.2
network_info_plus-2.1.3
network_info_plus_linux-1.1.2
network_info_plus_macos-1.3.0
network_info_plus_web-1.0.1
network_info_plus_windows-1.0.2
package_info_plus-1.4.3
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-2.0.0
path_provider-2.0.11
path_provider_android-2.0.16
path_provider_ios-2.0.10
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3
webview_flutter-3.0.4
webview_flutter_android-2.9.2
webview_flutter_wkwebview-2.9.1

**Comment by danagbemava-nc** [comment] 2022-08-03 07:44
Hi @maks, I believe this is a duplicate of https://github.com/flutter/flutter/issues/96988 albeit with different reproduction steps. 

Since the crash logs are the same, I'll be closing this as a duplicate of the linked issue. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-08-03 07:44 UTC
Labels: in triage
