### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software., errno = 225

### ISSUE THREAD

**Issue by BQLCODE** [flutter/flutter#136877] opened 2023-10-19 10:24 UTC
## exception

FileSystemException: FileSystemException: Cannot open file, path = 'D:\Flutter\build\app\outputs\flutter-apk\app-release.apk' (OS Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
, errno = 225)

```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5      _calculateSha (package:flutter_tools/src/android/gradle.dart:943:32)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:593:36)
<asynchronous suspension>
#7      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
<asynchronous suspension>
#8      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.22621.2428], locale ar-SY)
    [32m•[39m Flutter version 3.13.8 on channel stable at d:\flutterSdk
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 6c4930c4ac (18 hours ago), 2023-10-18 10:57:55 -0500
    [32m•[39m Engine revision 767d8c75e8
    [32m•[39m Dart version 3.1.4
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\AndroidSDK
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.6.33829.357
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m SM G532F (mobile) • 42001e79fe01c305 • android-arm    • Android 6.0.1 (API 23)
    [32m•[39m Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    [32m•[39m Chrome (web)      • chrome           • web-javascript • Google Chrome 118.0.5993.72
    [32m•[39m Edge (web)        • edge             • web-javascript • Microsoft Edge 118.0.2088.46

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```
https://stackoverflow.com/questions/77294420/flutter-contains-troj-gen

**Comment by dam-ease** [comment] 2023-10-19 10:30
Closing as duplicate of https://github.com/flutter/flutter/issues/61997

**Closed by dam-ease** 2023-10-19 10:30 UTC
Labels: in triage
