### ISSUE TITLE
Profile apk generated by `flutter run --profile` on emulator, fails to install on physical device 

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#81378] opened 2021-04-28 12:18 UTC
## Steps to Reproduce

1. Create new flutter app
2. Run it on android simulator with additional arguments `--profile` in run configurations from android studio  
3. find the apk under folder /build/app/outputs/flutter-apk/app-profile.apk
4. install that manualy on  samsung device running on android 8 
5. i got following result.

<img src="https://user-images.githubusercontent.com/12496655/116402115-a50b6b00-a849-11eb-8454-00ee9fbf103f.png" height="450" />	|

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/userA/Library/Android/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/userA/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-04-28 14:55
Hi @mehtahardikr 
Thanks for filing the issue. 
When I run profile build for emulator then load the APK on a physical, it crashes (same as you) on Oneplus 8.
However do the same for physical device only, `flutter run --profile -v` on one plus 8, then copy profile apk, it installs successfuly 
My guess is it is building APK specific to architecture, hence it's not compatible if you switch to a physical device from an emulator. This makes me think it's not a bug. 

Can you please explain why you need to load APK generated from `flutter run --profile` from emulator to physical device?

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • IN2011 (mobile)                       • c9d8ee0c      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.928]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.145, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.145 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1ad5cd9ee (5 hours ago), 2021-04-28 06:14:02 -0400
    • Engine revision adf2e24993
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • IN2011 (mobile)                       • c9d8ee0c      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.928]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```
		
</details>

**Comment by jonahwilliams** [comment] 2021-04-28 15:09
You should be able to see why it is failing by looking at the logcat. By default, flutter build apk --profile will build a fat apk containing all target architectures, but flutter run will only generate an apk for the targeted device's architecture. This could explain why it isn't working on your emulator.

**Comment by mehtahardikr** [comment] 2021-04-29 03:57
@TahaTesser  : I need to distribute apk for test via testfairy and that build is compact in size. you are saying that i have to generate fat apk which is big in size as expected. If one architracture has 20 mb in size then why fat apk has 35 m.b. in size.
it its generates fat apk then why we use it as native already provide compact size apk which is good to distribute as well. even .ipa files are ~19 to ~20 mb in size while generate for all ios devices.

**Comment by jonahwilliams** [comment] 2021-04-29 04:34
You need to generate an APK that matches the target platform and architecture you are distributing for. Closing because this is not a bug

**Closed by jonahwilliams** 2021-04-29 04:34 UTC
Labels: in triage

**Comment by mehtahardikr** [comment] 2021-04-29 06:08
@jonahwilliams  : Please i am targetting all devices android 6 + so want me to generate multiple apks for all devices ?

**Comment by TahaTesser** [comment] 2021-04-29 06:23
@mehtahardikr 
Please use `flutter build apk --split-per-abi`  with profile or release and generate APKs that matches target platform and architecture

**Comment by mehtahardikr** [comment] 2021-04-29 06:29
@TahaTesser  : so there is no other option for generate small size apk ? its generates  almost double size of apk.
