### ISSUE TITLE
[web]: <Looks like Icon widget isn't working>

### ISSUE THREAD

**Issue by Jayanth-L** [flutter/flutter#32368] opened 2019-05-09 05:22 UTC
On Flutter web preview the Icon widget i.e; Icon(Icons.home) isn't rendering properly
On Firefox and Chromium it looks like some kind of box.

Host OS: Arch Linux [5.0.10-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 27 20:06:45 UTC 2019 x86_64 GNU/Linux]

**Comment by anondev32** [comment] 2019-05-09 10:19
It's already implemented here.

https://github.com/flutter/flutter_web/tree/master/examples/custom_fonts

**Comment by icatalud** [comment] 2019-07-13 03:27
They should come by default when you create a new web project, just like Flutter.

**Comment by BondarenkoStas** [comment] 2019-10-14 20:21
That's the migration guide https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md#webassetsfontmanifestjson-optional.
Closing as a duplicate of #32245

**Closed by BondarenkoStas** 2019-10-14 20:21 UTC

**Comment by jonahwilliams** [comment] 2019-10-14 20:24
@BondarenkoStas that documentation is out of date. The only up to date web documentation is flutter.dev/web
