### ISSUE TITLE
Hava an error here

### ISSUE THREAD

**Issue by kadoyatsukasa** [flutter/flutter#33912] opened 2019-06-05 11:38 UTC
When i try to run my app on the android emulator,the program end up  with this error
```
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:61864/X87Wkx07T08=/ws
Exited (sigterm)
``` 

why?and how to fix up it???thanks

**Comment by DanTup** [comment] 2019-06-05 13:04
Did you create an Android emulator using Q level API?

If so, I think this is a dupe of #33050. Try creating one using API level 28 to see if that solves the issue until there's a fix.

**Comment by kadoyatsukasa** [comment] 2019-06-06 02:57
thanks ， problem has been solved now

**Closed** 2019-06-06 04:21 UTC
