### ISSUE TITLE
Need better instructions to create Standalone .apk file

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#124] opened 2015-11-09 21:14 UTC
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [afandria](https://github.com/afandria)**
_Tuesday Aug 11, 2015 at 18:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/559_

----

[Building a Standalone APK](https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/README.md#building-a-standalone-apk) instructions are not clear enough.

It has been inconvenient to only be able to start my Sky app via `sky_tool`, so I wanted to build my own APK. Unfortunately, the link to the stocks/example does not have a `README.md` for how to build it. It appears that the `BUILD.gn`, `sky.yaml`, and `apk/AndroidManifest.xml` files are important to the process, but I am not sure what command(s) are needed to produce the APK.

**Comment by abarth** [comment] 2015-11-10 22:25
Duplicate of #45

**Closed by abarth** 2015-11-10 22:25 UTC
Labels: affects: dev experience, customer: croupier
