### ISSUE TITLE
The newly created project is given a bunch of warnings, as shown below:

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90755] opened 2021-09-26 11:54 UTC
The newly created project is given a bunch of warnings, as shown below:
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

The newly created project is given a bunch of warnings, as shown below:
![image](https://user-images.githubusercontent.com/91245043/134806643-ba62e864-3edd-4837-8e2f-ad6484f12c3b.png)

**Comment by danagbemava-nc** [comment] 2021-09-27 08:28
Hi @gionlime, 

There is already an open issue tracking this https://github.com/flutter/flutter/issues/87464.

Kindly follow up there for more information. 

Closing as duplicate of #87464

**Closed by danagbemava-nc** 2021-09-27 08:28 UTC
Labels: in triage
