### ISSUE TITLE
Flutter web "TypeError: firebase.firestore is not a function" when hosting

### ISSUE THREAD

**Issue by blbhargav** [flutter/flutter#56267] opened 2020-05-04 04:16 UTC
I am using firestore in flutter web. Everything is working fine in local i.e,Android studio chrome. But when I hosted in firebase hosting (firebase serve) it's not working. The browser console giving error.
 
`
Uncaught TypeError: firebase.firestore is not a function
    at Object.arO (top_level.dart:125)
    at cloud_firestore_web.dart:26
    at alN.a (async_patch.dart:308)
    at alN.$2 (async_patch.dart:333)
    at Object.N (async_patch.dart:238)
    at Object.T8 (main.dart:8)
    at js_helper.dart:3221
    at js_helper.dart:3221
    at dartProgram (js_helper.dart:3221)
    at js_helper.dart:3221
`

flutter doctor -v 

`[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Linux, locale en_IN)
    • Flutter version 1.17.0-3.4.pre at /home/bhargav/Android/flutter
    • Framework revision e6b34c2b5c (34 hours ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/bhargav/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Redmi Note 7 Pro • a682ccfc   • android-arm64  • Android 9 (API 28)
    • Chrome           • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server       • web-server • web-javascript • Flutter Tools

• No issues found!
`
Any help please. 
https://stackoverflow.com/q/61584732/9103369

**Comment by iapicca** [comment] 2020-05-04 06:35
Hi @blbhargav 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-04 06:35 UTC
