### ISSUE TITLE
[MacOS] flutter not detecting mouse hover woking some time some times displays error

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#107063] opened 2022-07-04 10:46 UTC
<details>
<summary> Sample Code </summary>

```
void main() {
       runApp(const MyApp());
  }
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
    
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MacMainScreen(),
    );
  }
}```

```class MacMainScreen extends StatefulWidget {
  const MacMainScreen({Key? key}) : super(key: key);

  @override
  State<MacMainScreen> createState() => _MacMainScreenState();
}

class _MacMainScreenState extends State<MacMainScreen> {
  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    return material.Material(
      color: material.Colors.transparent,
      child: CupertinoPageScaffold(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: const [
            Text(
              "My Documents",
              style: TextStyle(color: CupertinoColors.black, fontSize: 20),
            ),
            SizedBox(
              height: 20,
            ),
           
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary> Flutter doctor</summary>

flutter doctor
       Doctor summary (to see all details, run flutter doctor -v):
        [✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-PK)
        [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
        [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
        [✓] Chrome - develop for the web
          [✓] Android Studio (version 2021.2)
          [✓] VS Code (version 1.68.1)
             [✓] Connected device (2 available)
              ! Error: Mac’s iPhone is not connected. Xcode will continue when Mac’s iPhone is connected. (code -13)
              [✓] HTTP Host Availability```

• No issues found!
</details>
<details>
<summary> Error Showing</summary>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 206 pos 12: '!_debugDuringDeviceUpdate': is not true.
package:flutter/…/rendering/mouse_tracker.dart:206
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      MouseTracker._deviceUpdatePhase
package:flutter/…/rendering/mouse_tracker.dart:206
#3      MouseTracker.updateWithEvent.<anonymous closure>
package:flutter/…/rendering/mouse_tracker.dart:317
#4      MouseTracker._monitorMouseConnection
package:flutter/…/rendering/mouse_tracker.dart:195
#5      MouseTracker.updateWithEvent
package:flutter/…/rendering/mouse_tracker.dart:316
#6      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:321
#7      GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:380
#8      GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:344
#9      GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:302
#10     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:285
#11     _rootRunUnary (dart:async/zone.dart:1442:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#14     _invoke1 (dart:ui/hooks.dart:170:10)
#15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 206 pos 12: '!_debugDuringDeviceUpdate': is not true

```
</details>

https://user-images.githubusercontent.com/71745182/177139538-fd17cb73-7bab-4656-ab5a-9178fb89791f.mov

**Comment by alihassan143** [comment] 2022-07-04 12:32
This error did not appear all time its appear some time when you run the project if you restart the same project again when the error appear after restarting the project whole error disappear

**Comment by exaby73** [comment] 2022-07-04 13:54
I am unable to reproduce this issue, though I will keep it open for insights from the team

**Comment by alihassan143** [comment] 2022-07-04 15:40
ok thanks

**Comment by alihassan143** [comment] 2022-07-14 06:13
@gspencergoog  this error did not appear all the time when you run the same project multiple time than it will start showing you this error this error did not appear every time when the error appear you just hot restart the app error disappear automatically

**Comment by gspencergoog** [comment] 2022-07-14 18:27
Hi @alihassan143, I'm sorry, if you can't provide a simpler reproduction case, then unfortunately we will have to close this issue since we can't make any progress on it.

If you do find a better way to reproduce this issue, please feel free to open a new issue with the details.

**Closed by gspencergoog** 2022-07-14 18:27 UTC
Labels: severe: crash, framework, platform-mac, a: desktop, r: invalid, a: mouse, P4
