### ISSUE TITLE
Flutter run gets stuck on "waiting for observatory port"

### ISSUE THREAD

**Issue by photonfighter** [flutter/flutter#51269] opened 2020-02-22 18:20 UTC
## Steps to Reproduce

Using Flutter v1.12.13+hotfix.8 on channel stable. Issue appears to be OS independent; tried on both Ubuntu 18.04 and Windows. Note that running on CLI and Android Studio allows the app to actually start and be used, but not in VS Code. Hot reload/restart was not working in any of these cases; Android Studio had the buttons greyed out.

This is all being tested on an LG VS835 running on API 24 (Nougat 7.0). 

1. Install Flutter on Windows/Linux by downloading the zip and extracting
2. Use ```flutter create testapp``` without changing any code/settings.
3. run ```flutter run``` from CLI, or use VS Code or Android Studio to run
4. App appears to install, but only a white screen appears, and ```flutter run --verbose``` gives "waiting for observatory port to be available" regardless of if it's running from CLI, VS Code, or Android studio.

## Things Tried

1. Uninstalling/reinstalling Flutter
2. Switching to channel master and back to stable
3. Turning off firewall (Windows Defender)
4. Running ```flutter clean```
5. Factory resetting VS835
6. Force stopping app and clearing caches, then resinstalling on VS835

### Note
Works on clean Pixel 2 API 28 AVD. However, VS835 has been my main development device for over a year now, and am only just now having issues with it.

## Logs (Windows)

```
flutter run --verbose
[  +25 ms] executing: [C:\Users\cadet\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\Users\cadet\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +73 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [C:\Users\cadet\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Users\cadet\flutter\] git ls-remote --get-url origin
[  +71 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +132 ms] executing: [C:\Users\cadet\flutter\] git rev-parse --abbrev-ref HEAD
[  +98 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +105 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +46 ms] Exit code 0 from: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           VS8355POV6LJFEQ85CY    device product:mph1_vzw model:VS835 device:mph1 transport_id:1
[  +15 ms] C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell getprop
[ +157 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +142 ms] Generating
C:\Users\cadet\ws\testapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +29 ms] ro.hardware = mph1
[   +1 ms] ro.build.characteristics = default
[  +50 ms] Launching lib\main.dart on VS835 in debug mode...
[   +8 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree
C:\Users\cadet\ws\testapp\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +35 ms] Exit code 0 from: C:\Users\cadet\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree
C:\Users\cadet\ws\testapp\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.testapp" (Raw: "com.example.testapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="testapp" (Raw: "testapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.testapp.MainActivity" (Raw:
                   "com.example.testapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +8 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell -x
logcat -v time -t 1
[ +156 ms] Exit code 0 from: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY
shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           02-22 13:06:56.223 I/wmt_launcher(  391): fw dynamic ctrl flag has been set
[   +6 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +1 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY logcat
-v time -T 02-22 13:06:56.223
[  +85 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +62 ms] Building APK
[  +17 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from C:\Users\cadet\ws\testapp\android\gradlew.bat.
[   +8 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +120 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +4 ms] executing: [C:\Users\cadet\ws\testapp\android\] C:\Users\cadet\ws\testapp\android\gradlew.bat
-Pverbose=true -Ptarget=C:\Users\cadet\ws\testapp\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[ +626 ms] Welcome to Gradle 5.6.2!
[   +4 ms] Here are the highlights of this release:
[   +1 ms]  - Incremental Groovy compilation
[   +1 ms]  - Groovy compile avoidance
[   +1 ms]  - Test fixtures for Java projects
[   +1 ms]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[ +877 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[  +12 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +174 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +104 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +3 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[  +85 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +5 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +2 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +86 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +8 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[   +1 ms] > Task :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 1s
[        ] 30 actionable tasks: 3 executed, 27 up-to-date
[ +527 ms] Running Gradle task 'assembleDebug'... (completed in 2.7s)
[  +36 ms] calculateSha: LocalDirectory: 'C:\Users\cadet\ws\testapp\build\app\outputs\apk'/app.apk
[  +53 ms] calculateSha: reading file took 50us
[ +588 ms] calculateSha: computing sha took 586us
[   +7 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +4 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree
C:\Users\cadet\ws\testapp\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +61 ms] Exit code 0 from: C:\Users\cadet\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree
C:\Users\cadet\ws\testapp\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.testapp" (Raw: "com.example.testapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="testapp" (Raw: "testapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.testapp.MainActivity" (Raw:
                   "com.example.testapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +3 ms] Stopping app 'app.apk' on VS835.
[   +1 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell am
force-stop com.example.testapp
[ +965 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell pm
list packages com.example.testapp
[+1232 ms] package:com.example.testapp
[   +4 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell
cat /data/local/tmp/sky.com.example.testapp.sha1
[  +65 ms] 761f181f2b713983e68bf9afa07ddb5056c89fd5
[   +1 ms] Latest build already installed.
[   +1 ms] VS835 startApp
[   +2 ms] executing: C:\Users\cadet\AppData\Local\Android\sdk\platform-tools\adb.exe -s VS8355POV6LJFEQ85CY shell am
start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling
true --ez enable-checked-mode true --ez verify-entry-points true com.example.testapp/com.example.testapp.MainActivity
[+1011 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.testapp/.MainActivity (has
extras) }
[   +2 ms] Waiting for observatory port to be available...
```

```
PS C:\Users\cadet\ws\testapp> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\cadet\flutter
    • Framework revision 0b8abb4724 (11 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\cadet\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\cadet\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • VS835 • VS8355POV6LJFEQ85CY • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-02-24 09:28
Hi @photonfighter 
Duplicate of [#33214](https://github.com/flutter/flutter/issues/33214)
Could you please try this possible [Solution](https://github.com/flutter/flutter/issues/33214#issuecomment-568733832)
Thank you

**Closed by TahaTesser** 2020-02-24 09:28 UTC

**Comment by Viswanth1038** [comment] 2020-07-31 12:03
I also had this issue.
In my case I had the release version installed and when running `flutter run` the debug version wouldn't install, so I removed the installed release version and ran again. It worked.

I'm on Manjaro Linux 20.0.3
Flutter 1.17.5

**Comment by Viswanth1038** [comment] 2020-07-31 12:07
> [   +1 ms] Latest build already installed.

See here 7th to last line in the logs

**Comment by Valentin-Seehausen** [comment] 2020-10-16 10:38
Still facing this issue on iOS.

**Comment by TahaTesser** [comment] 2020-10-16 12:11
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 175atsu** [comment] 2021-01-09 17:39
I also ran into the same bug when debugging on a terminal.

Solution
`adb uninstall [package name]`

**Comment by akramkun** [comment] 2021-01-25 17:42
i faced the same problem and fixed it by returning the @drawable/launch_background xml file to its default .

**Comment by abhinavsingh** [comment] 2021-05-31 21:27
> Hi @photonfighter
> Duplicate of [#33214](https://github.com/flutter/flutter/issues/33214)
> Could you please try this possible [Solution](https://github.com/flutter/flutter/issues/33214#issuecomment-568733832)
> Thank you

Unsure why is this duplicate of an Android use case.  For me, since past 2 weeks, this issue has creeped in out of no where.  

1. We are developing for iOS only.  
2. App behaves as expected with Xcode builds
3. Flutter run either manually, via VSCode and Android studio, fails everywhere
4. We ran `flutter run --verbose` and it clearly get stuck at "Waiting for observatory port" and then it crashes after timeout.

For iOS only workaround is to:

1) Run app using XCode
2. `flutter attach --debug-url "...< observatory url from XCode logs > .."`
