### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:FAILURE: Build failed with an exception.* What went wrong:Project 'app' not found in root project 'android'.* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 513ms Command: /Users/../Downloads/../android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by aalnazari** [flutter/flutter#59476] opened 2020-06-15 15:49 UTC
## Command
```
flutter build apk --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 513ms Command: /Users/macc/Downloads/mda_app 2/android/gradlew, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:277:57)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:73)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
```
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.4 19E287, locale en-SA)
    • Flutter version 1.20.0-1.0.pre.42 at /Users/macc/Downloads/delef/flutter
    • Framework revision 401690a64f (3 days ago), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macc/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 67826bdce54505760fe83b7ead70bdb5af6fe9f2
### Plugins
cloud_firestore-0.13.6
cloud_firestore_web-0.1.1+2
connectivity-0.4.8+6
connectivity_macos-0.1.0+2
firebase_analytics-5.0.15
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_messaging-6.0.16
flutter_local_notifications-1.4.4+1
flutter_plugin_android_lifecycle-1.0.6
flutter_youtube-2.0.0
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-0.5.28+1
local_auth-0.6.2+3
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
path_provider-1.6.10
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+9
shared_preferences_web-0.1.2+7
sqflite-1.3.1
trust_fall-1.0.4
url_launcher-5.4.10
url_launcher_macos-0.0.1+4
url_launcher_web-0.1.1+1
webview_flutter-0.3.22+1

**Comment by jonahwilliams** [comment] 2020-06-15 15:56
Duplicate of https://github.com/flutter/flutter/issues/59312

**Closed by jonahwilliams** 2020-06-15 15:56 UTC

**Comment by aalnazari** [comment] 2020-06-15 16:04
> .
