### ISSUE TITLE
Flutter channel unknown

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#48147] opened 2020-01-03 19:29 UTC
Already switched to channel stable, then installed version v1.9.1+hotfix.6 with `flutter version v1.9.1+hotfix.6` but channel still appears as unknown

```
AlfredoMBPro:apperto alfredo$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale es-AR)
    • Flutter version 1.9.1+hotfix.6 at /Users/alfredo/Desktop/flutter
    • Framework revision 68587a0916 (4 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone Alfredo • 00008020-001A03CE1161002E • ios • iOS 13.3

• No issues found!
AlfredoMBPro:apperto alfredo$ 
```

```
AlfredoMBPro:apperto alfredo$ flutter --version
Flutter 1.9.1+hotfix.6 • channel unknown • unknown source
Framework • revision 68587a0916 (4 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

```
AlfredoMBPro:apperto alfredo$ flutter channel
Flutter channels:
  beta
  dev
  master
  stable
```

**Comment by isadoraoliv** [comment] 2020-01-03 19:34
@quetool there seems to be something wrong with the installation of Flutter.
Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to fix it.

**Comment by quetool** [comment] 2020-01-03 19:37
Thanks @isadoraoliv, will try out...
In the meantime I did `flutter channel stable` then `flutter upgrade`

```
AlfredoMBPro:apperto alfredo$ flutter channel stable
Switching to flutter channel 'stable'...
git: Previous HEAD position was 68587a091 V1.9.1 hotfix
git: Switched to branch 'stable'
git: M  packages/flutter/lib/src/material/colors.dart
git: Your branch is up to date with 'origin/stable'.
AlfredoMBPro:apperto alfredo$ flutter upgrade
Downloading Dart SDK from Flutter engine 2994f7e1e682039464cb25e31a78b86a3c59b695...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200M  100  200M    0     0  12.0M      0  0:00:16  0:00:16 --:--:-- 12.0M
Building flutter tool...
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with --force.
AlfredoMBPro:apperto alfredo$ flutter upgrade --force
Upgrading Flutter from /Users/alfredo/Desktop/flutter...
Updating cf37c2cd0..27321ebba
 24 files changed, 651 insertions(+), 218 deletions(-)
Flutter is already up to date on channel stable
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
AlfredoMBPro:apperto alfredo$ 
```
and channel switched fine to stable

Then I did `flutter version 1.9.1+hotfix.6`
```
AlfredoMBPro:apperto alfredo$ flutter version 1.9.1+hotfix.6
Downloading package sky_engine...                                   0,7s
Downloading common tools...                                         1,5s
Downloading common tools...                                         1,3s
Downloading darwin-x64 tools...                                     4,9s
Switching Flutter to version 1.9.1+hotfix.6

Downloading engine...
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  263M    0 27595    0     0  64436      0  1:11:34 --:--:--  1:11:34 64324
  4  263M    4 10.5M    0     0  8261k      0  0:00:32  0:00:01  0:00:31 8261k
  8  263M    8 23.6M    0     0  10.2M      0  0:00:25  0:00:02  0:00:23 10.2M
 13  263M   13 36.7M    0     0  11.0M      0  0:00:23  0:00:03  0:00:20 11.0M
 18  263M   18 49.7M    0     0  11.5M      0  0:00:22  0:00:04  0:00:18 11.5M
 23  263M   23 62.8M    0     0  11.8M      0  0:00:22  0:00:05  0:00:17 12.8M
 28  263M   28 75.6M    0     0  11.9M      0  0:00:22  0:00:06  0:00:16 13.0M
 33  263M   33 88.7M    0     0  12.1M      0  0:00:21  0:00:07  0:00:14 13.0M
 38  263M   38  101M    0     0  12.2M      0  0:00:21  0:00:08  0:00:13 13.0M
 43  263M   43  114M    0     0  12.3M      0  0:00:21  0:00:09  0:00:12 13.0M
 48  263M   48  127M    0     0  12.3M      0  0:00:21  0:00:10  0:00:11 12.8M
 51  263M   51  137M    0     0  12.1M      0  0:00:21  0:00:11  0:00:10 12.2M
 56  263M   56  150M    0     0  12.1M      0  0:00:21  0:00:12  0:00:09 12.2M
 61  263M   61  163M    0     0  12.2M      0  0:00:21  0:00:13  0:00:08 12.2M
 66  263M   66  175M    0     0  12.2M      0  0:00:21  0:00:14  0:00:07 12.0M
 71  263M   71  187M    0     0  12.2M      0  0:00:21  0:00:15  0:00:06 12.0M
 75  263M   75  198M    0     0  12.1M      0  0:00:21  0:00:16  0:00:05 12.2M
 79  263M   79  210M    0     0  12.1M      0  0:00:21  0:00:17  0:00:04 12.0M
 84  263M   84  222M    0     0  12.1M      0  0:00:21  0:00:18  0:00:03 11.9M
 89  263M   89  235M    0     0  12.2M      0  0:00:21  0:00:19  0:00:02 12.1M
 94  263M   94  248M    0     0  12.2M      0  0:00:21  0:00:20  0:00:01 12.2M
 98  263M   98  260M    0     0  12.2M      0  0:00:21  0:00:21 --:--:-- 12.4M
100  263M  100  263M    0     0  12.2M      0  0:00:21  0:00:21 --:--:-- 12.5M
Building flutter tool...
Downloading package sky_engine...                                   0,8s
Downloading common tools...                                         1,3s
Downloading common tools...                                         1,3s
Downloading darwin-x64 tools...                                     3,5s

Flutter 1.9.1+hotfix.6 • channel unknown • unknown source
Framework • revision 68587a0916 (4 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.7.0

Running "flutter pub upgrade" in apperto...                        45,5s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale es-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
AlfredoMBPro:apperto alfredo$ 
```

But channel switched to unknown again...

**Comment by quetool** [comment] 2020-01-03 19:50
> @quetool there seems to be something wrong with the installation of Flutter.
> Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to fix it.

Didn´t solved my issue, instead of that i´ve got a lot of merge conflicts after git pull so I am now reinstalling flutter for good...

**Comment by quetool** [comment] 2020-01-03 20:16
I solved by downloading the SDK from https://flutter.dev/docs/development/tools/sdk/releases?tab=macos 🤷‍♂

**Comment by jmagman** [comment] 2020-01-03 21:55
Duplicate of https://github.com/flutter/flutter/issues/40950.

**Closed by jmagman** 2020-01-03 21:55 UTC

**Comment by zhanglijie5997** [comment] 2020-01-05 07:33
```
Flutter (Channel unknown, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B2106,
    locale zh-Hans-CN)  
```  I have the same problem as you,

**Comment by quetool** [comment] 2020-01-07 13:17
> Duplicate of #40950.

It seems different to me but ok...

**Comment by quetool** [comment] 2020-01-07 13:18
> ```
> Flutter (Channel unknown, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B2106,
>     locale zh-Hans-CN)  
> ```  I have the same problem as you, 
> ```

I do not upgrade to 1.12 yet but in order to solve to can do a clean reinstallation by downloading the SDK

**Comment by jmagman** [comment] 2020-01-07 21:23
> > Duplicate of #40950.
> 
> It seems different to me but ok...

It's the same underlying issue.  The channel is derived from the git branch you're on (master, stable, dev, beta), but `flutter version <>` checks out the repo in a detached HEAD state.

**Comment by kkuzvindiwana** [comment] 2020-03-09 15:56
I faced the same error ....Flutter (Channel unknown....) and I solved it by deleting the flutter sdk i.e the folder containing flutter 
and downloading the latest version on the official flutter website
