### ISSUE TITLE
Failed to start Flutter renderer: No GL implementation is available

### ISSUE THREAD

**Issue by amerchaabi** [flutter/flutter#91291] opened 2021-10-05 10:05 UTC
I create a simple "Hello Word" in flutter and enable web and linux platform to test is both,in chrome everything was ok and i see my first web app in flutter "Hello word",but in my desktop apps on Linux starting but not displaying anything and give me this message in terminal

```console
libEGL warning: MESA-LOADER: failed to open swrast: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1) (search paths /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri, suffix _dri)


** (app:22248): WARNING **: 05:45:50.289: Failed to start Flutter renderer: No GL implementation is available
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
```
and this is my hello word apps

```
mport 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

i use fedora 35 beta i hope u can help me guys and thanks you

**Comment by TahaTesser** [comment] 2021-10-05 14:21
Hi @amerchaabi 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76178
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-10-05 14:21 UTC
Labels: in triage
