### ISSUE TITLE
[camera] camera preview rotates in landscape mode

### ISSUE THREAD

**Issue by andraskende** [flutter/flutter#39669] opened 2019-09-02 04:19 UTC
```flutter create app3```

added ```camera: ^0.5.4+1``` to dependencies in ```pubspec.yaml```
changed to ```minSdkVersion 21``` in ```android/app/build.gradle```

used this simple example code from camera plugin homepage
https://github.com/flutter/plugins/tree/master/packages/camera

```flutter run```

Pixel 3a XL .  auto rotate enabled

CameraPreview portrait looks good

CameraPreview landscape counterrotates the preview 90 degrees resulting a preview in sideways and stretched.....

## Flutter doctor
```
All done!
[✓] Flutter is fully installed. (Channel beta, v1.8.3, on Mac OS X 10.14.6
    18G87, locale en-US)
[✓] Android toolchain - develop for Android devices is fully installed. (Android
    SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS is fully installed. (Xcode 10.3)
[✓] Android Studio is fully installed. (version 3.4)
[✓] VS Code is fully installed. (version 1.37.1)
[✓] Connected device is fully installed. (1 available)
```

In order to run your application, type:
```
cd app3
flutter run
```
Your application code is in app3/lib/main.dart.
```
andras:~ andras$ cd app3
andras:app3 andras$ code .
andras:app3 andras$ flutter run
Launching lib/main.dart on Pixel 3a XL in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           7.1s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        21.4s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         4.4s
Syncing files to device Pixel 3a XL...                           1,585ms

 To hot reload changes while running, press "r". To hot restart (and rebuild
state), press "R".
````

![Screenshot_20190901-205849](https://user-images.githubusercontent.com/23754/64090032-f3c3d300-ccfd-11e9-9ea1-32422bf9f049.png)

![Screenshot_20190901-205902](https://user-images.githubusercontent.com/23754/64090033-f3c3d300-ccfd-11e9-9fe0-6d2fb741ebe9.png)

**Comment by andraskende** [comment] 2019-09-11 03:02
for the time being I found a workaround which works for me at https://github.com/flutter/flutter/issues/29951#issuecomment-491099670

    return RotatedBox(
        quarterTurns: MediaQuery.of(context).orientation == Orientation.landscape ? 3 : 0,
        child: AspectRatio(
            aspectRatio: controller.value.aspectRatio,
            child: CameraPreview(controller),
        ),
    );

**Comment by escamoteur** [comment] 2019-09-24 17:12
Should be solved by https://github.com/flutter/plugins/pull/1952

**Comment by andraskende** [comment] 2019-09-25 01:01
Hi @escamoteur,

just tested again with fresh install 

[✓] Flutter is fully installed. (Channel stable, v1.9.1+hotfix.2, on Mac OS X
    10.14.6 18G95, locale en-US)

camera-0.5.4+2

Same issue camera preview screen keeps rotatiing..

Could you reopen this ticket ?

    import 'dart:async';
    import 'package:flutter/material.dart';
    import 'package:camera/camera.dart';

    List<CameraDescription> cameras;

    Future<void> main() async {
      cameras = await availableCameras();
      runApp(CameraApp());
    }

    class CameraApp extends StatefulWidget {
      @override
      _CameraAppState createState() => _CameraAppState();
    }

    class _CameraAppState extends State<CameraApp> {
      CameraController controller;

      @override
      void initState() {
        super.initState();
        controller = CameraController(cameras[0], ResolutionPreset.medium);
        controller.initialize().then((_) {
          if (!mounted) {
            return;
          }
          setState(() {});
        });
      }

      @override
      void dispose() {
        controller?.dispose();
        super.dispose();
      }

      @override
      Widget build(BuildContext context) {
        if (!controller.value.isInitialized) {
          return Container();
        }
        return AspectRatio(
            aspectRatio:
            controller.value.aspectRatio,
            child: CameraPreview(controller));
      }
    }

**Comment by escamoteur** [comment] 2019-09-25 06:45
Does this only happen on a real device? 
I just tried to reproduce on an Pixel2 emulator. On which Android version are you?

**Comment by andraskende** [comment] 2019-09-25 08:47
Emulator with Pixel 3XL worked, so yes this is only not working  on my real device...

Real device is Pixel 3a XL android 10 (also same issue on android 9) USB debugging..

Will try with different phone next few days...

Similar issues:
#35397
#29500 2.
#25232
#38069

**Comment by wanjm** [comment] 2019-10-07 02:49
without the feature, may app need to run in landscape with camera will not work;
I am write one online education app in flutter, and am blocked by this now;
why remove customer critical;

**Comment by Mapk26** [comment] 2019-10-30 16:37
Same issue on iPad and Samsung S8+.

**Comment by wanjm** [comment] 2019-11-04 04:05
besides this scenario, I also come across this in other plugins that capture video;
can any one let me know,
is it a bug of flutter or the camera plugin;

**Comment by TahaTesser** [comment] 2020-03-19 14:00
Hi @andraskende 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by andraskende** [comment] 2020-03-19 16:58
Hi Taha,

Pixel 3a XL Phone USB debugging
- Screen Auto-Rotate is disabled it works as expected
- Screen Auto-Rotate is enabled, when rotating to landscape the preview video over rotates...

here is everything:
https://gist.github.com/andraskende/08e7de65879b5d7e1b0a579b8879d1ef


Thanks,
Andras

**Comment by pajama** [comment] 2020-03-31 21:11
same problem on iphone x device

**Comment by kuyazee** [comment] 2020-10-21 19:15
Still happening on version `camera: ^0.5.8+10`

## Notes

- Device: iPhone 11 -  iOS 14.0.1
- Debug via USB
- App is set to DeviceOrientation.portraitUp when taking photos and displaying preview usung Chewie

## flutter doctor -v

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-PH)
    • Flutter version 1.22.0 at /Users/zonilyjamepesquera/flutter
    • Framework revision d408d302e2 (3 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zonilyjamepesquera/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • TempuraPhone (mobile) • 00008030-001925DE3C12802E • ios • iOS 14.0.1

• No issues found!
```

**Comment by jpiabrantes** [comment] 2021-01-26 11:19
It looks like version 0.7.0 solves this. https://pub.dev/packages/camera/changelog#070

**Comment by andosteinmetz** [comment] 2021-02-24 17:19
> It looks like version 0.7.0 was intended to solve this. https://pub.dev/packages/camera/changelog#070
> 
> It solved my problem by calling:
> `await _controller.lockCaptureOrientation(DeviceOrientation.portraitUp);`

Calling this fixes the issue on my Android A01, but crashes the app on my iPhone 6 running iOS v12.4.8

**Comment by amitrotner** [comment] 2021-05-02 06:28
> It looks like version 0.7.0 was intended to solve this. https://pub.dev/packages/camera/changelog#070
> 
> It solved my problem by calling:
> `await _controller.lockCaptureOrientation(DeviceOrientation.portraitUp);`

This solves the sideway and stretched preview but when I take a picture/video in landscape, it saved as portrait and not in landscape.

I am looking for a solution which solves both preview and saving.

**Comment by TahaTesser** [comment] 2021-05-31 13:08
Hi @andraskende 
This is fixed as mentioned in https://github.com/flutter/flutter/issues/39669#issuecomment-767477431
Check the update [official sample](https://pub.dev/packages/camera/example)
Closing as fixed

**Closed by TahaTesser** 2021-05-31 13:08 UTC
Labels: P4, a: quality, p: camera, p: first party, plugin

**Comment by davidmartos96** [comment] 2021-05-31 13:44
@TahaTesser I disagree with it being fixed unless I'm missing something. Here is a video from the example, where I previously lock it to portrait as in the comment you linked.

Same steps as before as described above but locking into portrait up before hand.


https://user-images.githubusercontent.com/22084723/120202468-e74c1180-c226-11eb-847f-cb411330b1e4.mp4

**Comment by TahaTesser** [comment] 2021-05-31 14:53
Hi @andosteinmetz 
You need to unlock portrait mode 
Here is the quick demo with dash as the subject using [official sample](https://pub.dev/packages/video_player/example)


### Portrait locked

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/120209515-72350800-c237-11eb-9a62-65ffe4a115d6.gif)


### Portrait unlocked

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/120210929-0489db80-c239-11eb-97c6-53644e722acf.gif)
