### ISSUE TITLE
webview_flutter cannot open the album under Android

### ISSUE THREAD

**Issue by hmTest6** [flutter/flutter#90786] opened 2021-09-27 03:33 UTC
test url :
https://webchat.7moor.com/wapchat.html?accessId=a902b190-fc75-11e9-9bd8-bd299448ef2d&fromUrl=2&urlTitle=1

webview_flutter cannot open the album under. Android,Please help me. Thancks!

**Comment by Josiassejod1** [comment] 2021-09-27 05:46
Is there any output @hmTest6 ?

**Comment by danagbemava-nc** [comment] 2021-09-27 08:26
Hi @hmTest6 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Also, please specify which version of `webview_flutter` you're using and I would also like you to confirm if this url can open the `album` using a `native` android application. 

If the native android application cannot open it, then `webview_flutter` can't either, since it is just a wrapper around the native android webview.

Thank you

**Comment by danagbemava-nc** [comment] 2021-10-21 14:36
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-10-21 14:36 UTC
Labels: waiting for customer response, in triage
