### ISSUE TITLE
Bug：Failed assertion: line 894 pos 16: 'index == parameters.length': is not true

### ISSUE THREAD

**Issue by dashuboluo** [flutter/flutter#68772] opened 2020-10-22 08:35 UTC
════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.setPubRootDirectories":
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:894:16)
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:882:17)
#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by Flutter framework ═════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by Flutter framework ═════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by pedromassangocode** [comment] 2020-10-22 08:54
This is a duplicate of https://github.com/flutter/flutter/issues/68705 and was recently fixed by https://github.com/flutter/flutter/pull/68721.

The fix is currently on latest `master` channel.

**Closed by pedromassangocode** 2020-10-22 08:54 UTC

**Comment by vleiswal** [comment] 2020-10-22 09:45
What is the fix then pls?

**Comment by pedromassangocode** [comment] 2020-10-22 12:52
> The fix is currently on latest `master` channel.
