### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by xinyuanliu** [flutter/flutter#90583] opened 2021-09-23 09:18 UTC
## Command
```
flutter build ios --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1891:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1362:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#14     _rootRunUnary (dart:async/zone.dart:1370:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.1 at /Users/liuxinyuan/Documents/code/flutter/sdk
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/liuxinyuan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/liuxinyuan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008030-001614A634A0802E • ios            • iOS 14.8
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 93.0.4577.82

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
Bugly-OA-Flutter-Plugin-407a8fbbf150b0cdf3ba36730d5bffe0cad84f61
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
connectivity_plus-1.1.0
connectivity_plus_linux-1.1.0
connectivity_plus_macos-1.1.0
connectivity_plus_web-1.1.0+1
connectivity_plus_windows-1.1.0
device_info-2.0.2
flutter_plugin_android_lifecycle-2.0.3
flutter_thumbplayer-812b7b1678482276fca344e7fffcae4e980e0a31
image_picker-0.8.2
image_picker_for_web-2.1.3
log_flutter-1795a4f921f00b95723bc664b8d3072a0cb8df23
package_info-2.0.2
path_provider-2.0.4
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sinian_secret_config-6911a15fd721ecf676a898301c2677b0874dadcf
sqflite-2.0.0+3
tencent_abtest_sdk-0.0.4
beacon_sdk_flutter-86bfdc183f5d87bfd2c1546bdd14b5a4cc55f4ed
tencent_im_sdk_plugin-3.2.4
tencent_lbs_flutter-0.0.2
tencent_lu_flutter-0.0.18
tencent_lu_qq_flutter-0.0.4
tencent_lu_wx_flutter-0.0.6
tencent_wns_flutter-0.0.8
TPNS-Flutter-Plugin-e9fe4ed5c36da67d1655efe7e2b9a7420ab058b6
url_launcher-6.0.9
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
wakelock-0.5.3+3
wakelock_macos-0.1.0+2
wakelock_web-0.2.0+2
webview_flutter-2.0.9

**Comment by darshankawar** [comment] 2021-09-23 09:32
Closing this as duplicate of #81666 and #65932

**Closed by darshankawar** 2021-09-23 09:32 UTC
Labels: in triage
