### ISSUE TITLE
"Running Gradle task 'assembleDebug'... (Starting a Gradle Daemon)" never ends

### ISSUE THREAD

**Issue by mohammadmomeni** [flutter/flutter#86888] opened 2021-07-22 17:37 UTC
## Steps to Reproduce

1. Run `flutter run -v`.

**Expected results:** 
Assemble debug process ends and the app is ready to watch in the virtual device

**Actual results:**
 getting stuck on `Running Gradle task 'assembleDebug'...`  and 
```Starting a Gradle Daemon, "N (ANY NUMBER)" busy Daemons could not be reused, use --status for details```
and run process never ends !

<details>
  <summary>Logs</summary>

```
[  +56 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +185 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [C:\src\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +47 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +5 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] executing: C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +37 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:1
[   +4 ms] C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +38 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Skipping pub get: version match.
[  +77 ms] Generating C:\Users\Raven\AndroidStudioProjects\testapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +37 ms] ro.hardware = ranchu
[   +9 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +18 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +3 ms] Launching lib\main.dart on sdk gphone x86 arm in debug mode...
[   +3 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Raven\AppData\Local\Temp\flutter_tools.9d1246b8\flutter_tool.faedfc72\app.dill --packages C:\Users\Raven\AndroidStudioProjects\testapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +12 ms] executing: C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[   +5 ms] <- compile package:testapp/main.dart
[  +34 ms] --------- beginning of main
           07-22 21:52:26.801 W/Binder:217_2(  217): type=1400 audit(0.0:151): avc: denied { read } for name="wakeup35" dev="sysfs" ino=19023 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[   +8 ms] executing: C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +28 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\Raven\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +24 ms] Building APK
[  +13 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from C:\Users\Raven\AndroidStudioProjects\testapp\android\gradlew.bat.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +105 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +1 ms] executing: [C:\Users\Raven\AndroidStudioProjects\testapp\android/] C:\Users\Raven\AndroidStudioProjects\testapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\Raven\AndroidStudioProjects\testapp\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3365 ms] Starting a Gradle Daemon, 129 busy Daemons could not be reused, use --status for details
[+3591 ms] Starting a Gradle Daemon, 130 busy Daemons could not be reused, use --status for details
[+3499 ms] Starting a Gradle Daemon, 131 busy Daemons could not be reused, use --status for details
[+3500 ms] Starting a Gradle Daemon, 132 busy Daemons could not be reused, use --status for details
[+3499 ms] Starting a Gradle Daemon, 133 busy Daemons could not be reused, use --status for details
[+3500 ms] Starting a Gradle Daemon, 134 busy Daemons could not be reused, use --status for details
[+3500 ms] Starting a Gradle Daemon, 135 busy Daemons could not be reused, use --status for details
[+3498 ms] Starting a Gradle Daemon, 136 busy Daemons could not be reused, use --status for details
[+3500 ms] Starting a Gradle Daemon, 137 busy Daemons could not be reused, use --status for details
[+3499 ms] Starting a Gradle Daemon, 138 busy Daemons could not be reused, use --status for details
[+3499 ms] Starting a Gradle Daemon, 139 busy Daemons could not be reused, use --status for details
[+3499 ms] Starting a Gradle Daemon, 140 busy Daemons could not be reused, use --status for details
Terminate batch job (Y/N)? Y
```

```
Analyzing testapp...
No issues found! (ran in 1.0s)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Raven\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Raven\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-07-23 10:07
Hi @mohammadmomeni 
This is a duplicate of https://github.com/flutter/flutter/issues/80212
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80212
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-23 10:07 UTC
Labels: in triage
