### ISSUE TITLE
firebase_messaging plugin fails to build

### ISSUE THREAD

**Issue by frederickcook** [flutter/flutter#12811] opened 2017-10-31 23:49 UTC
## Steps to Reproduce

Add firebase_messaging plugin to a project and build.

## Logs

```
    In file included from /Users/frederickcook/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-0.0.7/ios/Classes/FirebaseMessagingPlugin.m:7:
    In file included from /Users/frederickcook/GondolaProjects/Eng/tram/ios/Pods/Headers/Private/Firebase/Firebase.h:37:
    In file included from /Users/frederickcook/GondolaProjects/Eng/tram/ios/Pods/Headers/Public/FirebaseMessaging/FirebaseMessaging/FirebaseMessaging.h:1:
    /Users/frederickcook/GondolaProjects/Eng/tram/ios/Pods/Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:194:12: warning: parameter 'to' not found in the function declaration [-Wdocumentation]
     *  @param to           A string identifying the receiver of the message. For FCM
               ^~
    /Users/frederickcook/GondolaProjects/Eng/tram/ios/Pods/Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:194:12: note: did you mean 'receiver'?
     *  @param to           A string identifying the receiver of the message. For FCM
               ^~
               receiver
    /Users/frederickcook/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-0.0.7/ios/Classes/FirebaseMessagingPlugin.m:38:30: error: property 'delegate' not found on object of type 'FIRMessaging *'
        [FIRMessaging messaging].delegate = self;
                                 ^
    2 warnings and 1 error generated.
```

## Flutter Doctor

```
Frederick-Cook-Air% flutter doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/frederickcook/flutter
    • Framework revision e1174eb0f2 (6 hours ago), 2017-10-31 10:39:34 -0700
    • Engine revision fe92a5120c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frederickcook/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Frederick Cook’s iPhone • c181836da6febb49dcdbea495dea15b137def3cd • ios • iOS 11.0.3
    • iPhone SE               • 90C45D4E-F058-47E1-8114-75C7E85800DC     • ios • iOS 11.0 (simulator)
```

**Comment by frederickcook** [comment] 2017-10-31 23:55
Full verbose build output: https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output14.txt?alt=media&token=b81c1d7f-200a-4d94-b848-1c0e3cdef99f

**Comment by goderbauer** [comment] 2017-11-01 18:02
This builds fine on my machine. My suspicion from the error message is that your Firebase pods are out of date. Can you paste the content of your `ios/Podfile.lock`?

I am using the following versions:
```
  - Firebase/Core (4.5.0):
    - FirebaseAnalytics (= 4.0.4)
    - FirebaseCore (= 4.0.10)
  - Firebase/Messaging (4.5.0):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.6)
```

Not sure what the best way to update pods is. @xster can you advise?

**Comment by frederickcook** [comment] 2017-11-01 22:47
Ok, this is what my Podfile looked like previously:
```
PODS:
  - Bolts (1.8.4):
    - Bolts/AppLinks (= 1.8.4)
    - Bolts/Tasks (= 1.8.4)
  - Bolts/AppLinks (1.8.4):
    - Bolts/Tasks
  - Bolts/Tasks (1.8.4)
  - FBSDKCoreKit (4.26.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.26.0):
    - FBSDKCoreKit
  - Firebase/Auth (3.17.0):
    - Firebase/Core
    - FirebaseAuth (= 3.1.1)
  - Firebase/Core (3.17.0):
    - FirebaseAnalytics (= 3.9.0)
    - FirebaseCore (= 3.6.0)
  - Firebase/Database (3.17.0):
    - Firebase/Core
    - FirebaseDatabase (= 3.1.2)
  - Firebase/Messaging (3.17.0):
    - Firebase/Core
    - FirebaseMessaging (= 1.2.3)
  - Firebase/Storage (3.17.0):
    - Firebase/Core
    - FirebaseStorage (= 1.1.0)
  - firebase_analytics (0.0.1):
    - Firebase/Core
    - Flutter
  - firebase_auth (0.0.1):
    - Firebase/Auth
    - Firebase/Core
    - FirebaseUI/Auth (~> 3.0)
    - FirebaseUI/Google
    - Flutter
    - Google/SignIn
  - firebase_database (0.0.1):
    - Firebase/Database
    - Flutter
  - firebase_messaging (0.0.1):
    - Firebase/Core
    - Firebase/Messaging
    - Flutter
  - firebase_storage (0.0.1):
    - Firebase/Storage
    - Flutter
  - FirebaseAnalytics (3.9.0):
    - FirebaseCore (~> 3.6)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseAuth (3.1.1):
    - FirebaseAnalytics (~> 3.7)
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (3.6.0):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseDatabase (3.1.2):
    - FirebaseAnalytics (~> 3.7)
  - FirebaseInstanceID (1.0.10):
    - FirebaseCore (~> 3.6)
  - FirebaseMessaging (1.2.3):
    - FirebaseAnalytics (~> 3.8)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - FirebaseStorage (1.1.0):
    - FirebaseAnalytics (~> 3.7)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseUI/Auth (3.1.1):
    - Firebase/Auth
  - FirebaseUI/Google (3.1.1):
    - FirebaseUI/Auth
    - GoogleSignIn (~> 4.0)
  - Flutter (1.0.0)
  - Google/Core (3.1.0):
    - FirebaseAnalytics (~> 3.2)
  - Google/SignIn (3.1.0):
    - Google/Core
    - GoogleSignIn (~> 4.0)
  - google_sign_in (0.0.1):
    - Flutter
    - GoogleSignIn (~> 4.0)
  - GoogleSignIn (4.1.0):
    - GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)
    - GoogleToolboxForMac/NSString+URLArguments (~> 2.1)
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/Logger (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/NSDictionary+URLArguments (2.1.1):
    - GoogleToolboxForMac/DebugUtils (= 2.1.1)
    - GoogleToolboxForMac/Defines (= 2.1.1)
    - GoogleToolboxForMac/NSString+URLArguments (= 2.1.1)
  - GoogleToolboxForMac/NSString+URLArguments (2.1.1)
  - GTMOAuth2 (1.1.5):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.12):
    - GTMSessionFetcher/Full (= 1.1.12)
  - GTMSessionFetcher/Core (1.1.12)
  - GTMSessionFetcher/Full (1.1.12):
    - GTMSessionFetcher/Core (= 1.1.12)
  - image_picker (0.0.1):
    - Flutter
  - Protobuf (3.4.0)
  - url_launcher (0.0.1):
    - Flutter
```

With your clues above about pods being out of date, I blew away that `Podfile.lock` file and the `ios/Pods` dir and rebuilt. Same error. I then went back and updated my `pubspec.yaml` file to just use the latest version of all the firebase plugins, fixed all the resulting issues (a lot changed in ~60 days!) and blew everything away again and rebuilt and that worked.

I'm guessing that since I have been using firebase since August or so without `messaging`, then dropped in the `messaging` plugin with the latest version, there was a mismatch in `core` versions between what `messaging` was looking for and what the rest of the firebase plugins use? If that was the case perhaps we should be detecting a dependency mismatch and throwing a descriptive error? Or just downloading different versions of the plugin?

Either way, thanks for the help @Hixie! I'll leave this to you to close in case you identify any issues coming out of this.

**Comment by Hixie** [comment] 2018-01-31 00:44
We're going to close this since we don't know how to reproduce this problem.

**Closed by Hixie** 2018-01-31 00:44 UTC
Labels: plugin: firebase, ⌘‬ platform-mac

**Comment by kroikie** [comment] 2019-10-13 19:23
@frederickcook

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/948. Any further collaboration will be done there.
