### ISSUE TITLE
[Windows] (Release mode) Once shift key is pressed once, it is not removed from keys pressed ever

### ISSUE THREAD

**Issue by seanmc86** [flutter/flutter#78227] opened 2021-03-15 16:45 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a TextField and wrap this with a RawKeyboardListener
3. Build app in `release ` mode
3. Monitor key down and key up events in RawKeyboardListener's onKey method.

**Expected results:**

Shift key removed from raw keyboard keys pressed.

**Actual results:**

Once shift is pressed once, all future key events will continue to say shift is pressed, even when neither left or right shift are pressed.

The expected behaviour is correct in debug mode, but not release mode.

<details>
  <summary>Logs</summary>

Sample app:

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller;
  FocusNode _rawFocusNode;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
    _rawFocusNode = FocusNode();
  }

  void _handleRawKey(RawKeyEvent key) {
    // Uncomment to test
    // print("KEY ${key} ${key.logicalKey} ${key.character}");

    var shiftIsPressed = key.isKeyPressed(LogicalKeyboardKey.shiftLeft) ||
        key.isKeyPressed(LogicalKeyboardKey.shiftRight);
    var enterIsPressed = key.isKeyPressed(LogicalKeyboardKey.enter);
    final debug = 'Shift: $shiftIsPressed Enter: $enterIsPressed';
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(debug),
      duration: const Duration(seconds: 3),
    ));
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Container(
          color: Colors.red,
          child: RawKeyboardListener(
            focusNode: _rawFocusNode,
            onKey: _handleRawKey,
            child: TextField(
              decoration: InputDecoration(fillColor: Colors.green),
              controller: _controller,
              onEditingComplete: () => _controller.text = '',
              maxLines: 5,
              textInputAction: TextInputAction.unspecified,
            ),
          ),
        ),
      ),
    );
  }
}

```

```
flutter analyze
Analyzing testapp...                                                    
No issues found! (ran in 2.0s)
```

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.867], locale en-GB)
    • Flutter version 2.0.1 at C:\Work\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Sean\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Sean\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\Sean\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```

</details>

**Comment by devnought** [comment] 2021-03-15 17:44
I have observed this in `debug` on Windows, in addition to `release` builds.

**Comment by HansMuller** [comment] 2021-03-16 21:29
CC @dkwingsmt

**Comment by darshankawar** [comment] 2021-03-17 12:43
I was unable to replicate this issue in debug as well as in release mode using the sample code provided above. It recognized `Enter` key event but after pressing SHIFT, which also returned true, but after subsequent key press events, it always returned `false` for `Shift` pressed.

<img width="813" alt="Screenshot 2021-03-17 at 6 12 09 PM" src="https://user-images.githubusercontent.com/67046386/111469112-52b83400-874c-11eb-9e7b-6f415513264a.png">


![IMG-0693](https://user-images.githubusercontent.com/67046386/111469154-5ea3f600-874c-11eb-8cc8-20d108552c65.JPG)

**Comment by seanmc86** [comment] 2021-03-17 12:49
@darshankawar it is reproduced by:

1) Press shift-enter
2) Release shift
3) Press enter

The final keys pressed notification (when the final KeyUp for enter is received) shows "Shift: true Enter: false"

**Comment by darshankawar** [comment] 2021-03-17 13:15
Thanks @seanmc86 for the updated details. I now can notice the issue you mentioned.

![IMG-0693](https://user-images.githubusercontent.com/67046386/111473303-ea1f8600-8750-11eb-8297-673cf7a03768.JPG)

**Comment by Michael35699** [comment] 2021-03-18 02:07
I have been experiencing a similar issue. When typing on a text field, my left shift key behaves as expected, but my right shift key keeps getting locked, and I need to press the left shift key to unlock it.

**Comment by seanmc86** [comment] 2021-03-25 09:42
FYI, I've found a work around.

Using this check for shift returns the correct data:
```
RawKeyboard.instance.physicalKeysPressed
            .contains(PhysicalKeyboardKey.shiftLeft) ||
        RawKeyboard.instance.physicalKeysPressed
            .contains(PhysicalKeyboardKey.shiftRight)
```

Using either of these two does not work as expected:

1) From `RawKeyboardListener`'s `onKey`:
```
(RawKeyEvent key) => key.isKeyPressed(LogicalKeyboardKey.shiftLeft) ||
        key.isKeyPressed(LogicalKeyboardKey.shiftRight)
```
2) ```
RawKeyboard.instance.keysPressed
            .contains(LogicalKeyboardKey.shift)
```

Is this difference in PhysicalKeyboardKey vs LogicalKeyboardKey expected?

**Comment by Leadrive** [comment] 2021-05-10 09:25
Channel master, 2.3.0-1.0.pre.269
the latest master version, have little improvement, only to input &, #, will cause this bug.
and sometime is work file.very strange.

最新版本有所改进，只有按住右shift输入&, #字符时，才会重现此bug。输入&#时并不总是出现此错误，有时候正常，有点奇怪。

**Comment by yangyxd** [comment] 2021-07-08 02:33
> I have been experiencing a similar issue.

**Comment by TahaTesser** [comment] 2021-07-29 10:16
Hi 

This was reported in https://github.com/flutter/flutter/issues/75675 
I can confirm it is fixed, currently works in the latest `dev` and `master` channels, in debug and release mode

Also # doesn't cause any issue either

Can you please upgrade to the latest  `dev` and try again if you want
Execute the following commands to upgrade
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

Closing as duplicate of https://github.com/flutter/flutter/issues/75675

**Closed by TahaTesser** 2021-07-29 10:16 UTC
Labels: P4, a: build, a: desktop, a: release, engine, found in release: 2.0, has reproducible steps, platform-windows
