### ISSUE TITLE
Error extension on Android Studio and VSCode

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#65283] opened 2020-09-05 11:35 UTC
Hai there, i have some bug here,, my extension is showing error on as and vscode,

here my doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

• No issues found!
```

and here the error on IDE

**Android Studio**
<img width="695" alt="Screen Shot 2020-09-05 at 18 30 15" src="https://user-images.githubusercontent.com/10652810/92304251-6d903b80-efa6-11ea-9931-d8cb0721bafe.png">

**VS Code**
<img width="478" alt="Screen Shot 2020-09-05 at 18 29 58" src="https://user-images.githubusercontent.com/10652810/92304257-78e36700-efa6-11ea-8925-6da215772403.png">

Thanks for help..

**Comment by iapicca** [comment] 2020-09-06 09:33
@congfandi 

for flutter's vs code plugin
following the information on [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter)
the issue should be opened [here](https://github.com/Dart-Code/Dart-Code/issues)

for flutter'a android studio / jetbrains plugin
following the information on the [plugin's page](https://plugins.jetbrains.com/plugin/9212-flutter)
the issue should be opened [here](https://github.com/flutter/flutter-intellij/issues)

not on flutter's githib repo

**Comment by TahaTesser** [comment] 2020-09-07 09:00
Hi @congfandi 
Cany you please provide your `flutter analyze -v` and `flutter run --verbose` from terminal 

I can't reproduce this issue on the latest `stable`

![image](https://user-images.githubusercontent.com/48603081/92369261-68ea9500-f116-11ea-9239-d53ad9e889e8.png)
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.3 at C:\Code\flutter_stable
    • Framework revision 216dee60c0 (6 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

</details> 

It might plugin issue but both IDEs are showing it so I wonder what's going in
Can you also provide  a complete reproducible minimal code sample instead of screenshot
Thank you

**Comment by congfandi** [comment] 2020-09-07 09:27
> Hi @congfandi
> Cany you please provide your `flutter analyze -v` and `flutter run --verbose` from terminal
> 
> I can't reproduce this issue on the latest `stable`
> 
> ![image](https://user-images.githubusercontent.com/48603081/92369261-68ea9500-f116-11ea-9239-d53ad9e889e8.png)
> 
> flutter doctor -v
> It might plugin issue but both IDEs are showing it so I wonder what's going in
> Can you also provide a complete reproducible minimal code sample instead of screenshot
> Thank you


here @TahaTesser 

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.20.3 at /Users/congfandi/development/flutter
    • Framework revision 216dee60c0 (6 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/congfandi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 4C97FEF2-E3C8-4A85-8B90-D5B4B5BF06F9
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

```
[ +380 ms] executing: [/Users/congfandi/development/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +250 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 216dee60c0cc9449f0b29bcf922974d612263e24
[   +1 ms] executing: [/Users/congfandi/development/flutter/] git tag --contains
HEAD
[ +250 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.3
[  +12 ms] executing: [/Users/congfandi/development/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/congfandi/development/flutter/] git ls-remote
--get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [/Users/congfandi/development/flutter/] git rev-parse
--abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[   +1 ms] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.6
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19G2021
[  +71 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[ +969 ms] dart --disable-dart-dev
/Users/congfandi/development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_s
erver.dart.snapshot --disable-server-feature-completion
--disable-server-feature-search --sdk
/Users/congfandi/development/flutter/bin/cache/dart-sdk
[  +47 ms] ==>
{"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"
]}}
[   +2 ms] ==>
{"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/Users/con
gfandi"],"excluded":[]}}
[   +3 ms] Analyzing congfandi...
[ +566 ms] <==
{"event":"server.connected","params":{"version":"1.28.0","pid":61125}}
[  +36 ms] <== {"id":"1"}


```

**Comment by congfandi** [comment] 2020-09-07 09:37
> Hi @congfandi
> Cany you please provide your `flutter analyze -v` and `flutter run --verbose` from terminal
> 
> I can't reproduce this issue on the latest `stable`
> 
> ![image](https://user-images.githubusercontent.com/48603081/92369261-68ea9500-f116-11ea-9239-d53ad9e889e8.png)
> 
> flutter doctor -v
> It might plugin issue but both IDEs are showing it so I wonder what's going in
> Can you also provide a complete reproducible minimal code sample instead of screenshot
> Thank you

this is not help me :-(

**Comment by Abhishek01039** [comment] 2020-09-08 04:14
Have you installed dart extension also in vscode and Android studio ?
Thanks

**Comment by TahaTesser** [comment] 2020-09-08 07:14
Hi @congfandi 
Yeah doctor -v doesn't show dart extension, can you please make sure you've dart extension in vs code and android studio

<img width="521" alt="Screenshot 2020-09-08 at 12 43 12 PM" src="https://user-images.githubusercontent.com/48603081/92444691-e246be00-f1d0-11ea-8276-1ea6aa5b6df6.png">

This issue doesn't reproduce on my multiple laptops, It must be your setup

**Comment by congfandi** [comment] 2020-09-08 08:02
> Hi @congfandi
> Yeah doctor -v doesn't show dart extension, can you please make sure you've dart extension in vs code and android studio
> 
> <img alt="Screenshot 2020-09-08 at 12 43 12 PM" width="521" src="https://user-images.githubusercontent.com/48603081/92444691-e246be00-f1d0-11ea-8276-1ea6aa5b6df6.png">
> 
> This issue doesn't reproduce on my multiple laptops, It must be your setup

I have been install it

here my SS

**Android Studio Side**
<img width="986" alt="Screen Shot 2020-09-08 at 14 57 03" src="https://user-images.githubusercontent.com/10652810/92449355-24c5c600-f1e4-11ea-8212-47efd4669d9e.png">


**Visual Studio Side**
<img width="1292" alt="Screen Shot 2020-09-08 at 15 00 12" src="https://user-images.githubusercontent.com/10652810/92449425-42932b00-f1e4-11ea-8c76-d2406b380324.png">

**Comment by congfandi** [comment] 2020-09-08 08:03
> Have you installed dart extension also in vscode and Android studio ?
> Thanks

i have been install it ? is this issue on my mac ?

@Abhishek01039  @TahaTesser  ?? thanks for help..

**Comment by TahaTesser** [comment] 2020-09-08 08:19
Hi @congfandi 
Can you please try new project `flutter create myapp` and add this code and make sure you've min sdk 2.7.0
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

**Comment by congfandi** [comment] 2020-09-08 08:20
oke, a min.

**Comment by congfandi** [comment] 2020-09-08 08:24
![image](https://user-images.githubusercontent.com/10652810/92451645-36f53380-f1e7-11ea-80f8-46cebd3fc63e.png)


It's work,, can you please tell me what happen?

Thanks @TahaTesser  for help

**Comment by congfandi** [comment] 2020-09-08 08:24
can i close this issue ?

**Comment by congfandi** [comment] 2020-09-08 08:28
me and my team got this issue @TahaTesser  and you save my life .. thanksss...

**Comment by TahaTesser** [comment] 2020-09-08 09:12
@congfandi 
Extensions were introduced in dart 2.7.0, therefore you need min to be at least that  https://dart.dev/guides/language/extension-methods
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-08 09:12 UTC
Labels: in triage
