### ISSUE TITLE
Unable to run a scratch.dart file

### ISSUE THREAD

**Issue by gicounts** [flutter/flutter#47567] opened 2019-12-21 01:29 UTC
The option to run a scratch.dart file is unavailable on Android Studio.  Right-clicking on the scratch file under Scratches and Consoles will not show the Run option.  And I can't find a way to enable this capability.

Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by iapicca** [comment] 2019-12-22 11:48
Hi @gicounts  
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by gicounts** [comment] 2019-12-23 04:02
Hi Francecsco,

When I do a right-click on scratch.dart there should be a Run option on the
submenu to enable execution of that file.

[image: image.png]


Here's the Flutter doctor output -

> [√] Flutter (Channel beta, v1.9.1+hotfix.2, on Microsoft Windows [Version
> 10.0.18362.535], locale en-US)
>     • Flutter version 1.9.1+hotfix.2 at C:\Users\GregPC\OneDrive\flutter
>     • Framework revision 2d2a1ffec9 (4 months ago), 2019-09-06 18:39:49
> -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> [√] Android toolchain - develop for Android devices (Android SDK version
> 29.0.2)
>     • Android SDK at C:\Users\GregPC\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native
> profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build
> 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 42.1.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build
> 1.8.0_202-release-1483-b03)
> [√] VS Code (version 1.41.0)
>     • VS Code at C:\Users\GregPC\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.7.1
> [!] Connected device
>     ! No devices available
> ! Doctor found issues in 1 category.


And here's the Flutter run output -

> [  +11 ms] executing: [C:\Users\GregPC\OneDrive\flutter\] git log -n 1
> --pretty=format:%H
> [ +106 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
> [   +1 ms] 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
> [        ] executing: [C:\Users\GregPC\OneDrive\flutter\] git describe
> --match v*.*.* --first-parent --long --tags
> [  +62 ms] Exit code 0 from: git describe --match v*.*.* --first-parent
> --long --tags
> [        ] v1.9.1+hotfix.2-0-g2d2a1ffec
> [   +7 ms] executing: [C:\Users\GregPC\OneDrive\flutter\] git rev-parse
> --abbrev-ref --symbolic @{u}
> [  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/beta
> [        ] executing: [C:\Users\GregPC\OneDrive\flutter\] git ls-remote
> --get-url origin
> [  +53 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [  +98 ms] executing: [C:\Users\GregPC\OneDrive\flutter\] git rev-parse
> --abbrev-ref HEAD
> [  +75 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] beta
> [  +44 ms] "flutter run" took 114ms.



Thank you!

Greg

**Comment by zboyles** [comment] 2020-01-10 23:36
I have the same issue as Greg. The new root item Scratches and Consoles appears but I can't seem to run any scratches nor can I edit a configuration template for scratches as I've read elsewhere. 

Thank you,
Zac

Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by jonahwilliams** [comment] 2020-01-10 23:45
Removing tool designation since this has to do with android studio

**Comment by iapicca** [comment] 2020-01-17 10:46
Hi @gicounts   
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Closed by iapicca** 2020-01-17 10:46 UTC
Labels: dependency: dart

**Comment by sidekickbottom** [comment] 2020-04-26 22:30
Make sure you create the scratch.dart file directly under the project folder. Soon as you write some code in the file, you should see the option to Run scratch.dart on right-clicking the file. The option to run doesn't appear until you write some code.
