### ISSUE TITLE
Start iOS Simulator Not Shows after updating Flutter 1.22

### ISSUE THREAD

**Issue by Safnaj** [flutter/flutter#67074] opened 2020-10-01 19:05 UTC
## Steps to Reproduce

1. Choose Device to Run the App
2. Only Shows Create Android Emulator
3. Previously its shows both Start iOS Simulator & Create Android Emulator

**Expected results:** 
It should show Start iOS Simulator & Create Android Emulator both options.

**Actual results:** 
<img width="851" alt="Screenshot 2020-10-02 at 12 32 42 AM" src="https://user-images.githubusercontent.com/37530024/94852204-267f5400-0447-11eb-9d43-3c4f62224869.png">

Note: I have installed Flutter v1.22 and XCode 12 with iOS 14

**Comment by TahaTesser** [comment] 2020-10-02 09:34
Hi @Safnaj 

<img width="739" alt="Screenshot 2020-10-02 at 3 03 01 PM" src="https://user-images.githubusercontent.com/48603081/94909161-6898ac00-04c0-11eb-9cec-d4fdb0199aef.png">"

Do you have an iOS simulator in your doctor -v?

No issues with VSC `1.49.2`  on `v3.15.0` VS Code Flutter  extension

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0.1

• No issues found!
```

</details> 

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-02 09:34 UTC

**Comment by Safnaj** [comment] 2020-10-02 12:03
@TahaTesser in flutter doctor -v the device is appears if i only start the simulator. As in the image you shared above it's not showing the "Start iOS Simulator".

**Comment by Safnaj** [comment] 2020-10-02 12:27
@TahaTesser I have updated the XCode 2 days back. Will cause this issue ??
And do we need to have XCode Command line tools as well ?

**Comment by TahaTesser** [comment] 2020-10-02 13:44
@Safnaj 
Yes, that's how it should be, If the simulator is launched it will show in doctor -v 
Since this is VS Code plugin menu, please fille issue on their GitHub as mentioned https://github.com/flutter/flutter/issues/67074#issuecomment-702627589

**Comment by Safnaj** [comment] 2021-01-05 18:33
@TahaTesser Seems still this issue isn't fixed
