### ISSUE TITLE
Flexible should work within wrap

### ISSUE THREAD

**Issue by steeling** [flutter/flutter#82128] opened 2021-05-09 00:00 UTC
Any reason why Flexible doesn't work within wrap?

I want to have a series of pairs of items (a TextField next to a checkmark). When hitting the edge i want to wrap these. Why can't I use a flexiblie instead of a wrap?

```
Wrap(
  children:[ Flexible(child: Row(children:[Text1, checkMark()])), Flexible(child: Row(children: [Text1, checkMark()])])
```

**Comment by darshankawar** [comment] 2021-05-10 11:47
@steeling 
`Flexible` should be a descendant  of Row, Column or Flex.  If you use `Column` or `Row` instead of `Wrap`, you should see expected behavior, but since `Wrap` isn't, and hence, it may not be giving you the expected result.

**Comment by darshankawar** [comment] 2021-06-04 12:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-04 12:59 UTC
Labels: in triage, waiting for customer response
