### ISSUE TITLE
In windows when pinching using touch screen, scale events are not recognized

### ISSUE THREAD

**Issue by praveeng2565** [flutter/flutter#78189] opened 2021-03-15 05:37 UTC
Hi,

* In the Windows platform, I have tried to scale my application using the scale gesture on the touch screen. It didn’t get works. But when I have tried the same codes in the web platform the scaling gets works. This is because when I had scaled, the scale gesture events get called on the web. But in the windows, the hover and scroll event only gets called. Scale gesture events are not handled.

<details>
  <summary>Code sample with scale gesture</summary>

```
  double scale = 1.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onScaleUpdate: (ScaleUpdateDetails details) {
            setState(() {
              scale = details.scale;
            });
          },
          child: FlutterLogo(
            size: 400 * scale,
            duration: Duration.zero,
          ),
        ),
      ),
    );
  }
```

</details>

https://user-images.githubusercontent.com/71330249/111134466-a9353f00-85a1-11eb-95c8-f2418788eb43.mp4

* Also, in windows with the InteractiveViewer widget, the trackpad pinch zooming is not obtained as expected. It's hard to attain the expected zoom level when pinch-zooming using a trackpad.

<details>
  <summary>Code sample with Interactive viewer</summary>

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InteractiveViewer(
        minScale: 0.1,
        maxScale: 5.0,
        child: Stack(
          children: [
           Positioned.fill(
                  child: FlutterLogo(style: FlutterLogoStyle.horizontal)),
          ],
        ),
      ),
    );
  }
```

</details>

<details>
  <summary>Flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.3.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.3.29503.13
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1379]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>

Is there any way to resolve this?

Thanks in advance.

**Comment by stuartmorgan** [comment] 2021-03-15 10:38
Duplicate of https://github.com/flutter/flutter/issues/65171

**Closed by stuartmorgan** 2021-03-15 10:38 UTC
