### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by KARTIKEYA-NF** [flutter/flutter#150554] opened 2024-06-20 11:31 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Operation timed out, errno = 60
```
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#5      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136:12)
<asynchronous suspension>
#6      ErrorHandlingFile.writeAsString.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:246:24)
<asynchronous suspension>
#7      _run (package:flutter_tools/src/base/error_handling_io.dart:556:12)
<asynchronous suspension>
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:38:3)
<asynchronous suspension>
#9      _writePluginCmakefile (package:flutter_tools/src/flutter_plugins.dart:744:3)
<asynchronous suspension>
#10     writeWindowsPluginFiles (package:flutter_tools/src/flutter_plugins.dart:848:3)
<asynchronous suspension>
#11     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1089:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:386:5)
<asynchronous suspension>
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:383:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel
    stable, 3.22.2, on
    macOS 14.5 23F79
    darwin-arm64, locale
    en-US)
    [32m•[39m Flutter version
      3.22.2 on channel
      stable at
      /Users/karthikeya/d
      evelopment/flutter
    [32m•[39m Upstream repository
      https://github.com/
      flutter/flutter.git
    [32m•[39m Framework revision
      761747bfc5 (2 weeks
      ago), 2024-06-05
      22:15:13 +0200
    [32m•[39m Engine revision
      edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version
      2.34.3

[32m[✓][39m Android toolchain -
    develop for Android
    devices (Android SDK
    version 34.0.0)
    [32m•[39m Android SDK at
      /Users/karthikeya/L
      ibrary/Android/sdk
    [32m•[39m Platform
      android-34,
      build-tools 34.0.0
    [32m•[39m Java binary at:
      /Applications/Andro
      id
      Studio.app/Contents
      /jbr/Contents/Home/
      bin/java
    [32m•[39m Java version
      OpenJDK Runtime
      Environment (build
      17.0.10+0-17.0.10b1
      087.21-11572160)
    [32m•[39m All Android
      licenses accepted.

[32m[✓][39m Xcode - develop for
    iOS and macOS (Xcode
    15.4)
    [32m•[39m Xcode at
      /Applications/Xcode
      .app/Contents/Devel
      oper
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version
      1.15.2

[32m[✓][39m Chrome - develop for
    the web
    [32m•[39m Chrome at
      /Applications/Googl
      e
      Chrome.app/Contents
      /MacOS/Google
      Chrome

[32m[✓][39m Android Studio
    (version 2023.3)
    [32m•[39m Android Studio at
      /Applications/Andro
      id
      Studio.app/Contents
    [32m•[39m Flutter plugin can
      be installed from:
      🔨
      https://plugins.jet
      brains.com/plugin/9
      212-flutter
    [32m•[39m Dart plugin can be
      installed from:
      🔨
      https://plugins.jet
      brains.com/plugin/6
      351-dart
    [32m•[39m Java version
      OpenJDK Runtime
      Environment (build
      17.0.10+0-17.0.10b1
      087.21-11572160)

[32m[✓][39m VS Code (version
    1.90.2)
    [32m•[39m VS Code at
      /Applications/Visua
      l Studio
      Code.app/Contents
    [32m•[39m Flutter extension
      version 3.90.0

[32m[✓][39m Connected device (4
    available)
    [32m•[39m sdk gphone64 arm64
      (mobile)     •
      emulator-5554
      • android-arm64  •
      Android 14 (API 34)
      (emulator)
    [32m•[39m macOS (desktop)
      • macos
      • darwin-arm64   •
      macOS 14.5 23F79
      darwin-arm64
    [32m•[39m Mac Designed for
      iPad (desktop) •
      mac-designed-for-ip
      ad • darwin
      • macOS 14.5 23F79
      darwin-arm64
    [32m•[39m Chrome (web)
      • chrome
      • web-javascript •
      Google Chrome
      126.0.6478.62

[32m[✓][39m Network resources
    [32m•[39m All expected
      network resources
      are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
cloud_firestore-5.0.1
cloud_firestore_web-4.0.1
firebase_core-3.1.0
firebase_core_web-2.17.2

**Comment by danagbemava-nc** [comment] 2024-06-20 12:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/147591

**Closed by danagbemava-nc** 2024-06-20 12:00 UTC
Labels: in triage
