### ISSUE TITLE
Android Studio Plugin : should show simulator name instead of gphone for android simulators

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#84421] opened 2021-06-11 08:44 UTC
![Screenshot 2021-06-11 at 14 04 19](https://user-images.githubusercontent.com/12496655/121658069-9f4aab80-cabe-11eb-9791-68ab63c1c65a.png)

## Use case
For device selection dropdown showing various devices.

## Proposal

Right now showing only code name like `gphone` for every android simulator. It should be name of that simulator.
So, it can easily be identified on which simulator its going to Run.

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/UserA/Library/Android/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/UserA/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 91.0.4472.101

• No issues found!
```

`flutter emulators
` Output
```
5 available emulators:

apple_ios_simulator • iOS Simulator       • Apple  • ios
Nexus_9_Tab_API_30  • Nexus 9 Tab API 30  • Google • android
Pixel_3a_API_30_x86 • Pixel_3a_API_30_x86 • Google • android
Pixel_4_API_S_12    • Pixel 4 API S 12    • Google • android
new_5.0_Pixel_API_S • new 5.0 Pixel API S • Google • android
```

**Comment by TahaTesser** [comment] 2021-06-11 10:23
Hi @mehtahardikr 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-11 10:23 UTC
Labels: in triage
