### ISSUE TITLE
关于Flutter Image.xxx

### ISSUE THREAD

**Issue by kongxiaoan** [flutter/flutter#27214] opened 2019-01-29 03:12 UTC
Flutter 使用Image.xxx方式加载图片，然后跳转到原生Activity界面，返回时，之前flutter界面中加载的图片不见了，变成了黑色或者其他颜色的框，这是什么问题呢？希望您能解答

**Comment by loongliu** [comment] 2019-01-29 06:20
Translation:
Use `Image.xxx` to load image in flutter page. Navigate to Native Activity, then navigate back to flutter page. The original image in flutter page changed to  black or other color.

Why does this happened? Looking forward for your answer.

**Comment by kangwang1988** [comment] 2019-01-29 08:00
`flutter doctor -v`
and a minimal demo project to reproduce this issue would be helpful.
@kongxiaoan

**Comment by zoechi** [comment] 2019-01-29 09:01
Duplicate of #26654

**Closed by zoechi** 2019-01-29 09:01 UTC
Labels: waiting for customer response
