### ISSUE TITLE
flutter run --no-build still rebuild apk on android

### ISSUE THREAD

**Issue by aptarmy** [flutter/flutter#72342] opened 2020-12-15 09:19 UTC
Even if I change some little things it rebuilds the app. It should not rebuild and perform hot-reload to update the changes instead.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.20180.1000], locale th-TH)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)
```

Thank you

**Comment by pedromassangocode** [comment] 2020-12-15 11:01
Hi @aptarmy 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample and the steps to reproduce the issue?
Thank you

**Comment by aptarmy** [comment] 2020-12-15 14:18
Thank you for your fast response @pedromassangocode this is my terminal output.

```
$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.20180.1000], locale th-TH)
    • Flutter version 1.22.4 at C:\Users\apten\softwares\flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
```

and here are steps to reproduce the issue
1. Connect laptop to physical mobile device.
2. Create flutter app with the command `flutter create test_app`.
3. `cd` to that directory and run `flutter run`. This will build the app and install in the device as expected
4. Close debugging `ctrl+c` (to pretend to finish coding for today)
5. Run `flutter run --no-build` (to pretend to start coding tomorrow)
6. Flutter rebuild the app even though there is an apk file in output folder already

**Comment by pedromassangocode** [comment] 2020-12-16 08:15
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.86, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-9.0.pre.86 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 876c313784 (2 hours ago), 2020-12-16 01:23:03 -0500
    • Engine revision a70f6de139
    • Dart version 2.12.0 (build 2.12.0-155.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by vrnvorona** [comment] 2020-12-16 09:44
https://github.com/flutter/flutter/issues/68529 potentially relative?

**Comment by pedromassangocode** [comment] 2020-12-16 10:19
Thanks @vrnvorona 
Closing as duplicate of https://github.com/flutter/flutter/issues/68529. For anyone facing this issue, please follow up on https://github.com/flutter/flutter/issues/68529.

**Closed by pedromassangocode** 2020-12-16 10:19 UTC
Labels: a: build, found in release: 1.25, has reproducible steps, platform-android, tool
