### ISSUE TITLE
Multiple errors reported for dart:ffi win32 when running/testing

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#75113] opened 2021-02-01 05:14 UTC
see https://stackoverflow.com/questions/65912637/how-can-i-fix-this-error-struct-utf8-is-empty-support-for-empty-structs-is-d/65922099

I've seen this locally on macos as well.

/cc @dcharkes @kevmoo if you know anything

If this exists on the current release candidate we should find a cherrypick for it. /cc @christopherfujino - I'm not sure which hash(es) to check for that

Filing this as a P0 until we can determine whether this is happening on RC branch.

**Comment by kevmoo** [comment] 2021-02-01 05:31
No idea here. @mit-mit ? @timsneath ?

**Comment by timsneath** [comment] 2021-02-01 05:51
This should _not_ be fatal. It's an informational message caused by the transition to the stable API for FFI; as I understand it, Dart now throws this warning for empty `Struct` classes, and these should now be of type `Opaque`. `package:ffi` needs to be updated to be compatible with the latest Dart SDK. 

Paging @dcharkes, who is the owner for this.

**Comment by dnfield** [comment] 2021-02-01 05:54
It's not fatal but I get a wall of red text like that when I run flutter_test on a program that does not seem to have that dependency

**Comment by timsneath** [comment] 2021-02-01 05:59
Right. We probably shouldn't be flagging these breaking changes when there's no combination (as I understand it) of working FFI bits that solves it. 

I think the dependency chain is path_provider -> path_provider_windows -> win32 -> ffi, btw.

**Comment by dnfield** [comment] 2021-02-01 06:33
So it could just be on building the flutter_tools you get this?

**Comment by dcharkes** [comment] 2021-02-01 10:28
I've published https://pub.dev/packages/ffi/versions/0.3.0-nullsafety.0 which requires `2.12.0-265.0.dev` or greater. On Flutter master we're at `2.12.0-276.0.dev`, so this can be fixed on master.

The RC is at `2.12.0-259.0.dev` so it cannot use this `package:ffi` release.

For the RC we need a CP for https://github.com/flutter/engine/pull/23954. In order to deprecate `allocate` in `package:ffi` we need to provide an `Allocator`. But without the CP AllocatorAlloc.call` has no implementation and throws a no such method error. I'll file one. And then we need a `package:ffi` release that has the required SDK version of that CP.

**Comment by jonahwilliams** [comment] 2021-02-01 17:56
(removing tool as this does not involve the flutter_tools source code_

**Comment by pcsosinski** [comment] 2021-02-01 23:04
for 1.26 we need to pick https://github.com/flutter/engine/pull/23954 to the branch and then rev the package?  is this issue tracking any other fixes or can we close it?

**Comment by flutterq** [comment] 2021-02-02 02:21
[[Solved] error: Struct ‘Utf8’ is empty. Support for empty structs is deprecated… Use Opaque instead in flutter
](https://fluttercorner.com/error-struct-utf8-is-empty-support-for-empty-structs-is-deprecated/)

**Comment by dcharkes** [comment] 2021-02-02 08:49
Yes, on the Flutter side this cherry pick, and then bumping package revisions after we migrate all the packages and release versions for the Dart/Flutter beta builds.

> is this issue tracking any other fixes or can we close it?

Where are we tracking the CP and rolling the packages if we close this? On the other issue you mentioned tracking it on this:

> if this issue is only to track a CP fix for https://github.com/flutter/flutter/issues/75113, we can just tag https://github.com/flutter/flutter/issues/75113 (we do it differently in Flutter than Dart)

I don't mind closing any of these issues, as long as we track the work somewhere.

**Comment by omarreess** [comment] 2021-02-02 13:19
I have same issue , it's all with Flutter last version 
Just downgrade and make sure you are on the Stable channel version not beta

`    flutter channel stable
`

**Comment by christopherfujino** [comment] 2021-02-02 17:49
> Yes, on the Flutter side this cherry pick, and then bumping package revisions after we migrate all the packages and release versions for the Dart/Flutter beta builds.
> 
> > is this issue tracking any other fixes or can we close it?
> 
> Where are we tracking the CP and rolling the packages if we close this? On the other issue you mentioned tracking it on this:
> 
> > if this issue is only to track a CP fix for #75113, we can just tag #75113 (we do it differently in Flutter than Dart)
> 
> I don't mind closing any of these issues, as long as we track the work somewhere.

The Flutter release procedure is to close issues when they are fixed upstream, and apply the `cp: x.y` label meaning they are proposed for cherry pick, which is how they are tracked. Once they are fixed on release branch, the label is updated to `cp: x.y completed`. As such, I will close the issue and cherrypick it to branch 1.26

**Closed by christopherfujino** 2021-02-02 17:49 UTC
Labels: P0, a: error message, cp: 1.26, dependency: dart

**Comment by christopherfujino** [comment] 2021-02-02 18:06
> For the RC we need a CP for [flutter/engine#23954](https://github.com/flutter/engine/pull/23954). In order to deprecate `allocate` in `package:ffi` we need to provide an `Allocator`. But without the CP `AllocatorAlloc.call` has no implementation and throws a no such method error. I'll file one. And then we need a `package:ffi` release that has the required SDK version of that CP.

@dcharkes Is cherrypicking this blocked on a special `package:ffi` release for this RC branch, or am I reading this incorrectly?

**Comment by dcharkes** [comment] 2021-02-02 18:09
> @dcharkes Is cherrypicking this blocked on a special `package:ffi` release for this RC branch, or am I reading this incorrectly?

No, the cherry pick is not blocked. Updating `package:ffi` is blocked on this cherry pick.

**Comment by christopherfujino** [comment] 2021-02-02 18:16
> No, the cherry pick is not blocked. Updating `package:ffi` is blocked on this cherry pick.

I'm a little confused. Why is publishing a new version of `package:ffi` blocked on cherrypicking the dart change to the Flutter engine? `package:ffi` doesn't depend on Flutter, right?

And is it blocked by releasing the SDK? Meaning I have to do two releases, one with the dart patch, and second revving the pub package?

**Comment by dnfield** [comment] 2021-02-03 20:57
@dcharkes we should proabbly discuss if there's an option other than rolling packages to get this done. Rolling packages in a cherry pick is a bit more risky - we should avoid it if possible.

**Comment by dnfield** [comment] 2021-02-04 16:40
I may be incorrect on that. It seems like we're already rolling at least some packages for the release candidate, so we should be able to roll just this one too.

**Comment by dcharkes** [comment] 2021-02-04 16:47
@timsneath what is the progress on a `package:win32` release that depends on `ffi: ^0.3.0-nullsafety.1`?

**Comment by christopherfujino** [comment] 2021-02-04 20:04
@dcharkes FYI the flutter beta release with your engine change is out.

**Comment by lukepighetti** [comment] 2021-02-16 13:56
Getting this wall of red text anytime we use `flutter_cached_network_image`. Tracking issue here: https://github.com/Baseflow/flutter_cached_network_image/issues/541

**Comment by dcharkes** [comment] 2021-02-17 08:57
Repro on Flutter beta release before fix was in, and latest dev:
- 1.26.0-17.3.pre  Dart 2.12.0-259.8.beta
- 1.27.0-1.0.pre  Dart 2.13.0-0.0.dev

No repro on latest Flutter beta and latest Flutter master
- 1.26.0-17.6.pre  Dart 2.12.0-259.12.beta
- 1.27.0-2.0.pre.126  Dart 2.13.0-30.0.dev

https://gist.github.com/dcharkes/0ea37b831beeb023439d98296b25d0c7
