### ISSUE TITLE
Hot reload codelab experience: Step 5, part I

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13798] opened 2017-12-29 14:12 UTC
This bug is filed to track a suboptimal hot reload experience during a step in our primary codelab (https://codelabs.developers.google.com/codelabs/flutter/). Other similar bugs exist for other steps.

This bug tracks step 5, part I (Add an interactive text input field).

Before code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new FriendlychatApp());
}

class FriendlychatApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "Friendlychat",
      home: new ChatScreen(),
    );
  }
}

class ChatScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Friendlychat")),
    );
  }
}

```

After code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new FriendlychatApp());
}

class FriendlychatApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "Friendlychat",
      home: new ChatScreen(),
    );
  }
}

class ChatScreen extends StatefulWidget {
  @override
  State createState() => new ChatScreenState();
}

class ChatScreenState extends State<ChatScreen> {
  final TextEditingController _textController = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Friendlychat")),
      body: _buildTextComposer(),
    );
  }

  Widget _buildTextComposer() {
    return new Container(
      margin: const EdgeInsets.symmetric(horizontal: 8.0),
      child: new TextField(
        controller: _textController,
        onSubmitted: _handleSubmitted,
        decoration: new InputDecoration.collapsed(hintText: "Send a message"),
      ),
    );
  }

  void _handleSubmitted(String text) {
    _textController.clear();
  }
}

```

Result:
```
Reloaded 1 of 470 libraries in 372ms.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
type 'ChatScreen' is not a subtype of type 'StatelessWidget' of 'function result' where
ChatScreen is from
/Users/mit/Library/Developer/CoreSimulator/Devices/F49C5FF1-1784-4AC6-ACFD-C1D4222F3EDB/data/Containers/Data/Application/C52A7C9F-3328-4505-AE73-1A410B47A6C0/tmp/test011WLnNZ/test01/lib/main.dart
StatelessWidget is from package:flutter/src/widgets/framework.dart
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
Reloaded 1 of 470 libraries in 689ms.
Some program elements were changed during reload but did not run when the view was reassembled;
you may need to restart the app for the changes to have an effect.
• ChatScreenState (lib/main.dart:22)
• ChatScreen.createState (lib/main.dart:19)
```

Root causes:

   * Changing from Stateless to Stateful widget

**Comment by mit-mit** [comment] 2017-12-29 14:15
cc @rmacnak-google any way we can improve this error message?

**Comment by rmacnak-google** [comment] 2018-01-18 01:34
I'm confused why there's no stack trace for that exception. Perhaps overzealous stack trace filtering in the framework?

**Comment by Hixie** [comment] 2018-01-18 01:44
If it was on an iOS simulator, we had a bug in the log parsing that was stripping stack traces a few weeks ago.

**Comment by zoechi** [comment] 2019-01-17 14:52
Android output 
```
Initializing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 5358): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5358): The following assertion was thrown building Builder:
I/flutter ( 5358): type 'ChatScreen' is not a subtype of type 'StatelessWidget'
I/flutter ( 5358): 
I/flutter ( 5358): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5358): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5358): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5358):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5358): 
I/flutter ( 5358): When the exception was thrown, this was the stack:
I/flutter ( 5358): #0      StatelessElement.widget (package:flutter/src/widgets/framework.dart:3771:33)
I/flutter ( 5358): #1      Element.updateChild (package:flutter/src/widgets/framework.dart:2734:17)
I/flutter ( 5358): #2      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 5358): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #18     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 5358): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 5358): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 5358): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 5358): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 5358): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 5358): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5358): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #48     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 5358): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5358): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5358): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5358): #52     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 5358): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:685:20)
I/flutter ( 5358): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 5358): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5358): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5358): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 5358): #59     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 5358): #60     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 5358): #61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 5358): (elided one frame from package dart:async)
I/flutter ( 5358): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5358): Another exception was thrown: type 'ChatScreen' is not a subtype of type 'StatelessWidget'
Reloaded 1 of 421 libraries in 2,265ms.
I/flutter ( 5358): Another exception was thrown: type 'ChatScreen' is not a subtype of type 'StatelessWidget'
```
iOS output
```
Initializing hot reload...
Syncing files to device iPhone XR...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder:
flutter: type 'ChatScreen' is not a subtype of type 'StatelessWidget'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      StatelessElement.widget (package:flutter/src/widgets/framework.dart:3771:33)
flutter: #1      Element.updateChild (package:flutter/src/widgets/framework.dart:2734:17)
flutter: #2      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
flutter: #13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #59     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #65     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #69     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:685:20)
flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #76     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #77     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #78     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: type 'ChatScreen' is not a subtype of type 'StatelessWidget'
flutter: Another exception was thrown: type 'ChatScreen' is not a subtype of type 'StatelessWidget'
Reloaded 1 of 421 libraries in 1,153ms.
```

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 787FAF06-6F62-43F7-926C-A0C10DCA1E66 • ios         • iOS 12.1 (simulator)
```

**Comment by jonahwilliams** [comment] 2020-01-14 23:00
Closing as duplicate of https://github.com/flutter/flutter/issues/9811

**Closed by jonahwilliams** 2020-01-14 23:00 UTC
Labels: d: codelabs, documentation, passed first triage, t: hot reload
