### ISSUE TITLE
How to start a 'normal' Chrome instance? Chrome extensions are needed for development

### ISSUE THREAD

**Issue by hosseinkhojany** [flutter/flutter#108677] opened 2022-07-30 17:10 UTC
Some use-cases need extensions for development (e.g. the MetaMask extension injects a web3 object into every page).

Is there a way to start the 'normal' Chrome instance with flutter run -d chrome?

**Comment by ruchitmavani** [comment] 2022-07-30 17:20
duplicate of https://github.com/flutter/flutter/issues/43809

**Comment by hosseinkhojany** [comment] 2022-07-31 06:09
Honestly, this did not help at all. How can I use extensions when I put my program in debugging mode?

**Comment by exaby73** [comment] 2022-08-01 08:01
Hello @hosseinkhojany. You can use `flutter run -d web-server` to run the application, which then you'll be able to open in any browser, including extension enabled. You can then use the [Dart Debug Extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm) to debug your application. Let me know if this solved your issue

**Comment by rmschindler** [comment] 2022-08-11 15:06
I have the same issue: I desire to use a “normal” Chrome instance, not one which Flutter spins up. Furthermore, using `flutter run -d web-server`, which appears like an alternative, there is no “hot restart” functionality.

**Comment by exaby73** [comment] 2022-08-12 09:51
Marking as duplicate of https://github.com/flutter/flutter/issues/43809. If you disagree, please comment and we can reopen it

**Comment by rmschindler** [comment] 2022-08-12 18:59
Hi Nabeel (@exaby73), the fact that there is a duplicate issue (#43809) does not mean that this issue should be closed. That issue was closed due to non-activity; this issue was presumably opened again to address the same underlying problem (namely that `flutter run -d chrome` launches its own Chrome instance, and so presents certain limitations such as that extentions aren’t available).

**Comment by exaby73** [comment] 2022-08-15 06:45
@rmschindler https://github.com/flutter/flutter/issues/43809 was closed not because of inactivity but rather by @yjbanov. See [their comment](https://github.com/flutter/flutter/issues/43809#issuecomment-551310183).

I will reopen this issue for further insights from the team. Thank you for the feedback

**Comment by yjbanov** [comment] 2022-08-15 20:20
Looks like `--no-web-browser-launch` option is gone. However, extensions specifically are being addressed in https://github.com/flutter/flutter/pull/109157. Would it be fair to deduplicate this with https://github.com/flutter/flutter/issues/109156?

**Closed** 2022-09-05 21:10 UTC
Labels: new feature, tool, platform-web, proposal, r: timeout
