### ISSUE TITLE
Tooltips should not appear on mobile for Web

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55929] opened 2020-04-29 03:12 UTC
Tooltips appear (briefly) during clicks at gallery.flutter.dev.

As far as I know, iOS has no concept of tooltips, so these seem pretty awkward.  Also not sure that Android would show these briefly (not sure if it does, haven't tested an Android device).

![image](https://user-images.githubusercontent.com/11857803/80557692-9c5d2c00-898c-11ea-83be-b27215aad471.png)

**Comment by eseidelGoogle** [comment] 2020-04-29 03:13
See the "Back" tooltip appearing right as I click the back button in the Material Banner example.

**Comment by ferhatb** [comment] 2020-04-30 21:56
@eseidel : Have you tried connecting mouse/keyboard to iPad? tooltips should work in native. However in this case it is odd that it is seeing hover events.

**Comment by eseidelGoogle** [comment] 2020-04-30 21:59
it's possible my statement was overly broad. :)  I was using a finger on an iphone.  In that case tooltips were wrong, but it's possible the more general statement I made is incorrect.  Feel free to edit the bug as desired.

**Comment by ferhatb** [comment] 2020-05-06 21:50
@gspencergoog @goderbauer : Do we have special handling for which device the hover was initiated from ?

**Comment by goderbauer** [comment] 2020-05-06 22:16
PointerEvents have a `kind` property that say which device kind (mouse, touch, stylus, etc) generated the event: https://master-api.flutter.dev/flutter/gestures/PointerEvent/kind.html

As far as I can tell, tooltips should only trigger if you long-press a tooltip-enabled button or if you move with the mouse over it as per this code:

https://github.com/flutter/flutter/blob/bc5c46438ac6bac63bb872586c3edb84f4242384/packages/flutter/lib/src/material/tooltip.dart#L393-L410

Is it possible that on the web flutter incorrectly sees the touch events as mouse events to trigger the mouseregion?

/cc @dkwingsmt

**Comment by ferhatb** [comment] 2020-05-06 23:17
@goderbauer , thank you. That's exactly what i was looking for. We are probably not populating kind. I'll check web engine.

**Comment by ferhatb** [comment] 2020-05-14 22:46
@eseidelGoogle , i verified on latest gallery.flutter.dev, the tooltips don't show on touch, the engine sends correct pointer kind.

If you long press, it will show tooltip. Please reopen if you still see issue.

**Comment by eseidelGoogle** [comment] 2020-05-14 23:06
I just tried this again now.  Quick tap on the "back" chevron for me in the Material Banner example shows the "back" tooltip briefly before actually going back.  This is with the app saved as a PWA from mobile safari on my iPhone X.  Happy to work with you to repro.

Maybe my PWA is cached?  I'll check again.

**Comment by eseidelGoogle** [comment] 2020-05-14 23:07
Fresh load in Safari (after deleting the PWA) also shows the issue per above.  Maybe I need to clear my cache?

**Comment by ferhatb** [comment] 2020-05-14 23:28
Can't repro on either iPad6th gen or iPhone6. Quick touch on chevron, goes back with no tooltip. Long press on chevron shows the Back tooltip. Which iphone model ?

**Comment by eseidelGoogle** [comment] 2020-05-14 23:31
iPhone X.  Maybe I have something wrong with the phone.  Donno.

**Comment by eseidelGoogle** [comment] 2020-05-14 23:32
I cleared my cache and tried again in Safari and it still reproduced for me. 🤷‍♂️

**Comment by ferhatb** [comment] 2020-06-04 20:27
Verified tooltip failure on iPhone11 in simulator.

**Comment by pedromassangocode** [comment] 2020-09-02 10:09
I was not able to reproduce this with the latest Gallery website, has this been fixed by now? Tested with iPhone 11 Pro Max.

![gif](https://user-images.githubusercontent.com/67424416/91968528-af05ba00-ed0c-11ea-9d4c-acf608f7d254.gif)

**Comment by TheJulianJES** [comment] 2020-09-07 19:16
Seems to be fixed on the Flutter Dev website (tested on a physical iPhone X with iOS 14 Beta).

**Closed** 2022-04-13 12:56 UTC
Labels: framework, team: gallery, a: quality, platform-web, passed first triage, customer: web10, P4
