### ISSUE TITLE
[webview_flutter] [iOS] The initial cookies are set to previous WebView

### ISSUE THREAD

**Issue by mitsuki1995** [flutter/flutter#102804] opened 2022-04-29 03:41 UTC
## Steps to Reproduce

1. Execute `flutter run`(iOS) on the code sample(webview_flutter version: 3.0.2)
2. Wait for the first WebView
3. Click "show" button and wait for the second WebView
4. Click "print" button

**Expected results:** 
```
[FirstCookie] cookie: ${others};
[SecondCookie] cookie: ${others}; my_cookie_name=my_cookie_value
```

**Actual results:** 

Reproducing on devices and simulators.

iOS 13.6:
```
[FirstCookie] cookie: ${others}; my_cookie_name=my_cookie_value
[SecondCookie] cookie: ${others};
```

iOS 15.4:
```
[FirstCookie] cookie: ${others}; my_cookie_name=my_cookie_value
[SecondCookie] cookie: ${others}; my_cookie_name=my_cookie_value
```

On iOS 15.4 it works not bad in most cases. But on iOS 13.6, I can't find my cookies.
The only way to set cookies is calling CookieManager().setCookie **_after_** creating the second WebView

<details>
<summary>Code sample</summary>

```dart

import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WebView Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'WebView Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const url = "https://developer.apple.com/"; // any url
  static const domain = ".apple.com";

  bool show = false;
  WebViewController? secondController;
  WebViewController? firstController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Row(
            children: show
                ? [
                    _firstWebView(),
                    const SizedBox(width: 16),
                    _secondWebView(),
                  ]
                : [_firstWebView()],
          ),
          Row(children: [
            TextButton(
              onPressed: _showSecondWebView,
              child: const Text("show"),
            ),
            TextButton(
              onPressed: _printCookies,
              child: const Text("print"),
            )
          ])
        ],
      ),
    );
  }

  Widget _firstWebView() {
    return SizedBox(
      width: 100,
      height: 100,
      child: WebView(
        initialUrl: url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController controller) async {
          firstController = controller;
        },
      ),
    );
  }

  Widget _secondWebView() {
    // Future.delayed(Duration.zero, () {
    //   CookieManager().setCookie(const WebViewCookie(
    //     name: "my_cookie_name",
    //     value: "my_cookie_value",
    //     domain: domain,
    //   ));
    // });
    return SizedBox(
      width: 100,
      height: 100,
      child: WebView(
        initialUrl: url,
        initialCookies: const [
          WebViewCookie(
            name: "my_cookie_name",
            value: "my_cookie_value",
            domain: domain,
          )
        ],
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController controller) async {
          secondController = controller;
        },
      ),
    );
  }

  void _showSecondWebView() {
    show = true;
    setState(() {
      log("showSecondWebView");
    });
  }

  void _printCookies() async {
    log("cookie: ${await firstController?.runJavascriptReturningResult("document.cookie.toString()")}",
        name: "FirstCookie");
    log("cookie: ${await secondController?.runJavascriptReturningResult("document.cookie.toString()")}",
        name: "SecondCookie");
  }
}

```

</details>

![image](https://user-images.githubusercontent.com/38064997/165878545-3f1f4843-3d2a-4553-8de3-5246646cdbdf.png)

**Comment by darshankawar** [comment] 2022-04-29 09:23
@mitsuki1995 
Thanks for the report. I verified this on different iOS versions and devices namely, iOS simulator (15.2), iPhone 6+ (OS 12.4) and iPhone 6s (OS 15.3). On latest iOS versions, I do see the expected behavior as you reported, but on OS 12.4, it didn't load the first webview nor the second even after tapping on show and print.

OS 15.3:

<img width="339" alt="Screenshot 2022-04-29 at 2 51 20 PM" src="https://user-images.githubusercontent.com/67046386/165918094-92d18301-079c-4a46-a7d3-5f3839a0fd4a.png">


OS 12.4:

<img width="343" alt="Screenshot 2022-04-29 at 2 51 26 PM" src="https://user-images.githubusercontent.com/67046386/165918126-b50109b4-17bc-476e-8b22-d804d3ea04b0.png">


On iOS simulator 15.2, I get below in console log:

```
[log] showSecondWebView
[FirstCookie] cookie: my_cookie_name=my_cookie_value; s_vi=[CS]v1|3135D2CD8BDC06C7-60000C8946504011[CE]; s_cc=true; s_fid=48C1C6C98A98F301-2399808C2E11559F; s_pathLength=developer%3D1%2C; geo=IN
[SecondCookie] cookie: my_cookie_name=my_cookie_value; s_vi=[CS]v1|3135D2CD8BDC06C7-60000C8946504011[CE]; s_cc=true; s_fid=48C1C6C98A98F301-2399808C2E11559F; s_pathLength=developer%3D1%2C; geo=IN
```

So it seems on lesser iOS versions, it's not showing properly and hence you might be seeing the behavior you reported.



> The only way to set cookies is calling CookieManager().setCookie **_after_** creating the second WebView

Is that an acceptable solution for you ?

**Comment by mitsuki1995** [comment] 2022-04-29 16:35
> So it seems on lesser iOS versions, it's not showing properly and hence you might be seeing the behavior you reported.
> 
> >

I don't know why it was not showing properly. But in my case, these two WebViews worked and my cookie was set to the first one.

Here is My log: 
```
[log] showSecondWebView
[FirstCookie] cookie: s_vi=[CS]v1|31360982D7FF3CAB-4000146809416A4D[CE]; s_fid=4BA9E806D4BBC2BC-2B047B231A190E61; s_pathLength=developer%3D5%2C; my_cookie_name=my_cookie_value; s_cc=true
[SecondCookie] cookie: s_vi=[CS]v1|31360982D7FF3CAB-4000146809416A4D[CE]; s_cc=true; s_fid=4BA9E806D4BBC2BC-2B047B231A190E61; s_pathLength=developer%3D5%2C
```

**Comment by darshankawar** [comment] 2022-05-02 04:48
@mitsuki1995 
Does that mean the issue is resolved and can be closed ?

**Comment by mitsuki1995** [comment] 2022-05-05 01:59
> @mitsuki1995 Does that mean the issue is resolved and can be closed ?

Yes. Thanks for the comments.

**Comment by darshankawar** [comment] 2022-05-05 05:00
Closing as resolved.

**Closed by darshankawar** 2022-05-05 05:00 UTC
Labels: in triage
