### ISSUE TITLE
Android apps aren't loading or loading with black screen (in emulators)

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#10617] opened 2017-06-11 00:11 UTC
Android renders black. 

![screen shot 2017-06-10 at 5 08 01 pm](https://user-images.githubusercontent.com/1326504/27007209-8a1c2ddc-4dff-11e7-9e21-9e244335c12d.png)

## Steps to Reproduce

1. Create an AVD with Google Play Services.  Select Android O api 26, or api 24, with Google Play Services. Having Google Play Services will prevent you from changing the GLES in the emulator. At least at this time. 
2. Start up and try to debug a flutter project on Android AVD you just created.

Here is an example of the settings of the emulator with Google Play Services and Android O
![screen shot 2017-06-14 at 11 32 44 am](https://user-images.githubusercontent.com/1326504/27148459-42eddde0-50f5-11e7-8792-8ca1c3737c8c.png)

- I suspect if you select Hardware GLES 2.0 it will do the same thing. 

## Logs

No issues found!

## Flutter Doctor

```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 81eb140411 (24 hours ago), 2017-06-09 17:30:04 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 7.1.1 (API 25) (emulator)
    • iPhone 7                     • 458BC4FE-8205-4369-8718-193B9FC88C8B • ios         • iOS 10.3 (simulator)
```
- Note: I'm using the Community edition to debug.

**Comment by branflake2267** [comment] 2017-06-11 00:19
Same thing with Android O emulator. 
```
/Users/branflake2267/git/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 81eb140411 (24 hours ago), 2017-06-09 17:30:04 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

Process finished with exit code 0
```

![screen shot 2017-06-10 at 5 19 35 pm](https://user-images.githubusercontent.com/1326504/27007253-0619731c-4e01-11e7-97d1-216c52bd1778.png)

**Comment by branflake2267** [comment] 2017-06-11 18:58
The problem is I wasn't running the AVD with Software GLES 2.0. I was trying to use an AVD with Google Play Services and this is not possible to turn on software GLES with Google Play services. 

![screen shot 2017-06-11 at 11 50 57 am](https://user-images.githubusercontent.com/1326504/27013672-4e86c126-4e9d-11e7-9b2d-8eaf650bdc73.png)

**Comment by branflake2267** [comment] 2017-06-11 19:02
By the way, I had forgotten to create the AVD with this method so I'd suggest adding this to the doctor detection. But I suspect it's a matter of time before before hardware is support, and documentation is the best route in the meantime. So this could be closed if that's the case.

**Comment by chinmaygarde** [comment] 2017-06-11 23:40
We recently enabled software rendering on Android. Right now, it is behind a flag to `flutter run`. The patch that landed this was https://github.com/flutter/flutter/commit/a367dcb02c4cd20c20f82d389d67257a5b9c4359. Can you try adding `--enable-software-rendering` to the `run` call and check to see if that fixes your issue. We are investigating how the emulators fail when the OpenGLES is not enabled on the same so we can fallback to software rendering automatically.

**Comment by branflake2267** [comment] 2017-06-12 01:06
Nice. I tested it, and both command line execution and IDE launcher execution with the flag `--enable-software-rendering` work. I tested on android O AVD. 

`flutter run --enable-software-rendering -d emulator-5556`
or
![screen shot 2017-06-11 at 5 55 05 pm](https://user-images.githubusercontent.com/1326504/27016102-989f7004-4ed0-11e7-8a09-a927c8c42795.png)

**Comment by chinmaygarde** [comment] 2017-06-12 01:58
Good to know. I'll investigate how to automatically turn on software rendering on the emulators. The flag is rather obscure ATM. About adding a `doctor` check to ensure that OpenGLES is available on the emulators (either emulated or via host passthrough), I am not actually sure how that would be implemented. @jason-simmons or @eseidelGoogle might have ideas.

**Comment by eseidelGoogle** [comment] 2017-06-12 14:34
@chinmaygarde flutter detect at runtime that opengles isn't available and switch to software? (I thought you or @GaryQian added some version of such already?)

**Comment by chinmaygarde** [comment] 2017-06-12 16:20
There is definitely a fallback path in the code. But that depends on EGL initialization failing. What seems to be happening on the emulators is EGL initialization succeeding even without OpenGL support. We might need to investigate how initialization fails on the emulators to add more validity checks.

**Comment by eseidelGoogle** [comment] 2017-06-13 06:38
Is this related to https://github.com/flutter/flutter/issues/8127 ?

**Comment by eseidelGoogle** [comment] 2017-06-13 18:10
@lukef says he's stuck on this and doesn't know how to move past this.  He's advise his team not to upgrade to the latest version of their app.   We need to get him some help debugging or a workaround today. :/

**Comment by chinmaygarde** [comment] 2017-06-13 19:18
The emulators seems to be sensitive to the Android API version as well as the host platform. The Android emulator configuration we are trying to get working here is: Nexus 5x with Google Play Store Image on API 25. @jason-simmons on his Linux workstation was able to get create the AVD with host GPU passthrough working just fine. This was even though the "Emulator Performance" option was disabled for him too exactly like [described in the comment above](https://github.com/flutter/flutter/issues/10617#issuecomment-307649207). I, on the other hand, on a Mac workstation could not even launch the emulator at that configuration (QEMU crashes). We are still trying to reproduce the issue as described so we can figure out how to correct the software rasterizer fallback and/or warn the user that the AVD is not correctly configured for optimum performance.

In the meantime, possible workarounds for this particular issue are:
1. Switch to an emulator where you can select Hardware OpenGLES as an "Emulated Performance" option.
2. Explicitly use the software backend using the `--enable-software-rendering` flag as described in [the comment above](https://github.com/flutter/flutter/issues/10617#issuecomment-307669448). In this case, the performance of the emulator may be poor. This can be partially addressed by lowering the resolution of the AVD created.
3. Switch to using a an actual device for rendering.

Since this issue only affects some emulator configuration on some platforms and there are (admittedly poor) workarounds, I am going to remove the `TODAY` tag from this ticket.

**Comment by lukef** [comment] 2017-06-14 18:12
I've reproduced this on 2 separate machines now. Using flutter `master` and Android Emulator `26.1.1`.

**Comment by wmaxfield** [comment] 2017-06-14 18:23
The problem is your official flutter documentation states to set up hardware GLES 2.0 emulation. This fails, at least on a Macintosh OS 10.9.5, iMac 27".  If you select Automatic or Hardware, you will show black.  If you select SOFTWARE GLES 2.0 then it shows.  I suspect that the performance will suck in that case.  It may be a case of older drivers on the Macintosh.  I run older OS because of stability, and use VMWare if I must bump up to recent OS for SAR. (Stupid Apple Reasons)

**Comment by lukef** [comment] 2017-06-14 19:00
@chinmaygarde - "Switch to an emulator where you can select Hardware OpenGLES as an "Emulated Performance" option." does not work at all. Switching to "Hardware - GLES 2.0" results in a black screen. Using Software rendering renders the emulator unusable. I'm not really sure why you would remove the Today badge as this seems like a critical issue to me. 

Using a device isn't always an option and it slows down development times considerably.

**Comment by eseidelGoogle** [comment] 2017-06-14 20:18
@branflake2267 and @lukef  can you tell us more about the hardware you're running on?

I was able to reproduce just now following the steps @branflake2267 gave.  I'm on a MacBookPro13,3 with macOS 10.12.5 (16F73) Intel HD Graphics 530.  I'm using:

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /src/flutter
    • Framework revision 1a1bbacf0d (14 hours ago), 2017-06-13 23:22:58 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by lukef** [comment] 2017-06-14 20:22
My 2 devices are:

MacBookPro13,2
Intel Core i5
Intel Iris Graphics 550 (1536 MB)

iMac14,2
Intel Core i5
NVIDIA GeForce GT 755M (1024MB)

**Comment by eseidelGoogle** [comment] 2017-06-14 21:18
I've asked @cbracken to drive this to resolution.

**Comment by eseidelGoogle** [comment] 2017-06-14 21:56
We've had at least two more reports of this this morning.  Given that it's 3pm, I don't expect we'll complete this today, but we definitely need to get to a place where we aren't stranding users in this state.  Once they hit a black screen we don't provide any feedback or any explanation as to how to fix their setup.

**Comment by eseidelGoogle** [comment] 2017-06-14 22:10
I've just confirmed that flutter 0.0.8 (1a1bbacf0d16c1780377ea77580ec3b05c387f88) has this black screen bug, but that flutter 0.0.7 (e2f54df5ab96808060c4f91bee0274b2fc126afe) does not.

**Comment by eseidelGoogle** [comment] 2017-06-14 22:16
The AVD I'm using is:
```
Available Android Virtual Devices:
    Name: Nexus_5X_API_26
  Device: Nexus 5X (Google)
    Path: /Users/eseidel/.android/avd/Nexus_5X_API_26.avd
  Target: Google Play (Google Inc.)
          Based on: Android API 26 Tag/ABI: google_apis_playstore/x86
    Skin: nexus_5x
  Sdcard: 100M
```

**Comment by branflake2267** [comment] 2017-06-14 22:24
I noticed someone running an emulator without the option to select Hardware acceleration settings.

**Comment by eseidelGoogle** [comment] 2017-06-14 22:26
@jason-simmons is debugging.  https://github.com/flutter/engine/commit/ffe8181ffe7432b61a67323c80fd8025704e4695 is the current suspected culprit.

**Comment by jason-simmons** [comment] 2017-06-14 22:29
Try upgrading to the latest version of the Android emulator and running it from the command line with the various graphics accelerator options described in:
    https://developer.android.com/studio/run/emulator-acceleration.html#accel-graphics

`-gpu swiftshader` in particular may be useful

**Comment by eseidelGoogle** [comment] 2017-06-14 22:38
I'm using `Android emulator version 26.0.3.0 (build_id 3965150)` which only seems to support:
```
     on       -> enable GPU emulation
     off      -> disable GPU emulation
     auto     -> use the setting from the AVD (default)
     enabled  -> same as 'on'
     disabled -> same as 'off'
     guest    -> use guest-side OpenGL ES implementation
```
Is there a newer emulator I'm missing?

**Comment by lukef** [comment] 2017-06-14 22:39
There is a v26.1.1 also

**Comment by eseidelGoogle** [comment] 2017-06-14 22:41
I'm on the stable channel for Android Studio, it seems to think I'm up to date.  Maybe I need to move to beta dev or canary to pull more recent tooling?

**Comment by lukef** [comment] 2017-06-14 22:43
I think it's up to you really but I'd say a large majority of Android devs will have to use the canary builds as well to test their apps on the latest version.

**Comment by smrtsmrf** [comment] 2017-06-14 22:46
I don't have Android studio on my Mac (I know I could install it). Currently I'm using a solution I use for Ionic which allows me to run ```android avd``` from the command line and I can see my emulators and create new ones. Hardware acceleration is not an option. However, i can start the emalator from the command line, and using the -gpu flag mentioned above makes it work, choosing the guest option. The console logs are noisy (and possibly an indication of problems?) but it works

**Comment by eseidelGoogle** [comment] 2017-06-14 22:53
I'm now using `Android emulator version 26.1.1.0 (build_id 4051520) (CL:f55e2eef2479f03d2fa4619a7e723a32b60172b1)`, but I still only see the gpu options in https://github.com/flutter/flutter/issues/10617#issuecomment-308577889.

**Comment by goderbauer** [comment] 2017-06-15 00:11
This should be fixed on channel `master`. I am working on updating the `alpha` channel.

**Comment by goderbauer** [comment] 2017-06-15 01:04
I reverted the color correctness patch in the engine (see https://github.com/flutter/flutter/issues/10710) to fix the issue. This is causing some colors to render slightly different (see https://github.com/flutter/flutter/issues/10655). 

I am closing this bug as it is fixe in `master` and `alpha` now.

**Comment by mattsarett** [comment] 2017-06-15 15:45
Has anyone been able to reproduce this on Linux?  Or is this Mac only?

**Comment by eseidelGoogle** [comment] 2017-06-15 16:17
@mattsarett my impression is it's Mac only.

**Comment by mattsarett** [comment] 2017-06-15 16:22
Thanks!  On Linux I'm seeing that the query for GL sRGB support is failing.  So we are correctly falling back to GL non-color correct rendering (though it would be better to fall back to color correct rendering in software - this seems like a separate issue).  If I try to force GL sRGB correct rendering, I get the black screen.

I need to get an Android on Mac environment set up.  But my shot in the dark guess is that the GL query is suggesting sRGB support is available, when it is actually not...

**Comment by mattsarett** [comment] 2017-06-15 19:14
Alright I've determined the cause of this.  The Android emulators GL on Mac only supports 4444 pixel config (not even regular 8888!).  My CL (somewhat intentionally) dropped 4444 as a fallback rendering config.

When I reland, I'll make sure not to break this again.

Given the GL limitations of Android emulators on both Mac and Linux, I think we ought to consider falling back to software in these cases.

**Comment by branflake2267** [comment] 2017-06-15 19:32
Are the windows emulators faster?

**Comment by eseidelGoogle** [comment] 2017-06-15 19:39
@mattsarett Would the only-supports 4444 also explain bugs like https://github.com/flutter/flutter/issues/9965 ?

**Comment by mattsarett** [comment] 2017-06-15 19:55
Yes, absolutely.

**Comment by Tobiaswk** [comment] 2017-07-18 15:06
Can confirm it is not working on Linux. I'm on Arch linux running an emulator with hardware acceleration.

```
Name: Nexus_5X_API_25
  Device: Nexus 5X (Google)
    Path: /home/tobias/.android/avd/Nexus_5X_API_25.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 7.1.1 (Nougat) Tag/ABI: google_apis/x86_64
    Skin: nexus_5x
  Sdcard: 100M
```

```
Running flutter doctor...
[✓] Flutter (on Linux, locale da_DK.UTF-8, channel alpha)
    • Flutter at /home/tobias/workspace/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/tobias/bin/android-sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /home/tobias/bin/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • None
```

**Comment by Hixie** [comment] 2017-07-18 20:30
@Tobiaswk Can you check if it works for you on the master channel?

**Comment by Hixie** [comment] 2017-07-18 20:31
Our suspicion is that this may be fixed on master and will be fixed on alpha when we roll alpha, which will hopefully be soon.

**Comment by Hixie** [comment] 2017-07-18 20:31
We also really really need tests for this so that we don't unknowingly regress it again.

**Comment by Hixie** [comment] 2017-07-18 20:32
Assigned to Jason to confirm if it is broken right now on master (not to fix).

**Comment by Tobiaswk** [comment] 2017-07-19 15:36
@Hixie Experiencing the same problem on master channel.

```
[✓] Flutter (on Linux, locale da_DK.UTF-8, channel master)
    • Flutter at /home/tobias/workspace/flutter
    • Framework revision e13e7806e3 (4 hours ago), 2017-07-19 07:22:38 -0400
    • Engine revision c757fc7451
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/tobias/bin/android-sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /home/tobias/bin/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```

**Comment by mmartin101** [comment] 2017-07-22 05:29
Experiencing the same behavior as @Tobiaswk on Ubuntu 17.04 using the master channel

**Comment by rebit03** [comment] 2017-07-22 15:14
I have the problem on master on Win10, this is what I get
![black_screen](https://user-images.githubusercontent.com/4527037/28492315-239c4e3e-6f01-11e7-976e-fdbb2f16737f.jpg)
on alpha I get completely black screen

**Comment by Hixie** [comment] 2017-08-01 20:16
We are unable to reproduce any of the recently-reported issues on master.

We are going to close this bug. If you still hit a problem similar to the ones reported here, please file a new bug. Please test on the master channel as well, and let us know what your setup is, where it fails, any messages you get, and so forth.

**Comment by Tobiaswk** [comment] 2017-08-05 10:33
I'm sad to say... but I'm still having this problem. I'm on the master channel. Maybe there is more to this?

```
[✓] Flutter (on Linux, locale da_DK.UTF-8, channel master)
    • Flutter at /home/tobias/workspace/flutter
    • Framework revision 4da5e9b249 (10 hours ago), 2017-08-04 17:44:20 -0700
    • Engine revision 73afec4081
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/tobias/bin/android-sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /home/tobias/bin/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```

**Comment by eseidelGoogle** [comment] 2017-08-05 17:44
@chinmaygarde @jason-simmons @brianosman  What is the proper information to collect here?

**Comment by brianosman** [comment] 2017-08-07 14:37
I'm also unable to repro this on the emulator. Even if I force it to use software graphics, it looks bad (4444) but still renders more-or-less correct. Things I'd like to see/know:

1) What setting is enabled on the AVD configuration (is Emulated Performance set to Hardware or Software).
2) What OpenGL ES API level is being emulated? In the emulator, 'Extended Controls...', 'Settings'
3) What graphics card (and driver version, if you know) do you have on your host PC?

**Comment by eseidelGoogle** [comment] 2017-08-07 14:59
Sound like good things to add to https://github.com/flutter/flutter/issues/11402 :)

**Comment by Tobiaswk** [comment] 2017-08-07 15:08
@brianosman 
1. Hardware
2. OpenGL ES 2.0
3. Below is the output from ```lspci -vnn | grep VGA -A 12```
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:5916] (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device [17aa:224b]
	Flags: bus master, fast devsel, latency 0, IRQ 127
	Memory at eb000000 (64-bit, non-prefetchable) [size=16M]
	Memory at a0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

I hope we can get to the bottom of this ;)

**Comment by brianosman** [comment] 2017-08-07 15:19
@Tobiaswk Does changing the AVD configuration to Software fix the black screen. That's obviously not ideal, but might help us narrow down if it's actually a problem with the Intel driver implementation that's bubbling up to the emulator.

**Comment by Tobiaswk** [comment] 2017-08-07 15:34
@brianosman It makes no difference whether I select hardware or software emulation. It results in a black screen in both cases.

**Comment by brianosman** [comment] 2017-08-07 16:20
Hmm. Okay. Are you getting the same 'Calling unimplemented GLES API' message from earlier reports? And just to make sure - the emulator itself tends to work fine, but launching a flutter app just produces a black screen? Is this with all apps (if you try to run the flutter_gallery example, does that do the same thing?)

Paging @drWulf, who might have another idea.

**Comment by Tobiaswk** [comment] 2017-08-07 16:46
@brianosman Not getting the earlier reported 'Called unimplemented GLES API'. Everything else works with the emulator. I've tried non-flutter projects... they render fine. I tried the flutter_gallery example and also produces a black screen.

It does actually come with some other strange OpenGL related errors or messages. This is when launching flutter_gallery example project;
```
08-07 18:41:34.542 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
08-07 18:41:34.543 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
08-07 18:41:34.543 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
08-07 18:41:34.553 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008f38
08-07 18:41:34.555 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x000090ca
08-07 18:41:34.556 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x000090ce
08-07 18:41:34.558 3588-3588/io.flutter.examples.gallery E/eglCodecCommon: glUtilsParamSize: unknow param 0x000090cf
08-07 18:41:34.578 3588-3604/io.flutter.examples.gallery D/EGL_emulation: eglMakeCurrent: 0x7589955fb4a0: ver 3 1 (tinfo 0x7589b5da5300)
08-07 18:41:34.654 3588-3611/io.flutter.examples.gallery D/EGL_emulation: eglMakeCurrent: 0x7589b8664d20: ver 3 1 (tinfo 0x7589b868a940)
```

**Comment by drWulf** [comment] 2017-08-07 17:47
@Tobiaswk Can you upload your .avd directory and .ini file for your the emulator instance that is giving you problems?  I assume the resulting file size will larger that what can be attached to an issue so you will probably have to link to it from elsewhere.

Having the offending AVD will help us to determine if it a specific interaction with your hardware or in the interaction of flutter with that particular AVD instance.

**Comment by Tobiaswk** [comment] 2017-08-07 18:04
**I have a breakthough! I got it to work!** I manually edited the ```advancedFeatures.ini``` in the AVD directory.

Before my edit;
```
GrallocSync = on
EncryptUserData = on
IntelPerformanceMonitoringUnit = on
LogcatPipe = on
GLDMA = on
GLAsyncSwap = on
GLESDynamicVersion = on
Wifi = on
```

I changed the ```GLESDynamicVersion``` to ```off```;
```
GrallocSync = on
EncryptUserData = on
IntelPerformanceMonitoringUnit = on
LogcatPipe = on
GLDMA = on
GLAsyncSwap = on
GLESDynamicVersion = off
Wifi = on
```

The ```GLESDynamicVersion``` setting you can't change in any of the UI's provided my Google to my knowledge.

Now it works with either software or hardware emulation.

**Comment by cport1** [comment] 2017-08-08 19:13
@mmartin101 I am also getting this error on Ubuntu 17

**Comment by mmartin101** [comment] 2017-08-08 19:49
@cport1 are you using master? I checked again using master on Aug 1st and everything was working correctly. I will check again tonight.

**Comment by mmartin101** [comment] 2017-08-09 05:58
@cport1 Just checked again using the latest master. Still getting the black screen :cry:.

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/mmartin/flutter
    • Framework revision 3b76e7e258 (7 hours ago), 2017-08-08 15:46:47 -0700
    • Engine revision f0d440bec3
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/mmartin/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /home/mmartin/Android/Sdk
    • Java binary at: /home/mmartin/Apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/mmartin/Apps/android-studio-preview
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/mmartin/Apps/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by Tobiaswk** [comment] 2017-08-09 10:22
@mmartin101 Have you tried what I did?  I manually edited the ```advancedFeatures.ini``` in the AVD directory. Set ```GLESDynamicVersion``` to ```off```;

**Comment by cport1** [comment] 2017-08-09 12:24
@Tobiaswk where can I find the AVD directory?

**Comment by mmartin101** [comment] 2017-08-09 13:48
@Tobiaswk I do not have an `advancedFeatures.ini` file in my avd directory

Android Emulator was updated to 26.1.3 this morning, but doesn't look like Google has put out the release notes just yet https://developer.android.com/studio/releases/emulator.html.

After updating I tried running my flutter app, still black screen. I tried to manually add the `advancedFeatures.ini` file and set `GLESDynamicVersion` to off, still black screen.

I finally just deleted all AVDs using the AVD Manager and created a new one using API 24 (Nexus 5X). Now my flutter app to displays properly, no more black screen :)

**Comment by cport1** [comment] 2017-08-09 13:57
API 24 gives me the same results.

**Comment by Tobiaswk** [comment] 2017-08-17 18:32
@cport1 I'm on Linux; ```/home/tobias/bin/android-sdk/system-images/android-25/google_apis/x86_64```

**Comment by hkirk** [comment] 2017-08-31 08:59
I can reproduce the black screen on Win10, with the emulator set to automatically between software and hardware on both API 25 and 26. 
Forcing it to using Software - GLES 2.0 seem to fix it.

Version:

    $ flutter --version
    Flutter • channel alpha • https://github.com/flutter/flutter.git
    Framework • revision b156a0f054 (3 weeks ago) • 2017-08-11 22:01:40 -0700
    Engine • revision fef7d827d6
    Tools • Dart 1.25.0-dev.9.0

Doctor:

    Running flutter doctor...
    [√] Flutter (on Microsoft Windows [Version 10.0.14393], locale da-DK, channel alpha)
        • Flutter at C:\Users\au181645\flutter
        • Framework revision b156a0f054 (3 weeks ago), 2017-08-11 22:01:40 -0700
        • Engine revision fef7d827d6
        • Tools Dart version 1.25.0-dev.9.0
    
    [√] Android toolchain - develop for Android devices (Android SDK 26.0.1)
        • Android SDK at C:\Users\au181645\AppData\Local\Android\sdk
        • Platform android-26, build-tools 26.0.1
        • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    
    [√] Android Studio (version 2.3)
        • Android Studio at C:\Program Files\Android\Android Studio
        • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    
    [√] Android Studio (version 3.0)
        • Android Studio at C:\Program Files\Android\Android Studio Preview
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    
    [√] IntelliJ IDEA Ultimate Edition (version 2017.2)
        • Flutter plugin version 16.0
        • Dart plugin version 172.3968.20
    
    [√] Connected devices
        • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

**Comment by levrik** [comment] 2017-09-03 10:51
Just hit this issue out of the blue yesterday. Was working on app, restarted the emulator, built again and it turned black. Didn't change anything on the emulator or the code...

**Comment by lianyueforever** [comment] 2017-09-17 04:00
if you don't find"advancedFeatures.ini",you can creat it

**Comment by 741g** [comment] 2017-09-20 17:32
Hi, I work on the Android Emulator and just came across this. Thanks for the detailed debugging effort everyone.

In the future, if it's an emulator issue like this one please file a bug through issuetracker.google.com, component Android Emulator (https://issuetracker.google.com/issues/new?component=192727&template=843117).

The root problem seems to be that the host GPU driver doesn't necessarily support the framebuffer/renderbuffer format used by Flutter here. I'm looking into workarounds.

I've filed https://issuetracker.google.com/issues/66172607 to track this for the emulator. We should be able to support Flutter in GLESv3 mode soon.

Best,

Frank

**Comment by 741g** [comment] 2017-09-20 18:14
I've investigated and found the proximate cause leading to black screen on emulator: https://issuetracker.google.com/issues/66172607

There is a fixed system image linked in there (API 26 Google APIs x86 32-bit)

Seems like the Flutter framework calls glUnmapBufferOES even for buffers mapped without the OES suffix(glMapBufferRange), and that's what's breaking the emulator in GLES3 mode. We expect, perhaps too optimistically, buffers to be unmapped with glUnmapBuffer (no OES suffix).

We'll have that fixed with future revisions of emulator system images.

It's definitely a behavior that the emulator should support (since real apps are using it), but I'd recommend using glUnmapBuffer() instead (without the OES suffix), as that's more canonical OpenGL ES 3 usage; you're using the mapped buffer API in a way that follows the core spec strictly.

**Comment by eseidelGoogle** [comment] 2017-09-20 18:20
Unclear where the glUnmapBufferOES call is.

I don't see it in Flutter:
https://github.com/flutter/engine/search?utf8=%E2%9C%93&q=glUnmapBufferOES&type=
or Skia:
https://cs.chromium.org/search/?q=glUnmapBufferOES+file:%5Esrc/third_party/skia/+package:%5Echromium$&type=cs
@chinmaygarde or @brianosman might know.

**Comment by 741g** [comment] 2017-09-20 18:25
Right, that is strange.

https://cs.chromium.org/chromium/src/third_party/skia/src/gpu/gl/GrGLBuffer.cpp?type=cs&q=unmap+file:%5Esrc/third_party/skia/+package:%5Echromium$&l=234

Judging from how this looks, that should just call glUnmapBuffer. Need to make sure it's that way all the way down, though.

**Comment by 741g** [comment] 2017-09-20 18:27
I think I found something:

https://cs.chromium.org/chromium/src/third_party/skia/src/gpu/gl/GrGLAssembleInterface.cpp?q=unmap+file:%5Esrc/third_party/skia/+package:%5Echromium$&dr=C&l=805

populates glUnmapBufferOES, but the check below:

    if (version >= GR_GL_VER(3,0)) {
        GET_PROC(MapBufferRange);
        GET_PROC(FlushMappedBufferRange);
    } else if 

doesn't also GET_PROC(UnmapBuffer)

**Comment by sethladd** [comment] 2017-09-20 18:40
@741g thanks for taking a look! :)

**Comment by brianosman** [comment] 2017-09-20 18:56
Thanks! I'll look into patching Skia to fix this.

**Comment by brianosman** [comment] 2017-09-20 20:19
Fix landed in Skia: https://skia.googlesource.com/skia/+/8d4a5c75f07a70f71320a426f392783dbcf180ba#

**Comment by 741g** [comment] 2017-09-20 20:20
Awesome, thanks for the fix!

**Comment by goderbauer** [comment] 2017-09-25 18:07
I was able to verify that the the fix in skia actually fixed the black emulator screen on my Windows machine. Thank you so much @741g for debugging it and @brianosman for the quick fix!

**Comment by sethladd** [comment] 2017-09-25 18:15
Thanks everyone!

**Comment by collinjackson** [comment] 2017-09-26 20:10
Looks like this was fixed, closing

**Closed by collinjackson** 2017-09-26 20:10 UTC
Labels: customer blocker, customer: posse (eap), prod: engine, regression, ▣ platform-android, ⚠ TODAY

**Comment by HussainAlrebeh** [comment] 2018-11-19 09:07
> Just hit this issue out of the blue yesterday. Was working on app, restarted the emulator, built again and it turned black. Didn't change anything on the emulator or the code...
> 
> Edit: Fixed it by setting "OpenGL ES API Level" to "Compatibility (OpenGL ES 1.1/2.0)".
> ![image](https://user-images.githubusercontent.com/9491603/30002450-1266e230-90aa-11e7-9dfc-7c332715a7a1.png)
> 
> @mmartin101 Try the above if you don't have a `advancedFeatures.ini`.

This one fixed it for me. Thank you
