### ISSUE TITLE
Android：A blank screen appears when open a webview after using the method “pushAndRemoveUntil” twice 

### ISSUE THREAD

**Issue by a940582450** [flutter/flutter#77145] opened 2021-03-03 13:38 UTC
## Steps to Reproduce

Env：
手机：Vivo
android version：android 8.1

1. 使用pushAndRemoveUntil方法进入任意page.（比如：登录成功后进入主界面）
2. 再使用pushAndRemoveUntil方法进入另一page（比如：从主界面退出登录）
3. 使用webview_flutter或者flutter_inappwebview进入任意的webview页面
4. 此时可以看到webview页面盖着一层黑色的遮罩，点击或者滑动这个遮罩，遮罩会消失

**Expected results:** 
正常情况下，黑色的遮罩不应该出现

**Actual results:** 
如果不点击或者触摸黑色的遮罩，那么打开任意的网页，它都会出现

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

```

</details>

**Comment by TahaTesser** [comment] 2021-03-03 14:31
Hi @a940582450 
You seem to be using a very old Flutter version
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and `flutter run --verbose` logs  while connected Vivo device and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example and the webiew version
Thank you

**Comment by a940582450** [comment] 2021-03-04 09:50
Thanks for your reply.

经过不断的尝试，我发现当routes的层级大于等于3层时，再次打开任意webview，就会出现黑屏现象。

我也不知道如何才能提供一个 [minimal complete reproducible code sample]，所以我把下面的代码贴了上来。

如果这些信息仍然不够，请告诉我，我再来想办法提供完整的代码。
<details>
  <summary>webview</summary>

```
webview_flutter: ^1.0.7

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
class UWWebView extends StatefulWidget {
  UWWebView({Key key,
    @required this.url,
    this.title});
  String url;
  final String title;
  @override
  State<StatefulWidget> createState() {
    return new _UWWebViewState();
  }
}
class _UWWebViewState extends State<UWWebView> {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Builder(builder: (BuildContext context){
        return WebView(
            initialUrl: widget.url,
        );
      },),
    );
  }
}
```

</details>

<details>
  <summary>reproduce</summary>

```
1.使用Navigator.of(context).pushNamed(Routes.username);进行两次页面跳转；
2.再次打开任意webview：
Navigator.push( context,
        MaterialPageRoute(builder: (context) {
        return UWWebView(
          url:'https://www.baidu,com',
          title: 'test',
        );
      })
    );
3.黑屏现象就会出现
```

</details>

<details>
  <summary>flutter doctor --verbose</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.14.6 18G103 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/xxx/Documents/last_flutter/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • V1730EA (mobile) • 4b928638 • android-arm64 • Android 8.1.0 (API 27)
```

</details>

**Comment by a940582450** [comment] 2021-03-04 13:07
My conclusion was wrong.
It's actually the same problem with https://github.com/flutter/flutter/issues/74716.
The main reason is that an obscureText attribute in textfield trigger.

**Comment by TahaTesser** [comment] 2021-03-04 13:25
Hi @a940582450 
Thanks for the confirmation, unfortunately, I don't have a Vivo device to reproduce
Closing as duplicate of https://github.com/flutter/flutter/issues/74716
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-04 13:25 UTC
Labels: in triage
