### ISSUE TITLE
[Slider] TickMark and Thumb are not correctly aligned if the trackHeight is increased

### ISSUE THREAD

**Issue by guenth39** [flutter/flutter#108007] opened 2022-07-20 12:12 UTC
## Steps to Reproduce

I have created a dartpad to reproduce this issue, but it can also be reproduced on iOS and Android.
https://dartpad.dev/?id=b91a1c5345cd41b16156ebdae036618e

**Expected results:** 
The thumb and the tick marks are perfectly aligned, like it is if the trackHeight is not changed.

**Actual results:** 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/29251617/179978698-3aec6710-c0c3-459b-9000-2a1545c56a0b.png">

<details>
<summary>Code sample</summary>

```dart
class CustomSlider extends StatefulWidget {
  const CustomSlider({Key? key}) : super(key: key);

  @override
  State<CustomSlider> createState() => _CustomSliderState();
}

class _CustomSliderState extends State<CustomSlider> {
  double _value = .5;

  @override
  Widget build(BuildContext context) => SliderTheme(
        data: const SliderThemeData(
          trackHeight: 40,
        ),
        child: Slider(
          value: _value,
          onChanged: (value) => setState(() {
            _value = value;
          }),
          min: 0,
          max: 10,
          divisions: 10,
        ),
      );
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2022-07-21 11:00
duplicate of https://github.com/flutter/flutter/issues/62567

**Closed by TahaTesser** 2022-07-21 11:00 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.0, found in release: 3.1
