### ISSUE TITLE
[flutter_lints] The include file package:flutter_lints/flutter.yaml in project_name/analysis_options.yaml cannot be found

### ISSUE THREAD

**Issue by akadatsky** [flutter/flutter#86917] opened 2021-07-23 06:47 UTC
I want to add flutter_lints to my app, but suggestions inside IDE does not work and I see IDE error inside analysis_options.yaml:
`The include file package:flutter_lints/flutter.yaml in project_name/analysis_options.yaml cannot be found`

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/akadatsky/bin/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/akadatsky/bin/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/akadatsky/bin/android-sdk
    • ANDROID_SDK_ROOT = /home/akadatsky/bin/android-sdk
    • Java binary at: /home/akadatsky/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/akadatsky/bin/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /home/akadatsky/bin/idea-IC-203.7717.56
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[✓] VS Code (version 1.58.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • SM N970F (mobile) • 192.168.1.46:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

More details:
I added flutter_lints by command `flutter pub add --dev flutter_lints`
My pubspec.yaml has this lines:
```
dev_dependencies:
  flutter_lints: 1.0.4
```
My analysis_options.yaml looks like this:

```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
```

But lint checks do not work in Android Studio. If I manually copy data from flutter.yaml than it become works:
```
include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
```

**Comment by maheshmnj** [comment] 2021-07-23 14:17
Hi @akadatsky ,
Thanks for filing the issue, Please provide the output of `flutter doctor -v`,This helps to better investigate the issue.

Thank you.

**Comment by maheshmnj** [comment] 2021-07-23 14:25
Hi @akadatsky 
Thanks for filing the issue, Please provide the output of `flutter doctor -v`, Could you also share what IDE are you facing this error in?

Could you please try the following

- `flutter clean`
- `flutter pub get`
- try restarting the IDE

Thank you.

**Comment by akadatsky** [comment] 2021-07-23 14:32
Added flutter doctor -v output to first post. I use Android Studio

**Comment by maheshmnj** [comment] 2021-07-26 06:39
Thanks for the info, The flutter_lints wouldn't work if you `analysis_options.yaml` contains 

```
include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
```
Is that what your are trying to do?

**Comment by akadatsky** [comment] 2021-07-26 07:26
For test suggestions, I used this sample:
https://github.com/flutter/packages/blob/master/packages/flutter_lints/example/lib/main.dart

If my `analysis_options.yaml` looks like this, Android Studio does not show suggestions:
```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
```

After several attempts to fix it, I manually copy all lints checks without include tag and it looks like work now:
https://gist.github.com/akadatsky/d6cbdb1fd3253bf24eabd8593eb64530

So the main questions, why include tag does not work in `analysis_options.yaml`?

**Comment by TahaTesser** [comment] 2021-07-26 14:47
Hi @akadatsky 
Thanks for filing the issue,

On the current `stable` channel, the Flutter project doesn't have lints enabled by Default, you can read it [here](https://pub.dev/packages/flutter_lints#usage). Here when we add `analysis_options.yaml` with  from [README](https://pub.dev/packages/flutter_lints#usage) and `flutter pub add --dev flutter_lints` . 

Use following the code sample with missing consts, observer there are  no "prefer const" suggestions regardless of VS Code or Android Studio

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text("Hello World"),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>


While same ``analysis_options.yaml`  in current from `beta` to `master` channels, shows these suggestions
Even tho it is a package, I think it has to be supported by SDK too, which is now at least `2.3`, current stable lower than that 


Can you please upgrade to the latest  `beta` and try again with `analysis_options.yaml` from [README](https://pub.dev/packages/flutter_lints#usage)
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment] 2021-07-26 15:07
Update:
Seeing some behavior when reproducing stable channel issue, when restarted IDEs (VS Code and Android Studio)
Sometimes suggestions are not working in both IDEs and sometimes only 1 IDE shows suggestions, sometimes VS Code and sometimes Android Studio breaks.
<img width="1680" alt="Screenshot 2021-07-26 at 6 05 22 PM" src="https://user-images.githubusercontent.com/48603081/127012470-859cd173-9747-4139-a08f-139ca788bf3b.png">

**Comment by TahaTesser** [comment] 2021-08-17 13:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-08-17 13:45 UTC
Labels: waiting for customer response, in triage

**Comment by mkakabaev** [comment] 2021-08-19 17:13
@akadatsky In my situation the issue was caused by using forked plugin, i.e. there was a nested project / yet another pub spec.yaml file in my VSCode's source tree. I had to add this sub-project to "dart.analysisExcludedFolders" section of my VSCode workspace file (IDE restart required) and the problem has gone.
