### ISSUE TITLE
TextField does not support Persian well!

### ISSUE THREAD

**Issue by mrdimaan** [flutter/flutter#20829] opened 2018-08-20 20:10 UTC
Hi, I am writing an app using flutter in Persian (locale fa) and I think the TextField widget does not support it well. everything about English is fine but when I type Persian the text is not centered and goes near the bottom of input.

In Addition, I couldn't find an option for adjusting the text direction. actually, the text is right aligned but the direction is still ltr.
Thanks a lot.

**Comment by jonahwilliams** [comment] 2018-08-20 20:20
Please add the results of `flutter doctor -v`

**Comment by mrdimaan** [comment] 2018-08-20 20:32
What I said is not a bug that crashes the app! 
What I meant was the Widget UI. It  Can be improved for writing Persian apps. it really does not look right .
Eample:
![photo_2018-08-21_00-59-23](https://user-images.githubusercontent.com/32099630/44364929-858ae480-a4dd-11e8-8707-b9f6f2e7260a.jpg)
as you see the Persian text is not centered well and is near to the bottom of input

**Comment by mrdimaan** [comment] 2018-08-20 20:34
flutter doctor log:
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/moein/Documents/flutter-dev
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/moein/Android/Sdk
    • Android NDK at /home/moein/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.26.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • SM J730F • 5200f825ee301577 • android-arm • Android 7.0 (API 24)
```

**Comment by jonahwilliams** [comment] 2018-08-20 22:16
@mrdimaan The reason we ask for the Flutter version is because there are constantly improvements being made to the text handling of the framework, which you won't see on an older version. Unfortunately we went quite a while without releasing a new beta, but if you could try using dev or the master branch (at least to verify) I believe we've previously landed some improvements. If not, please let me know

**Comment by TeddyRomanos** [comment] 2018-08-21 05:51
i think that this issue is similar to issue #20183.

**Comment by mrdimaan** [comment] 2018-08-21 06:09
@TeddyRomanos No the text is complete but the position is not ok.

**Comment by mrdimaan** [comment] 2018-08-22 15:55
I tried the master branch and the problem is still there.

**Comment by mrdimaan** [comment] 2018-08-26 14:56
any news? if there is a way to correct this please tell me.

**Comment by jonahwilliams** [comment] 2018-08-26 19:42
cc @jason-simmons

**Comment by HansMuller** [comment] 2018-10-24 20:02
@mrdimaan If I understand the issue correctly, what you're [saying here](https://github.com/flutter/flutter/issues/20829#issuecomment-415083448) is that the baseline for Persian text  should be higher. And here [you're saying](https://github.com/flutter/flutter/issues/20829#issuecomment-414453280) that the baseline for Persian text (`ScriptCategory.tall`) should not be aligned with the english text (`ScriptCategory.english-like`), it should be  higher. 

We do use slightly taller fonts for locales like Arabic, however there's no adjustment of the baseline, which is just intrinsic to the font.

Do browsers like Chrome handle this correctly?

**Comment by GaryQian** [comment] 2018-11-03 00:49
It does indeed seem like we are rendering Persian (and I suspect other languages like Arabic) too low. This is what Chrome does compared to english:
![image](https://user-images.githubusercontent.com/1887398/47946328-69d19080-dec7-11e8-8c1a-8ad0541b3fea.png)
I am not currently working on this immediately, but will take a look as soon as I get a chance.

**Comment by mrdimaan** [comment] 2018-11-14 16:07
@HansMuller Hi, sorry for answering too late. Yes I mean the baseline for Persian text should be higher. This is an example of a perfect alignment in a messenger:
![capture](https://user-images.githubusercontent.com/32099630/48495207-bb253c80-e844-11e8-85c5-212202fa4f6c.PNG)

**Comment by GaryQian** [comment] 2018-11-16 00:56
https://github.com/flutter/flutter/issues/24317

**Comment by goderbauer** [comment] 2019-01-03 02:09
Closing this as a dupe of #24317.

**Closed by goderbauer** 2019-01-03 02:09 UTC
Labels: a: text input, framework
