### ISSUE TITLE
Flutter web app shows a white blank screen on older devices iOS devices

### ISSUE THREAD

**Issue by Halwest05** [flutter/flutter#83346] opened 2021-05-25 13:13 UTC
Hi! so i'm trying to make a PWA, it works on modern devices but not semi old devices like these one mentioned above, they just show a white blank screen, i tried hosting the app with firebase hosting and github pages, and i made a completely new flutter project (the default counter app) but the problem still persists, 

Here is my flutter doctor -v

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/halwest05/snap/flutter/common/flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/halwest05/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/103/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/103/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /snap/intellij-idea-community/299
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

Any help is appreciated.

**Comment by vitthal-inani** [comment] 2021-05-25 13:33
You hosted it and it's still not appearing? I dont think that has anything to do with the device.(Maybe I am wrong). can you share the hosted URL?

**Comment by vitthal-inani** [comment] 2021-05-25 14:11
The website itself is running on old emulators. I guess your problem is the code directly run isnt working on emulators? If its just the website not loading I guess you should update Android System WebView and chrome.

**Comment by Halwest05** [comment] 2021-05-25 14:42
> The website itself is running on old emulators. I guess your problem is the code directly run isnt working on emulators? If its just the website not loading I guess you should update Android System WebView and chrome.

Ok so it worked on the galaxy j3! (at least on chrome browser) but not the iPad 4 even on chrome.
By the way these two devices are real devices not emulated (i know they are old, but i still kept them xD).

**Comment by Halwest05** [comment] 2021-05-25 15:14
> Uh the Ipad's webview is not based on chrome like android plus they deprecated UIWebView(The old Webview used by iOS) in 2020 and new Ipad's have it completely different I am guessing you'll need to update safari or find work arounds on Google, my iOS knowledge is a little limited here though. I am happy the Android thing worked.
> Congrats.

No problem, thank you very much for your help and your time :)

**Comment by ConcenTech** [comment] 2021-05-25 19:16
Related to: https://github.com/flutter/flutter/issues/83176?

**Comment by TahaTesser** [comment] 2021-05-26 10:40
Hi @Halwest05 
The only old device I have is an iPhone 5s, I can confirm the Flutter web page doesn't load it in `html` or `canvaskit`


| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/119646460-df0b6500-be27-11eb-8c65-ed50daae81ce.jpeg" height="450" />	|



Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.66

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.164, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.164 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5e646717c8 (4 hours ago), 2021-05-26 02:39:02 -0400
    • Engine revision 221623d2bb
    • Dart version 2.14.0 (build 2.14.0-151.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.985]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 90.0.818.66

• No issues found!
```
		
</details>

✅ : No Issue ❌: has Issue

**Comment by yjbanov** [comment] 2021-05-27 22:11
@sigmundch is there anything in dart2js that we know might be breaking on old browsers?

**Comment by yjbanov** [comment] 2021-05-27 22:18
Actually, this is very likely duplicate of https://github.com/flutter/flutter/issues/83176. Will deduplicate.

**Closed by yjbanov** 2021-05-27 22:18 UTC
Labels: dependency: dart, e: device-specific, engine, found in release: 2.2, found in release: 2.3, has reproducible steps, platform-ios, platform-web

**Comment by bencer3283** [comment] 2021-05-31 13:31
#83646 may be also a duplicate issue, but with a easy work around described.

**Comment by sigmundch** [comment] 2021-06-01 15:58
dart2js still emits ES5, however we will be starting to use some ES6 features, like method declarations, arrow functions, and possibly the `??` operator in the future. 

@yjbanov - just to confirm that our test matrix matches: is this the latest info on supported browsers by flutter web: https://flutter.dev/docs/development/platform-integration/web#which-web-browsers-are-supported-by-flutter ?

/cc @Markzipan @rakudrama

**Comment by phenbyjen** [comment] 2021-06-08 07:03
Is this issue causes by viewport height? [White space at page bottom after device rotation in iOS Safari
](https://stackoverflow.com/questions/62717621/white-space-at-page-bottom-after-device-rotation-in-ios-safari)

**Comment by yellowgraysu** [comment] 2021-06-08 07:04
Is this issue causes by viewport height? [White space at page bottom after device rotation in iOS Safari
](https://stackoverflow.com/questions/62717621/white-space-at-page-bottom-after-device-rotation-in-ios-safari)
