### ISSUE TITLE
Linux tool_integration_tests_4_4 failing assertion

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#92042] opened 2021-10-18 21:28 UTC
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8833005578233648257/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_4_4/test_stdout

```
03:45 +27 ~20 -1: test/integration.shard/overall_experience_test.dart: flutter run writes and clears pidfile appropriately [E]                                                                         
  Expected: <0>
    Actual: <1>
  subprocess failed; exit code 1
```

```
    [ 10.0s] stdout: Oops; flutter has exited unexpectedly: "'package:flutter_tools/src/resident_runner.dart': Failed assertion: line 1373 pos 12: '!includeDevtools || devToolsServerAddress != null': is not true.".
```

**Comment by keyonghan** [comment] 2021-11-03 21:02
This flake still exists and it happened on three rows today:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/2349/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/2355/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/2360/overview

Could we mark the test as `skip: true` if we do not have a quick fix?

**Comment by zanderso** [comment] 2021-11-03 21:35
@Hixie @christopherfujino Could this test `test/integration.shard/overall_experience_test.dart: flutter run writes and clears pidfile appropriately` be run with verbose logging so that we can get some more information from the tool about why DevTools is not starting up correctly. /cc @kenzieschmoll

**Comment by keyonghan** [comment] 2021-11-03 21:53
TOT hit the flake again. Creating https://github.com/flutter/flutter/pull/93026 to mark the test as `skip: true`.

**Comment by Hixie** [comment] 2021-11-07 07:06
We can certainly add more logging but I'm not sure that we log anything useful for this particular failure mode unfortunately.

**Comment by Hixie** [comment] 2021-11-10 00:34
@kenzieschmoll are you able to take a look at this? We have a long history of this test acting flaky, and it seems to be related to devtools launch failures.

**Comment by kenzieschmoll** [comment] 2021-11-12 23:44
```
Oops; flutter has exited unexpectedly: "'package:flutter_tools/src/resident_runner.dart': Failed assertion: line 1380 pos 12: '!includeDevtools || devToolsServerAddress != null': is not true.".
```
This failure looks a little different than the one from https://github.com/flutter/flutter/issues/91270.
```
[flutter_gallery__start_up] [STDOUT] stderr: NoSuchMethodError: The getter 'uri' was called on null.
[flutter_gallery__start_up] [STDOUT] stderr: Receiver: null
[flutter_gallery__start_up] [STDOUT] stderr: Tried calling: uri
[flutter_gallery__start_up] [STDOUT] stderr: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
[flutter_gallery__start_up] [STDOUT] stderr: #1      ResidentRunner.printDebuggerList (package:flutter_tools/src/resident_runner.dart:1382:47)
[flutter_gallery__start_up] [STDOUT] stderr: #2      FlutterResidentDevtoolsHandler.serveAndAnnounceDevTools (package:flutter_tools/src/resident_devtools_handler.dart:96:23)
[flutter_gallery__start_up] [STDOUT] stderr: <asynchronous suspension>
```

In both cases though, it appears that at some point the devtools server is getting shut down shortly after it starts (see my comment from the other issue - https://github.com/flutter/flutter/issues/91270#issuecomment-953306561). I still have not been able to reproduce this locally to debug.

**Comment by Hixie** [comment] 2021-11-16 23:56
@godofredoc Are you able to help @kenzieschmoll reproduce this in CI?

**Comment by godofredoc** [comment] 2021-11-17 00:14
Taking a look!

**Comment by godofredoc** [comment] 2021-11-17 00:31
@kenzieschmoll on your local runs are you running the entire shard or just the failing test?

My assumption is that randomizing the order of execution is actually affecting this test. A few questions:

* Is the test hermetic, e.g. sets up all its dependencies and tears them down at the end?
* @Hixie do you know if the test runner parallelize the test execution? multiple tests running on parallel or asynchronously would explain the behavior of the dev server being killed in the middle of the test execution.

**Comment by Hixie** [comment] 2021-11-17 22:50
Within a file, the tests are not run in parallel.

Separate files can be run in parallel though, yes. That's controlled by `-j` on `flutter test`.

**Comment by godofredoc** [comment] 2021-11-17 23:41
I'll run the shard several times to see if we can replicate and if we do I'll set j=1 and try again.

**Comment by Hixie** [comment] 2021-11-30 23:36
@godofredoc any luck?

**Comment by godofredoc** [comment] 2021-12-15 00:10
@christopherfujino this is the bug that we were talking about in our last triage meeting.

How can we ensure any tests running devtools do not run in parallel?

**Comment by christopherfujino** [comment] 2021-12-15 00:35
> @christopherfujino this is the bug that we were talking about in our last triage meeting.
> 
> How can we ensure any tests running devtools do not run in parallel?

These should already be running single threaded: https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L380

```
Future<void> _runIntegrationToolTests() async {
  final String toolsPath = path.join(flutterRoot, 'packages', 'flutter_tools');
  final List<String> allTests = Directory(path.join(toolsPath, 'test', 'integration.shard'))
      .listSync(recursive: true).whereType<File>()
      .map<String>((FileSystemEntity entry) => path.relative(entry.path, from: toolsPath))
      .where((String testPath) => path.basename(testPath).endsWith('_test.dart')).toList();

  await _pubRunTest(
    toolsPath,
    forceSingleCore: true,
    testPaths: _selectIndexOfTotalSubshard<String>(allTests),
  );
}
```

**Comment by godofredoc** [comment] 2021-12-16 23:09
@christopherfujino can you please provide a command example on how to run specific tests?

**Comment by christopherfujino** [comment] 2021-12-17 00:20
@godofredoc 

So the exact command the shard is running is:

`../../bin/cache/dart-sdk/bin/pub run test --test-randomize-ordering-seed=20211018 -rcompact -j1 --no-color test/integration.shard/single_widget_reload_test.dart test/integration.shard/xcode_backend_test.dart test/integration.shard/ios_content_validation_test.dart test/integration.shard/command_output_test.dart test/integration.shard/cache_test.dart test/integration.shard/expression_evaluation_test.dart test/integration.shard/build_ios_config_only_test.dart test/integration.shard/overall_experience_test.dart test/integration.shard/macos_content_validation_test.dart test/integration.shard/generated_plugin_registrant_test.dart`

I'm not sure if `--test-randomize-ordering-seed` randomizes ALL tests across files, or if it runs files sequentially and then randomizes the tests within each file, but it can't hurt to provide the same random seed. So, to run a single file, the command:

```
../../bin/cache/dart-sdk/bin/dart test --test-randomize-ordering-seed=20211018 -j1 test/integration.shard/overall_experience_test.dart
```

Will run all the tests in that file. To run a particular test, you can provide `-n 'test name pattern'`, like:

```
../../bin/cache/dart-sdk/bin/dart test --test-randomize-ordering-seed=20211018 -j1 test/integration.shard/overall_experience_test.dart -n 'flutter run writes and clears pidfile appropriately'
```

Will run only a single test (after un-skipping this particular test).

**Comment by christopherfujino** [comment] 2022-03-22 23:03
@keyonghan do you know if this is still happening?

**Comment by keyonghan** [comment] 2022-03-22 23:22
With https://github.com/flutter/flutter/pull/93026 skipping the test, we haven't been able to run the flaky tests. Do we know if any fix has been submitted?

**Comment by christopherfujino** [comment] 2022-03-23 16:35
Ahh, I missed that you skipped it.

**Comment by godofredoc** [comment] 2022-03-29 23:09
@christopherfujino @keyonghan what are the next steps for this bug?

**Comment by keyonghan** [comment] 2022-03-30 04:43
I don't think this is still a P1 with the flaky test being skipped. Lowering to P3.
Assigning to myself to see if I can repro the issue locally.

**Comment by keyonghan** [comment] 2022-03-31 16:17
Didn't hit the flake after 100 runs locally. Will try testing from CI to see if any luck.

**Comment by keyonghan** [comment] 2022-04-04 16:43
Didn't hit the flake from CI either:
1) tried enabling the flaky unit test, and ran with latest random seed. No flake hit in 25 runs.
2) tried enabling the flaky unit test, and ran with earlier `'--test-randomize-ordering-seed=20211102'`. No flake in 50 runs. I am wondering is any related changes/fixes already in.

Enabling the test back to prod pool: https://github.com/flutter/flutter/pull/101267 as no flake hit in 50 runs.

Please reopen if hitting again.

**Closed by keyonghan** 2022-04-04 16:43 UTC
Labels: passed first triage, team: infra, passed secondary triage, P3, severe: flake
