### ISSUE TITLE
Lost connection to device - when trying to run in debug mode

### ISSUE THREAD

**Issue by deva666** [flutter/flutter#51457] opened 2020-02-26 08:12 UTC
After updating to MacOs  Catalina, can't run my app in debug mode anymore.
Builds correctly and every time gets stuck at syncing files with `Lost Connection to device`
I tried Flutter stable and beta channel, also tried running from Visual Studio Code and Android Studio.
I also tried running on iOS emulator, Android emulator, and physical Android device.
The same thing every time.

On Windows works without problem, same code.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-HR)
    • Flutter version 1.12.13+hotfix.8 at /Users/deva/Documents/Repos/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/deva/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • GM1913 • 68f90884 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

**Comment by VladyslavBondarenko** [comment] 2020-02-26 08:55
Hi @deva666 
could you provide your `flutter run --verbose`?

**Comment by deva666** [comment] 2020-02-26 10:21
```[   +4 ms] <- compile package:foodster/main.dart
[  +31 ms] D/PhoneWindow(22856): setNavigationBarColor: fffafafa
[ +214 ms] W/DynamiteModule(22856): Local module descriptor class for providerinstaller not found.
[  +23 ms] I/DynamiteModule(22856): Considering local module providerinstaller:0 and remote module providerinstaller:0
[        ] W/ProviderInstaller(22856): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote
version is 0.
[   +2 ms] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api,
linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I
(greylist,core-platform-api, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->copyMemory(JJJ)V (greylist, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getByte(J)B (greylist,core-platform-api, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getByte(Ljava/lang/Object;J)B (greylist,core-platform-api,
linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getLong(J)J (greylist,core-platform-api, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->putByte(JB)V (greylist,core-platform-api, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->putByte(Ljava/lang/Object;JB)V (greylist,core-platform-api,
linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api,
reflection, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api,
reflection, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
[  +15 ms] V/NativeCrypto(22856): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
[   +6 ms] W/devcic.foodste(22856): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String;
(greylist, reflection, allowed)
[  +34 ms] I/ProviderInstaller(22856): Installed default security provider GmsCore_OpenSSL
[ +607 ms] W/devcic.foodste(22856): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
(greylist,core-platform-api, linking, allowed)
[   +1 ms] W/devcic.foodste(22856): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
(greylist,core-platform-api, linking, allowed)
[   +1 ms] W/devcic.foodste(22856): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
[  +51 ms] W/devcic.foodste(22856): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V
(greylist, reflection, allowed)
[  +16 ms] W/devcic.foodste(22856): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy;
(greylist,core-platform-api, linking, allowed)
[        ] W/devcic.foodste(22856): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
[+4890 ms] Updating files
[ +693 ms] Service protocol connection closed.
[        ] Lost connection to device.
[+1008 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: Write failed (OS Error: Broken pipe,
errno = 32), address = 127.0.0.1, port = 51921
[        ] trying again in a few - 9 more attempts left
[ +504 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51926
[        ] trying again in a few - 8 more attempts left
[ +504 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51929
[        ] trying again in a few - 7 more attempts left
[ +505 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51930
[        ] trying again in a few - 6 more attempts left
[ +507 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51931
[        ] trying again in a few - 5 more attempts left
[ +504 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51932
[        ] trying again in a few - 4 more attempts left
[ +503 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51933
[        ] trying again in a few - 3 more attempts left
[ +503 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51934
[        ] trying again in a few - 2 more attempts left
[ +502 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51935
[        ] trying again in a few - 1 more attempts left
[ +504 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51936
[        ] trying again in a few - 0 more attempts left
[ +506 ms] Error writing "build/flutter_assets/assets/foodster_fts.sqlite" to DevFS: SocketException: OS Error: Connection refused, errno =
61, address = 127.0.0.1, port = 51939
[        ] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1,
port = 51939
[   +1 ms] Syncing files to device GM1913... (completed in 12,671ms, longer than expected)
[   +1 ms] "flutter run" took 25,548ms.
```
then 
```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#67     _rootRun (dart:async/zone.dart:1126:13)
#68     _CustomZone.run (dart:async/zone.dart:1023:19)
#69     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#70     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by jmagman** [comment] 2020-02-27 02:06
It crashes before the app can run?  Or is your app crashing on launch?
Would you mind testing on the [dev channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#dev)?

**Comment by deva666** [comment] 2020-02-27 05:48
I tried also the dev channel. Same thing.
The app doesn't crash, it just gets stuck at the loading screen (splash screen).
This is only when trying to attach a debugger. When running without debugger everything is fine.
But if I remove the sqlite file I am using from the assets it runs fine, debugger gets attached.

**Comment by exaby73** [comment] 2022-07-14 13:38
Hello @deva666. I cannot reproduce this issue currently. Can you confirm if this issue is fixed now?

**Comment by exaby73** [comment] 2022-07-15 03:45
Thank you for the confirmation. I'm closing the issue as fixed.

**Closed by exaby73** 2022-07-15 03:45 UTC
Labels: tool, platform-mac
