### ISSUE TITLE
Soft keyboard takes a while to open when text field has focus 

### ISSUE THREAD

**Issue by nivla360** [flutter/flutter#51124] opened 2020-02-20 14:33 UTC
## Steps to Reproduce

Any text field in my app has this problem

**Expected results:**  When text field is tapped or has focus its supposed to show the soft keyboard instantly but it does not 

**Actual results:** Some times it opens on first or second try then from there the problem starts. When this happens soft keyboard does not open and the IDE keeps logging this
`W/IInputConnectionWrapper(18599): getExtractedText on inactive InputConnection` for a while (about a minute, more or less) then it opens the softkey board. Sometimes it doesn't and when it does closing it also becomes a problem, when the back button is pressed it also takes some time to close, just like the amount of time it takes to open. This happens in all text fields I have in my app. Everything was working fine until I updated my Flutter.  
When soft keyboard opens and I press back to close it, it doesn't close but logs this `D/ViewRootImpl@980f170[MainActivity](27882): The input has been finished in ImeInputStage.`

**Logs when problem occurs:**
<summary>
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27882): getExtractedText on inactive InputConnection
</summary>
--

**Flutter Doctor Verbose:**
[√] Flutter (Channel master, v1.15.4-pre.95, on Microsoft Windows [Version 10.0.17758.1], locale en-US)
    • Flutter version 1.15.4-pre.95 at C:\src\flutter
    • Framework revision fcf7fda99c (2 days ago), 2020-02-19 04:41:27 +0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\nivla\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\nivla\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\nivla\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM G950U   • 192.168.8.100:5555 • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome             • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server         • web-javascript • Flutter Tools

• No issues found!

**Comment by VladyslavBondarenko** [comment] 2020-02-20 14:58
Hi @nivla360 
I can't reproduce it neither with master v1.15.4-pre.95 nor with the latest master 1.15.4-pre.117
Do you experience this with the latest version?

**Comment by nivla360** [comment] 2020-02-20 15:20
I don't remember the exact version it started occurring on, but I believe from version 1.15 upwards. Or may be it happens on Samsung devices. I'm using Samsung Galaxy S8 SM G950U. One other thing I noticed is when the keyboard finally opens it logs this:
 
D/ViewRootImpl@914d196[MainActivity]( 4072): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 1003) vi=Rect(0, 0 - 0, 1003) or=1
D/ViewRootImpl@914d196[MainActivity]( 4072): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 500202876928} changed=false
D/ViewRootImpl@914d196[MainActivity]( 4072): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 1003) vi=Rect(0, 63 - 0, 1003) or=1
D/ViewRootImpl@914d196[MainActivity]( 4072): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 500202876928} changed=false

**Comment by nivla360** [comment] 2020-02-20 15:31
@VladyslavBondarenko also when reproducing the problem, use text fields within forms or multiple text fields within a list instead

**Comment by VladyslavBondarenko** [comment] 2020-02-20 15:44
@nivla360 
Checked 
<details>
 <summary>this code</summary>

 ```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
      child: SafeArea(
        child: Scaffold(
          body: Column(
            children: <Widget>[
              Form(
                child: Column(
                  children: <Widget>[
                    TextField(),
                    TextField(),
                  ],
                ),
              ),
              Form(
                child: Column(
                  children: <Widget>[
                    TextField(),
                    TextField(),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

also with a real device (Redmi with Android 9), it's working as intended

**Comment by nivla360** [comment] 2020-02-20 16:07
Ok, I'll try the above code in a new project and give you feedback

**Comment by nivla360** [comment] 2020-02-21 08:17
@VladyslavBondarenko  I tried the code above and these are the results. I divided the video into two parts because after a while the keyboard just didn't open again thus the part 2 of the video

[Textfield bug.zip](https://github.com/flutter/flutter/files/4234953/Textfield.bug.zip)

**Comment by nivla360** [comment] 2020-03-03 15:56
I noticed another  thing, I downgraded to  v1.14.6 and realized this bug doesn't exist

**Comment by darshankawar** [comment] 2020-08-25 11:38
Hi @nivla360,
Can you please confirm if you still experience this issue using same device you mentioned earlier, on latest Stable or Master version ?
Thanks

**Comment by nivla360** [comment] 2020-08-25 14:47
> Hi @nivla360,
> Can you please confirm if you still experience this issue using same device you mentioned earlier, on latest Stable or Master version ?
> Thanks

I dont know about the master channel but I'm on beta channel right now and I don't have that issue.

**Comment by darshankawar** [comment] 2020-08-26 06:01
@nivla360,
Glad to know that you are not seeing the issue anymore. 
Given your last message, I am going ahead and closing this as fixed.
If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-08-26 06:01 UTC
Labels: a: text input, e: device-specific, framework, platform-android
