### ISSUE TITLE
Wrong app bar icon when having a drawer and opening a bottom sheet

### ISSUE THREAD

**Issue by jordyvandomselaar** [flutter/flutter#65263] opened 2020-09-04 20:05 UTC
When you don't have a drawer and you open a bottom sheet, you get a back button in the appbar as you'd expect;

![right_icon](https://user-images.githubusercontent.com/12712484/92280754-69a6df80-eefa-11ea-97fd-f41a50ff7132.gif)

When you do have a drawer, you get a persistent hamburger icon, trapping you in the bottom sheet:

![Kapture 2020-09-04 at 22 05 01](https://user-images.githubusercontent.com/12712484/92280886-bbe80080-eefa-11ea-995c-8dcc6d3b0a47.gif)

Is this intended default behaviour? It's fairly easy to solve in userland but I'm wondering if it shouldn't be default =)

**Comment by Pr47h4m** [comment] 2020-09-05 03:29
Can you attach Your code?

**Comment by Pr47h4m** [comment] 2020-09-05 03:30
This app bar icon usually comes when you use named routes 
Navigator.pushNamed(context,”/compose”);

**Comment by jordyvandomselaar** [comment] 2020-09-06 00:14
Sure thing! Here's my code:

```
import 'dart:ui';

import 'package:flutter/material.dart';

class MailList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Inbox"),
      ),
      body: ListView(
        children: [
        ],
      ),
      floatingActionButton: ComposeButton(),
      drawer: MainDrawer(),
    );
  }
}

class ComposeButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FloatingActionButton.extended(
      label: Text("Compose"),
      icon: Icon(Icons.edit),
      onPressed: () {
        Scaffold.of(context).showBottomSheet((context) {
          return ComposeMailBottomSheet();
        });
      },
    );
  }
}

class MailListItem extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListTile(
      isThreeLine: true,
      leading: CircleAvatar(
        child: Text("J"),
      ),
      title: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [Text("CodePen"), Text("19:53")],
      ),
      subtitle: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            "The CodePen Spark",
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          Text("This is a special edition"),
        ],
      ),
    );
  }
}

class ComposeMailBottomSheet extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: MediaQuery.of(context).size.height,
      child: Form(
        child: ListView(
          children: [
            TextFormField(
              decoration: InputDecoration(labelText: "To"),
            ),
            TextFormField(
              decoration: InputDecoration(labelText: "Subject"),
            ),
            TextFormField(
              decoration: InputDecoration(hintText: "Compose email", border: InputBorder.none),
              maxLines: null,
              minLines: 5,
              keyboardType: TextInputType.multiline,
            )
          ],
        ),
      ),
    );
  }
}

class MainDrawer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: ListView(
        children: [
          Text("MailApp", style: TextStyle(fontSize: 24),)
        ],
      ),
    );
  }
}
```

**Comment by Pr47h4m** [comment] 2020-09-06 05:58
Hello! @jordyvandomselaar 
I've checked your code what you are doing is opening StatelessWidget instead of returning modalBottomSheet
please checkout code snippet attached with some screenshots and if you need same like gmail app in android then tell me 

`import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: MailList(),
      debugShowCheckedModeBanner: false,
    ));

class MailList extends StatelessWidget {
  
  Future<void> _composeMail(BuildContext context) {
    return showModalBottomSheet(
      context: context,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(10.0),
        ),
      ),
      isScrollControlled: true,
      builder: (_) {
        return Padding(
          padding: EdgeInsets.fromLTRB(10 , 10, 10 , MediaQuery.of(context).viewInsets.bottom + 20),
          child: Wrap(
            children: [
              TextField(
                decoration:  InputDecoration(
                  labelText: "To:",
                ),
              ),
              TextField(
                decoration:  InputDecoration(
                  labelText: "Subject:",
                ),
              ),
              TextField(
                decoration:  InputDecoration(
                  labelText: "Message:",
                ),
              ),
              RaisedButton(
                child: Text("Send"),
                onPressed: () {},
              ),
            ],
          ),
        );
      },
    );
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Inbox"),
      ),
      body: ListView(
        children: [],
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: Text("Compose"),
        icon: Icon(Icons.edit),
        onPressed: () {
          _composeMail(context);
        },
      ),
      drawer: MainDrawer(),
    );
  }
}

class MainDrawer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: ListView(
        children: [
          Text("MailApp", style: TextStyle(fontSize: 24),)
        ],
      ),
    );
  }
}
`





![image](https://user-images.githubusercontent.com/56750378/92319165-6bc08980-f033-11ea-8a77-e795d4605778.png)
![image](https://user-images.githubusercontent.com/56750378/92319170-7da22c80-f033-11ea-9548-c51ae1faccb9.png)

**Comment by markusaksli-nc** [comment] 2020-09-07 07:59
Closing this since this is the expected behavior when pushing a drawer.

**Closed by markusaksli-nc** 2020-09-07 07:59 UTC
