### ISSUE TITLE
[Web] FlexibleSpaceBar stretch mode blurBackground behaves incorrectly on Web

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#46830] opened 2019-12-12 01:16 UTC
Discrepancy found in newly enabled screenshot tests for web in PR #46820

Web:
![z_flexible_space_bar_stretch_mode blur_background](https://user-images.githubusercontent.com/1267593/70673162-74b43400-1c36-11ea-8552-6fe2c6ef6ed7.png)

Flutter tester:
![z_flexible_space_bar_stretch_mode blur_background png o](https://user-images.githubusercontent.com/1267593/70673163-74b43400-1c36-11ea-8d46-2b968d8b9b84.png)

Test: test/material/flexible_space_bar_stretch_mode_test.dart

**Comment by ferhatb** [comment] 2020-01-08 00:42
Duplicate of https://github.com/flutter/flutter/issues/46827

**Closed by ferhatb** 2020-01-08 00:42 UTC
Labels: ☸ platform-web
