### ISSUE TITLE
InAppPurchase 0.3.4+10 crashes on iOS

### ISSUE THREAD

**Issue by andreacimino** [flutter/flutter#67202] opened 2020-10-03 07:02 UTC
Tested on Flutter 1.22 stable, iOS 14.
Version  0.3.4+3 is working fine.

When calling InAppPurchaseConnection.instance.buyNonConsumable

Now I get the following crash.

Fatal Exception: NSInvalidArgumentException
-[NSNull boolValue]: unrecognized selector sent to instance 0x1e8e2ca00
-[InAppPurchasePlugin addPayment:result:]

in_app_purchase
InAppPurchasePlugin.m - Riga 183
-[InAppPurchasePlugin addPayment:result:] + 183

in_app_purchase
InAppPurchasePlugin.m - Riga 103
-[InAppPurchasePlugin handleMethodCall:result:] + 103

**Comment by SpajicM** [comment] 2020-10-05 09:09
Duplicate https://github.com/flutter/flutter/issues/67139

**Comment by darshankawar** [comment] 2020-10-05 09:22
Closing this as duplicate of [65767](https://github.com/flutter/flutter/issues/65767)

**Closed by darshankawar** 2020-10-05 09:22 UTC
