### ISSUE TITLE
Providing a object deep copy method

### ISSUE THREAD

**Issue by byemylove203** [flutter/flutter#121073] opened 2023-02-20 04:42 UTC
## Use case
     - There are a lot of way to deep clone an object like json.decode(json.encode(objA)), ... but there's still no official way from flutter's team so i want a method that perform deep clone object

**Comment by stuartmorgan** [comment] 2023-02-20 12:42
Duplicate of https://github.com/dart-lang/sdk/issues/6459

**Closed by stuartmorgan** 2023-02-20 12:42 UTC
