### ISSUE TITLE
The colors of the PopupMenuItems and Cards are wrong after Flutter upgrade

### ISSUE THREAD

**Issue by iUnknownWs** [flutter/flutter#117833] opened 2022-12-30 23:07 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Execute `flutter upgrade` 
3. Tap on the profile picture or `PopupMenuButton`

**Expected results:** 

The colors of `PopupMenuItems` and the `Cards` should match with the PopupMenu background and the Card color

**Actual results:** 

![Screenshot_1672437061](https://user-images.githubusercontent.com/109998892/210116540-30c5661f-c25b-4481-aa19-f48cb23ea10a.png)

<details>
<summary>App bar with PopupMenu</summary>

```
Scaffold(
      backgroundColor: Theme.of(context).colorScheme.background,
      appBar: AppBar(
        automaticallyImplyLeading: false,
        elevation: 4,
        surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
        backgroundColor: Theme.of(context).colorScheme.surface,
        title: const Text('Asistente'),
        centerTitle: true,
        actions: [
          PopupMenuButton( 
              position: PopupMenuPosition.under,
              // color: ElevationOverlay.applySurfaceTint(
              //     Theme.of(context).colorScheme.surface,
              //     Theme.of(context).colorScheme.surfaceTint,
              //     2),
              elevation: 2,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4)),
              constraints: const BoxConstraints(
                minWidth: 112,
                maxWidth: 280,
              ),
              iconSize: 30,
              icon: CircleAvatar(
                backgroundImage: NetworkImage(user.photoURL!),
              ),
              // icon: const Icon(Icons.account_circle_outlined),
              itemBuilder: (BuildContext context) => [
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        leading: const Icon(Icons.settings),
                        onTap: (() {
                          Navigator.pop(context);
                          openDialog(context);
                        }),
                        title: Text(
                          'Configuración',
                          style: Theme.of(context)
                              .textTheme
                              .labelLarge
                              ?.copyWith(
                                  color:
                                      Theme.of(context).colorScheme.onSurface),
                        ),
                      ),
                    ),
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        leading: const Icon(Icons.account_circle),
                        onTap: (() {
                          Navigator.pop(context);
                          infoDialog(context);
                        }),
                        title: Text(
                          'Información',
                          style: Theme.of(context)
                              .textTheme
                              .labelLarge
                              ?.copyWith(
                                  color:
                                      Theme.of(context).colorScheme.onSurface),
                        ),
                      ),
                    ),
                    PopupMenuItem(
                      child: ListTile(
                        iconColor:
                            Theme.of(context).colorScheme.onSurfaceVariant,
                        leading: const Icon(Icons.logout_outlined),
                        onTap: (() {
                          final provider = Provider.of<GoogleSignInProvider>(
                              context,
                              listen: false);
                          provider.logout();
                          Navigator.pop(context);
                        }),
                        title: Text(
                          'Cerrar Sesión',
                          style: Theme.of(context)
                              .textTheme
                              .labelLarge
                              ?.copyWith(
                                  color:
                                      Theme.of(context).colorScheme.onSurface),
                        ),
                      ),
                    ),
                  ])
        ],
      ),
```

```
Card(
      clipBehavior: Clip.antiAlias,
      child: SizedBox(
        width: 300,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Image(
              image: NetworkImage(widget.products.imageUrl),
              fit: BoxFit.cover,
            ),
            ListTile(
              title: Text(widget.products.name),
              subtitle: Text('Precio: ${widget.products.price}\$'),
              visualDensity: VisualDensity.compact,
            ),
            Container(
              margin: const EdgeInsets.fromLTRB(16, 0, 0, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Cantidad: '),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(12, 0, 0, 0),
                    child: QuantityMenu(
                      quantityFuction: quantityFunction,
                    ),
                  ),
                ],
              ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(0, 0, 8, 8),
                  child: ElevatedButton(
                    style: ButtonStyle(
                      foregroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFFFFFFFF),
                      ),
                      backgroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFF6750A4),
                      ),
                    ),
                    onPressed: () => showDialog(
                      context: context,
                      barrierDismissible: false,
                      builder: (BuildContext context) => AlertDialog(
                        title: SizedBox(
                          width: 240,
                          height: 260,
                          child: QrImage(
                            data: data,
                            backgroundColor: Colors.white,
                          ),
                        ),
                        content: Text('ID del producto: $data'),
                        actions: <Widget>[
                          TextButton(
                              onPressed: () {
                                Navigator.pop(context);
                              },
                              child: const Text('Cerrar')),
                        ],
                      ),
                    ),
                    child: const Text(
                      'Mostrar QR',
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.fromLTRB(0, 0, 8, 8),
                  child: ElevatedButton(
                    style: ButtonStyle(
                      foregroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFFFFFFFF),
                      ),
                      backgroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFF6750A4),
                      ),
                    ),
                    onPressed: () => showDialog(
                      context: context,
                      barrierDismissible: false,
                      builder: (BuildContext context) => AlertDialog(
                        title: Text(
                          '¿Desea eliminar el producto ${widget.products.name} de la base de datos?',
                          textAlign: TextAlign.center,
                        ),
                        actions: <Widget>[
                          TextButton(
                              onPressed: () {
                                Navigator.pop(context);
                              },
                              child: const Text('Cancelar')),
                          TextButton(
                              onPressed: () {
                                final docProducts = FirebaseFirestore.instance
                                    .collection('products')
                                    .doc(widget.products.id);

                                docProducts.delete();
                                Navigator.pop(context);
                              },
                              child: const Text('Eliminar')),
                        ],
                      ),
                    ),
                    child: const Text(
                      'Eliminar',
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.fromLTRB(0, 0, 8, 8),
                  child: ElevatedButton(
                    style: ButtonStyle(
                      foregroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFFFFFFFF),
                      ),
                      backgroundColor: MaterialStateProperty.all<Color>(
                        const Color(0xFF6750A4),
                      ),
                    ),
                    onPressed: () => showDialog(
                      context: context,
                      barrierDismissible: false,
                      builder: (BuildContext context) => AlertDialog(
                        content: Text(
                          '¿Desea añadir $quantity ${widget.products.name}(s) a la lista de compras? \n \n'
                          'Atencion!: Si este producto ya se encuentra en el carrito añadirlo de nuevo reemplazará el anterior',
                          textAlign: TextAlign.center,
                        ),
                        actions: <Widget>[
                          TextButton(
                              onPressed: () {
                                Navigator.pop(context);
                              },
                              child: const Text('Cancelar')),
                          TextButton(
                              onPressed: () {
                                double total = widget.products.price *
                                    double.parse(quantity);
                                addToList(
                                        id: widget.products.id,
                                        total: total,
                                        name: widget.products.name,
                                        price: widget.products.price,
                                        imgUrl: widget.products.imageUrl,
                                        quantity: quantity)
                                    .then((value) => Navigator.pop(context));
                              },
                              child: const Text('Añadir')),
                        ],
                      ),
                    ),
                    child: const Text(
                      'Añadir al Carro',
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing tesis...
No issues found! (ran in 3.8s)
```

```
[√] Flutter (Channel master, 3.7.0-13.0.pre.68, on Microsoft Windows [Versi¢n 10.0.22623.1020], locale es-VE)
    • Flutter version 3.7.0-13.0.pre.68 on channel master at C:\Users\Will\Documents\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 239f80ed6c (5 days ago), 2022-12-25 14:48:16 -0500
    • Engine revision 3ae55014ff
    • Dart version 3.0.0 (build 3.0.0-63.0.dev)
    • DevTools version 2.20.0

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Will\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\Will\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.22623.1020]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2023-01-02 07:37
Thanks for the report @iUnknownWs 
Can you narrow down the code sample so that it is without any custom or third party plugin code and is just minimal but complete which we can directly use (ex: main.dart) that shows the behavior you are reporting ?
Also, please elaborate on the expected behavior you are looking for after running the code that you mentioned before upgrading was different as compared to after upgrade.

**Comment by iUnknownWs** [comment] 2023-01-02 07:57
The problem was a compatibility issue with the ListTiles inside the cards and popupmenu. I solved the problem removing the ListTiles.

**Comment by TahaTesser** [comment] 2023-01-02 11:03
duplicate of https://github.com/flutter/flutter/issues/117700

**Closed by TahaTesser** 2023-01-02 11:03 UTC
Labels: in triage

**Comment by rydmike** [comment] 2023-01-03 21:19
@iUnknownWs another simple workaround is to set the `tileColor` to `Colors.transparent`, either in the `ListTileTheme` or widget level. This works nicely if the surface that the `ListTile` has elevation tint color. Which e.g. Popup or Card will get in Material 3.

For some reason M3 `ListTile` theme defaults to `surface` color **without any elevation tint**, this will make it NOT fit on any elevated surface in M3. Past default `tileColor` in M2 for `ListTile` was `Colors.transparent`, which makes it work nicely on any background. I recommend using it also in M3. Hopefully it is an oversight in the M3 spec to require it to be `ColorScheme.surface` color instead of more universally usable `Colors.transparent`.

At the moment the M3 spec does call for surface color (https://m3.material.io/components/lists/specs), it is however a poor choice imo, but it is correct according to the WEB M3 spec. Hopefully the spec can be amended, since it is a poor design choice for the `ListTile` widget and its wide usage on different background colors.

Still, even if not amended, setting `tileColor` to `Colors.transparent` in the `ListTileTheme` is a simple fix.

cc. @TahaTesser @guidezpl

**Comment by iUnknownWs** [comment] 2023-01-03 21:26
> @iUnknownWs another simple workaround is to set the `tileColor` to `Colors.transparent`, either in the `ListTileTheme` or widget level. This works nicely if the surface that the `ListTile` has elevation tint color. Which e.g. Popup or Card will get in Material 3.
> 
> For some reason M3 `ListTile` theme defaults to `surface` color **without any elevation tint**, this will make it NOT fit on any elevated surface in M3. Past default `tileColor` in M2 for `ListTile` was `Colors.transparent`, which makes it work nicely on any background. I recommend using it also in M3. Hopefully it is an oversight in the M3 spec to require it to be `ColorScheme.surface` color instead of more universally usable `Colors.transparent`.
> 
> At the moment the M3 spec does call for surface color (https://m3.material.io/components/lists/specs), it is however a poor choice imo, but it is correct according to the WEB M3 spec. Hopefully the spec can be amended, since it is a poor design choice for the `ListTile` widget and its wide usage on different background colors.
> 
> Still, even if not amended, setting `tileColor` to `Colors.transparent` in the `ListTileTheme` is a simple fix.
> 
> cc. @TahaTesser @guidezpl 

That doesn't work to me

**Comment by rydmike** [comment] 2023-01-04 00:24
@iUnknownWs interesting. Can you explain what part exactly is not working?

Based on your used master Flutter version and limited code sample it should work. However, since your code sample is not actually a buildable sample, it is a bit challenging to demonstrate it with it. Another options is that I might have misunderstood what you are trying to accomplish. 

If you have buildable sample that demonstrates the issue you are having with using ListTile, I might be able to assist further. Of course, if you don't need and don't use the ListTiles at all anymore, that is certainly another option, like you already mentioned that you did. There are a few ways you can make the `ListTile` match the background on Popups and `Cards`. The one I mentioned is one way that has worked well for me in multiple popups and cards.
