### ISSUE TITLE
Android NDK and SDK error messages propose invalid Gradle syntax

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#109025] opened 2022-08-05 08:17 UTC
The error message for NDK/SDK versions proposes invalid gradle syntax:

```
One or more plugins require a higher Android NDK version.
Fix this issue by adding the following to /usr/local/google/home/dacoharkes/src/dart-lang/jni_gen/jni/example/android/app/build.gradle:
android {
  ndkVersion 22.1.7171670
  ...
}
```

It should be the following:

```
One or more plugins require a higher Android NDK version.
Fix this issue by adding the following to /usr/local/google/home/dacoharkes/src/dart-lang/jni_gen/jni/example/android/app/build.gradle:
android {
  ndkVersion "22.1.7171670"
  ...
}
```

Without the quotes Gradle fails to parse the file.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/google/home/dacoharkes/src/dart-lang/jni_gen/jni/example/android/app/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_16b3mv73oxqhtmgmlwjefvscm.android() is applicable for argument types: (build_16b3mv73oxqhtmgmlwjefvscm$_run_closure2) values: [build_16b3mv73oxqhtmgmlwjefvscm$_run_closure2@54de9eed]
```

**Comment by danagbemava-nc** [comment] 2022-08-05 09:43
Reproducible on stable and master

<details>
<summary>build.gradle</summary>

```groovy
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33
    // ndkVersion 22.1.7171670
    ndkVersion "22.1.7171670"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.t"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2104, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2104 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2ed0e5ae1 (4 hours ago), 2022-08-05 00:29:07 -0400
    • Engine revision 25bad51f09
    • Dart version 2.19.0 (build 2.19.0-66.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.6 19G71
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[build_ndk_no_quotes.txt](https://github.com/flutter/flutter/files/9267488/build_ndk_no_quotes.txt)
[build_ndk_with_quotes.txt](https://github.com/flutter/flutter/files/9267489/build_ndk_with_quotes.txt)

**Comment by danagbemava-nc** [comment] 2022-08-08 06:17
Closing this since the linked PR has been merged.

**Closed by danagbemava-nc** 2022-08-08 06:17 UTC
Labels: tool, t: gradle, has reproducible steps, found in release: 3.0, found in release: 3.1
