### ISSUE TITLE
Impossible to launch app on iPhone device (SE)

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#38677] opened 2019-08-16 08:53 UTC
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1031/Mi-L9wdg3L0=/ws

**Comment by jmagman** [comment] 2019-08-16 20:17
Are you debugging wirelessly?  Do you have "Connect via network" checked in Xcode?  Are you using a proxy?
Can you give us the output of `flutter doctor -v`

**Comment by alex9153** [comment] 2019-08-17 10:50
flutter doctor - all ok. 
Connect via network - disabled.
Proxy - not sure. How to check? I have many strange processes called iproxy (see screenshot)
<img width="908" alt="Снимок экрана 2019-08-17 в 13 49 29" src="https://user-images.githubusercontent.com/353832/63210348-f9160080-c0f5-11e9-83b2-7c0137ca675f.png">

**Comment by alex9153** [comment] 2019-08-18 05:47
Here is flutter doctor -v info

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale ru-RU)
    • Flutter version 1.7.8+hotfix.4 at /Users/aleks/Documents/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aleks/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/aleks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (4 available)
    • ZB602KL                               • J6AXB7654974VZ8                          • android-arm64 • Android 8.1.0 (API 27)
    • iPhone                                • 6b3c1596d17dad9b8728abe8f280c6362c483281 • ios           • iOS 12.3.1
    • iPhone Xs Max                         • 409DF9D7-4997-487D-99BF-108499796EF2     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPad Pro (12.9-inch) (3rd generation) • C0EE6ACC-269A-401A-B398-669289497DF4     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by alex9153** [comment] 2019-08-18 05:58
and offten hapens this: Could not update files on device: OS Error: Connection reset by peer, errno = 54

Only reboot my mac helps

**Comment by thavlik** [comment] 2019-08-20 19:19
I am experiencing this nonstop, and I feel like this exact problem has been going on for quite a while now. It has gone from the occasional relaunch to being completely unable to launch Flutter on iOS at all.

**Comment by jmagman** [comment] 2019-08-29 01:47
@DanTup

**Comment by DanTup** [comment] 2019-08-29 08:58
@thavlik your issue looks different to the OP here - it looks like a crash, whereas the original comment is "Error connecting to the service protocol".

@alex9153 if you disable WiFi on the phone and try again, does the issue disappear? Does it happen from the terminal if you run `flutter run -v`?

**Comment by alex9153** [comment] 2019-08-30 16:08
> @alex9153 if you disable WiFi on the phone and try again, does the issue disappear? Does it happen from the terminal if you run `flutter run -v`?

If disable WiFi error happens - Exited (sigterm) - without any information.
I not use terminal for launching. I use VS Code.

**Comment by DanTup** [comment] 2019-09-02 13:42
@alex9153 can you try using **Dart: Capture Logs** in VS Code to capture a log when this happens:

https://dartcode.org/docs/logging/#capture-logs-command

Tick only the **Flutter Run** and **Observatory/Debugger** options and reproduce the issue, then click **Stop Logging** and paste the log into a Gist and the link here.

Thanks!

**Comment by thavlik** [comment] 2019-09-06 19:16
> @thavlik your issue looks different to the OP here - it looks like a crash, whereas the original comment is "Error connecting to the service protocol".

Still happens with wifi disabled, `flutter run` from terminal also produces this. Honestly all of these errors are raised in a way that is rather inconsistent.

Just earlier I got the same error as the OP (hence why I'm revisiting this issue). The next time I try to launch from VS Code, I get this:
```
Launching lib/main.dart on Thomas’s iPad (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project
Xcode build done.                                           22.9s
Exited (sigterm)
```
And the iPad is hanging on a white screen. The next launch I get this:
```
Launching lib/main.dart on Thomas’s iPad (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
Xcode build done.                                            3.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    ld: file too small (length=0) file '/Users/thomashavlik/Library/Developer/Xcode/DerivedData/Runner-dglkkexbiwafetggkwoqpcfdxnpc/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/SwiftProtobuf.build/Objects-normal/arm64/BinaryDecoder.o' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the precompiled application for the device.

Error launching application on Thomas’s iPad (2).
Exited (sigterm)
```
...the next attempt:
```
Launching lib/main.dart on Thomas’s iPad (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project
Xcode build done.                                           23.5s
Could not update files on device: OS Error: Connection reset by peer, errno = 54
Exited (sigterm)
```
...and the next:
```
Launching lib/main.dart on Thomas’s iPad (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project
Xcode build done.                                            3.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-09-06 14:13:08.691 xcodebuild[38231:3403453]  DTDeviceKit: deviceType from 099865ef0579cf0ec05319f979f582fde1565b86 was NULL
    2019-09-06 14:13:08.728 xcodebuild[38231:3403453]  DTDeviceKit: deviceType from 099865ef0579cf0ec05319f979f582fde1565b86 was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    ld: file too small (length=0) file '/Users/thomashavlik/Library/Developer/Xcode/DerivedData/Runner-dglkkexbiwafetggkwoqpcfdxnpc/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/SwiftProtobuf.build/Objects-normal/arm64/Google_Protobuf_Timestamp+Extensions.o' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the precompiled application for the device.

Error launching application on Thomas’s iPad (2).
Exited (sigterm)
```
The subsequent attempt to launch the app via VS Code succeeded.

👎

**Comment by DanTup** [comment] 2019-09-09 09:08
@thavlik many of your issues look like connectivity issues between your machine and device (Connection reset by peer, deviceType from 099865ef0579cf0ec05319f979f582fde1565b86 was NULL, HttpException). The other issue (error "ld: file too small (length=0)") might be the result of a previously aborted build.

Do you have another cable and/or USB port you can try?

Also - I had a quick search and also found people reporting issue with iPads frequently connecting/disconnecting when they were at low power because they couldn't draw enough over the USB cable ([here](https://discussions.apple.com/thread/5453216) is one example) - if your iPad is below half charge, can you see if charging it makes any difference?

**Comment by thavlik** [comment] 2019-09-09 17:29
> @thavlik many of your issues look like connectivity issues between your machine and device (Connection reset by peer, deviceType from 099865ef0579cf0ec05319f979f582fde1565b86 was NULL, HttpException). The other issue (error "ld: file too small (length=0)") might be the result of a previously aborted build.
> 
> Do you have another cable and/or USB port you can try?
> 
> Also - I had a quick search and also found people reporting issue with iPads frequently connecting/disconnecting when they were at low power because they couldn't draw enough over the USB cable ([here](https://discussions.apple.com/thread/5453216) is one example) - if your iPad is below half charge, can you see if charging it makes any difference?

After changing out the official Apple lightning cable with a 3rd party cable, it *sometimes* works after changing ports on the mac mini. Two different models (2012 and 2018 w/ a USB-C adapter) both exhibit this flakiness with two different models of iPad (Pro 2018 and Air 2). The fact that it now works at all, albeit less than half the time, is an improvement.

**Comment by DanTup** [comment] 2019-09-09 17:38
Interesting - did you also try ensuring the iPad is fully charged? There were a *lot* of complaints online about people having intermittent connectivity when it was trying to draw power at the same time.

**Comment by thavlik** [comment] 2019-09-09 18:56
Both are always fully charged. It might be the USB-C adapter. Will keep you posted about this, and I appreciate the help.

**Comment by DanTup** [comment] 2019-09-10 10:06
I'm not familiar with the ports on these devices - what's the USB-C adapter for? Aren't the Mac Mini and the iPhone both Lightning?

I'm running out of ideas of things to try though ☹️  Did you try different ports? The link above has this: "it was connected to the USB port that was closest to the SD Card slot... I moved it another USB slot away from the SD card and voila - worked perfectly, instantly". I don't know that it's the same issue, but it's worth a shot!

**Comment by thavlik** [comment] 2019-09-10 18:32
The 2018 Mac Mini has four TB3 ports in lieu of USB-A. I think you are on the right track by suspecting a connectivity problem. There are times where it works without a hitch, then hot reloading stops working and all subsequent launch attempts fail. Seemingly nothing precipitates it, then seemingly nothing fixes it. I've been battling this for months now.

**Comment by Dmitry-N-Medvedev** [comment] 2019-09-22 09:27
guys, let's try disabling wifi on the device and see if it helps ( it did help in my case of iOS 13 )

**Comment by juicechu** [comment] 2019-10-12 04:51
`flutter doctor -v` show everything is ok
I found that this problem occurs as long as the iphone and mac are on the same LAN.
And if they are on the same LAN, `flutter run` is working

**Comment by lukepighetti** [comment] 2019-10-12 21:00
The problem occurs if they are on the same LAN, but `flutter run` works if they are on the same LAN?

**Comment by thavlik** [comment] 2019-12-02 14:47
I haven't been doing flutter development lately, but I can confirm that disabling wifi or joining a different network does not fix the issue.

**Comment by juicechu** [comment] 2020-01-16 02:59
> The problem occurs if they are on the same LAN, but `flutter run` works if they are on the same LAN? That seems contradictory?

sorry, i mean the iphone and mac not on the same LAN，everything is fine

**Comment by jmagman** [comment] 2020-04-08 17:46
Closing in favor of https://github.com/flutter/flutter/issues/46705 and related.  There's been a lot of recent work on this, you can try it on the [beta channel.](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)

**Closed by jmagman** 2020-04-08 17:47 UTC
Labels: engine, platform-ios, tool
