### ISSUE TITLE
a11y focus moves randomly in GridView with many children. 

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#61631] opened 2020-07-16 17:04 UTC
b/161434746

During the navigation in GridView, when GridView is scrolled by swiping, it is likely that A11y focus will jump randomly in the page. The black border indicates A11y focus will disappear sometimes. 

```dart
import 'package:flutter/material.dart';

void main() => runApp(A11yApp());

class A11yApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appBar =
    AppBar(title: const Icon(Icons.archive));

    return MaterialApp(
      home: Scaffold(
        appBar: appBar,
        body: SingleChildScrollView(
          child: Column(
            children: [_buildGridView(), _buildGridView(), _buildGridView()],
          ),
        ),
      ),
    );
  }

  Widget _buildGridView() {
    return Column(
      children: [
        const Text('Grid header'),
        GridView.count(
          shrinkWrap: true,
          crossAxisSpacing: 10,
          mainAxisSpacing: 10,
          crossAxisCount: 2,
          children: <Widget>[
            for (var i = 0; i < 50; ++i)
              Container(
                padding: const EdgeInsets.all(8),
                color: Colors.green[100],
                child: Text('Number $i'),
              ),
          ],
        ),
      ],
    );
  }
}
```

This is blocking release due to a11y review. See internal bug for videos on the behavior.

**Comment by nscobie** [comment] 2020-07-20 17:55
Quick status update: I have been focusing on debugging this issue for ~1.5 working days, but it's tricky and I haven't yet found the root cause. I will update this comment soon with my findings and thoughts so far.

**Comment by gaaclarke** [comment] 2020-07-20 22:20
@nscobie Did you see this when looking at the code, this TODO looks suspicious:
https://github.com/gaaclarke/engine/blob/44fdcfcac4d69708092f2e2a20cfb90ab7601117/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L206:L206
```objc
  } else if (layoutChanged) {
    // TODO(goderbauer): figure out which node to focus next.
    ios_delegate_->PostAccessibilityNotification(UIAccessibilityLayoutChangedNotification, nil);
  }
```

**Comment by chunhtai** [comment] 2020-07-20 22:28
I have an simpler repo
```dart
import 'package:flutter/material.dart';

void main() => runApp(A11yApp());

class A11yApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appBar =
    AppBar(title: const Icon(Icons.archive));

    return MaterialApp(
      home: Scaffold(
        appBar: appBar,
        body: SingleChildScrollView(
          child: GridView.count(
            shrinkWrap: true,
            crossAxisSpacing: 10,
            mainAxisSpacing: 10,
            crossAxisCount: 2,
            children: <Widget>[
              for (var i = 0; i < 50; ++i)
                Container(
                  padding: const EdgeInsets.all(8),
                  color: Colors.green[100],
                  child: Text('Number $i'),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by nscobie** [comment] 2020-07-20 22:30
@gaaclarke Yeah good catch, I've actually been thinking we could change that line if an API for programmatically changing a11y focus is ever introduced (#59594 and b/153847891#comment12), however I don't think it's causing our current issue. Passing `nil` is supposedly just a no-op, so a11y focus should remain on the newly focused element which was just swiped to and brought on screen.

**Comment by gaaclarke** [comment] 2020-07-20 22:36
@nscobie I'm not sure that comment refers to the next line of code but rather the code that doesn't yet exist there?  I was able to verify that that if statement is being executed when focus switches off the screen which is also the time before focus seems to jump.

**Comment by nscobie** [comment] 2020-07-20 22:57
@gaaclarke I think it's both actually. _UIAccessibility**Layout**ChangedNotification_ should be fired for any minor changes in layout (larger things like route changes are announced by _UIAccessibility**Screen**ChangedNotification_), and the second parameter can be used to change focus to a new element ([via StackOverflow](https://stackoverflow.com/a/28353796)). Since this code path is run whenever an update to the semantic tree would be considered a change in layout, it seems like it would be difficult to know which element to focus next without additional information being passed down from the framework. I think that's why we're just passing `nil` right now, since a no-op would be better than accidentally making the wrong decision on what deserves focus and potentially disorienting the user.

**Comment by nscobie** [comment] 2020-07-21 18:57
## More oddities

### Jumps happen at a consistent location, but the location is inconsistent

For a given configuration of types of scrollables, number of children, size of children), the element which causes the jump after swiping right enough ("jump point") seems to remain the same between app redeploys. Additionally, it is always "after the fold" (beyond the set of initially visible elements).

It's unclear whether the jump point is due to number of elements scrolled vs. number of pixels scrolled.

#### There appear to be caching issues as well

With the following repro, my iPhone 8 (iOS 13.5.1) will _usually_ jump after swiping onto element `11`, which is the third element beyond the fold. _However_, if I swipe back and forth and tap randomly before reaching the jump point of `11`, my jump point shifts to element `15`, and on future redeploys of the app _it remains at element `15`_ rather than the previous element `11`.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  debugPaintPointersEnabled = true;
  runApp(A11yApp());
}

class A11yApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
//      showSemanticsDebugger: true,
      home: Scaffold(
        appBar: AppBar(
            title: IconButton(
          icon: Icon(Icons.bug_report),
          onPressed: () =>
              debugDumpSemanticsTree(DebugSemanticsDumpOrder.traversalOrder),
        )),
        body: ListView(
          children: [
            ListView(
              shrinkWrap: true,
              children: <Widget>[
                for (var i = 1; i <= 50; ++i)
                  Container(
                    padding: const EdgeInsets.only(bottom: 50),
                    color: Colors.green[i%10 * 100],
                    child: Center(child: Text('$i')),
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

### Swiping very quickly delays the jump

If I continuously swipe very quickly and don't give the black focus box a chance to reappear between swipes, I can swipe beyond the normal "jump point" without triggering the usual focus jump. When I stop swiping, the focus will then jump back to the first element on screen as usual.

### Widgets present in the semantics tree

Results from calling `debugDumpSemanticsTree(DebugSemanticsDumpOrder.traversalOrder)` with different configurations:

**A single scrollable without `shrinkWrap`**
```dart
ListView(
  children: [ ... ],
);
```
The children currently visible in the viewport are seen in the semantics tree, in addition to at least one element offscreen in either direction, which is marked as `isHidden` (this is correct behavior, and enables accessibility scrolling on iOS)

**A single scrollable with `shrinkWrap: true`**
```dart
ListView(
  shrinkWrap: true,
  children: [ ... ],
);
```
The _only_ children in the semantics tree are those currently visible in the viewport, which prevents us from scrolling offscreen via swipe.

**Nested scrollables with `shrinkWrap: true` on the inner one**
```dart
ListView(
  children: [
    ListView(
      shrinkWrap: true,
      children: [ ... ],
    ),
  ],
)
```
_All of the children_ present in the list are displayed in the semantics tree, whether or not they are onscreen. I've tested this with 500 widgets, and it holds true.

**Comment by chunhtai** [comment] 2020-07-21 19:01
I also notice a weird behavior that the flutter receives a show on screen request for an non-exist id. not sure if this also happened in your case.

**Comment by chunhtai** [comment] 2020-07-21 22:56
ok i think i know where the problem is. I have been investigating the accessibility element in accessibility bridge.
and this is how it looks like

node 56 (rect: x=0, y=100, w=414, h=796 ))
     |
     | children
node6 (rect: x=0, y=0, w=212, h=212 )),    node7 (rect: x=212, y=0, w=212, h=212 )) ....

node 56 is the gridview where children are the container.

if we swipe to scroll the single child scroll view, the tree become like this


node 56 (rect: x=0, y=-120, w=414, h=796 ))
     |
     | children
node6 (rect: x=0, y=-220, w=212, h=212 )),    node7 (rect: x=212, y=-220, w=212, h=212 )) .... node14 (rect: x=700, y=950, w=212, h=212 ))


The children are updated correctly but the node56 no longer cover the entire viewport and that cause node 14 fall out of its parent rectangle. I think that confused the ios accessibility api. I believe something on their side are check the children must be within its parent rect in order to receive taps. I verified that by always hardcode the node 56 to have the right rect that cover the entire screen.

It seems like we need to update the framework the expend the gridview to have a larger height when its parent has an offset.

**Comment by nscobie** [comment] 2020-07-22 18:28
Thanks @chunhtai! I can confirm that seems to fix both the original random focus jumping issue, and the issue with being unable to tap newly revealed elements.

I have some concerns about accidentally breaking other scrolling use cases when updating the height of a GridView/scrollable to account for parent offset, but I'll look into it and see what I can figure out from here.

**Side note:** I was also considering changing the logic of `showOnScreen` to scroll the inner view rather than the outer view, but that would make scrolling onto the second GridView shown in the original repro be quite janky, as it would stay at the bottom of the screen, only revealing one row at a time. Instead, I believe we want to continue to support the behavior seen here, where the GridViews scroll seamlessly as one:
![flutter_04](https://user-images.githubusercontent.com/4683416/88213969-6c3dc600-cc27-11ea-9b69-e948b5610502.png)

**Comment by chunhtai** [comment] 2020-07-22 18:37
I also left a reply in the internal bug. If we want to stack gridview one after another, we usually use customscrollview
```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(A11yApp());

class A11yApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appBar =
    AppBar(title: const Icon(Icons.archive));

    return MaterialApp(
      home: Scaffold(
        appBar: appBar,
        body: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(child: Text('Grid header')), _buildGridView(),
            SliverToBoxAdapter(child: Text('Grid header')), _buildGridView(),
            SliverToBoxAdapter(child: Text('Grid header')), _buildGridView(),
          ],
        ),
      ),
    );
  }

  Widget _buildGridView() {
    return SliverGrid(
      delegate: SliverChildListDelegate(
        <Widget>[
          for (var i = 0; i < 50; ++i)
            Container(
              padding: const EdgeInsets.all(8),
              color: Colors.green[100],
              child: Text('Number $i'),
            ),
        ],
      ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 10,
        crossAxisSpacing: 10,
        childAspectRatio: 1.0,
      ),
    );
  }
}
```

**Comment by nscobie** [comment] 2020-07-23 02:07
Still investigating, but I think the fix will be more complicated than just expanding the GridView to have a larger height to account for the parent's scroll offset.

The `semanticBounds` for the `RenderShrinkWrappingViewport` used by shrink wrapped scrollables are being set correctly, and are large enough to encompass all offscreen children. However, the `SemanticsNode.rect` based off these bounds which is eventually passed to the engine has been clipped to fit within the parent's bounds. This clipping occurs when the framework is building the data to be sent to the engine.

It seems to me the clipping is either occurring before the translation from the parent's offset transform is applied, or there is some confusion between local and global space coordinates. However, if one of those options are true, I'm unsure why the issue would only be manifesting in this scenario with `shrinkWrap: true`.

Hoping to have a better grasp on this tomorrow.

**Comment by TahaTesser** [comment] 2020-07-24 12:50
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/tahatesser/Code/flutter_master
    • Framework revision e64fe11542 (11 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.89

• No issues found!

```

</details>

**Comment by nscobie** [comment] 2020-07-24 20:53
Sorry for not posting more regular updates, but I think I've finally found a solution, pending further testing and investigation.

[RenderViewportBase](https://github.com/flutter/flutter/blob/8e58c51d1a9b583b56c2ea9631625d73d3610c06/packages/flutter/lib/src/rendering/viewport.dart#L166) is an ancestor class for the viewport used by scrollables like `GridView` and `ListView`. It utilizes [two pane semantics](https://api.flutter.dev/flutter/rendering/RenderViewport/useTwoPaneSemantics-constant.html) to create an inner and an outer node ("pane") in the semantics tree, which allows for [excluding some children](https://api.flutter.dev/flutter/rendering/RenderViewport/excludeFromScrolling-constant.html) from semantic actions related to scrolling by placing the included children under the inner pane but the excluded children under the outer pane.

However, when this two pane viewport is nested under another scrollable, it looks like only the outer "pane" had its `rect` position adjusted to compensate for translations which would occur when the [engine calculates the semantic bounds](https://github.com/flutter/engine/blob/3596b9b8b4dc49137b02ac736675f1509c82c828/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L356) of an element by recursively applying each ancestor's transform. This is illustrated by the logs below (although they may be difficult to follow out of context).

**If we change the inner pane's `rect` to equal the outer pane's `rect` instead of just its size with offset zero, then the issue seems to be fixed. This would mean changing [this line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L787) from `..rect = Offset.zero & node.rect.size;` to `..rect = node.rect;`**

This fixes the original sample repro from the customer, and passes our current local unit tests (running `flutter test` in `packages/flutter` of the framework) but I would like to test other scrolling and nesting scenarios before claiming this is the final fix.

**Side note:** I was also investigating how semantic node [geometry is being calculated](https://github.com/flutter/flutter/blob/5e0ba2290f2905ee8260f6d42f31e5d6bca69686/packages/flutter/lib/src/rendering/object.dart#L3837), but ultimately couldn't figure out how to fix the issue by changing things there. If the above fix ends up not working out, this might be an area to investigate further.

### Debugging logs

TODO: explain what's going on here.

Node numbers:
```
#4 = SingleChildScrollView
#6 = GridView outer pane
#57 = Gridview inner pane
```

#### Slices of tree in framework

**Before scrolling**
```
2020-07-24 08:57:40.828941-0700 Runner[325:16481] flutter:        └─SemanticsNode#4
2020-07-24 08:57:40.829048-0700 Runner[325:16481] flutter:          │ Rect.fromLTRB(0.0, 76.0, 320.0, 568.0)
2020-07-24 08:57:40.829185-0700 Runner[325:16481] flutter:          │ actions: scrollUp
2020-07-24 08:57:40.829347-0700 Runner[325:16481] flutter:          │ flags: hasImplicitScrolling
2020-07-24 08:57:40.829460-0700 Runner[325:16481] flutter:          │ scrollExtentMin: 0.0
2020-07-24 08:57:40.829716-0700 Runner[325:16481] flutter:          │ scrollPosition: 0.0
2020-07-24 08:57:40.829856-0700 Runner[325:16481] flutter:          │ scrollExtentMax: 587.5
2020-07-24 08:57:40.830002-0700 Runner[325:16481] flutter:          │
2020-07-24 08:57:40.830213-0700 Runner[325:16481] flutter:          ├─SemanticsNode#5
2020-07-24 08:57:40.830470-0700 Runner[325:16481] flutter:          │   Rect.fromLTRB(121.0, 0.0, 199.0, 17.0)
2020-07-24 08:57:40.830606-0700 Runner[325:16481] flutter:          │   label: "Grid header"
2020-07-24 08:57:40.830703-0700 Runner[325:16481] flutter:          │   textDirection: ltr
2020-07-24 08:57:40.830960-0700 Runner[325:16481] flutter:          │
2020-07-24 08:57:40.831169-0700 Runner[325:16481] flutter:          └─SemanticsNode#6
2020-07-24 08:57:40.831283-0700 Runner[325:16481] flutter:            │ Rect.fromLTRB(0.0, 17.0, 320.0, 492.0)
2020-07-24 08:57:40.831535-0700 Runner[325:16481] flutter:            │
2020-07-24 08:57:40.831648-0700 Runner[325:16481] flutter:            └─SemanticsNode#57
2020-07-24 08:57:40.831774-0700 Runner[325:16481] flutter:              │ Rect.fromLTRB(0.0, 0.0, 320.0, 475.0)
2020-07-24 08:57:40.831913-0700 Runner[325:16481] flutter:              │ flags: hasImplicitScrolling
2020-07-24 08:57:40.832062-0700 Runner[325:16481] flutter:              │ scrollChildren: 50
2020-07-24 08:57:40.832289-0700 Runner[325:16481] flutter:              │ scrollIndex: 0
2020-07-24 08:57:40.832421-0700 Runner[325:16481] flutter:              │ scrollExtentMin: 0.0
2020-07-24 08:57:40.832557-0700 Runner[325:16481] flutter:              │ scrollPosition: 0.0
2020-07-24 08:57:40.832739-0700 Runner[325:16481] flutter:              │ scrollExtentMax: 0.0
```

**After scroll 1**
```
2020-07-24 09:00:42.367591-0700 Runner[325:16481] flutter:        └─SemanticsNode#4
2020-07-24 09:00:42.367723-0700 Runner[325:16481] flutter:          │ Rect.fromLTRB(0.0, 76.0, 320.0, 568.0)
2020-07-24 09:00:42.367836-0700 Runner[325:16481] flutter:          │ actions: scrollDown, scrollUp
2020-07-24 09:00:42.367960-0700 Runner[325:16481] flutter:          │ flags: hasImplicitScrolling
2020-07-24 09:00:42.368090-0700 Runner[325:16481] flutter:          │ scrollExtentMin: 0.0
2020-07-24 09:00:42.368222-0700 Runner[325:16481] flutter:          │ scrollPosition: 92.5
2020-07-24 09:00:42.368348-0700 Runner[325:16481] flutter:          │ scrollExtentMax: 587.5
2020-07-24 09:00:42.368474-0700 Runner[325:16481] flutter:          │
2020-07-24 09:00:42.368598-0700 Runner[325:16481] flutter:          ├─SemanticsNode#5
2020-07-24 09:00:42.368728-0700 Runner[325:16481] flutter:          │   Rect.fromLTRB(121.0, -92.5, 199.0, -75.5)
2020-07-24 09:00:42.368850-0700 Runner[325:16481] flutter:          │   flags: isHidden
2020-07-24 09:00:42.368972-0700 Runner[325:16481] flutter:          │   HIDDEN
2020-07-24 09:00:42.369173-0700 Runner[325:16481] flutter:          │   label: "Grid header"
2020-07-24 09:00:42.369573-0700 Runner[325:16481] flutter:          │   textDirection: ltr
2020-07-24 09:00:42.369617-0700 Runner[325:16481] flutter:          │
2020-07-24 09:00:42.369657-0700 Runner[325:16481] flutter:          └─SemanticsNode#6
2020-07-24 09:00:42.369697-0700 Runner[325:16481] flutter:            │ Rect.fromLTRB(0.0, 0.0, 320.0, 492.0)
2020-07-24 09:00:42.369733-0700 Runner[325:16481] flutter:            │
2020-07-24 09:00:42.369771-0700 Runner[325:16481] flutter:            └─SemanticsNode#57
2020-07-24 09:00:42.369809-0700 Runner[325:16481] flutter:              │ Rect.fromLTRB(0.0, 0.0, 320.0, 492.0)
2020-07-24 09:00:42.369848-0700 Runner[325:16481] flutter:              │ flags: hasImplicitScrolling
2020-07-24 09:00:42.369884-0700 Runner[325:16481] flutter:              │ scrollChildren: 50
2020-07-24 09:00:42.369991-0700 Runner[325:16481] flutter:              │ scrollIndex: 4
2020-07-24 09:00:42.370240-0700 Runner[325:16481] flutter:              │ scrollExtentMin: 0.0
2020-07-24 09:00:42.370454-0700 Runner[325:16481] flutter:              │ scrollPosition: 0.0
2020-07-24 09:00:42.370647-0700 Runner[325:16481] flutter:              │ scrollExtentMax: 0.0
```

**After scroll 2**
```
2020-07-24 09:02:05.234406-0700 Runner[325:16481] flutter:        └─SemanticsNode#4
2020-07-24 09:02:05.234446-0700 Runner[325:16481] flutter:          │ Rect.fromLTRB(0.0, 76.0, 320.0, 568.0)
2020-07-24 09:02:05.234484-0700 Runner[325:16481] flutter:          │ actions: scrollDown, scrollUp
2020-07-24 09:02:05.234522-0700 Runner[325:16481] flutter:          │ flags: hasImplicitScrolling
2020-07-24 09:02:05.234559-0700 Runner[325:16481] flutter:          │ scrollExtentMin: 0.0
2020-07-24 09:02:05.234595-0700 Runner[325:16481] flutter:          │ scrollPosition: 175.0
2020-07-24 09:02:05.234632-0700 Runner[325:16481] flutter:          │ scrollExtentMax: 587.5
2020-07-24 09:02:05.234667-0700 Runner[325:16481] flutter:          │
2020-07-24 09:02:05.234747-0700 Runner[325:16481] flutter:          ├─SemanticsNode#5
2020-07-24 09:02:05.234790-0700 Runner[325:16481] flutter:          │   Rect.fromLTRB(121.0, -175.0, 199.0, -158.0)
2020-07-24 09:02:05.234829-0700 Runner[325:16481] flutter:          │   flags: isHidden
2020-07-24 09:02:05.234906-0700 Runner[325:16481] flutter:          │   HIDDEN
2020-07-24 09:02:05.234946-0700 Runner[325:16481] flutter:          │   label: "Grid header"
2020-07-24 09:02:05.234984-0700 Runner[325:16481] flutter:          │   textDirection: ltr
2020-07-24 09:02:05.235063-0700 Runner[325:16481] flutter:          │
2020-07-24 09:02:05.235104-0700 Runner[325:16481] flutter:          └─SemanticsNode#6
2020-07-24 09:02:05.235141-0700 Runner[325:16481] flutter:            │ Rect.fromLTRB(0.0, 0.0, 320.0, 492.0)
2020-07-24 09:02:05.235181-0700 Runner[325:16481] flutter:            │
2020-07-24 09:02:05.235260-0700 Runner[325:16481] flutter:            └─SemanticsNode#57
2020-07-24 09:02:05.235302-0700 Runner[325:16481] flutter:              │ Rect.fromLTRB(0.0, 0.0, 320.0, 492.0)
2020-07-24 09:02:05.235340-0700 Runner[325:16481] flutter:              │ flags: hasImplicitScrolling
2020-07-24 09:02:05.235888-0700 Runner[325:16481] flutter:              │ scrollChildren: 50
2020-07-24 09:02:05.235932-0700 Runner[325:16481] flutter:              │ scrollIndex: 8
2020-07-24 09:02:05.235971-0700 Runner[325:16481] flutter:              │ scrollExtentMin: 0.0
2020-07-24 09:02:05.236008-0700 Runner[325:16481] flutter:              │ scrollPosition: 0.0
2020-07-24 09:02:05.236045-0700 Runner[325:16481] flutter:              │ scrollExtentMax: 0.0
```

#### Node updates received by the engine

**Before scrolling**
```
id: 4, rect = (0.0, 0.0, 320.0, 492.0), transform = \ 
    |1 0 0 0|
    |0 1 0 76|
    |0 0 1 0|
    |0 0 0 1|
id: 6, rect = (0.0, 0.0, 320.0, 475.0), transform = \ 
    |1 0 0 0|
    |0 1 0 17|
    |0 0 1 0|
    |0 0 0 1|
id: 57, rect = (0.0, 0.0, 320.0, 475.0), transform = \ 
    |1 0 0 0|
    |0 1 0 0|
    |0 0 1 0|
    |0 0 0 1|

rects after applying ancestor transforms
4  = SkRect::MakeLTRB(0, 76, 320, 568);
6  = SkRect::MakeLTRB(0, 93, 320, 568);
57 = SkRect::MakeLTRB(0, 93, 320, 568);
```

**After scroll 1**
```
id: 4, rect = (0.0, 0.0, 320.0, 492.0), transform = \ 
    |1 0 0 0|
    |0 1 0 76|
    |0 0 1 0|
    |0 0 0 1|
id: 6, rect = (0.0, 75.5, 320.0, 567.5), transform = \ 
    |1 0 0 0|
    |0 1 0 -75.5|
    |0 0 1 0|
    |0 0 0 1|
id: 57, rect = (0.0, 0.0, 320.0, 492.0), transform = \ 
    |1 0 0 0|
    |0 1 0 0|
    |0 0 1 0|
    |0 0 0 1|

rects after applying ancestor transforms
4  = SkRect::MakeLTRB(0, 76, 320, 568);
6  = SkRect::MakeLTRB(0, 76, 320, 568);
57 = SkRect::MakeLTRB(0, 0.5f, 320, 492.5f);
```

**After scroll 2**
```
id: 4, rect = (0.0, 0.0, 320.0, 492.0), transform = \ 
    |1 0 0 0|
    |0 1 0 76|
    |0 0 1 0|
    |0 0 0 1|
id: 6, rect = (0.0, 158.0, 320.0, 650.0), transform = \ 
    |1 0 0 0|
    |0 1 0 -158|
    |0 0 1 0|
    |0 0 0 1|
id: 57, NOT PRESENT (since no change)

rects after applying ancestor transforms
4  = SkRect::MakeLTRB(0, 76, 320, 568);
6  = SkRect::MakeLTRB(0, 76, 320, 568);
57 = SkRect::MakeLTRB(0, -82, 320, 410);
```

**Comment by Hixie** [comment] 2020-07-28 22:56
@nscobie Please update the issue with a conservative target milestone saying when you expect the fix will land, thanks! (This is just for planning purposes, helps us during triage.)

**Closed** 2020-07-31 16:46 UTC
Labels: P1, a: accessibility, customer: money (g3), f: scrolling, found in release: 1.21, framework, has reproducible steps, passed first triage, platform-ios, waiting for PR to land (fixed)
