### ISSUE TITLE
camera - takePicture and Firebase ML Vision

### ISSUE THREAD

**Issue by olheimer** [flutter/flutter#36254] opened 2019-07-16 12:28 UTC
## Steps to Reproduce

Device: iPhone 6, IOS 12.3.1

I am adapting the Flutter Firebase ML vision example (https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision/example). 
There the camera plugin is listening to startImageStream to perform text analysis on the camera data : camera_preview_scanner.dart.

A second part of this project is using image_picker to read camera or gallery image an do the same but on  a caputred image. (camera_preview_scanner.dart)

So I tried to change the camera_preview_scanner to use an image taken by camera plugin with the method takePicture and read the file in the same way a file from image_picker was read. 
But this did't work. 
I finally got it working by using flutter_image_compress plugin an just call FlutterImageCompress.compressAndGetFile with the saved file from camera plugin and put the result to Firebase ML Vision. Suddenly it worked.

On Android the image could be read by Firebase ML Vision without any extra measurments.
 
Is there any difference in imageformat from image_picker compared to camera takePicture?

**Comment by voduytuan** [comment] 2019-07-17 09:19
I think that the "camera" plugin stored photo with landscape mode and EXIF information (orientation info is portrait mode). So that, you can try capture the photo (with face) in landscape mode and the firebase_ml_vision will detect faces in landscape captured photo.

I'd just got this bug today, if i capture in portrait mode (iphone), firebase_ml_vision can not detect face. But when i rotate my camera in landscape and capture photo, this plugin works. I'm searching the solution to work around.

And i think the flutter_image_compress plugin you commented had remove the exif info and rotated the photo automattically.

**Comment by olheimer** [comment] 2019-07-18 09:26
But when I use the exif plugin I can read some exif information, also an orientation paramter. The paramter changes when switchin between portrait and and landscape mode.

What I tried now: compare the exif returned from "native camera" via image_picker to the exif data returned by images taken with the Flutter camera Plugin:

Native camera: Only in landscape left (when turning the device to the left (top of phone is left) => Orientation value is 1) the exif data are set. Otherwise they are null

Camera Plugin: In all modes exif data is received. The orientation value changes when changing device orientation

**Comment by BondarenkoStas** [comment] 2019-09-27 23:27
Duplicate of #35334. Closing it, please follow the referenced issue. @olheimer If you disagree, please comment and I will re-open it right away.

**Closed by BondarenkoStas** 2019-09-27 23:27 UTC
