### ISSUE TITLE
[Web][CanvasKit]: Locale text with punctuation such as full stop, comma position is misaligned.

### ISSUE THREAD

**Issue by shenruisi** [flutter/flutter#81300] opened 2021-04-27 15:19 UTC
![image](https://user-images.githubusercontent.com/911991/116267292-dd11a000-a7ae-11eb-89eb-61c505684357.png)
Code as below

![image](https://user-images.githubusercontent.com/911991/116267475-05999a00-a7af-11eb-89b0-a76798788d40.png)

**Comment by MasahideMori-SimpleAppli** [comment] 2021-04-28 02:23
The same phenomenon occurs in Japanese.
This is a pretty big problem.
For example
"こんにちは、Flutter。"
Then
"、" And "。" move to the middle of the line.

**Comment by darshankawar** [comment] 2021-04-28 06:56
@shenruisi 
Can you provide `flutter doctor -v` and provide the code in formatted text instead of screenshot, so that we can directly use it to verify this issue ?

Thanks.

**Comment by MasahideMori-SimpleAppli** [comment] 2021-04-28 09:19
Hi @shenruisi and @darshankawar.

Perhaps I have a similar problem.
So I will also submit my report as one of the sample cases.
Notably, recent Mac OS updates aren't the cause.
Also, there is a beta version of Flutter 1.x that does not contain this bug.

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.3 20E232 darwin-x64, locale ja-JP)
    • Flutter version 2.0.2 at /Users/morimasahide/documents/flutter
    • Framework revision 8962f6dc68 (7 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/morimasahide/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

**Comment by MasahideMori-SimpleAppli** [comment] 2021-04-28 09:24
Run the following code to find the bug.
Thank you.

```
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text(
              'こんにちは、Flutter。（Bug）',
              style: TextStyle(
                fontSize: 24,
              ),
            ),
            Text(
              'Hello, Flutter. (Correct display)',
              style: TextStyle(
                fontSize: 24,
              ),
            ),
          ],
        )
      ),
    );
  }
}
```

**Comment by MasahideMori-SimpleAppli** [comment] 2021-04-28 09:33
Postscript: The result is the same even if flutter upgrade.
I feel like there is a bug in Flutter 2.x.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (1 available)

**Comment by darshankawar** [comment] 2021-04-28 10:28
@MasahideMori-SimpleAppli 
Thanks for the code sample and detailed report. I tried it using latest master and believe is an issue with canvaskit rendering, because using `html` rendering, we see the `full stop` at correct position as below:

1. with `html` rendering : flutter run -d chrome --web-renderer html:

<img width="727" alt="Screenshot 2021-04-28 at 3 56 15 PM" src="https://user-images.githubusercontent.com/67046386/116389303-69b57000-a83a-11eb-8915-453fad38a7d9.png">


2. With `canvaskit` rendering: flutter run -d chrome:

<img width="682" alt="Screenshot 2021-04-28 at 3 54 37 PM" src="https://user-images.githubusercontent.com/67046386/116389369-7934b900-a83a-11eb-9a22-afbdd91b4e44.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (6 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

**Comment by MasahideMori-SimpleAppli** [comment] 2021-04-28 10:48
Dear @darshankawar

Thank you for letting me know.
It helped me a lot!

**Comment by shenruisi** [comment] 2021-05-02 12:03
@darshankawar 

Sorry for reply late. If i use html render, the punctuation seems in the right position. And waiting for fixed with CanvasKit.

**Comment by dion-li** [comment] 2022-02-17 10:30
> @MasahideMori-SimpleAppli Thanks for the code sample and detailed report. I tried it using latest master and believe is an issue with canvaskit rendering, because using `html` rendering, we see the `full stop` at correct position as below:
> 
> 1. with `html` rendering : flutter run -d chrome --web-renderer html:
> 
> <img alt="Screenshot 2021-04-28 at 3 56 15 PM" width="727" src="https://user-images.githubusercontent.com/67046386/116389303-69b57000-a83a-11eb-8915-453fad38a7d9.png">
> 
> 2. With `canvaskit` rendering: flutter run -d chrome:
> 
> <img alt="Screenshot 2021-04-28 at 3 54 37 PM" width="682" src="https://user-images.githubusercontent.com/67046386/116389369-7934b900-a83a-11eb-9a22-afbdd91b4e44.png">
> 
> flutter doctor -v

no, this is not the solution, because if i change to html render , the text style and color style will be change, please fix this problem quicklly

**Comment by MasahideMori-SimpleAppli** [comment] 2022-02-17 12:22
For Japanese texts, I was able to solve this problem.
It could be a problem with the default font.
When using the Noto Sans Japanese font, it could be displayed without any problem.
However, this solution requires font downloads, which is costly.

**Comment by kevmoo** [comment] 2022-05-09 19:16
We're looking into this. Need to chat w/ our friends working on Skia (CanvasKit)

**Comment by jason-simmons** [comment] 2022-05-09 21:35
The font fallback rules in the engine are prioritizing a font that renders these characters at a different position (see https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/font_fallbacks.dart)

I added logging to `_getEffectiveFontFamilies` and tried rendering this text.  The resulting family list was:
```
[Roboto, Ubuntu, Cantarell, DejaVu Sans, Liberation Sans, Arial, Roboto,
Noto Sans TC 0, Noto Sans TC 1, Noto Sans TC 2, Noto Sans SC 0, Noto Sans SC 1, Noto Sans
JP 0, Noto Sans JP 1, Noto Sans HK 0, Noto Sans HK 1, Noto Sans HK 2]
```
with the additional downloaded fallback fonts added in reverse alphabetical order.

If I patch `_getEffectiveFontFamilies` to move the `Noto Sans JP` fonts to the head of the list, then the characters render at the desired position.

**Comment by mdrideout** [comment] 2022-05-10 15:56
I'm unsure of whether this is directly relevant to the above comment or how downloaded fallback fonts work... However, 
because of the number of languages and characters we need to support, it is not practical for us to package the fonts into our app. Relying on user system fonts is best. Noto Sans JP is 4.5MB for a single font style alone. 

Unsure of what downloaded fallback fonts do to the application loading times.

**Comment by yjbanov** [comment] 2022-05-10 22:27
@mdrideout Be aware that in CanvasKit mode we have to download fonts even if you do not supply your own fonts. The fonts we download are sliced into many small files, so we don't fetch 4.5MB all at once, but instead we load them dynamically on-demand. The app loading time is therefore not affected, but some previously unseen characters may not render correctly or render as boxes while waiting for the font to arrive. We're looking to improve this in the future by better predicting the fonts the user may need (e.g. based on the `navigator.language` setting), [upcoming browser APIs](https://wicg.github.io/local-font-access/), and potentially adding API for developers to provide explicit signals to the Flutter engine.

**Comment by EGabriel12** [comment] 2022-05-31 12:54
Hi everyone
@kevmoo, is Skia team working on it?

**Comment by kevmoo** [comment] 2022-05-31 19:44
An engineer on our team is looking at it. Just not sure which one, @EGabriel12

**Comment by hterkelsen** [comment] 2022-09-26 22:29
I believe this issue is fixed now: 
![image](https://user-images.githubusercontent.com/1961493/192391859-0ef3924d-da40-4d07-a8d4-4b4e55a0cde5.png)

**Closed by hterkelsen** 2022-09-26 22:29 UTC
Labels: engine, a: internationalization, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 2.3
