### ISSUE TITLE
Support for downloading videos and offline playback

### ISSUE THREAD

**Issue by seanjackson** [flutter/flutter#107657] opened 2022-07-14 15:44 UTC
I am currently developing a movie streaming app one of the requirement is that the movie which is on hls video type that is m3u8 should be downloaded inside the app.The user should not be able to download on the external device. We noticed that flutter video player can not download and play offline video just like you have it in exoplayer.
Please can someone propose a solution or a way to go about this please.

**Comment by exaby73** [comment] 2022-07-15 07:16
Doesn't `VideoPlayerController.file` work for you? You can save the video files in the app and reference them using a `File` object.

**Comment by seanjackson** [comment] 2022-07-15 08:02
@exaby73 Thanks brother for the reply.We went for the flutter cache manager but right now the videos are saving but not playing.We want something like Netflix or youtube where users can download the movies or the video in app and delete after 2weeks.Please is there a way to go about this

**Comment by exaby73** [comment] 2022-07-18 03:20
@seanjackson I am not sure to be honest. I think your best bet would be asking on Stackoverflow or any of the communities highlighted on https://flutter.dev/community.

Unfortunately, I will close this issue since this is not a bug or feature request. If you disagree, please comment and we can reopen it. Thank you

**Closed** 2022-07-18 03:20 UTC
Labels: r: invalid
