### ISSUE TITLE
Should support trackpad gestures from host

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#23604] opened 2018-10-27 00:26 UTC
When running on a desktop platform, Flutter should be able to get trackpad gesture information from the host to enable scrolling.

**Comment by gspencergoog** [comment] 2019-05-02 00:58
Gestures should include scroll, pinch, and zoom.

Scroll is already minimally supported, because it falls back to emulating mouse scrollwheel, which is already implemented, but it's not as proportional as it should be.

**Comment by stuartmorgan** [comment] 2019-05-02 03:52
I had a proposed approach for gestural scroll (which assumed the OS itself was providing pre-interpreted gesture streams, as are available on macOS for scroll and pinch, for instance), which was intended to be extensible to other gestures like pinch to zoom, but Hixie was concerned that as implemented it conflated pre-interpreted gestures with the raw gesture input that recognizers are designed for.

Where it left off was that he wanted a doc that cataloged all the relevant gesture stream info that was available for each OS (we'd want to cover macOS, Windows, Linux, and Chrome OS), so that we could design accordingly. That's still on my TODO list, but has been consistently below other work in priority, so if someone else wants to do that before I get to it I'm happy to hand off.

**Comment by stuartmorgan** [comment] 2019-06-17 01:24
(For background see the discussion on #21953, particularly the end.)

**Comment by dkwingsmt** [comment] 2019-08-23 21:40
Note for a temporary fix in `AndroidTouchProcessor.java`:

On a Chromebook, if the user scrolls using two fingers on the trackpad, ARC translates it into a mouse down-move-up event sequence with "buttons: 0", which is no longer acceptable by `DragGestureRecognizer`.

This temporary fix patches these events by setting `buttons` to `1`, the primary button. This is by no means perfect, besides being ugly, but also it can trigger unintended drags that are not scrolling. The correct way is to implement trackpad gestures (as in this issue), but it is a much bigger job.

After this issue is fixed, remove the patch (the if-clause).

**Comment by SahajRana** [comment] 2020-02-12 08:50
@dkwingsmt @gspencergoog @stuartmorgan Are you guys working on this? We need this functionality for our project! Thanks.

**Comment by dkwingsmt** [comment] 2020-02-12 23:29
While I understand the importance of this feature, I don't think any of us 3 are working on it at the moment.  This is still on my radar and might come back after issues of higher priorities are finished.

**Comment by jmagman** [comment] 2020-03-19 22:52
iPadOS 13.4 (March 24 release) supports mouse/trackpad for 2018 iPad Pro.

**Comment by modulovalue** [comment] 2020-04-24 15:06
@gspencergoog @stuartmorgan could this issue please be expanded to include the ability to react to all trackpad changes, not just the limited set of gestures that were enumerated in the first comment https://github.com/flutter/flutter/issues/23604#issuecomment-488523607 i.e. force touch information on macOS (#53988) and changes to individual fingers via Listener.onPointerSignal.

**Comment by stuartmorgan** [comment] 2020-04-24 15:41
No; those are all district things that need distinct solutions. Please file a new feature request for raw touch information.

**Comment by escamoteur** [comment] 2020-10-29 19:32
Will this also support touch screens on Notebooks? Is this already supported on any desktop platform?

**Comment by dkwingsmt** [comment] 2020-10-29 19:35
Touch screen on notebook is supported by touch events, and I would be surprised if it isn't already supported; although if you're talking about pinching and rotating, that have to be recognized by the app. Otherwise, for touchpad, no progress yet.

**Comment by stuartmorgan** [comment] 2020-10-29 19:38
> I would be surprised if it isn't already supported

Touch events have not been wired up in any desktop embedding. That's unrelated to this issue though (see #52202, #65171)

**Comment by clarkezone** [comment] 2021-01-07 22:21
To do this on Windows with max perf we’d have to use DirectManipulation or InteractionTracker API’s

**Comment by samiuelson** [comment] 2021-03-12 10:34
Other than scroll gestures, also "back" and "forward" trackpad gestures should be supported. They are commonly used gestures on macOS.

**Comment by praveeng2565** [comment] 2021-04-15 04:50
I'm also facing this issue while trying to do pinch zoom using the trackpad on a macOS with an interactive viewer widget.

**Comment by michaelu123** [comment] 2021-04-29 07:06
This issue was opened on Oct 2018, now we have April 2021. Many issues were closed as duplicates of this issue, but here not much seems to happen. And I think the reference to a trackpad is misleading, because I want to be able to zoom/rotate on Windows or Web even without having a trackpad, just using a mouse. Either with a mouse wheel, or in a way similar to what Kivy does for Python: A right click paints a dot on the screen, simulating one finger, another mouse-click with hold simulates the second finger, which can now be moved around, towards or away from the dot, thus causing zoom or rotate. Another click on the dot removes it again.

**Comment by stuartmorgan** [comment] 2021-04-29 12:19
> And I think the reference to a trackpad is misleading

It isn't, because this issue is about wiring up trackpad gestures. If you want something else, that needs to be filed as a separate issue.

**Comment by michaelu123** [comment] 2021-05-04 08:50
OK, not misleading. I had the impression that people who migrate from an Android or IOS Flutter app to a Web or Windows app like me, and are surprised that they cannot pinch and zoom, come eventually to this issue, because trackpad gestures come close to what you can do on a mobile screen. But not all trackpads support more than one finger, and many PCs do not even have a trackpad. Therefore I think it would be nice to have something in the platform, that emulates two finger gestures. Like with kivy. But you are right, such a feature needs a separate issue. In the meantime, I use the Listener widget and the mouse wheel. With no mouse key pressed, the wheel zooms, with a key pressed, it rotates.

**Comment by SwissCheese5** [comment] 2021-05-12 11:14
I found several problems:
- Trackpad scrolling produces a delta of zero in a Windows Window, but not Flutter web on Windows.
- onPointerSignal in Listener does NOT fire when any other key is pressed. This works in Flutter web, but not Windows. It fires extremely inconsistently on Windows.

Here's a dartpad replicating the behavior. It works in the dartpad website, but they won't fire properly on Windows.
https://dartpad.dev/0bba2bc60f5ea81322463f91a37c5053?null_safety=true

I need to add that I have the synaptics touchpad driver.
![image](https://user-images.githubusercontent.com/7407478/117966132-3d1a5180-b32c-11eb-95e2-41aacb4eddd2.png)
![image](https://user-images.githubusercontent.com/7407478/117966161-47d4e680-b32c-11eb-8faa-83f86e6c37ae.png)

Should I file a separate issue or keep this here? This functionality is crucial to my team's project for accessibility purposes.

**Comment by stuartmorgan** [comment] 2021-05-12 11:59
@SwissCheese5 You should file new issues. This issue is about supporting trackpad gestures directly; the fact that trackpad scroll currently sends scroll wheel events is partial workaround for the lack of support tracked here. Limitations with that workaround would be unrelated to this.

**Comment by SwissCheese5** [comment] 2021-05-12 12:33
Done, thank you.

**Comment by AbhishekDoshi26** [comment] 2021-05-12 18:22
Not just scroll, we can't even select a particular text in Web.

**Comment by AryashDubey** [comment] 2021-06-15 08:21
Idk why but there are still no updates on this issue. Its a major problem and should be solved ASAP. I also have my flutter web project that needs this. Please solve it 🙏

**Comment by moffatman** [comment] 2021-06-18 22:23
@dkwingsmt @gspencergoog @stuartmorgan

I think since iPadOS only exposes the trackpad gestures through UIKit gesture recognizers, an approach of parsing raw trackpad touches in Flutter won't work. It will have to involved forwarding the native gesture details to the proper GestureRecognizers. 

By faking touches instead of sending scroll events, I was able to get two-finger swiping gestures to behave identically to native UIKit. Of course it will be better to turn the events into DragUpdateDetails and route them to the GestureRecognizer underneath the cursor. 

https://github.com/moffatman/engine/commit/1ff25130a7130f1e6cdfbb2bfde5b6ce712b302e

I am happy to contribute to this feature. I would love to get the native trackpad feel on my app on iPad, so please let me know if I'm wasting my time here or it's something I should continue at.

**Comment by stuartmorgan** [comment] 2021-06-18 23:28
https://github.com/flutter/flutter/issues/23604#issuecomment-488545525 is still the next step for this issue. This needs a design doc before it is implemented.

If you want to contribute to this feature, making that document would be the next step.

**Comment by khari998** [comment] 2021-08-29 05:50
Any progress on this would be greatly appreciated. I feel like this is one of the most crucial features for Flutter web.

**Comment by moffatman** [comment] 2021-08-29 16:42
I have almost completed my design document and some implementations. Hate to break it to you @khari998 but I don't believe it will be possible to get trackpad gestures working on the Web.

**Comment by khari998** [comment] 2021-08-29 21:05
> I have almost completed my design document and some implementations. Hate to break it to you @khari998 but I don't believe it will be possible to get trackpad gestures working on the Web.

I just converted a production website to Flutter Web and this seems to be the only thing missing. I want to cry 🙃

What is preventing this from being possible?

**Comment by moffatman** [comment] 2021-08-30 02:30
The browser doesn't tell web application code when scrolling ends. So we can't know whether the user is still holding their fingers on the trackpad or they lifted them off. See https://github.com/w3c/uievents/issues/58. Only on Safari it could be possible, since they have a non-standard feature called Gesture Events. But in general the browser steals all the gestures for itself and does the zooming and manipulating of the page.

**Comment by khari998** [comment] 2021-08-30 02:38
> The browser doesn't tell web application code when scrolling ends. So we can't know whether the user is still holding their fingers on the trackpad or they lifted them off. See [w3c/uievents#58](https://github.com/w3c/uievents/issues/58). Only on Safari it could be possible, since they have a non-standard feature called Gesture Events. But in general the browser steals all the gestures for itself and does the zooming and manipulating of the page.

So basically Chrome interprets the gestures from the trackpad by itself for the HTML it renders but is not able to handle it for Flutter because Flutter isn't in HTML?

**Comment by dkwingsmt** [comment] 2021-08-30 02:41
I think Web has standardized scroll events but I guess probably not for zooming events or scroll ends, or other details. Anyway, I'm looking forward to @moffatman's design docs. :)

**Comment by moffatman** [comment] 2021-09-01 13:32
@dkwingsmt 
Here's the document: https://flutter.dev/go/trackpad-gestures
I have it implemented on nearly all platforms, but it's not cleaned up. So I'll wait for design comments then fixup before creating the PR.

**Comment by dkwingsmt** [comment] 2022-05-11 10:28
> ## TODO
> After this is implemented, revert the patch in [flutter/engine#11420](https://github.com/flutter/engine/pull/11420) by removing the if-clause and the variable `_POINTER_BUTTON_PRIMARY`.
> 
> For reasoning, see the PR.

This TODO will be fixed by https://github.com/flutter/engine/pull/31595/files#r870134971. However, I'll to test it on a real device.

**Closed** 2022-06-14 00:03 UTC
Labels: new feature, platform-ios, framework, engine, f: gestures, platform-chromebook, a: desktop, customer: octopod, P4
