### ISSUE TITLE
[Impeller] Material widget's borderRadius clips the shadow of elevation

### ISSUE THREAD

**Issue by jehadhmoudah** [flutter/flutter#149474] opened 2024-06-01 10:31 UTC
### Steps to reproduce

1. Copy the provided code
2. Run, once using Skia and once using Impeller

Add 
```html
  <key>FLTEnableImpeller</key>
  <false/>
```
to Info.plist to run using Skia.

### Expected results

Using BorderRadius.only() for specific corners shouldn't clip the shadow produced by elevation.

Rendered with Skia:
<img src="https://github.com/flutter/flutter/assets/114701208/4a555dce-78d5-4557-b256-d05c09bee16e" width="250" height="auto">

### Actual results

The shadow gets clipped when rendering with Impeller and using BorderRadius.only()

Rendered with Impeller:
<img src="https://github.com/flutter/flutter/assets/114701208/adcaf2d4-04a2-461d-8607-c44102f56d16" width="270" height="auto">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text("Impeller"),
      ),
      body: Center(
        child: IntrinsicWidth(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(25),
                  topRight: Radius.circular(25),
                ),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Top"),
                ),
              ),
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                // borderRadius: BorderRadius.circular(25),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Middle"),
                ),
              ),
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.zero,
                  bottomLeft: Radius.circular(25),
                  topRight: Radius.zero,
                  bottomRight: Radius.circular(25),
                ),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Bottom"),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Here's a side by side comparison:
<div>
<img src="https://github.com/flutter/flutter/assets/114701208/1ea783c6-e91a-4f50-835e-2e89c89d43b1" width="250" height="auto">
<img src="https://github.com/flutter/flutter/assets/114701208/e48f357a-3623-4ae7-a40f-35775d83b269" width="250" height="auto">
</div>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1.1 23B81 darwin-arm64, locale en-PS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2024-06-03 07:45
Thanks for the report. Reproduced this issue on master channel as well.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 hours ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.69, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.69 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 124aacbaef (2 days ago), 2024-05-31 22:32:25 -0400
    • Engine revision d81edf635a
    • Dart version 3.5.0 (build 3.5.0-214.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jonahwilliams** [comment] 2024-06-03 17:46
This might be related to the work in https://github.com/flutter/engine/pull/53130 , or could be a coverage issue. needs investigation.

**Comment by gaaclarke** [comment] 2024-06-04 20:53
Here's the diff to help highlight the shadow differences:
![ezgif-7-494e54576b](https://github.com/flutter/flutter/assets/30870216/462ee474-84bc-40af-8424-81d7c55fca77)


In impeller the shadow is missing from the top of the item.  Also on the top left and right corners, left and right of them, the shadow is not consistent with the middle left and right of the shadows.

https://github.com/flutter/engine/pull/53130 won't have helped this since in the end it just changed the math for gaussian, not rrect_blur.  I probably should have changed the title.

**Comment by gaaclarke** [comment] 2024-06-04 21:06
I reran the test at 3dd40156afb6f878597d7018ea769b752ca5b115 on an iphone se and the differences aren't so stark as the above example.

![ezgif-7-ad6aaa73f8](https://github.com/flutter/flutter/assets/30870216/183336de-53e0-424e-a3db-7050dc4bb183)

The weird artifact where the middle is thicker is still present.  It isn't that noticeable.  The thing that seems to be the most wrong is the lack of any shadow at the top of the widget.

**Comment by gaaclarke** [comment] 2024-06-04 21:17
I filed a separate issue for the lack of a gap between the column items (although that didn't show up in the other screenshots above): https://github.com/flutter/flutter/issues/149689

**Comment by gaaclarke** [comment] 2024-06-04 22:41
Here's the frame capture for the render.  Aaaaaactually, jonah was right in that https://github.com/flutter/engine/pull/53130 would have effected this potentially (positively).  The top 2 shadows seem to be rendered with the gaussian blur, the middle one is using the rrect_blur.  So the slight fatness of the middle shadow is a discrepancy between those 2.  This also explains why the difference isn't as apparent after the change.  I would still like us to have more of a shadow on top of the widget.

[column3materials.gputrace.zip](https://github.com/user-attachments/files/15571137/column3materials.gputrace.zip)

**Comment by gaaclarke** [comment] 2024-06-05 17:33
I looked at this a bit and I'm going to consider it closed as a result of https://github.com/flutter/engine/pull/53130.  I think the results look good and the wonkiness seen in https://github.com/flutter/flutter/issues/149474#issuecomment-2148399150 doesn't show up anymore.  I'm also going to file an issue about the lack of any shadow at the top of the widget.  I worry that that the lack of the hairline shadow at the top could cause accessibility issues.

![yes-scale](https://github.com/flutter/flutter/assets/30870216/ceeeb9e7-1eaf-4878-bca2-bf58141f9710)

**Closed by gaaclarke** 2024-06-05 17:33 UTC
Labels: engine, has reproducible steps, P2, e: impeller, team-engine, triaged-engine, found in release: 3.22, found in release: 3.23

**Comment by gaaclarke** [comment] 2024-06-05 17:41
Issue filed for shadow at the top: https://github.com/flutter/flutter/issues/149757
