### ISSUE TITLE
Would like a Crashlytics plugin

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9592] opened 2017-04-25 22:57 UTC
Crashlytics is a good start.  Requested by @lukef

**Comment by sethladd** [comment] 2017-04-25 22:59
See also https://github.com/flutter/flutter/issues/614 and https://github.com/flutter/flutter/issues/4070

**Comment by sethladd** [comment] 2017-04-25 23:01
FWIW, another potential strategic partner has asked for Crashlytics.

**Comment by FaisalAbid** [comment] 2017-04-25 23:20
Is it currently possible right now to capture the stack trace when something crashes?

**Comment by eseidelGoogle** [comment] 2017-04-25 23:37
It's possible to capture a dart stack trace:
https://github.com/flutter/flutter/issues/614#issuecomment-292566271

**Comment by FaisalAbid** [comment] 2017-04-25 23:53
I wonder how Crashlytics/Firebase Crash reporiting will handle non ObjC/Java stack traces assuming they allow custom crash uploads.

We need this for Tunes app also, i'll experiment and report back

**Comment by FaisalAbid** [comment] 2017-04-27 19:11
Possible with FirebaseCrashReports if you do the following

Wrap up the crash from flutter in an Android Exception

```FirebaseCrash.report(new Exception(flutterCrashString));```

And that will be reported in the console

**Comment by lukef** [comment] 2017-06-01 20:58
Google is recommending to **NOT** use firebase for crash reporting on new projects anymore. I would suggest we close this issue.

**Comment by eseidelGoogle** [comment] 2017-06-01 21:05
https://firebase.google.com/docs/crash/

**Comment by eseidelGoogle** [comment] 2017-06-01 21:05
Actually, I think we can keep this open, it's just about providing crashlytics integration.

**Comment by sethladd** [comment] 2017-06-01 22:19
Updated the issue description :)

**Comment by eseidelGoogle** [comment] 2017-06-15 21:37
I believe @yjbanov is actively working on this.

**Comment by yjbanov** [comment] 2017-06-29 17:15
Unassigned for now because I'm not actively working on it. Still on the roadmap though.

**Comment by sethladd** [comment] 2017-11-15 01:32
A crash reporting option is here: https://pub.dartlang.org/packages/sentry

**Comment by Hixie** [comment] 2017-12-18 20:18
Closing as dupe of https://github.com/flutter/flutter/issues/614.

**Closed by Hixie** 2017-12-18 20:18 UTC
Labels: customer: posse (eap), plugin, plugin: first party

**Comment by dotdoom** [comment] 2018-02-09 20:09
Looks like #614 was closed without implementing Crashlytics support.
Moreover, it was suggested to make incremental enhancements.

@Hixie Do you think it's reasonable to reopen this now as an incremental enhancement to crash reporting?

**Comment by Hixie** [comment] 2018-02-13 06:11
Please don't hesitate to open a new bug. Probably best not to re-use this one since it has a confusing history and not much useful information.

**Comment by mit-mit** [comment] 2018-03-02 09:36
Thanks for opening #14765 -- for anyone interested in Crashlytics support, please cast a vote by pressing thumbs-up on the top-most comment in that new bug.

**Comment by AppleEducate** [comment] 2018-07-12 12:18
> on September 9th, 2018, Firebase Crash Reporting will be fully retired and you will no longer have access to that part of the console.

Since firebase crash reporting just announced they are retiring it in firebase in 60 days do we have an update for when crashlytics will be available for flutter?

**Comment by nokia6290** [comment] 2018-09-04 08:46
@AppleEducate I believe it means crashlytics will be default crash analytics for firebase Analytics.
