### ISSUE TITLE
Flutter State Restoration fails to restore navigation stack [Android]

### ISSUE THREAD

**Issue by drian0** [flutter/flutter#84193] opened 2021-06-08 14:40 UTC
The Android OS sometimes destroys an Activity due to situations like memory pressure. Flutter has a concept in place that allows restoring the application state after such an event. However, when the flutter framework performs state restoration it fails to restore the navigation stack. This means that after restoration the user will end up seeing a different widget. 

Assume you are building an app with a signup process consisting of six screens. If the activity is being destroyed while the user visits the sixth screen what happens is that the user will be suddenly reset to the first screen.

**Steps to reproduce**
1. Open developer options of your android device and enable *Don't keep activities*
2. Run the app from the example code below
3. The first screen is shown
4. Click on the button *show second screen*
5. The second screen is shown
6. Click on the button *create new Android activity*
7. Pick a random image from the gallery

**Expected**
- The second screen is shown

**Actual**
- The first screen is shown

**Code Sample**

```dart

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(RootRestorationScope(
      restorationId: 'root',
      child: MyApp()));
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: FirstScreen(),
    );
  }
}

class FirstScreen extends StatefulWidget {
  @override
  _FirstScreenState createState() => _FirstScreenState();
}

class _FirstScreenState extends State<FirstScreen> with RestorationMixin {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: Column(
      children: [
        Text("First Screen"),
        TextButton(
          child: Text("Show Second Screen"),
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute<void>(builder: (BuildContext context) {
              return SecondScreen();
            }));
          },
        )
      ],
    ));
  }

  @override
  String? get restorationId => 'firstscreen';

  @override
  void restoreState(RestorationBucket? oldBucket, bool initialRestore) {
  }
}

class SecondScreen extends StatefulWidget {
  @override
  _SecondScreenState createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> with RestorationMixin {
  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Text("Second Screen"),
      TextButton(
        child: Text("Launch new Android Activity"),
        onPressed: () async {
          ImagePicker picker = ImagePicker();
          await picker.getImage(source: ImageSource.gallery);
        },
      )
    ]);
  }

  @override
  String? get restorationId => 'secondscreen';

  @override
  void restoreState(RestorationBucket? oldBucket, bool initialRestore) {
  }
}

```

**Comment by TahaTesser** [comment] 2021-06-09 12:21
Hi @drian0 
This is probably duplicate of https://github.com/flutter/flutter/issues/59395
See   https://github.com/flutter/flutter/issues/59395#issuecomment-847787893 for more details

**Comment by drian0** [comment] 2021-06-10 04:26
Thank you for your reply. The issue #59395 is related but it is not a duplicate.

The scope of #59395 is the fact that on some devices the flutter activity restarts when picking an image. 
Please note that the issue has been closed because:

> I do not think there is any reasonable alternative to starting a new activity that would prevent the main activity from getting killed. This seems more of an issue with Android as a whole, where it is expected that your app will be able to restore itself in the case of this happening. As it does not seem to be specific to image_picker, nor to Flutter, I will be closing this issue.

In contrast, the scope of this issue here (#84193) is **not** to prevent the flutter activity from restarting but rather to handle the restart properly by restoring the state. The expectation is that after the restart the Navigation stack is restored i.e. the user sees the same screen as before the restart plus tapping "back" button leads to the previous screen, etc. Please see also [RestorationManager](https://api.flutter.dev/flutter/services/RestorationManager-class.html).

To clarify the impact: If you are implementing a signup process with a couple of screens in Flutter you can not use any component that will spawn a new Android activity such as image picker or image cropper. Doing so will cause some devices to restart the app and not recover properly - making it impossible for the affected users to sign up. In my estimation this is a critical issue and since there is no chance of changing Android's behavior it will be required to implement a solution within the domain of Flutter.

**Comment by TahaTesser** [comment] 2021-06-10 09:23
Hi @drian0 
Thanks for the details! 

### Steps and code sample

https://github.com/flutter/flutter/issues/84193#issue-915127113

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.295, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.3.0-17.0.pre.295 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f289aa19e7 (3 hours ago), 2021-06-10 02:29:02 -0400
    • Engine revision ad6c83164e
    • Dart version 2.14.0 (build 2.14.0-194.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19043.1052]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 91.0.4472.101
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 91.0.864.41

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.2.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1052]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by Zverik** [comment] 2022-03-25 06:44
I guess this issue is obsolete. You have to use `Navigator.restorablePush` for restoring a navigation tree. [This article](https://itnext.io/state-restoration-in-flutter-b6030b95a4d4) was a bt helpful for me, for the lack of good examples in the Flutter docs.

**Comment by goderbauer** [comment] 2022-04-20 22:06
The previous comment is correct. Closing this.

**Closed by goderbauer** 2022-04-20 22:06 UTC
Labels: platform-android, framework, has reproducible steps, found in release: 2.2, found in release: 2.3
