### ISSUE TITLE
[IOS] When iOS app is put to background/killed, WidgetBindingObserver should have 5 secs to run the process

### ISSUE THREAD

**Issue by SaintNicholas** [flutter/flutter#96779] opened 2022-01-18 16:59 UTC
On iOS, we have some things we are trying to do whenever the app is either backgrounded or force killed, and they can take several hundred milliseconds to complete. We are using `didChangeAppLifecycleState` callback of `WidgetsBindingObserver`, and we are finding that sometimes they complete, and sometimes they don't.

On iOS, the applicationDidEnterBackground (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground) and applicationWillTerminate (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate) functions both say:

```
applicationDidEnterBackground:

Your implementation of this method has approximately five seconds to perform any tasks and return. If the method doesn’t return before time runs out, your app is terminated and purged from memory.


applicationWillTerminate:

Your implementation of this method has approximately five seconds to perform any tasks and return. If the method does not return before time expires, the system may terminate the process altogether.
```

Because of this, we were hoping that we would have up to 5s to complete our actions, but that doesn't seem to be the case. It seems like iOS is saying that as soon as the application returns from the `applicationDidEnterBackground` and `applicationWillTerminate` callbacks, iOS will stop those applications from running, and it seems like flutter is returning immediately, so we do not get much time to complete our applications.

## Steps to Reproduce

To test this, I wrote an application that printed a log entry every millisecond once we got the callback that the application went into the paused state. That application is attached.

I first tested this with just putting the app into the background. I saw that we were running, on average, for around 200ms before iOS stopped our app from executing and the prints stopped. The 4 measurements I took were:
- 262ms in the paused state
- 178ms in the paused state
- 201ms in the paused state
- 200ms in the paused state

Then I tested this with force killing the app. The measurements I took were the following:
- Never got the callback saying the app went into the paused state.
- 12ms in the paused state
- 2ms in the paused state
- 2ms in the paused state
- Never got the callback saying the app went into the paused state.
- 6ms in the paused state

I'm not sure that this is a bug, but I expected the callback to be more reliable in the case that the app was force killed, and I was hoping we would get more time when the app was backgrounded?

Thanks!

[app_terminate_test.zip](https://github.com/flutter/flutter/files/7890961/app_terminate_test.zip)

**Comment by maheshmnj** [comment] 2022-01-19 10:27
Hi @SaintNicholas, Thanks for filing the issue, If I understand correctly when you put your app to background IOS roughly  stops app execution in around 200ms while in case of app termination the execution stops on average in 10ms, is that corect?

Can you please share How did you calculate  the time delta when the app was put to background to process stopped? from your code sample I see that the timer continuously logs to console even when the app is in background.
 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by SaintNicholas** [comment] 2022-01-19 15:17
I think you understand correctly. What I would do, exactly, is:

- Make a development release version of the app, so I could load it into my phone without the debugger connected.
- Load it only my phone.
- Watch the Xcode console when I run the app.
- Run and then force kill the app.

An example of what I see in the console is:

![image](https://user-images.githubusercontent.com/47845/150159646-0ea5b9e0-cd23-41de-893d-7102b56d72cd.png)

When I stop seeing the 'Paused' messages, I know that iOS shut down my app, because the timer that puts out the 'Paused' message is set to run forever. Based on the timestamps from the console logs, you can see that it only ran for a few milliseconds.

**Comment by maheshmnj** [comment] 2022-01-20 06:32
Thanks for the info @SaintNicholas. I am able to reproduce this same behavior. When the app is terminated forcefully the process stops immediately around  10-20 ms but incase of moving app to background the logs keep printing to console forever and the process never stops.

> Your implementation of this method has approximately five seconds to perform any tasks and return. If the method doesn’t return before time runs out, your app is terminated and purged from memory.

Also 5 seconds seems a very long time before the process is executed not sure if we are understanding this right. Leaving this issue open for further insights from the team.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.384, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.384 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a3fd36a115 (3 days ago), 2022-01-14 20:40:17 -0500
    • Engine revision 83d99a5809
    • Dart version 2.17.0 (build 2.17.0-16.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android
      11 (API 30)
    • iPhone 12 (mobile)     • A047BAB5-CBE0-4DAF-962E-01A35B593FB5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

 cc: @jmagman

**Comment by jmagman** [comment] 2022-01-20 18:49
It looks like the lifecycle state gets set to `AppLifecycleState.detached`, then the engine is destroyed, it doesn't wait for any life cycle delegates to finish work.
https://github.com/flutter/engine/blob/bdbd075d6233253f143bc844e981e90d82ae0d3c/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L818-L819

You could create a plugin that implements `applicationWillTerminate:` and `applicationDidEnterBackground:` and use the message channel to tell your dart code that the app is detaching.  I'm not sure if the app would wait to terminate until that's done though, since it's during a `UIApplicationWillTerminateNotification` observation? I'm more confident you'll get the result from `UIApplicationDidEnterBackgroundNotification`
https://github.com/flutter/engine/blob/57f7719e6eb3278508847d4e2e850125fc810032/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm#L217-L219

@gaaclarke any insights here?

**Comment by gaaclarke** [comment] 2022-01-20 22:07
Yea, so the 5 seconds it's referring to is performed synchronously with the main thread.  The way things work with Flutter apps is the lifecycle message is sent to Flutter asynchronously but the main thread (platform thread in engine parlance) doesn't wait for that notification to be handled.  In order to get that ~5s you'd need to block the main thread.

You could do what @jmagman is suggesting, create a plugin that subscribes to the notification for `applicationDidEnterBackground` and block execution in your handler until you get a message from Flutter that your operation has completed.

Alternatively, you could start officially [executing in the background](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio?language=objc).  Depending on what you are trying to do with that 5 seconds of time I might try to dissuade you from even thinking it would be a good idea.

**Comment by chinmaygarde** [comment] 2022-01-24 19:23
Closing based on guidance on a workaround.

**Closed by chinmaygarde** 2022-01-24 19:23 UTC
Labels: platform-ios, engine, has reproducible steps, found in release: 2.8, found in release: 2.9
