### ISSUE TITLE
Cursor bug in TextField. Cursor sticks and gets into the selection mode

### ISSUE THREAD

**Issue by inevitabile** [flutter/flutter#105185] opened 2022-06-02 01:41 UTC
## Steps to Reproduce

1. Run any app with a TextField

2. Tap on any of these keys
![Screenshot_151](https://user-images.githubusercontent.com/8906519/171528748-9313a67c-ac22-4346-8a98-5dec21b946e9.png)

3. Tap inside the field trying to change the cursor position

4. The cursor sticks and enters in selection mode (it's not exactly the selection mode but looks like it). You fall into a trap. Typing, closing the keyboard, setting the focus on another TextField - nothing helps. The cursor is still stuck.

https://user-images.githubusercontent.com/8906519/171528345-271c7ff9-b674-47d5-9ff7-b46f9a05e187.mp4

5. You can get out of it only by tapping on Backspace or Shift.
![Screenshot_152](https://user-images.githubusercontent.com/8906519/171528699-bd2e2793-a69a-4fc7-a75b-e6b65629c480.png)

*I have tested only on Samsung Galaxy S7 Edge (SM G935FD). I'm not sure whether we have the problem on other devices.

<details>
<summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Hello',
      debugShowCheckedModeBanner: false,
      home: MainScreen(),
    );
  }
}


class MainScreen extends StatefulWidget {
  const MainScreen({Key? key}) : super(key: key);

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  TextEditingController? _textController;

  @override
  void initState() {
    _textController = TextEditingController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Hello world'),
      ),
      body: Padding(
        padding: const EdgeInsets.only(top:20, left:30, right: 30),
        child: TextField(
          controller: _textController,
        ),
      ),
    );
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  RendererBinding.instance.setSemanticsEnabled(true);
  runApp(const MyApp());
}


```
</details>

By the way, I've tried with the TextFormField widget, I've tried to manipulate controller properties, even Flutter's older versions. It's the same.

<details>
<summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale ru-RU)
    • Flutter version 3.0.1 at C:\flutter\flutter_windows_2.8.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (13 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Futuro\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • SM G935F (mobile) • ad06170246004eb408 • android-arm64  • Android 8.0.0 (API 26)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

**Comment by maheshmnj** [comment] 2022-06-02 10:47
Hi @inevitabile, I tried to reproduce this issue on Xiaomi k20 Pro (Android 11) and I was not able to reproduce this issue.
Can you please check if inserting exclamation mark (!) at the end gives same result or not?
Looks similar to #98720

**Comment by inevitabile** [comment] 2022-06-02 11:55
Hi @maheshmnj, thank you for your reply.

No, the exclamation mark itself doesn't cause the problem. I typed it from the symbol toolbar and it's OK (as you can see in the video).
I have this bug only when I switch the keyboard by this key (no matter whether I type any symbol after or not):

![Screenshot_147](https://user-images.githubusercontent.com/8906519/171621792-a5c0131d-4c0c-4dbc-a2a8-5302e15aec7d.png)

and when I tap on this key (no matter what symbol it types: comma, question mark, or whatever)
![Screenshot_150](https://user-images.githubusercontent.com/8906519/171622311-eb7789c9-ad33-40d1-bd39-54141eead2d6.png)

BUT the result is the same as here https://github.com/flutter/flutter/issues/98720


https://user-images.githubusercontent.com/8906519/171619963-aab4d602-7357-478e-8585-438420bc77c4.mp4


By the way, I can't reproduce it on Samsung Galaxy A51.

**Comment by maheshmnj** [comment] 2022-06-02 13:25
> No, the exclamation mark itself doesn't cause the problem.

Thanks for the update @inevitabile,  This issue is same as #98720 as pointed above.

Closing as duplicate of the linked issue

**Closed by maheshmnj** 2022-06-02 13:25 UTC
Labels: in triage
