### ISSUE TITLE
Very misleading error message when you drastically change the starter project and then hot reload

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10684] opened 2017-06-14 03:05 UTC
Try this:

* create a new app
* start an emulator
* flutter run your new app
* yay, it works!
* then, replace your lib/main.dart with the following contents:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyWidget());
}

class MyWidget extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return new GestureDetector(
      onTap: () => print('tapped!')
    );
  }
}
```

And then:

* type `r` in your flutter run console

Expected: hot reloads and everything is awesome

Actual:

This error:

```
Initializing hot reload...
I/flutter ( 3394): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3394): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter ( 3394): 'file:///C:/Users/sethladd/Documents/Code/circles/lib/main.dart': malformed type: line 25: cannot
I/flutter ( 3394): resolve class 'MyHomePage' from 'MyApp'
I/flutter ( 3394):         home : new MyHomePage(title : "Flutter Demo Home Page"),
I/flutter ( 3394):                    ^
I/flutter ( 3394):
```

This is a pretty poor user experience:

* There is no more MyHomePage class in my source code, why is Flutter telling me there's an error here?
* There is no suggestion or hint that I need to Hot Restart

Luckily, I then remembered that:

* I can Hot Restart
* There is some issue about changing types of widgets and not working well with Hot Reload

(Neither of which a new user would understand :/)

Suggestions:

* Tolerate changing widget types (from stateless to stateful) during Hot Reloads
* Detect when a Hot Reload isn't possible, error out earlier than showing me code that no longer exists
* Suggest to the user something like "Bummer, that didn't seem to work. Please try Hot Restart with capital R."

Thanks!

**Comment by Hixie** [comment] 2017-06-14 19:51
What is happening is this:

- We don't rerun the `void main()` block. That's basically what it means to do a hot reload: we don't rerun the app from the start, we just update the code in place and keep going. Your app has already run its void main, so it won't rerun.

- We then mark every object in the system as needing to be rebuilt. In your app, you had a MyApp widget, so we rebuild it. Its build function used to try to instantiate a MyHomePage class. But that class doesn't exist anymore, so when we try to do that we fail.

No widgets are changing types.
The hot reload is possible, and worked fine. It's actually the rebuild that failed. You would get the same failure if you started your app with a MyApp class that tried to build a non-existent MyHomePage class.

We could detect that an error occurred during the hot reload's reassemble step, though, and tell the tool that things went poorly... How could we distinguish that from a typo in your code, though? Like, if all you had done was edit the MyApp builder to build a MyHomeBook instead of a MyHomePage, you'd get the exact same error, and we'd have no way to distinguish that error from the error you got here.

If the VM could report to us the list of classes that changed, and whether they were removed or had their class hierarchies changed, we could specifically rebuild just the widgets that changed, and we could complain if a class that previously was in the tree no longer existed.

**Comment by sethladd** [comment] 2017-06-14 21:09
Thanks for the analysis!

> The hot reload is possible, and worked fine

From the user's perspective, it didn't work fine. I pressed 'r' and I didn't see my change. I got an error about code that no longer existed :(

> We could detect that an error occurred during the hot reload's reassemble step, though, and tell the tool that things went poorly

Yes, please! That should cover a variety of cases, and we'll make it super clear: the action that the user requested did not complete, don't worry, just hit big R.

An overall point here is: it's not clear *why* hot reload failed, and it wasn't clear *what* to do next. That's really the bug.

As a user, I'm fine hitting big R as my escape hatch. Just tell me to do that in the error message. :)

cc @mit-mit

**Comment by Hixie** [comment] 2017-06-14 21:23
> Yes, please!

You missed the next two sentences which explain why that's not actually possible. :-) If we said "use R" anytime there was any error in hot reload, we'd be telling you to use "R" all the time even though most of the time using "R" will just give you the same error.

**Comment by sethladd** [comment] 2017-06-14 21:28
Sorry, I did miss it. However, I'm still not satisfied with this user experience :/

Remember, I hit _little r_ a few times and kept getting the same error. I was out of ideas. I was about to just quit the _flutter run_ session (Control-C) and relaunch. That's a valid workaround, but I think we can do better.

I solved this because I _a priori_ knew about Big R. I'm wondering what we can do to make it so that you don't need _a priori_ knowledge ?

**Comment by Hixie** [comment] 2017-06-14 22:14
The flutter tool announces it in the same sentence as hot reload:
```
🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
```

The ideal solution here is getting the VM to report the information as described above.

**Comment by sethladd** [comment] 2017-06-14 22:16
cc @a-siva @mit-mit 

@Hixie is referring to this text:

"If the VM could report to us the list of classes that changed, and whether they were removed or had their class hierarchies changed, we could specifically rebuild just the widgets that changed, and we could complain if a class that previously was in the tree no longer existed."

**Comment by lukechurch** [comment] 2017-06-14 22:28
cc @lukechurch

**Comment by a-siva** [comment] 2017-06-15 00:14
@rmacnak-google

**Comment by rmacnak-google** [comment] 2017-06-15 01:29
Removing a (non-root) widget class and all its uses in build methods would be a valid change. Hot reload should not complain here just because the old tree has a deleted class.

The VM knows that this compilation error happened in stale code (the deleted MyApp class), which is probably a good signal that restart may help. The typo scenario would usually cause an error in the current version of some code.

This change included `main`, which will not be run again. This special case probably deserves a warning of some kind, but we can't in general know if a change requires a restart to have an effect.

**Comment by mit-mit** [comment] 2017-06-15 13:06
> The VM knows that this compilation error happened in stale code (the deleted MyApp class), which is probably a good signal that restart may help

Yes, if we could know when to restart even if reload was requested that would be great. And if not, if we could at least know that something is going to fail and throw an exception, can we change the error message to say something that a little more explicitly?

**Comment by sethladd** [comment] 2017-06-15 15:24
> The VM knows that this compilation error happened in stale code (the deleted MyApp class), which is probably a good signal that restart may help.

Great!

**Comment by a-siva** [comment] 2017-09-28 16:43
Marking as a duplicate of #12300

**Closed by a-siva** 2017-09-28 16:43 UTC
Labels: dependency: dart, dev: tool - reload
