### ISSUE TITLE
Video player shows black screen on iOS while playing it in repeat mode

### ISSUE THREAD

**Issue by ITyongzhen** [flutter/flutter#73311] opened 2021-01-05 10:46 UTC
this is my code

```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

class RoomBgImage extends StatefulWidget {
  final String url;
  final double width;
  final double height;

  const RoomBgImage({Key key, @required this.url, this.width, this.height})
      : super(key: key);

  @override
  _RoomBgImageState createState() => _RoomBgImageState();
}

class _RoomBgImageState extends State<RoomBgImage> {
  VideoPlayerController _bgVideoPlayController;
  Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    _initFuture();
    print('roombgimage init');
    super.initState();
  }

  @override
  void dispose() {
    if (_bgVideoPlayController != null) {
      _bgVideoPlayController.dispose();
    }
    print('eagle.roombgimage dispose');
    super.dispose();
  }

  _initFuture() {
    print('widget._initFuture = ${widget.url}');
    _bgVideoPlayController = VideoPlayerController.network(widget.url);
    _bgVideoPlayController.setLooping(true);
    _bgVideoPlayController.setVolume(0);
    _initializeVideoPlayerFuture = _bgVideoPlayController.initialize();

  }

  @override
  void didUpdateWidget(RoomBgImage oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.url != widget.url) {
      _initFuture();
    }
  }

  @override
  Widget build(BuildContext context) {
    if (widget.url == null) return Container();
    return _buildMP4bg(widget.url, widget.width, widget.height);
  }

  void startVideo() async {
    if (_bgVideoPlayController != null &&
        _bgVideoPlayController.value != null) {
      await _bgVideoPlayController.play();
      await _bgVideoPlayController.setVolume(0);
    }
  }

  bool _videoInitial = false;

  Widget _buildAutoVideo(String url, double width, double height) {
    if (_initializeVideoPlayerFuture == null) {
      return Container(
        width: width,
        height: height,
        color: Colors.blue,
      );
    }


    return SizedBox(
      width: width,
      height: height,
      child: FutureBuilder(
        future: _initializeVideoPlayerFuture,
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot != null &&
              snapshot.connectionState == ConnectionState.done &&
              _bgVideoPlayController.value != null) {
            _videoInitial = true;
            Size vSize = _bgVideoPlayController.value.size;
            print('vSize = $vSize');
            if (vSize != null) {
              startVideo();
            }
            return AspectRatio(
              key: Key(widget.url),
              aspectRatio: width / height,
              child: VideoPlayer(_bgVideoPlayController),
            );
          } else {
            return Container(
              height: width,
              alignment: Alignment.center,
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
    );
  }

  Widget _buildMP4bg(String url, double width, double height) {
    return _buildAutoVideo(url, width, height);
  }
}

```

When I use:

```
RoomBgImage(url: 'https://xs-image.oss-cn-hangzhou.aliyuncs.com/mp4/cx/2.mp4',width: 200,height: 200,),
```

https://user-images.githubusercontent.com/23075407/103637210-174bfd00-4f86-11eb-9ebb-cf394b218d6b.MOV

[code.zip](https://github.com/flutter/flutter/files/5769687/code.zip)

The black screen video is attached

**Comment by darshankawar** [comment] 2021-01-05 12:01
@ITyongzhen 
The video you shared isn't loading for me, can you provide a sample video file that we can use to verify this ?
Thanks.

**Comment by ITyongzhen** [comment] 2021-01-05 13:03
OK, I uploaded it again。

[video.zip](https://github.com/flutter/flutter/files/5770266/video.zip)

**Comment by ITyongzhen** [comment] 2021-01-06 01:08
> @ITyongzhen
> The video you shared isn't loading for me, can you provide a sample video file that we can use to verify this ?
> Thanks.

@darshankawar I tested two phones, an iPhone 6S and an iPhone 11, both of which had the same problem.

[video.zip](https://github.com/flutter/flutter/files/5773351/video.zip)

**Comment by darshankawar** [comment] 2021-01-06 06:13
@ITyongzhen 
Can you provide `flutter doctor -v` ?

**Comment by ITyongzhen** [comment] 2021-01-07 01:13
@darshankawar 

Can you reproduce it？

this is my `flutter doctor -v`

Last login: Mon Jan  4 18:23:39 on ttys006
➜  ~ flutter doctor -v
[✓] Flutter (Channel unknown, 1.22.2, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.22.2 at /Applications/flutter
    • Framework revision 84f3d28555 (3 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/eagle/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.beta.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,LOCALHOST
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • eagle6s (mobile)  • 81cf48d92c32c08a29fd510edfd348b88ab86571 • ios • iOS
      13.6
    • iPhone 8 (mobile) • BFEF94E6-590D-4238-83E6-3749E34915DA     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
➜  ~

**Comment by darshankawar** [comment] 2021-01-07 05:57
@ITyongzhen 
Your code sample requires video to be an url, but the one you provided is a standalone video it seems.
Can you update the code sample to have latest video url so that we can use it directly and verify ?

**Comment by ITyongzhen** [comment] 2021-01-07 06:36
@darshankawar  Didn't you say that you can't access the URL I provided? You can convert this one second video into a video that you can access. This is a necessary problem

**Comment by darshankawar** [comment] 2021-01-07 10:50
@ITyongzhen 
Per your code sample, we need to pass the video url as:

`RoomBgImage(url: 'https://xs-image.oss-cn-hangzhou.aliyuncs.com/mp4/cx/2.mp4',width: 200,height: 200,),`

But the one video you sent is a stand-alone video which I tried to import in assets and run, but it didn't work, hence we requested you to update the code sample to have latest video url. Hope it's clear.

**Comment by ITyongzhen** [comment] 2021-01-08 01:52
@darshankawar  Sorry, I can't provide a URL you can access. I can only provide the website address of Alibaba cloud. In addition, the video material has been given to you. I think if you pay attention to this problem, you can easily convert it into a website you can visit

**Comment by darshankawar** [comment] 2021-01-11 06:33
Issue reproducible on latest master on iOS.


https://user-images.githubusercontent.com/67046386/104152204-e09e3880-5404-11eb-9c34-017a44f804a3.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.275 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

</details>

**Comment by nt4f04uNd** [comment] 2021-01-15 01:39
@darshankawar isn't this a duplicate of https://github.com/flutter/flutter/issues/73311

**Comment by nt4f04uNd** [comment] 2021-01-15 04:17
@darshankawar oh, i meant https://github.com/flutter/flutter/issues/41156

**Comment by darshankawar** [comment] 2021-01-15 06:06
Thanks for the tip @nt4f04uNd.
Closing this as duplicate in favor of https://github.com/flutter/flutter/issues/41156

**Closed by darshankawar** 2021-01-15 06:06 UTC
Labels: found in release: 1.26, has reproducible steps, p: first party, p: video_player, platform-ios, plugin

**Comment by ITyongzhen** [comment] 2021-01-20 09:07
[41156](https://github.com/flutter/flutter/issues/41156)  It seems that the issue has not solved this problem for two years. Seekto mentioned in the comments is useless @darshankawar
