### ISSUE TITLE
Keyboard-based text field editing stops working intermittently on macOS

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#50650] opened 2020-02-12 18:19 UTC
Both @csells and I saw an instance where a multi-line text field (I was using the one in the Gallery app's Material Text fields demo) stopped responding to some keyboard editing commands.

Both the up/down arrows and the command-A/command-C commands don't work. The left/right arrows did still work.

I had it happen once, and thereafter when I launched the app, I couldn't make it happen again.

I tried holding down keys when I started the app, running in debugger, debug mode, and release mode, and after the one time (which was in debug mode, but not in a debugger) I couldn't get it to happen again.

Chris says he couldn't get it NOT to happen for his app.

**Comment by gspencergoog** [comment] 2020-02-12 23:40
Stuart pointed out that the embedding implements left/right arrow editing, but not the rest, so probably this is a "stuck key" problem where the embedding is still working because it doesn't track pressed keys and the framework does. I'll test that theory out shortly.

**Comment by shaomaicheng** [comment] 2020-02-16 07:36
i have this problem too, i can not use cammand+A and  direction key to select my input in TextField when i use mac desktop

**Comment by shaomaicheng** [comment] 2020-02-16 07:37
Is this a bug,? or do we need to add logic ourselves, which is unreasonable

**Comment by shaomaicheng** [comment] 2020-02-16 08:29
i think TextField may don't  handle keybroad event ....

**Comment by shaomaicheng** [comment] 2020-02-17 02:30
i find it...in editable.dart, it add a keyboard listener:   _handleKeyEvent
it only handle command+ x,a,v,x

**Comment by technolion** [comment] 2020-04-02 07:56
Keyboard-based text field seems to work just fine on Flutter 1.16.4-pre.69 • channel master.

**Comment by stuartmorgan** [comment] 2020-06-04 19:24
> Is this a bug,?

Yes.

**Comment by stuartmorgan** [comment] 2020-06-12 03:50
Closing as a duplicate of https://github.com/flutter/flutter/issues/50553 since the underlying issue is stuck keys.

**Closed by stuartmorgan** 2020-06-12 03:50 UTC
Labels: P4, a: desktop, platform-mac
