### ISSUE TITLE
reroute to same statefulWidget (back and reenter), bug appear

### ISSUE THREAD

**Issue by zkcode** [flutter/flutter#21597] opened 2018-09-08 15:08 UTC
**Flutter environment:**
```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (1 available)
```

**Coding context:**
calling steps: home widget -> drawer item (routing) -> ONE Widget : successful for the first time.
then back to home widget-> repeat above steps -> bug as follow

**Bug information:**
```
I/flutter ( 5796): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5796): The following assertion was thrown building Builder:
I/flutter ( 5796): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3736 pos 12: '_state._widget ==
I/flutter ( 5796): null': is not true.
I/flutter ( 5796):
I/flutter ( 5796): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5796): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5796): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5796):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5796):
I/flutter ( 5796): When the exception was thrown, this was the stack:
I/flutter ( 5796): #2      new StatefulElement (package:flutter/src/widgets/framework.dart:3736:12)
I/flutter ( 5796): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:789:42)
I/flutter ( 5796): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2917:40)
I/flutter ( 5796): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 5796): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 5796): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 5796): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 5796): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 5796): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 5796): #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 5796): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 5796): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 5796): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 5796): #95     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4449:32)
I/flutter ( 5796): #96     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 5796): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #98     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 5796): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 5796): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #106    ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 5796): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 5796): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #112    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 5796): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 5796): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 5796): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 5796): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 5796): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 5796): #120    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 5796): #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 5796): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5796): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5796): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5796): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5796): #126    _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 5796): #127    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 5796): (elided 2 frames from class _AssertionError)
I/flutter ( 5796): ═════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment] 2018-09-08 16:17
Is it possible that you have a widget where `createState()` returns `null`?

Can you provide a running minimal reproduction?

**Comment by zkcode** [comment] 2018-09-09 08:33
the widget calling relationship as follow:
1. parent widget contains a list of child cards
2. when any internal child card change state, besides the child card rebuild with setState(), the parent widget will refresh the screen also.
3. so I declared an global parent widget state instance which will be created in corresponding parent StatefulWidget with createState()
4. then the child card State Widget will call parent widget setState() to refresh building
5. the first time, such building logic is fine, then the bug apear

btw, I have use another way to implement such requirement,  maybe this case can be closed, thanks a lot.

**Comment by zoechi** [comment] 2018-09-10 13:43
Can you please provide the code for a minimal reproduction (`main.dart`)?

**Comment by juanjoserodrigolazaro** [comment] 2018-09-12 21:52
same problem! any solutions?

**Comment by zoechi** [comment] 2018-09-13 05:40
@juanjoserodrigolazaro first we need to figure out what the problem is. 
Solutions comes afterwards.

Perhaps you can help with a minimal reproduction?

**Comment by juanjoserodrigolazaro** [comment] 2018-09-13 13:43
yes no problem, but i insist that its a little bit conceptual because the only thing im doing is using facebook login and shared preferences for saving session.

first calling login function:

Future<Null> _login() async {
    final FacebookLoginResult result =
    await facebookSignIn.logInWithReadPermissions(['email','public_profile']);

    switch (result.status) {
      case FacebookLoginStatus.loggedIn:
        accessToken = result.accessToken;



        var graphResponse = await http.get(
            'https://graph.facebook.com/v2.12/me?fields=name,first_name,last_name,email&access_token=${accessToken.token}');
        var profile = json.decode(graphResponse.body);

        //
        var ppic = "https://graph.facebook.com/"+profile['id']+"/picture?width=250&height=250";
        print(profile);
        print(profile['name']);
        print(profile['email']);
        print(ppic);

        saveSession(profile['name'], profile['email'], ppic);


        checkSession();








        break;
      case FacebookLoginStatus.cancelledByUser:
      //_showMessage('Login cancelled by the user.');
        break;
      case FacebookLoginStatus.error:
      //_showMessage('Something went wrong with the login process.\n'
      //  'Here\'s the error Facebook gave us: ${result.errorMessage}');
        print(result.errorMessage);
        break;
    }
  }



second:

saving session whith shared preferences (ok)



third checking session: 

Future go() {
    return new Future.delayed(const Duration(seconds: 1), () => Navigator.push(context, MaterialPageRoute(builder: (context) => Loged())));
  }

 Future<String> checkSession() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String name = prefs.getString("nombreFb");

    setState(() {
      if (name == null || name == "") {

      } else {

    
        go();

      }
    });

    return "success";
  }



Everything ok for the first time, then in loged page i have a drawer with listtitles in which 1 is logout, in which i logout from facebook (ok), then go back (i dont know wich one is the correct type of navigation, i think Navigator.of(context).pushNamedAndRemoveUntil('/home', (Route<dynamic> route) => false);
i have test with all this types https://medium.com/flutter-community/flutter-push-pop-push-1bb718b13c31


after that when i loged in again it give me the error of the state == null is not true .

**Comment by zoechi** [comment] 2018-09-13 14:20
Can you please provide a complete running minimal example in one file (`main.dart`)

**Comment by juanjoserodrigolazaro** [comment] 2018-09-13 14:30
cant give you all of my main dart.. it wouldnt work with just a minimal example, thank you for trying to help! maybe you could help me giving me and example of how i can route which method i have to make.

**Comment by zoechi** [comment] 2018-09-13 14:41
I don't want all of your main. 
I need the minimal amount of code that allows to reproduce.

If I try to create a working example that I can run and debug, I have to make tons of assumptions about how you might have built your app which probably leads to different behavior and then we can go on and on why my example behaves different from yours.

**Comment by juanjoserodrigolazaro** [comment] 2018-09-13 20:45
```
void main() {
  runApp(MaterialApp(
    title: 'CarWash',
    debugShowCheckedModeBanner: false,
    home: MyApp(),
    routes: <String, WidgetBuilder> {
      '/home': (BuildContext context) => new MyApp(),
      '/log': (BuildContext context) => new Loged(),
      '/config': (BuildContext context) => new Config(),
    },
  ));
}




class MyApp extends StatefulWidget {



  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static final FacebookLogin facebookSignIn = new FacebookLogin();
  Future go() {
    return new Future.delayed(const Duration(seconds: 1), () => Navigator.of(context).pushNamedAndRemoveUntil('/log', (Route<dynamic> route) => true));
  }



   saveSession(String name, String mail, String picture) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("nombreFb", name);
    prefs.setString("mailFb", mail);
    prefs.setString("pictureFb", picture);

  }

  Future<String> checkSession() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String name = prefs.getString("nombreFb");

    setState(() {
      if (name == null || name == "") {

      } else {

        //Navigator.of(context).pushNamedAndRemoveUntil('/log', ModalRoute.withName('/home'));
        //N
        //go();


          Navigator.push(context, MaterialPageRoute(builder: (context) => Loged()));


      }
    });

    return "success";
  }


  FacebookAccessToken accessToken;

  Future<Null> _login() async {
    final FacebookLoginResult result =
    await facebookSignIn.logInWithReadPermissions(['email','public_profile']);

    switch (result.status) {
      case FacebookLoginStatus.loggedIn:
        accessToken = result.accessToken;



        var graphResponse = await http.get(
            'https://graph.facebook.com/v2.12/me?fields=name,first_name,last_name,email&access_token=${accessToken.token}');
        var profile = json.decode(graphResponse.body);

        //
        var ppic = "https://graph.facebook.com/"+profile['id']+"/picture?width=250&height=250";
        print(profile);
        print(profile['name']);
        print(profile['email']);
        print(ppic);

        saveSession(profile['name'], profile['email'], ppic);


        checkSession();








        break;
      case FacebookLoginStatus.cancelledByUser:
      //_showMessage('Login cancelled by the user.');
        break;
      case FacebookLoginStatus.error:
      //_showMessage('Something went wrong with the login process.\n'
      //  'Here\'s the error Facebook gave us: ${result.errorMessage}');
        print(result.errorMessage);
        break;
    }
  }

  void entrar() {
    _login();
  }

  @override
  void initState() {
    checkSession();
    super.initState();
  }



  @override
  Widget build(BuildContext context) {


    return  new WillPopScope(
        onWillPop: () async {
      return true;
    },
    child: new MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Scaffold(
      resizeToAvoidBottomPadding: false,


      body: new Container(


        color: Colors.white,

    child: new Stack(
        children: <Widget>[
          new Align(
              alignment: Alignment.topCenter,
              child: new Column(
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  new Container(
                    margin: const EdgeInsets.only(top: 70.0),
                    height: 150.0,
                    child: Image.asset("images/washit.png"),
                  ),
                  new Container(
                    margin: const EdgeInsets.only(top: 26.0),
                    height: 150.0,
                    child: Image.asset("images/pinjump.gif"),
                  )
                ],
              )
          ),
          new Align(
            alignment: Alignment.center,
            child: new Container(
              margin: const EdgeInsets.only(right: 16.0, left: 16.0),
              child: new Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[

                ],
              ),
            ),
          ),
          new Align(
            alignment: Alignment.bottomCenter,
            child: new Container(
              height: 110.0,
              margin: const EdgeInsets.only(left: 16.0, right: 16.0, bottom: 40.0),
              width: double.infinity,
              child: new Column(
                children: <Widget>[
                  new Container(
                    width: double.infinity,
                    child: new RaisedButton(
                        onPressed: () {
                          entrar();
                        },
                        shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(30.0)),
                        color: Theme.of(context).accentColor,
                        child: new Row(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          mainAxisAlignment: MainAxisAlignment.center,
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[

                            Container(
                              margin: const EdgeInsets.only(right: 15.0),
                              child: Text("Iniciar Sesion",
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 19.0,
                                  fontFamily: "Roboto",
                                  fontWeight: FontWeight.bold,
                                ),

                              ),
                            ),
                            Icon(FontAwesomeIcons.facebook, color: Colors.white,)
                          ],
                        )
                    ),
                  ),

                  new Container(
                    width: double.infinity,
                    child: new RaisedButton(
                        onPressed: () {
                          Navigator.push(context, MaterialPageRoute(builder: (context) => Login2()));
                        },
                        shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(30.0)),
                        color: Colors.transparent,
                        child: new Row(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          mainAxisAlignment: MainAxisAlignment.center,
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[

                            Container(
                              margin: const EdgeInsets.only(right: 15.0),
                              child: Text("Acceso washers",
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 19.0,
                                  fontFamily: "Roboto",
                                  fontWeight: FontWeight.bold,
                                ),

                              ),
                            ),
                            Icon(FontAwesomeIcons.tint, color: Colors.white,)
                          ],
                        )
                    ),
                  )



                ],
              )
            ),
          )
        ],
      ),

    ),
    )
    )
    );
  }
}




LogedState log = new LogedState();



class Loged extends StatefulWidget {

  Loged({Key key}) : super(key: key);

  @override
  LogedState createState() =>  log;
}

class LogedState extends State<Loged> {



  static final FacebookLogin facebookSignIn = new FacebookLogin();

   saveSession(String name, String mail, String picture) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString("nombreFb", name);
    prefs.setString("mailFb", mail);
    prefs.setString("pictureFb", picture);

  


  }



  Future<Null> _logOut2() async {
    await facebookSignIn.logOut();

    setState(() {

      saveSession("", "", "");
   
  
      Navigator.of(context).pushNamedAndRemoveUntil('/home', (Route<dynamic> route) => false);

    });


  }

  var nombre = "";
  var mail = "";
  var picture = "http://bestvoyage.in/wp-content/uploads/profile.png";

  Future<String> getData() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    setState(() {
      nombre = prefs.getString("nombreFb");
      mail = prefs.getString("mailFb");
      maiil = mail;
      picture = prefs.getString("pictureFb");
    });


    return "success";
  }











  @override
  void initState() {
    mapController = new MapController();
    getData();
    getLocation();

    super.initState();
  }

  Mode _mode = Mode.overlay;


  Future<Null> centerMap(double lattt, double longgg) async {

    setState(() {
      lattt = -33.32;
      longgg = -70.514;

      mapController.center.latitude =  lattt;
      mapController.center.longitude = longgg;
      print("centro");
    });

  }


 



  @override
  Widget build(BuildContext context) {
    return new WillPopScope(
      onWillPop: () async {
        return true;
      },
      child: new MaterialApp(
        debugShowCheckedModeBanner: false,
        home: new Scaffold(
            key: homeScaffoldKey,
            appBar: AppBar(
              centerTitle: true,
            title: Text("Ingresar direccion",
              style: TextStyle(
                color: Colors.white
              ),
            ),
            actions: <Widget>[
         
              
              IconButton(
                icon: Icon(Icons.send),
                onPressed: ()  {
                  },
              )
            ],
            elevation: 5.0,
            backgroundColor: Theme.of(context).accentColor,
          ),
          drawer: new Drawer(
            child: new Container(
              color: Theme.of(context).accentColor,
              child: new ListView(
                children: <Widget>[
                  new UserAccountsDrawerHeader(
                    accountName: new Text(nombre),
                    accountEmail: new Text(mail),
                    currentAccountPicture: new CircleAvatar(
                      backgroundColor: Theme.of(context).accentColor,
                      child: new ClipOval(child: Image.network(picture)),
                    ),
                  ),

                  /*
                  new ListTile(
                    title: new Text("Solicitar servicio",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.normal,
                          fontFamily: "Roboto",
                          fontSize: 18.0
                      ),
                    ),
                    trailing: new Icon(FontAwesomeIcons.user, color: Colors.white,),
                    onTap: () {
                      Navigator.pop(context, true);
                    },
                  ),

                  */
                  new ListTile(
                    title: new Text("Mis pedidos",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.normal,
                          fontFamily: "Roboto",
                          fontSize: 18.0
                      ),
                    ),
                    trailing: new Icon(FontAwesomeIcons.shoppingBasket, color: Colors.white,),
                    onTap: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context) => MisPedidos()));
                    },
                  ),
                  new ListTile(
                    title: new Text("Precios",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.normal,
                          fontFamily: "Roboto",
                          fontSize: 18.0
                      ),
                    ),
                    trailing: new Icon(FontAwesomeIcons.dollarSign, color: Colors.white,),
                  ),

                  new ListTile(
                    title: new Text("Contacto",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.normal,
                          fontFamily: "Roboto",
                          fontSize: 18.0
                      ),
                    ),
                    trailing: new Icon(FontAwesomeIcons.phone, color: Colors.white,),
                    onTap: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context) => Contacto()));
                    },
                  ),
                  new Divider(color: Colors.white,),
                  new ListTile(
                    title: new Text("Cerrar sesion",
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.normal,
                        fontFamily: "Roboto",
                        fontSize: 18.0
                      ),
                    ),
                    trailing: new Icon(FontAwesomeIcons.timesCircle, color: Colors.white,),
                    onTap: () {
                      _logOut2();




                    },
                  )
                ],
              ),
            ),
          ),
          body:  new FlutterMap(
            mapController: mapController,
        options: new MapOptions(
        center: new LatLng(latt, longg),
        zoom: 17.0,
      ),
      layers: [
        new TileLayerOptions(
          urlTemplate: "https://api.tiles.mapbox.com/v4/"
              "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
          additionalOptions: {
            'accessToken': 'pk.eyJ1IjoianVhbmpvc2Vyb2RyaWdvbGF6YXJvIiwiYSI6ImNqbHEwcTlpbzJhdmYza2ttY2M0azUwZHYifQ.WhH3a7lVehmc3F0Jb8QrHA',
            'id': 'mapbox.streets',
          },
        ),
        new MarkerLayerOptions(
          markers: [
            new Marker(
              width: 60.0,
              height: 60.0,
              point: new LatLng(latt, longg),
              builder: (ctx) =>
              new Container(
                child:  new ClipRRect(
                  borderRadius: new BorderRadius.circular(40.0),
                  child: Image.network(picture,
                    height: 60.0,
                    width: 60.0,
                  ),
                ),
              ),
            ),
          ],
        ),
      ],
    ),
          floatingActionButton: Container(
            margin: const EdgeInsets.only(bottom: 25.0, right: 10.0),
            child: new FloatingActionButton(onPressed: getLocation, child: Icon(Icons.location_on),),
          )

        ),
      ),

    );
  }


}
```

**Comment by juanjoserodrigolazaro** [comment] 2018-09-17 16:14
@zoechi any update on this?

**Comment by zoechi** [comment] 2019-01-17 07:56
Duplicate of #11975

**Closed by zoechi** 2019-01-17 07:56 UTC
Labels: f: routes, framework, severe: crash
