### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by seifalmotaz** [flutter/flutter#115249] opened 2022-11-13 22:15 UTC
There is a wired error I have in flutter windows app.
When I press shift, ctrl or any key for long time like 1 or 2 seconds even when I press shift to capitalize character sometimes.

![image](https://user-images.githubusercontent.com/91150254/201546220-3087efb6-806b-4746-a813-57b44397b65a.png)

And this is the same error plain new flutter counter app `flutter create test_app`  without any edits.

![image](https://user-images.githubusercontent.com/91150254/201546740-7ecb2c6f-1e96-40e8-aea7-f1b29d61aa04.png)

When I press shift or any key long time like 1 or 2 seconds this error is very annoying when trying to capitalize character in text field or switching app with `windows + ctrl + arrow key` or `alt + tab`.

I am using flutter sdk version `'>=2.18.4 <3.0.0'`.

The only thing that can avoid you from getting this error is to press the shortcut or the key fast without pressing more than 500 milliseconds, but this is very annoying specifically for users and clients.

**Comment by danagbemava-nc** [comment] 2022-11-14 09:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99653. 

Kindly follow up in the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2022-11-14 09:41 UTC
Labels: in triage
