### ISSUE TITLE
Image widget with BoxFit.cover does not fully cover the parent, 1px bug

### ISSUE THREAD

**Issue by AleksMx** [flutter/flutter#44582] opened 2019-11-11 16:19 UTC
My application display Image in the Container widget that have colored background (for this test I use red background). I use BoxFit.cover flag. However, I see a red bar on the right side from the parent background.

![V1](https://user-images.githubusercontent.com/4531547/68602107-c68e6080-04b6-11ea-9215-256cf91d6373.png)

### Left side: all right:
![V3](https://user-images.githubusercontent.com/4531547/68602188-f5a4d200-04b6-11ea-8952-b4514866db83.png)

### Right side: red bar
![V2](https://user-images.githubusercontent.com/4531547/68602149-e1f96b80-04b6-11ea-92bb-bb58b231b75b.png)

On the phone screen, it looks more dramatic. The problem appears only with the flag "alignment: Alignment(0, -1)".

## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
        padding: EdgeInsets.only(top: 100, bottom: 55),
        child: Container(
            alignment: Alignment(0, -1),
            width: double.infinity,
            child: Container(
                width: 347,
                child: Container (
                    margin: EdgeInsets.all(20),
                    color: Colors.red,
                    child: Image.network("https://wowslider.com/sliders/demo-93/data1/images/landscape.jpg", fit: BoxFit.cover)
                )
            )
        )
    );
  }
}
```

**Target Platform:** Android 9
**Devices:** Honor 9 Lite

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.5 at /home/XXXX/app/flutter
    • Framework revision 1aedbb1835 (4 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/XXXX/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/XXXX/app/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/XXXX/app/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • LLD XXXX • XXXXX • android-arm64 • Android 9 (API 28)

• No issues found!
Process finished with exit code 0
```

**Comment by jorwan** [comment] 2020-05-14 12:07
I'm getting this too. Any update ?

Thanks

**Comment by Piinks** [comment] 2020-07-13 16:46
This looks like it might be anti-aliasing. https://github.com/flutter/flutter/issues/14288 discusses this along with some workarounds. It also links to a number of related issues.

**Comment by goderbauer** [comment] 2020-07-21 17:20
I am going to close this as a dup of #14288.

**Closed by goderbauer** 2020-07-21 17:20 UTC
Labels: a: images, a: quality, framework, severe: rendering

**Comment by AleksMx** [comment] 2020-07-25 17:57
Yes, it is anti-aliasing. In the problem above, the picture has coordinates: left = **6.5**px, top = 70px. Because Aligment widget trying to place the picture to the center.

**Combined picture:**

![image](https://user-images.githubusercontent.com/4531547/88461517-dd41df80-ceac-11ea-9f3e-898697dc048d.png)
top - with red background Container, bottom - with transparent background Container

**Problem may be in a very aggressive anti-aliasing algorithm. For example, how anti-aliasing works in Android:**

![image](https://user-images.githubusercontent.com/4531547/88461781-462a5700-ceaf-11ea-8f85-3efdda14645e.png)

**How it works in Flutter:**

![image](https://user-images.githubusercontent.com/4531547/88461838-cfda2480-ceaf-11ea-8d8c-0b745b297cd2.png)
Skia use 2 pixels.

**How it works in Android Chrome:**

![image](https://user-images.githubusercontent.com/4531547/88461999-10866d80-ceb1-11ea-8ee7-fc8d3cdfc2cf.png)

**Android Chrome, red square above green square:**

![image](https://user-images.githubusercontent.com/4531547/88462227-850ddc00-ceb2-11ea-8415-58a9dc79c36b.png)

### I placed the line and the picture at the same distance:

**left: 0.5px:**

![image](https://user-images.githubusercontent.com/4531547/88462866-462e5500-ceb7-11ea-95bf-04cba8750867.png)

**left: 1.0px:**

![image](https://user-images.githubusercontent.com/4531547/88463076-c86b4900-ceb8-11ea-9d85-b3b53723afd3.png)

![image](https://user-images.githubusercontent.com/4531547/88463146-47f91800-ceb9-11ea-86a9-dbe48a480404.png)

`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container (
      color: Colors.white,
      child: Stack (
        textDirection: TextDirection.ltr,
        children: [
          Positioned (
              left: 1,
              top: 100,
              bottom: 500,
              child: Container (
                color: Colors.red,
                width: 1,
                height: 200,
                child: null,
              )
          ),
          Positioned (
              left: 1,
              top: 150,
              bottom: 100,
              child: Image.network("https://wowslider.com/sliders/demo-93/data1/images/landscape.jpg", fit: BoxFit.cover)
          ),
        ],
      ),
    );
  }
}`



> This looks like it might be anti-aliasing. #14288 discusses this along with some workarounds. It also links to a number of related issues.

So, it looks like an error in the layout calculations, which provokes antialiasing error.

**Comment by AleksMx** [comment] 2020-07-25 17:59
> I am going to close this as a dup of #14288.

I think the problem is not only in anti-aliasing.

**Comment by goderbauer** [comment] 2020-07-27 17:51
> So, it looks like an error in the layout calculations

What is the error in layout calculation?

/cc @liyuqian for AA-related questions.

**Comment by liyuqian** [comment] 2020-07-30 02:08
The AA artifacts usually only affect a single column of pixels so I'm surprised that your 1st and 3rd screenshots in https://github.com/flutter/flutter/issues/44582#issuecomment-663883261 are showing artifacts of 2 pixels wide. CC @bsalomon @reed-at-google from the Skia team: does Skia recently introduce some AA algorithms that could impact 2 pixels adjacent to the edge?

@AleksMx : but I can't reproduce your 2-pixel-wide artifacts locally either using your code in https://github.com/flutter/flutter/issues/44582#issue-521055837 or https://github.com/flutter/flutter/issues/44582#issuecomment-663883261. Is that the code that you used to generate the screenshot?

**Comment by AleksMx** [comment] 2020-07-30 07:59
> The AA artifacts usually only affect a single column of pixels so I'm surprised that your 1st and 3rd screenshots in [#44582 (comment)](https://github.com/flutter/flutter/issues/44582#issuecomment-663883261) are showing artifacts of 2 pixels wide. CC @bsalomon @reed-at-google from the Skia team: does Skia recently introduce some AA algorithms that could impact 2 pixels adjacent to the edge?
> 
> @AleksMx : but I can't reproduce your 2-pixel-wide artifacts locally either using your code in [#44582 (comment)](https://github.com/flutter/flutter/issues/44582#issue-521055837) or [#44582 (comment)](https://github.com/flutter/flutter/issues/44582#issuecomment-663883261). Is that the code that you used to generate the screenshot?

What OS did you use? On my screenshots Android Chrome also uses 2 pixels for anti-aliasing. So most likely the problem is not with 2 pixels.

**Comment by bsalomon** [comment] 2020-07-30 16:56
I can't think of any recent changes to how we do antialiasing, particularly for rectangles (which is how I assume the red background is drawn).

**Comment by liyuqian** [comment] 2020-07-30 22:52
@AleksMx : I'm testing your Flutter sample app on Android (Moto G4). Android Chrome, native Android, and Flutter all use Skia so their AA properties should be similar. Can you please share the code of your red rectangles on top of green rectangles? That may give us better ideas where the problem is. From what I can see so far, https://github.com/flutter/flutter/issues/14288 is still most likely the root cause of the problem.
