### ISSUE TITLE
Flutter 2.0 [Web]: Hot restart takes a lot of time to display changes in release mode

### ISSUE THREAD

**Issue by m-hamzashakeel** [flutter/flutter#78239] opened 2021-03-15 19:45 UTC
I'm using `Flutter 2.0` the **Stable Flutter version for Mobile and App**  yet Flutter for web is taking **too much** time in `Hot reload/restart`
- ##  🔥 Hot reload/restart logs
![image](https://user-images.githubusercontent.com/43790152/111211338-1b347500-85f0-11eb-82f6-b14814ac6da8.png)

- ## 🩺 Flutter Doctor
![image](https://user-images.githubusercontent.com/43790152/111211460-3dc68e00-85f0-11eb-95e1-448b87b98220.png)

- ## 📝 Note
It does `hot reload/restart` normally for newly created flutter app, but as soon as I try to change any single line of code it start taking more than `30 secs` sometimes.

- ## ⚙ Solution tried
- `flutter clean`
- `recreated the project (twice)`
- `restarted PC, after changing flutter 2.0 path`

**Comment by darshankawar** [comment] 2021-03-16 10:19
Thanks @m-hamzashakeel for reporting this. It seems to be only happening in `release` mode for both `canvaskit` and `html` renderers.  In debug mode, the hot restart is fast and quick.

```
1. flutter run -d chrome --release (last 2 rows of each command denotes time taken after making changes):

Performing hot restart...                                          649ms
Restarted application in 652ms.

Performing hot restart...                                          568ms
Restarted application in 568ms.

Performing hot restart...                                          546ms
Restarted application in 547ms.

**Performing hot restart...                                          40.3s
Restarted application in 40,346ms.

Performing hot restart...                                          38.6s
Restarted application in 38,567ms.**


2. flutter run -d chrome

Performing hot restart...                                          325ms
Restarted application in 327ms.

Performing hot restart...                                           92ms
Restarted application in 92ms.

Performing hot restart...                                           69ms
Restarted application in 69ms.

**Performing hot restart...                                          190ms
Restarted application in 191ms.

Performing hot restart...                                          182ms
Restarted application in 182ms.**


3. flutter run -d chrome --web-renderer html --release:

Performing hot restart...                                          568ms
Restarted application in 570ms.

Performing hot restart...                                          526ms
Restarted application in 526ms.

**Performing hot restart...                                          31.2s
Restarted application in 31,209ms.

Performing hot restart...                                          31.1s
Restarted application in 31,119ms.**

4. flutter run -d chrome --web-renderer html:

Performing hot restart...                                          145ms
Restarted application in 148ms.

Performing hot restart...                                           86ms
Restarted application in 86ms.

**Performing hot restart...                                          206ms
Restarted application in 206ms.

Performing hot restart...                                          210ms
Restarted application in 210ms.**
```


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by m-hamzashakeel** [comment] 2021-03-18 07:17
@darshankawar Yes, it seems to be working fine in `debug` mode
So, what if I want to `release` a build then? Won't it be a problem in performance?

And one more thing? The issues remains open or should I close it? (Sorry new to opening issues)

**Comment by jonahwilliams** [comment] 2021-03-19 23:00
Hot restart in release mode needs to do a full release compilation and refresh - of course its slow. Closing as this is working as intended

**Closed by jonahwilliams** 2021-03-19 23:00 UTC
Labels: a: build, a: release, found in release: 2.0, has reproducible steps, perf: speed, platform-web, severe: performance, t: hot reload, tool
