### ISSUE TITLE
[Impeller] Bad quality of drawing.

### ISSUE THREAD

**Issue by darkstarx** [flutter/flutter#157912] opened 2024-10-31 08:41 UTC
Unfortunately, Impeller is not ready to be an acceptable substitution of Skia, since it's unable to generate the picture satisfied our clients.

### Steps to reproduce

Just draw a line on the `Canvas` with Impeller and compare the result with Skia engine renderer.

### Expected results

The image generated by Impeller is the same or better than the image generated by Skia.
Impeller can draw lines with stroke width less than 1 correctly (like Skia does).

### Actual results

The image generated by Impeller is worse.
Impeller is not able to draw lines with stroke width less than 1 correctly (like Skia does).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main()
{
  runApp(const MyApp());
}

class MyApp extends StatelessWidget
{
  const MyApp({ super.key });

  @override
  Widget build(final BuildContext context)
  {
    return MaterialApp(
      theme: ThemeData.light(useMaterial3: true),
      darkTheme: ThemeData.dark(useMaterial3: true),
      themeMode: ThemeMode.system,
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget
{
  const MyWidget({ super.key });

  @override
  Widget build(final BuildContext context)
  {
    return Padding(
      padding: const EdgeInsets.all(56.0),
      child: CustomPaint(
        painter: MyPainter(color: Theme.of(context).colorScheme.primary),
        child: const SizedBox.square(dimension: double.infinity),
      ),
    );
  }

}

class MyPainter extends CustomPainter
{
  final Color color;

  const MyPainter({
    required this.color,
  });

  @override
  void paint(final Canvas canvas, final Size size)
  {
    final origin = Offset.zero;
    canvas.drawLine(origin, size.bottomRight(origin),
      Paint()
        ..color = color
        ..strokeWidth = 0.5
    );
  }

  @override
  bool shouldRepaint(final MyPainter oldDelegate) => color != oldDelegate.color;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![impeller](https://github.com/user-attachments/assets/7a044c9a-8e46-4209-81b8-579250be1207)
![skia](https://github.com/user-attachments/assets/095c0701-6f94-4aea-ad15-bdbbf74b4496)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Xcode build done.                                            9,9s
Connecting to VM Service at ws://127.0.0.1:62857/L8ZHeuF_VJg=/ws
Connected to the VM Service.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-11-01 07:36
I can see this issue on Flutter stable `3.24.4` as reported. On Flutter master `3.27.0-1.0.pre.327`, the issue seems to appear either with or without Impeller. 


Demo on `iPhone 7, iOS 15.8`. Need to click on each screenshot and zoom in to 250% to see the difference:
<details open>
<summary>Demo screenshot</summary>

Flutter stable `3.24.4`

| With Impeller ❗ | Without Impeller ✅ |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/8fb5f3c9-da02-43be-9f82-594b7f17a0de"> | <img width="400" src="https://github.com/user-attachments/assets/030bc6bf-ae47-4bc9-9980-fcff005fccff">

Flutter master `3.27.0-1.0.pre.327`

| With Impeller ❗ | Without Impeller ❗ |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/7d465195-320a-44f5-af24-6ce827b593d1"> | <img width="400" src="https://github.com/user-attachments/assets/485b6ca5-4a02-4687-b1f7-605862ab4325">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-x64, locale en-VN)
    • Flutter version 3.24.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (12 hours ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio Ladybug.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.70
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```console
[!] Flutter (Channel master, 3.27.0-1.0.pre.327, on macOS 15.0.1 24A348 darwin-x64, locale en-VN)
    • Flutter version 3.27.0-1.0.pre.327 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b18d34c574 (20 minutes ago), 2024-10-31 22:53:17 -0400
    • Engine revision cd46383cd5
    • Dart version 3.7.0 (build 3.7.0-88.0.dev)
    • DevTools version 2.40.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio Ladybug.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.95.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 130.0.6723.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jonahwilliams** [comment] 2024-11-04 18:49
Duplicate of https://github.com/flutter/flutter/issues/138682

**Closed by jonahwilliams** 2024-11-04 18:49 UTC
Labels: engine, has reproducible steps, e: impeller, team-engine, found in release: 3.24, found in release: 3.27
