### ISSUE TITLE
FractionalSizedBox that is relative to an ancestor's maxHeight constraint

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2836] opened 2016-03-22 20:43 UTC
FractionalSizedBox that is relative to an ancestor's maxHeight constraint.

Every now and then, people want to be able to size something as a fraction of the maxHeight of one of the ancestors. For example, suppose you have a logo image inside a column inside a vertical scrollable, you might want the image to be 20% of the scrollable container extent.

We could actually do this; the constraints are available at that time. The main problem with this is, how do you identify the ancestor you want to base the height on?

**Comment by Hixie** [comment] 2016-03-22 20:58
Actually that wouldn't work, because we wouldn't know how to mark things dirty correctly.

So I guess we're back to the old idea of adding some extra information to the BoxConstraints class that describes the "current" size. "unbounded" constraints would set this, classes like FractionallySizedBox would use this instead of the maxWidth/maxHeight when doing the latter would throw due to them being infinite.

**Comment by jimbeveridge** [comment] 2016-03-24 18:22
@Hixie Is #2715 basically a dupe of this?

**Comment by Hixie** [comment] 2016-03-24 18:23
no, they are unrelated.

**Comment by abarth** [comment] 2017-01-27 06:02
Current plan is to use CustomSingleChildLayout instead of building all these permutations as separate widgets.

**Closed by abarth** 2017-01-27 06:02 UTC
Labels: customer: pink, new feature, prod: framework
