### ISSUE TITLE
`$flutter build ios-framework --xcframework` fails at time of building FBLPromises.framework which is dependency of some Flutter module

### ISSUE THREAD

**Issue by VasylZa** [flutter/flutter#70563] opened 2020-11-15 11:09 UTC
## Steps to Reproduce
Run ios framework build. eg. `$flutter build ios-framework --xcframework`

```yaml
pubspec.yaml in my case contains following dependencies:
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider:
  get_it: ^4.0.1
  protobuf:
  permission_handler: ^5.0.1+1
  intl: ^0.16.0
  vector_math: any
  just_debounce_it: 3.0.0+2
  wakelock: ^0.1.4+2
  http: 0.12.1
  hive: ^1.4.3
  hive_flutter: ^0.3.0+2
  cached_network_image: 2.2.0+1
  flutter_cache_manager: 1.4.1
  google_maps_flutter: ^0.5.28+1
  polyline: ^1.0.2
  json_serializable: ^3.3.0
  table_calendar: ^2.2.3
  flutter_staggered_grid_view: ^0.3.2
  pedantic: ^1.9.0
  carousel_slider: ^2.2.1
  tuple: ^1.0.3
  package_info: ^0.4.1
  shared_preferences: ^0.5.12+2
  timeago: ^2.0.27
  progress_dialog: ^1.2.4
  uuid: 2.2.2
  retry: ^3.0.1
  pin_code_fields: ^5.1.0
  assets_audio_player: ^2.0.12
  url_launcher: ^5.7.2
  vibration: ^1.7.1
  path_provider: ^1.6.18
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
```
## Logs

$ flutter build ios-framework --xcframework
 
```bash
Building frameworks for com.......ui in debug mode...
 ├─Populating Flutter.framework...                                  0.9s
 ├─Creating Flutter.xcframework...                                  4.2s
 ├─Building App.framework...                                        3.7s
 ├─Creating App.xcframework...                                      4.0s
 ├─Building plugins...                                                  
  124.7s (!)                                       
Unable to create universal FBLPromises.framework: 2020-11-14 04:12:17.240 xcodebuild[9603:1959855]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL
2020-11-14 04:12:17.383 xcodebuild[9603:1959921]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL
2020-11-14 04:12:17.383 xcodebuild[9603:1959921]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL

Please, note. FBLPromises.framework is build under:
...../build/ios/framework/Debug/iphoneos/Debug-iphoneos/PromisesObjC/FBLPromises.framework  folder
but `$flutter build ...` command expexts it in:
...../build/ios/framework/Debug/iphoneos/Debug-iphoneos/FBLPromises/FBLPromises.framework  folder
```

```bash
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-UA)
    • Flutter version 1.22.4 at /Volumes/Linux/flutter
    • Framework revision 1aafb3a8b9 (2 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vasylz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • MT’s iPhone (mobile) • 16d4f83a4e665f21c224cc08039067478c7c73b8 • ios • iOS 13.6
```

**Comment by TahaTesser** [comment] 2020-11-16 11:48
Hi @VasylZa 
 Make sure you have bitcode enabled https://github.com/flutter/flutter/issues/67285#issuecomment-703488689
Can you please provide your ` flutter build ios-framework --xcframework --verbose`  logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) including module and native app without us?
Thank you

**Comment by VasylZa** [comment] 2020-11-16 14:55
Hi @TahaTesser 

Thank you for your quick answer!

I did try with Bitcode and no. It not affects on result. I've attached minimal sample where issue is reproducible. Maybe it helps to locate the issue more precisely. Just run '$flutter build ios-framework --xcframework'

Thank you!

[sample.zip](https://github.com/flutter/flutter/files/5547032/sample.zip)

**Comment by TahaTesser** [comment] 2020-11-17 08:54
<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on macOS 11.0.1 20B29 x86_64, locale
    en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.2
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.198

• No issues found!
```

</details>

**Comment by jmagman** [comment] 2020-11-17 22:23
I think this was fixed in https://github.com/flutter/flutter/pull/69736, which is available on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels).  @VasylZa Would you be able to validate it works there?

**Comment by TahaTesser** [comment] 2020-11-18 04:01
@VasylZa 
You would need to upgrade some of your dependencies to work on master, when I tried, there were a bunch of dependency conflict s, please update them and try again on master as suggest above

**Comment by VasylZa** [comment] 2020-11-19 00:21
Hi @TahaTesser,

I've just updated dependencies and seems it works. I get frameworks build with `master` channel. Did not tested it in deep 
yet, but it works so far!

Thank you and your team for support!
Best regards,
Vasyl.

**Comment by jmagman** [comment] 2020-11-19 01:20
Thanks for validating @VasylZa!
Duplicate of https://github.com/flutter/flutter/pull/69736.

**Closed by jmagman** 2020-11-19 01:20 UTC
Labels: a: build, a: existing-apps, found in release: 1.22, found in release: 1.23, has reproducible steps, platform-ios, severe: crash, tool
