### ISSUE TITLE
Text with a big font size shows different on iOS Simulator and the physical device

### ISSUE THREAD

**Issue by ozc** [flutter/flutter#39697] opened 2019-09-02 19:05 UTC
A text with custom font and big font size 293 shows different on iOS Simulator and a physical device of iPhone Xs max. Other text with smaller font sizes looks exactly the same

But as for my comparison, on physical device text is displayed as fontSize: 80.

```
  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      body: Stack(
        children: <Widget>[
.....

          Column(
            children: <Widget>[
              Container(
                margin: EdgeInsets.only(
                  top: 1108,
                ),
                child: Text(
                  title,
                  style: TextStyle(
                      color: Color.fromRGBO(0x03, 0xef, 0xbc, 1.0),
                      fontFamily: 'United Sans Cond',
                      fontSize: 97,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 20.0),
                ),
              ),

.....

```
I can't output outputs of ```flutter doctor -v```, ```flutter analyze``` and ```flutter run --verbose```, as I don't have the device and got this as a feedback from a client. For simulator I don't have this issue so I guess the outputs are not necessary for it.

I'll try to provide more data and put the screenshots if I get permission to share them from the client.

**Comment by VladyslavBondarenko** [comment] 2020-01-14 15:21
Hi @ozc 
Closing this issue as probably duplicate of https://github.com/flutter/flutter/issues/41101
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-01-14 15:21 UTC
Labels: a: typography, ⌺‬ platform-ios
