### ISSUE TITLE
runZoned with zoneValues lost after hot reload

### ISSUE THREAD

**Issue by felangel** [flutter/flutter#93676] opened 2021-11-15 19:52 UTC
## Steps to Reproduce

1. Run the following [DartPad](https://dartpad.dev/?null_safety=true&id=cb3679e19fae946e8f3b26d67c7b3312)
2. Note that the zoneValue, 'Hello World' is consistently accessible even across rebuilds (tapping increment)
3. Copy the same code and run on mobile (iOS or Android) via `flutter run`
4. Note that the zoneValue, 'Hello World' is consistently accessible even across rebuilds (tapping increment)
5. Trigger a Hot Reload
6. Note that the zoneValue 'Hello World' is no longer accessible.
7. Tap the increment button or Trigger a Hot Restart
8. Note that the zoneValue, 'Hello World' is again accessible.

**Expected results:** 

I would expect `zoneValues` to be accessible across hot reloads.

**Actual results:** 

`zoneValues` are lost after a hot reload until either a hot restart or a widget rebuild.

### Additional Context

If we make token `const` it doesn't appear to have an impact.

Also, if we define a class `MyModel`:

```dart
class MyModel {
  final value = Zone.current[token] as String?;
}
```

And instantiate `MyModel` within the `State`:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

const token = '__token__';

void main() {
  runZoned(
    () => runApp(const MyApp()),
    zoneValues: {token: 'Hello World'},
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  final _myModel = MyModel();

  @override
  Widget build(BuildContext context) {
    final zone = Zone.current;
    final value = zone[token] as String?;
    return Scaffold(
      appBar: AppBar(title: const Text('Zones Demo')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Text('Zone HashCode: ${zone.hashCode}'),
            Text('Zone Value: $value'),
            Text('Model Value: ${_myModel.value}'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _counter++),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class MyModel {
  final value = Zone.current[token] as String?;
}
```

Then the value retrieved from the model behaves as expected even across hot reloads.

It looks like the current zone is not copied during a hot reload.

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

final token = Object();

void main() {
  runZoned(
    () => runApp(const MyApp()),
    zoneValues: {token: 'Hello World'},
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    final zone = Zone.current;
    final value = zone[token] as String?;
    return Scaffold(
      appBar: AppBar(title: const Text('Zones Demo')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Text('Zone HashCode: ${zone.hashCode}'),
            Text('Zone Value: $value'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _counter++),
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
{"CFBundleName":"zones","DTXcode":"1310","DTSDKName":"iphonesimulator15.0","UILaunchStoryboardName":"LaunchScreen","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","AppIcon83.5x83.
5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"19A339","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"21A559","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFBundleSupportedPlatforms":["iPho
neSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortra
itUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.example.zones","UIDeviceFamily":[1,2],"DTPlatformVersion":"15.0","CFBundleSignature":"????","CFBundleIcons":{"CFBundlePrimaryIcon
":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"13A1030d","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLef
t","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"19A339","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect and debug your
application. This prompt will not appear on release builds."}
[   +4 ms] executing: xcrun simctl launch FCB4BE3E-33DA-49FC-A861-F647555D56A9 com.example.zones --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +205 ms] com.example.zones: 51465
[   +1 ms] Waiting for observatory port to be available...
[ +416 ms] Observatory URL on device: http://127.0.0.1:55348/QIoVQ24XVz0=/
[   +9 ms] Caching compiled dill
[  +51 ms] Connecting to service protocol: http://127.0.0.1:55348/QIoVQ24XVz0=/
[ +167 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:55348/QIoVQ24XVz0=/.
[  +95 ms] DDS is listening at http://127.0.0.1:55351/1RcuH9jFcOE=/.
[  +59 ms] Successfully connected to service protocol: http://127.0.0.1:55348/QIoVQ24XVz0=/
[  +26 ms] DevFS: Creating new filesystem on the device (null)
[  +17 ms] DevFS: Created new filesystem on the device (file:///Users/felix/Library/Developer/CoreSimulator/Devices/FCB4BE3E-33DA-49FC-A861-F647555D56A9/data/Containers/Data/Application/42BE9414-534D-477C-ADEB-EDC73F58B7FA/tmp/zonesEyB4Fm/zones/)
[   +2 ms] Updating assets
[  +63 ms] Syncing files to device iPhone 13...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:zones/main.dart 7fd16ad6-36b9-4ac5-99dd-f42726cef603
[        ] <- 7fd16ad6-36b9-4ac5-99dd-f42726cef603
[  +64 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone 13... (completed in 71ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +6 ms] Connected to _flutterView/0x7fb30a810c20.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 13 is available at: http://127.0.0.1:55351/1RcuH9jFcOE=/
[ +490 ms] The Flutter DevTools debugger and profiler on iPhone 13 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:55351/1RcuH9jFcOE=/
[+4486 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[  +11 ms] Scanned through 528 files in 6ms
[        ] Syncing files to device iPhone 13...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:zones/main.dart 564d0ee5-dbd9-4020-bfeb-4217c387483f
[        ] <- 564d0ee5-dbd9-4020-bfeb-4217c387483f
[   +6 ms] Updating files.
[   +2 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 13... (completed in 9ms)
[        ] Synced 0.0MB.
[  +11 ms] Reassembling application
[  +39 ms] Hot reload performed in 67ms.
[   +1 ms] Performing hot reload... (completed in 73ms)
[        ] Reloaded 0 libraries in 78ms.
```

```
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel beta, 2.7.0-3.1.pre, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.7.0-3.1.pre at /Users/felix/fvm/versions/beta
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision fc7015e35a (3 weeks ago), 2021-10-27 15:18:41 -0700
    • Engine revision a75e3b80f9
    • Dart version 2.15.0 (build 2.15.0-178.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] VS Code (version 1.63.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • FCB4BE3E-33DA-49FC-A861-F647555D56A9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-11-16 10:01
Reproducible on all channels.

<details>
<summary> logs</summary>

```console
Multiple devices found:
M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
iPhone 13 (mobile)  • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
macOS (desktop)     • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
Chrome (web)        • chrome                               • web-javascript • Google Chrome 96.0.4664.45
[1]: M2007J20CG (5dd3be00)
[2]: iPhone 13 (7515F01A-C1B6-456E-8559-8D2383D3719D)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.6s
Xcode build done.                                            9.9s
Syncing files to device iPhone 13...                               165ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 13 is available at: http://127.0.0.1:59220/9ngdopj5d04=/
The Flutter DevTools debugger and profiler on iPhone 13 is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:59220/9ngdopj5d04=/

Performing hot reload...                                                
Reloaded 0 libraries in 166ms.

Performing hot restart...                                               
Restarted application in 412ms.

Performing hot reload...                                                
Reloaded 0 libraries in 145ms.

Performing hot reload...                                                
Reloaded 0 libraries in 45ms.

Application finished.
```
</details>

<details>
<summary>videos</summary>

`using initial sample`

https://user-images.githubusercontent.com/88313112/141960622-6e807cb4-8341-4dac-93b2-38f8583a3997.mp4

`using sample with MyModel class`

https://user-images.githubusercontent.com/88313112/141962604-bf777a12-2595-41b2-ace5-342c7efb067c.mp4


</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.723, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.723 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 245168f85c (13 hours ago), 2021-11-15 12:55:32 -0800
    • Engine revision 2962099077
    • Dart version 2.16.0 (build 2.16.0-14.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.8.0-3.1.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0-3.1.pre at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3dab555040 (4 days ago), 2021-11-12 11:50:00 -0800
    • Engine revision 09f1520e8b
    • Dart version 2.15.0 (build 2.15.0-268.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

```console
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-11.0.pre at /Users/nexus/dev/sdks/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (9 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```
</details>

**Comment by christopherfujino** [comment] 2021-11-16 22:42
@rmacnak-google is this a bug or working as intended?

**Comment by felangel** [comment] 2021-11-23 17:28
Another issue related to this can be seen by adding `WidgetsFlutterBinding.ensureInitialized();` and observing that the zoneValues are no longer available within `onPressed` callbacks.

```dart
import 'dart:async';

import 'package:flutter/material.dart';

final token = Object();

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZoned(
    () => runApp(const MyApp()),
    zoneValues: {token: 'Hello World'},
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    final zone = Zone.current;
    final value = zone[token] as String?;
    return Scaffold(
      appBar: AppBar(title: const Text('Zones Demo')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Text('Zone HashCode: ${zone.hashCode}'),
            Text('Zone Value: $value'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final zone = Zone.current;
          final value = zone[token] as String?;
          print('Zone HashCode: ${zone.hashCode}');
          print('Zone Value: $value');
          setState(() => _counter++);
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by dnfield** [comment] 2021-11-30 23:35
here's a pared down example of what's happening:


```dart
import 'dart:async';
import 'dart:convert';
import 'dart:developer' as developer;

const token = '__token__';

void main() {
  runZoned(
    () {
      // final currentZone = Zone.current;
      developer.registerExtension(
        'ext.flutter.reassemble',
        (_, __) async {
          // currentZone.run(() {
            print('hot reload value: ${Zone.current[token]} ${Zone.current}');
          // });
          final result = {
            'type': '_extensionType',
            'method': 'ext.flutter.reassemble',
          };
          return developer.ServiceExtensionResponse.result(json.encode(result));
        },
      );
      print('initial value: ${Zone.current[token]} ${Zone.current}');
    },
    zoneValues: {token: 'Hello World'},
  );
}
```

If you comment out the commented lines, things work as expected. The problem is we're running the reassmble callback in the root zone no matter what.

**Comment by a-siva** [comment] 2021-12-07 01:36
After discussion with @dnfield this does not appear to be a Dart issue and hence removing the dart:dependency label.

**Comment by christopherfujino** [comment] 2021-12-07 22:54
> here's a pared down example of what's happening:
> 
> ```dart
> import 'dart:async';
> import 'dart:convert';
> import 'dart:developer' as developer;
> 
> const token = '__token__';
> 
> void main() {
>   runZoned(
>     () {
>       // final currentZone = Zone.current;
>       developer.registerExtension(
>         'ext.flutter.reassemble',
>         (_, __) async {
>           // currentZone.run(() {
>             print('hot reload value: ${Zone.current[token]} ${Zone.current}');
>           // });
>           final result = {
>             'type': '_extensionType',
>             'method': 'ext.flutter.reassemble',
>           };
>           return developer.ServiceExtensionResponse.result(json.encode(result));
>         },
>       );
>       print('initial value: ${Zone.current[token]} ${Zone.current}');
>     },
>     zoneValues: {token: 'Hello World'},
>   );
> }
> ```
> 
> If you uncomment the commented lines, things work as expected. The problem is we're running the reassmble callback in the root zone no matter what.

@goderbauer how does the Framework figure out which Zone to run the re-assemble callback?

**Comment by dnfield** [comment] 2021-12-07 23:06
@christopherfujino right now we're just running it in whatever zone it's called in, which will generally be the root zone. We can fix that similar to how dart:ui handles this.

Here's where the framework is doing it:

https://github.com/flutter/flutter/blob/af9cf734e83e2ed29d47bc3e667c223a2b110323/packages/flutter/lib/src/widgets/binding.dart#L452

Here's what dart:ui does for things like this:

https://github.com/flutter/engine/blob/1c10e686a8f93ccef58119ff25f232eaee369702/lib/ui/platform_dispatcher.dart#L119-L129

**Comment by dnfield** [comment] 2021-12-07 23:08
So my idea is in `initInstances`, you'd check the `Zone.current` and save it, so that when reassmbleApplication is called, it's called from the zone that was in use when `initInstances` was called.

This still has the limitation that if you initialize the binding _outside_ of your custom zone, it will get called in that zone instead of your custom one, but I think that should be acceptable.

**Comment by goderbauer** [comment] 2021-12-07 23:08
The framework doesn't do any special work currently to figure out what zone to run it on: https://github.com/flutter/flutter/blob/af9cf734e83e2ed29d47bc3e667c223a2b110323/packages/flutter/lib/src/widgets/binding.dart#L443-L458

**Comment by dnfield** [comment] 2021-12-07 23:09
But see also discussion in https://github.com/flutter/flutter/issues/94123

**Comment by rrousselGit** [comment] 2022-01-09 20:50
Is there anything we can do to move this forward?

**Comment by MichelMelhem** [comment] 2022-02-26 19:59
any updates ?

**Comment by nikitadol** [comment] 2022-03-14 09:49
Is this a similar problem?
#62331

**Comment by kk4736532** [comment] 2022-08-06 16:55
Hy 
Hgjfhlhgddk jjc
 Jhgkhfk

**Comment by Hixie** [comment] 2022-12-05 21:30
Isn't the bug here that dart:developer doesn't capture the callback's zone when `developer.registerExtension` is called?

**Comment by natebosch** [comment] 2022-12-05 21:46
> Isn't the bug here that dart:developer doesn't capture the callback's zone when `developer.registerExtension` is called?

That seems like a reasonable suggestion.

Does using [Zone.current.bindBinaryCallback](https://api.dart.dev/stable/2.18.5/dart-async/Zone/bindBinaryCallback.html) on the callback passed to `registerExtension` solve this issue? If it does, we can file an issue to consider always doing that inside `registerExtension`, or if there are any drawbacks.

**Comment by Hixie** [comment] 2022-12-05 21:53
Yeah, I believe that's what we do for most other engine callback entry points. I haven't tested that it would solve the issue here, but it should, I think?

**Comment by brianquinlan** [comment] 2022-12-14 19:20
Empirically, hot reload works with `package:http`, which [uses `bindCallback`](https://github.com/dart-lang/http/blob/master/pkgs/http/lib/src/client.dart#L191)

**Comment by mkustermann** [comment] 2023-08-11 07:03
@Hixie wasn't this fixed in https://github.com/dart-lang/sdk/commit/ca03588d2b2c57b29cb9ee77022ec8b02d4d50ba (which refers to this issue)?

**Comment by Hixie** [comment] 2023-08-11 19:47
Apparently, and then we never closed this one! Oops! Thanks for the information!

**Closed by Hixie** 2023-08-11 19:47 UTC
Labels: c: new feature, tool, framework, dependency: dart, t: hot reload, customer: crowd, has reproducible steps, P3, blocked, found in release: 2.5, found in release: 2.6, found in release: 2.8, team-framework, triaged-framework, multiteam-retriage-candidate
