### ISSUE TITLE
Flutter doctor: Accepting Android Licenses doesn't work

### ISSUE THREAD

**Issue by Ghoster524** [flutter/flutter#50924] opened 2020-02-17 14:34 UTC
## Steps to Reproduce

1. I open a terminal by typing cmd into the searchbar
2. Then I write the command `flutter doctor -v`
3. I see the error "Android Licenses not accepted" so I run the command `flutter doctor --android-licenses`
4. I accept every licenses that has been shown (7 in total)
5. I rerun step 2, but got the exact same error

## Logs

```
C:\Users\Martijn>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale nl-NL)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\Martijn\Documents\flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • ANDROID_SDK_ROOT = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment] 2020-03-03 22:39
Duplicate of https://github.com/flutter/flutter/issues/51712.  This was filed first, but there's more info in that issue.

**Closed by jmagman** 2020-03-03 22:39 UTC
Labels: t: flutter doctor, tool
