### ISSUE TITLE
Flutter web with image widget using --dart-define=FLUTTER_WEB_USE_SKIA=true not render

### ISSUE THREAD

**Issue by anik786** [flutter/flutter#54771] opened 2020-04-14 19:15 UTC
When building an app with Flutter Web with `FLUTTER_WEB_USE_SKIA` flag, remote images do not show up.

## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the files as follows:

*main.dart*
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Image.network('https://placehold.it/50x50', width: 50, height: 50,),
        ),
      ),
    );
  }
}
```

3. Run the app using:

```
$ flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true
```

**Expected results:**
The app with the image.

**Actual results:**
The image does not show up.

Also whenever I resize the browser I get a console error:

```
Another exception was thrown: Instance of 'minified:cS<void>'
```

Note that the app works fine without the `FLUTTER_WEB_USE_SKIA` flag. Unfortunately I found too many bugs with the Flutter Web without the flag (e.g. unable to change color of images) and found using the flag a better bet.

Thanks for the help.

<details>
  <summary>Logs</summary>

```
Analyzing flutter_web_demo...
No issues found! (ran in 1.4s)
```
```
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
    • Flutter version 1.17.0 at C:\Users\yahya\flutter
    • Framework revision d3ed9ec945 (8 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yahya\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\yahya\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\yahya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-04-15 08:30
Issue exist on latest `beta`, `dev` and `master`, using `FLUTTER_WEB_USE_SKIA` opens blank page with error in console

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (3 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92
    • Web Server • web-server • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-15 09:00
The error thrown in `js_primitives.dart:49` is shown in the browser console not only on resizing, but on the first load as well.

`Could not load content for org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_primitives.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

(appears only when trying to load images)

**Comment by Ahmadre** [comment] 2020-05-21 16:37
Any Updates yet? Issue still exists on latest Master (1.19.0-2.0.pre.133).

<img width="829" alt="Bildschirmfoto 2020-05-21 um 18 35 37" src="https://user-images.githubusercontent.com/18512224/82582288-1e0e3700-9b92-11ea-9c42-86bbf0729679.png">

**Comment by Ahmadre** [comment] 2020-05-21 16:45
The good thing is: Actual SKIA lead me to a better looking logo 👍:
<img width="219" alt="Bildschirmfoto 2020-05-21 um 18 44 48" src="https://user-images.githubusercontent.com/18512224/82583329-3fbbee00-9b93-11ea-9087-a9d131c4da39.png">

**Comment by ReniDelonzek** [comment] 2020-05-21 17:19
I have the same problem yet too

**Comment by vekexasia** [comment] 2020-05-24 16:57
skia is amazing. Did this ever work?

**Comment by MichealReed** [comment] 2020-06-17 01:35
The package "Cached Network Image" works  2.3.0-beta+1.

`cached_network_image: ^2.3.0-beta+1`

If you use gifs, it's not even worth attempting as you will run into https://github.com/flutter/flutter/issues/56938.

**Comment by vekexasia** [comment] 2020-06-23 10:05
@MichealReed I confirm it's not working. Either i'm missing something but I tried both that version and -rc.

**Comment by MichealReed** [comment] 2020-06-23 16:26
@vekexasia try `2.3.0-rc`

see https://github.com/Baseflow/flutter_cached_network_image/issues/395

**Comment by cbenhagen** [comment] 2020-06-28 09:42
Duplicate of https://github.com/flutter/flutter/issues/49725 and https://github.com/flutter/flutter/issues/54010

**Comment by VladyslavBondarenko** [comment] 2020-06-29 11:03
Please follow up on https://github.com/flutter/flutter/issues/49725, https://github.com/flutter/flutter/issues/54010,
closing as duplicate

**Closed by VladyslavBondarenko** 2020-06-29 11:03 UTC
Labels: assigned for triage, e: web_canvaskit, engine, found in release: 1.17, found in release: 1.18, has reproducible steps, platform-web, severe: crash, severe: regression
