### ISSUE TITLE
[flutter build apk ] FAILED

### ISSUE THREAD

**Issue by yjouyang** [flutter/flutter#51035] opened 2020-02-19 11:56 UTC
Here is the error msg:

```
A problem occurred evaluating root project
'flutter_plugin_android_lifecycle'.
           > Failed to apply plugin [id 'com.android.library']
              > Minimum supported Gradle version is 5.4.1.
```

I have no idea how this dependency appear in my project and it seems that this plugin indeed uses a quit old version of gradle, which is 4.10.2

flutter version: 1.12.13+hotfix.8

**Comment by yjouyang** [comment] 2020-02-19 12:05
I figure out that `flutter_plugin_android_lifecycle` is introduced by `image_picker`

**Comment by TahaTesser** [comment] 2020-02-19 12:25
Duplicate of [#50867](https://github.com/flutter/flutter/issues/50867)

**Closed by TahaTesser** 2020-02-19 12:25 UTC
