### ISSUE TITLE
Branch iOS Deep Linking not directing me to the app

### ISSUE THREAD

**Issue by Zeekoh23** [flutter/flutter#152104] opened 2024-07-22 13:42 UTC
### Steps to reproduce

1. Follow the steps listed in the [documentation](https://docs.flutter.dev/development/ui/navigation/deep-linking) on how to enable deep linking for mobile
2. Attempt to boot url to iPhone simulator using xcrun simctl openurl booted https://{MY_DOMAIN}

### Expected results

The booted url opens to the desired page within the installed application

### Actual results

The website for the app is opened in Safari instead

### Code sample

    final canonicalIdentifier = const Uuid().v4();
    final DateTime today = DateTime.now();
    String dateString =
        '${today.year}-${today.month}-${today.day} ${today.hour}:${today.minute}:${today.second}';
    // initDeepLinkData();
    debugPrint('share type $category image $image');
    //  BranchContentMetaData metadata = BranchContentMetaData();

    const imageURL =
        'https://raw.githubusercontent.com/RodrigoSMarques/flutter_branch_sdk/master/assets/branch_logo_qrcode.jpeg';
    BranchResponse response = await FlutterBranchSdk.getShortUrl(
        buo: BranchUniversalObject(
            canonicalIdentifier: 'flutter/branch_$canonicalIdentifier',
            //parameter canonicalUrl
            //If your content lives both on the web and in the app, make sure you set its canonical URL
            // (i.e. the URL of this piece of content on the web) when building any BUO.
            // By doing so, we’ll attribute clicks on the links that you generate back to their original web page,
            // even if the user goes to the app instead of your website! This will help your SEO efforts.
            //canonicalUrl: 'https://flutter.dev',
            title: title,
            imageUrl: image != ''
                ? category == 'forum'
                    ? image.insert(6, '/')
                    : image
                : imageURL,
            contentDescription: 'KEDU APP - $dateString',
            contentMetadata: BranchContentMetaData()
              ..addCustomMetadata('title', title)
              ..addCustomMetadata(
                  'imageUrl',
                  image != ''
                      ? category == 'forum'
                          ? image.insert(6, '/')
                          : image
                      : imageURL)
              ..addCustomMetadata('id', id)
              ..addCustomMetadata('category', category),
            keywords: ['Plugin', 'Branch', 'Flutter'],
            publiclyIndex: true,
            locallyIndex: true,
            expirationDateInMilliSec: DateTime.now()
                .add(const Duration(days: 365))
                .millisecondsSinceEpoch),
        linkProperties: BranchLinkProperties(
            channel: 'share',
            feature: 'sharing',
            //parameter alias
            //Instead of our standard encoded short url, you can specify the vanity alias.
            // For example, instead of a random string of characters/integers, you can set the vanity alias as *.app.link/devonaustin.
            // Aliases are enforced to be unique** and immutable per domain, and per link - they cannot be reused unless deleted.
            //alias: 'https://branch.io' //define link url,
            //alias: 'p/$id', //define link url,
            stage: 'new share',
            campaign: 'campaign',
            tags: ['one', 'two', 'three'])
          ..addControlParam('\$uri_redirect_mode', '1')
          ..addControlParam('\$ios_nativelink', true)
          ..addControlParam('\$match_duration', 7200)
          ..addControlParam('\$always_deeplink', true)
          ..addControlParam('\$android_redirect_timeout', 750)
          ..addControlParam('referring_user_id', 'user_id') //;
          ..addControlParam('\$ios_url',
              'https://flutter-branch-sdk.netlify.app/',
              )
          ..addControlParam('\$android_url',
               'https://flutter-branch-sdk.netlify.app/',
              ));
    if (response.success) {
      if (context.mounted) {
        debugPrint('share link ${response.result}');
        FlutterBranchSdk.handleDeepLink('${response.result}?bnc_validate=true');
      }
    } else {
      if (context.mounted) {
        errorMessage(
          context: context,
          err: 'Error : ${response.errorCode} - ${response.errorMessage}',
        );
      }
    }

### Screenshots or Video

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-22 at 14 34 26](https://github.com/user-attachments/assets/62df82c3-8b86-48e3-94cc-fa9639d783d4)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2024-07-23 06:40
Closing as duplicate of https://github.com/flutter/flutter/issues/123985

**Closed by darshankawar** 2024-07-23 06:40 UTC
Labels: in triage

**Comment by Zeekoh23** [comment] 2024-07-24 16:40
Hello @darshankawar that didn't solve my problem
