### ISSUE TITLE
Debug OverAsyncSuspension on an await does not behave as expected

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18877] opened 2018-06-27 15:32 UTC
Given this app:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    doAsyncStuff();
    super.initState();
  }

  Future<void> doAsyncStuff() async {
    print("test"); // BREAKPOINT
    await new Future.value(true);
    print("test2");
    await new Future.microtask(() => true);
    print("test3");
    await new Future.delayed(const Duration(milliseconds: 1));
    print("done!");
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Container(),
    );
  }
}
```

If you put a breakpoint on the line `// BREAKPOINT` and once you hit it just start hitting `Step Over` (which sends a `OverAsyncSuspension` when at an async suspension) you would expect it to step through each line of that method. However, once it pauses on `await` and we send `OverAsyncSuspension` it just seems to resume with no further breaking.

```
Dart Code extension: 2.15.0-beta.2
Flutter extension: 2.14.0
Platform: mac
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk
    Ver: 2.0.0-edge.4c9689c1d2da97d0aa25cf16cc90c2e463ad157f
Flutter SDK:
    Loc: /Users/dantup/Dev/Google/flutter
    Ver: 0.5.6-pre.94

Wed Jun 27 2018 [16:29:27 GMT+0100 (BST)] Log file started
[16:29:30 GMT+0100 (BST)] [Observatory] ==> {"id":"409","method":"resume","params":{"isolateId":"isolates/721510985","step":"Over"}}
[16:29:30 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"409"}
[16:29:30 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113370638,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":362},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[16:29:30 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113370640,"pauseBreakpoints":[],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":405},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[16:29:30 GMT+0100 (BST)] [Observatory] ==> {"id":"410","method":"getStack","params":{"isolateId":"isolates/721510985"}}
[16:29:30 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":405},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@7048458\/scripts\/dart%3Aasync%2Fruntime%2Flibasync_patch.dart\/16441dce93b","uri":"dart:async\/runtime\/libasync_patch.dart","_kind":"kernel"},"tokenPos":1469},"function":{"type":"@Function","fixedId":true,"id":"classes\/241\/functions\/start","name":"start","owner":{"type":"@Class","fixedId":true,"id":"classes\/241","name":"_AsyncAwaitCompleter","_vmName":"_AsyncAwaitCompleter@7048458"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc8939b-127cbb440","name":"_AsyncAwaitCompleter.start","_vmName":"start","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this"…
[16:29:31 GMT+0100 (BST)] [Observatory] ==> {"id":"411","method":"getStack","params":{"isolateId":"isolates/721510985"}}
[16:29:31 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":405},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@7048458\/scripts\/dart%3Aasync%2Fruntime%2Flibasync_patch.dart\/16441dce93b","uri":"dart:async\/runtime\/libasync_patch.dart","_kind":"kernel"},"tokenPos":1469},"function":{"type":"@Function","fixedId":true,"id":"classes\/241\/functions\/start","name":"start","owner":{"type":"@Class","fixedId":true,"id":"classes\/241","name":"_AsyncAwaitCompleter","_vmName":"_AsyncAwaitCompleter@7048458"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc8939b-127cbb440","name":"_AsyncAwaitCompleter.start","_vmName":"start","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this"…
[16:29:33 GMT+0100 (BST)] [Observatory] ==> {"id":"412","method":"resume","params":{"isolateId":"isolates/721510985","step":"Over"}}
[16:29:33 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"412"}
[16:29:33 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113373334,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":405},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[16:29:33 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113373336,"pauseBreakpoints":[],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":395},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0},"atAsyncSuspension":true}}}
[16:29:33 GMT+0100 (BST)] [Observatory] ==> {"id":"413","method":"getStack","params":{"isolateId":"isolates/721510985"}}
[16:29:33 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":395},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@7048458\/scripts\/dart%3Aasync%2Fruntime%2Flibasync_patch.dart\/16441dce93b","uri":"dart:async\/runtime\/libasync_patch.dart","_kind":"kernel"},"tokenPos":1469},"function":{"type":"@Function","fixedId":true,"id":"classes\/241\/functions\/start","name":"start","owner":{"type":"@Class","fixedId":true,"id":"classes\/241","name":"_AsyncAwaitCompleter","_vmName":"_AsyncAwaitCompleter@7048458"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc8939b-127cbb440","name":"_AsyncAwaitCompleter.start","_vmName":"start","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this"…
[16:29:33 GMT+0100 (BST)] [Observatory] ==> {"id":"414","method":"getStack","params":{"isolateId":"isolates/721510985"}}
[16:29:33 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":395},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@7048458\/scripts\/dart%3Aasync%2Fruntime%2Flibasync_patch.dart\/16441dce93b","uri":"dart:async\/runtime\/libasync_patch.dart","_kind":"kernel"},"tokenPos":1469},"function":{"type":"@Function","fixedId":true,"id":"classes\/241\/functions\/start","name":"start","owner":{"type":"@Class","fixedId":true,"id":"classes\/241","name":"_AsyncAwaitCompleter","_vmName":"_AsyncAwaitCompleter@7048458"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc8939b-127cbb440","name":"_AsyncAwaitCompleter.start","_vmName":"start","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this"…
[16:29:36 GMT+0100 (BST)] [Observatory] ==> {"id":"415","method":"resume","params":{"isolateId":"isolates/721510985","step":"OverAsyncSuspension"}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointAdded","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376135,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/3","breakpointNumber":3,"isSyntheticAsyncContinuation":true,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":335}}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"415"}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376135,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":395},"function":{"type":"@Function","fixedId":true,"id":"classes\/1099\/closures\/73","name":"async_op","_vmName":":async_op","owner":{"type":"@Function","fixedId":true,"id":"classes\/1099\/functions\/doAsyncStuff","name":"doAsyncStuff","owner":{"type":"@Class","fixedId":true,"id":"classes\/1099","name":"_MyAppState","_vmName":"_MyAppState@16503710"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/77dc89446-127cbb560","name":"_MyAppState.doAsyncStuff","_vmName":"async_op","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointResolved","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376334,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/3","breakpointNumber":3,"isSyntheticAsyncContinuation":true,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16503710\/scripts\/file%3A%2F%2F%2FUsers%2Fdantup%2FDesktop%2Ftest_test_test%2Flib%2Fmain.dart\/16441dce9d1","uri":"file:\/\/\/Users\/dantup\/Desktop\/test_test_test\/lib\/main.dart","_kind":"kernel"},"tokenPos":496}}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.FirstFrame","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376461,"extensionData":{}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376462,"extensionData":{"number":1,"startTime":0,"elapsed":119615}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376466,"extensionData":{"number":2,"startTime":0,"elapsed":555}}}}
[16:29:36 GMT+0100 (BST)] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/721510985","name":"main.dart:main()","number":"721510985"},"timestamp":1530113376668,"extensionData":{"number":3,"startTime":179609,"elapsed":23948}}}}
Wed Jun 27 2018 [16:29:40 GMT+0100 (BST)] Log file ended
```

@a-siva @aam any ideas? Am I using it wrong or is this a bug? Our `OverAsyncSuspension` code has been in a long time, so I *think* it's correct; though it will have been tested with (non-Flutter) Dart originally.

**Comment by bkonyi** [comment] 2018-07-19 15:43
It looks like the implicit breakpoint set after the `await` isn't being resolved correctly, so the debugger just falls through and continues execution. However, interestingly enough, the debugger works properly with following modifications in the program:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    doAsyncStuff();
    super.initState();
  }

  void foo() {
    print('bar');
  }

  Future<void> doAsyncStuff() async {
    print("test"); // BREAKPOINT
    await new Future.value(true);
    print("test2");
    // await new Future.microtask(() => true); #1 totally remove this line or
    await new Future.microtask(foo);        // #2: use a tear-off instead of a closure
    print("test3");
    await new Future.delayed(const Duration(milliseconds: 1));
    print("done!");
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Container(),
    );
  }
}
```

Not sure what the cause is yet. I'll post updates when I have them.

**Comment by bkonyi** [comment] 2018-07-20 21:20
This should be fixed once [this patch in the Dart SDK](https://github.com/dart-lang/sdk/commit/6bddb6c112d7f8c220397652f92f4263daf5ca12) gets rolled into the Flutter engine, which should hopefully happen by Monday.

**Comment by bkonyi** [comment] 2018-07-26 22:56
Quick update: Dart SDK roll into Flutter is blocked on dart-lang/sdk#33993. Hopefully will be resolved by tomorrow so this issue can be closed.

**Comment by bkonyi** [comment] 2018-07-30 17:23
This fix has landed in the latest Dart SDK roll into Flutter.

**Closed by bkonyi** 2018-07-30 17:23 UTC
Labels: a: debugging

**Comment by DanTup** [comment] 2018-07-31 08:45
Fix looks good, thanks!
