### ISSUE TITLE
DraggableScrollableSheet not working as expected 

### ISSUE THREAD

**Issue by kjawadDeveloper** [flutter/flutter#70690] opened 2020-11-17 13:18 UTC
Draggable Scrollable sheet only works the first time and after that, it does drag and remained fixed. This only happens in the master branch. When I switched back to the stable branch everything worked perfectly.

**Comment by pedromassangocode** [comment] 2020-11-17 14:16
Hi @kjawadDeveloper 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Vofchuk** [comment] 2020-11-24 15:44
I'm having the same issue! I'm on the dev branch and after updating flutter yesterday the Draggable Scrollable sheet stopped working

**Comment by kjawadDeveloper** [comment] 2020-11-24 15:47
@Vofchuk  i moved back to master and it started working again

**Comment by Vofchuk** [comment] 2020-11-24 16:40
I see that @kjawadDeveloper , and it really solved the problem! thank you very much for the tip!

**Comment by pedromassangocode** [comment] 2020-11-25 07:23
> Hi @kjawadDeveloper
> Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample?
> Thank you

**Comment by kjawadDeveloper** [comment] 2020-11-25 07:36
[✓] Flutter (Channel master, 1.24.0-8.0.pre.147, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.147 at /Users/jawad/Flutter/flutter
    • Framework revision f04b3d917f (2 weeks ago), 2020-11-07 16:09:02 -0500
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jawad/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.67

• No issues found!

**Comment by pedromassangocode** [comment] 2020-11-25 08:35
Hi @kjawadDeveloper 
I need a minimal complete reproducible code sample as well!

**Comment by KunaalKumar** [comment] 2020-11-27 04:53
I've been able to reproduce this issue with the following code:

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DraggableScrollableSheet(
        minChildSize: 0.1,
        initialChildSize: 0.15,
        maxChildSize: 0.8,
        builder: (context, scrollController) => Material(
          elevation: 8,
          child: ListView.builder(
            controller: scrollController,
            itemBuilder: (context, index) => ListTile(
              title: Text("Item $index"),
            ),
          ),
        ),
      ),
    );
  }
```
The DraggableScrollableSheet expands till the maxChildSize and goes down to the minChildSize as expected initially. However after a hot reload, it resets to the initialChildSize and doesn't move. The ListView inside the builder scrolls as expected but the bottom sheet itself does not. 

I suspect that there could be an issue where the scrollController is being ignored after the hot reload.

**Comment by kjawadDeveloper** [comment] 2020-11-27 06:20
> I've been able to reproduce this issue with the following code:
> 
> ```dart
> @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: DraggableScrollableSheet(
>         minChildSize: 0.1,
>         initialChildSize: 0.15,
>         maxChildSize: 0.8,
>         builder: (context, scrollController) => Material(
>           elevation: 8,
>           child: ListView.builder(
>             controller: scrollController,
>             itemBuilder: (context, index) => ListTile(
>               title: Text("Item $index"),
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> ```
> 
> The DraggableScrollableSheet expands till the maxChildSize and goes down to the minChildSize as expected initially. However after a hot reload, it resets to the initialChildSize and doesn't move. The ListView, inside the builder, scrolls as expected but the bottom sheet itself does not.
> 
> I suspect that there could be an issue where the scrollController is being ignored after the hot reload.

Not even in hot reload but also if you rebuild the sheet. It does the same thing.

**Comment by pedromassangocode** [comment] 2020-11-27 09:30
Reproducible on `beta` and `master` channel.

<details><summary></summary>

```

```
</details>
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (9 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

<details><summary>flutter doctor -v</summary>

```

```
</details>

**Comment by HansMuller** [comment] 2020-11-30 21:27
CC @dnfield

**Comment by dnfield** [comment] 2020-12-01 04:52
Very likely caused by https://github.com/flutter/flutter/pull/71459.

reverting that since it caused at least one other problem as well that I haven't been able to track down yet.

**Comment by kubaprzetakiewicz** [comment] 2020-12-08 10:03
Seems to be working properly again as of `1.25.0-5.0.pre.108`.

**Comment by MrBirb** [comment] 2021-01-17 13:40
@pedromassangocode The PR that most likely caused this issue was reverted. Can you confirm and perhaps close this?

**Comment by Vofchuk** [comment] 2021-01-17 13:47
Checked now and is working again! Thinks!

**Comment by pedromassangocode** [comment] 2021-01-18 13:04
> @pedromassangocode The PR that most likely caused this issue was reverted. Can you confirm and perhaps close this?

Thanks, I can confirm that the PR was reverted and everything is working fine again. I'm going to close this for now and reopen it in case the issue appear again.

Thank you

**Closed by pedromassangocode** 2021-01-18 13:04 UTC
Labels: customer: web10, customer: workplace, f: scrolling, found in release: 1.24, framework, has reproducible steps, severe: regression
