### ISSUE TITLE
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

### ISSUE THREAD

**Issue by hassanyassiin** [flutter/flutter#116193] opened 2022-11-29 17:09 UTC
## Steps to Reproduce

Getting this error **[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument**  without pressing on any button/function. and this error doesn't show up every time rarely to show, but I want to know from where does this error is getting.

**Expected results:** 
Launching the app without getting any errors.

**Actual results:** 
Launching the app and sometimes(rarely) I'm getting this error.

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    en-LB)
    • Flutter version 3.3.9 on channel stable at
      /Users/hassanyassin/Desktop/Flutter/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassanyassin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone (19) (mobile) • 08f6d5d4e6ac65273a8757fc2424f2f593e6ca56 • ios
      • iOS 16.1.1 20B101
    • macOS (desktop)      • macos                                    •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)         • chrome                                   •
      web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by hassanyassiin** [comment] 2022-11-30 12:24
hello @huycozy , I'm not understanding this warning message from where it's coming, because it's happening in different screens and rarely it happens and without pressing on anything or function, so I don't know if there is a function that leads for this error(I don't think so because it's happening without pressing on any tap).

**Comment by huycozy** [comment] 2022-12-01 04:03
Hi @hassanyassiin 
The issue should be actionable with clear steps to reproduce it. I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and write a comment when you have clear steps to reproduce. Thanks!

**Comment by hassanyassiin** [comment] 2022-12-01 16:54
I also get it now with a default flutter app but I added to it firebase storage / firebase core and the image picker package.

// I don't have the steps to reproduce the problem, but it's happening suddenly and rarely even with the default flutter app and without pressing on anything

<img width="1512" alt="Screenshot 2022-12-01 at 12 07 01 PM" src="https://user-images.githubusercontent.com/94860683/205036596-6f4ecb94-a0cc-46c6-994a-fccee2d86e7d.png">

**Comment by darshankawar** [comment] 2022-12-02 05:33
@hassanyassiin 
Do you have M1 or Intel machine ? 
Can you switch to latest master and try again to see if it occurs on that version too ?

**Comment by hassanyassiin** [comment] 2022-12-02 14:46
@darshankawar  This error doesn't appear on the Master channel.
But I want to use the stable channel so how to avoid this error on the stable channel.

Yes I'm using MacBook Pro (M1 Pro chip)

**Comment by darshankawar** [comment] 2022-12-05 05:34
Can you also confirm if this is occuring using iOS or Android or on both platforms ?

**Comment by darshankawar** [comment] 2022-12-06 05:30
Can you also try to run the app directly from terminal / command line instead of from IDE and see if you still get same log with it too ? I don't think this is specific to `firebase_storage` or any other plugin but could be related to M1.

**Comment by darshankawar** [comment] 2022-12-08 05:59
Thanks for the update. I am unable to replicate this behavior using use case mentioned above, but based on the report and log, keeping it open and labeling for team's attention and insights.

```
Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           115.5s
Debug service listening on ws://127.0.0.1:49977/aJQpLXJT0-Y=/ws
Syncing files to device iPhone 13 Pro Max...

```

**Comment by chinmaygarde** [comment] 2023-01-09 19:24
The log seems [to being emitted here](https://github.com/flutter/engine/blob/eb5c6f0b4ed94325e9c9811cc8681d687e0f5c8a/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm#L203) and seems benign. @gaaclarke @iskakaushik Perhaps we can suppress it?

**Comment by hassanyassiin** [comment] 2023-02-06 08:18
@chinmaygarde I've noticed that I got this error when I add a package that makes http requests like firebase/http etc.. because I run default flutter app with only http package and this error occurs, then I tried it with firebase then this error occurs also, when I removed all the packages that makes http request, I've never seen this error again!.

Can you please let me know what should I do to solve this issue before publishing my app? because I'm trying to publish my app after 2 weeks.

Thanks !

**Comment by mr-srini** [comment] 2023-10-12 06:57
I have encountered the same problem

`Launching lib/main.dart on iPhone 15 Pro in debug mode...`
`main.dart:1`
`Xcode build done.                                           66.8s`
`(488) [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.`
`(171) [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument`
`[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.`
`Lost connection to device.`
`Exited`

**Comment by mr-srini** [comment] 2023-10-30 13:46
Unable to build iOS app, app is crashing.

**Comment by mr-srini** [comment] 2023-11-30 19:58
Circling back on this, I am unable to build my app for iOS because of this problem, Is there anything I am missing?

**Comment by S-Akhilesh** [comment] 2023-12-05 06:58
Hey there, I am also having the same problem not able to build the app for iOS. 

Log - 

'''
(488) [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
(171) [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
'''

**Comment by hls-app** [comment] 2024-02-01 09:25
Same issue

```
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

If this helps
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71
    darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (5 available)
[✓] Network resources
```

**Comment by sagar13b** [comment] 2024-03-21 15:30
Same issue while performing flutter run
`Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,749ms
Xcode build done.                                           11.1s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Lost connection to device.`

if this helps
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
sbhusal@DHNPLAP046-sbhusal app_fluter % flutter doctor -v
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-NP)
    • Flutter version 3.19.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.19.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sbhusal/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 14 (API 34) (emulator)
    • iPhone 15 Pro (mobile)      • 65FB77C6-4580-4682-8959-43901FA1E60D • ios           • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64  • macOS 14.1.2 23B92 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by chinmaygarde** [comment] 2024-04-18 17:21
The log itself is benign and the profiler will try again if it can't get the information. I've remove the log in https://github.com/flutter/engine/pull/52227

That log should not interfere with launching or publishing the app.

The reports of the asserts in platforms views or anything related to Impeller are unrelated. Please file separate issues with reproduction steps if you have them.

**Closed** 2024-04-18 19:50 UTC
Labels: platform-ios, engine, p: firebase, a: error message, P2, team-ios, triaged-ios
