### ISSUE TITLE
google_maps_flutter: ^2.0.1 - missing plugin exception, No implementation found for method tileOverlays

### ISSUE THREAD

**Issue by lukaglo** [flutter/flutter#79039] opened 2021-03-25 12:28 UTC
I understand that the goolge_maps_flutter plugin is by Flutter Team ...
Here is the error message I get via Sentry on running the app:
`MissingPluginException: MissingPluginException(No implementation found for method tileOverlays#update on channel plugins.flutter.io/google_maps_1)`
This does not seem to be critical (does not crash the app) but at this moment is the most frequently occuring error. Maybe the Team should be aware of this...

My environment is Android and here is the output from Flutter doctor:
```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.14393], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (1 available)
```

**Comment by TahaTesser** [comment] 2021-03-25 12:49
Hi @lukaglo 
This looks like https://github.com/flutter/flutter/issues/78625
Are you using Android Gradle 4.1?  Can you please test with the [workaround](https://github.com/flutter/flutter/issues/78625#issuecomment-803243381) locally in release mode `flutter run --release -v`?
Thank you

**Comment by lukaglo** [comment] 2021-03-25 13:04
Hello - I will need some time to check these for you. 
One thing - I am not using Progurard as seems to be the case in the Workaround you quote.
Regards

**Comment by ekasetiawans** [comment] 2021-03-25 14:05
@lukaglo proguard/R8 is enabled by default when you build a release APK or AAB
See https://flutter.dev/docs/deployment/android

**Comment by nt4f04uNd** [comment] 2021-03-25 14:16
flutter uses r8 which has uses the same rules as proguard

> proguard/R8 is enabled by default

this is a bit inaccurate, r8 came as replacement of proguard, flutter only uses r8

**Comment by ekasetiawans** [comment] 2021-03-25 14:18
@nt4f04uNd thank you for correcting me

**Comment by lukaglo** [comment] 2021-03-25 17:01
Hello again - I am using  'com.android.tools.build:gradle:3.5.0'. Do you think I should move up to 4.1 ?

**Comment by TahaTesser** [comment] 2021-03-26 07:41
@lukaglo 
Please upgrade to Gradle 4.1, If the problem persists, Can you please provide your and `flutter run --release --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by lukaglo** [comment] 2021-03-29 08:49
Hello - quick update. Migration to higher Gradle version did not help. I will try to provide the required additional information within 1-2 days.
Regards

**Comment by lukaglo** [comment] 2021-03-30 10:38
Hello again. 
I did the change proposed in the fix quoted. Here is the link to the results of run --release-verbose: [GDocs](https://docs.google.com/document/d/1VOFMVcCB_Wz84wM72y5aDNnTxCCTj07TAGd7LQedEVo/edit?usp=sharing) 
I have not tested extensively yet after implementing the build.gradle change - need more time to rollout for testing. 
Please let me know if the provided info is of any help to you.
Kind regards

**Comment by TahaTesser** [comment] 2021-03-31 07:27
@lukaglo 
There is no exception in your logs, Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by palchukovsky** [comment] 2021-04-08 15:57
Something wrong with the plugin design, I think. Sorry, I don't have time to provide a sample to reproduce right now, but my investigation has shown the main problem in my case is that google_maps_flutter controls the lifetime of the controller.

If Flutter decides to remove the widget from the widget tree - GoogleMap implementation calls "dispose" for the controller of the map and all scheduled but not completed calls with this controller will raise the exception "MissingPluginException(No implementation found for method map#...".

The situation even worsts if I need to control the map by this controller: I receive it by Future through callback onMapCreated callback, and I have always to watch - is it the same state that created this controller or already a new state. Because I have to manage map, for example, call animated camera moving.

I'm very new to Flutter, so maybe it's not a plugin design issue but my way to use it. Is it possible to use my own map controller, not which GoogleMap gives me by the callback onMapCreated? Or control controller "disposing"?

**Comment by pedromassangocode** [comment] 2021-05-07 10:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:52 UTC
Labels: in triage, waiting for customer response

**Comment by ozc** [comment] 2021-07-09 12:02
This error occurs if liteModeEnabled: false. If set true, there's no problem.
