### ISSUE TITLE
Adding TextField to ListTile's title field throws exception

### ISSUE THREAD

**Issue by vjyrakesh** [flutter/flutter#25902] opened 2018-12-30 09:49 UTC
I am trying to add a `TextField` widget in the `title` field of a `ListTile` widget in my app. When I run the application, I get an exception with the following information:
```
[{"event":"app.progress","params":{"appId":"f4965df4-4fca-47eb-b741-4c690f9c0687","id":"23","progressId":"hot.reload","message":"Performing hot reload..."}}]Performing hot reload...

Syncing files to device Android SDK built for x86...
I/flutter (27985): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (27985): The following assertion was thrown during performLayout():
I/flutter (27985): Please see the documentation for computeDistanceToActualBaseline for the required calling
I/flutter (27985): conventions of this method.
I/flutter (27985): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1642 pos 12: '!_debugDoingBaseline'
I/flutter (27985): 
I/flutter (27985): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (27985): more information in this error message to help you determine and fix the underlying cause.
I/flutter (27985): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (27985):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (27985): 
I/flutter (27985): When the exception was thrown, this was the stack:
I/flutter (27985): #2      RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1642:12)
I/flutter (27985): #3      _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:816:35)
I/flutter (27985): #4      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:846:18)
I/flutter (27985): #5      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:976:44)
I/flutter (27985): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #13     _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:892:9)
I/flutter (27985): #14     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:922:28)
I/flutter (27985): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (27985): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (27985): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #30     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter (27985): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #32     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (27985): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #34     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (27985): #35     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (27985): #36     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (27985): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #54     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (27985): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #56     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (27985): #57     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (27985): #58     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (27985): #59     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (27985): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #64     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (27985): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #81     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter (27985): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #83     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (27985): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #85     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27985): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27985): #97     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (27985): #98     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (27985): #99     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (27985): #100    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (27985): #101    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (27985): #102    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (27985): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27985): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27985): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (27985): #107    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (27985): #108    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (27985): #109    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Reloaded 2 of 456 libraries in 2,123ms.
I/flutter (27985): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (27985): 
I/flutter (27985): The following RenderObject was being processed when the exception was fired:
I/flutter (27985):   _RenderDecoration#f9d30 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
I/flutter (27985):   GestureDetector ← IgnorePointer ← Semantics ← TextField ← DefaultTextStyle ←
I/flutter (27985):   AnimatedDefaultTextStyle ← _ListTile ← ⋯
I/flutter (27985):   parentData: <none> (can use size)
I/flutter (27985):   constraints: BoxConstraints(w=299.4, 0.0<=h<=Infinity)
I/flutter (27985):   size: MISSING
I/flutter (27985): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (27985):   RenderRepaintBoundary#f8291 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):     RenderRepaintBoundary#a58ea NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):       RenderCustomPaint#d843b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):         RenderRepaintBoundary#27150 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):           RenderPointerListener#315b2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):   RenderAnimatedOpacity#86d9b relayoutBoundary=up15 NEEDS-PAINT
I/flutter (27985):     RenderParagraph#34402 relayoutBoundary=up16 NEEDS-PAINT
I/flutter (27985):   RenderConstrainedBox#47c5f NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985):   RenderCustomPaint#a4ecf NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#f9d30 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#595bf relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#78f11 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#ef2ce relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#d1aae relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a7bd7 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#048c9 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#f9a2e relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#5fdc5 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a31b3 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1d766 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#a9542 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#fb9a9 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#c65a9 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#ae195 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#eea10 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#f8291 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#c1d4c NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b52a0 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#7fc00 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#f9d30 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#595bf relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#78f11 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#ef2ce relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#d1aae relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a7bd7 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#048c9 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#f9a2e relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#5fdc5 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a31b3 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1d766 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#a9542 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#fb9a9 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#c65a9 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#ae195 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#eea10 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#f8291 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#c1d4c NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b52a0 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27985): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#7fc00 NEEDS-LAYOUT NEEDS-PAINT

```

Here's the output of the command `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-IN)
    • Flutter version 1.0.0 at /Users/rkasibha/work/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rkasibha/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 3 categories.

```

**Comment by zoechi** [comment] 2018-12-30 14:52
Duplicate of #24705

**Closed by zoechi** 2018-12-30 14:52 UTC
