### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by chejdj** [flutter/flutter#103331] opened 2022-05-09 09:20 UTC
## Command
```
flutter screenshot --type=skia --observatory-url=http://127.0.0.1:55677/7xa8RMYplgA=/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2188:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:776:28)
#4      FlutterVmService.screenshotSkp (package:flutter_tools/src/vmservice.dart:937:12)
#5      ScreenshotCommand.runSkia (package:flutter_tools/src/commands/screenshot.dart:141:54)
<asynchronous suspension>
#6      ScreenshotCommand.runCommand (package:flutter_tools/src/commands/screenshot.dart:113:19)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/lingoace/environment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 周前), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lingoace/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/lingoace/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • MI PAD 4 (mobile) • 4376750 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
### Plugins
amplitude_flutter-3.8.1
appsflyer_sdk-6.5.2+2
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_calendar-216803df7f2b2da8d96e184ea341a403078890df
device_info-2.0.3
device_info_plus-3.2.3
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
file_picker-4.5.1
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_core-1.12.0
firebase_core_web-1.6.3
firebase_crashlytics-2.5.2
firebase_messaging-11.2.7
firebase_messaging_web-2.3.0
firebase_remote_config-2.0.1
firebase_remote_config_web-1.0.11
flutter_genius_scan-4.5.0
flutter_image_compress-1.1.0
flutter_native_timezone-2.0.0
flutter_pdf_printer-ba16541fe3d697c261a61e3eff623e19b06c4cd5
flutter_pdfview-1.2.2
flutter_plugin_android_lifecycle-2.0.5
lingoace_plugin_track_alpha-5d7a3ecad00d8d0a6cf78925089b2dcde9446afc
flutter_screen_wake-1.0.2
flutter_statusbarcolor-0f440ca48d6844495d6265c7dcead875e9da11a3
fluttertoast-8.0.9
heic_to_jpg-0.2.0
image_gallery_saver-1.7.1
LingoAce-LiveRoom-Android-SDK-1334203990e229b86908136b379a2fb76f3c34db
lingoace_plugin_media_picker_alpha-cb8b475779f620133c4b7535cd12c40530b61b1a
lingoace_plugin_net_alpha-bf9f6f6083141c37788ed6fa4a

**Comment by danagbemava-nc** [comment] 2022-05-09 09:29
Closing as duplicate of #101962

**Closed by danagbemava-nc** 2022-05-09 09:29 UTC
Labels: in triage
