### ISSUE TITLE
Trying to assign data from cloud store.  data in the loop prints last and expected final data prints first as NULL

### ISSUE THREAD

**Issue by shan-vm** [flutter/flutter#59244] opened 2020-06-11 07:36 UTC
**Expected results:** 
There should not be null, a full value should be printed
Cannot find a proper doc for async and use it in widget!!!

**Actual results:** 
![image](https://user-images.githubusercontent.com/6676205/84357960-1ceb8b00-abcf-11ea-9a44-8fdeb2ce0c8a.png)

**Comment by TahaTesser** [comment] 2020-06-11 12:39
Hi @shan-vm 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-11 12:39 UTC
