### ISSUE TITLE
WEB -  Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by arjun-ckpatel** [flutter/flutter#79755] opened 2021-04-05 03:25 UTC
we are using quill and Editor are working fine but when we start to deploy on web then it's getting issue.

#Issue
main.dart.js:72075 Uncaught TypeError: Cannot read property 'toString' of null

Please find Screenshot
![Screenshot from 2021-04-04 15-15-21](https://user-images.githubusercontent.com/43512427/113533874-a8b22600-95ec-11eb-85f0-aea3b92bbf3e.png)

**Comment by iapicca** [comment] 2021-04-05 07:38
@arjun-ckpatel 
 [quill](https://pub.dev/packages/quill) is a 3rd party plugin (which isn't updated in 2 years !)
 please open an issue in the dedicated [github](https://github.com/Attict/quill/issues) 
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by arjun-ckpatel** [comment] 2021-04-05 08:10
which is best HTML Editor plugin for Flutter web ?

**Comment by iapicca** [comment] 2021-04-05 09:58
> which is best HTML Editor plugin for Flutter web ?
> we are currently using Flutter quill.
> https://github.com/singerdmx/flutter-quill

@arjun-ckpatel 
you may want to ask this question on [stackoverflow](https://stackoverflow.com/tags/flutter), [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) or [slack](https://fluttercommunity.dev/joinslack)

**Comment by pedromassangocode** [comment] 2021-04-05 13:53
Hi @arjun-ckpatel 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/singerdmx/flutter-quill).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-05 13:53 UTC
Labels: in triage
