### ISSUE TITLE
Flutter randomly throws "StateError: Bad state: ImageStream has been disposed" on iOS/Android

### ISSUE THREAD

**Issue by stx** [flutter/flutter#110953] opened 2022-09-04 20:27 UTC
We upgraded to Flutter 3.3.0 and we're rarely seeing a new error on production apps with both iOS and Android users. It seems more common on Android. We've seen it be triggered when background the app, when a device is low or out of memory, and while using the app normally.

```
StateError: Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
  File "image_stream.dart", line 602, in ImageStreamCompleter._checkDisposed
  File "image_stream.dart", line 742, in ImageStreamCompleter.reportImageChunkEvent
  File "zone.dart", line 1399, in _rootRunUnary
  File "zone.dart", line 1300, in _CustomZone.runUnary
  File "zone.dart", line 1209, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 339, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 515, in _DelayedData.perform
  File "stream_impl.dart", line 620, in _PendingEvents.handleNext
  File "stream_impl.dart", line 591, in _PendingEvents.schedule.<fn>
  File "zone.dart", line 1383, in _rootRun
  File "zone.dart", line 1293, in _CustomZone.run
  File "zone.dart", line 1201, in _CustomZone.runGuarded
  File "zone.dart", line 1241, in _CustomZone.bindCallbackGuarded.<fn>
  File "zone.dart", line 1391, in _rootRun
  File "zone.dart", line 1293, in _CustomZone.run
  File "zone.dart", line 1201, in _CustomZone.runGuarded
  File "zone.dart", line 1241, in _CustomZone.bindCallbackGuarded.<fn>
  File "schedule_microtask.dart", line 40, in _microtaskLoop
  File "schedule_microtask.dart", line 49, in _startMicrotaskLoop
```

## Steps to Reproduce

We're not able to reproduce it.

<details>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.0 22A5331f darwin-arm, locale
    en-US)
    • Flutter version 3.3.0 on channel stable at
      /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 14A5228q
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 18201FDF6007XH • android-arm64  • Android 12 (API 32)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.0 22A5331f
      darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome
      104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-09-05 11:01
Hi @stx, thanks for filing the issue but there is not enough information here so we can verify the issue. 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!

**Comment by huycozy** [comment] 2022-09-13 06:56
Hi @stx 
As an issue reported recently in #111342 which the OP has given the logs from Crashlytics, it seems that trying to reproduce in the local environment is unachievable. 

Also, there was a closed issue #77576 which has been fixed before (a similar log is reported at https://github.com/flutter/flutter/issues/77576#issuecomment-795022467) but this issue is still reported on flutter `3.3.0` in this issue and `3.3.1` in #111342. 

Before labeling the issue, please help to clarify the information indicated below:
- Does your app have an image list?
- Please take a look at issue #77576 and see similarities with your case
- What was the previous version where this error did not occur?
- Please provide list affected devices from Crashlytic tool

Thank you!

**Comment by stx** [comment] 2022-09-13 08:00
> Hi @stx As an issue reported recently in #111342 which the OP has given the logs from Crashlytics, it seems that trying to reproduce in the local environment is unachievable.
> 
> Also, there was a closed issue #77576 which has been fixed before (a similar log is reported at [#77576 (comment)](https://github.com/flutter/flutter/issues/77576#issuecomment-795022467)) but this issue is still reported on flutter `3.3.0` in this issue and `3.3.1` in #111342.
> 
> Before labeling the issue, please help to clarify the information indicated below:
> 
> * Does your app have an image list?
> * Please take a look at issue [Exception has occurred when call ImageProvider.evict at state.dispose #77576](https://github.com/flutter/flutter/issues/77576) and see similarities with your case
> * What was the previous version where this error did not occur?
> * Please provide list affected devices from Crashlytic tool
> 
> Thank you!

Images in a stack and in maps (tiles). 3.0.5. Same issue as #111342. Maybe the same as #77576. We don't use evict directly but maps use CachedNetworkImage that might.

SM-S908W
iPhone14,2
iPad Air (3rd generation)
SM-G781B
etc.

**Comment by huycozy** [comment] 2022-09-13 08:21
@stx Thanks for your quick response. Labeling this issue for further investigation from the team.

**Comment by PawlikMichal25** [comment] 2022-09-26 14:08
@huycozy any update?

We're getting quite a lot of this exception right now:
<img width="1277" alt="Screenshot 2022-09-26 at 16 03 52" src="https://user-images.githubusercontent.com/15315707/192296911-31cbbdeb-745c-4f79-bbcf-08016ffaa96d.png">
and it's clearly a regression, because it never happened before in our app.

The stacktrace unfortunately doesn't say precisely where the issue is happening:
<details>
  <summary>Stacktrace</summary>
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.. Error thrown null.
       at ImageStreamCompleter._checkDisposed(image_stream.dart:602)
       at ImageStreamCompleter.reportImageChunkEvent(image_stream.dart:742)
</details>

**Comment by huycozy** [comment] 2022-09-27 02:46
Hi @PawlikMichal25 
This issue has been prioritized with p4 which means the team agrees that it is important to work on. You might want to take a look at this: [How issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)

**Comment by avinash-kanjiya** [comment] 2022-09-29 14:48
Is this issue fixed in version 3.3.3  or not?

**Comment by iapicca** [comment] 2022-09-29 16:44
> ## Steps to Reproduce
> We're not able to reproduce it.

> Is this issue fixed in version 3.3.3 or not?

@avinash-kanjiya @PawlikMichal25 
I think it would be very hard for the team to fix an issue w/o any repro code
a code sample would probably help to speed up the process

**Comment by stx** [comment] 2022-09-29 17:35
We identified that this issue was caused by CachedNetworkImage (https://pub.dev/packages/cached_network_image). We replaced our caching mechanism and the problem stopped.

**Comment by iapicca** [comment] 2022-09-29 18:12
> We identified that this issue was caused by CachedNetworkImage (https://pub.dev/packages/cached_network_image).
> 
> We replaced the caching mechanism and the production errors stopped completely.
> 
> As a result, it appears that this issue may be identical to #77576.
> 
> I suspect it may be due to the `evict()` call in this deprecated function in CachedNetworkImage:
> 
> ```
>   @Deprecated(
>       '_loadAsync is deprecated, use loadBuffer instead, see https://docs.flutter.dev/release/breaking-changes/image-provider-load-buffer')
>   Stream<ui.Codec> _loadAsync(
>     image_provider.CachedNetworkImageProvider key,
>     StreamController<ImageChunkEvent> chunkEvents,
>     DecoderCallback decode,
>   ) {
>     assert(key == this);
>     return ImageLoader().loadAsync(
>       url,
>       cacheKey,
>       chunkEvents,
>       decode,
>       cacheManager ?? DefaultCacheManager(),
>       maxHeight,
>       maxWidth,
>       headers,
>       errorListener,
>       imageRenderMethodForWeb,
>       () => PaintingBinding.instance.imageCache.evict(key),
>     );
>   }
> ```

this looks like good work, maybe would be good notify the maintainer of [cached_network_image](https://github.com/Baseflow/flutter_cached_network_image/issues)

**Comment by luisphp89** [comment] 2022-09-30 23:05
> Identificamos que esse problema foi causado por CachedNetworkImage ( https://pub.dev/packages/cached_network_image ).
> 
> Substituímos o mecanismo de cache e os erros de produção pararam completamente.
> 
> Como resultado, parece que esse problema pode ser idêntico ao #77576 .
> 
> Eu suspeito que pode ser devido à `evict()`chamada nesta função obsoleta em CachedNetworkImage:
> 
> ```
>   @Deprecated(
>       '_loadAsync is deprecated, use loadBuffer instead, see https://docs.flutter.dev/release/breaking-changes/image-provider-load-buffer')
>   Stream<ui.Codec> _loadAsync(
>     image_provider.CachedNetworkImageProvider key,
>     StreamController<ImageChunkEvent> chunkEvents,
>     DecoderCallback decode,
>   ) {
>     assert(key == this);
>     return ImageLoader().loadAsync(
>       url,
>       cacheKey,
>       chunkEvents,
>       decode,
>       cacheManager ?? DefaultCacheManager(),
>       maxHeight,
>       maxWidth,
>       headers,
>       errorListener,
>       imageRenderMethodForWeb,
>       () => PaintingBinding.instance.imageCache.evict(key),
>     );
>   }
> ```

Can you show the code you used to solve the problem?

**Comment by nerder** [comment] 2022-10-05 10:36
@stx What's the workaround you've used? Should we expect this to be fixed from Flutter or from `CachedNetworkImage`, also besides of polluting the logs, whats the actual issue that the user is facing here?

**Comment by iapicca** [comment] 2022-10-05 11:51
@huycozy are you sure it's an issue w/ flutter and not CachedNetworkImage?

**Comment by huycozy** [comment] 2022-10-06 10:30
@iapicca thanks for reminding me.

@stx Based on your findings in https://github.com/flutter/flutter/issues/110953#issuecomment-1262594872, I will close this issue since it's `CachedNetworkImage` issue as confirmed. 

I also see @PawlikMichal25 raised an issue on that repository with https://github.com/Baseflow/flutter_cached_network_image/issues/785. So, please leave there your comment and react an upvote to the original comment will help to raise the issue. 

For anyone else facing this issue without using `CachedNetworkImage`, please file a new issue so that we may verify it. Thanks!

**Closed by huycozy** 2022-10-06 10:30 UTC
Labels: severe: regression, severe: crash, framework, f: scrolling, a: images, a: production, P4, needs repro info

**Comment by dgilperez** [comment] 2022-10-06 13:00
@stx thanks for identifying this! if you could share some hint on your workaround, it would be very helpful for us

**Comment by stx** [comment] 2022-10-06 16:13
> @stx thanks for identifying this! if you could share some hint on your workaround, it would be very helpful for us

Deleting the package.

**Comment by dgilperez** [comment] 2022-10-08 13:18
Thanks for that @stx, we just followed your advice and we're a happier team now :) 

We jumped to https://github.com/fluttercandies/extended_image in case anyone is interested. We'll be testing it in prod during the following days but it seems to run nice for now.

**Comment by micohalvarez-dart** [comment] 2022-10-14 05:32
@dgilperez hi how's the https://github.com/fluttercandies/extended_image? is it causing same issue as CachedNetworkImage?

**Comment by dgilperez** [comment] 2022-10-14 05:54
Flawless so far, in terms of errors. But I didn't do any proper benchmark to compare them. It just works for us
