### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Le fichier spécifié est introuvable., errno = 2

### ISSUE THREAD

**Issue by houssam2293** [flutter/flutter#83156] opened 2021-05-22 04:02 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. updated flutter to latest version.
2. updated the version of dependencies on pubspec.yaml file.
3. run pub get.

## Logs
FileSystemException: Cannot open file, OS Error: Le fichier spécifié est introuvable.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:240:50)
<asynchronous suspension>
#9      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:130:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:163:5)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [version 10.0.19041.985], locale fr-FR)
    • Flutter version 2.0.6 at E:\Programming\flutter_windows_2.0.4-stable\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at C:/Users/houss/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • ANDROID_HOME = C:/Users/houss/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.3
    • Flutter plugin version 55.0.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\houss\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
cloud_firestore-2.2.0
cloud_firestore_web-2.1.0
firebase_auth-1.2.0
firebase_auth_web-1.1.3
firebase_core-1.2.0
firebase_core_web-1.1.0
firebase_database-6.1.2
firebase_messaging-10.0.0
firebase_messaging_web-2.0.0
flutter_local_notifications-5.0.0+4
flutter_plugin_android_lifecycle-2.0.1
fluttertoast-8.0.7
google_sign_in-5.0.3
google_sign_in_web-0.10.0
image_picker-0.7.5+2
image_picker_for_web-2.0.0
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0

**Comment by iapicca** [comment] 2021-05-22 06:57
possible duplicate of https://github.com/flutter/flutter/issues/76479

**Comment by TahaTesser** [comment] 2021-05-24 10:07
closing as a duplicate of https://github.com/flutter/flutter/issues/76479

**Closed by TahaTesser** 2021-05-24 10:07 UTC
Labels: in triage
