### ISSUE TITLE
Latest dev, windows app will hang up when switch from windows taskbar

### ISSUE THREAD

**Issue by Leadrive** [flutter/flutter#75151] opened 2021-02-01 17:11 UTC
the lastest version 1.26.0-17.1.pre
compiled windows app, after run, when switch from windows taskbar, app will hang up.

rollback to 1.26.0-12.0.pre
git reset --hard a706cd211240f27be3b61f06d70f958c7a4156fe

it will work fine.

**Comment by stuartmorgan** [comment] 2021-02-01 17:56
Duplicate of https://github.com/flutter/flutter/issues/74797

**Closed by stuartmorgan** 2021-02-01 17:56 UTC
