### ISSUE TITLE
`flutter run` isn't conservative enough in what tools it downloads

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39094] opened 2019-08-23 03:19 UTC
I ran `flutter run` to run an app on an arm64 Android phone from my x64 host. I got:

```
Downloading android-arm-profile/linux-x64 tools...                  0.4s
Downloading android-arm-release/linux-x64 tools...                  0.2s
Downloading android-arm64-profile/linux-x64 tools...                0.2s
Downloading android-arm64-release/linux-x64 tools...                0.2s
Downloading android-x86 tools...                                    1.3s
Downloading android-x64 tools...                                    1.3s
Downloading android-arm tools...                                    0.6s
Downloading android-arm-profile tools...                            0.3s
Downloading android-arm-release tools...                            0.3s
Downloading android-arm64 tools...                                  0.6s
Downloading android-arm64-profile tools...                          0.4s
Downloading android-arm64-release tools...                          0.3s
```

This seems excessive. I think it should only have downloaded `android-arm64` and `android-x64`?

**Comment by jmagman** [comment] 2020-01-09 02:58
Duplicate of https://github.com/flutter/flutter/issues/6491.

**Closed by jmagman** 2020-01-09 02:58 UTC
Labels: a: first hour, a: quality, tool
