### ISSUE TITLE
[Web][Mobile] The Container border is not drawn properly in the mobile web browser.

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [flutter/flutter#118780] opened 2023-01-19 10:19 UTC
I have deployed the flutter PWA application. **In the mobile web browser,** the container border is not drawn properly.
## Steps to Reproduce

1. Enable web by flutter config --enable-web.
2. Execute flutter build web on the code sample.
3. Deploy the application (I have deployed using the surge).
4. Open the deployed link in the mobile web browser.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: <Widget>[
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 300,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('ID'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 200,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('Name'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 300,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('DOJ'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 300,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('City'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 200,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('Salary'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 300,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('Contact No'),
            ),
            Container(
              decoration: const BoxDecoration(
                  border: Border(
                      bottom: BorderSide(width: 3.0, color: Colors.black))),
              width: 300,
              height: 100,
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: const Text('Address '),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
    • Flutter version 3.3.10 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git  
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6       
    • DevTools version 2.15.0   

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio new
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\TamilarasanParantham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.55

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

I have previously reported this issue in https://github.com/flutter/flutter/issues/107705. 

The [mentioned issue](https://github.com/flutter/flutter/issues/46339) appears to have been merged and closed. Could you please inform me if it has been released? I am still experiencing the same issue on my end.

**Comment by danagbemava-nc** [comment] 2023-01-19 13:11
Hi @Tamilarasan-Paranthaman, the issue has indeed been fixed but it is not on the stable channel yet. It is available on the `beta` and `master` channels so it should make it into the next stable release. 

I'll be closing this since it has already been fixed. If you do face this issue on the `beta` or `master` channels, kindly provide the versions on which you reproduce the issue.  

PS: You can find out which versions have the fix you're interested in by following the guide in https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F

Thank you

**Closed by danagbemava-nc** 2023-01-19 13:11 UTC
Labels: in triage
