### ISSUE TITLE
two_dimensional_scrollables 0.3.1 is throwing IconTreeShakerException

### ISSUE THREAD

**Issue by alestiago** [flutter/flutter#152603] opened 2024-07-31 07:55 UTC
### Steps to reproduce

1. Create a Flutter application for web:

```sh
flutter create my_app --platforms web
```

2. Add the two_dimensional_scrollables v0.3.1 dependency:

```sh
flutter pub add two_dimensional_scrollables:0.3.1
```

3. Update `main.dart` to import the package:

```dart
// Add the unused dependency at the top of the file
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';
```

4. Build for web:

```sh
flutter build web
```

See failure with IconTreeShakerException.

5. Use the older 0.2.1 version of two_dimensional_scrollables:

```sh
flutter pub add two_dimensional_scrollables:0.2.1
```

6. Build for web:

```sh
flutter build web
```

See no IconTreeShakerException.

### Expected results

When using the latest two_dimensional_scrollables version (currently 0.3.1) building for web should not throw an IconTreeShakerException with tree shaking enabled. Note that disabling tree shaking succeeds the build.

### Actual results

Importing two_dimensional_scrollables 0.3.1 throws a IconTreeShakerException when building for web, but using two_dimensional_scrollables 0.2.1 does not.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const SizedBox());
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter build web

Target web_release_bundle failed: IconTreeShakerException: Invalid ConstFinder result. Expected "fontPackage" to be a
String, "fontFamily" to be a String, and "codePoint" to be an int, got: {codePoint: 9658.0, fontFamily: null,
fontPackage: null, matchTextDirection: false, fontFamilyFallback: null}.

To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
#0      IconTreeShaker._parseConstFinderResult (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:333:9)
#1      IconTreeShaker._findConstants (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:321:12)
<asynchronous suspension>
#2      IconTreeShaker._getIconData (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:109:45)
<asynchronous suspension>
#3      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:178:5)
<asynchronous suspension>
#4      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:158:25)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:126:3)
<asynchronous suspension>
#7      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:450:29)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#10     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#12     WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#13     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             15.7s
Error: Failed to compile application for the Web.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-31 10:01
Hi @alestiago, it appears that this may have been fixed on the master channel. I tested on stable and was able to reproduce the issue but the build succeeds on the master channel. 

Can you confirm if this is the case for you as well? 

PS: I think this may be an issue with the web tree shaking rather than the package as the build worked as expected for me on the stable channel with `android`, `macOS` & `iOS`

**Comment by alestiago** [comment] 2024-07-31 10:59
> Can you confirm if this is the case for you as well?

Switched to master and it seems to be working as expected, but not in stable.

Flutter doctor output:
```command
[✓] Flutter (Channel master, 3.23.0-14.0.pre.62, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2024-08-01 06:32
Hi @alestiago, thanks for confirming that this has been fixed on the master channel. I also just checked on the `beta` channel and this works as expected there as well so the fix will likely be in the next stable version. 

Per our triage policy, I'll be closing this since it has been fixed on the beta & master channels. 

Thank you

**Closed by danagbemava-nc** 2024-08-01 06:32 UTC
Labels: package, in triage
