### ISSUE TITLE
[Web] Regression in Master - PDF display distorted due to change in BMP Encoder

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#93615] opened 2021-11-14 10:08 UTC
Hi,

I noticed in our test environment that pdf rendering is broken on a very recent release in master. It was working fine in `2.4`, `2.5.3`, `2.8.0-3.1.pre`, `2.6.0-12.0.pre.662`, `2.6.0-12.0.pre.670` and so far narrowed it down that it was broken in `2.6.0-12.0.pre.674`, `2.6.0-12.0.pre.678`, `2.6.0-12.0.pre.696` and latest `master 2.6.0-12.0.pre.718`, can you please have a look and advise?

## Steps to reproduce
1. Clone the sample provided
2. Run it on web

| Normal | PDF distorted colours and rotated | 
| -- | -- |
| ![image](https://user-images.githubusercontent.com/81489824/141676089-7102b043-a558-408e-b275-55e65fb0a299.png) | ![image](https://user-images.githubusercontent.com/81489824/141674763-d03671ec-e12f-4134-b87c-f904eaa875cf.png) |

This repo I previously created for another problem represents the issue:
https://github.com/zambetpentru/flutter_88688_video_overwriting_widget

<details> 
<summary>flutter doctor</summary> 

```console
[√] Flutter (Channel master, 2.6.0-12.0.pre.718, on Microsoft Windows [Version 10.0.17763.2300], locale en-IE)
    • Flutter version 2.6.0-12.0.pre.718 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3d889b4e4b (16 hours ago), 2021-11-13 23:46:03 +0600
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.50

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2021-11-15 08:09
Hi @zambetpentru, what are the steps to reproduce?

**Comment by zambetpentru** [comment] 2021-11-15 08:26
Hi, 

Download and run the repo (it is a project with a single dart file) on the latest master and it should show the issue but not on the latest Beta or Stable.

**Comment by danagbemava-nc** [comment] 2021-11-15 09:22
Issue is reproducible on `master` but not on `dev`, `beta`, or `stable`. 

Issue persists with both `html` and `canvaskit` renderers.

<details>
<summary>screenshots</summary>

| stable,dev, beta | master | 
| -- | -- | 
|  <img width="763" alt="Screenshot 2021-11-15 at 08 50 56" src="https://user-images.githubusercontent.com/88313112/141752238-4b101d60-2ff8-4ae7-b9a8-33531b039077.png"> | <img width="736" alt="Screenshot 2021-11-15 at 08 53 19" src="https://user-images.githubusercontent.com/88313112/141752302-e74648aa-c511-473b-b649-4f70dad0cefc.png"> | 
</details>

<details>
<summary> flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.719, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.719 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 34dbee66de (9 hours ago), 2021-11-14 18:46:02 -0500
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-11.0.pre at /Users/nexus/dev/sdks/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (8 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.8.0-3.1.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0-3.1.pre at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3dab555040 (3 days ago), 2021-11-12 11:50:00 -0800
    • Engine revision 09f1520e8b
    • Dart version 2.15.0 (build 2.15.0-268.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by yjbanov** [comment] 2021-11-18 19:16
Can you please provide a repro case without the dependency on flutter_pdf_render? This way we'll know where exactly in Flutter the bug is. Otherwise, the bug may be in Flutter or in flutter_pdf_render.

**Comment by zambetpentru** [comment] 2021-11-18 19:46
Hi, I haven't come across another scenario where I have seen a similar issue unfortunately. I can say that I've been using a fixed version of pdf_render (1.08) since March (Note: not flutter_pdf_render) and has been stable throughout until changed on the Flutter side in that commit. Maybe the package author @espresso3389 can posit an alternative way to reproduce the issue.

**Comment by espresso3389** [comment] 2021-11-19 07:25
@zambetpentru 
I've created a minimum repro that works differently on the latest master and 2.6.0-12.0.pre.670 (858a328712):

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter #93615',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter #93615'),
        ),
        body: Container(
          color: Colors.black,
          child: Center(
            child: FutureBuilder<ui.Image>(
                future: createTestImage(),
                builder: (context, snapshot) =>
                    snapshot.hasData ? RawImage(image: snapshot.data) : const Text('No data loaded.')),
          ),
        ),
      ),
    );
  }
}

Future<ui.Image> createTestImage() async {
  const width = 256;
  const height = 256;
  final data = Uint8List(width * height * 4);
  // 2.6.0-12.0.pre.670 (858a328712): RGBA => Red fill
  // latest master                  : BGRA => Blue fill
  for (int i = 0; i < data.length; i += 4) {
    data[i] = 0xff;
    data[i + 1] = 0;
    data[i + 2] = 0;
    data[i + 3] = 0xff; // A
  }

  // white pixel
  // 2.6.0-12.0.pre.670 (858a328712): bottom-left
  // latest master                  : top-left
  data[0] = data[1] = data[2] = 0xff;

  final descriptor = ui.ImageDescriptor.raw(
    await ui.ImmutableBuffer.fromUint8List(data),
    width: width,
    height: height,
    pixelFormat: ui.PixelFormat.bgra8888,
  );
  final codec = await descriptor.instantiateCodec();
  final frame = await codec.getNextFrame();
  return frame.image;
}
```

**Comment by espresso3389** [comment] 2021-11-19 08:19
I think `PixelFormat.bgra8888` considered to accept `BGRA` byte array but on the older versions, it actually implemented to interpret input data as `RGBA`.

The current behavior on the latest master seems "correct" behavior according to its name althouth it is completely different behavior to the older ones.

And, the image is anyway vertically flipped. So the image should be bottom-up?

**Comment by espresso3389** [comment] 2021-11-19 08:30
It seems to be a duplicate of #89610.

**Comment by espresso3389** [comment] 2021-11-19 08:40
Is this the cause of the issue? Just 9 days ago.
https://github.com/flutter/engine/commit/64a9a1a06acb7008d814c025e7f85f7d72895360

**Comment by espresso3389** [comment] 2021-11-19 08:56
Just a guess, but the lines are not correct:
https://github.com/flutter/engine/blob/64a9a1a06acb7008d814c025e7f85f7d72895360/lib/web_ui/lib/src/ui/painting.dart#L563

**Comment by yjbanov** [comment] 2021-12-02 19:22
Classifying this as a new feature. We never meant Flutter content to be rendered as PDF. It only worked by accident. If we support this, we need a proper design and a testing strategy. As of right now, we cannot make any guarantees that it will work.

**Comment by ditman** [comment] 2021-12-02 19:39
@yjbanov I think this is attempting to do the opposite, converting each PDF page into an `ImageDescriptor.raw` so it can be rendered in a Flutter app. Check this example without any PDF logic:

* https://github.com/flutter/flutter/issues/93615#issuecomment-973820194

And an analysis here:

* https://github.com/flutter/flutter/issues/93615#issuecomment-973855483

Looks like a legit image rendering bug/platform difference (especially the vertical flipping, AFAIK there's no EXIF property that can result in *mirroring* an image).

**Comment by zambetpentru** [comment] 2021-12-02 21:10
Exactly I think the next step is to confirm what is the correct flutter behaviour for this image decoding, the historic or the current behaviour, and based on that we will know if the pdf_render plugin or Flutter needs to adapt.

**Comment by zambetpentru** [comment] 2021-12-14 18:37
Greetings @dkwingsmt, could you give us some insight into why the BMP Encoder array was reversed as part of https://github.com/flutter/engine/commit/64a9a1a06acb7008d814c025e7f85f7d72895360 ? 

I have a solution to fix the plugin issue referenced in this ticket, I'd just like to understand what the background of the change was around the decision to invert it.

**Comment by dkwingsmt** [comment] 2021-12-14 19:23
I'm sorry that it has caused such disturbance! The reason is to comply with BMP standard. 

The pixel stream in Flutter is defined as in RGB order, row first, and starts from the top left corner. However, by default (the way Flutter used to be coded) BMP is in a BGR order starting from the bottom left.

> origin, which indicates the direction in which the bits fill in the bitmap. It always contains 0, meaning the origin is the lower-left corner. Bits fill in from left-to-right and bottom-to-top. This field, however, is not the only thing that determines the origin of the image. Windows bitmaps do not use this field (the Windows structures stop after resolutionUnits). Windows bitmaps may be stored with an upper-left origin, indicated by storing a negative value for the image's height.

```
typedef struct RGB
{
  UINT8 blue;
  UINT8 green;
  UINT8 red;
} RGB;
```

https://www.drdobbs.com/architecture-and-design/the-bmp-file-format-part-1/184409517

Since it's so breaking, I probably should make it a flag instead of "fixing" it. What do you think?

**Comment by dkwingsmt** [comment] 2021-12-14 21:57
Thank you for the reply! 

I think it's always possible to make it an optional flag (say, `ui.PixelOrigin`). What I'm not sure is which pixel order to default to.
* Considering the change was breaking, it should be reasonable to make `PixelOrigin.bottomLeft` the default option so that nothing is broken.
* However, it seems to me that this is a behavioral discrepancy between Web and desktop (desktop is already originating from the top-left? Correct me if I'm wrong.) So it would make sense to make `PixelOrigin.topLeft` the default option.

**Comment by espresso3389** [comment] 2021-12-14 22:07
I understand the background of the change. And it's relatively easy to update the code to conform to the new behavior. So all we need is the documentation of the behavial change.

For my own package, [pdf_render](https://pub.dev/packages/pdf_render), I added [a workaround for the issue](https://pub.dev/packages/pdf_render/versions/1.0.18#rendering-breakage-on-recent-flutter-web) already.

**Comment by espresso3389** [comment] 2021-12-14 22:11
@zambetpentru I think we can close the issue now.

**Comment by dkwingsmt** [comment] 2021-12-14 22:11
Sure! I'll file a PR to add such an option.

**Comment by zambetpentru** [comment] 2021-12-14 22:22
Thanks @dkwingsmt , it sounds like the default for a flag should be like it is today to fix the old issue so that Desktop and Web are consistent.  

Cheers all!

**Closed** 2021-12-14 22:22 UTC
Labels: severe: new feature, severe: regression, platform-web, severe: rendering, has reproducible steps, P5, found in release: 2.6

**Comment by dkwingsmt** [comment] 2021-12-15 02:38
On a second thought, I'm a little confused on what I need to do. 

@espresso3389 @zambetpentru 

If I understand correctly, with my previous PR, `bgra8888` and `rgba8888` are now swapped, and the images are upside-down. But if your libraries/apps encapsulate file reading, parsing, and rendering, then all you need to do is to flip the pixel format option and the image data stream. Not saying I'm free of charges, but if I were to add a flag of, say, `bool useOldRawBehavior` which defaults to `false`, then you will have to modify your code to turn it on, then you could've just updated your other code.

Now, it becomes more complicated if the library needs the same data stream to work correctly for Flutter for Web both pre- and post-change, but again, if we're sticking with the new option as default, the only thing that will help is a way to detect whether the behavior has been made. 

So I think what I can do is:

1. Provide an easier way to flip the image upside-down.
2. Write a migration guide. 
3. Suggest a way to detect the current behavior kind.

For item 3, my plan is to call `decodeImageFromPixels` on a single-pixel image and test its result. The result will be asynchronous, obviously. 

What do you think?

**Comment by zambetpentru** [comment] 2021-12-15 10:07
Hi @dkwingsmt,

I would update the documentation (maybe I missed where it is) to define the structure of the Flutter pixel buffer (i.e. origin top left) on a page like this: https://api.flutter.dev/flutter/dart-ui/ImageDescriptor/ImageDescriptor.raw.html

Apart from that as you said the client code will have to change in any case, in our case for the PDF the problem has already been resolved. So since this is a framework bug fix I wouldn't do anything else on your side? :-)

**Comment by dkwingsmt** [comment] 2021-12-15 10:08
Yes I will. Thank you for your kind feedback!
