### ISSUE TITLE
ImageFiltered creates a padding around the SliverAppBar

### ISSUE THREAD

**Issue by bsfdeep** [flutter/flutter#71566] opened 2020-12-02 14:38 UTC
## Steps to Reproduce

1. Create a `SliverAppBar` with a `Stack` in the `flexibleSpace` that contains an image.
2. Wrap the image with an `ImageFiltered` widget and set `SigmaX` and `SigmaY` of `ImageFiltered.blur` to be anything greater than 0.
3. Notice the padding (the blue background seen) around the app bar.

**Actual results:** 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/73177989/100884055-766fab00-34ca-11eb-9ff5-09d0d5fac751.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/73177989/100887385-5a6e0880-34ce-11eb-9d5b-fccb24d56e59.png">

With SigmaX and SigmaY = 5

<img width="435" alt="image" src="https://user-images.githubusercontent.com/73177989/100886572-702efe00-34cd-11eb-85ec-f6b2df6c9993.png">

```
flexibleSpace: Stack(
                children: [
                  Positioned.fill(
                    child: ImageFiltered(
                      imageFilter: ImageFilter.blur(
                        sigmaX: 2,
                        sigmaY: 2,
                      ),
                      child: Image.asset(
                        'assets/images/CoverPicture.jpg',
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                ],
              ),
```

Any idea how can I stop it from shrinking the app bar?

<details>
  <summary>Logs</summary>

```
```

```
```

Flutter Doctor

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2020-12-02 15:46
Hi @bsfdeep 
I can reproduce the issue but this is not related to SliverAppBar, I don't believe this is a padding, it's just making edges translucent or shadow


### Preview
### Inside SliverAppBar
![Simulator Screen Shot - iPhone 12 - 2020-12-02 at 21 04 41](https://user-images.githubusercontent.com/48603081/100895200-4d0f4900-34e3-11eb-9f18-a3f2b83f0273.png)

### Scaffold Body
![Simulator Screen Shot - iPhone 12 - 2020-12-02 at 21 12 11](https://user-images.githubusercontent.com/48603081/100895279-5f898280-34e3-11eb-9b31-18948d702dcd.png)





<details> 
<summary>code sample</summary> 

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // body: CustomScrollView(
      //   slivers: [
      //     SliverAppBar(
      //       pinned: true,
      //       backgroundColor: Colors.red,
      //       collapsedHeight: 250,
      //       flexibleSpace: Stack(
      //         children: [
      //           Positioned.fill(
      //             child: ImageFiltered(
      //               imageFilter: ImageFilter.blur(
      //                 sigmaX: 10,
      //                 sigmaY: 10,
      //               ),
      //               child: Image.network(
      //                 'https://i.imgur.com/9OrBvmZ.jpg',
      //                 fit: BoxFit.cover,
      //               ),
      //             ),
      //           ),
      //         ],
      //       ),
      //     ),
      //     SliverFillRemaining()
      //   ],
      // ),

      body: Container(
        color: Colors.red,
        child: Stack(
          children: [
            Positioned.fill(
              child: ImageFiltered(
                imageFilter: ImageFilter.blur(
                  sigmaX: 10,
                  sigmaY: 10,
                ),
                child: Image.network(
                  'https://i.imgur.com/9OrBvmZ.jpg',
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

 duplicate of https://github.com/flutter/flutter/issues/39623
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

CC: @flar

**Closed by TahaTesser** 2020-12-02 15:46 UTC
