### ISSUE TITLE
[BUG] TextOverFlow.elipsis not working as inteded for google fonts.

### ISSUE THREAD

**Issue by AryashDubey** [flutter/flutter#79596] opened 2021-04-01 22:28 UTC
Describe the bug
I am using dmSans for my flutter web app but the textoverflow.elipsis is showing a ugly square in the end. This problem occurs only when using google fonts in a flutter web application and also this issue ONLY HAPPENS WITH CANVASKIT RENDERER.
To Reproduce

Use google fonts DM Sans in flutter web and make the text overflow
Use the Canvas Kit Renderer to run the app (IMPORTANT)
Expected behavior
Expected Behaviour should be ----> Signature...

Screenshots
![Screenshot 2021-04-01 014640](https://user-images.githubusercontent.com/70095055/113360605-bacf6280-9367-11eb-81ec-bdb04da59c67.png)

**Comment by iapicca** [comment] 2021-04-02 06:13
@AryashDubey 
can you provide your `flutter doctor -v`, your `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment] 2021-04-05 08:36
Hi @AryashDubey 
Can you please provide what was asked above?
Thank you

**Comment by AryashDubey** [comment] 2021-04-05 17:00
Here is my flutter doctor -v 

[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!


Here is my output of  flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v


[  +78 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +70 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[        ] 2.0.3
[  +40 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +75 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +13 ms] Skipping pub get: version match.
[  +42 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +7 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[ +111 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +4 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[  +27 ms] Generating C:\Users\HP\fontbug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +74 ms] List of devices attached
[  +54 ms] Launching lib\main.dart on Chrome in debug mode...
[   +9 ms] List of devices attached
[ +108 ms] Updating assets
[  +92 ms] Waiting for connection from debug service on Chrome...
[  +22 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[  +35 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[  +57 ms] <- reset
[   +9 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill 
C:\Users\HP\AppData\Local\Temp\flutter_tools.5a637980\flutter_tool.607f9832\app.dill --libraries-spec file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages  
C:\Users\HP\fontbug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\HP\AppData\Local\Temp\flutter_tools.5a637980\flutter_tools.f64155a7 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety       
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+19300 ms] Waiting for connection from debug service on Chrome... (completed in 19.4s)
[   +1 ms] Synced 34.7MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[ +163 ms] Using Opening in existing browser session.

[ +186 ms] [CHROME]:
[   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:58001/devtools/browser/646f3b71-dd1b-40b2-bd12-fbad31227e67
[+1181 ms] DwdsInjector: Received request for entrypoint at http://localhost:57969/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +10 ms] MetadataProvider: Loaded debug metadata
[   +9 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:57969/main_module.bootstrap.js
[+7466 ms] DevHandler: Debug service listening on ws://127.0.0.1:58041/ay0IGdV2NRI=/ws
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[+578464 ms] DevHandler: Stopped debug service on ws://127.0.0.1:58039
[   +5 ms] "flutter run" took 608,207ms.




Here is the issue with minimal code :-    https://github.com/AryashDubey/Font-Bug

**Comment by pedromassangocode** [comment] 2021-04-06 06:53
I'm able to reproduce this however, this is a duplicate of https://github.com/flutter/flutter/issues/76473. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-04-06 06:53 UTC
Labels: in triage
