### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException : io.flutter.embedding.engine.FlutterJNI.loadLibrary 

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#102873] opened 2022-04-30 10:53 UTC
## Steps to Reproduce

I can't reproduce it but i got the crash report from my production app on a Nexus 5 under Android 8.1.0.

![Capture d’écran 2022-04-30 à 12 52 58](https://user-images.githubusercontent.com/32631467/166102530-56073a3e-7b58-468c-9e78-40c15d398bf4.png)

Here is the stack trace : 

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.listeen.android/com.listeen.android.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.listeen.android/com.listeen.android.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.RuntimeException
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

Caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:369)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:184)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:12)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:106)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:7)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:13)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.util.concurrent.ExecutionException
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:28)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:184)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:12)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:106)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:7)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:13)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.listeen.android-k3oPYn-pYEjTq9tygEhsCQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:13)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:18)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Expected results:** 

The app should not crash. 

**Actual results:** 

The app is crashing.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale fr-FR)
    • Flutter version 2.10.5 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-05-02 06:44
Closing this as duplicate of https://github.com/flutter/flutter/issues/83596

**Closed by darshankawar** 2022-05-02 06:44 UTC
Labels: in triage
