### ISSUE TITLE
Downloaded executables cannot execute on host -- Breadcrumbs PLEASE

### ISSUE THREAD

**Issue by Enigmanomalous** [flutter/flutter#14998] opened 2018-02-28 23:33 UTC
### After several days ...
I started with a fresh install of Linux Mint 18.3 Cinnamon 64-bit

Made sure that it was fully updated and that all the command-line tools required were there (bash, mkdir, rm, git, curl, unzip, which)

Followed the instructions to install flutter and ran flutter doctor
	-git clone -b beta https://github.com/flutter/flutter.git
	-export PATH=`pwd`/flutter/bin:$PATH
	-flutter doctor
This was the result:

timberlane@TMBR ~ $ flutter doctor --verbose
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.UTF-8)
    • Flutter version 0.1.5 at /home/timberlane/flutter
    • Framework revision 3ea4d06340 (6 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

! Doctor found issues in 3 categories.
-------------------------------------------------------
Experience has taught me to resolve the first error that occurs as subsequent errors are likely to be the result of the first one. So my focus has been on:
	✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

I have scoured all the available bug reports for some clue as to what is causing this error and have gone down many rabbit-holes because of them. Unfortunately #6207 is misleading beyond its initial “Solution” which indirectly leads back to the required command-line tools availability.

Before anyone jumps to the conclusion that I have not attempted all the obvious steps like setting all the permissions and the possibility that resolving the subsequent errors (e.g.: ✗ Unable to locate Android SDK.) are at the root of this issue. I have attempted all that and much more ... to the extent of reformatting the hard drive and reinstalling the OS to eliminate any possibility of some random configuration conflict.

The issue here is simple. This is the kind of error that could be caused by many variables and there is no means by which to track down the specifics on the individual machine in question. I am confident that _flutter doctor_ is doing its job, I just have no idea what it is!

What I need are some breadcrumbs left by _flutter doctor_ that will give some clue as to what it was trying to do when it decided to through this error. If it was a permissions problem it would be easy to see where to resolve it, if it was some missing file, it would be easy to seek out the file, etc.

What about a log ???
Or if there is one somewhere, how about its location being prominently posted so I could go look at it?

I apologize if I have missed some solution here, I have searched for several days and attempted every imaginable fix. This seems to be a rather common error but with no clear solution or troubleshooting path.

Thank you in advance,
TMBR

**Comment by cbracken** [comment] 2018-03-01 00:30
@Enigmanomalous I'm not familiar with the 32-bit standard library packages for Linux mint, but since it's within the family of Debian Linux distros, does `sudo apt-get install lib32stdc++6` resolve this for you?

Unfortunately the exact install instructions will vary depending on Linux distro / package ecosystem for that distro, but I suspect that emitting commands for Debian, Fedora and maybe Arch might get us decent coverage.

**Comment by Enigmanomalous** [comment] 2018-03-01 01:43
@cbracken I very much appriecate your suggestion. But once again it assumes the underlying issue has something to do with a particular file (namely lib32stdc++6), which may in fact be the problem; in a specific instance.
My hope is that, as you suggest, flutter doctor would be made to emit some relevant info to troubleshoot the specifics.

**update:** As I was about to attempt to install the file lib32stdc++6 as you suggested, I ran flutter doctor again for the baseline. The subject error is now gone!!!
No explanation -- The only thing that I have worked on in the interim is installing Android Studio which was and is still in process of Downloading Components.

How, or why this effected a resolution is **MAGIC!** 
Maybe, someone out there will help us look behind the curtain , for the benefit of all those who follow in our adventurous path.

**Comment by cbracken** [comment] 2018-03-01 01:51
The specific issue in this case is that a test run of the 32-bit AOT compiler fails. Unfortunately, this isn't likely to mean much to most new Flutter developers, so I'm not sure that providing more detailed information (other than a link to the bug) is too helpful.

The most likely cause of that is a lack of 32-bit libraries installed on the system. In order to reduce issues filed for the most common cause, I'm landing #15004, which is a very lazy first-run at improving the error message with something a bit more actionable, but still retains the bug link as a fallback.

> As I was about to attempt to install the file lib32stdc++6 as you suggested, I ran flutter doctor again for the baseline. The subject error is now gone!!!

Android Studio also relies on the 32-bit libraries, so installing it was likely the cause for the error message going away.

> Maybe, someone out there will help us look behind the curtain , for the benefit of all those who follow in our adventurous path.

If what you're after is the actual check we run, here's the bit where it's implemented:
https://github.com/cbracken/flutter/blob/e83de0bd5f9d060d06b404dcd466f55f2ace70f7/packages/flutter_tools/lib/src/doctor.dart#L240-L255

**Comment by cbracken** [comment] 2018-03-01 01:55
Closing since #15004 should produce more actionable results, but happy to continue the discussion and/or hear any thoughts you've got on how we could improve the error reporting on this issue.

**Closed by cbracken** 2018-03-01 01:55 UTC

**Comment by paratout** [comment] 2018-03-01 15:40
Just happened with me, the install of lib32stdc++6 fixed it.

**Comment by JakeRed** [comment] 2018-09-05 04:32
macOS exec "brew install lib32stdc ++ 6" display：
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
yangmindeMacBook-Air:~ yimutian$ brew install lib32stdc++6
Error: No available formula with the name "lib32stdc++6" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Can you give me a hint?

**Comment by cbracken** [comment] 2018-09-05 19:14
@JakeRed based on your reply on #6207 it sounds like [my reply](https://github.com/flutter/flutter/issues/6207#issuecomment-418595627) there solved your problem. Glad to hear it!

**Comment by whataa** [comment] 2018-09-27 02:31
I just ran `flutter upgrade`, it executed `flutter doctor` after downloading,  then this issue happened with me. But when I ran `flutter doctor` again, this error is gone. I don't know why.

```
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (3 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.5 17F77, locale en-CN)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected devices
    ! No devices available

! Doctor found issues in 4 categories.
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.5 17F77, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment] 2018-09-27 06:07
@whataa did you try the suggestion from the comment just above yours?
