### ISSUE TITLE
using firebase_core: D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

### ISSUE THREAD

**Issue by Atominac** [flutter/flutter#27464] opened 2019-02-03 13:11 UTC

**Comment by Atominac** [comment] 2019-02-03 13:33
adding to this
error is only there when using both
image_picker:
firebase_core:

both works well separately.

**Comment by redvg** [comment] 2019-02-04 22:01
im having exactly the same, image_picker + firebase_core

**Comment by redvg** [comment] 2019-02-04 23:01
solved by downgrading to image_picker: ^0.4.12 as per #27194

**Comment by zoechi** [comment] 2019-02-07 10:19
Duplicate of #27194

**Closed by zoechi** 2019-02-07 10:19 UTC

**Comment by michelengelen** [comment] 2019-10-25 12:16
For anyone still experiencing it even with all those fixes applied:

I did fix it by updating the Gradle version in `<your-app>/android/gradle/wrapper/gradle-wrapper.properties` from `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

After that all builds run smoothly
