### ISSUE TITLE
Augmented Reality With Flutter

### ISSUE THREAD

**Issue by shubham8170** [flutter/flutter#75919] opened 2021-02-12 17:53 UTC
I am trying to develop an AR application but I face with many issues like how to create those 3D models, we can use unity for it, but can we develop the whole app without unity? There is some demo project on GitHub but this is not sufficient,

**Comment by iapicca** [comment] 2021-02-13 09:15
possible duplicate of https://github.com/flutter/flutter/issues/18509

**Comment by darshankawar** [comment] 2021-02-15 07:03
@shubham8170 
Check out [this](https://flutter.dev/docs/resources/faq#can-i-build-3d-opengl-apps-with-flutter) link to know about Flutter's support for 3D models.  You may also checkout [this](https://pub.dev/packages/arkit_plugin) plugin and [this](https://medium.com/codechai/flutter-and-ar-a65bb202c5d8) article for reference.

Closing from here for now.

**Closed by darshankawar** 2021-02-15 07:03 UTC
