### ISSUE TITLE
warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated (url_launcher)

### ISSUE THREAD

**Issue by 3mrdev** [flutter/flutter#56269] opened 2020-05-04 07:13 UTC
###  Steps to Reproduce

1. Run app or build app with -Xlint:deprecation for details.

**Expected results:** 
No warnings 

**Actual results:** 

```
C:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java:42: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
                       ^
C:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java:47: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
          return super.shouldOverrideUrlLoading(view, url);
                      ^
2 warnings
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\Android\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\sdk\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\sdk\sdk\platform-tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\Amr Abd Alkrim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • G8 • 1090308019017967 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment] 2020-05-04 09:53
duplicate of [#37616](https://github.com/flutter/flutter/issues/37616) [comment](https://github.com/flutter/flutter/issues/37616#issuecomment-522613577)

**Closed by TahaTesser** 2020-05-04 09:53 UTC
