### ISSUE TITLE
[go_router] Remove navigatorBuilder

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#108145] opened 2022-07-21 23:52 UTC
Once new route types are added to support nested routing (https://github.com/flutter/flutter/issues/108141) we can deprecate navigatorBuilder and recommend ShellRoute instead.

**Comment by ahmednfwela** [comment] 2022-07-27 02:31
the issue is pointing to itself, I think the correct one is  https://github.com/flutter/flutter/issues/108141 ?

**Comment by chunhtai** [comment] 2022-08-03 21:25
blocked on https://github.com/flutter/flutter/issues/108141

**Comment by chunhtai** [comment] 2022-08-22 18:50
merged into feature branch. check https://github.com/flutter/flutter/issues/108044 for progress

**Closed by chunhtai** 2022-08-22 18:50 UTC
Labels: P4, p: go_router
