### ISSUE TITLE
Samsung Galaxy S10 System Navigation Bar Icon Brightness Issue

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#39132] opened 2019-08-23 18:36 UTC
I'm testing on my Samsung Galaxy S10 device and the code works once and when I close and reopen the app, the navigation bar has all of its icons white. To get the navigation bar icons to go dark again, I have to hit the green refresh button in VS Code while in debug mode. Then, the navbar icons turn dark until I close the app and reopen it. However, if I force stop it, the icons turn dark which is what I want but I'm worried that when I build my app that if a user just leaves the app for a second and comes back, their navigation bar would be all messed up and they wouldn't be able to see the buttons. I just want to be able to know why this happens and find a way to fix it.

Expected Result:
![expected result](https://user-images.githubusercontent.com/25782944/63615180-bac78800-c5b2-11e9-94c9-456f6512a8ff.jpg)
Actual Result:
![actual result](https://user-images.githubusercontent.com/25782944/63615225-d0d54880-c5b2-11e9-8433-15f9ee4fc055.jpg)

Code:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark));
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'School Life',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.white,
      ),
      appBar: AppBar(
        iconTheme: IconThemeData(color: Colors.black),
        backgroundColor: Colors.white,
        brightness: Brightness.light,
        elevation: 0,
        centerTitle: true,
        title: Text("Home",
            style: TextStyle(
                color: Colors.black,
                fontFamily: 'OpenSans',
                fontWeight: FontWeight.w600)),
      ),
      drawer: CustomDrawer(),
    );
  }
}
```
Cmd: flutter doctor -v
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Owner\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Owner\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • SM G973U • R38M20KGKPK • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Levi-Lesches** [comment] 2019-08-25 20:22
Just did a bit of research, check [this](https://stackoverflow.com/questions/52489458/how-to-change-status-bar-color-in-flutter) out. Also, apparently setting `AppBar.brightness` can do the trick.

**Comment by EcoGames** [comment] 2019-08-25 23:08
Did you see my code? I've tried everything.

**Comment by Levi-Lesches** [comment] 2019-08-25 23:40
Right, I see that now. From your description, it seems like a call to `build` solves your problem. If you put a print statement in your `build` function, does it call after closing and re-opening your app (ie, when the problem starts)?

**Comment by Levi-Lesches** [comment] 2019-08-25 23:45
See [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) for how exactly to hook up a `setState` to an app startup. I believe you are interested specifically in [`WidgetsBindingObserver.didChangeAppLifeCycleState`](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html) when `state` is [`AppLifeCycleState.resumed`](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html)

**Comment by EcoGames** [comment] 2019-08-26 00:52
Thanks for your help! That seemed to work.

**Comment by Levi-Lesches** [comment] 2019-08-26 00:55
Glad to help!

**Comment by Reprevise** [comment] 2020-02-16 20:59
I'm reopening the issue because the cause of this seems to be the `AppBar`. Without the `AppBar`, the issue with the white status bar icons goes away when I relaunch the app.

**Comment by Levi-Lesches** [comment] 2020-02-16 21:07
So... did the `WidgetsBindingObserver` thing not work? Or are you saying that the cause of the issue should be fixed?

**Comment by Reprevise** [comment] 2020-02-16 21:15
Well I have two projects, one where I don't use an `AppBar` or `WidgetsBindingObserver` and it works fine and the one I'm currently working on uses an `AppBar` and the navigation buttons turn white on the white theme. I was using `WidgetsBindingObserver` which worked okay-ish but I refactored my project two months ago and decided to get rid of it. Both projects use the exact same code to change theme and the only difference is the `AppBar` not being on the pages.

**Comment by Levi-Lesches** [comment] 2020-02-16 21:40
> I was using `WidgetsBindingObserver` which worked okay-ish

Mind elaborating? That might give more clues on what the core issue is here.

**Comment by Reprevise** [comment] 2020-02-16 21:47
`WidgetsBindingObserver` worked fine for my case as on resume, it changed the navigation bar color, but it's not necessary and plus my implementation of it wasn't so good as every widget had to be a `StatefulWidget` (atleast how I did it inside of `initState`) since it had to be on every page so no matter which page the user left on, it would work. The real issue is why the `AppBar` has such an impact on the system navigation bar.

**Comment by Levi-Lesches** [comment] 2020-02-16 22:27
Could it be this? 
> ```dart
> appBar: AppBar(
>   iconTheme: IconThemeData(color: Colors.black),
>   backgroundColor: Colors.white,
>   brightness: Brightness.light,  // over here
>   // ...
> ```

**Comment by Reprevise** [comment] 2020-02-16 22:29
That code is old, but no it's not, I've tried both brightness' and got the same result. I thought the same thing at first.

**Comment by inceptusp** [comment] 2020-04-08 17:07
I am trying to change my navigation bar color, but the icons is not matching the defined brightness... No matter what brightness I define, the icons stick with a black color (when the system is in Dark Mode) or a white color (when the system is in Light Mode)... My device is a Samsung Galaxy J6... I've tried all options presented in [this](https://stackoverflow.com/questions/52489458/how-to-change-status-bar-color-in-flutter) stackoverflow thread and nothing works... The background color changes, but I'm still getting this problem with the icons...

**Comment by darshankawar** [comment] 2020-08-06 13:29
Hi @Reprevise,
Can you confirm if you still experience this issue on latest Flutter version (eg: dev, stable, master) ?
Thanks.

**Comment by Reprevise** [comment] 2020-08-07 14:16
I'm on the latest stable (1.20.1) and I still experience the issue.

Here's a minimally reproducible sample:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ));

    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}
```

# Steps

1. Launch app, icon brightness is dark while the navigation color is white.
2. Go to phone's home screen
3. Re-launch app
4. The navigation bar color remains white, however the icon brightness is light making it nearly impossible to see the icons.

This has something to do with the app not rebuilding when the app is relaunched shortly after being closed which is probably intentional however, this makes setting the icon brightness of a navigation bar difficult.

# Workaround

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ));
    }
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ));

    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}
```

By taking advantage of the `WidgetsBindingObserver`, we can observe when the app resumes and set the navigation bar accordingly however, apply this to every screen in the app is in my opinion, verbose.

**Comment by darshankawar** [comment] 2020-09-15 12:25
Issue replicable on latest master. the bottom bar icon colors change when coming back from home screen.

![39132](https://user-images.githubusercontent.com/67046386/93210080-a4bbd500-f77c-11ea-826e-55166369f435.png)


<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.22.0-10.0.pre.174 • channel master • https://github.com/flutter/flutter.git
Framework • revision 37b03ec2c2 (4 hours ago) • 2020-09-14 23:52:04 -0400
Engine • revision 7e962ba911
Tools • Dart 2.10.0 (build 2.10.0-124.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.174, on Mac OS X 10.15.4 19E2269, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-03-27 11:21
I verified this issue using code sample provided [above](https://github.com/flutter/flutter/issues/39132#issuecomment-670539477) running on latest stable version with Samsung S10 device, with which I wasn't able to replicate the reported error.
I'll optimistically close this as not reproducible and also the fact that there have not been any activity recently.
If anybody still thinks this is an issue on latest version, please file a new issue with relevant details so that we can address it properly.

**Closed by darshankawar** 2024-03-27 11:21 UTC
Labels: e: device-specific, platform-android, framework, engine, a: quality, has reproducible steps, P2, found in release: 1.21, found in release: 1.22, team-android, triaged-android
