### ISSUE TITLE
[image_picker] iOS image capturing issue

### ISSUE THREAD

**Issue by RahulAlchemy** [flutter/flutter#95555] opened 2021-12-20 10:55 UTC
![File](https://user-images.githubusercontent.com/88880822/146755766-22693e5a-9ccb-41c8-a1ee-79b61a68351a.jpg)

After capturing image if we click any of the white area  above and below of the use photo button its sending user to home screen.
this issue only happens in IOS device.

I'm not able to find what's the issue .

**Comment by darshankawar** [comment] 2021-12-20 13:21
@RahulAlchemy 
Provide `flutter doctor -v`, image_picker version and a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior you are facing.
Thanks.

**Comment by RahulAlchemy** [comment] 2021-12-21 04:44
`flutter doctor -v`
 Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1055], locale en-IN)
    • Flutter version 2.5.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 months ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\admin01\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

  `image_picker: ^0.8.4+4`  this is  version i have used in my project.


This is code where i used image picker
 
       
           Future<File?> showPickerBottomSheet(context) async {
                       File? file;
                 final ImagePicker _picker = ImagePicker();
               if (Platform.isIOS) {
                 bool isDrawerOpen = false;
                await showiOSActionSheet(context,
                    message: "Select Option",
                    firstTitle: AppLocalizations.of(context).photoLibrary,
                    secondTitle: AppLocalizations.of(context).camera,
                   firstCallBack: () async {
                            if (!isDrawerOpen) {
                              isDrawerOpen = true;
                              file = await _imgFromGallery(_picker);
                              isDrawerOpen = false;
                              Navigator.of(context).pop();
                            }
                        }, secondCallBack: () async {
                          if (!isDrawerOpen) {
                            isDrawerOpen = true;
                            file = await _imgFromCamera(_picker);
                            isDrawerOpen = false;
                            Navigator.of(context).pop();
                          }
                          }, cancelCallBack: () {
                            if (!isDrawerOpen) {
                              Navigator.pop(context);
                            }
                          });
                  return file;
                } else
                  await showModalBottomSheet(
                      context: context,
                      builder: (BuildContext bc) {
                        return SafeArea(
                          child: Container(
                            child: new Wrap(
                              children: <Widget>[
                                new ListTile(
                                    leading: new Icon(
                                      Icons.photo_library,
                                      color: AppColors.white,
                                    ),
                                    title: new Text(AppLocalizations.of(context).photoLibrary,
                                        style: Styles.airbnbCerealAppMedium
                                            .copyWith(fontSize: 14.sp)),
                                    tileColor: AppColors.eerieBlack,
                                    onTap: () async {
                                      file = await _imgFromGallery(_picker);
                                      Navigator.of(context).pop();
                                    }),
                                new ListTile(
                                  leading:
                                      new Icon(Icons.photo_camera, color: AppColors.white),
                                  title: new Text(AppLocalizations.of(context).camera,
                                      style: Styles.airbnbCerealAppMedium
                                          .copyWith(fontSize: 14.sp)),
                                  tileColor: AppColors.eerieBlack,
                                  onTap: () async {
                                    file = await _imgFromCamera(_picker);
                                    Navigator.of(context).pop();
                                  },
                                ),
                              ],
                            ),
                          ),
                        );
                      });
                return file;
                // }
              }

          // This method return captured image file and I'm facing issue in camera only
            Future<File?> _imgFromCamera(ImagePicker _picker) async {
              XFile? cameraImage =
                  (await _picker.pickImage(source: ImageSource.camera, imageQuality: 50));
              if (cameraImage != null) {
                return File(cameraImage.path);
              } else
                return null;
            }


         // This method return seletected image file 
          Future<File?> _imgFromGallery(ImagePicker _picker) async {
            XFile? galleryImage =
                (await _picker.pickImage(source: ImageSource.gallery, imageQuality: 50));
            if (galleryImage != null) {
              return File(galleryImage.path);
            } else
              return null;
}

**Comment by darshankawar** [comment] 2021-12-21 05:30
> After capturing image if we click any of the white area above and below of the use photo button its sending user to home screen.

This is happening due to a general problem in Flutter engine and isn't specific to image_picker plugin. You'll need to follow-up in [this](https://github.com/flutter/flutter/issues/14720) issue for further updates on this.
Closing this as a duplicate.

**Closed by darshankawar** 2021-12-21 05:30 UTC
Labels: in triage
