### ISSUE TITLE
DatePicker issues: IconButton tap targets do not work on the whole icon button, no way to set custom inner padding

### ISSUE THREAD

**Issue by Ax0elz** [flutter/flutter#129751] opened 2023-06-29 05:02 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a datepicker in M3 with showDatePick:

```
    final res = await showDatePicker(
                      context: context,
                      firstDate: DateTime.now().subtract(
                        const Duration(days: 365 * 99),
                      ),
                      initialDate: DateTime.now().subtract(
                        const Duration(days: 365 * 18),
                      ),
                      lastDate: DateTime.now().subtract(
                        const Duration(days: 365 * 16),
                      ),
                      builder: (context, child) {
                        return Align(
                          child: Column(
                            children: [
                              Flexible(child: child!),
                            ],
                          ),
                        );
                      },
                    );
```
Open Date Picker

### Expected results

- Icon Buttons are clickable
- Year toggle splash is adjustable, both border radius and size
- Inner padding of the whole date picker is adjustable

### Actual results

- Icons buttons do not work unless the very edge is clicked
- Year/Month toggle click area is not symmetric and cannot be adjusted
- Inner padding of the date picker is not adjustable

### Code sample

<details><summary>Code sample</summary>

```dart
    final res = await showDatePicker(
                      context: context,
                      firstDate: DateTime.now().subtract(
                        const Duration(days: 365 * 99),
                      ),
                      initialDate: DateTime.now().subtract(
                        const Duration(days: 365 * 18),
                      ),
                      lastDate: DateTime.now().subtract(
                        const Duration(days: 365 * 16),
                      ),
                      builder: (context, child) {
                        return Align(
                          child: Column(
                            children: [
                              Flexible(child: child!),
                            ],
                          ),
                        );
                      },
                    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/50639765/bf94bad1-82c1-4ab2-98e6-16a84126b415

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-06-29 10:22
Hi @Ax0elz. Thanks for filing this issue. I'm unable to reproduce the first issue on web, mobile and desktop. Can you provide more info on how I can reproduce this?
As regards the other two issues, these seem to be similar to this currently open proposal https://github.com/flutter/flutter/issues/93707

**Comment by Ax0elz** [comment] 2023-06-29 16:46
Looks like #93707 has some of the requests but does not seems to address the need for theme to have padding, and the ability to change the splash area for the toggle for the year selection.

As fast as the reproduction for the tap area for IconButton in the date picker I am not sure what would be different than the standard datePicker as seen in the attached video.

I do have some theme changes that might have some cause.
I change the tooltip theme:
```
  tooltipTheme: TooltipThemeData(
      decoration: BoxDecoration(
        color: baseTheme.colorScheme.secondaryContainer,
        borderRadius: BorderRadius.circular(borderRadius),
      ),
      textStyle: baseTheme.textTheme.bodyMedium,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      margin: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      showDuration: const Duration(milliseconds: 2500),
      waitDuration: const Duration(milliseconds: 500),
      triggerMode: TooltipTriggerMode.tap,
    ),
```

for IconButton:
```
 iconButtonTheme: IconButtonThemeData(
      style: buttonStyle.copyWith(
        shape: MaterialStateProperty.all(
          const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(8)),
          ),
        ),
        visualDensity: VisualDensity.compact,
        iconColor: MaterialStateProperty.all(
          baseTheme.colorScheme.primary,
        ),
        iconSize: MaterialStateProperty.all(20),
        backgroundColor: MaterialStateProperty.all(
          Colors.transparent,
        ),
        foregroundColor: MaterialStateProperty.all(baseTheme.colorScheme.outline.withOpacity(.5)),
        overlayColor: MaterialStateProperty.all(baseTheme.colorScheme.outline
            .withOpacity(baseTheme.brightness == Brightness.dark ? .2 : .5)),
        padding: MaterialStateProperty.all(EdgeInsets.zero),
        alignment: Alignment.center,
      ),
    ),
```

and the datePick theme:
```
   datePickerTheme: DatePickerThemeData(
      surfaceTintColor: baseTheme.colorScheme.surface,
      backgroundColor: baseTheme.colorScheme.surface,
      rangePickerSurfaceTintColor: Colors.transparent,
      rangePickerBackgroundColor: baseTheme.colorScheme.surface,
      yearStyle: baseTheme.textTheme.bodyMedium,
      dayStyle: baseTheme.textTheme.bodyMedium,
      headerHelpStyle: baseTheme.textTheme.bodyMedium,
      rangePickerHeaderHelpStyle: baseTheme.textTheme.bodyMedium,
      headerHeadlineStyle: baseTheme.textTheme.bodyMedium!.copyWith(fontSize: 25),
      rangePickerHeaderHeadlineStyle: baseTheme.textTheme.bodyMedium!.copyWith(fontSize: 25),
      weekdayStyle: baseTheme.textTheme.labelLarge!.copyWith(fontWeight: FontWeight.bold),
      shadowColor: Colors.white,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(borderRadius),
      ),
      elevation: 0,
    ),
```

Wondering if any of this would affect that tap area. There is a possibility the tooltip trigger mode interfaces maybe?

**Comment by dam-ease** [comment] 2023-06-30 08:34
Hi @Ax0elz. Thanks for the detailed explanation. I am able to reproduce this on the latest flutter `stable` channel using the code sample below. The issue seems to have been caused by `TooltipTriggerMode.tap` in the `TooltipThemeData` which seems to have been fixed on the latest `master` channel. Kindly switch to the latest `master` to confirm this issue no longer persists.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        tooltipTheme: const TooltipThemeData(
          padding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          margin: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
          showDuration: Duration(milliseconds: 2500),
          waitDuration: Duration(milliseconds: 500),
          triggerMode: TooltipTriggerMode.tap,
        ),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () async {
            await showDatePicker(
              context: context,
              firstDate: DateTime.now().subtract(
                const Duration(days: 365 * 99),
              ),
              initialDate: DateTime.now().subtract(
                const Duration(days: 365 * 18),
              ),
              lastDate: DateTime.now().subtract(
                const Duration(days: 365 * 16),
              ),
              builder: (context, child) {
                return Align(
                  child: Column(
                    children: [
                      Flexible(child: child!),
                    ],
                  ),
                );
              },
            );
          },
          child: const Text(
            "TEST",
            style: TextStyle(fontSize: 10),
          ),
        ),
      ),
    );
  }
}

``` 

</p>
</details>  

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.5 on channel stable at /Users/dammya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

```
[✓] Flutter (Channel master, 3.12.0-13.0.pre.19, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.12.0-13.0.pre.19 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b8595629b (2 hours ago), 2023-06-30 02:29:24 -0400
    • Engine revision 099a70ebbc
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

``` 

</p>
</details>

**Comment by Ax0elz** [comment] 2023-07-05 17:28
@dam-ease Yes looks like it is solved in master. Thanks :)

**Comment by darshankawar** [comment] 2023-07-06 05:49
Closing as fixed on master and based on above comment.

**Closed by darshankawar** 2023-07-06 05:49 UTC
Labels: in triage
