### ISSUE TITLE
Where do I find out what a Sliver is?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10242] opened 2017-05-21 21:03 UTC
@fablue asked on Gitter what a Sliver is.  I assumed maybe it might be explained in one of the Sliver class docs, but I don't see it?

https://docs.flutter.io/flutter/widgets/SliverList-class.html
https://docs.flutter.io/flutter/material/SliverAppBar-class.html
https://docs.flutter.io/flutter/material/SliverGrid-class.html

Maybe it should go in RenderSliver?
https://docs.flutter.io/flutter/rendering/RenderSliver-class.html
Except that one doesn't seem to have any class-level docs.

Is Sliver a term from Material?  @Hixie

**Comment by Hixie** [comment] 2017-05-21 21:06
dupe of https://github.com/flutter/flutter/issues/9737

**Closed by Hixie** 2017-05-21 21:06 UTC
Labels: dev: docs - api
