### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by AtharvMixraw** [flutter/flutter#155878] opened 2024-09-28 10:02 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
Open the terminal or command prompt.
Navigate to your Flutter project directory using cd /path/to/your/project.
Run the flutter run command.

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-IN)
    [32m•[39m Flutter version 3.24.3 on channel stable at /Users/aditimish

**Comment by danagbemava-nc** [comment] 2024-09-30 06:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903, parent issue in https://github.com/flutter/flutter/issues/153471.

If you have a reliable way to let us reproduce this, kindly leave a comment in the parent issue.

Thank you

**Closed by danagbemava-nc** 2024-09-30 06:54 UTC
Labels: in triage
