### ISSUE TITLE
Flutter , Visual Code Analyzer never finishing after update

### ISSUE THREAD

**Issue by merdo988** [flutter/flutter#39464] opened 2019-08-29 05:21 UTC
![ss1](https://user-images.githubusercontent.com/6937664/63912616-2176f680-ca36-11e9-96fe-b410670434be.png)
After update dart extension analyzer never ending.So , autocomplete and other things does not work.How can i fix that ? 

Launch Json : 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

Flutter Version : 1.6.6

**Comment by BondarenkoStas** [comment] 2019-08-29 11:41
Please provide ```flutter doctor -v output```. May it be possible that you opened vscode while Dart was still upgrading? Is it so only on the specific project? Can you provide your VSCode version and dart extension version? Did you tried to reinstall dart and flutter extensions? 
More info is needed to investigate the issue.

**Comment by merdo988** [comment] 2019-08-29 18:52
@BondarenkoStas Here is the flutter doctor -v output ss
![docker](https://user-images.githubusercontent.com/6937664/63968003-4788af00-caa7-11e9-80be-2b68c7c63edf.png)

**Comment by merdo988** [comment] 2019-08-29 18:57
I tried different project the some issues in all projects

**Comment by BondarenkoStas** [comment] 2019-08-30 07:47
@merdo988 I opened your project having the same versions of VS Code, flutter extension etc, but couldn't reproduce the issue. I would be hard to investigate without having exact steps to reproduce. Anyway, keeping it open. Please asks for help in StackOverflow as well or check https://flutter.dev/community for support options, probably the issue is not related to flutter itself but to your custom configuration.

**Comment by BondarenkoStas** [comment] 2019-09-03 16:54
@merdo988 are there any updates about your issue?

**Comment by iapicca** [comment] 2019-11-14 16:10
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-14 16:10 UTC
Labels: waiting for customer response
