### ISSUE TITLE
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string

### ISSUE THREAD

**Issue by chrizmichels** [flutter/flutter#146908] opened 2024-04-17 16:53 UTC
### Steps to reproduce

I got his crash log in my console:

 ⚠️ Result: {author: null, date: 2024-09-04T14:59:00.000Z, description: ������������� ����� �� ����������� ��������� ��
��������� ������� ���� ����� � ���� �������� �� �������������� �� ����������. ���� ����� �� ����� �� ���������, ����� �� ������� �� 8 ����� (����������).��������� �� ����� ���������� �� �������������
������� �� ��, ���� ���� �� � ������������ ����� � ������� ���., image: https://basketball.bg/pictures/pic_big/gallery/BFB/BFB-logo.jpg, logo: null, title: �� ������� ���� ����� � ���� �������� ��
�������������� �� �� ���������, url: http://basketball.bg/news.php?g=20&id=18020}
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[27, 91, 51, 56, 59, 53, 59, 50, 48, 56, 109, 226, 148, 130, 32, 226, 154, 160, 239, 184, 143, 32, 82, 101, 115, 117, 108, 116, 58, 32, 123, 97, 117, 116, 104, 111, 114, 58, 32, 110, 117, 108, 108, 44,
32, 100, 97, 116, 101, 58, 32, 50, 48, 50, 52, 45, 48, 57, 45, 48, 52, 84, 49, 52, 58, 53, 57, 58, 48, 48, 46, 48, 48, 48, 90, 44, 32, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 58, 32, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189,
239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 46, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 44, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 56, 32, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 239, 191, 189, 32, 40, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 41,
46, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239,
191, 189, 44, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191,
189, 239, 191, 189, 239, 191, 189, 46, 44, 32, 105, 109, 97, 103, 101, 58, 32, 104, 116, 116, 112, 115, 58, 47, 47, 98, 97, 115, 107, 101, 116, 98, 97, 108, 108, 46, 98, 103, 47, 112, 105, 99, 116, 117,
114, 101, 115, 47, 112, 105, 99, 95, 98, 105, 103, 47, 103, 97, 108, 108, 101, 114, 121, 47, 66, 70, 66, 47, 66, 70, 66, 45, 108, 111, 103, 111, 46, 106, 112, 103, 44, 32, 108, 111, 103, 111, 58, 32,
110, 117, 108, 108, 44, 32, 116, 105, 116, 108, 101, 58, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189,
32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32,
239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189,
44, 32, 117, 114, 108, 58, 32, 104, 116, 116, 112, 58, 47, 47, 98, 97, 115, 107, 101, 116, 98, 97, 108, 108, 46, 98, 103, 47, 110, 101, 119, 115, 46, 112, 104, 112, 63, 103, 61, 50, 48, 38, 105, 100,
61, 49, 56, 48, 50, 48, 125, 27, 91, 48, 109, 10]

I just scrolled through a result list of a data stream from firebase. Then the App suddenly crashed with the above log. It look like the crash happens when I call a firebase cloud function to extract the metadata of the url.

### Expected results

Application loads List View without crashing.

### Actual results

Application crashes

### Code sample

<details open><summary>Code sample</summary>

```dart
  final HttpsCallable callable =
        FirebaseFunctions.instance.httpsCallable('extractMetaData');
    final result = await callable.call({'url': url});

    if (result.data != null) {
      AppLogger.warning('Result: ${result.data}');
      return result.data as Map<String, dynamic>;
    } else {
      AppLogger.warning('Cloud Function did not return data');
      return null;
    }
    
    exports.extractMetaData = functions.https.onCall(async (data, context) => {
  const url = data.url;

  const result = await callUrlMetaScraper(url);

  if (result.error) {
    console.error(`Error fetching metadata for ${url}:`, result.error);
    return { error: result.error };
  }

  return result;

});

async function callUrlMetaScraper(data) {
    let result;

    try {
        const getContent = async url => {
          const promise = fetchHTML(url);
          await promise;

          return promise;
        };

        result = await getContent(data).then(html => metascraper({ html, url: data }));
      
    } catch (error) {
        console.error('Error in callUrlMetaScraper:', error.message);
        throw new functions.https.HttpsError('internal', 'Error in callUrlMetaDataScraper', error.message);
    }

    return result;
}

const metascraper = require('metascraper')([
      require('metascraper-author')(),
      require('metascraper-date')(),
      require('metascraper-description')(),
      require('metascraper-image')(),
      require('metascraper-logo')(),
      require('metascraper-title')(),
      require('metascraper-url')()
    ]);


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Here a screenshot of my list view and the data in firebase. I could not reproduce the crash.

[Upload media here]
![Screenshot 2024-04-17 at 18 42 47](https://github.com/flutter/flutter/assets/722728/dd3e97a0-705b-4409-8325-3619245995d4)
![Screenshot 2024-04-17 at 18 43 44](https://github.com/flutter/flutter/assets/722728/bf75770e-dc49-492e-b5a0-4325a1ff9b73)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: │ ⚠️ Result: {author: null, date: 2024-09-04T14:59:00.000Z, description: ������������� ����� �� ����������� ��������� ��
��������� ������� ���� ����� � ���� �������� �� �������������� �� ����������. ���� ����� �� ����� �� ���������, ����� �� ������� �� 8 ����� (����������).��������� �� ����� ���������� �� �������������
������� �� ��, ���� ���� �� � ������������ ����� � ������� ���., image: https://basketball.bg/pictures/pic_big/gallery/BFB/BFB-logo.jpg, logo: null, title: �� ������� ���� ����� � ���� �������� ��
�������������� �� �� ���������, url: http://basketball.bg/news.php?g=20&id=18020}
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[27, 91, 51, 56, 59, 53, 59, 50, 48, 56, 109, 226, 148, 130, 32, 226, 154, 160, 239, 184, 143, 32, 82, 101, 115, 117, 108, 116, 58, 32, 123, 97, 117, 116, 104, 111, 114, 58, 32, 110, 117, 108, 108, 44,
32, 100, 97, 116, 101, 58, 32, 50, 48, 50, 52, 45, 48, 57, 45, 48, 52, 84, 49, 52, 58, 53, 57, 58, 48, 48, 46, 48, 48, 48, 90, 44, 32, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 58, 32, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189,
239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 46, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 44, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239,
191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 56, 32, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 239, 191, 189, 32, 40, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 41,
46, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191,
189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239,
191, 189, 44, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191,
189, 239, 191, 189, 239, 191, 189, 46, 44, 32, 105, 109, 97, 103, 101, 58, 32, 104, 116, 116, 112, 115, 58, 47, 47, 98, 97, 115, 107, 101, 116, 98, 97, 108, 108, 46, 98, 103, 47, 112, 105, 99, 116, 117,
114, 101, 115, 47, 112, 105, 99, 95, 98, 105, 103, 47, 103, 97, 108, 108, 101, 114, 121, 47, 66, 70, 66, 47, 66, 70, 66, 45, 108, 111, 103, 111, 46, 106, 112, 103, 44, 32, 108, 111, 103, 111, 58, 32,
110, 117, 108, 108, 44, 32, 116, 105, 116, 108, 101, 58, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189,
32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239,
191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189,
239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 32,
239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 32, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189,
44, 32, 117, 114, 108, 58, 32, 104, 116, 116, 112, 58, 47, 47, 98, 97, 115, 107, 101, 116, 98, 97, 108, 108, 46, 98, 103, 47, 110, 101, 119, 115, 46, 112, 104, 112, 63, 103, 61, 50, 48, 38, 105, 100,
61, 49, 56, 48, 50, 48, 125, 27, 91, 48, 109, 10]

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
→ flutter doctor                                                                                                                                                                                [bb7c948]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-18 06:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137025. Kindly subcribe to the original issue for updates.

**Closed by danagbemava-nc** 2024-04-18 06:58 UTC
Labels: in triage
