### ISSUE TITLE
EditableTextState: The method 'findRenderObject' was called on null.

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#33730] opened 2019-06-02 16:49 UTC
Internal: b/138107141

## Steps to Reproduce

I am seeing this in Crashlytics and it comes from one of my user's devices, hence I don't know how to reproduce it.

## Logs

```
The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()

When the exception was thrown, this was the stack:
#0      EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:1352)
#1      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126)
#2      AnimationController.set:value (package:flutter/src/animation/animation_controller.dart:351)
#3      EditableTextState._stopCursorTimer (package:flutter/src/widgets/editable_text.dart:1300)
#4      EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:887)
#5      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:728)
#7      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:717)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383)
#10     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:380)
#11     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:351)
#12     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76)
#14     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67)
#15     _invoke3.<anonymous closure> (dart:ui/hooks.dart:264)
#19     _invoke3 (dart:ui/hooks.dart:263)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:136)
(elided 6 frames from package dart:async and package dart:async-patch)

The AnimationController notifying listeners was:
 AnimationController#cdd3c(⏮ 0.000; paused)
```

**Comment by yrom** [comment] 2019-08-29 06:13
I have same issue here, and it seems only occurred on iOS device

flutter version info:
```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (6 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

## logs
```
NoSuchMethodError: The method 'findRenderObject' was called on null. Receiver: null Tried calling: findRenderObject()

0 #0 EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:1465)
1 #1 _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124)
2 #2 AnimationController.set:value (package:flutter/src/animation/animation_controller.dart:362)
3 #3 EditableTextState._startCursorTimer (package:flutter/src/widgets/editable_text.dart:1392)
4 #4 EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:976)
5 #5 _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:743)
6 #6 _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49)
7 #7 _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:732)
8 #8 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397)
9 #9 _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49)
10 #10 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:394)
11 #11 MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365)
12 #12 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110)
13 #13 _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49)
14 #14 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:101)
15 #15 _invoke3.<anonymous closure> (dart:ui/hooks.dart:280)
16 #16 _rootRun (dart:async/zone.dart:1124)
17 #17 _CustomZone.run (dart:async/zone.dart:1021)
18 #18 _CustomZone.runGuarded (dart:async/zone.dart:923)
19 #19 _invoke3 (dart:ui/hooks.dart:279)
20 #20 _dispatchPlatformMessage (dart:ui/hooks.dart:141)


```

**Comment by ericwindmill** [comment] 2019-10-08 15:22
I am also seeing this issue. I'm using an Android emulator. 

strangely, it was working fine yesterday. I changed no code. Just got to work and fired it up. 

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AutoCompleteTextField<LineItem>(dirty, state: AutoCompleteTextFieldState<LineItem>#d05ed):
The getter 'size' was called on null.
Receiver: null
Tried calling: size

User-created ancestor of the error-causing widget was: 
  Container file:///Users/ericwindmill/greenbits/herer-flutter/herer/lib/screens/create_order/remove_item_dialog/information_panel.dart:52:28
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AutoCompleteTextFieldState.build (package:herer/ui_theme/input_widgets/text_input_auto_suggest/auto_suggest_text_field.dart:224:74)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
```

```
@override
  Widget build(BuildContext context) {
    final Size textFieldSize = (context.findRenderObject() as RenderBox).size;
```

**Comment by fightingLT** [comment] 2019-10-16 03:48
I have same issue too
flutter doctor log:
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.0)

error stackTrace:
{
	"event_id": "7e0fcaf331224c9eacf1fdbdd1214b4a",
	"project": 1452950,
	"release": null,
	"dist": null,
	"platform": "other",
	"message": "",
	"datetime": "2019-10-16T01:44:30.000000Z",
	"time_spent": null,
	"tags": [
		["level", "error"],
		["logger", "SentryClient"]
	],
	"_meta": {
		"platform": {
			"": {
				"val": "dart"
			}
		},
		"exception": {
			"values": {
				"0": {
					"stacktrace": {
						"frames": {
							"0": {
								"function": {
									"": {
										"len": 367,
										"rem": [
											["!limit", "s", 253, 256]
										]
									}
								}
							}
						}
					}
				}
			}
		}
	},
	"culprit": "unparsed in {userId: 5da6710f17440e49c646ecb1, app_version: 0.0.29, errorLog: #0      EditableTextState._getScrollOffsetForCaret (package:flutter/src/widgets/editable_text.dart:1631)",
	"exception": {
		"values": [{
			"stacktrace": {
				"frames": [{
					"function": ", deviceInfo: {name: iPhonexs, systemName: iOS, systemVersion: 12.4.1, model: iPhone, localizedModel: iPhone, identifierForVendor: 993F4E9A-F796-4F34-89D0-B9FBCFF0C45E, utsname: {sysname: Darwin, nodename: iPhonexs, release: 18.7.0, version: Darwin Kern...",
					"abs_path": "unparsed",
					"in_app": true,
					"filename": "unparsed"
				}, {
					"function": "_drawFrame",
					"abs_path": "dart:ui/hooks.dart",
					"in_app": false,
					"lineno": 207,
					"filename": "hooks.dart"
				}, {
					"function": "_invoke",
					"abs_path": "dart:ui/hooks.dart",
					"in_app": false,
					"lineno": 249,
					"filename": "hooks.dart"
				}, {
					"function": "_CustomZone.runGuarded",
					"abs_path": "dart:async/zone.dart",
					"in_app": false,
					"lineno": 923,
					"filename": "zone.dart"
				}, {
					"function": "_CustomZone.run",
					"abs_path": "dart:async/zone.dart",
					"in_app": false,
					"lineno": 1021,
					"filename": "zone.dart"
				}, {
					"function": "_rootRun",
					"abs_path": "dart:async/zone.dart",
					"in_app": false,
					"lineno": 1124,
					"filename": "zone.dart"
				}, {
					"function": "SchedulerBinding._handleDrawFrame",
					"abs_path": "package:flutter/src/scheduler/binding.dart",
					"in_app": true,
					"lineno": 891,
					"filename": "binding.dart"
				}, {
					"function": "SchedulerBinding.handleDrawFrame",
					"abs_path": "package:flutter/src/scheduler/binding.dart",
					"in_app": true,
					"lineno": 983,
					"filename": "binding.dart"
				}, {
					"function": "SchedulerBinding._invokeFrameCallback",
					"abs_path": "package:flutter/src/scheduler/binding.dart",
					"in_app": true,
					"lineno": 1033,
					"filename": "binding.dart"
				}, {
					"function": "EditableTextState._showCaretOnScreen.<fn>",
					"abs_path": "package:flutter/src/widgets/editable_text.dart",
					"in_app": true,
					"lineno": 1438,
					"filename": "editable_text.dart"
				}, {
					"function": "{userId: 5da6710f17440e49c646ecb1, app_version: 0.0.29, errorLog: #0      EditableTextState._getScrollOffsetForCaret (package:flutter/src/widgets/editable_text.dart:1631)",
					"abs_path": "unparsed",
					"in_app": true,
					"filename": "unparsed"
				}]
			},
			"type": "NoSuchMethodError",
			"value": "NoSuchMethodError: The method 'findRenderObject' was called on null.\nReceiver: null\nTried calling: findRenderObject()"
		}]
	},
	"fingerprint": ["{{ default }}"],
	"grouping_config": {
		"enhancements": "eJybzDhxY05qemJypZWRgaGlroGxrqHRBABbEwcC",
		"id": "legacy:2019-03-12"
	},
	"hashes": ["6bfea5b82c4bcb4af8be7efe3b386d55", "afaf34d0b66469feb63f11422d11ca07"],
	"key_id": "830689",
	"level": "error",
	"location": "unparsed",
	"logger": "SentryClient",
	"metadata": {
		"function": "{userId: 5da6710f17440e49c646ecb1, app_version: 0.0.29, errorLog: #0      EditableTextState._getScrollOffsetForCaret (package:flutter/src/widgets/editable_text.dart:1631)",
		"type": "NoSuchMethodError",
		"value": "NoSuchMethodError: The method 'findRenderObject' was called on null.\nReceiver: null\nTried calling: findRenderObject()",
		"filename": "unparsed"
	},
	"received": 1571190271.707,
	"sdk": {
		"version": "2.2.0",
		"name": "dart"
	},
	"timestamp": 1571190270.0,
	"title": "NoSuchMethodError: NoSuchMethodError: The method 'findRenderObject' was called on null.",
	"type": "error",
	"version": "6"
}

This problem is happening frequently, I hope to fix it as soon as possible, thank you

**Comment by Jinxishihenian** [comment] 2019-12-26 03:39
I ran into the same problem. FindRenderObject was called null, but anchorKey was already created.
Error log:
The method 'findRenderObject' was called on null.
Receiver: null
═ ═ ═ ═ ═ ═ ═ ═ (398) Exception caught by gesture ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═ ═
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject ();

**Comment by gitfornncn** [comment] 2020-02-06 15:34
Same  problem. Use WidgetsBinding.instance.addPostFrameCallback still got errors


════════ Exception caught by scheduler library ═════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()

**Comment by zhouliuji99** [comment] 2020-03-24 02:33
Same problem  。“#0 EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:1631)”。）
***[Message: Framework ERROR - NoSuchMethodError: The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()]

**Comment by chunhtai** [comment] 2020-05-28 23:28
Would also be good to share the code that receive this error message but not reproducible locally

**Comment by LongCatIsLooong** [comment] 2020-06-30 22:20
After looking into the code I still can't think of a possible scenario where `renderEditable` can be null. Maybe this exception is just a side effect of another exception (for example https://github.com/flutter/flutter/issues/49989) that prevented `_Editable` from being built. Let's see if fixing #49989 stops this from happening.

**Comment by LongCatIsLooong** [comment] 2020-08-11 22:36
I'm going to close this issue as there's no more crashes with similar stack traces reported since #60956 (https://github.com/flutter/flutter/commit/a6ce2d4bc7490916a022e6a05af75a6ad0852e8d, please note it's not in the 1.20 release). Please let me know if you're still experiencing this on master

**Comment by mikeesouth** [comment] 2021-01-22 12:56
Not sure if this is the same issue but I want to raise it here and see if I should create a new issue or if this should be reopened. I'm receiving the exact same error as the original poster but I also get a couple of another, very related, errors. 

I'm using flutter stable, currently version 1.22.5. Just like the original poster I haven't reproduced this myself but my users have sent error reports. I've received it both from Android and iOS devices and I have three similar error reports, all three are related to EditTextState and "The method 'findRenderObject' was called on null". The three reports are as follow (the first one is identical with the original poster):

1. [iOS] EditableTextState._onCursorColorTick - NoSuchMethodError: The method 'findRenderObject' was called on null
2. [iOS] EditableTextState._showCaretOnScreen.<anonymous closure> - NoSuchMethodError: The method 'findRenderObject' was called on null
3. [Android] EditableTextState.renderEditable - NoSuchMethodError: The method 'findRenderObject' was called on null

All of these reference the same source file and the same line: package:flutter/src/widgets/editable_text.dart:2307
Also note that error 3 is is also coming from _onCursorColorTick, it's the second line in the stack traces

The stack traces for 1 and 3 are very similar. Here are the stack traces (in order):
```
#0 EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:2307)
#1 AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:136)
#2 AnimationController.value= (package:flutter/src/animation/animation_controller.dart:367)
#3 EditableTextState._stopCursorTimer (package:flutter/src/widgets/editable_text.dart:2244)
#4 EditableTextState._startOrStopCursorTimerIfNeeded (package:flutter/src/widgets/editable_text.dart:2252)
#5 EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:2267)
#6 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226)
#7 FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1027)
#8 FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1723)
#9 _rootRun (dart:async/zone.dart:1182)
#10 _CustomZone.run (dart:async/zone.dart:1093)
#11 _CustomZone.runGuarded (dart:async/zone.dart:997)
#12 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037)
#13 _rootRun (dart:async/zone.dart:1190)
#14 _CustomZone.run (dart:async/zone.dart:1093)
#15 _CustomZone.runGuarded (dart:async/zone.dart:997)
#16 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037)
#17 _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

```
#0 EditableTextState._showCaretOnScreen. (package:flutter/src/widgets/editable_text.dart:2307)
#1 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117)
#2 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063)
#3 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971)
#4 _rootRun (dart:async/zone.dart:1190)
#5 _CustomZone.run (dart:async/zone.dart:1093)
#6 _CustomZone.runGuarded (dart:async/zone.dart:997)
#7 _invoke (dart:ui/hooks.dart:251)
#8 _drawFrame (dart:ui/hooks.dart:209)
```

```
#0 EditableTextState.renderEditable package:flutter/src/widgets/editable_text.dart:2307
#1 EditableTextState._onCursorColorTick package:flutter/src/widgets/editable_text.dart:2118
#2 AnimationLocalListenersMixin.notifyListeners package:flutter/src/animation/listener_helpers.dart:136
#3 AnimationController.value= package:flutter/src/animation/animation_controller.dart:367
#4 EditableTextState._stopCursorTimer package:flutter/src/widgets/editable_text.dart:2237
#5 EditableTextState._startOrStopCursorTimerIfNeeded package:flutter/src/widgets/editable_text.dart:2252
#6 EditableTextState._handleFocusChanged package:flutter/src/widgets/editable_text.dart:2267
#7 ChangeNotifier.notifyListeners package:flutter/src/foundation/change_notifier.dart:226
#8 FocusNode._notify package:flutter/src/widgets/focus_manager.dart:1027
#9 FocusManager._applyFocusChange package:flutter/src/widgets/focus_manager.dart:1723
dart:async/zone.dart:1182
#11 _CustomZone.run dart:async/zone.dart:1093
#12 _CustomZone.runGuarded dart:async/zone.dart:997
#13 _CustomZone.bindCallbackGuarded.<anonymous closure> dart:async/zone.dart:1037
dart:async/zone.dart:1190
#15 _CustomZone.run dart:async/zone.dart:1093
#16 _CustomZone.runGuarded dart:async/zone.dart:997
#17 _CustomZone.bindCallbackGuarded.<anonymous closure> dart:async/zone.dart:1037
dart:async/schedule_microtask.dart:41
dart:async/schedule_microtask.dart:50
```

**Comment by LongCatIsLooong** [comment] 2021-02-09 20:02
There's likely something else that prevented the `_Editable` subtree from being properly inflated, that would have been caught by existing asserts. Hopefully with NNBD this will stop happening or it will generate more informative crash reports. I'll keep the issue open probably until the next stable release.

**Comment by LongCatIsLooong** [comment] 2021-06-08 02:17
Looks like the crash stops happening.

**Closed by LongCatIsLooong** 2021-06-08 02:17 UTC
Labels: a: text input, customer: mulligan (g3), framework, passed first triage, platform-ios, severe: crash
