### ISSUE TITLE
Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'FlutterEngineRun'

### ISSUE THREAD

**Issue by daimonkor** [flutter/flutter#41405] opened 2019-09-26 20:24 UTC
Please help, I upgraded Flutter and windows build failed 

```
[ +255 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(629)] Not running in AOT
mode but could not resolve the kernel binary.
[   +3 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc(53)] Returning error
'kInvalidArguments' (2) from Flutter Embedder API call to 'FlutterEngineRun'. Origin:
c:\b\s\w\ir\cache\builder\src\flutter\shell\platform\embedder\embedder.cc:631
[   +3 ms] Failed to start Flutter engine: error 2
[   +1 ms] Failed to create view.

e:\Projects\Flutter_projects\addIt>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.7-pre.32, on Microsoft Windows [Version 10.0.18362.356], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.16)
[√] Android Studio (version 3.5)
[√] Connected device (4 available)

• No issues found!
```

I downloaded last windows project files from https://github.com/google/flutter-desktop-embedding/tree/master/example/windows

My test project https://www.dropbox.com/s/m2ts125om347ow8/addIt.7z?dl=0. it worked 14 days ago.

Thanks for help.

**Comment by jld3103** [comment] 2019-09-26 20:31
Look at #41352
For now simply run `flutter version 1.10.6`

**Comment by daimonkor** [comment] 2019-09-26 20:32
@jld3103 Thanks, I will try

**Comment by jonahwilliams** [comment] 2019-09-26 20:35
Duplicate of https://github.com/flutter/flutter/issues/41352

**Closed by jonahwilliams** 2019-09-26 20:35 UTC
