### ISSUE TITLE
Event handler make separated from build method of Provider in Flutter

### ISSUE THREAD

**Issue by Mickey-A-Mouse** [flutter/flutter#81192] opened 2021-04-26 10:19 UTC
Is it possible to handle event on provider's value updates, for example, if login is success, just navigate to main page? How to handle that event from consumer, without rebuilding widget tree. Is it possible? I need the way to handle provider's value update from consumer, but not from build method. If you need some code, I could provide.

My idea is:
`return Consumer<LoginProvider>(
      builder: (context, loginProvider, child) {
               return LoginScreenContent(context, loginProvider);
              },
      eventFired: (context, loginProvider){
                 Navigator.of(context).pushReplacementNamed(MainRoute);
                  }
 );`

`...
//on Success
WidgetsBinding.instance.addPostFrameCallback(
            (_) {
              Navigator.of(context).pushReplacementNamed(MainRoute);
            },
          );
          return Container();
...`

Thanks!

**Comment by pedromassangocode** [comment] 2021-04-26 10:30
Hi @Mickey-A-Mouse 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://pub.dev/packages/provider/).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-26 10:30 UTC
Labels: in triage
