### ISSUE TITLE
TextField can't catch focus when there are two textField with different keyboardType on phone

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#144658] opened 2024-03-06 02:05 UTC
### Steps to reproduce

write a code with two TextField with different two different keyboard type, but one need to be (keyboardType: TextInputType.visiblePassword),
and tap one TextField, focus get, and keyboard show up;
and then tap the second one, keyboard switched, but the second TextField did get focus;

### Expected results

the second one can get focus

### Actual results

the second one didn't get focused

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                width: 300,
                child: TextField(
                  decoration: InputDecoration(hintText: "Id", labelText: "Id"),
                ),
              ),
              SizedBox(
                width: 300,
                child: TextField(
                  keyboardType: TextInputType.visiblePassword,
                  obscureText: true,
                  decoration: InputDecoration(hintText: "name", labelText: "name"),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/3118573/a56a834f-cb60-46de-a17b-a543c6bd2861

it can't be recorded as password keyboard is used, please run by code;
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-06 08:36
Hi @wanjm, what device(s) are you experiencing this issue on? What keyboard are you using? 

Please provide the output of `flutter doctor -v`.

**Comment by wanjm** [comment] 2024-03-06 09:11
```
[!] Flutter (Channel stable, 3.16.9, on macOS 12.6.3 21G419 darwin-x64, locale en-CN)
    • Flutter version 3.16.9 on channel stable at /opt/google/flutter
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 41456452f2 (6 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/google/android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • ANDROID_SDK_ROOT = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • NTH AN00 (mobile) • AKRSVB1630026451 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

**Comment by danagbemava-nc** [comment] 2024-03-07 06:28
You are using an older version of flutter. Kindly upgrade to the latest version of flutter (3.19.2) to see if you still experience this issue. If you do, please provide the updated output of flutter doctor -v. Please also provide the keyboard type you use. I tried with gboard but I didn't experience any issues. 

Thank you

**Comment by wanjm** [comment] 2024-03-07 10:11
```
[!] Flutter (Channel stable, 3.19.2, on macOS 12.6.3 21G419 darwin-x64, locale en-CN)
    • Flutter version 3.19.2 on channel stable at /opt/google/flutter
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 7482962148 (9 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/google/android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • ANDROID_SDK_ROOT = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • NTH AN00 (mobile) • AKRSVB1630026451 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 122.0.6261.111

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

**Comment by wanjm** [comment] 2024-03-07 10:12
there is still such problem in 3.19.2

https://github.com/flutter/flutter/assets/3118573/10c47910-0fea-40f0-9ab4-2794a26b8693

**Comment by sachin96Boy** [comment] 2024-03-08 02:06
This issue seems to be fixed with the new version of Flutter (3.19.2). I tried to recreate the problem but It gives the focus to different textfield inputs properly. This is a screen recording from the Flutter 3.19.2 version.

https://github.com/flutter/flutter/assets/52316373/eaa0f3f5-fac2-441a-a088-dd1be01533c1


This is Flutter doctor response
```
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.3803], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.87.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

```

**Comment by danagbemava-nc** [comment] 2024-03-08 06:30
Hi @wanjm, what language setting is your keyboard using? Also, what keyboard are you using?

**Comment by wanjm** [comment] 2024-03-08 08:52
both  chinese XuFei  and chinese Baidu have such problem;
also I found there is one switch called "safe input"  in  setting "Languge and Input method";when turn "safe input" on, it will come accross this problem;

**Comment by wanjm** [comment] 2024-03-08 08:57
@sachin96Boy plese change line 21 to "keyboardType: TextInputType.visiblePassword,"

**Comment by sachin96Boy** [comment] 2024-03-08 12:57
I just tried with `keyboardType: TextInputType.visiblePassword`, and it properly focuses on different text fields. I'm sorry, but there wasn't any 'Safe Input' option in my Emulator. Here's my flutter doctor. 

```
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.3803], locale en-US)
    • Flutter version 3.19.2 on channel stable at C:\Users\Admin\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (10 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.87.1)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3803]    • Chrome (web)            • chrome        • web-javascript • Google Chrome 122.0.6261.111
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

**Comment by EchoPuda** [comment] 2024-03-12 09:44
Hi, I have also encountered a similar problem here. Does not occur in all phones, only in Huawei and Honor phones. 
And I also found that it was normal before version 3.10. I didn't do any further validation between version 3.10 and 3.16.
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2024-03-13 06:49
Hi @EchoPuda, if you use gboard on the honor/huawei devices, do you still have this issue?

**Comment by EchoPuda** [comment] 2024-03-13 08:27
Hi @danagbemava-nc , sorry, the Honor/Huawei device belongs to my client and they uses system keyboard. I cannot request them to install Gboard to help me test it.

By the way, this has not problem on my Google device or iPhone.

**Comment by wanjm** [comment] 2024-03-13 10:04
I checked HuaWei/Honor, there is such switch, and has such issue;
I also checked MI, there is also such switch, but no such issue;
I check Sumsung, there is no such switch, and no such issue;

**Comment by danagbemava-nc** [comment] 2024-03-14 06:37
Thanks for the update. 

Labeling this for further investigation. 

This appears to be device specific, related to Huawei & honor devices. It does not reproduce on my Pixel and others have confirmed this doesn't happen on devices other than huawei/honor.

**Comment by linvi7** [comment] 2024-03-20 02:37
Hi I checked vivo/oppo/Huawei/MI/One Plus also called "safe input" on, my flutter version is 3.19.3

**Comment by cookie-y** [comment] 2024-05-13 06:59
Oppo also has the same problem.

**Comment by LongCatIsLooong** [comment] 2024-05-23 17:20
So far I haven't been able to repro this on Huawei/Oppo devices with the "security input" option on, (commit c14d55c4d2). I followed the exact repro steps.

**Closed** 2024-06-13 18:09 UTC
Labels: a: text input, e: device-specific, platform-android, waiting for customer response, f: focus, P2, team-text-input, triaged-text-input

**Comment by qycqlq** [comment] 2024-06-17 01:13
> Hi, I have also encountered a similar problem here. Does not occur in all phones, only in Huawei and Honor phones. And I also found that it was normal before version 3.10. I didn't do any further validation between version 3.10 and 3.16.
> 
> ```
> [✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.3)
> [✓] Android Studio (version 2023.2)
> [✓] VS Code (version 1.86.2)
> [✓] Connected device (3 available)
> [✓] Network resources
> 
> • No issues found!
> ```

Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (4 months ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
My flutter version， I have also encountered a similar problem here in  Honor phones，but my Huawei has no problem。
