### ISSUE TITLE
how to capture board image to clipboard?

### ISSUE THREAD

**Issue by 3215466800** [flutter/flutter#94704] opened 2021-12-06 03:53 UTC
how to set/get capture board image to clipboard?

the clipboard is very important about desktop developer

like snap cut fast send file

we project is IM but now clipboard is a big problem now

**Comment by 3215466800** [comment] 2021-12-06 03:54
#32045

**Comment by darshankawar** [comment] 2021-12-06 09:27
Closing this as a duplicate of https://github.com/flutter/flutter/issues/32045

**Closed by darshankawar** 2021-12-06 09:27 UTC
Labels: in triage
