### ISSUE TITLE
Flutter downgrade not working on fresh install on mac

### ISSUE THREAD

**Issue by timosturm** [flutter/flutter#86474] opened 2021-07-15 10:29 UTC
This is basically the same issue as #78860. The goal is to compile and debug a flutter project that uses flutter `v1`.

## Steps to Reproduce

1. Have a mac with no flutter installed
2. Follow https://flutter.dev/docs/get-started/install/macos to install the newest version of flutter (currently 2.2.3)
3. Run `flutter downgrade`
4. Fail with `There is no previously recorded version for channel "stable".`

## Logs

<details>
<summary>Logs</summary>

```
$flutter downgrade
There is no previously recorded version for channel "stable".
```

Additional information:

```
$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2021-07-15 10:49
Hi @timosturm 
`flutter downgrade` only works if you have the previous in your tool history, since you're trying this on a mac with no history, this is expected behavior. 
You can check `flutter -h`
` Downgrade Flutter to the last active version for the current channel.`

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-15 10:49 UTC
Labels: in triage

**Comment by timosturm** [comment] 2021-07-15 11:12
While this may not be a bug in the command itself, this behavior is definitely not clear to me from the help comment and should be better explained there.

**Comment by TahaTesser** [comment] 2021-07-15 11:18
Command help clearly says last active, `Downgrade Flutter to the last active version for the current channel.` SInce no version was there before, Message by tools is appropriate
