### ISSUE TITLE
Vertical BarChart Label Error

### ISSUE THREAD

**Issue by Annika-schr** [flutter/flutter#41776] opened 2019-10-02 13:26 UTC
Hello, 

I tried to implement a vertical BarChart with labels. Therefore I copied the code from this example: 
https://google.github.io/charts/flutter/example/bar_charts/vertical_bar_label.html
https://github.com/google/charts/blob/master/charts_flutter/example/lib/bar_chart/vertical_bar_label.dart
When I try to run the app it fails when it comes to the page. 

## Exception
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:charts_common/src/chart/bar/bar_label_decorator.dart': Failed assertion: line 73 pos 12: 'renderingVertically == false': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  BarChart .../lib/pages/chart_example_renderer.dart:79:16
When the exception was thrown, this was the stack: 
#2      BarLabelDecorator.decorate (package:charts_common/src/chart/bar/bar_label_decorator.dart:73:12)
#3      BarRenderer.paintBar (package:charts_common/src/chart/bar/bar_renderer.dart:338:27)
#4      BaseBarRenderer.paint.<anonymous closure> (package:charts_common/src/chart/bar/base_bar_renderer.dart:575:9)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      BaseBarRenderer.paint (package:charts_common/src/chart/bar/base_bar_renderer.dart:566:18)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<String>#03488
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=667.0)
...  semantic boundary
...  size: Size(375.0, 667.0)
RenderObject: ChartContainerRenderObject<String>#03488
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=667.0)
  semantic boundary
  size: Size(375.0, 667.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

## flutter doctor 
```
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale de-DE)
    • Flutter version 1.9.1+hotfix.4 at .../projects/FlutterApp/flutter
    • Framework revision cc949a8e8b (5 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at .../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = .../Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[!] Android Studio (version 2.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2016.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 6 • 257DEBF9-EBBF-4A5C-ACC6-95E2D6AC474D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 5 categories.
Process finished with exit code 0
```

**Comment by BondarenkoStas** [comment] 2019-10-02 15:21
@Annika-schr Somehow I can't reproduce it, both example run just fine. Did you do any changes there?

**Comment by janmoppel** [comment] 2019-11-11 09:46
Hello @Annika-schr !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Closed by janmoppel** 2019-11-11 09:46 UTC
Labels: d: examples, waiting for customer response
