### ISSUE TITLE
Please add support for flutter in ubuntu touch OS

### ISSUE THREAD

**Issue by apy7hst** [flutter/flutter#105379] opened 2022-06-05 02:57 UTC
Please add support for flutter on a linux-based mobile platform such as ubuntu touch OS for it to become a productive operating system and developers can create unique apps for it as well. Here are some major websites for the operating system if you have any doubts :- 
https://ubuntu-touch.io - The operating system website
https://open-store.io - Website for the app store of ubuntu touch OS
https://clickable-ut.dev - development and app packaging tool for ubuntu touch OS
https://ubports.com - ubuntu touch OS publisher's website
https://docs.ubports.com - documentation for ubuntu touch OS
https://docs.innerzaurus.com - programming courses for developing apps in ubuntu touch OS

**Comment by zanderso** [comment] 2022-06-06 18:13
FYI @HansMuller @cbracken

**Comment by apy7hst** [comment] 2022-06-07 10:24
Are you ready to support ubuntu touch OS yet? Or are you not happy with it?

**Comment by cbracken** [comment] 2022-06-08 20:16
Thanks for filing this. We're currently focusing our efforts on iOS and Android for mobile and Windows, macOS, and Linux for desktop. While this is not something the team is likely to prioritise soon, we are certainly receptive to any high-quality patches to the existing embedders that would help.

I'm not at all familiar with Ubuntu Touch, but if it's a port of Ubuntu targeting mobile devices, then I'd imagine the existing Linux embedder should be a good starting point. From  there, I'd encourage you to identify and file bugs with repro steps for any gaps in the current embedder. That would help any community contributors with an interest in this project direct their contributions.

**Comment by robert-ancell** [comment] 2022-06-08 21:16
I'm not aware of any specific changes that would be required for Ubuntu Touch - is anything not working with the current Linux embedder? There might be some services that are Ubuntu Touch specific, but these would just require new Dart packages and/or Flutter plugins to implement (i.e. not a core part of Flutter).

**Comment by apy7hst** [comment] 2022-06-09 03:30
> Thanks for filing this. We're currently focusing our efforts on iOS and Android for mobile and Windows, macOS, and Linux for desktop. While Ubuntu Touch support is not something the team is likely to prioritise soon, we are certainly receptive to any high-quality patches to the existing embedders that would help.
> 
> I'm not at all familiar with Ubuntu Touch, but if it's a port of Ubuntu targeting mobile devices, then I'd imagine the existing Linux embedder should be a good starting point. From there, I'd encourage you to identify and file bugs with repro steps for any gaps in the current embedder. That would help any community contributors with an interest in this project direct their contributions.
> 
> /cc @robert-ancell who may also have thoughts.

You are right, ubuntu touch is derived from ubuntu linux. But the thing is, ubuntu touch is not traditional linux. Therefore, it cannot run linux applications in it. If you want to know how to install ubuntu touch in your phone, then please visit this page :- https://devices.ubuntu-touch.io , and if you want to learn how ubuntu touch works, then join this telegram group :- https://t.me/ubports . If you also want to learn about its app store, then join this telegram group :- https://open-store.io/telegram

**Comment by cbracken** [comment] 2022-06-10 18:14
> Therefore, it cannot run linux applications in it.

If the Linux embedder doesn't work for Ubuntu Touch devices, then it sounds like one of two things is likely:

*Case 1:* The Linux embedder could be made usable with minor patches that will not affect its main use-case on desktop Linux. If this is the case, I'd suggest you identify the exact issues and file specific/reproducible issues for those cases and send patches. So long as they don't negatively impact the main use-case of Desktop Linux, we're generally happy to review high-quality patches with tests.

*Case 2:* The Linux embedder as-is is fundamentally unusable on these devices and a new embedder would be required. In that case, you'll want to author a new embedder in a dedicated repo to cover the Ubuntu Touch use-case. For an example of how to do this, have a look at the [sony/flutter-embedded-linux](https://github.com/sony/flutter-embedded-linux) repo.

I'm going to close this bug for now since our focus is on improving the existing embedders for the bulk of our users; adding new platforms in the main repo is not something we're likely to prioritise at the moment, but I'd certainly encourage you to pursue writing your own embedder (or filing specific, reproducible bugs against the current embedder) as described above.

**Closed by cbracken** 2022-06-10 18:14 UTC
Labels: new feature, engine, platform-linux, proposal, e: OS Version specific, P5
