### ISSUE TITLE
[Get to know Firebase for Flutter]missing async for Future<void> function

### ISSUE THREAD

**Issue by mrpond** [flutter/flutter#78593] opened 2021-03-19 05:14 UTC
https://firebase.google.com/codelabs/firebase-get-to-know-flutter#5

![image](https://user-images.githubusercontent.com/18654771/111734278-637fbb80-88ac-11eb-8831-9ae8a1d6defd.png)
from
`GuestBook(addMessage: (String message) => print(message)),`
![image](https://user-images.githubusercontent.com/18654771/111734371-988c0e00-88ac-11eb-9aec-0610e8cde94c.png)

to
`GuestBook(addMessage: (String message) async => print(message)),`

**Comment by pedromassangocode** [comment] 2021-03-19 08:52
Closing as duplicate of https://github.com/flutter/flutter/issues/69239 that was closed yesterday, see https://github.com/flutter/flutter/issues/69239#issuecomment-801636125.
Thank you

**Closed by pedromassangocode** 2021-03-19 08:52 UTC
Labels: in triage
