### ISSUE TITLE
firebase_auth: ^0.16.0 Crash on android

### ISSUE THREAD

**Issue by niypoo** [flutter/flutter#58859] opened 2020-06-06 12:12 UTC
That I got it in Crashlytics 

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void k.b.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
```

it's happened 2 times on
Android  9

```
io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged (FirebaseAuthPlugin.java:45)
com.google.firebase.auth.zzp.run (zzp.java:24)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage (zzj.java)
android.os.Looper.loop (Looper.java:226)
android.app.ActivityThread.main (ActivityThread.java:7191)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:942)
```

and  happened 2 times on
Android  7.1.1

```
io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged (FirebaseAuthPlugin.java)
com.google.firebase.auth.zzp.run (zzp.java)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage (zzj.java)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6816)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1565)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1453)
```

**Comment by onkar-shaligram** [comment] 2020-06-06 17:12
try writing your " firebase_auth: ^0.16.0 " to => " firebase_auth: any ". And see if you get any errors.

**Comment by niypoo** [comment] 2020-06-06 17:58
> try writing your " firebase_auth: ^0.16.0 " to => " firebase_auth: any ". And see if you get any errors.

why! please can you explain more about ?

**Comment by onkar-shaligram** [comment] 2020-06-06 18:03
The thing is that your flutter version might be interfering with the version of the Firebase plugin in which it is written in. So if you will put the 'any' in front of the Firebase version then flutter will figure out which version to refer too...

**Comment by niypoo** [comment] 2020-06-06 18:50
> The thing is that your flutter version might be interfering with the version of the Firebase plugin in which it is written in. So if you will put the 'any' in front of the Firebase version then flutter will figure out which version to refer too...
> 
> As well as can you share this project's Github repository link so that I can have a look and would help you out in figuring what might be going wrong.?

I'm working with 
`Flutter 1.19.0-4.0.pre.47 • channel master`

**Comment by onkar-shaligram** [comment] 2020-06-06 19:11
Okay.. So it seems that your Flutter SDK version is a Dev channel. Kindly change the SDK to latest Stable channel which is 1.17  And then hopefully the " firebase_auth: ^0.16.0 " might work properly.
For more details about SDK refer https://flutter.dev/docs/development/tools/sdk/releases

**Comment by onkar-shaligram** [comment] 2020-06-06 19:13
Also let me know if you are getting any errors after running 'pub get'

**Comment by iapicca** [comment] 2020-06-08 07:43
Hi @niypoo 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-08 07:43 UTC
