### ISSUE TITLE
Possible regression in microbenchmarks_ios_MatrixUtils_affine_transformRect_iteration & 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#41986] opened 2019-10-04 15:53 UTC
Also seen in 
`microbenchmarks_ios_MatrixUtils_persp_transformPoint_iteration`, `microbenchmarks_ios_combineSemanticsInfoList_iteration`, `microbenchmarks_ios_MatrixUtils_affine_transformPoint_iteration`, `microbenchmarks_ios_combineSemanticsInfoSyncStar_iteration`, and `microbenchmarks_ios_gesture_detector_bench`, `microbenchmarks_ios_stock_build_iteration`, `microbenchmarks_ios_stock_layout_iteration`, `microbenchmarks_ios_traverseIterableSyncStar_iteration`, and `microbenchmarks_ios_traverseIterableSyncStar_iteration`. Many of these are quite noisy, but the trend appears to start markedly at or about #41329. (Commit https://github.com/flutter/flutter/commit/0b0942a60caafff56c19fea07d8f7b14e6286e1c). It's not clear why to me why this refactor would do it, though.

**Comment by mklim** [comment] 2019-10-04 18:30
Removing the TODAY issue since it's not clear that this should be a release blocker.

**Comment by liyuqian** [comment] 2019-10-29 23:47
@kf6gpe : the regression seems to be strangely fixed by https://github.com/flutter/flutter/commit/e778686e72e799e3555adf0777bee548eecb3103 and it's now even lower than the number before the regression (before regression: ~85ms, after regreesion: ~95ms, now: ~80ms).

@flar : any idea how this could happen?

**Comment by flar** [comment] 2019-10-30 00:31
I see no reason for the recent improvements. I searched 4 or 5 changes on either side of the first result that was faster and didn't see anything that would have affected it. It is pure dart code so this would have to be something that changed in the dart runtime and/or the Float64List support...?

Also, the description talks about a regressive trend that started around #41329, but I don't see that either when I look at the history of these benchmarks...?

**Comment by liyuqian** [comment] 2019-11-04 22:53
Closing this as the regression is gone. (Although we don't know how it's introduced, and how it's fixed; maybe some infra flakiness again?)

**Closed by liyuqian** 2019-11-04 22:53 UTC
Labels: severe: performance, severe: regression
