### ISSUE TITLE
webview_flutter widget crashes on Android when used with qr_code_scanner

### ISSUE THREAD

**Issue by oander11** [flutter/flutter#79254] opened 2021-03-29 06:22 UTC
I'm new with Flutter and not sure if this is the appropriate place for this type of bug, but since I've had no feedback on [SO](https://stackoverflow.com/questions/66743004/android-crashes-when-i-try-to-use-qr-scanning-with-a-web-view/66746215?noredirect=1#comment118007443_66746215) nor on [qr_code_scanner](https://github.com/juliuscanute/qr_code_scanner/issues/289) I also try here. 

The issue is when using a [webview_flutter](https://pub.dev/packages/webview_flutter) widget and stacking a [qr_code_scanner](https://github.com/juliuscanute/qr_code_scanner) on top (in z-order) of it. Then it crashes on Android. It works fine on iOS. Both widgets works fine independently, but apparently not when used together in this way.

The issue on Android is that the QR scanner doesn't show up, and I get the following log, repeatedly:
`D/mali_winsys(30667): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000 `

I've tried this on two Android devices (Android 10, v29 and Android 7, v24) with same results.

I've added the Flutter doctor output at the end of this issue. 

I've created a minimal app which reproduce the issue, it contains a full-screen webview with a button on-top. Press the button and the QR scanner will show up on iOS but not on Android. It requires the following dependencies:

```
qr_code_scanner: ^0.3.5
webview_flutter: ^2.0.2 
```

```
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _showQr = false;

  @override
  void initState() {
    super.initState();
    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  void closeQr() {
    setState(() {
      _showQr = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Stack(
          children: [
            WebView(
              initialUrl: 'https://flutter.dev',
            ),
            Center(
              child: TextButton(
                onPressed: () {
                  setState(() {
                    _showQr = !_showQr;
                  });
                },
                child: Text('Show QR Scanner'),
                style: TextButton.styleFrom(
                  primary: Colors.white,
                  backgroundColor: Colors.teal,
                  onSurface: Colors.grey,
                ),
              ),
            ),
          ],
        ),
        Center(
          child: (_showQr) ? QRWidget(onClose: closeQr) : null,
        ),
      ],
    );
  }
}

class QRWidget extends StatefulWidget {
  const QRWidget({
    Key key,
    this.onClose,
  }) : super(key: key);

  final Function onClose;

  @override
  State<StatefulWidget> createState() => _QRWidgetState();
}

class _QRWidgetState extends State<QRWidget> {
  Barcode result;
  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  // In order to get hot reload to work we need to pause the camera if the platform
  // is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller.pauseCamera();
    }
    controller.resumeCamera();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          _buildQrView(context),
          Container(
            alignment: Alignment.bottomCenter,
            padding: EdgeInsets.only(bottom: 60.0),
            child: Row(
              children: <Widget>[
                Expanded(
                  child: RawMaterialButton(
                    onPressed: () {
                      setState(() {
                        widget.onClose();
                      });
                    },
                    elevation: 2.0,
                    fillColor: Colors.white,
                    child: Icon(
                      Icons.close_sharp,
                      color: Color(0xff459d44),
                      size: 40.0,
                    ),
                    padding: EdgeInsets.all(8.0),
                    shape: CircleBorder(),
                  ),
                ),
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _buildQrView(BuildContext context) {
    // For this example we check how width or tall the device is and change the scanArea and overlay accordingly.
    var scanArea = (MediaQuery.of(context).size.width < 400 ||
            MediaQuery.of(context).size.height < 400)
        ? 150.0
        : 300.0;
    // To ensure the Scanner view is properly sizes after rotation
    // we need to listen for Flutter SizeChanged notification and update controller
    return QRView(
      key: qrKey,
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
          borderColor: Color(0xff459d44),
          borderRadius: 10,
          borderLength: 30,
          borderWidth: 10,
          cutOutSize: scanArea),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) {
      setState(() {
        result = scanData;
      });
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }
}
```

**Flutter doctor**

```
Flutter (Channel stable, 2.0.2, on macOS 11.2.1 20D74 darwin-x64, locale en-SE)
    • Flutter version 2.0.2 at /Users/nn/Flutter/flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nn/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • BLA L29 (mobile) • AQH7N18A12003135 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 89.0.4389.90
```

**Comment by pedromassangocode** [comment] 2021-03-29 11:27
Hi @oander11 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/juliuscanute/qr_code_scanner).

We don't track issues from third-party packages!

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-29 11:27 UTC
Labels: in triage

**Comment by oander11** [comment] 2021-03-29 11:40
Thanks, that makes sense. What is confusing to me, and got me to post here in first place, is that the [webview_flutter](https://pub.dev/packages/webview_flutter) plugin doesn't track its own issues, but instead links directly to this issue tracker. That's why I figured even plugin issues were handled here.
