### ISSUE TITLE
Android application crashing only in release mode

### ISSUE THREAD

**Issue by bahman2000** [flutter/flutter#25466] opened 2018-12-17 16:28 UTC
When I am trying to run the base project in debug mode, its giving output but app crashes on real device When I am trying to export a signed APK for release and then install.
```
error message:
 --------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 944 (any.flutterapp5)
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'samsung/x/x:7.0/x/x:user/release-keys'
A/DEBUG: Revision: '8'
A/DEBUG: ABI: 'arm'
A/DEBUG: pid: 944, tid: 944, name: any.flutterapp5  >>> com.yourcompany.flutterapp5 <<<
A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
A/DEBUG: Abort message: '[FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result. 
```

**Comment by zoechi** [comment] 2018-12-17 16:37
Please add the output of `flutter doctor -v`
and if possible other information about how to reproduce.

**Comment by zoechi** [comment] 2018-12-17 16:39
Similar error as #15100, #23088

**Comment by bahman2000** [comment] 2018-12-17 17:03
Solved by removing the "minifyEnabled true" line. but what is the reason for this problem?

**Comment by zoechi** [comment] 2018-12-17 17:08
I reopened #15100.
Lets close this one.

**Comment by zoechi** [comment] 2018-12-17 17:08
Duplicate of #15100

**Closed by zoechi** 2018-12-17 17:08 UTC
Labels: dependency: dart, e: device-specific, engine, severe: crash, tool, ▣ platform-android
