### ISSUE TITLE
[web][Flutter 3] dart:ui paintImage / canvas.drawImage not working on flutter 3.0

### ISSUE THREAD

**Issue by meamde** [flutter/flutter#104030] opened 2022-05-18 01:52 UTC
my code is

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:ui' as ui;
import 'package:http/http.dart';
import 'dart:typed_data';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyHomePage(),
        ),
      ),
    );
  }
}



class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  String url = 'https://storage.googleapis.com/cms-storage-bucket/c823e53b3a1a7b0d36a9.png';
  
  
  double x = 0;
  double y = 0;

  Image? _originalImage;
  ui.Image? updatedImage;
  
  @override
  void initState() {
    super.initState();

    _getThumbnail();
  }

    void _getThumbnail() async {
      
    updatedImage = await decodeImageFromList((await get(Uri.parse(url))).bodyBytes);

    ui.Image canvasImage = await printImageToCanvas(updatedImage!);
    final pngBytes = await canvasImage.toByteData(format: ui.ImageByteFormat.png);
    _originalImage = Image.memory(pngBytes!.buffer.asUint8List(), width: 500, height: 500, fit: BoxFit.fitWidth, filterQuality: FilterQuality.high);

    setState(() {});
  }
  
  Future<ui.Image> printImageToCanvas(ui.Image image) async {
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    
    paintImage(
      canvas: canvas,
      fit: BoxFit.cover,
      alignment: FractionalOffset.bottomCenter,
      rect: Rect.fromCenter(
        center: const Offset(155, 155),
        width: 300,
        height: 90
      ),
      image: image,
      isAntiAlias: true
    );
    
    final picture = recorder.endRecording();
    return picture.toImage(500, 500);
  }

  
  @override
  Widget build(BuildContext context) {

    debugPrint("build!!!!");
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              if(_originalImage != null)
                Container(
                  color: Colors.red,
                  width: 400,
                  height: 400,
                  child: _originalImage,
                ),
              
              if(updatedImage != null)
                Container(
                  color: Colors.amber,
                  width: 400,
                  height: 400,
                  child: CustomPaint(
                    painter: ImageEditor(updatedImage, x, y),
                  ),
                ),
            ],
          ),
        ],
      )
    );
  }
}

class ImageEditor extends CustomPainter {
  ui.Image? image;
  double x;
  double y;
  ImageEditor(this.image, this.x, this.y);

  @override
  void paint(Canvas canvas, Size size) {
    paintImage(
      canvas: canvas,
      fit: BoxFit.cover,
      alignment: FractionalOffset.bottomCenter,
      rect: Rect.fromCenter(
        center: const Offset(155, 155),
        width: 300,
        height: 90
      ),
      image: image!,
      isAntiAlias: true
    );
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
</details> 

this code print canvas direct to image widget, and draw with custom painter.

it shows on flutter 2.10.5,
![image](https://user-images.githubusercontent.com/26292435/168940636-3087d558-a9c6-47ad-b0a0-2d4dd499a16f.png)

but it shows on flutter 3.0,
![image](https://user-images.githubusercontent.com/26292435/168940702-8ac22856-a720-4689-839e-1d03d3348059.png)

there is any changed on usage for printImage method?

**Comment by meamde** [comment] 2022-05-18 06:28
it looks like a bug..
this happen only appear on flutter web. ios and android are printed image well.

**Comment by maheshmnj** [comment] 2022-05-18 08:33
Hi @meamde, Thanks for filing the issue, I can confirm the above code sample works fine on stable 2.10.5 and fails to load the image on stable/master 3.0  

### Stable 3.0 / master 3.1
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/31410839/168991518-ab66af43-aa33-49fb-8d0d-19d34e32aa5d.png">

### Stable 2.10.5

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/31410839/168992752-c021ab5a-ae84-47d5-ad36-17dc76df252c.png">


Adding a regression label since this works fine on older versions of flutter. Also, this is a web-only issue the image loads fine on the Desktop.

Seems like a duplicate of https://github.com/flutter/flutter/issues/103803

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
    • Flutter version 3.1.0-0.0.pre.419 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2eed8cbf93 (2 weeks ago), 2022-04-28 22:29:06 -0400
    • Engine revision dfdfe0b3b0
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>flutter doctor -v (2.10.5)</summary>

```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter_dev
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android
      11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by meamde** [comment] 2022-05-18 08:45
thanks for check this issue.
i hope so fix this issuse quickly.
Web in Flutter 3.0 is noticeably better than 2.0 in all other areas. we want to release our product with 3.0 :-)

**Comment by meamde** [comment] 2022-05-20 01:28
> Can you please check with `--web-renderer=html` and separately with `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false`?

when run with `--web-renderer=html` , throw an error and nothing printed on browser.
```
➜  default_project flutter run -d chrome --web-renderer=html
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             10.0s
This app is linked to the debug service: ws://127.0.0.1:65055/UrBoT-xMJac=/ws
Debug service listening on ws://127.0.0.1:65055/UrBoT-xMJac=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:65055/UrBoT-xMJac=
Flutter Web Bootstrap: Programmatic
build!!!!
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:65055/UrBoT-xMJac=
Error: [object Event]


    at Object.createErrorWithStack (http://localhost:65012/dart_sdk.js:5093:12)
    at Function._throw (http://localhost:65012/dart_sdk.js:20399:18)
    at Function.throwWithStackTrace (http://localhost:65012/dart_sdk.js:20396:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65012/dart_sdk.js:40921:18)
    at Object._microtaskLoop (http://localhost:65012/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:65012/dart_sdk.js:40784:13)
    at http://localhost:65012/dart_sdk.js:36261:9

```

when run with `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false` , same happen on 3.0.
```
➜  default_project flutter run -d chrome --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...              9.3s
This app is linked to the debug service: ws://127.0.0.1:49451/AYXeoo0xQgM=/ws
Debug service listening on ws://127.0.0.1:49451/AYXeoo0xQgM=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:49451/AYXeoo0xQgM=
Flutter Web Bootstrap: Programmatic
build!!!!
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:49451/AYXeoo0xQgM=
build!!!!
```

![image](https://user-images.githubusercontent.com/26292435/169430413-c6b514c0-9ac9-4157-b3a5-fd56838e37fa.png)

**Comment by jason-simmons** [comment] 2022-05-21 03:15
This renders as expected if I patch the engine to disable `browserSupportsImageDecoder`.

With the `CkBrowserImageDecoder` enabled, the engine calls `canvaskit.MakeLazyImageFromTextureSource` which returns an image backed by a `WebGLTextureImageGenerator`.

But `WebGLTextureImageGenerator` does not implement `onGetPixels`, so calls to `Image.toByteData` will fail.

(also see https://github.com/flutter/flutter/issues/104197)

**Comment by yjbanov** [comment] 2022-05-26 18:29
Sorry, forgot to mention that with the `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false` option you also need to build in either `--profile` or `--release` mode. Yeah, this is an issue with reading pixels in CanvasKit.

**Comment by yjbanov** [comment] 2022-05-26 18:29
Deduplicating into https://github.com/flutter/flutter/issues/103803

**Closed by yjbanov** 2022-05-26 18:29 UTC
Labels: severe: regression, framework, platform-web, a: images, has reproducible steps, found in release: 3.0, found in release: 3.1
