### ISSUE TITLE
Timeout for ext.flutter.debugDumpRenderTree is too short

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19022] opened 2018-07-02 23:30 UTC
When you hit `t` while looking at a complicated tree, e.g. the gallery pull-to-refresh screen, the tool times out and quits, even though information is flowing.

**Comment by Hixie** [comment] 2018-07-02 23:30
We shouldn't really use a timeout at all here, or should be somehow more clever about how we do this. A timeout makes no sense.

Alternatively we could get the string, smuggle the string over, and dump that quickly, instead of using the syslog to do it. That might be the better solution.

**Comment by zoechi** [comment] 2019-02-14 17:17
Looks like a duplicate of #17302
I tried to reproduce a month ago and wasn't able to.

**Comment by jonahwilliams** [comment] 2019-03-24 20:12
I'm not able to reproduce, I believe this was fixed with the timeout removal

**Closed by jonahwilliams** 2019-03-24 20:12 UTC
Labels: a: first hour, severe: crash, t: hot reload, tool
