### ISSUE TITLE
[web][safari][desktop] When GridView reaches the top does a "robot dance" on certain resolution

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#66909] opened 2020-09-29 15:06 UTC
## Video demo
https://youtu.be/SuhXrdEPXFU

## Live demo
https://demo.chefmenu.app/#/

to reproduce use trackpad while using 2 fingers scrolling or you can use mouse but don't press & hold only scroll

## Repro Code
https://github.com/tomasbaran/chefmenu2 

Unfortunately, I'm busy and don't have time to simplify the code. Feel free to fork and simplify or just to get the minimal repro code

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.380, on Mac OS X 10.15.6 19G73 x86_64, locale es-ES)
    • Flutter version 1.22.0-10.0.pre.380 at /Users/tomas/Development/flutter
    • Framework revision ec40df9576 (3 days ago), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by tomasbaran** [comment] 2020-09-29 19:09
Since it happens after it unexpectedly jumps to the top, may be related to: https://github.com/flutter/flutter/issues/55362 https://github.com/flutter/flutter/issues/63948

**Comment by TahaTesser** [comment] 2020-09-30 09:36
Hi @tomasbaran 
Thanks for filing this issue

### I can't reproduce with the default zoom level on Safari using  two on the trackpad
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/94667124-03ac4d00-032c-11eb-8eba-d077b7f95929.gif)

### Issue reproduces when you zoom out with `command & -`
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/94667384-643b8a00-032c-11eb-8663-8434689f8a5f.gif)

I also tried to reproduce in a simplified code sample with GrdiView but no issues 
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

const double kMaxCrossAxisExtent = 250;
const double kSliverAppBarLayerHeight = 60;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ClipRRect(
        borderRadius: BorderRadius.all(Radius.circular(30)),
        child: NestedScrollView(
          // controller: widget.scrollController,
          headerSliverBuilder: (context, isScrolled) {
            return [
              SliverPadding(
                padding: const EdgeInsets.all(10),
                sliver: SliverPersistentHeader(
                  pinned: true,
                  delegate: _SliverPersistentHeaderDelegate(
                    Container(
                      width: double.infinity,
                      height: kSliverAppBarLayerHeight,
                      decoration: BoxDecoration(
                          color: Colors.grey[700],
                          borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(30),
                              topRight: Radius.circular(30))),
                      child: Center(
                        child: Text('AppBar'),
                      ),
                    ),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(children: [
            Container(
              child: GridView.extent(
                crossAxisSpacing: 4.0,
                mainAxisSpacing: 8.0,
                maxCrossAxisExtent: kMaxCrossAxisExtent,
                children: <Widget>[
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                  Image.network("https://i.imgur.com/QCNbOAo.png"),
                ],
              ),
            ),
          ]),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class _SliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
  _SliverPersistentHeaderDelegate(this.child);

  final Widget child;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return child;
  }

  @override
  double get maxExtent => kSliverAppBarLayerHeight;

  @override
  double get minExtent => kSliverAppBarLayerHeight;

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) => true;
}

```

</details> 

@tomasbaran 
Feel free to edit this and make it reproducible version

**Comment by tomasbaran** [comment] 2020-09-30 11:45
I guess we are getting to the root of the problem. I tried to zoom it in and I did NOT experience the issue. So, it looks like it happens only in certain resolution. I'm on 21.5" iMac 4k (4096 x 2304) using Safari at full screen.

Nope. I'm did NOT use canvaskit.

**Comment by yjbanov** [comment] 2020-10-19 19:01
I can reproduce this in Safari using the supplied repro app.

**Comment by yjbanov** [comment] 2020-10-19 19:02
This feels like an issue with us processing wheel events /cc @mdebbar @gspencergoog

**Comment by gspencergoog** [comment] 2020-10-21 23:03
@mdebbar Can you take a look at this one?

**Comment by YeungKC** [comment] 2020-10-29 21:52
I'm almost sure it's the same as #55362, because when you mouse over the header section and start scrolling it's as expected.

I've fixed it and will merge it into master in the near future.

I recommend close this issue as it is already duplicated.

cc @TahaTesser @gspencergoog

**Closed** 2020-10-29 23:00 UTC
Labels: P4, a: desktop, a: quality, browser: safari, f: scrolling, found in release: 1.22, framework, has reproducible steps, platform-web
