### ISSUE TITLE
Document how to translate our material widgets

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#13576] opened 2017-12-14 20:32 UTC
Flutter's `package:flutter_localizations` provides translations for Flutter's material widgets. However, it will not support all of the world's languages out of the box. Instead, we provide API for developers to add missing translations.

On https://flutter.io/tutorials/internationalization/ we should add a section that explains how to do that.

This came up in the discussion over in https://github.com/flutter/flutter/issues/13482.

/cc @LarkAscending @Sfshaza @HansMuller

**Comment by HansMuller** [comment] 2017-12-19 19:18
https://github.com/flutter/flutter/pull/12645 was intended to simplify adding translations for Material.

We could just migrate its example to the tutorial.

**Comment by lyudmylab** [comment] 2018-03-12 15:31
Hi there, just a heads-up: Flutter apps can be translated on Crowdin -- Crowdin supports localization of .arb files, has API/CLI, Github integration, and is free for open source projects.

**Comment by yjbanov** [comment] 2018-03-12 16:41
That's good to know. Thanks for the tip!

**Comment by zoechi** [comment] 2018-12-04 08:34
Is this covered by https://flutter.io/docs/development/accessibility-and-localization/internationalization ?
Can this be closed and if anything is left out more concrete issues be files instead?

The recently merged PR #23850 might be relevant.

**Comment by yjbanov** [comment] 2018-12-09 20:02
Ok with closing until we get specific requests.

**Closed** 2018-12-09 20:15 UTC
Labels: a: internationalization, d: website - content, framework
