### ISSUE TITLE
flutter doctor --android-licenses fails in "main" java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by leemke** [flutter/flutter#82403] opened 2021-05-13 01:51 UTC
### Starting Environment:
running pixelbook - Chrome Os Version 91.0.4472.25 (Official Build) beta (64-bit)
Linux: Debian GNU/Linux 10 (buster)
started from a new install of linux (beta) with 24G of storage, 
Developers option enabled
install update/upgrade applied  after initial install of linux container

downloaded Android Studio from web site and installed it, via files application
In android studio - applied update to kotlin and then exited

sudo apt-get install openjdk-11-jdk  --fix-missing
sudo apt install chromium

downloaded flutter stable edition
ran "tar -xf $HOME/Downloads/flutter_linux_2.0.*-stable.tar.xz"
this creates the installation SDK in $HOME/flutter.
added $HOME/flutter/bin to the $PATH
after restarting terminal 
ran "flutter doctor"
received an error message concerning Android licenses 
ran "flutter doctor --android-licenses"
received error message
   Exception in thread "main" java.lang.NoClassDefFoundError 

## Logs

<details>
<summary>Logs</summary>

```
```

leemke@penguin:/etc$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/leemke/flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/leemke/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Google Pixelbook (mobile) • emulator-5554 • android-x64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

![Screenshot 2021-05-12 20 07 48](https://user-images.githubusercontent.com/5303630/118066123-c0a36500-b363-11eb-9222-52fec3030851.png)

```
```

</details>

**Comment by TahaTesser** [comment] 2021-05-13 08:04
Hi @leemke 
This is a known issue that needs a better error message https://github.com/flutter/flutter/issues/80273

You can fix the error by  following https://stackoverflow.com/a/64162776
Closing as duplicate of https://github.com/flutter/flutter/issues/80273

**Closed by TahaTesser** 2021-05-13 08:04 UTC
Labels: in triage

**Comment by leemke** [comment] 2021-05-13 14:40
Thank you for your response and help.
I was successful in changing the situation.
Thanks for your help

Larry
