### ISSUE TITLE
iOS14 is showing Flutter frequently pasting from clipboard

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#60780] opened 2020-07-02 16:18 UTC
See b/160404736

Internal customers trying their Flutter app on iOS 14 are pointing out the banner notifications showing up constantly that their app is copying from clipboard. Marking as P1 as Google started testing apps with iOS 14 already and intends to block releases due to this.

**Comment by Zazo032** [comment] 2020-07-02 16:44
This is probably fixed by https://github.com/flutter/flutter/pull/60316

**Comment by mehmetf** [comment] 2020-07-02 19:19
Turns out certain plugins might be causing this as well (such as firebase deeplinks). Right now, #60316 plus adding 

```
  <key>FirebaseDeepLinkPasteboardRetrievalEnabled</key>
  <false/>
```

seem to resolve the issue. Keeping it open for now to confirm.

**Comment by EliasDeuss** [comment] 2020-07-02 23:35
@mehmetf See #60145

**Comment by Hixie** [comment] 2020-07-07 22:56
@mehmetf I'm marking this as a dupe of #60145, which is not marked P1; please mark that bug P1 (or file a new P1 bug specific to a plugin if it's a plugin issue) if there is something specific you would like addressed ASAP.

**Closed by Hixie** 2020-07-07 22:56 UTC
Labels: P1, customer: money (g3), platform-ios
