### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by r-durao-pvotal** [flutter/flutter#131595] opened 2023-07-31 07:38 UTC
## Command
```
flutter run -d chrome --web-port 3000 --dart-define-from-file=configs.json
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1822:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2366:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2337:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:909:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:928:49)
#5      FlutterVmService._flutterToggle (package:flutter_tools/src/vmservice.dart:706:41)
#6      FlutterVmService.flutterToggleDebugPaintSizeEnabled (package:flutter_tools/src/vmservice.dart:725:9)
#7      ResidentHandlers.debugToggleDebugPaintSizeEnabled (package:flutter_tools/src/resident_runner.dart:817:33)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1821:7)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel unknown, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-PT)
    [33m![39m Flutter version 3.10.1 on channel unknown at /opt/homebrew/Caskroom/flutter/3.0.4/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    [33m![39m Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    [32m•[39m Framework revision d3d8effc68 (3 months ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1
    [32m•[39m Pub download mirror https://pvotaltech.jfrog.io/artifactory/api/pub/pvotal-pub
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/ricardodurao/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.80.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.52.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.0.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: d3d8effc686d73e0114d71abdcccef63fa1f25d2
### Plugins
camera-0.9.8+1
camera_android-0.9.8+3
camera_avfoundation-0.9.13+2
camera_web-0.2.1+6
connectivity_plus-3.0.6
desktop_webview_window-0.1.6
file_picker-3.0.4
flutter_dropzone-3.0.6
flutter_dropzone_web-3.0.10
flutter_inappwebview-6.0.0-beta.12
flutter_plugin_android_lifecycle-2.0.15
flutter_web_auth-0.4.3
google_maps_flutter-2.4.0
google_maps_flutter_android-2.4.15
google_maps_flutter_ios-2.2.3
google_maps_flutter_web-0.5.2
integration_test
location-4.4.0
location_web-3.1.1
maps_launcher-2.2.0
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
rive_common-0.1.0
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.2
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
url_launcher-6.1.12
url_launcher_android-6.0.37
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.18
url_launcher_windows-3.0.7
video_player-2.7.0
video_player_android-2.4.9
video_player_avfoundation-2.4.9
video_player_web-2.0.16
webview_cookie_manager-2.0.6
webview_flutter-4.2.2
webview_flutter_android-3.9.2
webview_flutter_wkwebview-3.7.2

**Comment by danagbemava-nc** [comment] 2023-07-31 08:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102994

**Closed by danagbemava-nc** 2023-07-31 08:59 UTC
Labels: in triage
