### ISSUE TITLE
unexpected behavior in load UI

### ISSUE THREAD

**Issue by DevFatani** [flutter/flutter#29513] opened 2019-03-17 18:14 UTC
Unexpected behavior when load ui [Click Here to see issue](https://imgur.com/a/up8FiDj)
```
[✓] Flutter (Channel master, v1.3.11-pre.37, on Mac OS X 10.13.6 17G5019, locale
    en-SA)
    • Flutter version 1.3.11-pre.37 at /Users/DevFatani/xxx/flutter-sdk
    • Framework revision 5b917fa946 (16 hours ago), 2019-03-16 22:39:34 -0400
    • Engine revision c6f9fe7e00
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/DevFatani/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone XS • A5833947-79DD-49B6-93BD-159AB950D38C • ios • iOS 12.1
      (simulator)

```

**Comment by jonahwilliams** [comment] 2019-03-17 20:07
Duplicate of #28484

**Closed by jonahwilliams** 2019-03-17 20:07 UTC
