### ISSUE TITLE
Application is lagging while navigation with database and Futurebuilder or WatchBoxBuilder

### ISSUE THREAD

**Issue by siddhesh-boppo** [flutter/flutter#82270] opened 2021-05-11 14:41 UTC
**I have tried moor database and hive database.** 

Hi Folks, Currently I want to save my device contacts in database. It saves contacts peacefully in the database but while loading that contact list from respective database on nextpage, takes time for navigation till the builder gets all the data from the database table. So it gives bad user experience.

Thanks.

**Comment by TahaTesser** [comment] 2021-05-12 08:41
Hi @siddhesh-boppo 
`WatchBoxBuilder` is from Hive 

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/hivedb/hive/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-12 08:41 UTC
Labels: in triage
