### ISSUE TITLE
[Impeller] Unable to change color of a bitmap font.

### ISSUE THREAD

**Issue by admincode1** [flutter/flutter#126546] opened 2023-05-11 13:52 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Unable to change custom font color since I upgraded to Flutter (Channel stable, 3.10.0).

### Expected results

final font1 = Theme.of(context).textTheme.bodyMedium!.copyWith(
        fontSize: 22,
        fontFamily: 'myFont',
        height: 1.9,
        color: Colors.blue, <<-- Here, the color either white or black in dark mode.
);

### Actual results

Or

### Code sample

TextStyle(
        fontSize: 22,
        fontFamily: 'myFont',
        height: 1.9,
        color: Colors.blue, <<-- Same result.
);

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/Adam/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Adam/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/Adam/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Adam’s iPhone (mobile) • 00008030-00********2B802E • ios            • iOS 16.4.1 20E252
    • macOS (desktop)          • macos                     • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment] 2023-05-12 06:21
@admincode1 I check this with Montserrat font but it displays as expected as below:

![Screenshot 2023-05-12 at 13 18 38](https://github.com/flutter/flutter/assets/104349824/a4074f2a-dd54-443f-bb1f-cb9042491fbd)

Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by admincode1** [comment] 2023-05-13 10:27
> @admincode1 I check this with Montserrat font but it displays as expected as below:
> 
> ![Screenshot 2023-05-12 at 13 18 38](https://user-images.githubusercontent.com/104349824/237886892-a4074f2a-dd54-443f-bb1f-cb9042491fbd.png)
> 
> Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

The problem only presents on iOS, Arabic texts only (Dart version 3.0.0, all channels).
Tested on Android (Channel stable 3.10.0) and iOS (Dart version < 3.0.0) & It's working fine.

![IMG-6604](https://github.com/flutter/flutter/assets/67590385/db5ff582-f0a6-4ef9-87f1-3e0e7b6e0a88)

![Screenshot_20230513_125427](https://github.com/flutter/flutter/assets/67590385/a9dfda59-8d89-4eeb-933c-abf675240698)

**Comment by huycozy** [comment] 2023-05-15 05:04
I check this on both latest stable and master channels but can not reproduce this issue, the text is rendered color correctly with Arabic as well.

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/d2ffc75e-2cb4-415e-8e67-c2abe8911f37">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.63, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.63 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b8f7a2a64 (5 hours ago), 2023-05-14 17:42:29 -0400
    • Engine revision 326de1d849
    • Dart version 3.1.0 (build 3.1.0-110.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Can you share the font you are using?

**Comment by admincode1** [comment] 2023-05-15 05:44
It's working with some fonts but not all.
Tested with [digitalkhatt2](https://arbfonts.com/digital-khatt-madina-quranic-font-download.html)
I was using it in the past year or so with no issue (sdk: <=3.0.0), but I only see the issue in sdk: >=3.0.0 all channels (iOS only).

**Comment by huycozy** [comment] 2023-05-16 04:12
Thanks, this seems to be related to Impeller since I can see it works if disabling Impeller (`--no-enable-impeller`)

<details>
<summary>Demo</summary>

| enable Impeller | disable Impeller |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/67dc070a-1b62-4ccb-a16c-27866fc65a6f"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/caacb18d-254a-40a4-b3e1-f18f67fcc279">

</details>

**Comment by huycozy** [comment] 2023-05-16 04:14
Thanks, this seems to be related to Impeller since I can see it works if disabling Impeller (`--no-enable-impeller`)

<details>
<summary>Demo</summary>

| enable Impeller | disable Impeller |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/67dc070a-1b62-4ccb-a16c-27866fc65a6f"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/caacb18d-254a-40a4-b3e1-f18f67fcc279">

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
			backgroundColor: Colors.black,
      body: Center(
        child: Text(
          'Hello - سشيسشييشيشسيشسيسش',
          style: TextStyle(
            fontSize: 22,
            fontFamily: 'digitalkhatt',
            height: 1.9,
            color: Colors.blue,
          ),
        ),
      ),
    );
  }
}
```
</details>

Affected custom font: [digitalkhatt2.otf.zip](https://github.com/flutter/flutter/files/11483929/digitalkhatt2.otf.zip)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.85, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.85 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2919572fb3 (71 minutes ago), 2023-05-15 19:01:28 -0700
    • Engine revision c4d4b40c65
    • Dart version 3.1.0 (build 3.1.0-113.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jason-simmons** [comment] 2023-05-18 02:10
Impeller is treating this font as a color bitmap font on iOS because it contains a `COLR` table.

On iOS, `SkTypeface_Mac` calls `CTFontGetSymbolicTraits`, sees the `kCTFontColorGlyphsTrait` flag because of the `COLR` table, and sets the `fHasColorGlyphs` flag.

Impeller's `DrawGlyph` then creates the atlas bitmap by calling `SkCanvas::drawGlyphs` using a default color of `SK_ColorWHITE`.  `TextContents` then used the glyph atlas color pipeline because this font is marked as `GlyphAtlas::Type::kColorBitmap`.  That pipeline does not apply the text foreground color because it thinks the glyph is a bitmap that is already colored.

Skia and CoreText can render this glyph with the intended color if Impeller sets the text color in the `SkPaint` used by `DrawGlyph`.  But that would require Impeller to maintain a different atlas for each text color.

@chinmaygarde @jonahwilliams

**Comment by chinmaygarde** [comment] 2023-05-26 21:28
A fix was discussed in the weekly sync. The glyph cache key will also store an additional color for all glyphs.

**Comment by SkylineGT1** [comment] 2024-04-19 22:24
Any update on this?

**Comment by mny459** [comment] 2024-05-14 00:42
Any Update on This？This bug will really stop me to use impeller

**Comment by jonahwilliams** [comment] 2024-05-16 07:17
Soon

**Closed** 2024-05-17 19:29 UTC
Labels: platform-ios, engine, a: typography, has reproducible steps, P2, e: impeller, found in release: 3.10, found in release: 3.11, team-engine, triaged-engine, slimpeller
