### ISSUE TITLE
[webview_flutter] Multiple WebViews on the screen are flickering on iphone 13 pro 120hz display

### ISSUE THREAD

**Issue by piotrmoskala** [flutter/flutter#99151] opened 2022-02-25 13:31 UTC
## Details
 Hey! 👋   I am using few WebViews as a rows in ListView widget, I know that WebView is pretty expensive widget but I found out such an interesting case when using/testing WebViews (can be blank no matter what's inside) in ListView. It causes flickering of whole interface. There are some issues with similar behaviour but not exactly the same. I am on Flutter 2.10.1 (Stable) 
 
It is happening for me only on 120hz screen of iPhone 13 Pro. Couldn't reproduce it on simulator. 
 

**Target Platform: iOS**
**Target OS version/browser: 15.3.1**
**Devices:iPhone 13 Pro**

**webview_flutter: ^3.0.1**

## Screen recording 

https://user-images.githubusercontent.com/1877654/155723193-937ef3cd-be6b-4d71-84ad-24eb66fa193e.mov

## Reproduce code 

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test app'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Expanded(
              child: ListView.builder(
                itemCount: 20,
                itemBuilder: ((context, index) {
                  return Container(
                    margin: const EdgeInsets.all(10),
                    height: 200,
                    child: const WebView(
                      initialUrl: 'https://flutter.dev',
                    ),
                  );
                }),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
## Logs

<details>
<summary>Logs</summary>

After running `flutter run --profile --trace-skia`

```
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f14f00 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3132, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f140c0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3138, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f14d20 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3139, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f14720 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3140, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x10aef8360 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3145, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f148a0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3144, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x10aef82a0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3143, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x10aef93e0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3150, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f15380 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3149, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x110f144e0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3148, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
[ProcessSuspension] 0x10aef9200 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=3146, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

</details>

<details> 
<summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale en-PL)
    • Flutter version 2.10.1 at /Users/piotrmoskala/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/piotrmoskala/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Piotr’s iPhone (mobile)             • 00008110-00144C1E2269801E            • ios            • iOS 15.1.1 19B81
    • iPad mini (6th generation) (mobile) • 5C51AC4C-C318-404F-95CD-8A39B868F95B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by joshoconnor89** [comment] 2022-02-25 16:58
i have this issue too.  please help!  thank you

**Comment by maheini** [comment] 2022-02-25 18:55
I got a similar behavior. When I build a listview.seperated and create a Listtile inside with selected = true, then the colored bar is very good visible outside of my list. 
I put my List between other widgets on top and bottom.

**Comment by maheshmnj** [comment] 2022-02-28 08:13
Hi @piotrmoskala, Thanks for filing the issue. I believe this is because flutter doesn't support 120hz display as of today and this is currently a WIP and is being tracked here https://github.com/flutter/flutter/issues/90675.  

I did verify on Android Redmi K20 pro with 75Hz refresh rate and iPhone 13 pro simulator but I couldn't reproduce the flickering.

Android Device| IOS simulator
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/155945778-29c8ffa5-b8fb-47a1-82f9-defbceb44ccb.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/155947113-508bd243-d652-4cbe-8bb2-e9f6c48b8848.mov' width=180/> 


> It is happening for me only on 120hz screen of iPhone 13 Pro. Couldn't reproduce it on simulator.

We currently do not have a device with 120hz refresh rate to verify the issue. I am leaving this issue open for further investigation from the team.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


@joshoconnor89 @maheini could you please share the device name on which you are seeing this flickering along with the output of `flutter doctor -v`?

Thanks

**Comment by maheini** [comment] 2022-02-28 15:38
@maheshmnj looks like my issue is different - My Listview is overflowing the borders. Got a simple example here:

![grafik](https://user-images.githubusercontent.com/65506676/156011739-6a8f3841-ed49-4f00-b515-7b662fd3fe7f.png)

### Details

<details>
<summary>minimal App Source code</summary>

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Container(
              height: 150,
              child: Center(
                child: Text(
                    'Container without color ->listtile background visible!'),
              )),
          Container(
              color: Colors.green,
              height: 150,
              child: const Center(
                child: Text(
                    'Container with color ->no listtile background visible'),
              )),
          Expanded(
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text('Item nr. $index'),
                  selected: index % 2 > 0 ? true : false,
                  selectedTileColor: Colors.red,
                );
              },
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale de-CH)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Martin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Martin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • BLA L29 (mobile)  • AQH7N18927003547 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by cyanglaz** [comment] 2022-02-28 18:52
> @maheshmnj looks like my issue is different - My Listview is overflowing the borders. Got a simple example here:
> 
> ![grafik](https://user-images.githubusercontent.com/65506676/156011739-6a8f3841-ed49-4f00-b515-7b662fd3fe7f.png)
> 
> ### Details
> minimal App Source code
> Flutter doctor -v

Since your issue is not the same as the original, I will hide your comment for easier triaging. Please feel free to open a new issue to describe what you experienced :)

**Comment by maheshmnj** [comment] 2022-03-01 05:25
@maheini You are hitting https://github.com/flutter/flutter/issues/86584 (not related to this issue), Please follow up on the linked issue for further updates

**Comment by sroddy** [comment] 2022-03-01 15:33
I'm pretty sure the underlying cause of this issue is the very same of this other one.
https://github.com/flutter/flutter/issues/98756

Not sure it's due to 120hz refresh rate, but for sure it's happening only on iPhone 13 Pro.
If someone has an iPad Pro with ProMotion display, it would be really helpful to understand whether it is also being affected.

**Comment by sroddy** [comment] 2022-03-08 12:26
For some reason which I can't completely understand if you set `CADisableMinimumFrameDurationOnPhone` to `true` inside the info.plist, the glitches I experience in the issue above are completely gone. @piotrmoskala maybe you can try to check if that is the case for this issue too

**Comment by cyanglaz** [comment] 2022-03-08 18:54
> For some reason which I can't completely understand if you set `CADisableMinimumFrameDurationOnPhone` to `true` inside the info.plist, the glitches I experience in the issue above are completely gone. @piotrmoskala maybe you can try to check if that is the case for this issue too

```
If you don’t enable faster refresh rates for your app, your [CADisplayLink](https://developer.apple.com/documentation/quartzcore/cadisplaylink?language=objc) callback might run at any of the speeds that the ProMotion display supports, at different times during normal GUI operations. In these cases, other animations in the system may affect the rate at which Core Animation calls your CADisplayLink callback. The rate at which Core Animation calls your CADisplayLink callback may not match the refresh rate hints that you provide to your CADisplayLink callback. Specifically, Core Animation won’t unlock any refresh rate that’s faster than the system’s default.```

So I think in ProMotion display devices, this has to be `true` for flutter since we are already suggesting refresh rates to CADisplayLink (even that we are not using the variable refresh rate)

I think we should add the `CADisableMinimumFrameDurationOnPhone` to the template so that ProMotion phones don't have this issue. Meaning we should land https://github.com/flutter/flutter/pull/94509 without [setting default refresh rate to 120] (https://github.com/flutter/engine/pull/29797)

cc @iskakaushik @jmagman

**Comment by piotrmoskala** [comment] 2022-03-18 09:53
> For some reason which I can't completely understand if you set `CADisableMinimumFrameDurationOnPhone` to `true` inside the info.plist, the glitches I experience in the issue above are completely gone. @piotrmoskala maybe you can try to check if that is the case for this issue too


Yes! After setting `CADisableMinimumFrameDurationOnPhone` to `true`, glitches are gone! 🤯

**Comment by kamami** [comment] 2022-04-05 09:55
> For some reason which I can't completely understand if you set `CADisableMinimumFrameDurationOnPhone` to `true` inside the info.plist, the glitches I experience in the issue above are completely gone. @piotrmoskala maybe you can try to check if that is the case for this issue too

This also fixed my issue described here: https://github.com/flutter/flutter/issues/101286

**Comment by jmagman** [comment] 2022-04-05 17:55
This was fixed by https://github.com/flutter/flutter/pull/100647

**Closed by jmagman** 2022-04-05 17:55 UTC
Labels: e: device-specific, platform-ios, plugin, severe: performance, p: first party, p: webview, severe: rendering, perf: speed, P4
