### ISSUE TITLE
Bottomsheet is overlapped by the keyboard ( Both persistent and modal ) 

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#17861] opened 2018-05-24 08:25 UTC
![screenshot_20180524-135141](https://user-images.githubusercontent.com/12619420/40473429-c7bf28da-5f59-11e8-949c-663c6b632b3e.jpg)
****
I want to implement something like this . I used modalbottomsheet with a texfield inside that but as soon as I click on it my bottomsheet with height around 100.0 is overlapped by the keyboard . I tried to fix this but couldn't . Please help thanks

**Comment by thelazyindian** [comment] 2018-07-07 08:18
Well I found a workaround for this issue

**Comment by iampawan** [comment] 2018-07-10 10:47
@thelazyindian Yes, I would love to hear that.

**Comment by frederickcxa** [comment] 2018-08-30 19:42
Any other solution for this?

**Comment by eurotrip11** [comment] 2018-09-10 10:26
Any news for this?

**Comment by AppleEducate** [comment] 2018-11-16 16:01
I took @thelazyindian approach and did exactly what @iampawan was trying to do:

https://github.com/AppleEducate/Tasks

**Comment by zoechi** [comment] 2018-11-27 14:43
Looks like a dup of #18564 (this is older but the other has more activity)

**Comment by goderbauer** [comment] 2018-12-29 01:42
Dupe of https://github.com/flutter/flutter/issues/18564.

**Closed by goderbauer** 2018-12-29 01:42 UTC
Labels: a: text input, framework

**Comment by socrates93** [comment] 2020-05-01 06:37
> Basically I used AnimatedPadding inside which Mediaquery viewInsets gets me the required padding after keyboard pops up to push the modalBottomSheet from bottom and thus preventing keyboard from overlapping my modalBottomSheet. Still there's some issue, The word suggestions bar displaying just above keyboard still overlaps bottom sheet lol. Still a better fix is needed.
> 
> ```dart
> return new AnimatedPadding(
>             padding: MediaQuery.of(context).viewInsets,
>             duration: const Duration(milliseconds: 100),
>             curve: Curves.decelerate,
>             child: new Container(
>               alignment: Alignment.bottomCenter,
>               child: Wrap(
>                 children: <Widget>[
>                                   new Text("Blah Blah"), 
>                                ],
>                          ), 
>                  ),
>         );
> ```


This works correctly. Additionally, to the **showModalBottomSheet** you must add the **isScrollControlled** to true. With this, it works wonderfully.
