### ISSUE TITLE
[Material 3] IconButton should support statesController as well

### ISSUE THREAD

**Issue by Knupper** [flutter/flutter#150086] opened 2024-06-12 06:50 UTC
### Use case

For TextButton/ElevatedButton/OutlineButton it is possible to give a own instance of a WidgetlStatesController / _MaterialStatesController_ into it. For a IconButton we have no such possibility, it always creates a own one in `_SelectableIconButtonState`. 

### Proposal

A IconButton has the same interface as the other M3 Buttons.

**Comment by danagbemava-nc** [comment] 2024-06-12 09:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139372

**Closed by danagbemava-nc** 2024-06-12 09:28 UTC
Labels: in triage
