### ISSUE TITLE
Crash when upgrading flutter from 3.10.2 to 3.10.3 during installation of Android toolchain

### ISSUE THREAD

**Issue by CicadaCinema** [flutter/flutter#128211] opened 2023-06-04 22:41 UTC
Not sure what is causing this, and it looks like the update resumed after I ran `flutter doctor`. I do not develop android apps on this machine.

Not sure if this is relevant, but I had another terminal session active with neovim and the Dart LSP running at the time of the crash.

```
$ flutter upgrade
Upgrading Flutter to 3.10.3 from 3.10.2 in /home/jazz/Software/flutter...
Downloading Linux x64 Dart SDK from Flutter engine 2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  203M    0 1998k    0     0  2603k      0  0:01:20 --:--:--  0:01:20 2602k
  8  203M    8 18.2M    0     0  10.3M      0  0:00:19  0:00:01  0:00:18 10.3M
 16  203M   16 34.5M    0     0  12.4M      0  0:00:16  0:00:02  0:00:14 12.4M
 24  203M   24 50.7M    0     0  13.4M      0  0:00:15  0:00:03  0:00:12 13.4M
 32  203M   32 67.0M    0     0  14.0M      0  0:00:14  0:00:04  0:00:10 14.0M
 40  203M   40 82.5M    0     0  14.3M      0  0:00:14  0:00:05  0:00:09 16.1M
 47  203M   47 97.3M    0     0  14.3M      0  0:00:14  0:00:06  0:00:08 15.8M
 55  203M   55  113M    0     0  14.6M      0  0:00:13  0:00:07  0:00:06 15.8M
 63  203M   63  129M    0     0  14.8M      0  0:00:13  0:00:08  0:00:05 15.8M
 71  203M   71  146M    0     0  14.9M      0  0:00:13  0:00:09  0:00:04 15.8M
 79  203M   79  162M    0     0  15.0M      0  0:00:13  0:00:10  0:00:03 15.9M
 86  203M   86  176M    0     0  14.9M      0  0:00:13  0:00:11  0:00:02 15.8M
 94  203M   94  192M    0     0  15.0M      0  0:00:13  0:00:12  0:00:01 15.7M
100  203M  100  203M    0     0  15.1M      0  0:00:13  0:00:13 --:--:-- 15.7M
Building flutter tool...
Resolving dependencies...
Got dependencies.

Upgrading engine...
Downloading android-arm-profile/linux-x64 tools...                 443ms
Downloading android-arm-release/linux-x64 tools...                 242ms
Downloading android-arm64-profile/linux-x64 tools...               270ms
Downloading android-arm64-release/linux-x64 tools...               261ms
Downloading android-x64-profile/linux-x64 tools...                 261ms
Downloading android-x64-release/linux-x64 tools...                 246ms
Downloading android-x86 tools...                                 1,347ms
Downloading android-x64 tools...                                 1,150ms
Downloading android-arm tools...                                 1,397ms
Downloading android-arm-profile tools...                           418ms
Downloading android-arm-release tools...                           292ms
Downloading android-arm64 tools...                               1,333ms

===== CRASH =====
si_signo=Bus error(7), si_code=2, si_addr=0x7fc5bd003680
version=3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000) on "linux_x64"
pid=35555, thread=35895, isolate_group=main(0x5594f1d82000), isolate=main(0x5594f1d83800)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7fc5bcec1000, vm_instructions=5594f01a4920
fp=7fc5ba77e560, sp=7fc5ba77e4f0, pc=7fc5bd003680
  pc 0x00007fc5bd003680 fp 0x00007fc5ba77e560 Unknown symbol
  pc 0x00005594f030e9b8 fp 0x00007fc5ba77e5f0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x128
  pc 0x00005594f030e83d fp 0x00007fc5ba77e650 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0xed
  pc 0x00005594f031059e fp 0x00007fc5ba77e690 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0x12e
  pc 0x00005594f032fe5f fp 0x00007fc5ba77ec20 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x2bf
  pc 0x00005594f0354a67 fp 0x00007fc5ba77ec90 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x127
  pc 0x00005594f0355094 fp 0x00007fc5ba77ece0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x00005594f046261b fp 0x00007fc5ba77ed60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14b
  pc 0x00005594f0462a68 fp 0x00007fc5ba77ed90 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x00005594f03e5f16 fp 0x00007fc5ba77ee50 /home/jazz/Software/flutter/bin/cache/dart-sdk/bin/dart+0x2352f16
-- End of DumpStackTrace
$ flutter doctor -v
Downloading package sky_engine...                                  304ms
Downloading flutter_patched_sdk tools...                           217ms
Downloading flutter_patched_sdk_product tools...                   217ms
Downloading linux-x64 tools...                                   2,658ms
Downloading linux-x64/font-subset tools...                         206ms
[✓] Flutter (Channel stable, 3.10.3, on Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64, locale en_GB.UTF-8)
    • Flutter version 3.10.3 on channel stable at /home/jazz/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (3 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7 (Fedora 15.0.7-2.fc37)
    • cmake version 3.26.4
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**Comment by huycozy** [comment] 2023-06-05 12:01
I tried upgrading flutter (also from 3.10.2 to 3.10.3) but it works well without crashing. 

<details>
<summary>Upgrade output logs  without issue (Ubuntu)</summary>

```console
huynq@ubuntu:~$ flutter upgrade
Upgrading Flutter to 3.10.3 from 3.10.2 in /home/huynq/Documents/Working/flutter...
Downloading Linux x64 Dart SDK from Flutter engine 2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  203M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  203M    0  270k    0     0   192k      0  0:18:04  0:00:01  0:18:03  192k
  4  203M    4 8444k    0     0  3512k      0  0:00:59  0:00:02  0:00:57 3511k
  9  203M    9 18.6M    0     0  5611k      0  0:00:37  0:00:03  0:00:34 5610k
 14  203M   14 29.0M    0     0  6755k      0  0:00:30  0:00:04  0:00:26 6754k
 19  203M   19 39.3M    0     0  7453k      0  0:00:28  0:00:05  0:00:23 8726k
 24  203M   24 49.6M    0     0  7938k      0  0:00:26  0:00:06  0:00:20  9.8M
 29  203M   29 59.6M    0     0  8255k      0  0:00:25  0:00:07  0:00:18 10.2M
 34  203M   34 70.0M    0     0  8530k      0  0:00:24  0:00:08  0:00:16 10.2M
 39  203M   39 80.1M    0     0  8725k      0  0:00:23  0:00:09  0:00:14 10.2M
 44  203M   44 90.3M    0     0  8894k      0  0:00:23  0:00:10  0:00:13 10.2M
 49  203M   49  100M    0     0  9013k      0  0:00:23  0:00:11  0:00:12 10.1M
 52  203M   52  107M    0     0  8910k      0  0:00:23  0:00:12  0:00:11 9878k
 58  203M   58  118M    0     0  9055k      0  0:00:23  0:00:13  0:00:10 9939k
 63  203M   63  129M    0     0  9184k      0  0:00:22  0:00:14  0:00:08  9.8M
 68  203M   68  139M    0     0  9277k      0  0:00:22  0:00:15  0:00:07  9.8M
 73  203M   73  150M    0     0  9374k      0  0:00:22  0:00:16  0:00:06  9.9M
 78  203M   78  160M    0     0  9461k      0  0:00:22  0:00:17  0:00:05 10.5M
 84  203M   84  171M    0     0  9535k      0  0:00:21  0:00:18  0:00:03 10.5M
 89  203M   89  182M    0     0  9604k      0  0:00:21  0:00:19  0:00:02 10.5M
 94  203M   94  192M    0     0  9661k      0  0:00:21  0:00:20  0:00:01 10.5M
 99  203M   99  202M    0     0  9710k      0  0:00:21  0:00:21 --:--:-- 10.5M
100  203M  100  203M    0     0  9715k      0  0:00:21  0:00:21 --:--:-- 10.5M
Building flutter tool...
Resolving dependencies...
Got dependencies.

Upgrading engine...
Downloading android-arm-profile/linux-x64 tools...                 686ms
Downloading android-arm-release/linux-x64 tools...                 258ms
Downloading android-arm64-profile/linux-x64 tools...               288ms
Downloading android-arm64-release/linux-x64 tools...               269ms
Downloading android-x64-profile/linux-x64 tools...                 307ms
Downloading android-x64-release/linux-x64 tools...                 260ms
Downloading android-x86 tools...                                 2,590ms
Downloading android-x64 tools...                                 2,252ms
Downloading android-arm tools...                                 2,176ms
Downloading android-arm-profile tools...                           665ms
Downloading android-arm-release tools...                           491ms
Downloading android-arm64 tools...                               2,476ms
Downloading android-arm64-profile tools...                         726ms
Downloading android-arm64-release tools...                         533ms
Downloading android-x64-profile tools...                           739ms
Downloading android-x64-release tools...                           539ms
Downloading android-x86-jit-release tools...                     1,075ms
Downloading Web SDK...                                              5.9s
Downloading package sky_engine...                                  161ms
Downloading flutter_patched_sdk tools...                           363ms
Downloading flutter_patched_sdk_product tools...                   364ms
Downloading linux-x64 tools...                                      4.5s
Downloading linux-x64-debug/linux-x64-flutter-gtk tools...       2,562ms
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...        969ms
Downloading linux-x64-release/linux-x64-flutter-gtk tools...        819ms
Downloading linux-x64/font-subset tools...                         199ms

Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (4 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.3, on Ubuntu 22.04.1 LTS 5.19.0-43-generic, locale en_US.UTF-8)
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[!] Flutter (Channel stable, 3.10.3, on Ubuntu 22.04.1 LTS 5.19.0-43-generic, locale en_US.UTF-8)
    • Flutter version 3.10.3 on channel stable at /home/huynq/Documents/Working/flutter
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-31, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.78.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-43-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.11.0-18.0.pre.76, on Ubuntu 22.04.1 LTS 5.19.0-43-generic, locale en_US.UTF-8)
    • Flutter version 3.11.0-18.0.pre.76 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b7415356e (2 days ago), 2023-06-03 07:16:37 -0400
    • Engine revision c838a1b059
    • Dart version 3.1.0 (build 3.1.0-166.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-31, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.78.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-43-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>


Does the issue happen again if you retry?

**Comment by CicadaCinema** [comment] 2023-06-05 13:07
No, I can't seem to be able to reproduce it.

```
$ git checkout 3.10.2
Note: switching to '3.10.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9cd3d0d9ff Roll engine to 90fa3ae28fe6ddaee1af2c120f01e50201c1401b. (#127460)
$ flutter doctor -v
Downloading Linux x64 Dart SDK from Flutter engine 90fa3ae28fe6ddaee1af2c120f01e50201c1401b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203M  100  203M    0     0  15.1M      0  0:00:13  0:00:13 --:--:-- 15.7M
Building flutter tool...
Resolving dependencies... (2.2s)
Got dependencies.
Downloading Material fonts...                                      492ms
Downloading Gradle Wrapper...                                      140ms
Downloading package sky_engine...                                  197ms
Downloading flutter_patched_sdk tools...                           334ms
Downloading flutter_patched_sdk_product tools...                   304ms
Downloading linux-x64 tools...                                   2,616ms
Downloading linux-x64/font-subset tools...                         661ms
[!] Flutter (Channel unknown, 3.10.2, on Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64, locale en_GB.UTF-8)
    ! Flutter version 3.10.2 on channel unknown at /home/jazz/Software/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 9cd3d0d9ff (12 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7 (Fedora 15.0.7-2.fc37)
    • cmake version 3.26.4
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
$ flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  * [new branch]            flutter-3.11-candidate.19 -> origin/flutter-3.11-candidate.19
git: Previous HEAD position was 9cd3d0d9ff Roll engine to 90fa3ae28fe6ddaee1af2c120f01e50201c1401b. (#127460)
git: Switched to branch 'stable'
git: Your branch is up to date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
$ flutter upgrade
Downloading Linux x64 Dart SDK from Flutter engine 2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203M  100  203M    0     0  15.3M      0  0:00:13  0:00:13 --:--:-- 15.3M
Building flutter tool...
Resolving dependencies... (2.1s)
Got dependencies.
Flutter is already up to date on channel stable
Flutter 3.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f92f44110e (4 days ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
$ flutter doctor -v
Downloading package sky_engine...                                  281ms
Downloading flutter_patched_sdk tools...                           252ms
Downloading flutter_patched_sdk_product tools...                   225ms
Downloading linux-x64 tools...                                   2,591ms
Downloading linux-x64/font-subset tools...                         118ms
[✓] Flutter (Channel stable, 3.10.3, on Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64, locale en_GB.UTF-8)
    • Flutter version 3.10.3 on channel stable at /home/jazz/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7 (Fedora 15.0.7-2.fc37)
    • cmake version 3.26.4
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 37 (KDE Plasma) 6.3.5-100.fc37.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

Before doing this, I cleared the `bin/cache` folder.

This time, it doesn't look like Flutter is downloading any Android tooling at all (compare these logs with the OP).

**Comment by huycozy** [comment] 2023-06-06 04:14
Perhaps the issue is related to the cache. Since it's not able to be reproduced, I'm not sure what the next action can be. So I'm therefore going to close this issue from here. 

Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! Thank you!

**Closed by huycozy** 2023-06-06 04:14 UTC
Labels: in triage
