### ISSUE TITLE
FlexibleSpaceBar title throws non null String exception

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#59368] opened 2020-06-12 22:03 UTC
I am using FlecibleSpaceBar and title in it with Text widget.
here is a code
```
FlexibleSpaceBar(
                  centerTitle: true,
                  collapseMode: CollapseMode.pin,
                  title: Text(
                    _details.name,
                    style: TextStyle(color: CustomColors.darkBlue),
                  ),
```
however until i am not setting name to empty string at details intiialization i get this error:
`A non-null String must be provided to a Text widget`

this would be understandabe but what i see the bug is - i keep getting this error even when i do null check this

```
FlexibleSpaceBar(
                  centerTitle: true,
                  collapseMode: CollapseMode.pin,
                  title: Text(
                    _details.name ?? '',
                    style: TextStyle(color: CustomColors.darkBlue),
                  ),
```

this eror goes away **ONLY** if i set name explicitly to empty strin ginside details class.

**Comment by superciccio** [comment] 2020-06-12 22:09
can you check if this `_details` is null ? so if is not ` _details.name ?? '',` that works

**Comment by vytautas-pranskunas-** [comment] 2020-06-12 22:39
Details not null because I am creating new instance just after constructor. However ?? Does not work. Because if I set name = '' explicitly in New instance it works

**Comment by superciccio** [comment] 2020-06-12 23:13
> Details not null because I am creating new instance just after constructor. However ?? Does not work. Because if I set name = '' explicitly in New instance it works

Details not null because I am creating new instance just after constructor.
what do you mean by that ?

```
Class Details {
final String name;
Deails({this.name= ''});
}
```

or what ?

**Comment by vytautas-pranskunas-** [comment] 2020-06-13 06:06
Class Details {

}

**Comment by iapicca** [comment] 2020-06-15 07:40
HI @vytautas-pranskunas- 
running this code

<details>
  <summary>sample</summary>

```dart
import 'package:flutter/material.dart';

/// adapting code from [https://api.flutter.dev/flutter/material/FlexibleSpaceBar-class.html#material.FlexibleSpaceBar.1]

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        physics: const BouncingScrollPhysics(),
        slivers: <Widget>[
          SliverAppBar(
            stretch: true,
            onStretchTrigger: () {
              // Function callback for stretch
              return;
            },
            expandedHeight: 300.0,
            flexibleSpace: 

            /// adapted snippet from [https://github.com/flutter/flutter/issues/59368#issue-638024741]
             
             FlexibleSpaceBar(
              centerTitle: true,
              collapseMode: CollapseMode.pin,
              title: Text(
                '',
                style: TextStyle(color: Colors.white),
              ),
            ),

            /// original

            // FlexibleSpaceBar(
            //   stretchModes: <StretchMode>[
            //     StretchMode.zoomBackground,
            //     StretchMode.blurBackground,
            //     StretchMode.fadeTitle,
            //   ],
            //   centerTitle: true,
            //   title: const Text('Flight Report'),
            //   background: Stack(
            //     fit: StackFit.expand,
            //     children: [
            //       Image.network(
            //         'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg',
            //         fit: BoxFit.cover,
            //       ),
            //       const DecoratedBox(
            //         decoration: BoxDecoration(
            //           gradient: LinearGradient(
            //             begin: Alignment(0.0, 0.5),
            //             end: Alignment(0.0, 0.0),
            //             colors: <Color>[
            //               Color(0x60000000),
            //               Color(0x00000000),
            //             ],
            //           ),
            //         ),
            //       ),
            //     ],
            //   ),
            // ),
          ),
          SliverList(
            delegate: SliverChildListDelegate([
              ListTile(
                leading: Icon(Icons.wb_sunny),
                title: Text('Sunday'),
                subtitle: Text('sunny, h: 80, l: 65'),
              ),
              ListTile(
                leading: Icon(Icons.wb_sunny),
                title: Text('Monday'),
                subtitle: Text('sunny, h: 80, l: 65'),
              ),
            ]),
          ),
        ],
      ),
    );
  }
}
```

</details>

everything seems to work as intended,
could you please provide 
your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-07 14:18
@vytautas-pranskunas- 
I hope you've solved the issue.
Closing as additional information isn't provided

**Closed by VladyslavBondarenko** 2020-07-07 14:18 UTC
Labels: f: material design, framework, in triage, waiting for customer response
