### ISSUE TITLE
Include untested files in test coverage

### ISSUE THREAD

**Issue by ShivamArora** [flutter/flutter#40948] opened 2019-09-20 07:51 UTC
## Steps to Reproduce

I'm unable to include the untested files in the test coverage report generated using:
`flutter test --coverage`.

1. Create three files namely `a.dart`, `b.dart`, `c.dart`.
2. Use some code from `c.dart` in `b.dart`.
3. Write the test cases for `b.dart`.
4. Generate the coverage report using `flutter test --coverage`.
5. Generate the html for the coverage report using `genhtml coverage/lcov.info -o coverage/html`.
6. You will see only the following two files covered in test coverage report:
     - `b.dart`
     - `c.dart`

**Note:** `a.dart` is not included in the test coverage report.

**Comment by BondarenkoStas** [comment] 2019-09-20 11:53
Duplicate of #27997 which is open.
Please check the last comment there, also a workaround is mentioned.
Closing it. If you disagree, feel free to comment and I will re-open it right away.

**Closed by BondarenkoStas** 2019-09-20 11:53 UTC
