### ISSUE TITLE
gradle.properties

### ISSUE THREAD

**Issue by glennmichaelmejias** [flutter/flutter#42991] opened 2019-10-18 06:10 UTC
everytime i open a project or an example from flutter plugins the gradle.properties format is like this
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=trueandroid.enableR8=true
```

**Comment by BondarenkoStas** [comment] 2019-10-18 11:41
Duplicate of #41016

**Closed by BondarenkoStas** 2019-10-18 11:41 UTC
