### ISSUE TITLE
[flutter camera]: buggy aspect ratio, cannot save to camera roll

### ISSUE THREAD

**Issue by iosephmagno** [flutter/flutter#85563] opened 2021-06-29 18:59 UTC
Hello there,

Camera plugin aspect ratio feature is buggy. We cannot take picture/video at a 3:4 aspect ratio (see #15953 and related ones). 

No one seem responsive on that, nor providing a precise timeline.

We need aspect ratio that:
- works in the controller, so we can take real photo/video in the select aspect ratio (not just previe live camera)
- doesn’t stretch image/video (currently 3:4 ratio looks stretched)

Also, we need to save photo/video to camera roll.

Please kindly report on that because we are investing money on flutter and no one replies.

Ioseph Magno
CEO of Presence

**Comment by TahaTesser** [comment] 2021-06-30 12:25
Hi @iosephmagno 
The original issue has assignee and `P3` priority label which higher than usual issues,  I understand your concerns, I will find out more on the progress of the issue
Closing as duplicate ofhttps://github.com/flutter/flutter/issues/15953

**Closed by TahaTesser** 2021-06-30 12:25 UTC
Labels: in triage

**Comment by iosephmagno** [comment] 2021-07-01 07:01
@TahaTesser I’m not sure that this is entirely covered by #15953. Can you please double check it? The above thread relates to CameraPreview, but aspect ratio needs to work in the controller. Otherwise, even if you fix the “stretch” bug in live preview, we still wouldn’t be able to take photo/video at the select aspect ratio. For example, we set a 3:4 aspect ratio but photo is taken in 16:9. 

Can you please double-check with the team mates working on the camera bugs and let us have a roamap? This should be P2 (Camera is core). Also, you assigned a P5 to our request to add “tap to focus”. We couldn’t even imagine a camera which doesn’t provide touch focus in 2021.

**Comment by TahaTesser** [comment] 2021-07-01 09:49
@iosephmagno 
There could be edge cases, I would suggest waiting for the original issue to get fixed,  even after that if there is something left to cover, I am happy to follow up with you after that, can always tag me for this. 

I'm working on finding out the progress, thanks for the patience.

**Comment by iosephmagno** [comment] 2021-07-01 10:07
@TahaTesser I'm afraid I'm not following you. Can you please check what people are doing? Because what's the use of fixing aspect ratio in Preview mode, if that doesn't allow us to take photo/video in the select aspect ratio? If so, you guys should extend the pending thread (which now is ambiguous). Same rationale applies to the rest. 

As kindly mentioned, we need to have a more clear roadmap.
Thx
