### ISSUE TITLE
Multiple engine instance for multiple windows crashed on Windows platform

### ISSUE THREAD

**Issue by cjng96** [flutter/flutter#66876] opened 2020-09-29 04:32 UTC
## Steps to Reproduce

I tried to make multiple windows on Windows platform by referring to Rodydavis's example as follows,
https://github.com/rodydavis/multi_window
https://github.com/flutter/flutter/issues/30701

But it's not working on Windows platform. :(

For most of the time It crashed and sometimes ran but the graph was broken. (I attached the screenshot)
![broken_screen](https://user-images.githubusercontent.com/6122665/94512934-57e5fd00-0258-11eb-87c0-f752a41bf33b.png)
I guess there are resouces shared by the separated engine instances and view controllers.

The steps I tried.

1. Running the command "flutter create mutilpleTest" to create sample project

2. Adding this code into the windows/runnner/main.cpp
```cpp
flutter::DartProject project(L"data");
FlutterWindow* createNewWindow(std::wstring key, double x, double y, int w, int h, RunLoop* run_loop) {
	FlutterWindow* window = new FlutterWindow(run_loop, project);
	const Win32Window::Point origin((int)x, (int)y);
	Win32Window::Size size(w, h);
	if (!window->CreateAndShow(key, origin, size)) {
		return nullptr;
	}
	window->SetQuitOnClose(true);    
        return window;
}
```

3. Modify the wWinMain function as follows,
```cpp
  //flutter::DartProject project(L"data");
  // FlutterWindow window(&run_loop, project);
  // Win32Window::Point origin(10, 10);
  // Win32Window::Size size(1280, 720);
  // if (!window.CreateAndShow(L"ft", origin, size)) {
  //   return EXIT_FAILURE;
  // }
  // window.SetQuitOnClose(true);
  auto win = createNewWindow(L"base", 10,10,200,200,&run_loop);
  if(win == nullptr) {
	return EXIT_FAILURE;
  }
```

4. Modify run_loop::Run() function like this,
```cpp
RunLoop::~RunLoop() {}

#include "flutter_window.h"
int i = 0;
FlutterWindow* createNewWindow(std::wstring key, double x, double y, int w, int h, RunLoop* run_loop);

void RunLoop::Run() {
  bool keep_running = true;
  TimePoint next_flutter_event_time = TimePoint::clock::now();
  while (keep_running) {
    // Create new window with engine instance after a while
    if(i++ == 1000) {
    	createNewWindow(L"test2", 300,300,300,300,this);
    }
```

**Expected results:** 
The multiple windows with separated engine instacne are running well without a crash and a broken graph.

**Actual results:**
Most time it crashed and sometimes running separated windows but have broken screen.

<details>
  <summary>Logs</summary>

```
[   +9 ms]   -- Installing: C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/kernel_blob.bin
[ +231 ms]   -- Installing: C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/NOTICES
[   +7 ms]   -- Installing: C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/packages
[   +2 ms]   -- Installing: C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons
[   +2 ms]   -- Installing:
C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets
[   +2 ms]   -- Installing:
C:/work_iner/ft/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +18 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
[        ] Done Building Project "C:\work_iner\ft\build\windows\INSTALL.vcxproj" (default targets).
[        ] Build succeeded.
[   +1 ms]     0 Warning(s)
[        ]     0 Error(s)
[        ] Time Elapsed 00:00:14.39
[  +21 ms] Building Windows application... (completed in 15.2s)
[ +982 ms] Observatory URL on device: http://127.0.0.1:1194/g1-UZhmozco=/
[   +7 ms] Caching compiled dill
[  +33 ms] Connecting to service protocol: http://127.0.0.1:1194/g1-UZhmozco=/
[   +4 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:1194/g1-UZhmozco=/.
[ +185 ms] DDS is listening at http://127.0.0.1:1198/z-omDqeblLQ=/.
[  +93 ms] Successfully connected to service protocol: http://127.0.0.1:1194/g1-UZhmozco=/
[   +2 ms] Waiting for Windows to report its views...
[   +6 ms] Waiting for Windows to report its views... (completed in 4ms)
[   +9 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device (file:///C:/Users/cjng96/AppData/Local/Temp/ft9e8aac83/ft/)
[   +3 ms] Updating assets
[  +97 ms] Syncing files to device Windows...
[   +6 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:ft/main.dart 9cd7c8b9-3270-4a7a-801c-17e5fa4bc348
[   +1 ms] <- 9cd7c8b9-3270-4a7a-801c-17e5fa4bc348
[  +89 ms] Updating files
[ +114 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Windows... (completed in 215ms)
[   +1 ms] Synced 1.8MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x19978dc8590.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload.
[   +3 ms] R Hot restart.
[   +2 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +2 ms] c Clear the screen
[   +2 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:1198/z-omDqeblLQ=/
[+6381 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///C:/Users/cjng96/AppData/Local/Temp/ft9e8aac83/ft/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 24,249ms.
[ +265 ms] ensureAnalyticsSent: 260ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
Analyzing ft...
No issues found! (ran in 1.8s)
```

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.401, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.401 at c:\flutter
    • Framework revision 9efdcf61d2 (6 hours ago), 2020-09-28 18:22:02 -0400
    • Engine revision 77701d303e
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at c:\android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = c:\android-sdk
    • Java binary at: C:\Program Files (x86)\Java\jdk8u202-b08\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\cjng96\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.63

! Doctor found issues in 2 categories.
![broken_screen](https://user-images.githubusercontent.com/6122665/94512314-b316f000-0256-11eb-88a0-3aa0e2748276.png)

```

</details>

**Comment by TahaTesser** [comment] 2020-09-29 13:37
Hi @cjng96 
When trying to reproduce with your changes, I am just getting a blank window with the following 
```
Warning: File "C:\Users\Taha\AndroidStudioProjects\master_flutter\pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
The timestamp was: 2020-09-29 14:14:31.000
The time now is: 2020-09-29 13:31:16.012053
Launching lib\main.dart on Windows in debug mode...
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method lastWindowKey on channel window_controller)
#0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:157
<asynchronous suspension>
#1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:332
#2      WindowController.lastWindowKey 
package:master_flutter/window_manager.dart:81
#3      main 

```

Can you please provide your a complete reproducible minimal code sample  in a repository 
Thank you

**Comment by cjng96** [comment] 2020-09-29 14:22
[ft.zip](https://github.com/flutter/flutter/files/5299680/ft.zip)

Thank you for your reply.

This source is what I tried with the command
$ flutter run -d windows

Thank you again.

**Comment by stuartmorgan** [comment] 2020-09-29 16:42
This is a duplicate of https://github.com/flutter/flutter/issues/53372

**Closed by stuartmorgan** 2020-09-29 16:42 UTC
Labels: in triage
