### ISSUE TITLE
Title in Scaffold AppBar does not show head characters correctly in RTL 

### ISSUE THREAD

**Issue by zarinfam** [flutter/flutter#15974] opened 2018-03-27 13:42 UTC
In RTL TextDirection when use Scaffold widget, its AppBar does not show head characters correctly.
I use Flutter (Channel beta, v0.1.5) 

![image](https://user-images.githubusercontent.com/1052394/37970523-f1505ef6-31e8-11e8-8489-0bb6ee1cc3be.png)

**Comment by zoechi** [comment] 2018-03-27 13:44
Can you please also try in `dev` channel. There were quite a few changes since beta was released

**Comment by zarinfam** [comment] 2018-03-27 20:00
In `dev` channel `TextOverflow.ellipsis` worked fine but `TextOverflow.clip` and `TextOverflow.fade` did not work correctly.

**Comment by zoechi** [comment] 2018-03-28 05:40
`master` channel might be worth a try as well for this topic, just to figure out if it's already fixed.

**Comment by zarinfam** [comment] 2018-03-28 10:16
`master` channel was like `dev` channel.

**Comment by zoechi** [comment] 2019-01-16 15:31
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment] 2019-01-16 15:32
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-02-12 07:54
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-12 07:54 UTC
Labels: a: typography, framework, waiting for customer response
