### ISSUE TITLE
sumsug android 14 after PlatformView from background  to foreground, it will become to disappear, because surface has been release , it need to recreate.

### ISSUE THREAD

**Issue by suzhengda** [flutter/flutter#145896] opened 2024-03-28 13:28 UTC
### Steps to reproduce

1. setup an PlatformView
2. start app. and let app turn to background
3. after a while, turn app to foreground
4. the platformview will become to disappear

### Expected results

 platformview don't  disappear

### Actual results

 platformview disappear

### Code sample

like FlutterWebviewPlugin with Surface mode.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-28 13:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139039. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-03-28 13:53 UTC
Labels: in triage
