### ISSUE TITLE
GoogleSignInAuthentication null idToken and GoogleSignInAccount.signIn never returns

### ISSUE THREAD

**Issue by alex-sue** [flutter/flutter#77650] opened 2021-03-08 22:58 UTC
Hi there,

  I'm seeing inconsistent things happening trying to integrate the google_sign_in (v 4.5.9) package for Android.  At times, it works, then I'll go to lunch and come back and then the idToken when trying to get the GoogleSignInAuthentication is null.  I have to sign out using the signOut method, but then when I call signIn again, the GoogleSignInAccount.signIn method never returns so I'm endlessly waiting.  After cleaning, uninstalling, rebuilding a couple times will it eventually give me back a JWT again.  Actually, I'm not sure what I did to get it to work again, I added a print statement.

I'm not sure how to get code to reproduce this.  I created a brand new project to try and reproduce the issue, but of course, it's ok there.  Well if there's any pointers on what could be causing the null idToken or signIn to never complete, that'd be a great help.

Thank you for your time

Below is from flutter doctor -v

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/alex/installs/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by alex-sue** [comment] 2021-03-11 02:30
hey @TahaTesser, thanks for the response!

Yes, I've brought over all the packages into the new project and it works perfectly.  One thing I didn't mention was that after moving back to the original project and cleaning and rebuilding a billion times, i just deleted the whole folder and recloned my project.  It then started working again like magic.  At a loss for words, i built an apk and loaded it on my phone (Android 10.0) and it exhibited signs of the signIn method not returning.  i turned off the device since it was the end of the day.  This morning, I turned it back on and started up the app.  It looked like the idToken, so it passed the signIn method and then failed my validation so it went back to the sign in screen.  I tapped it and it's working now.

So I eventually just copied all my dart code into the new project that works with the google_sign_in plugin and everything is working just fine so far.

I'm trying to slowly remove things to get a consistently reproducible project.  I just thought I'd reach out to see if there was an obvious reason the idToken returns as null, like maybe if the token was expired already or something. Ok, well will update on progress when I find something

Thanks!

**Comment by TahaTesser** [comment] 2021-03-11 08:37
Hi @alex-sue 
If you figure the cause, please provide details from https://github.com/flutter/flutter/issues/77650#issuecomment-793597038
Thank you

**Comment by pedromassangocode** [comment] 2021-04-07 12:44
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:44 UTC
Labels: in triage, waiting for customer response
