### ISSUE TITLE
DropdownButton throws exception when hint and selectedItemBuilder is provided

### ISSUE THREAD

**Issue by crtl** [flutter/flutter#65748] opened 2020-09-14 08:12 UTC
This issue already was posted before in [#42340](https://github.com/flutter/flutter/issues/42340) but still occurs on master.

## Steps to Reproduce

1. Create a `DropdownButton` with `hint` and `selectedItemBuilder`

**Expected results:** 
Button should work

**Actual results:**
Exception is thrown:

<details><summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building DropdownButton<String>(dirty, dependencies:
[Directionality, _InheritedTheme, MediaQuery, _LocalizationsScope-[GlobalKey#2b9e0]], state:
_DropdownButtonState<String>#f399a):
type 'DefaultTextStyle' is not a subtype of type 'Center' of 'value'
The relevant error-causing widget was:
  DropdownButton<String>
  file:///D:/dev/flutter/project/lib/screens/enter_details_screen.dart:60:20
When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart)
#1      _DropdownButtonState.build (package:flutter/src/material/dropdown.dart:1327:13)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#11     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#52     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#64     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#93     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#101    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#103    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#111    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#124    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#144    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#149    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#156    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#161    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#163    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#167    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#170    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#172    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#176    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#178    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#182    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#187    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#188    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#189    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#190    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#191    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#192    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
Flutter 1.22.0-10.0.pre.161 • channel master • https://github.com/flutter/flutter.git
Framework • revision cba91c97d0 (8 hours ago) • 2020-09-13 18:57:03 -0400
Engine • revision 2fc054147e
Tools • Dart 2.10.0 (build 2.10.0-121.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0-10.0.pre.161, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 4.0)

```

</details>

**Comment by pedromassangocode** [comment] 2020-09-14 10:37
I was able to reproduce this on latest master channel. This is a regression since was previously fixed by https://github.com/flutter/flutter/pull/42342.

Cc @shihaohong  who previously worked on a fix for https://github.com/flutter/flutter/issues/42340. Just FYI.

<details><summary>Logs</summary>

```
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 4,407ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building DropdownButton<String>(dirty, dependencies: [_InheritedTheme, MediaQuery, _LocalizationsScope-[GlobalKey#84c53]], state: _DropdownButtonState<String>#ec685):
type 'DefaultTextStyle' is not a subtype of type 'Text' of 'value'

The relevant error-causing widget was: 
  DropdownButton<String> file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:33:16
When the exception was thrown, this was the stack: 
#0      List.add (dart:core-patch/growable_array.dart)
#1      _DropdownButtonState.build (package:flutter/src/material/dropdown.dart:1327:13)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building DropdownButton<String>(dirty, dependencies: [_InheritedTheme, MediaQuery, _LocalizationsScope-[GlobalKey#84c53]], state: _DropdownButtonState<String>#ec685):
type 'DefaultTextStyle' is not a subtype of type 'Text' of 'value'

The relevant error-causing widget was: 
  DropdownButton<String> file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:33:16
When the exception was thrown, this was the stack: 
#0      List.add (dart:core-patch/growable_array.dart)
#1      _DropdownButtonState.build (package:flutter/src/material/dropdown.dart:1327:13)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details><summary>sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Test')),
        body: MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<String> items = <String>['Item 1', 'Item 2', 'Item 3'];
  String selectedItem = 'Item 1';

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 12.0),
        child: DropdownButton<String>(
          hint: Text('Here is a hint'),
          value: selectedItem,
          onChanged: (String string) => setState(() => selectedItem = string),
          selectedItemBuilder: (BuildContext context) {
            return items.map((String item) {
              return Text(item);
            }).toList();
          },
          items: items.map((String item) {
            return DropdownMenuItem<String>(
              child: Text(item),
              value: item,
            );
          }).toList(),
        ),
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.161 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision cba91c97d0 (12 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by crtl** [comment] 2020-09-15 08:03
The same happened when using `disabledHint`.

**Comment by maheshmnj** [comment] 2020-10-13 13:11
The temporary workaround for this is to use one of them based on the selected dropdownValue
```
   DropdownButton<String>(
              value: dropdownValue,
              style: TextStyle(color: Colors.grey, fontSize: 15),
              hint: dropdownValue != null
                  ? null
                  : Text(
                      'Select Value',
                      style: TextStyle(color: Colors.black),
                    ),
              onChanged: (value) => setState(() => dropdownValue = value),
              selectedItemBuilder: dropdownValue == null
                  ? null
                  : (BuildContext context) {
                      return ['ONE', 'TWO.', 'THREE'].map((String value) {
                        return Text(
                          dropdownValue,
                          style: TextStyle(color: Colors.green),
                        );
                      }).toList();
                    },
              items: ['ONE', 'TWO.', 'THREE']
                  .map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value,
                      style: TextStyle(inherit: false, color: Colors.red)),
                );
              }).toList(),
            ),
```
you can find a [dartpad example here ](https://dartpad.dev/05c40d6ec34b3dce935bd984c5bda199)

**Closed** 2020-10-14 08:52 UTC
Labels: f: material design, found in release: 1.20, found in release: 1.22, framework, has reproducible steps, severe: crash, severe: regression
