### ISSUE TITLE
java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by aarifali** [flutter/flutter#30900] opened 2019-04-11 09:18 UTC
E:\Dev. Requirement\RD Android\tlb_assistant\tlb_assistant>flutter build apk --release
Initializing gradle...                                              2.4s
Resolving dependencies...                                           7.8s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: D:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.8.0+3\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrid
es a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+2\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseInstanceIDService.jav
a uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.0.3\android\src\main\java\io\github\ponnamkarthik\toast\fluttertoast\FluttertoastPlugin.java uses or overri
des a deprecated API.
Running Gradle task 'assembleRelease'... Done                     149.1s (!)
Built build\app\outputs\apk\release\app-release.apk (9.4MB).

D:\Flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-IN)
    • Flutter version 1.2.1 at D:\Flutter\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by d-apps** [comment] 2019-07-06 18:29
Is this causing an issue? Because that's just a note/warning, we'll need to wait for flutter team update java classes for this plugins.
It doesn't stop you to build the app, at least.

**Comment by escamoteur** [comment] 2019-10-01 13:16
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment] 2019-11-08 09:09
Hi @aarifali 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-11-08 09:09 UTC
Labels: a: error message, waiting for customer response
