### ISSUE TITLE
PageView + PageView + ListView + viewportFraction -> ScrollController attached to multiple scroll views.

### ISSUE THREAD

**Issue by deimantasa** [flutter/flutter#63359] opened 2020-08-10 06:54 UTC
Hello,

I've discovered a bug in framework.

**Full code** (Update 1)
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({
    Key key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final PageController _parentPageController = PageController(viewportFraction: 1);
  final PageController _childPageController = PageController();
  final ScrollController _scrollController = ScrollController();

  List<List<FlutterLogo>> _listOfFlutterLogos = [];
  int _currentPage = 0;
  Map<int, int> childSelectionMap = {};

  @override
  void dispose() {
    _parentPageController.dispose();
    _childPageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home"),
        actions: [
          FlatButton(
            child: Text("Add Parent"),
            onPressed: () {
              setState(() {
                _listOfFlutterLogos.add([FlutterLogo()]);
              });
            },
          ),
          FlatButton(
            child: Text("Add Child"),
            onPressed: () {
              setState(() {
                _listOfFlutterLogos[_currentPage].add(FlutterLogo());
              });
            },
          ),
        ],
      ),
      body: PageView.builder(
          controller: _parentPageController,
          itemCount: _listOfFlutterLogos.length,
          onPageChanged: (parentPage) {
            setState(() {
              _currentPage = parentPage;
            });
          },
          itemBuilder: (context, parentIndex) {
            List<FlutterLogo> flutterLogos = _listOfFlutterLogos[parentIndex];
            return Column(
              children: [
                Expanded(
                  child: PageView.builder(
                      physics: NeverScrollableScrollPhysics(),
                      controller: _childPageController,
                      onPageChanged: (childPage) {
                        setState(() {
                          childSelectionMap[_currentPage] = childPage;
                        });
                      },
                      itemCount: flutterLogos.length,
                      itemBuilder: (context, childIndex) {
                        FlutterLogo flutterLogo = flutterLogos[childIndex];
                        return Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Expanded(child: flutterLogo),
                          ],
                        );
                      }),
                ),
                Expanded(
                  child: ListView.builder(
                      controller: _scrollController,
                      scrollDirection: Axis.horizontal,
                      itemCount: flutterLogos.length,
                      itemBuilder: (context, flutterLogoIndex) {
                        return InkWell(
                          onTap: () {
                            setState(() {
                              _childPageController.animateToPage(flutterLogoIndex,
                                  duration: kTabScrollDuration, curve: Curves.easeIn);
                            });
                          },
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Container(
                                width: 60,
                                height: 60,
                                child: flutterLogos[flutterLogoIndex],
                              ),
                              Container(
                                color: childSelectionMap[_currentPage] == flutterLogoIndex ? Colors.blue : Colors.transparent,
                                height: 10,
                                width: 20,
                              )
                            ],
                          ),
                        );
                      }),
                ),
                Text("Total Parent Lists: ${_listOfFlutterLogos.length}"),
                Text("Current Page: $_currentPage"),
              ],
            );
          }),
    );
  }
}
```
**Reproduction steps:**

1. Run app;
2. Click on `Add Parent` 3 times (until you see `Total Parent Lists: 3`);
3. Scroll to next page (`Current Page: 1`);
4. Click on `Add Child` 3 times;
5. Click on any of the child widgets on the bottom.

```
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 113 pos 12: '_positions.length == 1'
```

Without `viewportFraction` it works well. 

Looking forward for any advice in this case.

**Comment by darshankawar** [comment] 2020-08-10 14:06
Hi @zeromaro,
I tried your code and it does throw the exception upon tapping on child widgets, but the error says `ScrollController attached to multiple scroll views`.
Can you try to make `ScrollController` variable and add it as a `controller` and see if it works ?

**Comment by zeromaro** [comment] 2020-08-10 23:37
Hello @darshankawar ,

I've added scroll controller - behaviour didn't change. With `viewportFraction` less than 1 it will still crash.

**Comment by darshankawar** [comment] 2020-08-11 06:23
Issue is replicable on latest Stable (1.20.1).

**Comment by xu-baolin** [comment] 2020-08-12 02:08
Can not repro on up-to-date master-branch,
```
PS F:\flutter_dev\src_new\flutter> flutter doctor -v
[√] Flutter (Channel master, 1.21.0-8.0.pre.172, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.21.0-8.0.pre.172 at F:\flutter_dev\src_new\flutter
    • Framework revision 8dcb4c338a (2 hours ago), 2020-08-11 17:29:35 -0700
    • Engine revision 06458d2f6c
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (2 available)
    • PDCM00 (mobile)   • 9LL7VO8XUOIN75ZH • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.17763.615]

• No issues found!
```

**Comment by Jojoooo1** [comment] 2020-09-15 22:43
I am having the same issue.

**Comment by AcnoSaga** [comment] 2020-09-21 12:38
I have a vertical `PageView`, inside each page there's a vertical `CustomScrollView` (scrolling has been implemented manually through `RawGestureDetector`).

I have to manage a `List` of `ScrollController`s, since each `CustomScrollView` needs a `controller` through which I'm handling vertical swipes (I have to manage if the screen gets scrolled or the page gets changed).
```
import 'package:floating_bottom_navigation_bar/floating_bottom_navigation_bar.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:get/get.dart';
import 'package:tethered/screens/components/gap.dart';
import 'package:tethered/screens/home/book_details_page/components/book_details_info_text.dart';
import 'package:tethered/theme/size_config.dart';
import 'package:tethered/utils/colors.dart';
import 'package:tethered/utils/text_styles.dart';
import 'package:zefyr/zefyr.dart';

class ReadingPage extends StatefulWidget {
  @override
  _ReadingPageState createState() => _ReadingPageState();
}

class _ReadingPageState extends State<ReadingPage> {
  PageController _pageController;
  List<ScrollController> _listScrollControllers;
  ScrollController _activeScrollController;
  Drag _drag;
  ValueNotifier<bool> _isVisible = ValueNotifier(true);

  Null Function() Function(ScrollController) _changeBarVisibility;

  int numberOfPages = 15;
  int currentIndex = 0;

  @override
  void initState() {
    super.initState();
    _pageController = PageController(
      initialPage: 0,
      viewportFraction: 1,
      keepPage: true,
    );
    if (numberOfPages <= 3) {
      _listScrollControllers = List.filled(
        numberOfPages,
        ScrollController(),
        growable: true,
      );
    } else {
      _listScrollControllers = List.filled(
        3,
        ScrollController(),
        growable: true,
      );
    }

    _listScrollControllers.forEach((controller) {
      if (_changeBarVisibility == null) {
        _changeBarVisibility = (ScrollController scrollController) => () {
              // ignore: invalid_use_of_protected_member
              scrollController.positions.forEach((position) {
                if (position.userScrollDirection == ScrollDirection.reverse) {
                  _isVisible.value = false;
                }
                // ignore: invalid_use_of_protected_member
                if (position.userScrollDirection == ScrollDirection.forward) {
                  _isVisible.value = true;
                }
              });
            };
      }
      controller.addListener(_changeBarVisibility(controller));
    });
  }

  @override
  void dispose() {
    _pageController.dispose();
    _listScrollControllers.forEach((controller) {
      controller.removeListener(_changeBarVisibility(controller));
      controller.dispose();
    });
    super.dispose();
  }

  void _handleDragStart(DragStartDetails details) {
    if (_listScrollControllers[currentIndex].hasClients &&
        _listScrollControllers[currentIndex].position.context.storageContext !=
            null) {
      final RenderBox renderBox = _listScrollControllers[currentIndex]
          .position
          .context
          .storageContext
          .findRenderObject();
      if (renderBox.paintBounds
          .shift(renderBox.localToGlobal(Offset.zero))
          .contains(details.globalPosition)) {
        _activeScrollController = _listScrollControllers[currentIndex];
        _drag = _activeScrollController.position.drag(details, _disposeDrag);
        return;
      }
    }
    _activeScrollController = _pageController;
    _drag = _pageController.position.drag(details, _disposeDrag);
  }

  void _handleDragUpdate(DragUpdateDetails details) {
    var scrollDirection = _activeScrollController.position.userScrollDirection;

    if (_activeScrollController == _listScrollControllers[currentIndex] &&
        ((scrollDirection == ScrollDirection.reverse) &&
                _activeScrollController.offset.roundToDouble() >=
                    _activeScrollController.position.maxScrollExtent
                        .roundToDouble() ||
            (scrollDirection == ScrollDirection.forward) &&
                _activeScrollController.offset < 0)) {
      _activeScrollController = _pageController;
      _drag?.cancel();
      _drag = _pageController.position.drag(
        DragStartDetails(
          globalPosition: details.globalPosition,
          localPosition: details.localPosition,
        ),
        _disposeDrag,
      );
    }
    _drag?.update(details);
  }

  void _handleDragEnd(DragEndDetails details) {
    _drag?.end(details);
  }

  void _handleDragCancel() {
    _drag?.cancel();
  }

  void _disposeDrag() {
    _drag = null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: ValueListenableBuilder<bool>(
          valueListenable: _isVisible,
          builder: (context, isVisible, _) {
            return AnimatedContainer(
              color: TetheredColors.primaryDark,
              duration: Duration(milliseconds: 200),
              height: isVisible ? sx * 10 : 0.0,
              child: AnimatedContainer(
                duration: Duration(milliseconds: 200),
                height: isVisible ? sx * 10 : 0.0,
                width: sy * 90,
                child: Wrap(
                  children: [
                    Align(
                      alignment: Alignment.center,
                      child: FloatingNavbar(
                        unselectedItemColor: Colors.white,
                        selectedItemColor: Colors.white,
                        selectedBackgroundColor: Colors.transparent,
                        backgroundColor: Colors.transparent,
                        onTap: (int val) {
                          //returns tab id which is user tapped
                          _pageController.nextPage(
                              duration: Duration(milliseconds: 500),
                              curve: Curves.easeOutSine);
                        },
                        currentIndex: 0,
                        items: [
                          FloatingNavbarItem(icon: Icons.home, title: 'Home'),
                          FloatingNavbarItem(
                              icon: Icons.explore, title: 'Explore'),
                          FloatingNavbarItem(
                              icon: Icons.chat_bubble_outline, title: 'Chats'),
                          FloatingNavbarItem(
                              icon: Icons.settings, title: 'Settings'),
                        ],
                      ),
                    )
                  ],
                ),
              ),
            );
          }),
      // extendBody: true,

      // bottomNavigationBar: Container(),
      // backgroundColor: TetheredColors.primaryDark,
      body: ZefyrTheme(
        data: ZefyrThemeData(
          attributeTheme: AttributeTheme(
            bold: TextStyle(
              color: Colors.deepOrange,
            ),
            heading1: LineTheme(
              textStyle: TextStyle(color: Colors.blue),
              padding: EdgeInsets.zero,
            ),
          ),
        ),
        child: RawGestureDetector(
          gestures: <Type, GestureRecognizerFactory>{
            VerticalDragGestureRecognizer: GestureRecognizerFactoryWithHandlers<
                    VerticalDragGestureRecognizer>(
                () => VerticalDragGestureRecognizer(),
                (VerticalDragGestureRecognizer instance) {
              instance
                ..onStart = _handleDragStart
                ..onUpdate = _handleDragUpdate
                ..onEnd = _handleDragEnd
                ..onCancel = _handleDragCancel;
            })
          },
          behavior: HitTestBehavior.opaque,
          child: PageView.builder(
              physics: NeverScrollableScrollPhysics(),
              dragStartBehavior: DragStartBehavior.down,
              controller: _pageController,
              scrollDirection: Axis.vertical,
              itemCount: numberOfPages,
              onPageChanged: (index) {
                setState(() {
                  // if (currentIndex > index) {
                  //   final newController = ScrollController();
                  //   // newController.addListener(_changeBarVisibility);
                  //   _listScrollControllers[index] = newController;
                  // }

                  if (_listScrollControllers.length < numberOfPages &&
                      currentIndex < index) {
                    final newController = ScrollController();
                    newController
                        .addListener(_changeBarVisibility(newController));
                    _listScrollControllers.add(newController);
                  }
                  currentIndex = index;
                  // _activeScrollController = _listScrollControllers[index];
                });
              },
              itemBuilder: (context, index) => CustomScrollView(
                    physics: NeverScrollableScrollPhysics(),
                    controller: _listScrollControllers[index],
                    slivers: [
                      SliverAppBar(
                        actions: [],
                        backgroundColor: TetheredColors.primaryDark,
                        floating: true,
                      ),
                      SliverToBoxAdapter(
                        child: Padding(
                          padding: EdgeInsets.symmetric(horizontal: sy * 4),
                          child: Column(
                            children: [
                              Gap(height: 5),
                              Text(
                                'The Story of How London Got Its Name',
                                textAlign: TextAlign.center,
                                style:
                                    TetheredTextStyles.authSubHeading.copyWith(
                                  color: TetheredColors.readingPageTitle,
                                ),
                              ),
                              Gap(height: 5),
                              Wrap(
                                alignment: WrapAlignment.center,
                                children: [
                                  BookDetailsInfoText(
                                    icon: Icons.visibility,
                                    text: '21M views',
                                    color: TetheredColors.readingPageInfo,
                                  ),
                                  BookDetailsInfoText(
                                    icon: Icons.arrow_upward,
                                    text: '12K upvotes',
                                    color: TetheredColors.readingPageInfo,
                                  ),
                                  BookDetailsInfoText(
                                    icon: Icons.list,
                                    text: '21 Tethers',
                                    color: TetheredColors.readingPageInfo,
                                  ),
                                ],
                              ),
                              Gap(height: 5),
                              ZefyrView(
                                document: NotusDocument.fromJson(content),
                              ),
                              Gap(height: 5),
                            ],
                          ),
                        ),
                      ),
                    ],
                  )),
        ),
      ),
    );
  }
```

This is the code for the screen. It's a big project, so there's a lot of unrelated stuff.

I am getting this `ScrollController attached to multiple scroll views` issue too. I would appreciate it if someone can help

These are the dependencies:

```
dependencies:
  flutter:
    sdk: flutter
  get: ^3.10.2
  injectable: ^1.0.4
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  get_it: ^4.0.2
  carousel_slider: ^2.2.1
  badges: ^1.1.1
  cached_network_image: ^2.3.2+1
  shimmer: ^1.1.1
  pull_to_refresh: ^1.6.1
  flutter_spinkit: "^4.1.2"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_bloc: ^6.0.1
  provider: ^4.3.2+2
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
  notus: ^0.1.5
  floating_bottom_navigation_bar: ^1.4.1
  flutter_snake_navigationbar: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  injectable_generator: ^1.0.4
```

**Comment by deimantasa** [comment] 2020-09-21 12:45
I was able to solve the issue after some refactor and after I've extracted widgets to `StatefulWidget` classes. However I still think it's some kind of bug.

**Comment by sangle1996** [comment] 2020-10-12 09:45
I have the same issue here, so confusing with this bug

**Comment by OmarBakry-eg** [comment] 2021-05-17 20:37
Hello , i've the same issue here and thats my code 
SingleChildScrollView(
                                          physics: NeverScrollableScrollPhysics(),
                                          child: Column(
                                            children: [
                                              Container(
                                                width: 344,
                                                height: 235,
                                                decoration: BoxDecoration(
                                                  color: Colors.black12,
                                                  borderRadius: BorderRadius.circular(25.0),
                                                ),
                                                child: ClipRRect(
                                                  borderRadius: BorderRadius.circular(25.0),
                                                  child: PageView.builder(
                                                    itemCount: myPosts[i].images.length,
                                                    scrollDirection: Axis.horizontal,
                                                    controller: _pageController,
                                                    itemBuilder: (c, ind) => CachedNetworkImage(
                                                      errorWidget: (context, url, error) => Icon(Icons.error),
                                                      placeholder: (context, url) => FittedBox(
                                                        fit: BoxFit.none,
                                                        child: Container(
                                                          width: 80,
                                                          height: 80,
                                                          child: CircularProgressIndicator(
                                                            valueColor: AlwaysStoppedAnimation<Color>(Colors.blueGrey),
                                                          ),
                                                        ),
                                                      ),
                                                      imageUrl: myPosts[i].images[ind],
                                                      fit: BoxFit.fill,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              myPosts[i].images.length == 1
                                                  ? Offstage()
                                                  : Padding(
                                                      padding: EdgeInsets.only(top: 10),
                                                      child: SmoothPageIndicator(
                                                        controller: _pageController,
                                                        count: myPosts[i].images.length,
                                                        effect: WormEffect(),
                                                      ),
                                                    ),
                                            ],
                                          ),
                                        ),
                                        
                                        
             I using   smooth_page_indicator: ^0.2.3

**Comment by Piinks** [comment] 2022-03-08 18:37
This comment may be of some help from similar issue: https://github.com/flutter/flutter/issues/63458#issuecomment-718348235
You cannot access the `position` of a ScrollController and manipulate it if there is more than one attached. You can check first if there is more than one position, or access the one you want directly using the getter ScrollController.positions.

I am going to close this as I think it is working as intended, but if not, please update and we will take another look! Thanks!

**Closed by Piinks** 2022-03-08 18:37 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 1.20
