### ISSUE TITLE
[webview_flutter] webview hides behind other widgets in a column when scroll down on iOS

### ISSUE THREAD

**Issue by duy1998** [flutter/flutter#78383] opened 2021-03-17 02:04 UTC
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-VN)
    • Flutter version 2.0.1 at /Users/dinhcongduy1998yahoo.com.vn/Downloads/flutter
    • Framework revision c5a4b4029c (12 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dinhcongduy1998yahoo.com.vn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone (mobile)            • 00008030-001621562E6B802E            • ios • iOS 14.3
    • iPhone 12 Pro Max (mobile) • 07540BDB-42A1-4586-9083-3CACF2102F58 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```
</details>

Problem:
I'm trying build UI have Webview at top in a column. However, when scroll down fast webview is still render apart at top and hide below widgets in a column.

Thanks for reviewing

https://user-images.githubusercontent.com/43132958/111403501-a94b5100-86ff-11eb-99be-d0f5556063c2.MP4

**Comment by pedromassangocode** [comment] 2021-03-17 07:32
Hi @duy1998 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by duy1998** [comment] 2021-03-17 08:26
> Hi @duy1998
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

This is code example:
import 'package:flutter/material.dart';
import 'package:webview_flutter_plus/webview_flutter_plus.dart';

void main() {
  runApp(WebViewPlusExample());
}

class WebViewPlusExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebViewPlusExampleMainPage(),
    );
  }
}

class WebViewPlusExampleMainPage extends StatefulWidget {
  @override
  _WebViewPlusExampleMainPageState createState() =>
      _WebViewPlusExampleMainPageState();
}

class _WebViewPlusExampleMainPageState
    extends State<WebViewPlusExampleMainPage> {
  WebViewPlusController _controller;
  double _height = 1000;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('webview_flutter_plus Example'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              height: 100,
              child: WebViewPlus(
                initialUrl: 'assets/index.html',
                onWebViewCreated: (controller) {
                  this._controller = controller;
                },
                onPageFinished: (url) {
                  _controller.getHeight().then((double height) {
                    print("Height: " + height.toString());
                    setState(() {
                      _height = height;
                    });
                  });
                },
                javascriptMode: JavascriptMode.unrestricted,
              ),
            ),
            Column(
              children: List.generate(
                  1000,
                  (index) => Container(
                        height: 200,
                        width: 200,
                        child: Text(index.toString()),
                      )),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by pedromassangocode** [comment] 2021-03-17 11:38
Hi @duy1998 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/shah-xad/webview_flutter_plus).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by duy1998** [comment] 2021-03-18 01:03
> Hi @duy1998
> From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/shah-xad/webview_flutter_plus).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.
> Thank you
The Webview package is similar. 

Code example:
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(WebViewPlusExample());
}

class WebViewPlusExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebViewPlusExampleMainPage(),
    );
  }
}

class WebViewPlusExampleMainPage extends StatefulWidget {
  @override
  _WebViewPlusExampleMainPageState createState() =>
      _WebViewPlusExampleMainPageState();
}

class _WebViewPlusExampleMainPageState
    extends State<WebViewPlusExampleMainPage> {
  WebViewPlusController _controller;
  double _height = 1000;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('webview_flutter_plus Example'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              height: 100,
              child: WebView(
                initialUrl: 'assets/index.html',
                javascriptMode: JavascriptMode.unrestricted,
              ),
            ),
            Column(
              children: List.generate(
                  1000,
                  (index) => Container(
                        height: 200,
                        width: 200,
                        child: Text(index.toString()),
                      )),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by pedromassangocode** [comment] 2021-03-18 11:06
I can reproduce this issue on latest master channel.


<details>
<summary>flutter doctor -v</summary>

```bash
/Users/pedromassango/Code/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 2.1.0-13.0.pre.160, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.160 at /Users/pedromassango/Code/flutter_master
    • Framework revision f4e5354580 (42 minutes ago), 2021-03-18 06:21:01 -0400
    • Engine revision 38c4dac68b
    • Dart version 2.13.0 (build 2.13.0-148.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554                        • android-x64    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by duy1998** [comment] 2021-03-19 01:54
> I can reproduce this issue on latest master channel. WebView scroll if I replace `Column` with `ListView` widget!
> 
> flutter doctor -v

If you use ListView. The height of Webview may differ every time rebuild when you scroll.
Using ListView is my first solution but failed.


```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(WebViewPlusExample());
}

class WebViewPlusExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebViewPlusExampleMainPage(),
    );
  }
}

class WebViewPlusExampleMainPage extends StatefulWidget {
  @override
  _WebViewPlusExampleMainPageState createState() =>
      _WebViewPlusExampleMainPageState();
}

class _WebViewPlusExampleMainPageState
    extends State<WebViewPlusExampleMainPage> {
  WebViewController _controller;
  String kNavigationExamplePage = '''
<!DOCTYPE html><html>
<head><title>Navigation Delegate Example</title></head>
<body>
<p>
The navigation delegate is set to block navigation to the youtube website.
</p>
<ul>
<ul><a href="https://www.youtube.com/">https://www.youtube.com/</a></ul>
<ul><a href="https://www.google.com/">https://www.google.com/</a></ul>
</ul>
</body>
</html>
''';
  double heightWebview = 200;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('webview_flutter_plus Example'),
      ),
      body: ListView(
        shrinkWrap: true,
        children: [
          Container(
            height: heightWebview,
            child: WebView(
              initialUrl: kNavigationExamplePage,
              javascriptMode: JavascriptMode.unrestricted,
              gestureNavigationEnabled: false,
              onWebViewCreated: (webViewController) {
                _controller = webViewController;
                final String contentBase64 = base64Encode(
                    const Utf8Encoder().convert(kNavigationExamplePage));
                _controller.loadUrl('data:text/html;base64,$contentBase64');
              },
              onPageFinished: (url) async {
                // if (_controller != null) {
                //   _title = await _controller
                //       .evaluateJavascript('window.document.title');
                //   setState(() {});
                // }
                if (_controller != null) {
                  heightWebview = double.parse(
                      (await _controller?.evaluateJavascript(
                              'document.documentElement.scrollHeight;')) ??
                          '0');
                  if (mounted) {
                    setState(() {});
                  }
                }
              },
            ),
          ),
          Column(
            children: List.generate(
                1000,
                (index) => Container(
                      height: 200,
                      width: 200,
                      color: Colors.red,
                      child: Text(index.toString()),
                    )),
          )
        ],
      ),
    );
  }
}

```

Video demo:

https://user-images.githubusercontent.com/43132958/111720426-6967a380-8890-11eb-97bc-d24924244aec.MP4

In the video, you can see the height of the webview is differ after rebuilding when scrolling to top.

**Comment by mouseface99** [comment] 2021-04-08 01:52
I've encounter the same issue while embedded webview_flutter within my app

And I've found that the blocking block size may related to the scrolling speed. The fast you scroll, the bigger block may remains on the screen.

It seems the refresh rate is too low for webview so the last frame position still stuck on the screen and haven't been update.

`flutter doctor -v`

```
Last login: Wed Apr  7 09:37:18 on console
~ ❯ flutter doctor -v                                                                                      09:47:15
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.1 20C69 darwin-arm, locale zh-Hant-TW)
    • Flutter version 2.0.3 at /Users/mike/sdk/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mike/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mike/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Mike 的 iPhone (mobile) • 00008030-0009703C2690802E • ios            • iOS 14.4
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.114
```

And this issue only appear on iOS platform.

**Comment by TahaTesser** [comment] 2021-04-12 14:22
Closing as duplicate of  https://github.com/flutter/flutter/issues/76097

**Closed by TahaTesser** 2021-04-12 14:22 UTC
Labels: P4, a: platform-views, f: scrolling, found in release: 2.1, has reproducible steps, p: first party, p: webview, platform-ios, plugin
