### ISSUE TITLE
[Engine] Image assets manager hangs flutter engine on Android

### ISSUE THREAD

**Issue by VolodymyrLykhonis** [flutter/flutter#16783] opened 2018-04-20 03:07 UTC
## Steps to Reproduce

Upon loading asset image (on some phones, in some side state), the flutter engine hangs, while actual process continues to execute. Sometimes, Android produces ANR error.

I am on `v0.3.0`. If I switch to `beta` I get compilation error:

```
Initializing gradle...                                       1.0s
Resolving dependencies...                                    0.9s
Running 'gradlew assembleDebug'...                               
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
compiler message: Unhandled exception:
Crash when compiling file://.....lib/main.dart,
at character offset 6566:
lib/main.dart: Internal problem: Unhandled this in defaultTreeNode.
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#11     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#12     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#13     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#14     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#15     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#17     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#18     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#19     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#20     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#21     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#22     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#23     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#28     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#29     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#30     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#35     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#36     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#37     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#38     new Future.<anonymous closure> (dart:async/future.dart:174)
#39     _rootRun (dart:async/zone.dart:1122)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#43     _rootRun (dart:async/zone.dart:1126)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#47     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#48     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#11     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#12     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#13     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#14     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#15     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#17     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#18     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#19     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#20     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#21     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#22     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#23     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#28     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#29     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#30     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#35     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#36     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#37     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#38     new Future.<anonymous closure> (dart:async/future.dart:174)
#39     _rootRun (dart:async/zone.dart:1122)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#43     _rootRun (dart:async/zone.dart:1126)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#47     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#48     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on .....lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '......github.com/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 441

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '......github.com/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Gradle build failed: 1
```

#### run --verbose
Once attempts to load an image, log stops and nothing gets printed.
```
[        ] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[        ] An Observatory debugger and profiler on Nexus 5X is available at: http://127.0.0.1:8105/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+1039 ms] I/zygote64(13338): Do partial code cache collection, code=61KB, data=42KB
[   +2 ms] I/zygote64(13338): After code cache collection, code=61KB, data=42KB
[        ] I/zygote64(13338): Increasing code cache capacity to 256KB
[   +6 ms] D/DynamitePackage(13338): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[  +28 ms] I/Ads     (13338): Starting ad request.
[   +3 ms] I/Ads     (13338): Use AdRequest.Builder.addTestDevice("CC6F187D1887E034DD1E0E8A79FD073E") to get test ads on this device.
[  +79 ms] D/DynamitePackage(13338): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[  +38 ms] I/WebViewFactory(13338): Loading com.android.chrome version 65.0.3325.109 (code 332510952)
[  +12 ms] I/Ads     (13338): Starting ad request.
[        ] I/Ads     (13338): Use AdRequest.Builder.addTestDevice("CC6F187D1887E034DD1E0E8A79FD073E") to get test ads on this device.
[ +402 ms] I/cr_LibraryLoader(13338): Time to load native libraries: 7 ms (timestamps 7517-7524)
[  +22 ms] I/chromium(13338): [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
[        ] I/cr_LibraryLoader(13338): Expected native library version number "65.0.3325.109", actual native library version number "65.0.3325.109"
[ +433 ms] I/Ads     (13338): Trying mediation network: null
[        ] I/Ads     (13338): Instantiating mediation adapter: com.google.ads.mediation.admob.AdMobAdapter
[   +6 ms] W/Ads     (13338): Server parameters: {"pubid":"ca-app-pub-3940256099942544\/1033173712"}
[  +22 ms] D/DynamitePackage(13338): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[ +196 ms] I/Ads     (13338): Starting ad request.
[        ] I/Ads     (13338): Use AdRequest.Builder.addTestDevice("CC6F187D1887E034DD1E0E8A79FD073E") to get test ads on this device.
[ +156 ms] W/cr_ChildProcLH(13338): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
[  +31 ms] I/cr_BrowserStartup(13338): Initializing chromium process, singleProcess=false
[        ] I/cr_base (13338): Android Locale: en_US requires .pak files: [en-GB.pak, en-US.pak]
[ +180 ms] W/oozefit.android(13338): type=1400 audit(0.0:206): avc: denied { read } for name="vmstat" dev="proc" ino=4026546034 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
[ +341 ms] W/cr_media(13338): Requires BLUETOOTH permission
[  +86 ms] W/cr_CrashFileManager(13338): /data/user/0/.../cache/WebView/Crash Reports does not exist or is not a directory
[ +193 ms] W/VideoCapabilities(13338): Unrecognized profile 2130706433 for video/avc
[  +25 ms] I/VideoCapabilities(13338): Unsupported profile 4 for video/mp4v-es
[ +456 ms] I/zygote64(13338): Do full code cache collection, code=124KB, data=91KB
[   +1 ms] I/zygote64(13338): After code cache collection, code=119KB, data=64KB
[ +239 ms] I/Ads     (13338): Ad finished loading.
[  +96 ms] I/Ads     (13338): Ad finished loading.
[        ] I/Ads     (13338): Scheduling ad refresh 70000 milliseconds from now.
[ +156 ms] I/Ads     (13338): Ad finished loading.
[ +251 ms] I/zygote64(13338): Do partial code cache collection, code=122KB, data=80KB
[        ] I/zygote64(13338): After code cache collection, code=122KB, data=80KB
[        ] I/zygote64(13338): Increasing code cache capacity to 512KB
[  +50 ms] I/chromium(13338): [INFO:CONSOLE(0)] "Document was loaded from Application Cache with manifest https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.appcache", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
[        ] I/chromium(13338): [INFO:CONSOLE(0)] "Application Cache Checking event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
[ +460 ms] I/chromium(13338): [INFO:CONSOLE(0)] "Application Cache NoUpdate event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
```

## Flutter Doctor

```
[✓] Flutter (Channel unknown, v0.3.0, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.3.0 at /Users/Vladimir/Projects/github.com/flutter
    • Framework revision c73b8a7cf6 (7 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Vladimir/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • Nexus 5X • 00c40db5276fbe05 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

## Investigation

Seems to hang in engine [`engine.cc` on line 416](https://github.com/flutter/engine/blob/master/shell/common/engine.cc#L416)

```c
void Engine::HandleAssetPlatformMessage(
    fxl::RefPtr<blink::PlatformMessage> message) {
  fxl::RefPtr<blink::PlatformMessageResponse> response = message->response();
  if (!response) {
    return;
  }
  const auto& data = message->data();
  std::string asset_name(reinterpret_cast<const char*>(data.data()),
                         data.size());

  std::vector<uint8_t> asset_data;
  // !!! hangs on GetAsBuffer() call !!!
  if (asset_manager_ && asset_manager_->GetAsBuffer(asset_name, &asset_data)) {
     response->Complete(std::move(asset_data));
   } else {
    response->CompleteEmpty();
  }
}
```

**Comment by victorbonnet** [comment] 2018-04-21 10:58
I have same issue. It's happening on some devices only. Surprisingly I tested with 2 different Pixel XL 2, one is working and the other one is having ANR.

It seems that `firebase_admob` is causing this issue but I still don't exactly know why. Are you using `firebase_admob`? If so can you try to comment `FirebaseAdMob.instance.initialize` in your code to see if it's working for you?

**Comment by VolodymyrLykhonis** [comment] 2018-04-22 16:34
@victorbonnet  I think you are right, once I do not call `FirebaseAdMob.instance.initialize` it now works fine, no hanging.

**Comment by jason-simmons** [comment] 2018-04-24 22:51
Duplicate of https://github.com/flutter/flutter/issues/16222

**Closed by jason-simmons** 2018-04-24 22:51 UTC
