### ISSUE TITLE
[Flutter Web] TextField in Flutter Web adds an invisible character after the space character

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#78346] opened 2021-03-16 17:55 UTC
There is a "hidden space" character in the string the TextField produces if space is typed in. 

Consider the next string produced using the Flutter Web input text:
סתם ‏משהו

It looks like it contains 8 chars, but it actually contains 9, which made the string comparison a nightmare, that hidden character doesn't go away with ' ' replacement and as it is saved in the DB it's obviously problematic

Same happens with this one:
Hello ‎World
There is another invisible character after the space.

Simple copy the above strings into [this letter counter](https://wordcounter.net/character-count)

* for some reason the bug doesn't happen all the time wtih English, but often with Hebrew (probably also Arabic)
* The added special character seems to be a different one in each language..

Text Field code:

```
return TextField(textAlign: align,
          controller: controller, textDirection: TextDirection.ltr,
          decoration: InputDecoration(
        contentPadding: EdgeInsets.all(2.0),
        isDense: true,
        hintText: AppLocalizations.of(context).translate(prompt),
        hintStyle: TextStyle(color: Colors.black87.withOpacity(0.5),
              fontSize: style != null ? style.fontSize : 10),
        enabledBorder: UnderlineInputBorder(
          borderSide: BorderSide(width: 0.2, color: Colors.black),
        ),
          focusedBorder: UnderlineInputBorder(
            borderSide: BorderSide(width: 0.2, color: Colors.black),
             ),     
        ),
  onChanged: (value){
    if (onChange != null) {
      onChange(value);
    }
  });
```

Doctor:

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)

@mdebbar

**Comment by HansMuller** [comment] 2021-03-16 21:22
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2021-03-17 06:26
This seems to be a duplicate of https://github.com/flutter/flutter/issues/68989. Closing.

**Closed by LongCatIsLooong** 2021-03-17 06:26 UTC
