### ISSUE TITLE
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by peterkuch** [flutter/flutter#90764] opened 2021-09-26 14:54 UTC
`E/flutter ( 8570): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 8570): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter ( 8570): <asynchronous suspension>
E/flutter ( 8570): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:138)
E/flutter ( 8570): <asynchronous suspension>
E/flutter ( 8570): #2      main (package:get_cambodia_guide/main.dart:28)
E/flutter ( 8570): <asynchronous suspension>
E/flutter ( 8570): 
`
Run android error but ios work fine. please help me  I try
- flutter clean 
- Still can't fix

**Comment by Josiassejod1** [comment] 2021-09-27 05:45
Seems like a duplicate from #56778

**Comment by peterkuch** [comment] 2021-09-27 05:50
<img width="955" alt="Screen Shot 2021-09-27 at 12 47 33 PM" src="https://user-images.githubusercontent.com/14107698/134851706-e24223e7-3757-4ee5-8841-5402643d0436.png">
all everything ok with flutter doctor -v but i still got that problem.

**Comment by Josiassejod1** [comment] 2021-09-27 06:48
@peterkuch  in android studio you have Android Tools checked ?

**Comment by Josiassejod1** [comment] 2021-09-27 06:50
<img width="731" alt="Screen Shot 2021-09-26 at 11 50 50 PM" src="https://user-images.githubusercontent.com/12024422/134858423-2080a2e4-34bd-41c6-963e-aea6dbb527e9.png">

**Comment by peterkuch** [comment] 2021-09-27 07:02
<img width="751" alt="Screen Shot 2021-09-27 at 1 59 49 PM" src="https://user-images.githubusercontent.com/14107698/134859825-373d13c4-e8eb-4468-9849-b9d854a2200f.png">
all done updated but can't resolved it

**Comment by Josiassejod1** [comment] 2021-09-27 08:27
@peterkuch can you rerun flutter doctor?

**Comment by maheshmnj** [comment] 2021-09-27 10:54
Hi @peterkuch, Thanks for filing the issue. Please make sure you restart the application after you add the plugin please refer this https://github.com/flutter/flutter/issues/10912#issuecomment-310499594

**Comment by peterkuch** [comment] 2021-09-29 04:41
> @peterkuch can you rerun flutter doctor?

<img width="955" alt="Screen Shot 2021-09-27 at 12 47 33 PM" src="https://user-images.githubusercontent.com/14107698/135204414-9380a3a8-8a24-4ca4-8da4-df90ccb17cc3.png">

<img width="709" alt="Screen Shot 2021-09-29 at 11 37 08 AM" src="https://user-images.githubusercontent.com/14107698/135204429-8c517ca3-3ab7-4379-bd2a-edfdb73733be.png">

I can't resolve I try more , clean

**Comment by peterkuch** [comment] 2021-09-29 04:46
> @peterkuch can you rerun flutter doctor?

<img width="623" alt="Screen Shot 2021-09-29 at 11 43 38 AM" src="https://user-images.githubusercontent.com/14107698/135204798-ddf50c0b-20e0-4c69-b152-5907a9d1c51b.png">
1. Why default no this GeneratedPluginRegistrant.registerWith(flutterEngine);
2. when I try to put GeneratedPluginRegistrant.registerWith(flutterEngine); inside MainActity class it's wor.
Why?

**Comment by maheshmnj** [comment] 2021-09-29 05:53
>1. Why default no this GeneratedPluginRegistrant.registerWith(flutterEngine); 2. when I try to put GeneratedPluginRegistrant.registerWith(flutterEngine); inside MainActity class it's work 3 Why?

You don't need to manually register the plugin, Flutter run should handle it, You should have a `GeneratedPluginRegistrant.java` file which will register the plugin for you, This file is generated when you do `flutter build` or `flutter run`, Also there should be certain metafiles like `.flutter-plugins` and `.flutter-plugins-dependencies` in the root of your project which should have some meta info  about path_provider,  [This comment ](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594)should explain you why it works.

Closing the issue, as this is working as intended, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-29 05:53 UTC
Labels: in triage
