### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Función incorrecta., errno = 1

### ISSUE THREAD

**Issue by millerjeison** [flutter/flutter#136916] opened 2023-10-19 20:21 UTC
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Función incorrecta.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:337:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[✓] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Versi¢n 10.0.19045.3570], locale es-MX)
    • Flutter version 3.13.8 on channel stable at H:\versiones_flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (28 hours ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\miller\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33130.400
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Users\miller\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\223.8617.56
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at C:\Users\miller\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • SM N970F (mobile) • R58M84ZC3LK • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.3570]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 118.0.5993.88
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 118.0.2088.46

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.5+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
audio_session-0.1.16
just_audio-0.9.35
just_audio_web-0.4.8
package_info_plus-4.2.0
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
rive_common-0.2.3
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
sqflite-2.3.0
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.19
url_launcher_windows-3.0.8
video_player-2.7.2
video_player_android-2.4.10
video_player_avfoundation-2.4.11
video_player_web-2.0.17
wakelock_plus-1.1.3
webview_flutter-4.4.1
webview_flutter_android-3.12.0
webview_flutter_wkwebview-3.9.1

**Comment by huycozy** [comment] 2023-10-20 06:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224. The issue has been fixed recently. Please switch to master channel to check this:

```
flutter channel master
flutter upgrade
```

If you still experience this issue, kindly leave a comment there. Thank you!

**Closed by huycozy** 2023-10-20 06:18 UTC
Labels: in triage
