### ISSUE TITLE
Flutter always redownload the tools when switching between channels.

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#53101] opened 2020-03-23 15:38 UTC
I am in a stable channel.
When I switched to dev quickly the whole tool was reloaded.
when I returned to the stable branch. It keeps reloading the entire tool again.

**Comment by jmagman** [comment] 2020-03-24 00:35
Duplicate of https://github.com/flutter/flutter/issues/44212.

**Closed by jmagman** 2020-03-24 00:35 UTC
Labels: tool
