### ISSUE TITLE
Icons.sports_martial_arts_rounded shows Armenian flag.

### ISSUE THREAD

**Issue by eliaxelang007** [flutter/flutter#98093] opened 2022-02-09 05:41 UTC
## Steps to Reproduce

* Create a new Flutter project in [dartpad.dev](https://dartpad.dev/) with this code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: IconButton(
          iconSize: 200,
          icon: const Icon(Icons.sports_martial_arts_rounded),
          onPressed: () {}
        )
      )
    )
  ));
}

```

**Expected results:** 

![Expected](https://user-images.githubusercontent.com/54026120/153128906-905739ad-f50f-42ae-899a-50ba441610cb.png)

**Actual results:** 

![Actual](https://user-images.githubusercontent.com/54026120/153128930-47372f54-4ea8-44f2-a500-65f9f456375b.png)

**Flutter Doctor**

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on Debian GNU/Linux 11 (bullseye) 5.10.0-11-amd64, locale en_PH.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.64.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Additional Info**

I ran into this while I was trying to make an IconButton with the martial arts
icon in my own web app. When I switched to the master channel, the problem
disappeared.

**Comment by MeYo0o** [comment] 2022-02-09 08:15
i guess that's related when you switch from one channel to the other , if i were u , i would re-download the Flutter SDK again and try switching back and forth between channels to see if that problem still exists.

**Comment by eliaxelang007** [comment] 2022-02-09 09:11
It hapens on [dartpad.dev](https://dartpad.dev) too, so it's not just a problem with my system.

**Comment by eliaxelang007** [comment] 2022-02-09 09:15
I switched back from the master channel back to the stable channel, did ```flutter upgrade```, tested it but the problem still persists.

**Comment by danagbemava-nc** [comment] 2022-02-09 09:34
Hi @eliaxelang007, this is a duplicate of https://github.com/flutter/flutter/issues/97767. 

> When I switched to the master channel, the problem disappeared.

This is because the issue has been fixed on `master`. See https://github.com/flutter/flutter/issues/97767#issuecomment-1029885334 for more information. 

Since there's a cherry-pick request for #97767, I'm going to close this issue. Kindly follow up there for information.

**Closed by danagbemava-nc** 2022-02-09 09:34 UTC
Labels: in triage
