### ISSUE TITLE
[image_picker][web] cancel cause picker to never return

### ISSUE THREAD

**Issue by aoatmon** [flutter/flutter#92176] opened 2021-10-20 14:31 UTC
## Steps to Reproduce

- clone this [repository](https://github.com/aoatmon/picker_bug) or use the code sample below
- run `flutter run -d chrome`
- tap the fab
- when the picker window show up choose `cancel`

**Expected results:** 

- should return `null`

**Actual results:**

- never returns

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const PickerFilesProvider(child: MaterialApp(home: MyHomePage())));
}

Future<Iterable<XFile>> pickFiles() async {
  try {
    final maybeFiles = await ImagePicker().pickMultiImage();
    return [if (maybeFiles != null) ...maybeFiles];
  } on Exception catch (e, s) {
    debugPrint('$e, $s');
    return [];
  } on Error catch (e) {
    debugPrint('$e, ${e.stackTrace}');
    return [];
  }
}

extension XfilesNamesX on Iterable<XFile> {
  Iterable<String> get names sync* {
    for (final file in this) {
      yield file.name;
    }
  }
}

class PickerFilesProvider extends StatefulWidget {
  final Widget child;
  const PickerFilesProvider({
    required this.child,
  }) : super(key: const ValueKey('PickerFilesProvider'));

  @override
  State<PickerFilesProvider> createState() => _PickerFilesProviderState();
}

class _PickerFilesProviderState extends State<PickerFilesProvider> {
  late final ValueNotifier<Iterable<String>> _notifier;

  @override
  void initState() {
    super.initState();
    _notifier = ValueNotifier(<String>[]);
  }

  @override
  void dispose() {
    _notifier.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return _PickedFiles(
      child: widget.child,
      notifier: _notifier,
    );
  }
}

class _PickedFiles extends InheritedWidget {
  final ValueNotifier<Iterable<String>> notifier;
  const _PickedFiles({
    required this.notifier,
    required Widget child,
  }) : super(key: const ValueKey('PickedFiles'), child: child);

  static _PickedFiles of(BuildContext context) {
    final _PickedFiles? result =
        context.dependOnInheritedWidgetOfExactType<_PickedFiles>();
    assert(result != null, 'No PickedFiles found in context');
    return result!;
  }

  @override
  // ignore: avoid_renaming_method_parameters
  bool updateShouldNotify(_) => false;
}

extension PickedFilesX on BuildContext {
  ValueNotifier<Iterable<String>> get pickerfiles =>
      _PickedFiles.of(this).notifier;
}

class PickerButton extends StatefulWidget {
  const PickerButton({
    final key = const ValueKey('PickerButton'),
  }) : super(key: key);

  @override
  State<PickerButton> createState() => _PickerWidgetState();
}

class _PickerWidgetState extends State<PickerButton> {
  late final ValueNotifier<bool> _busy;

  @override
  void initState() {
    super.initState();
    _busy = ValueNotifier(false);
  }

  @override
  void dispose() {
    _busy.dispose();
    super.dispose();
  }

  void _pickFiles() async {
    _busy.value = true;
    context.pickerfiles.value = (await pickFiles()).names;
    _busy.value = false;
  }

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      child: ValueListenableBuilder<bool>(
          valueListenable: _busy,
          builder: (context, busy, _) => busy
              ? const CircularProgressIndicator(color: Colors.black)
              : const Icon(Icons.upload)),
      onPressed: _pickFiles,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    final key = const ValueKey('MyHomePage'),
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: PickedFilesListView(),
      floatingActionButton: PickerButton(),
    );
  }
}

class PickedFilesListView extends StatelessWidget {
  const PickedFilesListView({
    final key = const ValueKey('PickedFilesListView'),
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<Iterable<String>>(
      valueListenable: context.pickerfiles,
      builder: (context, names, _) => ListView(children: [
        for (final name in names) Center(child: Text(name)),
      ]),
    );
  }
}

```

</details>

<details>
  <summary>pubspec</summary>

```yaml
environment:
  sdk: '>=2.14.3 <3.0.0'
  flutter: ^2.5.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
```

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

</details>

**Comment by jamov** [comment] 2022-03-23 09:44
I guess no progress? Just now faced this issue myself.

**Comment by pauline-jubiliz** [comment] 2022-04-04 06:39
I also have the same problem that occurs only on the web. Were you able to find a workaround?

**Comment by ditman** [comment] 2022-05-07 01:19
The "cancel" event seems to be coming to web standards. The moment it's available in all browsers, we can hook it up. Don't despair:

https://github.com/whatwg/html/pull/6735

**Comment by ditman** [comment] 2022-05-07 02:00
Also interesting, there's a new [showPicker API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker) coming to trigger the file selector, rather than faking a "click" on the button!

**Comment by SnowZero** [comment] 2022-07-12 02:31
This problem may be related to [#90779](https://github.com/flutter/flutter/issues/90779).
Too long waiting time needing loading indicators instead,
but the cancellation event cannot be obtained on the Web

**Comment by ditman** [comment] 2022-07-12 23:35
I'm almost sure that #90779 is caused by a sub-optimal way of initializing XFiles on the web, where there isn't a constructor that can directly accept the File/Blob from the browser (instead, it needs to copy bytes, and the larger the image, the SLOWER that process is).

We have an issue tracking that problem: https://github.com/flutter/flutter/issues/91869

**Comment by leoshusar** [comment] 2022-09-19 16:08
There sure has to be a way, because `file_picker` library returns null after cancel.
Looking at the [code](https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/_internal/file_picker_web.dart#L125), I think it is using window `focus` event.
Maybe it would be worth a try?

**Comment by lukas-h** [comment] 2022-09-29 07:24
I keep experiencing this problem since a few months with `file_selector` and `image_picker` on the web

**Comment by ditman** [comment] 2022-10-01 01:52
@lukas-h makes sense, both plugins use the same technique in the browser (an `input type=file`).

**Comment by ditman** [comment] 2022-10-19 01:10
Unassigning myself, since I won't be able to work on this in the near future. Apologies!

**Comment by Dakrain** [comment] 2022-12-20 09:42
Any update guys? I facing the same issues too.

**Comment by ditman** [comment] 2022-12-20 19:36
The Chromium `cancel` event is being [worked on here](https://chromium-review.googlesource.com/c/chromium/src/+/4048886), it seems that all other browsers have already landed implementations of the `cancel` event for the file inputs.

**Comment by dam-ease** [comment] 2023-05-16 09:07
I am able to reproduce this issue using the latest version of the `image_picker` package and on the latest `stable` and `master` channels.
[Code Sample](https://github.com/flutter/flutter/issues/92176#issue-1031484097)


<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (10 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.4 20E247
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3 22E252 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.0 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (7 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e •
      ios            • iOS 16.4 20E247
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by iapicca** [comment] 2023-05-16 10:09
could the same [fix](https://github.com/flutter/packages/pull/3683) of https://github.com/flutter/flutter/issues/121328 be applied here?

**Comment by ditman** [comment] 2023-05-26 02:46
@iapicca yes, the implementations are not shared now, but the same fix (or extremely similar) could, and should, be applied to both plugins, as Stuart mentioned in the issue you linked.

**Comment by ditman** [comment] 2023-07-13 02:36
A fix for this is coming:

* https://github.com/flutter/packages/pull/4453

(The same fix for `file_selector` has already landed here: https://github.com/flutter/packages/pull/3683)

**Closed** 2023-08-04 15:08 UTC
Labels: platform-web, p: image_picker, package, has reproducible steps, P2, found in release: 3.10, found in release: 3.11, team-web, triaged-web, multiteam-retriage-candidate
