### ISSUE TITLE
Flutter stable assertion error

### ISSUE THREAD

**Issue by rakeshcoolrex** [flutter/flutter#76059] opened 2021-02-15 11:34 UTC
here is the error 

Installing build\app\outputs\flutter-apk\app.apk...                10.0s
Waiting for vivo 1902 to report its views...                        22ms
Syncing files to device vivo 1902...                               667ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on vivo 1902 is available at: http://127.0.0.1:62598/1XK5ulK4znw=/
W/StorageUtil(19967): no auth token for request
I/.adventuresqua(19967): The ClassLoaderContext is a special shared library.
W/FirebaseStorage(19967): type=1400 audit(0.0:78044): avc: denied { read } for name="u:object_r:mtk_em_tel_log_prop:s0" dev="tmpfs" ino=11093 scontext=u:r:untrusted_app:s0:c106,c256,c512,c768 tcontext=u:object_r:mtk_em_tel_log_prop:s0 tclass=file permissive=0
E/libc    (19967): Access denied finding property "persist.vendor.log.tel_dbg"
W/NetworkRequest(19967): no auth token for request
W/System  (19967): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(19967): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
D/Linux   (19967): [Posix_connect Debug]Process com.example.adventuresquad :443
D/OpenSSLLib(19967): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
D/OpenSSLLib(19967): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
I/System.out(19967): [OkHttp] sendRequest>>
I/System.out(19967): [OkHttp] sendRequest<<
I/flutter (19967): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19967): The following assertion was thrown building HomeScreen(dirty, state: _HomeScreenState#8fc85):
I/flutter (19967): 'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url !=
I/flutter (19967): null': is not true.
I/flutter (19967): 
I/flutter (19967): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19967): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19967): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19967):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (19967):
I/flutter (19967): The relevant error-causing widget was:
I/flutter (19967):   HomeScreen file:///C:/Users/tony/Desktop/projects/adventuresquad/lib/main.dart:21:13
I/flutter (19967):
I/flutter (19967): When the exception was thrown, this was the stack:
I/flutter (19967): #2      new NetworkImage (package:flutter/src/painting/_network_image_io.dart:25:14)
I/flutter (19967): #3      new Image.network (package:flutter/src/widgets/image.dart:409:68)
I/flutter (19967): #4      _HomeScreenState.build (package:adventuresquad/screens/HomeScreen.dart:45:32)
I/flutter (19967): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (19967): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (19967): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (19967): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (19967): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
I/flutter (19967): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
I/flutter (19967): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter (19967): ...     Normal element mounting (132 frames)
I/flutter (19967): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (19967): #144    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (19967): ...     Normal element mounting (258 frames)
I/flutter (19967): #402    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (19967): #403    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
I/flutter (19967): #404    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
I/flutter (19967): #405    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
I/flutter (19967): #406    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
I/flutter (19967): #407    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
I/flutter (19967): #408    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
I/flutter (19967): #409    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
I/flutter (19967): #410    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
I/flutter (19967): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)       
I/flutter (19967):
I/flutter (19967): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by pedromassangocode** [comment] 2021-02-15 11:51
> I/flutter (19967): The following assertion was thrown building HomeScreen(dirty, state: _HomeScreenState#8fc85):
> I/flutter (19967): 'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url !=
> I/flutter (19967): null': is not true.

Looks like you passed a null image URL in a Image widget. do you have a reproducible code sample?

**Comment by pedromassangocode** [comment] 2021-03-12 14:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:04 UTC
Labels: in triage, waiting for customer response
