### ISSUE TITLE
Cupertino Pulldown Implementation

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#120960] opened 2023-02-17 08:22 UTC
I'm curious whether a Cupertino Pull Down button can be implemented in the core library. It looks like this feature has been suggested before but has not had much action: [60298](https://github.com/flutter/flutter/issues/60298)

Notably, [@notDmDrl](https://github.com/notDmDrl) has implemented a feature-rich pull down menu that closely follows the [iOS spec](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/pull-down-buttons/) with comprehensive examples: [pull_down_button](https://github.com/notDmDrl/pull_down_button)

I've also been working to extend his implementation to support more features, but am unsure whether a Cupertino Pull Down menu is planned by the Flutter team (it does not appear so based upon the Cupertino theme tracker).

## Use case
From the iOS spec, a pull down menu "present commands or items that are directly related to the button’s action. The menu lets you help people clarify the button’s target or customize its behavior without requiring additional buttons in your interface."

## Proposal
Add pull down menu to the Cupertino widget library.

Example (WIP): 

https://user-images.githubusercontent.com/59215665/219591318-f5465875-c7a6-4492-a376-322ef33eb2b0.mov

**Comment by exaby73** [comment] 2023-02-17 11:21
Hello @davidhicks980. Since there is already an issue / proposal open for this, I'll close this issue as a duplicate of that. This can be a great opportunity to contribute to Flutter :) If you can, I'd encourage that you make a PR and add this widget that will eventually make it to a stable release near you.

**Closed by exaby73** 2023-02-17 11:21 UTC
Labels: in triage
