### ISSUE TITLE
Misplaced shadows when using nested SingleChildScrollView

### ISSUE THREAD

**Issue by Moomba42** [flutter/flutter#36463] opened 2019-07-18 16:02 UTC
# Expected Behavior

The shadows stay fixed under the Card widgets when placed in SingleChildScrollView, that is itself placed in a SingleChildScrollView (2d scrolling).

# Current Behavior

While scrolling from left to right, the shadows under the Card widgets get offset to the left, moving away from the widget itself. This gets really extreme when there is a lot of horizontal scrolling.

Also, when i switch the scroll directions (in the snippet that i provided below) so that the first SingleChildScrollView has a scroll direction of vertical, and the second one has horizontal, then horizontal scrolling doesn't affect the shadows anymore, but vertical scrolling does.

I tested it on Windows and Android.

The issue dissapears when there is only one SingleChildScrollView (1d)

## Steps to Reproduce

Run the following snippet in flutter environment, then scroll about, and watch the shadows slide.

```
Scaffold(
    appBar: AppBar(
        title: Text('Title'),
    ),
	body: SingleChildScrollView(
		scrollDirection: Axis.horizontal,
		child: SingleChildScrollView(
			scrollDirection: Axis.vertical,
			child: SizedBox(
				width: 2000,
				height: 1000,
				child: Stack(
					children: List.generate(200, (index) => Positioned(
						left: ((index/10).floor())*100.0,
						top: (((index/10).floor()%2)*100)+(index%10)*200.0,
						width: 100,
						height: 100,
						child: Card(elevation: 4,),
					)),
				),
			),
		),
	),
)
```

## Logs

No logs. No analysis errors.

## Version info (flutter doctor -v)
```
[√] Flutter (Channel master, v1.8.2-pre.81, on Microsoft Windows [Version 10.0.17134.885], locale pl-PL)
    • Flutter version 1.8.2-pre.81 at C:\src\flutter
    • Framework revision 578204df19 (14 hours ago), 2019-07-17 18:24:24 -0700
    • Engine revision f348270047
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 2b3336b51e)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\...\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830
    
[√] Connected device (2 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.17134.885]
    • Chrome  • chrome  • web-javascript • Google Chrome 75.0.3770.100
```

**Comment by BondarenkoStas** [comment] 2019-09-25 15:23
@Moomba42 Is it the same using current flutter stable or master?

**Comment by VladyslavBondarenko** [comment] 2020-04-28 19:16
@Moomba42 
I can't reproduce it with `dev v1.18.0-8.0.pre`, 
Closing, seems to be fixed,
comment please if it's not so and I'll reopen the issue

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision e0c63cd35e (5 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                               • web-javascript • Flutter Tools
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

</details>

**Closed by VladyslavBondarenko** 2020-04-28 19:16 UTC
Labels: f: scrolling, framework
