### ISSUE TITLE
page not loading getting error in console[web]

### ISSUE THREAD

**Issue by habeebul** [flutter/flutter#41045] opened 2019-09-22 05:01 UTC
```
browser_location.dart:94 Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
    at HashLocationStrategy.get path [as path] (browser_location.dart:94)
    at _engine.BrowserHistory.new.get currentPath [as currentPath] (history.dart:56)
    at _engine.BrowserHistory.new.[_setupStrategy] (history.dart:164)
    at _engine.BrowserHistory.new.set locationStrategy [as locationStrategy] (history.dart:51)
    at _engine.EngineWindow.new.set locationStrategy [as locationStrategy] (window.dart:81)
    at webOnlyInitializePlatform (initialization.dart:12)
    at webOnlyInitializePlatform.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at Object.webOnlyInitializePlatform (initialization.dart:8)
    at main$ (main_web_entrypoint.dart:7)
    at main$.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at main$ (main_web_entrypoint.dart:5)
    at Function.call$0 (client.js:27433)
    at client.js:26055
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3110)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11704)
    at Object._asyncStartSync (client.js:3075)
    at main__closure3.$call$body$main__closure (client.js:26063)
    at main__closure3.call$1 (client.js:25993)
    at StaticClosure._rootRunUnary [as call$2$5] (client.js:3393)
    at _CustomZone.runUnary$2$2 (client.js:13083)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:13011)
    at _ControllerSubscription._sendData$1 (client.js:12564)
    at _DelayedData.perform$1 (client.js:12771)
    at _StreamImplEvents.handleNext$1 (client.js:12845)
    at _PendingEvents_schedule_closure.call$0 (client.js:12817)
    at Object._microtaskLoop (client.js:3253)
    at StaticClosure._startMicrotaskLoop (client.js:3259)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:11580)
    at invokeClosure (client.js:1206)
    at MutationObserver.<anonymous> (client.js:1225)
get path @ browser_location.dart:94
get currentPath @ history.dart:56
[_setupStrategy] @ history.dart:164
set locationStrategy @ history.dart:51
set locationStrategy @ window.dart:81
webOnlyInitializePlatform @ initialization.dart:12
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
webOnlyInitializePlatform @ initialization.dart:8
main$ @ main_web_entrypoint.dart:7
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
main$ @ main_web_entrypoint.dart:5
Function.call$0 @ client.js:27433
(anonymous) @ client.js:26055
(anonymous) @ client.js:3110
call$2 @ client.js:11704
_asyncStartSync @ client.js:3075
$call$body$main__closure @ client.js:26063
call$1 @ client.js:25993
_rootRunUnary @ client.js:3393
runUnary$2$2 @ client.js:13083
runUnaryGuarded$1$2 @ client.js:13011
_sendData$1 @ client.js:12564
perform$1 @ client.js:12771
handleNext$1 @ client.js:12845
call$0 @ client.js:12817
_microtaskLoop @ client.js:3253
_startMicrotaskLoop @ client.js:3259
call$1 @ client.js:11580
invokeClosure @ client.js:1206
(anonymous) @ client.js:1225
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:164
_scheduleImmediate @ async_patch.dart:136
_scheduleAsyncCallback @ schedule_microtask.dart:71
_rootScheduleMicrotask @ zone.dart:1185
scheduleMicrotask @ zone.dart:1399
[_asyncCompleteError] @ future_impl.dart:577
_asyncCompleteWithErrorCallback @ future.dart:927
runBody @ async_patch.dart:117
_async @ async_patch.dart:123
webOnlyInitializePlatform @ initialization.dart:8
main$ @ main_web_entrypoint.dart:7
runBody @ async_patch.dart:84
_async @ async_patch.dart:123
main$ @ main_web_entrypoint.dart:5
Function.call$0 @ client.js:27433
(anonymous) @ client.js:26055
(anonymous) @ client.js:3110
call$2 @ client.js:11704
_asyncStartSync @ client.js:3075
$call$body$main__closure @ client.js:26063
call$1 @ client.js:25993
_rootRunUnary @ client.js:3393
runUnary$2$2 @ client.js:13083
runUnaryGuarded$1$2 @ client.js:13011
_sendData$1 @ client.js:12564
perform$1 @ client.js:12771
handleNext$1 @ client.js:12845
call$0 @ client.js:12817
_microtaskLoop @ client.js:3253
_startMicrotaskLoop @ client.js:3259
call$1 @ client.js:11580
invokeClosure @ client.js:1206
(anonymous) @ client.js:1225
childList (async)
call$1 @ client.js:11590
_scheduleAsyncCallback @ client.js:3272
_rootScheduleMicrotask @ client.js:3437
scheduleMicrotask @ client.js:3300
schedule$1 @ client.js:12806
_addPending$1 @ client.js:12555
_sendData$1 @ client.js:12365
add$1 @ client.js:12260
_onIncomingMessage$1 @ client.js:25615
eval @ VM390:3
invokeClosure @ client.js:1206
(anonymous) @ client.js:1225
Show 35 more frames
```

**Comment by BondarenkoStas** [comment] 2019-09-22 12:56
Seems to be a duplicate of #40876. @habeebul please provide your ```flutter doctor -v``` output.

**Comment by habeebul** [comment] 2019-09-22 13:34
@BondarenkoStas added flutter doctor -v output.

Microsoft Windows [Version 10.0.18362.356]
(c) 2019 Microsoft Corporation. All rights reserved.

E:\flutter_app\flutter_app>flutter doctor -v
[√] Flutter (Channel master, v1.10.6-pre.29, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)
    • Flutter version 1.10.6-pre.29 at E:\flutter
    • Framework revision 919cc97f6a (2 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\flutter
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\flutter
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

**Comment by jonahwilliams** [comment] 2019-09-22 13:42
duplicate of https://github.com/flutter/flutter/issues/40876

**Closed by jonahwilliams** 2019-09-22 13:42 UTC
