### ISSUE TITLE
camera-0.5.7+4 CameraPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#54747] opened 2020-04-14 13:06 UTC
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.7+4\android\src\main\java\io\flutter\plugins\camera\CameraPlugin.java uses or overrides a deprecated API.

**Comment by VladyslavBondarenko** [comment] 2020-04-14 13:37
Hi @kw2019ltd 
This isn't an error and just "deliberate and temporary" warning
Closing as duplicate of https://github.com/flutter/flutter/issues/47153

**Closed by VladyslavBondarenko** 2020-04-14 13:37 UTC
Labels: p: camera, platform-android, plugin
