### ISSUE TITLE
com.intellij.util.IncorrectOperationException: Sorry but parent: dev:b4d0901d has already been disposed

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#64947] opened 2020-08-31 11:15 UTC
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `4.0.1` • Flutter plugin `io.flutter 48.1.2` • Dart plugin `193.7547`

Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: dev:b4d0901d has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$595/1142060956@15771194 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:59)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:78)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:159)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:145)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:415)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:185)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:148)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:336)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:276)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:524)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:380)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hamdikahloun** [comment] 2020-08-31 11:42
Hi @bhanuka96 

Maybe you must add this issue here : [https://github.com/flutter/flutter-intellij](https://github.com/flutter/flutter-intellij)

**Comment by pedromassangocode** [comment] 2020-08-31 11:44
Hi @bhanuka96 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-31 11:44 UTC
