### ISSUE TITLE
Flutter 3.13.0 App crash with NullPointerException Attempt to read from field android.view.ViewRootImpl.mWindowAttributes

### ISSUE THREAD

**Issue by winterdl** [flutter/flutter#132891] opened 2023-08-19 12:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run example app with flutter 3.13.0
2. Select test 2
3. Tap any text on webpage 
4. Press back and app will crash 

Notes: 
- App works well with 3.10.6 but crash with 3.13.0
- App will crash only (3.13.0) when screen have more than 1 InAppWebView and useHybridComposition = false 
- Run on real device, Android 10

[webviewtest.zip](https://github.com/flutter/flutter/files/12385840/webviewtest.zip)

### Expected results

not crash

### Actual results

E/AndroidRuntime(19817): FATAL EXCEPTION: main
E/AndroidRuntime(19817): Process: com.example.webviewtest, PID: 19817
E/AndroidRuntime(19817): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(19817):        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1627)
E/AndroidRuntime(19817):        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1871)
E/AndroidRuntime(19817):        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4881)
E/AndroidRuntime(19817):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19817):        at android.os.Looper.loop(Looper.java:225)
E/AndroidRuntime(19817):        at android.app.ActivityThread.main(ActivityThread.java:7563)
E/AndroidRuntime(19817):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19817):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(19817):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/AndroidRuntime(19817): FATAL EXCEPTION: main
E/AndroidRuntime(19817): Process: com.example.webviewtest, PID: 19817
E/AndroidRuntime(19817): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(19817):        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1627)
E/AndroidRuntime(19817):        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1871)
E/AndroidRuntime(19817):        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4881)
E/AndroidRuntime(19817):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19817):        at android.os.Looper.loop(Looper.java:225)
E/AndroidRuntime(19817):        at android.app.ActivityThread.main(ActivityThread.java:7563)
E/AndroidRuntime(19817):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19817):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(19817):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-x64, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment] 2023-08-21 08:13
Hi @winterdl 
From what I can see, the issue is related to a 3rd party plugin ([flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)) rather than to Flutter or 1st party packages/plugins. It should be reported at that repository for better support there (I see you opened an issue there, so please follow up on it for updates)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, providing the entire of `flutter run -v`,  your `pubspec.yaml`, a minimal sample code that does not use 3rd party plugins and I will reopen it. Thank you!

**Closed by huycozy** 2023-08-21 08:13 UTC
Labels: in triage
