### ISSUE TITLE
Rendering text is much slower using Impeller on iOS with iPhone 7 Plus, where Skia is ~2ms while Impeller is ~20ms

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#127760] opened 2023-05-28 00:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the demo app. I see this problem when executing regression tests using my internal continuous benchmark infra.

I am not sure whether this is a bug or expected feature, but anyway I post it here since this rendering scenario (unlike my actual complex screens) looks simple for debugging.

### Expected results

When skia:

![image](https://github.com/flutter/flutter/assets/5236035/8e7b83ba-78fe-4704-a30c-b748dd3a913f)

Zoom in

![image](https://github.com/flutter/flutter/assets/5236035/88f2ef61-1d49-4553-9453-61909ce0c84e)

### Actual results

When impeller:

![image](https://github.com/flutter/flutter/assets/5236035/72c573d3-4995-4566-91dc-b73f695462d0)

Zoom in

![image](https://github.com/flutter/flutter/assets/5236035/f7cf14e5-d5f8-4f5d-a710-f528b885b4f7)

### Code sample

<details><summary>Code sample</summary>

```dart
class BenchmarkComplexRenderWidget extends StatefulWidget {
  const BenchmarkComplexRenderWidget({super.key});

  @override
  State<BenchmarkComplexRenderWidget> createState() => _BenchmarkComplexRenderWidgetState();
}

class _BenchmarkComplexRenderWidgetState extends State<BenchmarkComplexRenderWidget> {
  late final DateTime startTime;
  var frameIndex = 0;

  @override
  void initState() {
    super.initState();

    startTime = DateTime.now();

    unawaited(() async {
      while (true) {
        await WidgetsBinding.instance.endOfFrame;
        if (!mounted) break;
        setState(() => frameIndex++);
      }
    }());
  }

  @override
  Widget build(BuildContext context) {
    final duration = DateTime.now().difference(startTime);
    final fps = frameIndex / (duration.inMilliseconds / 1000 + 1e-5);

    // ignore: ban-name
    return Scaffold(
      // ignore: ban-name
      appBar: AppBar(
        title: const Text('ComplexRender'),
      ),
      body: ListView(
        children: [
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(child: Center(child: Text('FPS=${fps.toStringAsFixed(1)}'))),
              Expanded(child: Center(child: Text('frame=$frameIndex'))),
              Expanded(child: Center(child: Text('time=${duration.inMilliseconds}ms'))),
            ],
          ),
          const SizedBox(height: 16),
          _buildComplexRender(),
        ],
      ),
    );
  }

  Widget _buildComplexRender() {
    final alpha = (frameIndex % 60) / 60;

    return Opacity(
      opacity: alpha,
      child: ShaderMask(
        // ignore: prefer-extracting-callbacks
        shaderCallback: (bounds) => RadialGradient(
          center: Alignment.topLeft,
          radius: 0.5 + alpha * 0.5,
          colors: <Color>[Colors.yellow, Colors.deepOrange.shade900],
          tileMode: TileMode.mirror,
        ).createShader(bounds),
        child: Text(
          'This is complex render text' * 1000,
          style: TextStyle(
            fontSize: 6,
            height: 1,
            color: Theme.of(context).colorScheme.background,
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment] 2023-05-30 15:38
I don't know what version you're running on, so I can't reproduce exact results. Please include a commit hash when attaching profiles. At ToT, I get substantially better performance with Impeller versus Skia. That said, from https://github.com/flutter/engine/pull/42417 we can further improve things, then we'd need to find a way to make vertex stage faster.

![image](https://github.com/flutter/flutter/assets/8975114/1ed67775-ca0d-4b0d-9711-8a27ea828857)

**Comment by fzyzcjy** [comment] 2023-05-30 23:07
> I don't know what version you're running on, so I can't reproduce exact results. Please include a commit hash when attaching profiles.

Sorry, it is Flutter 3.10.1 stable. (Given Impeller is stable there, originally I thought it should be already fast enough)

> At ToT, I get substantially better performance with Impeller versus Skia.

That's good news! Then looking forward to using Impeller in the next stable release in production

**Comment by chinmaygarde** [comment] 2023-05-31 00:50
Closing this as fixed.

**Closed by chinmaygarde** 2023-05-31 00:50 UTC
Labels: engine, impeller
