### ISSUE TITLE
Uncaught TypeError for Web app with Rive dependency in debug mode

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#64011] opened 2020-08-18 00:15 UTC
## Steps to Reproduce

0. Use channel `beta` or later with `flutter config --enable-web` (tested on `1.20.2 • channel beta`)
1. Run `flutter create bug`.
2. Include a `rive: 0.0.7` dependency and `import 'package:rive/rive.dart'` in `main.dart`.
3. **Include `print(Rive(artboard: null));` in `main` for the tree shaker.**
4. Run `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`.
5. Open the JavaScript console after Chrome has launched.
6. See the following error and a blank page:

<details>
  <summary>Uncaught TypeError: Class extends value undefined is not a constructor or null at load__packages__rive__src__rive_core__shapes__triangle_dart (component_base.dart:38)</summary>

```
Uncaught TypeError: Class extends value undefined is not a constructor or null at load__packages__rive__src__rive_core__shapes__triangle_dart (component_base.dart:38)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

</details>

## Fix

Add a `--release` flag as well.

### What does not work

Adding just the `--release` flag without the Skia flag.

### Error table

The error from above appears/does not appear for the following commands:

```
ERROR: flutter run -d chrome
ERROR: flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true
ERROR: flutter run -d chrome --release
 FINE: flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release
```

## Elaboration

[Rive **requires** CanvasKit](https://github.com/rive-app/rive-flutter/issues/2#issue-657420230), which is why the flag is required. The app runs *fine* in *release mode*. However, not having access to debug mode makes the development workflow not feasible.

Running the same app in **release mode only** *without* the Skia flag will **result in the same error**.  
This is why [I concluded that Skia seems to not be working fully in debug mode on web](https://github.com/flutter/flutter/issues/63370#issuecomment-674561457), even with the flag.

## Why this is a Flutter issue

As this issue *seems* package-specific, you might argue that this does not belong here. However, the Rive package authors only state that the package [does not work without **Skia**](https://github.com/rive-app/rive-flutter/issues/2#issue-657420230).  
This in no way implies that debug mode would break this.

There seems to be something wrong with the way debug mode is compiled on web with Skia compared to release mode.

cc @yjbanov

**Comment by markusaksli-nc** [comment] 2020-08-18 06:53
In theory, rive is a third-party package so unless this is caused by the upstream issue mentioned in https://github.com/flutter/flutter/issues/63898 this should indeed be closed in favor of https://github.com/rive-app/rive-flutter/issues/2. I'm unconvinced that this is caused by any upstream issue since it would imply that [flutter_svg](https://pub.dev/packages/flutter_svg) wouldn't work with `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true` as well. But it does.

<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      theme: ThemeData(colorScheme: ColorScheme.dark()),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Container(
          child: Center(
            child: SvgPicture.asset("asset.svg"),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.135 at C:\Development\flutter_master
    • Framework revision 654022aecb (6 hours ago), 2020-08-18 03:01:02 +0300
    • Engine revision b9243713a0
    • Dart version 2.10.0 (build 2.10.0-36.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>
<details>
 <summary>flutter run -d chrome</summary>

![Annotation 2020-08-18 094551](https://user-images.githubusercontent.com/68219924/90479647-acfe0180-e137-11ea-9739-6413d694f429.png)
</details>
<details>
 <summary>flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true</summary>

![Annotation 2020-08-18 094404](https://user-images.githubusercontent.com/68219924/90479736-cf901a80-e137-11ea-999c-fc53e62e6204.png)
</details>

Due to this, I feel comfortable closing. You can mention this information in https://github.com/rive-app/rive-flutter/issues/2 to clarify there as well. I don't really know of any other way of testing at runtime if the Skia rendering option is recognized though. Since you already cc'd yjbanov can reopen if I'm wrong.

**Comment by creativecreatorormaybenot** [comment] 2020-08-18 07:06
@markusaksli-nc Why does it have to be related to `flutter_svg`?

This stack trace does not hint at that. As I mentioned, I doubt this is an issue with Rive. This looks like an issue with how Flutter compiles JavaScript.

**Comment by markusaksli-nc** [comment] 2020-08-18 07:29
`flutter_svg` also does not work without Skia (see https://github.com/dnfield/flutter_svg/issues/173#issuecomment-602771285). If the debug compile option was broken it would mean both `flutter_svg` and `rive` wouldn't work, but since `flutter_svg` does it seems like it would rule out this being an upstream issue.

**Comment by creativecreatorormaybenot** [comment] 2020-08-18 07:31
@markusaksli-nc We can change the title to not necessarily include Skia. I suppose this might just be related to the compiler and not related to Skia at all.

**Comment by iapicca** [comment] 2020-08-18 13:57
running the code below 
(following the [steps](https://github.com/flutter/flutter/issues/64011#issue-680599712) provided by @creativecreatorormaybenot)
with the latest master

<details>
  <summary>code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

/*  `pubspec.yaml`
dependencies:
  flutter:
    sdk: flutter
  rive: ^0.0.7
*/

void main() {
  print(Rive(artboard: null));
  runApp(const MaterialApp(
      home: Material(child: Center(child: FlutterLogo(size: 80)))));
}
```

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
    ✗ The blkid development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install libblkid-dev)
[!] Android Studio (not installed)
[!] VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)

! Doctor found issues in 3 categories.

```
</details>

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`

<details>
  <summary> logs</summary>

# chrome
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at load__packages__rive__src__rive_core__shapes__triangle_dart (component_base.dart:38)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

 # terminal

```bash
 francesco@francesco-yoga720  ~/projects/generative_art  flutter_master run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v                                                      ✔  2472  16:13:34 
[ +108 ms] executing: [/home/francesco/development/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a51dc3d913344f3073da12f4aae654c3299dec6c
[        ] executing: [/home/francesco/development/flutter_master/] git tag --points-at HEAD
[  +11 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/home/francesco/development/flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-139-ga51dc3d91
[  +10 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/francesco/development/flutter_master/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +38 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: /usr/lib/Android/platform-tools/adb devices -l
[  +16 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] executing: /usr/lib/Android/platform-tools/adb devices -l
[ +143 ms] Generating /home/francesco/projects/generative_art/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +67 ms] List of devices attached
[   +2 ms] List of devices attached
[  +56 ms] Launching lib/main.dart on Chrome in debug mode...
[  +51 ms] Updating assets
[  +97 ms] Syncing files to device Chrome...
[  +53 ms] Generating /home/francesco/projects/generative_art/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +41 ms] <- reset
[   +6 ms] /home/francesco/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/development/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/development/flutter_master/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true -DFLUTTER_WEB_USE_SKIA=true --output-dill
/tmp/flutter_tools.AWUJJE/flutter_tool.FJGYPZ/app.dill --libraries-spec file:///home/francesco/development/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.AWUJJE/flutter_tools.KHADHW --filesystem-scheme org-dartlang-app --initialize-from-dill
build/dfea9bfe94cb64da780a8ef62c567803.cache.dill.track.dill --platform file:///home/francesco/development/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +12 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10542 ms] Syncing files to device Chrome... (completed in 10,647ms, longer than expected)
[        ] Synced 26.4MB.
[        ] <- accept
[        ] Caching compiled dill
[ +257 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:38559/devtools/browser/4ee0c61d-280b-4728-9dd5-f447be6200f9
qqqq
Q
q
^C%         
```

</details>

`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v --release`

<details>
  <summary> logs</summary>

```bash
 francesco@francesco-yoga720  ~/projects/generative_art  flutter_master run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v --release                                            ✔  2476  16:46:55 
[ +108 ms] executing: [/home/francesco/development/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a51dc3d913344f3073da12f4aae654c3299dec6c
[        ] executing: [/home/francesco/development/flutter_master/] git tag --points-at HEAD
[  +11 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [/home/francesco/development/flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-139-ga51dc3d91
[  +13 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/francesco/development/flutter_master/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/home/francesco/development/flutter_master/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: /usr/lib/Android/platform-tools/adb devices -l
[  +16 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] executing: /usr/lib/Android/platform-tools/adb devices -l
[ +143 ms] Generating /home/francesco/projects/generative_art/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +69 ms] List of devices attached
[   +2 ms] List of devices attached
[  +56 ms] Launching lib/main.dart on Chrome in release mode...
[  +77 ms] Generating /home/francesco/projects/generative_art/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +7 ms] Compiling lib/main.dart for the Web...
[   +4 ms] Initializing file store
[   +4 ms] Done initializing file store
[  +62 ms] Skipping target: gen_localizations
[  +13 ms] Skipping target: web_entrypoint
[ +464 ms] dart2js: Starting due to {InvalidatedReason.inputChanged}
[+26804 ms] dart2js: Complete
[ +132 ms] web_release_bundle: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.outputChanged}
[ +107 ms] web_release_bundle: Complete
[  +87 ms] invalidated build due to missing files: build/web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +29 ms] web_service_worker: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.inputMissing}
[  +53 ms] web_service_worker: Complete
[   +3 ms] Persisting file store
[   +9 ms] Done persisting file store
[  +22 ms] Compiling lib/main.dart for the Web... (completed in 27.8s)
[ +217 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:40223/devtools/browser/105a0b93-0b3b-48af-a09a-87846f39e65b
[ +360 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +3 ms] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".
[+47178 ms] Application finished.
[   +7 ms] "flutter run" took 76,054ms.
[   +3 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

Regardless the use of a 3rd party plugin, I'd like to point out:
- flutter's behavior is inconsistent across `debug` and `release`
- in debug the terminal doesn't work as intended, namely `q` does not exit the app

@markusaksli-nc please consider reopening this issue

**Comment by markusaksli-nc** [comment] 2020-08-18 14:21
Alright I'll reopen for now in case this is an issue with the compiler. If this turns out to be invalid than this can still be considered a tool issue for not being able to quit since I observed that as well.

Marking as reproducible on the latest master `1.21.0-10.0.pre.135`, observed the same as @iapicca.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.135 at C:\Development\flutter_master
    • Framework revision 654022aecb (6 hours ago), 2020-08-18 03:01:02 +0300
    • Engine revision b9243713a0
    • Dart version 2.10.0 (build 2.10.0-36.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Comment by yjbanov** [comment] 2020-08-30 18:36
This sounds a lot like a DDC issue, since dart2js compiles this code without issues. @sigmundch can you please triage this?

**Comment by Markzipan** [comment] 2020-09-02 23:10
Following up here, this is confirmed to be a DDC issue. Something must have gone awry with our module ordering logic. I have a local pure-Dart repro of this failure, so I'll keep tinkering until I find the issue.

**Comment by ferhatb** [comment] 2020-09-09 23:30
@sigmundch verified this is DDC only, seems to be due to abstract base class not initialized yet when setting up ArtboardBase

 artboard_base.ArtboardBase = class ArtboardBase extends container_component.ContainerComponent {
 
is throwing exception since container_component.ContainerComponent is undefined (not initialized yet).

**Comment by Markzipan** [comment] 2020-09-10 00:03
Yep, this is a lib dependency ordering issue. I still have a minimal local repro and am cranking away at a fix. It should be out soon.

**Comment by creativecreatorormaybenot** [comment] 2020-09-16 09:47
@Markzipan I assume that you were able to fix the issue 🥳

Is there any chance this could get cherry-picked into `stable` or `beta`?

**Comment by sigmundch** [comment] 2020-09-16 18:48
Indeed, https://github.com/dart-lang/sdk/commit/53895b22707d986776db19d4c953d9d3b0178401 should fix this issue. Do let us know if that's not the case.

I filed a cherry-pick request for the Dart beta channel: https://github.com/dart-lang/sdk/issues/43453, which is intended to be part of the next beta and stable releases.

**Closed by sigmundch** 2020-09-16 18:48 UTC
Labels: P3, customer: thrive, customer: web10, dependency: dart, e: web_canvaskit, found in release: 1.21, has reproducible steps, p: third party, platform-web, severe: crash

**Comment by creativecreatorormaybenot** [comment] 2020-09-28 22:03
@sigmundch `rive` works now, but with the new beta version `universal_io` does not work anymore, unfortunately. 

There is a new type error, see https://github.com/flutter/flutter/issues/66859.

**Comment by Markzipan** [comment] 2020-10-02 22:49
Following up again, this issue's revealed a pretty severe historically-present issue in DDC. My previous fix was a much simpler patch that ended up breaking some hidden assumptions, but I'm working on a much more comprehensive fix.

**Comment by creativecreatorormaybenot** [comment] 2020-10-02 22:54
@Markzipan I reckoned it would be something along those lines, but that is great news 🎉

I am really excited for the comprehensive fix 🚀
