### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Bad state: StreamSink is closed".

### ISSUE THREAD

**Issue by ajaykumar2017** [flutter/flutter#55465] opened 2020-04-23 15:10 UTC
Flutter is exited unexpectedly with "Bad state: StreamSink is closed"

**Comment by VladyslavBondarenko** [comment] 2020-04-23 15:27
Hi @ajaykumar2017 
closing as duplicate of https://github.com/dart-lang/webdev/issues/943, it was fixed.
If you are experiencing this with master channel or current dev 1.18.0-6.0.pre, please provide your `flutter doctor -v` and logs of the error and I will reopen it

**Closed by VladyslavBondarenko** 2020-04-23 15:27 UTC

**Comment by ajaykumar2017** [comment] 2020-04-23 15:34
Hi @VladyslavBondarenko I am posting log of `flutter doctor -v` log
```
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Ajay\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```
