### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by ngdangtu-vn** [flutter/flutter#78107] opened 2021-03-13 12:44 UTC
## Command
```
flutter run -d Chrome
```

## ~Steps to~ Reproduce Requirement
1. Raspberry Pi 4 (8GB)
2. Ubuntu 20.10 `Linux linal 5.8.0-1016-raspi #19-Ubuntu SMP PREEMPT Tue Feb 9 20:12:43 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
3. Chromium 89 (installed via `apt`)

<details>
<summary><h2>What does dart-sdk lib contain?</h2></summary>

```bash
ngdangtu@raspberrypi:~/.local/flutter/bin/cache/dart-sdk/lib$ ll
total 120
drwxr-xr-x 25 ngdangtu ngdangtu  4096 Mar 11 07:40 ./
drwxr-xr-x  5 ngdangtu ngdangtu  4096 Mar 13 12:56 ../
-rw-r--r--  1 ngdangtu ngdangtu  1322 Mar 11 07:37 api_readme.md
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 async/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 cli/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 collection/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 convert/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 core/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 developer/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 ffi/
drwxr-xr-x  5 ngdangtu ngdangtu  4096 Mar 11 07:37 html/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 _http/
drwxr-xr-x  3 ngdangtu ngdangtu  4096 Mar 11 07:37 indexed_db/
drwxr-xr-x  6 ngdangtu ngdangtu  4096 Mar 11 07:51 _internal/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 internal/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 io/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 isolate/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 js/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 js_util/
-rw-r--r--  1 ngdangtu ngdangtu 14792 Mar 11 07:37 libraries.json
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 math/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 mirrors/
drwxr-xr-x  3 ngdangtu ngdangtu  4096 Mar 11 07:37 svg/
drwxr-xr-x  2 ngdangtu ngdangtu  4096 Mar 11 07:37 typed_data/
drwxr-xr-x  3 ngdangtu ngdangtu  4096 Mar 11 07:37 web_audio/
drwxr-xr-x  3 ngdangtu ngdangtu  4096 Mar 11 07:37 web_gl/
drwxr-xr-x  3 ngdangtu ngdangtu  4096 Mar 11 07:37 web_sql/
```

</details>

<details>
<summary><h2>Logs</h2></summary>

FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:770:57)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:733:54)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:516:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.41 at /home/ngdangtu/.local/flutter
    • Framework revision bc9d0e0a4b (2 days ago), 2021-03-11 17:25:02 +0530
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment] 2021-03-14 12:27
duplicate of https://github.com/flutter/flutter/issues/68958

**Comment by darshankawar** [comment] 2021-03-15 08:50
Closing this as duplicate of https://github.com/flutter/flutter/issues/68958

**Closed by darshankawar** 2021-03-15 08:50 UTC
Labels: in triage
