### ISSUE TITLE
fsutil error during installation on Windows.

### ISSUE THREAD

**Issue by chetanya1710** [flutter/flutter#15326] opened 2018-03-09 04:45 UTC
## Flutter Doctor

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...                         2.7s
Downloading package sky_engine...                     1.7s
Downloading common tools...                           4.1s
Downloading windows-x64 tools...                     17.7s
Downloading android-arm-profile/windows-x64 tools...  2.2s
Downloading android-arm-release/windows-x64 tools...  2.2s
Downloading android-arm64-profile/windows-x64 tools...  2.5s
Downloading android-arm64-release/windows-x64 tools...  2.4s
Downloading android-x86 tools...                     10.4s
Downloading android-x64 tools...                     10.9s
Downloading android-arm tools...                      9.2s
Downloading android-arm-profile tools...              6.7s
Downloading android-arm-release tools...              7.2s
Downloading android-arm64 tools...                    6.5s
Downloading android-arm64-profile tools...            6.1s
Downloading android-arm64-release tools...            6.0s
Downloading Gradle Wrapper...                         1.0s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 19.1.0)
[√] Android Studio (version 3.0)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.21.0)
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 14e926ccf48bfd1a)
CreateProcessW failed 193
Crash report written to C:\Windows\System32\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mravn-google** [comment] 2018-03-09 11:26
Possibly a duplicate of https://github.com/flutter/flutter/issues/15014

@chetanya1710 Thanks for reaching out. That does sound annoying. Would it be possible for you to attach `C:\Windows\System32\flutter_02.log` to this issue? That might speed up the process of resolving it.

**Comment by abhijit-kar** [comment] 2018-03-10 12:32
@mravn-google I faced the same problem, here's the Log u asked for. And it's not duplicate of #15014, because this comes after resolving that issue.

```
Usage : fsutil behavior query <option>

<option>

AllowExtChar
BugcheckOnCorrupt
Disable8dot3 [<Volume Path>]
DisableCompression
DisableCompressionLimit
DisableDeleteNotify [NTFS|ReFS]
DisableEncryption
DisableFileMetadataOptimization
DisableLastAccess
DisableSpotCorruptionHandling
EncryptPagingFile
MemoryUsage
MftZone
QuotaNotify
SymlinkEvaluation
DisableWriteAutoTiering [<Volume Path>]
DisableTxf [<Volume Path>]

Please use "fsutil 8dot3name query /?" for more information.

For DisableDeleteNotify if neither "NTFS" nor "ReFS" is specified, both values are shown.
```

**Comment by zoechi** [comment] 2018-07-31 20:01
Either #15014 or #18938

**Comment by zoechi** [comment] 2018-08-27 08:29
Is this still an issue?

**Comment by zoechi** [comment] 2018-10-08 09:01
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 09:01 UTC
Labels: a: first hour, waiting for customer response, ❖ platform-windows
