### ISSUE TITLE
PageView does not dispose page if it contains SelectableText 

### ISSUE THREAD

**Issue by dsolse** [flutter/flutter#93224] opened 2021-11-08 00:12 UTC
I am creating a reader with flutter, but on scrolling PageView does not dispose the content of the page because it has a SelectableText. The problem is behind the SelectableText because with Text it works fine. Also because of that, the app gets slow very quick.

I am currently using ScrollablePositionedList, but with ListView the same happend.

The code is a little more than what I show, but it explains the idea.

Any solutions or is a bug with the SelectableText widget?

```...
return PageView.builder(
      controller: controller.chaptersController,
      onPageChanged: (index) async {
        bookDataProvider.updateindexChapter(index);
        await db.updateLastChapterIndex(
          index,
          bookDataProvider.titleBook,
          bookDataProvider.language,
        );
      },
      itemBuilder: (BuildContext context, int itemIndex) {
          return ReaderChapter(
            controller: controller,
            doc: fileList.elementAt(itemIndex),
            isLastChapter: isLastChapter,
          );
      },
      itemCount: fileList.length + 1,
    );
...


class ReaderChapter extends StatelessWidget {
  const ReaderChapter({
    Key? key,
    required this.controller,
    required this.doc,
    required this.isLastChapter,
  }) : super(key: key);

  final EpubTextContentFile doc;
  final EbookController controller;
  final bool isLastChapter;


  @override
  Widget build(BuildContext context) {
    List<HtmlPragragh> paragraghs = [];
...

...
    final ItemPositionsListener itemPositionsListener =
        ItemPositionsListener.create();
    final ItemScrollController scroll = ItemScrollController();

    return ScrollablePositionedList.builder(
              ...
	      ...
              itemCount: paragraghs,
              itemBuilder: (context, index) => paragraghs.elementAt(index),
              itemPositionsListener: itemPositionsListener,
              itemScrollController: scroll,
    );
  }
}



class HtmlPragragh extends StatelessWidget {
  const HtmlPragragh({
    Key? key,
    required this.paragragh,
  }) : super(key: key);
  final String paragragh;

  @override
  Widget build(BuildContext context) {
	final splitSentence = ...
...  
    return Padding(
      padding:
          const EdgeInsets.only(left: 8.0, right: 8.0, bottom: 4.0, top: 0.0),
      child: SelectableText.rich(
        TextSpan(
          style: TextStyle(
            fontSize: dataT.fontSize,
          ),
          children: splitSentence,
      ),
    );
  }
}
```

Here is the flutter doctor: 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.62.0)
[√] VS Code, 64-bit edition (version 1.57.1)
[√] Connected device (2 available)

• No issues found!
```

 

https://user-images.githubusercontent.com/88752042/140666460-f09bb3b9-cfc3-4485-a1b9-aa6b92ad4921.mp4

**Comment by mamuseferha** [comment] 2021-11-08 07:55
Hi @dsolse, thank you for filing this issue.
For the issue to be workable, it needs to be reproducible with a minimal complete code sample that doesn’t include 3rd party plugins or complex production code. Please provide such sample.
Thank you

**Comment by dsolse** [comment] 2021-11-08 17:04
Thanks @mamuseferha, here is the code that shows the problem. The selectable text does not permit disposing while the Text does it in the scroll view.

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Example"),
      ),
      body: const PageViewEx(),
    );
  }
}

class PageViewEx extends StatelessWidget {
  const PageViewEx({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return PageView.builder(
      itemBuilder: (context, index) {
        if (index % 2 == 0) {
          return const ListViewWithSelectableText();
        } else {
          return const ListViewWithNormalText();
        }
      },
      itemCount: 10,
    );
  }
}

class ListViewWithSelectableText extends StatelessWidget {
  const ListViewWithSelectableText({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Expanded(
            flex: 4,
            child: Text("Selectable text: No disposing after page scrolling")),
        Expanded(
          flex: 40,
          child: ListView.builder(
            itemBuilder: (context, index) {
              return ListTile(
                  title: SelectableText(
                      "This is selectable text with index $index"));
            },
            itemCount: 40,
          ),
        ),
      ],
    );
  }
}

class ListViewWithNormalText extends StatelessWidget {
  const ListViewWithNormalText({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Expanded(flex: 4, child: Text("Text: Disposing without problem")),
        Expanded(
          flex: 40,
          child: ListView.builder(
            itemBuilder: (context, index) {
              return ListTile(
                  title: Text("This is normal text with index $index"));
            },
            itemCount: 40,
          ),
        ),
      ],
    );
  }
}
```

**Comment by mamuseferha** [comment] 2021-11-09 07:42
Hi @dsolse thank you for providing the sample code, `SelectableText` does not dispose because it uses the  `AutomaticKeepAliveClientMixin` mixin. 

This issue also seems to be a duplicate of https://github.com/flutter/flutter/issues/91509, you can follow up there as I will be closing this. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-09 07:42 UTC
Labels: in triage

**Comment by dsolse** [comment] 2021-11-09 17:17
So, by now is there no way to do what I want to? I mean, display a SelectableText in a PageView

**Comment by dsolse** [comment] 2021-11-09 23:01
Just tell me a way to implement what I want: To be able to add SelectableText to a PageView and dispose it when the page were swiped

**Comment by mamuseferha** [comment] 2021-11-10 07:10
@dsolse consider using a different widget instead of `SelectableText`, you can also check out this solution https://stackoverflow.com/a/67257370
