### ISSUE TITLE
signInWithCredential gives ERROR_REJECTED_CREDENTIAL when use with configured App to sign into other firebase project

### ISSUE THREAD

**Issue by Sengrith** [flutter/flutter#57948] opened 2020-05-25 14:58 UTC
Step to reproduce:

```
void login() {
  final app = FirebaseApp.configure(name: 'firebase-auth', options: {...});
  final auth = FirebaseAuth.fromApp(app);

  final onCodeSent = (String verificationId, [int force]) async {
    AuthCredential credential = PhoneAuthProvider.getCredential(
        verificationId: verificationId, smsCode: '123456');
    AuthResult result = await auth.signInWithCredential(credential);
  };

  app.verifyPhoneNumber(phoneNumber: '<<phoneNumber>>', codeSent: onCodeSent);
}

```
The code above give:

`ERROR_REJECTED_CREDENTIAL, The request contains malformed or mismatching credentials [ Project number mismatch. ], null`

I am sure the "project number" is correctly configured.

**Comment by TahaTesser** [comment] 2020-05-25 15:44
Hi @Sengrith 
For what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [Github](https://github.com/FirebaseExtended/flutterfire/issues). 
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-25 15:44 UTC
