### ISSUE TITLE
[go_router] nav_observer example shows go_router diagnostics info in the debug console when it shouldn't 

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99119] opened 2022-02-25 00:17 UTC
copied from https://github.com/csells/go_router/issues/250

The `debugLogDiagnostics` parameter to the GoRouter ctor is false, but the diagnostic logging info is still sent to the debug console.

**Comment by danagbemava-nc** [comment] 2022-04-13 10:19
I just looked into this, and the issue isn't from the `debugLogDiagnostics` parameter in the ctor. 

`MyNavObserver` has a logger of its own and it is set to listen to for any record in its ctor. 

```dart
class MyNavObserver extends NavigatorObserver {
  MyNavObserver() {
    log.onRecord.listen((e) => debugPrint('$e'));
  }

  final log = Logger('MyNavObserver');

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      log.info('didPush: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      log.info('didPop: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didRemove(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      log.info('didRemove: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) =>
      log.info('didReplace: new= ${newRoute?.str}, old= ${oldRoute?.str}');

  @override
  void didStartUserGesture(
    Route<dynamic> route,
    Route<dynamic>? previousRoute,
  ) =>
      log.info('didStartUserGesture: ${route.str}, '
          'previousRoute= ${previousRoute?.str}');

  @override
  void didStopUserGesture() => log.info('didStopUserGesture');
}
```

If the code in the ctor is commented out, nothing is logged to the debug console, since `debugLogDiagnostics` is false in the go_router ctor and based on [this comment](https://github.com/csells/go_router/issues/250#issuecomment-1005185447), I believe this example is working as intended and there isn't an issue with this. See video below

<details>
<summary>video </summary>

https://user-images.githubusercontent.com/88313112/163157073-e2daa3bb-e63f-4370-a0ff-4605949787b3.mov

</details>


Closing this as the example is WAI.

**Closed by danagbemava-nc** 2022-04-13 10:19 UTC
Labels: p: first party, package, in triage, P4, p: go_router
