### ISSUE TITLE
Windows - when maximize/resize window getting blank 

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#134880] opened 2023-09-16 17:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

create flutter windows project and run it.
this issue happened after install beta, 3.15.0-15.1.pre

### Expected results

should not blank screen

### Actual results

blank screen

### Code sample

<details><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/20491308/c73da1de-9343-4462-9a96-ed623429b100)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
__

### Flutter Doctor output

<details><summary>Doctor output</summary>

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.15.0-15.1.pre, on Microsoft Windows [Version 10.0.22621.2283], locale en-IN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by selvam920** [comment] 2023-09-16 17:45
![image](https://github.com/flutter/flutter/assets/20491308/b481273a-540d-4388-861d-ada3ca1c6eef)
![image](https://github.com/flutter/flutter/assets/20491308/eb813eda-b3ec-4b13-88ae-59d83572b408)

**Comment by jonahwilliams** [comment] 2023-09-16 19:55
Duplicate of https://github.com/flutter/flutter/issues/134262

**Closed by jonahwilliams** 2023-09-16 19:55 UTC
