### ISSUE TITLE
How can I make iOS also support delaying the obscuring of password input?

### ISSUE THREAD

**Issue by hello-soon** [flutter/flutter#129105] opened 2023-06-19 08:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

TextField component supports delaying the obscuring of password input on Android,
 but not on iOS where it immediately displays stars. 

How can I make iOS also support delaying the obscuring of password input?

### Proposal

 TextField(obscureText:true)

**Comment by dam-ease** [comment] 2023-06-19 12:50
Hi @hello-soon. Thanks for filing this issue. There seems to be an issue currently open that describes this issue. Kindly upvote and follow up on this issue for updates. Closing this as a duplicate of #115359

**Closed** 2023-06-19 12:50 UTC
Labels: in triage
