### ISSUE TITLE
[web] TextField with 'onEditingComplete' callback has problem with focus

### ISSUE THREAD

**Issue by mirkopoloni** [flutter/flutter#49570] opened 2020-01-27 19:02 UTC
Hello everybody,
I found a problem related to the TextField widget in combination with the 'onEditingComplete' callback.

### Which platform
The problem occurs when developing for the web, it works fine on Android and iOS.

### What I want to do
I use the 'onEditingComplete' callback with a TextField in order to preserve focus even when the user clicks outside the field.
The problem is that on the web the TextField seems to preserve focus once the user clicks outside it, but the field doesn't get the keyboard input anymore (need to manually refocus, click inside the field again).

### Steps to Reproduce
You can reproduce the steps here: https://dartpad.dev/3c4630a904451c887d8a070ce67c545c
1) Click on the TextField.
2) Insert some text.
3) Click outside the TextField.
4) The field seems to have focus, the cursor is there.
5) Try to write something, the text won't be inserted.

### More informations
The official doc for 'onEditingComplete' says:
(https://api.flutter.dev/flutter/material/TextField/onEditingComplete.html)

> Called when the user submits editable content (e.g., user presses the "done" button on the keyboard).
The default implementation of onEditingComplete executes 2 different behaviors based on the situation:
When a completion action is pressed, such as "done", "go", "send", or "search", the user's content is submitted to the controller and then focus is given up.
When a non-completion action is pressed, such as "next" or "previous", the user's content is submitted to the controller, but focus is not given up because developers may want to immediately move focus to another input widget within onSubmitted.
**Providing onEditingComplete prevents the aforementioned default behavior.**

Inside the flutter code here is where I found the 'onEditingComplete' function is called.
(flutter/packages/flutter/lib/src/widgets/editable_text.dart)
The field should lose focus only when the 'onEditingComplete' prop is null.

```dart
void _finalizeEditing(bool shouldUnfocus) {
    // Take any actions necessary now that the user has completed editing.
    if (widget.onEditingComplete != null) {
      widget.onEditingComplete();
    } else {
      // Default behavior if the developer did not provide an
      // onEditingComplete callback: Finalize editing and remove focus.
      widget.controller.clearComposing();
      if (shouldUnfocus)
        widget.focusNode.unfocus();
    }

    // Invoke optional callback with the user's submitted content.
    if (widget.onSubmitted != null)
      widget.onSubmitted(_value.text);
}
```

### Flutter doctor output
I tested it on both beta and dev channels.
#### Beta channel
```
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale it-DE)
    • Flutter version 1.13.6
    • Framework revision 659dc8129d (4 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
```

#### Dev channel
```
[✓] Flutter (Channel dev, v1.14.5, on Mac OS X 10.15.2 19C57, locale it-DE)
    • Flutter version 1.14.5
    • Framework revision 92cbaa3efe (4 days ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)
```

More infos
```
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

**Comment by iapicca** [comment] 2020-01-28 06:55
Hi @mirkopoloni 
could you please provide your `flutter doctor -v`
thank you for your clear and detailed explanation

**Comment by mirkopoloni** [comment] 2020-01-28 09:47
Hi @iapicca,
thanks for your quick answer and sorry for the missing informations, I forgot to add them.
I updated my previous message with the flutter doctor output, so that all infos stay in one place.

**Comment by zTrix** [comment] 2020-01-31 13:09
This problem does not appear on `v1.12.13`, so it's likely to be introduced in `v1.13.x`.

**Comment by nturgut** [comment] 2020-01-31 18:20
I'll have a look into this.

Thanks for filing the issue.

**Comment by nturgut** [comment] 2020-02-04 21:17
Hi,

When I synced to the latest master and tested the behaviour, I wasn't able to produce the issue. For me:

1. Click on the TextField.
2. Insert some text.
3. Click outside the TextField.
4. The text field looses focus and blur out.

There are lots of code paths there which checks the browser engine and the version. I suspect some browser engine might be inferred wrong.

Can you please share the browser+version+OS you saw this issue?

Best,

**Comment by mirkopoloni** [comment] 2020-02-05 10:26
Hi @nturgut,

I tested it on Mac OS X 10.15.2 (19C57) with Chrome (79.0.3945.130), Firefox (72.0.2) and Microsoft Edge (79.0.309.71).
I can reproduce the problem on every browser I tested.

Please let me know if there is something else I can do to help you.

**Comment by nturgut** [comment] 2020-02-05 16:24
My guess is the engine roll which fixes the issue is the channel you are using. 

Can you switch to master channel? For me the flutter doctor output starts with:

[✓] Flutter (Channel master, v1.14.7-pre.103, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.7-pre.103 at /usr/local/google/home/nurhan/development/flutter
    • Framework revision f14bc8fa5c (24 hours ago), 2020-02-04 11:36:41 -0500
    • Engine revision f44f50f3c5
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 c8ed304e97)

which has an engine version 4 weeks newer.

Let me know if the issue still continues, I'll have another look.

**Comment by mdebbar** [comment] 2020-02-05 18:45
@mirkopoloni thanks for reporting the issue. I was able to repro.

The issue here is that you're falling into a situation where the engine and the framework don't agree on the current state of focus. The framework thinks the text field is focused (hence, it renders the cursor, etc). The engine thinks the text field lost focus because the user has clicked away.

What happens here is the engine tells the framework to [close the connection](https://github.com/flutter/flutter/blob/374b55cc608bcc555713b37afa1ce8b089c4800c/packages/flutter/lib/src/widgets/editable_text.dart#L1471-L1478). The framework tries to [finalize editing](https://github.com/flutter/flutter/blob/374b55cc608bcc555713b37afa1ce8b089c4800c/packages/flutter/lib/src/widgets/editable_text.dart#L1333-L1348) of the text field but fails to unfocus even though `shouldUnfocus` is set to true. I'm not sure if this is by design or just an oversight (cc @nturgut @dnfield @franciscojma86).

As a workaround for now, you can do the following:
```dart
// Create a focus node somewhere in a stateful widget.
final FocusNode focusNode = FocusNode();

// Pass that focusNode to the TextField.
TextField(
  focusNode: focusNode,
  onEditingComplete: () {
    focusNode.unfocus();
    scheduleMicrotask(focusNode.requestFocus); // need to `import 'dart:async';`
  }
)
```

**Comment by pedromassangocode** [comment] 2020-09-24 09:30
I was not able to reproduce this on latest master channel.

Closing as probably fixed. For anyone interested in text field losing focus when clicking away please see https://github.com/flutter/flutter/issues/58207#issuecomment-639921667.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 1fef5912cf (4 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Closed by pedromassangocode** 2020-09-24 09:30 UTC
Labels: P4, a: text input, engine, f: focus, framework, platform-web

**Comment by hacker1024** [comment] 2020-09-30 08:58
I'm getting this exact issue on `master` - but only in Firefox (Dev Edition 82), and not Chrome or Safari. Here's a simple (just one Dart file) app I've been working on that has the issue: https://github.com/hacker1024/crc_graphics_id_converter/blob/master/graphics_id_converter_gui/lib/main.dart

The app is hosted here, if you'd like to try it yourself: https://crcgraphicsidconverter.hacker1024.tk

Click off the text field, and then click on it again. You'll notice that nothing changes visually, but it's impossible to write in it after doing so.

**Comment by pedromassangocode** [comment] 2020-09-30 09:26
Hi @hacker1024 
Please create a new issue and link it into this one. Since this has been closed as fixed and your issue may be caused by some other things.
Thank you
