### ISSUE TITLE
Web autofill throw exception when using html InputElement

### ISSUE THREAD

**Issue by dtruong27** [flutter/flutter#114620] opened 2022-11-03 16:14 UTC
## Steps to Reproduce

For some reason, the browser did not store my text in the release web build, but the exception occurs when I debug the code:

1. Run the app in debug mode with chrome as the device 
2. Enter first character of some stored text (for example in the attached video, I entered 7 because I had 700 stored by my browser) 
3. Tap on a text suggested by the browser (in my video, it is 700) 

**Expected results:** 

The suggested text should display without any exception

**Actual results:** 

I got the exception:

```
errors.dart:266 Uncaught Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:266:49)
    at Object.nullCheck (operations.dart:528:63)
    at [_handleEvent] (keyboard_binding.dart:347:38)
    at _engine.KeyboardConverter.new.handleEvent (keyboard_binding.dart:542:7)
    at keyboard_binding.dart:141:25
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at ret (js_patch.dart:413:11)
    at loggedHandler (keyboard_binding.dart:112:23)
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at ret (js_patch.dart:413:11)
throw_ @ errors.dart:266
nullCheck @ operations.dart:528
[_handleEvent] @ keyboard_binding.dart:347
handleEvent @ keyboard_binding.dart:542
(anonymous) @ keyboard_binding.dart:141
_checkAndCall @ operations.dart:334
dcall @ operations.dart:339
ret @ js_patch.dart:413
loggedHandler @ keyboard_binding.dart:112
_checkAndCall @ operations.dart:334
dcall @ operations.dart:339
ret @ js_patch.dart:413
errors.dart:266 Uncaught Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:266:49)
    at Object.nullCheck (operations.dart:528:63)
    at [_handleEvent] (keyboard_binding.dart:347:38)
    at _engine.KeyboardConverter.new.handleEvent (keyboard_binding.dart:542:7)
    at keyboard_binding.dart:144:25
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at ret (js_patch.dart:413:11)
    at loggedHandler (keyboard_binding.dart:112:23)
    at Object._checkAndCall (operations.dart:334:14)
    at Object.dcall (operations.dart:339:39)
    at ret (js_patch.dart:413:11)
```

<details>
<summary>Code sample</summary>

main.dart

```dart
import 'package:flutter/material.dart';

import 'text_input_native.dart' if (dart.library.html) 'text_input_web.dart'
    as text_input;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: AutofillGroup(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [
            Text(
              'Please enter email',
            ),
            Padding(
              padding: EdgeInsets.all(12.0),
              child: text_input.MyTextInput(),
            ),
            Text(
              'Please enter again',
            ),
            Padding(
              padding: EdgeInsets.all(12.0),
              child: text_input.MyTextInput(),
            ),
          ],
        )),
      ),
    );
  }
}
```

text_input_web.dart

```dart
import 'package:flutter/material.dart';
import 'package:universal_html/html.dart' as html;
import 'dart:ui' as ui;

class MyTextInput extends StatelessWidget {
  const MyTextInput({super.key});

  html.HtmlElement _textInput(int id) {
    return html.InputElement()
      ..id = 'text'
      ..type = 'text'
      ..name = 'text'
      ..className = 'text-input'
      ..placeholder = 'Text'
      ..autocomplete = 'email'
      ..style.cssText = 'width: 100%; height: 100%;';
  }

  @override
  Widget build(BuildContext context) {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'my_text_input',
      (int id) => _textInput(id),
    );

    return const SizedBox(
      height: 60,
      child: HtmlElementView(
        viewType: 'my_text_input',
      ),
    );
  }
}
```

text_input_native.dart

```dart
import 'package:flutter/material.dart';

class MyTextInput extends StatelessWidget {
  const MyTextInput({super.key});

  @override
  Widget build(BuildContext context) {
    return const TextField();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[+2473 ms] Error: Unexpected null value.
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
                    lib/_engine/engine/keyboard_binding.dart 347:38                                   [_handleEvent]
                    lib/_engine/engine/keyboard_binding.dart 542:7                                    handleEvent
                    lib/_engine/engine/keyboard_binding.dart 141:25                                   <fn>
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
                    lib/_engine/engine/keyboard_binding.dart 112:23                                   loggedHandler
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
[   +8 ms] Error: Unexpected null value.
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
           lib/_engine/engine/keyboard_binding.dart 347:38                                   [_handleEvent]
           lib/_engine/engine/keyboard_binding.dart 542:7                                    handleEvent
           lib/_engine/engine/keyboard_binding.dart 144:25                                   <fn>
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
           lib/_engine/engine/keyboard_binding.dart 112:23                                   loggedHandler
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
           dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
```

```
Analyzing test_keyboard_event...                                        
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-GB)
    • Flutter version 3.3.7 on channel stable at /Users/duy/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/duy/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/8568489/199770875-ae892c1b-2e89-402f-9c9d-2b5c2dfd4efa.mov

**Comment by dtruong27** [comment] 2022-11-03 16:15
The issue is related to https://github.com/flutter/flutter/issues/85807

But in my example, html.InputElement is used.

**Comment by darshankawar** [comment] 2022-11-04 06:45
Thanks for the report. Using the code sample, I see same error log as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.5.0-12.0.pre.105, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.105 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 44b6cd2ec7 (2 hours ago), 2022-11-03 23:02:22 -0400
    • Engine revision fb7cde6970
    • Dart version 2.19.0 (build 2.19.0-370.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by EBBozkurt** [comment] 2023-09-07 14:08
Is there any update about this issue? I have same situation (same as #122691 too). Actually works perfectly in build but appears in debug.


Here is the output of error: 

``` 
Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 855:63  nullCheck
lib/_engine/engine/keyboard_binding.dart 372:38                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 582:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 98:18                                    <fn>
lib/_engine/engine/keyboard_binding.dart 140:16                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall

Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 855:63  nullCheck
lib/_engine/engine/keyboard_binding.dart 372:38                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 582:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 101:18                                   <fn>
lib/_engine/engine/keyboard_binding.dart 140:16                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

Here is my Flutter specs, if needed: 

```
Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (2 weeks ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by SaltH2OFish** [comment] 2023-09-12 17:06
I too am experiencing same error, however it occurs when Flutter Web attempts to autofill in a field from previous used values.

[✓] Flutter (Channel stable, 3.13.3, on macOS 13.4.1 22F82 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.82.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by raymondjohnaov** [comment] 2023-09-14 03:30
I'm also getting the same error.

[√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.4 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (23 hours ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\raymondjohn\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.82.1)
    • VS Code at C:\Users\raymondjohn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 116.0.5845.189
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 116.0.1938.69

[√] Network resources
    • All expected network resources are available.
    

Its because event.key is null when the input is auto filled.

![image](https://github.com/flutter/flutter/assets/50701673/d60f5cde-2e2a-4fb4-92c8-357cd427e35a)

**Comment by yhelwa** [comment] 2023-09-20 11:34
Facing similar issue. Also why is it immediately filling the form instead of opening the password manager for me to choose the credentials? Is there a way for me to disable that and just show the available credentials?

**Comment by LightDragooon** [comment] 2023-10-02 02:20
Hello!

I am facing the same issue but I am not using **html.InputElement** just TextFormFields. After a quick debugging I found that for each TextFormField I am getting 2 exceptions. Both of them occur in the same place shown by @raymondjohnaov screenshot. The events that triggers are "keydown" and "keyup". From my side everything else works as expected, the issue is that it throws this exception.

`TextFormField(
                  autofillHints: const [AutofillHints.username],
                  restorationId: 'email_field',
                  textInputAction: TextInputAction.next,
                  textCapitalization: TextCapitalization.words,
                  decoration: const InputDecoration(
                    filled: true,
                    icon: Icon(Icons.mail),
                    labelText: 'Correo electrónico',
                  ),
                  onSaved: (value) {
                    loginData.email = value;
                    _password.requestFocus();
                  },
                  validator: _validateEmail,
                )`

**Comment by jozes** [comment] 2023-10-05 09:55
Having same problem in latest stable version 3.13.6 version on web platform.

Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 855:63  nullCheck
lib/_engine/engine/keyboard_binding.dart 372:38                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 582:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 98:18                                    <fn>
lib/_engine/engine/keyboard_binding.dart 140:16                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall

the above error is repeated  2 times for each field.

The error occurs when autofill populates the login fields.

Any progress on this issue?

**Comment by james-pellow** [comment] 2023-10-20 20:32
I'm a bit surprised by this situation.  Is anyone actually using flutter for web?  Not having autofill in forms is a bit severe!  I'm experiencing the same issue, and the minimal code is found below.  It works fine on macos, but on web it crashes as has already been accurately described.  The fact that this ticket has gone nearly an entire year without any serious reply leaves me feeling a bit nervous about flutter for the web.  At this point, I don't know of a way to make autofill work for web, and it doesn't look like anyone else does either given the lack of solutions here.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormState>();
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Form(
        key: _formKey,
        child: Center(
          child: SizedBox(
            width: 300,
            child: AutofillGroup(
              child: Column(
                children: <Widget>[
                  TextFormField(
                    controller: _usernameController,
                    autofillHints: const [AutofillHints.username],
                    decoration: const InputDecoration(
                      border: UnderlineInputBorder(),
                      labelText: 'Enter your username',
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter some text';
                      }
                      return null;
                    },
                  ),
                  TextFormField(
                    controller: _passwordController,
                    autofillHints: const [AutofillHints.password],
                    decoration: const InputDecoration(
                      border: UnderlineInputBorder(),
                      labelText: 'Enter your password',
                    ),
                    obscureText: true,
                    validator: (value) {
                      if (value == null || value.characters.length < 8) {
                        return 'Please enter a password with at least 8 characters';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 20),
                  ElevatedButton(
                    onPressed: () {
                      if (_formKey.currentState!.validate()) {
                        TextInput.finishAutofillContext();

                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(content: Text('Processing Data')),
                        );
                      }
                    },
                    child: const Text('Submit'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by jozes** [comment] 2023-10-20 21:57
@darshankawar Can you please check why this crash has still no solution? Is this problem assigned to anybody?
Thanks!

**Comment by Shery573** [comment] 2023-10-27 22:54
Happening with textfields too

**Comment by james-pellow** [comment] 2023-11-01 18:54
I appreciate you passing this on @jozes.  Is there any kind of an ETA on this @darshankawar?  Thank you for looking at this, as its causing us and others a fair level of pain.  There does seem to be a race of some kind as some times it works fine and others we wind up having to continue execution in the debugger twice per field in the form for exceptions.  That may explain why it does seem to be working for some people.

**Comment by darshankawar** [comment] 2023-11-02 05:10
The issue is assigned P2 priority. Please take a look at https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities to understand what it means and when it will be likely to be taken up and fixed.

**Comment by faFrafa** [comment] 2023-11-15 11:41
I also have this issue in Flutter web. Any update on a possible fix? Null safety, should be an easy one to fix.

**Comment by john-paradym** [comment] 2024-02-06 10:02
Any progress on this, or anyway we can track progress? Or any workarounds at all?

We're evaluating whether to use Flutter for web for fairly large project, and this is pretty much a blocker for any form entry/login screen of course.

As James says above, I'm now very much doubting that anyone is using Flutter for web for any significant projects 😞

**Comment by robertoestivill** [comment] 2024-02-06 10:04
> I'm now very much doubting that anyone is using Flutter for web for any significant projects 😞

**Comment by asda10** [comment] 2024-02-12 12:47
Same issue, same feeling...

**Comment by robertoestivill** [comment] 2024-02-12 13:08
> I have developed a web app in flutter which runs perfectly and is in production for a year and half. It is quite a complex app with complicated entry forms and utilising also Google maps (web version). During the development one will encounter some problems for which one needs to find good viable workarounds. Until the system level (flutter) is running without problems, you are fine. I must say that this is actually the only bug which is causing problems. I have just disabled autofill as the only place where the app is using it is for the login form. It is annoying that such basic functionality is not working and even greater shame is that the bug is not fixed for such a long period.


I'm glad you find the framework a great fit for your needs and you are happy with it. 
I wish my experience was the same. 
I've been running an app since December 2021 and so far I've hit all the following issues that are still open (some of them are related to this issue):

https://github.com/flutter/flutter/issues/87735
https://github.com/flutter/flutter/issues/120613
https://github.com/flutter/flutter/issues/72953
https://github.com/flutter/flutter/issues/52207
https://github.com/flutter/flutter/issues/33577
https://github.com/flutter/flutter/issues/122541

Many more have been closed in the process, which is a testament to how alive the development is.
Having to wait for new releases to fix customer issues is not a good business/product strategy though. 
Password managers, autofill, minimized rendering, are all break or make product features from my point of view.

I'm stuck with it for the long run and happy to work around it personally, but if you are after a good native web experience recommendation, I would personally, not recommend it.

**Comment by jozes** [comment] 2024-02-12 13:37
@robertoestivill 
I agree that the development team is obviously not coping with the amount of bugs. It seems that they have kind of a strange algorithm for defining the priority of resolving the bugs. Maybe they should stop working on development of new versions and first get rid of huge backlog of quite annoying bugs. Some of these bugs are resolved within new releases, but some of theme are more or less version independent and should be resolved.

The major reason why I have chosen flutter also for web application was the possibility to reuse a lot of code which was developed either for mobile app or web app. Honestly speaking, I had moment's when I have regretted  this decision. But at the end I was happy that I had made this decision. If I would have chosen another open source web development platform I would encounter similar problems. That is my experience from many past projects.
During the development I had much bigger problem with packages downloaded from pub.dev that became stale and their authors are not maintaining them any more or they maintain them with a huge lag. For some of them I had to simply prepare my own package to get rid of problems that I can't upgrade flutter. Yeah, a life of app developer was never an easy one and will never be. :-)  

Recently we were celebrating Christmas and maybe we should have written a letter to Santa to speed up resolving this bug. :-)

**Comment by faFrafa** [comment] 2024-02-12 15:35
To raise the priority of this issue we need to thumb-up the 1st comment of the ticket (see explanation in the link below). 

Please do so, otherwise, the maintainers will keep this issue in P2 (important, but can wait).

https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs

**Closed** 2024-02-16 07:04 UTC
Labels: c: crash, engine, platform-web, has reproducible steps, P2, found in release: 3.3, found in release: 3.5, team-web, triaged-web
