### ISSUE TITLE
Building Beautiful UIs with Flutter IconButton splash bug

### ISSUE THREAD

**Issue by ivangn03** [flutter/flutter#29040] opened 2019-03-08 09:05 UTC
## Steps to Reproduce

https://codelabs.developers.google.com/codelabs/flutter/#4

1. 
![splash_bug](https://user-images.githubusercontent.com/35631673/54018469-6742b880-4191-11e9-8b19-b3127883a60d.png)

2. 
![splash_bug_2](https://user-images.githubusercontent.com/35631673/54018659-f18b1c80-4191-11e9-9a5d-c37417a4abcb.png)

3. IconButton's splash doesn't work properly.

## Logs

```
```

```
[  +20 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[   +1 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] e5b1ed7a7f7b85c1877e09a9495681f719be5578
[        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[  +41 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 34 hours ago
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +52 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.3.8-0-ge5b1ed7a7
[ +118 ms] "flutter run" took 24ms.
[   +3 ms] "flutter run" took 24ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:627:9)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:239:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:529:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:486:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:477:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#34     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

```
√] Flutter (Channel dev, v1.3.8, on Microsoft Windows [Version 10.0.17134.590], locale ru-RU)
    • Flutter version 1.3.8 at C:\src\flutter
    • Framework revision e5b1ed7a7f (34 hours ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ivang\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.7
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\ivang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by darshankawar** [comment] 2020-07-08 11:09
Hi @ivangn03,
Can you please confirm if you still experience this issue on latest Flutter channel (eg : dev) ? 
If so, can you also provide minimal complete reproducible code sample ?

**Comment by markusaksli-nc** [comment] 2020-07-14 08:50
Hi @ivangn03 
This issue occurs due to the ripple being needed to render onto a Material. The Container decoration covers the Material. A workaround is mentioned in [this SO answer](https://stackoverflow.com/a/56231406). I've attached some sample code with a commented solution. Follow up on #31541 where the issue is tracked. Leaving it open with the purpose of editing codelab. Feel free to close if it will not be updated and #31541 will be fixed instead.
<details>
 <summary>Sample code</summary>

 ```
import 'package:flutter/material.dart';

void main() {
  runApp(
    FriendlyChatApp(),
  );
}

class FriendlyChatApp extends StatelessWidget {
  const FriendlyChatApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FriendlyChat',
      home: ChatScreen(),
    );
  }
}

class ChatScreen extends StatefulWidget {
  @override
  _ChatScreenState createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final _textController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("FriendlyChat"),
      ),
      body: Container(
          decoration: BoxDecoration(color: Theme.of(context).cardColor),
          child: _buildTextComposer()),
    );
  }

  Widget _buildTextComposer() {
    return Container(
        margin: EdgeInsets.symmetric(horizontal: 8.0),
        child: IconButton(
            icon: const Icon(Icons.send),
            onPressed: () => _handleSubmitted(_textController.text)));
    /*Material(
            child: IconButton(
                icon: const Icon(Icons.send),
                onPressed: () => _handleSubmitted(_textController.text)
            )
      );*/
  }

  void _handleSubmitted(String text) {
    _textController.clear();
  }
}
```
</details>

**Comment by maheshmnj** [comment] 2021-03-18 16:01
Whats the expected behavior? I made few changes and wrapped the Icon button in Material widget and the ripple seems to fill up the parent is that the expected behavior?
<img src="https://user-images.githubusercontent.com/31410839/111656378-7b195e80-8830-11eb-8d6b-db1370b9be35.png" width ="200">

**Comment by ivangn03** [comment] 2021-03-18 21:02
Yeah it's fine.

**Closed** 2021-03-18 21:02 UTC
Labels: d: codelabs, documentation, f: material design, framework, passed first triage
