### ISSUE TITLE
 Issue: Flutter plugin not installed; this adds Flutter specific functionality.     X Dart plugin not installed; this adds Dart specific functionality.

### ISSUE THREAD

**Issue by Sh00ny** [flutter/flutter#68274] opened 2020-10-16 05:36 UTC
Flutter doctor gives an error but  I can build my app without any problem in android studio. 

Dart and flutter plugin are installed

Questions: Is it a bug? Will I have any problem in my release version app? How can I solve it?

Logs :
//I tried reinstalling dart and flutter plugin didn't work.

√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
    • Flutter version 1.22.1 at C:\src\flutter\flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Shoony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

<img width="541" alt="Untitled picture" src="https://user-images.githubusercontent.com/64748053/96217069-7d387200-0f9f-11eb-99e2-79daf50247ba.png">

**Comment by sidrao2006** [comment] 2020-10-16 07:47
Hey @Sh00ny , this is not a bug.

Flutter and dart plugins are avaliable for Android Studio and some other IDEs to improve the development experience. 

For example, tye dart plugin has a default formatter, it also enables [dart lints](https://dart-lang.github.io/linter/lints/).
The flutter plugin adds a few buttons in your IDE to enable running `pub get`, `pub upgrade`, etc. which makes them easier to use.

Yes, definitely you can build and run your app without these plugins, but to make the most out of your IDE and your time, it is suggested that you install these plugins

**Comment by sidrao2006** [comment] 2020-10-16 08:36
@Sh00ny , I think this may be a known issue that Android 4.1 is not compatible with the flutter and dart plugins

**Comment by darshankawar** [comment] 2020-10-16 09:05
@Sh00ny 
The plugin warnings do not matter. See [this](https://github.com/flutter/flutter/issues/67986#issuecomment-707881534) comment for reference. Also this is similar to [67986](https://github.com/flutter/flutter/issues/67986).
Closing this as duplicate.

**Closed by darshankawar** 2020-10-16 09:05 UTC

**Comment by eckhartcke** [comment] 2020-10-22 15:29
The warnings are/were true. The dart and flutter plugins were nonfunctional as flutter doctor reports. I downgraded my Android Studio until it gets fixed because I depend heavily on these plugins.

**Comment by Daniell-Dantas** [comment] 2020-11-12 01:15
Hi! How can i downgrad Android Studio?
