### ISSUE TITLE
The map widget is overlapping other widgets

### ISSUE THREAD

**Issue by Flerma98** [flutter/flutter#113051] opened 2022-10-06 18:09 UTC
## Steps to Reproduce

Navigate to other page route.

Minimize the app and open it again.

The map will be above everything.

![Screenshot_20221006_120819](https://user-images.githubusercontent.com/39601246/194387206-447ab1a6-3e10-495a-83b3-d36a01709a0b.png)

**Comment by iapicca** [comment] 2022-10-06 19:42
a code sample could help to understand the problem

**Comment by danagbemava-nc** [comment] 2022-10-07 09:28
Hi @Flerma98, this is a duplicate of https://github.com/flutter/flutter/issues/89558. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. Kindly upvote the issue linked above.

Thank you

**Closed by danagbemava-nc** 2022-10-07 09:28 UTC
Labels: in triage
