### ISSUE TITLE
Work with flutter offline

### ISSUE THREAD

**Issue by abmoudz** [flutter/flutter#15759] opened 2018-03-20 19:14 UTC
hello i am new to this so my issue is i wanna work with flutter but i wanna do it offline but evry time i disconnect from intrenet i cant creat a new project 
i found online the commande --offline but i dont realy know where to add it 

ps:i am using windows

**Comment by rmtmckenzie** [comment] 2018-03-20 20:44
Have you already created a project while online? The first time you create a project, it needs to download and cache dependencies. It will then need to download more when you actually build for a device (using gradle or cocoapods for android and ios respectively).

Once you have the cashes, you should be able to run `flutter create --offline` and `flutter packages get --offline`.

Gradle technically does cache resources system-wide so you might be okay running it offline with a new project, but cocoapods does not.

This is probably a duplicate of #1945 though.

**Comment by abmoudz** [comment] 2018-03-20 20:54
@rmtmckenzie  my question is where to run that command exctly ?:

**Comment by Hixie** [comment] 2018-03-20 23:32
Run it in the command line, under a `cmd` shell.

**Comment by abmoudz** [comment] 2018-03-20 23:36
@Hixie 

i am getting this on the windows command shell

PS C:\WINDOWS\system32> flutter packages get --offline
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.


PS C:\WINDOWS\system32> flutter create --offline
No option specified for the output directory.
Create a new Flutter project.

If run on a project that already exists, this will repair the project, recreating any files that are missing.

Usage: flutter create <output directory>
-h, --help                     Print this usage information.
    --[no-]pub                 Whether to run "flutter packages get" after the project has been created.
                               (defaults to on)

**Comment by abmoudz** [comment] 2018-03-20 23:38
i thinks i am realy bad at this 👎

**Closed** 2018-03-20 23:46 UTC
Labels: waiting for customer response
