### ISSUE TITLE
Application don't run on iOS 13

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#40998] opened 2019-09-20 21:08 UTC
So, I recently updated to iOS 13 and now I am having a lot of issues...

My Flutter proyect don't run on a device with iOS 13 no matter it is a real device or an emulator, but there is more... I don't know why but my iPhone Xr is not being detected by VScode not from the bottom status bar nor even from crommand `flutter devices`. Simulators are detected but, like I said, app wont run.

This is what I get when I try to run on a iOS 13 simulator
```
Launching lib/main.dart on iPhone Xr13 in debug mode...
Xcode build done.                                           99,4s
	path: satisfied (Path is satisfied), interface: en0
[Crashlytics] Version 3.14.0 (144)
	path: satisfied (Path is satisfied), interface: en0
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98958 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff255eb6f5 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   MediaPlayer                         0x00007fff278e90b0 -[MPRemoteCommand addTarget:action:] + 1154
	5   flutter_radio                       0x000000010edf6129 -[FlutterRadioPlugin init] + 697
	6   flutter_radio                       0x000000010edf5ded +[FlutterRadioPlugin registerWithRegistrar:] + 173
	7   Runner                   <…>
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51030/u90zzfWNYiI=/ws
Exited (sigterm)
```

I tested on an iOS 12 simulator and works like it used to do...

This is `flutter doctor -v` (while my iPhone Xr was attached)

```
AlfredoMBPro:apperto alfredo$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale es-AR)
    • Flutter version 1.9.1+hotfix.2 at /Users/alfredo/Desktop/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • iPhone Xr12 • D9D6E659-D615-4AED-9023-8F542E15A7BC • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)
    • iPhone Xr13 • 827CF0D7-A526-46B4-8D2F-33BE7432FD8E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

UPDATE: Since flutter version 1.9 when I run or build my app a file called `flutter_export_environment.sh` is added to `ios/Flutter/`. What is this file for? I suppose this file sets environments variables but why it wasn´t used before? 

Flutter 1.9.1+hotfix.2 • channel stable isn't listed on changelog...

**Comment by quetool** [comment] 2019-09-20 21:58
UPDATE: So, I've solved the first issue listed and It turned out that is an issue from a particular plugin, so, dismiss that one.

There's still the `No Device Detected` issue but I was able to launch my app directly from XCode and now it crashes with this log:

```
2019-09-20 18:53:47.506672-0300 Runner[1106:68348] *** Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UIApplication.m:5240
2019-09-20 18:53:47.507714-0300 Runner[1106:68348] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
*** First throw call stack:
(0x1a3ba954c 0x1a38c40c8 0x1a3aa6330 0x1a3ee6368 0x1a7c12498 0x1a7c12a34 0x1a3f4e5d4 0x1a3e660a0 0x10a0d4c78 0x104c81104 0x104c1d738 0x104c726d8 0x104c2bf94 0x104c2e974 0x1a3b251b4 0x1a3b24eec 0x1a3b24560 0x1a3b1f408 0x1a3b1e978 0x1adc4e534 0x1a7c10f0c 0x1043af6a0 0x1a399ef04)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by christopherfujino** [comment] 2019-09-21 00:17
Can you try `rm -rf /Users/alfredo/Desktop/flutter/bin/cache; flutter devices` and see if that resolves your issue with your device not being detected? There was an issue with the cached artifacts that I have since fixed which is probably the cause.

As for the other issue, I haven't tried an ios13 emulator, but it sounds like [this issue](https://github.com/flutter/flutter/issues/40448). The fix for that is currently on the dev branch, you can test that out by checking out dev: `flutter channel dev`.

**Comment by ramamurthyk** [comment] 2019-09-21 12:15
I started facing the issue since this morning after Xcode automatically got upgraded to v11 :(

**Flutter doctor:**
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/***/documents/code/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/***/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • ONEPLUS A3003     • 192.168.0.10:5555                    • android-arm64 • Android 9 (API 28)
    • iPhone Xs Max     • 3DC9513C-E389-42E1-BC98-57D28AE08907 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone 11 Pro Max • 6DA18FF5-7296-401D-8AAB-EF466932587C • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
No issues found!

**Behaviour on:**
iOS-13 simulator - failed both from VS Code and Xcode
**While running from Xcode:**

2019-09-21 12:51:38.440378+0100 Runner[75876:7237792] flutter: Observatory listening on http://127.0.0.1:51229/1Jai67Gkpnw=/
2019-09-21 12:51:39.294566+0100 Runner[75876:7237145] *** Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/UIApplication.m:5240
2019-09-21 12:51:39.392722+0100 Runner[75876:7237145] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98958 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff255eb6f5 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff47163f36 -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:] + 255
	5   UIKitCore                           0x00007fff471643d9 -[UIApplication statusBar] + 24
	6   Foundation                          0x00007fff256146ef -[NSObject(NSKeyValueCoding) valueForKey:] + 317
	7   flutter_statusbarcolor              0x0000000109a430db -[FlutterStatusbarcolorPlugin handleMethodCall:result:] + 955
	8   Flutter                             0x00000001077a54fd __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	9   Flutter                             0x000000010773eec0 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	10  Flutter                             0x0000000107742780 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	11  Flutter                             0x000000010779fdb3 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_31NS_9allocatorIS8_EEFvvEEclEv + 57
	12  Flutter                             0x00000001077513f1 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 123
	13  Flutter                             0x0000000107756742 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	14  CoreFoundation                      0x00007fff23afc1e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23afbed2 __CFRunLoopDoTimer + 1026
	16  CoreFoundation                      0x00007fff23afb52a __CFRunLoopDoTimers + 266
	17  CoreFoundation                      0x00007fff23af629e __CFRunLoopRun + 2238
	18  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	19  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	20  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	21  Runner                              0x0000000104efee38 main + 72
	22  libdyld.dylib                       0x00007fff5123bcf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

It looks like a plugin to set status bar colour is faulting, hence the error. The app with the plugin was working fine in older versions (<iOS13).
Removed the plugin and now I'm able to build and debug the app on Simulator. Haven't tested on physical device yet.

Culprit plugin is: flutter_statusbarcolor: ^0.2.1
I'll report to the plugin dev to have a look at this issue.

latest status on iOS 13:
- [x] App building and launching fine on iOS13 simulator
- [x] Hot reload is working fine
- [ ] Haven't tested on iOS13 physical device yet

Hope this is useful to you folks.

**Comment by quetool** [comment] 2019-09-23 12:36
> Can you try `rm -rf /Users/alfredo/Desktop/flutter/bin/cache; flutter devices` and see if that resolves your issue with your device not being detected?

Indeed, that solved the issue, thanks!

> As for the other issue, I haven't tried an ios13 emulator, but it sounds like [this issue](https://github.com/flutter/flutter/issues/40448). The fix for that is currently on the dev branch, you can test that out by checking out dev: `flutter channel dev`.

I am already on dev channel...

**Comment by quetool** [comment] 2019-09-23 13:46
@christopherfujino  So, after deleting cache like @christopherfujino says the app starting to run again, but still crashing with some navigationbar related issue

This is the complete log from Debugger (Observatory)
https://gist.github.com/quetool/796fd0792237b62abf66c675b4f40653

And this is what Xcode says about...
```
2019-09-23 10:45:19.359579-0300 Runner[14794:998907] *** Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UIApplication.m:5240
2019-09-23 10:45:19.361845-0300 Runner[14794:998907] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
*** First throw call stack:
(0x1a3ba954c 0x1a38c40c8 0x1a3aa6330 0x1a3ee6368 0x1a7c12498 0x1a7c12a34 0x1a3f4e5d4 0x1a3e660a0 0x10a8f4c78 0x1054bd104 0x105459738 0x1054ae6d8 0x105467f94 0x10546a974 0x1a3b251b4 0x1a3b24eec 0x1a3b24560 0x1a3b1f408 0x1a3b1e978 0x1adc4e534 0x1a7c10f0c 0x104be36a0 0x1a399ef04)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by quetool** [comment] 2019-09-23 14:54
Here I am updating and closing this issue. I just found the solution for the statusbar related issue

-> https://pub.dev/packages/flutter_statusbarcolor#-changelog-tab-

![Captura de Pantalla 2019-09-23 a la(s) 11 47 32](https://user-images.githubusercontent.com/14978705/65436087-f5158680-ddf7-11e9-9eee-d75300c53e36.png)

Sorry for bother the community! With a non Flutter-related issue!

PD: Is it possible now Flutter is not logging anything at all in debug console? I am just not seeing any print() I have write o.O

**Comment by quetool** [comment] 2019-09-23 15:40
Sorry, I did not close this issue because I changed to stable again and I am getting this error

```
Launching lib/main.dart on iPhone Alfredo in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 37S53BMSN9
Xcode build done.                                           84,7s
2019-09-23 12:39:50.777 ios-deploy[43030:389751] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Could not install build/ios/iphoneos/Runner.app on 00008020-001A03CE1161002E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone Alfredo.
Exited (sigterm)
```

**Comment by christopherfujino** [comment] 2019-09-23 16:16
@quetool the "Device doesn't support wireless sync" error is this one https://github.com/flutter/flutter/issues/40448, which was fixed on dev. If you really want to use stable with iOS 13, you will have to wait for the next stable release, or you can cherry pick the fix into your local flutter (which is pretty easy). It just means changing the hash value in the file `flutter/bin/internal/ios-deploy.version`, then deleting the cache `rm -rf flutter/bin/cache` and then re-populating the cache with something like `flutter doctor`. Note, if you make this change locally, you will have to do a `git reset --hard` before upgrading.

**Comment by quetool** [comment] 2019-09-23 17:20
Oh! That's nice! I will wait for next stable release, dev channel is pretty good to me! Tanks @christopherfujino !

**Comment by christopherfujino** [comment] 2019-09-23 19:59
@quetool sounds good, I will close this now!

**Closed by christopherfujino** 2019-09-23 19:59 UTC
Labels: e: device-specific, ⌺‬ platform-ios

**Comment by quetool** [comment] 2019-10-01 17:42
I can confirm on 1.9.1+hotfix.4 • channel stable is all working fine so far...

**Comment by benbdevd** [comment] 2019-10-07 15:52
Not sure if relevant, but I also have an app that worked on iOS 12 and launched to black screen in iOS 13.

Disabling "UIApplicationSupportsMultipleScenes" seems to have fixed this.

**Comment by FineTillYouCameAlong** [comment] 2019-10-25 16:44
> UPDATE: So, I've solved the first issue listed and It turned out that is an issue from a particular plugin, so, dismiss that one.

Could you tell me which plugin was the issue and how did you solve it? I'm having the exact same crash

**Comment by quetool** [comment] 2019-10-25 19:22
@FineTillYouCameAlong Oh gosh! I don't remember anymore but plugins where I pushed a fix for iOS 13 are: `flutter_exif_rotation` https://github.com/NGhebreial/flutter_exif_rotation/pull/19#event-2732174691 and `flutter_radio` https://github.com/thyagoluciano/flutter_radio/pull/31#issuecomment-537663761 So it might be some of those
