### ISSUE TITLE
Can't wrap text on multiple lines

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#45193] opened 2019-11-19 21:20 UTC
Although I love Flutter for all it's simplicity and ease of use, there are some aspects of the Framework that drive me nuts some times, like something as simple as wrapping text over multiple lines.

I honestly don't know how hard it is to make `Text` to automatically wrap its contents over multiple lines, but this should be supported out-of-the-box, even if it means making a new widget, `WrappableText` in order to not break compatibility and etc.

here's my case, I have the following tree:

![image](https://user-images.githubusercontent.com/8120472/69186937-4e4c1e80-0af8-11ea-8560-5d1c2d3749a3.png)

The `Row` marked in yellow is overflowing if I place a long `string` under `Text`. I tried to wrap the `Text` inside a `Flexible` or an `Expanded`, but it didn't work (even though it works on the other Widget `AccountName`, which has as similar design, showing how tricky this is).

Even if there's a layout widget missing here, the Framework should be simpler and more robust  for text rendering, so I honestly think there's plenty of room here for improvement.

-----------

I made it work by wrapping the `Text` and its `Column` ancestor in a `Flexible`, but as I said before, the framework shouldn't need all that tinkering for something that simple.

**Comment by goderbauer** [comment] 2019-11-20 23:02
Can you provide some sample code that shows the issue? In theory, the text widget supports wrapping, see e.g. https://master-api.flutter.dev/flutter/widgets/Text/softWrap.html.

**Comment by feinstein** [comment] 2019-11-20 23:12
I think `softWrap` only works if the widget size can be easily calculated, but once you place a `Text` inside a `Row`, inside a `Column` and so on and so forth, the size of the widget can't be calculated anymore, so `Text` won't get the information that its `String` won't fit on the available size, since `Text` would be able to grow as much as it wants.

I think the hard thing about this problem is that `Text` can't know what's going on in order to react and make things right, as this is a problem with the layout of `Row` and `Column`.

**Comment by pedromassangocode** [comment] 2020-08-25 11:26
Hi @feinstein 
We need you to provide the code that reproduces the issue since we can't easily reproduce based on your explanation, also, please provide your `flutter doctor -v` and your `flutter run -v`.
Thank you.

**Comment by feinstein** [comment] 2020-08-25 12:56
Have you tried the last line I wrote on my last comment?

**Comment by pedromassangocode** [comment] 2020-08-25 13:17
Hi @feinstein 
Does the code bellow reproduce this issue?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Row(
                children: [
                  Text(
                    'Multi line text widget Multi line text widget Multi line text widget',
                    maxLines: 4,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by feinstein** [comment] 2020-08-25 19:09
Yes.

**Comment by feinstein** [comment] 2020-08-25 19:13
Just to be clear, this was opened in 2019, when docs and tools weren't as evolved as we have them now. Debugging this is a lot easier with the DevTools, but the point of this issue was to ask for a simpler way to have this all working.

Honestly after all this time in Flutter I don't even know if it's possible, so I will leave to the admins to decide if this should remain open or not.

**Comment by pedromassangocode** [comment] 2020-08-26 06:56
The code I shared https://github.com/flutter/flutter/issues/45193#issuecomment-680019251 shows a single line of text, not sure if it reproduces the actual issue. The text in the row will have its width unbounded and won't wrap due to this. At this point I can confirm that this issue is not reproducible on latest `master` channel.

![Screen Shot 2020-08-26 at 07 48 16](https://user-images.githubusercontent.com/67424416/91270433-83b12700-e770-11ea-9571-0a980f2b9782.png)

Since @feinstein confirmed that the code is supposed to reproduce the issue and it doesn’t, I feel safe to close this. If you disagree feel free to comment and I will reopen it.
Thank you

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.77, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.77 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision c8f3df7ea5 (5 hours ago), 2020-08-25 21:26:05 -0400
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by feinstein** [comment] 2020-08-26 19:25
@pedromassango please reopen this as the issue is still present, you probably just doesn't see it in your particular emulator.

Here's on mine:

![image](https://user-images.githubusercontent.com/8120472/91347105-293bb900-e7b8-11ea-8872-c82fc0eb1f4e.png)

And this is my Flutter doctor:

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale pt-BR)
    • Flutter version 1.20.2 at C:\Programming\Flutter\sdk\flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Michel\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Michel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment] 2020-08-27 06:38
I was able to reproduce this on latest `master` channel. 

![Screen Shot 2020-08-27 at 07 36 10](https://user-images.githubusercontent.com/67424416/91400687-fd601800-e837-11ea-9f01-7919caf79a21.png)

<details>
<summary> Logs</summary>

```

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 6.0 pixels on the right.

The relevant error-causing widget was: 
  Row file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:14:15
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#3b075 relayoutBoundary=up3 OVERFLOWING
...  parentData: offset=Offset(0.0, 439.5); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
...  size: Size(414.0, 17.0)
...  direction: horizontal
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  textDirection: ltr
...  verticalDirection: down
...  textBaseline: alphabetic
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.93, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.93 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision f35a8b7470 (2 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (4 available)            
    • iPhone 11 Pro Max (mobile) • B2A481C0-B2C1-495A-9ECA-0D3778F2FCD3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by exaby73** [comment] 2022-11-01 11:33
This issue can be solved by wrapping the `Text` in a `Flexible`. This is working as indented, and therefore I am closing this issue. Thank you.

**Closed by exaby73** 2022-11-01 11:33 UTC
Labels: framework, a: typography, has reproducible steps, found in release: 1.22
