### ISSUE TITLE
Terminate called after throwing instance of 'std::bad_cast' (arm64)

### ISSUE THREAD

**Issue by HoseinHaqiqian** [flutter/flutter#86283] opened 2021-07-12 09:29 UTC
I am using Pi4  and trying to run my flutter application by using `flutter run -d linux`.
My app will crash when i try to call a method channel function. 

**Error :** 

> terminate called after throwing instance of 'std::bad_cast'
> what(): std::bad_cast

**Comment by TahaTesser** [comment] 2021-07-13 07:57
HI @HoseinHaqiqian 
Arm Linux as a target is not yet supported https://github.com/flutter/flutter/issues/60678
Closing as duplicate of https://github.com/flutter/flutter/issues/60678

**Closed by TahaTesser** 2021-07-13 07:57 UTC
Labels: in triage

**Comment by HoseinHaqiqian** [comment] 2021-07-13 12:58
@TahaTesser I fixed my problem. It's working now on linux (arm64) .
Device : Raspberry Pi 4

**Comment by TahaTesser** [comment] 2021-07-13 13:00
@HoseinHaqiqian 
Can you please what you did?

**Comment by HoseinHaqiqian** [comment] 2021-07-13 17:45
@TahaTesser  I can't guess what exactly happend (maybe because of gcc version) but the error fixed after i removed all "cout" commands.
