### ISSUE TITLE
Make Clip widgets do nothing when they rececive Clip.none

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#98483] opened 2022-02-15 09:22 UTC
Currently Clip widgets throw when they receive Clip.none.
This creates problems such as verbose code when doing conditional rendering, losing state, and as a side-effect of this - a need for documentation for how to preseve the state everywhere where there is a `clipBehavior`.

We should consider instead making them to just draw nothing.

Filed from https://github.com/flutter/flutter/pull/98252#discussion_r805079840

**Comment by TahaTesser** [comment] 2022-02-15 09:47
I was just trying this out and turns out https://github.com/flutter/flutter/pull/95593 made it possible. 
Somehow my [reference](https://github.com/flutter/flutter/pull/98252#discussion_r805335884) was from an older commit. my bad. 

I am doing some testing to be sure, will let you know.

**Comment by TahaTesser** [comment] 2022-02-15 09:53
@nt4f04uNd 
Yep, I can confirm, it works fine with `clip.none` and no assertion is thrown. This also means we don't need to add docs for  preserving state.
I feel safe to close this

**Closed by TahaTesser** 2022-02-15 09:53 UTC
Labels: framework, a: quality, proposal

**Comment by nt4f04uNd** [comment] 2022-02-15 09:59
Nice, thanks for checking it out
