### ISSUE TITLE
The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by Cristhianveal** [flutter/flutter#55072] opened 2020-04-17 22:41 UTC
Hello friends!
I am developing an App, when compiling everything is fine. but I have been curious to take the APK to the playStore but for this I execute the command `flutter build apk --release` everything is fine but in the end it gives me some warnings and an error.
```
[  +23 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve

The plugin cloud_firestore could not be built due to the issue above.
```

I have been investigating, solutions say about the builder version, Activate androidX, I have done everything, have the muslims versions of the plugins, etc.

I share part of the code:

pubspec.yaml (https://carbon.now.sh/U92LFqlIzeEeX9FK7A7w)

build.gradle/Android (https://carbon.now.sh/Qpy4ELgIP3OdYgJctxVM)

build.gradle /Android/app (https://carbon.now.sh/6ezjG4tUtpKLaQHs0gdu)

Terminal Testing:

exit the terminal : `flutte run -v `( ) I have these warnings but still compile.
```
[  +46 ms] Note:
E:\Flutter\.pub-cache\hosted\pub.dartlang.org\flutter_twitter_login-1.1.0\android\src\main\java\com\roughike\fluttertwitterlogin\fluttertwitterlogin\TwitterLoginPlugin.java uses or overrides a deprecated API.
[  +86 ms] Note: Recompile with -Xlint:deprecation for details.

----------------
[  +65 ms] Note:
E:\Flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
[  +79 ms] Note: Recompile with -Xlint:unchecked for details.
[ +574 ms] > Task :google_maps_flutter:compileDebugJavaWithJavac
[  +36 ms] > Task :google_sign_in:generateDebugBuildConfig
[ +134 ms] Note: Some input files use unchecked or unsafe operations.
[  +63 ms] Note: Recompile with -Xlint:unchecked for details.
```

exit the terminal when applying flu `Flutter Build apk --release -v ` error:

```[ +116 ms] FAILURE: Build failed with an exception.
[  +15 ms] * What went wrong:
[   +3 ms] Execution failed for task ':flutter_twitter_login:verifyReleaseResources'.
[   +1 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +3 ms]    > 1 exception was raised by workers:
[   +2 ms]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[   +9 ms]      C:\Users\Cristhian VeAl\.gradle\caches\transforms-2\files-2.1\008d1469a31b18ebdf10df5189adf04f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
[   +4 ms]      C:\Users\Cristhian VeAl\.gradle\caches\transforms-2\files-2.1\008d1469a31b18ebdf10df5189adf04f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource
android:attr/ttcIndex not found.
[   +6 ms] * Try:
[   +4 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[  +14 ms] * Get more help at https://help.gradle.org
[   +4 ms] BUILD FAILED in 2m 4s
[  +22 ms] 559 actionable tasks: 18 executed, 541 up-to-date
[+1185 ms] Running Gradle task 'assembleRelease'... (completed in 126,2s, longer than expected)
[  +15 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[  +15 ms] Building plugin cloud_firestore...
[  +43 ms] Running Gradle task 'assembleAarRelease'...
[  +15 ms] "flutter apk" took 128.837ms.
The plugin cloud_firestore could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:781:7)
#2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:87:64)
#3      _rootRunBinary (dart:async/zone.dart:1204:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#8      Future._completeError (dart:async/future_impl.dart:534:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

I hope I can have a solution :(

I don't know if it's because of the cloud_firestore version, I've changed it to 7.0.7 and the same. 

capturin the compilation `flutter build apk --release` : 
[![Image from Gyazo](https://i.gyazo.com/6745e9a8d1a2596059f214cb7c1a6457.gif)](https://gyazo.com/6745e9a8d1a2596059f214cb7c1a6457)

result compiltaion: 
[![Image from Gyazo](https://i.gyazo.com/c71163e1fef14774698837adff26c033.png)](https://gyazo.com/c71163e1fef14774698837adff26c033)

Cheers.

**Comment by iapicca** [comment] 2020-04-20 09:10
Hi @Cristhianveal 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-20 09:10 UTC
