### ISSUE TITLE
Array uniforms wont work on Flutter web 

### ISSUE THREAD

**Issue by renancaraujo** [flutter/flutter#141296] opened 2024-01-10 19:03 UTC
### Steps to reproduce

1. Create a Flutter project from scratch or use the [simple shader sample](https://github.com/flutter/samples/tree/main/simple_shader).
1. Add a fragment shader file and use array uniforms
1. Try to run it on the web (`flutter run -d chrome`)

### Expected results

It whould run the project normally.

### Actual results

It fails as with an error message similar to:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following IndexError was thrown during paint():
RangeError (index): Index out of range: index should be less than 3: 3

The relevant error-causing widget was:
  CustomPaint CustomPaint: [...]/lib/main.dart:34:37

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 610:7                 _set]
lib/_engine/engine/canvaskit/painting.dart 368:5                                  setFloat
packages/flutter_shaders/src/set_uniforms.dart 62:5                               setFloat
packages/flutter_shaders/src/set_uniforms.dart 67:7                               setFloats
...
```

### Code sample

Full example here:
https://github.com/renancaraujo/array_uniforms_issue

Code sample:
<details open><summary>Code sample</summary>

```dart
// dart code
import 'dart:ui' as ui;

import 'package:flutter_shaders/flutter_shaders.dart';

// ...

  void paint(Canvas canvas, Size size) {
    shader.setFloatUniforms((value) {
      value.setSize(size);
      value.setFloats([
        0.1,
        0.2,
        0.3,
        0.4,
        0.5,
        0.6,
        0.7,
        0.8,
        0.9,
        1.0,
      ]);
    });

    final paint = Paint()..shader = shader;
    canvas.drawRect(
      Rect.fromLTWH(0, 0, size.width, size.height),
      paint,
    );
  }

```

```glsl
// shader code

#include <flutter/runtime_effect.glsl>

uniform vec2 uSize;
uniform float[10] uFloats; // array uniform

out vec4 fragColor;

void main() { 
    vec2 pos = FlutterFragCoord().xy;
    vec2 uv = pos / uSize;


// ...
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following IndexError was thrown during paint():
RangeError (index): Index out of range: index should be less than 3: 3

The relevant error-causing widget was:
  CustomPaint CustomPaint: [...]/lib/main.dart:34:37

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 610:7                 _set]
lib/_engine/engine/canvaskit/painting.dart 368:5                                  setFloat
packages/flutter_shaders/src/set_uniforms.dart 62:5                               setFloat
packages/flutter_shaders/src/set_uniforms.dart 67:7                               setFloats
...
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by renancaraujo** [comment] 2024-01-10 19:06
Extra info:

The code runs normally on  ios, android, macos, windows and linux on both skia and impelller. The issue only happens on the web.

Bug reproducible on master.

**Comment by huycozy** [comment] 2024-01-11 08:35
This looks similar to https://github.com/flutter/flutter/issues/128774 and it's marked as a duplicate of https://github.com/flutter/flutter/issues/116900. But this is only reproduced on web, I will keep this open to have other's thoughts. Thanks for the report.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.6, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (28 hours ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.19.0-3.0.pre.49, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.0-3.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 085aaa5d63 (55 minutes ago), 2024-01-10 21:13:27 -0500
    • Engine revision 42e3e02361
    • Dart version 3.4.0 (build 3.4.0-15.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by renancaraujo** [comment] 2024-01-12 11:56
Hello mr @jonahwilliams, i tried to fix this on https://github.com/flutter/engine/pull/49754 where i suspect the source of the problem is. LMK if thats right

**Closed** 2024-02-28 14:35 UTC
Labels: engine, platform-web, has reproducible steps, P2, team-web, triaged-web, found in release: 3.16, found in release: 3.19
