### ISSUE TITLE
Feature Request: Allow pushing a tree of pages

### ISSUE THREAD

**Issue by KathLevi** [flutter/flutter#24834] opened 2018-11-29 00:00 UTC
I am working on an app with messaging capability. When the app has been force closed or is running in the background the user receives a push notification. Clicking on the notification opens the app and ideally brings them to the thread of the message they just received. However, currently I am pushing three separate pages onto the stack and therefore one of the pages is shown for a split second before loading the thread. It would be ideal to be able to **push a tree of pages** onto the stack so that only the last page loads and is shown to the user rather than briefly showing all three.

**Comment by zoechi** [comment] 2019-02-21 15:21
Is this a duplicate of #11607 ?

**Comment by KathLevi** [comment] 2019-02-23 23:04
Yes, I believe it is.

**Comment by zoechi** [comment] 2019-02-24 00:01
Duplicate of #11607

**Closed by zoechi** 2019-02-24 00:01 UTC
Labels: f: routes, framework, severe: new feature
