### ISSUE TITLE
 Cannot touch  before loading image success （Just on ios）

### ISSUE THREAD

**Issue by Gaoxichao** [flutter/flutter#65909] opened 2020-09-16 04:03 UTC
## Steps to Reproduce

Before the image is successfully loaded, it cannot be clicked (such as sliding, clicking)，its only ios ，android is well，

this is code：

```
Image.network('https://img.warting.com/uploads/2017/1120/54-1G1201Z3300-L.jpg')

```
put is your project test 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Applications/flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (2 available)
    • ONEPLUS A6010 • 9469697b                             • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro • 360FE8C0-31CD-4771-8AE7-717E19CC64B8 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-09-16 08:34
Hi @Gaoxichao 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

I suggest you to upgrade to the latest stable version of Flutter since this issue may already be fixed.

Thank you

**Comment by Gaoxichao** [comment] 2020-09-16 09:11
@pedromassangocode 

**flutter doctor -v :**

```
macdeiMac:~ mac$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Applications/flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (2 available)
    • ONEPLUS A6010 • 9469697b                             • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro • 360FE8C0-31CD-4771-8AE7-717E19CC64B8 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**my code :**

```
import 'package:flutter/material.dart';

class IosImageTest extends StatefulWidget {
  @override
  _IosImageTestState createState() => _IosImageTestState();
}

class _IosImageTestState extends State<IosImageTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
            icon: Icon(Icons.arrow_back_ios),
            onPressed: () {
              // Cannot touch before loading image success
              Navigator.of(context).pop();
            }),
      ),
      body: Image.network('https://img.warting.com/uploads/2017/1120/54-1G1201Z3300-L.jpg'),
    );
  }
}

```

**It seems to be a picture problem, because you can change the picture, but why does the picture affect the application (frame)?**

**Comment by pedromassangocode** [comment] 2020-09-16 14:58
Hi @Gaoxichao 
Can you please provide clear steps to reproduce the issue? In the code you provided there is no click listener for the image but you are saying that the issue is about image click.
Thank you

**Comment by Gaoxichao** [comment] 2020-09-21 03:35
no steps , just click back button on loading image first, but second is well (because had image temp)

ps: only  ios devices.

**Comment by pedromassangocode** [comment] 2020-09-21 07:08
Hi @Gaoxichao 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose`.
Thank you

**Comment by TahaTesser** [comment] 2020-10-14 13:10
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 13:10 UTC
Labels: in triage
