### ISSUE TITLE
Problem with the back button in Android devices

### ISSUE THREAD

**Issue by kostricanitechnology** [flutter/flutter#141564] opened 2024-01-15 10:54 UTC
I am using the Local Authenticator plugin. It requires to use in MainActivity.kt the code below
`import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
    // ...
}`

but when I use this code the Back arrow button in Android Devices doesn't work, it closes the app instead of going back.

When I use in MainActivity.kt the code below 

`import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}`

the back button works now but the Authenticator doesn't work anymore.

Thanks

**Comment by dam-ease** [comment] 2024-01-15 14:08
Thanks for filing this @kostricanitechnology.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code or a sample repo we can run to reproduce this?
Also, kindly provide output of your `flutter doctor -v`.
Thank you

**Comment by kostricanitechnology** [comment] 2024-01-15 14:44
[loalauthenticator-backbutton-works.zip](https://github.com/flutter/flutter/files/13939969/loalauthenticator-backbutton-works.zip)
Hello, Thanks for your fast response.

I have created a simple project for the authenticator. the zip in the attachment is the case when the back button works after you go to "Test Page" and go back with "Back Button" on Android device (tried with Galaxy S21), but the Authenticator doesn't work.

Now, if you change the MainActivity.kt file of that project and add the new one below, the authenticator will work but the back button will not work anymore because the back button works only with "FlutterActivity".

`import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
  
}`

**Comment by dam-ease** [comment] 2024-01-16 07:25
Thanks for your response @kostricanitechnology.
From your comments, I see this seems to be an issue/related to predictive back not being supported for FlutterFragment yet which is being tracked in https://github.com/flutter/flutter/issues/109558. 

Per, this https://github.com/flutter/flutter/issues/109558#issuecomment-1683099477 and https://github.com/flutter/flutter/issues/109558#issuecomment-1684536696, it's known and currently in the works https://github.com/flutter/engine/pull/44865.
Kindly follow up, comment and upvote the issue.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/109558, if you disagree, please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2024-01-16 07:25 UTC
Labels: in triage
