### ISSUE TITLE
Pass engine switches arguments/dart VM flags to the engine in desktop

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#60393] opened 2020-06-26 22:30 UTC
On Android and iOS, this is possible for at least some flags - see e.g. https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L49 for iOS. On Android, this uses intents.

It would probably fine to have this only work in debug builds.

@stuartmorgan

**Comment by stuartmorgan** [comment] 2020-06-27 02:06
> It would probably fine to have this only work in debug builds.

I think that's probably what we'll have to do; I was thinking about this some today, and I can't think of a good hook point that's available to developers at runtime but not to end users of distributed apps, unless we gate it on debug. E.g., on iOS it's relatively easy for developers to pass command line arguments but basically impossible for end users, but the same isn't true on desktop.

To avoid conflicting with https://github.com/flutter/flutter/issues/32986, I was thinking maybe we should use environment variables. (Another option would be an argument wrapping the arguments, but since that already exists at the engine flag level to pass things to the dart VM, it would get really absurd).

**Comment by terrylucas** [comment] 2020-07-09 13:17
DevTools passes the argument `--enable-dart-profiling` to the engine using our own [main.cc](https://github.com/flutter/devtools/blob/master/packages/devtools_app/linux/main.cc).

The argument is passed [@ line 58 in main.cc](https://github.com/flutter/devtools/blob/master/packages/devtools_app/linux/main.cc#L58).

Is there a way to do this in the current Linux Desktop similar to how this was done with the older style main.cc?

@bkonyi is the flag `--enable-dart-profiling` still required?  If this is required, then this is a blocker for DevTools running in Linux Desktop (we develop using desktop).

**Comment by stuartmorgan** [comment] 2020-07-09 15:33
> Is there a way to do this in the current Linux Desktop similar to how this was done with the older style main.cc?

No, by design. That API is deprecated on all platforms, so was not carried forward to the new Linux embedding.

Do you actually want profiling on in every build, or just for local development? If the latter, this issue is about enabling that. If the former, we need to have longer conversation.

**Comment by terrylucas** [comment] 2020-07-09 20:46
We don't want profiling on a permanent basis just when we need to profile DevTools (a flag to flip on is fine we don't need an arbitrary argument).  I think someone added the argument then never removed it and it was checked in.

**Comment by kenzieschmoll** [comment] 2020-07-10 14:44
It was intentionally checked in to DevTools. But flipping a flag for when we need sounds reasonable if having it on all the time is having a negative affect.

**Comment by bkonyi** [comment] 2020-07-10 17:13
I don't think this was accidentally checked in as it was submitted when the Linux embedder only had debug mode support. However, the right solution is to match the profiler behavior of Flutter mobile applications.

**Comment by stuartmorgan** [comment] 2020-07-10 23:09
> the right solution is to match the profiler behavior

Meaning the Profile build configuration? That should already be the case.

**Comment by bkonyi** [comment] 2020-07-13 16:07
Yes, and whatever it is in debug mode as well. I can't remember whether or not the profiler is enabled by default there.

**Comment by stuartmorgan** [comment] 2020-07-13 17:06
The default behaviors of Debug and Profile should match mobile; if you find that's not the case please file an issue.

**Comment by stuartmorgan** [comment] 2020-09-22 19:45
Windows now (as of the next engine roll) allows passing arguments via environment variable in debug and profile mode, by setting:
* `FLUTTER_ENGINE_SWITCHES` to the number of switches
* `FLUTTER_ENGINE_SWITCH_<N>` (indexing from 1) to the individual switches. The `--` that would be used to pass them as a flag should **not** be included.

So for instance:
```
FLUTTER_ENGINE_SWITCHES=1
FLUTTER_ENGINE_SWITCH_1=observatory-port=12345
```
would set the observatory port.

I plan to add this to macOS and Linux as well. Feedback welcome on how this works out for people in practice.

(I didn't use a single `FLUTTER_ENGINE_SWITCHES=<list of switches>` format because getting separators, quoting, etc. on that correct, especially for passing dart switches which itself a nested list of switches, would be very tricky for people using it; the tradeoff is that it's less ergonomic in the simple case. Hopefully this is rare enough that that's not a significant issue.)

One thing that may not be obvious that's worth noting is that the count given in FLUTTER_ENGINE_SWITCHES is definitive; it won't look for `FLUTTER_ENGINE_SWITCH_<N>` flags past that value. That means it's possible to have a set of flags defined in the environment and turn them on and off just by changing `FLUTTER_ENGINE_SWITCHES`

**Closed** 2020-10-06 18:17 UTC
Labels: P5, a: desktop, engine, severe: new feature
