### ISSUE TITLE
Gap between widgets in Column widget

### ISSUE THREAD

**Issue by gxanshu** [flutter/flutter#138208] opened 2023-11-10 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm from web development background and in CSS we have `gap` property in flex boxes which allow developers to maintain gap with just single line.

```css
.container {
 display: flex;
 flex-direction: column;
 gap: 12px;
}
```

i'm trying to develop a mobile app with Flutter (btw really really amazing framework) and i already searched over internet there's like `gap` feature in Flutter.

### Proposal

i know that we can do that with spaceBox widget and with some other tricks but it will be a good to have a gap feature in Flutter itself.

Thank you.

**Comment by Jackjack47** [comment] 2023-11-10 09:21
may be you can use Container.margin to do this.

**Comment by Jackjack47** [comment] 2023-11-10 09:28
may be GridView.count can do this.

**Comment by gxanshu** [comment] 2023-11-10 10:04
> may be GridView.count can do this.

yup right! i'm just talking about normal `Column` widget.

**Comment by dam-ease** [comment] 2023-11-10 10:57
Thanks for proposing this. This spacing can be achieved with `SizedBox` or if you'll like to add equal spacings between widgets, you could use `ListView.Separated` or `GridView.count` or are there any other features this `gap` should have that can't be achieved with the suggested widgets, you could provide more information on this.
Thank you!

**Comment by gxanshu** [comment] 2023-11-11 03:57
> Thanks for proposing this. This spacing can be achieved with `SizedBox` or if you'll like to add equal spacings between widgets, you could use `ListView.Separated` or `GridView.count` or are there any other features this `gap` should have that can't be achieved with the suggested widgets, you could provide more information on this.
> Thank you!

Thanks for these really helpful suggestions. As i explained in my proposal I know that we can have gaps with `spaceBox`, `ListView.Separated`, `GirdView.count` etc.

But my real proposal is that whatever widget constructor takes List of widget as its child like `Column`, `Row` etc if they have a gap property to maintain equal gap then this would be really helpful.

Just one simple line of code to add gap in column and row widgets.

Most importantly it's just my personal view if anyone have better approach that provide more simplicity then please let me know.

Thank you!

**Comment by Piinks** [comment] 2023-11-15 20:02
This is a duplicate of https://github.com/flutter/flutter/issues/16957, which was closed since we do not intend to add support for this.

> which allow developers to maintain gap with just single line.

This can be done in Flutter similarly by just adding a line of code that inserts SizedBoxes on the desired spacing in between children.

This comment form Hixie on the original issue provides a bit more context:

> I think this is a reasonable thing to want to add to Row. The problem is, so are a hundred other similar things. Since it is very easy to add this feature (just two lines of code!) without actually modifying Row itself, it makes more sense to me to have a package that introduces a widget that does that work ("SpacerRow" or something).


There is a related issue you may want to follow, the Spacer widget is used for layouts like this. I filed a bug last week to see if we can add a Spacer.fixed: https://github.com/flutter/flutter/issues/138257

**Closed by Piinks** 2023-11-15 20:02 UTC
Labels: c: new feature, f: material design, c: proposal, team-design
