### ISSUE TITLE
Android: Cannot draw the bottom of fullScreen

### ISSUE THREAD

**Issue by naka-ok** [flutter/flutter#47683] opened 2019-12-23 16:51 UTC
## Steps to Reproduce

I cannot draw the bottom of fullScreen after upgrading Flutter.
"constraints.maxHeight" of body in Scaffold is different between 1.9.1 and 1.12.13.
Is there a way around the problem?

This be similar to the following issue - https://github.com/flutter/flutter/issues/46486

- Sample code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaff(),
    );
  }
}

class Scaff extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        print("scaff: maxWidth=${constraints.maxWidth}, maxHeight=${constraints.maxHeight}");
        return Scaffold(
          backgroundColor: Colors.amberAccent,
          body: Body(),
          floatingActionButton: FloatingActionButton(
            onPressed: null,
            child: Icon(Icons.add),
          ),
        );
      }
    );
  }
}

class Body extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return new LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        print("body: maxWidth=${constraints.maxWidth}, maxHeight=${constraints.maxHeight}");
        return Align(
          alignment: Alignment.bottomCenter,
          child: Text("Bottom Here.", style: TextStyle(fontSize: 24)),
        );
      }
    );
  }
}
```

**Target Platform: Android
**Target OS version/browser: Android 9.0 (SDK 28)
**Devices: Xperia XZ Premium

## Logs (on Android)

- Output at v1.12.13+hotfix.5
```
scaff: maxWidth=360.0, maxHeight=592.0
body: maxWidth=360.0, maxHeight=592.0
scaff: maxWidth=360.0, maxHeight=640.0
body: maxWidth=360.0, maxHeight=592.0
```
![v7](https://user-images.githubusercontent.com/12571835/71369843-531c5a80-25ef-11ea-8a6f-1db8625f7d79.png)

- Output at v1.9.1+hotfix.6
```
scaff: maxWidth=360.0, maxHeight=592.0
body: maxWidth=360.0, maxHeight=592.0
scaff: maxWidth=360.0, maxHeight=640.0
body: maxWidth=360.0, maxHeight=640.0
```
![v10](https://user-images.githubusercontent.com/12571835/71369766-1c464480-25ef-11ea-82fa-5dd6fc63fe9a.png)

- doctor
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale ja-JP)
    • Flutter version 1.12.13+hotfix.5 at E:\Tools\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Tools\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Tools\Android\android-sdk
    • Java binary at: C:\Tools\JetBrains\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Tools\JetBrains\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)                                                                                   
    • SO 04J • CB512ED97T • android-arm64 • Android 8.0.0 (API 26)                                                   
```
Thanks

**Comment by shihaohong** [comment] 2019-12-23 18:46
Hi! Do you happen to know if this is reproducible across iOS and Android?

**Comment by naka-ok** [comment] 2019-12-24 06:59
Thank you for reply.
There seems to be no abnormality on iOS.
The result was rendered full screen as expected in both versions.

On Android fullscrren mode, "System navigation bar" is hidden,
But new Flutter does not extend height of Scaffold boby.

## Logs

- Output at v1.12.13+hotfix.5
```
scaff: maxWidth=375.0, maxHeight=812.0
body: maxWidth=375.0, maxHeight=812.0
scaff: maxWidth=375.0, maxHeight=812.0
body: maxWidth=375.0, maxHeight=812.0
```
![iOS_both](https://user-images.githubusercontent.com/12571835/71399134-0de73f80-2666-11ea-8e55-49639168f9bb.png)

- Output at v1.9.1+hotfix.6
```
scaff: maxWidth=375.0, maxHeight=812.0
body: maxWidth=375.0, maxHeight=812.0
scaff: maxWidth=375.0, maxHeight=812.0
body: maxWidth=375.0, maxHeight=812.0
```
![iOS_both](https://user-images.githubusercontent.com/12571835/71399151-1ccdf200-2666-11ea-9003-a435226eb2ec.png)

- doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale ja-JP)
    • Flutter version 1.12.13+hotfix.5 at /Applications/Tools/flutter
    • Framework revision 27321ebbad (13 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Applications/Tools/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] Connected device (1 available)
    • iPhone X • 06489E4D-261D-4A36-A6CE-243486AFD3B0 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
```
Thanks

**Comment by lazarvgd** [comment] 2019-12-25 13:11
I am facing the same problem.

**Comment by crypt0ende** [comment] 2020-01-22 17:43
Android: **System Bottom Bar is hidden, but space is still taken, System UI remains**
_FullScreen by SystemChrome.setEnabledSystemUIOverlays([]);_

Before AndroidX migration bug was fixed. But now it came up again

**Comment by FranciscoNC** [comment] 2020-02-04 23:42
I found [this](https://stackoverflow.com/a/53744371/10903105), It works

**Comment by crypt0ende** [comment] 2020-02-06 09:21
Yes, but now keyboard overflow text fields. 

This Bug appeared after the recent update. 
Also, If I minimize an app and open it again, reserved bottom space disappears

**Comment by Piinks** [comment] 2020-03-04 23:22
First glance, may be related to https://github.com/flutter/flutter/pull/41803
I can look into this this week.

**Comment by Piinks** [comment] 2020-03-05 18:28
> First glance, may be related to #41803

Negate that, I was able to bisect this regression to #44369
@blasten do you know why that change would have caused this?

Above this also mentions another issue that may be related, #46486, I'll update there as well.

**Comment by jmagman** [comment] 2020-03-05 23:42
@Piinks do you suspect this is a tool issue?

**Comment by jmagman** [comment] 2020-03-06 00:06
Gotcha.  I think that was just turned on the new Android embedding, so this is probably caused by that, not particularly the tool flag change.  Will let the engine team take over, thanks!

**Comment by blasten** [comment] 2020-03-06 00:26
@matthew-carroll maybe the embedding is missing flag in the native call to the engine?

**Comment by matthew-carroll** [comment] 2020-03-06 04:28
I can take a look early next week if Jason doesn't find the issue by then. Please CC me on a PR if anyone solves the issue. Thanks.

**Comment by liujiakuoyx** [comment] 2020-04-01 08:57
I think this is the same issue as the one I've reported: #52472

**Comment by MichaelOttink** [comment] 2020-04-01 11:01
I am facing the same problem https://stackoverflow.com/questions/60815814/why-do-my-containers-size-bigger-than-the-screen-size-that-causes-the-singlechil/60968798#60968798

**Comment by liujiakuoyx** [comment] 2020-05-06 07:40
I found a way to work
```
bool canResizeToAvoidBottomInset(BuildContext context) {
  if (context == null) return false;
  var viewInsets = MediaQuery.of(context).viewInsets;
  var insetsBottom = viewInsets.bottom;
  var screenHeight = MediaQuery.of(context).size.height;
  return (screenHeight * 0.18) < insetsBottom;
}

return Scaffold(
     resizeToAvoidBottomInset: canResizeToAvoidBottomInset(context),
     .......
);
```

**Comment by xster** [comment] 2020-05-12 20:49
Summarizing: sounds like the v2 FlutterView is reading different window inset behaviors than v1 in transfering the mediaquery bottom inset values.

**Comment by kf6gpe** [comment] 2020-06-12 18:43
Downgrading to P1, as this isn't roll-blocking or build breaking.

**Comment by chinmaygarde** [comment] 2020-06-15 17:43
This is on Jason's TODO list this week.

**Comment by jason-simmons** [comment] 2020-06-17 00:29
This was fixed by https://github.com/flutter/engine/commit/e9f1efa2804232202b714609945397074fabff90

**Closed by jason-simmons** 2020-06-17 00:29 UTC
Labels: P3, engine, platform-android, severe: regression

**Comment by hhstore** [comment] 2021-06-10 08:36
- fix for `flutter 2.x`
- https://stackoverflow.com/a/67917177/16184406
