### ISSUE TITLE
google_maps_flutter_web has prefer_const_literals_to_create_immutables info warnings

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#104453] opened 2022-05-23 21:46 UTC
On engine roll https://github.com/flutter/flutter/pull/104431 new plugin warnings, `Linux flutter_plugins` is failing, tree is closed 
```
Analyzing google_maps_flutter_web...

   info - example/integration_test/google_maps_controller_test.dart:148:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:149:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:162:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:163:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:176:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:177:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:190:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:191:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:236:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:237:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:246:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:247:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:256:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:257:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:266:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:267:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8813346359515629377/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

**Comment by christopherfujino** [comment] 2022-05-23 21:50
This passed on presubmit on https://github.com/flutter/flutter/pull/104431, does this test use pinned plugins or pull from HEAD?

**Comment by christopherfujino** [comment] 2022-05-23 21:51
looks like this is the fix? https://github.com/flutter/plugins/commit/99aa799ea07ac717e9fc3205b22c7cb00cb528f3

**Comment by jmagman** [comment] 2022-05-23 21:55
@bparrishMines plugins sheriff, I don't see an open plugins->flutter roll PR to pick up https://github.com/flutter/plugins/pull/5793, is the roller off?

**Comment by jmagman** [comment] 2022-05-23 21:56
> does this test use pinned plugins or pull from HEAD?

I thought used pinned, but you're right, why did it pass in presubmit?

**Comment by christopherfujino** [comment] 2022-05-23 21:56
> @bparrishMines plugins sheriff, I don't see an open plugins->flutter roll PR to pick up [flutter/plugins#5793](https://github.com/flutter/plugins/pull/5793), is the roller off?

It says "waiting for roll window until 5/24/2022, 8:00:00 AM (Pacific Daylight Time)"? https://autoroll.skia.org/r/flutter-plugins-flutter-autoroll

**Comment by jmagman** [comment] 2022-05-23 21:59
> > does this test use pinned plugins or pull from HEAD?
> 
> I thought used pinned, but you're right, why did it pass in presubmit?

It does use pinned...
```
▌18:19:33▐ RUNNING: cd ../../t/flutter_plugins.SRYTXO; ../../w/flutter/git -c core.longPaths=true checkout f4ca73237db83f6ce207269d3000f58ad5b39000
```
https://github.com/flutter/flutter/blob/0015ed2b754109f37ab811673de2050f559c7c3e/dev/bots/test.dart#L1275-L1284

**Comment by jmagman** [comment] 2022-05-23 22:01
Reopened https://github.com/flutter/flutter/pull/104430

**Comment by jmagman** [comment] 2022-05-23 22:07
@stuartmorgan it's worth investigating why analysis passed in presubmit on top of the dart change https://github.com/flutter/flutter/pull/104431

**Comment by bparrishMines** [comment] 2022-05-23 22:07
> @bparrishMines plugins sheriff, I don't see an open plugins->flutter roll PR to pick up [flutter/plugins#5793](https://github.com/flutter/plugins/pull/5793), is the roller off?

Sorry it said that is was running, but it looks like the last 3 failed

**Comment by jmagman** [comment] 2022-05-23 22:24
Hm, just rolling the plugins sha didn't work. https://github.com/flutter/flutter/pull/104430

I don't think https://github.com/flutter/plugins/pull/5793 edited `google_maps_controller_test` or `google_maps_plugin_test`.  @ditman can you take a look?

**Comment by jmagman** [comment] 2022-05-23 22:31
PR at https://github.com/flutter/plugins/pull/5811.

**Comment by ditman** [comment] 2022-05-23 22:31
@jmagman can do. This is the place where I synced `google_maps_flutter_web` with the latest analysis coming from the framework, though:

https://github.com/flutter/plugins/pull/5791

**Comment by jmagman** [comment] 2022-05-23 22:33
> @jmagman can do. This is the place where I synced `google_maps_flutter_web` with the latest analysis coming from the framework, though:
>
> https://github.com/flutter/plugins/pull/5791

The `prefer_const_literals_to_create_immutables` is newer than that, in https://github.com/flutter/flutter/pull/104431

**Comment by ditman** [comment] 2022-05-23 22:39
The timing of this breakage has been somewhat unfortunate. As far as I can see, this "only" started breaking in the flutter -> plugins roll about 4h ago: https://github.com/flutter/plugins/pull/5809

Not sure how the new lint landed without breaking the flutter/flutter plugins test (?)

**Comment by ditman** [comment] 2022-05-23 22:54
Ah, I understand the problem now. The affected types were marked as immutable by this change which landed right before the plugins roll I linked above:

* https://github.com/flutter/plugins/commit/99aa799ea07ac717e9fc3205b22c7cb00cb528f3

The problem is that we couldn't see the breakage until the PR above got published on pub.dev, and then other packages (google_maps_flutter_web) started picking it up.

Anything that landed *after* the commit above in flutter/plugins was published would have triggered the error, we just didn't see anything.

Testing-wise, I think the issue has to do with us not running the dependent packages of a change while in PR, and pulling stuff from pub.dev when the change lands in `master`, but I'm sure @stuartmorgan has a more satisfactory description (and an issue about this problem, that we haven't had the time to tackle yet!)

Apologies for the breakage, this hits a small blind spot in plugins' CI.

**Comment by jmagman** [comment] 2022-05-23 23:02
Manual plugins roll https://github.com/flutter/flutter/pull/104430 merged, let's see if passes in post-submit...

**Closed** 2022-05-23 23:01 UTC
Labels: P0

**Comment by jmagman** [comment] 2022-05-24 00:28
> let's see if passes in post-submit...

(it did!)
