### ISSUE TITLE
> ![image](https://user-images.githubusercontent.com/46312580/103151635-c46e8a80-47ba-11eb-8ab0-286a6b470b0b.png)

### ISSUE THREAD

**Issue by mooduoye** [flutter/flutter#79564] opened 2021-04-01 16:32 UTC
> ![image](https://user-images.githubusercontent.com/46312580/103151635-c46e8a80-47ba-11eb-8ab0-286a6b470b0b.png)
> It's just been looked like this for several minutes.No other log files found in file system.Older version works. @VladyslavBondarenko
> Could you plz reopen this issue?

newly installed

_Originally posted by @CoderTyn in https://github.com/flutter/flutter/issues/61719#issuecomment-751352718_

**Comment by mooduoye** [comment] 2021-04-01 16:33
flutter 2.0.3 upgrade issue
<img width="181" alt="flutter_log" src="https://user-images.githubusercontent.com/76732862/113325374-3ef5fb80-9310-11eb-899c-0a51c837aeeb.PNG">

**Comment by iapicca** [comment] 2021-04-01 16:55
self duplicate of https://github.com/flutter/flutter/issues/79563

**Comment by TahaTesser** [comment] 2021-04-05 09:06
Closing as duplicate of https://github.com/flutter/flutter/issues/79563

**Closed by TahaTesser** 2021-04-05 09:06 UTC
Labels: in triage
