### ISSUE TITLE
[Impeller] Changes to use depth based clipping have regressed GPU frame times.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#145274] opened 2024-03-16 20:01 UTC
Canonical benchmark is probably complex layout: https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_gpu_frame_time%26sub_result%3D99th_percentile_gpu_frame_time%26sub_result%3Daverage_gpu_frame_time%26test%3Dcomplex_layout_scroll_perf_impeller__timeline_summary&selected=commit%3D39677%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_gpu_frame_time%252Ctest%253Dcomplex_layout_scroll_perf_impeller__timeline_summary%252C

AFAIK this application has few or no non-convex shapes. average GPU frame time regressed about 1.5ms

The new gallery is a similar story, the main page which used to have GPU times around ~2-3ms is now taking ~7-8ms. This is pushing us closer to frame budget on the Pixel 7s.

### Before

![image](https://github.com/flutter/flutter/assets/8975114/e1175057-14c0-4740-88e8-1d5fdc362e4a)

### After

![image](https://github.com/flutter/flutter/assets/8975114/ae4ef8b0-6f34-44e8-a8c7-75d7c17950de)

I don't think this is actually related to the StC portion of the change as there are few if any non-convex shapes. Instead, a change in depth testing from the assigned depth values/enabling of the depth test must be responsible

**Comment by jonahwilliams** [comment] 2024-03-18 00:22
The problem is the depth write portion of the intersect clip. For something like flutter gallery that has 3-4 intersect clips, we end up doing as many fullscreen depth writes. This is apparently super expensive, and constitutes roughly 6ms of the 7ms GPU frame time.

**Comment by jonahwilliams** [comment] 2024-03-18 19:31
I investigated iOS performance. On the flutter gallery example app, there does not seem to be any performance regression - and the clips themselves comprise a trivial amount of GPU time. While that is only one example, its possible that this is only an Arm/QC vs apple GPU performance difference.

**Comment by bdero** [comment] 2024-03-25 16:59
So right now we always draw intersect clips to the whole framebuffer. But we only need to actually need to draw over the max combined coverage of all the entities which the clip affects, which is something we can know by restore time.

> On the flutter gallery example app, there does not seem to be any performance regression - and the clips themselves comprise a trivial amount of GPU time. While that is only one example, its possible that this is only an Arm/QC vs apple GPU performance difference.

I would maybe try this against Wondrous on a high DPI iPad. I expect the performance is less than stellar on some screens there because of this.

**Comment by bdero** [comment] 2024-03-25 17:11
The actual limiting the size of the draw call is no problem, we just gotta compute the area we need to cover better.

**Comment by bdero** [comment] 2024-03-25 17:12
This is exactly the same as the optimization we were going to do for difference clips we talked about at some point, but never got around to it because they're so rare in practice.

**Comment by jonahwilliams** [comment] 2024-03-26 18:14
My rough idea: set a scissor rect for the render pass sized to the outer coverage of the clip rect, keep the scissor applied until the clip is restored. Avoids having to compute exact coverage. Essentially the depth write covers the non-rectangular and multisampled parts of the clip, the scissor does everything else.

**Comment by bdero** [comment] 2024-03-27 05:05
Yeah just using the clip coverage for the limiter is a good idea here. Pushed this to a patch here: https://github.com/flutter/engine/pull/51698.

I think trying to compute a smaller rect by unioning the coverage of all the entities is not worth the squeeze here...

**Comment by bdero** [comment] 2024-03-28 20:39
The new gallery regression was fixed by https://github.com/flutter/engine/pull/51731. Doesn't look like this fix had an impact on complex layout, though.

https://github.com/flutter/engine/pull/51736 also just landed and will hopefully have an impact on some benchmarks.

**Comment by bdero** [comment] 2024-04-02 17:13
We're doing better than before the regression after https://github.com/flutter/engine/pull/51736 landed. Closing this.
<img width="1507" alt="image" src="https://github.com/flutter/flutter/assets/919017/a61b3051-726d-48e5-9925-41129fb19395">

**Closed by bdero** 2024-04-02 17:13 UTC
Labels: P1, e: impeller, team-engine, triaged-engine

**Comment by jonahwilliams** [comment] 2024-04-02 17:59
very nice!
