### ISSUE TITLE
Material icons code point change

### ISSUE THREAD

**Issue by geekydiamond** [flutter/flutter#75633] opened 2021-02-08 14:19 UTC
Hi,

We were sharing material icon code point between web and flutter app. This was working until we upgraded Flutter and now there is a complete mismatch between the code points.
We have these code points stored in the database, and it looks like we suddenly need to map code points between web and flutter??

It looks like the backwards incompatible commit took place on 24th June 2020
[Material] Updated icons and fonts (#61778)
https://github.com/flutter/flutter/commits/master/packages/flutter/lib/src/material/icons.dart

Please could you advise why this backwards incompatible change took place, whether it can be resolved, and why flutter doesn't have consistent code points with the web code points
https://github.com/google/material-design-icons/blob/master/font/MaterialIcons-Regular.codepoints

Thanks,
Tom

**Comment by HansMuller** [comment] 2021-02-08 19:22
CC @willlarche

**Comment by willlarche** [comment] 2021-02-08 21:51
Hi, @geekydiamond ! My name's Will from Material Engineering and I was responsible for this change. I'm sorry it's caused trouble for your project.

The icon font that Flutter uses is not the icon font that's publicly available but rather one that is created _especially for Flutter_ by the Google Fonts team led by @rsheeter. When we pull it, it contains the latest of all externally licensed icons in all styles except 2-tone which is not supported in Flutter. 

It is not the one you find at google/material-design-icons. For various reasons I'm not privy to (mostly I believe around a rebuild of their icon->font pipeline) the codepoints in our new change were not going to match older versions of the codepoints. The Google Fonts team asked us if we were ok with that and we said yes. The `Icons` class in Flutter is intended to be accessed via the consts and not via the values they map to. And since anyone who updated would automatically have the new mapping, it was not considered a breaking change since it did not break the supported developer experience.

I'm so sorry that it ended up being trouble for you. **Unfortunately we cannot guarantee that the font we use will ever match the one in that directory**. We have our own release schedule which is independent of the Google Fonts team and we have a version of the icons font that is made especially for us. 

We also do not recommend using the codepoints directly in Flutter. They are intended to be accessed via the consts that don't change (`Icons` class). 

I'm going to close this issue as 'working as intended' but do write back if there's anything you find that is not working as intended!

**Closed by willlarche** 2021-02-08 21:51 UTC
Labels: f: material design, framework

**Comment by geekydiamond** [comment] 2021-02-09 09:50
Hi @willlarche ,

Thanks for the fast response. I'm very surprised that the view is that codepoints should not be used given the documentation around them.

The code point is listed on this page under every icon:
https://api.flutter.dev/flutter/material/Icons-class.html

The way to create an icon uses code points:
https://api.flutter.dev/flutter/widgets/IconData/IconData.html

The google documentation says to use code points if required
https://google.github.io/material-design-icons/#icon-font-for-the-web

I cannot see a way to create an icon from the consts in Flutter? If this is the recommended approach I would have expected there to be more support for this approach, and clearer documentation warning about using code points.

**Comment by willlarche** [comment] 2021-02-09 15:36
That's a good point on the listing of the numbers in the documentation. @HansMuller , any objection to us removing the line under the description of each `Icons`? (`IconData(58712, fontFamily: 'MaterialIcons')`)

The `IconData` class is the class backing `Icons`. Its api has to use codepoints to correctly access the font. This class is public because people use `IconData` with their own fonts for custom icons which are then treeshaken. 

The documentation for the icon font that says to use codepoints if required is the HTML guidance, not Flutter. And like I said, we don't even use this font. We have our own version from them. So documentation from that repo is useful for a comparison but doesn't completely apply to what we do in our repo. Since we have always used our own icon font that is updated independently of the public icon font, we never intended (and I certainly never imagined) that people would use the codepoints in projects of a completely different stack. (And btw, it's a very clever idea! And I'm sorry that we aren't going to be able to support it.) There could be an opportunity for you to use Flutter for Web to solve this problem. That would certainly mean that you're using the same codepoints and font. But I also understand if it makes no sense to rebuild all or a part of your web project. :\

Also good feedback about putting in a warning around the codepoints. @HansMuller any objection to us updating the `Icons` documentation to have an explicit explanation that we intend the icons to be access via the consts and that the codepoints are subject to change?

@geekydiamond , I know this may not quickly fix things, but since all the information you need is available in the source code, you may be able to roll your own solution to this problem. See [update_icons.dart](https://github.com/flutter/flutter/blob/master/dev/tools/update_icons.dart) for how we use the codepoints file that's found in bin/cache/artifacts/material_fonts to make our class. It could be a useful reference for you. 

Again, I'm sorry for the confusion around this and that we don't have a quick solution to your problem. Thank you for the feedback on how we can update the documentation to make our support developer experience clearer. I'd love to hear how you end up solving this in the long run too!

**Comment by rsheeter** [comment] 2021-02-10 08:17
For context, for general web use we provide one font for each style and "thing" has the same codepoint (with stable name:codepoint assignment) and ligature in all of them.

For Flutter we generate a single font that contained many styles of the same asset (thing, thing_outlined, thing_sharp, etc). We assume Flutter users use the provided constants and that those constants update when the font updates so it doesn't really matter if the codepoints are stable.

**Comment by geekydiamond** [comment] 2021-03-25 11:31
FYI we switched to embedding the ligature in a Text widget with the style setting the font family to the material font:
```
Text(
  iconLigature,
  style: TextStyle(
    fontFamily: iconFontFamily,
  ),
)
```
We then passed the ligature name from the web side, so it's all good now :)

I really suggest the docs are updated though so that others don't fall into a similar trap where they assume datapoints are immutable. For example, the Flutter icons page still has entries like:
ac_unit_rounded → const IconData
ac_unit — material icon named "ac unit rounded".
IconData(61491, fontFamily: 'MaterialIcons')

Thanks
