### ISSUE TITLE
BouncingScrollPhysics issue

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#62890] opened 2020-08-04 18:57 UTC
This is a pagination case. If a user in overscroll (maxExtended - position < 0) while new data coming into the list and didn't unpin it's finger, CustomScrollView with BouncingScrollPhysics will kick you into the end of the list.

Flutter channel: stable. 
Flutter version: v1.20.0

Example: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyHomePage());
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final list = [0, 1, 2];
  var loading = false;
  final colors = [
    Colors.cyan,
    Colors.indigo,
    Colors.pink,
    Colors.red,
    Colors.blue,
    Colors.yellowAccent
  ];

  final sc = ScrollController();

  @override
  void initState() {
    super.initState();
    sc.addListener(_onScroll);
  }

  Future<void> loadMore() async {
    if(list.length < 6){
      await Future.delayed(const Duration(seconds: 3));
      list.addAll([3, 4, 5]);
    }
  }

  void _onScroll() {
    final maxExtended = sc.position.maxScrollExtent;
    final position = sc.position.pixels;
    final dif = maxExtended - position;
    if (dif == 0.0 && !loading) {
      loading = true;
      loadMore().then((value) {
        setState(() {});
        loading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: CustomScrollView(
        controller: sc,
        physics: BouncingScrollPhysics(),
        slivers: [
          SliverList(
              delegate: SliverChildBuilderDelegate(
                  (_, index) => SizedBox(
                      width: double.infinity,
                      child: Container(
                        height: 400,
                        color: colors[index],
                        child: Text(
                          index.toString(),
                          style: TextStyle(
                            fontSize: 30,
                          ),
                        ),
                      )),
                  childCount: list.length))
        ],
      ),
    );
  }

  @override
  void dispose() {
    sc.dispose();
    super.dispose();
  }
}
```

Video: 
![ezgif-4-580f64cab9f1](https://user-images.githubusercontent.com/42138594/89333227-599ea480-d69d-11ea-8e23-afd69bab827c.gif)

**Comment by darshankawar** [comment] 2020-08-05 06:39
Hi @Renesanse,
I tried to replicate the code on latest Flutter dev and observed `RangeError` exception as below:

![62890](https://user-images.githubusercontent.com/67046386/89379935-5266ad80-d714-11ea-8da9-b19d25bc3c12.png)

Exception:

```
Another exception was thrown: RangeError (index): Invalid value: Not in inclusive range 0..5: 6

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following RangeError was thrown building:
RangeError (index): Invalid value: Not in inclusive range 0..5: 6

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      _MyHomePageState.build.<anonymous closure> (package:hello_world/main.dart:2830:38)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:448:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1129:28)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1142:55)
```
I tested on Android 8.1.0 device.

Did you get this exception when you tried ?

**Comment by Renesanse** [comment] 2020-08-05 09:15
Hi, @darshankawar. You don't need to scroll more than once to understand the issue, btw i can fix my example

**Comment by Renesanse** [comment] 2020-08-07 10:32
@darshankawar in release 1.17 everything is fine. I tested in 1.20

**Comment by dnfield** [comment] 2020-10-05 21:43
@Renesanse - could you write a test case that fails for what you're talking about? Your application looks like it's probably pretty close, but it's a little hard for me to tell right now what assertion would/should fail there.

**Comment by Hixie** [comment] 2020-10-05 22:23
The animated screenshot above is working as intended, FWIW (it's definitely what you want if the cause is just the contents changing height; it's less clear if it's what you want in a case such as this where there's just more content). You should be able to change it by replacing the scroll physics to not include the RangeMaintainingScrollPhysics, though.

**Comment by Renesanse** [comment] 2020-10-05 22:30
> @Renesanse - could you write a test case that fails for what you're talking about? Your application looks like it's probably pretty close, but it's a little hard for me to tell right now what assertion would/should fail there.

Hello @dnfield, I guess good explanation will be is a during configuration of ScrollPhysics right now, new data, for example, in ListView will move user's scroll position directly to the bottom of whole ListView widget ignoring that user did not scroll anything or other activities to appear on the bottom. I sure this issue connected with this pr https://github.com/flutter/flutter/pull/65135

**Comment by enricobenedos** [comment] 2020-10-13 21:26
Hello @darshankawar, 
after Flutter update from 1.20.4 to 1.22.0 I'm receiving the `Range` error as below:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following RangeError was thrown building:
flutter: RangeError (index): Invalid value: Not in inclusive range 0..8: 9
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:177:60)
flutter: #1      _SubArticlePageState.build.<anonymous closure> (package:wamii_app/pages/sub_article_page.dart:72:46)
flutter: #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:449:22)
flutter: #3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1130:28)
flutter: #4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1143:55)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
flutter: #6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1136:11)
flutter: #7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:350:23)
flutter: #8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
flutter: #9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
flutter: #10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
flutter: #11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:339:5)
flutter: #12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:485:5)
flutter: #13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:231:19)
flutter: #14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:274:19)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132:12)
flutter: #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
flutter: #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:507:13)
flutter: #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1561:12)
flutter: #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1470:20)
flutter: #22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
flutter: #23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
flutter: #24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
flutter: #25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
flutter: #26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #33     _invoke (dart:ui/hooks.dart:251:10)
flutter: #34     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```
The identical code deployed in production with `1.20.4` works perfectly but it generate exception with `1.22.0` and `1.22.1`

**Comment by enricobenedos** [comment] 2020-10-14 11:19
Is that bug fixed on `master`/`dev `branch? We are waiting to release our app update due to this bug

**Comment by Renesanse** [comment] 2020-10-14 21:25
Hello, you can try this fix for a while: https://github.com/flutter/flutter/pull/67178

**Comment by jp928** [comment] 2021-09-23 01:56
Any solution or work around?

**Closed** 2021-11-11 02:06 UTC
Labels: severe: regression, framework, f: material design, f: scrolling, has reproducible steps, found in release: 1.20
