### ISSUE TITLE
Cannot download flutter-cpp-client-wrapper.zip for 1.21.0-10.0.pre.139

### ISSUE THREAD

**Issue by Bangybug** [flutter/flutter#64041] opened 2020-08-18 13:42 UTC
I was about to build a windows desktop binding. But my build process was unsuccessful.  I'm getting 404 error while downloading https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-client-wrapper.zip
```

Flutter is already up to date on channel master
Flutter 1.21.0-10.0.pre.139 • channel master • https://github.com/flutter/flutter.git
Framework • revision a51dc3d913 (7 hours ago) • 2020-08-18 02:51:02 -0400
Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)

Downloading windows-x64/windows-x64-flutter tools... (cached)
[+7298 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools...
[   +6 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-client-wrapper.zip
[  +45 ms] List of devices attached
[ +335 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 0.4s)
[   +2 ms] "flutter run" took 14,788ms.
[  +18 ms] Download failed.
           URL: https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-client-wrapper.zip
           Error: 404 Not Found
```

**Comment by KristijanMitrik** [comment] 2020-08-18 13:46
I am having the same issue after upgrading flutter to new version

**Comment by Bangybug** [comment] 2020-08-18 13:56
I could locally roll back engine.version file in the flutter sdk to the previous commit to avoid this problem, just to keep things going for me.

**Comment by hamdikahloun** [comment] 2020-08-18 14:20
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-10.0.pre.139, on Microsoft Windows [version 10.0.19041.450], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)

• No issues found!

flutter run -d windows

Downloading windows-x64/flutter-cpp-client-wrapper tools...
Download failed.
URL:
https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-cl
ient-wrapper.zip
Error: 404 Not Found

**Comment by hamdikahloun** [comment] 2020-08-18 14:45
![image](https://user-images.githubusercontent.com/32666446/90527708-bdc76b00-e169-11ea-947b-839ade8d2628.png)

**Comment by TahaTesser** [comment] 2020-08-18 14:53
Just tried on windows, success 

<details> 
<summary>logs</summary> 

```
PS C:\Users\Taha> flutterm upgrade -v
[ +123 ms] executing: [C:\Code\flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3562b3c0de3baa990d61f852e6ff12e843223fc6
[   +1 ms] executing: [C:\Code\flutter_master/] git tag --points-at HEAD
[  +43 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [C:\Code\flutter_master/] git describe --match *.*.* --first-parent --long --tags                 [  +54 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags                                    [        ] 1.21.0-9.0.pre-138-g3562b3c0d                                                                                [  +22 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref HEAD                                         [  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD                                                            [        ] master                                                                                                       [  +60 ms] executing: [C:\Code\flutter_master/] git tag --points-at HEAD                                                [  +34 ms] Exit code 0 from: git tag --points-at HEAD
[        ] executing: [C:\Code\flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +65 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-138-g3562b3c0d
[   +3 ms] executing: [C:\Code\flutter_master/] git fetch --tags
[+2330 ms] executing: [C:\Code\flutter_master/] git rev-parse --verify @{u}
[  +32 ms] a51dc3d913344f3073da12f4aae654c3299dec6c
[   +1 ms] executing: [C:\Code\flutter_master/] git status -s
[  +89 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Code\flutter_master/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +6 ms] Upgrading Flutter from C:\Code\flutter_master...
[   +1 ms] executing: [C:\Code\flutter_master/] git reset --hard a51dc3d913344f3073da12f4aae654c3299dec6c
[ +466 ms] HEAD is now at a51dc3d91 Roll Engine from 02de4eb7cefa to 0b330467da24 (2 revisions) (#64024)
[   +2 ms] executing: [C:\Code\flutter_master/] bin\flutter upgrade --continue --no-version-check
[ +339 ms] Checking Dart SDK version...
[ +423 ms] Downloading Dart SDK from Flutter engine 0b330467da244c86637db5fdaa5ef5401e90beba...
[+17855 ms] Unzipping Dart SDK...
[+15798 ms] Building flutter tool...
[   +5 ms] Running pub upgrade...
[+34401 ms] Upgrading engine...
[+41204 ms] Downloading Android Maven dependencies...                          40.1s
[ +844 ms] Downloading android-arm-profile/windows-x64 tools...                0.8s
[+1178 ms] Downloading android-arm-release/windows-x64 tools...                0.7s
[+1161 ms] Downloading android-arm64-profile/windows-x64 tools...              0.8s
[+1062 ms] Downloading android-arm64-release/windows-x64 tools...              0.8s
[+1060 ms] Downloading android-x64-profile/windows-x64 tools...                0.8s
[+1071 ms] Downloading android-x64-release/windows-x64 tools...                0.8s
[+2780 ms] Downloading android-x86 tools...                                    2.5s
[+3881 ms] Downloading android-x64 tools...                                    2.5s
[+2896 ms] Downloading android-arm tools...                                    1.4s
[+1368 ms] Downloading android-arm-profile tools...                            1.3s
[ +988 ms] Downloading android-arm-release tools...                            0.9s
[+1603 ms] Downloading android-arm64 tools...                                  1.6s
[+1206 ms] Downloading android-arm64-profile tools...                          1.1s
[+1164 ms] Downloading android-x64-profile tools...                            1.1s
[+1103 ms] Downloading android-x64-release tools...                            1.0s
[+1342 ms] Downloading android-x86-jit-release tools...                        1.3s
[ +375 ms] Downloading package sky_engine...                                   0.3s
[+3102 ms] Downloading flutter_patched_sdk tools...                            1.7s
[+3647 ms] Downloading flutter_patched_sdk_product tools...                    1.7s
[+4644 ms] Downloading windows-x64 tools...                                    2.9s
[+3843 ms] Downloading windows-x64/font-subset tools...                        0.6s
[ +687 ms] Flutter 1.21.0-10.0.pre.139 • channel master • https://github.com/flutter/flutter.git
[   +2 ms] Framework • revision a51dc3d913 (8 hours ago) • 2020-08-18 02:51:02 -0400
[        ] Engine • revision 0b330467da
[        ] Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)
[   +1 ms] Running flutter doctor...
[+3364 ms] Doctor summary (to see all details, run flutter doctor -v):
[ +577 ms] [✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Microsoft Windows [Version 10.0.19041.450], locale
en-US)
[+9753 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[   +1 ms] [✓] Chrome - develop for the web
[        ] [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
[   +1 ms] [✓] Android Studio (version 4.0)
[   +1 ms] [✓] VS Code (version 1.48.0)
[   +1 ms] [✓] Connected device (3 available)
[        ] • No issues found!
[ +423 ms] "flutter upgrade" took 169,298ms.
[ +158 ms] ensureAnalyticsSent: 152ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
PS C:\Users\Taha> flutterm doctor -v
[✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.139 at C:\Code\flutter_master
    • Framework revision a51dc3d913 (8 hours ago), 2020-08-18 02:51:02 -0400
    • Engine revision 0b330467da
    • Dart version 2.10.0 (build 2.10.0-38.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30406.217
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment] 2020-08-18 14:56
```
event sent after app closed: {id: 0, progressId: null, message: Downloading windows-x64/windows-x64-flutter tools...}
event sent after app closed: {id: 0, progressId: null, finished: true}
event sent after app closed: {id: 1, progressId: null, message: Downloading windows-x64/flutter-cpp-client-wrapper tools...}
event sent after app closed: {id: 1, progressId: null, finished: true}
Download failed.
URL: https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-client-wrapper.zip
Error: 404 Not Found
```

<details> 
<summary>logs</summary> 

```
PS C:\Users\Taha> flutterm upgrade -v
[ +123 ms] executing: [C:\Code\flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3562b3c0de3baa990d61f852e6ff12e843223fc6
[   +1 ms] executing: [C:\Code\flutter_master/] git tag --points-at HEAD
[  +43 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [C:\Code\flutter_master/] git describe --match *.*.* --first-parent --long --tags                 [  +54 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags                                    [        ] 1.21.0-9.0.pre-138-g3562b3c0d                                                                                [  +22 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref HEAD                                         [  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD                                                            [        ] master                                                                                                       [  +60 ms] executing: [C:\Code\flutter_master/] git tag --points-at HEAD                                                [  +34 ms] Exit code 0 from: git tag --points-at HEAD
[        ] executing: [C:\Code\flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +65 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-138-g3562b3c0d
[   +3 ms] executing: [C:\Code\flutter_master/] git fetch --tags
[+2330 ms] executing: [C:\Code\flutter_master/] git rev-parse --verify @{u}
[  +32 ms] a51dc3d913344f3073da12f4aae654c3299dec6c
[   +1 ms] executing: [C:\Code\flutter_master/] git status -s
[  +89 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Code\flutter_master/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +6 ms] Upgrading Flutter from C:\Code\flutter_master...
[   +1 ms] executing: [C:\Code\flutter_master/] git reset --hard a51dc3d913344f3073da12f4aae654c3299dec6c
[ +466 ms] HEAD is now at a51dc3d91 Roll Engine from 02de4eb7cefa to 0b330467da24 (2 revisions) (#64024)
[   +2 ms] executing: [C:\Code\flutter_master/] bin\flutter upgrade --continue --no-version-check
[ +339 ms] Checking Dart SDK version...
[ +423 ms] Downloading Dart SDK from Flutter engine 0b330467da244c86637db5fdaa5ef5401e90beba...
[+17855 ms] Unzipping Dart SDK...
[+15798 ms] Building flutter tool...
[   +5 ms] Running pub upgrade...
[+34401 ms] Upgrading engine...
[+41204 ms] Downloading Android Maven dependencies...                          40.1s
[ +844 ms] Downloading android-arm-profile/windows-x64 tools...                0.8s
[+1178 ms] Downloading android-arm-release/windows-x64 tools...                0.7s
[+1161 ms] Downloading android-arm64-profile/windows-x64 tools...              0.8s
[+1062 ms] Downloading android-arm64-release/windows-x64 tools...              0.8s
[+1060 ms] Downloading android-x64-profile/windows-x64 tools...                0.8s
[+1071 ms] Downloading android-x64-release/windows-x64 tools...                0.8s
[+2780 ms] Downloading android-x86 tools...                                    2.5s
[+3881 ms] Downloading android-x64 tools...                                    2.5s
[+2896 ms] Downloading android-arm tools...                                    1.4s
[+1368 ms] Downloading android-arm-profile tools...                            1.3s
[ +988 ms] Downloading android-arm-release tools...                            0.9s
[+1603 ms] Downloading android-arm64 tools...                                  1.6s
[+1206 ms] Downloading android-arm64-profile tools...                          1.1s
[+1164 ms] Downloading android-x64-profile tools...                            1.1s
[+1103 ms] Downloading android-x64-release tools...                            1.0s
[+1342 ms] Downloading android-x86-jit-release tools...                        1.3s
[ +375 ms] Downloading package sky_engine...                                   0.3s
[+3102 ms] Downloading flutter_patched_sdk tools...                            1.7s
[+3647 ms] Downloading flutter_patched_sdk_product tools...                    1.7s
[+4644 ms] Downloading windows-x64 tools...                                    2.9s
[+3843 ms] Downloading windows-x64/font-subset tools...                        0.6s
[ +687 ms] Flutter 1.21.0-10.0.pre.139 • channel master • https://github.com/flutter/flutter.git
[   +2 ms] Framework • revision a51dc3d913 (8 hours ago) • 2020-08-18 02:51:02 -0400
[        ] Engine • revision 0b330467da
[        ] Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)
[   +1 ms] Running flutter doctor...
[+3364 ms] Doctor summary (to see all details, run flutter doctor -v):
[ +577 ms] [✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Microsoft Windows [Version 10.0.19041.450], locale
en-US)
[+9753 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[   +1 ms] [✓] Chrome - develop for the web
[        ] [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
[   +1 ms] [✓] Android Studio (version 4.0)
[   +1 ms] [✓] VS Code (version 1.48.0)
[   +1 ms] [✓] Connected device (3 available)
[        ] • No issues found!
[ +423 ms] "flutter upgrade" took 169,298ms.
[ +158 ms] ensureAnalyticsSent: 152ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
PS C:\Users\Taha> flutterm doctor -v
[✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.139 at C:\Code\flutter_master
    • Framework revision a51dc3d913 (8 hours ago), 2020-08-18 02:51:02 -0400
    • Engine revision 0b330467da
    • Dart version 2.10.0 (build 2.10.0-38.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30406.217
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
``` 

</details>

**Comment by hamdikahloun** [comment] 2020-08-18 14:59
For now you can downgrade => flutter downgrade

**Comment by stuartmorgan** [comment] 2020-08-18 16:19
I checked the bot for that build, and the upload succeeded, but was to:
https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/flutter-cpp-client-wrapper.zip
instead of:
https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-client-wrapper.zip

The folder appears to have been dropped, which is likely a regression from https://flutter-review.googlesource.com/c/recipes/+/5520
@blasten @godofredoc

**Comment by christopherfujino** [comment] 2020-08-18 16:38
Recipe revert here https://flutter-review.googlesource.com/c/recipes/+/5840

**Comment by christopherfujino** [comment] 2020-08-18 17:43
We have a good engine build at https://chromium.googlesource.com/external/github.com/flutter/engine/+/de98e846b3ad94cfb7de810526c91518b2d26c53. The next engine roll should pick this up.

**Comment by TahaTesser** [comment] 2020-08-19 14:28
Windows run is still broken with updates to latest master

<details> 
<summary>logs</summary> 

```
[  +97 ms] executing: [C:\Code\flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 021cf56fc97f96e0571bbb13d2c7a6d66de3beff
[        ] executing: [C:\Code\flutter_master/] git tag --points-at HEAD
[  +32 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\Code\flutter_master/] git describe --match *.*.* --first-parent --long --tags
[  +46 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-162-g021cf56fc
[   +9 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Code\flutter_master/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [C:\Code\flutter_master/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +14 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[+6502 ms] Downloading windows-x64/windows-x64-flutter tools... (cached)
[+6018 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools...
[  +11 ms] Downloading:
https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-cl
ient-wrapper.zip
[  +36 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:9
[ +501 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 0.5s)
[   +2 ms] "flutter run" took 13,126ms.
[   +8 ms] Download failed.
           URL:

https://storage.googleapis.com/flutter_infra/flutter/0b330467da244c86637db5fdaa5ef5401e90beba/windows-x64/flutter-cpp-cl
           ient-wrapper.zip
           Error: 404 Not Found
[  +14 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      Net._attempt (package:flutter_tools/src/base/net.dart:148:9)
           <asynchronous suspension>
           #2      Net.fetchUrl (package:flutter_tools/src/base/net.dart:63:33)
           #3      Cache.downloadFile (package:flutter_tools/src/cache.dart:489:16)
           #4      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:637:23)
           #5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:633:55)
           #6      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:667:26)
           #7      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:633:12)
           #8      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:654:12)
           #9      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:792:13)
           #10     _rootRunUnary (dart:async/zone.dart:1198:47)
           #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #18     CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart)
           #19     _rootRunUnary (dart:async/zone.dart:1198:47)
           #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #25     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #26     _rootRun (dart:async/zone.dart:1190:13)
           #27     _CustomZone.run (dart:async/zone.dart:1093:19)
           #28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +234 ms] ensureAnalyticsSent: 230ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 50
``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.162, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.162 at C:\Code\flutter_master
    • Framework revision 021cf56fc9 (44 minutes ago), 2020-08-19 09:30:28 -0400
    • Engine revision 0b330467da
    • Dart version 2.10.0 (build 2.10.0-38.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30406.217
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2020-08-19 16:11
> Engine revision 0b330467da

Because there hasn't been an engine roll.

**Comment by christopherfujino** [comment] 2020-08-20 00:35
This was fixed as of https://github.com/flutter/flutter/commit/380e8f3bb48ae19d7101d9319053af78fabedc5c.

**Closed by christopherfujino** 2020-08-20 00:35 UTC
Labels: P0, found in release: 1.21, has reproducible steps, platform-windows, severe: crash, severe: regression, tool

**Comment by christopherfujino** [comment] 2020-08-20 17:05
Affected framework hashes:

```
380e8f3bb48ae19d7101d9319053af78fabedc5c
606abc915fb85e6896c85e19c1cf3fa4f526745a
430e3cf08c49d34cbec618bd0b322e1635620287
1b69983c6d46cd163036c9027749f05f4c58c8f3
021cf56fc97f96e0571bbb13d2c7a6d66de3beff
db705b81e3aa427bec93f8d0d20cda82e35f1212
ce63f507336fa86278204dfac2b9a9546f81ab96
86d2fe9f2064a10f9220a5f1a69abf967df8564a
3e867f78dbcce935cefb5444a848586848d7c9e3
1b4775952889830e8181fb2997cd5c28418dd8c8
d6c254be4e2b4928e9f896b379a00bca394394f1
e1a09622df97efd4e4793a9b6b3e727db2af46e3
acdb909fcb7fa078d2c536db4c5182c4b1b37337
b92f80e22a570d284a698f4d022fbb268081046e
734a90eb3a039eb316a8611a1431a1d27e7c294b
6ca9cd7b8f6103a1475e71eec2e0888633da2e19
48287750d069d194221ca9694962bed1661f91c2
d504437d88a7de2e450a708a2245a23ebb3b172d
a42c56791b176df32f6dea5e2d6863608cbe8bc3
39c735f40876ca277678a0b91def0b151663b258
2122fe1fa102d2b0ee1afbd8135569cc2a36f04b
d1eff0b413db535f16c81cfeab24dc6b39d4738a
7f122c7429264088adcba73122c4aa69005f9f3a
bd6252eb3a49be1b1480a6336af444aa6c13c8a4
f0dd4ad5302d5424f77094bc50ebb7f2b32c447a
61362cff85816a0dfffb04ddc47a35e3e9ae3f7d
473744df2c50bb2756eed70d451be0262a2dfa74
a51dc3d913344f3073da12f4aae654c3299dec6c
```
