### ISSUE TITLE
[Camera] [android] CameraController doesn't update device orientation when orientation changes if orientation is locked

### ISSUE THREAD

**Issue by huylethanh** [flutter/flutter#89898] opened 2021-09-11 03:58 UTC
When we lock the view on `portraitUp` the device orientation does not change when we call `controller!.value.deviceOrientation`, it is set on the locked orientation.
 
On version `^0.8.1+4` after locking the orientation, the `CameraController` provides the correct orientation when I call `controller!.value.deviceOrientation`.

**Comment by danagbemava-nc** [comment] 2021-09-13 07:55
Hi @huylethanh, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by huylethanh** [comment] 2021-09-13 09:18
the step so simple. on the initState(). I added the code to lock the orientation.
//Lock the orientaion here
SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

and on the cameracontroll listener.
cameraController.addListener(() {
      if (mounted) setState(() {});

      // on version 0.8.1+4, i still get the call back. the new version is not. -------------------------------
      print(cameraController.value.deviceOrientation);
 });


On version 0.8.1+4 I can get the callback and the deviceOrientation shows correct when i rotate the phone screen.

My flutter doctor info:

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/huyle/development/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/huyle/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 970FABAB-E473-470A-99F0-5AB168E5D601 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment] 2021-09-13 14:45
Hi @huylethanh, I am using the `0.8.1+4` version and when I rotate the device, I don't get a print statements. 

Is there any additional context that I'm missing or any more information that you can provide? 

Thank you

**Comment by huylethanh** [comment] 2021-09-14 01:54
Hello make sure you only set the camera version camera: 0.8.1+4, not the camera: ^0.8.1+4. the code like the code file in the attachment. here is the screenshot.

![image](https://user-images.githubusercontent.com/37363048/133181715-b70befed-c1a2-48b4-8691-633275e95274.png)

**Comment by danagbemava-nc** [comment] 2021-09-14 06:56
Hi @huylethanh, thanks. I had my `orientation lock` on, that's why it wasn't changing. 

I can reproduce this issue on `android` only. `iOS` works just fine. 

It worked up until `camera: ^0.8.1+7` for `android`.

<details>
<summary>logs</summary>

`camera: ^0.8.1+7`

```console
Launching lib/issue_89898.dart on M2007J20CG in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59936/wKTTOMFKTV8=/ws
I/CameraManagerGlobal(  702): Connecting to camera service
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 100
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 101
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 21
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 22
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 25
W/CameraManagerGlobal(  702): [soar.cts] ignore the status update of camera: 61
W/CameraManagerGlobal(  702): ignore the torch status update of camera: 100
W/CameraManagerGlobal(  702): ignore the torch status update of camera: 21
W/CameraManagerGlobal(  702): ignore the torch status update of camera: 22
W/CameraManagerGlobal(  702): ignore the torch status update of camera: 61
I/com.example.w6(  702): ProcessProfilingInfo new_methods=511 is saved saved_to_disk=1 resolve_classes_delay=8000
D/MIUIInput(  702): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=182200475, downTime=182200475 } moveCount:0
D/MIUIInput(  702): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=182200508, downTime=182200475 } moveCount:3
I/Camera  (  702): [FPS Range Available] is:[15, 15]
I/Camera  (  702): [FPS Range Available] is:[8, 30]
I/Camera  (  702): [FPS Range Available] is:[30, 30]
I/Camera  (  702): [FPS Range] is:[8, 30]
E/libc    (  702): Access denied finding property "persist.vendor.camera.privapp.list"
W/com.example.w6(  702): type=1400 audit(0.0:292858): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=10063 scontext=u:r:untrusted_app:s0:c163,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.w6
E/CameraManagerGlobal(  702): Camera 61 is not available. Ignore physical camera status change
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeRight
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeLeft
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeRight
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeLeft
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeRight
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeLeft
I/flutter (  702): DeviceOrientation.portraitUp
I/flutter (  702): DeviceOrientation.landscapeRight
I/flutter (  702): DeviceOrientation.portraitUp
Application finished.
Exited (sigterm)
```

`camera: ^0.9.3`

```console
Launching lib/issue_89898.dart on M2007J20CG in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:60319/8w2QzHuDmUc=/ws
I/CameraManagerGlobal( 2087): Connecting to camera service
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 100
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 101
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 21
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 22
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 25
W/CameraManagerGlobal( 2087): [soar.cts] ignore the status update of camera: 61
W/CameraManagerGlobal( 2087): ignore the torch status update of camera: 100
W/CameraManagerGlobal( 2087): ignore the torch status update of camera: 21
W/CameraManagerGlobal( 2087): ignore the torch status update of camera: 22
W/CameraManagerGlobal( 2087): ignore the torch status update of camera: 61
I/com.example.w6( 2087): ProcessProfilingInfo new_methods=568 is saved saved_to_disk=1 resolve_classes_delay=8000
D/MIUIInput( 2087): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=182540902, downTime=182540902 } moveCount:0
D/MIUIInput( 2087): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=182540944, downTime=182540902 } moveCount:4
E/libc    ( 2087): Access denied finding property "persist.vendor.camera.privapp.list"
W/com.example.w6( 2087): type=1400 audit(0.0:294080): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=10063 scontext=u:r:untrusted_app:s0:c163,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.w6
E/CameraManagerGlobal( 2087): Camera 61 is not available. Ignore physical camera status change
I/Camera  ( 2087): startPreview
I/flutter ( 2087): DeviceOrientation.portraitUp
I/Camera  ( 2087): Updating builder settings
D/Camera  ( 2087): Updating builder with feature: ExposureLockFeature
D/Camera  ( 2087): Updating builder with feature: ExposurePointFeature
D/Camera  ( 2087): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 2087): Updating builder with feature: AutoFocusFeature
D/Camera  ( 2087): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 2087): updateNoiseReduction | currentSetting: fast
D/Camera  ( 2087): Updating builder with feature: FocusPointFeature
D/Camera  ( 2087): Updating builder with feature: ResolutionFeature
D/Camera  ( 2087): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 2087): Updating builder with feature: FlashFeature
D/Camera  ( 2087): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 2087): Updating builder with feature: FpsRangeFeature
I/flutter ( 2087): DeviceOrientation.portraitUp
Application finished.
Exited (sigterm)
```

`iOS for comparison`

```console
Launching lib/issue_89898.dart on Nexus’ IPhone in debug mode...
Found saved certificate choice "Apple Development: Dean Li (DXB2HBHNAA)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Dean Li (DXB2HBHNAA)"
Xcode build done.                                           13.6s
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Connecting to VM Service at ws://127.0.0.1:60473/XNHmJLo7gc0=/ws
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeRight
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeLeft
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeRight
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeLeft
flutter: DeviceOrientation.portraitDown
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeRight
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeLeft
flutter: DeviceOrientation.portraitDown
flutter: DeviceOrientation.landscapeLeft
flutter: DeviceOrientation.portraitUp
flutter: DeviceOrientation.landscapeRight
flutter: DeviceOrientation.portraitUp
Application finished.
Exited (sigterm)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.82, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.82 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3b7adb989f (2 hours ago), 2021-09-13 21:32:04 -0700
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by huylethanh** [comment] 2021-09-14 07:28
Thank you so much.

**Comment by BeMacized** [comment] 2021-09-28 11:32
It is indeed correct that you can no longer get the physical orientation of the device, as the `deviceOrientation` property should reflect the UI orientation since 0.9.0. 

While this seems to work fine when locking the orientation via the system, I see that the device orientation reported on iOS is not locked when using `SystemChrome.setPreferredOrientations`. 

I'm closing this issue in favour of #89216, so this can be discussed in further detail over there.

**Closed by BeMacized** 2021-09-28 11:32 UTC
Labels: severe: regression, platform-android, plugin, p: first party, p: camera, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
