### ISSUE TITLE
TextFields inside ListView dont rise above keyboard when focused in Flutter 3.10.1

### ISSUE THREAD

**Issue by Nidal-J** [flutter/flutter#127305] opened 2023-05-22 09:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just put  many textfields inside listview and see the behavior when focused

### Expected results

text field must rise over keyboard when focused the 

### Actual results

text field not rises over keyboard 

### Code sample

<details><summary>Code sample</summary>

```dart
class TestTextField extends StatelessWidget {
  const TestTextField({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.separated(
        padding: const EdgeInsets.all(20),
        itemCount: 5,
        separatorBuilder: (BuildContext context, int index) {
          return const SizedBox(height: 100);
        },
        itemBuilder: (BuildContext context, int index) {
          return TextFormField(
            initialValue: 'TextFiled #$index',
          );
        },
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/94992280/288c6016-7cd5-45ae-b6b8-1f413ad9bb91

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\nidal\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\nidal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • SM A315G (mobile) • RR8R209LQBK • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 113.0.1774.50

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment] 2023-05-22 12:32
Hi @Nidal-J 
I check this issue on my device `Realme 6, Android 11` but it works as expected

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/76b832c3-cf55-47f5-ab27-c6eadd69e2ce
</details>

From your video, it seems the list is on 2nd page, right? Can you try below minimal sample code to see if the issue still persists or not?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.separated(
        padding: const EdgeInsets.all(20),
        itemCount: 5,
        separatorBuilder: (BuildContext context, int index) {
          return const SizedBox(height: 100);
        },
        itemBuilder: (BuildContext context, int index) {
          return TextFormField(
            initialValue: 'TextFiled #$index',
          );
        },
      ),
    );
  }
}
```
</details>

**Comment by Nidal-J** [comment] 2023-05-22 13:09
Thanks, @huycozy 
I checked your code and it worked just fine as expected
But the problem is still in my code, that's because of the flutter_screenutil package 
I needed to pass the  argument useInheritedMediaQuery = true,
otherwise, the issue will still be found
This only happened after the last upgrade to Flutter 3.10.1

**Comment by huycozy** [comment] 2023-05-23 03:23
Hi @Nidal-J 
Since the issue is related to a 3rd party package (`flutter_screenutil`) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/OpenFlutter/flutter_screenutil/issues) for better support.

Closing, as this isn't an issue with Flutter itself. Thank you!

**Closed by huycozy** 2023-05-23 03:23 UTC
Labels: in triage
