### ISSUE TITLE
"A Timer is still pending even after the widget tree was disposed." assertion is ugly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#53296] opened 2020-03-25 20:10 UTC
We should move the "Pending timers" list into the assert and make the assert just be an exception so that it doesn't include the entire text of the assert code in the message:

```
Pending timers:
Timer (duration: 0:00:10.000000, periodic: true), created:
#0      new _FakeTimer._ (package:quiver/testing/src/async/fake_async.dart:294:42)
#5      FlutterBuildState.startFetchingUpdates (package:app_flutter/state/flutter_build.dart:89:26)
#6      main.<anonymous closure>.<anonymous closure> (file:///home/ianh/dev/cocoon/app_flutter/test/status_grid_test.dart:65:18)
#7      main.<anonymous closure>.<anonymous closure> (file:///home/ianh/dev/cocoon/app_flutter/test/status_grid_test.dart:60:89)
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
#21     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#22     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 31 frames from class _FakeAsync, dart:async, and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1119 pos 12: '() {
      if (   _currentFakeAsync.periodicTimerCount == 0
          && _currentFakeAsync.nonPeriodicTimerCount == 0) {
	return true;
      }
       
      debugPrint('Pending timers:');
      for (final String timerInfo in _currentFakeAsync.pendingTimersDebugInfo) {
	final int firstLineEnd = timerInfo.indexOf('\n');
	assert(firstLineEnd != -1);

	// No need to include the newline.
	final String firstLine = timerInfo.substring(0, firstLineEnd);
	final String stackTrace = timerInfo.substring(firstLineEnd + 1);

	debugPrint(firstLine);
	debugPrintStack(stackTrace: StackTrace.fromString(stackTrace));
	debugPrint('');
      }
      return false;
    }()'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1119:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:716:7)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#14     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#16     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#17     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#22     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#23     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#28     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:\
400:25)
(elided 33 frames from class _AssertionError, class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package\
:stack_trace)

The test description was:
  commits show in the same column (indirectly via StatusGridContainer)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -1: /home/ianh/dev/cocoon/app_flutter/./test/status_grid_test.dart: StatusGrid commits show in the same column (indirectly via StatusGrid\
Container) [E]
  Test failed. See exception logs above.
  The test description was: commits show in the same column (indirectly via StatusGridContainer)
```

**Comment by jibraniqbal666** [comment] 2020-04-07 17:24
can I pick up this issue and resolve it?

**Comment by Hixie** [comment] 2020-04-07 22:05
of course

**Comment by anggun21** [comment] 2020-04-08 08:34
anonsage

**Comment by Inconnu08** [comment] 2020-05-02 07:18
@jibraniqbal666 are you still working on this or can I take it up?

**Comment by SriniVest** [comment] 2020-05-07 11:28
How to reproduce the same error, I am learning flutter, so I would like to reproduce this error in my PC, with Android Studio

**Comment by Hixie** [comment] 2020-05-07 23:04
To repro this, create a `testWidgets` test that just creates a Timer() and doesn't cancel it.

**Comment by hongthong2** [comment] 2020-05-11 18:23
Duplicate of #

**Closed** 2020-05-18 23:20 UTC
Labels: a: error message, a: tests, easy fix, framework
