### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by SpeedyTiger** [flutter/flutter#98445] opened 2022-02-14 22:08 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.428, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
    • Flutter version 2.10.0-1.0.pre.428 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc6fd9e17d (10 days ago), 2022-02-04 18:52:33 +0200
    • Engine revision 2c3ee4895c
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:/Users/khaldoun10/AppData/Local/Android/Sdk/jdk-17/bin
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:/Users/khaldoun10/AppData/Local/Android/Sdk/jdk-17/bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\khaldoun10\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 98.0.1108.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: bc6fd9e17daa803742dc78ef8c3001fde99d37b3
### Plugins
firebase_auth-3.3.7
firebase_auth_web-3.3.7
firebase_core-1.12.0
firebase_core_web-1.5.4

**Comment by danagbemava-nc** [comment] 2022-02-15 08:21
Hi @SpeedyTiger, this is a duplicate of #95916.

If you have any information on how to reproduce or what you were doing when you experienced this issue, kindly provide more details in #95916. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-02-15 08:21 UTC
Labels: in triage
