### ISSUE TITLE
SharePlugin prematurely destroys method channel in onDetachedFromActivity

### ISSUE THREAD

**Issue by meder** [flutter/flutter#66969] opened 2020-09-30 10:52 UTC
We've been getting `MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)` and it seems like SharePlugin isn't handling activity and engine attachment/detachment symmetrically by tearing down method channel in `onDetachedFromActivity()` but only creating it in `onDetachedFromEngine()`. 

SharePlugin fix below appears to fix the issue:

```
@@ -33,8 +33,7 @@ public class SharePlugin implements Flut
 
   @Override
   public void onDetachedFromEngine(FlutterPluginBinding binding) {
-    methodChannel.setMethodCallHandler(null);
-    methodChannel = null;
+    tearDownChannel();
     share = null;
   }
 
@@ -45,7 +44,7 @@ public class SharePlugin implements Flut
 
   @Override
   public void onDetachedFromActivity() {
-    tearDownChannel();
+    share.setActivity(null);
   }
 
   @Override
@@ -66,7 +65,8 @@ public class SharePlugin implements Flut
   }
 
   private void tearDownChannel() {
-    share.setActivity(null);
     methodChannel.setMethodCallHandler(null);
+    methodChannel = null;
+    handler = null;
   }
 }
```

**Comment by darshankawar** [comment] 2020-09-30 12:56
@meder 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Amerr** [comment] 2020-10-08 07:18
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Users/amerrnathmurugan/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/amerrnathmurugan/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

```
@darshankawar

**Comment by jmagman** [comment] 2020-10-22 17:29
@meder Looks like you already investigated.  Want to send the plugin team a [pull request](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md) with your patch?

**Comment by stuartmorgan** [comment] 2021-05-27 14:52
This was fixed in https://github.com/flutter/plugins/pull/3942

**Closed by stuartmorgan** 2021-05-27 14:52 UTC
Labels: P6, a: existing-apps, customer: google, p: first party, p: share, passed first triage, platform-android, plugin
