### ISSUE TITLE
Help please when i want to run my project it doesn't run and gives me these errors.

### ISSUE THREAD

**Issue by MDONEABEL** [flutter/flutter#59840] opened 2020-06-19 08:19 UTC
<details>
  <summary>logs</summary>

```bash
Launching lib\main.dart on SM G610F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\MDONE\Desktop\demoapp\android\app\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method include() for arguments [:flutter_plugin_android_lifecycle] on project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:229:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('/C:/src/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
      final obstruct = navigationBar.fullObstruction == null ||
                                     ^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:230:25: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('/C:/src/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
          navigationBar.fullObstruction;
                        ^^^^^^^^^^^^^^^
Exception: Gradle task assembleDebug failed with exit code 1

```

</details>

**Comment by iapicca** [comment] 2020-06-19 08:54
Hi @MDONEABEL 
From what I can see, the issue is related to the 3rd party plugin [flutter_platform_widgets](https://pub.dev/packages/flutter_platform_widgets) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aqwert/flutter_platform_widgets).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-19 08:54 UTC
