### ISSUE TITLE
[google_maps_flutter] Flutter app crash on iPadOS EXC_BAD_ACCESS (code=2, address=0x16da77ff8)

### ISSUE THREAD

**Issue by samderlust** [flutter/flutter#72821] opened 2020-12-22 18:51 UTC
My flutter app displays a screen with Google Map and a list of Item, the List of Item is updating every 30 secs.
The app is running ok on my android devices, but when it runs on my IPad (iPadOS 14.2) it crashes occasionally after running for a while.

I tried to run the app using Xcode and when it crashes. It shows this:

<img width="878" alt="Screen Shot 2020-12-22 at 1 49 34 PM" src="https://user-images.githubusercontent.com/29016919/102922746-87be2e80-445c-11eb-9396-61d6e8697a78.png">

And this is what from Flutter run -verbose when I run with Vscode

## Steps to Reproduce

MAKE SURE TO RUN THE APP ON DEBUG MODE. BECAUSE THE ISSUE WILL EASILY HAPPEN
run the code below and let the app being idle for 5-10 mins.(set the screen time out to "never" on your iOS device)
after that time of idle. touch on the app and it will crash

```dart
import 'dart:async';
import 'dart:math' show pi;
import 'package:http/http.dart' show Client;
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapTestScreen extends StatefulWidget {
  static final String routeName = '/map_test';
  @override
  _MapTestScreenState createState() => _MapTestScreenState();
}

class _MapTestScreenState extends State<MapTestScreen>
    with TickerProviderStateMixin {
  GoogleMapController _controller;
  Timer _timer;
  double _val = 0.1;

  @override
  void initState() {
    super.initState();

    // _rotateAnimation = Tween<double>();
    _timer = Timer.periodic(Duration(seconds: 20), (_) async {
      final response =
          await Client().get('https://jsonplaceholder.typicode.com/posts');
      print(response.body);
      if (_val >= 1) {
        setState(() {
          _val = 0.1;
        });
      } else {
        setState(() {
          _val += 0.1;
        });
      }
      _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
    });
  }

  @override
  void dispose() {
    super.dispose();
    _timer.cancel();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(75, 74),
              zoom: 4,
            ),
            onMapCreated: (ctl) {
              _controller = ctl;
            },
            onCameraMove: (_) {
              _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
            },
          ),
          for (double i = 2.1; i < 7.0; i += 0.6)
            Positioned(
              top: 100 * i,
              left: 100 * i,
              child: RotatingBox(),
            )
        ],
      ),
    );
  }
}

class RotatingBox extends StatefulWidget {
  RotatingBox({Key key}) : super(key: key);

  @override
  _RotatingBoxState createState() => _RotatingBoxState();
}

class _RotatingBoxState extends State<RotatingBox>
    with TickerProviderStateMixin {
  AnimationController _rotateCtrl;

  @override
  void initState() {
    super.initState();

    _rotateCtrl = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 400),
    )..repeat();
  }

  @override
  void dispose() {
    _rotateCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation: _rotateCtrl,
        builder: (context, snapshot) {
          return Transform.rotate(
            angle: pi * _rotateCtrl.value * 2,
            child: Container(
              height: 60,
              width: 60,
              color: Colors.green,
            ),
          );
        });
  }
}
```

```
[+2194 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/2134A5A2-DFE2-47F4-9562-54FD25D9CEE8/tmp/<my-app-name>)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

```

Basically, it's running normally, and I let the app idle for a while. As soon as I touch on the app. it crashes

My pubspec.yaml
```
name: map_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.2.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

```

```
flutter analyze  
Analyzing <my_flutter_app_name>...                                            
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-CA)
    • Flutter version 1.22.5 at /Users/samderlust/flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/samderlust/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.8.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPad (2) (mobile) • 00008027-001D39002E0A002E • ios • iOS 14.2

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment] 2020-12-23 07:46
Hi @samderlust 
Can you please provide `flutter run --verbose` with crash logs and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by samderlust** [comment] 2020-12-23 12:57
@TahaTesser 
 I just added it. thanks

**Comment by TahaTesser** [comment] 2020-12-28 07:18
Hi @samderlust 
To better address the issue, please create a minimal code sample based on your description. Isolate the code that causes the issue and without using the third-party packages.
Thank you

**Comment by samderlust** [comment] 2021-01-04 15:24
After a while I think the problem come from the Google map plugin since the other screen has the maps crashes as well.
I do a search and think that my problem is the same with  [40650](https://github.com/flutter/flutter/issues/40650)

**Comment by samderlust** [comment] 2021-02-09 19:46
I reopen this issue since I'm able to update the step to reproduce this issue. Please kindly take a look at the first post

**Comment by TahaTesser** [comment] 2021-02-10 09:45
Hi @samderlust 
Here I created a complete runnable code sample from your snippet, using the latest`google_maps_flutter: ^1.2.0` on iPad with `iOS 14.4`, I can't reproduce any crash in  Xcode or VS Code, ran 10 min, no issues 

Please try this code sample with latest `google_maps_flutter: ^1.2.0` (you're using an older version) and provide steps to reproduce 

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:math' show pi;
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    initialRoute: '/',
    routes: {
      '/': (context) => FirstScreen(),
      '/map_test': (context) => MapTestScreen(),
    },
  ));
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Launch screen'),
          onPressed: () {
            // Navigate to the second screen using a named route.
            Navigator.pushNamed(context, MapTestScreen.routeName);
          },
        ),
      ),
    );
  }
}

class MapTestScreen extends StatefulWidget {
  static final String routeName = '/map_test';
  @override
  _MapTestScreenState createState() => _MapTestScreenState();
}

class _MapTestScreenState extends State<MapTestScreen>
    with TickerProviderStateMixin {
  GoogleMapController _controller;
  Timer _timer;
  double _val = 0.1;

  @override
  void initState() {
    super.initState();

    // _rotateAnimation = Tween<double>();
    _timer = Timer.periodic(Duration(seconds: 20), (_) {
      if (_val >= 1) {
        setState(() {
          _val = 0.1;
        });
      } else {
        setState(() {
          _val += 0.1;
        });
      }
      _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
    });
  }

  @override
  void dispose() {
    super.dispose();
    _timer.cancel();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(75, 74),
              zoom: 4,
            ),
            onMapCreated: (ctl) {
              _controller = ctl;
            },
            onCameraMove: (_) {
              _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
            },
          ),
          for (double i = 2.1; i < 7.0; i += 0.6)
            Positioned(
              top: 100 * i,
              left: 100 * i,
              child: RotatingBox(),
            )
        ],
      ),
    );
  }
}

class RotatingBox extends StatefulWidget {
  RotatingBox({Key key}) : super(key: key);

  @override
  _RotatingBoxState createState() => _RotatingBoxState();
}

class _RotatingBoxState extends State<RotatingBox>
    with TickerProviderStateMixin {
  AnimationController _rotateCtrl;

  @override
  void initState() {
    super.initState();

    _rotateCtrl = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 400),
    )..repeat();
  }

  @override
  void dispose() {
    _rotateCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation: _rotateCtrl,
        builder: (context, snapshot) {
          return Transform.rotate(
            angle: pi * _rotateCtrl.value * 2,
            child: Container(
              height: 60,
              width: 60,
              color: Colors.green,
            ),
          );
        });
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>



Thank you

**Comment by samderlust** [comment] 2021-02-10 11:43
Yeah, This issue is not happen all the time. Some time it happen really soon some time it takes a while to happen. 
Last time I test this I was using maps_flutter: 1.2.0

**Comment by samderlust** [comment] 2021-02-10 13:51
I've ran it 2 times this morning and it happened after around 10-15 mins maybe. I added fetching API into the code so it could  happen easier.
In addition, I run on iPad Pro 11. the screen refresh rate could affect this issue to happen more frequently than normal iPad?
Since it doest happen as frequent as on my iPhone Xs

**Comment by TahaTesser** [comment] 2021-02-11 08:19
Hi @samderlust 
I just doubled the rotating square still has no issue when running on physical iPad on iOS 14.4
Can you please update the example that could reproduce the crash reliably? fetching any open-source test API? 
Thank you

**Comment by samderlust** [comment] 2021-02-12 17:44
Hi, I've created a new app for testing this and still getting same issue even run on Vscode or Xcode.
There's nothing clear for me on how to make it crash. But basically just let the app run for awhile(5,10, 15,.. mins) and then touch the app again. it crashes.
Below is the code

```
import 'dart:async';
import 'dart:math' show pi;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:http/http.dart' show Client;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MapTestScreen(),
    );
  }
}

class MapTestScreen extends StatefulWidget {
  @override
  _MapTestScreenState createState() => _MapTestScreenState();
}

class _MapTestScreenState extends State<MapTestScreen>
    with TickerProviderStateMixin {
  GoogleMapController _controller;
  Timer _timer;
  double _val = 0.1;

  @override
  void initState() {
    super.initState();

    // _rotateAnimation = Tween<double>();
    _timer = Timer.periodic(Duration(seconds: 20), (_) async {
      final response =
          await Client().get('https://jsonplaceholder.typicode.com/posts');
      print(response.body);
      if (_val >= 1) {
        setState(() {
          _val = 0.1;
        });
      } else {
        setState(() {
          _val += 0.1;
        });
      }
      _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
    });
  }

  @override
  void dispose() {
    super.dispose();
    _timer.cancel();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(75, 74),
              zoom: 4,
            ),
            onMapCreated: (ctl) {
              _controller = ctl;
            },
            onCameraMove: (_) {
              _controller.getLatLng(ScreenCoordinate(x: 1, y: 1));
            },
          ),
          for (double i = 1.1; i < 10.0; i += 0.8)
            Positioned(
              top: 100,
              left: 100 * i,
              child: RotatingBox(),
            )
        ],
      ),
    );
  }
}

class RotatingBox extends StatefulWidget {
  RotatingBox({Key key}) : super(key: key);

  @override
  _RotatingBoxState createState() => _RotatingBoxState();
}

class _RotatingBoxState extends State<RotatingBox>
    with TickerProviderStateMixin {
  AnimationController _rotateCtrl;

  @override
  void initState() {
    super.initState();

    _rotateCtrl = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 400),
    )..repeat();
  }

  @override
  void dispose() {
    _rotateCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation: _rotateCtrl,
        builder: (context, snapshot) {
          return Transform.rotate(
            angle: pi * _rotateCtrl.value * 2,
            child: Container(
              height: 60,
              width: 60,
              color: Colors.green,
            ),
          );
        });
  }
}
```

# App Screenshot
![IMG_0024](https://user-images.githubusercontent.com/29016919/107802736-bc00ed80-6d2f-11eb-8f70-fa8049d7fb88.PNG)

# Xcode screenshot
![Screen Shot 2021-02-12 at 12 42 36 PM](https://user-images.githubusercontent.com/29016919/107802791-ca4f0980-6d2f-11eb-89f0-a26071ba33f3.png)

![Screen Shot 2021-02-12 at 12 43 05 PM](https://user-images.githubusercontent.com/29016919/107802852-dcc94300-6d2f-11eb-8ebb-983da904027c.png)

![Screen Shot 2021-02-12 at 12 43 30 PM](https://user-images.githubusercontent.com/29016919/107802904-eb175f00-6d2f-11eb-87bb-9bb9f2d3f586.png)

![Screen Shot 2021-02-12 at 12 43 59 PM](https://user-images.githubusercontent.com/29016919/107802958-fc606b80-6d2f-11eb-8528-c765f9ed5c51.png)

**Comment by TahaTesser** [comment] 2021-02-15 08:13
Hi @samderlust 
Tried to reproduce again using your updated code sample on iPad 8 running `iOS 14.4`

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS 14.4
    • iPhone 12 (mobile)   • FE087B7C-047B-40A9-AAEF-34B4AB9B4B1B • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
! Doctor found issues in 3 categories.
```

</details>


Ran the app for 20 mins (two times, once in VS Code and once in Xcode), no crash
Since it's reproducible for you on iPad, I feel safe to label this 
Thank you

**Comment by samderlust** [comment] 2021-02-16 13:56
Hi @TahaTesser  this happens quite consistently on my iPad Pro. It takes a longer time on my iPhone. I'm thinking if the refresh rate could be an impact? (since iPad Pro has the refresh rate of 120 fps).
When you run the app, could you try to move the map a round at first. and then let the app idle for a while before touching it again. That's how the app crashes every time  on my end.

**Comment by samderlust** [comment] 2021-03-09 15:01
I'm now using the fix at https://github.com/flutter/plugins/pull/3426 and see if it solves the problem

**Comment by samderlust** [comment] 2021-03-11 02:24
I'm closing this since https://github.com/flutter/plugins/pull/3426 solved my issue

**Comment by TahaTesser** [comment] 2021-03-11 13:58
@samderlust 
Let's wait for PR to get merged

**Comment by darshankawar** [comment] 2024-08-01 11:17
The linked PR was merged and there have been no similar reports since, so I will safely close this as resolved.
If anybody still sees a similar issue, please file a new issue with relevant details.

**Closed by darshankawar** 2024-08-01 11:17 UTC
Labels: c: crash, e: device-specific, platform-ios, waiting for PR to land (fixed), a: tablet, p: maps, package, P2, c: fatal crash, team-ios, triaged-ios
