### ISSUE TITLE
video_player plugin doesn't "stop" when hot restarted

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#25486] opened 2018-12-17 23:22 UTC
Running the video demo in the Flutter gallery in debug mode generates a pair of console messages every couple of seconds:
```
I/OMXClient(22602): IOmx service obtained
I/ACodec  (22602): codec does not support config priority (err -2147483648)
```
(FWIW the second message appears to be coming from https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/ACodec.cpp)

If the gallery demo is hot-restarted, this pair of messages continues ad nauseum, even though the video demo was not launched again.

**Comment by lifenautjoe** [comment] 2019-08-28 16:13
Any way to properly clean up the player so far?

**Comment by abderrahmen13** [comment] 2020-06-03 16:05
any solution ?

**Comment by maheshmnj** [comment] 2021-06-25 10:43
Hi @HansMuller,
Thanks for filing the issue is this still valid ? Considering the issue was filed long ago. I checked the[ gallery app](https://github.com/flutter/gallery) I could see that video player plugin is not being used there.  

I also ran the [video_player plugin samples](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example) to verify this issue and I can no longer reproduce it.

**Comment by TahaTesser** [comment] 2021-07-16 12:19
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-16 12:19 UTC
Labels: P4, a: video, p: first party, p: video_player, plugin
