### ISSUE TITLE
Cannot retrieve file length from file

### ISSUE THREAD

**Issue by xzqbetter** [flutter/flutter#53907] opened 2020-04-03 08:35 UTC
When I want to read the length of a mov file from iPhone, it catches the error: 

```txt
Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '/private/var/mobile/Containers/Data/PluginKitPlugin/E78182C6-A8B9-4FF8-92A5-BCE5A0FE1327/tmp/trim.58693B0C-965E-4B5B-AEF5-D97EA6699471.MOV' (OS Error: Operation not permitted, errno = 1)

**Comment by iapicca** [comment] 2020-04-03 08:46
Hi @xzqbetter 
I'm assuming you are using [path_provider](https://pub.dev/packages/path_provider);
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by xzqbetter** [comment] 2020-04-03 09:13
Hi @iapicca 

I'm  using the `image_picker`, the error happens when method `file.length()` calls
- image file works normal
- but mov file crash

my code
```dart
File file = await ImagePicker.pickVideo(source: ImageSource.gallery);
int len = await file.length();
```

flutter doctor -v
```txt
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/wsy/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wsy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • “way”的 iPhone     • 94a4f8393e082c4a5b677131684ac363726467b0 • ios • iOS 13.1.3
```

**Comment by iapicca** [comment] 2020-04-03 11:27
Hi again @xzqbetter 
thank you for your `flutter doctor -v` , 
can you please provide your `flutter run --verbose`
and your `pubspec.yaml` as well 
Thank you

**Comment by iapicca** [comment] 2020-04-24 11:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by FFChyan** [comment] 2020-05-20 02:52
Hi @iapicca ,
I get the same error. I use `image_picker` too, and the error happens when I try to upload a video using MultipartFile.fromFile(). Here is the code samle:

```
File _video;
_getVideoFromGallery() async {
  File video = await ImagePicker.pickVideo(source: ImageSource.gallery);
  _video = video;
}
```

```
try {
  Response response = await Dio().post(
    url,
    queryParameters: {},
    data: FormData.fromMap({
      "file": await MultipartFile.fromFile(
          _video.path.replaceAll('file://', ''),)  // iOS platform may need to modify the path like this
    }),
  );
} catch (e) {
}
```

pubspec.yaml

```
name: citizen_science
description: A new Flutter login application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flushbar: ^1.9.1
  ant_icons: ^1.0.0
  font_awesome_flutter: ^8.7.0
  fluttertoast: ^3.1.3
  dio: ^3.0.9
  image_picker: 0.5.4+3
  carousel_pro: ^1.0.0
  flutter_custom_dialog: ^1.0.16
  json_annotation: ^2.0.0
  provider: ^4.0.5
  video_player: ^0.10.11
  chewie: ^0.9.10

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/travel.jpeg
    - assets/images/twitter.png
    - assets/images/background.png
```

flutter doctor -v 

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.15.17 at /Library/flutter
    • Framework revision 2294d75bfa (2 个月前), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ivory/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/ivory/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/ivory/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Users/ivory/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • Yifu       • 00008030-000458E134D0802E • ios            • iOS 13.4
    • Chrome     • chrome                    • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server                • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

Flutter run --verbose
Some outputs near the error:

```
[ +140 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Zmx1dHRlcjogc3VibWl0X2lkPXtzdWJtaXRfaWQ6IDM4NH0=}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Cg==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Zmx1dHRlcjogX2RhdGFJbmZvTGlzdC5sZW5ndGg9MQ==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Cg==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Zmx1dHRlcjog5Lyg6KeG6aKR}}
[        ] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055313, bytes: Cg==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055320, bytes:
Zmx1dHRlcjog6KeG6aKR5Y+R6YCB5aSx6LSl77yaRmlsZVN5c3RlbUV4Y2VwdGlvbjogQ2Fubm90IHJldHJpZXZlIGxlbmd0aCBvZ
iBmaWxlLCBwYXRoID0gJy9wcml2YXRlL3Zhci9tb2JpbGUvQ29udGFpbmVycy9EYXRhL1BsdWdpbktpdFBsdWdpbi9CMTVFOTNCRi
03Q0QzLTQ5NTktQjgwRC1FNDhCQjYwNTMzNTcvdG1wL3RyaW0uOUFFNkJDRTctRUEwMC00NzhELUFEOEMtNzY4RjIwNjkxQjUxLk1
PVicgKE9TIEVycm9yOiBPcGVyYXRpb24gbm90IHBlcm1pdHRlZCwgZXJybm8gPSAxKQ==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942055320, bytes: Cg==}}
[        ] flutter: FileSystemException: Cannot retrieve length of file, path =
'/private/var/mobile/Containers/Data/PluginKitPlugin/B15E93BF-7CD3-4959-B80D-E48BB6053357/tmp/trim.9A
E6BCE7-EA00-478D-AD8C-768F20691B51.MOV' (OS Error: Operation not permitted, errno = 1)
[+3001 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942058326, bytes: Zmx1dHRlcjogZGVidWcgX3N1Ym1pdENvbnRyb2xsZXIucmV2ZXJzZSgpOw==}}
[   +1 ms] flutter: debug _submitController.reverse();
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate:
{type: @Isolate, id: isolates/3395607265613131, name: main, number: 3395607265613131}, timestamp:
1589942058327, bytes: Cg==}}
```

Could you please reopen the issue? Any solutions or suggestions are welcome! 

Thanks.

**Comment by FFChyan** [comment] 2020-05-20 02:58
Sorry for not openning a new issue, because @xzqbetter and I both run on iPhone, iOS 13. Also the error messages are the same. So I guess it might be the same problem.

**Comment by xzqbetter** [comment] 2020-05-20 05:30
@FFChyan @iapicca 
it seems to be the problem of ios version, in the higher ios version, the file permission are stricter
so try to update the `image_picker` to the newest version, it works normal

**Comment by iapicca** [comment] 2020-05-20 06:22
Hi @FFChyan  
I see you are using an obsolete version of both flutter and [image_picker](pub.dev/packages/image_picker)
please run flutter upgrade --force and 
update image_picker's version on your pubspec.yaml;
if the issue persists 
please provide your updated `flutter doctor -v` , 
your updated `pubspec.yaml` 
and a reproducible minimal code sample
that doesn't contains 3rd party plugins 
Thank you

**Comment by TahaTesser** [comment] 2020-06-12 13:11
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-12 13:11 UTC
Labels: in triage, waiting for customer response

**Comment by ArvindMewada** [comment] 2020-09-16 12:59
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = '(/data/user/0/com.docvita.consult/cache/file_picker/Offer Letter (1).pdf)' (OS Error: No such file or directory, errno = 2)`

**Comment by surhidamatya** [comment] 2021-01-27 07:35
ran into the same issue:
`flutter doctor -v` output
`[✓] Flutter (Channel master, 1.24.0-8.0.pre.147, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.147 at /Users/lf/flutter
    • Framework revision f04b3d917f (3 months ago), 2020-11-07 16:09:02 -0500
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lf/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
`

`pubspec.yaml` file

`name: file_chunk
description: File chunk

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  file_picker: ^2.1.0
  chunked_stream: ^1.1.0
  crypto: ^2.1.5
  flutter_uploader: ^1.2.1
  flutter_downloader: ^1.5.2
  image_picker: ^0.6.7+21
  dio: ^3.0.10
  provider: ^4.3.2+3
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
`

**Comment by TahaTesser** [comment] 2021-01-27 11:10
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
