### ISSUE TITLE
[Windows] Problem with the Input filed

### ISSUE THREAD

**Issue by jablonskipj** [flutter/flutter#44516] opened 2019-11-09 16:09 UTC
**Description**

Hey. I use the [Desktop project](https://github.com/google/flutter-desktop-embedding) to implement my own application using Flutter. I have encountered a problem with the Input fields on windows. The main problem that I have is that the cursor is switching the position randomly while using the numeric keyboard. This leads to a situation when typing for example `123` on the keyboard I can see `132` in the input field. Unfortunately, `onChange` function gives me the same result (the sequence is the same as the value that I can see in the input field), so I am not able to easily distinguish if I should reorganize the String manually.

**Steps to reproduce**

- Implement a small input field in the application
- run the app on Windows
- type something into the field with the use of numeric keyboard
- see the result where string in the input is different than the one you typed on the keyboard.

**Comment by stuartmorgan** [comment] 2020-03-24 13:43
Duplicate of #51431
(Duping to the newer bug since it has a detailed description of exactly what is happening.)

**Closed by stuartmorgan** 2020-03-24 13:43 UTC
Labels: a: desktop, engine, framework, ❖ platform-windows
