### ISSUE TITLE
Future.wait crashes when mixing Future and SynchronousFuture

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#71554] opened 2020-12-02 11:46 UTC
Following Flutter application code raises **_LateInitializationError (LateInitializationError: error)** exception:

```dart
Future main() async {
  await Future.wait([
    Future.delayed(Duration(milliseconds: 500)),
    SynchronousFuture(null),
  ]);
}
```

Workaround:

```dart
Future main() async {
  await Future.wait([
    Future.delayed(Duration(milliseconds: 500)),
    SynchronousFuture(null),
  ].where((f) => f is! SynchronousFuture));
}
```

**Comment by TahaTesser** [comment] 2020-12-02 12:26
Hi @PavelPZ 
Thanks for filing the issue

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.406, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.406 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 60bdcf55fe (7 hours ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (6 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • 78A5C06E-F69B-4D9D-9D6D-01389ADC306C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)     • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.67

• No issues found!
```

</details>

**Comment by lrhn** [comment] 2020-12-02 16:15
Don't use `SynchronousFuture`. It's inherently incompatible with the specified `Future` semantics, and any code written to assume correct `Future` semantics can behave in unspecified ways if it gets a `SynchronousFuture`.
(For experts only: Use `SynchronousFuture` only when you're the only on ever calling `then` on it, because then it's up to you to handle the incorrect behavior).

A `Future` *must not* call a callback in response to calling `then`/`catchError`/`whenComplete`. That allows code to set up callbacks and prepare for the result event in any order. This was the *first* feedback we got on the original `Future` design, it was simply too unpredictable and error-prone to call the callbacks immediately.
What happens here is that `Future.wait` goes through every future passed to it and calls `then` on it. Then, after having *counted* the number of futures, it allocates a list to capture the results. The synchronous future does a callback at the wrong time and the code tries to store a result into a yet-unallocated list, which causes the error. The fault is entirely caused by the behavior of `SynchronousFuture`.

**Comment by PavelPZ** [comment] 2020-12-02 17:57
I used it because the documentation says **"This class is useful in cases where you want to expose a single API, where
you normally want to have everything execute synchronously, but where on
rare occasions you want the ability to switch to an asynchronous model"**, which is exactly my case.

```SynchronousFuture``` is also recommended as a return from ```RouterDelegate.setInitialRoutePath``` /  ```RouterDelegate.setNewRoutePath```.

OK, I will avoid any use of `` SynchronousFuture``` and modify my code according to this pattern:

```
Future main() async {
  await Future.wait([
    Future.delayed(Duration(milliseconds: 500)), // pseudocode for async result
    null, // pseudocode for sync result
  ].where((f) => f != null));
}
```

**Comment by lrhn** [comment] 2020-12-03 13:01
Not using `SynchronousFuture` is a good choice, but I have bad news on the workaround. With null safety, the argument to `Future.wait<T>` must be an `Iterable<Future<T>>`, so you can't use `null` as value. You'll have to rewrite that again when you migrate to null safety, so you might as well do it now.

I highly recommend to just treat things that are sometimes asynchronous as always asynchronous. (Unless you have measurements proving that that is what is making your application too slow, then it might be worth adding the extra complexity of having an additional synchronous code path).

**Comment by PavelPZ** [comment] 2020-12-03 15:19
@lrhn thanks a lot, I will use pure asynchronous  solution.

**Comment by Piinks** [comment] 2022-06-16 23:15
@PavelPZ it sounds like your issue was resolved, so I am going to close this. If that is not the case, let us know and we will reopen it. Thank you!

**Closed by Piinks** 2022-06-16 23:15 UTC
Labels: framework, dependency: dart, a: error message, has reproducible steps, found in release: 1.24
