### ISSUE TITLE
Colorfilter matrix

### ISSUE THREAD

**Issue by lubritto** [flutter/flutter#19468] opened 2018-07-17 12:57 UTC
current just have color and blend mode, we need a colorfilter.matrix to change brightness, saturation and contrast of image for example..

**Comment by lubritto** [comment] 2018-12-03 17:59
@zoechi Any update ? This will permit so much things, like an image editor.. It will be a nice feature

**Comment by dnfield** [comment] 2019-01-14 06:19
Duplicate of https://github.com/flutter/flutter/issues/6688

**Closed by dnfield** 2019-01-14 06:19 UTC
Labels: framework, severe: new feature
