### ISSUE TITLE
About behavior when navigator.push with StatelessWidget

### ISSUE THREAD

**Issue by sh-ogawa** [flutter/flutter#45238] opened 2019-11-20 08:02 UTC
## Steps to Reproduce

1. My StatelessWidget run Navigator.push on tap button.
2. Switch to a new page.
At this time, the StatelessWidget that was somehow Navigator.pushed is rebuilt.
3. My StatelessWidget have FutureBuilder, so running function.

This function is expensive because it uses HTTP and SQLite' retrieve.
I want to prevent the StatelessWidget from being rebuilt when navigator.pop.

**Target Platform: Android
**Target OS version/browser: Android 10
**Devices: Pixel 3a

```
flutter doctor -v
[√] Flutter (Channel unknown, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.476], locale ja-JP)
    • Flutter version 1.9.1+hotfix.2 at C:\tools\flutter
    • Framework revision 2d2a1ffec9 (2 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\sh-ogawa\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593

[!] VS Code, 32-bit edition (version 1.38.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Pixel 3a • 96PAY0YLSB • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

Using IDE is Android Studio.

**Comment by iapicca** [comment] 2019-11-20 10:55
<details>
  <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: FirstRoute(),
    );
  }
}

// https://flutter.dev/docs/cookbook/navigation/navigation-basics
// change to stateful

class FirstRoute extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<FirstRoute> {

  @override
  void initState() {
    super.initState();
    print('FirstRoute initState');
  }

  @override
  void dispose() {
    super.dispose();
    print('FirstRoute dispose');
  }

  @override
  Widget build(BuildContext context) {
    print('FirstRoute build');
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            print('FirstRoute pushing');
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {

    @override
  void initState() {
    super.initState();
    print('SecondRoute initState');
  }

  @override
  void dispose() {
    super.dispose();
    print('SecondRoute dispose');
  }

  @override
  Widget build(BuildContext context) {
    print('SecondRoute build');
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            print('SecondRoute popping');
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>logs</summary>

```
/flutter (12514): FirstRoute build
I/flutter (12514): FirstRoute pushing
I/flutter (12514): SecondRoute initState
I/flutter (12514): SecondRoute build
I/flutter (12514): FirstRoute build
I/flutter (12514): SecondRoute popping
I/flutter (12514): FirstRoute build
I/flutter (12514): SecondRoute dispose
I/flutter (12514): FirstRoute pushing
I/flutter (12514): SecondRoute initState
I/flutter (12514): SecondRoute build
I/flutter (12514): FirstRoute build
```

</details>

Hi @sh-ogawa 
thank you for your contribution

**Comment by goderbauer** [comment] 2019-11-20 22:58
Looks like a duplicate of https://github.com/flutter/flutter/issues/11655.

**Closed by goderbauer** 2019-11-20 22:58 UTC
Labels: dependency: android, f: routes, framework

**Comment by jonataslaw** [comment] 2019-11-21 04:42
> ## Steps to Reproduce
> 1. My StatelessWidget run Navigator.push on tap button.
> 2. Switch to a new page.
>    At this time, the StatelessWidget that was somehow Navigator.pushed is rebuilt.
> 3. My StatelessWidget have FutureBuilder, so running function.
> 
> This function is expensive because it uses HTTP and SQLite' retrieve.
> I want to prevent the StatelessWidget from being rebuilt when navigator.pop.
> 
> **Target Platform: Android
> **Target OS version/browser: Android 10
> **Devices: Pixel 3a
> 
> ```
> flutter doctor -v
> [√] Flutter (Channel unknown, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.476], locale ja-JP)
>     • Flutter version 1.9.1+hotfix.2 at C:\tools\flutter
>     • Framework revision 2d2a1ffec9 (2 months ago), 2019-09-06 18:39:49 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
>     • Android SDK at C:\Users\sh-ogawa\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2019.1)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
>     • Flutter plugin version 39.0.3
>     • Dart plugin version 191.8593
> 
> [!] VS Code, 32-bit edition (version 1.38.1)
>     • VS Code at C:\Program Files (x86)\Microsoft VS Code
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (1 available)
>     • Pixel 3a • 96PAY0YLSB • android-arm64 • Android 10 (API 29)
> 
> ! Doctor found issues in 2 categories.
> ```
> 
> Using IDE is Android Studio.

Use this package 
https://pub.dev/packages/get

or await my pull be aproved 

https://github.com/flutter/flutter/pull/44731
