### ISSUE TITLE
provide a way to prevent DataRow to receive focus between rows up and down using up and down keys

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#74184] opened 2021-01-18 09:08 UTC
i want to move focus between rows up and down using keyboard Up and Down Keys .

<details>
<summary>code sample</summary>

```dart
return DataTable(
      columns: const <DataColumn>[
        DataColumn(
          label: Text(
            'Name',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Qty',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
      ],
      rows: const <DataRow>[
        DataRow(
          cells: <DataCell>[
            DataCell(
            TextField(
            )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
      ],
    );
```
</details>

**Comment by pedromassangocode** [comment] 2021-01-18 09:28
Hi @abdulrehmananwar 
Can you please elaborate a little bit more about this proposal? It is quite vague and hard to understand.
Thank you

**Comment by abdulrehmananwar** [comment] 2021-01-18 09:34
below is piece of code i want when i press keyboard down key then focus will be shift to below row same column. and when i press keyboard up key focus shift to up row same column.


return DataTable(
      columns: const <DataColumn>[
        DataColumn(
          label: Text(
            'Name',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Qty',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
      ],
      rows: const <DataRow>[
        DataRow(
          cells: <DataCell>[
            DataCell(
            TextField(
            )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(
                TextField(
                )),
            DataCell(
                TextField(
                )),
          ],
        ),
      ],
    );

**Comment by MrBirb** [comment] 2021-01-18 11:01
Looks like a duplicate of [#74022](https://github.com/flutter/flutter/issues/74022)

**Comment by pedromassangocode** [comment] 2021-01-18 14:02
> below is piece of code i want when i press keyboard down key then focus will be shift to below row same column. and when i press keyboard up key focus shift to up row same column.

For this use-case it is not possible because you have have a text field between in the same Row, so before the focus goes to the next Row it will move to the next text field first.

I guess you can currently do that by: first, detecting the key pressed and then move the focus to the next Row (or the first text field in it).

This is definitely similar to https://github.com/flutter/flutter/issues/74022.

Thank you

**Closed by pedromassangocode** 2021-01-18 14:02 UTC
Labels: in triage
