### ISSUE TITLE
Flutter Web : platformViewRegistry reference error with v1.18.0-11.1pre

### ISSUE THREAD

**Issue by bgrgv** [flutter/flutter#60529] opened 2020-06-29 16:46 UTC
Steps to reproduce :

```Dart
import 'dart:ui' as ui;
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;
// ignore: avoid_web_libraries_in_flutter
.
.
ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement,
    );
```

**Expected results:** 
Should show no errors. It works fine in v1.15 beta

**Actual results:** 

<details>
  <summary>Logs</summary>

```
The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix.
Try correcting the prefix or importing the library that defines 'platformViewRegistry'.
```

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (7 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\blesi\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\blesi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2020-06-30 09:19
duplicate of https://github.com/flutter/flutter/issues/41563

**Closed by TahaTesser** 2020-06-30 09:19 UTC
