### ISSUE TITLE
[camera][android]Occasionally crashes while recording

### ISSUE THREAD

**Issue by suli1** [flutter/flutter#71533] opened 2020-12-02 06:07 UTC
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
       at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:1919)
       at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:323)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:197)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by darshankawar** [comment] 2020-12-02 07:58
@suli1 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with devices on which you are seeing this crash.
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-23 09:19
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:19 UTC
Labels: in triage, waiting for customer response

**Comment by tgpsantos** [comment] 2021-01-26 17:07
@suli1 did you figure out what the problem was?
