### ISSUE TITLE
Rejecting re-init on previously-failed  androidx.media3.exoplayer.ExoPlayerImpl Unsupported profile 4 for video/mp4v-es

### ISSUE THREAD

**Issue by yemin82** [flutter/flutter#159599] opened 2024-11-29 02:14 UTC
### Steps to reproduce

1.android sdk 22
2.
https://nos.netease.com/cloudmusic/obj/wovChMODwrLCnGzCncOh/20509600883/5540/20229155412/1adb6e03b31712b7a6ea294d24759577.mp4

3.android sdk 23 is no bug

### Expected results

```
  @override
  Widget build(BuildContext context) {
    return VideoPlayer(VideoPlayerController.networkUrl(Uri.parse("https://nos.netease.com/cloudmusic/obj/wovChMODwrLCnGzCncOh/20509600883/5540/20229155412/1adb6e03b31712b7a6ea294d24759577.mp4"))..initialize()..play());
  }
```

### Actual results

Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.ExoPlayerImpl

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on sdk google atv x86 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Connecting to VM Service at ws://127.0.0.1:52783/OZbQ4f-OXYY=/ws
Connected to the VM Service.
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.ExoPlayerImpl$NoSuitableOutputPlaybackSuppressionAudioDeviceCallback>
I/ExoPlayerImpl( 6632): Init 277fc309 [AndroidXMedia3/1.4.1] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MetadataUtil( 6632): Skipped unknown metadata entry: desc
I/VideoCapabilities( 6632): Unsupported profile 4 for video/mp4v-es
D/MediaCodecInfo( 6632): NoSupport [codec.profileLevel, avc1.640032, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
D/MediaCodecInfo( 6632): NoSupport [codec.profileLevel, avc1.640032, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.audio.AudioCapabilitiesReceiver$AudioDeviceCallbackV23>
I/OMXClient( 6632): Using client-side OMX mux.
W/OMXNodeInstance( 6632): [1:google.h264.decoder] component does not support metadata mode; using fallback
E/ACodec  ( 6632): [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter$$ExternalSyntheticLambda0>
I/art     ( 6632): Rejecting re-init on previously-failed class java.lang.Class<androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter$$ExternalSyntheticLambda0>
D/MediaCodecInfo( 6632): NoSupport [codec.profileLevel, avc1.640032, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
W/MediaCodecRenderer( 6632): Format exceeds selected codec's capabilities [id=1, mimeType=video/avc, codecs=avc1.640032, res=1920x1080, color=NA/NA/NA/8/8, fps=25.0, OMX.google.h264.decoder]
I/OMXClient( 6632): Using client-side OMX mux.
I/SoftAAC2( 6632): limiting to stereo output
E/SoftAVC ( 6632): Decoder failed: -2
E/ACodec  ( 6632): [OMX.google.h264.decoder] ERROR(0x80001001)
E/ACodec  ( 6632): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 6632): Codec reported err 0x80001001, actionCode 0, while in state 6
E/MediaCodecVideoRenderer( 6632): Video codec error
E/MediaCodecVideoRenderer( 6632):   java.lang.IllegalStateException
E/MediaCodecVideoRenderer( 6632):       at android.media.MediaCodec.getBuffer(Native Method)
E/MediaCodecVideoRenderer( 6632):       at android.media.MediaCodec.getInputBuffer(MediaCodec.java:1428)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.getInputBuffer(SynchronousMediaCodecAdapter.java:126)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1320)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/MediaCodecVideoRenderer( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/MediaCodecVideoRenderer( 6632):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/MediaCodecVideoRenderer( 6632):       at android.os.Looper.loop(Looper.java:135)
E/MediaCodecVideoRenderer( 6632):       at android.os.HandlerThread.run(HandlerThread.java:61)
D/MediaCodecInfo( 6632): NoSupport [codec.profileLevel, avc1.640032, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, sdk_google_atv_x86, unknown, 22]
E/ExoPlayerImplInternal( 6632): Playback error
E/ExoPlayerImplInternal( 6632):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640032, -1, null, [1920, 1080, 25.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal( 6632):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6632):       at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 6632):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6632):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.h264.decoder
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal( 6632):       ... 3 more
E/ExoPlayerImplInternal( 6632):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal( 6632):       at android.media.MediaCodec.getBuffer(Native Method)
E/ExoPlayerImplInternal( 6632):       at android.media.MediaCodec.getInputBuffer(MediaCodec.java:1428)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.getInputBuffer(SynchronousMediaCodecAdapter.java:126)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1320)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/ExoPlayerImplInternal( 6632):       ... 6 more
E/ExoPlayerImplInternal( 6632): Disable failed.
E/ExoPlayerImplInternal( 6632):   java.lang.IllegalStateException
E/ExoPlayerImplInternal( 6632):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal( 6632):       at android.media.MediaCodec.flush(MediaCodec.java:662)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
E/ExoPlayerImplInternal( 6632):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
E/ExoPlayerImplInternal( 6632):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6632):       at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 6632):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/flutter ( 6632): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640032, -1, null, [1920, 1080, 25.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)
E/flutter ( 6632):
I/art     ( 6632): Debugger is no longer active

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.24.5, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
    ! Warning: `flutter` on your path resolves to /Library/Google/flutter/bin/flutter, which is not inside your current Flutter SDK checkout
      at /library/google/flutter. Consider adding /library/google/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Library/Google/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /library/google/flutter. Consider adding /library/google/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2024-11-29 07:36
Hi @yemin82, are you running this on an emulator? If so, did you create the emulator from android studio or are you using a third-party service?

**Comment by yemin82** [comment] 2024-11-29 07:37
> Hi @yemin82, are you running this on an emulator? If so, did you create the emulator from android studio or are you using a third-party service?

yes！from android studio

**Comment by danagbemava-nc** [comment] 2024-11-29 07:41
Then this is not a bug in the video_player plugin. This is an issue with the emulator itself. The native media player library only supports from android 23 onwards. See the Emulators section on this page

https://developer.android.com/media/media3/exoplayer/supported-devices

Closing from here as this is a bug in the emulator. 

Thank you

**Closed by danagbemava-nc** 2024-11-29 07:41 UTC
Labels: in triage

**Comment by yemin82** [comment] 2024-11-29 07:44
There are also problems in TV, which used to be okay, but recently I found out that there was a problem

**Comment by yemin82** [comment] 2024-11-29 07:46
But that's really not a bug in flutter
