### ISSUE TITLE
Regression in keyboardAppearance on iOS with Flutter 3.24?

### ISSUE THREAD

**Issue by arnab** [flutter/flutter#158439] opened 2024-11-11 03:02 UTC
### Steps to reproduce

I have a few `CupertinoSearchTextField` widgets in my app.

I upgraded from Flutter `3.22.3` to `3.24.4` recently. I am noticing that:

* Even with the iOS system appearance set to **dark**
* The app always shows the keyboard in light mode
* Until I upgraded to `3.24.4`, it used to follow the system appearance
* I can install previous versions of the app (from TestFlight) and see this difference

Is this a change/regression in the stable release?

### Other notes
* On Android, it correctly follows the system appearance, before and after the Flutter 3.24.4 upgrade

### Expected results

Keyboard shown using `CupertinoSearchTextField` should follow the system appearance.

### Actual results

On iOS, keyboard shown using `CupertinoSearchTextField` always shows in light mode.

### Code sample

<details open><summary>Code sample</summary>

```dart
      CupertinoSearchTextField(
        controller: textEditingController,
        autofocus: _searchHasFocus(searchState),
        onTap: () => _enableFocus(searchController),
        onSubmitted: (val) => _submitSearch(searchController, val),
        suffixMode: OverlayVisibilityMode.editing,
        onSuffixTap: () =>
            _clearSearchTextField(textEditingController, searchController),
        placeholder: hintText,
        prefixIcon: searchIcon(context),
        prefixInsets: const EdgeInsets.only(left: 8),
        style: Theme.of(context).textTheme.bodyLarge,
        suffixIcon: Icon(
          CupertinoIcons.xmark_circle_fill,
          size: 20,
          color: Theme.of(context).hintColor,
        ),
      );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| Flutter 3.22.3 | Flutter 3.24.4 |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/cdf0cd00-dc7b-469f-a732-e3801d6a8069" width="35%" /> | <img src="https://github.com/user-attachments/assets/50a3d810-a5b5-400e-a1ea-1616008e8deb" width="35%" /> | 

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by arnab** [comment] 2024-11-11 03:07
On a somewhat related note, I see that `CupertinoTextField` supports `keyboardAppearance` - which can be used to specify the keyboard light/dark mode: https://github.com/flutter/flutter/blob/18071ec0a87c281edffa0179228560dfe1f6f357/packages/flutter/lib/src/cupertino/text_field.dart#L225 (this support was added in https://github.com/flutter/flutter/pull/19244/).

But `CupertinoSearchTextField` does not allow specifying it, and does not pass this property into `CupertinoTextField`: https://github.com/flutter/flutter/blob/18071ec0a87c281edffa0179228560dfe1f6f357/packages/flutter/lib/src/cupertino/search_field.dart#L528-L556

**Comment by huycozy** [comment] 2024-11-11 11:36
Hi @arnab 
Checking this on Flutter 3.24.4, I don't see the issue with the following complete & minimal sample code. In this sample code, I only use a simple `CupertinoSearchTextField` widget and set themeMode to `ThemeMode.system`:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: CupertinoSearchTextField(),
      ),
    );
  }
}
```
</details>

Let's retry with this sample code and try to narrow your code down to find which causing this.

**Comment by arnab** [comment] 2024-11-11 18:22
Ah interesting! Thanks @huycozy ! 

I am using [flex_color_scheme](https://pub.dev/packages/flex_color_scheme) too, so it could be a combination of that. Although I have not changed the version of it recently.

I will look into what it could be on my side. Meanwhile, a (hopefully quick) question: should `CupertinoSearchTextField` also support `keyboardAppearance` (like `CupertinoTextField` does)? See [my note above](https://github.com/flutter/flutter/issues/158439#issuecomment-2467143341).

**Comment by arnab** [comment] 2024-11-11 18:43
It looks like this method: https://github.com/flutter/flutter/blob/18071ec0a87c281edffa0179228560dfe1f6f357/packages/flutter/lib/src/cupertino/theme.dart#L92C1-L96C1 is returning `light` (even if the system brightness is set to dark).

So based on that, I have found a workaround: as suggested in [this other, closed issue](https://github.com/flutter/flutter/issues/100180#issuecomment-1104135048), I am wrapping my `CupertinoSearchTextField` with a `CupertinoTheme` and that works:

```dart
      CupertinoTheme(
        data: CupertinoThemeData(
          brightness: Theme.of(context).brightness,
        ),
        child: CupertinoSearchTextField(
          ... // same properties as shown above
        ),
      );

```

**Comment by arnab** [comment] 2024-11-11 18:45
Specifically, it looks like `MediaQuery.platformBrightnessOf(context)` is defaulting to `light`:

- https://github.com/flutter/flutter/blob/18071ec0a87c281edffa0179228560dfe1f6f357/packages/flutter/lib/src/cupertino/theme.dart#L92C1-L96C1
- https://github.com/flutter/flutter/blob/18071ec0a87c281edffa0179228560dfe1f6f357/packages/flutter/lib/src/widgets/media_query.dart#L1376

**Comment by huycozy** [comment] 2024-11-12 05:27
>should CupertinoSearchTextField also support keyboardAppearance (like CupertinoTextField does)?

This should be addressed separately (feature request) for better tracking. I checked issue database but couldn't see an existing one.

>Specifically, it looks like MediaQuery.platformBrightnessOf(context) is defaulting to light:

It only falls to `Brightness.light` when `maybePlatformBrightnessOf` returns null. This depends on your theme settings too. 

Are you using MaterialApp? This reminds me of https://github.com/flutter/flutter/issues/146864, which makes me think this could be an underlying theme issue (same cause) and you can find some workarounds at https://github.com/flutter/flutter/issues/146864#issuecomment-2091882343. 

However, since you said this is a regression, this could not be the same. So please try to provide a minimal sample code that would be helpful to investigate later. Thanks!

**Comment by Scoper07** [comment] 2024-11-12 08:10
It seems like the issue you're experiencing is a regression in Flutter 3.24.4, where the keyboard no longer follows the system appearance on iOS, even when the system is set to dark mode. Prior to this version, it used to follow the system appearance, but now it defaults to light mode for the keyboard.

Since you’ve confirmed that Android behaves correctly, and this issue only affects iOS, it's likely a change or regression in how Flutter handles system appearance in the newer version. You could report this behavior to the Flutter team[,](https://medium.com/@fadimahar02/best-camera-for-filming-hunts-a92dbd506c9f) as it might be a bug introduced in the stable release. In the meantime, a potential workaround could be adjusting the keyboard appearance manually based on the system theme or using a custom approach to sync the appearance with the system.

You may also want to check for any updates or patches in Flutter 3.24.x, as the team might have already addressed this in a subsequent release.

**Comment by arnab** [comment] 2024-11-22 19:33
Hi @huycozy - I haven't had time to work on a repro. Also I added the workaround ([mentioned here](https://github.com/flutter/flutter/issues/158439#issuecomment-2468816900)).

If others are not seeing this issue, perhaps we can close this issue?

**Comment by danagbemava-nc** [comment] 2024-11-25 06:46
Hi @arnab, I tested the code sample provided in https://github.com/flutter/flutter/issues/158439#issuecomment-2467961088 and the keyboard does properly follow the theme mode. 

If you are able to come up with a minimal repro, we will appreciate that. 

For now, I'll be closing this. 

Thank you

**Closed by danagbemava-nc** 2024-11-25 06:46 UTC
Labels: in triage
