### ISSUE TITLE
Unclear Error message: Error: The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#148411] opened 2024-05-15 13:51 UTC
### Use case

```
$ flutter run macos
Error: The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error: Error running pod install
```
The error message is unclear and inexact.
1) it's not a `minimum iOS deployment version` but a `minimum MacOS deployment version`
2) what is the current requirement and what is the requirement of the plugin?

### Proposal

improve the error message

**Comment by danagbemava-nc** [comment] 2024-05-15 13:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/146744.

**Comment by stuartmorgan** [comment] 2024-05-16 11:02
I'm not sure this error is actually correct. Could you provide your full verbose build output?

**Comment by stephane-archer** [comment] 2024-05-16 14:35
@stuartmorgan Deleting `Pods` and `pod.lock` solves the issue on my side once again so I can't send you the full output.
If you play with "firebase_analytics" and update the required version you should be able to reproduce quite easily, that package generates more warning than any other package in my experience, the finest flutter package for MacOS <3
If you want more context, I'm happy to answer your questions to help you investigate.

**Comment by stuartmorgan** [comment] 2024-05-16 16:03
Without being able to see the specific versions of the pods you had I won't be able to determine if the error message was correct, so closing.

**Closed** 2024-05-16 16:03 UTC
Labels: tool, a: build, team-ecosystem
