### ISSUE TITLE
underline display error when render some unicode

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#75120] opened 2021-02-01 08:02 UTC
Same problem will happened when use TextField using Pingfang fontfamily. 
And I found it's the common problem when render some unicode using Text or TextField component.

Here is the code.

```
Text('ni\u2006hao', style: const TextStyle(
                fontSize: 72.0,
                color: const Color(0xFF333333),
                decoration: TextDecoration.underline,
                fontFamily: 'PingFang SC'
),)),
```

![image](https://user-images.githubusercontent.com/44207000/106430027-37e47580-64a6-11eb-83ee-2bfcba5b8790.png)

And obviously the height and y-coordinate of \u2006 's underline are different with other character.

I check the source code then I found all this is because the value underline_thickness of \u2006 's in metrics is smaller than other character which here is 3.55078 and others is 4.176.

same problem in  https://github.com/flutter/flutter/issues/33548

**Comment by pedromassangocode** [comment] 2021-02-01 12:33
Hi @xiaoxiaowesley 
I cannot reproduce the issue on latest master channel by using the Pingfang font family or using the code you provided above.

![Screen Shot 2021-02-01 at 13 25 59](https://user-images.githubusercontent.com/67424416/106458689-0a410180-6491-11eb-8d51-11897a3ae1a0.png)

Do you have a reproducible code sample? Or you can just modify the code bellow in a way that this issue is reproducible.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

final style = TextStyle(
  fontSize: 72.0,
  color: const Color(0xFF333333),
  decoration: TextDecoration.underline,
  fontFamily: 'PingFang'
);

void main() => runApp(
  MaterialApp(
    theme: ThemeData(fontFamily: 'PingFang'),
    home: Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
           Text('你好，世界', style: style,),
          TextField(
            controller: TextEditingController(text: '你好，世界'),
          ),
          SizedBox(height: 24,),
          Text('ni\u2006hao', style: style),

          TextField(
            controller: TextEditingController(text: 'ni\u2006hao'),
          ),
        ],
      ),
    ),
  ),
);
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.26.0-18.0.pre.90 at /Users/pedromassango/Code/flutter_master
    • Framework revision 25134a16d1 (2 days ago), 2021-01-29 23:52:30 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

**Comment by xiaoxiaowesley** [comment] 2021-02-02 06:18
Thanks for reply. This is a bug and fixed in  https://github.com/flutter/engine/pull/16709/commits.

**Comment by pedromassangocode** [comment] 2021-02-03 06:04
Closing this since it seems to be already fixed.
Thank you

**Closed by pedromassangocode** 2021-02-03 06:04 UTC
Labels: in triage
