### ISSUE TITLE
[linux]flutter app at ubuntu show chinese doesn`t work

### ISSUE THREAD

**Issue by godot0413301** [flutter/flutter#67984] opened 2020-10-13 03:22 UTC
## Steps to Reproduce

1.use snap to install flutter sdk on ubuntu20.04.
2.show chinese words in flutter made app.(I guess the reason is there is no chinese fonts)

**Expected results:** 

![image](https://user-images.githubusercontent.com/44113641/95808895-fd8b7880-0cfc-11eb-8245-45a63da02bf0.png)
**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-14.0.pre.148, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.23.0-14.0.pre.148 at /home/flutter/snap/flutter/common/flutter
    • Framework revision ac751cc50c (10 小时前), 2020-10-12 17:44:23 -0700
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/flutter/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/flutter/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/flutter/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!
```
```

</details>

**Comment by stuartmorgan** [comment] 2020-10-13 06:44
Duplicate of #30700

**Closed by stuartmorgan** 2020-10-13 06:44 UTC
