### ISSUE TITLE
Talkback focuses on the last focused element when the dialog/bottom sheet is reopened

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#55917] opened 2020-04-28 23:46 UTC
Internal: b/150749148

Somehow the state of the a11y is preserved when the bottom sheet/dialog is closed. This is causing the screen reader to *not* read title and description the second time the same dialog is opened.

```dart
        showModalBottomSheet<dynamic>(
            context: context,
            builder: (context) => Column(children: [
              Text("test bottom sheet", style: TextStyle(fontSize: 40)),
              SizedBox(height: 32),
              FlatButton(
                onPressed: () => Navigator.of(context).pop(),
                child: const Text('Deny'),
              ),
              FlatButton(
                onPressed: () => Navigator.of(context).pop(),
                child: Text('Allow'),
              ),
            ])
```

Try focusing on "Deny" and double tap to press it. Open the dialog again and observe that the focus is still on "Deny". It should instead be reset so that the reader can read the title and dialog content again.

**Comment by darrenaustin** [comment] 2020-04-29 19:29
Verified the repro case. Investigating now and will update when I have more info.

**Comment by darrenaustin** [comment] 2020-04-29 22:12
Little more info. Here is the repro app I am using:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.from(colorScheme: ColorScheme.light()),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _showModal() {
    showModalBottomSheet<void>(
      context: context,
      builder: (context) => Column(children: [
        Text("test bottom sheet", style: TextStyle(fontSize: 40)),
        SizedBox(height: 32),
        FlatButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Deny'),
        ),
        FlatButton(
          onPressed: () => Navigator.of(context).pop(),
          child: Text('Allow'),
        ),
      ]),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('A11y Bottom Modal')),
      body: Center(
        child: FlatButton(
          child: const Text('Show Modal'),
          onPressed: _showModal,
        ),
      ),
    );
  }
}
```

When I run this on a Pixel 3, here are the semantic trees for the initial and second runs:

First instance:
```
I/flutter (15577): SemanticsNode#0
I/flutter (15577):  │ Rect.fromLTRB(0.0, 0.0, 1080.0, 2028.0)
I/flutter (15577):  │
I/flutter (15577):  └─SemanticsNode#1
I/flutter (15577):    │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5) scaled by 2.8x
I/flutter (15577):    │ textDirection: ltr
I/flutter (15577):    │
I/flutter (15577):    └─SemanticsNode#6
I/flutter (15577):      │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5)
I/flutter (15577):      │ flags: scopesRoute, namesRoute
I/flutter (15577):      │ label: "Dialog"
I/flutter (15577):      │ textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      ├─SemanticsNode#7
I/flutter (15577):      │   Rect.fromLTRB(38.9, 322.6, 353.9, 369.6)
I/flutter (15577):      │   label: "test bottom sheet"
I/flutter (15577):      │   textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      ├─SemanticsNode#8
I/flutter (15577):      │   Rect.fromLTRB(152.4, 401.6, 240.4, 449.6)
I/flutter (15577):      │   actions: tap
I/flutter (15577):      │   flags: isButton, hasEnabledState, isEnabled, isFocusable
I/flutter (15577):      │   label: "Deny"
I/flutter (15577):      │   textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      └─SemanticsNode#9
I/flutter (15577):          Rect.fromLTRB(152.4, 449.6, 240.4, 497.6)
I/flutter (15577):          actions: tap
I/flutter (15577):          flags: isButton, hasEnabledState, isEnabled, isFocusable
I/flutter (15577):          label: "Allow"
I/flutter (15577):          textDirection: ltr
```

Second instance:
```
I/flutter (15577): SemanticsNode#0
I/flutter (15577):  │ Rect.fromLTRB(0.0, 0.0, 1080.0, 2028.0)
I/flutter (15577):  │
I/flutter (15577):  └─SemanticsNode#1
I/flutter (15577):    │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5) scaled by 2.8x
I/flutter (15577):    │ textDirection: ltr
I/flutter (15577):    │
I/flutter (15577):    └─SemanticsNode#10
I/flutter (15577):      │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5)
I/flutter (15577):      │ flags: scopesRoute, namesRoute
I/flutter (15577):      │ label: "Dialog"
I/flutter (15577):      │ textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      ├─SemanticsNode#11
I/flutter (15577):      │   Rect.fromLTRB(38.9, 322.6, 353.9, 369.6)
I/flutter (15577):      │   label: "test bottom sheet"
I/flutter (15577):      │   textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      ├─SemanticsNode#12
I/flutter (15577):      │   Rect.fromLTRB(152.4, 401.6, 240.4, 449.6)
I/flutter (15577):      │   actions: tap
I/flutter (15577):      │   flags: isButton, hasEnabledState, isEnabled, isFocusable
I/flutter (15577):      │   label: "Deny"
I/flutter (15577):      │   textDirection: ltr
I/flutter (15577):      │
I/flutter (15577):      └─SemanticsNode#13
I/flutter (15577):          Rect.fromLTRB(152.4, 449.6, 240.4, 497.6)
I/flutter (15577):          actions: tap
I/flutter (15577):          flags: isButton, hasEnabledState, isEnabled, isFocusable
I/flutter (15577):          label: "Allow"
I/flutter (15577):          textDirection: ltr
```

Which are structurally identical with just different node ids for the dialog and its subtree. Not sure what would be causing the issue given these trees. Perhaps there is something in the engine or underlying platform API that is caching something and reusing it when it sees the new instance.

**Comment by darrenaustin** [comment] 2020-04-30 06:54
I spent more time looking at the a11y bridge in the engine, but I didn't see anything that looked like it would be causing this issue. Unfortunately, I was having problems building the engine, so I wasn't able to debug further. Handing this over to Chris to see if he can take this any further on the engine side.

**Comment by pcsosinski** [comment] 2020-05-18 23:42
b/150749148

**Comment by pcsosinski** [comment] 2020-05-29 19:36
any update here?

**Comment by xster** [comment] 2020-06-02 22:57
@cbracken are you currently working on this?

**Comment by jonahwilliams** [comment] 2020-06-03 16:47
This seems similar to an issue that @gspencergoog looked at a while back, and myself a while before that.

I don't remember if we ever found a solution. There was a previous focus case that was caused by a timing issue - we sent the first semantics before the child widgets were visible and that caused the announcement to be blank. The fix there was the force the visibility to not hide semantics for that particular widget.

But in general, I don't think we have any idea what causes this.

**Comment by jonahwilliams** [comment] 2020-06-03 16:54
FWIW in this specific case I cannot reproduce the issue on a Pixel 4

**Comment by xster** [comment] 2020-06-03 18:57
@gaaclarke can you see if you can repro? We should ask for details in b/150749148 if needed. Otherwise let's close this.

**Comment by pcsosinski** [comment] 2020-06-12 17:42
any update on repro / closing this issue?

**Comment by gaaclarke** [comment] 2020-06-12 18:58
@pcsosinski, slipped.  Let me wrap up what I'm working on and I'll take a peek this afternoon

**Comment by gaaclarke** [comment] 2020-06-12 20:56
I ran Daren's code with the latest version of Flutter on my Android device and was able to reproduce the issue.  The second time the dialog is presented it does not say "test bottom sheet", it talks about the "Deny" button.

To be honest this is the first time I'm using Talkbalk and much more looks broken than that.  Talkback often says the name of the app and the green rectangle around objects isn't rendering.

**doctor:**
```
aaclarke-macbookpro2:issue_55917 aaclarke$ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-1.0.pre.41, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.0-1.0.pre.41 at /Users/aaclarke/dev/flutter
    • Framework revision d64884dedf (65 minutes ago), 2020-06-12 12:50:03 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

**android version:** 7.0

**device:** Asus Zenfone AR

**Comment by gaaclarke** [comment] 2020-06-13 00:15
**conclusions**
Someone is caching state that causes Talkback to avoid saying "test bottom sheet".  If you run through the reproduction steps except pressing the "Allow" instead of "Deny" button, when the sheet is brought back up, "Allow" is highlighted, not "Deny"

It is my belief that it is the operating system's accessibility library that is caching that state.  That would explain why some people could not reproduce the problem.  There doesn't seem to be any fix for Flutter. For evidence please see my debugging log.   It would be nice if someone with more Talkback experience could verify it.

**debugging log**

I did a bit of debugging and found that in the pathological case [AccessibilityBridge.findFocus](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1091) is returning `android.view.accessibility.AccessibilityNodeInfo@79dc; boundsInParent: Rect(566, 1397 - 874, 1565); boundsInScreen: Rect(566, 1397 - 874, 1565); packageName: com.example.issue_55917; className: android.widget.Button; text: null; error: null; maxTextLength: -1; contentDescription: Deny; viewIdResName: ; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; actions: [AccessibilityAction: ACTION_CLICK - null, AccessibilityAction: ACTION_CLEAR_ACCESSIBILITY_FOCUS - null]`

That result actually comes from [this line of code](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1106) so there might be some dirty state in the `accessibilityFocusedSemanticsNode` instance variable.

That variable is only ever set to a value in the [ACTION_ACCESSIBILITY_FOCUS action](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L949), but there are numerous places where it is cleared out.  That might point to a missed opportunity to clear it out.

I verified that `ACTION_CLEAR_ACCESSIBILITY_FOCUS` is getting issued when the sheet is dismissed.  When it is brought up again a `ACTION_ACCESSIBILITY_FOCUS` is issued, but [the handler](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L949) is finding the "Deny" button, not the sheet title like we expected.  That handler bases its result on [`flutterSemanticsTree.get(virtualViewId)`](https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L848), so that seems to be the source of the incorrect data.

The first time I bring up the sheet, the `virtualViewId` passed into `AccessibilityBridge.performAction` for the focus action is 7 which corresponds to the sheet title according to `flutterSemanticsTree`.  The second time the sheet is focused `virtualViewId` is 12 which corresponds to the "Deny" button.  The `virtualViewId` comes directly from Android's accessibility API via [AccessibilityNodeProvider.performAction](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeProvider#performAction(int,%20int,%20android.os.Bundle)), so it appears that the OS is caching the state in question.

**Comment by goderbauer** [comment] 2020-06-16 21:07
That all sounds plausible. Do you have any insights how Android learns of the existence of a node with the ID 12? If I understand it correctly, the first time the sheet comes up, no node with that ID exists, so it can't exactly cache the node id. So, somehow it must learn about the new id when the sheet comes up again (otherwise it couldn't/wouldn't give us that ID in  `AccessibilityBridge.performAction`). Does TalkBack perform hit testing to figure out what new node is in the location that previously had the focus? Does it walk the entire hierarchy again until it finds a node with the same rect?

To investigate this further, here is where I would look:

* When the sheet appears, we are presumably sending an TYPE_WINDOW_STATE_CHANGED event. Is there anything we can set on that event to indicate that this is something completely new and Android shouldn't use any cached information? (As an experiment: does the problem go away when the name of the route changes between invocations? The name is set here: https://github.com/flutter/engine/blob/f7d241fd8a889fadf8ab3f9d57918be3d986b4be/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1551)
* Is there anything interesting in TalkBack's log when the screen is brought up the second time? With verbose logging turned on, TalkBack is usually pretty verbose in telling you what and why its doing what its doing. Any indication in there why it wants to focus on node 12?
* Often it has also been helpful to compare the log Flutter produces when performing an action with what the log looks like when the same action is performed in a native app. In doing so, we often found that we were not sending events that TalkBack expected to function properly.

**Comment by gaaclarke** [comment] 2020-06-17 22:32
@goderbauer Here is the log when the sheet is brought back:
```
06-17 18:25:54.417 12190 12190 D Pipeline: execute()
feedback=Feedback{eventId=type:EVENT_TYPE_ACCESSIBILITY
subtype:TYPE_WINDOW_STATE_CHANGED time:3437226, sequence=[Part= focus=
action=FOCUS target=
android.support.v4.view.accessibility.AccessibilityNodeInfoCompat@79fe;
boundsInParent: Rect(566, 1565 - 874, 1733); boundsInScreen: Rect(566, 1565 -
874, 1733); packageName: com.example.issue_55917; className:
android.widget.Button; text: null; contentDescription: Allow; viewId: ;
checkable: false; checked: false; focusable: true; focused: false; selected:
false; clickable: true; longClickable: false; enabled: true; password: false;
scrollable: false; [ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS] focusActionInfo=
FocusActionInfo{ sourceAction=SCREEN_STATE_CHANGE
initialFocusType=RESTORED_LAST_FOCUS isForcedFeedbackAudioPlaybackActive
isForcedFeedbackMicrophoneActive }   ]}
```

The important part being **RESTORED_LAST_FOCUS**, so it is telling us that it is doing what I expected, it is caching the focus and restoring it.

**Comment by gaaclarke** [comment] 2020-06-17 22:39
Not only is it the operating system, and not Flutter, that is performing this behavior; it is explicitly doing this behavior.  It seems any attempt to make the operating system behave different wouldn't be in alignment with expectations of Talkback users.

**Closed by gaaclarke** 2020-06-17 22:39 UTC
Labels: P2, a: accessibility, customer: money (g3), platform-android

**Comment by davidv1992** [comment] 2020-12-09 09:35
If this is the wrong place to advocate for reopening this issue please tell me.

I also run into this issue in the context of an app I am developing. Based on the OS settings screen behaviour around dialogs (specifically the enable/disable talkback button in the settings screen and its alert dialog) keeping focus where it was last time is not desired behaviour. Finding some way to keep talkback and other screenreaders from caching the focus here would be a very good thing to have.

**Comment by KiruthikaAdhi** [comment] 2020-12-22 05:37
Is there a hack which will solve this issue, I am facing this issue in my app.
