### ISSUE TITLE
Building a desktop Linux app fails

### ISSUE THREAD

**Issue by adnan449** [flutter/flutter#77452] opened 2021-03-06 06:24 UTC
## Steps to Reproduce
Create a flutter project and try to run it.

## Logs

```
$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
/snap/flutter/current/usr/bin/ld: warning: //lib64/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Building Linux application...                                           
Exception: Build process failed
```

Full verbose log: https://pastebin.com/c9NTJjig

Flutter doctor: https://pastebin.com/rAAkRu0W

**Comment by TahaTesser** [comment] 2021-03-08 08:44
Hi @adnan449 
This is a duplicate of https://github.com/flutter/flutter/issues/77293
Workaround - https://github.com/flutter/flutter/issues/77293#issuecomment-791377450
Closing a duplicate, If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-08 08:44 UTC
Labels: in triage
