### ISSUE TITLE
bind to recognition service failed

### ISSUE THREAD

**Issue by rodrigonettooliveira** [flutter/flutter#34411] opened 2019-06-13 14:23 UTC
## Steps to Reproduce
1- I create an emulator nexus 4 api 22 android 5.1.
2-In `androidmanifest.xml` includes permission RECORD_AUDIO
3-in emulator -> more -> microphone -> options on
4-run the app 

## Logs
```
06-13 14:22:09.239 6412-6412/? E/libprocessgroup: failed to make and chown /acct/uid_10059: Read-only file system
06-13 14:22:09.239 6412-6412/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
06-13 14:22:09.240 6412-6412/? I/art: Not late-enabling -Xcheck:jni (already on)
06-13 14:22:09.296 6412-6412/com.example.flutter_app W/linker: libflutter.so: unused DT entry: type 0x6ffffef5 arg 0x1d58
06-13 14:22:09.296 6412-6412/com.example.flutter_app W/linker: libflutter.so: unused DT entry: type 0x6ffffffe arg 0x1cf8
06-13 14:22:09.296 6412-6412/com.example.flutter_app W/linker: libflutter.so: unused DT entry: type 0x6fffffff arg 0x3
06-13 14:22:09.307 6412-6428/com.example.flutter_app I/ResourceExtractor: Found extracted resources res_timestamp-1-1560435593012
06-13 14:22:09.385 6412-6412/com.example.flutter_app D/EGL_emulation: eglCreateContext: 0xb42e3520: maj 2 min 0 rcv 2
06-13 14:22:09.391 6412-6431/com.example.flutter_app D/EGL_emulation: eglMakeCurrent: 0xb42e3520: ver 2 0 (tinfo 0xb43d5050)
06-13 14:22:09.551 6412-6412/com.example.flutter_app I/TextToSpeech: Sucessfully bound to com.svox.pico
06-13 14:22:09.560 6412-6440/com.example.flutter_app D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-13 14:22:09.562 6412-6412/com.example.flutter_app D/Atlas: Validating map...
06-13 14:22:09.564 6412-6412/com.example.flutter_app I/TextToSpeech: Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
06-13 14:22:09.584 6412-6442/com.example.flutter_app I/TextToSpeech: Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
06-13 14:22:09.609 6412-6440/com.example.flutter_app I/OpenGLRenderer: Initialized EGL, version 1.4
06-13 14:22:09.610 6412-6440/com.example.flutter_app W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
06-13 14:22:09.615 6412-6435/com.example.flutter_app I/flutter: Observatory listening on http://127.0.0.1:46429/jez5tzcYsCo=/
06-13 14:22:09.617 6412-6440/com.example.flutter_app D/EGL_emulation: eglCreateContext: 0xb42e3160: maj 2 min 0 rcv 2
06-13 14:22:09.618 6412-6440/com.example.flutter_app D/EGL_emulation: eglMakeCurrent: 0xb42e3160: ver 2 0 (tinfo 0xb43d57f0)
06-13 14:22:09.621 6412-6440/com.example.flutter_app D/OpenGLRenderer: Enabling debug mode 0
06-13 14:22:09.634 6412-6440/com.example.flutter_app D/EGL_emulation: eglMakeCurrent: 0xb42e3160: ver 2 0 (tinfo 0xb43d57f0)
06-13 14:22:09.664 6412-6430/com.example.flutter_app D/EGL_emulation: eglCreateContext: 0xae834d60: maj 2 min 0 rcv 2
06-13 14:22:09.684 6412-6430/com.example.flutter_app D/EGL_emulation: eglMakeCurrent: 0xae834d60: ver 2 0 (tinfo 0xae839340)
06-13 14:22:10.381 6412-6412/com.example.flutter_app I/SimplePermission: Checking permission : android.permission.RECORD_AUDIO
06-13 14:22:10.385 6412-6412/com.example.flutter_app D/SpeechRecognitionPlugin: Current Locale : pt_BR
06-13 14:22:10.552 6412-6430/com.example.flutter_app D/EGL_emulation: eglMakeCurrent: 0xae834d60: ver 2 0 (tinfo 0xae839340)
06-13 14:22:10.585 6412-6429/com.example.flutter_app I/flutter: _platformCallHandler call speech.onCurrentLocale pt_BR
06-13 14:22:23.864 6412-6412/com.example.flutter_app E/SpeechRecognizer: bind to recognition service failed
06-13 14:22:23.876 6412-6429/com.example.flutter_app I/flutter: saida = true
```

C:\Users\rnoliveira\AndroidStudioProjects\flutter_app>flutter doctor -v
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [versÃ£o 10.0.15063], locale pt-BR)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rnoliveira\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Android
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

• No issues found!
```

**Comment by janmoppel** [comment] 2019-10-08 10:05
Hello @rodrigonettooliveira !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by rodrigonettooliveira** [comment] 2019-10-08 19:00
Hi my friend, that's ok. I'm use other way.

Tks.

Em ter, 8 de out de 2019 7:07 AM, Jan Moppel <notifications@github.com>
escreveu:

**Comment by fullstact69** [comment] 2019-11-05 18:52
bind to recognition service failed
How can I resolve this error?

**Comment by rodrigonettooliveira** [comment] 2019-11-06 00:31
I am use android with java program.


Em ter, 5 de nov de 2019 3:54 PM, fulldeveloper <notifications@github.com>
escreveu:

**Comment by iapicca** [comment] 2020-01-16 09:42
Hi @rodrigonettooliveira 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment] 2020-02-13 11:35
Hi  @rodrigonettooliveira 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by cristianrablau** [comment] 2020-02-23 18:12
Hi @TahaTesser ,
I can reproduce the same error using [https://pub.dev/packages/speech_to_text](https://pub.dev/packages/speech_to_text). More information here: [https://github.com/csdcorp/speech_to_text/issues/36](https://github.com/csdcorp/speech_to_text/issues/36)

`PS E:\git\Flutter\stt_test> flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale ro-RO)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.5)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.`

**Comment by TahaTesser** [comment] 2020-02-24 12:59
Hi @rodrigonettooliveira 
Since this is a 3rd party package, it would be better you report this issue on their repo and they can resolve this issue.
Thank you

**Comment by liyang1518** [comment] 2020-02-27 09:54
I also encountered the problem of consent. This problem behaves differently on different phones. Some phones are normal and some are abnormal.

**Comment by TahaTesser** [comment] 2020-02-27 10:17
Hi @liyang1518 

Can you please elaborate the issue you're facing? Are you using [https://pub.dev/packages/speech_to_text](https://pub.dev/packages/speech_to_text)

can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-03-20 13:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-03-20 13:52 UTC
Labels: in triage, waiting for customer response

**Comment by cristianrablau** [comment] 2020-03-20 15:35
I installed/enabled the Google app and I gave it access to microphone. All problems solved!

My problem was related to an external package but the error message was the same.
More information here:[https://github.com/csdcorp/speech_to_text/issues/36(https://github.com/csdcorp/speech_to_text/issues/36)

**Comment by liyang1518** [comment] 2020-03-21 08:27
> Hi @liyang1518
> 
> Can you please elaborate the issue you're facing? Are you using https://pub.dev/packages/speech_to_text
> 
> can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
> if you could post a minimal code sample to reproduce the problem
> Thank you


this is my local env.========>
E:\FSP\temp>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at E:\tools\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\IES\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\IDEA\IntelliJ IDEA 2018.3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • MIX 3 • b822784e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.


I used this speech recognition plugin：https://github.com/rxlabz/speech_recognition
and this is the failed log========>
I/flutter (26344): _MyAppState.activateSpeechRecognizer... 
D/SpeechRecognitionPlugin(26344): Current Locale : zh_CN
I/flutter (26344): _platformCallHandler call speech.onCurrentLocale zh_CN
I/flutter (26344): _MyAppState.onCurrentLocale... zh_CN
E/SpeechRecognizer(26344): bind to recognition service failed
I/flutter (26344): _MyAppState.start => result true


This problem behaves differently on different phones. for ex=====>
Same brand phone
in MIX 3  android10 is not ok ,There will be the above error.
in MI9 android9 is ok,
I'm not sure if it's a plugin issue or a flutter issue.
Looking forward to your reply。

**Comment by iapicca** [comment] 2020-03-21 11:51
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
