### ISSUE TITLE
Flutter Gallery not scrolling smoothly - Samsung S6 / Note 4

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#10481] opened 2017-06-03 04:13 UTC
## Steps to Reproduce

1. Scroll anywhere throughout the app (main screen, shop demo, etc.)
2. Notice a slight jittering as it scrolls, with occasional (very noticeable) skips.

Tested with [flutter-gallery-bv8-rc000](https://play.google.com/store/apps/details?id=io.flutter.gallery) **and** both alpha and master branches, run in release mode.

**Comment by eseidelGoogle** [comment] 2017-06-03 14:54
More from gitter "it's weird, almost like the touch is too sensitive. If I fling the actual deceleration animation is butter smooth."

**Comment by zoechi** [comment] 2018-11-30 09:40
Is this still an issue? I can't reproduce (Pixel XL)

**Comment by BondarenkoStas** [comment] 2019-10-24 12:42
Is it still an issue?

**Comment by iapicca** [comment] 2019-11-01 13:02
Hi @pauldemarco 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 13:02 UTC
Labels: engine, framework, severe: performance, waiting for customer response
