### ISSUE TITLE
flutter pub get "git@github.com: Permission denied (publickey)"

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#71574] opened 2020-12-02 16:08 UTC
I've just done a clean windows 10 pro install and not installed dart sdk as the docs mention that the flutter sdk is all thats required.

I'm having difficulty with a project that has dependencies in github. I'm starting a ssh agent with `start-ssh-agent`, when I run `flutter pub get` I get the following:

```
PS D:\dev\dart\os_app> flutter pub get
Git error. Command: `git clone --mirror git@github.com:jimmyff/great_circle_distance.git D:\dev\sdks\flutter\.pub-cache\git\cache\great_circle_distance-6016cccb55950ff1b6724c8c96eed8fafb100055`
stdout: 
stderr: Cloning into bare repository 'D:\dev\sdks\flutter\.pub-cache\git\cache\great_circle_distance-6016cccb55950ff1b6724c8c96eed8fafb100055'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

Its failing with the ssh key however if I immediately run `pub clone git@github.com:jimmyff/great_circle_distance.git test` it checks out correctly? It's as if flutter isn't making use of the ssh agent.

Please advise thanks.

Thanks

**Comment by TahaTesser** [comment] 2020-12-03 10:10
Hi @jimmyff 
From what I can see, the issue is related to a 3rd party `pub` plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-03 10:10 UTC

**Comment by jimmyff** [comment] 2020-12-10 16:04
Hey @TahaTesser I'm not sure you can really call pub a plugin! so should I take this up with dart-lang?
