### ISSUE TITLE
[Android] Flutter does not get the correct initial route when launch by a deep link 

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#121244] opened 2023-02-22 16:54 UTC
b/270298884

Follow the Android section of https://docs.flutter.dev/development/ui/navigation/deep-linking

If the deeplink is launched when the app is not open, it will launch with the default initial route `/` instead of the deeplinked route.

repro:

1. create a flutter app

<details>
<summary> main.dart </summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  routes: <String, WidgetBuilder> {
    '/': (_)=> Scaffold(appBar: AppBar(title: Text('/'))),
    '/abc': (_)=> Scaffold(appBar: AppBar(title: Text('/abc'))),
  }
));
```

</details>

2. in <flutter project>/android/app/src/main/AndroidManifest.xml, add following meta tags in <activity>

<details>
<summary> xml </summary>

```xml
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="http" android:host="flutterbooksample.com" />
    <data android:scheme="https" />
</intent-filter>
```
</details>

3. do a `flutter run` on any Android device (I am using motoG4)
4. force quit the app, and make sure the app is not in the background.
5. run adb command
```
adb shell 'am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "http://flutterbooksample.com/abc"' \
    <package name>
```

expect: the page is opened with `/abc` in the appbar
actual: the page is opened with `/` in the appbar

This only happen if the app is started cold, if the app is in the background the deeplink command will work correctly.

**Comment by chunhtai** [comment] 2023-02-22 16:56
label p2 as internal bug is a P1, please adjust accordingly

**Comment by gmackall** [comment] 2023-02-23 19:10
Related strategy doc at go/issue-121244

**Comment by camsim99** [comment] 2023-03-01 23:28
Workin on a repro for this. Will update when I can see it happening and have identified the cause.

**Comment by chunhtai** [comment] 2023-03-01 23:32
@chinmaygarde I think the fix will be on android embedding in engine because it should pass the uri to the framework side but didn't. Shouldn't this be marked as with `engine`?

**Comment by chinmaygarde** [comment] 2023-03-02 00:55
We followed the [new triage process this week](https://docs.google.com/document/d/1RBvsolWL9nUkcEFhPZV4b-tstVUDHfHKzs-uQ3HiX-w/edit#heading=h.smxa4a2dcbj8). `platform-android` should be the right tag for this right?

**Comment by reidbaker** [comment] 2023-03-02 19:01
Yes, Camille was able to get this compiling in google3 yesterday and has been talking to the person who filed the internal issue directly.

**Comment by chunhtai** [comment] 2023-03-02 19:15
I can reproduce it locally, feel free to ping me if you need my help

**Comment by camsim99** [comment] 2023-03-04 00:07
I was able to reproduce this with @chunhtai's reproduction. From talking with him, we determined that the source of the problem is that deep links are being handled in the engine only when the `FlutterActivity`'s [`onNewIntent()`](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)) method is called. This is _not_ called when the app has been force quit/is not running in the background. Thus, to fix this issue, an additional call to the logic in the `onNewIntent()` method needs to be added.

Timing seems to be the trickiest factor. So far, I've tried adding it to the [`onCreate(...)`](https://developer.android.com/reference/android/app/Activity#onCreate(android.os.Bundle)) and [`onStart(...)`](https://developer.android.com/reference/android/app/Activity#onStart()) methods, but both have proven to be too early for observers on the framework side to pick up.

**Comment by camsim99** [comment] 2023-03-06 18:35
It seems like using Android `Activity` lifecycle callback methods like `onCreate(...)` and `onStart(...)` will not work because all of these phases occur _before_ `initState()` is called for the app on the framework side, meaning route changes will be ignored because they cannot be picked up until `initState()` is called. This means we will have to find a way to let the engine know that it _may_ want to push route changes _after_ `initState()` has been called on the framework side.

**Comment by camsim99** [comment] 2023-03-06 21:54
After talking to @chunhtai, we landed on the solution of waiting for Flutter to render its first frame to try pushing updated route information if it has not already been pushed (like in the case where the app was in the background, which handles pushing route information slightly differently). This will happen after `initState()` is called, so the new route information will not be ignored. I plan to open a PR for this.

**Closed** 2023-03-09 18:42 UTC
Labels: platform-android, P2
