### ISSUE TITLE
Memory leak when pick image from gallery or take from camera from image_picker

### ISSUE THREAD

**Issue by uzumaki258** [flutter/flutter#54757] opened 2020-04-14 16:14 UTC
Hello, 
I use image_picker take an image and use that to pass to next page.

```
try{
      var _image = await ImagePicker.pickImage(
          source: fromCamera ? ImageSource.camera : ImageSource.gallery,
          maxHeight: 800,
          maxWidth: 600,
          );    
      retrieveLostData();
      if (_image != null && _image.path != null) {
        _goToChoosePage(context, _image);
      }
```

But when I choose an Image, the memory will increase.
![image](https://user-images.githubusercontent.com/26773292/79247121-4d030000-7ea4-11ea-8041-4d9411603158.png)
I have to resize to reduce memory, but it still not good if the user use app for a long time.
it would be great if I can release memory, or cache image after taking photos, or from Gallery.

Can you suggest me a way to do that?

Thank you

**Comment by TahaTesser** [comment] 2020-04-15 09:22
Hi @uzumaki258 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by uzumaki258** [comment] 2020-04-22 09:01
@TahaTesser Sorry for the late comment.
Here are flutter doctor -v and flutter run --verbose. It's pretty long so I add to txt file.
[flutter_doctor.txt](https://github.com/flutter/flutter/files/4514971/flutter_doctor.txt)
[output.txt](https://github.com/flutter/flutter/files/4514972/output.txt)
thank you!

**Comment by TahaTesser** [comment] 2020-04-22 09:54
Memory is increased every time a a different image is picked, not sure if this is an issue or it's caching images into by memory by design

Code - [image_picker exmaple ](https://pub.dev/packages/image_picker#-example-tab-)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

<img width="863" alt="Screenshot 2020-04-22 at 3 20 56 PM" src="https://user-images.githubusercontent.com/48603081/79968075-4892a480-84ad-11ea-8b56-5412c3f35014.png">

**Comment by SogoGolf** [comment] 2020-07-09 09:15
We are seeing the same issue on Flutter v1.17.2

Any eta for a fix ?

**Comment by SogoGolf** [comment] 2020-07-10 02:13
ok i wanted to add a note here in case someone else finds this ticket re memory issues & image_picker. i rushed to post a ticket freaking out about a massive memory leak, before looking at & understanding the available parameter options when preparing an image for display.

whilst i still dont have a full grasp of all the dials that you can tweak to minimise/optimise memory usage, i found the following to be a huge improvement and "fix".

first, you've got some important parameters on the getImage() method:

```
final pickedFile = await _picker.getImage(
        source: source,
        maxWidth: 600,  !!!!<=========    NOTE: maxWidth: null means **_full original width_**
        maxHeight: 600, !!!!<=========    NOTE: maxHeight: null means **_full original height_**
        imageQuality: 75,  !!!!<==== you can use this to increase/decrease image size
      );
```
if you dont set the ```maxHeight``` and ```maxWidth``` params, then you will get a FULL size image via the camera or image gallery

next:
when you are displaying that image in the UI, there are some important parameters to set on ```Image.file(..)```. for example:

```
return Image.file(
        File(
          _imageFile.path,
        ),
        width: 600,    !!!!<=========  
        height: 600,   !!!!<=========  
        cacheWidth: 600,   !!!!<=========  
        cacheHeight: 600,    !!!!<=========  
        filterQuality: FilterQuality.low,    !!!!<=========  
        scale: 1.0,    !!!!<=========  
        fit: BoxFit.contain,
      );
``` 
All of the marked parameters above can be used to affect the size and therefore memory footprint used when displaying the image.

By playing with the above noted params I was able to go from a continually increasing memory graph, to a flat one. Again I'm no expert on this topic and please let me know if I've got anything wrong above. But I can definitely tell you that adding/working with the params as noted above made a proven difference.

**BEFORE**
![image](https://user-images.githubusercontent.com/19580787/87108768-5c78c600-c2a6-11ea-8d18-30e1496bb546.png)

**AFTER**
![image](https://user-images.githubusercontent.com/19580787/87108705-423ee800-c2a6-11ea-8315-9d81095a34b4.png)

i think an easy first step for Google here is to add some details into the Flutter documentation re the above.

hope this helps someone.

**Comment by Dinesh41** [comment] 2020-10-05 02:11
Did anyone found workaround to fix this issue?

**Comment by dinesh-commits** [comment] 2020-10-05 02:23
> ok i wanted to add a note here in case someone else finds this ticket re memory issues & image_picker. i rushed to post a ticket freaking out about a massive memory leak, before looking at & understanding the available parameter options when preparing an image for display.
> 
> whilst i still dont have a full grasp of all the dials that you can tweak to minimise/optimise memory usage, i found the following to be a huge improvement and "fix".
> 
> first, you've got some important parameters on the getImage() method:
> 
> ```
> final pickedFile = await _picker.getImage(
>         source: source,
>         maxWidth: 600,  !!!!<=========    NOTE: maxWidth: null means **_full original width_**
>         maxHeight: 600, !!!!<=========    NOTE: maxHeight: null means **_full original height_**
>         imageQuality: 75,  !!!!<==== you can use this to increase/decrease image size
>       );
> ```
> 
> if you dont set the `maxHeight` and `maxWidth` params, then you will get a FULL size image via the camera or image gallery
> 
> next:
> when you are displaying that image in the UI, there are some important parameters to set on `Image.file(..)`. for example:
> 
> ```
> return Image.file(
>         File(
>           _imageFile.path,
>         ),
>         width: 600,    !!!!<=========  
>         height: 600,   !!!!<=========  
>         cacheWidth: 600,   !!!!<=========  
>         cacheHeight: 600,    !!!!<=========  
>         filterQuality: FilterQuality.low,    !!!!<=========  
>         scale: 1.0,    !!!!<=========  
>         fit: BoxFit.contain,
>       );
> ```
> 
> All of the marked parameters above can be used to affect the size and therefore memory footprint used when displaying the image.
> 
> By playing with the above noted params I was able to go from a continually increasing memory graph, to a flat one. Again I'm no expert on this topic and please let me know if I've got anything wrong above. But I can definitely tell you that adding/working with the params as noted above made a proven difference.
> 
> **BEFORE**
> ![image](https://user-images.githubusercontent.com/19580787/87108768-5c78c600-c2a6-11ea-8d18-30e1496bb546.png)
> 
> **AFTER**
> ![image](https://user-images.githubusercontent.com/19580787/87108705-423ee800-c2a6-11ea-8315-9d81095a34b4.png)
> 
> i think an easy first step for Google here is to add some details into the Flutter documentation re the above.
> 
> hope this helps someone.

Is this solved the problem?

**Comment by Dinesh41** [comment] 2020-10-19 07:47
Above method works for me

**Comment by TahaTesser** [comment] 2021-01-29 14:48
Hi @uzumaki258  
Testing the on the latest `stable` and `master`  using the latest ` 0.6.7+21` 
Memory seems fine when taking a pic or picking from Gallery multiple times

<img width="947" alt="Screenshot 2021-01-29 at 8 15 22 PM" src="https://user-images.githubusercontent.com/48603081/106289141-eaca8e80-626e-11eb-9fbf-148ba506fc2d.png">

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (7 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.73 at /Users/tahatesser/Code/flutter_master
    • Framework revision 791edc230d (5 hours ago), 2021-01-28 21:54:03 -0800
    • Engine revision 4ba79a34a0
    • Dart version 2.12.0 (build 2.12.0-272.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Can you please try the latest `stable` channel and latest package
Thank you

**Comment by pedromassangocode** [comment] 2021-03-12 14:02
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:02 UTC
Labels: P4, found in release: 1.18, has reproducible steps, p: first party, p: image_picker, perf: memory, plugin, severe: performance, waiting for customer response

**Comment by NarHakobyan** [comment] 2021-04-16 15:05
this issue still exists

```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-AM)
    • Flutter version 1.22.6 at /Users/narek/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/narek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/narek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7260174/Android Studio Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+0-b77-7246554)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/narek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7260174/Android Studio Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+0-b77-7246554)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```
