### ISSUE TITLE
multiplying a parsed double to (int or double) is giving arbitrary values

### ISSUE THREAD

**Issue by Navdeep-Goyal** [flutter/flutter#109664] opened 2022-08-17 05:23 UTC
I am parsing String to double using double.parse(String), and then multiplying it to (100 or 100.0), it is not returning the desired output for some values.

Example - 
double.parse("2489.7")
result - 2489.7
Then result * 100 
multiplied result - 248969.99999999997

```
Flutter 3.0.5 • channel stable •
Framework • revision f1875d570e (5 weeks ago) • 2022-07-13       
11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

**Comment by stuartmorgan** [comment] 2022-08-17 10:55
Duplicate of https://github.com/dart-lang/sdk/issues/36128 (and others).

**Closed by stuartmorgan** 2022-08-17 10:55 UTC
