### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed

### ISSUE THREAD

**Issue by harguilar** [flutter/flutter#96464] opened 2022-01-11 10:35 UTC
This is happening a lot now; from time to time again when am typing something on my MacOs to my app am getting this error:

```
KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, 
please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow 
Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0ee09(physicalKey: PhysicalKeyboardKey#7000b(usbHidUsage: "0x0007000b", debugName: "Key H"), logicalKey: LogicalKeyboardKey#00068(keyId: "0x00000068", keyLabel: "H", debugName: "Key H"), character: null, timeStamp: 36:15:59.731822)
```
I was wondering if you can help me with it.

**Comment by maheshmnj** [comment] 2022-01-11 10:54
HI @harguilar, Could you please share the output of `flutter doctor -v` and also specify any specific key combinations or steps to reproduce the issue.

Thanks

**Comment by harguilar** [comment] 2022-01-11 11:31
Hi maheshmnj, 
All am doing is running the app when I tried to type something on the textfield, nothing is typed and on the terminal display the information I sent above. I often has to reload the app to work and comes back again. 
Please find the info you requested below: and Thanks in advance
pro@PROs-MacBook-Pro afk-credits % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/harguilar/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/harguilar/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 92290B1A-8016-4029-A3A9-B99D77FAEEF2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
pro@PROs-MacBook-Pro afk-credits %

**Comment by maheshmnj** [comment] 2022-01-11 13:19
Thanks for the info Please follow up on this issue https://github.com/flutter/flutter/issues/96277. It would be great if you can identify what specific key combinations triggers the exception and what happens when the exception occurs, and comment on the linked issue.

Closing as a duplicate of the linked issue.

**Closed by maheshmnj** 2022-01-11 13:19 UTC
Labels: in triage

**Comment by harguilar** [comment] 2022-01-11 13:33
Man on my case is not any key combination at all, I just run the app once I tap on the textfield to start writing something the issues arises I cannot specifically tell you what caused and what not. All I see is just this behaviour.

**Comment by steeling** [comment] 2022-01-18 00:55
This is pretty debilitating when debugging. It happens to me roughly every 2 minutes, and sometimes the text input gets completely locked up to the point I need to do a full restart (~4-5 min build)
