### ISSUE TITLE
Navigator push/pop, state does not persists 

### ISSUE THREAD

**Issue by abaert** [flutter/flutter#55164] opened 2020-04-19 20:38 UTC
Hi there, when I push a new page, the state of the new page is not save when I pop it. Does someone knows how to fix this? 

Here, I have a heart icon on the new page, when I click it, it becomes white and it's sending the info to another page. But when I leave the page (with the pop) and come back, the state of the heart has changed.  

Thanks in advance! 
My code is quite big so I selected parts of it: 

```dart
final isAlreadySaved = favCoins.contains(widget.coin); 
children: <Widget>[
                    Row(children: <Widget>[
                              InkWell(
                                child :Padding(
                                  padding: EdgeInsets.only(bottom : 15),
                                  child: new Icon(
                                    Icons.arrow_back,
                                    color: Colors.white,
                                    size: 25,
                                  ),
                                ), 
                                onTap : (){
                                  setState((){
                                      Navigator.pop(
                                        context,
                                        MaterialPageRoute(builder: (context) =>HomeScreen()),
                                    );
                                  });
                                } 
                              )
                        ],)
                        Row( mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: <Widget>[
                              Text(widget.coin.name, style : TextStyle(color : Colors.white, fontSize :35)),
                              InkWell(
                                child :new Icon(
                                  isAlreadySaved ? Icons.favorite : Icons.favorite_border,
                                  color: Colors.white,
                                  size: 30,
                                ), 
                                onTap : (){
                                  setState((){
                                    isAlreadySaved ? favCoins.remove(widget.coin) : favCoins.add(widget.coin);
                                    HomePage(coin: widget.coin);
                                  });
                                }            
                              )
                        ],
                      ),
```

**Comment by TahaTesser** [comment] 2020-04-20 13:02
Hi @abaert 
Popping the page, destroys the page. I am not sure what you mean `the state of the new page is not save when I pop it.`

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-13 12:36
@abaert I hope you've found a solution, closing since this isn't an issue with flutter.
if you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-05-13 12:36 UTC
Labels: in triage, waiting for customer response
