### ISSUE TITLE
`CircularProgressIndicator` overflows container

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#138205] opened 2023-11-10 04:31 UTC
### Steps to reproduce

I put a `CircularProgressIndicator` inside a `SizedBox.square` which is inside a `Container`. I set `SizedBox.square.dimension` to `constraints.maxWidth, constraints.maxHeight` (using a `LayoutBuilder`).

### Expected results

The `CircularProgressIndicator` not overflowing its parent size.

### Actual results

The `CircularProgressIndicator` overflow its parent size. I checked the `Widget Inspector` and apparently it is taking the correct size but... the visuals shows the overflow.

I also put `Container.clipBehavior` to `Clip.antiAlias` and then the `CircularProgressIndicator` overflow was cutted off

### Screenshots or Video
https://github.com/flutter/flutter/assets/73592852/0cf7caff-ef51-473d-bf66-76eb5163f47e

https://github.com/flutter/flutter/assets/73592852/902d15e5-7af3-4e4b-b74d-7cb8c7ea0e53

**Comment by danagbemava-nc** [comment] 2023-11-10 10:14
Hi @busslina, this issue was fixed with https://github.com/flutter/flutter/pull/125945. By default the `strokeAlign` of `CircularProgressIndicator` is set to `CircularProgressIndicator.strokeAlignCenter` but you can set it to `CircularProgressIndicator.strokeAlignInside` and it will be contained within the container. 

I'll be closing this since it has already been fixed. 

If you still face this issue after setting  `CircularProgressIndicator.strokeAlignInside` kindly leave a comment below with a minimal complete reproducible code sample along with the output of `flutter doctor -v` so that we can investigate this issue. 

Thank you

**Closed by danagbemava-nc** 2023-11-10 10:14 UTC
Labels: in triage

**Comment by busslina** [comment] 2023-11-10 20:11
Ok, I don't have thes options yet. My Flutter version is:
```
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (3 months ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

I'm upgrading flutter...

**Comment by busslina** [comment] 2023-11-10 20:24
@danagbemava-nc It worked. Thank you very much
