### ISSUE TITLE
[google_maps_flutter] java.lang.IllegalStateException after upgrading to 1.12

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#48753] opened 2020-01-13 22:13 UTC
I cannot solve an issue with google maps ever since I followed this guide to upgrade to 1.12:

[Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#migrating-flutterview-uses)

Before the upgrade, the google maps worked fine on both iOS and Android. Now after upgrading and taking the steps in the guide, I get the errors below and cannot load the map on Android.

I have tried increasing the minimum sdk version as [seen here](https://github.com/flutter/flutter/issues/25714#issuecomment-498102303) and many different versions/channels of flutter.

Flutter run --verbose:

```
[ +183 ms] E/flutter (14843): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/google_maps
[  +14 ms] E/flutter (14843):   at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
[   +9 ms] E/flutter (14843):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
[   +1 ms] E/flutter (14843):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
[        ] E/flutter (14843):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/flutter (14843):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/flutter (14843):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/flutter (14843):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (14843):   at android.os.MessageQueue.next(MessageQueue.java:386)
[        ] E/flutter (14843):   at android.os.Looper.loop(Looper.java:175)
[        ] E/flutter (14843):   at android.app.ActivityThread.main(ActivityThread.java:7625)
[        ] E/flutter (14843):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (14843):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
[        ] E/flutter (14843):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
[        ] E/flutter (14843): , null)
[        ] E/flutter (14843): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter (14843): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] E/flutter (14843): <asynchronous suspension>
[        ] E/flutter (14843): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
[   +3 ms] E/flutter (14843): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
[        ] E/flutter (14843): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
[        ] E/flutter (14843): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
[        ] E/flutter (14843): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
[        ] E/flutter (14843): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
[        ] E/flutter (14843): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
[        ] E/flutter (14843): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] E/flutter (14843): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
[        ] E/flutter (14843): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
[        ] E/flutter (14843): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #18     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
[        ] E/flutter (14843): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
[        ] E/flutter (14843): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] E/flutter (14843): #30     RenderProxyBoxMixin.pe

```

Flutter doctor:

```
[√] Flutter (Channel master, v1.13.9-pre.69, on Microsoft Windows [Version 10.0.18362.535], locale en-CA)
    • Flutter version 1.13.9-pre.69 at C:\Users\madam\flutter
    • Framework revision 03a59bff03 (47 minutes ago), 2020-01-13 13:21:57 -0800
    • Engine revision 73d2fb374c
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 32ce9c7872)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\madam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270

[√] Connected device (1 available)
    • CLT L04 • DXU7N19105001128 • android-arm64 • Android 9 (API 28)

```

</details>

**Comment by dnfield** [comment] 2020-01-14 04:54
@mklim or @amirh might know

**Comment by mklim** [comment] 2020-01-14 18:11
Looks like a duplicate of #47921, going to close in favor of the older bug. Thank you for the stack trace!

**Closed by mklim** 2020-01-14 18:11 UTC
Labels: p: maps, plugin
