### ISSUE TITLE
Scrollbar should hide when content is completely displayed

### ISSUE THREAD

**Issue by khainke** [flutter/flutter#86035] opened 2021-07-07 19:56 UTC
## Use case
Im using the `Scrollbar` widget on a horizontal ListView like this:

```dart
class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key}) : super(key: key);

  final ScrollController colorListScrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: IntrinsicWidth(
          child: Scrollbar(
            controller: colorListScrollController,
            isAlwaysShown: true,
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              controller: colorListScrollController,
              child: Row(
                children: Colors.primaries
                    .map(
                      (c) => Container(
                        width: 32,
                        height: 64,
                        color: c,
                      ),
                    )
                    .toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

## Current Behavior / Issues
On startup of the application (web), the scrollbar is not visible:
![hidden-at-start](https://user-images.githubusercontent.com/4837890/124820134-5d9e0b00-df6d-11eb-9c92-0ede4296c30f.png)

On a resize of the app, the scrollbar becomes visible:
![visible-after-resize](https://user-images.githubusercontent.com/4837890/124820176-6b539080-df6d-11eb-9cb0-11601439d8f6.png)

After a second resize, the scrollbar remains visible, but the percentage of the handle to the track is somewhat messed up (marked area):
![visible-after-second-resize](https://user-images.githubusercontent.com/4837890/124820280-8e7e4000-df6d-11eb-9321-c2e7f514b0fb.png)

Similar issues also appear with desktop apps, i did not test with mobile systems.

## Proposal
1. Scrollbar should not be displayed, when entire content is on screen
2. Scrollbar handle should have correct percentage size with regard to the track, when resizing the window

Arguable the `isAlwaysShown` option could overwrite the first point, but i think this is the more wanted use case of a scrollbar.

## Complete Example 
main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scrollbar Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key}) : super(key: key);

  final ScrollController colorListScrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: IntrinsicWidth(
          child: Scrollbar(
            controller: colorListScrollController,
            isAlwaysShown: true,
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              controller: colorListScrollController,
              child: Row(
                children: Colors.primaries
                    .map(
                      (c) => Container(
                        width: 32,
                        height: 64,
                        color: c,
                      ),
                    )
                    .toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by xu-baolin** [comment] 2021-07-08 10:39
This is a duplicate of #75613, which aims to be fixed by #85499 and #82687
I am going to close this as a duplicate, but if you feel this is not the same issue, feel free to comment and we can re-open. Thank you!
CC @Piinks

**Closed by xu-baolin** 2021-07-08 10:39 UTC
Labels: a: desktop, f: scrolling, framework, passed first triage, platform-web, proposal, severe: new feature
