### ISSUE TITLE
build flutter engine with --no-prebuilt-dart-sdk tag can not success , stay at "STAMP ..."

### ISSUE THREAD

**Issue by zhaoshuyu** [flutter/flutter#109299] opened 2022-08-10 09:16 UTC
when i 
1. modify a dart sdk file in path "flutter_engine/src/third_party/dart/sdk/lib/async/zone.dart"
2. and build flutter engine with --no-prebuilt-dart-sdk tag
this build will run forever and can not succeed, it stays at "[5951/5971] STAMP obj/flutter/sky/sky.stamp"

## Logs

```
$ src % ninja -C out/host_release
ninja: Entering directory `out/host_release'
[5951/5971] STAMP obj/flutter/sky/sky.stamp
```

```
% flutter doctor -v
[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.5 21G72 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.1 at /Users/XXX/workspace/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/XXX/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Users/XXX/Downloads/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by zhaoshuyu** [comment] 2022-08-10 09:28
<img width="898" alt="image" src="https://user-images.githubusercontent.com/15855092/183866340-f29410ba-bfb8-4b59-aa33-8b29acf9f4cd.png">
monitor show dart:kernel-service_snapshot.dart.dill has running almost 2h.

**Comment by Thafseena** [comment] 2022-08-10 09:42
ok

**Comment by mraleph** [comment] 2022-08-10 10:12
Most likely your modification to the file has a bug of some sort. The build will run Dart code as part of the build, so if you modify Dart SDK in a wrong way your build will fail. 

Hard to say what exactly is going wrong without seeing the actual modification you are doing. I'd suggest to run build with `-v` and then debug the hanging command.

**Comment by zhaoshuyu** [comment] 2022-08-10 10:21
> 

when i stop last build, and start a new build with -v
this time the build stay at "touch obj/flutter/sky/sky.stamp"
<img width="558" alt="image" src="https://user-images.githubusercontent.com/15855092/183878054-f343cef7-70d2-4f37-bb1f-85801c3ae3c5.png">

i modify the dart file only add one line to print log
<img width="701" alt="image" src="https://user-images.githubusercontent.com/15855092/183878237-da9801eb-35b9-4c6e-ae8c-09a027840891.png">

**Comment by mraleph** [comment] 2022-08-10 12:19
@zhaoshuyu yeah, you can't do this. Tools used during the build written in Dart might be using `stdout` as a communication channel with other tools so you can't just `print` like that into `stdout`.

**Comment by mraleph** [comment] 2022-08-10 12:20
I am closing this because this is working as intended.

**Closed by mraleph** 2022-08-10 12:19 UTC
Labels: in triage
