### ISSUE TITLE
webview_flutter incorrectly serializes postMessage() calls

### ISSUE THREAD

**Issue by omnicron-llc** [flutter/flutter#124250] opened 2023-04-05 18:29 UTC
In JS:
window.Toast.postMessage({foo: 1, bar: 2})
This should serialize to '{"foo": 1, "bar": 2}' in JavascriptMessage.message for the VERY obvious reason that it skips having to manually encode the object and is more semantically correct. Instead we get {foo: 1, bar: 2} which while informative to a human is useless.

The problem was already opened as an issue at https://github.com/flutter/flutter/issues/75313 and summarily closed because of the absolutely asinine reason that the user did not give the output of flutter doctor - this is not a version or machine specific issue; it is an implementation fault that needs to be rectified, and it's flatly embarrassing that it wasn't remedied when the original issue reporter included the specific implementation change needed to fix the problem.

**Comment by stuartmorgan** [comment] 2023-04-05 18:53
Closing as a duplicate of https://github.com/flutter/flutter/issues/42986

> [...] because of the absolutely asinine reason [...] flatly embarrassing

Please take a moment to review our code of conduct before engaging further in our issue tracker.

> the original issue reporter included the specific implementation change needed to fix the problem

Which did not come as a PR, and was thus unusable since code that is not submitted with a signed CLA can't be accepted. It also didn't include any other necessary elements, since as tests.

It also ignored the fact that it was a breaking change.

You are certainly welcome to submit a complete PR, following the project's established process, that addresses the issue.

**Closed by stuartmorgan** 2023-04-05 18:53 UTC
