### ISSUE TITLE
I can't accept android-licenses

### ISSUE THREAD

**Issue by allowthere** [flutter/flutter#14942] opened 2018-02-28 03:00 UTC
## Steps to Reproduce

When I run `flutter build apk` and `flutter run` I get 

    Error running Gradle:
    Unable to download needed Android SDK components, as the following licenses have not been accepted:
    Android SDK Build-Tools 26.0.2, Android SDK Platform 27
    To resolve this, please run the following command in a Terminal:
    flutter doctor --android-licenses

But `flutter doctor --android-licenses` says 

     Warning: File /home/user/.android/repositories.cfg could not be loaded.         
     All SDK package licenses accepted.======] 100% Computing updates... 

So it looks like all license agreements were accepted. PS. I can build Android Apps in Android Studio.

## Flutter Doctor

    Flutter (on Linux, locale en_US.UTF-8, channel beta)
        • Flutter version 0.1.4 at /home/user/Downloads/flutter
        • Framework revision f914e701c5 (8 days ago), 2018-02-19 21:12:17 +0000
        • Engine revision 13cf22c284
        • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0
       ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mkhennoussi** [comment] 2018-02-28 17:24
Same here, same errors. Any ideas ?

Thanks !

**Comment by mkhennoussi** [comment] 2018-02-28 17:37
I found a solution... maybe it will work for you as it did for me (For me the issue was the` flutter create` command used the old android sdk folder). 
Please @allowthere , check your "local.properties" file in the android folder.
Be sure the "sdk.dir= " value points to the same folder as the ANDROID_HOME variable.

Hope it helps !

**Comment by cbracken** [comment] 2018-03-01 07:20
@allowthere would you mind including the entire output of `flutter doctor --verbose`, in particular the bit covering Android Studio?

Also, based on the `Downloaded executables cannot execute on host.` message, it looks like you may not have a 32-bit version of libstc++ installed. I actually just landed a patch (#15004) that improves the error message a bit. The new instructions read:
```
Downloaded executables cannot execute on host.
See https://github.com/flutter/flutter/issues/6207 for more information.

On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
On Fedora: dnf install libstdc++.i686
On Arch: pacman -S lib32-libstdc++5
```

It looks like there may be a mismatch between the Android Studio location that Flutter is detecting and the one in your `local.properties` file under your project's `android` directory. What @mkhennoussi suggested should work to fix the license issue (related issue: #13750). You'll also need to install the appropriate 32-bit libstdc++ library for the 32-bit AOT compiler to produce binaries for Android. The instructions above should help -- if not, please shout :)

**Comment by edufolly** [comment] 2018-03-03 21:43
@mkhennoussi I had the same problem. The solution works great for me. The Android SDK isn't on default path in OSX.

**Comment by WangChangQin** [comment] 2018-03-10 02:09
@mkhennoussi  Nice ,It works!

**Comment by MiltoxBeyond** [comment] 2018-05-08 22:37
I ran into this issue today and the recommendation didn't work.

`Run SDK_LOCATION\tools\bin\sdkmanager --licenses` instead of the recommendation to update.  It'll let you accept the missing licenses

**Comment by ramsung** [comment] 2018-06-02 07:08
I too had the same problem I rectified it by manually installing sdk version 26.0.2 from sdk manager in Android Studio. hope it helps!

**Comment by Wryhder** [comment] 2018-06-18 15:33
I have this problem as well. I've run `flutter doctor --android-licenses` more than a dozen times. Each time it tells me at the end `All SDK package licenses accepted` and then the next time I run it, it starts with `5 of 5 SDK package licenses not accepted. 100% Computing updates...`.
I am also unable to install the Flutter plugin in Android Studio. It's nowhere to be found. One time, I actually did see it, and then the next moment it was no longer in the list of plugins.

`flutter doctor --verbose` gives this:

```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_NG)
    • Flutter version 0.4.4 at /home/user/Programs/flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 2.2)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 145.971.7
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by egm24** [comment] 2018-06-24 23:52
@Wryhder Try running `sudo flutter doctor --android-licenses`

**Comment by Wryhder** [comment] 2018-06-25 10:20
@egm24 I installed Flutter in my home directory; running that gives me
```
sudo: flutter: command not found
```
I have successfully installed the Flutter plugin in Android Studio. Probably because I upgraded to version three point something from 2.2.
It took a few tries, but I also can now run a project. Still can't accept the licenses, though.
Output of `flutter doctor --verbose`:
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_NG)
    • Flutter version 0.5.1 at /home/user/Programs/flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK at /home/user/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /home/user/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.1)
    • Android Studio at /home/user/Programs/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.12.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by zoechi** [comment] 2018-06-25 11:02
@Wryhder that looks like you didn't add the `flutter/bin` directory to `PATH`

**Comment by Wryhder** [comment] 2018-06-25 13:36
@zoechi It's in my PATH.
Here's the result of `echo $PATH`:
```
/home/user/.local/share/umake/bin:/home/user/.rvm/gems/ruby-2.4.2/bin:/home/user/.rvm/gems/ruby-2.4.2@global/bin:/home/user/.rvm/rubies/ruby-2.4.2/bin:/home/user/.cargo/bin:/home/user/bin:/home/user/.local/bin:/home/user/.nvm/versions/node/v8.9.4/bin:/home/user/Programs/flutter/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:~/.pyenv/bin:/home/user/.local/share/umake/bin:/home/user/.cargo/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/user/.rvm/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/platform-tools:/home/user/Programs/flutter/bin/cache/dart-sdk/bin:/home/user/.rvm/bin:/home/user/.rvm/bin

```

**Comment by zoechi** [comment] 2018-06-25 14:01
@Wryhder please check if `/home/user/Programs/flutter/bin` contains a `flutter` executable for example by executing `/home/user/Programs/flutter/bin/flutter` and post the output.

**Comment by Wryhder** [comment] 2018-06-26 08:53
@zoechi Apologies for the late reply. I'm assuming I wouldn't be able to use Flutter at all if there weren't an executable in there?
Here's the output: 
```
~$ ~/Programs/flutter/bin/flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help            Print this usage information.
-v, --verbose         Noisy logging, including all shell commands executed.
-d, --device-id       Target device id or name (prefixes allowed).
    --version         Reports the version of this tool.
    --bug-report      Captures a bug report file to submit to the Flutter team (contains local paths, device
                      identifiers, and log snippets).

    --flutter-root    The root directory of the Flutter repository (uses $FLUTTER_ROOT if set).

Available commands:
  analyze          Analyze the project's Dart code.
  build            Flutter build commands.
  channel          List or switch flutter channels.
  clean            Delete the build/ directory.
  config           Configure Flutter settings.
  create           Create a new Flutter project.
  devices          List all connected devices.
  doctor           Show information about the installed tooling.
  drive            Runs Flutter Driver tests for the current project.
  emulators        List and launch available emulators.
  format           Format one or more dart files.
  fuchsia_reload   Hot reload on Fuchsia.
  help             Display help information for flutter.
  install          Install a Flutter app on an attached device.
  logs             Show log output for running Flutter apps.
  packages         Commands for managing Flutter packages.
  precache         Populates the Flutter tool's cache of binary artifacts.
  run              Run your Flutter app on an attached device.
  screenshot       Take a screenshot from a connected device.
  stop             Stop your Flutter app on an attached device.
  test             Run Flutter unit tests for the current project.
  trace            Start and stop tracing for a running Flutter app.
  upgrade          Upgrade your copy of Flutter.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.
```

**Comment by zoechi** [comment] 2018-06-26 08:56
@Wryhder sorry, seems I misinterpreted the error message.

> sudo: flutter: command not found

Perhaps it means the `sudo` command was not found or `sudo: flutter` was not found. 
Actually I find it hard to tell :D

**Comment by Wryhder** [comment] 2018-06-26 09:14
@zoechi I get that kind of error message when I append `sudo` to a command that doesn't require it. I installed Flutter in my home directory, so I don't need `sudo` to run it.
If, however, I'd installed it in `/opt/` or `/usr/local/share/`, I _might_ need `sudo`.
I just tried to run `sudo npm -g ls`, and I got a similar error message. However, plain `npm -g ls` works.

**Comment by zoechi** [comment] 2018-06-26 09:28
@Wryhder https://unix.stackexchange.com/questions/245772/why-running-command-as-sudo-returns-command-not-found
You can also check https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components but this might have changed since the answers were posted, but I think it's worth a try.

**Comment by cbracken** [comment] 2018-06-26 17:53
@Wryhder this looks to me as though flutter isn't on the `PATH` when sudo'ed to root. If you wanted to do this, I would run `sudo /absolute/path/to/flutter/bin/flutter`. 

That said, generally you should avoid running flutter as root; in fact, Flutter includes [checks to warn people](https://github.com/flutter/flutter/blob/579116412f5deb17f7b8cef3d8e4aa484a6e6b0e/bin/flutter#L132-L138) specifically not to do this.

If the issue is that flutter thinks you haven't yet accepted the licences, you could try running the sdkmanager command directly:
```
~/Library/Android/sdk/tools/bin/sdkmanager --licenses
```
and see if that helps.

**Comment by Wryhder** [comment] 2018-06-28 10:40
@cbracken @zoechi @egm24 Thanks a lot!

`sudo /home/user/Programs/flutter/bin/flutter doctor --android-licenses` worked.
I accepted the licenses, and when I ran `~/Android/Sdk/tools/bin/sdkmanager --licenses` (just to make sure), I got
```
Loading local repository...
All SDK package licenses accepted.======] 100% Computing updates...
```

**Comment by Nullstr1ng** [comment] 2018-08-09 07:53
regarding the licenses, after accepting all 6 licenses, it still wont work and Flutter keeps saying that I should I accept the licenses which I have done several times... 

SOLUTION I found was:
I ran the Command as Administrator and accepted all licenses and now its working

**Comment by sahil904** [comment] 2018-09-27 10:49
flutter doctor --android-licenses
and agree for licenses type y
this is the best soloution for this issue

**Comment by nb312** [comment] 2018-11-02 10:01
> I ran into this issue today and the recommendation didn't work.
> 
> `Run SDK_LOCATION\tools\bin\sdkmanager --licenses` instead of the recommendation to update. It'll let you accept the missing licenses

This is work for me, thanks.

**Comment by ENOONE** [comment] 2019-01-22 06:02
I ran into the same issue today. And I figured it out. Just install the sdk 27 in android studio. I only have 28 for my android and that was the issue.

**Comment by zoechi** [comment] 2019-01-22 07:48
For
```
   > Failed to install the following Android SDK packages as some licences have not been accepted.
       platforms;android-27 Android SDK Platform 27
```
see also #26832

**Comment by thgoebel** [comment] 2019-01-22 18:43
Here's what fix the issue for me:
Since `flutter doctor -v` said `Platform android-28, build-tools 28.0.3`
but `flutter run` complained about `Android SDK Platform 27, Android SDK Build-Tools 26.0.2
` I installed that version by running 

```/home/user/Android/Sdk/tools/bin/sdkmanager --install "build-tools;26.0.2"```

Note that it then asks you to accept the license for that version as well, plus you might need to [fix java](https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a/51644855#51644855)

**Comment by abakim** [comment] 2019-04-21 04:36
I solved it configuring java SDK 1.8 and Android API 28 in "Project Structure" (File->Project Structure).
![imagen](https://user-images.githubusercontent.com/25142449/56465552-bb1dff80-63d5-11e9-9ded-9ec26e004f83.png)
![imagen](https://user-images.githubusercontent.com/25142449/56465553-bf4a1d00-63d5-11e9-9a0e-dbd2184b3f85.png)

**Comment by iapicca** [comment] 2019-11-01 12:50
Hi @allowthere 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 12:50 UTC
Labels: t: flutter doctor, tool, ▣ platform-android

**Comment by buster95** [comment] 2019-12-03 00:32
I resolve this running cmd like administrator and in linux running with sudo

**Comment by essdiel** [comment] 2020-02-12 04:25
I resolved this in Linux by running
`sudo yes | sdkmanager --licenses`
to accept all licenses.

**Comment by abhisada** [comment] 2020-11-10 06:16
> I found a solution... maybe it will work for you as it did for me (For me the issue was the` flutter create` command used the old android sdk folder).
> Please @allowthere , check your "local.properties" file in the android folder.
> Be sure the "sdk.dir= " value points to the same folder as the ANDROID_HOME variable.
> 
> Hope it helps !

Sir, can you please elaborate a little more .. after opening  local.properties file what I to do??

**Comment by sushanth-hrn** [comment] 2021-04-28 06:40
![image](https://user-images.githubusercontent.com/62287403/116357914-b0936d80-a81a-11eb-81c5-104862258c10.png)

**Comment by exerror14** [comment] 2021-06-15 05:06
[All Possible solution added [Solved] Flutter run error: You have not accepted the license agreements](https://fluttercorner.com/flutter-run-error-you-have-not-accepted-the-license-agreements/)
