### ISSUE TITLE
Scrollbar thumb doesn't follow the mouse when dragged in reversed list

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#88779] opened 2021-08-24 11:32 UTC
This is likely a duplicate #81035, which was closed, but I have no idea why, so opening a new one

## Example

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          reverse: true,
          itemCount: 100,
          itemBuilder: (_, i) {
            return ListTile(title: Text('Item $i'));
          },
        ),
      ),
    );
  }
}
```

**Expected results:** 

Thumb follows the mouse when dragged

**Actual results:** 

Thumb goes in the opposite direction

https://user-images.githubusercontent.com/6261302/130609175-cfab6f70-5f1a-4244-9030-9a47aeb79c8f.mov

**Flutter version**
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by TahaTesser** [comment] 2021-08-24 12:34
Hi @lesnitsky 
Thanks for filing the issue, I can reproduce this on  `stable, 2.2.3`, however, this has been fixed in later channels. I cannot reproduce it on the latest beta channel 

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v` 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on Microsoft Windows [Version 10.0.22000.160], locale en-US)
    • Flutter version 2.5.0-5.2.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (6 days ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31613.86
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • SM M025F (mobile)       • R9ZR205XX0A   • android-arm    • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.160]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```

</details>

Closing as duplicate of https://github.com/flutter/flutter/issues/81035

**Closed by TahaTesser** 2021-08-24 12:34 UTC
Labels: in triage
