### ISSUE TITLE
Flutter Regex is slower in Release mode then Dev

### ISSUE THREAD

**Issue by nicolasmansour** [flutter/flutter#60243] opened 2020-06-24 22:47 UTC
I have a regex extension method that removes diacritics from Arabic text
  String removeDiacritics(){
    return this.replaceAll(RegExp(r'[\u{0640}\u{064D}\u{064C}\u{064B}\u{064E}\u{064F}\u{0650}\u{0651}\u{0652}]', unicode:true), '')
      .replaceAll(RegExp(r'[\u{0623}\u{0625}]', unicode:true),'\u{0627}');
  }
I iterate through a list of 31102 records and call this method for every record. In dev mode it takes about 800 milliseconds to process, in release mode it takes about 10 seconds. Attached is the Arabic tab delimited file I load into a list then iterate and remove diacritics.
[vdv.txt](https://github.com/flutter/flutter/files/4828210/vdv.txt)

**Comment by jonahwilliams** [comment] 2020-06-24 22:50
Duplicate of https://github.com/dart-lang/sdk/issues/37785

**Closed by jonahwilliams** 2020-06-24 22:50 UTC
