### ISSUE TITLE
How to buy subscription upgrade

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#51535] opened 2020-02-27 04:25 UTC
In Android, subscription can be upgrade or downgrade using [setOldSku](https://developer.android.com/google/play/billing/billing_subscriptions.html#Allow-upgrade) method. Is that API expose in in_app_purchase plugin?

**Comment by rahulraj64** [comment] 2020-03-06 07:18
Not yet. Duplicate of https://github.com/flutter/flutter/issues/32395

**Comment by VladyslavBondarenko** [comment] 2020-03-17 16:14
Duplicate of https://github.com/flutter/flutter/issues/32395

**Closed by VladyslavBondarenko** 2020-03-17 16:14 UTC
Labels: d: stackoverflow, documentation, p: first party, p: in_app_purchase, plugin
