### ISSUE TITLE
firebase_admob-0.9.3+2 - AdRequestBuilderFactory.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by zpaya** [flutter/flutter#56234] opened 2020-05-03 12:46 UTC
## Steps to Reproduce
1. Build flutter for release with command `flutter build appbundle`
Command executed successfully but with a Note below

> Note: /home/zini/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.

**Output file of below command:**
flutter doctor -v
[flutter doctor -v.txt](https://github.com/flutter/flutter/files/4570285/flutter.doctor.-v.txt)

flutter run --verbose
[flutter run --verbose.txt](https://github.com/flutter/flutter/files/4570298/flutter.run.--verbose.txt)

pubspec.yml
[pubspec.yml.txt](https://github.com/flutter/flutter/files/4570299/pubspec.yml.txt)

Will this cause my ads to display after uploading app to play store?

**Comment by iapicca** [comment] 2020-05-04 06:36
Hi @zpaya  
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-04 06:36 UTC
