### ISSUE TITLE
Helpy

### ISSUE THREAD

**Issue by geep33** [flutter/flutter#70943] opened 2020-11-20 15:02 UTC

**Comment by sidrao2006** [comment] 2020-11-20 15:39
Hello @geep33 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?

Or if you opened this issue by mistake, please close it

Thank you!

**Comment by YeungKC** [comment] 2020-11-20 16:31
Because the issue does not have any valid information, I will close the issue.

I will reopen it if there is a valid information update.

**Closed by YeungKC** 2020-11-20 16:31 UTC
