### ISSUE TITLE
Optimize setIsVolatile for Path

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58870] opened 2020-06-06 17:27 UTC
Internal: b/174239851

We had some performance issue that's related with `SkPath::setIsVolatile` before: https://github.com/flutter/flutter/issues/17889. That issue was closed because Skia introduced CCPR and it has a nice performance even without `setIsVolatile`.

Unfortunately, CCPR was later disabled https://github.com/flutter/flutter/issues/17889#issuecomment-481522785 and we're seeing this issue again.

In particular, here's a comparison of our `cubic_bezier_perf__timeline_summary` benchmark with and without `setIsVolatile` (using https://github.com/flutter/flutter/commit/8b201b988b710323bcba5349952b227d1da37f1d and https://github.com/flutter/engine/commit/1482d9b05e3cb0b0ebd36555e5e30bc8f2734770):

|   | without setIsVolatile | with setIsVolatile |
| --- | --- | --- |
|  90th_percentile_frame_rasterizer_time_millis | 24.108 | 13.95 |
|  99th_percentile_frame_rasterizer_time_millis | 47.098 | 18.366 |

In addition to the speed improvement, `setIsVolatile(true)` should also improve the memory usage as Skia will no longer cache the volatile paths.

As path animations get more and more popular through Rive/Flare among our customers such as "customer: money (g3)" and "customer: dream (g3)", having `setIsVolatile` may become more and more beneficial (see, e.g., https://github.com/flutter/flutter/issues/57686).

**Comment by liyuqian** [comment] 2020-06-06 17:43
CC @Hixie @chinmaygarde, we probably should revive https://github.com/flutter/engine/pull/5560.

Luckily, we have better ways to test memory now (thanks to @dnfield @terrylucas @iskakaushik @albertwang0116). To figure out whether we should `setIsVolatile(true)` by default, we could use our new tools to benchmark the CPU, GPU, and memory usage of this `cubic_bezier_perf` benchmark or some other more realistic Rive/Flare animations.

Also CC @pcsosinski @zoeyfan @mehmetf @jasonch99 to see how customers think about this issue, and what priority it has.

**Comment by dnfield** [comment] 2020-06-06 17:50
What if we just set the path as volatile until we actually draw it, after which we don't expect to modify it anymore?

**Comment by liyuqian** [comment] 2020-06-06 17:58
@dnfield : `setIsVolatile` is kind of like `setIsDrawingOnlyOnce` which disables Skia to cache the path mask. So even if a path is not modified later, if that path is only drawn once, `setIsVolatile` still saves a lot of performance.

**Comment by dnfield** [comment] 2020-06-06 18:21
Once as in only to one SkPicture, or once as in the picture is drawn only once?

I'm not sure how a flutter developer would ever know whether to set this flag or not.

**Comment by Hixie** [comment] 2020-06-06 23:46
> I'm not sure how a flutter developer would ever know whether to set this flag or not.

This is why we haven't exposed flags like this in the past. Unless we can solve this problem, we will definitely have people setting the flag at the wrong time and making things worse.

**Comment by liyuqian** [comment] 2020-06-08 18:58
Once as in the picture is drawn only once.

I think we should set the default value to best fit most people, and leave an option for experts who will run benchmarks and figure out what's best for their use cases (e.g., Rive engineers).

Following Ian's earlier suggestion of introducing a new class, do you think the following class would be clear enough?
```
/// A [Path] that's expected to be drawn only once in the current frame,
/// and will never be drawn again in future frames.
///
/// This class aims purely at improving the performance of those one-time paths
/// by disabling some unnecessary caching. It has exactly the same visual result
/// and APIs as [Path].
class VolatilePath extends Path {
  ...
}
```

**Comment by Hixie** [comment] 2020-06-08 19:17
> leave an option for experts who will run benchmarks and figure out what's best for their use cases (e.g., Rive engineers).

I 100% guarantee that such an API will be used by non-experts incorrectly. Here's a non-exhaustive list of ways it could happen:

1. Someone finds out about this API by looking at the API docs, and writes an unclear blog post with the title "One quick trick to improve your Flutter performance" and some sample code that people start cargo-culting into their app.
2. Someone includes this API in a YouTube video of "Top 10 Flutter APIs you didn't know about" and mentions that it's good for performance. Half a million viewers start using this API everywhere they can because "it's good for performance".
3. We work hard to hide the API so that only experts find it. Someone discovers its existence and tweets about it. Because it's an attractive "experts only" API and people like thinking they're experts, they start using it, even though it's inappropriate for them.
4. Someone uses it correctly in a library. Someone else forks that library and changes how it works, and now the library uses the API incorrectly.
5. Someone finds a library that uses it correctly, and cargo-cults its code into their app.

We should avoid having APIs that are traps like this. Otherwise, what will happen is five years from now we'll be making this API a no-op because people misuse it so much that it's better to just ignore calls to the API and use heuristics than it is to honor the API. (And we won't be able to remove it because that would break too many apps, so it'll just be a vestigial API.)

As an aside, introducing a new subclass for Path might turn every call to Path from a direct dispatch to a polymorphic dispatch, we should check with the VM folks.

**Comment by liyuqian** [comment] 2020-06-08 19:48
I see. So it seems that our goal is to setIsVolatile internally using some heuristics, and not expose an API for developers?

The information needed for making the heuristic decision seems to be only available on the Skia level. @reed-at-google @bsalomon : can Skia set the path as volatile by default, and turn it to non-volatile once the path is rasterized multiple times? To preserve the old behavior, we could only enable that heuristics under some opt-in flag such as `SkPath::setDynamicVolatility`.

To @Hixie : sorry that I remember something wrong. Your suggestion was not about a new class, but a new constructor for `Path`. So it should be something like `Path.makeVolatile` and we shouldn't have the polymorphic dispatch problem?

Finally, we can always just `setIsVolatile(true)` for all paths in Flutter if it's at least better than `setIsVolatile(false)` for all paths in Flutter. Hence I'm renaming this issue's title from "Expose setIsVolatile for Path" to "Optimize setIsVolatile for Path".

**Comment by Hixie** [comment] 2020-06-08 21:34
I don't know enough about setIsVolatile to say what out goal should be, just that it's one of those mysterious APIs that I predict will get misused. :-)

Re the polymorphic dispatch thing, it's probably worth doing a one-off benchmark to see what the impact is. There's almost certainly areas of our framework where we fall prey to this problem today, might be a good place to look for optimizations in general if it's an actual thing.

**Comment by dnfield** [comment] 2020-06-08 21:52
I strongly suspect that most users are using paths as volatile - basically, once it gets drawn to a picture, it's not used again or explicitly drawn to another picture.

**Comment by dnfield** [comment] 2020-06-09 04:06
I'm a bit curious about why we can't just set the flag once the path is actually drawn to a second canvas - or _maybe_ once a sub-picture is drawn to another picture, but I'm not sure if that's "too late" to get whatever caching benefits Skia provides there.

I'm also a bit curious about whether this would impact the rest of our `draw*` operations on `Canvas`, which all boil down to paths internally in Skia. Presumably _all_ of those paths should be marked as non-volatile, but I'd think that Skia should be doing that internally if it isn't already.

**Comment by liyuqian** [comment] 2020-06-09 16:31
I just discussed with the Skia team and it seems that there are two ways of set volatility in Flutter by heuristics:
1. Design and utilize our own display list structure instead of `SkPicture`. @chinmaygarde , you mentioned that you're going to work on this after Metal. What's the progress now?
2. If we're still using `SkPicture`, we can play the picture into a custom canvas and intercepting all paths and set their volatility accordingly.

**Comment by chinmaygarde** [comment] 2020-07-13 18:31
@liyuqian: I see you added the customer tags. Can you xreference them to upstream bugs?

**Comment by liyuqian** [comment] 2020-07-13 19:04
@chinmaygarde : sure, I added https://github.com/flutter/flutter/issues/57686 which was created by jasonch@google.com

**Comment by dnfield** [comment] 2020-09-10 07:42
Local testing indicates that just setting all paths to volatile reduces memory usage in Flare/Rive heavy applications. I have not attempted measuring impact on frame times, but given above I would assume they're better.

I think as long as this doesn't hurt any of our existing benchmarks by much, we should consider just always setting this to true.

**Comment by dnfield** [comment] 2020-09-10 08:37
Unfortunately, on the new gallery transitions perf, there's a significant regression by setting paths to volatile. This is from a Pixel 4:

before:

```
    "average_frame_build_time_millis": 2.182658033826637,
    "90th_percentile_frame_build_time_millis": 3.462,
    "99th_percentile_frame_build_time_millis": 18.605,
    "worst_frame_build_time_millis": 65.617,
    "missed_frame_build_budget_count": 38,
    "average_frame_rasterizer_time_millis": 6.199544109878487,
    "90th_percentile_frame_rasterizer_time_millis": 10.82,
    "99th_percentile_frame_rasterizer_time_millis": 22.746,
    "worst_frame_rasterizer_time_millis": 122.53,
    "missed_frame_rasterizer_budget_count": 50,
    "frame_count": 1892,
    "frame_rasterizer_count": 1893,
```
after:
```
    "average_frame_build_time_millis": 2.27074847645429,
    "90th_percentile_frame_build_time_millis": 3.796,
    "99th_percentile_frame_build_time_millis": 23.051,
    "worst_frame_build_time_millis": 120.86,
    "missed_frame_build_budget_count": 40,
    "average_frame_rasterizer_time_millis": 10.10648753462602,
    "90th_percentile_frame_rasterizer_time_millis": 13.296,
    "99th_percentile_frame_rasterizer_time_millis": 29.086,
    "worst_frame_rasterizer_time_millis": 135.314,
    "missed_frame_rasterizer_budget_count": 117,
    "frame_count": 1805,
    "frame_rasterizer_count": 1805,
```

Average only goes down a bit, but worst gets a lot worse.

**Comment by dnfield** [comment] 2020-11-19 19:13
I have another approach for this that I think will work - locally it seems to reduce transition time as well. Should have a patch up for review shortly, trying to run some more benchmarks as well.

**Comment by dnfield** [comment] 2020-11-19 19:14
At a high level, my new approach does this:

- setIsVolatile(true) by default
- setIsVolatile(false) once the path is drawn twice
- setIsVolatile(true) if the path is mutated even if it was drawn twice

**Comment by dnfield** [comment] 2020-11-19 22:13
Update: my approach is not using fml::WeakPtr correctly. I think we should be able to fix this by refactoring some things in fml/tonic - going to try to get that done first.

**Comment by liyuqian** [comment] 2020-11-19 23:07
I'm still curious about your approach so is there any code I can read? Specifically, I'm very interested in how to track if a path in an SkPicture has been painted twice.

**Comment by dnfield** [comment] 2020-11-19 23:24
I'll upload what I have while I work on the other piece.

**Comment by dnfield** [comment] 2020-11-19 23:26
I'm not quite looking to see if it's rendered more than once, I'm really just checking if the path is still alive after a couple frames. If it is alive I assume it'll be drawn again and set the flag.

**Comment by dnfield** [comment] 2020-11-19 23:26
https://github.com/flutter/engine/pull/22620

**Comment by liyuqian** [comment] 2020-11-19 23:31
I see. So if a path gets destructed in 1 frame, but ends up being recorded and re-rasterized in multiple frames with the same SkPicture, your approach will still mark it as volatile, and pay some potential performance cost? Do you have a number comparison like https://github.com/flutter/flutter/issues/58870#issuecomment-690084259 ?

**Comment by dnfield** [comment] 2020-11-19 23:44
Yes - 

baseline
```
    "average_frame_build_time_millis": 2.2711369294605817,
    "90th_percentile_frame_build_time_millis": 3.21,
    "99th_percentile_frame_build_time_millis": 19.642,
    "worst_frame_build_time_millis": 60.696,
    "missed_frame_build_budget_count": 18,
    "average_frame_rasterizer_time_millis": 5.746145228215772,
    "90th_percentile_frame_rasterizer_time_millis": 10.647,
    "99th_percentile_frame_rasterizer_time_millis": 26.335,
    "worst_frame_rasterizer_time_millis": 87.355,
    "missed_frame_rasterizer_budget_count": 23,
    "frame_count": 1205,
    "frame_rasterizer_count": 1205,
```
after
```
    "average_frame_build_time_millis": 2.309207407407407,
    "90th_percentile_frame_build_time_millis": 3.059,
    "99th_percentile_frame_build_time_millis": 18.608,
    "worst_frame_build_time_millis": 54.183,
    "missed_frame_build_budget_count": 17,
    "average_frame_rasterizer_time_millis": 5.269529654036252,
    "90th_percentile_frame_rasterizer_time_millis": 9.842,
    "99th_percentile_frame_rasterizer_time_millis": 24.982,
    "worst_frame_rasterizer_time_millis": 60.98,
    "missed_frame_rasterizer_budget_count": 21,
    "frame_count": 1215,
    "frame_rasterizer_count": 1214,
```

And it substantially reduces graphics memory usage on the rive-app/example.

**Comment by liyuqian** [comment] 2020-11-21 00:57
Cool! I wonder if you can also add a per-frame-tracing that counts how many paths are volatile and how many paths are non-volatile in https://github.com/flutter/engine/pull/22620? I think it might be useful to better understand the behavior and debug future performance changes.

**Comment by MrBirb** [comment] 2020-12-12 11:41
Looks like PR was merged

**Comment by dnfield** [comment] 2020-12-12 16:31
Was reverted, should be relanded again soon though

**Comment by dnfield** [comment] 2020-12-21 21:54
Had to be reverted again - the implementation caused non-deterministic screen diff test behavior. Should be fixable.

**Closed** 2020-12-22 16:25 UTC
Labels: P2, customer: dream (g3), customer: money (g3), engine, passed first triage, perf: memory, perf: speed, severe: performance, waiting for PR to land (fixed)
