### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The syntax for the file name, directory name or volume label is incorrect, errno = 123

### ISSUE THREAD

**Issue by xMinecraftPro5x** [flutter/flutter#138505] opened 2023-11-15 19:11 UTC
## Command
```
flutter create (D:)
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The syntax for the file name, directory name or volume label is incorrect, errno = 123

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      IosProject.existsSync (package:flutter_tools/src/xcode_project.dart:214:50)
#6      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:137:13)
#7      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:63)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:242:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous cl  _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      IosProject.existsSync (package:flutter_tools/src/xcode_project.dart:214:50)
#6      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:137:13)
#7      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:63)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:242:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>osure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>  _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      IosProject.existsSync (package:flutter_tools/src/xcode_project.dart:214:50)
#6      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:137:13)
#7      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:63)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:242:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)

**Comment by danagbemava-nc** [comment] 2023-11-16 07:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99954.

**Closed by danagbemava-nc** 2023-11-16 07:26 UTC
Labels: in triage
