### ISSUE TITLE
Firebase core failed to resolve all the pendency, How can I resolve this error?

### ISSUE THREAD

**Issue by tfkcoder** [flutter/flutter#130890] opened 2023-07-19 13:54 UTC
![error](https://github.com/flutter/flutter/assets/102759674/e6cc94f4-3674-492d-9ba0-90300e55587b)

**Comment by dam-ease** [comment] 2023-07-19 15:08
Hi @tfkcoder 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Also, kindly refrain from posting pictures if not necessary. 
Closing this issue, since very little information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion.
Thank you.

**Closed by dam-ease** 2023-07-19 15:08 UTC
Labels: in triage
