### ISSUE TITLE
Widget size is displayed incorrectly when switching monitors

### ISSUE THREAD

**Issue by KennyYi** [flutter/flutter#89521] opened 2021-09-06 00:29 UTC
## Steps to Reproduce

1. Need two monitors with different resolutions
2. Run flutter web app `flutter run -d chrome`
3. Move web page to another monitor

* I use the default counter app for testing.

**Expected results:** 

The proportions of the widgets should not change.

**Actual results:** 

![Screen Shot 2021-09-06 at 9 00 33](https://user-images.githubusercontent.com/18023504/132145446-aaff76d8-90fc-4160-942c-976cfd2bb8d7.png)

<img width="762" alt="Screen Shot 2021-09-06 at 9 00 49" src="https://user-images.githubusercontent.com/18023504/132145453-4e72b3df-4823-4203-87cf-2ac0b751a3df.png">

<details>
  <summary>Logs</summary>

```
```

```
Analyzing web_sample...                                                 
No issues found! (ran in 1.3s)
```

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (9 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
kenny@Kennyui-MacBookPro web_sample % flutter doctor -v    
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-KR)
    • Flutter version 2.2.3 at /Users/kenny/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kenny/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kenny/Library/Android/sdk
    • Java binary at: /Users/kenny/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

**Comment by khari998** [comment] 2021-09-06 02:18
I was getting something like this too. Sometimes it would adapt just fine, other times it would not. To get rid of it, I would just refresh the page on the new monitor but it is annoying. The behavior has been inconsistent for me.

**Comment by TahaTesser** [comment] 2021-09-06 11:35
Hi @KennyYi 
Does this happen on a desktop app? I will try both at home later tonight

**Comment by KennyYi** [comment] 2021-09-06 23:41
@TahaTesser This happens on a web app (`flutter run -d chrome`). I run my app on a macbook.

**Comment by TahaTesser** [comment] 2021-09-07 07:28
Hi @KennyYi 
I just tried a monitor attached to an MBP on the latest `stable` using `flutter run -d chrome` 

### MBP
<img width="1011" alt="Screenshot 2021-09-07 at 10 26 01" src="https://user-images.githubusercontent.com/48603081/132302504-0740c687-0418-47de-80cd-0da4ac340275.png">

### Monitor
![Screenshot 2021-09-07 at 10 24 33](https://user-images.githubusercontent.com/48603081/132302512-8aa7ca7d-300c-4af8-8f99-d55878fb8a97.png)


Is one of the monitors scaled up? Resize web app somehow? There is a known issue for this https://github.com/flutter/flutter/issues/77084

Also, can you please desktop app?

**Comment by KennyYi** [comment] 2021-09-08 00:05
This will make it easier to check.

1. Make your web app to fit your Monitor screen (Not full screen mode)

**Monitor**
![Screen Shot 2021-09-08 at 8 51 52 (2)](https://user-images.githubusercontent.com/18023504/132424693-5b9ad5c4-15a5-48ed-95f6-80dfffad4e34.png)

**MBP**
<img width="538" alt="Screen Shot 2021-09-08 at 8 51 52" src="https://user-images.githubusercontent.com/18023504/132424816-0f027321-e7b5-4f07-8474-678802b8960d.png">


2. Drag web app to your MBP fast

**Monitor**
![Screen Shot 2021-09-08 at 8 52 31 (2)](https://user-images.githubusercontent.com/18023504/132424791-ef6b0a08-d7a0-432b-8b51-e3e13dca2bf2.png)

**MBP**
<img width="538" alt="Screen Shot 2021-09-08 at 8 52 31" src="https://user-images.githubusercontent.com/18023504/132424805-0328681e-1dba-42c1-b424-164dae3d8c4d.png">


* MBP resolution is bigger than the other monitor.
* I tried with the macOS app, this issue hasn't happend.

**Comment by maheshmnj** [comment] 2021-09-08 04:53
Not sure if this is related but I am facing a similar issue when moving a [flutter web app](http://vocabhub.web.app/) from mac to another desktop the app resizes absurdly sometimes. The app is built on the latest `master channel 2.6.0`


https://user-images.githubusercontent.com/31410839/132448444-f35c4f21-08c2-4982-b718-27c402a1d42f.mov

**Comment by TahaTesser** [comment] 2021-09-08 06:30
Hi @KennyYi @maheshmnj 
Thanks for the reproduction, the issue is not actually caused by switching monitor but resizing the window, you guys are hitting https://github.com/flutter/flutter/issues/77832
Closing as duplicate of https://github.com/flutter/flutter/issues/77832

**Closed by TahaTesser** 2021-09-08 06:30 UTC
Labels: in triage

**Comment by TahaTesser** [comment] 2021-09-08 13:07
Just to be clear, you can see resolution changes even in other apps (non-flutter) when switching one resolution to another resolution display but here when you resize the web window, it doesn't scale properly hence https://github.com/flutter/flutter/issues/77084

**Comment by maheshmnj** [comment] 2021-09-28 11:48
This is likely a duplicate of https://github.com/flutter/flutter/issues/77605
