### ISSUE TITLE
Exception after wrapping ListView in a Column

### ISSUE THREAD

**Issue by ehcpdeveloper** [flutter/flutter#78726] opened 2021-03-21 12:58 UTC
## Steps to Reproduce

Create a ListView in a page, 

```
body: new ListView.builder(
            itemCount: data == null ? 0 : data.length,
            itemBuilder: (BuildContext context, int index) {
              return new_item(data[index]);
            },
          ),

```
Run page. it runs normal. 

wrap ListView with a Column container:

```
body: Column(
        children: [
          new ListView.builder(
                itemCount: data == null ? 0 : data.length,
                itemBuilder: (BuildContext context, int index) {
                  return new_item(data[index]);
                },
              ),
        ],
      ),
```

run page. it raises exception:

```
======== Exception caught by rendering library =====================================================
Vertical viewport was given unbounded height.
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderViewport#8c6b1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderViewport#8c6b1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderIgnorePointer#3aaf0 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderSemanticsAnnotations#ba87d relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderPointerListener#5c1a1 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
====================================================================================================
Reloaded 4 of 629 libraries in 862ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderSemanticsGestureHandler#4c81d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ListView file:///Users/vidinlib/Documents/personal/flutter/siparis/lib/Sepet.dart:64:15
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:119:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
...
The following RenderObject was being processed when the exception was fired: RenderPointerListener#aa164 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...  size: MISSING
...  behavior: deferToChild
...  listeners: signal
RenderObject: RenderPointerListener#aa164 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
  size: MISSING
  behavior: deferToChild
  listeners: signal
...  child: RenderSemanticsGestureHandler#4c81d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...    size: MISSING
...    gestures: <none>
...    child: RenderPointerListener#5c1a1 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...      size: MISSING
...      behavior: opaque
...      listeners: down
...      child: RenderSemanticsAnnotations#ba87d relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...        size: MISSING
...        child: RenderIgnorePointer#3aaf0 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...          size: MISSING
...          ignoring: false
...          ignoringSemantics: false
====================================================================================================
```

flutter analyze output:
lots of info output, no error output. 

```
$ >flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Unable to find any JVMs matching version "1.8".
Unable to find any JVMs matching version "1.8".
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale de-DE)
⡿Unable to find any JVMs matching version "1.8".
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```
I am using/testing currently on ios emulator, thats why I dont need android studio.

**Comment by SushantChandla** [comment] 2021-03-21 13:15
https://stackoverflow.com/questions/45669202/how-to-add-a-listview-to-a-column-in-flutter

**Comment by ehcpdeveloper** [comment] 2021-03-21 13:59
Thank you for info.
That solves the issue. 
I was expecting that I can directly use such widget...

**Comment by iapicca** [comment] 2021-03-21 15:08
> That solves the issue.

@ehcpdeveloper if the issue is solved consider closing it

**Comment by Ossabla** [comment] 2021-03-21 19:42
@ehcpdeveloper The solution has been found, so please close the issue.

**Comment by pedromassangocode** [comment] 2021-03-22 10:16
Based on the last four comments, I feel safe to close this issue.
Thank you

**Closed by pedromassangocode** 2021-03-22 10:16 UTC
Labels: in triage

**Comment by ehcpdeveloper** [comment] 2021-03-22 11:06
Sorry, I did not see latest comments in last day.
