### ISSUE TITLE
25% regression in `web_benchmarks_skwasm`:`bench_material3_scroll_semantics.skwasm.drawFrameDuration.average`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144254] opened 2024-02-27 20:48 UTC
Introduced in https://github.com/flutter/flutter/pull/144208

[skia perf](https://flutter-flutter-perf.skia.org/e/?keys=Xd5aae662d37d65b97e4cd71a25028fc2&selected=commit%3D39546%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dbench_material3_scroll_semantics.skwasm.drawFrameDuration.average%252Ctest%253Dweb_benchmarks_skwasm%252C&xbaroffset=39546)

cc @eyebrowsoffire

**Comment by eyebrowsoffire** [comment] 2024-02-27 22:07
The PR that triggered this change was a engine roll with a number of changes. I ran benchmarks against a number of the intermediate commits in order to further isolate the issue, and it appears to have happened with this Dart SDK roll specifically: https://github.com/flutter/engine/pull/50979

There are a few dart2wasm-specific changes in that roll, but I haven't yet isolated it down to a specific dart commit.

**Comment by mkustermann** [comment] 2024-02-28 22:46
The "root cause" of the regression is according to my analysis - https://github.com/dart-lang/sdk/commit/c625797f8a3ea9a346d5170ada18d1d6f57e36d6 - which implemented proper `dart:developer`.

* After that CL landed, the APIs in `dart:developer` actually do something as supposed to before where they were stubbed out.
* The fact that this shows as 25% regression means that what this benchmark is measuring is to a large extend measurement logic itself (e.g. timline events etc) itself.
* This can be seen in the profiles of before/after quite clearly: `Timeline.startSync` / `Timeline.finishSync` are high on the profile (e.g. called by `PipelineOwner.flushSemantics`)
* When running the benchmark manually in the browser window, it jitters around, gut doesn't actually sroll down and up
* Given the above, I assume the flutter benchmarking system is benchmarking `--profile` mode and not `--release` mode?
* Together this somewhat puts into question the usefulness of this benchmark.

In any case, I'll close this as working as intended.

**Closed by mkustermann** 2024-02-28 22:46 UTC
Labels: c: regression, dependency: dart, P0, team-web, triaged-web

**Comment by gaaclarke** [comment] 2024-02-28 22:55
> The fact that this shows as 25% regression means that what this benchmark is measuring is to a large extend measurement logic itself (e.g. timline events etc) itself.
> Given the above, I assume the flutter benchmarking system is benchmarking --profile mode and not --release mode?

I wouldn't dismiss a benchmark because it is measuring a large portion of profiling overhead.  That is the point of `--profile` mode, to be profiled =)  If that mode creates so much overhead that the profiles are no longer useful, that's a problem.  Would it be prudent to revisit the performance of `dart:developer` on the web?

**Comment by eyebrowsoffire** [comment] 2024-02-28 22:58
It's not that the profiles are not useful, the baselines have just changed. I think that's perfectly reasonable. I think it's a good idea to just rebaseline this and triage the skia perf notification and close this bug. I just wanted to make sure we weren't actually regressing rendering performance before closing it.

**Comment by mkustermann** [comment] 2024-02-29 06:41
> I wouldn't dismiss a benchmark because it is measuring a large portion of profiling overhead. 

If the program I want to measure behaves - when measuring it - 25% differently from real world, then that's a problem. The numbers just won't be representative of the real app (and we only care about the real app). When profiling & optimizing real world apps one needs to get metrics for the real app.

> If that mode creates so much overhead that the profiles are no longer useful, that's a problem. Would it be prudent to revisit the performance of dart:developer on the web?

The problem may not be the `dart:developer` implementation per se, it just forwards calls to the browser APIs. It may be more due to the framework doing significantly more work in `--profile` mode than in `--release` mode. Could it be that we issue too many timeline events (given the work that happens in-between)?

Two more things
* the actual benchmark in the web page doesn't seem to scroll properly (try running it) it just moves few pixels down & up, instead of scrolling new widgets in. Is this intentional?
* the fact that the profile ran just fine before the CL, means that those timeline events aren't needed for the benchmark to run. Can those benchmark run in `--release` mode instead?

**Comment by gaaclarke** [comment] 2024-02-29 16:52
> Could it be that we issue too many timeline events (given the work that happens in-between)?

Maybe that's something we could help with?  Elide timeline events that happen at too high of a frequency?  I imagine what is an acceptable frequency will depend on the target platform which will be difficult of users to get right in all cases.
