### ISSUE TITLE
A must-have feature is missing: "scroll to index" for ListView and SliverList

### ISSUE THREAD

**Issue by vizakenjack** [flutter/flutter#130262] opened 2023-07-10 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### The problem

There is no way to scroll a ListView or SliverList to a specific item when the height is not fixed.

I have been working on four different Flutter projects since 2020, and in each of them, I was required to use the [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list). 

In 2023, this package is still the only way to use scrollToIndex method, with a following list of problems:
- You can't use your ScrollController. There is ItemScrollController with a private ScrollController inside, and there is no way to access it. 
- You can only scroll and align by an item's top edge, and there is no way to align by a bottom edge.
- If you need to scroll to the latest item, it will either lead to an undesired animation (having alignment 0 - top edge of the item to the top edge of a viewport), or you'll end up writing a function to calc a proper alignment.
- You can't use some packages that only works with ListView (f.e. 'pull_to_refresh')
- You will have to fork and modify it, because it's not a production-ready solution.

### Why is it important?

A lot of developers are coming to Flutter from native, where scroll to index is a part of a standard library, and it's not required to install a third-party packages.

[Example on iOS](https://www.hackingwithswift.com/quick-start/swiftui/how-to-scroll-to-a-specific-row-in-a-list)

[Example on Android](https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#scrollToPositionWithOffset(int,%20int))

[Example on React Native](https://aboutreact.com/scroll_to_a_specific_item_in_scrollview_list_view/)

### Similar issues

https://github.com/flutter/flutter/issues/123187
https://github.com/flutter/flutter/issues/119491
https://github.com/flutter/flutter/issues/81005
https://github.com/flutter/flutter/issues/71742

### The solution

Add scrollToIndex feature as a part of standard library, for ListView and SliverList.
Add an argument to select alignment by leading edge or trailing edge

**Comment by foxweb** [comment] 2023-07-10 13:37
👍

**Comment by LinXunFeng** [comment] 2023-07-11 00:48
I made a package that supports scrollToIndex feature for `ListView`, `SliverList`, `GridView`, `SliverGrid` and third-party `ScrollView` widget.

Hope this can help you before the Flutter team supports the feature.

Repo: [scrollview_observer](https://github.com/LinXunFeng/flutter_scrollview_observer)

**Comment by darshankawar** [comment] 2023-07-11 07:54
@vizakenjack 
A similar request was made in this old issue https://github.com/flutter/flutter/issues/12319 for which the solution was to use scrollable_positioned_list as you mentioned along with limitations.

Have you also looked at community packages other than above which offers the feature already ? Like https://pub.dev/packages/indexed_list_view and https://github.com/quire-io/scroll-to-index

Also see if [this](https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac) article is helpful in your case or not.

For sliverlist, see if https://github.com/flutter/flutter/issues/81005#issuecomment-999942723 is helpful or not.

**Comment by vizakenjack** [comment] 2023-07-11 10:39
@darshankawar yes, I have tried other packages.

ScrollToIndex had serious performance issues, so I didnt use it.

IndexedListView is a similar to scrollable positioned list, with same issues - without an access to ScrollController, and without bottom edge alignment. It's also not maintained - the last update was in 2021.

My proposal is that "scroll to index" should be a part of core library, like in Native. It takes a lot of time when you have to find and try other packages just to solve one single problem

**Comment by darshankawar** [comment] 2023-07-11 13:07
Thanks for the feedback @vizakenjack 
How about https://github.com/flutter/flutter/issues/130262#issuecomment-1629930197 ?

**Comment by darshankawar** [comment] 2023-07-12 05:39
Thanks for the update and feedback. There have been similar issues for the feature requests:

https://github.com/flutter/flutter/issues/12319
https://github.com/flutter/flutter/issues/81005

**Comment by goderbauer** [comment] 2023-07-18 22:21
Duplicate of https://github.com/flutter/flutter/issues/81005.

**Closed by goderbauer** 2023-07-18 22:21 UTC
Labels: c: new feature, framework, f: scrolling, c: proposal, team-framework
