### ISSUE TITLE
Seeing a green rectangle around the border of the gallery app when I run it

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#16810] opened 2018-04-20 19:25 UTC
## Steps to Reproduce

Running the flutter gallery, I see a green border around it off of master.

## Doctor
Version: 
Flutter (Channel master, v0.3.3-pre.2, on Linux, locale en_US.UTF-8)
<snip>

**Comment by pboos** [comment] 2018-05-24 12:08
I just noticed this with an app I am building.  In the emulator it didn't have it. On a Nexus 5X it didn't have it either. On the Pixel 2 it is showing a green border of about the size of 1dp.

## Doctor:
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (12 days ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

![screenshot_20180524-210513](https://user-images.githubusercontent.com/398400/40484422-86118012-5f96-11e8-8770-8edaea0b4cc1.png)

**Comment by pplante** [comment] 2018-07-12 02:55
I am seeing this in my app when trying to capture a screenshot or screencast from the emulator.  Is there any workaround?  I believe this is caused by something in the Android accessibility?

**Comment by jonahwilliams** [comment] 2018-07-12 03:33
I have seen this before, but it is difficult to reproduce.  Visually, that does look a lot like the TalkBack a11y focus, I will take a look and see what I can find

**Comment by lgArlequin** [comment] 2018-08-29 13:44
I have this problem when test an app in a Oneplus one with android 8.1.0, but not in a moto g3 with android 6

**Comment by lgArlequin** [comment] 2018-08-29 13:54
I solved adding this:
<item name="android:defaultFocusHighlightEnabled">false</item>
to styles.xml.

https://stackoverflow.com/questions/49541354/disable-defaultfocushighlightenabled-in-the-android-part-for-a-xamarin-forms-app

**Comment by HannoOttens** [comment] 2018-08-31 07:14
Had the same issue after updating to Flutter v0.7.5 on a Oneplus 5T (Android 8.1)

**Comment by jpeiffer** [comment] 2018-10-10 00:37
Just happened to me on 0.9.4 using the Android Emulator for Pixel API 26.

I had to uninstall and reinstall.

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.4 at /Users/jpeiffer/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/jpeiffer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/jpeiffer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • Android SDK built for x86                                                                                                                                       
```

**Comment by jpeiffer** [comment] 2018-12-22 04:18
I saw it using a Pixel 2 & 3 Emulator.  I'm not at liberty to share the code or important part of the screen, but I can share the upper right corner that at shows the issue.

![green_outline](https://user-images.githubusercontent.com/6424555/50370528-69c04980-0576-11e9-83d5-98cbc295a612.png)

This has been happening randomly since IO.  It only seems to happen in debug mode (thankfully), but the fact that it happens is creating resistance to using Flutter on a wider scale.

Results of Flutter Doctor:
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/jpeiffer/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jpeiffer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jpeiffer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```

**Comment by JimmyRobz** [comment] 2019-01-06 16:42
> I solved adding this:
> `<item name="android:defaultFocusHighlightEnabled">false</item>`
> to styles.xml.
> 
> https://stackoverflow.com/questions/49541354/disable-defaultfocushighlightenabled-in-the-android-part-for-a-xamarin-forms-app

This solution from @lgArlequin works for me!

**Comment by shakes80** [comment] 2019-02-05 15:54
I solved adding this:
`<item name="android:defaultFocusHighlightEnabled">false</item>`
to
`./android/app/src/main/res/values/styles.xml`

**Comment by efortuna** [comment] 2019-04-16 20:02
A great way to easily repro this is to run any app on ChromeOS. Very visible.

**Comment by Dancovich** [comment] 2019-07-13 14:57
Just saw this on my release app on a Galaxy S8 compiled with Flutter 1.7.8 hotfix 3.

Couldn't reproduce it later for screenshot. Will try the defaultFocusHighlightEnabled workaround next.

**Comment by ra7bi** [comment] 2019-07-21 19:41
I'm having some problem but at the bottom of my app border , i tried defaultFocusHighlightEnabled and still same , Im getting yellow rectangle . Please help 

Thanks

**Comment by feinstein** [comment] 2019-12-09 16:01
Get this on the Pixel AVD but I don't on my OnePlus 5 device with Android 9.

**Comment by nabeelkv** [comment] 2019-12-30 14:54
It showing because you activated "Repaint Rainbow".

#To hide "Repaint Rainbow" :  
Run your app -> Toggle Flutter Inspector -> More Actions -> Hide Repaint Rainbow

![flutter-rainbow-repainter](https://user-images.githubusercontent.com/43858092/71587079-56a96780-2b42-11ea-8fe3-7e51e17ed27c.png)

Hope it helps :)

**Comment by mfarizon** [comment] 2020-01-28 17:08
@nabeelkv Not convinced by your explanation, it happened to me with the Flutter Europe application, so it can happen on production as well. 
![Screenshot_20200124-110447](https://user-images.githubusercontent.com/22452175/73287204-29abab80-41f9-11ea-882f-239f6121bef2.png)

**Comment by lgArlequin** [comment] 2020-01-28 17:42
> I solved adding this:
> `<item name="android:defaultFocusHighlightEnabled">false</item>`
> to styles.xml.
> 
> https://stackoverflow.com/questions/49541354/disable-defaultfocushighlightenabled-in-the-android-part-for-a-xamarin-forms-app

@mfarizon  Did you try this?

**Comment by mfarizon** [comment] 2020-01-28 17:52
Yes I just added it, but I don't know exactly how to reproduce it, it comes from time to time. I will tell you if it ever happens again.

**Comment by ceranco** [comment] 2020-04-04 16:21
I can reproduce this bug consistently by pressing the `Up` key when my android emulator (`Nexus 6P API 28`) is in focus.

>I solved adding this:
`<item name="android:defaultFocusHighlightEnabled">false</item>`
to styles.xml.

This solves it for me 😄

**Comment by bawantha** [comment] 2020-05-23 08:17
There was no border until I use `ThemeData()` to app and adding above `<item name="android:defaultFocusHighlightEnabled">false</item>` works what will be the reason for that ?

**Comment by jbojcic1** [comment] 2020-07-04 14:23
This happens for me too. I see the green border around the app when I focus the input and then I can't type anything.

Flutter details:
```
λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.46.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

I am using Pixel 2 API 28 emulator.

Adding `<item name="android:defaultFocusHighlightEnabled">false</item>` doesn't help. Also when I add that in android studio I see the following message `android:defaultFocusHighlightEnabled requires API level 26`

**Comment by febritecno** [comment] 2020-08-04 13:18
> I solved adding this:
> `<item name="android:defaultFocusHighlightEnabled">false</item>`
> to
> `./android/app/src/main/res/values/styles.xml`

Solved with this tutorial. thanks all :)

**Comment by andrefedev** [comment] 2020-08-08 21:12
Same problem here, I'm using RawKeyboardListener with autoFocus set to true and I'm getting a green-bordered screen.

**Comment by vishnureddys** [comment] 2020-08-16 15:06
I had this exact same issue, I got this when I clicked some key on my keyboard by mistake. Did not happen again after I went back on the emulator. But when I had this issue, hot reload was not working for me.

**Comment by TahaTesser** [comment] 2020-09-08 13:43
Notice this issue sometimes not always reproducible

**Comment by xuzhuo99hy** [comment] 2021-03-16 02:46
nice, resolve it!

**Comment by aksagarwal42** [comment] 2021-03-27 15:25
@lgArlequin Thanks man, your solution worked like a charm for me!

**Comment by 1IxI1** [comment] 2021-09-29 19:23
I just closed app on the phone/emulator and rebuilt the app. It works for me.

**Comment by Fauzdar1** [comment] 2022-03-14 08:49
I've faced the same issue in the emulators, but, not just this border, whenever this border appears, the status bar size also increases. 

I can't reproduce it but some keyboard shortcut triggers it, whenever it appeared, I was trying to change my laptop's brightness, so I believe, any combo of Ctrl/Shift/Alt + F10/F11/F12 triggers it any such combo doesn't disable it.

**Comment by Amine-Mb** [comment] 2022-03-21 15:03
solved this with:
  flutter clean
  flutter run

**Comment by KyotoSenpaii** [comment] 2022-07-21 04:52
So i've noticed this happens when im using the emulator from android studio and i select the emulator window and then press the arrow keys... i think it selects the container or something close to that.

To solve i just close de app in the emulator and open again :D (and make sure i dont press the arrow keys)

**Comment by Serguncheouss** [comment] 2023-03-22 07:44
It is still happens on all devices that I used. On Android Emulator it happens if press on PC keyboard, on real devices it happens when you use a gamepad.

If remove this from AndroidManifest.xml:
```
<meta-data
android:name="io.flutter.embedding.android.NormalTheme"
android:resource="@style/NormalTheme"
/>
```
Or if you use a custom theme, it may looks like whole screen overlaying:

![untitled](https://user-images.githubusercontent.com/16072066/226833373-1689ee69-e43f-42f8-b2d2-56d8cf3ad704.gif)

This `<item name="android:defaultFocusHighlightEnabled">false</item>` solves the issue but only for API level 26 and above.

**Comment by hirios** [comment] 2023-09-20 00:18
@jbojcic1 Did you manage to solve it? I have the same problem using RawKeyboard

**Comment by edilsongg** [comment] 2023-11-25 22:38
This problem also blocks the functioning of GameButtonB using a gamepad, I need this function please

**Comment by karatekid430** [comment] 2024-01-27 13:50
None of the solutions here actually work. The issue still persists.

**Comment by karatekid430** [comment] 2024-01-27 13:54
Okay, you have to remember to put it in styles.xml for values-night. People, develop for dark mode, it is important not to keep people awake at night by creating unnecessary blue light.

**Comment by karatekid430** [comment] 2024-01-27 13:57
My general feedback for Flutter is that the Android implementation is an absolute joke, and this is supposedly made by Google who makes Android. I have to do so many little fixes for Android here that I just do not have to do in iOS. It's not a good look for your Android ecosystem and affirms the reasons why I moved away from it in my personal life.

**Comment by dazemc** [comment] 2024-03-23 10:37
This is not an issue.

For anyone that happens upon this, it appears to happen when using physical or an emulated peripheral (keyboard/mouse/gamepad). The problem is that it's not really a problem. This is a focus border for navigation that is usually hidden until you use a peripheral. I'd guess for accessibility reasons. The real issue is abstraction, like usual.

You can resolve this by simply closing the app and reopening it, or turning off the focus border completely. The latter may affect accessibility though.

**Comment by mossmana** [comment] 2024-04-12 18:44
As there should be no changes needed in the Flutter SDK itself to address this issue, I am closing this issue. However, it is reasonable that the documentation should be updated to better explain this Android specific behavior. So, I have also created a new issue to track the documentation update: https://github.com/flutter/flutter/issues/146695. Feel free to comment on the new issue if you would like to see specific information in the documentation.

**Closed** 2024-04-12 18:44 UTC
Labels: platform-android, framework, engine, a: quality, P2, found in release: 1.20, team-android, triaged-android
