### ISSUE TITLE
Specific text input on Xiaomi device jumps the selection to beginning

### ISSUE THREAD

**Issue by YunusZhao** [flutter/flutter#47763] opened 2019-12-25 03:06 UTC
## Steps to Reproduce

1. create a flutter application with TextField
2. input something, then input "(".
3. the selection jump to begin.

**Devices:XiaoMi

## Logs

```
```

```
```

```
```

**Comment by YunusZhao** [comment] 2019-12-25 03:08
It`s not wrong, but looks terrible !

**Comment by iapicca** [comment] 2019-12-25 12:15
Hi @YunusZhao 
Can you please describe the issue in detail 
also please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
To better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by YunusZhao** [comment] 2019-12-26 02:55
OK @iapicca
it`s not a wrong, the application can normally run .
it‘s a bug at TextField with XiaoMi's MIUI system.
you can write a simple app, just has a TextFiled .
run it on a XiaoMi, input "(",.

**Comment by iapicca** [comment] 2019-12-27 07:41
Hi @YunusZhao 
does this [code](https://dartpad.dartlang.org/32750f22d29898193474703f93eebfc4) represent the issue you are describing?
I'm not experiencing said issue on a "stock android" device,
please consider that this issue might be related 
to the virtual keyboard in use on your device,
are you experiencing this issue with different keyboards?
thank you

**Comment by YunusZhao** [comment] 2019-12-27 08:06
Yes @iapicca thank you first。
in other android device， it's right.
but when the code run on XiaoMi(a Chinese mobile phone brands, lots people use it), it's wrong!
Example: 
    I input "abc",in TextFile, it's "abc|". ("|" symbol selection)
    Then, I input "(", in other device, it's "abc(|)",
    but in XiaoMi , it's "|abc()", the selection jump to the begin.
    I think it's a bug.

**Comment by iapicca** [comment] 2019-12-27 08:23
Hi again @YunusZhao 
are you experiencing this behavior with different virtual keyboards?
thank you

**Comment by dnfield** [comment] 2020-01-17 21:50
@GaryQian - is this on your radar?

**Comment by dnfield** [comment] 2020-01-17 21:51
(and/or is it a dupe of something else you've seen)

**Comment by darshankawar** [comment] 2020-09-18 12:41
Hi @YunusZhao,
Since we don't have Xiaomi device to replicate this issue, could you confirm if you still see the issue on that device using latest Flutter version ?
If so, can you provide the latest `flutter doctor -v`, along with screenshot of the issue ?
Thanks.

**Comment by markusaksli-nc** [comment] 2020-10-09 07:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by markusaksli-nc** 2020-10-09 07:43 UTC
Labels: a: text input, framework, platform-android, waiting for customer response
