### ISSUE TITLE
[Impeller] impellerc hangs when there is a crash on Windows

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#107812] opened 2022-07-18 03:48 UTC
Have been playing around with impellerc this weekend. Encountered a snag though.

It seems relative includes are based off of the project root, and not the directory where the shader resides. Additionally, when a compilation error occurs the build process hangs, the messages are not printed to stderr either.

Repro steps:

pubspec.yaml:
```yaml
# ...
flutter:
  shaders:
    - assets/shader/basic.frag
```

assets/shader/basic.frag:
```glsl
#version 320 es

precision highp float;

layout(location = 0) out vec4 fragColor;

// NOTE: "assets/shader/common.glsl" works
#include "common.glsl"

void main() {
  fragColor = vec4(COLOR, 1.0);
}
```

assets/shader/common.glsl:
```glsl
#define COLOR vec3(1.0, 0.0, 0.0)
```

lib/main.dart:
```dart
void main() { /* not important, reproduce with `flutter build bundle --verbose` */ }
```

Running `flutter build bundle --verbose` will hang. The impellerc process never exits, as I can see it in Task Manager. Running impellerc manually shows the error though.

I'd expect relative includes to be resolved relative to the compiling source file, and not the Flutter project root.

cc @zanderso @chinmaygarde

**Comment by chinmaygarde** [comment] 2022-07-18 16:11
> It seems relative includes are based off of the project root, and not the directory where the shader resides.

To fix this, the Flutter tool should invoke Impeller with a default `--include` that specifies the source directory. The tool or caller can specify as many include directories as they need. The [default GN rules](https://github.com/flutter/engine/blob/9e8a29a1d56d5cdf6af6c604fed78a047d7db642/impeller/tools/impeller.gni#L272) used in the engine do this. Perhaps the tool should do this by default as well.

> Additionally, when a compilation error occurs the build process hangs, the messages are not printed to stderr either.

The ImpellerC binary dumps error [messages to std::cerr](https://github.com/flutter/engine/blob/9e8a29a1d56d5cdf6af6c604fed78a047d7db642/impeller/compiler/impellerc_main.cc#L71), perhaps the tools is not intercepting and forwarding these? Its a dead simple setup so not sure why this wouldn't work.

> The impellerc process never exits, as I can see it in Task Manager.

This one is a head scratcher. The tool creates no threads and has no complex locking behavior. Do you have the ImpellerC invocation handy? I'll try to reproduce this locally.

**Comment by chinmaygarde** [comment] 2022-07-18 16:12
cc @jonahwilliams for guidance on if std::cerr is intercepted by the Flutter tool.

**Comment by zanderso** [comment] 2022-07-18 16:49
Looks like it's trying to capture stderr when the exit code is non-zero:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/shader_compiler.dart#L74.

I should have some cycles to take a look this afternoon.

**Comment by zanderso** [comment] 2022-07-18 22:07
The absence of stderr output and hang didn't reproduce on macOS for me. I have a Windows machine at home that I'll try to repro on.

**Comment by chinmaygarde** [comment] 2022-07-18 22:16
Sounds good. I've been trying to setup my cloudtop today with limited success as well.

**Comment by christopherfujino** [comment] 2022-09-06 20:28
Closing this as the cause of hte crash was fixed.

**Closed by christopherfujino** 2022-09-06 20:28 UTC
Labels: tool, engine, P3, impeller
