### ISSUE TITLE
"read access violation" running Flutter embedder on Windows

### ISSUE THREAD

**Issue by markmclaren2** [flutter/flutter#19079] opened 2018-07-04 16:34 UTC
[This page](https://github.com/flutter/engine/wiki/Custom-Flutter-Engine-Embedders) suggests I should be able to run the sample GLFW program using the Windows .dll file that was uploaded by the buildbots. But when I run the program I see the Flutter window for a few seconds then I get an exception with this text printed to the console:

```
Exception thrown: read access violation.
this->mBreakIterator._Mypair._Myval2 was nullptr. 
```
See below for stacktrace.

# Steps to reproduce

1. Create a new project in Visual Studio 2015 and add this as the main source file:
https://gist.github.com/chinmaygarde/8abf44921f7d87f6da7bf026267c4792

2. Download the GLFW Windows pre-compiled 64-bit binaries from [this page](http://www.glfw.org/download.html) and add the .h and .lib files to the VS project

3. Download the pre-compiled Flutter windows 64 embedder binaries from [this page](https://storage.googleapis.com/flutter_infra/flutter/6fe748490d1772d72274bf8b9efb72c5c2160237/windows-x64/windows-x64-embedder.zip) and add the .h and .lib files to the VS project.  Also include the .dll directory in your path and restart VS.

4. Checkout version 0.5.6 version of Flutter and run 'flutter build packages' in the examples/flutter_gallery directory. Then update the #define MY_PROJECT variable in the main source file to point to this flutter_gallery directory.

5. Build and run the project in VS in Debug x64 mode.  The Flutter window opens and processes mouse move events, but after a few seconds we get the error shown above. See stacktrace below.

# Stacktrace
```
	flutter_engine.dll!minikin::WordBreaker::setText(const unsigned short * data, unsigned __int64 size) Line 55	C++
 	flutter_engine.dll!minikin::LineBreaker::setText() Line 77	C++
 	flutter_engine.dll!txt::Paragraph::ComputeLineBreaks() Line 271	C++
 	flutter_engine.dll!txt::Paragraph::Layout(double width, bool force) Line 422	C++
 	flutter_engine.dll!tonic::DartCall<void (__cdecl blink::Canvas::*)(double) __ptr64>(void(blink::Canvas::*)(double) func, _Dart_NativeArguments * args) Line 199	C++
 	flutter_engine.dll!blink::Paragraph_layout(_Dart_NativeArguments * args) Line 36	C++
 	flutter_engine.dll!dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments * args, void(*)(_Dart_NativeArguments *) func) Line 199	C++
 	[External Code]	
 	flutter_engine.dll!blink::Paragraph_layout(_Dart_NativeArguments * args) Line 36	C++
 	[External Code]	

```
# Flutter Doctor Output

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v0.5.6, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
    • Flutter version 0.5.6 at C:\Users\Mark\dev\flutter
    • Framework revision 472bbccf75 (8 days ago), 2018-06-26 17:01:46 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by gedw99** [comment] 2018-07-10 18:37
Well done for getting this far .

@mit-mit. Might know who can help.

**Comment by clarkezone** [comment] 2018-07-10 20:01
For instructions for GLFW check here: https://github.com/CallumIddon/flutter-desktop-embedding/tree/GLFW-Windows/windows#adding-windows-as-a-target-platform

I’ve not tried these but I do have a seperate fork bringing up an embedder on Windows using Angle which is working so I can atest that the Windows builds do work.

**Comment by stuartmorgan** [comment] 2019-08-08 23:39
I'm going to close this since this was with what is now a very old version of Flutter, and it's not clear from the STR here if the downloaded library was using the correct hash, or this was a Flutter/engine version mismatch here.

If you can still reproduce this with a current version, and ensuring that the hash of the engine library is correct, please comment with details and we can re-open. (Although with the changes in the last year, if you are just interested in running on Windows rather than specifically making a custom embedder, it's much easier now.)

**Closed by stuartmorgan** 2019-08-08 23:39 UTC
Labels: e: embedder, engine, ❖ platform-windows
