### ISSUE TITLE
[windows] Scanning Barcode on text filed missing data

### ISSUE THREAD

**Issue by mjafartp** [flutter/flutter#86607] opened 2021-07-17 16:07 UTC
## Steps to Reproduce

Scanning Barcode using a barcode scanner on a text field

Scanned value: 8999544575524

**Expected results:** 8999544575524

**Actual results:**  899545552

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19042.1110], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

• No issues found!

**Comment by iapicca** [comment] 2021-07-17 16:52
@mjafartp 
can you provide your `pubspec.yaml` and a code sample

**Comment by stuartmorgan** [comment] 2021-07-17 17:01
Duplicate of https://github.com/flutter/flutter/issues/84210

**Closed by stuartmorgan** 2021-07-17 17:01 UTC
