### ISSUE TITLE
TextField disposes manually-provided FocusNode

### ISSUE THREAD

**Issue by lucaslcode** [flutter/flutter#22187] opened 2018-09-23 12:27 UTC
`TextField` calls dispose even when a `FocusNode` is manually provided. Not sure if it is intended behaviour, but in my use case, I have a list of FocusNodes in my state - only one of them is used for a TextField. This means an exception is thrown when I dispose them all.

## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
    title: 'Demo',
    home: MyApp()
    ));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Demo'),
        ),
        body: Center(
          child: MaterialButton(
            child: Text("Dialogue"),
            onPressed: () {
              FocusNode myFocusNode = FocusNode();
              showDialog(
                context: context,
                builder: (context) => AlertDialog(
                  content: TextField(focusNode: myFocusNode),
                )
              ).then((_) => myFocusNode.dispose());
              
            },
          ),
        )
    );
  }
}
```

1. Use a `TextField` with your own `FocusNode`
2. Dispose of the FocusNode
3. Dispose of the TextField

## Logs

```
/flutter ( 9777): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9777): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 9777): A FocusNode was used after being disposed.
I/flutter ( 9777): Once you have called dispose() on a FocusNode, it can no longer be used.
```

```
[√] Flutter (Channel master, v0.9.3-pre.20, on Microsoft Windows [Version 10.0.17134.285], locale en-GB)
    • Flutter version 0.9.3-pre.20 at D:\code\flutter
    • Framework revision 6d134e0c86 (5 hours ago), 2018-09-23 00:43:05 -0700
    • Engine revision 57fd394e59
    • Dart version 2.1.0-dev.5.0.flutter-654c4babc8

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\lucas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

[√] VS Code, 64-bit edition (version 1.27.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by lucaslcode** [comment] 2018-09-23 13:55
Provided a minimal reproduction. Note that it's pointless to provide your own FocusNode in this case, but it will be difficult to show a case where its useful that's also minimal.

**Comment by HansMuller** [comment] 2018-11-20 20:43
Thanks for the minimal test case!

What's going on here isn't the TextField disposing its focusNode. The TextField is trying to remove the listener it added to the focusNode, and unfortunately it's doing so after the app has disposed the focusNode.

The focusNode should be disposed when the stateful widget that contains it is disposed, rather than when its route is popped (which is too early).

In this case it is necessary to create a StatefulWidget that manages the focusNode's lifetime. Here's a version of the test case that does that: https://gist.github.com/HansMuller/bac7f18890c33907dfa4300943ad971d

I'm going to close this bug since things are working as intended. If you think there's still an outstanding problem, please reopen it.

**Closed by HansMuller** 2018-11-20 20:43 UTC
Labels: a: text input, framework, severe: crash

**Comment by lucaslcode** [comment] 2018-11-21 22:51
Thanks for the example. My example wasn't very good, actually what I was doing in my real app was closer to what you suggested.

It turns out I was disposing the custom state myself twice - once in an InheritedWidget-style provider, and redundantly again in the widget that creates the provider.
