### ISSUE TITLE
[tool_crash] FormatException: No ':' on line (at offset 12)

### ISSUE THREAD

**Issue by mayupandey** [flutter/flutter#60256] opened 2020-06-25 03:57 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException: FormatException: No ':' on line (at offset 12)
```
#0      parse (package:package_config/packages_file.dart:64:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:17:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:49:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:53:5)
#4      new PackageUriMapper (package:flutter_tools/src/compile.dart:199:116)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:647:26)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#16     _rootRun (dart:async/zone.dart:1180:38)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
```
```
[✓] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.17.4 at C:\Users\Microsoft.000\Desktop\flutter
    • Framework revision 1ad9baa8b9 (7 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Microsoft.000\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Microsoft.000\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 3c43b0abaf8b4697b1eeee971bd31124a2fe1602

**Comment by TahaTesser** [comment] 2020-06-25 10:06
duplicate of https://github.com/flutter/flutter/issues/57864

**Closed by TahaTesser** 2020-06-25 10:06 UTC
