### ISSUE TITLE
firebase_ml_vision streaming crashes when using Med/High ResolutionPreset

### ISSUE THREAD

**Issue by dwach414** [flutter/flutter#32652] opened 2019-05-13 21:51 UTC
## Steps to Reproduce

1. Using the example from https://github.com/bparrishMines/mlkit_demo
2. Then setting the camera ResolutionPreset to medium or high on iOS and high on Android
3. When trying to byte stream images to the firebase_ml_vision for barcode reading. It cannot process fast enough and crashes with no error on iOS and and OOM on Android.

## Logs

For Android it doesn't always crash with OOM, and when it doesn't it just runs slow posting this over and over. This is running on my Galaxy S8.
```/zygote64( 1826): Starting a blocking GC Alloc
[   +9 ms] I/zygote64( 1826): Clamp target GC heap from 269MB to 256MB
[   +1 ms] I/zygote64( 1826): Alloc concurrent copying GC freed 70(47KB) AllocSpace objects, 5(9MB) LOS objects, 4% free, 245MB/256MB, paused 140us total 12.212ms
[   +7 ms] I/zygote64( 1826): Starting a blocking GC Alloc
[   +8 ms] I/zygote64( 1826): Starting a blocking GC Alloc
[        ] I/zygote64( 1826): Clamp target GC heap from 273MB to 256MB
[        ] I/zygote64( 1826): Alloc concurrent copying GC freed 261(63KB) AllocSpace objects, 2(4MB) LOS objects, 2% free, 249MB/256MB, paused 144us total 9.662ms
[        ] I/zygote64( 1826): Starting a blocking GC Alloc
[   +8 ms] I/zygote64( 1826): Starting a blocking GC Alloc
[        ] I/zygote64( 1826): Clamp target GC heap from 274MB to 256MB
[   +1 ms] I/zygote64( 1826): Alloc concurrent copying GC freed 24(32KB) AllocSpace objects, 1(1204KB) LOS objects, 2% free, 250MB/256MB, paused 144us total 8.335ms
[        ] I/zygote64( 1826): Starting a blocking GC Alloc
[   +9 ms] I/zygote64( 1826): Starting a blocking GC Alloc
[        ] I/zygote64( 1826): Clamp target GC heap from 276MB to 256MB
[   +1 ms] I/zygote64( 1826): Alloc concurrent copying GC freed 50(47KB) AllocSpace objects, 1(2MB) LOS objects, 1% free, 252MB/256MB, paused 134us total 8.667ms
[   +1 ms] I/zygote64( 1826): Starting a blocking GC Alloc
[  +12 ms] I/zygote64( 1826): Starting a blocking GC Alloc
```
On my iPhone Xs it crashes with no information.
``` 
[        ] Connected to _flutterView/0x104029e18.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on Daniel’s iPhone is available at: http://127.0.0.1:1030/PpGz07914_Q=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+38274 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/C191611A-84A2-4B4B-9353-5B31673aASDFA/tmp/AppNameLgIknR/AppName/)
[        ] Sending to VM service: _deleteDevFS({fsName: AppName})
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 106,751ms.
[        ] "flutter run" took 106,751ms.
```

Flutter analyze is clean.

Here is the flutter doctor output
```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/computer/dev/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/computer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/computer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Daniel’s iPhone • 00008020-00165D420128002E • ios • iOS 12.2

• No issues found!
```
### Notes
From my own investigation. It seems to be an issue with how large each frame of the images is are, and how flutter runs its background processes.

When you scan but you disconnect the preview it still crashes all the same, so that isn't related. And if you start the byte streaming, but don't do any processing it also is fine. 

Which means it is something to do with the speed in which Dart can handle processing these images. I feel like if the images didn't go through dart before going back to native, this would be a lot faster.

**Comment by BondarenkoStas** [comment] 2019-10-12 12:57
@dwach414 was it fixed with https://github.com/flutter/plugins/pull/1615 or you still experience it?

**Comment by iapicca** [comment] 2019-11-08 10:38
Hi ... 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 10:38 UTC
Labels: waiting for customer response
