### ISSUE TITLE
[Android] Switching between TextFields with TextInputType.number briefly shows the regular keyboard

### ISSUE THREAD

**Issue by lavinov-mercury** [flutter/flutter#154913] opened 2024-09-10 10:43 UTC
### Steps to reproduce

1. Run the Example app on Android
2. Focus on the first input
3. Tap on the keyboard's Next button

### Expected results

The numeric keyboard should be displayed.

### Actual results

The regular keyboard appears while switching between TextFields.

### Code sample

<details>
  <summary>Example app</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Keyboard switching issue'),
        ),
        body: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                keyboardType: TextInputType.number,
                textInputAction: TextInputAction.next,
              ),
              TextField(
                keyboardType: TextInputType.number,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0417210c-ded1-4808-851d-8d57de004e73

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/InputMethodManager(27659): showSoftInput() view=io.flutter.embedding.android.FlutterView{6e50532 VFE...... .F....ID 0,0-1080,2277 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(27659): Flattened final assist data: 396 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
D/InsetsController(27659): show(ime(), fromIme=true)
2
D/InputMethodManager(27659): showSoftInput() view=io.flutter.embedding.android.FlutterView{6e50532 VFE...... .F...... 0,0-1080,2277 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(27659): Flattened final assist data: 396 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
D/InsetsController(27659): show(ime(), fromIme=true)
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
3
D/InsetsController(27659): show(ime(), fromIme=true)
D/InputMethodManager(27659): showSoftInput() view=io.flutter.embedding.android.FlutterView{6e50532 VFE...... .F...... 0,0-1080,2277 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(27659): Flattened final assist data: 396 bytes, containing 1 windows, 3 views
D/InsetsController(27659): show(ime(), fromIme=true)
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
2
D/InsetsController(27659): show(ime(), fromIme=true)
D/InputMethodManager(27659): showSoftInput() view=io.flutter.embedding.android.FlutterView{6e50532 VFE...... .F...... 0,0-1080,2277 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/AssistStructure(27659): Flattened final assist data: 396 bytes, containing 1 windows, 3 views
D/InsetsController(27659): show(ime(), fromIme=true)
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(27659): The input method toggled cursor monitoring on
2
D/InsetsController(27659): show(ime(), fromIme=true)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.4.1 23E224 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-10 11:39
Reproducible using the code sample provided above. This appeared to have regressed since 3.22.3 as this works as expected in 3.19.6 but not 3.22.3 onwards

| 3.19.6 | 3.22.3+ | 
| -- | -- |
| <video src="https://github.com/user-attachments/assets/fe795952-d0f2-4bc5-8ecb-a18fdd7d032d" /> | <video src="https://github.com/user-attachments/assets/23bd6817-717f-4380-a258-bde13b358a96" /> |

<details>
<summary>flutter doctor -v</summary>

  
```
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (7 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
```

```
[!] Flutter (Channel master, 3.25.0-1.0.pre.320, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.320 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6e2b6aedb (6 hours ago), 2024-09-10 01:27:20 -0400
    • Engine revision 3dc8b71f96
    • Dart version 3.6.0 (build 3.6.0-232.0.dev)
    • DevTools version 2.39.0
```
</details>

**Comment by thejitenpatel** [comment] 2024-09-10 13:42
Hi @danagbemava-nc 👋, I am not able reproduce this bug on master branch, please verify again.

**Comment by danagbemava-nc** [comment] 2024-09-10 13:43
Thanks for the heads up @bleroux. I may have forgotten to test on master 😅😅 while I was checking for regression.

Closing this as fixed on the master channel

**Closed by danagbemava-nc** 2024-09-10 13:43 UTC
Labels: c: regression, platform-android, has reproducible steps, team-text-input, found in release: 3.24, found in release: 3.25

**Comment by bleroux** [comment] 2024-09-10 13:52
> Thanks for the heads up @bleroux. I may have forgotten to test on master 😅😅 while I was checking for regression.
> 
> Closing this as fixed on the master channel

No worry, you are juggling with so many flutter versions and platforms :exploding_head: .
The way your check issues on those various combinations is so useful, thanks! :pray:

**Comment by lavinov-mercury** [comment] 2024-09-10 14:02
That’s great that the issue is already fixed, thanks!
Do you know when this fix will be included in a stable release?

**Comment by bleroux** [comment] 2024-09-10 14:22
This fix is in the beta channel for the moment, see [this discussion](https://github.com/flutter/flutter/issues/154398#issuecomment-2340794481) for more details.
