### ISSUE TITLE
Spacing Error in SliverChildBuilderDelegate when using specific margin values

### ISSUE THREAD

**Issue by maupleke** [flutter/flutter#65810] opened 2020-09-15 02:53 UTC
I'm seeing unintended spacing lines when using SliverChildBuilderDelegate to dynamically build groups of items based on containers without top and bottom margins.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update main.dart to attached sample [main.zip](https://github.com/flutter/flutter/files/5222183/main.zip)
3.  Thin lines between some containers shouldn't be displayed as the containers don't have any margin between then

![Screenshot_1600138200](https://user-images.githubusercontent.com/71303348/93159770-4db6f100-f6e5-11ea-90a7-d7043a1c931f.png)

**Expected results:** 
Expected contiguous panels made of containers without top and bottom margin

**Actual results:** 
Thin lines between some containers

```
C:\Dev\Sample\flutter_app>flutter analyze
Analyzing flutter_app...
No issues found! (ran in 11.7s)
```

```
C:\Dev\Sample\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.2 at C:\DevTools\flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mauricio\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\DevTools\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\DevTools\AndroidStudio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

</details>

**Comment by maupleke** [comment] 2020-09-15 03:02
`
import 'package:flutter/material.dart';

const Color colorScaffoldBackground = Colors.white;
const Color colorAccountOverviewbackground = Colors.red;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Overview> _overviewList = List<Overview>();

  @override
  void initState() {
    super.initState();
    _loadOverviewList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: colorScaffoldBackground,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: buildMain(),
    );
  }

  Container buildMain() {
    return Container(
        color: colorAccountOverviewbackground,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: _listView(),
          ),
        ));
  }

  List<Widget> _listView() {
    return [
      Expanded(
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, pos) => _buildAccountRow(context, pos),
                childCount: _overviewList.length,
              ),
            ),
          ],
        ),
      ),
    ];
  }

  Widget _buildAccountRow(BuildContext context, int pos) {
    switch (_overviewList[pos].rowType) {
      case 'HEADER':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10, top: 5),
            padding: EdgeInsets.only(left: 8, right: 8, top: 6, bottom: 6),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(topLeft: Radius.circular(15), topRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Text(_overviewList[pos].name),
                  ],
                ),
              ],
            ),
          );
        }
        break;

      case 'ACCOUNT':
        {
          return Container(
            color: colorScaffoldBackground,
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    SizedBox(
                      width: 5,
                    ),
                    Container(
                      width: 30,
                      alignment: Alignment.centerLeft,
                      child: Icon(
                        _overviewList[pos].iconData,
                        size: 16,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;

      case 'TOTAL':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(bottomLeft: Radius.circular(15), bottomRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 5),
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;
    }
    return SizedBox.shrink();
  }

  void _loadOverviewList() {
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Accounts'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 1', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 2', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Wallet', iconData: Icons.account_balance_wallet));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Credit Cards'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Visa', iconData: Icons.credit_card));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Savings'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Car Fund', iconData: Icons.directions_car));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Home Fund', iconData: Icons.home));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Vacation Fund', iconData: Icons.local_airport));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Emergency Fund', iconData: Icons.local_hospital));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Retirement Fund', iconData: Icons.lock));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
  }
}

class Overview {
  String rowType;
  String name;
  IconData iconData;

  Overview({
    this.rowType,
    this.name,
    this.iconData,
  });
}
`

**Comment by maupleke** [comment] 2020-09-15 03:03
```
import 'package:flutter/material.dart';

const Color colorScaffoldBackground = Colors.white;
const Color colorAccountOverviewbackground = Colors.red;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Overview> _overviewList = List<Overview>();

  @override
  void initState() {
    super.initState();
    _loadOverviewList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: colorScaffoldBackground,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: buildMain(),
    );
  }

  Container buildMain() {
    return Container(
        color: colorAccountOverviewbackground,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: _listView(),
          ),
        ));
  }

  List<Widget> _listView() {
    return [
      Expanded(
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, pos) => _buildAccountRow(context, pos),
                childCount: _overviewList.length,
              ),
            ),
          ],
        ),
      ),
    ];
  }

  Widget _buildAccountRow(BuildContext context, int pos) {
    switch (_overviewList[pos].rowType) {
      case 'HEADER':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10, top: 5),
            padding: EdgeInsets.only(left: 8, right: 8, top: 6, bottom: 6),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(topLeft: Radius.circular(15), topRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Text(_overviewList[pos].name),
                  ],
                ),
              ],
            ),
          );
        }
        break;

      case 'ACCOUNT':
        {
          return Container(
            color: colorScaffoldBackground,
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    SizedBox(
                      width: 5,
                    ),
                    Container(
                      width: 30,
                      alignment: Alignment.centerLeft,
                      child: Icon(
                        _overviewList[pos].iconData,
                        size: 16,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;

      case 'TOTAL':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(bottomLeft: Radius.circular(15), bottomRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 5),
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;
    }
    return SizedBox.shrink();
  }

  void _loadOverviewList() {
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Accounts'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 1', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 2', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Wallet', iconData: Icons.account_balance_wallet));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Credit Cards'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Visa', iconData: Icons.credit_card));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Savings'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Car Fund', iconData: Icons.directions_car));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Home Fund', iconData: Icons.home));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Vacation Fund', iconData: Icons.local_airport));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Emergency Fund', iconData: Icons.local_hospital));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Retirement Fund', iconData: Icons.lock));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
  }
}

class Overview {
  String rowType;
  String name;
  IconData iconData;

  Overview({
    this.rowType,
    this.name,
    this.iconData,
  });
}

```

**Comment by TahaTesser** [comment] 2020-09-15 09:10
Hi @maupleke 
This interesting , I notice space goes away if we provide more top margin or remove, I can only see it with value of 5 on top margin

**`margin: EdgeInsets.only(left: 10, right: 10, top: 0),`**
<img src="https://user-images.githubusercontent.com/48603081/93190433-ff473800-f760-11ea-9590-19dcf4087e97.png" width="400" height="800" />

**`margin: EdgeInsets.only(left: 10, right: 10, top: 20),`**
<img src="https://user-images.githubusercontent.com/48603081/93190445-02422880-f761-11ea-8ac7-28a9ecb43be3.png" width="400" height="800" />

**`margin: EdgeInsets.only(left: 10, right: 10, top: 5),`**
<img src="https://user-images.githubusercontent.com/48603081/93190460-053d1900-f761-11ea-9cbe-746005e91849.png" width="400" height="800" />

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

const Color colorScaffoldBackground = Colors.white;
const Color colorAccountOverviewbackground = Colors.red;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Overview> _overviewList = List<Overview>();

  @override
  void initState() {
    super.initState();
    _loadOverviewList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: colorScaffoldBackground,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: buildMain(),
    );
  }

  Container buildMain() {
    return Container(
        color: colorAccountOverviewbackground,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: _listView(),
          ),
        ));
  }

  List<Widget> _listView() {
    return [
      Expanded(
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, pos) => _buildAccountRow(context, pos),
                childCount: _overviewList.length,
              ),
            ),
          ],
        ),
      ),
    ];
  }

  Widget _buildAccountRow(BuildContext context, int pos) {
    switch (_overviewList[pos].rowType) {
      case 'HEADER':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10, top: 5),
            padding: EdgeInsets.only(left: 8, right: 8, top: 6, bottom: 6),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(15), topRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Text(_overviewList[pos].name),
                  ],
                ),
              ],
            ),
          );
        }
        break;

      case 'ACCOUNT':
        {
          return Container(
            color: colorScaffoldBackground,
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    SizedBox(
                      width: 5,
                    ),
                    Container(
                      width: 30,
                      alignment: Alignment.centerLeft,
                      child: Icon(
                        _overviewList[pos].iconData,
                        size: 16,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;

      case 'TOTAL':
        {
          return Container(
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(
                  bottomLeft: Radius.circular(15),
                  bottomRight: Radius.circular(15)),
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 5),
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;
    }
    return SizedBox.shrink();
  }

  void _loadOverviewList() {
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Accounts'));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'Bank Account 1',
        iconData: Icons.account_balance));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'Bank Account 2',
        iconData: Icons.account_balance));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'Wallet',
        iconData: Icons.account_balance_wallet));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Credit Cards'));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT', name: 'Visa', iconData: Icons.credit_card));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Savings'));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'New Car Fund',
        iconData: Icons.directions_car));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT', name: 'New Home Fund', iconData: Icons.home));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'Vacation Fund',
        iconData: Icons.local_airport));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT',
        name: 'Emergency Fund',
        iconData: Icons.local_hospital));
    _overviewList.add(Overview(
        rowType: 'ACCOUNT', name: 'Retirement Fund', iconData: Icons.lock));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
  }
}

class Overview {
  String rowType;
  String name;
  IconData iconData;

  Overview({
    this.rowType,
    this.name,
    this.iconData,
  });
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.3 at C:\Code\flutter_stable
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details> 



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.174, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.174 at C:\Code\flutter_master
    • Framework revision 37b03ec2c2 (5 hours ago), 2020-09-14 23:52:04 -0400
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.102

• No issues found!```

</details>

**Comment by knaeckeKami** [comment] 2020-09-15 10:21
Probably related:
https://github.com/flutter/flutter/issues/14288
https://github.com/flutter/flutter/issues/25009
https://github.com/flutter/flutter/issues/15035#issuecomment-370028740

**Comment by maupleke** [comment] 2020-09-15 11:43
Closing as dupe from #14288

**Comment by TahaTesser** [comment] 2020-09-15 11:45
Hi @maupleke 
Not sure about that, do you think this is related to color?

**Comment by TahaTesser** [comment] 2020-09-15 11:52
I would suggest keeping this open to track this bug until further confirmation since the reproducing case isn't exactly the same    as https://github.com/flutter/flutter/issues/14288

**Comment by maupleke** [comment] 2020-09-15 13:15
@TahaTesser seems to be an kown issue affecting all controls: [You're drawing a series of rectangles adjacent to each other, on top of a different background color, but they don't quite line up with the physical pixel boundaries. This means we try to antialias the edges, and each one is painted on top of the background, so the background shows up in the antialiasing. This is working as intended; it's how graphics works.](https://github.com/flutter/flutter/issues/15035#issuecomment-370028740)

I've changed the margins as you suggested and the issue continues, probably because my device has a different pixel density than yours.

I've changed my approach to keep container color the same as background color as recommended on the cases and added visual effects using box decoration:

![Screenshot_1600175653](https://user-images.githubusercontent.com/71303348/93215088-571f7800-f73c-11ea-9d91-82b6070714a3.png)

Code:

```
import 'package:flutter/material.dart';

const Color colorScaffoldBackground = Colors.white;
const Color colorBoxShadow = Color(0x1a000000);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Overview> _overviewList = List<Overview>();

  @override
  void initState() {
    super.initState();
    _loadOverviewList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: colorScaffoldBackground,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: buildMain(),
    );
  }

  Widget buildMain() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: _listView(),
    );
  }

  List<Widget> _listView() {
    return [
      Expanded(
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, pos) => _buildAccountRow(context, pos),
                childCount: _overviewList.length,
              ),
            ),
          ],
        ),
      ),
    ];
  }

  Widget _buildAccountRow(BuildContext context, int pos) {
    Widget sliver;
    switch (_overviewList[pos].rowType) {
      case 'HEADER':
        {
          sliver = Container(
            margin: EdgeInsets.only(left: 10, right: 10, top: 20),
            padding: EdgeInsets.only(left: 8, right: 8, top: 6, bottom: 6),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(topLeft: Radius.circular(15), topRight: Radius.circular(15)),
              boxShadow: [
                BoxShadow(
                  color: colorBoxShadow,
                  blurRadius: 5,
                  spreadRadius: 0,
                  offset: Offset(0, -5),
                ),
              ],
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Text(_overviewList[pos].name),
                  ],
                ),
              ],
            ),
          );
        }
        break;

      case 'ACCOUNT':
        {
          sliver = Container(
            color: colorScaffoldBackground,
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    SizedBox(
                      width: 5,
                    ),
                    Container(
                      width: 30,
                      alignment: Alignment.centerLeft,
                      child: Icon(
                        _overviewList[pos].iconData,
                        size: 16,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;

      case 'TOTAL':
        {
          sliver = Container(
            margin: EdgeInsets.only(left: 10, right: 10),
            padding: EdgeInsets.only(left: 8, right: 8, top: 10, bottom: 10),
            decoration: BoxDecoration(
              color: colorScaffoldBackground,
              borderRadius: BorderRadius.only(bottomLeft: Radius.circular(15), bottomRight: Radius.circular(15)),
              boxShadow: [
                BoxShadow(
                  color: colorBoxShadow,
                  blurRadius: 5,
                  spreadRadius: 0,
                  offset: Offset(0, 5),
                ),
              ],
            ),
            child: Column(
              children: <Widget>[
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 5),
                        child: Text(
                          _overviewList[pos].name,
                          overflow: TextOverflow.fade,
                          softWrap: false,
                        ),
                      ),
                    ),
                  ],
                )
              ],
            ),
          );
        }
        break;
    }

    return sliver;
  }

  void _loadOverviewList() {
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Accounts'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 1', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Bank Account 2', iconData: Icons.account_balance));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Wallet', iconData: Icons.account_balance_wallet));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Credit Cards'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Visa', iconData: Icons.credit_card));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
    _overviewList.add(Overview(rowType: 'HEADER', name: 'Savings'));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Car Fund', iconData: Icons.directions_car));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'New Home Fund', iconData: Icons.home));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Vacation Fund', iconData: Icons.local_airport));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Emergency Fund', iconData: Icons.local_hospital));
    _overviewList.add(Overview(rowType: 'ACCOUNT', name: 'Retirement Fund', iconData: Icons.lock));
    _overviewList.add(Overview(rowType: 'TOTAL', name: 'TOTAL'));
  }
}

class Overview {
  String rowType;
  String name;
  IconData iconData;

  Overview({
    this.rowType,
    this.name,
    this.iconData,
  });
}


```

**Comment by TahaTesser** [comment] 2020-09-16 08:54
Hi @maupleke 
Thanks for confirming, definitely sounds like a known issue related to anti-aliasing 
Closing as duplicate of #14288
If you disagree, please write in the comments, I will reopen it 
Thank you

**Closed by TahaTesser** 2020-09-16 08:54 UTC
Labels: a: quality, f: scrolling, found in release: 1.20, found in release: 1.22, framework, has reproducible steps
