### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'dependencies' was called on null.Receiver: nullTried calling: dependencies

### ISSUE THREAD

**Issue by yannanna0920** [flutter/flutter#71391] opened 2020-11-30 06:51 UTC
## Command
```
flutter update-packages --force-upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'dependencies' was called on null.
Receiver: null
Tried calling: dependencies
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      createTemporaryFlutterSdk (package:flutter_tools/src/commands/update_packages.dart:1457:60)
#2      UpdatePackagesCommand.runCommand (package:flutter_tools/src/commands/update_packages.dart:322:33)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1119:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:974:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:264:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.17763.1577], locale zh-CN)
    • Flutter version 1.24.0-8.0.pre.374 at D:\软件\flutter_windows_v1.2.1-stable\flutter
    • Framework revision 183f0e797a (4 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yannanna\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\yannanna\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\yannanna\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.35.1)
    • VS Code at C:\Users\yannanna\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.4+15
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b

**Comment by TahaTesser** [comment] 2020-11-30 10:20
Hi @yannanna0920 
Are you using `build_runner` or any package that depends on it? 
https://github.com/dart-lang/build/issues/2569

**Comment by jonahwilliams** [comment] 2020-11-30 14:03
@yannanna0920  unless you are planning to contribute a PR to flutter, you should not ever run that command - it can break your SDK. To update the dependencies of your package use `flutter pub get`.

**Comment by zanderso** [comment] 2020-12-08 22:35
Duplicate of https://github.com/flutter/flutter/issues/71876

**Closed by zanderso** 2020-12-08 22:35 UTC
Labels: in triage, waiting for customer response

**Comment by yannanna0920** [comment] 2020-12-31 09:24
> @ yannanna0920 除非您打算为PR做出贡献，否则永远不要运行该命令-它会破坏您的SDK。要更新软件包的依赖关系，请使用`flutter pub get`。

Update path error resolved. Thank you

**Comment by digitpk** [comment] 2021-02-10 11:26
but still, I am getting this error:

Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0, flutter_localizations from sdk is incompatible with intl_translation >=0.17.7.
Because intl_utils >=1.6.3 <1.9.0 depends on intl_translation 0.17.10 and intl_utils >=1.9.0 depends on intl_translation 0.17.10+1, intl_utils >=1.6.3 requires intl_translation 0.17.10 or 0.17.10+1.
Thus, flutter_localizations from sdk is incompatible with intl_utils >=1.6.3.
So, because food_delivery_app depends on both flutter_localizations any from sdk and intl_utils ^1.8.0, version solving failed.
pub get failed (1; So, because food_delivery_app depends on both flutter_localizations any from sdk and intl_utils ^1.8.0, version solving failed.)

**Comment by zanderso** [comment] 2021-02-10 16:30
@digitpk This issue is closed, and it looks like you are having a different problem. Please file a new issue with full details.
