### ISSUE TITLE
How to release Timer in flutter?

### ISSUE THREAD

**Issue by zhouyangyng** [flutter/flutter#42569] opened 2019-10-12 08:11 UTC
I have added flutter to my iOS app. When I use Timer in flutter, it works. And I release timer in dispose() method, but it's not called when I pop FlutterViewController. So it causes a memory leak.

Flutter doctor log:

```
[✓] Flutter (Channel master, v1.9.6-pre.44, on Mac OS X 10.14.6
    18G95, locale zh-Hans-CN)
    • Flutter version 1.9.6-pre.44 at /Users/xmly/flutter
    • Framework revision d3b70c91bf (6 weeks ago), 2019-08-27
      19:08:35 -0700
    • Engine revision f93b9cbff1
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK
    version 29.0.1)
    • Android SDK at /Users/xmly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for
      native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone SE   • 09C906C2-D2F0-4D59-B6BD-D929FA079E7D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by jmagman** [comment] 2019-10-15 20:29
This looks like a duplicate of the other issue you filed. https://github.com/flutter/flutter/issues/42643.

**Closed by jmagman** 2019-10-15 20:29 UTC
Labels: d: stackoverflow, engine, ⌺‬ platform-ios
