### ISSUE TITLE
setVertexArrayObject: set vao to

### ISSUE THREAD

**Issue by kaarens93** [flutter/flutter#67420] opened 2020-10-06 15:44 UTC
Not an issue per say but I would like to know the meaning behind this message. I am getting a TON of these messages on my console which makes it extremely hard to debug because I have to scroll through all the 'setVertexArrayObject' messages. For context, I am using a package which uses a webview.

**Comment by Dasunx** [comment] 2020-10-06 16:54
Duplicate of #48079
Take a look at this issue

**Comment by kaarens93** [comment] 2020-10-07 00:01
Thanks @Dasunx. Good to know I'm not the only one having this issue, however; like the most recent commenter, I don't want to downgrade (currently using stable 1.20.4). Also no mention of what this error message means

**Comment by darshankawar** [comment] 2020-10-07 07:19
@kaarens93 
Please provide `flutter doctor -v` and a minimal code sample that has plugin code you are using.
Thanks.

**Comment by pedromassangocode** [comment] 2020-10-28 11:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-28 11:41 UTC
Labels: in triage
