### ISSUE TITLE
Invalid VM configuration on Android Things

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#17726] opened 2018-05-18 17:29 UTC
Low priority

## Environment

Flutter (Channel master, v0.2.5-pre.396, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
Android things 8.1.0
Board: NXP i.MX7D

## Steps to Reproduce

When building a release build for Android Things Dart will crash due to an incompatible VM configuration error. Debug builds work fine but are extremely slow.

## Logs

```
05-18 10:20:21.906 1928-1928/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Things/iot_imx7d_pico/imx7d_pico:8.1.0/OIM1.180327.036/4760714:userdebug/dev-keys'
05-18 10:20:21.907 1928-1928/? A/DEBUG: Revision: '0'
    ABI: 'arm'
    pid: 1902, tid: 1902, name: [omitted]  >>> [omitted] <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-18 10:20:21.912 1928-1928/? A/DEBUG: Abort message: '[FATAL:flutter/runtime/dart_vm.cc(413)] Error while initializing the Dart VM: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override arm-eabi hardfp' but the VM has 'product no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override arm-eabi softfp'
    '
        r0 00000000  r1 0000076e  r2 00000006  r3 00000008
        r4 0000076e  r5 0000076e  r6 be984cdc  r7 0000010c
        r8 00000000  r9 be984e24  sl a47be310  fp a47be300
        ip 8e088239  sp be984cc8  lr a51b29f7  pc a51ac428  cpsr 200f0030
05-18 10:20:21.924 1928-1928/? A/DEBUG: backtrace:
        #00 pc 0001a428  /system/lib/libc.so (abort+63)
        #01 pc 0014efab  /data/app/[omitted]--SMXeEezHwIfOxBFVkjgmw==/lib/arm/libflutter.so
        <lots more of those>
        #15 pc 000022f1  /data/app/[omitted]--SMXeEezHwIfOxBFVkjgmw==/oat/arm/base.odex (offset 0x2000)
```

**Comment by mraleph** [comment] 2018-05-20 10:30
Duplicate of #17387

**Comment by mraleph** [comment] 2018-05-20 10:31
Should have been fixed by @cbracken on master AFAIK. Please tell us if it is not fixed.

**Closed by mraleph** 2018-05-20 10:30 UTC
