### ISSUE TITLE
Add the Share features for web also

### ISSUE THREAD

**Issue by rahulkushwaha-techconfer** [flutter/flutter#75412] opened 2021-02-04 12:16 UTC
Hi sir ,you are doing great job . This dependencies is very smooth to use in  android . I want to use this in Flutter web also. So, Please add these features in upcoming release of your dependencies . 
 Thanks..

**Comment by darshankawar** [comment] 2021-02-04 13:54
Closing this as duplicate of https://github.com/flutter/flutter/issues/55330

**Closed by darshankawar** 2021-02-04 13:54 UTC
