### ISSUE TITLE
[Web][CanvasKit][Mobile]: Various TextField cursor bugs on iOS Safari and Chrome browsers

### ISSUE THREAD

**Issue by git9am** [flutter/flutter#78031] opened 2021-03-12 15:51 UTC
## Steps to Reproduce

1. Create a new flutter app by `flutter create textfield`.
2. Modify `main.dart`, adding some TextFields  in a scrollable widget. Code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: SingleChildScrollView(
        child: Container(
          color: Colors.white,
          child: Column(children: [
            SizedBox(height: 20), make(2, null),
            SizedBox(height: 30), make(4, null), 
            SizedBox(height: 40), make(6, null),
            SizedBox(height: 50), make(8, null),
            SizedBox(height: 60), make(10, null),
            SizedBox(height: 70), make(12, null)
          ]),
        ),
      ),
    );
  }

  TextField make(minLines, maxLines) {
    return TextField(
      minLines: minLines,
      maxLines: maxLines,
      keyboardType: TextInputType.multiline,
      decoration: InputDecoration(filled: true, isDense: true, fillColor: Colors.yellow, focusColor: Colors.yellow),
      style: TextStyle(color: Colors.black, fontSize: 14, height: 1.4, backgroundColor: Colors.yellow),
    );
  }
}

```
3. Build the app `flutter build web --web-renderer canvaskit --dart-define=FLUTTER_WEB_USE_SKIA=true `
4. Host the app with any server
5. Visit the app from an iPhone's Safari (or Chrome, which shows same bugs)
6. We see three buggy behaviors:
  - Bug 1 (Most often):
    - Scroll to a tall TextField 
    - Long press to focus on it
    - Watch the keyboard pops up
  - Bug 2 (Quite often):
    - Focus on a TextField
    - Scroll
    - Another cursor shows up
  - Bug 3 (Less often but not hard to reproduce):
    - Double tap to focus on a TextField
    - Two cursors are blinking (They're very close and almost overlapped)

**Expected results:** 
For Bug 1: After the keyboard pops up, the TextField should show properly.
For Bug 2: There's only one cursor.
For Bug 3: There's only one cursor.

**Actual results:** 
For Bug 1: After the keyboard pops up, the TextField shows less than it should be.
For Bug 2: There are two cursors.
For Bug 3: There are two cursors.

<details>
  <summary>Logs</summary>

```
```

```
Analyzing textfield...                                                  
No issues found! (ran in 3.4s)
```

```
[✓] Flutter (Channel beta, 2.0.0, on macOS 11.2.1 20D74 darwin-x64, locale en-CN)
    • Flutter version 2.0.0 at /Users/hejq/flutter
    • Framework revision 60bd88df91 (9 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hejq/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • ObjectPhone (mobile) • 00008101-001D70941189003A • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192
```

</details>

https://user-images.githubusercontent.com/39660295/110963908-9813e480-838d-11eb-9996-a6bbbf09e939.MP4

https://user-images.githubusercontent.com/39660295/110963944-a104b600-838d-11eb-8ae0-71674961f58a.MP4

https://user-images.githubusercontent.com/39660295/110963964-a82bc400-838d-11eb-99d9-e9f7bb9f1ed9.MP4

**Comment by darshankawar** [comment] 2021-03-15 13:25
@git9am 
Thanks for the detailed report.
Can you please confirm if the same behavior persists on latest beta (2.0.1) or master (2.1.0) ?

**Comment by git9am** [comment] 2021-03-16 12:28
> @git9am
> Thanks for the detailed report.
> Can you please confirm if the same behavior persists on latest beta (2.0.1) or master (2.1.0) ?

Yes it reproduces on master.

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.104, on macOS 11.2.3 20D91 darwin-x64, locale en-CN)
    • Flutter version 2.1.0-13.0.pre.104 at /Users/hejq/flutter
    • Framework revision 5be3f215ed (5 hours ago), 2021-03-16 08:35:00 +0100
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hejq/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
```

Tested on iOS 14.4.

Uploading RPReplay_Final1615897058.mov…

**Comment by darshankawar** [comment] 2021-03-17 07:20
Thanks for the detailed bug report @git9am.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by mdebbar** [comment] 2021-03-23 16:53
### Bug 1
I'm not able to reproduce this one. From the video, it looks more like a rendering issue not a text editing issue (cc @yjbanov & @hterkelsen).

### Bug 2
I'm unable to reproduce this one either.

### Bug 3
The 3rd bug (double caret) is a known issue (https://github.com/flutter/flutter/issues/70841).

**Comment by git9am** [comment] 2021-06-19 12:38
I did a few research and found something, but I'm not sure if it's relevant to this issue.

Enabling `_debugVisibleTextEditing` (`src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart`) in the flutter engine shows flutter `TextField` and the `textarea` element not overlapping.

![Simulator Screen Shot - iPhone 12 - 2021-06-19 at 20 31 55](https://user-images.githubusercontent.com/39660295/122642542-846edb80-d13d-11eb-9a71-cb63262fc242.png)

![Simulator Screen Shot - iPhone 12 - 2021-06-19 at 20 32 32](https://user-images.githubusercontent.com/39660295/122642546-89338f80-d13d-11eb-92c7-8d53b5f9c976.png)

Same thing happens on a PC Chrome but there's no browser highlight or tooltip, so everything works.

![screenshot-20210619-203333](https://user-images.githubusercontent.com/39660295/122642619-eaf3f980-d13d-11eb-8adc-309dfe4a4fab.png)

**Comment by dreamchrome** [comment] 2023-01-02 04:01
TextFields, especially multiline ones, are still unusable for us for web on mobile browsers as of 3.3.10. The bug isn't noticeable on a simple page with one TextField. But when it's nested deep in a scrollable widget, custom fonts etc., trying to tap the cursor to anywhere results in the cursor jumping to the start, end, or some random place in between.

**Comment by inyong1** [comment] 2023-06-10 05:36
The issue also happened in a dialog even the dialog only contains of on simple TextField

https://github.com/flutter/flutter/assets/5109308/9ef136ea-aacb-40fc-9159-756754c082c4

**Comment by yjbanov** [comment] 2023-08-03 18:14
Bug #1 is captured by https://github.com/flutter/flutter/issues/129174. Since we deduplicated 2 out of 3, and the third one couldn't be reproduced, I'm closing this issue in favor of the existing ones.

**Closed by yjbanov** 2023-08-03 18:14 UTC
Labels: a: text input, engine, a: typography, platform-web, c: rendering, a: build, e: web_canvaskit, has reproducible steps, P1, found in release: 2.0, browser: safari-ios, team-web, multiteam-retriage-candidate
