### ISSUE TITLE
Flutter, error: Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.

### ISSUE THREAD

**Issue by tanvirgeek** [flutter/flutter#50786] opened 2020-02-14 07:45 UTC
I am getting an error in runtime. I do not have any clue whats the error about:

The error:
Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.

**Comment by TahaTesser** [comment] 2020-02-14 08:17
Hi ... 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by RomanJos** [comment] 2020-02-16 10:37
Because tou either passed a null value to Color() or missed 0xFF before the actual hex code which is the alpha channel https://api.flutter.dev/flutter/material/Colors-class.html

**Comment by TahaTesser** [comment] 2020-03-06 09:11
Hi @tanvirgeek 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-06 09:11 UTC
Labels: waiting for customer response

**Comment by epipheus** [comment] 2020-04-05 11:42
I get this same error from the following:
```dart
MaterialApp(
      theme: ThemeData(
        primaryColor: Color.fromRGBO(9, 11, 34, 0.75),
        accentColor: Colors.deepPurple[700],
      ),
      home: InputPage(),
    );
```

**Comment by TahaTesser** [comment] 2020-04-06 10:16
Hi @epipheus 
Can you please create a new issue and please the details using the template?
Thank you
