### ISSUE TITLE
"No runnable apps" after project creation in Atom

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2587] opened 2016-03-10 22:23 UTC
Steps to repro:

* Open Atom
* Select Flutter, Create new project
* Let the project creation finish

Expected:

The "run targets" widget in the toolbar shows "lib/main.dart (flutter)" in the select dropdown.

Actual:

"No runnable apps" is displayed, and no way to refresh that UI widget.

![screen shot 2016-03-10 at 2 21 37 pm](https://cloud.githubusercontent.com/assets/5479/13686615/73f98aa0-e6cb-11e5-852b-5fd31f7230a4.png)

Workaround:

* close the main.dart
* open the main.dart

FWIW I worked with at least one person in the codelab that was confused by this behavior. It's non-obvious that I need to close and open the file. And it's weird not having a way to refresh the run target window itself.

**Comment by sethladd** [comment] 2016-03-10 22:23
cc @devoncarew

**Comment by devoncarew** [comment] 2016-03-11 00:07
We should write a launch config file for the app when creating the project.

**Comment by devoncarew** [comment] 2016-03-11 16:30
Dupe of #2176

**Closed by devoncarew** 2016-03-11 16:30 UTC
Labels: affects: atom-plugin, ⚠ bug
