### ISSUE TITLE
An error occurred when I inserted children into Stack

### ISSUE THREAD

**Issue by Cvilia** [flutter/flutter#38617] opened 2019-08-15 09:57 UTC
Stack(children: <Widget>[_headerBg(context), _headerCard(context)])
Above is my Stack,both _headerBg and _headerCard return Container,but Container‘s child is null,
Logcat showed me 
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.

**Comment by melwinlobo18** [comment] 2019-08-15 16:40
Can you create a gist of the code and share the link?

**Comment by BondarenkoStas** [comment] 2019-09-05 13:51
This is a question better suited for StackOverflow, since it seems to be related to implementation, not to the flutter itself. See https://flutter.dev/community for support options. 
As you didn't provide any more information, I assume the issue is solved and close it. If you disagree, feel free to comment here and I will reopen it.

**Closed by BondarenkoStas** 2019-09-05 13:51 UTC
