### ISSUE TITLE
Make it easier to provide a builder for Grid

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#8952] opened 2017-03-22 14:32 UTC
I'm using a GridLayout to show images loaded from the network, see below

```dart
class NewReleases extends StatefulWidget {
  @override
  createState() {
    return new NewReleasesState();
  }
}

class NewReleasesState extends State<StatefulWidget> {
  List<Container> newReleases = new List();

  @override
  Widget build(BuildContext context) {
    return new Container(child: getGrid());
  }

  @override
  void initState() {
    super.initState();
    loadNewReleases();
  }

  Widget getGrid() {
    return new GridView.extent(
        maxCrossAxisExtent: 150.0,
        padding: const EdgeInsets.all(4.0),
        mainAxisSpacing: 4.0,
        crossAxisSpacing: 4.0,
        children: newReleases);
  }

  loadNewReleases() async {
    List<TORelease> releases = await NewReleaseController.getNewReleases();
    print(releases.length);
    for (int i = 0; i < releases.length; i++) {
      newReleases
          .add(new Container(child: new Image.network(releases[i].imageURL)));
    }
    setState(() {});
  }
}
```

This works fine on iOS
![simulator screen shot mar 22 2017 10 28 51 am](https://cloud.githubusercontent.com/assets/253700/24202864/7e40f550-0eea-11e7-9122-83c29d7d3d70.png)

However on Android (physical device) it just loads a black screen.

**Comment by Hixie** [comment] 2017-03-22 16:36
If you dump the newReleases array in the build function, does it show build being called with a full array?

**Comment by FaisalAbid** [comment] 2017-03-23 04:09
Actually I don't know what the heck is going on anymore. I'm so confused.
Turns out this isn't just an android issue. Because i was using the simulator to deploy, I was using the instant run mode in flutter to deploy the change and the newReleases array was already built out so the album covers were showing.

This happens on iOS too. The issue is very weird.

@eseidelGoogle I am going to rename this issue

```
class NewReleasesState extends State<StatefulWidget> {
  List<Container> newReleases = [new Container(child: new Image.network("https://flutter.io/images/flutter-mark-square-100.png"))];

  @override
  Widget build(BuildContext context) {
    return getGrid();
  }

  @override
  void initState() {
    super.initState();
    loadNewReleases();
  }

  Widget getGrid() {
    print("New releases grid now has ${newReleases.length}");
    return new GridView.extent(
        maxCrossAxisExtent: 150.0,
        padding: const EdgeInsets.all(4.0),
        mainAxisSpacing: 4.0,
        crossAxisSpacing: 4.0,
        children: newReleases);
  }

  loadNewReleases() async {
    newReleases.clear();
    List<TORelease> releases = await NewReleaseController.getNewReleases();
    for (int i = 0; i < releases.length; i++) {
      newReleases
          .add(new Container(child: new Image.network(releases[i].imageURL)));
    }
    setState(() {
      print("set state");
      newReleases = newReleases;
    });
  }
}
```

## **So first run** Everything is black except a flutter logo
![simulator screen shot mar 23 2017 12 06 07 am](https://cloud.githubusercontent.com/assets/253700/24231711/85fd7ac6-0f5c-11e7-91b9-f167a8e2a653.png)

The print statements are as follow.

```
New releases grid now has 1
New releases grid now has 0
set state
New releases grid now has 20
```
If you notice when I do newReleases.clear();, it looks like getGrid is running right away, newReleases =0;

then I call setState and getGrid is run again, and now newReleases = 20

but the view does not refresh. it is still the flutter logo.

**Comment by Hixie** [comment] 2017-03-23 19:42
There's two problems with the code:
1. You should assume that builds can happen all the time. That's why you rebuild with size zero. There's something else in the system that happens to be rebuilding (probably the WidgetsApp because of the i18n redundant-rebuild bug), and that's triggering you to rebuild.
2. You're passing the same list object in every time, so the system assumes nothing has changed. In Flutter, once you've passed a List to a widget, you should never modify it again.

To fix it, just change loadNewReleases to create a new list instead of clearing and updating the old one.

The main red flag is that in your first sample, you have an emply setState, which means you likely haven't changed any state, and in the second, you have a setState with a redundant call (setting something to itself), which again probably means you haven't changed any state.

**Comment by FaisalAbid** [comment] 2017-03-23 19:46
Thanks Ian, i will try this shortly and let you know. 

Appreciate the detailed response!

**Comment by sethladd** [comment] 2017-03-23 19:49
> You're passing the same list object in every time, so the system assumes nothing has changed. In Flutter, once you've passed a List to a widget, you should never modify it again.

If I may ask a follow-up, I believe you're talking about this line: `children: newReleases);`

Since we're creating a new instance of GridView (`new GridView.extent`) in build(), isn't that sufficient to signal that "something has changed" ? (clearly not :) but trying to learn more here)

setState is the signal that says "this widget's state has changed, please schedule me for rebuilding". At least, that's my impression :) so why do I need to be aware of the identity of the lists I pass as children to widgets that are created during build() ?

Thanks!

**Comment by FaisalAbid** [comment] 2017-03-23 19:55
That was my thought processes as well. I assumed when build ran, it checked if there are new items in the listview and went okay time to render new stuff since I signalled setState

**Comment by FaisalAbid** [comment] 2017-03-23 20:23
Hey @Hixie  

I changed loadNewReleases to the following code but still getting the same issue.

```
  loadNewReleases() async {
    newReleases = new List();
    List<TORelease> releases = await NewReleaseController.getNewReleases();
    setState(() {
      for (int i = 0; i < releases.length; i++) {
        newReleases
            .add(new Container(child: new Image.network(releases[i].imageURL)));
      }
    });
  }
```

**Comment by Hixie** [comment] 2017-03-23 20:32
> Since we're creating a new instance of GridView (`new GridView.extent`) in build(), isn't that sufficient to signal that "something has changed" ? (clearly not :) but trying to learn more here)

It's enough to signal that something has changed, but it's not enough to signal _what_ has changed. And in this case, the list hasn't changed, it's the same list (it's `operator==` with the old one).

> I changed loadNewReleases to the following code but still getting the same issue.

Move the `newReleases = new List();` into the setState, so it's after the `await`. The problem is that with your new code you're still running the risk that your build function gets called between when you update the `newReleases` member to the new list, and when you actually populate it. As soon as the build function uses the new list, it's too late to mutate it.

**Comment by sethladd** [comment] 2017-03-23 20:53
> it's operator== with the old one

Ah, so, build() returns a Widget. And then the framework compares that return value with the previously returned value via `operator==`, and GridView's `operator==` incorporates all of its parameters (including children:). I hope I got that right.

**Comment by Hixie** [comment] 2017-03-23 21:19
In this particular case the list is passed to a delegate class which then responds to a "shouldRelayout" function by using `operator==` on the list in the new object vs the old object. So your description is wrong in the specifics but correct in the general sense, yes.

**Comment by FaisalAbid** [comment] 2017-03-23 21:25
so hypothetically if I was building a chat app, whenever a new message came through the websocket, I would have to rebuild the list + the new message?

**Comment by sethladd** [comment] 2017-03-23 21:40
Thanks! Your explanations definitely helped.

**Comment by Hixie** [comment] 2017-03-23 21:59
@FaisalAbid I would recommend using a GridView.custom in that case (or indeed in any case where you have many widgets, or if you don't know ahead of time how many widgets you have), passing it a  SliverChildBuilderDelegate for the childrenDelegate and a SliverGridDelegateWithMaxCrossAxisExtent for the gridDelegate (the latter is what GridView.extent does).

cc @abarth It might be worth making the builder case the default rather than the child list case, for grids.

**Comment by FaisalAbid** [comment] 2017-03-23 22:04
I see! I wish it was easier! Maybe a GridView.dynamic where I dont have to do so much work myself and just pass in a list and keep updating it

**Comment by eseidelGoogle** [comment] 2017-04-06 15:57
@Hixie how do we understand the priority of this bug?  It sounds like this is not a blocker (@faisalAbid has something working), but it would be an API breaking change and thus should be M2?

**Comment by Hixie** [comment] 2017-04-07 00:16
Correct. API stability.

**Comment by Hixie** [comment] 2017-04-18 22:31
@abarth I'm assigning this one to you as the person who is most familiar with grids. Feel free to WONTFIX if you think the API is fine.

**Closed** 2017-04-21 21:09 UTC
Labels: customer: tunes (eap), prod: API stability, ▣ platform-android

**Comment by eseidelGoogle** [comment] 2017-04-26 21:17
@Skylled hit a variant of this (mutating a list and passing it repeatedly) in Gitter just now. :(
