### ISSUE TITLE
>flutter doctor -v fatal: bad config line 1 in file C:\ProgramData/Git/config

### ISSUE THREAD

**Issue by RaviDhakad** [flutter/flutter#36439] opened 2019-07-18 09:05 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad config line 1 in file C:\ProgramData/Git/config

```
#0      _runSync (package:flutter_tools/src/version.dart:522:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:501:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#45     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad config line 1 in file C:\ProgramData/Git/config


#0      _runSync (package:flutter_tools/src/version.dart:522:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:501:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:192:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:125:33)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:51:10)
#31     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#32     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by stuartmorgan** [comment] 2019-07-18 13:02
Duplicate of #31050

**Closed by stuartmorgan** 2019-07-18 13:02 UTC

**Comment by ibnmusaally** [comment] 2020-08-03 07:30
git: fatal: bad config line 1 in file .git/config

**Comment by ibnmusaally** [comment] 2020-08-03 07:31
how to solve this issue

**Comment by JusticeSelormBruce** [comment] 2020-08-03 09:26
> how to solve this issue

you are getting this error because you have not initialize git.

just initialize git and you should be good to go

**Comment by mkchouhan2016** [comment] 2020-08-15 17:05
> > how to solve this issue
> 
> you are getting this error because you have not initialize git.
> 
> just initialize git and you should be good to go

>How to initialize git sir??? in window

**Comment by Shreyasharma92** [comment] 2020-09-17 19:28
using git init command
