### ISSUE TITLE
Support for Android Dynamic Delivery

### ISSUE THREAD

**Issue by prasanthkvm** [flutter/flutter#18070] opened 2018-05-31 13:07 UTC
https://developer.android.com/guide/app-bundle/configure is this possible with flutter?

**Comment by Hixie** [comment] 2018-06-12 23:14
Looks like "Dynamic Delivery" and "App Bundle" is the same, so closing as duplicate of https://github.com/flutter/flutter/issues/17829.

**Closed by Hixie** 2018-06-12 23:14 UTC
