### ISSUE TITLE
iOS simulator hangs on 'waiting for observatory port to be available'.

### ISSUE THREAD

**Issue by claeyssensstef** [flutter/flutter#114154] opened 2022-10-27 14:20 UTC
While running the default counter app on an iOS simulator, my app hangs while waiting for observatory port to be available.
I tried both with Flutter version 3.0.5 and 3.3.6.
I tried downgrading XCode from 14 to 13.4.1
I tried deleting the DerivedData folder. 
I tried with an iOS 15.5 simulator and a iOS 16.0 simulator.
None of the above fixed the issue.
A colleague of mine who uses an Intel Mac with XCode 13.4.1 can't reproduce the issue.

## Steps to Reproduce

1. `flutter create myap`
2. `open -a Simulator`
3. `flutter run -v`
4. simulator starts with a white screen, but hangs on the observatory port for approximately 10 minutes
5. eventually the simulator shows the counter app as expected

## Logs

<details>
<summary>Logs</summary>

This part of the logs is the final part of the verbose logs since the terminal cuts off the output if it is too long.

```

[   +3 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch C16F3E62-9938-4A50-9DE2-55A9FBF795E1 com.example.flutterBugtest --enable-dart-profiling --enable-checked-mode
--verify-entry-points --observatory-port=0
[ +264 ms] com.example.flutterBugtest: 76133
[        ] Waiting for observatory port to be available...
[+103630 ms] Observatory URL on device: http://127.0.0.1:59153/IV-Ph6UdH4o=/
[  +10 ms] Caching compiled dill
[  +43 ms] Connecting to service protocol: http://127.0.0.1:59153/IV-Ph6UdH4o=/
[  +97 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:59153/IV-Ph6UdH4o=/.
[  +44 ms] DDS is listening at http://127.0.0.1:59156/FUpRzsO9q4M=/.
[  +31 ms] Successfully connected to service protocol: http://127.0.0.1:59153/IV-Ph6UdH4o=/
[  +17 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device
(file:///Users/stefclaeyssens/Library/Developer/CoreSimulator/Devices/C16F3E62-9938-4A50-9DE2-55A9FBF795E1/data/Containers/Data/Application/4CA7FACD-532B-450B-83E0-24581B22A92
B/tmp/flutter_bugtestIkS6AF/flutter_bugtest/)
[   +1 ms] Updating assets
[  +61 ms] Syncing files to device iPhone 13 mini...
[   +3 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_bugtest/main.dart 1ddd7e1f-4af4-4a2c-98aa-a56f4399836c
[        ] <- 1ddd7e1f-4af4-4a2c-98aa-a56f4399836c
[        ] Bundle processing done.
[ +135 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone 13 mini... (completed in 137ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +8 ms] Connected to _flutterView/0x13500d020.
[   +4 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 13 mini is available at: http://127.0.0.1:59156/FUpRzsO9q4M=/
[  +43 ms] The Flutter DevTools debugger and profiler on iPhone 13 mini is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:59156/FUpRzsO9q4M=/

```

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.5 21G72 darwin-arm, locale nl-BE)
    • Flutter version 3.3.6 on channel stable at /Users/stefclaeyssens/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (2 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/stefclaeyssens/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • C16F3E62-9938-4A50-9DE2-55A9FBF795E1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by navaronbracke** [comment] 2022-10-27 16:53
@claeyssensstef I forgot to mention this earlier, you can pipe the terminal output to a file, since by default it gets truncated.

`flutter run -v > /path/to/file/log.txt`

Could you update the OP and add the logfile as an attachment to it?


cc @bkonyi The observatory message was changed in https://github.com/dart-lang/sdk/issues/46756 but I still see `Waiting for observatory port to be available...` when running with Flutter 3.3.5 / Dart 2.18.2, even though that issue mentioned that the cutoff would have been Dart 2.17.

I don't get any problems with a hanging Simulator though, so I'm not sure why the ProcessDiscovery could be hanging on https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L490

**Comment by bkonyi** [comment] 2022-10-27 17:19
> cc @bkonyi The observatory message was changed in [dart-lang/sdk#46756](https://github.com/dart-lang/sdk/issues/46756) but I still see `Waiting for observatory port to be available...` when running with Flutter 3.3.5 / Dart 2.18.2, even though that issue mentioned that the cutoff would have been Dart 2.17.

The `Waiting for observatory port to be available...` is likely coming from `flutter_tools`, not the Dart VM. While that message should be changed as well, it shouldn't be causing any issues at this point.

**Comment by huycozy** [comment] 2022-10-28 10:11
Hi @claeyssensstef 
Can you please provide the full log of `flutter run -v` as @navaronbracke mentioned at https://github.com/flutter/flutter/issues/114154#issuecomment-1293810236? And please also retry on the latest Flutter `master` channel to check if the issue still reproduces. 

Also, I find there is issue #111167 which may be similar to this by its log (_Waiting for observatory port to be available..._) and it's reproducible on M1 machine.

**Comment by claeyssensstef** [comment] 2022-10-28 11:15
I believe that in shutting off my system overnight, the problem seems to be resolved (for now). 
I've still attached the `flutter run -v` log file since the issue might show up again.
[log.txt](https://github.com/flutter/flutter/files/9887869/log.txt)

**Comment by navaronbracke** [comment] 2022-10-28 11:34
@huycozy the issue you mentioned seems eerily similar to this problem. I'd suggest we close this issue as a duplicate?

**Comment by huycozy** [comment] 2022-10-28 12:21
@navaronbracke thanks for your attention to this issue. This issue may be duplicated to https://github.com/flutter/flutter/issues/111167. The OP didn't have the error message, though.  

@claeyssensstef When you face this issue again, can you retry on the latest master channel and check if you encounter the same behavior as [domesticmouse](https://github.com/domesticmouse) at https://github.com/flutter/flutter/issues/111167#issuecomment-1243641894?

**Comment by Ali1Ammar** [comment] 2022-10-28 23:31
> I believe that in shutting off my system overnight, the problem seems to be resolved (for now). I've still attached the `flutter run -v` log file (where the issue is resolved) since the issue might show up again. [log.txt](https://github.com/flutter/flutter/files/9887869/log.txt)

that work for me too restarting the computer fix the bugs

**Closed** 2022-11-18 13:17 UTC
Labels: waiting for customer response, in triage
