### ISSUE TITLE
An unpleasant flash between the launch screen and the first screen of the app IOS

### ISSUE THREAD

**Issue by umagloire99** [flutter/flutter#72129] opened 2020-12-11 09:58 UTC
hello everyone,
 i have customised a launch screen `LaunchStoryBoard` of my application on ios using xcode which works fine. Also constraints are set and shows excellently. Basically a logo at the `top-center` and a text `below` as show in the image below. However, when transitioning (when app finishes to launch) to the main screen , It pulls up an unpleasant flash between the text and the top centered image. All elements are stacked to the top before the main screen appears.

I think it has to do with the way flutter renders the main screen or the outgoing transition. Any help in debugging this behavior will be greatly appreciated.

Steps
- Create a custom splash (LaunchStoryBoard)  screen of more than two entities e.g (imageView, Label or text).
- Run the the app on any simulator or real device.
- See the transition between Launch screen and main story board. 
- Elements are stacked to the top.

Screenshots
- LaunchStoryBoard Screen
<img width="116" alt="original" src="https://user-images.githubusercontent.com/36057707/101889236-7a24c100-3b9f-11eb-8722-3f542e9d4fef.png">

- MainStoryBoard screen
<img width="116" alt="Untitled" src="https://user-images.githubusercontent.com/36057707/101889447-b22c0400-3b9f-11eb-93db-7f398ce75793.png">

 I am using
```
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (3 months ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

**Comment by TahaTesser** [comment] 2020-12-11 11:46
Hi @umagloire99 
Looks like you're running few months old Flutter, please upgrade to the latest `stable`

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` UPDATED  your `flutter run --verbose` and a complete reproducible minimal code sample in a repository 
Thank you

**Comment by wenxiangjiang** [comment] 2020-12-12 04:37
The same as #65823 ?

**Comment by muarachmann** [comment] 2020-12-12 21:44
Hi @TahaTesser yes I can confirm this. I am using the latest flutter and Xcode versions. Layout renders properly but at the tail end when transitioning to the main screen, Logo and other widgets stack up.

```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/muarachmann/Library/Android/Contents
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by muarachmann** [comment] 2020-12-14 04:00
> The same as #65823 ?

@wenxiangjiang yes very correct, and I noticed this happens each time you modify the default LaunchStoryBoard even with the slightest of constraints. Keeping it as default as it comes has no issues. In my use case I wanted a more personalized launch screen maybe some text below and image at the center but the transition makes it horrible.

@TahaTesser  Feel free to close this in favour of #65823

**Comment by TahaTesser** [comment] 2020-12-14 15:07
@wenxiangjiang 
Can you please provde detalls asked in https://github.com/flutter/flutter/issues/72129#issuecomment-743148100

**Comment by wenxiangjiang** [comment] 2020-12-14 15:12
@TahaTesser I have provided details in #65823

**Comment by umagloire99** [comment] 2020-12-20 16:52
still facing the same issue! anyone to help me pls?

**Comment by TahaTesser** [comment] 2020-12-21 07:03
@umagloire99 
Closing as duplicate of  https://github.com/flutter/flutter/issues/65823
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-21 07:03 UTC
Labels: in triage
