### ISSUE TITLE
Reading data 3 times from firestore while using Stream Builder

### ISSUE THREAD

**Issue by dileepxdn** [flutter/flutter#31733] opened 2019-04-27 18:01 UTC
I have create a firebase project and inserted 100 documents into firestore collection app and I have created a stream builder and get those documentsin that collection so,   I have closed and opened app and updated and deleted some documents then I have firestore usage it reached up to 3.2k reads. And writes and deletes are normal . Later I ran log in stream builder I have seen that at each update or delete firestore getting data 3 times . Please solve or show me a way to solve this issue.

**Comment by BondarenkoStas** [comment] 2019-10-16 12:18
@dileepxdn did you manage to fix it? If not, please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close the issue here.

**Comment by iapicca** [comment] 2019-11-08 09:55
Hi @dileepxdn 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:55 UTC
Labels: waiting for customer response
