### ISSUE TITLE
Address null safety exclusions in flutter/flutter

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#110021] opened 2022-08-22 17:09 UTC
See https://github.com/flutter/flutter/issues/110016 for context.

- [x] migrate `dev/devicelab/test/runner_test.dart:5:// @dart = 2.8`: https://github.com/flutter/flutter/pull/110582
- [-] files excluded to test backwards compatibility with pre 2.12:
  ```
  dev/integration_tests/web/lib/null_assert_main.dart:5:// @dart = 2.8
  packages/flutter/test/foundation/_compute_caller_unsound_null_safety.dart:5:// @dart=2.9
  packages/flutter/test/foundation/_compute_caller_unsound_null_safety_error.dart:5:// @dart=2.9
  ```
- [x] convert `dev/integration_tests/android_semantics_testing` to null safety (https://github.com/flutter/flutter/issues/90633)

- [x] Remaining flutter/flutter work - flutter_tools - tracked in https://github.com/flutter/flutter/issues/71511)

**Comment by jmagman** [comment] 2022-08-22 17:21
Duplicate of https://github.com/flutter/flutter/issues/71511

**Comment by jmagman** [comment] 2022-08-22 17:22
Actually I guess this needs to track:
```
dev/devicelab/test/runner_test.dart:5:// @dart = 2.8
dev/integration_tests/web/lib/null_assert_main.dart:5:// @dart = 2.8
packages/flutter/test/foundation/_compute_caller_unsound_null_safety.dart:5:// @dart=2.9
packages/flutter/test/foundation/_compute_caller_unsound_null_safety_error.dart:5:// @dart=2.9
```

**Comment by devoncarew** [comment] 2022-08-22 17:26
Thanks - I updated the first comment to reflect the other (flutter tools) issue.

**Comment by goderbauer** [comment] 2022-08-30 17:35
> files deliberately excluded to test backwards compatibility with pre 2.12:

I believe the tests/files listed in this section can just be deleted once we don't support non-null-safe code anymore.

**Comment by goderbauer** [comment] 2022-08-30 17:38
> convert dev/integration_tests/android_semantics_testing to null safety

In the past, we have filed to migrate this to null safety, see https://github.com/flutter/flutter/issues/90633 for some history.

**Comment by devoncarew** [comment] 2022-09-13 21:26
I'm going to close this out as the last 3 exclusions are intentional for testing pre-null safe behavior. We will need a way to track and remove those as well at some point.

**Closed** 2022-09-13 21:27 UTC
Labels: framework, a: null-safety, P4
