### ISSUE TITLE
Failed Android build: Android dependency has different version for the compile (27.0.1) and runtime (27.1.1) classpath

### ISSUE THREAD

**Issue by dconeybe** [flutter/flutter#24570] opened 2018-11-20 18:19 UTC
## Steps to Reproduce

1. Launch Android Studio
2. Click "Start a new Flutter project"
3. Select "Flutter Application" and click "Next"
4. Fill out project information in the following screens, clicking "Next" then click "Finish" on the last screen
5. Open pubspec.yml in the Android Studio editor
6. Add the following under "dev_dependencies":
```yml
  flutter_launcher_icons: ^0.6.1
  google_sign_in: ^3.2.1
  firebase_analytics: ^1.0.3
  firebase_auth: ^0.5.20
  firebase_database: ^1.0.4
  firebase_storage: ^1.0.3
  flutter_firebase_ui: ^0.0.11
  image_picker: ^0.4.10
  image_cropper: ^0.0.8
```
7. Press the "Play" button to build and run the application.

## Expected Results:
App compiles and runs successfully

## Actual Results:
```
App fails to compile, with the following error:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-core-utils' has different version for the compile (27.0.1) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```
## Logs

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.11.7, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.7 at /Users/dconeybe/local/flutter
    • Framework revision 7a005e1dcd (26 hours ago), 2018-11-19 11:14:05 -0500
    • Engine revision 2e06da3df9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/dconeybe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode_10.0.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

Here is the Flutter application that failed to compile:
[buildbug.zip](https://github.com/flutter/flutter/files/2601012/buildbug.zip)

**Comment by dconeybe** [comment] 2018-11-20 19:04
FYI I was able to work around this build problem by adding the following lines to the "android" section of android/app/build.gradle

```
    configurations.all {
        resolutionStrategy.force 'com.android.support:support-compat:27.1.1'
        resolutionStrategy.force 'com.android.support:appcompat-v7:27.1.1'
        resolutionStrategy.force 'com.android.support:support-v4:27.1.1'
    }
```

I now have other runtime issues (app crashes upon launch, most likely unrelated to this bug report) but at least it compiles :)

**Comment by Isonomic** [comment] 2018-12-30 03:58
I dont know why or how this works, but thank you so much. I love people like you who are freaking brilliant

**Comment by zoechi** [comment] 2018-12-30 15:00
Duplicate of: #25862

**Closed by zoechi** 2018-12-30 15:00 UTC
Labels: p: first party, plugin, severe: crash
