### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: There is not enough space on the disk., errno = 112

### ISSUE THREAD

**Issue by fulldev100** [flutter/flutter#136056] opened 2023-10-06 01:49 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: There is not enough space on the disk.
, errno = 112
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:606:14)
#2      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:124:16)
#3      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:81:17)
#4      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#5      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#6      ChromiumLauncher._restoreUserSessionInformation (package:flutter_tools/src/web/chrome.dart:347:24)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:194:7)
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:133:38)
#9      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:521:29)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
    • Flutter version 2.0.1 at D:\Projects\Flutter\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (2 years, 7 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-20\bin\java
    • Java version Java(TM) SE Runtime Environment (build 20.0.1+9-29)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.77.3)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 117.0.2045.47

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
path_provider-2.0.4
path_provider_linux-2.1.6
path_provider_macos-2.0.3
path_provider_windows-2.0.6
sqflite-2.0.2
url_launcher-5.7.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1

**Comment by danagbemava-nc** [comment] 2023-10-06 08:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/54213

**Closed by danagbemava-nc** 2023-10-06 08:15 UTC
Labels: in triage
