### ISSUE TITLE
[tool_crash] Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by rishav00a** [flutter/flutter#62571] opened 2020-07-30 11:46 UTC
## Command
```
flutter --no-color create --org co.domain app_name
```

## Logs
ArgumentError: Invalid argument(s): Invalid type for "path": null
```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:162:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:25:41)
#2      ForwardingFileSystem.directory (package:file/src/forwarding/forwarding_file_system.dart:23:49)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:256:21)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:63:38)
#5      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:629:46)
#6      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:543:29)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:37)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.330], locale en-US)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\asus\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\asus\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\asus\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM A605G • 6590a8fb • android-arm • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment] 2020-07-30 12:19
duplicate of https://github.com/flutter/flutter/issues/56811

**Closed by TahaTesser** 2020-07-30 12:19 UTC
