### ISSUE TITLE
Spans cannot have a zero length Android (only on Samsung Galaxy Grand Prime)

### ISSUE THREAD

**Issue by AlexiCoard** [flutter/flutter#10363] opened 2017-05-27 12:42 UTC
## Steps to Reproduce

Initialize a Textfield with a controller, basically with : 

```dart
final TextEditingController _controller = new TextEditingController();
    _controller.text = "";

   new TextField(
        controller: _controller,
        decoration: new InputDecoration(hintText: 'Message...')
    )
```
## Logs

When I tap on the textfield, I got the following error displayed on IntelliJ : 

```
D/ViewRootImpl(18079): ViewPostImeInputStage ACTION_DOWN
E/SpannableStringBuilder(18079): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(18079): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(18079): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(18079): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

Got this error only on my Samsung Galaxy Grand Prime (my personnal phone running with Android 5.0.2, as I cannot get a newer version atm). When I tried my code on a Galaxy Tab with Android 5.1 i didn't get the problem.

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [version 10.0.15063], channel alpha)
    • Flutter at C:\Users\alexi\flutter
    • Framework revision 973304d5fb (9 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\alexi\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] Android Studio (version 2.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[√] WebStorm (version 2016.3)
    • Flutter plugin version 12.1

[√] Connected devices
    • SM G530FZ • 504fd4cc • android-arm • Android 5.0.2 (API 21)

```

Any known issue related ?

**Comment by eseidelGoogle** [comment] 2017-05-27 14:47
Sounds like an issue with our text input integration on Android.  We're presumably sending values to the Android IME system it does not expect to get.

**Comment by eseidelGoogle** [comment] 2017-05-27 14:48
This may also relate to the Samsung Keyboard?  We got another report about samsung keyboard quirks in https://github.com/flutter/flutter/issues/10341.

**Comment by AlexiCoard** [comment] 2017-05-27 14:52
Don't think it is related to a keyboard in particular,  I tried with the Samsung keyboard and the Google keyboard. Got the same issue for both

**Comment by markentingh** [comment] 2017-06-04 01:03
I'm getting this error as well, on an Android emulator running Pixel (Android version 7.1.1) with the default keyboard selected

**Comment by eseidelGoogle** [comment] 2017-06-04 17:29
https://stackoverflow.com/questions/13670374/android-span-exclusive-exclusive-spans-cannot-have-a-zero-length may have some context?

**Comment by AlexiCoard** [comment] 2017-06-08 19:01
Just tried with a Oneplus 3t with Android 7.1, with the keyboard hiding the textfield and not, no problems, seems like a bug with Android 5

**Comment by BenSower** [comment] 2017-06-29 09:24
I had the same Problem on a
* Samsung Galaxy S6
* Samsung Galaxy S5
* Motorola GB 3

With both Samsung Keyboard, Google Keyboard and Swiftkey.

**Comment by eseidelGoogle** [comment] 2017-06-29 15:21
@jason-simmons has been in this code recently and might know.  It's unclear from the comments above if all reporters are talking about the same issue.

Is the issues just the log message?  Or is there some other behavior that is being reported here?

**Comment by AlexiCoard** [comment] 2017-06-29 15:24
From the issue a first reported, it was not only the log message.

When I tapped on the textfield, the keyboard was displayed for like 0.5s and then was closed automatically, displaying the log I gave (Spans cannot have zero length), preventing the user to use the textInput. So yes, it is a bug and not just a strange log

**Comment by eseidelGoogle** [comment] 2017-06-29 15:31
So the keyboard immediately disappearing may be a bug @Hixie is working on as we speak (more generally of widgets going offscreen and losing their state).

**Comment by BenSower** [comment] 2017-06-30 06:45
@eseidelGoogle 
For me, the issue is only the log messages. I had another problem creating an infinite loop printing this log message over and over again, which led me to believe it is somehow connected, but I could rule that out. 
For now, it's not really a real issue, just an annoyance.

**Comment by barchoum** [comment] 2018-09-13 21:15
I have the same problem when i try to use the onClickListener ,
this is the message when i debug (E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length.
                          SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length).
please help

**Comment by aaronfg** [comment] 2018-10-19 03:30
I'm having this same issue -- it is just a log message. No behavior issues can be detected by me anyhow.

Tried on Pixel 1, Essential PH-1, Nexbit Robin and Android Sim.

Tried stock google kb and Swiftkey on all physical devices.

Doesn't appear to be device specific at all.

**Comment by SuperMata** [comment] 2018-12-05 02:21
Hi, I get the same error when I type on a TextFormField.
E/SpannableStringBuilder( 4207): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```
TextFormField(
                scrollPadding: EdgeInsets.all(4),
                controller: descriptionController,
                enableInteractiveSelection: bool.fromEnvironment('true'),
                decoration: new InputDecoration(
                    labelText: 'Incident Description',
                  icon: Icon(FontAwesomeIcons.pencilAlt)
                ),
                maxLines: 8,
                validator: (value) {
                  if (value.isEmpty) {
                    return 'Please provide description';
                  }
                },
              )
```

**Comment by Dikymon** [comment] 2018-12-07 13:01
I'm in a similar situation as @SuperMata, but if I remove the enclosing Form() the error is no longer there.

**Comment by joaovirgili** [comment] 2018-12-26 01:59
I have the both errors. Log span an the listview with a TextFormField closing after i click it.

**Comment by sofpanos** [comment] 2019-05-03 09:24
Was getting the same issue on Xiaomi RED Mi Note 4 with swift key keyboard, switching to Gboard made the error message disappear.

**Comment by MatiDeve** [comment] 2019-06-16 19:13
Hi, I had the same error. In my case, the problem wasn't the TextFormField. It was because of the key inside the Form widget. If you use a key, the general widget must be StatefulWidget, not StatelessWidget.

Wrong code

    ```
class MyWidget extends StatelessWidget{
      final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
      @override
      Widget build(BuildContext context) {
        // TODO: implement build
        return Scaffold(
          body: Form(
            key: _formKey,
            child: TextFormField(),
          ),
        );
      }
    }
```

Right Code

    ```
class MyWidget extends StatefulWidget{
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return _MyWidgetState();
      }
    }
    
    class _MyWidgetState extends State<MyWidget>{
      final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
      @override
      Widget build(BuildContext context) {
        // TODO: implement build
        return Scaffold(
          body: Form(
            key: _formKey,
            child: TextFormField(),
          ),
        );
      }
    }
```

**Comment by knockshore** [comment] 2019-10-09 06:33
> Hi, I had the same error. In my case, the problem wasn't the TextFormField. It was because of the key inside the Form widget. If you use a key, the general widget must be StatefulWidget, not StatelessWidget.
> 
> Wrong code
> 
> ```
> class MyWidget extends StatelessWidget{
>      final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
>      @override
>      Widget build(BuildContext context) {
>        // TODO: implement build
>        return Scaffold(
>          body: Form(
>            key: _formKey,
>            child: TextFormField(),
>          ),
>        );
>      }
>    }
> ```
> 
> Right Code
> 
> ```
> class MyWidget extends StatefulWidget{
>       @override
>       State<StatefulWidget> createState() {
>         // TODO: implement createState
>         return _MyWidgetState();
>       }
>     }
>     
>     class _MyWidgetState extends State<MyWidget>{
>       final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
>       @override
>       Widget build(BuildContext context) {
>         // TODO: implement build
>         return Scaffold(
>           body: Form(
>             key: _formKey,
>             child: TextFormField(),
>           ),
>         );
>       }
>     }
> ```

Thanks, this worked.

**Comment by samoray1998** [comment] 2020-01-23 09:06
i'm useing the huawei y6 and i got the same error when i tried to do this :

 Expanded(
                      child: TextFormField(
                        decoration: InputDecoration(
                          hintText: 'Phone number',
                          
                          prefixIcon: Icon(Icons.phone)
                        ),
                        
                      ),
                    ),

**Comment by TahaTesser** [comment] 2020-03-10 11:47
Hi @samoray1998 
Please take a look at this [comment](https://github.com/flutter/flutter/issues/10363#issuecomment-502478029)

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final TextEditingController _controller = new TextEditingController();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  void initState() {
    _controller.text = "";
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Form(
          key: _formKey,
          child: TextFormField(
              controller: _controller,
              decoration: new InputDecoration(hintText: 'Message...')),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

### Running on 

```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

Reproduce no issues

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you

**Closed by TahaTesser** 2020-03-10 11:47 UTC
Labels: a: text input, e: device-specific, framework, ▣ platform-android
