### ISSUE TITLE
Video_player first frame stuck on iOS.

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [flutter/flutter#88414] opened 2021-08-18 06:50 UTC
When i play video using Video_player,  it's first frame Stuck. This is an issue for iOS real device. 
I am having timer on behalf of video playing. 
There is no api to detect if it is still or not.

**Comment by TahaTesser** [comment] 2021-08-18 08:13
Hi @ADARSHAGNIHOTRI 
Can you please provide `flutter doctor -v`, your `video_player` version, a minimal complete reproducible code sample] and `flutter run -v > run.log` (this will copy your logs in a file, please drop this file in the comments below)
Thank you

**Comment by ADARSHAGNIHOTRI** [comment] 2021-08-18 09:34
@TahaTesser 
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D75 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/rootinfosolutions/Documents/flutter1.22.6/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rootinfosolutions/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio copy.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio copy.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 52AE51DD-2938-40FB-BE4D-9216D196C1E7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
 video_player: ^2.1.14

**Comment by ADARSHAGNIHOTRI** [comment] 2021-08-18 09:35
@TahaTesser  Here is the issue which i was following but no updates there.

https://github.com/flutter/flutter/issues/65853

**Comment by ADARSHAGNIHOTRI** [comment] 2021-08-18 12:12
@FlutterIssues

**Comment by TahaTesser** [comment] 2021-08-19 08:47
closing as a duplicate of https://github.com/flutter/flutter/issues/65853

**Closed by TahaTesser** 2021-08-19 08:47 UTC
Labels: in triage

**Comment by ADARSHAGNIHOTRI** [comment] 2021-08-19 09:26
@TahaTesser closing this issue is good but i opened this issue only because there is no update on  #65853 .
