### ISSUE TITLE
Unable to find bundled Java version 

### ISSUE THREAD

**Issue by Francesco-FL** [flutter/flutter#118535] opened 2023-01-15 21:42 UTC
I just upgraded from Android Studio 2021 Chipmunk to Android Studio 2022 Electric eel, and I got this error in the "flutter doctor": Unable to find bundled Java version.

I've tried: deleting old versions of Android Studio, completely deleting and re-downloading Android Studio, and I've tried re-doing the <flutter config --android-studio-dir"...">. I find the same error both in an existing project, and in a completely new project.

However I can still build and install builds, is this normal? What problems should this error give me other than a warning from the flutter doctor?

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Versione 10.0.19045.2486], locale it-IT)
    • Flutter version 3.3.10 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\varot\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\varot\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.74
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by roufy235** [comment] 2023-01-15 22:29
[https://github.com/flutter/flutter/issues/118502](url)

**Comment by TahaTesser** [comment] 2023-01-16 10:36
duplicate of https://github.com/flutter/flutter/issues/106674

**Closed** 2023-01-16 10:37 UTC
