### ISSUE TITLE
google_sign_in: signInSilently breaks the app when it starts

### ISSUE THREAD

**Issue by GiacomoK** [flutter/flutter#28430] opened 2019-02-24 18:36 UTC
Hi,  
I get an error if I use `signInSilently` function when app starts.  
This is the code of main.dart file:

```dart
    void main() async {
      // Create Persistor
      final persistor = Persistor<AppState>(
        storage: FlutterStorage(),
        serializer: JsonSerializer<AppState>(AppState.fromJson),
      );

      // Load initial state
      final initialState = await persistor.load();
      bool logged = false;

      if (initialState.isLoggedIn && initialState.accessToken != null && initialState.loginType != null) {
        initialState.silentlyLogin(); // <---- HERE I GET THE ERROR
        logged = true;
      } else {
        initialState.logout();
      }

      final store = Store<AppState>(
        appReducer, /* Function defined in the reducers file */
        //initialState: initialState ?? AppState.initial(),
        initialState: initialState != null && logged ? initialState : AppState.initial(),
        middleware: [persistor.createMiddleware()],
      );

      runApp(Amalarte(store: store));
    }

    class MyApp extends StatefulWidget {
     ...
    }
```
This is the silentlyLogin function of my state: 
 ```dart
    void silentlyLogin() async {
        switch (loginType) {
          case "google":
            globals.googleSignIn.signInSilently();
            break;
        }
    }
```
This is globals file:  
```dart
    GoogleSignIn googleSignIn = GoogleSignIn(
      scopes: [
        'profile',
        'openid',
      ],
    );
```
I get the error on the line 551 del file `message_codecs.dart`:  

    throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);

I do not why and I do not know howto solve it.

**Comment by GiacomoK** [comment] 2019-02-24 19:12
I found the message error:  

    sign_in_required

I read this is a problem about app not authorized.  But the normal signin works like a charm. The silent login does not work.

**Comment by ifjorissen** [comment] 2019-03-21 19:46
Encountering this issue as well (but we've only observed it on iOS). We use firebase auth (with Google as the only enabled provider).

We've been doing this in our development environment-- building the app directly onto the ios device.
These are the steps that repro the issue most consistently:
1. Install app (debug build, if it matters) & sign in normally
2. Uninstall the app
3. Rebuild onto the device
4. At this point, our app attempts to silently sign in _if there's a firebase user where at least one provider is google_
5. Exception throws `sign in required`

Silent sign in fails whenever the app is updated. We've also found that attempting to login after getting this platform exception via interactive sign in hangs. Reopening the app seems to resolve this.

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(sign_in_required, com.google.GIDSignIn, The operation couldn’t be completed. (com.google.GIDSignIn error -4.))
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>                                               
#2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:226:58)
<asynchronous suspension>                                               
#3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:268:20)
#4      GoogleSignIn.signInSilently (package:google_sign_in/google_sign_in.dart:311:48)
#5      SignInService.signInWithGoogle (package:{OUR APP}/services/sign_in_service.dart:99:16)
<asynchronous suspension>                                               
#6      new SignInService.<anonymous closure> ({OUR APP}/services/sign_in_service.dart:61:19)
<asynchronous suspension>                                               
#7      _rootRunUnary (dart:async/<…>
```

Aside: we have tried catching the error by wrapping in try/catch blocks, setting `signInSilently({suppressErrors: false})`, and using catchError

**Comment by cyanglaz** [comment] 2019-03-27 16:37
@GiacomoK Could you try `signInSilently(suppressErrors:false)` to catch the error?

**Comment by stocksp** [comment] 2019-03-27 21:11
I can't catch the exception but the IDE (VS Code) stops and spits back

**Comment by cyanglaz** [comment] 2019-03-28 00:45
@stocksp What do you mean by 'I can't catch the exception but the IDE (VS Code) stops and spits back'?
Could you share a minimum app to reproduce the issue?

**Comment by stocksp** [comment] 2019-03-28 05:38
All I meant was that I wrapped the call to .signInSilently in a try catch but I don't catch anything.  It just breaks right in the IDE with the Exception I posted above.  Here is the code
void initState() {
    super.initState();
    state = AppState.free;
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      print('Change Sign in: $account');
    });
    try {
      _googleSignIn.signInSilently(suppressErrors:false); // here is where we stop
    } catch (e) {
      print('SigninSilent error $e');
    }
    
    print('Done with initState');
  }

**Comment by cyanglaz** [comment] 2019-03-28 15:47
> All I meant was that I wrapped the call to .signInSilently in a try catch but I don't catch anything. It just breaks right in the IDE with the Exception I posted above. Here is the code
> 
> ```
> void initState() {
>     super.initState();
>     state = AppState.free;
>     _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
>       setState(() {
>         _currentUser = account;
>       });
>       print('Change Sign in: $account');
>     });
>     try {
>       _googleSignIn.signInSilently(suppressErrors:false); // <--here is where we stop
>     } catch (e) {
>       print('SigninSilent error $e');
>     }
>     
>     print('Done with initState');
>   }
> ```
> I can post up my project tomorrow if it would help. It currently is using Firebase Vision stuff, so I'll have to remove my google plist stuff. I'll be able to revisit this late tomorrow morning and should be able to rebuild a simplified project without the Firebase. I saw this issue with signInSilently before I introduced Firebase...

@stocksp Thank you for providing the code block. Since `_googleSignIn.signInSilently(suppressErrors:false)` returns a Future, you won't be able to catch the error using a try-catch block directly. 
You can do something like ```     _googleSignIn.signInSilently(suppressErrors: false).catchError((dynamic e){
       print('$e');
     });```
to catch the error. 
There are more ways to catch error of a Future, you can find more details here. 
https://www.dartlang.org/guides/libraries/futures-error-handling

**Comment by stocksp** [comment] 2019-03-28 19:05
@cyanglaz thanks a million for your comment (I'm a reactNative dev so I'm still flailing with Dart).  I was  having an issue with the Vision package ... ended up deleting the pod lock file and reinstalling.  signInSilently now works as advertised !!

**Comment by GiacomoK** [comment] 2019-04-10 11:56
> @GiacomoK Could you try `signInSilently(suppressErrors:false)` to catch the error?

Tried the same initial code with this line edited:

`await globals.googleSignIn.signInSilently(suppressErrors: false);`

But I always get this error:

`sign_in_required`

**Comment by cyanglaz** [comment] 2019-04-10 19:48
@GiacomoK The error could be caused by not having a valid signed-in google account on the device. If you can catch the error, then you should be able to handle gracefully for user. (Ask user to sign in regularly again for example)

**Comment by Hixie** [comment] 2019-04-16 23:16
@GiacomoK Any updates from your end? Was @cyanglaz's idea helpful?

**Comment by Nolence** [comment] 2019-04-17 17:14
I feel like I'm in the same boat here. Based off a few SO answers, I updated and looked into my `debug.keystore` multiple times thinking it was something to do with that. What makes me think it isn't a mismatched SHA1 or SHA256 problem though is that I can successfully login if I remove the initial request to `signInSilently` on my login page. After I auth, if I close the app, add back the `signInSilently` request, and restart the debugger the call to sign in silently will also work.

What doesn't work is if I haven't signed in at all or am signed out and then hit the `signInSilently` -- I get a `com.google.android.gms.common.api.ApiException: 4` platform error that I cannot catch. I am also `awaiting` as @cyanglaz suggested:

```dart
// inside async func
try {
  GoogleSignInAccount _currentUser = await _googleSignIn.signInSilently(suppressErrors: true);
} catch (e) {
// } on PlatformException catch (e) { // doesn't work either
  print("$e");
}
```

![signinsilently_exception](https://user-images.githubusercontent.com/29642168/56307264-b3bed380-6101-11e9-848e-0f61c49d8ea1.PNG)

The only thing I'm doing non-standard since having created the flutter project was follow [this advice](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/37#issuecomment-439386380) in changing version numbers when I was having a seperate problem.

**Comment by GiacomoK** [comment] 2019-04-17 17:19
> @GiacomoK The error could be caused by not having a valid signed-in google account on the device. If you can catch the error, then you should be able to handle it gracefully. (Ask user to sign in regularly again for example)

What you mean with this?

> could be caused by not having a valid signed-in google account on the device

**Comment by cyanglaz** [comment] 2019-04-17 17:54
@GiacomoK I mean that signInSilently would only work if the user has already signed in. As the document in the Google Sign-In api states: `Attempts to sign in a previously authenticated user without interaction.`. You can find more details here: https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_sign_in

**Comment by cyanglaz** [comment] 2019-04-17 18:03
@Nolence Is it happening on iOS or Android? Could you paste your flutter doctor -v here?

**Comment by Nolence** [comment] 2019-04-17 18:54
Woah, thanks @cyanglaz! Yup, the IDE was catching the uncaught exception and that was the issue. 

![breakpoints](https://user-images.githubusercontent.com/29642168/56313186-38641e80-610f-11e9-858f-862ceac5c818.PNG)

I had `Uncaught Exceptions` checked. If you're still interested, here's the `flutter doctor -v` output:

```
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.3.8 at C:\src\flutter
    • Framework revision e5b1ed7a7f (6 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rexma\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\rexma\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

I haven't tested it with an Apple device yet, but I'll update this when I do (I'm assuming it'll work though).

**Comment by GiacomoK** [comment] 2019-04-19 15:28
> @GiacomoK I mean that signInSilently would only work if the user has already signed in. As the document in the Google Sign-In api states: `Attempts to sign in a previously authenticated user without interaction.`. You can find more details here: https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_sign_in

@cyanglaz  It seems that was my problem.
I tried this (my app is on Android):
- open the app and signin NOT silently (I chose my google account)
- close the app
- reopen the app and signin silently. Everything worked like a charm.

Thanks.

**Comment by cyanglaz** [comment] 2019-04-19 16:37
It seems like the issue has been resolved! I am closing the issue now. If any related issue has been found please feel free to open another one with details.

**Closed by cyanglaz** 2019-04-19 16:37 UTC
Labels: p: first party, p: google_sign_in, plugin, severe: crash

**Comment by halilcapa** [comment] 2020-03-16 10:27
**I get an error on this code line
![2020-03-15_00-50-21-ee6a806ef11acd83dd3d7314685d1a2b](https://user-images.githubusercontent.com/48388384/76747218-dd590280-6789-11ea-8f3d-cd314c90359d.png)
**
googleSignIn.signInSilently (suppressErrors: false) .then ((account) {
handleSignIn (account);
}). catchError ((err) {
print ('Oturum açma hatası: $ err');
});
}

HELPME PLEASE `import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:selfca/models/user.dart';
import 'package:selfca/pages/activity_feed.dart';
import 'package:selfca/pages/create_account.dart';
import 'package:selfca/pages/profile.dart';
import 'package:selfca/pages/search.dart';
import 'package:selfca/pages/timeline.dart';
import 'package:selfca/pages/upload.dart';
import 'package:google_sign_in/google_sign_in.dart';

final GoogleSignIn googleSignIn = GoogleSignIn();
final usersRef = Firestore.instance.collection('users');
final DateTime timestamp = DateTime.now();
User currentUser;

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool isAuth = false;
  PageController pageController;
  int pageIndex = 0;

  @override
  void initState() {
    super.initState();
    pageController = PageController();
    // Detects when user signed in
    googleSignIn.onCurrentUserChanged.listen((account) {
      handleSignIn(account);
    }, onError: (err) {
      print('Error signing in: $err');
    });
    // Reauthenticate user when app is opened
    googleSignIn.signInSilently(suppressErrors: false).then((account) {
      handleSignIn(account);
    }).catchError((err) {
      print('Error signing in: $err');
    });
  }

  handleSignIn(GoogleSignInAccount account) {
    if (account != null) {
      createUserInFirestore();
      setState(() {
        isAuth = true;
      });
    } else {
      setState(() {
        isAuth = false;
      });
    }
  }

  createUserInFirestore() async {
    // 1) check if user exists in users collection in database (according to their id)
    final GoogleSignInAccount user = googleSignIn.currentUser;
    DocumentSnapshot doc = await usersRef.document(user.id).get();

    if (!doc.exists) {
      // 2) if the user doesn't exist, then we want to take them to the create account page
      final username = await Navigator.push(
          context, MaterialPageRoute(builder: (context) => CreateAccount()));

      // 3) get username from create account, use it to make new user document in users collection
      usersRef.document(user.id).setData({
        "id": user.id,
        "username": username,
        "photoUrl": user.photoUrl,
        "email": user.email,
        "displayName": user.displayName,
        "bio": "",
        "timestamp": timestamp
      });

      doc = await usersRef.document(user.id).get();
    }

    currentUser = User.fromDocument(doc);
  }

  @override
  void dispose() {
    pageController.dispose();
    super.dispose();
  }

  login() {
    googleSignIn.signIn();
  }

  logout() {
    googleSignIn.signOut();
  }

  onPageChanged(int pageIndex) {
    setState(() {
      this.pageIndex = pageIndex;
    });
  }

  onTap(int pageIndex) {
    pageController.animateToPage(
      pageIndex,
      duration: Duration(milliseconds: 300),
      curve: Curves.easeInOut,
    );
  }

  Scaffold buildAuthScreen() {
    return Scaffold(
      body: PageView(
        children: <Widget>[
          // Timeline(),
          RaisedButton(
            child: Text('Logout'),
            onPressed: logout,
          ),
          ActivityFeed(),
          Upload(),
          Search(),
          Profile(),
        ],
        controller: pageController,
        onPageChanged: onPageChanged,
        physics: NeverScrollableScrollPhysics(),
      ),
      bottomNavigationBar: CupertinoTabBar(
          currentIndex: pageIndex,
          onTap: onTap,
          activeColor: Theme.of(context).primaryColor,
          items: [
            BottomNavigationBarItem(icon: Icon(Icons.whatshot)),
            BottomNavigationBarItem(icon: Icon(Icons.notifications_active)),
            BottomNavigationBarItem(
              icon: Icon(
                Icons.photo_camera,
                size: 35.0,
              ),
            ),
            BottomNavigationBarItem(icon: Icon(Icons.search)),
            BottomNavigationBarItem(icon: Icon(Icons.account_circle)),
          ]),
    );
    // return RaisedButton(
    //   child: Text('Logout'),
    //   onPressed: logout,
    // );
  }

  Scaffold buildUnAuthScreen() {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topRight,
            end: Alignment.bottomLeft,
            colors: [
              Theme.of(context).accentColor,
              Theme.of(context).primaryColor,
            ],
          ),
        ),
        alignment: Alignment.center,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text(
              'FlutterShare',
              style: TextStyle(
                fontFamily: "Signatra",
                fontSize: 90.0,
                color: Colors.white,
              ),
            ),
            GestureDetector(
              onTap: login,
              child: Container(
                width: 260.0,
                height: 60.0,
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage(
                      'assets/images/google_signin_button.png',
                    ),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return isAuth ? buildAuthScreen() : buildUnAuthScreen();
  }
}
`
