### ISSUE TITLE
Failed assertion in scroll_activity.dart after introducing firebase_dynamic_links

### ISSUE THREAD

**Issue by uf65** [flutter/flutter#70035] opened 2020-11-07 20:01 UTC
I got the following debug output

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 613 pos 15: 'to != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new DrivenScrollActivity (package:flutter/src/widgets/scroll_activity.dart:613:15)
#3      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:185:43)
#4      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:159:37)
#5      HomePageState._scrollToBottom (package:flutterapp/screens/Home.dart:47:23)
#6      HomePageState.initState.<anonymous closure> (package:flutterapp/screens/Home.dart:113:45)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

after introducing dynamic links to my app (firebase_dynamic_links). So I am filing the bug as suggested. My own piece of code (#5 from the stack) is as follows:

  _scrollToBottom() {
    _scrollController.animateTo(_scrollController.position.maxScrollExtent,
        duration: Duration(seconds: 10), curve: Curves.linear);
    new Timer(const Duration(seconds: 12), _jumpToTop);
  }

The connection between dynamic links and the scrollController is unclear to me, but I did not do much research yet.

**Comment by iapicca** [comment] 2020-11-08 09:41
@uf65 
for issue related to firebase I recommend to open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by TahaTesser** [comment] 2020-11-09 08:48
Hi @uf65 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-09 08:48 UTC
