### ISSUE TITLE
WebView's text selection dialog is not responding to touch events

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#24585] opened 2018-11-20 22:26 UTC
Internal: b/141519527

If you select text inside the webview and try to tap one of the copy/share/etc buttons it doesn't respond.

**Comment by nsharma098** [comment] 2018-12-27 16:49
Is their any progress in this issue?

**Comment by amirh** [comment] 2018-12-28 17:09
@DCrow I'm not aware of any related fix in the engine (note that this is on Android), are you sure about it?
(this is unrelated to #24207)

**Comment by lzxb** [comment] 2019-07-19 01:15
I also need it.

**Comment by XHL-study** [comment] 2019-07-19 13:03
me too

**Comment by masewo** [comment] 2019-07-20 10:49
Please upvote this issue if you need this 👍

**Comment by mtallenca** [comment] 2019-07-22 20:54
I have a solution for this bug but it's a total hack.  Flutter is capturing the touches and forwarding them to the webview.  Unfortunately on Android, the selection dialog is a top level window not in the webview, so when the webview gets the tap, the selection dialog is dismissed.   My current solution grabs the location of the selection dialog, then intercept touches when the selection dialog is visible and calls the appropriate menu handler when a tap should have been redirected to the selection dialog.

I can post a sample project if this isn't fixed soon.

**Comment by joelbrostrom** [comment] 2019-08-09 15:31
This might seam like a minor issue, but "look up"-apps relies on their customer to copy/paste items/names/phone numbers/order numbers etc.

Try asking a user to type `Microsoft Windows Vista Ultimate UPGRADE Limited Numbered Signature Edition #32NR07` on a mobile keyboard when comparison shopping. 😅

**Comment by wingohtcom** [comment] 2019-08-19 08:04
@mtallenca could post the sample project? looks like it's not going to be fixed anytime soon

**Comment by sibe7691** [comment] 2019-08-19 10:40
@mtallenca +1

**Comment by sldboy** [comment] 2019-08-21 03:44
me too,The keyboard can pop , but do not input text, on Android oppo, honor phone.

**Comment by Moycks** [comment] 2019-09-06 06:52
I want to long press to save the webpage image, but I don't know how to do.

**Comment by ydwan** [comment] 2019-10-28 06:31
I also need it.

**Comment by ydwan** [comment] 2019-10-28 06:40
@mtallenca  +1

**Comment by ydwan** [comment] 2019-10-28 11:06
I think the context menu view level is lower than WebView. 
When clicking "select all", it seems to penetrate the WebView at the bottom.

**Comment by joelbrostrom** [comment] 2019-11-27 15:04
Quote by @mklim in #38375 regarding this issue:

> glad to hear this specific issue is resolved for you. You can follow progress on the copy/paste issue at #24585. The current milestone for landing a fix is December 31, but like all milestones, that's a goal and may change at any point. Unfortunately there's also a decent chance that the fix for it will need to land in the flutter engine and then roll to the framework and the other channels, which will take a decent amount of time on its own as well. Sorry that you're blocked on it.

**Comment by sldboy** [comment] 2020-01-10 05:22
Is their any progress in this issue?

**Comment by Nico04** [comment] 2020-01-10 09:01
> 
> 
> Is their any progress in this issue?

You can use my idea as a workaround meanwhile :
https://github.com/flutter/flutter/issues/37927#issuecomment-539439488

**Comment by libo1223** [comment] 2020-03-02 06:46
> slib包来解析html / css并构建一个flutter的widget树的解决方案。到目前为止，结果



> I have a solution for this bug but it's a total hack. Flutter is capturing the touches and forwarding them to the webview. Unfortunately on Android, the selection dialog is a top level window not in the webview, so when the webview gets the tap, the selection dialog is dismissed. My current solution grabs the location of the selection dialog, then intercept touches when the selection dialog is visible and calls the appropriate menu handler when a tap should have been redirected to the selection dialog.
> 
> The solution we had no longer works in flutter 1.9+. There were some underlying changes with the implementation fo PlatformViews. We have pivoted to building a solution that is using the html and csslib packages to parse the html/css and build a flutter widget tree. So far results looks promising - but far from release ready.

i have the some question to reslove ,so Is it released now?

**Comment by libo1223** [comment] 2020-03-02 07:36
> > slib包来解析html / css并构建一个flutter的widget树的解决方案。到目前为止，结果
> 
> > I have a solution for this bug but it's a total hack. Flutter is capturing the touches and forwarding them to the webview. Unfortunately on Android, the selection dialog is a top level window not in the webview, so when the webview gets the tap, the selection dialog is dismissed. My current solution grabs the location of the selection dialog, then intercept touches when the selection dialog is visible and calls the appropriate menu handler when a tap should have been redirected to the selection dialog.
> > The solution we had no longer works in flutter 1.9+. There were some underlying changes with the implementation fo PlatformViews. We have pivoted to building a solution that is using the html and csslib packages to parse the html/css and build a flutter widget tree. So far results looks promising - but far from release ready.
> 
> i have the some question to reslove ,so Is it released now?
i have the same question to reslove ,so Is it released now?

**Comment by gabidusa** [comment] 2020-03-04 20:12
Hello,
Is there any progress on this issue?
Any roadmap for fixing it.
Thanks!

**Comment by deandreamatias** [comment] 2020-03-04 21:51
Please stop commenting on problems things like at:

> any update on this

The best option is to add this emoji :+1: in the initial comment.
To see a priority of each issue, we can see in which Milestone the issue is added. This issue belongs
to milestone March 2020

Thank

**Comment by yenole** [comment] 2020-03-14 09:30
内置实现文本选择对话框和解决输入框失去焦点隐藏键盘，等待稳定后提交Pull request，
大家有需要可以看看
https://github.com/yenole/plugins

**Comment by tvolkert** [comment] 2020-04-01 00:05
@bparrishMines this is one of four webview issues marked as critical.  How's your bandwidth for being able to look at these?

**Comment by dariosci** [comment] 2020-04-02 13:29
Hello! The same happens to me with the text boxes, when I have to fill one, the keyboard appears but the box does not respond to keystrokes.
but it happens to me with the apk app-arm64-v8a-release.apk. on a xiaomi mi 9t with android 10.
I have tested the apk app-armeabi-v7a-release.apk on an older device (a samsung j7) with android 8.1 and it works perfectly.

I hope you can help me. Cheers!

**Comment by bparrishMines** [comment] 2020-04-02 19:27
@tvolkert I've made some progress on this and will try to work on this again sometime this quarter.

**Comment by p30arena** [comment] 2020-04-28 08:23
Hi @bparrishMines 
Would you please explain your solution?
I'm bringing EditText and UITextfield to flutter, and having the same issue.

Should I wait for an engine update or should I show custom Flutter-Based Action Menu?

**Comment by coolan2013** [comment] 2020-04-29 07:59
> 内置实现文本选择对话框和解决输入框失去焦点隐藏键盘，等待稳定后提交Pull request，
> 大家有需要可以看看
> https://github.com/yenole/plugins

大侠问一下，稳定了么？这个问题的原因是什么？ios有这个问题么？

**Comment by yenole** [comment] 2020-04-29 08:12
> > 内置实现文本选择对话框和解决输入框失去焦点隐藏键盘，等待稳定后提交Pull request，
> > 大家有需要可以看看
> > https://github.com/yenole/plugins
> 
> 大侠问一下，稳定了么？这个问题的原因是什么？ios有这个问题么？

目前项目在使用中，暂时未发现其他问题，iOS没有这个问题。

**Comment by coolan2013** [comment] 2020-04-29 09:07
> > > 内置实现文本选择对话框和解决输入框失去焦点隐藏键盘，等待稳定后提交Pull request，
> > > 大家有需要可以看看
> > > https://github.com/yenole/plugins
> > 
> > 
> > 大侠问一下，稳定了么？这个问题的原因是什么？ios有这个问题么？
> 
> 目前项目在使用中，暂时未发现其他问题，iOS没有这个问题。

我用这个控件打开https://mil.huanqiu.com/article/3y1qV42IIkh，里面的视频无法播放，但这个视频在头条和qq移动浏览器中是可以播放的，这个控件可以正常播放哔哩哔哩网站中的视频。您知道什么原因么？

**Comment by coolan2013** [comment] 2020-04-29 09:34
> > > > 内置实现文本选择对话框和解决输入框失去焦点隐藏键盘，等待稳定后提交Pull request，
> > > > 大家有需要可以看看
> > > > https://github.com/yenole/plugins
> > > 
> > > 
> > > 大侠问一下，稳定了么？这个问题的原因是什么？ios有这个问题么？
> > 
> > 
> > 目前项目在使用中，暂时未发现其他问题，iOS没有这个问题。
> 
> 我用这个控件打开[https://mil.huanqiu.com/article/3y1qV42IIkh，里面的视频无法播放，但这个视频在头条和qq移动浏览器中是可以播放的，这个控件可以正常播放哔哩哔哩网站中的视频。您知道什么原因么？](https://mil.huanqiu.com/article/3y1qV42IIkh%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84%E8%A7%86%E9%A2%91%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE%EF%BC%8C%E4%BD%86%E8%BF%99%E4%B8%AA%E8%A7%86%E9%A2%91%E5%9C%A8%E5%A4%B4%E6%9D%A1%E5%92%8Cqq%E7%A7%BB%E5%8A%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%92%AD%E6%94%BE%E7%9A%84%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%8E%A7%E4%BB%B6%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%92%AD%E6%94%BE%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%BD%91%E7%AB%99%E4%B8%AD%E7%9A%84%E8%A7%86%E9%A2%91%E3%80%82%E6%82%A8%E7%9F%A5%E9%81%93%E4%BB%80%E4%B9%88%E5%8E%9F%E5%9B%A0%E4%B9%88%EF%BC%9F)

猜测可能是服务器根据终端app类型自动选择是否传输视频数据？

**Comment by heatonandy** [comment] 2020-05-22 19:34
@bparrishMines Hi Maurice, just wanted to see if you felt like this was on track for June.  I apologize for asking for a status update, but I would like to know if I can depend on this fix for some business timing decisions I need to make.  Thanks so much for your hard work, I know we all appreciate it!

**Comment by blasten** [comment] 2020-06-04 02:23
I have verified that hybrid composition on Android fixes this issue. However, more testing needs to be done before we decide if this plugin can be migrated to this mode.

We expect to release hybrid composition on Android next stable release.

@bparrishMines let's chat about your findings when you get chance.

**Comment by blasten** [comment] 2020-10-14 00:06
This has been fixed in Flutter 1.22/ WebView 1.0 - use hybrid composition in the Flutter WebView plugin.

https://github.com/flutter/plugins/tree/master/packages/webview_flutter#using-hybrid-composition

**Closed by blasten** 2020-10-14 00:06 UTC
Labels: P3, a: annoyance, a: platform-views, customer: crowd, customer: google, customer: product, customer: quill (g3), customer: raven, engine, p: first party, p: webview, p: webview-keyboard, platform-android, plugin, waiting for PR to land (fixed)
