### ISSUE TITLE
ElevatedButton inconsistency across mobile/web

### ISSUE THREAD

**Issue by aleripe** [flutter/flutter#84042] opened 2021-06-05 13:36 UTC
Hello,
I've found an inconsistency on ElevatedButton inconsistency across mobile/web. Web has less spacing/margin and buttons look smaller and crammed.

```
import 'package:flutter/material.dart';

const Color colorYouTube = Color(0xffcc191e);
const Color colorMedium = Color(0xff333333);
const Color colorFacebook = Color(0xff3b5998);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Elevated buttons',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Elevated buttons'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildButton(
            'YouTube',
            colorYouTube,
          ),
          _buildButton(
            'Medium',
            colorMedium,
          ),
          _buildButton(
            'Facebook',
            colorFacebook,
          ),
        ],
      ),
    );
  }

  Widget _buildButton(
    String title,
    Color color,
  ) {
    return ElevatedButton(
      child: Text(title),
      style: ElevatedButton.styleFrom(primary: color),
      onPressed: () {},
    );
  }
}
```

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Versione 10.0.19042.985], locale it-IT)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (9 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alessandro\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Alessandro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!
```

**Comment by bernaferrari** [comment] 2021-06-05 17:21
This is not a bug, it is a feature. Duplicate of https://github.com/flutter/flutter/issues/83045.

**Comment by aleripe** [comment] 2021-06-05 18:22
How can this a feature? 😅

**Comment by aleripe** [comment] 2021-06-06 06:55
How can an inconsistency be a feature? How are we supposed to deal with it to get the same result on all platforms?

**Comment by aleripe** [comment] 2021-06-06 15:25
I answer myself after a day of investigation and debugging. Just put this into `main.dart`'s theme:

```
elevatedButtonTheme: ElevatedButtonThemeData(
	style: ButtonStyle(
	  tapTargetSize: MaterialTapTargetSize.padded,
	  visualDensity: VisualDensity(horizontal: 0, vertical: 0),
	),
),
textButtonTheme: TextButtonThemeData(
	style: ButtonStyle(
	  tapTargetSize: MaterialTapTargetSize.padded,
	  visualDensity: VisualDensity(horizontal: 0, vertical: 0),
	),
),
```

**Comment by darshankawar** [comment] 2021-06-07 08:07
Thanks for digging in and finding solution. For tracking, please follow-up in original issue, https://github.com/flutter/flutter/issues/83045.

Closing this as duplicate.

**Closed by darshankawar** 2021-06-07 08:07 UTC
Labels: in triage
