### ISSUE TITLE
Android memory leaks until it is killed by the system

### ISSUE THREAD

**Issue by fly512** [flutter/flutter#31303] opened 2019-04-19 11:06 UTC
We tested the latest version, as well as beta version, and found that if any animation on the APP plus a picture, it would lead to a constant increase in memory. The more complex the UI, the faster the memory grows (Native memory).

The simplest version below, with only one picture and one animation

![企业微信截图_15556719181553](https://user-images.githubusercontent.com/16027300/56421664-2d0f1f80-62d6-11e9-839d-1b33817e3ed4.png)

When APP goes back to the background, Native memory decreases slightly. In the background, the memory will not change, but when it goes back to the front, Native memory will be higher than before.

```
[√] Flutter (Channel unknown, v1.5.2, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
    • Flutter version 1.5.2 at C:\tool\flutter
    • Framework revision efe744a360 (2 days ago), 2019-04-17 10:43:19 -0400
    • Engine revision fdd427241b
    • Dart version 2.2.1 (build 2.2.1-dev.4.2 8e73b3c006)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\xxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\xxx\AppData\Local\Android\sdk
    • Java binary at: C:\tool\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\tool\android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.1
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • KNT AL10 • 69DDU16511000544 • android-arm64 • Android 6.0 (API 23)
```

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() async {
	runApp(App());
}

class App extends StatefulWidget {
	App() {
		print("new App");
	}
	
	@override
	_AppState createState() => new _AppState();
	
}

class _AppState extends State<App> {
	@override
	void initState() {
		super.initState();
	}
	
	@override
	void dispose() {
		super.dispose();
	}
	
	@override
	Widget build(BuildContext context) {
		print("App Build");
		return new MaterialApp(
			title: "test",
			home: Boot()
		);
	}
}

class Boot extends StatefulWidget {
	Boot({Key key}) : super(key: key);
	
	@override
	BootState createState() => new BootState();
}

class BootState extends State<Boot> {
	@override
	void initState() {
		super.initState();
	}
	
	@override
	void dispose() {
		super.dispose();
	}
	
	@override
	Widget build(BuildContext context) {
		List<Widget> res = [];
		for(int i = 0; i < 200; i++){
			res.add(
				new Container(
					height: 20.0,
					decoration: new BoxDecoration(
						border: new Border(
							bottom: new BorderSide(
								color: Theme.of(context).dividerColor
							)
						)
					),
					child: new Text(
						i.toString()
					),
				)
			);
		}
		return new Scaffold(
			body: new Stack(
				children: <Widget>[
					new Positioned(
						child: new Image.network(
							"http://47.254.30.207/background.png",
							fit: BoxFit.cover,
						),
						left: 0.0,
						top: 0.0,
						width: MediaQuery.of(context).size.width,
						height: MediaQuery.of(context).size.height,
					),
					new Positioned(
						left: 0.0,
						top: 0.0,
						width: MediaQuery.of(context).size.width,
						height: MediaQuery.of(context).size.height,
						child: new Center(
							child: new CupertinoActivityIndicator(
								animating: true,
								radius: 50.0,
							),
						),
					)
				],
			),
		);
	}
}
```

**Comment by fly512** [comment] 2019-04-19 14:57
@mklim @kangwang1988

**Comment by mklim** [comment] 2019-04-19 18:17
Thanks for reporting the bug!

In debug mode I'm seeing memory climbing just from combining the loop/array with the animation even without any image.

So far I've been unable to reproduce any kind of memory climb at all in release mode though.

Just making sure, are you seeing this leak in both release mode and debug mode?

**Comment by fly512** [comment] 2019-04-20 03:03
@mklim We also found this problem in profile and release modes, as long as the time is long enough (the screen is not closed, less than the background, hours) memory will continue to grow, when the UI is very complex, memory growth is very fast.

**Comment by fly512** [comment] 2019-04-20 16:12
Profile Mode
A more complex UI was redone and ran for more than an hour (the screen was always on in the front desk).
You'll find that Native memory keeps going up.

![profile](https://user-images.githubusercontent.com/16027300/56459706-1fd35d00-63ca-11e9-90d2-5a3e65159746.png)

**Comment by fly512** [comment] 2019-04-20 16:16
This is the test code.
Two resource images are needed in the assets/images/directory, as shown in the annex.

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'dart:async';
import 'dart:math';

void main() async {
	runApp(App());
}

class App extends StatefulWidget {
	App() {
		print("new App");
	}
	
	@override
	_AppState createState() => new _AppState();
	
}

class _AppState extends State<App> {
	@override
	void initState() {
		super.initState();
	}
	
	@override
	void dispose() {
		super.dispose();
	}
	
	@override
	Widget build(BuildContext context) {
		print("App Build");
		return new MaterialApp(
			title: "test",
			home: Boot()
		);
	}
}

class Boot extends StatefulWidget {
	Boot({Key key}) : super(key: key);
	
	@override
	BootState createState() => new BootState();
}

class BootState extends State<Boot> {
	int _index = 0;
	@override
	void initState() {
		super.initState();
		new Timer.periodic(new Duration(seconds: 3), (Timer timer){
			this.setState((){
				this._index = (this._index + 1) % 8;
			});
		});
	}
	
	@override
	void dispose() {
		super.dispose();
	}
	
	@override
	Widget build(BuildContext context) {
		return new Scaffold(
			body: new Stack(
				children: <Widget>[
					new Positioned(
						child: new Image.asset(
							"assets/images/background.png",
							fit: BoxFit.cover,
						),
						left: 0.0,
						top: 0.0,
						width: MediaQuery.of(context).size.width,
						height: MediaQuery.of(context).size.height,
					),
					new Container(
						width: MediaQuery.of(context).size.width,
						child: new Column(
							children: <Widget>[
								new AppBar(
									automaticallyImplyLeading: false,
									leading: new BackButton(),
									title: new Text("test"),
									backgroundColor: Colors.transparent,
									elevation: 0.0,
								),
								new Padding(
									child: new Wrap(
										runSpacing: 15.0,
										children: List.generate(8, (int index){
											return new HeadIcon(
												isSpeaking : index == this._index
											);
										}),
									),
									padding: new EdgeInsets.only(
										top: 15.0,
										bottom: 15.0
									),
								),
								new Expanded(
									child: new MessageList(),
								)
							],
						),
					),
				],
			),
		);
	}
}

class MessageList extends StatefulWidget {
	MessageList({Key key}):super(key: key);
	MessageListState createState() => new MessageListState();
}

class MessageListState extends State<MessageList> {
	Timer _timer;
	List<int> _data = [];
	ScrollController _controller;
	Random _random = new Random();
	
	@override
  void initState() {
    super.initState();
    this._controller = new ScrollController(keepScrollOffset: true);
    this._controller.addListener(this._onScroll);
    this._timer = Timer.periodic(new Duration(milliseconds: 200), this._onTimer);
  }
  
  @override
  void dispose() {
		if(this._timer != null){
			this._timer.cancel();
			this._timer = null;
		}
		this._controller.removeListener(this._onScroll);
		this._controller.dispose();
    super.dispose();
  }
	
	_onTimer(Timer timer){
		this.setState((){
			this._data.add(this._random.nextInt(20));
			if(this._data.length > 200){
				this._data.removeRange(0, this._data.length - 200);
			}
		});
		//for test
		this._scrollEnd();
	}
	
	void _onScroll(){
	
	}
	
	void _scrollEnd(){
		if(!this._controller.hasClients) return;
		if(this._controller.position == null) return;
		if(this._controller.position.maxScrollExtent == null) return;
		if(this._controller.position.maxScrollExtent > this._controller.offset){
			this._scrollToEnd();
		}
	}
	
	void _scrollToEnd() {
		if(!this._controller.hasClients) return;
		this._controller.jumpTo(
			this._controller.position.maxScrollExtent
		);
	}
 
	@override
	Widget build(BuildContext context) {
    return new ListView.builder(
	    controller: this._controller,
	    itemCount: this._data.length,
	    itemBuilder: (BuildContext context, int index){
	    	return new Container(
			    height: 42.0 + this._data.elementAt(index),
			    padding: new EdgeInsets.only(
				    left: 15.0,
				    top: 6.0,
				    bottom: 6.0
			    ),
			    child: new Row(
				    children: <Widget>[
							new ClipRRect(
								borderRadius: new BorderRadius.all(
									new Radius.circular(15.0)
								),
								child: new Image.asset(
									"assets/images/head.jpg",
									width: 30.0,
									height: 30.0,
								),
							),
					    new Padding(
						    padding: new EdgeInsets.only(
							    left: 12.0
						    ),
						    child: new Text(
							    "number ${this._data.elementAt(index)} => data len = ${this._data.length} => max len = 200",
							    style: new TextStyle(
								    fontSize: 12.0
							    ),
						    ),
					    )
				    ],
			    ),
		    );
    });
  }
}

class HeadIcon extends StatelessWidget {
	final bool isSpeaking;
	HeadIcon({Key key, this.isSpeaking = false}):super(key: key);
	
	@override
	Widget build(BuildContext context) {
    return new Container(
	    width: MediaQuery.of(context).size.width / 4,
	    alignment: Alignment.topCenter,
	    child: new Stack(
		    overflow: Overflow.visible,
		    children: <Widget>[
		    	new ClipRRect(
				    borderRadius: new BorderRadius.all(
					    new Radius.circular(33.0)
				    ),
				    child: new Image.asset(
					    "assets/images/head.jpg",
					    width: 66.0,
					    height: 66.0,
				    ),
			    ),
			    new SoundFastWare(
				    isSpeaking: this.isSpeaking,
			    )
		    ],
	    ),
    );
  }
}

class SoundFastWare extends StatefulWidget {
	final bool isSpeaking;
	SoundFastWare({Key key, this.isSpeaking}):super(key: key);
	
	@override
	_SoundFastWareState createState() => new _SoundFastWareState();
}

class _SoundFastWareState extends State<SoundFastWare> with SingleTickerProviderStateMixin {
	AnimationController _controller;
	Animation _opacity;
	Animation _scale;
	
	@override
	void initState() {
		super.initState();
		this._controller = new AnimationController(
			duration: const Duration(milliseconds: 800),
			vsync: this,
		);
		this._opacity = Tween(
			begin: 1.0,
			end: 0.0,
		).animate(
			CurvedAnimation(
				parent: this._controller,
				curve: Interval(
					0.0,
					1.0,
					curve: Curves.linear,
				),
			),
		);
		this._scale = Tween(
			begin: 1.0,
			end: 1.25,
		).animate(
			CurvedAnimation(
				parent: this._controller,
				curve: Interval(
					0.0,
					1.0,
					curve: Curves.linear,
				),
			),
		);
		this._scale.addListener(this._onChanged);
		if(this.widget.isSpeaking){
			this._controller.forward();
		}
	}
	
	@override
	void didUpdateWidget(SoundFastWare old){
		super.didUpdateWidget(old);
		if(old.isSpeaking != this.widget.isSpeaking){
			if(this.widget.isSpeaking){
				this._controller.forward(from: 0.0);
			}
		}
	}
	
	@override
	void dispose() {
		this._scale.removeListener(this._onChanged);
		this._controller.dispose();
		super.dispose();
	}
	
	_onChanged() async {
		setState(() {
		
		});
		if(this._controller.status == AnimationStatus.completed && this.widget.isSpeaking){
			this._controller.forward(from: 0.0);
		}
	}
	
	Widget _buildAni(BuildContext context, Widget child) {
		double width = 66.0;
		double translate = 0.0 - ((this._scale.value - 1.0) * width / 2 / this._scale.value);
		return new Container(
			width: width,
			height: width,
			decoration: new BoxDecoration(
				border: new Border.all(
					color: this.widget.isSpeaking ?
					Colors.amberAccent.withOpacity(this._opacity.value) :
					Colors.transparent,
					width: 3.0,
					style: BorderStyle.solid,
				),
				borderRadius: new BorderRadius.circular(width / 2),
			),
			transform: Matrix4.identity()
				..scale(this._scale.value, this._scale.value)
				..translate(translate, translate),
		);
	}
	
	@override
	Widget build(BuildContext context) {
		double width = 66.0;
		return new Positioned(
			left: 0.0,
			top: 0.0,
			width: width,
			height: width,
			child: new IgnorePointer(
				child: new AnimatedBuilder(
					animation: this._controller,
					builder: _buildAni
				),
			),
		);
	}
}

```

![background](https://user-images.githubusercontent.com/16027300/56459736-98d2b480-63ca-11e9-92f4-4443d4877a9e.png)
![head](https://user-images.githubusercontent.com/16027300/56459737-996b4b00-63ca-11e9-834f-bfd8894e52ed.jpg)

**Comment by fly512** [comment] 2019-04-22 13:05
@mklim Very anxious, online project

**Comment by mklim** [comment] 2019-04-22 16:46
Got it, thanks for the clarification. And it's not a problem, thanks for the extra info. Looking into it again.

**Comment by mklim** [comment] 2019-04-22 17:56
I'm seeing a leak with the latest sample case. No OOM crash yet, but I can see it climbing just from letting it run for a couple minutes. /cc @jason-simmons

**Comment by mklim** [comment] 2019-04-22 21:01
I think `ImageCache` is likely related here. I'm not seeing the same linear climb with `maximumSize = 0`.

**Comment by jason-simmons** [comment] 2019-04-22 22:40
I noticed that a lot of `EngineLayer` objects are not being garbage collected promptly when running this app.  Increasing `EngineLayer::GetAllocationSize` to something much higher seems to help.

**Comment by fly512** [comment] 2019-04-23 02:48
Thank you very much. We will adjust Engine Layer:: GetAllocation Size and then test it.

**Comment by fly512** [comment] 2019-04-24 02:48
When we set Layer:: GetAllocation to 200,000, we found that there were still problems on some mobile phones.
Setting Layer:: GetAllocation to 1 million works well

**Comment by fly512** [comment] 2019-04-24 15:43
We found that when we set Engine Layer:: GetAllocation to a large value, the performance of different mobile phones varies greatly. One can maintain 300 MB of memory in use, but some will maintain around 1G.

**Comment by dnfield** [comment] 2019-04-25 05:55
Is there some other way we can clue the VM to GC these objects without spoofing the size?

Is this just a Dart VM bug on Android that it's not collecting something with no references left to it?  Or are we retaining a refernece somewhere?

**Comment by fly512** [comment] 2019-04-25 11:41
@jason-simmons @mklim @dnfield 

We tested the release version again today, and we found that memory leaks still exist, memory will continue to rise, will not stop, Profile mode is much better.

**Comment by dnfield** [comment] 2019-04-25 17:20
Just talked with @jason-simmons a bit more about this.

He's seeing that this app just never goes idle, so the GC doesn't get a chance to collect these items. But making them look bigger forces GCs too often in apps that don't need it, which slows some other key performance metrics we can't afford.

A few thoughs on this:

1. @mraleph - is there some way the Garbage Collector can be smarter about this?  Is there a deadline we can give it that says "collect this stuff even if we're saying we're not idle after this much time"?
2. It may make sense to pool `EngineLayers` instead of collecting them.  I'm not sure about the model there, @liyuqian probably knows more.  The idea would be that instead of creating a new `EngineLayer` for each frame, we only create them if the pool has been exhausted.  This should keep our memory usage more constent and limit GC churn during animations.
3. I don't like this idea, but it may make sense to give users an option to "try to force" a GC. 

I don't like the third option because .NET has it and it almost never works the way you think it will.  It can only ever be a suggestion to the GC, it's really hard to test or predict, and the cases where a user actually knows when to do a GC are very, very, very rare.

/cc @Hixie

**Comment by dnfield** [comment] 2019-04-25 17:21
(As far as whether this is a retain cycle, I'm pretty sure it's not - Jason says that forcing a GC fixes it, which shouldn't be the case if it was actually a retain cycle)

**Comment by zhileichen** [comment] 2019-04-26 03:49
@dnfield Thanks for the clarification and ideas. It appears the first two options need some time to resolve and test, since our app has already been delivered to lots of users, it's urgent for us to deliver a hotfix, so the third option might be a solution for us right now.   Would you please share some more on how to force a GC manually? We have the ability to re-compile the engine.
Thanks a lot.

**Comment by liyuqian** [comment] 2019-04-26 05:44
1. For the really "quick" fix, modify the engine to always return a null `EngineLayer`. That way, you won't have any memory cost by discarding the retained rendering performance optimization. If you have any questions, I'll implement the hack and post the git diff here.

2. In the long run, I'll raise the priority of https://github.com/flutter/flutter/issues/31498 and hopefully fix it in a week or two.

**Comment by dnfield** [comment] 2019-04-26 06:01
Looking at your code, there are a few optimiztions you might try - locally they get better memory performance for me and probably better frame builds.  See https://gist.github.com/dnfield/b6e5b4ada9f79f98243628e361567f00

Things I did:

- Try to avoid building the whole Scaffold on every tick.
- Try to avoid creating more animations than needed (e.g. don't create those `SoundFastWare` animations if they won't draw anything).
- Try to avoid creating more `ClipRect`s than necessary.  clipping is expensive - Try to only create the ones you need and reuse them in the tree; if you have multiple images in your actuall application and can't do it the way I did it in the gist, maybe you can use some GlobalKeys based on the avatar you want to show so that the framework will reuse them a bit more.
- Avoid repeatedly calling `List.removeRange`.  It's not got great performance characteristics.  You could probably do better than a Queue here - it has O(1) add and remove, but O(N) lookup.  With a better circular list/queue class, you could probably get O(1) lookup and O(1) add and remove (e.g. a list of 200 items with a pointer to the head and tail that just keeps cycling through the buffer and does quick addition to figure out how to look up an index).

**Comment by dnfield** [comment] 2019-04-26 06:03
In other words, I would first try to tune the performance of your app so you don't have to resort to things like trying to force more garbage collections. I suspect your framerates are already on the slower side - anything you do to make GCs happen more frequently without changing that will only make your app slower :(

**Comment by zhileichen** [comment] 2019-04-26 06:05
Thanks for your reply.  
I'll try to modify the engine by your way, but it would be great if you could post the git diff. :)

**Comment by zhileichen** [comment] 2019-04-26 08:49
@liyuqian Thanks for your reply. 
We will try to modify the engine by the your way. But it would be great if you could post the hacked code. :)

**Comment by zhileichen** [comment] 2019-04-26 08:50
@dnfield Very appreciated for your detail explanation, advises and the gist.
Since the demo code we provided is not part of our product app, we made it to demonstrate the memory increasement issue deliberately, the optimization suggestions are helpful but still cannot resolve the memory issue in our product app.So we would try liyuqian's hack way. :)
Thank you.

**Comment by liyuqian** [comment] 2019-04-28 00:15
@zhileichen Here's the diff that I just tested:
```
diff --git a/lib/ui/painting/engine_layer.h b/lib/ui/painting/engine_layer.h
index 1dc565c51..5c008e7dd 100644
--- a/lib/ui/painting/engine_layer.h
+++ b/lib/ui/painting/engine_layer.h
@@ -27,7 +27,8 @@ class EngineLayer : public RefCountedDartWrappable<EngineLayer> {
 
   static fml::RefPtr<EngineLayer> MakeRetained(
       std::shared_ptr<flutter::ContainerLayer> layer) {
-    return fml::MakeRefCounted<EngineLayer>(layer);
+    return nullptr;
+    // return fml::MakeRefCounted<EngineLayer>(layer);
   }
```

I'm sorry that I didn't have a chance to test and post this on Friday because there was a TODAY issue (the highest priority issue of Flutter) on that day.

Please let me know if this alleviates your memory usage or not. If not, maybe something other than `EngineLayer` is causing the issue.

**Comment by zhileichen** [comment] 2019-04-28 03:35
@liyuqian Thanks for your code. We have modified the engine as same as your code last friday, but it did not alleviate the memory usage, the memory still increase linearly. It turns out it's not the EngineLayer causing the issue? 
And we found that, increasing EngineLayer::GetAllocationSize to **10,000,000**  works well in the Profile mode, but not works in the Release mode.  When set EngineLayer::GetAllocationSize to **10,000,000** and compile the engine in Profile mode, the memory usage of our app would increased linearly at first, after a period  the usage would stay smooth and steady in a level. 
![2](https://user-images.githubusercontent.com/4406891/56858249-9dd6cb80-69a9-11e9-8f15-5c521f830d96.png)

**Comment by zhileichen** [comment] 2019-04-28 03:38
Are any optimizations turned on to disable the modification of EngineLayer::GetAllocationSize in the  Release mode ?

**Comment by mraleph** [comment] 2019-04-28 10:04
@dnfield I don't think there is any amazing GC based solution here - it a fairly classical issue when GC managed heap retains native resources of unknown size. If you have an object which is managed by GC then you need to periodically trigger full GC to collect it. For GC to trigger VM needs to understand that heap is too large. However if full GC triggers too often - you get performance degradation. 

/cc @rmacnak-google

**Comment by liyuqian** [comment] 2019-04-28 17:28
@zhileichen I think huge `EngineLayer::GetAllocationSize` in the profile mode may be triggering full GC to collect memory in other places. It seems that doesn't happen in release mode so you may need to find another way. @mraleph and @rmacnak-google from the Dart team may have better suggestions to that end.

**Comment by fly512** [comment] 2019-05-21 02:25
@jason-simmons @mklim @dnfield
I'm sorry to interrupt. Is there any progress to solve this problem?

**Comment by fly512** [comment] 2019-05-31 14:59
@jason-simmons @mklim @dnfield
I'm sorry to interrupt. Is there any progress to solve this problem?

**Comment by liyuqian** [comment] 2019-11-25 23:18
Bringing this back to our attentions. This is already a "customer: crowd" issue, and I just heard from @cbracken that Fuchsia is also experiencing this kind of memory issue (the memory usage keeps going up). So this issue is becoming more and more important.

Here's one potential strategy to fix this:
1. Confirm the reproduction of this issue on master Flutter today. @mklim : since you've tried reproduced it earlier, can you please confirm if it's still reproducible today?
2. Once reproduced, turn the reproduction into a device lab memory test so everyone can reproduce this issue with a minimum effort, and we can continuously track our working progress. Either I, @dnfield , or @jason-simmons can take this once the reproduction is confirmed.
3. Collaborate with the DevTools (CC @cobblest @terrylucas ) and Dart teams to figure out exactly where the memory goes. The engine may need to provide better APIs for that.

**Comment by dnfield** [comment] 2019-11-26 00:38
Since this bug was opened, we've reduced the size of the Skia resource cache significantly.  Is it significantly increasing beyond that?  

We should take a look at where the allocated memory is going.

**Comment by liyuqian** [comment] 2019-11-26 01:25
@dnfield : if it never increases beyond that point, which means that this issue is no longer reproducible, then we can close this issue without further work :D That's the best case and I do hope Michael would give us that good news. And if that's indeed the case, we'll probably just file a separate issue on Fuchsia only as they may not set the resource cache properly.

**Comment by mklim** [comment] 2019-11-26 22:16
I'm not seeing an obvious leak given the earlier repro case from [issuecomment-485139640](https://github.com/flutter/flutter/issues/31303#issuecomment-485139640). I am seeing an initial spike in memory, but the usage seems to drop back down to around 9400KB on my test device given enough time. [Test data is in this spreadsheet.](https://docs.google.com/spreadsheets/d/124KShuIXL_w0No8T7qacqzjGe4nNkg3kZjEHBKeyzG4/preview)

Given that I think we should close this and re-open new issues about leaks in the future with specific reproduction cases. Memory leaks can come from basically anywhere, so it's likely whatever was root causing this initially has been fixed like @dnfield suggested and the leaks @cbracken is reporting on Fuchsia are from a different path.

**Closed by mklim** 2019-11-26 22:16 UTC
Labels: customer: crowd, severe: crash, severe: performance

**Comment by dnfield** [comment] 2019-11-26 22:30
Thanks for the detailed analysis @mklim .  A quick look at your data suggests to me that https://github.com/flutter/engine/pull/10434 probably helped this case significantly.  The graphics cache is not getting larger than 50mb (assuming I have the scale right) in your sheet, whereas previously it would have been allowed to grow to about 10x that.
