### ISSUE TITLE
Error (Xcode): /usr/local/Caskroom/flutter/3.10.5

### ISSUE THREAD

**Issue by MTEV** [flutter/flutter#130207] opened 2023-07-08 18:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

weh run. 
flutter build ios. or.  run my ios. project. i have this issue 

### Expected results

Got dependencies!
Building my.body.fitteness for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: PK582D5UEM
Running pod install...                                             76.0s
Running Xcode build...                                                  
Xcode build done.                                           1279.8s
Failed to build iOS app
Error (Xcode): /usr/local/Caskroom/flutter/3.10.5/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/test_api-0.6.1/lib/expect.dart': No such file or
directory

Encountered error while building for device.
 

### Actual results

Failed to build iOS app

any help please 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)

**Comment by stuartmorgan** [comment] 2023-07-08 19:50
Closing as a duplicate of https://github.com/flutter/flutter/issues/129883

**Closed by stuartmorgan** 2023-07-08 19:50 UTC
