### ISSUE TITLE
[Textfield] assertion was thrown during paint(): [Rect / RRect] argument contained a NaN value.

### ISSUE THREAD

**Issue by jesper372** [flutter/flutter#70610] opened 2020-11-16 13:39 UTC
Creating this issue as requested in #66457

**Steps to Reproduce**

1. Run the the code below in the "stable" channel in an iOS or Android emulator (this code is taken straight out of #66457, but with an extra page added to the PageView):

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Login(),
    );
  }
}

class Login extends StatefulWidget {
  const Login({Key key}) : super(key: key);

  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> with TickerProviderStateMixin {
  FocusNode emailFocusNode;
  FocusNode passwordFocusNode;
  TextEditingController emailTextController;
  TextEditingController passwordTextController;
  final PageController pageController = PageController();

  Duration duration = Duration(milliseconds: 200);
  Curve tonalCurve = Curves.easeIn;

  @override
  void initState() {
    super.initState();

    emailTextController = TextEditingController();
    emailFocusNode = FocusNode()..requestFocus();
    passwordTextController = TextEditingController();
    passwordFocusNode = FocusNode();
  }

  @override
  void dispose() {
    emailTextController.dispose();
    emailFocusNode.dispose();
    passwordTextController.dispose();
    passwordFocusNode.dispose();
    super.dispose();
  }

  Widget fieldLabel({String label}) {
    return Container(
      width: MediaQuery.of(context).size.width,
      padding: const EdgeInsets.only(
        top: 15,
        left: 24,
        right: 24,
      ),
      child: Text(
        label,
        textAlign: TextAlign.center,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;

    final emailScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'email',
            ),
            TextField(
              controller: emailTextController,
              keyboardType: TextInputType.emailAddress,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    final passwordScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'password',
            ),
            TextField(
              obscureText: true,
              controller: passwordTextController,
              textInputAction: TextInputAction.go,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    final finalScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            Text("Done"),
          ],
        ),
      ),
    );

    return Container(
      child: PageView(
        controller: pageController,
        children: [
          emailScreen,
          passwordScreen,
          finalScreen,
        ],
      ),
    );
  }
}
```
</details>

2. Simply swipe from the first page to the second, and then to the third. If an exception hasn't already been thrown, just keep swiping between the pages, and one occurs eventually. This happens regardless of whether any text has been entered into the TextField widgets on the first and second pages.

<details>
  <summary>Logs</summary>

Here's the stack trace for iOS:
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///Users/jesper/github_issue/lib/main.dart:105:13
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2042:14)
#5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
#6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#a670f relayoutBoundary=up16
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
...  size: Size(375.0, 19.0)
...  cursorColor: Color(0x362196f3)
...  showCursor: ValueNotifier<bool>#ac0d7(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 2, extentOffset: 2, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#5e105(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#fe31e, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "•g"
RenderObject: RenderEditable#a670f relayoutBoundary=up16
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
  size: Size(375.0, 19.0)
  cursorColor: Color(0x362196f3)
  showCursor: ValueNotifier<bool>#ac0d7(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 2, extentOffset: 2, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#5e105(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#fe31e, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "•g"
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Here's the stack trace for Android:
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
Rect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 31: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///Users/jesper/github_issue/lib/main.dart:86:13
When the exception was thrown, this was the stack: 
#2      _rectIsValid (dart:ui/painting.dart:31:10)
#3      Canvas.drawRect (dart:ui/painting.dart:3727:12)
#4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2039:14)
#5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
#6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#0d8a9 relayoutBoundary=up19
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...  size: Size(411.4, 19.0)
...  cursorColor: Color(0xff4285f4)
...  showCursor: ValueNotifier<bool>#02564(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 9, extentOffset: 9, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#75cab(offset: 0.0, range: 0.0..0.0, viewport: 411.4, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e38c2, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackMountainView subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "dsfsdffgh"
RenderObject: RenderEditable#0d8a9 relayoutBoundary=up19
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
  size: Size(411.4, 19.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#02564(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 9, extentOffset: 9, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#75cab(offset: 0.0, range: 0.0..0.0, viewport: 411.4, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e38c2, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackMountainView subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "dsfsdffgh"
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Output for "flutter analyze":

```
Analyzing github_issue...                                               
No issues found! (ran in 1.8s)
```
Output for "flutter doctor -v" (note that after upgrading to Android Studio 4.1, flutter doctor reports that the Flutter and Dart plugins aren't installed, even though they are; I guess this is the issue reported by many in https://github.com/flutter/flutter-intellij/issues/4523).

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.3 at /Users/jesper/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jesper/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5025f
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 4ADCA001-8F3F-496A-9C5A-1650E2DC2A37 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
```
</details>

**Comment by pedromassangocode** [comment] 2020-11-16 14:37
Reproducible on latest stable but this does **NOT** reproduce on latest master channel.
Adding regression label since this was already fixed before by https://github.com/flutter/flutter/pull/66845.

Can't test this on `beta` channel right now.

Cc @LongCatIsLooong 

<details><summary>Logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           71.8s
Waiting for iPhone 12 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:56324/XMJFl3p4xbA=/ws
Syncing files to device iPhone 12 Pro Max...

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:86:13
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2042:14)
#5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
#6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#58d4f relayoutBoundary=up16
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=428.0, 0.0<=h<=Infinity)
...  size: Size(428.0, 19.0)
...  cursorColor: Color(0xff2196f3)
...  showCursor: ValueNotifier<bool>#6be41(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#8cc70(offset: 0.0, range: 0.0..0.0, viewport: 428.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#3e649, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#58d4f relayoutBoundary=up16
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=428.0, 0.0<=h<=Infinity)
  size: Size(428.0, 19.0)
  cursorColor: Color(0xff2196f3)
  showCursor: ValueNotifier<bool>#6be41(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#8cc70(offset: 0.0, range: 0.0..0.0, viewport: 428.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#3e649, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by LongCatIsLooong** [comment] 2020-11-16 17:29
From the stacktrace it's the same problem as #66457. Looks like #66845 is not in stable yet (its first tag is 1.23.0-13.0.pre).

**Comment by jesper372** [comment] 2020-11-16 19:00
@LongCatIsLooong 
Is there any way of knowing when #66845 will be in stable?

**Comment by LongCatIsLooong** [comment] 2020-11-16 19:20
@jesper372 you can see the tags that contain the commit following the instructions in https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F. So I'd expect this commit will be in 1.23 (unless it's reverted in the future).

**Comment by TahaTesser** [comment] 2020-11-18 14:55
duplicate of https://github.com/flutter/flutter/issues/70096

**Comment by TahaTesser** [comment] 2020-11-18 14:57
I think this is a duplicate of https://github.com/flutter/flutter/issues/70096#issuecomment-724141999

CC @LongCatIsLooong

**Closed** 2020-11-18 15:10 UTC
Labels: a: text input, f: material design, found in release: 1.22, framework, has reproducible steps, platform-ios, severe: crash, severe: regression
