### ISSUE TITLE
Last TabBarView Child Doesn't Render Properly When Browser Window Is Resized

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter#60374] opened 2020-06-26 17:51 UTC
## Steps to Reproduce

1. Run `flutter create tabview_bug`.
2. Update the files as follows: ... 
* Replace all of the code in main.dart with the code from the Flutter cookbook example for "Work with tabs" https://flutter.dev/docs/cookbook/design/tabs so the Flutter app is now the interactive example tabs app.

* (Optional) To make the bug behavior more noticeable, wrap the three TabBarView child Icon widgets with Containers, and assign different colors. Note: this has nothing to do with the bug. It just helps visualize the bug's behavior easier.

Replace lines 26 - 28:
```
   Icon(Icons.directions_car)),
   Icon(Icons.directions_transit)),
   Icon(Icons.directions_bike)),
```
With:
```
   Container(color: Colors.amberAccent, child: Icon(Icons.directions_car)),
   Container(color: Colors.greenAccent, child: Icon(Icons.directions_transit)),
   Container(color: Colors.blueAccent, child: Icon(Icons.directions_bike)),
```

3. Run the Flutter app and select the "bicycle" tab then resize the browser window to make the window larger by dragging the left edge of the window. 

**Expected results:** 
The content of the tab view should render with the widgets contained within the view area of the tab view.

**Actual results:** 
The content of the tab view moves to the left as the size of the browser window increases in size to the left. I've tested this behavior by varying the number of TabBarView children and the bug behavior is always on the nth child, children 1 through n-1 display correctly. Swiping the content area or changing the current tab corrects the problem. Resizing the browser window to a small size does not exhibit the bug behavior.

#### NOTE
I was able to reproduce this bug on all Flutter channels, master, dev, and beta, on June 25, 2020.

<details>
  <summary>Logs</summary>

```
Output from `flutter run --verbose` doesn't have useful information associated with this bug.
```

```
Analyzing tabview_bug...
No issues found! (ran in 4.8s)
```

```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.2.pre at /Users/michaeljordan/Development/flutter
    • Framework revision 9b9b543d92 (4 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/michaeljordan/Library/Android/sdk
    • Platform android-28, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-06-29 11:16
<details> 
<summary>Code Sample</summary> 

```  import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Container(
                  color: Colors.amberAccent, child: Icon(Icons.directions_car)),
              Container(
                  color: Colors.greenAccent,
                  child: Icon(Icons.directions_transit)),
              Container(
                  color: Colors.blueAccent, child: Icon(Icons.directions_bike)),
            ],
          ),
        ),
      ),
    );
  }
}


``` 

</details>     <details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (6 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by yjbanov** [comment] 2020-07-09 22:16
Does this happen in Flutter for desktop? Curious if this is a web issue or general framework issue?

**Comment by mjordan56** [comment] 2020-07-10 03:46
Hi Yegor,

I don't know if this issue happens on Flutter desktop as well, I only
tested on Flutter web. This isn't an issue on Flutter mobile as you can't
resize the mobile device the way you can resize a browser window. My
gut-level suspicion is that this is a general framework issue that wasn't
exposed on mobile because of the inability to enlarge the view. I don't
have any reason for my belief beyond intuition.

Michael

**Comment by TahaTesser** [comment] 2020-07-10 10:13
I've assigned `a:desktop` since we can resize window of the browser on desktop only by dragging)

**Comment by rydmike** [comment] 2020-08-12 00:23
As far as I can see the fix https://github.com/flutter/flutter/pull/63146 that just landed on master and fixes https://github.com/flutter/flutter/issues/60288 and https://github.com/flutter/flutter/issues/61156 also fixes this issue as it is effectively a duplicate of them both. This issue can imo be closed.

**Comment by markusaksli-nc** [comment] 2020-08-12 06:36
@rydmike Thanks for reminding me. It was better to wait for confirmation here but I'm going to close this as no longer reproducible on the latest master `1.21.0-8.0.pre.176`.

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.176, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.176 at C:\Development\flutter_master
    • Framework revision d9637ed784 (3 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

I did notice some strange behavior when resizing the browser window but it's not related to this issue.

**Closed by markusaksli-nc** 2020-08-12 06:36 UTC
Labels: a: desktop, f: material design, found in release: 1.20, found in release: 1.21, framework, has reproducible steps

**Comment by mjordan56** [comment] 2020-08-12 14:49
@rydmike, @markusaksli-nc  I can confirm the bug I reported is resolved. I tested my Flutter web app against master 1.21.0-8.0.pre.177 and the content of the last TabBarView child is now rendering as expected when the browser window is resized. I'm good with closing this issue. Thanks!

**Comment by rydmike** [comment] 2020-08-15 14:03
The fix (https://github.com/flutter/flutter/pull/63146) that solved this issue has been reverted since it was failing some tests.

This issue report is however a duplicate of the older report https://github.com/flutter/flutter/issues/60288, so I recommend we keep this report closed and track future progress only via https://github.com/flutter/flutter/issues/60288 that has been reopened.
