### ISSUE TITLE
Flutter DefaultTabControlle and NestedScrollView scroll issue

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#57071] opened 2020-05-13 02:53 UTC
i have  "DefaultTabControlle" that content   "NestedScrollView" and "TabBarView",every tab view content a "List builder" ,when i scroll inside one of list builder (inside tabs) , all other tabs is sync the scroll position;
here is an example code :
```dart
const _tabs = [
  'Apple',
  'Banana',
  'Cherry',
];

const String _appBarTitle = 'Fruits';

class StickyTabsPage extends StatelessWidget {
  const StickyTabsPage();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(_appBarTitle), elevation: 0.0),
      body: DefaultTabController(
        length: _tabs.length, // This is the number of tabs.
        child: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverList(
                delegate: SliverChildListDelegate(
                  [
                    Container(
                      color: Colors.grey,
                      height: 220.0,
                      child: Center(
                        child: const Text(
                          'Header',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 24.0,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              SliverPersistentHeader(
                pinned: true,
                delegate: _StickyTabBarDelegate(
                  TabBar(
                    isScrollable: true,
                    tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            children: _tabs.map((String name) {
              return SafeArea(
                child: ListView.builder(
                  itemCount: 30,
                  itemBuilder: (context, index) {
                    return ListTile(
                      title: Text('Item $index'),
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

![issue](https://user-images.githubusercontent.com/2295872/81797231-15d64c00-9541-11ea-8ca5-7a8644e2d53d.gif)

flutter doctor -v

```console
[✓] Flutter (Channel dev, v1.14.5, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.14.5 at /Users/xxx/Library/flutter
    • Framework revision 92cbaa3efe (4 months ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)
```

**Comment by iapicca** [comment] 2020-05-13 09:44
Hi @lyf571321556 
the issue does reproduce with this [code](https://dartpad.dev/780826bfe3196c473813a9fad711e4cd) and the latest master
```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.22, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.19.0-2.0.pre.22 at /Users/nevercode/development/flutter_master
    • Framework revision 2f993d70c1 (13 hours ago), 2020-05-12 13:44:02 -0700
    • Engine revision 156970a248
    • Dart version 2.9.0 (build 2.9.0-8.0.dev 4e520824f5)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```
thank you

**Comment by iapicca** [comment] 2020-05-13 10:40
Hi again @lyf571321556 
I just realised that this issue is a duplicate of https://github.com/flutter/flutter/issues/36419
I'm closing the current one.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-13 10:40 UTC
Labels: f: scrolling, found in release: 1.19, framework, has reproducible steps
