### ISSUE TITLE
Windows: Provide a way to request redraw

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#75319] opened 2021-02-03 11:19 UTC
Currently when creating hidden window and showing it later the content does not get repainted automatically (unless something else triggers the repaint). It would be helpful if there was a way from embedder to tell the flutter HWND to repaint itself. 

It could be either custom message (i.e. WM_FLUTTER_REQUEST_REDRAW = WM_USER) or parent could simply forward its WM_SHOWWINDOW to flutter HWND and flutter would trigger redraw on WM_SHOWWINDOW.

**Comment by stuartmorgan** [comment] 2021-02-03 15:19
Duplicate of https://github.com/flutter/flutter/issues/75319

**Comment by stuartmorgan** [comment] 2021-02-03 15:19
Er, https://github.com/flutter/flutter/issues/69716

**Comment by stuartmorgan** [comment] 2021-02-03 15:21
Oh, looking at the patch this is at a slightly different level. Sorry for the noise.

**Comment by knopp** [comment] 2021-02-03 15:23
Right. I think https://github.com/flutter/flutter/issues/69716 would address the part where this patch calls `SendWindowMetrics` to trigger the redraw, which seems bit wonky.

**Comment by cbracken** [comment] 2021-02-05 18:17
Closed by flutter/engine#24186Closed by flutter/engine#24186.

**Closed by cbracken** 2021-02-05 18:17 UTC
Labels: a: desktop, engine, passed first triage, platform-windows, severe: new feature
