### ISSUE TITLE
Hitting enter can cause a flutter app to crash on fuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#13046] opened 2017-11-16 17:55 UTC
## Steps to Reproduce
1. build and boot up a recent build. 
2. Log in as guest. 
3. Type 'das'.
4. Hit Enter to launch the dashboard suggestion, Boom.

## Logs
```
[00156.757] 86878.86924> [INFO:suggestion_engine_impl.cc(442)] Requesting focus for story_id 2f1e08804b04b32676b01341f693eded
[00156.767] 85028.85051> DEBUG ASSERT FAILED at (../../zircon/system/ulib/async/auto_wait.cpp:36): status == ZX_OK
[00156.767] 85028.85051> status=-25
[00156.767] 01189.01252> <== fatal exception: process flutter:armadillo_user_... (+1)[85028] thread ui[85051]
[00156.767] 01189.01252> <== undefined instruction, PC at 0x78deb3a93c20
[00156.767] 01189.01252> CS: 0 RIP: 0x78deb3a93c20 EFL: 0x10202 CR2: 0
[00156.767] 01189.01252> RAX: 0x65 RBX: 0x101c40538a80 RCX: 0 RDX: 0x78deb3b5328c
[00156.767] 01189.01252> RSI: 0x5773041175bd RDI: 0x78deb3b53200 RBP: 0x2afa541eb4e0 RSP: 0x2afa541eb4c8
[00156.767] 01189.01252> R8: 0x1 R9: 0 R10: 0x65 R11: 0x246
[00156.767] 01189.01252> R12: 0x101c40538a00 R13: 0x39c536b3ffb0 R14: 0x39c536b400d8 R15: 0x101c40538b18
[00156.767] 01189.01252> errc: 0
[00156.767] 01189.01252> bottom of user stack:
[00156.767] 01189.01252> 0x00002afa541eb4c8: 052aac04 00005773 00000000 00000000 |..*.sW..........|
[00156.768] 01189.01252> 0x00002afa541eb4d8: 40538a80 0000101c 541eb500 00002afa |..S@.......T.*..|
[00156.768] 01189.01252> 0x00002afa541eb4e8: 052aab9e 00005773 00000000 00000000 |..*.sW..........|
[00156.768] 01189.01252> 0x00002afa541eb4f8: 40538a30 0000101c 541eb520 00002afa |0.S@.... ..T.*..|
[00156.768] 01189.01252> 0x00002afa541eb508: 056549ab 00005773 000000a6 00000000 |.Ie.sW..........|
[00156.768] 01189.01252> 0x00002afa541eb518: 40538b18 0000101c 541eb580 00002afa |..S@.......T.*..|
[00156.768] 01189.01252> 0x00002afa541eb528: 056568ac 00005773 051b95bd 00005773 |.he.sW......sW..|
[00156.768] 01189.01252> 0x00002afa541eb538: 36b3ffa8 000039c5 03849867 69040de0 |...6.9..g......i|
[00156.768] 01189.01252> 0x00002afa541eb548: 40538b00 0000101c 40538b10 0000101c |..S@......S@....|
[00156.768] 01189.01252> 0x00002afa541eb558: 40538a00 0000101c 36b400e0 000039c5 |..S@.......6.9..|
[00156.768] 01189.01252> 0x00002afa541eb568: 03849867 69040de0 36b400d8 000039c5 |g......i...6.9..|
[00156.768] 01189.01252> 0x00002afa541eb578: 52a2c1c0 000010bd 541eb5a0 00002afa |...R.......T.*..|
[00156.768] 01189.01252> 0x00002afa541eb588: 0565690e 00005773 06666268 00005773 |.ie.sW..hbf.sW..|
[00156.768] 01189.01252> 0x00002afa541eb598: 40538a00 0000101c 541eb5e0 00002afa |..S@.......T.*..|
[00156.768] 01189.01252> 0x00002afa541eb5a8: 051b2c0c 00005773 52a2c101 000010bd |.,..sW.....R....|
[00156.768] 01189.01252> 0x00002afa541eb5b8: 36b40180 000039c5 52a2c1c0 000010bd |...6.9.....R....|
[00156.768] 01189.01252> arch: x86_64
[00156.769] 01189.01252> dso: id=a2a0fb2f528afd35 base=0x7ef277b7a000 name=libz.so
[00156.769] 01189.01252> dso: id=8fe1f17722cff0f4 base=0x7c94601f8000 name=libVkLayer_threading.so
[00156.769] 01189.01252> dso: id=18b8f25cccfe06161cb5a52192462e25761d04ad base=0x78deb3a78000 name=libc.so
[00156.769] 01189.01252> dso: id=43374063090eb40e base=0x7513d6e5d000 name=libfxl.so
[00156.769] 01189.01252> dso: id=83d5c8cfdd705921109e40de6f9e26e47c53038e base=0x723595154000 name=<vDSO>
[00156.769] 01189.01252> dso: id=f034f421787360bc base=0x6fb8f7c5d000 name=libc++abi.so.1
[00156.769] 01189.01252> dso: id=360ba7d2b699e6f7 base=0x6e4b3ba6c000 name=libvulkan.so
[00156.769] 01189.01252> dso: id=944d3dc1d4acace1444ae8357308aa0099259115 base=0x67c668551000 name=libasync-default.so
[00156.769] 01189.01252> dso: id=09ab53c187ea2cad base=0x6405c0e9e000 name=libVkLayer_core_validation.so
[00156.769] 01189.01252> dso: id=a744e191036ece27 base=0x5eaa72316000 name=libicui18n.so
[00156.769] 01189.01252> dso: id=7b05f370b5abfdef5c7283db03b54146464fb7ed base=0x58c5930c4000 name=libdriver.so
[00156.769] 01189.01252> dso: id=7b384aeca102b8bf base=0x577303fea000 name=app:flutter:armadillo_user_... (+1)
[00156.769] 01189.01252> dso: id=43e40effc277a0f3 base=0x5407b5f9f000 name=libc++.so.2
[00156.769] 01189.01252> dso: id=935be63a95211aa4 base=0x5055d8e89000 name=libcrypto.so
[00156.769] 01189.01252> dso: id=f435df5221b7cd81b7c38f966093e82ef22947e4 base=0x4f84c8854000 name=liblaunchpad.so
[00156.769] 01189.01252> dso: id=7e863a664fdcfc7a base=0x4eaae2c41000 name=libVkLayer_parameter_validation.so
[00156.769] 01189.01252> dso: id=626ed768c4f9e078 base=0x4bf2c9691000 name=libunwind.so.1
[00156.769] 01189.01252> dso: id=d9b3341e46831f64 base=0x463ad24fd000 name=libminizip.so
[00156.769] 01189.01252> dso: id=81675874a401bd6b6533da0450a574e669af6e03 base=0x41ae3835b000 name=libtrace-engine.so
[00156.769] 01189.01252> dso: id=d81b719722c017da base=0x2ed595d56000 name=libmagma.so
[00156.769] 01189.01252> dso: id=f21f6208ac57a1b3 base=0x1aeb4b367000 name=libfxl_logging.so
[00156.769] 01189.01252> dso: id=7f682c5d21c17d73 base=0x1adf391b5000 name=libssl.so
[00156.769] 01189.01252> dso: id=b6de74bcc0ec3337 base=0x194d5c338000 name=libVkLayer_unique_objects.so
[00156.769] 01189.01252> dso: id=d3997760089ea7b1 base=0x14ec5c7a2000 name=libicuuc.so
[00156.769] 01189.01252> dso: id=56652fc5e09790fa base=0x10f0d9305000 name=libvulkan_intel.so
[00156.769] 01189.01252> dso: id=61586ad4aaa7b70b71cd3b70a7c1bfeff21edc88 base=0xb5ca5298000 name=libfdio.so
[00156.769] 01189.01252> dso: id=87dd3ab6942eb263 base=0x579a6dca000 name=libfsl.so
[00156.769] 01189.01252> bt#01: pc 0x78deb3a93c20 sp 0x2afa541eb4c8 (libc.so,0x1bc20)
[00156.769] 01189.01252> bt#02: pc 0x5773052aac04 sp 0x2afa541eb4d0 (app:flutter:armadillo_user_... (+1),0x12c0c04)
[00156.770] 01189.01252> bt#03: pc 0x5773052aab9e sp 0x2afa541eb4f0 (app:flutter:armadillo_user_... (+1),0x12c0b9e)
[00156.770] 01189.01252> bt#04: pc 0x5773056549ab sp 0x2afa541eb510 (app:flutter:armadillo_user_... (+1),0x166a9ab)
[00156.770] 01189.01252> bt#05: pc 0x5773056568ac sp 0x2afa541eb530 (app:flutter:armadillo_user_... (+1),0x166c8ac)
[00156.770] 01189.01252> bt#06: pc 0x57730565690e sp 0x2afa541eb590 (app:flutter:armadillo_user_... (+1),0x166c90e)
[00156.770] 01189.01252> bt#07: pc 0x5773051b2c0c sp 0x2afa541eb5b0 (app:flutter:armadillo_user_... (+1),0x11c8c0c)
[00156.770] 01189.01252> bt#08: pc 0x5773051ac7e4 sp 0x2afa541eb5f0 (app:flutter:armadillo_user_... (+1),0x11c27e4)
[00156.770] 01189.01252> bt#09: pc 0x5773051abc8d sp 0x2afa541eb670 (app:flutter:armadillo_user_... (+1),0x11c1c8d)
[00156.770] 01189.01252> bt#10: pc 0x57730520e42d sp 0x2afa541eb6d0 (app:flutter:armadillo_user_... (+1),0x122442d)
[00156.771] 01189.01252> bt#11: pc 0x577305200545 sp 0x2afa541eb710 (app:flutter:armadillo_user_... (+1),0x1216545)
[00156.771] 01189.01252> bt#12: pc 0x577305200cce sp 0x2afa541eb770 (app:flutter:armadillo_user_... (+1),0x1216cce)
[00156.771] 01189.01252> bt#13: pc 0x577305e83c18 sp 0x2afa541eb7b0 (app:flutter:armadillo_user_... (+1),0x1e99c18)
[00156.771] 01189.01252> bt#14: pc 0x577305e838fd sp 0x2afa541eb820 (app:flutter:armadillo_user_... (+1),0x1e998fd)
[00156.771] 01189.01252> bt#15: pc 0x577305bf8e56 sp 0x2afa541eb870 (app:flutter:armadillo_user_... (+1),0x1c0ee56)
[00156.771] 01189.01252> bt#16: pc 0x5773059a95d7 sp 0x2afa541eb880 (app:flutter:armadillo_user_... (+1),0x19bf5d7)
[00156.771] 01189.01252> bt#17: pc 0x5773059a9295 sp 0x2afa541eb890 (app:flutter:armadillo_user_... (+1),0x19bf295)
[00156.771] 01189.01252> bt#18: pc 0x5773059f4637 sp 0x2afa541eb8a0 (app:flutter:armadillo_user_... (+1),0x1a0a637)
[00156.771] 01189.01252> bt#19: pc 0x5773059f4b97 sp 0x2afa541eb8b0 (app:flutter:armadillo_user_... (+1),0x1a0ab97)
[00156.771] 01189.01252> bt#20: pc 0x5feec79c7f56 sp 0x2afa541eb8c0 (libicui18n.so,0x144556b1f56)
[00156.771] 01189.01252> bt#21: pc 0x13416d4a8b9a sp 0x2afa541eb8d0 (libvulkan_intel.so,0x250941a3b9a)
[00156.771] 01189.01252> bt#22: pc 0x577305baa99a sp 0x2afa541eb8e0 (app:flutter:armadillo_user_... (+1),0x1bc099a)
[00156.772] 01189.01252> bt#23: pc 0x13416d4a8b9a sp 0x2afa541eb8f0 (libvulkan_intel.so,0x250941a3b9a)
[00156.772] 01189.01252> bt#24: pc 0x57730592b5b0 sp 0x2afa541eb900 (app:flutter:armadillo_user_... (+1),0x19415b0)
[00156.772] 01189.01252> bt#25: pc 0x57730592b757 sp 0x2afa541eb910 (app:flutter:armadillo_user_... (+1),0x1941757)
[00156.772] 01189.01252> bt#26: pc 0x5baf4e081f96 sp 0x2afa541eb920 (libdriver.so,0x2e9bafbdf96)
[00156.772] 01189.01252> bt#27: pc 0x577305bf90ac sp 0x2afa541eb930 (app:flutter:armadillo_user_... (+1),0x1c0f0ac)
[00156.772] 01189.01252> bt#28: pc 0x577305dfc660 sp 0x2afa541eb940 (app:flutter:armadillo_user_... (+1),0x1e12660)
[00156.772] 01189.01252> bt#29: pc 0x577305dfcbe1 sp 0x2afa541ebcb0 (app:flutter:armadillo_user_... (+1),0x1e12be1)
[00156.773] 01189.01252> bt#30: pc 0x577305dfc9df sp 0x2afa541ebd30 (app:flutter:armadillo_user_... (+1),0x1e129df)
[00156.773] 01189.01252> bt#31: pc 0x57730650f18a sp 0x2afa541ebd70 (app:flutter:armadillo_user_... (+1),0x252518a)
[00156.773] 01189.01252> bt#32: pc 0x5773056c717f sp 0x2afa541ebde0 (app:flutter:armadillo_user_... (+1),0x16dd17f)
[00156.773] 01189.01252> bt#33: pc 0x5773052a5543 sp 0x2afa541ebe00 (app:flutter:armadillo_user_... (+1),0x12bb543)
[00156.773] 01189.01252> bt#34: pc 0x57730582bdf8 sp 0x2afa541ebe80 (app:flutter:armadillo_user_... (+1),0x1841df8)
[00156.773] 01189.01252> bt#35: pc 0x57730582ca45 sp 0x2afa541ebeb0 (app:flutter:armadillo_user_... (+1),0x1842a45)
[00156.773] 01189.01252> bt#36: pc 0x57730582bfc0 sp 0x2afa541ebef0 (app:flutter:armadillo_user_... (+1),0x1841fc0)
[00156.773] 01189.01252> bt#37: pc 0x57730582befb sp 0x2afa541ebf20 (app:flutter:armadillo_user_... (+1),0x1841efb)
[00156.773] 01189.01252> bt#38: pc 0x57730582a499 sp 0x2afa541ebf50 (app:flutter:armadillo_user_... (+1),0x1840499)
[00156.773] 01189.01252> bt#39: pc 0x5773051a949a sp 0x2afa541ebfa0 (app:flutter:armadillo_user_... (+1),0x11bf49a)
[00156.774] 01189.01252> bt#40: pc 0x78deb3a9312e sp 0x2afa541ebfe0 (libc.so,0x1b12e)
[00156.774] 01189.01252> bt#41: pc 0 sp 0x2afa541ec000
[00156.774] 01189.01252> bt#42: end
start of symbolized stack:
#42: (unknown)
#01: abort at ../../zircon/third_party/ulib/musl/src/exit/abort.c:7
#02: async::AutoWait::Cancel() at ??:?
#03: ~AutoWait at ../../out/dashboard/../../zircon/system/ulib/async/auto_wait.cpp:19
#04: ~Connector at ../../out/dashboard/../../garnet/public/lib/fidl/cpp/bindings/internal/connector.cc:42
#05: ~Router at ../../out/dashboard/../../garnet/public/lib/fidl/cpp/bindings/internal/router.cc:94
#06: ~Router at ../../out/dashboard/../../garnet/public/lib/fidl/cpp/bindings/internal/router.cc:87
#07: fidl::Binding<mozart::InputMethodEditorClient, mozart::InputMethodEditorClient*>::Close() at ../../out/dashboard/../../garnet/public/lib/fidl/cpp/bindings/binding.h:151
#08: flutter_runner::RuntimeHolder::HandleTextInputPlatformMessage(blink::PlatformMessage*) at ../../out/dashboard/../../third_party/flutter/content_handler/runtime_holder.cc:?
#09: flutter_runner::RuntimeHolder::HandlePlatformMessage(fxl::RefPtr<blink::PlatformMessage>) at ../../out/dashboard/../../third_party/flutter/content_handler/runtime_holder.cc:367
#10: blink::RuntimeController::HandlePlatformMessage(fxl::RefPtr<blink::PlatformMessage>) at ../../out/dashboard/../../third_party/flutter/runtime/runtime_controller.cc:138
#11: blink::(anonymous namespace)::SendPlatformMessage(Dart_Handle*, std::2::basic_string<char, std::2::char_traits<char>, std::_2::allocator<char> > const&, _Dart_Handle*, tonic::DartByteData const&) at ../../out/dashboard/../../third_party/flutter/lib/ui/window/window.cc:91
#12: void tonic::DartCallStatic<void (Dart_Handle*, std::2::basic_string<char, std::2::char_traits<char>, std::2::allocator<char> > const&, _Dart_Handle*, tonic::DartByteData const&)>(void (_Dart_Handle*, std::2::basic_string<char, std::2::char_traits<char>, std::_2::allocator<char> > const&, _Dart_Handle*, tonic::DartByteData const&), _Dart_NativeArguments*) at ../../out/dashboard/../../topaz/lib/tonic/dart_args.h:209
#13: dart::NativeArguments::ReturnValue() const at ../../out/dashboard/../../third_party/dart/runtime/vm/native_arguments.h:138
(inlined by) dart::NativeEntry::ReturnValueIsError(dart::NativeArguments*) at ../../out/dashboard/../../third_party/dart/runtime/vm/native_entry.cc:89
(inlined by) dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (_Dart_NativeArguments*)) at ../../out/dashboard/../../third_party/dart/runtime/vm/native_entry.cc:186
#14: dart::NativeEntry::AutoScopeNativeCallWrapper(_Dart_NativeArguments*, void (_Dart_NativeArguments*)) at ../../out/dashboard/../../third_party/dart/runtime/vm/native_entry.cc:156
#15: kDartVmSnapshotInstructions at ??:?
#16: kDartVmSnapshotInstructions at ??:?
#17: kDartVmSnapshotInstructions at ??:?
#18: kDartVmSnapshotInstructions at ??:?
#19: kDartVmSnapshotInstructions at ??:?
#20: ?? ??:0
#21: ?? ??:0
#22: kDartVmSnapshotInstructions at ??:?
#23: ?? ??:0
#24: kDartVmSnapshotInstructions at ??:?
#25: kDartVmSnapshotInstructions at ??:?
#26: ?? ??:0
#27: kDartVmSnapshotInstructions at ??:?
#28: dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) at ../../out/dashboard/../../third_party/dart/runtime/vm/dart_entry.cc:126
#29: dart::DartEntry::InvokeClosure(dart::Array const&, dart::Array const&) at ../../out/dashboard/../../third_party/dart/runtime/vm/dart_entry.cc:155
#30: dart::DartEntry::InvokeClosure(dart::Array const&) at ../../out/dashboard/../../third_party/dart/runtime/vm/dart_entry.cc:134
#31: Dart_InvokeClosure at ../../out/dashboard/../../third_party/dart/runtime/vm/dart_api_impl.cc:4108
#32: tonic::DartInvokeVoid(_Dart_Handle*) at ../../out/dashboard/../../topaz/lib/tonic/logging/dart_invoke.cc:28
#33: tonic::DartMicrotaskQueue::RunMicrotasks() at ../../out/dashboard/../../topaz/lib/tonic/dart_microtask_queue.cc:81
#34: async_loop_invoke_wait_handler at ../../out/dashboard/../../zircon/system/ulib/async/loop.c:566
#35: async_loop_dispatch_wait at ../../out/dashboard/../../zircon/system/ulib/async/loop.c:248
#36: async_loop_run_once at ../../out/dashboard/../../zircon/system/ulib/async/loop.c:?
#37: async_loop_run at ../../out/dashboard/../../zircon/system/ulib/async/loop.c:192
#38: fsl::MessageLoop::Run() at ../../out/dashboard/../../garnet/public/lib/fsl/tasks/message_loop.cc:164
#39: main at ../../out/dashboard/../../third_party/flutter/content_handler/main.cc:16
#40: start_main at ../../zircon/third_party/ulib/musl/src/env/__libc_start_main.c:57
#41: (unknown)
end of symbolized stack
```

**Comment by eseidelGoogle** [comment] 2017-11-16 18:03
@collinjackson Do you have a fuchsia device yet such that you could help Andrew resolve this?

Otherwise @chinmaygarde or @jason-simmons have historically had devices.

**Comment by eseidelGoogle** [comment] 2017-11-16 18:41
@apwilson tells me @abarth may be on this?

**Comment by jason-simmons** [comment] 2017-11-17 00:39
I have a Fuchsia device and can reproduce this.  It's failing an assert because a call to async_cancel_wait() is returning ZX_ERR_NOT_FOUND

Will need help from the Fuchsia team to root cause this.

**Comment by abarth** [comment] 2017-11-17 08:08
I investigated this issue for most of today.  I'm pretty sure its a kernel bug and have filed a bug with the kernel team.  I'm going to close this issue here but I might re-open it if the kernel team bounces the bug.

**Closed by abarth** 2017-11-17 08:08 UTC
Labels: crash, customer blocker, customer: fuchsia
