### ISSUE TITLE
GetMaterialApp.router() issues with Get.snackbar()

### ISSUE THREAD

**Issue by opxdelwin** [flutter/flutter#131659] opened 2023-08-01 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create new flutter project
2. Add 2 screens, namely being "screen 1" and "screen 2".
3. Use `go_router` for NavigatorV2 navigation
4. Exec `Get.snackbar()` in any screen to get this issue.

### Expected results

Get default snackbar popup on top

### Actual results

1. No UI output
3. Debug Console: "Unexpected null value"

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:go_router/go_router.dart';

void main() {
  // GoRouter configuration
  final _router = GoRouter(
    initialLocation: "/screen1",
    routes: [
      GoRoute(
        path: '/screen1',
        builder: (context, state) => const Screen1(),
      ),
      GoRoute(
        path: '/screen2',
        builder: (context, state) => const Screen2(),
      ),
    ],
  );
  runApp(GetMaterialApp.router(
    routeInformationParser: _router.routeInformationParser,
    routeInformationProvider: _router.routeInformationProvider,
    routerDelegate: _router.routerDelegate,
  ));
}

void showGet() {
  Get.snackbar("GET SnackBar", "It's working?");
}

class Screen1 extends StatefulWidget {
  const Screen1({super.key});

  @override
  State<Screen1> createState() => _Screen1State();
}

class _Screen1State extends State<Screen1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            IconButton(
                onPressed: () => context.push("/screen2"),
                icon: Icon(Icons.swipe_right_alt)),
            ElevatedButton(
                child: Text("SCREEN 1, GET SNACKBAR"),
                onPressed: () => showGet()),
          ],
        ),
      ),
    );
  }
}

class Screen2 extends StatefulWidget {
  const Screen2({super.key});

  @override
  State<Screen2> createState() => _Screen2State();
}

class _Screen2State extends State<Screen2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            IconButton(
                onPressed: () => context.push("/screen1"),
                icon: Icon(Icons.swipe_left_alt)),
            ElevatedButton(
                child: Text("SCREEN 2, GET SNACKBAR"),
                onPressed: () => showGet()),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Restarted application in 164ms.
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
Error: Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:63  nullCheck
packages/get/get_navigation/src/snackbar/snackbar_controller.dart 91:50           [_configureOverlay]
packages/get/get_navigation/src/snackbar/snackbar_controller.dart 331:5           [_show]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 435:5   dsend
packages/get/get_utils/src/queue/get_queue.dart 42:47                             _check$
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/get/get_utils/src/queue/get_queue.dart 37:14                             [_check]
packages/get/get_utils/src/queue/get_queue.dart 29:5                              add
packages/get/get_navigation/src/snackbar/snackbar_controller.dart 357:31          _addJob
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/get/get_navigation/src/snackbar/snackbar_controller.dart 355:23          [_addJob]
packages/get/get_navigation/src/snackbar/snackbar_controller.dart 63:27           show
packages/get/get_navigation/src/extension_navigation.dart 465:17                  ExtensionSnackbar.snackbar
packages/getx_issue_repl/main.dart 28:7                                           showGet
packages/getx_issue_repl/main.dart 77:34                                          <fn>
packages/flutter/src/material/ink_well.dart 1154:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 275:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 654:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 311:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 244:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 630:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 465:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 445:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 331:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 400:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 363:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 320:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 293:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1251:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 269:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 168:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 791:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 720:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 317:16                                    loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\KIIT0001\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.80.2)
    • VS Code at C:\Users\KIIT0001\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-08-01 11:43
Hi @opxdelwin 
From what I can see, the issue is related to a 3rd party package (https://pub.dev/packages/get) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/jonataslaw/getx/issues). 

Closing, as this isn't an issue with Flutter itself.  

If you still think this is a Flutter framework issue, please write in the comments, providing a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party packages/plugins and I will reopen it for further discussion.

**Closed by huycozy** 2023-08-01 11:43 UTC
Labels: in triage
