### ISSUE TITLE
[linux] App doesn't render Bengali language characters properly 

### ISSUE THREAD

**Issue by ssantanuberaa** [flutter/flutter#65942] opened 2020-09-16 13:57 UTC
Hello Flutter Team,
I am building a Desktop application using flutter on Linux environment. But it doesn't support characters of Bengali language. Following is a sample code that I was trying out -
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
	// This widget is the root of your application.
	@override
	Widget build(BuildContext context) {
		return MaterialApp(
			title: 'Flutter Demo',
			home: Material(
				child: Center(
					child: Text("শান্তনু বেরা")
				),
			),
		);
	}
}
```
If I run the same code for mobile application, the Bengali characters shows perfectly, but in Desktop application it fails to show the character. Instead it shows a square box in place of the characters. How can I solve this problem? Below is the output looks like on my desktop.

![image](https://user-images.githubusercontent.com/28649026/93346982-36494680-f852-11ea-9637-eaae25c8054d.png)

Here is my Flutter Doctor summary -

![image](https://user-images.githubusercontent.com/28649026/93347392-a35cdc00-f852-11ea-81a1-a717c3a3615f.png)

**Comment by HansMuller** [comment] 2020-09-16 15:27
CC @shihaohong

**Comment by TahaTesser** [comment] 2020-09-16 15:39
Hi @ssantanuberaa 
I can reproduce it on Linux only, macOS desktop app renders fine
**Linux**

![image](https://user-images.githubusercontent.com/48603081/93359761-99da7080-f860-11ea-9aa9-d8286ccdbbc6.png)



**macos**
<img width="400" alt="Screenshot 2020-09-16 at 9 08 52 PM" src="https://user-images.githubusercontent.com/48603081/93360094-e4f48380-f860-11ea-8e8a-1076fe8c688d.png">



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
	// This widget is the root of your application.
	@override
	Widget build(BuildContext context) {
		return MaterialApp(
			title: 'Flutter Demo',
			home: Material(
				child: Center(
					child: Text("শান্তনু বেরা")
				),
			),
		);
	}
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.204, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.204 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision b2b5f2636a (7 minutes ago), 2020-09-16 08:02:06 -0700
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • iPhone 11 (mobile) • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2020-09-16 16:33
Duplicate of https://github.com/flutter/flutter/issues/30700

**Closed by stuartmorgan** 2020-09-16 16:33 UTC
Labels: a: desktop, a: internationalization, a: typography, f: material design, found in release: 1.22, framework, has reproducible steps, platform-linux
