### ISSUE TITLE
Introducing platforms directory to simplify project structure.

### ISSUE THREAD

**Issue by itome** [flutter/flutter#122659] opened 2023-03-15 02:26 UTC
## Use case
Now flutter have many supported platforms and directory for each platform (`android` `ios` `web` ...) is in top level of project.
I think it's better to move those directory to `platforms` directory.

## Proposal
Current situation
```
[root]
  - android
  - ios
  - lib
    - [dart code here]
  - linux
  - macos
  - web
  - windows
```
Proposal
```
[root]
  - lib
  - platforms
    - android
    - ios
    - linux
    - macos
    - web
    - windows
```

**Comment by stuartmorgan** [comment] 2023-03-15 02:40
Closing as a duplicate of https://github.com/flutter/flutter/issues/71400

**Closed by stuartmorgan** 2023-03-15 02:40 UTC
