### ISSUE TITLE
didChangeDependencies called every time Navigator.push called 

### ISSUE THREAD

**Issue by karabaralex** [flutter/flutter#39872] opened 2019-09-05 04:52 UTC
Steps to repro:

1. Create Widget1 which pushes another Widget2 using Navigator.push
2. add logging to Widget1's didChangeDependencies

Actual: observe that Widget1's didChangeDependencies called every time Widget2 get pushed to the tree
Expected: didChangeDependencies is not called (since no dependency changed)

Example:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Navigator.of(context).push(MaterialPageRoute(builder: (_) {
      print("push next page");
      return NextPage();
    }));
  }

  @override
  void initState() {
    print("init state called");
    super.initState();
  }

  @override
  void didChangeDependencies() {
    print("didChangeDependencies called");
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(child: Container(color: Colors.green,), onTap: () {
      Navigator.of(context).pop();
    },);
  }
}
```

It is probably happens because whenever widget get pushed element tree changes and Widget1 get deactivated and activated again. activate code looks like this:
```
  /// Transition from the "inactive" to the "active" lifecycle state.
  ///
  /// The framework calls this method when a previously deactivated element has
  /// been reincorporated into the tree. The framework does not call this method
  /// the first time an element becomes active (i.e., from the "initial"
  /// lifecycle state). Instead, the framework calls [mount] in that situation.
  ///
  /// See the lifecycle documentation for [Element] for additional information.
  @mustCallSuper
  void activate() {
    assert(_debugLifecycleState == _ElementLifecycle.inactive);
    assert(widget != null);
    assert(owner != null);
    assert(depth != null);
    assert(!_active);
    final bool hadDependencies = (_dependencies != null && _dependencies.isNotEmpty) || _hadUnsatisfiedDependencies;
    _active = true;
    // We unregistered our dependencies in deactivate, but never cleared the list.
    // Since we're going to be reused, let's clear our list now.
    _dependencies?.clear();
    _hadUnsatisfiedDependencies = false;
    _updateInheritance();
    assert(() { _debugLifecycleState = _ElementLifecycle.active; return true; }());
    if (_dirty)
      owner.scheduleBuildFor(this);
    if (hadDependencies)
      didChangeDependencies();
  }
```
see check:
```
    if (hadDependencies)
      didChangeDependencies();
```

so it always calls didChangeDependencies even if no dependency is actually changed.

**Comment by radvansky-tomas** [comment] 2019-10-12 03:10
I think that it happens on "pop" too

**Comment by jam33** [comment] 2020-01-30 02:59
confirming i see similar behavior on both push and pop (when state via provider is not changed on descendant page/widget)

**Comment by AHoxha19** [comment] 2020-04-26 20:39
i can confirm too. I have the same problem when i pop.

**Comment by hassanbht** [comment] 2020-05-04 05:56
I have the same problem

**Comment by chi-tran** [comment] 2020-05-12 07:44
That also happens for me, does anybody understand if this is expected behaviour and how to resolve it correctly?

**Comment by hasanzia1993** [comment] 2020-07-09 20:44
Nothing on it yet ? I am calling Navigator.push in it which overflows the stack

**Comment by VladyslavBondarenko** [comment] 2020-07-23 09:01
With current stable `1.17.5` and master `1.21.0-2.0.pre.114` I can see that didChangeDependencies is called only after initState, [what is expected](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html), and not on every push or pop.

<details>
 <summary>code sample and logs</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Navigator.of(context).push(MaterialPageRoute(builder: (_) {
      print("push next page");
      return NextPage();
    }));
  }

  @override
  void initState() {
    print("init state called");
    super.initState();
  }

  @override
  void didChangeDependencies() {
    print("didChangeDependencies called");
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NextPage extends StatefulWidget {
  @override
  _NextPageState createState() => _NextPageState();
}

class _NextPageState extends State<NextPage> {

  @override
  void initState() {
    print("init state NextPage called");
    super.initState();
  }

  @override
  void didChangeDependencies() {
    print("didChangeDependencies NextPage called");
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      child: Container(
        color: Colors.green,
      ),
      onTap: () {
        Navigator.of(context).pop();
      },
    );
  }
}
```

```
I/flutter ( 3289): init state called
I/flutter ( 3289): didChangeDependencies called
I/.example.newap( 3289): ProcessProfilingInfo new_methods=663 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter ( 3289): push next page
I/flutter ( 3289): init state NextPage called
I/flutter ( 3289): didChangeDependencies NextPage called
I/flutter ( 3289): push next page
I/flutter ( 3289): init state NextPage called
I/flutter ( 3289): didChangeDependencies NextPage called
```

</details>

Closing as fixed, if you disagree please write in comment and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-23 09:01 UTC
Labels: framework

**Comment by GraSim** [comment] 2020-12-27 15:52
The issue is still occuring in Flutter 1.22.5. In my case, every time I clicked in TextFormField and soft keyboard appears.
