### ISSUE TITLE
[Impeller] Investigate alternatives to using the swapchain with Vulkan on Android.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132512] opened 2023-08-14 18:48 UTC
From the last Skia Graphics sync ([go/impeller-graphite-sync](http://go/impeller-graphite-sync)), it was mentioned that Chrome uses surface control [to create](https://source.chromium.org/chromium/chromium/src/+/main:components/viz/service/display_embedder/buffer_queue.cc;drc=fa66b68f5c1d2b022e392796307062d88b81deb0;l=158) and [send Android Hardware Buffers directly to SurfaceFlinger](https://source.chromium.org/chromium/chromium/src/+/main:components/viz/service/display_embedder/skia_output_device_buffer_queue.cc;drc=24024cbe27dcebbcb258ee7da984db81a88d66e7;l=392) when able. Since there is an API availability issue, [there is a Vulkan swapchain fallback](https://source.chromium.org/chromium/chromium/src/+/main:components/viz/service/display_embedder/skia_output_device_vulkan.cc;drc=ee37f51db66140a21ee2c9e88f967bd59c473f91;l=183).

This technique may also be used for GL [citation needed, see chat thread about the mention].

The main benefit to avoiding swapchains was that they make it hard to control allocations for the underlying images and image views.  This tracks as Impeller goes to great lengths (relative to other backends) avoid hitting the allocators in frame workloads.

From discussion in [go/impeller-weekly](http://go/impeller-weekly), work on this alternative will not be prioritized till we are past stable with Impeller on Android.

#### References & Breadcrumbs
* https://developer.android.com/ndk/reference/group/native-activity#asurfacecontrol
* https://developer.android.com/ndk/reference/group/a-hardware-buffer
* Chat thread [go/bc94d8bd-bfcf-4915-b7d1-8d5d213eeb55](http://go/bc94d8bd-bfcf-4915-b7d1-8d5d213eeb55)
* Email Thread [go/15ec12be-dfda-4ce7-8e39-20db4ebedd50](http://go/15ec12be-dfda-4ce7-8e39-20db4ebedd50)

**Comment by johnmccutchan** [comment] 2024-02-07 19:54
Duplicate of https://github.com/flutter/flutter/issues/143105

**Closed by johnmccutchan** 2024-02-07 19:54 UTC
Labels: P3, e: impeller, team-engine, triaged-engine
