### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by sahil311289** [flutter/flutter#18973] opened 2018-07-01 02:14 UTC
```Launching lib/main.dart on Sahil’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: Q48Y4UFKL8
Running pod install...
Starting Xcode build...
Xcode build done.
Installing and launching...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws

**Comment by sahil311289** [comment] 2018-07-01 02:14
```/Users/sahil/flutterDevelopment/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by sahil311289** [comment] 2018-07-01 02:17
I'm basically trying to implement Speech Recognition plugin found here: https://github.com/rxlabz/speech_recognition
While it works just fine on Android, a new iOS build in Swift finds one or more errors. Have been struggling for days. Please help me resolve this issue.

**Comment by dklinzh** [comment] 2018-07-03 07:32
Duplicate of #17803

**Comment by zoechi** [comment] 2018-07-03 07:40
Thanks @dklinzh for spotting.
@sahil311289 I hope it's ok with you if I close as dup.
Otherwise add a comment and I'll reopen.

**Closed by zoechi** 2018-07-03 07:40 UTC
Labels: ⌺‬ platform-ios

**Comment by kianoosh** [comment] 2018-09-03 11:17
you don't need to remove it just
brew unlink python@2

**Comment by BrianSipple** [comment] 2019-01-02 10:17
There's another solution outlined [here](https://forums.swift.org/t/swift-repl-starts-with-error-when-homebrew-python-is-installed/12927/3) which involves using an alias to only modify your shell path while running `swift`. 

Seems like a good strategy if you don't want to change the way you're managing Python system-wide (that is, with Homebrew 😄).
