### ISSUE TITLE
Firebase auth with Transaction in flutter

### ISSUE THREAD

**Issue by tarektaamali** [flutter/flutter#46963] opened 2019-12-13 09:28 UTC
I want to make a transaction in update profile in firebase if any error in request i make rollback  .does flutter and firebase authentification support Transactions 

![Capture du 2019-12-13 09-12-59](https://user-images.githubusercontent.com/17914433/70789303-0afd6c80-1d93-11ea-8e40-06971e1a0bd0.png)

**Comment by iapicca** [comment] 2019-12-13 12:43
Hi @tarektaamali 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-13 12:43 UTC
