### ISSUE TITLE
DropdownButton items font appears buggy

### ISSUE THREAD

**Issue by topex-psy** [flutter/flutter#52279] opened 2020-03-10 00:11 UTC
## Steps to Reproduce

1. Create new flutter project
2. Create dropdown input with `DropdownButton`, for example:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _listMetodePembayaran = <String>[];
  String _metodePembayaran;

  @override
  void initState() {
    _listMetodePembayaran = ['Tunai', 'ATM/Bank', 'Go-Pay', 'OVO', 'Dana', 'Jenius'];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter Dropdown"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("Metode pembayaran:", style: TextStyle(fontWeight: FontWeight.bold),),
            SizedBox(height: 15,),
            DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                isDense: true,
                underline: null,
                value: _metodePembayaran,
                style: TextStyle(fontSize: 16, color: Theme.of(context).textTheme.bodyText1.color),
                onChanged: (String val) {
                  setState(() { _metodePembayaran = val; });
                },
                items: _listMetodePembayaran.map<DropdownMenuItem<String>>((String val) {
                  return DropdownMenuItem<String>(
                    value: val,
                    child: Text("$val"),
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** 
Dropdown item font match current text theme

**Actual results:** 
Dropdown item font is buggy & has yellow underline. Apparently this happen after I ran `flutter upgrade` yesterday (flutter channel master).

Dropdown Closed | Dropdown Opened
:-------------------------:|:--------------------------:
![Screenshot_20200310-070130](https://user-images.githubusercontent.com/14989865/76267682-24348d00-629e-11ea-8022-704855cf23bb.jpg) | ![Screenshot_20200310-070136](https://user-images.githubusercontent.com/14989865/76267722-44644c00-629e-11ea-9892-9caea88139fe.jpg)

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel master, v1.15.19-pre.17, on Microsoft Windows [Version 10.0.18362.657], locale en-ID)
    • Flutter version 1.15.19-pre.17 at G:\Android\Flutter\flutter
    • Framework revision 5b0a79dbdb (23 hours ago), 2020-03-08 21:16:01 -0400
    • Engine revision 981c03631e
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: G:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at G:\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (3 available)
    • ASUS X00RD • J7AXGF039027BHD • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome          • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server      • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-03-10 08:49
```
Flutter 1.15.19-pre.17 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5b0a79dbdb (32 hours ago) • 2020-03-08 21:16:01 -0400
Engine • revision 981c03631e
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

![Screenshot_1583830126](https://user-images.githubusercontent.com/48603081/76295156-20bef700-62da-11ea-9ad3-54c2ba2a65cb.png)


Duplicate of [#52018](https://github.com/flutter/flutter/issues/52018)

**Closed by TahaTesser** 2020-03-10 08:49 UTC
