### ISSUE TITLE
SVG not rendering correctly in iOS

### ISSUE THREAD

**Issue by muezz** [flutter/flutter#146110] opened 2024-04-02 03:33 UTC
### Steps to reproduce

1. Install latest version of `flutter_svg`
2. Save the SVG given below in the assets folder
3. Render it using the `SvgPicture.asset()` widget.

### Expected results

The SVG should render correctly as I have not found any issues in the SVG so far.

### Actual results

There are weird colored rectangles wherever there are angled reflections on the screens inside the SVG.

### Code sample

<details open><summary>Code sample</summary>

```svg
<svg width="202" height="202" viewBox="0 0 202 202" fill="none" xmlns="http://www.w3.org/2000/svg">
<g opacity="0.1">
<path d="M168.839 40.4202C151.338 23.6259 126.411 28.2356 112.716 40.9333C102.709 50.2253 86.9446 63.6987 74.7398 63.1129C62.64 62.5271 48.807 54.136 33.7742 60.6C18.9393 66.967 14.8872 88.0276 21.5936 104.131C28.3243 120.291 52.8834 133.425 82.5976 145.674C93.5136 150.246 105.249 152.54 117.083 152.413C117.083 152.413 143.981 152.134 154.089 145.666C162.004 140.592 165.393 137.259 173.95 124.343C180.414 114.566 184.745 100.822 185.23 87.5064C185.84 71.2373 181.913 52.9684 168.839 40.4202Z" fill="#FFBF47"/>
<path opacity="0.8" d="M168.839 40.4202C151.338 23.6259 126.411 28.2356 112.716 40.9333C102.709 50.2253 86.9446 63.6987 74.7398 63.1129C62.64 62.5271 48.807 54.136 33.7742 60.6C18.9393 66.967 14.8872 88.0276 21.5936 104.131C28.3243 120.291 52.8834 133.425 82.5976 145.674C93.5136 150.246 105.249 152.54 117.083 152.413C117.083 152.413 143.981 152.134 154.089 145.666C162.004 140.592 165.393 137.259 173.95 124.343C180.414 114.566 184.745 100.822 185.23 87.5064C185.84 71.2373 181.913 52.9684 168.839 40.4202Z" fill="white"/>
</g>
<path d="M98.3371 166.795C140.095 166.795 173.946 164.782 173.946 162.299C173.946 159.816 140.095 157.802 98.3371 157.802C56.5796 157.802 22.7285 159.816 22.7285 162.299C22.7285 164.782 56.5796 166.795 98.3371 166.795Z" fill="#FFBF47"/>
<path opacity="0.6" d="M98.3371 166.795C140.095 166.795 173.946 164.782 173.946 162.299C173.946 159.816 140.095 157.802 98.3371 157.802C56.5796 157.802 22.7285 159.816 22.7285 162.299C22.7285 164.782 56.5796 166.795 98.3371 166.795Z" fill="white"/>
<path d="M36.5851 67.0276H162.492C163.612 67.0276 164.687 67.4729 165.48 68.2654C166.272 69.0579 166.718 70.1327 166.718 71.2535V154.235H32.3633V71.2535C32.3633 70.1334 32.8079 69.0592 33.5996 68.2668C34.3912 67.4744 35.465 67.0287 36.5851 67.0276Z" fill="#FFBF47" stroke="#263238" stroke-width="0.920603" stroke-miterlimit="10"/>
<path d="M161.269 73.8431H37.8145V143.61H161.269V73.8431Z" fill="white"/>
<mask id="mask0_100_99" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="37" y="73" width="125" height="71">
<path d="M161.269 73.8431H37.8145V143.61H161.269V73.8431Z" fill="white"/>
</mask>
<g mask="url(#mask0_100_99)">
<g style="mix-blend-mode:multiply" opacity="0.4">
<path d="M161.269 143.61V84.0562L59.1504 143.61H161.269Z" fill="#FFBF47"/>
</g>
</g>
<path d="M161.269 73.8431H37.8145V143.61H161.269V73.8431Z" stroke="#263238" stroke-width="0.690452" stroke-miterlimit="10"/>
<path d="M146.014 150.038H53.6797V154.587H146.014V150.038Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M146.014 152.231H53.6797V154.591H146.014V152.231Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M21.4961 157.285C21.4961 157.285 23.0151 159.14 27.5561 160.655H172.132C172.132 160.655 175.501 159.81 177.02 157.451L21.4961 157.285Z" fill="#FFBF47" stroke="#263238" stroke-width="0.920603" stroke-miterlimit="10"/>
<path d="M176.257 153.964H22.2803C21.6778 153.964 21.1895 154.453 21.1895 155.055V156.417C21.1895 157.019 21.6778 157.507 22.2803 157.507H176.257C176.859 157.507 177.348 157.019 177.348 156.417V155.055C177.348 154.453 176.859 153.964 176.257 153.964Z" fill="#FFBF47" stroke="#263238" stroke-width="0.920603" stroke-miterlimit="10"/>
<path d="M99.5137 70.8454C100.165 70.8454 100.693 70.3173 100.693 69.6658C100.693 69.0142 100.165 68.4861 99.5137 68.4861C98.8622 68.4861 98.334 69.0142 98.334 69.6658C98.334 70.3173 98.8622 70.8454 99.5137 70.8454Z" fill="#263238"/>
<path d="M83.9275 68.4861H54.4355C54.3581 68.4861 54.2814 68.4708 54.2098 68.4412C54.1383 68.4115 54.0732 68.3681 54.0185 68.3133C53.9637 68.2585 53.9202 68.1935 53.8906 68.122C53.861 68.0504 53.8457 67.9737 53.8457 67.8962C53.8457 67.8188 53.861 67.7421 53.8906 67.6705C53.9202 67.599 53.9637 67.5339 54.0185 67.4792C54.0732 67.4244 54.1383 67.3809 54.2098 67.3513C54.2814 67.3217 54.3581 67.3064 54.4355 67.3064H83.9275C84.0837 67.3075 84.2331 67.3699 84.3435 67.4803C84.4538 67.5907 84.5163 67.7401 84.5174 67.8962C84.5174 68.0527 84.4552 68.2027 84.3446 68.3133C84.234 68.4239 84.084 68.4861 83.9275 68.4861Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M144.078 68.4861H114.586C114.429 68.4861 114.279 68.4239 114.169 68.3133C114.058 68.2027 113.996 68.0527 113.996 67.8962C113.997 67.7401 114.06 67.5907 114.17 67.4803C114.28 67.3699 114.43 67.3075 114.586 67.3064H144.078C144.234 67.3064 144.384 67.3685 144.495 67.4792C144.606 67.5898 144.668 67.7398 144.668 67.8962C144.668 68.0527 144.606 68.2027 144.495 68.3133C144.384 68.4239 144.234 68.4861 144.078 68.4861Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M165.562 91.5706C165.473 91.5706 165.387 91.5354 165.323 91.4727C165.26 91.4099 165.224 91.3246 165.223 91.2353V81.4626C165.224 81.3729 165.26 81.2872 165.323 81.2238C165.387 81.1603 165.472 81.1243 165.562 81.1232C165.651 81.1243 165.737 81.1605 165.799 81.224C165.862 81.2875 165.897 81.3733 165.897 81.4626V91.2353C165.897 91.3243 165.862 91.4095 165.799 91.4724C165.736 91.5353 165.651 91.5706 165.562 91.5706Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M33.6283 91.5706C33.5843 91.5706 33.5406 91.562 33.5 91.5451C33.4593 91.5283 33.4223 91.5036 33.3912 91.4724C33.36 91.4413 33.3353 91.4043 33.3185 91.3636C33.3016 91.323 33.293 91.2794 33.293 91.2353V81.4626C33.293 81.3733 33.3282 81.2875 33.3909 81.224C33.4537 81.1605 33.539 81.1243 33.6283 81.1232C33.718 81.1243 33.8037 81.1603 33.8671 81.2238C33.9305 81.2872 33.9666 81.3729 33.9676 81.4626V91.2353C33.9666 91.3246 33.9304 91.4099 33.8668 91.4727C33.8033 91.5354 33.7176 91.5706 33.6283 91.5706Z" fill="#FFBF47" stroke="#263238" stroke-width="0.691688" stroke-miterlimit="10"/>
<path d="M87.8457 101.949H63.0401C61.3287 101.949 59.9414 103.337 59.9414 105.048V157.415C59.9414 159.126 61.3287 160.513 63.0401 160.513H87.8457C89.557 160.513 90.9444 159.126 90.9444 157.415V105.048C90.9444 103.337 89.557 101.949 87.8457 101.949Z" fill="#263238"/>
<path d="M89.566 108.381H61.3184V154.086H89.566V108.381Z" fill="white"/>
<mask id="mask1_100_99" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="61" y="108" width="29" height="47">
<path d="M89.566 108.381H61.3184V154.086H89.566V108.381Z" fill="white"/>
</mask>
<g mask="url(#mask1_100_99)">
<g style="mix-blend-mode:multiply" opacity="0.4">
<path d="M89.5651 138.726L63.2324 154.082H89.5651V138.726Z" fill="#FFBF47"/>
</g>
</g>
<path d="M89.566 108.381H61.3184V154.086H89.566V108.381Z" stroke="#263238" stroke-width="0.52825" stroke-miterlimit="10"/>
<path d="M78.5135 105.181H72.3727C72.2656 105.181 72.1628 105.139 72.0871 105.063C72.0113 104.987 71.9688 104.885 71.9688 104.777C71.9688 104.67 72.0113 104.567 72.0871 104.492C72.1628 104.416 72.2656 104.373 72.3727 104.373H78.5135C78.6207 104.373 78.7235 104.416 78.7992 104.492C78.875 104.567 78.9175 104.67 78.9175 104.777C78.9175 104.885 78.875 104.987 78.7992 105.063C78.7235 105.139 78.6207 105.181 78.5135 105.181Z" fill="#FFBF47"/>
<path opacity="0.4" d="M78.5135 105.181H72.3727C72.2656 105.181 72.1628 105.139 72.0871 105.063C72.0113 104.987 71.9688 104.885 71.9688 104.777C71.9688 104.67 72.0113 104.567 72.0871 104.492C72.1628 104.416 72.2656 104.373 72.3727 104.373H78.5135C78.6207 104.373 78.7235 104.416 78.7992 104.492C78.875 104.567 78.9175 104.67 78.9175 104.777C78.9175 104.885 78.875 104.987 78.7992 105.063C78.7235 105.139 78.6207 105.181 78.5135 105.181Z" fill="white"/>
<path d="M77.1188 156.663C77.1188 156.332 77.0205 156.007 76.8363 155.732C76.652 155.456 76.3902 155.241 76.0838 155.114C75.7775 154.987 75.4404 154.954 75.1151 155.019C74.7899 155.083 74.4912 155.243 74.2567 155.478C74.0222 155.712 73.8625 156.011 73.7978 156.336C73.7331 156.661 73.7664 156.998 73.8932 157.305C74.0201 157.611 74.235 157.873 74.5108 158.057C74.7865 158.241 75.1106 158.34 75.4422 158.34C75.8869 158.34 76.3133 158.163 76.6278 157.849C76.9422 157.534 77.1188 157.108 77.1188 156.663Z" fill="#FFBF47" stroke="#263238" stroke-width="0.704333" stroke-miterlimit="10"/>
<path d="M76.2905 155.815H74.5938V157.512H76.2905V155.815Z" fill="#FFBF47" stroke="#263238" stroke-width="0.52825" stroke-linecap="round" stroke-linejoin="round"/>
<path opacity="0.6" d="M76.2905 155.815H74.5938V157.512H76.2905V155.815Z" fill="white" stroke="#263238" stroke-width="0.52825" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M76.2905 155.815H74.5938V157.512H76.2905V155.815Z" stroke="#263238" stroke-width="0.52825" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M171.773 156.142V119.996C171.773 117.502 169.751 115.479 167.257 115.479H90.9532C88.4587 115.479 86.4365 117.502 86.4365 119.996V156.142C86.4365 158.636 88.4587 160.659 90.9532 160.659H167.257C169.751 160.659 171.773 158.636 171.773 156.142Z" fill="#FFBF47" stroke="#263238" stroke-width="0.868674" stroke-miterlimit="10"/>
<path d="M167.223 158.651V117.487H90.9838V158.651H167.223Z" fill="white"/>
<mask id="mask2_100_99" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="90" y="117" width="78" height="42">
<path d="M167.223 158.651V117.487H90.9838V158.651H167.223Z" fill="white"/>
</mask>
<g mask="url(#mask2_100_99)">
<g style="mix-blend-mode:multiply" opacity="0.4">
<path d="M167.223 125.749L110.812 158.647H167.223V125.749Z" fill="#FFBF47"/>
</g>
</g>
<path d="M167.223 158.651V117.487H90.9838V158.651H167.223Z" stroke="#263238" stroke-width="0.651505" stroke-miterlimit="10"/>
<path d="M169.276 138.685C169.153 138.685 169.033 138.649 168.93 138.58C168.828 138.511 168.748 138.414 168.701 138.3C168.654 138.186 168.642 138.061 168.667 137.94C168.691 137.819 168.751 137.708 168.838 137.622C168.925 137.535 169.037 137.476 169.158 137.452C169.279 137.429 169.404 137.442 169.517 137.489C169.631 137.537 169.728 137.617 169.796 137.72C169.864 137.823 169.899 137.944 169.899 138.067C169.898 138.231 169.832 138.389 169.715 138.504C169.598 138.62 169.441 138.685 169.276 138.685Z" fill="#263238"/>
<path d="M158.231 115.891H160.958C161.04 115.891 161.107 115.825 161.107 115.742V115.629C161.107 115.546 161.04 115.479 160.958 115.479H158.231C158.148 115.479 158.081 115.546 158.081 115.629V115.742C158.081 115.825 158.148 115.891 158.231 115.891Z" fill="#FFBF47" stroke="#263238" stroke-width="0.652671" stroke-miterlimit="10"/>
<path d="M148.599 115.887H153.822C153.85 115.888 153.877 115.883 153.902 115.873C153.928 115.863 153.951 115.848 153.971 115.828C153.99 115.809 154.006 115.786 154.016 115.761C154.027 115.736 154.032 115.709 154.032 115.681C154.032 115.654 154.027 115.627 154.016 115.602C154.006 115.576 153.99 115.553 153.971 115.534C153.951 115.515 153.928 115.5 153.902 115.49C153.877 115.48 153.85 115.475 153.822 115.475H148.599C148.544 115.475 148.492 115.497 148.453 115.536C148.414 115.574 148.393 115.627 148.393 115.681C148.393 115.736 148.414 115.788 148.453 115.827C148.492 115.866 148.544 115.887 148.599 115.887Z" fill="#FFBF47" stroke="#263238" stroke-width="0.652671" stroke-miterlimit="10"/>
</svg>

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1526" alt="image" src="https://github.com/flutter/flutter/assets/100420605/a9035526-f3a0-4432-bb5b-1f8b9aa22743">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-PK)
    • Flutter version 3.19.4 on channel stable at /Users/abdulmuezz/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (12 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/abdulmuezz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/abdulmuezz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 00008101-001A54CE3EE3001E            • ios            • iOS 17.3.1 21D61
    • iPhone 15 Pro Max (mobile) • 531B59D9-FCB3-43C1-A266-849DA08521B9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by muezz** [comment] 2024-04-02 03:36
I also checked the issues in the repo for `flutter_svg`. The author responded to an issue and said that it is a bug inside the iOS Impeller engine. That [issue](https://github.com/flutter/flutter/issues/130078) was closed last year and I am not sure if it was resolved or not.

**Comment by danagbemava-nc** [comment] 2024-04-02 08:46
| master | stable | 
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/88313112/6fbdcb1b-912f-4139-b65c-0fd543f6a95a" width="300" />  | <img src="https://github.com/flutter/flutter/assets/88313112/29911909-82f5-4d3b-b528-504db3dd5ee8" width="300" /> |

This has been fixed on the `master` channel. This is a duplicate of https://github.com/flutter/flutter/issues/141893 and affects only simulators. 

Given that this has been fixed on the master channel, I will be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2024-04-02 08:46 UTC
Labels: in triage
