### ISSUE TITLE
Performance issue when loading one lakh records in ListView

### ISSUE THREAD

**Issue by ashok-kuvaraja** [flutter/flutter#109985] opened 2022-08-22 07:37 UTC
Hi Team,

I have implemented a ListView and load 1 lakh records. It builds properly. But, I am facing a performance issue in scrolling my list view through the scrollbar.  It is taking a long time to scroll to the corresponding position in the ListView.

## Steps to Reproduce

1.  Please run the below code snippets
2.  Use the scrollbar to scroll the listView
3.  You could see the late response from the ListView to scroll to the corresponding position.

**Expected results:** Scrolling should be happen quickly in the ListView

**Actual results:** When scrolling the listview through the scrollbar, App hung and scrolled to the position after taking a long time

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyListView(),
    );
  }
}

class MyListView extends StatelessWidget {
  const MyListView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
          itemCount: 100000,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text('Item $index'),
            );
          }),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>
  
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.5 at C:\Flutter\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\AshokKuvaraja\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.0 Preview 1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Professional 2022 version 17.4.32804.182
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\AshokKuvaraja\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)        
    • Windows (desktop)                • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19044.1889]
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 104.0.1293.63
```

</details>

Please find the demo below,

https://user-images.githubusercontent.com/60499432/185865377-07181461-e437-4fd3-bfeb-ab8e1c653145.mp4

**Comment by ShakyaCsun** [comment] 2022-08-22 09:35
In order to improve ListView performance, you can either specify `itemExtent` or a `prototyeItem`. For your code sample, you can easily solve the scrolling issue with following modification:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyListView(),
    );
  }
}

class MyListView extends StatelessWidget {
  const MyListView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: 100000,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('Item $index'),
          );
        },
        // Add This
        prototypeItem: const ListTile(
          title: Text('Item 99999'),
        ),
      ),
    );
  }
}
```

**Comment by abinvs-2019** [comment] 2022-08-22 11:06
@ashok-kuvaraja  
Try:  primary param in listView builder
primary(Creates a scrollable, linear array of widgets that are created on demand.

This constructor is appropriate for list views with a large (or infinite) number of children because the builder is called only for those children that are actually visible.)

**Comment by ashok-kuvaraja** [comment] 2022-08-22 11:09
> In order to improve ListView performance, you can either specify `itemExtent` or a `prototyeItem`. For your code sample, you can easily solve the scrolling issue with following modification:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyListView(),
>     );
>   }
> }
> 
> class MyListView extends StatelessWidget {
>   const MyListView({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: ListView.builder(
>         itemCount: 100000,
>         itemBuilder: (context, index) {
>           return ListTile(
>             title: Text('Item $index'),
>           );
>         },
>         // Add This
>         prototypeItem: const ListTile(
>           title: Text('Item 99999'),
>         ),
>       ),
>     );
>   }
> }
> ```

Hi @ShakyaCsun, 

Thanks. It is working for me.

**Comment by exaby73** [comment] 2022-08-22 13:08
Hello @ashok-kuvaraja. Glad that you were able to find a solution to your problem. Though for future reference, I believe you would get better support on sites like StackOverflow or other communities you can find [here](https://flutter.dev/community).

Since this is not a bug or feature request, I am closing this as invalid. Thank you.

**Closed** 2022-08-22 13:09 UTC
Labels: r: invalid, in triage
