### ISSUE TITLE
Web integration tests are not executed on CI for flutter/plugins

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#66449] opened 2020-09-23 13:07 UTC
In flutter/plugins#3060, I made a change to make certain tests fail, but the CI checks are still green (apart from the formatting checks). If the `test_driver` files are not in an `example/` directory, I don't think they are executed. [source](https://github.com/flutter/plugin_tools/blob/093a2a5346498fcea29350fdbe01e895330a4a40/lib/src/drive_examples_command.dart#L85-L91)

Even if these tests are moved to an `example/` folder, I don't think CI is setup to run driver tests on web properly. I could be wrong, but the only coverage for such tests in the plugins repo is just a single test in the [.cirrus.yml](https://github.com/flutter/plugins/blob/b96c847d8c18fc49399756a22fcf44d58ad1e48c/.cirrus.yml#L62).

We would probably need to teach the plugin_tools to understand web in a generic manner to fix this.

cc @ditman

**Comment by ditman** [comment] 2020-09-23 20:38
This is correct, flutter/plugins still don't run tests for web. The issue is that we have a megamix of test types (some do flutter test --platform, others flutter drive), and I've been migrating everything to flutter drive.

/cc @nturgut, she also mentioned the same :)

**Comment by ditman** [comment] 2020-09-23 20:39
(PS: I'm not going to assign a priority for this, so we bring it up during Triage tomorrow)

**Comment by nturgut** [comment] 2020-09-23 22:11
As you said there is one test that runs on cirrus ci. So far it was useful to protect against the changes on e2e package (aka integration_test). The majority of the integration tests are on flutter/engine repo.

I'm not a plugin author but for testing e2e package the existing test is enough. (One good addition could have been screenshot testing however, this repo does not have any comparators (such as ImageDiff class we use in engine or goldens.dart on flutter side).

**Comment by ditman** [comment] 2020-09-23 23:24
Platform implementation packages won't be very testable with screenshot testing, because normally those packages don't implement the whole plugin, just the platform-dependent code. For "core" plugins, screenshots could be more usable! (See google_maps_flutter as a core plugin package vs google_maps_flutter_web as a platform implementation package

**Comment by cyanglaz** [comment] 2020-10-09 18:12
Removing the `flake` label as it is not a flake.

**Comment by stuartmorgan** [comment] 2021-05-17 15:58
This is mostly resolved, and there's a newer issue tracking the specific plugins that are left, so closing.

**Closed by stuartmorgan** 2021-05-17 15:58 UTC
Labels: a: tests, passed first triage, plugin, severe: new feature, team
