### ISSUE TITLE
Keyboard is not popping up in Firefox

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#52886] opened 2020-03-19 13:36 UTC
### 1) Keyboard isn't popping up on second tap.
I am using TextFormField in Flutter web. It works as expected in Google Chrome. But when it is launched in Firefox, the keyboard doesn't pop up properly.

When clicked for the first time:
<img src="https://storage.googleapis.com/ifra-github-issues/Screenshot_2020-03-19-18-32-38-362_org.mozilla.firefox.jpg" alt="drawing" width="320" height="700"/>
Works great.

But if I close the keyboard using the Back button and then click on the TextFormField again the keyboard won't pop up. But if I focus on a different TextFormField, then it'll work fine.
<img src="https://storage.googleapis.com/ifra-github-issues/Screenshot_2020-03-19-18-33-12-754_org.mozilla.firefox.jpg" alt="drawing" width="320" height="700"/>
It works fine in Google Chrome.

### 2) Problem while focusing on the text in TextFormField.
Also, when there are multiple lines in the TextFormField, as shown above, I am able to focus on the second line in Chrome but I can only focus on the first line in Firefox. Sorry, I don't think screenshots will be of much use to show this error.

### 3) The cursor isn't rendering properly.
There's one more issue with how the cursor is rendered in Chrome. I wasn't able to figure it out in Fiefox as it wasn't rendering at all.
<img src="https://storage.googleapis.com/ifra-github-issues/Screenshot_2020-03-19-18-30-11-060_com.android.chrome.jpg" alt="drawing" width="320" height="700"/>

I launched the web app in the following phone:
**Device: Mi POCO F1
Android Vesion: 9**

Browser:
**Google Chrome (V80.0.3987.119)
Mozilla Firefox (V68.5.0)**

**Comment by VladyslavBondarenko** [comment] 2020-03-19 14:11
Hi @melwinlobo18 
what flutter version do you use?

**Comment by melwinlobo18** [comment] 2020-03-19 14:53
Flutter version 1.14.6
Channel beta

**Comment by nturgut** [comment] 2020-03-19 22:37
Thanks for filing the issue. Can you please use the master channel and let us know if it is working for you?

**Comment by melwinlobo18** [comment] 2020-03-20 05:22
I switched the channel.
**Flutter version 1.16.2-pre.23
Channel master**

The problems which I mentioned above still exist. Along with it, I noticed a few more issues while selecting text from the TextFormField.

#### Google Chrome
<img src="https://storage.googleapis.com/ifra-github-issues/Screenshot_2020-03-20-10-41-07-730_com.android.chrome.jpg" alt="drawing" width="320" height="700"/>

#### Mozilla Firefox
<img src="https://storage.googleapis.com/ifra-github-issues/Screenshot_2020-03-20-10-42-27-340_org.mozilla.firefox.jpg" alt="drawing" width="320" height="700"/>


I launched the web app in the following phone:
**Device: Mi POCO F1
Android Vesion: 9**

Browser:
**Google Chrome (V80.0.3987.119)
Mozilla Firefox (V68.5.0)**

**Comment by nturgut** [comment] 2020-06-12 16:44
@melwinlobo18 thanks a lot for filing the issue.

It looks like there are different issues here:

(1) Firefox Virtual keyboard, we can use this issue for it.
(2) Browser cursor is visible for multiline fields. It looks like this happens both in Chrome and Firefox. Can you create another issue for this one?
(3) Text measurement @mdebbar is this related to the other text measurement issues?

**Comment by melwinlobo18** [comment] 2020-06-12 16:56
I raised this issue a few months ago. I had forgotten about it. But today I opened [Hack20](https://flutterhackathon.com/url) and realized these issues still exist. Especially the **Firefox Virtual keyboard** issue, I have to reload the page for it work properly again. I hope this issue will be fixed soon.

@nturgut I'll file a new issue for _Browser cursor is visible for multiline fields_ :)

**Comment by TahaTesser** [comment] 2020-08-27 15:28
Hi @melwinlobo18 
Are you still experiencing this issue on latest `master `
If yes, Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment] 2020-10-14 15:05
Hi @melwinlobo18 
Unable to reproduce this issue 

Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 15:05 UTC
Labels: P5, a: text input, browser: firefox, framework, platform-web, waiting for customer response
