### ISSUE TITLE
Images flicker on macOS (Safari) - Flutter Web

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#48681] opened 2020-01-12 18:49 UTC
Images flicker when the widget is scrolled or a button inside the widget gets hovered.

The widget:
```
Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget> [
        Expanded(
            flex: 2,
            child:  Text(
              'label',
              textAlign: TextAlign.left,
              style: TextStyle(
                color: Colors.green,
              ),
            ),
        ),
        Expanded(
          flex: 13,
          child: Card(
            margin: EdgeInsets.only(left: 9.0, right: 9.0),
            color: Colors.black12,
            child: Column( 
              children: <Widget>[
                SizedBox(
                  height: 130,
                  width: 200,
                  child: Stack(
                    children: <Widget>[
                      Positioned.fill(
                        child: FadeInImage.assetNetwork(
                          image: 'path/to/some/image',
                          placeholder: 'images/transparent.png',
                          fit: BoxFit.cover,
                        ),
                      ),
                      Positioned(
                        bottom: 8.0,
                        left: 8.0,
                        right: 8.0,
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          alignment: Alignment.bottomRight,
                          child: Text('label', style: TextStyle(fontSize: 12.0, color: Colors.red), textAlign: TextAlign.right),
                        )
                      ),
                      Positioned(
                        bottom: 0,
                        left: 0,
                        child: HandCursor( 
                          child: IconButton(
                            icon: Icon(
                              Icons.play_circle_outline,
                              size: 34,
                            ),
                            color: Colors.green,
                            onPressed: () {
                               //some actions
                            },
                          ),
                        ),
                      ),
                    ]
                  ),
                )
              ]
            ),
          ),
        ),
      ]
    );
```

I have about 10 of the above in a **ListView** with a horizontal layout.
Every time the button inside is hovered the image looks like reloading and flickers (same as on Chrome when I have the dev tools opened). 

Info about Flutter:

```
Flutter 1.13.9-pre.59 • channel master • https://github.com/flutter/flutter.git
Framework • revision ab36346af6 (22 hours ago) • 2020-01-11 14:20:05 -0500
Engine • revision 3d37d39d95
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 395daaa3ec)
```

**Comment by jonahwilliams** [comment] 2020-01-12 23:31
Duplicate of https://github.com/flutter/flutter/issues/48373

**Closed by jonahwilliams** 2020-01-12 23:31 UTC
