### ISSUE TITLE
print statement doesnt work in ios native plugin

### ISSUE THREAD

**Issue by shyandsy** [flutter/flutter#28856] opened 2019-03-04 22:58 UTC
I am writting the native plugin code for ios, but the print statement doesnt work, and the breakpoint even no work.

 I notice there only one print work located in 
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    print("Before\nAfter\n")  // here
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by Hixie** [comment] 2019-04-02 23:54
Does it work if you use `NSLog`? (https://developer.apple.com/documentation/foundation/1395275-nslog)

**Comment by nilobarp** [comment] 2019-05-22 03:05
Having the same issue. Tried with `NSLog`, also added a new line to it (#13204) but flutter console doesn't show the logs. It is worth mentioning that this is in a plugin project.

**Comment by TahaTesser** [comment] 2020-10-22 12:41
Hi @shyandsy 
Looks like this is fixed https://github.com/flutter/flutter/issues/13204#issuecomment-712511304 
Although still not working for me,  will follow on the up duplicate issue 
```
import Flutter
import UIKit

public class SwiftHelloBetaPlugin: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "hello_beta", binaryMessenger: registrar.messenger())
    let instance = SwiftHelloBetaPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)
  }

  public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
     print("hi!")
    NSLog("Before\nAfter")
    NSLog("\nHello, World!")
    result("iOS " + UIDevice.current.systemVersion)
  }
}

```

Closing as duplicate of https://github.com/flutter/flutter/issues/28856

**Closed by TahaTesser** 2020-10-22 12:41 UTC
Labels: P4, engine
