### ISSUE TITLE
* What went wrong: 'com.google.firebase:firebase-common' has different version for the compile (16.0.3) and runtime (16.1.0) classpath

### ISSUE THREAD

**Issue by VnurtureTechnologies** [flutter/flutter#37460] opened 2019-08-02 06:39 UTC
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'com.google.firebase:firebase-common' has different version for the compile (16.0.3) and runtime (16.1.0) classpath. You should manually set the same version via DependencyResolution
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by BondarenkoStas** [comment] 2019-09-19 14:52
@VnurtureTechnologies Please report if the issue still relevant. Please provide your ```flutter doctor -v``` output, and your Gradle version.

**Comment by iapicca** [comment] 2019-11-11 16:16
Hi @VnurtureTechnologies 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 16:16 UTC
Labels: waiting for customer response
