### ISSUE TITLE
Make an option for Wrap widget to have the Expanded children to fill the remaining space

### ISSUE THREAD

**Issue by FadyQJ** [flutter/flutter#136154] opened 2023-10-08 12:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am creating a custom ChipInput widget similar to how gmail has chips for each email recipient.

I need to use Wrap to make it work, but there is no parameter in Wrap where I can have the last element take the remaining space, instead it puts the last widget on to a new line and expands it to fill the row.

This is the widget in question

```dart
import 'package:flutter/material.dart';

class ChipInput extends StatelessWidget {
  final String label;

  const ChipInput({
    super.key,
    required this.label,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border(
          bottom: BorderSide(
            color: Colors.black,
            width: 1.0,
          ),
        ),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Padding(
              padding: EdgeInsets.only(left: 4, right: 4), // TODO
              child: Text(label)),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(4, 4, 4, 4),
              child: Wrap(
                spacing: 4, // TODO
                runSpacing: 6, // TODO
                children: [
                  ...List<Widget>.generate(16, (value) =>
                    Focus(
                        descendantsAreFocusable: false,
                        canRequestFocus: false,
                        child: InputChip(
                          label: Text("Test Chip $value"),
                          onDeleted: () {},
                        ),
                    )
                  ),
                  Expanded(
                    child: TextField(
                      decoration: InputDecoration(
                        isDense: true,
                        constraints: BoxConstraints(minWidth: 200), // TODO
                        enabledBorder: UnderlineInputBorder(
                          borderSide: BorderSide(color: Colors.transparent),
                        ),
                        focusedBorder: UnderlineInputBorder(
                          borderSide: BorderSide(color: Colors.transparent),
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

![image](https://github.com/flutter/flutter/assets/4512932/bb9f3c02-faae-4597-ac0f-11a1366ae210)

The TextField is put on a new line, but I want it to be added next to the "Test Chip 15" like so

![image](https://github.com/flutter/flutter/assets/4512932/721e2319-fe11-438c-83a1-d0a9785fb01a)

### Proposal

The solution is to add a parameter to the Wrap widget similar to Flexible where we can define if the expanded widget should be done on a new line or not.

In combination with the ConstrainedBox for the Textfield it should achieve the desired effect.

A simpler solution would be to make the Wrap expand on the same line by default and introduce a new child widget for Wrap, WrapNewLine for example where if the user wants to expand said widget on a new line he can wrap it in a WrapNewLine widget which indicated to the Wrap widget that the new widget should be inserted on a new line.

Of course other solutions may be better suited but this proposal is based on my limited knowledge of the inner workings of Flutter.

**Comment by fischerscode** [comment] 2023-10-08 20:44
`Expanded` / `Flexible` can't be placed into an `Wrap`, since they expect a `FlexParentData`.

However, I've create PR  #136161, to propose a new widget `TightWrap` that would solve this use case by trying to fit the child in the current wrap run first. I'd be interested in feedback, esp. from the Flutter team.

<details>
<summary>Copy-Paste Example based on the code above</summary>

To test the PR, one can wrap the `TextField` with a `TightWrap`.

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Center(
          child: ChipInput(label: "test"),
        ),
      ),
    );
  }
}

class ChipInput extends StatelessWidget {
  final String label;

  const ChipInput({
    super.key,
    required this.label,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Padding(
            padding: const EdgeInsets.only(left: 4, right: 4), // TODO
            child: Text(label)),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(4, 4, 4, 4),
            child: Wrap(
              spacing: 4, // TODO
              runSpacing: 6, // TODO
              children: [
                ...List<Widget>.generate(16, (value) =>
                  Focus(
                      descendantsAreFocusable: false,
                      canRequestFocus: false,
                      child: InputChip(
                        label: Text("Test Chip $value"),
                        onDeleted: () {},
                      ),
                  )
                ),
                const TextField(
                  decoration: InputDecoration(
                    isDense: true,
                    constraints: BoxConstraints(minWidth: 200), // TODO
                    enabledBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                    focusedBorder: UnderlineInputBorder(
                      borderSide: BorderSide(color: Colors.transparent),
                    ),
                  ),
                )
              ],
            ),
          ),
        )
      ],
    );
  }
}
```

</details>

**Comment by fischerscode** [comment] 2023-10-08 20:54
Duplicate of #135301

**Closed** 2023-10-09 07:30 UTC
Labels: in triage
