### ISSUE TITLE
Slider notifies "onChangeEnd" twice  when it is over a InkWell/GestureDetector

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#28115] opened 2019-02-18 19:48 UTC
When embedding a Slider inside a InkWell, the Slider fires twice "onChangeEnd" if you start dragging it.
Check this snippet:

``` dart

void main() => runApp(MyAppTeste());

class MyAppTeste extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tests Flutter',
      home: Page(),
    );
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          InkWell(
            onTap: () {
              print("Tapped Inkwell!");
            },
            child: SliderTest(),
          ),
//          SliderTest()
        ],
      ),
    );
  }
}

class SliderTest extends StatefulWidget {
  @override
  _SliderTestState createState() => _SliderTestState();
}

class _SliderTestState extends State<SliderTest> {
  double value = 0;

  @override
  Widget build(BuildContext context) {
    return Slider(
      value: value,
      min: 0,
      max: 100,
      onChanged: (value) {
        setState(() {
          this.value = value;
        });
      },
      onChangeEnd: (value) {
        print("Value selected $value");
      },
    );
  }
}

```

If you just tap somewhere in the slider's "line" verything works fine. But if you drag it, it will fire twict the "onChanceEnd" method.

I also realized the if you drag too fast, it will fires only once.  But users don't use the sliders like that. I believe this has something related to the InkWell/GestureDetector that is behind it....

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17763.316], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code (version 1.30.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-19 07:48
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by shinayser** [comment] 2019-02-19 15:26
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Zoechi the one the post is exactly that. Actually this is a Scaffold. Just embedding it into any MaterialApp will run properly.

**Comment by zoechi** [comment] 2019-02-19 15:31
To be runnable it should include `main() {...}`.
The point is that we shouldn't need to make any assumptions. Just copy-paste and run.
Otherwise there is always room for different behavior.

**Comment by shinayser** [comment] 2019-02-19 15:36
Understood! I've updated the code above with the requirements.

**Comment by zoechi** [comment] 2019-02-19 15:59
Thanks!

I wasn't able to reproduce though.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D42, locale en-AT)
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```
Can you please try with `master` (or `dev`) channel?

```
flutter channel master
flutter doctor
```

**Comment by shinayser** [comment] 2019-02-19 16:12
I just switched to 1.2.2-pre.21 and seems the problem is **gone**. You may close the issue if you want :)
Also, this issue seems related to this same problem: https://github.com/flutter/flutter/issues/18561

**Comment by shinayser** [comment] 2019-02-19 17:58
@zoechi Actually I've posted a wrong code snippet on this issue and tested it on my machine wrongly too... The issue **still persist** on  v1.2.2-pre.21.
I've updated the code snippet above so you can check for yourself.

**Comment by Lootwig** [comment] 2019-02-25 23:15
Facing the same issue with this hierarchy:

MaterialApp > Custom stateless > Scaffold > BlocBuilder > Stack > BlocProvider > Custom stateless > GestureDetector > Stack > Container > Opacity > ListView > Custom stateful > Container > Column > Slider

**Comment by marcglasberg** [comment] 2019-03-21 21:53
https://github.com/flutter/flutter/issues/28961

**Comment by hugocbpassos** [comment] 2019-03-21 22:01
@shinayser Why do you believe it's related to InkWell/GestureDetector? I'm also facing this problem without using any of those.

**Comment by shinayser** [comment] 2019-03-21 22:20
> @shinayser Why do you believe it's related to InkWell/GestureDetector? I'm also facing this problem without using any of those.

You are 100% right.

**Comment by ebeem** [comment] 2019-05-14 23:21
I hope this gets fixed as my issue #18561 was closed by the bot

@hugocbpassos can you tell us what did you use to reproduce the problem? I wrote this issue long time ago, but I remember that this problem is related to `GestureDetector` and you will face it in all widgets that use `GestureDetector` like buttons or inkwells.

it's still not clear whether this is the expected behavior or not anyway, it does not seem like an expected behavior to me.

**Comment by hugocbpassos** [comment] 2019-05-14 23:45
@ebeem As far as I can remember, I wrote an example app to check this. I did wrote another right now, but the problem only happened when using `GestureDetector`/`Inkwell`. I can not tell you whether I poorly tested or part of the bug has been fixed.

**Comment by ebeem** [comment] 2019-05-15 00:02
@hugocbpassos my use case was a `FlatButton` inside of an `InkWell`
this was the reason why I wrote the issue before.

I think `FlatButton` has an `InkWell` child (that's what makes the ripple effect and tab events as well, not sure tho)
inside `InkWell` you can see it uses `GestureDetector` a lot

so my investigation last time led me to believe the problem was with `GestureDetector`
and it's only with `onTapDown` and `onTapUp`.
`onTap` gets fired only once.

However, I am just saying what I remember, it could be wrong.

**Comment by CiriousJoker** [comment] 2019-09-02 11:58
Issue still persists.. Is this going to be fixed anytime soon?

**Comment by JimmySoftLLC** [comment] 2019-10-06 16:20
I have the same problem, slider onChangedEnd fires, sometimes once but often times twice.  I need this to work because I call a method inside onChangeEnd which passes the context.  Then I get a warning that the context is unsafe.

**Comment by JimmySoftLLC** [comment] 2019-10-06 17:08
I have a work around so that my updateSomething does not get called twice.  That keeps me out of the unsafe context problem but the value is not correct that gets sent.  Tapping works ok.
```
onChangeEnd: (double endValue) {
                          if (!hitState) {
                            hitState=true;
                            var endValueToSend = endValue.round();
                            print ('end state ' + endValueToSend.toString());
                            changeUserStoryPriorityUsingSlider(_index, endValueToSend.toInt(),context);
                          }
                        },
```

**Comment by nt4f04uNd** [comment] 2019-10-11 19:44
Having this issue when slider is inside one of the tabs in tab view

**Comment by nt4f04uNd** [comment] 2019-10-11 21:07
I have a case, where `onChangeEnd` called twice only when `onChanged` is called before, so I solved this with such code

```dart
  bool _isUpdateInvoked = false;
  int _callCounter = 0;

 // Drag functions
  void _handleChangeStart(double newValue) async {
    setState(() {
       // some actions....
    });
  }

  void _handleChanged(double newValue) {
    setState(() {
      _isUpdateInvoked = true;
       // some actions....
    });
  }

  void _handleChangeEnd(double newValue) async {
    if (!_isUpdateInvoked) {
      setState(() {
        // some actions....
      });
    } else {
      if (_callCounter == 0) // Ignore first invocation
        _callCounter++; 
      else {
        setState(() {
          _callCounter = 0;
          _isUpdateInvoked = false;
          // some actions....
        });
      }
    }
  }
```

**Comment by theochampion** [comment] 2019-10-14 09:47
still facing the problem as well, any updates on this?

**Comment by shinayser** [comment] 2019-10-14 14:29
Guys, give a +1 on this post so flutte team picks it for fixing.

**Comment by Mavahu** [comment] 2019-11-10 16:04
Experiencing the same bug in my Application :/

**Comment by EArminjon** [comment] 2019-12-01 08:54
> Having this issue when slider is inside one of the tabs in `TabBarView` and multiple children (e.g. two tabs) are present. Maybe scroll controller that is used inside `TabBarView` can cause such issue?

same context for me, bug is present

**Comment by JimmySoftLLC** [comment] 2019-12-01 13:44
Mine is in a card widget that is in a list view in a tab view.  I think the slider widget is just broken.

**Comment by juumixx** [comment] 2020-01-16 12:11
Can confirm this bug when Slider is inside a SingleChildScrollView.

**Comment by liugangnhm** [comment] 2020-02-19 09:56
same issue

**Comment by 0xcodezero** [comment] 2020-03-10 13:45
Same issue 

```
Flutter 1.15.4-pre.82 • channel master • https://github.com/flutter/flutter.git
Framework • revision e481fcae52 (3 weeks ago) • 2020-02-14 22:34:30 -0800
Engine • revision d60f298d9e
Tools • Dart 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)
```

**Comment by evansherry** [comment] 2020-03-12 08:08
Same issue

**Comment by evansherry** [comment] 2020-03-15 15:13
I found that the problem occurred in the settings of HorizontalDragGestureRecognizer and TapGestureRecognizer. The onTapDown, onTapUp of TapGestureRecognizer has been triggered before the gesture swipe. Is there any effective solution?

**Comment by WillCanU** [comment] 2020-05-15 02:06
I found a work around by wrapping the Slider in a GestureDetector and using onTapCancel with a canEnd bool to flag if it can call onChangeEnd. 

The reason for using onTapCancel is because without dragging, onTapCancel will call after onChanged so there is no interference with the onChanged. 

But if you drag, onTapCancel will call first, setting canEnd = false. Directly after that onChangeEnd will call (when we don't want it to), so it's skipped. onChanged will set canEnd = true, for the onChangeEnd we want to trigger. 

code: 

       GestureDetector(
          onTapCancel: () {
            canEnd = false;
          },
          child: Slider(
            value: slVal,
            onChangeEnd: (endPoint) {
              if (canEnd) {
                //Change End logic here 
            }
            },
            onChanged: (value) {
              canEnd = true;
            },
          ),
        );

**Comment by TahaTesser** [comment] 2020-05-29 15:23
```
D/ViewRootImpl@8304ca8[MainActivity](30251): ViewPostIme pointer 0
I/flutter (30251): Value onChangeEnd 0.16767393867924527
D/ViewRootImpl@8304ca8[MainActivity](30251): ViewPostIme pointer 1
I/flutter (30251): Value onChangeEnd 99.30719339622644
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F   • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.5 19F96
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by evansherry** [comment] 2020-06-04 02:28
I use delayed processing onChangeEnd to solve this problem
```
class _FixSliderState extends State<FixSlider> {
  static const duration = Duration(milliseconds: 100);
  DateTime lastOnChangeEnd;
  Timer _timer;

  @override
  Widget build(BuildContext context) {
    return Slider(
      value: widget.value,
      min: widget.min,
      max: widget.max,
      onChangeStart: (double value){
        if(lastOnChangeEnd == null || 
            DateTime.now().difference(lastOnChangeEnd) > duration){
          widget.onChangeStart?.call(value);
        }else{
          _timer?.cancel();
        }
      },
      onChanged: widget.onChanged,
      onChangeEnd: (double value){
        lastOnChangeEnd = DateTime.now();
        delayOnChangeEnd((){
          widget.onChangeEnd?.call(value);
        });
      },
    );
  }

  void delayOnChangeEnd(VoidCallback action){
    _timer?.cancel();
    _timer = Timer(duration, action);
  }
}
```

**Comment by TheWalkingFridge** [comment] 2020-06-06 15:13
Same issue.

**Comment by pinpong** [comment] 2020-06-14 18:35
+1

**Comment by JankoLancer** [comment] 2020-06-25 09:58
I have made gist with minimal reproducible widget tree:
https://dartpad.dartlang.org/dca160bb5917bdbb422cad2024cb6512

**Comment by fzyzcjy** [comment] 2020-08-16 00:04
+1 For even flutter 1.20... Any updates?

**Comment by vanlooverenkoen** [comment] 2020-09-08 10:01
Is there a temporary fix we can use right now?

**Comment by LemonBabyluo** [comment] 2020-09-14 07:46
same issue

**Comment by cbreezier** [comment] 2020-09-15 03:46
@WillCanU I wasn't able to use your proposed workaround successfully - maybe something has changed internally in Flutter?

For me, the `onTapCancel` gets fired after the first `onChangeEnd`. The order I observe is:
start
change
end
cancel
start
change
change
change
end

**Comment by mikeesouth** [comment] 2020-09-17 07:51
I guess that this is a confirmed bug by now and it looks like it's been planned - great! I just wanted to say that I'm also experiencing this with stable flutter (1.20.3) and that it seems to have the same effect on 'onChangeStart' (i.e. that event is also fired multiple times).
I'm currently using a "workaround" that listens to the onChanged event, if the onchanged is called at least once, then the next onChangeEnd is an actual end. Please note that it does not recognize "taps" on the slider thumb or if you press and hold the thumb without moving it. It will only trigger onChangeEnd if the onChange event fires at least once, i.e. the thumb has to be moved (at least a little bit).

```
onChanged: (value) => _sliderChanged = true,
onChangeStart: (value) => _sliderChanged = false,
onChangeEnd: (value) {
  if (!_sliderChanged) return;
  print('onChangeEnd after actual slider movement');
}
```

Keep _sliderChanged in widget state.

**Comment by WieFel** [comment] 2021-01-21 10:06
Same issue. Running Flutter stable 1.22.5

**Comment by daadu** [comment] 2021-03-15 12:55
@WieFel Thanks for the workaround!!

**Comment by Sakorni** [comment] 2021-03-17 14:08
@WieFel, Thanks for your workaround! You're breathtaking!

**Comment by maares** [comment] 2021-03-21 15:50
Unfortunately for me non-of above solutions worked for me, although they worked as great examples for my work around:
```

bool _cancelBugEvent = true;

Slider(
          min: 0.0,
          max: 1.0,
          onChanged: (value) async {
            
          },
          onChangeStart: (value) async {
           
          },
          onChangeEnd: (value) async {
            ///FIXME: https://github.com/flutter/flutter/issues/28115
            
            if (_cancelBugEvent) {
              _cancelBugEvent = false;
            } else if (!_cancelBugEvent) {
              _cancelBugEvent = true;
              //execute code when drag released
            }
            
          };

```

Is there a release plan we can track? Thanks in advance!

**Comment by cirediew** [comment] 2021-03-24 10:32
I'm using `Slider.adaptive` and this problem only occurs on Android (material slider) devices. The cupertino version of the adaptive slider works fine.

<details>
<summary>
flutter doctor
</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/eric/development/flutter
    • Framework revision 8962f6dc68 (13 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eric/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/eric/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/eric/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```
</details>

**Comment by evansherry** [comment] 2021-04-05 11:32
@WieFel  This workaround is not so reliable. 
If you drop the area outside the thumb, then pause for a moment and continue sliding, the print log looks like this

```
onChangeStart: 0.48814937736414643
onChanged: 0.29379905024661296
onChangeEnd: 0.29379905024661296
onHorizontalDragCancel
onChangeStart: 0.29379905024661296
onChanged: 0.2353359415561338
onChanged: 0.23375586014759692
onChanged: 0.23217577873906003
onChangeEnd: 0.23059569733052315
```

Most of the current cases are fine, we can also set a `_complete` flag to control the number of appearances of onChangeStart.

```
onHorizontalDragCancel: () {
  _cancelled = true;
  print('onHorizontalDragCancel');
}
```

```
onChangeStart: (double value) {
  if(_complete){
    print('onChangeStart');
  }
  _complete = false;
  _cancelled = false;
  },
onChanged: () => print('onChanged');,
onChangeEnd: (double value) {
  if(_cancelled) return;
  _complete = true;
  print('onChangeEnd')
  }
```
[dh_slider](https://github.com/evansherry/dh_slider) uses a delay as a workaround, it's not a great way to do it, but it's safer.

**Comment by flaviopessini** [comment] 2021-04-19 20:36
Hello, I am experiencing the same problem with Slider in version 2.0.5 of Flutter. The function is triggered twice.

**Comment by JKRC** [comment] 2021-05-10 04:32
I have the same problem :(( any solution for this?

**Closed** 2021-05-20 23:44 UTC
Labels: P4, customer: crowd, f: material design, found in release: 1.22, found in release: 1.26, framework, has reproducible steps

**Comment by delegate-it** [comment] 2021-07-02 17:17
I am facing the problem too. I have a slider inside tabview. Is there any solution?
