### ISSUE TITLE
Exception: null. The flutter tool cannot access the file or directory.       Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current       user.

### ISSUE THREAD

**Issue by Hitika2000** [flutter/flutter#80193] opened 2021-04-10 14:20 UTC
## Steps to Reproduce
Flutter was working fine but when packages were updated it started throwing this error

## Logs

<details>
<summary>Logs</summary>

```
```

[√] Flutter (Channel master, 2.1.0-13.0.pre.524, on Microsoft Windows [Version 10.0.18363.1440], locale en-IN)
    • Flutter version 2.1.0-13.0.pre.524 at C:\flutter
    • Framework revision 98a9618993 (2 days ago), 2021-04-07 22:34:03 -0700
    • Engine revision cf86823971
    • Dart version 2.13.0 (build 2.13.0-213.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\keval\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file or directory.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current
      user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:778:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:768:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:559:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:386:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:313:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.

</details>

**Comment by iapicca** [comment] 2021-04-10 14:35
possible duplicate of https://github.com/flutter/flutter/issues/70216

**Comment by darshankawar** [comment] 2021-04-12 09:30
Closing this as duplicate of https://github.com/flutter/flutter/issues/70216.
Also see [this](https://github.com/flutter/flutter/issues/73674#issuecomment-758011657) possible workaround.

**Closed by darshankawar** 2021-04-12 09:30 UTC
Labels: in triage
