### ISSUE TITLE
A render exception occurred in the flutter in tabbarview

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#74284] opened 2021-01-20 00:59 UTC
The render exception occurred in the flutter. The background color should have been displayed in tabbarview Color.fromRGBO (242, 242, 244, 1); the color of the block is shown in the place of the Color.fromRGBO (255, 255, 255, 1);

**video**

https://user-images.githubusercontent.com/44134842/105112053-25108f00-5afd-11eb-8f4a-accfe7ae66c2.mp4

**project is**

[message.zip](https://github.com/flutter/flutter/files/5839480/message.zip)

**code is**  

<details>
<summary>code sample</summary>

```dart
class cloudManage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _cloudManage();
  }
}

class _cloudManage extends State<cloudManage>
    with SingleTickerProviderStateMixin {
  TabController tc;

  _cloudManage() {
    this.tc =
        new TabController(length: serverElemMap.values.length, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          padding: EdgeInsets.fromLTRB(
            paddingBorder.toDouble(),
            topMargin.toDouble(),
            paddingBorder.toDouble(),
            10,
          ),
          child: Row(
            children: [
              Expanded(
                child: TabBar(
                  physics: BouncingScrollPhysics(
                      parent: AlwaysScrollableScrollPhysics()),
                  isScrollable: true,
                  tabs: serverElemMap.values
                      .map((value) => TextOrdinary(value.serverName))
                      .toList(),
                  controller: tc,
                ),
              )
            ],
          ),
          alignment: Alignment.centerLeft,
        ),
        Expanded(
          child: Container(
            child: TabBarView(
              physics: BouncingScrollPhysics(
                  parent: AlwaysScrollableScrollPhysics()),
              children: serverElemMap.values.map((e) {
                return Column(
                  children: [
                    ...e.serverUserList.map((e) => _userElem(e)).toList()
                  ],
                );
              }).toList(),
              controller: tc,
            ),
            margin: EdgeInsets.symmetric(horizontal: paddingBorder.toDouble()),
          ),
        ),
      ],
    );
  }
}
```
</details>

dev android is android10 It's a physical machine

I have the same problem with Android 11 AVD

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (6 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17763.1697], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by pedromassangocode** [comment] 2021-01-20 07:35
Hi @au-top 
Can you please provide your `flutter run --verbose`, the actual vs expected results and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? The code you provide seems to be a a big project that makes things hard to find the real issue. Please provide a runnable code that focus on reproducing the issue only. 
Thank you

**Comment by pedromassangocode** [comment] 2021-02-12 10:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-12 10:28 UTC
Labels: in triage, waiting for customer response
