### ISSUE TITLE
Misleading "Used by" section

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#89702] opened 2021-09-09 01:44 UTC
I just noticed that https://github.com/flutter/flutter now has a "Used by" section that looks as follows:

![image](https://user-images.githubusercontent.com/19204050/132608255-8c283478-0144-42cc-b4cd-35e3febcb76a.png)

I think that this is misleading (at least I am not aware of a way of using Flutter as a dependency) or at least unexpected.

---

There are two concerns I have:

1. How is a repo marked as _using_ Flutter? Should this be documented?
2. Is this intended in the first place?

An easy fix would be for a maintainer to disable that section in the repo about settings.

**Comment by bernaferrari** [comment] 2021-09-09 01:49
Duplicate of https://github.com/flutter/flutter/issues/88809
Yes, I believe they will hide it, but the right person with the right access to the Flutter repo needs to see these issues.

**Comment by creativecreatorormaybenot** [comment] 2021-09-09 01:50
GitHub issue search is so bad.. I tried to find an existing issue, as always.

**Comment by stuartmorgan** [comment] 2021-09-09 01:58
Closing as a duplicate.

**Closed by stuartmorgan** 2021-09-09 01:58 UTC
