### ISSUE TITLE
TabBar tabs loses their overlay color when a parent has a color

### ISSUE THREAD

**Issue by Keetz** [flutter/flutter#145595] opened 2024-03-22 14:42 UTC
### Steps to reproduce

Run the code and press the button to set a color on the parent Container.

### Expected results

With no color on the Container the hover color for the tabs is red and they are green when pressed.
I expect the hover and pressed color to still be there when the parent Container gets a color.

### Actual results

The color effects are completely gone from the tabs.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  late final TabController _tabController;

  Color? backgroundColor;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  void changeBackground() {
    setState(() {
      if (backgroundColor == null) {
        backgroundColor = Colors.grey[500];
      } else {
        backgroundColor = null;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          color:
              backgroundColor, // Comment out this and see that the overlay effects are back on the TabBar
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TabBar(
                overlayColor: MaterialStateProperty.resolveWith<Color>(
                  (Set<MaterialState> states) {
                    if (states.contains(MaterialState.hovered)) {
                      return Colors.red;
                    }
                    return Colors.green;
                  },
                ),
                controller: _tabController,
                tabs: const [
                  Tab(child: Text('foo')),
                  Tab(child: Text('bar')),
                ],
              ),
              FilledButton(onPressed: changeBackground, child: const Text('button')),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
me@me-desktop:~/Documents/test$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.3, on Ubuntu 22.04.4 LTS 6.5.0-25-generic, locale en_US.UTF-8)
    • Flutter version 3.19.3 on channel stable at /home/me/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/me/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/me/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/me/android-studio
    • Flutter plugin version 76.3.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2024-03-25 11:31
Hi @Keetz 
Thanks for the report, this looks like it is working as intended.
`Container` decoration is drawn on top of `TabBar` Material. as a result you don't see the overlay color.

To overcome this, use the `ink` widget for the decoration.

```dart
        child: Ink(
          decoration: BoxDecoration(
            color: backgroundColor,
          ),
          child: Column(
```
https://github.com/flutter/flutter/assets/48603081/8918e645-46a7-4b18-b330-0635b08d37a1


Closing as working as intended.

**Closed by TahaTesser** 2024-03-25 11:31 UTC
Labels: framework, f: material design, has reproducible steps, team-design, found in release: 3.19, found in release: 3.21

**Comment by Keetz** [comment] 2024-03-25 11:57
@TahaTesser thanks for your reply.
Is this documented somewhere more in depth? It is really not intuitive why a Container is above some part of its child, like the overlay colors, but not the rest.

Also, why does the button not have this issue? I guess it is because the button itself has an ink/material layer which work as the background?
