### ISSUE TITLE
Tree closed to a bunch of infra failures

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#75021] opened 2021-01-29 20:52 UTC
The flutter master tree is currently closed due to what appear to be a bunch of infra failures:

<img width="1617" alt="Screen Shot 2021-01-29 at 12 49 03 PM" src="https://user-images.githubusercontent.com/19588/106325869-60633a00-6230-11eb-9089-9d9ebe655131.png">

They almost all appear to be mac related.

Not sure of the process here or what information you need, but can someone take a look? Thanks.

**Comment by keyonghan** [comment] 2021-01-29 21:04
All these happened on mac-android bots, we are still investigating.

**Comment by keyonghan** [comment] 2021-01-29 22:24
Mac17-mac19 keeps restarting, causing multiple tasks in zombie status, and finally timeout with infra error.
The cause seems related to salt state that checks the swarming service state to start it. 
We moved the keys out of the salt server to mitigate the issue. 
Now bots come back to a normal state.

**Comment by keyonghan** [comment] 2021-01-29 23:31
Tree is open. Closing here, but with https://github.com/flutter/flutter/issues/75031 to track the root issue.

**Closed by keyonghan** 2021-01-29 23:31 UTC
Labels: P0, team: infra
