### ISSUE TITLE
How to rebuild when enter background.

### ISSUE THREAD

**Issue by loongliu** [flutter/flutter#37002] opened 2019-07-26 09:17 UTC
When app enter background, User can see content through `Recent Tasks` in Android or `MultiTasks` in iOS. There is a feature request that application content need be rebuilt when enter background. Through `WidgetsBindingObserver`, I can achieve this on Android, but on iOS, widget does not be rebuilt.
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  String _state = 'init';

  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        setState(() {
          _state = 'resumed';
          print(_state);
        });
        break;
      case AppLifecycleState.inactive:
        setState(() {
          _state = 'inactive';
          print(_state);
        });
        break;
      case AppLifecycleState.paused:
        setState(() {
          _state = 'paused';
          print(_state);
        });
        break;
      case AppLifecycleState.suspending:
        setState(() {
          _state = 'suspending';
          print(_state);
        });
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          '$_state',
          style: Theme.of(context).textTheme.display1,
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

App shows `inactive` in Android's `Recent Tasks`, which is desired, but shows `resumed` in iOS's `MultiTasks`, which is not desired. The print shows all executing paths are same.

**Maybe the rendering pipeline is stoped before `inactive` event on iOS and before `paused` event on Android?**

**Comment by danspano** [comment] 2019-09-11 01:18
Seems to be a duplicate of #33236

At this time there are no frames rendered from the moment the WidgetsBindingObserver callback fires. An example of using iOS platform code to work around the issue (for certain use cases) is also posted in #33236

**Comment by BondarenkoStas** [comment] 2019-09-21 14:29
Thank you @danspano ! I think it's safe to close the issue. It will stay as referenced in the mentioned one. @loongliu If you disagree, feel free to comment and I will re-open it.

**Closed by BondarenkoStas** 2019-09-21 14:29 UTC
