### ISSUE TITLE
Loading webgl action animations on android phones is very slow

### ISSUE THREAD

**Issue by tianzhiguo123** [flutter/flutter#128319] opened 2023-06-06 09:00 UTC
## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by huycozy** [comment] 2023-06-06 12:04
Hi @tianzhiguo123 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps
- Please attach the timeline trace JSON file since it's related to performance issue. You can find the instructions for it in this issue https://github.com/flutter/flutter/issues/74833.

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by huycozy** 2023-06-06 12:04 UTC
Labels: in triage
