### ISSUE TITLE
Ink widget float above SafeArea in IOS simulator

### ISSUE THREAD

**Issue by codenoobforreal** [flutter/flutter#89208] opened 2021-08-31 07:41 UTC
## Steps to Reproduce

try this dummy code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: ListView(children: [
            Ink(
              width: 20,
              height: 20,
              decoration: const ShapeDecoration(
                color: Colors.black,
                shape: CircleBorder(),
              ),
              child: IconButton(
                icon: const Icon(Icons.arrow_back),
                color: Colors.white,
                onPressed: () {
                  print('do nothing');
                },
                iconSize: 10,
              ),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
            const SizedBox(
              height:400,
              child:Text('box'),
            ),
          ]),
        ),
      ),
    );
  }
}

```

**Expected results:** 
the SafeArea widget will cover the ink widget
**Actual results:** 
![image](https://user-images.githubusercontent.com/18373253/131462735-90ba8747-507f-4f91-aaa9-b808bece0893.png)
![image](https://user-images.githubusercontent.com/18373253/131462760-657b524e-9c47-4eba-b8ec-9b9ea8c9fb9a.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2021-08-31 09:02
Hi @codenoobforreal, can you please provide the output of your `flutter doctor -v`?

Thank you

**Comment by codenoobforreal** [comment] 2021-08-31 09:21
sure!
![image](https://user-images.githubusercontent.com/18373253/131477300-4d778c6c-e121-4733-8834-a890b44f2e17.png)

**Comment by danagbemava-nc** [comment] 2021-08-31 10:21
Hi @codenoobforreal, I am unable to reproduce this issue with the sample you provided. 
See attached video

https://user-images.githubusercontent.com/88313112/131485971-5165347d-1179-4fe0-814e-15f9dac4dde9.mov

**Comment by codenoobforreal** [comment] 2021-08-31 10:35
sorry for the wrong code,try this one.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: ListView(children: [
           /// place it to the left
            Row(
              children: [
                const SizedBox(width: 20),
                Ink(
                  width: 20,
                  height: 20,
                  decoration: const ShapeDecoration(
                    color: Colors.black,
                    shape: CircleBorder(),
                  ),
                  child: IconButton(
                    icon: const Icon(Icons.arrow_back),
                    color: Colors.white,
                    onPressed: () {
                      print('do nothing');
                    },
                    iconSize: 10,
                  ),
                ),
              ],
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
            const SizedBox(
              height: 400,
              child: Text('box'),
            ),
          ]),
        ),
      ),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/18373253/131487769-396df246-1e35-412c-86c7-7b81a1a64781.png)
![image](https://user-images.githubusercontent.com/18373253/131487860-db83c91c-1b4b-4591-91f5-d417bbc78b8c.png)

**Comment by danagbemava-nc** [comment] 2021-08-31 10:46
Hi @codenoobforreal, the issue isn't one with the framework but one with implementation. 
The way the `Ink` widget works is that it paints the `decoration` on the nearest `Material ancestor`. 

Because the closest in this case was the `Scaffold`, that's why it was painted over the `Scaffold`. 

See the `decoration` in the docs below. 

https://api.flutter.dev/flutter/material/Ink-class.html

To solve your issue, wrap either the `Row` or the `Ink` with a `Material` widget.

Closing as this is not an issue with flutter itself. 

If you disagree, kindly leave a comment explaining why and I reopen. 

Thank you

**Closed by danagbemava-nc** 2021-08-31 10:46 UTC
Labels: in triage

**Comment by codenoobforreal** [comment] 2021-08-31 10:52
@danagbemava-nc thanks a lot!
I should read the doc more carefully.
anyway.Thank you for your patience with me who is new to flutter.
