### ISSUE TITLE
Scaffold body doesn't resize after set android:windowFullscreen to true on Android

### ISSUE THREAD

**Issue by kithe-raker** [flutter/flutter#71009] opened 2020-11-22 05:03 UTC
<img width="548" alt="ภาพหน้าจอ 2563-11-21 เวลา 21 40 52" src="https://user-images.githubusercontent.com/54874488/99894676-c83d5780-2cb8-11eb-8690-8667eae850d6.png">
<img width="312" alt="ภาพหน้าจอ 2563-11-21 เวลา 21 40 57" src="https://user-images.githubusercontent.com/54874488/99894680-cb384800-2cb8-11eb-95b2-ad1f33f74dbf.png">

i've got the issues when set
```
 <item name="android:windowFullscreen">true</item>
```
the `MediaQuery.of(context).viewInsets.bottom` always return 0 , then my scaffold's body can not be resized to avoid overlapping the keyboard.

Here is my `flutter doctor -v`

```
[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale th-TH)
    • Flutter version 1.22.1 at /Users/Ouu/documents/Coding/flutter`
    • Framework revision f30b7f4db9 (6 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Ouu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM N920C (mobile)      • 011711ebf1801301                     • android-arm64  • Android 7.0 (API 24)
    • iPhone 8 Plus (mobile) • FD5B6919-6CC9-45BC-ACFA-1DD557AA33C9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
does it has any solution by not removing
` <item name="android:windowFullscreen">true</item>`

**Comment by darshankawar** [comment] 2020-11-23 10:30
@Kitti-pop 
Please provide a complete minimal reproducible code sample that shows the issue. Also specify on which platform are you facing the issue  along with expected and actual behavior.
Thanks.

**Comment by Kitti-pop** [comment] 2020-11-23 16:59
hi @darshankawar  i'm facing this issues only on android platform
here is the issues
[https://drive.google.com/file/d/1aCqqX8iTIHjMqG-sWHJJCQe8PtcznKt3/view?usp=sharing](url)
and i want to make it work like on IOS 
like this
[https://drive.google.com/file/d/1nAPXonF_mGs-hrNSHRAc1LsXMGSVDjl2/view?usp=sharing](url)

**Comment by Kitti-pop** [comment] 2020-11-23 17:00
here are my code in that page
```
 @override
  Widget build(BuildContext context) {
    screenutilInit(context);
    return WillPopScope(
      onWillPop: () => null,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        backgroundColor: Constants.lightPrimary,
        body: ListView(
          children: <Widget>[
            Container(
              height: screenHeightDp,
              width: screenWidthDp,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Align(
                    alignment: Alignment.topRight,
                    child: GestureDetector(
                      child: Container(
                          margin: EdgeInsets.only(top: 20, right: 20),
                          child: IconNeumorBox(
                              borderRadius: 20,
                              depth: 3,
                              icon: Icons.home,
                              iconColor: Color(0xffff6666),
                              height: 37,
                              width: 50)),
                      onTap: () {
                        nav.push(context, DraftAndPublishMainstrem());
                      },
                    ),
                  ),
                  Container(
                    height: screenHeightDp / 1.9,
                    child: PageView(
                      children: [SignUp(), SignIn()],
                    ),
                  ),
                  Align(
                    alignment: Alignment.bottomCenter,
                    child: Container(
                        padding: const EdgeInsets.all(10.0),
                        child: Text(
                          "By continuing, you agree to\nBanna’s Terms of Service, Privacy policy.",
                          textAlign: TextAlign.center,
                        )),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by Kitti-pop** [comment] 2020-11-23 17:16
i've tried to remove the status bar by add `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);` before `runApp` in `void main`
it look great, but when i open keyboard the keyboard the status bar show again that the reason why i add 
`<item name="android:windowFullscreen">true</item>` but got the above issues instead.

**Comment by darshankawar** [comment] 2020-11-24 06:38
@Kitti-pop 
In which file are you setting the `android:windowFullScreen` ? 
Check [this](https://github.com/flutter/flutter/issues/51165) issue and see if setting the above property in styles.xml works for you.

**Comment by Kitti-pop** [comment] 2020-11-24 07:39
> @Kitti-pop
> In which file are you setting the `android:windowFullScreen` ?
> Check [this](https://github.com/flutter/flutter/issues/51165) issue and see if setting the above property in styles.xml works for you.

i've set  `android:windowFullScreen` in `styles.xml` file 
Yeah it work status bar is completely disappeared , but i can't scroll when open keyboard on android platform when set `android:windowFullScreen` to `true`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting -->
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowFullscreen">true</item> 
    </style>
</resources>

```

**Comment by darshankawar** [comment] 2020-11-24 11:06
@Kitti-pop 
Added the said property in `styles.xml` and used sample from [this](https://github.com/flutter/flutter/issues/51165#issue-568726209) issue and saw that when textfield is tapped, it opens the keyboard and scaffold resizes properly.

I couldn't use your code sample since it contains lot of custom properties and widgets. Please provide a code sample that we can simply copy paste and run in IDE to see the issue.

**Comment by Kitti-pop** [comment] 2020-11-24 11:24
@darshankawar 
yeah, i've already add that property to `styles.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:windowFullscreen">true</item>
    </style>

    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowFullscreen">true</item> 
    </style>
</resources>
```
and use sample from [that](https://github.com/flutter/flutter/issues/51165#issue-568726209) issue
but still got the same [issue](https://drive.google.com/file/d/1MQK7pYDr7vGLh2ILoPRwoVKWwDQ8Ffe4/view?usp=sharing)

**Comment by darshankawar** [comment] 2020-11-24 13:27
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

**Comment by darshankawar** [comment] 2020-11-24 13:30
Similar to [this](https://github.com/flutter/flutter/issues/51165) closed issue.

**Comment by maheshmnj** [comment] 2022-12-02 05:15
Hi @kithe-raker, I verified the issue on the latest master channel and I see scaffold resizes properly after  modifying the styles.xml as per https://github.com/flutter/flutter/issues/71009#issuecomment-732859195

https://user-images.githubusercontent.com/31410839/205219936-68e307cb-2e4d-4e33-890e-e402ca5d5a45.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing since this is not reproducible, In case you still encounter the problem, Please feel free to comment on this issue and we will reopen it.

**Closed by maheshmnj** 2022-12-02 05:15 UTC
Labels: platform-android, framework, f: material design, passed first triage, a: layout, has reproducible steps, found in release: 1.22
