### ISSUE TITLE
[linux] RangeSlider scheduler exception on official example

### ISSUE THREAD

**Issue by dferrarigrowtech** [flutter/flutter#144933] opened 2024-03-11 15:22 UTC
### Steps to reproduce

1. Run `flutter create --sample=material.RangeSlider.1 mysample` on a linux machine
2. `flutter run -d linux`

### Expected results

No runtime error.

### Actual results

<details>
<summary> `flutter run -d linux --verbose` </summary>

```console
[   +8 ms] executing: uname -m
[   +6 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +39 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +69 ms] Skipping pub get: version match.
[ +122 ms] Generating /home/damiano/Desktop/mysample/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +70 ms] No packages with native assets. Skipping native assets compilation.
[   +1 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/damiano/Desktop/mysample/.dart_tool/package_config_subset}
[  +44 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +1 ms] /home/damiano/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /home/damiano/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/home/damiano/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/2e4ba9c6fb499ccd4e81420543783cc7267ae406/ --output-dill /tmp/flutter_tools.WNTAWF/flutter_tool.YOPLXG/app.dill --packages
/home/damiano/Desktop/mysample/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/26c1224f28ba1925f2521c2679048535.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +18 ms] Building Linux application...
[   +6 ms] <- compile package:mysample/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/damiano/Desktop/mysample/linux
[  +17 ms] -- Configuring done
[   +3 ms] -- Generating done
[   +7 ms] -- Build files have been written to: /home/damiano/Desktop/mysample/build/linux/x64/debug
[   +4 ms] executing: ninja -C build/linux/x64/debug install
[   +5 ms] ninja: Entering directory `build/linux/x64/debug'
[+1149 ms] [1/5] Generating /home/damiano/Desktop/mysample/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/damiano/Desktop/mysample/linux/flutter/ephemeral/flutter_linux/flutter_linux.h,
_phony_
[   +2 ms] [   +7 ms] executing: uname -m
[        ] [   +7 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +14 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +52 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +21 ms] Initializing file store
[        ] [   +3 ms] Done initializing file store
[        ] [  +26 ms] Skipping target: native_assets
[        ] [   +1 ms] Skipping target: gen_localizations
[        ] [   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +301 ms] Skipping target: unpack_linux
[        ] [ +205 ms] Skipping target: kernel_snapshot
[        ] [ +141 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +5 ms] Done persisting file store
[        ] [   +2 ms] build succeeded.
[        ] [   +4 ms] "flutter assemble" took 773ms.
[        ] [  +78 ms] ensureAnalyticsSent: 76ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +322 ms] [2/5] Building CXX object CMakeFiles/mysample.dir/flutter/generated_plugin_registrant.cc.o
[  +24 ms] [3/5] Building CXX object CMakeFiles/mysample.dir/my_application.cc.o
[  +83 ms] [4/5] Linking CXX executable intermediates_do_not_run/mysample
[        ] [4/5] Install the project...
[   +2 ms] -- Install configuration: "Debug"
[  +15 ms] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/mysample
[        ] -- Set runtime path of "/home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/mysample" to "$ORIGIN/lib"
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +49 ms] -- Up-to-date: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/lib
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[   +2 ms] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +2 ms] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +43 ms] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin.json
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/damiano/Desktop/mysample/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[   +7 ms] Building Linux application... (completed in 1,753ms)
[ +171 ms] VM Service URL on device: http://127.0.0.1:34641/FlJeftpFG4k=/
[   +2 ms] Caching compiled dill
[  +66 ms] Connecting to service protocol: http://127.0.0.1:34641/FlJeftpFG4k=/
[  +87 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:34641/FlJeftpFG4k=/.
[  +61 ms] DDS is listening at http://127.0.0.1:39483/KMq6Bgojlv0=/.
[  +30 ms] Successfully connected to service protocol: http://127.0.0.1:34641/FlJeftpFG4k=/
[  +27 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device (file:///tmp/mysampleSEXHLM/mysample/)
[   +1 ms] Updating assets
[  +59 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:mysample/main.dart a6f1fd0a-05f2-4672-9bf0-a26deae599ff
[        ] <- a6f1fd0a-05f2-4672-9bf0-a26deae599ff
[   +1 ms] Bundle processing done.
[  +59 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 63ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x56a425cad690.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on Linux is available at: http://127.0.0.1:39483/KMq6Bgojlv0=/
[ +183 ms] ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
                    The following _TypeError was thrown during a scheduler callback:
                    Null check operator used on a null value
                    
                    When the exception was thrown, this was the stack:
                    #0      _RenderRangeSlider.assembleSemanticsNode (package:flutter/src/material/range_slider.dart:1702:28)
                    #1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4962:13)
                    #2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
                    #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
                    #4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
                    #5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
                    #6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
                    #7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
                    #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
                    #9      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4666:16)
                    #10     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3630:25)
                    #11     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
                    #12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
                    #13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:589:25)
                    #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
                    #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
                    #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
                    #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
                    #18     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
                    #22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
                    (elided 3 frames from class _Timer and dart:async-patch)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +1 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:39483/KMq6Bgojlv0=/
[  +24 ms] Another exception was thrown: Bad state: Future already completed
[+5894 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///tmp/mysampleSEXHLM/mysample/)
[ +251 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

[   +1 ms] "flutter run" took 9,087ms.
[  +23 ms] ensureAnalyticsSent: 22ms
[        ] Running 1 shutdown hook
[  +16 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [RangeSlider].

void main() => runApp(const RangeSliderExampleApp());

class RangeSliderExampleApp extends StatelessWidget {
  const RangeSliderExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('RangeSlider Sample')),
        body: const RangeSliderExample(),
      ),
    );
  }
}

class RangeSliderExample extends StatefulWidget {
  const RangeSliderExample({super.key});

  @override
  State<RangeSliderExample> createState() => _RangeSliderExampleState();
}

class _RangeSliderExampleState extends State<RangeSliderExample> {
  RangeValues _currentRangeValues = const RangeValues(40, 80);

  @override
  Widget build(BuildContext context) {
    return RangeSlider(
      values: _currentRangeValues,
      max: 100,
      divisions: 5,
      labels: RangeLabels(
        _currentRangeValues.start.round().toString(),
        _currentRangeValues.end.round().toString(),
      ),
      onChanged: (RangeValues values) {
        setState(() {
          _currentRangeValues = values;
        });
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on Ubuntu 22.04.4 LTS 6.5.0-25-generic, locale en_US.UTF-8)
    • Flutter version 3.19.3 on channel stable at /home/damiano/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (4 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/damiano/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/damiano/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.25.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/damiano/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-12 07:55
Hi @dferrarigrowtech, this issue was initially reported in https://github.com/flutter/flutter/issues/141953 and has since been fixed by https://github.com/flutter/flutter/pull/141965. This wasn't limited to linux only.

I just tested on the stable and master channels and while it reproduced on stable, it didn't reproduce on master. Per our triage policy, I'll be closing this since it has been fixed on the `master` channel. 

If you do run into this issue on the `master` channel, kindly leave a comment below with the version and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2024-03-12 07:55 UTC
Labels: in triage
