### ISSUE TITLE
Part 2 of tutorial refers to method buildRows that does not exist

### ISSUE THREAD

**Issue by rwprice31** [flutter/flutter#101442] opened 2022-04-06 18:53 UTC
Follow the tutorial, buildRows as referenced in Step 4 does not exist from previous code nor in the code that is supposed to be the gold code for this tutorial

**Comment by darshankawar** [comment] 2022-04-07 06:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/100362

**Closed by darshankawar** 2022-04-07 06:41 UTC
Labels: in triage
