### ISSUE TITLE
App eventually crash when using google maps flutter

### ISSUE THREAD

**Issue by osmartakashi** [flutter/flutter#121548] opened 2023-02-27 21:42 UTC
Hello, I´m working on an app that uses the google maps plugin but eventually the app crashes, and in the debug console has an exception message.
Here is the sample code to reproduce the issue:

<details>
<summary>code sample</summary>

### main.dart

```dart
import 'package:flutter/material.dart';
import 'package:poc_geral/mapa_widget.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[MapaWidget()],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

### MapaWidget

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapaWidget extends StatefulWidget {
  final LatLng posicaoInicialMapa;
  final double zoomInicial;
  final Map<MarkerId, Marker>? markers;

  MapaWidget({
    Key? key,
    this.posicaoInicialMapa =
        const LatLng(37.42796133580664, -122.085749655962),
    this.zoomInicial = 18.5446,
    this.markers,
  }) : super(key: key);

  @override
  State<MapaWidget> createState() => _MapaWidgetState();
}

class _MapaWidgetState extends State<MapaWidget> {
  final Completer<GoogleMapController> _controller = Completer();

  LatLngBounds _createBounds(List<LatLng> positions) {
    final southwestLat = positions.map((p) => p.latitude).reduce(
        (value, element) => value < element ? value : element); // smallest
    final southwestLon = positions
        .map((p) => p.longitude)
        .reduce((value, element) => value < element ? value : element);
    final northeastLat = positions.map((p) => p.latitude).reduce(
        (value, element) => value > element ? value : element); // biggest
    final northeastLon = positions
        .map((p) => p.longitude)
        .reduce((value, element) => value > element ? value : element);
    return LatLngBounds(
        southwest: LatLng(southwestLat, southwestLon),
        northeast: LatLng(northeastLat, northeastLon));
  }

  LatLngBounds _bounds(Set<Marker> markers) {
    return _createBounds(markers.map((m) => m.position).toList());
  }

  _onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
//TODO: Colocamos essa verificação de forma provisória, da forma que está não vai exibir a distãncia da localização do usuário até o restaurante
    if (widget.markers != null &&
        widget.markers!.length > 1 &&
        widget.posicaoInicialMapa.latitude > 0 &&
        widget.posicaoInicialMapa.longitude > 0) {
      try {
        controller.animateCamera(
          CameraUpdate.newLatLngBounds(
            _bounds(Set<Marker>.of(widget.markers!.values)),
            50,
          ),
        );
      } catch (_) {}
    }
  }

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      mapType: MapType.normal,
      initialCameraPosition: CameraPosition(
        target: widget.posicaoInicialMapa,
        zoom: widget.zoomInicial,
      ),
      onMapCreated: _onMapCreated,
      markers:
          widget.markers != null ? Set<Marker>.of(widget.markers!.values) : {},
      compassEnabled: false,
      mapToolbarEnabled: false,
      myLocationButtonEnabled: false,
      buildingsEnabled: false,
      zoomControlsEnabled: false,
    );
  }
}
```
</details>

Below is the error message when trying to open the map. Note that the map open up but with an error behind.

```
[  +26 ms] W/ziparchive(24782): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000001d/GoogleCertificates.dm': No such file or
directory
[   +3 ms] W/ziparchive(24782): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000001d/GoogleCertificates.dm': No such file or        
directory
[ +117 ms] I/SnapshotHandler(24782): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.poc_geral, using defaults.
[   +8 ms] W/MobStoreFlagStore(24782): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.poc_geral, may result in 
stale flags.
[   +1 ms] W/MobStoreFlagStore(24782): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed:
pkg=com.example.poc_geral, sha256=[46d835e8c0c1a50229bdb1dfaf47880aaef9ac4289b7638392a045d73d546e25], atk=false, ver=230413047.true (go/gsrlt)
[   +2 ms] W/MobStoreFlagStore(24782):  at ajq.s(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):3)
[   +1 ms] W/MobStoreFlagStore(24782):  at ajq.get(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +3 ms] W/MobStoreFlagStore(24782):  at ala.g(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +2 ms] W/MobStoreFlagStore(24782):  at ys.d(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):1)
[   +1 ms] W/MobStoreFlagStore(24782):  at yu.run(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):0)
[   +1 ms] W/MobStoreFlagStore(24782):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
[   +1 ms] W/MobStoreFlagStore(24782):  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
[   +2 ms] W/MobStoreFlagStore(24782):  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)    
[   +1 ms] W/MobStoreFlagStore(24782):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[        ] W/MobStoreFlagStore(24782):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[        ] W/MobStoreFlagStore(24782):  at java.lang.Thread.run(Thread.java:1012)
[        ] W/MobStoreFlagStore(24782): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.poc_geral,
sha256=[46d835e8c0c1a50229bdb1dfaf47880aaef9ac4289b7638392a045d73d546e25], atk=false, ver=230413047.true (go/gsrlt)
[   +1 ms] W/MobStoreFlagStore(24782):  at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
[   +1 ms] W/MobStoreFlagStore(24782):  at android.os.Parcel.createException(Parcel.java:2995)
[   +1 ms] W/MobStoreFlagStore(24782):  at android.os.Parcel.readException(Parcel.java:2978)
[   +2 ms] W/MobStoreFlagStore(24782):  at android.os.Parcel.readException(Parcel.java:2920)
[   +2 ms] W/MobStoreFlagStore(24782):  at ff.c(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +2 ms] W/MobStoreFlagStore(24782):  at ru.a(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):4)
[   +1 ms] W/MobStoreFlagStore(24782):  at jl.e(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +1 ms] W/MobStoreFlagStore(24782):  at kk.t(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +2 ms] W/MobStoreFlagStore(24782):  at kk.u(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):3)
[   +1 ms] W/MobStoreFlagStore(24782):  at kk.e(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):2)
[   +1 ms] W/MobStoreFlagStore(24782):  at ko.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@230413047@23.04.13 (190800-0):69)
[   +7 ms] W/MobStoreFlagStore(24782):  at android.os.Handler.dispatchMessage(Handler.java:102)
[   +1 ms] W/MobStoreFlagStore(24782):  at android.os.Looper.loopOnce(Looper.java:201)
[        ] W/MobStoreFlagStore(24782):  at android.os.Looper.loop(Looper.java:288)
[  +14 ms] W/MobStoreFlagStore(24782):  at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by danagbemava-nc** [comment] 2023-02-28 07:52
Hi @osmartakashi, kindly share the logs you get when the app crashes. 

Please also provide the output of `flutter doctor -v` as well as the version of `google_maps_flutter` & `google_maps_flutter_android` that you're using. 

Also, do you experience the crash in release mode or is it only in debug mode, what device(s) do you experience the crash on? 

BTW, the error you posted above is being tracked in https://github.com/flutter/flutter/issues/109115

**Comment by osmartakashi** [comment] 2023-02-28 13:16
Sorry, here is the flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1265], locale pt-BR)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\osmar\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\osmar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.57

[√] HTTP Host Availability
    • All required HTTP hosts are available

Here is the version of the plugins:
google_maps_flutter_android-2.4.6
google_maps_flutter-2.2.4

**Comment by danagbemava-nc** [comment] 2023-02-28 14:05
Hi @osmartakashi, can you upgrade to the latest version of flutter to see if you still experience the crash? 

Please also provide the full output of `flutter run -v` with the full crash log. The output may be huge so kindly put it into a .txt or .log file and attach it here. 

Thank you

**Comment by osmartakashi** [comment] 2023-02-28 17:46
Hello, after upgrade to the latest version of flutter the error persits. I don´t know what to do from now, it´s really frustrating. The app doesn´t crash everytime but only a few times. The error in the log appears all the time, here the same log after upgrade flutter:

`I/DynamiteModule(15386): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
2
W/ziparchive(15386): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000002a/GoogleCertificates.dm': No such file or directory
I/SnapshotHandler(15386): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#br.com.grupotrigo.gurume, using defaults.
W/MobStoreFlagStore(15386): Unable to update local snapshot for com.google.android.libraries.consentverifier#br.com.grupotrigo.gurume, may result in stale flags.
W/MobStoreFlagStore(15386): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=br.com.grupotrigo.gurume, sha256=[b8004b1b920035bc13192198178663fe88e73930c9386349fa1d0a8e233c4ed5], atk=false, ver=230617047.true (go/gsrlt)
W/MobStoreFlagStore(15386): 	at ajp.s(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):3)
W/MobStoreFlagStore(15386): 	at ajp.get(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):2)
W/MobStoreFlagStore(15386): 	at akz.g(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):2)
W/MobStoreFlagStore(15386): 	at yr.c(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):1)
W/MobStoreFlagStore(15386): 	at yt.run(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):0)
W/MobStoreFlagStore(15386): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
W/MobStoreFlagStore(15386): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore(15386): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore(15386): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/MobStoreFlagStore(15386): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/MobStoreFlagStore(15386): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore(15386): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=br.com.grupotrigo.gurume, sha256=[b8004b1b920035bc13192198178663fe88e73930c9386349fa1d0a8e233c4ed5], atk=false, ver=230617047.true (go/gsrlt)
W/MobStoreFlagStore(15386): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
W/MobStoreFlagStore(15386): 	at android.os.Parcel.createException(Parcel.java:2995)
W/MobStoreFlagStore(15386): 	at android.os.Parcel.readException(Parcel.java:2978)
W/MobStoreFlagStore(15386): 	at android.os.Parcel.readException(Parcel.java:2920)
W/MobStoreFlagStore(15386): 	at ff.c(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):2)
W/MobStoreFlagStore(15386): 	at ru.a(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):4)
W/MobStoreFlagStore(15386): 	at jl.e(:com.google.android.gms.dynamite_mapsdynamite@230617047@23.06.17 (190800-0):2)
`

**Comment by danagbemava-nc** [comment] 2023-03-01 06:58
Hi @osmartakashi, I may be misunderstanding the definition of crash you're using. 

What happens when the app crashes for you? 

- Does it just log the error you've posted above?
- Does the entire application exit? 
- Does the map become unresponsive?
- or something else

**Comment by osmartakashi** [comment] 2023-03-01 12:19
> Hi @osmartakashi, I may be misunderstanding the definition of crash you're using.
> 
> What happens when the app crashes for you?
> 
> * Does it just log the error you've posted above?
> * Does the entire application exit?
> * Does the map become unresponsive?
> * or something else

Just to clarify, as I mentioned above the app doesn´t crash everytime you use it. It crashes eventually when load the widget called "MapaWidget". Although the app doesn´t crash all the time, the log message is displayed everytime you enter in the screen that uses the "MapaWidget".
When the crash ocurres the app exit suddenly, but the log error is the same.
 Please let me know if its clrear now. Thank you!

**Comment by danagbemava-nc** [comment] 2023-03-01 12:47
Yes, it's clearer now. 

What device(s) are you experiencing the crash on and how long does it usually take for it to crash? I'm trying to reproduce the issue on my end but so far I haven't been able to

**Comment by osmartakashi** [comment] 2023-03-01 17:49
There is not a specific device, I observe that in all pluged devices or emulators the problem ocurres. I atached a video that shows exactly the moment the problem happens.
[2023-03-01 14-42-59.zip](https://github.com/flutter/flutter/files/10863960/2023-03-01.14-42-59.zip)

**Comment by danagbemava-nc** [comment] 2023-03-02 06:26
Yhh, this is a duplicate of https://github.com/flutter/flutter/issues/109115. 

Kindly subscribe to the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-03-02 06:26 UTC
Labels: in triage
