### ISSUE TITLE
[Google_maps]After change BitmapDescriptor.fromBytes to BitmapDescriptor.bytes app crash

### ISSUE THREAD

**Issue by PrzemyslawPluszowy** [flutter/flutter#149183] opened 2024-05-28 15:00 UTC
### Steps to reproduce

![image](https://github.com/flutter/flutter/assets/113164695/7a5f5993-67a4-467c-a3d5-cf97ff900c5f)
this func work good but if i change to BitmapDescriptor.bytes(imageToBytesUint8List); 
i have this error:
![image](https://github.com/flutter/flutter/assets/113164695/2bac9358-18c0-415a-aa71-76b037a9b69b)

What is wrong?

### Expected results

Need find solution for this error

### Actual results
```

E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): Failed to handle method call
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): java.lang.IllegalArgumentException: Cannot interpret [bytes, {bitmapScaling=auto, byteData=[B@420caa1, imagePixelRatio=1.0}] as BitmapDescriptor
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugins.googlemaps.Convert.toBitmapDescriptor(Convert.java:71)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugins.googlemaps.Convert.interpretMarkerOptions(Convert.java:452)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugins.googlemaps.MarkersController.addMarker(MarkersController.java:195)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugins.googlemaps.MarkersController.addMarkers(MarkersController.java:41)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMethodCall(GoogleMapController.java:385)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at android.os.Handler.handleCallback(Handler.java:900)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#plugins.flutter.dev/google_maps_android_3(18423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
 static generateCustomMarkersIconFromPath(String? path) async {
    try {
      if (path == null || path.isEmpty) {
        return BitmapDescriptor.defaultMarker;
      }
      Uint8List bytes = File(path).readAsBytesSync();
      bytes = (_resizeImage(bytes, 140, 140))!;

      ui.Image image = await _convertImageFromUint8ListToCanvasImage(bytes);
      final generatedImage = await _drawCanvas(image);
      final ByteData? imageToBytes =
          await generatedImage.toByteData(format: ui.ImageByteFormat.png);
      if (imageToBytes == null) {
        return BitmapDescriptor.defaultMarker;
      }
      final Uint8List imageToBytesUint8List = imageToBytes.buffer.asUint8List();
      return BitmapDescriptor.bytes(imageToBytesUint8List);
    } catch (e) {
      return BitmapDescriptor.defaultMarker;
    }
  }

  static Future<ui.Image> _drawCanvas(ui.Image image) async {
    ui.PictureRecorder recorder = ui.PictureRecorder();
    Canvas canvasRecord = Canvas(recorder);
    PinCanavasDraw pinCanvasDraw = PinCanavasDraw(image: image);
    pinCanvasDraw.paint(canvasRecord, const Size(200, 200));
    var genratedImage = await recorder.endRecording().toImage(200, 200);
    return genratedImage;
  }

  static Uint8List? _resizeImage(Uint8List data, width, height) {
    Uint8List? resizedData = data;
    ui_image.Image? img = ui_image.decodeImage(data);
    ui_image.Image resized =
        ui_image.copyResize(img!, width: width, height: height);
    resizedData = Uint8List.fromList(ui_image.encodePng(resized));
    return resizedData;
  }

  static Future<ui.Image> _convertImageFromUint8ListToCanvasImage(
      Uint8List img) async {
    final Completer<ui.Image> completer = Completer();
    ui.decodeImageFromList(img, (ui.Image img) {
      return completer.complete(img);
    });
    return completer.future;
  }
}

class PinCanavasDraw extends CustomPainter {
  PinCanavasDraw({
    required this.image,
  });

  ui.Image image;

  @override
  void paint(Canvas canvas, Size size) async {
    Paint paint1 = Paint()
      ..color = const Color.fromARGB(163, 0, 0, 0).withOpacity(0.8)
      ..strokeWidth = 1
      ..style = PaintingStyle.fill;
    canvas.drawRect(const Rect.fromLTWH(23, 23, 154, 154), paint1);
    Path pathPin = Path()
      ..moveTo(100, 200)
      ..lineTo(80, 170)
      ..lineTo(120, 170)
      ..close();
    Path pathShadow = Path()..addRect(const Rect.fromLTWH(23, 23, 154, 154));
    canvas.drawPath(pathPin, paint1);
    canvas.drawShadow(pathShadow, const Color.fromARGB(255, 0, 0, 0), 3, false);

    canvas.drawImage(image, const Offset(30, 30), Paint());
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-05-29 08:07
@PrzemyslawPluszowy Can you provide us a runnable reproducible code sample in properly formatted text so that we can directly use it and verify at our end ? Providing code screenshot isn't much helpful.

**Comment by PrzemyslawPluszowy** [comment] 2024-05-29 08:46
done

**Comment by PrzemyslawPluszowy** [comment] 2024-05-29 08:59
another error after migration to flutter maps 2.6.1 in another project
when i'm back to .fromAssetImage all work fine

```dart

static Future<BitmapDescriptor> _createIcon(MapPinType type) async {
    return await BitmapDescriptor.asset(
      const ImageConfiguration(
        devicePixelRatio: 2.5,
        size: Size(28, 28),
      ),
      type.getPathIcon(),
    );
  }
}

enum MapPinType {
  accident,
  towing,
  delivery;

  String getPathIcon() {
    switch (this) {
      case MapPinType.accident:
        return Assets.images.iconMapCrashPng.path;
      case MapPinType.towing:
        return Assets.images.garageMapIcon.path;
      case MapPinType.delivery:
        return Assets.images.iconMapHome.path;
    }
  }
}
```
![image](https://github.com/flutter/flutter/assets/113164695/07d8041e-caef-4095-9d05-bd8d71c894ad)

**Comment by darshankawar** [comment] 2024-05-29 11:49
> ```dart
> static generateCustomMarkersIconFromPath(String? path) async {
> ```

@PrzemyslawPluszowy How are you calling this method ? Can you provide us complete code (ex: main.dart) so that we can simply copy paste and verify this further ?




> another error after migration to flutter maps 2.6.1 in another project

What version you were on earlier before upgrading to 2.6.1 ? 
Also, this issue I was able to replicate with the help of another [issue](https://github.com/flutter/flutter/issues/149226#issue-2322270554).

**Comment by PrzemyslawPluszowy** [comment] 2024-05-29 11:57
this is the same issue https://github.com/flutter/flutter/issues/149226#issue-2322270554

**Comment by stuartmorgan** [comment] 2024-05-29 18:58
This is an unintended effect of the way the federated change to add the new formats was rolled out. The new formats won't be supported until https://github.com/flutter/packages/pull/6826 lands.

@jokerttu Could you do a new PR ASAP to remove the deprecation notice? We can re-add it after the implementation PRs have landed.

**Comment by stuartmorgan** [comment] 2024-05-29 21:17
Re-opening as the crash will still happen if people use the new methods; removing the deprecation should just reduce the chances of people starting to use them before the implementation lands.

> Should those be reverted as well, before [flutter/packages#6826](https://github.com/flutter/packages/pull/6826) lands.

Let's see how quickly the implementations land; not actively pushing people to the not-yet-supported versions should help a lot.

(In retrospect, yes, we should have added the class without public constructors first, then added support for them, then added the constructors and the deprecations.)

**Comment by MMoarales** [comment] 2024-06-03 10:54
Same problem here, someone has any solution for this ?

**Comment by stuartmorgan** [comment] 2024-06-03 11:33
The solution is not to use the new constructors until https://github.com/flutter/packages/pull/6826 lands.

**Comment by MMoarales** [comment] 2024-06-03 12:11
Ok, got it, thank you!!!

**Comment by SkimoBen** [comment] 2024-06-19 16:58
One thing I've noticed when using `BitmapDescriptor.fromAssetImage()` is that the marker sizing ends up being totally different on android Vs. iOS / chrome. So like everyone else has mentioned, using the _other_ deprecated method `return BitmapDescriptor.fromBytes(resizedData);` Seems like the best solution currently. 

It will be really awesome if `BitmapDescriptor.asset()` _just works_ soon.

**Comment by jokerttu** [comment] 2024-06-20 06:23
https://github.com/flutter/packages/pull/6826 is now landed and new methods, `BitmapDescriptor.asset()` and `BitmapDescriptor.bytes()` are implemented for each platform, and can be used after using after plugin versions are updated to latest. 
Latest version of google_maps_flutter 2.7.0 now also exposes new AssetMapBitmap and BytesMapBitmap classes.

**Closed** 2024-06-20 09:45 UTC
Labels: c: regression, p: maps, package, team-ecosystem, P1, triaged-ecosystem
