### ISSUE TITLE
iOS Simulator isn't displayed in Flutter Device Section

### ISSUE THREAD

**Issue by acbelter** [flutter/flutter#89256] opened 2021-08-31 22:46 UTC
## Problem

Launched iOS Simulator isn't displayed in the devices list. After clicking on "Open iOS Simulator", iOS Simulator window just becomes the foreground window.

![image](https://user-images.githubusercontent.com/4152363/131581118-083d8ac1-451c-4bf6-92e1-e31289f186f8.png)

flutter doctor -v output:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.14.4 18E227 darwin-x64, locale en-RU)
    • Flutter version 2.2.3 at /Users/acbelter/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/acbelter/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio 4.0 Stable.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.0 Stable.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159
```

</details>

flutter emulators -v output:

<details> 
<summary>logs</summary> 
	
```console
[ +103 ms] executing: sysctl hw.optional.arm64
[  +21 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +9 ms] executing: [/Users/acbelter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [/Users/acbelter/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +22 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[  +10 ms] executing: [/Users/acbelter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/acbelter/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [/Users/acbelter/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.4
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18E227
[  +77 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +36 ms] executing: /usr/bin/xcode-select --print-path
[  +15 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[  +13 ms] executing: /Users/acbelter/Library/Android/sdk/emulator/emulator -list-avds
[  +63 ms] Nexus_5X_API_26
           Nexus_5_API_24
           Pixel_4a_API_31
[   +7 ms] 4 available emulators:
           
[   +4 ms] apple_ios_simulator • iOS Simulator   • Apple  • ios
[   +1 ms] Nexus_5X_API_26     • Nexus 5X API 26 • Google • android
[        ] Nexus_5_API_24      • Nexus 5 API 24  • Google • android
[        ] Pixel_4a_API_31     • Pixel 4a API 31 • Google • android
[        ] To run an emulator, run 'flutter emulators --launch <emulator id>'.
[        ] To create a new emulator, run 'flutter emulators --create [--name xyz]'.
[        ] You can find more information on managing emulators at the links below:
             https://developer.android.com/studio/run/managing-avds
             https://developer.android.com/studio/command-line/avdmanager
[  +14 ms] "flutter emulators" took 242ms.
[ +115 ms] ensureAnalyticsSent: 109ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```
	
</details>

What I'm trying to fix the problem:
1. Restart iOS Simulator, restart Android Studio, restart Xcode etc.
2. Install VS Code. Result: `Failed to launch iOS Simulator: Error: Emulator didn't connect within 60 seconds`
3. Reinstall Xcode (try 11.3.1 and 11.2.1) or rename Xcode.app
4. Switch flutter channel via `flutter channel dev/master/beta/stable` + `flutter upgrade`
5. `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` + `sudo xcodebuild -runFirstLaunch` + `sudo xcodebuild -license`
6. Run iOS Simulator via `flutter emulators --launch`
7. `Xcode - Preferences... - Locations - Command Line Tools` and select `Xcode 11.2.1 (11B500)` or `Xcode 11.3.1`
8. Setup Android SDK in Android Studio (`File - Project Structure - Project`)
9. Remove `flutter/bin/cache folder` + ` flutter clear`

P.S.
- iOS Simulator was displayed in the devices list earlier before updating `flutter`, `flutter plugin` or something else.
- I don't want to update Xcode because Xcode with version > 11.3.1 requires update macOS to 10.15. Could Xcode 11.x be the problem?

**Comment by TahaTesser** [comment] 2021-09-01 08:17
Hi @acbelter 
I see you're running macOS `10.x.x`, this makes it a duplicate of https://github.com/flutter/flutter/issues/87422. 
The fix would be available in the latest `beta` channel.

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Thank you.

**Comment by acbelter** [comment] 2021-09-01 10:09
Hi @TahaTesser
After executing the commands `flutter doctor` asks to update Xcode:
`Flutter requires a minimum Xcode version of 12.0.1.`

Does this mean that on macOS 10.14.x it's impossible to fix the problem with iOS Simulator and I need to update macOS to 10.15.x and Xcode to 12.0.1?

**Comment by TahaTesser** [comment] 2021-09-01 11:44
Hi @acbelter 
Can you please provide full `flutter doctor -v`

**Comment by TahaTesser** [comment] 2021-09-01 11:51
@acbelter 
Actually you need to upgrade for beta channel 

```console
Found "Xcode 11.2.1, Build version 11B500". Xcode 12.0.1 or greater is required to develop for iOS.
Encountered error while building for device.
```

**Comment by acbelter** [comment] 2021-09-01 12:41
> Hi @acbelter
> Can you please provide full `flutter doctor -v`

<details>
<summary>Full output from console</summary>

```
acbelter$ flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:  + c2cfaf7cb1...a8ff930b52 experimental_skshaper -> origin/experimental_skshaper  (forced update)
git:    a0b560f4d5..36531fbc9f  master                -> origin/master
git: Switched to branch 'beta'
git: Your branch is up to date with 'origin/beta'.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
acbelter$ flutter upgrade --force
Downloading Dart SDK from Flutter engine 7a4c4505f6a7a1aa758d62b58150dce43cfa473f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  219M  100  219M    0     0  5790k      0  0:00:38  0:00:38 --:--:-- 5855k
Building flutter tool...
Flutter is already up to date on channel beta
Flutter 2.5.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 19c61fed0d (13 days ago) • 2021-08-18 17:10:31 -0700
Engine • revision 7a4c4505f6
Tools • Dart 2.14.0 (build 2.14.0-377.7.beta)
acbelter$ flutter doctor -v
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on Mac OS X 10.14.4 18E227 darwin-x64, locale en-RU)
    • Flutter version 2.5.0-5.2.pre at /Users/acbelter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (13 days ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/acbelter/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ Flutter requires a minimum Xcode version of 12.0.1.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.0 Stable.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>

**Comment by acbelter** [comment] 2021-09-01 12:51
> @acbelter
> Actually you need to upgrade for beta channel
> 
> ```
> Found "Xcode 11.2.1, Build version 11B500". Xcode 12.0.1 or greater is required to develop for iOS.
> Encountered error while building for device.
> ```

@TahaTesser So I can't fix the issue without updating Xcode to 12.0.1?

**Comment by TahaTesser** [comment] 2021-09-01 13:07
@acbelter 
Unfortunately not, I have tested an app in CI/CD using Xcode 11.2 on latest beta channel, same error,

**Closed** 2021-09-01 13:08 UTC
Labels: in triage

**Comment by TahaTesser** [comment] 2021-09-01 13:12
https://github.com/flutter/flutter/issues/87422 only fixes the error message FYI, you still need to upgrade

**Comment by acbelter** [comment] 2021-09-01 13:43
@TahaTesser Thank you! I will upgrade Xcode to 12.0.1 and write about the results :)

**Comment by acbelter** [comment] 2021-09-01 23:24
Everything works on `macOS 10.15.7`, `Xcode 12.4` and `Flutter 2.5.0-5.2.pre` from beta channel.
