### ISSUE TITLE
Crash when running via Simulator on M1

### ISSUE THREAD

**Issue by koteesy** [flutter/flutter#86181] opened 2021-07-09 16:36 UTC
## Steps to Reproduce

1. Buy a m1 macbook
2. Run: flutter run in a terminal
3. get crash

## What i already tried
1. Install ffi - Not working
2. Tried to add excluded arch to xcode - Not working
3. Tried to run xcode via rosetta - Not working
4. Tried to call: flutter run via rosetta terminal - Not working

## Flutter doctor:

```

[✓] Flutter (Channel stable, 2.2.2, on macOS 12.0 21A5248p darwin-arm, locale
    ru)
    • Flutter version 2.2.2 at /Users/koteezy/development/flutter
    • Framework revision d79295af24 (4 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/koteezy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 3E212CDE-28D3-4FA1-A92B-06C148F09C01 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

## Some videos
Run from xcode: https://youtu.be/qFn3pxBpKRo
Run from terminal: https://youtu.be/sIo-KA8U82A

## Dependencies
cupertino_icons: ^1.0.2
flutter_inappwebview: ^5.3.2
webview_flutter: ^2.0.8

## Note
Just now i create a new app without dependencies with: 
```
flutter create -i swift -a kotlin test.designtest
```

And get same issue

## Logs

<details>
<summary>Logs</summary>

```
Incident Identifier: 85B06C49-2D76-4DE3-80F7-2F7C5456FFCA
CrashReporter Key:   F7A889AD-4A8B-57A9-A541-2EE35549A1F6
Hardware Model:      MacBookAir10,1
Process:             Runner [92854]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/3E212CDE-28D3-4FA1-A92B-06C148F09C01/data/Containers/Bundle/Application/4794BA21-93D3-40AC-AB1B-E6278D27632F/Runner.app/Runner
Identifier:          com.example.testBrowser
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [92190]
Coalition:           com.apple.CoreSimulator.SimDevice.3E212CDE-28D3-4FA1-A92B-06C148F09C01 [39952]
Responsible Process: SimulatorTrampoline [92179]

Date/Time:           2021-07-09 19:17:32.9496 +0300
Launch Time:         2021-07-09 19:17:32.2846 +0300
OS Version:          macOS 12.0 (21A5248p)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4302245888
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file                 1006f1000-1006f5000    [   16K] r-x/r-x SM=COW  ...t_id=d4adfe41
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [92854]

Triggered by Thread:  0

Application Specific Information:



Thread 0 Crashed:
0   ???                           	    0x7ff7ffc2bbd8 ???
1   <translation info unavailable>	       0x100721e54 ???
2   dyld                          	       0x2009d688f dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 890
3   dyld                          	       0x2009d56b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
4   dyld                          	       0x2009d54b4 start + 388
5   dyld                          	       0x2009d0000 ???

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffc18320 ???
1   ???                           	    0x7ff7ffc311a0 ???


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000108778af8  rcx: 0x0000000000000000  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000108e15000
   r8: 0x0864797a0a7200ec   r9: 0x0000000000000000  r10: 0x0000000108e15000  r11: 0x0000000108c38010
  r12: 0x0000000000000000  r13: 0x0000000108c38060  r14: 0x0000000200a44080  r15: 0x0000000000000000
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0x000000010070fc64 tmp1: 0x000000010070ef8c tmp2: 0x00000002009eeca3


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2009d0000 -        0x200a37fff dyld (*) <4e207376-cc5d-3986-a0bd-4d09f4217e68> /usr/lib/dyld

EOF

Model: MacBookAir10,1, BootROM 7429.0.72.0.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_wifi, wl0: May  4 2021 18:24:35 version 18.20.281.2.7.8.107 FWID 01-7c11bd60
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
```

</details>

**Comment by koteesy** [comment] 2021-07-09 17:05
## Update

I update flutter to new 2.2.3 version, create a new application and issue still exists, flutter doctor show me all green

**Comment by maheshmnj** [comment] 2021-07-12 10:21
Hi @koteesy,
Thanks for filing the issue, This looks like the issue is specific to macOS 12 and there's already an open issue filed here https://github.com/flutter/flutter/issues/85545. You may follow up there for further updates.

I am going to close this issue as a duplicate if you disagree feel free to comment and I will reopen it.
Thank you.

**Closed by maheshmnj** 2021-07-12 10:21 UTC
Labels: in triage
