### ISSUE TITLE
Flutter - Migrate to the Play Install Referrer API

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#46761] opened 2019-12-11 08:17 UTC
Hi there, I have a flutter app published in Google Play, I have received yesterday the following email from Google:

>  Hello Google Play Developer,

> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.

> Action required

> Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games. 

My app uses both firebase and AdMob plugins, so I guess either or both of them causes this. Any suggestion would be greatly appreciated!

**Comment by iapicca** [comment] 2019-12-11 12:37
Hi @angel1st 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-11 12:37 UTC
