### ISSUE TITLE
Failed assertion in animation_controller.dart

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#152825] opened 2024-08-04 00:58 UTC
### Steps to reproduce

I don't have an isolated sample to reproduce this and only seeing these errors in MacOS debug build and stack trace has no references to my application code. Also, I'm not using any explicit animations. So, I presume this comes from some framework stuff, e.g. page transitions or other activity.

Release builds on Android and iOS don't throw this error.

### Expected results

Expected to have no errors, or at least some details 

### Actual results

AnimationController throws some exceptions with no specifics.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 848 pos 12: 'elapsedInSeconds >= 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:848:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:258:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1235:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1233:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1150:5)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
#11     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:606:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:274:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:180:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:768:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:639:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:493:12)
#8      new InkHighlight (package:flutter/src/material/ink_highlight.dart:60:9)
#9      _InkResponseState.updateHighlight (package:flutter/src/material/ink_well.dart:993:29)
#10     _InkResponseState.handleHoverChange (package:flutter/src/material/ink_well.dart:1270:5)
#11     _InkResponseState.handleMouseEnter (package:flutter/src/material/ink_well.dart:1258:7)
#12     MouseTracker._handleDeviceUpdateMouseEvents (package:flutter/src/rendering/mouse_tracker.dart:423:29)
#13     MouseTracker._handleDeviceUpdate (package:flutter/src/rendering/mouse_tracker.dart:277:5)
#14     MouseTracker.updateAllDevices.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:373:9)
#15     MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:205:9)
#16     MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:367:5)
#17     RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:460:22)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
#20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#21     _invoke (dart:ui/hooks.dart:312:13)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#23     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _FrameCallbackEntry)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 13.6.6 22G630 darwin-arm64, locale en-CA)
    • Flutter version 3.22.3 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ***
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.18808

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by darshankawar** [comment] 2024-08-05 09:00
Thanks for the report @ekuleshov 
You are most likely hitting https://github.com/flutter/flutter/issues/149999 which has been fixed and must be available in master, but not in stable yet. 
Closing as already fixed and duplicate of linked issue.

**Closed by darshankawar** 2024-08-05 09:00 UTC
Labels: in triage

**Comment by ekuleshov** [comment] 2024-08-05 10:49
@darshankawar any chance this could be prioritized for the stable channel hot fixes?

**Comment by darshankawar** [comment] 2024-08-05 11:11
I think it is too late to cherry pick in 3.22.3.
A new stable release is expected soon so hopefully it will have the said fix in it. Do watch out for release.

**Comment by ekuleshov** [comment] 2024-08-09 20:15
@darshankawar I'm running the new stable 3.24.0 and still getting this assertion on macos.

It seems to be related to scrolling, but probably not to the overscroll, as I saw it triggered while being in a middle of a long scrollable list...

```
[✓] Flutter (Channel stable, 3.24.0, on macOS 13.6.6 22G630 darwin-arm64, locale en-CA)
    • Flutter version 3.24.0 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (10 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ***
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 81.0.2
    • Dart plugin version 241.18968.26

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.
```

**Comment by darshankawar** [comment] 2024-08-12 05:20
Thanks for checking. Can you switch to master and re-run your scenario to see if it resolves or persists ?
