### ISSUE TITLE
Allow custom TextSelectionControls inside SelectableText.

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#59418] opened 2020-06-14 11:16 UTC
![image](https://user-images.githubusercontent.com/19904063/84591740-1a906780-ae41-11ea-9e20-5795d589c173.png)

## Use case

Right now it is only possible to have the Cupertino and material appearance of the selection control. And this is limited to the Copy/Cut/Paste/Select All options. 

Having the ability to customize the selection control would bring us more freedom to build custom solutions.
Do you want to search on google a selected text? Or call a selected phone number? Highlight the selected text? Make it bold?

The implementation doesn't look difficult as it would be just adding the optional param and use it if it is not null and isSelectabe = true. [Check here were to add it](https://github.com/flutter/flutter/blob/97dc7eee570a31ed34f10834abf20549184cfe35/packages/flutter/lib/src/material/selectable_text.dart#L624).

**Comment by TahaTesser** [comment] 2020-06-15 10:57
Please comment the details you mentioned here in the duplicate issue 

duplicate of https://github.com/flutter/flutter/issues/36985

**Closed by TahaTesser** 2020-06-15 10:57 UTC
