### ISSUE TITLE
ElevatedButton style applying wrong vertical padding

### ISSUE THREAD

**Issue by dallas1287** [flutter/flutter#146574] opened 2024-04-10 13:55 UTC
### Steps to reproduce

Setting the ElevatedButtonTheme ButtonStyle padding doesn't seem to correctly reflect the requested vertical padding.
It seems to be the vertical padding ONLY, my tests so far have only been on windows.

### Expected results

The padding reports as the desired vertical padding from the ButtonStyle settings.

### Actual results

The vertical padding is 8 pixels less than it should be.

### Code sample

Here is the code for setting the ElevateButton style
```
  ElevatedButtonThemeData get elevatedButtonTheme =>
      ElevatedButtonThemeData(style: defaultElevatedButton);

  ButtonStyle? get defaultElevatedButton => ButtonStyle(
      backgroundColor:
          MaterialStateProperty.resolveWith<Color>((Set<MaterialState> states) {
        if (states.contains(MaterialState.pressed)) {
          return theme.dividerOnPrimary_65p;
        } else if (states.contains(MaterialState.hovered)) {
          return theme.dividerOnPrimary;
        } else if (states.contains(MaterialState.focused)) {
          return theme.blue100;
        } else if (states.contains(MaterialState.disabled)) {
          return theme.blue100.withOpacity(0.5);
        }
        return theme.blue100;
      }),
      shape: MaterialStateProperty.resolveWith<OutlinedBorder?>(
          (Set<MaterialState> states) {
        if (states.contains(MaterialState.focused)) {
          return RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
              side: BorderSide(color: theme.primaryBg, strokeAlign: -3.0));
        }
        return RoundedRectangleBorder(borderRadius: BorderRadius.circular(8));
      }),
      textStyle: MaterialStatePropertyAll(theme.txtTheme.headlineMedium!),
      padding:
          const MaterialStatePropertyAll(EdgeInsets.fromLTRB(24, 16, 24, 16)),
      foregroundColor:
          MaterialStateProperty.resolveWith<Color>((Set<MaterialState> states) {
        if (states.contains(MaterialState.focused) ||
            states.contains(MaterialState.disabled)) {
          return theme.primaryBg;
        } else if (states.contains(MaterialState.hovered) ||
            states.contains(MaterialState.pressed)) {
          return Colors.white;
        }
        return theme.primaryBg;
      }),
      overlayColor: const MaterialStatePropertyAll(Colors.transparent),
      surfaceTintColor: const MaterialStatePropertyAll(Colors.transparent),
      splashFactory: NoSplash.splashFactory);
```
Here is the button usage
```
        ElevatedButton(
            onPressed: () {},
            child: const Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.square_outlined),
                  SizedBox(width: 8),
                  Text('Button'),
                  SizedBox(width: 8),
                  Icon(Icons.square_outlined)
                ])),
```

### Screenshots or Video

Here is a snapshot of the widget details tree:
![image](https://github.com/flutter/flutter/assets/18126791/32b6708d-4885-4e06-a528-1ae1f1a48569)

You can see very clearly that the padding is 8 pixels too small in the vertical directions. It's reporting 8 and should be 16. If i change my padding to 18 the padding becomes 10. As far as I can tell something just isn't cascading right. 

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    • Flutter version 3.19.4 on channel stable at C:\Users\Dallas\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (3 weeks ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Dallas\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34714.143
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.88.0)
    • VS Code at C:\Users\Dallas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 123.0.6312.106
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 123.0.2420.81

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment] 2024-04-11 08:01
Hi @dallas1287 
This is the intended behavior, please see https://github.com/flutter/flutter/issues/137411#issuecomment-1815019901. Closing this as a duplicate of https://github.com/flutter/flutter/issues/137411.

**Closed by huycozy** 2024-04-11 08:01 UTC
Labels: in triage

**Comment by huycozy** [comment] 2024-04-12 03:58
I think it should be improved to warn users about that. Please also share your thoughts on #137411. Thanks!
