### ISSUE TITLE
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════

### ISSUE THREAD

**Issue by Ddtarsariya** [flutter/flutter#67521] opened 2020-10-07 12:50 UTC
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 481 pos 16: '_displacementTickerLastElapsed == null': is not true.

**--------------Sample Code ---------------**

`import 'package:bal_attendance/class/class_tile.dart';
import 'package:bal_attendance/models/class.dart';
import 'package:bal_attendance/screens/home/add_class/add_class.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:provider/provider.dart';

class ClassList extends StatefulWidget {
  @override
  _ClassListState createState() => _ClassListState();
}

class _ClassListState extends State<ClassList> {
  ScrollController _hideFloatingButtoncontroller;
  bool _isShow = true;

  @override
  void initState() {
    super.initState();
    _isShow = true;
    _hideFloatingButtoncontroller = ScrollController();
    _hideFloatingButtoncontroller.addListener(() {
      if (_hideFloatingButtoncontroller.position.userScrollDirection ==
          ScrollDirection.reverse) {
        if (_isShow == true) {
          setState(() => _isShow = false);
        }
      } else {
        if (_hideFloatingButtoncontroller.position.userScrollDirection ==
            ScrollDirection.forward) {
          if (_isShow == false) {
            setState(() => _isShow = true);
          }
        }
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    _hideFloatingButtoncontroller.removeListener(() {});
  }

  @override
  Widget build(BuildContext context) {
    final classes = Provider.of<List<Class>>(context) ?? [];

    return Scaffold(
      floatingActionButton: Visibility(
        visible: _isShow,
        child: Container(
          margin: EdgeInsets.fromLTRB(0, 0, 10, 20),
          child: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {
              Navigator.push(
                  context, MaterialPageRoute(builder: (context) => AddClass()));
            },
          ),
        ),
      ),
      body: ListView.builder(
        controller: _hideFloatingButtoncontroller,
        itemCount: classes.length,
        itemBuilder: (context, index) {
          return ClassTile(clase: classes[index]);
        },
      ),
    );
  }
}
`

**----Flutter Doctor-----**
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.19042.546], locale en-IN)
    • Flutter version 1.22.0 at C:\Users\tarsa\AppData\Local\Android\flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\tarsa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\tarsa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (2 available)
    • Infinix X573 (mobile)              • 33d7c628      • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!

_Originally posted by @Ddtarsariya in https://github.com/flutter/flutter/issues/34009#issuecomment-704911208_

**Comment by Calamity210** [comment] 2020-10-07 12:57
Duplicate of #65845

**Closed** 2020-10-07 14:45 UTC
