### ISSUE TITLE
Bug Flutter apps displaying background on apps start launch?

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#91210] opened 2021-10-04 04:51 UTC
I don't know if this is normal or a bug issue, I've noticed some apps (my own included) after making a release version or even a debug one when launch it will display a weird bronze background color few milliseconds Screenshot below) is this normal on build or is there any resolution for this ?

Here's my build.gradle and AndroidManifest in case it helps
```gradle
    compileOptions {
     sourceCompatibility 1.8
     targetCompatibility 1.8
     }

    buildTypes {
     release {
        minifyEnabled true
        shrinkResources true
        zipAlignEnabled true
        proguardFiles getDefaultProguardFile(
                'proguard-android-optimize.txt'),
                'proguard-rules.pro'
        signingConfig signingConfigs.release
      }
````
AndroidManifest

<details> 
<summary>AndroidManifest.xml</summary> 
	
```xml
    <uses-feature android:name="android.hardware.camera.autofocus"/>
    <uses-permission android:name="android. permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="com.android.vending.BILLING" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT"/>

    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="myapp"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:requestLegacyExternalStorage="true"
        >

        <receiver android:name="com.app.myapp">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
        </receiver>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="https"
                    android:host="YOUR_SUBDOMAIN.page.link" />
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value=""/>

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value=""/>

        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <service            android:name="com.app.fayda.localnotifications.services.LocalNotificationsService"
            android:exported="false" />

        <meta-data            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
```
	
</details>

<img src="https://user-images.githubusercontent.com/29728429/135796117-288bb305-4a88-40c5-8e3a-6930db28e1b6.png" height="450" />	

Here is another example of Tinder app which has the same issue right before Splash screen appear Screenshot tinder

<img src="https://user-images.githubusercontent.com/29728429/135796134-fac4991f-0430-427e-a8ea-5712b735be1e.png" height="450" />

**Comment by devduiux** [comment] 2021-10-04 09:51
Hello @zakblacki 

I have solution for this problem you need to follow some steps if you want to check your issue is solved for release version or not 

If you want to solve issue first then you need to run in release build variant for that follow this steps

(1). Flutter clean and flutter pub get
(2). Open Android Module of Project in another window
(3).  Wait for all process and after that First Clean Project and Rebuild Project if you don't have Idea about then see this picture
![Screenshot 2021-10-04 at 2 24 53 PM](https://user-images.githubusercontent.com/91519387/135822492-dfa078ce-4146-4868-84ff-e097d82a5c47.png)

(4). Wait for Rebuild process complete and now change your build variants first at your left bottom you can see tab "Build variant" open it and after that in the front of "app" folder you can see in column of "Active Build Variant" like such "debug" please change it to "release"  If you don't have any idea then see picture



![Screenshot 2021-10-04 at 2 30 25 PM](https://user-images.githubusercontent.com/91519387/135823390-2493ff42-5294-4704-a468-f3982056f654.png)

(5). after that repeat step 3 
(6) and run project from Android Module If you face the grey screen issue then you can know what is the exactly error in Logcat section and also make sure that your keystore file and keystore details are proper for release

**Comment by TahaTesser** [comment] 2021-10-04 12:52
Hi @zakblacki 

> Here is another example of Tinder app which has the same issue right before Splash screen appear Screenshot tinder

Seems like the b behaviour you describe is reproducible in non-flutter apps too. 

The grey screen in the Flutter app shows in release mode instead of the red crash screen. looks like your apps has some issue. Debug your app further to find out why your app is crashing in release mode, as this is not an issue with Flutter itself. Brown screen is not related to thIs.


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-10-04 12:52 UTC
Labels: in triage
