### ISSUE TITLE
[web] flutter.js is not generated on deleting the build folder manually

### ISSUE THREAD

**Issue by caduandrade** [flutter/flutter#104830] opened 2022-05-27 13:53 UTC
`build web` does not recreate the `flutter.js` file if the `build` directory is deleted. I don't understand why since this `build` directory is ignored in `.gitignore` and is only created when running the command.

## Steps to Reproduce

1. create a flutter project
2. run `flutter build web` (build/web/flutter.js exists)
3. delete `build` directory
4. run again `flutter build web` (build/web/flutter.js not exists)

## Logs

```bash
cadu@cadulandia:/cadu$ flutter create webtest
Creating project webtest...
Running "flutter pub get" in webtest...                          1,432ms
Wrote 127 files.

All done!
In order to run your application, type:

  $ cd webtest
  $ flutter run

Your application code is in webtest/lib/main.dart.

cadu@cadulandia:/cadu$ cd webtest/
cadu@cadulandia:/cadu/webtest$ ls build
ls: cannot access 'build': No such file or directory
cadu@cadulandia:/cadu/webtest$ flutter build web

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             23.9s
cadu@cadulandia:/cadu/webtest$ ls build/web/flutter.js 
build/web/flutter.js
cadu@cadulandia:/cadu/webtest$ rm -rf build
cadu@cadulandia:/cadu/webtest$ flutter build web

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             682ms
cadu@cadulandia:/cadu/webtest$ ls build/web/flutter.js 
ls: cannot access 'build/web/flutter.js': No such file or directory

```

## Flutter doctor

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-44-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /cadu/desenv/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/cadu/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /home/cadu/Android/Sdk
    • Java binary at: /cadu/desenv/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /cadu/desenv/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /cadu/desenv/idea-IC-211.7628.21
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-44-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by caduandrade** [comment] 2022-05-27 14:10
I had to create another project to retrieve the `flutter.js` file

**Comment by navaronbracke** [comment] 2022-05-27 15:26
That file should be regenerated after doing `flutter clean` ?

**Comment by caduandrade** [comment] 2022-05-27 16:02
> That file should be regenerated after doing `flutter clean && flutter build web`?

Yes. With `clean` the file was created. At least it's a faster and smarter way to recover `flutter.js` than I did.

Anyway, it's still weird, don't you think? The `build` command creates the directory. It should create all files always.

**Comment by navaronbracke** [comment] 2022-05-27 17:03
Yeah, `flutter clean` should remove the entire build directory, while `flutter build` should recreate it.

**Comment by maheshmnj** [comment] 2022-05-30 07:55
Hi @caduandrade, Thanks for filing the issue. I see similar behavior on the latest stable and the master channel

- deleting the build directory manually and on rebuilding the app `flutter.js` file is not regenerated.
- Run `flutter clean` and rebuild the app `flutter.js` is generated

Not sure if this is an intended behavior labeling the issue for further insights from the team.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.961, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.961 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0777b0d2c4 (7 hours ago), 2022-05-27 00:45:12 -0400
    • Engine revision 5af8579cbe
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by maheshmnj** [comment] 2022-05-30 07:57
Looks same as https://github.com/flutter/flutter/issues/103070

cc: @ditman

**Comment by christopherfujino** [comment] 2022-05-31 22:07
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/103070. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-05-31 22:07 UTC
Labels: tool, platform-web, a: release, has reproducible steps, found in release: 3.0, found in release: 3.1

**Comment by ditman** [comment] 2022-06-01 19:37
We've thought of detecting the "flutter has deleted the `build` folder" as a sign that they wanted to do a `build clean`; I'm investigating how to add that feature cleanly to the `flutter` tool.
