### ISSUE TITLE
usePathUrlStategy causes execution to stop when path with multiple slashes entered into the web browser (3.7)

### ISSUE THREAD

**Issue by runionke** [flutter/flutter#119161] opened 2023-01-25 16:56 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample (chrome)
2. in browser update the url with /test/bug to go to the test route with a parameter of bug

**Expected results: the text: param is bug 

**Actual results: route will not load, presenting a blank screen 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:go_router/go_router.dart';

void main() {
  usePathUrlStrategy();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationProvider: Routing.routes.routeInformationProvider,
      routeInformationParser: Routing.routes.routeInformationParser,
      routerDelegate: Routing.routes.routerDelegate,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, this.param});
  final String? param;
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Text('param is $param'));
  }
}

class Routing {
  static final routes = GoRouter(initialLocation: '/', routes: [
    GoRoute(path: '/', builder: (context, state) => const MyHomePage()),
    GoRoute(
      path: '/test/:param',
      builder: (context, state) => MyHomePage(param: state.params['param']),
    )
  ]);
}

```

</details>

<details>
  <summary>Logs</summary>

```

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:58816/Xafzxy-rgzg=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:58816/Xafzxy-rgzg=
Application finished.
(base) kr@Kevins-Air test_route_issue % flutter run --verbose
[   +9 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: [/Users/kr/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] executing: [/Users/kr/Development/flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[  +61 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] 3.7.0
[   +6 ms] executing: [/Users/kr/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/kr/Development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +19 ms] executing: [/Users/kr/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.0.1
[        ] executing: sw_vers -buildVersion
[   +8 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22A400
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: /Users/kr/Library/Android/sdk/platform-tools/adb devices -l
[  +19 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +637 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[   +1 ms] Xcode 14.2
           Build version 14C18
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 2
[        ] /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[        ] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted
[  +94 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 16.2 --
[  +24 ms] List of devices attached
[  +78 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.iOS-16-2" : [

               ]
             }
           }
[+2849 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,2",
                        "identifier" : "C3EB51C7-D8F0-472E-9364-05769A371B20",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-14-pro-1",
                        "modelName" : "iPhone 14 Pro",
                        "name" : "iPhone 14 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,3",
                        "identifier" : "2E382105-4A6E-4128-9BFF-E86B68E656BD",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-11-4th-1",
                        "modelName" : "iPad Pro (11-inch) (4th generation)",
                        "name" : "iPad Pro (11-inch) (4th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,5",
                        "identifier" : "6447ABD3-FA9B-4BB8-BC93-5F41A5AFA6B1",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-6th-1",
                        "modelName" : "iPad Pro (12.9-inch) (6th generation)",
                        "name" : "iPad Pro (12.9-inch) (6th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,7",
                        "identifier" : "3332CE53-07F6-43C0-BED4-F8E3E32ADF7D",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-14-1",
                        "modelName" : "iPhone 14",
                        "name" : "iPhone 14"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "5722E50D-143A-4C25-98FC-A847D9D05696",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,3",
                        "identifier" : "947E9F56-91F7-4D6B-887A-80D070DC4C74",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-14-pro-max-1",
                        "modelName" : "iPhone 14 Pro Max",
                        "name" : "iPhone 14 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,17",
                        "identifier" : "037A2A1B-0B64-4B26-AAEA-0D51E702A456",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air5-1",
                        "modelName" : "iPad Air (5th generation)",
                        "name" : "iPad Air (5th generation)"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "13.0.1 (22A400)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.macosx",
                        "modelCode" : "MacBookAir10,1",
                        "identifier" : "00008103-001424C821A2001E",
                        "architecture" : "arm64e",
                        "modelUTI" : "com.apple.macbookair-late-2020",
                        "modelName" : "MacBook Air",
                        "name" : "My Mac"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "D07AA28F-3D10-4E16-A2F7-00C94073E462",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,8",
                        "identifier" : "0B29EB10-B6A8-4222-B7AD-423D3869E575",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-14-plus-1",
                        "modelName" : "iPhone 14 Plus",
                        "name" : "iPhone 14 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "16.2 (20C52)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "8071349A-210D-45E1-9EA7-687BFDC245DB",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)"
                      }
                    ]
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Skipping pub get: version match.
[ +101 ms] Launching lib/main.dart on Chrome in debug mode...
[  +42 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +2 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Updating assets
[  +39 ms] Waiting for connection from debug service on Chrome...
[  +19 ms] <- reset
[   +2 ms] /Users/kr/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/kr/Development/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/Users/kr/Development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/7b/pls067n91_q_mcgwnvb8njkc0000gn/T/flutter_tools.txyjT4/flutter_tool.874xeV/app.dill --packages
/Users/kr/Development/projects/test_route_issue/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root
/var/folders/7b/pls067n91_q_mcgwnvb8njkc0000gn/T/flutter_tools.txyjT4/flutter_tools.3mXYU9 --filesystem-scheme org-dartlang-app
--initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///Users/kr/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --verbosity=error
--sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10389 ms] Waiting for connection from debug service on Chrome... (completed in 10.4s)
[        ] Synced 33.2MB.
[        ] <- accept
[        ] Caching compiled dill
[  +46 ms] Using Google Chrome 109.0.5414.87 

[ +357 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +13 ms] Found ARM Chrome installation at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, forcing native launch.
[ +603 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:59215/devtools/browser/f4ae9373-6571-4491-bdb3-c393f0d4f46a
[ +609 ms] DwdsInjector: Received request for entrypoint at http://localhost:59198/main_module.bootstrap.js
[   +1 ms] MetadataProvider: Loading debug metadata...
[   +2 ms] MetadataProvider: Loaded debug metadata for module: web_entrypoint.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/go_router/src/information_provider.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/flutter_web_plugins/url_strategy.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/flutter_web_plugins/src/navigation/url_strategy.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/flutter_web_plugins/src/navigation/utils.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/flutter_web_plugins/src/navigation/js_url_strategy.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/flutter_web_plugins/src/navigation_common/url_strategy.dart
[        ] MetadataProvider: Loaded debug metadata (sound null safety)
[  +11 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:59198/main_module.bootstrap.js
[+1760 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +36 ms] DevHandler: Debug service listening on ws://127.0.0.1:59237/GIwgZsvgLxQ=/ws

[   +9 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 9, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
           _setStreamIncludePrivateMembers, id: 9, params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +1 ms] This app is linked to the debug service: ws://127.0.0.1:59237/GIwgZsvgLxQ=/ws
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
           _setStreamIncludePrivateMembers, id: 10, params: {streamId: Stderr, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
           _setStreamIncludePrivateMembers, id: 11, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 12, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
           _setStreamIncludePrivateMembers, id: 12, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +2 ms] Debug service listening on ws://127.0.0.1:59237/GIwgZsvgLxQ=/ws
[        ] 💪 Running with sound null safety 💪
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:59237/GIwgZsvgLxQ=
[+2025 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:59237/GIwgZsvgLxQ=
[+9737 ms] ChromeProxyService: Destroying isolate
[        ] BatchedExpressionEvaluator: Closed
[        ] ChromeProxyService: Destroying isolate

```

```
No issues found! (ran in 1.0s)
```

```
Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-arm64, locale en-US)
    • Flutter version 3.7.0 on channel stable at /Users/kr/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kr/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by runionke** [comment] 2023-01-25 19:25
After some further testing, this isn't related to GoRouter, and appears to be specific to usePathUrlStrategy(). Without path strategy, this works as expected.

**Comment by jorgelrj** [comment] 2023-01-25 19:32
Notice the same issue on different web apps I work with. 

With `usePathUrlStrategy().`, reloading a nested url (parent/child), throws a service worker exception. Removing the call to url strategy fixes the issue

**Comment by darshankawar** [comment] 2023-01-26 10:31
Thanks for the report @runionke 
I tried your code sample using latest master, added `/test/bug` to the url which resulted in expected behavior per your description:

<img width="462" alt="Screenshot 2023-01-26 at 4 00 05 PM" src="https://user-images.githubusercontent.com/67046386/214814220-9008c63d-fda4-4894-a130-2451241344b8.png">

Maybe it is related to [this](https://github.com/flutter/flutter/pull/118684) fix which is available in master, but not in stable yet.

**Comment by jorgelrj** [comment] 2023-01-26 18:28
@darshankawar  I can confirm that the issue is solved for me on the master channel

**Comment by runionke** [comment] 2023-01-26 19:34
Can also confirm fixed in master.

**Comment by darshankawar** [comment] 2023-01-27 05:12
Thanks for confirming. I am going ahead and closing this as it works on master. The fix should be available in stable per Flutter team's release policy as mentioned [here](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel).

**Closed by darshankawar** 2023-01-27 05:12 UTC
Labels: in triage
