### ISSUE TITLE
[go_router] navigatorKey is missing 

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#109943] opened 2022-08-21 12:41 UTC
I am trying to navigate to another screen when a firebase push notification is clicked but i can't make it work 
as I am getting the following error 
`package:go_router/src/router.dart': Failed assertion: line 270 pos 12: 'inherited != null': No GoRouter found in context`.

With MaterialRoute we had a navigatorKey when we were able to use to navigate

```
class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<NavigatorState> navigatorKey = GlobalKey(debugLabel: "Main Navigator");
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      navigatorKey: navigatorKey,
      home: new Scaffold(
        appBar: AppBar(),
        body: new Container(),
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment] 2022-08-22 09:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109479. 

Kindly follow up in the linked issue for updates and please upvote it. 

Thank you

**Closed by danagbemava-nc** 2022-08-22 09:39 UTC
Labels: in triage
