### ISSUE TITLE
After upgrading to 3.22 Flutter Web ignores the -no-web-resources-cdn config

### ISSUE THREAD

**Issue by cfsbhawkins** [flutter/flutter#148713] opened 2024-05-20 21:18 UTC
### Steps to reproduce

Compile an Web App in 3.19 will use local webserver for canvaskit files, when compiling in 3.22 it now replaces it with pulling the file from google CDN which breaks my ability to work in a completely offline mode. 

flutter build web --no-web-resources-cdn --web-renderer canvaskit --release

### Expected results

CanvasKit and all files should pull from /canvaskit dir.

### Actual results

Canvaskit pulls from Google CDN

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Computer at .163 has been downgraded to 3.19.6, computer at .170 is on 3.22, no other changes.

![Screenshot 2024-05-20 at 4 17 07 PM](https://github.com/flutter/flutter/assets/14224435/82f919a2-d7ab-48f1-a6b8-b28a64c9fa9d)
![Screenshot 2024-05-20 at 4 17 29 PM](https://github.com/flutter/flutter/assets/14224435/e567511a-8fe0-45cf-a07b-de5610ef2622)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by navaronbracke** [comment] 2024-05-21 09:14
I can reproduce this bug.

1. flutter create web_sample
2. cd web_sample
3. flutter build web --no-web-resources-cdn
4. cd build/web
5. dart pub global run dhttpd (I installed dhttpd globally with Pub)
6. open a new chrome window and open the network tab
7. go to localhost, under the port of dhttpd
8. All assets, except a variant of the Roboto font (a TTF file) come from localhost. The Roboto font comes from `fonts.gstatic.com` (ignore the `pageScript.js` in my screenshot, that is a local chrome extension that I have)

<img width="1552" alt="Screenshot 2024-05-21 at 11 10 59" src="https://github.com/flutter/flutter/assets/23480364/415385cd-f1d4-4b8d-99a9-77c90cbb18ca">

```
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-x64, locale
    en-BE)
    • Flutter version 3.22.0 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision 5dcb86f68f (12 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.209

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by huycozy** [comment] 2024-05-21 10:52
I checked this on my end and saw the same result as @navaronbracke shared above. 

`KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf` font comes from `https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf`. But I see script files come from local host (canvaskit.js for eg).

@cfsbhawkins As I see above, `canvaskit.js` file is still fetched from CDN. Do you have any specific configuration on `web` module? Could you confirm this on a new Flutter project?

**Comment by cfsbhawkins** [comment] 2024-05-22 20:54
Repo: https://github.com/cfsbhawkins/web_test

**Comment by huycozy** [comment] 2024-05-23 05:41
Thanks for your update, @cfsbhawkins. I see the issue. On a newly created project or re-created `web` module, `canvaskit.js` and `canvaskit.wasm` files are used from `gstatic.com` instead of localhost.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 hours ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-44.0.pre.10, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-44.0.pre.10 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fe0932f2c0 (76 minutes ago), 2024-05-22 22:19:25 -0400
    • Engine revision b8b82454e3
    • Dart version 3.5.0 (build 3.5.0-178.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by kevmoo** [comment] 2024-05-23 05:47
@eyebrowsoffire @yjbanov ?

**Comment by sashkent3** [comment] 2024-05-24 16:45
Putting the following in the web/flutter_bootstrap.js fixes the issue:
```
{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
    config: {
        canvasKitBaseUrl: "canvaskit"
    },
    serviceWorkerSettings: {
        serviceWorkerVersion: {{flutter_service_worker_version}}
    }
});
```

**Comment by eyebrowsoffire** [comment] 2024-06-07 21:51
Reopening because this also requires a flutter tool side change

**Comment by cfsbhawkins** [comment] 2024-06-07 23:36
Thanks for fixing it, will this make a cherry pick into the next 3.22 hotfix? I am currently having to hold back at 3.19 because our use case the appliances are air gapped usually.

**Comment by kevmoo** [comment] 2024-06-08 02:53
I don't think we want this closed yet...from https://github.com/jmagman/engine/commit/abee142667bdecd2ff307a4c78393b30574147b2

**Comment by eyebrowsoffire** [comment] 2024-06-13 16:24
@cfsbhawkins If you are blocked, you can just set the local `canvasKitBaseUrl` in the JavaScript config and that will prevent CanvasKit stuff from being fetched from CDN. An example `flutter_bootstrap.js` would look like this:

```
{{flutter_build_config}}
{{flutter_js}}
_flutter.loader.load({
    config: {
        canvasKitBaseUrl: "/canvaskit/",
    }
});
```

See https://docs.flutter.dev/platform-integration/web/bootstrapping for more details.

**Comment by eyebrowsoffire** [comment] 2024-06-28 19:01
Fixed with https://github.com/flutter/flutter/pull/150806

**Closed by eyebrowsoffire** 2024-06-28 19:01 UTC
Labels: c: regression, tool, platform-web, has reproducible steps, P1, e: wasm, team-web, triaged-web, found in release: 3.22
