### ISSUE TITLE
The keyboard doesn't show up in Textformfield

### ISSUE THREAD

**Issue by jesussmile** [flutter/flutter#123183] opened 2023-03-22 03:17 UTC
I have created a  textformfield that takes an input and then convert them to a chip like this in the picture 

[![enter image description here][1]][1]

It doesn show the chip but then after the first chip input the keyboard wont pop up again
there isn't much to say about this problem thats all, also is this a good approach ? eventually i want the chips to be draggable such that i can rearrange them. 
Please note: I dont want to use any package or plugin.This is all the code there is for now, you can try it in a dart pad or sth
here is the code
```dart
import 'package:flutter/material.dart';
class FruitChip extends StatelessWidget {
  final String label;
  final bool isMatched;
  FruitChip({
    required this.label,
    this.isMatched = true,
  });
  @override
  Widget build(BuildContext context) {
    return Chip(
      label: Text(
        label,
        style: TextStyle(
          color: Colors.white,
        ),
      ),
      backgroundColor: isMatched ? Colors.green : Colors.red,
    );
  }
}
class FruitForm extends StatefulWidget {
  @override
  _FruitFormState createState() => _FruitFormState();
}
class _FruitFormState extends State<FruitForm> {
  final List<String> fruits = ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'];
  final List<Widget> chips = [];
  final TextEditingController _textEditingController = TextEditingController();
  void _addChip(String fruit, bool isMatched) {
    setState(() {
      chips.add(FruitChip(
        label: fruit,
        isMatched: isMatched,
      ));
      _textEditingController.clear();
    });
  }
  bool _isFruitMatched(String input) {
    for (String fruit in fruits) {
      if (fruit.toLowerCase() == input.toLowerCase()) {
        return true;
      }
    }
    return false;
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Fruit Form'),
      ),
      body: Column(
        children: [
          TextFormField(
            controller: _textEditingController,
            onChanged: (String value) {
              String trimmedValue = value.trim();
              bool isMatched = _isFruitMatched(trimmedValue);
              if (isMatched) {
                setState(() {
                  chips.add(FruitChip(label: trimmedValue));
                });
                _textEditingController.value = const TextEditingValue(
                  text: '',
                  selection: TextSelection.collapsed(offset: 0),
                );
              }
            },
            keyboardType: TextInputType.text,
            maxLines: null,
            buildCounter: (BuildContext context,
                    {int? currentLength, int? maxLength, bool? isFocused}) =>
                null,
            style: const TextStyle(
              fontSize: 16.0,
            ),
            textAlignVertical: TextAlignVertical.top,
            textAlign: TextAlign.left,
            readOnly: chips.isNotEmpty,
            showCursor: true,
            cursorWidth: 2.0,
            cursorColor: Colors.blue,
            cursorRadius: Radius.circular(4.0),
            decoration: InputDecoration(
              contentPadding: EdgeInsets.symmetric(vertical: 8.0),
              hintText: 'Enter a fruit name',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
              ),
              prefixIcon: chips.isNotEmpty
                  ? Wrap(
                      spacing: 8.0,
                      children: chips,
                    )
                  : null,
            ),
          ),
        ],
      ),
    );
  }
}

```

  [1]: https://i.stack.imgur.com/BOPPb.jpg
  [2]: https://i.stack.imgur.com/9pXyo.jpg

**Comment by huycozy** [comment] 2023-03-22 07:58
Hi @jesussmile 
As far as I can see, this is caused by `readOnly: chips.isNotEmpty` from your implementation code. This should be handled by another solution. 

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.  Please also see https://flutter.dev/community or https://www.reddit.com/r/flutterhelp for resources and ask questions like this.

Closing, as this isn't an issue with Flutter framework itself.

**Closed by huycozy** 2023-03-22 07:58 UTC
Labels: in triage
