### ISSUE TITLE
FileSystemException: FileSystemException: Cannot create link, path = 'E:\repos\pizza_website\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows' (OS Error: Incorrect function. , errno = 1)

### ISSUE THREAD

**Issue by godalming123** [flutter/flutter#80038] opened 2021-04-08 10:12 UTC
my flutter app is giving error. this is the .log file the flutter said the crash report was written to I don't know what code has caused the error but [the github repo](https://github.com/godalming123/pizza_website) might be useful. I have just pushed every commit. And I am also using flutter for desktop. However my app works in web except clicking on the action button doesnt work then.

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get

## exception

FileSystemException: FileSystemException: Cannot create link, path = 'E:\repos\pizza_website\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows' (OS Error: Incorrect function.
, errno = 1)

```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/plugins.dart:1125:12)
#5      createPluginSymlinks (package:flutter_tools/src/plugins.dart:1066:5)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:1151:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:273:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:164:5)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#22     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-GB)
    • Flutter version 2.0.2 at C:\ProgramData\flutter_windows_1.22.4-stable\flutter
    • Framework revision 8962f6dc68 (4 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\jamie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 2 categories.
```

**Comment by godalming123** [comment] 2021-04-08 10:52
I have tried `flutter clean .` and app still isnt working.

**Comment by TahaTesser** [comment] 2021-04-08 10:54
Related to https://github.com/flutter/flutter/issues/66224

**Comment by TahaTesser** [comment] 2021-04-08 10:55
CC @jonahwilliams

**Comment by godalming123** [comment] 2021-04-09 08:32
my app works on chrome debug mode.

**Comment by jmagman** [comment] 2021-04-15 01:46
Duplicate of https://github.com/flutter/flutter/issues/66224.

Try moving your project to the `C:\` volume where Flutter is installed.

**Closed by jmagman** 2021-04-15 01:46 UTC
Labels: passed first triage, platform-windows, severe: crash, tool
