### ISSUE TITLE
MissingPluginException(No implementation found for method placemarkFromCoordinates on channel flutter.baseflow.com/geocoding)

### ISSUE THREAD

**Issue by letto4135** [flutter/flutter#81526] opened 2021-04-30 03:21 UTC
Ran into an error with the geocoding package, but error seems to trace back to flutter. Error is in platform_channel.dart _invokeMethod. When invoke method is called with placemarkFromCoordinates it fails to return anything on web (result == null). 

Check the last couple comments in this issue:
https://github.com/Baseflow/flutter-geocoding/issues/14

```
import 'package:geocoding/geocoding.dart' as geo;

Future<LocationData> determinePosition() async {
    Location location = new Location();

    bool _serviceEnabled;
    PermissionStatus _permissionGranted;
    LocationData _locationData;

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        throw Error();
      }
    }

    _permissionGranted = await location.hasPermission();

    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        print("Location not enabled");
        return null;
      }
    }
    
    location.changeSettings(accuracy: LocationAccuracy.low);

    _locationData = await location.getLocation();

    locationServicesEnabled = true;

    return _locationData;
  }
```

**Comment by pedromassangocode** [comment] 2021-04-30 07:05
Hi @letto4135 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-geocoding/issues).

As said in https://github.com/Baseflow/flutter-geocoding/issues/14#issuecomment-784994016, this plugin does not have support for Web apps.

Closing, as this isn't an issue with Flutter itself.  
Thank you

**Closed by pedromassangocode** 2021-04-30 07:05 UTC
Labels: in triage

**Comment by letto4135** [comment] 2021-04-30 11:52
@pedromassango As I explained, I traced the error to flutter itself, not the third party plugin. I even gave the flutter filename and method being invoked when the error happens... There is a chance that it is still the fault of the plugin not calling something correctly, but considering it is basically saying flutter does not have this method for web when it does for IOS and android I'd say the error is probably flutter.

**Comment by letto4135** [comment] 2021-04-30 14:15
@pedromassangocode Possibly, but I don't understand what a methodchannel is, or what it's doing. The methodchannel from geocoding is this
```
MethodChannel methodChannel = MethodChannel('flutter.baseflow.com/geocoding');
```
I'm not sure if that means it is making some sort of api call to that site? If so then it is the plugin but idk what exactly it's doing..

**Comment by pedromassangocode** [comment] 2021-05-03 11:45
Hi @letto4135 
I suggest you to report on the plugin's repository!
