### ISSUE TITLE
MD5 compute hash file stronger slow in release mode

### ISSUE THREAD

**Issue by Thetyne** [flutter/flutter#24906] opened 2018-12-01 20:42 UTC
I download a 50MB file inside flutter application. Android OS.
I suprised that compute MD5 hash is very slow.

in debug mode : MD5 hash take 2 seconds.
in release mode (flutter build apk) : MD5 hash take 1 minute 15 seconds.

## Steps to Reproduce

Code:
```dart
Future<String> calculateMD5SumAsync(String filePath) async
  {
    String ret = "";
    var file = new File(filePath);
    if (await file.exists())
    {
      try
      {

        var hash = await md5.bind(file.openRead()).first;
        ret = hex.encode(hash.bytes).toUpperCase();
      }
      catch (exception)
      {
        logger.severe("Unable to evaluate the MD5 sum :", exception);
        return null;
      }
    }
    else
    {
      logger.warning("'" + filePath + "' doesn't exits so unable to evaluate its MD5 sum.");
      return null;
    }
    return ret;
```

## Logs

flutter analyze
Analyzing application...
No issues found! (ran in 5.3s)

```
flutter doctor -v
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [version 10.0.17134.407], locale fr-FR)
    • Flutter version 0.11.13 at C:\flutter_sdk\flutter
    • Framework revision 58c8489fcd (2 days ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • COL L29 • CLCDU18425007412 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by Thetyne** [comment] 2018-12-01 20:43
i try with other android device. i obtain same issue

**Comment by mraleph** [comment] 2018-12-02 17:34
@Thetyne is `md5` from [`package:crypto`](https://pub.dartlang.org/packages/crypto) or do you use some other package? 

Is `flutter run --release --target-platform android-arm64` any faster?

**Comment by Thetyne** [comment] 2018-12-02 17:37
yes, i use md5 from package crypto.

crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"

**Comment by Thetyne** [comment] 2018-12-02 17:50
Yes, with  the command "flutter run --release --target-platform android-arm64", the MD5 copute hash is fast.

Do i need always compile with arm64?

**Comment by mraleph** [comment] 2018-12-02 17:54
Thanks for checking! 

> Do i need always compile with arm64?

Unfortunately if you are targeting older phones you can't limit yourself to just ARM64. 

I just wanted to verify that this is the same issue. I think AOT performance on this sort of code on ARM32 should be considerably better with HEAD Dart (not yet rolled into Flutter). I will check tomorrow. 

However it is still far from perfect - further improvements are tracked in https://github.com/dart-lang/sdk/issues/34473

**Comment by Thetyne** [comment] 2018-12-03 11:15
Ok, i am waiting for it

**Comment by mraleph** [comment] 2018-12-04 22:48
@Thetyne the Dart has not been rolled in Flutter because those rolls were suspended at least until Dec 10th. I will update this issue when you can try again.

**Comment by Thetyne** [comment] 2018-12-04 22:50
@mraleph ok, thanks for this response

**Comment by NBTX** [comment] 2018-12-14 00:05
It seems this package is also affected by the same issue: https://github.com/Erly/dbcrypt

**Comment by NBTX** [comment] 2019-01-06 00:38
Are we expecting the PR anytime soon?
I don't mean to rush - we just might have to consider some alternative methods if there isn't a guarantee for the PR.

**Comment by mraleph** [comment] 2019-01-07 09:50
There is still currently around 3.5x difference on `master` between debug and release mode, according to my measurements. I am getting the following on my ARM32 device for MD5 hash computation over 5MB array:

```dart
import 'package:flutter/widgets.dart';
import 'package:crypto/crypto.dart';

void main([List<String> args]) {
  final alwaysTrue = (args?.length != 42);
  final data = alwaysTrue ? Uint8List(5 * 1024 * 1024) : File('whatever').readAsBytesSync();
  for (var i = 0; i < data.length; i++) {
    data[i] = i;
  }

  final sw = Stopwatch()..start();
  print("START {{{");
  print("${data.length ~/ (1024 * 1024)} mbytes hashed to ${md5.convert(data)}");
  print("}}} DONE IN ${sw.elapsedMilliseconds} ms.");
}
```

- In JIT mode hash is computed in ~800 ms.
- In AOT mode hash is computed in ~2700 ms.

@sjindel-google could you take a look at the hot spot? I suspect AOT is suffering from poor representation selection and inability to inline `List<int>` accesses.

**Comment by mraleph** [comment] 2019-01-07 09:51
also /cc @aartbik

**Comment by NBTX** [comment] 2019-01-12 17:07
> @NBTX have you tried `dev` channel? (`flutter channel dev`)

I'm unable to build my app using the dev channel. Some of the dependencies don't build correctly but I'll try isolating the problem code into a new project on the dev channel.

**Comment by sjindel-google** [comment] 2019-01-17 12:04
I've identified the regression locally, between MD5 performance on JIT vs AOT.

I'm working on improvements to arithmetic devirtualization and unboxing which dramatically improves MD5 performance on JIT and AOT. Unfortunately this work is delayed by some issues in our range analysis, but we can expect to the improvements to land in the Dart SDK within a few weeks.

**Comment by sjindel-google** [comment] 2019-01-22 12:46
I've landed improvements in the Dart SDK to both JIT and AOT performance of MD5. On my Nexus 5X, the performance of MD5 in AOT mode is now faster than the original JIT performance.

**Comment by mraleph** [comment] 2019-03-21 10:22
The original problem with JIT vs AOT discrepancy has been solved by @sjindel-google 
 
```
» flutter run --debug --target-platform android-arm
I/flutter (10031): START {{{
I/flutter (10031): 5 mbytes hashed to 006a88ed7d5826af90d38dba4666fd89
I/flutter (10031): }}} DONE IN 570 ms.

» flutter run --release --target-platform android-arm
I/flutter (10145): START {{{
I/flutter (10145): 5 mbytes hashed to 006a88ed7d5826af90d38dba4666fd89
I/flutter (10145): }}} DONE IN 530 ms.
```

Let us know if things are still not fast enough.

**Closed by mraleph** 2019-03-21 10:22 UTC
Labels: dependency: dart, engine, severe: performance
