### ISSUE TITLE
Flutter DevTools not showing Network response on iOS device (since 3.7 update)

### ISSUE THREAD

**Issue by nizwar** [flutter/flutter#120164] opened 2023-02-07 08:09 UTC
This happens since I upgrade flutter to 3.7.0, and it seems like it doesn't get a touch on the 3.7.1 update, 

Request network connection with DIO's latest plugin, it shows the list of requests, (overview and headers tab were OK), but on the response tab, it doesn't show anything.

Happened only on iOS devices (including the simulator) no matter if i running current apps or create new project, on android it's working really fine.

![Screenshot 2023-02-07 at 14 58 57](https://user-images.githubusercontent.com/33113137/217186496-04c6baa7-f924-481b-b102-5a1595e0a812.png)
![Screenshot 2023-02-07 at 14 58 51](https://user-images.githubusercontent.com/33113137/217186529-d3be32a0-c75b-4ef2-af49-22aaf73bf0d8.png)

**Expected results:** 
I can see responses either it was JSON or HTML from any network requests just like when I do debug with android devices

**Actual results:** 
Blank on the response tab

(Code samples and logs are not included because it's not related to the issue)

**Comment by exaby73** [comment] 2023-02-07 10:24
Hello @nizwar. I cannot reproduce this issue with stable or master, testing both on a simulator and a physical 12 pro max. Here's the code I used

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? response;

  void _requestFromApi() {
    get(Uri.parse('https://jsonplaceholder.typicode.com/posts/1')).then(
      (value) => setState(
        () => response = value.body,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title)
      ),
      body: Center(
        child: Text(response ?? 'Empty'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _requestFromApi,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

**Comment by tek4fun** [comment] 2023-02-09 01:34
I got this problems on both my two Mac M1

**Comment by PiN73** [comment] 2023-02-09 02:42
Same on iOS simulator

```
Flutter 3.7.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 32fb2f948e • 2023-02-08 07:30:10 -0800
Engine • revision f40b73f8a4
Tools • Dart 2.19.2 • DevTools 2.20.1
```

&nbsp;| Android emulator | iOS simulator
-|:-:|:-:
Request sent to server | yes | yes
Response received | yes | yes
Request Overview shown in DevTools | yes | yes
Request Headers shown in DevTools | yes | yes
Response Headers shown in DevTools | yes | yes
Request Body in DevTools | yes | **empty**
Response Body in DevTools | yes | **empty**

So the problem seems to be with DevTools 2.20.1 and iOS

**Comment by PiN73** [comment] 2023-02-09 03:10
Issue in DevTools repository: https://github.com/flutter/devtools/issues/5194

**Comment by exaby73** [comment] 2023-02-09 07:04
Since this issue is related to devtools and as per https://github.com/flutter/flutter/issues/120164#issuecomment-1423560608, it's already raised there, I am closing this issue. Thank you

**Closed by exaby73** 2023-02-09 07:04 UTC
Labels: waiting for customer response, in triage
