### ISSUE TITLE
ReorderableListView throws error on reorder list items

### ISSUE THREAD

**Issue by samarthagarwal** [flutter/flutter#21829] opened 2018-09-13 18:35 UTC
I am trying to create a `ReorderableListView` with items. These items are either `Containers` or `Dismissibles` (with child as `ListTile`) depending on certain conditions. The data is being retrieved from Cloud Firestore and a list of widgets is then created which is used to render the `ReorderableListView`. The `onReorder` function is very simple as shown below.

```
reorder(oldIndex, newIndex) {
    if (newIndex > oldIndex) {
      newIndex -= 1;
    }

    setState((){
        final Widget item = tiles.removeAt(oldIndex);
        tiles.insert(newIndex, item);
    });
}
```
`tiles` is the list of Widgets as explained above.
It works fine as long as we try to move an item in the list from a lower index to a higher index. As soon as we try to move an item up in the list, i.e., higher index to a lower index, it throws the error.

`Multiple widgets used the same GlobalKey.`

![Screenshot](https://i.imgur.com/SHayyOX.png)

## Steps to Reproduce

1. Create a ReorderableListView with different widgets as children.
2. Implement the `onReorder` as quoted above.
3. Try moving an item from a higher index to a lower index (up in the list).

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LongPressDraggable<Key>(state:
flutter: _DraggableState<Key>#e8a65):
flutter: Multiple widgets used the same GlobalKey.
flutter: The key [GlobalObjectKey ValueKey<String>#0ecff] was used by multiple widgets. The parents of those
flutter: widgets were:
flutter: - Listener(listeners: [down], behavior: deferToChild, renderObject: RenderPointerListener#f9529
flutter:   relayoutBoundary=up4 NEEDS-LAYOUT)
flutter: - Listener(listeners: [down], behavior: deferToChild, renderObject: RenderPointerListener#e8933
flutter:   relayoutBoundary=up3)
flutter: A GlobalKey can only be specified on one widget at a time in the widget tree.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      GlobalKey._debugReserveFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:172:11)
flutter: #1      GlobalKey._debugReserveFor (package:flutter/src/widgets/framework.dart:190:6)
flutter: #2      Element.updateChild.<anonymous closure> (package:flutter/src/widgets/framework.dart:2693:13)
flutter: #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2696:6)
flutter: #4      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #14     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #18     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
flutter: #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #51     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
flutter: #52     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
flutter: #53     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
flutter: #54     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1659:58)
flutter: #55     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:728:15)
flutter: #56     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1659:13)
flutter: #57     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
flutter: #59     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
flutter: #61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
flutter: #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
flutter: #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #68     _invoke (dart:ui/hooks.dart:128:13)
flutter: #69     _drawFrame (dart:ui/hooks.dart:117:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing jesuskids...                                           
No issues found! (ran in 2.7s)
```

```
samarthagarwal$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.2 17C205, locale en-IN)
    • Flutter version 0.7.3 at /Users/samarthagarwal/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/samarthagarwal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/samarthagarwal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone X • 80AF0226-FD88-4237-9639-ACF2CB8C3D37 • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by samarthagarwal** [comment] 2018-09-13 18:51
Looks like an added delay of 20-50 milliseconds fixed the issue.

```
reorder(oldIndex, newIndex) {
    if (newIndex > oldIndex) {
      newIndex -= 1;
    }

    Future.delayed(Duration(milliseconds: 20), (){
      setState(() {
        final Widget item = tiles.removeAt(oldIndex);
        tiles.insert(newIndex, item);
      });
    });
}
```

**Comment by zoechi** [comment] 2018-09-14 07:12
Are you using `GlobalKey`s for items in the list?

**Comment by samarthagarwal** [comment] 2018-09-14 08:43
Yes, each item in the `tiles` list (either `Dismissible` or `Container`) has a unique `GlobalKey`. I have ensured that the keys are unique by logging them to the console. I have also tried using `Key` instead of using `GlobalKey`. But the error exists.

PS: The `GlobalKey`s/`Key`s are the document ids of the documents from Cloud Firestore, hence they are always unique.

**Comment by zoechi** [comment] 2018-09-14 08:46
`GlobalKey` is expensive and discouraged. 
What are you using them for?

Can you please provide a runnable minimal reproduction (`main.dart`)?

**Comment by zoechi** [comment] 2018-09-25 16:28
The problem is caused by building widgets in advance and reusing them instead of rebuilding them every time in `build()`

```dart
import 'package:flutter/material.dart';
//import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async';
import 'dart:convert';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Firebase',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage() : super();

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
//  final cloudFirestore = Firestore.instance;
  List<int> items = [];
  List<dynamic> programItems = [];

  bool programItemsLoaded = false;

  Future getProgramsItems() async {
    programItems = json.decode(
        '[{"documentID": "001_ABC", "program_item_title": "Activity"}, {"documentID": "002_ABC", "program_item_title": "Connect with Others"}, {"documentID": "003_ABC", "program_item_title": "Bible Story"}, {"documentID": "004_ABC", "program_item_title": "Discussion"}, {"documentID": "005_ABC", "program_item_title": "Prayer"}, {"documentID": "006_ABC", "program_item_title": "Welcome"}]');

    makeTiles();

    this.setState(() {
      programItemsLoaded = true;
    });

    return programItems;
  }

  makeTiles() {
    items = [];

    for (int i = 0; i < programItems.length; i++) {
      items.add(i);
//      var item = programItems[i];
//
//      print(i.toString() + " " + item["documentID"]);
//
//      ListTile tile = ListTile(
//        key: Key(item["documentID"]),
//        title: Text(item["program_item_title"]),
//      );
//
//      tiles.add(tile);
    }
  }

  ListTile makeTile(int index) {
    var item = programItems[index];
    return ListTile(
      key: Key(item["documentID"]),
      title: Text(item["program_item_title"]),
    );
  }

  onReorder(oldIndex, newIndex) {
    if (newIndex > oldIndex) {
      newIndex -= 1;
    }

    setState(() {
      final int item = items.removeAt(oldIndex);
      items.insert(newIndex, item);
    });
  }

  @override
  void initState() {
    super.initState();
    getProgramsItems();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: programItemsLoaded == false
          ? Container(
              child: Center(
                child: Text("Loading..."),
              ),
            )
          : ReorderableListView(
              children: items.map(makeTile).toList(),
              onReorder: (oldIndex, newIndex) {
                onReorder(oldIndex, newIndex);
              },
            ),
    );
  }
}
```

**Comment by zoechi** [comment] 2018-09-25 16:29
Thanks for the great reproduction BTW!

**Comment by samarthagarwal** [comment] 2018-09-25 19:28
Thanks for the code that you shared, Could you please explain the difference between your code and the code in question in a little more detail?

**Comment by zoechi** [comment] 2018-09-26 08:42
The main difference is that in my code a new list of `ListTile()` is created from `makeTile` in every build.

It might still be a bug in the framework that your code causes an exception.

To me it sounds like an issue in the diffing algorithm that tries to figure out which widgets need to be re-rendered.
When the whole list is a new instance Flutter might just drop and re-render all items and therefore not run into the bug. 

@Hixie ?

**Comment by samarthagarwal** [comment] 2018-09-26 08:56
I am not sure if that is what is it. It is possible that what you are saying is correct because of the knowledge of how the framework works that you have, but it does not make sense to me. Setting state also rebuilds the widget tree, and on reorder, I am reordering the elements and recreating the list and then setting the sate. So the list is rebuilt. Moreover, the bug is fixed if I add a slight delay using `Future.delayed` (as small as 20 milliseconds works) inside the reorder method, it works fine. It feels like for a very small duration of time (about 20 ms or so), the reordered items or the lists (old and new) tend to have the same keys. I don't know how flutter handles this internally but that is what the error message indicates to me.

**Comment by AndreHaueisen** [comment] 2018-11-19 19:57
I have the same problem here. I'm using a normal `Key()` that I'm sure it is unique.
Recreating the entire list on every build is very expensive. I hope you guys can fix it.

**Comment by lakshyab1995** [comment] 2019-01-28 13:32
> Looks like an added delay of 20-50 milliseconds fixed the issue.
> 
> ```dart
> reorder(oldIndex, newIndex) {
>     if (newIndex > oldIndex) {
>       newIndex -= 1;
>     }
> 
>     Future.delayed(Duration(milliseconds: 20), (){
>       setState(() {
>         final Widget item = tiles.removeAt(oldIndex);
>         tiles.insert(newIndex, item);
>       });
>     });
> }
> ```

I am also facing the same issue i.e Multiple widgets used the same GlobalKey.
I have verified the id of global keys also by assigning each key a debug label, every id is unique.
By adding some millisecond delay before removing and inserting at new position in onReorder works for me.

**Comment by incker** [comment] 2019-09-08 00:40
Is it serious?

still no closing bug in a year?
only adding delay to fix??

**Comment by QB3L** [comment] 2019-09-15 23:05
Is the delay the accepted way of doing this right now?

**Comment by aqwert** [comment] 2019-09-18 23:18
Just came across this and what solved for me was that the Key object also needs to be recreated rather than captured upfront on the creation of the page/widget.

**Comment by QB3L** [comment] 2019-09-19 01:07
@aqwert you mind showing how us how you did it? Curious about your approach. Did you went with the approach of creating cells on every re-build? Or perhaps loop through the already created ones and assign new keys or some other better approach perhaps?

**Comment by aqwert** [comment] 2019-09-23 01:24
The widgets themselves are new for each build. In the example above it is new ListTile in each build. What would not work is if you cache the keys in the stateful widget and then reused them on the newly built ListTile. The key also had to be a new instance on the build.

**Comment by andymstone** [comment] 2019-10-23 10:13
On the beta version of flutter at least, @zoechi's revised code in https://github.com/flutter/flutter/issues/21829#issuecomment-424412362 only works for dragging items down the list - if I drag an item higher up the list I get the 'multiple widgets used the same GlobalKey' exception.  

My flutter doctor:
```
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version
    10.0.17763.805], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)
```

**Comment by PeteSwad** [comment] 2019-11-08 13:52
I changed line347 in reorderable_list.dart
from  `final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(toWrap.key);`
to `final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(UniqueKey());`
the exception stopped and dragging an item up the list worked ok.

I dont understand the reorderable_list.dart code enough to know if the change has some knockon effects though.

**Comment by incker** [comment] 2019-11-08 14:11
> I changed line347 in reorderable_list.dart
> from `final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(toWrap.key);`
> to `final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(UniqueKey());`
> the exception stopped and dragging an item up the list worked ok.
> 
> I dont understand the reorderable_list.dart code enough to know if the change has some knockon effects though.

Any way it doesn't look like correct solution

**Comment by QB3L** [comment] 2019-11-08 14:46
Submit a PR @PeteSwad ?

**Comment by shihaohong** [comment] 2020-02-12 20:27
I believe this has been fixed with https://github.com/flutter/flutter/pull/49896 (more info in https://github.com/flutter/flutter/issues/43780). It turns out that this was a result of a problem with the `GlobalKey` detection algorithm. 

I tested it in `stable` and was able to reproduce the error, but it seems to be okay in `master`. I will close the issue for now, but if it still occurs in `master`, please feel free to re-open the issue!

**Closed by shihaohong** 2020-02-12 20:27 UTC
Labels: f: material design, f: scrolling, framework, severe: crash

**Comment by klaszlo8207** [comment] 2020-05-03 18:52
any new on this? Is it fixed?
