### ISSUE TITLE
[CupertinoDatePicker] iOS-style DatePicker in date mode is distorted if its width is high

### ISSUE THREAD

**Issue by zengraf** [flutter/flutter#74500] opened 2021-01-22 16:04 UTC
## Steps to Reproduce

Tested on `1.26.0-1.0.pre-dev`
1. Run `flutter create bug`.
2. Replace `MyHomePage` class with this code:
```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlineButton(
          child: Text("Show DatePicker"),
          onPressed: () {
            showCupertinoModalPopup(
              context: context,
              builder: (_) => Container(
                height: 250,
                color: Colors.white,
                child: CupertinoDatePicker(
                  onDateTimeChanged: (_) {},
                  mode: CupertinoDatePickerMode.date,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

**Expected results:** 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/23504276/105513259-6312dc00-5cd2-11eb-805a-57cd2fe9ec5e.png">

**Actual results:** 

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/23504276/105513738-f6e4a800-5cd2-11eb-9d17-b8e6a0ff3f96.png">

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/23504276/105513389-8b9ad600-5cd2-11eb-9be0-f3117a83c510.png">

<details>
  <summary>Logs</summary>

```
```

```
Analyzing bug_datepicker...
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.26.0-1.0.pre at
      /Users/zengraf/.asdf/installs/flutter/1.26.0-1.0.pre-dev
    • Framework revision 63062a6443 (6 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zengraf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/zengraf/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/zengraf/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 9E677C17-37B2-4E6B-BF9C-977D6E1B38D9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by zengraf** [comment] 2021-01-22 16:07
Duplicate of #54241

**Comment by TahaTesser** [comment] 2021-01-25 08:23
Hi @zengraf 
Closing as duplicate of https://github.com/flutter/flutter/issues/54241
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-25 08:23 UTC
