### ISSUE TITLE
Framework does not handle key events sent by iOS simulator ( Xcode 12.2 )

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68741] opened 2020-10-21 22:11 UTC
Currently it looks like the framework does not handle iOS key events (https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/services/raw_keyboard.dart#L346). This causes the terminal to fill up with errors when trying to hot reload/restart.

```
An Observatory debugger and profiler on iPhone SE (2nd generation) is available at: http://127.0.0.1:59659/-Rhr2AmeKQM=/
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: Unknown keymap for key events: ios
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new RawKeyEvent.fromMessage (package:flutter/src/services/raw_keyboard.dart:346:9)
flutter: #1      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:595:43)
flutter: #2      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: #3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:47)
flutter: #4      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
flutter: #5      _invoke3.<anonymous closure> (dart:ui/hooks.dart:274:15)
flutter: #9      _invoke3 (dart:ui/hooks.dart:273:10)
flutter: #10     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Unknown keymap for key events: ios
flutter: Another exception was thrown: Unknown keymap for key events: ios
```

**Comment by DanielEdrisian** [comment] 2020-10-21 22:50
I'm experiencing the same issue

**Comment by xster** [comment] 2020-10-22 15:26
I can reproduce. Seems like touch handling stopped working altogether on simulator. Even on iOS 13.

**Comment by gspencergoog** [comment] 2020-10-22 17:34
@xster Touch handling?  Or just key events?

**Comment by gspencergoog** [comment] 2020-10-22 17:39
My suspicion is that because we merged the [engine side](https://github.com/flutter/engine/pull/20972) of this change, but not [the framework side](https://github.com/flutter/flutter/pull/65193) (because the tree was then closed), perhaps there were undesired side effects. I haven't tested that hypothesis yet, though.

**Comment by gspencergoog** [comment] 2020-10-22 17:44
The fix could be as simple as merging the framework side, which I will do anyhow as soon as the tree is open.

**Comment by xster** [comment] 2020-10-22 18:01
Touch handling is broken as well

**Comment by gspencergoog** [comment] 2020-10-22 18:07
OK, I'm able to fix the key event problem by just applying the framework side of the changes.  I wasn't able to reproduce the touch handling part of the problem, though.  Perhaps it's another issue?

**Comment by gspencergoog** [comment] 2020-10-22 18:07
How are you reproducing the touch handling part of the problem?

**Comment by xster** [comment] 2020-10-22 18:19
doh! sorry, false alarm from me. It wasn't responding but it was actually that my simulator was frozen :S
I cannot reproduce on master head. Tentatively lowering back to P4. 

@DanielEdrisian were you seeing issues with touch handling transmissions in the comparison tool or was it key entries?

**Closed** 2020-10-22 20:33 UTC
Labels: P4, a: text input, framework, platform-ios
