### ISSUE TITLE
[google_maps_flutter] Update minimum GoogleMaps dependency to a version that supports ARM simulators

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#94491] opened 2021-12-01 19:54 UTC
GoogleMaps 6.0 supports ARM simulators.  
https://cloud.google.com/blog/products/maps-platform/announcing-version-60-maps-and-places-sdks-ios

Adopt the dependency in `google_maps_flutter`.
https://github.com/flutter/plugins/blob/2a236e9fd9bb1a35dd9572763f04faac2351840f/packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec#L20

Revert workaround from https://github.com/flutter/plugins/pull/4209

**Comment by stuartmorgan** [comment] 2021-12-01 20:00
This is tricky for the reasons discussed in https://github.com/flutter/flutter/issues/86820

If we don't pin, then we can't safely remove the workaround. If we do pin, we drop support for everything before iOS 12.

**Comment by wverhoeven** [comment] 2023-02-19 23:27
All devices that support iOS 11 can support iOS 12. iOS 11 has been unsupported by Apple for almost 5 years now and the market share is minuscule.

google_maps_flutter has been long awaiting an upgrade and supporting iOS 11 shouldn't be holding it up.

**Comment by stuartmorgan** [comment] 2023-02-20 02:08
> All devices that support iOS 11 can support iOS 12. iOS 11 has been unsupported by Apple for almost 5 years now

Our plugins follow [Flutter support](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms), not OS vendor support.

The fact that a device can be updated doesn't mean that everyone actually updates, and the application developers using Flutter can't control whether end users update their devices.

> google_maps_flutter has been long awaiting an upgrade

Given that the plugin is currently structured such that you will get the newest SDK that is compatible with your application's target version, I'm not sure what you mean by "an upgrade". Please file an issue describing the functionality you want that is not currently available.

**Comment by lababiba1** [comment] 2023-03-29 11:15
@stuartmorgan all we want is just a normal scrolling on ios simulator. Issues are applied above.

**Comment by lababiba1** [comment] 2023-03-29 11:18
> Plugin breaks whole app scroll.
> P4

**Comment by stuartmorgan** [comment] 2023-03-29 14:14
The issue is that `pub` doesn't have any way to express native OS version dependencies, so it's not just that doing this would drop iOS 11 support, it's that it would **break compilation** for everyone using this plugin who is targetting iOS 11 with their app—which is everyone who hasn't changed the default set by `flutter` (likely the large majority of clients).

The options I see are:
- Wait for Flutter to drop iOS 11 support (at which point we can just change the Flutter SDK minimum, so that the resolver will take care of it silently).
- Do a breaking version change to `google_maps_flutter`, which is disruptive for everyone.

If anyone has suggestions for other options that don't cause a bunch of people's builds to suddenly break, we can certainly consider them.

**Comment by stuartmorgan** [comment] 2023-03-29 14:17
In the meantime, as a workaround for anyone who needs to test on an ARM simulator, you could make a trivial fork of `google_maps_flutter_ios` that removes [this line](https://github.com/flutter/packages/blob/a24cc2e692473a4b769f0767f39a10968d26a91e/packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec#L25) and changes [this line](https://github.com/flutter/packages/blob/a24cc2e692473a4b769f0767f39a10968d26a91e/packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec#L23) from `11.0` to `12.0`.

Then you would just add a [dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) to your app's pubspec.yaml to [depend on your fork via git](https://dart.dev/tools/pub/dependencies#git-packages) when testing.

**Comment by Rexios80** [comment] 2023-09-01 16:36
I was able to fix this with the following in my `Podfile`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
```

**Comment by stuartmorgan** [comment] 2023-09-01 16:42
> ```ruby
>     target.build_configurations.each do |config|
>       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
> ```

I would very strongly recommend against anyone copying this code; blindly stomping the deployment target of every plugin is almost certainly going to cause hard-to-find problems later. E.g., if you at some point add a plugin that actually requires iOS 14+, instead of getting a message that will indicate the plugin doesn't work with your app, you'll get random compilation failures inside the plugin (and if you then report them to the plugin author because you don't realize that it's because you added this code to your project months ago and forgot, they will be very confused).

**Comment by Rexios80** [comment] 2023-09-01 16:55
Thank you for pointing that out. We added that line a looooooong time ago to silence warnings from plugins targeting lower iOS versions. Is something like this less sinful?

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      if target.name == 'google_maps_flutter_ios'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
      end
    end
  end
end
```

**Comment by AhmedLSayed9** [comment] 2023-10-24 01:31
> In the meantime, as a workaround for anyone who needs to test on an ARM simulator, you could make a trivial fork of `google_maps_flutter_ios` that removes [this line](https://github.com/flutter/packages/blob/a24cc2e692473a4b769f0767f39a10968d26a91e/packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec#L25) and changes [this line](https://github.com/flutter/packages/blob/a24cc2e692473a4b769f0767f39a10968d26a91e/packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec#L23) from `11.0` to `12.0`.
> 
> Then you would just add a [dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) to your app's pubspec.yaml to [depend on your fork via git](https://dart.dev/tools/pub/dependencies#git-packages) when testing.

This workaround still doesn't solve the broken listViews scroll behavior.

**Comment by stuartmorgan** [comment] 2024-01-04 18:24
I have a PR ready to go for this once the `flutter` change to require 12.0 reaches `stable`.

**Comment by jmagman** [comment] 2024-01-17 06:30
Ugh actually GoogleMaps 6.0 doesn't support arm simulators in CocoaPods.  Looks like it started vending xcframeworks in 7.3, which requires iOS 13.
7.2:
https://github.com/CocoaPods/Specs/blob/c7fdc15bea18f1945ace4333897997ed3b9957cf/Specs/a/d/d/GoogleMaps/7.2.0/GoogleMaps.podspec.json#L379-L380
7.3:
https://github.com/CocoaPods/Specs/blob/c7fdc15bea18f1945ace4333897997ed3b9957cf/Specs/a/d/d/GoogleMaps/7.3.0/GoogleMaps.podspec.json#L379-L380

The 6.0 announcement says the xcframeworks are in beta and gives manual instructions for how to install it.

**Comment by stuartmorgan** [comment] 2024-01-17 18:26
Hm, so is this a Cocoapods-only problem at this point? Because I'm able to locally build and run the `ios12` example without issue (using Xcode 15.1). I didn't notice that it was still running the actual `Runner` app as an intel process (which I do see in the build logs and Activity Monitor now that I'm looking for it) since what I was expecting to see if removing that workaround failed was a build failure.

If it no longer affects plugin clients, and only affects podspec validation, we could consider just hacking around that for now.

**Comment by jmagman** [comment] 2024-01-17 18:52
Using a x64-only simulator plugin hasn't been a build problem since https://github.com/flutter/flutter/pull/87362.

The issue is that using the old GoogleMaps version without ARM simulator support forces the simulator to run as an Intel process.  And that's buggy https://github.com/flutter/flutter/issues/112244 (and others linked to this issue).  We could hack around the podspec validation, or just exclude the google_maps_flutter plugin from that validation.

**Comment by stuartmorgan** [comment] 2024-01-17 20:02
> Hm, so is this a Cocoapods-only problem at this point? Because I'm able to locally build and run the `ios12` example without issue (using Xcode 15.1).

It turns out that this is because we still had example-project-level hacks to exclude arm64 from before the `flutter`-level workaround went in, so my tests weren't valid at all 🙁. Builds of `ios12` fail with the current podspec once I remove those.

> Using a x64-only simulator plugin hasn't been a build problem since #87362.

I've remembered the critical thing here though: old versions of `GoogleMaps` *don't declare that they don't support arm64*, so that tool check doesn't work. Which is why you added the annotation at the plugin level in the first place.

So I need to revert the podspec change and re-publish.

**Comment by stuartmorgan** [comment] 2024-01-17 21:33
Now that that's resolved, looking forward to how to fix this given what we now know that iOS 13 is the minimum, not 12, revisiting [my earlier comment](https://github.com/flutter/flutter/issues/94491#issuecomment-1488707303) the options are:

1. Wait for Flutter to drop iOS 12 support (at which point we can just change the Flutter SDK minimum, so that the resolver will take care of it silently).
2. Wait for [Provide better error message when a plugin requires a min iOS version higher than the app #113762](https://github.com/flutter/flutter/issues/113762) to reach stable (it will be in the next major stable release, as current stable is 3.16, and the first beta it was in was 3.17), and set the min Flutter version to that version, so that there's a useful error message.
3. Do a breaking version change to `google_maps_flutter`, which is disruptive for everyone.

Given that (2) should be available soon, I think we can rule out (3). At that point it's a question of which is worse for developers using `google_maps_flutter`:
* having to do [a workaround](https://github.com/flutter/flutter/issues/94491#issuecomment-1488713501) to get better simulator behavior, or
* being forced to drop iOS 12 support in their application.

**Comment by stuartmorgan** [comment] 2024-01-18 02:06
Note to future selves: when we land this, we should also remove the remaining example-app-level `EXCLUDED_ARCHS` (on the unit test targets, to force them to match the actual Runner build, so that they succeed).

**Closed** 2024-04-16 18:56 UTC
Labels: platform-ios, p: maps, package, P2, team-ios, triaged-ios
