### ISSUE TITLE
Blank Screen After passing the Column to ListView.builder

### ISSUE THREAD

**Issue by shahryar-cmyk** [flutter/flutter#49108] opened 2020-01-18 10:58 UTC
When I'm trying to wrap the main_screen.dart scaffold body argument to the column/Row widget But only the App Bar Title is showing. Not the Body argument of the Scaffold. I want to add the some other widget in the column/Row view this is why it is essential for me. Please describe how to resolve this issue. I tried wrapping it with container then column/Row but nothing works.
[lib.zip](https://github.com/flutter/flutter/files/4080418/lib.zip)

**Comment by Zazo032** [comment] 2020-01-18 11:21
Duplicate of https://github.com/flutter/flutter/issues/48881, see the comments for the solution

**Comment by shahryar-cmyk** [comment] 2020-01-18 11:22
> Duplicate of #48881, see the comments for the solution

This is not working either

**Comment by Ayoubdesigner101** [comment] 2020-01-18 14:31
#49111

**Comment by shahryar-cmyk** [comment] 2020-01-18 14:38
> #49111

I don't understand the reference you provide can you explain it how my issue is related to this one.

**Comment by iapicca** [comment] 2020-01-20 07:18
Hi @shahryar-cmyk 
This platform is not meant for assistance on personal code.
Can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible **minimal** code sample.
Thank you

**Comment by iapicca** [comment] 2020-02-14 12:57
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-14 12:57 UTC
Labels: waiting for customer response
