### ISSUE TITLE
Could not fetch GradlePrioject . 21K+ problems

### ISSUE THREAD

**Issue by ShineSalt** [flutter/flutter#53090] opened 2020-03-23 11:56 UTC
![image](https://user-images.githubusercontent.com/45146002/77314284-73ae9a80-6d2d-11ea-9ec3-69de91c0540b.png)

**Comment by iapicca** [comment] 2020-03-23 12:06
Hi @ShineSalt 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and a reproducible minimal code sample
(`changenotifierprovider` straight into `runApp`?)

Please refrain from posting pictures if not necessary.
Thank you

**Comment by ShineSalt** [comment] 2020-03-23 12:07
C:\Users\sunuw>flutter run --verbose
[  +19 ms] executing: [D:\2019\Flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +84 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [D:\2019\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +47 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[  +11 ms] executing: [D:\2019\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\2019\Flutter\flutter\] git ls-remote --get-url origin
[  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +104 ms] executing: [D:\2019\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] "flutter run" took 101ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:690:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:285:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by iapicca** [comment] 2020-03-23 12:12
Hi again @ShineSalt 
it looks like there's some problem in your code
`This command should be run from the root of your Flutter project`
could you please provide a reproducible minimal code sample
thank you

**Comment by ShineSalt** [comment] 2020-03-23 12:44
Yes I have done it from the root of the flutter project as well. But the response is same.

**Comment by iapicca** [comment] 2020-03-23 13:27
Hi again @ShineSalt
could you please provide a reproducible minimal code sample
thank you

**Comment by TahaTesser** [comment] 2020-04-17 10:29
Hi @ShineSalt 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-17 10:29 UTC
Labels: in triage, waiting for customer response
