### ISSUE TITLE
Snackbar does not close if dialog is open

### ISSUE THREAD

**Issue by bobatsar** [flutter/flutter#33761] opened 2019-06-03 15:07 UTC
## Steps to Reproduce

If a Snackbar is displayed and at the same time a Dialog is opened, the Snackbar will not disappear after the specified Duration.
If the Snackbar as its own is used, all works as expected.

See the following gist for a small example.
https://gist.github.com/bobatsar/32a7a94d16fa002cb70bae6b4f310168

## Logs

```
flutter analyze
Analyzing flutter_snackbar_test...                                      
No issues found! (ran in 1.6s)

```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale de_DE.utf8)
    • Flutter version 1.5.4-hotfix.2 at /home/xxx/flutter
    • Framework revision 7a4c33425d (vor 5 Wochen), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/xxx/android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/xxx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/xxx/android-studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • HTC U11 life • HT7AY1C00279 • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by SashaKryzh** [comment] 2019-07-03 06:10
Have the same issue.

**Comment by SashaKryzh** [comment] 2019-07-03 06:15
It's my solution for now
`Future.delayed(Duration(seconds: 1), () {
_scaffoldKey.currentState.hideCurrentSnackBar();
        });`

**Comment by tapizquent** [comment] 2020-04-07 23:31
This issue is still happening. Any progress on this?

**Comment by TahaTesser** [comment] 2020-06-05 11:36
duplicate of https://github.com/flutter/flutter/issues/39898

**Closed by TahaTesser** 2020-06-05 11:36 UTC
Labels: f: material design, framework
