### ISSUE TITLE
( AnimatedCrossFade ) crossFadeState have wrong behaviour

### ISSUE THREAD

**Issue by xiabui** [flutter/flutter#130115] opened 2023-07-07 03:57 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello everyone,

I have problems with the code below when I'm trying to show the firstChild. The state.user currently return null, but AnimatedCrossFade always show the secondChild. Thanks and have a nice day!

Flutter version: 3.10.5

### Expected results

Show the firstChild when state.user == null

### Actual results

Always show the secondChild when state.user == null

### Code sample

<details><summary>Code sample</summary>

```dart
Container(
  padding: const EdgeInsets.symmetric(
    vertical: 60,
    horizontal: 16,
  ),
  width: context.screen.width,
  decoration: BoxDecoration(
    color: context.theme.colorScheme.background,
    boxShadow: [
      BoxShadow(
        color: context.theme.shadowColor,
      ),
    ],
  ),
  child: AnimatedCrossFade(
    secondChild: Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        CircleAvatar(
          radius: 60,
          backgroundImage: state.user!.image.isNotEmpty
              ? NetworkImage(
                  '${ApiEndpoint.baseUrl}/${state.user!.image}',
                  headers: Network.headers,
                )
              : null,
        ),
        const SizedBox(
          height: 16,
          width: double.infinity,
        ),
        Text(
          '${state.user!.firstName} ${state.user!.lastName}',
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: context.theme.colorScheme.primary,
          ),
        ),
        Text(
          state.user!.email,
          style: TextStyle(
            fontSize: 14,
            color: context.theme.colorScheme.secondary,
          ),
        ),
      ],
    ),
    firstChild: Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        const CircleAvatar(
          radius: 60,
        ),
        const SizedBox(
          height: 16,
          width: double.infinity,
        ),
        Text(
          'Guest',
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: context.theme.colorScheme.primary,
          ),
        ),
        OutlinedButton(
          onPressed: () => _navigateToPage(const LoginPage()),
          child: Text(context.language.loginTitle),
        ),
      ],
    ),
    crossFadeState: state.user == null ? CrossFadeState.showFirst : CrossFadeState.showSecond,
    duration: const Duration(milliseconds: 300),
  ),
 );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\bvxia\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\bvxia\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJUltimate
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\bvxia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 114.0.1823.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-07-07 09:37
Hi @xiabui 
Your sample code contains an undefined element (`state.user`). For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thank you!

**Comment by xiabui** [comment] 2023-07-07 10:06
Hi @huycozy,

Here is your sample code:
```dart
import 'package:flutter/material.dart';
class User {
  User({required this.name});
  final String name;
}

class BugReport extends StatelessWidget {
  BugReport({super.key});

  User? user; // null value

  @override
  Widget build(BuildContext context) {
    var mediaQuerySize = MediaQuery.of(context).size;

    return Scaffold(
      body: Container(
        padding: const EdgeInsets.symmetric(
          vertical: 60,
          horizontal: 16,
        ),
        width: mediaQuerySize.width,
        decoration: BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black26.withOpacity(0.4),
            ),
          ],
        ),
        child: AnimatedCrossFade(
          firstChild: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const CircleAvatar(
                radius: 60,
              ),
              const SizedBox(
                height: 16,
                width: double.infinity,
              ),
              const Text(
                'Guest',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue,
                ),
              ),
              OutlinedButton(
                onPressed: () => {},
                child: const Text('text'),
              ),
            ],
          ),
          secondChild: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const SizedBox(
                height: 16,
                width: double.infinity,
              ),
              Text(
                user!.name,
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue,
                ),
              ),
            ],
          ),
          crossFadeState: user == null ? CrossFadeState.showFirst : CrossFadeState.showSecond,
          duration: const Duration(milliseconds: 300),
        ),
      ),
    );
  }
}
```

**Comment by huycozy** [comment] 2023-07-07 12:02
Thanks for the update. Your code still has error so I complete it as below. And when I run the sample, it works as expected.  Please try below sample code and confirm this.  

<details>
<summary>Demo</summary>

![Screenshot 2023-07-07 at 18 57 33](https://github.com/flutter/flutter/assets/104349824/95ac9202-079b-43e7-a2b8-eadbc15dce7f)
</details>

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';
class User {
  User({required this.name});
  final String name;
}

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        body: BugReport(),
      ),
    ),
  );
}


class BugReport extends StatelessWidget {

  User? user;

  BugReport({super.key}); // null value

  @override
  Widget build(BuildContext context) {
    var mediaQuerySize = MediaQuery.of(context).size;

    return Scaffold(
      body: Container(
        padding: const EdgeInsets.symmetric(
          vertical: 60,
          horizontal: 16,
        ),
        width: mediaQuerySize.width,
        decoration: BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black26.withOpacity(0.4),
            ),
          ],
        ),
        child: AnimatedCrossFade(
          firstChild: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const CircleAvatar(
                radius: 60,
              ),
              const SizedBox(
                height: 16,
                width: double.infinity,
              ),
              const Text(
                'Guest',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue,
                ),
              ),
              OutlinedButton(
                onPressed: () => {},
                child: const Text('text'),
              ),
            ],
          ),
          secondChild: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const SizedBox(
                height: 16,
                width: double.infinity,
              ),
              Text(
                user?.name ?? "",
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue,
                ),
              ),
            ],
          ),
          crossFadeState: user == null ? CrossFadeState.showFirst : CrossFadeState.showSecond,
          duration: const Duration(milliseconds: 300),
        ),
      ),
    );
  }
}
```
</details>

**Comment by xiabui** [comment] 2023-07-07 17:09
Hi @huycozy,

Thanks for your help. Your code can run perfectly. But can you take a little bit of your time to explain why my code got that exception. My previous code can run without any errors yesterday! Is that AnimatedCrossFade build 2 child before they check the crossFadeState?

Best Regards.

**Comment by huycozy** [comment] 2023-07-10 03:27
Hi,
Your initial sample code used `state.user`, which depends on state value change. Since it's not transparent, I can't verify it. But I would recommend you double-check the data source which could impact state data that leads to wrong behavior you have seen.

Closing the issue as it could be an implementation issue. If you disagree, please write in the comments with more information and I will reopen it for further discussion. Thanks!

**Closed by huycozy** 2023-07-10 03:27 UTC
Labels: in triage
