### ISSUE TITLE
iOS does not provide an API to query whether voice control is turned on

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#76808] opened 2021-02-25 20:12 UTC
iOS adds the new assistive technology called voice control in iOS 13. However, there is currently no API to know whether this service is turned on of off. We currently uses a workaround by adding a callback in [FlutterView isAccessibilityElement] to enable the semantics when it is called.

This is not a perfect solution because we don't know when the voice control is turned off, and the semantics will continue being collected even if it is not needed..

**Comment by timsneath** [comment] 2023-04-12 18:54
Resolving as duplicate of #98502. While this issue is older, the other issue has slightly more detailed information about the rationale, so resolving this one in favor of the other.

**Closed by timsneath** 2023-04-12 18:54 UTC
Labels: platform-ios, a: accessibility, passed first triage
