### ISSUE TITLE
[Codelab Error] Potential error in In App Purchases codelab - Page 11 > App Store Setup > Part 8

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#112965] opened 2022-10-05 18:33 UTC
On [Page 11 > App Store Setup > Part 8](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#10) of the In App Purchases codelab, I believe the documentation should guide developers to select Version 1 notifications. Version 2 notifications return a signed response, which will throw an error in the handleAppStoreServerEvent function.

[Apple Docs](https://developer.apple.com/documentation/appstoreservernotifications/receiving_app_store_server_notifications)

Reference documentation section: 
<img width="770" alt="image" src="https://user-images.githubusercontent.com/59215665/194134356-acfb51d8-16fa-46ab-ab74-347ab5b9c1bf.png">

**Comment by darshankawar** [comment] 2022-10-06 05:34
Closing this as duplicate of https://github.com/flutter/flutter/issues/109976

**Closed by darshankawar** 2022-10-06 05:34 UTC
Labels: in triage
