### ISSUE TITLE
Images picked by image_picker doesn't keep the original extension if File name contain UNICODE Example FileName  —Pngtree—romantic christmas candlelight_5268680.png

### ISSUE THREAD

**Issue by IshankDev** [flutter/flutter#47719] opened 2019-12-24 06:48 UTC
## Steps to Reproduce
![—Pngtree—romantic christmas candlelight_5268680](https://user-images.githubusercontent.com/28293257/71398823-b934cc00-2647-11ea-99b9-32d35d2a7bd4.png)

1. Include the image_picker package
2.  
```
 var img = await ImagePicker.pickImage(source: ImageSource.gallery);
print("Image picker file path - ${img.path}");
```
3. Expecting a .png file, instead of seeing: Image picker path - `/data/user/0/com.eventoshub.app/cache/image_picker5688292166033133018.jpg`

```
flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/ishank/WorkData/flutter
    • Framework revision 27321ebbad (13 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ishank/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7761

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • BND AL10 • 192.168.1.2:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Target Platform:** Andriod
**Target OS version/browser:** Android 9
**Devices:**  Honor 7x (But observed on all devices with specific file)

## Logs

```
Image picker path - /data/user/0/com.eventoshub.app/cache/image_picker5688292166033133018.jpg
```

**Comment by ozzy1873** [comment] 2020-01-26 14:35
pickVideo does the same thing and the filename does not need to have Unicode characters. If I pick the video '/storage/self/primary/Movies/small.mp4', the extension is changed to "jpg". We keep going around and around this issue. I don't understand why it is so difficult to leave the extension unchanged.

**Comment by lzzy12** [comment] 2020-05-15 11:32
Hi is there a workaround for this?

**Comment by radi-cho** [comment] 2020-08-07 13:11
@jonahwilliams @engine-flutter-autoroll @jmagman @dnfield @gspencergoog

**Comment by dnfield** [comment] 2020-08-07 15:07
@radi-cho please do not tag random engineers in issues. In particular one of the names you tagged is not monitored by a human, and the other names you tagged do not work on this plugin much.  This issue is appropriately triaged and will eventually be reviewed.

**Comment by sunnykinger** [comment] 2020-10-23 03:25
has anyone able to find a workaround for this issue?

**Comment by niwatly** [comment] 2020-10-28 02:02
@sunnykinger I switched to [file_picker](https://pub.dev/packages/file_picker).

**Comment by lzzy12** [comment] 2020-10-28 03:53
1 workaround is to downgrade to 0.6.2 but that's not a permanent solution. Better move to file_picker as suggested above

**Comment by Saadkhattak00** [comment] 2021-01-16 23:00
hello every one i need a little help how save image taken from gallery to files i used imagepicker it work fine with camera it SAVE IMAGES but when i take from gallery it does not save image


File _image;
  Future getImageCamera() async {
    final image = await ImagePicker().getImage(source: ImageSource.camera);

    setState(() {
      if (image != null) {
        _image = File(image.path);
      }
    });
  }

  Future getImageGallery() async {
    final appDir = await getApplicationDocumentsDirectory();

    final PickedFile file =
        await ImagePicker().getImage(source: ImageSource.gallery);
    if (file != null) {
      setState(() {
        _image = File(file.path);
       
      });
      // final fileName = basename(_image.path);
      // var i = await File(_image.path).copy("${appDir.path}");
      // print(i.path);
      // final File image = await ImagePicker.pickImage(source: imageSource);


  Future<void> saveImage() async {
    final appDir = await getApplicationDocumentsDirectory();
    final fileName = basename(_image.path);
    print("Image Saved");
    final File savedimage = await _image.copy('${appDir.path}/$fileName');

    setState(() {});
  }

**Comment by pedromassangocode** [comment] 2021-02-10 14:48
This seems to be a duplicate of https://github.com/flutter/flutter/issues/52419. I~m closing this one since https://github.com/flutter/flutter/issues/52419 has more activity and has some linked PRs. For anyone interested in this, please follow up on https://github.com/flutter/flutter/issues/52419.
Thank you

**Closed by pedromassangocode** 2021-02-10 14:48 UTC
Labels: a: assets, p: first party, p: image_picker, plugin
