### ISSUE TITLE
Allow Apps to override MediaQuery

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#86797] opened 2021-07-21 18:05 UTC
Reopening @aloisdeniel issue:
https://github.com/flutter/flutter/issues/33384

I'm working on a way to simulate various device configurations at runtime to preview my apps without the need to change my device.

I achieved that by wrapping my app in a container with a fixed size for the screen resolution, but I would like also to override screen padding (and potentially all `MediaQuery` properties).

The issue is that `WidgetsApp` instantiate a `MediaQuery` from `WidgetsBinding.instance.window`, so I couldn't override the padding easily.

It is doable by making a custom app widget, but it is not very convenient since there's various app implementations (`MaterialApp`, `CupertinoApp`, ...). I could also create a custom `SafeArea` that is based on my own `MediaQuery`, but again it is not very convenient, and having a fork of a built-in widget isn't that great (and I would have to do the same for all `MediaQuery` based widgets).

For testing, It is not that great to have a static variable referenced too...
## Proposal

If a `MediaQuery` is already in the tree, the `WidgetsApp` should use it.

Instead of :

```dart
 return MediaQuery(
      data: MediaQueryData.fromWindow(WidgetsBinding.instance.window),
      child: Localizations(
        locale: appLocale,
        delegates: _localizationsDelegates.toList(),
        child: title,
      ),
    );
```

We could have :

```dart
 return MediaQuery(
      data: MediaQuery.of(context, nullOk: true) ?? MediaQueryData.fromWindow(WidgetsBinding.instance.window),
      child: Localizations(
        locale: appLocale,
        delegates: _localizationsDelegates.toList(),
        child: title,
      ),
    );
```

This way, we could override the default `MediaQuery`.

**Comment by zs-dima** [comment] 2021-07-21 18:06
partly related issue and history: https://github.com/flutter/flutter/issues/86783

**Comment by goderbauer** [comment] 2021-07-28 22:36
As was pointed out in https://github.com/flutter/flutter/issues/33384#issuecomment-497219633, you can use the builder property to inject your own MediaQuery. Why does that not work for you?

**Comment by goderbauer** [comment] 2021-07-28 22:39
This also appears to be a duplicate of https://github.com/flutter/flutter/issues/81293.

**Comment by zs-dima** [comment] 2021-07-29 03:01
@goderbauer thanks for reply
But injection doesn't allow to add MediaQuery as parent widget to wrap MaterialAww widget !
So it could not solve this issue

**Comment by zs-dima** [comment] 2021-07-29 03:02
@goderbauer and it is no open issue about, so I will have to create new issue to keep it open till it will be solved

**Comment by zs-dima** [comment] 2021-07-29 21:30
@goderbauer more over I could not see any #33384 (comment)

**Comment by goderbauer** [comment] 2022-04-13 21:47
We have this property now for exactly this use case: https://master-api.flutter.dev/flutter/material/MaterialApp/useInheritedMediaQuery.html

**Closed by goderbauer** 2022-04-13 21:47 UTC
Labels: framework, proposal, passed first triage, a: layout
