### ISSUE TITLE
How to get the image path in iOS

### ISSUE THREAD

**Issue by RayZhao1998** [flutter/flutter#27533] opened 2019-02-05 09:50 UTC
I use method `getApplicationDocumentsDirectory()` in `path_provider` to get the image path.

However, when I `flutter run` or update my app in AppStore, the path got by `getApplicationDocumentDirectory()` will change and I can't get the image by the path stored before.

**Comment by mcplectrum** [comment] 2019-02-05 21:34
This is probably a duplicate of: https://github.com/flutter/flutter/issues/23957

**Comment by GaryQian** [comment] 2019-02-06 01:21
Closing, as is duplicate. See #23957 for further details.

**Closed by GaryQian** 2019-02-06 01:21 UTC

**Comment by RayZhao1998** [comment] 2019-02-06 01:38
Thanks.
